### ISSUE TITLE
Reproducible issue leveraging notebook opened from folder in a git repo

### ISSUE THREAD

**Issue by danmanrique** [microsoft/azuredatastudio#10016]
Issue Type: <b>Bug</b>

I have the same experience on 3 machines now with the latest Azure Data Studio (Macbook - Catalina, SurfaceBook Win10, Dell T7600 Win10). 
 
I created a notebook, everything works. 
Pushed the notebook into git. 
Opened folder in ADS, via a git repo, and tried to run the notebook again, and unexpected errors occur. 
I click on File->New for a new notebook, using the same connection and I can run the new notebook fine. 

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19603

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz (24 x 1995)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.93GB (46.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by danmanrique** [comment]
![image](https://user-images.githubusercontent.com/8976972/79407942-260e0200-7f68-11ea-9d4c-0c5a0ff35e90.png)
![image](https://user-images.githubusercontent.com/8976972/79407985-3f16b300-7f68-11ea-8e58-47d76a84a1a3.png)

**Comment by chlafreniere** [comment]
Can you detail what errors that you're seeing, @danmanrique? It's a little hard to see from your screenshot.

If you open the Developer Tools (Help --> Toggle Developer Tools), and go to the Console, are there any errors printed there after you repro the issue?

**Comment by chlafreniere** [comment]
Closing issue as we need more info here. Feel free to reopen with more details if this still reproes.
