### ISSUE TITLE
ipynb file is not rendered in Notebook in ADS when opened from File Explorer

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10027]
- Azure Data Studio Version:
Version: 1.17.0-insider (user setup)
Commit: 15fc4517eeaa551f8f352e0fed54c6044d31f530
Date: 2020-04-13T17:32:48.451Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Steps to repro:**
When I set my ADS to be the default program to open ipynb files and I double click on the ipynb file to open it from File Explorer, ADS does not render the notebook (i.e. it stays in json format). 

However, if I open a second ipynb file (by double clicking in File Explorer), the second ipynb file is rendered to notebook in ADS. 

When navigating back to the first ipynb file in ADS, ADS starts opening a new tab with the rendered view of the first ipynb file.

![NotebookRenderingIssue](https://user-images.githubusercontent.com/6405919/79296274-cfcd9000-7e8f-11ea-994b-284a522f2b16.gif)

Note: the error that you see in the gif file occasionally comes up (but not all the time).

**Comment by anthonydresser** [comment]
Out of interest, can you try the same thing for .sql files and see if the query editor shows up or you get a default editor.

**Comment by MsSQLGirl** [comment]
@anthonydresser  - when I double click on .sql files, the Query Editor shows up as expected including the syntax highlight. 
![image](https://user-images.githubusercontent.com/6405919/79596134-dda03280-8094-11ea-988e-5b84baea7c9a.png)

**Comment by chlafreniere** [comment]
Looks like this is a language association issue on startup. Let me get a PR soon and make sure that @anthonydresser can take a look.

**Comment by chlafreniere** [comment]
Fixed by #10055.
