### ISSUE TITLE
Connect button on query editor is not working

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10025]
- Azure Data Studio Version: 
latest master

Steps to Reproduce:
1. make sure you don't have any active connections
2. open a new query window
3. click on the connect button

Expected:
The connection dialog appears

Actual:
nothing happens

**Comment by alanrenmsft** [comment]
@aaomidi very likely to be caused by this PR: https://github.com/microsoft/azuredatastudio/pull/9835
I am testing whether reverting the PR will fix the problem

**Comment by aaomidi** [comment]
Yeah this is being solved by https://github.com/microsoft/azuredatastudio/pull/10026

**Comment by alanrenmsft** [comment]
@aaomidi  nice :)
