### ISSUE TITLE
Can't move Profile editor between split editors

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10068]
1. Create split editor panes
2. Open Profiler - it opens in one pane
3. Attempt to drag editor to other pane

The profiler editor closes and this error appears 

```
Unable to open 'Profiler: sqltools2019-3': Cannot register more than one working copy with the same resource untitled:..
```

(the text isn't cut off - that's what the actual error says)

**Comment by brase** [comment]
I got the same error when trying to open the profiler. 

I am using 1.19.0

**Comment by smartguest** [comment]
Closing as it appears you can drag the profiler window between two split editors currently.
