### ISSUE TITLE
Connection Dialog editable dropdown arrow misaligned

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10063]
RC Build :

![image](https://user-images.githubusercontent.com/28519865/79616973-38e51b80-80bb-11ea-83fa-85d1f7bd0df2.png)

Current Stable Build : 

![image](https://user-images.githubusercontent.com/28519865/79616928-194df300-80bb-11ea-81ec-d4d57b0313f1.png)

**Comment by chlafreniere** [comment]
Discussed during DRI, and doesn't meet the bar for April.
