### ISSUE TITLE
window Authentication

### ISSUE THREAD

**Issue by shivsh1748** [microsoft/azuredatastudio#10079]
Issue Type: <b>Feature Request</b>

it is not working on macos.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 19.3.0

**Comment by Charles-Gagnon** [comment]
Please include any other information that might help us - for example are there any errors that pop up when you try to connect? Can you successfully connect to any machines with windows auth?

I would also suggest going through this doc and making sure you have your environment set up correctly as well : https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-ver15
