### ISSUE TITLE
Search from Jupyter Book viewlet shows error

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10076]
Issue Type: <b>Bug</b>

1. Create a folder with a number of notebook files. Then copy SQL 2019 BDC Guide jupyter book and save it in the same folder.
![image](https://user-images.githubusercontent.com/6405919/79702731-d9724180-825b-11ea-8cff-49bef4ff6228.png)

2. Click on the Search icon on the Book title.
![image](https://user-images.githubusercontent.com/6405919/79702747-ec851180-825b-11ea-8c50-7a99479d7112.png)

3. Type "azdata" on the Search which shows an error: 
![image](https://user-images.githubusercontent.com/6405919/79702766-09b9e000-825c-11ea-9f27-d9573205b29d.png)

If you click away, you'll get to see **files to include**
![image](https://user-images.githubusercontent.com/6405919/79702780-1b9b8300-825c-11ea-93b2-6fc9e94ef239.png)

i.e. ` c:\Temp\RandomNotebooks\Notebook03.ipynb\**\*.md,c:\Temp\RandomNotebooks\Notebook03.ipynb\**\*.ipynb `

4. Search doesn't seem to work - i.e. doesn't return any value. 

**Workaround**:
Changing the **files to include** manually to something else seems to work: ` c:\Temp\RandomNotebooks\**.ipynb`

![image](https://user-images.githubusercontent.com/6405919/79702815-5c939780-825c-11ea-8625-47757634b6dc.png)

Azure Data Studio version: azuredatastudio-rc1 1.17.0-rc1 (370e5219109ec13ea5f811f2fd9707c89d23d9f7, 2020-04-17T19:42:06.447Z)
OS version: Windows_NT x64 10.0.18363

Extensions: none

**Comment by kburtram** [comment]
Discussed in shiproom and approved pending PR review.
