### ISSUE TITLE
Editable dropdowns don't send onValueChanged events when the value was manually updated

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#10082]
Editable dropdowns don't send onValueChanged events when the value was manually updated

Edit:
Actually looks like the issue is less severe than I thought. You have to press Enter for the dropdown value to update. This might be by design so I'll leave this open and we can discuss if this is expected behavior.

**Comment by kburtram** [comment]
Closing older engineering-focused bugs to prioritize customer-facing bugs.
