### ISSUE TITLE
Update ModelView toolbar to use Taskbar

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#10109]
The implementations of the Taskbar and ModelView toolbar are currently quite different, with the Taskbar having Actions as the toolbar items and the ModelView toolbar having ModelView items like buttons and dropdowns as toolbar items. 

There are two options:
1. Update the existing ModelView toolbarContainer to use the Taskbar. The Taskbar has Actions and HTMLElements, so there would need to be a way to convert the toolbarContainer items to those.
2. Create a new ModelView component that is a wrapper around the Taskbar.

Changing the ModelView toolbar to use the Taskbar would allow for consistency so that the style and behavior changes would only need to be made in one place and for code reuse.

**Comment by kburtram** [comment]
Closing older engineering tasks to focus on customer facing issues.  Please reactive if this issue is tracking upcoming planned work.
