### ISSUE TITLE
Feedback Button  Is Pointless

### ISSUE THREAD

**Issue by jkarr** [microsoft/azuredatastudio#10102]
Issue Type: <b>Bug</b>

1: Use the feedback button to report a problem
2: Feedback will get posted on Twitter
3: AzureSupport and AzureDataStudio will think you are talking about a web-service

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19041

**Comment by vickyharp** [comment]
I saw your thread on Twitter. We'll see what we can do to make sure the AzureSupport account knows how to route questions correctly. The AzureDataStudio account is indeed run by this team.

**Comment by kburtram** [comment]
Thanks for opening this issue!  Feedback on twitter is reaching @vickyharp, who is the PM owner for this product.  Please let us know if there are any issues you're encountering using the product that I could assist with.
