### ISSUE TITLE
Unnecessary information logged when verbose logging level is enabled

### ISSUE THREAD

**Issue by PiJoCoder** [microsoft/azuredatastudio#10108]
Issue Type: <b>Bug</b>

In a presentation we saw with ADS a demo was showing Verbose Tracing Level and logging in with a user password caused that password to show as a clear text in the verbose log.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aaomidi** [comment]
https://github.com/microsoft/sqltoolsservice/pull/950

**Comment by aaomidi** [comment]
This should be resolved and I think we have a new SqlToolsService version in release.
