### ISSUE TITLE
Closed tabs persist

### ISSUE THREAD

**Issue by jkarr** [microsoft/azuredatastudio#10101]
Issue Type: <b>Bug</b>

Step 1: With Azure Data Studio (ADS) open, open a bunch of tabs
Step 2: Close ADS
Step 3: Open ADS, all the tabs have persisted (this is good)
Step 4: Delete all the tabs
Step 5: Close ADS
Step 6: Open ADS
Step 7: The tabs deleted in step 4 are back

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (16.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jkarr** [comment]
Some more information.  I was just able to clear all my open tabs and they stayed closed when I re-opened Azure Data Studio.

I closed all tabs, as is my new morning normal, then, instead of doing a new query, I opened a folder.  When I did that, I got a prompt asking me if I wanted to save changes on all the tabs that I had just closed.  I said no, and went on my way.  This time, when I closed and re-opened Azure Data Studio, all my tabs were gone :)  

Perhaps when closing all tabs the save changes dialog isn't prompting properly and so the tabs aren't actually closing.

**Comment by bwilson-cjusd** [comment]
I have been having this exact issue. If I close all the tabs, and open a new one to do some work, then close ADS and open it later, the previous tabs, plus my new ones also are re-opened.

After following your steps outlined of opening a new folder, I made a new folder that I can work in and selected it, the behavior of ADS seems to have been corrected.

**Comment by kburtram** [comment]
Closing this issue since it hasn't repro'ed recently.  Please let us know if you're still impacted by this bug on the current release.
