### ISSUE TITLE
Schema compare preview pane is not fully visible

### ISSUE THREAD

**Issue by Depechie** [microsoft/azuredatastudio#10103]
Issue Type: <b>Bug</b>

I did a schema compare between 2 DB's and when I select a row in the result screen, the preview pane below is not showing all info.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.3.0

</details>

**Comment by Depechie** [comment]
![Screen Shot 2020-04-21 at 14 46 01](https://user-images.githubusercontent.com/351693/79867937-70b3d200-83df-11ea-9ef3-2b80d2e5b4be.png)

**Comment by kisantia** [comment]
@Depechie How big is the window? A current limitation of schema compare is that the height is a maximum of 800 pixels.

**Comment by Depechie** [comment]
I was running Azure data studio on a 25" screen with 2560*1440 resolution full screen.
So the window itself could not have been more than 800. I would guess it was around 100.

**Comment by kisantia** [comment]
@Depechie I'm not able to repro this on my mac with the same build. Does this repro every time and for all rows? If the window is less than 800 pixels tall, there should be a scrollbar on the right side. Is that there or missing?

**Comment by Depechie** [comment]
hey @kisantia seems i can't reproduce either... when I do the compare now, the window is indeed not covering the full height ( guess the 800px limit ). But it is much bigger than when I reported the problem.
So it occured for sure, but I can't reproduce it straight away.

**Comment by kisantia** [comment]
Hmm that's strange, but good it isn't happening anymore. Please reopen this issue if it starts happening again consistently. Thanks!
