### ISSUE TITLE
Azure Data Studio doesn't work reliably when attempting to copy large amounts of data

### ISSUE THREAD

**Issue by jkarr** [microsoft/azuredatastudio#10123]
Issue Type: <b>Bug</b>

Perform a query with roughly 15K results.  Attempt to copy the results to clipboard and Azure Data Studio will hang and eventually crash.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10710U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (12.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
Update the title to encompass some of the related issues duplicated against this issue.  Please look through duplicate issues when resolving this to ensure the overall copy/paste from grid experience is working as expected.
