### ISSUE TITLE
Error while connecting

### ISSUE THREAD

**Issue by Wallie1981** [microsoft/azuredatastudio#10121]
Issue Type: <b>Bug</b>

Occures when opening a SQL file that is GIT controlled, and trying tot connect it to an Azure SQL DB.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (2.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details>Extensions: none

**Comment by kburtram** [comment]
I wasn't able to reproduce a connection error when using a SQL file that was included in a git repo.  Are there any additional repro steps or error logs that may help us narrow down the problem?

**Comment by kburtram** [comment]
I haven't been able to reproduce this.  Please let us know if you're seeing this issue on the latest build.
