### ISSUE TITLE
Duplicated invalidate accounts in Create Firewall account picker list

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10126]
- Azure Data Studio Version: `1.17.0`

Steps to Reproduce:

1. Have some Azure accounts with expired credentials in 1.16.1 (not sure exactly which parts are necessary for repro, but this was my state)
2. Upgrade to 1.17.0
3. Refresh credentials for accounts
4. Log into Azure SQL DB and create firewall rule

Expected: Pick an account and rule created

Actual: Duplicate accounts.  Some in expired and validate state.  Choosing the first Microsoft Account left Create Firewall Rule dialog spinning "in-progress" indefinitely.  Canceling the dialog and trying again, then choosing second Microsoft account worked as expected and server connected.

**Comment by aaomidi** [comment]
Hmm this is the dangling accounts I was talking about where I introduced the "Clear all accounts" as a possible workaround. 

I will look into adding a quick cleanup functionality to get rid of old accounts.

**Comment by aaomidi** [comment]
I'm going to need to open a PR for this. Currently working on it, it's a pretty small change.

**Comment by kburtram** [comment]
Approving based on shiproom discussion.

**Comment by kburtram** [comment]
This appears fixed in current RC build
