### ISSUE TITLE
Issue login with AAD

### ISSUE THREAD

**Issue by marrim-myob** [microsoft/azuredatastudio#10137]
Hi I have downloaded the Azure Data Studio and suddenly stopped working for AAD Logins.

Azure Data Studio Version on Mac: 1.16.1

Here is the errors
  ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
2/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:2280 [Extension Host] (node:5584) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
console.<computed> @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:2280
t.log @ workbench.desktop.main.js:403
$logExtensionHostMessage @ workbench.desktop.main.js:4563
_doInvokeHandler @ workbench.desktop.main.js:4570
_invokeHandler @ workbench.desktop.main.js:4570
_receiveRequest @ workbench.desktop.main.js:4568
_receiveOneMessage @ workbench.desktop.main.js:4567
(anonymous) @ workbench.desktop.main.js:4565
fire @ workbench.desktop.main.js:206
fire @ workbench.desktop.main.js:553
_receiveMessage @ workbench.desktop.main.js:558
(anonymous) @ workbench.desktop.main.js:555
fire @ workbench.desktop.main.js:206
acceptChunk @ workbench.desktop.main.js:551
(anonymous) @ workbench.desktop.main.js:550
t @ workbench.desktop.main.js:561
ZoneDelegate.invokeTask @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:421
Zone.runTask @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:188
ZoneTask.invokeTask @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:496
ZoneTask.invoke @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:485
emit @ events.js:203
addChunk @ _stream_readable.js:295
readableAddChunk @ _stream_readable.js:276
Readable.push @ _stream_readable.js:210
onStreamRead @ internal/stream_base_commons.js:166
/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:2280   ERR No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.
5/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/zone.js/dist/zone-node.js:2280   ERR Cannot read property 'addAccountAction' of undefined: TypeError: Cannot read property 'addAccountAction' of undefined
    at file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:7174:611
    at c.fire (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:206:102)
    at HTMLAnchorElement.<anonymous> (file:///Applications/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:626:746)

**Comment by aaomidi** [comment]
Hi! Is this still an issue with the latest 1.17.1 release?

**Comment by aaomidi** [comment]
I'll close this in favor of #10314 to track the azure auth issues there.

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/issues/10314#issuecomment-627722312
