### ISSUE TITLE
Azure view continually asks for SqlLogin credentials

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10145]
- Azure Data Studio Version: `1.17.0`

Steps to Reproduce:

1. Navigate to a SQL DB in the the Azure view that requires SqlLogin authentication
2. Try to expand the node and then execute commands on child nodes

Expected: If there is existing connection profile for DB in servers everything works with no auth prompts.  If there is no existing connection then you get prompted for auth once and the password is remember for rest of session, if Remember Password is clicked then the password is remember for next sessions too.

Actual: Every action encounters the below error and requires an additional authentication.  AAD MFA is reset as default auth for every action.

![image](https://user-images.githubusercontent.com/599935/80124976-e2a62b80-8545-11ea-88f8-326fbaca0251.png)

**Comment by ransagy** [comment]
I'm pretty sure i still suffer from this (and have for a while when i give ADS another try every now and then) when its marked closed for the April release which is versioned 1.17 despite the OP post here saying it IS happening in 1.17.

Anyway, my scenario is:
1. installed clean 1.17.
2. Add Azure account - get redirected to browser, choose account, close browser window after connection is done.
3. Naviagte the account, subscription, SQL database nodes.
4. Try expanding one of the DB nodes.
5. "Login failed for user: <the default SQL admin user that was created with the DB etc>"

**Comment by rhythmnewt** [comment]
@ransagy I have the same issue with the Azure blade still. It's baffling that both this issue and mine #9525 are marked as fixed but they really are not.

**Comment by ransagy** [comment]
I wonder if we should open a new, specific issue on that - As both our issues respective titles reflect something different. 

The issue specifically is that any action initiated from the Azure view/group of the connections tab always tries to use SqlLogin repeatedly regardless of which authentication was used before.

thoughts @kburtram @Charles-Gagnon ? (as you worked on the other mentioned issue)

**Comment by aaomidi** [comment]
New issues are always appreciated. Sometimes a specific issue ends up being multiple and are marked as closed when a PR is sent out for them.

**Comment by ransagy** [comment]
Done: #10268
