### ISSUE TITLE
How to modify the location of python files installed by default in ads

### ISSUE THREAD

**Issue by dqaudithillstone** [microsoft/azuredatastudio#10168]
- Azure Data Studio Version:

Steps to Reproduce:

1.I want to change the default installation python by ADS ,for exampel :d:\python ，because the c disk space  is not enough

**Comment by chlafreniere** [comment]
For a new python installation, you can specify where Python is installed (including another drive letter).

For existing python installations, that Python can be installed into the folder of your choosing.
