### ISSUE TITLE
Format Error with '\' in SQL code

### ISSUE THREAD

**Issue by NanookSoftware** [microsoft/azuredatastudio#10189]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Charles-Gagnon** [comment]
@NanookSoftware Could you please type out the issue you're seeing? The bug submission form has a max length it can accept to autofill the template.

**Comment by NanookSoftware** [comment]
![image](https://user-images.githubusercontent.com/40308431/80508710-67c68180-8946-11ea-9da7-95f0584606b3.png)

**Comment by NanookSoftware** [comment]
![image](https://user-images.githubusercontent.com/40308431/80508797-7e6cd880-8946-11ea-8695-60b5b7ee5697.png)

**Comment by Charles-Gagnon** [comment]
I'm not sure what the issue is from your screenshot - could you please explain the issue you're having?

**Comment by NanookSoftware** [comment]
OK So I am including 3 images (Code from ADS after last Update - error, Code from ADS with the '\' commented out, code from SSMS)

**Comment by NanookSoftware** [comment]
![image](https://user-images.githubusercontent.com/40308431/80536953-2dbea500-8971-11ea-8227-12f5653b9bd5.png)

**Comment by NanookSoftware** [comment]
![image](https://user-images.githubusercontent.com/40308431/80536963-31eac280-8971-11ea-94d3-b6f30ea8e5ac.png)

**Comment by NanookSoftware** [comment]
![image](https://user-images.githubusercontent.com/40308431/80536977-357e4980-8971-11ea-90ac-67c77caeca8f.png)
