### ISSUE TITLE
Close all tabs without saving

### ISSUE THREAD

**Issue by brunossn** [microsoft/azuredatastudio#10190]
**Is your feature request related to a problem? Please describe.**
When I need to close to many tabs, Azure Data Studio ask me to save for every tab. If I have 20 tabs, I have to click 20 times in "No" button.

**Describe the solution or feature you'd like**
A button "Not to all"

**Describe alternatives you've considered**
A list of opened tabs like Visual Studio does

**Additional context**
![image](https://user-images.githubusercontent.com/1033649/80512744-58e6cb80-8954-11ea-8b9c-3b51c0057f74.png)

**Comment by kburtram** [comment]
@brunossn thanks for the suggestion.  We've had this request a few times.  For some reason, this is the save behavior we picked up from our upstream vscode dependency.  Ideally, we'd get this fixed there and then it would come to us in a future merge.

You can close and not save all editors using the `Close All Editors` button in the File Explorer viewlet (screenshot below).  But I agree, not sure why it doesn't do this when closing all editors from document tab menu.

![image](https://user-images.githubusercontent.com/599935/80543834-9e12f980-8964-11ea-8cf4-323d72fb8c67.png)

**Comment by kburtram** [comment]
Closing based on the current comment.  Thanks for the suggestion!

**Comment by FezVrasta** [comment]
The correct solution is described in this other issue:

https://github.com/Microsoft/vscode/issues/54647#issuecomment-413760045
