### ISSUE TITLE
UI blurred on startup after W10 update

### ISSUE THREAD

**Issue by gsogeek** [microsoft/azuredatastudio#10209]
Issue Type: <b>Bug</b>

When starting the application with hardware GPU enabled, the UI is unusable. Adding the --disable-gpu flag will allow the UI to display properly. This also appears to be affecting VS Code and other Electron-based apps, so it may be an upstream issue with Radeon adapters. _Included System Info was gathered without the --disable-gpu flag._

- With Hardware GPU Enabled: 

![image](https://user-images.githubusercontent.com/348429/80611457-9f95fd80-8a08-11ea-8394-a771a36e2a6a.png)

- With --disable-gpu added:

![image](https://user-images.githubusercontent.com/348429/80611154-3f06c080-8a08-11ea-9493-3ec66d31233f.png)

Azure Data Studio version: azuredatastudio 1.17.0 (b32a48ab73d8914647d33d9684bcb7b48adfe0cc, 2020-04-24T00:21:10.639Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
cms|Mic|0.8.0
dacpac|Mic|1.4.0
datavirtualization|Mic|1.4.0
import|Mic|0.14.0
managed-instance-dashboard|Mic|0.4.1
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.4.0
server-report|Mic|0.2.2
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@anthonydresser any ideas on this one?  Looks like a OS driver issue if I had to guess.

**Comment by anthonydresser** [comment]
Most likely its a electron driver issue if disabling gpu fixes it. vscode is investigating upgrading electron to 8 so that might fix it.

**Comment by anthonydresser** [comment]
not sure how much testing they have done with it, but it doesn't look they have found too much wrong with the upgrade https://github.com/microsoft/vscode/compare/electron-8.0.x so we might be able to make our own upgrade before them if we think we will need a fix before they make a fix.

**Comment by gsogeek** [comment]
I'm doing a bit more testing on the affected devices and there seems to be a common element between electron-based apps and the Radeon driver being delivered in the latest round of Windows Updates... I'm seeing it stabilize and clear up when I remove the driver set, and re-install from AMD (Radeon Software 19.10.24.04) rather than what is delivered by windows update. I'll know more for sure when I run that process on a second affected machine and establish a pattern.

**Comment by gsogeek** [comment]
This is a result of a windows update interacting with a Radeon GPU.
