### ISSUE TITLE
Error signing in to Azure

### ISSUE THREAD

**Issue by rodrigolopes** [microsoft/azuredatastudio#10207]
after opening Azure data studio for first time after upgrade, I try to sign in to Azure and a page opens in a  browser with message 'Failure when retreiving tokens.'
url of the page is:
http://localhost:53248/callback?code=AQABAAIAAAAm-06blBE1TpVMil8KPQ41GqQD5dyOIwVJoyj_8G6l8GzuPZww5DMrtHOerUFIKraLI8E-M_R-r5nxU0Dvt2UJIQ4_iQZpb3l50LWw0d7zdidLlJxwwRDg09pG7twFovazNtrTGNJ_kx5VNJ67yiARhQw7qiP0r5vgQM1qLQSqDMhFLzeBLg92h3L0j63O3jAey76PV0xDVqZhAKULUTnTcuua7sAnqEnhOUYGqI4HgHXZ5uW2L1kdm3-8j1ol9VDhWhkTs7BQtOl48vSAh0asrizF2BCO9sAnsJyxEP7uzxUj81P_fJpxoJXBpdStLUwVLPf156o4qcva67QBtnt9l_ltaxROeShRAX7pJM6Sb0M_8mYKbsQiONdVhrgWCfU6o4SwdAT6xJSCttSh874M9BQdhE2LmlsRYIflPxr0NbRsNk53dvfYHdTizMmON4rhJMWk6rv_IG3IlN_Rqoni1Y6jG0M6_sz1ExmeD0hwqs4Je6Y4CVLIAZzSYD1f2kJwFKcPHnh56O8u9YQ0G_z4RBBmfI_16VG4jyK0kZ_6tI_DVmvFZS2tWnIGFRcoX3DlVDiOftAQruriMcbV8uUhyiAuBNcWSvdYvx1ghM8oLGQEqPFHeyZiPAhVo7NEN2mUW6nrehiQYTssC_UD_lffuehNC_OezoIiAHQ_Cyg6dv8wsbKc-9nNubXex0R1oR7xgtw8JjaCuFdCT8vXSaBW-LdE69jzw7C4agzj1kjf784Uv6BKhjSvOI2iAhCPvc8mryO74XSr-TsKlvyxuA_QTlP2e7Z3bq-jr4zKPspiCS4L5RK0m_hxXiThyNNPOdP4Y9a56aPkaaZhjOo_SCEbIAA&state=53248%2cAAX1x5vZN9DEudS8Hw0Crg%253D%253D&session_state=d0e2274a-cb5a-4da9-aa8b-5cef0f7fd6d9

Azure Data Studio version: azuredatastudio 1.17.0 (b32a48ab73d8914647d33d9684bcb7b48adfe0cc, 2020-04-24T00:21:10.639Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2667 v4 @ 3.20GHz (4 x 3200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (4.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
cms|Mic|0.8.0
dacpac|Mic|1.4.0
import|Mic|0.14.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@aaomidi do you have any ideas for this issue?

**Comment by marcin-vt** [comment]
Same here Version: 1.17.1
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-29T23:48:52.060Z (6 days ago)
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Linux x64 4.15.0-1082-azure

Console log:
> /dsvm/tools/azuredat…t/zone-node.js:2280 Retrieving the Azure token failed. Please sign in again.
> console.<computed>	@	/dsvm/tools/azuredat…t/zone-node.js:2280
> /dsvm/tools/azuredat…t/zone-node.js:2280 [Extension Host] Error: Error: Request failed with status code 502
> 	at e.<anonymous> (/dsvm/tools/azuredatastudio-linux-x64/resources/app/extensions/azurecore/dist/extension.js:16:130744)
> 	at Generator.throw (<anonymous>)
> 	at s (/dsvm/tools/azuredatastudio-linux-x64/resources/app/extensions/azurecore/dist/extension.js:16:125321)
> 	at processTicksAndRejections (internal/process/task_queues.js:85:5)
> /dsvm/tools/azuredat…t/zone-node.js:2280   ERR Unexpeted error handling Azure Account dropdown click : Error: Failure when retreiving tokens

Can it be related to a proxy settings? Is there a local log with more information?

**Comment by aaomidi** [comment]
@marcin-vt, @rodrigolopes 

As a debugging step, would you mind going to 

Settings -> Extensions > Azure Authentication Method

Disable Azure Code Grant, and enable Azure Device Code.

Try the authentication again with the developer console open (Help -> Toggle Developer Tools).

Does this authentication method succeed or does it fail the same way?

Thanks!

**Comment by marcin-vt** [comment]
Thnx for answer @aaomidi.

Changing authentication method causes following error:

> [Extension Host] Error: Request failed with status code 502
> 	at e.exports (/dsvm/tools/azuredatastudio-linux-x64/resources/app/extensions/azurecore/dist/extension.js:16:100048)
> 	at e.exports (/dsvm/tools/azuredatastudio-linux-x64/resources/app/extensions/azurecore/dist/extension.js:16:135056)
> 	at IncomingMessage.<anonymous> (/dsvm/tools/azuredatastudio-linux-x64/resources/app/extensions/azurecore/dist/extension.js:166:57545)
> 	at IncomingMessage.emit (events.js:208:15)
> 	at endReadableNT (_stream_readable.js:1168:12)
> 	at processTicksAndRejections (internal/process/task_queues.js:77:11)
> /dsvm/tools/azuredat…t/zone-node.js:2280   ERR Cannot read property 'close' of undefined: TypeError: Cannot read property 'close' of undefined
>     at e.closeAutoOAuthDialog (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:3916:23)
>     at endAutoOAuthDeviceCode (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:7802:561)
>     at e.$endAutoOAuthDeviceCode (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:4918:447)
>     at e._doInvokeHandler (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:707)
>     at e._invokeHandler (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5032:399)
>     at e._receiveRequest (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5031:59)
>     at e._receiveOneMessage (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5029:908)
>     at file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:5028:136
>     at e.fire (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67)
>     at fire (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:576:470)
>     at t.PersistentProtocol._receiveMessage (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:580:921)
>     at file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:578:67
>     at e.fire (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:194:67)
>     at g.acceptChunk (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:574:17)
>     at file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:573:393
>     at Socket.t (file:///dsvm/tools/azuredatastudio-linux-x64/resources/app/out/vs/workbench/workbench.desktop.main.js:584:332)
>     at ZoneDelegate.invokeTask (/dsvm/tools/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone-node.js:421:31)
>     at Zone.runTask (/dsvm/tools/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone-node.js:188:47)
>     at ZoneTask.invokeTask (/dsvm/tools/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone-node.js:496:34)
>     at Socket.ZoneTask.invoke (/dsvm/tools/azuredatastudio-linux-x64/resources/app/node_modules.asar/zone.js/dist/zone-node.js:485:48)
>     at Socket.emit (events.js:203:13)
>     at addChunk (_stream_readable.js:295:12)
>     at readableAddChunk (_stream_readable.js:276:11)
>     at Socket.Readable.push (_stream_readable.js:210:10)
>     at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)

Strangely enough I also have version 1.12 installed (same vm) and there authentication with device code works there without any issue.

**Comment by aaomidi** [comment]
Hi! The latest insiders version should give you more information on why the authentication failed.

Could you please try that?

**Comment by marcin-vt** [comment]
@aaomidi sadly it did not give me more meaningful error messages (maybe you can get more out of it):
- device code method (fails straight after clicking add account): [device_code_errm.log](https://github.com/microsoft/azuredatastudio/files/4608285/device_code_errm.log)
- code grant method (fails after logging in browser with my AD user): [code_grant_errm.log](https://github.com/microsoft/azuredatastudio/files/4608301/code_grant_errm.log)

I have also checked logs in ~/.config/azuredatastudio/logs - but once again nothing interesting there.

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/issues/10314#issuecomment-627722312
