### ISSUE TITLE
Syntax highlighting breaks after selecting a string containing a backslash

### ISSUE THREAD

**Issue by MarkStockwellZA** [microsoft/azuredatastudio#10208]
- Azure Data Studio Version: 1.17.0

SELECT statements work fine, but the syntax is not highlighted with the correct colors.

Steps to Reproduce:

1. Write a select statement with a literal string that contains a backslash.

Example: In this screenshot, the **AS** keyword should be blue and the column names should be white with the default dark theme on Windows 10.

<img width="549" alt="Capture" src="https://user-images.githubusercontent.com/64535776/80597098-aa13bf80-8a27-11ea-9708-5a786e102da7.PNG">

**Comment by Charles-Gagnon** [comment]
This was broken with https://github.com/microsoft/azuredatastudio/commit/1868a7d3705e4dc32b438ab24303052ed2cc9f09#diff-bb684abea1ae7b363da775aeba9b0bf6

@MarkStockwellZA @NanookSoftware As a temporary workaround while I investigate why this was changed you can manually revert the file to get the previous colorization behavior back.

Go to https://raw.githubusercontent.com/microsoft/azuredatastudio/0b7e7ddbf96bf76e2acc774ae560a06de064b4f5/extensions/sql/syntaxes/sql.tmLanguage.json and copy the text there.

Then go to the ADS install directory and find the `resources\app\extensions\sql\syntaxes\sql.tmLanguage.json` file (in Windows it's `%LOCALAPPDATA%\Programs\Azure Data Studio\resources\app\extensions\sql\syntaxes\sql.tmLanguage.json`) and replace the contents of that file with what you copied above.

**Comment by Charles-Gagnon** [comment]
Closing this as upstream https://github.com/microsoft/vscode-mssql/issues/1666

We'll work on getting this fixed but for the time being you can revert to the earlier version of the grammar as described above if this is affecting you.

**Comment by Charles-Gagnon** [comment]
Re-opening for port request to 1.18 release

**Comment by kburtram** [comment]
Merged to release/1.18

**Comment by MarkStockwellZA** [comment]
The issue is re-occurring in the latest version of VS Code and Azure Data Studio. Specifically, it seems to happen when the last character of a string literal is a backslash. Thanks.
<img width="1028" alt="Capture" src="https://user-images.githubusercontent.com/64535776/86108521-8d494600-bac3-11ea-9066-2517aabed0dd.PNG">

**Comment by PacoTuesday** [comment]
I'm experiencing this issue in version 1.49.1 [Image](https://github.com/user-attachments/assets/28667924-be7c-4b02-815b-370ee122ecbf)
