### ISSUE TITLE
Large Number of Error Messages Results in ADS Unresponsiveness

### ISSUE THREAD

**Issue by Xtrimmer** [microsoft/azuredatastudio#10211]
- Azure Data Studio Version: 1.17.0

Steps to Reproduce:

1. Do anything that would result in STS returning hundreds of error messages that would show up in the MESSAGES Pane.

![image](https://user-images.githubusercontent.com/4079568/80626623-95253500-8a03-11ea-91c2-ed93cb078c9e.png)

When the error count exceeds a large number, the Message pane becomes empty and ADS becomes unresponsive.

**Comment by anthonydresser** [comment]
Are the error arriving quickly and that is causing the slow down? or does it take a while before the window stops responding?

**Comment by Xtrimmer** [comment]
They come in at a pretty fast rate but not so fast that is freezes up instantaneously. It usually takes about approximately 30 seconds before the the program becomes overwhelmed.

**Comment by anthonydresser** [comment]
Last time I tried to solve a similar problem I used a test script that just while looped printed messages and was able to solve the issue reasonably well. I'll need a better test script to attempt to solve it this time.

**Comment by kburtram** [comment]
Closing older issues that don't have recent repro reports.  Please let us know if you're still impacted by this issue.
