### ISSUE TITLE
Search highlights very big sections instead of just the search word or sentence.

### ISSUE THREAD

**Issue by daschall** [microsoft/azuredatastudio#10245]
Issue Type: <b>Bug</b>

When searching for a term in a Jupyter notebook, the current paragraph or sentence is highlighted, instead of just the search word.
This is nice if the word is contained in a small paragraph/sentence, but not if ADS starts highlighting my entire screen and I have to search for the exact occurence myself.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.91GB (105.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by MsSQLGirl** [comment]
Same issue as #9550.

**Comment by chlafreniere** [comment]
Closing as dupe
