### ISSUE TITLE
Microsoft.Data.SqlClient.SqlException

### ISSUE THREAD

**Issue by MusabEdriss** [microsoft/azuredatastudio#10258]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by kburtram** [comment]
@MusabEdriss from the bug message it looks like there is some missing data that was copied into the clipboard.  Please add that information to the bug if available, with a description of the problem and repro steps, ideally.

**Comment by kburtram** [comment]
Closing since the issue doesn't contain sufficient information to investigate.  Please let us know if you have additional information regarding this exception.
