### ISSUE TITLE
Azure SQL Database DNS Alias Fails to Connect

### ISSUE THREAD

**Issue by jdanton** [microsoft/azuredatastudio#10260]
- Azure Data Studio Version:

Version: 1.17.1
Commit: 814ce88c41e0daaca89afed8b184e795057a6f9d
Date: 2020-04-29T23:53:03.736Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:

1. Create a DNS alias for an Azure SQL Database.
2. Attempt to connect to that database.
3. Connection never completes

![AzureSQLDB--DNSBug](https://user-images.githubusercontent.com/7385792/81002823-db213500-8e17-11ea-9bb6-f14715106a4b.gif)

**Comment by aaomidi** [comment]
Is this consistent? Does this problem still exist when you've restarted your computer?

How have you made the DNS record?

**Comment by kburtram** [comment]
Closing older issues without current repro reports.  Please let us know if this issue is still impacting your scenario and provide additional info requested in previous comment if so.  Thanks!
