### ISSUE TITLE
The Azure Group in the Connections sidebar uses the wrong auth mechanism

### ISSUE THREAD

**Issue by ransagy** [microsoft/azuredatastudio#10268]
Issue Type: <b>Bug</b>

When trying to perform any action from the Connections > Azure sidebar group, Every operation fails to login properly. This issue follows up on two others: #10145 #9525 

**Steps to repro:**
1. Add an Azure account using Universal MFA auth - get redirected to browser, choose account, close browser window after connection is done.
2. Unfold the the account, subscription, SQL database nodes.
3. Try expanding one of the DB nodes.

**Actual**: The connection fails and a both the "Connection" flyout appears to the right as well as a dialog stating "Login failed for user: <default sa account name here>"

This continues if i manually choose MFA and then try another operation like expanding the tables node or right click - new query, etc.

**Expected**: the operations will use the logged-in Azure MFA account rather than SqlLogin.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (4.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment]
Thank you for this issue. Unfortunately switching the default behavior isn't going to be super easy since the majority of our users still use SqlLogin over MFA.

I'll have to brainstorm some ideas on how to make this experience work for both scenarios without too much hassle.

**Comment by Charles-Gagnon** [comment]
@aaomidi I think at the very least we can make it remember which auth type the user chose and default to that. That should a good start I think since yeah it's going to be difficult to pick the "right" one by default.

**Comment by ransagy** [comment]
Either that or a way to configure it - If i signed into the account with MFA, either default to that or give me an option to set it, whether in advance or at the point of creation.

**Comment by aaomidi** [comment]
I'll have to push this issue back since there are some other azure login issues right now.

**Comment by aaomidi** [comment]
For now we've decided SqlLogin should remain the default.

**Comment by ransagy** [comment]
What about configuring it? Or at least remembering the last used value?

The experience as it is is very poor for Azure users, to be honest.
