### ISSUE TITLE
[Task] dotnet build doesnt work with dlls when ther are in sqltools Folder

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#10273]
This is to track a bug where we are facing issues while loading DacFx dlls to load in build. When the files are in SqlToolsService folder normally - the build fails to load them (particularly the composition dll) but copying them to a separate folder works.

**Comment by kisantia** [comment]
no longer a problem now that we're moving away using the DacFx DLLs in STS to build projects and going to use the Microsoft.Build.Sql SDK for building both legacy and SDK style projects
