### ISSUE TITLE
Preserve line endings in results grid when copying

### ISSUE THREAD

**Issue by liamdo** [microsoft/azuredatastudio#10281]
**Is your feature request related to a problem? Please describe.**
When copying from a results grid cell that contains line endings, the pasted result does not preserve the line endings. 
**Describe the solution or feature you'd like**
I'd like a option to preserve line endings from the results grid or not when copying similar to SSMS. 

1. Execute this query in Azure Data Studio
`SELECT 'line 1' + CHAR(13) + CHAR(10) + 'line 2' + CHAR(13) + CHAR(10) + 'line 3'`
2. Copy from the results grid
3. Observe when pasting back into a text area the line feed and carraige returns have disappeared
![image](https://user-images.githubusercontent.com/29865380/81170409-8950ea00-8f92-11ea-9149-65283cc84e9b.png)

Behaviour I'd like to see
![image](https://user-images.githubusercontent.com/29865380/81170448-9ec61400-8f92-11ea-86c2-5953a5801cf5.png)

**Describe alternatives you've considered**
I had to revert back to SQL Server Management Studio when I know I'll be dealing with queries with output containing line endings
**Additional context**
SSMS setting for context 
![image](https://user-images.githubusercontent.com/29865380/81170067-e6986b80-8f91-11ea-8b86-e1a4b3312b43.png)

**Comment by Charles-Gagnon** [comment]
This setting exists as `Sql: Copy Remove New Line`

![image](https://user-images.githubusercontent.com/28519865/81184771-a7542580-8f65-11ea-86f8-59cf7867f239.png)

When unchecked it will preserve CR/LF from copied results.

**Comment by liamdo** [comment]
@Charles-Gagnon Thank for pointing that out, in my settings that was ticked. My google-fu missed this!
