### ISSUE TITLE
Failed to register account provider

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#10284]
- Azure Data Studio Version:
Version: 1.18.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.45.0
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0
Steps to Reproduce:

1. Startup Azure Data Studio
2. Open developer  tools -> console. 

The following error is seen:

/Users/arvranmac/git/ads/node_modules/zone.js/dist/zone-node.js:2280 [Extension Host] Failed to register account provider: TypeError: this.metadata.settings.scopes is not iterable (at AzureAccountProviderService.registerAccountProvider (/Users/arvranmac/git/ads/extensions/azurecore/out/account-provider/azureAccountProviderService.js:125:25))
console.<computed> @ /Users/arvranmac/git/ads/node_modules/zone.js/dist/zone-node.js:2280

**Comment by aaomidi** [comment]
Are you seeing this issue in insiders?

**Comment by ranasaria** [comment]
i observed it on a dev build but I am ~2 days behind the master.

**Comment by kburtram** [comment]
I'm not seeing this in the insiders build or my dev environment.  Please reactive if you see this in an official build, otherwise, I suspect it's something with the local dev build.
