### ISSUE TITLE
css-style getting copied unexpectedly to container from a contained item

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#10293]
- Azure Data Studio Version:
Version: 1.18.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.45.0
Electron: 7.2.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

Steps to Reproduce:

1. Create an azdata.TextComponent object with the following CSS style properties set:
`{
		"border-right-width": "2px",
		"border-right-style": "solid",
		"border-right-color": "#57A200"
}`

2. As usual this item is wrapped in some container before finally getting registered in a modelview object.

3. It is rendered it show up as below:
![image](https://user-images.githubusercontent.com/41588310/81242826-fda38180-8fc2-11ea-843b-e31efc93b22c.png)
The green line to the right of 'Privacy policy' is expected. The second green line below the Privay policy is not.

Upon inspecting Elements in Developer Tools this is what is seen:
Node corresponding to our TextComponent with the said border CSS style as expected:

\<p ng-reflect-ng-style="[object Object]" title="" role="" aria-hidden="false" style="**_border-right: 2px solid rgb(87, 162, 0);_** font-style: normal; font-weight: normal; color: rgb(0, 120, 212); width: 102px;"\>
 		\<a class="modelview-text-link" href="http://outlook.com" tabindex="0" target="blank">Privacy policy</a>
\</p> 

But looking at its parent node we see the following:
\<modelview-text style="overflow: hidden; position: relative; **_border-right: 2px solid rgb(87, 162, 0);_** font-style: normal; font-weight: normal; color: rgb(0, 120, 212);">
	\

So the css styles being replicated both on the <p> node and the modelview-text node causes the extra green line to show up. If I remove the "border-right: 2px solid rgb(87, 162, 0);" from the modelview-text node using the Developer Tools then the extra green line disappears.

**Comment by kburtram** [comment]
Closing older API-level bugs to focus on customer scenarios.  Please log a bug for the impacted customer scenario.
