### ISSUE TITLE
Notebook viewlet steals focus on startup

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10290]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open a folder containing a notebook (such as the azuredatastudio repo directory)
2. Close and reopen ADS
3. Start working with a saved connection

Expected: Focus stays in the Connection viewlet

Actual: About 5 or 10 seconds after startup focus is switched to the Notebook viewlet, even if user is in middle of task in Connection viewlet.

**Comment by chlafreniere** [comment]
@corivera you were looking at a bug in this area, correct?

**Comment by corivera** [comment]
Should be fixed. Here's the original PR: https://github.com/microsoft/azuredatastudio/pull/10234
