### ISSUE TITLE
Connections widget: Need filtering to find the connection in a long list

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#10308]
Issue Type: <b>Feature Request</b>

When there are a lot of connections in the Servers section of the Connections widget, we need filtering to identify the connection. When the connections require a scroll bar to display them, this is very useful.

![image](https://user-images.githubusercontent.com/7318752/81358272-e334db00-908a-11ea-9940-821db993c8b4.png)

In addition to just filtering on the cluster name, it would be ideal to be able to search even for a db/table/column name. With too many connections this helps with finding the cluster you need to work with.

Azure Data Studio version: azuredatastudio 1.17.0 (b32a48ab73d8914647d33d9684bcb7b48adfe0cc, 2020-04-24T00:21:10.639Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment]
We already have a couple of issues that have the same request

https://github.com/microsoft/azuredatastudio/issues/6963
https://github.com/microsoft/azuredatastudio/issues/860

So I'm closing this one as a duplicate. 

@qifahs Feel free to add the live site label to those if you think it'd be useful
