### ISSUE TITLE
Connecting to server or DB in Azure view does not allow navigating to the Manage view. Must connect via Server connections

### ISSUE THREAD

**Issue by ninarn** [microsoft/azuredatastudio#10300]
- Azure Data Studio Version: The very latest **insider** build. I honestly can't find how to check the version number, but I updated to the latest only this morning. (I suggest providing instructions for how to check version number in the above instructions.)

Steps to Reproduce:

1. Open Azure Data Studio - Insiders
2. Connect to Azure account
3. In Connections viewlet, expand Azure section in object explorer
4. Expand my subscription and select my server
5. Enter connection information for my server (I used AAD)
6. Once connected to server, right click on server and click 'Manage'
7. Nothing happens...
8. Right click on server and click Connect
9. Enter same connection credentials
10. Once connected to server a second time (it appears in the Servers section of object explorer now), right click on server (in Azure section) and click Manage
11. Manage view for server appears on right side

I encountered this same exact issue for a specific SQL database in an Azure SQL server. Connecting in the Azure view did not allow me to open the Manage view for the database. I had to go to the Servers section and open a new connection for that database before I could enter the Manage view for the database.

**Comment by ninarn** [comment]
To provide more info, I am having this same issue for all of the right click operations/actions that I try to execute in the Azure view versus the Servers view. All of the options in the right click menu in the Azure view for a database don't work for me. Info for each action I've tried below:

1. **Manage** - works in Server view, does nothing from Azure view
2. **New query or New notebook** - works in Server view, does nothing from Azure view
3. **Backup or Restore** - helpful info message given from Management screen (on right side), and unhelpful error message given from Azure view. (screenshot attached)
![ADS Backup error](https://user-images.githubusercontent.com/11049163/81338768-0008e880-9062-11ea-8fbb-ed35a96f0d00.png)

**Comment by kburtram** [comment]
@ninarn we're in the process of redesigning the Azure view experience.  That refactoring should address this type of issue.

**Comment by aaomidi** [comment]
This problem should be fixed.
