### ISSUE TITLE
Tried to open a connection that's being tunneled through SSH

### ISSUE THREAD

**Issue by romeyinfc** [microsoft/azuredatastudio#10304]
Issue Type: <b>Bug</b>

1. Opened  a connection to the tunneled connection using "Connections"
2. Opened a new file that tries to use that connection.
3. Received error.

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.19624

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.88GB (33.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
query-editor-boost|dre|0.4.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
azuredatastudio-postgresql|Mic|0.2.6
import|Mic|0.14.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
sqlops-spexecutesql-to-sql|pej|1.0.1
sql-search|Red|0.4.0
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(3 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@romeyinfc do you know what error you received?  Have you been able to verify the tunnel is generally working, perhaps by validating with a different application such as SQLCMD?

**Comment by romeyinfc** [comment]
@kburtram the error popped up after connecting to the database. To be honest, it looked like a false-positive because I was still able to connect and do everything I needed to do. However, the error kept persisting.

**Comment by kburtram** [comment]
@romeyinfc do you happen to still have the error message?  Or know if the problem persists on the 1.18.1 release?

**Comment by romeyinfc** [comment]
@kburtram I haven't been able to reproduct it in 1.18.1, so it may very well be fixed. Thank you for the help!

**Comment by kburtram** [comment]
Closing issue based on previous comments.  Thanks for reporting this bug!
