### ISSUE TITLE
Provided Books is empty

### ISSUE THREAD

**Issue by capnsue** [microsoft/azuredatastudio#10325]
Issue Type: <b>Bug</b>

in ADS insiders, the "provided books" section is empty.  This is where the troubleshooting / deployment notebooks should be.  They do show up in my non-Insiders ADS for some reason.  How can I fix this?

Azure Data Studio version: azuredatastudio-insiders 1.18.0-insider (dac1970c4355d47bfb710e09a3791226c4b7c929, 2020-05-08T05:38:03.421Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|127.89GB (97.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.5.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
datavirtualization|Mic|1.4.0
import|Mic|0.14.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
whoisactive|Mic|0.1.4

</details>

**Comment by MaddyDev** [comment]
@capnsue Provided books section load up empty, you need to explicitly launch the 'SQL Server 2019 Guide" command from command pallet to open up the tsg book. When you say the section is empty, it's not opening the book even when you launch the command?
