### ISSUE TITLE
Git repository not being recognized

### ISSUE THREAD

**Issue by sanderstad** [microsoft/azuredatastudio#10334]
Issue Type: <b>Bug</b>

Since version 1.18 I no longer have the ability to handle Git repositories in ADS.
It will tell me to initialize the repo if I want but the folder is already a repository

1. Update to version 1.18
2. Create a repository
3. Open the folder in Azure Data Studio using "Open Folder"

See image below how it looks. Left you see the Git repo not being recognized. The terminal shows that this is a Git repo.
![image](https://user-images.githubusercontent.com/6154981/81536355-af4c0500-936b-11ea-803a-557ab3d9dfa3.png)

Azure Data Studio version: azuredatastudio-insiders 1.18.0-insider (dac1970c4355d47bfb710e09a3791226c4b7c929, 2020-05-08T05:38:03.421Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (19.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|86%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.14.0
profiler|Mic|0.11.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Stuart-Moore** [comment]
Can replicate on MacOS

Same folder/rep is fine in the standard build

**Comment by kburtram** [comment]
I can also repro this.  Maybe we had a break in a recent vscode merge.

**Comment by aaomidi** [comment]
This seems to be fixed in master now.

**Comment by sanderstad** [comment]
Thanks! As soon as the insiders edition gets released I'll test the changes

**Comment by kburtram** [comment]
This should be fixed in today's insider build.  Thanks for reporting!

**Comment by kburtram** [comment]
This is back in the RC build.  I'm seeing the below errors in the log.

```
c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 Activating extension 'vscode.git' failed: undefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefinedundefined is not defined.
```

And init repo does this

```
ERR command 'git.init' not found: Error: command 'git.init' not found
    at e._tryExecuteCommand (file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio - RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:4813:836) [<root>]
    at file:///C:/Users/karlb/AppData/Local/Programs/Azure Data Studio - RC1/resources/app/out/vs/workbench/workbench.desktop.main.js:4813:717 [<root>]
    at c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\node_modules.asar\zone.js\dist\zone-node.js:872:34 [<root>]
    at drainMicroTaskQueue (c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\node_modules.asar\zone.js\dist\zone-node.js:595:35) [<root>]
    at ZoneTask.invokeTask (c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\node_modules.asar\zone.js\dist\zone-node.js:500:21) [<root>]
    at Socket.ZoneTask.invoke (c:\Users\karlb\AppData\Local\Programs\Azure Data Studio - RC1\resources\app\node_modules.asar\zone.js\dist\zone-node.js:485:48) [<root>]
    at Socket.emit (events.js:203:13) [<root>]
    at addChunk (_stream_readable.js:295:12) [<root>]
    at readableAddChunk (_stream_readable.js:276:11) [<root>]
    at Socket.Readable.push (_stream_readable.js:210:10) [<root>]
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17) [<root>]
```

@anthonydresser do you have time to take a look at this one?

**Comment by anthonydresser** [comment]
Sure

**Comment by anthonydresser** [comment]
This looks like a webpacking issue. I'm verifying but if it is, there's not a great fix.

**Comment by kburtram** [comment]
weird, it was working a few days ago.  is this an intermittent issue or something?

**Comment by kburtram** [comment]
OK, it looks like I validate on my dev build, so that's why it was working.  This will block the release, so please let me know if you'd like some assistance to try to investigate a fix.

**Comment by anthonydresser** [comment]
I'm testing fixes atm.

**Comment by anthonydresser** [comment]
Fixes in the linked PRs
