### ISSUE TITLE
Ubuntu 16.04 Installation Operation not permitted

### ISSUE THREAD

**Issue by tomchavakis** [microsoft/azuredatastudio#1034]
- SQL Operations Studio Version:

Steps to Reproduce:

Operating System: Ubuntu-x64 16.04.3

sudo apt-get install libxss1

sudo apt-get install libgconf-2-4

sudo apt-get install libunwind8

sudo dpkg -i /home/tom/Downloads/sqlops-linux-0.27.3.deb 

(Reading database ... 263102 files and directories currently installed.)
Preparing to unpack sqlops-linux-0.27.3.deb ...
Unpacking sqlops (0.27.3-1522127969) ...
dpkg: error processing archive sqlops-linux-0.27.3.deb (--install):
 unable to open '/usr/share/sqlops/resources/app/node_modules/jquery-ui/themes/base/selectmenu.css.dpkg-new': Operation not permitted
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 sqlops-linux-0.27.3.deb

**Comment by kburtram** [comment]
@tomchavakis are you still hitting this issue on current releases?  We do test Ubuntu every release and I haven't been able to repro this yet.

**Comment by tomchavakis** [comment]
@kburtram I am still hitting this issue on the latest release (sqlops-linux-0.31.4.deb) at Ubuntu 16.04.
Now I use 18.04 and everything is fine.
For the issue purposes I have just tested again at a VM using Ubuntu 16.04 and now I am getting the following error:

sudo dpkg -i sqlops-linux-0.31.4.deb 
(Reading database ... 
(Reading database ... 263550 files and directories currently installed.)
Preparing to unpack sqlops-linux-0.31.4.deb ...
Unpacking sqlops (0.31.4-1531879093) ...
dpkg: error processing archive sqlops-linux-0.31.4.deb (--install):
 unable to open '/usr/share/sqlops/resources/app/out/vs/workbench/parts/debug/browser/media/clear-repl-inverse.svg.dpkg-new': Operation not permitted
Processing triggers for bamfdaemon (0.5.3~bzr0+16.04.20180209-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for desktop-file-utils (0.22-1ubuntu5.1) ...
Processing triggers for gnome-menus (3.13.3-6ubuntu3.1) ...
Processing triggers for mime-support (3.59ubuntu1) ...
Errors were encountered while processing:
 sqlops-linux-0.31.4.deb

**Comment by kburtram** [comment]
Closing as this related to old ADS build and older version of Ubuntu.  Please let us know if this problem persists with current ADS and Ubuntu versions.  Thanks!
