### ISSUE TITLE
Azure Data Studio Welcome page scrollbar is larger than the content

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#10347]
Easier to see than explain:

[Scrolling.zip](https://github.com/microsoft/azuredatastudio/files/4612463/Scrolling.zip)

(The file is a mp4 since gif reduces the quality a lot)

**Comment by bergeron** [comment]
@alanrenmsft was I supposed to be assigned this bug?

**Comment by alanrenmsft** [comment]
sorry, my mistake @bergeron

**Comment by kburtram** [comment]
Closing older issues without recent repro reports.
