### ISSUE TITLE
May 2020 Endgame

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#10354]
# May 2020 - Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.18

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

## Extensions Testing

Install the latest build of ADS from the link above.

#### VSIX Files

Extension | Changed in this Release?
-- | --
Admin Pack |  No
Admin Tool Extension for Windows | No
Agent | No
CMS  | No
Dacpac | No
Import | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/import/import-0.15.0.vsix)
Profiler | No
Schema Compare | No
PostgreSQL | No
Query History | No
Data Virtualization | No
Machine Learning | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/machine-learning/machine-learning-0.1.0.vsix)

## Scenario Sign Off

- [x] Edit Data @smartguest 
- [x] ADS Shell @kburtram 
- [x] Query Editor @anthonydresser 
- [x] Notebooks  @chlafreniere 
- [x] Livesite tooling @qifahs, @MsSQLGirl      
- [x] Data Virtualization @Charles-Gagnon   
- [x] Acquisition @kburtram 
- [x] Connection @Charles-Gagnon 
- [x] Language Service @Charles-Gagnon 
- [x] Query History @Charles-Gagnon 
- [x] Spark Job Submission @chlafreniere 
- [x] Resource Deployment @alanrenmsft 
- [x] Books @MaddyDev 
- [x] Charting and Insights @alanrenmsft 
- [x] Dashboard @alanrenmsft  
- [x] Backup/Restore @udeeshagautam 
- [x] File Import @kenvanhyning / @aasimkhan30 
- [x] DacFx Deployment @kisantia 
- [x] SQL Profiler @alanrenmsft 
- [x] CMS @abist 
   - https://github.com/microsoft/azuredatastudio/issues/10443 - Fixed
   - https://github.com/microsoft/azuredatastudio/issues/10446 - Fixed
- [x] SQL Agent @abist 
- [x] Azure Integration @aaomidi
- [x] Extension Manager @alanrenmsft 
- [x] Schema Compare @kisantia / @udeeshagautam 
- [x] Big Data Cluster @Charles-Gagnon 
- [x] SSMS Integration @Charles-Gagnon 
- [x] Data Explorer @abist 
 
## Partner Signoffs
- [ ] PGSQL @akamath46297 
- [x] SQL On Demand @BranislavGrbicMDCS 

[win-user]: https://go.microsoft.com/fwlink/?linkid=2127522
[win-system]: https://go.microsoft.com/fwlink/?linkid=2127432
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2127716
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2127431
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2127523
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2127433
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2127524

**Comment by aaomidi** [comment]
Since @aasimkhan30 has worked on the import extension, I assigned it to him.
