### ISSUE TITLE
ModelView Radio Buttons checked property isn't updated when button is deselected

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10357]
The RadioButtonComponent isn't getting its properties updated on the extension side if deselected because another button in the named group was selected.

This is mostly due to the fact that radio button inputs don't get notified through the change event when deselected - so there's no easy way to hook into this. A possible fix is to keep a map of all radio buttons in each group and when one is updated it goes through and sets the property for the others as well.

**Comment by kburtram** [comment]
Closing older engineering-focused bugs to prioritize customer scenario-facing bugs.  Please log a bug for the customer scenario impacted, or reactive if you plan to fix in an upcoming release.
