### ISSUE TITLE
Uncheck unselected radio buttons in Configure Python wizard

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#10360]
When clicking on the Installation Type radio buttons in the Configure Python wizard, the visual button state changes correctly, but the "checked" state in the backing RadioButtonComponent doesn't update. The checked state gets set to true, but never gets set to false. Thus the impact here is that the user is locked into the installation type initially selected in the wizard, and trying to change the installation type does nothing, even though it seems like it should be changing based on the UI behavior.

The issue https://github.com/microsoft/azuredatastudio/issues/10357 was created to track the underlying radio button fix, but for now the linked PR https://github.com/microsoft/azuredatastudio/pull/10361 fixes the issue just in the Python wizard to limit release impact.

**Comment by kburtram** [comment]
Approved in shiproom
