### ISSUE TITLE
Notebook is not rendered when viewed from Viewlet

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10368]
Issue Type: <b>Bug</b>

1. Open a Jupyter Book. 
2. In the Notebooks viewlet, click on of the file and it will not render the ipynb.
![ViewletIssue](https://user-images.githubusercontent.com/6405919/81775720-34d1d100-94a2-11ea-9f97-7b61011a3988.gif)

Note: if you open the same file from Explorer, it works just fine. 

Azure Data Studio version: azuredatastudio-insiders 1.18.0-insider (dac1970c4355d47bfb710e09a3791226c4b7c929, 2020-05-08T05:38:03.421Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (35.29GB free)|
|Process Argv|F:\OneDrive - Microsoft\Demo\Azure Data Studio\Notebooks\WWISuspectMitigation.ipynb|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by chlafreniere** [comment]
This has since been fixed.
