### ISSUE TITLE
Can't select connections

### ISSUE THREAD

**Issue by rhitglgl** [microsoft/azuredatastudio#1037]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
Open query window
Select connect
    Neither Recent Connections or Saved Connections do anything, can see connections listed under Servers

**Comment by rhitglgl** [comment]
I am on version 0.27.3, issue still exists

Thanks

On Apr 2, 2018, at 5:24 PM, Matt Irvine <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhitglgl<https://github.com/rhitglgl> We had a bug like this fixed in the latest 0.27.3 release. Can you try updating to that release and checking if the issue still exists?

You should be able to check for updates from within SQL Ops Studio by clicking on the settings icon in the bottom left and choosing check for updates, but if for some reason that's not working you can download the latest version at https://docs.microsoft.com/en-us/sql/sql-operations-studio/download. Thanks

**Comment by kburtram** [comment]
@rhitglgl you may try clearing our the SQL Ops Studio application cache to see if that helps.

On Windows you can delete `C:\Users\[UserName]\AppData\Roaming\sqlops`.

On macOS the folder is `~/Library/Application Support/sqlops`

This would clear out any corrupt connection settings state, but would also remove any saved connections or other settings (so you may want to back up those settings prior to deleting the above folders).

**Comment by rhitglgl** [comment]
The issue is that the top of the dialog, where the connections are shown, is not visible if app is not full screen. You scroll up to see them, you need to make the app full screen. This is on mac, don’t know about windows.

Thanks

Sent from my iPhone

On Jul 20, 2018, at 11:23 AM, Karl Burtram <notifications@github.com<mailto:notifications@github.com>> wrote:


@rhitglgl<https://github.com/rhitglgl> you may try clearing our the SQL Ops Studio application cache to see if that helps.

On Windows you can delete C:\Users\[UserName]\AppData\Roaming\sqlops.

On macOS the folder is ~/Library/Application Support/sqlops

This would clear out any corrupt connection settings state, but would also remove any saved connections or other settings (so you may want to back up those settings prior to deleting the above folders).

**Comment by pohvak** [comment]
running version 0.31.4 on Mac OS High Sierra and still had this issue, in fact, I can't save any sql user password, i had to type it everytime

**Comment by kburtram** [comment]
I'll close this out since I can't repro and there have been a ton of fixes in this area.  Please let me know if the issue persists on the `1.8.0` build.
