### ISSUE TITLE
Failed to execute 'removeChild' on 'Node'

### ISSUE THREAD

**Issue by sdlins** [microsoft/azuredatastudio#10379]
- Azure Data Studio Version: 1.18.0-insiders

Steps to Reproduce:

1. Trying to open settings after an inconsistent state (Maybe because of #10378);

Result:

Não foi possível abrir 'Configurações': Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node..

I can't open settings anymore, nor even in json mode. I will have to find the file in my storage and edit it out of ADS.

After remove the config cited in #10378 (horizontal scrolling) and restart, I can open settings again.

**Comment by anthonydresser** [comment]
We have fixed the issue you referenced. Can you confirm if you are still seeing this issue?

**Comment by kburtram** [comment]
Closing based on @anthonydresser previous comment.  Please let us know if issue persists on a build with the fix.  We're planning the 1.19.0 release for Wed this week.
