### ISSUE TITLE
Feature Request: Add Ability to Remove the "Messages" Drill-Down Pane

### ISSUE THREAD

**Issue by IObsequious** [microsoft/azuredatastudio#1038]
Thanks for all of your hard work! This IDE is simple, snazzy, and sleek. I may actually _enjoy_ working with databases one day thanks to Zen Mode.

I would like to have the option to remove the messages pane that appears after a query executes. Perhaps output and message panes could benefit from granularity of the same order as MSBuild ( for example, the verbosity '/v' parameter when running from the command line). Having the simple ability to hide the messages pane would suffice as well. Drilling it down doesn't work and even then, its still an eye sore. 

It could be possible that you may already have such an ability somewhere in the IDE. If so, I implore you to consider moving it to the view tab or to a context menu after a right click. Currently, it's location is not immediately intuitive. 

Again, Thanks for giving this to the community!

**Comment by kburtram** [comment]
@IObsequious you can set `"sql.messagesDefaultOpen": false` to have the Message Pane minimized by default which will save the time to keep collapsing it.  I'll keep this suggestion open to track having it entirely not visible.

**Comment by kburtram** [comment]
We've moved Messages to a separate tab now.  It should not occupy any additional vertical space in the UI layout.  Please let me know if this doesn't address the concern raised in this issue.

**Comment by IObsequious** [comment]
@kburtram Thank you for your follow up. You guys are paving the way, in my opinion, as far as user experience and user customization is concerned. Virtually every setting is accessibly and each iteration of the program becomes more intuitive to my workflows. Messages are no longer a neussance. In fact, I had not thought about them in a very long time. This issue is definately closed with many thanks for you and your team's work.
