### ISSUE TITLE
SQL Server Profiler Extension not displaying Login Name

### ISSUE THREAD

**Issue by raswinraaj** [microsoft/azuredatastudio#10393]
- Azure Data Studio Version:1.17.1

Steps to Reproduce:

1. Install SQL Server Profiler - version : 0.11.0
2. Start Profiler Session by connected to an Azure SQL DB 
3. The table that is generated does not show the value of the Login Name even though the column is available. It is always empty irrespective of what user is logged in.
![image](https://user-images.githubusercontent.com/50330414/81934592-d4ab6e00-960c-11ea-9609-95ce87ff537b.png)

**Comment by alanrenmsft** [comment]
@raswinraaj the LoginName is mapped to the field server_principal_name of sqlserver package, and unfortunately it is not available for Azure SQL database. (it is available for standalone SQL Server), the views in Azure Data Studio is designed to be server type agnostic, unfortunately, you will always see these 2 columns without any values.

if you really want to get rid of this column, you can customize this view or add a new view:
1. open the View menu group in the main menu bar
1. select 'Command Palette...'
1. run command: 'Preferences: Open User settigs'
1. filter by the keyword: 'Profiler: View templates' - see first screenshot
1. Click 'Edit in Settings.json' button
1. you can now either remove the loginName column under the 'standard view', or make a copy of the view and then remove the unwanted columns.

![Screen Shot 2020-06-01 at 6 05 03 PM](https://user-images.githubusercontent.com/13777222/83468847-d78ec700-a432-11ea-9460-9ad36164ad37.png)
![Screen Shot 2020-06-01 at 6 06 57 PM](https://user-images.githubusercontent.com/13777222/83468850-d8bff400-a432-11ea-83eb-1d3ebaadcbdd.png)

**Comment by alanrenmsft** [comment]
I am closing the issue since i have explained the reason and solutions.

**Comment by raswinraaj** [comment]
@alanrenmsft  My sole reason for raising this bug was because we have multiple users and we wanted to know which users' query execution was taking the longer duration during profiling. It is unfortunate that this feature is not available. Can  this be raised as a feature request?

**Comment by alanrenmsft** [comment]
@raswinraaj I took another look and realized it is actually doable, for now as a workaround, please locate the LoginName column for the views that you are interested in (follow the steps in my previous comment) and update it to make it look like this:

```
                {
                    "name": "LoginName",
                    "eventsMapped": [
                        "server_principal_name",
                        "username"
                    ]
                },
```
I will make corresponding code changes to update the default templates to include this field.

BTW, please remove the customization when a new ADS version is released so that you can get the future new default templates.

thanks for bring this to our attention and let me know if you have any other questions

**Comment by alanrenmsft** [comment]
@raswinraaj my fix has been merged, if you use the latest ADS insider build you will see the loginName being populated now.

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master

**Comment by raswinraaj** [comment]
Thanks Alan for fixing this quickly.
