### ISSUE TITLE
files opened with the files.association set to "sql" do not have the database connection toolbar

### ISSUE THREAD

**Issue by JustinSpedding** [microsoft/azuredatastudio#1039]
SQL Operations Studio Versions tested:
- 0.27.3
- 0.29.3

Steps to Reproduce:
1) Create a new file called "blah.SQL"
2) Create a new file called "blah.PRC"
3) Add this to your settings: `    "files.associations": {"*.prc": "sql"},`
4) Open both files

In both files, the editor has proper syntax highlighting. Without the file.associations setting, the .PRC file would not even have that. However, even with the setting, the .PRC file does not have the toolbar at the top of the editor with the Run, Cancel, Connect, and Change Connection buttons. The .SQL files does have it.

The toolbar should be applied to any file type that is associated with SQL in the settings.

**Comment by anthonydresser** [comment]
This should work now, we did a refactor of our editor in the last few releases and this functionality came with it.

**Comment by jackRoark** [comment]
I just installed ADS for the first time, two and half years after this issue was resolved and I'm experiencing this same exact problem. As with the OP, the proper syntax highlighting is adopted but the database connection toolbar does not display.

**Comment by jackRoark** [comment]
Nevermind, all set. I found that after creating this setting:

```
"files.associations": {
  "*.my_ext": "sql"
}
```

I also have to create this one:

```
"workbench.editorAssociations": {
  "*.my_ext": "workbench.editor.queryEditor"
}
```
