### ISSUE TITLE
Stream initial query results as they become available

### ISSUE THREAD

**Issue by whatisalwaystrue** [Microsoft/azuredatastudio#1040]
I would love to use this as a teaching tool for people that are new to Sql.  One thing that would be nice would be if the initial results would stream back to the client much like they do in SSMS.  This helps everyone, but especially people new to sql, visualize that the query is what they were intending it to be.

**Comment by MattIrv** [comment]
Thanks for the suggestion. @whatisalwaystrue is there any chance you could give an example of a query where you're seeing different behavior on SSMS and SQL Ops Studio? Thanks

**Comment by kevcunnane** [comment]
@benrr101 do we have any other issue tracking this? I know it was something we scoped out back when we did the MSSQL extension in VSCode with the plan of waiting until we heard from users about the need for this. Do you remember what the rough cost of implementing it would be?

Agree that a good example query to highlight how this works / can be useful would be helpful.

**Comment by whatisalwaystrue** [comment]
Sure,

If you run:

 select * from bigTable

SSMS:
The results start populating results right away.  In more complex queries there is a delay before the results become available, but as soon as the engine starts streaming results they become available. 

sqlops:
"Executing query" spins until the query is complete or you press cancel. 

The advantage to seeing your results right away is that it re-affirms the context of the query that you ran.  My specific use case is that I use SSMS to teach business users how to do simple queries and updates.  There are many times that in seeing the initial results they realize they forgot to group by, or sort, etc.   We have some users on Mac and it would be great to be able to teach this cross platform. 

Thanks for looking at this.

**Comment by ranasaria** [comment]
This feature is in works and should hit our December Release, next month.

**Comment by kburtram** [comment]
Closing since feature is in this release https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.6.
