### ISSUE TITLE
Master Database Opened When Database Dashboard Launched from Server's Database's List

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#10409]
When launching the database dashboard from the databases list in the servers dashboard:
![image](https://user-images.githubusercontent.com/40371649/81986565-e41abf00-95ec-11ea-8029-c7a8dad61884.png)

The breadcrumb shows 'master' as the database that's launched.

**Comment by alanrenmsft** [comment]
double click on the row will redirect to the correct database, but context menu will always lead to master database dashboard.

**Comment by alanrenmsft** [comment]
BTW, this is a regression introduced in this release.

**Comment by kburtram** [comment]
Closing issue since bug fix is merged.
