### ISSUE TITLE
Edit Connection Updating Password Resulted in 2 Connections in Servers View

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#10405]
I had a connection saved in ADS to a server. This password was since updated. Right clicked the server and chose "Edit Connection", which resulted in 2 connections to the same server showing up in the Connections viewlet.

**Comment by aaomidi** [comment]
Reopening since port request has not been merged yet.

**Comment by kburtram** [comment]
I merged the port so I'll close now.  @aaomidi Thanks!
