### ISSUE TITLE
Install schema compare option from sql proj extension

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#10415]
Add "do you want to install - yes/no" and opening the extn. viewlet with SC searched.

In core, there's src/sql/workbench/contrib/extensions/browser/extensionsActions.ts and ShowRecommendedExtensionsByScenarioAction that can be exposed. Can also look if there's a vscode command for this.

**Comment by Benjin** [comment]
Covered by https://github.com/microsoft/azuredatastudio/issues/11096
