### ISSUE TITLE
Connection is closed when it's edited even when edit is canceled 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10421]
1. Right click an existing connected connection
2. Select Edit Connection
3. Click cancel on the connection dialog that appears

Expected : The connection dialog is closed and the connection works as normal

Actual : The connection is disconnected (note the UI shows it as connected but if you right click on the node you don't get the correct set of actions and if you connect to another server it'll update the icon)

**Comment by kburtram** [comment]
This was not repro'ing for me on the latest build.  Please let us know if you're still impacted by this scenario.
