### ISSUE TITLE
Invalid Account warning shown when user has not yet selected an account

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#10422]
When an azure account picker dropdown is displayed to the user for example in arc deployments, if the account picker fields are optional then by default an empty string is the default selected value for an account. In this scenario, we show the following warning even when there is a valid account available for the user to select.
**_Error: Invalid account_**

**Comment by aaomidi** [comment]
I don't think this is an azure area issue - @ranasaria can you assign another label for this?

**Comment by kburtram** [comment]
Closing older issues without current repro reports.
