### ISSUE TITLE
Welcome Page New/Open File Button Text Misaligned

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#10427]
This is what I see from my Mac:

![image](https://user-images.githubusercontent.com/40371649/81999753-f572c400-960a-11ea-9142-4396b9cb407c.png)

Notice that 'Open File' is much higher up on the button than the 'New' text.

**Comment by kburtram** [comment]
The button labels appear aligned in the current build.

![image](https://user-images.githubusercontent.com/599935/129826797-3b329dd9-fd57-4833-be51-9a6e9071a301.png)
