### ISSUE TITLE
Edit connection doesn't populate passwords/remember password

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10424]
1. Right click on a server that is set up with SQL Auth and has "Remember Password" checked

Expected : Edit connection dialog appears with all information (including password) filled in
Actual : Password and "Remember Password" fields are not populated correctly

![EditConnection](https://user-images.githubusercontent.com/28519865/129644685-959f3c10-4b79-4168-a874-de9eda38290f.gif)

**Comment by kburtram** [comment]
I couldn't repro this on the current build.  Could you please reactive if you can still repro?

**Comment by Charles-Gagnon** [comment]
@kburtram I can still repro this on both the latest insiders and stable builds

In addition the "Remember password" box is not checked even though it was checked in the original dialog.

![EditConnection](https://user-images.githubusercontent.com/28519865/129644685-959f3c10-4b79-4168-a874-de9eda38290f.gif)
