### ISSUE TITLE
Error filtering subscriptions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10438]
Filter subscriptions on an Azure account and this error pops up after you click OK :

```
Error running command azure.resource.selectsubscriptions: Cannot read property 'inspect' of undefined. This is likely caused by the extension that contributes azure.resource.selectsubscriptions.
```

**Comment by kburtram** [comment]
@aaomidi could you please take a look at this one?

**Comment by Charles-Gagnon** [comment]
I have a PR out for it to at least get rid of the error

**Comment by aaomidi** [comment]
Huh, this was working for me very recently. I'll take a look at this, would rather fix the problem than break the functionality.

**Comment by Charles-Gagnon** [comment]
Define "working". Because the functionality isn't broken - it still filters just fine. It just displays this error now (which yes is a recent regression)

**Comment by aaomidi** [comment]
Yeah it looks like this part of the code is even unnecessary. Good find!

**Comment by kburtram** [comment]
Fix has been merged.
