### ISSUE TITLE
Deployment links hard to read on dark theme

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10448]
![image](https://user-images.githubusercontent.com/28519865/82095668-5d311980-96b4-11ea-88cb-119e6f33f2ba.png)

Regression from April. 

Previously :

![image](https://user-images.githubusercontent.com/28519865/82095719-7934bb00-96b4-11ea-9e3a-a674cd7865f9.png)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft FYI - I'm working on fixing this. It's a regression because of my changes to the hyperlink styling I did for modelview links

**Comment by kburtram** [comment]
Fix merged to release/1.18
