### ISSUE TITLE
Provide a better console experience

### ISSUE THREAD

**Issue by santiaago** [microsoft/azuredatastudio#1046]
When creating extensions for SQL Operations Studio the current experience with the developer tools is not great.

This issue is linked to this VSCode issue which is locked and closed..
https://github.com/Microsoft/vscode/issues/6745

If you happen to create a react+redux application that uses a redux logger to log actions see changes of state in the extension the logs currently provided by SQL Operations studio are quite poor.

Here is an example of that:

### In SQL Operations Studio:

<img width="234" alt="screen shot 2018-03-26 at 17 11 48" src="https://user-images.githubusercontent.com/825563/38096944-07ed26ba-336c-11e8-82b2-24959e53542c.png">

### In Chrome:

<img width="578" alt="screen shot 2018-03-26 at 17 16 53" src="https://user-images.githubusercontent.com/825563/38096947-0a39c9dc-336c-11e8-8c6a-ad842389c7c6.png">
Notice that all objects are expandable in chrome but in SQLOperation Studio we don't see a lot.

**Comment by kburtram** [comment]
@santiaago there is a VS Code extension that enables a debugging experience for SQL Ops Studio extension similar to VS Code development experience.  I've create a wiki page with additional details at https://github.com/Microsoft/sqlopsstudio/wiki/Debugging-an-Extension-with-VS-Code.

Personally I debug extensions by attaching directly to the Extension Host with sqlops repo loaded into VS Code.  There is a launch task `Attach to Extension Host` for this.  The extension would need to be loaded into the SQL Ops process somehow.  Either by being installed via VSIX or the extensions build task could copy the output into the SQL Ops build output.

I suspect using the VS Code debugging extension should be more straightforward in most cases, but haven't tried it yet.  @kevcunnane would have additional details if you hit any issues with it.

**Comment by santiaago** [comment]
thanks for the reply @kburtram 

I followed the wiki and I was able to debug the sqlops extension from vscode.

I found some errors in the `launch.json` available in the wiki but I cannot update it:

- There is a missing `"` in "runtimeExecutable": "sqlops", line
- There is a missing `}` after `"timeout": 25000`

```json
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "SqlOps Extension",
            "type": "sqlopsExtensionHost",
            "request": "launch",
            "runtimeExecutable": "sqlops",
            "args": [
                "--extensionDevelopmentPath=${workspaceRoot}"
            ],
            "stopOnEntry": false,
            "sourceMaps": true,
            "outFiles": [
                "${workspaceRoot}/out/**/*.js"
            ],
            "preLaunchTask": "",
            "timeout": 25000
        }
    ]
}
```

**Comment by kburtram** [comment]
@santiaago I've updated the wiki to use the `launch.json` snippet you've provided.  Thanks for the corrections!

**Comment by kburtram** [comment]
Closing out older issues.  We'd prefer any fixes in this area to be taken upstream.  Thanks for reporting!
