### ISSUE TITLE
backslash before a single quote breaks syntax coloring

### ISSUE THREAD

**Issue by SteveSte** [microsoft/azuredatastudio#10471]
Issue Type: <b>Bug</b>

If the last character of a string is a backslash, the syntax coloring get confused and start to colour all text like a string.
It's very easy to reproduce:
```
USE MASTER

-- good
DECLARE @path VARCHAR(100) = 'c:\Users'
SELECT * FROM [master].[INFORMATION_SCHEMA].[TABLES]

-- bad
DECLARE @path VARCHAR(100) = 'c:\Users\'
SELECT * FROM [master].[INFORMATION_SCHEMA].[TABLES]
```

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
qpi|joc|0.1.6
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.14.0
profiler|Mic|0.11.0
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
This has been fixed upstream https://github.com/microsoft/vscode-mssql/issues/1666

While we work on getting the fix down to ADS you can follow the instructions here for a temporary workaround fix : https://github.com/microsoft/azuredatastudio/issues/10208#issuecomment-622966422
