### ISSUE TITLE
Dacpac built in NET Core contains the primary DLL's DDL

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#10486]
- Azure Data Studio Version: Current Dev
(On behalf of @Benjin )

Steps to Reproduce:

1. build dacpac in ADS
2. open and inspect model.xml
3. DDL for the primary DLL is generated.

There is a setting for the same in SSDT/DacFx which seems to be switched differently in SSDT vs NET core path. Need a fix in DacFx

**Comment by udeeshagautam** [comment]
@Benjin  lets sync on this I might have a probable fix.

**Comment by Benjin** [comment]
Sources to trace:
1. \DacFx_Preview_SqlProj\Product\Source\SchemaSql\SchemaModel\SqlModelBuilder.cs line 492  function AddAssemblyReference(CustomSchemaData customData)
2. consts : skipCreationIfEmpty and generateSqlClrDdl
3. set in DacFx_Preview_SqlProj\Product\Source\SqlTasks\SchemaToolsSql\Build\SqlTaskHost.cs line 780

**Comment by Benjin** [comment]
Has this been checked in and the new nuget ported over to STS?
