### ISSUE TITLE
Errors not colorized correctly in messages panel

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10496]
Regression from April.

Current April stable bits :

![image](https://user-images.githubusercontent.com/28519865/82350821-af25b800-99b0-11ea-8afc-e470ae270841.png)

Current RC build :

![image](https://user-images.githubusercontent.com/28519865/82350854-b77df300-99b0-11ea-91b9-64a43fa5dc55.png)

The spacing is also different from what it was.

**Comment by kburtram** [comment]
Fix ported to release/1.18
