### ISSUE TITLE
Unable to open 'Profiler: tcp:dsims.database.w': Cannot register more than one working copy with the same resource untitled:..

### ISSUE THREAD

**Issue by edippity** [microsoft/azuredatastudio#10492]
Issue Type: <b>Bug</b>

I just upgraded Azure Data Studio and when i try to start profiler by,
1) View Menu
2) Command Pallette
3) Profiler: Launch Profiler
4) Select connection

 i am getting this message...
Unable to open 'Profiler: tcp:dsims.database.w': Cannot register more than one working copy with the same resource untitled:..

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (23.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.14.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
whoisactive|Mic|0.1.4
sqlops-spexecutesql-to-sql|pej|1.0.1
sql-search|Red|0.4.0
plan-explorer|Sen|0.9.7
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by darrenprunty** [comment]
Hitting the same issue today myself. Let me know if you get anywhere with it! :)

**Comment by Charles-Gagnon** [comment]
I'm going to close this so this should be fixed in the latest released version (1.18). If you still encounter this after updating let us know and we can investigate!

**Comment by ymkumar** [comment]
I am also getting the same error. I have uninstall land Installed it.

**I am unable to launch the SQL profiler though the Azure Studio and getting following error.  Any suggestions?
Unable to open 'Profiler: tcp:glpf2tmdpn.datab': Cannot set property 'actionBarContext' of undefined.**

**Comment by kburtram** [comment]
@ymkumar have you updated to the latest version of ADS and the profiler extension?  After that please try opening and\or closing any folder.  That will clear out the "open tabs" cache to and hopefully reset the bad state causing this.
