### ISSUE TITLE
SQL/IPYNB files opened that use showTextDocument() API, are now shown a text editor.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#10490]
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch TSG book from command pallet: 'SQL Server 2019 Guide'
2. Open any markdown file that have relative links to ipynb files. (Ex: TroubleShooters markdown)
3. Open any notebook link

Expected:
Notebook file opens with correct kernel.
Actual:
Notebook opens up as text file with json content.

This also repros when the relative files are sql files. They just open as text files.

Following VSCode change is the cause:  https://github.com/microsoft/vscode/issues/96888

**Comment by anthonydresser** [comment]
This sounds like a canidatate for an upstream bug, opening files from markdowns don't use custom editors...the fix we made won't last very long, since we are moving away from just using .sql extension for query editor.
