### ISSUE TITLE
Stable build is using insiders icon

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10508]
- Azure Data Studio Version: 1.18.0

Steps to Reproduce:

1. Install ADS on Windows

Expected: Correct branding icons

Actual: Insiders build icon on stable build 

![image](https://user-images.githubusercontent.com/599935/82382895-a6010f00-99e1-11ea-9f9d-95a8ed571aba.png)

**Comment by kburtram** [comment]
@anthonydresser any idea where the best place to look for this is?  I'm assuming it's related to the mixins?

**Comment by anthonydresser** [comment]
looks like the mixin's arennt' overwriting the correct files, ill take a look

**Comment by anthonydresser** [comment]
testing a fix here
https://github.com/microsoft/azuredatastudio/pull/10509

**Comment by anthonydresser** [comment]
Its not that its using insiders, its that it's using our default ones in the repo. Might be useful looking into making out icons in our master branch not the same as our insiders to catch this in insiders.

**Comment by kburtram** [comment]
@anthonydresser thanks!  Let me know if your fix works.  Otherwise, I've created this PR as a more immediate workaround https://github.com/microsoft/azuredatastudio/pull/10511.  This puts the stable icon in the default location in release/1.18.

**Comment by kburtram** [comment]
This is fixed in release/1.18 now.
