### ISSUE TITLE
Database (recovering)

### ISSUE THREAD

**Issue by MauricioMaya** [microsoft/azuredatastudio#10506]
My database has been in recovering status for 1 day and i can't
<img width="1280" alt="Screen Shot 2020-05-19 at 4 47 52 PM" src="https://user-images.githubusercontent.com/37224246/82381840-802f3680-99f0-11ea-84e0-024e52dc0e31.png">
 use it, is there any way to get my database if i didn't make a backup or how can i check if it will recover somehow?
<img width="1280" alt="Screen Shot 2020-05-19 at 4 48 46 PM" src="https://user-images.githubusercontent.com/37224246/82381905-a359e600-99f0-11ea-84e8-4fc3aafdb254.png">

**Comment by kburtram** [comment]
@MauricioMaya in this case, Azure Data Studio is simply reporting the status of the database provided by SQL Server.  You'll need to bring the DB back online, and the exact steps vary based on the current reason the DB is in Recovery.

A general procedure that may help is (1) open a query editor to the master DB (2) run some variation of "ALTER DATABASE SET ONLINE" to bring the DB online.  I'd recommend going through docs on how to bring a SQL Server DB back online.  Search the Internet for something like "ALTER DATABASE SET ONLINE" is a good starting point.  Hope that helps.

**Comment by kburtram** [comment]
@MauricioMaya the DB state displayed in the OE isn't really a bug, assuming the state is correct.  I'll close this issue.  Please see previous comment for a suggestion on how to take the DB back online.
