### ISSUE TITLE
No navigation buttons when we open a new book in a different viewlet.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#10501]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a saved book on your Notebooks viewlet. 
2. Click on notebooks to check of navigation button (Previous and Next) are rendered correctly.
3. Now open TSG book in the provided books viewlet (either by launching the SQL Server 2019 Guide from command pallet or from BDC dashboard)
4. Go back to the notebooks on the Notebooks viewlet. And check for navigation buttons opening any existing notebook. 
They're not rendered.

Only one view shows the navigation buttons correctly at any time. (Usually the viewlet that was last accessed opening a book, will render navigation buttons).

**Comment by chlafreniere** [comment]
Setting to June since there's an open PR out for this already.

**Comment by MaddyDev** [comment]
This has been fixed by #10523. Closing this.
