### ISSUE TITLE
"Run Current Query" keybind no longer behaving as expected

### ISSUE THREAD

**Issue by JFitzMan** [microsoft/azuredatastudio#10538]
Issue Type: <b>Bug</b>

In previous versions the expected behavior of this keybind was to run either the currently selected query or run whichever query the cursor was currently active on. This also used to be able to handle comments included within the queries and selections, as well as multiple queries in the same batch. There are a couple of easily reproducable issues now:

1) Pressing this keybind now runs the entire script regardless of cursor position.

2) Highlighting multiple queries and pressing this keybind results in only the top query being run. In the past, it would run the entire selection. Example: highlight and run both of these in the same batch
select 1
select 1

3) If there is a comment above a query and you include this in the highlighted text, the query will not run. Example: highlight the comment and the select and run.
-- the following gets 1
select 1

4) If you have a query commented out and highlight it to run, it will not run. Example:  run the select 1 by highlighting everything besides the comment characters
-- select 1

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (5.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.60
gitlens|eam|9.8.1
ssmskeymap|kev|1.1.0
query-history|Mic|0.1.0
server-report|Mic|0.2.2
whoisactive|Mic|0.1.4
azure-account|ms-|0.8.4
powershell|ms-|2019.5.0
vsliveshare|ms-|1.0.337
team|ms-|1.149.2
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.3
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1
vscode-icons|vsc|8.8.0
snippet-creator|nik|0.0.4
poor-sql-formatter|WSR|0.1.0

(3 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
I'll close this issue based on the workaround in release/1.18.  We can use one of the duplicate issues to track the longer-term fix in master.  @JFitzMan a hotfix for this is planned for tomorrow if no other blocking bugs are found.

**Comment by kburtram** [comment]
Fixed in release/1.19.  Let's sync up in future meeting how to avoid regressions related to fixes directly in release branches.
