### ISSUE TITLE
Update winget manifest for each release

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#10534]
Windows Package Manager now includes Azure Data Studio. As part of our release process, let's also push an updated manifest file to winget https://github.com/microsoft/winget-pkgs/tree/master/manifests/Microsoft/AzureDataStudio

**Comment by kburtram** [comment]
This is going to be a manual process until the steps can be automated in the future.  I'm not sure if it makes sense to track this as an issue, or if it's better to put in the release checklist documentation.  There are no place code changes for this issue in this milestone.

**Comment by kburtram** [comment]
Closing older issues.  This doesn't appear to changes to the product to support this.  As a process change this is better discussed in shiproom meeting.

**Comment by Charles-Gagnon** [comment]
Reopening this to track getting this added to our release pipeline.
