### ISSUE TITLE
Azure Data Studio - Profiler - Duration measuring unit

### ISSUE THREAD

**Issue by bbuic** [microsoft/azuredatastudio#10536]
Hello,

can someone explain me in which unit is duration in ADS profiler? When i trace own database requests duration was unreal compare to when i run sql command in SSMS!

Bojan

**Comment by alanrenmsft** [comment]
@bbuich it is in microseconds, you can find more information here: https://docs.microsoft.com/en-us/sql/relational-databases/event-classes/sql-batchcompleted-event-class?view=sql-server-ver15

**Comment by davidAtInleague** [comment]
voting for (low priority!) feature request: add this information in the grid display somewhere
