### ISSUE TITLE
Conversion overflow with SELECT on table with lots of decimal fields

### ISSUE THREAD

**Issue by chamih** [microsoft/azuredatastudio#10541]
Issue Type: <b>Bug</b>

Using a table with a 31 decimal fields, which are defined as Decimal (38, 20), e.g.	[OriginalFaceValue] [decimal](38, 20) NULL

When doing a select * or Select top (1000), it fails with "Query failed: Conversion overflows." 

Works fine for a smaller selection e.g. top (100). No issues at all in in SSMS.
 

Azure Data Studio version: azuredatastudio 1.17.1 (814ce88c41e0daaca89afed8b184e795057a6f9d, 2020-04-30T00:16:35.943Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (12.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.47.0
import|Mic|0.14.0
profiler|Mic|0.11.0

</details>

**Comment by alanrenmsft** [comment]
@chamih this should have been fixed by now. please try the latest release.
