### ISSUE TITLE
Run Current Query not behaving as expected

### ISSUE THREAD

**Issue by turrini-giorgio** [microsoft/azuredatastudio#10543]
Issue Type: <b>Bug</b>

Ctrl+F5: Run Current Query executes al statements in the editor after upgrading to May 2020 version

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4700HQ CPU @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
azuredatastudio-postgresql|Mic|0.2.6
import|Mic|0.15.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.4.0
server-report|Mic|0.2.2
azdata-sanddance|msr|1.3.9

</details>

**Comment by olegueret** [comment]
I'm on macos and have swapped Run Query (originally F5) and Run Current Query (originally cmd-F5), so Run Query is cmd-F5 and Run Current Query F5.

Now F5 executes Run Query !!! Tried to assign F9 to Run Current Query but it doesn't work: it also executes Run Query.

This happens (F5 or F9) when having the cursor inside the query. If I select the whole statement of a single query then the shortcut works fine and executes the selected query.

I'm also on 1.18.0, this worked fine in 1.17.x

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:48:48.510Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 7|
|Memory (System)|8.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6


</details>

**Comment by Charles-Gagnon** [comment]
This has been fixed - if you update to the 18.1 hotfix build this should be resolved. Thanks for the report!
