### ISSUE TITLE
Current version is fubar'd

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#10549]
Issue Type: <b>Bug</b>

Having updated to the latest available version as of 26/05/2020 when I do Ctrl-N for new query window I get:
"Unable to open 'SQLQuery_2 - disconnected': Cannot read property 'clearInput' of undefined."

If I do File >> Open file and select a script file (or drag/drop a script file onto the ADS window) I get;
"Unable to open '\[file name\] - disconnected': Cannot read property 'clearInput' of undefined."

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (2.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
deletedb|Ale|0.0.3
tsqlchecker|Dan|0.0.1
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
import|Mic|0.15.0
profiler|Mic|0.11.0
server-report|Mic|0.2.2

</details>

**Comment by kburtram** [comment]
@peterlukerow please see the discussion in https://github.com/microsoft/azuredatastudio/issues/10537.  I think this is the same issue.  We're looking into pushing a hotfix once we have one available.  Sorry for the inconvenience.

**Comment by peterlukerow** [comment]
@kburtram - ah yes it sounds like the same thing.

**Comment by kburtram** [comment]
@peterlukerow thanks for confirming.  We're currently working on a fix for this.
