### ISSUE TITLE
Query Plan tooltips are outside the screen

### ISSUE THREAD

**Issue by eggpa** [microsoft/azuredatastudio#10547]
Issue Type: <b>Bug</b>

Write a non-trivial query on non-trivial database and click "Explain". In the "Query Plan" tab move mouse over some nodes. If node is complex enough the tooltip goes outside of screen making it impossible to read it. It seems tooltips appear roughly from node's position and downwards and they're always same width. In order to fit all content tooltips should be able to fix all vertical space and more horizontal space.

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (15.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aasimkhan30** [comment]
This is likely fixed in the new execution plan feature
