### ISSUE TITLE
DROP TABLE IF EXISTS

### ISSUE THREAD

**Issue by procyongis** [microsoft/azuredatastudio#10553]
Issue Type: <b>Bug</b>

IF EXISTS will not pass validation when connecting to a MSSQL Server.

DROP TABLE IF EXISTS #school_attend

I know that IF EXISTS is not available on Azure Databases.

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:48:48.510Z)
OS version: Darwin x64 19.4.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (6.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@procyongis , are you saying ADS is showing intellisense error? or execution error?

**Comment by kburtram** [comment]
@procyongis I wasn't able to repro this issue either.  When using DROP IF EXISTS with temporary tables please be sure to add batch separators (GO statements) after the DROP and before the CREATE.  And DROP IF EXISTS only works with temp tables on SQL 2016+, as far as I understand.

![image](https://user-images.githubusercontent.com/599935/84063095-4f01b080-a975-11ea-8b7f-4efdda95217b.png)
