### ISSUE TITLE
stacking windows vertically screws up visibility of window content

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#10555]
Issue Type: <b>Bug</b>

1) open a Top 1000 query for your table in tab 1
2) open a Top 1000 query for your table in tab 2
3) At this point you should have three tabs open (the Welcome tab, the SQLQuery_1 tab and the SQLQuery_2 tab. Each query should have finished and you should have each tab divided into both the query and results portions of the tab
4) Now drag SQLQuery_1 tab down to the bottom of the screen so that it shows half the screen with the blue highlight.
5) let go so that the SQLQuery_1 tab is moved below SQLQuery_2

Notice that SQLQuery_2 tab has its sql preview portion scrolled off the top of the screen and there is no scroll bar on this tab so that you can't view the entire window anymore. This makes the top tab useless.

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         930  @ 2.80GHz (8 x 2834)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|12.00GB (2.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.2.2

</details>

**Comment by anthonydresser** [comment]
Can you post a screenshot of what you are seeing? If I follow your repro I get something that looks normal.
![image](https://user-images.githubusercontent.com/4324725/83567697-d6af7100-a4d6-11ea-9b5f-6494973218a6.png)

**Comment by anthonydresser** [comment]
Taking another look, are you refering to the fact that the text portion of the top window is no longer visible? this is fixable by dragging the divider between the grid and the text portion to resize the window. (or double click it to auto drag it to be 50/50.
![image](https://user-images.githubusercontent.com/4324725/83567839-1d04d000-a4d7-11ea-92fb-f0b4f3743c34.png)

**Comment by gregveres** [comment]
@anthonydresser I should have taken a screen shot when it happened. I can't get it to happen now, but i have had it happen to me every time before. 

However, given what you are pointing out, I am wondering if what I was seeing is what you are showing in the second screen shot. I wonder if when the window loses half its height and has to resize, maybe the resizing was doing it such that the SQL Pane was getting shrunk to next to nothing so I couldn't even see the scroll bars and, as you point out, all I had to do was resize with the divider. 

I will keep trying to reproduce it and see if that is the issue. 
Let's close this for now assuming that is the issue and if I can reproduce it, I will reopen.
