### ISSUE TITLE
Azure Data Studio Schema compare issue

### ISSUE THREAD

**Issue by v-omali** [microsoft/azuredatastudio#10556]
@joe-r-ups

- Azure Data Studio Version: 1.17.1

Steps to Reproduce:

When comparing two different Azure SQL Databases, Azure Data Studio indicates that there are no changes. It is stuck at initializing compare.

**Comment by udeeshagautam** [comment]
@v-omali, thanks for reporting the issue. We have noticed Azure database comparisons taking longer time but this should not remain stuck. To help us investigate the issue further

1. Can you please let us know approximate size of the databases. 
2. Also, you mentioned ADS indicates there are no changes - does that mean the compare eventually finishes and shows a message that there are no differences? if so - how long it took to finish?

Thanks for your help!

**Comment by v-omali** [comment]
++ Joe

**Comment by v-omali** [comment]
@joe-r-ups

**Comment by kisantia** [comment]
@v-omali @joe-r-ups can you also try using the SSDT schema compare in Visual Studio and see if the comparison finishes using that tool?
