### ISSUE TITLE
Postgres for Azure Arc Dashboard

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#10567]
Todo:
- [x] Overview
- [x] Launch to Portal
- [x] Delete
- [x] Properties
- [x] Connection strings
- [x] Diagnose issues
- [x] Support request
- [x] Health status
- [ ] Tests
- [ ] Backup (stretch)
- [ ] Restore (stretch)

**Comment by Charles-Gagnon** [comment]
Closing since initial work is done
