### ISSUE TITLE
No more possible to filter objects by schema

### ISSUE THREAD

**Issue by paololabe** [microsoft/azuredatastudio#10601]
In the previous versions was possible to search by schema for example, typing "sp:MYSS."  all stored procedures of the schema MYSS was listed.
Beside was also possibile to search for an object specifying its schema and part if its name, for example MYSS.myTableName, while now the schema is not recognized.
Both features seem to be removed, why ? 
Any change to restore them?

**Comment by alanrenmsft** [comment]
@paololabe thanks for reporting the issue, this is a regression introduced recently, i will fix it .
