### ISSUE TITLE
Connecting to AWS Aurora (Postgres)

### ISSUE THREAD

**Issue by pablocastilla** [microsoft/azuredatastudio#10600]
Why not converting Azure Data Studio in the Visual Studio Code of accessing data bases? The universal tool!

I would love to be able to connect to AWS Aurora (postgres interface).

**Comment by alanrenmsft** [comment]
hmm, we do have a PostgreSQL extension in Azure Data Studio, with it installed, you should be able to connect to the Postgres in AWS (in the new connection dialog, select PostgreSQL as the connection type)

![Screen Shot 2020-06-01 at 3 45 19 PM](https://user-images.githubusercontent.com/13777222/83462002-f2574080-a41e-11ea-9c2d-cf50b4a55eb0.png)
