### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_AI4D: All controls are set as links.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#10619]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark;#DesktopApp;#MAS4.1.2;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#AI4D;#MAS4.1.2;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS4.1.2, MAS1.3.1, MAS4.2.1
Tool: Accessibility insights for desktop

**Repro Steps:**
1 .Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 . Launch accessibility insights for desktop and hover over the controls on the screen.

**Actual:**
Issue1:
On hovering over all the controls all of them are set as links, but on clicking each of them new dialog or tab have opened no redirection to a website.

Issue2:
On hovering over the new button the control is set as group and no name.

**Same issue in the following screen:**
1 .Resources-show more control 

**Expected:**
Issue1:
The control type for all controls should be set as a button and same should be announced by screen readers.
Since on activating each control, there is no redirection to a new url in the web browser.

Issue2:
The new control should be set as button with name as "New"

**User Impact:**
Screen reader users will get wrong control information of the control.

**Attachment link for Reference:**
![A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_AI4D](https://user-images.githubusercontent.com/24580570/83238901-b8830180-a1b4-11ea-8415-81a3073d7469.png)
![A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_AI4D_Issue2](https://user-images.githubusercontent.com/24580570/83239206-2deed200-a1b5-11ea-90a9-69e311382177.png)

**Comment by alanrenmsft** [comment]
we don't have an active PR for this one as well. @v-bbrady

**Comment by fsteffi** [comment]
![image](https://user-images.githubusercontent.com/24580570/223413713-9740828f-7a9c-4718-bbf7-6a28247c3225.png)
![image](https://user-images.githubusercontent.com/24580570/223413815-5a9e37a4-6436-4d43-a576-0566036c99e3.png)

#closed;
Version: 1.43.0-insider (user setup)
Commit: b4d5a08199e9e0cb0138ce540c086ac32d072019
Date: 2023-03-07T06:31:08.002Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25300
