### ISSUE TITLE
Missing operator icons in execution plans

### ISSUE THREAD

**Issue by HugoKornelis** [microsoft/azuredatastudio#1061]
- SQL Operations Studio Version: 0.27.3

Steps to Reproduce:
Request "Explain" or "Run Current Query with Actual Plan"
SELECT p.FirstName, p.LastName, COUNT(*) OVER (ORDER BY p.FirstName ROWS UNBOUNDED PRECEDING)
FROM Person.Person AS p;

Look at the icons for the Window Spool operator (it is represented as an empty box) and for the Sequence Project operator (represented as a generic grey square).
These are just examples, the list of operators without icon is longer.

These operators are always represented as a generic grey square:
Bitmap
Catchall
COND
Population Query
Sequence Project
Snapshot

These operators have no icon at all:
Adaptive Join
Batch Hash Table Build
Clustered Index Merge
Deleted Scan
Index Delete
Index Insert
Index Spool
Index Update
Table Merge
UDX
Window Aggregate
Window Spool

**Comment by LitKnd** [comment]
I am not seeing any indication of parallelism in individual parallel operators -- not sure if that would count as a "missing" operator, or if you would prefer to have a separate feature request?

To say this a different way, I can see a parallelism action operator like "Gather Streams" that tells me that other operators are run in parallel, but the operators running in parallel do not have a visual indicator. 

In SSMS, there are double arrows on operators run in parallel.

**Comment by kburtram** [comment]
Please try out the **SentryOne Plan Explorer** extension.  This is our recommended query plan viewer.
