### ISSUE TITLE
Manage Seach Grid too small

### ISSUE THREAD

**Issue by johnstontrav** [microsoft/azuredatastudio#10611]
Issue Type: <b>Bug</b>

1. Connect DB
2. Select Manage
3. Can't read the search grid

![Virgin_DB_virgin_prod](https://user-images.githubusercontent.com/7200330/83211529-adbe7180-a1a0-11ea-9f6e-d3cd9593c135.jpg)

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:11:42.467Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (7.57GB free)|
|Process Argv|-psn_0_1069317|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscodeintellicode|Vis|1.2.1

</details>

**Comment by johnstontrav** [comment]
I think the issue might be a possible corrupt profile caused by an extension.  I will let you know once I do a fresh install.

**Comment by alanrenmsft** [comment]
@johnstontrav , have you customized the database widgets before? to check it:
1. from main menu -> View
1. Command Palette...
1. Run command: Preferences: Open User Settings
1. search for _dashboard.database.widgets_
<img width="1065" alt="Screen Shot 2020-05-28 at 9 02 51 PM" src="https://user-images.githubusercontent.com/13777222/83219978-9e9add80-a126-11ea-92b9-8238d0fede6f.png">

1. and click 'Edit in settings.json'
<img width="702" alt="Screen Shot 2020-05-28 at 8 59 14 PM" src="https://user-images.githubusercontent.com/13777222/83219816-30eeb180-a126-11ea-87fb-5a68f8860f6e.png">

do you have this settings edited there? if so, you can update the sizeX and SizeY of the Search widget, the new default value is now SizeX:3 SizeY:2 as shown in my screenshot above, you might still have the old default value.

**Comment by johnstontrav** [comment]
WOW!!! thanks @alanrenmsft I have been trying to hunt this down for ages!

**Comment by JorgeTorselli** [comment]
WOW!!! thanks @alanrenmsft, It work!!

**Comment by alanrenmsft** [comment]
@JorgeTorselli and @johnstontrav , just curious, was the dashboard customization done by you directly or by installing some other extensions?

**Comment by JorgeTorselli** [comment]
I just use the dashboard as it is no third party installations, I don´t like the SQL Search from Red Gate, it is better on MSSQL, and here just using it...

**Comment by johnstontrav** [comment]
@alanrenmsft it was just the default.

**Comment by JorgeTorselli** [comment]
Yes just the default...
