### ISSUE TITLE
Description of Azure Data Studio on Linux during installation

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10613]
- Azure Data Studio Version: 1.18.1

Steps to Reproduce:

1. Install Azure Data Studio on Linux Ubuntu 18.04 using Software Installer. Use the .deb file when installling.

![image](https://user-images.githubusercontent.com/6405919/83213581-5627f380-a117-11ea-9e9d-6c103a785f10.png)

Please update the tag line.. Perhaps we can use the first paragraph of the [doc](https://docs.microsoft.com/en-us/sql/azure-data-studio/what-is?view=sql-server-ver15)?
_Azure Data Studio is a cross-platform database tool for data professionals using the Microsoft family of on-premises and cloud data platforms on Windows, MacOS, and Linux. See http://aka.ms/azuredatastudio for documentation._

**Comment by aaomidi** [comment]
The new branding should be available for August release and insiders.

**Comment by dzsquared** [comment]
I just stumbled on this tonight while installing ADS on my chromebook.  I noticed in the merged fix the old sqlops URL is still in play.  Maybe we swap that out for https://aka.ms/azuredatastudio?
