### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_Keyboard:Focus on closing the preview dialog is not on the preview button.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#10618]
[“Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#Benchmark#DesktopApp;#MAS2.4.3;#SQL Azure Data Studio;#FTP;#STP;#Keyboard

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS2.4.3

**Repro Steps:**
1 .Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 .Tab to Preview button and press enter and use escape to close the dialog.

**Actual:**
On using escape to close the dialog the next tab focus is on new button.

The same issue observed when drop-down of the new button is closed 

**Expected:**
The tab focus after closing the dialog should be on the button that activated the dialog that is should be visible on the preview button itself.

**User Impact:**
Keyboard users will receive the wrong order of navigation to the controls.

**Attachment link for Reference:**
[10618A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4700484/10618A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_Keyboard.zip)

**Comment by alanrenmsft** [comment]
I think we don't need to spend time out fixing this issue, because the Preview button will be removed once the accessibility testing is done. so closing the issue.

**Comment by fsteffi** [comment]
![image](https://user-images.githubusercontent.com/24580570/223413419-a8af4357-c3d6-4446-ac86-7264cd20b88f.png)

#closed;
