### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by Sodajunkie** [microsoft/azuredatastudio#10626]
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/4702916/renderer1.log)

Issue Type: <b>Bug</b>

I'm not sure how to reproduce the issue.  I came back to the application and saw the error, which said to submit this ticket along with my log file.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.98GB (3.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-reveal|evi|4.0.3
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.4.0
import|Mic|0.15.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
server-report|Mic|0.2.2
azdata-sanddance|msr|1.3.9
sqlops-spexecutesql-to-sql|pej|1.0.1
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
Thanks! I'm going to close this since we have the information we need here - if you have a specific repro or more information you can give us just respond here and we can reopen if needed.
