### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Welcome_ExtendyourdataStudio_ScreenReader: Decorative image is announced.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#10624]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#NonBenchmark;#DesktopApp;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#NVDA;#JAWS;#STP;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS1.3.1
Screen reader : NVDA2020.1, JAWS

**Repro Steps:**
1 . Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 . Navigate Extend your data Studio on Welcome screen.
4 . Launch screen reader as NVDA and navigaet to "SQL SERVER AGENT" button.

**Actual:**
On navigating to all the 4 buttons starting from "SQL SERVER AGENT" using insert+numpad(6) the graphic present beside each of the buttons is announced as "un-labeled graphic"

**Same issue with JAWS**

**Expected:**
The line decorative graphic should not be announced in browse mode just the name of the button should be announced.

**User Impact:**
Screen reader users will think the image is informative while its not.

**Attachment link for Reference:**
[10624A11y_AzureDataStudioStayHealthy_Welcome_ExtendyourdataStudio_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4701140/10624A11y_AzureDataStudioStayHealthy_Welcome_ExtendyourdataStudio_ScreenReader.zip)

**Comment by v-bbrady** [comment]
I was no able to recreate issue

**Comment by kisantia** [comment]
@fsteffi I am unable to repro this. Only "SQL Server Agent button" gets announced by NVDA, no decorative image.
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/e56c8e11-6dc6-46b1-8b8b-f9f20009a429)

**Comment by kisantia** [comment]
Copied from email thread with Steffi (in a previous thread it was mentioned that Steffi doesn't have access to close or reply on this issue and asked me to copy the reply here and close the issue) :

Hi 
 
Same for the below bug as well.
 
Not repro
#Closed;
 
 
Thanks
Steffi
