### ISSUE TITLE
Next button in a Wizard still shows up as enabled when enabled=false

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#10638]
When setting **enabled**=false on the Done button in a wizard, the button grays out and is not clickable. When trying to do the same with the Next button, **enabled** can be set to false and the button will still be clickable. Other navigation buttons in the wizard may have the same issue, but those are the only two I tested.

**Comment by kburtram** [comment]
Closing older API-level bugs to focus on customer scenario-focused bugs.  Please open a bug for the impacted customer scenario, or reactive this issue if you plan to fix in an upcoming release.
