### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Dashboard_Home - Toolbar_Screenreader : NVDA is not announcing non focusable content.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10647]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#Benchmark;#A11yTCS;#A11yMAS;#DesktopApp;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#NVDA;#STP;#JAWS;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360cc46910025453c14e5e02cda8d1ac33d0
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS1.3.1
Screenreader : NVDA 2019.3.1,JAWS

**Repro Steps:**
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Double click on connected server or right click on it & select manage option to open the Dashboard.
4. Navigate to Home under Dashboard & hit enter.
5.Navigate to "Learn more" button.
6.Start screenreader as NVDA and hit next arrow to read contents in the section below toolbar.   

**Actual:**
NVDA is not reading the Version,Computer name,Edition,OS version information contained in the expanded section below toolbar which don't have any focus. 

**Similar issue also observed with JAWS.**

**Expected:**
NVDA should read the Version,Computer name,Edition,OS version information contained in the expanded section below toolbar which don't have any focus. 

**User Impact:**
Screen reader users will not get any information about the content.

**Attachment link for Reference:**
[10647_A11y_AzureDataStudioStayHealthy_Dashboard_Home - Toolbar_Screenreader.zip](https://github.com/microsoft/azuredatastudio/files/4707190/10647_A11y_AzureDataStudioStayHealthy_Dashboard_Home.-.Toolbar_Screenreader.zip)

**Comment by alanrenmsft** [comment]
this is also by design, tab focus should move item to focusable items, if you want to navigate the page there are special screen reader keys for it. not sure about nvda, but on macOS voiceover you can press CAPS + Left/Right to browse the text elements.
