### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Welcome_AzureDataStudio-Insiders_Usability: The data in the drop down are not visible when the theme are applied.

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#10644]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev4;#A11yTCS;#A11yUsable;#Benchmark;#DesktopApp;#SQL Azure Data Studio;#FTP;#STP;#HighContrast;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Pre-Requisite:** : enable theme  solarized light

**Repro Steps:**
1 .Launch Azure Data Studio Insiders application.
2 . If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3 .Tab to Preview button and press enter.
4 .Apply the theme quite light and solarized light

**Actual:**
Issue1:
The items under dropdown new are not visible when navigated to each of them.

Issue2:
When color theme high contrast is applied the drop-down new is not recognizable as a drop down. 

**Expected:**
Issue1:
The items under dropdown should be  visible when navigated to each of them.

Issue2:
When color theme high contrast is applied the drop-down should be  recognizable as a drop down

**User Impact:**
Keyboard and low vision users will face difficulty in viewing the data.

**Attachment link for Reference:**
![Screenshot (150)](https://user-images.githubusercontent.com/24580570/83321720-212eb480-a26f-11ea-9072-f7de2c84b6e0.png)
![Screenshot (151)](https://user-images.githubusercontent.com/24580570/83321721-21c74b00-a26f-11ea-8d75-00465973241d.png)

**Comment by alanrenmsft** [comment]
we don't have an active PR for this issue, @v-bbrady , please take a look at this one.
