### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader : NVDA is incorrectly announcing row number of table records. 

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10649]
[“Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#NVDA;#NonBenchmark;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS1.3.1,
Screenreader : NVDA 2019.3.1

**Repro Steps:**
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Double click on connected server or right click on it & select manage option to open the Dashboard.
4. Navigate to Databases under Dashboard & hit enter.
5.Navigate to table records.
6.Start Screenreader as NVDA and observe whether NVDA is reading all table records or not.

**Actual:**
NVDA is not reading correctly the Databases first 5 table records.

**Expected:**
NVDA should read the Databases first 4 table records correctly.

**User Impact:**
Screen reader users will get incorrect information about the table records and get confused.

**Attachment link for Reference:**

[10649_A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader.zip](https://github.com/microsoft/azuredatastudio/files/4707518/10649_A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader.zip)

**Comment by alanrenmsft** [comment]
@pranshu512 that is weird, i am not able to reproduce this issue, could you please try again?
this is what i am getting:
![Screen Shot 2020-07-13 at 7 08 12 PM](https://user-images.githubusercontent.com/13777222/87372396-484df680-c53c-11ea-9d18-a8359960a66f.png)

**Comment by Rama8345** [comment]
Verified the issue at Azure Data Studio. the issue is not reproducible. So, closing the bug. Please find attachment for reference.
**Github Tags:**#Closed;
![10649_Closed](https://user-images.githubusercontent.com/115216656/221792595-a584a5cf-76ac-41e5-8d21-75f36ced94e0.gif)
