### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_ImportFlatFileWizard_ModifyColumns_AI4D: All table column headers are set as Text.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10656]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#MAS4.1.2;#SQL Azure Data Studio;#FTP;#AI4D;#MAS4.2.1;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider
Commit: e8dc0d1
Date: 2020-05-27T17:24:57.733Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS4.1.2, MAS4.2.1
Tool: Accessibility insights for desktop

**Repro Steps:**
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Install the SQL Server Import extension.
4. Right click on any database undere the connected server & select Import Wizard.
5. Provide Input file details & Next.
6. On Preview Data screen, navigate till Next button & hit enter.
7.Launch accessibility insights for desktop and hover over table column header.

**Actual:**
Modify columns table column headers are set as Text.

**Expected:**
Modify columns table column headers should be set as column header.

**User Impact:**
Screen reader users will get wrong control information of the table column header.

**Attachment link for Reference:**

![Screenshot (313)](https://user-images.githubusercontent.com/64009219/83331359-712f6a80-a2b3-11ea-8014-675192bb584c.png)

**Comment by aasimkhan30** [comment]
This fix is merged in the main

**Comment by HindujaArugula** [comment]
Verified the bug in 
Bug is fixed and does not repro. Hence closing the bug.
Please find the closing attachment.
**Github Tags:**#Closed;
<img width="674" alt="10656_Closed" src="https://user-images.githubusercontent.com/125462007/219610227-565fe68a-2b8c-41f5-a4f6-0ccca58d69c2.png">
