### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader : NVDA is not announcing the expand and collapse functionality of show actions button.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10650]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev2;#A11yTCS;#A11yMAS;#DesktopApp;#MAS1.3.1;#SQL Azure Data Studio;#FTP;#NVDA;#MAS4.2.2;#JAWS;#STP;#NonBenchmark;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS1.3.1, MAS4.2.2
Screenreader : NVDA 2019.3.1,JAWS

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Double click on connected server or right click on it & select manage option to open the Dashboard.
4. Navigate to Databases under Dashboard & hit enter.
5.Navigate to Show actions button in the column 5 of table records.
6.Start Screenreader as NVDA and observe whether NVDA is announcing the expand and collapse functionality of button or not.

**Actual:**
NVDA  is not announcing the expand and collapse functionality of show actions button.

**Similar issue also observed with JAWS.**

**Similar issue also observed in following scenarios:**
1)Notebook-->Markdown Toolbar(NVDA not announce expanding/collapsing functionality of "Toggle more" button)
2)Import Flat File Wizard-->Modify Columns(NVDA not announce expanding/collapsing functionality of dropdown in the 2nd column of the table.)

**Expected:**
NVDA should announce the expand and collapse functionality of show actions button.

**User Impact:**
Screen reader users will face difficulty to understand the expand and collapse state of show actions button.

**Attachment link for Reference:**

[10650_A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader.zip](https://github.com/microsoft/azuredatastudio/files/4707520/10650_A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Screenreader.zip)

**Comment by alanrenmsft** [comment]
@pranshu512 , please don't include other scenarios as similar issues in an issue, you should open separate issues for each scenario.

for this particular issue, the ... button is not meant to be a button with expanded/collapsed state. it is just providing an extra way to open the context menu. closing as won't fix.
