### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Usability: Table records are not visible when the high contrast theme are applied.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10652]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**:#A11y_AzureDataStudioStayHealthy;#A11ySev4;#A11yTCS;#A11yUsable;#DesktopApp;#SQL Azure Data Studio;#FTP;#STP;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Repro Steps:**
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Double click on connected server or right click on it & select manage option to open the Dashboard.
4. Navigate to Databases under Dashboard & hit enter.
5 .Apply the theme high contrast and observe table records.

**Actual:**
When color theme high contrast is applied table records are not visible.

**Expected:**
When color theme high contrast is applied table records should be visible.

**User Impact:**
Low vision users will face difficulty to view the table records.

**Attachment link for Reference:**
![Screenshot (311)](https://user-images.githubusercontent.com/64009219/83329720-b8642e00-a2a8-11ea-87d8-995d8be73a0b.png)

**Comment by alanrenmsft** [comment]
this has been fixed in the latest insider build
