### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Dashboard_Databases_Colorcontrast : Color contrast ratio of table record focus indication is less than 3:1.

### ISSUE THREAD

**Issue by pranshu512** [microsoft/azuredatastudio#10651]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11ySev3;#A11yTCS;#A11yWCAG2.1;#DesktopApp;#SQL Azure Data Studio;#FTP;#MAS1.4.11;#Colorcontrast;#NonBenchmark;#Win32;#Acc123;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.19.0-insider (system setup)
Commit: 8288360
Date: 2020-05-29T05:54:49.731Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Additional Details:**
MAS References: MAS1.4.11
Tool: Accessibility insights for desktop

**Repro Steps:**

1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Double click on connected server or right click on it & select manage option to open the Dashboard.
4. Navigate to Databases under Dashboard & hit enter.
5.Hover over databases table record using mouse.
6.Open Accessibility Insights for Desktop and check the Color contrast ratio of table record focus indication.

**Actual:**
Color contrast ratio of table record focus indication is 1.37:1 i.e less than required 3:1.

Similar issue also observed in following scenarios:
1)Import Flat File Wizard-->Specify Input File
2)Import Flat File Wizard-->Preview Data
3)Import Flat File Wizard-->Modify Columns
4)Import Flat File Wizard-->Summary

**Expected:**
Color contrast ratio of table record focus indication must be atleast 3:1.

**User Impact:**
Low vision user would find it difficult to identify focus on table records.

**Attachment link for Reference:**
![bug](https://user-images.githubusercontent.com/64009219/83328288-99ad6980-a29f-11ea-82c1-a85bd8bbaf3f.png)

**Comment by alanrenmsft** [comment]
@pranshu512 you are comparing 2 background colors, background of the hovered row and the background color of the dashboard, it doesn't impact user from reading the information on the screen. my understanding is that only text vs background contrast ratio needs to meet 3:1 requirement. please reopen if you think my understanding is wrong.
