### ISSUE TITLE
powershell notebook

### ISSUE THREAD

**Issue by jpmlinssen** [microsoft/azuredatastudio#10658]
Issue Type: <b>Bug</b>

When choosing powershell as kernel the first time you start ADS and create a new notebook from the menu, it  wants to install Python instead of powershell. 

regards
jack

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
Hi @jpmlinssen, this is by design. Our PowerShell kernel is a true Jupyter kernel, and as such, needs Jupyter installed on the machine (which requires Python). This is why you're getting prompted to install Python.
