### ISSUE TITLE
SQL Schema Compare "ignore comments" general option doesn't work for /* comments */

### ISSUE THREAD

**Issue by hpwright** [microsoft/azuredatastudio#10661]
Issue Type: <b>Bug</b>

Prepare the environments.
1.  Choose a small database that contains at least one object that contains a /* */ style comment.  Lets call this database "A"
2.  Make a copy of this database and restore it on to either the same or different SQL instance.  Lets call this database "B"
3.   Change what's inside a /* */ style comment in database "B"

Reproduce the problem
1.  Start up a SQL Server Schema Compare session and select the databases to compare.  Make sure the database contain code that includes /* */ style comments.  Also make sure that at least one of comments between the enviroments being compared
2.  Click the Options button
3.  Select the General Options tab
4.  Check the tick box next to the "Ignore Comments" option
5.  Click OK and run the compare.
6.  You will see the object in Database "B" being highlighted as a difference, even though it should not be a difference due the to only change being in the /* */ style comment.  

Extension version: 1.4.0
Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@hpwright does the object being compared have any other differences besides the comment? I tried to repro this by comparing two databases with the only difference being a comment and didn't see differences when using schema compare.
