### ISSUE TITLE
Notebook PySpark kernel fails to authenticate

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10669]
Don't have a consistent repro, but it seems to happen when you launch a notebook from a disconnected node. From what I saw the call to getCredentials wasn't returning with anything sometimes and thus we didn't have a password to fill in.

**Comment by chlafreniere** [comment]
I've been testing this as part of testing, and can no longer repro this behavior when running a spark kernel on first run. As a result, closing this.
