### ISSUE TITLE
Buttons text not aligned in Welcome Page

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#10696]
The text in the buttons Welcome Page are not vertically aligned properly.

<img width="175" alt="Screen Shot 2020-06-03 at 10 47 43 AM" src="https://user-images.githubusercontent.com/6411451/83670401-f5ba0b80-a587-11ea-83a3-a2267c69adb1.png">

**Comment by kburtram** [comment]
This issue is fixed on the latest build.
