### ISSUE TITLE
Cannot connect SQL server from Ubuntu 20.04

### ISSUE THREAD

**Issue by OsmanAktemur** [microsoft/azuredatastudio#10692]
- Azure Data Studio Version: 1.18.1 (I tried another same old versions that works on Ubuntu 19.10 and still same result )

Hi i cannot conect sql server from Ubuntu 20.04 however i can connect with DBeaver successfully. Azure studio hanging while connect. I can telnet/ping to sql server and it seems there is no network issue. Btw i can connect to local sql server which i run on docker
![image](https://user-images.githubusercontent.com/7611781/83621712-b4c9f300-a597-11ea-8cc8-fd77add830af.png)

All logs folder attached.
[logs.zip](https://github.com/microsoft/azuredatastudio/files/4722504/logs.zip)

Steps to Reproduce:

1.Fill server user and password information.

**Comment by adlerdias** [comment]
I'm facing the same issue a fresh install of 20.04 on vmware.

nc / ping / rdp connection working as expected.

![image](https://user-images.githubusercontent.com/307859/83638070-fb5f2380-a57e-11ea-9d85-6c9d459fd3d4.png)

**Comment by OsmanAktemur** [comment]
> I'm facing the same issue a fresh install of 20.04 on vmware.
> 
> nc / ping / rdp connection working as expected.
> 
> ![image](https://user-images.githubusercontent.com/307859/83638070-fb5f2380-a57e-11ea-9d85-6c9d459fd3d4.png)
> 
> # Steps to Reproduce
> A fresh Ubuntu 20.04
> 
> sudo apt install libxss1 libgconf-2-4 libunwind8
> 
> download and install azuredatastudio then try to connect to any sqlserver instance.

Mine Ubuntu 20.04 installation considered fresh, i install it two days ago.

**Comment by OsmanAktemur** [comment]
Another hint is;
I tried with VS Code MS-SQL plugin and there is same issue there. Both apps use this process and while hanging conect "MicrosoftSqlToolsServiceLayer" is consuming too much CPU also can be hearing fans are spinning fast :) 
![image](https://user-images.githubusercontent.com/7611781/83648911-47ca5380-a5bf-11ea-8b15-8777e0f2bbf1.png)


![Screenshot from 2020-06-03 17-34-23](https://user-images.githubusercontent.com/7611781/83650429-0175f400-a5c1-11ea-937d-232e8b4d4ec4.jpg)

**Comment by abist** [comment]
@OsmanAktemur Thanks for opening the issue! Could you see if there' any error that pops up on the Developer Console (`Ctrl/Cmd+Shift+I` or `Help`->`Toggle Developer Tools` -> `Console`) and paste them here if any?

**Comment by OsmanAktemur** [comment]
@abist Hi, Logs like this, seems only one error in the console, but it is alredy exsits before i try to connect
![Screenshot from 2020-06-05 19-52-08](https://user-images.githubusercontent.com/7611781/83903286-85b5ac00-a766-11ea-999a-72c1b0d3a556.jpg)

**Comment by Barthezzcz** [comment]
still bugged even on 1.19.0

**Comment by adlerdias** [comment]
I'm moving to valentina studio free for now, if some test is needed just mention.

**Comment by OsmanAktemur** [comment]
Hi again, i solved this issue by following these steps;
https://askubuntu.com/questions/1233186/ubuntu-20-04-how-to-set-lower-ssl-security-level

@adlerdias if you wanna try check it

**Comment by Barthezzcz** [comment]
THANKS ! its working now

pá 17. 7. 2020 v 19:53 odesílatel OsmanAktemur <notifications@github.com>
napsal:

**Comment by cheenamalhotra** [comment]
Closing as customers are unblocked.
