### ISSUE TITLE
allow resize of search box in database management page/tab

### ISSUE THREAD

**Issue by ngicbrad** [microsoft/azuredatastudio#10698]
The search widget on the database management page can be resized. With the last update columns can't be resize much and the whole search widget can't be resized. it would be nice to make it bigger to see proc and table names etc. 

![Capture](https://user-images.githubusercontent.com/66383737/83672832-e8f7e080-a5a4-11ea-8144-67f9abca3c2a.PNG)

**Comment by alanrenmsft** [comment]
@ngicbrad please refer to my comments for a similar issue: https://github.com/microsoft/azuredatastudio/issues/10611#issuecomment-635745613.

please reopen the issue if it doesn't meet your needs.
