### ISSUE TITLE
we need a better icon for the arc extension

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10706]
<img width="696" alt="Screen Shot 2020-06-03 at 9 38 05 AM" src="https://user-images.githubusercontent.com/13777222/83690017-d2518980-a5a4-11ea-890f-8da870ca3a35.png">

**Comment by alanrenmsft** [comment]
@chlafreniere @ranasaria , I think we need a better icon for this extension 😃

**Comment by chlafreniere** [comment]
This has since been fixed:

![image](https://user-images.githubusercontent.com/40371649/83700693-55caa500-a5bc-11ea-8c99-8b1f82498944.png)
