### ISSUE TITLE
the dark theme style of manage packages icon for python kernel is not consistent with the rest of the UI

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10707]
let's get a blue version for this icon.
<img width="104" alt="Screen Shot 2020-06-03 at 9 36 22 AM" src="https://user-images.githubusercontent.com/13777222/83690236-3d9b5b80-a5a5-11ea-8f8f-f658131546e5.png">

**Comment by chlafreniere** [comment]
We need to figure this out as part of accessibility. This is under the preview flag, so moving to July.

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by chlafreniere** [comment]
I've been looking at this and will continue looking today; it's an issue that affects any extension-contributed actions to the notebook toolbar.

**Comment by chlafreniere** [comment]
There's interplay here between the masked icons that isn't trivial to figure out at all, so we need to have a discussion with design. The ask here is to have the same icons for light + dark mode (but not for hc). This action is contributed by an extension, so it makes fixing this particular issue in a generic way much harder. A few different avenues to pursue here:
- Work with design to review theme icon foreground colors; there may be opportunity to do either align with dashboards (where every icon is blue for all themes) or the rest of the app (where there are distinct icons for light/dark themes)
- Work with VS Code to contribute the ability to contribute an action with its own high contrast icon (separate from light/dark)
- Any other options anyone else has 😄

**Comment by chlafreniere** [comment]
This has since been fixed:

<img width="162" alt="image" src="https://user-images.githubusercontent.com/40371649/174452957-7d8f1dc1-f355-46e4-91c6-9732a20957bb.png">

Closing as a result.
