### ISSUE TITLE
the edit/close button for the notebook cell menu doesn't do anything.

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10713]
<img width="334" alt="Screen Shot 2020-06-03 at 9 26 56 AM" src="https://user-images.githubusercontent.com/13777222/83692664-4b52e000-a5a9-11ea-9c14-c87c6a596000.png">

I clicked on the X button and it becomes Edit button, both doesn't seem to be doing anything.

**Comment by chlafreniere** [comment]
It works for text cells, just doesn't do anything for code cells.
