### ISSUE TITLE
Search Widget

### ISSUE THREAD

**Issue by JorgeTorselli** [microsoft/azuredatastudio#10727]
The previous version the search widget was more functional, I noticed that it changed, now the search widget is shown as a table, but it is very narrow and does not let me change the size of the column enough to read the object name, I tried to resize the widget but it didn't let me, is there any way to do it? Or can you return the widget to the way it displayed objects before the last update?

**Comment by alanrenmsft** [comment]
@JorgeTorselli please refer to my comments for a similar issue: #10611 (comment). hope this helps.

**Comment by alanrenmsft** [comment]
please reopen the issue if it doesn't help.
