### ISSUE TITLE
June 2020 Endgame

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10720]
# June 2020 - Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.19

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

## Extensions Testing

Install the latest build of ADS from the link above.

#### VSIX Files

Extension | Changed in this Release?
-- | --
Admin Pack |  No
Admin Tool Extension for Windows | No
Agent | No
CMS  | No
Dacpac | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/dacpac/dacpac-1.5.0.vsix)
Import | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/import/import-0.15.0.vsix)
Profiler | No
Schema Compare | No
PostgreSQL | No
Query History | No
Data Virtualization | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/datavirtualization/datavirtualization-1.5.0.vsix)
Machine Learning | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/machine-learning/machine-learning-0.1.0.vsix)
SQL Assessment | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/sql-assessment/sql-assessment-0.1.0.vsix)
## Scenario Sign Off

- [ ] Query Editor @anthonydresser 
- [x] Notebooks  @chlafreniere 
- [x] Edit Data @smartguest 
- [x] ADS Shell @kburtram 
- [x] Livesite tooling @qifahs, @MsSQLGirl      
- [x] Data Virtualization @Charles-Gagnon   
- [x] Acquisition @kburtram 
- [x] Connection @Charles-Gagnon 
- [x] Language Service @Charles-Gagnon 
- [x] Query History @Charles-Gagnon 
- [x] Spark Job Submission @chlafreniere 
- [x] Resource Deployment @alanrenmsft 
- [x] Books @MaddyDev 
- [x] Charting and Insights @alanrenmsft 
- [x] Dashboard @alanrenmsft  
- [x] Backup/Restore @udeeshagautam 
- [x] File Import @kenvanhyning / @aasimkhan30 
- [x] DacFx Deployment @kisantia 
- [x] SQL Profiler @alanrenmsft 
- [x] CMS @abist 
- [x] SQL Agent @abist 
- [x] Azure Integration @aaomidi
- [x] Extension Manager @alanrenmsft 
- [x] Schema Compare @kisantia / @udeeshagautam 
- [x] Big Data Cluster @Charles-Gagnon 
- [x] SSMS Integration @Charles-Gagnon 
- [x] Data Explorer @abist 
 
## Partner Signoffs
- [x] PGSQL @akamath46297 
- [x] SQL On Demand @BranislavGrbicMDCS 
- [x] SQL Assessment @alexprotsenko 

[win-user]: https://go.microsoft.com/fwlink/?linkid=2132305
[win-system]: https://go.microsoft.com/fwlink/?linkid=2131971
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2131970
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2131972
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2132306
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2131974
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2131973

**Comment by swjain23** [comment]
Hi,

The fix for AAD auth is not included in this release. I am getting the same "Failed to get Azure account token for connection" error. I see that the fix is still open: https://github.com/microsoft/azuredatastudio/pull/10662.

**Comment by aaomidi** [comment]
@swjain23 I'm going to remove your comment here as this was meant to be locked. Could you please update that issue or make a new issue?

**Comment by aaomidi** [comment]
@swjain23 has your team confirmed that PR solves your problem?

**Comment by swjain23** [comment]
@aaomidi - Let me follow up.
