### ISSUE TITLE
Dashboard 'Tables' table '...' doesn't do anything

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#10736]
- Azure Data Studio Version: `1.19.0`

Steps to Reproduce:

1. Open the Dashboard DB page
2. Click on the '...' in the Table list

Expected: Pop-up with list of available commands
Actual: Nothing happens

![image](https://user-images.githubusercontent.com/599935/83799311-75b0a600-a65a-11ea-95db-1c87fd4659ee.png)

**Comment by alanrenmsft** [comment]
this seems to be a Windows specific issue, let me look into it.
