### ISSUE TITLE
i have a linked azure account but the dialog is not showing it

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10734]
<img width="1053" alt="Screen Shot 2020-06-04 at 11 11 15 AM" src="https://user-images.githubusercontent.com/13777222/83795400-40a15500-a654-11ea-83a0-352f45299824.png">
<img width="503" alt="Screen Shot 2020-06-04 at 11 11 39 AM" src="https://user-images.githubusercontent.com/13777222/83795404-41d28200-a654-11ea-9367-1cc1e89a9ce3.png">

**Comment by aaomidi** [comment]
This issue is caused by the latest vscode merge. Does anyone have more experience with the splitView system? It seems something breaks each time we do a merge (this is the second issue in this area in the past month) that can help me out and validate if we're using this properly?

CC @anthonydresser @Charles-Gagnon

**Comment by alanrenmsft** [comment]
@aaomidi maybe this will help: https://github.com/microsoft/azuredatastudio/pull/10737

**Comment by Charles-Gagnon** [comment]
Not specifically - are you seeing an error?

**Comment by aaomidi** [comment]
@Charles-Gagnon It looks like we need a ViewContainer for the Account Pane view, I'm not sure if we have one?

https://github.com/microsoft/azuredatastudio/blob/5105694fb39498139480172d1d82de76b15893e6/src/sql/workbench/services/accountManagement/browser/accountDialog.ts#L332

This view needs to be registered under 		Registry.as<IViewsRegistry>(ViewContainerExtensions.ViewsRegistry).registerViews()

and that method is requiring a container for this. Not sure what to do here.

**Comment by aaomidi** [comment]
Hmm, I think I got it. I'll send a PR.
