### ISSUE TITLE
edit data editor is not showing any data

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10730]
<img width="963" alt="Screen Shot 2020-06-04 at 10 41 16 AM" src="https://user-images.githubusercontent.com/13777222/83792542-09c94000-a650-11ea-8d73-0e043641cfa8.png">

**Comment by smartguest** [comment]
A recent pull seemed to have caused this, I'm not sure which one it is.

**Comment by smartguest** [comment]
It appears to be an error involving the slash for HorizontalSlashWidth in HorizontalFlexibleSash

**Comment by alanrenmsft** [comment]
@smartguest that seems to be correct, I have another issue related to that: https://github.com/microsoft/azuredatastudio/issues/10729, please include me in your PR, that might make it easier for me to fix this one, i will look into another issue first.

**Comment by smartguest** [comment]
@alanrenmsft It seems to be that in flexibleSash, the way the sash was being created and used does not reflect the current Sash code, it will need to be rewritten

**Comment by alanrenmsft** [comment]
@smartguest do you mind joining today's DRI meeting to share your findings?

**Comment by smartguest** [comment]
Yeah sure, I will.

**Comment by smartguest** [comment]
nevermind, a simple null check was enough to resolve the problem
