### ISSUE TITLE
Mac: Cannot select multiple cells

### ISSUE THREAD

**Issue by soundskinky** [microsoft/azuredatastudio#10745]
Issue Type: <b>Bug</b>

On a Mac:
In the table returned by a SQL query, need to be able to shift-click and cmd-click to select a contiguous or disjoint set of cells, such as to copy a set of values in order to paste them into another query or an external app.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:11:42.467Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by abist** [comment]
@soundskinky Thanks for opening this bug @soundskinky. I cannot seem to repro this bug, could you check your developer console (`Help` -> `Toggle Developer Tools` or `Ctrl/Cmd+Shift+I` ->`Console`) and see if there are any errors there?
