### ISSUE TITLE
Some notebook cell actions take two clicks now

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#10741]
previously if i want to do some actions on the cell, i can click on the '...' button on the top right corner of the cell, for example, i want to run all cells before.

now, i had to first make the target cell as active, this is kind of annoying thing caused by the one extra click 😃

**Comment by chlafreniere** [comment]
This is by design for now. But let's keep it in the backlog for now.

**Comment by chlafreniere** [comment]
This has been active for 6 months and is by design. Closing it.
