### ISSUE TITLE
Error: Failed to get Azure account token for connection

### ISSUE THREAD

**Issue by evertonmc** [microsoft/azuredatastudio#10763]
Issue Type: <b>Bug</b>

Getting `Error: Failed to get Azure account token for connection` when trying to connect to a database by using an AAD Connection.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:05:17.848Z)
OS version: Linux x64 4.15.0-1081-oem

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 4072)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 1|
|Memory (System)|31.06GB (19.11GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6

</details>

**Comment by evertonmc** [comment]
also teste at 

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (24.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6


</details>

**Comment by evertonmc** [comment]
and 

Azure Data Studio version: azuredatastudio-insiders 1.19.0-insider (ce17a73edecab492ca2244b142c19f04d8df3871, 2020-06-04T05:37:31.582Z)

**Comment by kburtram** [comment]
@aaomidi any ideas on this one?  Or how to collect additional diagnostic information?

**Comment by evertonmc** [comment]
Seems to be solved in the newest insider... probably related to #10662 #10753 
Azure Data Studio version: azuredatastudio-insiders 1.19.0-insider (22d7c9083eba69683a9e36ec1f1e74c7981a7626, 2020-06-09T05:29:30.988Z)

**Comment by aaomidi** [comment]
Will close this issue then!

Thanks!

**Comment by jdms754** [comment]
I am able to reproduce still. Issue appeared recently. Deleted the folder in %appdata%, but that did not resolve it.

Version: 1.21.0-insider (user setup)
Commit: 53ec7585a9da594c2465bfffa01238d1efc190a7
Date: 2020-07-22T05:58:57.276Z
VS Code: 1.48.0
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19635

**Comment by babak1199** [comment]
Started to get this error recently after upgraded to 1.25.2. Deleting %appdata% resolved my issue but had to re-enter plenty of data.

Version: 1.25.2 (user setup)
Commit: [4d4917d328ab7a7526817a0f0ef03237a79aa54d](https://github.com/microsoft/azuredatastudio/commit/4d4917d328ab7a7526817a0f0ef03237a79aa54d)
Date: 2021-01-20T22:52:13.492Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
