### ISSUE TITLE
Remainder Obj folder from ADS doesn't let following project build succeed in SSDT

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#10779]
- Azure Data Studio Version: Dev build 

Steps to Reproduce:

1. Build a project in ADS - works fine
2. Close ADS and open the same project in SSDT
3. Build the project in SSDT
4. Fails to build (because of preexisting obj folder - even clean build doesnt clean the obj folder
5. Clean/delete the object folder manually (workaround)
6. build passes

Adding P1 for review but this has an easy workaround so not sure if this is P1 for June

**Comment by udeeshagautam** [comment]
@dzsquared @MsSQLGirl - we'll try to take this but any thoughts if this is a blocker for this month?

**Comment by dzsquared** [comment]
@udeeshagautam not a blocker for June to me, due to GUI-based and quick workaround

**Comment by udeeshagautam** [comment]
closing this.
