### ISSUE TITLE
Should make sqlops dropdown to look the same as VScode custom select box

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#1077]
VScode has introduced custom select box. We should make the look of editable drop down  (refactor) to be the same.

**Comment by anthonydresser** [comment]
is this just for the arrow? it looks the same to me other than the arrow

**Comment by AbbiePetcht** [comment]
I think it's just the arrow

**Comment by kburtram** [comment]
Closing older issues.
