### ISSUE TITLE
Edit/close button not working on code cells 

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#10771]
- Azure Data Studio Version: 1.19.0-RC1

Steps to Reproduce:

1. Create a new empty notebook
2. Create a multi line code cell 
3. Select the code cell when it's collapsed and click on close/edit icon.

The cell doesn't have the same behavior as markdown cells 

![close-icon](https://user-images.githubusercontent.com/34872381/83912087-1fa73580-a722-11ea-88d7-06b6aa13f789.gif)

**Comment by Charles-Gagnon** [comment]
This was fixed by https://github.com/microsoft/azuredatastudio/pull/10719 - code cells shouldn't have the edit action.
