### ISSUE TITLE
Markdown cell more actions has extra separator

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10800]
Bottom one is unnecessary and should be removed.

Visible only in Windows client.

![image](https://user-images.githubusercontent.com/28519865/84084439-55555400-a998-11ea-8700-3df3bd9f6b21.png)

**Comment by chlafreniere** [comment]
@halerankin could you take a look at this? Not a June release issue, but would be great to fix over the next couple of weeks.

**Comment by chlafreniere** [comment]
Fixed by #10827.
