### ISSUE TITLE
Notebook toolbar connection dropdown too small

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#10808]
Repros in both RC and current master

![image](https://user-images.githubusercontent.com/28519865/84088434-58087700-a9a1-11ea-8d42-0893523c6cb3.png)

18.1 : 

![image](https://user-images.githubusercontent.com/28519865/84088481-78383600-a9a1-11ea-8ab5-b748aca55517.png)

**Comment by Charles-Gagnon** [comment]
@halerankin Assigning this to you since you've been doing work in this area - something to look at when you get some time

**Comment by halerankin** [comment]
@Charles-Gagnon I just tested this on Mac OS and on Windows. I see the following:
![notebook-ui-main](https://user-images.githubusercontent.com/12279161/87972085-30fe9400-ca7b-11ea-863f-40813219e2c5.PNG)
There does not appear to be a layout issue with the dropdown arrow for each.

**Comment by Charles-Gagnon** [comment]
Looks fine on main for me now - possibly some temporary issue from vs code merge. Will close for now.
