### ISSUE TITLE
Notebook toolbar > Add cell button tooltip is incorrect

### ISSUE THREAD

**Issue by halerankin** [microsoft/azuredatastudio#10828]
- Azure Data Studio Version: latest

Steps to Reproduce:

1. Hover over add cell button to reveal tooltip: "Code cell".

![image](https://user-images.githubusercontent.com/12279161/84189897-da994100-aa4a-11ea-817f-67c49bdc80f6.png)

This should be corrected to read: "Add cell"

**Comment by kburtram** [comment]
Approved in shiproom.

**Comment by chlafreniere** [comment]
This was previously merged in (see linked PR).
