### ISSUE TITLE
Unable to connect to an Azure Synapse Instance from Azure Data Studio

### ISSUE THREAD

**Issue by basilcherian** [microsoft/azuredatastudio#10839]
Open Azure Data Studio, enter the connection string, provide the connection type (MFA 2FA). When clicking on Connect, it simply rotates forever and never connects. 
This issue is applicable only when I try to connect from a specific machine. Please help resolve the same.

**Comment by kburtram** [comment]
@aaomidi any thoughts on how to troubleshoot this one?

**Comment by aaomidi** [comment]
We definitely need more logs on this. @basilcherian can you click Help -> About on the machine you're having issues from and send us the information? Also, the same process on the machines you're not having a problem on.

Would be good to see what the differences between these two machines are.
