### ISSUE TITLE
Requesting Interactive Sorting of Results

### ISSUE THREAD

**Issue by pareshmotiwala** [microsoft/azuredatastudio#10847]
Like the IntelliJ which helps you interactively sort results, would serve adhoc query writers a lot by avoiding expensive sorts.

**Comment by pareshmotiwala** [comment]
Can somebody explain, what does the status mean? sorry I am not familiar with this!

**Comment by pareshmotiwala** [comment]
@kburtram any word on this please?

**Comment by Charles-Gagnon** [comment]
@alanrenmsft We can close this now, right?

@pareshmotiwala We recently added sorting to the results grid, could you check out the latest builds and see if that fits your needs?

**Comment by pareshmotiwala** [comment]
I will ! Let me get back to you 

Apologies for the brevity of the email 
as it is sent from my iPhone.
Regards
Paresh Motiwala

**Comment by pareshmotiwala** [comment]
I tried with 18.10 and it did not work.
Am I missing something?

*Paresh Motiwala*

**Comment by Charles-Gagnon** [comment]
SSMS does not currently have this feature - which given the version number sounds like what you were using.

This forum is for Azure Data Studio issues only, are you also still not seeing the feature here?

SSMS feedback can be given at https://feedback.azure.com/d365community/search/?q=ssms

**Comment by pareshmotiwala** [comment]
I do see it in ADS although I had requested fir SSMS! This is surely a good start!
Thank you

Apologies for the brevity of the email 
as it is sent from my iPhone.
Regards
Paresh Motiwala
