### ISSUE TITLE
CMS can't register azure ad auth type

### ISSUE THREAD

**Issue by drdamour** [microsoft/azuredatastudio#10872]
- Azure Data Studio Version:1.18.0

Steps to Reproduce:

1. add a centralized server
2. attempt to add a server registration
3. the authentication option only lists windows authentication and non of the AAD options

**Comment by cheenamalhotra** [comment]
Duplicate of #17264

**Comment by drdamour** [comment]
think this was a mistaken dupe...that other ticket is about adding a cms...this is about registering a new server within a cms
