### ISSUE TITLE
Prompting for connect every time

### ISSUE THREAD

**Issue by Proavtor** [microsoft/azuredatastudio#10871]
Issue Type: <b>Bug</b>

1. Open saved before sql file and connect to database
2. Open another saved sql file
3. Switch to the first file at another tab by clicking to the file in explorer and ADS propt to connect although this tab has already connected

Azure Data Studio version: azuredatastudio 1.18.0 (2acd37a1b1cff34b64fbb4ea2d40715d7e2accac, 2020-05-19T23:54:30.554Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (1.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|10.4.3
vsc-material-theme|Equ|30.0.0
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
azuredatastudio-postgresql|Mic|0.2.6
import|Mic|0.15.0
managed-instance-dashboard|Mic|0.4.1
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.4.0
server-report|Mic|0.2.2
whoisactive|Mic|0.1.4
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.3
vscodeintellicode|Vis|1.2.1

</details>

**Comment by smartguest** [comment]
Issue does not repro when opening a saved SQL file and connecting it to a database. Opening another file shows its connected to the same database. Clicking on the first SQL file in explorer shows it is still connected.

**Comment by smartguest** [comment]
@Proavtor have you tried the latest build yet and see if it was able to be reproduced there?
