### ISSUE TITLE
File browser error on Ubuntu 18.04

### ISSUE THREAD

**Issue by priverop** [microsoft/azuredatastudio#10876]
Issue Type: <b>Bug</b>

1. Click on Restore a database.
2. Select "Restore from Backup file".
3. Click on the three dots to select the path.
4. Wait for the error screen to show with the message: File browser error. An error occured while loading the file browser.
Also, there is already a selected path when you click the three dots: "D:\rdsdbdata\BACKUP". The same issue happened in 1.17.1.
I've seen this error multiple times but every issue is closed as they were solved.

Azure Data Studio version: azuredatastudio-rc1 1.19.0-rc1 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T06:28:43.810Z)
OS version: Linux x64 4.15.0-101-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 2876)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|15.54GB (0.23GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by kburtram** [comment]
I haven't seen this repro on recent builds.  Please let us know if you're still impacted by this issue.
