### ISSUE TITLE
Notebooks used by functionality exposed by Resource Deployment Extension Requires Pandas, but Pandas not Installed by Default

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#10886]
Some of our notebooks (including deployment scenarios) require pandas to be installed, but we don't install pandas by default any longer when selecting the Python kernel. Need a solution that makes the process more smooth.

Not a regression from May. Reported internally.

Affected users:
Windows users who select to install Python kernel dependencies only.

(i.e. if users install requirements for all kernels and/or are on Linux/Mac, they are unaffected). Workaround is to install pandas using the Manage Packages functionality.

**Comment by ranasaria** [comment]
So, these are the notebooks that require pandas' functionality. This can be removed from other notebooks as it is just copied and pasted dependency that has percolated over.
![image](https://user-images.githubusercontent.com/41588310/99018024-01820480-250e-11eb-99b3-94daac30cf99.png)

**Comment by ranasaria** [comment]
So, these are the notebooks that require pandas' functionality. This can be removed from other notebooks as it is just copied and pasted dependency that has percolated over.
![image](https://user-images.githubusercontent.com/41588310/99018024-01820480-250e-11eb-99b3-94daac30cf99.png)
