### ISSUE TITLE
Cannot select Add  Account type like Azure China Mooncake

### ISSUE THREAD

**Issue by hundunmuchi** [microsoft/azuredatastudio#10893]
Issue Type: <b>Feature Request</b>

This tools feature is very awsome for Data analysis, but unluck it is not working for China azure data source. 
Would you please help suggest how can I add Azure China account into studio?
Thanks.

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:14:29.147Z)
OS version: Windows_NT x64 10.0.18363

**Comment by aaomidi** [comment]
I will bring this to PM attention.

@yualan

**Comment by aaomidi** [comment]
Closing in favor of #9832 - please express your interest for the China cloud region on that issue. Thanks!
