### ISSUE TITLE
Provide support for deleting database via context menu

### ISSUE THREAD

**Issue by tomkerkhove** [microsoft/azuredatastudio#109]
### SQL Operations Studio Version
0.23.6

### Steps to Reproduce:
1. Connect to server
2. Right click on database
3. Context menu shows up with following values:
      - Manage
      - New Query
      - Refresh

### Feature Request
It would be good to have the option "Delete" that removes the database instead of having to write a `DROP DATABASE` script

**Comment by kevcunnane** [comment]
@llali if we implement this please remember the Azure SQL DB scenario (e.g. kick off a job for this and show in our jobs viewlet, since it can take a while).

**Comment by tomkerkhove** [comment]
Thanks for considering this!

**Comment by sashwin** [comment]
@kburtram This would be really nice to have. Please plan for this.

**Comment by cheenamalhotra** [comment]
"Drop" operation is supported in preview Basic Admin features on Databases. 

Closing as resolved.
