### ISSUE TITLE
Standardize on sqlproj slashes

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#10905]
Standardize on slash direction (/ vs \) for when moving a project between platforms. After some initial investigation, it looks like SSDT is able to build correctly with / slashes and ADS on mac is able to build correctly with \ slashes, so it seems feasible to standardize on one direction. However, more testing needs to be done to ensure this will work.

**Comment by Benjin** [comment]
Standardize on backslash for writing, convert to local at runtime for displaying the tree

**Comment by kisantia** [comment]
confirmed that csproj also uses backslashes on Mac
