### ISSUE TITLE
IntelliSense incorrect behavior with carriage return on group by

### ISSUE THREAD

**Issue by mattneerincx** [microsoft/azuredatastudio#10916]
Issue Type: <b>Bug</b>

If I type in the following text:

select
   *
from
    sometable
group

Then I place the cursor after group and type in by in lower case and hit enter.  The IntelliSense does not move to next line and also capitalizes BY.   The default behavior should just be move to next line (I have to hit enter 2 times to go to next line).   

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:08:06.892Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (24 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.93GB (229.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by sql-koala** [comment]
Hi, you can solve this for yourself with config in keybinding.json:
```
    {
        "key": "enter",
        "command": "-acceptSelectedSuggestion",
        "when": "acceptSuggestionOnEnter && suggestWidgetVisible && suggestionMakesTextEdit && textInputFocus"
    },
```
For Azure DS you basically need to disable Enter key to accept (intellisense) suggestions.

**Comment by kburtram** [comment]
This is the upstream behavior of vscode intellisense so closing as external.  We are considering adding a "GROUP BY" completion suggestion which would likely help a little for this specific scenario.  Thanks for reporting this issue.
