### ISSUE TITLE
Manual widget repositioning problem

### ISSUE THREAD

**Issue by GreyOrGray** [microsoft/azuredatastudio#1091]
- SQL Operations Studio Version: 0.28.1

I realize this is probably low importance, but using the edit option to manually position dashboard widgets can shove them into unexpected places or cause widgets to completely cover other widgets.

Steps to Reproduce: Click the _edit_ pencil and drag widgets around.

Normal:
![image](https://user-images.githubusercontent.com/33128934/38433159-13d543ba-3987-11e8-9f71-365444f62245.png)

From Normal state - Tried to drag my Task Errors widget down:
![image](https://user-images.githubusercontent.com/33128934/38433217-465f5a96-3987-11e8-8544-0d7fd6350983.png)

From Normal state - Moved my large widget to the right:
![image](https://user-images.githubusercontent.com/33128934/38433314-9a28a77c-3987-11e8-8896-dc0dd65489fd.png)

Now my Task Errors widget is just sitting behind the larger one.
![image](https://user-images.githubusercontent.com/33128934/38433352-ba114ff8-3987-11e8-9645-20dbde053dc1.png)

**Comment by kburtram** [comment]
Closing out older issues.  We're refactoring the dashboard in the next couple months and will resolve\replace this particular functionality.  Thanks for reporting!
