### ISSUE TITLE
Notebook Viewlet doesn't highlight activated / opened file from Search viewlet

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#10938]
- Azure Data Studio Version:
Version: 1.18.1 (user setup)
Commit: 5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa
Date: 2020-05-26T21:14:29.147Z
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Go to Search Viewlet.
2. Search for a keyword.
3. Open the file from the search result.
4. Navigate to the Notebook viewlet.
Here you can see that the activated / opened file is not highlighted. So if user wants to open the neighboring notebook, they won't be able to. 

Expected: Activated / opened file from Search viewlet should be highlighted in Notebook viewelet.

**Comment by Charles-Gagnon** [comment]
This sounds like the issue @MaddyDev fixed - can you update to 1.19 and try it there?

**Comment by MsSQLGirl** [comment]
Oh yes.. I was going to add that I could repro in 1.19.
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

I also talked offline with @MaddyDev on this. She can repro too.

**Comment by MaddyDev** [comment]
This is not a regression and has the same behavior on prior releases as well. (@MsSQLGirl can you confirm that) We fixed a regression on the highlight behavior in 1.19.

**Comment by MsSQLGirl** [comment]
Correct. Not regression.
