### ISSUE TITLE
Issue copying data from notebook grid

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#10931]
Me Too!  have tried close and reopen..  still no luck
![copypaste](https://user-images.githubusercontent.com/63085169/84717448-26069e80-afb9-11ea-8d2d-e35fa5da3734.gif)

![image](https://user-images.githubusercontent.com/63085169/84717470-40d91300-afb9-11ea-9ebf-e7e3e88c447d.png)

_Originally posted by @don-binerd in https://github.com/microsoft/azuredatastudio/issues/10335#issuecomment-644453968_

**Comment by lucyzhang929** [comment]
Resolved in latest version of ADS.
