### ISSUE TITLE
"Explain" button just runs the query, without showing query plan

### ISSUE THREAD

**Issue by jialinding** [microsoft/azuredatastudio#10945]
Issue Type: <b>Bug</b>

When writing a query, pressing the "Explain" button has the same effect as pressing "Run". That is, it returns full results and has no tabs for "Query Plan" or "Top Operations". This happens even on simple queries (for example, the default "Select top 1000" query for a given table).

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|47.72GB (34.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by kburtram** [comment]
@jialinding I wasn't able to repro with basic testing.  Is there any additional information you could provide to help isolate the problem? e.g., which version of SQL Server running against, extensions installed, etc.?

Here's what I'm seeing with SELECT 1000 against SQL Server 2019.

![image](https://user-images.githubusercontent.com/599935/84837590-5ec06b00-afed-11ea-8f3a-38ad15ef1597.png)

**Comment by jialinding** [comment]
@kburtram I have no extensions downloaded, and I am connecting to an Azure Synapse SQL pool instance. I just downloaded and re-installed the newest version of Data Studio and the problem is slightly different now: the first time I press the "Explain" button, it works as expected and there is a "Query Plan" tab. But if I press "Explain" again, it just runs the query. If I disconnect from the SQL pool and re-connect, then the button works again. Here is a gif of what happens:

![2020-06-16-19-40-15](https://user-images.githubusercontent.com/7818796/84839171-64787980-b00a-11ea-813d-e9a8b6ca00e3.gif)

**Comment by kburtram** [comment]
Unfortunately query plan doesn't currently work with DW connections.  This is being tracked with issue https://github.com/microsoft/azuredatastudio/issues/2273.
