### ISSUE TITLE
Update to SqlToolsService 3.0.0-release.1 breaks Database Project build

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#10943]
Via PR https://github.com/microsoft/azuredatastudio/pull/10935
FYI to @kburtram

**Comment by kburtram** [comment]
@Benjin the main change here is to upgrade to .Net Core SDK 3.0.

**Comment by Benjin** [comment]
Yup; I'm looking into what needs changing on our end to facilitate the new version.

**Comment by kburtram** [comment]
@Benjin cool, let me know if there are any hard blocking issues that need to be resolved.  If necessary, we can rollback the upgrade while the issues are worked through.  But since .Net Core 2 is approaching end of life, we'll want to get this upgrade in relatively soon.

**Comment by Benjin** [comment]
Leaving this open until SqlToolsService is back to the updated version (including the updated DacFx)

**Comment by Benjin** [comment]
Updated DacFx came into SqlToolsService with https://github.com/microsoft/sqltoolsservice/pull/986
