### ISSUE TITLE
Cannot see long error message because horizontal scroll is missing

### ISSUE THREAD

**Issue by jovanpop-msft** [microsoft/azuredatastudio#10956]
- Azure Data Studio Version: 1.19.0

I have executed some SQL query that has longer error message. In the **Messages**  tab is shown error message but since it is long I cannot see the end of the message. There is no horizontal scroll.

I need to copy entire error message and paste it in some editor to see what is the issue.

Steps to Reproduce:

1. Execute some statement that will cause long error message (see example below). 

![image](https://user-images.githubusercontent.com/20593304/84885747-bfa27e80-b093-11ea-936b-8250fec622a6.png)

**Comment by anthonydresser** [comment]
This was caused by #10554, working on a generic fix now.
