### ISSUE TITLE
Creating project for master db, opening editor does not have master as selected db

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#10981]
- Azure Data Studio Version:

Steps to Reproduce:

1. Create SQL project
2. Add a table item which already exists in master
3. build the project
4. close the editors
5. from problems panel, find the error in the table and click on it

Expected: the editor should open with "master" as selected db
Actual: Database dropdown doesn't have anything selected. in onecase it showed undefined

**Comment by udeeshagautam** [comment]
- Not Letting user connect and shows undefined in drop down
- Check if it specifically happens master or other databases too

(the expectation is not really that it should be connected but should allow user to connect at least)

**Comment by udeeshagautam** [comment]
@llali I tried this with and without master db and I am always able active connection wen there is one in connetcion explorer and connect button enabled when there is none. based on the expectation that looks correct - can we close this?

![image](https://user-images.githubusercontent.com/46980425/87352282-a87a7380-c50f-11ea-8c3b-d2632c528f9b.png)

![image](https://user-images.githubusercontent.com/46980425/87352220-900a5900-c50f-11ea-8b46-59a525dc6b31.png)

**Comment by llali** [comment]
sure if it works as expected let's close it. Thanks

**Comment by udeeshagautam** [comment]
closing for now as discussed
