### ISSUE TITLE
files not arranged in folders when sqlproj created on windows is opened on mac

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#10986]
Steps to Reproduce:

1. Create a new project on Windows in SSDT by importing a database so it has some files and folders
2. Copy the folder of the project to a mac
3. Open the project in ADS on mac

Actual:
<img width="263" alt="Screen Shot 2020-06-17 at 2 26 50 PM" src="https://user-images.githubusercontent.com/31145923/84952485-e4542180-b0a6-11ea-9088-72a31ce08b31.png">

Expected:
It should be displayed the same way that it was in SSDT
<img width="370" alt="Screen Shot 2020-06-17 at 2 30 16 PM" src="https://user-images.githubusercontent.com/31145923/84952618-182f4700-b0a7-11ea-97df-af597f57aa6a.png">
And how ADS on windows shows it
![Screen Shot 2020-06-17 at 2 31 58 PM](https://user-images.githubusercontent.com/31145923/84952747-53317a80-b0a7-11ea-825b-8018af4c7b58.png)

**Comment by udeeshagautam** [comment]
Related less severe issue from other side of round tripping : https://github.com/microsoft/azuredatastudio/issues/11018
