### ISSUE TITLE
Publish doesn't show details about connection error

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#10985]
- Azure Data Studio Version:

Steps to Reproduce:

1. Create SQL project
2. Add tables 
3. Publish to a server

Actual: the connection fails and it's not clear why. there's not actual error
Expected: If connection fails for the publish, it should show the error details

**Comment by Benjin** [comment]
Thought this already happened when publish failed.  Confirm the current behavior and circle back with Leila if behaving as expected

**Comment by udeeshagautam** [comment]
As per the current UI -
1. connection happens with connections dialog before starting publish so all initial errors are surfaced that way.
2. if connection fails during publish, deploy task shows the full error.

![image](https://user-images.githubusercontent.com/46980425/164787331-3f6840ef-6e19-4fc0-ac83-64580808beea.png)

Hence closing. Please reopen if this is still seen.
