### ISSUE TITLE
Not clear how to provide target connection in publish dialog 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#10984]
- Azure Data Studio Version:

the Edit button in the dialog is not clear to be for adding new connection.

**Comment by Benjin** [comment]
Ideas:
* Make connection-string box read-only
* Consider "Edit" rename to something else

To discuss with Raden

**Comment by dzsquared** [comment]
I would caution against making the connection string box read-only.  Users may be bringing connection strings from other sources - web deployment, key vault, (??).

I like the idea of renaming the "Edit" button.
