### ISSUE TITLE
Updating database in Schema Compare dialog doesn't enable "Ok" button

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#10987]
Steps to Reproduce:

1. Open Schema Compare.
2. Populate Source and Target databases for schema compare. Press 'Ok'.
3. Press '...' to update source or target. In the dialog, update either of the databases. 'Ok' still remains disabled.

**Comment by udeeshagautam** [comment]
not able to repro this in latest bits hence closing
