### ISSUE TITLE
Add Icons to DB Project Pane

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11001]
For users familiar with the files viewlet, the projects pane is missing the familiar actions icons.

Icons for "Add Item", "Add Folder", and "Collapse Folders" would aid the user in navigating the extension.

(collapse folders is a duplicate of #10979)

**Comment by udeeshagautam** [comment]
First set of icons added. Keeping it open to track for second set

**Comment by udeeshagautam** [comment]
@SakshiS-harma  to check for folder icon
