### ISSUE TITLE
Open DB Project Does Not Integrate with Source Control Provider

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11000]
- Azure Data Studio Version:
Version: 1.20.0-insider (user setup)
Commit: 95107f1f611df05f85e1cc7122f088f4d9cc6aec
Date: 2020-06-18T05:34:11.799Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open established sqlproj (in folder initialized for git)
2. Unless user also opens the project in files area, ADS source control does not parse changes

Following #10974 should the folder also be opened to tie into source control functionality?

**Comment by udeeshagautam** [comment]
Moving to ADO
