### ISSUE TITLE
Proxy Authentication Error

### ISSUE THREAD

**Issue by rrmetzger** [microsoft/azuredatastudio#11002]
- Azure Data Studio Version:
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

After install the program asks for proxy authentication on start, but the dialog is 'locked'. The fields are available, but pressing <Ok> or <Cancel> does nothing. 

Steps to Reproduce:

1. Start from the desktop
2. Upon loading, when you have proxy the dialog will show up
3. Filling the fields of user and password works, but pressing <Ok> or <Cancel> does nothing, it is only possible to close the dialog on the window, and the proxy authentication fails.

**Comment by cssuh** [comment]
closed with #18296
