### ISSUE TITLE
Stuck at step 2 of Create a new book.

### ISSUE THREAD

**Issue by ahkenho** [microsoft/azuredatastudio#11017]
- Azure Data Studio Version:
Version: 1.19.0
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:03:19.036Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0

Steps to Reproduce:
ran step 2 script, enter the folder for the book, then enter the location for notebooks and markdown. then get below error. Please help how to solve it in ADS.

Traceback (most recent call last):
  File "/Users/xxx/azuredatastudio-python/0.0.1/bin/jupyter-book", line 8, in <module>
    sys.exit(main())
  File "/Users/xxx/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/xxx/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/click/core.py", line 760, in main
    _verify_python3_env()
  File "/Users/xxx/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/click/_unicodefun.py", line 130, in _verify_python3_env
    " mitigation steps.{}".format(extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8

**Comment by ahkenho** [comment]
I have set the encoding in Terminal to en_US.UTF-8, and still getting the same error.
export LC_ALL=en_US.UTF-8

and I see both LC-ALL and LANG is set to en_US.UTF-8.

**Comment by MaddyDev** [comment]
@ahkenho are you able to run other notebooks? (python)

**Comment by MaddyDev** [comment]
Closing this since we have UI based CreateBook and are no longer using the notebook to create book.
