### ISSUE TITLE
Notebook results showing password

### ISSUE THREAD

**Issue by kevchant** [microsoft/azuredatastudio#11024]
Issue Type: <b>Bug</b>

Hi, spotted something unusual the other day and thought I better report it.

If you use the Deploy SQL Server Wizard to create a container the password is hidden for the results of the 'Required information' cell.

However, in the 'Start a new container' section it is very visible, so you have to be careful if sharing notebooks. Is this expected, or should this password also be hidden?

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chlafreniere** [comment]
@alanrenmsft can you take a look at this?

**Comment by alanrenmsft** [comment]
@chlafreniere Should I work with @yualan on this?
