### ISSUE TITLE
SQL Project command palette selection of "add database reference" error

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11034]
- Azure Data Studio Version:
Version: 1.20.0-insider (user setup)
Commit: 340d8d37c94c7aea74fdea72d016654cb2f4f5bd
Date: 2020-06-19T05:33:29.191Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Open database project.  Optional: select "Database References" item in viewlet
2. Using the command palette select "Database Projects: Add Database Reference"
3. Error below:
> Command 'Database Projects: Add Database Reference' resulted in an error (Cannot read property 'root' of undefined)
4. Right click the "Database References" item in viewlet and select "Add Database Reference"  (works as expected)

**Comment by kisantia** [comment]
fixed by #11003. "Add Database Reference" shouldn't have been in the command palette
