### ISSUE TITLE
screen to display kube config info is stuck in spinning mode when config file is not present - Arc data controller extension

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#11035]
- Azure Data Studio Version:

Steps to Reproduce:

1. Deploy the Azure Arc data controller extension onto the latest insiders build
2. Launch the data controller wizard
3. In the screen where the wizard attemps to read the config file from the default path to display the cluster contexts, if the config file is not present, it seems to be stuck with a spinning wheel.

It should drop an error message "File not found. Please select a kube config file" ..

**Comment by alanrenmsft** [comment]
@ranasaria will you be able to fix in July milestone?

**Comment by ranasaria** [comment]
We will tackle it in August release. Planned to shipped in insiders before that.
