### ISSUE TITLE
AzureCore should maybe integrate with VSCode accounts

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#11044]
VSCode Accounts Added

![image](https://user-images.githubusercontent.com/1465785/85331681-6a97ab80-b48b-11ea-9fc1-bf593a1d6471.png)

Thoughts?

**Comment by Charles-Gagnon** [comment]
My gut instinct is "yes" since it's likely that this is something they're going to be using across the app so it seems to make sense to hook into this if we can. Have you been able to look at all into what that would take? Is this something that other extensions can contribute to?

**Comment by kburtram** [comment]
We'll likely want to keep our account management UX, but it will probably make sense to use the same underlying authentication\account storage subsystem at some point.  I'm not aware of any incoming vscode features that require us to escalate this work, so I think we're fine to do this some time in the next several months.
