### ISSUE TITLE
Show projects that fail to load in tree

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#11047]
Useful information to include in overall UX:
* message for why it failed to load
* context menu item for reloading

Steps to repro the issue:
Mangle the XML to remove either a few tags, skip element name or attribute information.

**Comment by kisantia** [comment]
option: in the notification that the project failed to load, add a button to open the .sqlproj. @SakshiS-harma can you take a look at this?

**Comment by SakshiS-harma** [comment]
After discussion, here are a few more options that can be tried:
- Toast notification to present the error of the failure, along with a button to open the .sqlproj file.
- Disable project (context menu to only have essential commands like Remove project, edit sqlproj file, open containing folder) with no children nodes.
- Project with only one child that prints the error.

**Comment by kisantia** [comment]
closing since there haven't been any other requests for this
