### ISSUE TITLE
Azure Data Studio Behind Proxy

### ISSUE THREAD

**Issue by Abhinav625** [microsoft/azuredatastudio#11056]
**Azure Data Studio Version:**
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Steps to Reproduce:**
1. Go to File->Preferences ->Setting->HTTP
2. Edit "http.proxy" :" " to "http.proxy" : "10.x.x.x:1234" 

**Issue:**
I am from network security team and one of our user want to use Azure Data Studio application. We have proxy enabled in our environment and we want this application to forward all outbound traffic via proxy. I have configured the proxy setting in the application but when I checked the logs the application is still not forwarding the traffic to proxy. Not sure what's the issue. 
How can I force this application to use proxy setting, please help, it is affecting production.
I searched for Azure Data Studio documentation but couldn't find single document showing how to configure proxy setting in this application.

**Comment by Abhinav625** [comment]
> Hi,
> 
> I have the same issue. Are there any failure updates by Microsoft?

Unfortunately, no update so far.

**Comment by nellang** [comment]
Still no update? I have the same issue :(

**Comment by cssuh** [comment]
closed with #18296
