### ISSUE TITLE
Intellisense not recognizing a view

### ISSUE THREAD

**Issue by JumbaJookiba** [microsoft/azuredatastudio#11057]
Issue Type: <b>Bug</b>

In the query editor, my view is not recognized as an existing item, and everything is underlined as error, although the query is correctly executed, when run.

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
qpi|joc|0.1.6
admin-tool-ext-win|Mic|0.0.2
dacpac|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.1
powershell|ms-|2020.4.0
query-history|Mic|0.1.0
azdata-sanddance|msr|1.3.9
schema-visualization|R0t|0.2.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@JumbaJookiba the IntelliSense schema suggestions come from a locally maintained metadata cache that is created when the query editor connection is established.  If the metadata is updated while the query editor is open it's possible for the cache to contain outdated info.  Please try running the `Refresh IntelliSense Cache` command from the Command Palette to rebuild the local cache on-demand.

**Comment by kburtram** [comment]
Closing based on previous comment.  Refreshing the cache should update local metadata.  If that doesn't work diagnostic error reporting can be disabled in the user settings.
