### ISSUE TITLE
Linked Account does not display non-ASCII characters

### ISSUE THREAD

**Issue by nesshoever** [microsoft/azuredatastudio#11055]
Issue Type: <b>Bug</b>

If the display name of a microsoft account contains non-ASCII characters, they are not displayed correclty encoded

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.18363

![2020-06-23_14-46-21](https://user-images.githubusercontent.com/11948164/85405303-7f923e80-b560-11ea-87cf-46b85114e4eb.png)

**Comment by cheenamalhotra** [comment]
Closing as we now support UTF8 characters
