### ISSUE TITLE
Notebook Data Export

### ISSUE THREAD

**Issue by goudstad** [microsoft/azuredatastudio#11068]
Issue Type: <b>Bug</b>

Environment: Azure Data Studio Notebook with SQL.  

Issues:
- Exporting data result to Excel spreadsheet does not include header.
- Copying data result to Excel is not comma-separated; all texts are joined together.

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.18362

**Comment by RicardoNoerr** [comment]
Also on Copy/Paste
