### ISSUE TITLE
ADS prompts for authentication for every tenant my AzureAD account has a guest account in.

### ISSUE THREAD

**Issue by Matteus-Andersen** [microsoft/azuredatastudio#11070]
- Azure Data Studio Version: 1.19.0

When I start ADS I get several prompts to authenticate to ever tenant that my azure account has a guest account in.
![image](https://user-images.githubusercontent.com/67370493/85546907-abbfc500-b61d-11ea-91db-75f5b05a7373.png)

This started after I updated to version 1.19.0.

Is there a way to specify the tenant ID I want to use?

**Comment by kburtram** [comment]
@aaomidi do you have any suggestions to resolve this issue?

**Comment by aaomidi** [comment]
The plan for the future in this space: We should load and refresh the azure accounts JIT instead of at startup.

**Comment by aaomidi** [comment]
@Matteus-Andersen This is expected for now - this is a limitation from your tenant and is based on the security settings of the tenant. We'll try to make the UX better in the future.

**Comment by Matteus-Andersen** [comment]
Is the limitation a setting I can change or something?

Also, is it possible to add a feature so that you can specify a tenant ID you want to connect to?

**Comment by Charles-Gagnon** [comment]
@aaomidi That's a good suggestion - having a filter list or something people could add tenant IDs to which would make us skip that when processing Azure stuff. Thoughts?

**Comment by aaomidi** [comment]
Yeah that was my initial thought. "Don't ask again" button, and it adds itself to the settings of the user.

@kburtram @alanrenmsft any thoughts on this suggestion?
