### ISSUE TITLE
Arc data controller deployment fails

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#11086]
- Azure Data Studio Version:

Steps to Reproduce:

1.Go through the Azure Arc data controller deployment and select a region that has multiple words such as "West US 2"
2. run the notebook.

The deployment fails because the region is not properly mapped back to westus2.

**Comment by ranasaria** [comment]
I will look at this since Charles is OOF.

**Comment by ranasaria** [comment]
Only East US, East US2, and Central US were the supported regions in azure arc deployments in the past. I synced up with Dinaker and I will make a check-in to expand this list to the following regions:
                "East US",
                "East US 2",
                "Central US",
                "East US 2 EUAP",
                "Central US EUAP",
                "West Europe",
                "Southeast Asia",
                "West US 2"

**Comment by ranasaria** [comment]
Upon further discussion with the platform team in the final check-in we decided to skip the following:

"East US 2 EUAP",
"Central US EUAP",

as the above are used only internally for testing.
