### ISSUE TITLE
Unable to change Account Password

### ISSUE THREAD

**Issue by spartan27244** [microsoft/azuredatastudio#11098]
- Azure Data Studio Version:

Steps to Reproduce:

1. Changed Azure AD Password
2. Unable to connect to Azure SQL database because it does not prompt for new password
3. Cannot Add a new Account

So I have no way to use this product anymore until I can get it to recognize a new password is needed.

**Comment by aaomidi** [comment]
What operating system are you using?

**Comment by spartan27244** [comment]
Windows Server 2016



Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by kburtram** [comment]
@spartan27244 have you tried removing and re-adding the account in the Account Manager dialog as a workaround for this bug?

**Comment by spartan27244** [comment]
There is no account management option in the app.

**Comment by aaomidi** [comment]
If you login with the new & correct password, it should just accept it and work fine.

If that's not working, open Credential Manager on windows. Go to Windows Credentials. Delete entries that start with `Microsoft.SqlTools`. This will delete your credentials associated with ADS.

**Comment by spartan27244** [comment]
It does not ask me to login

**Comment by aaomidi** [comment]
@spartan27244 What I meant was pressing "New Connection" and then entering the server details, username, and password (Assuming you're using SqlLogin) and pressing connect. That should overwrite whatever is currently stored.

**Comment by spartan27244** [comment]
I have tried deleting the connection and re-adding it. It remembers the account information and does not give me the opportunity to log in or change a password. It simply tri3es to connect and errors out.

**Comment by aaomidi** [comment]
Alright let's try to do the credential manager route then :)

**Comment by spartan27244** [comment]
And that would be?

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/issues/11098#issuecomment-653178559

> If that's not working, open Credential Manager on windows. Go to Windows Credentials. Delete entries that start with Microsoft.SqlTools. This will delete your credentials associated with ADS.

**Comment by spartan27244** [comment]
There is nothing in credential manager that even resembles that entry

**Comment by aaomidi** [comment]
So you don't have any entries that resemble:

![image](https://user-images.githubusercontent.com/1465785/86402298-7429cc00-bc60-11ea-93fb-3b3c6e0a3f45.png)
?

If that's the case whats the error you get when connecting to a server?

**Comment by spartan27244** [comment]
Not a single one

**Comment by spartan27244** [comment]
![Untitled](https://user-images.githubusercontent.com/45295245/86402540-fffc2200-bc79-11ea-86ba-f3e15f3cb300.png)

**Comment by spartan27244** [comment]
![Untitled](https://user-images.githubusercontent.com/45295245/86402636-2c17a300-bc7a-11ea-8bf5-53e860d6ff26.png)

**Comment by aaomidi** [comment]
Thanks! 

Can you press the + 
![image](https://user-images.githubusercontent.com/1465785/86402669-12b62d00-bc61-11ea-8d57-45d71c19332f.png)  here, and add your account again?

You can also press Help -> Toggle Developer Tools to get more context on what the error is when failing to refresh your account.

**Comment by spartan27244** [comment]
I see where you are pointing to and I see my credential there, I deleted it, and upon a reconnect attempt it now goes to a browser to get credential information. i.e. it works. Seems a lot to go through if you had a lot of connections and just needed to update your password.

Thanks.

**Comment by aaomidi** [comment]
Thanks! I mainly misunderstood your problem as being that you changed your SqlLogin password initially. Sorry about that!
