### ISSUE TITLE
Import New Database Project - Unable to save in root directory

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11107]
- Azure Data Studio Version:
Version: 1.20.0-insider (user setup)
Commit: 710d0462d8d81373aa2bc0f36f88955c902cb173
Date: 2020-06-25T05:31:00.820Z
VS Code: 1.46.0
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Right click on SQL Server 2019 database and choose Import New Database Project.
2. Use default name.
3. Choose SchemaObjectType.
4. Save on an empty drive.
![image](https://user-images.githubusercontent.com/6405919/85803739-b1d8a300-b6fc-11ea-8a0f-23b151a1fe03.png)

An error like this would appear
![image](https://user-images.githubusercontent.com/6405919/85803689-95d50180-b6fc-11ea-9311-beaa7da1a734.png)

**Comment by udeeshagautam** [comment]
Check if import is also creating a new folder with proj name - if not we may want to follow the same path
