### ISSUE TITLE
Seeking community feedback on SQL Database Projects extension (Insiders preview)

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11105]
### To bring project-based SQL database development to a cross-platform experience, we are announcing SQL Database Projects Extension (Insiders Preview) is now available in the latest [Azure Data Studio Insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main).

![Projects-Listing - Copy](https://user-images.githubusercontent.com/12227241/85800375-78a53080-b706-11ea-980a-507d7dc4136d.png)

## Getting Started with SQL Database Projects

* Create a new database project by going to the **Projects** viewlet under Explorer, or by searching for **New Database Project** in the command palette.
* Existing database projects can be opened via **Open Database Project** in the command palette.
* Start from an existing database by using **Import New Database Project** from the command palette.

![image](https://user-images.githubusercontent.com/12227241/85738927-06146080-b6c6-11ea-939f-5e1ce166f484.png)

Official documentation is available [here](https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-database-project-extension).

### Get started with database projects in Azure Data Studio today by grabbing the latest [Azure Data Studio Insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main).

**Comment by ErikEJ** [comment]
The linked "data tier application" article has too much confusing emphasis on .bacpac (and not enough on .dacpac)

**Comment by rrmistry** [comment]
Firstly, great work team 👍  Huge thanks from our whole team ❤️ !!!

Our specific requests by priority:
1. Ability to select verbosity of output for any SSDT tasks
   (e.g. "Import Project from Database" only creates 1 line log for import task saying "Extract project files succeeded ...")
1. Closer integration between Azure Data Studio folder workspaces and active SSDT project
   1. Is it possible to have a default `*.sqlproj` file that is always opened in a workspace? Something we can specify in the workspace settings?
   (ideally something that can be [parameterized](https://code.visualstudio.com/docs/editor/variables-reference) like `"${workspaceFolder}/${workspaceFolderBasename}.sqlproj"`)
   1. We have 1500+ objects in our SSDT project. This is tedious to navigate when the project is first opened. Could we have a "collapse folders" button on the `Projects` panel? (similar to "Collapse Folders in Explorer" button on folder panel)
   1. For newly imported project from database, open the project folder as workspace when import starts
   1. Prompt to initialize Git repo with default `.gitignore` and `.gitattributes` generated for SSDT project ([similar to VS Git initialization](https://github.com/github/gitignore/blob/master/VisualStudio.gitignore))
1. Ability to chain together build and deploy activities automatically from tasks. Maybe with https://github.com/microsoft/azuredatastudio/issues/10370
1. [SQL synonym support](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-synonym-transact-sql) for multi-schema databases
   Workaround available: manually edit `*.sqlproj` XML and add synonym that way
1. Simple support for pre/post deployment scripts. Maybe just allow users to use UI to add / remove these script
   Workaround available: manually edit `*.sqlproj` XML and add pre/post deployment scripts that way
1. Self-contained SSDT support without requiring users to install .NET Core SDK
   Acknowledge this is a big ask so low priority but very nice to have

**Comment by rishenp** [comment]
Im trying to build a .sqlproj file, and im getting the following error:
/Users/profile/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.1.2/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): Build error : .NET Core should not be using a file backed model. [/Users/profile/dev/test.sqlproj]

Any ideas?

**Comment by kburtram** [comment]
Closing older issues without recent interaction.  Please reactive if you're still seeking feedback on this preview.
