### ISSUE TITLE
Import New Database Project from live database does not show object explorer

### ISSUE THREAD

**Issue by kevinvngo** [microsoft/azuredatastudio#11115]
Version: 1.20.0-insider (user setup)
Commit: 710d0462d8d81373aa2bc0f36f88955c902cb173
Date: 2020-06-25T05:31:00.820Z
VS Code: 1.46.0
Electron: 7.3.1
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
Using Synapse SQL Pool (SQL DW).

1. Click Create project from Database

2. Connect to live Database
3. Click SchemaObjectType
4. Observe that there is no object explorer tree folder:
![image](https://user-images.githubusercontent.com/15145589/85816611-b020d680-b720-11ea-84ae-2b1c6c2fd890.png)

5. Note the scripts are folder structure was created:
![image](https://user-images.githubusercontent.com/15145589/85816676-dfcfde80-b720-11ea-8c39-128c3d304ee9.png)

**Comment by kisantia** [comment]
should be fixed by #11102
