### ISSUE TITLE
Find keeps refocusing you to the found item in Notebook

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#11120]
We have written the needed data into
Issue Type: <b>Bug</b>

1. Open a Notebook.
2. Click Ctrl + F and search for something that's present in a notebook cell.
3. After the item is found, switch to some other cell and start typing something  **( Note: Keep the find textbox open)**
4. After typing a single letter in the new cell, the notebook will automatically focus to the cell where something was found previously. 

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:06:05.429Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (12.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
pastetheplan|dre|0.2.0
agent|Mic|0.47.0
import|Mic|0.15.0

</details>

**Comment by chlafreniere** [comment]
@MaddyDev can you take a look?

**Comment by MaddyDev** [comment]
> @MaddyDev can you take a look?

Yep, I've actually fixed this in the search PR. I can send a separate PR addressing this.

**Comment by kburtram** [comment]
Approved in shiproom
