### ISSUE TITLE
Update text in Azure Arc extension

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#11147]
Update deployment wizard text
- [ ] Replace 'SQL DB managed instance' to 'Azure SQL managed instance – Azure Arc’
- [ ] Update azdata description with 'Deploy, manage and use Azure Arc enabled data services and Big Data Clusters

**Comment by twright-msft** [comment]
- [ ] Rename 'Docker account details' to 'Container registry details'

- [ ] Rename 'Docker account login' to 'Container registry login'

- [ ] Rename 'Password' to 'Container registry password'
