### ISSUE TITLE
Get 'Error: no such option: --content-folder' when create book(Preview)

### ISSUE THREAD

**Issue by pengyuehaha** [microsoft/azuredatastudio#11158]
- Azure Data Studio Version:
1.19.0
Steps to Reproduce:

1. Create Book(Preview)
2. When Running 'Create a new book' Cell, after input the book name and content folder I will get such error.
![error](https://user-images.githubusercontent.com/5258804/86166084-1151fc80-bac9-11ea-83f9-0de8beb362da.PNG)

**Comment by MaddyDev** [comment]
@pengyuehaha What values did you provide on destination and source input prompts?

**Comment by pengyuehaha** [comment]
I put C:\Book1 and C:\OSS\Spark\content. And the markdown files and notebooks are all under C:\OSS\Spark\content

**Comment by MaddyDev** [comment]
Can you open Manage Packages (the last icon the notebook toolbar located at the top right corner) and in your installed packages list, can you scroll and check the version of jupyter-book installed.

**Comment by pengyuehaha** [comment]
It is 0.7.0

**Comment by chlafreniere** [comment]
Ah, this is almost certainly because jupyter-book 0.7.0 has a breaking change with the folder structure, which we don't support yet.

**Comment by MaddyDev** [comment]
As an alternative until we roll our changes to fix this, Please make sure to install jupyter-book version <= 0.6.4 before running/using this notebook to create a book. (You can install using the manage packages and selecting the version 0.6.4)
