### ISSUE TITLE
Incorrect coloration when a string ends with a backslash

### ISSUE THREAD

**Issue by MarkStockwellZA** [microsoft/azuredatastudio#11150]
The issue is re-occurring in the latest version of VS Code and Azure Data Studio. Specifically, it seems to happen when the last character of a string literal is a backslash. Thanks.
<img width="1028" alt="Capture" src="https://user-images.githubusercontent.com/64535776/86108521-8d494600-bac3-11ea-9066-2517aabed0dd.PNG">

_Originally posted by @MarkStockwellZA in https://github.com/microsoft/azuredatastudio/issues/10208#issuecomment-651673844_

**Comment by Charles-Gagnon** [comment]
Looks like it just got into VS Code recently and is currently slated to be merged into our repo.

https://github.com/microsoft/azuredatastudio/pull/11149/files?file-filters%5B%5D=.json#diff-bb684abea1ae7b363da775aeba9b0bf6

I'll make sure this gets in for the July release of ADS - and VS Code should have the fix in their next major release. It looks like the VS Code insiders build has it fixed already so you can verify it on that in the meantime if you wish.

**Comment by Charles-Gagnon** [comment]
Moving this back into July - it's currently fixed in insiders and I just want to verify it in the RC build before closing this.

**Comment by Charles-Gagnon** [comment]
Verified fixed in RC build
