### ISSUE TITLE
OS X 10.10.15 Cannot Connect to Server or Account

### ISSUE THREAD

**Issue by chrisbabayans** [microsoft/azuredatastudio#11164]
- Azure Data Studio Version:1.19.0
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:03:19.036Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 14.5.0

Steps to Reproduce:
---No server connection----
1.OS X 10.10.15
2. +New Server Connection
3. Gets stuck for hours. I used my Windows 10 machine to connect with the same settings as quick as I expected

---No account connection---
1. OS X 10.10.15
2. Go to settings
3. Search "cloud" and make sure "Enable Public Cloud" is checked. I have enables all the clouds trying to connect.
4. Click on the bottom left icon to add an account
5. Click "add an account"
6. See "You have no clouds enabled" error message. I used my Windows 10 machine to connect with the same settings as quick as I expected

**Comment by chrisbabayans** [comment]
[Data studio logs OSX 10 10 15.zip](https://github.com/microsoft/azuredatastudio/files/4861601/Data.studio.logs.OSX.10.10.15.zip)
Here's the entire log folder. I appreciate your it.

**Comment by kburtram** [comment]
@chrisbabayans the only errors that seemed unusual in the log were ones like the following `[2020-06-30 21:40:49.823] [renderer1] [error] An unknown error occurred. Please consult the log for more details.`  Unfortunately this doesn't provide a lot of context on where to look for the problem.

@aaomidi do you have any suggestions for possible workarounds or additional diagnostics that could help troubleshoot?

**Comment by aaomidi** [comment]
Let's try to get you into a fresh state of the application.

Could you please open Terminal, and go to `~Library/Application Support`. Do you see a folder called `azuredatastudio`?

Can you delete that folder? `rm -rf azuredatastudio` should do the trick.


If you don't want to do this, we can start by trying to get more logs. Please open Azure Data Studio, and click Help -> Toggle Developer Tools. Keep this window open while trying to login to Azure. If it fails please paste in the `console` tab of the developer tools window as a comment to this issue.

Thanks!

**Comment by chrisbabayans** [comment]
`(base) Christophers-MacBook-Pro:Library christopherbabayans$ ls azuredatastudio
ls: azuredatastudio: No such file or directory
(base) Christophers-MacBook-Pro:Library christopherbabayans$ pwd
/Users/christopherbabayans/Library
`

No

**Comment by aaomidi** [comment]
Library/Application Support

**Comment by chrisbabayans** [comment]
```

(base) Christophers-MacBook-Pro:Application Support christopherbabayans$ pwd
/Library/Application Support

(base) Christophers-MacBook-Pro:Application Support christopherbabayans$ ls azuredatastudio
ls: azuredatastudio: No such file or directory
(base) Christophers-MacBook-Pro:Application Support christopherbabayans$ 
```

Still no

**Comment by aaomidi** [comment]
By any chance is it `Azure Data Studio`?

**Comment by chrisbabayans** [comment]
```
$ pwd
/Library/Application Support
$ ls Azure*
ls: Azure*: No such file or directory
$ ls Azure\ Data\ Studio
ls: Azure Data Studio: No such file or directory

```
No

**Comment by aaomidi** [comment]
Alright in that case lets try to do the other suggestion.

 Please open Azure Data Studio, and click Help -> Toggle Developer Tools - click on the console tab. Try to add your Azure account to the application again with the + sign on the Azure pane. Does the application provide any more interesting information in the logs?

**Comment by chrisbabayans** [comment]
I drew lines in Console View PNG connecting the message to the button clicked to cause it. On the right side of the screen, you can see the connection pane is stuck. 

![Console View](https://user-images.githubusercontent.com/12175419/86985250-af873780-c145-11ea-94d5-04deaae51d20.png)

Below is a picture of the enabled clouds so we are sure I am not imagining things. 

![Enabled Clouds](https://user-images.githubusercontent.com/12175419/86985369-f412d300-c145-11ea-9771-f8877520e939.png)



[20200708T175634.zip](https://github.com/microsoft/azuredatastudio/files/4893912/20200708T175634.zip)


Included the log directory output for the application session.

**Comment by aaomidi** [comment]
Could you please test this scenario on the latest insiders?

**Comment by kburtram** [comment]
Closing based on previous discussion.  Please let us know if the problem persists in current builds.
