### ISSUE TITLE
Empty "Accounts" viewlet showing up in ActionBar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11172]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Tab through Action Bar or click on Action Bar a little below extension manager icon

Expected: No hidden, empty viewlets

Actual: Accounts viewlet button is there with no icon and empty viewlet.  It appears to be a side-effect of this change https://github.com/microsoft/azuredatastudio/commit/d08a224550b4156b23bc4edcecb26cf437f1e64e. 

<img width="357" alt="Screen Shot 2020-07-01 at 2 10 15 PM" src="https://user-images.githubusercontent.com/599935/86292095-f05ed980-bba4-11ea-9a0e-6cc099cb5e87.png">

**Comment by aaomidi** [comment]
Hmm, looks like by default it registers itself there. Will try to find where that's happening.

**Comment by aaomidi** [comment]
Merged to main and release
