### ISSUE TITLE
Checkboxes in ModelView tree components don't display correctly

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11170]
Latest insiders/main

Only the data virtualization extension seems to be using this feature of the ModelView tree.

The checkboxes are all set to the intermediate state by default now and clicking them doesn't do anything. 

![Capture](https://user-images.githubusercontent.com/28519865/86287330-df11cf00-bb9c-11ea-9e9a-fe99e246f0a6.gif)

**Comment by Charles-Gagnon** [comment]
Moving this back into July - this is a complete breaking bug for the Data Virt extension so needs to be fixed. I will investigate and work on a fix.

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by kburtram** [comment]
Port request for this https://github.com/microsoft/azuredatastudio/pull/11256
