### ISSUE TITLE
ADS is wrongly generating bdc.json file when we customize storage settings for BDC

### ISSUE THREAD

**Issue by sujayi** [microsoft/azuredatastudio#11185]
- Azure Data Studio Version: 1.19.0

Steps to Reproduce:

1. Select New Deployment and choose SQL Server Big Data Cluster. You can choose either New AKS Cluster or Existing AKS Cluster. Click on next by filling mandatory fields until you reach below step. 
2. Provide the desired Claim Size for data per pools then click on next. 
![image](https://user-images.githubusercontent.com/42182826/86390450-b1408f00-bc5d-11ea-8aa8-3eb7f125d63e.png)
3. Now at this step you can get config files in 2 ways: 
          1. Click on save config files which will save both bdc.json & control.json files to your machine 
![image](https://user-images.githubusercontent.com/42182826/86391229-0fba3d00-bc5f-11ea-9017-d2b8b3682056.png)
           2. You can click on script to Notebook, then follow the deployment steps by executing the code cells. 
                In this process you will generate deployment configuration files, by default they are saved to 
                 ads-bdc-custom-profile folder (both bdc.json & control.json) 
![image](https://user-images.githubusercontent.com/42182826/86390964-99b5d600-bc5e-11ea-8bdd-f7deb6437048.png)
4. If you look at the bdc.json file, the storage definition for pools written under spec.resources.**master.**storage****
    but the correct spec should follows as: spec.resources.**master.**spec.storage**** but it is generating incorrectly 
    This is same for storage-0 & data-0 pools. Please see below.

Fyi.. BDC deployment works even with wrong storage definition as it ignores and uses controller size for other pools.

**Working-Storage Json File:**
![Working-storage-spec-bdc](https://user-images.githubusercontent.com/42182826/86396100-f3ba9980-bc66-11ea-99c0-fc2fdbf1f3f3.JPG) 
**Non-Working-Storage Json File generated by ADS:**
![Non-working-storage-spec-bdc](https://user-images.githubusercontent.com/42182826/86396106-f6b58a00-bc66-11ea-8a54-61ccf258ca36.JPG)

Also attached both correct and incorrect json(txt) files. 
[incorrect-bdc-by-ADS.txt](https://github.com/microsoft/azuredatastudio/files/4866034/incorrect-bdc-by-ADS.txt)
[correct-bdc.txt](https://github.com/microsoft/azuredatastudio/files/4866042/correct-bdc.txt)

**Comment by alanrenmsft** [comment]
@sujayi Thanks for opening the issue, the fix should be in tomorrow's insider release.

**Comment by sujayi** [comment]
Thanks for your help Alan.


Best,
Sujay
