### ISSUE TITLE
Text on Device Code login page very difficult to read in dark mode

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11181]
![image](https://user-images.githubusercontent.com/28519865/86376118-66158480-bc3b-11ea-94ef-b025c92e02da.png)

**Comment by cheenamalhotra** [comment]
Seems fixed now, below screenshot is from latest ADS v1.39:
![image](https://user-images.githubusercontent.com/13396919/186604373-f088aab1-cbc7-49d9-8c11-dfdef738c99a.png)

I will proceed to close the issue.
