### ISSUE TITLE
Device Code "Copy & Open" button hidden by "Adding account" status message

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11183]
What about just using the status bar instead of the big notification box? And/or having it just automatically prompt the user to copy & open

![image](https://user-images.githubusercontent.com/28519865/86376873-7e39d380-bc3c-11ea-92d7-f769d2f803d9.png)

**Comment by Charles-Gagnon** [comment]
Also - closing this box doesn't appear to do anything. I'm still able to log in just fine after dismissing the pop up.

**Comment by aaomidi** [comment]
Closing the box doesn't really do anything by design. But that UI looks terrible. I'll try to clean it up - although it's less of a priority since this is a non default auth method.
