### ISSUE TITLE
A11y_AzureDataStudioStayHealthy_Notebook_Toolbar_Keyboard: The 3 buttons in the tool bar are not keyboard accessible 

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#11193]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_AzureDataStudioStayHealthy;#A11yTCS;#A11yMAS;#DesktopApp;#MAS2.1.1;#SQL Azure Data Studio;#FTP;#STP;#Keyboard;#Benchmark;#A11ySev1;#Win32;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.20.0-insider (system setup)
Commit: fd29e351990ab1306f674d1fcc9a6820cbbfcc36
Date: 2020-07-02T05:40:02.292Z
VS Code: 1.46.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS References:MAS2.1.1

**Repro Steps:**
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3.  Right-click connection and click New Notebook
4. Click on cell and select code cell.

**Actual:**
When the item code cell is selected the focus moves to the editor and the  toolbar at the top of the editor has no keyboard key tab movement to it . 

**Expected:**
The tab key should move to "Add cell" and the rest 2 buttons beside it and it should be able to move out and in of the tool bar.

**User Impact:**
Keyboard and screen reader users will not be able to access the controls and perform the action associated to it

**Attachment link for Reference:**
[11193A11y_AzureDataStudioStayHealthy_Notebook_Toolbar_KeyboardThe 3 buttons in the tool bar are not keyboard accessible .zip](https://github.com/microsoft/azuredatastudio/files/4868233/11193A11y_AzureDataStudioStayHealthy_Notebook_Toolbar_KeyboardThe.3.buttons.in.the.tool.bar.are.not.keyboard.accessible.zip)

**Comment by VasuBhog** [comment]
@fsteffi there is already a keyboard shortcut **(Outdent)** that allows for the user to tab backwards to the toolbar when the focus is on the code cell editor.

Below is the keyboard shortcut that can be found through Command Palette:

![image](https://user-images.githubusercontent.com/23587151/88106872-cda05f00-cb6b-11ea-9840-3287fbdb5e5c.png)

**Outdent: Shift + Tab**

**Comment by fsteffi** [comment]
Version: 1.43.0-insider (user setup)
Commit: b4d5a08199e9e0cb0138ce540c086ac32d072019
Date: 2023-03-07T06:31:08.002Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.25300

#closed;

[Video 3-07 at 17.19 (3).webm](https://user-images.githubusercontent.com/24580570/223416877-038196d7-4215-48ab-aa06-5b13cca044b2.webm)
