### ISSUE TITLE
Add integration tests for Sql-database-projects' context menu

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#11190]
Add tests to verify the context menu for database projects is generated correctly.
Something similar to objectExplorer tests(https://github.com/microsoft/azuredatastudio/blob/main/extensions/integration-tests/src/test/objectExplorer.test.ts#L47).

**Comment by kburtram** [comment]
Closing older engineering-focused issues.  Please reactive if this is still tracking planned work.
