### ISSUE TITLE
Notebook with power shell script does't load kernel 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#11206]
- Azure Data Studio Version: 1.19.0

Steps to Reproduce:

1. Create a notebook with powershell scripts and saved. 
2. Close ADS
3. Re-open ADS and open the notebook created in step#1

Expected: Powershell Kernel should load successfully 
Actual: Kernel is at" Loading" state for ever and doesn't let me to change it

**Comment by chlafreniere** [comment]
@corivera would be great if you could help @llali with this one 😄

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by chlafreniere** [comment]
Worked with @llali and with the latest RC the issue no longer reproes either for her or for me. Possibly due to our environment variable bug fix when loading powershell kernels.
