### ISSUE TITLE
Extensions in welcome page no icon

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#11205]
Issue Type: <b>Bug</b>

The icons for some of the extensions in the welcome page are blank.

![image](https://user-images.githubusercontent.com/4324725/86622687-2d481900-bf75-11ea-9d52-524db2b8a39e.png)

Azure Data Studio version: azuredatastudio-insiders 1.20.0-insider (2d989e1180f342d684a4e26f76b941843b7fc261, 2020-07-03T05:33:38.245Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (7.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-sqlite|ant|1.0.7
material-icon-theme|PKi|3.9.2
vscode-icons|vsc|9.6.0

</details>

**Comment by Charles-Gagnon** [comment]
Dupe of https://github.com/microsoft/azuredatastudio/issues/10731 - although that was closed for some reason so I'll leave this open. 

Being fixed by https://github.com/microsoft/azuredatastudio/pull/11104

**Comment by anthonydresser** [comment]
This probably has to do with my firewall, since others can't repro.

**Comment by Charles-Gagnon** [comment]
He's changing it so the icons are bundled in with the app anyways so it shouldn't be a problem once that goes in.
