### ISSUE TITLE
Editor's title formatting is inconsistent when tabs are hidden

### ISSUE THREAD

**Issue by dubeg** [microsoft/azuredatastudio#11203]
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Toggle tabs visibility

__Before__
![image](https://user-images.githubusercontent.com/6020602/86514725-a151b800-bde1-11ea-900f-2d684c8d06da.png)

__After__
![image](https://user-images.githubusercontent.com/6020602/86514730-af073d80-bde1-11ea-8e31-4e37009460db.png)

__Note__
I don't know whether the editor's name (e.g. "settings.json") is too small compared to the icon and breadcrumbs, or the other way around. The breadcrumbs' font seems too big because the characters' lower-legs are truncated, and the name seems too small (an illusion when viewed next to the bigger text elements?).

**Comment by kburtram** [comment]
I'm not seeing this behavior on the latest builds.  Please let us know if this is still an issue on your machine?

**Example tab bar**
<img width="787" alt="Screen Shot 2020-08-10 at 11 41 09 AM" src="https://user-images.githubusercontent.com/599935/89818365-7c4a1680-dafe-11ea-86c0-6ff4eac4b32b.png">
