### ISSUE TITLE
Power shell scripts keep running without any result or status

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#11213]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open notebook and change kernel to powershell
2. add the following script:
$msbuild = "C:\WINDOWS\Microsoft.NET\Framework\v3.5\MSBuild.exe"
$arguments = "/v:q /nologo"
start-process $msbuild $arguments 
3. run the cell
Expected: Should either fail or run the process
Actual: cell keeps running without any result

**Comment by chlafreniere** [comment]
This no longer reproes on the RC build, either for @llali or for me.
