### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by combrinckd** [microsoft/azuredatastudio#11225]
Issue Type: <b>Bug</b>

Every time in last 2 weeks I open Azure Data Studio, it says there is an update. Like before I download the update and replace the old files (on linux Mint 19.2)
Reopening Data Studio I would expect it to be updated, yet it is still on version 1.18.1, even though the update downloaded and opened from the extracted folder is 1.19.0 (file downloaded is azuredatastudio-linux-1.19.0.tar.gz)

Azure Data Studio version: azuredatastudio 1.18.1 (5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa, 2020-05-26T21:05:17.848Z)
OS version: Linux x64 5.3.0-62-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 3145)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_off<br>flash_stage3d: unavailable_off<br>flash_stage3d_baseline: unavailable_off<br>gpu_compositing: unavailable_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Load (avg)|3, 2, 2|
|Memory (System)|15.42GB (2.26GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon2d|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon2d|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.5.0
import|Mic|0.15.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@combrinckd I wasn't able to repro this on Ubuntu 20.  The update was pointing me at the 1.19.0 for me.  Do you see similar behavior when downloading the archive from https://go.microsoft.com/fwlink/?linkid=2132349?  Have you verified that the path is correctly setup to load the azuredatastudio binary from the 1.19.0 folder?

**Comment by combrinckd** [comment]
@kburtram thank you for the assist. For some reason update worked when downloading it from the link you provided. I have not downloaded it from there before. Been under bit of pressure couple of weeks so haven't checked it myself, my apologies. Thanks again.
