### ISSUE TITLE
SSMS/ADS Integration for Azure SQL DB and SQL auth broken in v1.19

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11230]
- Azure Data Studio Version:
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Connect to an Azure SQL DB in SSMS with sql authentication
2. At a database or server node in object explorer, select the Azure Data Studio > New Query or New Notebook options
3. Azure Data Studio opens and instead of opening new file, gets stuck at connection screen with error "Windows logins are not supported in this version of SQL Server"

![image](https://user-images.githubusercontent.com/12227241/86827147-40331a00-c057-11ea-84b3-a587711fb72d.png)

**Comment by aasimkhan30** [comment]
@kburtram ssms doesn't pass the authenticationType when starting the ADS instance. ADS by default uses Integrated login if no authentication type is provided. So, there is nothing we can do in ADS to fix the bug. 

We can close this issue or wait for ssms to fix the bug and then close it.
