### ISSUE TITLE
Trouble downloading Python dependencies

### ISSUE THREAD

**Issue by funkjo** [microsoft/azuredatastudio#11247]
- Azure Data Studio Version: 1.18.1

Steps to Reproduce:

1. Open a new notebook for the first time
2. Change kernal to Python 3
3. For Python installation, create a new path - Notebook: Python Path (On windows, it defaulted to C:\Users\user\azuredatastudio-python

After Python download is complete, Python dependencies installation is attempted:   
```> "C:\Users\<user>\azuredatastudio-python\0.0.1\python.exe" -m pip install --user "jupyter>=1.0.0" "pandas>=0.24.2" "sparkmagic>=0.12.9" "prose-codeaccelerator>=1.3.0" "powershell-kernel>=0.1.3" --extra-index-url https://prose-python-packages.azurewebsites.net```   

Installation of every dependency fails wither this error:   
```Could not fetch URL https://prose-python-packages.azurewebsites.net/jupyter/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host=''prose-python-packages.azurewebsites.net', port=443): Max retries exceeded with url: /jupyter/ (Caused by SSLError(SSLError(1,'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:841)'),)) - skipping```

I am trying to get set up in a corporate environment

**Comment by chlafreniere** [comment]
@corivera can you please help here

**Comment by corivera** [comment]
The index at https://prose-python-packages.azurewebsites.net is only needed for the **prose-codeaccelerator** package, which isn't needed for most use cases. In ADS we only use that package for our Analyze in Notebook feature, which is only usable when connecting to Spark clusters. If you're not planning on using Prose, then you can skip installing that package.

In case the other packages weren't installed by that command, you can omit the Prose parts and rerun the following command from a command prompt, updating the username part of the path as appropriate:

"C:\Users\USERNAME\azuredatastudio-python\0.0.1\python.exe" -m pip install --user "jupyter>=1.0.0" "pandas>=0.24.2" "sparkmagic>=0.12.9" "powershell-kernel>=0.1.3"

**Comment by chlafreniere** [comment]
We've removed prose from the default list of packages that we install for the past couple of releases, and no longer ping that particular endpoint for packages. Closing this issue.
