### ISSUE TITLE
New Query Prompts for Text Editor, Opens Generic File Editor

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#11240]
On the RC build, when selecting New Query (either from the File Menu, keyboard shortcut, or welcome page), I'm always prompted to select the text editor with which to open the new file:

![image](https://user-images.githubusercontent.com/40371649/86865652-44c1f780-c084-11ea-9da2-d82864ba2fce.png)

Selecting the editor then opens the generic file editor:

![image](https://user-images.githubusercontent.com/40371649/86865700-5d321200-c084-11ea-81a3-6b8575728f6d.png)

If I change the language of the file back to SQL, everything works as expected:

![image](https://user-images.githubusercontent.com/40371649/86865721-6ae79780-c084-11ea-9185-9911b5fe81df.png)

**Comment by kburtram** [comment]
I've only been able to repro this from the Welcome Page on the latest RC build.

**Comment by chlafreniere** [comment]
Interesting. Was just able to repro via File --> New Query.

(am on Mac).

**Comment by kburtram** [comment]
@chlafreniere thanks, I can repro from the File->New Query menu on mac as well.

@anthonydresser could you please take a look at this?

**Comment by anthonydresser** [comment]
I can only repro from the welcome page and I can see why its reproing from the welcome page.

**Comment by kburtram** [comment]
Approved in shiproom
