### ISSUE TITLE
Search not working on all files, unless open

### ISSUE THREAD

**Issue by Exicle** [microsoft/azuredatastudio#11248]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open folder
2. Open .sql file
3. Choose text to search for from file
4. Close file
5. Search for text

I renamed a table from Load >> LoadHistory, and renamed the identity column from LoadID to LoadHistoryID.  In searching for any instances of the old column name, encountered this error.

I cannot see at all what could be causing this.  The keyword "Load" appears to be a red-herring, as there are plenty of script files that are not appearing, e.g. a search for "tvf" returns only a couple of files when there should be 15+ tvf's.

The folder opened has 117 files in 20 folders.

I got to the bottom of this - naming folders with "..." causes this issue.  Cannot rename in Explorer, only in ADS...

**Comment by kburtram** [comment]
The search functionality is coming from upstream in vscode and hasn't been modified in ads.  I wasn't able to repro this bug on the latest build.  Please let us know if you're still impacted by this bug.
