### ISSUE TITLE
azure account list not getting populated

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#11251]
the subscription list is populated properly but the account list is empty, if i press Refresh, then it will be correctly populated.

<img width="251" alt="Screen Shot 2020-07-08 at 11 32 29 AM" src="https://user-images.githubusercontent.com/13777222/86956994-e55cf980-c10e-11ea-901c-051a6bb25569.png">

**Comment by alanrenmsft** [comment]
@Charles-Gagnon  have you seen this issue before?

**Comment by Charles-Gagnon** [comment]
Nope, gut feeling here is this is a modelview issue. Did you verify that the values are being set and then on the renderer side they're being updated in the correct order?
