### ISSUE TITLE
Resource Groups duplicated in Edge to VM deployment dialog

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#11255]
- Azure Data Studio Version:
Version: 1.20.0-insider (user setup)
Commit: f95cb5f5d38531d4968c2b4c4b6ebcc543d59e4e
Date: 2020-07-08T05:30:20.501Z
VS Code: 1.46.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

In selecting the 2nd subscription under this account in the ADS dialog, I get a doubled up list of resource groups.

![image](https://user-images.githubusercontent.com/12227241/86962937-485b8a00-c129-11ea-899f-aafe392c7f79.png)

![image](https://user-images.githubusercontent.com/12227241/86962949-4d203e00-c129-11ea-9277-538f68ffe3ea.png)

**Comment by alanrenmsft** [comment]
@dzsquared , you are no longer able to reproduce the issue with latest ADS insider build, right?

**Comment by dzsquared** [comment]
Correct - the resource groups do now populate correctly.
