### ISSUE TITLE
Connection dialog "Server group" has incorrect default value

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11258]
- Azure Data Studio Version: `rc1`

Steps to Reproduce:

1. Open Connection Dialog when there is at least 1 saved server group

Expected: Default server group value is `<default>`

Actual: Default server group is not set to `<default>`

![image](https://user-images.githubusercontent.com/599935/86972383-b99a3d80-c127-11ea-9e37-a73b07b001c4.png)

**Comment by aaomidi** [comment]
Can we close this issue now?
