### ISSUE TITLE
No enabled cloud error when using Account Dialog on startup

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11260]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open ADS and open Account Dialog immediately after startup
2. Click Add Account

Expected: Go through process to add account

Actual: Error about no clouds enabled even though public cloud is enabled.  This appears to be a race condition with something loading on startup.  Trying to add an account a little later (~10-15 seconds) works as expected.

![image](https://user-images.githubusercontent.com/599935/86977916-86a97700-c132-11ea-9621-d599137ead5b.png)

**Comment by twright-msft** [comment]
@yualan - heads up on this.  We have a customer that has hit this too.  Can we investigate please?

**Comment by Charles-Gagnon** [comment]
@twright-msft This particular issue that Karl submitted should only happen for the first couple of seconds after starting ADS. From what I gathered in the e-mail thread this customer is hitting this error even long after starting ADS which implies it's a separate issue than this - can you confirm this?

Having them provide a video of this error in action would be helpful here in case there's something else that's getting lost in the back and forth.

**Comment by MsSQLGirl** [comment]
I can repro this in the following ADS versions - 
Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Version: 1.24.0-insider (user setup)
Commit: 89b935e2df7fc34be37ca613002445a2ec263fd8
Date: 2020-10-23T18:07:52.218Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Note: I have ADS running for more than 10 minutes for both versions. Tried a few times and no success. No workaround either.

![NoCloudIssue](https://user-images.githubusercontent.com/6405919/97064838-f9adf080-155d-11eb-826a-86f910abd358.gif)

**Comment by Charles-Gagnon** [comment]
@MsSQLGirl 

1. If you expand the Azure view does that show any nodes or just "Loading..."?
1. If you open the dev console (Help -> Toggle Developer Tools) and go to the console tab are there any errors there? (aside from the one about the Buffer.from being deprecated)

**Comment by jongoneok** [comment]
I am also having this issue (#13220 originally).
console log attached:

[20201104_Azure_Data_Studio_Console.log](https://github.com/microsoft/azuredatastudio/files/5489740/20201104_Azure_Data_Studio_Console.log)

**Comment by Charles-Gagnon** [comment]
For anyone still hitting this issue, to help us track this down could you : 

1. Download the insiders build of ADS (https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)
1. Repro the issue
1. Open command palette (Click View -> Command Palette)
1. Run the command: Developer: Open Logs Folder
1. This will open the log file locally. Attach the renderer.log to this issue or e-mail it to me directly

**Comment by tarry87** [comment]
hy Charles, 

I mailed you the logs  on 17/11 . did you got a chance to look into it?

**Comment by Charles-Gagnon** [comment]
I did but unfortunately the logs didn't contain anything that seemed to be directly related. I haven't had time to look further into this - I'll update when I do.

But in the meantime just to be sure could you do these steps instead : 

1. Close all other instances of ADS
1. Download the insiders build of ADS (https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and launch it
1. Run the `Developer: Set Log Level...` command
1. Select the `Debug` log level from the available levels
1. Run the `Developer: Reload Window` command
1. Repro the issue
1. Open command palette (Click View -> Command Palette)
1. Run the command: Developer: Open Logs Folder and keep the folder open
1. Exit ADS
1. Zip up the entire log folder and send that to me

**Comment by kburtram** [comment]
Moving into March for further investigation based on related reports on issue #13969.

**Comment by jpsebasti** [comment]
I just installed ADS version 1.26.0 on my Mac OS Catalina 10.15.7.  This is a fresh install, I removed the older version.
I click on the person icon (above settings cog).  I have the ability to Add and Account.  I click that and immediately get an error message: You have no clouds enabled.  Go to Settings -> Search Azure Account Configuration -> Enable at least one cloud

I go to Settings and in the search box, I put "Azure Account Configuration".  I immediately get the No Settings Found message.  

I'm not even sure where to find cloud setting to enable.  This flow is really confusing to an end user.

**Comment by kburtram** [comment]
@jpsebasti you shouldn't need to enable an Azure Account Configuration.  This setting is mostly for isolated cloud environments for certain regions/entities.  Could you please check in the Help->Developer Tools console to see if there are any errors there?

@cssuh any ideas how to troubleshot or correct the issue @jpsebasti is encountering?

**Comment by jpsebasti** [comment]
I'll also note that the error on a Mac says:  Go to Settings->Search Azure Account Configuration -> Enable at least one cloud.

On a mac, the flow is actually Azure Data Studio->Preferences->Settings    to get to the Settings menu.  Also, the error that I'm getting as shown above says "Search Azure Account Configuration"  what does that mean?  Does it mean put the words "Search Azure Account Configuration" into the search box?  This seems strange to me.  Of course putting those words into the settings search box returns nothing.  I also tried just putting "Account Configuration" into the search box which also returned nothing.

I happen to be a stickler for words and instructions to users in both error messages presented by software and in documentation.  I've found both quite lacking in virtually all Microsoft products.

Here are flow pictures of what I see:

[Azure_Data_Studio_Error.docx](https://github.com/microsoft/azuredatastudio/files/6102031/Azure_Data_Studio_Error.docx)

**Comment by abhisheksiddhu** [comment]
Getting this on a fresh installation of Azure Data studio and getting no such option for the required setting

![image](https://user-images.githubusercontent.com/17928903/161592031-2861d353-608e-4d16-b0fc-4c2eb3e40caf.png)

No disabled extensions either

![image](https://user-images.githubusercontent.com/17928903/161592140-75d810bb-10be-4788-923e-e01d62b8e902.png)

**Comment by cheenamalhotra** [comment]
@abhisheksiddhu 

Can you please confirm if this directory exists for you?
`C:\Users\<>\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\azurecore`
or, `C:\Users\<>\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore`

As Azure settings are included from this extension and they are expected to be loaded.
Please try and let us know, also if possible using the [latest insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build.
