### ISSUE TITLE
Cannot connect to the SQL Server from Azure Data Studio on Ubuntu os

### ISSUE THREAD

**Issue by alina-mulik** [microsoft/azuredatastudio#11261]
**Precondition:**
VPN connection required.
**Steps:**
1. Open Azure Data Studio
2. Connection type - Microsoft  SQL Server
3. Enter Server name
4. Authentication type - SQL Login
5. Enter Password 
6. Press Connect
**Actual result:** The connection is installing for a long time. As a result - cannot connect to the server. Absolutely the same steps work on Widows.

**Comment by kburtram** [comment]
@alina-mulik was there any error message when trying to connect?  I was able be repro using a basic connection with SqlLogin from Ubuntu 20.

**Comment by alina-mulik** [comment]
Hi, unfortunately, here were no messages, just endless connection process,
i stopped it manually.

Kind regards,
Alina Mulik

пт, 10 июл. 2020 г., 00:35 Karl Burtram <notifications@github.com>:

**Comment by alina-mulik** [comment]
Also, yes, the issue was on Ubuntu 20.

Kind regards,
Alina Mulik

пт, 10 июл. 2020 г., 00:35 Karl Burtram <notifications@github.com>:

**Comment by jostrander** [comment]
I've tried finding logs for this particular error and there doesn't seem to be anything of value.

```
[2020-07-17 13:34:56.178] [renderer1] [info] Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:|server:serverhere|user:userhere|group:C777F06B-202E-4480-B475-FA416154D458
[2020-07-17 13:35:15.967] [renderer1] [error] An unknown error occurred. Please consult the log for more details.
```

Looking in the rest of the logs folder most of the logs are empty or show an initialization message.

**Comment by makingglitches** [comment]
I'm trying now from Fedora 34.

On Fedora 33 was working perfectly, so firstly I suspect that.

Had to manually install openldap-compat layer to get the server to run again.

Now systemctl status mssql-server shows it running.

Installing mssql-tools,  sqlcmd can connect fine with sa account but suddenly Azure Data Studio cannot.

I'm pretty sure sqlcmd uses the odbc driver to connect so there might be the issue.

Please help.

**Comment by bdezonia** [comment]
Just a ping that I am getting this exact problem on CentOS 7 (CentOS Linux release 7.9.2009 (Core)). My systemctl says everything is running fine. There are no errors in the logs. Can connect with sqlcmd and do various operations. Azure Studio just fails to connect while waiting a LONG time.

**Comment by jostrander** [comment]
Manually upgrading to OpenSSL 1.1.1k fixed this issue for me. IIRC it was an issue with auto-upgrade or downgrade of TLS from whatever the default is. 

```
OpenSSL 1.1.1k  25 Mar 2021
built on: Tue May  4 23:46:49 2021 UTC
```

**Comment by makingglitches** [comment]
Mayhaps they add that to the system requirements or to the minimum version required in whatever packages they publish ? Didn't build this from source.

**Comment by bdezonia** [comment]
@makingglitches I was waiting to see if the OpenSSL fix got some upvotes myself before commenting. I also did not compile. My dev system has many other packages that would break if I messed with the installed OpenSSL version.

**Comment by makingglitches** [comment]
openssl seems to be a prob of late

**Comment by makingglitches** [comment]
Of note I didn't realize the initial post said vpn 

I wasn't using a vpn

**Comment by cheenamalhotra** [comment]
Hi Everyone, checking-in if this issue continues to occur. 
Please let us know by upvoting or adding a comment to confirm. I would also request logs/stacktrace if possible with the latest Stable version of Azure Data Studio.

Some tips to help resolve any possible issues:
1. Ensure TLS 1.2 is supported and enabled on target SQL Server as Linux OSes are have been disabling TLS 1.1 and TLS 1.0 by default.
2. Review default cipher suites on Linux and follow [recommended action](https://learn.microsoft.com/en-us/dotnet/core/compatibility/cryptography/5.0/default-cipher-suites-for-tls-on-linux#recommended-action), if not already.
3. If TLS 1.2 cannot be enabled on server side, you can try to set this in OpenSSL as a workaround:
    ```
    MinProtocol = TLSv1
    CipherString = DEFAULT@SECLEVEL=1
    ```

**Comment by cheenamalhotra** [comment]
One more thing I would like to mention for connections taking long time, would be to review DNS settings, and ensure server hostname can be resolved on client environment. Alternatively, IP address can be used to connect to target SQL server is host name continues to be a problem.

**Comment by cheenamalhotra** [comment]
Closing as not enough details to investigate further.
