### ISSUE TITLE
Estimated Query Plan / Explain should have a keybinding

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1127]
- SQL Operations Studio Version: any

Steps to Reproduce:
- We currently have no way to run the "Explain" action in a query editor without clicking the button. There should be keyboard binding for this. We have at least the potential to have one of these for the actual plan running, so this should be easy.

**Comment by chojrak11** [comment]
Possibly it could default to CTRL+L just like in SSMS.

**Comment by alanrenmsft** [comment]
@aasimkhan30 have you already addressed this issue in recent execution plan improvement?

**Comment by lewis-sanchez** [comment]
@alanrenmsft, yes, this has been addressed this issue in the past. `ctrl`/`cmd` + `L` is the shortcut for the "Estimated Plan" button.
