### ISSUE TITLE
Change "Import New Database Project" to a different name

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#11279]
A couple options so far are "Create New Database Project" or "Export into database project"

**Comment by SakshiS-harma** [comment]
To be consistent with SSDT, I would vote for "Create New Database Project".

**Comment by simonsabin** [comment]
I've always hated the menus in SSMS for DAC as they aren't clear on context. 
"Export to Database project" and of "Sync with database project" to keep a database project up to date.
