### ISSUE TITLE
manage packages button is enabled for powershell kernel

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#11286]
for SQL kernel, this button is disabled, but for powershell kernel it is not.

![Screen Shot 2020-07-09 at 7 42 57 PM](https://user-images.githubusercontent.com/13777222/87110863-dc5a4e00-c21c-11ea-9017-0f14ed4e813f.png)

**Comment by chlafreniere** [comment]
It's enabled for every Jupyter kernel, since the package management is for Python packages. This is by design.
