### ISSUE TITLE
'workbench.view.accountpanel' showing up in panel tabs

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11283]
@aaomidi Related to your fix you did earlier for getting this out of the viewlet panel?

![image](https://user-images.githubusercontent.com/28519865/87105109-e2e1c900-c20e-11ea-86ea-957945ac13c7.png)

**Comment by aaomidi** [comment]
Hmm..Not sure what the fix for this would be.
