### ISSUE TITLE
MIAA instances under Azure view have themselves as children

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11297]
They have all their sibling nodes as children, infinitely recursing

![image](https://user-images.githubusercontent.com/28519865/87192746-f8f19700-c2ab-11ea-95b0-f6024eac6546.png)

![image](https://user-images.githubusercontent.com/28519865/87192508-79fc5e80-c2ab-11ea-941d-aec874966540.png)

**Comment by kburtram** [comment]
Approved in shiproom
