### ISSUE TITLE
BDC Deployment wizard locations don't have friendly names

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11292]
These should be displayed as their friendly names in the dialog 

![image](https://user-images.githubusercontent.com/28519865/87176350-d309c980-c28e-11ea-8645-24f3ce9fbc1b.png)

**Comment by alanrenmsft** [comment]
closing since the feature is no longer supported. @Charles-Gagnon , correct me if I am wrong.
