### ISSUE TITLE
Results scrolling is broken

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#11300]
Issue Type: <b>Bug</b>

With enough results grid to start scrolling, the scrolling breaks in the results grid.

![image](https://user-images.githubusercontent.com/4324725/87197332-31df3b00-c2af-11ea-9501-be7c323d2d78.png)

Azure Data Studio version: azuredatastudio Dev 1.20.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (1.11GB free)|
|Process Argv|. --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data --remote-debugging-port=9222|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-sqlite|ant|1.0.7
remote-ssh|azu|0.50.0
material-icon-theme|PKi|3.9.2
vscode-icons|vsc|9.6.0

</details>

**Comment by kburtram** [comment]
Fix merged to release/1.20
