### ISSUE TITLE
No shortcut key to show Notebooks viewlet

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#11301]
Feature request: shortcut key for opening Notebooks viewlet

<img width="1786" alt="ADSNotebooksViewlet" src="https://user-images.githubusercontent.com/23462877/87192847-2dfde980-c2ac-11ea-87a6-1551b7452d28.png">

**Comment by Charles-Gagnon** [comment]
FYI - those parts are called "Views". "Viewlet" is the larger containers in the left sidebar (so there is a Notebook Viewlet that contains 3 views - "Search Results", "Notebooks" and "Provided Books")

**Comment by lucyzhang929** [comment]
There is already a shortcut key for notebooks viewlet (ctrl/cmd + shift + B).
