### ISSUE TITLE
Export Excel file no longer shows "Open File" prompt 

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11316]
- Azure Data Studio Version: `release/1.20`

Steps to Reproduce:

1. Run a query and Export results as Excel

Expected: A prompt to open the file after saving

Actual: No prompt to open the file.  The prompt should look like as below.

![image](https://user-images.githubusercontent.com/599935/87333604-321b4880-c4f2-11ea-8e21-66de8c56d66c.png)

**Comment by anthonydresser** [comment]
This is caused by https://github.com/microsoft/azuredatastudio/commit/381a747b623f877db5f58970e2c72838c54691d1 I think the safest thing to do this late is just revert the commit in the release branch (it was targeted for fixing remote) and I'll work on a better fix in main.

**Comment by anthonydresser** [comment]
I also have #11324 which adds back the open file option, but not the open file location option.
