### ISSUE TITLE
Kqlmagic in notebook - KeyError: 'primaryKey'

### ISSUE THREAD

**Issue by sqlworldwide** [microsoft/azuredatastudio#11313]
- Azure Data Studio Version:
Version: 1.19.0 (user setup)
Commit: 4095037f2578c23033867e611e82c13de114ca5a
Date: 2020-06-11T22:06:05.429Z
VS Code: 1.46.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041
Steps to Reproduce:

1. In Azure Data studio:
%kql loganalytics://workspace='DEMO_WORKSPACE';appkey='DEMO_KEY';alias='myworkspace'

%%kql 
AzureMetrics 
| where * has "CPU"
| take 20

I do get the result set but with this error message:

---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
~\AppData\Roaming\Python\Python36\site-packages\IPython\core\formatters.py in __call__(self, obj)
    343             method = get_real_method(obj, self.print_method)
    344             if method is not None:
--> 345                 return method()
    346             return None
    347         else:

c:\users\taiob\azuredatastudio-python\0.0.1\lib\site-packages\Kqlmagic\results.py in my__repr_data_resource_(self)
    660 
    661             # remove primary key, becuase index is the primary key
--> 662             del schema["primaryKey"]
    663 
    664             # replace pandas version with kqlmagic version

KeyError: 'primaryKey'

**Comment by MsSQLGirl** [comment]
@gupta1  - FYI. 

The same query seems to work on aka.ms/lademo

![image](https://user-images.githubusercontent.com/6405919/87328521-730f5f00-c4ea-11ea-87d8-d19f4adac92c.png)

**Comment by MsSQLGirl** [comment]
@sqlworldwide  - can you please try running this and send it back? (Please rename txt to ipynb since GitHub doesn't support attaching ipynb).

Recommended steps to run: clear all results, and run cell one-by-one. 

[Kqlmagic - LogAnalytics demo.txt](https://github.com/microsoft/azuredatastudio/files/4939437/Kqlmagic.-.LogAnalytics.demo.txt)

**Comment by MsSQLGirl** [comment]
@sqlworldwide - I'm closing this issue since it seems to be working for you now. 
Please feel free to add additional comments on what might have fixed the problem that you first encountered.
