### ISSUE TITLE
rendering issue with linking

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#11318]
- Azure Data Studio Version:
July 2020 Release Candidate
Version: 1.20.0-rc1
Commit: 810cd8c33b3cc95872a1c71a4b097ae0b8df44fd
Date: 2020-07-10T07:58:47.322Z
VS Code: 1.46.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.5.0
Steps to Reproduce:

1. In a new notebook, Zoom in 2-3 times and enter the following code in a text markdown cell.
```
[Microsoft homepage](http://www.microsoft.com)
![Churn-Index](https://www.ngdata.com/wp-content/uploads/2016/05/churn.jpg)
```
You should be zoomed in enough that that 2nd link wraps to a line below and looks as follows.
Actual:
![image](https://user-images.githubusercontent.com/41588310/87336057-2762b280-c4f6-11ea-9b00-3f9da17ea1d2.png)

Expected:
The wrapped down line should not cut-off.

Observation:
This issue does not show up if you have an additional new line below the link as follows:
```
[Microsoft homepage](http://www.microsoft.com)
![Churn-Index](https://www.ngdata.com/wp-content/uploads/2016/05/churn.jpg)

```

**Comment by chlafreniere** [comment]
No longer able to repro this issue. We've made improvements to cell height calculations, so closing this issue.
