### ISSUE TITLE
Datatype dropdown doesn't work in Modify Column Page of Import Wizard

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#11320]
- Azure Data Studio Version:

Steps to Reproduce:

1. Start the import wizard, select a file to import, click next.
2. Click next on preview page
3. On the modify column page try changing the datatype. 
4. The datatype changes are not reflected when the table is created. 

![image](https://user-images.githubusercontent.com/6816294/87341742-f89d0a00-c4fe-11ea-8d19-767089e0d82f.png)

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 This seems like a pretty big issue (that might be affecting other components). Please verify whether it's a regression and try to figure out why this isn't working so we have some context for shiproom.

**Comment by aasimkhan30** [comment]
@Charles-Gagnon I'm adding a temporary fix for this particular issue. I will also keep investigation on what is actually causing this bug.
