### ISSUE TITLE
SQL Tools Service component exited unexpectedly (on startup)

### ISSUE THREAD

**Issue by mpwhitt** [microsoft/azuredatastudio#11338]
- Azure Data Studio Version: 1.20.0-insider

Steps to Reproduce:

1.  Open Azure Data Studio
2.  Observe errors thrown.

Azure Data Studio suddenly started throwing errors late last week.  As a note, I have a separate user account on the same machine running Azure Data Studio with no issues.  This error started on the normal version and continues to appear on the insiders build.  I have updated Node.js but still see the same issue.

![AzureBug](https://user-images.githubusercontent.com/5447314/87419322-436f5e00-c5a1-11ea-9ff9-e0acb48da9b0.PNG)

![AzureDataStudioVersion](https://user-images.githubusercontent.com/5447314/87419453-83cedc00-c5a1-11ea-8f60-04428945f94f.PNG)

**Comment by kburtram** [comment]
@mpwhitt does the `1.19.0` stable build work correctly?  Do you have any extensions installed or anything else that could help narrow down the root cause?

You may try uninstall\reinstall just to make sure nothing got corrupted during installation, or something like that.

**Comment by mpwhitt** [comment]
@kburtram The 1.19.0 build throws the same errors when launching after a fresh install.  I also deleted the azuredatastudio folder under %APPDATA%.  No extensions installed that I'm aware of.

**Comment by mpwhitt** [comment]
Not sure if this is related or not, but I also see this when clicking "Change SQL language provider"...

![getControlError](https://user-images.githubusercontent.com/5447314/87541895-0de57600-c670-11ea-84ec-5e8a889ddbee.PNG)

**Comment by kburtram** [comment]
@mpwhitt you can try turning on Verbose logging and checking the SQL Tools Service log.  This log may contain PII so shouldn't be posted here, but you may be able to get additional details on what's causing the crash.

![image](https://user-images.githubusercontent.com/599935/92533610-b08d2180-f1e7-11ea-9c0a-43cb19cefedb.png)

The log location is visible in the command-line arguments to SQL Tools Service, which can be viewed from the "Help->Open Process Explorer" menu.

![image](https://user-images.githubusercontent.com/599935/92533780-04980600-f1e8-11ea-91cc-4ab75fb9f598.png)

**Comment by mpwhitt** [comment]
@kburtram - I turned on verbose logging, restarted a couple of times, but the process explorer doesn't show the file location as referenced in your screenshot.  I also checked the corresponding Microsoft.mssql folder on my machine, but it's empty.
![sql_tools](https://user-images.githubusercontent.com/5447314/93871069-12479400-fc9c-11ea-8de4-71573ebcb614.PNG)
