### ISSUE TITLE
Azure account handling

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/azuredatastudio#11353]
Issue Type: <b>Bug</b>

I can only log in to one of my Azure tenants at a time.  I know that my situation is odd.  We have two tenants, one was setup with personal accounts and another using AD.   The user names are the same.  I'm unable to log into both of these tenants at the same time.  Take a look at Azure Storage Explorer, it's capable of handling this.

Azure Data Studio version: azuredatastudio 1.20.0 (cfbadd1eaef2dfa1fd643009c572137c704f1009, 2020-07-14T23:40:35.393Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
@aaomidi do you happen to know if this is a change in `1.20.0`?  Or if we expect this scenario to be supported currently?

**Comment by aaomidi** [comment]
Can you explain more on how the application doesn't handle multiple azure accounts? If you sign in with two accounts what happens?

**Comment by aaomidi** [comment]
@kburtram This isn't anything we should've caused with 1.20.0

**Comment by dsmeltz** [comment]
Let me see if I can clarify my issue.

I have 2 Azure accounts, one is a personal account and one is a work/business account.  Both accounts use the same email address. (I know this is odd, but the company had an Azure tenant before we adopted Dynamics 365.  With the move to Dynamics, we now have another, Active Directory controlled, tenant.)

When I log in to Azure, I have to say which account I want to log in to: personal or work/business.  

With Data Studio, I can only add one of these account at a given time.  When I try to add the other account, it just replaces the previously setup account.  It does change the account though, I just don't have access to both of them at the same time.

This is the first I'm trying this feature.  So I highly doubt it's a bug in the latest release.  It's just an odd thing that I'm unable to add both of my Azure accounts.

I'm not sure what Storage Explorer is doing differently but it handles my situation fine:
![image](https://user-images.githubusercontent.com/1830600/87588865-5f165980-c6b2-11ea-97f5-637f0ebc79be.png)

**Comment by aaomidi** [comment]
Ah yeah, this is definitely an issue since I think we've historically used the account email as the "unique key" for storage.

Thanks I'll  see if I can get around this and use proper UUIDs we get from oauth.
