### ISSUE TITLE
Unable to add account

### ISSUE THREAD

**Issue by PMLIO** [microsoft/azuredatastudio#11375]
Issue Type: <b>Bug</b>

Unable to add account. Opens browser and then times out

Azure Data Studio version: azuredatastudio 1.20.0 (cfbadd1eaef2dfa1fd643009c572137c704f1009, 2020-07-14T23:40:35.393Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1225 v3 @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@aaomidi any suggestions on how to troubleshoot this issue?

**Comment by aaomidi** [comment]
I just changed a lot of the code in this area yesterday. Does this issue still happen?

Please make sure that that localhost website its trying to load isn't forcing to be https, that won't work. If it does you have HSTS enabled for localhost. If you tell me which browser you're using I can help you disable HSTS for localhost.
