### ISSUE TITLE
drag and drop of columns and tables: multiple selections should be possible

### ISSUE THREAD

**Issue by kaysauter** [microsoft/azuredatastudio#11374]
**Is your feature request related to a problem? Please describe.**
With release Version 1.20.0 you've released the new feature of drag & drop from Tables or Columns into the editor for writing queries. A single table / column doesn't really solve a pain though; The real pain is when you've got to write (or drag & drop) every single table / column. For tables, it might be a bit less obvious but I can imagine the situation that you want to be able to put all tables you need beforehand so you can use them in getting things done style. For columns, its is fairly common that you want to specify many or all columns without using  the wildcard * as in `Select * from Table` 

**Describe the solution or feature you'd like**
I want to be able to select multiple or all columns that I can drag & drop into the editor like I can in SSMS. If possible, there could also be a multi selection (which is not possible in SSMS either) of columns you want to use. Make sure that a comma is given into it. For Tables, just allow to pick tables and put into query window. 
To put the cherry on top of the cake: let the user give the option to pick either: columns are placed horizontally like 
`Column1, Column2, ..., Column N` or vertically like 

```
Column1
, Column2
, ...
, Column N
```
and let decide if the comma is trailing or before column (as above)

**Describe alternatives you've considered**
Alternative is to do this manually which may be a pain.

**Additional context**

**Comment by kaysauter** [comment]
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [dragging and drop table and columns into the query editor (#8335)](https://www.github.com/microsoft/azuredatastudio/issues/8335)

I was asked to open this issue. Source: https://www.linkedin.com/feed/update/urn:li:activity:6689263020633276416?commentUrn=urn%3Ali%3Acomment%3A%28activity%3A6689263020633276416%2C6689298645348700160%29

**Comment by kburtram** [comment]
@ChrisSun-ms can you see if this would be a relatively straightforward enhancement to the OE DnD feature?
