### ISSUE TITLE
Change Schema Compare to different name

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azuredatastudio#11391]
**Schema compare as a menu items doesn't give context**
As a name what does the schema compare do. It allows comparison to a project, another database, so why not have those as options.

**Provide clear actions**
Beyond Compare has a nice feature, that I right click on a folder/file and select "Select left file/folder to compare". Have the menu "Select source database to compare" and then when I right click on another project I can click "select compare to <db name>" 

Or following the VS Code model, where I can select two items and select compare selected.

This way I get the power of all the built in UI and connections, and the schema compare immediately fires with the relevant source and target comparisons. I don't have a stark Schema Compare dialogue, where I then have to select the target by using the select target drop downs. 

It also facilitates automatically applying filters on the source and target. If I select the tables  node on two databases, the schema compare can then compare the tables. 

This would obviously require multi select to be possible in the server explorer

**Comment by simonsabin** [comment]
Any discussion on this?

**Comment by kisantia** [comment]
closing as there are no plans to change the name of schema compare
