### ISSUE TITLE
Column width of Search panel is too short

### ISSUE THREAD

**Issue by rramname** [microsoft/azuredatastudio#11404]
Issue Type : Bug

Hi Team,

Thanks for the great product.

The column width (which seems to be 18-20 chars Max) in the search panel (Right click database -> Manage -> Enter Search team) is too small. Objects with larger names are not visible which is making it difficult to correctly identify object. 

Could it be made a little bigger?

Here is the screen shot of default master database.

![image](https://user-images.githubusercontent.com/34177573/87806423-da981800-c824-11ea-95a3-bc8fca4bd1ff.png)

Version Info:

![image](https://user-images.githubusercontent.com/34177573/87806478-f4395f80-c824-11ea-8684-b052b0ddbb08.png)

**Comment by alanrenmsft** [comment]
@rramname please see my comments here: https://github.com/microsoft/azuredatastudio/issues/10611#issuecomment-635745613

please reopen the issue if it doesn't help.

**Comment by rramname** [comment]
Thank you @alanrenmsft . That did the trick.
