### ISSUE TITLE
Focus not in editor after dropping table from OE into editor

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11403]
- Azure Data Studio Version: `1.21.1`

Steps to Reproduce:

1. Drag and drop a table from OE into the editor

Expected: Focus is in the editor after the drop operation is complete.  This allows typing operations to go to the editor after the drop is complete, which is a natural workflow when using this feature.

Actual: Focus is in Object Explorer.

**Comment by kburtram** [comment]
@cssuh could you please take a look at this for August?  I think this minor enhancement will smooth out the most common use-case a bit.

**Comment by cssuh** [comment]
ok sure I think it would be a good improvement to the user experience
