### ISSUE TITLE
WHERE keyword not implemented properly

### ISSUE THREAD

**Issue by RedRevYol** [microsoft/azuredatastudio#11420]
- Azure Data Studio Version:

Steps to Reproduce:

Getting an error saying "Invalid column name 'name'". 
I wrote:
SELECT * FROM table
WHERE column="name";

I'm getting red squigglies on "name" showing the error message

**Comment by Charles-Gagnon** [comment]
What you pasted isn't a valid statement to begin with - for example " aren't valid string delimiters in T-SQL.

Could you provide more information such as the table schema you're trying to select from and paste the exact query that's giving you the error?

**Comment by RedRevYol** [comment]
Nevermind, put this issue as resolved. Sorry for the convenience

**Comment by kburtram** [comment]
@RedRevYol thanks for confirming.
