### ISSUE TITLE
Azure Accounts clicking "Add Account" does nothing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11425]
Insiders 

1. Open Azure Accounts pane
1. Click "Add Account" button
1. "Adding Account..." message appears but nothing else happens

No errors in console.

**Comment by aaomidi** [comment]
I'm unable to repro this.

**Comment by Charles-Gagnon** [comment]
I don't really have any other information to provide so I'll close this for now and if I keep seeing it we can investigate further.
