### ISSUE TITLE
Large Notebook appears to cause a crash

### ISSUE THREAD

**Issue by paulgbrown** [microsoft/azuredatastudio#11436]
- Azure Data Studio Version:

Steps to Reproduce:

1. Create a large Jupyter Notebook. File causing problem specifically contain 265,615 rows with 31 cells. 16 Text and 15 Code. It also contained the results of numerous queries in the code.

2. Save the file and close ADS.

3. Restart ADS and open the file. ADS should appear to hang and eventually this message appears: 
![image](https://user-images.githubusercontent.com/3458046/87989592-eba48b80-caa7-11ea-8f54-2a812f9c1513.png)

Note: Later in the day, while attempting to recreate for this issue, I repeated the above steps and several seconds after the message appeared, the file opened. I was then able to edit the file as normal. Not sure what changed between initial problem and recreation other than I closed several tabs in Chrome.

Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
Thanks, we've looked into this and this is related to how we render tables. Work is ongoing here.

**Comment by paulgbrown** [comment]
Thanks, Chris!

**Comment by chlafreniere** [comment]
We're still working on this. We're improving table rendering this month, and we'll see if it fixes this particular issue. Moving this out since we're close to code complete.

**Comment by corivera** [comment]
Fixed with Incremental Grid Rendering setting.
