### ISSUE TITLE
Cannot read property of undefined

### ISSUE THREAD

**Issue by sandermvanvliet** [microsoft/azuredatastudio#11447]
Issue Type: <b>Bug</b>

With the latest update I get the error while browsing servers in the connections pane:

```
Cannot read property '6b7a3f49-a6cf-4daa-acc9-c7d2064c88a0' of undefined
```

**Steps to reproduce:**
- Open Azure Data Studio

The error message appears immediately and it is not possible to expand an existing connection to view the databases or to create a new connection.

Azure Data Studio version: azuredatastudio-insiders 1.21.0-insider (6f9991e22ba4aa5e7a33e13da8bf4f22d50b974a, 2020-07-20T06:10:07.442Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (15.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment]
This one should be fixed in the new insiders. Can you test again?

**Comment by sandermvanvliet** [comment]
Just updated to:

```
Version: 1.21.0-insider (user setup)
Commit: eccf3cf5fe8f60d04d70096bc94c654cab60d81a
Date: 2020-07-24T09:33:09.435Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
```

and can confirm that the error message is gone now and I can connect and browse Azure SQL Servers again.

One thing I noticed is that my configured accounts are no longer there and I had to add them back again. Not a big deal, glad everything works again 👍
