### ISSUE TITLE
Books viewlet tree has Azure account actions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11451]
1. Expand an Azure subscription node (this seems to be a required step - if you don't do this the actions don't appear)
1. Open books viewlet
1. Open book/notebook (in either view)
1. Right click on items in the tree

Actions for Azure Accounts are showing up
![image](https://user-images.githubusercontent.com/28519865/88081464-40daae80-cb35-11ea-960c-783dc9e9578d.png)

**Comment by Charles-Gagnon** [comment]
@aaomidi @MaddyDev Assigning this to both of you - not sure whether this is an Azure view issue or Notebooks view issue.

**Comment by MaddyDev** [comment]
Don't see these actions anymore, @Charles-Gagnon can you also confirm so I can close this.

**Comment by Charles-Gagnon** [comment]
Confirmed I'm not seeing this behavior anymore.
