### ISSUE TITLE
A connection was successfully established with the server, but then an error occurred during the pre-login handshake.

### ISSUE THREAD

**Issue by erddys** [microsoft/azuredatastudio#11456]
- Azure Data Studio Version: 1.20.1
Hello, 
After an update to the latest version I started getting this error when trying to conect to a database **A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)**

Asking some friends, they were having the same issue, except one of them who had installed the version 17.1.1. When I downgrade to that version, no more error.

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/azuredatastudio/issues/11367#issuecomment-659614111

Does this solve your issue?

**Comment by erddys** [comment]
Yes, the downgrade to the version 17.1.1 solve the issue

**Comment by erddys** [comment]
Yes, #11367  solve the issue. Thanks

**Comment by pendletonrichard** [comment]
This was not actually a bug (For ME)  
I changed (Advanced Settings) {Trust Server Certificate} to {True} and the connection Succeeded.
