### ISSUE TITLE
Tab to autocomplete field names chooses the last option instead of first

### ISSUE THREAD

**Issue by pcj-jenzabar** [microsoft/azuredatastudio#11452]
Issue Type: <b>Bug</b>

I have two fields in my table JOB_NAME, and JOB_TIME. When I type 'job' and press TAB it autocompletes with JOB_TIME instead of JOB_NAME. It should select the first entry by default instead of the last.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz (2 x 2300)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (3.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Could you attach a video of this happening? It seems to work fine for me. Is the highlighted item in the list on JOB_NAME or on JOB_TIME when you start typing JOB?

![Capture](https://user-images.githubusercontent.com/28519865/88201046-d2145880-cbfb-11ea-9aea-45ad70983f7e.gif)

**Comment by pcj-jenzabar** [comment]
Here you go.

![2020-07-27-16-43-57](https://user-images.githubusercontent.com/67909738/88595533-c0cab200-d028-11ea-8670-a3300e631d54.gif)

**Comment by pcj-jenzabar** [comment]
I should mention this is in an INSERT INTO statement, not a select, that is a difference I noted here. Though I also see JOB_TIME coming up first in a SELECT (I just don't often query based on that column myself)

**Comment by Charles-Gagnon** [comment]
Do you have the `Editor: Suggest Selection` setting set to recentlyUsed? 

![image](https://user-images.githubusercontent.com/28519865/89057107-f1a13480-d311-11ea-8fba-f75166f0cad3.png)
