### ISSUE TITLE
Missing "Install tools" button

### ISSUE THREAD

**Issue by vin-yu** [microsoft/azuredatastudio#11461]
- Azure Data Studio Version:

Version: 1.21.0-insider (user setup)
Commit: 92c8d890c453dae24d8dc63fe47df27e2ce6b8f4
Date: 2020-07-21T06:04:40.423Z
VS Code: 1.48.0
Electron: 8.3.3
Chrome: 80.0.3987.165
Node.js: 12.13.0
V8: 8.0.426.27-electron.0
OS: Windows_NT x64 10.0.19569

Scenario:
Trying to deploy Managed Instance - Azure Arc

Steps to Reproduce:
1. Open Azure Data Studio and install Arc plugin. 
2. Click on "New Deployment"
3. Get prompted to install kubectl (see screenshot) 
![MicrosoftTeams-image](https://user-images.githubusercontent.com/7897410/88101447-d9335c00-cb52-11ea-8e44-7e0a52904eb3.png)

4. Click 'Install Tools' and you'll see that kubectl is being installed.
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7897410/88101481-e5b7b480-cb52-11ea-8a32-9be2d4163a69.png)

5. 'azdata' was not installed and now there is no 'Install tools' button to install
![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/7897410/88101506-efd9b300-cb52-11ea-959f-afbf0a89ec79.png)
Expected Behavior: 
Can install azdata and kubectl to proceed with Managed Instance Azure Arc Deployment

**Comment by chlafreniere** [comment]
@Charles-Gagnon can you assist Vin here? 

@vin-yu please follow the bug bash instructions for installing azdata; there is no integrated install yet through the deployment experience for Arc resources

**Comment by Charles-Gagnon** [comment]
@vin-yu If you close and re-open the dialog does the "Install tools" button appear?

But what Chris said is true - while we do support auto-install for azdata it will download the publicly released version of azdata and so will not have the Arc commands. You need to pre-install the correct version of azdata per the bug bash docs.

**Comment by Charles-Gagnon** [comment]
It works fine for me - it looks like this is on Windows, right? We install them one at a time - did you maybe close the UAC prompt or something? I can't see anything immediately obvious as to what went wrong - we seem to be handling the error cases fine.

If this still shows even after closing and re-opening the dialog or we can get a consistent repro then I can investigate further - doesn't seem like a thing I'd expect to happen often though as it is.
