### ISSUE TITLE
Jupyter Book: Collapse multiple books in the workspace setting

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11482]
**Is your feature request related to a problem? Please describe.**
My workspace has more than 7 books with multiple chapters. When the workspace is opened, the books are all expanded to the first level chapters.

**Describe the solution or feature you'd like**
When opening a workspace with multiple books, it should be possible to configure the workspace to open the books collapsed by default.

**Describe alternatives you've considered**
Manually collapsing book one by one.

**Additional context**
Livesite

**Comment by chlafreniere** [comment]
Ack. Until we have this implemented, it's good to direct folks to the collapse action in the viewlet:

![image](https://user-images.githubusercontent.com/40371649/88322612-d4e37c00-ccd5-11ea-8193-725325ee22e2.png)
