### ISSUE TITLE
unable to login sqlserver db

### ISSUE THREAD

**Issue by RandallDW** [microsoft/azuredatastudio#11480]
Issue Type: <b>Bug</b>

I was able to connect my db before, but several days ago, it suddenly not work. 
Got connection error as 
```
A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 35 - An internal exception was caught)
```
I tried to connect with sqlcmd, everything works fine but not with azure data studio.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:32:14.131Z)
OS version: MacOS Catalina

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Tarig0** [comment]
This is also happening on windows, seems to be introduced in the last update.

Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Tarig0** [comment]
Just found out if I use the server name instead of an alias the connection would work

**Comment by Charles-Gagnon** [comment]
I'll close this since your problem was resolved - but what alias are you referring to? And you said sqlcmd worked - was that with the alias too?

**Comment by Tarig0** [comment]
Alias in the domain joined name of the box is x and we can connect using a different alias y. This is a work around and not a solution since this worked before.

**Comment by RandallDW** [comment]
Login without alias doesn't work for me neither.
