### ISSUE TITLE
Azure fields in Deployment dialog will fail if account is stale

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11499]
If the account chosen is stale (needs to be re-authenticated) then the queries to get the subscriptions/RGs will fail without any indication what the issue is. 

This happens at https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/src/ui/modelViewUtils.ts#L906 and https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/src/ui/modelViewUtils.ts#L981.

We should be checking if isStale is true and if it is then refreshing the account before attempting to fetch the resources.

**Comment by Charles-Gagnon** [comment]
@ranasaria I'm assigning this to you for now - if you're finished with the test stuff this would be a good thing to look at.

**Comment by ranasaria** [comment]
Ok will do. I still have next week on test stuff but I will start stealing some cycles for this next week.
