### ISSUE TITLE
Opening folder in workspace containing Books causes error shown in Notebooks Viewlet

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11490]
1. Open folder (not a Jupyter Book - just a regular folder) that contains Books
1. Browse to Notebooks Viewlet

(I haven't tested this fully so maybe it's something else causing this - the repo I tried this with is the SqlNewHireOnboarding and this just happened when I opened the root folder in ADS from File -> Open Folder)

This error appears :

![image](https://user-images.githubusercontent.com/28519865/88313182-ffc6d380-ccc7-11ea-87c6-bb65a14ccc9e.png)

Not sure the case when we'd display this error - but if we're going to display it we should try to give some more information. Where is it looking for this TOC for example.

**Comment by chlafreniere** [comment]
@MaddyDev may be related to the other issues you've been looking into.

**Comment by MaddyDev** [comment]
Looking into it.

**Comment by MaddyDev** [comment]
This is a valid error, there is actually a file 'Table of Contents' missing from one of the books opened. So closing this issue, I'll look into enhancing the error shown to include the bookName/path from where the file is missing.
