### ISSUE TITLE
Update error message when project with same name already exists

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#11504]
Steps to reproduce:
1. Import a project from a database with the default name
2. Try to import the same database project again to the same location

Expected:
Project should be successfully created, possibly with an incremented counter appended to the folder name, or an error message that says that a project with the same name exists at that location

Actual:
This error message didn't get updated after the change was made to create a new folder when creating a project from a db. The existing .sqlproj is actually at /Users/kisantia/SqlProjects/DatabaseProjectskeep_AdventureWorks2017/
![image](https://user-images.githubusercontent.com/31145923/88351360-ded3a200-cd0a-11ea-9cf8-94e481611f06.png)

**Comment by udeeshagautam** [comment]
@kisantia should we have an item for auto increment separartely (thats not included in the PR right?)? @anjalia might have some cycles to help with that one.

**Comment by kisantia** [comment]
@udeeshagautam opened up #11601 to track this. It would be great is @anjalia has time to get this added :)
