### ISSUE TITLE
Resource Deployment does not discover installed azdat

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#11506]
- Azure Data Studio Version:
Insiders build as of 23 July 2020.

OS: MacOs Catalina with all the latest updates.

Steps to Reproduce:

1.click on + next to arc deployments 
2. A wizard opens with arc card sele Ted that reports missing azdata tool. This happens even when azdata of right version was already installed. And when azdata is just installed by ads itself. 

Impact: can't install arc instance or miaa.

**Comment by Charles-Gagnon** [comment]
This has been working fine for me - do you have any other information? Did you restart ADS after the installation? What platform are you on?

**Comment by ranasaria** [comment]
This is the error that I get:
❯ azdata -v
dyld: Library not loaded: @executable_path/../.Python
  Referenced from: /usr/local/Cellar/azdata-cli/20.0.0/libexec/bin/python
  Reason: image not found
/usr/local/bin/azdata: line 2: 35930 Abort trap: 6           /usr/local/Cellar/azdata-cli/20.0.0/libexec/bin/python -m azdata.cli "$@"

**Comment by ranasaria** [comment]
So this was not a doc bug after all and reproduced with the latest ignite build of azdata.

**Comment by Charles-Gagnon** [comment]
@ranasaria We can close this out then since it's confirmed to be an azdata issue?

**Comment by ranasaria** [comment]
I am waiting for a platform workitem for this. Will close this after linking to that.

**Comment by ranasaria** [comment]
Tracking this using the following platform bug:
https://sqlhelsinki.visualstudio.com/DefaultCollection/aris/_workitems/edit/15979/?triage=true

so closing it here.
