### ISSUE TITLE
Import Wizard extension not working

### ISSUE THREAD

**Issue by jotigautam** [microsoft/azuredatastudio#11527]
- Azure Data Studio Version:

Steps to Reproduce:

1.  Import Wizard is not showing up on pressing ctrl+I or by clicking on 'Import wizard' on particular database.

**Comment by jotigautam** [comment]
Azure data Studio 1.20.1

**Comment by NeilGoodUKABC** [comment]
Issue for us - Unable to Import simple Text/CSV file
Steps taken:

- Open SQL Flat File Import Wizard
- Select Database and file to Import
- Agree with Columns and Style of data
- Click Import
- Get long error message (which I cannot copy over to here).
-
![image](https://user-images.githubusercontent.com/68856622/88551430-c3bea600-d01a-11ea-9b7d-08d6c2d9d5d7.png)


Thanks, Neil Good.

System Info 
CPUs	Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (8 x 2394)
GPU Status	2d_canvas: unavailable_software
flash_3d: disabled_software
flash_stage3d: disabled_software
flash_stage3d_baseline: disabled_software
gpu_compositing: disabled_software
multiple_raster_threads: enabled_on
oop_rasterization: disabled_off
protected_video_decode: disabled_off
rasterization: disabled_software
skia_renderer: disabled_off_ok
video_decode: disabled_software
viz_display_compositor: enabled_on
viz_hit_test_surface_layer: disabled_off_ok
webgl: unavailable_software
webgl2: unavailable_software
Load (avg)	undefined
Memory (System)	56.00GB (41.76GB free)
Process Argv	
Screen Reader	no
VM	0%

**Comment by aaomidi** [comment]
@NeilGoodUKABC @jotigautam What type of SQL Server are you using? What type of authentication are you using to authenticate to the SQL Server (SQL Login, AAD, etc)

Thanks!
