### ISSUE TITLE
Need to be able to display a name/alias to an Arc data controller in ADS

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#11522]
- Azure Data Studio Version:
Version: 1.21.0-insider (user setup)
Commit: b098ce64b5f79b6db2d39f637cea73a2fa9f4550
Date: 2020-07-17T05:40:08.933Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
Right now a controller appears under its IP address and port. With several controllers registered in their ADS, it is not easy to remember for which one is which. Instead, having a friendly name/nickname would help.

![image](https://user-images.githubusercontent.com/22226386/88449503-41589b00-cdfc-11ea-8bb5-6d5a619c1093.png)

**Comment by twright-msft** [comment]
A data controller has a name property.  Ideally we retrieve that and use it.  Alternatively, we could allow the user to specify a user-chosen friendly name similar to the Servers viewlet in the Connections panel.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon do we have an area for Arc?
