### ISSUE TITLE
my personal Azure account displayed twice

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#11537]
Steps to Reproduce:

1. add my personal Azure account
2. restart ADS
3. open Azure account dialog

I am getting the following view, there are 2 entries for my personal account.

![image](https://user-images.githubusercontent.com/13777222/88595221-6d9c3380-d017-11ea-8641-a88e2424418f.png)

also, for my personal account, instead of showing my name, the email address is displayed twice.

**Comment by aaomidi** [comment]
Just had this happen to me too. I've root caused it too. Thanks for filing this bug.
