### ISSUE TITLE
The title of the dashboard pane should contain the name of the instance it is about

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#11532]
- Azure Data Studio Version:

Steps to Reproduce:

The title of the dashboard panes should contain the name of the instance (Postgres for instance) it is about. Right now it does not and it is confusing.

In this example, I have 8 instances deployed. I have opened dashboards for several of them but I can't distinguish them unless I look at the pane itself:
![image](https://user-images.githubusercontent.com/22226386/88570947-c5c03f00-cff1-11ea-946b-19f0b2c98bc6.png)

**Comment by alanrenmsft** [comment]
@Charles-Gagnon could you please put this in a proper milestone?
