### ISSUE TITLE
A11y_AzureDataStudio_Welcome_Resources_ScreenReader : Hidden content as radio button is announced while navigating to the "History" tab control.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/azuredatastudio#11546]
**"[Check out Accessibility Insights! ](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-manai%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847260936&sdata=T26HQfSGOlnuRQdX%2ByXk%2B2bxqgwFvCIVfuboZUWidYY%3D&reserved=0)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”**
GitHubTags:#A11y_AzureDataStudioJuly2020;#A11y_July27_2020_TestPass;#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#MAC;#Screenreader;#VoiceOver;#A11ySev2;#Benchmark;#MAS1.3.1#FTP;

### Environment Details:
Application Name: Azure Data Studio
Application Version: 1.21.0-insider
Commit: eccf3cf
Date: 2020-07-24T09:28:31.172Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Operating system: macOS Catalina (Version 10.15.6 (19G73)
Screen Reader: VoiceOver
MAS References: MAS1.3.1

### Repro Steps:
1. Launch Azure Data Studio Insiders application.
2. If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3. Navigate till Resources section on Welcome screen.
4. Start screen reader, observe if some hidden radio button is announced while navigating to "History" tab control.

### Actual:
When screen reader users navigate to the "Resources" section, an hidden content as radio button is announced while navigating to the "History" tab.

### Expected:
The hidden content should not be announced to the screen reader users while navigating to the "History" tab.

### User Impact:
If some unnecessary content is announced to the screen reader users while navigating through the screen content then users will miss understand the content on the screen and then this will lead to confusion.

### Attachment link for Reference:
[11546_A11y_AzureDataStudio_Welcome_Resources_ScreenReader Hidden content as radio button is announced while navigating to the "History" tab control.zip](https://github.com/microsoft/azuredatastudio/files/4985710/11546_A11y_AzureDataStudio_Welcome_Resources_ScreenReader.Hidden.content.as.radio.button.is.announced.while.navigating.to.the.History.tab.control.zip)

**Comment by Harika1702** [comment]
https://user-images.githubusercontent.com/100270074/218694926-a1d66e92-1c63-406c-9840-bdec119efc37.mov
Verified the issue Now it is fixed.

Git Hub Tags- #Closed;
