### ISSUE TITLE
A11y_AzureDataStudio_Welcome_AzureDataStudio-Insiders_ScreenReader : The screen reader focus does not remain within the "Preview" dialog while navigation.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/azuredatastudio#11541]
**"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-manai%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847260936&sdata=T26HQfSGOlnuRQdX%2ByXk%2B2bxqgwFvCIVfuboZUWidYY%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”**
GitHubTags:#A11y_AzureDataStudioJuly2020;#A11y_July27_2020_TestPass;#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#MAC;#Screenreader;#VoiceOver;#A11ySev1;#Benchmark;#MAS1.3.1;#MAS1.3.2;#FTP;

### Environment Details:
Application Name: Azure Data Studio
Application Version: 1.21.0-insider
Commit: eccf3cf
Date: 2020-07-24T09:28:31.172Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Operating system: macOS Catalina (Version 10.15.6 (19G73)
Screen Reader: VoiceOver
MAS References: MAS1.3.1, MAS1.3.2

### Repro Steps:

1. Launch Azure Data Studio Insiders application.
2. If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3. Start screen reader, navigate to "Preview" control and activate it.
4. A dialog appears on the screen, try to navigate within the dialog and observe if the screen reader focus remains within the dialog or not.

### Actual:
When the dialog appears on the screen after activating the "Preview" control and the screen reader users start navigating through the dialog content, the screen reader focus does not remain within the dialog itself the user are able to reader the content present out side the dialog without even closing it which is incorrect.

### Expected:
The screen reader focus should remain within the dialog when they are navigating through the dialog content and the background content should not be announced to the users until the dialog is closed.

### User Impact:
If the screen reader users are able to access the content present in the background of the dialog without closing it than the users will have difficulty in understanding the start and end of the dialog.

### Attachment link for Reference:
[11541_A11y_AzureDataStudio_Welcome_AzureDataStudio-Insiders_ScreenReader The screen reader focus does not remain within the "Preview" dialog while navigation.zip](https://github.com/microsoft/azuredatastudio/files/4985292/11541_A11y_AzureDataStudio_Welcome_AzureDataStudio-Insiders_ScreenReader.The.screen.reader.focus.does.not.remain.within.the.Preview.dialog.while.navigation.zip)

**Comment by alanrenmsft** [comment]
I have simplified the preview information to use tooltip to show the text provided by the old dialog.

**Comment by Ashutoshsahoo164** [comment]
Closing this bug , as the scenario itself is not present in UI.
GitHubTags:#Closed;
