### ISSUE TITLE
A11y_AzureDataStudio_Welcome_ExtendyourdataStudio_ScreenReader : The decorative image present besides the links such as "SQL Server Agent", "SQL Server Profiler", etc. is announced for screen reader users.

### ISSUE THREAD

**Issue by MayuriNaik** [microsoft/azuredatastudio#11548]
**"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-manai%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847260936&sdata=T26HQfSGOlnuRQdX%2ByXk%2B2bxqgwFvCIVfuboZUWidYY%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”**
GitHubTags:#A11y_AzureDataStudioJuly2020;#A11y_July27_2020_TestPass;#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#Benchmark;#MAC;#Screenreader;#VoiceOver;#A11ySev2;#Benchmark;#MAS1.3.1;#MAS1.1.1;#FTP;

### Environment Details:
Application Name: Azure Data Studio
Application Version: 1.21.0-insider
Commit: eccf3cf
Date: 2020-07-24T09:28:31.172Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Operating system: macOS Catalina (Version 10.15.6 (19G73)
Screen Reader: VoiceOver
MAS References: MAS1.3.1, MAS1.1.1

### Repro Steps:
1. Launch Azure Data Studio Insiders application.
2. If Welcome screen is not shown on application launch, then navigate to Help --> Welcome.
3. Navigate Extend your data Studio on Welcome screen.
4. Start screen reader, navigate to the decorative images besides the links such as "SQL Server Agent", "SQL Server Profiler", etc.
5. Observe if the decorative images are announced or not.

### Actual:
When screen reader users navigate to the images besides the links such as "SQL Server Agent", "SQL Server Profiler", etc. they are announced with some alternative text which is not appropriate as these images are for decorative purpose.

### Expected:
The decorative images present besides the links such as "SQL Server Agent", "SQL Server Profiler", etc. should not be announced for screen reader users.

### User Impact:
If the content that is present on the screen and it is used for only visual appearance then these content should not be announced to the screen reader users because they will consider it as informative information and this can lead to confusion for screen reader users.

### Attachment link for Reference:
[11548_A11y_AzureDataStudio_Welcome_ExtendyourdataStudio_ScreenReader The decorative image present besides the links such as "SQL Server Agent", "SQL Server Profiler", etc. is announced for screen reader users.zip](https://github.com/microsoft/azuredatastudio/files/4985857/11548_A11y_AzureDataStudio_Welcome_ExtendyourdataStudio_ScreenReader.The.decorative.image.present.besides.the.links.such.as.SQL.Server.Agent.SQL.Server.Profiler.etc.is.announced.for.screen.reader.users.zip)

**Comment by Raghu-addepalli** [comment]
Issue is fixed Hence closing the bug and added attachment.
Githubtags:  #Closed;
[11548_Fixed.zip](https://github.com/microsoft/azuredatastudio/files/10813035/11548_Fixed.zip)
