### ISSUE TITLE
Drag and drop view names the same way we can drag and drop view columns or table names and columns

### ISSUE THREAD

**Issue by Matticusau** [microsoft/azuredatastudio#11569]
**Is your feature request related to a problem? Please describe.**
Currently we can drag and drop Table Names and Columns. We can also drag and drop View Columns into the editor. However we cannot drag and drop the view name.

Raising this as a feature request as I know in the [July Release](https://cloudblogs.microsoft.com/sqlserver/2020/07/15/the-july-2020-release-of-azure-data-studio-is-now-available/) post you mention it was only supporting Tables at this time.

**Describe the solution or feature you'd like**
Be able to drag and drop the view name into the editor

Would also be nice to drag the "Columns" branch in the explorer tree and it drag all the column names into the editor, that is a short cut SSMS has and I miss it.

While I am documenting my wish list, it would be nice to drag and drop other objects not just tables, views etc as we interact with them from a dev/admin perspective.

**Describe alternatives you've considered**
Typing manually... so none

**Additional context**
Here's a quick clip demonstrating the behavior I am seeing.
![20200729164415](https://user-images.githubusercontent.com/11083642/88766851-184d5700-d1bc-11ea-9ef6-c41e6421af20.gif)

Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kburtram** [comment]
@cssuh could you look at this?  seems like a reasonable request.
