### ISSUE TITLE
Jupyter Books should be collapsed/expanded using keyboard shortcuts

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#11560]
With multiple Books showing up its cumbersome to navigate to the root of each book to to collapse/expand levels when the books contains thousands of notebooks. 

There should be keyboard shortcuts and/or menu items to do just that. Below is an example from a popular editor which has this feature.

<img width="481" alt="image" src="https://user-images.githubusercontent.com/29285871/88702131-cde6b000-d0bf-11ea-91e5-6a7274fd9e8a.png">

**Comment by chlafreniere** [comment]
This is a vscode issue if you don't like the existing keyboard shortcut. But items can be collapsed/expanded using the spacebar.
