### ISSUE TITLE
Saving Text Editors defaults to txt

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11564]
Insiders/main

![image](https://user-images.githubusercontent.com/28519865/88726611-eae0aa80-d0e2-11ea-8e0d-34311b884d3e.png)

**Comment by Charles-Gagnon** [comment]
@MaddyDev @chlafreniere FYI

**Comment by chlafreniere** [comment]
I'm guessing this is related to https://github.com/microsoft/vscode/pull/102100/files. This also affects query editor on my machine btw, @anthonydresser

**Comment by Charles-Gagnon** [comment]
This is actually a regression in vs code too - issue submitted

https://github.com/microsoft/vscode/issues/103704

It'd be fairly easy to fix ourselves if needed - but I think we should wait and see if they get back to this quickly.

**Comment by kburtram** [comment]
Fixed in release/1.21
