### ISSUE TITLE
Passing location of NETCoreTargetsPath as linux path doesn't work

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azuredatastudio#11576]
- Azure Data Studio Version:

Steps to Reproduce:

1. resolving a full path to the /mnt/c/.....
2. run the dotnet build <project> "/p:NETCoreTargetsPath=<resolved path>"

```
error MSB4019: The imported project "C:\mnt\c\Users\SimonSabin\source\repos\template.sql\src\lib\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets" was not
found.
```

**Comment by udeeshagautam** [comment]
related : https://github.com/microsoft/azuredatastudio/issues/11577.

Documentation required.

**Comment by alanrenmsft** [comment]
@udeeshagautam is this an August issue? if so, could you please assign this issue?

**Comment by simonsabin** [comment]
its with https://www.nuget.org/packages/Microsoft.SqlServer.DACFx/150.4861.1-preview
