### ISSUE TITLE
azdata error message shows up every launch on dev builds

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11574]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open ADS

Expected: No error messages

Actual: The below error message on every startup.  Please add a "Don't Show Again" option to the error message so it doesn't keep popping up.

<img width="506" alt="Screen Shot 2020-07-29 at 11 26 44 AM" src="https://user-images.githubusercontent.com/599935/88838548-91ce5080-d18e-11ea-80a3-bb90831d9db0.png">

**Comment by Charles-Gagnon** [comment]
Yeah, guess people are probably going to get annoying by that. Its for a non-shipped extension so isn't something that would show up in released builds but I'll remove the error message for now and figure out a better way to handle displaying the message so it isn't a pain for dev work.
