### ISSUE TITLE
Backslash before a single quote within a string breaks syntax highlighting

### ISSUE THREAD

**Issue by richardtallent** [microsoft/azuredatastudio#11571]
- Azure Data Studio Version: 1.19.0

If a `\` appears within an SQL string immediately before a `'` character, all text after that string appears as if it is part of the string (*i.e.*, in dark red by default). Intellisense isn't broken, just the syntax highlighting.

This issue happens both for `\` appearing at the end of a string (where the `'` is the string terminator), or within a string where the `'` is escaped using `''`.

Steps to Reproduce:

1. Enter a valid T-SQL statement that includes a `\` character immediately before a `'` character. Examples:

```SQL
SELECT * FROM [customer] WHERE lastname = 'Smith\';
SELECT * FROM [customer] WHERE company = 'Mary\'' Smith';
SELECT * FROM [orders] -- This entire line is red for either of the above
```

It appears that the syntax highlighter is assuming that `\'` indicates an escaped single quote, but this is not the case in T-SQL. Backslash only escapes a character if the string is followed by an `ESCAPE '\'` clause, and even when that happens, it won't escape a single quote (which can only be escaped using `''`).

*(Oddly enough, this issue also breaks GitHub's SQL syntax hightlighing above.)*

**Comment by Charles-Gagnon** [comment]
This should be fixed with the latest stable release (1.20). Let me know if you're still seeing the issue after updating!
