### ISSUE TITLE
Welcome Page: Open Button Text Not Visible (Light Theme)

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#11598]
When using the default theme and opening the welcome page, I can't see the text in the Open button:

![image](https://user-images.githubusercontent.com/40371649/89075947-2f16b980-d334-11ea-9657-15d64ca0ca3b.png)

**Comment by alanrenmsft** [comment]
@v-bbrady are you working on this one?

**Comment by alanrenmsft** [comment]
@v-bbrady it does repro for me on Mac. BTW, you can ask your questions in the issue so that everyone knows you are working on it.

**Comment by alanrenmsft** [comment]
@v-bbrady please only close the issue when the fix is ported to the release branch. thanks

**Comment by kburtram** [comment]
Fix in release/1.21
