### ISSUE TITLE
Need to check for azdata login context before attempting azdata-based actions

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#11599]
- Azure Data Studio Version:

Steps to Reproduce:

1.Try to deploy a SQL or PG instance via the ADS deployment wizard.  If the user doesnt login via azdata login prior to running the wizard it will fail.

Version: 1.19.0-insider (user setup)
Commit: 187667f4f1f52ee5e5a4b74e9a183574d6f46273
Date: 2020-06-10T05:36:56.219Z
VS Code: 1.46.0
Electron: 7.3.0
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Name: Azure Arc deployment extension for Azure Data Studio (preview)
Id: microsoft.arcdeployment
Description: Provides an experience to deploy Azure SQL DB managed instances and Azure Database for PostgreSQL Hyperscale server groups on Azure Arc from Azure Data Studio. This extension is only applicable to customers in the Azure Arc data services private preview.
Version: 0.3.1
Publisher: Microsoft

From: Pradeep
Sent: Thursday, June 11, 2020 6:02 PM

Hi Team,

As we are aware many of the azdata commands expect the login context to be set with the controller, Is it possible to include login functionality into SQL/PGSQL deployment wizard in ADS.

At present the deployment experience is failing with the following error. How long the azdata stores the login context to a specific controller , when it will expire , does it have a renewal functionality.

Please let me know if you want me to file a request for the same to triage this.

For sure it’s possible for customer to execute login command from console and re-run the notebook but providing a single window experience to have a successful deployment would be great.

 
Creating a PostgreSQL server group on Azure Arc

ERROR: You must be authenticated to run this command. First run the azdata login --help for more information on how to login.

An exception has occurred, use %tb to see the full traceback.

SystemExit: exit code: 1

C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\lib\site-packages\IPython\core\interactiveshell.py:3339: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.

**Comment by Charles-Gagnon** [comment]
@twright-msft Yup - this is part of the work I'm doing for the azdata extension. Should have some sort of experience for the August release.
