### ISSUE TITLE
Table grid misaligned after going to Create insight

### ISSUE THREAD

**Issue by scalancea** [Microsoft/azuredatastudio#116]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:
1. execute some select query (select top10 * from Users -- will suffice)
1. switch to chart view
1. click "Create Insight" (new tab opens)
1. switch back to query tab
1. from the bottom pane, switch to results

Result:
table grid misaligned

**Comment by kevcunnane** [comment]
@anthonydresser any ideas? I've seen this on occasion. It seems to be inconsistent for me but can we fix Slickgrid layout issues somehow to resolve?

**Comment by BartekR** [comment]
If it matters - the same happens for Windows 7 Enterprise - OS Version 6.1.7601, sqlops 0.23.6

**Comment by anthonydresser** [comment]
I have an idea for this fix. Requires code coming from a different feature. Will address this once that is checked in.

**Comment by anthonydresser** [comment]
This should be fixed. Reopen if you continue to experience this.
