### ISSUE TITLE
Kernel does not load properly (Need to Change to Python3 but appears to be not responding)

### ISSUE THREAD

**Issue by charithdilshancaldera** [microsoft/azuredatastudio#11607]
- Azure Data Studio Version: 

![image](https://user-images.githubusercontent.com/68316199/89130649-e105df80-d506-11ea-8898-d142f77a81f9.png)

Steps to Reproduce:

1. Install Azure Data Studios (Fresh Install) 
2. Open a new notebook 
3. Change the kernel to Python 3
4. Let the libraries to install 

I have already checked previous similar issues, but couldn't find anything useful. 

![image](https://user-images.githubusercontent.com/68316199/89130793-37bfe900-d508-11ea-8390-1f4d28f2855a.png)

**Comment by pete1854** [comment]
I have the same problem.

**Comment by chlafreniere** [comment]
@corivera could you help here please

**Comment by corivera** [comment]
@charithdilshancaldera Is there any additional output after the start notebook command in the output, or does it just hang after that point without any additional info?

**Comment by charithdilshancaldera** [comment]
Hi Corivera, 
no there is no additional output after below - 

... Creating C:\Users\[Username]\AppData\Roaming\jupyter\instances\36fb4632-6e1e-4a1a-b6c0-2c8b9fa95f16
... Creating C:\Users\[Username]\AppData\Roaming\jupyter\instances\36fb4632-6e1e-4a1a-b6c0-2c8b9fa95f16\config
... Creating C:\Users\[Username]\AppData\Roaming\jupyter\instances\36fb4632-6e1e-4a1a-b6c0-2c8b9fa95f16\data
... Creating C:\Users\[Username]\AppData\Roaming\jupyter\instances\36fb4632-6e1e-4a1a-b6c0-2c8b9fa95f16\config\custom
... Starting Notebook server
    > "C:\Users\[Username]\azuredatastudio-python\0.0.1\python.exe" "c:\Users\[Username]\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users\[Username]" --port=9634 --NotebookApp.token=0d8a83161c2bb5b138262b3475bb571ffd5f630f6552a7e3

**Comment by chlafreniere** [comment]
If you take the command (port + token aren't necessary) and paste it into a command prompt, would you mind pasting the output?

`"C:\Users[Username]\azuredatastudio-python\0.0.1\python.exe" "c:\Users[Username]\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --no-mathjax --notebook-dir "c:\Users[Username]"`

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by chlafreniere** [comment]
We've identified this as an issue relating to the `notebook` python package. There was a recent update earlier this week which ended up breaking the ability for us to detect when a Jupyter server was running. We're working on a fix for this issue.

In the meantime, @charithdilshancaldera and @pete1854 if you do the following, it should allow you to work around this issue:

First, identify the full path to python (you can see it in the screenshot above after you create a notebook and choose any kernel besides SQL; it's listed in the Output window, and make sure that the dropdown reads "Notebooks" for the channel)

Once you have the full path, you'll be using pip to download a specific version of the `notebook` library (6.0.3 in this case).

`<full_path_to_python> -m pip install --user notebook==6.0.3`

If you get a chance to try this out, it would be very helpful for us to validate our understanding 😄

**Comment by sanderstad** [comment]
@chlafreniere I have executed the command you mentioned and this was the result

![image](https://user-images.githubusercontent.com/6154981/89380822-7d430880-d6f8-11ea-98a6-4f569feddb7e.png)

After restarting ADS I was able to open an existing PowerShell Notebook

**Comment by pete1854** [comment]
Thanks @chlafreniere - this worked for me. Kernel changed successfully.

**Comment by chlafreniere** [comment]
Thanks for confirming, @sanderstad and @pete1854. We have a fix for this in the insiders build today (i.e. so users won't need to run these commands). We'll have this fix in the next (stable) release as well later this month.

**Comment by TheBigBear** [comment]
Had the exact same issue and the workaround of downgrading to 6.03 of notebook module worked for me too. Thanks.

**Comment by chlafreniere** [comment]
A fix for this (i.e. not requiring the workaround with the `notebook` package) is included in our latest release (which shipped earlier today).
