### ISSUE TITLE
Attempting to install arm64 version of Data Studio on WSL Ubuntu with error

### ISSUE THREAD

**Issue by cobrow** [microsoft/azuredatastudio#11606]
- Azure Data Studio Version: azuredatastudio-linux-1.20.1

Steps to Reproduce:

1. Running Windows ARM64 Build 20175
2. Download the deb build for Azure Data Studio
3. Open Ubuntu terminal running WSL version 20.04
4. Ran command to install sudo dpkg -i ./downloads/azuredatastudio-linux-1.20.1.deb
5. Received error message below

dpkg: error processing archive ./downloads/azuredatastudio-linux-1.20.1.deb (--install):
 package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
 ./downloads/azuredatastudio-linux-1.20.1.deb

**Comment by kburtram** [comment]
We currently don't produce arm builds for Azure Data Studio.  Unfortunately this error is expected when installing the amd64 in that environment.
