### ISSUE TITLE
August 2020 - Release Endgame

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11613]
# August 2020 - Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.21

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

## Extensions Testing

Install the latest build of ADS from the link above.

#### Extensions

Extension | Changed in this Release? | Requires latest ADS?
-- | -- | --
Admin Pack |  No
Admin Tool Extension for Windows | No
Agent | No
CMS  | No
Dacpac | Yes | No
Import | Yes | No
Profiler | No
Schema Compare | No
PostgreSQL | No
Query History | No
Data Virtualization | Yes | No
Machine Learning | Yes | Yes
SQL Assessment | Yes | Yes
## Scenario Sign Off

- [x] Query Editor @anthonydresser 
- [x] Notebooks  @chlafreniere 
- [x] Edit Data @smartguest 
- [x] ADS Shell @kburtram 
- [ ] Livesite tooling @qifahs, @MsSQLGirl      
- [x] Data Virtualization @Charles-Gagnon   
- [x] Acquisition @kburtram 
- [x] Connection @Charles-Gagnon 
- [x] Language Service @Charles-Gagnon 
- [x] Query History @Charles-Gagnon 
- [x] Spark Job Submission @Charles-Gagnon 
- [x] Resource Deployment @alanrenmsft 
- [x] Books @MaddyDev with known tracking issue #11657 
- [x] Charting and Insights @alanrenmsft 
- [x] Dashboard @alanrenmsft  
- [x] Backup/Restore @udeeshagautam 
- [x] File Import @kenvanhyning / @aasimkhan30 
- [x] DacFx Deployment @kisantia 
- [x] SQL Profiler @alanrenmsft 
- [x] CMS @abist 
- [x] SQL Agent @abist 
- [x] Azure Integration @aaomidi
- [x] Extension Manager @alanrenmsft 
- [x] Schema Compare @kisantia / @udeeshagautam 
- [x] Big Data Cluster @Charles-Gagnon 
- [x] SSMS Integration @Charles-Gagnon 
- [x] Data Explorer @abist 
- [ ] Machine Learning @llali 
 
## Partner Sing-offs
- [x] PGSQL @akamath46297 
- [x] SQL On Demand @BranislavGrbicMDCS 
- [x] SQL Assessment @alexprotsenko 
- [ ] Managed Instance - Jovan Popovic

[win-user]: https://go.microsoft.com/fwlink/?linkid=2132305
[win-system]: https://go.microsoft.com/fwlink/?linkid=2131971
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2131970
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2131972
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2132306
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2131974
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2131973

**Comment by IanKemp** [comment]
So, which is the latest build?

The one linked here?

Or the one linked at https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main ?

**Comment by kburtram** [comment]
@IanKemp we publish three release channels.  (1) stable builds released monthly with hotfixes as needed (2) insiders build from main branch published daily.  This is the "latest" build. (3) the release candidate build for the upcoming monthly release.  This is the build linked from this issue and is used for the purpose of test sign-off.  We create the release branch about a week prior to releasing, so there's some small delta from the latest RC build and the latest insiders build.
