### ISSUE TITLE
ML Extension - PREDICT sql script formatted for readability

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11619]
**Is your feature request related to a problem? Please describe.**
The PREDICT function is not preformatted, making it hard to read. 

**Describe the solution or feature you'd like**
SQL Keywords should be in capital. 
Indentation to make it easier to read. 
Here's an example: 
[expected_predict_format.txt](https://github.com/microsoft/azuredatastudio/files/5018600/expected_predict_format.txt)

**Describe alternatives you've considered**
Formatting on my own. Or perhaps use one of sql formatter extension.

**Additional context**
n/a

**Comment by llali** [comment]
@MsSQLGirl does this look correct?

DECLARE @model VARBINARY(max) = (
	SELECT model
	FROM [onnx].[dbo].[models3]
	WHERE model_id = 3
);
WITH predict_input
AS (
	SELECT TOP 1000
	CAST([pi].[CRIM] AS FLOAT) AS CRIM,
	CAST([pi].[ZN] AS FLOAT) AS ZN,
	CAST([pi].[INDUS] AS FLOAT) AS INDUS,
	CAST([pi].[CHAS] AS FLOAT) AS CHAS,
	CAST([pi].[NOX] AS FLOAT) AS NOX,
	CAST([pi].[RM] AS FLOAT) AS RM,
	CAST([pi].[AGE] AS FLOAT) AS AGE,
	CAST([pi].[DIS] AS FLOAT) AS DIS,
	CAST([pi].[RAD] AS FLOAT) AS RAD,
	CAST([pi].[TAX] AS FLOAT) AS TAX,
	CAST([pi].[PTRATIO] AS FLOAT) AS PTRATIO,
	CAST([pi].[B] AS FLOAT) AS B,
	CAST([pi].[LSTAT] AS FLOAT) AS LSTAT
	FROM [onnx].[dbo].[features] AS pi
)
SELECT
[predict_input].[CRIM],
[predict_input].[ZN],
[predict_input].[INDUS],
[predict_input].[CHAS],
[predict_input].[NOX],
[predict_input].[RM],
[predict_input].[AGE],
[predict_input].[DIS],
[predict_input].[RAD],
[predict_input].[TAX],
[predict_input].[PTRATIO],
[predict_input].[B],
[predict_input].[LSTAT],
[p].[variable1]
FROM PREDICT(MODEL = @model, DATA = predict_input, runtime=onnx)
WITH (
	variable1 REAL
) AS p

**Comment by llali** [comment]
<img width="424" alt="Screen Shot 2020-08-11 at 4 48 51 PM" src="https://user-images.githubusercontent.com/17187348/89960018-9ebd5c00-dbf2-11ea-966c-670ad39f3108.png">

**Comment by MsSQLGirl** [comment]
Thanks @llali :)
