### ISSUE TITLE
Refresh account credentials and Add an account doesn't work

### ISSUE THREAD

**Issue by hardevs** [microsoft/azuredatastudio#11618]
- Azure Data Studio Version: 1.20.1
- OS: macOS Catalina 10.15.6

Steps to Reproduce:

1. Under CONNECTIONS, click New Connection icon
2. In Connection Details section:
- When an account is selected, clicking on "Refresh account credentials" doesn't do anything
- Selecting "Add an account..." also doesn't do anything

In either cases, I would expect browser to launch and user would need to enter their credentials - but browser is not launching. I'm getting the same issue by downgrading ADS to previous version.

Version: 1.20.1
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:32:14.131Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

**Comment by kburtram** [comment]
@aaomidi do you know what could be happening in this scenario?

**Comment by aaomidi** [comment]
@hardevs Could you please try with the latest insiders build: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by hardevs** [comment]
@aaomidi  Insiders build works just fine.

> @hardevs Could you please try with the latest insiders build: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by aaomidi** [comment]
This fix will be in the next version of ADS :)
