### ISSUE TITLE
Tab Color Does Not Update When Changing Connection

### ISSUE THREAD

**Issue by woojamon** [microsoft/azuredatastudio#11616]
Steps to reproduce:

1. Create two server groups and set a different color for each.
2. Set `"queryEditor.tabColorMode": "fill"` in settings.
3. Click on a server in a group and open a new query. Note that the tab has the correct color.
4. Click the "Change Connection" button near the top of the tab, and change the connection to a server in the other color group.
5. The tab color does not change.

This can be particularly dangerous if switching between development and production servers without knowing about this bug.

**Comment by cheenamalhotra** [comment]
Closing as issue is resolved in recent releases.
