### ISSUE TITLE
install error on a non domain joined local user windows environment

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#11630]
- Azure Data Studio Version:
Version: 1.21.0-insider (user setup)
Commit: f941f9910bd481220cb8d2e944d51163731e849d
Date: 2020-08-03T05:36:14.244Z
VS Code: 1.48.0
Electron: 9.1.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

- Steps to Reproduce:

1. Log in as a local windows user account in a workgroup joined brand new windows vm.
2. Download the Windows User Installer insider's build msi from: https://azuredatastudio-update.azurewebsites.net/latest/win32-x64-user/insider 
3. Run the msi to install ads-insiders version.
4. Click through using default options of the installer. Except on 'Select Additional Tasks' page, check all of the following options:
![image](https://user-images.githubusercontent.com/41588310/89243100-0272d400-d5b8-11ea-858d-728ad2de495a.png)
5. The installation pops up the following error:
**Actual:**
![image](https://user-images.githubusercontent.com/41588310/89239904-6cd34680-d5af-11ea-920f-6b70ee2b4f2c.png)

**Expected:**
Installation to succeed without any error popups.

The product seems to have finished installation and appears to be working.

**Comment by kburtram** [comment]
I am not able to repro this on the current build.  Please let us know if you're still impacted by this issue.
