### ISSUE TITLE
Data Virt validation isn't working for Oracle SID field

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11636]
Able to leave the page without having anything entered in.

**Comment by kenvanhyning** [comment]
IIUC, the wizard works okay as long as a value is entered properly then?  If so, we can move this to September.

**Comment by Charles-Gagnon** [comment]
I'm still working on doing that validation - but yes it should. 

Can we at least see what the fix is? I'm worried this is going to affect other dialogs that use required fields as well which could end up causing lots of issues.

**Comment by chlafreniere** [comment]
Moving out to October since it won't be fixed this week before code complete.

**Comment by Charles-Gagnon** [comment]
This is working as expected now

![image](https://user-images.githubusercontent.com/28519865/95257377-1239af00-07d9-11eb-9370-34940ab5add1.png)
