### ISSUE TITLE
CMS: System Databases and master shown twice

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11640]
The `master` database and the `System Databases` folder shows up twice when expanding the CMS servers.

![Screen Shot 2020-08-04 at 11 06 18 AM](https://user-images.githubusercontent.com/6411451/89328770-ba4cc380-d642-11ea-88d0-a73d16bc0fc0.png)

**Comment by cheenamalhotra** [comment]
Don't see that issue anymore with latest v1.44.1, closing as resolved.

![Image](https://github.com/microsoft/azuredatastudio/assets/13396919/2f5df62f-212a-4e90-994a-8ea7c6c589a3)
