### ISSUE TITLE
Second level pop out menu disappearing after 2 seconds on Windows

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#11655]
reproes on Insider as well as RC builds

as shown in the following screenshot, the Views pop out will disappear after 2 seconds.
![image](https://user-images.githubusercontent.com/13777222/89445262-c0f13e80-d707-11ea-9aa5-ecc944b54dee.png)

**Comment by Charles-Gagnon** [comment]
Shiproom approved

**Comment by kburtram** [comment]
Waiting for vscode merge https://github.com/microsoft/azuredatastudio/pull/11674 to see if this resolves this issue.
