### ISSUE TITLE
Schema compare loading spinner not showing

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#11665]
- Azure Data Studio Version: 1.21.0-rc1

Steps to Reproduce:

1. Do a schema compare
2. Click compare again and see that the loading spinner and loading text don't show (they show for the first comparison)

**Comment by udeeshagautam** [comment]
This is with no changes in Schema Compare Extension (reproing with old SC with latest ADS)

**Comment by udeeshagautam** [comment]
@Charles-Gagnon thanks for the fix, validated in main. Since you have the fix - okay to assign the bug to you?

**Comment by Charles-Gagnon** [comment]
Shiproom approved
