### ISSUE TITLE
Schema compare options reset button doesn't work

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#11666]
- Azure Data Studio Version:  1.21.0-rc1

Steps to Reproduce:

1. Select a source and target for a schema comparison
2. Click on options
3. Change an option, then click Reset and see that the tables are gone
![image](https://user-images.githubusercontent.com/31145923/89468790-0aa05000-d72d-11ea-9b32-97882f94d0ab.png)

**Comment by udeeshagautam** [comment]
This is with no changes in Schema Compare Extension (reproing with old SC with latest ADS)

**Comment by Charles-Gagnon** [comment]
Shiproom approved
