### ISSUE TITLE
azure data studio is very slow (responsiveness) on macos

### ISSUE THREAD

**Issue by joepaulk** [microsoft/azuredatastudio#11673]
- Azure Data Studio Version: Version: 1.20.1
System info (attached):
MacBook Air (13-inch Early 2015)
Processor: 1.6 GHz Dual-Core Intel Core i5
Memory: 8 GB 1600 MHz DDR3

Steps to Reproduce:

1. Try to open an azure sql database using azure ad authentication or sql authentication.
2. Then try to open three or four tabs.

**Comment by joepaulk** [comment]
![macbook-air-sys-info](https://user-images.githubusercontent.com/10821941/89498548-c468f080-d801-11ea-94e9-a982aad4c235.png)

attached the sysinfo.

I can try to add a screen capture of it later.

**Comment by kburtram** [comment]
@joepaulk are there any particular features or other details that can help repro?  For example, are you working with BLOBs, chart, scripts that generate large logs or many resultsets, etc?  We're planning to do some targeted perf fixes in the upcoming months, so specific details of what's slow will help prioritize fixes.  Thanks!

**Comment by cheenamalhotra** [comment]
Closing issue as stale as we haven't heard back from you, please reopen if you still experience the same in latest release - with details as requested above.
