### ISSUE TITLE
Welcome page isn't displayed on 1st launch

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11684]
- Azure Data Studio Version: `release/1.21`
OS: macos

Steps to Reproduce:

1. Open ADS on first launch

Expected: Non-preview welcome page

Actual: No welcome page

**Comment by Charles-Gagnon** [comment]
Shiproom approved pending triage

**Comment by kburtram** [comment]
Fix ported to release/1.21
