### ISSUE TITLE
Constantly trying to connect to Azure SQL server

### ISSUE THREAD

**Issue by IeuanWalker** [microsoft/azuredatastudio#11683]
Issue Type: <b>Bug</b>

Failing to connect to azure SQL server through AAD MFA

Just constantly loading

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
azuredatastudio-postgresql|Mic|0.2.6
cms|Mic|0.8.0
dacpac|Mic|1.5.0
datavirtualization|Mic|1.6.0
import|Mic|0.18.0
managed-instance-dashboard|Mic|0.4.1
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.4.0
sql-assessment|Mic|0.2.0
schema-visualization|R0t|0.2.0
sql-search|Red|0.4.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by aaomidi** [comment]
Could you also please try this scenario on the latest insiders version?

**Comment by Charles-Gagnon** [comment]
@IeuanWalker I'm closing this since we haven't heard back - if you are still encountering this issue and can provide the above requested information let us know and we can re-open if needed.
