### ISSUE TITLE
Column editing

### ISSUE THREAD

**Issue by phampdx** [microsoft/azuredatastudio#11682]
Issue Type: <b>Feature Request</b>

Please provide column mode editing feature as available in VS and SSMS.

Thanks,

Khanh

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18363

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/282, as I assume by Column Edit you mean editing the column definitions of a table.  Please let me know if there is a different functionality you're referring to.
