### ISSUE TITLE
AAD - Auth Type, no discernable tenant selection

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/azuredatastudio#11681]
Issue Type: <b>Bug</b>

Trying to sign in to a Managed Instance and I get 3 "Default Directory" options in the "Azure AD tenant" field.  None of them work.

I would expect to see two, that are differentiated in some way.

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1241 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.1.0
azdata-sanddance|msr|3.0.0
sql-search|Red|0.4.0

</details>

**Comment by Charles-Gagnon** [comment]
@dsmeltz Could you post an image of what you're seeing?

**Comment by dsmeltz** [comment]
I'm on 1.21.0 now and everything seems to working as it should.
