### ISSUE TITLE
pre-login Handshake

### ISSUE THREAD

**Issue by KhairulHabibSamaon** [microsoft/azuredatastudio#11707]
Issue Type: <b>Bug</b>

A connection was successfully established with the server, but then an error 
occurred during the pre-login handshake. (provider: SSL Provider, error: 0 - 
The wait operation timed out.)

previous version i'm ok to connect to the server. but after update lately, that server cannot login anymore while i'm login with other software it's work

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:32:14.131Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_57358|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
This looks likely to be caused by https://github.com/microsoft/azuredatastudio/issues/11367#issuecomment-659614111 - please try either installing the server certificate locally or setting `TrustServerCertificate` to true in the advanced properties and see it that solves your issue.

**Comment by KhairulHabibSamaon** [comment]
@Charles-Gagnon thanks boss it's working
