### ISSUE TITLE
Improve logging for test failures

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11717]
We get intermittent test failures from the integration tests, but currently the error messages aren't useful enough to be able to tell exactly what went wrong from the logs themselves. We should investigate whether there's any additional information we can include in the logs to help diagnose these issues.

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=72403&view=logs&j=bfccef3f-45d4-504d-9a7f-a8a74922e6bf&t=6a7a61df-4b52-52e2-d763-2058c7ca42b4

```
  1) Dacpac integration test suite
       Import and export bacpac:
     Error: Timeout of 60000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (E:\mssqltoolsagentworkspace\102\s\extensions\integration-tests\out\test\dacpac.test.js)
  	at listOnTimeout (internal/timers.js:531:17)
  	at processTimers (internal/timers.js:475:7)

  2) Object Explorer integration suite
       Standalone database context menu test:
     Error: This editor is not connected to a database (Parameter 'OwnerUri')
  	at e:\mssqltoolsagentworkspace\_temp\azuredatastudio-win32-x64\resources\app\extensions\mssql\dist\main.js:1:66723
  	at e:\mssqltoolsagentworkspace\_temp\azuredatastudio-win32-x64\resources\app\extensions\mssql\dist\main.js:1:67017
  	at Immediate.<anonymous> (resources\app\extensions\mssql\dist\main.js:1:67376)
  	at processImmediate (internal/timers.js:439:21)

```

**Comment by aasimkhan30** [comment]
@Charles-Gagnon should I close this issue now?

**Comment by kburtram** [comment]
Closing older engineering focused bugs.  Please reactive if this is tracking upcoming planned work.
