### ISSUE TITLE
Error when cancelling out of ML "Manage Packages" prompts

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#11716]
1. Open dashboard
2. Navigate to Machine Learning tab
3. Click `Manage packages in database`
4. Get prompted to install packages
5. Decline (cancel) the dialog by hitting escape or clicking elsewhere

This error message shows up

![image](https://user-images.githubusercontent.com/28519865/89685231-cccc3480-d8b0-11ea-8420-5d8d3806908e.png)

Show an error message of some sort here seems fine - but this error message in particular doesn't seem useful. It should probably say something about needing to have those packages to continue.

**Comment by udeeshagautam** [comment]
This is fixed. not sure why the PR didnt close it.

**Comment by Charles-Gagnon** [comment]
@udeeshagautam @llali Because you need to put the keyword before every issue that you want closed. 

Doing `fixes #1234 and #4567` will only close 1234. You need to do `fixes #1234 and fixes #4567` or something similar
