### ISSUE TITLE
Allow Tasks API

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#11725]
In an attempt to make ADS development tool for Azure Functions it requires that the Tasks API be available. The Azure Functions extension integrates with it for function development.

Install the extensions for Azure Account and Azure Functions and then upon trying to activate the Azure Functions explorer you see this error:

![image](https://user-images.githubusercontent.com/11204251/89726893-81677280-d9e5-11ea-82da-4874ee4cac51.png)

Tasks themselves offer users the ability to automate more actions in VS Code, which I can only assume should allow the same thing for ADS. Tasks in VS Code allow you to perform multiple commands from the command palette or execute scripts/processes more seamlessly.

**Comment by kburtram** [comment]
@abist is currently working on enabling the vscode Tasks API and integrating with the existing ads task management functionality as part of the SQL Project build feature.  The current plan is to release this in September.

**Comment by rrmistry** [comment]
Linking to related issue https://github.com/microsoft/azuredatastudio/issues/10370 so we can potentially close at the same time.
