### ISSUE TITLE
ML - Azure API warning when connecting to Azure 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#11730]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open import model wizard
2. select Azure to import model from Azure
3. login to azure

Expected: Subscriptions should show up successfully
Actual: ADS shows a warning "
A call was made to azdata.accounts.getSecurityToken, this method is deprecated and will be removed in future releases. Please use getAccountSecurityToken instead. "

Subscriptions are loaded finally but warnings keeps showing up

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/11718 😄
