### ISSUE TITLE
Still failing to login to Azure via https://localhost

### ISSUE THREAD

**Issue by IanKemp** [microsoft/azuredatastudio#11731]
- Azure Data Studio Version: 1.20.1, 1.21.0-rc1, 1.21.0-insider

Steps to Reproduce:

1. Click Azure > Sign into Azure... > Add account
2. Browser window opens at https://localhost:<some_port>/signin?nonce=<some_base64_value>
3. Nothing else happens

The fact that this is still happening, months after I reported basic usability issues with logging in to Azure (#8331) and after others have reported the same issue (https://github.com/microsoft/azuredatastudio/issues/8829#issuecomment-572046339), gives me very little confidence in the team developing this application.

To be blunt, Azure Data Studio is not fit for purpose. It is broken in the most fundamental ways. Apart from not being able to login to Azure, attempting to launch a profiling session against an Azure SQL DB added via the "Servers" area (the only reason I have this terrible piece of software installed) gives "Cannot profile Azure system databases" (I didn't realise I was trying to do that). Yes, the toast error messages are _beautiful_, but they don't provide any sort of guidance as to what the actual problem is or how I might go about fixing it. You may as well dump the errors to console.out, they're that useful.

"Open source" does not mean "release to the public without any sort of internal testing". It does not mean "use customers as alpha testers". The Microsoft of a decade ago would never have allowed an application in this state to get into customers' hands. I want that Microsoft back.

**Comment by kburtram** [comment]
@aaomidi any idea why the localhost auth page isn't loading?

@IanKemp have you tried using Device Code auth to add the Azure account?  I don't think that method requires opening a localhost socket.

<img width="549" alt="Screen Shot 2020-08-10 at 11 01 46 AM" src="https://user-images.githubusercontent.com/599935/89815210-39d20b00-daf9-11ea-8744-b882a4000d5a.png">

**Comment by kburtram** [comment]
@IanKemp regarding the SQL Profiler error, the issue there is connections to servers use the master database as the DB for the connection.  So when Profiler is launched from this node it tries to use master, which is blocked on Azure.  A workaround is to specify the database in the connection dialog when creating the connection and launch the profiler from this node.  I'll open a separate bug to resolve this issue as part of taking the SQL Profiler extension out of preview.

**Comment by aaomidi** [comment]
The issue here is that your browser has an HSTS tag attached to localhost, this means your browser will force localhost to load with https - and that will just fail.

If you're on edge:
- Visit edge://net-internals/#hsts
- Delete domain security policies
- Enter `localhost`

If you're on chrome, do the same thing as edge except the address is chrome://net-internals/#hsts. Other browsers have similar settings but I'm not sure where they are.

**Comment by aaomidi** [comment]
Please comment back if the hsts problem didn't solve your issue and we can look into it more!
