### ISSUE TITLE
shortcut sp_help

### ISSUE THREAD

**Issue by daviodassi** [microsoft/azuredatastudio#11749]
Issue Type: <b>Bug</b>

shortcut sp_help alt + f2 doesn´t work znymore

Azure Data Studio version: azuredatastudio 1.20.1 (fe6312306647441b30102a64bb43abb06ebcf2be, 2020-07-17T02:39:41.016Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3317U CPU @ 1.70GHz (4 x 1696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
cms|Mic|0.8.0
dacpac|Mic|1.5.0
import|Mic|0.18.0
profiler|Mic|0.11.0
whoisactive|Mic|0.1.4
sql-search|Red|0.4.0
simple-data-scripter|sea|0.1.3

</details>

**Comment by kburtram** [comment]
@daviodassi I think this shortcut can be added by installing the "SSMS Keymap" extension from the Extension Manager.  I don't think this was previously the default keymap for `alt-f2` as far as I can recall.

**Comment by daviodassi** [comment]
Until previous version it has that shortcut, but in version 1.20.1 it´s gone. 
I tried "SSMS Keymap" extension but I had the same issue

**Comment by daviodassi** [comment]
@kburtram 
I have another computer here. 
I just did the shortcut test in version 1.16.0 and it had sp_help shortcut alt+F2 working fine (without "SSMS Keymap" extension installed)
I updated for the last version 1.20.1 and it´s gone in this another machine.

Hope it helps!

**Comment by Charles-Gagnon** [comment]
Thanks for the additional information, we made some changes to the settings recently and this got broken with that. I have a PR out to fix it - that should be in insiders in the next day or two.
