### ISSUE TITLE
Extension Admin pack for SQL Server not working properly

### ISSUE THREAD

**Issue by coolsekali** [microsoft/azuredatastudio#11753]
After installing "Admin Pack for SQL Server" extension, none of the administration options shows up on the database info page. I was able to reproduce the issue on a different machine running Windows server 2019.

Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

![ADS Issue](https://user-images.githubusercontent.com/24290978/89926937-70bc2580-dbba-11ea-9ee1-dac37d01290f.png)

**Comment by kburtram** [comment]
@coolsekali please verify that you have Preview Features setting enabled.

<img width="558" alt="Screen Shot 2020-08-11 at 10 34 08 AM" src="https://user-images.githubusercontent.com/599935/89929602-440a0d00-dbbe-11ea-9b7f-1f7c7b35df70.png">

**Comment by coolsekali** [comment]
Thank you! I have enabled the preview and it works. Thanks!
