### ISSUE TITLE
Add to Path on MacOSX

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/azuredatastudio#11768]
How do you add ```azuredatastudio``` to path on mac osx? to install i just downloaded a .zip and put the application in the /Applications folder. Is there a default location the binaries/folders are stored on mac such as /bin or something?

**Comment by kburtram** [comment]
@stevenhurwitt have you tried to run the "Install azuredatastudio command in PATH" command? You can access it from the command-line.

<img width="661" alt="Screen Shot 2020-08-11 at 6 32 14 PM" src="https://user-images.githubusercontent.com/599935/89965230-290cbc80-dc01-11ea-9251-12cfce7009c3.png">

**Comment by stevenhurwitt** [comment]
ohhh thanks didn't realize that was literally a command in data studio! that should work
