### ISSUE TITLE
Search in Notebook viewlet errored after collapse all and expand a book

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11779]
- Azure Data Studio Version:
Version: 1.21.0-rc1 (user setup)
Commit: cb1f46bfcd8620a3670284097fb56d32e602517b
Date: 2020-08-09T18:38:41.644Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Load a workspace with multiple books.
2. Perform a search in **Notebook viewlet** where the results will show the results in multiple books.
![image](https://user-images.githubusercontent.com/6405919/90063582-73904680-dc9e-11ea-8d91-c7e49273d83d.png)

3. Click Collapse all 
![image](https://user-images.githubusercontent.com/6405919/90063270-f49b0e00-dc9d-11ea-85cb-ef9a70434fa7.png)
4. Then navigate to one of the folders, i.e. "content <book name>", and click one of the files.

You'll then see an error like this:
![image](https://user-images.githubusercontent.com/6405919/90063393-2c09ba80-dc9e-11ea-9d78-12549451e7b9.png)

Then for some reason, **Explorer viewlet** will be launched / opened.
![image](https://user-images.githubusercontent.com/6405919/90063453-43e13e80-dc9e-11ea-9802-f9acfd16d46a.png)

Expected:
Search should 
1. not produce an error, and 
2. not jump to Explorer viewlet.

**Comment by chlafreniere** [comment]
@MaddyDev can you take a look?
