### ISSUE TITLE
ADS maximized window spills onto second monitor

### ISSUE THREAD

**Issue by coltr-genebygene** [microsoft/azuredatastudio#11778]
- Azure Data Studio Version: 1.21.0
Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Maximize ADS on a display in a multi-monitor setup
2. You will see that the edges of the ADS window spill over onto the bordering screens

**Comment by kburtram** [comment]
Closing as diff of https://github.com/microsoft/azuredatastudio/issues/11585
