### ISSUE TITLE
Diagram and Table Design UI

### ISSUE THREAD

**Issue by WisdomCorp** [microsoft/azuredatastudio#11787]
** We would like the Diagram and Table Design UI like in SQL Server Management Studio like in Windows. **
Diagram like how we visually build relationship in Sql Server Management Studio in Windows. Thanks

**Comment by kburtram** [comment]
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/282 and https://github.com/microsoft/azuredatastudio/issues/94.  Thanks for opening this suggestion!
