### ISSUE TITLE
Broken link to release archive

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [microsoft/azuredatastudio#11788]
- Azure Data Studio Version: 1.21.0

Steps to Reproduce:

1. https://github.com/microsoft/azuredatastudio/releases/tag/1.21.0 

2. Linux TAR.GZ (https://go.microsoft.com/fwlink/?linkid=2138706)

3. curl -I "https://go.microsoft.com/fwlink/?linkid=2138706"
HTTP/1.1 302 Moved Temporarily
Location: https://azuredatastudio-update.azurewebsites.net/1.21.0/linux-x64-archive/stable

4. curl -I "https://azuredatastudio-update.azurewebsites.net/1.21.0/linux-x64-archive/stable"
**HTTP/1.1 404 Not Found**

**Comment by Charles-Gagnon** [comment]
Fixed, thanks!
