### ISSUE TITLE
Cannot activate extension for SQL Server Import

### ISSUE THREAD

**Issue by Titovdwalt** [microsoft/azuredatastudio#11789]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a new query
2. Connect to a database
3. press ctrl + I

It will then say "Activating Extensions" and then nothing happens

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Can you investigate?

@Titovdwalt - If you can provide logs (details below) that'd help

**Comment by Titovdwalt** [comment]
Hi @Charles-Gagnon, I managed to get it to work.
I restarted and then reinstalled the app (not sure if any of that was necessary).

It then showed that it was installing a few things after I pressed CTRL + I and then after a minute or so it worked!

**Comment by mauvedeity** [comment]
I'm also having this issue, on MacOS 10.15.6, fully patched up to date. I've followed the steps above to find the log files, but I can't see "renderer.log".

**Comment by Charles-Gagnon** [comment]
@mauvedeity 

The actual filename will have a number in it - e.g. `renderer1.log`. 

If you don't see that - what files do you see in that folder?
