### ISSUE TITLE
Expand/Collapse All Nodes of a Database Project from Context Menu

### ISSUE THREAD

**Issue by anjalia** [microsoft/azuredatastudio#11795]
Problem:
Users would like functionality to easily view all of the subfolders and files of a database project

Suggested Improvement:
Add "Expand All" and "Collapse All" to context menu when one right-clicks on a specific database project

Need for this discussed in PR: https://github.com/microsoft/azuredatastudio/pull/11728. Related to issue #10979

**Comment by udeeshagautam** [comment]
completed
