### ISSUE TITLE
Kusto query shows layout issuse

### ISSUE THREAD

**Issue by joberume** [microsoft/azuredatastudio#11805]
Perhaps due to issue shared via email with you, I get into this unstable state for querying kusto:
![image](https://user-images.githubusercontent.com/52225468/90186677-6a21df80-dd6d-11ea-8bfa-9ee41eac131b.png)

**Comment by MsSQLGirl** [comment]
Also had similar issue - 
![image](https://user-images.githubusercontent.com/6405919/90323957-849abb00-df1d-11ea-99fe-7afe648d6d0f.png)

**Comment by MsSQLGirl** [comment]
@gupta1 I can't seem to repro this in the latest version.
