### ISSUE TITLE
Need a provider specific management dashboard in ADS

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#11804]
**Is your feature request related to a problem? Please describe.**
Users can add widgets to show up on the management dashboard. Current users have widgets backed by SQL queries. Now that we are adding support for Kusto, these widgets show up on the Kusto management dashboard and they are errored out.
![image](https://user-images.githubusercontent.com/7318752/90186576-347cf680-dd6d-11ea-9478-2343bcb5f5e9.png)

**Describe the solution or feature you'd like**
Users should be able to specify which provider they are adding the widget for.

**Comment by kburtram** [comment]
@qifahs widgets can control which provider's dashboard they will show up on using a when clause.  For example, here is how we restrict some of the default widgets to MSSQL https://github.com/microsoft/azuredatastudio/blob/main/extensions/insights-default/package.json#L65.  

The default Kusto dashboard doesn't have these widgets, but you can add some using the when clause for that provider.  If extensions are showing widgets on Kusto that don't belong there please log a bug against those extensions to add a filter to supported providers.

Here's what the Kusto dashboard looks like by default.  Please let me know if I'm missing something with this feature request.

![image](https://user-images.githubusercontent.com/599935/132778702-2c6b862e-e0bf-4a34-9042-3dd88451b1f0.png)
