### ISSUE TITLE
Need "Script as Execute" option for Kusto functions

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#11800]
**Is your feature request related to a problem? Please describe.**
When the current tab is not Kusto, then there is no way to open a new query window using the function as the starting point. 

**Describe the solution or feature you'd like**
Add a "Script as Execute" right-click menu option to open a new Kusto query window on the function.

**Describe alternatives you've considered**
Alternative is to create a query window on a table, and then drag/drop the function to it, then clear out the rest of the query. This is very tedious and not discoverable.

**Comment by JustinMDotNet** [comment]
This was implemented in PR #11990
