### ISSUE TITLE
Refresh Kusto cluster doesn't seem to reconnect properly

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11824]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to ADX cluster in the Connections viewlet.
2. After a few minutes, try to expand the objects. It will show:
![image](https://user-images.githubusercontent.com/6405919/90323668-371c4f00-df19-11ea-8b83-8fd135156322.png)

3. Click on Refresh on the database level or the cluster level, it still doesn't seem to reconnect.

Expected: reconnecting. 
Current workaround: disconnect and create a new connection.

**Comment by qifahs** [comment]
Related to #11830

**Comment by JustinMDotNet** [comment]
This was fixed with PR#1085 ^. Closing issue.
