### ISSUE TITLE
Reopening Azure Data Studio with Kusto notebook didn't work

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11827]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a Kusto notebook in ADS with some query and results. 
2. Close and reopen. 
![image](https://user-images.githubusercontent.com/6405919/90324062-d5f77a00-df1e-11ea-8a3a-9aab34778671.png)

Or .. 
Reopen a saved Kusto notebook also causes similar issues.

**Comment by gupta1** [comment]
@MsSQLGirl  I cant repro this issue. I will close this for now.
