### ISSUE TITLE
Drag and drop object to a Query Window should use Kusto identifier quoting

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11823]
- Azure Data Studio Version:

Steps to Reproduce:

1. Drag & drop a table from object explorer to a Query window.

Actual:
![image](https://user-images.githubusercontent.com/6405919/90323571-cc1e4880-df17-11ea-83ce-32fd986a2e7b.png)

Expected:
`['Covid19'] | take 10`
or
`["Covid19"] | take 10`

As per documented [here](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/schema-entities/entity-names#identifier-quoting).

**Comment by MsSQLGirl** [comment]
@JustinMDotNet - can you please confirm that the new behavior (for drag and drop) would be using the following special character handling? i.e. `['entity name']`  or `["entity name"]`
![image](https://user-images.githubusercontent.com/6405919/91914611-5206f700-ec6d-11ea-8b46-45d52344b67e.png)

**Comment by JustinMDotNet** [comment]
This has been implemented as part of PR 11990.
