### ISSUE TITLE
Server / cluster icon on Connections wizard should represent the server / cluster type

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11825]
- Azure Data Studio Version:

Steps to Reproduce:

Connection wizard
![image](https://user-images.githubusercontent.com/6405919/90323837-924f4100-df1b-11ea-9a9f-23ff180048fd.png)
Usability issues:
1. it's hard to tell that one of the kusto connection is using SQL vs the other one using Kusto. 
2. hard to tell which one is Kusto vs SQL - it'd be good to be able to distinguish with icon cue.
3. inconsistency of this experience vs Connection viewlet / Object Explorer -

Connection viewlet / object explorer
![image](https://user-images.githubusercontent.com/6405919/90323845-ab57f200-df1b-11ea-9ba8-371ad2052f44.png)

**Comment by JustinMDotNet** [comment]
This effort is being tracked here: https://mssqltools.visualstudio.com/ADS%20LiveSite%20Support/_workitems/edit/3486

**Comment by JustinMDotNet** [comment]
This was fixed with #12621
