### ISSUE TITLE
Switching query tabs closes both

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#11832]
- Azure Data Studio Version: 
![Screen Shot 2020-08-17 at 2 05 43 PM](https://user-images.githubusercontent.com/18150417/90428928-bed99900-e092-11ea-86f7-937dc6f87e71.png)

Steps to Reproduce:

1. Connect to two different DBs (I had one local DB and on Azure DB)
2. Select the 'Select Top 1000' option from one table in the local DB
3. Select the 'Select Top 1000' option from one table in the Azure DB 
4. You should have two tabs open now - try to switch to the tab with the query from step 2
5. Both tabs get closed and the following error is presented:
![Screen Shot 2020-08-17 at 2 01 27 PM](https://user-images.githubusercontent.com/18150417/90428541-26431900-e092-11ea-8cb2-68121d80bbea.png)

Additionally, after this happens I cannot open a new query at all.
![Screen Shot 2020-08-17 at 2 02 19 PM](https://user-images.githubusercontent.com/18150417/90428620-4541ab00-e092-11ea-87d7-8388e6bdd70d.png)

Note: this was on a mac

Update: this bug is not present on the latest release but shows up on the insiders build

**Comment by anthonydresser** [comment]
Can you still repro this in main? doesn't seem to be reproing for me

**Comment by kburtram** [comment]
I can repro on today's insider build with the following.

1. Open a connected SQL editor
2. Open another connected SQL editor
3. Run a query in one editor
4. Run a query in the other editor
5. Switch back to the first editor

**Comment by anthonydresser** [comment]
This is no longer reproing on main, I merged my table in this morning, so I might have fixed it as part of that PR, but I can verify.

**Comment by anthonydresser** [comment]
This was fixed as part of #11781
