### ISSUE TITLE
Notebook: Scrolling horizontally on the editor should be visible at all times (on the bottom of the screen)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11835]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: 3192d056f2d5545089a61f5ef6debd9382bb07c7
Date: 2020-08-17T05:37:23.730Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Write very long notebook and that goes beyond the screen length. 
2. When editing it's hard to scroll left and right.

**Comment by halerankin** [comment]
Screen shots?
Does the content wrap or not?

**Comment by MsSQLGirl** [comment]
Use the following file to repro. Please change the file extension to ipynb. 
[ScrollingSync.txt](https://github.com/microsoft/azuredatastudio/files/5249250/ScrollingSync.txt)

When scrolling using the editor scroll (not the notebook scroll), it's a little bit tricky to see if what you see on the editor is what you see in the preview. I'm not sure what's a good way to solve this btw. 
An alternative might be that a user can click on the spot on the editor and the preview will try to match that position. 




![NotebookScrolly](https://user-images.githubusercontent.com/6405919/93661674-705f4780-fa0e-11ea-9e7e-6f4a1ae3710b.gif)
