### ISSUE TITLE
DB project - need to support Miscellaneous area (to exclude folders & files from Build)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11836]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: 3192d056f2d5545089a61f5ef6debd9382bb07c7
Date: 2020-08-17T05:37:23.730Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to repro:
1. Add a new folder and a new script (e.g. kql file)
2. Click on Build.. it will come up with an error. 

Ask: we need a way to exclude certain folders in the project from Build but make it visible in the Projects pane.

**Comment by udeeshagautam** [comment]
We should have feature parity wih SSDt here. if I know correclty we added the exclude for files already. The folder exclude is still remaining.

**Comment by kisantia** [comment]
there is currently support for excluding folders. Closing this because including excluded files/folders is being tracked in https://github.com/microsoft/azuredatastudio/issues/13344
