### ISSUE TITLE
After a period of inactivity on Query editor, unable to reconnect automatically

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11830]
- Azure Data Studio Version:
Version: 1.21.0
Commit: c44e2bc6104d3cfcdc4b2800d9ec56515491f988
Date: 2020-08-13T19:16:41.418Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Write a query in Kusto and then don't use it for a few minutes. 
2. Come back to the query and rerun the query. You should see an error that looks like this: 

![image](https://user-images.githubusercontent.com/6405919/90323698-af831000-df19-11ea-8293-d73009523802.png)

Usability issue: 
a. The error can be a little misleading, causing users to think that they are unauthorized.
b. Looking at the "Disconnect" and "Change connection" pane, it's not obvious that I've been disconnected and suppose to change connection. (Or perhaps, I'm using the wrong cue to look if I've been disconnected in the Query editor?)

**Comment by JustinMDotNet** [comment]
SqlToolService PR to resolve issue
https://github.com/microsoft/sqltoolsservice/pull/1081/files
