### ISSUE TITLE
Notebook newline behavior in ADS vs ADO Jupyter Preview

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11846]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: 3192d056f2d5545089a61f5ef6debd9382bb07c7
Date: 2020-08-17T05:37:23.730Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Create a bullet point with a new line and create a table. 
ADS will show render the table properly.
ADO notebook preview will not render the table.

**Comment by chlafreniere** [comment]
@MsSQLGirl can you help me out with some sample markdown? I'm a bit confused.

Are you saying that there should be a bullet point and then a table right below that bullet?

**Comment by MsSQLGirl** [comment]
Vanilla jupyter book shows the following:
![image](https://user-images.githubusercontent.com/6405919/93660985-2162e380-fa09-11ea-8db6-31cdfe3a0772.png)

ADS RC1 shows the following:
![image](https://user-images.githubusercontent.com/6405919/93661002-3ccdee80-fa09-11ea-8c7f-1c163c16e646.png)
Version: 1.22.0-rc1 (user setup)
Commit: 5a2fdc4034b63c72e110e21d8d9dfc5b27f540f3
Date: 2020-09-19T04:15:34.721Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041


ADO Jupyter Preview shows the following:
![image](https://user-images.githubusercontent.com/6405919/93661049-89b1c500-fa09-11ea-88c4-4bc7e8ef992b.png)

Notebook to repro - 
[NotebookWithTables.txt](https://github.com/microsoft/azuredatastudio/files/5249221/NotebookWithTables.txt)

**Comment by chlafreniere** [comment]
There's no styling info saved in the notebook here. Is the ask them to center all tables?

**Comment by MsSQLGirl** [comment]
(Sent this too late last night and forgot to provide context :))
* ADO Jupyter preview seems to be having problems with bullets in general.
I've logged this issue with the ADO Jupyter Notebook renderer instead, since ADS behavior is matching with vanilla jupyter notebook. https://github.com/Azure/ipynb-renderer/issues/5

Styling wise - centered vs not, let's track that separately :) 

Closing this item~
