### ISSUE TITLE
Virtualize Data from CSV isn't working

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#11842]
- Azure Data Studio Version: 1.21.0 / data virt extension: 1.7.0

Steps to Reproduce:

1. Connect to a BDC
2. Expand the HDFS and navigate to any CSV
3. run the CSV virtualize data wizard
4. just hit next on first screen
5. 2nd screen (preview) doesn't show preview and gives an error: Method not found

**Comment by bweissman** [comment]
@Charles-Gagnon  - could you look into that for me please?

**Comment by Charles-Gagnon** [comment]
@bweissman Thanks, found the issue and am working on a fix. Will update once that's available.

**Comment by Charles-Gagnon** [comment]
@bweissman Could you try out https://sqlopsextensions.blob.core.windows.net/extensions/datavirtualization/datavirtualization-1.8.0.vsix and verify that it fixes your issue?

1. Uninstall current data virt extension
1. Download vsix from above
1. Manually install VSIX (File -> Install Extension from VSIX Package)
1. Reload ADS
1. Try to Virtualize from CSV

**Comment by bweissman** [comment]
@Charles-Gagnon The wizard runs through but the output is wrong. 

The issue is the format that's being generated (STRING_DELIMITER and FIRST_ROW, see below):

Output:

CREATE EXTERNAL FILE FORMAT [CSV]
WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'Some ''"''', FIRST_ROW = 1));

Desired (and previous) Output:

CREATE EXTERNAL FILE FORMAT [CSV]
WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'\"', FIRST_ROW = 2));

**Comment by Charles-Gagnon** [comment]
Thanks, yeah looks like some stuff has changed with the underlying Prose discovery implementation. Investigating. 

@aasimkhan30 FYI

**Comment by bweissman** [comment]
Works like a charm - thank you :)

**Comment by Charles-Gagnon** [comment]
@bweissman The extension has been updated on both stable and insiders builds. I would suggest uninstalling the extension that I gave you and then installing it again from the gallery (there shouldn't be any differences but it's good to make sure you're on the "official" version)

Thanks again for helping track down this issue!
