### ISSUE TITLE
Notebook markdown toolbar should always be pinned on the top when scrolling

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11847]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: fc9d08a62bfc50596d4c5c4dba4f9567b7562908
Date: 2020-08-18T05:41:09.330Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Write a long text that wraps around. The length should exceed the app length.
2. When scrolling on the text, the markdown toolbar disappears.

Usability issue: users need to scroll up and down to do formatting just to get to the markdown toolbar.

**Comment by halerankin** [comment]
@MsSQLGirl This is not a bug. It's a request to modify UI behavior. The markdown toolbar remains at top of the cell and does not stick to top of screen when content is scrolled.

**Comment by MsSQLGirl** [comment]
Reopened it because while it was not a bug, it had usability implication. 
Closed it because I have just realized that Laura has solved the issue regardless the classification of the issue :D 

Thanks @halerankin & @laurajjiang.
