### ISSUE TITLE
Azure tenant drop-down isn't sized correctly with no accounts

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11856]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Create Firewall rule dialog with no Azure accounts added

Actual: Azure tenant drop-down is not sized correctly

![image](https://user-images.githubusercontent.com/599935/90560610-39b6b880-e154-11ea-9720-74b148dc57c4.png)

**Comment by aaomidi** [comment]
Huh I solved this issue a while ago hmm

**Comment by kburtram** [comment]
I'm still see this, but this time with accounts added.
