### ISSUE TITLE
ADS - Jupyter notebook: Unable to open several instances of the TSG100 notebook

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#11851]
- Azure Data Studio Version:

Steps to Reproduce:

1.In this example I would like to run one instance of the notebook to troubleshoot each of the Postgres instances that are deployed:
![image](https://user-images.githubusercontent.com/22226386/90549508-79c16f80-e143-11ea-8dd6-99b6ac169123.png)

**Comment by chlafreniere** [comment]
@TheJY this is by design for now. Please save the notebook if you need to execute it multiple times.
