### ISSUE TITLE
Query History truncates query when selected

### ISSUE THREAD

**Issue by JonathanWilkins** [microsoft/azuredatastudio#11865]
- Azure Data Studio Version:
Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Select a query to execute
2. Execute query that has been selected
3. Query showing in query has been truncated in the beginning
![Screenshot 2020-08-19 at 11 20 17](https://user-images.githubusercontent.com/3468550/90623500-73e49080-e20e-11ea-9425-c3fad64c4571.png)

**Comment by Charles-Gagnon** [comment]
The extension has been refactored to retrieve the query text in a different way so this should no longer be an issue. Let me know if you're still seeing this!
