### ISSUE TITLE
WYSIWYG – Ability to copy paste table from excel to notebook text cell

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#11861]
**Is your feature request related to a problem? Please describe.**
Users want to add a selection of cells (rows x columns) from Excel to Notebook. They want the pasted data gets preformatted by notebook. 

**Describe the solution or feature you'd like**
Ctrl+V to understand context and build a table markdown with the context automatically for users when pasting to text cell in Notebooks 

**Describe alternatives you've considered**
none. Need to build manually. 

**Additional context**
n/a

**Comment by MsSQLGirl** [comment]
@rajeshka - feel free to clarify the expected experience here in case I missed anything.

**Comment by chlafreniere** [comment]
This is tracked by WYSIWYG tasks. Just tried this myself on my private build, and copy/paste excel --> notebook worked as expected.
