### ISSUE TITLE
[Database Support] IBM DB2

### ISSUE THREAD

**Issue by mahoneyl** [microsoft/azuredatastudio#11866]
If you want to see DB2 support in Azure Data Studio, click the thumbs up 👍 sign.

**Note:** Please keep comments to this issue focused on discussions of what you would like to see instead of +1 comments.

**Comment by mahoneyl** [comment]
There were a few threads in the past requesting DB2 support which were closed. I wanted to show there's still interest for this feature! AzureDataStudio is a great product which would make a huge impact in the DB2 world.

https://github.com/microsoft/azuredatastudio/issues/929
https://github.com/microsoft/azuredatastudio/issues/6043
https://github.com/microsoft/azuredatastudio/issues/56

**Comment by tacusa** [comment]
I agree with Mahoneyl. As a manager of a mixed environment I would love to have a single place to go to for all the SQL. It would be great way to introduce my DB2 guy's to the rest of the databases and introduce code management. 

Please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please, please

**Comment by mahoneyl** [comment]
This would be a very useful tool for my team if we could use it with our DB2 database.

**Comment by alanrenmsft** [comment]
Thank you for your feedback! This feature is currently out of scope, and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.

**Comment by timothydilbert** [comment]
I think this should be reopened.
