### ISSUE TITLE
AsyncServerTree - Dragging tree items expands connection nodes as they're dragged over

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11886]
- Azure Data Studio Version:

Steps to Reproduce:

1. Place a server inside a server group.
2. Drag and drop the server out of the test group to remove it from the group.

Expected - Should be able to move a server out of a group by dragging out

Actual - Not possible now, and other servers that are hovered on while dragging, get connected to.

**Comment by Charles-Gagnon** [comment]
From your description I believe this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/11874. 

I'm going to update it to refer to the dragging connection issue instead since that's a separate thing.
