### ISSUE TITLE
Connection Dialog - Saved Connection group isn't updated

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11887]
- Azure Data Studio Version:

Steps to Reproduce:

1. Add a connection to a group.
2. Open Connection Dialog to see the Saved Connections.

Expected - Connection should be updated inside the Connection Dialog
Actual - Connection Dialog still shows the connection out of the group

**Comment by kburtram** [comment]
I couldn't repro on the latest build.  All the groups and connections appeared as expected in the Save Connections folder.  Please reactive if the issue is still impacting your use case.
