### ISSUE TITLE
Extensions: Marketplace extension page disable button doesn't do anything

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11885]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open the Extensions view to see installed extensions.
2. Go to the page of one of the installed extensions and click on Diable.

Expected - Either Disable button shouldn't exist in built-in extensions' pages or disable should actually disable the extension
Actual - Nothing happens

![Screen Shot 2020-08-20 at 10 03 39 AM](https://user-images.githubusercontent.com/6411451/90802680-71e10700-e2cc-11ea-8bd1-c6d41510b7db.png)

**Comment by alanrenmsft** [comment]
I will compare with VSCode and see whether we are doing it differently

**Comment by alanrenmsft** [comment]
I just tried this on latest insider and RC builds, the enable/disable feature is working as expected. are you still seeing the issue? can you provide a gif to show your operations?
