### ISSUE TITLE
Connection Dialog - Horizontal scrollbar shown in Saved Connections Tab

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11884]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open Saved Connections Tab in Connection Dialog.

Expected - No horizontal scrollbar since there's not a server name that long in the list
Actual -

![Screen Shot 2020-08-20 at 9 49 56 AM](https://user-images.githubusercontent.com/6411451/90801334-a48a0000-e2ca-11ea-9d06-5ad103b2ce68.png)

EDIT: This issue is similar to the issue about horizontal scrollbar in the connections tree when setting "horizontal scrolling" to true.

**Comment by abist** [comment]
Left an edit about clearer repro

**Comment by kburtram** [comment]
This doesn't appear to be an issue since the Connection Dialog UX was redesigned.  Currently the Browse Saved Connection view  does not show a horizontal scrollbar for me.

![image](https://user-images.githubusercontent.com/599935/129836443-853bfe24-efeb-4a52-afeb-bbc2995a4e8c.png)
