### ISSUE TITLE
AsyncServerTree - Horizontal scrollbar in connections tree

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11895]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open User Preferences and turn "Horizontal Scrolling" to true in workbench settings.

Expected - Object Explorer tree should behave like it did earlier or show the horizontal bar only when necessary.

Actual - A horizontal scrollbar is shown no matter what. It cannot be used to drag sideways either.

![Screen Shot 2020-08-20 at 2 40 33 PM](https://user-images.githubusercontent.com/6411451/90828760-65bc7000-e2f3-11ea-9d43-29c23d07bf1b.png)

**Comment by kburtram** [comment]
Closing as low impact issue.  If the Horizontal Scrollbar is explicitly set it doesn't seem a big deal for it to be visible all the time.  Most of the time this setting will be false.
