### ISSUE TITLE
Create Firewall Rule dialog shows account list empty even through accounts are registered

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#11899]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Create Firewall Rule dialog with accounts registered

Expected: Accounts shown in picker

Actual: No accounts shown in picker, but tenant shows content.  Note, this doesn't reproduce consistently.

![image](https://user-images.githubusercontent.com/599935/90834062-38c18a80-e2fe-11ea-8f36-b66db19cfb92.png)

![image](https://user-images.githubusercontent.com/599935/90834180-7b836280-e2fe-11ea-97d9-b8a54420342e.png)

![image](https://user-images.githubusercontent.com/599935/90834113-5131a500-e2fe-11ea-99a0-ae5a97baa77d.png)

**Comment by alanrenmsft** [comment]
tested with insider and RC build, I am not able to reproduce the issue anymore. @kburtram are you still seeing it?

**Comment by alanrenmsft** [comment]
I am moving this out out Sep release.

**Comment by kburtram** [comment]
@alanrenmsft I'll double-check and close the issue if this no longer repros.  Thanks!

**Comment by kburtram** [comment]
Closing older issue without recent repro reports.
