### ISSUE TITLE
Query Editor not showing correctly

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#11890]
Issue Type: <b>Bug</b>

Query editor is not showing the command bar when opening a sql file.
![image](https://user-images.githubusercontent.com/4324725/90815098-fc326680-e2de-11ea-93de-1476578cd515.png)

This was caused by #11750

Azure Data Studio version: azuredatastudio Dev 1.22.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (14.18GB free)|
|Process Argv|. --disable-background-networking --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-breakpad --disable-client-side-phishing-detection --disable-default-apps --disable-dev-shm-usage --disable-renderer-backgrounding --disable-sync --metrics-recording-only --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data --remote-debugging-port=9222|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cssuh** [comment]
I am seeing this as well on the latest insiders build
