### ISSUE TITLE
Connection Dialog: Recent Connections tab unindented

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11891]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open Connection Dialog.

Expected - Recent Connections should be indented as earlier.

Actual - 

Before:
![Screen Shot 2020-08-20 at 12 22 52 PM](https://user-images.githubusercontent.com/6411451/90815681-ed987f00-e2df-11ea-8bec-bd756587a765.png)

After:
![Screen Shot 2020-08-20 at 12 21 13 PM](https://user-images.githubusercontent.com/6411451/90815643-d78abe80-e2df-11ea-8893-ae1685e08fa0.png)

**Comment by Charles-Gagnon** [comment]
@abist I think you're missing a screenshot? Or could you explain further? I'm not seeing what issue you're referring to - the old tree wasn't indented either. 

Old Tree :

![image](https://user-images.githubusercontent.com/28519865/90816238-cb533100-e2e0-11ea-896b-dee6435ae938.png)

![image](https://user-images.githubusercontent.com/28519865/90816217-c1313280-e2e0-11ea-99c5-b0cf9fd69fae.png)

**Comment by abist** [comment]
Sorry if it wasn't clear, I meant the Tab Title `Recent Connections` right at the top is indented towards left and is the left-most thing in the dialog.

**Comment by Charles-Gagnon** [comment]
Ahhhh, ok @anthonydresser this is probably related to your changes for the Azure view I imagine?

**Comment by abist** [comment]
Reopening until the fix is in for release.
