### ISSUE TITLE
data controller notebook not getting generated

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#11909]
- Azure Data Studio Version:

Steps to Reproduce:

1. Run through the Deploy Azure Arc data controller wizard and provide all the required values
2. Click on Script to Notebook

Expecting to see the notebook.
However, its stuck at a partially generated notebook.
screenshot below:

![image](https://user-images.githubusercontent.com/43253513/90913404-16c51800-e391-11ea-8a03-a9187a3ac8d9.png)

**Comment by Charles-Gagnon** [comment]
@dnethi It works fine for me. Can you confirm :

- You're using the latest insiders version
- `%USERPROFILE%\.azuredatastudio-insiders\extensions\microsoft.arc-0.3.0\notebooks\arcDeployment\deploy.arc.control.plane.ipynb` exists

Are there any errors in the console after it attempts to open?

**Comment by Charles-Gagnon** [comment]
@ranasaria Please follow up with @dnethi to see if this issue is still happening.

**Comment by ranasaria** [comment]
This happens once a while and is not a consistent repro. The workaround is to try again. While not ideal, this random issue has been seen for a while and happens only in corner cases. It is something that we will take a closer look later. Lowering priority and pushing to backlog.

**Comment by dnethi** [comment]
Closing for now as I havent seen it happen again..
