### ISSUE TITLE
BDC Deployment Wizard - Greyed Out Next Button

### ISSUE THREAD

**Issue by mwdarab** [microsoft/azuredatastudio#11929]
Running ADS on Windows 10 Surface Book 2.

**ADS version**:
Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Steps to reproduce**:

1. Open ADS and click on Connections ellipses
2. Click on New Deployment...
3. Choose the "SQL Server Big Data Cluster" tile, and keep defaults (New Azure Kubernetes Service Cluster), Accept Privacy policy, and click Select
4. Choose either "deployment configuration profile" (aks-dev-test or aka-dev-test-ha), click Next
5. Click Next to go to Step 3 (Cluster settings)
6. Type in passwords, then change "authentication mode" to Active Directory. Then change back to "Basic". The "Next" button is grayed out. You have to control X the admin username or cluster name and paste it back in, in order for the Next button to highlight itself back to blue.

If I click the drop down and choose "Active Directory" then decide to go back to "Basic"....the Next button should not grey out.

**Comment by Charles-Gagnon** [comment]
This no longer repros for me, was likely fixed by many of the other fixes we've done in this area. Please reopen if you still see this!
