### ISSUE TITLE
SQL Ops Studio for OSX to Support 10.11 El-Capitan

### ISSUE THREAD

**Issue by farizzed** [microsoft/azuredatastudio#1192]
As an old Macbook user and my company use SQL Server, I would like to propose SQL Ops Studio to support OSX 10.11 El-Capitan.

- SQL Operations Studio Version:
Version 0.27.3 (0.27.3)

Steps to Reproduce:
1. Opens SQL Operations Studio.
2. The application gives me warning that my os (10.11) doesn't support SQL Ops.
3. I cannot use SQL Ops.
4. Please gives support on osx 10.11.
5. Thank you!

**Comment by ellwoods** [comment]
I'm in the same position

**Comment by kburtram** [comment]
I'm going to close this issue out as upstream since .Net Core is not planning to add support for El Capitan in a future release.  Thanks for reporting this issue.
