### ISSUE TITLE
SQL Server Import: Modify Columns step is ignoring my edits on Azure Data Studio for macOS.

### ISSUE THREAD

**Issue by MarcusOy** [microsoft/azuredatastudio#11949]
My issue is explained well with this old comment:

> Modify Columns step is ignoring my edits on Azure Data Studio for macOS. After I choose to continue, the table is created with the suggested types instead my edits. That's causing an "Error inserting data into table" because of one of my columns is VARCHAR(72), and PROSE is setting VARCHAR(50)

_Originally posted by @williamthiago in https://github.com/microsoft/azuredatastudio/issues/2090#issuecomment-509819216_

A few details about my environment:
- Version: 1.21.0
- Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
- Date: 2020-08-11T20:51:42.148Z (1 wk ago)
- VS Code: 1.48.0
- Electron: 7.3.2
- Chrome: 78.0.3904.130
- Node.js: 12.8.1
- V8: 7.8.279.23-electron.0
- OS: Darwin x64 19.4.0 (MacOS 10.15.4 Catalina)

Steps to Reproduce:

1. Install SQL Server Import extension.
2. Connect to db server (I am connecting to an AzureSql database)
3. Run Flat File Import: Import Wizard from command palette
4. Fill in necessary fields in Step 1
5. Preview Data in Step 2
6. Modify data types for 1 or more columns (for example: `tinyint` -> `int`, `nvarchar(50)` -> `nvarchar(200)`) in Step 3
7. Receive an error that complains about data truncation. In my example, I've changed the data type of the `Winner` column from `bit` to `nvarchar(20)`, but the error says that a string cannot be converted to a boolean; one can infer that the importer ignored my manual correction. See example below.

![Screen Shot 2020-08-24 at 10 28 15 PM](https://user-images.githubusercontent.com/16263577/91115842-bbc14880-e650-11ea-9613-66f698b88327.png)

**Comment by MarcusOy** [comment]
Contributers, please change label from `Area - Edit Data` to `Area - SQL Import`.

**Comment by aasimkhan30** [comment]
@MarcusOy what is your import extension version? 

You can go to marketplace and check your extension version. 

![image](https://user-images.githubusercontent.com/6816294/92147692-54359680-edd0-11ea-8a2a-2a5259d00128.png)

**Comment by MarcusOy** [comment]
@aasimkhan30 0.19.0
