### ISSUE TITLE
Font color mismatch in Welcome Page

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11956]
The blue color for `Show All` seems deeper than the blue for every other link.

![118230244_314192463158219_320447093935554761_n](https://user-images.githubusercontent.com/6411451/91218453-ebfafc80-e6cd-11ea-8269-042a62d3b603.png)

**Comment by kburtram** [comment]
This appears to be fixed on the current build.

![image](https://user-images.githubusercontent.com/599935/129837384-20a9feaa-284d-4605-b09f-1896313e12da.png)
