### ISSUE TITLE
Deployment password field for data controller cannot have password pasted

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#11965]
- Azure Data Studio Version: v1.22.0-insiders

Steps to Reproduce:

1. Launch deployment wizard.
2. Choose data controller option.
3. Click next, attempt to paste into password field.

This happened on a Mac as FYI. Let's double check to see if this is specific to password field or not.

From Azure Arc bug bash.

**Comment by Charles-Gagnon** [comment]
@yualan Who was running into this issue? We can't seem to repro it - did you make sure to verify that they did actually have text in the clipboard for pasting?
