### ISSUE TITLE
Datatype in CSV wizard won't be accepted

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#11968]
Azure Data Studio Version: 1.21.0 / data virt extension: 1.8.0

Steps to Reproduce:

1. Run the virtualize CSV wizard
2. Change the datatype of a string column from nvarchar(50) to char(10) from the drop down
3. Change it manually to char(2)
4. Generate the Script
5. The script will have char(10)

**Comment by bweissman** [comment]
@Charles-Gagnon sorry - I think I got another one for you :)

**Comment by Charles-Gagnon** [comment]
Good find @bweissman ! I've confirmed the repro and will look into this.

It does work if you press enter while in the input box as a short-term workaround if you need this functionality.
