### ISSUE TITLE
Add button for New and Open Database Project

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#11979]
It would be nice to have the button actions for `New` and `Open` projects similar to other trees.

![Screen Shot 2020-08-26 at 11 01 02 PM](https://user-images.githubusercontent.com/6411451/91396887-3379a980-e7f0-11ea-8b91-531e6fbd7355.png)

**Comment by udeeshagautam** [comment]
Question to Shiproom : Since this is minimal change and PR available - can we take this?

**Comment by udeeshagautam** [comment]
Merged.
