### ISSUE TITLE
workbench.action.query.shortcut1 error message - cannot read property 'shortcut1' of undefined

### ISSUE THREAD

**Issue by vaidymohan** [microsoft/azuredatastudio#11978]
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch Azure Data Studio.
2. Connect to a database server.
3. Open a new query window. 
4. Write a query (for instance; SELECT * FROM AuditLog).
5. Select the table name and use the shortcut that would mimic "sp_help". In my case, I've set it up to F1.
6. When I use the keyboard shortcut, I get the error message "Cannot read property 'shortcut1' of undefined"

Screenshots attached for your reference.
<img width="853" alt="Screen Shot 2020-08-27 at 09 43 03" src="https://user-images.githubusercontent.com/39476127/91373750-bd099580-e849-11ea-9f18-4845e64803f2.png">
<img width="2227" alt="Screen Shot 2020-08-27 at 09 44 01" src="https://user-images.githubusercontent.com/39476127/91373815-dca0be00-e849-11ea-9c3c-13b4f2f4d116.png">

**Comment by Charles-Gagnon** [comment]
@vaidymohan This should be fixed in insiders by https://github.com/microsoft/azuredatastudio/issues/11749 - if you have a chance could you try it out there and see if you're still seeing it?

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
