### ISSUE TITLE
Arc data controller deployment notebook has incorrect command 'kubectl get pods -A'

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#11985]
- Azure Data Studio Version:

Steps to Reproduce:

1.  Go through the Arc data controller deployment wizard
2.  Run the notebook.
3.  In the output, you will see that it tells you to run something like this:  C:\ProgramData\chocolatey\bin\kubectl.exe get pods -A

But this will give  you an error:
C:\ProgramData\chocolatey\bin\kubectl.exe get pods -A

I think this -A thing was deprecated in kubectl or something.  It should be --all-namespaces instead.

A further optimization would be to actually pass the user-specified namespace as a parameter so that it is filtered to just the data controlller namespace.  In a real world customer deployument getting all pods across all namespaces could yield thousands of rows. :)

kubectl get pod -n <user's namespace>

would be much, much better.

**Comment by Charles-Gagnon** [comment]
Good feedback - I'll update it to use the namespace instead

**Comment by Charles-Gagnon** [comment]
@ranasaria I'll work on this - you focus on your other stuff.
