### ISSUE TITLE
SP: Go to Definition

### ISSUE THREAD

**Issue by Oleg26Dev** [microsoft/azuredatastudio#120]
- SQL Operations Studio Version:
0.23.6
x64

Steps to Reproduce:

exec dbo.usp_clean

I select 'dbo.usp_clean' or 'usp_clean' , then right-click->Peek definition or Go to definition. In any case I receive the script:

CREATE SCHEMA [dbo]
GO

When I do in the explorer tree 'Script as Create' then I receive the message
'No script was returned when scripting as Create on object StoredProcedure'

**Comment by stanac** [comment]
probably duplicate of #110

**Comment by llali** [comment]
Fixed in sqltoolservice v1.2.0-alpha.39. It will be in the next release

**Comment by mrlife** [comment]
@llali Hi, is this supposed to be fixed in 0.25.3? I'm still seeing in that release.

**Comment by llali** [comment]
@mrlife I reopen the issue to investigate more. I thought it should be fixed but maybe it was a different issue than the one I fixed.

**Comment by abist** [comment]
Hey @Oleg26Dev , I can't seem to repro this issue. Is the stored procedure dbo.usp_clean being completed by intellisense when you type it in? Can you give more details about how you see this behavior?

**Comment by mrlife** [comment]
I am experiencing this on Mac, and the intellisense works, but “go to definition” and “peek definition” just give what the OP mentions:

CREATE SCHEMA [dbo]
GO

**Comment by kburtram** [comment]
I verified this is working on `1.8.0` with the following snippet ` EXEC [sys].[sp_help]`.
