### ISSUE TITLE
azdata-cli installation errors with 1603

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12006]
azdata extension supports the installation/upgrade of azdata-cli. However, on windows it ends up with an error: 
1603. 

**Output Channel:**
_...
...
Downloading (85.42 / 85.42 MB)
Download finished
Executing command "msiexec /qn /i C:\Users\arvran\AppData\Local\Temp\azdata-cli-20.0.1.msi"
Unexpected exit code from command :  (1603)_

**Popup Error notification:**
_Error upgrading azdata : Unexpected exit code from command :  (1603)_

**There are 2 issues here:**

1. The user does not know what went wrong so the logging needs to be made richer.
2. After a manual repro and after harvesting the logs the core issue was the following:

```
MSI (s) (98:6C) [14:32:29:923]: Product: Azure Data CLI -- Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine. Log on as administrator and then retry this installation.

Error 1925. You do not have sufficient privileges to complete this installation for all users of the machine. Log on as administrator and then retry this installation.
Action ended 14:32:29: InstallExecute. Return value 3.
Action ended 14:32:29: INSTALL. Return value 3.
```
[msi.azdata.20.0.1.log](https://github.com/microsoft/azuredatastudio/files/5144364/msi.azdata.20.0.1.log)

**Comment by Charles-Gagnon** [comment]
Fixed
