### ISSUE TITLE
[Azure Arc] Missing Properties, and incorrect Grafana/Kibana links on MIAA dashboard 

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12016]
- Azure Data Studio Version: 1.22.0-insiders

Steps to Reproduce:

1. Connect to data controller
2. Right-click a MIAA instance
3. Click a grafana or Kibana link

Also would be good to double check the server properties.

![image](https://user-images.githubusercontent.com/30873802/91685668-d9d6ef00-eb0f-11ea-8991-bfa6b544153d.png)

**Comment by vin-yu** [comment]
For the kibana link, there does not appear to be a property of 'instance_name' but there is a 'custom_resource_name'

So I think the query should look something like this:
https://20.153.67.165:30777/kibana/app/kibana#/discover?_a=(query:(language:kuery,query:'kubernetes_namespace:"arc"  and **custom_resource_name**:"miaademo3"'))

**Comment by vin-yu** [comment]
There are other properties at the top such as resource group, data controller, compute, etc. not filled in.
