### ISSUE TITLE
azdata notification shows on every start on dev builds

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#12031]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open ADS on dev build

Expected: No notifications everytime

Actual: azdata keeps prompting for install.  There should be option "Don't show again" or some other way to disable.

![image](https://user-images.githubusercontent.com/599935/91773089-ed7b6780-eb9a-11ea-958d-88f85f65155e.png)

**Comment by kburtram** [comment]
BTW, why is azdata extension loading on startup?  Perhaps the activation event should be scoped to an action that requires azdata.

**Comment by Charles-Gagnon** [comment]
@kburtram Yeah - so the interesting thing here is that by itself the extension isn't really doing anything. It's basically just there for providing the API to other extensions to use. And currently there isn't an "only load when another extension that depends on this activates" event so we have to do this (from what I've seen at least).
