### ISSUE TITLE
Convert Records to Maps

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#12047]
I used a few `Record` objects around the database projects code that, in retrospect, should've been `Map`s for flexibility and cleanliness of code.

**Comment by udeeshagautam** [comment]
@Benjin this seems open for a while - you think we should take it or this is worth closing for now and revisit when we are doing something closer to that code.

**Comment by kisantia** [comment]
closing since a lot of this will change with the sql project xml parsing moving to DacFx
