### ISSUE TITLE
Freezes when expanding tables and database contains lots of tables

### ISSUE THREAD

**Issue by mmgagnon** [microsoft/azuredatastudio#1205]
- SQL Operations Studio Version: sqlops 0.27.3 (9474415ad68b5a70e8b851698c8c836664a9d5b5, 2018-03-27T05:25:59.481Z)
- OS Version: Windows_NT x64 6.3.9600
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
server-report|Mic|0.1.0

---

Steps to Reproduce:

1. Get a database with a huge number of tables (tested with a database containing around 50 000 tables)
2. Expand the "Tables" folder under "Servers"
3. The application freezes and becomes unresponsive, and must be killed

Reproduces without extensions: Yes/No

**Comment by cheenamalhotra** [comment]
With recent improvements, ADS doesn't freeze if Object Explorer is slow to fetch data. Operations can be performed in parallel with 'Parallel Message Processing' enabled by default. Closing as resolved.
