### ISSUE TITLE
azure view is missing

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#12052]
this is what i am seeing on latest insider:
![image](https://user-images.githubusercontent.com/13777222/91810191-55a16c00-ebe2-11ea-983f-e698993835e4.png)

expected:
![image](https://user-images.githubusercontent.com/13777222/91810262-71a50d80-ebe2-11ea-8501-7c7b2b907612.png)

**Comment by anthonydresser** [comment]
This is intentially, it is in the connection dialog now as a tab.
