### ISSUE TITLE
Reusing CSS files between components

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#12071]
![image](https://user-images.githubusercontent.com/1465785/91915345-238a1b80-ec6f-11ea-83e5-be2547ffc3ef.png)

The card component and the radio component are sharing the same CSS file. This breaks the component standard and adds a heavy tax on future modifications to specific components.

Let's make sure we're not doing this and we can use eslint rules to prevent this in the future too.

**Comment by kburtram** [comment]
Closing engineering-level issues to prioritize customer-facing issues.
