### ISSUE TITLE
[Azure Arc] Improve accept EULA in all the Azure Arc deployment wizards

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12077]
We need to remove the prompt or persist checkbox across deployment wizards. This came up during deployment refactor discussion with team as well. There is definite interest to make this experience more seamless.

**Comment by ranasaria** [comment]
Can you share more details on what the desired experience would be? We can do it over a call and I can transcribe our conclusions. Also check out the latest, because I did update the 'accept Eula' experience yesterday.

**Comment by Charles-Gagnon** [comment]
@ranasaria The biggest thing here is that we should be seeing if the user already accepted the azdata EULA and if they have then have this checkbox be filled. 

And really we should just remove this checkbox completely and instead have the EULA prompt appear like we do for the azdata commands if it isn't accepted.

**Comment by ranasaria** [comment]
So this is only for arc dc create, miaa and postgress instance create and not for other older resource deployment scenarios right?

Arvind.

________________________________

**Comment by ranasaria** [comment]
There is still small followup work remaining to improve the experience so reopening this.
