### ISSUE TITLE
[Azure Arc] Going to SQL manage dashboard pops open the connection panel

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12079]
When attempting to open a MIAA dashboard, connection dialog pops open.

**Comment by Charles-Gagnon** [comment]
This isn't random - we need a SQL connection to query for certain things like databases.

But the design here isn't great - we should make it clearer what the dialog is for (likely for now just having another custom connection dialog to prompt the user for username/password)

**Comment by Charles-Gagnon** [comment]
@chlafreniere This is something you/someone else could potentially work on next week as well. Basically I want to replace the call to openConnectionDialog here https://github.com/microsoft/azuredatastudio/blob/main/extensions/arc/src/models/miaaModel.ts#L170 with a much simpler dialog that's basically a copy of https://github.com/microsoft/azuredatastudio/blob/main/extensions/arc/src/ui/dialogs/connectControllerDialog.ts#L1.

We should still keep the connection profile and connect using that azdata.connection.connect once we have the information. 

I can likely knock this out the week I get back as well if needed.
