### ISSUE TITLE
[Azure Arc] Validation check for deployment fields

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12082]
azdata is adding support by September release to check validation for fields like min/max cores, memory, etc. We should include this logic in deployment flows.

[AB#3778](https://mssqltools.visualstudio.com/dea8be32-0532-4a8f-a2f4-89271d8b1cc5/_workitems/edit/3778)

**Comment by ranasaria** [comment]
The scope of this work is the validation of data entry within the fields. Higher-level semantic validations should be addressed as part of #12728 or a new issue.

**Comment by ranasaria** [comment]
Here are the validations that we need to do/ensure for cores and memory fields for MIAA and Postgres.

![AzdataMemoryCoreValidations](https://user-images.githubusercontent.com/41588310/95117719-e4336c80-06fd-11eb-9daf-fcd80fd14b41.jpg)
