### ISSUE TITLE
[Azure Arc] Add additional Postgres deployment fields

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12081]
- Add username

**Comment by bergeron** [comment]
The username can't be configured.  It's always 'postgres'.  But we'll add the other fields that are missing.

**Comment by Charles-Gagnon** [comment]
I'm thinking for this it might be useful to have a non-editable input box with the name so the user can clearly see what it's going to be. (and then in the future I can see us allowing editing that value so it would be a simple matter to just make the box editable when that happens)
