### ISSUE TITLE
Question: which respository is the master for 'Operations and Support Jupyter Book - SQL Server 2019 Big Data Clusters'?

### ISSUE THREAD

**Issue by mi-hol** [microsoft/azuredatastudio#12099]
**Is your feature request related to a problem? Please describe.**
I wanted to correct a typo in the official documentation, but can't find the affected file neither here nor in MicrosoftDocs/sql-docs repo, hence I created https://github.com/MicrosoftDocs/sql-docs/issues/5405 but get pointed back to Azure Data Studio

**Describe the solution or feature you'd like**
A clear statement in readme.md on how to address bugs in official Microsoft Jupyter Books distributed via Azure Data Studio

**Describe alternatives you've considered**
First checked MicrosoftDocs/sql-docs repo then this repo

**Comment by chlafreniere** [comment]
Hey @barbaravaldez can you work with folks from the BDC team on where users are supposed to file issues? I love the idea of a readme file that's clear.

**Comment by barbaravaldez** [comment]
Hi @mi-hol after discussing this with the team. The right place for submitting issues regarding the SQL Server 2019 BDC Guide should be https://github.com/microsoft/tigertoolbox.

**Comment by barbaravaldez** [comment]
@chlafreniere I'll work with @MikeRayMSFT to add a note in the BDC docs.

**Comment by chlafreniere** [comment]
Awesome. Thank you @barbaravaldez

**Comment by mi-hol** [comment]
moved to https://github.com/microsoft/tigertoolbox/issues/226
