### ISSUE TITLE
Welcome page shows unexpected text on the top screen on Insiders 1.22.0

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12093]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: d8dcc9085731df0ff6bb9dc336c0a76e6e1a0dd0
Date: 2020-09-02T05:57:25.600Z
VS Code: 1.48.0
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Install latest insiders.
2. Launch `> Help: Welcome` if it's not yet opened.

![image](https://user-images.githubusercontent.com/6405919/92048075-a8426b80-ed3b-11ea-896c-ab42241af774.png)

**Comment by kburtram** [comment]
This doesn't repro for me in the latest insiders or RC1 build
