### ISSUE TITLE
Manage dashboard window crashes when tab switching

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#12106]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open the Manage Dashboard
2. Switch to different tab, hiding the dashboard
3. Switch back to dashboard

Expected: Dashboard shows

Actual: Dashboard crashes with below error.

```
Unable to open 'adssql:WideWorldImporters': Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'..
```

**Comment by kburtram** [comment]
@alanrenmsft @anthonydresser not sure if this is a dashboard bug or something that came in with the latest merge.  Could one of you please take a look and figure out where to route or how to fix?

**Comment by alanrenmsft** [comment]
@kburtram ack! working on it
