### ISSUE TITLE
Extension tags don't reflow properly

### ISSUE THREAD

**Issue by hannahqin** [microsoft/azuredatastudio#12113]
Version: 1.21.0
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:51:42.148Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

On smaller screen resolutions, when the extension manager is expanded and you're viewing an extension with a long name, the Extension identifier and Preview tags overflow outside of the window.

![92162989-dc736600-ede7-11ea-9c60-35d9f29cb9b5](https://user-images.githubusercontent.com/9788775/92163574-c87c3400-ede8-11ea-9cfb-c6bbd1c87004.png)

**Comment by alanrenmsft** [comment]
vscode behaves the same way, no-wrapping probably is by design, but I do think there should be a horizontal scrollbar. please open an issue in vscode repository.
