### ISSUE TITLE
Deploy MIAA via DC dashboard fails

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12111]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to an existing data controller
2. Use the "+ New Instance" button on the controller dashboard to initiate a new MIAA deployment
3. After filling out the details, click Deploy. 

The deployment fails and launches the Notebook. 
Running this notebook as-is via "Run cells" succeeds.

**Comment by Charles-Gagnon** [comment]
@ranasaria Can you help @dnethi here with the workaround that you and Sean had to verify it's the same Python issue?

**Comment by ranasaria** [comment]
Dinkar, can you add the deployment output channel log? Some screenshots of the failure that you see would be helpful? 
Also, answer the following questions as it helps us understand if what you are seeing is the same as another known issue.
Is the machine where you are testing this 'domain' joined?
Is it the user account local or domain account? 
Is this on physical hardware or a VM? 
Is this a newly commissioned machine?

**Comment by dnethi** [comment]
Sure..

In- line..


Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by ranasaria** [comment]
This is an issue with the execution of a notebook using azdata. Filed a bug against the platform team here:
https://sqlhelsinki.visualstudio.com/aris/_workitems/edit/17282/.

Closing this.
