### ISSUE TITLE
Run a query, switch to server report and the App stop run query´s

### ISSUE THREAD

**Issue by bigleka** [microsoft/azuredatastudio#1211]
- SQL Operations Studio Version:
Version 0.28.4-insider
Commit 3d6fb7a8fa8e941306109f69bc094e307b9ff8c2
Date 2018-04-23T05:43:47.587Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Steps to Reproduce:

Open a new query and run any select.
Open the SERVER REPORTS, click to run query on "Backup Growth Trend", he open a new query and then wen I click on Run or try F5 he open the connect screen and don´t connect in any server.
Go Back on the SQLQuery1 the result panel show the columns and lines of the result but with no results, when try run the query again the App don´t do anything.

**Comment by kburtram** [comment]
@AbbiePetcht any idea what's happening here?

**Comment by AbbiePetcht** [comment]
@bigleka I can't repro the issue

This is the steps I did:
1. Open new query and run "select * from sys.tables"
2. Open dashboard and select Server Reports
3. Right click to run query on "Backup Growth Trend" - This will open new query and run the query. I don't have to click on Run or F5

I tried to rerun both my select statement and Backup Growth Trend query. They ran successfully.

**Comment by bigleka** [comment]
I got the same error with the release 29.1 and 29.2 and now I create a Dump file with the moment of the error, do you want analyze ?

**Comment by kburtram** [comment]
I'm going to close out this older issue that we couldn't repro.  Please let me know if you're still experiencing this issue.
