### ISSUE TITLE
SandDance doesn't load in Insiders build 1.22.0-insider

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12114]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: 887ce88100b95940762eaa7bdb35556a5f92873c
Date: 2020-09-03T06:09:59.695Z
VS Code: 1.48.0
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Install SandDance extension.
2. Connect to a database, and run a query. 
3. Click on the Visualizer icon next to the result set.
You should see a tab open but with no details. 
![image](https://user-images.githubusercontent.com/6405919/92167427-375c8b80-edef-11ea-9560-d85be8ae42e0.png)

When I run this on the stable version:
![image](https://user-images.githubusercontent.com/6405919/92168191-72f75580-edef-11ea-94ef-e3e9239a8bf4.png)

Version: 1.21.0 (user setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kburtram** [comment]
@anthonydresser I was seeing some webview related errors when I tried to load Sanddance.  Could you check if this something with the extension APIs?  Or some other issue.  Thanks!

**Comment by anthonydresser** [comment]
Looks like this was fixed as part of a vscode merge yesterday, should be in the next insiders build.

**Comment by anthonydresser** [comment]
Which is out now.

**Comment by MsSQLGirl** [comment]
Thanks! Confirmed that this is fixed.
My environment:
Version: 1.22.0-insider
Commit: 4cc3a3f7885db47330c23abe99e7bb4c9c01f384
Date: 2020-09-04T05:46:28.727Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-45-generic
