### ISSUE TITLE
'Ignore Recommendation' button on extension details looks like plain text

### ISSUE THREAD

**Issue by hannahqin** [microsoft/azuredatastudio#12115]
Version: 1.21.0
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:51:42.148Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.6.0

See screenshot below. I believe this used to be styled as a blue button?

<img width="727" alt="Screen Shot 2020-09-03 at 2 54 29 PM" src="https://user-images.githubusercontent.com/9788775/92177588-a6d57980-edf5-11ea-999b-d6cda6d442e6.png">

**Comment by chlafreniere** [comment]
also reproes in vscode

**Comment by kisantia** [comment]
There's no longer an option to ignore the recommendations in ADS and vscode: 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/ea9e6579-f754-468f-bc5b-3c78ef7d9be2)
