### ISSUE TITLE
Blank SQLPlan?

### ISSUE THREAD

**Issue by geoffreywiseman** [microsoft/azuredatastudio#12123]
- Azure Data Studio Version: 1.21.0

Steps to Reproduce:

1. Open a *.sqlplan file
2. Azure studio opens with a "Query Plan" tab
3. Query Plan tab is empty

**Comment by geoffreywiseman** [comment]
I'd offer more information, but I don't really have any more information -- but happy to try things if you have suggestions.

**Comment by abist** [comment]
Seems like it's being tracked here - https://github.com/microsoft/azuredatastudio/issues/12176. Feel free to join the discussion there! Closing this issue as duplicate.

**Comment by geoffreywiseman** [comment]
Thanks -- I didn't find that issue, but it sounds like it could well be the same issue, I agree.
