### ISSUE TITLE
Can't connect to SQL Server database in Azure

### ISSUE THREAD

**Issue by rohansp** [microsoft/azuredatastudio#12131]
- Azure Data Studio Version: 1.21.0 (user setup)

Steps to Reproduce:

1.Set up new connection in Azure Data Studio to connect to SQL Server database in Azure.

2. Authentication Type = SQL Login

3. Entered server name ,username and password.

Connection Error
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 0 - A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.)

**Comment by Charles-Gagnon** [comment]
@rohansp Are you able to connect to the server through other means - such as sqlcmd or SSMS? The error indicates there's something else blocking you from connecting here.

**Comment by rohansp** [comment]
Yes, I am able to connect with SSMS.
