### ISSUE TITLE
jupyter notebook SOP063 fails on Windows

### ISSUE THREAD

**Issue by mi-hol** [microsoft/azuredatastudio#12138]
- Azure Data Studio Version:
1.21.0
Steps to Reproduce:
on Microsoft Windows 10.0.18362.1049

1. Go to 'Provided Books'
2. Open Book 'Operations and Support Jupyter Book - SQL Server 2019 Big Data Clusters'
3. Go to Notebook 'SOP063'
4. Select 'Run all'
get error
```
START: curl -L https://aka.ms/azdata-msi -o C:\Users\user\AppData\Local\Temp\azdata-cli.msi @ 2020-09-04 16:38:26 (2020-09-04 14:38:26 UTC)
       using: C:\WINDOWS\system32\curl.EXE (Windows 10 on AMD64)
       cwd: c:\Program Files\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\install
 C:\Python38\lib\subprocess.py:844: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stdout = io.open(c2pread, 'rb', bufsize)
C:\Python38\lib\subprocess.py:849: RuntimeWarning: line buffering (buffering=1) isn't supported in binary mode, the default buffer size will be used
  self.stderr = io.open(errread, 'rb', bufsize)
 STDERR:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
STDERR:                                  Dload  Upload   Total   Spent    Left  Speed
STDERR: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
STDERR: 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file 
STDERR: Warning: C:UsersuserAppDataLocalTempazdata-cli.msi: Permission denied
STDERR: 
  0 85.4M    0  1572    0     0   1572      0 15:49:36 --:--:-- 15:49:36  9192
STDERR: curl: (23) Failed writing body (0 != 1572)
 An exception has occurred, use %tb to see the full traceback.

SystemExit: Shell command:

	curl -L https://aka.ms/azdata-msi -o C:\Users\mholzer2\AppData\Local\Temp\azdata-cli.msi (0:00:00s elapsed)

returned non-zero exit code: 23.
```

Note: running the Shell command with pwsh run as Administrator succeeds without error.
from STDERR: Warning: C:UsersuserAppDataLocalTempazdata-cli.msi I'd assume the path delimiters '\\' are incorrect.
using '\\\\' might be the fix.

**Comment by mi-hol** [comment]
update with ADS 1.22.0
it fails one command later with 
START: cmd /c C:\Users\user\AppData\Local\Temp\azdata-cli.msi /passive @ 2020-09-04 17:06:11 (2020-09-04 15:06:11 UTC)
       using: C:\WINDOWS\system32\cmd.EXE (Windows 10 on AMD64)
       cwd: c:\Users\user\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\install
An exception has occurred, use %tb to see the full traceback.

SystemExit: Shell command:

	cmd /c C:\Users\mholzer2\AppData\Local\Temp\azdata-cli.msi /passive (0:00:12s elapsed)

returned non-zero exit code: 1603.

**Comment by stuartpa** [comment]
I've refactored SOP063 to use urllib (and not use curl anymore). This will be available in the upcoming CU8 version of the book

**Comment by chlafreniere** [comment]
Thanks @stuartpa. Closing this issue.
