### ISSUE TITLE
Issue Reporter is empty

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#12137]
Version: 1.21.0 (system setup)
Commit: 2413919f186f780f0193d047da3d90bb3c1e9bf6
Date: 2020-08-11T20:52:47.502Z
VS Code: 1.48.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. While trying to report a separate issue I clicked the Help\Report Issue option.
1. The Issue Reporter window appears but it is completely blank.
1. Min/max window, clicking inside, etc does nothing.

I replicated this issue on 2 different machines.

**Comment by yualan** [comment]
This also reproed on my machine on Stable and Insiders, as well as a couple other PM's. Let's investigate for September release.

**Comment by abist** [comment]
This issue occurs in packaged builds only, investigating
