### ISSUE TITLE
Finalize Arc & azdata display strings

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#12148]
- [ ] EULA prompts
- [ ] Installation prompts
- [ ] Upgrade prompts
- [ ] "SQL managed instance - Azure Arc"
- [x] "PostgreSQL Hyperscale - Azure Arc"
- [ ] Azure Data CLI instead of azdata
- [x] Preview title for Arc controller deployment

The tiles on the Deployment hub should continue to show the suffix "(preview)" while we are still in preview, though.

**Comment by uc-msft** [comment]
Please fix string in below message:

No Azure ARC controllers are currently connected. Please run the command: 'Connect to Existing Azure Arc Controller' and then try again
