### ISSUE TITLE
data controller deployment wizard changes

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12151]
- [ ] In Step 1, it says "Select from installed existing Kubernetes clusters". Change it to "Select from existing Kubernetes clusters"

- [ ] In Step 3, it says "Provide details to create Azure Arc data controller and register with Azure". We are not doing any registration in this flow. Its a separate manual step. so we need to change the title to "Provide details to create Azure Arc data controller"

**Comment by chlafreniere** [comment]
@ranasaria I'll fix this myself to take some things off of your plate.
