### ISSUE TITLE
Getting error while connecting to azure sql server.  Error: Token retrival failed with an error. Open developer tools to view the error

### ISSUE THREAD

**Issue by amanraj09** [microsoft/azuredatastudio#12165]
- Azure Data Studio Version: 1.21.0 (macos)

Steps to Reproduce:

- followed below approach when i got this error **`Token retrival failed with an error. Open developer tools to view the error`**
1. Add connection type as Microsoft SQL Server
2. Choose Authentication type as Azure Active Directory - Universal with MFA support
3. Put Database name
4 Try to connect

**I remember i started getting this issue once i changed my AAD password.**

<img width="649" alt="Screenshot 2020-09-05 at 6 03 02 PM" src="https://user-images.githubusercontent.com/6585649/92305235-1046bb00-efa3-11ea-8dde-9230ade0eb74.png">

<img width="542" alt="Screenshot 2020-09-05 at 6 03 45 PM" src="https://user-images.githubusercontent.com/6585649/92305241-19378c80-efa3-11ea-9bc0-c1be8a45f327.png">

**Comment by javiermarasco** [comment]
I noticed this today as well, it was working fine a few days ago and didn't changed anything in the SQL instances (Azure SQL Servers)

**Comment by I90Runner** [comment]
I am encountering similar issue as well.
Version Info 
Version: 1.23.0
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T22:58:36.079Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Error: 
Error: Token retrival failed with an error. Open developer tools to view the error

**Comment by gabrieljoelc** [comment]
same action and error:

Version: 1.24.0
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:35:27.682Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by achand9** [comment]
I also experienced similar issue after changing by AAD password. Is there a work around to resolve this ?

**Comment by shortall** [comment]
Same action and error
![image](https://user-images.githubusercontent.com/22685125/100992997-be371680-354c-11eb-905b-6b27eb0c5b51.png)

**Comment by gsaiz** [comment]
> 
> 
> Same action and error
> ![image](https://user-images.githubusercontent.com/22685125/100992997-be371680-354c-11eb-905b-6b27eb0c5b51.png)
> I was able to work around by clearing files from
> C:\Users\{UserNameHere}\AppData\Roaming\azuredatastudio\Azure Accounts
> Then reloading the app. On first load got a blank error notification, second load OK then could connect to server

This was the only way to fix the error for me.

**Comment by Gopinathreddy6098** [comment]
Hi All,
Good Afternoon.
I am getting below error while connecting to azure data studio from jumphost.
Token retrieval failed with an error. Open developer tools to view the error

Could you please help me on the same.

Thanks ,
Gopinath

**Comment by gregiare** [comment]
I had this same issue after changing my Azure Active Directory password. @shortall 's workaround worked for me also. This really should be fixed so the application can gracefully handle when someone changes there AAD password. I am on version 1.25.1

**Comment by Gopinathreddy6098** [comment]
Hi, 
Thanks for your response, but I'm not clear on fix.

**Comment by memblin-taurus** [comment]
This just started happening to me today, no changes to Data Studio or AAD or password etc... Clearing the connection cache as per @shortall 's answer fixed the issue and allowed me to reconnect.

**Comment by matheusdarosa** [comment]
If you are on MAC, the path to the folder containing the files that should be deleted is:

`~/Library/Application Support/azuredatastudio/Azure Accounts`

**Comment by wheezymustafa** [comment]
@matheusdarosa I'm having the same issue on my Mac, but I'm not finding any cache in the location you specified

**Comment by janitorr** [comment]
Had the same issue on:

Version: 1.25.2 (user setup)
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:52:13.492Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Deleting file from and re-authenticating helped.
C:\Users\{UserNameHere}\AppData\Roaming\azuredatastudio\Azure Accounts

**Comment by lluthus** [comment]
The same for me from yesterday evening
 Error: Token retrieval failed with an error. Open developer tools to view the error

any help ?

**Comment by memblin-taurus** [comment]
Hi @lluthus

There are two issues I've found with Azure Data Studio's implementation of Azure AD - Universal with MFA support authentication.

Token refresh failure:
--------------------
You will find that after about 2 weeks token dies and will not refresh as you would expect. No amount of trying to open a new connection will trigger the re-auth process. 

Solution: Close Azure Data Studio and delete cached token here:
C:\Users\m_emb\AppData\Roaming\azuredatastudio\Azure Accounts


HSTS localhost pinned to https:
----------------------
You may find due to development work or other applications authenticating that localhost has become pinned to HTTPS only. When Azure data studio tries to reauthenticate (it opens a browser window with localhost address over http which redirects to Microsoft auth page for you to login). This fails if localhost is pinned to https only.

To resolve load chrome, Edge or browser you are using and find HSTS settings:

Example in Chrome paste in the address bar:
chrome://net-internals/#hsts

First confirm the domain’s HSTS settings are recorded by Chrome by typing the hostname 'localhost' into the 'Query HSTS/PKP domain' section and click Query. 

If the Query box returns a result, then type the same hostname 'localhost' into the 'Delete domain security policies' section and click Delete.

Now try reconnecting in AzureData Studio.

Hope this helps save countless hours of wasted time.

**Comment by billyswitzer** [comment]
This happens every time I have to update my AD password. janitorr's fix above works.

**Comment by lehmus** [comment]
On Ubuntu, the folder path is: `/home/$USER/.config/azuredatastudio/Azure Accounts`

**Comment by schmocker** [comment]
on mac, the folder path is: ```/Users/tobias/Library/Application Support/azuredatastudio/Azure Accounts```. I closed Azure Data Studio, removed the file ```azureTokenCache_azure_publicCloud```in this folder and restarted Azure Data Studio and it worked again.

**Comment by daleche-sh** [comment]
It does be a problem. I reactive my account and then experienced the same issue.  The resolution shared by memblin-taurus works. Thank you!

**Comment by HeidiHasting** [comment]
experienced this again today, I often just switch back to SSMS if ADS starts to cause issues. This time checked and found this page, I ended up doing the delete, reauthenticating, closing and reopening and its back. Very frustrating and sad to see a bug like this that deters from using the product open for over a year.

Also not great user experience with error message to say open developer tools for error, yup and then what the users of the product might not be app developers or people who work with AAD authentication. might as well just have unknown error like SSMS.

**Comment by itsmaryann** [comment]
Still an issue with 1.33.1. The workaround works for me. Thanks to all who posted the workaround.

Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by PiotrPerak** [comment]
Will this ever be solved?

**Comment by Janneman96** [comment]
This exception did not show when I tried to connect to a database throught the "Connections (ctrl + shift + d)" menu. It just kept loading without any error message.

Only when I tried to edit the connection and tried to connect through that window, is when I got the same error.

**Comment by Janneman96** [comment]
This bug still occurred for me in version 1.34.

**Comment by matt-nordberg** [comment]
I was unable to follow the workaround above (couldn't find the specified path on mac) but found a different workaround within Azure Data Studio (v 1.34.0):
1. Click the "Accounts" (user icon) button on the bottom left
2. Remove the faulty account
3. Re-add the account, either with the "add user" icon in that pane, or by editing the connection and selecting "Add an account..." in the Account drop-down

**Comment by gregiare** [comment]
> I was unable to follow the workaround above (couldn't find the specified path on mac) but found a different workaround within Azure Data Studio (v 1.34.0):
> 
> 1. Click the "Accounts" (user icon) button on the bottom left
> 2. Remove the faulty account
> 3. Re-add the account, either with the "add user" icon in that pane, or by editing the connection and selecting "Add an account..." in the Account drop-down

This worked for me in version 1.34.0 on Windows 10.

**Comment by schmocker** [comment]
> @schmocker Thanks for your post. I'm hitting this issue + tried your fix with no luck - can't find the folder. Is it in the same location in the later Azure Data Studio builds?

@charlespickettau for me it is. (I just updated the path to be relative to your user: ~/Library/Application Support/azuredatastudio/Azure Accounts)

**Comment by philipnye** [comment]
> I was unable to follow the workaround above (couldn't find the specified path on mac) but found a different workaround within Azure Data Studio (v 1.34.0):
> 
> 1. Click the "Accounts" (user icon) button on the bottom left
> 2. Remove the faulty account
> 3. Re-add the account, either with the "add user" icon in that pane, or by editing the connection and selecting "Add an account..." in the Account drop-down

If like me you don't display the Activity Bar so can't follow the letter of @matt-nordberg's solution, another way of removing your existing account is to go via the command palette and use _Clear all saved accounts_. Then you can re-add your account as Matt says, by selecting "Add an account..." in the Account drop-down when attempting to open a fresh connection.

**Comment by alexbousquet** [comment]
I created a PowerShell script (compatible with Windows and macOS) to automatically close ADS, delete the file(s) in the `Azure Accounts` directory, then relaunch ADS:

```
# Set OS-specific variables
if($IsMacOS) {
  $app = '/Applications/Azure Data Studio.app'
  $process = Get-Process | Where-Object { $_.Path -like "$app*" }
  $token_path = '~/Library/Application Support/azuredatastudio/Azure Accounts/'
} else {
  $app = 'azuredatastudio'
  $process = Get-Process azuredatastudio
  $token_path = '~/AppData/Roaming/AzureDataStudio/Azure Accounts'
}

# Stop all running instances of Azure Data Studio
Write-Host 'Confirm you want to stop the processes found:' -ForegroundColor DarkYellow -Separator 
$process | Stop-Process -Confirm


# Remove all files from Azure Accounts directory
Write-Host 'Confirm you want to delete the token files found:' -ForegroundColor DarkYellow
Get-ChildItem $token_path | Remove-Item -Confirm


# Launch Azure Data Studio
try {
  Start-Process -FilePath $app

  Write-Host 'Done! Launching Azure Data Studio...' -ForegroundColor Cyan
}
catch {
  Write-Host 'Failed to reopen Azure Data Studio' -ForegroundColor DarkYellow
}
```

I'm gonna be adding it as a cmdlet to my local Azure module with the name `CompensateFor-AzureDataStudioInadequacies`.

**Comment by SQLvariant** [comment]
I was able to connect to Azure SQL from ADS once again using [The Workaround](https://github.com/microsoft/azuredatastudio/issues/12165#issuecomment-802673850).  On Edge browser I used edge://net-internals/#hsts and even though the Query step didn't return any results, I went ahead and did the Delete step anyways.  After that I tried connecting to one of my Azure SQL DBs and voila!

**Comment by kburtram** [comment]
We made a change to the Grant token refresh code in Feb that should help in some of the scenarios discussed in this issue (specifically password change or token expiration).  I'm seeing a notification on startup when the password is expired (and will look into removing that).  But the account is refreshing as expected in the Accounts dialog and connections are successful after updating the token.  Are you still seeing this on 1.35.1 or later build?

**Comment by alexbousquet** [comment]
@kburtram Appears to be grabbing new tokens without issue now (for me, at least).

Thank you!

**Comment by shortall** [comment]
@kburtram I haven't had this since my original instance

**Comment by kburtram** [comment]
Thanks for confirmation that this issue is not still repo'ing on the latest build!  I'll close this issue now since it's been long-running and actually has discussion of multiple related bugs.  We still have a few other active AAD bugs that we're currently working on for April and beyond, and plan a larger upgrade from ADAL to MSAL in June or Aug.  If you are still hitting issues with AAD, account management, etc.  Please add a comment to one of the other active issues or open a new issue if applicable.

**Comment by tomdecort** [comment]
> If you are on Mac, the path to the folder containing the files that should be deleted is:
> 
> `~/Library/Application Support/azuredatastudio/Azure Accounts`

Could it be that this location has changed? Can't find it on my Mac 🤷🏼

**Comment by alexbousquet** [comment]
> > If you are on Mac, the path to the folder containing the files that should be deleted is:
> > `~/Library/Application Support/azuredatastudio/Azure Accounts`
> 
> Could it be that this location has changed? Can't find it on my Mac 🤷🏼

I just updated to 1.37 and the directory/file remain:

<img width="1509" alt="Screen Shot 2022-06-29 at 6 43 42 PM" src="https://user-images.githubusercontent.com/45643/176574640-63d5ad4b-89dc-484a-86c5-437a3636103d.png">
