### ISSUE TITLE
Row Serial Numbers after 99 are clipped in Results Grid

### ISSUE THREAD

**Issue by themilinda** [microsoft/azuredatastudio#12168]
**Is your feature request related to a problem? Please describe.**
On running query having rows more than 99 in Results Grid , the row serial number is clipped 100 onwards. On double clicking the row serial number column, serial numbers are shown with all digits. It should be shown with all digits by default.

**Describe the solution or feature you'd like**
Related issue is https://github.com/microsoft/azuredatastudio/issues/172. But seems it excludes this point. This may be a feature so that row number doesn't take lot of space. But is is helpful if complete serial number is visible. Is there any setting to turn it on or off?
![Capture](https://user-images.githubusercontent.com/66711116/92349667-6e36e800-f0f4-11ea-9929-a8d7c9ff098b.PNG)

**Comment by anthonydresser** [comment]
This is intentional, since we stream the results we don't know how big that column needs to be and it would be disruptive to users to keep resizing that column. That columns is resizeable by dragging the separator.
