### ISSUE TITLE
SQL Server Profiler Extension - make it harder to clear filter

### ISSUE THREAD

**Issue by saasaTom** [microsoft/azuredatastudio#12171]
Love the extensions - but it is to easy to accidentally clear a filter via the toolbar. 

These filters can take a while to setup and if you haven't saved them you have to redo them.

It would be nice to have either a confirmation dialogue - "Are you sure?" or only show the clear filter button under the Filter menu

**Comment by LucasWBritz** [comment]
Also I'd love to suggest that we move the 'Clear Data' to be more close to the 'Start', 'Stop', 'Pause' controls.
I've many times cleared my filters instead of clearing my data.

![image](https://user-images.githubusercontent.com/24421665/94590024-6e8e5300-025c-11eb-9bac-43f9f6d10ad9.png)

**Comment by alanrenmsft** [comment]
@saasaTom @LucasWBritz both suggestions have been implemented, you should be able to see it in tomorrow's insiders build or the next stable release.
