### ISSUE TITLE
Unable to change password when it has expired

### ISSUE THREAD

**Issue by nathan-tugwell** [microsoft/azuredatastudio#12215]
- Azure Data Studio Version: Version: 1.21.0 Mac OS 

When my sql password expires- it tells me that my password has expired there is no option to change the password

Steps to Reproduce:

1. let password expire
2. error will appear telling you password has expired
3. no options appears 
![Screenshot 2020-09-10 at 15 16 27](https://user-images.githubusercontent.com/29708117/92743589-9b93c800-f378-11ea-92c4-b9b6a9226b71.png)

**Comment by Charles-Gagnon** [comment]
You'll need to log in with another administrator account and change the password of the account in question - this isn't something we can fix from the client side that I know of.

**Comment by rick-syncbak** [comment]
I'm still seeing this in version 1.48.0 in 2024. Every time I create a new user who uses Azure Data Studio with "User must change password at next login" , we have to have them use a desktop w/ SSMS to change their password. Did https://github.com/microsoft/azuredatastudio/pull/21295 not really fix it, or was 21295 never included in a release?
