### ISSUE TITLE
I see the arc instances listed twice

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12227]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install the Azure Arc extension
2. Connect to a controller that has 1 or more data instances
I see the instances listed twice.
![image](https://user-images.githubusercontent.com/43253513/92807917-22907280-f370-11ea-984a-70b25cf943f5.png)

![image](https://user-images.githubusercontent.com/43253513/92807944-291eea00-f370-11ea-9007-e316c827c236.png)

**Comment by Charles-Gagnon** [comment]
@dnethi Are you still seeing this? I've never seen this issue myself...

**Comment by dnethi** [comment]
Here..

I just hit the Refresh button a couple of times, and it doubles my instances.

[cid:image001.png@01D68B43.84A23160]

Also note, its not displaying the name of the instances.

[cid:image003.png@01D68B43.84C34DF0]

FWIW, I uninstalled my ADS insiders build this morning, and reinstalled. Still seeing above issues.


Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by Charles-Gagnon** [comment]
@dnethi I'm still not seeing the images you're attempting to attach. Could you please ensure those are embedded properly?

and as usual please include the logs from the azdata output channel.

**Comment by dnethi** [comment]
Here..

I just hit the Refresh button a couple of times, and it doubles my instances.

[cid:image001.png@01D68B44.51C72150]

Also note, its not displaying the name of the instances.

[cid:image003.png@01D68B44.51F0A250]

FWIW, I uninstalled my ADS insiders build this morning, and reinstalled. Still seeing above issues.


Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by Charles-Gagnon** [comment]
@dnethi Could you please make sure you're using Github to post updates - responding via e-mail breaks the image links.

When you say you "hit refresh multiple times" - are you able to click refresh again before it's finished refreshing? The button should be disabled once you click refresh until the refresh finishes....

And I still would like to see the azdata logs if you're able to repro this consistently.
