### ISSUE TITLE
DB Project tree seems to be throwing an error

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#12223]
- Azure Data Studio Version:

Steps to Reproduce:

1. Seeing the following in Dev build of Db Projects, didnt notice any issue with its working so far

![image](https://user-images.githubusercontent.com/46980425/92787128-af7e0080-f35d-11ea-9b46-78b5e79e7a3f.png)

**Comment by kisantia** [comment]
side effect from this is that the catch for that error removes the project from the list of open projects, so if you try to add a table or anything to the project after it's loaded, then the project goes away when the tree refreshes
