### ISSUE TITLE
Error when Switching Connections

### ISSUE THREAD

**Issue by ZohairTharani** [microsoft/azuredatastudio#12244]
We receive the following error whenever switching connections in Azure Data Studio as detailed below

![image](https://user-images.githubusercontent.com/26558994/92968358-d0168b00-f42f-11ea-87b5-7663ed9d527d.png)

We have to reset the Connection Details every time this occurs. Why does this happen? Is there a fix in line for this? 

- Azure Data Studio Version: 1.21.0

Steps to Reproduce:

1. Not sure. No pattern necessarily noticed and occurs more often than it should

**Comment by Charles-Gagnon** [comment]
@ZohairTharani Could you provide some more information? 

1. How exactly are you "changing the connection" - is this from the query editor or somewhere else?
1. Are you able to connect to the connection you're switching to normally? (through the Servers connection tree?)
1. What do you mean by "reset the connection details"?
