### ISSUE TITLE
some awaits on pendingOperations may be unnecessary in cacheManager

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12253]
- Azure Data Studio Version:

Steps to Reproduce:

Code Review

There are probably a few excessive awaits in CacheManager (extensions/resource-deployment/src/helpers/cacheManager.ts). They should be double-checked, thoroughly tested, and removed if not needed.

**Comment by kburtram** [comment]
Closing engineering-focused tasks to focus on customer-facing issues.  Please open an issue for the customer bug impacted by this issue.  Thanks!
