### ISSUE TITLE
Notebook Kernel is not consistent for Kusto

### ISSUE THREAD

**Issue by JustinMDotNet** [microsoft/azuredatastudio#12255]
- Azure Data Studio Version: 1.22.0-insider

Steps to Reproduce:

1. Have Kusto Connection in object explorer
2. Select new notebook on Kusto Cluster
3. Notice the Kernel is set to Kusto
4. Select new notebook on the same Kusto Cluster (or different Kusto Cluster)
5. Notice the kernel is set to SQL
6. Repeat steps 4 and 5 and notice the same result

**Comment by VasuBhog** [comment]
The PR above addresses the issue and fixes the impact for users opening multiple notebooks via a Kusto connection, therefore ensuring that all _New Notebook_ experiences for Kusto will open with **Kusto** as the selected Kernel whenever connected to a Kusto connection (shown below).
![image](https://user-images.githubusercontent.com/23587151/93137406-07d93900-f6a3-11ea-963c-d3018e5f0eb1.png)
