### ISSUE TITLE
MIAA missing in Azure view

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12260]
- Azure Data Studio Version: 1.22.0-insiders

Steps to Reproduce:

1. Download Azure Arc extension
2. Open Azure View and Sign in to Azure
3. MIAA instances are not listed.

According to UC, MIAA instances were listed here before. Not sure if regression from platform, partner team, or specific to our extension.

**Comment by Charles-Gagnon** [comment]
@uc-msft @yualan Can you confirm that you still see the folder - just not the instances within it?

![image](https://user-images.githubusercontent.com/28519865/93123201-971f2600-f67c-11ea-9a76-bd91ae8779fb.png)
