### ISSUE TITLE
Database projects build failure - dacfx dependency

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#12269]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: e16d3ed827161e6f071750370e9eea8837e3ac9b
Date: 2020-09-14T05:43:50.093Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Import database (AdventureWorksLT will suffice) to project
2. Build project command
3. Build fails with error message
>stdout: 
    stdout: c:\Users\drskwier\.azuredatastudio-insiders\extensions\microsoft.sql-database-projects-0.1.2\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): Build error : Could not load file or assembly 'System.IO.Packaging, Version=4.0.5.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [c:\Users\drskwier\Documents\DatabaseProjects\DatabaseProjectAdventureWorks2019\DatabaseProjectAdventureWorks2019.sqlproj]

![image](https://user-images.githubusercontent.com/12227241/93132916-42cf7280-f68b-11ea-8c7c-d512366bf2c3.png)

**Comment by kisantia** [comment]
fixed by #12336

**Comment by sqlchick** [comment]
The latest version of the Insiders Build still has this problem. Meaning I can't get a successful build of the DB project, thus I can't do a schema comparison. However...since the SQL Database Projects extension is now released in the Sept 2020 release of Azure Data Studio, we no longer need the Insiders Build for this particular purpose.

**Comment by dzsquared** [comment]
@sqlchick Can I confirm the version of the insiders build that you are on and seeing the build problem?  We certainly want it to be working in both!

Is it:
> Version: 1.23.0-insider (user setup)
> Commit: c26963e848a135de3d44868435ddbec156da13d0
> Date: 2020-09-23T05:41:16.160Z

**Comment by sqlchick** [comment]
Version: 1.23.0-insider (user setup)
Commit: c26963e848a135de3d44868435ddbec156da13d0
Date: 2020-09-23T05:41:16.160Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by kisantia** [comment]
thanks for catching this! The fix is in the stable release, but we forgot to update the insiders extensions gallery with the newer vsix too.

**Comment by kisantia** [comment]
The insiders gallery is updated and should be fixed in the insiders build tomorrow
