### ISSUE TITLE
Deployment wizards should follow Azure subscription filtering

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#12261]
When a user filters an Azure subscription in Azure extension, it should be reflected in other features like the deployment wizard for example.

This ask specifically comes from Azure Arc, but could also come from Azure workstream.

[AB#3779](https://mssqltools.visualstudio.com/dea8be32-0532-4a8f-a2f4-89271d8b1cc5/_workitems/edit/3779)

**Comment by kenvanhyning** [comment]
Yes - this should act like the portal.  The subscription filter should be accessible in context where it makes sense but the filter should be a global config that all features respect.

**Comment by ranasaria** [comment]
My plan is to use the filtered subscriptions from the Azure navigation tree in the deployment wizards. However, as a first cut, I do not plan to provide users the ability to change this filtering from the deployment wizard. If the subscription that the user intends to use in not in the filtered list, then the user will have to go back to that Azure navigation tree to alter the filtered subscription list. 

I will follow this up with more conveniences as needed especially as user feedback that we get meanwhile will be especially useful.

**Comment by Charles-Gagnon** [comment]
Yup, that seems like a reasonable way to start

**Comment by ranasaria** [comment]
So the first cut is now checked in.

**Comment by ranasaria** [comment]
I think we should close this issue and open a new one(s) for any other improvements that we want to do here.

**Comment by ranasaria** [comment]
Created issue #12726 for any follow-up work needed here. Closing this.
