### ISSUE TITLE
Arc data controller dashboard not displaying all the properties

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12279]
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch ADS and connect to a Arc data controller
2. Launch the Arc data controller dashboard

most of the properties are empty.

![image](https://user-images.githubusercontent.com/43253513/93144004-e590ec80-f69d-11ea-8b52-6463ea304f6f.png)

**Comment by Charles-Gagnon** [comment]
Please provide : 

1. Console logs
2. azdata output channel logs
3. Whether this happens every single time or is intermittent

(these things are good to include whenever you submit any bugs related to Arc stuff in general for future reference)

**Comment by dnethi** [comment]
1.  Where is the console log file?
  2.  Azdata output:


Searching for existing azdata installation...
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" --version"
stdout : 20.1.1

SQL Server 2019 (15.0.4063)

Python (Windows) 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 02:47:15) [MSC v.1900 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\python.exe'
Found existing azdata installation of version (v20.1.1) at path:C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" login -e https://52.229.229.196:30080 -u arcadmin --output json"
stdout : {
  "logs": [],
  "result": null,
  "stderr": [],
  "stdout": [
    "Logged in successfully to `https://52.229.229.196:30080` in namespace `arcsept`. Setting active context to `arcsept`."
  ]
}
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" arc dc config show --output json"
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" arc dc endpoint list --output json"
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" arc postgres server list --output json"
Executing command ""C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" arc sql mi list --output json"
stdout : {
  "logs": [],
  "result": [],
  "stderr": [],
  "stdout": []
}
stdout : {
  "logs": [],
  "result": null,
  "stderr": [],
  "stdout": [
    "No data controller exists in namespace `arcsept`."
  ]
}
stdout : {
  "logs": [],
  "result": [],
  "stderr": [],
  "stdout": []
}
stdout : {
  "logs": [],
  "result": [
    {
      "description": "Management Proxy",
      "endpoint": "https://52.229.240.42:30777",
      "name": "mgmtproxy",
      "protocol": "https"
    },
    {
      "description": "Log Search Dashboard",
      "endpoint": "https://52.229.240.42:30777/kibana",
      "name": "logsui",
      "protocol": "https"
    },
    {
      "description": "Metrics Dashboard",
      "endpoint": "https://52.229.240.42:30777/grafana",
      "name": "metricsui",
      "protocol": "https"
    },
    {
      "description": "Cluster Management Service",
      "endpoint": "https://52.229.229.196:30080",
      "name": "controller",
      "protocol": "https"
    }
  ],
  "stderr": [],
  "stdout": []
}






  1.  Happens in the latest build. All the time.



[cid:image002.png@01D68AC1.59F618F0]


Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by Charles-Gagnon** [comment]
Console logs are the developer console logs (Help -> Toggle Developer Tools -> Console)

Is this controller right? -> `https://52.229.229.196:30080 in namespace 'arcsept'. `

From the logs you attached : `No data controller exists in namespace 'arcsept'`

Can you run azdata commands such as `azdata dc config show` on the command line and see if you get any output?

**Comment by dnethi** [comment]
I did some cleanup on my end – deleted old dc, created new one, re-created the config file etc..
So right now, I have a fresh dc with one MIAA instance..

The dashboard is loading the values for dc, but Arc Resources list looks messed up..

[cid:image002.png@01D68AC5.0CA1F7A0]



Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by Charles-Gagnon** [comment]
@dnethi The image isn't embedded correctly.

And could you provide the same info as earlier? (mostly the azdata logs in this case I think)

**Comment by alanrenmsft** [comment]
@Charles-Gagnon is this a September release issue?

**Comment by Charles-Gagnon** [comment]
I'm closing this since you said that the properties are showing correctly now. Let me know if you see this again.
