### ISSUE TITLE
Query Editor Results Panel Blank after Maximizing Table

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#12273]
On RC build:

- Open query editor
- Type in 2 statements such as:
```
select 1
select 1
```
- Click Maximize action on either of the resulting tables
- Results view is blank:
![image](https://user-images.githubusercontent.com/40371649/93137799-e7a17e00-f692-11ea-91ff-761dba683d12.png)

**Comment by chlafreniere** [comment]
I've preemptively put this into the September release, @kburtram. Assuming other folks can repro, this seems like it would meet the bar.

**Comment by abist** [comment]
I could repro this issue, I can take a look.
