### ISSUE TITLE
WYSIWYG: Tables with Captions Break Table Rendering

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#12270]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: e16d3ed827161e6f071750370e9eea8837e3ac9b
Date: 2020-09-14T05:43:50.093Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
Steps to Reproduce:

1. Go to [this link](https://docs.microsoft.com/en-us/learn/modules/secure-and-isolate-with-nsg-and-service-endpoints/5-exercise-vnet-service-endpoints) and copy starting from the top of the body of the page ("Exercise - Restrict access to Azure Storage...") all the way through the header labeled "Configure storage account and file share".  Paste this into a text cell of a Notebook.  You should notice that everything was copied properly except for the markdown table titled "ADD RULES TO THE NETWORK SECURITY GROUP".

If you attempt to copy only the table by itself, you will probably be successful.  The issue presents itself when you are trying to copy a larger range of elements off of a web page.

**Comment by chlafreniere** [comment]
This is what it currently looks like:
![image](https://user-images.githubusercontent.com/40371649/93144492-f4c46a00-f69e-11ea-929b-bf4526947a80.png)
