### ISSUE TITLE
Notebook Text Cells: First 2 Characters Not Selectable in Split/Markdown Modes

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#12284]
Cannot select first 2 characters with mouse when text cell is in split or markdown view mode

**Comment by halerankin** [comment]
Below is a screen shot of the markdown in editor with default position that no longer conflicts with three overlapping elements. Of the three, `margin-view-overlays` is shown. This, along with Its sibling `glyph-margin` and its parent div with class `margin` are three elements with a width assigned from code not from CSS.

In short, the solution was to remove a custom position I had added to CSS months ago.

![image](https://user-images.githubusercontent.com/12279161/93252642-a076c400-f74a-11ea-98c6-f5ae661f85bd.png)
