### ISSUE TITLE
Feedback button on ADS doesnt work

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12280]
- Azure Data Studio Version:

Steps to Reproduce:

1. Launch ADS
2. Use the feedback button to create an issue
3. Click the "Preview on github" button

I get a "not found" error

**Comment by Charles-Gagnon** [comment]
@dnethi What version is this on? Can you give more information - for example where is this "not found" error appearing?

**Comment by dnethi** [comment]
[cid:image003.png@01D68AC1.0BC6AFA0]


[cid:image002.jpg@01D68AC1.0BBD87E0]




Dinakar Nethi
Dinakar.Nethi@microsoft.com<mailto:Dinakar.Nethi@microsoft.com> | Senior Program Manager | Azure Arc - Data |

**Comment by chlafreniere** [comment]
@dnethi we fixed a very similar issue to this. if you can still repro, plz reopen
