### ISSUE TITLE
Update the title of the Dusky deployment tile

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#12302]
- Azure Data Studio Version:

The title of the Dusky deployment tile in ADS is incorrect:
![image](https://user-images.githubusercontent.com/22226386/93242151-33a7fd80-f73b-11ea-9e20-6c84591db03a.png)

It should be:
PostgreSQL Hyperscale server groups - Azure Arc (Preview)

**Comment by bergeron** [comment]
Being addressed in https://github.com/microsoft/azuredatastudio/pull/12187
