### ISSUE TITLE
Adding a cell resizes the environment zoom level

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#12328]
- Azure Data Studio Version: 1.22 Insider

Adding a text cell resizes the environment zoom level

![Resize](https://user-images.githubusercontent.com/8250560/93246050-0b230200-f741-11ea-8faf-6b221348d88f.gif)

**Comment by chlafreniere** [comment]
Looks like the same is true for code cells as well. Great bug. Thank you!

**Comment by SQLvariant** [comment]
I can repro with Insider's build 🙁
But so far, only with SQL Notebooks, not PowerShell (thankfully!)

**Comment by chlafreniere** [comment]
Not a regression, not a September release blocker.
