### ISSUE TITLE
Azure Arc data controller doesnt display Arc resource names

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#12333]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install the Azure Arc extension
2. Launch ADs
3. Connect to a data controller that has arc resources deployed, such as MIAA or PG
4. The dashboard doesnt display the name column for the arc resources.

![image](https://user-images.githubusercontent.com/43253513/93282665-c2406d00-f783-11ea-822b-cab32a73a282.png)

**Comment by chlafreniere** [comment]
Dupe of #12304.
