### ISSUE TITLE
NameError: name 'sql_instance_port' is not defined

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12341]
1. On the latest code from main branch, do a miaa instance add deployment. Be sure to leave SQL instance port field blank.
The deployment fails. upon running the notebook generated manually the following error is observed:
**_NameError: name 'sql_instance_port' is not defined_**

To gather more information all environment variables were printed. Here is the dump of relevant variables. I am also attaching the generated notebook.
 'AZDATA_NB_VAR_ARC_CONTROLLER': 'arc-cp1 (https://52.186.34.255:30080)',
 'AZDATA_NB_VAR_CONTROLLER_ENDPOINT': 'https://52.186.34.255:30080',
 'AZDATA_NB_VAR_CONTROLLER_PASSWORD': '********',
 'AZDATA_NB_VAR_CONTROLLER_USERNAME': 'arcadmin',
 'AZDATA_NB_VAR_SQL_CORES_LIMIT': '8',
 'AZDATA_NB_VAR_SQL_CORES_REQUEST': '4',
 'AZDATA_NB_VAR_SQL_INSTANCE_NAME': 'sqlinstance1',
 'AZDATA_NB_VAR_SQL_INSTANCE_PORT': '',
 'AZDATA_NB_VAR_SQL_MEMORY_LIMIT': '8',
 'AZDATA_NB_VAR_SQL_MEMORY_REQUEST': '16',
 'AZDATA_NB_VAR_SQL_PASSWORD': '********',
 'AZDATA_NB_VAR_SQL_STORAGE_CLASS_DATA': 'default',
 'AZDATA_NB_VAR_SQL_STORAGE_CLASS_LOGS': 'default',
 'AZDATA_NB_VAR_SQL_USERNAME': 'sa'

[deploy-20200916021055.ipynb.zip](https://github.com/microsoft/azuredatastudio/files/5229909/deploy-20200916021055.ipynb.zip)

**Comment by Charles-Gagnon** [comment]
@ranasaria I was able to deploy successfully and even tried manually running the Notebook you gave me and still wasn't able to repro the issue. 

Can you provide any further context here? Are you sure that you ran the cell that defines those variables?

```
sql_instance_port = os.environ.get("AZDATA_NB_VAR_SQL_INSTANCE_PORT")
sql_instance_cores_request = os.environ.get("AZDATA_NB_VAR_SQL_CORES_REQUEST")
sql_instance_cores_limit = os.environ.get("AZDATA_NB_VAR_SQL_CORES_LIMIT")
sql_instance_memory_request = os.environ.get("AZDATA_NB_VAR_SQL_MEMORY_REQUEST")
sql_instance_memory_limit = os.environ.get("AZDATA_NB_VAR_SQL_MEMORY_LIMIT")
```

**Comment by chlafreniere** [comment]
I only observed this when I didn't run the first cell in the notebook. @ranasaria can you confirm?

**Comment by Charles-Gagnon** [comment]
@ranasaria I'm closing this since we haven't had a repro. Reopen if necessary.
