### ISSUE TITLE
[Public Preview BB] - Data Controller Deployment Wizard to Provide Image Tag Option

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#12349]
- Azure Data Studio Version:
Name: Azure Arc
Id: microsoft.arc
Description: Provides deployment and management capabilities for Azure Arc
Version: 0.4.0
Publisher: Microsoft

Version: 1.22.0-rc1 (user setup)
Commit: 403ff6cfec2a0673bfbdb0a0a57eb9b6af023fab
Date: 2020-09-16T01:51:31.696Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:
it always assumes the specific image tag and tries to download the image; i am morphing the image tag here as public preview is not out yet and i don't want to show the bits version.

13m         Warning   Failed             pod/bootstrapper-kzcq9    spec.containers{bootstrapper}   kubelet, aks-nodepool1-19803852-vmss000000   Failed to pull image "azurearcdata.azurecr.io/azure-arc-data/arc-bootstrapper:private-xxxx": [rpc error: code = Unknown desc = Error response from daemon: Get https://azurearcdata.azurecr.io/v2/azure-arc-data/arc-bootstrapper/manifests/private-xxxx: unauthorized: Application not registered with AAD., rpc error: code = Unknown desc = Error response from daemon: Get https://azurearcdata.azurecr.io/v2/azure-arc-data/arc-bootstrapper/manifests/private-xxxx-new: unauthorized: authentication required, visit https://aka.ms/acr/authorization for more information.]   15m          4       bootstrapper-kzcq9.16353246ed450830
13m         Warning   Failed             pod/bootstrapper-kzcq9    spec.containers{bootstrapper}   kubelet, aks-nodepool1-19803852-vmss000000   Error: ErrImagePull

**Comment by Charles-Gagnon** [comment]
Talked with PMs - not needed for public preview but we should look into enabling this to be set for dev/test purposes.

**Comment by Charles-Gagnon** [comment]
Closing this since it isn't something we plan on working on currently
