### ISSUE TITLE
Disable upgrade existing button if no databases

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#12356]
The deploy settings page should default to new database if there aren't any databases and the upgrade existing database radio button should be disabled.
<img width="899" alt="Screen Shot 2020-09-16 at 11 14 03 AM" src="https://user-images.githubusercontent.com/31145923/93376088-f2345280-f80d-11ea-87d6-ddccfa3a4e45.png">

**Comment by SrivatsanVasudevan** [comment]
If no one has started work on this, can I go ahead and start working on this issue?

**Comment by kisantia** [comment]
@SrivatsanVasudevan sure go for it! :)
