### ISSUE TITLE
Spaces in path doesn't retain working directory in Windows

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12357]
Issue Type: <b>Bug</b>

Open a notebook from "OneDrive - Microsoft" directory then the current directory is set for some reason to %userprofile% directory so if you have OS commands referencing files with relative path they will fail. This behavior is different for same notebook opened from a local folder or networked drive.

Repro steps:
On Windows, create python notebook in a OneDrive-Microsoft folder with cell “!cd”. Open the folder, and execute the cell – output should show the ondrive folder instead of the userprofile folder.

Now, try the same on Mac or with networked folder in Windows and the behavior is as expected - current directory is the directory where the notebook resides.

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (f2709c7100e25f114794cf78774a7af6bc68f57e, 2020-09-16T09:28:35.849Z)
OS version: Windows_NT x64 10.0.20211

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (15.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.4.0
azdata|Mic|0.2.0

</details>

**Comment by chlafreniere** [comment]
@barbaravaldez can you look here at the behavior between 1.21 (August release) and the RC build?

**Comment by barbaravaldez** [comment]
I was able to repro.
@chlafreniere it looks like both the August release and the latest RC build have the same issue.
