### ISSUE TITLE
central management servers

### ISSUE THREAD

**Issue by siprav2688** [microsoft/azuredatastudio#12353]
- Azure Data Studio Version:

Steps to Reproduce:

1.

**Comment by siprav2688** [comment]
I am not able to execute queries on all the servers that I added in server group using central management servers extension. It is not giving the option of new query for the server group. So having this extension means we should be able to execute particular query on all the servers that we have added in server group.

**Comment by siprav2688** [comment]
The links provided is not the answer I am looking for :(

**Comment by kburtram** [comment]
It looks like the basic CMS functionality is working as far as I can tell.  You should be able to run queries by right-clicking on a server and selecting New Query.  Please let us know if you're still impacted by this issue.

![image](https://user-images.githubusercontent.com/599935/130505033-406f71c8-4f8f-4e84-8b50-4c9c510ecd6e.png)
