### ISSUE TITLE
Remove Port Option for MIAA Deploy

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#12369]
During MIAA deploy, port option will be removed in a PR that will be merged in soon.

We need to remove this option from deploy wizards + notebook.

**Comment by Charles-Gagnon** [comment]
@chlafreniere So we can close https://github.com/microsoft/azuredatastudio/issues/12341 then right?

**Comment by chlafreniere** [comment]
@Charles-Gagnon I don't know. The same pattern exists for the other parameters that were added, so removing that parameter may just push the error down to the next line (if that makes any sense).

**Comment by Charles-Gagnon** [comment]
@chlafreniere Yeah that's fair. I can't repro it though and the notebook looks fine to me so I'm not sure there's an actual bug here. Following up with Arvind on that.

**Comment by chlafreniere** [comment]
@Charles-Gagnon ack
