### ISSUE TITLE
Arc data controller deployment wizard doesn't allow dc namespace / name with "-"

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12367]
- Azure Data Studio Version:

Steps to Reproduce:

1. Invoke Azure Arc data controller deployment wizard
2. Type "-" in the namespace or dc name

Expected Behavior:

Name with "-" should be accepted

Actual Behavior:

There are some errors on this page, click 'Show Details' to view the errors.
========================
Data controller namespace (lower case letters, digits and - only)
Data controller name (lower case letters, digits and - only)

**Comment by Charles-Gagnon** [comment]
@uc-msft What name are you trying to use? I can use a name with - just fine as long as it doesn't start or end with one (per the spec https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names) :

```
contain at most 63 characters
contain only lowercase alphanumeric characters or '-'
start with an alphanumeric character
end with an alphanumeric character
```

**Comment by uc-msft** [comment]
azure-arc-data

**Comment by Charles-Gagnon** [comment]
@uc-msft I'm closing this since I was able to successfully start deployment with the name given. Let me know if you're still seeing this issue even after updating to the latest version of the extensions.

Note though that azdata recently added a 13-character length limit to names so that name given isn't valid anyways. I'll be adding a check for that in ADS as well.

**Comment by uc-msft** [comment]
There is no 13-character limit for namespace or dc name in azdata. Now, I see why the string "azure-arc-data" fails for me - it is 14 characters long. I use below azdata command just fine to create data controller (have always done that):

export arcns=azure-arc-data
azdata arc dc create -n $arcns-dc -ns $arcns -s $SUB_ID -g $RG -l eastus --path $configpath --connectivity-mode indirect
