### ISSUE TITLE
Make property getters `semVersion` and `path` in AzdataTool.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12373]
Just make these property getters `semVersion` and `path`. 

(and even if you were to keep these as functions then don't use anonymous functions like this - it's just annoying to read.
```
public function getSemVersion(): SemVer {
...
```
is much better for class level functions.

_Originally posted by @Charles-Gagnon in https://github.com/microsoft/azuredatastudio/pull/12292#discussion_r488781368_

**Comment by Charles-Gagnon** [comment]
Minor improvement - not worth tracking in an issue
