### ISSUE TITLE
Notebook - Kusto new cell execution seems to update previous cell when using print

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12376]
- Azure Data Studio Version:
Version: 1.22.0-insider (user setup)
Commit: 7e76f8cb2078290d765fc3b46c2a7209850db2a8
Date: 2020-09-16T05:43:11.572Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Connect to help.kusto.windows.net using your AAD account. 
2. On Connections viewlet, right click on Samples DBD and choose New Notebook. 
3. Write the following code on the first code cell and run it.
```print strcat("Database in scope: ", current_database())```
This should output the database name.
4. Write the following code on the second code cell and run it.
```StormEvents | take 10```

Actual:
You should notice that the first Code cell's output (print_0) is updated with other values (may be from the first column of the second code cell's output?)
![NotebookKustoNewCellIssue](https://user-images.githubusercontent.com/6405919/93396380-6847b200-f82c-11ea-9bfd-27923347223e.gif)

Expected:
First code cell's output should not be changed by the subsequent code cell output.

**Comment by MsSQLGirl** [comment]
@gupta1 , @VasuBhog : FYI.

**Comment by chlafreniere** [comment]
@MsSQLGirl please sync with @lucyzhang929. I believe this may be related to a bug she's working on now (#12275)

**Comment by lucyzhang929** [comment]
I have a PR out addressing this issue right now (https://github.com/microsoft/azuredatastudio/pull/12363)

**Comment by MsSQLGirl** [comment]
This can be closed now. Confirmed fix in:
Version: 1.22.0-rc1 (user setup)
Commit: 681ecbd9467da3ccfcb11712cad617859081dc54
Date: 2020-09-18T18:54:37.816Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
