### ISSUE TITLE
Remove sqlmi/pg instance creation from deployment wizard when invoked from Server connections viewlet....

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12378]
Issue Type: <b>Bug</b>

Currently the instance creation can never be done from wizard when invoked from the server connections viewlet.  see isssue:

https://github.com/microsoft/azuredatastudio/issues/12377

I suggest we don't show the sqlmi/pg instance creation options in this context since user will be blocked anyway.

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (fb28b69bb0897660e38b85ffabdff79c345a8043, 2020-09-16T19:25:06.133Z)
OS version: Windows_NT x64 10.0.20215

**Comment by Charles-Gagnon** [comment]
Closing since the intention would be to fix 12377 and unblock this scenario.
