### ISSUE TITLE
Mark "Azure Arc data controller" also as preview in the new deployment wizard

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12371]
Issue Type: <b>Bug</b>

The first screen showing the Azure Arc data services deployment options doesn't show data controller also is in preview. Both managed instance & postgresql is marked as preview. We should mark data controller as preview for consistency.

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (fb28b69bb0897660e38b85ffabdff79c345a8043, 2020-09-16T19:25:06.133Z)
OS version: Windows_NT x64 10.0.20215

**Comment by Charles-Gagnon** [comment]
Added to https://github.com/microsoft/azuredatastudio/issues/12148
