### ISSUE TITLE
Arc dashboard doesn't show resources...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12380]
See screenshot.

![arc-dashboard](https://user-images.githubusercontent.com/10999577/93398778-0e95b680-f831-11ea-819c-6da9857a8508.png)

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (fb28b69bb0897660e38b85ffabdff79c345a8043, 2020-09-16T19:25:06.133Z)
OS version: Windows_NT x64 10.0.20215

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.4.0
azdata|Mic|0.2.0

</details>

**Comment by Charles-Gagnon** [comment]
Do you actually have resources deployed? I agree that we should show some text when there aren't any instances available but this makes it sound like you expect there to be instances shown.

**Comment by uc-msft** [comment]
Yes, I have many SQL & PG instances deployed. other folks had same problem so install a cluster with instances and see.

pg11-01-0            3/3     Running   0          152m
pg11hs-01-0          3/3     Running   0          153m
pg11hs-01-1          3/3     Running   0          153m
pg11hs-01-2          3/3     Running   0          153m
pg11hs-01-3          3/3     Running   0          153m
pg11hs-01-4          3/3     Running   0          153m
pg12-01-0            3/3     Running   0          154m
pg12hs-01-0          3/3     Running   0          155m
pg12hs-01-1          3/3     Running   0          155m
pg12hs-01-2          3/3     Running   0          155m
pg12hs-01-3          3/3     Running   0          155m
pg12hs-01-4          3/3     Running   0          155m
sqlmi-01-0           3/3     Running   0          158m
sqlmi-02-0           3/3     Running   0          156m

**Comment by Charles-Gagnon** [comment]
@uc-msft Are you still seeing this issue? I've never hit it myself and haven't heard of anyone who has.

If you do hit it please collect : 

1. Developer console logs (Help -> Toggle Developer Tools -> Console tab) 
2. azdata output (Output pane -> azdata)

![image](https://user-images.githubusercontent.com/28519865/93685983-1d19e300-fa68-11ea-9f59-acff68797dfa.png)

**Comment by Charles-Gagnon** [comment]
Closing this unless we can get a repro - haven't heard of anyone else hitting this.
