### ISSUE TITLE
Clicking on nodes with children in Notebook viewlet doesn't expand/collapse the node

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#12390]
Normal behavior is to collapse/expand the node.

![Capture](https://user-images.githubusercontent.com/28519865/93497438-464e3e00-f8c5-11ea-8633-34e41338d8ca.gif)

**Comment by chlafreniere** [comment]
By design, since these sections can be represented by markdown/notebooks files themselves, so we need to give users the ability to open these files.

**Comment by Charles-Gagnon** [comment]
But why wouldn't you have both? This behavior doesn't feel very natural to me as it is. Especially since if you click on the Book items in the viewlet it will expand/collapse the nodes under it. 

![Capture](https://user-images.githubusercontent.com/28519865/97590488-e6ff4580-19bb-11eb-86b4-1b961679ebb3.gif)
