### ISSUE TITLE
Connection Dialog "Recent connections" misaligned

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#12394]
It looks like the "Azure pane" preview flag didn't correctly fix all the alignment issues.  This should be a simple fit&finish fix.

![image](https://user-images.githubusercontent.com/599935/93506446-215fc800-f8d1-11ea-84f3-ca3a86adf417.png)

**Comment by kburtram** [comment]
@abist do you have time to look at this today?  Hopefully it's a pretty simple fix.

**Comment by abist** [comment]
Also tracked here - https://github.com/microsoft/azuredatastudio/issues/11891

**Comment by abist** [comment]
Will have this issue open for a PR against release branch and the other one for main.

**Comment by kburtram** [comment]
@abist thanks!  Let's use your issue.  I postponed since I thought the feature flag would resolve this issue.

**Comment by kburtram** [comment]
Issue being tracked in https://github.com/microsoft/azuredatastudio/issues/11891
