### ISSUE TITLE
Server dashboard backup widget shows old results

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1242]
SQL Operations Studio Version: April insiders build 0.28.5

Steps to Reproduce:
1. Open a server dashboard
2. Close SQL Ops Studio and reopen it
3. Open the same server dashboard again and observe that the "Last updated" time for the backup widget is from at least the first time you opened the dashboard, if not earlier

Expected behavior: The widget refreshes automatically when the dashboard is opened for the first time in a session, if not every time the dashboard is opened.

Depending on when you first opened the dashboard for the given server and when you last refreshed, the results may be very out of date, as in the below screenshot:

![Backup widget results last updated in March](https://user-images.githubusercontent.com/3758704/39204309-4cab87a2-47ac-11e8-93cc-78f4883c8481.png)

**Comment by kburtram** [comment]
Closing older issues.
