### ISSUE TITLE
Open search results in editor not showing results

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12423]
Steps to Reproduce:

1. Search a term in Notebooks View
2. When results load on the side bar, click on Open in Editor
3. Results are not loaded in the editor
![Screen Shot 2020-09-17 at 3 55 02 PM](https://user-images.githubusercontent.com/34872381/93537236-d7420b00-f8ff-11ea-95eb-18e527d57170.png)

**Comment by chlafreniere** [comment]
Not a regression. May want to disable the results editor in this scenario.
