### ISSUE TITLE
Blocker: Unable to indicate a target data controller. Field is disabled

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#12434]
- Azure Data Studio Version: RC1

Steps to Reproduce:

1. Deploy a Dusky server group
2. Try to indicate a target data controller
the field is disabled you cannot select any entry or input anything

That is a blocker for 9/22

![image](https://user-images.githubusercontent.com/22226386/93543657-fd23db80-f910-11ea-85be-4ee4b4a8f462.png)

**Comment by chlafreniere** [comment]
Dupe of #12344
