### ISSUE TITLE
Starting New Dusky Deployment wizard displays message Azure Data CLI:u.apiService.azdataApi.azdata.getSemVersion is not a function

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#12437]
- Azure Data Studio Version: RC1

Steps to Reproduce:

1. Starting new Dsuky  deployment wizard displays below message. Seems to happen systematically after installing the PG extension in ADS. Restarting ADS does not solve the issue

Azure Data CLI:u.apiService.azdataApi.azdata.getSemVersion is not a function
You will need to restart Azure Data Studio if the tools are installed manually to pick up the change. You may find additional details in 'Deployments' and 'azdata' output channels

![image](https://user-images.githubusercontent.com/22226386/93545818-4165aa80-f916-11ea-80dc-35f725557bb5.png)

**Comment by chlafreniere** [comment]
Fixed in #12292.
