### ISSUE TITLE
Latest RC1 build is giving errors about azdata CLI

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#12440]
Issue Type: <b>Bug</b>

Below error is when trying to do "New Deployment..."

Azure Data CLI:u.apiService.azdataApi.azdata.getSemVersion is not a function
You will need to restart Azure Data Studio if the tools are installed manually to pick up the change. You may find additional details in 'Deployments' and 'azdata' output channels

Output from azdata window:

eulaAccepted state on startup: true
Searching for existing Azure Data CLI installation...
Executing command: '"C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" --version'
No Azure Data CLI is available, [install the Azure Data CLI](command:azdata.install) to enable the features that require it.
stdout: 20.2.0

Build (20200917.2:arc_release_candidate)

SQL Server 2019 (15.0.4063)

Legal docs and information: https://aka.ms/eula-azdata-en

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\python.exe'
Found existing Azure Data CLI installation of version (v20.2.0) at path:C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd
Checking for latest available version of azdata
Getting text contents of resource at URL https://aka.ms/azdata/release.json
Downloading (0 / 0.00 MB)
Downloading (0.00 / 0.00 MB)
Download finished
Latest available Azure Data CLI version: 20.0.1.
Currently installed version of azdata: 20.2.0 is same or newer than any other version available
Executing command: '"C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\wbin\azdata.cmd" --version'
stdout: 20.2.0

Build (20200917.2:arc_release_candidate)

SQL Server 2019 (15.0.4063)

Legal docs and information: https://aka.ms/eula-azdata-en

Python (Windows) 3.6.8 (tags/v3.6.8:3c6b436a57, Dec 23 2018, 23:31:17) [MSC v.1916 32 bit (Intel)]

Python location 'C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\python.exe'

Azure Data Studio version: azuredatastudio-rc1 1.22.0-rc1 (7ad9da7fdaa295c1f336cff40a12580874b5febc, 2020-09-18T00:57:54.158Z)
OS version: Windows_NT x64 10.0.20215

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.4.0
azdata|Mic|0.2.0
azuredatastudio-postgresql|Mic|0.2.6

</details>

**Comment by chlafreniere** [comment]
Fixed in latest extension push.
