### ISSUE TITLE
cannot define workbench.action.query.shortcut* in settings

### ISSUE THREAD

**Issue by Remko1981** [microsoft/azuredatastudio#12451]
- Azure Data Studio Version: 1.21.0 (User setup)

It is supposedly possible to use query shortcuts as they are used in SSMS. By this i mean that you can write a query such as: 'SELECT TOP 1000 * FROM ' and then activate this query on a selection you have made. I can find the keyboard shortcuts for this behavior. And in other issues it is mentioned that it used to work in Azure data studio. But the setting is unavailable for me. 
See for instance #4605 . And [this stackoverflow discussion](https://stackoverflow.com/questions/57778865/select-query-shortcut-in-azure-data-studio-1-9-0) in which the functionality is described. 
I uninstalled all extensions and reinstalled Azure data studios but this did not help.

If anyone knows the setting to add this manualy to the JSON file i would be grateful.

**Comment by Remko1981** [comment]
I installed an older version and found out how you can add the shortcut manually to your settings. Open the all commands line with "ctrl+shift+p". Search for "Preferences: Open Settings (JSON)" . Add in the following line with the " symbols. Change the number after shortcut to change which shortcut should trigger:

"sql.query.shortcut4": "SELECT TOP 1000 * FROM "

**Comment by alanrenmsft** [comment]
@Remko1981 Is the issue resolved for you? I just tried it on latest ADS, and it works for me.
1. define the shortcut key for your shortcut. this can be done by open command palette and run command: Open Keyboard settings
1. define the query, just like you did, you can actually bring up the UI based setting editor by running the command: Open User Settings, the one you picked is editing json file directly.
1. open query editor, connect to a database then select some text and then press your shortcut key

I am going to close the issue, feel free to reopen it if you still have problem.
