### ISSUE TITLE
spurious need to upgrade azdata message pops up.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12454]
The following pop is seen once in a while in my development environment. This should never be happenning.
![image](https://user-images.githubusercontent.com/41588310/93618580-52510300-f98c-11ea-83c3-301c3e710d2c.png)

Not only is the popup incorrect when a version higher than expected is installed but the [instructions](https://github.com/microsoft/Azure-data-services-on-Azure-Arc/blob/Aug-2020/scenarios-new/001-install-client-tools.md)  link on that page seems to be stale as well.

**Comment by ranasaria** [comment]
The strings shown in this popup are not supposed to be even in use. I am just going to have to check-in the removal of those strings. This might have been some weird build issue on my machine. I am doing git clean -fxd on my machine to clean up everything to start afresh. With the removal of the unneeded string and cleanup of my machine, hopefully, will mark the end of this weird issue.

**Comment by Charles-Gagnon** [comment]
@ranasaria I'm closing this since it should be fixed with your PR. Let me know if you still see this.
