### ISSUE TITLE
Setting to choose between Recent and Saved connections

### ISSUE THREAD

**Issue by pmduda** [microsoft/azuredatastudio#1246]
Issue Type: <b>Feature Request</b>

When you open **New Query** and click **Connection** right pane opens with **Connections** and **Recent Connections** selected.

Add an option to open **Connections** pane on **Saved Connections** tab (possibly with all groups expanded?)

VS Code version: sqlops 0.28.5-insider (3b90530717fa16ae289f6b4255b8f65cb089a893, 2018-04-24T03:24:41.772Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment]
The connection dialog has been redesigned a few months ago.  Please let us know if you have suggestions on the current design.  Thanks!
