### ISSUE TITLE
Machine Learning Extension - deleting from a model table errored

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12464]
- Azure Data Studio Version:
Version: 1.22.0-rc1 (user setup)
Commit: e7798a8e324797fd0e84af15ec95e410860955c9
Date: 2020-09-18T05:26:58.087Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Import a new model from a flat file using the Import Model button. Complete the steps. 
2. Launch Import Model again. Choose the model that you just imported. Delete it.
Actual:
![image](https://user-images.githubusercontent.com/6405919/93630729-4cb0e880-f99f-11ea-95d5-3e1e70f0668c.png)

Expected:
no error.

**Comment by udeeshagautam** [comment]
Marking oct but will be fixed along with the other issue in Sept

**Comment by aasimkhan30** [comment]
Fixing the labels

**Comment by udeeshagautam** [comment]
@llali can you please test and close this one when you get a chance.

**Comment by llali** [comment]
Verified it's fixed. But found similar issue in another page. will create a seperate bug
