### ISSUE TITLE
Kusto Connection Viewlet after reload does not work

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12475]
- Azure Data Studio Version:
Version: 1.22.0-rc1 (user setup)
Commit: 681ecbd9467da3ccfcb11712cad617859081dc54
Date: 2020-09-18T18:54:37.816Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Connect to an ADX cluster. There should be a new ADX cluster connection added to the viewlet. 
2. Browse to an ADX database. 
3. Hit F1 and choose "Developer: Reload Window" 
4. When you navigate to the Connection viewlet, you should see the ADX cluster that you just added earlier. 
5. Click on it to navigate / browse the cluster / databases. 

Actual: The connection will keep spinning. 

![KustoConnectionViewletReloadIssue](https://user-images.githubusercontent.com/6405919/93647873-4847f800-f9be-11ea-88bd-77366a1b0d3c.gif)

Expected: It should just connect and show the databases. 

Workaround: delete connection and add it again every time you reload ADS window.

**Comment by MsSQLGirl** [comment]
Note: I cannot repro this for SQL connections. Tested with Azure SQL DB.

**Comment by MsSQLGirl** [comment]
@gupta1 & @JustinMDotNet - would this be part of Sep release fix?

**Comment by MsSQLGirl** [comment]
The same behavior if the Connection is disconnected and then click Refresh. Still can repro using this version:
Version: 1.23.0-insider (user setup)
Commit: f47c5dcc75506373fca35305572a0f4f8b4c63f9
Date: 2020-09-24T05:38:38.610Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Kusto extension:
~\.azuredatastudio-insiders\extensions\microsoft.kusto-0.1.0\sqltoolsservice\Windows\3.0.0-release.33

**Comment by MsSQLGirl** [comment]
Tested against Kusto 0.1.1 version on both Insiders and ADS Stable. Issue still persists. 
Version: 1.23.0-insider (user setup)
Commit: cf9754f627720f1e29693d9be1100a44c37ce010
Date: 2020-09-29T05:40:10.361Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by MsSQLGirl** [comment]
Upgrading to the recommended System Requirements seem to solve the problem.
https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15#recommended-system-requirements 

Was (not working): 
Virtual Processor: 1 or 2 
RAM: 4GB

Now (working)
Virtual Processor: 4
RAM: 8GB 

:) 

We'll likely need to revisit this to understand what's going on in the backend as part of stress testing.

**Comment by JustinMDotNet** [comment]
This issue has been resolved.
