### ISSUE TITLE
arc sqlmi deployment fails through wizard but works on notebook

### ISSUE THREAD

**Issue by vin-yu** [microsoft/azuredatastudio#12543]
- Azure Data Studio Version:
**Version: 1.22.0-rc1 (system setup)**
Commit: 95625b65c47d0ac62399a506dae00da97a223af4
Date: 2020-09-21T19:49:57.788Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.20201

Steps to Reproduce:

1. Install Azure Arc 0.4.2 and Azure Data CLI 0.2.2 extensions 
2. Connect to Arc DC 
3. Create a new instance by pressing "New Instance" on the data controller page 
4. Press - 'Managed Instance - Azure Arc'
5. Go through deployment wizard and press 'Deploy'

It will fail, and it will open the notebook, press 'run all' on Notebook, and sqlmi gets deployed. 

![image](https://user-images.githubusercontent.com/7897410/93830538-564b8200-fc25-11ea-94d6-000ceb937ea0.png)

**Comment by chlafreniere** [comment]
This is a known azdata bug.

**Comment by Charles-Gagnon** [comment]
Not applicable anymore since all deployments go through Notebooks now
