### ISSUE TITLE
ADS Version number 

### ISSUE THREAD

**Issue by Totekin** [microsoft/azuredatastudio#12540]
I have Azdata cli version 20.2.0 installed on my machine and when I open Azure data studio its giving me the following error msg. I would suggest that the system should check for lowest version number and then anything that is above work and dont return and error msg. 

<img width="1128" alt="ADSImage" src="https://user-images.githubusercontent.com/60743196/93828180-a6274a80-fc1f-11ea-8a53-5b550037b446.PNG">
<img width="831" alt="versionnumber" src="https://user-images.githubusercontent.com/60743196/93828196-ac1d2b80-fc1f-11ea-954b-b6b118ff7b97.PNG">

**Comment by chlafreniere** [comment]
@Charles-Gagnon I mentioned to @Totekin that it looks like the extension version is out of date here and to ensure that he has latest build + extension. Just assigning this to you now so that it's on your radar. Likely no issue but just FYI.

**Comment by Charles-Gagnon** [comment]
Closing this since this was with an older version on insiders. Newer builds should work as expected.
