### ISSUE TITLE
Broken link to release archive

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [microsoft/azuredatastudio#12555]
- Azure Data Studio Version: 1.21.0

Steps to Reproduce:

1. https://github.com/microsoft/azuredatastudio/releases/tag/1.22.0 

2. Linux TAR.GZ (https://go.microsoft.com/fwlink/?linkid=2142212)

3. curl -I "https://go.microsoft.com/fwlink/?linkid=2142212"
HTTP/1.1 302 Moved Temporarily
Location: https://azuredatastudio-update.azurewebsites.net/1.22.0/linux-x64-archive/stable

4. curl -I "https://azuredatastudio-update.azurewebsites.net/1.22.0/linux-x64-archive/stable"
**HTTP/1.1 404 Not Found**

**Comment by chlafreniere** [comment]
@abist can you assist please?

**Comment by Charles-Gagnon** [comment]
Fixed, apologies for that @MiRacLe-RPZ! Let us know if you're still seeing issues.

@abist Sync up with me so we can make sure this is documented correctly.
