### ISSUE TITLE
terms of use spans 2 lines on review page of dc create

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12557]
The following picture shows that on the revision page of the dc create wizard, terms of use spans two lines. This should be on one line:

![image](https://user-images.githubusercontent.com/41588310/93858741-80c32c80-fc71-11ea-9b4f-cdc7699aca45.png)

**Comment by abist** [comment]
Did you intend to take this for the hotfix?

**Comment by Charles-Gagnon** [comment]
This is in the extension so isn't something we'd consider for the hotfix anyways.
