### ISSUE TITLE
Fail to invoke/create new support from the Azure Portal

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#12552]
- Azure Data Studio Version: 
Version: 1.22.0-rc1 (user setup)
Commit: 7f3d5bac0a64c64a16df025c69f549e390a2783f
Date: 2020-09-18T20:40:16.015Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Azure Arc extension v: 0.4.3.

Steps to Reproduce:

1. deploy DC
2. deploy Dusky server group
3. manage the server group from ADS
4. select [New support request] page
5. click  [New support request] link

Nothing happens when clicking the link

![image](https://user-images.githubusercontent.com/22226386/93848487-882d0a80-fc5e-11ea-848c-afd68c6551ed.png)

**Comment by bergeron** [comment]
@TheJY Fixed here: https://github.com/microsoft/azuredatastudio/pull/12560
