### ISSUE TITLE
Kusto Auth Problems

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/azuredatastudio#12559]
- Azure Data Studio Version: 1.22.0 (nice)

Steps to Reproduce:

1. Add connection, choose fancy new Kusto option (thanks for this!!!)
2. Authentication hangs (connecting to non-default tenant)

Any help is appreciated, glad y'all are finally releasing Kusto support! Also saw this issue in the different `kusto` branches.

Steven

**Comment by stevenhurwitt** [comment]
also can i add a kusto kernel to notebooks?

**Comment by MsSQLGirl** [comment]
@stevenhurwitt  Kusto kernel is supported in notebooks. The documentation is here: https://docs.microsoft.com/sql/azure-data-studio/notebooks/notebooks-kusto-kernel

I'm adding @JustinMDotNet here to help investigate this.

**Comment by aaomidi** [comment]
@stevenhurwitt During the connection dialog phase, do you see the option to pick the specific tenant? When the user has multiple Azure tenants, we should be showing a dialog to pick the correct one associated with the service. That should probably fix this issue.

**Comment by stevenhurwitt** [comment]
hmm I get the option for my tenant `ENERX` or the default one, but it defaults to `ENERX` already. Is there a chunk of the source code I could grab for the extension to test auth? It looked like it used to have a few dependencies but has recently been rewritten?

**Comment by stevenhurwitt** [comment]
also when i check the ext host logs i'm getting this: `Error: Cannot find module 'c:\Users\steve\.azuredatastudio\extensions\microsoft.kusto-0.1.0\out\main'`

**Comment by aaomidi** [comment]
@stevenhurwitt Unfortunately the auth and connection dialog code is spread between two very separate pieces.

Hmm, can you try just switching the tenant to the other one and back to ENERX? I wonder if there is a bug with how it picks which tenant to pick.

**Comment by stevenhurwitt** [comment]
Tried that and both of them hang - is there a default tenant cluster url that i could try accessing to test that one?

**Comment by stevenhurwitt** [comment]
tried connecting to the Samples db on https://help.kusto.windows.net and got the same result. It hangs in az data studio but says it was successful in the logs.

**Comment by stevenhurwitt** [comment]
please let me know if there's any update on this! been really psyched to try out the new kusto functionality

**Comment by stevenhurwitt** [comment]
issue is resolved in the new update, thanks so much! just wondering, is there any way to execute control commands (besides `.show`) in azdatastudio?
