### ISSUE TITLE
azdata-ext fails to discover azdata-cli even though it is installed

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12561]
- Azure Data Studio Version:
Version: 1.22.0
Commit: 77b9a708df3679c26a89ba24a070b3f7a078a510
Date: 2020-09-21T18:41:27.116Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.5.0
Steps to Reproduce:

1. With ARC extension, azdata extension, and Azdata-cli already installed, sometimes (maybe, 1 in 20 times) a popup is shown that azdata-cli was not found, asking the user to install azdata-cli. Only recourse to the user is to restart ADS.

[2020-09-22T16:39:29.166Z] Searching for existing Azure Data CLI installation...
[2020-09-22T16:39:29.226Z] Could not find Azure Data CLI. Error: not found: azdata

**_Expected:_**
An installed azdata-cli should be discovered everytime.

**Comment by Charles-Gagnon** [comment]
There's nothing in the logs about a command failure or anything? We should improve that if so - knowing why it failed to "find" azdata would be a good thing to add.

**Comment by ranasaria** [comment]
Looking at the code the error that we are seeing is coming from here:
https://github.com/npm/node-which/blob/6a822d836de79f92fb3170f685a6e283fbfeff87/which.js#L10,

**Comment by ranasaria** [comment]
Looking at the code the error that we are seeing is coming from that code:
 https://github.com/npm/node-which/blob/6a822d836de79f92fb3170f685a6e283fbfeff87/which.js#L10,

**Comment by Charles-Gagnon** [comment]
Haven't seen this in a while so closing until we see it again
