### ISSUE TITLE
Kusto Notebook: query result only shows column headers, no data rows shown.

### ISSUE THREAD

**Issue by baselsalam** [microsoft/azuredatastudio#12565]
- Azure Data Studio Version: 1.22.0 (user setup)
Commit: 77b9a708df3679c26a89ba24a070b3f7a078a510
Date: 2020-09-21T20:23:13.120Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Create a notebook.
2. Add a KQL query block, with even a very simple query: print 'hello'
3. Expected: results show both a column header and data rows.
   Actual: results only show column headers.

This happens with print 'hello' as well as TableName | limit 10

**Comment by MsSQLGirl** [comment]
@JustinMDotNet & @gupta1 I can repro this.

MOre details on my environment - 






- Azure Data Studio Version:Version: 1.23.0-insider
Commit: f47c5dcc75506373fca35305572a0f4f8b4c63f9
Date: 2020-09-24T05:50:12.653Z
VS Code: 1.48.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-47-generic

Path to kusto 
~\.azuredatastudio\extensions\microsoft.kusto-0.1.0\sqltoolsservice\Windows\3.0.0-release.33

Tested on both Linux Ubuntu and Windows 10 with the same Kusto release versions.

Steps to Reproduce: (same as above)

Actual - 
No results returned.

![image](https://user-images.githubusercontent.com/6405919/94190367-d7db2400-fe60-11ea-8fd6-940e3497e1fe.png)


Expected -
Results should show. 

Previous version ~\.azuredatastudio\extensions\microsoft.kusto-0.1.0\sqltoolsservice\Windows\3.0.0-release.23 seems to work.

**Comment by baselsalam** [comment]
By the way, the repro doesn't require any columns to be of type dynamic.

It repros on this (integer column type)
`range x from 1 to 10 step 1`

as well as this (string column type)
`range x from 1 to 10 step 1 | project x=tostring(x)`

**Comment by baselsalam** [comment]
Verified fixed in v0.1.1 of the extension.

**Comment by gupta1** [comment]
Fixed in this PR https://github.com/microsoft/sqltoolsservice/pull/1084
