### ISSUE TITLE
Dark Mode Not Working

### ISSUE THREAD

**Issue by bestickley** [microsoft/azuredatastudio#12562]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open Settings and set to dark mode.
2. Expect to see dark mode but it doesn't work

See screenshot:

![image](https://user-images.githubusercontent.com/35735118/93916014-df6ec180-fcd6-11ea-88a9-cb1a8553f23c.png)

**Comment by Charles-Gagnon** [comment]
@bestickley Do you also have `Auto Detect Color Scheme` enabled and the OS in dark mode?

![image](https://user-images.githubusercontent.com/28519865/93916750-da057d00-fcbe-11ea-9907-9b23d78f249b.png)

You can also manually set the color theme by running the `Preferences: Color Theme` command and choosing a dark mode theme.

![image](https://user-images.githubusercontent.com/28519865/93916881-0c16df00-fcbf-11ea-90a2-7983fb20af96.png)

**Comment by bestickley** [comment]
@Charles-Gagnon, thank you for the quick response.
I see now that I was toggling the **Preferred** Color Theme.
It works as expected!
