### ISSUE TITLE
Move Arc instance deployments to use Notebook wizards

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#12577]
It's a better deployment experience for now and lets users configure settings prior to deploying.

Should also make Notebook wizards support "Script" and "Run" buttons - script will generate notebook but not execute while run would script and execute notebook.

[AB#3777](https://mssqltools.visualstudio.com/dea8be32-0532-4a8f-a2f4-89271d8b1cc5/_workitems/edit/3777)

**Comment by ranasaria** [comment]
The changes made converts to wizard, but we still need to provide both script and run experience. Currently checked in experience provides only the script experience
