### ISSUE TITLE
Synchronize release notes with product update

### ISSUE THREAD

**Issue by toasteur** [microsoft/azuredatastudio#12584]
**Is your feature request related to a problem? Please describe.**
after a restart due to an update, a notification appears to suggest consulting the release notes and allow to open a link to the release notes on microsoft docs. for several past versions, each i used this link the release notes only contained information about the PREVIOUS versions, which is not quite useful

**Describe the solution or feature you'd like**
synchronize a new product release with the association version notes

**Comment by Charles-Gagnon** [comment]
@toasteur The link should be to https://go.microsoft.com/fwlink/?linkid=862277 which contains the latest release notes. There might be a little delay as the docs site is updated for every release but generally the content should be correct. Can you confirm whether this is the case?

**Comment by toasteur** [comment]
the release note page is indeed up to date now with a link associated to the 1.49.1 fix, but i think this link wasn't here after the update when vs code offered to see the release notes.
