### ISSUE TITLE
Tabs turn empty after comparison

### ISSUE THREAD

**Issue by LPugens** [microsoft/azuredatastudio#12585]
Issue Type: <b>Bug</b>

When I choose to compare two scripts on different tabs, the original tabs turn blank.

Azure Data Studio version: azuredatastudio 1.22.0 (77b9a708df3679c26a89ba24a070b3f7a078a510, 2020-09-21T20:23:13.120Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.79GB (1.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.0.0
profiler|Mic|0.11.0

</details>

**Comment by alanrenmsft** [comment]
@LPugens , Thanks for letting us know, I tried the "comparing active File with..." command with version 1.22 but I am not able to repro the issue, could you please provide repro steps and also screenshots?
