### ISSUE TITLE
.set commands encounter error "Control commands (starting with a dot '.') cannot be served from the query endpoint"

### ISSUE THREAD

**Issue by baselsalam** [microsoft/azuredatastudio#12588]
- Azure Data Studio Version: 1.22.0 (user setup)

Steps to Reproduce:
1. Open a new query, connect to a kusto cluster
2. Run a normal query, ensure that works, like: print 'hello'
3. Now try to save the results of this into a table, using:
        .set _Test_FromADS <| (print 'hello')

This fails with
"message": "Control commands (starting with a dot '.') cannot be served from the query endpoint unless they are .show control commands.",

**Possible fix:** for queries that start with control command (starts with dot, except for .show),
the request needs to go against the management endpoint (/v1/rest/mgmt),
not the query endpoint (/v1/rest/query)

**Comment by gupta1** [comment]
@baselsalam This should work in kusto 0.2.0 version which will be released this week.

PR: microsoft/sqltoolsservice#1094
