### ISSUE TITLE
Servers Tab Not Showing Saved Connections After Update

### ISSUE THREAD

**Issue by azntegman** [microsoft/azuredatastudio#12587]
Issue Type: <b>Bug</b>

The servers according inside of connections are not showing my saved connections.  I checked my settings.json and I can see that the saved connections are still there, but are somehow not being loaded.  

Azure Data Studio version: azuredatastudio 1.22.0 (77b9a708df3679c26a89ba24a070b3f7a078a510, 2020-09-21T20:23:13.120Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Can you please include a screenshot of what you're seeing? If you add a new connection does it not show up? Also please include the logs using the instructions from the bot.

**Comment by azntegman** [comment]
> Can you please include a screenshot of what you're seeing? If you add a new connection does it not show up? Also please include the logs using the instructions from the bot.

- Here's a screenshot of what I see, that connection group "Test" was a connection group I tried to add and also does not show up.  The collapsed group has sensitive info, so I prefer not to show it
![image](https://user-images.githubusercontent.com/26801967/94052481-a39f2f00-fd9e-11ea-9738-8c7a15e6da5a.png)


> We need more info to debug your particular issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.
> 
> To find your logs:
> 
> * Open command palette (Click **View** -> **Command Palette**)
> * Run the command: **`Developer: Open Logs Folder`**
> 
> This will open the log file locally. Please include renderer.log

I've attached the logs here: I just grabbed the whole folder.
[20200923T131205.zip](https://github.com/microsoft/azuredatastudio/files/5270251/20200923T131205.zip)


Please let me know if there is anything else needed. 

Thanks

**Comment by Charles-Gagnon** [comment]
Hmm, there's nothing here indicating what the problem could be. 

Could you try uninstalling and then reinstalling?

If that doesn't help then could you close ADS, open it and once it's done loading go to `Help -> Toggle Developer Tools` and then click the `console` tab and see if there's any errors displayed there?

![image](https://user-images.githubusercontent.com/28519865/94173383-ba01c500-fe48-11ea-9429-53ae8307d4ef.png)

**Comment by azntegman** [comment]
> Hmm, there's nothing here indicating what the problem could be.
> 
> Could you try uninstalling and then reinstalling?
> 
> If that doesn't help then could you close ADS, open it and once it's done loading go to `Help -> Toggle Developer Tools` and then click the `console` tab and see if there's any errors displayed there?
> 
> ![image](https://user-images.githubusercontent.com/28519865/94173383-ba01c500-fe48-11ea-9429-53ae8307d4ef.png)

Just tried reinstalling it, and same thing happens.  I do see 1 error in the console but it doesn't look related

![image](https://user-images.githubusercontent.com/26801967/94199403-5eeac500-fe7e-11ea-87ca-b5f9554ac0fa.png)

**Comment by Charles-Gagnon** [comment]
And just to be sure - changing color themes doesn't change anything?

**Comment by azntegman** [comment]
> And just to be sure - changing color themes doesn't change anything?
Just tried that. Nothing happens aside from the color theme changing as I swap themes. No additional console errors/info.

**Comment by Charles-Gagnon** [comment]
Couple more things to try : 

1. Browse to the folder where settings.json is located
1. Close ADS
1. Rename the file to `settings.json.bak`
1. Restart ADS
1. Try to add a connection

If that doesn't work:

1. Uninstall ADS
1. Download the installer from https://github.com/microsoft/azuredatastudio/releases/tag/1.21.0
1. Install it and then try adding a connection as normal

**Comment by azntegman** [comment]
> Couple more things to try :
> 
> 1. Browse to the folder where settings.json is located
> 2. Close ADS
> 3. Rename the file to `settings.json.bak`
> 4. Restart ADS
> 5. Try to add a connection
> 
> If that doesn't work:
> 
> 1. Uninstall ADS
> 2. Download the installer from https://github.com/microsoft/azuredatastudio/releases/tag/1.21.0
> 3. Install it and then try adding a connection as normal

Hi, sorry for the late reply.  The first part didn't work so I ended up installing 1.21.0 and everything is back to normal, showing my old connections.  

Thanks for all you help.

**Comment by Charles-Gagnon** [comment]
And if you update back to 1.22 then you still don't see the connections?

Would you be willing to e-mail me your settings.json file so I can see if there's something specific to your environment? (Passwords are not stored there - but it would contain server names and usernames)

**Comment by azntegman** [comment]
> And if you update back to 1.22 then you still don't see the connections?
> 
> Would you be willing to e-mail me your settings.json file so I can see if there's something specific to your environment? (Passwords are not stored there - but it would contain server names and usernames)

Just updated it back to 1.22 and connections disappeared again.  I really would rather not send the settings.json file.  Unless you don't mind me renaming the server names and changing anything that I deem sensitive information.

In the mean time, I will downgrade it back to 1.21

Thanks

**Comment by Charles-Gagnon** [comment]
It's worth looking at to see if there's something odd with the format - so yeah if you don't mind stripping out whatever sensitive information you have in there and mailing that to chgagnon@microsoft.com that'd be great.

When you've tried adding a single server what type of server is it and how are you authenticating (SQL login/AAD)?

**Comment by azntegman** [comment]
Alright I'll strip sensitive data and send it over.  I didn't actually try adding a server, because I tried adding a server group, something super basic, and that didn't show up. But my connections are all Windows Authentication if that helps.

**Comment by Charles-Gagnon** [comment]
I was able to repro the issue - it looks like you've modified the settings.json file manually so the values aren't what we expect. 

The first entry in the connection groups section needs to have capitalized ROOT as the name - using lowercase will break it as you're seeing.

```
    {
      "name": "ROOT",
      "id": "c777f06b-202e-4480-b475-fa416154d458"
    },
```

Fixing that made it work for me.

![image](https://user-images.githubusercontent.com/28519865/94586932-b9956f80-0236-11eb-9bec-5311aa7f268b.png)


Do you know how you got in this state? If you deleting the settings.json file as I suggested and then added the connections using the ADS connection dialog it should be setting the values as expected so if that's not happening let me know.

I'll look into making it not so strict in the casing requirements - but in general custom modifications to the settings.json should be done with care and only in special circumstances.

**Comment by Charles-Gagnon** [comment]
I have a PR out with a fix so that should be out in the next stable release. In the meantime you can either roll back to 1.21 or use 1.22 and change the root group name to ROOT as suggested as a workaround.

**Comment by azntegman** [comment]
> I was able to repro the issue - it looks like your settings.json has a lowercase root group name which is throwing off our logic (this was refactored in the last release which is why you're seeing it break now).
> 
> The first entry in the connection groups section needs to have capitalized ROOT as the name with the new logic - using lowercase will break it as you're seeing.
> 
> ```
>     {
>       "name": "ROOT",
>       "id": "c777f06b-202e-4480-b475-fa416154d458"
>     },
> ```
> 
> Fixing that made it work for me.
> 
> ![image](https://user-images.githubusercontent.com/28519865/94586932-b9956f80-0236-11eb-9bec-5311aa7f268b.png)
> 
> Do you know how you got in this state? If you deleting the settings.json file as I suggested and then added the connections using the ADS connection dialog it should be setting the values as expected so if that's not happening let me know.
> 
> I'll look into making it not so strict in the casing requirements - but in general custom modifications to the settings.json should be done with care and only in special circumstances.

I definitely did not change "root" name, but I do modify my settings manually.  However, I have been using ADS since it was called SQL Operations Studio.  I bet you it was when I copied the settings.json from there to ADS. 

You think that might be it?

Thanks again for you help.

**Comment by Charles-Gagnon** [comment]
That could very well be it - thanks for all your help investigating it!
