### ISSUE TITLE
Flat file import stripping backslash characters

### ISSUE THREAD

**Issue by pnhughes** [microsoft/azuredatastudio#12593]
Azure Data Studio Version:
Version: 1.22.0 (user setup)
Commit: 77b9a708df3679c26a89ba24a070b3f7a078a510
Date: 2020-09-21T20:23:13.120Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Prepare simple CSV file (UTF-8, CRLF) including file paths for import (or any other column containing backslash characters. (See attached "ads_import_test.txt" (renamed from .csv to allow for upload)).
2. Invoke flat file import wizard (i.e. right-click on target database, select Import Wizard)
3. Select import file and import database name and click Next to data preview.
4. Preview of column originally containing backslash characters contains no backslash characters
5. If import is completed, column is imported without backslashes.

Imports I am attempting to perform in this version are highly similar to previous import work performed successfully with previous versions. This is the first such import attempted on the current version of ADS, and the first time I have experienced this issue.

[ads_import_test.txt](https://github.com/microsoft/azuredatastudio/files/5271970/ads_import_test.txt)

![ads_import_test_preview](https://user-images.githubusercontent.com/5973777/94070966-59bf4480-fdb0-11ea-80d1-f47b7af033e9.png)

**Comment by pnhughes** [comment]
As an update, I have tested this issue with the current Insider build (1.23) and with my last known good version of ADS (1.19), and neither resolves the issue.  In each case, the Import extension version appears to be the same (1.0.0 in the marketplace description, but 0.0.5 in the blob download URL (https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.5/win-x64.zip)).

**Comment by pnhughes** [comment]
Additional update - Import appears to not treat the backslash character as a literal in the column data, but rather as an escape character.  For example, if a double-backslash is included in the import file column, a single backslash appears in that position in the import preview.

**Comment by Charles-Gagnon** [comment]
@pnhughes Note that with regards to the version - the download URL you're referring to is for the backing service that the extension downloads (it's a separate dotnet app that runs in the background). So that's expected to be 0.0.5 and is not tied to the extension version directly.
