### ISSUE TITLE
installation link for azdata tool in control create notebook is broken

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12599]
The azdata installation link in the azdata tool table at the top of the notebook generated by Azure Arc Data Controller Create Wizard is broken. It points to https://github.com/microsoft/Azure-data-services-on-Azure-Arc/blob/master/scenarios/001-install-client-tools.md which gives 404.

Also, the tool name should be changed to Azure Data CLI

**Comment by Charles-Gagnon** [comment]
This has been fixed
