### ISSUE TITLE
SQL Server Import extension still has preview tag

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#12594]
SQL Server Import moved to v1.0 but still has preview tag in both marketplaces

@aasimkhan30

**Comment by weblorin** [comment]
The Extension details also say _Import Flat File Wizard (preview)_ and _This experience is currently in its initial preview._ 

The details also says it can _copy data from a flat file (.csv, .txt, .json)_ and then a few sentences later says _only works on .txt and .csv files_.

**Comment by pnhughes** [comment]
Moreover, I notice when downloading the extension that the version on the blob server is 0.0.5.  Not sure how relevant this is.

https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.5/win-x64.zip
