### ISSUE TITLE
WYSIWYG Text view: Tab key should set list item to its next logical level

### ISSUE THREAD

**Issue by halerankin** [microsoft/azuredatastudio#12600]
In the Text view, use of the Tab key when cursor is positioned at the start of a list item should result in setting the list item to its next logical level. This behavior can be demonstrated in Markdown view:

![image](https://user-images.githubusercontent.com/12279161/94086534-1ff63a00-fdc0-11ea-810e-6fdc289b288b.png)

Findings:
In Markdown view, Tab key before `- list item` will cause it to shift to its next logical list item level.
In Text view, Tab key at same position makes cursor jump into first element of next cell.

In light of this somewhat related issue: #6682, we could try to solve for both indenting code and setting list items to their next logical level.

**Comment by halerankin** [comment]
@MsSQLGirl for visibility

**Comment by chlafreniere** [comment]
@halerankin Mmm. Can we look at how we handle undo in the text cell component and do the same sort of thing that we do for undo/select all and call `stopPropagation()`?
