### ISSUE TITLE
Installation and First time usages

### ISSUE THREAD

**Issue by GirishKumarSharma** [microsoft/azuredatastudio#12604]
I have downloaded azuredatastudio-linux-1.22.0.tar.gz, extracted to folder and run the ./azuredatastudio from bin folder. But what are new connection details? How do I obtain them i.e. what is Server name, user name and password. It seems that very first question but very sad, it has not asked anywhere. I am very much interested to test this app.

**Comment by Charles-Gagnon** [comment]
@GirishKumarSharma Please see the docs for guides to help you get started! https://docs.microsoft.com/sql/azure-data-studio/what-is
