### ISSUE TITLE
Adding Azure account with unicode characters shows wrong

### ISSUE THREAD

**Issue by tomgron** [microsoft/azuredatastudio#12629]
Issue Type: <b>Bug</b>

My name (Tommi Grönlund) was shown weird after adding connection to the Azure Data Studio. 

Azure Data Studio version: azuredatastudio 1.22.0 (77b9a708df3679c26a89ba24a070b3f7a078a510, 2020-09-21T20:23:13.120Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (17.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.0.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.5.0
server-report|Mic|0.2.2
sql-assessment|Mic|0.2.0
sql-database-projects|Mic|0.1.3
whoisactive|Mic|0.1.4

</details>

![image](https://user-images.githubusercontent.com/1743381/94237711-ecc6be80-ff17-11ea-83b9-3ba13354a100.png)

**Comment by tomgron** [comment]
This still shows wrong in latest version (1.37.0 user setup)
![image](https://user-images.githubusercontent.com/1743381/179365674-aaeca921-cad0-432c-9ce9-ba4348fa3686.png)

**Comment by andrekamman** [comment]
Same here! 
Since Azure specifically asks for your name, you can expect people to use accents and characters that are applicable to spell their name correctly. Displaying that incorrectly in a tool, especially if that tool is related to handling data, should never happen and seems like something which is easy to fix to me.
![Snag_d3d35860](https://user-images.githubusercontent.com/5106160/199036524-63e0f5c6-34a5-403e-a58f-22233014b404.png)

**Comment by bidgeir** [comment]
I have the same issue. It´s not a showstopper but it´s very annoying in this day and age. It´s not really helpful for adoptions when your name cannot be spelt correctly. 

![image](https://user-images.githubusercontent.com/4395145/199040872-cf6b347d-5e50-4dea-ac68-eb211c2e1529.png)

**Comment by ClaudioESSilva** [comment]
Hi folks, +1 here
![image](https://user-images.githubusercontent.com/19521315/199041387-08bbec11-7b22-453f-9379-41f77619c782.png)

**Comment by tomgron** [comment]
Version: 1.39.1 (user setup)
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22621

This has still the name wrong, 

![image](https://user-images.githubusercontent.com/1743381/199816863-16c921c6-35a4-44e8-81df-6212cfd497db.png)

**Comment by Charles-Gagnon** [comment]
This should be fixed in the [Insiders Build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main), and will be included in the next stable update later this month. If you try out insiders and still see the issue let us know and we can investigate further!

**Comment by tomgron** [comment]
> This should be fixed in the [Insiders Build](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main), and will be included in the next stable update later this month. If you try out insiders and still see the issue let us know and we can investigate further!

True, at least for me insiders build seems to work perfectly. Hope this gets soon to the main release : 
![image](https://user-images.githubusercontent.com/1743381/199819198-c13e782f-ad37-4b5e-b246-2bcad832d3d7.png)
