### ISSUE TITLE
Flat file import stuck on Step 4

### ISSUE THREAD

**Issue by Bluefire-IT** [microsoft/azuredatastudio#12624]
- Azure Data Studio Version:

Steps to Reproduce:

1. at the step 4, import status takes too long to load, been 30 minutes and still stuck. This happens right after the update
![test](https://user-images.githubusercontent.com/71860188/94220513-b5f2a780-ff1b-11ea-8c3e-815053b0490a.PNG)

**Comment by aasimkhan30** [comment]
@Bluefire-IT can you provide more information about the file that you are trying to import? 
(The size of it, number of rows and column)

**Comment by Bluefire-IT** [comment]
In the sample picture, the file size imported is 62bytes, with a total row of 4 and 3 columns.

**Comment by mauvedeity** [comment]
I'm also having this problem. I think it's to do with the "Server name" field showing "MSSQL", which is obviously not the name of the server I'm trying to import to. My file is 8 columns of CSV, 89 rows, 3073 characters. I've imported similar files before.

**Comment by sheenaia** [comment]
Hi, I’m facing the same issue of being stuck on Step 4. I gave it an hour or so and the status is still loading. The file (CSV) size im trying to upload is 19.1GB with 34.9M rows & 41 Columns. Is there a better way to import such a large file into ADS (using a mac)?
