### ISSUE TITLE
Unable to connect now

### ISSUE THREAD

**Issue by supeRpoweRcodeR** [microsoft/azuredatastudio#12649]
Hi ,

Suddenly ADS stopped working, I t was working an hour back.

Is there any outage for ADS or Azure Cloud ??

This is a complete blocker.

**Comment by Charles-Gagnon** [comment]
https://status.azure.com/en-us/status

Seems there's an AAD outage - I'm going to close this now since that's likely the issue but if you think it's unrelated or still have this issue after it's resolved let us know and we can investigate further.
