### ISSUE TITLE
SQL Temp tables not persisted between cells

### ISSUE THREAD

**Issue by ChrisUnsworth** [microsoft/azuredatastudio#12647]
- Azure Data Studio Version:
1.22
Steps to Reproduce:

1. Create new notebook using an SQL Kernel
2. Create code cell containing:
`DROP TABLE IF EXISTS #Test

SELECT *
INTO #Test
FROM 
 (VALUES (1)) AS v(i)

SELECT * FROM #Test`
3. Create second code cell with:
`SELECT * FROM #Test`
4. observe error message:
`Msg 208, Level 16, State 0, Line 1
Invalid object name '#Test'.
Total execution time: 00:00:00

`

**Comment by Charles-Gagnon** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/12646

**Comment by anisri** [comment]
SQL temp tables persist between cells, but intellisense doesn't recognize those table names. Still a lingering issue here.
