### ISSUE TITLE
SQL Notebooks: Cells being treated isolated

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#12646]
Issue Type: <b>Bug</b>

1. Create a SQL notebook
2. First Cell: "USE <any user database>"
3. Second cell: "SELECT * from <any table in that db>"

Error: Table doesn't exist
Reason: The second cell didn't keep the database context

This worked fine in previous releases

Azure Data Studio version: azuredatastudio 1.22.0 (77b9a708df3679c26a89ba24a070b3f7a078a510, 2020-09-21T20:23:13.120Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (18.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.4.4
azdata|Mic|0.2.2
datavirtualization|Mic|1.9.0

</details>

**Comment by chlafreniere** [comment]
This is now in the release branch and a fix will go out as part of our upcoming release to stable. Insiders will have the fix during the next insiders build.
