### ISSUE TITLE
Wont let me import a flat file when localhost is connected

### ISSUE THREAD

**Issue by ferpompa** [microsoft/azuredatastudio#12648]
Issue Type: <b>Bug</b>

It's frustrating that i cant import my .csv file, it stays on import status and wont go through, I'vve done it before and worked perfectly, don't know whats going this time. 

Azure Data Studio version: azuredatastudio 1.22.0 (77b9a708df3679c26a89ba24a070b3f7a078a510, 2020-09-21T18:41:27.116Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.0.0

</details>

**Comment by HikkaV** [comment]
Have the same issue, please help.

**Comment by Bluefire-IT** [comment]
having a same issue too.

**Comment by chrisgwilliams** [comment]
The flat file importer stopped working immediately after installing the latest Azure Data Studio update. 

I've used it probably 50 times in the last month, worked fine.

Version: 1.22.0 (user setup)
Commit: 77b9a708df3679c26a89ba24a070b3f7a078a510
Date: 2020-09-21T20:23:13.120Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Could you please investigate?

**Comment by chrisgwilliams** [comment]
Reinstalling 1.21 gets rid of the problem. FYI.
