### ISSUE TITLE
Add a Kusto support for Log Analytics and Azure Resource Graph queries

### ISSUE THREAD

**Issue by alexandair** [microsoft/azuredatastudio#12665]
It would be very useful if you could extend Kusto support to Log Analytics and Azure Resource Graph queries.

**Comment by MsSQLGirl** [comment]
Great news!
Azure Data Studio Insiders v1.32.0 ([download](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)) now supports Azure Monitor Logs extension preview. We expect this to be part of Azure Data Studio 1.32.0 August Release stable. 

In Azure Data Studio Insiders / stable v1.32.0, 
1. search for "Azure Monitor Logs" extension. 
2. install the extension.
3. In the Connections viewlet, 
- create a new connection with 'Azure Monitor Logs' connection type. 
- provide the Log Analytics workspace ID that you'd like to connect to.
- connect using AAD.
- (ignore the Database field)
- click Connect
4. Start writing KQL queries, such as 
```
AzureDiagnostics
| take 10
```

Users can also create a new notebook connecting to "Log Analytics" kernel.

Note: it is possible to access the AppInsights data by traversing to the Log Analytics workspace. 

Hope this helps.

Note: We don't have plan for Azure Resource Graph yet.

**Comment by Charles-Gagnon** [comment]
Given the above I'm going to close this - if you still are looking to have support for Azure Resource Graph please open another issue for that specifically. Thanks!
