### ISSUE TITLE
Control commands

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/azuredatastudio#12705]
**Is your feature request related to a problem? Please describe.**
It would be nice to run control commands to create tables and such as that's what a lot of my work entails.

**Describe the solution or feature you'd like**
I'm not sure if this is possible with the Kusto API, I'm guessing it may be more of an upstream problem as to how the API handles control commands (which makes sense from a security perspective). [The documentation is helpful but a little sparse](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/management/).

**Describe alternatives you've considered**
Using the web portal works fine of course, but I like Azure Data Studio :)

**Additional context**
Is there any part of the extension source I could look at to see how queries are parsed and requested as well as the same for response handling? If it's something like switching api endpoints I could take a stab at it and submit a pull request.

**Comment by gupta1** [comment]
This should work in kusto 0.2.0 version which will be released this week: https://github.com/microsoft/sqltoolsservice/pull/1094
