### ISSUE TITLE
LogAnalytics support in ADS

### ISSUE THREAD

**Issue by gupta1** [microsoft/azuredatastudio#12701]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Charles-Gagnon** [comment]
@JustinMDotNet Can we close this now that support for this has been added?

**Comment by JustinMDotNet** [comment]
This is now supported in the Azure Monitor Logs extension. Closing.
