### ISSUE TITLE
External Streams and External Streaming Jobs aren't placed in a folder when creating a project from a database

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#12716]
When organized by "Schema/ObjectType", input/output streams and streaming jobs are top-level elements, but should probably go under the ExternalResources folder with External File Format and External Data Source

**Comment by kisantia** [comment]
needs to be fixed in DacFx

**Comment by kisantia** [comment]
@ssreerama feel free to ask for more info on this. This isn't for January release, not an urgent thing

**Comment by ssreerama** [comment]
@kisantia, Sure, will look into it and reach you if I have any questions :)

**Comment by ssreerama** [comment]
This is fixed and sent to DacFx CR.

**Comment by ssreerama** [comment]
This Issue is fixed and moved to the code base.
