### ISSUE TITLE
[xcb] Unknown sequence number while processing queue - XInitThreads -ubuntu

### ISSUE THREAD

**Issue by sajagekar** [Microsoft/azuredatastudio#1272]
- SQL Operations Studio Version: 0.28.6

Steps to Reproduce:
Installed Ubuntu version of it, While launching the application getting below error.

[xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
/home/sunila/sqlops-linux-x64/sqlops: ../../src/xcb_io.c:274: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
Aborted (core dumped

Sometimes it is working but not launching app.

**Comment by sajagekar** [comment]
Are below all libraries needed?

alsa-lib (alsa-lib-x205ta)
cairo (cairo-git, cairo-ubuntu, cairo-dfb, cairo-minimal, cairo-infinality, cairo-nomesa, cairo-infinality-ultimate)
curl (curl-http2-git, curl-git, curl-ssh)
fontconfig (fontconfig-git, fontconfig-infinality, fontconfig-ubuntu, fontconfig-srb, fontconfig-infinality-ultimate)
gcc-libs (gcc-libs-multilib-x32, gcc-libs-git, gcc-libs-multilib-git)
gconf (gconf-gtk2)
glibc (glibc-git)
gtk2 (gtk2-patched-gdkwin-nullcheck, gtk2-patched-filechooser-icon-view, gtk2-ubuntu)
libsecret
libunwind (libunwind-git)
libxkbfile
libxss
libxtst
nss (nss-hg)
python
krb5

**Comment by sajagekar** [comment]
I tried to run it but it keeps freezing the VM so I have to terminate it each time. I tried reinstalling but I get the same issue. I type 'sqlops' into terminal and I get the following message: update#setstate idle 
and then it eventually freezes.

I have tried installation using Debian as well as tar. Also increased VM size to 16 GB RAM & 4 cores.

**Comment by kburtram** [comment]
@sajagekar I tested the July release on a default Ubuntu installation and it worked as expected installed either from the .deb and .tar.gz file.  This could be a conflict with some other software installed on your machine.
