### ISSUE TITLE
Validation needed for already existing resource names chosen by the user.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12728]
Here are a few examples:
1. - [ ]  Mi Sql instance name
2. - [ ] 2. Postgres Server instance name
3. - [ ] 3. Arc dc name, arc namespace.

It would be good to do these validations before exiting the corresponding wizard pages so that the user can be alerted about failures that they will run into during notebook execution.

**Comment by Charles-Gagnon** [comment]
Not something we're planning on doing currently
