### ISSUE TITLE
Dac Editor Build error : .NET Core should not be using a file backed model.

### ISSUE THREAD

**Issue by JChristian23** [microsoft/azuredatastudio#12730]
When testing the new Dacpac editor extension on a Database Projected created in VS 19, the project opens correctly and can be edited, but when I attempt to build the solution, the build fails with the following error: 

Build error : .NET Core should not be using a file backed model.

I have verified that it builds successfully with VS 19, even after being upgraded to Azure Data Studio's version.

**Comment by kisantia** [comment]
@JChristian23 can you share the rest of the call stack? It would also be helpful if you can share the .sqlproj or a sample .sqlproj that repros the error.

**Comment by JChristian23** [comment]
@kisantia Here you go
[ADS Publish Callstack.txt](https://github.com/microsoft/azuredatastudio/files/5329848/ADS.Publish.Callstack.txt)
[Asos.zip](https://github.com/microsoft/azuredatastudio/files/5329854/Asos.zip)

**Comment by kisantia** [comment]
@JChristian23 can you try commenting out line 27( `<GenerateCreateScript>True</GenerateCreateScript>`)  in the sqlproj? The build error went away when I removed that. I'll have to investigate more why that project property is causing this build error.

**Comment by JChristian23** [comment]
Rather than commenting it out, I went into VS 19, then went into Properties > Project Settings. Under Output times, I unchecked Create script and it built correctly. When I reset it back to True, the build failed again, so that is definitely the hangup. For now though setting that property to false functions

**Comment by kisantia** [comment]
Ok thanks for the confirmation and finding this bug! I created another issue to track this bug #12754 and we'll try to get to it in an upcoming release.

To generate a create script in ADS, you can use the publish dialog for now, which has a generate script button. If the target database doesn't already exist, the generated script will be for creating a new database for the project

**Comment by jwisener** [comment]
this bug has prevented us from using this.

**Comment by tlentine** [comment]
Just ran into this bug today ourselves.

**Comment by kisantia** [comment]
closing as this is being tracked upstream in the DacFx repo: https://github.com/microsoft/DacFx/issues/47#issuecomment-1314202507
