### ISSUE TITLE
Schema compare dialog blank while loading

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#12769]
The schema compare dialog can take some time to load, but it's just blank with no indication that loading is happening. Instead of waiting for the databases list to finish loading, load the rest of the dialog and have a loading spinner in the place of the database dropdown.

**Comment by udeeshagautam** [comment]
This refers to the source target select dialog - right?

**Comment by kisantia** [comment]
yup the select source and target dialog
