### ISSUE TITLE
WYSIWYG editing replaces linked images relative path to absolute path

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#12776]
Edit a notebook with image in WYSIWYG editor
Save the notebook
Check the diff

eg. `![](./media/example.jpg)`,

gets converted to
`![](c:\\Users\\<<user>>\\repos\\MyBooK\\content\\TSGs\\/./media/example.jpg)`

**Comment by chlafreniere** [comment]
@rajeshka can you please put some more info here besides empty strings

**Comment by Charles-Gagnon** [comment]
@chlafreniere Fixed it (if you go into edit mode usually the content is still there, in this case he just hadn't escaped it properly so it thought it was actual markdown 😆 )
