### ISSUE TITLE
Schema compare opens with previous window's selected source

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#12775]
Version: Schema Compare 1.5.0

Steps to reproduce:
1. open a schema compare window
2. Select a source
3. open a new schema compare window from command palette

Expected:
Source and target in new schema compare should be blank

Actual:
Source is filled with same selected source as previous schema compare. If you selected a target too, that will also be remembered when you click on the '...' to change source/target

Strangely only happens in release, can't repro in dev build
![schemaCompareRemembers](https://user-images.githubusercontent.com/31145923/95263573-d4da1f00-07e2-11eb-8d1a-6f023af21f3e.gif)

**Comment by udeeshagautam** [comment]
Adding to Nov for avoiding new chnages but looks like ths is already fixed.

**Comment by kisantia** [comment]
confirmed this is fixed in insiders
