### ISSUE TITLE
[intermittent] Schema compare Source/Target select dialog gets incorrectly re-populated

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#12779]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a Schema compare window from a database
2. source will be already populated at this time.
3. click the Browse '..." button to select target
4. source is automatically repopulated to some other value then actually selected - this should never happen

This doesnt happen often and is not a regression but still need investigation since it happens without users input

**Comment by kisantia** [comment]
might have been related to #12775
