### ISSUE TITLE
ML- Image cut off in Useful links 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#12788]
- Azure Data Studio Version:

Steps to Reproduce:

Some images are cut off in the dashboard for ML extension.

<img width="684" alt="Screen Shot 2020-10-07 at 9 08 46 AM" src="https://user-images.githubusercontent.com/17187348/95357738-1a4b2a80-087d-11eb-9e45-97b39e060cab.png">

**Comment by halerankin** [comment]
Currently unable to repro using Window 10, and ADS Insiders Build v1.24.0

**Comment by llali** [comment]
I can repro this in mac
