### ISSUE TITLE
Couldn't enable cloud in Azure Data Studio

### ISSUE THREAD

**Issue by MChan1410** [microsoft/azuredatastudio#12786]
Issue Type: <b>Bug</b>

Hi, I would like to add an azure account, but seems like its disabled. 
When am trying to search for ' Azure Account Configuration -> Enable at least one cloud' in Settings. I couldn't find anything. 

Without that I couldn't add my account.

Azure Data Studio version: azuredatastudio 1.22.1 (1b5c54dd8c6eb03bf7ed1e04889d9f41de0523b3, 2020-09-29T16:41:11.578Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by arome** [comment]
I'm facing the same issue

**Comment by Charles-Gagnon** [comment]
@MChan1410 - If you type in just the first part do you see these options? At least one of them needs to be checked.

![image](https://user-images.githubusercontent.com/28519865/95911364-415e9c00-0d56-11eb-9c2b-4da78524af12.png)

@arome - Are you having the same issue with the settings?

**Comment by MChan1410** [comment]
Hello arome, My problem is "it doesn't even show" in options to enable it.
Attached.

[image: image.png]

**Comment by MChan1410** [comment]
Awesome, Probably I would have done the same thing. I applied a filter on
"Disabled" extensions and found Azure (Core) was disabled :-)

Thank you, Omar! It resolved my issue. .

[image: image.png]

**Comment by MChan1410** [comment]
![Capture](https://user-images.githubusercontent.com/72504119/96027709-4428c200-0e26-11eb-8aa6-0106b8034a9f.PNG)

Thank you arome! I am closing this issue now.

**Comment by Charles-Gagnon** [comment]
Interesting - do either of you know how you got into this state? That extension should never be disabled

**Comment by arome** [comment]
Yup in my case, I had logged out of all my accounts from my organization email. 
So when I opened Azure Data Studio the next day it showed me that there was an error in my connection and this extension opened. I then disabled it thinking this was causing the issue.
And ye, that's pretty much it.
