### ISSUE TITLE
Kqlmagic in Azure Data Studio should behave like pip install where it picks the latest best non-dev version

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12792]
- Azure Data Studio Version:
Version: 1.22.1
Commit: 1b5c54dd8c6eb03bf7ed1e04889d9f41de0523b3
Date: 2020-09-29T16:38:23.291Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-48-generic

Steps to Reproduce:

1. Use **Manage Packages** on a Python Notebook. 
2. Click on **Add New** then search for Kqlmagic. 
Actual - 
![image](https://user-images.githubusercontent.com/6405919/95371952-c0a02b80-088f-11eb-8448-a5442f82c269.png)

Expected - 
pip upgrade command today installs/upgrades kqlmagic with the latest non-dev version. It would be best to match this behavior. 
i.e. only list 0.1.11, 0.1.12, 0.1.13, 0.1.113post etc. 
(For testing purposes, users can install the dev versions from pip manually if needed)

**Comment by chlafreniere** [comment]
@corivera is there a relatively simple fix that we can do here? I seem to recall that we have that logic that allows us to sort package versions, so wondering if we can augment that with sorting when a package has "dev" like it does here.

**Comment by corivera** [comment]
The sorting method we use is here: https://github.com/microsoft/azuredatastudio/blob/main/extensions/notebook/src/common/utils.ts#L146

I'll take a look at these new cases.
