### ISSUE TITLE
Arc deployment localization keys not found in release/1.23

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#12797]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open ADS
2. On the bottom right corner you can see the warnings.

![image](https://user-images.githubusercontent.com/6816294/95390112-b8ed8080-08a9-11eb-87f4-e8248513d5bd.png)
![image](https://user-images.githubusercontent.com/6816294/95390006-8c396900-08a9-11eb-8a27-5f6874a0dbd1.png)

**Comment by abist** [comment]
Can confirm -

![Screen Shot 2020-10-07 at 2 35 40 PM](https://user-images.githubusercontent.com/6411451/95390596-7ed0ae80-08aa-11eb-9e1d-b5a31d1a88f5.png)

**Comment by ranasaria** [comment]
It is not just those three missing localized strings. MIAA and Postgres instance deployments are broken right now in the release branch.

**Comment by Charles-Gagnon** [comment]
Ack, looking into this
