### ISSUE TITLE
Not able to connect to ms-sql container listening on port 1433 on Mac

### ISSUE THREAD

**Issue by Awdesh** [microsoft/azuredatastudio#1280]
Issue Type: <b>Bug</b>

I am running a ms-sql container on port 1433 on Mac but not able to connect to it. I use 'localhost' as a server name and SQL Login authentication.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:07:51.383Z)
OS version: Darwin x64 15.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Users/asd8a7/Downloads/SQL Operations Studio.app/Contents/MacOS/Electron -psn_0_4076515|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.28.1
server-report|Mic|0.1.1

</details>
Reproduces only with extensions

**Comment by MattIrv** [comment]
@Awdesh I tried to reproduce this but it connects successfully for me. Could you provide the error message you get when trying to connect? Also, can you confirm whether you can connect from within the container using sqlcmd (https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-linux-2017#connect-to-sql-server) and from tools that aren't SQL Operations Studio (such as [mssql-cli](https://blogs.technet.microsoft.com/dataplatforminsider/2017/12/12/try-mssql-cli-a-new-interactive-command-line-tool-for-sql-server/) running on your Mac?

Note that if you set up your container by following the exact directions at https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker then your instance of SQL Server will be running on port 1401, not port 1433.

You also indicated that it reproduces only with extensions, is that correct?

**Comment by Awdesh** [comment]
I use DBeaver and also have a python app that connects to mssql successfully.
I also tried connecting to the hosted SQL server instance but get the same issue.

SQL operation studio doesn't give me any error.Where should I see the error? progress circle keeps spinning endlessly.

**Comment by jannyg** [comment]
I have the same issue. The progress circle keeps spinning endlessly when trying to connect. I have verified connection to the server with mssql-cli from the same machine. How can i help you to reproduce this?

macOS 10.13.5
sqlops 0.30.6

MSSQL 2008 R2 on Windows 2008 R2
