### ISSUE TITLE
Loading Kernel stuck never ends

### ISSUE THREAD

**Issue by eliassal** [microsoft/azuredatastudio#12804]
Issue Type: <b>Bug</b>

When I open some notebooks with powershell (mainly to use dbatools ), I the bar where we have "Cell Run All Kernel...."
In font of Kernel = Loading Kernel....
and never ends, restarted ADS, rebooted the machine but nothing helped

![ADS-Kernel](https://user-images.githubusercontent.com/8447864/95425904-534ed200-0945-11eb-892e-20520a544caf.jpg)

Azure Data Studio version: azuredatastudio 1.22.1 (1b5c54dd8c6eb03bf7ed1e04889d9f41de0523b3, 2020-09-29T16:41:11.578Z)
OS version: Windows_NT x64 10.0.19041

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
datavirtualization|Mic|1.10.0
import|Mic|1.0.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.5.0
azdata-sanddance|msr|3.1.0
sqlops-spexecutesql-to-sql|pej|1.0.1
schema-visualization|R0t|0.2.0

</details>

**Comment by corivera** [comment]
Closing due to no repro.
