### ISSUE TITLE
Add support to wildcards in SQL Projects

### ISSUE THREAD

**Issue by kblok** [microsoft/azuredatastudio#12817]
**Is your feature request related to a problem? Please describe.**
I'm able to setup sqlprojects using wildcards en visual studio

```xml
<Build Include="dbo\**\*.sql" />
<None Include="Scripts\**\*.sql" />
````

I'm getting a funny result when using that sqlproj in datastudio

![image](https://user-images.githubusercontent.com/2198466/95498305-fb7e8e00-0979-11eb-9c16-8d8d4de77d2c.png)

**Describe the solution or feature you'd like**
It would be great to support wildcards there.

**Comment by tlentine** [comment]
This would be a fantastically useful feature and in our case speed adoption of being able to use Azure Data Studio for development instead of using Visual Studio & SSDT.

**Comment by kisantia** [comment]
@kblok @tlentine there is now support for SDK-style projects in ADS and wildcards are supported for SDK-style projects if you'd like to give it a try!

Blog on SDK-style sql projects: https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-build-sql-the-next-frontier-of-sql-projects/ba-p/3290628
