### ISSUE TITLE
Saved connection when selected does not show actual Server Group in details

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#1281]
- SQL Operations Studio Version: `0.28.6`

This is mostly cosmetic issue but the saved connection if it exists under a server group does not show the group selected in the connection details.

Steps to Reproduce:
1. Create a new server group
2. Add some saved connections to the group.
3. In a new query window go to connections
4. Go to saved connections
5. Select a saved connection.
6. Note that the Server Group shows `<none>` and not the actual group it is a part of.

![image](https://user-images.githubusercontent.com/11204251/39335051-03c365d8-4977-11e8-9f54-6a3c9dcf6703.png)

For reference my current user settings that shows the saved connections:

```json
{
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        },
        {
            "name": "containers",
            **"id": "a1cc5cf6-b647-46c7-a755-e28194b17dae",**
            "parentId": "C777F06B-202E-4480-B475-FA416154D458",
            "color": "#85AE72",
            "description": "Instances tied to Docker Containers"
        }
    ],
    "datasource.connections": [
        {
            "options": {
                "server": "localhost,1412",
                "database": "",
                "authenticationType": "SqlLogin",
                "user": "sa",
                "password": "",
                "applicationName": "sqlops",
                **"groupId": "a1cc5cf6-b647-46c7-a755-e28194b17dae"**,
                "databaseDisplayName": ""
            },
            **"groupId": "a1cc5cf6-b647-46c7-a755-e28194b17dae",**
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "9b4f56e3-2016-4ae1-ae66-a13b32348ecd"
        },
        {
            "options": {
                "server": "localhost,1414",
                "database": "",
                "authenticationType": "SqlLogin",
                "user": "sa",
                "password": "",
                "applicationName": "sqlops",
                **"groupId": "a1cc5cf6-b647-46c7-a755-e28194b17dae",**
                "databaseDisplayName": ""
            },
            **"groupId": "a1cc5cf6-b647-46c7-a755-e28194b17dae",**
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "73c3cd66-18e8-4548-95ba-f977de369622"
        }
    ]
}
```

**Comment by MattIrv** [comment]
@llali This only repros when connecting from a query editor and not otherwise.

We have some code in `connectionDialogService.ts` (line 293) that tells us not to save the connection when connecting from a query editor, and the way we implement that is by setting the group to None (see `connectionWidget.ts` line 385)

Maybe there's a better way of handling this that doesn't involve using the None server group as a way of storing that the connection shouldn't be saved

**Comment by kburtram** [comment]
Closing this older issue as by-design.  When connecting to a server from the query editor we default to not save the connection to object explorer tree to support ad-hoc querying of servers without creating clutter.  To save a connection please connect to the server through the servers viewlet.  Thanks!
