### ISSUE TITLE
MIAA/PG Deployment notebooks don't have controller information filled in

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#12814]
1. Fill out deployment fields for MIAA/PG
1. Script to Notebook

The controller endpoint/username fields are empty : 
![image](https://user-images.githubusercontent.com/28519865/95495608-82b90b00-0954-11eb-8e7d-bed919314136.png)

Saw this initially when I was testing the release branch but this also repros for me in main

**Comment by ranasaria** [comment]
Investigating

**Comment by ranasaria** [comment]
Observed this error that fires just before notebook is opened. It vanishes quickly so is hard to see.

Cannot read property '_treeProvider' of undefined

**Comment by ranasaria** [comment]
Fixed by PR: #12828
