### ISSUE TITLE
Changing Server target in Project Publish UI doesn't trigger enabling Publish button

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#12812]
Repro:
1. Right-click on project, select Publish
2. Select profile (server is blank because not set in profile, database is set in profile)
3. Select server connection

Expected:
Publish/Generate Script should be enabled because all required fields are completed

Reality:
Publish/Generate Script are disabled, typing anything in Database field enables them

**Comment by kisantia** [comment]
moved to November since there's a workaround to enable and this isn't a regression

**Comment by kisantia** [comment]
also happens without publish profile. Can repro by: 
1. open publish dialog
2. change database name in editable dropdown
3. select server connection

the targetDatabaseDropdown.value is returning undefined even though it does have a value in the UI
