### ISSUE TITLE
No message when adding new (different) db reference to sqlproj that's already referenced

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#12811]
Not sure if it's replacing/updating the existing reference or not changing anything because it's already ref'ed.  Probably should have a toast saying "Reference to <project> already exists; would you like to update it with the new settings?" or something.

Question: can I have one project (or one dacpac) reused for multiple different databases?  Seems corner-case-y, but not inherently invalid.

**Comment by kisantia** [comment]
I think this should be fixed by https://github.com/microsoft/azuredatastudio/pull/12795 and will be in the extension will be updated later today

**Comment by kisantia** [comment]
confirmed that this was fixed by #12795.

Yup, a project or dacpac can be referenced by multiple projects
