### ISSUE TITLE
Sort columns in Result set

### ISSUE THREAD

**Issue by markingmyname** [microsoft/azuredatastudio#12822]
Azure Data Explorer web tool and Kusto Explorer allow you to sort the columns in the result set, however, we cannot sort columns in Azure Data Studio.

Can we add this functionality?

Here is a screenshot of a result set with column headings as an example.

![image](https://user-images.githubusercontent.com/22989000/95504727-d2a6ca80-0972-11eb-8f33-475b8c41a14a.png)

Thank you.

**Comment by NerdicSQL** [comment]
I would like to add that this is a functionality that would be incredibly useful on the notebook side as well (which maybe uses the same result grid code?).

Other notebooks enable the sorting of results within the raw table views by clicking a column to toggle the sort order ascending or descending, which I find to be an incredibly useful way of preventing the same query from having to be rerun multiple times with different predicates during analysis.

For reference, Databricks Notebooks looks like this when sorted descending on my second column in my example notebook.
![image](https://user-images.githubusercontent.com/41307046/95594419-cbe78880-0a42-11eb-9c2e-62b02c918a4d.png)

**Comment by alanrenmsft** [comment]
You can sort the columns using the column menu or using the shortcut key (SHIFT+ALT+O) to sort the columns, the keyboard shortcut will be available in next release. and the colum menu is already available.
