### ISSUE TITLE
options/required tools information overlaps card.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12820]
Saw the following for the deployments landing page on main:

![image](https://user-images.githubusercontent.com/41588310/95501522-4a69fa80-095d-11eb-8f83-99d23ea00bd2.png)

I wonder if this is an issue because I have a 'sample deployment card' installed or is it an issue with us having more than 9 cards?

**Comment by ranasaria** [comment]
OK this was found to be happening only when we have too many cards. When I removed two cards from my installed extension to come down to 8 cards this issue did not repro.

There was a second more critical issue observed with I had more than 8 cards. As can been seen from the originally attached picture, with  any of 'Azure Arc Data Controller', 'Azure SQL managed instance - Azure Arc (preview)' or 'PostgreSQL Hyperscale server groups - Azure Arc (preview)' card selected, the load of the tools table was hanging with 'Loading required tools information' message spinning forever.

Reducing priority since in production we currently do not have more than 9 cards. We should fix this soon as it is a ticking timebomb which will surface as soon as a couple of more cards are added.

**Comment by aasimkhan30** [comment]
Closing this since it is a not an issue now.
