### ISSUE TITLE
Import Flat file wizard

### ISSUE THREAD

**Issue by rmanthey99** [microsoft/azuredatastudio#12831]
After selecting the csv file and updating data types the import just gets hung up and never loads into a new table.  I have restarted the process numerous times and have gotten the same results. Today when I opened azure data studio it did update to the newest version 1.22.1 9/29/2020 release

**Comment by dzsquared** [comment]
@rmanthey99 this looks like an issue that is fixed in the upcoming release (#12624 )

the fix is available in the Insiders build already, which you can grab here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by aasimkhan30** [comment]
The bug is fixed in the latest release. Closing this issue.
