### ISSUE TITLE
New Query from Kusto Cluster in Azure Viewlet doesn't Connect

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#12841]
From the Azure viewlet (contact me if you need more info), right clicked on a Kusto cluster and chose "New Query". Got the following error:

![image](https://user-images.githubusercontent.com/40371649/95533056-04ca2380-0997-11eb-8191-0ef10997f2e6.png)

**Comment by JustinMDotNet** [comment]
Reached out to Chris for steps to reproduce:

![image](https://user-images.githubusercontent.com/63619224/97623032-52f4a480-19e2-11eb-95d2-78da2921d769.png)
