### ISSUE TITLE
WYSIWYG does not provide an option for creating a link

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12859]
WYSIWYG edit mode does not provide an option for inserting a link, need to switch to Split View. 
![Screen Shot 2020-10-09 at 11 13 10 AM](https://user-images.githubusercontent.com/34872381/95617516-6bdfea80-0a20-11eb-8843-318ea1659494.png)

- Azure Data Studio Version:
Version: 1.23.0-rc1
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:40:51.445Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create a text cell and the toolbar does not provide a link option.

**Comment by chlafreniere** [comment]
@barbaravaldez this is by design for now. Links + images coming soon(tm).

However, I don't think that we had an issue tracking this. So let's move it to November 😄

**Comment by MsSQLGirl** [comment]
Note: this issue fixes the crawl experience that @VasuBhog  worked on. 
https://github.com/microsoft/azuredatastudio/issues/14151#issuecomment-790050558
