### ISSUE TITLE
WYSIWYG Inconsistency when highlighting text in code format

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12877]
- Azure Data Studio Version:
Version: 1.23.0-rc1
Commit: 7429407029af2e08d17a8928825815cffad94f17
Date: 2020-10-09T00:40:51.445Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:
1. Add a text cell in a notebook
2. Insert code and type something
3. Select the text and highlight it.
**First case**
4. If you switch to Markdown or Split View and then return instead of seeing a highlighted element it'll contain the markdown tags <mark></mark>
**Second case**
4. If you exit the edit mode, the highlight will be removed.

**Comment by chlafreniere** [comment]
Tracked with #12467.
