### ISSUE TITLE
Intellisense missing TSQL "DISTINCT" in Autocomplete

### ISSUE THREAD

**Issue by sebcruz** [microsoft/azuredatastudio#1289]
- SQL Operations Studio Version:

Steps to Reproduce:
type the text:
select distinct

Intellisense will colorize the text properly as a keyword for TSQL once fully typed out, but the Autocomplete is not recognizing it as a keyword.  It does bring up two options: 
     approx_count_distinct
     dm_fts_index_keywords_position_by_document 

but never the word distinct.  This is true even when partially typing the word distinct out.  I never see it as a real option to take advantage of the tab to autocomplete.

![image](https://user-images.githubusercontent.com/7232985/39387682-d0c99d46-4a2f-11e8-9c52-a68503282741.png)

**Comment by kburtram** [comment]
The SQL Parser will only provide keyword suggestions if there are no schema based suggestions.  Fixing requires upstream changes to the SQL Parser component.

**Comment by sql-koala** [comment]
I added this to my sql snippets. It's a good workaround, imo.

```
	"distinct": {
		"prefix": "distinct",
		"body": [
			"DISTINCT "
		],
		"description": "DISTINCT"
	},
```

**Comment by kburtram** [comment]
@sql-koala that's a nice workaround for this bug.  Thanks!  I'm going to close this older bug as "upstream" as the parser code is tracked in a different code base.
