### ISSUE TITLE
Password confirmation validation message does not vanish when password text field changes

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#12891]
When entering a password and confirm password field information on the azure arc data controller create screen, if a user enters a password incorrectly then upon trying to navigate to next page, an error shows up as below. However, this error does not vanish as the user starts typing in new password information. It gets revalidated only when the user tries to navigate out of that page again.
![image](https://user-images.githubusercontent.com/41588310/95771569-244f9d80-0c70-11eb-81f6-bc3bad7b53bd.png)

**Comment by kburtram** [comment]
@ranasaria is this needed for Nov and is the fix on track for end of week?

**Comment by ranasaria** [comment]
No. Moved it.

**Comment by chlafreniere** [comment]
Since this was moved to a different release, removed the Approved label.

**Comment by Charles-Gagnon** [comment]
The message is updated as the user types - removing it once the two fields match. 

(this should really be using the inputbox validation but that's a separate issue)
