### ISSUE TITLE
WYSIWYG Notebook - Updating a cell with relative path causes removal of the paths

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12899]
- Azure Data Studio Version:
Version: 1.23.0-rc1 (user setup)
Commit: 05615c796db46a766f62ffd90b4d78553b75e2d9
Date: 2020-10-12T18:54:16.767Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open an existing notebook with a relative path. See attached file (last cell).
2. Click edit on the text cell with a relative path. 
3. Switch to markdown **Split view** mode. You'll see the actual relative path value.
4. Switch back to **Rich Text** mode. Type in a new text in a new line.
5. Exit out of edit mode in the text cell. 
You'll now see that the relative paths are removed. i.e. no hover on links.
When you edit, you'll also see that the link has been removed both on the **Rich Text** and the **Split view** modes.

File for testing:
[KUS001 - Check Kqlmagic installation.txt](https://github.com/microsoft/azuredatastudio/files/5372639/KUS001.-.Check.Kqlmagic.installation.txt)
![EditCausesBadRelativePath](https://user-images.githubusercontent.com/6405919/95887088-4ad70c80-0d34-11eb-9a65-380dd71b130a.gif)

The workaround is for users to always remember to use **Split View** or **Markdown** mode. But because the default mode is Rich Text view, this will significantly impact users with files where text cells have relative paths.

**Comment by Charles-Gagnon** [comment]
@barbaravaldez - Not sure if this is related to https://github.com/microsoft/azuredatastudio/pull/12802. Could you take a look at this?

**Comment by MsSQLGirl** [comment]
Note: I see this behavior in RC1. Also, it seems that it's affecting those paths with "%20" as show on the sample file. 

Exhibit 1 -  For paths **with** "%20"
`* [KUS002 - Querying internal Kusto clusters with Kqlmagic](.\KUS002%20-%20Querying%20internal%20Kusto%20clusters%20with%20Kqlmagic.ipynb)` will become `[KUS002 - Querying internal Kusto clusters with Kqlmagic]()`

Exhibit 2 - For paths **without** "%20"
`[KUS003 - Kqlmagic in ADS Demo](.\KUS003-Kqlmagic-in-ADS-Demo.ipynb)` will become `[KUS003 - Kqlmagic in ADS Demo](KUS003-Kqlmagic-in-ADS-Demo.ipynb)` where `.\` is removed.

**Comment by VasuBhog** [comment]
I can help look into this as well as it seems to be a high priority WYSIWYG bug.

**Comment by Charles-Gagnon** [comment]
@VasuBhog Thanks - could you and @barbaravaldez  sync up and work on this?

**Comment by VasuBhog** [comment]
Hi, @MsSQLGirl I am only seeing the behavior when the `.\` is removed after following the same steps (I am using a Mac). I do believe that this issue is focused on the windows path and the `.\`. I will continue to investigate with @barbaravaldez. 

![relative_path](https://user-images.githubusercontent.com/23587151/95903291-918c2d00-0d5b-11eb-82dd-8ed65aeb2eb7.gif)

**Comment by VasuBhog** [comment]
This is not a regression, as it also happens in the current stable version of ADS (September release).

**Comment by sredman** [comment]
Is there a setting to disable the rich text editing or make it not the default? I keep scrogging my files by editing them and not noticing that I'm in rich text mode.

**Comment by VasuBhog** [comment]
Hi @sredman, yes you are able to uncheck the setting "Set Rich Text View By Default" in the settings. Therefore making your default for text cells be Markdown viewer instead.

![image](https://user-images.githubusercontent.com/23587151/95919061-898bb780-0d72-11eb-84a1-4ea225f03ee1.png)
