### ISSUE TITLE
Connection Dialog Browse Tab issues

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#12909]
This is the master issue to track all work items as well as the issues found for the browse tab during internal testing.

General:

- [x] filtering is not implemented
- [x] scrollbar not visible when needed
- [ ] allow refreshing of specified nodes
- [x] put the feature behind preview flag
- [x] update the browse tab's title to 'Browse (Preview)'
- [x] the tree is not theme aware.
- [x] use folder icon for Saved Connections, Azure and connection groups

Saved connections:

- [x] no icon for entries in saved connections
- [x] entries remain 'loading...' even after the connection provider extension is installed, OE gets updated properly in this case
- [x] newly added connections or server groups are not reflected here, have to reload to make them show up.
- [x] remove the color on the connection groups

Azure:

- [x] top level account grouping
- [x] no indicator that the resources are being loaded
- [x] bring the azure context menus to the new tree
- [x] show more information for azure nodes - include type and subscription name
- [x] start cloudshell command - add account picker step

**Comment by jaredrdavis** [comment]
![image](https://user-images.githubusercontent.com/5952945/97632218-72de9500-19ef-11eb-875d-3c7918d9c6b0.png)
Here's how I was thinking the refresh and filter icons could be represented on the account level.
