### ISSUE TITLE
Handling JSON data within SQL Notebook

### ISSUE THREAD

**Issue by kentmaxwell** [microsoft/azuredatastudio#12918]
My request is related to working with JSON data in SQL Server.  When I write a query in a normal query window that returns JSON data I am able to click on that JSON in the results plane.  This causes another window to open showing the entire JSON message, well-formatted.  If I do the same action in a SQL Notebook, I am unable to click on or otherwise explode JSON data from a result.  

My feature request is to see that possibility exists in a SQL Notebook.

I created a video that demonstrates this situation:  [Video](https://www.screencast.com/t/UtGDO8sz2p)

**Comment by chlafreniere** [comment]
This makes a lot of sense. Let's see if we can address this soon. @lucyzhang929 assigning to you when you have capacity

**Comment by lucyzhang929** [comment]
Hi @kentmaxwell, this feature should be available now in the latest Insiders build.

@chlafreniere We weren't passing the isJson field to the table before, but it's been added with my grid streaming changes.

**Comment by chlafreniere** [comment]
Thanks @lucyzhang929! I'll close this issue then.
