### ISSUE TITLE
validateErrorMessage and placeholder support for Dropdown Component 

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#12923]
The Dropdown Component currently supports withValidation when being created by modelbuilder, however there is no support for validateErrorMessage unlike the Inputbox component, meaning the user won't be able to see why the validation for the dropdown value is invalid or not. 

Additionally there is no support for a placeholder value, which means there must be an actual value in the dropdown or its blank,

There should be support for validation of the dropdown values so that if the value is invalid, the user would know why its wrong, and there should be the option for placeholder values as well (in case the user doesn't want the dropdown to be blank, but it doesn't hold an actual value)

External messages and error checking are required to show why a dropdown value is invalid, and it is inconsistent with input boxes.

Dropdown screenshot:
![Dropdown validation screenshot](https://user-images.githubusercontent.com/18018452/96034562-919d3300-0e16-11eb-8d0a-31a8e2af78b1.png)

Inputbox screenshot:
![Inputbox validation screenshot](https://user-images.githubusercontent.com/18018452/96034593-9e218b80-0e16-11eb-8822-429a61e3c654.png)

**Comment by kburtram** [comment]
Closing older API level bugs to focus on customer-facing bugs.  Please open a bug against the dialog that is impacted by this API issue.  Thanks!
