### ISSUE TITLE
WYSIWYG and swithcing to markdown causing issues with deletion of text that have "<" and ">"

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#12931]
- Azure Data Studio Version:
Version: 1.23.0 (system setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a text cell in a notebook.
2. Type `\<testing1\>` in the **Split View** mode.
3. Switch to **Rich Text** mode. Exit out of editing mode.
4. Add a new text underneath the line - say "awesome". Switch to Markdown. Exit out of editing mode.
What you'll see:
The rich text mode removed the `\<` and`\>`.
Going back and forth will cause removal of the entire `\<testing1\>` word. 

This is a breaking change for existing users that may be using this form a lot.
 
![BreakingChangeWithLessThanGreaterThan](https://user-images.githubusercontent.com/6405919/96067406-8960ea00-0e4e-11eb-92a4-ae59173cd52e.gif)

Expected: no removal of `\<` and`\>` in markdown when switching back and forth. No removal of texts.

**Comment by MsSQLGirl** [comment]
@barbaravaldez , @VasuBhog - the behavior of removing texts when switching back-and-forth Split View and Rich Text modes is similar to #12899.

**Comment by VasuBhog** [comment]
@MsSQLGirl this also repros in the September release. Therefore, not a regression. However, I do believe that this is tied to the issue that @barbaravaldez is currently working on (the one you linked). We will aim to fix these for the November release.

**Comment by halerankin** [comment]
It's removing what can be interpreted as HTML tags. This happens when the turndown service converts markup into rich text.
