### ISSUE TITLE
Filter / Search Databases, Tables, Stored Procedures etc. in the Connections Side Bar

### ISSUE THREAD

**Issue by jsn-m** [microsoft/azuredatastudio#12932]
**Is your feature request related to a problem? Please describe.**
It takes time to scroll through hundreds of tables in the Connections Side Bar to find a table and look at column definitions, while I work on a query in the Query Editor.

**Describe the solution or feature you'd like**
I would like to be able to search or filter the databases, tables, stored procedures etc. within the Connections Side Bar, to quickly find the object I am looking for. An implementation similar to SSMS's (right-click on object) filter would suffice.

**Describe alternatives you've considered**
I have used the dashboard to search but it doesn't work well (speed wise) and doesn't show column or structure definitions from a drop down.

**Additional context**
The image below illustrates the view which I would like to filter in the Connections Side Bar.
![image](https://user-images.githubusercontent.com/28594877/96081621-ffe70180-0eb9-11eb-829b-b1287aeca0fa.png)

The image below shows the existing SSMS feature that I would like to see implemented.
![image](https://user-images.githubusercontent.com/28594877/96081586-e80f7d80-0eb9-11eb-8586-9940ed3ab797.png)

**Comment by pacorreia** [comment]
This is really a important missing feature, at least for me where govern objects by schema

**Comment by mammadkoma** [comment]
How we can filter tables like SSMS by right click on Tables folder?

**Comment by Vaelek** [comment]
This is an invaluable and seemingly simple feature to implement. A free text field above everything that we can type into and just filters the resulting tree accordingly would be amazing. Please do not relegate it to a context menu like SSMS.

**Comment by Desmo46** [comment]
Would love to see some progress on this, a simply function but makes using ADS very difficult to use without.

**Comment by bdparkhurst** [comment]
Would love to see this get in there!

**Comment by nigel108** [comment]
I also logged a ticket like this one,  hoping they add it in.

**Comment by gregmousseau** [comment]
+1 for this feature. Trying to find a specific field in an unfamiliar database with hundreds of tables is a needle in a haystack. Going to try SSMS instead.

**Comment by mjdjunk** [comment]
It's hard to believe Microsoft has ignored this for almost 2-1/2 years.  I agree with everything every member has mentioned above.  And having to use the "Manage" tab is painful.  Not having the same functionality from SSMS' object explorer in the Connections pane in AZD is...a pain.  Why would Microsoft remove functionality that so many users have relied on for years is something I don't understand.  But, it's also very typical of Microsoft to just do what they want and ignore what users want.

**Comment by Johannes-Vink** [comment]
I use SMMS in combination with a datawarehouse with I don't know like 5000+ database objects. I use the filter functionality in SSMS extensively. Every time scrolling through the list in ADS makes me run back to SSMS.

**Comment by strandloper** [comment]
I had thought I would like to see schema as a subgroup of tables in the tree, but a filter with the ability to select only specific schemas would work as well.

**Comment by onuromer** [comment]
That is one of the reasons why I don't use Azure Data Studio. If an application is not capable of handling common daily tasks, it wont get accepted. And you cant keep installing an extension for everything, even for the most crucial functionality. Some things need to be built-in.

**Comment by alleycat58uk** [comment]
Any update on this enhancement request? It would improve usability massively

**Comment by pacorreia** [comment]
I think that maybe only a  connection with the Product group owning this
one will actually be able to provide feedback and prioritize.

But sometimes they seem really unreacheable.

A sábado, 18/03/2023, 14:07, Paul Griffiths ***@***.***>
escreveu:

**Comment by lucky-ly** [comment]
This.
I can't comprehend, how Microsoft with all their resources still can't implement such a basic feature in 2023. And one single guy behind HeidiSQL nailed it a decade ago or maybe even earlier.
And SSMS... Well, at least it has some way of filtering tables and columns, but HeidiSQL's implementation is superior IMO - it's right there, just text field above tables list, it works instantaneously and it supports wildcards, so I can type something like `chat|user` and immediately see tables that I need in the list: `chatrooms`, `chatroom_to_users`, `users`.

Would be so great if ADS finally got this feature...

**Comment by aasimkhan30** [comment]
Filtering was added in #22937 and will be available for the May release.

**Comment by bdparkhurst** [comment]
WHOOO HOOO!  Thank you!
