### ISSUE TITLE
Open Python Installation in Terminal

### ISSUE THREAD

**Issue by Calidus** [microsoft/azuredatastudio#12943]
**Is your feature request related to a problem? Please describe.**
Getting an existing python notebook up and running in Azure Data Studio can be frustrating when you have multiple python installations. I spent a embarrassing amount of time installing modules into the wrong python environment.

**Describe the solution or feature you'd like**
I want a easy way to navigate to the python installation that Azure Data Studio is using, so I can run pip to install modules. Something like "Open Python Installation in Terminal."

Making the kernel dropdown more descriptive would also be helpful. 

Examples:
Python 3 - Azure Data Studio
Python 3 - External

**Comment by chlafreniere** [comment]
Hi @Calidus we have a package management dialog that we

**Comment by Calidus** [comment]
I was unaware of this feature, it looks like a solution to my problem.
