### ISSUE TITLE
Typos in deployment flow

### ISSUE THREAD

**Issue by ninarn** [microsoft/azuredatastudio#12954]
- Azure Data Studio Version: Stable/GA build

Steps to Reproduce:

1. Open Connection viewlet
2. Click "..." in Connection view
3. Click "New deployment"
4. Select "Azure SQL" tile

Issues in Azure SQL Database flow:
- Tile titled "Azure SQL" should be titled "Azure SQL Database" and description should be "Create a SQL database, database server, or elastic pool in Azure."
- Button in bottom right should say "Select" when "Single database" is selected to match experience for other similar selections
- Sentence casing should be used:
        - Dropdown options should be sentence cased, i.e. "Single database", "Elastic pool", "Database server"
        - Wizard step 1 - title should be sentence cased - "Azure SQL Database - Azure account settings"
        - Wizard step 1 - "Azure Account" should be "Azure account"; "Sign In" should be "Sign in"
- Wizard step 2 - Firewall rule should be optional
- Wizard step 2 - Add a description somewhere (bottom of page?) saying "Create a firewall rule for your local client IP in order to connect to your database through Azure Data Studio after creation is completed."

**Comment by aasimkhan30** [comment]
@ninarn I am closing this issue. I will use #12955 to track the issues in insiders.
