### ISSUE TITLE
Cannot add MFA credentials

### ISSUE THREAD

**Issue by talinas** [microsoft/azuredatastudio#12957]
Issue Type: <b>Bug</b>

1. MFA Add new account functionality doesn't trigger account setup dialog. 
2. 'Clear all saved accounts' doesn't do anything (old creds stay after executing this command)

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (15.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cssuh** [comment]
#12448 duplicate
