### ISSUE TITLE
Drag n drop : fields

### ISSUE THREAD

**Issue by opernes** [Microsoft/azuredatastudio#1295]
Issue Type: <b>Feature Request</b>

hello,

We really would need the drag and drop fonctionnality : on a field (column, table...) , drag n drop on the scripting window : auto typing the name of the field. 

Or in addition, a double-clic option.

Thanks in advance ! 

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.16299

**Comment by anthonydresser** [comment]
dupe #793
