### ISSUE TITLE
date format problem

### ISSUE THREAD

**Issue by luismiguelgilbert** [microsoft/azuredatastudio#1296]
Issue Type: <b>Bug</b>

on results grid, when a string column contains a string date (such as 2018-04-27T18:33:55.870Z), then it will be automatically formatted as 04/27/2018 18:33:55 or whatever my dateformat is... 
This is a bit confusing because it is a string column, and should be displayed as a string (not as a date).

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|Memory (System)|15.70GB (7.93GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|50%|

</details>Extensions: none
Reproduces without extensions

**Comment by kburtram** [comment]
@MattIrv I think your pending PR https://github.com/Microsoft/sqltoolsservice/pull/663 should also fix this?

**Comment by kburtram** [comment]
@MattIrv actually it looks like your change doesn't resolve this.  I guess your change is for deserialization and this issue is on the serialization side.

**Comment by anthonydresser** [comment]
We could probably implement this has a setting, since we try and be smart and auto format fields we recognize.

**Comment by smartguest** [comment]
From the current build, this problem no longer happens when I attempt to repro it with a varchar table.

@luismiguelgilbert Have you still encountered this issue with the latest build? Let us know if you do.
