### ISSUE TITLE
Linked account name with encoding issue

### ISSUE THREAD

**Issue by t-mxcom** [microsoft/azuredatastudio#12988]
Issue Type: <b>Bug</b>

I connected Azure Data Studio to my Microsoft work account.
My familyname is "Eßmayr" but the second letter ß (sharp s, eszett, `&szlig;`) isn't displayed correctly.

![AzureDataStudio-LinkedAccounts-EncodingProblem](https://user-images.githubusercontent.com/34266991/96431621-1071e180-1204-11eb-9027-330fa3242bad.png)

Thanks for fixing this issue!

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.37GB (19.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0

</details>

**Comment by cssuh** [comment]
#12629 duplicate
