### ISSUE TITLE
A11y_SQL Azure Data Studio_Select an Operations_ScreenReader: Irrelevant Information is announced when we select radio buttons using Tab key

### ISSUE THREAD

**Issue by khansahab15** [microsoft/azuredatastudio#12983]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) – Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**: #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudio_Oct2020; #SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG1.3.1;#Benchmark;#NVDA;#JAWS;#AINotInScope;

**Environment Details:**
Application Name: SQL Azure Data Studio
Version 1.22.1 User Setup
Windows Version: Windows10
Screen reader: NVDA2020.3

**Repro Steps:**

1. Launch Azure Data Studio.
2. Connect to server.
3. Search & install Dacpac extension.
4. Navigate to 'Connections' Panel.
5. Expand the server connected in step 2.
6. Right click/ Open the context menu for database and select Data-tier application wizard from the context menu.
7. Launch screen reader as NVDA and tab to radio button and observe what Screenreader is announcing

**Actual:**
On navigating to the radio buttons using tab Key irrelevant information "Step1 select an operation" is announced 

**Same issue is observed with JAWS**

**Expected:**
On navigating to the radio buttons using Tab key irrelevant information like  "Step1 select an operation" should not be announced 

**User Impact:**
The screen reader users will get irrelevant information 

**Attachment:**
[12983_A11y_SQL.Azure.Data.Studio_Select.an.Operations_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/5401525/12983_A11y_SQL.Azure.Data.Studio_Select.an.Operations_ScreenReader.zip)

**Comment by kapilvaishna** [comment]
**GithubTags**:#Closed;
**GithubTags**:#Regressed:03-02-23;

https://user-images.githubusercontent.com/124254981/217530271-273d290d-d2f9-483d-a7fe-dd3c3d929d59.mp4
