### ISSUE TITLE
href  attribute removed from untrusted notebooks

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#12990]
Links are only clickable on Mac and Trusted Windows Notebooks.
Encounter this issue when fixing [12899](https://github.com/microsoft/azuredatastudio/issues/12899).
On Windows, the href attribute is removed from the element if it contains an URI-encoded absolute path when sanitizing the contents. 
This only happens with untrusted notebooks on Windows.

**Comment by chlafreniere** [comment]
Hmm, I'm a little confused. Does this only happen on Windows or also on Mac?

Links being sanitized away is by design.

**Comment by chlafreniere** [comment]
Closing as by design.
