### ISSUE TITLE
Feature Request: Azure Active Directory Authentication

### ISSUE THREAD

**Issue by orofino** [Microsoft/azuredatastudio#13]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Create new connection
2. Select Authentication Type

**Comment by kevcunnane** [comment]
To clarify: is this request for Azure Active Directory (integrated and password) authentication? @saurabh500 can help comment on this if so.

**Comment by Code-DJ** [comment]
My iMac is connected to windows domain. I login to the mac using domain credentials. When I try to connect using windows authentication, I get the following error:


System.Data.SqlClient.SqlException (0x80131904): Cannot access Kerberos ticket. Ensure Kerberos has been initialized with 'kinit'.
ErrorCode=InternalError, Exception=Interop+NetSecurityNative+GssApiException: GSSAPI operation failed with error -  An unsupported mechanism was requested (unknown mech-code 0 for mech unknown).
   at System.Net.Security.NegotiateStreamPal.GssInitSecurityContext(SafeGssContextHandle& context, SafeGssCredHandle credential, Boolean isNtlm, SafeGssNameHandle targetName, GssFlags inFlags, Byte[] buffer, Byte[]& outputBuffer, UInt32& outFlags, Int32& isNtlmUsed)
   at System.Net.Security.NegotiateStreamPal.EstablishSecurityContext(SafeFreeNegoCredentials credential, SafeDeleteContext& context, String targetName, ContextFlagsPal inFlags, SecurityBuffer inputBuffer, SecurityBuffer outputBuffer, ContextFlagsPal& outFlags)
   at System.Data.SqlClient.SNI.SNIProxy.GenSspiClientContext(SspiClientContextStatus sspiClientContextStatus, Byte[] receivedBuff, Byte[]& sendBuff, Byte[] serverName)
   at System.Data.SqlClient.SNI.TdsParserStateObjectManaged.GenerateSspiClientContext(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength, Byte[] _sniSpnBuffer)
   at System.Data.SqlClient.TdsParser.SNISSPIData(Byte[] receivedBuff, UInt32 receivedLength, Byte[]& sendBuff, UInt32& sendLength)
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, Object providerInfo, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.<>c__DisplayClass22_0.<TryGetConnection>b__0(Task`1 _)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ReliableConnection.ReliableSqlConnection.<>c__DisplayClass28_0.<<OpenAsync>b__0>d.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ReliableConnection\ReliableSqlConnection.cs:line 298
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.<TryOpenConnection>d__46.MoveNext() in C:\J\jobs\sqltoolsservice_master_win\workspace\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 542
ClientConnectionId:719fbb11-e2be-46ca-b44c-fb57f4179fd6

**Comment by Code-DJ** [comment]
Additionally, I have followed the instructions for the mssql extension of vscode and still get the error:

klist shows the following:

Credentials cache: API:40D6C9CB-493E-4FEB-A227-1B551220F829
        Principal: username@DOMAIN.COM

  Issued                Expires               Principal
Nov 15 10:30:32 2017  Nov 15 20:30:32 2017  krbtgt/DOMAIN.COM@DOMAIN.COM
Nov 15 10:42:06 2017  Nov 15 20:30:32 2017  HTTP/server1.domain.com@DOMAIN.COM
Nov 15 10:53:15 2017  Nov 15 20:30:32 2017  HTTP/server2@DOMAIN.COM

**Comment by orofino** [comment]
@kevcunnane yes, correct.

**Comment by Code-DJ** [comment]
@kevcunnane since this is Azure related do you want me to move my comments to a separate issue? Thanks!

**Comment by saurabh500** [comment]
@orofino @Code-DJ  the Azure Integrated auth support needs to get into .Net Core for the tools to use it. There is an open issue at https://github.com/dotnet/corefx/issues/8807 and we are trying to work with security team to support FedAuth on .Net Core 
Are you looking for Azure Active Directory username and password support or Azure Active Directory Integrated Authentication support?

**Comment by orofino** [comment]
@saurabh500 I'm looking for username/password support.

We have an Azure SQL Database with Azure AD security groups governing access. It would be great to allow users in those groups to use this application without having to create local SQL accounts.

**Comment by kevcunnane** [comment]
@Code-DJ yes, please create a separate issue for Windows authentication issues. Again that's mostly going to be upstream (e.g. improve error messages in the SqlClient driver, improve the drivers reliability) but will let us track it cleanly.

**Comment by mmoizk** [comment]
I didn't see any voting button , so please consider my comment here as my request and vote for this feature. SSMS 17 does it great.

**Comment by orofino** [comment]
@mmoizk you may want to thumbs up the linked issue (dotnet/corefx#8807) as it seems the team there is referencing those for prioritization.

**Comment by sebcruz** [comment]
Please consider my comment as an Up Vote for this.  Please add the same AAD authentication options as are currently available in SSMS.

**Comment by Code-DJ** [comment]
Should the title be changed to Azure Active Directory Authentication for clarity?

**Comment by kevcunnane** [comment]
@Code-DJ  done.

**Comment by Ocanamat** [comment]
Great tool guys. Please also consider this comment as my up vote for this feature request. Thanks!

**Comment by pmooij** [comment]
Azure AD MFA, yes please!

**Comment by CoreyCaldwell** [comment]
And another vote for AD MFA

**Comment by acds** [comment]
+1

**Comment by Svengalx** [comment]
+1

**Comment by B4PJS** [comment]
Need MFA authentication

**Comment by kevinvngo** [comment]
+1

**Comment by jmaragon** [comment]
please, ad Active Directory MFS support to this great tool

**Comment by TwoUnder** [comment]
+1

**Comment by MLFlakus** [comment]
+ 1

**Comment by jharris8567** [comment]
+1

**Comment by atfernando** [comment]
+1

**Comment by RanjithkumarRagavan** [comment]
+1

**Comment by YogeshPraj** [comment]
+1

**Comment by kplantus** [comment]
+1 for AAD w. MFA support.

**Comment by addp009** [comment]
+1

**Comment by rameezrajas** [comment]
+1

**Comment by slicc** [comment]
+1

**Comment by artsai** [comment]
+1

**Comment by jboarman** [comment]
@saurabh500 @kevcunnane @erickangMSFT

Now that [.NET Core 2.2 has added AccessToken support](https://github.com/dotnet/corefx/issues/13660#issuecomment-413921458), does that provide sufficient ability to support Azure MFA login support in SQL Ops Studio?

**Comment by MattIrv** [comment]
@kburtram this is assigned to you right now, are you working on it for October? If not I can grab it since the .NET Core preview release should support AAD now

**Comment by kentongray** [comment]
@mattlvr @kburtram is this actively being worked on? Feel so close!

**Comment by snbcdev** [comment]
Excited that I may be able to try out this new tool soon! Once I can connect to our Azure SQL DBs with AD+MFA, that is.

**Comment by schalkje** [comment]
+1 for MFA

**Comment by anbudhanush** [comment]
hi guys, 
when this feature is expected to be released ?

**Comment by PaulStirpe** [comment]
The tools is not really useful without Active Directory Integrated Authentication and better yet Active Directory Universal Authentication with MFA. Looking forward to this feature being implemented.

**Comment by thanksforthepen** [comment]
> To clarify: is this request for Azure Active Directory (integrated and password) authentication? @saurabh500 can help comment on this if so.

11/19/2018 - Did this ever happen? I'd love to have people login with their AAD username and password.

**Comment by yualan** [comment]
Keep an eye out for the next monthly release. When we have an insider build out, feel free to try it out and let us know if there are any gaps with the feature.

**Comment by yualan** [comment]
![image](https://user-images.githubusercontent.com/30873802/49131872-ac03ad00-f28e-11e8-8b79-86ab33f7a252.png)

Thanks to @MattIrv and @kburtram, AAD is now in the latest Insider build (1.3.4). Please try it out here and give us feedback before we include it in the December stable release: https://github.com/Microsoft/azuredatastudio/releases

**Comment by yellowianox73** [comment]
Is there 1.3.4 for Windows?

**Comment by yualan** [comment]
@yellowianox73 Yes, the Windows installer link works for me and confirmed will download 1.3.4 even though it lists as 1.1.4. Will get this changed.

**Comment by yellowianox73** [comment]
Yeap it works! but for some reasons I have cleared out the SQL authentication!

**Comment by orofino** [comment]
This is looking good to me! 1.3.4-insider on MacOS Mojave 10.14.1. Thanks for much for adding.

**Comment by kburtram** [comment]
Closing since this feature is available in https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.6 and will be included in the December release planned for 12/12.

**Comment by sergiokoval** [comment]
doesn't seem it supports "Azure Active Directory - Password" type of authentication. Any plans to have this feature as well?

**Comment by sqlarcher** [comment]
> doesn't seem it supports "Azure Active Directory - Password" type of authentication. Any plans to have this feature as well?

Unless you have not found it, you can under "Authentication Type" just select "Azure Active Directory - Universal with MFA Support" and this will work the same as "Azure Active Directory - Password". This is available since the December release of Azure Data Studio.

**Comment by sergiokoval** [comment]
> > doesn't seem it supports "Azure Active Directory - Password" type of authentication. Any plans to have this feature as well?
> 
> Unless you have not found it, you can under "Authentication Type" just select "Azure Active Directory - Universal with MFA Support" and this will work the same as "Azure Active Directory - Password". This is available since the December release of Azure Data Studio.

**Comment by sergiokoval** [comment]
> > doesn't seem it supports "Azure Active Directory - Password" type of authentication. Any plans to have this feature as well?
> 
> Unless you have not found it, you can under "Authentication Type" just select "Azure Active Directory - Universal with MFA Support" and this will work the same as "Azure Active Directory - Password". This is available since the December release of Azure Data Studio.

thanks for your reply! Yes, I can see that option but it doesn't provide me with entering username/password after.  There is empty Account dropdown but no way to type username and password. Was looking for something similar to this window in sql management studio:
![image](https://user-images.githubusercontent.com/31712183/50766911-3b7f8100-127b-11e9-8086-a5bbb9677f54.png)

Am I missing something?

I'm using 1.3.7 insider version.

**Comment by kburtram** [comment]
@sergiokoval I'm not sure if that authentication method was implemented in the .Net Core AAD support.  @MattIrv do you know the details why we only support "Universal with MFA".

**Comment by MattIrv** [comment]
@sergiokoval The account dropdown that shows up there should have an option to "Add an account", which will open a dialog with instructions on how to log into your account. Is that option missing for you?

**Comment by MattIrv** [comment]
We're also tracking support for password authentication in this issue: https://github.com/Microsoft/azuredatastudio/issues/2814. However looking at discussions around username/password auth (e.g. https://github.com/AzureAD/azure-activedirectory-library-for-nodejs/pull/99) it seems like they're pushing for everyone to use web login. So I still need to understand whether there are truly scenarios where users can't use web login and whether our ADAL library actually supports username/password authentication

**Comment by sergiokoval** [comment]
hi @MattIrv , the option "Add an account" appeared but nothing happened when I click on it. But after I tried to disconnect from corporate network and switched to regular public connection. So it took me to the device login page eventually. 
Seems its not "firewall friendly".  However no issues authenticating against azure in other apps using the same methods.
