### ISSUE TITLE
Create Jupyter Book's TOC is not honoring the folder structure of the source files.

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13000]
- Azure Data Studio Version:
Version: 1.23.0 (system setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Download the PrepBook.zip file and extract all. 
2. Run Create Jupyter Book (Preview) feature on the PrepBook folder. 
The book created has book sections that don't match the folder structure:
![image](https://user-images.githubusercontent.com/6405919/96534200-1d162a00-1244-11eb-975e-29d5a79e1a21.png)

Expected:
the TOC should match the folder structure of the source folder.

**Comment by MsSQLGirl** [comment]
@barbaravaldez : FYI.

**Comment by barbaravaldez** [comment]
@MsSQLGirl - Hey Julie, what jupyter-book version are you using for creating the book?
Also, can you share the PrepBook.zip?

**Comment by MsSQLGirl** [comment]
@barbaravaldez I'm using Jupyter-book version 0.8.2. I've sent you the PrepBook.zip file separately. File is a bit large :)

**Comment by barbaravaldez** [comment]
This is issue was fixed in #14210
