### ISSUE TITLE
Return control to CMD console window by default after SQLOps application is closed

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#1300]
- SQL Operations Studio Version:
Version 0.28.5-insider
Commit 3b90530717fa16ae289f6b4255b8f65cb089a893
Date 2018-04-24T03:24:41.772Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Any time if I launch the slops from command line on windows I notice that the command line doesn’t return me the prompt back once the application is closed.I have to manually hit enter or ctrl+c to get back to the prompt. This make the user believe that the process has not completely exited and its doing something in the backend. I was hoping once the process is shutdown the command line prompt should return back

![sqlops_cmdline](https://user-images.githubusercontent.com/27516588/39449211-11d9d5fa-4ce5-11e8-8d4c-d9d5455a7d63.png)

**Filing this issue based on Karl's inputs as follows**
when SQL Ops is launched from a command window it appears to be capturing the consoles STDIO handles, and writing to them after returning control back to cmd.exe.  This behavior is present in the VS Code upstream code, so we’d likely prefer to have the fix applied there.

In the behavior you’re describing it doesn’t sound like the command terminal is frozen.  It’s more likely a STDERR message has been written to the console moving the focus from the input prompt.  Pressing ENTER returns focus back to the input prompt.

Please log a bug and we can work with upstream to understand this issue and where best to fix

**Comment by kburtram** [comment]
Closing older "upstream" issues.  This should ideally be addressed in vscode code base.  Thanks for reporting!
