### ISSUE TITLE
Copy SQL text like the SSMS (color only w/o the background)

### ISSUE THREAD

**Issue by yanivharpaz** [microsoft/azuredatastudio#13005]
I'm using the dark theme on the SSMS and it's very convenient to copy SQL queries from it to emails. even though it's the dark theme, the result on the email body remains with the default coloring of the text (without the dark background).

I think the way SSMS works with it is very useful.
my current workaround - 
Currently when I need to copy a query to emails, I copy and paste it from the ADS to the SSMS and from there into the outlook email.

**Comment by kburtram** [comment]
Closing as upstream since copy/paste behavior is entirely from vscode.  Please log bug on that repro if you're still impacted by this issue.  Thanks!
