### ISSUE TITLE
Difficult to switch datasets when they have long names with same starting characters

### ISSUE THREAD

**Issue by prakashkumarbng** [microsoft/azuredatastudio#13014]
- Azure Data Studio Version:  1.22.1

Steps to Reproduce:

1. Create multiple datasets with similar starting name (which is very much possible in real applications)
  Eg.  LONG_NAME_DATASET_EXAMPLE_1, LONG_NAME_DATASET_EXAMPLE_2, LONG_NAME_DATASET_EXAMPLE_3, LONG_NAME_DATASET_EXAMPLE_4, LONG_NAME_DATASET_EXAMPLE_5
2. Click on dropdown to select dataset and you will find that it is so difficult to find the one you need. You need to hover over each one of them to see what is full name

Fix:
1. Please make the dataset box expandable by user or let it auto adjust width based on dataset length.

**Comment by kburtram** [comment]
I'm unclear which UI you're referring to specifically but I think you mean the Database selector dropdown in the Query Editor.  I believe we widened this dropdown a while back and it seems wide enough to easily accommodate the long names in the bug description (see screenshot below).

For reference, it is also possible to execute `USE [LONG_NAME_DATASET_EXAMPLE_5]` to switch to the database directly without using the DB selector control.  Please let us know if your scenario is still impacted back this issue.

![image](https://user-images.githubusercontent.com/599935/129840755-d4b7440a-aec4-4c53-abef-3b88945171f9.png)

**Comment by prakashkumarbng** [comment]
@kburtram if you remove the big dataset in your screenshot (i.e. DacFxExtractTest.......)  then you will notice the problem.
Yes, I can use the using statement, but if I want to run same query on multiple datasets at random, won't it be easy to select relevant dataset from dropdown instead of typing dataset name each time in using statement?
