### ISSUE TITLE
Server Objects are MIA

### ISSUE THREAD

**Issue by obscurityness** [microsoft/azuredatastudio#13013]
Issue Type: <b>Bug</b>

Since the last upgrade I'm unable to see any objects beneath my Services in the connections pain.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
sqldm-performance-insights|IDE|0.4.0
import|Mic|1.1.0
azdata-sanddance|msr|3.1.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
Is your issue the same as https://github.com/microsoft/azuredatastudio/issues/12992 ?

**Comment by obscurityness** [comment]
Yes, I believe so.

_____________________________________________
Jared Barnes
Partner Program Director
O: +1(669) 262-2674
M: +14048031369
servicenow.com<https://www.servicenow.com/>
LinkedIn<https://www.linkedin.com/company/servicenow> | Twitter<https://twitter.com/servicenow> | YouTube<https://www.youtube.com/user/servicenowinc> | Facebook<https://www.facebook.com/servicenow>

**Comment by Charles-Gagnon** [comment]
I'll close this as a duplicate then - if you can provide any further information such as any errors you see in the logs that would be helpful since this doesn't seem to be a widespread problem.
