### ISSUE TITLE
some times can not connect db 

### ISSUE THREAD

**Issue by oxwanawxo** [microsoft/azuredatastudio#13031]
Issue Type: <b>Bug</b>
the db manager page can not show db or table list,and when I restart it ,sometimes the azuredatastudio worked, sometimes not
![image](https://user-images.githubusercontent.com/5927682/96820146-eadd1600-1457-11eb-8782-fe25e6606d71.png)
 
Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
ads-language-pack-zh-hans|Mic|1.9.0
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
schema-compare|Mic|1.6.0

</details>

**Comment by alanrenmsft** [comment]
@oxwanawxo do you see any error in the development tools console when this happens? you can open it from here: Help menu => Toggle Developer Tools


![image](https://user-images.githubusercontent.com/13777222/97345152-f8731100-1846-11eb-9ea2-bea975fc489b.png)

**Comment by oxwanawxo** [comment]
These infos may help
[cid:image002.png@01D6AD10.9D3449E0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Alan Ren<mailto:notifications@github.com>
发送时间: 2020年10月28日 02:24
收件人: microsoft/azuredatastudio<mailto:azuredatastudio@noreply.github.com>
抄送: Lucifer.WQi<mailto:Lucifer.WQi@outlook.com>; Mention<mailto:mention@noreply.github.com>
主题: Re: [microsoft/azuredatastudio] some times can not connect db (#13031)


@oxwanawxo<https://github.com/oxwanawxo> do you see any error in the development tools console when this happens? you can open it from here: Help menu => Toggle Developer Tools

[image]<https://user-images.githubusercontent.com/13777222/97345152-f8731100-1846-11eb-9ea2-bea975fc489b.png>

―

**Comment by alanrenmsft** [comment]
@oxwanawxo missed your previous reply, but I can't really see the attachment in github, could you please do it using the github website?

**Comment by oxwanawxo** [comment]
@alanrenmsft 
sorry , ,it took so long to reply，and here is the error info
![QQ截图20201209160751](https://user-images.githubusercontent.com/5927682/101602366-f9e44b80-3a38-11eb-92aa-bd25ed715fbb.png)
`
mainThreadExtensionService.ts:65 [[object Object]]Unexpected token S in JSON at position 0
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:437
_receiveMessage @ ipc.net.ts:778
(anonymous) @ ipc.net.ts:633
fire @ event.ts:535
acceptChunk @ ipc.net.ts:185
(anonymous) @ ipc.net.ts:185
t @ ipc.net.ts:21
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 SyntaxError: Unexpected token S in JSON at position 0
	at JSON.parse (<anonymous>)
	at u.onData (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:148549)
	at Socket.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:147913)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:437
_receiveMessage @ ipc.net.ts:778
(anonymous) @ ipc.net.ts:633
fire @ event.ts:535
acceptChunk @ ipc.net.ts:185
(anonymous) @ ipc.net.ts:185
t @ ipc.net.ts:21
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:65 [[object Object]]Message header must separate key and value using :
$onExtensionRuntimeError @ mainThreadExtensionService.ts:57
_doInvokeHandler @ rpcProtocol.ts:401
_invokeHandler @ rpcProtocol.ts:332
_receiveRequest @ rpcProtocol.ts:278
_receiveOneMessage @ rpcProtocol.ts:220
(anonymous) @ rpcProtocol.ts:93
fire @ event.ts:535
fire @ ipc.net.ts:437
_receiveMessage @ ipc.net.ts:778
(anonymous) @ ipc.net.ts:633
fire @ event.ts:535
acceptChunk @ ipc.net.ts:185
(anonymous) @ ipc.net.ts:185
t @ ipc.net.ts:21
emit @ events.js:223
addChunk @ _stream_readable.js:309
readableAddChunk @ _stream_readable.js:290
Readable.push @ _stream_readable.js:224
onStreamRead @ internal/stream_base_commons.js:181
mainThreadExtensionService.ts:66 Error: Message header must separate key and value using :
	at c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:146298
	at Array.forEach (<anonymous>)
	at a.tryReadHeaders (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:146249)
	at u.onData (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:148108)
	at Socket.<anonymous> (c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:8:147913)
	at Socket.emit (events.js:223:5)
	at addChunk (_stream_readable.js:309:12)
	at readableAddChunk (_stream_readable.js:290:11)
	at Socket.Readable.push (_stream_readable.js:224:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:181:23)
`

**Comment by Charles-Gagnon** [comment]
Are you seeing the same errors that oxwanawxo was seeing @yorkshirelandscape ?

Those errors are implying that the JSON RPC channel is getting some invalid content when reading messages, which is pretty bizarre. 

https://github.com/microsoft/vscode-languageserver-node/blob/main/jsonrpc/src/common/messageBuffer.ts#L103

Unfortunately there isn't really any logging that deep into the RPC layer to see what the client is receiving that's causing it to throw there. And we don't log the full message content being sent on the server side either...so we'd likely need to start by looking into adding more verbose logging in both of those places to try and track down what could be happening here.

**Comment by yorkshirelandscape** [comment]
I'm seeing the "Message header must separate key and value using :" error. I don't recall seeing the "Unexpected token S" one. 

It can happen spontaneously while I'm working on a db I'm already connected to or while trying to create a new connection, either just after starting the program or later. It will affect one server but not another. It happens frequently enough that I'm sure I could get you some more error data within a couple days.

Nice hat, btw.

**Comment by yorkshirelandscape** [comment]
Ahh, I DO get the "Unexpected token S" error, after all. 

[[object Object]]Unexpected token S in JSON at position 0

**Comment by oxwanawxo** [comment]
@yorkshirelandscape 
recently, this situation do not show again when i updated it to the lastest version, and may be the issue related with computers, my office pc occured,my owner do not

**Comment by cheenamalhotra** [comment]
Closing as issue is not reproducible anymore.
Let us know if you continue to experience the issue along-with logs for investigation, and we can re-open the issue.
