### ISSUE TITLE
trying to open d/b 

### ISSUE THREAD

**Issue by deanhunter** [microsoft/azuredatastudio#13039]
Issue Type: <b>Bug</b>

have just downloaded this piece of rubbish.

can not open 2019 database

progress wheel just sits there rotating ad infinitum

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (9.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
Please look through existing open issues to see if any match the problem you're having. If none do then we'll need you to provide more information such as :

1. Any errors you see
1. Whether you can connect to this server through other means (SQLCMD, SSMS, etc)
1. How long do you wait for the connection to be made? There should be a 60sec timeout if the server can't be reached
