### ISSUE TITLE
All Extensions fail to open

### ISSUE THREAD

**Issue by sqllensman** [microsoft/azuredatastudio#13033]
Issue Type: <b>Bug</b>

When trying to use almost any extension in a new install of Azure Data Studio it fails with message like
Unable to open 'Extension: Managed Instance Dashboard': Unexpected token < in JSON at position 0.

Expected result: Something works

Actual Result: Meaningless error message

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
alwayson-insights|mat|0.2.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
cms|Mic|0.8.0
dacpac|Mic|1.6.0
datavirtualization|Mic|1.10.0
import|Mic|1.1.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.6.0
server-report|Mic|0.2.2
powershell|ms-|2020.4.0

</details>

**Comment by kburtram** [comment]
@sqllensman are you still experiencing this issue on latest builds?  We didn't see any other reports of similar issues, so perhaps something got broken during install.  Have you tried reinstalling?

**Comment by kburtram** [comment]
Closing older issues that don't have recent repro reports.  Please let us know if you're still impacted by this issue.
