### ISSUE TITLE
Current insider build won't install Azure Data CLI

### ISSUE THREAD

**Issue by greglow-sdu** [microsoft/azuredatastudio#13048]
- Azure Data Studio Version: Latest insiders build

Steps to Reproduce: I added Azure Data CLI. Now every time I start ADS, I get a message telling me that Azure Data CLI is missing, and gives me an option to install it. When I click yes, the install then fails telling me that names must be alphanumeric and less than 70 characters long.

1.

**Comment by Charles-Gagnon** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/13046 - this should be in the insiders build tomorrow
