### ISSUE TITLE
Wrong error message text in Arc SQL MI create notebook says 'password' when it should say 'username'

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13053]
- Azure Data Studio Version:

Steps to Reproduce:

1.When trying to create an SQL MI from a Notebook without the USERNAME but the PASSWORD variable being set, you get a slightly wrong error message: 

ERROR: Please provide an Arc SQL managed instance password through the env variable AZDATA_USERNAME.

---------
Notice that it says '**password** through' instead of 'username through'.

**Comment by Charles-Gagnon** [comment]
@twright-msft What Notebook? I'm not seeing this error message in any of our stuff. Could you include a screenshot of where you're seeing this?
