### ISSUE TITLE
Missing syntax highlight for "RIGHT" keyword

### ISSUE THREAD

**Issue by tanyogeorgiev** [microsoft/azuredatastudio#13054]
- Azure Data Studio Version: 1.23.0

File [(sql.tmLanguage.json](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql/syntaxes/sql.tmLanguage.json
) ) must be updated!

Steps to Reproduce:
1.Every query with RIGHT function... SELECT CHAR(RIGHT('65', 2))

**Comment by dzsquared** [comment]
@Charles-Gagnon I don't think this PR made it into the tmLanguage for vscode-mssql 
https://github.com/microsoft/vscode-mssql/pull/1739

**Comment by Charles-Gagnon** [comment]
We get this file from VS Code. Submitted an issue to see about getting the grammar file updated : https://github.com/microsoft/vscode/issues/109251
