### ISSUE TITLE
DATE_BUCKET() Error Indicator with 4 Parameters

### ISSUE THREAD

**Issue by feaselkl** [microsoft/azuredatastudio#13069]
- Azure Data Studio Version: 1.23.0 (system setup)

Steps to Reproduce:

1. Enter the following code when connected to an Azure SQL Edge instance:

```
DECLARE
    @date DATETIME2(0) = '2020-04-15 21:22:11',
    @origin DATETIME2(0) = '2020-01-01';
SELECT 1 AS BucketNumber, DATE_BUCKET(wk, 1, @date, @origin) AS BucketBeginDate;
```

An error appears indicating that this syntax is correct and that `DATE_BUCKET()` requires three arguments:
![image](https://user-images.githubusercontent.com/1330589/97084616-5523c100-15e6-11eb-865d-80ed8935696b.png)

[Origin is, however, a valid, optional argument for the function](https://docs.microsoft.com/en-us/azure/azure-sql-edge/date-bucket-tsql) and executing the script succeeds:
![image](https://user-images.githubusercontent.com/1330589/97084642-77b5da00-15e6-11eb-9675-23f1bb20132f.png)

This does not block any work as executing the code succeeds, but it does show an unnecessary issue in an otherwise-fine script.

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
