### ISSUE TITLE
Filename Filter

### ISSUE THREAD

**Issue by kazoo60** [microsoft/azuredatastudio#13065]
I would like a function like the "Search Solution Explorer" function in Visual Studio to find object files in my project.

I am working with a database with several thousand objects.  To scroll through the list of procedures to find the one I want to edit takes a long time. We are used to the VS interface that allows you to find files quickly by typing in their name or a portion of the name. 

When I use the file-content search feature in ADS (the looking glass icon on the LHS), too many results are returned.  That feature is useful for sure, but a much more common requirement for us is find a file where the object name is known. 

If a "Search file explorer" field could be included at the top of the display (under "EXPLORER") that would filter the files, this requirement would be met.  (See screenshot for context).  

My apologies if this functionality exists and I have missed it.

Thank you
![ObjectList](https://user-images.githubusercontent.com/33428344/97062334-b781b080-1557-11eb-9ebd-d821324e6061.PNG)

**Comment by Charles-Gagnon** [comment]
You can do this by just selecting the tree and starting to type - then making sure "Enable Filter on Type" is selected :

![Capture](https://user-images.githubusercontent.com/28519865/97064174-eea49180-1558-11eb-9b50-1ae68c398cf7.gif)

(we're aware this isn't very discoverable and are going to try to make it more discoverable - but in the meantime I hope this is the functionality you're looking for!)

**Comment by kazoo60** [comment]
Thank you!  Works great.

Tim

**Comment by andriysavin** [comment]
The workaround doesn't work for me as described. When I type a word it finds and highlights separate characters of this word, but not whole words. Also, this "feature" is poorly discoverable. Why not just add a convenient file filter field like in Visual Studio?

**Comment by Charles-Gagnon** [comment]
@andriysavin Could you share a screenshot of what you mean with it highlighting the separate characters of the word?

**Comment by andriysavin** [comment]
@Charles-Gagnon I'm afraid I'm not allowed to publish screenshots with project's files list, but to give you the idea: when I was typing "cal" to find files containing "Calculate", these files were not shown (they definitely were there), but instead it was showing some fuzzy-search results like on the screenshot. When I checked one more time recently, the files suddenly started to appear in the search results, but this fuzzy-search was there too.
![image](https://user-images.githubusercontent.com/12996633/218834304-e91bb5ca-6f1d-4f7e-8670-57f53810076e.png)

**Comment by andriysavin** [comment]
@Charles-Gagnon I've just tried, and yes, in VS code it works better. However, IMHO it has the same usability issue (which I probably interpreted as inability to find my files in ADS): it doesn't expand folders to unveil search results like VS does AND it says there are no matches while there are!
![image](https://user-images.githubusercontent.com/12996633/219016740-b677f29c-a4da-4a39-8009-30df444d924d.png)
![image](https://user-images.githubusercontent.com/12996633/219020494-621fbf4d-e071-4f08-b34d-0a881e159657.png)

So 1. If you're new to the product, you need to notice the dots next to folders perhaps indicating there are matches there (but I'm not sure); 2. You have to manually expand each folder to observe search results - that's annoying. 

Also, I noticed these dots even next to folders which didn't unveil any matches:
![image](https://user-images.githubusercontent.com/12996633/219017806-7ff17d7d-9fda-4ac8-9aca-d283f6b40856.png)

**Comment by Charles-Gagnon** [comment]
Gotcha, yeah the tree find widget isn't really a fully featured find. If you're looking for a specific file in an opened folder you can hit ctrl+p and that will open a quick input find that will search through all opened files.

Otherwise I would suggest opening an issue on the [VS Code](https://github.com/Microsoft/vscode) repo to see if you can get any traction there - that way it would benefit all users of both VS Code and ADS. Changes to core features like that are generally something we don't do to avoid having too many conflicts with what we inherit from them.
