### ISSUE TITLE
Enter-PSSession does not work in PowserShell code cell.

### ISSUE THREAD

**Issue by johnmart82** [microsoft/azuredatastudio#13070]
Issue is that when executing PowerShell using the PowerShell kernel in a code cell the Enter-PSSession functionality does not work. There are no error messages to indicate that it has not succeeded or the code is not being executed on the remote server.

Expected result is that the code block is executed on the remote server within the section between Enter-PSSession and Exit-PSSession.

- Azure Data Studio Version: 1.23.0 (user setup)

Assumptions:
1. PowerShell Extension is installed.

Steps to Reproduce:
1. Create new Notebook and select PowerShell kernel.
2. Create a code cell.
3. Add following code, substituting your target server name. 
```
$ServerName = "SQL01"

Enter-PSSession -ComputerName $ServerName

Whoami
hostname
$ServerName

Exit-PSSession
```
4. Execute code cell.
5. Review output from code execution and note that the hostname is for the local system and the parameter is for the remote target.

Note: This code works fine in ISE or when using .ps1 files in ADS.

**Comment by chlafreniere** [comment]
@VasuBhog can you work with @johnmart82 to understand what's going on here?

**Comment by VasuBhog** [comment]
Hi @johnmart82, can you please confirm that you are using the newly released PowerShell kernel 0.1.4. You are able to update to the new version via the manage packages dialog. Search for powershell_kernel (in the Add new) package, and then make sure the version is 0.1.4 (shown below).

![image](https://user-images.githubusercontent.com/23587151/97523194-995ceb80-196f-11eb-9ca5-50310db41e13.png)

**Comment by VasuBhog** [comment]
@johnmart82 I have not heard back from you. I was wondering if you were able to upgrade to the newest PowerShell Kernel package and see if that got you the error as well. 

Please let me know if the issue persists.

**Comment by VasuBhog** [comment]
Closing since there isn't currently sufficient context to investigate.
