### ISSUE TITLE
After Release 1.23 server don't expand folders

### ISSUE THREAD

**Issue by linhoz** [microsoft/azuredatastudio#13072]
HI,

After the release 1.23 my servers don´t expand to see the folders (Databases, Security and Server Objects). After downgrade to 1.22.1 version worked. But I´d like to know how to fix this problem in 1.23 version.

Tkx

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/12992
