### ISSUE TITLE
the azdata.accounts.onDidChangeAccounts event will trigger in many cases where the accounts didn't actually change

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#13083]
I saw the following comment in the tree provider code: https://github.com/microsoft/azuredatastudio/blob/main/extensions/azurecore/src/azureResource/tree/treeProvider.ts#L29

		azdata.accounts.onDidChangeAccounts(async (e: azdata.DidChangeAccountsParams) => {
			// This event sends it per provider, we need to make sure we get all the azure related accounts
			let accounts = await azdata.accounts.getAllAccounts();
			accounts = accounts.filter(a => a.key.providerId.startsWith('azure'));
			// the onDidChangeAccounts event will trigger in many cases where the accounts didn't actually change
			// the notifyNodeChanged event triggers a refresh which triggers a getChildren which can trigger this callback
			// this below check short-circuits the infinite callback loop
			this.setSystemInitialized();
			if (!equals(accounts, this.accounts)) {
				this.accounts = accounts;
				this.notifyNodeChanged(undefined);
			}
		});

please investigate and see whether the issue is still there.

**Comment by kburtram** [comment]
Closing older API-focused issues to prioritize customer scenario-facing issues.  Please open an issue for the feature impacted by this API behavior if applicable.  Thanks!
