### ISSUE TITLE
Refreshing arc controller connection gives error...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#13085]
Issue Type: <b>Bug</b>

Converting circular structure to JSON
    --> starting at object with constructor 'i'
    |     property 'next' -> object with constructor 'i'
    --- property 'prev' closes the circle

Azure Data Studio version: azuredatastudio-rc1 1.23.0-rc1 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:09:00.244Z)
OS version: Windows_NT x64 10.0.20241

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.5.1
azdata|Mic|0.3.1
azuredatastudio-postgresql|Mic|0.2.6

</details>

**Comment by Charles-Gagnon** [comment]
Haven't seen this so assuming it's been fixed by now
