### ISSUE TITLE
Notebook cell execution count is incrementing from all cell executions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#13088]
1. Create new notebook
1. Create two code cells and add any content to them
1. Run the first cell
1. Run the second cell

Expected : 

Both cells have an execution_count of 1.

Actual : 

Cell 1 has an execution_count of 1, but cell 2 has an execution count of 2.

And then if you go back to Cell 1 and run it again the execution count is bumped up to 3 and so on.

**Comment by chlafreniere** [comment]
This is by design. Here's a screenshot from Jupyter where I ran the first cell, the second cell, and the first cell again:

![image](https://user-images.githubusercontent.com/40371649/97518976-a10f9680-1955-11eb-8d0f-a89d4d170204.png)

**Comment by Charles-Gagnon** [comment]
Huh...I guess maybe it's mean to be used to determine in what order cells were executed? Do you have any idea on the reasoning behind this?
