### ISSUE TITLE
[Feature Request] Support TOC Tag

### ISSUE THREAD

**Issue by mattmsft** [microsoft/azuredatastudio#13096]
Support the [[\_TOC\_]] tag from the Azure Devops wiki markdown syntax https://docs.microsoft.com/en-us/azure/devops/project/wiki/wiki-markdown-guidance?view=azure-devops#table-of-contents-toc-for-wiki-pages:

The [[\_TOC\_]] tag should automatically generates a table of contents from all the headers in the notebook. This is especially useful in large notebooks with many cells and headings.

**Comment by chlafreniere** [comment]
This is nonstandard syntax, and as such, doesn't allow for any interop with any other notebook viewers. To be completely honest, I don't see us implementing this at all; if we did, that would ensure that notebooks can't be rendered in any other notebook viewers, which goes against our principle of interop with open source.
