### ISSUE TITLE
Unable to reach New Deployment work flow due to command 'azdata.resource.deploy' not found

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#13123]
- Azure Data Studio Version:

Steps to Reproduce:

1. install ADS Insiders
2. install Arc extension 0.6.0
3. install azdata extension 0.4.0
4. Server blade\Connections\...\New Deployment...

fails with error:
![image](https://user-images.githubusercontent.com/22226386/97504503-3b5ee280-1934-11eb-8801-a2511a93f4c6.png)

**Comment by Charles-Gagnon** [comment]
Are there any errors in the console logs (Help -> Toggle Developer Console -> console tab)? This is likely due to the resource deployment extension not being loaded for some reason. 

And where are you getting these versions of the extensions from? The current released versions are 0.5.1 and 0.3.1...

**Comment by Charles-Gagnon** [comment]
@TheJY And just to be sure - you do have the latest insiders right? No updates available?

**Comment by TheJY** [comment]
@Charles-Gagnon correct, no update available. Reproed with current non insiders version of ADS as well.

**Comment by Charles-Gagnon** [comment]
> Are there any errors in the console logs (Help -> Toggle Developer Console -> console tab)? This is likely due to the resource deployment extension not being loaded for some reason.
> 
> And where are you getting these versions of the extensions from? The current released versions are 0.5.1 and 0.3.1...

Can you respond to these? I'm able to deploy just fine and no one else seems to be having this issue so not sure what's going on here.

**Comment by Charles-Gagnon** [comment]
Closing this for now since I haven't heard of this happening again - let me know if you still see this.
