### ISSUE TITLE
Workspace connections don't show without added user connection

### ISSUE THREAD

**Issue by JustinMDotNet** [microsoft/azuredatastudio#13137]
- Azure Data Studio Version: 1.24

Note: Adding a connection to the object explorer shows all connections

Steps to Reproduce:

1. Have ADS installation with no added connections in Object Explorer
2. Have ADS Livesite extension installed
3. Open Livesite Workspace: TSGWorkspace
4. Notice the servers don't get loaded in the Object Explorer

![image](https://user-images.githubusercontent.com/63619224/97613830-639f1d80-19d6-11eb-8fe6-e97d4f8453c5.png)

**Comment by kburtram** [comment]
Below is what I am seeing in the Servers view with the above repro on the current build.  Please verify this issue and close if no repro, or add some additional repro context and assign to me.  Thanks!

![image](https://user-images.githubusercontent.com/599935/132779210-fe55a044-74e6-492a-96a5-506b63ea8ed0.png)

**Comment by kburtram** [comment]
Closing as no repro.
