### ISSUE TITLE
Results don't always show

### ISSUE THREAD

**Issue by chris904apps** [microsoft/azuredatastudio#13133]
Issue Type: <b>Bug</b>

Sometimes, believe only with the Powershell Kernal, I don't see any results after code block has ran. Doesn't appear to have errored but with no results. I'm unsure.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (19.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
sql-prompt|Red|0.2.2

</details>

**Comment by VasuBhog** [comment]
@chris904apps, can you please confirm that you are using the newly released PowerShell kernel 0.1.4.
You are able to update to the new version via the manage packages dialog. Search for powershell_kernel (in the Add new) package manager dialog, and then make sure the version is 0.1.4 as shown below.

![image](https://user-images.githubusercontent.com/23587151/98858431-34e96400-2426-11eb-9563-432419580035.png)

**Comment by chlafreniere** [comment]
Closing this as we need more info.
