### ISSUE TITLE
Modifying components in ModelViewDashboard only works after the tab has been selected

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio#13134]
In the Arc extension we use a ModelViewDashboard with multiple tabs.  When opening a dashboard, the model may not have data yet.  If so, we initialize certain UI components with loading text/icons.  Then when the model is loaded, each tab modifies its components with the real values.

We're seeing that modifying these components only works after the tab has been selected.  It doesn't have to currently be selected.  Just has to have been selected at some point.  Modifications made while the tab has never been selected don't appear in the UI when you do eventually visit the tab.

We've seen similar behavior in the past where we can't use LoadingComponents on anything other than the default tab.  Even though we set loading to false, the spinner keeps spinning unless you visited the tab while it was loading.

What's interesting is that adding components seems to work fine, even without visiting the tab.  It's just removing or modifying components that doesn't take effect.

The current repro is the Compute + Storage page of the Arc Postgres dashboard.  The text boxes keep the 'loading' placeholder even when the debugger shows we've changed it.  And it only unsticks once you visit the tab then refresh the model.  To repro this, the model must not have data on initial load.  So this only happens the first time you open a dashboard for each resource. (Though it could cause stale data in other situations)

Let me know if it's useful and I can create a minimal repro.

**Comment by chlafreniere** [comment]
This is blocking the postgres team from being able to release their next dashboard page for the experiences that they're building for Azure Arc. Need to investigate the fix here.

**Comment by Charles-Gagnon** [comment]
re-opening since this is still an issue, they just worked around it.
