### ISSUE TITLE
Notebook: H2 with <mark> tag seems to overlap in preview / WYSIWYG

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13146]
- Azure Data Studio Version:
Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a new notebook and type the following:
```## <mark>No marvel then, though I mistake my view; The sun itself sees not, till heaven clears.</mark>```

![image](https://user-images.githubusercontent.com/6405919/97660364-9117b580-1a2e-11eb-9b32-37ecf4784fdf.png)

This seems to be an issue with H2 but not H1, H3 or H4.
Expected outcome: no overlapping.

**Comment by MsSQLGirl** [comment]
@halerankin FYI

**Comment by chlafreniere** [comment]
Almost certainly related to #13032

**Comment by halerankin** [comment]
we'll just need to increase default line height for H2

**Comment by chlafreniere** [comment]
@MsSQLGirl can you still repro this? I was able to previously, but I now see the following:

![image](https://user-images.githubusercontent.com/40371649/106540867-ac72e080-64b5-11eb-9671-d570a4bacd28.png)

**Comment by halerankin** [comment]
Re-tested main branch in local build using Mac OS. Confirmed as displaying as expected.

**Comment by chlafreniere** [comment]
Closing as neither @halerankin nor I can repro this any longer. Feel free to reopen if you see this again @MsSQLGirl
