### ISSUE TITLE
Notebooks with code cells cannot be marked as Trusted

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13172]
- Azure Data Studio Version:
Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

also 
Version: 1.24.0-insider (user setup)
Commit: 7857e8aeb9e1310a7e8af0285543d42cd505c716
Date: 2020-10-30T05:34:43.899Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open an existing notebook that has Code cell. 
I'm unable to mark this as Trusted now. 
![image](https://user-images.githubusercontent.com/6405919/97767746-73545a00-1adb-11eb-82b0-ac9a56c9c49e.png)

The screenshot is from a file from my own repo that I cloned locally:
https://github.com/MsSQLGirl/jubilant-data-wizards/blob/main/Notebook%20Templates/TutorialTemplate.ipynb

Expected: be able to mark as Trusted.
Impact: users who have links in the code cells (from the same notebook) cannot be launched because of the Trusted issue.

**Comment by chlafreniere** [comment]
There has to be a nested folder here.

Basically we're looking at:
- Open folder in ADS
- From notebooks viewlet, open a notebook that's not in the root of whatever folder you previously opened

**Comment by chlafreniere** [comment]
@lucyzhang929 could you take a look at this when you get a chance next week 😄

**Comment by chlafreniere** [comment]
Just kidding @lucyzhang929. It was simple enough (1 line change) 😄
