### ISSUE TITLE
build for arm64?

### ISSUE THREAD

**Issue by stevenhurwitt** [microsoft/azuredatastudio#13178]
**Is your feature request related to a problem? Please describe.**
How can I build this for arm64? would like to use on my raspberry pi now that vscode is arm64-compatible.

**Describe the solution or feature you'd like**
To build the repo from source, `yarn install` isn't working for me, saying "no install file".

**Describe alternatives you've considered**
Making a dockerfile, but docker is broken for me on raspberry pi

**Additional context**
Azure edge is great, made a SQL server IOT hub, can use VSCode now, so ADX would be a great addition to this ecosystem.

**Comment by Charles-Gagnon** [comment]
We don't currently support building for arm64 - see the enhancement request here : https://github.com/microsoft/azuredatastudio/issues/1774
