### ISSUE TITLE
More Source Control than just Git

### ISSUE THREAD

**Issue by JediSQL** [microsoft/azuredatastudio#13185]
**Is your feature request related to a problem? Please describe.**
We have an existing source control system that meets our needs very well.
Git lacks features we use on a daily basis as part of our established procedures.

**Describe the solution or feature you'd like**
It seems that "VS Code" supports development of extensions for source control:
https://code.visualstudio.com/docs/editor/versioncontrol
Please enhance Azure Data Studio to support those extensions.

**Describe alternatives you've considered**
It does not seem like there is an alternative, other than using the source control from its own interface without IDE integration.

**Additional context**
N/A

**Comment by Charles-Gagnon** [comment]
Closing this as it's very similar to https://github.com/microsoft/azuredatastudio/issues/2307

Have you tried installing other version control extensions into ADS? We haven't really modified that stuff so it should generally work depending on the extension.

If you do find an extension that doesn't work then I'd suggest opening an issue with the owner of that extension to add support for ADS - and if there's any issues in ADS preventing that then opening an issue here at that time with the details.
