### ISSUE TITLE
SQL Assessment runs infinitely for some SQL Server instances

### ISSUE THREAD

**Issue by aguzev** [microsoft/azuredatastudio#13206]
- Azure Data Studio Version: 1.23.0

Steps to Reproduce:

1. Install SQL Assessment extension to ADS
1. Connect to a SQL Server 2008 R2 instance
1. Right-click the instance and select **Manage**
1. Click **SQL Assessment**
1. Click **Invoke Assessment**
1. Assessment runs forever

For Azure Data Studio Version 1.24.0-insider

1. On a SQL Server instance (any version) disable _xp_cmdshell_
1. Install SQL Assessment extension to ADS
1. Connect to the instance configured at step 1
1. Right-click the instance name on the left pane and select **Manage**
1. Click **SQL Assessment**
1. Click **Invoke Assessment**
1. Assessment runs forever

**Comment by kburtram** [comment]
@aguzev this should be fixed in release/1.24.  Could you please verify on the latest RC1 build?
