### ISSUE TITLE
Not able to configure Python to run PowerShell kernel

### ISSUE THREAD

**Issue by sanderstad** [microsoft/azuredatastudio#13215]
Issue Type: <b>Bug</b>

I have been using the Insiders edition for months and running PowerShell Notebooks. Suddenly after the most recent update I have the configure Python again to run the PowerShell kernel

1. Open a PowerShell Notebook.
2. It opens a wizard called "Configure Python to run PowerShell kernel". Click "Next"
![image](https://user-images.githubusercontent.com/6154981/98087714-d39f1f00-1e80-11eb-9a9f-933d2ddd9ef5.png)
3. Click on "Install"
![image](https://user-images.githubusercontent.com/6154981/98087755-ddc11d80-1e80-11eb-8a14-b8755812ea33.png)
4. You get the error message
![image](https://user-images.githubusercontent.com/6154981/98087826-f6313800-1e80-11eb-8a36-bb14b7b060d2.png)

The full error message
```
Could not start session: Cannot overwrite an existing Python installation while python is running. Please close any active notebooks before proceeding.
```

The problem is that this wizard only appears when I open a PowerShell Notebook, but I can't close the opened Notebook when the wizard appears.

Also like I said before, I have been running PowerShell Notebooks for months and months and now I have to reconfigure it again?

Azure Data Studio version: azuredatastudio-insiders 1.24.0-insider (3ec1f7cc2bd11879830fb5f8e25592e547bc622a, 2020-11-04T06:33:22.225Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (11.37GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/sstad/source/repos/Databases/Waypoint%20Analytical/NotebooksArchive|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.6.0
sql-database-projects|Mic|0.3.0
azdata-sanddance|msr|3.1.0
sql-prompt|Red|0.2.3
tsqlt-test-generator|taz|0.0.5
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by chlafreniere** [comment]
@VasuBhog can you work with folks on the team (@corivera or @pensivebrian) to determine how we can make this more seamless?

**Comment by corivera** [comment]
@VasuBhog we only needed to do a package upgrade here, so we can probably skip throwing that error in this case. This error is meant to prevent file permission failures thrown when trying to overwrite python files that are currently in use.

**Comment by sanderstad** [comment]
Is there any progress on this because both the stable client as the insiders edition have this problem and I can't work with my notebooks anymore.

Is there some sort of workaround that I can just run a command that updates the package?

**Comment by sanderstad** [comment]
Fixed it by using the current python installation.

The notebooks gave me another problem because suddenly it gave me errors with `Authorization Manager check failed`
Apparently I have to set the execution policy for the current user every time I run a PowerShell Notebook?

**Comment by VasuBhog** [comment]
@sanderstad we are currently looking to address this issue. @corivera do you have any workaround suggestions regarding the new issue Sander is experiencing: `Authorization Manager check failed`?

**Comment by corivera** [comment]
That's news to me, I'm not familiar with an error like that. @sanderstad Could you open a separate issue with the errors you're getting related to Authorization Manager?

**Comment by VasuBhog** [comment]
@sanderstad let us know if you have any other problems with the PowerShell kernel. Thanks, @corivera for helping on this!
