### ISSUE TITLE
WYSIWYG - Highlighting a bold or italics text is not preserved after switching to markdown or exiting cell.

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#13212]
- Azure Data Studio Version:
Version: 1.24.0-rc1
Commit: 04117b2333373bf326d367de40fb018a83218775
Date: 2020-11-03T00:40:26.189Z (1 day ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
Steps to Reproduce:

1. Add a text cell to notebook
2. Add highlight to a bold (or italics) text.
3. Exit edit mode or switch to back and forth from markdown to rich text view and the highlighting disappears.

**Comment by chlafreniere** [comment]
This will be addressed with #13032

**Comment by jasonhorner** [comment]
hey @chlafreniere  it looks like that request is still awaiting a merge any idea on a rough timing of this.. it seems to globally convert any markdown into html when edits are made in the WYSIWYG  editor in my case it takes my MD hyperlinks and turns them into ugly html making it more cumbersome to edit IMHO. what should happen is that it should preserve any MD  but respect any HTML on round trips through both editors. this is probably easier said than done.  should i enter a new bug or feature for the broader scope or is this fixed globally?

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by chlafreniere** [comment]
@jasonhorner could you please create a new issue? Would be super helpful to include either a sample notebook or sample text cell content and we can take a look.
