### ISSUE TITLE
queryEditor.results.copyIncludeHeaders not working

### ISSUE THREAD

**Issue by isaarikko** [microsoft/azuredatastudio#13217]
Issue Type: <b>Bug</b>

Setting: Query Editor > Results: Copy Include Headers (queryEditor.results.copyIncludeHeaders)
does not work. After checking the option in Settings, saving Settings file, restarting ADS, copy still don't include headers.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (5.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.1.0

</details>

**Comment by EdCallahan** [comment]
Still broken in azuredatastudio 1.27.0
