### ISSUE TITLE
"Validate External Streaming Job" not showing up when external streaming job is added to project

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#13233]
Steps to Reproduce:

1. Add an external streaming job to a project
2. Right click on newly added external streaming job to open context menu

Expected: "Validate External Streaming Job" should be the first option in the context menu
Actual: only "Exclude from project" and "Delete" are in the context menu

it shows up correctly if the project is closed and opened again
![validateExternalStreamingJob](https://user-images.githubusercontent.com/31145923/98166856-f4756d80-1e9c-11eb-970d-9911c4fd2255.gif)

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by udeeshagautam** [comment]
Should not need porting for Nov
