### ISSUE TITLE
No message after clicking "Validate External Streaming Job"

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#13234]
There should be an information message if successful or error message if validation failed, but there isn't any that pops up. This is with sqltoolsservice updated to 3.0.0-release.50.

I tried adding a break point on line 595 and it wasn't getting hit. https://github.com/microsoft/azuredatastudio/blob/342ff47e512bd30b66ac0fdad0d487a2235f2a18/extensions/sql-database-projects/src/controllers/projectController.ts#L593-L600

**Comment by udeeshagautam** [comment]
Should not need porting for Nov

**Comment by Benjin** [comment]
This is happening because the SqlToolsService binaries don't have the new functions, despite the source code being checked in.  @Charles-Gagnon is investigating what's going on with the builds.
