### ISSUE TITLE
Schema compare fails when applying changes with streaming input or Job

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#13246]
- Azure Data Studio Version:

Steps to Reproduce:

Schema compare fails to apply differences in streaming objects (only external streams and streaming jobs) where as dacpac and project extensions are able to apply these changes. The error is folowing and seems to come from DacFx -

Performing script generation is not possible for this comparison result.

**Comment by udeeshagautam** [comment]
Adding to backlog since this seems to be coming from DacFx. Dacpac and Project extensions can be used as a workaround.

**Comment by Benjin** [comment]
This occurs when the Streaming Job difference is present, regardless of whether it's "included" when you hit apply.
