### ISSUE TITLE
Drag-ability ...

### ISSUE THREAD

**Issue by lproberge77** [microsoft/azuredatastudio#13249]
Issue Type: <b>Feature Request</b>

In MSSQL, the ability to drag tables name, fields name or all columns using columns folder is really usefull... It can be nice to have that feature in furter releases.

regards

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T22:58:36.079Z)
OS version: Darwin x64 19.6.0

**Comment by Charles-Gagnon** [comment]
We have this functionality in the latest version of ADS : 

![Capture](https://user-images.githubusercontent.com/28519865/98273918-ab2e2800-1f47-11eb-86d0-a5d5df113248.gif)
