### ISSUE TITLE
Make ApplicationIntent setting visibile in UI

### ISSUE THREAD

**Issue by mcenzato** [microsoft/azuredatastudio#13274]
It's very nice that ADS allow to choose in connection dialog ApplicationIntent value with an explicit combobox.
In my everyday work, sometimes (often) I connect to our prods DBs using the read scale out replica (i.e. ApplicationIntent=ReadOnly) to query/investigate data without interfer with the production ReadWrite DBs user operativity (some queries can take long time, DBs are very, very huge).
But when I need to update something obviously I switch to RW DB.
With a lot query windows opened, it's to simple (and errorprone) to forget than one query window is connected to RW DB and not to RO.
I suggest to put something in the UI (color, bold, asterisk, what you prefer) that immediately shows to the user when a Query Window has a open connection to a Read Only replica (or the other way around).

**Comment by kburtram** [comment]
@mcenzato there is an option for ApplicationIntent in the Advanced page of the connection dialog.  Is the feature request to move this option out of Advanced to make it more discoverable in the UI?

<img width="492" alt="Screen Shot 2020-11-11 at 12 11 23 PM" src="https://user-images.githubusercontent.com/599935/98859610-4aa35d00-2417-11eb-92bc-fd84a2d9f905.png">

**Comment by mcenzato** [comment]
@kburtram I kwnow the option and it's not hidden, almost for me.
My d
request is about to have some kind of UI differentiation when I have tens of query windows opened, some in read-only mode and some others no: with a long work (all the day) and a lot of activity sometimes I don't remember witch windows has R/O connection and witch not.

**Comment by kburtram** [comment]
@mcenzato thanks for clarifying the request!

**Comment by mcenzato** [comment]
To clarify even more, often I'm working in Azure DB production to analyze (and sometime fix) data.
We are leveraging Read-Scaleout replica in Business tier, and for me is important to do the data analysis in R/O replica (ApplicationIntent=ReadOnly) because often the query are very huge and not indexed-optimized (as I told, it's not normal application code bug investigation queries).
That said, my query windows are almost all in R/O mode, but sometimes, identified a problem, I have to fix (update stmts) it and I need also a RW connection/query window.
Things are complicated due to the fact the application is partitioned into 7 DBs, than often I've 7 RO query windows and I need also 7 RW query windows; jumping form one query window to others becomes highly error prone (a readonly query on production RW DB can cause timeout to end-users).
Having clear UI differentiation (query windows name color, window backgroud, etc...) would help me a lot!

**Comment by cheenamalhotra** [comment]
This is being considered with PR #22045

**Comment by cheenamalhotra** [comment]
_We're almost ready, moving milestone to May to add additional time to test with the insiders build._

**Comment by mcenzato** [comment]
Thanks Cheena!

**Comment by cheenamalhotra** [comment]
Remaining work:
- Show advanced options on Query editor/Dashboard/Table Designer tabs on hover, as visible in Object explorer.
- Ensure Profile name is respected on Query Editor/Table Designer tab titles as in Dashboard.

**Comment by smartguest** [comment]
It is not possible to split the Editor title on the ADS window and the tooltip on hover without making significant changes to the current ADS window/tab control, so they will have to be the same for now.

**Comment by cheenamalhotra** [comment]
Closing as addressed with https://github.com/microsoft/azuredatastudio/pull/24486
