### ISSUE TITLE
Expiration time when trying to Virtualize Data in PolyBase agains huge Oracle databases

### ISSUE THREAD

**Issue by macarv-ms** [microsoft/azuredatastudio#13278]
- Azure Data Studio Version: Latest

![image](https://user-images.githubusercontent.com/54983537/98365641-9e363500-202a-11eb-963b-c9b757e2cba2.png)

Steps to Reproduce:

1. Try to virtualize a huge Oracle database (with huge number of objects with huge number of columns each) usinx ADS Virtualization extention.

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13279
