### ISSUE TITLE
Bottom border on hover is not visible on connection icons (New connection etc.) 

### ISSUE THREAD

**Issue by BranislavGrbicMDCS** [microsoft/azuredatastudio#13275]
- Azure Data Studio Version:

Steps to Reproduce:

1. Hover over 'New connection' icon 
2. notice that bottom border is not visible 
3. We've noticed it on Source Control icon as well, it might be across all icons.

**Comment by kburtram** [comment]
I'm not able to notice a missing border on the New Connection icon (screenshot below).  Please provide a screenshot if there is a particular UI element being rendered incorrectly.  Thanks!

![image](https://user-images.githubusercontent.com/599935/129842026-23db6c3a-a965-4c8e-be92-f67e38c1194e.png)
