### ISSUE TITLE
Receive an unhandled error while building a database project if .NET Core isn't installed

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13288]
Steps to Reproduce:
1. Create/open a db project.
2. Build.

Error:
![image](https://user-images.githubusercontent.com/57200045/98407907-4ba64a00-2025-11eb-98a3-eec1eabf71e7.png)

Expected: report a user-friendly error about how dotnet couldn't be found.

**Comment by udeeshagautam** [comment]
@SakshiS-harma I am seeing these two boxes (one with the helpful error) - can you please share the output window content as well to see if there is any reason why its not showing the helpful message on some machines

![image](https://user-images.githubusercontent.com/46980425/98737499-208c6500-235b-11eb-810f-790aa5a3b933.png)

**Comment by SakshiS-harma** [comment]
@udeeshagautam I remember I saw these two errors as well (helpful message as well). 
As for now, I tried to repro the issue by uninstalling .NET Core. But this time I didn't receive these two errors instead just the following:
![image](https://user-images.githubusercontent.com/57200045/101213188-d7b08f00-362e-11eb-9978-b1cc8bc892a2.png)

The output window has the following error:
![image](https://user-images.githubusercontent.com/57200045/101213331-12b2c280-362f-11eb-9813-0a2821477128.png)

**Comment by kisantia** [comment]
@SakshiS-harma can you check if you're still able to repro? Assigning to you for repro and initial investigation

**Comment by SakshiS-harma** [comment]
I am still able to repro the issue. The last time that I tried I didn't clean dotnet completely (didn't remove the folder), hence wasn't seeing the original behavior. But I can confirm, I am seeing it now. And there is no information/error in output window.

**Comment by SakshiS-harma** [comment]
Closing this bug, since the error that was mentioned as unhandled, actually adds up with the informational message and helps with understanding the root cause to be the absence of .NET Core. Informational message can be ignored without the error- hence keeping it as-is.
