### ISSUE TITLE
Table gets corrupted while editing in WYSIWYG mode

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#13289]
- Azure Data Studio Version:

Steps to Reproduce:

1. edit the table
2. Save, Close the file
3. Open the file again

![tabledisappear](https://user-images.githubusercontent.com/29285871/98409670-1fd89380-2028-11eb-8ea3-b49cc7595245.gif)

**Comment by kburtram** [comment]
@rajeshka @chlafreniere could you start a thread in the Shiproom teams channel to provide context and get this approved?

**Comment by chlafreniere** [comment]
Some more context:
- This affects tables that don't have headings. Tables with headings work as expected.
- This is not a regression

**Comment by MsSQLGirl** [comment]
@chlafreniere - can you please confirm that this is the workaround?
![image](https://user-images.githubusercontent.com/6405919/98578208-e1361980-2271-11eb-919e-11b3d6e55023.png)

**Comment by barbaravaldez** [comment]
> @chlafreniere - can you please confirm that this is the workaround?
> ![image](https://user-images.githubusercontent.com/6405919/98578208-e1361980-2271-11eb-919e-11b3d6e55023.png)

@MsSQLGirl - that's correct 😄 Tables with a header do not get corrupted.

**Comment by chlafreniere** [comment]
This has been checked into main. Closing as it will make the next release.
