### ISSUE TITLE
Azure Subscription Loading in Connection Dialog is Extremely Slow

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13297]
This reproes for me both on Windows and on Mac on the latest RC1 build when I try to expand my account in the Browse portion of the connection dialog. I have 49 subscriptions so curious if there are any logs that I can help with. Didn't spot anything obvious in the developer console either.

Just see infinite spinning, unfortunately: **(Update: it doesn't spin forever. It loaded after ~5 minutes for me)**

![image](https://user-images.githubusercontent.com/40371649/98428046-9db29400-2054-11eb-95d0-8a12a41ef61d.png)

Note: if I go to the Azure view in the Connections viewlet, I get a list of subscriptions almost immediately, so I do not believe that this is a problem with my Azure account.

Azure Data Studio version: azuredatastudio-rc1 1.24.0-rc1 (6805a582c910e948d217b0b7f266a8e94cb7ba25, 2020-11-07T00:10:09.374Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (32.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.6.2
azdata|Mic|0.4.0
datavirtualization|Mic|1.10.0
kusto|Mic|0.2.0

</details>

**Comment by kburtram** [comment]
I'm getting this error expanding one of my accounts in the Azure view in the 1.24 build.  I didn't see this error on the 1.23 build.

![image](https://user-images.githubusercontent.com/599935/98428400-27af2c80-2056-11eb-8a9c-f546f63f299c.png)

**Comment by Charles-Gagnon** [comment]
@kburtram @cssuh I made a new issue for that since it seems like a different issue than what @chlafreniere reported https://github.com/microsoft/azuredatastudio/issues/13303

**Comment by alanrenmsft** [comment]
the time to load the resources is depending on the number of subscriptions available in the azure account, we are fetching the resources sequentially due to Azure throttling, if you have a lot of subscriptions, you can right click on the azure account node and 'Select subscriptions' to reduce the number of subscriptions to fetch.
