### ISSUE TITLE
Kusto Database Dashboard: Tables are Shown Twice in List

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13294]
- Connect to a Kusto cluster (e.g. help.kusto.windows.net) and open Manage dashboard for the cluster
- From there, right click on a database and click 'Manage'

On the database dashboard, every table will be listed twice:

![image](https://user-images.githubusercontent.com/40371649/98427367-b79ea780-2051-11eb-9b4f-47a99d8824e3.png)

**Comment by gupta1** [comment]
Closing this one. Not able to repro it.
