### ISSUE TITLE
Kusto Database Dashboard: Mismatch between "select top <n>" label and resulting query

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13295]
Right click on a table that's listed in the database dashboard of a Kusto cluster, and you'll see an item labeled as "Select Top 1000":

![image](https://user-images.githubusercontent.com/40371649/98427461-149a5d80-2052-11eb-94b6-06bf0c012a35.png)

- Select this item from the menu. The resulting query looks like the following:

![image](https://user-images.githubusercontent.com/40371649/98427491-3267c280-2052-11eb-9bce-91a8aee788e7.png)

Note the "take 10". These numbers should match (1000 vs. 10).

**Comment by MsSQLGirl** [comment]
@JustinMDotNet , @gupta1 -  can you please triage?
