### ISSUE TITLE
Selecting all text from messages tab isn't possible

### ISSUE THREAD

**Issue by peterrow** [microsoft/azuredatastudio#13302]
Issue Type: <b>Bug</b>

1) Output text via print statements such that there is enough lines that you have to scroll the message tab to see all the text.
2) Using mouse highlight all the text by clicking at the start of the text and holding the mouse button whilst you scroll down.
3) Press Ctrl-C to copy.
4) In text editor of your choice press Ctrl-V to paste. [BUG]: It only copied the text that was visible in the message tab at the time you press Ctrl-C rather than all the text that was highlighted!

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
import|Mic|1.1.0
profiler|Mic|0.11.0
azdata-sanddance|msr|3.1.0

</details>

**Comment by kburtram** [comment]
There is an context menu "Copy All" that can be used to copy the entire message output.  Hopefully that helps with what you're trying to accomplish.  Though there are some issues selecting long blocks of text in that UI that should be improved.

![image](https://user-images.githubusercontent.com/599935/130506571-8a816568-4c82-4c29-813a-302268b1e9e9.png)

**Comment by alanrenmsft** [comment]
same as https://github.com/microsoft/azuredatastudio/issues/13774
