### ISSUE TITLE
PySpark Notebooks don't work 

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#13307]
- Azure Data Studio Version: 1.23.0 and 1.24.0-insiders 

Steps to Reproduce:

1. Create a new notebook
2. Change Kernel to PySpark
3. Add a code cell with ANY code (e.g.: "import pandas")
4. connect to a server that supports PySpark (e.g. BDC)
5. run the notebook

Result: 

The code failed because of a fatal error:
	Failed to change language to python.
Exception details:
	"'Namespace' object has no attribute 'url'".

Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.

The issue can be resolved by downgrading the sparkmagic package from 0.17.0 (latest) to any previous

**Comment by chlafreniere** [comment]
@VasuBhog can you work with Stuart on this one?

**Comment by VasuBhog** [comment]
I am able to repro the issue in ADS and Jupyter Notebook as shown below. I believe this is an issue with sparkmagic, which I will continue to investigate, as downgrading seems to be the only workaround at the moment to resolve this. 

![image](https://user-images.githubusercontent.com/23587151/98864261-323f3c80-242f-11eb-8db3-4cec2264c061.png)

**Comment by VasuBhog** [comment]
@bweissman this issue has been identified as an issue with the 0.17.0 release and therefore can be tracked [here](https://github.com/jupyter-incubator/sparkmagic/issues/683). For now, I would downgrade as you had suggested to an older version till this issue is patched in.

**Comment by VasuBhog** [comment]
@bweissman this is now fixed with the new patch release of [sparkmagic 0.17.1](https://github.com/jupyter-incubator/sparkmagic/releases/tag/0.17.1). You can go ahead and upgrade using the package manager within ADS.
