### ISSUE TITLE
Error expanding Azure account node

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#13303]
From https://github.com/microsoft/azuredatastudio/issues/13297#issuecomment-723369814

> I'm getting this error expanding one of my accounts in the Azure view in the 1.24 build. I didn't see this error on the 1.23 build. Refreshing the account didn't change the error and I'm hitting the same error on multiple machines.
> 
> ![image](https://user-images.githubusercontent.com/599935/98428400-27af2c80-2056-11eb-8a9c-f546f63f299c.png)

**Comment by cssuh** [comment]
if you open the developer tools console when you see this error, are there any error messages?
