### ISSUE TITLE
Parameterized notebook reorders column values when executed

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13304]
- Azure Data Studio Version:
Version: 1.24.0-rc1 (user setup)
Commit: 582a3c05fdff72ff5e1af5bc68adbadd5eaf35a5
Date: 2020-11-07T03:04:12.672Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a Kqlmagic query connecting to the help.kusto.windows.net.
2. Write the following query and you'll see that the column ordering is not good. 
``` %kql StormEvents | take 10```

Note: I've shared the notebook with @VasuBhog and @chlafreniere earlier. But will upload again here soon as a reference.

Expected: column values are assigned to the appropriate columns.
Workaround: nothing that is sustainable. Users are limited to displaying the columns based on the column name order..

**Comment by VasuBhog** [comment]
I will investigate, as I believe this is something Papermill handles in regard to the output structure.

**Comment by VasuBhog** [comment]
After some investigation, I found that even Jupyter Notebook repros this issue if I set up a KQL magic notebook there. Moreover, I found that both the command line and python API papermill produce the same resulting issue of reordering the data but not the column headers (slightly different issues it seems than @MsSQLGirl). 

I will open an issue on papermill's end to get more feedback as I believe it is solely based around the execution of papermill. 

![image](https://user-images.githubusercontent.com/23587151/99109742-e2877f00-25ae-11eb-9f57-597e14495ded.png)
**Left**: ADS execution of notebook
**Right**: Papermill execution of notebook

**Comment by chlafreniere** [comment]
@VasuBhog let's try to get this one in for December. If you need help, please let me know.

**Comment by VasuBhog** [comment]
Sure thing @chlafreniere. After further investigation this seems to be an issue on the table rendering on our end, so will debug and address the fix.

**Comment by kburtram** [comment]
Approved in shiproom
