### ISSUE TITLE
SQL MI and Postgres wizard can be closed to open notebook even when passwords do not match

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#13319]
**Repro:**
1. Run ADS from the latest development code in the Main branch.
2. New Deployment ... -> Azure Sql managed Instance - Azure Arc -> Select
3. Check the terms of use -> Next

**Actual:** It is possible to click 'Script to notebook' to close the wizard and open the notebook to execute when the password values entered do not match.

**Expected:** An error should be shown about mismatching passwords and the user should not be able to end the wizard and open the notebook.

**Comment by kburtram** [comment]
@ranasaria is there any updates for this issue?  It's currently the final open issue in the Nov milestone which was originally planned for tomorrow.

**Comment by Charles-Gagnon** [comment]
Closing since this is fixed in main and we're not porting to 1.24 release
