### ISSUE TITLE
Editing of Text Automatically goes to Rich Text View instead of staying in Markdown

### ISSUE THREAD

**Issue by harlananelson** [microsoft/azuredatastudio#13316]
When I edit text, I want it to always be in markdown, not rich text.  But when I go back to edit text I have entered in markdown, the editor switches back to rich text.

**Comment by barbaravaldez** [comment]
Hi @harlananelson, by default editing is in Rich Text View. You can uncheck this option in the notebook's settings, so every time you edit a cell it goes into Split View, instead.
![Screen Shot 2020-11-09 at 1 35 58 PM](https://user-images.githubusercontent.com/34872381/98599224-819b3680-2290-11eb-824c-e537a69c7ec7.png)

**Comment by chlafreniere** [comment]
@harlananelson closing this issue as we have a setting for this. Please feel free to reopen if this doesn't solve your problem.
