### ISSUE TITLE
azdata CLI installed prompt should have a "Reload" button

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#13335]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Install azdata CLI using Azure Arc extension

Expected: If there is a prompt to restart Azure Data Studio, there is a button to do so, similar to the "Reload" button in extension manager.

Actual: Prompt to restart but no button to do so

![image](https://user-images.githubusercontent.com/599935/98708995-a518bc80-2336-11eb-988c-a5a47084fcbf.png)

**Comment by Charles-Gagnon** [comment]
The problem here is we need a full restart to pick up the env vars - not just a window reload.

We haven't really gotten any feedback on this either way - but we could look into doing what we did for deployment and just manually modify the env vars ourselves to remove this being necessary.
