### ISSUE TITLE
DeprecationWarning: Buffer()...when installing extension from command line

### ISSUE THREAD

**Issue by ThatDeaf-ITGuy** [microsoft/azuredatastudio#13332]
- Azure Data Studio Version: 1.23.0
- OS: Ubuntu 18.04 

Steps to Reproduce:

1. Try to install an extension (I used the Azure Data Studio postgres extension) using CLI options:
`../azuredatastudio --install-extension ~/Downloads/azureds_pgsqlext.vsix `

2. See depreciation warning in shell that looks like this
```shell
(node:100837) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. 
```

**To be clear, this doesn't prevent the extension from being installed.** I just noticed the warning and thought I should report it.

**Comment by Charles-Gagnon** [comment]
This is a known upstream issue so I'll close it here, but thanks for the report!
