### ISSUE TITLE
Schema compare not showing options

### ISSUE THREAD

**Issue by kakins** [microsoft/azuredatastudio#13331]
Issue Type: <b>Bug</b>

I select a db for schema compare, then select the Target ellipses and no options appear for me to select another database.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (5.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0
schema-compare|Mic|1.6.0
sql-prompt|Red|0.2.1
sql-search|Red|0.4.0
simple-data-scripter|sea|0.1.3

</details>

**Comment by kisantia** [comment]
can you please share a screenshot? Is the dialog opening but empty? It might be the same problem as https://github.com/microsoft/azuredatastudio/issues/12769 which will be fixed in the next schema compare release

**Comment by kakins** [comment]
Will do as soon as I get a chance

**Comment by kisantia** [comment]
Schema compare version 1.7.0 just got published today and should have the fix for #12769, which I think is the same issue here. Can you verify if it's fixed in the new version?

**Comment by udeeshagautam** [comment]
@kakins please let us know if you are still facing this issue. Thanks!

**Comment by kakins** [comment]
Sorry for the delay!  I downloaded the latest version and it appears to work now, thanks!
