### ISSUE TITLE
KeyError: 'AZDATA_NB_VAR_KUBECTL' when running the Arc DC create wizard/notebook on insiders build

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13365]
- Azure Data Studio Version:

Steps to Reproduce:

1.Go through Arc DC wizard
2. Get to the end and click Deploy
3. Notebook comes up and starts executing.
4. Create Azure Arc Data Controller cell fails with the following error:

KeyError                                  Traceback (most recent call last)
<ipython-input-6-8c2870a028b8> in <module>
      4 os.environ["AZDATA_PASSWORD"] = arc_admin_password
      5 if os.name == 'nt':
----> 6     print(f'If you don\'t see output produced by azdata, you can run the following command in a terminal window to check the deployment status:\n\t {os.environ["AZDATA_NB_VAR_KUBECTL"]} get pods -n {arc_data_controller_namespace}')
      7 run_command(f'azdata arc dc create --connectivity-mode Indirect -n {arc_data_controller_name} -ns {arc_data_controller_namespace} -s {arc_subscription} -g {arc_resource_group} -l {arc_data_controller_location} -sc {arc_data_controller_storage_class} --profile-name {arc_profile}')
      8 print(f'Azure Arc Data Controller: {arc_data_controller_name} created.')

~\azuredatastudio-python\0.0.1\lib\os.py in __getitem__(self, key)
    667         except KeyError:
    668             # raise KeyError with the original key value
--> 669             raise KeyError(key) from None
    670         return self.decodevalue(value)
    671 

KeyError: 'AZDATA_NB_VAR_KUBECTL'

**Comment by Charles-Gagnon** [comment]
@ranasaria Any update on this? Are you still unable to repro this?

**Comment by ranasaria** [comment]
I have sent a pr out.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
