### ISSUE TITLE
Wrong button label - says 'Select' when it should say 'Deploy' - in Arc data controller wizard

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13364]
- Azure Data Studio Version:
Version: 1.24.0-insider
Commit: 7cd4964f353f6235f2b1281cbbe9b7875cf01e78
Date: 2020-11-10T06:40:03.265Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1.  Run the deployment wizard
2. Choose Arc data controller
3. Go through wizard until end
4. On final screen the button set is like this
![image](https://user-images.githubusercontent.com/14988070/98905385-317aca80-2470-11eb-9fe2-51bae80bf75e.png)
'Select' button should be 'Deploy'.

I've only noticed this on insiders build.  Stable says 'Deploy' not 'Select'.

**Comment by twright-msft** [comment]
Same thing for the SQL MI wizard.

**Comment by Charles-Gagnon** [comment]
This should be fixed with the latest insiders build with the fix @aasimkhan30 did yesterday - I've verified it looks correct on mine.

![image](https://user-images.githubusercontent.com/28519865/98973655-dcb76e00-24c8-11eb-8f2d-ae885a358995.png)
