### ISSUE TITLE
failed to connect

### ISSUE THREAD

**Issue by end-user** [microsoft/azuredatastudio#13377]
Issue Type: <b>Bug</b>

Attempted to connect to SQL instance

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (5.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-prompt|Red|0.2.4
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment]
@end-user did you receive any error message when trying to connect?  do you know if you can connect to the server using other tools on this client machine?

**Comment by end-user** [comment]
The big problem is I don't get an error message.  Not only can I connect to this instance with other tools, this failure is occurring while ADS is connected to the server in question.  I don't have 100% repeatability, but it does continue to happen.  Specifically I have a sql file open but disconnected.  I click the "connect" button at the top; it brings up a list of recent connections on the right; I double-click one and immediately get a little "unexpected error occurred while connecting" at the bottom. It would be helpful to know _what_ the error was, but here we are. It appears to happen with saved connections too.  Again, I can successfully connect to the server; I can also open a new query and paste and run the sql there.  I just can't connect using the button at the top.

**Comment by kburtram** [comment]
@end-user thanks for the additional context.  Could you please check the "Help->Toggle Developer Tools" console the next time you see this.  Hopefully there is a more error logging available there.

**Comment by cheenamalhotra** [comment]
Hi @end-user 

Following up on this, due to continue to experience issues with latest ADS version **1.40.1**?
Would appreciate any logs, additional info if you do observe issues.

**Comment by end-user** [comment]
tbh, this was two years ago and I don't remember exactly what I was trying to do and what wasn't working.  However with v1.40.1, I _am_ able to see Azure databases/servers, and most things work as expected (except for table "design").  So I _think_ this can be closed.
