### ISSUE TITLE
SQL to Notebook Button UI display error

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#13375]
- Azure Data Studio Version: 1.25.0-insider
Commit: 850422164c29c2765911deb9af92e20afe962db1
Date: 2020-11-12T06:45:28.501Z (12 hrs ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Open a Notebook 
2. Switch kernel to Python3, see that the Convert to SQL is greyed out but adds extra padding to the right

![image](https://user-images.githubusercontent.com/23587151/98987437-c7077000-24eb-11eb-98d8-0215e980b2b5.png)

![image](https://user-images.githubusercontent.com/23587151/98987268-ab9c6500-24eb-11eb-80c1-ba064bac2c4d.png)

Also going back to the kernel that supports the button, still has the padding issue.

**Comment by chlafreniere** [comment]
@MaddyDev can you look at this one when you have a sec? Not critical for December by any means, but a good bug for a rainy day 😄
