### ISSUE TITLE
Debian package download link broken

### ISSUE THREAD

**Issue by jimbergstrom** [microsoft/azuredatastudio#13371]
- Azure Data Studio Version: 1.24

Steps to Reproduce:

1. Visit https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15
2. Click .deb next to linux
3. Redirects to https://azuredatastudio-update.azurewebsites.net/1.24.0/linux-deb-x64/stable which ruturns a `404`

**Comment by kburtram** [comment]
@jimbergstrom there was an error during the upload publishing.  The issue should now be resolved.  Thanks for reporting.
