### ISSUE TITLE
Unable to find insights query file (SQL)

### ISSUE THREAD

**Issue by eflamm** [microsoft/azuredatastudio#13374]
Issue Type: <b>Bug</b>

When I select Manage for my on-premise sql server (2016), both widgets (BackupStatus and Database Size) on the default server management page return errors. The initial error text is: 
> Could not find query file at any of the following paths : file:///c%3A/Users/EricFlamm/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/extensions/insights-default/c%3A/Users/EricFlamm/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/extensions/insights-default/sql/backup_detail.sql

The SQL file is definitely located at the latter (/sql/) location. ADS should be able to locate it. I can not figure out where the default widgets are configured - there is no server.dashboard settings in my settings.json (user/workspace) files.

Azure Data Studio version: azuredatastudio 1.23.0 (d296b6397e0acfddc57e9085e736e084969cdaeb, 2020-10-13T23:03:09.799Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570S CPU @ 2.90GHz (4 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (6.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.1.0

</details>

**Comment by kburtram** [comment]
@eflamm are you still seeing this error with the 1.24.0 build released earlier today?

**Comment by eflamm** [comment]
No - the widgets are working again on the server dashboard.
