### ISSUE TITLE
Update project file to use BeforeBuild instead of AfterClean for SSDT roundtrip build error

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#13376]
#10882 fixed the build error in SSDT by cleaning out the generated assests.json on rebuild, but as suggested in #11114, it would be even better to have this done before build so that users can use build instead of rebuild

**Comment by simonsabin** [comment]
Just a notification this wasn't released in 0.5.1. or in 1.25.1

**Comment by kisantia** [comment]
this got checked in right after we did the 0.5.1 release, so it is planned to be included in the 0.6.0 release in February. Let us know if you would like us to release this sooner in insiders :)

**Comment by simonsabin** [comment]
I was just making a note for anyone looking that it isn't in the current build
