### ISSUE TITLE
Spurious 'Azure Data CLI' still not discovered message.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#13384]
**Steps to Reproduce:**
On a machine with no kubectl installed do the following:

1. Kickoff the 'Create Azure Arc data controller' wizard.
2. The tools requirement and eula page shows highlighting the need to install kubectl as well as providing an 'install tools' button. 
3. Install kubectl using the 'Install Tools' button on that page. Once the installation is done the page gets updated to the following:
![image](https://user-images.githubusercontent.com/41588310/99011661-77cc3a00-2501-11eb-9458-1ee0093b951e.png)

**Actual:** There is a spurious information message stating:
`Following tools: Azure Data CLI were still not discovered. Please make sure that they are installed, running and discoverable`
**Expected:** There should be no informational message stating that some tools were still not discovered when discovered paths of all tools are shown in the table below.

**ADS Version:**
_Version: 1.25.0-insider (user setup)
Commit: 8504221
Date: 2020-11-12T07:04:19.873Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042_

**Comment by Charles-Gagnon** [comment]
Almost guaranteed this is because of the initial setup time it takes for the azdata extension to activate and find azdata. If you wait ~10sec does it then work correctly?

**Comment by ranasaria** [comment]
I restarted ADS and then it worked correctly. I think it is not the 10s wait but that fact that kubectl got installed in between might be leading us to this state.
