### ISSUE TITLE
sql projects icon cutoff on mac

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#13381]
the right side of the icon is a little cutoff on mac:
![image](https://user-images.githubusercontent.com/31145923/99004298-ae9b5380-24f3-11eb-85d6-76f66dd6aba5.png)

but it looks fine on windows:
![image](https://user-images.githubusercontent.com/31145923/99008691-81eb3a00-24fb-11eb-9c01-6e2bcfa9a9fb.png)

**Comment by alanrenmsft** [comment]
You probably won't have to spend time on this if it is only on the old tree.
