### ISSUE TITLE
Be able to edit an existing connection

### ISSUE THREAD

**Issue by yooakim** [microsoft/azuredatastudio#1339]
Issue Type: <b>Feature Request</b>

I am not able to edit existing connections. It realy makes ligfe easier if there is a way to edit an existing connection.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@yooakim there should be a UI-based experience for this.  The current workaround is to edit the connection settings in the User Settings file.

**Comment by MichaelMillward** [comment]
I second this!

**Comment by smartguest** [comment]
Fixed by PR #10214
