### ISSUE TITLE
Error starting profiler: Operation not supported

### ISSUE THREAD

**Issue by gavillal** [microsoft/azuredatastudio#13399]
**ERROR Starting profiler: Operation not supported on version 10.50.1600.**

- **Azure Data Studio Version: 1.23.0**
- **Plugin: Sql Server Profiler Version: v0.11.0**
- Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
- Date: 2020-10-13T22:58:36.079Z (1 mo ago)
- VS Code: 1.49.0
- Electron: 9.2.1
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Darwin x64 19.6.0

Steps to Reproduce:

1. shift + command + p
![image](https://user-images.githubusercontent.com/74423188/99098195-4786a900-259e-11eb-828e-0df879ed8543.png)
2. Show error:
![image](https://user-images.githubusercontent.com/74423188/99098320-769d1a80-259e-11eb-809f-bec71bf398e5.png)

Help please 👍

**Comment by kburtram** [comment]
@gavillal I think this error message is referring to SQL Server version 10.50.1600 (SQL Server 2008 R2).  Unfortunately, Azure Data Studio only officially supports SQL Server 2014+.  The error message should be improved.  If possible, using SSMS SQL Profiler is probably the best option for profiling this server, though I see you're on macos and may not have that tool available..

**Comment by gavillal** [comment]
you're right, thank you very much.
