### ISSUE TITLE
Schema compare not working for SQL server databases

### ISSUE THREAD

**Issue by bakirp** [microsoft/azuredatastudio#13398]
Issue Type: <b>Bug</b>

Open Object explorer
select database
Right click database
click on Schema compare
Now try to select target Schema
it is not working

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19041

**Comment by kisantia** [comment]
which version of the schema compare extension is installed? Is the dialog to select source and target not opening? I'm unable to repro this on windows with ADS 1.24.0 and schema compare 1.6.0

**Comment by bakirp** [comment]
> which version of the schema compare extension is installed? Is the dialog to select source and target not opening? I'm unable to repro this on windows with ADS 1.24.0 and schema compare 1.6.0

I am using SQL Server Schema Compare V 1.6.0. and ADS 1.24. Please see below screenshot. After selecting source database try to select target database. If it is not re-producible in one time then try to perform same step more then 5 times. Sometime it worked and later it was not working.

![image](https://user-images.githubusercontent.com/40136516/99224120-b9aff580-280b-11eb-9852-0913fe7bff5d.png)

**Comment by kisantia** [comment]
Schema compare version 1.7.0 just got published today and should have the fix for https://github.com/microsoft/azuredatastudio/issues/12769, which I think is the same issue here. Can you verify if it's fixed in the new version?

**Comment by bakirp** [comment]
> Schema compare version 1.7.0 just got published today and should have the fix for #12769, which I think is the same issue here. Can you verify if it's fixed in the new version?

Hi @kisantia,
For me it is working now. Many thanks.

**Comment by udeeshagautam** [comment]
Closing the issue as per above confirmation. Please reactivate if you face this again.
