### ISSUE TITLE
Pressing "Page Down" or "Down Arrow" on "Edit Data" mode make much new rows

### ISSUE THREAD

**Issue by LeonxPRO** [microsoft/azuredatastudio#1340]
Issue Type: <b>Bug</b>

1. Open any table in "Data Edit" mode
2. Press "Page Down" on keyboard untill new row for inserting new data show
3. Continue press "Page Down" or "Down Arrow" on keyboard. New empty rows create again and again.

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3330 CPU @ 3.00GHz (4 x 2993)|
|Memory (System)|15.96GB (8.34GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
whoisactive|Mic|0.1.0

</details>
Reproduces only with extensions

**Comment by kburtram** [comment]
@LeonxPRO do you know if the table you tested with had an columns that required a inputted value, or where all the columns null-able or having a default value.  If none of the columns required input then the behavior sounds like 'By Design'.

**Comment by kburtram** [comment]
It looks like SSMS doesn't add a new row until at least one of the fields in the current "new row" row has been edited.  We'll switch to the SSMS behavior in a upcoming release.

**Comment by smartguest** [comment]
Pushing Page down no longer endlessly creates a new row, it's now similar to what is found in SSMS
