### ISSUE TITLE
2nd page of Arc Wizards does not load and stays blank

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#13405]
**Steps to Reproduce:**
1. Fire up an arc wizard Miaa Create/Postgres Create/DC create
2. Navigate past then Tools and Eula Page to the 2nd page.

**Actual:** The 2nd page stays blank.
![image](https://user-images.githubusercontent.com/41588310/99114345-8704c380-25a5-11eb-833c-a825ca0b5a18.png)

**Expected:** The 2nd page loads successfully and all fields are visible and usable.

**- Azure Data Studio Version:**
```
Version: 1.25.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0
```

**Comment by ranasaria** [comment]
Same behavior for Deploy SQL Server 2019 container images, asde wizard so it is widespread.

**Comment by ranasaria** [comment]
This error is seen on the console: 
[70393:1113/120548.617208:INFO:CONSOLE(144)] "%c  ERR color: #f33 Error rendering component: {0} TypeError: Cannot read property 'id' of undefined", source: file:///Users/arvranmac/git/ads/out/vs/platform/log/common/log.js (144)

**Comment by chlafreniere** [comment]
I cannot repro this issue on Insiders

**Comment by Charles-Gagnon** [comment]
I can repro and see the issue - working on it now
