### ISSUE TITLE
Build a database project from command line no longer possible with latest extension

### ISSUE THREAD

**Issue by ross-p-smith** [microsoft/azuredatastudio#13409]
- Azure Data Studio Version: 
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Install the Sql Database Projects extension and follow this guide https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line?view=sql-server-ver15#prerequisites which lists the files that are required to build a project from the command line. In version 1.3 of the extension, those files were present. In 1.4 the files are no longer copied to the \.azuredatastudio\extensions\microsoft.sql-database-projects-x.x.x\BuildDirectory\

**Comment by dzsquared** [comment]
Confirming you are on the latest version of the database projects extension, v0.4.1?  Your message mentions v1.3 and v1.4, not sure where those version numbers were coming from.
Also confirming that you have performed a build in Azure Data Studio with the latest version of the extension?  The files are placed in the folder during that first build.

**Comment by ross-p-smith** [comment]
Apologies I meant 0.3 and not 1.3. They have just come back! It was that first build that must have copied them to the folder. I had upgraded the extension today and the files were not present. Sorry for the panic. Where do these files get copied from out of interest?

Happy to close

**Comment by kisantia** [comment]
the files get copied from SqlToolsService, which gets the files from the DacFx nuget

**Comment by ross-p-smith** [comment]
Perfect - just found them - https://github.com/Microsoft/sqltoolsservice/releases/download/v3.0.0-release.52/microsoft.sqltools.servicelayer-rhel-x64-netcoreapp3.1.tar.gz
