### ISSUE TITLE
New Deployment Wizard Cannot be Closed via Escape Alone

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13406]
(Reproes in 1.24.0 and Insiders)

Launch New Deployment Wizard. You'll see something like this by default:
![image](https://user-images.githubusercontent.com/40371649/99116364-bd900d80-25a8-11eb-8d92-c0132d502673.png)

Press escape once:
![image](https://user-images.githubusercontent.com/40371649/99116389-c8e33900-25a8-11eb-80d3-d6baf033334f.png)

Now, press escape any number of times.

Expected behavior: wizard closes
Actual behavior: nothing happens

**Comment by alanrenmsft** [comment]
the escape key pressing event is swallowed by the new category list you added a while back. @aasimkhan30 , please take a look and fix it.

**Comment by aasimkhan30** [comment]
This change was fixed in the https://github.com/microsoft/vscode/pull/110760 and merged to ADS. Closing this issue for now.
