### ISSUE TITLE
Can no longer copy results from grid with embedded newlines preserved

### ISSUE THREAD

**Issue by Kanmuri** [microsoft/azuredatastudio#13417]
- Azure Data Studio Version:

Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Also tried insiders build:

Version: 1.25.0-insider (user setup)
Commit: 536628603e6df2a343f3bdf05df99e6aa0dfb706
Date: 2020-11-13T06:35:06.455Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Run a query where the results include a nvarchar column with embedded newlines
e.g.
```sql
select
N'foo
bar';
```
2. Copy the result out of the grid and paste it into another window

Expected:
```
foo
bar
```
Actual:
```
foobar
```

There was a setting (that I had set) that allowed you to turn off ADS stripping out newline when you went to copy values from the results grid. That used to be `"sql.copyRemoveNewLine": false`. Unfortunately that appears to now be an invalid configuration setting (editing `settings.json` and hovering over that setting tells me it is now an "Unknown Configuration Setting") and I am not finding a replacement. (If there is a new setting that will handle this that I'm just not seeing, I would love to know about it.)

I don't know when this broke/was removed as I had avoided updates for several months after intellisense was broken for a couple of months last year. I just recently decided to try updating to a newer version, and unfortunately ran into this issue when I did.

I have not been able to find another issue addressing this, so I am opening this issue. The issues I did find all referenced the very `sql.copyRemoveNewLine` setting that appears to no longer be valid.

**Comment by Kanmuri** [comment]
I tried rolling back by uninstalling and reinstalling successive releases (the last hotfix for a release if there were any) until I got back to the June 2020 Release (version 1.19.0). It looks like that was the last version that had the `sql.copyRemoveNewLine` config setting as being valid and the last one that properly stopped stripping out the newlines when I copy string values from the results grid.

**Comment by Charles-Gagnon** [comment]
This setting was moved and now lives under `Data` -> `Query Editor` -> `Results`

![image](https://user-images.githubusercontent.com/28519865/99304766-a864ea00-2807-11eb-8965-74dd75ce462c.png)

**Comment by Kanmuri** [comment]
Thank you very much for pointing me in the right direction. :)
