### ISSUE TITLE
Connection error with Notebook: Query failed on Notebooks

### ISSUE THREAD

**Issue by AbeOmor** [microsoft/azuredatastudio#13414]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to a server with a Notebook
2. Run the Notebook
3. Close Data Studio
4) Reopen Data Studio and run the same notebook
5. Cell don't run and give an error: Query failed: The connection does not support MultipleActiveResultSets.

I'm a PM on the AzureML team and showed this bug to @yualan 
![image](https://user-images.githubusercontent.com/9068012/99133379-951b0a00-25ce-11eb-9688-5ae254787339.png)

**Comment by chlafreniere** [comment]
@lucyzhang929 could you work with @AbeOmor and @yualan on this one? I believe this message is coming from the driver but we should understand the repro if at all possible.

**Comment by lucyzhang929** [comment]
Hi @AbeOmor, which version of ADS are you using? I was not able to repro on 1.24

**Comment by chlafreniere** [comment]
Closing since we need a bit more info here. Feel free to reopen if this is still occurring. Thanks!
