### ISSUE TITLE
Task fails with 'An exception occurred while executing a Transact-SQL statement or batch.' instead of the actual error message

### ISSUE THREAD

**Issue by Mertsch** [microsoft/azuredatastudio#13421]
**Is your feature request related to a problem? Please describe.**
When I ran a backup with the UI version of the backup wizard the backup task failed with 
```
Backup Database: Backup failed for Server 'SERVER-PC'.
An exception occurred while executing a Transact-SQL statement or batch.
```

When running the same backup request with the SQL Script generated by the UI the error message is as follows
```
Started executing query at Line 1
Msg 4208, Level 16, State 1, Line 1
The statement BACKUP LOG is not allowed while the recovery model is SIMPLE. Use BACKUP DATABASE or change the recovery model using ALTER DATABASE.
Msg 3013, Level 16, State 1, Line 1
BACKUP LOG is terminating abnormally.
Total execution time: 00:00:00.001
```

**Describe the solution or feature you'd like**
I would expect to see the actual error message in the task details. As a fairly new user, I have no idea why the backup is not working without knowing the workaround above.

**Additional context**
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z (4 days ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by erinstellato-ms** [comment]
@Mertsch Hi there - I re-tested this is version 1.34 of ADS and the correct error message displayed when I tried to run a tlog backup via T-SQL, with the database in SIMPLE recovery.  Can you please confirm this is also fixed for you?  Thank you!

**Comment by Mertsch** [comment]
Indeed
