### ISSUE TITLE
Failed to save results. 

### ISSUE THREAD

**Issue by aott88** [microsoft/azuredatastudio#13420]
Issue Type: <b>Bug</b>

Error. Failed to save to file.xlsx: The writer is closed or in error state. 

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:35:27.682Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 4, 3|
|Memory (System)|32.00GB (17.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@aott88 do you see any error messages in the "Help->Developer Tools" Console?  Any idea if there is anything noteworthy about the data being save to Excel that may be triggering the issue? i.e. is it just "typical" numeric and text data, or are there BLOB, JSON, etc. columns?

**Comment by kburtram** [comment]
Closing based on pending `Needs More Info`.  Please let us know if you are still impacted by this issue and have additional info that could help diagnosis the issue.  Thanks!

**Comment by mark-dodrill** [comment]
Seeing this also, Azure Data Studio 1.42.0, Date: 2023-03-17

notificationsAlerts.ts:42 Failed to save results. Error: Failed to save Yuriy-Results.xlsx: The Writer is closed or in error state.
onDidChangeNotification @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:575
deliver @ event.ts:779
fire @ event.ts:740
addNotification @ notifications.ts:206
notify @ notificationService.ts:137
doSave @ resultSerializer.ts:343
processTicksAndRejections @ node:internal/process/task_queues:96
log.ts:313   ERR Error loading database names for query editor  TypeError: Cannot read properties of undefined (reading 'databaseNames')
    at U.getDatabaseNames (queryActions.ts:859:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
notificationsAlerts.ts:42 Failed to save results. Error: Failed to save Yuriy-Results.xlsx: The Writer is closed or in error state.

Tried saving .csv or Excel, same results.
