### ISSUE TITLE
Import Wizard Won't Launch on Linux

### ISSUE THREAD

**Issue by mdougherty3** [microsoft/azuredatastudio#13423]
- Azure Data Studio Version: 1.24.0
- OS: Fedora 33
- Linux Kernel version: 5.8.18
- SQL Server version: 2016

Steps to Reproduce:

1. Install SQL Server Import Extension
2. Press CTRL + I or right-click a database and select 'Import Wizard'
3. Nothing happens at all

**Comment by kburtram** [comment]
@aasimkhan30 can you repro this?  any suggestions how to determine what's going on here?

**Comment by gpuma** [comment]
Same thing happens to me. On Zorin OS 15.3 with the version 1.25.1 of Azure Data Studio

**Comment by aasimkhan30** [comment]
@mdougherty3 and @gpuma can you update azure data studio and install (after uninstalling) import extension and see if it is working.

**Comment by aasimkhan30** [comment]
Closing this issue as it cannot be reproduced in the latest version.
