### ISSUE TITLE
'BACKUP DATABASE' Should be used instead of 'BACKUP LOG' for simple recovery model

### ISSUE THREAD

**Issue by Mertsch** [microsoft/azuredatastudio#13422]
- Azure Data Studio Version:
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Change a DB recovery model to simple
```
-- Change the Recovery mydb to SIMPLE - https://docs.microsoft.com/en-us/sql/relational-databases/backup-restore/view-or-change-the-recovery-model-of-a-database-sql-server
USE [master];
ALTER DATABASE [mydb] SET RECOVERY SIMPLE;
```

2. Open the Backup Wizard UI, note that the UI does know the recovery model is simple!

3. Run the backup, and fail with
```
Started executing query at Line 1
Msg 4208, Level 16, State 1, Line 1
The statement BACKUP LOG is not allowed while the recovery model is SIMPLE. Use BACKUP DATABASE or change the recovery model using ALTER DATABASE.
Msg 3013, Level 16, State 1, Line 1
BACKUP LOG is terminating abnormally.
Total execution time: 00:00:00.001
```

4. Inspect the generated script, which is
`BACKUP LOG [mydb] TO  DISK...`
instead of
`BACKUP DATABASE [mydb] TO  DISK...`

**Comment by erinstellato-ms** [comment]
@Mertsch Hi - I just tested this in version 1.34 of ADS and did not have the same behavior.  After changing to SIMPLE recovery with T-SQL, when I went to backup the database, it correctly detected the recovery model as simple and allowed me to run either a full or differential backup only.  Can you please confirm that you see the same?  Thank you!

**Comment by Mertsch** [comment]
Recovery Model is now properly detected

**Comment by erinstellato-ms** [comment]
@Mertsch Thank you for confirming!
@kburtram Would you be able to mark this as completed?  Thanks!
