### ISSUE TITLE
Machine Learning - Import Models - button to Make Predictions doesn't work

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13426]
- Azure Data Studio Version:
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

![image](https://user-images.githubusercontent.com/6405919/99217136-33080380-278c-11eb-8822-8d4e1ca0a2de.png)

Steps to Reproduce:

1. Launch ML Extension from a SQL Server 2019 instance.
2. Click on View or Import MOdels button.
3. Import a model from a file, into an existing / new model table. 
4. After successfully imported, you should see Imported Model table, which will itemize the list of the models in that table. Each row will have an icon that looks like a line chart for prediction. If you click on this icon, it does nothing.

![MLImportedModelMakePredictionIssue](https://user-images.githubusercontent.com/6405919/99216660-08697b00-278b-11eb-92ae-03ed7a00e546.gif)

Expected: Since ONNX runtime is not supported in SQL Server 2019, launching Make Prediction icon after importing a model from the View or Import Model step, should provide a graceful failure that ONNX runtime is not supported..

**Comment by MsSQLGirl** [comment]
@llali & @udeeshagautam - can you please triage?

**Comment by Charles-Gagnon** [comment]
This should be fixed by https://github.com/microsoft/azuredatastudio/pull/13540
