### ISSUE TITLE
"Open Existing" dialog uses the same icon for Project and Workspace

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#13437]
These placeholder icons need to be updated with the real icons when we get them from UX team

![image](https://user-images.githubusercontent.com/1609827/99297694-72bb0380-27fd-11eb-9fde-d1ed812a49b7.png)

Other thoughts:
* As-is, this feels like I've forced through several extra clicks, when I could've just chosen between "Open existing project" and "Open workspace" in the welcome area.
* "Enter" seems like an odd verb to use, when the user's most likely going to click the button to browse, and "location" makes it sound like I'm picking a folder rather than a file.  What about "choose project" or "select project" instead? (dropping "location" entirely.  Same comment for "Create new" dialog.

**Comment by kburtram** [comment]
Approved in shiproom
