### ISSUE TITLE
Running a cell on SQL Notebook doesn't show the affected rows.

### ISSUE THREAD

**Issue by Josersanvil** [microsoft/azuredatastudio#13433]
Issue Type: <b>Bug</b>

I was already having an issue where the psql connection is not globally available at program start on `Change Connection`, but that was an issue I learned to solve by going connecting the server first and then right clicking the name of the local psql server and clicking "New notebook" or "New query" from there, and then it was available for use. 

But the latest update brought an even more annoying issue where the output of a query from a Notebook on SQL does not show the output rows (Like they're hidden), with no way to show them.
I'm using the same connection and same notebook I was using on the previous version (that worked) but now it doesn't show the output of the queries, even when it seems like it ran successfully.

**To reproduce**:
- I'm using the `microsoft.azuredatastudio-postgresql` extension.
- Created a new server connection on PostgreSQL.
   - Connection type: PostgreSQL.
   - Server name: localhost.
   - User name: postgres.
   - Database name: mydatabase.
   - Server group: <Default>
   - Name: psql-mydatabase.
- Right click the connection on the left-side panel on `CONNECTIONS>SERVERS` and click `New notebook`.
-  Select: `Kernel: SQL` and `Attach to: psql-mydatabase`.
-  Run any query. eg: `SELECT * FROM "public.MYTABLE"`

Expected something like: 
```
(10 row(s) affected)
Total execution time: 00:00:00.023

	COL1	COL2	COL3	COL4
1     R1C1        R1C2        R1C3        R1C4
2     R2C1        R2C2        R2C3        R2C4
...
10    R10C1      R10C2      R10C3      R10C4
```
What I get: (It doesn't show the affected rows)
```
(10 row(s) affected)
Total execution time: 00:00:00.023

	COL1	COL2	COL3	COL4
```
This is something that only happens on the notebooks and not when running a direct Query (a query does show the affected rows).

I've already tried clicking "Expand cell", rebooting my system and restarting the app.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (0.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.6
azdata-sanddance|msr|3.1.0

(1 theme extensions excluded)

</details>

**Comment by pdbenbow** [comment]
I just encountered the same issue. My first screenshot below shows the output from a regular query tab. The second screenshot shows the output from a cell in my SQL notebook. I'm using v0.2.6 of the PostgreSQL extension.

![image](https://user-images.githubusercontent.com/13852613/99388723-0515e280-28a4-11eb-85cb-111ee53201e5.png)
![image](https://user-images.githubusercontent.com/13852613/99388819-2545a180-28a4-11eb-9010-951648791814.png)
![image](https://user-images.githubusercontent.com/13852613/99388888-3abacb80-28a4-11eb-813d-de6c38ff7dca.png)

**Comment by chlafreniere** [comment]
@lucyzhang929 could you take a look?
