### ISSUE TITLE
Refresh SQL project when github branch change

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#13432]
**Is your feature request related to a problem? Please describe.**
Project section in explorer doesn't update when I checkout a branch. There is not an option to refresh.

**Describe the solution or feature you'd like**
This should happen automatically when a new branch is checkout and the `sqlproj` file is different. 

**Describe alternatives you've considered**
There should be an icon to refresh and in the right click menu.

**Additional context**
Currently I have to close the Database project and open the file again.

![image](https://user-images.githubusercontent.com/33104726/99274522-4c866b00-27df-11eb-97d4-1bcd11a9133b.png)

**Comment by kisantia** [comment]
@virtualdvid in the December release, we moved projects to its own separate viewlet and there is now a "Refresh" option in the overflow '...' menu that refreshes all the projects
![image](https://user-images.githubusercontent.com/31145923/101680292-52a1ed00-3a15-11eb-8584-ad598faac00a.png)

**Comment by virtualdvid** [comment]
Awesome! I just got the update and it is there. I'll test all the new features!

**Comment by kisantia** [comment]
closing as there hasn't been activity on this issue. There is a refresh button on the projects viewlet
![image](https://user-images.githubusercontent.com/31145923/206558138-3063c348-3c57-4595-b630-841f4e8e65a5.png)
