### ISSUE TITLE
allow user to overwrite the default workspace name

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#13447]
![image](https://user-images.githubusercontent.com/13777222/99300824-ec54f080-2801-11eb-9b69-3cbd449c1a7f.png)

the project name is a good default for the workspace name, but we should also allow user to type in a name for the workspace.

**Comment by udeeshagautam** [comment]
We need to think about this in **open project** context as well - because open project  withot a workspace also create new workspace.. should we have edit options there too?
