### ISSUE TITLE
Opening an already open project should show an informational message

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13448]
It should follow the pattern followed by Projects extension (when trying to open an already opened project):
![image](https://user-images.githubusercontent.com/57200045/99306043-72286a00-2809-11eb-9005-9e7f017c3a75.png)

Steps to Reproduce:

1. Open an already opened project.

**Comment by kisantia** [comment]
@SakshiS-harma where is this happening? Did it happen with the new data workspace viewlet?

**Comment by SakshiS-harma** [comment]
@kisantia Yes, it is happening in new data workspace viewlet. If the project that a user is trying to open is already opened in the viewlet, it doesn't show any informational message (which was the case in Projects extension).
