### ISSUE TITLE
Create new Project dialog has only one template and looks incomplete

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#13442]
- Azure Data Studio Version: Dev

Steps to Reproduce:

1. Create new Project dialog has single projct type template which looks incomplete. Need Edge type template seperately

![image](https://user-images.githubusercontent.com/46980425/99299745-83b94400-2800-11eb-96ee-f608584c77bc.png)

**Comment by kisantia** [comment]
Edge template added in https://github.com/microsoft/azuredatastudio/pull/13558
