### ISSUE TITLE
workspace file should be placed in the folder user picked

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#13445]
currently the workspace file is placed under the project folder, I think it should be under the folder the user picked as workspace usually will have multiple projects.

**Comment by udeeshagautam** [comment]
No option to pick workspace location

![image](https://user-images.githubusercontent.com/46980425/99303778-4f488680-2806-11eb-9436-b6bfefb27968.png)

**Comment by dzsquared** [comment]
Right now we're in a limbo where the workspace file is placed in the project's new folder, not the folder shown in the "Location" box. (despite what the dialog says)

workspace file is going to be placed in "NewProjectLocation" folder according to dialog:
![image](https://user-images.githubusercontent.com/12227241/101295340-e8e5d100-37d1-11eb-8924-a4a3be99a542.png)

that is where the project folder is created, but no workspace file:
![image](https://user-images.githubusercontent.com/12227241/101295353-06b33600-37d2-11eb-9516-bc4adc74e128.png)

the sqlproj and the workspace together in the project folder:
![image](https://user-images.githubusercontent.com/12227241/101295362-1468bb80-37d2-11eb-9a8b-2507558d03b7.png)
