### ISSUE TITLE
When pinned to start, small icon is not correct

### ISSUE THREAD

**Issue by camaro322hp** [microsoft/azuredatastudio#13452]
- Azure Data Studio Version: 1.24.0

Steps to Reproduce:

1. Pin application to start menu
2. Right click -> Resize -> small

![icon](https://user-images.githubusercontent.com/66386436/99322047-0273a880-2824-11eb-8a1c-8a5817195ab8.png)

**Comment by camaro322hp** [comment]
FYI - The medium size icon also looks incorrect.  
![icon_medium](https://user-images.githubusercontent.com/66386436/99560290-92c40180-297a-11eb-98b4-03e6575a5cd5.png)

**Comment by Charles-Gagnon** [comment]
Re-opening for stable fix

**Comment by kburtram** [comment]
Looks fine to me with the latest builds now.

![image](https://user-images.githubusercontent.com/599935/101198099-c9a34400-3617-11eb-9235-4a7906362b46.png)

**Comment by camaro322hp** [comment]
Thank you @kburtram - icon in 1.25.0 looks great.
