### ISSUE TITLE
show more/less links on Machine Learning dashboard stop working after multiple clicks

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#13468]
works on latest stable release, but not on insider builds
![image](https://user-images.githubusercontent.com/13777222/99466434-41236480-28f1-11eb-8eb6-983f0bd0ca3a.png)

**Comment by llali** [comment]
@alanrenmsft just noticed that insider has the older version of ML. 0.4.0. The bug should be fixed after updating to 0.5.0. Created the PR to update the extension for insider here: https://github.com/microsoft/azuredatastudio/pull/13475

**Comment by alanrenmsft** [comment]
@llali are you sure? I am able to reproduce the issue with latest main branch locally.

**Comment by llali** [comment]
yeah me tool. but it looks fine in the release. Investigating ...

**Comment by alanrenmsft** [comment]
It could be changes in ADS core caused the issue... I am going to publish the 0.5.0 to insider anyway.

**Comment by llali** [comment]
yeah I see other issue with tables in ML extension as well
