### ISSUE TITLE
Problem with new icon size

### ISSUE THREAD

**Issue by ForerunnerG34** [microsoft/azuredatastudio#13471]
Issue Type: <b>Bug</b>

They new icons is good, but the sizes are implemented correctly for the Start Menu, it extends to the borders of the area without margins.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

Extensions: none

**Comment by vesselin-ag** [comment]
Experiencing the same issue with latest update:
![image](https://user-images.githubusercontent.com/62258734/99674258-d2a2eb80-2a43-11eb-8fa2-cfd03911c3b4.png)

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/13452
