### ISSUE TITLE
Extra white space in sqlproj file

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#13474]
- Azure Data Studio Version:

Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

There is a minor bug that is adding or removing a white space in the `sqlproj` file. When The file is created in VS19 or Az Data Studio one of them is adding a space at the end of some lines in the `<ItemGroup>` so when I want to verify my changes using `source control` in AzDS I got tons of changes highlighted instead of my small change.

![image](https://user-images.githubusercontent.com/33104726/99567257-d02c8d00-2982-11eb-9c30-fe2c67fa66f9.png)

Steps to Reproduce:

1. Create a project in AzDS or VS19
2. Create an object in AzDS
3. Check `sqlproj` file in `source control` in AzDS there will be highlighted lines with extra space.

![azuredatastudio_vZ68drtNSz](https://user-images.githubusercontent.com/33104726/99568154-edae2680-2983-11eb-8440-d3df1792ce82.png)

![azuredatastudio_JNw1YT8Jm6](https://user-images.githubusercontent.com/33104726/99568023-c35c6900-2983-11eb-8f28-573bb01897d2.png)

**Comment by kisantia** [comment]
I think we just need to add `whiteSpaceAtEndOfSelfclosingTag: true` to this line https://github.com/microsoft/azuredatastudio/blob/905a8a3896df15ab2c41f5a4fc6b403ac8adfd28/extensions%2Fsql-database-projects%2Fsrc%2Fmodels%2Fproject.ts#L898


but will need to do a little more testing to confirm before making this change
