### ISSUE TITLE
ML - Buttons don't showup in Table models 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#13476]
- Azure Data Studio Version:
<img width="1198" alt="Screen Shot 2020-11-18 at 1 39 00 PM" src="https://user-images.githubusercontent.com/17187348/99591394-9324c280-29a3-11eb-85aa-20c40dca71ec.png">

**Comment by Charles-Gagnon** [comment]
I have a fix for this but I need to investigate some more - I think something else might be done right here that's breaking this.
