### ISSUE TITLE
Azure Login Fails when Connecting to MI or any Azure SQL Resource

### ISSUE THREAD

**Issue by MarkTimson-BIDev** [microsoft/azuredatastudio#13470]
When Connecting to an Azure MI. I login to the Azure subscription completely fine using my orgs email address, I can see the list of all the Azure Sql Resources I have access to. 

However when attempting to connect to the resource using the Azure Resource, I expand the MI and I get this message.

`Login failed for user 'cRU64XIma3ewLqAN'.`

This looks like it is attempting to use a SQL login and not my Integrated Azure Email address Login. When Changing the Authentication to Azure Active Directory with MFA support and connect this succeeds. However then drilling into an actual Database I get the same Error as the above again. 

I was hoping this error would of been fixed by now as there is more traction with ADS. And for me this is a major adoption blocker. I dont want to have to keep changing the Authentication type every time I want to login to a resource. 

Please can the Devs prioritize this as a matter of urgency.

**Comment by MarkTimson-BIDev** [comment]
Hi,

Please can I get an update on any idea when this bug might be fixed?

Many Thanks,

**Comment by cheenamalhotra** [comment]
Hi @MarkTimson-BIDev 

This issue has been addressed with latest ADS release v1.40.1. 
We fixed the behavior where Azure tree resources were defaulting to 'Sql Login'.

I will proceed to close the issue, if you need further assistance, please feel free to re-open.
