### ISSUE TITLE
Sql notebook doesn't show data

### ISSUE THREAD

**Issue by katjakoka** [microsoft/azuredatastudio#13486]
- Azure Data Studio Version:
Version: 1.24.0
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:35:27.682Z (1 wk ago)
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. I try to execute a sql query in the notebook but don't get any data back, only the columns of the table. It looks as if there is not data in the table, however, if I run SQLQuery with the same query the data does get displayed.

<img width="1000" alt="Screenshot 2020-11-19 at 16 22 19" src="https://user-images.githubusercontent.com/74683609/99688148-c17ace80-2a85-11eb-9684-01cfc60e8152.png">
<img width="1063" alt="Screenshot 2020-11-19 at 16 19 40" src="https://user-images.githubusercontent.com/74683609/99688152-c2136500-2a85-11eb-9d76-e395ab9c4b49.png">

Why doesn't the data get displayed in the notebook by executing sql query there?

**Comment by chlafreniere** [comment]
@lucyzhang929 could you try to diagnose this particular issue?

**Comment by lucyzhang929** [comment]
Hi @katjakoka, when you execute the sql query in a notebook, do you see any errors in the debug console? You can open the debug console from here: Help menu => Toggle Developer Tools => Console tab
![Screen Shot 2020-11-19 at 8 26 47 AM](https://user-images.githubusercontent.com/23462877/99694240-0e888180-2a41-11eb-87a8-9bf6ad375227.png)

**Comment by katjakoka** [comment]
I see following when I execute the sql query in a notebook:
<img width="787" alt="Screenshot 2020-11-19 at 18 22 44" src="https://user-images.githubusercontent.com/74683609/99701120-51277980-2a94-11eb-9c6f-c6a12815dba6.png">

**Comment by kingabzpro** [comment]
I have the same issue
