### ISSUE TITLE
Icon for "no tabs" state is outdated

### ISSUE THREAD

**Issue by radentonev** [microsoft/azuredatastudio#13494]
Issue Type: <b>Bug</b>

When I don't have tabs, there s a placeholder image that shows a gray flat version of the ADS icon. This icon is a gray representation of our old icon, and should be updated.

**Current implementation:**
<img width="573" alt="Screen Shot 2020-11-19 at 4 06 44 PM" src="https://user-images.githubusercontent.com/71295692/99739702-30562880-2a82-11eb-8ba6-17c96ef0445e.png">

**What it should be changed to:**
<img width="499" alt="Screen Shot 2020-11-19 at 4 17 41 PM" src="https://user-images.githubusercontent.com/71295692/99739960-ce49f300-2a82-11eb-85c3-c31bfcb8b4b0.png">

Azure Data Studio version: azuredatastudio-insiders 1.25.0-insider (698b79f0f34ccd2b5274c61ebc6618b9f74eb65f, 2020-11-16T06:32:39.477Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
spellright|ban|3.0.52
sqldm-performance-insights|IDE|0.4.0
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.6.0
datavirtualization|Mic|1.12.0
import|Mic|1.1.0
machine-learning|Mic|1.0.0
ml-services|Mic|0.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.7.0
sql-database-projects|Mic|0.5.0
azdata-sanddance|msr|3.1.0

</details>

**Comment by abist** [comment]
@radentonev Do you have the new updated themed icon pack so we can update it?

**Comment by kburtram** [comment]
Closing older issues.
