### ISSUE TITLE
Keywords in lower case

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/azuredatastudio#13501]
Issue Type: <b>Feature Request</b>

It would be great if ADS stops converting the keywords to upper case. My code style is lower case for SQL keyworks (select, union all, delete, etc.).

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment]
Hello @ArmandoLacerda - there's a setting that controls this. Check this box and all Intellisense suggestions to lower case. Let us know if this doesn't provide the functionality you need!

![image](https://user-images.githubusercontent.com/28519865/99825346-c5513400-2b0b-11eb-8f4a-3d16b25e6b5b.png)
