### ISSUE TITLE
Lock request time out period should be editable

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#1352]
Issue Type: <b>Feature Request</b>

executed a sql query on a sql server with heavy load and the query failed with

Started executing query at Line 1
Msg 1222, Level 16, State 52, Line 1
Lock request time out period exceeded. 
Total execution time: 00:00:05.011

if i would do the same with SSMS the query would wait endless (if not manually stopped) to be able to run successfully

VS Code version: sqlops 0.28.6 (3abbc8fd9713cdf847dcde703402d10a09eaa4ec, 2018-04-24T21:19:12.047Z)
OS version: Windows_NT x64 10.0.17134

---
the same query executed successfully with SSMS after 00:01:20

**Comment by LitKnd** [comment]
When this is done, is it possible to also change the default lock timeout to unlimited / -1, like SSMS? Please let me know if you'd like a separate issue for that, can do. Just hard to figure out where the line is on something like this.

**Comment by alanrenmsft** [comment]
looks like this is already implemented.
![image](https://user-images.githubusercontent.com/13777222/204941947-ca13f15d-b940-4df2-9ab0-d8ab030651a0.png)
