### ISSUE TITLE
Projects createnew or openexisting has an odd appearing button

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#13528]
Version: 1.25.0-insider (system setup)
Commit: 0b6fb504dc13e8dec935a21b39cb266d27b71c35
Date: 2020-11-23T06:41:43.143Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. workspace pane select "create new" or "open existing"
2. button next to location appears oddly but is still clickable

![image](https://user-images.githubusercontent.com/12227241/100034517-2ea5a100-2db1-11eb-914b-e85e7de45d62.png)

![image](https://user-images.githubusercontent.com/12227241/100034534-39603600-2db1-11eb-954e-55238cd47641.png)

**Comment by Charles-Gagnon** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/commit/6e0a4f27de9199cf62ac0083c02ed2130d855d30
