### ISSUE TITLE
Ability to filter database objects by name, schema on object browser

### ISSUE THREAD

**Issue by pacorreia** [microsoft/azuredatastudio#13531]
When browsing tables, views, stored procedures, I always miss simple functionally like filtering by name and/or schema.

Be able to filter the tree view of objects like it happens on SSMS:
![image](https://user-images.githubusercontent.com/54323159/100087660-f6e93880-2e46-11eb-9b17-19e39c0ed386.png)

I don't see other alternatives

**Comment by pacorreia** [comment]
actually found a request for this with different description, I'm closing it

**Comment by mammadkoma** [comment]
How we can filter tables like SSMS by right click on Tables folder?
