### ISSUE TITLE
Notebooks: PostgreSQL - No output from queries

### ISSUE THREAD

**Issue by bjarkebrodin** [microsoft/azuredatastudio#13546]
Issue Type: <b>Bug</b>

Issue: result tables from queries in notebooks always empty, even though row count is registered correctly (for example 'select 'Hello, World!;' would output nothing but show 1 row affected). This happens 100% of the time no matter what i have changed in the environment so far. Additionally, no errors related to this seem to exist outside azureDS.

First observed after updating to latest version (11-24-2020) - unsure if related but seems suspicious.

Tried: 
- making a new notebook
- restarting azure data studio
- restarting machine
- reinstalling azure data studio
- purging azure data studio entirely, and installing again
- making a new connection
- running a wide range of queries
- switching machine (and operating system -  Windows10 and this Mac)

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:35:27.682Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|8.00GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by lucyzhang929** [comment]
Hi @bjarkebrodin, this issue has been fixed in the latest insiders version and the fix will be available in the next release as well. You can download the insiders version here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
