### ISSUE TITLE
brew update seems to take a long time

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#13556]
Steps to Reproduce:

1. Kickoff the workflow to install/upgrade azdata on MacOS.

Actual: It takes 5+ minutes to finish the operation and the user gets the impression that it has hung.
Expected: Install/upgrade finishes in less than 2 minute2.

I observed that currently on my MacOS, brew update itself is taking 6+ minutes.
![image](https://user-images.githubusercontent.com/41588310/100326207-834a4700-2f7e-11eb-833f-2b8e3086b9bd.png)
The time ' 6m 9s' in yellow on the bottom right is the amount of time taken for the last command and so that is how long it took to run brew update.

We should investigate if running 'brew update' is absolutely necessary. Brew underneath the cover runs update itself but that can be switched off using an environment variable.
https://github.com/Homebrew/brew/issues/1670

**Comment by Charles-Gagnon** [comment]
Haven't heard any other feedback about this so closing
