### ISSUE TITLE
Jupyter Notebook CSV/Excel export header duplication occuring every 500 rows

### ISSUE THREAD

**Issue by stefkruger** [microsoft/azuredatastudio#13562]
Issue Type: <b>Bug</b>

Replication use case: 
- Using a notebook containing a SQL cell.
- The SQL cell contains a SQL query that returns more than 500 result records.
- When a user tries to export the result set to CSV or Excel using the built in Jupyter notebook functionality buttons for "Save as CSV" or "Save as Excel", the headers of the dataset duplicates after every 500 lines in the resulting exported file.

Confirmed to occur without any custom extensions loaded. There doesn't appear to be any obvious configuration setting in ADS to affect this.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.1
rainbow-csv|mec|1.7.0
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.7.0
server-report|Mic|0.2.2
material-icon-theme|PKi|4.0.1
kuskus-extensions-pack|ros|1.0.1

</details>

**Comment by kburtram** [comment]
Approved in shiproom
