### ISSUE TITLE
upon editing tables in Azure data studio, last column's width size cannot be increased

### ISSUE THREAD

**Issue by himanshupanchal52** [microsoft/azuredatastudio#13566]
Issue Type: <b>Bug</b>

When a table is selected to be edited(even in sql server), there seems no possible way to increase the width of the column on the most right side.

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by smartguest** [comment]
You have to move to the very top of the column to do this, this is an aspect of a dependency that we do not have direct control over unfortunately, but it is possible to change the width of the column on the right side.
