### ISSUE TITLE
Add missing parameter to Data Workspaces "Create Project" contract

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#13575]
Tech lead port request: https://github.com/microsoft/azuredatastudio/issues/13573
Port PR: https://github.com/microsoft/azuredatastudio/pull/13574

Business justification: necessary to surface a project template specifically for SQL Edge/Streaming projects in the new Data Workspaces dialog for "Create Project"

Business risk: Low.  This adds a new parameter to pipe existing data through to the project extension.  All new logic changes take place in the extension itself (where a port isn't needed)

**Comment by kburtram** [comment]
Approved in shiproom
