### ISSUE TITLE
Enable/Disable SQLCMD button missing.

### ISSUE THREAD

**Issue by chriseaton** [microsoft/azuredatastudio#13572]
- Azure Data Studio Version: 1.24.0
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T17:54:37.927Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 4.18.0-193.28.1.el8_2.x86_64

Steps to Reproduce:

1. Open a *.sql script file.
2. Notice the Enable/Disable SQLCMD button is not appearing.
![image](https://user-images.githubusercontent.com/5247568/100662573-f00c6b00-3309-11eb-8fc0-2be89262d537.png)

![image](https://user-images.githubusercontent.com/5247568/100662592-f995d300-3309-11eb-8974-1c92c2c18351.png)

Only MS extensions installed:

![image](https://user-images.githubusercontent.com/5247568/100662728-21853680-330a-11eb-9c15-8fe56c59f291.png)

**Comment by Charles-Gagnon** [comment]
@chriseaton I'm not able to repro this myself - do you have the preview features enabled? You need that checked in order to see the SQLCMD mode button : 

![image](https://user-images.githubusercontent.com/28519865/100665426-11228b00-330d-11eb-81ad-93ba10086a19.png)

**Comment by chriseaton** [comment]
That was it! Thanks - didn't realize it was in preview!
