### ISSUE TITLE
Port request for adding a missing parameter to the new Data Workspaces contract

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#13573]
Business justification port request: https://github.com/microsoft/azuredatastudio/issues/13575
Port PR: https://github.com/microsoft/azuredatastudio/pull/13574

This change adds a missing parameter to the contract between the new Data Workspaces extension and implementing project extensions that specifies which template was selected in the New Project dialog, which is important if the extension registers multiple templates (as in the case for Database Projects registering simple sqlproj and ASDE specific sqproj).

**Comment by kburtram** [comment]
The PR can act as the port request.
