### ISSUE TITLE
Prompts for SPN information should only be shown for direct connected mode

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13588]
- Azure Data Studio Version: 1.25.0-insider

When creating an Azure Arc data controller, we should only prompt the user for the SPN information when the direct connected mode is selected.

Steps to Reproduce:

1. Create Arc data controller.
2. Get to the prompt for direct/indirect mode.
3. See that it prompts you for SPN information in both direct and indirect mode.  Should be just in direct mode.

**Comment by Charles-Gagnon** [comment]
The input boxes should be disabled when you select Indirect mode. Are you not seeing this? What's your version info?

![image](https://user-images.githubusercontent.com/28519865/100789575-7b016a00-33cb-11eb-96bb-bac6bc905217.png)
