### ISSUE TITLE
Should say 'Service Principal' instead of SPN in create Arc data controller wizard

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13589]
- Azure Data Studio Version:

'SPN' isnt really accurate anyway because SPN stands for Service Principal Name.  Here we are asking for things like ID, Tenant ID, etc.

Let's spell it out completely to avoid any confusion about what is needed.

**Comment by Charles-Gagnon** [comment]
Re-opening for porting
