### ISSUE TITLE
Issue Reporter in ADS gives you a 'Not found' error

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13587]
I've noticed lately that when I file a bug from ADS using the Issue Reporter, when you click on the 'Preview on GitHub' button it opens a browser and gives you a 'Not found' response.

Example URL that is opened:
https://github.com/Microsoft/azuredatastudio/issues/new&title=Prompts%20for%20SPN%20information%20should%20only%20be%20shown%20for%20direct%20connected%20mode&body=%0AIssue%20Type%3A%20%3Cb%3EBug%3C%2Fb%3E%0A%0AWhen%20creating%20an%20Azure%20Arc%20data%20controller%2C%20we%20should%20only%20prompt%20the%20user%20for%20the%20SPN%20information%20when%20the%20direct%20connected%20mode%20is%20selected.%0A%0AExtension%20version%3A%200.6.3%0AAzure%20Data%20Studio%20version%3A%20azuredatastudio-insiders%201.25.0-insider%20(c7cca5afea12f977e66f0d078222ca95394b2f79%2C%202020-11-19T08%3A39%3A47.479Z)%0AOS%20version%3A%20Windows_NT%20x64%2010.0.19042%0A%0A%0A%3C!--%20generated%20by%20issue%20reporter%20--%3E

**Comment by chlafreniere** [comment]
I can repro this when choosing "An extension" for the File on field:

![image](https://user-images.githubusercontent.com/40371649/100792478-8ce50c00-33cf-11eb-9812-9a95cabd491d.png)

Spot checked a few extensions and all seem to have this behavior.
