### ISSUE TITLE
Port request for updating to latest SQL Tools Service (.61) to take DacFx fix

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#13596]
Port PR: https://github.com/microsoft/azuredatastudio/pull/13595

Business justification: Fixes a bug that prevents applying a schema compare result to a database, if that result includes Edge/Streaming objects. (Issue #13246)

Business risk: New DacFx nuget version, all P0/P1/P2 tests passed

**Comment by kburtram** [comment]
@Benjin FYI, you don't need to create a new issue for the port request.  You can use the existing issue (https://github.com/microsoft/azuredatastudio/issues/13246) for this purpose.
