### ISSUE TITLE
Should provide examples, help text, validation, and link to documentation on ADS Create data controller wizard

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#13590]
**Is your feature request related to a problem? Please describe.**
We have seen that users can oftentimes be confused by what is required for the service principal.  They need to know exactly what information we need, where to get it from, and what permissions the service principal needs to have.

**Describe the solution or feature you'd like**
Provide more information on what the user needs to provide.
Provide examples of the values we are expecting.
Validate that the provided input is valid - i.e. GUID-validation, check to see if the provided SP has the correct permissions in  Azure already.

**Describe alternatives you've considered**
None.

**Additional context**

**Comment by Charles-Gagnon** [comment]
Will be adding this once I finish up some of the other work. Do you have good descriptions of these values @twright-msft ? I was going to provide a link to https://docs.microsoft.com/en-us/azure/azure-arc/data/upload-metrics as the main source of information but if you have handy descriptions for these values that'd be appreciated.

**Comment by Charles-Gagnon** [comment]
re-opening for porting
