### ISSUE TITLE
Error in Jupyter book TOC does not contain enough information to diagnose the issue

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#13597]
- Azure Data Studio Version:

Steps to Reproduce:

1. Delete a file linked by Jupyter book.
1. Reload ADS.

ADS gives error but does not provide enough data to diagnose the error eg
<img width="235" alt="image" src="https://user-images.githubusercontent.com/29285871/100801971-97a69d80-33dd-11eb-8f5b-e52b20350d6a.png">

**Comment by barbaravaldez** [comment]
mmm does this happen when we delete the file but keep the file information in the toc?

**Comment by chlafreniere** [comment]
@barbaravaldez I've put this in January. Can we add some logs to help make this a bit easier to debug?

**Comment by barbaravaldez** [comment]
@rajeshka - I included the book title to the error message.
@chlafreniere - I'll add some logging to book operations for next release.
