### ISSUE TITLE
Final summary screen for controller deployment shows environment variables..

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#13611]
![deployment](https://user-images.githubusercontent.com/10999577/100830853-75327580-3419-11eb-957a-9cc949ec563b.png)
Issue Type: <b>Bug</b>

The final summary screen shows environment variables instead of the actual values for subscription id and location property

Azure Data Studio version: azuredatastudio-rc1 1.25.0-rc1 (d45758b4f45738daa04e7d2c19e6852836f8e338, 2020-11-30T23:46:38.747Z)
OS version: Windows_NT x64 10.0.20262

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
arc|Mic|0.6.2
azdata|Mic|0.4.0
azuredatastudio-postgresql|Mic|0.2.6

</details>

**Comment by Charles-Gagnon** [comment]
Pushed extension updates to RC build - this should be fixed once those are updated. 

![image](https://user-images.githubusercontent.com/28519865/100912863-de4fd280-3485-11eb-9d00-75c3aab65f03.png)
