### ISSUE TITLE
alter table add, keyword missed

### ISSUE THREAD

**Issue by ClutteredSchema** [microsoft/azuredatastudio#13643]
Issue Type: <b>Bug</b>

for - alter table add

'add' is not recognized as a key word

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (6.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.2
query-history|Mic|0.1.0
sql-assessment|Mic|0.5.0

</details>

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this issue myself, could you try updating to the latest version of ADS and if you're still seeing the issue reply with the statement you're using and the type of server you're connecting to?
