### ISSUE TITLE
Text cell is not visible when exiting an "empty" cell

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#13655]
- Azure Data Studio Version:
Version: 1.25.0-rc1
Commit: 2d50d2c5d1ed5f426c46e06cee436dce8debc6c9
Date: 2020-12-03T02:42:55.288Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

![Screen Shot 2020-12-03 at 2 17 24 PM](https://user-images.githubusercontent.com/34872381/101095112-467be280-3572-11eb-88ae-567f1a16f1fc.png)

Steps to Reproduce:
1. Create a new text cell
2. Press tab and exit the cell 

In version 1.24, looks like this.
![Screen Shot 2020-12-03 at 2 19 47 PM](https://user-images.githubusercontent.com/34872381/101095341-a2df0200-3572-11eb-890a-ef9b573239a8.png)

**Comment by corivera** [comment]
Looks like the text cells are getting saved in the ipynb file, but aren't getting rendered in the notebook. I'll try to take a look and see if it's a quick fix.

**Comment by chlafreniere** [comment]
Closing old issue since it likely won't meet our bar to fix anytime soon and should be a corner case (tab is converted into ```>``` in md)
