### ISSUE TITLE
Dacpac deploy page shows "already exsting database error" even when database is not present

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#13667]
- Azure Data Studio Version: 1.25 
- Dacpac ext 1.6 (not updated)

Steps to Reproduce:

1. Use dacfx wizard to deploy a Dacpac 
2. Select a dacpac , then select new DB flow 
3. add a name for DB which is not present in database
4. already existing database error keeps showing up even when the name is unique - unexpected

Workaround : It does not block the deployment so user can go through the deployment even after the error

Update : Looks like a regression but dacpac extension is not updated this release. 
Dacpac 1.6 Core 1.24 - doesnt repro
Dacpac 1.6 Core 1.25 - repros

Image for ref :
![image](https://user-images.githubusercontent.com/46980425/101120911-a3dc5780-35a3-11eb-9366-315092896ac2.png)

**Comment by udeeshagautam** [comment]
Bringing to Dec after confirming on regression

**Comment by udeeshagautam** [comment]
@Charles-Gagnon  this is postponed so not urgent but can you please let us know on below.
I debugged into this and it seems to be related to a recent validation call change in core on input box and base componnent. Do you know if we need to change the way we call validation from extensions.

**Comment by Charles-Gagnon** [comment]
You shouldn't be calling validate from extensions typically. They're supposed to validate every time the text changes.

**Comment by udeeshagautam** [comment]
Not calling validate - passing the validation function only. That has to be from extension right?

here is the code - would you be able to take a look (okay if post release)
https://github.com/microsoft/azuredatastudio/blob/0c82024cf36d8e2f8887cc2d4bbdf3181dc85103/extensions/dacpac/src/wizard/api/dacFxConfigPage.ts#L76

**Comment by Charles-Gagnon** [comment]
That should be fine. Is this function not being called when you update the text (delete a character or whatever)?

**Comment by udeeshagautam** [comment]
So the function is called and returns correctly - but seems like the value is not being respected and the error shows always (as in image above).

**Comment by kisantia** [comment]
only repros when the "New Database" radio button is selected after the dacpac is chosen. Doesn't happen if "New Database" is chosen before the file is chosen, so this probably has something to do with the database name getting set when the file location is selected
