### ISSUE TITLE
Keyboard shortcut and commands to navigate between the Editor, Results and Messsages

### ISSUE THREAD

**Issue by jagdishrajan** [microsoft/azuredatastudio#13661]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have just run a query by pressing F5 and then I have to use the mouse to navigate to the results pane or the messages pane.  The toggle query results (Shift+Windows+R) works but it doesn't place the focus on the Results pane.

**Describe the solution or feature you'd like**
I would like keyboard shortcuts to place focus directly on the Results pane, the Message pane and back on the Editor pane (which could be the existing Ctrl+1 for group 1 or Focus Current Query).  I also need a shortcut to navigate between the datasets if multiple datasets are returned.

**Describe alternatives you've considered**
An alternative would be a lesser keyboard shortcut like F6 in SQL Management Studio which cycles between the Editor pane, Results pane and Messages pane.

**Additional context**
If we want to use the existing Shift+Windows+R for toggling the Results pane, then it should also place focus on the first or most recent result set.  Then have a shortcut like F6 and Shift F6 that allows you to navigate between the results.  On pressing Shift+Windows+R again the results are hidden and focus is on the Editor pane.
Shift+Windows+M could be the shortcut for the Messages pane.

**Comment by kburtram** [comment]
@alanrenmsft I thought we had all the shortcuts mentioned in this issue in order to meet accessibility compliance.  Do you know what the current shortcuts are and if they can be remapped in the keymap editor?

**Comment by alanrenmsft** [comment]
let me have a look at it.

**Comment by alanrenmsft** [comment]
@kburtram apparently we don't have it shortcut keys to switch between the "views", when I joined ADS team there are only a few accessibility bugs remaining, I don't remember seeing such issues/requirements for accessibility.

I think this is a relative small task and let me try to get this done in Jan release milestone.

**Comment by alanrenmsft** [comment]
@jagdishrajan I added a shortcut key to switch between the results area and query editor area. Win+SHIFT+F.

**Comment by alanrenmsft** [comment]
![abc](https://user-images.githubusercontent.com/13777222/103966550-ebab4d00-5114-11eb-9525-f27e030a8964.gif)
@jagdishrajan this is how it looks like

**Comment by jagdishrajan** [comment]
The Win+SHIFT+F only puts focus on the title of the Results pane.  Can we have it actually put focus on the results?  Pressing it again should put focus on the body of the Messages pane and pressing it again should put focus back on the editor pane.  Right now after focus is on the title you still have to hit TAB to put focus on the body or the results cells.
