### ISSUE TITLE
Resource Deployment shows missing tools after auto-installing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#13679]
1. Start with kubectl/azdata installed but not az
1. Start BDC deployment
1. It'll prompt to auto-install az, let it do so
1. After it's done this warning message is shown : 

![image](https://user-images.githubusercontent.com/28519865/101203181-281ff080-361f-11eb-87a9-68c837cd6c0b.png)

But as you can see from the table it apparently was able to find those tools just fine.

**Comment by ranasaria** [comment]
Please note that the wizard is unusable in this state. The only workaround is to cancel out of the wizard and launch it again. The all tools are discovered, and the wizard proceeds to the 2nd page.
