### ISSUE TITLE
"No workspace open" message isn't completely correct

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13678]
With no workspace open, the message in Projects is a little delusional
![image](https://user-images.githubusercontent.com/57200045/101202556-49cca800-361e-11eb-8711-4be7987e0a71.png)

There is no way to create a workspace from "Create new" button.

Also, in future when other type of projects contribute to workspace here, presenting information of "Sql Database projects" specifically will be incomplete/shouldn't be presented, since it will become a big list.
![image](https://user-images.githubusercontent.com/57200045/101202530-3e797c80-361e-11eb-8d8b-44d40672d84d.png)

**Comment by simonsabin** [comment]
Interested as to why a workspace is now needed?

**Comment by dzsquared** [comment]
1. "Create new or open existing to get started."
2. "To learn more about projects read our docs."

**Comment by simonsabin** [comment]
Hey Drew,
Any comment about why a workspace is needed? I've found the requirement quite intrusive since its introduction

**Comment by dzsquared** [comment]
@simonsabin - the workspace supports managing additional settings around the project. I would be interested in knowing how it is causing friction for you so we can streamline

**Comment by dzsquared** [comment]
@SakshiS-harma - new docs link https://aka.ms/azuredatastudio-projects

**Comment by simonsabin** [comment]
On the workspace aspect and also the project view #11349
* For no other projects we develop in VS Code do we use workspace and thus the need to create one is odd
* The language about New, Open Existing, feel odd when you have projects already "open" in the folder you've got open.
* The approach of "hiding the project file" and having a different folder view hiding files seems totally against the clarity model that has been pushed in VScode and the modern project approach.
* Adding existing files isn't possible
* moving files and folders you now have two different approaches, if you do it in  

I'm interested to know what other settings are possible with workspaces. It feels its being introduced to support the legacy model for projects co developed with Visual Studio, and thus the complexity that involves. 
It feels the direction is going away from approach in vscode
