### ISSUE TITLE
No informational message presented before overwriting workspace file

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#13677]
Steps to Reproduce:

1. Open an existing workspace with a few projects in it.
![image](https://user-images.githubusercontent.com/57200045/101201163-21dc4500-361c-11eb-893c-0dbd4cf1936e.png)

2. Close workspace (all opened projects are removed).
![image](https://user-images.githubusercontent.com/57200045/101201983-716f4080-361d-11eb-9237-893e2b8f1e70.png)

3. Open a project, for which the sqlproj and workspace file exist in the same folder, with same name
[To have sqlproj and workspace under same folder: simply create a new project (or create project from database) with no workspace opened. This will create the project with a workspace file along side, in the same folder (with same name).]
![image](https://user-images.githubusercontent.com/57200045/101201253-4cc69900-361c-11eb-8f49-a50a4345d5c0.png)

4.  Since no workspace is currently open, it creates a new workspace with the same name as project in the same folder, overwriting the older workspace file. 
![image](https://user-images.githubusercontent.com/57200045/101201813-29501e00-361d-11eb-8872-00db4ea150ad.png)

Expectation: atleast an informational error should be presented informing that the workspace file with same name exists and content will be overwritten.
Better outcome: Give user an option to chose if workspace file should be overwritten.

**Comment by kisantia** [comment]
dup of #13453
