### ISSUE TITLE
Jupyter Book: Dots on sections in a book appearing - unrelated to changes

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13688]
- Azure Data Studio Version:
Version: 1.25.0-insider (user setup)
Commit: 6f731fcd9e545acb4680744eda55d5358dd551c5
Date: 2020-12-03T06:32:49.293Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

- Also happening on 
Version: 1.24.0 (user setup)
Commit: eb3c0f5d9df86b9490606aab7fffaa253b0aca4d
Date: 2020-11-10T23:38:09.705Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a jupyter book. 
2. Make changes to a notebook file. (On the screenshot, the file I updated is red circled 1)
3. Navigate to Notebook viewlet. All the sections belonging to the same notebook will be marked with dots. The file that you made changes didn't. 

![image](https://user-images.githubusercontent.com/6405919/101227255-0ee16900-364c-11eb-9abd-3d1938ae8548.png)

Questions / comments:
1. What do the dots represent?
2. Concerns: it may distract or give the wrong signals for users who make lots of changes to notebook files.

**Comment by Charles-Gagnon** [comment]
@barbaravaldez If you're looking at this could you assign the triage tag and put in the proper milestone?
