### ISSUE TITLE
Add Support for Other SQL Languages (Databricks, Spark)

### ISSUE THREAD

**Issue by sebcruz** [microsoft/azuredatastudio#1368]
Extending the scope of SQL Ops Studio to go beyond SQL Server to include emerging SQL-like technologies. I'd love the ability to connect to and execute queries against Databricks (Spark SQL), Hadoop Clusters, U-SQL, other open source databases.  Sure some of those are supported in VSCode, but the experience isn't as great as what you have created in SQL Ops Studio.

**Comment by kburtram** [comment]
Closing older issues.  We provide an extensibility model that allows alternate data providers to be added if desired.  Thanks for the suggestion!
