### ISSUE TITLE
SQL editor fails to execute a query when a file path contains '%20'

### ISSUE THREAD

**Issue by pensivebrian** [microsoft/azuredatastudio#13684]
Steps to Reproduce:

1. Create a .sql file with a %20 in the path: C:\Temp\Folder%20Repro\test.sql
2. Open and execute a query from the file in ADS

Result: The query fails to execute and the error popup appears to file an issue

This issue was discovered investigating the same behavior #10259 for notebooks. It appears the root cause is the sql tools service does not encode the ownerUri string before instantiating the System.Uri, which causes the %20 to be decoded as a space. Once this happens the ownerUri won't match the value used by the ADS client which expects the %20 since it's part of the path. The fix should be to encode the ownerUri before instantiating the System.Uri.

The notebooks issue is different since it takes a different code path in the sql tools service, that doesn't involve System.Uri, so only a fix in ADS is needed.

Folks are hitting this when they clone a repro in github or Azure DevOps with a SPACE in the file name. The git clone uri contains the %20 which is encoded in the folder name.

**Comment by kburtram** [comment]
This appears to be working fine on current builds.  Please let us know if this is still impacting your use case.

![image](https://user-images.githubusercontent.com/599935/129844560-e00ab9e0-aa61-48cf-b57f-2126a7598647.png)
