### ISSUE TITLE
Create data controller wizard shows a blank screen for choosing config profile step in Insider version 

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#13699]
- Azure Data Studio Version:
Version: 1.26.0-insider (user setup)
Commit: a70dce785574d26d40fabc8d829f48f807f75195
Date: 2020-12-07T06:51:37.898Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Launch ADS
2. Initiate the Create data controller wizard
3. When you get to Step 3: Choose the config profle, it shows a blank screen.

I am able to proceed to next/previous step in the wizard.. 

![image](https://user-images.githubusercontent.com/43253513/101379916-b5568580-3869-11eb-88b5-54776c899bcb.png)

**Comment by Charles-Gagnon** [comment]
How long did you wait? It can sometimes take 5-10 seconds to load.

Is there any error in the console logs?

**Comment by dnethi** [comment]
[20201207T080644.zip](https://github.com/microsoft/azuredatastudio/files/5656006/20201207T080644.zip)

**Comment by Charles-Gagnon** [comment]
It looks like you're using the insiders version of ADS - currently there's some issues with the extension there. I'll be getting a new version out in the next day or two so let's have you try again once that's out to see if you're still not seeing the options.

**Comment by Charles-Gagnon** [comment]
@dnethi I just updated the insiders extension version, I'm going to close this since I haven't seen it and if you see this issue again let me know

**Comment by snaldurgkar** [comment]
seeing same issue - Create data controller wizard shows a blank screen for choosing config profile step. 
Azure data studio is running on Mac OS BigSur 11.5.2
Azure data studio Version: 1.32.0
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:09:20.282Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0

**Comment by snaldurgkar** [comment]
20201207T080644.zip

**Comment by snaldurgkar** [comment]
20210901T185839.zip
