### ISSUE TITLE
Default Note book text cell editor to Markdown

### ISSUE THREAD

**Issue by alevyinroc** [microsoft/azuredatastudio#13696]
I prefer to do my text editing using plain Markdown, not toolbar-based WYSIWYG editing. It's rather frustrating to have to switch from WYSIWYG mode to Markdown or "split" mode every time I edit a text cell.

**Describe the solution or feature you'd like**
I would like to have the ability to default text cell editing to Markdown mode, either as a setting for each notebook or globally across my Azure Data Studio preferences.

**Comment by Charles-Gagnon** [comment]
@alevyinroc You can change the default mode in the settings with this option - unchecking it will default to the "split mode" editing

![image](https://user-images.githubusercontent.com/28519865/101394627-a7aafb00-387d-11eb-9d3e-cd24303d3f7b.png)

**Comment by chlafreniere** [comment]
@alevyinroc closing this as we have the setting that controls this behavior. Please feel free to reopen if that setting doesn't meet your needs.
