### ISSUE TITLE
Copy with Query Results : Ctrl+Alt Keybindings should not be used by default

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#13703]
Per https://github.com/microsoft/azuredatastudio/blob/main/src%2Fvs%2Fplatform%2Fkeybinding%2Fcommon%2FkeybindingsRegistry.ts#L210 we shouldn't be using ctrl+alt keybindings by default for Windows.

I can't recall the exact reasonings behind this but I believe there's two main issues : 

1. They're used for unicode support
1. They're often used for accessibility controls

So overriding that will negatively affect both of these

**Comment by Charles-Gagnon** [comment]
@gupta1 @qifahs

**Comment by MsSQLGirl** [comment]
Thanks @Charles-Gagnon for the feedback. 

@qifahs  @gupta1 - can we use Ctrl + K Ctrl + R combo?
It seems that ADS is still using Ctrl + Alt + C right now.
