### ISSUE TITLE
Save As CSV/Excel repeats header every 500-ish rows

### ISSUE THREAD

**Issue by leonpeeters** [microsoft/azuredatastudio#13721]
Issue Type: <b>Bug</b>

- Ensure that queryEditor.results.saveAsCsv.includeHeaders = True
- In a notebook, run a SQL query that returns at least, say, 1100 rows
- On the result, click the "Save As CSV" or "Save As Excel" button 
- The resulting file contains the header on row 1 and row 502 (and rows 1+501*k in general for larger outputs)

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (3.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.1.0

</details>

**Comment by lucyzhang929** [comment]
Hi @leonpeeters, this issue has been fixed in insiders which can be downloaded here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main. The next release, 1.25.0, will also contain the fix.
I will close this issue for now, please feel free to re-open if you have any other questions.

**Comment by leonpeeters** [comment]
Thank you @lucyzhang929 !
