### ISSUE TITLE
Kusto Notebooks Show SQL as Kernel on Reopen

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13737]
- Azure Data Studio Version:
Version: 1.25.0-rc1 (user setup)
Commit: 634ea0ab6a60543d712dbc77266059de1d70c08c
Date: 2020-12-08T19:09:44.467Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a new notebook connecting to ~Python~ KQL Kernel. 
2. Save the file.
3. Reopen it. The kernel will not be set to ~Python~ KQL and will get changed back to the default, which is SQL.

An additional ask would be to remember the default connection string / compute location, where applicable.

**Comment by chlafreniere** [comment]
@MsSQLGirl I cannot repro, either on Windows or on Mac. Using the 1.25 (stable). Let's sync offline on this, because that's quite concerning.

**Comment by MsSQLGirl** [comment]
Updating the description. It is an issue for KQL (not Python. apologies.

**Comment by VasuBhog** [comment]
@MsSQLGirl just want to confirm, this is for the Kusto Kernel correct? I believe that this issue would be similar: #12566.

**Comment by MsSQLGirl** [comment]
@VasuBhog  - yes similar, but this one only concerns on the Kusto kernel (and not the connection strings / Attach To details)

**Comment by qifahs** [comment]
This is important for livesite customers. It is not intuitive for the customer to realize that there is a Kusto query on the Notebook, and switch the kernel dropdown to Kusto, before choosing the connection. If a Notebook was saved with the Kusto kernel displayed in the dropdown, it should re-open with the same kernel displayed, and not switch back to displaying SQL.

**Comment by chlafreniere** [comment]
@MsSQLGirl need your help with priority here. Any chance that you could help?

**Comment by MsSQLGirl** [comment]
This issue is now tracked here: 14545
