### ISSUE TITLE
SQL Server Agent does not show even after installing latest version and Admin Pack for SQL Server extension

### ISSUE THREAD

**Issue by anirbanbagchi** [microsoft/azuredatastudio#13741]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install Azure Data Studio 1.25.0 on Windows 10 Enterprise Edition.
2. Install Admin Pack for SQL Server extension. If required restart or reload application.
3. Connect to SQL Server instance where you have sysadmin or relevant permission to view/edit SQL Server Agent jobs.
4. SQL Server Agent option is not available when you select your database instance and go to Manage.

![Screenshot-1](https://user-images.githubusercontent.com/8215315/101697360-4f225c00-3a3d-11eb-986a-bd8936a9388c.png)
![Screenshot-2](https://user-images.githubusercontent.com/8215315/101697362-4fbaf280-3a3d-11eb-8836-153b94c37042.png)

**Comment by kburtram** [comment]
@abist can you double-check this and see if we need to push an agent update?

**Comment by kburtram** [comment]
@anirbanbagchi I wasn't able to repro this.  Could you please check that you have Preview Features enabled in the User Settings?  This is required to show the Agents tab in dashboard?

**Comment by abist** [comment]
@kburtram I wasn't able to repro this. 
@anirbanbagchi Could you open the Console (Help -> Toggle Developer Tools -> Console) and see if there are any errors there?

**Comment by anirbanbagchi** [comment]
@kburtram Can you let me know which option to check for. I was able to locate settings but unable to find anything that say something like Enable Preview.

**Comment by abist** [comment]
@anirbanbagchi 
![Screen Shot 2020-12-09 at 4 49 47 PM](https://user-images.githubusercontent.com/6411451/101706728-9826e000-3a3e-11eb-9e54-1e4f2e7630f1.png)

**Comment by anirbanbagchi** [comment]
@abist Got it. Thanks. It's working fine now.
