### ISSUE TITLE
Export To Notebook for SQL results skipped comments

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13745]
- Azure Data Studio Version:
Version: 1.25.0 (user setup)
Commit: 8c6bd8c857592c14afbb589a7d307baec1f5b5ed
Date: 2020-12-05T06:45:46.586Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open SampleSQL.sql file from https://gist.github.com/MsSQLGirl/00149be9684476c8619f8d1ef8bee4bc in Azure Data Studio.
2. Convert to this file to Notebook with "Export To Notebook" button.
3. You should see an output like SampleSQLActual.ipynb https://gist.github.com/MsSQLGirl/00149be9684476c8619f8d1ef8bee4bc in Azure Data Studio.
4. This output is missing the middle comments, i.e. 
```
-- Search for Text Inside All the SQL Procedure
```
and 
```
-- Compare Row Counts in Tables From Two Different Databases With the Same Schema
```

Expected outcome: SampleSQLExpected.ipynb https://gist.github.com/MsSQLGirl/00149be9684476c8619f8d1ef8bee4bc 

Missing items are circled in 1 and 2:
![image](https://user-images.githubusercontent.com/6405919/101714718-f2c83800-3a4e-11eb-91d6-6414984e94e7.png)

**Comment by Charles-Gagnon** [comment]
This should be fixed now
