### ISSUE TITLE
'Close all Windows' behaviour

### ISSUE THREAD

**Issue by zotrb** [microsoft/azuredatastudio#13750]
Issue Type: <b>Bug Report</b>

Close All Windows has two disappointing features:

1) It doesn't close all the windows. It stops and askes the user to confirm the close of every modified window in turn. This takes away the benefit of this really useful command.

2) It doesn't use the same key binding (Alt+W+L) as in Visual Studio and SSMS, which is a frustrating inconsistency when switching frequently between these 3 tools. 

Azure Data Studio version: azuredatastudio 1.25.0 (8c6bd8c857592c14afbb589a7d307baec1f5b5ed, 2020-12-05T06:45:46.586Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alanrenmsft** [comment]
@zotrb, thank you for opening the issue, unfortunately this is a feature we inherit from VSCode. 
the first issue is being tracked by: https://github.com/microsoft/vscode/issues/111973. regarding to the shortcut keys, yeah, I don't know why they decided to use different keys to begin with. you can follow the instructions here: https://code.visualstudio.com/docs/getstarted/keybindings to update the default shortcut key bindings. it is for vscode but also works for ADS.
