### ISSUE TITLE
it never connects to the db on first instance

### ISSUE THREAD

**Issue by mohitKhanna1411** [microsoft/azuredatastudio#13768]
Issue Type: <b>Bug</b>

it never connects to the db on first instance,m I always have to kill the app and try in again.

Azure Data Studio version: azuredatastudio 1.25.0 (8c6bd8c857592c14afbb589a7d307baec1f5b5ed, 2020-12-05T06:43:11.244Z)
OS version: Darwin x64 20.1.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 5, 10|
|Memory (System)|8.00GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cssuh** [comment]
No additional info was provided
