### ISSUE TITLE
Populate Binary Versions of SQLOps Studio Package

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#1378]
- SQL Operations Studio Version:
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
when i look at the versions of files of SQLOps studio apart from SQLOps.exe i dont see any versions for the respective dependent binaries.

![binaryversions](https://user-images.githubusercontent.com/27516588/39832510-0098d956-53e5-11e8-86cd-439005d9dcc4.png)

**Comment by llali** [comment]
@MattIrv is this a build issue? do you know why the version are missing from the dlls?

**Comment by MattIrv** [comment]
I'm not entirely sure what it would involve but I suspect we'd have to set the version as part of the build configuration and don't currently do so.

That should be fine, though it would be a bit of work since right now the version is only calculated after the build by the release script

**Comment by kburtram** [comment]
Closing older issues that are scheduled in an upcoming milestone.  Please let us know if this is still impacting your workflow.  Thanks!
