### ISSUE TITLE
SQL Connection recovery after it expires

### ISSUE THREAD

**Issue by pacorreia** [microsoft/azuredatastudio#13796]
After a connection is closed either because it timed out due to:

- inactivity
- network failure

It would be good to have the same behavior as SSMS, meaning, if we run a query again, it will try to connect using the existing tokens in cache, credentials, etc.

Currently it behaves like this:

1. First attempt it shows this:
`Started executing query at Line 55
Msg 18456, Level 14, State 233, Line 1
Login failed for user '<token-identified principal>'. Token is expired.
Total execution time: 00:00:00.379
Total execution time: 00:00:00.379`
2. attempt ane next ones gives this:
`Total execution time: 00:00:00`

I have to force a disconnect/change connection on top to same connection to make it work again.

The behavior that I would expect is at least:

1. 1st tell the connection is closed
2. 2nd attempt will open it if possible and run the desired action.

This is valid in server connections panel and/or open queries

I have reasons believe this is a quick improvement that have lot's of minutes per day 👍

**Comment by Rohansi** [comment]
This is a very annoying one. It's the one thing that makes me close Azure Data Studio and switch to SQL Server Management Studio  - because it doesn't have this problem at all even when it's the same database with the same authentication and everything.

**Comment by Charles-Gagnon** [comment]
@caohai Your PR should have improved this scenario right? https://github.com/microsoft/azuredatastudio/pull/16936

@Rohansi could you try using the [latest insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master) and let us know if you continue seeing this issue?

**Comment by caohai** [comment]
> @caohai Your PR should have improved this scenario right? #16936
> 
> @Rohansi could you try using the [latest insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master) and let us know if you continue seeing this issue?

The error message is the same as the one I looked into. It should be fixed if AAD with MFA auth is used.

@Rohansi Are you using AAD with MFA auth for your connections?

**Comment by Rohansi** [comment]
Yes, I'm using AAD with MFA auth. I'll give that a try - thanks!

That PR looks like it only fixes the issue with running queries from the editor. When the token is refreshed does it also refresh for other parts of the UI? Is there a GitHub issue for tracking the remaining items, including the connection panel (expanding tables etc.), IntelliSense, notebooks, etc.? Or is it this one?

**Comment by caohai** [comment]
> Yes, I'm using AAD with MFA auth. I'll give that a try - thanks!
> 
> That PR looks like it only fixes the issue with running queries from the editor. When the token is refreshed does it also refresh for other parts of the UI? Is there a GitHub issue for tracking the remaining items, including the connection panel (expanding tables etc.), IntelliSense, notebooks, etc.? Or is it this one?

@Rohansi Yes the fix is currently only scoped to query editor as it's the most common scenario people get this issue. We are currently looking into other parts as well and I will be creating issues for those soon.

**Comment by caohai** [comment]
Closing this issue as a fix for connection expiration in query editor has been merged and will be in the October release (or you can try it with the latest insiders). For tracking other AAD token expiration related issues please refer to this mega issue #17047
