### ISSUE TITLE
Provide standalone vsix download for sql project extension

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/azuredatastudio#13794]
**Is your feature request related to a problem? Please describe.**
sometimes I work in an environments where I don't have admin rights, this prevents me from installing this add-in and no vsix seems to be provided.

**Describe the solution or feature you'd like**
allow add-in to install without admin rights, provide a stand alone vsix installer for offline and administrative installs

**Describe alternatives you've considered**
This Is The way :)

**Additional context**
N/A

**Comment by kburtram** [comment]
@jasonhorner here is the link to the latest sql project extension VSIX https://sqlopsextensions.blob.core.windows.net/extensions/sql-database-projects/sql-database-projects-0.5.1.vsix.  Future versions should follow a similar file naming convention (i.e. just update the version string).

We'll look at this issue as a more general request to make it easy to download VSIX for offline install.  We do have this page for this purpose, but it doesn't look like it's being maintained consistently https://github.com/microsoft/azuredatastudio/wiki/List-of-Extensions.

**Comment by dzsquared** [comment]
@jasonhorner - you will also need the .NET Core SDK installed on the workstation to use the SQL project extension (https://dotnet.microsoft.com/download/dotnet-core/3.1)

**Comment by udeeshagautam** [comment]
Closing based on above links. Please reactivate for any further questions/issues.
