### ISSUE TITLE
Notebook padding / gaps before headings getting wider impacting readability

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13810]
- Azure Data Studio Version:
Version: 1.25.1 (user setup), 1.24.0 (user setup)

also verified on:
Version: 1.26.0-insider (user setup)
Commit: 1903388b6bb48c38f28ecbb21dd7accf4d3ea00e
Date: 2020-12-15T06:31:43.151Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a new notebook with H1. 
2. Open it in v1.23.0 as well as v1.25.1. You'll see that the padding / gap in v1.25.1 and above have increased compared to v1.23.0.

> Note: the padding / gaps in general have increased for other Heading levels also.

![image](https://user-images.githubusercontent.com/6405919/102190275-ad4fa480-3e6c-11eb-8735-0b7c27e767c0.png)

The other version - 
Version: 1.23.0 (user setup)
Commit: d296b6397e0acfddc57e9085e736e084969cdaeb
Date: 2020-10-13T23:03:09.799Z
VS Code: 1.49.0
Electron: 9.2.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by MsSQLGirl** [comment]
@halerankin - thoughts on this?

**Comment by halerankin** [comment]
@MsSQLGirl I can dive into the styles to see where that's coming from. I assume we want to decrease the gap.

**Comment by halerankin** [comment]
@MsSQLGirl Take a look at this PR. The conversation about top-padding in edit versus preview led to adding the additional 14px on top. I can remove it but height difference between the two modes will persist.
https://github.com/microsoft/azuredatastudio/pull/13153

**Comment by MsSQLGirl** [comment]
@halerankin - I've reviewed this on the Insiders build. The padding looks much better now :)  Thank you!

Version: 1.26.0-insider (user setup)
Commit: 30054e632c75f8df0ea351f2c51b8ec7d5fa5be5
Date: 2020-12-30T06:36:16.231Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
