### ISSUE TITLE
Intellisense doesn't recognize "If Exists" extension of drop table, and Doesn't recognize any temptable names

### ISSUE THREAD

**Issue by ClutteredSchema** [microsoft/azuredatastudio#13814]
Issue Type: <b>Bug</b>

The below, with the SQL Type as MSSQL, will not recognize 'If Exists' nor will it recognize temp tables referenced after the create statement. 

        --Find all ID's with Changes, regardless of source
        Drop table if exists #EmployeeIDs
        Create Table #EmployeeIDs 
            (EmployeeID varchar(25) not null Primary Key Nonclustered
            ,index tmp_EmployeeIDs clustered columnstore)
        Insert Into #EmployeeIDs
        
        Select EmployeeID from ultp.MasterStaff Where SysStartTime >= @DateTime_Max_SystemModstamp
            Union
        Select EmployeeID from ultp.EmployeeChanges Where RecordValidStart >= @DateTime_Max_SystemModstamp

Drop Table If Exists #ChangeTimeline
Create Table #ChangeTimeline
    (EmployeeID varchar(25) not null
    ,ChangeDateTime datetime2 not null
    ,Constraint pk_tmp_ChangeTimeline Primary Key Nonclustered (EmployeeID, ChangeDateTime)
    ,Index ccsi_tmp_ChangeTimeline Clustered Columnstore)

Insert Into #ChangeTimeline
    Select Distinct
     ec.EmployeeID
     ,ec.ChangeDateTime 
     From ultp.EmployeeChanges as ec
     Where Exists (Select 1 from #EmployeeIDs as e Where e.EmployeeID = ec.EmployeeID )

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.5.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
datavirtualization|Mic|1.10.0
import|Mic|1.1.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
server-report|Mic|0.2.2
azdata-sanddance|msr|3.1.0
sql-search|Red|0.4.0
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this with the query you gave - could you check if this is still an issue with the latest release of ADS and if it is let me know what type of server you're connected to?
