### ISSUE TITLE
Dropdown is returning older value in onValueChange event handler 

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#13826]
@Charles-Gagnon , PR: #13691  has broken the dropdown.value. Right now, the value of the dropdown is changed after the event is fired. 

Any extensions using dropdown.value in their dropdown.onValueChange() event handler will get a stale value of the dropdown. 

Extensions affected: 
1. Import,
2. Resource Deployment

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Are you sure that this is with the current state of things and not in the branch that you've been changing? I just took a look at this and the events seem to have the expected value for both normal select boxes and editable dropdowns. 

If this is with the current stuff from main then please include instructions as to how to repro the issue in case I'm missing something.
