### ISSUE TITLE
Pyspark Kernel is not loading

### ISSUE THREAD

**Issue by emacastelli** [microsoft/azuredatastudio#13821]
Issue Type: <b>Bug</b>

Right click on BDC connection --> New Notebook --> Change kernel to Pyspark
It hungs and show an error.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:51:41.708Z)
OS version: Linux x64 5.8.0-31-generic

**Comment by emacastelli** [comment]
More info:

I tried with sparkmagic 0.15 and 0.17.1. Same behavior.

It just gets stuck in "Changing Kernel..." and fails with this error fisrt:

Failed to change kernel due to error: Canceled 

And if I try again, it fails with:

Failed to change kernel. Kernel pysparkkernel will be used. Error was: Invalid response: 404 Not Found

I would appreciate your help.

**Comment by chlafreniere** [comment]
@VasuBhog could you help here please?

**Comment by VasuBhog** [comment]
Hi @emacastelli, I am sorry to hear that you're having trouble with the pyspark kernel. I was **not** able to repro this with my **Mac** and **Windows** Machines. This may be a Linux based issue. One thing I recommend is uninstalling sparkmagic and reinstalling it to the latest.

Once you open the notebook via the BDC connection, does it set the kernel to SQL?  

![image](https://user-images.githubusercontent.com/23587151/102409358-c444e280-3fa3-11eb-80bf-2ecfc78bb5c9.png)

Python Version: 3.6
sparkmagic: 0.17.1
ADS Version: 1.25.1

**Comment by emacastelli** [comment]
Hi! I tried what you suggested but the problems its still there. 

When I open notebook from BDC it goes to SQL  kernel.

I think I could have some issue with python local installation. I have this:

![image](https://user-images.githubusercontent.com/70211371/102419666-03445980-3fdf-11eb-96b0-f44177333b0f.png)

What installation do you suggest me to choose?

**Comment by VasuBhog** [comment]
Yes, it must be a sparkmagic and python compatibility issue. I am currently using Python 3.6 on both machines and it seems to work with the newest version. Can you please try to download and use Python 3.6?

![image](https://user-images.githubusercontent.com/23587151/102522234-da59ae00-404a-11eb-8af1-23b64f155d7b.png)

**Comment by emacastelli** [comment]
Hello,

I could fix the issue. I was uninstalling / installing sparkmagic manually, from terminal. I did it again from Packages Manage and it worked. 

Thank you.

**Comment by emacastelli** [comment]
Resolved by unistalling /installing sparkmagic from Packages Manager (ADS)

**Comment by VasuBhog** [comment]
No problem :). Great to hear!
