### ISSUE TITLE
SandDance for Azure Data Studio Visualizer Not Working!

### ISSUE THREAD

**Issue by nilsut** [microsoft/azuredatastudio#13825]
I have tried this visualizer on different computers. When i tried it for the first time it worked perfectly and it was very helpful. However after i closed the app and opened it later on the extension did not work. The visualizer symbol appears but nothing happens when i clicked the button. Also the data studio is not giving any errors when i pressed the button. Later , i tried this extension on another computer and this time it didn't worked even on the first time. The visualizer extension is very beneficial and one time it worked it was very helpful. I really want to be able to use it again if somehow you can solve this problem.

**Comment by nilsut** [comment]
UPDATE: I didn't do anything different. I just uninstalled and then installed the extension as i did before on the other computer and after couple of times the visualizer now works, don't know why , don't know how ?

**Comment by nilsut** [comment]
[Logs.zip](https://github.com/microsoft/azuredatastudio/files/5705944/Logs.zip)

**Comment by alanrenmsft** [comment]
@nilsut  next time when you see the issue, aside from the logs mentioned above, please also open the developer tools and see whether there are any errors in the console:

1. Open help menu
2. pick "Toggle Developer Tools"

![image](https://user-images.githubusercontent.com/13777222/102417272-38858300-3fb0-11eb-81ab-d94a42597bc9.png)

also, in case you have any issue regarding the SandDance extension itself, please open issues here: https://github.com/microsoft/SandDance/issues

**Comment by nilsut** [comment]
Thank you for your help, so far everything is okay.

**Comment by alanrenmsft** [comment]
@nilsut unfortunately, I don't see anything useful in the logs for the issue you described, please let us know if you see it again with the developer tools console screenshot. I am going to remove the logs now and close the issue.
