### ISSUE TITLE
Connection Dialog opens twice when Launched from Notebooks

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#13837]
- Create new notebook
- Create new code cell
- Press F5 (connection dialog will appear)
- Click cancel (or press escape key)
[Nothing happens 😞]

Note: I am not able to repro this behavior for query editor.

**Comment by chlafreniere** [comment]
Given that January will be forked off of December, moving this to February milestone (where we need to fix this).

**Comment by chlafreniere** [comment]
@VasuBhog can you take a look? For February release so not immediately urgent.

**Comment by chlafreniere** [comment]
@VasuBhog can you still repro?

**Comment by vasubhog1** [comment]
I can not repro on current Mac insiders. However, I do see it still happening on the first click of cancel on Windows. If a user clicks `cancel` twice on windows then it will close (workaround).

**Comment by chlafreniere** [comment]
Reopening for port request

**Comment by kburtram** [comment]
Closing since related PR has merged to release/1.26.
