### ISSUE TITLE
Japanese Language Pack is not available

### ISSUE THREAD

**Issue by Asugakoisi** [microsoft/azuredatastudio#13835]
- Azure Data Studio Version:1.25.1 

Steps to Reproduce:

1. Open the command palette.
2. Fill in the text box with "Configure Display Language."
3. Click "Install additional languages..."
4. Select "Japanese Language Pack for Azure Data Studio."
5. Error message is displayed.

The error message : "Unable to open 'Extension: Japanese Language Pack for Azure Data Studio': XHR failed."

**Comment by smartguest** [comment]
@Asugakoisi Hi can you try and download the Japanese language pack now? There was a misnamed file location that was on the manifest, we corrected it and now it should point to the correct file location. If your extensions gallery freezes, please let me know. Thanks!

**Comment by Asugakoisi** [comment]
I was able to use the Japanese language pack successfully. Thank you!
