### ISSUE TITLE
Dashboard tabs needs `show open dashboards` when tabs flow off the screen

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1383]
- SQL Operations Studio Version:

Steps to Reproduce:
Open all the publicly released tabs in a small Ops Studio window
![image](https://user-images.githubusercontent.com/10819925/39844737-8905682a-53a6-11e8-8696-ba564c712304.png)

You'll notice some of them flow off the screen. For editor tabs this is solved by having a `show open editors` option in a `...` dropdown so users can find the missing ones. Can we have something similar? It's not obvious when one of the tabs is hidden.
![image](https://user-images.githubusercontent.com/10819925/39844776-aa1a8658-53a6-11e8-820d-ba33009a7f7e.png)

**Comment by kevcunnane** [comment]
Another comment - on 1st open the scrollbar isn't enabled. If you resize it appears so you can scroll, but this is particularly bad since the initial experience is that this is "broken"

**Comment by kburtram** [comment]
This UX has been redesigned a while back.  Please let us know if you're still impacted by this issue.
