### ISSUE TITLE
Use Redgate Adventure Works

### ISSUE THREAD

**Issue by brentwc** [microsoft/azuredatastudio#13839]
Issue Type: <b>Bug</b>

My Client IP does not have access to the server. Azure itself is not permitting the read.
This isn't a bug for Azure Data Studio - placing it here for other readers of the forum (below) connecting to the DB via ADS.
https://www.sqlservercentral.com/articles/connecting-to-adventureworks-on-azure
https://www.sqlservercentral.com/forums/topic/connecting-to-adventureworks-on-azure

Azure Data Studio version: azuredatastudio 1.24.0 (eb3c0f5d9df86b9490606aab7fffaa253b0aca4d, 2020-11-10T23:38:09.705Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|62.07GB (51.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by way0utwest** [comment]
This isn't an appropriate place for this issue, as this isn't an ADS issue. You should post a note at the article you've linked to.

**Comment by brentwc** [comment]
Yep. If you go to the link, the post links to this article.

**Comment by alanrenmsft** [comment]
just like @way0utwest said, an ADS issue is not the best place for this as this is not actionable for us, and we have to close it.

**Comment by brentwc** [comment]
@way0utwest @alanrenmsft ADS itself prompted me to supply the bug report via an automated form generated within ADS it was the first time I had been prompted to do so by this client, hence the disclaimer it isn't an ADS bug. (Except maybe that the logger shouldn't have prompted me for a simple firewall issue.)
