### ISSUE TITLE
can't login Azure China account

### ISSUE THREAD

**Issue by baolijn** [microsoft/azuredatastudio#13849]
when we use Azure Data Studio, we can't login Azure China account, can you privide a solution?

**Comment by kburtram** [comment]
@baolijn have you enabled support for Azure Chine in the User Settings?  Please let us know if this doesn't resolve the issue?

<img width="708" alt="Screen Shot 2020-12-17 at 11 28 48 PM" src="https://user-images.githubusercontent.com/599935/102586846-b4babc00-40bf-11eb-84cc-fac04a568f1a.png">

**Comment by cssuh** [comment]
Closing this issue as no additional information has been provided.
