### ISSUE TITLE
Notebook: Support for multiple code cell kernal/connections within a notebook

### ISSUE THREAD

**Issue by tmichael-ms** [microsoft/azuredatastudio#13845]
**Is your feature request related to a problem? Please describe.**
I have data stored in SQL and Kusto data stores that I want to pull into a single notebook.  Currently, I am limited to creating separate notebooks for each set of queries since the Kernal and Connection settings is at the notebook level.

**Describe the solution or feature you'd like**
Code cells in notebooks should have independent kernal/connection settings

**Comment by alanrenmsft** [comment]
If I remember correctly, this is already being worked on or already available, @chlafreniere, am I right?

**Comment by chlafreniere** [comment]
Correct. Both are in progress.

**Comment by lucyzhang929** [comment]
Closing this issue for now since we already have two issues tracking this
multiple connections: https://github.com/microsoft/azuredatastudio/issues/5031
multiple kernels: https://github.com/microsoft/azuredatastudio/issues/5451
