### ISSUE TITLE
Create project from database dialog should show loading indicator

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#13841]
When launching the Create project from database dialog from the context menu of a database, the server and database dropdown are already populated, but sometimes the database dropdown is blank for a few second while waiting for the list of databases to load.

![image](https://user-images.githubusercontent.com/31145923/102533666-94a4e180-405a-11eb-895a-2edf0e92fb61.png)

 It would be nice if there was a loading indicator like this:
![image](https://user-images.githubusercontent.com/31145923/97920933-117c3600-1d0f-11eb-8124-80ffb6b479d8.png)

**Comment by zijchen** [comment]
I think this issue is fixed in #14511, I can no longer reproduce in latest ADS release. @kisantia can you verify?

**Comment by kisantia** [comment]
yup this is already fixed. Sorry I forgot about this issue when I sent out that PR.
