### ISSUE TITLE
Add default authentication type setting

### ISSUE THREAD

**Issue by TroyWitthoeft** [microsoft/azuredatastudio#13851]
**Is your feature request related to a problem? Please describe.**

Can we consider creating a `DefaultAuthenticationType` setting ?
Currently the default authentication type for all connections into Azure SQL databases is `SQL Login`.

![image](https://user-images.githubusercontent.com/1102958/102626853-5ddfd180-4115-11eb-8e54-323e5549da34.png)

Let's give users the options to choose their default?

**Describe the solution or feature you'd like**

If you are using Azure SQL you are _probably_ also using Active Directory - either Windows Authentication or AAD.  For those users, it would be very convenient if they had the option to select the default connection type when connecting to Azure SQL databases.  

If we added this setting, I suspect making it's scope universal - all connections - would be the easiest to implement.  Quick win.  Eventually, you'd probably want to get more granular, and accommodate users that want to customize the defaults based upon the type of Azure databases in their subscription. 

    All conns = SQL Login 
        Azure SQL conns = AD
        PostGres conns = AAD

The design and implementation should consider this eventuality. 

**Describe alternatives you've considered**

I understand that one workaround is saving the connection string into a server group. 
![image](https://user-images.githubusercontent.com/1102958/102627515-4e14bd00-4116-11eb-8d4d-9f55cc646bc6.png)

It feels like ADS is pushing the users towards creating and curating a list of registered servers.  However, why recreate the list? 
 This list already exists in Azure! It is _Azure_ Data Studio, after all.   😄   Why not just use that list?  Starting with a global settings, let's work towards creating some settings that govern ADS' connection negotiation with different types of sql servers in the image above? 

User story = If I am a new user of ADS, and I launch ADS for the first time. I can add my Azure Account, connect to Azure, expand my SQl Server folder, double-click to connect. On first connection, I am prompted to edit the settings and select default connection type.  

**Additional context**

This would be a fantastic "quality of living" improvement for those of us with lots of Azure SQL Databases.  In particular, the **new user experience** for those of us using AD/AAD could really benefit from it.  I am open to submitting a PR.  Thanks for your consideration!

**Comment by TroyWitthoeft** [comment]
So, I was able to clone the repo down and get up and running on my local thanks to the [contributing](https://github.com/microsoft/azuredatastudio#contributing) guide, thanks!

After a little debugging, I can see that as a auser if I double-click on the node, the code-behind picks up the hardcoded authentication type value down in `databaseTreeDataProvider.ts` file.  Swapping that hardcode from `SqlLogin` over `AzureMFA` got it done for double click.   

![Feature2](https://user-images.githubusercontent.com/1102958/103427367-9dcf9b80-4b8e-11eb-86a4-63e059573b7b.gif)

However, clicking the connect icon on the right of the row seems to hit a different code path.  Exploring that code path, I can see that we have made some provisions for a default values.  For instance, click the connect icon hits up the `getDefaultProviderName()` method which IS pulling in user configured values.   I'll need to study this a bit more to figure out the right way to implement it.  Double-click or connect button, both? Either way, it will be useful to my team which does a lot of work in Azure SQL and tends to log in using AAD tokens.   Thanks, and happy new year.

**Comment by TroyWitthoeft** [comment]
@schwammy  Thanks for reminding me of this.  Yes, this kinda died on the vine.  But, I went ahead and forked this repo and pushed my feature out on my own branch here.  https://github.com/TroyWitthoeft/azuredatastudio/tree/Feature-AutoAzureAD

**Comment by TroyWitthoeft** [comment]
All right, I spoke with @kburtram on prior PR #14709.  I implemented his fixes, I believe I also found a bug fix.  New PR #14784 created.  Local testing looks good.

**Comment by wabby80** [comment]
How is this issue going? :) I've just started using ADS and stumbled upon this annoying bug. Wonder why they decided to default to SQL login and be able to change it.

**Comment by TroyWitthoeft** [comment]
@wabby80 - We've got some progress! @kburtram is helping implement the feature.  
Completing PR #16999 should add it to main! 🎉

**Comment by kburtram** [comment]
Closing based on https://github.com/microsoft/azuredatastudio/pull/16999.  Thanks for the contribution @TroyWitthoeft!

**Comment by TroyWitthoeft** [comment]
Thanks @kburtram!  Will try and track user feedback and happy to adjust if we see any issues.  This will be a big help for those of us with lots of Azure Sql databases using AAD to login!

**Comment by TroyWitthoeft** [comment]
Just making a note.  Looks like - as of v1.330 - this feature seems to behaves as expected in the SQL database tree, but not the SQL Server tree. 

![image](https://user-images.githubusercontent.com/1102958/145611956-80748431-d139-4167-ad9f-035b3d37c400.png)
