### ISSUE TITLE
SQL Execution Plan issues

### ISSUE THREAD

**Issue by nivGandhi** [microsoft/azuredatastudio#1385]
- SQL Operations Studio Version:

Steps to Reproduce:
Hello Team,

I have database with 500 GB size. when i have executed slow working stored procedure to check the execution plan. I am facing performance(up and down scroll bar) issues in this tool.

**Comment by kburtram** [comment]
@nivGandhi do you know approximately how many UI elements are in the query plan diagram?

**Comment by nivGandhi** [comment]
It;s more than 200. I don't know the exact count.

**Comment by kburtram** [comment]
@nivGandhi thanks for the additional info.  Performance issues handling large execution plans should probably be fixed in the external showplan control we consume.  I'll mark this as upstream to track the issue.

**Comment by kburtram** [comment]
Please use **SentryOne Plan Explorer** for working with query execution plans.  This extension should have better support for working with large query plans.
