### ISSUE TITLE
When running a query automatically connect, if the token has expired

### ISSUE THREAD

**Issue by jagdishrajan** [microsoft/azuredatastudio#13866]
**Is your feature request related to a problem? Please describe.**
I hit F5 to run a query. I get an error message that the connection token has expired on my saved or recent connection.  Now I have to click Connect again, select the connection and click Connect.

**Describe the solution or feature you'd like**
This is all too slow.  On running a query when the connection token has expired it should simply automatically connect by reinitializing the the same connection that expired.  Prompt for a password or whatever if needed, but if the password is saved then just connect and execute the query.

**Describe alternatives you've considered**

**Additional context**
This is similar to what SQL Management Studio does.

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/6872.  We're currently working on a fix for this bug.
