### ISSUE TITLE
SQL Server Import fails on M1 mac running macOS 11.1

### ISSUE THREAD

**Issue by danhausman** [microsoft/azuredatastudio#13864]
- Azure Data Studio Version:  1.25.1
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98

Steps to Reproduce:
Running SQL Server Import v1.1.0

1.Log in to database. 
2. Start Import 
3. Point to DB and source file
4. Import
5. Fails output below:

Same file works fine on Intel macOS 11.15.7  I am happy to send more logs or do more testing if it helps. Please let me know.

![Screen Shot 2020-12-21 at 10 44 19 AM](https://user-images.githubusercontent.com/46173156/102794794-e2328e80-4379-11eb-8806-bb8616d68884.png)

**Comment by aasimkhan30** [comment]
This seems a duplicate to this https://github.com/microsoft/azuredatastudio/issues/5692 issue. 

Here is the solution posted for this issue.
https://github.com/microsoft/azuredatastudio/issues/5692#issuecomment-650396719

**Comment by dcr21** [comment]
Hi, I still don't understand the solution here. Can someone do a walkthrough ?
