### ISSUE TITLE
"Copy remote link" is slow

### ISSUE THREAD

**Issue by coquagli** [microsoft/azuredatastudio#13868]
Issue Type: <b>Performance Issue</b>

![image](https://user-images.githubusercontent.com/24420239/102918797-39edfa00-444d-11eb-9b45-c4e8c3ba5dbe.png)

The Notebook tool "Copy remote link" seems like it should just be a fairly simple operation. But it takes 3 - 5 seconds every time. Is there some kind of bug making this operation take longer? Could the slow part be pre-computed and cached?

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-devops-simplified-prs|ads|0.0.6
spellright|ban|3.0.52
adslivesite|Mic|0.0.42
kusto|Mic|0.4.0
powershell|ms-|2020.4.0
back-n-forth|nic|0.2.1

</details>

**Comment by JustinMDotNet** [comment]
Created internal bug for tracking
https://mssqltools.visualstudio.com/ADS%20LiveSite%20Support/_workitems/edit/4332
