### ISSUE TITLE
Schema Compare has fuzzy scroll effected by pre-selection

### ISSUE THREAD

**Issue by srinath999** [microsoft/azuredatastudio#13876]
When a user has selected a cell in schema compare and makes changes in selection. the schema compare screen scrolls without user interaction

- Azure Data Studio Version: 1.25.2

Steps to Reproduce:

1.click on a cell with check box in schema compare screen.
2.scroll somewhere else and change selection
This results in the schema compare screen scroll to previously selected cell.

https://user-images.githubusercontent.com/19923196/103135878-ba2c8d80-46e1-11eb-8179-c2fb12a68c0e.mp4

**Comment by kisantia** [comment]
I'm unable to repro. Might have been fixed with the table fixes made in the last few months
