### ISSUE TITLE
Table features we need

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#1389]
Using this issue to track the features we need to make sure we have for our table implementation

- [ ] Is a table - looks like a table

**Selection**
- [ ] Cell Selection
- [ ] Row Selection
- [ ] Changable selection model
- [ ] Drag selection
- [ ] Keyboard navigation

**Looks**
- [ ] Themable for selection, hover, selection row, hover row
- [ ] (Optional) hover column, selection column
- [ ] Custom Cell renders, multiple per table

**Data**
- [ ] Windowed scrolling
- [ ] (Optional) Cacheing
- [ ] async data retrieval
- [ ] (Optional) pre render number of rows (scroll height)
- [ ] (Optional) filtering
- [ ] (Optional) Sorting
- [ ] (Optional) find

**Interaction**
- [ ] Event driven interaction
- [ ] On click
- [ ] On right click
- [ ] On key press

**Comment by anthonydresser** [comment]
I'm probably missing some features here.

**Comment by anthonydresser** [comment]
Going to backlog this since we don't need to immediately anymore

**Comment by kburtram** [comment]
@anthonydresser are you still tracking anything with this issue?  If not, please close it out.  Thanks!

**Comment by kburtram** [comment]
Closing older issues
