### ISSUE TITLE
Connection page does not handle UTF-8 charaters in account name

### ISSUE THREAD

**Issue by Eneuman** [microsoft/azuredatastudio#13896]
Issue Type: <b>Bug</b>

Create a Azure Account with a foreign charaters in it
Login with that account name in Windows
Connect to a database in Azure Using Active Directoy MFA.

As you can see in the screen shoot, the correct foreign character is not displayed. In this case it is a "ö"

![image](https://user-images.githubusercontent.com/12099277/103454791-aab3d280-4ce7-11eb-857e-2593f219f9af.png)

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
Please verify that the fix for this issue also fixes the account name being displayed elsewhere in the UI, such as is described in https://github.com/microsoft/azuredatastudio/issues/16829.  Thanks!

**Comment by Eneuman** [comment]
Hi @kburtram 

UTF-8 characters in the subscription name works but the the logged in account name in the UI is still wrong:
I'm using a AAD name containing foreign characters.
![image](https://user-images.githubusercontent.com/12099277/132139470-fa3bf4e7-b8fc-445a-b70c-b43a71f72deb.png)

**Comment by cheenamalhotra** [comment]
This issue has been addressed in latest v1.40.1, with PR #21070 
Closing as resolved.
