### ISSUE TITLE
Azure Data Studio Error Code: 50173 - Unable to logon to the DB after changing the AD Password

### ISSUE THREAD

**Issue by kodeaask** [microsoft/azuredatastudio#13895]
I changed my AD Password. After that, when I try to log on to the Azure SQL Server Database via Azure Data Studio using 'Azure Active Directory - Universal with MFA support' it constantly throw the error

Error: Token retrival failed with an error. Open developer tools to view the error

I tried to 'Refresh the credentials' but still it keeps throwing the same error.

I'm able to logon to the SQLServer DB via SSMS. The problem is only via Azure Data Studio.

**Comment by kburtram** [comment]
@cssuh do you have any suggestions here?

@kodeaask I think the access token may need to be cleared from the credential cache.  You may try removing the the account from the Account Management dialog and then readding it.  I recall there may be some bugs in this scenario we need to fix.

**Comment by cssuh** [comment]
Might want to try some of the temporary workarounds mentioned here: https://github.com/microsoft/azuredatastudio/issues/12637

**Comment by kodeaask** [comment]
HI @kburtram and @cssuh : Thanks a lot for your response. Yes, removing the Account completely from the Account Management and then re-adding that has resolved the issue.
