### ISSUE TITLE
can't install postgreSQL extension

### ISSUE THREAD

**Issue by steverezhener** [microsoft/azuredatastudio#13890]
Issue Type: <b>Bug</b>

Failed to install 'microsoft.azuredatastudio-postgresql'.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4025U CPU @ 1.90GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
It looks like you're using an older version of ADS which the latest version of the PG extension doesn't support. Please update to the latest ADS version and try again - let us know if that doesn't work.

**Comment by steverezhener** [comment]
Hi Charles,

You are correct, TY. I upgraded ADS and now PostgreSQL extension is installable. I wish that extension installation would be smart enough to start with upgrading ADS if that is necessary.

Thanks in advance,
Steve Rezhener.
Data Therapist building DATA Analytics
COZYROC-Star | Melissa MVP | SentryOne PAC
https://www.datasteve.com<https://www.datasteve.com/>
[cid:image001.png@01D6E373.13E383B0]<https://www.datasteve.com/> [cid:image002.png@01D6E373.13E383B0] <mailto:%20steve.rezhener@outlook.com>  [cid:image003.png@01D6E373.13E383B0] <https://www.twitter.com/SteveRezhener>  [cid:image004.png@01D6E373.13E383B0] <https://www.linkedin.com/in/steverezhener/>
Co-leader, LA Data Platform User Group<https://ladataplatform.pass.org/>
Co-organizer, SQL Saturday in Los Angeles<https://www.sqlsaturday.com/978>
Schedule a meeting - https://calendly.com/steverezhener/60min
