### ISSUE TITLE
Moving a page in the _toc.yml causes the Notebooks list to stop opening pages

### ISSUE THREAD

**Issue by tster123** [microsoft/azuredatastudio#13893]
Issue Type: <b>Bug</b>

1. open ADS to a notebook with a _toc.yml
2. Open the _toc.yml in another text editor
3. Move a page from one section to another section in the _toc.yml
4. Go back to ADS and and click on pages in the Notebooks list.  They won't open. 

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.84GB (38.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azure-devops-simplified-prs|ads|0.0.2
spellright|ban|3.0.52
adslivesite|Mic|0.0.10
kusto|Mic|0.4.0
powershell|ms-|2020.4.0
back-n-forth|nic|0.2.1

</details>

**Comment by MaddyDev** [comment]
@tster123  Does ADS throw any error when you open the book? Also can you send me the toc.yml file and tell me what you're moving around in it. Thanks.

**Comment by tster123** [comment]
Seems like this issue has been fixed since I opened it.
