### ISSUE TITLE
Anchor / cross reference is not scrolling to the appropriate section of Notebook

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#13899]
- Azure Data Studio Version:
Version: 1.26.0-insider (user setup)
Commit: 30054e632c75f8df0ea351f2c51b8ec7d5fa5be5
Date: 2020-12-30T06:36:16.231Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open https://raw.githubusercontent.com/MsSQLGirl/jubilant-data-wizards/main/Notebook%20Templates/TroubleshootingGuideTemplate.ipynb in ADS. 
2. Try browsing to the notebook parts using the links, i.e. 
![image](https://user-images.githubusercontent.com/6405919/103493700-ac64bf80-4de7-11eb-88dd-03c92c4546ab.png)

Expected: 
Users should be able to easily see that the page has scrolled to the target heading / anchor. 
For example:
When the ADS Window is maximized: 
1. Actual: When users click on "Overview" (because it's visible on the very bottom of the page), users might not realize / easily find where the link goes to. Suggestion: it would be nice to scroll it to the appropriate heading. 
2. Actual: When users click on "Risk / Impacts", "Symptoms" or "Mitigation", the page scrolls but the headings are not visible. i.e. scrolled too much that users might find hard to identify which section is referring to the link clicked.  
![AnchorIssueFullScreen](https://user-images.githubusercontent.com/6405919/103494143-2dbd5180-4dea-11eb-94ea-a3e9e2a14eaa.gif)

When the ADS Window is in a custom size (i.e. not maximized), the experience is different from when the window is maximized.
1. Actual: When users click on "Overview" (not visible on the window, it doesn't go anywhere.
2. Actual: When users click on "Symptoms", the page scrolls but the Symptoms is right in the middle of the window.
![AnchorIssue](https://user-images.githubusercontent.com/6405919/103493931-0ca83100-4de9-11eb-8ea1-451ca15022db.gif)

I commented a potentially related issue https://github.com/microsoft/azuredatastudio/issues/9941#issuecomment-749340415 - where the offset issue is more severe if the text cell containing the links are somewhere in the middle of a notebook.

File to repro: https://github.com/MsSQLGirl/jubilant-data-wizards/blob/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis/ADSNotebooksDemo.ipynb

In Azure Data Studio, you can simply press Ctrl + O, and paste the raw path
`https://raw.githubusercontent.com/MsSQLGirl/jubilant-data-wizards/main/Simple%20Demo/Sample%20Notebooks%20-%20Data%20Analysis/ADSNotebooksDemo.ipynb`

(in case the below gif doesn't play, click on it)
![LinkingIssue](https://user-images.githubusercontent.com/6405919/102851192-0c16a000-43d0-11eb-987d-74e2c253a31b.gif)

**Comment by MsSQLGirl** [comment]
@chlafreniere @halerankin - would you be able to look into this please? Thank you!

**Comment by halerankin** [comment]
@MsSQLGirl @chlafreniere Just before Christmas, I dedicated an entire day to testing the current experience and to look for possible solutions. So far I have no solutions. I will dive back in.

**Comment by halerankin** [comment]
My PR has one approval so far. We should get this into master ASAP.
https://github.com/microsoft/azuredatastudio/pull/13926

**Comment by Charles-Gagnon** [comment]
@halerankin You should add people as reviewers if you want them to look at it 😄 Many people don't get notified of a PR unless they're added as a reviewer.

**Comment by chlafreniere** [comment]
Fixed by #13926.
