### ISSUE TITLE
Connecting to Azure 

### ISSUE THREAD

**Issue by juriaan-atos** [microsoft/azuredatastudio#13906]
Issue Type: <b>Bug</b>

Integrated security Login failed for user '<token-identified principal>'.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (9.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
profiler|Mic|0.11.0

</details>

**Comment by cssuh** [comment]
Hello, thank you for your bug report.  If you open up the `Developer Tools` by selecting `Ctrl + Shift + P` and typing Developer Tools, do you see any additional error messages?

**Comment by juriaan-atos** [comment]
Hallo,
i was able to get the error in Developer tools.

Database 'AUTH' on server 'azeuwfsbdevsql01.database.windows.net' is not currently available. Please retry the connection later. If the problem persists, contact customer support, and provide them the session tracing ID of '{B04746D6-D96C-4575-8A6C-3FB0F84B109E}'.


The Auth database is running in Serverless mode and goes offline. It seems the db is not started and the connection fails, (this is not happening in visual studio)

Juriaan van Oosterom
Software Engineer  @ Atos B&PS-BTN/NL-DIG-BI-Unit1
The Netherlands (CET)

M: +316-513 15 250
E: juriaan.vanoosterom@atos.net<mailto:juriaan.vanoosterom@atos.net>

[cid:image001.png@01D6E47C.41AF3F50]
[cid:image002.png@01D6E47C.41AF3F50]<http://www.linkedin.com/in/juriaanvanoosterom>

**Comment by cssuh** [comment]
From the error message it seems like your database was not up when you are trying to connect, can you verify that it is available when you are attempting to connect via ADS?

**Comment by juriaan-atos** [comment]
Yes, when the db is started manually all is fine.
It seems the timeout Is not waiting for the database to come online before the message is thrown.

Juriaan van Oosterom
Software Engineer  @ Atos B&PS-BTN/NL-DIG-BI-Unit1
The Netherlands (CET)

M: +316-513 15 250
E: juriaan.vanoosterom@atos.net<mailto:juriaan.vanoosterom@atos.net>

[cid:image001.png@01D6E8F7.829B99D0]
[cid:image002.png@01D6E8F7.829B99D0]<http://www.linkedin.com/in/juriaanvanoosterom>
