### ISSUE TITLE
SQL Server Agent doesn't display in manage tab

### ISSUE THREAD

**Issue by raeokay** [microsoft/azuredatastudio#13911]
Issue Type: <b>Bug</b>

Installed SQL Server Agent, loaded the Manage tab for my server, and there is no SQL Agent section available. Tried uninstalling and reinstalling, no dice. Only "home" and "databases" sections remain available. 

![image](https://user-images.githubusercontent.com/34099563/103668819-89502200-4f45-11eb-9ebb-a94cc16e288d.png)

**Two errors from dev console:** 

[0105/104910.419:ERROR:registration_protocol_win.cc(103)] CreateFile: The system cannot find the file specified. (0x2)

console.ts:137 [Extension Host] (node:7736) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

---

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (7.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.1.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
sql-assessment|Mic|0.5.0
sql-database-projects|Mic|0.5.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by abist** [comment]
@raeokay Thanks for opening the issue. Can you confirm whether you have "Preview Features" as enabled in the User Settings? If not, then you'll have to enable them to see SQL Agent.

**Comment by raeokay** [comment]
Ah, you got me. Forgot to enable that in a fresh install. 

Thank you!
