### ISSUE TITLE
SQL Server Import Extension Import CSV File,If I rename the column, first row data lost forever.

### ISSUE THREAD

**Issue by liuwy1005** [microsoft/azuredatastudio#13919]
- Azure Data Studio Version:
Version: 1.25.1
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:51:41.708Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Linux x64 5.4.0-59-generic
Steps to Reproduce:

1.Right click database - import wizard.
2.Browse the csv file click "Next".
3.Preview Data grid column name was my first row data information,then i click "next" to modify "colunm name" and "Data Type" 
4.select my import table after import status tells me that sucessfully.
5.My first row data information lost forever.

**Comment by aasimkhan30** [comment]
@liuwy1005 can you please provide me an example of the data that you are trying to import. I cannot repro this error at my end.

**Comment by liuwy1005** [comment]
hi there:
&nbsp; &nbsp; example of the test data is in the email attachment
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; thanks.




刘文勇
liuwy1005@qq.com



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "microsoft/azuredatastudio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月3日(星期三) 上午6:06
收件人:&nbsp;"microsoft/azuredatastudio"<azuredatastudio@noreply.github.com&gt;;
抄送:&nbsp;"Scan"<151242066@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [microsoft/azuredatastudio] SQL Server Import Extension Import CSV File,If I rename the column, first row data lost forever. (#13919)





 
@liuwy1005 can you please provide me an example of the data that you are trying to import. I cannot repro this error at my end.

**Comment by liuwy1005** [comment]
This issue has been fixed.
