### ISSUE TITLE
Kusto is showing as the default provider in Connection Dialog

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#13930]
Kusto is currently showing as the default provider when opening the connection dialog. This seems to be purely a display issue though - the fields all correspond to a SQL connection and if a SQL server name is put in then it can connect successfully.

The default should be shown as MSSQL regardless of what extensions are installed (PG, Kusto, etc)

![image](https://user-images.githubusercontent.com/28519865/103952637-99a6ff00-50f5-11eb-8247-a9b982d88402.png)

**Comment by MsSQLGirl** [comment]
@gupta1 can you please look into this?

**Comment by cssuh** [comment]
I am not seeing this anymore - is anyone able to repro the issue? Otherwise, I will just close it.

**Comment by gupta1** [comment]
> I am not seeing this anymore - is anyone able to repro the issue? Otherwise, I will just close it.

@cssuh I am able to repro it in main branch.

**Comment by cssuh** [comment]
I found that reverting [this commit](https://github.com/microsoft/azuredatastudio/pull/13813) fixed the issue so I have asked @aasimkhan30 to take a look.
