### ISSUE TITLE
Connection Pane shows wrong azure account for saved connections

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#13933]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a New Query
2. Select `Connect`
3. Select any saved Azure SQL DB connection
![Screen Shot 2021-01-08 at 2 55 43 PM](https://user-images.githubusercontent.com/18150417/104058581-f2dc6480-51c1-11eb-8624-42716877c22e.png)
4. It displays the wrong Azure Account, but I am still able to connect when the incorrect account is selected. (in this case, it should be my Microsoft account instead of my personal outlook)

**Comment by Charles-Gagnon** [comment]
Probably related to https://github.com/microsoft/azuredatastudio/issues/13930

My gut feeling here is that the connection dialog isn't telling the dropdown to select the proper account/provider when it's initialized so it just displays the first in the list. (but the backing account/provider would be the persisted one so if you just try to connect it works as expected)

**Comment by cssuh** [comment]
This got fixed here: https://github.com/microsoft/azuredatastudio/pull/14163
