### ISSUE TITLE
Error "TypeError: Cannot read property 'accessToken' of undefined" for any DB connection request

### ISSUE THREAD

**Issue by sumanthewhiz** [microsoft/azuredatastudio#13936]
Issue Type: <b>Bug</b>

All of a sudden I can no longer connect to any of my prod/uat environment databases. Whenever I try to connect, I get the error "TypeError: Cannot read property 'accessToken' of undefined".

However, I can connect to the same database servers / DBs using other clients like SQL Server Management Studio etc.

This has been happening suddenly since about a week now, and I had been successfully using ADS for the same DB connections for over an year until then.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (21.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cssuh** [comment]
Hello, thank you for your bug report.  Can you check the `Developer Tools` section (`Ctrl + Shift + P` and type Developer Tools) to see if there are any additional error messages?

**Comment by sumanthewhiz** [comment]
Found an additional error (highlighted in bold) when I turned on the Developer Tools console:

**console.ts:137 [Extension Host] Expiration time was not defined. This is expected on first launch -** 
log.ts:197   ERR TypeError: Cannot read property 'accessToken' of undefined
	at f.getAccountSecurityToken

**Comment by hulvei3** [comment]
This keeps happening when you haven't used azure data studio for a while. I need to remove my Azure linked account **completely** and start over for this to work.

**Comment by jagdishrajan** [comment]
When I get this error I can sometimes fix it with the command Azure Accounts: Clear Azure Account Token Cache.  Today, however, it was particularly stubborn and I needed to run command Azure: Sign In, delete my Azure account connection and recreate it.  Very annoying, to say the least!

**Comment by larinico** [comment]
The issue is still happening. 
![image](https://user-images.githubusercontent.com/37266549/142442862-d1577175-f7dd-4fe3-80f6-24c4312d965e.png)

I am the owner of the server I try to connect to. 
I am using ADD in order to sign in. 

I've removed my account, cleared cache and still not able to access the db using Data Studio.

**Comment by tcc-sejohnson** [comment]
Just wanted to chime in -- this is still occurring. Only way to fix it for me was to remove the account completely, clear the Azure token cache, and re-sign in. This was after a system restart and about a week of not using ADS. I'm on Ubuntu.

**Comment by joeyjiron06** [comment]
still not working for me, i tried everything mention above and still not working. when can this get fixed?

**Comment by Alessandro91-dev** [comment]
I have the same issue on my side, for a tenant, linked to my working account, for customer environment.
Its working for SSMS and SSMS asks me to resign. ADS just spinning for hours doing nothing. 
I discovered that the saved connections are empty while having this issue.
Workaround is to delete linked Azure Sub in ADS, sometimes additional restart ADS too and add Azure Sub again (need to be logged in to Azure customer environment before add account) . Than the saved connection is back filled. 
- ADS feels like no working tool by now. so many annoying bugs. Fall back is SSMS each time when even workaround is not working.
- For multi tenant auth with web browser, its annoying that it only works when I first log in to other tenant in same browser.

![image](https://user-images.githubusercontent.com/79930853/159506927-aaddcd72-3c4d-4784-b3ce-dc80fdd2cffe.png)
![image](https://user-images.githubusercontent.com/79930853/159508620-af57b7df-1a9d-4e98-98ed-fe07c61e2934.png)

**Comment by louwill** [comment]
This problem is still occurring for me.  Azure SQL database authenticating via Azure AD - Universal with MFA support.

![image](https://user-images.githubusercontent.com/1969592/169323424-633947dc-95af-41f7-9c8b-b06c5053bf2e.png)
