### ISSUE TITLE
Clipped menu bar on non-full screen view for Mac OS

### ISSUE THREAD

**Issue by laurajjiang** [microsoft/azuredatastudio#13946]
Version: 1.25.1
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:57:41.946Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0

Steps to Reproduce:

1. Open Azure Data Studio application in a non-full screen view on a Mac system 
2. See clipped menu bar by action side menu

![image](https://user-images.githubusercontent.com/39676345/104268642-385e9300-5449-11eb-836a-70499fb4ca5d.png)

**Comment by Charles-Gagnon** [comment]
@laurajjiang I'm not sure I see what you're referring to - what's clipped in the attached screenshot?

**Comment by laurajjiang** [comment]
![104369280-0ba28e00-54d2-11eb-9b42-2a4c9c0133b6](https://user-images.githubusercontent.com/39676345/104369490-5e7c4580-54d2-11eb-864e-240aafcf73c5.png)
![Screen Shot 2021-01-12 at 12 32 16 PM](https://user-images.githubusercontent.com/39676345/104369501-60de9f80-54d2-11eb-9cb3-7922fa24f2b8.png)

Sorry, I should have marked/circled in the original picture. I compared the behavior to my browser and the full-screen version of the ADS - particularly on the full screen version, there's extra padding on the bottom of the menu bar.

**Comment by kburtram** [comment]
@laurajjiang thanks for reporting this issue.  We don't do anything in the application to control the placement of these standard macOS windows buttons.  I assume this is an issue upstream, either in vscode or Electron.  FWIW, I'm not seeing the same positioning as you on my macos (screen below).  Unfortunately, I don't think we have a straightforward way to adjust the placement of those buttons.

<img width="501" alt="Screen Shot 2021-02-09 at 10 01 03 AM" src="https://user-images.githubusercontent.com/599935/107407035-ffecbc00-6abd-11eb-8ac7-e626175b2ecd.png">
