### ISSUE TITLE
Label UNSAVED Nothing to save

### ISSUE THREAD

**Issue by gle-glcsi** [microsoft/azuredatastudio#13949]
Issue Type: <b>Bug</b>

Hello
From the beginning of Azure Data Studio (installed yestreday), I have the label (1 UNSAVED) but nothing to save. If I click on "Close all editors", nothing happens.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (8.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gle-glcsi** [comment]
![image](https://user-images.githubusercontent.com/77354281/104354541-a1a5db00-5509-11eb-9fda-e3e672ae9c1e.png)

**Comment by Charles-Gagnon** [comment]
If you delete %APPDATA%\Backups does that clear the count?

**Comment by gle-glcsi** [comment]
I deleted %appdata%\azuredatastudio\bakups and it is solved.
Thanks !

Guillaume
De : Charles Gagnon <notifications@github.com>
Envoyé : mardi 12 janvier 2021 19:22
À : microsoft/azuredatastudio <azuredatastudio@noreply.github.com>
Cc : Guillaume LEJEUNE <gle@glcsi.fr>; Author <author@noreply.github.com>
Objet : Re: [microsoft/azuredatastudio] Label UNSAVED Nothing to save (#13949)


If you delete %APPDATA%\Backups does that clear the count?
