### ISSUE TITLE
Signed in user name display problem

### ISSUE THREAD

**Issue by JanosBerke** [microsoft/azuredatastudio#13948]
- Azure Data Studio Version:
Version: 1.25.1 (system setup)
Commit: e7eacc32c0d20bd4da843320c3bfac231b308c98
Date: 2020-12-11T01:59:24.271Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Open ADS
2. Sign in with an MSID
3. Check the signed in user's name
![image](https://user-images.githubusercontent.com/34519114/104302604-494ee900-54c9-11eb-93e2-15eb58271136.png)

**Comment by cssuh** [comment]
Closing as this is a duplicate #12629
