### ISSUE TITLE
Expired grant token not updating

### ISSUE THREAD

**Issue by IeuanWalker** [microsoft/azuredatastudio#13953]
Issue Type: <b>Bug</b>

Try to sign in but I get an error saying 'token retrieval failed', looking inside the dev tools I get the below error.

Tried adding a new account, it opens up the browser I sign in but I get the same error.

![image](https://user-images.githubusercontent.com/6544051/104438312-c50f6b00-5587-11eb-8e48-3a3f69030fe9.png)

```
Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2020-12-11T09:41:15.6470000Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2020-12-29T09:59:06.0000000Z'.\r\nTrace ID: c3a82c17-703b-4bbf-b85c-6c0fa6091300\r\nCorrelation ID: 1960f17b-46e2-49f1-8eb1-c399c1d85529\r\nTimestamp: 2021-01-13 10:05:13Z","error_codes":[50173],"timestamp":"2021-01-13 10:05:13Z","trace_id":"c3a82c17-703b-4bbf-b85c-6c0fa6091300","correlation_id":"1960f17b-46e2-49f1-8eb1-c399c1d85529","error_uri":"https://login.microsoftonline.com/error?code=50173"}
```

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (15.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
arc|Mic|0.6.5
azdata|Mic|0.4.1
azuredatastudio-postgresql|Mic|0.2.7
cms|Mic|0.8.0
dacpac|Mic|1.6.0
datavirtualization|Mic|1.10.0
import|Mic|1.1.0
machine-learning|Mic|0.6.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
server-report|Mic|0.2.2
sql-assessment|Mic|0.5.0
whoisactive|Mic|0.1.4
schema-visualization|R0t|0.2.0
schema-visualization|R0t|0.3.0
sql-search|Red|0.4.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kpedroza** [comment]
Go to the Azure Accounts folder and rename (or delete, depending on how brave you feel in the moment) the file stored in it (azureTokenCache_azure_publicCloud), so you force Azure to create a new token

![MicrosoftTeams-image](https://user-images.githubusercontent.com/10052726/112681716-b8837a80-8e34-11eb-8165-b8a860314d1c.png)

**Comment by kenvanhyning** [comment]
Moving out of April ask mode.  If there is a known repro and fix ready, please bring back for April consideration.

**Comment by Charles-Gagnon** [comment]
Same basic issue as https://github.com/microsoft/azuredatastudio/issues/14159 so closing as duplicate
