### ISSUE TITLE
Using SQL Database Projects extension version 0.5.1 - Build fails

### ISSUE THREAD

**Issue by wknsJimmy** [microsoft/azuredatastudio#13955]
- Azure Data Studio Version:
- Version: 1.26.0-insider (user setup)
Commit: bcae0d2b02533376cec694455977739c44bb1069
Date: 2021-01-13T06:37:13.136Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

SQL Database Projects extension version: 0.5.1

Steps to Reproduce:

1.Connect to an existing database
2.Use the **Create Project from Database** option
3.Confirm the scripts for each object exist in the Project folders
4.Right click on the Project name and choose **Build**

5.Partial Build output window is as follows:

	_[ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\Jimmy_Blacksmith\\source\\repos\\HKTest\\ADSInsideRepo\\SIRDev\\SIRDev.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\Howard_Kealy\\.azuredatastudio-insiders\\extensions\\microsoft.sql-database-projects-0.5.1\\BuildDirectory"
    stdout: Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout:   Restore completed in 22.15 ms for c:\Users\Jimmy_Blacksmith\source\repos\HKTest\ADSInsideRepo\SIRDev\SIRDev.sqlproj.
    stdout: 
    stdout:   Creating a model to represent the project...
    stdout: 
    stdout: c:\Users\Jimmy_Blacksmith\.azuredatastudio-insiders\extensions\microsoft.sql-database-projects-0.5.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018: The "SqlBuildTask" task failed unexpectedly. [c:\Users\Jimmy_Blacksmith\source\repos\HKTest\ADSInsideRepo\SIRDev\SIRDev.sqlproj]
    stdout: c:\Users\Jimmy_Blacksmith\.azuredatastudio-insiders\extensions\microsoft.sql-database-projects-0.5.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018: System.TypeInitializationException: The type initializer for 'SqlSchemaModelStaticState' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [c:\Users\Jimmy_Blacksmith\source\repos\HKTest\ADSInsideRepo\SIRDev\SIRDev.sqlproj]_

6. Clicking on the link to the "Not found" file says "Unable to resolve non-existing file 'c:\Users\Jimmy_Blacksmith\source\repos\HKTest\ADSInsideRepo\SIRDev\SIRDev.sqlproj]' 
**Note the closing square bracket**

7. Confirmed that the **.sqlproj** file does actually exist in that location

**Comment by udeeshagautam** [comment]
@wknsJimmy thanks for reporting. Can you please help us with following answers,

1. does the same project build fine in SSDT?
2. does the project build in ADS stable december release?
3. which dotnet SDK version is installed on the box (at C:\Program Files\dotnet\ location)

**Comment by wknsJimmy** [comment]
1.  Not using SSDT – we are moving from using SSMS in order to use Database Projects in order to use Source control plus Azure DevOps to Build, Test and Deploy our solutions (Azure Data Factory, Azure SQL database, Azure Analysis Services and Power BI reports) – we chose to skip SSDT and go straight to ADS. Give me some time and I will check out if I have an issue with SSDT and get back to you.
  2.
2. No. I got the same error  message in the ADS stable December release – so I then went to the Insider release

3.
[cid:image003.png@01D6EA06.79E25DF0]

**Comment by wknsJimmy** [comment]
Just an update to point 1:
Yes the project builds in SSDT and I get my dacpac

**Comment by udeeshagautam** [comment]
@wknsJimmy thanks for the details. 

In the above message looks like image you shared for question-3 dotnet version did not come through. Can you please share the dotnet sdk version on you machine again. 

I tried reproing this with a few databases on our side but could not get the error so far. Is it possible for you to share the project or just the sqlproj file with us?

**Comment by kpapaj** [comment]
Looks the same problem in v0.6.1 version of SQL Datababase Project:
[ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\TMP\\TSQLV5\\TSQLV5.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\Karol\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.6.1\\BuildDirectory"
    stdout: Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout:   Restore completed in 54,92 ms for c:\TMP\TSQLV5\TSQLV5.sqlproj.
    stdout: 
    stdout:   Creating a model to represent the project...
    stdout: 
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018: The "SqlBuildTask" task failed unexpectedly. [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018: System.TypeInitializationException: The type initializer for 'SqlSchemaModelStaticState' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified. [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModel.RegisterImplementationForSqlModelImpl(ModelSchema storeSchema) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModel.SqlSchemaModelStaticState.RegisterModelSchema() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModel.SqlSchemaModelStaticState..cctor() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: 
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    --- End of inner exception stack trace --- [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModel..ctor(SqlDatabaseSchemaProvider databaseSchemaProvider, SqlPlatforms platform, ModelCollation collation, String modelFileName, ErrorManager errorManager, Boolean validationEnabled, Boolean initializeBuiltIns, Boolean validateCasingOnIdentifiers, Boolean convertCrossDbRefToWarning, Boolean isMsdb, ModelStorageType modelStorageType, Boolean storeSourceCodePositionAnnotations) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlSchemaModelConstructor.ConstructServiceImplementation() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Sql.Build.SqlTaskHost.CreateDataSchemaModel() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Tasks.Sql.TaskHostLoader.LoadImpl(ITaskHost providedHost, TaskLoggingHelper providedLogger) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Tasks.Sql.TaskHostLoader.Load(ITaskHost providedHost, TaskLoggingHelper providedLogger) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Tasks.Sql.SqlBuildTask.ExecuteLoadTaskHostStep() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Tasks.Sql.SqlBuildTask.ExecuteStep(Func`1 step) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Data.Tools.Schema.Tasks.Sql.SqlBuildTask.Execute() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: c:\Users\Karol\.azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask) [c:\TMP\TSQLV5\TSQLV5.sqlproj]
    stdout: 
    stdout: 
    stdout: Build FAILED.

**Comment by wknsJimmy** [comment]
> @wknsJimmy thanks for the details.
> 
> In the above message looks like image you shared for question-3 dotnet version did not come through. Can you please share the dotnet sdk version on your machine again.
> 
> I tried reproing this with a few databases on our side but could not get the error so far. Is it possible for you to share the project or just the sqlproj file with us?



> @wknsJimmy thanks for the details.
> 
> In the above message looks like image you shared for question-3 dotnet version did not come through. Can you please share the dotnet sdk version on your machine again.
> 
> I tried reproing this with a few databases on our side but could not get the error so far. Is it possible for you to share the project or just the sqlproj file with us?

The version of dotnet is as follows:

2.1.202 [C:\Program Files\dotnet\sdk]
2.1.403 [C:\Program Files\dotnet\sdk]
2.1.520 [C:\Program Files\dotnet\sdk]

And here is the content of the sqlproj file


<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" ToolsVersion="4.0">
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <Platform Condition=" '$(Platform)' == '' ">AnyCPU</Platform>
    <Name>SIRDev</Name>
    <SchemaVersion>2.0</SchemaVersion>
    <ProjectVersion>4.1</ProjectVersion>
    <ProjectGuid>{45D9424E-B64C-4488-9036-6D4A512F9979}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider</DSP>
    <OutputType>Database</OutputType>
    <RootPath>
    </RootPath>
    <RootNamespace>SIRDev</RootNamespace>
    <AssemblyName>SIRDev</AssemblyName>
    <ModelCollation>1033, CI</ModelCollation>
    <DefaultFileStructure>BySchemaAndSchemaType</DefaultFileStructure>
    <DeployToDatabase>True</DeployToDatabase>
    <TargetFrameworkVersion>v4.5</TargetFrameworkVersion>
    <TargetLanguage>CS</TargetLanguage>
    <AppDesignerFolder>Properties</AppDesignerFolder>
    <SqlServerVerification>False</SqlServerVerification>
    <IncludeCompositeObjects>True</IncludeCompositeObjects>
    <TargetDatabaseSet>True</TargetDatabaseSet>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <OutputPath>bin\Release\</OutputPath>
    <BuildScriptName>$(MSBuildProjectName).sql</BuildScriptName>
    <TreatWarningsAsErrors>False</TreatWarningsAsErrors>
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <DefineDebug>false</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <OutputPath>bin\Debug\</OutputPath>
    <BuildScriptName>$(MSBuildProjectName).sql</BuildScriptName>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <DefineDebug>true</DefineDebug>
    <DefineTrace>true</DefineTrace>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">11.0</VisualStudioVersion>
    
    <SSDTExists Condition="Exists('$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets')">True</SSDTExists>
    <VisualStudioVersion Condition="'$(SSDTExists)' == ''">11.0</VisualStudioVersion>
  </PropertyGroup>
  <Import Condition="'$(NetCoreBuild)' == 'true'" Project="$(NETCoreTargetsPath)\Microsoft.Data.Tools.Schema.SqlTasks.targets"/>
  <Import Condition="'$(NetCoreBuild)' != 'true' AND '$(SQLDBExtensionsRefPath)' != ''" Project="$(SQLDBExtensionsRefPath)\Microsoft.Data.Tools.Schema.SqlTasks.targets"/>
  <Import Condition="'$(NetCoreBuild)' != 'true' AND '$(SQLDBExtensionsRefPath)' == ''" Project="$(MSBuildExtensionsPath)\Microsoft\VisualStudio\v$(VisualStudioVersion)\SSDT\Microsoft.Data.Tools.Schema.SqlTasks.targets"/>
  <ItemGroup>
    <PackageReference Condition="'$(NetCoreBuild)' == 'true'" Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All"/>
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Properties"/>
    <Folder Include="Views"/>
    <Folder Include="UserDefinedTypes"/>
    <Folder Include="Tables"/>
    <Folder Include="StoredProcedures"/>
    <Folder Include="Security"/>
    <Folder Include="Functions"/>
  </ItemGroup>
  <Target Name="AfterClean">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json"/>
  </Target>
  <ItemGroup>
    <Build Include="Views\vSSDWANv2.sql"/>
    <Build Include="Views\vServerOnPremisev2.sql"/>
    <Build Include="Views\vServerOnPremise.sql"/>
    <Build Include="Views\vServerInCloudv2.sql"/>
    <Build Include="Views\vServerInCloud.sql"/>
    <Build Include="Views\vMSLicenseUsagev2.sql"/>
    <Build Include="Views\vMSLicenseUsage.sql"/>
    <Build Include="Views\VL_Job_Performance_Day_Range_From_New_To_Completedv2.sql"/>
    <Build Include="Views\vCountryKPIIndexv2.sql"/>
    <Build Include="Views\vCountryKPIIndex.sql"/>
    <Build Include="Views\vBOSSUsagev2.sql"/>
    <Build Include="Views\vBOSSUsage.sql"/>
    <Build Include="Views\Supervisor.sql"/>
    <Build Include="Views\SIR Volumes.sql"/>
    <Build Include="Views\Service.sql"/>
    <Build Include="Views\Product - Service.sql"/>
    <Build Include="Views\Product - Job.sql"/>
    <Build Include="Views\Party Customer.sql"/>
    <Build Include="Views\Order Date.sql"/>
    <Build Include="Views\Managing Affiliate.sql"/>
    <Build Include="Views\Line of Business.sql"/>
    <Build Include="Views\Job.sql"/>
    <Build Include="Views\Job Scheduled Date From.sql"/>
    <Build Include="Views\Job Performance - Day Range From New To Confirmed.sql"/>
    <Build Include="Views\Job Performance - Day Range From New To Completed.sql"/>
    <Build Include="Views\Job Performance - Day Range From In Progress To Completed.sql"/>
    <Build Include="Views\Job Performance - Day Range From Confirmed To In Progress.sql"/>
    <Build Include="Views\Inspector.sql"/>
    <Build Include="Views\Executing Affiliate.sql"/>
    <Build Include="Views\Date - Service Last Under App.sql"/>
    <Build Include="Views\Date - Service Last Confirmed.sql"/>
    <Build Include="Views\Date - Service Last Completed.sql"/>
    <Build Include="Views\Date - Service Last Cancel.sql"/>
    <Build Include="Views\Date - Service First New.sql"/>
    <Build Include="Views\Date - Service Execution To.sql"/>
    <Build Include="Views\Date - Service Execution From.sql"/>
    <Build Include="Views\Date - Service Execution Expected.sql"/>
    <Build Include="Views\Date - Order Created.sql"/>
    <Build Include="Views\Date - Nomination.sql"/>
    <Build Include="Views\Date - Job Scheduled To.sql"/>
    <Build Include="Views\Date - Job Scheduled From.sql"/>
    <Build Include="Views\Date - Job Last Validated.sql"/>
    <Build Include="Views\Date - Job Last InProgress.sql"/>
    <Build Include="Views\Date - Job Last Confirmed.sql"/>
    <Build Include="Views\Date - Job Last Completed.sql"/>
    <Build Include="Views\Date - Job Last Cancel.sql"/>
    <Build Include="Views\Date - Job First New.sql"/>
    <Build Include="Views\Date - Job Creation.sql"/>
    <Build Include="Views\Customer Care.sql"/>
    <Build Include="UserDefinedTypes\Phone.sql"/>
    <Build Include="UserDefinedTypes\OrderNumber.sql"/>
    <Build Include="UserDefinedTypes\NameStyle.sql"/>
    <Build Include="UserDefinedTypes\Name.sql"/>
    <Build Include="UserDefinedTypes\Flag.sql"/>
    <Build Include="UserDefinedTypes\AccountNumber.sql"/>
    <Build Include="Tables\xFrom_New_To_Confirmed.sql"/>
    <Build Include="Tables\xFrom_New_To_Completed.sql"/>
    <Build Include="Tables\xFrom_In_Progress_To_Completed.sql"/>
    <Build Include="Tables\xFrom_Confirmed_To_In_Progress.sql"/>
    <Build Include="Tables\WorkOrderConfirmation.sql"/>
    <Build Include="Tables\User.sql"/>
    <Build Include="Tables\Tmp_WorkOrderConfirmation.sql"/>
    <Build Include="Tables\Tmp_User.sql"/>
    <Build Include="Tables\Tmp_Service.sql"/>
    <Build Include="Tables\Tmp_Product.sql"/>
    <Build Include="Tables\Tmp_Output_Report.sql"/>
    <Build Include="Tables\Tmp_Order.sql"/>
    <Build Include="Tables\Tmp_Location.sql"/>
    <Build Include="Tables\Tmp_Job.sql"/>
    <Build Include="Tables\Tmp_Data_Entry.sql"/>
    <Build Include="Tables\Tmp_Customer.sql"/>
    <Build Include="Tables\Tmp_Affiliates.sql"/>
    <Build Include="Tables\Subscription Computer Country.sql"/>
    <Build Include="Tables\SGS Geography Trimmed.sql"/>
    <Build Include="Tables\Service.sql"/>
    <Build Include="Tables\Servers On Premise.sql"/>
    <Build Include="Tables\Servers in Cloud.sql"/>
    <Build Include="Tables\Servers in Cloud Aug 2020.sql"/>
    <Build Include="Tables\Servers in Cloud 31 Aug 2020.sql"/>
    <Build Include="Tables\Servers in Cloud 25 Aug 2020.sql"/>
    <Build Include="Tables\Server Tracking 31 Aug 2020.sql"/>
    <Build Include="Tables\SDWAN.sql"/>
    <Build Include="Tables\SDWAN Info.sql"/>
    <Build Include="Tables\SDWAN 2020 08 25.sql"/>
    <Build Include="Tables\RecoveryFolders_Global.sql"/>
    <Build Include="Tables\RecoveryFolders_France.sql"/>
    <Build Include="Tables\RecoveryFolders_CountryName.sql"/>
    <Build Include="Tables\Project Master.sql"/>
    <Build Include="Tables\Project Data.sql"/>
    <Build Include="Tables\Product.sql"/>
    <Build Include="Tables\Output_Report.sql"/>
    <Build Include="Tables\Order.sql"/>
    <Build Include="Tables\OPSData.sql"/>
    <Build Include="Tables\MS License Usage.sql"/>
    <Build Include="Tables\Location.sql"/>
    <Build Include="Tables\LastExtractDate.sql"/>
    <Build Include="Tables\Job_Performance_Day_Range_From_New_To_Confirmed.sql"/>
    <Build Include="Tables\Job_Performance_Day_Range_From_New_To_Completed.sql"/>
    <Build Include="Tables\Job_Performance_Day_Range_From_In_Progress_To_Completed.sql"/>
    <Build Include="Tables\Job_Performance_Day_Range_From_Confirmed_To_In_Progress.sql"/>
    <Build Include="Tables\Job.sql"/>
    <Build Include="Tables\ipplan.sql"/>
    <Build Include="Tables\Inet.sql"/>
    <Build Include="Tables\hkBISPs.sql"/>
    <Build Include="Tables\Geography.sql"/>
    <Build Include="Tables\F_SIRHK.sql"/>
    <Build Include="Tables\F_SIR.sql"/>
    <Build Include="Tables\filter_region.sql"/>
    <Build Include="Tables\filter_lob.sql"/>
    <Build Include="Tables\filter_kam.sql"/>
    <Build Include="Tables\filter_country.sql"/>
    <Build Include="Tables\filter_activity.sql"/>
    <Build Include="Tables\Fact_Total.sql"/>
    <Build Include="Tables\ExecutionLogHistory.sql"/>
    <Build Include="Tables\ExecutionControl.sql"/>
    <Build Include="Tables\ErrorCounts_Global.sql"/>
    <Build Include="Tables\ErrorCounts_CountryName.sql"/>
    <Build Include="Tables\D_Supervisor.sql"/>
    <Build Include="Tables\D_Service.sql"/>
    <Build Include="Tables\D_Product_Service.sql"/>
    <Build Include="Tables\D_Product_Job.sql"/>
    <Build Include="Tables\D_Party_Customer.sql"/>
    <Build Include="Tables\D_Order_Date_Set.sql"/>
    <Build Include="Tables\D_Order_Date_Full.sql"/>
    <Build Include="Tables\D_Order_Date.sql"/>
    <Build Include="Tables\D_Managing_Affiliate.sql"/>
    <Build Include="Tables\D_Line_of_Business.sql"/>
    <Build Include="Tables\D_Job_Performance_Day_Range_From_New_To_Confirmed.sql"/>
    <Build Include="Tables\D_Job_Performance_Day_Range_From_New_To_Completed.sql"/>
    <Build Include="Tables\D_Job_Performance_Day_Range_From_In_Progress_To_Completed.sql"/>
    <Build Include="Tables\D_Job_Performance_Day_Range_From_Confirmed_To_In_Progress.sql"/>
    <Build Include="Tables\D_Job.sql"/>
    <Build Include="Tables\D_Inspector.sql"/>
    <Build Include="Tables\D_Executing_Affiliate.sql"/>
    <Build Include="Tables\D_Date.sql"/>
    <Build Include="Tables\D_Customer_Care.sql"/>
    <Build Include="Tables\D_Country.sql"/>
    <Build Include="Tables\D_Affiliates.sql"/>
    <Build Include="Tables\DateRangeTable_CountryName.sql"/>
    <Build Include="Tables\DateDimension.sql"/>
    <Build Include="Tables\Data_Entry.sql"/>
    <Build Include="Tables\Customer.sql"/>
    <Build Include="Tables\Computer.sql"/>
    <Build Include="Tables\CMDBVM.sql"/>
    <Build Include="Tables\Clouds.sql"/>
    <Build Include="Tables\BOSS extract.sql"/>
    <Build Include="Tables\Affiliates.sql"/>
    <Build Include="Tables\2020-10-25 Server tracking.sql"/>
    <Build Include="StoredProcedures\UpdateExtractDate.sql"/>
    <Build Include="StoredProcedures\UpdateExecutionControl.sql"/>
    <Build Include="StoredProcedures\TruncateDataMartTables.sql"/>
    <Build Include="StoredProcedures\ReleaseXMLLock.sql"/>
    <Build Include="StoredProcedures\ReleaseListingLock.sql"/>
    <Build Include="StoredProcedures\ReleaseFolderClearLock.sql"/>
    <Build Include="StoredProcedures\ReleaseExcelLock.sql"/>
    <Build Include="StoredProcedures\ProcDateRange.sql"/>
    <Build Include="StoredProcedures\Load_F_SpecialOffer.sql"/>
    <Build Include="StoredProcedures\Load_F_SIR_Volumes.sql"/>
    <Build Include="StoredProcedures\Load_F_Sales.sql"/>
    <Build Include="StoredProcedures\Load_F_Certnet.sql"/>
    <Build Include="StoredProcedures\Load_D_Supervisor.sql"/>
    <Build Include="StoredProcedures\Load_D_ShipMethod.sql"/>
    <Build Include="StoredProcedures\Load_D_Service.sql"/>
    <Build Include="StoredProcedures\Load_D_Product_Service.sql"/>
    <Build Include="StoredProcedures\Load_D_Product_Job.sql"/>
    <Build Include="StoredProcedures\Load_D_Product.sql"/>
    <Build Include="StoredProcedures\Load_D_Party_Customer.sql"/>
    <Build Include="StoredProcedures\Load_D_Order_Date.sql"/>
    <Build Include="StoredProcedures\Load_D_Managing_Affiliate.sql"/>
    <Build Include="StoredProcedures\Load_D_Line_Of_Business.sql"/>
    <Build Include="StoredProcedures\Load_D_Job_Performance_Day_Range_From_New_To_Confirmed.sql"/>
    <Build Include="StoredProcedures\Load_D_Job_Performance_Day_Range_From_New_To_Completed.sql"/>
    <Build Include="StoredProcedures\Load_D_Job_Performance_Day_Range_From_In_Progress_To_Completed.sql"/>
    <Build Include="StoredProcedures\Load_D_Job_Performance_Day_Range_From_Confirmed_To_In_Progress.sql"/>
    <Build Include="StoredProcedures\Load_D_Job.sql"/>
    <Build Include="StoredProcedures\Load_D_Inspector.sql"/>
    <Build Include="StoredProcedures\Load_D_Executing_Affiliate.sql"/>
    <Build Include="StoredProcedures\Load_D_Customer_SCD.sql"/>
    <Build Include="StoredProcedures\Load_D_CustomerCare.sql"/>
    <Build Include="StoredProcedures\Insert_TmpInSTG.sql"/>
    <Build Include="StoredProcedures\Insert_TmpInDataMart____.sql"/>
    <Build Include="StoredProcedures\InsertInFolderList.sql"/>
    <Build Include="StoredProcedures\InsertDefaultMember_Dimension.sql"/>
    <Build Include="StoredProcedures\GenerateMerge_Dimension_SCD.sql"/>
    <Build Include="StoredProcedures\GenerateMerge_Dimension.sql"/>
    <Build Include="StoredProcedures\GenerateMergeStatement.sql"/>
    <Build Include="StoredProcedures\FeedSTGTable.sql"/>
    <Build Include="StoredProcedures\FeedDataMartTable.sql"/>
    <Build Include="StoredProcedures\FakeSP.sql"/>
    <Build Include="StoredProcedures\CreateXMLLock.sql"/>
    <Build Include="StoredProcedures\CreateListingLock.sql"/>
    <Build Include="StoredProcedures\CreateFolderListIfNotExists.sql"/>
    <Build Include="StoredProcedures\CreateFolderClearLock.sql"/>
    <Build Include="StoredProcedures\CreateExcelLock.sql"/>
    <Build Include="StoredProcedures\ClearFolderList.sql"/>
    <Build Include="StoredProcedures\CheckErrors.sql"/>
    <Build Include="StoredProcedures\BulkCopy_TmpInSTG.sql"/>
    <Build Include="Security\STG_SP.sql"/>
    <Build Include="Security\STG_Global.sql"/>
    <Build Include="Security\STG_CountryName.sql"/>
    <Build Include="Security\KPI.sql"/>
    <Build Include="Security\DM_SP.sql"/>
    <Build Include="Security\DM_SEC.sql"/>
    <Build Include="Security\DM_Global.sql"/>
    <Build Include="Security\DM_CountryName.sql"/>
    <Build Include="Security\DM.sql"/>
    <Build Include="Security\ADF_CountryName.sql"/>
    <Build Include="Security\ADF.sql"/>
    <Build Include="Functions\tfn_Tally.sql"/>
    <Build Include="Functions\DateRange.sql"/>
  </ItemGroup>
</Project>

**Comment by wknsJimmy** [comment]
[SIRDev.txt](https://github.com/microsoft/azuredatastudio/files/6032454/SIRDev.txt)

Here is the sqlproj file with the extension changed to txt

**Comment by supamii** [comment]
@wknsJimmy - I had the same problem you did.  Missing System.Runtime is seems fundamentally off.

I had Visual Studio 2017 Pro with dotnet core 2.1 (no other dotnet core runtimes/sdks)


-- On a hunch I went head and installed a more recent version of dotnet core (requires visual studio 2019)

I went ahead and installed Visual Studio 2019 Community with dotnet core 3.x


The build feature in Azure Data Studio works now

**Comment by kpapaj** [comment]
@supamii - I have VS 2017, VS 2019 and .NET SDK 2.1.521 installed, still the problem persists ...

**Comment by supamii** [comment]
If you're looking to unblock yourself, try to install dotnet3.x

**Comment by kpapaj** [comment]
Installing dotnet 3.x doesn't help, the same error again.

**Comment by udeeshagautam** [comment]
Hi @wknsJimmy, we tried reproing the issue but could not so far. I tried using the project file you shared and after removing the objects (tables/views, which I dont have) it is building fine with ADS and command prompt. Following are few steps that can help us debug the issue further.

1. We are using dotnet.exe to do the build, so can you please help check if you run the same cmmand from command prompt - are you getting the exact same error (you can copy the command from output window)

"C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\Jimmy_Blacksmith\\source\\repos\\HKTest\\ADSInsideRepo\\SIRDev\\SIRDev.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\Howard_Kealy\\.azuredatastudio-insiders\\extensions\\microsoft.sql-database-projects-0.5.1\\BuildDirectory"

2. If so, I think one possibility is that the machine has a lower version of dotnet SDK. can you please check that you have dotnet core SDK 3.1 or higher installed and System.Runtime present on the machine 

Paths to check
- C:\Program Files\dotnet\sdk\<version> - please make sure you have **3.1 or higher version of SDK**
- C:\Program Files\dotnet\sdk\<version>\Microsoft\Microsoft.NET.Build.Extensions\net461\lib\System.Runtime.dll

If the folder seems incomplete please install from https://dotnet.microsoft.com/download/dotnet/3.1

**Comment by adriennn** [comment]
I'm seeing a similar error appearing out of the blue after an update to the SQL Database Project extension 0.14.1 (which fixed another bug) with either of the following:

.NET 3.1.416
.NET 6.0.101

ADS: 1.34.0 (user setup)

is there a way to rollback the extension to something before 0.14.1 in order to debug?

**Comment by Charles-Gagnon** [comment]
@adriennn You can download previous versions of the extension by replacing the ##.##.## with the version you want in this URL : https://sqlopsextensions.blob.core.windows.net/extensions/sql-database-projects/sql-database-projects-##.##.##.vsix

e.g. https://sqlopsextensions.blob.core.windows.net/extensions/sql-database-projects/sql-database-projects-0.14.0.vsix
