### ISSUE TITLE
Connecting to Azure SQL DB using MFA on Azure Data Studio

### ISSUE THREAD

**Issue by alex-rolls** [microsoft/azuredatastudio#13989]
- Azure Data Studio Version: 1.25.1 (user setup) 
Azure data studio is not listening to the port number which is being generated in the URL that you are being directed to. 

Steps to Reproduce:

1. Setup AD for SQL DB
2. Try to connect to SQL DB using Azure Data Studio
3. Add account
4. Enter Details

**Comment by alex-rolls** [comment]
I have tried the below 2 versions for Azure Data Studio: 1.25.1 
and 1.26.0 insider build (https://github.com/Microsoft/azuredatastudio) 

I believe it is similar or the same as this issue but is still hasn't been fixed? 

https://github.com/microsoft/azuredatastudio/issues/5742

**Comment by alex-rolls** [comment]
I am getting the below messages in the console: 

DevTools failed to load SourceMap: Could not parse content for file:///C:/errorObject.js.map: Unexpected end of JSON input

Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:123 [Extension Host] Error: unable to get local issuer certificate - 
m @ Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:123

  ERR Failed to create Object Explorer session

Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:123 [Extension Host] Error: unable to get local issuer certificate - 

Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:123 [Extension Host] Error: unable to get local issuer certificate - 

ApplicationInsights:CorrelationIdManager 
Array(1)
0: {code: "UNABLE_TO_GET_ISSUER_CERT_LOCALLY"}

(node:37124) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

**Comment by alex-rolls** [comment]
I authenticate this account: 
![image](https://user-images.githubusercontent.com/72560461/120793034-49aa5800-c52e-11eb-9e58-8e3f7677375b.png)

![image](https://user-images.githubusercontent.com/72560461/120793101-634b9f80-c52e-11eb-891f-dd9e52e54c99.png)

Get the below error: 

![image](https://user-images.githubusercontent.com/72560461/120793161-7494ac00-c52e-11eb-8fb7-e333ac820f87.png)

**Comment by cheenamalhotra** [comment]
Closing as it's an old issue and may not occur anymore with MSAL. 
Please open a new issue if it occurs with latest ADS stable release.
