### ISSUE TITLE
Database table list listed

### ISSUE THREAD

**Issue by martinthogersen** [microsoft/azuredatastudio#13986]
Issue Type: <b>Bug</b>

1. Open the list of servers
2. Expand a connection (under Servers)
3. I would expect to see a list of tables from the database, but nothing is shown

I can find tables manually and query data by writing queries manually (eg. "SELECT * FROM orders" is working).

![image](https://user-images.githubusercontent.com/239008/104788079-8a791e80-5791-11eb-9935-ffa35145255e.png)

The database properties doesn't work either:

![image](https://user-images.githubusercontent.com/239008/104788128-aaa8dd80-5791-11eb-8b00-4c36eb8a1a59.png)

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:57:41.946Z)
OS version: Darwin x64 20.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|32.00GB (2.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
datavirtualization|Mic|1.10.0

</details>

**Comment by martinthogersen** [comment]
[application-logs.zip](https://github.com/microsoft/azuredatastudio/files/5851267/application-logs.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/5851271/console.log)

Please see the attached files.

**Comment by cssuh** [comment]
@martinthogersen Have you updated to the latest version? Please let me know if you're still experiencing this issue.
