### ISSUE TITLE
Update icon on macOS to match the new UI language

### ISSUE THREAD

**Issue by dadepretto** [microsoft/azuredatastudio#14014]
I'm always frustrated when I look at the dock of my Mac with macOS Big Sur and see the Azure Data Studio icon popping out with its irregular design.

I'd like to see a new icon for macOS Big Sur users that match the rest of the new UI language.

I know it isn't a priority by any means and that other Microsoft products still have to update as well (eg. VS/VSCode), but I personally find that with the new macOS update the ADS icon got really more distracting than ever for Mac users.

<img width="626" alt="macOS Big Sur dock with Azure Data Studio icon" src="https://user-images.githubusercontent.com/42669027/105417866-8428ed80-5c3c-11eb-9e63-90cd2bddc9d1.png">

**Comment by kburtram** [comment]
@dadepretto thanks for reporting this issue.  We'll pass your feedback to our UX designers.

**Comment by desmortum** [comment]
VSCode just updated with new icon! Need to catch up.
