### ISSUE TITLE
straing vehaivor in check, lack of optoin to  check / uncheck all

### ISSUE THREAD

**Issue by pablogarnica** [microsoft/azuredatastudio#14016]
The process of check / un check has a strange behavior, lack a option to check / uncheck all

**Comment by alanrenmsft** [comment]
@pablogarnica could you please share a screenshot? I can't tell which piece of UI you are talking about here.

**Comment by kburtram** [comment]
Closing since this doesn't have enough context to properly route.  Please reactive or log another issue with additional context if you are still having problems with this UI.
