### ISSUE TITLE
Cannot delete the postgres server group after a postgres server group is created but gets stuck due to insufficient resource on ADS

### ISSUE THREAD

**Issue by zxli** [microsoft/azuredatastudio#14024]
- Azure Data Studio Version: 1.26.0-insider (user setup)
- Azure Arc extension Version: 0.7.1
- Azure Data CLI extension Version: 0.5.1

Steps to Reproduce:

1. Create a postgres server group which will get stuck due to insufficient resource for sure on ADS.
2. Close the notebook deployment window while the created postgres server group gets stuck on ADS.
3. Refresh the Arc controller management page so the stuck postgres server group shows up on ADS.
4. Click the stuck postgres server group on the Arc controller management page to bring up the postgres server group page on ADS.
5. Hit "Delete" button

Expected - Deletion should work.

Actual - Nothing seems to happen. I don't see "azdata arc postgres server delete" command is issued in the output windows of Azure Data CLI.

After closing and re-opening ADS app, "Delete" button starts to work.

**Comment by bergeron** [comment]
I see this too.  For me it doesn't require the deployment to get stuck.  It requires (1) Deploy PG from within ADS (2) Manage it (3) Try to delete it.  Nothing happens.  It does work after restarting ADS or if PG was deployed outside of ADS.  Attaching a debugger to see why it doesn't execute.

**Comment by nasc17** [comment]
I see this issue as well but I am also seeing it when trying to edit the postgres server. The azdata commands are not able to run before progress error occurs. Can also confirm it works after restarting ADS. 

1. Deploy postgres server
2. Mange it -> Compute & Storage page
3. Save a change to worker count, CPU, or memory

Expected: Progress notification should have shown and error that is being caught should show error message on window.

Version: 1.26.0-insider
Azure Arc extension v0.7.1
Azure Data CLI extension v0.5.1

**Comment by bergeron** [comment]
This is the error message I see in the debugger.  For some reason it's not surfaced in the UI even though  `vscode.window.showErrorMessage` is executed.  I'm not exactly sure which line is throwing this.

```
message:'Converting circular structure to JSON\n    --> starting at object with constructor 'Node'\n    |     property 'next' -> object with constructor 'Node'\n    --- property 'prev' closes the circle'
stack:'TypeError: Converting circular structure to JSON\n    --> starting at object with constructor 'Node'\n    |     property 'next' -> object with constructor 'Node'\n    --- property 'prev' closes the circle\n\tat JSON.stringify (<anonymous>)\n\tat stringify (c:\\azuredatastudio\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:18:21)\n\tat Function.serializeRequestArguments (c:\\azuredatastudio\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:576:23)\n\tat RPCProtocol._remoteCall (c:\\azured…otocol.js:355:58)\n\tat Proxy.<anonymous> (c:\\azuredatastudio\\out\\vs\\workbench\\services\\extensions\\common\\rpcProtocol.js:146:41)\n\tat ExtHostProgress.withProgress (c:\\azuredatastudio\\out\\vs\\workbench\\api\\common\\extHostProgress.js:25:25)\n\tat Object.withProgress (c:\\azuredatastudio\\out\\vs\\workbench\\api\\common\\extHost.api.impl.js:472:44)\n\tat c:\\azuredatastudio\\extensions\\arc\\out\\ui\\dashboards\\postgres\\postgresOverviewPage.js:149:41\n\tat processTicksAndReject...
```
