### ISSUE TITLE
Azure Arc controllers section gets stuck when opening ADS app.

### ISSUE THREAD

**Issue by zxli** [microsoft/azuredatastudio#14025]
- Azure Data Studio Version: 1.26.0-insiders (user setup)
- Azure Arc extension Version: 0.7.1
- Azure Data CLI extension Version: 0.5.1

Steps to Reproduce:

1. Open ADS app.
2. While ADS is determining Python location, expand an Arc controller.

Expected - The Arc controller should be expanded properly.

Actual - ADS gets stuck when expanding the Arc controller forever.

**Comment by bergeron** [comment]
I can reproduce this.  With this additional error when I right click -> Remove controller.

Version: 1.26.0-insider
Commit: 5f61becd365649d0075b8eb44bcfb381160868ef
Azure Arc extension v0.7.1
Azure Data CLI extension v0.5.1

![image](https://user-images.githubusercontent.com/3500406/105530512-c255f980-5c9c-11eb-9a27-1fbdc52b3cfd.png)

**Comment by Charles-Gagnon** [comment]
@zxli @bergeron What do you mean "determining Python location"? Do you mean determining azdata location?

**Comment by zxli** [comment]
In the output window of Azure Data CLI, I see "Python location 'C:\Program Files (x86)\Microsoft SDKs\Azdata\CLI\python.exe'". If I expand Arc controller before seeing that message, this bug would repro.

**Comment by Charles-Gagnon** [comment]
Gotcha, thanks. Yeah that's just printing the output from azdata --version. 

I have a repro too and am working on a fix.

**Comment by Charles-Gagnon** [comment]
@bergeron I'm not able to repro your issue though. Do you have a consistent repro of the issue?
