### ISSUE TITLE
Missing git cherry-pick in Azure Data Studio

### ISSUE THREAD

**Issue by mahmoudshaaban** [microsoft/azuredatastudio#14022]
Issue Type: <b>Feature Request</b>

In Azure Data Studio (ADS), I cannot find the git cherry-pick feature.
Could you please add it?

**Comment by dzsquared** [comment]
This was added to VS Code in 1.52 (Nov 2020), at this time Azure Data Studio is based on VS Code 1.48.  We do regularly bring in the VS Code updates after some time.

https://code.visualstudio.com/updates/v1_52#_git-new-commands

**Comment by mahmoudshaaban** [comment]
> 
> 
> This was added to VS Code in 1.52 (Nov 2020), at this time Azure Data Studio is based on VS Code 1.48. We do regularly bring in the VS Code updates after some time.
> 
> https://code.visualstudio.com/updates/v1_52#_git-new-commands

Thanks for the propmet response and info. Do we have an estimated time plan in the roadmap when this can be done?

All the best,
Mahmoud

**Comment by alanrenmsft** [comment]
@mahmoudshaaban I would say in a month or so.

**Comment by alanrenmsft** [comment]
Moving this to March milestone since I think the merge will be done by then, and we can verify and close this issue at the end of march release.

**Comment by mahmoudshaaban** [comment]
> 
> 
> Moving this to March milestone since I think the merge will be done by then, and we can verify and close this issue at the end of march release.

@alanrenmsft Thanks a lot!

**Comment by kburtram** [comment]
We pick up vscode changes periodically on an on-going basis.  So we don't track individual upstream features as issues in the repo.  Thanks!
