### ISSUE TITLE
Add BACPAC support for Azure DB "Backup\Restore"

### ISSUE THREAD

**Issue by iforlife** [microsoft/azuredatastudio#1403]
backup and restore from Azure is super slow. I keep windows vm only to be able to backup and restore azure sql db with dacpacs via ssms

**Comment by llali** [comment]
@iforlife backup and restore are not available for Azure db in SQL Operation Studio or ssms. It's bug if you see the feature available. You can import a database using a bacpac in ssms which the feature is not available in SQL Ops Studio at this moment.

**Comment by iforlife** [comment]
Sorry, I meant `bacpac`. It would be very useful for me to have this feature in SQL Ops Studio.

**Comment by tolemac** [comment]
@iforlife can you change the title including "bacpac" word? In order to others user can upvote it.

**Comment by chaim1221** [comment]
Any word on this?

**Comment by udeeshagautam** [comment]
@iforlife thanks for opening the issue. 

We do not have Backup/Restore support (to/from .bak files) for Azure DBs. 

But we do have Import/Export support from/to .bacpac files enabled through **SQL Server Dacpac Extension**. This works against both Azure and On Premise databases. Thsi also provides support for extact/publish for dacpacs. Please let us know if this would solve your use case.
