### ISSUE TITLE
Refresh button in server/database dashboard doesn't refresh server/database

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#14031]
From UX Benchmark study, users created a new table and attempted to refresh the dashboard, but the dashboard did not reflect the change. When users refreshed in object explorer, then dashboard got refreshed appropriately.

**Comment by alanrenmsft** [comment]
I am not able to reproduce the issue:
1. open database dashboard
2. create a table 
3. refresh the database dashboard
I see the new table show up immediately.
