### ISSUE TITLE
Unexpected error when opening .sql file from git folder

### ISSUE THREAD

**Issue by federicoaguirre1** [microsoft/azuredatastudio#14044]
Issue Type: <b>Bug</b>

I get an error after opening a .sql file that is on a git folder

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1035G1 CPU @ 1.00GHz (8 x 1190)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.80GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
azdata-sanddance|msr|3.1.0
sql-prompt|Red|0.2.5
sql-search|Red|0.4.0
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@federicoaguirre1 could you please add the repro steps?

**Comment by federicoaguirre1** [comment]
Hello Alan, sorry for the late reply.

I have got a .sql file on my local git repository folder
[image: image.png]

then, I try to open it with azure data studio
[image: image.png]
and I get this error (I cannot use that file in azure data studio, it does
not allow me to run the query, or connect with any db, nothing, what I need
to do is to copy and paste the sql code into another new window)
[image: image.png]

Thank you,

Federico

**Comment by alanrenmsft** [comment]
@federicoaguirre1 Thanks for reply, I am not able see the images you sent, I am afraid you have to open github and attach images:

![image](https://user-images.githubusercontent.com/13777222/106169378-2a488c00-6144-11eb-8f2f-64761b0936e4.png)

**Comment by federicoaguirre1** [comment]
![image](https://user-images.githubusercontent.com/70523193/106190819-13388700-61a2-11eb-8202-aac7b57081a9.png)
![image (2)](https://user-images.githubusercontent.com/70523193/106190820-13d11d80-61a2-11eb-93df-c5482c7ae679.png)
![image (1)](https://user-images.githubusercontent.com/70523193/106190826-15024a80-61a2-11eb-8264-401fed17ce17.png)

**Comment by Charles-Gagnon** [comment]
This is a similar issue to https://github.com/microsoft/azuredatastudio/issues/10259. I'm not sure if the PR that fixes the Notebook issue will also fix this though so leaving this one open for the time being.

@pensivebrian If you get a chance could you test out this scenario with your fix to see if it also resolves this one?

**Comment by pensivebrian** [comment]
My fix is for notebooks only - I still need to figure out an automated test for that.

For the .sql editor, we have to make a fix in the sqltoolsservice.

**Comment by alanrenmsft** [comment]
@federicoaguirre1 the issue is caused by the `%20` in the file path, we are working on a fix. for now, to unblock you, you can either remove the %20 string from the folder name or copy the query to a new window and run it.

**Comment by federicoaguirre1** [comment]
Alright, thank you.
Have a good day
Federico
