### ISSUE TITLE
Declarative table items are never cleared

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14048]
When setting the rows for a declarative table if there are any components in the previous data we never clear them from the container - which means that they won't be garbage collected until the table itself is destroyed.

This normally isn't going to be a huge impact since most of our tables are static things - but if there's a table such as the Arc PG Parameters table which can be refreshed to load new rows then all the previous components will stick around and quickly cause a larger perf issue. 

There's also a side problem of us calling "addItems" every single time a property is updated for the table - since we do that as part of the getPropertiesForMainThread. addItems should be only called for new items - not for any existing items (or when other properties were changed).

**Comment by alanrenmsft** [comment]
@Charles-Gagnon could you please put this in a milestone?

**Comment by kenvanhyning** [comment]
Doesn't meet ask mode bar.
