### ISSUE TITLE
Hour and date of cell execution

### ISSUE THREAD

**Issue by cristobalsarome** [microsoft/azuredatastudio#14056]
**Is your feature request related to a problem? Please describe.**
Sometimes I'm not sure when I executed a cell with sql code

**Describe the solution or feature you'd like**
I would add the date and hour of exectution, besides the execution time (already showed)

**Additional context**
I think it should be very useful and not hard to implement

**Comment by chlafreniere** [comment]
This is being tracked by #9237. Closing this as dupe.
