### ISSUE TITLE
Switching database doesn't work.

### ISSUE THREAD

**Issue by mees-** [microsoft/azuredatastudio#14054]
Issue Type: <b>Bug</b>

I have two databases. They have the exact same tables and columns. When I switch between them in a "select top 1000" query it always returns the rows for the database that I right-clicked "select top 1000" on

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.18363

**Comment by kburtram** [comment]
@mees- I wasn't able to repro this issue.  I used the query `select * from sys.tables` and used the database drop-down in the query editor to switch between databases.  The query returned the tables for the selected table.  

Am I missing something else in the repro?  You may try using `USE databasename` in your SQL scripts as a workaround (this is basically what the drop-down does).

**Comment by mees-** [comment]
@kburtram I have also not been able to reproduce this bug since I first encountered it. When I first noticed it I was very sure that I was looking at the wrong data. As I said, I haven't had the issue since the first time.

**Comment by kburtram** [comment]
Closing older issues without a recent repro on current builds.  Please let us know if you're still being impacted by this issue.  Thanks!
