### ISSUE TITLE
PowerShell notebook cell stop button hangs

### ISSUE THREAD

**Issue by codykonior** [microsoft/azuredatastudio#14067]
Issue Type: <b>Bug</b>

Create a single code cell:

```
Start-Sleep -Seconds 5
Write-Host "Done"
```

Click the play icon and it will wait 5 seconds then display done.

If you click the play icon again followed by the stop icon, it will stay on the stop icon and never complete. You can no longer run this cell or any other cells in the notebook until restarting ADS.

![image](https://user-images.githubusercontent.com/12396330/105959460-dfccfe00-60b6-11eb-8155-6de9f5d1014b.png)

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:52:13.492Z)
OS version: Windows_NT x64 10.0.17763

Extensions: none

**Comment by chlafreniere** [comment]
@VasuBhog can you take a look please?

**Comment by VasuBhog** [comment]
@codykonior can you please tell me which version of the powershell kernel. You can find this via the Package Manager in Notebooks (shown below).

![image](https://user-images.githubusercontent.com/23587151/106059980-57476100-60a8-11eb-8783-21b3c0b62571.png)

**Comment by codykonior** [comment]
Hi, I haven't been able to find any way to get to a package manager. It doesn't show in the fast > menu, it's not on the sidebar, it's not in the title bar menus. I also Google'd azure data studio and "package manager" and nothing came up.

**Comment by codykonior** [comment]
Found it! 0.1.4.

**Comment by chlafreniere** [comment]
May be similar root cause to https://github.com/microsoft/azuredatastudio/issues/6251

**Comment by VasuBhog** [comment]
Hey @codykonior, seems this issue is only on Windows as far as my testing has been. I will be working on updating the PowerShell kernel to fix this issue. The issue does revolve around the PowerShell version you may have installed on your windows. 
If you download the newest version of Powershell located [here](https://github.com/PowerShell/PowerShell/tree/master/docs/learning-powershell) the issue should not be there anymore.

**Comment by codykonior** [comment]
Hi, yes it’s Windows and PS 5.1, and I’ll remember to mention that next time thanks. 

I won’t be using PowerShell Core for a bunch of reasons but look forward to your fix. Thanks.

**Comment by VasuBhog** [comment]
See comment here: https://github.com/microsoft/azuredatastudio/issues/14065
