### ISSUE TITLE
PowerShell notebook cell output randomly includes wrapper code

### ISSUE THREAD

**Issue by codykonior** [microsoft/azuredatastudio#14066]
Issue Type: <b>Bug</b>

Create a single code cell:

```
Write-Host "First cell"
```

Click the play button on the cell a few times. It's possible for it to randomly return one of three options:
- (Nothing)
- "First cell"
- Part of the script wrapper

```
. {
>> Write-Host "First cell"
>> }
>> 
First cell
```

![image](https://user-images.githubusercontent.com/12396330/105959133-7e0c9400-60b6-11eb-97d7-8100f2220078.png)

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:52:13.492Z)
OS version: Windows_NT x64 10.0.17763

Extensions: none

**Comment by chlafreniere** [comment]
@VasuBhog we already have an issue tracking this, correct?
