### ISSUE TITLE
Import Flat File Wizard Window is Blank

### ISSUE THREAD

**Issue by ckas28** [microsoft/azuredatastudio#14072]
Issue Type: <b>Bug</b>

 I installed the Admin Pack for SQL Server and enabled it. 
When I right click or press ctrl+I to open Import Wizard, the Import Flat File Wizard window will open but will be blank other than "Step 1 Specify Input File". There is nothing else in the window including no input boxes.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![image](https://user-images.githubusercontent.com/78105286/106039062-82708700-608d-11eb-808a-078a63a5c5b7.png)

**Comment by kburtram** [comment]
@aasimkhan30 could you try to determine what is happening here?

**Comment by aasimkhan30** [comment]
@ckas28, You seem to be using a very old version of Azure Data Studio. Can you please update your ADS to the latest version?

**Comment by kburtram** [comment]
Closing based on previous comment.  Please trying updating to latest versions and let us know if the issue persists.
