### ISSUE TITLE
Syntax Highlighting Error COUNT(*)

### ISSUE THREAD

**Issue by Kellett** [microsoft/azuredatastudio#14070]
- Azure Data Studio Version: 
Version: 1.25.2 (system setup)
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:52:13.492Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

---

- Steps to Reproduce:

1. Open a query window
2. Enter the following 
```
SELECT COUNT(*) FROM sys.tables  --sys.tables just used as an example.
```

3. The syntax highlighting will make the first bracket red
4. This doesn't seem to happen with other characters
---

- Screenshot of issue:
![image](https://user-images.githubusercontent.com/1553850/106008982-c4aac000-60af-11eb-9271-1fb98b17ccf7.png)

**Comment by Charles-Gagnon** [comment]
What color theme is this? I'm trying with the Monokai theme (which you appear to be using) and it looks fine on my end : 

![image](https://user-images.githubusercontent.com/28519865/106036036-a336dd80-6089-11eb-9a18-fecf4a343d5c.png)

Might try uninstalling and reinstalling - it's possible the colorization files got messed up in an update or something.

**Comment by Kellett** [comment]
Uninstalled, reinstalled. Still having the issue

**Comment by Charles-Gagnon** [comment]
I'm going to close this since we haven't seen any other reports of this happening. If you're still seeing this can you verify that you see this with the Monokai theme? Does this also look incorrect in other color themes?
