### ISSUE TITLE
You must enable preview features in order to use restore

### ISSUE THREAD

**Issue by jekon29** [microsoft/azuredatastudio#14081]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kburtram** [comment]
@jekon29 thanks for reporting this issue.  Currently the Restore feature is still in preview, so this is the expected behavior.  We are planning the remaining work to move this feature out of preview.
