### ISSUE TITLE
Error in Arc deployment notebooks - undefined variables

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio#14092]
@nasc17 and I are getting this error in the deployment notebooks for SQL MI and Postgres on Arc.

- ... -> New Deployment
- Choose Azure SQL MI Arc or Postgres Hyperscale Arc
- Fill in options
- Click deploy

![image](https://user-images.githubusercontent.com/3500406/106178626-dbecba80-614e-11eb-90b0-e3cc0013cf53.png)

If I comment out the offending line, controller_kubectl_context is not defined either:

![image](https://user-images.githubusercontent.com/3500406/106178691-f2931180-614e-11eb-9561-25ed7d2177a3.png)

Azure Arc extension 0.7.0
Azure Data CLI extension 0.5.0

Version: 1.26.0-insider
Commit: 8651db1e7edfe83452c01c6aeb4cfe6d20baabfa
Date: 2021-01-28T07:00:09.975Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Charles-Gagnon** [comment]
This is probably caused by insiders being ahead of the current extension version in the marketplace - I updated the extension and no longer get this error. @bergeron @nasc17 Could you update to the latest version and give it a shot?

**Comment by nasc17** [comment]
Updating the extensions and did not see the error.

**Comment by bergeron** [comment]
I updated the extensions and no longer get the error.  I'll close the bug.
