### ISSUE TITLE
Error creating Ubuntu 20 build container

### ISSUE THREAD

**Issue by MHacker9404** [microsoft/azuredatastudio#14094]
- Azure Data Studio Version: 1.25.2

Steps to Reproduce:

1. Using mcr.microsoft.com/dotnet/sdk:latest as base image
2. wget -nv -O azuredatastudio.deb "https://go.microsoft.com/fwlink/?linkid=2151506"
3. dpkg -i azuredatastudio.deb
4. azuredatastudio --install-extension microsoft.admin-pack --user-data-dir='.' 

results in: 
`/usr/share/azuredatastudio/bin/../azuredatastudio: error while loading shared libraries: libX11-xcb.so.1: cannot open shared object file: No such file or directory`

**Comment by alanrenmsft** [comment]
@MHacker9404 are you able to start azuredatastudio? I am trying to understand whether the error is related to install-extension.

**Comment by MHacker9404** [comment]
Within the ubuntu container that I'm trying to create? Trying to manually run ADS gives me the same exact error as above.
All I'm trying to do is a create a custom image that can be used for my build processes - I don't need to run ADS in an interactive mode in the container.  That's on my desktops...

**Comment by alanrenmsft** [comment]
thanks, in that case it is not related to install extension, I will put it under the correct area path. 
A couple more questions:
1. Did this ever work before?
2. since you said you don't need to run ADS in interactive mode, I am curious how are you planning to use the custom image with azuredatastudio?

**Comment by MHacker9404** [comment]
So this works with the AWS CodeBuild Ubuntu image to build an sqlproj as part of the buildspec.yaml.  But there were intermittent failures on loading the extensions, which is why I'm going down the road with the custom-image, so everything is already installed.  (Plus - it speeds up build times).
The interactive sessions woud be my developers using ADS on their local workstations....I just need the build capability.
I found the dockerfiles that Amazon uses to create their images - so I may start with that, and add to it....

**Comment by alanrenmsft** [comment]
If you only need the build capability you might not need ads. 
@udeeshagautam @kisantia what is the easiest way to build a .sqlproj on Linux?

**Comment by MHacker9404** [comment]
I wish - I've tried the [MSBuild.Sdk](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj), but having issues with the master.dacpac reference - which I need for a view in my database.
ADS builds the whole thing fine - but the buildspec is not stable enough - so I go the custom image route 😄

**Comment by kburtram** [comment]
@MHacker9404 you may look at how we create our Linux Integration Test images https://github.com/microsoft/azuredatastudio/blob/main/build/azure-pipelines/linux/Dockerfile.  This has some `apt install` commands and the xvfb config steps to run ADS headless.

**Comment by MHacker9404** [comment]
Will do - thank you muchly....

**Comment by dzsquared** [comment]
@MHacker9404 - if you're looking to build a sqlproj from Linux, you may find this info helpful: https://docs.microsoft.com/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line
It lays out which files to grab from an ADS install to build from the command line - only prerequisite then is the .NET Core SDK.

**Comment by kburtram** [comment]
I close this issue based on the above discussion.  I think some of the commands in the linked docker file could make ADS work on the build container, but likely @dzsquared's suggestion to pull out the required build tools makes more sense for CI pipeline.  Please let us know if there's anything else we can assist with here.
