### ISSUE TITLE
Can't signin with Azure AD

### ISSUE THREAD

**Issue by empz** [microsoft/azuredatastudio#14108]
Issue Type: <b>Bug</b>

After signin in with Azure AD I can't see anything. When trying to switch the subscription I get the following error:

> Error running command azure.resource.selectsubscriptions: Failed to get credential for account Emiliano Parizzi - emiliano.parizzi@mydomain.com. Please refresh the account.. This is likely caused by the extension that contributes azure.resource.selectsubscriptions.

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:52:13.492Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (18.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
kusto|Mic|0.4.0
profiler|Mic|0.11.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@ChrisSun-ms any ideas how we could troubleshoot this issue?

@empz is there a link to refresh the account credentials in the Accounts Dialog?  It sounds like there may be some invalid cached state for this account.  Was this the first time you tried adding this account?

**Comment by empz** [comment]
Tried refreshing, removing and re-adding the account. Used to work a while
ago, but haven't used it for a while. Now it won't no matter what I try.

**Comment by cssuh** [comment]
https://github.com/microsoft/azuredatastudio/issues/12637#issuecomment-754116948
can you please try this method of re-adding your account?

**Comment by empz** [comment]
I actually just had to do a clean install of Windows for other reasons and I can no longer reproduce this issue. 
It's working fine. Closing.
