### ISSUE TITLE
Close jupyter notebook command does not work in notebooks within a book.

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#14116]
The close jupyter notebook command does not work in notebooks within a book.
- Azure Data Studio Version:
Version: 1.25.2
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:47:41.882Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.2.0
Steps to Reproduce:

1. Open a book, right click "Close Jupyter Notebook".
2. It doesn't do anything.

Feature request: 
Replace command for remove notebook which removes the notebook from the toc.yml.

**Comment by chlafreniere** [comment]
@barbaravaldez can I assume that this isn't new behavior?

**Comment by barbaravaldez** [comment]
> @barbaravaldez can I assume that this isn't new behavior?

It's not new.
