### ISSUE TITLE
Failed to start profiler - Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.

### ISSUE THREAD

**Issue by kraay** [microsoft/azuredatastudio#14122]
- Azure Data Studio Version: 1.25.2

Steps to Reproduce:

1. Connect to server.
2. Go to database
3. Press Alt + P

Error: Failed to start session: An exception occurred while executing a Transact-SQL statement or batch.

![image](https://user-images.githubusercontent.com/10906811/106377528-9f75c480-63c3-11eb-8deb-76dae4a28f1b.png)

It is failing for this server, but working for another server I connect to.

**Comment by kraay** [comment]
I tried the workaround shared in https://github.com/microsoft/azuredatastudio/issues/6353. I ran the script on the server and tried starting the profiler again in Azure Data Studio, but it failed with the same issue.

**Comment by kburtram** [comment]
@kraay do you see any error message in the "Help->Toggle Developer Tools" Console log?

**Comment by kburtram** [comment]
I wasn't able to repro this with the latest build/extension.  Please add additional context to the issue, such as error logs etc., if you are still experiencing this problem.  Thanks!
