### ISSUE TITLE
SQL Connection - Database Dashboard Widgets not Working

### ISSUE THREAD

**Issue by janszedc** [microsoft/azuredatastudio#14126]
After updating to the latest release of ADS, the database dashboard widgets no longer populate with data.  This includes third party extensions such as sp_WhoIsActive.  This issue also occurred for others on my team.

![image](https://user-images.githubusercontent.com/49908138/106462386-021e9d00-6464-11eb-9531-997e7ceb49d1.png)

**Comment by kburtram** [comment]
@janszedc the current ADS version is 1.25.2.  Have you tried this scenario with the latest version (screenshot shows version 1.15.0)?

**Comment by janszedc** [comment]
For some reason I think my ADS keeps downgrading itself. The notification
to check for updates continually pops up saying new updates are available
no matter how many times I run it. Eventually it will say no updates are
available, but when I restart it pops back up.

I wonder if some group policy or security firewall is blocking the install
and silently continuing? I will have to look tomorrow.

**Comment by kburtram** [comment]
@janszedc that's strange behavior with the upgrade.  It's not a good long-term solution, but you can find the direct links to download the latest version from the project README.

**Comment by kburtram** [comment]
@janszedc please let us know if this issue is occurring on the latest ADS build.  If you are still experiencing auto-upgrade problems, please open a separate bug for that.  Thanks!

**Comment by janszedc** [comment]
@kburtram This issue is still occurring in the latest build of ADS 1.27.0 as well as version 1.26.1.  

The auto-updating is still a problem, but I have not opened a separate issue for that.  I was able to temporarily work around that by doing a fresh install like you recommended.
