### ISSUE TITLE
Adding a connection resets zoom level

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#14128]
Issue Type: <b>Bug</b>

Adding a new connection resets the zoom level of the environment, similar to https://github.com/microsoft/azuredatastudio/issues/12328

In this gif it's going from an extreme zoom in to an extreme zoom out

![Azure Data Studio - Resize when adding connections](https://user-images.githubusercontent.com/8250560/106499708-c12f8400-6475-11eb-9ec6-35c35afd4dc9.gif)

Note that if you open the bug submission dialog it remains at the previous zoom in level though the rest of the app shows zoomed out

![image](https://user-images.githubusercontent.com/8250560/106499441-757cda80-6475-11eb-93ff-1c12bf32f1e4.png)

Azure Data Studio version: azuredatastudio-insiders 1.26.0-insider (8651db1e7edfe83452c01c6aeb4cfe6d20baabfa, 2021-01-28T07:00:09.975Z)
OS version: Windows_NT x64 10.0.19042

**Comment by dzsquared** [comment]
I also see a similar (yet not quite as intense) change in zoom level.  Whenever I close or open a workspace, the zoom level returns to a slightly zoomed in state.

In the gif below, I close a workspace and the zoom level remains the same.
Then - I reset the zoom level and when I open a workspace the zoom level increases.
Repeat reseting the zoom level and closing the workspace, zoom level increases back.
![zoom-change](https://user-images.githubusercontent.com/12227241/118710820-ac33f200-b7d3-11eb-86cf-f2e96c9af3ed.gif)

**Comment by albegouws** [comment]
Knowing there is a huge backlog, this would be a nice quality of life bugfix...

**Comment by AndrewBorst** [comment]
Can we generalize the title of this issue? The zoom reset occurs on other operations in Azure Data Studio (ie. Manage) and it is hard to find this issue under open issues.

**Comment by alanrenmsft** [comment]
investigated into this a little bit, and found out that the zoom level in the electron app is updated without going through the ADS's zoom update code path. have to debug Electron to find out who is setting it.

**Comment by dzsquared** [comment]
Opening server dashboard is reseting zoom
![2022-04-27_13-00-38 (1)](https://user-images.githubusercontent.com/12227241/165621457-8290a293-8271-4b51-bba0-3cff08d39ee3.gif)

**Comment by alanrenmsft** [comment]
I've implemented a workaround in ADS for this issue: 
![zoom-after](https://user-images.githubusercontent.com/13777222/171299585-a59d3e7a-5c73-45a8-b5b7-2913b977c830.gif)
