### ISSUE TITLE
replace the save/restore cache tasks with ADO's own cache task

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14149]
the save/restore cache tasks will fail occasionally and they are no longer being maintained, but the ADO's Cache task only support one folder, I've opened a feature request: https://developercommunity.visualstudio.com/idea/1324372/support-multiple-folders-in-ado-cache-task.html

we should do the replacement once the request is completed, or we can do our own processing under the restriction of one folder.

**Comment by Charles-Gagnon** [comment]
Could we not have multiple cache tasks - one for each folder?

**Comment by alanrenmsft** [comment]
if we do that we will need to configure at least 1+x (number of extensions) tasks, and when new extensions are added the build yaml also needs to be updated. doesn't seem to be a good solution to me.
