### ISSUE TITLE
ADS fails to get credentials for an azure account

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#14165]
- Azure Data Studio Version: 1.25.2
Steps to Reproduce:

1. Add an azure account in ADS
2. Open the account in data explorer. 

![image](https://user-images.githubusercontent.com/6816294/106967311-cdc50e00-66fb-11eb-9d3d-42358462f9a1.png)

**Comment by abist** [comment]
@aasimkhan30 Could you please use the template to include the ADS version in the issue as well

**Comment by Charles-Gagnon** [comment]
@rajeshsetlem The error states `The user account is disabled` - have you confirmed that the account you're attempting to use is indeed active?

**Comment by rajeshsetlem** [comment]
@Charles-Gagnon The account is active in my AAD home organization. But since I got added to other AAD tenants, my account is locked out in one of them and ADS should ideally have improved exception handling.

**Comment by kenvanhyning** [comment]
Moving tenant related work to May.  Too large of a change to add for ask mode.

**Comment by cssuh** [comment]
We have since fixed the tenant fetching logic, so closing this.
