### ISSUE TITLE
Toolbar Container needs more top/bottom padding

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#14199]
The toolbar container across the dashboards could use more top/bottom padding for the buttons found within it. 

Comparison to toolbar in Portal:
<img width="400" alt="toolbaragain" src="https://user-images.githubusercontent.com/69922333/107265567-4af0cb80-69f9-11eb-9362-e1daa7821ffa.PNG">

**Comment by alanrenmsft** [comment]
I fixed this in https://github.com/microsoft/azuredatastudio/pull/14188
