### ISSUE TITLE
Script view as Create/Alter not working

### ISSUE THREAD

**Issue by ursu123** [microsoft/azuredatastudio#14211]
Issue Type: <b>Bug</b>

When I click Script view/table as Create/Alter I get this error and nothing happens:

Error running command dataExplorer.scriptAsCreate: undefined. This is likely caused by the extension that contributes dataExplorer.scriptAsCreate.

Azure Data Studio version: azuredatastudio 1.25.2 (4d4917d328ab7a7526817a0f0ef03237a79aa54d, 2021-01-20T22:47:41.882Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 4|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
sql-database-projects|Mic|0.5.1
azdata-sanddance|msr|3.1.0

</details>

**Comment by ursu123** [comment]
[20210209T201209.zip](https://github.com/microsoft/azuredatastudio/files/5954034/20210209T201209.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/5954035/console.log)

**Comment by kburtram** [comment]
@abist could you please try to determine what's happening here?

**Comment by kenvanhyning** [comment]
Holding this for April askmode since it was postponed in March.  Need to verify if this is actionable this week.

**Comment by abist** [comment]
@ursu123 I wasn't able to repro this issue. Could you specify what kind of server and database you're connected to?

**Comment by abist** [comment]
@ursu123 I noticed in the logs you provided that there's a login error right before the scriptAsCreate error:

```
​  INFO Creating new connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:database|server:server|user:username|databaseDisplayName:database|group:
​  INFO Adding connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:database|server:server|user:username|databaseDisplayName:database|group:
​  INFO Successfully added connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:database|server:server|user:username|databaseDisplayName:database|group:
​  INFO Deleting connection connection:providerName:MSSQL|applicationName:azdata|authenticationType:SqlLogin|database:database|server:server|user:username|databaseDisplayName:database|group:
​   ERR Login failed for user 'username'.
​ Error running command dataExplorer.scriptAsCreate: undefined. This is likely caused by the extension that contributes dataExplorer.scriptAsCreate.
onDidChangeNotification @ ​
​   ERR An unknown error occurred. Please consult the log for more details.
​   ERR Login failed for user 'username'.
```
Is the connection being made with the correct credentials?

**Comment by kburtram** [comment]
Closing this based on the previous comment.  It looks like the connection is failing to login into the server.  Please try removing and readding the connection.  Please let us know if you're still impacted by this issue.  Thanks!
