### ISSUE TITLE
TreeComponent collapses after backward wizard navigation

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#14221]
- Azure Data Studio Version: 1.26.0-insider (user setup)
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125

Steps to Reproduce:

1. In the extensions sample, update `mainController.ts` to render `TreeComponent` in a wizard, rather than a dialog by changing [line 529](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/samples/sqlservices/src/controllers/mainController.ts#L529) to:
```typescript
await this.getTab3Content(view);
```
2. Build the extension and install it in ADS
3. Run `sqlservices.openWizard` command, you should see a tree view:
![image](https://user-images.githubusercontent.com/11728682/107448328-50800b80-6af6-11eb-82ae-7ebb8e6d4427.png)
4. Navigate to the next page by pressing `Next` button and then navigate back by pressing `Previous` button - the tree view is collapsed to single row:
![image](https://user-images.githubusercontent.com/11728682/107448393-73122480-6af6-11eb-922a-501de8d69ea4.png)

**Expected behavior:**
Tree view should respect its set dimensions.

**Comment by alanrenmsft** [comment]
I am working on these issues this week. @nahk-ivanov
