### ISSUE TITLE
WizardComponent does not refresh buttons state when set from TreeComponent change handler

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#14226]
- Azure Data Studio Version: 1.26.0-insider (user setup)
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125

Steps to Reproduce:

1. In the extensions sample, update `mainController.ts` to accept `Next` button in `getTab3Content`, by changing [line 83](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/samples/sqlservices/src/controllers/mainController.ts#L83) to:
```typescript
private async getTab3Content(view: azdata.ModelView, nextButton?: azdata.window.Button): Promise<void> {
```
2. Also change `onNodeCheckedChanged` handler to disable the next button, by adding the following line after [line 130](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/samples/sqlservices/src/controllers/mainController.ts#L130):
```typescript
nextButton.enabled = false;
```
3. Finally render `TreeComponent` in a wizard, rather than a dialog by changing [line 529](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/samples/sqlservices/src/controllers/mainController.ts#L529) to:
```typescript
await this.getTab3Content(view, wizard.nextButton);
```
4. Build the extension and install it in ADS
5. Run `sqlservices.openWizard` command, you should see a tree view and `Next` button enabled:
![image](https://user-images.githubusercontent.com/11728682/107453310-955c7000-6aff-11eb-934b-65189ec65e92.png)
6. Uncheck node 12 - the `Next` button is still enabled (**Expected behavior**: next button should be disabled)
![image](https://user-images.githubusercontent.com/11728682/107453331-a0170500-6aff-11eb-942b-13f79d2197a7.png)
7. Click `Next` button to navigate to the next page and then click `Previous` button to navigate back to the first page.
![image](https://user-images.githubusercontent.com/11728682/107453377-b6bd5c00-6aff-11eb-9385-71afee9cbe9a.png)
8. `Next` button is now disabled

**Expected behavior**
Button state should be updated when `enabled` property changes during step 6.

I hit this when trying to implement custom validation for the tree control - depending on the selected nodes we would like to allow/disallow user to proceed in the wizard. Standard validation for the `TreeComponent` does not seem to have a way to validate the selection, so I was trying to roll out my own solution. Ideally it would be nice to extend validation feature for the `TreeComponent` to allow a delegate that is called on check state changes and returns true/false, but if we can at least fix this issue - that would be a workaround in the interim.

**Comment by alanrenmsft** [comment]
the state of the the following three buttons are controlled by the wizard itself: next, previous, done. extensions are supposed to leverage the page validation to control the enabled state of them. I tried the following code in the sqlservices extensions on top of your changes. around line 124 in maincontroller.ts

```
		let checkedItems = []; // track the checked tree items
		let tree: azdata.TreeComponent<TreeNode> = view.modelBuilder.tree<TreeNode>().withProperties({
			'withCheckbox': true
		}).withValidation(() => { // use withValidation to control the state of the next button.
			return checkedItems.length === 1;
		}).component();
		let treeView = tree.registerDataProvider(treeDataProvider);

		treeView.onNodeCheckedChanged(item => {
			checkedItems.push(item); // updated the checkedItems array.
			tree.validate(); // run the validation to refresh the validity state of the page
			if (item && item.element) {
				item.element.changeNodeCheckedState(item.checked);
			}
		});
```

you can use this or the navigation validator we chatted about today. let me know.


![wizard-nav](https://user-images.githubusercontent.com/13777222/108141469-a0bc1800-7078-11eb-9a1a-a43778d8eabf.gif)

**Comment by alanrenmsft** [comment]
forgot to tag you @nahk-ivanov

**Comment by alanrenmsft** [comment]
please reactivate if you are having issue with the solution I provided.
