### ISSUE TITLE
TreeComponent fails to handle node state change when azdata.TreeComponentItem defines an id

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#14229]
- Azure Data Studio Version: 1.26.0-insider (user setup)
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125

There are actually two issues for the price of one! :)

Steps to Reproduce:

1. In the extensions sample, update `treeDataProvider.ts` to populate `id` property of the `TreeComponentItem`s that it returns by adding the following line after [line 273](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/samples/sqlservices/src/controllers/treeDataProvider.ts#L273):
```typescript
item.id = element.id;
```
2. Build extension and install it in ADS
3. Run `sqlservices.openDialog` command and navigate to the "Test tab3", you should see a tree view:
4. Check node `112`, the error shows in the console:
```
ERR Cannot read property 'error' of undefined: TypeError: Cannot read property 'error' of undefined
    at file:///C:/Users/user/AppData/Local/Programs/Azure Data Studio - Insiders/resources/app/out/vs/workbench/workbench.desktop.main.js:5988:774
```
This comes from the [mainThreadTreeViews.ts](https://github.com/microsoft/azuredatastudio/blob/9fdb5037bc37fb4c0d034669153644172c2ba182/src/vs/workbench/api/browser/mainThreadTreeViews.ts#L190), where `this.notificationService` is `undefined`. This obviously masks the actual error so needs to be fixed first.

Once you fix this issue, you will get the actual error:
```
Element with id <xyz> is already registered
    at createAndRegisterTreeNode (c:\Users\user\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:681:840)
    at c:\Users\user\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:680:542
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async Promise.all (index 0)
```
This comes from the [extHostTreeViews.ts](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/src/vs/workbench/api/common/extHostTreeViews.ts#L573). Seems like `elements` cache is not being properly cleaned up on [line 457](https://github.com/microsoft/azuredatastudio/blob/ce612a3d9613a1857772150892e5f9abe1dd44f7/src/vs/workbench/api/common/extHostTreeViews.ts#L457) before the refresh.

I don't really know if this `id` is supposed to be used. Per documentation, it is supposed to be a unique identifier of the node (which it is in the sample code) and is used to track the item state. While we can probably live without this feature, my worry is that when `id` is not provided - it generates (random?) one automatically, so it might be that those are not cleaned up either during refresh and just dangle there forever.

**Comment by alanrenmsft** [comment]
I am not able to reproduce the issue anymore, I tried local dev instance as well as the latest insider build, could you please give it another try?

**Comment by alanrenmsft** [comment]
please reactive if you are still seeing the issue.

**Comment by nahk-ivanov** [comment]
Just updated to latest insider build:
  Version: 1.27.0-insider (user setup)
  Commit: 87a9ae0975d89222b41d2c804eff2500fe61d8a7

and the issue is still present. It is actually very interesting - the error happens when you check node `112`, but does not happen when you check/uncheck leaf `12` node, which makes me think more and more that it is a bug and not an expected behavior.

![image](https://user-images.githubusercontent.com/11728682/108405534-08d44080-71d6-11eb-87ef-7cd6f66ac17a.png)
