### ISSUE TITLE
Dialog tab should not be created if it doesn't register with modelviewProvider

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#1423]
Create dialog tab without registering tab with modelviewProvider

Expect: It should show error or tab should not be created.

Actual: It creates an empty tab
![image](https://user-images.githubusercontent.com/25463959/40074587-d27ab8fc-582e-11e8-8596-d58c8c1b475b.png)

**Comment by MattIrv** [comment]
I guess we could throw an error here so that the user knows they're doing something wrong but the current behavior doesn't really seem like a bug to me

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if this problem persists.
