### ISSUE TITLE
Cross-referencing standards in Jupyter Notebooks

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14247]
- Azure Data Studio Version:
Version: 1.26.0-insider (user setup)
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125
Date: 2021-02-08T06:39:21.221Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Steps to Reproduce:**

Given the following markdown:
`## **1. Searching / navigating files**`

My research shows three different formats for cross-referencing: 
	
1. ADS == DocFX / enghub markdown == Github Markdown -> this works with the following cross-referencing format:
	`#1-searching--navigating-files`

2. Binder = Jupyter Notebook -> this works with the following cross-referencing format:
	`#1.-Searching-/-navigating-files`
	
3. VSCode and ADO Jupyter Renderer support this:
	`#-1-searching-navigating-files-` 

GitHub Jupyter Notebook viewer does not seem to support any cross-referencing formats tried above.

**Comment by barbaravaldez** [comment]
@chlafreniere, this probably won't make for March so I'll be moving this to April.

**Comment by chlafreniere** [comment]
Talked about this with @MsSQLGirl and since this isn't blocking OneNote adoption (or causing customer dissat at the moment -- this item tracks an item that would prevent future issues with notebook interop), moving down to Pri 2.

**Comment by chlafreniere** [comment]
Deep linking scenarios have since been documented internally. Closing as a result.
