### ISSUE TITLE
Search results are confusing when pinned Notebook's book is opened in Book Tree View

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#14259]
Having the book of a pinned notebook opened in the Books View will divide the results in two nodes (the directory of the pinned notebook and the book's root)
![Screen Shot 2021-02-11 at 10 38 47 AM](https://user-images.githubusercontent.com/34872381/107682568-57716000-6c55-11eb-8044-a8435ed11924.png)

- Azure Data Studio Version:
Version: 1.26.0-rc1
Commit: 06bace1fcf7ec79b3f2df8588400f56b54476125
Date: 2021-02-08T08:33:58.217Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0

Steps to Reproduce:
1.Open a book and pin a notebook from the same book.
2. Search for a term that appears in multiple sections of the book as well the newly pinned notebook.
3. The search results will be divided in two nodes.

**Comment by aasimkhan30** [comment]
@barbaravaldez assigning this issue to you. In the future, please assign all the ask mode issues. Thanks!
