### ISSUE TITLE
Using $ in ADS works (but not Jupyter Notebook?)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14260]
- Azure Data Studio Version:
Version: 1.26.0-insider (user setup)
Commit: e4c5af266399991296e538d3428906e9dd918cbf
Date: 2021-02-11T07:01:41.112Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Source file is here: https://gist.github.com/MsSQLGirl/2be8583c80221d2ef761926a6610e266

> This is a question on compatibility.

Raw: 
```
#### Additional useful markers:  

While these tags work in Azure Data Studio, some other Jupyter Notebook viewers may not display them properly. 

| html tag | what it looks like |
| -- | -- |
| `<u>underline</u>`  | <u>underline</u> |
| `<mark>highlight</mark>` | <mark>highlight</mark>|


#### Table creation
This is a table example when using markdown. 
> **Tip**: Only two dashes ( `--` ) are needed to form a table. 

Will look like this:

| Tables   |      Are      |  Cool |
|----------|:-------------:|------:|
| col 1 is |  left-aligned | $1600 |
| col 2 is |    centered   |   $12 |
| col 3 is | right-aligned |    $1 |

```

Jupyter Notebook:
![image](https://user-images.githubusercontent.com/6405919/107682439-33158380-6c55-11eb-9b2d-fbd10c02594d.png)

ADS:
![image](https://user-images.githubusercontent.com/6405919/107682553-52acac00-6c55-11eb-8998-5a571d65ab6b.png)

VSCode:
![image](https://user-images.githubusercontent.com/6405919/107684235-62c58b00-6c57-11eb-8cee-39aa616f1e97.png)

I'm not sure what the expected outcome should be.

**Comment by chlafreniere** [comment]
Please see https://github.com/jupyter/notebook/issues/1183 for context.

**Comment by MsSQLGirl** [comment]
Ok. I guess for now we can close this with "\" to escape $ :)
Thoughts?

**Comment by chlafreniere** [comment]
Agreed. Feel free to reactivate if you encounter further problems.
