### ISSUE TITLE
Restore dialog doesn't select correct database on open + UI flashing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14282]
RC1

Previous behavior was that when you right clicked on a database and selected `Restore` it would open the restore dialog with that database selected from the list of database backups. This is no longer happening - it's selecting the first one in the list instead.

There also appears to be other UI related issues - selected various options is resulting in lots of values flashing in and out.

**Comment by Charles-Gagnon** [comment]
@udeeshagautam Did you not see these when you were doing signoff testing?

**Comment by kisantia** [comment]
this sounds similar to this issue in the dacpac extension #14213 where the first database in the list is selected instead of the database that was right clicked to launch the dialog

**Comment by udeeshagautam** [comment]
Confirmed that it is flashing for right click (not for other launch points - not sure why)

**Comment by kburtram** [comment]
@udeeshagautam I've ported your fix to release/1.26.
