### ISSUE TITLE
not able to close Profiler editor

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14291]
when the session is not stopped, user is not able to close the profiler window, and the message is irrelevant.
![image](https://user-images.githubusercontent.com/13777222/107838698-e2d51900-6d5b-11eb-9962-fa62e03426c6.png)

**Comment by kburtram** [comment]
@alanrenmsft is this impacting the 1.26 (Feb) release?  Or a recent regression?
