### ISSUE TITLE
No keyboard shortcut support

### ISSUE THREAD

**Issue by akselsoft** [microsoft/azuredatastudio#14305]
Issue Type: <b>Bug</b>

I clicked the close on a tab and was prompted with the "Save or Don't Save" dialog. I attempted to use Tab OR arrow keys to move to the Don't Save. 

I then tried Ctrl or Alt or anything. NO keybaord shortcut worked to respond to the dialog.

Very frustrating

Azure Data Studio version: azuredatastudio 1.25.3 (b277eafb8f5328ea26c6edfddd1999292ac27937, 2021-02-09T23:17:41.828Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-wakatime|Wak|4.0.0

</details>

**Comment by cssuh** [comment]
This is expected behavior and is in line with what vscode does.
