### ISSUE TITLE
A11y_AzureDataStudioSQL_Project_Database_CreateProjectFromDatabase_Keyboard: Keyboard focus is moving outside of the "Create Project From Database" pane after hitting shift + tab key.

### ISSUE THREAD

**Issue by Shivamd1** [microsoft/azuredatastudio#14317]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudioSQL_Feb2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.3;#Keyboard;#FTP;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Database Project and install extension SQL Database Projects.
2. Tab till SQL Database Project Home Screen with heading "Projects".
3. Tab to connections select your server and connect to it.
4. Few databases will appear under your connection then press shift+f1 on any database
5. Tab till "Create project from database" and hit enter.
6. Tab to the "Select connection" button under "Source database" title and press shift + tab key.
7. Check if focus is moving outside of the pane

### Actual:
Keyboard focus is moving outside of the "Create Project From Database" pane after hitting shift + tab key.

Same issue is observed in below screen:

1. data tier application

### Expected:
Keyboard focus should not go outside of the "Create Project From Database" pane after hitting shift + tab key.

### User Impact:
Keyboard only users will face difficulty in navigating again in the pane.

**Comment by Roopesh-T** [comment]
Issue is not repro in env so closing the bug,
![image](https://user-images.githubusercontent.com/86601127/219016477-6564fc92-7824-441c-817b-0c28ee705ed1.png)
![14317_Clsoed](https://user-images.githubusercontent.com/86601127/219016529-1a5aadc0-30b9-4886-ad3c-90d6e5062abd.gif)

**GitHub Tag**:#Closed;
