### ISSUE TITLE
A11y_AzureDataStudioSQL_Project_CreateProjectFromDatabase_Keyboard: Keyboard focus is getting trapped as it is not moving by hitting tab key when keyboard focus is on "cancel" button

### ISSUE THREAD

**Issue by Shivamd1** [microsoft/azuredatastudio#14318]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudioSQL_Feb2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.1.2;#Keyboard;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio
Windows Version: Windows10

### Repro Steps:

1. Launch the application-Azure Database Project and install extension SQL Database Projects.
2. Tab till SQL Database Project Home Screen with heading "Projects".
3. Tab to connections select your server and connect to it.
4. Few databases will appear under your connection then press shift+f10 on any database
5. Tab till "Create project from database" and hit enter.
6. Tab to the "Cancel" button and press tab key.
7. Check if focus is moving to next focusable control or not.

### Actual:
Keyboard focus is getting trapped as it is not moving to the next focusable control which is "Select connection" button by hitting tab key when keyboard focus is on "cancel" button.

### Expected:
Keyboard focus should go to the next focusable control which is "Select connection" button by hitting tab key

### User Impact:
Keyboard only users will face difficulty in navigating inside the pane.

**Comment by prabhudevu** [comment]
I have verified the issue in the latest build 1.42.0 issue is fixed hence closing the bug

![14138_fxed](https://user-images.githubusercontent.com/98821792/220099887-7dfe7dca-36bb-4fe1-b366-c620f4c34aaf.gif)

**GithubTags:**#Closed;#Regressed:02-20-23;
