### ISSUE TITLE
Adding project to temp workspace doesn't work

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#14310]
Steps to Reproduce:

1. Close any open workspace
2. Go to file -> Add a folder to the current workspace and add a folder. This will create an untitled workspace
3. Go to projects viewlet and add a new project. You can tell it's a temp workspace because the path to the workspace is just a number
![image](https://user-images.githubusercontent.com/31145923/108121907-56c33a00-7058-11eb-9207-4930668ccea3.png)

![image](https://user-images.githubusercontent.com/31145923/108121627-f7652a00-7057-11eb-9e64-48272b5887d7.png)

workaround is to save your workspace before trying to add a project. Potential fix is to detect if the workspace is a temp workspace and require the user to save before a project can be added.

**Comment by udeeshagautam** [comment]
@kisantia assigning to you, let's disuess this week. @dzsquared  FYI

**Comment by kisantia** [comment]
after some discussion, we should treat this like the "no workspace open" case. If there's a temp workspace open, have the "new workspace will be created text" and inputbox for the location with a default, save it before adding project to it.
