### ISSUE TITLE
Clicking on a notebook file from Search Results of Notebook viewlet should open the file and highlight the keyword

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14325]
**Is your feature request related to a problem? Please describe.**
When searching for a keyword in the Search pane of Notebook Viewlet, it will then display the notebooks containing the keyword. I click on the notebook file to open the file. 
Areas to improve: **I then have to click Ctrl + F and copy the keyword and paste it to the Find dialog (3 more steps).** 

**Describe the solution or feature you'd like**
1. When I click on the notebook file to open the file, it should automatically highlight the searched keyword (with Ctrl + F). 
2. It should also activate / highlight in the Notebook viewlet the notebook file that I just opened. -> This one is related to #12740 

**Describe alternatives you've considered**
For item 1, alternative is just using Ctrl + F (three steps)
For item 2, no alternative

**Additional context**

**Comment by radentonev** [comment]
I think the behavior after clicking on a result should be to open file + highlight search results, but no NOT show CTRL+F search box. After click on the notebook content, the highlights should be cleared. if the user wants to see the highlights again, they can once again click on the search results to display them.

Showing CTRL+F menu automatically seems a bit too too far, as I believe some users would not want to deal with closing that every time they don't need it. If the highlight is in place that should be enough for many use cases. However, if a user does want to go ahead and press CTRL+F (if highlight was not enough), then it should be auto-populated with the matched search string.

Thanks,
Raden.

**Comment by chlafreniere** [comment]
Initial implementation is in March. The question re: the find widget popping up will be post-March

**Comment by chlafreniere** [comment]
@MsSQLGirl since this has been implemented, this is no longer a Pri: 1, no?

**Comment by chlafreniere** [comment]
Given that this work is in, closing this tracking issue. Let's chat about what your concerns are, @radentonev. Would be great to get some user feedback here as well, and we can track that work item separately.
