### ISSUE TITLE
Editing Books: Throw error if section is not found when trying to update target book table of contents after git pull.

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#14322]
Throw error when section is not found, before attempting to modify the table of contents. If we do not check then we are only removing the section but never adding it again.
This issue only happens when the book view doesn't pick up the latest changes of table of contents. Like trying to pull changes on git and never reloading ADS. https://github.com/microsoft/azuredatastudio/issues/9249

- Azure Data Studio Version:
Version: 1.26.0-rc1
Commit: 0423480148eb7a993749587599a2e0e69947adba
Date: 2021-02-14T04:35:36.893Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0

**Comment by chlafreniere** [comment]
hey @barbaravaldez I just want to make sure I'm crystal clear on the repro here. Is the following correct?

- Open a book in ADS
- Alter some files outside of the book editing mechanism (e.g. either outside of ADS, git pull, etc.)
- (this part I'm not 100% clear on) Make an edit to the book in ADS
- Section will be gone

Can you help clarify?

**Comment by barbaravaldez** [comment]
> just want to make sure I'm crystal clear on the repro here. Is the following correct?

So, if there were some changes and the Book View does not reflect those. For instance a section that no longer in the table of contents, the quick pick will still show the the section because to the BookModel the section is still there.
So if I want to move a notebook/section to that section then it'll remove it from the source book toc but it won't add it to the target book because it'll never find that removed section. So for the user would think we only removed it from the table of contents of the source book.

**Comment by chlafreniere** [comment]
Chatted about this offline. Not a regression. Doesn't meet escrow bar, but good to fix in insiders and get in for March.
