### ISSUE TITLE
Query Tab database icon always show red even if connected

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/azuredatastudio#14321]
- Azure Data Studio Version: 1.25.3

Steps to Reproduce: 

1. Open a new query
2. Run any query
3. Icon is shown in red at all time

**Comment by kburtram** [comment]
@drizztdourden08 the red color of the query tab is no meant to convey connectivity state.  It is actually just the color vscode assigned to SQL files at some point, since they wanted to have different colors for different file types.  I'll pass your feedback to our UX team.  Thanks!

**Comment by drizztdourden08** [comment]
Wow. Yeah. Thanks for that. 

Very confusing. The tab can actually be disconnected and will show the "disconnected" writings. The color probably should reflect that state instead.
