### ISSUE TITLE
ADS crashes when chart button is clicked in the results pane

### ISSUE THREAD

**Issue by MatrixArchitect** [microsoft/azuredatastudio#14335]
Issue Type: <b>Bug</b>

1. Execute any query that returns tabular data
2. Click on the Chart button/icon to the right of the results pane
3. ADS pops up a a little window on bottom right saying it recommends installing some visualization extension and freezes. The buttons in the dialog box ("Install All" and "Show Recommendations") do not respond to mouse clicks. ADS becomes unresponsive to all user interaction. After a while another dialog pops up with options for "Reopen", "Keep Waiting" and "Close". (I do not see any recommended data visualization extensions in the extension list either.)

It has had this behavior out of the box. Installation and removal of any extensions have had no affect on this behavior.

Azure Data Studio version: azuredatastudio 1.25.3 (b277eafb8f5328ea26c6edfddd1999292ac27937, 2021-02-09T23:10:35.151Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1535M v6 @ 3.10GHz (4 x 3096)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|4.42GB (1.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.6.0
import|Mic|1.2.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.8.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.5.0
sql-database-projects|Mic|0.5.1
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@MatrixArchitect I wasn't able to repro this behavior.  Could you please see if there are any error logs in the Developer Tools Console following instructions above?  

The Show Recommendations button will prompt to install SandDance extension.  Likely if you install that extension it would avoid showing the prompt (as a temporary workaround to the crash).

**Comment by MatrixArchitect** [comment]
[exthost.log](https://github.com/microsoft/azuredatastudio/files/6007554/exthost.log)
[DeveloperTools.log](https://github.com/microsoft/azuredatastudio/files/6007555/DeveloperTools.log)

@kburtram Thank you. I have attached both the logs. I see in the Console that some js libraries failed to load. I also see a message about "whoisacitve" extension being unresponsive. However, I used to run into this issue even before I installed this extension yesterday. I am not sure why the js libraries are not loading? Could this be an installer issue where the installer doesn't install libraries properly? There are no *.map files in "file:///C:/Program%20Files/Azure%20Data%20Studio/resources/app/out/vs/code/electron-browser/workbench/" 

ADS was installed with all default options. I first noticed this in 1.24 and it continued even after upgrading to 1.25. 

The console log is from before the application froze. I am not sure if it includes historical data. (There are no timestamps.) However, the "preserve log" option is not checked in the console settings window. Let me know if you want to check "preserve log" and try to reproduce the issue and then capture the console logs.

Finally, I just installed the SandDance extension. After that when I clicked on the Chart button (not the visualization button added by SandDance) I didn't get the Show Recommendations dialog but the client area, including  menus and all other UI elements, froze again. The Developer Tools areas remains active. I didn't see any updates to the logs though.

Let me know if there's anything else I can do to assist with RCA.

**Comment by kburtram** [comment]
@MatrixArchitect thanks for the additional context.  The logs unfortunately don't have too much to go on, particularly if you hit the issue prior to installing whoisactive extension called out in the log.  Could you generally describe the dataset you're trying to graph, e.g., how many rows/columns, any large data types like JSON, XML, BLOB, etc.?  Thanks!

**Comment by MatrixArchitect** [comment]
@kburtram - thanks for your response. I definitely hit the issue before installing the "whoisactive" extension. 

I just upgraded 1.26 but the issue continues to happen. To answer your question: I just run a simple query against AdventureWorks2019. Here it is: 

SELECT
    CustomerID, 
    CAST(OrderDate AS DATE) AS OrderDate, 
    SalesOrderID, 
    ROW_NUMBER() OVER(PARTITION BY CustomerID ORDER BY SalesOrderID) AS [Row Number]
FROM Sales.SalesOrderHeader;

It returns about 31,465 rows. 

I think I am beginning to see what's happening. I trimmed down the result set to 1000 using the TOP clause and it didn't crash. As I increased the number of records returned by a 1000 each time the performance degraded exponentially (or so it seems). At some point the extension is hitting some kind of a timeout leading to the issue I reported. At around 4000 records the performance becomes unbearable. On my VM with 8GB RAM and 4 processors (XEON) 5000 records seems to be the breaking point. Just as the graph painted, almost simultaneously, I also got the ugly Window is not responding message, with the "Reopen", "Keep Waiting" and "Close" buttons, dialog box. It definitely seems related to the size of the result set and it seems the UI thread gives up on the script engine which is still busy trying to generate a chart (of course the chart in the case of this query is meaningless. I was just randomly trying to play with the Chart to get a better feel for ADS.) This was good insight for me.

**Comment by kburtram** [comment]
@MatrixArchitect thanks for the additional context.  I think we have some scalability problems with charting lots of datapoints.  We should either fix, or at least limit the number of datapoints rendered to avoid causing UI hangs.

@alanrenmsft any thoughts on how to handle this scenario?

**Comment by alanrenmsft** [comment]
I'll think about it and come up with something in April release.

**Comment by MatrixArchitect** [comment]
@kburtram and @alanrenmsft thank you both. Look forward to the update.
