### ISSUE TITLE
Adding row in edit data messes up the table

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#14346]
- Azure Data Studio Version: 1.26 RC1

Steps to Reproduce:

1. Right click on a table in data explorer
2. Click on Edit data
3. Add a table row (tab through cells while entering the data)

Data Entered in Edit Data:
![image](https://user-images.githubusercontent.com/6816294/108439138-8f544680-7205-11eb-81e4-4f669b5955fb.png)
Data Actually Displayed in Table: 
![image](https://user-images.githubusercontent.com/6816294/108439081-73e93b80-7205-11eb-9415-9cf023fe328c.png)

**Comment by aasimkhan30** [comment]
Seems to be a regression. Moving it to February milestone.

**Comment by cssuh** [comment]
Tried running the `Edit Data` command on an existing table, and it does not work.  I put more data and hit `Run`, but it doesn't show up when I query the DB.

**Comment by smartguest** [comment]
@cssuh Hitting run doesn't do anything for Edit Data at the moment, its only meant to edit the data as with SSMS. The results table will show up when you query the top 1000 results.

**Comment by aasimkhan30** [comment]
moving to backlog as it cannot be reproduced

**Comment by kburtram** [comment]
@aasimkhan30 if this can no longer be reproduced should we close the issue?
