### ISSUE TITLE
Unable to scale out Arc Postgres Hyperscale

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#14349]
- Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7911f67c09ae9de526709d24788ffb6dec
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension: 0.7.3

Steps to Reproduce:

1. deploy Arc Postgres Hyperscale
2. Go to compute/storage page and increase the number of worker nodes.

It does display a window 
![image](https://user-images.githubusercontent.com/22226386/108448408-80c25b00-7216-11eb-9550-2db923b5848d.png)

that indicates the instance is being updated but nothing happens in the background (verified with kubectl and azdata commands) and that window stays open forever it seems.

**Comment by nasc17** [comment]
**No repro** 
Arc extension 0.7.3
Version: 1.26.0-rc1 (user setup)
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:43:27.038Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
