### ISSUE TITLE
Configure node parameters for Arc Postgres Hyperscale does not work

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#14351]
- Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7911f67c09ae9de526709d24788ffb6dec
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension 0.7.3

Steps to Reproduce:

1. Deploy Arc Postgres Hyperscale
2. Go to the node parameters page
3. some of the page loads but some never loads (rotating blue bagels keeps turning) and the [search to filter items] field is disabled.
4. 
![image](https://user-images.githubusercontent.com/22226386/108449531-7ef99700-7218-11eb-825f-a440d384a743.png)

**Comment by nasc17** [comment]
**No repro** 
Arc extension 0.7.3
Version: 1.26.0-rc1 (user setup)
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:43:27.038Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
