### ISSUE TITLE
Unable to create a support request for Arc Postgres Hyperscale

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#14350]
- Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7911f67c09ae9de526709d24788ffb6dec
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension: 0.7.3

Steps to Reproduce:

1.deploy Arc Postgres Hyperscale
2.go to the new support request page
3. click new support request
4. click [open] when prompted
5. you'll get a resource not found page
6. 
![image](https://user-images.githubusercontent.com/22226386/108449039-a9972000-7217-11eb-92cb-0adf7c1ebf4b.png)

**Comment by bergeron** [comment]
@TheJY Was `azdata arc dc upload` run?  The resource won't be created in Azure until then.

**Comment by nasc17** [comment]
No repro
Arc extension 0.7.3
Version: 1.26.0-rc1 (user setup)
Commit: 995095f
Date: 2021-02-19T03:43:27.038Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by nasc17** [comment]
Uploaded resource (indirect connectivity mode) to portal before trying to create support request.
