### ISSUE TITLE
Experience with Arc Postgres Hyperscale is too unstable and unpredictable

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#14352]
- Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7911f67c09ae9de526709d24788ffb6dec
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension 0.7.3 

Steps to Reproduce:

1. At times none of the content loaded at run time loads
2. deploy Arc Postgres Hyperscale
3. go to any page, no runtime content loads even after several minutes wait:
3.1 connection string page:
![image](https://user-images.githubusercontent.com/22226386/108450634-62f6f500-721a-11eb-9940-60f94bec4e3e.png)

3.2 properties page
![image](https://user-images.githubusercontent.com/22226386/108450689-773af200-721a-11eb-9c04-440d2850f4f2.png)

3.3. compute and storage page
![image](https://user-images.githubusercontent.com/22226386/108450735-86ba3b00-721a-11eb-9779-cb05e2596c0f.png)

3.4 overview page
![image](https://user-images.githubusercontent.com/22226386/108450780-96398400-721a-11eb-91a7-7afa61d07024.png)

**Comment by nasc17** [comment]
Checked to see if this issue came up at all on stable release and still could not repro. 
Version: 1.26.0 (user setup)
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:26:50.428Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by Charles-Gagnon** [comment]
I'll close this then unless we get a more consistent repro with the stable build.
