### ISSUE TITLE
Configuring mem/vCPU settings does not seem to work

### ISSUE THREAD

**Issue by TheJY** [microsoft/azuredatastudio#14355]
Azure Data Studio Version:
Version: 1.26.0-rc1 (user setup)
Commit: 37727b7
Date: 2021-02-18T06:12:35.818Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Arc extension: 0.7.3

Steps to Reproduce:

1. deploy Arc Postgres Hyperscale
2. Go to compute/storage page and set CPU limit.
It does display a window
image
![image](https://user-images.githubusercontent.com/22226386/108452284-15c85280-721d-11eb-8530-01a3258b4752.png)

that indicates the instance is being updated but nothing happens in the background (verified with kubectl and azdata commands) and that window stays open forever it seems.

**Comment by nasc17** [comment]
No repro
Arc extension 0.7.3
Version: 1.26.0-rc1 (user setup)
Commit: 995095f
Date: 2021-02-19T03:43:27.038Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
