### ISSUE TITLE
Postgres Parameters Page Discard Button never disabled. 

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#14366]
Discard button stays enabled after use. 
- Azure Data Studio Version: Version: 1.26.0-rc1 (user setup)
![discardbutton](https://user-images.githubusercontent.com/69922333/108754614-02f29e00-74fb-11eb-9952-16704297cc01.gif)

Steps to Reproduce:

1. Deploy Arc Postgres Hyperscale
2. Go to the node parameters page
3. Alter a a parameter value
4. Press discard button 
5. Table is set back to initial state but discard button is still enabled.

**Comment by zxli** [comment]
I'm able to repro this issue.
