### ISSUE TITLE
Database Projects - Add existing file to project

### ISSUE THREAD

**Issue by SQLDBAWithABeard** [microsoft/azuredatastudio#14383]
**Is your feature request related to a problem? Please describe.**
Because it is a requirement, I need to add existing files into a database project (yeah I know it's not awesome but still it is there)

I can of course do this by editing the sqlproj file but this is unsuitable for some users.

**Describe the solution or feature you'd like**
Add Existing Item to be added to this menu and to the command palette

![image](https://user-images.githubusercontent.com/6729780/108733966-dfdde380-7526-11eb-98eb-bab4ec741c9d.png)

**Describe alternatives you've considered**
Manual editing of sqlproj file works but is unsuitable for all

Thank you very much.

**Comment by malcolm738** [comment]
I think there is a possible issue with the "Exclude from project" option
Logically in it does the same thing as delete in ADS, just leaving an orphaned file as well

Could it amend the 'Build Include="my.sql"' to 'None Include="my.sql"' so it's visible in ADS and excluded from project build

The enhancement would fit with the above request as the file being re-added may have been excluded and not visible preventing it being re-added without the .sqlproj file edit
