### ISSUE TITLE
Arrows to Collapse\Open Folders

### ISSUE THREAD

**Issue by NicholasIbarra** [microsoft/azuredatastudio#14384]
Issue Type: <b>Bug</b>

In SSMS, I can navigate the folders via my arrow keys left and right. I.e. 
Server 
   --> Databases 
      --> [Database] 
         --> Programability 
            --> Stored Procedures 
               --> [Procedure]
               --> [Procedure]
               --> [Procedure]

I can be on a specific procedure and arrow left and it will collpase the folder. And continute to do so until I make it to the root node that is the server. 

I can arrow up and down, just no left or right. 

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>
|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.95GB (117.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@NicholasIbarra thanks for your suggestion!  Currently the spacebar will expand/collapse containers in the tree, but I agree the arrows are also a natural command for this action.

**Comment by NicholasIbarra** [comment]
@kburtram Perfect, I will use this work around in the mean time. I want to migrate to the Data Services, so just wanted to provide feedback. I use SSMS daily and navigating the file tree speeds up finding objects since we have a lot of views and procedures. Thanks!

**Comment by KeithWalters** [comment]
See also #5579

I think the key thing is that space-bar can't move you up to the parent. Most treeviews support using the left arrow to both collapse the current node if expanded, but also move up to the parent if the current node is already collapsed - that's the more specific useful keyboard navigation.

**Comment by theSuda** [comment]
Is this under development? I miss this feature so much every day. Also the ability to apply filter on trees. It's so hard to replace SSMS :)

**Comment by aasimkhan30** [comment]
This was fixed by #22511
