### ISSUE TITLE
The code cell toolbar is not shown when the focus is moved to it using keyboard

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14405]
Steps to Reproduce:

1. Open a new notebook and add a code cell
2. click inside the code cell and now you can see the cell toolbar
3. move the focus away and navigate to the code cell with keyboard (tab key)

Expected:
the toolbar should appear

Actual:
toolbar is not shown

**Comment by chlafreniere** [comment]
@MaddyDev has since made some tabbing improvements, so I can no longer repro this:
![tabbing](https://user-images.githubusercontent.com/40371649/164808880-d48e3f57-9e05-42dd-9804-0953cf294da6.gif)

Closing as a result.
