### ISSUE TITLE
Python Manage Packages dialog doesn't filter packages according to which python version they support

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#14407]
The default Python instance used by ADS is Python 3.6.6, but pandas 1.2.2 requires at least Python 3.7.1. Going by the dialog, it seems like we should be able to install 1.2.2 successfully, but the install fails later due to the current Python version being unsupported for that version of pandas. We should be filtering out the package versions in the version dropdown according to what is supported for the current Python version.

**Comment by chlafreniere** [comment]
Hey @corivera will this realistically make the March release? If so, great!

If you won't be able to get to this over the next few days, please feel free to move out to April.

**Comment by corivera** [comment]
If the package metadata has a supported versions list, then I should be able to do it by end of day.

**Comment by chlafreniere** [comment]
@corivera sounds good, thanks! Just making sure our list for March is up to date 😄

**Comment by corivera** [comment]
@chlafreniere I have the package filtering working (with tests included), and I'm currently scanning through the PyPI Rest API docs to see if I've missed any weird versioning details.
