### ISSUE TITLE
not able to do keyboard navigation within ADS because of the callout dialog

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14406]
once we have the callout dialog opened once, the keyboard navigation within ADS is broken, unless the notebook is closed.

![image](https://user-images.githubusercontent.com/13777222/108915606-fbf28b00-75e1-11eb-9106-754ff5ef6085.png)

**Comment by alanrenmsft** [comment]
also, keyboard navigation is not possible within this dialog

**Comment by chlafreniere** [comment]
@halerankin please take a look. We need to fix this for March. Please let me know if you have any concerns.
