### ISSUE TITLE
Sync with VS Code source

### ISSUE THREAD

**Issue by leonardder** [microsoft/azuredatastudio#14413]
**Is your feature request related to a problem? Please describe.**
VS Code has received some major accessibility improvements in the last few months. Most notably, the settings UI is way more usable for blind or partially sighted people.

**Describe the solution or feature you'd like**
Sync with latest VS Code source. Also, please consider formalizing a strategy to do this on a regular basis, e.g. quarterly.

**Comment by kburtram** [comment]
@leonardder we have a process to routinely update the vscode source we're build from.  Currently the insiders builds has an update through ~1.51.  We are planning to catchup with 1.53 in the next few weeks.  This is on-going engineering, so we don't track this through github issues.  Thanks!

**Comment by leonardder** [comment]
Thanks for your explanation! Is there an easy way to find out what version of Code is targeted by a certain release of Data Studio?

**Comment by dzsquared** [comment]
@leonardder to get the VS Code engine version of your currently installed Azure Data Studio, click "About" in the "Help" menu

**Comment by Charles-Gagnon** [comment]
@dzsquared I believe @leonardder was asking for whether we plan out the syncs such that external users could see when we plan to be synced up to a certain point.

Currently we do not do this though - the VS Code merging isn't done on a completely regular basis at this time and depending on what changes have been made on their end some merges take longer than others. But typically we try to stay within a release or two of them when they do a release. 

Looking through the commits to see when the merges happen is the only way to know for sure where we're currently at - look for commits such as this one https://github.com/microsoft/azuredatastudio/commit/ce612a3d9613a1857772150892e5f9abe1dd44f7 which will contain the commit hash that we'll be synced up to at that point.

**Comment by dzsquared** [comment]
This is also an item we have included in the release notes in the past, adding @yualan for awareness
For example: https://docs.microsoft.com/en-us/sql/azure-data-studio/release-notes-azure-data-studio?view=sql-server-ver15#march-2020

**Comment by leonardder** [comment]
> @leonardder to get the VS Code engine version of your currently installed Azure Data Studio, click "About" in the "Help" menu

Wow, I should have checked that myself, it is good to know that this info is available. Thanks for pointing this out.

Stable is now at 1.48, so that clarifies why the new settings editor behavior (introduced in 1.50) isn't yet there.

> This is also an item we have included in the release notes in the past, adding @yualan for awareness

Yes, I recall that and it would be very helpful if this could be added in next release notes. For many people it might not be relevant, but as for accessibility, ADS heavily relies on improvements in VS Code.

**Comment by raeokay** [comment]
I've gotten this extension to load in ADS 1.28.0 (VS Code 1.51.0) by changing the vscode version in package.json to match the version ADS is on. I assume this will cause problems for some dependencies that it appears ADS doesn't use. I also added the azdata engine with all versions because I don't know what I'm doing. :) But it compiled, and it's working fine in ADS -- whether it would cause issues in VS Code is unknown to me. 

Changes: 

`	"engines": {
		"vscode": "^1.51.0",
		"azdata": "*"
	},`

`	"devDependencies": {
		"@types/chroma-js": "2.1.3",
		"@types/lodash-es": "4.17.4",
		"@types/node": "12.12.70",
		"@types/sortablejs": "1.10.6",
		"@types/vscode": "1.51.0",
                ... blah blah blah`
