### ISSUE TITLE
Adding cells doesn't mark a Notebook as dirty

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14426]
1. Create New Notebook
2. Add a new cell to it
3. Close Notebook editor

Expected : Prompted to ask to save Notebook

Actual : No prompt - editor is closed immediately

This is a regression from 1.25.3

Note that typing in the cell does then correctly mark it as dirty - it's just the initial adding that doesn't.

**Comment by chlafreniere** [comment]
![image](https://user-images.githubusercontent.com/40371649/109078948-0e88c500-76b3-11eb-8762-fe15c19967ce.png)

No repro on Mac.
