### ISSUE TITLE
Table filter icon displaying multiple times

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14437]
Insiders/Main

This only appears to happen for the SQL Assessment extension - my hunch is that it's because they're the only ones to do appendData

Possibly caused by https://github.com/microsoft/azuredatastudio/pull/14333

![image](https://user-images.githubusercontent.com/28519865/109196427-8ce77480-7750-11eb-94f4-3f4136953295.png)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Do you have time to look into this?

**Comment by alanrenmsft** [comment]
let me take a look and I will fix it
