### ISSUE TITLE
Migrate all 1st-party Git repos sqlopsstudio depends on to Microsoft organization

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#1443]
All 1st-party source code we depend on for the sqlops project should be in the Microsoft organization.  Currently there are a few repos like `Slickgrid` and `Service Downloader` that are in personal GitHub repos.  We'll need to go through appropriate OSS process for these repos to bring them into MS org with proper licenses, etc.

**Comment by kburtram** [comment]
@anthonydresser could you please put together a list of any 1st-party repos (including forked repos) that sqlopsstudio depends on that aren't in MS org.  We can then start the OSS approval process to move these into the desired location.  Thanks!

**Comment by anthonydresser** [comment]
```
"slickgrid": "github:anthonydresser/SlickGrid#2.3.16"
"html-query-plan": "git://github.com/anthonydresser/html-query-plan.git#2.4"
"service-downloader": "github:anthonydresser/service-downloader#0.1.2"
```
