### ISSUE TITLE
IPV6 / Named Pipe connection no longer working

### ISSUE THREAD

**Issue by jaquesleroux** [microsoft/azuredatastudio#14430]
Issue Type: <b>Bug</b>

MacOS Big Sur

Was able to connect to SQL dev with named pipe using IPv6 address
This week after update . No longer able to connect to any of our customers SQL servers

Tested.. With Window MSSMS on Windows with same credentials and able to connect.
 - so.. Not server issue.
 - Applciation issue.

How is this a production release version!
Did that before about a year ago . .and now it is back!

No way to revert to previous version to be able to work. How is this a production ready application! 
Not Happy!

Azure Data Studio version: azuredatastudio 1.26.0 (995095f696fd9800e7e621d34daa895d57989ccd, 2021-02-19T03:24:52.069Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
datavirtualization|Mic|1.10.0
import|Mic|1.2.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@jaquesleroux we are tracking a connectivity regression impacting macos with issue https://github.com/microsoft/azuredatastudio/issues/14382.  We have a hotfix planned for today which reverts the SqlClient driver update.  

Here's a direct link to that build https://sqlopsbuilds.azureedge.net/stable/796abbdf5fdd341e3528e30a6b777c93e115eb02/azuredatastudio-macos-1.26.1.zip.  If you have time please let us know if this update fixes the issue you're hitting or if this is a separate issue.

**Comment by jaquesleroux** [comment]
@kburtram Many thanks  😊  

I downloaded it now and able to connect. 
Many thanks for getting this resolved so quickly .
Apologies for harshness earlier.. Was a frustrating day all in all 😇

FYI: Version details where it is working
Version: 1.26.1
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:37:01.966Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0
