### ISSUE TITLE
SQL Assessment Extension -  not rendering the result in UI

### ISSUE THREAD

**Issue by sqlworldwide** [microsoft/azuredatastudio#14435]
- Azure Data Studio Version:
- Version: 1.26.0 (system setup)
Commit: 995095f696fd9800e7e621d34daa895d57989ccd
Date: 2021-02-19T03:26:50.428Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Using the extension run an SQL assessment
2. I see the assessment if I click the history tab
3. Clicking one of the assessments does not render on the UI I only get a blank screen.
4. Hence I cannot save it in a table nor I can create an HTML file.

![Screenshot 2021-02-25 105545](https://user-images.githubusercontent.com/26484126/109181800-53b40200-775a-11eb-9f83-0494305d4ca0.png)

![Screenshot 2021-02-25 111201](https://user-images.githubusercontent.com/26484126/109182102-a7265000-775a-11eb-91df-d450105a901b.png)

**Comment by Charles-Gagnon** [comment]
Thanks for the report - it looks like this was an issue that got into the 1.26 build but has been fixed in Insiders. 

Could you install the latest insiders build from https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main and verify that it's fixed there for you?

(It looks like there's another issue with duplicate filter icons though - I'll file an issue for that separately)

**Comment by Charles-Gagnon** [comment]
@vchvlad FYI

**Comment by sqlworldwide** [comment]
> Thanks for the report - it looks like this was an issue that got into the 1.26 build but has been fixed in Insiders.
> 
> Could you install the latest insiders build from https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main and verify that it's fixed there for you?
> 
> (It looks like there's another issue with duplicate filter icons though - I'll file an issue for that separately)

Thank you so much. I will and let you know.

**Comment by sqlworldwide** [comment]
I can confirm that the insider's edition fixed the issue I reported. Thank you for a quick response.

**Comment by Charles-Gagnon** [comment]
Thanks! The next stable release is planned for mid-March so this fix should be in there then. Sorry for the inconvenience!
