### ISSUE TITLE
Notebooks: Escape does not make current active cell inactive

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#14434]
- Azure Data Studio Version:
Version: 1.27.0-insider
Commit: 9148aa1ed552cc89b7362f8132c2dec437ce5537
Date: 2021-02-23T09:26:49.644Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1. Create new notebook
2. Add cell (either code or text)
3. Press escape

Cell remains active.

**Comment by chlafreniere** [comment]
May be related to the keydown/keyup conversation with the callout feature.
