### ISSUE TITLE
Cannot delete folder with files from the SQL Database Project

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#14440]
- Azure Data Studio Version: 1.27.0-insider (user setup)
Commit: 9148aa1ed552cc89b7362f8132c2dec437ce5537

**Steps to Reproduce:**

1. In the database project, right-click a non-empty folder and select "Delete":
![image](https://user-images.githubusercontent.com/11728682/109200856-f027d580-7755-11eb-8de0-5c4c2bf08b56.png)

2. The error message appears:
![image](https://user-images.githubusercontent.com/11728682/109200544-9b845a80-7755-11eb-9fe9-30d8933f11b7.png)

**Expected result:**
Folder and files should be deleted.

**Comment by nahk-ivanov** [comment]
I was fixing some other issues and looked into this real quick as well. The problem is in `ProjectsController.delete` [here](https://github.com/microsoft/azuredatastudio/blob/ff6e37747710edab1e1ab94627e398e5866a6561/extensions/sql-database-projects/src/controllers/projectController.ts#L533). We try to find an entry for the selected folder, but there is none, so it does not do anything, `success` is `false` and it bails with an error.

One thing to do here is I will update the add API to ensure all `<Folder />` items exist, but I think it makes sense to address this even if folder items are missing - everything else works fine, VS works fine. In order to fix this we would probably need to rewrite the method to operate on the tree items and for each of the tree items attempt to remove the associated project item and actual file/folder on disk. Since this is a removal - if item does not exist already - we just silently continue, as not having it was the intention anyway.

**Comment by kisantia** [comment]
closing since this works in both legacy and sdk style projects when I tried now.
