### ISSUE TITLE
Cannot delete a folder from SQL Database Project when there are excluded files in it

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#14441]
- Azure Data Studio Version: 1.27.0-insider (user setup)
Commit: 9148aa1ed552cc89b7362f8132c2dec437ce5537

**Steps to Reproduce:**

1. Create new SQL Database Project, add folder and a file under it.
![image](https://user-images.githubusercontent.com/11728682/109202949-69282c80-7758-11eb-8c18-1ae489f078e6.png)

2. Right-click the **file** and select "Exclude from project"
![image](https://user-images.githubusercontent.com/11728682/109203036-86f59180-7758-11eb-8f15-5845df5ae6e6.png)

3. Right-click the **folder** and select "Delete":
![image](https://user-images.githubusercontent.com/11728682/109203111-9d9be880-7758-11eb-8d11-4f013f2455a6.png)

4. Error message appears:
![image](https://user-images.githubusercontent.com/11728682/109203150-aab8d780-7758-11eb-856e-ed9ae5bb70d4.png)

**Expected result:**
Folder should be removed from disk and the project (this is the behavior of Visual Studio in such cases). Although I prefer the experience to be consistent with VS, the point could be made that we don't want to unintentionally remove user files. In that case we should at least exclude the folder from the project and keep it on disk. Either way, I don't think error message is the good solution here.

**Comment by kisantia** [comment]
@zijchen lets look into what vscode does when you try to delete a folder in the file explorer and be consistent with that

**Comment by zijchen** [comment]
VSCode prompts user for delete confirmation so we can probably do something similar
![image](https://user-images.githubusercontent.com/13544267/109370087-b63cf900-7853-11eb-8cd3-d1a17bb05a92.png)
