### ISSUE TITLE
Find highlight is not seen when cell edit mode is active

### ISSUE THREAD

**Issue by halerankin** [microsoft/azuredatastudio#14455]
On Mac OS X, with a given cell editor active, the **scroll to** position of the current highlighted hit (in orange) is just out of view. See image below: 
<img width="1520" alt="image" src="https://user-images.githubusercontent.com/12279161/108438024-44d1ca80-7203-11eb-9a99-4f18dd3aff1d.png">

When the editor is NOT active, the highlighted hit is not obstructed by the UI in any way. See image below:
<img width="1523" alt="image" src="https://user-images.githubusercontent.com/12279161/108438241-b742aa80-7203-11eb-8e5e-c1a4ffd57f05.png">

**Comment by MaddyDev** [comment]
Fixed by the #15149
