### ISSUE TITLE
Schema Compare Generate Script Ignores Tables defined in Security Policy in SQL Server

### ISSUE THREAD

**Issue by tlentine** [microsoft/azuredatastudio#14453]
- Azure Data Studio Version: Insiders version 1.27.0-insider
- Schema Compare: 1.9.1
- Dacpac: 1.7.0
- Database Project: 0.7.0

**Background**
We use Security Policies as part of our adoption of Row Level Security within SQL Server. We have a process in place that ensures any table defined within the specified schema (dbo in this case) is added to the existing security policy. Typically we do not need to remove tables from the policy once they are added. However, we are trying to embrace "Database DevOps" and let the Schema Compare tool generate the change script necessary to modify a target database to match our updated source project. This is where things start to get dicey.

Schema Compare tries really hard to make sure that tables match up perfectly, including column order, etc. Sometimes this means that Schema Compare will generate scripts that will remove constraints from the tables, and run a process to create a new table, push existing data into the new table, drop the original table, then rename the "new" table to the final object name. Whilst this **can** work, in our case this falls flat when one actually tries to execute the script against a target db without some serious modifications.

Steps to Reproduce:

1. Create a table in SQL Server 
2. Create a security policy that references said table
3. Add data to your table
4. Modify your table by adding a few new fields
5. Perform a schema compare and generate the script
6. Attempt to execute the script against the target database

**What happens** (at least in our case)
The script, if it is created in such a way to as to create a new table, insert data to the new table, drop the existing table, rename the "new" table, will fail when it tries to drop the original table because it is referenced by the Security Policy.

**What I'd like to see happen**
I'd like at the very least to be warned about this BEFORE finding a runtime failure with the script. 

In an ideal circumstance, if the "change script" could remove the table from the security policy and add it back after the table has been modified that would be great.

This is obviously very edge case, but it is a pain point that prevents us from achieving next level nirvana with automated database CI / CD. : )

**Comment by kisantia** [comment]
@tlentine is this the same behavior as SSDT schema compare? Just want to make sure we have the same baseline behavior right now.

**Comment by tlentine** [comment]
They are similar, yes - it's been a pain point for us for a while with SSDT - I'm hoping we'll have a better experience with Azure Data Studio / Schema Compare overall.

**Comment by kisantia** [comment]
this change would need to be made in DacFx

**Comment by tlentine** [comment]
Is there a public repo where I can open an issue?

**Comment by kisantia** [comment]
there's this repo https://github.com/microsoft/DACExtensions/issues, but it's the same team that works on DacFx and the extensions that use DacFx in ADS, so we're aware of this issue opened here.

**Comment by kisantia** [comment]
closing as this is upstream in Dacfx
