### ISSUE TITLE
Remember Notebooks Folder

### ISSUE THREAD

**Issue by bgreen77** [microsoft/azuredatastudio#14460]
Issue Type: <b>Feature Request</b>

On initially opening the App, and selecting a folder for Notebooks, the notebooks stored in the selected folder are listed.

Closing and then re-openening the app, the previously selected folder for the notebooks is lost, and it has to be selected again.

It would be good to either:
- Have a setting of the default notebooks folder, so that they are listed automatically on app launch (if the setting is set)
- Remember the last folder used, and list the notebooks in that folder

While we do have Pinned Notebooks, and they are retained, I see the Pinned Notebooks as a list of frequently used notebooks or notebooks that I am working with at a given time.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

**Comment by chlafreniere** [comment]
Thanks @bgreen77.

Out of curiosity, if you open a folder in ADS (i.e. through the File menu), does that help your scenario, or do you need the flexibility to see notebooks in different folders than whatever folder/workspace is opened globally in ADS?

**Comment by chlafreniere** [comment]
Closing since we need a bit more info here. Feel free to reopen if this is still occurring. Thanks!
