### ISSUE TITLE
Keywords for Temporal Tables catched as problem

### ISSUE THREAD

**Issue by abinsubizdk** [microsoft/azuredatastudio#14461]
Issue Type: <b>Bug</b>

Running ADS on Azure Database.

Have some script that manipulates Temporal tables.

For some reason some of the keywords are highlighted as problems, but the query runs just fine.

 ALTER TABLE [dbo].[xxx] SET ( SYSTEM_VERSIONING = OFF );
 ALTER TABLE [dbo].[xxx]  DROP PERIOD FOR SYSTEM_TIME;

SYSTEM_VERSIONING 
FOR 

are both reported.

![Problems Reported for Temporal Commands](https://user-images.githubusercontent.com/78896940/109263795-2de33780-7804-11eb-9594-aa90f92a72d6.png)

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-select-top-n|jim|0.0.5
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.7.0
datavirtualization|Mic|1.10.0
import|Mic|1.2.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.9.1
sql-database-projects|Mic|0.6.1
azdata-sanddance|msr|3.1.0

</details>

**Comment by alanrenmsft** [comment]
I am able to reproduce the issue with azure sql server.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon is this going to be fixed when you refresh the Y file while fixing the other similar issue?

**Comment by Charles-Gagnon** [comment]
It should be, yes

**Comment by alanrenmsft** [comment]
@Charles-Gagnon assigning this to you, do you think this will be fixed in May release?

**Comment by Charles-Gagnon** [comment]
@abinsubizdk This should be fixed in the upcoming release of ADS (1.30)
