### ISSUE TITLE
Issue to connect to named instance from ADS on MacOS

### ISSUE THREAD

**Issue by mikedavem** [microsoft/azuredatastudio#14478]
- Azure Data Studio Version: 1.26.0

Steps to Reproduce:

1. Using **server\instance** format fails to connect to named instance

I'm facing the following error msg:

**_A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)_**

However using following formats work successfully:

- **server,port**
- **server\instance\\\\**

**Comment by Charles-Gagnon** [comment]
@mikedavem Please update to the latest version - 1.26.1. This is a hotfix rolling back a SqlClient driver change that had a regression for kerberos auth on non-Windows platforms. See https://github.com/microsoft/azuredatastudio/issues/14382 for more details.
