### ISSUE TITLE
IPYNB file corruption

### ISSUE THREAD

**Issue by claudiosalvio-vscode** [microsoft/azuredatastudio#14481]
Issue Type: <b>Bug</b>

Several times during the last few days IPYNB files got corrupted while I was editing them in ADS.

I have been using ADS on Windows and managing this kind of files for almost a year and this is the first time this has happened.
The only recent change I've made in my enviroment is that I upgraded ADS to version 1.26.1.

In order to try to find the problem, I opened an IPYNB file with ADS, edited a text cell and saved the file.
I then opened the IPYNB file with a text editor (Notepad++) and looked at the segment of the file corresponding to the text cell I had modified.

What I detected is that the line breaks in the modified segment are \n instead of \r\n.
In the rest of the file, they remained as they always were: \r\n. 
I suspect this might be due to some change in the code causing ADS to not respect the system enviroment line breaks. 
Since this is the only difference I found, I believe that it may be causing some undesired effect which leads to the file becoming corrupted.

Thanks to all who contribute to making this very useful software possible.

Greetings,
Claudio

I 💙 ADS

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8350 Eight-Core Processor            (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off_ok<br>video_decode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.50GB (17.68GB free)|
|Process Argv|--extensions-dir C:\Program Files\Azure Data Studio\resources\app\extensions -- C:\Users\Administrator\Apuntes\content=apuntes_created.yyyyMMdd=20210228_device=wskjdcen-kk4k_kernel=PowerShell_user=administrator@wskjdcen-kk4k.ipynb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (32)</summary>

Extension|Author (truncated)|Version
---|---|---
azurecore|Mic|0.1.0
bat|vsc|1.0.0
big-data-cluster|Mic|1.0.0
configuration-editing|vsc|1.0.0
data-workspace|Mic|0.1.0
docker|vsc|1.0.0
extension-editing|vsc|1.0.0
git|vsc|1.0.0
git-ui|vsc|1.0.0
github|vsc|0.0.1
github-authentication|vsc|0.0.1
image-preview|vsc|1.0.0
insights-default|Mic|0.1.0
json|vsc|1.0.0
json-language-features|vsc|1.0.0
markdown|vsc|1.0.0
markdown-language-features|vsc|1.0.0
merge-conflict|vsc|1.0.0
microsoft-authentication|vsc|0.0.1
sqlservernotebook|Mic|0.3.9
mssql|Mic|0.1.0
notebook|Mic|0.1.0
powershell|vsc|1.0.0
python|vsc|1.0.0
r|vsc|1.0.0
resource-deployment|Mic|0.0.1
search-result|vsc|1.0.0
sql|vsc|1.0.0
vscode-theme-seti|vsc|1.0.0
xml|vsc|1.0.0
xml-language-features|mic|1.0.0
yaml|vsc|1.0.0

(11 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
@MaddyDev you have some context here, correct?

**Comment by chlafreniere** [comment]
Once fix has been identified, potential hotfix candidate.

**Comment by MaddyDev** [comment]
@claudiosalvio-vscode Sorry about the experience, Can you elaborate when you say corrupted? Are you seeing the content updated to something unexpected when you open the file or the file contents not rendered at all. If you can share a repro/steps to a repro would help us find the issue. Thanks.

**Comment by claudio-salvio** [comment]
Almost every time the file was corrupted it showed garbage but on one or two occasions the content did not appear at all.
By garbage I mean characters that were out of place.
For example, on one occasion there was a "99" written in a place where I had not written any numbers.
On another occasion there was a stray ">" in the wrong place in a text cell and it was visible when the cell was not in edit mode.
In all cases when I would open the IPYNB file with a text editor I found that it was corrupt, there were markdown segments out of place or interspersed with each other in odd ways.
Honestly, since I use ADS a lot I downgraded to version 1.25.3 which I knew worked correctly.
Anyway, I still consider that the change in the new line is probably responsible for what happens.
As soon as I can I will reinstall version 1.26.1 but a few days ago I changed jobs and I am very busy.
I can't commit to testing right away.
Thanks for your interest.
Regards,
Claudio

**Comment by MaddyDev** [comment]
> Hello Maddy
> Almost every time the file was corrupted it showed garbage but on one or two occasions the content did not appear at all.
> By garbage I mean characters that were out of place.
> For example, on one occasion there was a "99" written in a place where I had not written any numbers.
> On another occasion there was a stray ">" in the wrong place in a text cell and it was visible when the cell was not in edit mode.
> In all cases when I would open the IPYNB file with a text editor I found that it was corrupt, there were markdown segments out of place or interspersed with each other in odd ways.
> Honestly, since I use ADS a lot I downgraded to version 1.25.3 which I knew worked correctly.
> Anyway, I still consider that the change in the new line is probably responsible for what happens.
> As soon as I can I will reinstall version 1.26.1 but a few days ago I changed jobs and I am very busy.
> I can't commit to testing right away.
> Thanks for your interest.
> Regards,
> Claudio

Thanks for the info, I haven't been able to repro this behavior, are you editing the notebook on ADS using wysiwyg mode or markdown? Also it would be great if you can share the corrupted notebook with us.

**Comment by MaddyDev** [comment]
@claudiosalvio-vscode Thanks for your time, but we're not sure what change caused this and we're not able to repro this on our latest. It would be a huge help if you can try our insiders and see if this issue repros.

**Comment by MaddyDev** [comment]
Fixed by #14529 Waiting confirmation from user.

**Comment by MaddyDev** [comment]
Closing the issue since March release that has the fix is out.
