### ISSUE TITLE
Notebook output fields not saved

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14486]
Version: 1.26.1 (user setup)
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:42:55.085Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

1. Create Notebook
2. Add code cell with some simple code it in and execute
3. Save the Notebook
4. Clear the Notebook results
5. Save the Notebook
6. Close the Notebook
7. Re-Open the saved Notebook

Expected : Notebook is opened without any results displayed

Actual : Output results are still there along with metadata such as execution count

Possibly related to https://github.com/microsoft/azuredatastudio/issues/14426

**Comment by MaddyDev** [comment]
#14427 fixes this.
