### ISSUE TITLE
Markdown horizontal scrollbar usability

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14483]
To repro: 
* ADS
Version: 1.26.1 (user setup)
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:42:55.085Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Is your feature request related to a problem? Please describe.**
1. Floating horizontal scrollbar is hard to get to when word wrap is turned off. 
At a glance, users won't know that there is a scroll bar. 
![image](https://user-images.githubusercontent.com/6405919/109590835-8430ce80-7ac1-11eb-91ff-8d8a373b271c.png)

2. It only shows when you hover around somewhere in the middle. 
![MarkdownHorizontalScrollBar](https://user-images.githubusercontent.com/6405919/109590923-a0347000-7ac1-11eb-976e-a326e7e20c08.gif)

3. Sometimes it's off the screen. This makes it hard for scrolling horizontally while editing the lines that are on the top, There will be a lot of scrolling up and down while scrolling horizontally. 
![image](https://user-images.githubusercontent.com/6405919/109591357-39fc1d00-7ac2-11eb-9586-f79ede4dc7e9.png)

**Describe the solution or feature you'd like**
The Horizontal scrollbar to show more intuitively. 

**Describe alternatives you've considered**
None.

**Additional context**
Word wrap is often turned off for users can work with tables.

**Comment by MsSQLGirl** [comment]
Added more details and screenshots.

**Comment by radentonev** [comment]
**Scroll bar visibility**: this seems to be consistent with rest of ADS: only show scrollbars on mouse hover and/or if editor is active. I think if we are to make a change, it needs to be more global and would require alignment with everyone. At first glance, this doesn't seem like a problem to me.

**Scroll bar off screen**: For large cells, I think that it is problematic that it is off screen. I think we should make it sticky to the bottom of the visible area, similarly how the markdown editor is sticky to the top.

**Scroll bar position**: It should show up at the bottom of the cell, and not in the middle (end of content). The exception is if the bottom of the cell is lower than visible area. Then, it should be sticky to the bottom of visible area.

**Comment by MsSQLGirl** [comment]
Changing this to P2.
