### ISSUE TITLE
Unable to close tab after connection deletion

### ISSUE THREAD

**Issue by martindlarsson** [microsoft/azuredatastudio#14495]
- Azure Data Studio Version: 1.26.1

Steps to Reproduce:

1. Created a new connection to a database and saved it with a name under connections
2. Right clicked on it and clicked Manage. A new tab appears with objects
3. Right click on the connection and delete it
4. I am now unable to close the "Manage"-tab. Needed to restart the client to get rid of the tab.

**Comment by alanrenmsft** [comment]
not able to reproduce the issue.

**Comment by kburtram** [comment]
Closing based on previous comment and lack of current repro.  Please let us know if you're still impacted by this issue.
