### ISSUE TITLE
Some queries never stop executing

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azuredatastudio#14496]
Issue Type: <b>Bug</b>

Starting with the latest release I'm seeing issues running simple queries. In one case I had a T-SQL error in the query but in another the query looks fine (having just run it on another machine's instance of ADS). However when I click Run it starts running the query and never ends. Clicking Cancel does nothing. This is for an arbitrary query. For example the one I was trying to run was this.

```
BEGIN TRY
  sys.xp_create_subdir N'G:\Temp' 
END TRY BEGIN CATCH
  SELECT ERROR_NUMBER() AS ErrorNumber, ERROR_SEVERITY() AS ErrorSEverity, ERROR_MESSAGE AS ErrorMessage
END CATCH
```
I don't think it has anything to do with the query itself, other than perhaps a compiler error or something, as I have other queries that do this as well. I can copy the query, close ADS, open it back up, paste the query in and it then runs fine. It is intermittent at best. 

This started with the latest release.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (9.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@CoolDadTx Are you saying the query you posted can be executed just fine? I see two problems with it. in line 2 you are missing `exec` and in line 4, there should be a pair of parenthesis after ERROR_MESSAGE.

**Comment by CoolDadTx** [comment]
@alanrenmsft No. I'm saying that if I take the same query and put it into SSMS then it fails immediately. However in ADS it starts and never completes. Once in this state the only way to recover is to restart ADS. If I take a working query in SSMS and drop it into a new instance of ADS then it executes. I can also see query errors in ADS for some queries but others just refuse to stop.

It almost appears like it is having an issue running a query with errors for the first time but I don't know for sure.

**Comment by CoolDadTx** [comment]
Here's another query.

```
DECLARE @kundres_local TABLE (invoice_number BIGINT, Reminder INT)
DECLARE @OOF TABLE (SALDO_KR INT, DOKNR BIGINT, Datum2 DATETIME)

INSERT INTO @kundres_local ( invoice_number, Reminder )
SELECT OOF.DOKNR, -1 AS Uttryck1
FROM @OOF oof LEFT JOIN @kundres_local kundres_local ON OOF.DOKNR = kundres_local.invoice_number
WHERE (((OOF.SALDO_KR)>0) AND (DATEDIFF(day, GETDate(), Datum2) >0) AND ((kundres_local.invoice_number) Is Null));
```

This query is valid. When I originally ran it the first 2 times it had errors such as bad alias and unknown function. It correctly reported the errors. After I fixed those errors and got to this query I ran it and ADS started running the query and never stopped.  Closing ADS and opening it back up, opening a new query window, pasting the above query in and then running it has it return 0 results like I expected.

**Comment by alanrenmsft** [comment]
thanks @CoolDadTx  I will take a look at this issue.

**Comment by alanrenmsft** [comment]
I am not able to reproduce the issue, are you still seeing the issue with the latest ADS release? if so please reactivate and add the logs mentioned in the comment (https://github.com/microsoft/azuredatastudio/issues/14496#issuecomment-791063311) above.
