### ISSUE TITLE
add an Azure account doesn't work due to SSL error

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14493]
![image](https://user-images.githubusercontent.com/13777222/109584134-de2b9700-7ab5-11eb-95e5-4c1c09f30546.png)

in the code, we use http but most modern browser will automatically use https. when this error happens, user has to disable auto https in order to make it work.

**Comment by kburtram** [comment]
I recall Amir looked at this scenario a while ago and determined there isn't really anything we can do.  We can get a verified certificate for localhost, so even if we tried to support HTTPS the user would still hit a cert validation error.  Perhaps if we moved the entire auth scenario into the product UI (without shelling to browser) we could avoid hitting an error in this configuration.

**Comment by alanrenmsft** [comment]
for those who run into this issue, you can workaround the issue by disabling the auto https setting in your browser for localhost and retry. for Microsoft Edge(chromium based), you can follow the instructions here: https://stackoverflow.com/questions/63825407/microsoft-edge-redirects-http-localhost-to-https-localhost

**Comment by kburtram** [comment]
@alanrenmsft thanks!  I believe switching to Device Code authentication in the User Settings also avoids this issue.

**Comment by kburtram** [comment]
This behavior is "by design" in that the port on localhost needs to be http or self-signed cert.  Many browsers block/warn on self-signed cert, so that isn't better option.  Resolution is either to manually edit URL to http:// or to use device code, which doesn't require a redirect to localhost.
