### ISSUE TITLE
Manage Packages Icon has styling issues

### ISSUE THREAD

**Issue by radentonev** [microsoft/azuredatastudio#14507]
Manage Packages Icon Issues:
- Padding is off (all themes)
- Color is wrong for dark theme.

![Screen Shot 2021-03-02 at 3 26 50 PM](https://user-images.githubusercontent.com/71295692/109728806-c1519b00-7b6b-11eb-8e2c-703002a52f52.png)

**Steps to Reproduce:**
1. Open a notebook
2. Select Python kernel
3. For color issue, select dark theme

**Azure Data Studio Version:**
Version: 1.27.0-insider
Commit: 48a63e1f508ac6fd54cd741d1824a00acb557a2e
Date: 2021-03-01T06:37:55.612Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

**Comment by Charles-Gagnon** [comment]
@halerankin Please sync up with @chlafreniere if you want to bring this to ask mode for the March release

**Comment by chlafreniere** [comment]
Tested in main and looks good. Reopening for Ken's consideration:
![image](https://user-images.githubusercontent.com/40371649/110419171-a5f3fd80-804d-11eb-8c93-983036eb38be.png)
![image](https://user-images.githubusercontent.com/40371649/110419192-b0ae9280-804d-11eb-940b-f3c1e2e10e88.png)
![image](https://user-images.githubusercontent.com/40371649/110419206-b73d0a00-804d-11eb-831c-e094a1f3e547.png)
