### ISSUE TITLE
A11y_AzureDataStudioSQL_Project_Database_CreateProjectFromDatabase_Keyboard: Keyboard focus is moving outside of the "Create Project From Database" pane after hitting shift + tab key.

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/azuredatastudio#14519]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**: #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudioSQL-MAC-Feb2021;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#WCAG2.4.3;#Keyboard;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio
Mac OS Version: Big Sur Version 11.2.2

### Repro Steps:

1. Launch the application-Azure Database Project and install extension SQL Database Projects.
2. Tab till SQL Database Project Home Screen with heading "Projects".
3. Tab to connections select your server and connect to it.
4. Few databases will appear under your connection then right click on any database
5. Tab till "Create project from database" and hit enter.
6. Tab to the "Select connection" button under "Source database" title and press shift + tab key.
7. Check if focus is moving outside of the pane.

### Actual:
Keyboard focus is moving outside of the "Create Project From Database" pane after hitting shift + tab key.

Same issue is observed in below screen:
Data tier application

### Expected:
Keyboard focus should not go outside of the "Create Project From Database" pane after hitting shift + tab key.

### User Impact:
Keyboard only users will face difficulty in navigating again in the pane.

**Comment by kisantia** [comment]
same as windows issue https://github.com/microsoft/azuredatastudio/issues/14317

**Comment by Swati1700** [comment]
Verified the bug in the environment Application Name: Azure Data Studio.  Issue is fixed and does not reproduced. Please find the not repro attachment below.
[14519_Fixed.webm](https://user-images.githubusercontent.com/86710888/220338349-e008d55e-7227-4de4-b24b-6d76485d5df2.webm)

**Comment by 12-shweta** [comment]
Github Tags:#Closed;

**Comment by Swati1700** [comment]
Github Tags:#Closed;
