### ISSUE TITLE
A11y_AzureDataStudioSQL_Project_CreateNewProject_Popup_Keyboard: Keyboard focus goes outside of the popup by hitting tab key

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/azuredatastudio#14518]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**: #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudioSQL-MAC-Feb2021;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#WCAG2.4.3;#Keyboard;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio
Version: 1.26.1
Mac OS Version: Big Sur Version 11.2.2

### Repro Steps:

1. Launch the application-Azure Database Project and install extension SQL Database Projects.
2. Tab till SQL Database Project Home Screen with heading "Projects".
3. Tab till "Create New Project" button or "+" button and hit enter.
4. Fill out every field and click "ok" button.
5. A popup will appear
6. Navigate inside the popup and hit tab keys and check where keyboard focus goes.

### Actual:
Keyboard focus goes outside of the popup by hitting tab key

Issue observed with shift + tab key also.

### Expected:
Keyboard focus should not go outside of the popup by hitting tab key. Keyboard focus should remain inside the popup.

### User Impact:
Keyboard only users will face difficulty in navigating again in the popup

**Comment by kisantia** [comment]
same as windows issue https://github.com/microsoft/azuredatastudio/issues/14304

**Comment by Swati1700** [comment]
Verified the bug in the environment
Application Name: Azure Data Studio
macOS: Ventura 13.2
Issue is fixed and does not reproduced. Please find the not repro attachment below.
[Screen Recording (5).webm](https://user-images.githubusercontent.com/86710888/220867108-cd3b7399-8ec6-4ed5-91b9-c03d60911a73.webm)

Github Tags:#Closed;
