### ISSUE TITLE
A11y_AzureDataStudioSQL_Project_CreateProjectFromDatabase_Keyboard: Keyboard focus is getting trapped as it is not moving by hitting tab key when keyboard focus is on "cancel" button.

### ISSUE THREAD

**Issue by RohitJadhav-TCS** [microsoft/azuredatastudio#14520]
“[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags**: #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudioSQL-MAC-Feb2021;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#WCAG2.1.2;#Keyboard;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio
Mac OS Version: Big Sur Version 11.2.2

### Repro Steps:

1. Launch the application-Azure Database Project and install extension SQL Database Projects.
2. Tab till SQL Database Project Home Screen with heading "Projects".
3. Tab to connections select your server and connect to it.
4. Few databases will appear under your connection then right click on any database
5. Tab till "Create project from database" and hit enter.
6. Tab to the "Cancel" button and press tab key.
7. Check if focus is moving to next focusable control or not.

### Actual:
Keyboard focus is getting trapped as it is not moving to the next focusable control which is "Select connection" button by hitting tab key when keyboard focus is on "cancel" button.

### Expected:
Keyboard focus should go to the next focusable control which is "Select connection" button by hitting tab key

### User Impact:
Keyboard only users will face difficulty in navigating inside the pane.

**Comment by kisantia** [comment]
same as windows issue https://github.com/microsoft/azuredatastudio/issues/14318

**Comment by Swati1700** [comment]
Github Tags:#Closed;
