### ISSUE TITLE
Connections: Servers not showing connected servers

### ISSUE THREAD

**Issue by ssucher** [microsoft/azuredatastudio#14525]
Issue Type: <b>Bug</b>

"Connections: Servers" section in the upper left is regularly not showing my connected servers in the list.  When I refresh, or reestablish the connection, I can connect and run queries just fine, but the sever doesnt show in the list. 

Azure Data Studio version: azuredatastudio 1.19.0 (4095037f2578c23033867e611e82c13de114ca5a, 2020-06-11T22:03:19.036Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.4.0

</details>

**Comment by Charles-Gagnon** [comment]
@ssucher Do you mean the actual top level servers or the folders underneath each connection? (Databases/tables/etc)?

**Comment by ssucher** [comment]
Both - i expect to see a server and list of folders under each connection here:
![image](https://user-images.githubusercontent.com/18265660/109851462-f06e1800-7c10-11eb-9e06-3441fa8d7a66.png)

**Comment by kburtram** [comment]
Closing due to lack of log information needed to investigate issue.  Please follow steps in above comment if you are still impacted by this issue.
