### ISSUE TITLE
Negative multiplication to 0 returns a -0

### ISSUE THREAD

**Issue by isdataninja** [microsoft/azuredatastudio#14548]
- Azure Data Studio Version:

- Version: 1.26.1 (user setup)
- Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
- Date: 2021-02-24T23:42:55.085Z
- VS Code: 1.48.0
- Electron: 9.4.3
- Chrome: 83.0.4103.122
- Node.js: 12.14.1
- V8: 8.3.110.13-electron.0
- OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1.
`SELECT
	EOMONTH(P.[Transaction date]) AS 'Eff Date',
	P.[Investment Group] AS 'Investment Group',
	'HC' AS 'Position',
	**ISNULL(P.[Amount], 0.0) * -1.0 AS 'HCD',**
	NULL AS 'HCT'
FROM [dbo].[TRANSACTIONS] P
WHERE	[Transaction Effective Date] = '2020-05-31' 
	AND [Investment Group] = 'Contoso'`

Tested this with SSMS and it returns the expected value of 0.

**Comment by alanrenmsft** [comment]
@notyourninja could you please attach a screenshot?
I tried this query: select -1 *0 
and I am getting this:
![image](https://user-images.githubusercontent.com/13777222/110154614-4cfc3f00-7d99-11eb-96c0-949da1a02289.png)


And BTW, what is the `**` for in your query.

**Comment by notyourninja** [comment]
hi @alanrenmsft, 
to clarify this was in using a notebook, please see screenshot here. please disregard the **, that was a slight error in trying to obfuscate the query. 
![2021-03-06 08_45_34-Edit Check Validation ipynb - Azure Data Studio](https://user-images.githubusercontent.com/15051875/110209156-e50d2d80-7e58-11eb-8396-e056918e5d6e.png)

**Comment by alanrenmsft** [comment]
notebook and query editor share the same grid component. For this particular row, what is the actual value of P.[Amount Reporting Ccy]? 
I tried the following query in notebook
`select ISNULL(NULL, 0.0) * -1.0 as 'ColumnA'` but not able to reproduce the issue, I suspect that value is not null.

**Comment by alanrenmsft** [comment]
@notyourninja could you please also try the query I posted?

**Comment by kburtram** [comment]
Closing older issue due to lack of response to previous questions and lack of internal repro.  Please let us know if you're still impacted by this issue.
