### ISSUE TITLE
[Notebook] Kusto Notebook Language Info Metadata is only updated after connecting to a Kusto connection

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#14545]
- Azure Data Studio Version: 1.26.1
- Windows and Mac

**Not a Regression.**

Steps to Reproduce:

1. Created new notebook
2. Changed kernel to Kusto
3. Saved notebook
4. Reopened notebook

Change Kernel and Save:
![StableSaveKusto](https://user-images.githubusercontent.com/23587151/109904968-e79e3600-7c52-11eb-81fb-40d783330bfe.gif)

Change connection to Kusto cluster and save:
![SaveKustoConnection](https://user-images.githubusercontent.com/23587151/109907130-93955080-7c56-11eb-8c93-b5e656a5d4ab.gif)

The language_info only gets updated after a user connects to a Kusto cluster.

**Comment by chlafreniere** [comment]
@VasuBhog is this still an issue?

**Comment by VasuBhog** [comment]
This issue still exists, but I can have a quick fix for this.
