### ISSUE TITLE
Update to supported tags in .sqlproj file to exclude / remove files from build / project view

### ISSUE THREAD

**Issue by malcolm738** [microsoft/azuredatastudio#14544]
**Is your feature request related to a problem? Please describe.**
The ADS extension doesn't support the 'Build Action' option in Visual Studio
So a file listed in the Project will be in the Build, depending on the build option other files in the folder may be included as well

Supporting more than just 
- Folder Include
- Build Include
would allow better visibility of files in the project folders and control what is included in the build

**Describe the solution or feature you'd like**
To manage system build folders with the current **_Folder Include="Properties"_** add
**_Content Remove="bin\ **\ * . *"_** and _**Content Remove="bin\ **\ * . * "**_ to exclude build folders
To allow files to be excluded add support to amend **_Build Include_** to **_None Include_**
If Pre/Post deployment have scripts to be managed via workspace add support for **_Content Remove_** to remove folders from the project

**Describe alternatives you've considered**
Manual edits of the .sqlproj files to allow files to be visible in the project and excluded from build

**Additional context**
The add/remove single file is linked to https://github.com/microsoft/azuredatastudio/issues/14383
Manual changes made when working around https://github.com/microsoft/azuredatastudio/issues/14075

**Comment by kisantia** [comment]
@malcolm738 There is now support for SDK-style projects in ADS and wildcards are supported for SDK-style projects if you'd like to give it a try! To exclude a folder in an sdk style project, add <Build Remove="folder\**" /> to the sqlproj or select "Exclude" on the folder node in the project tree. Please open an issue for any bugs or if there are other scenarios you'd like supported. Thanks!

More info on SDK-style sql projects: https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-build-sql-the-next-frontier-of-sql-projects/ba-p/3290628
