### ISSUE TITLE
Support Sdk="MSBuild.Sdk.SqlProj/1.10.0" in .sqlproj Project setting for standalone build

### ISSUE THREAD

**Issue by malcolm738** [microsoft/azuredatastudio#14542]
**Is your feature request related to a problem? Please describe.**
When doing a cross platform build if the build machine doesn't have access to the '.targets' file then the build will fail

**Describe the solution or feature you'd like**
The MSBuild Sdk for SQLProj, https://github.com/rr-wfm/MSBuild.Sdk.SqlProj , provides an option for the build to work
There are limitations on referenced database (need nuget or import via relevant file path) and Pre/Post deployment scripts need to be single file (':r' import not currently supported)

**Describe alternatives you've considered**
The alternative is to add dependencies to build server, this requires cloning folder
C:\Users\ {user} \ .azuredatastudio\extensions\microsoft.sql-database-projects-0.6.1\BuildDirectory 
from a machine with ADS extension added, this requires a check and update for updates of the extension / patches to the system database dacpacs

**Additional context**
This links to issues with cross platform build and details added to https://github.com/microsoft/azuredatastudio/issues/14075

**Comment by kisantia** [comment]
@malcolm738 an alpha package has been released if you'd like to try it: https://www.nuget.org/packages/Microsoft.Build.Sql/0.1.1-alpha

instructions can be found here: https://github.com/microsoft/DacFx/tree/main/src/Microsoft.Build.Sql

**Comment by kisantia** [comment]
Microsoft.Build.Sql is now public preview! More info: https://techcommunity.microsoft.com/t5/azure-sql-blog/microsoft-build-sql-the-next-frontier-of-sql-projects/ba-p/3290628
