### ISSUE TITLE
Support registering extension type in model view editor

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#1455]
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by llali** [comment]
@AbbiePetcht what's this request? can you please add more info?

**Comment by AbbiePetcht** [comment]
@llali  the extension should be able to add the new type of document and it should be recognized the document type and open the custom editor when the user opens that type of document. 

The current workaround in extension is that when the document is opened, it immediately closes the text document file and reopen with the model view editor.

**Comment by kburtram** [comment]
Closing older engineering focused issues.
