### ISSUE TITLE
Handle concurrent calls in Initialize Books method.

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#14578]
- Azure Data Studio Version:
Version: 1.27.0-insider
Commit: 6ecacd6faa47b8b3c8d96abd4477a983ef583cdf
Date: 2021-03-03T23:32:47.800Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.3.0

When modifying multiple books at the same time, we need to handle concurrent calls, so that when a book gets refreshed it doesn't end in a weird state.

**Comment by chlafreniere** [comment]
@barbaravaldez what's the impact of this bug? I'm not super clear here what can happen.

**Comment by barbaravaldez** [comment]
@chlafreniere actually I thought this would happen rarely, but I could repro twice when moving sections back to back for a while.
The weird state it enters is that it won't load the book completely. I'll put this for March Release

**Comment by chlafreniere** [comment]
Ok. If you can already repro, then let's try to fix it for March if we can, @barbaravaldez. Just wanted to make sure this was a problem that we've been able to see in action 😄.
