### ISSUE TITLE
I cannot access the Accounts section of Azure Data Studio to add a new Azure subscription I created...

### ISSUE THREAD

**Issue by iperez79** [microsoft/azuredatastudio#14580]
- Azure Data Studio Version:

Steps to Reproduce:

1. I clicked on the accounts icon
![image](https://user-images.githubusercontent.com/60801869/110178655-64a0eb00-7dcc-11eb-8ab6-bf1a0de165ad.png)

2. A popup showed I had no linked accounts  (which is strange because I am already connecting with a previous subscription I added a while back) 
![image](https://user-images.githubusercontent.com/60801869/110179459-b9913100-7dcd-11eb-88bf-38d42d73d641.png)

3. After clicking ADD ACCOUNT, I get an error saying I have NO CLOUDS ENABLED
![image](https://user-images.githubusercontent.com/60801869/110179542-d9285980-7dcd-11eb-9b24-49c1aa9787d8.png)

4. I went to Settings and searched accordingly but get no results. 

![image](https://user-images.githubusercontent.com/60801869/110179966-93b85c00-7dce-11eb-9d33-dad44ac4f556.png)

Any help is appreciated. Thanks

**Comment by kburtram** [comment]
@iperez79 could you please check if there are any errors in the "Help->Developer Tools" Console?  Also, which extensions do you have installed?

**Comment by kburtram** [comment]
@iperez79 I saw a similar issue today and deleting %APPDATA%\azuredatastudio resolved the issue with the missing Azure settings.  You could try that, though removing that folder would reset the application state back to 1st-launch.  Please let us know if you see errors in the log files.

**Comment by cssuh** [comment]
Closing this issue for now, we can reopen if more info is added
