### ISSUE TITLE
March 2021 Release Endgame

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#14596]
# March 2021 Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.27

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

[win-user]: https://go.microsoft.com/fwlink/?linkid=2132305
[win-system]: https://go.microsoft.com/fwlink/?linkid=2131971
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2131970
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2131972
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2132306
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2131974
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2131973
Install the latest build of ADS from the link above.

## Scenario Sign Off

Scenario Sign offs have been moved to [this page](https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_testPlans/define?planId=4707&suiteId=4768)

## Partner Sign-offs
- [ ] PGSQL @QingqingYuan2
- [ ] SQL On Demand @BranislavGrbicMDCS 
- [ ] SQL Assessment @alexprotsenko

**Comment by kburtram** [comment]
@cssuh since we tracking this release test sign-off through ADO I don't think we need this issue anymore.

**Comment by alanrenmsft** [comment]
we can leave the RC build link in this issue.
