### ISSUE TITLE
Edit data run & stop buttons don't make sense when SQL pane isn't visible

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1459]
- SQL Operations Studio Version: master 8e234d9b

Steps to Reproduce:
1. Connect to a server and open edit data

Actual behavior: "Run" and "Stop" buttons are visible and it's not immediately obvious what they do (users could think clicking Run cause the changes you've made to be committed)

Expected behavior: An interface more similar to the old version of edit data, at least when the sql pane isn't visible

New interface:
![Default edit data interface showing a run button and a disabled stop button](https://user-images.githubusercontent.com/3758704/40383416-b5f2ab86-5db5-11e8-8615-e48cfc2d916f.png)

Old interface:
![Old default edit data interface showing a disabled stop button and a refresh button](https://user-images.githubusercontent.com/3758704/40383473-d8dbdf64-5db5-11e8-8edc-1cbcbf498584.png)

**Comment by kburtram** [comment]
Closing older issues.
