### ISSUE TITLE
Failure to run queries after short idle time 

### ISSUE THREAD

**Issue by bronthulke** [microsoft/azuredatastudio#14606]
It seems sometimes when I don't do anything in Azure Data Studio for a while (e.g. about 20 minutes), when I next try to run a query it, it gets stuck just saying "Executing query...".  If I hit "Cancel" nothing happens, it doesn't cancel anything.  The connection still shows as connected (it has a green dot on it).

I've experienced this when connecting to a remote Azure SQL Database AND just a local SQL Server Express database.

If I completely close the query tab and create a new one, it seems to work.

ADS Version: 1.26.1
Operating System: Windows 10

**Comment by cheenamalhotra** [comment]
From the description it seems related with intellisense blocking issue recently fixed in the [insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build.
I will close this issue as resolved, please re-open if you experience it again.
