### ISSUE TITLE
Content is lost if editing in both rich text mode and split view mode

### ISSUE THREAD

**Issue by encimita** [microsoft/azuredatastudio#14610]
Issue Type: <b>Bug</b>

- Open the attached notebook (rename BEFORE.txt to BEFORE.ipynb: 
[BEFORE.txt](https://github.com/microsoft/azuredatastudio/files/6108330/BEFORE.txt))
- Select the markdown cell containing the subtitle "### Pointers", double click to edit
- Change the cell view to Split view
- On the left side of the cell (the markdown one, not the preview one), select all the text from the beginning of the cell up until the subtitle "## Symptoms" excluded
- Right click and Cut
- Select the markdown cell containing the subtitle "## Context", double click to edit
- Stay in the Rich Text view, go to the last line and press enter twice (once goes to a new bullet point, twice goes to a newline without bullet point)
- Now, switch to Split view
- Go to the last line in Split view (notice: the newline you just made seems to have disappeared!)
- From the last line, hit enter twice to get an empty line, and then the cursor on the following line
- Paste the text you copied
- Save and close the notebook

Expected: my changes are visible
Actual: my changes are not visible, if you open the file with notepad you can see they are wrongfully added to the metadata of the cell instead (see attached notebook AFTER.txt, rename it to AFTER.ipynb [AFTER.txt]:(https://github.com/microsoft/azuredatastudio/files/6108329/AFTER.txt))

Notice: at some point during my testing I could even break my notebook (meaning Azure Data Studio would no longer open it and say it was not valid), but I could not make a small example for it.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (8 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (17.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|Mic|0.4.0

</details>

**Comment by lucyzhang929** [comment]
Hi @encimita, thank you for the detailed steps. This issue is fixed in Azure Data Studio Insiders (which can be downloaded here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and will also be available in our next release (1.27).
Note: The other issue you mentioned around new lines disappearing is tracked here https://github.com/microsoft/azuredatastudio/issues/12904

Feel free to reopen this issue if there are further questions.
