### ISSUE TITLE
Issue Reporter dialog is blank

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#14623]
- Azure Data Studio Version: `1.27.0 RC`

Steps to Reproduce:

1. Open Issue Reporter

Expected: Dialog renders

Actual: Dialog is blank.  No exception in the output console.

![image](https://user-images.githubusercontent.com/599935/110525481-7aaef400-80c9-11eb-9fb5-4167b7ab82b2.png)

**Comment by chlafreniere** [comment]
@kburtram I see that this was merged. Can we close this issue?
