### ISSUE TITLE
Notebook navigation buttons sometimes don't show

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14628]
RC1/main

This seems to happen more in RC1/main although I was able to see it in 1.26 as well so seems like it might not be a full regression.

1. Open BDC 2019 book
2. Click the `Troubleshooters` section link
3. Click the `TSG101` link

Expected : `Previous` and `Next` buttons appear

Actual : No buttons

No errors in the console either

**Comment by barbaravaldez** [comment]
I checked back to September 2020 Release and it seems that when opening a notebook from a link the navigation buttons won't show.
