### ISSUE TITLE
Error when connecting to SQL Server

### ISSUE THREAD

**Issue by yunghk** [microsoft/azuredatastudio#14621]
- Azure Data Studio Version:
Version: 1.26.1 (user setup)
Date: 2021-02-24T23:42:55.085Z
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
1. Open ADS
2. New connection: Microsoft SQL Server
3. Enter credentials, <default> database, connect
4. Double-click on Server explorer

Server connection keeps on loading and do not expand the server explorer as expected.

Error log using DevTools:
`
ERROR TypeError: Cannot read property 'height' of undefined
    at T.getTableHeight (explorerWidget.component.ts:187)
    at ...
`

Error Log File: [-1615315349888.log](https://github.com/microsoft/azuredatastudio/files/6110745/-1615315349888.log)

**Comment by kburtram** [comment]
@yunghk the error appears to be coming from the Manage dashboard.  Specifically one of the input box references is undefined.  Is there anything noteworthy about this server?  e.g do you have permissions to access, etc.  

Do you know if other servers are working properly in the tool?  If not, you may try uninstall/reinstall in case something broke during installation.

Also, as a possible workaround, if you click on the Expander arrow '>' next to the server name in Server Explorer, it will try to expand the connection metadata without opening the dashboard.  That may allow you to do other work not involving dashboard until we can identify & fix.

**Comment by yunghk** [comment]
@kburtram I don't have full permission on this server, but i tried connecting to a specific Database, that i have full permission, and the Explorer didn't work too. 

I have noticed that i can do queries normally when connected to this last database, but when left-click in Manage, the Database Properties tab don't show anything but the loading icon.

**Comment by m4th13u79** [comment]
I installed v1.26 this morning and I have the same problem. I can execute query but when I try to manage the Database it doesn't work. I just have a loading spinner.

I got the following warning/errors in the console : 
[renderer1] [warning] Could not find ServerInfo for connection f3e5f0a8-5cf8-4d09-97f6-b0e32f558851 when updating icon
[renderer1] [error] Error rendering widget explorer-widget {}

**Comment by kenvanhyning** [comment]
Holding this in ask mode for April - need to see if we can get a solid repro and a fix this week.  Otherwise we will move to May.

**Comment by alanrenmsft** [comment]
I will take a look at this one.

**Comment by alanrenmsft** [comment]
I have coded a PR for the error message reported in the issue description: https://github.com/microsoft/azuredatastudio/pull/14981.

but I don't think it is causing the server explorer to stop working. I tried to connect using a user with the 'public' server, I am able to connect and expand the server tree.

@yunghk and @m4th13u79  , could you please provide more detailed information:
1. what type of the SQL Server are you connecting to, if SQL Server on Prem, what is the version?
2. what server roles and permissions does your user have?

**Comment by alanrenmsft** [comment]
closing since there is no response.
