### ISSUE TITLE
Cannot open query plan

### ISSUE THREAD

**Issue by strelok1** [microsoft/azuredatastudio#14632]
- Azure Data Studio Version:
Version: 1.26.1
Commit: 796abbdf5fdd341e3528e30a6b777c93e115eb02
Date: 2021-02-24T23:37:01.966Z
VS Code: 1.48.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

- Steps to Reproduce:

1. Open any Sql Query plan exported by SSMS 18
2. Query plan doesn't open

Error in notification
Unable to open 'Query Plan': Cannot read property 'getBoundingClientRect' of null.

Devtools output:

  | onDidChangeNotification | @ | notificationsAlerts.ts:36
-- | -- | -- | --
  | (anonymous) | @ | breadcrumbsModel.ts:294
  | fire | @ | event.ts:570
  | addNotification | @ | notifications.ts:204
  | notify | @ | notificationService.ts:94
  | doHandleOpenEditorError | @ | editorGroupView.ts:1024
  | (anonymous) | @ | editorGroupView.ts:931
  | async function (async) |   |  
  | (anonymous) | @ | editorGroupView.ts:931
  | doShowEditor | @ | editorGroupView.ts:931
  | doOpenEditor | @ | editorGroupView.ts:931
  | openEditor | @ | editorGroupView.ts:888
  | openEditor | @ | editorService.ts:516
  | onEditorOpening | @ | editorReplacerContribution.ts:74
  | open | @ | untitledTextEditorInput.ts:21
  | onGroupWillOpenEditor | @ | editorService.ts:516
  | (anonymous) | @ | editorService.ts:109
  | fire | @ | event.ts:570
  | openEditor | @ | editorGroupView.ts:888
  | openEditor | @ | editorService.ts:516
  | openResources | @ | window.ts:570
  | async function (async) |   |  
  | openResources | @ | window.ts:570
  | onOpenFiles | @ | window.ts:506
  | async function (async) |   |  
  | onOpenFiles | @ | window.ts:506
  | (anonymous) | @ | window.ts:162
  | emit | @ | events.js:228
  | onMessage | @ | electron/js2c/renderer_init.js:115

<img width="1445" alt="image" src="https://user-images.githubusercontent.com/2357295/110558850-515c9980-8197-11eb-9648-dccb3efd5500.png">

**Comment by alanrenmsft** [comment]
@kburtram I tried this in previous stable builds, the issue is not new. did we ever support visualize the query plan file? my understanding is we should just treat this file as a normal text file, please confirm.

**Comment by alanrenmsft** [comment]
also, doesn't seem to be an ASK mode issue, I am going to move this out to April milestone. sounds good? @kburtram
