### ISSUE TITLE
Group items in side panel by schema.

### ISSUE THREAD

**Issue by ahartman89** [microsoft/azuredatastudio#14645]
Issue Type: <b>Feature Request</b>

I'd like the tree view/object explorer/side bar to group items by schema.

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19042

**Comment by kburtram** [comment]
Thanks for opening this issue.  We're tracking this enhancement with https://github.com/microsoft/azuredatastudio/issues/7.  Closing as duplicate.
