### ISSUE TITLE
Temporal Table drop is failing in Schema Compare Apply 

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#14655]
- Azure Data Studio Version:

Steps to Reproduce:

1. Compare a schema with temporal table to one without it
2. try to genrate script or apply
3. the oder of drop steps seems to be
- remove sys versioning
- dop anything depepndent on the table
- drop the table

order should be

- dop anything depepndent on the table
- remove sys versioning
- drop the table

The current order is causing script to fail. Seems like a dacfx fix for similar temporal issue uncovered this new flow issue. 

use the attached dacpac (deploy to a db) as target and empty db as source
[MyDemoProjectTest.zip](https://github.com/microsoft/azuredatastudio/files/6119483/MyDemoProjectTest.zip)

**Comment by kisantia** [comment]
@udeeshagautam @ssreerama moving this to May release to give more time for this to be fixed in DacFx since code complete for April release is tomorrow

**Comment by ssreerama** [comment]
Sure that would be good. Also, this has been completed and merged to the DacFx Dev :)

**Comment by kisantia** [comment]
fixed by https://github.com/microsoft/azuredatastudio/pull/15344
