### ISSUE TITLE
Failed to start SQL Tools Service

### ISSUE THREAD

**Issue by rajeshpandeyji** [microsoft/azuredatastudio#14669]
Issue Type: <b>Bug</b>

After upading to my mac to new update of mac big sur 11.2.2, i am unable to open Azure Data Studio and even after recent update to 11.2.3 issue is not resolved.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:37:01.966Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|8.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
Closing due to lack of logs.  Please let us know if you are still encountering and have additional logs to share.  Thanks!
