### ISSUE TITLE
db project messy diffs when sqlproj edited in Visual Studio

### ISSUE THREAD

**Issue by joshbooker** [microsoft/azuredatastudio#14674]
It appears certain edits in the Project Applet (ie: add file, add reference) cause the .sqlproj file to be re-written and there is an extra space on many lines.  This becomes a problem if/when the project is edited in Visual Studio which doesn't add the extra space.  

This makes for messy diffs in source control.  

Interestingly, ADS doesn't add extra space on lines I've edited manually such as those having `<SupressTsqlWarnings>` in the image below.

![http://joshbooker.github.io/ADS-projdiffs2021-03-11134151.png](http://joshbooker.github.io/ADS-projdiffs2021-03-11134151.png)

Thanks for listening.

**Comment by kisantia** [comment]
in the last release we changed the behavior in ADS to add whitespace at the end of self closing tags since that's what Visual Studio does https://github.com/microsoft/azuredatastudio/pull/13805. We can consider making this a configurable setting if that would be helpful.

**Comment by joshbooker** [comment]
thanks Kim for your reply.  I must have had it backwards.  I noticed this sometime ago in VS then saw it again today so it was the new release rather than an ongoing discrepancy.  As long as the tools do it the same way, my needs are met. case closed.  

Thanks again for all your hard work.  We're really loving the ADS Project tooling.

**Comment by kisantia** [comment]
Ok I'll close this issue then. Feel free to open again if it would be useful to have this as a configurable user setting. 

Thanks for the feedback! :)
