### ISSUE TITLE
Database dropdown styling issue with extra long database names

### ISSUE THREAD

**Issue by zijchen** [microsoft/azuredatastudio#14676]
Azure Data Studio Version: 1.26.1

Steps to Reproduce:

1. Create and build a database project
2. Publish project -> select a server
3. Database dropdown dialog is misaligned:
![image](https://user-images.githubusercontent.com/13544267/110855557-5ee35380-826b-11eb-8dc6-b6892dae7d1a.png)

This only seems to be an issue when there are very long database names. Example when database names are short:
![image](https://user-images.githubusercontent.com/13544267/110855654-84705d00-826b-11eb-807e-9b2720c9f640.png)

**Comment by alanrenmsft** [comment]
Hi @zijchen , Could you please try the latest insider build? I am not able to reproduce the issue anymore.
![image](https://user-images.githubusercontent.com/13777222/115317106-92997f00-a12f-11eb-8c96-9ff0b13be848.png)

**Comment by alanrenmsft** [comment]
please reopen if you still see the pop up menu shows up at random place on the screen.

**Comment by zijchen** [comment]
I can verify that this is fixed in latest Insider build. Thanks Alan!
