### ISSUE TITLE
Markdown editing causes notebook file corruption

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#14678]
- Azure Data Studio Version: 1.26

A notebook was edited repeatedly and it seems that the closing ] bracket of got misplaced. 
<img width="414" alt="image" src="https://user-images.githubusercontent.com/29285871/110859138-d6b37d00-826f-11eb-8ed1-6fb0cb0d17ac.png">

**Comment by MaddyDev** [comment]
Duplicate of #14481
