### ISSUE TITLE
Option to display a list of connections & servers on the right hand side

### ISSUE THREAD

**Issue by devlern** [microsoft/azuredatastudio#14694]
Please provide an option to display a list of connections & servers on the right hand side just like in a browser you can move developers tools from left to right, it would be great for the AZ Studio to have this flexibility as well

Thanks!

**Comment by Charles-Gagnon** [comment]
You can actually do this already! Right click on the side bar and select `Move side bar right` 

![image](https://user-images.githubusercontent.com/28519865/110970973-24cb8d80-830f-11eb-80a2-711e27647d0c.png)

**Comment by Charles-Gagnon** [comment]
(There's also a `Toggle Side Bar Position` command that can be ran from the command palette to accomplish the same thing)
