### ISSUE TITLE
Welcome page doesn't update layout correctly when maximized/unmaximized

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14699]
1.26.1/main

1. Open welcome page
2. Resize ADS window so it's small enough that the content is laid out in a vertical column
2. Maximize ADS
3. Unmaximize ADS

The Welcome page content is now cut off at the bottom. Manually resizing the window at this point will update the layout and cause it to be resized correctly.

![image](https://user-images.githubusercontent.com/28519865/110979727-d66fbc00-8319-11eb-8919-1210ca33d585.png)

**Comment by kisantia** [comment]
not able to repro on the latest insiders
