### ISSUE TITLE
Welcome page preview link doesn't show on small window widths

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#14700]
1.26.1/main

1. Open the welcome page
2. Resize ADS to a smaller width

The "Preview" text/link at the top right will move off to the right and not be visible - the only way to get it back is to increase the window size again. 

![WelcomePage_Preview](https://user-images.githubusercontent.com/28519865/110980053-441be800-831a-11eb-90e5-943d158ef902.gif)

**Comment by kisantia** [comment]
Preview was removed from welcome page in https://github.com/microsoft/azuredatastudio/pull/18280
