### ISSUE TITLE
ADS Insiders Update Install bug

### ISSUE THREAD

**Issue by wallig1** [microsoft/azuredatastudio#14703]
- Azure Data Studio Version: Insider

Steps to Reproduce:

1. Accepted update lastest version of ADS Insider
2. I interrupted the install
3. When I went back into ADS Insider I got this
![image](https://user-images.githubusercontent.com/71532375/110986178-30747f80-8322-11eb-9b26-de6279b71d3f.png)
4. Cannot go back into ADS - not sure if I need to delete and reinstall

**Comment by Charles-Gagnon** [comment]
At this point you'd need to reinstall - just running the installer again should fix any issues. Let us know if it doesn't!
