### ISSUE TITLE
Notebooks: Result table columns are squished after saving notebook with chart

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#14719]
- Azure Data Studio Version: 1.27 RC build
(not a regression)

Steps to Reproduce:

1. Run query in notebook code cell that returns table with multiple columns
2. Click on chart option
3. Save notebook
4. Close and reopen notebook (chart is shown)
5. Click table option
6. Table columns will be squished
![Screen Shot 2021-03-12 at 2 34 22 PM](https://user-images.githubusercontent.com/23462877/111005825-645e9d80-8340-11eb-98ba-82b6166ab122.png)

**Comment by chlafreniere** [comment]
No longer reproes:

<img width="1544" alt="image" src="https://user-images.githubusercontent.com/40371649/165627004-e7605ac3-cb92-4aba-89cc-e20c223a1f1f.png">

Closing as a result. We've made enhancements since this was opened around grid enhancements.
