### ISSUE TITLE
Wizards and dialogs should support custom width

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#1471]
I need to make the dialog bigger than it's default size so it should have an small/big option or let setting custom width

**Comment by kburtram** [comment]
We should have a set of supported widths and the Wizard API should allow the extension to choose.  Probably `large` and `small` is sufficient.

**Comment by MattIrv** [comment]
@llali  No, there's no way to set it wide or thin when making a wizard or dialog from an extension right now. It's already supported in the backend code though so it should be pretty quick to wire through if that's all we need. Custom widths might be a bit more difficult

**Comment by kburtram** [comment]
Closing since we don't currently have a use-case requiring this new extensibility option.
