### ISSUE TITLE
Absolute poor PowerShell usage training material

### ISSUE THREAD

**Issue by cadayton** [microsoft/azuredatastudio#14725]
Issue Type: <b>Feature Request</b>

Absolute poor PowerShell usage training material.

All of the "How To blogs" that I have reviewed are fundmentality useless in doing anything meaningful with Azure Data Studio.  Most suffer from going from 0 to 60 in 2 seconds rather than taking a baby steps approach to presenting the detail.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19042

**Comment by kburtram** [comment]
@cadayton thanks for opening this issue.  I don't have context on which blogs you're referring to.  Could you please provide a couple example links?  The issues on this repo are mainly tracking product bugs and feature requests, but we may be able to forward this feedback to the correct owner with more context.

**Comment by cadayton** [comment]
@cadayton.  I was just commenting in general about the collection of blogs in the wild that didn't do much justice to get started with Azure Data Studio.  There more of a show off of here is what I've done vrs here is how accomplished X using Y.

**Comment by Charles-Gagnon** [comment]
Are you referring to the Powershell extension in ADS or just general powershell terminal usage?

If it's the powershell extension I would suggest filing a request on their repo : https://github.com/PowerShell/vscode-powershell (we use the same VSIX as VS Code)

**Comment by kburtram** [comment]
Closing as out of scope.  We don't track improvements to this content on this repro.  Please see if there is a place to provide feedback whether the problematic content is hosted.  I don't really have context on what is being referred to specifically here.  Thanks!
