### ISSUE TITLE
Notebook - Ability to see and edit links in WYSIWYG mode

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#14724]
**Is your feature request related to a problem? Please describe.**
User wants to see what link was created when in WYSIWYG mode. 

**Describe the solution or feature you'd like**
Consider Display Text in WYSIWYG that has underlying markdown `[Display Text](URL)` ... 

When users are using WYSIWYG mode: 
1. Users can select the _Display Text_ that has been associated to some _URL_, and click on the Link button, then show the current values for both **Text to display** and **Address** (currently only shows **Text to Display** value). Changing the **Text to display** and **Address** values, will update the _Display Text_ and the _URL_. 
2. Users can place a cursor in the middle of the_Display Text_, and click on the Link button, then show the current values for both **Text to display** and **Address** (currently only shows **Text to Display** value). Changing the **Text to display** and **Address** values, will update the _Display Text_ and the _URL_. 

![EditLinkWYSIWYG](https://user-images.githubusercontent.com/6405919/111052294-7c045780-840e-11eb-9b57-50bb36b916e7.gif)

**Describe alternatives you've considered**
Switch to Markdown

**Additional context**
Teams has a way to do this

**Comment by chlafreniere** [comment]
Merged into release/1.28.
