### ISSUE TITLE
Tab Confusion

### ISSUE THREAD

**Issue by glennoleum** [microsoft/azuredatastudio#14728]
Issue Type: <b>Feature Request</b>

The current tab is indistinguishable from other tabs. I find myself closing all tabs so I know where I am.

Please change the appearance of the current tab.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19041

**Comment by abist** [comment]
@glennoleum Thanks for opening the issue. The current tab always has a darker background compared to other tab backgrounds. Is there something else you're suggesting here?

**Comment by alanrenmsft** [comment]
closing, no reply after 7 days. @glennoleum please reopen when you getting a chance to reply to @abist 's question above.
