### ISSUE TITLE
[WYSIWYG] Add a link to a section

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#14734]
Adding a link to a section works, until the code cell is modified then the link is replaced by workbench html.

Expected result:
`[Code](#code)`
Result: 
`[Code](..\AppData\Local\Programs\Azure%20Data%20Studio%20-%20RC1\resources\app\out\vs\code\electron-browser\workbench\workbench.html)`

- Azure Data Studio Version:
Version: 1.27.0-rc1 (user setup)
Commit: 3368af9371f777338a7318e3c746f3dca390396d
Date: 2021-03-15T06:07:09.474Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
Steps to Reproduce:

1. Create a code cell
2. Add a link in WYSIWYG, using the link button
3. Exit the cell
4. Re-enter the cell and update it.
5. The link has been changed for a workbench html.

**Comment by chlafreniere** [comment]
Merged into release/1.28.
