### ISSUE TITLE
add account

### ISSUE THREAD

**Issue by RussellSmithGit** [microsoft/azuredatastudio#14730]
Issue Type: <b>Bug</b>

When I trie to add a connection, and use Universal with MFA support.  I select "Add account" it launches a browser (localhost:###) but the site claims connection is not secure.  and cannot proceed.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.21332

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.91GB (16.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.2.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@RussellSmithGit the AAD login redirect is opened as HTTP connection.  Some browsers have a setting that will auto-redirect HTTP to HTTPS, so you can likely workaround the issue by modify the URL in the web-browser to force the connection to HTTP.  Alternatively, there is a setting to switch to "Device Code" authentication in the User Settings (try searching for Device Code).  I think that auth method does not require a redirect to localhost.

@cssuh any other suggestions of what to do here?

**Comment by cssuh** [comment]
@RussellSmithGit Yes, please give the device code method a try.  You should be able to select it after selecting "Add Account" under the accounts view.  Also, what web browser are you using?

**Comment by dcottam** [comment]
I have the same issue at present and found that whilst I can create a new account connection via "Device Code" when the token expires it is not refreshing via the "Device Code" but trying to open the "localhost" page and failing. My workaround is to copy paste the URL into IE and it's able to authenticate and proceed.

**Comment by cheenamalhotra** [comment]
Closing as external
