### ISSUE TITLE
extremely long wait time connecting to saved servers or executing simple queries and high system memory use

### ISSUE THREAD

**Issue by Olga-B** [microsoft/azuredatastudio#14737]
Issue Type: <b>Bug</b>

hello this is happening consistently regardless of which server I connect to using either Recent or Saved connections 

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (0.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.2.0
powershell|ms-|2020.4.0
sql-prompt|Red|0.2.6

</details>

**Comment by abist** [comment]
@Olga-B Thanks for opening the issue. Could you please elaborate the problem you're facing? What happens when you try to connect using Recent or Saved connections?

**Comment by Olga-B** [comment]
@abist Sorry for the delayed response. 
It depends. Often it just hangs indefinitely. 
Just now, I tried opening a new querying editor and connecting to a server using a recent connection and it's been "connecting" for 5 minutes. During that time I've opened a new query editor in SSMS, connected to the same server and ran use to connect to a staging db and then a simple select top 10 from a table. After another ten minutes or so, I got the following connection error from ADS: "TypeError: Cannot read property 'connectionProfile' of undefined"

**Comment by Olga-B** [comment]
I just tried connecting using a saved connection instead of a recent one and got the following error this time (log file attached):
```An unexpected error occurred while connecting. Please [file an issue](command:workbench.action.openIssueReporter) with the title 'Unexpected Error Occurred while Connecting' and include the log file [C:\Users\OBlyumin\AppData\Roaming\azuredatastudio\logs\20210316T111806\renderer1.log](command:workbench.action.openLogsFolder)```
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/6151066/renderer1.log)

**Comment by cssuh** [comment]
Hi @Olga-B, what authentication method are you using to connect to these DBs?

**Comment by Olga-B** [comment]
@cssuh Authentication Type is "SQL Login"

**Comment by Olga-B** [comment]
fwiw, the frequency of this issue comes and goes with no changes on my end. sometimes it is happening constantly with every new connection or after running one or two queries shortly after opening a connection. other times much more sporadically.

**Comment by gsimardnet** [comment]
I also get problems where a simple query that should take less than one second to run may take several seconds before I get the result. I can do the same thing in SSMS and it's much faster there.

**Comment by cheenamalhotra** [comment]
This issue has been addressed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), updated here: https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1692517196
Closing as resolved.
