### ISSUE TITLE
Unable to open 'SQLQuery_1 - sqldev...grated)': Maximum call stack size exceeded.

### ISSUE THREAD

**Issue by Chutneypot89** [microsoft/azuredatastudio#14744]
- Azure Data Studio Version:

Steps to Reproduce:

1. Run following query until complete

declare @cnt int = 1
while @cnt <= 130000
begin
print @cnt
set @cnt = @cnt + 1
end

2. Open a new Query tab window

3. Return to the first query window, that is when you will receive the following error:
    "Unable to open 'SQLQuery_1 - sqldev...grated)': Maximum call stack size exceeded."

4. Also it will erase the SQLQuery_1 text
![Azure Data Studio](https://user-images.githubusercontent.com/80746789/111277372-0df3a680-8641-11eb-95f2-991f7b97e0c1.PNG)

**Comment by NavtejSaini-MSFT** [comment]
@alanrenmsft Please help us with this issue as this has been raised on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/questions/314719/index.html) as well and Cx is blocked here.
Let us know if we need to get some info from Cx.

**Comment by alanrenmsft** [comment]
@NavtejSaini-MSFT sure, let me try to repro it.

**Comment by NavtejSaini-MSFT** [comment]
@alanrenmsft Were you able to test this?

**Comment by alanrenmsft** [comment]
not yet, I will give it a try this week.

**Comment by alanrenmsft** [comment]
@NavtejSaini-MSFT I am able to reproduce it, I will investigate it.

**Comment by alanrenmsft** [comment]
@NavtejSaini-MSFT BTW, Azure Data Studio issues should be tracked in this repository, I think you should close the ticket on Microsoft Q&A.

**Comment by NavtejSaini-MSFT** [comment]
@alanrenmsft There is no closure of issues on Microsoft Q&A but I would love to post the resolution for other people. I thank you for checking the issue.

**Comment by alanrenmsft** [comment]
@NavtejSaini-MSFT @Chutneypot89 I have a PR out to fix the issue.

**Comment by Chutneypot89** [comment]
Thank you, did you receive the same error codes when you reproduced the issue?

**Comment by Chutneypot89** [comment]
Thank you

**Comment by alanrenmsft** [comment]
the changes are merged, it will be in tomorrow's insider build https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release.
