### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#14742]
Issue Type: <b>Bug</b>

Attempt to connect to previously working saved connection. It will not connect, and give the error message "Connection canceled" with no further details.

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:37:01.966Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@waltersblake do you see any exception in the "Help -> Toogle Developer Tools" Console?  Or anything else that could help us repro this bug?

**Comment by waltersblake** [comment]
Hi,

This ended up being a server firewall issue. I could not seem to get much helpful feedback from Azure Data Studio, so tried in SSMS and got an error message that helped to fault find it.

**Comment by kburtram** [comment]
Closing based on previous resource.  ADS should give the similar connection error messages as SSMS since we're both using the same client driver.  This is apparently not the case so we'll take a look at what could be happening here.
