### ISSUE TITLE
After executing a schema compare

### ISSUE THREAD

**Issue by pauldj54** [microsoft/azuredatastudio#14746]
- Azure Data Studio Version: 1.26.1
Steps to Reproduce:

1. Open a database project
2. Open the schema compare
3. Select as source the database project and as target the Azure Synapse Provisioned Pool as target
4. Run "compare"

Results:
![image](https://user-images.githubusercontent.com/706754/111319371-34780880-8666-11eb-8420-cfee05ab2a58.png)

Connection to the database works. I was able to create a new project from this database.

**Comment by kisantia** [comment]
looks like same issue as #14107
