### ISSUE TITLE
Create an Azure Arc data controller in the Azure portal - Provisioning Notebook Namespace Input

### ISSUE THREAD

**Issue by demoolya** [microsoft/azuredatastudio#14745]
- Azure Data Studio Version:
Version: 1.27.0-insider (user setup)
Commit: 9df7c6c1aa78e90ec084a66f5b4901d86c579387
Date: 2021-03-15T05:46:24.739Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Generate provisioning notebook for Azure Arc data controller with the steps mentioned in https://docs.microsoft.com/en-in/azure/azure-arc/data/create-data-controller-resource-in-azure-portal?view=sql-server-ver15
2. In the step 4 while configuring environment variables it asks for the namespace for Arc data controller, the Note for this input is quite long due to which the input box is not visible clearly. Image below.
![image](https://user-images.githubusercontent.com/54091686/111293531-5fb32580-866f-11eb-8e98-09d506a93dd4.png)

3. So instead of using this:

```
while True:
    print("Please enter a namespace.")
    print("\n".join(i for i in namespaces))
    namespace = input(f"Namespace (Note: Enter an existing namespace without data controller created or a new namespace name. If the namespace doesn't already exist, an attempt will be made to create it first.) : ")
    NAMESPACE = namespace.strip()
    if len(NAMESPACE) != 0:
        dc = !kubectl get datacontroller -n {NAMESPACE}
        if len(dc[1::]) == 0:
            clear_output(wait=True)
            break
        else:
            print("The namespace you entered has data controller created already.")
    clear_output(wait=True)
    print("Invalid namespaces.\n")
```

4. We can use something like the following for better user experience:

```
while True:
    print("Please enter a namespace.")
    print("\n".join(i for i in namespaces))
    print("Note: Enter an existing namespace without data controller created or a new namespace name. If the namespace doesn't already exist, an attempt will be made to create it first.")
    namespace = input(f"Namespace  : ")
    NAMESPACE = namespace.strip()
    if len(NAMESPACE) != 0:
        dc = !kubectl get datacontroller -n {NAMESPACE}
        if len(dc[1::]) == 0:
            clear_output(wait=True)
            break
        else:
            print("The namespace you entered has data controller created already.")
    clear_output(wait=True)
    print("Invalid namespaces.\n")

```

**Comment by Charles-Gagnon** [comment]
Thanks for the suggestion @demoolya! The Notebook in question is actually going to be replaced with a link that will open the Deployment wizard in ADS directly - so I'm going to close this since that should be happening before too long and this isn't blocking any scenarios.
