### ISSUE TITLE
In ADS on a Mac:  Unable to load profile file

### ISSUE THREAD

**Issue by WorldFootballLeague** [microsoft/azuredatastudio#14754]
- Azure Data Studio Version:
NOTE:  This error occurred on a Mac running ms sql server in a docker container.  I was able to use the same process on a windows machine (running ms sql server natively) without error.

Steps to Reproduce:
1. Open a sqlproj in ADS
2. Make sure you have a sql server running locally with a db you can deploy to
3. After updating the db name, intial catalog, user name, and password, save the text below as dev.publish.xml
4. Right-click the project and choose publish
5. Click the folder icon in the dialog and browse for the dev.publish.xml file created in step 4
6. app will prompt to connect to sql server
7. toast at bottom right will show "unable to open profile file".

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetDatabaseName>Database_Name</TargetDatabaseName>
    <DeployScriptFileName>Script.database.sql</DeployScriptFileName>
    <TargetConnectionString>Data Source=(LOCAL);Initial Catalog=NAMEOFDATABASE;User id=USER;Password=TYPEPASSWORDHERE</TargetConnectionString>
    <ScriptDatabaseOptions>True</ScriptDatabaseOptions>
    <BlockIncrementalDeploymentIfDataLoss>False</BlockIncrementalDeploymentIfDataLoss>
    <PublishDependentProjects>False</PublishDependentProjects>
    <ProfileVersionNumber>1</ProfileVersionNumber>
    <SingleUserMode>False</SingleUserMode>
    <BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>
    <DropObjectsNotInSource>False</DropObjectsNotInSource>
    <DropStatisticsNotInSource>False</DropStatisticsNotInSource>
    <DropExtendedPropertiesNotInSource>False</DropExtendedPropertiesNotInSource>
    <DropPermissionsNotInSource>False</DropPermissionsNotInSource>
    <DropRoleMembersNotInSource>False</DropRoleMembersNotInSource>  
  </PropertyGroup>
</Project>

**Comment by kisantia** [comment]
@WorldFootballLeague can you share the contents of the publish profile to repro this (without the connection info of course)? 

I was able to load this simple publish profile: 
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <IncludeCompositeObjects>True</IncludeCompositeObjects>
    <TargetDatabaseName>targetDb</TargetDatabaseName>
    <DeployScriptFileName>DatabaseProject1.sql</DeployScriptFileName>
    <TargetConnectionString>Data Source=***;User id=***;Password =***;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Connect Timeout=60;Encrypt=False;TrustServerCertificate=True</TargetConnectionString>
    <ProfileVersionNumber>1</ProfileVersionNumber>
  </PropertyGroup>
  <ItemGroup>
    <SqlCmdVariable Include="ProdDatabaseName">
      <DefaultValue>defaultProdName</DefaultValue>
      <Value>prodname</Value>
    </SqlCmdVariable>
  </ItemGroup>
</Project>
```

**Comment by WorldFootballLeague** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns=http://schemas.microsoft.com/developer/msbuild/2003>
  <PropertyGroup>
    <TargetDatabaseName>Database_Name</TargetDatabaseName>
    <DeployScriptFileName>Script.database.sql</DeployScriptFileName>
    <TargetConnectionString>Data Source=(LOCAL);Initial Catalog=NAMEOFDATABASE;User id=USER;Password=TYPEPASSWORDHERE</TargetConnectionString>
    <ScriptDatabaseOptions>True</ScriptDatabaseOptions>
    <BlockIncrementalDeploymentIfDataLoss>False</BlockIncrementalDeploymentIfDataLoss>
    <PublishDependentProjects>False</PublishDependentProjects>
    <ProfileVersionNumber>1</ProfileVersionNumber>
    <SingleUserMode>False</SingleUserMode>
    <BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>
    <DropObjectsNotInSource>False</DropObjectsNotInSource>
    <DropStatisticsNotInSource>False</DropStatisticsNotInSource>
    <DropExtendedPropertiesNotInSource>False</DropExtendedPropertiesNotInSource>
    <DropPermissionsNotInSource>False</DropPermissionsNotInSource>
    <DropRoleMembersNotInSource>False</DropRoleMembersNotInSource>
  </PropertyGroup>
</Project>

**Comment by kisantia** [comment]
looks like there were just quotes missing on the second line around "http://schemas.microsoft.com/developer/msbuild/2003". I was able to load the profile on mac after adding those. The error message in SSDT actually said what was wrong, so I will work on improving the error message in ADS.

**Comment by WorldFootballLeague** [comment]
Thanks.

**Comment by WorldFootballLeague** [comment]
Even if I quote the line indicated, I still get “cannot open profile file.”  Now I get the error on the Windows machine too.  The example you sent me failed.  I do not have a prod variable set up.  And, I need the switches below.

<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TargetDatabaseName>Database_Name</TargetDatabaseName>
    <DeployScriptFileName>Script.database.sql</DeployScriptFileName>
    <TargetConnectionString>Data Source=(LOCAL);Initial Catalog=NAMEOFDATABASE;User id=USER;Password=TYPEPASSWORDHERE;</TargetConnectionString>
    <ScriptDatabaseOptions>True</ScriptDatabaseOptions>
    <BlockIncrementalDeploymentIfDataLoss>False</BlockIncrementalDeploymentIfDataLoss>
    <PublishDependentProjects>False</PublishDependentProjects>
    <ProfileVersionNumber>1</ProfileVersionNumber>
    <SingleUserMode>False</SingleUserMode>
    <BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>
    <DropObjectsNotInSource>False</DropObjectsNotInSource>
    <DropStatisticsNotInSource>False</DropStatisticsNotInSource>
    <DropExtendedPropertiesNotInSource>False</DropExtendedPropertiesNotInSource>
    <DropPermissionsNotInSource>False</DropPermissionsNotInSource>
    <DropRoleMembersNotInSource>False</DropRoleMembersNotInSource>
  </PropertyGroup>
</Project>

**Comment by kisantia** [comment]
@WorldFootballLeague sorry the example I sent was meant to just show the format I was requesting for sharing the publish profile. I was able to repro the error and looks like it's because of the semicolon at the end of the target connection string. If there's no semicolon before </TargetConnectionString> the profile will load successfully. I have opened a bug to track fixing this #14789

**Comment by kisantia** [comment]
@WorldFootballLeague were you able to verify if this worked? I made the fix and it will be in the next release of the sql database projects next month.

**Comment by WorldFootballLeague** [comment]
Thanks for contacting me.  I’m working with a Mac user on this issue and he has not had the time to get with me today.  I will update you as soon as I can.

**Comment by kisantia** [comment]
@WorldFootballLeague just following up on if you heard back from the user and if we can close this issue.

Thanks,
Kim

**Comment by WorldFootballLeague** [comment]
The user is so frustrated that he has, I believe, abandoned trying to update his database locally.  If he recovers enough to try again, I will let you know the outcome.  Closing the issue seems to be the most appropriate course right now.

Thanks.

**Comment by kisantia** [comment]
ok thanks I will close this then. Assuming the semicolon was the issue, the fix will be in the release next month.
