### ISSUE TITLE
Connect to azure sql database from script in git repo on Azure DevOps

### ISSUE THREAD

**Issue by FransGer** [microsoft/azuredatastudio#14762]
Issue Type: <b>Bug</b>

Connect to azure sql database from script in git repo on Azure DevOps

Azure Data Studio version: azuredatastudio 1.26.1 (796abbdf5fdd341e3528e30a6b777c93e115eb02, 2021-02-24T23:42:55.085Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8171M CPU @ 2.60GHz (4 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off_ok<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (12.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by abist** [comment]
@FransGer Thanks for opening the issue! Could you please elaborate on the problem you're facing? Are you trying to query a database which fails?

**Comment by FransGer** [comment]
@abist Yes, I have a script that is sitting in a Git repo from Azure DevOps.
When I open a normal file and try and connect the DB in question, it works fine, but as soon as I try and open the script from the local repo and try and open the same connection it gives me this error.

Hope this is enough info to go on, if you need more please let me know :-)

![image](https://user-images.githubusercontent.com/48481773/111528070-5dcd8d00-8769-11eb-994f-4f6358b3c056.png)

**Comment by Charles-Gagnon** [comment]
@FransGer Apologies for the delay - it seems like you have a `%20` in the path to the file. I fixed an issue with that in the last release, could you try updating to 1.29+ and let us know if you still are seeing this problem?
