### ISSUE TITLE
sql projects "open containing folder" not working correctly

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#14760]
Version: 1.27.0

If you have multiple projects open, doing "open containing folder" on the different projects won't bring you to the correct file in file explorer or finder.

The correct uri is getting passed through the command to fileActions.contribution.ts. Looks like this got broken in the latest vscode merge. Right clicking on a file in the file explorer viewlet and doing "reveal in finder/file explorer" still works correctly.

**Comment by Charles-Gagnon** [comment]
@kisantia Since the VS Code merge might still be a bit away you could bring over the fix early if you wanted to as well - seems like a small enough one that it should be fine
