### ISSUE TITLE
Sluggish Interface/Scrolling When Viewing Large Data Sets

### ISSUE THREAD

**Issue by m82labs** [Microsoft/azuredatastudio#1477]
- SQL Operations Studio Version:
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
On a reasonably busy system run:
```
SELECT  TOP(100)
        *
FROM    sys.dm_exec_cached_plans
        CROSS APPLY sys.dm_exec_query_plan(plan_handle)
```
Operations Studio slows down substantially, and scrolling becomes very jerky. 

This is on a modern laptop:
i7-6820HQ @ 2.70GHz
16 GB of memory

**Comment by kburtram** [comment]
Another note is that the repro also makes tab switch really slow.

**Comment by anthonydresser** [comment]
We've made improvements in this area. Reopen if you continue to see issues in this area.
