### ISSUE TITLE
Notebook-results of code cell cannot be cleared if the file is saved with results

### ISSUE THREAD

**Issue by donkeyhit** [microsoft/azuredatastudio#14785]
1, Open the notebook, and run some cells. The result will be shown below the cell. If I click save, the output will be saved. 
2, Then, even I click "Clear results" button, the output is not displayed, but the "outputs" content is still in the file. 
3, close this file and open the file again, the results of previously running the cell will be shown
4, these results can never be cleared in ADS

**Comment by lucyzhang929** [comment]
Hi @donkeyhit, which version of ADS are you using? I am unable to repro this issue on the latest version (1.27)

**Comment by donkeyhit** [comment]
Hi Lucy,

I am using 1.26.1. Not sure if that is the reason. But I have one file that
I cannot clear the results.

**Comment by lucyzhang929** [comment]
Can you update to the latest version of ADS and try clearing the results?

**Comment by chlafreniere** [comment]
Closing since we need a bit more info here. Feel free to reopen if this is still occurring. Thanks!
