### ISSUE TITLE
SQL SERVER AGENT extension not appearing in 'Manage'

### ISSUE THREAD

**Issue by johnalbertginete** [microsoft/azuredatastudio#14786]
Issue Type: <b>Bug</b>

To reproduce the bug:
1. Install SQL Server Agent extension into Azure Data studio
2. Reload as necessary
3. Go to Servers or DB, right-click, then click Manage
4. You'll see that the new extension SQL Server Agent does not appear in any of the tabs

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:18:54.187Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
What kind of server are you connecting to? The Agent tab won't show up if it's an Azure, SQL On Demand or if the connection is to a specific DB (it needs to be a top-level server connection)

**Comment by abist** [comment]
@johnalbertginete Also make sure you have the preview settings switched on in the user settings for Agent to show up.

**Comment by johnalbertginete** [comment]
Thanks for your responses @Charles-Gagnon and @abist!

I am connecting to an Azure SQL Server so I guess that's the reason why it does not appear?
Also, I confirm that my 'Preview Settings' is switched on.

Below is a screenshot of my settings. It's strange that the SQL Server Agent does not appear in the 'Extensions' section.
![image](https://user-images.githubusercontent.com/48909968/111736964-b9a72b80-88b9-11eb-935b-f6ab12feb9b6.png)

**Comment by Charles-Gagnon** [comment]
SQL Agent is a feature that's only available for On-Prem and Managed Instance servers, so unfortunately if you're using a SQL Azure server then you won't be able to use this feature. 

https://docs.microsoft.com/sql/ssms/agent/sql-server-agent

As for why it doesn't show in the extensions section - that's because it doesn't have any extension-specific settings. The view you're looking at is just for settings and so if an extension doesn't have any settings specific to it then it won't have a section there.
