### ISSUE TITLE
diagram is not showing bars for values with decimal point

### ISSUE THREAD

**Issue by KelchnerK** [microsoft/azuredatastudio#148]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. create select with count and percentage
2. create diagram for visualization
3. count is shown in diagram percentage is not shown

the problem is not the mixture, when the result consists only of values with decimal seperator than nothing is shown - maybe only a problem in regions where the decimal seperator is a comma.

**Comment by kburtram** [comment]
Cleaning up old issues.  I'm going to close this as "won't fix" for now since we don't plan to address in the next few milestones.
