### ISSUE TITLE
Extension not compatible with sqlops version fail to install but doesn't show a clear message

### ISSUE THREAD

**Issue by llali** [Microsoft/azuredatastudio#1480]
- SQL Operations Studio Version:

Steps to Reproduce:
Install an extension that's not compatible with the installed sqlops 

Expected: installation should fail with "not compatible error" 
Actual: installation fails with general error and actual error in logged in the console

**Comment by alanrenmsft** [comment]
this has been fixed in my recent changes, user will be see an error notification if there is a compatibility issue.
