### ISSUE TITLE
Postgres Server Parameters Page does not show expectation

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#14803]
When running edit command from server parameters page, exit code was not caught. Pop up notification states instance has been updated which is inaccurate. 

<img width="676" alt="uncaughtexception" src="https://user-images.githubusercontent.com/69922333/111833696-c45cc300-88af-11eb-89d0-ddf6e25e24c1.PNG">

**Comment by Charles-Gagnon** [comment]
Is this a consistent repro? Do you know what caused it? (for repro/debugging purposes)

**Comment by nasc17** [comment]
> Is this a consistent repro? Do you know what caused it? (for repro/debugging purposes)

Specifically in this case it is being cause by the incorrect argument for engine version: server edit -n pgt1 --engine-settings allow_system_table_mods="On",archive_mode="always",array_nulls="Off",autovacuum="Off",authentication_timeout="66",autovacuum_analyze_scale_factor="0.15" **--engine-version postgresql**
This is happening when running from source not the ADS release ( was appearing previously not sure for the same error). It is possible it is because of how the error is being classified.

**Comment by Charles-Gagnon** [comment]
Gotcha, thanks. I'll take a look at this one since it seems like a more general problem with the azdata extension. I'll let you know if I need any other information.

**Comment by nasc17** [comment]
> Gotcha, thanks. I'll take a look at this one since it seems like a more general problem with the azdata extension. I'll let you know if I need any other information.

I just checked it on the compute and storage page and that catches the same error just fine. I am pretty sure it is something specific with this dashboard.
