### ISSUE TITLE
fix the tenant list in add account dialog

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14808]
the tenant list is not correctly implemented, it is not showing anything and has wrong size.
use tab key to navigate to the remove button (shown in screenshot below)
![image](https://user-images.githubusercontent.com/13777222/111848003-47d5de80-88c7-11eb-8f53-c0eb36b6a565.png)

and now press tab key, you will get to the blank screen and the account list disappeared.
![image](https://user-images.githubusercontent.com/13777222/111847792-d138e100-88c6-11eb-9d27-0b50ad30db3c.png)

please either remove the tenant list or fix it.

**Comment by dlindblom** [comment]
Can we have proper tenant list implemented? As today Data Studio does not work when having multiple tenant under same account, and especially with MFA enabled

**Comment by cssuh** [comment]
This has since been fixed, so closing.
