### ISSUE TITLE
Licensing question for master.dacpac files in this repository

### ISSUE THREAD

**Issue by jmezach** [microsoft/azuredatastudio#14825]
**Is your feature request related to a problem? Please describe.**
This is more a question than a feature request and isn't necessarily a problem.

**Describe the solution or feature you'd like**
As the author of [MSBuild.Sdk.SqlProj](https://github.com/rr-wfm/MSBuild.Sdk.SqlProj/) I've been receiving quite a few questions (ie. rr-wfm/MSBuild.Sdk.SqlProj#64) as to whether our users can reference objects in the `master` databases of their respective SQL Server installations. For that to work they need the `master.dacpac` of the appropriate SQL Server version. So far the answer has been to have people create their own NuGet package containing that `master.dacpac` which they can then reference in their project. Although that works fine, it is quite a hassle for folks to have to build and host their own NuGet package somewhere to make this work.

Recently it has been brought to my attention that the `master.dapac` of various versions of SQL Server are available within this repository (see https://github.com/microsoft/azuredatastudio/tree/main/extensions/sql-database-projects/BuildDirectory/SystemDacpacs). It would be greatly beneficial for our project to be able to include these `.dacpac` files in our NuGet package so that our users don't have to create a package themselves. Unfortunately it seems that this isn't allowed from a licensing standpoint since the license of this repository clearly states:

> You may not sublicense the Software Code or any use of it

**Describe alternatives you've considered**
We do have a workaround now where users create their own NuGet package, but that isn't ideal. Another possibility could be that we depend on Azure Data Studio with the SQL Server Database Projects extension be installed on the developers machine. However, that would also require it to be installed in CI/CD scenario's, which is what `MSBuild.Sdk.SqlProj` is geared towards for that most part in the first place.

**Additional context**
I've already tried to reach out to various people, such as @dzsquared, to see if there's something that can be done here, but since I'm thinking of adding this repo as a submodule I figured I might as well post an issue here to see what people think.

**Comment by abist** [comment]
@udeeshagautam This seems like a question for SQL projects, so you might have some idea here

**Comment by dzsquared** [comment]
@jmezach Am I understanding correctly that the system dacpacs are needed in CI/CD pipelines for build validation of objects that use system objects? I'm checking again into the ability to alter the licensing on the dacpacs but I'm also wondering if there's an alternative of changing the build logic.

**Comment by jmezach** [comment]
@dzsquared Yes, that is one of the primary motivations behind `MSBuild.Sdk.SqlProj` to allow CI/CD of database projects without the need to have Visual Studio with SQL Server Data Tools installed on your build agent and also so that you can do CI/CD cross-platform (ie. on Linux/Mac).

Personally I'm not usually referencing system objects from my database projects, but I can understand why people would want to do that and obviously it is possible with the old SQL Server Data Tools database projects (.sqlproj).

Of course we could change the build logic, but the core problem is that we'd need to get the `master.dacpac` (and probably `msdb.dacpac` as well) from somewhere during CI. Ideally I'd like to not depend on something that needs to be installed on the box as that usually leads to problems down the road.

I guess we could work around the licensing issue if there was a Microsoft owned NuGet package that would include these. We could then simply have our users add a `<PackageReference>` to that package and it would just work (probably with some special casing for that package in `MSBuild.Sdk.SqlProj`).

**Comment by dzsquared** [comment]
The system dacpacs are now available in independent nuget packages - https://www.nuget.org/packages/Microsoft.SqlServer.Dacpacs
