### ISSUE TITLE
Rich-Click Manage Database not populating charts/widgets

### ISSUE THREAD

**Issue by janszedc** [microsoft/azuredatastudio#14822]
Using the latest build of Azure Data Studio.  
![image](https://user-images.githubusercontent.com/49908138/112026261-6547ba00-8b0c-11eb-9e18-771e9125a690.png)

When right-clicking on a **server** and selecting 'Manage' both the Database Size (MB) and Search widget populate correctly.  However, when right-clicking on a **database** and selecting 'Manage', nothing populates in the dashboard.

![image](https://user-images.githubusercontent.com/49908138/112026010-29acf000-8b0c-11eb-9428-e362f093ae9e.png)

**Comment by janszedc** [comment]
Please delete this issue.  I will re-open the following: https://github.com/microsoft/azuredatastudio/issues/14126

**Comment by alanrenmsft** [comment]
@janszedc what is the type of server you are connecting to?

**Comment by janszedc** [comment]
I was able to fix it by not only reinstalling ADS, but also removing any related files and doing a clean install.  It was something in my settings.json file that was causing the issue in my admin account, but not my normal domain user that I use to sign in to my PC.
