### ISSUE TITLE
Easily Change sort method in Explorer side panel

### ISSUE THREAD

**Issue by brett-x** [microsoft/azuredatastudio#14839]
I normally like the files in the Explorer pane to be sorted by date Modified. But fairly often I need to find a file by its name, or at least what the name starts with. (I sometimes have older versions of the same file that I keep for reference.) 

This request is to Add a button (or other method) in the Explorer view that allows me to change the sort, instead of having to 1) search for the file, or 2) go to Settings and change the sort method. Honestly, right now, I go to my file system instead, which seems like a workaround for a missing feature.

**Comment by kburtram** [comment]
This portion of the product comes entirely from VSCode without any modifications for ADS.  Please log this feature request in vscode repo and we would pick up the update in the future upstream refresh.  Thanks!
