### ISSUE TITLE
Azure AD authenticated user permission change not reflected unless account removed and re-added

### ISSUE THREAD

**Issue by shahiddev** [microsoft/azuredatastudio#14845]
- Azure Data Studio Version: 
Version: 1.27.0 (system setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z (1 wk ago)
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Azure SQL, create users based on AD groups (e.g. Create user [db-readers] FROM EXTERNAL PROVIDER; grant roles as appropriate)
2. Add team member to that group in Azure AD.
3. They connect to DB with ADS using Azure AD authentication and are able to log in and do their stuff 👍 
4. Add the team member to an elevated privilege group (e.g. db writers) in Azure AD
5. Disconnect and reconnect to the Server/DB and try and modify data - fails 👎 
6. AD account has to be removed in ADS and re-added to pick up new permissions.

We are currently manually doing the group membership changes in AD but will be looking at automating this in future so would hope this scenario would work out of the box. 

Are we doing something wrong?

**Comment by shahiddev** [comment]
If someone was able to give me some hints as to how to tackle this I may be able to take a look at this and submit a PR if possible?

**Comment by cheenamalhotra** [comment]
I don't reproduce this issue in latest ADS builds, closing as stale.
Please let us know if you experience the issue in latest insiders builds.

**Comment by shahiddev** [comment]
Hi, I missed the notification that this was being closed. We have been making this work for over years but since 1.43 our workaround isn't working anymore.

This appears to still be a problem in 1.47 and requires us to clear the token cache for the new group permissions to be picked up.
