### ISSUE TITLE
Azure Active Directory - Universal with MFA support never renews grants

### ISSUE THREAD

**Issue by garyamorris** [microsoft/azuredatastudio#14851]
- Azure Data Studio Version: 

Version: 1.27.0 (user setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Add a db connection using Azure Active Directory - Universal MFA support
2. Add user account within the connection
3. Eventually the connection fails with invalid_grant message 
4. Only way to fix is remove Azure user and re-add, even though I'm bounced back to my login it never seems to actually renew the grant

Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2021-03-11T13:11:19.3170000Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2021-03-23T09:26:23.0000000Z'.\r\nTrace ID: 1f3e2556-1ef8-45c6-9fbd-7d8d5d472200\r\nCorrelation ID: 0fd65cfe-73aa-4f08-80bb-bad346f29757\r\nTimestamp: 2021-03-24 10:05:03Z","error_codes":[50173],"timestamp":"2021-03-24 10:05:03Z","trace_id":"1f3e2556-1ef8-45c6-9fbd-7d8d5d472200","correlation_id":"0fd65cfe-73aa-4f08-80bb-bad346f29757","error_uri":"https://login.microsoftonline.com/error?code=50173"}

**Comment by AndreaCuneo** [comment]
Same issue here. No workaround found yet and I cannot work with my databases, so is quite impactful.

I'm looking for some profile folder from where I can remove the previous grants. Any pointers where the folder is?

Version: 1.27.0 (system setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by cssuh** [comment]
https://github.com/microsoft/azuredatastudio/issues/12637 duplicate
