### ISSUE TITLE
Item #512: feature doesn't work with decimal datatype

### ISSUE THREAD

**Issue by mappao** [microsoft/azuredatastudio#14868]
- Azure Data Studio Version: 1.27

https://github.com/microsoft/azuredatastudio/issues/512

Steps to Reproduce:

1. Simply select a dataset from a table with a decimal datatype (I've tried with decimal(18,4)) column and select a cell range. No summary shows on bottom bar

**Comment by alanrenmsft** [comment]
@mappao could you please try the latest ADS 1.28 ?

**Comment by mappao** [comment]
> @mappao could you please try the latest ADS 1.28 ?

Yes, upgraded just now and not working, both on decimal and money datatypes:

![image](https://user-images.githubusercontent.com/23529300/115678318-ade3d480-a351-11eb-916e-238e1f52505b.png)

On float also, when you have decimal numbers:

![image](https://user-images.githubusercontent.com/23529300/115679320-bd175200-a352-11eb-9aac-66eced9906a6.png)

It appears to be related on comma (or maybe decimal separator) presence

**Comment by mappao** [comment]
Another interesting try:

![image](https://user-images.githubusercontent.com/23529300/115690455-5cd9dd80-a35d-11eb-9f26-c30dd05218ca.png)

Cell value on first row is excluded.

**Comment by alanrenmsft** [comment]
this is helpful, we need to handle different decimal points and separators.

**Comment by alanrenmsft** [comment]
@mappao , I tried to create a new server with default language set to German to mimic your scenario, but the default decimal point is still . instead of , do you mind let me know how is your server/login setup?

**Comment by alanrenmsft** [comment]
@mappao I have fixed the issue for the cells that are returned as number/decimal types, for the string typed, there is no reliable way to determine the locale that was used to do the formatting, please open a separate issue if that is really important for you, we will triage and determine the priority for that.
