### ISSUE TITLE
Issue: Big execution plan is not complete so it can't be saved

### ISSUE THREAD

**Issue by jirifa** [microsoft/azuredatastudio#14865]
ADS Version: 1.27.0
OS: Windows 10

Reproducible steps:
1. Write a query with big execution plan
2. Run query with actual plan (CTRL + M)
3. Click on XML ShowPlan
4. It opens new tab with the plan but it is not complete (the plan has 1 row and 2 097 153 columns - I assume, that the limit is 2MB)
5. SentryOne Plan Explorer extension can't process it

Log from developer tools:
[-1616661545038.log](https://github.com/microsoft/azuredatastudio/files/6203194/-1616661545038.log)

Please, raise the limit for plans to more MBs or provide some workaround.

Thanks!

**Comment by alanrenmsft** [comment]
@jirifa after investigation, I found we have a setting to control the max xml char length, you can adjust it based on your scenario:
![image](https://user-images.githubusercontent.com/13777222/115470277-eae18700-a1ea-11eb-94e0-d27bbd99503c.png)
