### ISSUE TITLE
Cant connect to db after opening a new file

### ISSUE THREAD

**Issue by nwicke-pk** [microsoft/azuredatastudio#14873]
Issue Type: <b>Bug</b>

 Whenever I open a .sql file and try to connect to an azure sql database I  get...
 An unexpected error occurred while connecting. Please [file an issue](command:workbench.action.openIssueReporter) with the title 'Unexpected Error Occurred while Connecting' and include the log file [C:\Users\nwicke\AppData\Roaming\azuredatastudio\logs\20210325T104427\renderer1.log](command:workbench.action.openLogsFolder)

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by cssuh** [comment]
Can you please include the log file here?

**Comment by nwicke-pk** [comment]
Log is attached.  I removed some identifying information. 
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/6232006/renderer1.log)

**Comment by cheenamalhotra** [comment]
Closing as inactive
