### ISSUE TITLE
Connecting to server...

### ISSUE THREAD

**Issue by cstyve** [microsoft/azuredatastudio#14879]
Issue Type: <b>Bug</b>

Double click on connection

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2123 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.9.1
server-report|Mic|0.2.3
sql-database-projects|Mic|0.7.1
sqlops-spexecutesql-to-sql|pej|1.0.1
schema-visualization|R0t|0.3.0
sql-prompt|Red|0.2.6
sql-search|Red|0.4.0

</details>

**Comment by cssuh** [comment]
Hi could you please elaborate more on the bug you are facing? How can we reproduce the error you are seeing? Do you get any error messages?

**Comment by cssuh** [comment]
not enough info
