### ISSUE TITLE
Can't see the  Projects viewlet under Explorer

### ISSUE THREAD

**Issue by SQLDataSide** [microsoft/azuredatastudio#14880]
Hi I have installed "SQL Database Projects" in my Azure Data Studio, but I can't see the  Projects viewlet under Explorer, also I tried " Projects: New in the command palette" and I got the message ....

A new workspace will be created and opened in order to open project. The Extension Host will restart and if there is a folder currently open, it will be closed.

.... then I got the error .....
No provider was found for project type with id: ''
Source: Data workspace (Extension)

Please help 
thanks
Nik

**Comment by kisantia** [comment]
Hi Nik, which version of ADS and the sql database projects extension do you have installed?

**Comment by SQLDataSide** [comment]
still cant get it working

I have.............................
Version: 1.25.2 (user setup)
Commit: 4d4917d328ab7a7526817a0f0ef03237a79aa54d
Date: 2021-01-20T22:52:13.492Z
VS Code: 1.48.0
Electron: 9.3.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041
.....................................................................
and for SSMS i have 
.
SQL Server Management Studio						15.0.18142.0
Microsoft Analysis Services Client Tools						15.0.1389.0
Microsoft Data Access Components (MDAC)						10.0.19041.1
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.19041.0
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19041

**Comment by kisantia** [comment]
can you try using the [latest](https://github.com/microsoft/azuredatastudio/releases/tag/1.27.0_release) ADS release and verifying that the latest version of sql database projects extension(0.6.0) is installed?
