### ISSUE TITLE
If I open a new project and no workspace is open but its existing - error occurs

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#14906]
- Azure Data Studio Version:

Steps to Reproduce:

1. have a workspace in a folder names abc.workspace and a abc.sqlproj
2. Open ADS with no project
3. Go through Open existing flow and select project abc.sqlproj 
4. This tries to makes another abc.workspace in same place and fails

Expected: it should be able to reuse the workspace with some notif message.

![image](https://user-images.githubusercontent.com/46980425/113029990-f7ba1000-9141-11eb-9412-72737bd4b13e.png)

**Comment by kisantia** [comment]
no longer an issue after removal of workspaces from this dialog
