### ISSUE TITLE
Cannot read property 'connection' of undefined

### ISSUE THREAD

**Issue by romanyefimets** [microsoft/azuredatastudio#14901]
- Azure Data Studio Version: 1.27.0 (MacOS)

Cannot create a new connection. Clicking new connection produces the error 
"Cannot read property 'connection' of undefined"

Also, cannot chose the Connection Type, clicking the dropdown arrow does nothing. 

![Screen Shot 2021-03-29 at 12 47 14 PM](https://user-images.githubusercontent.com/19218559/112891498-101c2300-908d-11eb-84ff-3f13f9e615b2.png)

Steps to Reproduce:

1. Download and install application 
2. Click New Connection

**Comment by cssuh** [comment]
Hi @romanyefimets, do you see any error messages in the Developer Tools Console? You can check this by going to `Help` -> `Toggle Developer Tools`

**Comment by RHammond2** [comment]
Hi, I've been having this same issue too.

I just checked the Developer Tools Console and am getting the below errors. As a note, I have also fully shut down my computer a couple of times and uninstalled and reinstalled the app.

![image](https://user-images.githubusercontent.com/13874373/116719703-9e3f3e00-a998-11eb-8f96-2612484c5495.png)

**Comment by RHammond2** [comment]
This bug is rendering it so I'm unable to access data at all, is there any status update on this or any workaround that could be used?

**Comment by softcoda** [comment]
I encountered the same error after updating to: v.1.33.0. Apparently, the Azure studio was opening in RESTRICTED MODE by default. I didn't notice the notification at top of the window at once; only after several restarts.

So, change the mode to Trusted. Hopefully, this should solve the problem, as it did for me.

**Comment by kburtram** [comment]
@softcoda thanks for providing that additional context!  We're tracking what appears to be the restricted mode bug at https://github.com/microsoft/azuredatastudio/issues/17535.  I suspect this issue predates that feature, but has the same error stack.  It's strange ADS started in restricted mode without a prompt.  I'll see if we can figure out what's going on there.

**Comment by kburtram** [comment]
I'll close this issue to focus the investigation on this particular exception into a single issue https://github.com/microsoft/azuredatastudio/issues/17535.  Please add any additional related comments to that issue to help consolidate any diagnostic info/workarounds/etc.  Thanks!

**Comment by RHammond2** [comment]
@deltaGPhys this was resolved for me in the June 2021 release and I've not encountered issues since, thank you.
