### ISSUE TITLE
AD Password Change Breaks All Saved Connections

### ISSUE THREAD

**Issue by aarongiust** [microsoft/azuredatastudio#14935]
Issue Type: <b>Bug</b>

I had to change my password on my AD account and now all of my saved connections do not work. It keeps asking me to re-authenticate, takes me out to a web page to log in, after logging in it says I'm good to go, but then the whole cycle starts over once back in Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (20.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
cms|Mic|0.8.0

</details>

**Comment by aarongiust** [comment]
Going to the linked accounts dialog, deleting the account, and then adding it back clears this issue.

**Comment by cssuh** [comment]
#12637 closing for duplicate issue
