### ISSUE TITLE
there is a problem after an update 

### ISSUE THREAD

**Issue by emindemir93** [microsoft/azuredatastudio#14966]
Issue Type: <b>Bug</b>

after last update of azure data studio it cannot load my connections and doesn't understand the language that i use and cannot connect to database

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:18:54.187Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@emindemir93 are you seeing any errors in the "Help -> Toggle Developer Tools" Console?  Have you tried reinstalling ADS (as we haven't see widespread reports of this type of error after upgrade to 1.27.0?

**Comment by emindemir93** [comment]
I did re-install but didn't fix so I download the v1.26.1 after that i update the ADS and now everything is look OK
