### ISSUE TITLE
notebook cell execution never stops if the row count exceeds the max row count

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#14977]
the default max row count for notebook cell output is 5000, as shown in the screenshot below, there are more than 5000 rows returned by the query, when the first 5000 are displayed in the output, the execution status indicator is never updated to completed.

![image](https://user-images.githubusercontent.com/13777222/113621425-74506100-9610-11eb-9759-8bc764b82585.png)

**Comment by chlafreniere** [comment]
No repro for me: 
![image](https://user-images.githubusercontent.com/40371649/114109843-f6e45500-988a-11eb-9ead-1c8dcbe5c538.png)

Moving to May to look further.

**Comment by alanrenmsft** [comment]
@chlafreniere I tried the latest insider on Windows and I can still see the issue

**Comment by alanrenmsft** [comment]
actually, the query returns after 2 min and 36 seconds

![image](https://user-images.githubusercontent.com/13777222/115315775-dc349a80-a12c-11eb-9fed-56b996d1bca8.png)

phew... false alarm

**Comment by chlafreniere** [comment]
@alanrenmsft wow that's interesting. And the query returns much more quickly from the query editor?
