### ISSUE TITLE
sqlpackage.exe feedback

### ISSUE THREAD

**Issue by joshbooker** [microsoft/azuredatastudio#14975]
Where is the correct place/method to provide feedback on the sqlpackage.exe utility?  

For example, it's a known issue that export bacpac fails when there are windows credentials in the database.  Apparently this is by design.  I'd like to suggest the need for an an added option to ignore users\permissions.

ie: https://github.com/Microsoft/azuredatastudio/issues/3337

TIA

**Comment by kisantia** [comment]
sqlpackage/dacfx issues can be opened in the [DacExtensions](https://github.com/microsoft/DACExtensions/issues) repo

**Comment by joshbooker** [comment]
Issue added, please up vote
https://github.com/microsoft/DACExtensions/issues/63
