### ISSUE TITLE
Add refresh button on Projects dashboard

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#15008]
It might be confusing for customers on how to refresh dashboard. As of now, it needs to be reopened.
![image](https://user-images.githubusercontent.com/57200045/113783993-79351380-96e9-11eb-96cf-c5174274241e.png)

Add a refresh button on the toolbar.

**Comment by udeeshagautam** [comment]
@SakshiS-harma please add labels when creating the issues :)

**Comment by udeeshagautam** [comment]
Marking it april since it came from and In-april bug PR comment
