### ISSUE TITLE
When an Object Explorer task times out it breaks Object Explorer

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#1503]
- SQL Operations Studio Version: master 8fce79f

Steps to Reproduce:
1. Try to expand a folder in Object Explorer that times out (after 45 seconds a popup will appear saying it timed out)
2. Try to refresh/expand other folders

Expected behavior: Even if one expand task fails, others are independent
Actual behavior: Subsequent refreshes/expands also fail

I can reproduce this pretty consistently by connecting to Azure SQL DB and trying to expand the Security > Logins folder, which usually times out for me

Workaround: Disconnect and reconnect

**Comment by kburtram** [comment]
Please look at https://github.com/Microsoft/sqlopsstudio/issues/2238 when resolving this issue to make sure that scenario is fixed as well.

**Comment by MattIrv** [comment]
I'll use this to track some of our reliability issues in Object Explorer. A few listed below that I want to look into:
- [ ] Expanding Security > Logins when connected to Azure is very slow and usually times out. The same expansion happens instantly in SSMS. It looks like there are ~1000 logins when this expands so it might be something to do with the amount
- [ ] Once one task in OE times out no other task can ever complete for that connection. To reproduce, expand Security > Logins on Azure, wait for it to time out, and then try to expand a database's Tables folder.
- [ ] When a long-running task is going on it blocks all other tasks. To reproduce, expand Security > Logins on Azure and immediately expand a database's Tables folder. It will spin forever instead of expanding. This might be the same root cause as the previous issue.
- [ ] When your password is unsaved, connecting in OE and filling in the password when prompted causes the connection to move to the bottom of the current group (in general updating any connection by opening the connection dialog, selecting the connection from saved connections, and changing anything causes this behavior)
