### ISSUE TITLE
Insert link in WYSIWYG modifies existing section / header link unexpectedly

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#15043]
- Azure Data Studio Version:
Version: 1.27.0 (user setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

and 

Version: 1.28.0-rc1 (user setup)
Commit: 519012c69002b890cdacc9b5528f8e04231a03c9
Date: 2021-04-07T23:26:03.155Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:
1. Create a working link such as below in markdown mode in a notebook.
`1. [Searching / navigating TSGs](#1-searching--navigating-tsgs)`

2. Edit again using WYSIWYG mode to create a new link using the Copy Path and Insert Link button. The above existing "Searching / navigating TSGs" will get altered to something like this:

`1. [Searching / navigating TSGs](..\..\..\..\..\Users\<username>\AppData\Local\Programs\Azure%20Data%20Studio%20-%20RC1\resources\app\out\vs\code\electron-browser\workbench\workbench.html)`

**Comment by MsSQLGirl** [comment]
@chlafreniere  - I added this as Pri:1 ... 

I'm going to investigate what happens if this is not a header link next.

**Comment by MsSQLGirl** [comment]
Confirmed that this seems to be affecting only those `#` header / section links.

**Comment by VasuBhog** [comment]
I believe that this is similar to this bug that @barbaravaldez issued: #14734 and has a PR currently out: #14950. I will test this specific issue, as it seems anchor links currently get formatted improperly once edited.

**Comment by VasuBhog** [comment]
I can confirm (on Windows) that I was not able to reproduce this issue with Barbara current fix for anchors in WYSIWYG.

**Comment by chlafreniere** [comment]
@MsSQLGirl did you get a chance to test this? Does it still repro in the latest RC builds?

**Comment by MsSQLGirl** [comment]
Fixed and verified on the following build: 
Version: 1.28.0-rc1 (user setup)
Commit: 8c9037fbdfe8d7194a8a75c303fbfad408994642
Date: 2021-04-08T20:27:25.783Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042
