### ISSUE TITLE
Missing row when SQL notebook saves to Excel or csv

### ISSUE THREAD

**Issue by jwatkin** [microsoft/azuredatastudio#15048]
- Azure Data Studio Version: 1.27.0

Steps to Reproduce:

1. Create a new SQL notebook in Azure Data Studio.
2. Create a code cell.
3. Create a SQL query in this code cell that will return at least 1000 rows, I don't know the exact limit. 
4. Examine the result set, specifically row 501.
5. Use the SQL notebook result set controls on top of the result set to save the file as Excel or csv.
6. Open the saved file and look for row 501.
7. You'll see that row 501 from the result set is missing from the file and the file contains one less row than the result set.
8. Copy and paste the same query into a "New Query" window outside of the SQL notebook.
9. Run the query and note row 501.
10. Use this query's result set controls to the side of the result set to save the file as Excel or csv, remember you're not in the SQL notebook anymore.
11. Open the saved file and you'll see that row 501 from the result set is present and the file row count matches the result set row count, which suggests the problem is with SQL notebooks.

This was reproduced on three separate systems, with different random queries, but against the same SQL Server instance: macOS Mojave; Windows 10 running under Parallels; PC hardware running Windows 10 natively.

**Comment by lucyzhang929** [comment]
Hi @jwatkin, thank you for reporting. This issue has been fixed and will be available in the next ADS release (v1.28.0). It is also available now in Insiders which can be downloaded here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main.

**Comment by jwatkin** [comment]
Thank you. I'm sorry I didn't spot that. I had only searched for open issues, not closed ones.
