### ISSUE TITLE
Import extension asking azdata CLI to be installed/updated before startup

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#15045]
- Azure Data Studio Version: 1.28.0-insider

Steps to Reproduce:

1. Install Import extension
2. Press ctrl + I

@Charles-Gagnon This popup shows up when I am trying to start the import extension.

![image](https://user-images.githubusercontent.com/6816294/113984902-71b45e00-9800-11eb-9fed-769eabb39309.png)

After clicking 'Accept', it just gets stuck on this step and flat file service never starts. 

![image](https://user-images.githubusercontent.com/6816294/113985000-8a247880-9800-11eb-80d7-1d1bb373bc33.png)

I believe it has something to do with this commit of yours. https://github.com/microsoft/azuredatastudio/pull/15010

**Comment by Charles-Gagnon** [comment]
This should have nothing to do with the import extension - the azdata extension will display this regardless of any other extensions when there's a new update. It's probably just a timing thing where both extensions are activating at the same time. If you just start up ADS you should see the prompt regardless of whether you start the import wizard or not. 

Where is the import extension getting stuck? Did you verify that it's activating correctly?

**Comment by Charles-Gagnon** [comment]
There was an issue with the download center yesterday that was causing the azdata install to fail on windows - if you try again do you still see the same behavior?

**Comment by Charles-Gagnon** [comment]
Are you sure that you weren't just downloading/installing the Import Service? I just tried it and did see that - and then once the flat file import service was installed it opened the dialog as expected.

```
[Extension Host] 	downloading the package: https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.6/win-x64.zip (at ServiceDownloadProvider.<anonymous> (c:\Users\chgagnon\.azuredatastudio-rc1\extensions\microsoft.import-1.2.0\node_modules\service-downloader\out\serviceDownloadProvider.js:100:29))
```

**Comment by aasimkhan30** [comment]
Closing this issue as it was fixed in PR https://github.com/microsoft/azuredatastudio/pull/15088
