### ISSUE TITLE
SQL Server Profiler will not launch

### ISSUE THREAD

**Issue by bartsipes** [microsoft/azuredatastudio#15064]
- Azure Data Studio Version:
Version 0.29.3
Commit 7099922c35bc3b3e223228c972cc03cee5abbe25
Date 2018-05-04T05:46:24.032Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Install SQL Server Profiler extension (Microsoft.profiler) version 0.11.0
2. Connect to DB
3. Press Ctrl + Shift + P
4. Type 'Profiler: Launch Profiler' and Press enter
5. Error message will appear in bottom right with this message: command 'profiler.newProfiler' not found

**Comment by Charles-Gagnon** [comment]
It looks like you're using a much older version of ADS - please update to the [latest version](https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release) and let us know if it still doesn't work for you.

**Comment by bartsipes** [comment]
@Charles-Gagnon I upgraded to 1.28.0 and that fixed the issue. I had previously just checked with the built in updater but apparently it was so old that the update mechanism no longer worked (was reaching out to https://sqlops-update.azurewebsites.net/api/update/win32-x64/stable/7099922c35bc3b3e223228c972cc03cee5abbe25%20HTTP/1.1).

Thanks!
