### ISSUE TITLE
[Feature] Sql Server Agent- Run From Step ability

### ISSUE THREAD

**Issue by TomJKlug** [Microsoft/azuredatastudio#1507]
Sql Server Agent is looking excellent. Would love to see the functionality to Run from Step on a job. We have multi step jobs that we need to run from a certain step under certain conditions and would love to be able to do it from SQL OPS and not jump box to a windows machine to do the task.

**Comment by abist** [comment]
@kburtram We will have the "Run Job" feature in the Jobs and Jobs History page, but not individual steps. Do we plan to have running individual steps?

**Comment by TomJKlug** [comment]
The run individual steps is what I was referring to, We utilize an agent job with multiple steps and there are times we go in and run from step 10 for instance of a 30 step job. It would be awesome to have that functionality instead of having to go to another tool.

**Comment by kburtram** [comment]
@abist is this still planned for December release?

**Comment by abist** [comment]
@kburtram This is now possible using the `Edit Job` -> `Edit Step` and reordering the steps. We don't have a specific button to start from a specific step. Will try to get that in if we want it that way as well.

**Comment by abist** [comment]
@kburtram Added new PR for direct functionality.
