### ISSUE TITLE
Project dashboard presenting incorrect information

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#15070]
Azure Data Studio Version: 
Version: 1.28.0-rc1 (user setup)
Commit: 1c91f7971e8d4563dca47ab113953b4ad8d59b64
Date: 2021-04-09T00:19:50.442Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create project from "VerifyContainedDBImportExport12892" db.
2. Try publishing the project. It fails but the Deployments table in dashboard shows that it was successful.
![image](https://user-images.githubusercontent.com/57200045/114145104-ece24680-98ca-11eb-9acc-f5072dd543a5.png)

![image](https://user-images.githubusercontent.com/57200045/114145173-fec3e980-98ca-11eb-89ac-8c5e3b3b2a14.png)

**Comment by udeeshagautam** [comment]
merged hence closing.
