### ISSUE TITLE
Schema compare finds differences between sql project created from database and the original database

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#15071]
Steps to Reproduce:

1. Create a project from an existing database. 
2. Perform schema compare between the project's dacpac and the original database.

Expected outcome: No difference
Actual outcome: Tons of differences with "GRANT EXECUTE" on objects.

![image](https://user-images.githubusercontent.com/57200045/114146401-6595d280-98cc-11eb-8836-811480f7ceb2.png)

**Comment by jcoryatjr** [comment]
Any idea what the status of this bug is in the backlog?  I am able to create a dacpac using SSMS with the included GRANTS which gives the expected results in ADS Schema Compare.

**Comment by kisantia** [comment]
Might be related to #19528 and #17789

**Comment by kisantia** [comment]
I found why these grant permissions aren't being added when the project is created from the database. In SSDT, there's an option "Import permissions" that is unselected by default. If that option is checked, then the grant permissions are added to the project and there are no differences when comparing the project to the db.

![image](https://user-images.githubusercontent.com/31145923/194673325-27a74868-2920-46ad-a08f-09a388700488.png)

ADS does not currently have this option exposed in the create project from database dialog, so I'll look into adding it for the upcoming release.
