### ISSUE TITLE
Cannot deselect specific stored procedure from list of changes. Error: "Specified method is not supported"

### ISSUE THREAD

**Issue by maccer83** [microsoft/azuredatastudio#15074]
Issue Type: <b>Bug</b>

1. Make a schema comparison
2. Try to remove a specific stored procedure from the list of actions (Change) by removing the checkmark from the "Include" column.

Expected result: the checkmark is removed

Actual result: The checkmark is removed at first. But after a few seconds, I get an error box with the message "Specified method is not supported" (Source: SQL Server Schema Compare (Extension)). The list of changes updates, and the stored procedure gets ticked again, so there is no way for me to deselect it.
![Specified_method_not_supported](https://user-images.githubusercontent.com/12064302/114213703-9ffe7e80-9963-11eb-8bd1-adfe1b0d250d.png)

This seems to happen only for one out of two databases I try to sync the same stored procedure and same changes with. Both are hosted at at an external web service and should run on the same version of SQL Server, even though they are on different servers.

Is there a log file for the Schema Compare extension operations where I can get more information about the error to help me/you to troubleshoot?

The stored procedure is relatively long, 660 rows, not sure if this can cause problems?

This problem does not occur when syncing against the same database using SSDT in Visual Studio.

Extension version: 1.9.1
Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:18:54.187Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|
</details>

**Comment by kisantia** [comment]
@maccer83 can you share source and target dacpacs that repro this issue(doesn't have to be the exact dacpacs you were seeing this problem with, just sample dacpacs that have the same issue) so that we can repro and debug this?

**Comment by jkylehumphrey** [comment]
I'm also having this issue but mine is when trying to deselect a table.  The console log window is empty and there are no relevant logs in the log directory. 

![image](https://user-images.githubusercontent.com/418102/116928899-aa8ef980-ac2b-11eb-80c3-af8d81def6fd.png)

**Comment by jkylehumphrey** [comment]
> I'm also having this issue but mine is when trying to deselect a table. The console log window is empty and there are no relevant logs in the log directory.
> 
> ![image](https://user-images.githubusercontent.com/418102/116928899-aa8ef980-ac2b-11eb-80c3-af8d81def6fd.png)

I'm comparing MSSQL database to MSSQL database directly.  No dacpac.

**Comment by kisantia** [comment]
I tried comparing AdventureWorks to another database and was able to exclude AdventureWorks tables with the latest insiders build and schema compare 1.10.0. 

Can you use the dacpac extension to extract dacpacs for a source and target that repro this and email them to me at kisantia@microsoft.com?

**Comment by jkylehumphrey** [comment]
> I tried comparing AdventureWorks to another database and was able to exclude AdventureWorks tables with the latest insiders build and schema compare 1.10.0.
> 
> Can you use the dacpac extension to extract dacpacs for a source and target that repro this and email them to me at [kisantia@microsoft.com](mailto:kisantia@microsoft.com)?

I'm not sure I can/should do that.  I can't open the exported dacpac file to verify that sensitive information isn't in it.  This is a client's database.

**Comment by kisantia** [comment]
@jkylehumphrey the dacpac created by the dacpac wizard contains schema only, no data. You can verify the contents by changing the file extension of the dacpac to .zip and unzipping it. Another option is to share only the model.xml from the unzipped dacpacs since that's the schema, which is all that's needed for reproing. 

If you're still uncomfortable with that, please try to create a sample source and target database that repros this issue and share dacpacs from those.

**Comment by jkylehumphrey** [comment]
> @jkylehumphrey the dacpac created by the dacpac wizard contains schema only, no data. You can verify the contents by changing the file extension of the dacpac to .zip and unzipping it. Another option is to share only the model.xml from the unzipped dacpacs since that's the schema, which is all that's needed for reproing.
> 
> If you're still uncomfortable with that, please try to create a sample source and target database that repros this issue and share dacpacs from those.

☝️

**Comment by kisantia** [comment]
@jkylehumphrey if you deploy the dacpacs, does the issue repro for those databases?

**Comment by SakshiS-harma** [comment]
@jkylehumphrey just following up here with Kim's question- did you try deploying the dacpacs? And did that repro the issue for those databases?

**Comment by SakshiS-harma** [comment]
Closing this issue for now, since we didn't hear back on it further. Please feel free to re-open it with more information.
