### ISSUE TITLE
azdata-cli installation fails when invoked from within Azure Data Studio or from command line

### ISSUE THREAD

**Issue by justPaulo** [microsoft/azuredatastudio#15096]
- Azure Data Studio Version: Version: 1.27.0
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:18:54.187Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 20.4.0

Steps to Reproduce:

1. Launch Azure Data Studio;
2. Immediate upon start, Azure Data CLI extension complains that "Could not find Azure Data CLI, install it now? If not then some features will not be able to function."
3. Error is obtained (always): "Error installing Azure Data CLI: Unexpected exit code from command: Error: Cannot install under Rosetta 2 in ARM default prefix (/opt/homebrew)! To rerun under ARM use: arch -arm64 brew install ... To install under x86_64, install Homebrew into /usr/local. (1)"

**Comment by Charles-Gagnon** [comment]
Are you using an M1 ARM-based Mac? The error seems to be from that - could you try following the instructions on this page to install the CLI directly?

https://docs.microsoft.com/en-us/sql/azdata/install/deploy-install-azdata-macos?view=sql-server-ver15

And then if/when you get the same error above as I expect try running `arch -arm64 brew install azdata-cli` instead?

**Comment by justPaulo** [comment]
Affirmative. I already did that a couple of weeks ago and as stated at the top of the article, macOS support is only provided up to 10.15, excluding this way 11.x Big Sur. It looks to me there is already plenty of Microsoft software running on arm64, why not AzData?

Regarding the reference to brew that was also attempted (specifying the target architecture by prefixing the command with "arch -arm64"), the same errors as before:

==> /opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/bin/pip install -v --no-deps --no-binary :all: --ignore-installed /private/tmp/azdata-cli--gssapi-20210412-3257-a5w0fb/gssapi-1.6.12
Last 15 lines from /Users/user/Library/Logs/Homebrew/azdata-cli/112.pip:
    requirement.install(
  File "/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 856, in install
    six.reraise(*exc.parent)
  File "/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/lib/python3.8/site-packages/pip/_vendor/six.py", line 703, in reraise
    raise value
  File "/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/lib/python3.8/site-packages/pip/_internal/operations/install/legacy.py", line 74, in install
    runner(
  File "/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 273, in runner
    call_subprocess(
  File "/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/lib/python3.8/site-packages/pip/_internal/utils/subprocess.py", line 242, in call_subprocess
    raise InstallationError(exc_msg)
pip._internal.exceptions.InstallationError: Command errored out with exit status 1: /opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/tmp/pip-req-build-sfsa10xl/setup.py'"'"'; __file__='"'"'/private/tmp/pip-req-build-sfsa10xl/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/tmp/pip-record-0li4bpvv/install-record.txt --single-version-externally-managed --compile --install-headers /opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/include/site/python3.8/gssapi Check the logs for full command output.
WARNING: You are using pip version 20.2.4; however, version 21.0.1 is available.
You should consider upgrading via the '/opt/homebrew/Cellar/azdata-cli/20.3.2/libexec/bin/python3 -m pip install --upgrade pip' command.
Removed build tracker: '/private/tmp/pip-req-tracker-5va5wyyk'

Do not report this issue to Homebrew/brew or Homebrew/core!

**Comment by Charles-Gagnon** [comment]
I talked with the owners of the azdata CLI and the status currently is that they don't support Big Sur/ARM64 yet but will be looking into that going forward.

As this is an external issue I will close this for now since there's nothing we can do from the ADS side. If I have any updates I'll let you know!
