### ISSUE TITLE
Connection to ADX Kusto cluster does not work

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#15102]
- Azure Data Studio Version:
Version: 1.28.0-rc1 (user setup)
Commit: e1aae951a3f89d4a4bfc91c776f40c9a951cfa14
Date: 2021-04-09T22:38:42.845Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

**Regression**

Steps to Reproduce:

1. Connect to an existing ADX cluster; or help.kusto.windows.net. 
![image](https://user-images.githubusercontent.com/6405919/114465379-e2aa9b80-9b9b-11eb-9b21-d232489816d5.png)

Expected:
It should connect (it works on v1.27)

Actual:
Error message appears and users cannot connect
![image](https://user-images.githubusercontent.com/6405919/114465424-f35b1180-9b9b-11eb-9bdb-1beb5d4a4654.png)

**Comment by JustinMDotNet** [comment]
PR Open
https://github.com/microsoft/sqltoolsservice/pull/1187
