### ISSUE TITLE
Query Database Connection Drop down, change hover cursor

### ISSUE THREAD

**Issue by OzBob** [microsoft/azuredatastudio#15122]
Query new window
Choose different database in SQL Server
Drop down is a text field 
On Mouse Over of Down Chevron, cursor stays 'text', but should be 'pointer'
This will help indicate user can click and the other databases will be displayed as choices.
![image](https://user-images.githubusercontent.com/1796771/114647550-dcd5c700-9d0f-11eb-849a-6b1d532ac03c.png)

**Comment by alanrenmsft** [comment]
this is the default html select box behavior:
https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_select
