### ISSUE TITLE
Clicking on blank area in Connection Dialog Recent list resets all fields

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15132]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Connection Dialog
2. Fill out form with details
3. Click on highlighted back  area

Expected: Focus changes and nothing else

Actual: All the fields filled out in step 2 are reset.  Not a big deal but weird UX bug.

![image](https://user-images.githubusercontent.com/599935/114755079-1e657280-9d0e-11eb-8bd3-35df4e1742f0.png)

**Comment by cheenamalhotra** [comment]
@kburtram 

Is that an OS specific behavior? 
I don't reproduce this issue in Windows. Tested with latest stable 1.40.1

**Comment by cheenamalhotra** [comment]
Closing as issue not reproducible.
