### ISSUE TITLE
Can't connect to SQLMI using MFA Conditional Access

### ISSUE THREAD

**Issue by tspannagel** [microsoft/azuredatastudio#15144]
Hi, 
Since the last update I can't connect to my Azure SQLMIs (SQL DB is working fine however?!)

I click connect, the browser(edge chromium) opens to log in and says "account added. you may close this page now". If i then go back to the azure data studio, i only get spinning circles next to the connection i try to open. No errors or anything. 

If i hit "New query" and then select the connection, i get the following token retrieval error: 
![2021-04-15 08_17_48-SQLQuery_3 - disconnected - Azure Data Studio](https://user-images.githubusercontent.com/3897109/114823609-09e3b180-9dc4-11eb-9b7b-d8316aff679f.png)

Using SSMS i can connect to both SQLMIs using MFA with no issue.

Version: 1.27.0 (user setup)
Commit: 765c7064d46253d88393e0e1ff78874b6fe8fa64
Date: 2021-03-16T21:24:59.168Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19042

[main.log](https://github.com/microsoft/azuredatastudio/files/6315565/main.log)
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/6315566/renderer1.log)
[sharedprocess.log](https://github.com/microsoft/azuredatastudio/files/6315567/sharedprocess.log)
[telemetry.log](https://github.com/microsoft/azuredatastudio/files/6315568/telemetry.log)
[exthost.log](https://github.com/microsoft/azuredatastudio/files/6315570/exthost.log)

**Comment by Charles-Gagnon** [comment]
Was this working in 1.26?

Could you update to the latest release (1.28) and verify if you're still seeing this issue?

And could you also get the console logs as described below?

**Comment by tspannagel** [comment]
Hi Charles, 

yes, this was working in 1.26. I checked the log as above and i think  i found the problem: 

There's a problem with the refresh token not being swapped/overridden after I've changed my password. 

```
  Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2021-01-21T06:20:48.3063862Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2021-03-19T12:45:59.0000000Z'.\r\nTrace ID: 9d530802-8b5e-452c-86a1-069f96e84000\r\nCorrelation ID: 42eaac5f-b6d0-403b-ad38-7579a5a7ac44\r\nTimestamp: 2021-04-19 14:46:37Z","error_codes":[50173],"timestamp":"2021-04-19 14:46:37Z","trace_id":"9d530802-8b5e-452c-86a1-069f96e84000","correlation_id":"42eaac5f-b6d0-403b-ad38-7579a5a7ac44","error_uri":"https://login.microsoftonline.com/error?code=50173"}
  t.log @ console.ts:141
  $logExtensionHostMessage @ mainThreadConsole.ts:27
  _doInvokeHandler @ rpcProtocol.ts:365
  _invokeHandler @ rpcProtocol.ts:365
  _receiveRequest @ rpcProtocol.ts:306
  _receiveOneMessage @ rpcProtocol.ts:174
  (anonymous) @ rpcProtocol.ts:105
  fire @ event.ts:531
  fire @ ipc.net.ts:449
  _receiveMessage @ ipc.net.ts:785
  (anonymous) @ ipc.net.ts:642
  fire @ event.ts:531
  acceptChunk @ ipc.net.ts:191
  (anonymous) @ ipc.net.ts:191
  t @ ipc.net.ts:925
  emit @ events.js:223
  addChunk @ _stream_readable.js:309
  readableAddChunk @ _stream_readable.js:290
  Readable.push @ _stream_readable.js:224
  onStreamRead @ internal/stream_base_commons.js:181
```
