### ISSUE TITLE
Cannot Create Database Project from Azure SQL DB

### ISSUE THREAD

**Issue by nativeTexanATX** [microsoft/azuredatastudio#15162]
- Azure Data Studio Version: 1.28.0

Steps to Reproduce:

1. Connect to an Azure SQL DB
2. Click "Create Project from Database"
3. The "Create Project from Database" side window opens up, "Server" is automatically selected but grayed out; however, "Database" (which is required to continue) only displays "Loading" and spinner is always displayed. Clicking on "Database" shows a dropdown with a "checkmark" next to "Loading" and there is no way to continue.

<img width="379" alt="01" src="https://user-images.githubusercontent.com/56049054/115051522-877def00-9ea2-11eb-9526-cf550e344aa4.png">
<img width="508" alt="02" src="https://user-images.githubusercontent.com/56049054/115051551-8fd62a00-9ea2-11eb-91ad-29cd6592470f.png">

**Comment by SakshiS-harma** [comment]
Hi @nativeTexanATX ... thanks for reporting the issue.
I do see one problem here..
![image](https://user-images.githubusercontent.com/57200045/115061795-7501b680-9e9e-11eb-93b2-650874e69e33.png)
The highlighted connection button here means that the server isn't connected and this is contradictory because the first image shows that the database is connected (or may be it is just stale and got disconnected). Try clicking on the connection button and connect to the server. When the server is connected, it should ideally look like:
![image](https://user-images.githubusercontent.com/57200045/115062438-328ca980-9e9f-11eb-8423-89d9dfe04de6.png)
Once the server is connected, it should be able to load the databases.

**Comment by nativeTexanATX** [comment]
Thank you for the quick reply. 🙌🏻 It appears as though there could be something else going on in the Conncetion. (I've also checked this from both MacOS and from Windows, both running the 1.28.0 of Azure Data Studio.)

1. I can connect, expand the database tree and run queries against the connection (Azure SQL DB):

<img width="1708" alt="01" src="https://user-images.githubusercontent.com/56049054/115094406-03982700-9ee3-11eb-8a97-47eec5eafae4.png">

2. Selected "Create Project from Database" and, as you suggested, clicked on the "connect" icon to reconnect to the database: (I've tried this against the primary and secondary nodes, as well, although in this example, I'm connecting to the primary node.)

Forgive me for erasing all the information here (for safety), but the server name, login, and database name are all populated when I click "Connect", I promise. 😬

<img width="494" alt="02" src="https://user-images.githubusercontent.com/56049054/115094494-65589100-9ee3-11eb-9bf6-a0e4235f30eb.png">

3. Same result as before: the connection succeeds, but the "Database" name is left as "Loading".

<img width="494" alt="03" src="https://user-images.githubusercontent.com/56049054/115094534-891bd700-9ee3-11eb-8092-455c1c7ae950.png">

Same behaviour occurs when trying from Windows.

Versions of both:

<img width="907" alt="Screen Shot 2021-04-16 at 18 44 10" src="https://user-images.githubusercontent.com/56049054/115094790-6ccc6a00-9ee4-11eb-8457-e99b4fc9c25e.png">

<img width="965" alt="Screen Shot 2021-04-16 at 18 45 28" src="https://user-images.githubusercontent.com/56049054/115094800-7655d200-9ee4-11eb-87ab-c04fd3f46d6c.png">

**Comment by SakshiS-harma** [comment]
That is weird. I tried this scenario but it is working as expected for me.
Can you share the console logs?

**Comment by nativeTexanATX** [comment]
Howdy! I've attached the logs (minus any sensitive bits) as requested. 👍🏻

[20210420T091323.zip](https://github.com/microsoft/azuredatastudio/files/6344266/20210420T091323.zip)

In order to generate a concise log, I closed ADS, restarted it (creating a new log folder), connected to the Azure SQL DB, then clicked "Manage" and then "Create Project from Database", repeated connecting to the Azure SQL DB, and once the "Database" was stuck on "Loading", I quit ADS and zipped the logs. (Hope this helps.)

**Comment by nativeTexanATX** [comment]
Howdy and good morning! Now it's my turn to apologize; I was out of town last week, so forgive my delay. 👍🏻

(I've been given db_owner of the target database in question, but I'm not sure about what permissions I have in the "master" database.)

Screenshots are attached, but both Schema Compare and Extract succeeded without issue. (I've used both successfully in the past; and actually, I was looking for a way a while back to turn the DACPAC into a project.)

Schema Compare: (Properties were populated, and the "Database Name" was populated correctly.)

<img width="1998" alt="01 Schema Compare Screen Shot 2021-05-04 at 10 32 05" src="https://user-images.githubusercontent.com/56049054/117030538-5df7fc80-acc5-11eb-9eb5-d8fd67d166c3.png">

Creating the DACPAC: (As above.)

<img width="694" alt="02 Dacpac Screen Shot 2021-05-04 at 10 32 43" src="https://user-images.githubusercontent.com/56049054/117030823-a1eb0180-acc5-11eb-9533-82fbae0cb304.png">

DACPAC Created Successfully:

<img width="799" alt="03 Dacpac Success Screen Shot 2021-05-04 at 10 33 40" src="https://user-images.githubusercontent.com/56049054/117030872-ab746980-acc5-11eb-85b7-502b60c29040.png">

**Comment by lphong** [comment]
Any update on this bug? I think the issue was the extension requires access to master to list databases. If the user doesn't have access, this will not load.

**Comment by SakshiS-harma** [comment]
That is correct. I am able to repro the issue with contained databases (where the user/login isn't present at master level but db level).
I have a fix that will rectify this behavior, but as of now I am getting an upstream error with login failure. I am looking into that and once that is figured out, will send a PR for this.
Thanks for the patience :).

**Comment by SakshiS-harma** [comment]
The above PR fixes the ADS side of issue.
https://github.com/microsoft/azuredatastudio/issues/15629 - created this issue for tracking the backend issue.
