### ISSUE TITLE
Links inserted in split view/MD view are inserted as a list item

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15167]
All current versions of ADS (1.27+, main/insiders)

1. Create new text cell
2. Go to split view/MD view
3. Insert link

Expected : Link is inserted without any additional formatting
Actual : Link is inserted with a preceeding - which causes it to show up as a list item : 

![InsertList](https://user-images.githubusercontent.com/28519865/115057119-821ba700-9e98-11eb-8789-29cc3b76ace1.gif)

Links inserted in WYSIWYG mode do not have this.

**Comment by chlafreniere** [comment]
This is a problem when pressing enter. When using the mouse, this isn't an issue. @Charles-Gagnon in general should the callout be responsible for ensuring that the enter key is captured and propagation is stopped?

**Comment by Charles-Gagnon** [comment]
If the modal is handling the enter key (which I assume it would - triggering the insert button) then yes it should. Is this an issue with the KEY_UP for enter not being stopped and then being caught by the editor?
