### ISSUE TITLE
Run with Parameters doesn't check Notebook kernel

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15170]
Currently we only support Python3 for parameterized notebooks (in terms of the syntax we expect for this to function), but we never check that so users can run a parameterized notebook as any kernel they want and while it may sometimes work generally they'll probably hit some issue along the way. 

We should display an error or even just hide the "Run with Parameters" action when the kernel isn't Python3.

**Comment by VasuBhog** [comment]
Run with Parameters can be used on all Spark kernels, Python Kernel, PowerShell, and the .Net Interactive Kernels as they support the passing of parameters. We can document this to ensure that users who click the run parameters action can learn more Parameterization and ensure we document that we currently are focused on Python kernel parameterization first and will work toward supporting all other kernels as well.
