### ISSUE TITLE
dacpac in model.xml file is replacing \r\n for &#xD;&#xA

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#15194]
- Azure Data Studio Version:

Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

I have all my `ddls` files with a header:

--####################################################################
--# Author:      Developer Name
...
--####################################################################

When I generate the publish script to deploy, found out that some views and stored procedures are going to be updated even though they don't have any change.

After researching I found that in the `dacpac` in the file `model.xml`. Got that the end line characters `\r\n` are being replace by `#xD;&#xA`:

```xml
<Property Name="HeaderContents" Value="--####################################################################&#xD;&#xA;--# Author:      Developer Name&#xD;&#xA ...
```

How can I prevent this issue.

**Comment by kisantia** [comment]
Schema compare has the "Ignore Comments" option that should prevent this. Unfortunately, the dacpac extension doesn't support setting different options. You can also try using [sqlpackage](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver15) and setting the /p:IgnoreComments=true

**Comment by virtualdvid** [comment]
Hi @kisantia good clue!! I was able to add this `<IgnoreComments>True</IgnoreComments>` tag into the `.publish.xml` file. All good. It stopped showing me Stored Procedures or Views when I generate the publish script. It is clean now!! Thanks!!

**Comment by kisantia** [comment]
awesome glad to hear it worked!
