### ISSUE TITLE
Wrap radio button labels in a <label> tag

### ISSUE THREAD

**Issue by paulirwin** [microsoft/azuredatastudio#15205]
**Is your feature request related to a problem? Please describe.**
To make the radio buttons more accessible, radio buttons and their labels should be wrapped in a `<label>` tag. Those with repetitive stress injuries often have difficulty mousing to precise targets, so hitting the radio button directly is more challenging. It is easier to hit a larger target including the entire label, plus this should help with accessibility for screen readers.

**Describe the solution or feature you'd like**
Wrap the `<input>` and `<span>` tags for the RadioButton component in a `<label>` tag. This does not seem to affect the styling at all from my quick test in dev tools.

**Describe alternatives you've considered**
An alternative could be to add an event handler to the `<span>` to check the radio button, but this is extra JavaScript code that is unnecessary, as the HTML engine will do this automatically with `<label>`.

**Additional context**
This mainly affects me on the data-tier application wizard. Clicking on the labels of these 4 options does not select their respective radio buttons:
![image](https://user-images.githubusercontent.com/1874103/115604629-d3fc6c80-a29e-11eb-8297-2210daf7e8da.png)

Here is a modification in dev tools where I manually wrapped the controls in a label tag, which achieves the desired behavior with no visual changes:
![image](https://user-images.githubusercontent.com/1874103/115604880-19209e80-a29f-11eb-924b-3cfca6b6d129.png)

I believe the radioButton.ts constructor code can be changed in this way to accomplish this, but I have not tested this as I have not set up the build environment yet (note the last 4 lines of the constructor changed):
```TS
constructor(container: HTMLElement, opts: IRadioButtonOptions) {
    super();
    this.inputElement = document.createElement('input');
    this.inputElement.type = 'radio';
    this.inputElement.style.verticalAlign = 'middle';
    this.inputElement.style.margin = '3px';

    this._label = document.createElement('span');
    this._label.style.verticalAlign = 'middle';

    this.label = opts.label;
    this.enabled = opts.enabled || true;
    this.checked = opts.checked || false;
    this.onclick(this.inputElement, () => {
        this._onClicked.fire();
        this.checked = true;
    });
    this.inputElement.addEventListener('change', () => {
        if (this._internalCheckedStateTracker !== this.inputElement.checked) {
            this._internalCheckedStateTracker = this.inputElement.checked;
            this._onChangedCheckedState.fire(this._internalCheckedStateTracker);
        }
    });

    // CHANGED CODE:
    const labelElement = document.createElement('label');
    labelElement.appendChild(this.inputElement);
    labelElement.appendChild(this._label);

    container.appendChild(labelElement);
}
```

Also, for what it's worth, I don't believe that the `this.onClick` handler code works as intended.

**Comment by Charles-Gagnon** [comment]
Thanks for the feedback, I agree this seems like an excellent suggestion. @alanrenmsft think you'd have time to take a look?

@paulirwin I'm curious about your last statement - what about the handler do you think isn't working as intended?

**Comment by paulirwin** [comment]
I may have misunderstood the code, it appeared at first to be a click handler for the entire RadioButton widget that would check the radio button input, but upon reviewing it again, it appears like it might be a delegated event that only applies to click on the input element? If so then disregard. My apologies, I can't currently build/debug the app beyond tinkering in dev tools.

**Comment by Charles-Gagnon** [comment]
No worries, what you said is correct. This implementation here is just attaching an onclick event handler to the specified HTML element (in this case the inputElement). This is used to ensure that we fire the correct events for consumers of this widget to receive and that the internal state is kept consistent (since the value can either be changed programmatically through the checked property on the widget or by user interaction through the raw input element we have to maintain our own state to ensure the proper events are fired)

**Comment by alanrenmsft** [comment]
@paulirwin I guess you are using the stable build, I've made similar change a few days back to both checkboxes and radio buttons, so that you can interact with the control by clicking on the text part. this is currently only available in the insider build.

**Comment by paulirwin** [comment]
@alanrenmsft That is correct, I am using the stable build. But I was unable to find a relevant issue to upvote so I filed this one. My apologies if this is a duplicate! :-)

**Comment by alanrenmsft** [comment]
@paulirwin no worries. btw, here is PR: https://github.com/microsoft/azuredatastudio/pull/14965 and the corresponding issue: https://github.com/microsoft/azuredatastudio/issues/14964

I think we can consider this issue as closed now. please feel free to open more issues :-)
