### ISSUE TITLE
Unable to connect .sql files to a sql db

### ISSUE THREAD

**Issue by DIDianGermishuizen** [microsoft/azuredatastudio#15201]
Issue Type: <b>Bug</b>

opened existing .sql file with t-sql commands, connection then to SQL Sevrer fails. When opening a new query on the db it works fine, just for existing .sql files it fails connection. File is in a local git repo

Azure Data Studio version: azuredatastudio 1.27.0 (765c7064d46253d88393e0e1ff78874b6fe8fa64, 2021-03-16T21:24:59.168Z)
OS version: Windows_NT x64 10.0.19042

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
query-editor-boost|dre|0.4.1
gitlens|eam|10.2.1
vsc-material-theme|Equ|32.5.0
rainbow-csv|mec|1.7.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
dacpac|Mic|1.8.0
import|Mic|1.3.0
powershell|ms-|2020.4.0
query-history|Mic|0.1.0
schema-compare|Mic|1.10.0
sql-database-projects|Mic|0.8.2
material-icon-theme|PKi|3.9.2
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
Does the path to the file contain a %20 in it? There's a [known issue](https://github.com/microsoft/azuredatastudio/issues/14044) with those paths.

If this is the case could you try getting the latest [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) and seeing if you still have the issue there? I just checked in a fix yesterday for that.

**Comment by DIDianGermishuizen** [comment]
Hi Charles, 
You nailed it on the head, there was a %20 in my Git Rep directory where the .sql files were stored. 
Renamed the local folder to remove it and now all is working again. 

I did not get a chance to try out the insiders build to see if the bug doesn't exist there, apologies. 

Thank you for the assistance!
I will leave it up to you to close this Issue accordingly.

**Comment by Charles-Gagnon** [comment]
Thanks for the follow up, glad that fixed it! I'll close this issue as a duplicate then.
