### ISSUE TITLE
Object Explorer task didn't complete within 45 seconds.

### ISSUE THREAD

**Issue by jhowe1** [microsoft/azuredatastudio#15204]
Issue Type: <b>Bug</b>

Connect to server/database, expand tables, views or programmability. Times out.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:25:54.683Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (0.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
schema-compare|Mic|1.10.0
sql-database-projects|Mic|0.8.2
sql-search|Red|0.4.0

</details>

**Comment by alanrenmsft** [comment]
most likely this is caused by the server unavailability, does this happen consistently? when this happens are you able to run queries against the same server?

**Comment by abist** [comment]
@alanrenmsft I don't think there's a configuration in the user settings to limit the timing

**Comment by jhowe1** [comment]
Hi this is not server unavailability it's a production azure server and was happening regularly. There is also only about 10 databases on the server. @alanrenmsft , @abist I think what was causing the issue was I had two connections open to the same server, but different databases. I now just have the one connection and seems to be ok. Not sure if you've had similar experiences with other users?

**Comment by jhowe1** [comment]
Closing this as no longer seems to be an issue.
