### ISSUE TITLE
Git Diff freezing whole UI in 1.28.0

### ISSUE THREAD

**Issue by dgee2** [microsoft/azuredatastudio#15209]
Issue Type: <b>Bug</b>

Open folder with git repo
Make change to file
Go to Source Control (Ctrl + Shift + G)
Select file to view diff
Whole Azure Data Studio UI Freezes and never opens diff

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (7.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
azdata|Mic|0.6.3
dacpac|Mic|1.8.0
import|Mic|1.3.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.10.0
server-report|Mic|0.2.3
sql-database-projects|Mic|0.8.2
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.1.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
Is the file you're trying to compare a SQL file?

We have a fix for that in the current insiders build which you can try out - see https://github.com/microsoft/azuredatastudio/issues/15180 for more details.

**Comment by dgee2** [comment]
Yes it was a SQL issue. Thanks for letting me know. I'll give the insiders build a go.

**Comment by dgee2** [comment]
Yes it was a SQL issue. Thanks for letting me know. I'll gthe insiders build.
