### ISSUE TITLE
ADS SQL Database Project unable to build : No such file or directory

### ISSUE THREAD

**Issue by jhowe1** [microsoft/azuredatastudio#15210]
- Azure Data Studio Version: 1.28.0

Steps to Reproduce:

1. Create blank database project 

2. Downloaded latest Mac OS installer 3.1.114 (assuming this is correct) as per https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension?view=sql-server-ver15#net-core-sdk

3. Click either compare or Build

4. stderr: /bin/sh: /usr/local/share/dotnet/sdk/dotnet: No such file or directory

5. This documentation or process needs to be improved. Why can appropriate .net core not be installed with database project extension? This is becoming urgent, a fast response would be greatly appreciated.

**Comment by kisantia** [comment]
can you run `dotnet --list-sdks` and see if the installed 3.1.114 dotnet sdk shows?

**Comment by jhowe1** [comment]
Thanks for your reply, yes I have multiple installed I also tried installing visual studio for mac and .net core through this to see if it would resolve the issue. 
<img width="336" alt="image" src="https://user-images.githubusercontent.com/73300529/115843268-8e62af80-a416-11eb-9e61-e5472d4928cd.png">

**Comment by kisantia** [comment]
Which version of the sql database projects extension is installed? Something else to try is setting the full path to the .net core sdk installation in the settings 
![image](https://user-images.githubusercontent.com/31145923/115911652-341c1b80-a423-11eb-9d2a-b7dff76d6a7b.png)

**Comment by kisantia** [comment]
can you also try building in terminal by running the dotnet command? It would look something like this:
` "/usr/local/share/dotnet/dotnet"  build "/Users/username/SqlProjects/test/test.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="/Users/username/.azuredatastudio/extensions/microsoft.sql-database-projects-0.8.2/BuildDirectory"`

**Comment by jhowe1** [comment]
Hi presumably i'm using latest version, 
<img width="484" alt="image" src="https://user-images.githubusercontent.com/73300529/116070407-8019cb00-a684-11eb-88b3-ab6bddef87de.png">
.net core path was already populated
<img width="305" alt="image" src="https://user-images.githubusercontent.com/73300529/116070557-ae97a600-a684-11eb-84ec-c358b060364f.png">

**Comment by jhowe1** [comment]
Building through terminal succeeded, however through ADS GUI still fails for some reason... 
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/73300529/116072346-dd168080-a686-11eb-8d8f-bc6ad4d76078.png">

**Comment by kisantia** [comment]
Ok thanks for checking. Looks like the problem is the .NET Core path in the settings. Try removing the path or making it '/usr/local/share/dotnet' instead. 

This setting is blank by default and the default path of '/usr/local/share/dotnet' is used in that case. Do you remember setting this path before sometime?

**Comment by jhowe1** [comment]
Ha yes that fixed it! No I don't remember ever setting that... strange... I also deleted and reinstalled ADS recently. Thanks for the help.

**Comment by johnborges** [comment]
In order to get this working for me my path in `settings.json` needed to be: 
```json
{
    "sqlDatabaseProjects.dotnetSDK Location": "/usr/local/share/dotnet/x64/"
}
```
