### ISSUE TITLE
Disable Welcome Screen on Start

### ISSUE THREAD

**Issue by pzelnip** [microsoft/azuredatastudio#15214]
**Is your feature request related to a problem? Please describe.**

Every time I start Azure data studio I'm greeted with the Welcome page, and the first thing I do every single time is close it.  It serves no value to me and just means an extra click every time I start ADS.

**Describe the solution or feature you'd like**
A setting to disable the Welcome screen showing up on startup.

**Describe alternatives you've considered**

I thought `Help: Hide Welcome Tour` was for this, but upon picking that option in the command palette the welcome screen still comes up next time I start ADS.

**Additional context**

N/A

**Comment by Charles-Gagnon** [comment]
You can choose the startup experience through the `Workbench: Startup Editor` setting : 

![image](https://user-images.githubusercontent.com/28519865/115782104-222d7080-a370-11eb-9596-abc2d5c8e250.png)

**Comment by pzelnip** [comment]
Perfect, thank you very much, that was exactly what I was looking for.
