### ISSUE TITLE
Wrong line number in the output

### ISSUE THREAD

**Issue by OSch24** [microsoft/azuredatastudio#15236]
Issue Type: <b>Bug</b>

If I select a line in an SQL script, e.g. line 210, and execute it via F5, the following appears under "Messages". 

14:37:38Started executing query at Line 211
(100 rows affected)
Total execution time: 00:00:00.061

As you can see, it writes "Line 211".
But this is wrong, I marked line 210 and let the script run.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.18363

**Comment by alanrenmsft** [comment]
I can repro the issue, put it in May for now.
