### ISSUE TITLE
The title does not change when the database connection changes

### ISSUE THREAD

**Issue by gaocheng1986** [microsoft/azuredatastudio#15231]
Issue Type: <b>Bug</b>

The title does not change when the database connection changes

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (6.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
sql-prompt|Red|0.2.3
sql-search|Red|0.4.0

</details>

**Comment by gaocheng1986** [comment]
![image](https://user-images.githubusercontent.com/41283904/115987302-13042800-a5e7-11eb-9c97-d8621ce4ad2c.png)

**Comment by gaocheng1986** [comment]
This bug has been around for a long time and has not been fixed

**Comment by alanrenmsft** [comment]
@gaocheng1986 thanks for reporting the issue, this will be fixed in the upcoming release.
