### ISSUE TITLE
Error running command sqlDatabaseProjects.build: Invalid DSP in .sqlproj file.

### ISSUE THREAD

**Issue by virtualdvid** [microsoft/azuredatastudio#15248]
I'm getting this error when I try to build the project in Az Data Studio. I built it successfully on visual studio 2019.

Error running command sqlDatabaseProjects.build: Invalid DSP in .sqlproj file. This is likely caused by the extension that contributes sqlDatabaseProjects.build.

Steps to Reproduce:

1. Bulid project. 

Here my `DSP` tag in `.sqlproj` file   `<DSP>Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider</DSP>`

Wondering what changed. I haven't installed any other software or even an Az Data Studio update in a while.

- Azure Data Studio Version:
Version: 1.28.0 (user setup)
Commit: 13e362762762e5cb76a5c8afd2bc650f48c2d3d8
Date: 2021-04-15T00:24:15.710Z
VS Code: 1.51.0
Electron: 9.4.3
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by kisantia** [comment]
this was a regression exposed in the April release in version 0.8.2 of sql database projects. The fix is checked in and will be updated in insiders soon. Thanks for finding this!

**Comment by virtualdvid** [comment]
I'm using heavily Az Data Studio and Visual Studio 2019. As always I'll report any weird behavior :)

Out of topic, Do you have any news on this [13344](https://github.com/microsoft/azuredatastudio/issues/13344)
The guys in my team using Az Data Studio have to do it manually in the `.sqlproj` file and sometimes they just mess the file lol.

Thanks!

**Comment by kisantia** [comment]
Sql database projects is now updated with the fix in insiders (version 0.9.0 of the extension). 

No new updates on including existing/excluded files, but we will be working on more improvements in the upcoming months.
