### ISSUE TITLE
Extension Gallery Icons missing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15255]
![image](https://user-images.githubusercontent.com/28519865/116321442-eb3fcc00-a76e-11eb-9a1e-916efa6fdf33.png)

**Comment by alanrenmsft** [comment]
@Charles-Gagnon I think this is by design and has always been like this, if you increase the width of the view you will see the icons.

**Comment by Charles-Gagnon** [comment]
Oh hah, interesting. Guess I must have reduced the size of that at some point and assumed that was the default - verified that it does seem to be working correctly now once properly expanded.
