### ISSUE TITLE
Query Result Aggregates

### ISSUE THREAD

**Issue by hiteshdavey** [microsoft/azuredatastudio#15279]
I have been using SQL Server since version 6.5 and one thing I am always missing in SSMS and ADS is EXCEL-like Result aggregates. ADS result pane is not developer-friendly (in other words, it is less productive). As a developer and analyst, I always find it difficult to analyze the data aggregate **at a glance** during development and I end up using other SQL add-ons like Devart SQL Complete & SqlAssistant.

Showing result aggregate is not rocket science. Kindly add a status bar showing result aggregate for select rows/col(s)/cells.
This feature will be more useful to developers than giving too much emphasis on the notebook features.

**Show the following result aggregates (SUM/MIN/MAX/AVG/COUNT/NULL, NOT NULL & DISTINCT counts/ string data length on the status bar or as a tooltip. Provide an option to choose which aggregate function users desire to see.**

Column Sorting and Filtering options will be an added advantage!

Looking forward to seeing this feature working in one of the very near-future releases of ADS!

Kindly requesting MS to give serious consideration to this feature request. Hope the ADS team will hear the user's voice.

**Comment by alanrenmsft** [comment]
😄 the feature you requested were implemented recently, the latest stable has it, but there a few fixes not in it, I'd encourage you to try the latest insider build.

you have to enable the preview features in user settings:
![image](https://user-images.githubusercontent.com/13777222/116754553-c7be9080-a9bd-11eb-998d-556f1bca023c.png)

**filtering/sorting:**
![image](https://user-images.githubusercontent.com/13777222/116754648-f63c6b80-a9bd-11eb-924b-a86888e5b91c.png)

There is a max row count limit for filtering and sorting:
![image](https://user-images.githubusercontent.com/13777222/116754898-5fbc7a00-a9be-11eb-9f8c-12148914bbf1.png)

**selection summary:**
In the status bar, you can see the aggregates for selected cells.
![image](https://user-images.githubusercontent.com/13777222/116754983-88447400-a9be-11eb-9adf-b630706e932c.png)

**Comment by hiteshdavey** [comment]
Hi Alanrenmsft,

I have updated ADS and seen the enhancements. I appreciate the enhancements done BUT what is still missing is...

1. "NULL counts". Let say my query fetched 2k (or more) records and out of this; a couple of cols has some row(s) with null values. It would impossible to know abt null value count unless I explicitly filter that col to check null existence. And applying a filter every time to see if there are null rows is really a cumbersome exercise! It is like looking for a needle in a haystack! So I strongly suggest add NULL counter aggregate along with other aggregates.

2. If I apply a filter on a given col then that col header is clearly showing "filter icon", this gives me a clear indication that given col is filtered but if I sort a col then it supposes to show an AZ-down arrow icon / ZA up arrow icon; otherwise, it is difficult to know which col is sorted by mistake.

3. One-click option to restore result back to original resultset output (without re-running the SQL). This will be handy in case I have a long-running query result and I played around with it and now I want to go back to the initial output.

4. Option to set alternating row/col color.

**Comment by alanrenmsft** [comment]
@hiteshdavey I was going through the selection summary related issues and noticed your comments.
Item 1. I am fixing it in https://github.com/microsoft/azuredatastudio/issues/20913
Item 2. the sort order is already available now
Item 3 and 4 please open separate issues form them.

**Comment by hiteshdavey** [comment]
I also suggest abbreviating "Average" to "Avg"; "Distinct Count" to
"Distinct Cnt"; "Null Count" to "Null Cnt" to save on display space. Also,
it would be a valuable addition if "NotNull Count" is also shown (this
would be really useful when the resulting output is beyond the scope of the
visible screen).
