### ISSUE TITLE
Settings error with connections.sortBy configuration

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15272]
```
workbench.desktop.main.js:1256 Conflict in default settings: Ignoring datasource.connections.sortBy as datasource.connections is []
```

Pretty sure this is because the configuration stuff parses out .'s as being object properties, so by saying a configuration has the name `datasource.connections.sortBy` we're looking for the `sortBy` property in the `datasource.connections` configuration (which we already use as an array of connections so then fails)

We need to use a different name for this to avoid that.

**Comment by Charles-Gagnon** [comment]
@caohai @alanrenmsft FYI, I now seem to recall seeing the behavior I described above when looking through this stuff a while back, just had forgotten about it during the PR.

**Comment by caohai** [comment]
I'll create a PR to use a different name.

**Comment by alanrenmsft** [comment]
is this caused by the recent vscode merge?
