### ISSUE TITLE
No longer able to get visual studio 2015 build tools to compile ADS (For new contributors, not existing ones).

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#15290]
- Azure Data Studio Version:

Steps to Reproduce:

1. Follow the instructions for building ADS in the wiki.
2. Try to run "npm install --global windows-build-tools --vs2015"
3. No build tools are installed and yarn doesn't work properly. 
4. Install visual studio code 2017 with 2015 build tools, same result.

This issue is related to the fact that a number of Visual Studio 2015 repositories are seemingly offline and there's no way to acquire the tools in a way that works with ADS. Attempts to install Visual Studio 2015 and related dependencies manually resulted in bugs and other errors when attempting to compile the project.  Without these tools, there's no way to compile ADS. I have notified the Windows-Build-Tools repository about this issue, but this seems to be a larger issue involving Visual Studio 2015 repositories as a whole.

**Comment by Charles-Gagnon** [comment]
I don't think this is something that should be opened here - this would be an upstream issue with the [windows-build-tools](https://github.com/felixrieseberg/windows-build-tools#readme) repo so I'd suggest filing an issue there if you're having problems even just trying to install it.
