### ISSUE TITLE
Ability to filter Object Explorer schema objects

### ISSUE THREAD

**Issue by DrGriff** [microsoft/azuredatastudio#15296]
Issue Type: <b>Feature Request</b>

I want to view/edit one of our stored procedures, we have about 500 of them.

With the SSMS I can right-click on the [Stored Procedure] folder and filter with part of the name.

In the Azure Data Studio, I believe that to get to the list of stored procedures I have to drill down to this using the Connections feature, but once I can see those, I can't then filter with part of the name.....that would be so useful.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19042

**Comment by alanrenmsft** [comment]
@DrGriff 
you can actually do the filtering in the database dashboard. You can open the dashboard by clicking the 'Manage' option in the context menu of the database tree node.

![image](https://user-images.githubusercontent.com/13777222/116909622-54a15e00-abf9-11eb-99e0-22e83b07ca24.png)

and within the dashboard:
to can do a search by name, or by type and then name (sp:SEARCHTEXT)
![image](https://user-images.githubusercontent.com/13777222/116909741-7bf82b00-abf9-11eb-8a12-e44062bb007d.png)

**Comment by timothyhoffmann** [comment]
Using "Manage" is functional but obscure.  Would still like to see a right-click filter menu directly on the tree.

**Comment by MsSQLGirl** [comment]
Being able to browse and filter Schema from object explorer is also important because we generally have some actions (right click) that we want to do. Or sometimes even expand it to be able to drag and drop column / table name when building queries.

**Comment by Johannes-Vink** [comment]
I am sorely missing this feature compared to SSMS and this is the number one reason why I go back to SSMS. I am a data warehouse developer/architect and use SSMS as a primary driver for SQL development work and some monitoring on the agent jobs.Nothing DBA fancy stuff.

We have 5k+ database objects, spread across multiple schema's, divided in tables, views, stored procedures, functions. We have them all. I am not good at scrolling an endless list of objects and I am definitely not good in looking into an alfabetically sorted list, especially as I often remember a part of the schema name.

Scenario's:
* I filter on a part of the schema name, then inspect the available tables/views and start writing code, while checking the available objects
* Right click on an object and use several of the available options: drop/create, select, insert, generate ddl
* Using object explorer details to mass generate drops/selects. I can live without this feature, but would be an added bonus

**Comment by aasimkhan30** [comment]
dup of #12932
