### ISSUE TITLE
Unsaved SQL notebook stuck loading kernels and contexts

### ISSUE THREAD

**Issue by jwatkin** [microsoft/azuredatastudio#15311]
- Azure Data Studio Version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:25:54.683Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

Steps to Reproduce:

I haven't tried to reproduce this yet. Instead, this is what I'm guessing led to the issue:

1. I have a SQL notebook that I've been using reliably for days.
1. I added some test queries and ran some tests that returned a large set of results, maybe 63,000 rows. Maybe 10 columns per row with less than 100 total characters per row.
1. What I think is new is that I shut down my Mac without saving the SQL notebook. I would normally clear all of the results and save the notebook file before quitting.
1. Upon restarting Azure Data Studio, the (unsaved) notebook file contents won't display and the controls are stuck displaying "Loading kernels..." and "Loading contexts..."
1. If try to do a Git diff on the unsaved file from within ADS, I can see some diff information but the diff doesn't complete. Instead, I see two ADS messages. One reads that the diff algorithm stopped after 5000 ms, and asked if I want to remove the limit. The other message indicates that tokenization, wrapping, and folding has been turned off for this large file to reduce memory usage and to prevent crashing, then asked if I want to force enable some features. I didn't choose to do that yet. If I force enable the features could things get worse, such as me not being able to relaunch ADS without it crashing?

**Comment by jwatkin** [comment]
I ended up closing the unsaved notebook file without saving it, which probably wasn't a good move on my part. I should have done a "Save As ..." to another file. In any case, the last saved notebook file can now be opened without it getting stuck loading the kernel and contexts. Some test queries were lost but I should be able to recreate them in 15 minutes. A Git diff on this file still produces the warning message that tokenization, wrapping, and folding has been turned off for this large file to reduce memory usage and to prevent crashing, then offers to force enable some features. The file's JSON is 1495 lines long and contains a mix of both text and SQL cells. Is this considered a large notebook file?

**Comment by jwatkin** [comment]
The warning message that "tokenization, wrapping, and folding has been turned off for this large file to reduce memory usage and to prevent crashing" no longer appears, but I don't recall doing anything to make that happen. I didn't accept the "force enable some features" button. There was an additional macOS restart. I'll try to reproduce this entire issue when I have the time. Unfortunately unrelated project deadlines keep me from doing this now.

**Comment by chlafreniere** [comment]
Closing since we need a bit more info here. Feel free to reopen if this is still occurring. Thanks!
