### ISSUE TITLE
NULL count in query result aggregates

### ISSUE THREAD

**Issue by hiteshdavey** [microsoft/azuredatastudio#15322]
I have updated ADS and seen the enhancements. I appreciate the enhancements done BUT what is still missing is...

1. Show "NULL count" in the query result aggregates. Let say my query fetched 2k (or more) records and out of this; a couple of cols has some row(s) with null values. It would impossible to know abt null value count unless I explicitly filter that col to check null existence. And applying a filter every time to see if there are null rows is really a cumbersome exercise! It is like looking for a needle in a haystack! So I strongly suggest add NULL counter aggregate along with other aggregates.

2. If I apply a filter on a given col then that col header is clearly showing "filter icon", this gives me a clear indication that given col is filtered but if I sort a col then it supposes to show an AZ-down arrow icon / ZA up arrow icon; otherwise, it is difficult to know which col is sorted by mistake.

3. One-click option to restore result back to original resultset output (without re-running the SQL). This will be handy in case I have a long-running query result and I played around with it and now I want to go back to the initial output.

4. Option to set alternating row/col color.

**Comment by alanrenmsft** [comment]
@hiteshdavey 
for No.1 do you select all the cells (in the table or in a column) and then check the aggregates in the status bar?

**Comment by alanrenmsft** [comment]
No. 2 and No.3 is being tracked here. https://github.com/microsoft/azuredatastudio/issues/14587

**Comment by hiteshdavey** [comment]
> @hiteshdavey
> for No.1 do you select all the cells (in the table or in a column) and then check the aggregates in the status bar?

![ADS ResultPane](https://user-images.githubusercontent.com/44848636/117265299-b966ed80-ae71-11eb-95f1-d993dc3f3931.png)

The middle name of some emps has NULL values; I would like to see NULL counts (not just Count/rows) in the result aggregates.
I have selected the entire col (which is highlighted in blue color).

**Comment by alanrenmsft** [comment]
@hiteshdavey , right now, the aggregates will only show when there are numeric cells selected, are there any numeric values in the middle name column?

**Comment by hiteshdavey** [comment]
> @hiteshdavey , right now, the aggregates will only show when there are numeric cells selected, are there any numeric values in the middle name column?

See the pic. The query column is now numeric. All I want to see is "NullCount: 3" along with other aggregates like SUM.
The result has 3 rows with a null value. Is it possible to hide AVG. I prefer to see MIN=1 and MAX=6?

![ADS ResulGrid](https://user-images.githubusercontent.com/44848636/117420535-4d50bc00-af3b-11eb-8e4c-868ff73a245b.png)

**Comment by alanrenmsft** [comment]
this has been implemented a while ago.
![image](https://github.com/microsoft/azuredatastudio/assets/13777222/e7d86c26-eea3-4936-85a5-aae216b1e7ba)
