### ISSUE TITLE
ADS crashes while trying to open previous commits to source control

### ISSUE THREAD

**Issue by smjasont** [microsoft/azuredatastudio#15343]
- Azure Data Studio Version: 1.28.0

Steps to Reproduce:

1. Open folder in explorer, select file, select previous commit from timeline OR select a file under changes in source control view
2. ADS crashes

I've attempted this a dozen times with several different files to make sure it wasn't just a corrupted file, but crashes every time. Also closed and re-opened the repo, no luck

**Comment by Charles-Gagnon** [comment]
Duplicate of #15180 - see that issue for instructions to revert to a working version until a build with the fix is released.
