### ISSUE TITLE
Open Folder button doesn't do anything in File Explorer

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15369]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open ADS with no folder loaded
2. Click Open Folder

Expected: Prompt to open Folder

Actual: Nothing happens

<img src='https://user-images.githubusercontent.com/599935/117556535-de4c9380-b01e-11eb-8f26-a60e5cb60981.png' alt='Screenshot of File Explorer Open Folder button' width='400px' />

**Comment by Charles-Gagnon** [comment]
FWIW @caohai - not sure how far your investigation has gone but my initial guess for this is the security fix we did recently to not allow executing commands by default : https://github.com/microsoft/azuredatastudio/pull/15118. So if you haven't found something out already I'd suggest starting by looking at the stuff there to make sure that was set up correctly for the Views Welcome contributions.

**Comment by caohai** [comment]
> FWIW @caohai - not sure how far your investigation has gone but my initial guess for this is the security fix we did recently to not allow executing commands by default : #15118. So if you haven't found something out already I'd suggest starting by looking at the stuff there to make sure that was set up correctly for the Views Welcome contributions.

Thanks @Charles-Gagnon for the info. I haven't looked into this one, will look into the changes you suggested some time this afternoon.

**Comment by Charles-Gagnon** [comment]
@caohai Reopening this for port request - if you're fixing something that's intended to go into the release branch either : 

1. In the initial PR don't auto-close the issue, save that for the PR into the release branch
2. Close it but then immediately re-open it

This ensures that it continues to show up when looking at issues for the milestone until it's actually merged in
