### ISSUE TITLE
Schema compare dialog Ok button not enabled

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#15360]
- Azure Data Studio Version: Insiders
- Schema Compare version: 1.10.0

Steps to Reproduce:

1. connect to a server
2. launch schema compare
3. click "..." to open schema compare dialog
4. select database for source and target

actual:
Ok button is disabled even though dropdowns are populated

expected:
since the dropdowns are all populated, the Ok button should be enabled

Workaround is to change the database selection, but this wouldn't work if there's only one database in the dropdown.

![schemacomparebug](https://user-images.githubusercontent.com/31145923/117369788-4746d680-ae7a-11eb-9c75-141c8ca3b887.gif)

**Comment by udeeshagautam** [comment]
@Benjin can you pleae take a look.
