### ISSUE TITLE
Delayed, or no execution of queries

### ISSUE THREAD

**Issue by robertgale** [microsoft/azuredatastudio#15382]
Issue Type: <b>Bug</b>

I frequently press (say) Ctrl-Enter to begin execution of a query and the status bar changes to "Executing query..." but the execution time doesn't move - often for many seconds. The "Cancel" button (oddly named) doesn't do anything! Sometimes the query runs after a random amout of time, and then the real execution time is correctly reported. However, frequently the query doesn't run at all, Cancel doesn't work, and the only way to proceed is to close Azure Data Studio altogether and start all over again. Making the tool pathetically useless.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3900X 12-Core Processor             (24 x 3800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.95GB (8.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
schema-compare|Mic|1.10.0
sql-prompt|Red|0.2.6
sql-search|Red|0.3.1

</details>

**Comment by alanrenmsft** [comment]
this has been fixed in the latest insider build, please give it a try. similar to https://github.com/microsoft/azuredatastudio/issues/23145
