### ISSUE TITLE
Azure Data Studio red squiggly lines keep appearing.

### ISSUE THREAD

**Issue by Ric-de-fame** [microsoft/azuredatastudio#15380]
I have an issue with ADS, every time I issue a CREATE OR ALTER PROCDURE the squiggly red lines appear underneath all my lines of codes. When hovering over  one of the red lines it says  : 'ALTER PROCEDURE' must be the only statement in the batch.
The fact that there's nothing wrong with my code but the red lines won't disappear is really annoying. 
I've tried refreshing IntelliSense, the lines do go away only to reappear later.
Does anybody else have this issue and know how to fix it?

![image](https://user-images.githubusercontent.com/43514758/117590503-e4a85000-b183-11eb-92fe-d8861b401298.png)

**Comment by kburtram** [comment]
The error diagnostics come from the SQL Parser upstream component. It's likely this component will need to be updated to correctly recognize this syntax.
