### ISSUE TITLE
"Restore" button disappeared

### ISSUE THREAD

**Issue by Hang1314** [microsoft/azuredatastudio#15381]
- Azure Data Studio Version:

Steps to Reproduce:

No " Restore" button at my function area
Anyone can give me a favor?
Thanks
![issue](https://user-images.githubusercontent.com/83959088/117663634-09321580-b1e0-11eb-942d-f35650aaa385.png)

**Comment by kburtram** [comment]
@Hang1314 do you have "Preview Features" setting enabled in the User Settings?  Restore is currently considered a preview feature.

**Comment by Hang1314** [comment]
> The screenshot above is at the "instance" level for Azure SQL DB, restore is not supported for Azure SQL DB.
> 
> To export or import a database for Azure SQL DB, install the "SQL Server dacpac" extension and use the data tier application wizard.
> 
> Azure SQL DB, no restore button:
> ![image](https://user-images.githubusercontent.com/12227241/117865574-f30d6f00-b24a-11eb-955f-deea12d6cca4.png)
> 
> full SQL instance:
> ![image](https://user-images.githubusercontent.com/12227241/117865613-fd2f6d80-b24a-11eb-91be-d2eab523f086.png)

Thanks a lot

**Comment by Hang1314** [comment]
> @Hang1314 do you have "Preview Features" setting enabled in the User Settings? Restore is currently considered a preview feature.

oh, it still doesn't work for me

**Comment by alanrenmsft** [comment]
this is by design. as @dzsquared mentioned above, you cannot restore the master database of SQL Azure server. 
https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/dashboard/browser/pages/serverDashboardPage.contribution.ts#L83
