### ISSUE TITLE
"Create Project from Database" Action has No Icon on Server Dashboard Toolbar

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#15394]
This is what I see from the toolbar (maybe just needs an extension refresh?)

![image](https://user-images.githubusercontent.com/40371649/117725329-d7965b80-b199-11eb-9834-859225289036.png)

**Comment by chlafreniere** [comment]
@Charles-Gagnon FYI

**Comment by cssuh** [comment]
Approved in shiproom

**Comment by cssuh** [comment]
Port request has been merged
