### ISSUE TITLE
Loading Spinner Isn't Animated

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#15395]
(on Mac)
Example: clicking "Refresh" on the Databases page in the server dashboard. Loading spinner is static and doesn't have any animation:

![image](https://user-images.githubusercontent.com/40371649/117725601-35c33e80-b19a-11eb-82db-6f99eb2e79e5.png)

In April (and before), we saw the spinner animate:
![image](https://user-images.githubusercontent.com/40371649/117725721-6b682780-b19a-11eb-85a2-2d4def1d6844.png)

**Comment by cssuh** [comment]
Reassigning for load balancing in shiproom
