### ISSUE TITLE
Inconsistency with connecting to Azure hosted DBs

### ISSUE THREAD

**Issue by shoesCodeFor** [microsoft/azuredatastudio#15401]
Issue Type: <b>Bug</b>

Issues with connecting to Azure hosted SQL Server instances.  I can connect with other SQL clients but not Data Studio.  One thing of note is that the first connection to the DB is usually successful, but the following queries are not.  There is also a notable issue that a user cannot switch query tabs and reuse the connection.  

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:25:54.683Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by cheenamalhotra** [comment]
Hi @shoesCodeFor 

Following up on the same, can you let us know if you're still experiencing any issues with ADS when connecting to Azure hosted SQL instances? Would recommend you to update ADS to latest version to validate the same.

**Comment by cheenamalhotra** [comment]
Closing as inactive
