### ISSUE TITLE
Add Duplicate command to Query context menu

### ISSUE THREAD

**Issue by KoalaBear84** [Microsoft/azuredatastudio#1541]
Issue Type: <b>Feature Request</b>

Please add a Duplicate command to the Query context menu.

Many times you have similair queries which this feature will be useful.

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.14393

**Comment by KoalaBear84** [comment]
Yes. Like duplicating a tab in Chrome. Creating a copy of the selected tab/document together with the query text(s) in it. And also with that same connection it has.

**Comment by anthonydresser** [comment]
dupe #245
