### ISSUE TITLE
Schema compare source target selection dialog is not populating target dbs correctly

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#15422]
- Azure Data Studio Version:

Steps to Reproduce:

1. connect to a server with multiple dbs
2. right click on one db and select schema compare
3. click on ... for target
4. the diaog opens 
5. If you go to select targets only one db is showing in dropdown even through the sever is connected.

![image](https://user-images.githubusercontent.com/46980425/117898165-31218780-b279-11eb-96a2-313dc9da1704.png)

![image](https://user-images.githubusercontent.com/46980425/117898183-40083a00-b279-11eb-93cd-f93ae73ee400.png)

**Comment by udeeshagautam** [comment]
Regression : Yes
Workaround available : Yes - just connect from the SC dialog itself again, doesnt lose context.

**Comment by ssreerama** [comment]
Unable to repro the issue, could be an intermittent. Will keep an eye on this issue and if able to repro it, we can provide a fix for it. Closing this one for now!
