### ISSUE TITLE
Notebooks: Run Cells Below also runs the current cell 

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#15432]
- Azure Data Studio Version: RC (not a regression)

**Comment by chlafreniere** [comment]
@lucyzhang929 I believe this is by design and follows what happens in Jupyter.

**Comment by lucyzhang929** [comment]
@chlafreniere Ah I see. Verified that it is the same behavior in Jupyter. I'll close this issue. Thanks!
