### ISSUE TITLE
Azure Data Studio Database Project Publish Data Loss Config

### ISSUE THREAD

**Issue by eits79** [microsoft/azuredatastudio#15436]
- Azure Data Studio Version: 1.28

Steps to Reproduce:

1. Remove column from create table script in Data Studio project
2. Publish dacpac from Azure Data Studio SQL Database Project to a table with data
3. Deploy dacpac failed - Core Microsoft SqlClient Data Provider: Msg 50000, Level 16, State 127, Line 6 Rows were detected. The schema update is terminating because data loss might occur.

Please advise how to configure Azure Data Studio publish to ignore data loss warning and continue. I want to drop a column so I don't care about the data in the column.

**Comment by kisantia** [comment]
One option is to use a publish profile and set BlockOnPossibleDataLoss to false. There currently isn't a way to create a publish profile in ADS through the UI like SSDT has, but you can create a new .publish.xml file to set these settings.
sample.publish.xml 
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="Current" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <IncludeCompositeObjects>True</IncludeCompositeObjects>
    <TargetDatabaseName>SampleDatabaseProject</TargetDatabaseName>
    <DeployScriptFileName>SampleDatabaseProject.sql</DeployScriptFileName>
    <ProfileVersionNumber>1</ProfileVersionNumber>
    <BlockOnPossibleDataLoss>False</BlockOnPossibleDataLoss>
  </PropertyGroup>
</Project>
```

Another option is to deploy using the dacpac wizard in ADS(install the dacpac extension to use this). This wizard shows if there will be any possible data loss and requires the user to check a checkbox if they want to proceed despite possible data loss.

**Comment by eits79** [comment]
@kisantia Thank you for your reply. I'll need to educate myself more on the publish profile options. When I tried a custom profile, the ADS publish included revoke connect from all my db users. The same happens when I tried the dacpac wizard. If I just use the default publish with no custom profile, the generated script works fine with no extra revoke connect. Is there another parameter needed to prevent this behavior? Are you aware of any comprehensive documentation on the publish profile options?

**Comment by kisantia** [comment]
These are the default options that get set for the dacpac wizard and sql project publish when no profile is passed in. When a profile is passed in, only the options in the profile are used.
https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/DacFx/DacFxOperation.cs#L102-L113

[Here's](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-publish?view=sql-server-ver15) a list of the different options that can be set in the profile (sqlpackage is a command line wrapper around the same engine used by the dacpac wizard and sql project publish). @dzsquared is there any Microsoft documentation on publish profiles? I did a quick search and I only found this [wiki](https://github.com/DrJohnT/AzureDevOpsExtensionsForSqlServer/wiki/DAC-Publish-Profile) someone else wrote on github that gives an overview of how to create one in VS.

**Comment by eits79** [comment]
Thanks @kisantia. I was able to get the desired behavior now with the examples you provided. This helped me as well, https://docs.microsoft.com/en-us/dotnet/api/microsoft.sqlserver.dac.dacdeployoptions?view=sql-dacfx-150&viewFallbackFrom=sql-dacfx-140.3881.1

**Comment by kisantia** [comment]
awesome glad to hear :)
