### ISSUE TITLE
Cloud Shell (PowerShell) is broken

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15441]
RC1/insiders

Opening up the cloud shell in PowerShell mode seems to be broken, I just get a bunch of weird text like this : 

![image](https://user-images.githubusercontent.com/28519865/118038562-2112b200-b324-11eb-96ac-e25465dd43e3.png)

Bash shell seems fine

**Comment by cssuh** [comment]
Approved in shiproom

**Comment by Charles-Gagnon** [comment]
@abist I'm still seeing issues in both insiders and RC1. e.g. 

1. Still seeing gibberish in the console, especially when resizing the pane. It doesn't always happen right away, sometimes it takes a number of resizes to trigger it
2. The warning about setting up cloud shell is popping up a lot - pretty much anytime I resize the terminal
3. We're recreating the session with each resize event it looks like, which seems to be causing us to hit the limit of 20 sessions pretty quick and then start erroring out
![ShellConsole](https://user-images.githubusercontent.com/28519865/118851347-7f8ce280-b886-11eb-9b28-9110eaba8e1d.gif)
4. After I closed the terminal and tried to re-open it then it just stayed blank. The console had a bunch of errors though : 

![image](https://user-images.githubusercontent.com/28519865/118850719-ebbb1680-b885-11eb-98e0-d952746771ac.png)

**Comment by Charles-Gagnon** [comment]
Did some more testing on the current stable and it looks like this stuff is broken there too so seems like not a regression at least (as far as the broken behavior when resizing the window goes)

**Comment by cheenamalhotra** [comment]
Closing as this is no longer an issue (tested with v1.44-RC1)

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/2f4ed97d-cdde-49a2-8310-a64edff27f38)
