### ISSUE TITLE
Support attachments properties in notebook metadata for simple image referencing

### ISSUE THREAD

**Issue by joberume** [microsoft/azuredatastudio#15469]
**Is your feature request related to a problem? Please describe.**
When editing notebooks in the WYSIWYG editor, you are able to paste in images from the clipboard. This is great as it automatically handles the serialization of the image and placement in the notebook. The form that it places the image in the notebook is as an embedded base64 format that is inlined with the rest of the text. This makes the editing experience very clunky in the case I want to edit text immediately after the image in the markdown editor. I need to perform heavy duty scrolling to reach the area of interest. This is a burdensome experience that does not incentivize easy editing, especially as it looks like the scroll bar in the cells competes with the scroll bar at the notebook level. 

**Describe the solution or feature you'd like**
I would like for ADS to support the attachment format used by [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/latest/examples/Notebook/Working%20With%20Markdown%20Cells.html#Markdown-attachments). This reduces the image markup in the markdown version of the text to a few characters. I would like this to be the default supported insertion method of the image when in WYSIWYG mode so that whenever the user switches to markdown, they do not have to fight with the scrolling bars.

**Describe alternatives you've considered**
Only other alternative I can think is that it does not embed the image, but rather creates the image on a relative directory and references that image with a filepath.

**Comment by joberume** [comment]
Attn: @MsSQLGirl , @rajeshka , @JustinMDotNet

**Comment by chlafreniere** [comment]
@MaddyDev not sure if you'll have any capacity, but FYI here. Given your work with cell attachments, do you have a rough estimate of how we can make pasting "just work" (i.e. by adding a cell attachment)?

**Comment by chlafreniere** [comment]
@joberume we've been working on cell attachments and for May, users will be able to use split/markdown mode to insert a new cell attachment via the callout dialog:

![image](https://user-images.githubusercontent.com/40371649/118209351-4f27ed00-b41d-11eb-8d6d-d140b0ca6449.png)

**Comment by joberume** [comment]
@chlafreniere That's stupendous! At least for markdown editors, this will not be an issue. Will make sure to surface this with our customers 🤗

Will it be possible in the future to switch this mechanism for WYSIWYG as well? If currently not yet available, we keep this issue open for tracking purposes 😁

**Comment by chlafreniere** [comment]
@joberume absolutely, that's the next step (enabling this for WYSIWYG). And correct, not currently available.

**Comment by MaddyDev** [comment]
> @MaddyDev not sure if you'll have any capacity, but FYI here. Given your work with cell attachments, do you have a rough estimate of how we can make pasting "just work" (i.e. by adding a cell attachment)?

Sure thing, I think I'll work to include it for the June release.

**Comment by chlafreniere** [comment]
This is in with above PRs

**Comment by MsSQLGirl** [comment]
The attachment is added properly. However, when using WYSYWIG to remove the image, it seems the underlying file contains the image data still.

To repro:
1. Create a new notebook and a new text cell.
2. Paste image (screenshot) in text cell via WYSIWYG. 
3. Save.
4. Open in Notepad, you'll see the embedded image base64 text. Close
5. Open in ADS, remove the image from WYSYWIG. 

Actual: the embedded image base64 text is still showing.
Expected: the embedded image base64 text should not show

**Comment by Charles-Gagnon** [comment]
@MsSQLGirl Issue opened for that : https://github.com/microsoft/azuredatastudio/issues/15635
