### ISSUE TITLE
Change standard color back to black

### ISSUE THREAD

**Issue by maximilian22x** [microsoft/azuredatastudio#15460]
Hello, 

its a horrible idea to use grey as standard color for the editor and menu (and results panel) text. 

Please change to black. 

People can see text if its black and on a white background. 

Regards

**Comment by alanrenmsft** [comment]
@maximilian22x could you please attach a screenshot?

**Comment by kburtram** [comment]
The colors are controlled by the selected Color Theme.  Please look through the themes to find one that matches your preference.  Alternatively you can load any themes from the VS Code marketplace by downloading and then installing the VSIX in the extension manager.
