### ISSUE TITLE
Error Messsage upon opening ADS

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#15486]
- Azure Data Studio Version:
<img width="264" alt="Screen Shot 2021-05-14 at 11 58 29 AM" src="https://user-images.githubusercontent.com/18150417/118316450-b5f3e780-b4ab-11eb-893e-314745bd0e5f.png">

Steps to Reproduce:

1. Open ADS
2. Error message pops up:
<img width="459" alt="Screen Shot 2021-05-14 at 11 55 20 AM" src="https://user-images.githubusercontent.com/18150417/118316327-8a70fd00-b4ab-11eb-8d20-703612c0d16e.png">

from developer tools console:
<img width="654" alt="Screen Shot 2021-05-14 at 11 56 46 AM" src="https://user-images.githubusercontent.com/18150417/118316331-8ba22a00-b4ab-11eb-9c9d-0813ac48447b.png">

path is:
file:///Applications/Azure Data Studio - Insiders.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js

Note: I also updated to Big Sur yesterday, not sure if that is related or not.

**Comment by Charles-Gagnon** [comment]
@chlafreniere This seems to be coming from NotebookModel https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/services/notebook/browser/models/notebookModel.ts#L1111

**Comment by chlafreniere** [comment]
@cssuh is there a notebook that you have open when ADS starts up?

This error can technically be due to numerous different issues, but in reality, often implies that there's an issue with a Python install.

@lucyzhang929 as FYI

**Comment by cssuh** [comment]
@chlafreniere yes I have the DRI notebook open when ADS starts up.  Just closed the notebook and reopened and the error does not show in that scenario.

**Comment by chlafreniere** [comment]
Interesting. So does this repro every time that you have the DRI notebook open when ADS starts?

From: Christopher Suh ***@***.***>
Date: Friday, May 14, 2021 at 1:03 PM
To: microsoft/azuredatastudio ***@***.***>
Cc: Chris LaFreniere ***@***.***>, Mention ***@***.***>
Subject: Re: [microsoft/azuredatastudio] Error Messsage upon opening ADS (#15486)

@chlafreniere<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fchlafreniere&data=04%7C01%7Cchlafren%40microsoft.com%7C4e4ead698b394069dba608d91713623d%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637566194285144461%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BCtb%2FpR3o18lQvRofny9J9ld6ecMsJ%2BpRoMu8cfBhuE%3D&reserved=0> yes I have the DRI notebook open when ADS starts up. Just closed the notebook and reopened and the error does not show in that scenario.

**Comment by cssuh** [comment]
Yes, it has happened every time - if I start without an editor open, then the error only shows up once I open the DRI notebook.

**Comment by chlafreniere** [comment]
I'd suggest running the "Reinstall Notebook Dependencies" command pallette task and see if that fixes it for you, @cssuh

**Comment by cssuh** [comment]
That didn't seem to work, I think this is an issue with Big Sur because I am not able to run it in ADS 1.28 (latest public release) either.

**Comment by chlafreniere** [comment]
@cssuh are you still seeing this?

**Comment by cssuh** [comment]
<img width="457" alt="Screen Shot 2021-07-13 at 10 27 45 PM" src="https://user-images.githubusercontent.com/18150417/125567670-250cb594-1739-42ee-9da1-daa0047a37a0.png">
This is the error I'm getting now, but from talking to other people who upgraded to Big Sur, it seems to be isolated to  my machine.

**Comment by kburtram** [comment]
Closing issues without repro on current builds.  Please reactive if you're still impacted by this issue.
