### ISSUE TITLE
Pasting an image into text cell renders image outside cell

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#15491]
- Azure Data Studio Version: 1.29.0-rc1

Steps to Reproduce:

1. Create new notebook and add a text cell.
2. Copy paste and image into the cell.

![image](https://user-images.githubusercontent.com/12754347/118335931-88b43300-b4c5-11eb-97aa-156d1b46c26d.png)

**Comment by barbaravaldez** [comment]
The issue only happens when creating a new cell and the cell is empty.
