### ISSUE TITLE
Unable to copy and paste to external app

### ISSUE THREAD

**Issue by stefanodcd** [microsoft/azuredatastudio#15507]
Issue Type: <b>Bug</b>

The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called.

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:25:54.683Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.3.0
schema-compare|Mic|1.10.0
sql-database-projects|Mic|0.8.2
schema-visualization|R0t|0.7.1

</details>

**Comment by Charles-Gagnon** [comment]
Could you explain your situation a bit more? What are you trying to copy and paste and is the text you have above an error you're seeing or something?

**Comment by stefanodcd** [comment]
i ran a query with json output, clicked on the json and then tried to copy a value from to another tab and to postman. Copy and paste did not work and instead showed the warning The WebView must be attached to the DOM and the dom-ready event emitted before this method can be called. I tried to recreate the issue this morning to add some screenshots but funny enough it is working now. So please feel free to close and i will reopen if it happens again.

**Comment by kburtram** [comment]
I couldn't repro on the current build, so as suggested, I'll close not.  Please let us know if this issue persists.
