### ISSUE TITLE
Tiered HDFS mounts don't refresh

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#15513]
- Azure Data Studio Version: 1.28.0

Steps to Reproduce:

1. Connect to a Big Data Cluster that has a tiered HDFS mount
2. Go to the HDFS folder of that BDC and navigate to the mount
3. Right mouse click - refresh

This does not trigger a refresh from the source (azdata bdc hdfs mount refresh --mount-path).

If that is by design, there should be an option to do so.

**Comment by Charles-Gagnon** [comment]
Thanks for submitting this - it does look like we don't support refreshing the mount status (refresh just fetches the current list of files from the controller). 

As a workaround in the meantime if you run the refresh command manually through azdata and then refresh the node in ADS the new files should show up.

**Comment by bweissman** [comment]
yeah, that works but obviously isn't ideal. maybe we could have 2 options like "Refresh (Controller)" and "Refresh (Full)"?

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
