### ISSUE TITLE
Clicking on file in git pending changes crashes studio

### ISSUE THREAD

**Issue by milanc** [microsoft/azuredatastudio#15514]
When trying to view differences in source control panel studio hangs.
Only solution is to restart it.

Tried with uninstall, removed remaining folders, and reinstall.
This is happening only on files with sql extension because changes preview for other files are working.

I have VS Code and I have no issues in it to see differences in pending changes.

**Comment by Charles-Gagnon** [comment]
Duplicate, see https://github.com/microsoft/azuredatastudio/issues/15180 for details and instructions for reverting until the fix is published.

**Comment by milanc** [comment]
Before submitting it I was trying to find something similar, guess not hard enough. :)
Looking forward to the new release.
Thank you for quick response.

**Comment by Charles-Gagnon** [comment]
We just released today so if you update to the latest stable then you should no longer see this issue! Let us know if you're still encountering any issues.

**Comment by milanc** [comment]
Fixed, thank you.
