### ISSUE TITLE
Renaming files or folders

### ISSUE THREAD

**Issue by SodaMty** [microsoft/azuredatastudio#15529]
Issue Type: <b>Bug</b>

I can't rename files or folders from Explorer section

Steps:
1. Open Explorer Section with CTRL+SHIFT+E or click on the icon (Explorer).
2. Select a file or folder to rename.
3. Press F2, edit mode is now on.
4. Type new name for the file or folder selected.
5. Press ENTER (Is doing nothing)

My Wrokaround is go to Windows Explorer and rename the file or folder here.

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
kusto|Mic|0.5.4
machine-learning|Mic|0.9.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
schema-compare|Mic|1.11.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.9.1
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
@SodaMty - I can repro the issue where pressing enter doesn't work, but if I just deselect the item after renaming it still applies the rename as expected. Does that also happen for you?

**Comment by SodaMty** [comment]
No, if I just deselect the item keep doing nothing

**Comment by Charles-Gagnon** [comment]
Could you attach a video of this behavior? I wasn't seeing that so I want to be sure that we're looking at the correct issue.

**Comment by SodaMty** [comment]
Sure, here is the video

You know what?, making the video I realized that it is not only when renaming a file or folder but also when creating it.
It seems an issue of permissions in the OS, it is worth mentioning that I have the same permissions before installing version 1.29.0.

Now I have some meetings, but as soon as I finish them I will do a restart of the computer, it is worth mentioning that I do not remember having restarted the computer before, so that some change of an ADS installer will be applied.

**Comment by SodaMty** [comment]
I have already restarted my computer and the behavior remains the same, I have even also noticed that when I am working in Zen mode, invoking the menu with the ALT key does not work and before I could do this, I do not know if it is due to the same thing, other key combinations work fine, such as CTRL + P

**Comment by MartinRyx** [comment]
> I can repro the issue where pressing enter doesn't work, but if I just deselect the item after renaming it still applies the rename as expected. Does that also happen for you?

@Charles-Gagnon That works for me too, but it's still kind of annoying having to deselect instead of just hitting Enter
