### ISSUE TITLE
SqlStaticCodeAnalysisTask DB Project Build Error

### ISSUE THREAD

**Issue by mattgreenbank** [microsoft/azuredatastudio#15531]
- Azure Data Studio Version: 1.29

Steps to Reproduce:

1. When building an existing Azure SQL Database DB project where (static) code analysis is enabled, the build fails as the task is missing from the Azure Data Studio directory.

**.azuredatastudio\extensions\microsoft.sql-database-projects-0.9.1\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(1371,7): error MSB4036: The "SqlStaticCodeAnalysisTask" task was not found. Check the following: 1.) The name of the task in the project file is the same as the name of the task class. 2.) The task class is "public" and implements the Microsoft.Build.Framework.ITask interface. 3.) The task is correctly declared with <UsingTask> in the project file, or in the *.tasks files located in the "C:\Program Files\dotnet\sdk\5.0.203" directory.**

**Comment by kisantia** [comment]
same as https://github.com/microsoft/azuredatastudio/issues/13781
