### ISSUE TITLE
Populate Server Names in Connection Parameter

### ISSUE THREAD

**Issue by hiteshdavey** [microsoft/azuredatastudio#15556]
ADS Connection parameters screen has no option to **Browse for Servers** (network and local servers) like SSMS. In the absence of such an option, it is difficult to know the list of available servers. and keying in the server name or IP manually is error-prone and results in trial and error; therefore I request the ADS team to provide such useful basic features.

By default auto-populate all local servers. If users want to connect n/w server then let them have the option to "browse for more..." like SSMS login parameters.

N.B: ADS app is far from complete. It is seriously lacking many basic features which SSMS providing for many yrs and I don't understand why such basic options are missing since day one of the ADS release?

**Comment by kburtram** [comment]
We decided not to support the SQL Server network discovery feature when building the connection dialog since the "SQL Server Brower" service is now disabled by default in SQL Server installs.  I'll leave this here to discuss when reviewing potential enhancements to the connection experience.

**Comment by cheenamalhotra** [comment]
Closing this issue as this feature has not received much interest from the community and since SQL Server Browser service is now disabled by default, it makes this support low priority to be supported for Enterprise applications.
