### ISSUE TITLE
Enable background updates on Windows

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1555]
The VS Code 1.23.1 merge brought the capability for background updates, but we need to do some work to enable them

Right now if you try to do a background update you get all sorts of permission denied errors, maybe because the files are in use. We should investigate this and fix it.

We'll also need to modify our update server so that it forwards the update's `supportsFastUpdate` info to the client.

To test you can run the following code with Node and then set your update server in `product.json` to your local IP:
```
var http = require('http');

http.createServer(function (req, res) {
  res.write('{"url":"https://sqlopsbuilds.azureedge.net/insider/8a3509e0062448b1335a0fb2eab7050d50a3a07a/SqlOpsStudioSetup.exe","name":"0.30.3-insider","version":"8a3509e0062448b1335a0fb2eab7050d50a3a07a","productVersion":"0.30.3-insider","hash":"4335fc1315a7a9d7f6d96e9be142d0e8334001f6","sha256hash":"f0737a6a4df5d114b796a634ae4347326beed16e0d24f2ec09b4f17fdb453d23","supportsFastUpdate": true}'); //write a response to the client
  res.end();
}).listen(8080);
```

**Comment by kburtram** [comment]
Closing older issues.  We're tracking tasks like this in ADO currently.
