### ISSUE TITLE
'Open in Azure Portal' doesn't work for SQL databases

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#15579]
'Open in Azure Portal' feature in the Azure resources browser doesn't work for SQL databases, for 'sql server' resource type, the link works.

![image](https://user-images.githubusercontent.com/13777222/119710666-787c4c00-be13-11eb-9b16-efa155d549db.png)

@Charles-Gagnon

**Comment by cheenamalhotra** [comment]
Closing as issue not reproducible in latest releases.
