### ISSUE TITLE
Azure Data Studio very slow on first query

### ISSUE THREAD

**Issue by athosmoreno** [microsoft/azuredatastudio#15572]
Issue Type: <b>Performance Issue</b>

When I open Azure Data Studio for the first time in a Windows boot and log in into a server, it takes several minutes to complete the first query I make, no matter how simple or complex it is. It doesn't let me cancel the query and also doesn't let me open another tab to connect again (it times out). This behavior doesn't happen on SSMS.

After this, the tool (usually) works fine.

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 14868	azuredatastudio main
    0	   165	  4788	   window (● SQLQuery_1 - OMAPRDIACPD12.csgiprod.com.Comcast_CRE_UAT (Integrated) - Azure Data Studio)
    0	    88	 27312	     extensionHost
    0	    62	  5940	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=27312
    0	    22	 13872	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.102\MicrosoftSqlToolsCredentials.exe" --log-file c:\Users\morath01\AppData\Roaming\azuredatastudio\logs\20210525T150237\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	     5	  7860	         console-window-host (Windows internal process)
    0	    22	 17856	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.102\SqlToolsResourceProviderService.exe" --log-file c:\Users\morath01\AppData\Roaming\azuredatastudio\logs\20210525T150237\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	     5	  6300	         console-window-host (Windows internal process)
    0	   125	 25476	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.102\MicrosoftSqlToolsServiceLayer.exe" --log-file c:\Users\morath01\AppData\Roaming\azuredatastudio\logs\20210525T150237\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	     5	 20932	         console-window-host (Windows internal process)
    0	    34	 15604	   utility
    0	    21	 17136	   crashpad-handler
    0	   123	 17308	   gpu-process
    0	    82	 24980	   window (Issue Reporter)
    0	    80	 27112	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by alanrenmsft** [comment]
@aasimkhan30 have you seen this kind of issue before?

**Comment by athosmoreno** [comment]
I made a test with a SQL Server instance installed on the machine and this doesn't happen. I can only reproduce with SQL Server instances inside a network (not sure if this extra info is of any use).

**Comment by Code-DJ** [comment]
@alanrenmsft this looks similar to https://github.com/microsoft/azuredatastudio/issues/15230.

**Comment by alanrenmsft** [comment]
@athosmoreno @Code-DJ Similar to https://github.com/microsoft/azuredatastudio/issues/23145, I have fixed the issue, please try the latest insiders build.
