### ISSUE TITLE
Arc SQL MI deployment links to PaaS portal #MAY2021BUGBASH

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio#15581]
I was trying to deploy SQL MI on Azure Arc through ADS.
I followed the usual steps.  ... -> New Deployment.  

![image](https://user-images.githubusercontent.com/3500406/119714707-0823f980-be18-11eb-8a31-c1a7027847cc.png)

I thought there used to be a SQL MI tile with "Arc" in the name.  But I click the closest thing, which is the SQL MI tile under Hybrid.

![image](https://user-images.githubusercontent.com/3500406/119714897-3efa0f80-be18-11eb-8b65-374a4a830978.png)

I'm linked to this page in the Azure Portal: https://portal.azure.com/#create/Microsoft.SQLManagedInstance
But this page describes a "fully managed PaaS database service" which doesn't sound like an Arc deployment.

Version: 1.30.0-insider
Commit: e49dd129516c052fc53480eed7804c7c61b9a313
Date: 2021-05-26T05:45:31.584Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/3500406/119713055-2852b900-be16-11eb-9fab-5fbf87d0e104.png)

**Comment by Charles-Gagnon** [comment]
@bergeron That is now under the "Resource Type" dropdown 

![image](https://user-images.githubusercontent.com/28519865/120556730-c237da00-c3b1-11eb-86d4-0bf21455a809.png)

This was an ask from the PMs to consolidate the MI offerings into one tile.

If you do a deployment from the controller dashboard (New Instance) then we filter down to just the Arc version though - it only shows both when going from "New Deployment..."
.
Let me know if you/anyone else thinks this should be displayed differently or contain different text - although I would also say that we should consider updating the wiki page to include messaging about Arc as well so users know the various options they have for deploying a MI server.
