### ISSUE TITLE
Changes do not confirm when press Enter

### ISSUE THREAD

**Issue by DaniSangelo** [microsoft/azuredatastudio#15591]
- Azure Data Studio Version: Version: 1.29.0 (user setup)
                                              Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
                                              Date: 2021-05-15T01:12:11.112Z
                                              VS Code: 1.53.0
                                              Electron: 11.2.2
                                              Chrome: 87.0.4280.141
                                              Node.js: 12.18.3
                                              V8: 8.7.220.31-electron.0
                                              OS: Windows_NT x64 10.0.19041

Steps to Reproduce:

1. Select a file to rename
2. Rename it and press Enter to confirm. Nothing happens. I need to click anywhere else.

**Comment by alanrenmsft** [comment]
dupe of https://github.com/microsoft/azuredatastudio/issues/15529
