### ISSUE TITLE
Updating Spanish Lang Pack gives an error

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15597]
- Azure Data Studio Version: `1.29.0`

Steps to Reproduce:

1. Click update on installed lang pack extension (Spanish in this case)

Expected: Update works

Actual: Update fails

![image](https://user-images.githubusercontent.com/599935/120059976-ca86c280-c009-11eb-93bb-8ec532e0f803.png)

**Comment by kburtram** [comment]
@smartguest could you please take a look at why this is happening?

**Comment by smartguest** [comment]
@kburtram I am unable to reproduce this by installing the older lang packs from the extensions archive (or even the 1.26.1 one that I sent you a while ago) and it automatically updates without any issue besides requiring a restart. Can you try again with another ADS client on another computer with an older Spanish lang pack installed? For reference here is a video showing what is going on on my side.

https://user-images.githubusercontent.com/18018452/120363077-9852ba80-c2c0-11eb-843b-b7f4a867e96d.mp4
