### ISSUE TITLE
Profiler: Failed to start session: Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by bart-coppens** [microsoft/azuredatastudio#15595]
[20210528T084746.zip](https://github.com/microsoft/azuredatastudio/files/6558883/20210528T084746.zip)

- Azure Data Studio Version:
Version: 1.29.0 (system setup)
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:12:11.112Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Connect to a server
2. Press "alt+P"
3. Press "start"

now this error occurs:
Failed to start session: Object reference not set to an instance of an object.

Logs are attached

**Comment by bart-coppens** [comment]
[20210531T081848.zip](https://github.com/microsoft/azuredatastudio/files/6568167/20210531T081848.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/6568169/console.log)

**Comment by SakshiS-harma** [comment]
@bart-coppens From the above message, it appears that the issue was resolved (just not closed). I am closing this issue for now. You can open another issue if you hit some other problems with Profiler. Thanks!
