### ISSUE TITLE
Temporal Table PK Change

### ISSUE THREAD

**Issue by philnoakes** [microsoft/azuredatastudio#15626]
- Azure Data Studio Version:

Steps to Reproduce:

1.Create a temporal table that utilizes a non-clustered primary key
2.Deploy the table to the database.
3.Change the primary key to clustered
4.Deploy the new primary key definition to the database.

Results - dacpac script attempts to drop the existing primary key without first turning off system versioning. This obviously causes the deployment to fail. There is no work-around for this in pre or post deploy scripts.

**Comment by kisantia** [comment]
Needs to be fixed in DacFx. @ssreerama do you know if this was fixed with the temporal table fix you recently made?

@philnoakes which version of ADS are you using?

**Comment by philnoakes** [comment]
I'm using 1.28. But the sqlpackage version i'm using is showing 14.0.4127.1

**Comment by kisantia** [comment]
are you using sqlpackage to generate the script, not the dacpac wizard in ADS? Please use the [latest version of sqlpackage ](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver15)if you are using sqlpackage.

**Comment by ssreerama** [comment]
@kisantia , The fix that we recently made is to support the temporal table drop, I don't think of this scenario that came under the previous fix. 

@philnoakes, please update your issue status by using the latest sqlpackage, If the bug still exists, we can look into it! Thanks.

**Comment by kisantia** [comment]
please reopen this issue if there are more details that can be provided
