### ISSUE TITLE
"System out of memory exception" crashes Operations Studio

### ISSUE THREAD

**Issue by netcrawler00** [Microsoft/azuredatastudio#1562]
Issue Type: <b>Bug</b>

Run a query supposed to return a large amount of data.
In SSMS, I get the error message "An error occurred while executing batch. Error message is: Une exception de type 'System.OutOfMemoryException' a été levée.".
In SOS, the app crashes.

SQL Operations Studio version: sqlops 0.29.3 (7099922c35bc3b3e223228c972cc03cee5abbe25, 2018-05-04T05:46:24.032Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|Memory (System)|15.88GB (6.30GB free)|
|Process Argv|C:\Users\BC08875\Documents\Perso\PortableApps\PortableApps\sqlops-windows\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.29.0
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>
Reproduces only with extensions

**Comment by netcrawler00** [comment]
@alanrenmsft it was a big result like 10 millions of records, maybe more, with around 30 fields. 
My expectation on this is not that the data should be displayed in any case, but that the exception should be handled as in SSMS so that I can keep working : I know the mistake was mine runing such a big query.

**Comment by alanrenmsft** [comment]
@netcrawler00 Thanks! I will try to reproduce it.

**Comment by alanrenmsft** [comment]
adding more details:

![image](https://user-images.githubusercontent.com/13777222/44123244-35509d94-9fdc-11e8-80e9-66979229574f.png)

On my machine, I was able to run a query with 22 million rows and 40 columns, the size of the temp file to store the results is 13.6 GB. I only have 4GB of RAM. I also have the 3 mentioned extensions installed.

**Comment by alanrenmsft** [comment]
Moving to backlog for now and i will look into it once becomes actionable.
