### ISSUE TITLE
Error when accessing database properties

### ISSUE THREAD

**Issue by maheshc** [microsoft/azuredatastudio#15624]
Issue Type: <b>Bug</b>

Right click on a database from the databases list (from connections window), click on database properties. In the database properties window, click on "File" link. Error thrown - Could not load file or assembly 'Microsoft.SqlServer.BatchParser.dll' or one of its dependencies. The specified module could not be found. (mscorlib)

I have only Azure Data Studio installed, SSMS in not installed. SQL 2019 Dev edition with latest CU.

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (9.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
Could you check whether you have that file in `%USERPROFILE%\.azuredatastudio\extensions\microsoft.admin-tool-ext-win-0.0.2\ssmsmin\Windows\15.0.18124.0`?

**Comment by maheshc** [comment]
I am using a portable version, so my extension folder is within the Azure Data Studio\Data folder. I can see the file 'Microsoft.SqlServer.BatchParser.dll' under the folder "\AzureDataStudio\Data\extensions\microsoft.admin-tool-ext-win-0.0.2\ssmsmin\Windows\15.0.18124.0\". 

Attached is a screenshot of the file properties. Also attached is the list of files I found in the folder.
[list.txt](https://github.com/microsoft/azuredatastudio/files/6627304/list.txt)


![image](https://user-images.githubusercontent.com/205277/121439646-3e1bbe80-c97e-11eb-9a7d-aec46ed9b7d6.png)

**Comment by Charles-Gagnon** [comment]
When you say "portable version" do you mean the zip? That should still be putting the extensions in the USERPROFILE location. Can you provide the full path to the folder of the extension?

**Comment by maheshc** [comment]
I do mean that I downloaded the zip version. After unzipping, I created a "data" folder under the main ADS folder. This makes ADS put all extensions under the data folder instead of userprofile. See details here - https://code.visualstudio.com/docs/editor/portable. As ADS uses the same code base as VS Code, it allows the same portable version creation steps.

**Comment by Charles-Gagnon** [comment]
Ah neat, all sorts of fun VS Code features I've never known about!

I still can't seem to repro this - could you verify exactly what this "file link" you're clicking on is? I'm able to view the Files tab just fine.

**Comment by Charles-Gagnon** [comment]
Closing this as I'm unable to repro, let me know if you have further information to share.
