### ISSUE TITLE
Update Portuguese (Brazil) Language Pack is not available

### ISSUE THREAD

**Issue by adilsontg** [microsoft/azuredatastudio#15639]
- Azure Data Studio Version: 1.29

Steps to Reproduce:

1. Open the command palette.
2. Fill in the text box with "Configure Display Language."
3. Click "Install additional languages..."
4. Select "Portuguese Language Pack for Azure Data Studio."
5. Error message is displayed.
The error message: "Error while updating 'Portuguese (Brazil) Language Pack for Azure Data Studio' extension. Please check the log for more details."

**Comment by Charles-Gagnon** [comment]
@smartguest Can you take a look?

**Comment by Charles-Gagnon** [comment]
In the meantime @adilsontg you can download the language pack manually here : https://sqlopsextensions.blob.core.windows.net/extensions/langpacks/1.29.0/ads-language-pack-pt-BR-1.29.0.vsix

And then install it via `File` -> `Install Extension from VSIX Package`

**Comment by adilsontg** [comment]
I was able to use the file language pack manually successfully. Thank you!

**Comment by Charles-Gagnon** [comment]
re-opening for investigation into issue

**Comment by Charles-Gagnon** [comment]
@smartguest I went ahead and fixed the filename and verified that the download works as expected now so I'm going to close this issue
