### ISSUE TITLE
Welcome page responsiveness is not working properly

### ISSUE THREAD

**Issue by radentonev** [microsoft/azuredatastudio#15638]
Issue Type: <b>Bug</b>

There is an issue with the responsiveness of the welcome page. The 4 cards in the middle no longer appear in one line, even on a wide screen.

Current behavior
![Screen Shot 2021-06-08 at 3 44 49 PM](https://user-images.githubusercontent.com/71295692/121267195-ada38800-c870-11eb-99e2-1fe52e89f054.png)

Expected behavior
<img width="572" alt="Screen Shot 2021-06-08 at 3 48 29 PM" src="https://user-images.githubusercontent.com/71295692/121267410-ffe4a900-c870-11eb-9869-6cb9c5eb14d8.png">

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:09:31.644Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 2, 2|
|Memory (System)|16.00GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
adslivesite|Mic|0.0.46
agent|Mic|0.48.0
arc|Mic|0.9.4
azdata|Mic|0.6.4
azuredatastudio-postgresql|Mic|0.2.7
datavirtualization|Mic|1.12.0
machine-learning|Mic|0.9.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.9.1
azdata-sanddance|msr|3.1.0
plan-explorer|Sen|0.9.8

</details>

**Comment by alanrenmsft** [comment]
this has been fixed a while back, if you use the insider build you will see it is working fine now.
