### ISSUE TITLE
Notebook extension fails to load trying to configure Python 3.8

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#15649]
- Azure Data Studio Version: 1.30.0-rc1

Notebook extension fails trying to setup Python 3.8. I did the process with insider successfully before but it failed in RC build. I deleted folder azuredatastudio-python to make it install everything again but it still fails. 

Steps to Reproduce:

1. Using ADS RC for MacOS, Open a notebook and select Python
2. dialog to configure Python 3.8 opens and starts the configuration

Expected: Notebook installs Python 3.8 successfully 
Actual: The process fails with following error:
 
ncountered an error when trying to retrieve list of installed packages: Command failed: "/Users/[user]/azuredatastudio-python/bin/python3" -m pip list --format=json
dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/[user]/azuredatastudio-python/bin/python3
  Reason: image not found

    > "/Users/[user]/azuredatastudio-python/bin/python3" -m pip install --user "jupyter>=1.0.0"
    stderr: dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
    stderr:   Referenced from: /Users/[user]/azuredatastudio-python/bin/python3
    stderr:   Reason: image not found
    stderr: 
Installing Notebook dependencies failed with error: Process exited with error code: null. StdErr Output: dyld: Library not loaded: /usr/local/opt/gettext/lib/libintl.8.dylib
  Referenced from: /Users/[user]/azuredatastudio-python/bin/python3
  Reason: image not found

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Can you work with Leila to figure this out?

**Comment by lucyzhang929** [comment]
Updating gettext fixed this issue: `brew reinstall gettext`

**Comment by Charles-Gagnon** [comment]
Is that an ML dependency or something? Is this going to affect other users?

**Comment by llali** [comment]
> Is that an ML dependency or something? Is this going to affect other users?

yes ML has dependency to Notebook but the issue I had was happening to notebook itself. after installing gettext the problem was gone
