### ISSUE TITLE
SQL Notebook with parameterization run error

### ISSUE THREAD

**Issue by kkbruce** [microsoft/azuredatastudio#15641]
Issue Type: <b>Feature Request</b>

I want to write SQL Notebook with parameterization, Example:

Code Cell 1 (Set Parameters)
```
DECLARE @today DATE
SET @today = GETDATE()
```

Code Cell 2
```
SELECT @today
```

But they always run error. Does parameterization support SQL kernel at present?

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19042

**Comment by Charles-Gagnon** [comment]
Not yet, currently parameterization only supports the Python kernel. 

@VasuBhog @chlafreniere Can we get the docs here updated to clearly state that we only support the Python kernel currently? https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-parameterization?view=sql-server-ver15

**Comment by kkbruce** [comment]
Any support plans? SQL Notebook without parameterization is clumsy enough to write.

**Comment by Charles-Gagnon** [comment]
I'm going to close this since we already have an issue tracking support for this : https://github.com/microsoft/azuredatastudio/issues/13771
