### ISSUE TITLE
@deprecated createModelViewDialog - ambiguous hint

### ISSUE THREAD

**Issue by m4ss1m0g** [microsoft/azuredatastudio#15643]
- Azure Data Studio Version:

Version: 1.29.0 (system setup)
Commit: 0f5cfdc2c8c2433028842e16dc5ac1a65da24292
Date: 2021-05-15T01:12:11.112Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Create a new dialog extension
2. Open the main.ts

The deprecated message is ambiguous: **createModelViewDialog** is deprecated use **createModelViewDialog**

``` typescript
        /**
         * @deprecated please use the method createModelViewDialog(title: string, dialogName?: string, width?: DialogWidth) instead.
         * Create a dialog with the given title
         * @param title The title of the dialog, displayed at the top
         * @param isWide Indicates whether the dialog is wide or normal
         */
        export function createModelViewDialog(title: string, dialogName?: string, isWide?: boolean): Dialog;
```

Question
createModelViewDialog is deprecated or not?

**Comment by Charles-Gagnon** [comment]
That version of the function is (with the isWide parameter) - you should use the version that takes a `width?: DialogWidth` parameter. It provides all the same functionality and more.

**Comment by m4ss1m0g** [comment]
No `createModelViewDialog(title: string, dialogName?: string, width?: DialogWidth)` with the `width` parameter inside the d.ts

**Comment by Charles-Gagnon** [comment]
A solid point - forgot that one is still in proposed : https://github.com/microsoft/azuredatastudio/blob/main/src/sql/azdata.proposed.d.ts#L648

We're not going to remove the old function anytime soon so feel free to continue using it until we get the new one into the stable API.

@alanrenmsft - Note to us that we probably shouldn't be deprecating stuff in the main API until we have a replacement there - it's pretty confusing if people aren't familiar with the proposed API and given our usual time frame for actually removing stuff waiting a bit longer for it to make it into stable isn't a huge deal.
