### ISSUE TITLE
Notebook doesn't prompt to install required dependencies for Powershell kernel when opening existing Notebook

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15656]
0. Delete existing Python installation and reinstall base dependencies
1. Open Notebook that is configured to use the Powershell kernel

The Notebook just hangs and never prompts the user or completes. If I create a new Notebook and switch to the Powershell kernel I'm then prompted to install the Powershell kernel after which opening the original Notebook works as expected.

**Comment by lucyzhang929** [comment]
@Charles-Gagnon, which ADS version are you using? I was unable to repro on RC. 

After reinstalling Python and opening https://github.com/microsoft/azuredatastudio-docs/blob/main/Guides/Release-Testing/Notebooks/PowerShell/Simple-PS.ipynb, the configure Python wizard opened:


![Screen Shot 2021-06-09 at 6 19 24 PM](https://user-images.githubusercontent.com/23462877/121449878-82439a80-c94f-11eb-99cf-0c7d8cd6e548.png)


Version: 1.30.0-rc1 (user setup)
Commit: dc69b012a818f6c0d2811318cd3a17e28a4a4450
Date: 2021-06-09T19:01:58.926Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Charles-Gagnon** [comment]
Interesting, yeah this is with RC1 (and main). I haven't tested whether this is a regression though, but I imagine it wouldn't be since we haven't touched this code in a while. I'll try to dig into it a bit more and see if I can figure out what's going on.

(this also repros if you just delete the powershell-kernel package and then try to open the Notebook. Which seems to be the same behavior as https://github.com/microsoft/azuredatastudio/issues/15652 so probably the same issue)

**Comment by lucyzhang929** [comment]
I was able to repro after deleting powershell-kernel package and trying to open a powershell notebook (both on stable and RC so not a regression).

**Comment by chlafreniere** [comment]
@lucyzhang929 does this imply that our package detection logic isn't working correctly? Please add a test case to the ADO test plan.

**Comment by lucyzhang929** [comment]
I believe it has something to do with the way we cache our kernel setups when the jupyter server is started. I'll investigate some more and add a test case.
