### ISSUE TITLE
Notebook Insert Link paths have a / when editing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15663]
1. Create text cell in Notebook
2. Insert a link to a local file
3. Select the link and click the `Insert Link` button to edit it

The path is displayed with a prefixed / on windows

`/C:/Users/chgagnon/AppData/Local/Programs/Azure%20Data%20Studio%20-%20RC1/resources/app/out/vs/code/electron-browser/workbench/Desktop/SQLQuery_1.sql`

**Comment by MsSQLGirl** [comment]
I had a look at this. While it's harmless for now, I think it will cause confusion. 
I noticed that with the "/" it seems to still be working OK after clicking `Insert` or `Cancel`. 
Also when adding the link again (without the "/") works too. 

Can we please get this fix soon please?
