### ISSUE TITLE
Navigation buttons not showing when notebook is opened by link

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#15679]
Opening a notebook by link does not show navigation buttons.
Navigation buttons are only present when opening a notebook from tree view or when it's opened by using the previous/next buttons from a notebook.

- Azure Data Studio Version:
Version: 1.30.0-rc1
Commit: dc69b012a818f6c0d2811318cd3a17e28a4a4450
Date: 2021-06-09T19:00:06.170Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 20.5.0

**Comment by Charles-Gagnon** [comment]
Does this happen all the time for you? I think this is probably a duplicate of https://github.com/microsoft/azuredatastudio/issues/14628 - but that was something that seemed to happen intermittently.

**Comment by barbaravaldez** [comment]
@Charles-Gagnon, I think it's a duplicate. I'll close this issue.
