### ISSUE TITLE
Investigate Scrollable View test failure

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#15678]
Investigate Scrollable View test intermittent test failure -

  1) ScrollableView
       shrinks views correctly:

      AssertionError [ERR_ASSERTION]: view1 is entire size
      + expected - actual

      -0
      +200
      
      at Context.<anonymous> (file:///Users/runner/work/1/s/out-build/sql/base/test/browser/ui/scrollableView/scrollableView.test.js:81:20)

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/15790.
