### ISSUE TITLE
Queries are very slow for columns that contain large values

### ISSUE THREAD

**Issue by ihorbond** [microsoft/azuredatastudio#15672]
Issue Type: <b>Bug</b>

After applying latest update queries take FOREVER, seems like it just hangs. Same queries connected to exactly the same server work perfectly fine in SSMS, under 3 seconds. I think this is due to the large size of one of the nvarchar(max) columns, ADS can't handle it well

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@ihorbond are you saying it worked fine for ADS version 1.28?

**Comment by ihorbond** [comment]
@alanrenmsft I believe so but don't take my word for it. If it helps I can restore to 1.28 and try the same query ?

**Comment by alanrenmsft** [comment]
@ihorbond, yes, it would definitely help.

**Comment by ihorbond** [comment]
@alanrenmsft sorry for the late reply. Installed 1.28 and it's the same problem. Taking a closer look it does seem like it slows down a lot on a row that has nvarchar(max) column with a very large value. LEN(my_col_name) returns 3884005 hope this helps

**Comment by cheenamalhotra** [comment]
@ihorbond 

This should be resolved in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), as we addressed large string read issues in PR https://github.com/microsoft/sqltoolsservice/pull/2161 recently. I will proceed to close this issue.
