### ISSUE TITLE
Move to.. failing to successfully move notebook

### ISSUE THREAD

**Issue by tobarnes** [microsoft/azuredatastudio#15690]
- Azure Data Studio Version:

Steps to Reproduce:
Here, I tried a simple move of a notebook from one folder to a different folder in the same book.  The result seems to be the notebook is moved to the content folder and the TOC is not updated to either remove the original definition or to add the new one.  This will results in many errors from ADS as a result of things not being properly modified for this operation.  I've captured them here.  The proof of the lack of modification is that merely moving the file back to its original location results is a complete healing of all the issues.
1.
[Move To issues.docx](https://github.com/microsoft/azuredatastudio/files/6635960/Move.To.issues.docx)

**Comment by tobarnes** [comment]
![image](https://user-images.githubusercontent.com/85718225/121728321-f8581680-caa1-11eb-8cbf-6d89ccbbb473.png)
applying version info.

**Comment by MsSQLGirl** [comment]
@barbaravaldez - can you please help triage this also?

**Comment by MsSQLGirl** [comment]
@tobarnes - can you please confirm that this is a regression?

**Comment by tobarnes** [comment]
No, I would not classify this as a regression.  It is more rightly classified as a latent bug that was only now uncovered.

**Comment by barbaravaldez** [comment]
@MsSQLGirl, I think this might be an edge case. I'll try to repro

**Comment by tobarnes** [comment]
We were able to reproduce this issue reliably, multiple times, but the function also seems to work reliably in other cases. We believe this to be a corner-case at this time, which needs to be debugged and fixed, but this issue has likely been in this function since it’s release in March.  Therefore, by not applying any changes we are no worse off than we have been for the past 3 months.  Failures should be restricted to single user events and it is quite easy to resolve the breakage by returning the file to its original location.  To complete the move will require manual steps for now for these cases, but this has not been reported in the 3 months since release.  It seems likely we won’t see any cases of it before the July release, where we can apply a true fix.

Recommendation: not to apply a change for the June release.  Failures are unlikely, given we had no cases reported since the March release of this function.

**Comment by kburtram** [comment]
Approved in shiproom
