### ISSUE TITLE
Installed python libraries are not recognised

### ISSUE THREAD

**Issue by BilalHaniff** [microsoft/azuredatastudio#15696]
I'm using an external Python installation.  I was able to create a notebook and change the kernel to python3. However, I am no longer able to change the kernel in my notebook. Its stuck on loading kernel.

ADS wants to install the required dependencies. I see the the following in the output

Encountered an error when trying to retrieve list of installed packages: Unexpected token C in JSON at position 4273

My packages are visible via pip and are all installed

How do I fix this ?

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Could you take a look at this when you get a chance?

**Comment by lucyzhang929** [comment]
Hi @BilalHaniff, could you share the version of ADS you are using and the OS please?

Just to confirm, you were able to use this same external Python installation and run Python notebooks previously?

**Comment by chlafreniere** [comment]
Closing as we need more info here. Feel free to reopen if you can provide more details, @BilalHaniff!
