### ISSUE TITLE
Add a field for server description in connection form and show in both recent connection history and servers tab

### ISSUE THREAD

**Issue by rsaa** [microsoft/azuredatastudio#157]
- SQL Operations Studio Version:

Steps to Reproduce:

**Comment by kevcunnane** [comment]
Would this description be shown in the hovertext?

**Comment by rsaa** [comment]
Hi,

Sorry, I wasn't clear with my feature request. Here's what I meant:

At our place, we use IP addresses of DB servers to connect to. We would
like to give them a meaningful name in SQL Operations Studio so we can pick
the server by name without having to remember IP addresses in Connection/
Recent History pane on right and servers tab on left.

[image: Inline image 2]

Hope that helps.


Thanks.

**Comment by GitClickOk** [comment]
Another reason is, we can have multiple connections to the same instance, but different databases, or different credentials or purposes. A Description field to differentiate and display in Servers Tree will be really useful.

**Comment by cheenamalhotra** [comment]
Connection "Name" is supported in ADS, closing this feature as its available.
