### ISSUE TITLE
SQL Agent Extension Unreliable

### ISSUE THREAD

**Issue by therealdandecker** [microsoft/azuredatastudio#15707]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install SQL Agent Extensin
2. Ensure you have proper permissions to access SQL Agent
3. Right click and go to 'Manage' on a DB connectin
3. Sometimes the SQL Agent appears, sometimes it does not, and there does not seem to be documentatino or specification on the type of security access required to make it appear when managing a DB.  
4. I am a server admin for two of our SQL Servers and so far the agent somtimes shows, and sometimes does not; on one DB where I am DB owner for instance the agent does not appear.

**Comment by therealdandecker** [comment]
It’s not. At least not reliably. I am not using any Azure SQL instances in this case.

I feel like it’s likely DB permission related but can’t figure out what that would be. Sometimes it shows, sometimes it doesn’t.

Shows on our ERP, does not on data warehouse.
________________________________

**Comment by cssuh** [comment]
Closing as no logs were provided.
