### ISSUE TITLE
Incorrect formatting of italics in Azure SQL notebooks

### ISSUE THREAD

**Issue by philipnye** [microsoft/azuredatastudio#15705]
Issue Type: <b>Bug</b>

Steps to reproduce:
1. Add a text cell to a SQL notebook containing two words to be italicised which themselves contain an underscore e.g. "A _table_here_ and then _another_here_"

Actual result: The words "table_here", "and", "then" and "another_here" are all italicised.
Expected results: Only the words "table_here" and "another_here" are italicised.

Azure Data Studio version: azuredatastudio 1.29.0 (0f5cfdc2c8c2433028842e16dc5ac1a65da24292, 2021-05-15T01:12:11.112Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.3.0
azdata-sanddance|msr|3.2.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by chlafreniere** [comment]
I tried this on our latest builds, and was unable to repro this issue:

<img width="260" alt="image" src="https://user-images.githubusercontent.com/40371649/165638464-3d745c47-9817-4588-8c6a-4bcfd6c41707.png">

Please feel free to reopen with further repro steps if this is still impacting you. Thanks!
