### ISSUE TITLE
Manage Packages Icon overlaps text

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#15710]
![manage-packages](https://user-images.githubusercontent.com/18150417/121950100-145ff000-cd0e-11eb-8910-50f09e3a245f.PNG)

It looks like the Manage Packages icon is overlapping the Manage Packages text.
This is from the "non-preview features" version of the insiders build.

**Comment by chlafreniere** [comment]
Fixed recently with various PRs fixing actionbar issues
