### ISSUE TITLE
add telemetry for project dashboard

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#15725]
Update [power BI dashboard](https://msit.powerbi.com/groups/a799d1d3-bb58-4048-a03c-52aa8e37f3b8/reports/a00c3a55-8930-410d-a822-2c7a1cf6e703/ReportSectionb28ac1acaf5384081038) to easily show telemetry for project dashboard opening and add telemetry for any other useful information specific to the project dashboard(if we can think of any other useful to track).

**Comment by Charles-Gagnon** [comment]
FYI we already have an event for when dashboards are opened, so you should be able to use that as long as you're giving it a unique name 

https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/api/browser/mainThreadModelViewDialog.ts#L58

**Comment by kisantia** [comment]
ah ok thanks good to know! I noticed that it wasn't in the data workspace extension actions in the power BI dashboards, so we'll just need to add that so it's easy to find

**Comment by kisantia** [comment]
I added the sql projects dashboard daily users to the Data Developer Experiences report so it's easier to find
