### ISSUE TITLE
A11y_AzureDataStudioSQLMigration_AzureSQLMigration_ScreenReader:NVDA is reading the link as learn more link which is not descriptive enough for the users when tabbing to the link.

### ISSUE THREAD

**Issue by Shivamd1** [microsoft/azuredatastudio#15738]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.4;#AINotInScope;#NVDA;#JAWS;#Linkpurpose;#STP

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10
Screen Reader:NVDA,JAWS

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter.
4. Start Screen Reader:NVDA
5. Tab till learn more link using tab key.

### Actual:
NVDA is reading the link as learn more link which is not descriptive enough for the users when tabbing to the link.
**This issue is also observed with JAWS.**

### Expected:
NVDA should read as learn more things you need before migration link when tabbing to the link.

### User Impact:
Screen reader users will not understand the purpose of the link.

**Comment by Yashi1201** [comment]
Closing the bug as the issue is not repro
Version: 1.42.0-insider(user-setup)
![15738_NVDA](https://user-images.githubusercontent.com/93374043/220328269-860b7ffb-e7b2-4b32-9161-c73ba896ce71.png)
![15738_JAWS](https://user-images.githubusercontent.com/93374043/220328308-9306063b-dba2-4017-9a38-fefb2356b2c4.png)

**GithubTags**:#Closed;
