### ISSUE TITLE
A11y_AzureDataStudioSQLMigration_MigratetoAzureSQL_MigrationAssessment:On pressing Tab key the focus does not move inside the migration assessment page but it remains on the azure SQL target page.

### ISSUE THREAD

**Issue by Shivamd1** [microsoft/azuredatastudio#15740]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.3;#AINotInScope;#Keyboard

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter.
4. Tab till Migrate to azure sql and press enter.
5. Add azure account and tab till next button and press enter.
6. Select SQL server on azure virtual machine radio button and tab till view/select button and press enter.
7. Press tab key and check if the focus moves inside the migration assessment screen.

### Actual:
On pressing Tab key the focus does not move inside the migration assessment page but it remains on the azure SQL target page.
**This issue is also observed in scenario:**

- Migration In progress-Migration Cutover

### Expected:
On pressing Tab key the focus should move inside the Migration assessment page.

### User Impact:
Keyboard only users will not be able to navigate through the page.

**Comment by fsteffi** [comment]
issue does not repro
#Closed;

Version: 1.43.0-insider (user setup)
Commit: 9d16a48dee06c0533c5c6e405e775685d098a5ae
Date: 2023-03-20T05:49:59.560Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

![Tab focus](https://user-images.githubusercontent.com/24580570/228227413-6c1226ef-0804-4b4b-9354-29d8d2b10062.gif)
