### ISSUE TITLE
A11y_AzureDataStudioAAE_PG1_Compute + Storage_Keyboard: Informative tool tips present on the screen are not getting keyboard focus.

### ISSUE THREAD

**Issue by krrish2021** [microsoft/azuredatastudio#15760]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#Keyboard;#WCAG2.4.3;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio-AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till Azure Arc Controller tree and tab to the node present under it
4. Tab to child node "PG1" and open manage and tab to "Compute + Storage" page
5. Tab to Informative tool tips

### Actual:
Informative tool tips present on the screen are not getting keyboard focus.

### Expected:
Informative tool tips present on the screen should get keyboard focus.

### User Impact:
Keyboard users will get confused if the tool tip do not focus in logical sequenced order.

**Comment by krrish2021** [comment]
issue is not reproducing in the version 20.3.5 , as the tooltips are disabled now. Please find the attachment.

https://user-images.githubusercontent.com/85863543/127601036-98370d1c-6a32-467a-b085-141cbaefd435.mp4

**Comment by krrish2021** [comment]
@candiceye the issue can not be verified as the "pg1" control is not available in latest azure data studio @nasc17 Please reopen the bug.
![Screenshot (182)](https://user-images.githubusercontent.com/85863543/150961614-1e4e4e1a-aa19-47d9-b99a-e6af876d8c9c.png)

**Comment by candiceye** [comment]
The tooltips are being highlighted in the postgres dashboard's compute + storage tab, as shown below in the screen recording:
[https://msit.microsoftstream.com/video/33b20840-98dc-a228-114a-f1ec8fb7aa5d](https://msit.microsoftstream.com/video/33b20840-98dc-a228-114a-f1ec8fb7aa5d)
