### ISSUE TITLE
A11y_AzureDataStudioAAE_Sql Instance 1_Compute + Storage_Keyboard: Only color is used to identify between normal text of screen and "scaling computes vCores and memory" link

### ISSUE THREAD

**Issue by krrish2021** [microsoft/azuredatastudio#15771]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AzureDataStudio_AAE_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#Keyboard;#WCAG1.4.1;#AINotInScope;

### Environment Details:
Application Name: Azure Data Studio-AAE
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure arc and Azure data ClI
2. Connect to Azure Arc Controller
3. Tab till Azure Arc Controller tree and tab to the node present under it
4. Tab to child node "Sqlinstance1" and open manage and tab to "Compute + Storage" and press enter
5. Tab to "scaling computes vCores and memory" link
6. Check the link if it has a tooltip or different font or bold text or underline.

### Actual:
Only color is used to identify between normal text of screen and "scaling computes vCores and memory" link.
Similar issue is observed through out the application.

### Expected:
Only color should not be used to identify between normal text of screen and "scaling computes vCores and memory" link. Link can have a tooltip or different font or bold text or underline.

### User Impact:
Keyboard users will get confused to identify between normal text and link on screen.

**Comment by Harika1702** [comment]
GitHub Tags: #Closed;
