### ISSUE TITLE
Some Notebook extension tests are broken

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15791]
There were a couple tests in https://github.com/microsoft/azuredatastudio/blob/main/extensions/notebook/src/test/book/bookTocManager.test.ts there were broken during the VS Code merge and it wasn't an obvious fix.

They should either be fixed or removed if they don't seem useful.

**Comment by barbaravaldez** [comment]
@Charles-Gagnon, I can start working on this
