### ISSUE TITLE
R package installs using ADS 1.30.0 & Machine Learning 0.10.0 add-in into SQL 2019 fails

### ISSUE THREAD

**Issue by Stevew7777** [microsoft/azuredatastudio#15802]
Installing R packages to SQL 2019 from ADS 1.30.0 using Machine learning 0.10.0 Add in - seems to be failing.
It seems the ODBC driver error is now fixed from 1.29.0 ( thanks!! ) but it seems the R package deployment code is failing.
Please post back here if you need other ADS error logs etc to be supplied.
---------------------------------------------------------------------------------------------
ADS Version: 1.30.0 (system setup)
Commit: 59c4b8e90cf2d3a24bed72623197f10f8d090fdc
Date: 2021-06-16T19:04:08.858Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.14393
---------------------------------------------------------------------
Code output when R package deployment fails :( it requires upgrade from sqlmlutils from 1.0.3 to 1.1.0 after upgrade from ADS 1.29.0 to 1.30.0 )

    stdout: 
    stdout: Installing collected packages: sqlmlutils
    stdout: 
    stdout: 
    stdout:   Found existing installation: sqlmlutils 1.0.3
    stdout: 
    stdout: 
    stdout:     Uninstalling sqlmlutils-1.0.3:
    stdout: 
    stdout: 
    stdout:       Successfully uninstalled sqlmlutils-1.0.3
    stdout: 
    stdout: 
    stdout: Successfully installed sqlmlutils-1.1.0
    stdout: 
    stdout: 
    stdout: Package sqlmlutils exists on server. Set upgrade to True in install to force upgrade.
    stdout: The version of sqlmlutils you are trying to install is 1.1.0.
    stdout: The version installed on the server is 1.0.3
    stdout:     
    stdout: 
    stdout: 
    stdout: 
    stdout: R version 3.5.2 (2018-12-20) -- "Eggshell Igloo"
    stdout: Copyright (C) 2018 The R Foundation for Statistical Computing
    stdout: Platform: x86_64-w64-mingw32/x64 (64-bit)
    stdout: 
    stdout: 
    stdout: R is free software and comes with ABSOLUTELY NO WARRANTY.
    stdout: You are welcome to redistribute it under certain conditions.
    stdout: Type 'license()' or 'licence()' for distribution details.
    stdout: 
    stdout: 
    stdout:   Natural language support but running in an English locale
    stdout: 
    stdout: R is a collaborative project with many contributors.
    stdout: Type 'contributors()' for more information and
    stdout: 'citation()' on how to cite R or R packages in publications.
    stdout: 
    stdout: 
    stdout: Type 'demo()' for some demos, 'help()' for on-line help, or
    stdout: 'help.start()' for an HTML browser interface to help.
    stdout: Type 'q()' to quit R.
    stdout: 
    stdout: 
    stdout: > 
    stdout: formals(quit)$save <- formals(q)$save <- "no"
    stdout: 
    stdout: > 
    stdout: library(sqlmlutils)
    stdout: 
    stdout: > 
    stdout: connection <- connectionInfo(driver="ODBC Driver 17 for SQL Server", database="master", server="WIN-EIJV319T4OF")
    stdout: 
    stdout: > 
    stdout: r = getOption("repos")
    stdout: > r["CRAN"] = "https://cran.r-project.org"
    stdout: > options(repos = r)
    stdout: > pkgs <- c("abn")
    stdout: > sql_install.packages(connectionString = connection, pkgs, scope = "PUBLIC")
    stdout: 
    stdout: (package install may take a few minutes, set verbose=TRUE for progress report)
    stdout: 
    stdout: 
    stderr: Error: Error in SQL Execution: Error: <SQL> '
    stderr: EXEC sp_execute_external_script
    stderr: @language = N'R'
    stderr: ,@script = N'
    stderr: pkgGetLibraryPath <- function (scopeint) 
    stderr: {
    stderr:     if (!all.equal(scopeint, as.integer(scopeint))) {
    stderr:         stop("pkgGetLibraryPathExtLib(): scope expected to be an integer", 
    stderr:             call. = FALSE)
    stderr:     }
    stderr:     if (scopeint == 0) {
    stderr:         extLibPath <- Sys.getenv("MRS_EXTLIB_SHARED_PATH")
    stderr:     }
    stderr:     else if (scopeint == 1) {
    stderr:         extLibPath <- Sys.getenv("MRS_EXTLIB_USER_PATH")
    stderr:     }
    stderr:     else {
    stderr:         stop(paste0("pkgGetLibraryPathExtLib(): invalid scope value ", 
    stderr:             scopeint, ""), call. = FALSE)
    stderr:     }
    stderr:     extLibPath <- normalizePath(extLibPath, mustWork = FALSE)
    stderr:     extLibPath <- gsub("\\\\", "/", extLibPath)
    stderr:     return(extLibPath)
    stderr: }
    stderr: getScopeLibraryPaths <- function () 
    stderr: {
    stderr:     publicPath <- try(pkgGetLibraryPath(0), silent = TRUE)
    stderr:     if (inherits(publicPath, "try-error")) {
    stderr:         publicPath <- NA
    stderr:     }
    stderr:     privatePath <- try(pkgGetLibraryPath(1), silent = TRUE)
    stderr: 
    stderr: Execution halted
    stderr:

**Comment by Stevew7777** [comment]
Hi everyone, 

Ive tested 1.31.0 Insiders system build, and it has installed R packages OK ,  using the Machine Learning 0.10.0  extension.

Thanks for the prompt fix - very much appreciated! 

Now we can use ADS with SQL Managed Instances to allow us to move forward with Azure!

Thanks.

**Comment by llali** [comment]
Hi @Stevew7777 . Thanks for reporting this bug. I'm going to close it since you verified the fix in the latest version. Please reopen if you still see the issue.
