### ISSUE TITLE
Button icons overlapping text

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#15815]
Issue Type: <b>Bug</b>

Buttons in the toolbar have icons overlapping the text of the button.

![image](https://user-images.githubusercontent.com/13488/122582587-4df26d00-d026-11eb-8545-a790c13a8294.png)

Azure Data Studio version: azuredatastudio-insiders 1.30.0-insider (35832e83da0dc4848a08a026d34b8ed9d116481b, 2021-06-18T06:11:30.417Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (19.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@Charles-Gagnon , I thought you have fixed this, but I am still seeing this too in today's insider build.

**Comment by alanrenmsft** [comment]
a few more places:
![image](https://user-images.githubusercontent.com/13777222/122606321-9c573a00-d02d-11eb-83d0-8375602069dc.png)
![image](https://user-images.githubusercontent.com/13777222/122606374-b1cc6400-d02d-11eb-9b32-9a72c9c6a1c7.png)

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/122617009-5657a180-d040-11eb-92c9-8c7aff35d143.png)
