### ISSUE TITLE
Preferences Query Editor > Results (number of rows) is ignored

### ISSUE THREAD

**Issue by eddieyanez** [microsoft/azuredatastudio#15814]
Issue Type: <b>Bug</b>

Change the preference for:

Query Editor > Results: In Memory Data Processing Threshold
from 5000 to 50000

<img width="825" alt="image" src="https://user-images.githubusercontent.com/1080027/122568697-a4a07c80-d00f-11eb-9fc6-a8c22cc65e43.png">

Run a query with over 32K results in notebook. 

Expected: the full list with 32K rows. Instead: I can only see 5K.

<img width="223" alt="image" src="https://user-images.githubusercontent.com/1080027/122568825-c6016880-d00f-11eb-899a-7ca3b35090cd.png">

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T18:57:01.467Z)
OS version: Darwin x64 19.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1068NG7 CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 3|
|Memory (System)|16.00GB (1.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.10.0
azdata-sanddance|msr|3.2.0

</details>

**Comment by lucyzhang929** [comment]
Hi @eddieyanez, this is the setting for maximum number of rows displayed in notebook result tables:
<img width="506" alt="Screen Shot 2021-06-18 at 6 59 43 AM" src="https://user-images.githubusercontent.com/23462877/122572806-f393e500-d002-11eb-9e3d-b06be2266dca.png">

Feel free to reopen this issue if you have any other questions.

**Comment by eddieyanez** [comment]
> Hi @eddieyanez, this is the setting for maximum number of rows displayed in notebook result tables:
> <img alt="Screen Shot 2021-06-18 at 6 59 43 AM" width="506" src="https://user-images.githubusercontent.com/23462877/122572806-f393e500-d002-11eb-9e3d-b06be2266dca.png">
> 
> Feel free to reopen this issue if you have any other questions.

Hi Lucy, the second screenshot is of the notebook result tables. Another screenshot with more of the table - the rest is hidden due to confidentiality reasons. Does the setting not control this result table?

<img width="252" alt="image" src="https://user-images.githubusercontent.com/1080027/122578859-e9c9ac00-d019-11eb-8851-4ce78ce9c583.png">

**Comment by lucyzhang929** [comment]
The **Notebook: Max Table Rows** setting controls the number of rows displayed in notebook result tables. 

The **Query Editor > Results: In Memory Data Processing Threshold** setting (from your first screen shot) does not control the number of rows displayed.

**Comment by eddieyanez** [comment]
Got it, thanks for explaining.

Apologies for the confusion.
