### ISSUE TITLE
Insiders - icons on new query window no longer aligned properly

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#15829]
- Azure Data Studio Version: 1.30.0-insiders (system setup)
- OS Version: Windows 10 20H2 build

Steps to Reproduce:

1. Open New Query Window

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/11204251/122628882-8887f400-d07e-11eb-9f92-eb9ce67ed1fd.png)

**Comment by alanrenmsft** [comment]
thanks @wsmelton for letting us know, we have fixed the issue: https://github.com/microsoft/azuredatastudio/issues/15815
