### ISSUE TITLE
content alignment changed for the account dropdown in firewall rule dialog 

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#15820]
now:
![image](https://user-images.githubusercontent.com/13777222/122601599-6498c400-d026-11eb-8e9a-f6c056c44211.png)

1.30 stable:
![image](https://user-images.githubusercontent.com/13777222/122601646-74b0a380-d026-11eb-90d0-b5e60ecbe5de.png)

**Comment by kburtram** [comment]
Approved in shiproom if there is time in July
