### ISSUE TITLE
entry point for resource deployment in connections view is gone

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#15824]
![image](https://user-images.githubusercontent.com/13777222/122606702-361ee700-d02e-11eb-8d05-93d41402435f.png)

**Comment by Charles-Gagnon** [comment]
This is probably a good time to talk about finding a better place for this - it's really not discoverable at all in its current location.

**Comment by alanrenmsft** [comment]
@abist any update?

**Comment by kburtram** [comment]
Approved in shiproom
