### ISSUE TITLE
Installing Notebook dependencies failed with error: EPERM: operation not permitted, unlink 'C:\python-3.6.6-win-x64-0.0.1-offline\0.0.1\python.exe'

### ISSUE THREAD

**Issue by sqllensman** [microsoft/azuredatastudio#15835]
After unfortunately accepting the "upgrade" to Version 1.30 discovered that 
1. The required version of Python has changed
2. The program continues to be completely incapable of actually doing this upgrade.

Upgrade failed with error message

Installing Notebook dependencies failed with error: EPERM: operation not permitted, unlink 'C:\python-3.6.6-win-x64-0.0.1-offline\0.0.1\python.exe'

The requirement to use an Offline install to get Python working was a reflection of earlier versions inability to do a proper install for any machine behind a Corporate firewall.

**Comment by sqllensman** [comment]
This is simply a continuation of Issue #13424

There appears to have been now attempt to make this program usable in real world secure setups.

**Comment by lucyzhang929** [comment]
Hi @sqllensman, can you check that Python is not running in Task Manager before upgrading? We close all active notebook sessions before removing the old Python installation but it is possible that something else is using that Python installation and causing the error when we try to remove it.

**Comment by sqllensman** [comment]
Python is not running in Task Manager.

This is purely related to an inability of the Install process to connect to Internet.


The installer cannot get a new version and this should be checked prior to making breaking changes like removing an older working version of Python.

The fact that you cannot properly do an install or upgrade is already a known issue (see #8204 and #13434)

**Comment by lucyzhang929** [comment]
Hi @sqllensman, we have fixed the Python update process to ensure the new version is installed before removing the old version. We have also documented the steps for installing Python offline here: https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-python-offline-installation?view=sql-server-ver15.

Please feel free to comment here or open a new issue if you have any other questions!
