### ISSUE TITLE
A11y_SQL Azure Data Studio_Notebooks - Code cell_Screenreader : The +code and +text options are reading as links but they perform like buttons.

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [microsoft/azuredatastudio#15843]
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

GitHubTags: #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudio_Win32_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG4.1.2;#NVDA;#JAWS;

### Environment Details:
Application Name: SQL Azure Data Studio
Version: 1.30.0-insider (user setup)
Windows Version: Win10
Screen reader : JAWS, NVDA2020.2

### Repro Steps:
Launch Azure Data Studio Insiders application.
Connect to server.
Right-click connection and click New Notebook
Click on cell and select code cell.
Run the screen reader and navigate to the "+code" and "+text" options.
Hit enter to see their operations as a button.

### Actual:
Screen reader is announcing the "+Code" and "+text" options as link but they are performing their operations like buttons. The functionality is opening in the same window screen.

This issue is observed in both the screen readers JAWS and NVDA.

### Expected:
The links should not be read as buttons as they are performing like buttons.

### User Impact:
Screen reader only user will face difficulty to understand and differentiate the functionality of the control.

### Attachment :
https://microsoftapc-my.sharepoint.com/:v:/g/personal/v-asahoo_microsoft_com/EQNsEzeN7vhDtlbsypcqSWwBCdewRPAnYcOZ1Vn1fMBHKg?e=rzt6qD

**Comment by Harika1702** [comment]
<img width="960" alt="15843_A11y_Issue Fixed" src="https://user-images.githubusercontent.com/100270074/217788661-6d99a117-d241-486a-9408-40a44c593a9e.png">
Verified this issue in the below environment.
App Name: Azure data studio Insider
Version: 1.42.0-insider (user setup)
Commit: 99a924dbcdce7bbaa0ab78b19f84e83035e54651
Date: 2023-02-08T06:58:10.882Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
GitHub Tag:#Closed;
