### ISSUE TITLE
A11y_SQL Azure Data Studio_Notebooks - Code cell_Screenreader : Screen reader is announcing the number of list items in the dropdown incorrectly present in the toolbar.

### ISSUE THREAD

**Issue by Ashutoshsahoo164** [microsoft/azuredatastudio#15841]
"[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier."

GitHubTags: #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudio_Win32_Jun2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG4.1.2;#NVDA;#JAWS;#STP

### Environment Details:
Application Name: SQL Azure Data Studio
Version: 1.30.0-insider (user setup)
Windows Version: Win10
Screen reader : JAWS 2021.2105.53 , NVDA2020.2

### Repro Steps:
1. Launch Azure Data Studio Insiders application.
2. Connect to server.
3. Press the context menu key on connection and hit enter on New Notebook
4. Hit enter on cell and select code cell.
5. Run the screen reader and navigate to the "kernel" and "Attach to" combo box in the toolbar section
6. Hit enter to read the items from the drop down.
7. Check that the number of items reading is different from number of items present.

### Actual:
Screen reader is announcing 11 list of items present in the "kernel" dropdown but there are only 6 list of items.
Also for the "Attach for" dropdown it is announcing as 3 items rather it has 2 items only. This issue is observed sometimes when we navigate through Tab and Shift+Tab keys.

This issue is observed in both the screen readers JAWS and NVDA.

### Expected:
Correct number of items must be announced by the screen reader while navigating through combo boxes.

### User Impact:
Screen reader only user will face difficulty to understand .

**Comment by chlafreniere** [comment]
Also reproes in vscode. Opened an upstream issue there: https://github.com/microsoft/vscode/issues/129869.

**Comment by Harika1702** [comment]
![15841_A11y_Issue resolved](https://user-images.githubusercontent.com/100270074/217748775-8bd618bd-66a9-4218-aacc-5f9e7e15ad03.jpg)
![15841_A11y_Issue resolved1](https://user-images.githubusercontent.com/100270074/217749000-517082ea-3558-4196-9523-746601bb7802.jpg)
Verified this issue in the below environment.
Application name: Azure data studio insider
Version: 1.42.0-insider (user setup)
Commit: 99a924dbcdce7bbaa0ab78b19f84e83035e54651
Date: 2023-02-08T06:58:10.882Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
GitHub Tags: #Closed;
