### ISSUE TITLE
A11y_AzureDataStudioSQLMigration_Migrationinprogress_Migrationcutover_Keyboard:The focus moves to the previous database screen after it refreshes automatically and on pressing tab the focus does not appear on the cutover page.

### ISSUE THREAD

**Issue by sspatil123** [microsoft/azuredatastudio#15860]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#SH_AZUREDATASTUDIOSQLMigration_June2021;#SQL Azure Data Studio;#Win10;#FTP;#DesktopApp;#WCAG2.4.3;#AINotInScope;#Keyboard

### Environment Details:
Application Name: SQL Azure Data Studio
Windows Version: Win10

### Repro Steps:

1. Launch the application-Azure Data Studio-Insiders and install extension Azure SQL Migration.
2. Connect to any sql server.
3. Tab till Azure SQL migration Tab and press enter 
4. Tab till "Data migration in progress" and press enter.
5. Tab till ongoing migration under database table header and press enter.
6. Tab till complete cutover button and press enter.
7. Tab till "I confirm that there are no additional...."checkbox na check if the focus remains on the checkbox for sometime.

### Actual:
The focus moves to the previous database screen after it refreshes automatically and on pressing tab the focus does not appear on the cutover page.

### Expected:
The focus should remain on the checkbox as long as the user is not performing any action.

### User Impact:
Keyboard users will not be able to tab inside the cutover window after the database screen refreshes.

**Comment by aasimkhan30** [comment]
We have fixed this issue in the insiders and this issue is no longer reproduced.

**Comment by aasimkhan30** [comment]
We have fixed this issue in the insiders and it can no longer be reproduced.
