### ISSUE TITLE
Open Schema Compare from .scmp-file in file explorer

### ISSUE THREAD

**Issue by MartinRyx** [microsoft/azuredatastudio#15880]
In our database projects we have several scmp-files with pre-configured schema compares. 
As now I can use the files by opening the _Schema Compare_ from the context-menu on the connection, and then click _Open .scmp-file_.

If I try to open the file from the file explorer or the project explorer I only get the underlaying XML-file, which mostly often isn't very useful.
It would be great to open a Schema Compare tab with the selected file loaded.

An alternative would be a context menu with the option _Open in Schema Compare_ or similar.

**Comment by HeidiHasting** [comment]
+1 to this. Very frustrating to have to go to a connection and then open schema compare menus and then open the .scmp file especially when the scmp file already has the database connections setup. Preference would be to be able to open the file from the file menu either as Open File or separate menu item Open Schema Compare file / Open scmp file
