### ISSUE TITLE
Decreasing the width of ADS window messes up notebook toolbar

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#15895]
STABLE:
<img width="737" alt="Screen Shot 2021-06-24 at 9 49 50 AM" src="https://user-images.githubusercontent.com/23462877/123302576-b2537780-d4d1-11eb-996b-769f723eaf57.png">

INSIDERS:
<img width="786" alt="Screen Shot 2021-06-24 at 9 50 11 AM" src="https://user-images.githubusercontent.com/23462877/123302571-b089b400-d4d1-11eb-9180-0f2dd3fd7740.png">

**Comment by MsSQLGirl** [comment]
I'm also seeing this: 
![image](https://user-images.githubusercontent.com/6405919/123732145-4f097280-d84e-11eb-8d5b-41f211d1fec3.png)

Version: 1.31.0-insider (user setup)
Commit: c3e0958f2d13b50b53fc409870aee46dac9695e2
Date: 2021-06-28T05:48:40.392Z
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043
