### ISSUE TITLE
Unable to sign in to Azure Account

### ISSUE THREAD

**Issue by jmarti326** [microsoft/azuredatastudio#15892]
Issue Type: <b>Bug</b>

Click Add An Account 
It opens Microsoft Edge for Mac
URL:https://localhost:49996/signin?nonce=0TYhv7EBUrZ34FIRfw08RQ==

Edge shows The connection for this site is not secure
Localhost sent an invalid response
ERR_SSL_PROTOCO_ERROR

Try to do it in many other browsers and get same result.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T18:57:01.467Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (2.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
profiler|Mic|0.11.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.10.0

</details>

**Comment by Charles-Gagnon** [comment]
This is due to your browser automatically redirecting to https - see this thread for details and workarounds : 

https://github.com/microsoft/azuredatastudio/issues/14493
