### ISSUE TITLE
button component should have options to include icon and label and tooltip

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#1590]
button component should have option to include icon and label similar to action bar

```
this._actionbar.push(this.tab.actions, { icon: true, label: false });
```

In the current implementation, it assumes that if iconPath is valid, it will show both label and icon without tooltip. We should have options to only show icon with tooltip, showing both label and icon.

**Comment by kburtram** [comment]
Closing older unfunded task work-items.
