### ISSUE TITLE
button to enable sqlcmd mode is missing

### ISSUE THREAD

**Issue by mirubid** [microsoft/azuredatastudio#15903]
Issue Type: <b>Bug</b>

There is no button to enable sqlcmd mode making this product useless to me.
According to google, there should be a clearly visible button on the query editor to enable sqlcmd mode but this button does not exist.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3299)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
managed-instance-dashboard|Mic|0.4.2
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.10.0

</details>

**Comment by kburtram** [comment]
@mirubid currently SQLCMD is a preview feature.  Could you please verify in your user setting that the "Enable Preview Features" settings is enabled?

**Comment by mirubid** [comment]
Yes, thank you. That worked. It took me a while to find but finally found
this under Settings->Work Bench->Enable Preview Features and it did work.
