### ISSUE TITLE
Notebooks: Misaligned Execution Count

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#15918]
![image](https://user-images.githubusercontent.com/40371649/123485764-9b8b4e80-d5bf-11eb-93c0-a7dcaba41d62.png)

Looks to be related to the other alignment issues that we've seen; regression since 1.30. Sell must not be selected to show up.

**Comment by corivera** [comment]
Seems to be fixed now. Tested with SQL and Python kernels.
