### ISSUE TITLE
.sqlproj build fails with MSB4181, but builds fine in Visual Studio

### ISSUE THREAD

**Issue by jamesyolk** [microsoft/azuredatastudio#15910]
- Azure Data Studio Version: 1.3
- OS Version: Windows 10 Edu 19043

Steps to Reproduce:

1. Load existing SSDT .sqlproj that builds fine in Visual Studio
2. Right click on project in Explorer tab to Build or Publish
3. Build fails with this output: 
```
	[ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\james\\Documents\\Git\\work\\ReddinetDatabase\\ReddinetDatabase\\ReddinetDatabase.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\james\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.10.0\\BuildDirectory"
    stdout: Microsoft (R) Build Engine version 17.0.0-preview-21302-02+018bed83d for .NET
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout:   Determining projects to restore...
    stdout: 
    stdout:   Restored c:\Users\james\Documents\Git\work\ReddinetDatabase\ReddinetDatabase\ReddinetDatabase.sqlproj (in 103 ms).
    stdout: 
    stdout:   Creating a model to represent the project...
    stdout: 
    stdout: c:\Users\james\.azuredatastudio\extensions\microsoft.sql-database-projects-0.10.0\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4181: The "SqlBuildTask" task returned false but did not log an error. [c:\Users\james\Documents\Git\work\ReddinetDatabase\ReddinetDatabase\ReddinetDatabase.sqlproj]
    stdout: 
    stdout: 
    stdout: Build FAILED.
    stdout: 
    stdout: 
    stdout: c:\Users\james\.azuredatastudio\extensions\microsoft.sql-database-projects-0.10.0\BuildDirectory\Microsoft.Data.Tools.Schema.SqlTasks.targets(586,5): error MSB4181: The "SqlBuildTask" task returned false but did not log an error. [c:\Users\james\Documents\Git\work\ReddinetDatabase\ReddinetDatabase\ReddinetDatabase.sqlproj]
    stdout:     0 Warning(s)
    stdout:     1 Error(s)
    stdout: 
    stdout: 
    stdout: Time Elapsed 00:00:00.84
    stdout: 
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\james\\Documents\\Git\\work\\ReddinetDatabase\\ReddinetDatabase\\ReddinetDatabase.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\james\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.10.0\\BuildDirectory"    … exited with code: 1
	>>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\james\\Documents\\Git\\work\\ReddinetDatabase\\ReddinetDatabase\\ReddinetDatabase.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="c:\\Users\\james\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.10.0\\BuildDirectory"   … errored out: Process exited with code 1
```
I'm not sure if related, but my builds were working with this project before the latest update of Azure Data Studio just few days ago or last week (i can't remember since I don't use everyday). But stopped working and getting this MSB4181 error that I can't find any info on. I tried re-installing the SQL Database Projects extension and check my .net core SDK and follow this guide here https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line?view=sql-server-ver15 to make sure I have all the stuff. Still no luck. Don't know anyone else using ADS with this extension and SSDT, so hoping someone could help me figure out, really don't want to use bunch of apps to work with sql, ADS is almost the perfect one.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
can you try the previous ADS release to confirm if this is a regression? I just tried creating a project in SSDT of AdventureWorks and was able to build it in ADS with the 1.30 release. Please also share a sample project that will repro this. Thanks!

**Comment by jamesyolk** [comment]
I've figured out the problem, I had .NET 6 Preview SDK installed and when I removed it, everything is working again.

**Comment by kisantia** [comment]
glad you got it figured out! Also good for us to know that this doesn't work with the .NET 6 preview SDK :)

**Comment by dzsquared** [comment]
I wanted to leave the .NET 6 preview SDK in place, the workaround I used was to add a global.json file to my project directory. 
https://docs.microsoft.com/en-us/dotnet/core/tools/global-json?tabs=netcore3x

```json
{
    "sdk": {
      "version": "3.1.410",
      "rollForward": "latestFeature"
    }
}
```

I haven't tested if this has any side effects on how the project works in SSDT.
