### ISSUE TITLE
Error at start up

### ISSUE THREAD

**Issue by kundankaushik** [microsoft/azuredatastudio#15933]
Issue Type: <b>Bug</b>

three errors - 
"Couldn't start client AzureResourceProvider"
"Couldn't start client SerializationProvider"
"Failed to start SQL Tools Service"

Furthermore I can't add an account (asking to enable cloud, although it is enabled). I believe it is because of above three errors at the startup

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kundankaushik** [comment]
Attaching the console.log and zipped log folder.
[console.log](https://github.com/microsoft/azuredatastudio/files/6737382/console.log)
[log.zip](https://github.com/microsoft/azuredatastudio/files/6737383/log.zip)

**Comment by Charles-Gagnon** [comment]
It looks like you have some issues running the SQL Tools Service executable. Do you have any antivirus or other software installed on your machine that might be blocking this?

I would also suggest trying out the archive (zip) version of ADS to see if you're seeing the same issue there.

**Comment by kundankaushik** [comment]
It works from archive(zip) version. 
Thanks very much. Appreciate your help.

**Comment by jackhollowaypls** [comment]
For anyone still experiencing this issue. I had this on a fresh MacOS installation on Apple Silicon M1 Pro. Turns out I hadn't run any applications yet using Rosetta. So some of the app must have Rosetta dependancies.

I right clicked Azure Data Studio > Get Info > Open Using Rosetta. Pressed install on the prompt to install Rosetta, app ran successfully. Closed it, followed the above and unticked Open Using Rosetta and now works fine.
