### ISSUE TITLE
Notebook Scrollbar usability issues

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#15943]
- Azure Data Studio Version:
Version: 1.31.0-insider (user setup)
Commit: 5fa53c3519eb0ad6b6b4fd815a2336133cc1fb99
Date: 2021-06-29T05:47:05.813Z
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Editing reasonably length text cell sometimes can cause issues due to positioning of horizontal scrollbar.

See below:
![ScrollDrama](https://user-images.githubusercontent.com/6405919/123873192-f936d800-d8ea-11eb-86f7-3a97180ad606.gif)

For testing purposes, use ~\sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb from SQL 2019 BDC, resize your window to something like 1020 in width. 

Does this issue occur when all extensions are disabled?: n/a

**Comment by MsSQLGirl** [comment]
Related to #14483

**Comment by VasuBhog** [comment]
Needs design discussion around the horizontal scrollbar placement.
