### ISSUE TITLE
Account selector drop-down not disabled during connection

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#15947]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Connect to SQL Server using AAD

Expected: Controls disabled during connection

Actual: Account selector drop-down is not disabled during connection.

![image](https://user-images.githubusercontent.com/599935/123880387-6486a700-d8f7-11eb-912f-9d0cb0743e04.png)

**Comment by cheenamalhotra** [comment]
Closing as this issue is now resolved.
