### ISSUE TITLE
Notebook - Insert Link when linking to parent's parent folder gets inadvertently updated (and not working)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#15942]
- Azure Data Studio Version:
Version: 1.31.0-insider (user setup)
Commit: 5fa53c3519eb0ad6b6b4fd815a2336133cc1fb99
Date: 2021-06-29T05:47:05.813Z
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Windows_NT x64 10.0.19043

> # Update on 7/2/2021:
> Issues described in this bug:
> 1. Insert Link GUI does not work as expected as described below. 
> 2. Creating link to parent's (grand parent's) notebooks/files don't work either. URI doesn't get parsed properly. 

Steps to Reproduce:

1. Save the SQL 2019 BDC notebook locally. 
2. Create a folder inside _diagnose_, call it _julie_. Create a new notebook file inside diagnose/julie. 
3. Create a link to  **C:\Temp\SQL2019BDC\sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb** using **_Insert Link_** in WYSIWYG mode.
> Note: this path must be a full path and must be at least two parents above where your current notebook is. The way I did this was via right click > Copy Full Path from the target notebook. See the gif below. 
>My home folder for the SQL 2019 BDC is C:\Temp\SQL2019BDC, so to repro this you need to update C:\Temp\SQL2019BDC to where you store your SQL2019BDC. 
4. Once **_Insert Link_** is created it looks proper, i.e. `..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb`.
5. Create a new link (with the target link to **C:\Temp\SQL2019BDC\sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb**) using **_Insert Link_** in WYSIWYG mode again. The first link that got created from step 4 will get updated to: `.\....\troubleshooters\tsg100-troubleshoot-bdc.ipynb`; the second link is still OK, i.e. `..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb`.
> Note: this second link's path must be a full path and must be at least two parents above where your current notebook is, just like the instruction on step 3 above.

![InsertLinkParentParentNotebook](https://user-images.githubusercontent.com/6405919/123868917-2e402c00-d8e5-11eb-85e3-1945cfc3c553.gif)

Here's an example of what it looks like after Step 5.

```
| Updates | Comment | Read | Video |
| --- | --- | --- | --- |
| 1\. TSG101 | more robust | [how to](.\....\troubleshooters\tsg100-troubleshoot-bdc.ipynb)<br> |  |
| 2\. TSG036 | test | [how to](..\log-analyzers\tsg036-get-controller-logs.ipynb#steps)<br> | [test](https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-guidance?view=sql-server-ver15) |
| 3\. TSG046 | more robust | [how to](..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb)<br> | [TEST](https://docs.microsoft.com/en-us/sql/azure-data-studio/notebooks/notebooks-guidance?view=sql-server-ver15) |
|  |  |  |  |
```

Note: to clarify **_Insert Link_** in WYSIWYG looks like this:
![image](https://user-images.githubusercontent.com/6405919/123900134-59467200-d91d-11eb-8085-9ac1517a01ca.png)

I'm currently blocked when creating a link to parent's parent file, because using **Insert Link** does not work and causes bad URI format, and creating a relative path also does not work (ADS shows an error) - see below comment.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by MsSQLGirl** [comment]
Note that both links, i.e `.\....\troubleshooters\tsg100-troubleshoot-bdc.ipynb` and `..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb` that Insert Link created does not work. I got these errors (the message looks the same even though the paths are different):

![image](https://user-images.githubusercontent.com/6405919/123881801-4d958400-d8fa-11eb-8601-26981cb551c3.png)
![image](https://user-images.githubusercontent.com/6405919/123881817-58e8af80-d8fa-11eb-9a23-96111b20c273.png)

Same issue happens on this version too:
Version: 1.30.0 (user setup)
Commit: 59c4b8e90cf2d3a24bed72623197f10f8d090fdc
Date: 2021-06-16T19:04:08.858Z
VS Code: 1.53.0
Electron: 11.2.2
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by smartguest** [comment]
From my research, this  appears to be a bug caused by document.execCommand('insertHTML'), which is not handled on the ADS side, the escaped URL and name are formed correctly when they are passed into the command but the result in the HTML doc is not correct. also every subsequent insertion of the URL causes the dots in the previous URLS to increment by 1.

**Comment by smartguest** [comment]
Also apparently the way URLs are parsed in the notebook is that the URL has to be entered in a specific way: file://~sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb unlike web addresses.

**Comment by smartguest** [comment]
@MsSQLGirl As of right now, it appears that only relative paths, in regard to the current notebook's directory are supported in the notebook editor.

Copying and pasting the local file URL is not supported right now by the code.

 So essentially instead of entering: "~sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb", you have to enter: "..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb" instead, which is not very intuitive for the average user.

**Comment by MsSQLGirl** [comment]
I did use the full path i.e. "C:\Temp\SQL2019BDC\sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb".
Apologies that the way I described it earlier was confusing / misleading.

**Comment by MsSQLGirl** [comment]
Note: 
The Insert Link feature as shown below is supposed to translate full path to a relative path since 2 versions ago. @VasuBhog, can you please keep me honest? :) 
![image](https://user-images.githubusercontent.com/6405919/123899924-fbb22580-d91c-11eb-9a67-52bb2a9fa08b.png)

**Comment by MsSQLGirl** [comment]
Please review the start of this thread as I have updated with clarifying details to describe the repro and where I'm blocked. Let me know if you have any questions :) 

Thank you!

**Comment by smartguest** [comment]
I was not able to reproduce this issue when using the provided Sql Server 2019 Guide built into ADS, it initially replicated what you saw, but after a few tries and restarts, it didn't reproduce anymore. 

What I did was that:
1. I opened the TSG100, clicked save as and saved it into the same location. 
2. Created a new file in diagnose/julie with the same name as yours and then tried to add links via highlighting or entering, and they came out correct one after the other. 

This led to the same problem you were seeing until it no longer happened after a while. (I'm running this via the debugger).

**Comment by MsSQLGirl** [comment]
1. Can you please confirm that the following target links work for you? (manually created)
..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb

2. Can you please share the markdown path that the Insert Link WYSIWYG mode generates after you paste the full path, i.e your equivalent path to my C:\Temp\SQL2019BDC\sqlserver2019\content\troubleshooters\tsg100-troubleshoot-bdc.ipynb full path?

**Comment by VasuBhog** [comment]
> Note:
> The Insert Link feature as shown below is supposed to translate full path to a relative path since 2 versions ago. @VasuBhog, can you please keep me honest? :)
> ![image](https://user-images.githubusercontent.com/6405919/123899924-fbb22580-d91c-11eb-9a67-52bb2a9fa08b.png)

Yes, you are correct the full path does convert to the relative path. I currently did all the repro steps in my latest development/Insiders/Stable (on Mac) and I do not see the issue:
![image](https://user-images.githubusercontent.com/23587151/123902699-28b50700-d922-11eb-8aa3-ffffae395d2b.png)

Will be testing on Windows as well, as this might be targeted just for Windows.  @smartguest were you using windows as well?

**Comment by smartguest** [comment]
Yes that is correct, I am debugging on Windows.

**Comment by smartguest** [comment]
@MsSQLGirl Upon testing it again, opening both files with "open file" on ADS, the link is broken again for both of them (with the additional dots appearing on the previous links if you add another link), The link with ..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb doesn't work.

However, if you "save as" the "tsg-100-troubleshoot-bdc.ipynb" file in the same place, then add the link to the code, it resolves fine no matter how many duplicate links you add and the ..\..\troubleshooters\tsg100-troubleshoot-bdc.ipynb link works.

My path resolves to (without "save as") for the correct path above: <user_folder>\azuredatastudio\.build\builtInExtensions\Microsoft.sqlservernotebook\.build\builtInExtensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\diagnose\julie\....\troubleshooters\tsg100-troubleshoot-bdc.ipynb

With the save as, the same path correctly opens up the file. Guess this must be a context file access issue.

**Comment by smartguest** [comment]
There needs to be a way to preserve the file access even after the editor window is closed, at the moment its only temporary and can easily be broken if markdown mode is clicked on.

**Comment by VasuBhog** [comment]
Yeah, will investigate this further as it must have to do with our link callout dialog/markdown converter.

**Comment by MsSQLGirl** [comment]
Thanks @smartguest and @VasuBhog for investigating this. 

Yes, you're right, I do switch from markdown and WYSIWYG a lot when editing.

**Comment by MsSQLGirl** [comment]
Folks, I updated the first comment with the following to ensure that we are on the same page that it turns out we have two issues here:

> Update on 7/2/2021:
> Issues described in this bug:
> 1. Insert Link GUI does not work as expected as described below.
> 2. Creating link to parent's (grand parent's) notebooks/files don't work either. URI doesn't get parsed properly.

**Comment by kburtram** [comment]
Approved in shiproom
