### ISSUE TITLE
After connecting to the BDC, when expanding HDFS it will thrown error username and password required

### ISSUE THREAD

**Issue by ronking-zhu** [microsoft/azuredatastudio#15952]
Issue Type: <b>Bug</b>

After connecting to the BDC, when expanding HDFS it will prompt to input password and username. however after we input the username and password in the azure data studio dialog. It will keep prompting the username and password. And it will prompt the connection is to a private IP address such as https://172.18.0.6:30080. And then the error username and password required thrown out. 

Azure Data Studio version: azuredatastudio 1.25.1 (e7eacc32c0d20bd4da843320c3bfac231b308c98, 2020-12-11T01:59:24.271Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (2.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
pastetheplan|dre|0.2.0
datavirtualization|Mic|1.12.0
import|Mic|1.3.0

</details>

**Comment by Charles-Gagnon** [comment]
Could you please update to the latest version of ADS (currently 1.30) and then if you still see the issue get the logs as detailed below

**Comment by MH11097** [comment]
Has this problem been solved yet? If yes please let me know! Thanks!!

**Comment by Charles-Gagnon** [comment]
If you're also seeing an issue

1. What version of ADS are you using? Update to the latest if you haven't yet already
2. If it's the latest version (currently 1.31) please attach the logs as requested above.

**Comment by MH11097** [comment]
ADS 
```
Version: 1.31.0 (user setup)
Commit: a430fd2592763ef4c4a406821967e4b7b2b3d876
Date: 2021-07-20T19:43:31.605Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042
```
It works fine when VPN to server's network (both private IP and public IP). But when I turn off VPN and using public IP, only SQL works and HDFS returns errors. 
[console.log](https://github.com/microsoft/azuredatastudio/files/6920896/console.log)
[App_log.zip](https://github.com/microsoft/azuredatastudio/files/6920899/App_log.zip)

**Comment by MH11097** [comment]
This looks like my issue but I'm still not clear how to fix it ?
https://github.com/microsoft/azuredatastudio/issues/7180#issue-492518342

**Comment by Charles-Gagnon** [comment]
I asked the BDC team about this and unfortunately their response was that this was a known issue but currently have no plans to fix it. We can't really do anything about that from the ADS side so I'm going to close this out for now, sorry for not having a better solution for you 

(the response you noted above was from an earlier version of BDC where you could edit the table used to store endpoint information. But that isn't possible any longer - there's no way to modify the endpoints being reported back to ADS)
