### ISSUE TITLE
macOS touchbar RUN option missing

### ISSUE THREAD

**Issue by Abhijit-Revamp** [microsoft/azuredatastudio#15968]
Issue Type: <b>Bug</b>

Latest stable version of AzureDataStudio

When you open a script (.SQL) the RUN option was there on the macOS TouchBar.

In the latest version if you click in the script window, the option goes missing from the TouchBar.

If you run the script by pressing F5 or Run icon and then click in the bottom pane, the Touch Bar shows the same.

See the attached images.

Similar issue was there VSCode https://github.com/microsoft/vscode/issues/123105

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T18:57:01.467Z)
OS version: Darwin x64 20.5.0
![missing](https://user-images.githubusercontent.com/44320018/124126544-69369100-da98-11eb-9f77-0251b20734da.png)
![Visible](https://user-images.githubusercontent.com/44320018/124126573-6f2c7200-da98-11eb-954c-aa2d406e6ff0.jpg)

**Comment by Charles-Gagnon** [comment]
@Abhijit-Revamp Does this still repro with the latest [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)?

**Comment by Abhijit-Revamp** [comment]
Yes. Its repro on 

Version: 1.31.0-insider
Commit: 5fa53c3519eb0ad6b6b4fd815a2336133cc1fb99
Date: 2021-06-29T05:49:12.638Z (2 days ago)
VS Code: 1.56.0
Electron: 12.0.4
Chrome: 89.0.4389.114
Node.js: 14.16.0
V8: 8.9.255.24-electron.0
OS: Darwin x64 20.5.0

**Comment by lucyzhang929** [comment]
Hi @Abhijit-Revamp, I was not able to repro this issue on main or insiders build. Does this happen for both new untitled sql files and saved sql files?

**Comment by Abhijit-Revamp** [comment]
It happens on both saved and untitled files.

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Are you focusing in the editor? (maybe try typing some text too) That's one of the things mentioned in https://github.com/microsoft/vscode/issues/106541 to repo the issue

**Comment by lucyzhang929** [comment]
Yep I can still see the Run Query button in the touch bar when I'm typing. (both main and insiders)

**Comment by Charles-Gagnon** [comment]
Interesting...ok well I have a PR out for pulling over the fix VS Code did (basically just bump the Electron version to get a fixed version there) so we'll probably just get that in and then see if it still repros on the insiders build once that goes out. I'll update here once that happens.

**Comment by Abhijit-Revamp** [comment]
awesome.
Thanks

**Comment by Abhijit-Revamp** [comment]
> Yep I can still see the Run Query button in the touch bar when I'm typing. (both main and insiders)

I know when this works. If you are in Explorer view then it works. In all other views, it breaks.
<img width="79" alt="image" src="https://user-images.githubusercontent.com/44320018/124172929-09f07500-dac8-11eb-881a-cec665d8f20d.png">

**Comment by Charles-Gagnon** [comment]
@Abhijit-Revamp The latest insiders build has my fix, when you get a chance could you test it out and see if it fixes the issue for you?

**Comment by Abhijit-Revamp** [comment]
@Charles-Gagnon 
Bingo. Now the "Run Query" option is continuously available irrespective of which window pane I click.

And its visible even when I am typing in the editor

Thanks a lot

**Comment by Charles-Gagnon** [comment]
Thanks for the confirmation! And thanks for finding that VS Code issue, definitely made this a lot easier to track down 😄
