### ISSUE TITLE
Schema compare fails to returns a change set when comparing against DW

### ISSUE THREAD

**Issue by mattgreenbank** [microsoft/azuredatastudio#15979]
**Issue:** When performing a schema compare from Azure Data Warehouse (source) to Azure Data Studio (target), the schema compare fails to return a result set, the message being 'Initializing Comparison. This might take a moment'. 

**Expected result:**
If a schema compare is peformed in Visual Studio 2019 (v. 16.10.02) using the same database project where Azure Data Warehouse is the source, the change set is returned in approx. 5 minutes.

**Actual result:**
As the schema compare doesn't complete after 40 minutes I end up cancelling the operation. On checking the queries on Azure Data Warehouse, all the schema compare queries have completed successfully.

![image](https://user-images.githubusercontent.com/83944536/124279088-f7655280-db3e-11eb-9c85-8e3b9208b3de.png)

Azure Data Studio version: azuredatastudio 1.30.0

**Comment by kisantia** [comment]
can you please share sample source and target dacpacs so we can repro and investigate this?

**Comment by kisantia** [comment]
closing since we couldn't repro. Might have been fixed by https://github.com/microsoft/azuredatastudio/pull/17184 and https://github.com/microsoft/sqltoolsservice/pull/1250
