### ISSUE TITLE
Azure does not open sql files by double click in folder

### ISSUE THREAD

**Issue by dmarek6108** [microsoft/azuredatastudio#15974]
Issue Type: <b>Bug</b>

When I try to open a .sql file in my documents by double clicking, azure never opens. I have .sql to default to azure. What else am I missing? It seems like if you double click on a sql query file it should open Azure Data Studio if the default app is set.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (9.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
If you right click on a .sql file and select `Open With` and then `Choose another app` you should be able to select Azure Data Studio. When you do so make sure you check `Always use this app to open .sql files`.

Let me know if that doesn't work!
