### ISSUE TITLE
Duplicate "Getting Started" entries in Help menu

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15980]
Version: 1.31.0-insider (user setup)
Commit: e8ba89750bae05438d729302c62f092ce3e5f01c
Date: 2021-07-02T05:29:28.141Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

![image](https://user-images.githubusercontent.com/28519865/124309577-c75a8700-db1f-11eb-9945-dfcb63bf0645.png)

**Comment by alanrenmsft** [comment]
@kburtram are you working on this issue now? If not I can take it over.

**Comment by kburtram** [comment]
@alanrenmsft I was going to fix this now.  Should be done by shiproom review this afternoon.

**Comment by kburtram** [comment]
Approved in shiproom

**Comment by kburtram** [comment]
Fixed in release/1.31
