### ISSUE TITLE
Reloading SQLCMD vars during publish clears ones from publish profile

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#15990]
1. Launch publish project dialog from a project
2. Load profile with 1+ SQLCMD variables in it
3. Click `Reload values from project`

Expected : 

Variables loaded from profile are kept.

Actual :

Variables loaded from profile are cleared, leaving only variables from the project - the user must reload the profile to get the values back.

**Comment by Benjin** [comment]
The described bug behavior matches how SSDT works.  I think I agree with Charles in what feels intuitive, though.
