### ISSUE TITLE
A11y_AzureDataStudio_Filter_Keyboard : When user sorts the column in ascending or descending order, keyboard focus is going to the top of the  screen instead of remaining on the table

### ISSUE THREAD

**Issue by SaisreeDandamudi** [microsoft/azuredatastudio#15999]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:** 
#A11yMAS; #A11yTCS; #SH-AzureDataStudio-June2021; #SQL Azure Data Studio; #Win10; #DesktopApp; #WCAG2.4.3; #AINotInScope; #Keyboard;

### Environment Details:
Azure Data Studio Version: 1.30.0 (user setup)
OS Version: 21H1

### Steps to Reproduce:

1. Launch Azure Data Studio
2. Connect to any SQL server and write a query
3. Tab till results grid and press F3 so that the filters pop-up will open
4. Tab till "Sort Ascending" button and press enter and verify the keyboard focus

### Actual:
When user sorts the column in ascending or descending order, keyboard focus is going to the top of the  screen instead of remaining on the table

### Expected:
When user sorts the column in ascending or descending order, the keyboard focus should remain on the table

### User Impact:
Keyboard users and screen reader users will get confused if the focus order is not proper

**Comment by Charles-Gagnon** [comment]
@alanrenmsft

**Comment by v-supupp** [comment]
#A11yMAS;#A11yTCS;#SH-AzureDataStudio-June2021;#SQL Azure Data Studio;#Win10;#DesktopApp;#WCAG2.4.3;#AINotInScope;#Keyboard;A11ySev2;

**Comment by v-mtatikonda** [comment]
#A11ySev2;

**Comment by VijayaBharathyA** [comment]
#Closed; #Regressed:06-23-23;

Verified issue in below environment :
Issue is fixed
Version: 1.44.1 (user setup)
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:12:48.765Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
![ascending](https://github.com/microsoft/azuredatastudio/assets/100189407/420740d2-4efa-41a7-94e2-3752745baf1c)
