### ISSUE TITLE
Support for Azure DevOps

### ISSUE THREAD

**Issue by edwardkutin** [microsoft/azuredatastudio#16001]
Issue Type: <b>Feature Request</b>

Support for Azure DevOps online source code repository, in addition to Github.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19043

**Comment by Charles-Gagnon** [comment]
You should be able to use git repos in ADO just like Github - the source control provider is just a generic git provider so can interact with a git repo hosted on ADO as well.

Or are you asking for support for TFVC?

**Comment by edwardkutin** [comment]
No I am not asking for support for TFVC, but you have provided clarification for me on the issue. I did not realise that I could use the source control provider to connect to ADO. Thanks for replying.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
