### ISSUE TITLE
A11y_AzureDataStudio_Filter_Keyboard : When user sorts the column in ascending or descending order, keyboard focus is going to the top of the application instead of remaining on the table

### ISSUE THREAD

**Issue by 12-shweta** [microsoft/azuredatastudio#16021]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags: #A11yMAS;#A11yTCS;A11ySev2;#SH-AzureDataStudio-Linux-Jul2021;#SQL Azure Data Studio;#Linux;#DesktopApp;#WCAG2.4.3;#AINotInScope;#Keyboard;#FTP;

### Environment Details:
Azure Data Studio Version: 1.31.0-insiders
OS Name: Ubuntu 20.04.2 LTS
GNOME Version: 3.36.8

### Steps to Reproduce:
1. Launch Azure Data Studio
2. Connect to any SQL server and write a query
3. TAB till results grid and press F3 so that the filters pop-up will open
4. TAB till "Sort Ascending" button and press ENTER key and verify the keyboard focus

### Actual:
When user sorts the column in ascending or descending order, keyboard focus is going to the top of the screen instead of remaining on the table

### Expected:
When user sorts the column in ascending or descending order, the keyboard focus should remain on the table

### User Impact:
Keyboard users and screen reader users will get confused if the focus order is not proper

**Comment by 12-shweta** [comment]
Verified the bug in the Azure Data Studio Version: 1.31.0-insiders. The issue is fixed.

**Comment by Rama8345** [comment]
**GithubTags:#Closed;**
