### ISSUE TITLE
Can't connect to SQLServer Database in Explorer

### ISSUE THREAD

**Issue by Avaruz** [microsoft/azuredatastudio#16038]
Issue Type: <b>Bug</b>

Just open the ADS an open a New Query

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (2.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.0
profiler|Mic|0.11.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.10.0

(2 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Closing due to lack of logs required for investigation.  Please let us know if you're still impacted by this issue and can provide requested logs.  Thanks!
