### ISSUE TITLE
Opening a sqlplan file renders incorrectly

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#16042]
This happens in 1.30 stable, not sure if it ever worked. Just noticed it while fixing the editor override stuff.

![image](https://user-images.githubusercontent.com/28519865/124974905-39304600-dfe2-11eb-8128-5242d22c3418.png)

**Comment by alanrenmsft** [comment]
could you please the sqlplan file here? I tested this during the release signoff
![image](https://user-images.githubusercontent.com/13777222/125123042-09994080-e0ab-11eb-8edc-e6a21dbf5f58.png)

**Comment by Charles-Gagnon** [comment]
[plan.sqlplan.txt](https://github.com/microsoft/azuredatastudio/files/6802979/plan.sqlplan.txt)

**Comment by aasimkhan30** [comment]
@Charles-Gagnon, tried the SQL plan file in 1.32.0 stable release and it renders fine.

![image](https://user-images.githubusercontent.com/6816294/135898015-2d1d2e6b-4468-4cf5-b089-e3643ef793e6.png)
