### ISSUE TITLE
Unable to connect using kerberos on macos

### ISSUE THREAD

**Issue by shawn-gmr** [microsoft/azuredatastudio#16048]
Issue Type: <b>Bug</b>

Followed the instructions outlined here: https://docs.microsoft.com/en-us/sql/azure-data-studio/enable-kerberos?view=sql-server-ver15

and still was not able to connect to SQL Server using Windows authentication.

Connection failed due to Kerberos error.
Help configuring Kerberos is available at https://aka.ms/sqlopskerberos
If you have previously connected you may need to re-run kinit.

running klist I can see my ticket.

Running on macOS Big Sur version 11.4

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T18:57:01.467Z)
OS version: Darwin x64 20.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (1.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Code-DJ** [comment]
@shawn-gmr have you tried this? https://github.com/microsoft/azuredatastudio/issues/23#issuecomment-345361519

**Comment by shawn-gmr** [comment]
I haven't, but will give it a try and let you know

**Comment by shawn-gmr** [comment]
should we see  RestrictedKrbHost/ at all after running setspn -L, if the SPN has been registered for SQL Server? I see 7 other values as well, including HOST/, TERMSRV/ and WSMAN/

**Comment by Code-DJ** [comment]
@shawn-gmr yes I see all of those. Also, I am not sure, its been a while but changing those files on macOS don't make a difference. I think setspn is what fixed it for me.

**Comment by shawn-gmr** [comment]
Our issue may be internal. Either SQL Server or Domain Controllers, since there was a change.
