### ISSUE TITLE
welcome page doesn't respect the enable preview feature flag, new welcome page will be launched

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#16054]
after the preview feature is enabled,  most of the time it is the new welcome page, but occasionally, I get the old welcome page

**Comment by kburtram** [comment]
The welcome page version is chosen on application startup and persisted throughout the application lifetime.  So changes to the preview flag won't take effect until ADS is restarted.  Preview flag setting is false on 1st launch, so you'll see the old page.  If flag is set to true subsequent sessions with use the new page.  Please let us know if you are not observing this behavior.
