### ISSUE TITLE
can't login Azure China account

### ISSUE THREAD

**Issue by newman-xu** [microsoft/azuredatastudio#16063]
![image](https://user-images.githubusercontent.com/13306846/125230744-ffc24800-e30b-11eb-97fd-aaade18d49c4.png)
![image](https://user-images.githubusercontent.com/13306846/125230776-12d51800-e30c-11eb-8caa-c6103c8aad3f.png)

**Comment by Dolphinsimon** [comment]
See #15746

**Comment by JustinMDotNet** [comment]
Linked PR that should fix this issue.
