### ISSUE TITLE
double click in the editor group tab empty area doesn't open a query editor

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#16074]
similarly, double clicking in the editor group when no editor is open should also open a query editor. 

@Charles-Gagnon seems caused by https://github.com/microsoft/azuredatastudio/commit/8f202d91b6b11e2ed548ab1fd1fe0e464db49abc, I reverted this locally and it  works as expected. do you have some time to look into this issue?

**Comment by alanrenmsft** [comment]
more information: I fixed the issue after the vscode merge with this PR: https://github.com/microsoft/azuredatastudio/pull/15874

**Comment by Charles-Gagnon** [comment]
Yeah I'll take a look

**Comment by kburtram** [comment]
Approved in shiproom
