### ISSUE TITLE
Manage Packages Dialog has Unnecessary Horizontal Scrollbar

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#16088]
In notebook, change to Jupyter kernel, choose Manage packages. Notice horizontal scrollbar that impedes functionality:

![image](https://user-images.githubusercontent.com/40371649/125364969-4aea5400-e328-11eb-8a1a-3f4ca2f56b15.png)

**Comment by lucyzhang929** [comment]
Both the vertical and horizontal scrollbars are showing again since the July release.

**Comment by chlafreniere** [comment]
@lucyzhang929 is this something that you can look at for November, or do we need to punt?

**Comment by lucyzhang929** [comment]
I can take a look for November
