### ISSUE TITLE
Right click on editor tab menu has multiple options using a different font size

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#16095]
Version: 1.31.0-rc1
Commit: 862c91d7d323e06f9dd7085bff122d05775de9d5
Date: 2021-07-12T18:34:02.127Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

When right clicking the editor tab, the menu font size doesn't match all the options.
![Screen Shot 2021-07-12 at 5 21 34 PM](https://user-images.githubusercontent.com/34872381/125371588-ec2bd700-e335-11eb-898b-3d5d4962afd8.png)

**Comment by alanrenmsft** [comment]
which one is not the same? they all look the same to me :)

**Comment by alanrenmsft** [comment]
@barbaravaldez

**Comment by barbaravaldez** [comment]
yeah, I think that the options above Pin look smaller. 

Here is how it looks in vscode:
![Screen Shot 2021-07-14 at 11 18 30 AM](https://user-images.githubusercontent.com/34872381/125672482-8b2f5a18-f0e6-4bf5-865a-467eea337311.png)

**Comment by kburtram** [comment]
Closing as upstream since we don't have any code/config to customize the fonts for this menu.
