### ISSUE TITLE
No longer able to change database context after recent upgrade 

### ISSUE THREAD

**Issue by ndwivedi** [microsoft/azuredatastudio#16102]
Issue Type: <b>Bug</b>

In the ADS query window, earlier we were able to change database context when you run a query. Now that option is grayed out and disabled and only way to do is use "use Database";  which works but is inconvinient.
 

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T18:57:01.467Z)
OS version: Darwin x64 19.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.59GB free)|
|Process Argv|-psn_0_278596|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (21)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
query-editor-boost|dre|0.4.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.3.0
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.10.0
whoisactive|Mic|0.1.4
vscode-docker|ms-|0.8.2
azdata-sanddance|msr|3.2.0
simple-data-scripter|sea|0.1.3
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alanrenmsft** [comment]
I just tried this on Mac and I was able to change the database context, could you please attach a screenshot?

**Comment by ndwivedi** [comment]
![image](https://user-images.githubusercontent.com/9135814/126225102-b4a602b4-b136-4ced-8f90-ef7075769584.png)


for postgres
![image](https://user-images.githubusercontent.com/9135814/126225233-c015b3cd-1afc-4888-87d7-9f2e1ef91e37.png)

**Comment by ndwivedi** [comment]
![image](https://user-images.githubusercontent.com/9135814/126225321-76ed5291-056b-4e37-bc32-7e3882a133b0.png)

**Comment by alanrenmsft** [comment]
@ndwivedi after looking into the code, I guess you have enabled the accessibility support in settings, please change it to auto or off, meanwhile I will check why are we doing this.

![image](https://user-images.githubusercontent.com/13777222/129423846-9bbb20a6-1f66-4026-9338-aa041de522f4.png)

**Comment by kburtram** [comment]
Closing based on the previous suggestion and PR #16779.  Please let us know if the problem persists on the current insider builds or the next stable build.  Or if disabling the previously mentioned setting works around the issue.  Thanks!

**Comment by ndwivedi** [comment]
Thank you that fixed that issue but now I get this error.
![image](https://user-images.githubusercontent.com/9135814/134572030-4b337e88-306c-4ea1-8562-67cda2f01ece.png)

**Comment by alanrenmsft** [comment]
@ndwivedi please open a new issue and add detailed repro steps, we will look into that.
