### ISSUE TITLE
Update minimum required azdata version for sql database projects

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#16105]
Need to bump this because of the changes in the data workspace extension to remove the references to workspaces.

**Comment by tomcdona** [comment]
Apologies @kisantia, I'm sure this isn't the correct way to follow up on a bugfix, however this change seems to be blocking the SQL Database Projects extension in the Marketplace now?
The SQL Database Projects Extension is listing at v0.11.0
![image](https://user-images.githubusercontent.com/864859/126218302-22b66ed8-d794-4752-809c-c6a94cb1f35e.png)
However, Azure Data Factory is still at version 1.30.0 and now it seems the Extension is disabled :( 
![image](https://user-images.githubusercontent.com/864859/126218899-cee69ef6-62c6-49c3-8660-e743781128e5.png)

**Comment by kisantia** [comment]
@tomcdona thanks for bringing this up! Should be fixed now
