### ISSUE TITLE
Export Notebook as SQL file has no query editor toolbar

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#16108]
- Azure Data Studio Version: 1.31 rc

Steps to Reproduce:

https://user-images.githubusercontent.com/23462877/125516982-9c3c3880-7259-4ece-81bf-48f2536034a1.mov

**Comment by chlafreniere** [comment]
@Charles-Gagnon do you have any context here? Could this be related to what was previously editor replacement?

**Comment by Charles-Gagnon** [comment]
Almost positively, I'll investigate.

**Comment by chlafreniere** [comment]
Thanks @Charles-Gagnon
