### ISSUE TITLE
Add 'Open w/ Azure Data Studio in Azure Portal

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#1611]
With the upcoming release of SQL DW extension, there may be more SQL DW users trying out SQL Operations Studio. Most DW users use Azure Portal when interacting with DW. @kevinvngo suggested that we investigate how we can open DW instances directly from Azure Portal, similar to what is already done with Visual Studio. 

![vs blade](https://user-images.githubusercontent.com/30873802/41264362-2513bbe0-6da1-11e8-9fc7-a868dc18146d.png)

**Comment by kburtram** [comment]
I believe this support has been added.  Please let us know if you're tracking some other work with this issue.
