### ISSUE TITLE
Projects dialog validation is out of order

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#16113]
Steps to repro:
1. Close any open workspace
2. open create new project dialog
3. put invalid location
4. click "Create"

expected:
Error will show that location is invalid

actual:
popup shows asking if it's ok to restart ADS and the error only shows after the user clicks ok on the notification

![dialogValidation](https://user-images.githubusercontent.com/31145923/125526673-0177a321-4479-44cb-8371-219a22e9e4a3.gif)

**Comment by Charles-Gagnon** [comment]
@kisantia Is this something you all were planning on looking at or should I investigate? (since it's likely due to my changes)

I assume this is a release blocker?

**Comment by kisantia** [comment]
@Charles-Gagnon yup we'll try to take this for July. Should be a simple fix, but we'll let you know if we need help investigating.

**Comment by udeeshagautam** [comment]
Port Req merged.
