### ISSUE TITLE
M1 version for Mac M1 ?

### ISSUE THREAD

**Issue by ngohungphuc** [microsoft/azuredatastudio#16125]
**Describe the solution or feature you'd like**
Do we have an ETA for M1 version for Mac ?

**Comment by alanrenmsft** [comment]
@yualan do we have ETA for M1 Version?

**Comment by therealdandecker** [comment]
I won’t speak to timing (because I do not know) but I know at least an insider version of the MSSQL extension to VS Code for ARM64 exists so I think it’s just a matter of time. If/when that is in mainline / production I would be surprised if Azure Data Studio did not follow closely behind. 

Rosetta 2 / Azure Data Studio work great on M1; SSMS also works well on Windows 10 ARM64 through the x86 translation. I think if anything the value add in ARM64 AZD at this point is for Raspberry Pi and Ubuntu ARM64 as it seems Canonical and the RPi foundation have strong relationships with Microsoft. A nice IDE/query engine for edge devices would be a huge convenience.

**Comment by piotrlangowski** [comment]
Hi, are there any news regarding apple silicon version of AZD? Would be nice to have native app for perceived speed, lowered cpu usage and better power usage when not connected to the charger.

**Comment by ramzzzay** [comment]
Any updates?

**Comment by lucasfolino** [comment]
If support for M1 come does that mean it will also support ARM64 in general, or the opposite?  I can point to this issue #1774

**Comment by abist** [comment]
@lucasfolino Yes, hopefully it will be addressed for all ARM64 architectures, not just Mac M1 Silicon

**Comment by louisoftokyo** [comment]
Are there any updates to share on this? This would be hugely helpful.

**Comment by suraj50488** [comment]
Waiting for an ARM version of data studio. Hoping to hear an update soon!

**Comment by therealdandecker** [comment]
Imagine you’ll be waiting a while considering this has been open a bit. I imagine it’s not actually a matter of compiling ADS for ARM64 but the SQL connectivity.

**Comment by tuxpoldo** [comment]
Please! It's a pity that ADS works slower on my Mac Studio than on my old MBP...

**Comment by jaquesleroux** [comment]
Bump.. any news on this? 
Crazy.. SQL Oracle Developer client on arm64 JRE is 10 times faster loading+interaction than ADS 😔

**Comment by Nova-Logic** [comment]
Bump, we need awesome azure data studion on awesome M1 Mac's

**Comment by mcx808** [comment]
Bump. A year in and VSCode is now arm64, MSSQL Extension is arm64, even OneDrive is arm64. In fact ADS is the only tool I have left that is still not apple silicon native.

**Comment by tuxpoldo** [comment]
August 2022 Release (1.38) since without Apple Silicon support :-(

**Comment by jaquesleroux** [comment]
Garr... Moved to October 2022 Release now 😞😞😞

**Comment by alanrenmsft** [comment]
I've started working on the ARM64 macOS support, I noticed that vscode has 3 flavors, Intel, Apple Silicon and Universal. I understand the Universal one can run on both Intel chip and Apple Silicon, but why is it needed at all? why are folks not using Intel build or Apple Silicon build directly?

**Comment by winzig** [comment]
Universal probably not needed for a dev tool like vscode, but the general idea is that most consumers are not going to know what chip architecture they're running, so best bet for a mainstream app is to offer a universal build that can run on any Mac.

**Comment by cuong0993** [comment]
I believe 3 flavours can serve all users.
The universal one is for people who do not care what CPU architecture is. Just download it and use it on every MAC.
However, its size is larger than Intel/M1 ones then will increase download bandwidth.
And maintaining all 3 flavours need more effort from developers.
Then please consider trade-offs.

**Comment by alanrenmsft** [comment]
Thanks @winzig @cuong0993

**Comment by alanrenmsft** [comment]
Support for Apple Silicon is now available for Azure Data Studio Insiders build, please give it a try and let us know if you run into any issues, you can get it from: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
![image](https://user-images.githubusercontent.com/13777222/195130678-784da537-593f-4270-9ef7-fd58ff02db75.png)

If everything goes well, we should be able to have our first arm64/universal ADS stable build by November.

NOTES: The main app is now running natively on Apple Silicon but there are still some remaining works for backend services, tracked by: https://github.com/microsoft/azuredatastudio/issues/20775

**Comment by tuxpoldo** [comment]
Thank you VERY MUCH!

**Comment by kburtram** [comment]
@alanrenmsft are you keeping this open or should it be closed now?

**Comment by alanrenmsft** [comment]
@kburtram I'll close this after the Nov release.

**Comment by alanrenmsft** [comment]
The ARM64 macOS native builds will be available for the upcoming stable release.

**Comment by alanrenmsft** [comment]
Release 1.40 is now available:

https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release
![image](https://user-images.githubusercontent.com/13777222/202282010-4c5efd95-becf-491d-a8f3-d7119f3d6dc8.png)
