### ISSUE TITLE
Consider update package to lastest version ?

### ISSUE THREAD

**Issue by ngohungphuc** [microsoft/azuredatastudio#16126]
**Is your feature request related to a problem? Please describe.**
Seems like there is not much change in package.json since we are still using angular version 4.

**Describe the solution or feature you'd like**
Would the team consider to migrate all the package to the lastest version ?
If so can I help ?

**Comment by Charles-Gagnon** [comment]
This is something we've talked about doing at some point but it hasn't been a priority. Feel free to submit a PR though if you want to try giving it a shot! 

I'm going to close this as it's not something we're actively tracking at this time.
