### ISSUE TITLE
Schema compare Select Source target dialog's OK button not enabled

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#16131]
- Azure Data Studio Version: July RC
- OS Version: windows
Steps to Reproduce:

1. Open Schema compare 
2. Open diaog to Select Source and target
3. If source and target are database the OK utton on Select sorce Tareget dilaog keep being disabled 
![image](https://user-images.githubusercontent.com/46980425/125682581-47ff870f-7e7f-4412-98c7-ddb42de704e8.png)

this was not there in last release and no chnages for this release have happened. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
Verified that this was still working in the 1.30 release, so this is a regression.

Tried setting the ok button to true on line 722 in populateDatabaseDropdown. The ok button started as enabled when the dialog opened, but then when I changed the target to db, the ok button got disabled even though it should've been getting set to true
