### ISSUE TITLE
Microsoft.Data.SqlClient bug prevents connections on TLS1.3 enabled OS

### ISSUE THREAD

**Issue by Rans4ckeR** [microsoft/azuredatastudio#16140]
- Azure Data Studio Version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
- OS Version: Windows 10 Pro 21H1 19043.1110

Steps to Reproduce:

1. Enable TLS1.3
2. Reboot
3. Connect to (local) server, results in:
`Microsoft.Data.SqlClient.SqlException: A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - No process is on the other end of the pipe.)`

See: [https://github.com/dotnet/SqlClient/issues/1151](https://github.com/dotnet/SqlClient/issues/1151)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kburtram** [comment]
@Rans4ckeR thanks for reporting this issue.  We'll update the driver once a fix is available.

**Comment by cheenamalhotra** [comment]
Fix for this issue had been made available in Microsoft.Data.SqlClient a while ago, closing this as resolved.
