### ISSUE TITLE
connect button is focusable when disabled

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#16142]
![image](https://user-images.githubusercontent.com/13777222/125691557-360ba8b6-63f5-4250-a79d-05800410de49.png)

this issue impacts all the UI with buttons in ADS, caused by recent vscode merge.

**Comment by alanrenmsft** [comment]
@smartguest turns out this is a not a connection dialog specific issue, feel free to assign it to me.

**Comment by kburtram** [comment]
Fix merged to releasse/1.31
