### ISSUE TITLE
multiple notifications about new AZDATA available from different extensions

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#16152]
noticed this on my local dev instance of ADS
![image](https://user-images.githubusercontent.com/13777222/125704851-99993d04-62a8-4f5c-88d7-e3fcde7ce8b8.png)

@Charles-Gagnon can we do something to make sure there is only one prompt?

**Comment by Charles-Gagnon** [comment]
This is temporary as @candiceye is working on moving everything over before we delete the azdata extension. I'll see if we can get it cleaned up here soon, but for the time being just tell it to `Don't ask again`
