### ISSUE TITLE
-- #regions

### ISSUE THREAD

**Issue by mattmc3** [microsoft/azuredatastudio#1618]
It would be great to have support for specifying regions for code folding in sql files in SqlOps, similar to how C# supports this. T-SQL is unique in that it is not as easily modularized as other languages, which makes code folding significantly more helpful in this context.

VS Code ticket [here](https://github.com/Microsoft/vscode/issues/12146) for reference.

```sql
-- #region

select folding
into #please
from feature_request

/* more code... */

-- #endregion 

```

**Comment by sheitmann** [comment]
adding the following to
`C:\Program Files\SQL Operations Studio\resources\app\extensions\sql\language-configuration.json`
will add it
```javascript
"folding": {
	"markers": {
		"start": "^\\s*--\\s*#region\\s*.*$",
		"end": "^\\s*--\\s*#endregion\\s*.*$"
	}
}
```

**Comment by anthonydresser** [comment]
Seems like this is something we could easily support out of the box using the configuration @sheitmann provided.

**Comment by mattmc3** [comment]
Awesome. I was unable to edit these files on a mac without azure-data-studio being detected as corrupted (I assume because the app's verified sha changed), so having this be part of the default install would be fantastic.

**Comment by KennyEng12** [comment]
Hi, may I know is this being implemented?

Thanks,
Kenny.
