### ISSUE TITLE
Notebooks: Insert Link fails when using local file path wrapped in quotes

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#16189]
When using a quoted file path in the Text Cell insert link dialog, clicking the submit button does nothing. The dialog closes and no link text appears in the text cell. However, when you remove just the quotes around the file path the new link text gets inserted correctly.

**Comment by chlafreniere** [comment]
Not a regression so pushing to next release

**Comment by corivera** [comment]
Note that this quoted path issue only affects WYSIWYG. Additionally, when using a full quoted path in the markdown link, ADS tries to append the quoted path to the current working directory, as though the quoted path was a relative path.
