### ISSUE TITLE
Creating new SQL project from Database fails to load new project in workspace in Project view

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#16227]
Repro:
0. Install SQL Database Projects extension
1. Connect to database, right-click on database and select "Create Project from Database"
2. Choose location inside the currently-open workspace/folder
3. Click "Okay", project gets created correctly

Expected:
Database Projects view automatically opens the newly-created project because it's within the current workspace

Reality:
Get error saying the project is already open (it isn't).  Project is detected and loads correctly upon reloading the workspace.
<img width="479" alt="Screen Shot 2021-07-16 at 2 00 15 PM" src="https://user-images.githubusercontent.com/1609827/125990025-0872bf27-d840-4f5e-9797-782afd6d07b9.png">

Work-around:
Reload the workspace or restart ADS.  The project will now be detected as part of the workspace, and will open automatically.

**Comment by Benjin** [comment]
@Charles-Gagnon as an FYI.  Likely related to the workspace changes for VS Code.  Not major enough to take to release shiproom, so we'll fix this for next month.

**Comment by Charles-Gagnon** [comment]
This is likely in the extension anyways so we can just fix it and then push a new release as needed. Let me know if you want me to help out with the fix at all.

**Comment by udeeshagautam** [comment]
@Benjin, @Charles-Gagnon - just checking if we will be able to take it for August?

**Comment by Charles-Gagnon** [comment]
I will definitely take a look at it if @Benjin isn't able to

**Comment by Benjin** [comment]
Already in the process of looking at it; it'll be in for August
