### ISSUE TITLE
Core SQL Strings not being localized with current langpacks in ADS.

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#16322]
Some outstanding strings that haven't been localized yet in ADS: 
#6325
#6329 
#6338

This is caused by these strings not having the appropriate translated resource strings in the langpack source files, (They weren't added previously due to being part of the vs folder originally)

My PR #16195 fixes these issues.

**Comment by kburtram** [comment]
Approved in shiproom
