### ISSUE TITLE
SQL Database Projects: Unavailable in ADS

### ISSUE THREAD

**Issue by boylec** [microsoft/azuredatastudio#16337]
Mac:

The extension "Projects" viewlet is not visible in the sidebar of Azure Data Studio all of the sudden.

* Reinstalled ADS.
* Uninstalled and reinstalled SQL Database Projects extension.
* Ran "> Projects: Open existing project" from  the command pallet and opened the SQL proj file. An error which claims the project is already open appeared. So essentially I'm stuck and cannot open or access my SQL proj files at this point.
* The extension is grayed out in the @installed view of the extension explorer with no explanation and is not labeled either enabled or disabled within the view.

**Comment by boylec** [comment]
One last symptom:
The extension is grayed out in the @installed view of the extension explorer with no explanation and is not labeled either enabled or disabled within the view.

**Comment by Charles-Gagnon** [comment]
Is the version of the extension listed as 0.11.0? There was a publishing mistake earlier where an updated version of the extension was released early.

To fix this : 

1. Run the `Extensions: Open Extensions Folder` command from the command palette
2. Delete the `microsoft.sql-database-projects-0.11.0` folder
3. Restart ADS
4. Go to the gallery and download the extension again (it should be `0.10.0`)

**Comment by boylec** [comment]
It is indeed, thank you for the quick response. I'll try this immediately and report back.

**Comment by boylec** [comment]
Steps I followed steps 1 through 3, however step 4 seems to not be possible at this moment.

The only version available in the extension explorer shows as 0.11.0

![image](https://user-images.githubusercontent.com/8148174/126253621-62176c18-0f43-4050-9639-b911aceba63c.png)

**Comment by Charles-Gagnon** [comment]
What version of ADS is this with (Insiders or Stable)?

**Comment by boylec** [comment]
I believe this is Stable
![image](https://user-images.githubusercontent.com/8148174/126255936-537fd394-1aef-49b3-9d50-5451b9db9d47.png)

**Comment by Charles-Gagnon** [comment]
Apologies, it looks like there was a lingering issue there. If you restart ADS you should see the 0.10.0 version as expected.

**Comment by boylec** [comment]
Okay, I was able to get 0.10.0 installed and restarted ADS.

Unfortunately my symptoms persist.

**Comment by Charles-Gagnon** [comment]
And you still don't see the icon on the sidebar panel? If you right click on the sidebar do you see `Projects` listed there? If you do make sure it's checked.

![image](https://user-images.githubusercontent.com/28519865/126257904-e4112779-125d-473f-be63-3ac007828363.png)

**Comment by boylec** [comment]
Thats correct, still no icon - nor a Projects selection in the dropdown.

![image](https://user-images.githubusercontent.com/8148174/126258092-caf90069-f3a4-46aa-8417-1bfcc0f47c3c.png)

**Comment by boylec** [comment]
![image](https://user-images.githubusercontent.com/8148174/126258411-7e8c4635-3245-4d60-9dcf-d22323757335.png)

**Comment by boylec** [comment]
[console.log](https://github.com/microsoft/azuredatastudio/files/6847477/console.log)
[dev logs.zip](https://github.com/microsoft/azuredatastudio/files/6847479/dev.logs.zip)

**Comment by Charles-Gagnon** [comment]
@kisantia @Benjin Any ideas? I'm not seeing anything indicating what the issue is.

@boylec Something else to try

1. Run the `Developer: Open Logs Folder` command
2. From there go up 3 directories to the folder  containing the `azuredatastudio` directory
3. Close ADS
4. Rename the `azuredatastudio` directory to something else (such as `azuredatastudio_bak`)
5. Start ADS

This will reset your user settings so we can see if it's something there that got messed up. You can then just delete the new `azuredatastudio` folder and rename the bak one to restore your settings.

**Comment by boylec** [comment]
Yep, that seems to have resolved the issue.

Even after I restored the original ```azuredatastudio``` things appear to remain restored.

Thanks for the quick response once again - not sure what the actual root cause was.
