### ISSUE TITLE
Import Wizard is not opening. 

### ISSUE THREAD

**Issue by noelogbuagu** [microsoft/azuredatastudio#16367]
At the bottom of the screen, it just shows activating extension but the SQL Server Import extension never opens. I don't know whether this is a singular problem or not.

**Comment by jakodev** [comment]
me too

**Comment by kburtram** [comment]
@aasimkhan30 do you have any idea what could be happening here?

**Comment by kburtram** [comment]
FWIW, I tested the latest ADS release with the latest Import extension and the wizard loaded fine for me against on-prem SQL Server instance.  One thing to note is the extension will download binaries on first launch that needs to complete prior to showing the UI.  You should see the below in the output log while this is happening.

```
Downloading https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.7/win-x64.zip
(37,917 KB)....................Done downloading Flat File Import Service
Installing Flat File Import Service to https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.7/win-x64.zip
Installed Flat File Import Service
```

**Comment by Blogem** [comment]
I had the same problem. After an uninstall and reinstall of the extension (and also a restart of data studio for good measure), the log messages @kburtram mentioned showed up. It took maybe 30 seconds after hitting CTRL+I before the log messages  appeared.

**Comment by kburtram** [comment]
Closing based on previous comments.  Please let us know if the wizard opening delay was not related to service download on 1st run.  Thanks!
