### ISSUE TITLE
Smoke test: Python installation test timing out

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#16364]
![Screen Shot 2021-07-20 at 2 11 38 PM](https://user-images.githubusercontent.com/23462877/126396740-c3fa99e4-77eb-438b-b7b8-da9b776273e6.png)

**Comment by chlafreniere** [comment]
Closing for now as this hasn't reappeared in the past couple of weeks after smoke test fixes have gone in
