### ISSUE TITLE
SQL Database Projects Extension - stuck in disabled

### ISSUE THREAD

**Issue by shaunryan** [microsoft/azuredatastudio#16373]
SQL Database Proejects extension is stuck in a disabled state. All the dependencies have been installed.

- Azure Data Studio Version: 1.25.3 
- OS Version: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Installed Extensions Admin Pak for SQL Server
2. Installed .Net framework 3.1
3. Installed SQL Database Projects Extension

Does this issue occur when all extensions are disabled?: N/A - they have to be distabled or it won't work.

**Comment by Charles-Gagnon** [comment]
Please update to the latest version of ADS and let us know if the issue persists

**Comment by Charles-Gagnon** [comment]
And what version of the extension do you have? If it's 0.11.0 then please see this thread for instructions on rolling back (there was a bad update pushed early) 

https://github.com/microsoft/azuredatastudio/issues/16337#issuecomment-883819384

**Comment by shaunryan** [comment]
@Charles-Gagnon on it. I realised it was quite old soon after I posted. Trying to get it up upgraded and will close down if resolved.

**Comment by kisantia** [comment]
@shaunryan did you get a chance to upgrade and see if projects is still disabled?

**Comment by kisantia** [comment]
closing since we haven't heard back. Feel free to reopen if you're still seeing this problem with the latest sql projects extension
