### ISSUE TITLE
Support connection string in the Connection dialog

### ISSUE THREAD

**Issue by languy** [microsoft/azuredatastudio#16376]
**Is your feature request related to a problem? Please describe.**
The current connection dialog is mostly meant for sql. It is not possible to add or remove fields needed for connecting to a service that only requires a connection string.

**Describe the solution or feature you'd like**
Ability to customize removing all fields except connection name or server name and to add a field for connection string.
A "Remember connection string" checkbox should also be displayed so ADS can cache the connection string.
We would want to customize the "Advanced" fields as well (to confirm that this is already possible in the current implementation).

**Describe alternatives you've considered**
Currently repurposing the password field for the connection string, since it works the same way.
But not able to remove all other fields.
I believe serverName is used for the key to cache the password right now.

**Additional context**
This is a P0 for us.

**Comment by alanrenmsft** [comment]
@cheenamalhotra this was implemented a while back: https://github.com/microsoft/azuredatastudio/commit/b8858f011d2cbeb92d60dfa9a33d1346b313cba3, I forgot to close this one.
