### ISSUE TITLE
Support customizing left click or left double-click on "CONNECTIONS" tree nodes

### ISSUE THREAD

**Issue by languy** [microsoft/azuredatastudio#16377]
**Is your feature request related to a problem? Please describe.**
The "CONNECTIONS" tree contains the current connections as top-level nodes.
One can expand these nodes and some of the nodes can be left clicked or double-clicked to open dashboards.
My understanding is that the server and database nodes are hardwired to some dashboards.
We can create our own dashboards from our extension, but we cannot invoke them when clicking on the nodes.

**Describe the solution or feature you'd like**
From our extension code we want to customize which dashboard to show when left-clicking or double-clicking on a particular node.

**Describe alternatives you've considered**
The current implementation uses right-click to invoke the dashboard, but it doesn't solve the left-click-opens-unwanted-dashboard issue.

**Additional context**
This is a P1.

**Comment by alanrenmsft** [comment]
@languy you can customize the double click experience by adding the `isDefault:true` property to the command in the OE item context menu contribution. https://github.com/microsoft/azuredatastudio/pull/22455/files#diff-fdd531ac83f636b3015220925db3e0512f8304be6e1b3e6ad969e1670126d663R497

let me know if you have any questions.

**Comment by languy** [comment]
For the record, after discussion with Alan, no need to customize which dashboard opens when double-clicking on top-level connection node.
