### ISSUE TITLE
Ability to customize icons for the nodes in the CONNECTIONS tree

### ISSUE THREAD

**Issue by languy** [microsoft/azuredatastudio#16374]
**Is your feature request related to a problem? Please describe.**
We would like to populate the CONNECTIONS tree with non-sql-related nodes.

**Describe the solution or feature you'd like**
From our extension, customize the icons for a given node type (ie provide a link to the svg file in the program).

**Describe alternatives you've considered**
We currently have to choose a node type that provides an icon that is similar to what we like.

**Additional context**
This is a P0 for us.

**Comment by Charles-Gagnon** [comment]
I'm not sure what your exact use case is - but it sounds like you may want to look into providing your own tree. That would allow you to fully customize it - including things such as context menus and icons.

https://code.visualstudio.com/api/extension-guides/tree-view
https://github.com/microsoft/vscode-extension-samples/blob/main/tree-view-sample/README.md

An example from our own code : https://github.com/microsoft/azuredatastudio/blob/main/extensions/arc/src/ui/tree/azureArcTreeDataProvider.ts
