### ISSUE TITLE
SQL Server Agent not showing up after installation

### ISSUE THREAD

**Issue by gvsureshreddy** [microsoft/azuredatastudio#16387]
Issue Type: <b>Bug</b>

Hello,

I installed SQL Server Agent extension in ADO. However, I am not seeing it when I click on manage for a Azure SQL databse. I followed below steps to install SQL Server Agent extension.

https://database.guide/install-the-sql-server-agent-extension-on-azure-data-studio/

Thanks,
Suresh

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:43:31.605Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6226 CPU @ 2.70GHz (48 x 2694)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|127.66GB (117.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
azdata-sanddance|msr|3.3.0

</details>

**Comment by kburtram** [comment]
@gvsureshreddy Azure SQL DB doesn't support SQL Agent so Azure Data Studio doesn't display the UI in the Manage page.  SQL Agent is only supported in Azure SQL Managed Instance, Azure SQL VM, or on-premise SQL Server.

**Comment by gvsureshreddy** [comment]
Thanks @kburtram. Is there any other way to schedule query in ADS with Azure SQL DB?

**Comment by dzsquared** [comment]
@gvsureshreddy there are a number of ways to schedule a query in Azure SQL DB, but they would not be in Azure Data Studio. These are just a few examples:
- Azure Logic Apps: https://docs.microsoft.com/azure/connectors/connectors-create-api-sqlazure
- Azure Function: https://docs.microsoft.com/azure/azure-functions/functions-scenario-database-table-cleanup
- Elastic Jobs: https://docs.microsoft.com/azure/azure-sql/database/elastic-jobs-overview

**Comment by jppo** [comment]
I have the same kind of problem.
I installed AzureDataStudio on Linux (Debian Buster 10.10) and the Sql Agent does not show in "Manage". 
The server is also Linux and all connections are OK with Sqlcmd. With DataStudio  I see databases,tables, requests are OK.
The only problem is that, even if SQL Server Agent is enabled I can't see it with "manage".
I am working with a "standard user".
I make a test with the "root"  user (strongly discouraged) and ... I see SqlAgent on the "manage" screen and it is working.
Is there a solution to that problem ?

Regards
JP P
