### ISSUE TITLE
Getting slow day by day

### ISSUE THREAD

**Issue by VaibhavD-intelegain** [microsoft/azuredatastudio#16393]
Issue Type: <b>Performance Issue</b>

I am experiencing performance issue day by day and loosing interest to use this..
1. Delay in connections.. even for localhost sometime
2. Longer query execution time in startup, or after some idle time
3. For longer running queries, cancel button is not working... It remains in execution mode. I have to close and restart azure data studio

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:43:31.605Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (2.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	    84	 16512	azuredatastudio main
    1	    77	  1628	   window (Issue Reporter)
    0	    76	  3172	   shared-process
    0	    61	  2056	     ptyHost
    0	   164	  9512	   window (● SQLQuery_1 - localhost.TenantV1 (Integrated) - MigrationScripts - Azure Data Studio)
    0	   102	  7472	     extensionHost
    0	   101	  5216	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.110\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\vaibhav.d\AppData\Roaming\azuredatastudio\logs\20210722T115014\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	    10	 11800	         console-window-host (Windows internal process)
    0	    32	  6660	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.110\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\vaibhav.d\AppData\Roaming\azuredatastudio\logs\20210722T115014\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	    10	  8116	         console-window-host (Windows internal process)
    0	    35	 10372	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.110\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\vaibhav.d\AppData\Roaming\azuredatastudio\logs\20210722T115014\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	    10	 15620	         console-window-host (Windows internal process)
    0	    12	 14996	     watcherService 
    0	    11	 15536	       console-window-host (Windows internal process)
    0	    24	 14832	   crashpad-handler
    0	    38	 17132	   utility
    0	   153	 17196	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● SQLQuery_1 - localhost.TenantV1 (Integrated) - MigrationScripts - Azure Data Studio)
|    Folder (MigrationScripts): 30 files
|      File types: sql(30)
|      Conf files:;
```

</details>
Extensions: none

**Comment by raeokay** [comment]
Looks like this issue: https://github.com/microsoft/azuredatastudio/issues/14853

**Comment by kburtram** [comment]
@VaibhavD-intelegain thanks for reporting this issue.  Sorry you're experiencing performance issues.  We're continuing to try to improve performance incrementally across core product scenarios.  Our next release will include some notebook loading perf improvements.

I'll close this issue as a duplicate for issue https://github.com/microsoft/azuredatastudio/issues/3231, which has been a long standing issue we've had with cancel sometimes not working.  I'll move that bug back into a current milestone for further investigation.  We only track 1 bug per issue so please create new issues for individual bugs if there is anything else you'd like us to investigate.
