### ISSUE TITLE
Throw keyword states incorrect syntax

### ISSUE THREAD

**Issue by DanielSSilva** [microsoft/azuredatastudio#1643]
- SQL Operations Studio Version: 0.28.6 

Steps to Reproduce: Check the image below. Basically simply having a `THROW` states incorrect syntax and all the code following that does the same, although all the code runs as expected.
![image](https://user-images.githubusercontent.com/6862119/41526408-0fa2f74a-72dc-11e8-9f56-8dbd1f9addc1.png)
The first throw states `Incorrect syntax near 'THROW'.  Expecting CONVERSATION, DIALOG, DISTRIBUTED, or TRANSACTION.`

and the SELECT `Incorrect syntax near 'SELECT'.  Expecting CATCH, CONVERSATION, or TRY.`

**Comment by kburtram** [comment]
This looks like an upstream bug in the T-SQL Parser component.  I'm seeing the same bug in SSMS.  I'll open a bug against that component to investigate further.

![screen](https://user-images.githubusercontent.com/599935/43617321-39ecf416-9676-11e8-86e1-dbbc156ce362.png)

**Comment by patrickcarlohickman** [comment]
The documentation for the THROW statement states the previous statement must be terminated by a semicolon:

> The statement before the THROW statement must be followed by the semicolon (;) statement terminator.
>
> - https://docs.microsoft.com/en-us/sql/t-sql/language-elements/throw-transact-sql?view=sql-server-ver15

Even though it doesn't appear to be needed for correct code execution, if you place a semicolon after the BEGIN statement, the syntax checker will be happy.

```
IF (INSULL(@abc,1) = 1)
BEGIN;
    THROW 50001, 'The abc is disabled', 1;
END
```

**Comment by kburtram** [comment]
@patrickcarlohickman thanks for the clarification on this issue.  It looks like the product behavior is matching the documented syntax (even though I agree it appears unintuitive).
