### ISSUE TITLE
Copy ignores localised decimal separator

### ISSUE THREAD

**Issue by jakoss** [microsoft/azuredatastudio#16438]
- Azure Data Studio Version: 1.31.0
- OS Version: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Run any query that have decimal as result
2. Copy results (Ctrl + c)
3. Paste in notepad

The copied content should have localized decimal separator, but right now it always copies the dot (it should be comma here in Poland). It worked well in 1.30.0, so i guess this is a regression. And i could swear that this issue happened before, but i couldn't find the original issue

Does this issue occur when all extensions are disabled?: Yes

**Comment by dollyjuice** [comment]
Yes, something has changed! I cant copy and paste my results in Excel anymore because the pasted results don't change to destination formatting (Pt-br).
In ADS the the number was 24708502.1300 and when I copy to Excel it used to be 24.708.502,13. Now it appears as 
247.085.021.300

**Comment by smartguest** [comment]
It appears to be a change made to STS that is causing this issue, will need to see if this change was done for a reason or not.
