### ISSUE TITLE
Unable to proceed with extension authoring/development

### ISSUE THREAD

**Issue by faraoman** [microsoft/azuredatastudio#16455]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Install Azure Data Studio 1.31.0 (Aur for Manjaro, Windows by Microsoft Site)
2. Using `yo azuredatastudio` (if needed see [https://github.com/llali/generator-azuredatastudio](https://github.com/llali/generator-azuredatastudio)) create a new extension called ads-test-ext (using typescript
3. Open ads-test-ext folder with Visual Studio Code (v 1.58.2)
4. Install in Visual Studio Code the extension with id: `ms-mssql.sqlops-debug`
5. Run the project with F5
6. Now Azure Data Studio will open with DevTool Window and there are no way to proceed with extension development (see [https://imgur.com/a/chxx9RM](https://imgur.com/a/chxx9RM))
7. *All this step are working with Azure Data Studio 1.30.0*

Azure Data Studio version: azuredatastudio 1.31.0 (a430fd2592763ef4c4a406821967e4b7b2b3d876, 2021-07-20T19:40:24.296Z)
OS version: Linux x64 5.12.16-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor (8 x 4018)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.61GB (1.61GB free)|
|Process Argv|--no-sandbox --unity-launch --no-sandbox|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|plasma|
|XDG_CURRENT_DESKTOP|KDE|
|XDG_SESSION_DESKTOP|KDE|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by aasimkhan30** [comment]
@faraoman, can you open an issue in that repository?

**Comment by kburtram** [comment]
Closing since the issue has been moved to different repro.  Thanks for your interest in extension development!
