### ISSUE TITLE
Unable to see Azure Databases in Servers Group

### ISSUE THREAD

**Issue by tlentine** [microsoft/azuredatastudio#16472]
Issue Type: <b>Bug</b>

Version: 1.32.0-insider
Commit: 07ad50670efc204f399ebbe7ca10f2e29169cda8
Date: 2021-07-28T05:39:45.938Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

Using Azure Data Studio Insiders, I am unable to expand any of my Azure SQL Databases (vCore-based). I am able to connect and open a new query window and issue statements against the databases located on the Azure SQL Database, but I can't see any of the databases in the Server Explorer window. This happens across multiple Azure SQL Database(s) hosted in different Azure Subscriptions.

I believe this to be an issue with the latest insiders build as yesterday this all worked as expected.

Azure Data Studio version: azuredatastudio-insiders 1.32.0-insider (07ad50670efc204f399ebbe7ca10f2e29169cda8, 2021-07-28T05:39:45.938Z)
OS version: Darwin x64 20.5.0

<details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.47.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.11.0
azdata-sanddance|msr|3.3.0

(1 theme extensions excluded)

</details>

**Comment by tlentine** [comment]
Here you go. For what it is worth, I installed the non-insiders build (version 1.31.0) and do not experience the issue with that version.

[Console.log](https://github.com/microsoft/azuredatastudio/files/6902552/Console.log)
[ApplicationLogs.zip](https://github.com/microsoft/azuredatastudio/files/6902553/ApplicationLogs.zip)

**Comment by abist** [comment]
@tlentine Thanks for posting the logs. To be clear, you can see the server in the explorer but not the databases inside it?

**Comment by tlentine** [comment]
That is correct. I can connect to the server, I can open a query window and see the list of databases in the drop down list, but in the explorer I am not able to expand the tree and see any of the databases on the servers I connect to.

**Comment by abist** [comment]
@tlentine Thanks for the reply! What kind of server is it? It will help me look into the problem in more detail.

**Comment by tlentine** [comment]
It happens across different Azure SQL Database servers (vCore based). Connecting to SQL Server on my local network works as expected. It is only failing with Azure SQL Databases.

**Comment by lewis-sanchez** [comment]
@tlentine, this issue appears to be fixed in the latest insider version of Azure Data Studio `1.41.0-insider`. Please try the latest insider version and see whether this is fixed for you: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch
