### ISSUE TITLE
Error ERR_SSL_PROTOCOL_ERROR when I try to login or link an account

### ISSUE THREAD

**Issue by DFMERA** [microsoft/azuredatastudio#16489]
- Azure Data Studio Version: 1.31.1
- OS Version: Windows 10

Steps to Reproduce:
When I try to login into Azure Data Studio or when I try to link a new account it opens a browser (to load de Microsoft login page as it is supposed to do) but the browser tries to open a localhost site like https://localhost:50055/signin?nonce=WXXlp6hpPC8NjuTNfFMhig== and the site never loads because of an ERR_SSL_PROTOCOL_ERROR error
Please check the images attached 

![Error Azure data studio 1](https://user-images.githubusercontent.com/23387464/127578673-f309cf4d-2bdd-4bd7-9e29-2204913c8178.PNG)
![Error Azure data studio 2](https://user-images.githubusercontent.com/23387464/127578674-3c7d35b5-d3df-48b4-8d7e-8ff4a2e767aa.PNG)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
This is due to your browser automatically redirecting to https - see this thread for details and workarounds :

#14493
