### ISSUE TITLE
Query Editor database selector drop-down doesn't work for DB Pool connections

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#16501]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Connect to SQL DW instance with a DB Pool
2. Open Query editor using connection
3. Change DB using DB Selector drop-down

Expected: Database changes

Actual: An error occurs and DB doesn't change

**Comment by chlafreniere** [comment]
Does this happen for notebooks as well, @kburtram?
