### ISSUE TITLE
An unexpected error occurred while connecting.

### ISSUE THREAD

**Issue by islamtg** [microsoft/azuredatastudio#16511]
Issue Type: <b>Bug</b>

trying to connect to a sqldb but unable to connect with following error An unexpected error occurred while connecting. Please [file an issue](command:workbench.action.openIssueReporter) with the title 'Unexpected Error Occurred while Connecting' and include the log file [C:\Users\iselghaz\AppData\Roaming\azuredatastudio\logs\20210731T132847\renderer1.log](command:workbench.action.openLogsFolder)

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (18.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
powershell|ms-|2020.4.0
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.11.0
sql-dw|Mic|0.0.1

</details>

**Comment by Charles-Gagnon** [comment]
Closing this now as we have many similar issues - please let us know if you have more information to share!
