### ISSUE TITLE
Query experience does not indicate which cluster you are connected to

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#16513]
Issue Type: <b>Bug</b>

Repro:
- Connect to any database and execute a query.

![image](https://user-images.githubusercontent.com/7318752/127753282-88c85a81-aa54-4fc6-97b0-1c9322d194ff.png)

The query experience lists the database name. If you are dealing with multiple clusters/servers having the same database names it is not possible to identify which cluster this particular window is querying by just looking at the query window.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (9.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/128919894-fe487e67-3082-482b-9ea8-21f7b375807c.png)
as shown above, there are 3 places you can see the context: document tab header, ADS app title and the status bar.

Does it help?

**Comment by cheenamalhotra** [comment]
Closing as per above comment.
