### ISSUE TITLE
Arc controller deployment shows error if no arcdata extension installed

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#16518]
1. Don't have arcdata extension installed
2. Start new arc controller deployment

This error is shown after a bit 

```
Unexpected exit code from command: ERROR: The command requires the extension arcdata. Unable to prompt for extension install confirmation as no tty available. Run 'az config set extension.use_dynamic_install=yes_without_prompt' to allow installing extensions without prompt. (2)
```

If the extension isn't installed we should detect that on the first page and not run any of the commands on following pages (which is likely where this error is coming from, currently the pages will be created in the background once the wizard is opened even if the pre-reqs aren't met)

**Comment by candiceye** [comment]
@Charles-Gagnon  Just to clarify, by "we should detect that on the first page" you meant the first page of the arc dc deployment wizard (Step 1), not the home page of ADS. And so if we're on Step 1 of the wizard and no arcdata is detected, we should not allow the user to continue to Step 2?

**Comment by Charles-Gagnon** [comment]
Correct. I filed https://github.com/microsoft/azuredatastudio/issues/16519 specifically for that. This one is more of a general issue where the fact that azdata isn't installed is causing an error to be thrown from a later page - which is confusing to the user.

(this is a general problem with the wizard though - but currently most wizards don't have logic like this one does to run commands in the background so you don't see it show up in the others typically)
