### ISSUE TITLE
Login Error with Azure AD MFA

### ISSUE THREAD

**Issue by shahid-aman-maersk** [microsoft/azuredatastudio#16539]
Issue Type: <b>Bug</b>

While trying to add a connection to azure SQL with loging using Azure AD MFA - , Data Studio uses cached login, even after a successful authentication on the browser.

Response error! - {"error":"invalid_grant","error_description":"AADSTS50173: The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed or reset their password. The grant was issued on '2021-06-28T11:55:38.4136589Z' and the TokensValidFrom date (before which tokens are not valid) for this user is '2021-07-

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (8.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0

</details>

**Comment by ALZDBA** [comment]
In my case, we recently enabled AAD MFA, it is requesting another password after AAD MFA validation ( call to number ).
No matter the password I provide, it fails !

_> git log --oneline --cherry master...master@{upstream} --
> git pull --tags MyProject master
fatal: Failed to find location service
fatal: Authentication failed for 'https://dev.azure.com/aperam/MyProject /_git/MyProject /'_

**Comment by ALZDBA** [comment]
Did this ever work with AAD MFA ??
