### ISSUE TITLE
Copying large data sets does not work on Mac

### ISSUE THREAD

**Issue by bowmansteven** [microsoft/azuredatastudio#16537]
When trying to copy results from the Results in Query Editor... clicking Copy or Copy with Headers simply doesn't work.

I have seen this bug previously reported, but it's been marked resolved.

Version: 1.31.1
Commit: 65fb22cc7c36db9c53af1ed2fdbdf48f66c682be
Date: 2021-07-28T21:13:05.032Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/10123.  We'll investigate the various related copy from results grid issues when investigating that bug.  Thanks!
