### ISSUE TITLE
An unexpected error occurred while connecting. 

### ISSUE THREAD

**Issue by DaveBabler** [microsoft/azuredatastudio#16538]
Issue Type: <b>Bug</b>

I expected to connect.
The actual results was that this Issue Reporter Screen popped up, and as such, I am submitting this bug-report as requested.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (16.01GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
rainbow-brackets|2gu|0.0.6
pastetheplan|dre|0.2.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
powershell|ms-|2020.4.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.11.0
whoisactive|Mic|0.1.4
extra-sql-script-as|pac|0.3.0
sqlops-spexecutesql-to-sql|pej|1.0.1
schema-visualization|R0t|0.7.1
sql-prompt|Red|0.2.7
sql-search|Red|0.4.0
plan-explorer|Sen|0.9.8
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by abist** [comment]
@DaveBabler Thanks for opening the issue. This is a general message we show when an error occurs. Do you know what issue you encountered when you got this message? You can perhaps upload the log file as indicated in your title.

**Comment by Charles-Gagnon** [comment]
I'm closing this for now as we already have numerous similar issues - please let us know if you have more information to share!
