### ISSUE TITLE
AAD Server Connection Tree does not expand

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#16549]
- Azure Data Studio Version: 1.32.0-insider
- OS Version: Windows 10

Steps to Reproduce:

1. Open a new ADS window

2. Select an AAD connection to connect and expand the connection tree

3. The tree does not expand

![Screen Shot 2021-08-03 at 1 17 09 PM](https://user-images.githubusercontent.com/18150417/128081314-7f7865a7-0c48-4efe-bf5b-452c8a52d811.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
@aasimkhan30 please verify your fixed resolved this issue in the latest RC build.
