### ISSUE TITLE
not connected 

### ISSUE THREAD

**Issue by kaskej** [microsoft/azuredatastudio#16548]
Issue Type: <b>Bug</b>

Connection canceled

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:13:05.032Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@kaskej there isn't enough details in this issue for us to provide any suggestions or investigation.  Please search through our issue history and there are many issues discussing potential ways to handle connectivity problems.  If you don't see an issue that discusses what you are seeing please reactive the issue with additional context.
