### ISSUE TITLE
Arc controller dashboard lists empty endpoint

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#16545]
![image](https://user-images.githubusercontent.com/28519865/128059041-65120a7c-6f99-426f-bddc-27715c7458d9.png)

Is there even an endpoint anymore now that everything is going through k8?

**Comment by candiceye** [comment]
I think we can take that field out entirely. @swells checking with you, there's no more controller endpoint right?

**Comment by candiceye** [comment]
Checked with Sean offline and we no longer need endpoint. Sent out a PR to remove the controller endpoint: https://github.com/microsoft/azuredatastudio/pull/16647
