### ISSUE TITLE
MSSQL 2008 R2 

### ISSUE THREAD

**Issue by lzuhuo** [microsoft/azuredatastudio#16568]
Issue Type: <b>Bug</b>

Not connect

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:01:02.538Z)
OS version: Linux x64 5.11.0-7620-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-4160T CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 0|
|Memory (System)|15.55GB (12.31GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by abist** [comment]
@lzuhuo Thanks for opening the issue. Can you describe your issue in more detail? Are you having problems connecting to the server?

**Comment by kburtram** [comment]
@lzuhuo Azure Data Studio doesn't officially support 2008 R2 and there are some known incompatibilities.  In some cases it may still function correctly for various use-cases, but in general the suggestion is to use an alternate tool for working with that version of SQL Server.  Sorry for the inconvenience.

**Comment by lzuhuo** [comment]
Actually, I can connect on windows using azure data studio, but not on ubuntu 21.04
