### ISSUE TITLE
查询结果字体无法自定义

### ISSUE THREAD

**Issue by yineric** [microsoft/azuredatastudio#16592]
Issue Type: <b>Feature Request</b>

查询结果，特别是表格查询结果的字体无法自定义为其他字体，比如微软雅黑

Azure Data Studio version: azuredatastudio 1.28.0 (13e362762762e5cb76a5c8afd2bc650f48c2d3d8, 2021-04-15T00:24:15.710Z)
OS version: Windows_NT x64 10.0.19042

**Comment by kburtram** [comment]
@yineric we do not currently have an option to set the query results grid font in ADS.  Unfortunately we are only able to work with issues filed using English text.  Please open an issue using English if you'd like to have this enhancement tracked in our backlog.  Thanks!
