### ISSUE TITLE
Default installation location for .NET on Linux

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#16598]
Default installation location for .NET on Linux platform is /usr/share, but the default used in Sql Database projects is /usr/local/share- hence it throws an error while loading the extension as well while building any project

Steps to Reproduce:
1. Open Sql db projects extension in ADS on Linux platform. Or build a project in ADS on Linux platform.
2. Even if .NET is installed, it would thrown an error that the installation is missing.

Workaround: Provide the installation path (/usr/share/dotnet) in sdk location in settings.
![image](https://user-images.githubusercontent.com/57200045/128563854-b6272e50-95b8-4f64-9918-8c1b26607dcc.png)

**Comment by Charles-Gagnon** [comment]
@SakshiS-harma Were you planning on fixing this? I just ran into this issue on Linux.
