### ISSUE TITLE
Unable to create a Database Project from Azure Synapse Analytics Serverless Pool database

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/azuredatastudio#16607]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. connect to serverless pool
2. Right click connection -> Create Project from Database

![image](https://user-images.githubusercontent.com/7981510/128579504-4b5de4f6-4dd9-4d7c-993a-8a572eb4b89d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@jasonhorner can you try this scenario in SSDT to see if the error also repros or if this is ADS specific? Thanks!

**Comment by kisantia** [comment]
closing this issue as support for Synapse Serverless Pool in DacFx is being tracked in https://github.com/microsoft/DacFx/issues/23
