### ISSUE TITLE
Still receiving error that the SQL Server Import Wizard will not start

### ISSUE THREAD

**Issue by Rik-Tec** [microsoft/azuredatastudio#16600]
Issue Type: <b>Bug</b>

Trying to upload a CSV to a database. I submitted a bug report yesterday when this was happening. It actually started working later yesterday but it has started not working again

Extension version: 1.3.1
Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.61GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
@aasimkhan30

**Comment by aasimkhan30** [comment]
@Rik-Tec, what is the error you are getting over here? Is the wizard starting successfully for you?
If possible, can you please paste a screenshot?

**Comment by Rik-Tec** [comment]
Hey @aasimkhan30 

![image](https://user-images.githubusercontent.com/84989347/128935294-6c34370b-53e5-42ec-b769-b1d5b9018f1a.png)

![image](https://user-images.githubusercontent.com/84989347/128935340-57fcce94-92d4-461b-9bfe-5cb71fdcd57c.png)

Let me know if those worked or if you need me to acquire additional information

**Comment by aasimkhan30** [comment]
@Rik-Tec Can you delete the folder 

C:\Users\erik.itner\.azuredatastudio\extensions\microsoft.import-1.3.1\flatfileimportservice (close ADS before deleting).

and reopen the import wizard in ADS?

**Comment by Rik-Tec** [comment]
![image](https://user-images.githubusercontent.com/84989347/129387220-74009a0c-41b8-467c-87b9-4060b12fdac5.png)

It worked. Thanks

**Comment by aasimkhan30** [comment]
Closing issue as it has been fixed.
