### ISSUE TITLE
Number separators not using current locale setting

### ISSUE THREAD

**Issue by Keen83** [microsoft/azuredatastudio#16617]
Issue Type: <b>Bug</b>

Hi! I am from Ukraine and have ukrainian number settings on my PC. That means I use comma as a decimal numbers separator. But when I select data from decimal column in AzDataStudio, I see the result with dot as a separator. At the same time, Excel works well and show me decimal numbers with commas.
Previousy it used to work well until I updated Azure Data Studio this week

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (5.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by smartguest** [comment]
This seems to be caused by a recent change in SQL Tools Service that returns the wrong number separator for some reason, this change may have been done for a reason.

**Comment by smartguest** [comment]
It appears this is an issue with the dotnet version bump used by sqltoolsservice, the get string for the value appears to function differently, I will need to see how to change this.
