### ISSUE TITLE
Tasks no longer work in 1.31.1 - 'Cannot read property 'variables' of undefined'

### ISSUE THREAD

**Issue by kerwinc** [microsoft/azuredatastudio#16615]
After installing 1.31.1, custom tasks no longer work. Reverting back to 1.30.0 works.

- Azure Data Studio Version: 1.31.1
- OS Version: Windows 10 version 2004 (OS Build 19041.928)

Steps to Reproduce:

1. Create a tasks.json file in the .azuredatastudio folder with the following task:

```
{
  "version": "2.0.0",
  "command": "pwsh.exe",
  "inputs": [
    {
      "id": "paramMessage",
      "description": "Message:",
      "default": "This should work...",
      "type": "promptString"
    }
  ],
  "tasks": [
    {
      "label": "Write-Message in Shell",
      "type": "shell",
      "command": "Write-Host \"Message is: ${input:paramMessage}\"",
      "problemMatcher": [],
      "group": "none"
    }
  ]
}

```

2. Run the task from Azure Data Studio.

### Error Reported:

```
Cannot read property 'variables' of undefined
```

![image](https://user-images.githubusercontent.com/1898560/128593005-b55d75aa-94e4-4d97-ad99-a23da839417b.png)

**Comment by Charles-Gagnon** [comment]
@abist

**Comment by kerwinc** [comment]
Thanks @abist !
