### ISSUE TITLE
Assessment does not throw runtime errors in RC 1.32

### ISSUE THREAD

**Issue by brian-harris** [microsoft/azuredatastudio#16639]
This change is in main branch.
PR for main branch: https://github.com/microsoft/azuredatastudio/pull/16627

Steps:
* create a source connection with a user that does not have permission to access more than one database
* open sql-migration extension for that source server
* click create new migration
* select all databases to assess for migration and click next
* an error message should display but notice error message does not relate to assessment
* select to view assessment results for sql managed instance* 
* notice assessment results are missing

**Comment by kburtram** [comment]
This has been merged into release/1.32 branch.
