### ISSUE TITLE
Add support to cancel the dialog closing event

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#1664]
- SQL Operations Studio Version:
latest master as of 6/18/2018

Steps to Reproduce:
The dialog created by the extension framework using sqlops.window.modelviewdialog.createDialog('test dialog'), doesn't support the cancellation of the dialog closing event, the desired behavior should be:
1. On 'OK' clicked event, the extension should be able to cancel the closing event. e.g. in case of error while creating the object, it would be helpful to keep the dialog opened so that the user can retry the operation
2. In case of cancel button clicking or ESC key pressing, the framework should ask the extension whether to show a confirmation dialog to avoid the data loss...

**Comment by kburtram** [comment]
Closing old tasks.  Please open in the context of an extension under active development.
