### ISSUE TITLE
Database name's text box's text isn't used whenever a query is run

### ISSUE THREAD

**Issue by himanshu-panchal** [microsoft/azuredatastudio#16659]
Issue Type: <b>Bug</b>

1. Open Azure Data Studio and connect to a server with multiple databases.
2. Select a database from the dropdown in header. Actually, even after typing it, you will have to click the database's name in the dropdown.
![image](https://user-images.githubusercontent.com/88723282/128896178-6e54d805-12c4-4264-99bb-de1b1f412ab0.png)

3. Now(preferably) run a select command on a table in the database we just selected. For this illustration I selected 'master' database and have a table 'TblBugTest' in it.  It is supposed to run perfectly as expected.
![BE0DAB87-283A-4EC7-90D2-935671E78050](https://user-images.githubusercontent.com/88723282/128896322-ec319156-43c5-40b2-9f18-3d4ab4d88f62.png)

4. Now I have another database 'APIRND', type your second database's name in the database name text box accurately but do not press enter or click the name in the dropdown.
5. Now for my illustration, 'APIRND' doesn't have 'TblBugTest' table, but when we will press run, the command will execute successfully, moreover it will run that query on the last dropdown clicked database(i.e. master in this case).
![B6004FCF-A760-4F19-920B-8EEC097476C0](https://user-images.githubusercontent.com/88723282/128896492-a33ac6fb-7696-4d2c-8ffd-7835a8c53141.png)

6. Now, type 'APIRND' in the database name text box but this time click on this database's name in the dropdown.
7. Now, since the table is not in the second database , it will not execute successfully.
![image](https://user-images.githubusercontent.com/88723282/128896612-5f965db1-484d-4cad-87f6-121c42ee2922.png)

My assumption is that clicking on the database name on the dropdown updates a variable and that variable is used as the target database.  In my opinion, either the database name's text box should always reflect that variable's value or everytime the query is run or the target database's name should be fetched from the database name's texbox.

I know the active database’s name is in the bottom right corner but it can still cause confusion to those who are migrating to Azure Data Studio on UNIX or windows systems and may also drive them to reach wrong conclusions while handling their data.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8300H CPU @ 2.30GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
It sounds like the issue may be that we aren't committing the database selection when we move focus out of the dropdown.  We only update on click and ENTER events.

**Comment by himanshu-panchal** [comment]
> It sounds like the issue may be that we aren't committing the database selection when we move focus out of the dropdown. We only update on click and ENTER events.

I get that but if someone copies database name directly to the text box which is a usual practice with SSMS users, it might lead them to believe that their data(or the program) is wrong
