### ISSUE TITLE
Getting "The filename, directory name, or volume label syntax is incorrect." trying to run Python commands

### ISSUE THREAD

**Issue by gitmadness** [microsoft/azuredatastudio#16656]
Issue Type: <b>Bug</b>

Updated Python and ADS and now Python commands like %pip install Kqlmagic fail with "The filename, directory name, or volume label syntax is incorrect.". 

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.22000

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (55.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Could you check this out?

**Comment by lucyzhang929** [comment]
Hi @gitmadness, I am able to repro and will look into the issue. In the meantime, could you try using the following to install Kqlmagic?
```
import sys
!{sys.executable} -m pip install Kqlmagic
```

**Comment by gitmadness** [comment]
@lucyzhang929, the below command works

import sys
!{sys.executable} -m pip install Kqlmagic

**Comment by gitmadness** [comment]
@lucyzhang929, just to clarify, do you plan to restore the original behavior or do I need to add "import sys..." everywhere?

**Comment by lucyzhang929** [comment]
@gitmadness I will investigate the issue for our September release but in the meantime I would suggest using the code snippet above.

**Comment by gitmadness** [comment]
Using the code snippet means updating all the code cells in all the notebooks, right? That is inconvenient. Is there another workaround which require less updates?
________________________________

**Comment by lucyzhang929** [comment]
It looks like this is a known issue with IPython 7.26: https://github.com/ipython/ipython/issues/13084. You can mitigate the issue by downgrading to 7.25. 

To install IPython 7.25 in ADS, open the Manage Packages wizard, 
![Screen Shot 2021-08-12 at 8 03 27 AM](https://user-images.githubusercontent.com/23462877/129220626-04b79e25-b7e2-488d-80ef-a4e283e6e503.png)

search for IPython and choose 7.25 in the package version dropdown. You may need to restart ADS after the installation is complete.
![Screen Shot 2021-08-12 at 8 03 45 AM](https://user-images.githubusercontent.com/23462877/129220639-3030fa4f-208a-4102-9d06-c74ae535b678.png)


I will close this issue for now. Feel free to re-open if you have any other questions!
