### ISSUE TITLE
SQL Db Projects extension doesn't load, if no input provided on information message

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#16657]
Steps to Reproduce:

1. If dotnet isn't installed or a dotnet version isn't supported and no input is provided on the informational pop-up, sql db projects extension fails to load. 
![Capture](https://user-images.githubusercontent.com/57200045/128898094-841f91e3-357c-472b-96fc-ffe36fd4e7fa.JPG)

Workaround:
Reload ADS and when the pop up comes, provide an input.
![image](https://user-images.githubusercontent.com/57200045/128898047-76b0ae84-935c-4080-9fa0-a0004c358a89.png)

**Comment by udeeshagautam** [comment]
Reopeneing since its not aprroved/ported.

**Comment by udeeshagautam** [comment]
Port PR merged
