### ISSUE TITLE
An unexpected error occurred while connecting.

### ISSUE THREAD

**Issue by AmmonNucor** [microsoft/azuredatastudio#16673]
Issue Type: <b>Bug</b>

I got an error that said to file a report, and to include this file:
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/6963878/renderer1.log)

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks! I'm going to close this now since we have the information we need and there are already numerous issues for connection problems. If you have any additional information to add either reply here or file a new issue.
