### ISSUE TITLE
Custom buttons for the wizard page are not displayed

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#16687]
- Version: 1.32.0-insider (user setup)
- Commit: 309e558727225bde9e577f8f566e68f8b657ae45
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Modify `/samples/sqlservice/src/controller/mainController.ts` on line 527, replace `wizard.customButtons = ...` with `page1.customButtons = ...`, which essentially registers custom buttons for a certain page, instead of the entire wizard
2. Build the `sqlservice` sample extension and install it in ADS
3. In ADS run the `sqlservice.openWizard` command from command palette
4. Look at the buttons panel at the bottom

Actual result:
![image](https://user-images.githubusercontent.com/11728682/128949813-5c673987-5aaf-4b33-acfd-5e6fb72f16e7.png)

Expected result:
![image](https://user-images.githubusercontent.com/11728682/128949677-388d158f-cc3a-408d-b48d-5fd28d251a9d.png)

**Comment by Charles-Gagnon** [comment]
Not ideal - but as a workaround you should be able to register the button on the wizard level and then just show/hide it as needed. The import wizard currently does this : 

https://github.com/microsoft/azuredatastudio/blob/main/extensions/import/src/wizard/flatFileWizard.ts#L148

@alanrenmsft Do you know anything about this? I wonder if this ever worked - none of our code even seems to use this.

**Comment by nahk-ivanov** [comment]
@Charles-Gagnon that's what I've done, yes. I'm not sure about "if this ever worked" part, but here's what the JSDoc says for the `customButtons` on the wizard:

![image](https://user-images.githubusercontent.com/11728682/128952660-4d3d10a4-80f9-4657-a699-cb3fd3193dd2.png)

Hard to estimate the work when I planned to simply place two elements in an array, but ended up doing my own wizard wrapper that manages the buttons state between navigations...
