### ISSUE TITLE
LoadingComponent does not propagate children validity state

### ISSUE THREAD

**Issue by nahk-ivanov** [microsoft/azuredatastudio#16692]
- Azure Data Studio Version: 1.32.0-insider (user setup)
- Commit: 309e558727225bde9e577f8f566e68f8b657ae45
- OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Modify `/samples/sqlservice/src/controller/mainController.ts`:
    - on line 128 change `}).component();` to `}).withValidation(() => false).component();`, essentially adding a validation to the tree control that always reports invalid state;
    - after line 133 add `tree.validate();` which performs validation of the tree control when check state changes;
2. Build the `sqlservice` sample extension and install it in ADS
3. In ADS run the `sqlservice.openDialog` command from command palette
4. Look at the buttons pane at the bottom of the dialog

**Expected result:**

![image](https://user-images.githubusercontent.com/11728682/128953430-63a9d706-19df-441d-8042-713dd359d2db.png)

**Actual result:**

![image](https://user-images.githubusercontent.com/11728682/128953296-1e6debe7-3478-41c8-b0c2-3a27ec7732c8.png)

You can achieve the expected result by simply removing loading component from the equation: in `mainController.ts` on line 155 (original 154) replace `formWrapper` with `formModel` when calling `initializeModel` - the form will propagate children validity state just fine. The problem is that loading component is a container, but does not inherit from `ContainerBase`, since it only allows one child. Instead it maintains its own child reference. There is no code that subscribes to child validity state change event, like the `ContainerBase` does.

**Comment by nahk-ivanov** [comment]
I also noticed that validity state of the loading control itself does not refresh when you set `loading` property. For instance, initial state is `loading = true` and it reports invalid (which is great, you should not be able to complete/navigate further), but when you set `loading = false`, it still stays invalid, until you explicitly call `validate()` on it. I think it should be done automatically, as for all other controls when their state changes.

**Comment by alanrenmsft** [comment]
> I also noticed that validity state of the loading control itself does not refresh when you set `loading` property. For instance, initial state is `loading = true` and it reports invalid (which is great, you should not be able to complete/navigate further), but when you set `loading = false`, it still stays invalid, until you explicitly call `validate()` on it. I think it should be done automatically, as for all other controls when their state changes.

@nahk-ivanov when setting the loading property of loading component, it will trigger the validation event, I am not able to reproduce the issue. 

I have a fix for the main issue.
