### ISSUE TITLE
Incorporation of the AZUREDATASTUDIO_EXTENSIONS environment variable as a replacement or prevailing alternative to VSCODE_EXTENSIONS.

### ISSUE THREAD

**Issue by claudio-salvio** [microsoft/azuredatastudio#16739]
In **VSCode**, I use the **VSCODE_EXTENSIONS** environment variable to make it so that **all users** using the program on a computer have the **same set of extensions** available without having to replicate it to each user profile.

I would like to do the same thing with **Azure Data Studio (ADS)** but would want to have a **specific environment variable** for it.
That variable could be called **AZUREDATASTUDIO_EXTENSIONS** or **ADS_EXTENSIONS**.
It could replace the **VSCODE_EXTENSIONS** variable or supplement it in a prevalent way.
What I want to imply by this is that if both are declared only the ADS specific variable should be taken into account.

From what I found exploring the source code it seems to be used only in:
https://github.com/microsoft/azuredatastudio/blob/3cb2f552a6f004dccd153577aecfd75f3d1bacae/src/vs/platform/environment/common/environmentService.ts#L147

It seems to me that this could be achieved by replacing:
```javascript
const vscodeExtensions = env['VSCODE_EXTENSIONS'];
```
with:
```javascript
const vscodeExtensions = env['AZUREDATASTUDIO_EXTENSIONS'] ?? env['VSCODE_EXTENSIONS'];
```
Greetings,
Claudio

**Comment by Charles-Gagnon** [comment]
Good suggestion! I've opened a PR for adding `ADS_EXTENSIONS` as an option : https://github.com/microsoft/azuredatastudio/pull/16747

**Comment by claudio-salvio** [comment]
Thank you!
