### ISSUE TITLE
Seeing "Project already opened" message for every project I open or create

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#16755]
- Azure Data Studio Version: 1.32 RC (latest Projects extension)
- OS Version:

Steps to Reproduce:

1. Open ADS
2. Create a database project or open a database project that is not opened already
3. the project is created/opened fine but it always shows an information message - project already open 
4. Expectation is : this message should ONLY show when the project is actually already opened in workspace.

![image](https://user-images.githubusercontent.com/46980425/129263212-89557e93-1d46-48da-a6f4-beceb7cf5b4c.png)

This doesnt hinder the fnuctionality so I am hesitant in taking this so late but should surely take for next release.

**Comment by udeeshagautam** [comment]
@Benjin can you take a look, not sure if its related to fixes we did for tree update. Probably wont qualify for August.

**Comment by Charles-Gagnon** [comment]
@udeeshagautam The RC1 gallery hasn't been updated yet (it should be 0.12.0)

Can you try on insiders and see if you still see it there?

**Comment by Charles-Gagnon** [comment]
The gallery was just updated so try again with the latest version
