### ISSUE TITLE
SQL DB Project - Open Existing project window 'select project file Location' textbox is disappearing  

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#16751]
- Azure Data Studio Version: 
- OS Version:

Open Existing project window 'select project file Location' textbox is disappearing when selecting git repository radio button and selecting Local radio button again.

Steps to Reproduce:

1. Install SQL DB Projects extension
2. Select DB Projects from the side bar.
3. Click on Open existing folder icon) on top and a open existing project window opens.
4. Select Git repository button and select back to Local, notice the "select project file Location" textbox is disappearing.

Repro Video:
https://user-images.githubusercontent.com/74571829/129240045-4378cd9f-85d6-4ba6-80e4-62bb648bf652.mp4

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Note that the local clone path is having the same issue so likely the same fix will be needed there 

![image](https://user-images.githubusercontent.com/28519865/129246206-a816b047-83d6-4a7d-9580-fc66a8341e5d.png)

**Comment by udeeshagautam** [comment]
Yep noticed that too. restating the same worry - I am still not sure if we are catching all of these instances affected by model view change

**Comment by udeeshagautam** [comment]
Closing since port is merged
