### ISSUE TITLE
SQL projects don't build when active dotnet version is 6.0 preview

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#16766]
Repro:
1. Install any version of .NET 6.0 (including via VS 2022)
2. Try to build any SQL project using SQL Database Projects extension

Expected: success
Reality: Failure with no error message
![image](https://user-images.githubusercontent.com/1609827/129280783-0654783c-3a9e-441f-9b31-08c53330a1d5.png)

Work-around:

force dotnet.exe to target a lower version of .NET, per [these instructions](https://docs.microsoft.com/en-us/dotnet/core/versions/selection).  You can run `dotnet new globaljson --sdk-version 5.0.400 --force` to generate a global.json file.  Put it in next to `azuredatastudio.exe`.

**Comment by kisantia** [comment]
related to #15910

**Comment by pkanavos** [comment]
There's no need to put `global.json` next to the executable. This won't work on a Mac anyway. It's enough to put `global.json` in the project folder or a parent.

Unfortunately, this affects Visual Studio Code as well. Annoyingly, the warning pops up even if no database project is loaded.

**Comment by kisantia** [comment]
This has been fixed in DacFx and will be included in the next release of ADS and the sql database projects extension in vscode.

**Comment by kisantia** [comment]
updated DacFx was brought into ADS in #17627
