### ISSUE TITLE
Vertical selections with Alt key modifier

### ISSUE THREAD

**Issue by Devy-Devly** [microsoft/azuredatastudio#16763]
Issue Type: <b>Feature Request</b>

Hi,

In SQL Management Studio you can select text vertically with the Alt key modifier.
Would be great to have this in Azure Data Studio too please.

Many thanks.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:03:21.018Z)
OS version: Windows_NT x64 10.0.19043

**Comment by Charles-Gagnon** [comment]
In ADS holding alt + shift will allow you to select text in a column.
