### ISSUE TITLE
Copy the template of missing index (from the query plan) for applied it

### ISSUE THREAD

**Issue by mstaelen** [microsoft/azuredatastudio#16774]
Issue Type: <b>Feature Request</b>

It could be interesting to copy the template to paste it in the notebook or apply directly with a prompt for the naming.

Azure Data Studio version: azuredatastudio 1.31.1 (65fb22cc7c36db9c53af1ed2fdbdf48f66c682be, 2021-07-28T21:13:05.032Z)
OS version: Darwin x64 20.6.0

**Comment by aasimkhan30** [comment]
This feature is added in the new execution plan feature. You can click on the recommendations to open the missing index query in a new window. 

![image](https://user-images.githubusercontent.com/6816294/163854614-008c516f-498e-43a0-96ba-b001ab859696.png)
