### ISSUE TITLE
Run Powershell generates "Running the contributed command: 'Powershell.Debug.Start' Failed

### ISSUE THREAD

**Issue by brenttempleton** [microsoft/azuredatastudio#16793]
When running a Powershell file if I want to run the entire file it generates this error:
"Running the contributed command: 'Powershell.Debug.Start' failed.

![image](https://user-images.githubusercontent.com/54143062/129629598-93053504-ab03-4dfb-b62b-ed97dbc16bdc.png)

I can highlight all the content and use the "run selected" command and that works
I can put the content in a notebook cell and that works, just when I open a file and try to run the entire file without highlighting.

I have tried this on a few computers (co-workers, virtual machines, etc), so I'm pretty sure it is not something with my installation.

**Comment by Charles-Gagnon** [comment]
This appears to be an issue with the Powershell extension - could you please open an issue in their repo? https://github.com/PowerShell/vscode-powershell
