### ISSUE TITLE
Improvement needed on Azure Monitor Logs extension connection error

### ISSUE THREAD

**Issue by mikewo** [microsoft/azuredatastudio#16816]
- Azure Data Studio Version: 1.32.0-insider
- OS Version: Windows_NT x64 10.0.19042

Version: 1.32.0-insider
Commit: 95a08d2ce79f018905b390ffb12ebd6415a809e2
Date: 2021-08-17T05:36:26.904Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

This is minor, but a better experience could be made with improving the error messaging to the user.

Steps to Reproduce:

1. Install Azure Monitor Logs extension
2. Click to add connection
3. Supply valid Azure AD creds
4. Supply invalid connection workspace ID Or select an AD tenant that is different from where the workspace lives
5. Click Connect
6. Result is "Object reference not set to an instance of an object" error message. 

Perhaps something like "The Log Analytics Workspace can not be reached. Please validate the WorkspaceID, the correct tenant is selected, and that you have access to the workspace."

If there is an underlying error coming back that would be more helpful that could be surfaced as well.

Does this issue occur when all extensions are disabled?: No, but then the issue is in the extension.

**Comment by mikewo** [comment]
PS - Once connected this functionality is awesome! 😄

**Comment by MsSQLGirl** [comment]
@JustinMDotNet & @qifahs - FYI. Let's triage this for planning.

**Comment by MsSQLGirl** [comment]
@JustinMDotNet - can you please let us know when it's available in Insiders so that folks can help verify? 
Thanks,
Julie
