### ISSUE TITLE
Account with non-latin characters under Azure tab in Connections viewlet does not display correctly

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#16829]
- Azure Data Studio Version:
Version: 1.32.0 (user setup)
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:08:28.086Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Steps to Reproduce:

1. Connect to Azure account that contains non-latin characters. 
2. Go to Azure Tab in Connections viewlet. 

You'll see something like this:
![image](https://user-images.githubusercontent.com/6405919/130109593-bb9e571f-314f-4768-84dd-1aa236b7fc58.png)

Expected, non-latin characters should be supported. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by kburtram** [comment]
This looks like a variation of https://github.com/microsoft/azuredatastudio/issues/13896.  Closing as a duplicate.  I'll make a note in the at issue to also check this UI element that is displaying the same value.
