### ISSUE TITLE
Changing keyboard shortcut for copy results from grid has no effect

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#16843]
1. Open keyboard shortcuts and search for `grid.copySelection`
2. Change that to something else from the default ctrl+c
3. Run a query and select some cells, then press the new keybinding

Nothing happens. Pressing ctrl+c still copies the selection as expected though.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon  which version are you using?
for me: 
latest stable:
![image](https://user-images.githubusercontent.com/13777222/130286114-0490eb08-8a06-4cb0-96d6-038b5be7573a.png)

today's insider:
![image](https://user-images.githubusercontent.com/13777222/130286207-cb795b01-c318-4dde-9db9-e6f26aa9ca5e.png)

**Comment by Charles-Gagnon** [comment]
Well that's fascinating, I'm seeing ctrl+shift+c for all my instances. You're on Windows, right?

Guess I'll dig into why it's showing as ctrl+shift+c for me to see if something got changed locally....

**Comment by Charles-Gagnon** [comment]
🤦‍♂️ Yeah I just had set it manually to ctrl+shift+c sometime previously...so that explains that.

But it looks like something is broken here, because I would expect that if I change the keybinding to something else that it still works. But that's not happening - even if I change it to something like ctrl+u.

**Comment by Charles-Gagnon** [comment]
I updated the issue title to reflect the actual issue here. @alanrenmsft could you see if you can repro this just to make sure this isn't something else I missed with my local environment?

**Comment by alanrenmsft** [comment]
yes, I think the shortcut key binding is actually not being used here, hard coded to CTRL+C. a bug.

**Comment by Charles-Gagnon** [comment]
It's odd because we do register a keybinding for this (which is where the context menu is getting its value from)

https://github.com/microsoft/azuredatastudio/blob/main/src/sql/workbench/contrib/query/browser/query.contribution.ts#L230

So theoretically that should be triggered when the keybinding is pressed. But I'm not seeing it be hit at all.

**Comment by Charles-Gagnon** [comment]
Possible slickgrid is capturing the other keypresses and stopping them from propagating up. But other stuff like ctrl+p work so...yeah not sure off hand.

**Comment by alanrenmsft** [comment]
this has been fixed recently
![image](https://github.com/microsoft/azuredatastudio/assets/13777222/0b4a7911-2255-44c9-a1ae-411a6ab79565)
