### ISSUE TITLE
Unable to copy / paste cell data from query Results table

### ISSUE THREAD

**Issue by JordanMarr** [microsoft/azuredatastudio#16844]
- Azure Data Studio Version: v1.32.0
- OS Version: Win10

Steps to Reproduce:

1. Run a query
2. Try to copy a value from a single cell in the result set (select cell and hit CTRL+C)
3. Try to paste value into query pane (or anywhere) using CTRL+V
4. Result is that value was never copied to the clipboard

![image](https://user-images.githubusercontent.com/1030435/130270570-d99aad38-db30-4e0f-befa-463b182d336e.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes (I disabled _all_ extensions)

**Comment by Charles-Gagnon** [comment]
If you right click and select the "Copy" action does that also not work?

**Comment by JordanMarr** [comment]
> If you right click and select the "Copy" action does that also not work?

It does not work; I don't even get a context menu when I right click.

**Comment by Charles-Gagnon** [comment]
Do you get a context menu elsewhere in the app - like in the main editor pane or on the tree views to the side?

Could you also try downloading the [insiders version of ADS](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master) and seeing if you get the same thing there?

**Comment by JordanMarr** [comment]
I do get a context menu in both the query pane and the connections pane. 
I will try the insiders version next...

**Comment by JordanMarr** [comment]
Same issue in the freshly installed Insiders build: no context menu and CTRL+C doesn't copy cell value to my clipboard.

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Any ideas here? I've never seen any reports of this kind of issue happening and am not sure what could be causing some events not to be handled correctly...

**Comment by JordanMarr** [comment]
Console.log from dev tools console tab:
[console.log](https://github.com/microsoft/azuredatastudio/files/7023254/console.log)

**Comment by JordanMarr** [comment]
Zipped application log folder:
[20210820T125621.zip](https://github.com/microsoft/azuredatastudio/files/7023281/20210820T125621.zip)

**Comment by Charles-Gagnon** [comment]
Oh wow, thank you for finding that out @JordanMarr! Sorry about the issues you had, glad you were able to resolve it.
