### ISSUE TITLE
Unidentified error with azure authentication

### ISSUE THREAD

**Issue by saisn-kr** [microsoft/azuredatastudio#16855]
Issue Type: <b>Bug</b>

Hello, Initially I have added servers to the azure data studio, but later they do not login anymore. Everytime I try to logi in it gives me an error 'Unidentified error with azure authentication'. It works fine with sql server mgmt studio 18.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (9.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0
query-history|Mic|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
Closing as inactive. 
Please open a new issue with attached logs if issue persists with latest version of ADS.
