### ISSUE TITLE
Super Slow Performance

### ISSUE THREAD

**Issue by Colton-Bell** [microsoft/azuredatastudio#16917]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

took it a while to perform a simple SQL query (maybe 2-3 minutes) to return 331 values.

The same query (Below) runs under 00:00:01 on MS SSMS

SELECT TOP (1000) [StaffID]
      ,[UserName]
      ,[StaffName]
      ,[StaffNumber]
      ,[isAdmin]
  FROM [DB_NAME_REDACTED].[dbo].[Users]

I'm doubting its a its anything to do with the data or query, probably something in the environment. Please let me know what is to come of this. I like the sleek design of this UI/UX better than SSMS, but if this is something that is persistent in your system, I will have to go back.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (8.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    89	 19160	azuredatastudio main
    0	    77	   956	   shared-process
    0	    63	 13688	     ptyHost
    0	    70	 15656	       C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe
    0	     6	 17832	       console-window-host (Windows internal process)
    0	    38	  5476	   utility
    0	   124	 11468	   gpu-process
    0	    23	 14596	   crashpad-handler
    0	   226	 18564	   window (dbo.Users_1 - ProfTrack (Workspace) - Azure Data Studio)
    0	    12	 11156	     watcherService 
    0	    11	 11500	       console-window-host (Windows internal process)
    0	    65	 17976	     searchService
    0	   115	 19748	     extensionHost
    0	    65	  5988	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=19748
    0	    35	  7664	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.121\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\cbell\AppData\Roaming\azuredatastudio\logs\20210827T104504\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	    10	 15120	         console-window-host (Windows internal process)
    0	   127	 15104	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.121\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\cbell\AppData\Roaming\azuredatastudio\logs\20210827T104504\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	    10	 17240	         console-window-host (Windows internal process)
    0	    35	 15752	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.121\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\cbell\AppData\Roaming\azuredatastudio\logs\20210827T104504\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	    10	 12388	         console-window-host (Windows internal process)
    0	    80	 18984	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (dbo.Users_1 - ProfTrack (Workspace) - Azure Data Studio)
|    Folder (ProfTrack): 14 files
|      File types: cache(2) dll(1) pdb(1) txt(1) props(1) targets(1) sql(1)
|                  code-workspace(1) sqlproj(1)
|      Conf files:;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.12.0

</details>

**Comment by Smoovsky** [comment]
What's the latency between your client and server?
