### ISSUE TITLE
Schema Compare: "Specified method is not supported" when deselecting Change actions.

### ISSUE THREAD

**Issue by m4ttheweric** [microsoft/azuredatastudio#16934]
Version: 1.32.0
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:09:20.282Z (2 wks ago)
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 19.6.0

Steps to Reproduce:

1.  Initiate a schema comparison between two dbs, dacpacs, or any combo of those two.
2. Try to uncheck a "change" from the list of actions (can be changes to a table or SP)

Expected: I can uncheck a change to modify what I am applying.

Actual: After about 4 seconds, the checkbox changes back to "checked" and I get the error message: "Specified method is not supported".

Seems to be closely related to this: [https://github.com/microsoft/azuredatastudio/issues/15074]( https://github.com/microsoft/azuredatastudio/issues/15074 )

I made a comment over there but figured the best thing would be to open a new issue.

Mentioning @SakshiS-harma here since they were involved on the last issue as well.

Mentioning @maccer83 since they submitted the other issue. 

**Note:** I tried this on both the latest prod and insider builds. Same issue. The insider build does not allow me to toggle developer tools, so I chose to make all of my screenshots and logs from the production build so it's consistent.

**Note:** This does not seem to occur with any "Delete" actions. Also, a slightly different behavior occurs with the "Add" actions -- when attempting to uncheck some of them, it gives an error message "Cannot exclude <thing>. Included dependants exist". The thing in question is a "CREATE USER" statement, which makes no sense to be a "dependant".

The screenshot attached shows the developer console output. Nothing helpful happening in there from what I can see.

![Screen Shot 2021-08-30 at 10 57 44 AM](https://user-images.githubusercontent.com/49927862/131383848-484bba17-43fc-480d-911b-2adc5228b370.png)

[Application Logs](https://github.com/microsoft/azuredatastudio/files/7078568/app.logs.zip)
[Extension Logs](https://github.com/microsoft/azuredatastudio/files/7078572/extension.logs.zip)

**Comment by m4ttheweric** [comment]
As an update, the insider build does seem to exhibit some improvement, but not 100% resolved.

In the screenshots, I can uncheck some of the change actions, but not all of them:

![Screen Shot 2021-08-30 at 11 43 56 AM](https://user-images.githubusercontent.com/49927862/131388845-4080b4b0-996e-43e4-a562-81383cb4dae1.png)
![Screen Shot 2021-08-30 at 11 43 52 AM](https://user-images.githubusercontent.com/49927862/131388855-5d830eab-ba5b-4445-893b-3b3380e3fb36.png)

**Comment by kisantia** [comment]
@m4ttheweric can you share sample source and target dacpacs and which changes are showing the behavior so I can try to debug this? I haven't been able to get this error message when testing with my sample dbs.

**Comment by kisantia** [comment]
please reopen if sample source and target dacpacs that repro this can be shared.

**Comment by alder-french-leviton** [comment]
I'm experiencing this same issue with the latest version of Azure Data Studios. In my case I can't deselect certain table changes in Schema Compare, but I can deselect others. I get the same "Specified method is not supported" error.
