### ISSUE TITLE
Create data controller wizard shows a blank screen for choosing config profile step.

### ISSUE THREAD

**Issue by snaldurgkar** [microsoft/azuredatastudio#16964]
Azure data studio is running on Mac OS BigSur 11.5.2 
Azure data studio Version: 1.32.0 
Commit: 4a45ba7 
Date: 2021-08-16T18:09:20.282Z 
VS Code: 1.56.0 Electron: 12.0.7 
Chrome: 89.0.4389.128 
Node.js: 14.16.0 V8: 8.9.255.25-electron.0 
OS: Darwin x64 20.6.

Logs:
20210901T185839.zip

**Comment by Charles-Gagnon** [comment]
@snaldurgkar It looks like the logs didn't upload properly, can you please try again?

**Comment by snaldurgkar** [comment]
[20210901T185839.zip](https://github.com/microsoft/azuredatastudio/files/7094381/20210901T185839.zip)

**Comment by Charles-Gagnon** [comment]
@candiceye From the logs : 

```
Activating extension Microsoft.azcli failed due to an error:
[2021-09-01 18:58:49.551] [exthost] [error] TypeError: Invalid Version: 
	at new c (/Users/snaldurg/.azuredatastudio/extensions/microsoft.azcli-0.1.0/dist/extension.js:1:1645)
	at /Users/snaldurg/.azuredatastudio/extensions/microsoft.azcli-0.1.0/dist/extension.js:1:34041
	at processTicksAndRejections (internal/process/task_queues.js:93:5)
	at async t.findAz (/Users/snaldurg/.azuredatastudio/extensions/microsoft.azcli-0.1.0/dist/extension.js:1:33767)
	at async t.activate (/Users/snaldurg/.azuredatastudio/extensions/microsoft.azcli-0.1.0/dist/extension.js:1:19490)
	at async Promise.all (index 2)
	at async Promise.all (index 0)
```

Were you planning on releasing a new version of the azcli extension here at some point? You've made some big changes with the version parsing since the initial release so I wouldn't be surprised if the initial version of the extension is breaking in some scenarios.

@snaldurgkar Could you run `az --version` from the terminal and share the output?

**Comment by snaldurgkar** [comment]
az --version
azure-cli                         2.27.2
core                              2.27.2
telemetry                          1.0.6

Extensions:
k8sconfiguration                   0.2.4
k8s-configuration                  1.1.0
connectedk8s                       1.1.7
arcdata                            1.0.0
resource-graph                     2.1.0
customlocation                     0.1.2

Python location '/usr/local/Cellar/azure-cli/2.27.2/libexec/bin/python'
Extensions directory '/Users/snaldurg/.azure/cliextensions'

Python (Darwin) 3.9.6 (default, Jun 29 2021, 05:25:02) 
[Clang 12.0.5 (clang-1205.0.22.9)]
Legal docs and information: aka.ms/AzureCliLegal
Your CLI is up-to-date.

**Comment by snaldurgkar** [comment]
I've not changed anything ,but today I'm able to see the config profiles populated and also deploy data controller.

**Comment by chlafreniere** [comment]
@snaldurgkar since this doesn't repro any longer, closing this. If it occurs again, please feel free to reopen. Thanks!
