### ISSUE TITLE
Notebook: Support for text editing shortcut such as Ctrl+b, etc

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#16977]
**Is your feature request related to a problem? Please describe.**
Ctrl+b should bold text but it toggles the left side controls

**Describe the solution or feature you'd like**
Idea: Context-aware keyboard shortcut?
Questions:

1. what does VSCode support today for their notebook w.r.t Ctrl+B etc? Not by default.
2. is the next step to support jupyter notebook shortcut as well? on top of this text editing keyboard shortcut?

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by VasuBhog** [comment]
@MsSQLGirl answers to your questions:
1. VS Code Notebooks currently have no support for keybindings to markdown text (specifically the ones we have on our markdown toolbar - Bold, Italicize, Underline... etc). 
2. I also found that Jupyter Notebooks does not support any kind of Markdown keybindings as well. 

I believe we can add a few general keybindings for some of the markdown toolbar actions we currently have.

**Comment by VasuBhog** [comment]
Added keybindings for WYSIWYG will investigate splitview/md shortcuts as well. Tracked here: #17210
