### ISSUE TITLE
Notebook: Insert Link button behaviors in Markdown vs in WYSIWYG

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#16972]
- Azure Data Studio Version:
Version: 1.32.0 (user setup)
Commit: 4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e
Date: 2021-08-16T18:08:28.086Z
VS Code: 1.56.0
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19043

Insert Link in markdown behavior is different from Insert Link in WYSIWYG.

Steps to Reproduce:

1. Use Insert Link button in Markdown and paste from "copy relative path" that has spaces in the path. 
2. Use Insert Link button in WYSIWYG and paste from "copy relative path" that has spaces in the path.

WYSIWYG creates and translates link to relative properly.
Markdown does not create a link. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by chlafreniere** [comment]
@VasuBhog is this at all related to the encoding/decoding work that you're doing?

Curious if we can lump it in with that work or if this is wholly separate.

**Comment by VasuBhog** [comment]
@chlafreniere I believe that I can check this in as well with the other work.
