### ISSUE TITLE
Notebook: WYSIWYG edit mode should allow link tooltip

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#16975]
**Is your feature request related to a problem? Please describe.**
After editing or creating a link when you hover over it you don't get a tooltip showing you where the link points to.

**Describe the solution or feature you'd like**
Add tooltip when text cell is not on edit mode. This is needed especially to make sure that uses know where the link would go to (security reasons)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by chlafreniere** [comment]
Should be addressed by #16967.
