### ISSUE TITLE
Unexpected Error Occured while connecting

### ISSUE THREAD

**Issue by neap15** [microsoft/azuredatastudio#16998]
Issue Type: <b>Bug</b>

Tried to connect with credentials that worked previously, over an OpenVPN connection.  possible issues with DNS when switching VPNs?

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:09:20.282Z)
OS version: Darwin x64 20.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
import|Mic|1.3.1
profiler|Mic|0.11.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4

</details>

**Comment by kburtram** [comment]
@neap15 what error are you receiving when you try to connect to the SQL Server?

**Comment by neap15** [comment]
This seems to be a network issue.  My ISP is blocking the VPN I require to access this server.

**Comment by kburtram** [comment]
I'll close based on the previous comment.  Unfortunately the network issue will need to be resolved before connecting in ADS.  Thanks!
