### ISSUE TITLE
Switching active queries using File Explorer causes DB drop-down selector to losses value

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#16992]
- Azure Data Studio Version: `main`

Steps to Reproduce:

Same repro as related bug https://github.com/microsoft/azuredatastudio/issues/4656.

1. Open folder with multiple SQL files
2. Open a couple files and connect to dbs
3. Switch between active documents by selecting files in File Explorer

Expected: Results, connection and UI state is maintained when switching documents

Actual: Query document database drop-down selector says `undefined` but connection and results are persisted.

![image](https://user-images.githubusercontent.com/599935/132051057-e15a9f73-086d-44c9-a563-1fb571e0b5f4.png)

**Comment by smartguest** [comment]
Issue appears to be caused by the connection profile being unable to retrieve the database name for some reason.

**Comment by smartguest** [comment]
When paused and debugging, the connection management service is able to retrieve the name, however without the pause and debugging, it seems to move onto the next line quickly without waiting for the profile to be loaded.

**Comment by smartguest** [comment]
If you click on a file from file explorer, it tries to create a brand new connection instead of switching over to a new connection profile, which causes problems.
