### ISSUE TITLE
Feature Request: work with Central Management Server

### ISSUE THREAD

**Issue by Zhunya** [microsoft/azuredatastudio#17]
- SQL Operations Studio Version: 0.23.6

We have lot of servers group and a lot more servers in CMS, recreating them in new OPS will be big headache.

**Comment by pmpjr6465** [comment]
Completely agree. We have a couple hundred instances, to manually add them would be no good.

**Comment by Zhunya** [comment]
I think it will be possible to write custom script to convert CMS content to %APPDATA%\sqlops\User\Settings.json with help from [dbatools](https://github.com/sqlcollaborative/dbatools) module function Get-DbaRegisteredServer

**Comment by jdshkolnik** [comment]
@Zhunya As a one-time thing, yes, but that would mean breaking from actively used/maintained CMS which is unappealing.

**Comment by kburtram** [comment]
@Zhunya we plan to fully support CMS integration in Object Explorer viewlet prior to GA.

**Comment by R-i-c-h-B** [comment]
Being able to seamlessly integrate with the CMS's that the other groups are maintaining would definitely be extremely beneficial.  Taking it a step further, and having a mechanism to transparently source control those CMS contents through git integration with the rest of the projects/workspaces would be even better :)

**Comment by sonnypdx** [comment]
I created a python script to convert the regsvr contents into JSON that can be copy/pasted into user settings file.  Have not had a chance to create a help document yet, but anyone is interested in using it or extending it please feel free:
https://github.com/sonnypdx/pynotes/blob/master/sqlopsstudio/regsvrToJSON.py

**Comment by jdshkolnik** [comment]
Where does this stand? It's the main reason I don't use Data Studio.

**Comment by kburtram** [comment]
@jdshkolnik we are currently doing our planning through the end of June and this item was included in a larger proposal to update the Server viewlet (basically to consolidate the Server and Azure viewlets and make the new Server viewlet extensible to additional Data Source metadata providers, such as CMS).  Hopefully, this would land in March or April releases, but we aren't currently working on this feature yet.

**Comment by NJohnson9402** [comment]
Needs to happen! It's a roadblock for adoption. Glad that it's on the roadmap; let's get it done.

**Comment by amtwo** [comment]
@kburtram Do plans to "fully support CMS integration" include support for multi-server queries? In SSMS, that is one of the features I use CMS for the most--to run a query against a group of CMS servers, and get a single, consolidated result set.

**Comment by reharmsen** [comment]
I sure hope this will be included in the June release, as we plan to also start using Azure Data Studio a lot more next to SSMS18. But currently this is a blocking issue for us.

**Comment by yualan** [comment]
CMS is coming in June release and already available in our Insider Build. Closing issue.
