### ISSUE TITLE
ADS Web Smoketest is failing because of a timeout while waiting for Python install notification.

### ISSUE THREAD

**Issue by lewis-sanchez** [microsoft/azuredatastudio#17017]
In [notebook.test.ts](https://github.com/microsoft/azuredatastudio/blob/main/test/smoke/src/sql/areas/notebook/notebook.test.ts), the smoke test that opens a new notebook, configures Python, and executes one cell is failing because of a timeout in the _waitForInstallationComplete method in [configurePythonDialog.ts](https://github.com/microsoft/azuredatastudio/blob/main/test/automation/src/sql/configurePythonDialog.ts).

The timeout seems to be happening because the python installation complete notification isn't rendering after 1 minute.

**Comment by lucyzhang929** [comment]
I can increase the timeout - hopefully that'll pass the tests. Thanks for opening the issue!
