### ISSUE TITLE
Add option for Word wrap in query window

### ISSUE THREAD

**Issue by raoulteeuwenPE** [microsoft/azuredatastudio#17022]
**Is your feature request related to a problem? Please describe.**
When currently editting queries, as a user i'm not able to activate word wrap, which makes me need to scroll horizontally

**Describe the solution or feature you'd like**
Add an option (in the View menu?) to toggle Word wrap, so text wraps and the user does not have to scroll horizontally

**Describe alternatives you've considered**
Keep scrolling ;-)

**Additional context**
-

**Comment by Charles-Gagnon** [comment]
There's a `Toggle Word Wrap` command that seems to work fine for me, is this not functioning for you?

**Comment by raoulteeuwenPE** [comment]
> There's a `View: Toggle Word Wrap` command that seems to work fine for me, is this not functioning for you?

I did not find any reference to that while searching both in ADS and online. Thank you, does what i was looking for :-).
