### ISSUE TITLE
Azure view doesn't properly set Server Group when showing Connection Dialog

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#17037]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Use Azure view to navigate through SQL DB resources
2a. Expand database that you don't have AAD permissions to

or

2b. Click the Connect button on the DB resource

Expected: In 2a the Server Group is set to `<Do not save>` and the connection is not saved.  In 2b the Server Group is set to `<Default>` and the connection is saved.

Actual: In 2a the Server Group is set to `<Default>` and the connection is not saved.  In 2b the Server Group is set to `<Do not save>` and the connection is saved.

**Comment by cheenamalhotra** [comment]
PR #22518 addresses 2b, 

However I cannot reproduce 2a. When connecting to a server without AAD access, I get below error:
`Login failed for user '<token-identified principal>`
