### ISSUE TITLE
Git Source Control UI unavailable

### ISSUE THREAD

**Issue by persamina** [microsoft/azuredatastudio#17033]
- Azure Data Studio Version: 1.33.0-insider (user setup)
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Open a folder with git initialized in it
2. Navigate to the Source Control tab (Ctrl+Shift+G)
3. Observe that the UI interface is not available.

Does this issue occur when all extensions are disabled?: Yes - no extensions are installed

**Comment by kburtram** [comment]
This looks like an in-cycle regression.  Git appears to be working correctly on the latest stable build.  Thanks for reporting!  We'll take a look.
