### ISSUE TITLE
Allow SSMS results window to be on a different monitor

### ISSUE THREAD

**Issue by AtlasRoark** [microsoft/azuredatastudio#17043]
SSMS Results window takes up prime screen real estate.  Always have to ctrl-r to make it go away.

Allow an option to open results window on a different monitor

**Comment by kburtram** [comment]
Thanks for opening this suggestion!  This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/8964.  Please add any additional context to that issue if there is anything missing.

**Comment by AtlasRoark** [comment]
Not exactly a duplicate of [#8964](https://github.com/microsoft/azuredatastudio/issues/8964).  Which is closed.,  Reopen this please. It's just silly that the results window can't be on another monitor.
