### ISSUE TITLE
The export buttons disappeared from the query results (Mac)

### ISSUE THREAD

**Issue by thejokenott** [microsoft/azuredatastudio#17075]
Issue Type: <b>Bug</b>

1) Select File > New Query
2) Write your favorite SELECT statement
3) Execute the statement
4) There should be Export to Excel and Export to CSV buttons next to the query results, as they used to be before the 1.32.0 release. These are nowhere to find now.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:09:20.282Z)
OS version: Darwin x64 20.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|29, 20, 20|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@thejokenott I see the export buttons next to the result set on 1.32.0 and the latest insider build.  Do you see any errors in the "Help->Developer Tools" Console or other steps that would help repro this issue?  Thanks!

Here's what I'm seeing with the above repro

![image](https://user-images.githubusercontent.com/599935/133319949-618d34bf-1f6b-4ab6-9070-efe3f4b7342e.png)

**Comment by thejokenott** [comment]
Toggling the Developer tools gives a bunch of "DevTools failed to load SourceMap: Could not load content for..." warnings, but that's it. 
<img width="327" alt="image" src="https://user-images.githubusercontent.com/37587716/133323449-6c660202-cc72-447b-92fd-6807f15bd06b.png">
Same problem with different color settings. Also I remember the result set using a fixed width font, which is clearly not happening here.

**Comment by kburtram** [comment]
@thejokenott in the screenshot you also don't have the filtering drop-down arrows on the column headers.  Often when we see things "totally broken" there is some type of problem with the installation.  

Have you tried uninstalling and reinstalling to correct any potential acquisition issues?  If that did work you could try removing `/User/[USERNAME]/Library/Application Support/azuredatastudio`, which removing cached application state.  That would revert back to "1st launch" setup.  This can workaround some bugs.

**Comment by thejokenott** [comment]
Removing the `azuredatastudio` directory solved the issue. Thank you!
