### ISSUE TITLE
Notebook, Out-Gridview in .NET (PowerShell) kernel fails

### ISSUE THREAD

**Issue by claudio-salvio** [microsoft/azuredatastudio#17105]
Hello

When I try to use **Out-Gridview** in a **code cell** of a **notebook** with **.NET (PowerShell) kernel** it **fails** with the following error:
![image](https://user-images.githubusercontent.com/66575834/133913953-8adc0191-e1c1-41e2-ba3e-c02eee5846b3.png)

Is there any way to use **Out-Gridview** in a code cell when the notebook kernel is **.NET (PowerShell)**?
I use **Out-GridView** a lot as a selection tool when the kernel is **PowerShell** and would like to be able to do it also with **.NET (PowerShell)**.
Not being able to do it is something that stops me from adopting the latter.

In case it is not currently possible, will you be able to advise me where to make the request to make it possible?

Regards

**Comment by silvinapose** [comment]
I think it is important to fix this bug.
Out-GridView is a fundamental element to interactivity when using PowerShell in ADS.

**Comment by VasuBhog** [comment]
Hi @claudio-salvio, this seems to be an existing issue with the .Net Interactive PowerShell as @sadukie mentioned as well. Please file an issue there in order to help track the progress with this issue. 
https://github.com/dotnet/interactive/

**Comment by claudio-salvio** [comment]
> Hi @claudio-salvio, this seems to be an existing issue with the .Net Interactive PowerShell as @sadukie mentioned as well. Please file an issue there in order to help track the progress with this issue. https://github.com/dotnet/interactive/

✔️Done.
Thank you.

**Comment by corivera** [comment]
Closing this issue since .NET Interactive support has been removed from ADS.
