### ISSUE TITLE
Notebook not able to run sql query after AAD token gets expired

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#17104]
Steps to Reproduce:

1. Create a notebook from a server connection with **AAD-MFA** auth.
2. Wait for some time (AAD access token expires in 1 hour by default) then run a sql query that requires connection.
3. Result will say `Query was canceled by user` although the cancel button is not pressed.

![Screen Shot 2021-09-17 at 14 50 53](https://user-images.githubusercontent.com/21186993/133857410-2fd6259e-c844-41f7-a994-edcaa782e337.png)

**Comment by chlafreniere** [comment]
@caohai I've added this to the October milestone since you have a PR out that references this issue. Feel free to move this issue out if it doesn't get totally fixed by this issue.

**Comment by caohai** [comment]
@chlafreniere Sure, I haven't sent the PR yet but it should be done shortly. (The link that references this issue is actually a mega issue for AAD token instead of a PR.)
