### ISSUE TITLE
Insertion of Null into existing record

### ISSUE THREAD

**Issue by manattweb** [microsoft/azuredatastudio#1710]
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce: N/A

How can you insert a NULL value into an existing record? In SSMS, it's CTRL+0. Is it to just type in the word NULL?

**Comment by kburtram** [comment]
@manattweb if you type the string `NULL` into a field's edit box this should save the DB value `NULL` into the field.  This has the "corner-case" that you can't enter the string value `NULL` into a field using the Data Editor.

I like the idea of having a keyboard shortcut to insert this value to make it more explicit.

**Comment by manattweb** [comment]
Thanks for the info. I noticed a keyboard editor in the tool. Can I define my own key command for doing this?

**Comment by kburtram** [comment]
Closing out older issues.  I don't think there is way to automate the inserting of the text `NULL` unfortunately.  Thanks for filing this issue!
