### ISSUE TITLE
Open file button after Save as Excel doesn't do anything

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#17132]
Steps to Reproduce:

1. Run a query and save the results as Excel.
2. Once the file is saved, you get a pop up with a button `Open file` for the saved excel file.
3. Click Open file button

Expected- The file opens
Actual - Nothing happens

**Comment by alanrenmsft** [comment]
you are using mac, right?

**Comment by abist** [comment]
@alanrenmsft Yes

**Comment by Charles-Gagnon** [comment]
@abist Does this repro for you anymore? Is it possibly because of https://github.com/microsoft/azuredatastudio/issues/17618? Try with the latest dev/insiders and see if you still see the same behavior with my fix.

**Comment by abist** [comment]
@Charles-Gagnon This seems to be fixed in latest insiders.
