### ISSUE TITLE
Azure SQL Migration Extension: The access token for selected account is no longer valid

### ISSUE THREAD

**Issue by wgbartley** [microsoft/azuredatastudio#17145]
Issue Type: <b>Bug</b>

Immediately after linking a user account, I receive the error:

The access token for selected account 'Garrett Bartley - user@host.com (XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX)' is no longer valid. Select 'Link Account' and refresh the account, or select a different account.

I get the same error no matter which AD tenant I select from the dropdown.

Extension version: 0.1.8
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 3800X 8-Core Processor              (16 x 3900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (10.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aasimkhan30** [comment]
Moving this issue out of December as there have been some fixes made to the extension to better handle it.

**Comment by raymondtruong** [comment]
Access tokens expire from time to time, and when they do, we prompt the user to re-link their account in the wizard. Additionally, we've made several changes over the last year to improve the experience here. If this issue still persists, feel free to reopen the issue.
