### ISSUE TITLE
add sql binding - check if file is open/dirty before editing on disk

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#17156]
Azure SQL function bindings item

I've managed to open a function file, make some changes - run the "add sql binding" command - realize the changes aren't appearing in the editor because I've forgotten yet again to save before running the command.  If I save now I will get a conflict notice - I can overwrite with my changes and run the add sql binding command again.

It would be extra special if the command could save me from myself.

**Comment by alanrenmsft** [comment]
@udeeshagautam @kisantia is this the right area path?

**Comment by kisantia** [comment]
yup this is the right one. Thanks!

**Comment by udeeshagautam** [comment]
@kisantia assigning to you as you are looking intoit already.
