### ISSUE TITLE
Kusto extension deletes file contents on save when editor: format on save enabled

### ISSUE THREAD

**Issue by alexkyllo** [microsoft/azuredatastudio#17159]
Issue Type: <b>Bug</b>

Steps to Reproduce:

1. Install the Kusto extension
2. In Settings, tick "Editor: Format on Save"
3. Open an existing .kql file and edit it
4. Save the file, and the file contents will be deleted

Extension version: 0.5.4
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700 CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (7.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alexkyllo** [comment]
This also happens when I do Command Pallete > Format Document on a Kusto query in a .kql file, without saving. It deletes the entire contents of the file buffer.

**Comment by chlafreniere** [comment]
@JustinMDotNet would you be the right person to look at this?

**Comment by MsSQLGirl** [comment]
@JustinMDotNet : FYI - I can repro both.

**Comment by JustinMDotNet** [comment]
Pull Request created to fix this https://github.com/microsoft/sqltoolsservice/pull/1251/files

**Comment by JustinMDotNet** [comment]
This will release with the October release.

**Comment by alexkyllo** [comment]
This issue still happens--just reproduced it on the following versions:

Version: 1.35.1 (user setup)
Commit: fab63efd307e54c063c8af03474bbb5d77f5fd11
Date: 2022-03-15T18:03:38.261Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Kusto (KQL) extension version v0.5.4 (preview)
