### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by YankoNik** [microsoft/azuredatastudio#17157]
Issue Type: <b>Bug</b>

Crash 

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (6.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
profiler|Mic|0.11.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@YankoNik could you please provide some more details on the repro steps leading up to the crash and any error messages you may have received?  Unfortunately there isn't currently sufficient details to investigate this issue.  Thanks!
