### ISSUE TITLE
Failed to script "as execute"

### ISSUE THREAD

**Issue by smilieface** [microsoft/azuredatastudio#17167]
Issue Type: <b>Bug</b>

Created a new stored procedure in a database.

Scrolled down to stored procedure, right-click and select "Script as Execute"

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.73GB (41.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
cms|Mic|0.8.0
dacpac|Mic|1.8.0
import|Mic|1.3.1
powershell|ms-|2021.8.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.11.0
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.12.0
sql-prompt|Red|0.2.8

</details>

**Comment by kburtram** [comment]
@smilieface I wasn't able to repro using the steps in the description.  Was there anything "special" about the sproc or is it all sprocs?  Did you receive any errors in the "Help->Developer Tools" Console output or otherwise?  Thanks!
