### ISSUE TITLE
on the Create New Firewall Rule dialog, need to show more details on tenant drop-down to differentiate

### ISSUE THREAD

**Issue by burtonrodman** [microsoft/azuredatastudio#17162]
on the Create New Firewall Rule dialog (after attempting to connect to an SQL Azure db without a valid rule)
in the "Azure tenant" drop-down, there are many entries that just say "Default Directory".

This is not enough information to make an informed choice.  Please include the tenant directory uri as is the pattern on many other applications that have this input.  ex:  Default Directory (mycompany.onmicrosoft.com).

![image](https://user-images.githubusercontent.com/7658657/134735535-9b870888-3dac-4278-8718-70a728f4bf10.png)

**Comment by burtonrodman** [comment]
this an improvement but why not show the more information directory uri (my company.on microsoft.com) instead of a guid that i have to go look up?

**Comment by cheenamalhotra** [comment]
The tenant URI isn't available in the tenant information in frontend, and would require big changes to make that happen. I'll keep an eye out for that opportunity, but wanted to unblock this case with some fix by appending GUID that's still differentiable.

**Comment by burtonrodman** [comment]
fair enough.  thanks!!
