### ISSUE TITLE
Add support for APS/PDW

### ISSUE THREAD

**Issue by dudilevi1** [microsoft/azuredatastudio#1717]
Hi, there is an extension for SQL DW, i'm sure that with small modification it can support APS appliance.

Thanks

**Comment by Joatmon27** [comment]
Any updates on this?

**Comment by cheenamalhotra** [comment]
We don't have an extension for SQL DW/Synapse, as MSSQL supports connectivity. 
Is there a specific requirement from that front?

Would recommend trying out [latest insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build and letting us know specific asks and any gaps.

**Comment by cheenamalhotra** [comment]
Closing as inactive.
