### ISSUE TITLE
Hard coded port :80 in ads code

### ISSUE THREAD

**Issue by gupta1** [microsoft/azuredatastudio#17172]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:
Created a github issue as well.
basically something in ADS is hard coding port :80 to the end of the URL, so the proxy is forcing everything to be https://, but because of the hard coded :80 somewhere the communication is being lost

![image](https://user-images.githubusercontent.com/11342435/134966158-73746f24-d407-4b66-8fdd-0b09c926af58.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
@gupta1 ADS Web runs on port 8000 and doesn't open port 80.  Can you provide additional details on how to repro this issue?  When I run ADS Web in my test env this issue does not occur.

**Comment by lewis-sanchez** [comment]
@gupta1, ADS doesn't open port 80 as shown here while monitoring traffic for ADS Web:
![image](https://user-images.githubusercontent.com/87730006/135198307-1fb98709-62f5-4041-8f81-12111a6553f5.png)


It does however run on port 8000 and I can see the resources coming through the wire as GET requests
![image](https://user-images.githubusercontent.com/87730006/135198405-5188b9d9-d399-4e0b-a0a1-ae92deecd458.png)
