### ISSUE TITLE
Error when I connect

### ISSUE THREAD

**Issue by Avaruz** [microsoft/azuredatastudio#17191]
Issue Type: <b>Error</b>

When I try to connect to an server with the name instead of ip address i get an error.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

**Comment by kburtram** [comment]
@Avaruz the client driver will try to use DNS to convert a server name into an IP address before communicating to the server.  Have you confirmed that the server name is correctly being resolved on the machine you're connecting from?  You can run `nslookup [SERVERNAME]` from the CLI to confirm that DNS resolution is working as expected.

**Comment by Avaruz** [comment]
The error doens't happen again.
