### ISSUE TITLE
Support for shell/command-line sql comparison

### ISSUE THREAD

**Issue by Nefcanto** [microsoft/azuredatastudio#17205]
**Is your feature request related to a problem? Please describe.**
Comparing databases using UI means that we can't automate SQL Comparison for our CI/CD pipelines. Right now I want to have the ability to drop the pipeline if databases are not identical and no suitable migration script is provided.
But I can't.

**Describe the solution or feature you'd like**
The solution is to support a command-line interface. A pseudo-code would be:

```
azure-data-studio-sql-compare -sourceConnectionString="" -targetConnectionString="" -booleanResponse
```
And the response could be true/false, telling us whether databases are identical or different

**Describe alternatives you've considered**
Right now we can't have a fully automated CI/CD pipeline. We manually compare databases and manually monitor quality by push reviews to make sure migrations scripts are provided by developers.

**Additional context**
Azure Data Studio is awesome. And its extensions are even more awesome. SQL Compare is an amazing extension that is truly useful and we use it on a daily basis in all of our projects. Its CLI would make fully automated CI/CD pipelines possible.

**Comment by Charles-Gagnon** [comment]
@udeeshagautam @kisantia @Benjin FYI

@Nefcanto Are you referring to the schema compare extension or something else?

**Comment by kisantia** [comment]
@Nefcanto sounds like the sqlpackage [Deploy Report](https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-deploy-drift-report?view=sql-server-ver15) action might be able to do what you're looking for. Sqlpackage is a command line tool and the deploy report be an xml file with any differences between the source and target.

**Comment by Nefcanto** [comment]
@Charles-Gagnon , yes, I'm referring to the schema compare extension with this id:

`microsoft.schema-compare`

**Comment by Nefcanto** [comment]
@kisantia, thank you for that reference.

Is it a cross-platform utility? We're using Linux (Ubuntu and Debian).

**Comment by kisantia** [comment]
@Nefcanto yup sqlpackage is cross-platform. Here's a link with the downloads for the different platforms: https://docs.microsoft.com/en-us/sql/tools/sqlpackage/sqlpackage-download?view=sql-server-ver15
