### ISSUE TITLE
get older version of Azure Arc

### ISSUE THREAD

**Issue by AnyiYang** [microsoft/azuredatastudio#17202]
Issue Type: <b>Bug</b>

My customer could not use ADS to do backup and resotre on Postgres. After checking, in the latest version of Azure Arc extension (0.9.6), Postgres backup/restore was removed due to the plan on re-designing APIs. The APIs will be introduced in the future when they are ready. So customer wants to use previous version of Azure Arc extension.

In extension of ADS, we could only find the latest version of Azure Arc extension (0.9.6). Even when I select "Install Another Version...", only the latest version can be found. Is there any way to install previous version of Azure Arc extension? How can we find previous version of .vsix file for Azure Arc extension?

Extension version: 0.9.6
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
We don't officially support multiple versions of an extension in our marketplace. And older versions of extensions are also unsupported and could result in various issues. 

If you are ok with all this and still want to give it a shot you can get older versions by changing the version number in the URL and downloading the VSIX manually : https://sqlopsextensions.blob.core.windows.net/extensions/arc/arc-0.9.6.vsix. Just know that this is unsupported so any issues that arise from this are something we won't be able to help with.

**Comment by AnyiYang** [comment]
Thanks Charles for your update
