### ISSUE TITLE
Inherit database connections from current context.

### ISSUE THREAD

**Issue by satya-spektrasystems** [microsoft/azuredatastudio#17213]
Think that I am connected to a database and writing a storedprocedure. Now I want to write a helper function so I clicked ctrl+N, creates a new unsaved file. This unsaved file should inherit the database connection like SSMS. But in Azure data studio I have to select the database again from the saved list. This is unnecessary and taking a lot of time.

**Comment by Charles-Gagnon** [comment]
What version are you using? We have that same functionality and it appears to be working fine in my testing with the latest version.

If you could get the logs as described below that may help determine if there's something else going on that is causing it to fail.

**Comment by cheenamalhotra** [comment]
Hi @satya-spektrasystems 

Do you have any update to question from @Charles-Gagnon? 
Please let us know if this is still reproducible. Thanks!

**Comment by cssuh** [comment]
Closing as no logs were provided.
