### ISSUE TITLE
Unable to install python kernel 

### ISSUE THREAD

**Issue by PinkysBinkys** [microsoft/azuredatastudio#17217]
Issue Type: <b>Bug</b>

1. Open Notebook
2. Prompted to install Python kernel
3. Clicked through to install taking all defaults
4. Failed with the following error: 

ERROR: Failed building wheel for argon2-cffi
ERROR: Could not build wheels for argon2-cffi which use PEP 517 and cannot be installed directly
WARNING: You are using pip version 19.2.3, however version 21.2.4 is available.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz (8 x 4200)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.79GB (13.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by corivera** [comment]
No, that's a different error message than the one I was seeing. This looks like a problem with the pip install process.

**Comment by corivera** [comment]
Closing due to no repro.
