### ISSUE TITLE
sqlproj sql binding create connection string in app setting but publish to docker doesn't update it

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17256]
- Azure Data Studio Version:
- OS Version:

we need a consistent behavior when working with sql proj inside the workspace with azure functions. When creating a sql proj with Azure function and then use sql binding, connection string is created in the  the local setting but when publishing to docker we don't update the connection string. We should store the name of the connection string env variable somewhere so that we don't ask for the name again when we publish to docker. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
closing for now since we aren't focusing in this area right now
