### ISSUE TITLE
 Build Docker Image from VS Code Command/Shortcut

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#17259]
It is not possible for SQL Project to build the image via the command "Docker Images: Build Image" or right-clicking the SQL Project Dockerfile and going through the steps as it will result in an error: ` => ERROR [3/4] COPY .mssql/commands/ /opt/commands` since the user has to pass in additional env variables to build the image properly.

**Comment by llali** [comment]
@VasuBhog  would you please add more details for this item?
