### ISSUE TITLE
After ADS update, the previously pinned tabs are no longer pinned

### ISSUE THREAD

**Issue by BurstX** [microsoft/azuredatastudio#17280]
Issue Type: <b>Bug</b>

Pin a few tabs (with T-SQL code in them) in an ADS instance you have, then upgrade ADS to the next version. The pinned tabs are no longer pinned after the update.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (13.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
Closing as inactive issue.
