### ISSUE TITLE
Extensibility: Dialog alignment

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#1733]
I recently spoke to Smitha, and she suggested a small change in the dialog UI. The Tabs aren't aligned properly with the components in the dialog. She suggested that they all be aligned. I've added a screenshot to make it as clear as possible - 

![untitled](https://user-images.githubusercontent.com/6411451/41930884-40eb088c-7931-11e8-9ad0-b57300ad56ff.png)

**Comment by kburtram** [comment]
Closing older extensibility API issues.  Please open a bug against the SQL Agent dialog if this is still a problem.
