### ISSUE TITLE
DMS - Typo 

### ISSUE THREAD

**Issue by gabor-rozsa** [microsoft/azuredatastudio#17337]
Issue Type: <b>Bug</b>

At DMS specification in the "Setup integration runtime" part:

"..from onpremises fie share to Azure."

correct:
"..from onpremises file share to Azure."

Extension version: 0.1.8
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.79GB (42.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
@brian-harris FYI

@gabor-rozsa Could you include a screenshot of the string in question?
