### ISSUE TITLE
Migration failed with internal error while restoring database

### ISSUE THREAD

**Issue by ingebeumer** [microsoft/azuredatastudio#17332]
Issue Type: <b>Bug</b>

Hi all,
Using Azure SQL Migration extension in Azure Data Studio for a migration of WideWorldImportersDW from local SQL Server 2019 to Azure SQL Managed Instance I get a message: 
"Migration for Database 'WideWorldImportersDW_offline_fromADS' failed with error 'An internal error occurred while restoring the database. Please retry the restore request later.'."
Retrying restore later and even the next day gave the same error. 
 
Manual restore from SSMS had a more meaningful message indicating the issue:
'Msg 41915, Level 16, State 1, Line 13
Memory-optimized filegroup must be empty in order to be restored on General Purpose tier of SQL Database Managed Instance.
Msg 3013, Level 16, State 1, Line 13
RESTORE DATABASE is terminating abnormally'
 
After taking the easy route and scaling my Managed instance from General Purpose service tier to Business Critical, the migration was successful, ending in "migrationState": "Succeeded".
 
Please review if the message in Azure SQL Migration extension is eligible for improvement to give a more meaningful message leading to easier troubleshooting.
 
Thank you and kind regards, Inge

Extension version: 0.1.8
Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.22473

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (4.33GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by raymondtruong** [comment]
Our service has been updated to improve error messaging and now includes a troubleshooting link to further assist with configuration issues. If this issue still persists, feel free to reopen the issue.
