### ISSUE TITLE
Sign in to Azure is stuck when using Proxy

### ISSUE THREAD

**Issue by preethamrajk** [microsoft/azuredatastudio#17356]
Issue Type: <b>Bug</b>

When I want to connect my Azure AD account, I am stuck after I enter my credentials and login on Azure Login page and I don't get a successful callback to Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042
![image](https://user-images.githubusercontent.com/16648593/137226357-b3f1e2f9-06ec-449b-bec3-fdb4279a7cf7.png)
![image](https://user-images.githubusercontent.com/16648593/137226209-5e4dcb0f-7940-442d-abb0-0216782b2a9e.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.11.0
sql-database-projects|Mic|0.12.0

</details>

**Comment by philipphomberger** [comment]
I have the same Issue at 2 Terminal Servers (Windows Server 2019).  At the moment I have no Idea why. Because I have a lot of other Servers there this problem is not exist. I have try reinstall the Application but that not change anything.

**Comment by philipphomberger** [comment]
**Here some more input from my side:** 
After login to Azure in the Browser:
![Bildschirmfoto 2022-01-20 um 08 09 57](https://user-images.githubusercontent.com/13222043/150292743-e37e2fed-18d5-41a8-9ef8-904b950191a0.png)
I get a loop. 
Than I open the calback link in the Developer Tools.
![Bildschirmfoto 2022-01-20 um 08 17 49](https://user-images.githubusercontent.com/13222043/150293039-ab7fb4c7-49a9-4563-9b17-f565d057cb2b.png)
The site load in a loop for some minutes. 
Than the Connection get close.
![Bildschirmfoto 2022-01-20 um 08 18 45](https://user-images.githubusercontent.com/13222043/150293137-56773ea3-b6f8-4037-ac5a-4a77fe14ef23.png)
And in the Application I can see that error.
![Bildschirmfoto 2022-01-20 um 08 19 23](https://user-images.githubusercontent.com/13222043/150293180-2386d230-d11b-4fef-9efd-020f68394be0.png)
And this in the log.
![Bildschirmfoto 2022-01-20 um 08 24 39](https://user-images.githubusercontent.com/13222043/150293223-f8537a91-d8a9-4000-bc12-512e225a145f.png)

**Comment by preethamrajk** [comment]
@cssuh @kburtram 

Any update on this?

This has been in the backlog for a year.

**Comment by cssuh** [comment]
Hi @preethamrajk, we are working on this now, and plan to have it in our October release.

**Comment by preethamrajk** [comment]
Still having the same issue @cssuh.

Don't think this has been fixed in the latest release from yesterday.

``` 
Version: 1.40.0 (system setup)
Commit: 3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:05.361Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by cssuh** [comment]
Hi @preethamrajk, can you please share the error you're seeing?

**Comment by preethamrajk** [comment]
Adding logs from 

.....\azuredatastudio\logs\20221117T105753\exthost1\output_logging_20221117T105758

```
[Verbose]: Starting login - []
[Verbose]: Fetching token - []
[Error]: Login failed - []
[Error]: Error: socket hang up - []

**Comment by cssuh** [comment]
@preethamrajk Can you also please share your proxy settings?

**Comment by preethamrajk** [comment]
Here it is 
```
C:\WINDOWS\system32>SET | findstr "PROXY"
HTTPS_PROXY=http://127.0.0.1:9000
HTTP_PROXY=http://127.0.0.1:9000
NO_PROXY=localhost,127.0.0.0/8,*****.com.au,*****.net.au,*.australiaeast.azmk8s.io,*.australiasoutheast.azmk8s.io, login.docker.com

**Comment by cssuh** [comment]
You also need to whitelist the following URLs:

https://management.azure.com 
https://login.microsoftonline.com 

you may need to whitelist additional URLs but this can sometimes vary on a case-by-case basis - in order to verify you aren’t blocking any URLs from going through, go to Help > Toggle Developer Tools and select the Network tab.  Here you will see any URLs that are getting blocked that you may need to whitelist to successfully add your account.

**Comment by preethamrajk** [comment]
Hi @cssuh 

Those URLs are already whitelisted by the Network guys. As you can imagine, the whole corp network would be crippled without access to these URLs.. 😃
