### ISSUE TITLE
Notebook kernel list: not showing kernels in kernelspec for new notebooks

### ISSUE THREAD

**Issue by sadukie** [microsoft/azuredatastudio#17351]
Issue Type: <b>Bug</b>

## Problem

When creating a new notebook in Azure Data Studio, the kernels list seems hard-coded rather than pulling from the Jupyter kernelspec list.

## Reproduction Steps

1. Have more than just the default kernels installed in the Jupyter kernelspec.

- I blogged about getting the R kernel installed here: [Data Adventurer: Getting an R Jupyter Kernel in Azure Data Studio](https://data-adventurer.com/2021/10/13/getting-an-r-jupyter-kernel-in-azure-data-studio/)

2. Have Jupyter installed. (I already had this installed because I wasn't seeing anything in the Settings for Jupyter within Azure Data Studio.)
3. Check the Jupyter kernelspec to ensure other kernels are installed by running this in the terminal:
`jupyter kernelspec list`
4. Open Azure Data Studio.
5. Create a new notebook via the **File** menu, **New Notebook** option.
6. Check the Kernel dropdown and notice it is the default list - SQL, PySpark, Spark | Scala, Spark | R, Python 3, and PowerShell.
Not all kernels in the Jupyter kernelspec list appear.

## System Information

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (7.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

## Workaround

1. Change to a different kernel.  Notice the "Changing kernel..." text.
2. Once the kernel is changed, check the Kernel dropdown.  Notice that the kernels in the kernelspec list appear.

- I blogged about my workaround at [Data Adventurer: Buggy Kernels List in Azure](https://data-adventurer.com/2021/10/13/buggy-kernels-list-in-azure-data-studio/).

## Possible Solution

Have the notebook pull its list of kernels from the kernelspec list from the beginning.

**Comment by VasuBhog** [comment]
Hi @sadukie, we have been tracking this work internally and definitely will be working to fix this with the next release in part of the integration with the .Net Interactive Kernels extension.

**Comment by chlafreniere** [comment]
@VasuBhog @corivera has this been fixed?

**Comment by VasuBhog** [comment]
I thought we discussed that this would've been a part of the .Net Interactive work, and as such was not prioritized for my work. I am not sure about @corivera update for this.

**Comment by corivera** [comment]
The .NET Interactive work isn't going to change anything about how we register kernels. We populate that dropdown based on the standardKernels that are registered in the extension manifest. Retrieving kernels only jupyter knows about is a separate issue.

**Comment by chlafreniere** [comment]
This won't make this upcoming release and requires some more design discussions. Moving this out.

**Comment by Charles-Gagnon** [comment]
@chlafreniere I'm moving this into backlog until we can go through the design for this
