### ISSUE TITLE
User Management makes this tool completely unusable

### ISSUE THREAD

**Issue by danabrash** [microsoft/azuredatastudio#17352]
Issue Type: <b>Bug</b>

3 times now, 3 separate systems, 3 separate installs.  Azure creds.

Credentials management takes my credentials. logs me in, and when I try to connect to get my list or connect to a server it returns me to the user selection pane.

There is no options, context menu, nothing available on my account.

Removing and re-adding the account doesn't help.

Azure Data Studio version: azuredatastudio 1.30.0 (59c4b8e90cf2d3a24bed72623197f10f8d090fdc, 2021-06-16T19:04:08.858Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (4 x 2995)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|20.00GB (9.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
@danabrash 

Checking in, do you still observe any issue with Azure connection? 
Could you please try [latest insider build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know?

**Comment by cheenamalhotra** [comment]
Closing as issue is no longer reproducible.
