### ISSUE TITLE
Cannot connect to the Extensions Marketplace

### ISSUE THREAD

**Issue by aakawero** [microsoft/azuredatastudio#17362]
Issue Type: <b>Bug</b>

It has been a while since the message "We cannot connect to the Extensions Marketplace at this time, please try again later" has been showing up.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19043

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2133 CPU @ 3.60GHz (12 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.66GB (42.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|Mic|0.5.4

</details>

**Comment by aakawero** [comment]
In case it helps. this is the error message shown in ADS
***@***.***

I've confirmed with other people and they also have same error message

**Comment by alanrenmsft** [comment]
@aakawero were you trying to share an image? you have to open the github webpage to attach images. also are you able to access the link that Karl shared?

**Comment by aakawero** [comment]
@alanrenmsft here is the image
![image](https://user-images.githubusercontent.com/92546451/138361784-cc5f5cb2-e553-4815-93aa-8a3fac1c6eee.png)

Also link that @kburtram shared shows me this
![image](https://user-images.githubusercontent.com/92546451/138362255-9e74ba64-3463-4a2f-bad4-8f099885e2f2.png)

**Comment by alanrenmsft** [comment]
please reactivate with the error information.
