### ISSUE TITLE
ADS Web new Python install breaks notebook smoke tests

### ISSUE THREAD

**Issue by lewis-sanchez** [microsoft/azuredatastudio#17367]
- Azure Data Studio Version: 1.33.0-insider
- OS Version: Windows 10.0.19043

The smoke tests for ADS Web are timing out because Python notebooks aren't being configured correctly and prevents them from opening correctly.

Steps to Reproduce:

1. Launch ADS Web
2. Create a new notebook
3. Change the Kernel to Python3
4. In the configure python runtime blade, select "New Python Installation".
![image](https://user-images.githubusercontent.com/87730006/137410124-bd420449-e42a-4c6e-a0eb-1d1f8d02b65b.png)
5. Click Next
6. Click Install
7. After the notebook dependencies installation completes. The following error appears and the kernel is set back to SQL:
![image](https://user-images.githubusercontent.com/87730006/137410330-8603056c-39f0-479e-b298-9ee8877a0c84.png)

- Changing the python configuration in ADS Web to use an existing Python installation allows notebooks to work in web mode correctly.
![image](https://user-images.githubusercontent.com/87730006/137410418-cc926b67-5296-43b4-8129-7036b0eb700d.png)
- After reconfiguring Python for notebooks, changing the kernel to Python3 and running any Python statements in a notebook works
![image](https://user-images.githubusercontent.com/87730006/137410587-6698c20b-2aea-4a0d-85dc-cbd12d353104.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chlafreniere** [comment]
@lewis-sanchez how did we end up handling this? Have these tests been turned off, or are these still failing?

**Comment by lewis-sanchez** [comment]
@chlafreniere, they're currently turned off in the web build only because they were failing.

**Comment by chlafreniere** [comment]
Gotcha. Can we close this issue? Or are you keeping it open for tracking (in which case, we should move it out of the milestone)

**Comment by lewis-sanchez** [comment]
@chlafreniere, I was keeping it open for tracking since we would eventually like to have those smoke tests running in the web build pipeline since they would help with ensuring that notebooks are sound in the web build.

**Comment by chlafreniere** [comment]
@lewis-sanchez ok. Any issues if I move it to the February milestone?

**Comment by lewis-sanchez** [comment]
@chlafreniere, no issues.

**Comment by chlafreniere** [comment]
@lewis-sanchez are you still looking into this, or has the test been disabled?

**Comment by lewis-sanchez** [comment]
@chlafreniere, that test has been disabled.

**Comment by chlafreniere** [comment]
@lewis-sanchez do we have any plans to bring back this test soon? Otherwise, I'd like to move it to the backlog to avoid having to punt this every release.

**Comment by lewis-sanchez** [comment]
@chlafreniere, no, I don't know when that test will be back.

Also, to clarify that test is only disabled for the web build and not for the other builds.

**Comment by kburtram** [comment]
Closing older issues.  We're no longer supporting ADS webmode.
