### ISSUE TITLE
Split Cell Icon Should be last action icon

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#17381]
Version: 1.33.0-insider
Commit: 7f92d8bc19c6269ad793f71b819667f7956c1638
Date: 2021-10-18T05:32:35.776Z (14 hrs ago)
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0

![Screen Shot 2021-10-18 at 10 41 33 AM](https://user-images.githubusercontent.com/23587151/137800507-f9deb5ac-4ffc-4ec3-a3a7-7d7e31f96eaa.png)

After discussion in Scrum. The Split Icon should be the last icon prior to the more actions menu.

**Comment by chlafreniere** [comment]
@VasuBhog this needs to go into the release branch. Please don't close approved issues during ask mode unless they're already in a release branch.
