### ISSUE TITLE
Project dashboard should refresh after Build and Publish buttons are clicked

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17426]
Dashboard shows accurate information when loaded and when refreshed, but if you build or publish using the dashboard buttons, the tables don't automatically update when the actions have completed.  Simple fix: refresh the tables automatically after the invoked actions have completed.

**Comment by udeeshagautam** [comment]
Closing with low-pri for now to clean up. We can pick these if taking changes in related features
