### ISSUE TITLE
Unable to Create Multiple Saved Connections to Same Target

### ISSUE THREAD

**Issue by nativeTexanATX** [microsoft/azuredatastudio#17438]
- Azure Data Studio Version: 1.33.0-insider
- OS Version: Darwin x64 10.6.0

When saving connections with different properties, for example one with ApplicationIntent = ReadWrite and another with ReadOnly, Azure Data Studio does not handle settings.json correctly or consistently.

For the sake of argument, I’m starting with Azure Data Studio in a pristine environment. The screenshots below show Azure Data Studio on the left, and Visual Studio Code on the right. I’ve opened the Azure Data Studio settings.json file in Visual Studio Code to show step-by-step what happens. (The screenshots are clipped from a screen recording on macOS using the Screenshot app.)

Steps to Reproduce:

1. Open Azure Data Studio

<img width="1647" alt="Screen Shot 2021-10-21 at 13 03 26" src="https://user-images.githubusercontent.com/56049054/138344901-1fede166-602b-4bc8-b38f-f22e87dae6d0.png">

2. From the “Connections” menu, click “Add Connection” and fill out the properties for the connection.

<img width="433" alt="Screen Shot 2021-10-21 at 13 09 14" src="https://user-images.githubusercontent.com/56049054/138345024-8dda3fc5-7638-466f-a3c4-1347d2bbff52.png">

For the “Name”, I used the format “DatabaseName (ServerName) (ApplicationIntent)”.

3. Click on “Advanced” and fill out the additional properties.

<img width="433" alt="Screen Shot 2021-10-21 at 13 09 32" src="https://user-images.githubusercontent.com/56049054/138345329-e857cccf-a9cf-4ddf-ae68-d4ac076e6b4b.png">

4. Click “OK” and then “Connect” on the previous window.

In this case, the configuration is saved, written to settings.json, and the connection is established.

<img width="1675" alt="Screen Shot 2021-10-21 at 13 14 35" src="https://user-images.githubusercontent.com/56049054/138345417-2252c33b-7bd5-49a0-b81f-55eda52f5951.png">

5. Repeat Steps 1 to 4, using the same target, but this time change the ApplicationIntent to ReadOnly and change the “Name” to ReadOnly.

<img width="424" alt="Screen Shot 2021-10-21 at 13 26 39" src="https://user-images.githubusercontent.com/56049054/138345544-16235ca6-b026-4d4b-8fb3-cf14f2d706b2.png">

<img width="424" alt="Screen Shot 2021-10-21 at 13 26 55" src="https://user-images.githubusercontent.com/56049054/138345557-a7ba82f1-a954-445f-8bc0-89f847ae8e37.png">

6. Click “OK” on “Advanced Properties”, then click “Connect”. In this case, the existing connection is re-established and the configuration in settings.json is overwritten.

<img width="1648" alt="Screen Shot 2021-10-21 at 13 30 49" src="https://user-images.githubusercontent.com/56049054/138345667-f5df0e77-35d4-4ce6-b1bc-9d60f6ef30d1.png">

At this point, I decided to manually copy the configuration in settings.json and create two separate entries. I had to restart Azure Data Studio, but when the application first starts up, the configuration is displayed correctly.

NOTE: One thing I did for safety was change the “Id” so that each connection had a different GUID.

![Untitled](https://user-images.githubusercontent.com/56049054/138345954-634c99c0-75f2-4d5a-bf7a-8c8be890b74a.png)

After updating the configuration and restarting Azure Data Studio:

<img width="1648" alt="Screen Shot 2021-10-21 at 13 41 20" src="https://user-images.githubusercontent.com/56049054/138345833-abc5f3b9-f205-427f-acdc-bb5da673c768.png">

7. With Azure Data Studio restarted, and the configuration loaded successfully and correctly, expand the node of one connection.

<img width="337" alt="Screen Shot 2021-10-21 at 14 15 40" src="https://user-images.githubusercontent.com/56049054/138346160-05f9a534-f69a-4fff-8a94-a6f728b27a01.png">

First oddity: Both connections (though different) show the green “Connected” icon.

Second oddity: Attempting to expand the second node results in a continuous spinning icon, and the connection node never expands.

<img width="337" alt="Screen Shot 2021-10-21 at 14 17 03" src="https://user-images.githubusercontent.com/56049054/138346227-20a2e7ab-5595-4788-9d96-6191f97d140f.png">

Third oddity: If you attempt to expand the second node again, the configuration is overwritten.

<img width="1556" alt="Screen Shot 2021-10-21 at 14 20 13" src="https://user-images.githubusercontent.com/56049054/138346464-00db1835-b6a1-46b5-b45d-0e846a27e05e.png">

Azure Data Studio appears to be using the actual target database name when writing and loading the configuration, but it appears to be inconsistently handled. It should use the Connection Id instead. There are numerous cases for having multiple saved connections to the same target (especially when dealing with an AG and ApplicationIntent).

Does this issue occur when all extensions are disabled?: Yes

**Comment by cssuh** [comment]
Thank you for your detailed issue submission, this is definitely interesting and something we will take a look at for the next release. Does this happen for connections made with SQL Login as well (not just AAD connections)?

**Comment by nativeTexanATX** [comment]
> Thank you for your detailed issue submission, this is definitely interesting and something we will take a look at for the next release. Does this happen for connections made with SQL Login as well (not just AAD connections)?

(_I apologize for the delay; wasn't paying attention throughout the holidays. Hope your new year is off to a good start!_)

To answer your question, it happens for **each of** SQL Login and AAD, but does not overlap on the authentication type.

For example, I had a connection ("ConnectionA") defined as AAD.
1) I created a new connection ("ConnectionB") using ConnectionA as a base, but changed the authentication type to "SqlLogin" with "Application Intent" set to "ReadWrite".
2) Attempted to create a new connection ("ConnectionC") using ConnectionB except using "ReadOnly" application intent; the SQL Login connection in the tree was overwritten, but the AAD connection remained untouched.

So, it seems I can create an AAD "ReadWrite" application intent connection and a SqlLogin "ReadOnly"application intent connection. Which is a good workaround, however, we do have some Azure databases that only allow AAD and do not accept SQL Login. ("Login failed for user ... Reason: Azure Active Directory only authentication is enabled.")

Hope that helps!

**Comment by cheenamalhotra** [comment]
_We're almost ready, moving milestone to May to add additional time to test with the insiders build._

**Comment by cheenamalhotra** [comment]
Support is now available in latest insiders with PR https://github.com/microsoft/azuredatastudio/pull/22735, closing as resolved.
