### ISSUE TITLE
Tries to run a notebook everytime I start azuredatastudio

### ISSUE THREAD

**Issue by LanceHMCH** [microsoft/azuredatastudio#17433]
Issue Type: <b>Bug</b>

1.Run the notebook DynamicBPCheck until crashes
2. Restart azuredatastudio  It tries to open the notebook.  The windows times out and I can close it.  

If I want to use azuredatastudio I must open another window while waiting for this window running the failed notebook to timeout.  If I do not I can't open a new window that does not try to run the notebook that crashed.

It happens with the extensions disabled or enabled.

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:08:28.086Z)
OS version: Windows_NT x64 10.0.19042

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.83GB (20.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0

</details>

**Comment by VasuBhog** [comment]
Hi @LanceHMCH, can you provide the DynamicBPCheck notebook so I can repro this specific issue.

**Comment by LanceHMCH** [comment]
I no longer have a copy of this notebook.
I have uninstalled an reinstalled the program and it still tries to run this notebook.
Are there instructions to completely remove azure data studio and it configuration files?
How does a new install still reference that notebook?


Lance Harra
Database Administrator

***@***.***
Education<https://education.mchdata.com/data/education>  |  Healthcare<https://education.mchdata.com/data/healthcare>  |  Government<https://www.mchdata.com/data/government>  |  Religion<https://education.mchdata.com/data/religion>
800-776-6373  |  mchdata.com<https://www.mchdata.com/>
Stay up to date as K-12 policies continue to evolve
with our exclusive COVID-19 Map and Data Resource<https://www.mchdata.com/covid19/schoolclosings>.

**Comment by VasuBhog** [comment]
Hello, if I understand the problem correctly. No matter if you uninstall ADS and reinstall it will open this previous notebook again. This is expected behavior if you do not close the notebook before closing ADS. If you are unable to close the notebook via the traditional method of clicking the x (shown below):
![image](https://user-images.githubusercontent.com/23587151/140100030-1b71e8f0-2703-4471-a3e8-3f2bf0197593.png)
then you can use the command palette (ctrl+shift+p) and search for `View: Close All Editors`. This will ensure that it closes all notebooks/editors that are currently open. 

Once that is done, please close ADS and see if the issue remains.

**Comment by Charles-Gagnon** [comment]
@LanceHMCH Sorry to hear you're having issues, could you try these steps to clear the backup cache? That may be what's causing 

1. Close all instances of ADS
2. Browse to `%appdata%/azuredatastudio`
2. Delete the `Backups` folder (it just contains hot reload backups for editors so shouldn't affect any of your settings)
3. Start up ADS again

Let us know if you're still seeing the Notebook open up at launch after those steps

**Comment by LanceHMCH** [comment]
Thanks,

Deleting the backup directory fixed my problem.

Lance Harra
Database Administrator

***@***.***
Education<https://education.mchdata.com/data/education>  |  Healthcare<https://education.mchdata.com/data/healthcare>  |  Government<https://www.mchdata.com/data/government>  |  Religion<https://education.mchdata.com/data/religion>
800-776-6373  |  mchdata.com<https://www.mchdata.com/>
Stay up to date as K-12 policies continue to evolve
with our exclusive COVID-19 Map and Data Resource<https://www.mchdata.com/covid19/schoolclosings>.

**Comment by Charles-Gagnon** [comment]
Glad to hear it! I'll close this issue now - if you keep running into issues with a particular notebook please let us know and we can investigate!
