### ISSUE TITLE
Export to excel and csv no longer works

### ISSUE THREAD

**Issue by MervAmos** [microsoft/azuredatastudio#1743]
Issue Type: <b>Bug</b>

export to excel and csv no longer works, it just exports garbage text file

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|3.93GB (0.69GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.29.0
profiler|Mic|0.1.1
server-report|Mic|0.1.2
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@MervAmos do you have any additional repro steps?  For example, is there anything "special" about the data being queries, etc.?  I wasn't able to get a local repro using a simple DMV query (e.g. below)

![screen](https://user-images.githubusercontent.com/599935/41983450-fd79ba32-79e2-11e8-8bcb-c534580ddd60.png)

**Comment by MervAmos** [comment]
Hi Karl

Just clicked either excel or csv icon and it only saves as all types *.* 2 days ago it was fine prior to an office update. But now ops studio does not allow save as excel or csv
My connection is to an azure sql dB for this query

Regards

Merv Amos

Elastacloud Ltd | <http://www.elastacloud.com/> www.elastacloud.com| <http://www.twitter.com/elastacloud> @elastacloud
[cid:FA4D07E4181D48B0BB095A837C7BA026]
[cid:EDC04067FDFF466D877EEA11F4150216]

London | 3 Waterhouse Square, 138 Holborn, London EC1N 2SW
Midlands | Merchants Court, 21-23 Castle Gate, Nottingham NG1 7AQ
Spain | Office 40 - 42, Scientific Park Almeria (PITA), Av. de la Innovacion, 15, 04160 Almeria
Company Reg: 07900393<tel:07900393>. VAT Number: 127973874
On 27 Jun 2018, 16:22 +0100, Karl Burtram <notifications@github.com>, wrote:

@MervAmos<https://github.com/MervAmos> do you have any additional repro steps? For example, is there anything "special" about the data being queries, etc.? I wasn't able to get a local repro using a simple DMV query (e.g. below)

[screen]<https://user-images.githubusercontent.com/599935/41983450-fd79ba32-79e2-11e8-8bcb-c534580ddd60.png>

**Comment by MervAmos** [comment]
Karl

Save file as type does not save as excel for me

[cid:image001.png@01D40EAF.D015EAF0]

**Comment by kburtram** [comment]
Closing this out as no repro.  Please let us know if you're still experiencing this issue.  Thanks!
