### ISSUE TITLE
Untitled SQL files reopening as plain text with hot exit

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#17450]
- Azure Data Studio Version: `main`
Steps to Reproduce:

1. Open untitled sql file and modify contents
2. Restart ADS

Expected: Untitled file is reopened as SQL file

Actual: Untitled file is reopened as plain text file (see screenshot for example).

![image](https://user-images.githubusercontent.com/599935/138371181-d00c48b0-3a63-423a-abdf-b9120d7bd7d4.png)

**Comment by Charles-Gagnon** [comment]
Although I should make sure - the issue I'm seeing seems to only really happen when switching between different versions of ADS. So for example if I open ADS stable, create a new query and then exit and open RC1 then I'll see this behavior. 

Does that match your experience or do you see this even when only opening one version of ADS?
