### ISSUE TITLE
No user feedback when refreshing list of databases

### ISSUE THREAD

**Issue by alexangas** [microsoft/azuredatastudio#17458]
- Azure Data Studio Version: 1.32 / 1.33 Insiders
- OS Version: Windows 10 "current"

Steps to Reproduce:

1. In the Connections pane, connect to a server
2. Expand the "Databases" folder and observe the spinner displayed over the folder icon: 
![image](https://user-images.githubusercontent.com/132198/138448527-65db1638-664a-472c-98aa-827cf816218b.png)
3. Wait for list of databases to load
4. Right-click on "Databases" folder and click Refresh. Observe that no spinner is displayed and there is no other obvious user feedback.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
Closing as PR #20621 is merged that should address this issue.
