### ISSUE TITLE
Width of database name to narrow

### ISSUE THREAD

**Issue by alexangas** [microsoft/azuredatastudio#17457]
- Azure Data Studio Version: 1.32 / 1.33 Insiders
- OS Version: Windows 10 "current"

Steps to Reproduce:

1. New Query
2. Connect to server
3. Choose a database that has a name longer than 24 characters, on a server where more than one database has the same prefix of at least half of those characters
4. Run a query and then forget what database you ran it against because the database selector is too narrow 😄 .

![image](https://user-images.githubusercontent.com/132198/138448260-34a7691c-5a0b-48dd-a876-608839f5bd94.png)

I know it is possible to look down the bottom right corner but that's not as convenient as having close to the query you're working on.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
@alexangas the full form of the current context is also available at the application header bar:
![image](https://user-images.githubusercontent.com/13777222/139919209-299f388d-27e4-478e-9445-2047482d31f7.png)

hope this helps.
