### ISSUE TITLE
Bug: Horizontal scroll bar is hidden when 8 or less rows are on the screen

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#1746]
- SQL Operations Studio Version: 0.30.6

Horizontal scroll bar is hidden when 8 or less rows are on the screen:

![HORIZONTAL_BAR_HIDDEN](https://i.imgur.com/rBweonA.png)

![HORIZONTAL_BAR_VISIBLE](https://i.imgur.com/54WlDvu.png)

**Comment by alanrenmsft** [comment]
the issue is fixed.
