### ISSUE TITLE
Feature Request: Hide "Results" pane by dragging its top border down to the very end

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#1747]
- SQL Operations Studio Version: 0.30.6

For now, hiding *Results* pane is realized through key combination (Ctr+Windows+R by default). This is **very** inconvenient, so is it possible to be able to hide pane by dragging its top border down to the very end? For now, it's **impossible** to drag it less than ≈30% of screen (it stops dragging). In other words, I'd want the same behavior as in SQL Server. Thanks!

**Comment by kevcunnane** [comment]
This seems like a valid request.

**Comment by JohnyL** [comment]
Any news?

**Comment by kburtram** [comment]
The results pane no longer has a minimum size requirement.  Thanks for logging this suggestion!

**Comment by JohnyL** [comment]
@kburtram Thanks a lot! 😉
