### ISSUE TITLE
Extensibility: Ability to Increase the Size of the Blue Bar at the Bottom

### ISSUE THREAD

**Issue by JASM2007** [microsoft/azuredatastudio#1750]
- SQL Operations Studio Version: 0.30.6

There should be a way to increase the size of the Blue Bar a the Bottom of SQL Operation Studio it's too small to really notice what it trying to tell the user. Not sure what the official name of that object is.

![image](https://user-images.githubusercontent.com/40634806/41979088-396fe3b4-79f1-11e8-9b4e-6f6c77e7ecbb.png)

**Comment by kevcunnane** [comment]
This behavior is something we inherit from Visual Studio Code. When you say 

> Not sure what the official name of that object is

What do you mean? If it's an element we control, we might be able to improve on at least that part.

**Comment by JASM2007** [comment]
Sorry for being unclear,

When I right click on the black left banner in SQL Operation Studio it is referred as the "Activity Bar". But below that there is the blue ribbon as seen in the screen shot above. I wasn't sure what to call the name of that blue ribbon.  Since it's at the very bottom of SQL operations and the blue ribbon is very thin is hard to read/see any of the icons. So I was hoping there was a way to expand the size blue ribbon or move it to a different location since it is basically a list of various notifications. Does that help?

**Comment by kevcunnane** [comment]
That does help. At present there's no way to increase the size. Most items do have hovertext to help on this. I'll keep this issue open and tracked as upstream since it is something we inherit from the base VSCode implementation. Thanks for the suggestion!

**Comment by kburtram** [comment]
This functionality is coming from the vscode platform code.  We prefer if this was fixed upstream.  Thanks for opening this suggestion!
