### ISSUE TITLE
Toolbar for Run Cancel Connect disappears after renaming file

### ISSUE THREAD

**Issue by mmcaulay** [microsoft/azuredatastudio#17517]
Issue Type: <b>Bug</b>

Open a file and connect to a database, rename that file in the explorer. The toolbar then disappears to Run/Cancel/Connect at the top of the editor window.
![image](https://user-images.githubusercontent.com/4042561/139164748-d473aeea-aaf0-4652-be79-88327d7ef8a4.png)

The only way to get the toolbar back is to close the individual file (not the whole folder) and reopen it. Would expect the toolbar to remain if a file is renamed.
![image](https://user-images.githubusercontent.com/4042561/139164882-fb906c56-deaf-463b-a3a4-eb1f7643938e.png)

This is using local SQL Server connections rather than Azure.

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
ssmskeymap|kev|1.1.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.12.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
azdata-sanddance|msr|3.3.0

(2 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
Moving this out since the merge isn't going to get in this release....

**Comment by Charles-Gagnon** [comment]
Closing this as it appears to be fixed in dev/insiders.

@mmcaulay If you get a chance to try out the latest insiders and verify that you also don't see the issue there anymore that'd be great!

**Comment by mmcaulay** [comment]
I can see this is fixed in the latest version, thankyou
