### ISSUE TITLE
Support ODBC Connections

### ISSUE THREAD

**Issue by rabader** [microsoft/azuredatastudio#17536]
Support for ODBC connections will allow users to use this as a one-stop shop for their database solutions. I have to work with Microsoft SQL Server databases, but also Hive, and other dbs that ODBC connections would enable.

**Comment by kburtram** [comment]
Thanks for the suggestion.  We're currently tracking this with https://github.com/microsoft/azuredatastudio/issues/7505.  Closing as duplicate.  Please add any missing context to the other issue.
