### ISSUE TITLE
'Copy with headers' error

### ISSUE THREAD

**Issue by retromermaidprincess** [microsoft/azuredatastudio#17545]
Issue Type: <b>Bug</b>

1. Run query
2. Right click on results...
3. ... Copy with headers
4. Application window freezes

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (21.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
1. Is there anything unusual about this result set (very large, unusual data types, something else)?

2. If you run a simple query such as `select * from sys.databases` and then try to select and copy with headers do you have the same issue? 

3. Do you see the same behavior with just `Copy`?

4. Does it eventually start responding or does the window stay frozen until you force quit? (if so how long did you wait?)

**Comment by retromermaidprincess** [comment]
1. Large result set, but I've copied larger.
2. Not seeing an issue with select * from sys.databases
3. Same behavior with copy
4. Takes 30 seconds to respond.  Sometimes it's necessary to force quit after more than two minutes of inactivity.

**Comment by alanrenmsft** [comment]
Same as https://github.com/microsoft/azuredatastudio/issues/23264
