### ISSUE TITLE
Allow user-level installations

### ISSUE THREAD

**Issue by toddlindner** [microsoft/azuredatastudio#1754]
- SQL Operations Studio Version: 0.30.6

Steps to Reproduce:
1.  Download sqlops-windows-setup-0.30.6.exe
2.  Run as unprivileged ser
3.  Error "You must be logged in as an administrator when installing this program."

Can this be resolved, like the vs code team?
https://github.com/Microsoft/vscode/issues/534

**Comment by kevcunnane** [comment]
@kburtram, this seems like something we could consider once we pick up the June changes in VSCode.

**Comment by shawmanz32na** [comment]
This is live in VSCode stable - see https://code.visualstudio.com/updates/v1_26#_user-setup-for-windows .

Can it now be time to consider this?

**Comment by kburtram** [comment]
This is currently supported.
