### ISSUE TITLE
Connection to Azure Synapse

### ISSUE THREAD

**Issue by ShakleeBI** [microsoft/azuredatastudio#17547]
Issue Type: <b>Bug</b>

For the life of me, I cannot connect to Azure Synapse. I changed my windows password, which gave me an error about the token or something. I was able to log into Azure Synapse but the connection never took. I reinstalled the program, but now it just spins without actually connecting or throwing any kind of error. I use Azure Active Director - Universal with MFA. SSMS currently works with the same settings. Please help!

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.77GB (22.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0

</details>

**Comment by Charles-Gagnon** [comment]
Have you tried removing and re-adding your account? There's some caching issues we've seen in the past.

@cssuh

**Comment by ShakleeBI** [comment]
That led me to the right place. I had re-login using the accounts (looks like a profile button) within the program and add my account for a Linked Account. I first needed to ensure Azure Account Configuration -> Enable at least one cloud was enabled before logging in using the profile section. I was just stuck on the connection setting, which was getting me nowhere (I could even see my account within that screen).
