### ISSUE TITLE
Kerneländerungen

### ISSUE THREAD

**Issue by guidoklein** [microsoft/azuredatastudio#17560]
Issue Type: <b>Bug</b>

Im Notebook ist keine Kerneländerung auf Python etc. möglich

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (21.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-de|Mic|1.33.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.13.0

</details>

**Comment by kburtram** [comment]
@guidoklein unfortunately we can only provide support on this repo in English.  sorry for any inconvenience.
