### ISSUE TITLE
Create SQL Binding should give user default connection setting name

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17569]
Currently we just ask them to enter their own or create a new one

![image](https://user-images.githubusercontent.com/28519865/139953522-d90fdc26-c872-41ab-bb51-fa014ec86cdc.png)

It would be handy to have the top option be a default name (SqlConnectionString or something) - if the settings file don't already have it then indicate as such with a + icon or something.

**Comment by lucyzhang929** [comment]
@chlafreniere @Charles-Gagnon @dzsquared  Do we want to replace the `+ Create new local app setting` with `+ SqlConnectionString` or have both options?

**Comment by Charles-Gagnon** [comment]
Both, SqlConnectionString should always be on top, followed by `Create new local app setting`.

If there is already an app setting named `SqlConnectionString` then it should be shown without the plus icon

**Comment by Charles-Gagnon** [comment]
So it'll either be 

```
+ SqlConnectionString
+ Create new local app setting
...
```
or
```
SqlConnectionString
+ Create new local app setting
...
```
