### ISSUE TITLE
Unable to connect account via localhost redirect

### ISSUE THREAD

**Issue by YodasMyDad** [microsoft/azuredatastudio#17561]
Issue Type: <b>Bug</b>

If I try to connect an account, I get redirected to my web browser and it trys to connect via a non existant localhost url. So I get a 404 error. Same happens with Azure Data Explorer. Here is the Github issue https://github.com/microsoft/AzureStorageExplorer/issues/4342 ... Have to use integrated sign in to get around it, but cannot find that setting in this data studio

Azure Data Studio version: azuredatastudio-insiders 1.34.0-insider (d7b0b6c251238b159cb76b902d348e9e993bfcfb, 2021-11-02T05:45:03.588Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (3.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (20)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.47.0
arc|Mic|0.9.6
azcli|Mic|0.1.0
azdata|Mic|0.6.4
azuredatastudio-postgresql|Mic|0.2.7
cms|Mic|0.9.1
dacpac|Mic|1.9.1
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
machine-learning|Mic|0.11.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2021.8.2
profiler|Mic|0.12.1
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.13.0
sql-dw|Mic|0.0.1

</details>

**Comment by Charles-Gagnon** [comment]
Are you seeing the same SSL error as the issue you linked? If your web browser is automatically redirecting http links to https then that would be the problem - you need to disable that in your browser to use the code grant auth method.

Alternitively you can use the device code which doesn't use the local web server. Find these settings and ensure `Code Grant` is unchecked and `Device Code` is checked.

![image](https://user-images.githubusercontent.com/28519865/139910461-b80d39e5-cea2-43cd-833d-7c60117b9d7d.png)

**Comment by YodasMyDad** [comment]
Yes, same error as that issue. I have changed those settings and can now connect my azure account. Thanks.

**Comment by Charles-Gagnon** [comment]
Thanks for following up, glad the workaround worked! I'll be closing this issue - but we're aware the experience is still a little rough in some parts and will be working to make improvements there in the future.

**Comment by YodasMyDad** [comment]
I was also able to work around this by going to

chrome://net-internals/#hsts

Delete domain security policies

Entering 'localhost' and clicking delete

Now the login works fine without having to change any settings

**Comment by LordZoltan** [comment]
@YodasMyDad has the correct way to sort this - especially since device code is being deprecated
