### ISSUE TITLE
Cannot change the height of messages pane

### ISSUE THREAD

**Issue by Kritiqual** [microsoft/azuredatastudio#17562]
As the title says, does anyone know how to change the height of the messages pane after excute? It keeps using half of my screen height

**Comment by kburtram** [comment]
@Kritiqual you should be able to resize the message pane using the sash control.  When the mouse is hovered over the divider line between the message and editor controls the divider should change to a wider blue line indicating that the cursor is positioned correctly for resize operation (see screenshot for example).  Is this not the behavior you're observing?  Maybe a screenshot would be helpful to provide better suggestions.  Thanks!

![image](https://user-images.githubusercontent.com/599935/139916196-dc2d012e-604d-462d-a7c5-2dc31b044020.png)

**Comment by Kritiqual** [comment]
i did that, but when I choose another block of code, it goes back to original size

**Comment by alanrenmsft** [comment]
so the request here is to remember the results/messages pane's size and apply it to subsequent query editors, right?

**Comment by Kritiqual** [comment]
Yes, that's what I want :||
