### ISSUE TITLE
Create SQL Binding fails for untitled files

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17571]
1. Create new untitled file
2. Change it to C# lang
3. Run `MS SQL: Add SQL Binding` command

This error is displayed `

Could not find file '$(WorkspacePath)\Untitled-1'.`

**Comment by lucyzhang929** [comment]
@Charles-Gagnon @chlafreniere What is the expected behavior here? Should the Add SQL Binding command not be shown for untitled files?

**Comment by Charles-Gagnon** [comment]
That's one quick solution (which should be simple to do with updating the when clause). For initial work that would probably be good enough, I don't imagine people are making many untitled C# files and putting functions in them anyways.

**Comment by chlafreniere** [comment]
When creating a new HTTP trigger through the AF extension, is the resulting file untitled or saved? If it's saved as like "HTTPTrigger1.cs", then absolutely let's not show for untitled files

**Comment by lucyzhang929** [comment]
Yep, it is saved as HTTPTrigger1.cs
