### ISSUE TITLE
Create SQL Binding should allow users to choose server from MSSQL extension (if installed) and use that connection 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#17570]
Currently we require that the user enters their own string. It would be nice to generate it for them by having them select a connection (or make a new connection) using the VS Code selection connection prompts.

![image](https://user-images.githubusercontent.com/28519865/139953967-8296a9c2-b4dd-45ec-a0f6-0168d59551c2.png)

(when entering in manually as well it would be nice to have an example string somewhere they can reference as well since it's common to not remember exactly how each one is formatted)

**Comment by lucyzhang929** [comment]
P1: show an example of a connection string (description field)
