### ISSUE TITLE
Can't type in code cell after editing Notebook text cell

### ISSUE THREAD

**Issue by dullroar** [microsoft/azuredatastudio#17579]
We have written the needed data into your clipboard because it
Issue Type: <b>Performance Issue</b>

The performance upgrade appears to have moved all the rendering to a background thread, which gives the illusion of UI interaction but few things work until CPU goes back to 0 on a complicated notebook. The new shortcut keys for the Markdown cells also seems to be causing a lot of issues elsewhere. I cannot type in pre-existing code cells in a notebook but have to copy the code out, edit it elsewhere and then paste it back in, and the Ctrl-C/Ctrl-V shortcut keys don't even work for paste.

Azure Data Studio version: azuredatastudio 1.33.0 (6783aa6967e8c6d086b6f04e5fbf527659981389, 2021-10-26T17:28:15.782Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz (8 x 2095)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|20.00GB (5.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details> was too large to send. Please paste.

**Comment by lucyzhang929** [comment]
Hi @dullroar, thank you for filing an issue. Couple of clarifying questions:
1. Would you be able to share the notebook where you encountered this issue: "I cannot type in pre-existing code cells in a notebook"? 
2. Is this happening with every pre-exisiting notebook that you open?
3. Just to confirm, are you referring to the Incremental Grid Rendering feature when you say performance upgrade? And are you seeing the issues when the feature is turned on?

**Comment by dullroar** [comment]
Lucy:
1. This is internal notebooks documenting data quality issues in our CRM system so sadly, no. I will say where I see it most is in fairly large notebooks, but there is nothing fancy going on. A text cell stating "This is an attribute on a CRM entity, following are one or two queries showing data issues," and then the code cell(s) and result(s). All results are grids, not charts. None of the result sets are overly large, it is just there are quite a few cells and cell types in each notebook. The most problematic .ipynb file with results in it is 3MB.
2. Yes, although at "some point" when editing a new notebook, past a certain x of complexity (size? cell count? don't know), will start slowing down, too.
3. I am referring to the release that just came out, azuredatastudio 1.33.0 (6783aa6, 2021-10-26T17:28:15.782Z from the info I pasted above, apparently. To my knowledge I am not on any insider release. I upgraded to this release because the release notes promised performance improvements. The prior release without the problems I am experience would just freeze for a couple minutes when opening one of these files, but then everything worked pretty well. Now, the usability has gone down dramatically. :(

**Comment by lucyzhang929** [comment]
Hi @dullroar,
 
The fix for "I cannot type in pre-existing code cells in a notebook" is now available in Insiders, which can be downloaded here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main. 
Can you try out the latest Insiders build and see if you run into any issues typing in pre-existing code cells?

For the performance issues, can you check if the Incremental Grid Rendering feature is on? You can find this by going to Settings and searching for Incremental Grid Rendering. Turning this feature off should give you the same performance as the previous release (1.32).
<img width="904" alt="Screen Shot 2021-11-04 at 8 32 35 AM" src="https://user-images.githubusercontent.com/23462877/140358628-8fb4bc01-771b-4349-820f-f3544aa7c72b.png">

For the Markdown keyboard shortcuts, could you explain the specific shortcuts that are not working and what issues they are causing?

**Comment by dullroar** [comment]
1. I am now on the Insiders build and can state the "cannot type in pre-existing code cells in a notebook" still exists there.
2. I turned off Incremental Grid Rendering, and indeed it goes back to the old behavior of taking minutes to render and become responsive, but then it works quite nicely. I prefer that. I can always go get some more water while waiting for a notebook to open. :)
3. It isn't the **_Markdown_** keyboard shortcuts that aren't working - sorry if I was unclear. It is Ctrl-C/Ctrl-V isn't working by keyboard shortcut in the code cells when the symptoms in #1 are occurring, but mouse commands (select all, Copy, Paste) still work. So sometimes, since it can take minutes for a code cell to become editable, I will use the mouse to copy out the code in the cell, edit it somewhere else (koff Notepad++ koff) and then use the mouse to paste it back into the notebook code cell. That works, but is the definition of "clunky" and obviously not desired behavior.

**Comment by Charles-Gagnon** [comment]
Can you confirm the version of ADS Insiders you're using (Help -> About -> Copy)

**Comment by dullroar** [comment]
Version: 1.33.0 (user setup)
Commit: 6783aa6967e8c6d086b6f04e5fbf527659981389
Date: 2021-10-26T17:28:15.782Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment]
Ah, that's still the stable release. Could you try following the instructions here to get the insiders build and try that? https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

(they can be installed side-by-side so you don't have to uninstall the stable build or anything first)

**Comment by dullroar** [comment]
I am confused. I downloaded the release from that page, installed it, and started it from the installer wanting to launch it. Do I have to remove the system-installed release first?

**Comment by Charles-Gagnon** [comment]
Odd, which insiders installer did you use?

**Comment by dullroar** [comment]
azuredatastudio-windows-user-setup-1.34.0-insider.exe is what I launched from the Downloads folder.

**Comment by dullroar** [comment]
Logged out, logged back in, started ADS, confirmed in Task Manager the path to the executable was in my AppData. It still looks like the same About info, though:
Version: 1.33.0 (user setup)
Commit: 6783aa6967e8c6d086b6f04e5fbf527659981389
Date: 2021-10-26T17:28:15.782Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by dullroar** [comment]
Also confirmed ADS is in my PATH and that it is pointing to AppData, and that there isn't another ADS in my path (like from a system install).

**Comment by Charles-Gagnon** [comment]
How are you launching the insiders build? You should have two entries in the start menu : 

![image](https://user-images.githubusercontent.com/28519865/140393115-1b744185-b004-487f-8581-eb3cc21ee389.png)

Or you can also 

1. Launch from a cmd window with `azuredatastudio-insiders`
2. Browse to `%LOCALAPPDATA%\Programs\Azure Data Studio - Insiders` and launch `azuredatastudio-insiders.exe`

**Comment by Charles-Gagnon** [comment]
@dullroar FYI I updated the title to focus specifically on the "can't type in the cell" issue.

Once we've verified the fix with you then we can see if you're still running into perf issues and if so open a separate issue for that.

**Comment by dullroar** [comment]
Thanks @Charles-Gagnon @lucyzhang929 for your help on diagnostics.

**Comment by Charles-Gagnon** [comment]
Thanks for the confirmation @dullroar - so it sounds like the "can't type in code cell" issue is resolved in the insiders?

Would you mind making a new issue for the perf issues with any details you can provide? We can start helping with taking a look at that separately then.

**Comment by dullroar** [comment]
@Charles-Gagnon I would consider this issue resolved. May I tag you when I open a new performance-related ticket?

**Comment by chlafreniere** [comment]
Feel free to tag me @dullroar. I can assign it out 😄
