### ISSUE TITLE
DeprecationWarning when installing extension from command-line

### ISSUE THREAD

**Issue by thecesrom** [microsoft/azuredatastudio#17585]
- Azure Data Studio Version: 1.33.0
- OS Version: Windows 10/macOS 10.15

Steps to Reproduce:

1. Run `azuredatastudio --install-extension <extension-id[@version] | path-to-vsix>`
    ```bash
    $ azuredatastudio --install-extension Microsoft.admin-pack
    Installing extensions...
    Installing extension 'microsoft.admin-pack' v0.0.2...
    (node:28640) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
    (Use `azuredatastudio --trace-deprecation ...` to show where the warning was created)
    Extension 'microsoft.admin-pack' v0.0.2 was successfully installed.
    ```
1. Passing the `--trace-deprecation` option has no effect, and prints the following output
   ```Warning: 'trace-deprecation' is not in the list of known options, but still passed to Electron/Chromium.```

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
This is an upstream issue from VS Code - see https://github.com/microsoft/vscode/issues/82524
