### ISSUE TITLE
"Command Not Found" Error After Installing Projects Extension and choosing "Add SQL Binding" command

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#17581]
After installing vsix, I wasn't prompted to reload VS Code. I tried using the "Add SQL Binding" command from the command palette, and was met with a popup that stated "command not found".

After reloading VS Code, everything worked as intended.

**Comment by lucyzhang929** [comment]
@chlafreniere are you still able to repro? I reinstalled the Projects extension and was able to use the add sql binding command right away.

**Comment by chlafreniere** [comment]
Can't repro any longer. Closing issue as a result.
