### ISSUE TITLE
Generated binding for HttpTrigger doesn't include necessary System.Collections.Generic import.

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17583]
1. Create a new Azure Function (HttpTrigger)
2. Add sql binding to function

Expected: output is immediately compileable

Actual: missing `using` statement results in error for "unknown" reference for `IEnumerable<T>`

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/17572
