### ISSUE TITLE
SQL Binding fails without a useful error message 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17580]
- Azure Data Studio Version:
- OS Version:

I get 401 for installing the nuget package when I run SQL binding but the only thing I get in UI is a general error "Process Existed with code 1" 
I see the actual error in the output but I think the error message should at least mention to check the output for details

Steps to repro:
1- Create a function app
2- open .cs file 
3- Run Create SQL binding command
4 - follow the prompts  

As I mentioned above, I do have a problem with installing the nuget so not sure if the same error happens for other failures.

Expected: Should get useful error message for when "Create SQL Binding" command failed
Actual: got the error " "Process Existed with code 1" "
 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Could you give more details? It's unclear exactly where you're hitting this issue...exact repro steps would be appreciated.

**Comment by llali** [comment]
@Charles-Gagnon  I added steps in the bug. let me know if it's still not clear.
