### ISSUE TITLE
Remember Password is not selected on saved connections causing password to be forgotten

### ISSUE THREAD

**Issue by jasoncavett** [microsoft/azuredatastudio#17594]
- Azure Data Studio Version: 1.33.0
- OS Version: Windows 11

Steps to Reproduce:

1. Open up Azure.
2. Open a new tab.
3. Click "Connect" along the top bar
4. Select a saved connection from my list
5. The "Remember password" box is always unticked now

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
Probably related to https://github.com/microsoft/azuredatastudio/issues/10424

**Comment by jasoncavett** [comment]
Possibly. I should probably specify that this issue just happened to me with the latest release. The other looks to be well over a year old.

**Comment by JeffBusterCase** [comment]
> Possibly. I should probably specify that this issue just happened to me with the latest release. The other looks to be well over a year old.

Yep me too. It was there aways. After the last update the passwords showed up but the checkbox to save it was not checked. So I proceed to 'connect' without noticing that at first. Lost the password.....

After a few tryouts, it seems the checkbox to save the password only works once. So everytime you need to check it before connecting. If not, the password will be lost.
