### ISSUE TITLE
Open File after Save as Excel No Longer opens it via Microsoft Excel

### ISSUE THREAD

**Issue by bjones021595** [microsoft/azuredatastudio#17618]
Issue Type: <b>Bug</b>

Hi - after updating to the latest Azure Data Studio, I can no longer open a saved excel file in Microsoft Excel after using the Save as Excel feature on a query. It gives an alert of "An external application is trying to open..." and tries to open the file in Azure Data Studio rather than Microsoft Excel. Please help!

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) E-2286M  CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (55.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.48.0
query-history|Mic|0.1.0
sql-assessment|Mic|0.6.1
azdata-sanddance|msr|3.3.0

</details>

**Comment by timbo3220** [comment]
I have the same issue. It's driving me nuts
Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by emead-spentech** [comment]
Same issue - also, occasionally when the popup of "An external application is trying to open xxxx in asuredatastudio" is up for a few seconds, I get another error of "Another instance of azuredatastudio has stopped responding"



![Screenshot 2021-11-12 110934_LI](https://user-images.githubusercontent.com/46965538/141498752-5461b14f-02ee-4b4c-b460-0f5a76b0471e.jpg)

**Comment by isaarikko** [comment]
Having the same issue

Issue Type: <b>Bug</b>

Pervioulsy opening Excel after saving the query results opened Excel, now Data Studio is tryign to open Excel in editor window

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by Charles-Gagnon** [comment]
Thanks for the reports everyone, the fix for this has been checked in. So it should be showing up in the insiders builds starting next week if you wanted to test it out there. Otherwise it will be included in our next release (sometime early December).

Sorry for the inconvenience!

**Comment by bjones021595** [comment]
Thank you!
