### ISSUE TITLE
Database [Security] [Users] settings in Azure data studio

### ISSUE THREAD

**Issue by JuliusHolmberg** [microsoft/azuredatastudio#17622]
I noticed some massive differences between **Azure data studio** and **SQL Server Management Studio** when it comes to handling Security and Users of a Database.

I can't use Azure data studio to set up my Security and Users as far as I can see. 
Azure data studio: https://prnt.sc/1yrp568 (I can't get open a menu or change any of these)
SQL Server Management Studio : https://prnt.sc/1yrpf1r
I've looked over this article https://docs.microsoft.com/sv-se/sql/azure-data-studio/settings?view=sql-server-ver15 but the answers to my question is not in there.

Am I missing something?
Should I not expect the same settings being available in the two programs?

**Comment by Charles-Gagnon** [comment]
Have you tried using the `Database Administration Tool Extensions for Windows` extension? That adds support for the properties and generate script wizard from SSMS into ADS. 

![image](https://user-images.githubusercontent.com/28519865/140791683-1975a9bb-32c0-40d8-bc10-1c59a3a5c3ea.png)


![image](https://user-images.githubusercontent.com/28519865/140791588-c7c69378-6194-4afd-88f6-7ff832537fa5.png)

**Comment by JuliusHolmberg** [comment]
Thank you friend. That's exactly what I needed!
