### ISSUE TITLE
Wiki information about Azure Data Studio extensions is outdated

### ISSUE THREAD

**Issue by nojetlag** [microsoft/azuredatastudio#17635]
**Is your feature request related to a problem? Please describe.**
The links to the .vsix files are outdated. (https://github.com/microsoft/azuredatastudio/wiki/List-of-Extensions) Looking at the versions that these links download and what is available in the ADS extension manager(often they are newer) doesn't match. At the same time it is currently not possibe to use tools like ProGet (Indeo) to have access to these extensions from clients that are not able to directly access the internet (not uncommon in high security environments). Why are these extensions not hosted on the MSFT marketplace like other extensions ? From what I understand is that ADS is based on Visual Studio Code, then why again a different approach to dealing with extensions ?

**Describe the solution or feature you'd like**
Either keep these links current or why not integrate the extensions in the https://code.visualstudio.com/docs/editor/extension-marketplace. ?

**Describe alternatives you've considered**
none, current situation is a bit frustrating for users that can't directly access the internet with ADS

**Additional context**

**Comment by Charles-Gagnon** [comment]
Thanks for catching that @nojetlag, the list should be updated now!

As for your question about the marketplace - unfortunately currently we are unable to onboard onto the VS/VS Code marketplace in its current state. We have plans to move over there eventually but there's no ETA at the moment.

**Comment by nojetlag** [comment]
Hi @Charles-Gagnon thanks very much for updating. However I think the link to the .vsix for SQL Server Agent is now broken. Rest looks good! Also thanks for the update about the marketplace situation. Hope this will come 2022 :)

**Comment by Charles-Gagnon** [comment]
Ah, apologies for that! The links should be correct now (also fixed up some others that weren't accurate)
