### ISSUE TITLE
Inconsistent/Unexpected Results: Sorting Query Results with Nulls in SQL Notebook

### ISSUE THREAD

**Issue by ebeery11** [microsoft/azuredatastudio#17633]
Issue Type: <b>Bug</b>

When SQL notebook query results return NULLs, "Sort Ascending" and "Sort Descending" functions in the query results table yield inconsistent and unexpected results.

**Sample Query:**

```SQL
DROP TABLE IF EXISTS #Temp_A
DROP TABLE IF EXISTS #Temp_B;

CREATE TABLE #Temp_A
(
    id char(3),
    first_name VARCHAR(30)
)

CREATE TABLE #Temp_B
(
    id char(3),
    sales numeric(19,4)
)

INSERT INTO #Temp_A
VALUES 
('1', 'eric'),
('2', 'bob'),
('3', 'sally'),
('4', 'joe'),
('5', 'nancy'),
('6', 'frank'),
('7', 'alice'),
('8', 'rico')

INSERT INTO #Temp_B
VALUES
('1', '200000'),
('5', '60000'),
('7', '750000'),
('4', '250000'),
('8', '130000')

SELECT
    a.id,
    a.first_name,
    SUM(b.sales) as Sum_Sales
FROM
    #Temp_A as a
    LEFT OUTER JOIN #Temp_B as b
        ON a.id = b.id
GROUP BY
    a.id,
    a.first_name
ORDER BY
    id ASC
```
**Initial Results**
![image](https://user-images.githubusercontent.com/16659917/140925644-01d0b767-8031-461c-a2c6-7f02c3ca8fbe.png)

**Actual Results after "Sort Ascending"**
![image](https://user-images.githubusercontent.com/16659917/140925695-954630ad-2b20-4b8e-a626-a2d36d3d3a95.png)
![image](https://user-images.githubusercontent.com/16659917/140925725-f68806b3-f441-4cf0-ab47-4c068f814b94.png)

**Expected Results after "Sort Ascending"**
![image](https://user-images.githubusercontent.com/16659917/140925907-f4f38c25-86c0-4e73-8251-9baa739399e8.png)

**Actual Results after "Sort Descending"**
![image](https://user-images.githubusercontent.com/16659917/140925786-ffd9702a-cb18-4cd6-b2e0-aa264552d07d.png)

**Expected Results after "Sort Descending"**
![image](https://user-images.githubusercontent.com/16659917/140925989-f3e137ea-56ec-41b0-9066-24c511316fdc.png)

I should note that the results seem to be inconsistent - after alternating between "Sort Ascending" and "Sort Descending" numerous times, eventually I am able to manipulate the results to this, with all NULLS finally grouped together, at which point a subsequent "Sort Ascending" or "Sort Descending" operation finally returns the desired result (after _many_ clicks).

![image](https://user-images.githubusercontent.com/16659917/140926332-208b38de-bee2-42a5-8684-305cfc0d6d27.png)

These results are unexpected, and can be difficult to catch when a query returns more than ≈ a dozen rows.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (4.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

**Comment by chlafreniere** [comment]
@alanrenmsft looks like this also affects query editor grids. Any idea what could be going wrong here?

Happy to look into this myself, got any pointers?

**Comment by alanrenmsft** [comment]
I'll take a look @chlafreniere
