### ISSUE TITLE
Crash on startup with no error message when graphics acceleration is turned on under vmware

### ISSUE THREAD

**Issue by mtk** [microsoft/azuredatastudio#17641]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Launch an instance of Fedora 35 as a guest running under Windows 10 as a VMware host.
2. Make sure graphics acceleration for the VM is turned *on*.
3. Launch azuredatastudio and watch it silently return with no error message.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
Does this also occur with VS Code?

**Comment by mtk** [comment]
interesting question.  no, it did not.  i thought of that test myself :-).
/mark

**Comment by mtk** [comment]
after the 1.33.0 -> 1.33.1 upgrade, it:

1) sometimes crashes with no error message (or any kind of message at all)
2) sometimes displays a solid white window with a menu bar that reads "file/edit/view/help".  the menu items drop down but any choice is just ignored.

**Comment by mtk** [comment]
if it starts without crashing (but fails to do anything useful), are there command line arguments that enable debug logging?

**Comment by mtk** [comment]
turning off graphics acceleration made it work for a while.  but after the latest round of fedora updates, even with vmware graphics acceleration off, it crashes silently.  mesa, for example, is 21.2.5 on this platform.  is there any way to make it print some diagnostics??

**Comment by mtk** [comment]
ah, here we go.  

`libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[main 2021-11-14T19:17:48.779Z] Starting VS Code
[main 2021-11-14T19:17:48.781Z] from: /usr/share/azuredatastudio/resources/app
[main 2021-11-14T19:17:48.781Z] args: {
`

**Comment by mtk** [comment]
as of the latest round of updates (many for KDE), we're backing to silent crashing. any thoughts on how i could provide more info to you?

**Comment by kburtram** [comment]
@mtk I'm not sure if you intended to close the issue (as your most recent comment ends with a question).  Unfortunately though I am not really sure how to best investigate.  I'll try to install the Fedora version with VMWare and see if I can repo, but will need to allocate some time to run that test.  The error appears to be happening at lower-level than we typically code (e.g. in Electron or Chromium, etc.) when interacting with device drivers.  You may try downgrading to an older build (from a few months ago, for example) and seeing if that helps.  The point of that test would be use an early version of Electron, which may not have this incompatibility.

**Comment by mtk** [comment]
i did not intend to close it.  will this reopen it?  the issue still exists in the december 2020 v1.34 release.
