### ISSUE TITLE
incorrect JSON data when the grid is sorted/filtered. The hyperlink to inspect the JSON data is assigned to another loaded entry.

### ISSUE THREAD

**Issue by VinDeg75** [microsoft/azuredatastudio#17657]
Azure Data Studio
Version: 1.33.1 (user setup)
Commit: 0b9ef714c823d662815f441aec4a94eaa21940f8
Date: 2021-11-04T17:45:15.872Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.19041

**Steps to reproduce:**
1. Execute a query  that returns an product serial and a related JSON column data (NVARCHAR(Max)) with that also contains this ref somewhere.
2. In the result set check that the data is consistent (proof its still ok)
3. sort or filter on the product serial using the result grid
4. open the json bij clicking in the cell of the grid and find another records JSON values.

For info, i've extracted the serial via` json_value(...)` to ensure that the data in the database was correct. 

(Can't share data example here due confidentiality, sorry)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft

**Comment by alanrenmsft** [comment]
@VinDeg75 could you please provide the data to reproduce the issue with the confidential information removed.
