### ISSUE TITLE
new connection Azure SQL DB "Connect" in Connections sidebar spins indefinitely

### ISSUE THREAD

**Issue by WilliamDAssafMSFT** [microsoft/azuredatastudio#17661]
Issue Type: <b>Bug</b>

Just installed latest (non-insiders) version and DB Projects extension.
Connections that I can make instantly to Azure SQL DBs in SSMS spin indefinitely in the Connection side-bar. Confirmed Azure SQL DB firewall allows my IP. Using same username/password for SQL auth that works in SSMS, where the new connection opens immediately.
No popup for login failure.
Submitted this Issue Report while the Connection was spinning for 1+ minute.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (18.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.13.0
sqlservbdc-app-deploy|Mic|1.4.0

</details>

**Comment by WilliamDAssafMSFT** [comment]
Will get an error from the "Create new project from Database", where a Task will eventually appear with "Login failed for user..." even though I have open query connections with that connection.  Is the database project import process using all the same connection properties?

**Comment by kisantia** [comment]
@WilliamDAssafMSFT where are you launching "Create project from database" from? If launched from right clicking on an active connection, then opening the connection dialog to select a different selection isn't needed. If selecting a different/new connection, then the same connection dialog used to make connections in the connections viewlet is used.

**Comment by WilliamDAssafMSFT** [comment]
I cannot repro. Shrug.
