### ISSUE TITLE
Cancelling Save dialog means file cannot be saved, blanks file

### ISSUE THREAD

**Issue by mmcaulay** [microsoft/azuredatastudio#17663]
Issue Type: <b>Bug</b>

Steps to reproduce:
- Create a new file and start typing any text.
- Ctrl S to save the file
- Cancel the Save dialog before saving
- Ctrl S to save. Error message shows that save dialog is already open when it isn't.
![image](https://user-images.githubusercontent.com/4042561/141719121-03d2b6df-b42f-41fa-8f60-f0b38cfa8d5c.png)

The first time I saw it, I lost the contents of the file being saved and just got a blank editor window. The second time, I could still see the text I'd entered. The second time, the app prompts to save or discard changes and if you discard you can't close the file.

If the text is still there in the editor window, then the workaround is to paste it into a new window and save that.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (0.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
ssmskeymap|kev|1.1.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.12.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
azdata-sanddance|msr|3.3.0

(2 theme extensions excluded)

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Charles-Gagnon** [comment]
@mmcaulay Are you still seeing this? I just tried to repo it and can't seem to on my machine.

Does this happen every time you try this or is it intermittent?

**Comment by mmcaulay** [comment]
Hi it was consistent at the time but now I can't reproduce it.

**Comment by Charles-Gagnon** [comment]
Thanks, I'm going to close this now then since it doesn't seem like anyone else is hitting it either but if it happens again let us know!
