### ISSUE TITLE
Incorrect object list cursor behavior - first time R-Click

### ISSUE THREAD

**Issue by DouglasRBruce** [microsoft/azuredatastudio#17692]
Issue Type: <b>Bug</b>

Please consider changing this behavior - it is very annoying and non-productive:

1) Open/Manage a database - all objects are displayed in the list
2) Use the mouse wheel to go down PAST the first page of results
3) Right click on any object on that page
4) You are taken right back to the top object.  The R-Click menu is for the first object, not the one that was clicked on.

I would expect the item R-Clicked on to be selected and the R-Click menu to be for the item clicked on.

This seems to only occur the FIRST time the list is interacted with.  It's possibly just an initialization issue.  The workaround is to always click on the first object; then the behavior won't occur.  But I don't think it was meant to work this way.  Thanks!

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.17134
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (9.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
sql-search|Red|0.4.0
vscodeintellicode|Vis|1.2.1

(3 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@DouglasRBruce  the issue has been fixed and the fix will be included in the upcoming release.
