### ISSUE TITLE
Workspace Word Wrap setting not being honored

### ISSUE THREAD

**Issue by dhgrajeda** [microsoft/azuredatastudio#17690]
- Azure Data Studio Version: 1.33.1
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Under user settings set "Editor: Word Wrap" value to "on"
2. Under workspace settings set "Editor: Word Wrap" value to "off"
3. Open a notebook with a long paragraph and open the editor for that cell

Expected: The editor should have word wrap on. Our users expect this behavior which is set for them using the workspace settings.

Result: Word wrap is not on, and the scroll bar is not visible.

Does this issue occur when all extensions are disabled?: Yes

**Comment by barbaravaldez** [comment]
This is a duplicate of #17686
