### ISSUE TITLE
SQLCMD statments flagged as errors even when in SQLCMD mode

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#17691]
Issue Type: <b>Bug</b>

I have a working SQLCMD file.  My editor is set in SQLCMD mode (I know since the option at the top of the tab has a button to "Disable SQLCMD")

Even so, my valid SQLCMD statements are flagged as errors. e.g.

:setvar foo "bar" 

is flagged with the error message 
"Incorrect syntax near ':'.",

Note: this often happens after changing my connection.  Also, toggling the disable/enable sqlcmd button usually removes the error message

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
import|Mic|1.5.0
powershell|ms-|2021.8.2

</details>

**Comment by gbritton1** [comment]
Screen shot:

![image](https://user-images.githubusercontent.com/12263288/142234798-c9fe1e39-deef-4d54-ab52-92a2a93be3f3.png)

**Comment by Charles-Gagnon** [comment]
@llali Aren't we supposed to be disabling the language parsing when in sqlcmd mode?

**Comment by llali** [comment]
@Charles-Gagnon I don't think I worked on this feature before and I don't have any idea how it should work.

**Comment by gbritton1** [comment]
I don't think you should disable language parsing.  rather, you should also accept SQLCMD syntax as well as T-SQL

**Comment by alanrenmsft** [comment]
@kisantia is this something that was assigned to you by Udeesha?

**Comment by kisantia** [comment]
@alanrenmsft Udeesha added this a couple years ago, but I also haven't worked on this feature before.
