### ISSUE TITLE
Synapse SQL query for SStream not working in Azure Data Studio

### ISSUE THREAD

**Issue by mmiryala2** [microsoft/azuredatastudio#17701]
Issue Type: <b>Bug</b>

Here is a query that is not working in Azure Data Studio that is working in Synapse.

SELECT TOP 10 *
  FROM OPENROWSET(
  BULK 'Path/2021/11/Stream.D1_2021_11_14.ss',
  DATA_SOURCE = 'PROCESSED',
  FORMAT = 'SStream',  PARSER_VERSION='2.0'
) AS a

I get the following error
"Incorrect syntax near 'FORMAT'"

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (12.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yualan** [comment]
Hi @mmiryala2, what are you attempting to connect to in both Synapse Studio and in Azure Data Studio?

**Comment by alanrenmsft** [comment]
@mmiryala2 please reopen with answers to Alan's question.
