### ISSUE TITLE
Connections taking a long time to connect

### ISSUE THREAD

**Issue by magestorm55** [microsoft/azuredatastudio#17703]
Issue Type: <b>Performance Issue</b>

Basically any connection takes at least 30 seconds to establish. 

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   105	 14916	azuredatastudio main
    0	   187	  3840	   gpu-process
    0	    54	 10488	   crashpad-handler
    0	    78	 40840	   window (Issue Reporter)
    0	   191	 44340	   window (● SQLQuery_2 - rssql2019.master (Integrated) - Azure Data Studio)
    0	   150	 48416	     extensionHost
    0	   127	 27744	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.139\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\e4056\AppData\Roaming\azuredatastudio\logs\20211118T104330\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	    11	 51508	         console-window-host (Windows internal process)
    0	    36	 29500	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.139\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\e4056\AppData\Roaming\azuredatastudio\logs\20211118T104330\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	    11	 30876	         console-window-host (Windows internal process)
    0	    34	 30636	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.139\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\e4056\AppData\Roaming\azuredatastudio\logs\20211118T104330\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	    11	 43288	         console-window-host (Windows internal process)
    0	    33	 47496	       c:\Users\e4056\.azuredatastudio\extensions\microsoft.net-6-runtime-0.1.0\bin\runtime\dotnet.exe exec c:\Users\e4056\.azuredatastudio\extensions\microsoft.azuredatastudio-oracle-0.1.0\bin\service\AdsOracleExtensionService.dll
    0	    11	  1940	         console-window-host (Windows internal process)
    0	    67	 49516	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=48416
    0	    61	 46764	   utility
    0	   112	 49936	   shared-process
    0	    65	 49928	     ptyHost
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
eltsnap-simple-data-flow|bit|1.0.1
pastetheplan|dre|0.2.0
sql-server-diagnostic-book|ema|0.2.0
sql-data-inspector|ern|0.4.0
qpi|joc|0.1.6
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-oracle|Mic|0.1.0
dacpac|Mic|1.8.0
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
net-6-runtime|Mic|0.1.0
powershell|ms-|2021.8.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.13.0
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.3.0
extra-sql-script-as|pac|0.3.0
schema-visualization|R0t|0.7.1
sql-prompt|Red|0.2.8
sql-search|Red|0.4.1
simple-data-scripter|sea|0.1.6
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
Hey @magestorm55, sorry to hear you're having issues. Our repo adheres to the Microsoft [Code of Conduct](https://opensource.microsoft.com/codeofconduct/) and so we ask that any discussion remains civil and relevant to the discussion. I've edited your description to only include the parts relevant to any investigation.

If you have any other information - such as the type of server you're trying to connect to and whether you see these types of connection issues using other tools that may help with the investigation. Thanks!

**Comment by cssuh** [comment]
Closing as no further information was shared
