### ISSUE TITLE
Currently there is no version (x86-32 bit or ARM64) available for ARM64 PCs

### ISSUE THREAD

**Issue by gcaughey** [microsoft/azuredatastudio#1774]
- SQL Operations Studio Version:

Steps to Reproduce:

Always connected ARM64 PCs could be useful devices for SQL admins if supported

**Comment by cobrow** [comment]
Attempted to install on upcoming Surface Pro X and validating this Enhancement request.  Microsoft wants to push Windows on ARM would appreciate a compiled version of ARM64 or x86 to run on this platform.

**Comment by sivey42** [comment]
still no version of Azure Data Studio for Surface Pro X. Same goes for SSMS.

**Comment by Chris-FLD** [comment]
I agree. This would be useful for me and a few other colleagues who use Surface Pro X while on the road. If it's so easy for 3rd Parties to create ARM64 compiled versions of their software it would make sense for Microsoft to do the same and lead by example.

I look forward to seeing this and other Microsoft productivity / business applications being released with ARM64 support.

Thanks.

**Comment by openindustryorg** [comment]
Could you provide an an update on the status of this issue?

Thanks for you work.

**Comment by openindustryorg** [comment]
Any update please?

**Comment by gustavokei** [comment]
I am also interested in this. VSCode got some insider builds for ARM64 and it is working perfectly on my ARM Chromebook. Would be awesome to see it happen with ADS as well.

**Comment by openindustryorg** [comment]
> I am also interested in this. VSCode got some insider builds for ARM64 and it is working perfectly on my ARM Chromebook. Would be awesome to see it happen with ADS as well.

Hey gustavokei https://code.visualstudio.com/download just a heads up VSCode is released forARM64 now, so no need for insiders.

+1 on seeing ADS also.

**Comment by fonnesbeck** [comment]
Frankly, its a little ridiculous to market a device called a Surface *PRO* X and have it completely unable to interact with SQL Server. Database tools should have been the first thing out the door to be compatible with ARM, if its being touted as a pro device. Even with x86 emulation now available, there is still no way to use the device as a SQL Server client.

**Comment by therealdandecker** [comment]
So where does this stand? You’ve got Surface Pro X, Raspberry Pi and now Mac OS all operating on ARM64. With the insiders build available for VS Code and the SQL extension failing is it a matter of ODBC/OLE DB connectivity on the new architecture?

**Comment by lucasfolino** [comment]
I am interested in using this on a Pi4.  What is the underlying issue?  Shouldn't this kind of automatically work on ARM64 since it is electron?  Is it a specific component that doesn't work or a dependency that is missing?

**Comment by therealdandecker** [comment]
Not possible right now.

My speculation without confirmation: while VS Code has been released for ARM64, Azure Data Studio has not. I believe it comes down to support for the SQL driver (ODBC/OLE DB).

There has yet to be a Microsoft release of any cross platform ODBC connector to SQL for ARM64. If you install the SQL extension on ARM64 VS Code it also does not work.  You can even run a version of SQL Server on RPi4 using Docker and Azure SQL edge, the command line tools and connectivity are not available.

So, I think the Azure Data Studio teams real hold up is that Microsoft simply has not developed an official way for SQL DB connectivity on ARM64.

Best,

Dan Decker
________________________________

**Comment by lucasfolino** [comment]
If it is just SQL server that is the issue then why not release it for ARM64 and just support Postgres until the drivers for SQL are working.  Even if they want to slap a beta tag to it it would add value for some none the less and work out some of the bugs that would happen on ARM64.

**Comment by therealdandecker** [comment]
Have to take that up with Microsoft but I have not seen any Microsoft supported SQL driver for ARM64.

The code is open source so you could always modify, compile and use building from source.
________________________________

**Comment by lucasfolino** [comment]
Any one who works on the project can we get some actual input on this?   Is this planned?  Is this the reason there is no ARM64 support?  What is the status for ARM64 OLE DB/ODBC?

**Comment by kburtram** [comment]
@lucasfolino the main reason this hasn't been enabled yet is due to resource constraints and prioritization.  We don't use OLEDB or ODBC, and I'm not sure the status on that component on ARM.  We build on .Net Core and we'd need to compile that component for each of the platforms we'd like to support.  Most the work is updating the build scripts.  Another issue is that our development team doesn't currently have ARM64, Pi, or Apple Silicon devices so we'd don't have test environments to support these chipsets.  

This work has come up in a couple of our recent planning sessions and will be picked up in a future development iteration.  Though the timeline is not currently committed due to prioritization of other in-progress work.

**Comment by therealdandecker** [comment]
Curious if this is in the pipeline.

**Comment by tuxpoldo** [comment]
Any news on this?

**Comment by Nova-Logic** [comment]
@kburtram we need this. World need this, ARM is the future, since  Apple pushing ARM , and Microsoft trying to popularise ARM we need dev tools that support ARM, and ADS is important for that.

**Comment by therealdandecker** [comment]
If you are wanting to follow progress, I think this is where to look. [(https://github.com/microsoft/sqltoolsservice/releases)]

I think (could be wrong) the SQL Service layer used by VS Code MSSQL Extension and ADS is what is ultimately holding back this request.

**Comment by Pr1vEsc** [comment]
SQL Tools [4.1.0.19] Is showing a package for MAC ARM using .NET 6. 
(Microsoft.SqlTools.ServiceLayer-osx-arm64-net6.0.tar.gz).

I hope Azure Data Studio will soon be native because that would be great.


> If you are wanting to follow progress, I think this is where to look https://github.com/microsoft/sqltoolsservice/releases
> 
> I think (could be wrong) the SQL Service layer used by VS Code MSSQL Extension and ADS is what is ultimately holding back this request.

**Comment by alanrenmsft** [comment]
Folks, I just tried Azure Data Studio on a Windows 11 with ARM processor, and I am able to use it without any issue. I saw some comments mentioned they couldn't even run the app at all, I suppose it is because the emulator is only available recently?

Now the ask here is to produce a native build for Windows on ARM, right?

**Comment by alanrenmsft** [comment]
Folks, we have arm64 builds for Window now, it is only available for Insiders build at the moment and will be available in December stable build.

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch
![image](https://user-images.githubusercontent.com/13777222/201409332-a1c1b4e9-7d99-43fd-8d68-d4426eaf6e17.png)

@cobrow @iemejia

**Comment by iemejia** [comment]
@alanrenmsft For ref, just started to test it and found this minor issue https://github.com/microsoft/azuredatastudio/issues/21266
