### ISSUE TITLE
ADS 1.33.1 won't update over 1.32.0 on Linux with DEB file

### ISSUE THREAD

**Issue by craigs100** [microsoft/azuredatastudio#17740]
Issue Type: <b>Bug</b>

1. Have V1.32.0 of ADS installed. 
2. Download the azuredatastudio-linux-1.33.1.deb file.
2. Double click the downloaded file to have it open in the Package Manager.
3. Note red error banner on Package Manager stating "Error: Breaks existing package 'azuredatastudio' conflict: azuredatastudio()"

Azure Data Studio version: azuredatastudio 1.32.0 (4a45ba7cf20dd4129f1a08e5e776dfb33e3d1d1e, 2021-08-16T18:00:41.235Z)
OS version: Linux x64 5.13.0-21-generic (Linux Mint 20.2)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|31.02GB (0.89GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>Extensions: none

**Comment by kburtram** [comment]
@craigs100 I was able to upgrade from 1.34.0. to 1.35.1 with the below command sequence on Mint Linux.  You may try to uninstall the azuredatastudiopackage and then reinstall it to workaround the issue.  Please let us know if you are still impacted by this issue on the latest release.

```
# -- install to 1.34.0
user@user-Virtual-Machine:~/Downloads$ sudo apt install ./azuredatastudio-linux-1.34.0.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'azuredatastudio' instead of './azuredatastudio-linux-1.34.0.deb'
The following NEW packages will be installed:
  azuredatastudio
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/121 MB of archives.
After this operation, 478 MB of additional disk space will be used.
Get:1 /home/user/Downloads/azuredatastudio-linux-1.34.0.deb azuredatastudio amd64 1.34.0-1639602013 [121 MB]
Selecting previously unselected package azuredatastudio.
(Reading database ... 315334 files and directories currently installed.)
Preparing to unpack .../azuredatastudio-linux-1.34.0.deb ...
Unpacking azuredatastudio (1.34.0-1639602013) ...
Setting up azuredatastudio (1.34.0-1639602013) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...
user@user-Virtual-Machine:~/Downloads$ azuredatastudio

# -- update to 1.35.1
user@user-Virtual-Machine:~/Downloads$ sudo apt install ./azuredatastudio-linux-1.35.1.deb
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'azuredatastudio' instead of './azuredatastudio-linux-1.35.1.deb'
The following packages will be upgraded:
  azuredatastudio
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/125 MB of archives.
After this operation, 62.6 MB of additional disk space will be used.
Get:1 /home/user/Downloads/azuredatastudio-linux-1.35.1.deb azuredatastudio amd64 1.35.1-1647367587 [125 MB]
(Reading database ... 319445 files and directories currently installed.)
Preparing to unpack .../azuredatastudio-linux-1.35.1.deb ...
Unpacking azuredatastudio (1.35.1-1647367587) over (1.34.0-1639602013) ...
Setting up azuredatastudio (1.35.1-1647367587) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for desktop-file-utils (0.24+linuxmint1) ...

# confirm OS and distro
user@user-Virtual-Machine:~/Downloads$ uname -a
Linux user-Virtual-Machine 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
user@user-Virtual-Machine:~/Downloads$ cat /etc/debian_version 
bullseye/sid
```

**Comment by craigs100** [comment]
Thanks.

With version 1.34.0 installed, I removed it with: sudo apt-get remove azuredatastudio
I then installed version 1.35.1 by double clicking on the .deb file to initiate the package manager and clicked "Install". The installation proceeded apparently correctly but gives the final result as shown in the screenshot below. Note the error message at the top, which I guess is due to the package manager now being in a position to do a re-install, which it cannot do safely unless the package is first removed. A bit of a vicious circle.  The package itself appears to be correctly installed and working:-

![Screenshot from 2022-04-08 09-47-09](https://user-images.githubusercontent.com/1143883/162401316-a34775af-c9d8-4ac1-9b84-e3573f0a403b.png)

**Comment by sjsepan3** [comment]
This has been the case with every version of ADS that I have ever installed; when its checks for an existing version, it finds a conflict. As @craigs100 noted above, this even applies to the version _just installed_. 
Despite the message, the version installed works fine.

'Remove'ing the older version and then installing the .deb is/has been a valid work-around. It is just an annoyance, as Code and Codium never do this.

Version: 1.43.0
Commit: b790d700898b1095d83e62f0de14678a58222520
Date: 2023-04-10T23:08:07.209Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Linux x64 5.15.0-69-generic
