### ISSUE TITLE
Dashboard: OS Version doesn't show correctly for all versions

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1775]
- SQL Operations Studio Version: Daily build

Steps to Reproduce:
- Connect to a new SQL Server version (e.g. one from daily SQL drops)
- Manage and show dashboard
- OS version starts with `soft SQL Server ...` instead of capturing `Windows Server 2016 Datacenter 1` as expected.

**Comment by alanrenmsft** [comment]
this has been fixed recently.
