### ISSUE TITLE
Database selection doesn't work properly

### ISSUE THREAD

**Issue by elifozlem** [microsoft/azuredatastudio#17751]
Issue Type: <b>Bug</b>

After the databases are loaded, when i scrolling list and selecting a database brings it back to the top of the list

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:43:30.222Z)
OS version: Darwin x64 20.6.0

**Comment by alanrenmsft** [comment]
I believe this is a dupe of #17808
