### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by paulkckho** [microsoft/azuredatastudio#17752]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

How do we resolve this error? 

OS: Windows 10 Pro
![Screenshot 2021-11-28 164049](https://user-images.githubusercontent.com/72099759/143791099-7272e965-4d2f-4795-bd89-5b0e88ccd1b5.png)

How do we connect Azure Data Studio to SQL Server when we cannot establish connection?

**Comment by cssuh** [comment]
No further info provided
