### ISSUE TITLE
[Database Support] ODBC connections

### ISSUE THREAD

**Issue by Panguaneta** [microsoft/azuredatastudio#17765]
If you want to see ODBC DSNs support in Azure Data Studio, click the thumbs up 👍 sign.

**Comment by alanrenmsft** [comment]
Thank you for your feedback! This feature is currently out of scope and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.
