### ISSUE TITLE
Unable to Login with AAD w/MFA anymore!

### ISSUE THREAD

**Issue by SashaRisner** [microsoft/azuredatastudio#17777]
Issue Type: <b>Bug</b>

I am suddenly unable to login to my azure sql databases using Azure Active Directory with MFA. I cannot add an account, It tells me I need to search for azure cloud in settings - I've tried that and it does not exist. I've tried to remove my MFA account but I don't see how I can. I would clear my cache but I don't know where this is cached. Would like to reset azure data studio settings and start clean but whenever I uninstall and install, it remembers everything... not working!

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (23.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>Extensions: none

**Comment by slaymaker1907** [comment]
I was also experiencing this issue. However, I was able to resolve it by explicitly removing my account then adding it again. In order to remove the account @SashaRisner, you need to click on the person icon above the settings wheel which will bring up your linked accounts. Then just click on the X next to the account. I hope this helps!

![image](https://user-images.githubusercontent.com/12125553/146851329-96908454-8f0a-4e9a-8a0d-6ccbbdd5ee07.png)

**Comment by cssuh** [comment]
@SashaRisner please try the suggestion that @slaymaker1907 has provided, and if it still doesn't work, please let us know.

**Comment by SashaRisner** [comment]
Appreciate the suggestion but it did not work. I tried everything in the UI to delete my account but it kept 'remembering' the configuration. I ended up physically deleting the folder azuredatastudio under %userprofile%\AppData\Roaming\ and that finally fixed it.
