### ISSUE TITLE
Backup files component does not allow clicking on 2nd file

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1777]
- SQL Operations Studio Version: daily

Steps to Reproduce:
- Get to the Backup wizard (click Backup in a DB Dashboard or similar behavior
- Add a 2nd file to the backup files
- Try to remove it by clicking on it, then clicking `-` button

Expected: 
- Clicking changes the selection
Actual:
- Cannot click to change. Clicking adds some weird dropdown / subvalue instead.

Workaround:
- Use arrow keys to toggle between them. This is frustrating but does work

![image](https://user-images.githubusercontent.com/10819925/42051378-cb8a7b5e-7ac0-11e8-8eb7-a21bf7ebb9f1.png)

**Comment by anthonydresser** [comment]
looks like it was caused by https://github.com/Microsoft/sqlopsstudio/commit/dafb7809875f49856b9b38e823a2f7dbd72733dd I haven't looked at what changes were made to cause it, but I wouldn't be surprised if we have to rewrite this control.

**Comment by kevcunnane** [comment]
Does this count as an accessibility issue by the way? Also how were you identifying the VSCode merge as the cause?

**Comment by anthonydresser** [comment]
accessibility issue? probably? but it's just a usability problem. Its the first commit where this problem shows up, and it also makes sense. That ui component is extended from a vscode component, so they probably rewrote that component and the modifications Kate made to it before no longer work.

**Comment by kevcunnane** [comment]
Cool. What are next steps? Do we need to chat with @kburtram to get this prioritized?

**Comment by anthonydresser** [comment]
I'll have to look at home much work it will be to rewrite this and let @kburtram know.
