### ISSUE TITLE
No longer saves connections with sql server credentials

### ISSUE THREAD

**Issue by CoryKoehler** [microsoft/azuredatastudio#17776]
Issue Type: <b>Bug</b>

Hello,

Try connecting to any db via the Azure connection tab using SQL credentials and clicking save connection.
It no longer saves for easy reconnection in future

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 3970X 32-Core Processor  (64 x 3700)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.90GB (109.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cssuh** [comment]
This was fixed in https://github.com/microsoft/azuredatastudio/pull/17718
