### ISSUE TITLE
Update yarn installer task that uses Node execution handler 6 (EOL)

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#17772]
The latest version of yarninstaller task uses node 6 execution handler that is going to go out of support in March 2022.

The solution is to either replace this task with something else or wait for an update. 

Error Message:
##[warning]This task uses Node 6 execution handler, which will be removed March 31st 2022. If you are the developer of the task - please consider the migration guideline to Node 10 handler - https://aka.ms/migrateTaskNode10 (check this page also if you would like to disable Node 6 deprecation warnings). If you are the user - feel free to reach out to the owners of this task to proceed on migration.

Task to be updated:
![image](https://user-images.githubusercontent.com/6816294/144128686-aec82bd5-1294-4c22-b998-596b7889595d.png)

There is already an issue filed at the task repo: https://github.com/geeklearningio/gl-vsts-tasks-yarn/issues/102

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 I'm not seeing this anymore - is this still active?

**Comment by aasimkhan30** [comment]
The latest version of this task ships with node 10 execution handler. This issue should automatically be fixed for us as we are pulling the latest version of this task. 

https://github.com/geeklearningio/gl-vsts-tasks-yarn/issues/102
