### ISSUE TITLE
Sqlproj schema compare against project doesn't refresh the model after changes are applied 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17783]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a project from a db with tables 
2. Add a table to sql proj
3. Open schema compare and select db as source and project as target 
4. compare and apply changes to delete the table
5. build the project and make sure table is deleted
6. in same schema compare window click on compare again
7
Expected: should show no difference 
Actual: got an error for the missing script:
Schema Compare failed: Unexpected exception caught during population of target model: Could not find file 'c:\Users\[user]\SqlProjTest\DatabaseProjectkeep_AdventureWorks2019\Tables\Table1.sql'.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Benjin** [comment]
Reopening the Schema Compare window works; ideally would refresh the model schema compare uses

**Comment by kisantia** [comment]
I'm not able to repro this anymore. Might have been fixed with https://github.com/microsoft/azuredatastudio/pull/18890, since that reloads the projects
