### ISSUE TITLE
Schema compare against project shows differences that are not when comparing against dacpac 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17789]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create db project from AdventureWorks 2019
2. Open Schema compare 
2. compare the project with db
Expected: no differences 
Actual:
Extended property is different: 
EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'AdventureWorks 2016 Sample OLTP Database';
GO

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Benjin** [comment]
Investigation: does this repro in SSDT as well?  I suspect it's resulting from how DacFx builds the model from loose script files.

**Comment by kisantia** [comment]
closing as I'm not able to repro this. Might have been fixed by https://github.com/microsoft/sqltoolsservice/pull/1727
