### ISSUE TITLE
schema compare open to editor shows an error

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17784]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. open schema compare with any source/target
2. right click on the tag and click on "reopen editor with"

editor opens with some scripts but with an error:
Unable to open 'Schema Compare': Unable to resolve resource ModelViewEditorScheme:Schema%20Compare.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
closing since I don't see this anymore in insiders - nothing happens when I right click on a schema compare editor and click "reopen editor with...". Maybe this was fixed in a vscode merge.
