### ISSUE TITLE
Updating project from database "thinks" without indication before finishing operation for Direct Apply op

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17788]
UX should give some indication that it's doing something (i.e. building the model from the sqlproj, doing the comparison) so the user isn't confused/concerned.

Occurs when "Apply Changes Directly" is selected.

**Comment by dzsquared** [comment]
task suddenly appears after applying changes finishes:
![image](https://user-images.githubusercontent.com/12227241/144338054-95a09a1b-beb7-4d1d-9433-12329b09ee3b.png)
