### ISSUE TITLE
Update target is not loading the database project after successfully updated the project

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#17785]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a database project from the database
2. Add a table to the database
3. Right click on db project and 'update project from database'
4. SC window will show the differences and click on 'Apply'
5. After successful update, observe the database projects pane and the db project is not loaded with new changes unless we close and reopen or click a refresh button.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
fixed in https://github.com/microsoft/azuredatastudio/pull/18890
