### ISSUE TITLE
When applying schema compare changes to a project, result from tools service says success despite error message

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17786]
Comparing two sql projects, and applying changes: result object from tools service says it  succeeded, but there's an error message.  Files appear to be getting created on disk (via DacFx), but the failure occurs before they can be added to the Sqlproj (possibly why refreshing doesn't occur/appear to do anything)

**Comment by Benjin** [comment]
Unable to repro currently.  Need to save more details about the specific project/setup that caused this issue.

**Comment by kisantia** [comment]
Closing because I think this was fixed in https://github.com/microsoft/azuredatastudio/pull/18532 and there haven't been any other reports of this
