### ISSUE TITLE
Sharing custom snippets

### ISSUE THREAD

**Issue by Janneman96** [microsoft/azuredatastudio#17793]
I'd like to share SQL snippets with my colleagues through git. But I don't want a git repository in my C:\Users\[user]\AppData\Roaming\azuredatastudio\User\snippets folder. I'd like to reference a snippet file in another folder.

Can you change Azure Data Studio so I can add references to existing snippet files, which are not in the users folder?

Example solutions:
- add the option to choose an existing snippets file (on the whole C disk) instead of creating a new one
- add a configuration option in the json file where you can reference an external snippets file

**Comment by Charles-Gagnon** [comment]
We (being a fork of VS Code) support user snippet files which can be placed in a workspace : https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

So the workspace would contain the snippet definition file(s) that could then be stored in git.
