### ISSUE TITLE
*Issue* Cannot connect upon opening another file

### ISSUE THREAD

**Issue by ryangatchalian912** [microsoft/azuredatastudio#17802]
Issue Type: <b>Bug</b>

1. Open an SQL file.
2. Connect to an active SQL Server connection.
3. Hit Run.
4. Open another SQL file.
5. Connect to the [same] active SQL Server connection from STEP 2.
6. Hit Run.

Actual Result: Connection in STEP 5 keeps on looping.
Expected Result: It should proceed and connect so I can run STEP 6.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.84GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (29)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
asde-deployment|Mic|0.4.1
azcli|Mic|0.2.0
azuredatastudio-oracle|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.7
azuremonitor|Mic|0.1.4
cms|Mic|0.8.0
dacpac|Mic|1.8.0
datavirtualization|Mic|1.12.0
dsct-oracle-to-ms-sql|Mic|0.1.1
import|Mic|1.5.0
kusto|Mic|0.5.4
machine-learning|Mic|0.11.0
managed-instance-dashboard|Mic|0.4.2
net-6-runtime|Mic|0.1.0
powershell|ms-|2021.8.2
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.13.0
sql-migration|Mic|0.1.10
sql-dw|Mic|0.0.1
azdata-sanddance|msr|3.3.0
sql-prompt|Red|0.2.9
vscodeintellicode|Vis|1.2.1
</details>

**Comment by cssuh** [comment]
closing for not enough info
