### ISSUE TITLE
Remaining .NET Interactive API work

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#17829]
- [x] Resolve problems with internal ExecuteManagers not loading due to missing defaultKernel info @corivera 
- [x] Fix issue with File -> New Notebook command not working
- [x] Implement ADS NotebookCellExecution behavior in adsNotebookController.ts @Charles-Gagnon 

FYI @Charles-Gagnon @chlafreniere

**Comment by corivera** [comment]
Additional tasks for the next set of APIs, once cell execution is checked in.

Additional APIs needed by latest stable version of Dotnet Interactive:

- [ ] vscode.workspace.onDidOpenNotebookDocument
- [ ] vscode.workspace.onDidCloseNotebookDocument
- [ ] vscode.window.activeNotebookEditor
- [ ] vscode.workspace.notebookDocuments
- [ ] vscode.workspace.openNotebookDocument
- [ ] vscode.window.showNotebookDocument

**Comment by corivera** [comment]
And here's some leftover tasks from the previous set of APIs that we might want to look into if we have time.

- [ ] Add more cell execution tests in vscodeNotebookApi.test.ts
- [ ] Check if we need activation events for "onNotebook:*"
- [ ] Fix aliased SQL kernels showing up for non-SQL notebooks
- [ ] Investigate runCell cancellation

**Comment by corivera** [comment]
Interactive has a hard dependency on the Jupyter extension, so we need to add the APIs needed to support that.

- [ ] vscode.notebooks.onDidChangeCellMetadata
- [ ] vscode.notebooks.onDidChangeNotebookDocumentMetadata
- [ ] vscode.notebooks.onDidChangeCellOutputs
- [ ] vscode.notebooks.onDidChangeNotebookCells
- [ ] vscode.notebooks.onDidChangeNotebookDocument
- [ ] vscode.notebooks.onDidChangeCellExecutionState
- [ ] vscode.window.visibleNotebookEditors

**Comment by corivera** [comment]
Looks like vscode.notebooks.onDidChangeNotebookDocument doesn't exist in our repo or in vscode.

**Comment by chlafreniere** [comment]
> Looks like vscode.notebooks.onDidChangeNotebookDocument doesn't exist in our repo or in vscode.

I wonder if this used to exist in a previous version of the vscode notebook API

**Comment by corivera** [comment]
The Jupyter extension is using 1.63, with the vscode repo currently at 1.64, so it must have been around for a short time. I'll check the history.

**Comment by corivera** [comment]
Looks like that method was never part of the extension API. It just looked like it was, since I was searching for things in the vscode.notebooks namespace, and there was a "notebooks.onDidChangeNotebookDocument" that was only an internal Jupyter event.

**Comment by corivera** [comment]
I currently have basic C# notebooks working for .dib files. I need to do a couple of other things still:

- [ ] Enable creating new notebooks from .NET Interactive
- [ ] Fix kernel routing issues when using .NET Interactive in .ipynb files (i.e. commands are being incorrectly routed through our jupyter provider)
- [ ] Enable language coloring for .NET Interactive cells

**Comment by corivera** [comment]
@chlafreniere Should I be putting all these new features behind a preview flag?
