### ISSUE TITLE
Running query to get data scope config fails

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17825]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. open an editor for an instance of SQL Server (mine is a docker container from SQL server 2019 image)
2. Run this query: SELECT * FROM sys.database_scoped_configurations 

Expected: get the result
Actual:
Error: Query failed: Value cannot be null. (Parameter 'key')

I verified this works in October release 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
this is recently introduced by https://github.com/microsoft/sqltoolsservice/pull/1326
