### ISSUE TITLE
Welcome Page: Tooltip Doesn't Show when Hovering Over Preview Info Icon

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#17830]
In previous versions of ADS, when I hovered over the Preview Info icon (top right of the welcome page), I got a nice tooltip. Unfortunately, this tooltip isn't showing for me in RC builds:

![image](https://user-images.githubusercontent.com/40371649/144949758-7176da57-2b73-4a85-abaa-6f58dd36e94b.png)

In 1.33.1, it works as expected:
![image](https://user-images.githubusercontent.com/40371649/144949890-19a55cbc-ec49-4789-8bdf-dae71caa3ea8.png)

**Comment by kburtram** [comment]
We're removed the Preview flag from this feature on that it is GA quality.
