### ISSUE TITLE
PS Integrated Console 'crashes' when trying to run any PS script

### ISSUE THREAD

**Issue by Firmbyte** [microsoft/azuredatastudio#17839]
Opening any PS scrpt and running it, the PS Integrated Console crashes. 

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	powershell.exe
  Problem Signature 02:	10.0.14409.1005
  Problem Signature 03:	584a185c
  Problem Signature 04:	System.Management.Automation
  Problem Signature 05:	10.0.14409.1018
  Problem Signature 06:	5bac3bc0
  Problem Signature 07:	7aae
  Problem Signature 08:	0
  Problem Signature 09:	System.StackOverflowException
  OS Version:	6.3.9600.2.0.0.272.7
  Locale ID:	1033
  Additional Information 1:	d34e
  Additional Information 2:	d34e763b2334d493da43dffdedbbc013
  Additional Information 3:	8a01
  Additional Information 4:	8a014f3d872478b583b3a363b4438989

**Comment by kburtram** [comment]
I wasn't able to repro this by creating a simple test script that echos a string and running in integrated terminal (as shown below).  Are there any additional repro steps that you could provide that would help diagnosis what's happening?

```
PS C:\Users\kburt\Desktop> .\test.ps1
test1
```

**Comment by cheenamalhotra** [comment]
Closing as stale. Not enough info to investigate.

**Comment by Firmbyte** [comment]
There’s been no communication asking for more info.

Regards,
Iain Barnetson
T: 713-492-3460
________________________________

**Comment by cheenamalhotra** [comment]
Pasting as posted by @kburtram above:

> I wasn't able to repro this by creating a simple test script that echos a string and running in integrated terminal (as shown below). Are there any additional repro steps that you could provide that would help diagnosis what's happening?
> 
> ```
> PS C:\Users\kburt\Desktop> .\test.ps1
> test1
> ```
