### ISSUE TITLE
local host

### ISSUE THREAD

**Issue by mannikunamneni** [microsoft/azuredatastudio#17834]
Issue Type: <b>Feature Request</b>

i am not getting local host

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:43:30.222Z)
OS version: Darwin x64 21.1.0
Restricted Mode: No

**Comment by cssuh** [comment]
Hi, can you please specify what your problem is? Are there any error messages you're seeing? https://docs.microsoft.com/en-us/sql/azure-data-studio/quickstart-sql-server?view=sql-server-ver15 here is a quickstart guide for connecting and querying SQL server.
