### ISSUE TITLE
sqlproj deploy to docker container doesn't save the connection profile

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17846]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. open a sql proj
2. right click on project and click publish
3. select publish to new server( container) and click on publish button

Expected:  connection is added to profiles after deploy is finished (show in viewlet)
Actual: connection is available in recent connection but is not added to profiles 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by udeeshagautam** [comment]
By design as of now. Please reactivate if it is affecting any scenarios.
