### ISSUE TITLE
generate project from openapi should use default project save location setting

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#17841]
If the Default Project Save Location is set, it should be an option in the Select project location quick pick

![image](https://user-images.githubusercontent.com/31145923/145111171-2a29f20d-dfdc-412c-8536-a4617d6c7402.png)

**Comment by joshbooker** [comment]
@kisantia are there docs or description of this db project from openApi feature?

**Comment by kisantia** [comment]
unfortunately no docs. This feature was added by @Benjin in this PR #17078, which has a short description

**Comment by kisantia** [comment]
closing as this has been deprioritized
