### ISSUE TITLE
Clicking on  "Manage" button when db is selected from OE opens Server dashboard

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#17844]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Connect to a server
2. Select a db
3. right click and select Manage

Expected: db dashboard 
Actual: it opens server dashboard

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chlafreniere** [comment]
@alanrenmsft would this be in your area?
