### ISSUE TITLE
Right Click on Table > Edit Data (DOES NOT WORK)

### ISSUE THREAD

**Issue by hbycr1** [microsoft/azuredatastudio#17848]
Issue Type: <b>Bug</b>

Right Click on Table > Edit Data (DOES NOT WORK)

This has been intermittent for a while now and is a huge pain when trying to quickly add/edit a row

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-10100F CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.87GB (10.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lewis-sanchez** [comment]
Hi @hbycr1, do you still face this issue when you try to edit table data in Azure Data Studio? Also, when you encounter this error, do you get an error log or call stack that could help troubleshoot this?

**Comment by kburtram** [comment]
Thanks for reporting this issue.  Closing based on previous comment and lack of details needed to repro & investigate further.  Please let us know if you're still impacted by this issue.
