### ISSUE TITLE
Manage Packages wizard: table scrolls to top after selecting an installed package the first time

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#17858]
Steps to Reproduce:

1. Open a Python notebook
2. Open the Manage Packages wizard
3. Scroll down on list of installed packages
4. Click on a package

Expected: The clicked package is highlighted
Actual: The table scrolls to the top and the first package is highlighted

This only happens for the first click. Scrolling and clicking on packages after the first time works fine.

https://user-images.githubusercontent.com/23462877/145234563-f9291345-9c62-4f38-9c86-c3ff27a462a4.mov

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chlafreniere** [comment]
@lucyzhang929 I can't repro this right now. Can you see if you still can?

**Comment by lucyzhang929** [comment]
I am no longer able to repro this as well - will close the issue.
