### ISSUE TITLE
Issue Reporter Doesn't Create Issue on GitHub After Clicking "Preview on GitHub"

### ISSUE THREAD

**Issue by areed1192** [microsoft/azuredatastudio#17857]
- **Azure Data Studio Version:** 1.33.1
- **OS Version:** Darwin x64 21.1.0

**Steps to Reproduce:**

1. Navigate to the "Report Issue" under the "Help" tab.
2. Select "This is a Bug Report"
3. Select "Azure Data Studio" option for the "File On" field.
4. Fill out the "Title" Field.
5. Fill out the "Steps to Reproduce" text box.
6. Check the "Include my System Information" option.
7. Check the "Include my enabled extensions" option.
8. Check the "Include A/B experiment info" option.
9. Click the "Preview on GitHub" button.

Depending on whether you have GitHub opened on your browser, it will make the internet browser active and go to the GitHub website if you currently have it open. If you do not have it opened nothing will happen if you click the "Preview on GitHub" button. I am currently using Microsoft Edge as my browser and have it set as my default browser on my Mac system.

Does this issue occur when all extensions are disabled?: **Yes**

**Comment by Charles-Gagnon** [comment]
@chlafreniere @lucyzhang929 Could one of you try this out on your mac? It seems to work fine for me on my Windows machine.

@areed1192 Could you check your console logs (Help -> Toggle Developer tools -> Console tab) and see if there's any error showing up when you click the button?

**Comment by lucyzhang929** [comment]
I was not able to repro the issue on my mac (default browser is Edge). I had this issue page open on my browser and when I clicked "Preview on GitHub" a new tab was opened successfully with the preview.

**Comment by areed1192** [comment]
@Charles-Gagnon I was unable to see anything when I opened Developer Tools. When I click the "Preview on GitHub" button the console tab remains the same. When I do click the button, it will only go to the existing GitHub page I have open and will not create a new tab like @lucyzhang929 is experiencing.

**Comment by kisantia** [comment]
Closing since I'm not able to repro this on the latest ADS release on macOS 13.5. Please reopen if this is still happening in the latest release
