### ISSUE TITLE
Edit Data editors should have [Edit] or similar indicator in their title

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1785]
- SQL Operations Studio Version:

Steps to Reproduce:
- Edit a table

Expected:
- `Sales.Orders [Edit]` or similar shows up (compare to SSDT and see how it does this)
Actual
- `Sales.Orders_1` shows instead. This is had to distinguish from query windows

**Comment by kburtram** [comment]
Closing older issues.  Thanks for the suggestion.
