### ISSUE TITLE
Save as Excel on Windows doesn't open Excel

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#1786]
- SQL Operations Studio Version:
- OS: Windows

Steps to Reproduce:
Run a query & click Save as Excel button. Fill in path and click OK

Expected:
- Excel appears with the file opened
Actual:
- Excel never opens

This may be machine-specific, but warrants investigation. We use a VSCode API to open files natively and this works for browser paths, but perhaps in this case we need to prompt with more info so excel files open as expected?

**Comment by kburtram** [comment]
There is a now an `Open File` button in the save completed notification window that will launch Excel.
