### ISSUE TITLE
Book tree view scroll not working after opening notebook

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#17875]
- Azure Data Studio Version:
Version: 1.34.0-rc1
Commit: d5a3370b655a53b3f431ac7008ab84ba311d991b
Date: 2021-12-08T20:14:15.444Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 21.1.0

Steps to Reproduce:
1. Open ADS Livesite repo in the Explorer Viewlet
2. `Cmd + p` to open file picker and open the **ASCDiagnostics_SQL** notebook 
3. Go to the Notebooks Viewlet
4. Try scrolling in the Book Tree View

**Comment by MaddyDev** [comment]
@qifahs I looked into the issue and the notebook in question is not in the toc, hence missing from the book tree view and highlight will not work. (But found a bug which lands us in an endless loop trying to find the notebook. I'll address that)
