### ISSUE TITLE
Notebooks: Highlight and Insert Code keyboard shortcut error in Markdown mode

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#17878]
Version: 1.34.0-rc1 (user setup)
Commit: 651f6fdcfc28e07f2ff25b76900fc5b52559a8b8
Date: 2021-12-09T02:01:49.852Z
VS Code: 1.58.0
Electron: 12.0.9
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Windows_NT x64 10.0.22000

Steps:
1. Create new notebook and add text cell
2. Type some text in cell
3. Try to highlight text using keyboard shortcut Ctrl + Shift + h
4. Try to insert code using keyboard shortcut Ctrl + Shift + k

Expected:
Text is highlighted
Code block is inserted

Actual:
![Screen Shot 2021-12-09 at 6 52 46 AM](https://user-images.githubusercontent.com/23462877/145420143-cf9b50eb-8421-4855-ae0a-d93513707619.png)
![Screen Shot 2021-12-09 at 7 09 11 AM](https://user-images.githubusercontent.com/23462877/145421862-574691a2-01b8-49fd-ba8a-c0fcafe07bb3.png)

**Comment by Charles-Gagnon** [comment]
NOT a regression but this is pretty bad functionality wise and is a simple fix so feel we should take this for ask mode.
