### ISSUE TITLE
1.33.1immediately exits on Fedora 35

### ISSUE THREAD

**Issue by camckay** [microsoft/azuredatastudio#17887]
No error message or terminal output. Application starts, and then immediately exits. Version 1.32 runs without issue.

**Comment by camckay** [comment]
The RPM gives no errors on the command line, but running from the tar.gz does.

`$ azuredatastudio
[main 2021-12-09T22:46:51.100Z] window: vscode-file:// protocol is explicitly disabled
[main 2021-12-09T22:46:51.130Z] update#setState idle
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[19523:1209/164652.592182:FATAL:gpu_data_manager_impl_private.cc(415)] GPU process isn't usable. Goodbye.

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 

Unexpected crash report id length
Failed to get crash dump id.
Report Id: 
Illegal instruction (core dumped)
`
Attempted to run with --disable-gpu but that failed as well.

**Comment by camckay** [comment]
So it appears that the application will run when using --no-sandbox.

**Comment by kburtram** [comment]
Thanks for reporting this issue.  I wasn't able to repro with 1.35.1 installed from RPM on a clean Fedora 35 installation.  Please let us know if you're still impacted by this issue on the current release.

**Comment by camckay** [comment]
Yes I am still impacted. So is everyone running Wayland and Nvidia. This is a known issue affecting any apps still running older versions of electron.
