### ISSUE TITLE
Adding connection results in unknown Tenant

### ISSUE THREAD

**Issue by joberume** [microsoft/azuredatastudio#17894]
Please help with triaging: 

- Azure Data Studio Version: December RC1
- OS Version: Windows 10

Form seems to be completed with incomplete/null values -- when user tries to add a connection, Tenant is not recognized. When exercising the tenant dropdown to switch values, it seems to populate the value back in properly. I presume this has something todo with the way values are being populated in the form as there hasn't been any changes in the Kusto side. 

Attn: @JustinMDotNet 

Please view GIF:
![FailedToAddConnetion2](https://user-images.githubusercontent.com/52225468/145649279-b989bce2-3f47-4f3a-97c3-f2890b6dcffe.gif)

**Comment by JustinMDotNet** [comment]
Confirmed in Insiders that this is happening for Sql Connection
![MicrosoftTeams-image](https://user-images.githubusercontent.com/63619224/146069148-c07950a2-804b-4c61-8564-c97bdc3545df.png)
s

**Comment by Charles-Gagnon** [comment]
Is this a regression from the last stable release (1.33)?

**Comment by joberume** [comment]
> Is this a regression from the last stable release (1.33)?

Just confirmed that not, I am able to repro on v1.33. Will remove the December release tag.

**Comment by chlafreniere** [comment]
@kburtram was just chatting with @qifahs and it sounds like a few folks from his team are hitting this. Is there any chance someone from your team could take a look? I believe @joberume mentioned initially that there didn't appear to be changes on the Kusto side.

**Comment by data-marty** [comment]
I hit this today also - any ETA on getting it corrected please?

**Comment by mhammons** [comment]
Ditto:
Version: 1.35.1 (user setup)
Commit: fab63efd307e54c063c8af03474bbb5d77f5fd11 Date: 2022-03-15T18:03:38.261Z (1 wk ago)
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.O
OS: Windows_NT x64 10.0.19042
