### ISSUE TITLE
Temp tables only persist for a very short period

### ISSUE THREAD

**Issue by philipnye** [microsoft/azuredatastudio#17907]
Issue Type: <b>Bug</b>

1. Create a temporary table
2. Attempt to execute a `select` against the temporary table around 10 minutes later. (For the avoidance of doubt: in the same window.)

Result: `Invalid object name '#awarded_contracts' (for example)`.

I'm finding that my temporary tables don't persist very long at all - in some cases, as little as 10/15 minutes.

I wonder if this is related to #10352 (and hence falls under #17047). I mention this as until #10352 was fixed I had frequent problems with my token expiring (`Login failed for user '<token-identified principal>'` error message). Until that point I didn't encounter this issue with my temp tables not lasting very long - though that's possibly because my token used to expire before I could hit this temp table issue.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19041
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (0.89GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/nyep/Institute%20for%20Government/Research%20-%20Data%20science/Projects/Whitehall%20Monitor/Contracts_Data|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0
azdata-sanddance|msr|3.3.0
vscode-todo-highlight|way|1.0.4

</details>

**Comment by alanrenmsft** [comment]
the temp tables will be disposed when the session is closed, this feature is related to the Azure Authentication, @cssuh , not sure how are you handling it, we should not only refresh the token when it is near expiration but also try to keep the session id the same.

**Comment by kburtram** [comment]
Closing based on the merged PR referenced above.  Please let us know if you're still impacted by this bug.  Thanks!
