### ISSUE TITLE
Query failed on basic select query

### ISSUE THREAD

**Issue by unlock21** [microsoft/azuredatastudio#17926]
Issue Type: <b>Bug</b>

----
```
query: SELECT * FROM <TABLENAME>
```
```
result: Query failed: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
```

> the same query works fine in azuredatastudio 1.33.1. I've had this issue for about 3 days on insider, updating everyday.

----

Azure Data Studio version: azuredatastudio-insiders 1.34.0-insider (568b62b903546dfe7f01b17c66001896c9aa725c, 2021-12-15T06:31:53.132Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.89GB (20.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.47.0
dacpac|Mic|1.9.1
import|Mic|1.5.0
profiler|Mic|0.12.1
sql-assessment|Mic|0.6.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this with a basic query myself, how many rows does the table have?

**Comment by kburtram** [comment]
@unlock21 is this happening for all queries?  or just with particular tables/views?  If it's only particular views/tables is there anything noteworthy that would help us determine what's happening?  Thanks for reporting this!

**Comment by unlock21** [comment]
CREATE TABLE [dbo].[TEST](
	[Subtotal] [money] NULL
)
SELECT Subtotal FROM TEST
INSERT INTO TEST (Subtotal) VALUES (1)
SELECT Subtotal FROM TEST -- ERROR
UPDATE TEST SET Subtotal = NULL
SELECT Subtotal FROM TEST
UPDATE TEST SET Subtotal = 1
SELECT Subtotal FROM TEST -- ERROR

CREATE TABLE [dbo].[TEST2](
	[Subtotal] [money] NOT NULL
)
SELECT Subtotal FROM TEST2
INSERT INTO TEST2 (Subtotal) VALUES (1)
SELECT Subtotal FROM TEST2 -- ERROR

So it looks like it's erroring out when a money type column has a value.

@Charles-Gagnon @kburtram Sorry I didn't have that specified before, didn't look to far into it :)

**Comment by alanrenmsft** [comment]
@unlock21 thanks! looks like the money type is causing problem, I'll look into that

**Comment by kburtram** [comment]
Approving for Dec release due to impact to critical use case.

**Comment by kburtram** [comment]
@unlock21 thanks for reporting this issue on the insiders build!  This would have certainly resulted in a hotfix to the Dec release.  We'll be looking at our related test cases to understand why this wasn't caught earlier.  Tomorrow's insider and Dec release shouldn't be impacted by this issue.

**Comment by unlock21** [comment]
Everything looks good! Thank you for getting that fixed so quick. You all are the best!
