### ISSUE TITLE
Cannot even connect to simple database connection from inside the query window

### ISSUE THREAD

**Issue by devoneonline** [Microsoft/azuredatastudio#1792]
Issue Type: <b>Bug</b>

Cannot even connect to simple database connection from inside the query window

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@devoneonline I wasn't able to repro this issue.  Did you run into a specific issue when clicking the "Connect" button in the Query Editor?

![screen](https://user-images.githubusercontent.com/599935/42113156-24e15acc-7b9f-11e8-9077-b9275b51c9ef.png)

**Comment by devoneonline** [comment]
Hi Karl,

I downloaded the latest sql operation studio, which ever was available for
download.

I clicked on the same button mentioned in the screenshot, when entered
details for the local sql server express with windows authentication.

It never connects ..

Please let me know if more information is needed.

Thanks & Regards,
Dev

**Comment by kburtram** [comment]
@devoneonline are you still hitting this issue?  If so, could you please check if there are any error messages in the `Help -> Developer Tools` Console window?

**Comment by anthonydresser** [comment]
Going to close due to inactivity. Feel free to reopen if you continue to see this.
