### ISSUE TITLE
Outdated link to release archive

### ISSUE THREAD

**Issue by MiRacLe-RPZ** [microsoft/azuredatastudio#17939]
- Azure Data Studio Version: 1.34.0

Steps to Reproduce:

1. https://github.com/microsoft/azuredatastudio/releases/tag/1.34.0 

2. Linux TAR.GZ (https://go.microsoft.com/fwlink/?linkid=2183277)

3. curl -I "https://go.microsoft.com/fwlink/?linkid=2183277"
HTTP/1.1 302 Moved Temporarily
Location: https://azuredatastudio-update.azurewebsites.net/1.33.1/linux-x64/stable

1.33.1 <> 1.34.0

**Comment by Charles-Gagnon** [comment]
Thanks for the report @MiRacLe-RPZ - we had to rollback the release temporarily while we resolve an issue. The links should be corrected once we've verified things are good. For the time being those links pointing to 1.33.1 is correct. 

Let us know if this is a blocking issue for you.
