### ISSUE TITLE
Can't connect to an encrypted database

### ISSUE THREAD

**Issue by rsilvabcib** [microsoft/azuredatastudio#17945]
Issue Type: <b>Bug</b>

Instance is AlwaysEncrypted 
Database has encrypted columns in some tables.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.70GB (3.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
Can you provide more details on what you're observing?  Is the connection failing to be established?  Or the encrypted columns are being show as binary?  Also, have you set the `Always Encrypted` option to `True` in the Advanced Dialog?

**Comment by cheenamalhotra** [comment]
Verified: Encrypted data is decrypted appropriately when 'Always Encrypted' is set to 'Enabled' on the connection advanced options. Closing issue as no further details available.
