### ISSUE TITLE
Right Click for Top 1000 not working

### ISSUE THREAD

**Issue by amigosnw** [microsoft/azuredatastudio#17941]
Issue Type: <b>Bug</b>

After making a valid connection to a database instance, our Developer attempts to do a 'Select top 1000' from the right click context menu and there is no response or query window opening up. We ARE able to open a separate query window and type the statement and it renders results.... This clearly appears to be a bug.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alanrenmsft** [comment]
@amigosnw what type of server were you connected to? and also how long did you wait?
