### ISSUE TITLE
STRING_SPLIT function call is incorrectly reported as a syntax error

### ISSUE THREAD

**Issue by markashleybell** [microsoft/azuredatastudio#17960]
- Azure Data Studio Version: `1.34.0`
- OS Version: Windows 10 Pro `21H1`  build `19043.1348`  with Windows Feature Experience Pack `120.2212.3920.0`
- Database: Microsoft SQL Server 2019 (RTM-GDR) (`KB4583458`) - `15.0.2080.9` (X64) Developer Edition (64-bit)
- Database Compatibility Level: `130`

Steps to Reproduce:

Write a T-SQL query which uses the `STRING_SPLIT` function ([reference](https://docs.microsoft.com/en-us/sql/t-sql/functions/string-split-transact-sql)). 

The `STRING_SPLIT` call is reported as a syntax error, when it clearly isn't, because executing the query works perfectly:

![image](https://user-images.githubusercontent.com/483470/146506721-c465b4b0-1f9f-4b0d-a7ac-723d45866b88.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by chlafreniere** [comment]
This issue is known and fixed in the latest version of SqlParser. @Charles-Gagnon and @alanrenmsft FYI. Doesn't look like a new version of the SqlParser nuget package has been created yet that STS can consume.

**Comment by alanrenmsft** [comment]
put this in Feb milestone to follow up on getting the latest parser for STS.
