### ISSUE TITLE
Creating items follow there own placement, instead of SSDT

### ISSUE THREAD

**Issue by mverbaas** [microsoft/azuredatastudio#17963]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a project in SSDT
2. Import database in project
3. This (by default) creates a schema/object folder structure (dbo/tables/tablename.sql)
4. Opening the project with VSCode/Azure Data Studio and right click tables folder (node) new item -> table

This creates a tables folder in the root of the project, instead in the tables folder that already exists

Does this issue occur when all extensions are disabled?: Yes

**Comment by adriennn** [comment]
I'm seeing the same behaviour after opening a project that was created in Azure Data Studio with Visual studio. In VS, the functionality works as expected (items created where right-clicked) but in both ADS and VS Code, the items are created at the root of the project.

**Comment by kisantia** [comment]
looks related to #11026

**Comment by kisantia** [comment]
sql database projects 0.14.1 has been released with the fix. Thanks for reporting this issue!
