### ISSUE TITLE
Unterminated comment causes query not to be sent to server.

### ISSUE THREAD

**Issue by cczen** [microsoft/azuredatastudio#17967]
Issue Type: <b>Bug</b>

1. new query 
2. enter an unterminated comment anywhere in the editor:  select 'test' /* test
3. execute query

Expected Results:
Server returns: Missing end comment mark '*/'.

Actual Results:
Azure Data Studio shows in Messages:

Execution failed due to an unexpected error: 
	Could not find the resource "Microsoft.SqlTools.ManagedBatchParser.Localization.SR.resources" among the resources "Microsoft.SqlTools.ManagedBatchParser.SR.resources" embedded in the assembly "Microsoft.SqlTools.ManagedBatchParser", nor among the resources in any satellite assemblies for the specified culture. Perhaps the resources were embedded with an incorrect name.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (16.22GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by smartguest** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/18205
