### ISSUE TITLE
Deleting a folder that contains a file fails

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#17965]
Platform: macOS

Repro:
1. Create a new project
2. Create a folder in the project
3. Create a script in the folder
4. Delete the folder containing the script
5. When you see the prompt "would you like to delete <folder> and all of its contents?", confirm yes.

Expected:
    Folder deletes

Reality:
    Error: "Unable to locate 'Delete' target: '/DeleteTest/MyFolder'"

Notes:
* If the folder you're trying to delete contains other folders (but no files!) then it succeeds.

**Comment by nahk-ivanov** [comment]
Might be a duplicate of #14440

**Comment by Benjin** [comment]
Yup, looks like it.
