### ISSUE TITLE
Can't change python kernel

### ISSUE THREAD

**Issue by muthugit** [microsoft/azuredatastudio#17964]
Issue Type: <b>Bug</b>

I've created notebook with default python environment. But after that, I can't change the environment to another python.

Note: I am using Mac

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 18.7.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by chlafreniere** [comment]
@lucyzhang929 can you help here?

**Comment by lucyzhang929** [comment]
Hi @muthugit,

Are you trying to change the Python installation through the Configure Python for Notebooks wizard?

Could you provide more specific steps and any error messages you see?

**Comment by chlafreniere** [comment]
Closing this for now as we need more logs to debug further. Please reactivate if you are able to provide logs, @muthugit. Thanks!
