### ISSUE TITLE
SQL Server Profiler Fails to create new session. 

### ISSUE THREAD

**Issue by williammsft** [microsoft/azuredatastudio#17975]
Issue Type: <b>Bug</b>

The SQL Server Profiler Extension fails to create a new session. This just appears to be a limit of how the sessions are being created due to a specified buffer size that ends up being smaller than the minimum then what Azure SQL DB or even an On Prem server needs based on the installed RAM. A high amount of RAM installed will cause the problem. 

Steps to Reproduce.

1. 	Open Azure Data Studio.
2. 	Make sure to have the Profiler v0.11.0 installed or the Admin Pack for SQL Server 0.0.2.
3. 	Once installed connect to an Azure Database or any other type of SQL Server with a large amount of memory.
        a.	(Any tier or server with 256GB of memory should do)
5. 	Press ALT+P or right click on the instance/AzureDB and select Launch Profiler. 
6. 	Chose Standard_Azure if on AzureDB or Standard_OnPrem/TSQL_OnPrem if on a on premise server.
7. 	Here the error "Failed to start session: An exception occurred while executing a Transact-SQL statement or batch." will occur. 

If you run the code it is trying to do in Azure Data Studio 1.34.0 or in SSMS 18.10 in a query window it will still cause the error similar to "The specified buffer size is less than the minimum size. The minimum allowed size is 16986060 bytes". (Code below). Either removing the MAX_MEMORY option or setting it to a level higher than that 16986060 bytes in this example it will work fine. So setting to 16,588 KB works. What would seem to need to be done here is either remove the options, or give the user an option to select the size of the buffer allowed to prevent this from happening as that buffer size differs depending on how much RAM is on the system itself. That buffer is not based on what SQL is using or what is allocated to SQL with a max memory setting. 

	CREATE EVENT SESSION [ADS_Standard_Azure] ON DATABASE ADD EVENT sqlserver.attention (ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.database_id, sqlserver.username, sqlserver.query_hash, sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system], (0))))
	    ,ADD EVENT sqlserver.existing_connection (SET collect_options_text = (1) ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.username, sqlserver.session_id))
	    ,ADD EVENT sqlserver.LOGIN (SET collect_options_text = (1) ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.username, sqlserver.session_id))
	    ,ADD EVENT sqlserver.logout (ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.username, sqlserver.session_id))
	    ,ADD EVENT sqlserver.rpc_completed (ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.database_id, sqlserver.username, sqlserver.query_hash, sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system], (0))))
	    ,ADD EVENT sqlserver.sql_batch_completed (ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.database_id, sqlserver.username, sqlserver.query_hash, sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system], (0))))
	    ,ADD EVENT sqlserver.sql_batch_starting (ACTION(package0.event_sequence, sqlserver.client_app_name, sqlserver.client_pid, sqlserver.database_id, sqlserver.username, sqlserver.query_hash, sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system], (0)))) ADD TARGET package0.ring_buffer (
	    SET max_events_limit = (1000)
	    ,max_memory = (51200)
	    )
	    WITH (
	            MAX_MEMORY = 8192 KB
	            ,EVENT_RETENTION_MODE = ALLOW_SINGLE_EVENT_LOSS
	            ,MAX_DISPATCH_LATENCY = 5 SECONDS
	            ,MAX_EVENT_SIZE = 0 KB
	            ,MEMORY_PARTITION_MODE = PER_CPU
	            ,TRACK_CAUSALITY = ON
	            ,STARTUP_STATE = OFF
	            )

Extension version: 0.11.0
Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (12.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by manshahi** [comment]
i have faced this issue today. when i press Alt-P to open SQL Server Profiler
SQL Server Version: 16.0.1000.6
Azure Data Studio: 1.43.0
SQL Server Profiler :  0.12.2
An exception occurred while executing a Transact-SQL statement or batch. ---> The specified buffer size is less than the minimum size. The minimum allowed size is 11759580 bytes.
