### ISSUE TITLE
can't open Extensions

### ISSUE THREAD

**Issue by rscottparker** [microsoft/azuredatastudio#17978]
Issue Type: <b>Bug</b>

go to extensions and get error 'Extension: SQL Server Import': Unexpected token < in JSON at position 0.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6150 CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
azuredatastudio-oracle|Mic|0.1.0
net-6-runtime|Mic|1.0.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.12.0
sql-prompt|Red|0.2.9
sql-search|Red|0.4.1
db-snapshot-creator|sea|0.1.0

(2 theme extensions excluded)

</details>
<!-- generated by issue reporter --
![azure_studio_error](https://user-images.githubusercontent.com/10632722/147923013-611a6515-9048-429f-9b29-871cb4c691b1.PNG)
>

**Comment by Charles-Gagnon** [comment]
Are you still seeing this issue? Typically when seeing something like this it's due to a network related issue (error downloading the gallery metadata).

If you still are then can you try browsing to https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json to see if you're able to access it directly yourself?

**Comment by rscottparker** [comment]
It’s fine now. Thanks!!

Sent from my iPhone

On Jan 4, 2022, at 3:29 PM, Charles Gagnon ***@***.***> wrote:

﻿

Are you still seeing this issue? Typically when seeing something like this it's due to a network related issue (error downloading the gallery metadata).

If you still are then can you try browsing to https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fsqlopsextensions.blob.core.windows.net%2Fmarketplace%2Fv1%2FextensionsGallery.json&data=04%7C01%7C%7C61e6c74b34b749ec408808d9cfc0ec4a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769249772871827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=WZjLcrTLyx1qa%2BVMEikfbBSv%2FlReU9oc4S1UISusJks%3D&reserved=0> to see if you're able to access it directly yourself?

—
Reply to this email directly, view it on GitHub<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fazuredatastudio%2Fissues%2F17978%23issuecomment-1005147716&data=04%7C01%7C%7C61e6c74b34b749ec408808d9cfc0ec4a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769249772871827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Tx2tZLqlGKAPALxC8C%2FWLXVbRZ80VjT4AxoCPyxV8dg%3D&reserved=0>, or unsubscribe<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACRD4EQEWZ7CUMR3LDDZQJDUUNKC5ANCNFSM5LE7P3UQ&data=04%7C01%7C%7C61e6c74b34b749ec408808d9cfc0ec4a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769249772871827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=O%2FkJ9FjC%2F43S1i2bpOG8YrQvHXFHm5q8dDnaHkjQG24%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7C%7C61e6c74b34b749ec408808d9cfc0ec4a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769249772871827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I39CuOlmT4%2BDkxEnqWwrgdOdnjOAGtoEwx8Tr67EUjU%3D&reserved=0> or Android<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7C%7C61e6c74b34b749ec408808d9cfc0ec4a%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637769249772871827%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=I6rCRnj1CvBjQID27ewBXikD2nwCt4hpY58%2Bid7BcaY%3D&reserved=0>.
