### ISSUE TITLE
Dragging column into query window includes schema

### ISSUE THREAD

**Issue by KathiKellenberger** [microsoft/azuredatastudio#18004]
Issue Type: <b>Bug</b>

Open a Query window and connect to AdeventureWorks database 
Type in 
SELECT 
FROM HumanResources.Department
In the Connections window, find the HumanResources.Department table in AdventureWorks. 
Expand to see the Columns folder. 
Drag the Columns folder into the Query window and release after the word SELECT. 
I expect to see a list of comma delimeted columns, but instead I see Schema.Columns. To run the query, I would need to remove the schema from each column name.

SELECT [HumanResources].[DepartmentID],[HumanResources].[Name],[HumanResources].[GroupName],[HumanResources].[ModifiedDate]
FROM HumanResources.Department;

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (20.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.12.0

</details>

**Comment by Charles-Gagnon** [comment]
@cssuh
