### ISSUE TITLE
VSCode Merge breaks Mac Build

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#18003]
- OS Version: OSX Monterey 

Steps to Reproduce:

Developing on Mac for ADS.
1. Pull latest from main 
2. Run Yarn 
3. See Playwright error.

I see that the version we use for playwright is 1.12.3 and there was an issue regarding this on their repo recently as well which is fixed but requires the new version of playwright: https://github.com/microsoft/playwright/issues/7555

It looks like playwright fixed this issue here: https://github.com/microsoft/playwright/commit/3c7d2aae6a0596df717239d24b60ba3702f5fdb8

cc: @Charles-Gagnon

**Comment by Charles-Gagnon** [comment]
The error in the linked issue is different than the issue you showed me (please include that in the bug description). Is there any reason that you think they're related other than the linked issue is talking about MacOS12?

VS Code is still on 1.17.1 and I would be very surprised if they were just ignoring this issue so I assume that there's an update between our version (1.12.3) and 1.17.1 that fixes it.

I can't really help here though as I don't have a mac to test with...

**Comment by VasuBhog** [comment]
Updated comment - I can update to 1.17.1 to be on par with VS Code then.
