### ISSUE TITLE
Standard kernel timeout error appearing every time a Notebook is opened

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18022]
1. Create new Notebook
2. Wait 30sec

These errors appear in the console

![image](https://user-images.githubusercontent.com/28519865/148606496-0b8b5773-ae8f-433e-92ec-c3cc2917522e.png)

**Comment by chlafreniere** [comment]
Just as one data point, I have the Kusto extension installed. Unclear if this is related or not, since @lucyzhang929 doesn't have it installed on her machine.
