### ISSUE TITLE
Links to files not working in Notebooks

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#18021]
Steps to Reproduce:

1. Create a link to another notebook or markdown file in a text cell
2. Click on link

Expected: File opens in new tab
Actual: File does not open

**Comment by VasuBhog** [comment]
Able to repro on Mac for both Absolute Links and Relative. Creates link, but does not open - same error.

**Comment by lucyzhang929** [comment]
The links are only broken on mac and not windows. I added a breakpoint in the `onclick` method [here](https://github.com/microsoft/azuredatastudio/blob/529e4fe0ded02f69fc56b3553b565127d608903d/src/sql/workbench/contrib/notebook/browser/cellViews/linkHandler.directive.ts#L46) and on mac, when the link is clicked, the scheme is `vscode-file` while on windows, the scheme is `file`. @Charles-Gagnon do you have any ideas as to why the scheme for the same file would be different on different platforms?
