### ISSUE TITLE
Registered CMS servers aren't displaying

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18030]
Latest from main (stable 1.34 seems to work fine)

Even after adding a new server registration nothing shows up in the tree

![image](https://user-images.githubusercontent.com/28519865/148624796-50a83c19-a049-4f77-9010-249976d42416.png)

**Comment by abist** [comment]
What OS is this? It seems to be fine on MacOS.

![Screen Shot 2022-02-08 at 10 20 16 AM](https://user-images.githubusercontent.com/6411451/153051085-55db92e5-3d6f-4477-8dbb-48e1256aaafe.png)

**Comment by Charles-Gagnon** [comment]
Doesn't seem to repro for me anymore
