### ISSUE TITLE
Preview of markdown files not showing

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#18048]
Opening preview of markdown files results in web view loading error.

Error loading webview: Error: Could not register service workers: InvalidStateError: Failed to register a ServiceWorker: The document is in an invalid state.

Version: 1.35.0-insider
Commit: c84cb8409b298c88aafb9a35c5c8f12a7aa2fc42
Date: 2022-01-10T06:39:51.236Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.1.0

**Comment by chlafreniere** [comment]
This issue doesn't repro any longer, so closing for now.
