### ISSUE TITLE
Add confirmation to update project in update project dialog

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#18077]
It would be nice to have a prompt for the user to confirm that they want to update their project in case they want to change their mind, like when clicking the schema compare apply button:
![image](https://user-images.githubusercontent.com/31145923/149413749-9a9f3974-16b6-4a70-9d51-d520e4658371.png)

**Comment by Benjin** [comment]
For "Apply" option in Update Project dialog
