### ISSUE TITLE
Project update says success but build and schema compare failed

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#18078]
![image](https://user-images.githubusercontent.com/31145923/149414280-7b681594-c8dd-4544-97b2-58455c1f0631.png)

**Comment by Benjin** [comment]
@kisantia Can you send/attach the project you used to repro this?  I haven't hit this one my end.

**Comment by kisantia** [comment]
apply schema compare changes failed with wide world importers and a blank project.

**Comment by Benjin** [comment]
Still investigating the fundamental cause, but Tools Service is correctly sending a failed task result.  ADS's task display recognizes that it failed, but when the result object emerges from the service back to the extension, the sucess boolean is set to true (despite the error message being preserved).
