### ISSUE TITLE
Index gets dropped when updating project from database

### ISSUE THREAD

**Issue by zijchen** [microsoft/azuredatastudio#18076]
Steps to Reproduce:

1. Create new sqlproj, add a Table1.sql with following script:
```tsql
CREATE TABLE [dbo].[Table1] (
    [Id] INT NOT NULL PRIMARY KEY,
    [Col1] NVARCHAR (100) NOT NULL
);
GO

CREATE INDEX IX_Col1 ON Table1 (Col1);
GO
```
2. Publish to database
3. Delete Table1.sql from project
4. Update project from database, the table definition is restored but the index creation script is missing

**Comment by zijchen** [comment]
Schema compare from the restored sqlproj vs the database still picks up the difference

**Comment by kisantia** [comment]
tracking this as part of #19392
