### ISSUE TITLE
schemaCompare with project has target fails to apply changes

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#18079]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. opened a sqlproject I created from adventure works
2. open schema compare and set project as target
3. use a db with a table as source
4. select option to not drop objects in target if doesn't exist in source
5. click on apply

Expected: one table should get created
Actual: error

![image](https://user-images.githubusercontent.com/17187348/149414386-e8cb3ab8-5aed-4608-b65d-565d303a3fb8.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
Update Project hasn't been released in stable yet, so moving this bug to April.

**Comment by udeeshagautam** [comment]
@Benjin is this fixed? I am seeing this scenario failing for today's build too. the error is different for me though - index out of range.

**Comment by kisantia** [comment]
These errors should be fixed, but the "Drop objects not in source" option doesn't look like it's getting honored. I opened a separate issue for this #19730.
