### ISSUE TITLE
Can't save query

### ISSUE THREAD

**Issue by nord-** [microsoft/azuredatastudio#18084]
Issue Type: <b>Bug</b>

Trying to save a query I have open in editor, but it fails with message:
"Promise.allSettled is not a function"

Azure Data Studio version: azuredatastudio-insiders 1.35.0-insider (d4534f875fbc382933131999816b963726dd8afd, 2022-01-14T06:43:54.417Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (13.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0
simple-data-scripter|sea|0.1.6

</details>

**Comment by Charles-Gagnon** [comment]
Looks related to https://github.com/microsoft/azuredatastudio/issues/18047
