### ISSUE TITLE
New notebook prompted to save as json file while saving

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#18088]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a new notebook and edit
2. Close the notebook and choose 'Save' option from the prompt. Notebook's suggested to save as json file instead of ipynb.

![image](https://user-images.githubusercontent.com/12754347/149562814-b5b71724-9e80-461e-9a64-82b9f4da06dc.png)

**Comment by chlafreniere** [comment]
@chlafreniere to verify 😄

**Comment by chlafreniere** [comment]
@kenvanhyning can repro this still on Windows (both when doing save as for new or existing notebooks). Reopening as a result.

**Comment by chlafreniere** [comment]
This is a Windows 11 issue. Save dialog doesn't populate the extension by default, and the file type just says "JSON".

**Comment by Charles-Gagnon** [comment]
Closing as the issue here is still fixed, a slightly different issue was what Ken was seeing

https://github.com/microsoft/azuredatastudio/issues/18310
