### ISSUE TITLE
Enable border customization for ButtonComponent

### ISSUE THREAD

**Issue by languy** [microsoft/azuredatastudio#18105]
**Is your feature request related to a problem? Please describe.**
I'm using an `ButtonComponent` of type `Informational` with a white background.
The button borders are not visible and it is not possible to customize the borders.
<img width="243" alt="image" src="https://user-images.githubusercontent.com/21954022/149746691-fc4eae33-ea85-4d47-8b1a-306270c4389d.png">

**Describe the solution or feature you'd like**
Enable customizing the button borders via CSS. The UI design calls for some shadowing.

**Describe alternatives you've considered**
Change background color to non-white.

**Additional context**
Here's how the UI design looks like:
<img width="270" alt="image" src="https://user-images.githubusercontent.com/21954022/149745716-b77f0f36-001e-4622-8be1-641e79fcd38c.png">

**Comment by alanrenmsft** [comment]
@languy  I will take a look.

**Comment by alanrenmsft** [comment]
@languy you can use the CSSStyles to specify the border, see example below.
```TypeScript
view.modelBuilder.button().withProps({
			buttonType: azdata.ButtonType.Informational,
			...
			CSSStyles: {
				'border-color':'red',
				'border-style':'solid',
				'border-width':'1px'
			}
		}).component();
```

since you are using custom color, you have to handle the theme change event and assign the proper color for the theme.
```
		vscode.window.onDidChangeActiveColorTheme(e=>{
			buttonContainer.updateCssStyles({
				...
			});
		});
```
