### ISSUE TITLE
When exporting a query result as a CSV or other file type, a filename is not populated by default.

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18115]
Steps to Reproduce:
1. Run a query in a SQL code cell or query editor.
2. Try to export the results as a CSV.
3. Save the file. The save dialog will not have any filename populated by default.
4. Try to export the results again. A default filename is now provided in the dialog (e.g. Results.xml).

**Comment by chlafreniere** [comment]
@corivera I'm unable to repro this (both through query editor + notebooks). Here's what I see on latest insiders, for Mac and Windows:

![image](https://user-images.githubusercontent.com/40371649/150283030-1d09ef0f-89e4-43cb-ac97-007a9da8ea52.png)

![image](https://user-images.githubusercontent.com/40371649/150282992-7f07c1e6-c5a6-4639-9dd4-563b25c75bf8.png)

Can you still repro on your machine on latest?

**Comment by corivera** [comment]
Yeah, it still repros for me on Windows. I'm re-opening ADS every time, in case it's relevant.

**Comment by Charles-Gagnon** [comment]
I can repro this as well (on both stable 1.34.0 and insiders)

![image](https://user-images.githubusercontent.com/28519865/150403854-abe29c83-6407-44a6-b9b4-2c06a3da7121.png)

If I save the CSV then it populates with `Results.csv` as expected (even for new Notebooks)
