### ISSUE TITLE
Connections not working after Azure AD user password reset

### ISSUE THREAD

**Issue by mjmhall1** [microsoft/azuredatastudio#18143]
Issue Type: <b>Bug</b>

I had to change my Azure AD password and since then I have had connection issues. I have removed and re added my account in Data Studio which has allowed me to create new query windows that work but still getting intermitent issues.

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (4.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.14.1
azdata-sanddance|msr|3.3.0
sql-search|Red|0.4.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alexbousquet** [comment]
You haven't specified the error message you're receiving, but I wouldn't be surprised it if was related to #12165.

You can follow the steps over there, which worked for me when nothing else would. I just commented over there with a PowerShell script to automate the process.

**Comment by Charles-Gagnon** [comment]
@mjmhall1 Did the instructions linked help you at all?

**Comment by Charles-Gagnon** [comment]
@cssuh FYI - have you had a chance to add that process to our wiki yet?

**Comment by mjmhall1** [comment]
> 

I managed to get my connection working by going to the user icon and removing my linked account, then restarting data studio and reentering my linked account details.

**Comment by Charles-Gagnon** [comment]
Thanks for the update, glad things are working again for you. I'll close this now since the issue seems to be resolved - we'll keep working on tracking down these problems to avoid needing to do this again in the future though!
