### ISSUE TITLE
Columns of type 'hierarchyid' display incorrectly as unicode strings

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#18154]
Repro steps:
1. Select a column of type hierarchyid.  For example from the Employee table in AdventureWorks.

Expected: Value displayed as hex value.

Actual: Value displayed as unicode string.

![image](https://user-images.githubusercontent.com/599935/151041644-8d72ec88-ace1-4ddf-903d-fe5f87cbb3a8.png)

**Comment by jemackay** [comment]
Just upgraded to the latest version of ADS v1.35.1 (don't know old version) and had the same problem. Any updates on this? I am forced to use MS SQL Management Studio until this is fixed.

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Is this one of the ones you've fixed in STS recently?
