### ISSUE TITLE
I could not connect with azuredatastudio after I installed it. what is the proplem?

### ISSUE THREAD

**Issue by MohammedAliHu** [microsoft/azuredatastudio#18152]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Can you please provide more information about your issue? Are you getting any errors and what steps are you taking that aren't working as you expect.
