### ISSUE TITLE
Add SQL binding connection string doesn't include password

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18166]
1. Add SQL binding to an existing Azure Function
2. When prompted choose "Select Connection" and select a connection that uses SQL auth

The connection string is added successfully, but the password is set to ****** so it can't be used until the user updates it. (even if the password is saved)

There are a couple potential things we could do here to make the experience better : 

1. Warn the user that they need to enter the password manually (preferably with a link to open the file for them)
2. Prompt the user for the password again and then insert it (should verify that it's correct before doing this). If they choose not to enter the password that should be fine as long as they are told they will need to enter it later. 
3. If the password is saved then insert it directly

**Comment by dzsquared** [comment]
I'd prefer not option 3, as we'd be pulling the password into an easily-accessible plain text file.
