### ISSUE TITLE
Add SQL binding connection string has sqlops Application Name

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18165]
1. Add SQL binding to an existing Azure Function
2. Choose "select connection" and select a connection from the list

The connection string is added successfully but it has the `Application Name` field set to `sqlops-connection-string`. While this doesn't really break anything it isn't accurate and shouldn't be included in this context. 

![image](https://user-images.githubusercontent.com/28519865/151247086-2c2c14af-2564-4a5b-9fe8-24e8513aeecb.png)

**Comment by VasuBhog** [comment]
This seems to be due to what we get back from STS, so that change would need to be made there.
