### ISSUE TITLE
Unable to list Oracle Schema details after connecting

### ISSUE THREAD

**Issue by svsr99** [microsoft/azuredatastudio#18175]
Issue Type: <b>Bug</b>

Added new Oracle db connecton after adding Oracle extension. When trying to expand schema, an error pops-up as "Index was outside the bounds of the array." and unable to proceed further. 

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 6, 27|
|Memory (System)|16.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-oracle|Mic|0.1.0
net-6-runtime|Mic|1.0.0
sql-dw|Mic|0.0.1
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
@nahk-ivanov - Do you have a public repo that we can have Oracle extension bugs moved to?

**Comment by nahk-ivanov** [comment]
Not yet. I plan to look into it in the near future. Feel free to assign these to myself in the interim.

cc @benrr101

**Comment by nahk-ivanov** [comment]
Hey,

This should be fixed in v0.1.1 that was just released. Please try again and let us know!

Thanks,
Alex.
