### ISSUE TITLE
Migrate to Azure wizard hanging on list databases

### ISSUE THREAD

**Issue by SreekanthcGitHub** [microsoft/azuredatastudio#18183]
- Azure Data Studio Version: 1.34.0
- OS Version:  Windows 2012 R2
-  Azure SQL Migration extension has been installed on Azure Data Studio
- Issue
-  I am not able to list the databases of source ( Step2) in migrate to azure SQL wizard- it just hung there , I uninstalled/restart the node/resinstalled the azure studio and tried but the issue remains.
- FYI :- I have approximately 1000 databases on SQL instance 
- Appreciate any help to resolve this.

**Comment by Charles-Gagnon** [comment]
@brian-harris @rchlkm
