### ISSUE TITLE
Notebook extension failing on Mac M1

### ISSUE THREAD

**Issue by tmorell** [microsoft/azuredatastudio#18186]
- Azure Data Studio Version: 1.34.0 and 1.35.0-insider
- OS Version: macOS Monterey 12.1 and 12.2

Steps to Reproduce:

1. Unzip azuredtastudio-macos-1.xx.x.zip
2. Copied app to Applications folders.
3. Launched app and granted execute access.
4. Buttons to open or create a book do not work. No error message or information.
5. shift + cmd + p: `Jupyter Books: Create Jupyter Book` throws the following exception:

```
Command 'Jupyter Books: Create Jupyter Book' resulted in an error (Running the contributed command: 'notebook.command.createBook' failed.)
```
ADS works without any issues on a Mac (Intel) following the same steps indicated above.

Does this issue occur when all extensions are disabled?: Yes/No
There are no extensions installed.

**Comment by chlafreniere** [comment]
@barbaravaldez can you think of why this may be happening on M1?

**Comment by barbaravaldez** [comment]
Hi @tmorell, thanks for filing an issue. Do you see a similar error when trying to open notebooks in ADS? 

Also, it would be very helpful if you could provide application and console logs to see what could be causing the issue.

**Comment by barbaravaldez** [comment]
> @barbaravaldez can you think of why this may be happening on M1?

@chlafreniere from the title, I think there might be an issue with the initialization of the notebooks extension, since the opening jupyter notebooks command is failing as well.

**Comment by tmorell** [comment]
Thanks for the prompt response. These are the log files:

[logs-folder.zip](https://github.com/microsoft/azuredatastudio/files/7975626/logs-folder.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/7975627/console.log)

**Comment by alanrenmsft** [comment]
@barbaravaldez @chlafreniere , I just noticed that the resource deployment related extensions are not working on ARM64 macOS because of the notebook extension failed to load.

I chatted with the MySQL extension team, they had a similar issue recently, the need to have a separate build of MySQL Tools Service for ARM64 macOS to include additional packages required

**Comment by alanrenmsft** [comment]
@chlafreniere 
`mainThreadExtensionService.ts:111 Activating extension 'Microsoft.notebook' failed: Command failed: "/Users/jianren/azuredatastudio-python/bin/python3" -c "import platform;print(platform.python_version())"
dyld[6343]: Library not loaded: '/usr/local/opt/gettext/lib/libintl.8.dylib'
  Referenced from: '/Users/jianren/azuredatastudio-python/bin/python3.8'
  Reason: tried: '/usr/local/opt/gettext/lib/libintl.8.dylib' (no such file), '/usr/local/lib/libintl.8.dylib' (no such file), '/usr/lib/libintl.8.dylib' (no such file)`

**Comment by chlafreniere** [comment]
@alanrenmsft I see, thanks. @corivera could we need a different python build to work with ARM-based Macs?

**Comment by corivera** [comment]
Possibly, but it's interesting that this is happening during extension activation. I thought our notebook python instance was only getting loaded when using the Python kernel in an open notebook. Could this be a PATH issue where the azuredatastudio-python bits are messing with the local version of python?

**Comment by alanrenmsft** [comment]
@corivera let me know if you want to use my M1 macbook.

**Comment by corivera** [comment]
Will do

**Comment by corivera** [comment]
Did a bit of testing, and looks like only our provided python package has this problem. Using the existing python instance on MacOS worked fine without any issues. Since Python is included with Macs by default, we can probably document using that as a workaround.
