### ISSUE TITLE
Query results seldom return

### ISSUE THREAD

**Issue by SheldonHage** [microsoft/azuredatastudio#18193]
Issue Type: <b>Bug</b>

Rarely do query results return.   Sometimes query results for one query appear in window for other queries.   Sometimes the results of a SELECT * 1000 being back incomplete columns and wrang data in each column

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@SheldonHage we need some more information in order to identify the issue here.
1. what type of server are you connecting to?
2. network latency between client and sql server.
3. authentication type
4. a recording of the repro.

thanks!

**Comment by alanrenmsft** [comment]
@SheldonHage please reopen when you have the requested information ready so that we can investigate.

**Comment by SheldonHage** [comment]
Problem has been solved with recent updates.   Can no longer reproduce.
