### ISSUE TITLE
[FIXED] - Deepin 15.9 (Debian distro) support

### ISSUE THREAD

**Issue by 0versun** [microsoft/azuredatastudio#1821]
Issue Type: <b>Feature request</b>

Failed to start Sql tools service. 

Steps to Reproduce:

1.     Install latest deepin distro http://cdimage.deepin.com/releases/15.9/deepin-15.9-amd64.iso
2.     Install Sql Operation Studio form deepin app store or directly form vscode site
3.     Install mssql-tools/panda,now 14.0.4.0-1 amd64, Tools for Microsoft(R) SQL Server(R)
4.     Try to run Sql Operation studio
5.     observe result
![deepinscreenshot_sqlops_20180702232212](https://user-images.githubusercontent.com/17294426/42184611-ce8d96c4-7e4e-11e8-8ad7-6b84aaba9769.png)

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:50:31.119Z)
OS version: Linux x64 4.15.0-29deepin-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 3064)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.66GB (0.75GB free)|
|Process Argv|/usr/share/sqlops/sqlops --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by 0versun** [comment]
Hi please close issue, its not reproduce on the new version of deepin distro and new version of azure data studio

**Comment by abist** [comment]
Closing issue as fixed.
