### ISSUE TITLE
intellisense truncates table names with ellipses

### ISSUE THREAD

**Issue by softwareCobbler** [microsoft/azuredatastudio#18211]
**Is your feature request related to a problem? Please describe.**
desired parity with ssms

**Describe the solution or feature you'd like**
Intellisense displays full table name

**Describe alternatives you've considered**
use ssms

**Additional context**
In azure data studio, intellisense for a table name completion looks like (the ellipses are literal, ADS truncates table names)
```
use db;
select * from |
    > some_table_n... <db>.<schema>.<even-shorter-truncated-table-name>
    > some_table_n... <db>.<schema>.<even-shorter-truncated-table-name>
    > some_table_n... <db>.<schema>.<even-shorter-truncated-table-name>
```
In ssms, intellisense for a table name completion looks like:
```
use db;
select * from |
   > some_table_name_with_a_common_prefix_1
   > some_table_name_with_a_common_prefix_2
   > some_table_name_with_a_common_prefix_3
```

Intellisense loses a lot of its value when there are many choices, but the choices all share a prefix and only the common prefix is shown.

**Comment by alanrenmsft** [comment]
@softwareCobbler could you please provide screen shots?

**Comment by alanrenmsft** [comment]
@softwareCobbler thanks for the screen shots.

I took a look and found that it does allow you to expand the detail to a separate tooltip pop up. see the screen recording below. This is a feature we inherited from VSCode. note that the 'Read More' icon is not visible in light theme but the placeholder is there, I will fix it.

![intellisense](https://user-images.githubusercontent.com/13777222/155227890-cbf1ce8b-f4de-4822-ae6c-656690303686.gif)

**Comment by softwareCobbler** [comment]
oh wow, didn't see the little `>` icon. good deal! thanks.

**Comment by alanrenmsft** [comment]
@softwareCobbler  what color theme do you use?

**Comment by alanrenmsft** [comment]
@softwareCobbler  FYI, the icon not visible in light theme issue will be fixed in April stable release. https://github.com/microsoft/azuredatastudio/pull/18529
