### ISSUE TITLE
Can't connect to an Azure SQL Database after upgrading to Windows 11

### ISSUE THREAD

**Issue by Binary-Samurai** [microsoft/azuredatastudio#18213]
![Error](https://user-images.githubusercontent.com/79224995/152404000-957b5fbe-f3f8-43f0-8c25-9946d651e489.jpg)
Issue Type: <b>Bug</b>

I receive an error in Azure Data Studio after upgrading to Windows 11 "Error: Token Retrieval failed with an error. Open developer tools to view the error"

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.72GB (4.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.14.1

</details>

**Comment by Charles-Gagnon** [comment]
@cssuh

**Comment by cssuh** [comment]
Hi @Binary-Samurai, can you please try removing your azure account and then re-adding it?

**Comment by Binary-Samurai** [comment]
My apologies for the delayed response. The suggestion from @cssuh worked as expected
