### ISSUE TITLE
Getting "Unsupported external data source type '6'." 

### ISSUE THREAD

**Issue by ashishmg-gds** [microsoft/azuredatastudio#18235]
- Azure Data Studio Version: 1.32.0
- OS Version: Windows 10

Steps to Reproduce:

1. Created external data sources for reading parquet files in ADLS gen 2
2. Tried `create project from database` and recieving error : 

`Microsoft.Data.Tools.Schema.Sql.SchemaModel.SqlExternalDataSource: Unsupported external data source type '6'.`

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ashishmg-gds** [comment]
This was due to a data source created in source db , which was not queryable, I guess due to snappy.parquet format. After removing the same, its working now

**Comment by asackmann** [comment]
> This was due to a data source created in source db , which was not queryable, I guess due to snappy.parquet format. After removing the same, its working now

Can you give more details, i have the same error. Thanks.
