### ISSUE TITLE
Add keyboard navigation to queryplan graph.

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18285]
Steps to Reproduce:

1. Click on a graph node.
2. Use arrow nodes to navigate between graph nodes.
3. Arrow keys don't work
![image](https://user-images.githubusercontent.com/6816294/153355098-d2cf7514-597e-4bf0-bbc0-59af24b4b988.png)

**Comment by kburtram** [comment]
I don't have a fix available yet, so this no longer meets the bug bar for Feb.  Will move to April.
