### ISSUE TITLE
Add search feature in properties view

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18291]
Currently it can get difficult to search for a property in properties view. Adding a search feature will be helpful here. 
![image](https://user-images.githubusercontent.com/6816294/153356491-e68a8c10-fa5c-4e43-93de-bd485af351af.png)

**Comment by aasimkhan30** [comment]
This feature is not present in insiders.

**Comment by tdoshin** [comment]
![image](https://user-images.githubusercontent.com/72947001/200394479-2c9403a8-0dc0-4d44-8146-980c3089d7e6.png)

Is this what you are referring to? Just confirming @aasimkhan30 @erinstellato-ms

**Comment by erinstellato-ms** [comment]
@tdoshin Not sure of the reference here?
