### ISSUE TITLE
Chart viewer - Copy as image pastes black background

### ISSUE THREAD

**Issue by BartekR** [microsoft/azuredatastudio#183]
- SQL Operations Studio Version: 0.23.6, x64

Steps to Reproduce:
1. Run query that produces numerical results (e.g. SELECT a = 1, b = 2)
2. Click 'View as chart'
3. Click 'Copy as image'
4. Open Paint
5. Paste

The result: image with black background

'Save as image' saves with no problems.

OS Version: Windows 7 Enterprise (6.1.7601)

[EDIT] I'm using "Light SQL Operations Studio (default light)" color scheme.

**Comment by kburtram** [comment]
Cleaning up old issues.  I'm going to close this as "won't fix" for now since we don't plan to address in the next few milestones.
