### ISSUE TITLE
Need to warn users when running on unsupported OS version

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#1831]
We often get error reports from users running on non-support OS versions, such as downlevel macOS. SQL Ops should have a warning or error on startup to notify user that scenario is unsupported.

**Comment by abist** [comment]
We had this feature - https://github.com/Microsoft/carbon/pull/2569
I think it's a regression ever since we isolated the service downloader

**Comment by kburtram** [comment]
Closing older issues.
