### ISSUE TITLE
SQL array results to JSON array (instead of string)

### ISSUE THREAD

**Issue by kuhlaid** [microsoft/azuredatastudio#18325]
Issue Type: <b>Feature Request</b>
I have a column from my SQL query results that prints out the following:
| researcher  | 
| ------------- | 
| [12,3,4]  | 
| [5,3,19]  | 

I then save the SQL query results (above) using the 'Save As JSON' button in the results pane. 

However when I save as JSON, the researcher values are wrapped in quotes like so:
```
[
  {
    "researcher": "[12,3,4]"
  },
 {
    "researcher": "[5,3,19]"
  }
]
```
Ideally values in brackets would be treated as a JSON array when saving as JSON, and the JSON output would look like:
```
[
  {
    "researcher": [12,3,4]
  },
 {
    "researcher": [5,3,19]
  }
]
```

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

**Comment by alanrenmsft** [comment]
this is by design, since the column string typed, it will be serialized as a string.

**Comment by kuhlaid** [comment]
To resolve this after exporting the query results to JSON, I loaded the results in Visual Studio Code and used the following string search and replace to remove the quotes from the JSON.
```
"researcher": "\[(.+)\]"   --- regex search text
"researcher": [$1]          --- replace text
```
