### ISSUE TITLE
Make .vsix of "Schema Compare for Azure Data Studio" available to download

### ISSUE THREAD

**Issue by ojmucianski** [microsoft/azuredatastudio#18346]
Can you please add the .vsix file either here:
https://github.com/microsoft/azuredatastudio/tree/main/extensions/schema-compare
or here:
https://github.com/Microsoft/azuredatastudio/wiki/List-of-Extensions

**Comment by Charles-Gagnon** [comment]
Thanks for catching that @ojmucianski ! I've added it to the list

https://go.microsoft.com/fwlink/?linkid=2143758

This link will be updated as new versions are released so will always be pointing to the latest version available.
