### ISSUE TITLE
No ability to copy object name from Properties window

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18359]
- Azure Data Studio Version:
Version: 1.35.0-insider (user setup)
Commit: 3cfd1d23da0efba022104635b01b22cfa9a08524
Date: 2022-02-14T06:49:59.062Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Execute a SELECT query in ADS with the plan (CTRL + M)
2. View the properties of an object access operator (e.g. scan or seek).
3. The OBJECT information is misaligned, and there is no ability to copy any of the object name (database, table, index) from the window:

![image](https://user-images.githubusercontent.com/98599126/153962703-c726a238-99f7-45c0-ac00-abddce1234cf.png)

4. Within SSMS, the ability to copy the entire object name exists both by selecting the value and then using right-click, and via a pop-up window:

![image](https://user-images.githubusercontent.com/98599126/153962881-0165c540-b124-4c8a-bf10-3553e730ffe1.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by aasimkhan30** [comment]
This was fixed with PR #20208
