### ISSUE TITLE
Information in incorrect location within Properties window for SELECT operator

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18357]
- Azure Data Studio Version:
Version: 1.35.0-insider (user setup)
Commit: 3cfd1d23da0efba022104635b01b22cfa9a08524
Date: 2022-02-14T06:49:59.062Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open a query window and run a SELECT statement, with the plan (CTRL +M)
2. In the plan window, open the properties for the SELECT operator.
3. The values for SET OPTIONS appear above the SET OPTIONS text:

![image](https://user-images.githubusercontent.com/98599126/153961425-b4a3faaa-cffd-438a-8ea0-c368c5b3360e.png)

4. Memory grant information is located above and below the Memory Grant Info tag:

![image](https://user-images.githubusercontent.com/98599126/153961323-4d4b70ff-9e0e-4cca-9249-83738a789736.png)

5. The Wait Stats and Query Time stats information is also misaligned:

![image](https://user-images.githubusercontent.com/98599126/153961544-f696f5b4-fcea-481c-9f26-113014127e9b.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
Fix available.
