### ISSUE TITLE
Provide the ability to copy the Object name

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18358]
**Is your feature request related to a problem? Please describe.**
When viewing a query plan, on the Top Operations pane it would be nice to be able to copy the object name:

![image](https://user-images.githubusercontent.com/98599126/153962060-df4b7eb7-0b1f-413f-8894-b433b8bf95b8.png)

**Describe the solution or feature you'd like**
There are times when troubleshooting and tuning and being able to quickly copy an object name (e.g. an index) makes the next step in troubleshooting easier.

**Describe alternatives you've considered**
I see no other way to copy the object name.

**Additional context**
N/A

**Comment by lewis-sanchez** [comment]
Closing this issue since the bug has been fixed in a previous PR. Here's a gif of copying an object name in the "Top Plans" tab working in Azure Data Studio:

![Execution Plan - Copy Object Name](https://user-images.githubusercontent.com/87730006/193332921-a80011a2-297c-46f6-9c50-0e12e42e06a4.gif)
