### ISSUE TITLE
Langpacks not available for February release.

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#18363]
Langpacks are not currently available for the February release right now, they will need to be added within the next couple of days. Without the langpack port, changes to the strings in ADS won't be translated. (Minor issue where git extension is not localized, but this is due to alterations made for the extension which means it needs to be translated again)

**Comment by Charles-Gagnon** [comment]
@smartguest Assigning to you for Feb release

**Comment by smartguest** [comment]
Langpack source have been merged into February release.
