### ISSUE TITLE
Manage Packages - latest Version pandas is old

### ISSUE THREAD

**Issue by AlexanderWolf-x** [microsoft/azuredatastudio#18367]
Issue Type: <b>Bug</b>

I want to install the latest version of pandas. This is 1.4.1.
But when I search in the Manage Packages Tool, I just get the version 1.1.5.

![image](https://user-images.githubusercontent.com/47870373/154042864-b1dbe312-c521-4a4f-9950-ba876381ba06.png)

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
qpi|joc|0.1.6
agent|Mic|0.48.0
datavirtualization|Mic|1.12.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment]
Hmm, I see the following myself:

<img width="439" alt="image" src="https://user-images.githubusercontent.com/40371649/155436134-64f1c1a2-647a-4e9a-a426-f3156360f822.png">

@AlexanderWolf-x, are you leveraging Anaconda, or vanilla Python?

**Comment by lucyzhang929** [comment]
I am seeing the latest version:
![Screen Shot 2022-04-07 at 1 21 44 PM](https://user-images.githubusercontent.com/23462877/162289492-46691eab-2946-43d8-a810-acee231f2b86.png)

@AlexanderWolf-x  are you still seeing the same issue?

**Comment by corivera** [comment]
This is probably due to the local Python version. According to PyPI, Pandas 1.1.5 is supported for 3.6.1 and above, but for later Pandas versions either Python 3.7 or 3.8 is required. Our manage packages dialog filters out any unsupported package versions in order to prevent failures during the package installation.
