### ISSUE TITLE
Error while creating a new notebook

### ISSUE THREAD

**Issue by ArmandoLacerda** [microsoft/azuredatastudio#18368]
Issue Type: <b>Bug</b>

Cannot read property 'reinitializeContents' of undefined

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (23.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
Closing as we need logs to debug further. Please feel free to reactivate if you can still repro and can provide logs.
