### ISSUE TITLE
Graph edges can be disconnected from source and target in Query Plan

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18360]
Steps to Reproduce:

1. Click explain button on query to generate the show plan graph.
2. Graph edges can be disconnected from source and target by clicking on the edge ends. 
Before:
![image](https://user-images.githubusercontent.com/6816294/153963106-fdbb613c-4e31-41de-adaa-b12dad2497e9.png)
After:
![image](https://user-images.githubusercontent.com/6816294/153963042-7545291f-236e-4e11-a62f-9dac433cb8f3.png)

**Comment by kburtram** [comment]
Fixed in release.
