### ISSUE TITLE
Displaying actual execution plans requires CTRL+M or using the Command Palette for every query execution 

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18371]
**Is your feature request related to a problem? Please describe.**
This is an inconsistency compared to SSMS with enabling actual execution plans.  In SSMS, there is a menu option (Query | Include Actual Execution Plan) which then turns on the actual plan for every query executed in that query window.  In ADS, you have to use CTRL + M every time, or open the Command Palette (right-click, find Run Current Query with Actual Plan) for EACH individual query you want to execute.   

**Describe the solution or feature you'd like**
Provide the ability to enable the actual execution plan for a connection.

**Describe alternatives you've considered**
Note: running

SET STATISTICS XML ON;
GO

and then executing queries does cause the actual plan to show up each time

**Additional context**
N/A

**Comment by aasimkhan30** [comment]
This feature was added in PR https://github.com/microsoft/azuredatastudio/pull/19629
