### ISSUE TITLE
Code cells intellisense not working in untitled notebooks

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#18370]
Steps to Reproduce:

1. Create a new notebook in ADS
2. Add a code cell
3. Wait until SQL kernel is done loading
3. Type 'sql'
4. The suggestion widget never shows up

**Comment by Charles-Gagnon** [comment]
Closing as duplicate - intellisense did usually show up after a time. Issues there are well-known and being tracked in other issues such as https://github.com/microsoft/azuredatastudio/issues/17923
