### ISSUE TITLE
Open Plan File button opens plan XML

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18377]
**Is your feature request related to a problem? Please describe.**
When viewing a plan (CTRL+M) the pop up for the icon says "Open Plan File", but it opens the plan XML.  I would expect a "plan file" to be a saved execution plan.

![image](https://user-images.githubusercontent.com/98599126/154126582-39838d07-c5c3-498c-9c95-72b1f43be44d.png)

**Describe the solution or feature you'd like**
Better text for the icon might be "View Plan XML" or "Open Plan XML".

**Describe alternatives you've considered**
See above.

**Additional context**
 In SSMS, if you right-click in the plan you have Show Execution Plan XML... as an option.

**Comment by kburtram** [comment]
These menu labels are trying to generic, to be applicable to other data provider execution plans.  But in the meantime, I agree `Show Execution Plan XML` seems like a more appropriate text.
