### ISSUE TITLE
Query plan properties table height doesn't fit the whole space

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#18376]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Connect to wideworldimporters db
2. Run the following query with query plan
3. right click on one of the graph to open the properties

Actual:
The properties table's height only extends to half of the page. 

Expected: the table should fit the whole space 

![image](https://user-images.githubusercontent.com/17187348/154126030-a29268ae-b10d-441f-a398-2aab06e80d12.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
actually, the properties pane is, but the plan view is not, this screenshot is properly better:
![image](https://user-images.githubusercontent.com/13777222/154130324-4bdd2115-e127-4aa0-bc49-1d42f600e19b.png)

**Comment by kburtram** [comment]
When https://github.com/microsoft/azuredatastudio/issues/18382 is fixed to be 100% height by default this should also be resolved.

**Comment by aasimkhan30** [comment]
Fixed in PR https://github.com/microsoft/azuredatastudio/pull/18409
