### ISSUE TITLE
Inconsistent use of magnifying glass with minus (-) icon

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18380]
- Azure Data Studio Version:
Version: 1.35.0-insider (user setup)
Commit: 3cfd1d23da0efba022104635b01b22cfa9a08524
Date: 2022-02-14T06:49:59.062Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1.  Execute a query with CTRL+M
2. There are a few icons on the right of the plan for magnification.  If you hover over the magnifying glass with the minus sign (-), the popup says "Zoom Out"
![image](https://user-images.githubusercontent.com/98599126/154127354-b0b548c6-226c-467b-88de-9431820e392b.png)

3. Select the icon to customize the zoom:
![image](https://user-images.githubusercontent.com/98599126/154127715-1c056cfe-744f-4aba-ab03-0cee4d16bec1.png)

4. Enter a number, the same icon for Zoom Out is now for "Enter":
![image](https://user-images.githubusercontent.com/98599126/154127551-2bbaa3c4-ab04-4485-a597-b78ce1664432.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
Fixed in main.  Trivial icon update so proposed to take for Feb.

**Comment by kburtram** [comment]
Related PR merged to release
