### ISSUE TITLE
Unique identifier columns are not allowed to be a primary key in table designer.

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18383]
Steps to repro:
1. Open table designer.
2. Change the column type to unique identifier. 
3. The UI does disables the primary key checkbox. 

Column 3: is not allowed to be primary key in table designer. 
![image](https://user-images.githubusercontent.com/6816294/154129937-8e41edb9-0db3-4f9b-a92c-1136cb2daae9.png)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Assigning this to you for Feb release
