### ISSUE TITLE
language automatically changes in query editor when pasting certain query text into it

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18399]
Paste the following code into a query editor and the language automatically changes to Docker, it will break query execution and intellisense.

```
SELECT TOP 100 *

FROM sys.all_views

CROSS JOIN sys.objects o

CROSS JOIN sys.tables t

CROSS JOIN sys.all_columns
```

![image](https://user-images.githubusercontent.com/13777222/154157074-d0477e25-dc22-479a-a404-ca3cb21fe008.png)

this doesn't happen in Dec release.

**Comment by Charles-Gagnon** [comment]
Filed issue in VS Code for this as well 

https://github.com/microsoft/vscode/issues/143145
