### ISSUE TITLE
PLEASE make clear in documentation/app that Oracle extension does not support queries

### ISSUE THREAD

**Issue by indieshack** [microsoft/azuredatastudio#18418]
**_I'm surprised I need to write this_**, but it's not at all clear from documentation about the Oracle extension that the Azure Data Studio Oracle extension does not support queries against an oracle DB. 

My assumption (and I'm sure the assumption of many people who download the extension) is that the Oracle extension provides the same kinds of capabilities as another non-microsoft db, Postgres, which does support queries. 

**If the Oracle extension's only function is to provide partial support for ETL/import into SQL Server fine - but make that clearer than it currently is both in documentation and the app itself.** The cryptic response "Execution failed due to an unexpected error: No Handler Registered" doesn't cut it.

**Comment by Charles-Gagnon** [comment]
@nahk-ivanov

**Comment by nahk-ivanov** [comment]
@aciortea Any ideas?

**Comment by Charles-Gagnon** [comment]
Two suggestions I have : 

1. Put the section about missing capabilities at the top of the README (and ideally bold the header or something to make it stand out)
2. https://docs.microsoft.com/sql/azure-data-studio/quickstart-oracle?view=sql-server-ver15 should also have a similar section about the missing capabilities

**Comment by nahk-ivanov** [comment]
Updated the docs.
