### ISSUE TITLE
Unable to copy text from markdown cell

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#18437]
Issue Type: <b>Bug</b>

Repro in RC build:
- Open any Notebook
- Try to copy text from a markdown cell. Select the text and hit Ctrl+C

Text is not copied and cannot be pasted into another application.

Azure Data Studio version: azuredatastudio-rc1 1.35.0-rc1 (2e53b4c241351c61c8d7c487490c567b10626316, 2022-02-17T01:54:24.927Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.92GB (27.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
We should verify if this still repros once @barbaravaldez has her fixes in

**Comment by Charles-Gagnon** [comment]
@barbaravaldez Assigning to you for following up with verifying this after your fix is published

**Comment by barbaravaldez** [comment]
Closing for now. Not able to repro anymore
