### ISSUE TITLE
How to disable Windows Background Updates

### ISSUE THREAD

**Issue by anique9999** [microsoft/azuredatastudio#18441]
Hi,
Is there a way to disable the auto update feature via script like installer argument [/SILENT etc.]?
![image](https://user-images.githubusercontent.com/90675448/154470286-2f5e574b-edbc-4067-8e0c-e42469e8be30.png)

Thanks

**Comment by abist** [comment]
@anique9999 Does unchecking this option not disable the background updates?

**Comment by Charles-Gagnon** [comment]
If I'm understanding correctly, @anique9999 is asking for being able to set that setting during installation.

As far as I know that's not possible - but you can have your install script create a user settings file to configure this setting instead.

The `settings.json` would look like this :

```
{
    "update.enableWindowsBackgroundUpdates": false
}
```

(by default this would go in the `%APPDATA%/azuredatastudio/User` folder)

**Comment by Charles-Gagnon** [comment]
I'm going to close this as there doesn't seem to be an issue here - feel free to use https://github.com/microsoft/azuredatastudio/discussions for asking general questions

**Comment by Charles-Gagnon** [comment]
Yes, you can either use [Portable Mode](https://code.visualstudio.com/docs/editor/portable) or use the [--user-data-dir](https://code.visualstudio.com/docs/editor/command-line#_advanced-cli-options) command line option when launching.

(ADS is a fork of VS Code so we share much of the underlying functionality, such as the two features above)

**Comment by anique9999** [comment]
Does it affect the application performance if I'm moving user data to %ProgramFiles% using command line option [--user-data-dir C:\Program files\] ?

**Comment by anique9999** [comment]
>  you'll have to use that parameter every time you launch ADS

So, passing that parameter during installation setup (script) isn't enough to save the settings in a specified location? I mean that if users launches ADS multiple times at some point it'll go back to default location.

Users have to pass that parameter every time they launch ADS?

**Comment by Charles-Gagnon** [comment]
Correct. Passing it in during installation isn't going to do anything - the installer doesn't support that parameter. That's only for ADS itself.
