### ISSUE TITLE
Links to section not working

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#18477]
Links to another section opens workbench.html file.
Version: 1.35.0-rc1
Commit: 295009ec3d9b76497aa81e3e21de65f2528c2b87
Date: 2022-02-18T04:43:38.363Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.3.0

Steps to Reproduce:

1. Add a text cell and add link to a section. Using markdown or html
2.` [#example](#example)` or `<a href="#example"></a href="#example"/></a>`
3. Link opens workbench.html file

**Comment by chlafreniere** [comment]
@barbaravaldez is this a regression?

**Comment by barbaravaldez** [comment]
@chlafreniere yes, this was introduced by the vscode merge
