### ISSUE TITLE
Cannot double click on text in a WYSIWYG cell

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18493]
1. Create a new notebook.
2. Create a WYSIWYG text cell.
3. Type some text in the cell.
4. Try to double click on a word in the cell to highlight it. The word is briefly highlighted, but then the highlight is cleared and the cursor is moved to the beginning of the cell.

**Comment by chlafreniere** [comment]
Not a regression from 1.34. Moving to April.
