### ISSUE TITLE
Icons are not accessible

### ISSUE THREAD

**Issue by yenniejun** [microsoft/azuredatastudio#18538]
Issue Type: <b>Bug</b>

Icons are not accessible. There should be tooltips for the icons (like settings, Accounts, and all the other icons I have no idea what they mean) or an option to show the text.

I am using Mac desktop version of Azure Data Studio

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 6, 6|
|Memory (System)|32.00GB (0.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Could you verify if you're seeing this too? I see the tooltips just fine on Windows

![image](https://user-images.githubusercontent.com/28519865/155364035-8eca6c2a-047c-48b9-befb-d2e7eb37a20e.png)

**Comment by lucyzhang929** [comment]
I am able to see the tooltips on Mac. The tooltips do take one or two seconds to appear especially the first time I hover over the icons.

**Comment by kburtram** [comment]
Closing as "no repro" since we are seeing hover tooltips in this scenario.  Please try ensuring the application was responsive when testing this scenario and leave the mouse hovering over icon for a few seconds while the tooltip is being shown.  Thanks for reporting this issue.
