### ISSUE TITLE
Failed to change kernel. Kernel SQL will be used. Error was: Can't find notebook manager for provider jupyter

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#18545]
Issue Type: <b>Bug</b>

Open a new notebook. Kernel takes some time to load and defaults to SQL.
Select from dropdown menu PowerShell or Python 3.
Error appears: Failed to change kernel. Kernel SQL will be used. Error was: Can't find notebook manager for provider jupyter
Ctrl+shift+P to reinstall Notebook Dependencies. -> new error: Command 'Reinstall Notebook dependencies' resulted in an error (command 'jupyter.reinstallDependencies' not found)
Removed Azure Data Studio.
Reinstalled ADS. Same behaviour.

Extremely similar to https://github.com/microsoft/azuredatastudio/issues/16746
So similar that I Copy/Pasted that bug report here and only made minor changes.

Please let me know if I can provide any additional logs?

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:47:33.863Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (17.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sidebar|Acr|1.1.2
docs-authoring-pack|doc|0.1.8
dacpac|Mic|1.8.0
powershell|ms-|2021.12.0
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.14.1
sql-dw|Mic|0.0.1
vscode-docker|ms-|1.6.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment]
@barbaravaldez this is the issue that we're talking about offline 😄

**Comment by barbaravaldez** [comment]
Worked with @SQLvariant offline and the issue was fixed by removing the azuredatastudio-python folder and reinstalling python again from Configure Python dialog.
