### ISSUE TITLE
Do a copy (CTRL-C) from a result in a grid result does a copy with header

### ISSUE THREAD

**Issue by lpvezina** [microsoft/azuredatastudio#18554]
Issue Type: <b>Bug</b>

1. Do a query that return a resultset
2. Select a single cell in the resultset grid
3. Do CTRL-C
4. Paste the content of the clipboard in the query section

**Expected**
Only the result of the cell is pasted

**Actual result** 
Header is also pasted with the result

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10610U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (13.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
atlascode|atl|2.7.0
bracket-pair-colorizer-2|Coe|0.1.4
pastetheplan|dre|0.2.0
query-editor-boost|dre|0.4.1
gitlens|eam|10.2.1
grepper|Gre|0.0.7
ssmskeymap|kev|1.1.0
indent-rainbow|ode|7.4.0
queryplan-show|phi|0.0.6
vscode-yaml|red|0.10.0
trailing-spaces|sha|0.3.1

</details>
ve written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by Charles-Gagnon** [comment]
The default behavior for this is controlled by a setting - make sure you have that set to false.

![image](https://user-images.githubusercontent.com/28519865/155770327-81c46a9f-e38a-4869-a0c0-c9dba5af6e71.png)

**Comment by lpvezina** [comment]
Oh!  This is perfect!  Was it added in the previous release?  I started having this behavior in 1.34 and waited to 1.35 to see if if was going to be fixed.  But, this is nnot a bug, but a nice behavior : let the user choose to whether or not getting the Header on CTRL-C.
Thanks!  I'll close the ticket.

**Comment by alanrenmsft** [comment]
@lpvezina I think this feature has been there for quite a while.

**Comment by lpvezina** [comment]
@alanrenmsft Could be.  I might have fliped it to True thinking to change something else.

**Comment by Scott123456** [comment]
The text in this option is confusing and, to me, does not produce the intended result. With this option on, Ctrl + C will always copy with header. If I right click on a result cell, and choose "Copy" or "Copy with Header" they both have the same functionality now. I cannot copy without header unless I turn this option off which is confusing.
