### ISSUE TITLE
Fix issues with stuck cells after doing Run All Cells in Interactive notebooks

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18577]
When using an Interactive notebook and clicking the runAllCells button, execution will sometimes stop halfway down the page or a cell in the middle will be stuck in a running state until cancelled. Cancelling the cell and running it again works, so this might just be a UI level bug.

For example, the #!value cell in this test notebook gets stuck when doing run all cells, but succeeds when running by itself. https://github.com/dotnet/interactive/blob/main/samples/notebooks/polyglot/Variable%20sharing.ipynb

**Comment by Charles-Gagnon** [comment]
@corivera Is this still planned for April?

**Comment by corivera** [comment]
Moved to June

**Comment by chlafreniere** [comment]
@corivera can you remind me where we're at with this issue? Does it still repro?

**Comment by corivera** [comment]
Yep, issue still exists.

**Comment by chlafreniere** [comment]
@corivera ok, thanks for checking. Just looking at all issues in the August milestone.
