### ISSUE TITLE
A11y_AzureDataStudio_New deployment - SQL Server on Windows_High Contrast:Focus is not adapting for install location field in specify SQL server install location page when the high contrast Aquatic theme is applied

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/azuredatastudio#18596]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio; #WCAG4.3.1; #Win32; #AINotInScope; #No Disruption of Accessibility Features; #High Contrast;

### Environment Details:
Windows Version :Windows 11 Enterprise
Application name :Azure Data studio

### Repro Steps:
1.Turn on High Contrast Aquatic theme on Settings.
2. Launch Azure Data Studio.
3. Select the Connections icon (if not already selected) from left bar.
4. Click on the ellipses '...' and select "New Deployment"
5. In the Deployment options, select "SQL Server on Windows" card.
5. From the dropdown for Version under Options, select from the available options.
6. Click the "Select" button  
7. This will start the setup installer for SQL Server setup. 
8. Follow the instructions through the setup process to install a SQL Server on Windows
9. In specify SQL server install location page
10. Verify install location field in Aquatic theme received focus or not

### Actual Result:
Focus is not adapting for install location field in specify SQL server install location page when the high contrast Aquatic theme is applied.

### Expected Result:
Focus should  adapt for install location field in specify SQL server install location page when the high contrast Aquatic theme is applied.

### Attachment:

![A11y_AzureDataStudio_New deployment - SQL Server on Windows_High Contrast_install Location](https://user-images.githubusercontent.com/100189407/156163673-fee326fa-eb69-4bc5-bdab-e31b5f1b9cac.gif)

**Comment by alanrenmsft** [comment]
the install SQL server feature you tested is not a part of AzureDataStudio. so closing it, let me know if you don't know the owner of the sql server installer.

**Comment by VijayaBharathyA** [comment]
@alanrenmsft Could you please let us know if we need to route this bug to the sql server installer team? If yes, could you please let us know the vso and owner's detaills?  and also can you resolve that bug, because bug can be closed by trusted tester only

**Comment by VijayaBharathyA** [comment]
@alanrenmsft Could you please route it to the appropriate owner or team and reactivate the bug.
**Note:** "Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"

**Comment by VijayaBharathyA** [comment]
@Matteo-T

As per above comments bug is external to SQL server, could you please let us know the Service tree name, VSO details and Area path to log a bug.

**Comment by VijayaBharathyA** [comment]
#Closed;
After discussing in Bug discussion call We are able to see cursor in High contrast Theme hence we are closing the Bug.
