### ISSUE TITLE
A11y_AzureDataStudio_New deployment - SQL Server on Windows_High Contrast:Important notice in Microsoft sql server license terms page is not adapting high contrast Aquatic theme 

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/azuredatastudio#18595]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio; #WCAG4.3.1; #Win32; #AINotInScope; #No Disruption of Accessibility Features; #High Contrast;

### Environment Details:
Windows Version :Windows 11 Enterprise
Application name :Azure Data studio

### Repro Steps:
1.Turn on High Contrast Aquatic theme on Settings.
2. Launch Azure Data Studio.
3. Select the Connections icon (if not already selected) from left bar.
4. Click on the ellipses '...' and select "New Deployment"
5. In the Deployment options, select "SQL Server on Windows" card.
5. From the dropdown for Version under Options, select from the available options.
6. Click the "Select" button  
7. This will start the setup installer for SQL Server setup. 
8. Follow the instructions through the setup process to install a SQL Server on Windows
9. Verify Important notice in Microsoft sql server license terms page  is adapting Aquatic theme or not

### Note:
Connections and Notebooks icon is not adapting high contrast Aquatic theme

### Actual Result:
Important notice in Microsoft sql server license terms page  is not adapting high contrast Aquatic theme

### Expected Result:
Important notice in Microsoft sql server license terms page should adapt high contrast Aquatic theme

### Attachment:
![A11y_AzureDataStudio_New deployment - SQL Server on Windows_High contrast](https://user-images.githubusercontent.com/100189407/156155307-95373d1b-0639-4d75-a80b-d1964391c7a8.png)

**Comment by alanrenmsft** [comment]
the install SQL server feature you tested is not a part of AzureDataStudio. so closing it, let me know if you don't know the owner of the sql server installer.

**Comment by Gayathri1501** [comment]
@alanrenmsft Could you please let us know if we need to route this bug to the SQL server installer team? If yes, could you please do let us know the vso and owner's details?

**Comment by Gayathri1501** [comment]
@alanrenmsft --Could you please provide alias for the owner of this bug. So, that I can discuss the bug with him. Thanks in Advance.

**Comment by alanrenmsft** [comment]
@Gayathri1501 I already did: matteot.

**Comment by VijayaBharathyA** [comment]
@alanrenmsft Could you please route it to the appropriate owner or team and reactivate the bug.
**Note:** "Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"

**Comment by VijayaBharathyA** [comment]
@Matteo-T 

As per above comments bug is external to SQL server, could you please let us know the Service tree name, VSO details and Area path to log a bug.

**Comment by VijayaBharathyA** [comment]
Verified the issue in SQL Server 2022 issue still repro
![image](https://user-images.githubusercontent.com/100189407/218942385-da29422b-2f30-432b-8682-99b57d4ce9ce.png)

**Comment by VijayaBharathyA** [comment]
We will be Tracking issue Here https://msdata.visualstudio.com/Database%20Systems/_workitems/edit/2231808
