### ISSUE TITLE
refresh does not work

### ISSUE THREAD

**Issue by bzynpb** [microsoft/azuredatastudio#18599]
Issue Type: <b>Bug</b>

Hi Team, 
I have change my file but azure does not show my latest work even tough I try to refresh couple of time. 
How can I see my latest file? 

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-visualization|R0t|0.8.2

</details>

**Comment by Charles-Gagnon** [comment]
What are you trying to refresh exactly? And what "file" are you trying to see?

**Comment by alanrenmsft** [comment]
@bzynpb please reopen with the requested information.
