### ISSUE TITLE
Allow for named default constraints in Azure Data Studio Table Designer

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#18603]
**Is your feature request related to a problem? Please describe.**
When using the table designer in SQL Server, any default constraints that are created are scripted with no defined names e.g.:

```
ALTER TABLE [Activity].[INSTANCES]
ADD [NewBitColumn] BIT DEFAULT 0 NULL;
```

When this happens, SQL Server generates an arbitrary name (e.g. `DF__INSTANCES__NewBi__2F1D4F78`)

Our business processes require named defaults on all our constraints which means we can't use the table designer directly.

**Describe the solution or feature you'd like**
 ADS's table designer to support naming the default constraints (to something that's not arbitrary name)

**Describe alternatives you've considered**

**Additional context**

@alanrenmsft

**Comment by alanrenmsft** [comment]
@tdoshin where is this coming from?
