### ISSUE TITLE
Excel number format

### ISSUE THREAD

**Issue by Zanzacar** [microsoft/azuredatastudio#18615]
Issue Type: <b>Bug</b>

Before updating to this current version I was able to save a report to excel and the numbers would be saved as numbers. However now that I have updated when I run the same report and save as excel it comes in as text for some reason. Switching it back seems to be problematic.

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.76GB (18.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|3.3.0

</details>

**Comment by cympaulife** [comment]
having the same issue also

**Comment by Zanzacar** [comment]
> having the same issue also

As a quick solution you can export to csv then open it in excel and save as an excel document. Isn't great but got the job done for me without having to fuss around with cell formats or whatever else.

**Comment by PVanOste** [comment]
This issues is resulting in downstream problems, and needs to be addressed quickly.

**Comment by alanrenmsft** [comment]
@Zanzacar Thanks for reporting the issue, a new version with the fix for this issue should be available later this week.

**Comment by cheenamalhotra** [comment]
Closing as issue had been fixed.
