### ISSUE TITLE
.NET Interactive Create new notebook opens the same notebook twice

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#18638]
1. Run the command  .NET Interactive Create new Blank notebook
2. Create as ipynb
3. Choose C# as language

It opens two instances of the new notebook
<img width="1337" alt="Screen Shot 2022-03-04 at 11 28 35 AM" src="https://user-images.githubusercontent.com/34872381/156830601-fe75fb46-42ee-419a-b50b-558e40800dc1.png">

**Comment by corivera** [comment]
Closing issue since the create ipynb notebook command is removed in the latest version of the extension.
