### ISSUE TITLE
[Interactive] JavaScript kernel does not work

### ISSUE THREAD

**Issue by jonsequitur** [microsoft/azuredatastudio#18643]
- Azure Data Studio Version: 
Azure Data Studio - Insiders
Version: 1.36.0-insider (user setup)
Commit: a2c39369c98916366ff7bcf9826c7cab7b8de38f
Date: 2022-03-04T06:28:43.281Z (13 hrs ago)
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS Version:
Windows 11

Steps to Reproduce:

1. Create .NET Interactive notebook
2. Set cell language to JavaScript
3. Run `console.log(123)`
4. It shows an error: `Error: No handler found for command type SubmitCode`
![image](https://user-images.githubusercontent.com/547415/156833480-c40907be-b0e8-472f-a0ba-4d163c0c03ff.png)

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by corivera** [comment]
Closing this issue since .NET Interactive support has been removed from ADS.
