### ISSUE TITLE
.NET Interactive's Save command saves notebook as empty plain text

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#18641]
1. Create notebook using .NET interactive command
2. Save untitled notebook using .NET Interactive
3. The saved notebook is opened in the editor as plain text.

<img width="1604" alt="Screen Shot 2022-03-04 at 11 54 46 AM" src="https://user-images.githubusercontent.com/34872381/156832508-f856b5d0-9f59-40cc-b233-154eecd7dd3b.png">

**Comment by corivera** [comment]
Closing issue since this command is removed in the latest version of the extension.
