### ISSUE TITLE
Error popup Icon proposes confusion where to close it.

### ISSUE THREAD

**Issue by JeffBusterCase** [microsoft/azuredatastudio#18652]
**Is your feature request related to a problem? Please describe.**
Whenever I try to close a error dialog, I miss the close button by the error Icon.

**Describe the solution or feature you'd like**
Select a different Icon to represent an error

**Describe alternatives you've considered**
none

**Additional context**
This shows when you click on View Problem
And Error Icon is much more close to the query, so we Look at him... and want to close it, so we click on it. But it dosen't work.. because the close button is the X without the circle around it. Yet, they seem too much alike, and permits confusion.
![image](https://user-images.githubusercontent.com/12688410/156879014-0b5d9a9b-f036-4eab-aba8-1a570a8e1444.png)

A simple search for close icon on google displays better this problem:
![image](https://user-images.githubusercontent.com/12688410/156879175-b926e77d-e1df-4e8f-aec5-17429f51ba1f.png)

What I suggest is to use ! instead:
![image](https://user-images.githubusercontent.com/12688410/156879430-02726f73-6d03-4a37-97bf-fefa70a6ac03.png)

**Comment by kburtram** [comment]
@JeffBusterCase thanks for opening this feature enhancement suggestion!  This particular UX is coming from upstream vscode editor and has not been modified in Azure Data Studio.  For upstream features we typically only modify if there is something distinct about our user segment vs. the vscode user community.  In this case, I think is more general UX feedback around the error experience in the editor and so would be better to be addressed upstream.  Please log this suggestion against vscode and we can pickup when refreshing upstream source code.

**Comment by JeffBusterCase** [comment]
Ok! Thanks!
