### ISSUE TITLE
Wont Connect to LocalHost

### ISSUE THREAD

**Issue by LuisRaulRivera24** [microsoft/azuredatastudio#18654]
Issue Type: <b>Bug</b>

Error message where my query won't connect to local host.
"An unexpected error occurred while connecting..."

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (3.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.0

</details>

**Comment by kburtram** [comment]
@LuisRaulRivera24 are there any error messages or callstacks in the "Help->Developer Tools" Console?  does the connection work when you add to Servers viewlet and only fail when running queries?  Do connections to other servers work fine?  Have you tried to connect to localhost with other tools, such as SSMS, successfully?  Thanks!

**Comment by kburtram** [comment]
Closing per previous comment and inability to repro.  Please let us know if you are still impacted by this issue and can provided additional diagnostic info.  Thanks!
