### ISSUE TITLE
Add account stuck at loading --Version 1.35.0

### ISSUE THREAD

**Issue by Narvinuk** [microsoft/azuredatastudio#18651]
- Azure Data Studio Version:
- OS Version: 1.35.0

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
@Narvinuk have you tried to remove and re-add the account?  Are you getting any error messages in the "Help->Developer Tools" console?

**Comment by kburtram** [comment]
Closing due to inability to repro and no available diagnostic information.  Please let us know if you are still impacted by this issue and the previous suggestion did not workaround this issue.
