### ISSUE TITLE
new extension throwing missing localized string error

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18662]
![image](https://user-images.githubusercontent.com/13777222/157103724-146d3544-981d-44ad-a185-f388ee3b738a.png)

**Comment by Charles-Gagnon** [comment]
@VasuBhog You shouldn't have the % in the nls file : 

https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-bindings/package.nls.json

	"%displayName%": "SQL Bindings",

Example correct one : https://github.com/microsoft/azuredatastudio/blob/main/extensions/arc/package.nls.json
