### ISSUE TITLE
Interactive: Restart Notebook Kernel palette command does not restart kernel

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#18661]
Full command name: ".NET Interactive: Restart the current notebook's kernel"

**Comment by chlafreniere** [comment]
Restart kernel (for Jupyter kernels in ADS) was checked in with #18835, but this doesn't resolve the .NET Interactive issue, which likely uses some of the VS Code APIs under the covers to do a restart.

**Comment by Charles-Gagnon** [comment]
@chlafreniere Moving this out to June

**Comment by corivera** [comment]
Closing this issue since .NET Interactive support has been removed from ADS.
