### ISSUE TITLE
Can it support macOS monterey ?

### ISSUE THREAD

**Issue by wastu01** [microsoft/azuredatastudio#18705]
- Azure Data Studio Version:
- OS Version:  macOS monterey 12.2.1

dose it support macOS monterey ?
the website  supported-operating-systems not include my computer system  
https://docs.microsoft.com/zh-tw/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15

**Comment by abist** [comment]
@wastu01 Yes, it is supports macOS Monterey (I'm currently on macOS Monterey), even though it might not be explicitly mentioned in the docs. Are you having trouble opening ADS on Monterey?

**Comment by Charles-Gagnon** [comment]
@abist Can you work with PMs to get that list updated?

**Comment by wastu01** [comment]
tks reply. it works well so far

**Comment by dzsquared** [comment]
Our supported operating systems docs have been updated - thanks @wastu01 for bringing this up!

https://docs.microsoft.com/sql/azure-data-studio/download-azure-data-studio#supported-operating-systems
