### ISSUE TITLE
Results Output: Filter on NULLs

### ISSUE THREAD

**Issue by Scott123456** [microsoft/azuredatastudio#18707]
**Is your feature request related to a problem? Please describe.**
The drop down filter in the results set output viewer does not allow to filter on NULL values. It only allows filtering on values with data.

**Describe the solution or feature you'd like**
If there are nulls in the column, I should be able to select NULL in the filter values.

**Describe alternatives you've considered**
I can sort so all NULL are at the top of the results, but cannot filter to NULL.

**Additional context**
In the screenshot you can see that there are null values in the column, but there is no option to filter to it.
![image](https://user-images.githubusercontent.com/10225537/157924139-c6e480e4-4f54-4c08-89ce-1dc5d62877bb.png)

**Comment by alanrenmsft** [comment]
@Scott123456 the issue has been fixed and the fix will be available in next release. looks like this:
![image](https://user-images.githubusercontent.com/13777222/160963586-03e1c6ac-c6c7-4faa-9764-095d03eef5f2.png)

**Comment by Scott123456** [comment]
I'm using this feature in the new April 2022 release. Awesome job!
