### ISSUE TITLE
Insert column in-between with Table Designer

### ISSUE THREAD

**Issue by manthena** [microsoft/azuredatastudio#18717]
The new Table Designer feature which is currently in preview has "+Add New" option to add a new column. However the new column is added to the end of the table by default.

Please provide an option to add new column in-between the existing columns (similar to "Insert column" option in SSMS).

**Comment by alanrenmsft** [comment]
1. allow insert column: context menu to insert column after/before selected column
2. add new buttons next to "Add New" button to move column up or down
3. allow drag and drop to reposition column
