### ISSUE TITLE
Edit Connection often shows wrong connection details

### ISSUE THREAD

**Issue by morangozul** [microsoft/azuredatastudio#18736]
- Azure Data Studio Version:  1.35.0 
- OS Version: Windows_NT x64 10.0.19042

Steps to Reproduce:

0. Open Azure Data Studio
1. Right-click on a server connection
2. Select "Edit Connection"
3. Sometimes the connection details are wrong. When they are wrong, they are from the latest added connection. 

Does this issue occur when all extensions are disabled?: Yes

**Comment by jashwood** [comment]
This is the kind of bug that could have us making data or code changes in the wrong environment!

**Comment by cssuh** [comment]
Hi @morangozul, is this happening for azure databases, non-azure databases, or both?  What details are wrong? Can you show screenshots of an example where this is happening? I'm not able to repro on my machine, so trying to collect some more details.

**Comment by kburtram** [comment]
I was unable to repro this issue with build 1.35.1 after using Edit Connection numerous times.  The two things that come to mind are perhaps (1) the right-click context menu was inadvertently focused on a different node in OE and an unexpected connection was edited or (2) an item in the Recent Connections list was clicked on in the Connection Dialog updating the connection details.  Please let us know if you can provide additional repro details to help determine what's happening.  Thanks!

**Comment by morangozul** [comment]
Hello, sorry for the delay on my side. 
@cssuh I have only tested this with azure databases. All the details were 'wrong' and matched exactly a connection that I had just added to Azure Data Studio during the same session. I had this happen while I was sharing my screen with a colleague, and it made me doubt my sanity. 😅
Other connections were also affected when I selected "Edit Connection". The problem was gone after re-starting ADS, but was a scary thing and I felt like it should be reported immediately.

**Comment by morangozul** [comment]
Hello again, today I experienced this problem again and can guarantee that it is related to adding a new connection. 
Steps:
1) Open Azure Data Studio
2) Click on 'Add new connection'
3) Enter the new connection info and press 'Connect'. Your new connection will show the green marker that you are now successfully connected. 
4) Right-click on a pre-existing saved connection that has the red marker (so that you aren't connected to it at the moment). 
5) Select "Edit Connection"
6) Look at the connection details and note that they are all from the newly added connection. 

Sadly, I can't make a video to show this because the data is confidential.

**Comment by Dale-Wilks** [comment]
Connection occasionally show wrong database.  The latest time it happened after re-connecting after losing network connection
![Screenshot 2022-09-01 142243](https://user-images.githubusercontent.com/89921381/187926255-8964b5a1-a474-4aad-a793-9efbfe9a14bb.png)
