### ISSUE TITLE
Copy/paste during running request 

### ISSUE THREAD

**Issue by SalavatFront** [microsoft/azuredatastudio#18756]
- Azure Data Studio Version: 1.35.0
- OS Version: WIndows 10 21H1 (build 19043.1586)

Steps to Reproduce:

1. In first tab execute some request and receive results.
2. Start long running request to SQL server in second tab.
3. In first tab try to copy some string from results view table (CTRL + C or right mouse button + Copy)
4. Try to paste somewhere. Old buffer value will be pasted - incorrect behavior.
5. Wait until request in first tab finished.
6. Try to paste - copied value pasted - correct behavior.

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
@SalavatFront I need your help to reproduce the issue. below are your repo steps and my comments.

1. In first tab execute some request and receive results.

this is tab 1
![image](https://user-images.githubusercontent.com/13777222/172267868-3af1b73a-7221-454d-9616-fefd93460a41.png)

2. Start long running request to SQL server in second tab.

this is tab 2, start executing
![image](https://user-images.githubusercontent.com/13777222/172268120-7a16e446-be86-437a-96c3-6451f1f87bfa.png)

3. In first tab try to copy some string from results view table (CTRL + C or right mouse button + Copy)
I copied 2 cells

4. Try to paste somewhere. Old buffer value will be pasted - incorrect behavior.
I am getting the correct string pasted 
![image](https://user-images.githubusercontent.com/13777222/172268411-a40ed25d-1ff2-425a-8f6d-06dd62a35a90.png)


Am I missing something here?

**Comment by SalavatFront** [comment]
@alanrenmsft Hello. I could not reproduce it either on my new machine. I guess you can close it. Thank you.
