### ISSUE TITLE
adding GitLens extension to sql database project

### ISSUE THREAD

**Issue by softboy99** [microsoft/azuredatastudio#18755]
adding GitLens extension to sql database project. Current Git SCM, cannot see code historylist

**Comment by Charles-Gagnon** [comment]
I'm closing this since generally extension support requests should go to the extension owner itself. If you think there's something missing from ADS core itself please provide some more details so we can triage this appropriately!

**Comment by softboy99** [comment]
Hi,
If current Git SCM, can see code historylist, we doesn't need extra extension.
