### ISSUE TITLE
Create SQL binding fails on .NET core 3.1 -

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#18767]
- MSSQL Extension Version: 1.13.0
Version: 1.65.0 (Universal)
Commit: b5205cc8eb4fbaa726835538cd82372cc0222d43
Date: 2022-03-02T11:11:20.886Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin arm64 21.3.0

Steps to Reproduce:

1. create a functions project on .NET 3.1
2. use object explorer to create SQL binding

![image](https://user-images.githubusercontent.com/12227241/157323190-9ce29ec8-a41d-46cf-9c04-eff46add4da9.png)

edit:
discovered this is independent of the project's target platform, but dependent on whether the .net 6 SDK is on the environment.  a workaround is to also install .net 6 in the environment.

**Comment by VasuBhog** [comment]
Just tested this after uninstalling all sdks/runtimes. Only installed 3.1 .Net SDK.
<img width="544" alt="image" src="https://user-images.githubusercontent.com/23587151/162337909-0b498fb8-72ab-4b9b-a9ac-166f5bb86310.png">

I was able to create SQL binding with the latest changes.

**Comment by dzsquared** [comment]
Closing as low pri with upcoming .NET Core 3.1 EOL in Dec 2022.
