### ISSUE TITLE
SQL Binding Templates shows storage account wizard

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#18780]
SQL Bindings Extension latest

Steps to Reproduce:

1. User uses Create Azure Function with SQL Binding from a selected table.
a. If user doesn't have a function file go through create flow
3. User chooses a function project folder (if many)
4. Prompt for Function Name (placeholder of table name)
5. Prompt for type of binding
6. Prompt for namespace
7. Issue if AzureWebJobStorage in local.settings.json is empty 
8. ![Screen Shot 2022-03-17 at 7 14 24 PM](https://user-images.githubusercontent.com/23587151/159096490-1dd488e6-0339-4021-8437-948c18ae450d.png)

This is due to vscode-azurefunctions https://github.com/microsoft/vscode-azurefunctions/blob/main/src/debug/validatePreDebug.ts#L123. 
If AzureWebJobsStorage is an empty string and does not use HTTP Trigger then it will always open the issue in step 7.

**Comment by chlafreniere** [comment]
When does AzureWebJobsStorage get added to the settings file? I assume that this is something that's done by the AF extension?

cc @dzsquared

**Comment by Charles-Gagnon** [comment]
Yes, that's one of the default values populated when the project is created.

**Comment by VasuBhog** [comment]
So from my understanding and in most scenarios, we would not have an azureWebJobStorage for SQL Bindings. In local.settings.json then would have an empty string. 

In the meantime, the workaround I did was set the setting to a placeholder value in https://github.com/microsoft/azuredatastudio/pull/18768.

**Comment by Charles-Gagnon** [comment]
It depends - while the templates are specifically for an HTTP trigger we do support other types of triggers. So in general we can't say we'll never need it. But for this specific case? Because we're using the template which is only HTTP triggers then putting an empty value there is fine.
