### ISSUE TITLE
Quickbase databases are not showing up

### ISSUE THREAD

**Issue by PyMach** [microsoft/azuredatastudio#18787]
- Azure Data Studio Version: 1.35
- OS Version:  Windows 10 Enterprise 21H2

Steps to Reproduce:

1. Connect to Quickbase
2. You will see no databases listed

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by PyMach** [comment]
When I connect Quickbase using SSMS it does work

**Comment by alanrenmsft** [comment]
@PyMach could you please share the version of the sql server you are connecting to?

**Comment by kburtram** [comment]
@PyMach  Unfortunately we do not have a copy of Quickbase to repro and investigate this issue.  Could you please connect to the database using SSMS and run a command such as `SELECT @@VERSION` to determine the version of SQL Server Quickbase is using?  That may provide enough context to investigate.  Thanks!

**Comment by cheenamalhotra** [comment]
Closing the issue because it needs more information and has not had recent activity from long time. 
If you have more info to help resolve the issue, please leave a comment.
