### ISSUE TITLE
Pasting SQL changes language mode to Powershell

### ISSUE THREAD

**Issue by lambertaa-churchaccount** [microsoft/azuredatastudio#18800]
Issue Type: <b>Bug</b>

Pretty regularly when I copy valid SQL from one tab and paste it into another tab, the new tab has its language mode automatically changed to Powershell. This is incredibly annoying because if I try to change the language mode back to SQL I get a message telling me that I cannot change the language mode on an unsaved script.

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (3.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@lambertaa-churchaccount  could you please share the query that can reproduce the issue? also were you coping query to a query editor (within it there is a toolbar with these actions: run query, connect )?

**Comment by lambertaa-churchaccount** [comment]
I cannot as it contains sensitive information, but I have this happen about once a week. I was copying from one tab to another. Both tabs were query editors.

**Comment by lambertaa-churchaccount** [comment]
This one just happened to me and does not include sensitive information. I pasted the following into a query editor and the type changed to "Markdown". It is repeatable for me. I undo all changes until the language type says SQL again (since I get an error when trying to change it manually), then clear everything with CTRL-A and Del or backspace, then paste the below code, and it switches again to Markdown.


select pe.PropertyNumber as PropertyNumber,
    pet.*
from PropertyEntity pe
join PropertyEntityType pet on pe.PropertyEntityTypeId = pet.PropertyEntityTypeId

PropertyNumber,
FacilityType, --Property, Structure, Space
StructureNumber, -- 5000130-01 or null
SpaceNumber,  -- 5000130-01 or null
AddressType, -- Physical Location, Delivery Location, Mailing
StreetAddress1,2,3,
PostalCode,
Location1Type,
Location1,
Location2Type,
Location2,
Location3Type,
Location3,
Location4Type,
Location4,
Location5Type,
Location5,
Latitude,
Longitude

**Comment by alanrenmsft** [comment]
finally, I am able to reproduce the issue, it has to be in an editor from a previous session (open an new editor and reopen azure data studio), newly opened editor in current session won't have such problem. are you seeing the same behavior? @lambertaa-churchaccount 

I have a fix for it and the fix will be shipped in our next release.
