### ISSUE TITLE
Table Designer: Preview icon is not styled correctly

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#18802]
![Screen Shot 2022-03-22 at 10 27 57 PM](https://user-images.githubusercontent.com/6411451/159630197-a598583c-6cc5-4140-af36-972b7f2a82e4.png)

the icon seems to be under the text

**Comment by alanrenmsft** [comment]
on mac?

**Comment by abist** [comment]
yes

**Comment by alanrenmsft** [comment]
@abist is it the local dev instance or the installed instance?

**Comment by abist** [comment]
@alanrenmsft This is in dev. Installed looks fine.

**Comment by abist** [comment]
Closing as I don't see the issue any more.
