### ISSUE TITLE
Extensibility: Object Explorer should be updatable from provider-side, not just from user-click

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1881]
- SQL Operations Studio Version:

Steps to Reproduce:
- Create an extension that provides an ObjectExplorerProvider
- Connect & expand a set of nodes
- Perform some kind of context-menu action that should add a node to an already-expanded section of the tree
  - Inside the extension, call the handler passed into the `registerOnExpandCompleted` method, which should indicate an expansion is done

Expected: 
- The node is refreshed in the UI (this was expected per discussion with @llali offline)
Actual:
- The UI isn't updated
- You have to manually click "Refresh" for the nodes to reappear

**Comment by MattIrv** [comment]
@kevcunnane when you say "expand a set of nodes" you mean via the Object Explorer provider API?

As a workaround you should be able to use the `objectexplorer` namespace api to expand the node, but we can fix it in the provider API as well

**Comment by kburtram** [comment]
Closing out older issues.
