### ISSUE TITLE
Do not truncate operator names

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#18818]
Version: 1.36.0-insider (user setup)
Commit: 5a87e552bc728691c61c7eab8dcaf64af93bce33
Date: 2022-03-23T05:27:42.969Z
VS Code: 1.59.0
Electron: 13.5.0
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open ADS
2. Run the query below with actual plan (CTRL + M) against WideWorldImporters

SELECT *
FROM Sales.Orders o
JOIN Sales.OrderLines ol
ON o.OrderID = ol.OrderID
WHERE o.OrderDate BETWEEN '2016-01-01 00:00:00.000' AND '2016-12-31 23:59:59.997'
ORDER BY o.CustomerID, o.OrderDate DESC

3. Notice that the Clustered Index Scan and Columnstore Index Scan operations have the name truncated.

![image](https://user-images.githubusercontent.com/98599126/159952773-9f624923-0eb1-4ebf-b097-50a1da0f1503.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by erinstellato-ms** [comment]
@lewis-sanchez I'm running the latest Insider build and I can see that the names are not truncated, but we that creates a separate issue where long object names overlap.  Can we do some kind of word wrap to prevent this?  Example of overlap below.

![image](https://user-images.githubusercontent.com/98599126/162289914-2c3786ba-f51c-45aa-b32c-d313697d35e5.png)

**Comment by kburtram** [comment]
Fix merged to release branch
