### ISSUE TITLE
Add hyperlinks and close feature to Info Container

### ISSUE THREAD

**Issue by stuti149** [microsoft/azuredatastudio#18819]
**Is your feature request related to a problem? Please describe.**
Feature required for oracle assessment extension 

**Describe the solution or feature you'd like**
1. Add hyperlinks inside info box
2. Add close icon inside info box
<img width="444" alt="image" src="https://user-images.githubusercontent.com/87131830/159974558-6abe784e-dab4-4bbb-a2a1-ae45069162b0.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by kburtram** [comment]
Fix merged to release branch
