### ISSUE TITLE
New project in Sql project extension in vscode doesn't ask for target framework

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#18824]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. In project extension in vscode click on + to create new project
2. enter project name and location

Expected: I expected to ask for project target framework but didn't see the prompt
Actual: project is created and target is set to 150 by default

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
added in https://github.com/microsoft/azuredatastudio/pull/18731
