### ISSUE TITLE
Azure Data Studio Connection has no username field

### ISSUE THREAD

**Issue by rockwayschool** [microsoft/azuredatastudio#18829]
I just downloaded ADS for Mac.  I am trying to set up a connection, but there is no place to enter a username, unlike pictures I have seen on the web which include this field.  Is this a bug?

I am trying to use AD authentication but not with my user account.

Release number: 1.35.

<img width="489" alt="Screen Shot 2022-03-25 at 5 29 28 PM" src="https://user-images.githubusercontent.com/67080909/160205054-7d64661c-b14a-40bb-92ee-c28ad05a59dc.png">
1

**Comment by Charles-Gagnon** [comment]
See these docs for instructions on how to set up Kerberos authentication for MacOS. That is where you will specify the account to use.

https://docs.microsoft.com/sql/azure-data-studio/enable-kerberos?view=sql-server-ver15
