### ISSUE TITLE
Accessibility Issue: No tooltip is seen when "Preview Feature" icon hovered over

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#18820]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Open table designer preview by right clicking on table and selecting "Design"
2. On far right, hover over "i" icon next to "Preview feature"

Expected Outcome: 

Tool tip phrase should appear above or around "i" icon to provide more info

Actual Outcome: 

Nothing happens

![image](https://user-images.githubusercontent.com/72947001/160010713-a3961216-6b2f-4106-83f0-83c279a8aee5.png)

Does this issue occur when all extensions are disabled?: Yes/No

@alanrenmsft @abist

**Comment by alanrenmsft** [comment]
@tdoshin what are you expecting as the tooltip?

**Comment by alanrenmsft** [comment]
interesting thing is once we are done with accessibility testing this will be removed. so closing the issue.
