### ISSUE TITLE
Add context menu support to Table Component

### ISSUE THREAD

**Issue by brian-harris** [microsoft/azuredatastudio#18834]
Issue Type: <b>Feature Request</b>

The SQL Migration extension is currently using the DeclarativeTable component that supports a context menu column.  The extension needs to use a Table component instead to support large lists but also uses context menu/column support.  This missing features is a blocker for the extension

Azure Data Studio version: azuredatastudio Dev 1.36.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by aasimkhan30** [comment]
This issue is fixed and already present in the main. Closing it for now.

PR for reference:  https://github.com/microsoft/azuredatastudio/pull/18914
