### ISSUE TITLE
Azure auth uses endpoint as resource

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18845]
Currently we hardcode the resource for a token request to the endpoint for the resource, but when making connections the resource may be different in some circumstances. 

https://github.com/microsoft/azuredatastudio/blob/cb11c2bb227d7a2ed7599cce46ea7e22758a58cf/extensions/azurecore/src/account-provider/auths/azureAuth.ts#L254

**Comment by shueybubbles** [comment]
Either add the resource and authority URLs as optional parameters to the connection settings or attempt to discover the URLs using TDS in the tools service before issuing the authentication request in the UI.
