### ISSUE TITLE
Extensibility: design official API for Object Explorer Context menu object

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1884]
With the PR #1883 we will have support for Object Explorer context menus, but we should look more closely at the context menu object passed to extensions. There are a number of issues to consider when updating this:
1. Finding the correct node from this is a bit cumbersome right now - there's no information about the session sent with the request, which means a decent bit of work is needed on the extension side to map this correctly. We should consider adding this
2. There are 3 fields passed including an `isConnectionNode` object, which makes up for the fact that you have different objects at each level in the tree: ConnectionGroup, ConnectionProfile, then TreeNode for all objects under that. Ideally we'd pass 1 object with all key info instead of the current split set of info
3. There's no support for ConnectionGroup actions

Overall this needs a bit of a design review - it'll do the job for now, but we could streamline in the future.

**Comment by kburtram** [comment]
Closing out older issues.
