### ISSUE TITLE
Showing the current Connected Server when hover over tab

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#1885]
Issue Type: <b>Feature Request</b>

At the moment you can't tell which server you are connected to. It would be nice to be able to hover on the tab and see the connected server for the current tab.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

**Comment by anthonydresser** [comment]
You can show the connection info in the tab name using the ` "sql.showConnectionInfoInTitle"` setting.

**Comment by alanrenmsft** [comment]
this has been implemented and enabled by default. setting name: queryEditor.showConnectionInfoInTitle
