### ISSUE TITLE
Tab Indicate Connection(development/production)

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#1887]
Issue Type: <b>Feature Request</b>

Currently there is a pink database icon, it would be useful to indicating are you connecting to Development or Production Server. Taken From the Defined Group.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

**Comment by anthonydresser** [comment]
I believe this is achievable using the `"sql.tabColorMode"` setting. Feel free to reopen if this does not solve your problem.
