### ISSUE TITLE
Add warning and parallelism icons to execution plan nodes. 

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18879]
Warning icon not displayed in ADS: 
![image](https://user-images.githubusercontent.com/6816294/160926017-81b17e14-0363-4678-9c80-6a0bd4ca1765.png)
Warning icon displayed in SSMS 
![image](https://user-images.githubusercontent.com/6816294/160926033-81398888-9dec-4be8-a9a3-6060a20eae8c.png)

Same for Parallelism 
![image](https://user-images.githubusercontent.com/6816294/160926169-2806b289-4080-41cb-a026-ec59c3237632.png)
SSMS:
![image](https://user-images.githubusercontent.com/6816294/160926208-f066eaea-2257-4e85-97d0-66c559aa4810.png)

**Comment by kburtram** [comment]
Fix merged to release branch
