### ISSUE TITLE
Open execution plan in result grid to graphical editor instead of plan xml

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#18880]
![image](https://user-images.githubusercontent.com/6816294/160926419-192d0f37-f78e-4c3c-a77f-bae03983342c.png)

**Comment by lewis-sanchez** [comment]
Closing this issue since this has been fixed already. Below is a gif of this working in the latest insiders build.

![Execution Plan - Open execution plan in result grid to graphical editor](https://user-images.githubusercontent.com/87730006/193882031-dee014f0-03c0-4260-b4f0-64380878c30b.gif)
