### ISSUE TITLE
Not Enough Room for the Grid

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#1888]
Issue Type: <b>Feature Request</b>

It may be better to have the result message into tab instead of underneath the grid, not enough room for grid result.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@datauduong thanks for the suggestion.  Having the Messages show in a separate tab would be nice user setting, or perhaps a new default.  To mitigate a little, you can try the `"sql.messagesDefaultOpen": false` user setting which will cause the Messages pane to be collapsed by default.

**Comment by kburtram** [comment]
The UX has been changed to match what is described in this issue.  Please let us know if you still have additional suggestions in this area.  Thanks!

**Comment by datauduong** [comment]
Thank you, all working as expected.
