### ISSUE TITLE
OE right click > Manage for databases opens the server dashboard instead of database

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#1891]
- SQL Operations Studio Version: Master 0b1e9c7

Steps to Reproduce:
1. Connect in OE and open the **server dashboard**
1. Close the server dashboard
2. Expand the server's database folder and open a **database dashboard**

Actual behavior: The server dashboard opens
Expected behavior: The database dashboard opens

As a workaround if you right click > manage again with the server dashboard already open it will open the correct dashboard.

Kevin addressed some part of this bug in #1883 but it looks like there's a bit more work to do.

**Comment by kevcunnane** [comment]
I thought I had fixed in my PR... still not fully fixed? Darn. It is definitely "better" than the last public release though - this failed 100% of the time there.

**Comment by MattIrv** [comment]
Updated with more specific repro steps. You have to first open the server dashboard, then close it, then open the database dashboard

**Comment by Charles-Gagnon** [comment]
Not able to repro this in master so closing this out
