### ISSUE TITLE
Timed out waiting for function project to be created

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18927]
1. Close all folders/workspaces
2. Right click on table and select "Create Azure Function with SQL binding"
3. Choose to create a new project
4. On the "Select a language" step just wait a while - eventually this timeout message will appear

We shouldn't be starting the timeout timer if the user still has information to enter since they can take as long as they want for that.

**Comment by VasuBhog** [comment]
Similar to #18925. Shouldn't start timeout while the user is entering prompts.

**Comment by VasuBhog** [comment]
This seems to be done by the extension of the azure functions. I start the timeout [here](https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-bindings/src/services/azureFunctionsService.ts#L63) after the user finishes the createFunction.
