### ISSUE TITLE
HTML table converted to MD table on Ctrl + S

### ISSUE THREAD

**Issue by claudiosvcc** [microsoft/azuredatastudio#18921]
- Azure Data Studio Version: 1.35.0
- OS Version: At least Mac and Windows

When MD has a HTML table tag, using **ADS notebook extension**, when edited using the **UI**, after saving it will try to convert it to MD table format.
Problem is, it will break formating. And for multi-line cells, MD format is a nightmare.
Hence, we need to keep HTML format eventually.

If using **MD editor**, table is preserved, but that's not easily discoverable.

Steps to Reproduce:
1. Add any HTML table using the MD editor.
2. Open it using the rich text UI editor
3. Make any change on text
4. Save it

**Actual:** It will convert the html table tag into MD table;
**Expected:** Keep HTML tables as is. Or at least allow us to set that in a given repository we do not want to convert it. 
**Reasoning:** While the MD table is desired for smaller text, it will be very hard to maintain on tables that were more sophisticated (or more complicated), e.g., when you have a specific cell in a row which is multi-lined.

E.g.,:
```html
<table style="border: 1px solid black;">
<tr style="border: 1px solid black;">
<td>This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. </td>
</tr>
<tr style="border: 1px solid black;">
<td>This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. This is a very long text and should be in multiple lines what won't be nice to edit in Md style table. </td>
</tr>
</table>
```

It will properly render on preview mode
![image](https://user-images.githubusercontent.com/3660616/161615646-2671d952-69d9-4c6d-bed8-aa28f075b452.png)

 

But if any editing happen on Preview mode, when saving, the table will be converted to:
![image](https://user-images.githubusercontent.com/3660616/161615705-27eba85c-bee4-4791-be9a-ee24b29f3700.png)

Does this issue occur when all extensions are disabled?: Yes/**No** -> This is using the Notebook Extension.

The only Extension I can file using report issue dialog is Kusto's

**Comment by chlafreniere** [comment]
Changed this into an enhancement to give users choice of converting to MD table or not; we've actually heard the opposite feedback as well (to go ahead and convert HTML tables into MD because they're easier to edit when looking at pure markdown).
