### ISSUE TITLE
'New Query' action launched using Cmd+N should only use active connection if it supports query provider

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1893]
- SQL Operations Studio Version:

Steps to Reproduce:
- Have a connection type that doesn't have a matching QueryProvider
- Connect to it in object explorer
- Use Ctrl/Cmd+N to open a new SQL file

Expected:
- It shouldn't be connected to the connection since it's not supported for querying
Actual:
- It is "connected" to that same connection, the DB dropdown is empty, and queries won't work.

**Comment by kburtram** [comment]
Cleaning up older issues.  I think in general Connection Providers should generally also be Query Providers.  I guess we could have some cases where this isn't so, and we don't enforce this constraint, but I'm not aware of where this gap is causing an experience problem with our current connection providers.
