### ISSUE TITLE
"Create Azure Function with SQL binding" doesn't prompt user about connection string setting

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18930]
1. Open existing function project
2. Right click on a table and create a new binding

The user is walked through adding the binding but is never prompted to select the connection string setting to use or whether to save the password in the settings file.

**Comment by VasuBhog** [comment]
Why would the user be asked to choose the connectionString? Since they pick a specific connection we are able to retrieve the connectionString directly from the connectionInfo they choose.
