### ISSUE TITLE
Duplicate "Must have Functions Project" warnings 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#18932]
1. Close all folders/workspaces
2. Right click on table and select "Create new Azure Function with SQL binding"

First this error pops up

![image](https://user-images.githubusercontent.com/28519865/161639644-3841637b-2bf2-498a-8ef1-eeeacbe4f59d.png)

Then if you click "Create Azure Function Project" this pops up

![image](https://user-images.githubusercontent.com/28519865/161639687-fae6aa5a-011d-45c6-a30a-aaab264f0c80.png)

This isn't a great experience to have essentially duplicate messages like this.

**Comment by VasuBhog** [comment]
Reopened for Port Request.
