### ISSUE TITLE
Renaming or moving a file under source control doesn't properly update the repo

### ISSUE THREAD

**Issue by jaapie** [microsoft/azuredatastudio#18942]
Issue Type: <b>Bug</b>

To reproduce this bug:

 1. Open a folder that is under source control (Git)
 2. Rename or move a file
 3. `git status` or the source control tab will show the ensuing carnage

Once you move or rename a file, git thinks the old one is deleted and that there is a new file to track. What should happen is that ADS should use `git mv <old> <new>` to properly move or rename a file.

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T17:53:45.534Z)
OS version: Linux x64 5.4.0-105-generic
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: enabled_on<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 1, 0|
|Memory (System)|31.19GB (3.67GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
import|Mic|1.5.0
powershell|ms-|2021.12.0
profiler|Mic|0.11.0
azdata-sanddance|msr|3.3.0
vim|vsc|1.10.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
The git provider ADS uses comes from VS Code. Could you see if you encounter the same behavior there - and if so open an issue in their repo?

**Comment by jaapie** [comment]
Certainly! I will try now.

**Comment by jaapie** [comment]
Confirmed: the issue is the same in VSCode. I will file an issue there.
