### ISSUE TITLE
No Azure settings in Azure Data Studio extensions

### ISSUE THREAD

**Issue by Philippe85** [microsoft/azuredatastudio#18954]
Issue Type: <b>Bug</b>

Hello,

I uninstalled and reinstalled Azure Data Studio (with and wihthout ssms 18.11), and I have no Azure settings under Extensions.
So, I can't add azure account to connect to my azure databases.

Thank you.

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.14GB free)|
|Process Argv|-r --server=frfrspsprdconfirm0001.database.windows.net --user=fr-cld-ppeuret@kpmg.fr|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.3
dacpac|Mic|1.8.0
schema-compare|Mic|1.12.0

</details>

**Comment by cheenamalhotra** [comment]
Closing as inactive. 
Please reopen if needed with steps to reproduce the same.
