### ISSUE TITLE
not able to add description to PK, FK and check constraints

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#18985]
as you can see, I have set the description but the script doesn't include it.

![image](https://user-images.githubusercontent.com/13777222/162549093-0ff4d659-3dbd-4364-a51f-98ff91a98364.png)

![image](https://user-images.githubusercontent.com/13777222/162549097-7f86d461-30be-49c2-9368-c6f6dda856dd.png)

![image](https://user-images.githubusercontent.com/13777222/162549105-b5954be3-a9d2-4024-b08b-d955bdb320bc.png)

**Comment by caohai** [comment]
I did a quick test, there are 3 scenarios.
1. Editing description for an existing constraint which already has description, works
2. Adding description to an existing constraint, works
3. Adding description to a newly created constraint, doesn't work

I'll take a look.

**Comment by kburtram** [comment]
Fix merged to release branch
