### ISSUE TITLE
Won't connect to sleeping Azure SQL

### ISSUE THREAD

**Issue by Roozle** [microsoft/azuredatastudio#18993]
Issue Type: <b>Bug</b>

If the target Azure SQL database is asleep, Azure Data Studio struggles to connect

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22593
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (19.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.6.0
alwayson-insights|mat|0.2.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
dacpac|Mic|1.8.0
import|Mic|1.5.0
profiler|Mic|0.11.0
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4

</details>

**Comment by smartguest** [comment]
Currently as it is right now, if connecting to a database directly, ADS will notify the user that the database isn't available at the moment and to try again later, this is correct as the database itself isn't currently available. This might be different if connecting to the server first and trying to get the database list. Will have to debug this every hour to see the result.
