### ISSUE TITLE
Running powershell commands that use -credentials dont work

### ISSUE THREAD

**Issue by pr1malc0de** [microsoft/azuredatastudio#19012]
- Azure Data Studio Version: 1.35.1
- OS Version: 10 (latest)

Steps to Reproduce:

1. Setup credentials to use
$Username = "Test"
$Password = "Pass"
$SecurePassword = $Password | ConvertTo-SecureString -AsPlainText -Force
$Script:Credentials = New-Object System.Management.Automation.PSCredential -ArgumentList $UserName, $SecurePassword
3. Run a command using credentials such as  Invoke-command -credential $Credentials.
4. Generates errors The user name or password is incorrect. For more information, see the about_Remote_Troubleshooting Help topic
5. Running same code in powershell outside ADS works

Does this issue occur when all extensions are disabled?: Yes/No No because it disables extensions required to run

**Comment by caohai** [comment]
Hi @pr1malc0de , are you talking about powershell in terminal or powershell kernel in notebook?

**Comment by pr1malc0de** [comment]
Appears to work after updating
