### ISSUE TITLE
autosave files

### ISSUE THREAD

**Issue by tekken22** [Microsoft/azuredatastudio#1902]
Issue Type: <b>Bug</b>

sql operation studio  resets my auto save setting, I had it OFF. There were two events
first I installed latest update, second my Windows got restarted at night while
sos was opened. I am not sure which  of these events triggered auto save even though I had it off for over a month and it was always asking if I want to save. Lost some queries that I did not intend to save.

This option should stay unchanged after updates or if closed by Windows. 

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2623 v4 @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (7.61GB free)|
|Process Argv|D:\3partyPrograms\micrsosft\sqlops\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment]
Thanks for reporting this @tekken22. Can you clarify if you're referring to the "files.autoSave" setting or some other setting? If so, do you know what value it got changed to? Or did it just not respect the setting the one time either when it updated or when Windows restarted?
