### ISSUE TITLE
[Notebook] Inconsistencies with notebook URI handling.

### ISSUE THREAD

**Issue by brettfo** [microsoft/azuredatastudio#19031]
The .NET Interactive extension provides notebook support for Azure Data Studio and in that extension we use the notebook's URI to differentiate between the various open notebooks.

So far we've found three separate values being returned by the notebook's URI `.toString()` method:

1. From `vscode.workspace.onDidOpenNotebookDocument` the value `notebook.uri.toString()` returns `"untitled:Notebook-1"` which is as expected.  Similarly `vscode.window.activeNotebookEditor.document.uri.toString()`.
2. Cell execution through the interface method `azdata.nb.IKernel.requestExecute` the value `cell.notebook.uri.toString()` returns `"[object Object]"` which is unexpected.
3. From languages services, e.g., through `vscode.HoverProvider.provideHover` the value `document.notebook` is returning `null` which is unexpected so we're forced to fall back to the cell's URI (e.g., `"untitled:notebook-editor-0"`) which isn't what we want.  We expect `document.notebook.uri.toString()` to behave like example 1.

**Comment by corivera** [comment]
Looks like item 2 was conveniently fixed by my commit earlier today: https://github.com/microsoft/azuredatastudio/commit/d98a42103576df5125934cc4a14dbdb15261cf2a

I'll look into item 3.
