### ISSUE TITLE
Notebook view pin/unpin doesn't update immediately

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19044]
Not a regression, present in 1.35.1 as well

1. Open up workspace with Notebooks in it
2. Click the "pin" icon next to a Notebook

Nothing appears to happen. It does seem like the pin/unpin action is working in the background though - if I reload the window then the icon displays correctly. The icon just isn't updating correctly.

**Comment by chlafreniere** [comment]
@barbaravaldez has an item been added to the test plan to catch this in future releases?
