### ISSUE TITLE
Increase/Decrease Text Editor* Font Size only with Scroll Wheel (Not Zoom!)

### ISSUE THREAD

**Issue by JeffBusterCase** [microsoft/azuredatastudio#19041]
**Is your feature request related to a problem? Please describe.**
Sometimes I want to get a better view of some part in the text, but the current Zoom with Ctrl + makes everything implode in the screen. Making it difficult to edit, and no sense in using it...
![image](https://user-images.githubusercontent.com/12688410/163190567-9e0d7f5b-4b7a-41df-85d1-162db18df29f.png)

**Describe the solution or feature you'd like**
If we could increase and decrease only the editor font with the scroll wheel, it would be a lot faster, easier and simplier to see/edit.

**Describe alternatives you've considered**
Using C + shortcut.

**Additional context**
How it should be after increasing with the scroll wheel:
![image](https://user-images.githubusercontent.com/12688410/163190246-9d686ca5-21d4-49d1-9b22-972f25bd4c90.png)

**Comment by caohai** [comment]
Can you try this? worked for me.
> Out of Box solution for zoom in/out for text only:
> 1. Ctrl+Shift+P (or View->Command Palette...)
> 2. Type Open User Settings
> 3. Edit settings.json
> 4. Add "editor.mouseWheelZoom": true
> 5. Save it.
> 
> You can use your mouse wheel to zoom in or zoom out only text in the text box.


https://stackoverflow.com/questions/41540781/is-there-a-way-in-vscode-to-only-zoom-in-on-the-editor/41684631#41684631

**Comment by JeffBusterCase** [comment]
Cool!!! But why isn't this a default setting?
