### ISSUE TITLE
"Show Query Plan XML" opens editor that prompts to save as XML, not sqlplan

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19054]
When viewing a query plan and select "Show Query Plan XML" a new editor is opened with the XML language set. This is nice for highlighting and whatnot, but if the user then tries to save that file it prompts to save as xml instead of sqlplan.

**Comment by erinstellato-ms** [comment]
@Charles-Gagnon This is consistent behavior - I expect that if we open the XML in a new editor, and a user wants to save it, it should save as .xml.  If they want to save the .sqlplan file, just go back to the graphical plan, right-click and save it.
