### ISSUE TITLE
.Net Interactive/Jupyter extensions log errors on startup

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19066]
![image](https://user-images.githubusercontent.com/28519865/163279569-f6372a4a-6eed-4908-8f2f-ce4230cd9a9c.png)

**Comment by Charles-Gagnon** [comment]
Adding it to extensionAllowedProposedApi in product.json should fix this

**Comment by corivera** [comment]
Reopening for port request.
