### ISSUE TITLE
Table designer - period column error isn't very clear about the issue or how to resolve it

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19078]
1. Create a new table
2. In the general properties select "System Versioning enabled"

Immediately an error appears saying `System versioned tables must have the period columns defined.` 

Couple of problems : 
1. There's no indication of what these are or how to create them. 
2. I eventually stumbled across the "System Versioning" section in the column properties, but even adding a `Row start` and `Row end` column it still gave the same error. It wasn't until I happened to notice in a sample script on the docs site that the types must be `datetime2` (I just had datetime)
3. During all this I was unable to attempt to publish to see what the server told me the error was. I could have copied the script from the tab and ran it manually, but that seems like a lot of extra hassle. 

While the issue here is for this specific scenario, I think this is applicable in general to the feature. How are users supposed to discover what these errors mean or how to resolve them? It might be useful to let users publish the script even with errors so at least the engine can come back with its own errors that might help figure out what's the matter.

**Comment by alanrenmsft** [comment]
instead of allowing publish when the state is invalid, I think we should make the validation error more informative, for example, adding a link to our docs site.
