### ISSUE TITLE
Table Designer - Can't change type of period columns after setting "Generate Always As" setting

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19076]
1. Add new column
2. In the column properties set "Generated Always As" to Row start or row end

Now the type field is made readonly. Is there a reason for this? I can make the column a non-period column again, change the type and then make it a period column just fine.

**Comment by alanrenmsft** [comment]
the logic is something we copied from SSDT not sure about the reason behind it.
@caohai could you please take a look? 
also for row start/end columns, is the data type always required to be datetime2, if so, we can probably automatically change it to datatime2.

**Comment by caohai** [comment]
@alanrenmsft 
I took a brief look and from official [doc](https://docs.microsoft.com/en-us/sql/relational-databases/tables/creating-a-system-versioned-temporal-table?view=sql-server-ver15#important-remarks)
> A system-versioned temporal table must have a primary key defined and have exactly one PERIOD FOR SYSTEM_TIME defined with two datetime2 columns, declared as GENERATED ALWAYS AS ROW START / END

Currently column type editability will be set to false if it's a `TemporalGeneratedAlwaysColumn`. I think it's reasonable to automatically set the col to type `datatime2` in this case. I'll send a PR to fix this unless there are other concerns.

**Comment by alanrenmsft** [comment]
@caohai is RowStart and RowEnd only designed for temporal table? if so it is safe to auto change data type to datatime2, otherwise we have to leave it as is.

**Comment by caohai** [comment]
@alanrenmsft based on this doc I believe `datatime2` is required for syntax `GENERATED ALWAYS AS ROW { START | END } `
https://docs.microsoft.com/en-us/sql/t-sql/statements/create-table-transact-sql?view=sql-server-ver15#:~:text=ROW-,datetime2,-START%3A%20NOT%20NULL

![image](https://user-images.githubusercontent.com/21186993/163501595-d1d1dfb4-4886-4912-b195-432873b78dab.png)

**Comment by caohai** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/19321
