### ISSUE TITLE
No ability to see additional information in Properties Window

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#19079]
Version: 1.36.0-rc1 (user setup)
Commit: 8bed83422692070b0231a9fbba3feaed22625ef1
Date: 2022-04-13T22:39:52.200Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Steps to Reproduce:

1. Open a query window in ADS
2. Execute a query with CTRL + M to get the actual plan 

USE WideWorldImporters;
GO
SELECT [CustomerID], SUM([AmountExcludingTax])
FROM [Sales].[CustomerTransactions]
WHERE [CustomerID] = 1092
GROUP BY [CustomerID];
GO

3.  Open the Properties window, click on the SELECT icon.
4. Find Set Options (should be near the top).  There is a ... to allow you to see the additional options set for the query, but you cannot select anything.

![image](https://user-images.githubusercontent.com/98599126/163288757-dfc82d98-631d-4b01-9b98-df122767070f.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
It's kind of weird too that it seems to just be a stringified version of the fields below it. Do we even need to show that there?

(but regardless, we should have hover tooltips or scrollbars for this stuff)

**Comment by erinstellato-ms** [comment]
@Charles-Gagnon My request would be that we provide the same options that currently exist in SSMS, which is that there's an option to expand the line to see more info (and honestly, if we did this for more of the entries, that would be great because the Properties window in ADS is very, very, very long.

![image](https://user-images.githubusercontent.com/98599126/163399169-33a9bc21-4646-4149-ac7b-3c18bb0758b9.png)

Expanded:
![image](https://user-images.githubusercontent.com/98599126/163399229-cf28d1c8-e75b-4f0f-a972-1fc0501f2849.png)

**Comment by Charles-Gagnon** [comment]
That would be fantastic, and having the "section titles" bolded is also a much better experience.

**Comment by Charles-Gagnon** [comment]
Probably, we can have separate issues tracking adding the tooltip to the fields and another that tracks adding the collapse and bolding. @aasimkhan30 that sound good to you?

**Comment by aasimkhan30** [comment]
IIRC, the complete information is shown as tooltips when the fields are hovered.

**Comment by erinstellato-ms** [comment]
@aasimkhan30 True, when you hover over the field the complete info shows up.  But if I want to copy that info elsewhere, it's not easy to do.  I would either have to screen shot it (which is then image and not text), or go into the XML.

**Comment by erinstellato-ms** [comment]
I created an issue for adding collapse and bolding: https://github.com/microsoft/azuredatastudio/issues/19127

And one for copying info from the properties pane: https://github.com/microsoft/azuredatastudio/issues/19128

**Comment by erinstellato-ms** [comment]
Updates made to properties window now allow entire text to be displayed when the cell is hovered over, and it can be copied.  For different sections, shading has been used instead of bolding.
