### ISSUE TITLE
"No kernel found" errors for .NET Interactive kernel completions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19070]
1. Create new .NET interactive notebook and add a code cell (I've repro'd this with both sql and C# cells), then start typing in it

I'm seeing a bunch of these errors, and it doesn't seem like intellisense is working

![image](https://user-images.githubusercontent.com/28519865/163282616-ff2f83e1-250c-4b44-beaf-4282a23bbdf4.png)

**Comment by Charles-Gagnon** [comment]
Maybe same issue as https://github.com/microsoft/azuredatastudio/issues/18639

**Comment by corivera** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/18639
