### ISSUE TITLE
Table designer doesn't prompt user to save before the app closes

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19080]
1. Open designer for new table
2. Make some changes so the state is dirty
3. Exit ADS

Instead of being prompted if you want to save the app immediately exits - losing all progress. This is fine for normal editors which are backed up, but the designer editors aren't and so the user just loses everything.

**Comment by alanrenmsft** [comment]
@abist could you please take a look at this one? and see whether we can show a prompt when the app is closing?

**Comment by Charles-Gagnon** [comment]
Take a look at the task code - they hook into something (from VS Code land) to prompt the user whether they really want to exit if a task is running.
