### ISSUE TITLE
The query editor ran into an issue...

### ISSUE THREAD

**Issue by ecassidy-etc** [microsoft/azuredatastudio#19099]
Issue Type: <b>Bug</b>

1. Open Azure Data Studio - Insiders (Fresh, no open queries)
2. Open a new query (SQLQuery_1)
3. Connect to a database
4. Run a query (`SELECT EQPSYSID, ControlLevel FROM acEquipMaster`)
5. Open a new query (SQLQuery_2)
6. Connect to a database (in my case, it's the same one)
7. Run a query (`SELECT EQPSYSID, ControlLevel FROM acEquipMaster`)
8. Switch back to SQLQuery_1
9. Run the query again
10. Switch back to SQLQuery_2
    - See error: "The query editor ran into an issue and has stopped working. Please save and reopen it."
    - Switching back to SQLQuery_1, see the same error

Azure Data Studio version: azuredatastudio-insiders 1.36.0-insider (fcd4c6e15bbe7f960c94e4dd1f614298dd18d7ce, 2022-04-13T05:25:49.733Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 x 2195)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|39.89GB (9.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.47.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.12.1
sql-assessment|Mic|0.6.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by ecassidy-etc** [comment]
Fixed by #19046 that was just pulled in minutes after I submitted this 🤦‍♂️

**Comment by Charles-Gagnon** [comment]
Does that actually fix your issue? The linked PR was for fixing query plan, not anything to do with normal query execution.

**Comment by ecassidy-etc** [comment]
I saw an update was available just after submitting and now I can't reproduce the error. That PR was pulled in minutes after I submitted this and the same error is screenshot in the issue. Figured it looked related.
