### ISSUE TITLE
Allow drag drop columns from serverExplorer table columns folder to query editor

### ISSUE THREAD

**Issue by psimoneau22** [Microsoft/azuredatastudio#1909]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:

Allow drag drop columns from serverExplorer table columns folder to query editor.  Dragging the 'columns' folder listed under a database table to the query editor will drop a comma delimited list of columns.   This is very useful for example when you want to select all columns except a few, and not having to write out each column name.

**Comment by anthonydresser** [comment]
dupe #1295
