### ISSUE TITLE
SQL Bindings - When creating new project if the user adds it to an empty workspace we never add the binding

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19109]
1. Run the "Create Azure Function with SQL Binding" command in an empty workspace
1. When prompted to create a new project do so
2. Go through all the project creation prompts
3. When prompted where to open the project, select "Open in current window" or "Add to workspace"

The project is created successfully, but then VS Code reloads the window because it added the item to an empty workspace (known behavior). This means that we never finish the "Add binding" flow and end up with just the AF project without a binding added. 

This also happens when running from the context menu command, and is not a regression (it's always been like this as far as I can tell)

**Comment by VasuBhog** [comment]
Yeah this will be solved once we refactor to using one createAzureFunctionAPI

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/18929
