### ISSUE TITLE
"Create SQL Binding" prompts user for language/framework if creating new project

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19116]
1. Run "Create Azure Function with SQL Binding" command in an empty workspace
2. When prompted, select "Create new project"

The create project flow then goes on to prompt the user select a language and target framework. We shouldn't be doing this since we only support C# and netcoreapp3.1 currently. 

The root issue here is a bug in the AF extension : https://github.com/microsoft/vscode-azurefunctions/issues/3115 - when no `folderPath` is given then the create project flow loses all options given to it.

**Comment by VasuBhog** [comment]
Does the prompt happen before or after selecting the template for creating a new azure function project?
