### ISSUE TITLE
Run Notebooks with Parameters fails silently if notebook is Untitled

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#19114]
Running Notebooks with Parameters (from the notebook toolbar) is unsupported for Untitled notebooks, but currently we don't throw an error when the user tries to do so. They can go through the steps of setting the parameters, but then a new notebook doesn't open and there's no error notification as to why. Additionally, if you keep all the parameters the same, a new notebook will be opened that's exactly the same, but has no Injected Parameters cell.

**Comment by chlafreniere** [comment]
@VasuBhog is this expected behavior?

**Comment by VasuBhog** [comment]
@chlafreniere yes we do not support untitled notebooks. But can make this experience better.
