### ISSUE TITLE
Provide ability to copy text from cells in the Properties pane for a query plan

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#19128]
**Is your feature request related to a problem? Please describe.**
Users sometimes have a need to copy information from the Properties pane for use elsewhere

**Describe the solution or feature you'd like**
Provide ability to copy text from cells in the Properties pane for a query plan

**Describe alternatives you've considered**
I do not know of an alternative...

**Additional context**
Within the Properties pane, you can highlight a cell, but if you right-click on it, there is no option to copy:

![image](https://user-images.githubusercontent.com/98599126/163631865-9cc95890-d5ae-43be-ae8f-7bac0ff9842a.png)

This does exist in SSMS:

![image](https://user-images.githubusercontent.com/98599126/163631895-92b1a97b-d9de-49a4-a7e0-6d8e5bd4ef95.png)

**Comment by aasimkhan30** [comment]
already fixed by PR #20208
