### ISSUE TITLE
WHere does ADS store connection passwords?

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#19132]
Issue Type: <b>Bug</b>

1. create a new SQL Server connection using a sql login and check box to save password
2. connection works
3. Notice that in settings.json no password is displayed
4. in connections pane, disconnect, then reconnect
5. connection works

SO, where is the password stored for use when the connection is opened?

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.22598
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-oracle|Mic|0.1.2
azuredatastudio-postgresql|Mic|0.2.7
import|Mic|1.5.0
net-6-runtime|Mic|1.0.0
powershell|ms-|2021.12.0

</details>

**Comment by abist** [comment]
@gbritton1 We actually intentionally remove the password from the settings.json file so it doesn't reside in plaintext there. When you put in your password, we use the OS level password storing mechanism (Windows Credential Manager in your case) to store the password and strip it from the settings file. The password is retrieved again from the credential manager as well.

**Comment by Charles-Gagnon** [comment]
Closing this as there doesn't seem to be any issue being reported. Feel free to use https://github.com/microsoft/azuredatastudio/discussions if you just have general questions on specific functionality!
