### ISSUE TITLE
Publish error

### ISSUE THREAD

**Issue by PyMach** [microsoft/azuredatastudio#19155]
- Azure Data Studio Version: 1.35.1
- OS Version: Windows 10

Steps to Reproduce:

1. From your database project change the type of identity column for example  BIGINT to INT
2. Build and try to publish

Here is the Error Message
******************************
Deploy dacpac: Could not deploy package.
Warning SQL72015: The type for column Module_id in table [dbo].[Module] is currently BIGINT IDENTITY (1, 1) NOT NULL but is being changed to INT IDENTITY (1, 1) NOT NULL. Data loss could occur and deployment may fail if the column contains data that is incompatible with type INT IDENTITY (1, 1) NOT NULL.

Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 50000, Level 16, State 127, Line 6 Rows were detected. The schema update is terminating because data loss might occur.
Error SQL72045: Script execution error. The executed script:
IF EXISTS (SELECT TOP 1 1
FROM [dbo].[IntakeModule])
RAISERROR (N'Rows were detected. The schema update is terminating because data loss might occur.', 16, 127)
WITH NOWAIT;

******************************

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by PyMach** [comment]
I confirm that the table "Module" it empty.

**Comment by kisantia** [comment]
Can you try using a publish profile and setting BlockOnPossibleDataLoss to false. The default for this setting is true, which causes the operation to terminate regardless if the target database contains data. Example of how to create a publish profile and other potential workaround is in this issue #15436

**Comment by PyMach** [comment]
Its working after following your above instructions.  Thank you!
