### ISSUE TITLE
Tab Behavior inside Table Designer

### ISSUE THREAD

**Issue by Peter-Schneider** [microsoft/azuredatastudio#19160]
While inside the table designer the user should stay inside the columns grid when pressing TAB. Right now it switches to the Columns Properties panel.

**Comment by alanrenmsft** [comment]
You should be able to navigate through all the cells in the columns grid by pressing tab key, after that the keyboard focus will go to the next focusable element which is the column properties. as shown in the GIF below.
![tab-navigation](https://user-images.githubusercontent.com/13777222/164325934-e7c9d047-15f5-458d-aebd-1f9b5555c03e.gif)

we can't trap the keyboard focus inside the grid, it will an accessibility bug if we do it.
