### ISSUE TITLE
Execution plan zoom does not zoom the badge icons 

### ISSUE THREAD

**Issue by aasimkhan30** [microsoft/azuredatastudio#19171]
![image](https://user-images.githubusercontent.com/6816294/164527199-7d4907b8-4f83-415f-b937-64ef8e73a37a.png)

Steps to reproduce:
1. Open an execution plan with badge icons
2. Click on zoom (either + or -)
3. the badge icons do not scale with the graph

**Comment by erinstellato-ms** [comment]
FYI, this was also noted externally https://twitter.com/josh_the_coder/status/1517556064388009985?s=20&t=jOgJatUegL7vQhqgNp3uSA

**Comment by aasimkhan30** [comment]
This issue is fixed in the insiders and will be release in June stable release.

**Comment by kburtram** [comment]
Fix merged to release/1.36
