### ISSUE TITLE
Command #!connect kql fails with "Required command was not provided" 

### ISSUE THREAD

**Issue by gitmadness** [microsoft/azuredatastudio#19189]
Issue Type: <b>Bug</b>

1. Create new Notebook
2. Insert the following code in the same Code cell
```
#r "nuget:Microsoft.DotNet.Interactive.Kql,*-*"

#!connect kql --kernel-name TestTestTest --cluster "https://help.kusto.windows.net" --database "Samples"
```
3. Run all and get the following error:
```
Error: Required command was not provided.
Unrecognized command or argument 'kql'.
Unrecognized command or argument '--cluster'.
Unrecognized command or argument 'https://help.kusto.windows.net'.
Unrecognized command or argument '--database'.
Unrecognized command or argument 'Samples'.
```
4. Works if #!connect is run from a separate Code cell

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (19.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|Mic|0.5.4
dotnet-interactive-vscode|ms-|1.0.3175020
jupyter|ms-|2021.8.1046824664

</details>

**Comment by chlafreniere** [comment]
@corivera can you help here?

**Comment by corivera** [comment]
Sure. This is probably a nuget issue, since none of the kql stuff is showing up at all.

**Comment by corivera** [comment]
I'll ask the Interactive folks if this is by design.

**Comment by corivera** [comment]
Looks like this is a bug in Interactive, so I'll open an issue in their repo.
