### ISSUE TITLE
Create Table/Edit Table dialog is very buggy

### ISSUE THREAD

**Issue by akshay-pande** [microsoft/azuredatastudio#19182]
Issue Type: <b>Bug</b>

1. Try to create a SQL table. If you don't leave the text field after you enter something, like field name or datatype length, the value reverts to the previous one
2. Very buggy when you try to edit an existing table. For e.g. I created a duplicated field by mistake which gave an error while saving. But after I removed the field and tried to save and publish again, it kept giving me an incorrect error. 

I think this feature is still unstable and needs a lot of development still

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.85GB (0.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.13.1
sql-database-projects|Mic|0.16.1
sql-prompt|Red|0.2.10
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by alanrenmsft** [comment]
@akshay-pande We've made improvements for both of the issues you mentioned in our recent ADS release that went out a couple days ago, Could you please upgrade and try again? 

Please definitely let us know the issues that you ran into so that we can keep improving it.

**Comment by alanrenmsft** [comment]
please reopen if those issues are not resolved for you after upgrade and share the error message with us for debugging.
