### ISSUE TITLE
Model View: Make info field part of FormComponent, rather than FormItemLayout

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#1918]
Setting the info/help text for a component via FormItemLayout.info can be pretty awkward when dealing with a complex layout, since it has to be set via FormContainer.addFormItem. The help bubble is set per FormComponent though, so it makes sense to make it a field for FormComponent, similar to the required field.

**Comment by kburtram** [comment]
Closing out old issues.
