### ISSUE TITLE
Fix graph icons in Object Explorer to not cause additional metadata queries

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#19180]
- Azure Data Studio Version: `main`

The recent change to have icons for graph node and edge tables caused a significant perf regression when expanding OE Tables folder.  This is the underlying bug tracked with issue https://github.com/microsoft/azuredatastudio/issues/19166, which is being addressed in 1.36.1 hotfix.  This issue is tracking fixing this issue in main for the June release by retaining the graph icons without introducing the additional overhead during folder expansion.

Steps to Reproduce:

1. Connect to SQL Server 
2. Expand Tables folder

Expected: Minimal amount of SQL queries executed to get table list and essential properties

Actual: A unique query for each table getting stretchdb properties causing significant perf regression and timeouts expanding the folder.

**Comment by alanrenmsft** [comment]
fixed by https://github.com/microsoft/sqltoolsservice/pull/1633
