### ISSUE TITLE
Results Pane Column Filter Drop Down Missing

### ISSUE THREAD

**Issue by jesman3** [microsoft/azuredatastudio#19186]
- Azure Data Studio Version: 1.36.1
- OS Version: Windows 11

Steps to Reproduce:

1.Installed Azure Data Studio on a new computer including any updates
2.Run a query and the columns in the results pane do not have the drop down selector to access the filter and sorting options.
3.I looked all over for a setting to enable this and I only found the setting that limits the functionality based on row count and the query I am testing with has fewer rows than the setting limits you to.

Does this issue occur when all extensions are disabled?: Yes

![ADS_NoColumnDropDown](https://user-images.githubusercontent.com/12089698/164790817-6e488eb8-d47b-401c-9195-814afbda7aeb.png)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft I can't repro this myself, I seem to recall the filter being disabled in some circumstances though - am I remembering correctly?

**Comment by alanrenmsft** [comment]
@jesman3 have you enabled preview features? this feature is still a preview feature right now.
![image](https://user-images.githubusercontent.com/13777222/164863125-92a1295b-1ab3-4c9a-ba45-01806ad37b79.png)

**Comment by alanrenmsft** [comment]
please reopen if still can't get it to work.
