### ISSUE TITLE
Easy database push

### ISSUE THREAD

**Issue by MostHostLA** [microsoft/azuredatastudio#19193]
Issue Type: <b>Feature Request</b>

Assuming a local machine has a database - named and tagged, from which the initial deployment occurred - it would be nice to be able to single click a button to apply all the local changes directly to Azure instead of having to go in, delete the database, and re-publish

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

**Comment by alanrenmsft** [comment]
@MostHostLA It is not very easy for me to figure out which feature are you talking about, could you please elaborate a bit more?

**Comment by MostHostLA** [comment]
"It is not very easy for me to figure out which feature are you talking about"
Well, it's a feature request, so I hope it's normal you can't figure out what feature I'm talking about as it doesn't currently exist?

In essence:
There is currently no way (I know of ) to keep a local database and an azure database "in sync" on request.
From azure data studio one can publish again after deleting the existing database, but it's not very intuitive / also requires access in MSSQL, and/or running queries to re-establish the user access.

https://stackoverflow.com/questions/71976008/best-way-to-get-azure-and-local-sql-server-development-databases-to-sync-on-requ

I would love a feature that just "syncs" any 2 database with one another.
Without necessarily having to delete a database, particularly when the changes one has made are just to the data and not to the structure but not limited to that.
It should probably be handled internally as a drop table - create table - populate table - recreate keys.
And I'll probably have to script something to that effect myself for the time being.

**Comment by kisantia** [comment]
closing issue. Feel free to reopen if you have any more questions on schema compare or sql projects
