### ISSUE TITLE
Add further Validation for SQL Binding Prompts 

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#19209]
SQL Bindings 0.0.1

Add Further validation to handle object names with and without schema, bracket-quoted names (mix and match those).

Table Manually entered by the user to be used in the SQL binding parameters.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
@chlafreniere @VasuBhog Putting this here for discussion to make sure we're all on the same page. 

Should we actually be doing this? If the user enters it manually I think trying to do any sort of parsing/validation is likely to just cause issues down the line if we miss a specific case or there's a bug.

This kind of thing is easy enough for users to fix and won't cause any failures if they mistype so I don't see a problem with just taking whatever they give us as long as it's not empty.
