### ISSUE TITLE
Syntax highlighting: Nested multi-line comments not properly highlighted

### ISSUE THREAD

**Issue by bensherman1** [microsoft/azuredatastudio#19205]
When executed, the syntax below is valid and has nothing to execute. Based on the syntax highlighting, it looks like it should return a single row result set with the value of `1` and/or error out.

```sql
/*
SELECT 'a'
-- foo bar
/* far bin */
SELECT 1
*/
```

**Comment by Xanadu333** [comment]
Hi, I am having the same issue and would like it to be reviewed/solved.
Note: SSMS works perfectly fine with this concept and yet Azure Data Studio doesn't.

**Comment by Xanadu333** [comment]
Is this not an issue worth looking forward to?

**Comment by OwlsSleeping** [comment]
Duplicate of #848 

Also related thread with more detail on the vscode extension repo-
https://github.com/microsoft/vscode-mssql/issues/1014
