### ISSUE TITLE
Unable to add account via 'Accounts' after reinstall

### ISSUE THREAD

**Issue by Thijs9955** [microsoft/azuredatastudio#19213]
- Version: 1.36.1 (user setup)
 - Commit: e56e1d931bbb110fe8f24751423c4e184bb8f22d
 - Date: 2022-04-21T21:25:10.399Z
 - VS Code: 1.59.0
 - Electron: 13.6.6
 - Chrome: 91.0.4472.164
 - Node.js: 14.16.0
 - V8: 9.1.269.39-electron.0
 - OS: Windows_NT x64 10.0.19044

When trying to add an Microsoft account, the application gets stuck in the 'loading accounts'. I am still able to close this accounts window.

Steps to Reproduce:

1. Reinstall Azure Data Studio
2. Click on 'Accounts' in left corner 

Does this issue occur when all extensions are disabled?: Yes

![afbeelding](https://user-images.githubusercontent.com/104421018/165255367-2275480d-a92e-4805-a156-775f2ce7d48c.png)

**Comment by cssuh** [comment]
Closing as sufficient logs have not been provided. @Thijs9955 please feel free to re-open this if you are able to attach some more logs.

**Comment by Thijs9955** [comment]
Unfortunately I cannot do that anymore. To fix the issue I reinstalled windows and Azure Data Studio. This fixed the issue.

Van: github-actions[bot] ***@***.***>
Verzonden: vrijdag 6 mei 2022 22:18
Aan: microsoft/azuredatastudio ***@***.***>
CC: Thijs van Berkel ***@***.***>; Author ***@***.***>
Onderwerp: Re: [microsoft/azuredatastudio] Unable to add account via 'Accounts' after reinstall (Issue #19213)


We need more info to debug your Azure Active Directory issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster.

  *   In the settings menu, find the setting titled Azure: Logging Level and select the Verbose option
  *   Run the process that produces your error
  *   Open command palette (Click View -> Command Palette)
  *   Run the command: Developer: Open Logs Folder
  *   Follow this path to find the Azure Accounts log file: [default log folder]/exthost1/output_logging_[earliest timestamp]/#-Azure Acounts.log
  *   Please attach the Azure-Accounts.log file to the issue.
