### ISSUE TITLE
No longer able to minimize items in Notebook viewlet

### ISSUE THREAD

**Issue by joberume** [microsoft/azuredatastudio#19210]
Issue Type: <b>Bug</b>

After new update, I am unable to minimize items in outline for the Notebooks viewlet
![image](https://user-images.githubusercontent.com/52225468/165188726-094aa53c-65c2-45c2-8b18-f0b0fbf9e086.png)

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 3950X 16-Core Processor             (32 x 3493)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.94GB (89.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by joberume** [comment]
Looks like it does not repro if I open via Folder and not workspace. Another notable feature about my workspace, is that perhaps some of the books I have opened, may contain notebook files in the TOC that do not exist (resulting in an error modal dialog box). Not sure if this has anything to do with the issue, but though of mentioning it.

**Comment by chlafreniere** [comment]
@barbaravaldez can you take a look?

**Comment by barbaravaldez** [comment]
Closing since we cannot repro on latest build
