### ISSUE TITLE
Allow Users to Select a Lower Row Number When Editing Data

### ISSUE THREAD

**Issue by shuby722** [microsoft/azuredatastudio#19221]
**Is your feature request related to a problem? Please describe.**
When I go to edit data the default `Select TOP (1000)`  is way too large of a select for single row editing capabilities

**Describe the solution or feature you'd like**
To be able to choose the number of rows I want to select/edit

**Describe alternatives you've considered**
Have a lower default Selection body for initial table load speed since you can change that once it loads.

**Additional context**
n/a

**Comment by dfalso** [comment]
In SSMS, the Tools->Options->SQL Server Object Explorer config allows setting values for both Edit and Select. Both of those also support a value of 0 - no TOP clause at all (this is what my team uses). We'd appreciate the same config for the Object Explorer in ADS.

**Comment by dfalso** [comment]
Also, this feels similar to #7197 
Maybe you can merge these issues.

**Comment by shuby722** [comment]
Only reason it was not merged originally is the fact that I have seen multiple requests opened and minimal movement but I agree. 
Closing to focus the one issue in progress.
