### ISSUE TITLE
Images/Icons disappearing on refresh/keeping stagnant

### ISSUE THREAD

**Issue by goyal-anjali** [microsoft/azuredatastudio#19226]
Original state ->
![image](https://user-images.githubusercontent.com/66509246/165503444-c8756381-4bfb-4ef4-8857-bc00989811c8.png)

After disappearing ->
![image](https://user-images.githubusercontent.com/66509246/165503396-5410af16-c667-4329-a054-698ef3f279a8.png)

Raw html component when image/icon is visible->
div title="" class="model-view-component-icon-150 icon" style="background-size: 14px 14px; margin: 3px 3px 0px 0px; padding: 0px; width: 14px; height: 14px;"></div>

Raw html when image/icon disappears ->
div title="" class="model-view-component-icon-132 icon" style="background-size: 14px 14px; margin: 3px 3px 0px 0px; padding: 0px; width: 14px; height: 14px;"></div>

When the image is visble -
Src of the image 
<html>
<body>

Current source: | vscode-file://vscode-app/c:/Users/anjaligoyal/Back…duct/AdsOracleAssessment/images/successStatus.svg
-- | --

</body>
</html>

**Comment by goyal-anjali** [comment]
@alanrenmsft @aasimkhan30 Recalling the issue

**Comment by alanrenmsft** [comment]
@aasimkhan30 are you taking care of this issue?

**Comment by aasimkhan30** [comment]
Yes, I am investigating this issue.

**Comment by goyal-anjali** [comment]
Following up @aasimkhan30

**Comment by goyal-anjali** [comment]
Hey @aasimkhan30, any updates on this issue?

**Comment by aasimkhan30** [comment]
@goyal-anjali , I have taken this issue for the December release
