### ISSUE TITLE
Schema Compare file not reusable for Database Projects

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#19228]
Issue Type: <b>Bug</b>

Schema Compare file (.SCMP) not reusable when Database Projects is either source or target.  When starting from Database Projects (icon on left-bar) > right-click project, choose Manage > click Schema Compare > click Open .scmp file > choose .scmp file from location: the Schema Compare window opens properly, however the .sqlproj file that was previously saved as a reference in the .SCMP file is no longer recognized (the source or target side, whichever the .sqlproj was on, is blank).  When you click the ellipse and try to choose your .sqlproj file, it allows you to choose one, but you then receive `"Schema Compare failed: Object reference not set to an instance of an object."` message.

At this point, the .SCMP file seems to produce the same error even if you to switch a .DACPAC file and then try to compare.  If I close out of the Schema Compare tab, go back to Manage page for the Database Project and try to start the process again, even using an .SCMP file which was save with a db & .DACPAC as it's comparison, results in the same error.

It seems like this error is coming from the database side of the comparison.  Once I change the connection & re-connect to the database, the `"Schema Compare failed: Object reference not set to an instance of an object."` error goes away.  Only after that step can I go back and point the schema compare at the .sqlproj file I was originally working with.

Extension version: 1.13.0
Azure Data Studio version: azuredatastudio-insiders 1.37.0-insider (4e849f0d601f9e5210f3612458d8f1effae9d527, 2022-04-27T05:28:05.548Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (15.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@udeeshagautam @Benjin scmp support for sql projects wasn't added when support for schema compare and update project was added, right?

**Comment by tecodan** [comment]
Any updates on this? 
I am experiencing the exact same issue (ADS v1.37.0, schema compare tool v1.14.0, SQL Database objects v0.17.1)
