### ISSUE TITLE
Unable to login when user is required to change password on first login

### ISSUE THREAD

**Issue by mikesabin** [microsoft/azuredatastudio#19246]
Issue Type: <b>Bug</b>

When setting up a new connection to a SQL Server from Azure Data Studio (ADS) on a macintosh; we are unable to complete the setup and connection for a user account that is configured to change password on first login.    

ADS seems to connect to the server, and replys with "login failed for user '***'. Reason: The password of the account must be chnaged"

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:26:00.881Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cssuh** [comment]
Hi @mikesabin , is this for an Azure SQL Server or a local server?

**Comment by mikesabin** [comment]
It was for a local server.   As a workaround, I was able to open a terminal session with Azure Data Studio and issue the sqlcmd like: sqlcmd -U someuser -P s0mep@ssword -z a_new_p@a$$w0rd

It did not work when I was opening a MACOS terminal session outside of ADS and attempting to perform the same command, and then connect to the SQL Server via ADS.

**Comment by cheenamalhotra** [comment]
@mikesabin 

We have an open issue to track this feature request: #605 
Please use the same to track further progress on the same.

Thanks!
