### ISSUE TITLE
Feature from Visual Studio 2022 & SSMS: Ability to paste column of multi-line selection using ALT - Click and drag

### ISSUE THREAD

**Issue by dghViperdude0** [microsoft/azuredatastudio#19240]
I saw that Issue #1757 (https://github.com/microsoft/azuredatastudio/issues/1757) is closed, but a feature that I frequently use in **Visual Studio 2022 and SSMS** while editing TSQL code, is still not yet available in Azure Data Studio and Visual Studio Code.

I'm referring to the **[ALT - click and drag down]** feature that **pads out** lines below with tabs or spaces, creating an immediate & **aligned** system allowing you to paste a column of text.  This is the column of text that's copied into the clipboard using the "Multi-caret copy\paste experience" (referred to in the Visual Studio release notes - https://docs.microsoft.com/en-us/visualstudio/releases/2022/release-notes-v17.0)

I primarily use the feature to quickly create UPDATE and MERGE statements where the target and source have the same column names.  What I do is duplicate the column list on the right hand side and then add the "= src." text. 

You can replicate what I mean by opening each of the apps - SSMS and Visual Studio 2022 - and in a code editor place the mouse cursor over in the top-right area of blank space, hold down ALT and then click and drag straight down.  This is where you can paste the column of text copied using the ALT-SHIFT-click and drag feature **and keep it all aligned**.

VS looks like this:
![image](https://user-images.githubusercontent.com/100020564/165661289-8559b9f9-10a2-4b25-841f-0e812bcb3a0f.png)

But in ADS and VSC, the best tool available is CTRL-SHIFT-I, which creates carets at the end of every line but **does not do any padding**, so looks like this:
![image](https://user-images.githubusercontent.com/100020564/165661876-794ad6fc-5f0f-4fdb-a94a-b6d20326ba1b.png)

So at this point, even if I hit the tab key or space bar before pasting a muli-line, multi-caret text selection it won't be nicely aligned.
My preferred end result using **Visual Studio 2022 or SSMS** is this:
![image](https://user-images.githubusercontent.com/100020564/165663810-f57e169c-5964-4bd3-85d4-eda51bb4f211.png)

Can you copy this functionality over from Visual Studio 2022, please?

**Comment by dghViperdude0** [comment]
...Or alternatively, allow the CTRL-SHIFT-ALT key combination to perform automatic padding when combined with a mouse drag.  Even if toggled via a user setting.

**Comment by alanrenmsft** [comment]
@dghViperdude0 could you please open an issue in VSCode repository? Azure Data Studio is a fork of VSCode, we will automatically get the editor improvements vscode makes when we do the code merge.
