### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by linlae** [microsoft/azuredatastudio#19243]
Issue Type: <b>Bug</b>

Error

Azure Data Studio version: azuredatastudio 1.35.1 (fab63efd307e54c063c8af03474bbb5d77f5fd11, 2022-03-15T18:03:38.261Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
dacpac|Mic|1.10.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
machine-learning|Mic|0.11.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2021.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.16.1
azdata-sanddance|msr|3.3.0
sql-prompt|Red|0.2.6
sql-search|Red|0.4.0

(1 theme extensions excluded)

</details>

**Comment by lewis-sanchez** [comment]
Hi @linlae, to better help you, what are you attempting to do in Azure Data Studio when you encounter the error?

**Comment by Charles-Gagnon** [comment]
Closing this due to lack of info, if you can provide more information about the specific issue you're having please let us know!
