### ISSUE TITLE
SSL Provider error

### ISSUE THREAD

**Issue by Colio** [microsoft/azuredatastudio#19252]
Issue Type: <b>Bug</b>

Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: TCP Provider, error: 0 - Se agotó el tiempo de espera del semáforo.)
 ---> System.ComponentModel.Win32Exception (121): Se agotó el tiempo de espera del semáforo.
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at 
ClientConnectionId:bf6a78fb-27f5-4ba9-8249-bc031fedff73
Error Number:121,State:0,Class:20

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.41GB (4.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Colio** [comment]
![image](https://user-images.githubusercontent.com/4514357/166239448-7bb48fcd-1dea-405e-8530-d3be83abaecb.png)

**Comment by kburtram** [comment]
@Colio please search through the issue history for similar issues (such as https://github.com/microsoft/azuredatastudio/issues/13457).  This is typically caused by a change in the Sql Client driver to no longer trust self-signed server certificates by default.  This can be overridden by setting Trust Server Certificate to True in the Advanced Connection settings.  Please let us know if this does not address this issue.  Thanks!

**Comment by Solar-Matrix-Core** [comment]
> @Colio please search through the issue history for similar issues (such as #13457). This is typically caused by a change in the Sql Client driver to no longer trust self-signed server certificates by default. This can be overridden by setting Trust Server Certificate to True in the Advanced Connection settings. Please let us know if this does not address this issue. Thanks!

I got a same issue, and setting "trustServerCertificate" to true does not work for me. However, when I use sqlcmd or connection string on .Net Core project, I can connect to this server. Any other solutions?
