### ISSUE TITLE
Provide ability to add included columns to a nonclustered index

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#19259]
**Is your feature request related to a problem? Please describe.**
There is no ability to add included columns to a nonclustered index

**Describe the solution or feature you'd like**
Provide ability to add included columns to a nonclustered index

**Describe alternatives you've considered**
If this is not supported, we need to make sure it is documented.

**Additional context**
If we support this, we should also be able to note which columns are included (versus key columns) when viewing the index.

**Comment by erinstellato-ms** [comment]
Example T-SQL code:
CREATE NONCLUSTERED INDEX [NCI_Sales_OrderInfo] 
	ON [Sales].[Orders]
	([CustomerID], [OrderDate])   --index key columns
	INCLUDE([ExpectedDeliveryDate])   --included column(s)

**Comment by caohai** [comment]
Added via STS vbump in #20031
