### ISSUE TITLE
Disabled azurecore and can't get it back

### ISSUE THREAD

**Issue by bertsanders** [microsoft/azuredatastudio#19264]
Issue Type: <b>Bug</b>

Looks like I disabled azurecore and I cannot get it back.  Please assist.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:26:00.881Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
1. Go to the `Extensions` viewlet
2. In the search box type `@builtin` and press Enter
3. Find `Azure (Core)` and right click on it, then select `Enable`
