### ISSUE TITLE
incorrect font size in result grid

### ISSUE THREAD

**Issue by edwinxml** [microsoft/azuredatastudio#19268]
Issue Type: <b>Bug</b>

Execute any query with JSON output e.g.
"SELECT * FROM [MY_TABLE] FOR JSON AUTO"
The result grid will show output in JSON format, however the font size becomes smaller than default and even new query is run after, the size is still not reset back to default. 
Workaround is restart program to reset it.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.18362
Restricted Mode: No

<details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
pastetheplan|dre|0.2.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
cms|Mic|0.8.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
powershell|ms-|2021.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
server-report|Mic|0.2.3
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@edwinxml 
I ran the query on the right side first and then your query on the left, but I don't see a difference in font size.
![image](https://user-images.githubusercontent.com/13777222/166979972-695651af-1046-4063-a506-c4d055784341.png)

could you please share more detailed repro steps? and screenshots would help.

**Comment by edwinxml** [comment]
Run query in one tab
1. Run `SELECT TOP 100 * FROM sys.tables`, result in normal font
2. Then run `SELECT TOP 100 * FROM sys.tables FOR JSON AUTO`, result in smaller font (actually all font in the program are changed to smaller one), and wont change back until program restart. 
If the font not change after run the it, simply click on the field in result grid, which open a tab to show the json result (which is really great and helpful), and then font change to smaller one.

![19268](https://user-images.githubusercontent.com/104807379/167051639-86a27240-3087-4450-9ada-badaddb08fbb.png)

**Comment by cheenamalhotra** [comment]
Closing as inactive issue.
