### ISSUE TITLE
Add support for in-line analysis notebook functions

### ISSUE THREAD

**Issue by pnhughes** [Microsoft/azuredatastudio#1927]
- SQL Operations Studio Version: 0.30.6 (Windows 10)

Feature Request: Operations Studio has become my go-to daily platform for query and analysis work.  With the increasing availability of SQL notebook style apps (SQL Notebook, Jupyter, HUE) which allow for combined analysis notes and in-line queries and results, it's tempting to switch but I am reluctant to give up the simplicity and directness of the connection methods in Operations Studio.  I'd love to see support for inline notebooks in Ops Studio in some form.  

This may be possible via an extension which would parse query text and create a reader-friendly copy in a separate window, including code blocks of query text or results as desired.  Perhaps in future versions this type of function could be built in.

**Comment by kevcunnane** [comment]
@pnhughes is this a request for SQL Notebook support, or just Notebook integration? We've shipped basic Notebook support as part of the SQL Server 2019 (preview) extension, and have SQL support on our roadmap as a built-in feature with no need for Jupyter. We'd love to hear what your top requested features are, issues etc.

**Comment by chlafreniere** [comment]
SQL Notebook support has been added since this issue was created. Please try it out and give us feedback!
