### ISSUE TITLE
CTRL-F Options

### ISSUE THREAD

**Issue by sfscgjohnson** [microsoft/azuredatastudio#19270]
When pressing CTRL-F it only searches/replaces the active file and there is no way to search the files I have currently open.

**Describe the solution or feature you'd like**
When I do a CTRL-F is should be able to select between This Document, All Open Documents, or the Current Selection.

**Describe alternatives you've considered**
Using another tool

**Additional context**
I typically have many open windows and I need to find certain text in the open

**Comment by Charles-Gagnon** [comment]
You can use ctrl+shift+F to search across your workspace + open editors.
