### ISSUE TITLE
default project location in currently opened folder

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#19272]
**Is your feature request related to a problem? Please describe.**
Even if I have a folder open, especially in VS Code, and create a new SQL project - I have to reselect that folder as the project location.
![image](https://user-images.githubusercontent.com/12227241/166515137-d44c3ad8-ae61-4c4a-a144-8f08e6045194.png)

![image](https://user-images.githubusercontent.com/12227241/166515237-e7ebaf4f-96a2-4d19-9896-03f0c5674fbf.png)

**Describe the solution or feature you'd like**
It would be nice to be offered the current location as a default option to save time.

![image](https://user-images.githubusercontent.com/12227241/166515357-7ffbedd9-a5fb-4dde-aae4-338e5902b5ee.png)

**Additional context**
If multiple folders are open in a workspace in ADS, defaulting to at least 1 of them would be ok for this edge scenario.

**Comment by yndue736** [comment]
I am also facing the same problem as you ca see here on [Ac Dc TIG welder](https://protigwelder.com/best-ac-dc-tig-welder/) page and kindly help me about it.
