### ISSUE TITLE
Add ability to create filtered index (nonclustered)

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#19278]
**Is your feature request related to a problem? Please describe.**
There is no ability to create a filtered index in the Table Designer

**Describe the solution or feature you'd like**
Add the ability to create a filtered index.  Example T-SQL:

CREATE NONCLUSTERED INDEX [NCI_OrderLines_Info] 
	ON [Sales].[OrderLines]
	([OrderID], [StockItemID], [Quantity])
	WHERE [Quantity] > 10

**Describe alternatives you've considered**
If we will not support this, we need to note it in the documentation.

**Additional context**
N/A

**Comment by caohai** [comment]
Added via STS vbump in #20031
