### ISSUE TITLE
Primary key tablename not updating when changing default name

### ISSUE THREAD

**Issue by NvHulst** [microsoft/azuredatastudio#19281]
Issue Type: <b>Bug</b>

Whenever creating a new table, before giving it a name, create an primary key.
Now check the sql command and see that the primary key has the default table name included.
Now change the table name and check the command again. The primary key table name has not changed. When going to the primary key, uncheck some checkboxes and check again, the command has now updated the table name of the primary key.

What it should do.
- Update the table name of primary key in the sql command as soon you update the table name itself.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:26:00.881Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|32.00GB (0.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
tasks: 
1. if the name is not provided by the user, the auto generated names (PK, FK, Index...) should be updated  automatically.
2. follow SSDT's naming convention for PK, FK, index.

**Comment by alanrenmsft** [comment]
fix will be shipped in the upcoming release.
