### ISSUE TITLE
Double click on markdown preview to edit markdown shows error message

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#19288]
Related to https://github.com/microsoft/vscode/issues/132914

![Screen Shot 2022-05-04 at 1 14 02 PM](https://user-images.githubusercontent.com/34872381/166818299-ce50c7c7-8de9-47fa-a4dd-31c13d896d44.png)

**Comment by chlafreniere** [comment]
@barbaravaldez how long has this been an issue in ADS?

**Comment by barbaravaldez** [comment]
@chlafreniere- Unfortunately, I think it has been there for a few months. The vscode fix was done last year in September.
I'm able to edit the markdown file though, the actual issue is that we show an error message when we shouldn't.

**Comment by chlafreniere** [comment]
@barbaravaldez gotcha, thanks for clarifying.
