### ISSUE TITLE
renaming table in table designer does not work if cursor is still in name field

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#19285]
Version: 1.36.0
Commit: 0704471e6b4a79f0c2c2425b22dc6bee60a1c2a8
Date: 2022-04-19T18:21:59.017Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.4.0
Steps to Reproduce:

1. open designer for an existing table
2. change the table name and leave cursor in the field
3. save - generate script with changes

the preview window shows no changes, yet the script editor shows the change

![2022-05-04_10-36-03 (3)](https://user-images.githubusercontent.com/12227241/166747504-eb2e2568-f839-4471-a093-dd584bdff935.gif)

**Comment by alanrenmsft** [comment]
I've fixed the issue that when there are no changes user can still trigger the publish changes dialog by pressing CTRL+S.
In order to submit the changes, user has to move the focus out of the text box, this is currently by design. we can revisit it if we have a lot of users complaining about it.
