### ISSUE TITLE
Applying schema compare changes on Stored Procedure objects causes comment headers to duplicate

### ISSUE THREAD

**Issue by tecodan** [microsoft/azuredatastudio#19298]
Issue Type: <b>Bug</b>

When performing a Schema compare between a Database (Src) and a Database Project (Target) where there are changes in the Stored Procedure code, and that Stored Procedure has commentary before the definition, then that commentary is duplicated when the changes are applied to the Project.

Eg.
In Database:

```
/***************/
/* Comments */
/***************/
CREATE PROCEDURE [dbo].[sp_test] 
as
BEGIN
DECLARE @var1 varchar(20)='foo';
DECLARE @var2 varchar(20)='bar';
END;
```

In Database Project:

```
/***************/
/* Comments */
/***************/
CREATE PROCEDURE [dbo].[sp_test] 
as
BEGIN
DECLARE @var1 varchar(20)='foo';
END;
```

After applying changes, the following occurs in the Database Project:

```
/***************/
/* Comments */
/***************/
/***************/
/* Comments */
/***************/
CREATE PROCEDURE [dbo].[sp_test] 
as
BEGIN
DECLARE @var1 varchar(20)='foo';
DECLARE @var2 varchar(20)='bar';
END;

```
Extension: Schema Compare 1.13.1 with SQL Database Project 0.16.1
Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (2 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|8.00GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>
oard because it was too large to send. Please paste.

**Comment by kisantia** [comment]
Also happens for views. Doesn't happen for tables.

Probably related to the comments showing as part of the stored proc's script in schema compare, but not for tables

![Image](https://user-images.githubusercontent.com/31145923/186742982-39ee694d-0cb0-49b6-9509-c8e6bd35d5e3.png)

![Image](https://user-images.githubusercontent.com/31145923/186742949-1587200c-c237-42c9-beb2-c1562089c516.png)

**Comment by kisantia** [comment]
fixed in DacFx. Will be brought into ADS with the next DacFx update that should happen before the October release.
