### ISSUE TITLE
Expanding table folder fails for Azure SQL Server

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#19335]
- Azure Data Studio Version: 1.37.0-insider
- OS Version: Windows 11

Steps to Reproduce:

1. Connect to Azure SQL Server
2. Try to expand the "Tables" folder"
3. `An exception occurred while executing a Transact-SQL statement or batch.`

![Screen Shot 2022-05-11 at 9 44 39 AM](https://user-images.githubusercontent.com/18150417/167903765-db9755ed-1bae-49b9-b414-fb6b357d4791.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
@cssuh This doesn't really provide any actionable info, can you please work on getting some logs and/or debugging into it to try and figure out what's going wrong?

**Comment by kburtram** [comment]
It looks like the below query is causing this issue.  There error is below.  It looks like `ledgertbl` was `tbl` in the previous query.

@Charles-Gagnon I haven't confirmed yet (will do so now), but I suspect this query is coming from SMO.  I recall you mentioned SMO was recently bumped so that may be what's introduced this.

```
Msg 4104, Level 16, State 1, Line 5
The multi-part identifier "ledgertbl.is_system_versioned" could not be bound.
```

Current OE query.
```SQL
exec sp_executesql N'SELECT
SCHEMA_NAME(tbl.schema_id) AS [Schema],
tbl.name AS [Name],
tbl.object_id AS [ID],
CAST(CASE ledgertbl.is_system_versioned WHEN 1 THEN 1 ELSE 0 END AS bit) AS [IsSystemVersioned],
tbl.temporal_type AS [TemporalType],
CAST(tbl.is_external AS bit) AS [IsExternal]
FROM
sys.tables AS tbl
WHERE
((CAST(
 case 
    when tbl.is_ms_shipped = 1 then 1
    when (
        select 
            major_id 
        from 
            sys.extended_properties 
        where 
            major_id = tbl.object_id and 
            minor_id = 0 and 
            class = 1 and 
            name = N''microsoft_database_tools_support'') 
        is not null then 1
    else 0
end          
             AS bit)=@_msparam_0) and (tbl.temporal_type=@_msparam_1 or tbl.temporal_type=@_msparam_2))
ORDER BY
[Schema] ASC,[Name] ASC',N'@_msparam_0 nvarchar(4000),@_msparam_1 nvarchar(4000),@_msparam_2 nvarchar(4000)',@_msparam_0=N'0',@_msparam_1=N'0',@_msparam_2=N'2'
```

Here is the previous query from 1.36.1.

```SQL
exec sp_executesql N'SELECT
SCHEMA_NAME(tbl.schema_id) AS [Schema],
tbl.name AS [Name],
tbl.object_id AS [ID],
CAST(CASE tbl.temporal_type WHEN 2 THEN 1 ELSE 0 END AS bit) AS [IsSystemVersioned],
tbl.temporal_type AS [TemporalType],
CAST(tbl.is_external AS bit) AS [IsExternal]
FROM
sys.tables AS tbl
WHERE
((CAST(
        case
          when tbl.is_ms_shipped = 1 then 1
          else 0
        end
       AS bit)=@_msparam_0) and (tbl.temporal_type=@_msparam_1 or tbl.temporal_type=@_msparam_2))
ORDER BY
[Schema] ASC,[Name] ASC',N'@_msparam_0 nvarchar(4000),@_msparam_1 nvarchar(4000),@_msparam_2 nvarchar(4000)',@_msparam_0=N'0',@_msparam_1=N'0',@_msparam_2=N'2'
```

**Comment by Charles-Gagnon** [comment]
Thanks, I'll work with @shueybubbles on this.

**Comment by kburtram** [comment]
@Charles-Gagnon sounds good.  I've confirmed reverting SMO to previous version such as https://github.com/microsoft/sqltoolsservice/pull/1492 resolves this issue in my dev env.  Please let me know if there's any additional context needed for this issue.  If you don't want to revert SMO or prefer to revert the whole commit please close my PR.
