### ISSUE TITLE
Slow response to Select statement

### ISSUE THREAD

**Issue by dyhodge** [microsoft/azuredatastudio#19349]
Issue Type: <b>Bug</b>

ON a MAC, i randomly have the system delay for minutes before providing results from a select statement.
The following errors show in the Developer tools each time
--------
Failed to load resource: net::ERR_FILE_NOT_FOUND
workbench.desktop.main.js:sourcemap:135 [Extension Host] (node:56636) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.(Use `Azure Data Studio Helper (Renderer) --trace-deprecation ...` to show where the warning was created)

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:26:00.881Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (8.99GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
azuremonitor|Mic|0.1.4
cms|Mic|0.8.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
schema-compare|Mic|1.13.1
server-report|Mic|0.2.3
sql-dw|Mic|0.0.1
azdata-sanddance|msr|3.3.0

</details>

**Comment by cssuh** [comment]
Closing as no logs were provided.
