### ISSUE TITLE
ALTER not recognized as reserved keyword

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#1937]
- SQL Operations Studio Version: 0.31.3-insider

Steps to Reproduce:
1. Open New Query
2. Type Alter

Expected behavior is for Alter to be colored blue. For September, we should do a pass of all recognized T-SQL reserved keywords and ensure they are recognized in SQL Operations Studio. Is there a reference file I can review?

**Comment by aaomidi** [comment]
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/reserved-keywords-transact-sql?view=sql-server-2017

**Comment by aaomidi** [comment]
ALTER (something) is caught and given a blue highlight. ALTER on it's own isn't. This may be working as intended. I'll confirm the intended behavior.

**Comment by abist** [comment]
This is now fixed and verified.
