### ISSUE TITLE
Schema Compare publish to project doesn't add indexes correctly

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#19392]
When comparing two projects where one has a table with a non-clustered index and the other doesn't, the non-clustered index does not get added to the project when the changes are applied.

Steps to repro:
1. Create project1 with the script:
```
CREATE TABLE [dbo].[Table1] (
    [Id]       INT NOT NULL PRIMARY KEY NONCLUSTERED ([Id] ASC),
    [column_1] INT CONSTRAINT [df_col2] DEFAULT ((1)) NULL,
    [column_2] INT NULL,
    [column_3] INT NULL,
    CONSTRAINT [CK_1] CHECK ([column_3]>(0))
);

GO
CREATE NONCLUSTERED INDEX [Index_1]
    ON [dbo].[Table1]([column_2] ASC);
```
2. Create project2 with the script:
```
CREATE TABLE [dbo].[Table1]
(
  [Id] INT NOT NULL PRIMARY KEY
)

```
3. Schema compare the two projects

![image](https://user-images.githubusercontent.com/31145923/168692062-e8139d61-2034-44a5-af23-66f603172fbc.png)

4. Apply the changes.

Expected:  scripts should be the same
Actual: project2 does not have Index_1
![image](https://user-images.githubusercontent.com/31145923/168692074-1baea9c9-8890-4575-a733-9e50bc7ebaed.png)

**Comment by kisantia** [comment]
dropping an index also doesn't work

**Comment by aleguerrero** [comment]
Same thing happens with Primary keys, Foreign keys, and constraints.
I do the same exact steps as the issue and the constraints don't go through.

**Comment by kisantia** [comment]
fixed in DacFx and will be in the June release
