### ISSUE TITLE
Profiler Text / Details view shows up inconsistently

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#1939]
Issue Type: <b>Bug</b>

1. Open Profiler (Alt+P)
2. Start Profiler (Alt+S)
3. If event doesn't automatically start, run a T-SQL query like Select 1
4. Select an event in profiler, then try to click the arrow on bottom right of screen.

![image](https://user-images.githubusercontent.com/30873802/42776992-9eff0d26-88ed-11e8-9e54-20454d75838c.png)

This doesn't happen all the time, but the arrow to pop up Text / Details will sometimes not pop up, and there appears to be no option to drag the view up (occasionally it does).

SQL Operations Studio version: sqlops 0.31.3-insider (4d67eca8bb40d840fff464e399640998a8ecd400, 2018-07-15T18:12:31.866Z)
OS version: Windows_NT x64 10.0.17134

**Comment by madelinemacd** [comment]
This error seems to have come back, and should be investigated.

**Comment by kburtram** [comment]
I haven't seen this recently so I'll close.  We can investigate if it comes back again.
