### ISSUE TITLE
Issue with the apk

### ISSUE THREAD

**Issue by qmqmpzpz** [microsoft/azuredatastudio#19435]
https://github.com/microsoft/azuredatastudio/blob/dbaa78a737c9a3214a50465a0587f97e11b15490/.github/CODEOWNERS#L7

{mqk tile. psf. }
 for then if .psv { printf / vcode.nsl }
    sql for while .sql ends / #18800 #19434 
     sql do while ends #19434 "azurecore" / "tslint" / "azuscl" / "gitcommand" / "dispose" / () => 9
       yarn.lock "dispose" printf file based sql nsl. to psv. = = yarn book . schema base token == 5

**Comment by alanrenmsft** [comment]
@qmqmpzpz it is not very clear to me what issue you are having. could you please provide more information?
