### ISSUE TITLE
Third-party dependencies cannot be installed.

### ISSUE THREAD

**Issue by winking-d** [microsoft/azuredatastudio#19431]
Issue Type: <b>Bug</b>

1. download the pagk
2. install
3. choose "Yes"
4. No response

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (5.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@winking-d I am assuming you are referring to installation of third party extensions. which extension are you trying to install?

**Comment by aasimkhan30** [comment]
@winking-d, can you please update to the latest version of ads and try again? I think you're experiencing this issue:
https://github.com/microsoft/azuredatastudio/issues/19369. 
For some reason, ads is not surfacing vsix installations errors. I am working on it for the June release.

**Comment by alanrenmsft** [comment]
please reopen the issue when you have the information we requested.
