### ISSUE TITLE
SQL Bindings - Choosing to manually enter table name has incorrect info

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19436]
1. Run Create Azure function w/ SQL Binding command
2. Go through prompts until asked to enter table name
3. Choose "Enter SQL table or view to query"

A couple of issues : 

1. The title is incorrect (says `Function Name` when it should be `Table or View`)
2. The default text isn't correct

![image](https://user-images.githubusercontent.com/28519865/169362244-18e6e911-cefc-446b-8b3d-5fe42192971a.png)

**Comment by VasuBhog** [comment]
@Charles-Gagnon  Function Name should not have any special characters including `.`. As this is used for the class name for the `.cs` file and therefore would show an error
