### ISSUE TITLE
Publishing project to multiple containers only adds the one connection to connections pane

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#19447]
1. Publish the same project twice using the "Publish to new Azure SQL Database emulator" option
2.  choose not to delete existing containers when publishing the second time

expected: the connections to the two containers should show in the connections viewlet with the port specified
actual: only one connection is in the connections viewlet
![image](https://user-images.githubusercontent.com/31145923/169417789-759c29cc-05a6-420f-85c8-92fb1cf6ea3b.png)

**Comment by Benjin** [comment]
By design, but waiting to see if there's any feedback on this choice

**Comment by kisantia** [comment]
Closing as by design. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.
