### ISSUE TITLE
Opening SQL DB Project Extension shows duplicate set of buttons and text

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#19441]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Installed the RC Build for mssql and sqldbProj extension vsix files 
2. Click on the SQL DB Project extension, and observe the UI.
3. UI looks like this:
![image](https://user-images.githubusercontent.com/74571829/169411235-4037bc97-a42b-47d8-a581-1a646e7d6dcd.png)
4. Create a SQL DB Proj and navigate to projects tab.
5. right click on newly created project and observe the options.
![image](https://user-images.githubusercontent.com/74571829/169412445-04b51a58-588b-4462-8c45-f2be4a8bf165.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
@ssreerama This is pretty odd, are you sure you installed the VS Code version of the extension?

**Comment by ssreerama** [comment]
Yes, I installed the version "sql-database-projects-vscode-0.16.2.vsix"

**Comment by ssreerama** [comment]
Turns out I have duplicated "Data Workspace" extensions installed on my machine 😁. Deleting it resolved the issue. 

Closing this Issue, since it is developer env issue...
