### ISSUE TITLE
SQL Binding - Non-SQL auth connection strings have password placeholder inserted

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19452]
1. Run `Create Azure Function with SQL Binding`
2. Select Create New Project
3. Go through prompts, making sure to select a connection with integrated auth
4. Finish making the function

The local.settings.json file has the connection string with `Integrated Security` set to true as expected, but it also includes the password placeholder text (`Password=******`)

![image](https://user-images.githubusercontent.com/28519865/169423098-7951b2aa-e9af-4470-8307-2fcd7b157f8b.png)

**Comment by VasuBhog** [comment]
Seems to be something specifically handled by getConnectionString API call that is returned - so would have to look at vscode-mssql.

**Comment by Charles-Gagnon** [comment]
A short-term quick fix could also be to manually check and replace that value for non-sql auth.
