### ISSUE TITLE
Needs a M1 arch support badly

### ISSUE THREAD

**Issue by piyush97** [microsoft/azuredatastudio#19457]
The Data studio takes a lot of CPU usage on my M1 max machine. It needs a native arch support. The current, rosetta version is really drains my mac's battery in minutes.

I think a lot of people are facing the same issue, I'd prefer using DataGrip instead because of native M1 arch support instead of x86 version.

**Comment by abist** [comment]
This issue is being tracked here - https://github.com/microsoft/azuredatastudio/issues/16125
Closing as duplicate
