### ISSUE TITLE
Exporting Query Result to Excel Should Not Require Scrolling to the Bottom

### ISSUE THREAD

**Issue by goudstad** [microsoft/azuredatastudio#19453]
Issue Type: <b>Bug</b>

I created a query from MS SQL Server which I'd like to export the result to an Excel spreadsheet.  I waited for the query to finish execution and then I clicked on the "Save As Excel" button on the right.  To my surprise, only 1625 out of 46393 records were exported.  I tried again, but this time I scrolled to the bottom of query result before I clicked on the the "Save As Excel" button on the right.  All results were exported.  

Suggestion to developer: Users should not need to scroll to the export bottom to export the full result.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

**Comment by alanrenmsft** [comment]
@goudstad  I was not able to reproduce the issue

![export](https://user-images.githubusercontent.com/13777222/169587502-b4f48054-cb53-4da9-a2c6-a65ab9b21ab1.gif)
