### ISSUE TITLE
Find replace has no scope

### ISSUE THREAD

**Issue by gbarnis** [microsoft/azuredatastudio#19461]
Issue Type: <b>Feature Request</b>

In SSMS you can select to find / replace in "Selection"/"File"/"Open files" etc

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

**Comment by kburtram** [comment]
The Find experience in Azure Data Studio is taken without modification from upstream VS Code.  We don't have current plans to customize unless there is a specific need for data-oriented use-cases.  Please consider logging this suggestion upstream in the vscode repo and we will pickup when we refresh from upstream.  Thanks!
