### ISSUE TITLE
SQL Binding - Display detailed error information when dotnet add command fails

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19470]
Currently if an error occurs running the `dotnet add` command after creating a function then an error similar to this is displayed

![image](https://user-images.githubusercontent.com/28519865/169592751-3284af71-d1ec-408d-80f2-4b5d728831fc.png)

This doesn't tell the user what the actual issue is though. We should be doing a couple of things here : 

1. Make sure we're logging the full stdout from the command to an output window
2. Direct the user to the output window for further information (provide button that brings up the output channel)

**Comment by VasuBhog** [comment]
related to #18767

**Comment by chlafreniere** [comment]
By the way, I got a message similar to this when adding an input binding, and then tried adding an output binding into the same function project.

**Comment by VasuBhog** [comment]
Will prioritize this in order to ensure we can help users identify the problem. This was found to be a dev machine issue where if a user does the same command in terminal it should state what the issue is.
