### ISSUE TITLE
Allow more Maximum Characters Retrieved in query results grid

### ISSUE THREAD

**Issue by dfalso** [microsoft/azuredatastudio#19480]
**Is your feature request related to a problem? Please describe.**
When copying cell data from the Results grid, large text strings are truncated to 65,535 characters. This most often shows up in JSON-esque data, but we see it in other large text blobs as well (description fields, for instance). 

**Describe the solution or feature you'd like**
SSMS has a Maximum Characters Retrieved Non-XML Data setting (Tools->Options->Query Results->SQL Server->Results to Grid), which does default to 65535 but allows for larger values (at least as large as 2000000). Please duplicate this config setting. 

**Describe alternatives you've considered**
No good alternatives, other than working with SSMS in parallel for longer text blobs. 

**Additional context**
```
select
	string_agg(
		[stub]
		, ''
	) + 'b'
from (
	select top 8192 *
	from sys.all_columns
) as A
cross join (
	//note that REPLICATE caps at 8000 chars for varchar(max), so using string_agg instead
	select cast(replicate('a', 8) as varchar(max)) as [stub]
) as B
```

**Comment by alanrenmsft** [comment]
@dfalso this has been fixed now, please refer to this comment: https://github.com/microsoft/azuredatastudio/issues/392#issuecomment-1239773578

**Comment by alanrenmsft** [comment]
@dfalso BTW, this is only available in the Insiders build, the next stable release will have the fix.
