### ISSUE TITLE
Extensibility: Context menu has databaseName in profile, but it's not in the profile.options

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#1950]
- SQL Operations Studio Version:

Steps to Reproduce:
- Create an extension with context menu contributions
- Right-click and run some action

Expected:
- both profile.databaseName and profile.options.database match
Actual:
- profile.options.database is empty

The main issue is when merging the same code in a context menu command and a dashboard task. You use options since it's meant to be the "universal truth" but it doesn't have the value.

Root cause:
- I missed that you need to use a ConnectionProfile and update the database value there, rather than cloning as an .toIConnectionProfile and editing that instead. The ConnectionProfile class does write-through to the options but .toIConnectionProfile does not since it's a flat object type.

**Comment by kburtram** [comment]
Closing out older issues.
