### ISSUE TITLE
Need to hit "Refresh" to see new tables created or confirm tables deleted

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#19511]
- Azure Data Studio Version: 1.36.2
- OS Version: Windows 11

Steps to Reproduce:

1. Open Azure Data Studio
2. Create a new table inside an object in the connections pane
3. Publish 

Expected:
New Table should automatically appear inside Tables folder

Actual:
Need to hit Refresh in order to see table populate inside Tables folder. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Seems to be duplicate of https://github.com/microsoft/azuredatastudio/issues/1720

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/1720.  This seems like a reasonable change that we should make for "quality of life" usability improvements.
