### ISSUE TITLE
 VSCode - SQL DB Project: Add table on newly opened project not working for the first time.

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#19510]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a new instance of VSCode
2. Open SQL DB Project extension and create a project
3. Right click on project and click' Add Table'
4. Error banner is coming(see below ss), but if try for second time, it works.
![image](https://user-images.githubusercontent.com/74571829/170138014-5498de84-5c3e-45ce-8770-602c8f20c559.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
I'm unable to repro this. Can you give the extension versions and more details? Maybe the extensions weren't finished being activated the first time you clicked "Add table"?

**Comment by ssreerama** [comment]
I was able to reproduce it repeatedly during that day and now with main branch I couldn't reproduce it. Thanks for verifying it.
