### ISSUE TITLE
Feature Request: Add Support for Dataverse Connections

### ISSUE THREAD

**Issue by ackerman-chris** [microsoft/azuredatastudio#19522]
**Is your feature request related to a problem? Please describe.**
Please add support to be able to connect to Dynamics (Dataverse) connections via Azure Data Studio. Currently this is only supported using SSMS.

**Describe the solution or feature you'd like**
Add a new connection option that will support Dataverse connections to your org's Dynamics 365 Database.

**Describe alternatives you've considered**
Using SQL Server Management Studio

**Additional context**
N/A

**Comment by cheenamalhotra** [comment]
Closing as duplicate.
