### ISSUE TITLE
WYSIWYG: Image disappears after going out of editing mode

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#19546]
- Azure Data Studio Version: 1.36.2
- OS Version: Windows

Steps to Reproduce:

1. Paste an image
2. Go out of editing mode by clicking anywhere outside the cell

repro content being sent to the team

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chlafreniere** [comment]
@barbaravaldez is this related to the other issue that you're looking into?

**Comment by barbaravaldez** [comment]
@chlafreniere It's not related, but also I'm not able to get a consistent repro

**Comment by chlafreniere** [comment]
oooh ok. @MaddyDev can you take a look in that case?
