### ISSUE TITLE
computed column issues

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#19549]
1. when there is only 1 column and the column is a computed column, save it will fail
  ![image](https://user-images.githubusercontent.com/13777222/170593777-7b5acc7b-ab4b-4173-83e9-80150edcf4fd.png)
2. computed column cannot be deleted
  ![image](https://user-images.githubusercontent.com/13777222/170593818-d281c5ea-242f-46cd-8092-faa33862abbc.png)

**Comment by caohai** [comment]
1. I can add a validation rule for the case where all columns are computed columns. (I tested with SSDT and saw the same incorrect syntax error from engine).
2. I'll fix this.

**Comment by caohai** [comment]
Fixed by STS vbump in https://github.com/microsoft/azuredatastudio/pull/19237
