### ISSUE TITLE
"Database Administration Tool Extensions for Windows" extension does not work!

### ISSUE THREAD

**Issue by AminAvan** [microsoft/azuredatastudio#19559]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

Hello friends,

I have installed the "Database Administration Tool Extensions for Windows" extension on my Azure Data Studio, while, when I right-click on a SQL database to "Generate Script...", this option is not there!!

Would you please advise me?

Thanks,
Amin

**Comment by Charles-Gagnon** [comment]
@AminAvan What OS are you on?

**Comment by kburtram** [comment]
The option appears there and is working correctly with latest ADS/SSMS on Windows 11 in my testing today.  I'll close based on lack from repro and unanswered question above.  Please let us know if you are still impacted by this issue.  Thanks!

![image](https://user-images.githubusercontent.com/599935/184686539-bdf44b92-c2b4-4b0b-8fd8-6deef3a8f996.png)
