### ISSUE TITLE
Can't save Notebook: first argument must of type String...

### ISSUE THREAD

**Issue by ishazel** [microsoft/azuredatastudio#19554]
Issue Type: <b>Bug</b>

I have not been able to intentionally reproduce this issue, it seems to happen randomly.

I have an ipynb file with many SQL blocks. All blocks run as expected. Sometimes I can successfully save for a while, but seemingly at random, the file will decide it can't save any more, and ADS returns this error:

> Failed to save 'filename.ipynb': The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received an instance of Object

I can copy every block into a new blank ipynb file and it will save successfully, at least for a little while.

Edit: it only seemed to happen when cells have been run, otherwise you can save. I just tried the Insiders version and have not had the issue yet. Sorry I didn't try before posting.

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|7.68GB (1.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
jupyter|ms-|2021.8.1046824664
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment]
We've had another report of this internally. @lucyzhang929 can you take a look?

**Comment by lucyzhang929** [comment]
Hi @ishazel, would you be able to share the notebook where you hit this issue?

**Comment by ishazel** [comment]
@lucyzhang929 I'm not comfortable sharing the original file. But I can reproduce the issue reliably on my machine.

- Open ADS (non-Insiders).
- Connect to a database. 
- From the connection overview (I guess?) click New Notebook.
- Create a section, type your query, and save now before running (or you won't be able to)
- Run the query (for instance, `SELECT TOP 100 * FROM Clients`).
- You won't be able to save now.

File from above method is attached.
[broken-notebook.ipynb.zip](https://github.com/microsoft/azuredatastudio/files/8846336/broken-notebook.zip)

**Comment by lucyzhang929** [comment]
I followed the steps above (changing the query to `SELECT * FROM sys.tables`) and was unfortunately not able to repro the issue. 
To confirm, you are able to run a cell and save the same notebook above in ADS insiders?

**Comment by ishazel** [comment]
@lucyzhang929 

Yes it works fine in Insiders, I can save after executing.

I have more details. The problem is with the cell output. If the query was valid and a result table is displayed, I get the error. If I clear the cell output or delete the cell altogether, I can save the workbook again. If I change my query to select into a temp table, it runs fine and I can save.

Possibly related. I was surprised and slightly panicked to see that when a notebook was pushed to GitHub, the results of any cells that had been executed are also pushed to GitHub. I'm careful now to always clear all cells frequently.

**Comment by chlafreniere** [comment]
@ishazel do you have the Jupyter extension installed on Insiders?

You shouldn't need the Jupyter extension installed unless you are leveraging the .NET Interactive extension. Otherwise, ADS has Jupyter notebook support built-in.

**Comment by ishazel** [comment]
Yes, uninstalling it fixed the issue 👍🏻
