### ISSUE TITLE
Convert Notebooks From Synapse Workspace

### ISSUE THREAD

**Issue by AustinMReppert** [microsoft/azuredatastudio#19553]
Currently when an Azure Synapse workspace is cloned Notebook files are stored in a JSON format. From within Azure Synapse Notebooks can be exported to work with Azure Data Studio. It would be nice to have a feature to convert between the JSON format and other Notebook formats.

**Comment by chlafreniere** [comment]
@yualan @dzsquared FYI

**Comment by syedimranFB** [comment]
has anyone found any solution for this?

**Comment by AustinMReppert** [comment]
https://marketplace.visualstudio.com/items?itemName=SynapseVSCode.synapse
