### ISSUE TITLE
Azure Cosmos DB API for MongoDB extension

### ISSUE THREAD

**Issue by yuri-mish** [microsoft/azuredatastudio#19561]
Issue Type: <b>Bug</b>

Can't find and install Azure Cosmos DB API for MongoDB extension

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

Extensions: none

**Comment by dzsquared** [comment]
Hi @yuri-mish - the Cosmos DB/MongoDB extension is currently available in Azure Data Studio insiders only.  It looks like you have 1.36.2 stable installed, try out insiders here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
