### ISSUE TITLE
Loading Contantly DB

### ISSUE THREAD

**Issue by pabloBrizzi** [microsoft/azuredatastudio#19567]
Issue Type: <b>Bug</b>

The Data Bases stay constantly "loading".

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.37GB (6.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
what type of databases are showing as loading? sql server or other database types?

**Comment by pabloBrizzi** [comment]
Sql server

**Comment by kburtram** [comment]
@pabloBrizzi are you still impacted by this issue?  if so, could you please add the log information requested above so we can investigate.  Thanks!

**Comment by cheenamalhotra** [comment]
_Gentle ping @pabloBrizzi !_

**Comment by cssuh** [comment]
Closing as no logs provided.
