### ISSUE TITLE
Notebook cell results are mixed up with other cells results

### ISSUE THREAD

**Issue by sumngh** [microsoft/azuredatastudio#19585]
Issue Type: <b>Bug</b>

In case of notebook, if we have executed cell 1 query to get the results and lets says its taking more time due to performance issue in connecting to DB and lets say we started cell 2 execution then the result of the cell 1 results is displayed in cell 2 results window and no results for cell 2 query.

This is really a serious issue. Cell execution should be sequential, ones the first queued query is completed then only the second should run and the results should be displayed in their own windows.

Of if Microsoft is planning to have them run parallely that will be great but the results should be in correct cell windows

Azure Data Studio version: azuredatastudio 1.35.0 (e9c8eb8564f537726b36b5f15c7f35e62f229284, 2022-02-23T17:36:02.883Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
machine-learning|Mic|0.11.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
azdata-sanddance|msr|3.3.0

</details>

**Comment by sumngh** [comment]
I have tried with updated version of Azure data studio also, issue is still there.

**Comment by sumngh** [comment]
New Version:
Azure Data Studio version: azuredatastudio 1.36.2 (https://github.com/microsoft/azuredatastudio/commit/2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)

**Comment by corivera** [comment]
@sumngh What kernel were you seeing this issue with?

**Comment by sumngh** [comment]
Hi Cory,

While creating tickets I think all information are included by default by the application.
I have not selected any specific kernel for this. Everything was set default when we use notebook with SQL query in studio.

Thanks & Regards
•••••••••••••••••••••••••••••••••••••••••••••••
Sumer Singh
+91-8287014644

| Deal with the world the way it is, not the way you wish it was. |

••• From Mobile (Outlook)

**Comment by sumngh** [comment]
Hi Cory,

I think I didn’t mentioned that cells were running parallel.
Please can you recheck the ticket details. 

Thanks & Regards
•••••••••••••••••••••••••••••••••••••••••••••••
Sumer Singh
+91-8287014644

| Deal with the world the way it is, not the way you wish it was. |

••• From Mobile (Outlook)

**Comment by corivera** [comment]
You mentioned cells weren't being executed sequentially, which is why I was wondering if cells were somehow running in parallel. Did the long-running cell 1 complete and produce output before you started running cell 2?

**Comment by sumngh** [comment]
No cell 1 no execution not completed.
And I started cell 2 , so cell 1 results displayed in cell2.
This is incorrect.

Thanks & Regards
•••••••••••••••••••••••••••••••••••••••••••••••
Sumer Singh
+91-8287014644

| Deal with the world the way it is, not the way you wish it was. |

••• From Mobile (Outlook)

**Comment by sumngh** [comment]
Thanks Cory for your quick response.

Thanks & Regards
•••••••••••••••••••••••••••••••••••••••••••••••
Sumer Singh
+91-8287014644

| Deal with the world the way it is, not the way you wish it was. |

••• From Mobile (Outlook)
