### ISSUE TITLE
table designer + sql db proj: add an index to the table will generate script with build error

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#19609]
a `GO` statement is missing between the statements

`
CREATE TABLE [dbo].[Table1] (
    [Id]       INT NOT NULL PRIMARY KEY CLUSTERED ([Id] ASC),
    [column_1] INT NOT NULL,
    [column_2] INT NULL
);

// GO is required here in order to build.

CREATE NONCLUSTERED INDEX [Index_1]
    ON [dbo].[Table1]([column_2] ASC);

GO
`

**Comment by kisantia** [comment]
fix is checked into DacFx
