### ISSUE TITLE
[CSS Supportability] Please add "debug" switch with "exceptions console"

### ISSUE THREAD

**Issue by cbenkler** [microsoft/azuredatastudio#1961]
Please add a configuration switch which would enable an "exceptions console" that shows information that right now can be obtained only by attaching a debugger.  E.g. - the debug console from VS Code debugging experience.

**Comment by ranasaria** [comment]
@cbenkler 
Checkout the latest preview build of azure data studio. This includes the following new settings:
    _"mssql.tracingLevel": "All",
    "mssql.logFilesRemovalLimit": 100,
    "mssql.logRetentionMinutes": 60,_

When mssql.tracingLevel is set the corresponding tracing information is not only sent to a file but is also logged in the Azure Data Studio UI's Output Channel called: Log (SqlTools). Ctrl-Shift-U is the shortcut to bring up the output pane.

Kindly try out the feature and share your feedback.

**Comment by kburtram** [comment]
Exceptions are being surfaced in the Help->Developer Tools Console.  Please let us know if there is some additional exception details you need that aren't being surfaced.  Thanks!
