### ISSUE TITLE
Results Window Goes "Blank"

### ISSUE THREAD

**Issue by Troesler-illuminate** [microsoft/azuredatastudio#19612]
Issue Type: <b>Performance Issue</b>

Often the results window of a query will go "blank" meaning that individual cell valures are not shown, but the grid lines will still be drawn. To fix this I usually have to drag around the vertical and/or horizontal scroll bars to get the table to be drawn correctly for a section of data. I am not sure if this is a function of row count or column count, but it happens on most tables/result sets and is preventing me from reasonably switching from SSMS to Azure Data Studio as my "daily driver".

For reference, this specific result set had 74k rows and 150 columns, but it has happened on lesser result sets as well.

I tried disabling all extensions and this still occurred. I also limited to 10k rows and the problem still occurred. Here is a screenshot of the behavior:

![image](https://user-images.githubusercontent.com/88000271/171876109-0e167fc5-33e2-484a-8f49-cbc5dee46600.png)

**Steps to reproduce**

1. Query a table in your database with a decent amount of rows and columns
2. Scroll through the results window in either (or both) the horizontal and vertical directions
3. Eventually you will notice the cells becoming blank and not displaying data

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.69GB (22.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    91	 64532	azuredatastudio main
    0	    86	 10224	   shared-process
    0	    71	 26568	     ptyHost
    0	   140	 20576	   gpu-process
    0	    82	 65060	   window (Issue Reporter)
    0	   193	 65300	   window (● SQLQuery_1 - 1323-TROESLER-L.sis_api (Integrated) - Azure Data Studio)
    0	   161	 46640	     extensionHost
    0	    71	 19596	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=46640
    0	    47	 27056	       dotnet tool run dotnet-interactive -- notebook-parser
    0	    25	 31312	         "C:\Program Files\dotnet\dotnet.exe" C:\Users\Tyler\.nuget\packages\microsoft.dotnet-interactive\1.0.317502\tools/net6.0/any/Microsoft.DotNet.Interactive.App.dll notebook-parser
    0	    11	 35648	         console-window-host (Windows internal process)
    0	    35	 52148	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.238\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\Tyler\AppData\Roaming\azuredatastudio\logs\20220603T102636\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical
    0	    11	 41172	         console-window-host (Windows internal process)
    0	    37	 56740	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.238\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\Tyler\AppData\Roaming\azuredatastudio\logs\20220603T102636\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical
    0	    11	 22308	         console-window-host (Windows internal process)
    0	   165	 71092	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\3.0.0-release.238\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\Tyler\AppData\Roaming\azuredatastudio\logs\20220603T102636\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical
    0	    11	 18000	         console-window-host (Windows internal process)
    0	    38	 81364	   utility
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.3
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.13.1
sql-assessment|Mic|0.6.1
sql-database-projects|Mic|0.16.1
dotnet-interactive-vscode|ms-|1.0.3175020
jupyter|ms-|2021.8.1046824664
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by alanrenmsft** [comment]
@Troesler-illuminate I did experience the slowness comparing to small dataset, but eventually, it will be rendered after a second or so. for you how long does it stay like that for?
![slow-results](https://user-images.githubusercontent.com/13777222/183180748-ca43fd2c-88f9-49ca-a65c-8d79dfd70de6.gif)

**Comment by Troesler-illuminate** [comment]
@alanrenmsft I just tested with the latest build and it offers similar behavior to what you included in your screen recording. Before it would just stay like that until I moved the scroll bar one way or the other. The performance in the latest build is much better/acceptable!

**Comment by alanrenmsft** [comment]
great to know, thanks!

**Comment by PaddySe** [comment]
This problem is still there, even when only a couple of rows are returned from the query. It usually helps to switch to the Messages tab and back, but it is highly annoying having to switch back and forth between mouse and keyboard just to be able to see the results.
