### ISSUE TITLE
SQL Migration - Error running assessment multiple times

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19617]
1. Click "Migrate to Azure SQL" button on server dashboard
2. Select some databases
3. Click Next
4. Assessment should succeed
5. Click "Cancel" 
6. Click "Migration to Azure SQL" button on server dashboard
7. Click Next

This error appears 

![image](https://user-images.githubusercontent.com/28519865/171952611-cb3101f7-73af-4b8e-837d-c98c9c64b058.png)

**Comment by raymondtruong** [comment]
This issue has been identified and has been fixed in the latest release.
