### ISSUE TITLE
ONNX runtime is not supported in current server

### ISSUE THREAD

**Issue by superichmann** [microsoft/azuredatastudio#19628]
Issue Type: <b>Bug</b>

I get this error message when click "Make predictions"
python 370
pip installed onnxruntime succesfully

Extension version: 0.11.0
Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820X CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (36.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|18%|
</details>

**Comment by Charles-Gagnon** [comment]
Reopening, the linked issue appears to be where we added the error message. But I'm guessing that @superichmann is saying they aren't expecting this to fail - is that correct?

@llali to help figure out what the issue is here and improve documentation/error message as needed

**Comment by Charles-Gagnon** [comment]
@llali I'd suggest making that error message clearer - indicating specifically what is/isn't supported and ideally linking to docs as well?

**Comment by superichmann** [comment]
Hi guys, thanks for the replies!

I have installed SQL Server 2019 developer on windows 10 and azure data studio with ML extension on the same machine.

These features should work? maybe I am missing something :(
