### ISSUE TITLE
Include Checkboxes Randomly and Dynamically Moving/Unchecking

### ISSUE THREAD

**Issue by boothkd** [microsoft/azuredatastudio#19635]
Issue Type: <b>Bug</b>

1 Run Schema Compare
2 Click Compare; resulting comparison is multiple pages
3 Begin clicking "Include" checkboxes to clear/exclude or set/include
4 After several rows have been selected the display jumps to the top of the first page
5 Scroll down to row that was last checked or unchecked to find that the box has reverted back to its original state

Extension version: 1.13.1
Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:18:20.649Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by kisantia** [comment]
dup of #5939
