### ISSUE TITLE
June 2022 Release Endgame

### ISSUE THREAD

**Issue by erpett** [microsoft/azuredatastudio#19632]
# June 2022 Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.37

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

[win-user]: https://go.microsoft.com/fwlink/?linkid=2132305
[win-system]: https://go.microsoft.com/fwlink/?linkid=2131971
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2131970
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2131972
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2132306
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2131974
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2131973
Install the latest build of ADS from the link above.

## Scenario Sign Off

[ADS Scenario Signoff Test Plan](https://dev.azure.com/mssqltools/CrossPlatBuildScripts/_testPlans/define?planId=11686&suiteId=11913)

## Partner Sign-offs

[Partner Signoff Test Plan](https://dev.azure.com/mssqltools/CrossPlatBuildScripts/_testPlans/define?planId=11950&opId=61&suiteId=11975)

@QingqingYuan2 (PGSQL)
@BranislavGrbicMDCS (SQL On Demand) 
@alexprotsenko (SQL Assessment)

**Comment by alanrenmsft** [comment]
@aasimkhan30 did you unpin this issue by mistake?
