### ISSUE TITLE
SQL DB Proj - updateSystemDatabaseReferencesInProjFile doesn't handle all cases

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#19641]
It currently assumes that there is only a single ItemGroup with ArtifactReference items in it and that the ItemGroup doesn't have any other items in it. There are two issues with that : 

1. If there are multiple ItemGroups with ArtifactReference items then we won't clean up until all items are removed
2. If the ItemGroup has other non-ArtifactReference items in it then those will be deleted

**Comment by kisantia** [comment]
Should be fixed by the work to move the sql project xml parsing to DacFx, which will leverage Microsoft.Build libraries to do the reading and writing to the .sqlproj
