### ISSUE TITLE
Horizontal scrollbar in query editor very difficult to click

### ISSUE THREAD

**Issue by jvincent-siplay** [Microsoft/azuredatastudio#1964]
Issue Type: <b>Bug</b>

* Open a new query window
* Create a simple query  (e.g. `select 1`) and execute it to display the results pane
* Edit the query to be longer than the width of the window so a horizontal scrollbar appears
* Try to click and drag the scrollbar

The scrollbar overlaps the pane splitter, making the clickable area much smaller than the visible height of the scrollbar (which is very small to begin with).  At 100% DPI on Windows 10, only the top 3 or 4 pixels of the scrollbar are clickable.  Anything below that causes the vertical resize cursor to appear.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.79GB (12.91GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by VeritableHero** [comment]
The status bar at the bottom of the application also appears to overlap the horizontal scroll bar. This makes it more difficult than it should be to click on while using a 2560x1440 monitor. (Not sure about other resolutions)

**Comment by anthonydresser** [comment]
This should be fixed, reopen if you continue to experience this.
