### ISSUE TITLE
table designer in SQL proj fails on Azure SQL DB proj

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#19656]
Version: 1.37.0-insider
Commit: 8cb6d48da2eb5e1d9f5a5719f6523ba1af0a2908
Date: 2022-06-07T05:44:02.958Z
VS Code: 1.59.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.5.0

sqlproj v 0.17.0

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>SampleProject</Name>
    <ProjectGuid>{16346529-9E6D-4EF8-9F64-6E1C9E6BE7DA}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <ItemGroup>
    <PreDeploy Include="Script.PreDeployment1.sql" />
  </ItemGroup>
  <ItemGroup>
    <PostDeploy Include="Script.PostDeployment1.sql" />
  </ItemGroup>
</Project>
```

unable to open an existing table script in designer.  switching project target platform for sql server resolves the issue

![image](https://user-images.githubusercontent.com/12227241/172422458-455b9932-8712-4081-aa2a-0742b874784c.png)

**Comment by kisantia** [comment]
fix for this will be in DacFx
