### ISSUE TITLE
Results pane does not allow user to see bottom-most row or scrollbar without resizing

### ISSUE THREAD

**Issue by nmyron** [microsoft/azuredatastudio#19664]
Issue Type: <b>Bug</b>

When I run a query against a database, the result pane often does not display the bottom left-right scrollbar, nor the last row of result data, without resizing the pane slightly upward.

This is a pretty consistent issue. If I run the query, this will occur. If I resize the pane, then run the query again, I will again have to resize the result pane to allow me to see the last result in the list as well as the bar. 

I pretty much have to run a query, resize the pane up to see the entire list after scrolling all the way down. Then resize it down again, run a new query, and move it back up if I intend to re-use the same tab. It's pretty inconvenient. 

Azure Data Studio version: azuredatastudio-insiders 1.37.0-insider (8cb6d48da2eb5e1d9f5a5719f6523ba1af0a2908, 2022-06-07T05:48:33.772Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (7.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.47.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.12.1

</details>

**Comment by nmyron** [comment]
Correction, if there is a bottom scrollbar for left-right, I never see it, even if I resize the pane for the bottom result to come into view

Here's a screen grab before and after I resize the pane. You can see the last row that is fully on screen is row with ident 4805, but there is a row with data just out of sight. 

If I click to resize that pane, and just pull it up just a tad, that row comes into view with ident 4800. Sometimes I can click that row also, and it will pop up into view and become visible. But, that last row (unless the result set is smaller than the pane itself) doesn't ever seem to be on screen by default.

![image](https://user-images.githubusercontent.com/3048553/172640513-b22372ae-6288-4a66-85e5-6355557c375c.png)
![image](https://user-images.githubusercontent.com/3048553/172641095-b7f3d321-1e63-4ec4-b24a-2aef59342087.png)

**Comment by alanrenmsft** [comment]
@nmyron are you still having this issue with the latest ADS? I tried but not able to reproduce it, can you think you of anything special about your local setup?

![query-grid-sizing](https://user-images.githubusercontent.com/13777222/184250442-e1abb229-2148-48c7-865c-72f66bba1f5d.gif)

**Comment by alanrenmsft** [comment]
please let us know if you are still having issues @nmyron
