### ISSUE TITLE
project update from database fails on schemaCompare.runComparison not found

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#19662]
Issue Type: <b>Bug</b>

Schema compare extension is installed and loads from a database directly. 
In sql project extension the "update project from database" option fails to open schema compare with an error message of `command 'schemaCompare.runComparison' not found"

Azure Data Studio version: azuredatastudio-insiders 1.37.0-insider (8cb6d48da2eb5e1d9f5a5719f6523ba1af0a2908, 2022-06-07T05:44:02.958Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
asde-deployment|Mic|0.4.1
dacpac|Mic|1.10.0
schema-compare|Mic|1.13.0
sql-database-projects|Mic|0.17.0
indent-rainbow|ode|8.2.2

(1 theme extensions excluded)

</details>

![2022-06-07_11-48-15 (1)](https://user-images.githubusercontent.com/12227241/172460148-630a9824-b2c5-4dc8-bde0-907b91c87181.gif)

**Comment by kisantia** [comment]
closing since I wasn't able to repro and there haven't been any other reports of this. Can investigate more if we can get a consistent repro
