### ISSUE TITLE
[CSS Supportability] Allow levels of verbosity in debug logs

### ISSUE THREAD

**Issue by suresh-kandoth** [Microsoft/azuredatastudio#1967]
When we enable debug logs, we need to be able to specify certain levels of verbosity so the person troubleshooting issues can get the level of logging they need. Also should be there some default level of logging enabled always - some simple things?

**Comment by ranasaria** [comment]
@suresh-kandoth. In the latest preview release, we have included the following user configurable settings:

    "mssql.tracingLevel": "All",
    "mssql.logFilesRemovalLimit": 100,
    "mssql.logRetentionMinutes": 60,

mssql.tracingLevel allows the user to configure the tracing at several levels. Default setting out of the door is set to "Critical". Kindly use the feature and share any feedback that you have.
