### ISSUE TITLE
cannot use Ctr+C in Grid results

### ISSUE THREAD

**Issue by Terrymac22** [microsoft/azuredatastudio#19694]
Issue Type: <b>Bug</b>

I have Azure data studio installed on my mac. I have also setup keyboard shortcuts on the mac and in Azure data studio to set Ctrl+C = copy. This works everywhere but in the grid of azure data studio. I can highlight an item in the grid, but when I hit Ctrl+C, it does not copy. This works correctly in the query window, just not in the grid. Also, when I highlight an item in the grid and use the menus, the keyboard shortcut for copy says ^C. So I know I have the shortcut setup correctly.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:26:00.881Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
whoisactive|Mic|0.1.4

</details>

**Comment by alanrenmsft** [comment]
@Terrymac22 the fix is in the latest insider build and will be in next stable build in a couple weeks.
