### ISSUE TITLE
open the connection viewlet after the database is published or at least show a message to user to give more info of what to do next

### ISSUE THREAD

**Issue by stuartpa** [microsoft/azuredatastudio#19718]
From Lelia:

Thanks for your feedback. I'll check if we can open the connection viewlet after the database is published or at least show a message to user to give more info of what to do next. would you mind creating an issue [here]

From Silvano:

Once the database is published to local emulator you should see it popping up automatically in your connections of the SQL Server panel in VS Code.
If that didn’t work it is clearly a bug, adding Leila to see if she can help troubleshooting.

From Stuart:

Really impressed with the Azure SQL DB Emulator experience in VS Code, it just worked first time I tried it.
 
Only thing I found that didn’t flow in the experience, is “Publish” just ended with [1], with no hint on what to do next.
 
What do I do now?
 
What I think I want is for a SQL Server “Connection” to be automatically opened in Code.  Can this be made to happen? (e.g. like this [2], which I did manually)

[1]
![image](https://user-images.githubusercontent.com/9289538/173348271-b3aa9a42-1039-467f-a511-9be3f6046731.png)

[2]
![image](https://user-images.githubusercontent.com/9289538/173348309-c1ec3f52-b1a6-411f-9e80-7a2f530afcc8.png)

**Comment by llali** [comment]
this is already fixed in the upcoming release of SQL Project extension
