### ISSUE TITLE
Sql projects table designer description issues

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#19719]
1. Create a new table and open it in designer, add description to "Id" and hit save, added description is not showing up for me.
2. redundant GO line in sql file after publishing description
![image](https://user-images.githubusercontent.com/21186993/173408651-d823b722-2c97-4f93-9cc6-1c40637cd48a.png)
3. description edit/deletion not working

**Comment by kisantia** [comment]
More details:
1. descriptions are never getting added for columns, but do get added for the table and indexes. For primary key, foreign key, check constraints, the description gets added if it's added the same time as the object, but if a description is added later, it isn't actually added when publishing.
2. extra GO isn't consistently added. Seems like it's only happening for primary keys, foreign keys, and check constraints.
3. table and index descriptions get updated and deleted, but constraint, primary key, and foreign key descriptions do not.
