### ISSUE TITLE
New T-SQL functions are not colored

### ISSUE THREAD

**Issue by mkorsukov** [microsoft/azuredatastudio#19737]
Environment:
- Azure Data Studio Version: 1.37.0
- OS Version: Ubuntu Linux x64 5.13.0-48-generic

Steps to Reproduce:

1. Create a new query:
```sql
-- OLD
select coalesce(1, null);

-- NEW functions
select greatest(1,2,3);
select least(1,2,3);

```

2. The old function is colored, but new ones remain in "default" code color.

![image](https://user-images.githubusercontent.com/21244808/173922816-d5a1e9da-e8c1-426a-8240-16adb87d50c3.png)

3. Consider coloring other functions as well: `generate_series`, `date_bucket`.

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/19756 - we'll use that one as the main tracking issue for incorrect colorization
