### ISSUE TITLE
SQLCMD mode button in query does not appear

### ISSUE THREAD

**Issue by bootrider** [microsoft/azuredatastudio#19744]
- Azure Data Studio Version:1.37.0
- OS Version:Windows_NT x64 10.0.19042

Steps to Reproduce:

1. Create a connection
2. over the connection, right click -new Query
3. the button does not appear.

Looking for  solution I found that this functionality was added in september 2019:
https://cloudblogs.microsoft.com/sqlserver/2019/09/10/the-september-release-of-azure-data-studio-is-now-available/

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
Do you have preview features enabled? Settings -> Workbench: Enable Preview Features

![image](https://user-images.githubusercontent.com/28519865/174115781-b8147557-511f-4f7c-9e1e-c18d1ab1b0f5.png)

That is required to use SQLCMD mode currently.

**Comment by kburtram** [comment]
Closing based on previous comment.  Please let us know if the above doesn't work for you.

**Comment by bootrider** [comment]
It works!!! thanks
