### ISSUE TITLE
Infinite loading animation after connect to SQL server

### ISSUE THREAD

**Issue by NemecMichal** [microsoft/azuredatastudio#19747]
Issue Type: <b>Bug</b>

Infinite loading animation after SQL server is connected (green badge next to server name).
No databases are shown.

<img width="448" alt="Screenshot 2022-06-16 at 9 59 08" src="https://user-images.githubusercontent.com/74740622/174022371-ef98e547-8357-4e5e-b875-98b5eb65eb32.png">

For this to work, I need to exit Azure Data Studio (CMD+Q) and reopen (several times).
<img width="440" alt="Screenshot 2022-06-16 at 10 04 20" src="https://user-images.githubusercontent.com/74740622/174022980-7691d18f-6ba0-40bf-b5f0-fb2fb6c8a455.png">

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T19:53:12.357Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.14.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by aasimkhan30** [comment]
This issue is fixed by #21954 and #21811
