### ISSUE TITLE
T-SQL functions are not colored in correctly in query editor

### ISSUE THREAD

**Issue by aborremans** [microsoft/azuredatastudio#19756]
Issue Type: <b>Bug</b>

I noticed that JSON functions were not the correct color in the ADS query editor. Upon investigation, I found that there are several other T-SQL functions are also not the correct color in the query editor. See attached screenshot. 

When looking to see if this was already reported I found Issue #19737 which only reports a couple of newer T-SQL functions, not the below list.

![image](https://user-images.githubusercontent.com/13876614/174161310-6cfbc055-94fe-4815-b6b5-b10254ce1b15.png)

Functions that I have noticed where function name is not colored correctly in the ADS query editor:
JSON_VALUE
JSON_QUERY
JSON_MODIFY
APPROX_COUNT_DISTINCT
LAG
LEAD
COLLATIONPROPERTY
TERTIARY_WEIGHTS
ENCRYPTBYKEY
DECRYPTBYKEY
ENCRYPTBYPASSPHRASE
DECRYPTBYPASSPHRASE
KEY_ID
KEY_GUID
DECRYPTBYKEYAUTOASYMKEY
KEY_NAME
SYMKEYPROPERTY
ENCRYPTBYASYMKEY
DECRYPTBYASYMKEY
ENCRYPTBYCERT
DECRYPTBYCERT
ASYMKEYPROPERTY
ASYMKEY_ID
SIGNBYASYMKEY
SIGNBYCERT
VERIGYSIGNEDBYCERT
IS_OBJECTSIGNED
DecryptByKeyAutoCert
HASHBYTES
DATALENGTH
IDENT_SEED
IDENT_CURRENT
IDENT_INCR 
SQL_VARIANT_PROPERTY
GENERATE_SERIES
DATE_BUCKET
GREATEST
LEAST

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (17.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.14.0
sql-database-projects|Mic|0.17.1
simple-data-scripter|sea|0.1.6

</details>

**Comment by Charles-Gagnon** [comment]
Thanks @aborremans, this is a great list! We're working on filling in the gaps here and this list will be a great starting point. Appreciate the time you took to list these all out!

I've added the ones from the other issue and will close that one to keep these all consolidated into one

@llali FYI

**Comment by Charles-Gagnon** [comment]
@aborremans These should be correctly colorized in the latest ADS update. Let us know if you see any more that aren't correct!

![image](https://user-images.githubusercontent.com/28519865/181388158-a7c944f0-a41f-4b85-9444-ed6d576cf14c.png)

**Comment by aborremans** [comment]
I just updated to the most recent version and things are looking great! Thanks @Charles-Gagnon
