### ISSUE TITLE
ADS should have the multi-caret feature that VS and SSMS have.

### ISSUE THREAD

**Issue by ShadowFiendZX** [microsoft/azuredatastudio#19753]
In VS and SSMS you can use mutli-caret editing by doing Shift+Alt Up/Down. [Here's](https://docs.microsoft.com/en-us/visualstudio/ide/finding-and-replacing-text?view=vs-2022#multi-caret-selection) some docs.
This feature greatly improved the development experience when it was added to VS and SSMS, and should be added to ADS, especially for parity's sake.
Currently in ADS if you do Shift+Alt Down it'll just duplicate a line downwards, this is typically done via Ctrl+D, although in VS it's Ctrl+E+V. This behavior is rather annoying when expecting the keybind to behave the same way as it does in VS and SSMS.

**Comment by alanrenmsft** [comment]
@ShadowFiendZX the feature is also available in ADS, by default it is: CTRL+SHIFT+ UP/DOWN keys. You can customize the keyboard shortcut settings by running this command:
![image](https://user-images.githubusercontent.com/13777222/174142132-45c75ce5-66c7-409f-aed9-6997874050ea.png)

some background: Azure Data Studio is a fork of VSCode, not sure why vscode decided to use a different shortcut key to begin with, we inherited it from VSCode.

I just did a quick search and found there is an extension for VSCode that does what you want: https://marketplace.visualstudio.com/items?itemName=ms-vscode.vs-keybindings, please download the extension and install it in ADS
![image](https://user-images.githubusercontent.com/13777222/174143614-492c2dd5-51f8-40ff-97cd-ae0121502011.png)

![image](https://user-images.githubusercontent.com/13777222/174143528-47bef6ad-42fc-4fbf-b459-c5ddbd8dc28a.png)

you should be able to use the VS shortcuts.

**Comment by ShadowFiendZX** [comment]
Thank you, that'll be a great help.
