### ISSUE TITLE
Results grid rows disappear when clicking headers

### ISSUE THREAD

**Issue by irahsu** [microsoft/azuredatastudio#19771]
Issue Type: <b>Bug</b>

Open a new query window and run a query that returns > 20 rows and creates a vertical scroll bar. Scroll down more than half way, then click a column header. Rows from the bottom of the result grid will disappear. Scrolling or sorting results causes them to re-appear. The further down you scroll, the more rows disappear, eventually resulting in all rows disappearing!

For full video showing the bug, see here: https://www.youtube.com/watch?v=4kuAQUtsi3s

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5950X 16-Core Processor             (32 x 3400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (12.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|36%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0
schema-compare|Mic|1.14.0
sql-database-projects|Mic|0.17.1

</details>
<!-- generated by issue reporter --
![ezgif-4-98221b3e20](https://user-images.githubusercontent.com/14944424/174416425-f5e1e45f-c8a0-4b9d-b9c0-9f2715454267.gif)
>

**Comment by irahsu** [comment]
![ezgif-4-98221b3e20](https://user-images.githubusercontent.com/14944424/174416505-4a714e60-8e9a-4aac-8bb5-561e52c83430.gif)

**Comment by alanrenmsft** [comment]
@irahsu thanks for reporting the issue, I've fixed it and next stable build should have the fix, if you are using Insider build, you should be able to get the fix by next week.
