### ISSUE TITLE
`with as` is highlighted as error

### ISSUE THREAD

**Issue by Fred-Wu** [microsoft/azuredatastudio#19776]
The `with as` clause is highlighted as error with the following message, but the codes are running fine. 

![image](https://user-images.githubusercontent.com/4111978/174520879-3b1af2c2-52e4-457c-ad0a-95f895374d8f.png)

![image](https://user-images.githubusercontent.com/4111978/174520684-f3c1da03-7db5-4e47-8071-e39e7f796f84.png)

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/199832077-d2d5b22f-64a8-42de-9398-7984e8af1e88.png)
this is fixed now.
