### ISSUE TITLE
Highlight schema difference in Schema Compare

### ISSUE THREAD

**Issue by davidcchase** [microsoft/azuredatastudio#19800]
Issue Type: <b>Feature Request</b>

When using Schema Compare in Visual Studio, the differences in the DDL are highlighted (so, for example, I can easily pick out a column name change in a large table). This is extremely helpful and should be in ADS Schema Compare.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No

**Comment by kisantia** [comment]
ADS schema compare leverages the existing vscode diff editor. A column name change is shown like this - can you please elaborate on what the desired behavior here would look like?
![image](https://user-images.githubusercontent.com/31145923/175393302-c6233fb2-917c-4568-9629-c2199fc1e888.png)

**Comment by kisantia** [comment]
feel free to reopen if more information on the request can be provided
