### ISSUE TITLE
Table Design: Error on publish since 1.37

### ISSUE THREAD

**Issue by drizztdourden08** [microsoft/azuredatastudio#19812]
Hi,

Let me start by saying THIS is the functionality that I was waiting for since ADS was first announced (It was called SQL data studio at first I believe). The Table design was the missing component for this to be the only tool required for any database and ditched the old SSMS entirely.

We're not completely there but I was really happy when it first made it's way in ADS a couple months back. I've been using it since then whenever possible. This new addition sicne 1.37 of being able to reorder and everything was the last brick in my opinion for this to be usable in most situation.

However, I've just updated and can't use the designer anymore for some reason. Used it yesterday before updating and it worked just fine.

Today, after the update, It gives me the error message in the screenshot below:
![image](https://user-images.githubusercontent.com/36481532/175332661-762fea5d-a233-4710-b237-8af13d143a2a.png)

I'm not sure if it's related to the update or not. Restarting doesn't change anything. I can do any other query like normal.

regards,

**Comment by drizztdourden08** [comment]
Update: I've been able to modify another table just fine by adding a column at the right place.

Here's what I'm trying to do exactly here in this table:
1- Opening Designed
2- Waiting for the "preview message to go" and finish loading
3- Clicking on the "remove" button to delete the column
4- Confirming that I want to remove the column as it is indexed and will be removed from foreign and so on.
5- Click publish
6- Get the above error

I will be removing the column another way so I will not be able to test again unfortunately. Hope this is enough.

**Comment by drizztdourden08** [comment]
I am pretty sure it has something to do with the constraint somehow. I couldn't remove the constraint either (without removing the column).

SSMS removed everything just fine using the same method.

**Comment by caohai** [comment]
I took a brief look and was able to reproduce the error. I'll work on a fix in the coming few days.

**Comment by alanrenmsft** [comment]
@drizztdourden08 it was called SQL Operations Studio 😄

**Comment by caohai** [comment]
Fixed by STS vbump in #20150

@drizztdourden08 This should be fixed in the latest insider build. Can you give it a try?

**Comment by alanrenmsft** [comment]
@caohai actually we don't have an insider build today, there is an issue with the build pipeline. please wait for the new insider build.

**Comment by caohai** [comment]
> @caohai actually we don't have an insider build today, there is an issue with the build pipeline. please wait for the new insider build.

I think the latest insider is from 7/22. I tested with that one and this issue is fixed for me.
![image](https://user-images.githubusercontent.com/21186993/180855334-9320c5d4-1d6e-4c67-a69b-ae955e8fceaa.png)

**Comment by drizztdourden08** [comment]
Thanks for this. 

I don’t have an insider build to test on the machine where I saw the problem. It’s an enterprise server machine and I can’t use insider preview on it. I’ll take your word for it for now and wait for the release.

good support and timeline to work on this. Really great team. :)

**Comment by tdoshin** [comment]
Thank you so much for this feedback @drizztdourden08. It seems like you are very excited and knowledgeable about the Table Designer Feature in Azure Data Studio. Would you be interested in participating in a brief survey? If yes, please respond in this thread and I will follow up with additional details

**Comment by drizztdourden08** [comment]
Sure.

> Thank you so much for this feedback @drizztdourden08. It seems like you are very excited and knowledgeable about the Table Designer Feature in Azure Data Studio. Would you be interested in participating in a brief survey? If yes, please respond in this thread and I will follow up with additional details

Sure. Send it over. I’d be glad to help.
