### ISSUE TITLE
Database Picker Truncates/Obscures Long Database Names

### ISSUE THREAD

**Issue by swaschitz** [microsoft/azuredatastudio#19826]
Issue Type:  Feature Request (not a bug, but a nuissance)

When I connect to certain customer servers, their database names are longer than the pulldown will allow.  This makes it very difficult to select the correct database.  It is further compounded when the databases all start with the same first X characters, such that the only distinct characters are after the truncation/obscuring.  The only easy solution is to select the database and then look on the bottom corner of the screen to see if the correct one has been selected.  It is very tedious.  

I would like the control to size to the maximum width of the longest database name.  If this is not possible, can this control be resized.  If further not possible, can the font size of the control be made customizable?

The only workable solution was making the truncated/obscured selection and then glancing down at the bottom right status to see if I got the right one.  This frequently takes multiple attempts.

I've included a screenshot of one such customer system where it has been obscured/truncated.  This seems to happen on both Mac and Windows on the latest release 1.3.70.  The database names are "Display_Expand_Cloud_XXX", so you can see the XXX is being truncated.  The application in question is designed to look for the "Display_Expand_Cloud_" portion, so simply renaming the database is not possible.  I have other servers which have similar names that are slightly too long, so this is more than one application.  

<img width="842" alt="2022-06-22_16-34-24" src="https://user-images.githubusercontent.com/71793478/175778332-c581e6ea-a441-4ed1-aab9-95b896aa4903.png">

**Comment by alanrenmsft** [comment]
@swaschitz There was a bug when calculating the required width for a given text, I have fixed it. Could you please try the [latest insider build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)? 

The fix will be included in August's stable release.

**Comment by swaschitz** [comment]
I can confirm that this is now working as I would expect in this Insiders Release:

Version: 1.39.0-insider
OS: Darwin x64 21.6.0

Thank you very much!!!  I really appreciate it!
<img width="422" alt="2022-07-27_16-26-19" src="https://user-images.githubusercontent.com/71793478/181366374-7b23d1d8-50ef-440a-bc7a-b1d81d60c22c.png">

**Comment by swaschitz** [comment]
I can also confirm this is fixed on Windows.  Once again, thank you very much!!! I really appreciate it!
<img width="415" alt="2022-07-27_16-58-20" src="https://user-images.githubusercontent.com/71793478/181371158-1e801e1a-c216-441d-a002-ff3b56ecce3d.png">

**Comment by alanrenmsft** [comment]
@swaschitz good to know. thanks for confirming.
