### ISSUE TITLE
The scroll bar doesn't show or incorrect when resizing webview component in modelview

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#1984]
- install sqlservices (sample) extension
- Run cmd "sqlservices.openEditorWithWebView2"

Actual result:
The editor and scroll bar show correctly when it first displays.
However, when resize the window, the scroll bar either doesn't show or scrolling the scrollbar doesn't go through the end of the page. 

![image](https://user-images.githubusercontent.com/25463959/43022668-d68061e6-8c1c-11e8-96f1-e03c4e59a5ea.png)

**Comment by kburtram** [comment]
Closing out old issues.  Please reactive if this is still impacting a user scenario.
