### ISSUE TITLE
Table Designer preview add column fails on SYS_VER table

### ISSUE THREAD

**Issue by yzorg** [microsoft/azuredatastudio#19849]
**Is your feature request related to a problem? Please describe.**
1. Start with a table.  Add Period columns and enable SYSTEM_VERSIONING.
1. Open table designer on the table.
1. Add a column, drag to 2nd column in the table.
1. Click "generate script".

The script disables SYSTEM_VERSIONING correctly but doesn't add the column to the history table, so re-enabling history fails.

**Describe the solution or feature you'd like**
Consider including in the script adding the column to the history table too. 

**Describe alternatives you've considered**
Alternative 1. Ask user if they would like to drop and re-create empty _History table.
Alternative 1b. Instead of dropping, give user the option to rename history table with a unique suffix, like _20220627, _20220627b, _20220627c, etc.

**Additional context**
11:24:02 AMStarted executing query at Line 73
Msg 13523, Level 16, State 1, Line 79
Setting SYSTEM_VERSIONING to ON failed because table 'FooOffice.sm.tmp_ms_xx_MyTable' has 15 columns and table 'FooOffice.sm.MyTable_History' has 14 columns.
Batch execution time: 00:00:00.254
An error was encountered during execution of batch. Exiting.
Total execution time: 00:00:01.814

In first step, my SYSTEM_VERSIONING columns and history table looks like:
```sql
    [PeriodStart]   DATETIME2 (7) GENERATED ALWAYS AS ROW START HIDDEN NOT NULL,
    [PeriodEnd]     DATETIME2 (7) GENERATED ALWAYS AS ROW END HIDDEN   NOT NULL,
    PERIOD FOR SYSTEM_TIME ([PeriodStart], [PeriodEnd]),
-- PK here
) WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE=[sm].[MyTable_History], DATA_CONSISTENCY_CHECK=ON));
```

**Comment by caohai** [comment]
Fixed by STS vbump in #20031
