### ISSUE TITLE
A11y_Azure Data Studio extension 'Azure SQL Migration'_Assessment results and recommendations_ScreenReader: Narrator/NVDA is not announcing 'Choose your azure SQL target' label name when focus lands on Azure SQL managed instance/SQL server on AVM radio buttons

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/azuredatastudio#19844]
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### Github Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #Benchmark; #SH-AzureSQLMigration-Win32-Jun2022; #DesktopApp; #Win32; #SQL Migration Control Plane; #WCAG2.1.1; #Keyboard;

### Environment and OS details:
Azure Data Studio Version 1.37.0(User Setup)
Windows Version 21H2 (OS Build 22000.675)

### Note:

- This issue is observed for radio buttons and browse folder name fields in "Get Azure recommendation" dialog as well
- This issue is observed for all form fields present in the app

### Repro Steps:

1. Turn on Narrator/NVDA
2. Install Azure data studio app and install Azure SQL migration extension
3. Connect to SQL server, tab till respective server, right click and select manage
4. Tab till Azure SQL Migration in sitemap and press enter key
5. Tab till migrate to azure sql and press enter
6. Navigate to databases grid in "Databases for assessment" in step 1, select few databases and click on 'next' button
7. Navigate to Azure SQL managed instance/SQL server on AVM radio buttons in "Assessment results and recommendations" and verify screen reader is announcing corresponding 'Choose your azure SQL target' label name or not

### Actual Result:
Narrator/NVDA is not announcing 'Choose your azure SQL target' label name when focus lands on Azure SQL managed instance/SQL server on AVM radio buttons

### Expected Result:
Narrator/NVDA is not announcing 'Choose your azure SQL target' label name when focus lands on Azure SQL managed instance/SQL server on AVM radio buttons

### Attachment:
![NVDA (2)](https://user-images.githubusercontent.com/83570638/176119927-337aa76a-2f02-449b-88a0-489231dbdd4a.png)
![NVDA (3)](https://user-images.githubusercontent.com/83570638/176119973-494471c7-8d15-4916-ab8c-091f1f2a4768.png)
![Narrator_](https://user-images.githubusercontent.com/83570638/176120111-cc9a42a4-7885-48ef-b146-7abfb4929903.gif)

**Comment by VijayaBharathyA** [comment]
@aasimkhan30 
**Verified the issue in below Environment:**
Issue is Partially fixed could please Reactivate the bug 
Version: 1.41.1 (user setup)
![Notes_NVDA](https://user-images.githubusercontent.com/100189407/218031182-657f4b16-11d4-4817-a096-344beed469ad.png)
![Notes_Narrator](https://user-images.githubusercontent.com/100189407/218031190-b5166858-ec14-4fe0-b599-d1d7ca1a362a.png)
![Choose your azure SQL target_NVDA](https://user-images.githubusercontent.com/100189407/218031194-628b1fff-6820-4191-8413-a6aec024ed9a.png)
![Choose your azure SQL target_Narrator](https://user-images.githubusercontent.com/100189407/218031195-ce51a4ff-640e-4538-81be-5b0aaeb39e20.png)

**Comment by aasimkhan30** [comment]
Adding a demo extension as an example of this bug:
Please install this extension using:
![image](https://user-images.githubusercontent.com/6816294/221327707-9e84f364-8944-4010-accb-c6b1205dbae5.png)

Once installed:
1. Press F1
2. Type Bug Dialog 19844 and select the first option
![image](https://user-images.githubusercontent.com/6816294/221327747-82f4a38e-2cdc-46b8-9608-aab76e8d7466.png)
3. This should open a dialog with the example of the bug:
![image](https://user-images.githubusercontent.com/6816294/221327812-01fd9cf4-d845-4892-81bc-c96f1bdcc19b.png)


[adsextensionzip.zip](https://github.com/microsoft/azuredatastudio/files/10829952/adsextensionzip.zip)

**Comment by brian-harris** [comment]
@VijayaBharathyA This bug seems to be related to a narrator issue and not/no longer an ADS or SQL-Migration extension issue. I am closing this bug.  Please open a 3rd party issue with narrator using the sample above.

**Comment by VijayaBharathyA** [comment]
#closed; 
**Verified issue in Below environment :**
Version: 1.44.0-insider (user setup)
Commit: 938a8bffbe2b9950e545f583a575f71c2caab08e
Date: 2023-04-18T05:29:43.917Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
NVDA is announcing select a folder on your local drive
![Fixed (4)](https://user-images.githubusercontent.com/100189407/234222045-552ccc9b-71a6-4dc6-b23d-c4632058719b.png)
