### ISSUE TITLE
A11y_Azure Data Studio extension 'Azure SQL Migration'_Azure SQL target_Keyboard: On pressing esc to collapse tooltips, entire "Migrate to Azure SQL" dialog gets closed

### ISSUE THREAD

**Issue by NiharikaTipirishetty** [microsoft/azuredatastudio#19847]
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### Github Tags:
#A11yMAS; #A11yTCS; #A11ySev3; #Benchmark; #SH-AzureSQLMigration-Win32-Jun2022; #DesktopApp; #Win32; #SQL Migration Control Plane; #WCAG2.1.1; #Keyboard;

### Environment and OS details:
Azure Data Studio Version 1.37.0(User Setup)
Windows Version 21H2 (OS Build 22000.675)

### Note:
This issue is observed for all the tooltips present in the app

### Repro Steps:

1. Install Azure data studio app and install Azure SQL migration extension
2. Connect to SQL server, tab till respective server, right click and select manage
3. Tab till Azure SQL Migration in sitemap and press enter key
4. Tab till migrate to azure sql and press enter
5. Navigate to databases grid in "Databases for assessment" .
6. Navigate to tooltips present in step 3 and press esc, verify that entire dialog gets collapsed instead of tooltip info

### Actual Result:
On pressing esc to collapse tooltips, entire "Migrate to Azure SQL" dialog gets closed

### Expected Result:
On pressing esc to collapse tooltips, tooltip info should get collapsed/dismissed, entire "Migrate to Azure SQL" dialog shouldn't get closed.

### Attachment:
![Keyboard_azure sql target_](https://user-images.githubusercontent.com/83570638/176179005-3fb067dc-fa65-45d4-9d63-b570c640f1ce.gif)

**Comment by aasimkhan30** [comment]
This issue is duplicated of  https://github.com/microsoft/azuredatastudio/issues/19583
and was fixed by PR #19741
