### ISSUE TITLE
Cannot connect to Azure SQL Database.

### ISSUE THREAD

**Issue by tomdecort** [microsoft/azuredatastudio#19863]
Issue Type: <b>Bug</b>

Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T19:53:12.357Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.10.0
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.14.0
server-report|Mic|0.2.3
sql-database-projects|Mic|0.17.1
whoisactive|Mic|0.1.4
azdata-sanddance|msr|3.3.0
schema-visualization|R0t|0.3.0

</details>

**Comment by cssuh** [comment]
@tomdecort Do you see any errors in the Developer Tools Console when you encounter this issue?

**Comment by tomdecort** [comment]
Hi,

Really appreciate your quick response. The problem was that I didn’t fill in the database name (azure hosted SQL Server, account with read-only on DB), the error description is a bit confusing as to me.

Cheers,
Tom


On 29 Jun 2022, at 21:36, Christopher Suh ***@***.******@***.***>> wrote:



@tomdecort<https://github.com/tomdecort> Do you see any errors in the Developer Tools Console when you encounter this issue?

**Comment by cheenamalhotra** [comment]
I will proceed to close this as user-error, as confirmed in [comment](https://github.com/microsoft/azuredatastudio/issues/19863#issuecomment-1171017403).
The error thrown is expected, as ADS is making connection to 'default (master)' database, and wouldn't know you didn't intend to connect to 'master' DB.
