### ISSUE TITLE
Problem with Cyrillic encoding when exporting JSON

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#1986]
- SQL Operations Studio Version: 0.30.6
- SQL Server 2017 (14.0.3030.27)

I want to save a table to JSON and then import it to SQL Server. The table contains Cyrillic characters.
Source data:
```SQL
CREATE TABLE tempdb..CyrTable
(
    atext nvarchar(max),
    id    nvarchar(20)
);

INSERT INTO tempdb..CyrTable VALUES
(N'просто текст 1', N'1'),
(N'просто текст 2', N'2');

SELECT * FROM tempdb..CyrTable;
```

Then I save this data into JSON using Windows-1251 encoding (`"files.encoding": "windows1251"`).
Finally, I [import](https://blogs.msdn.microsoft.com/sqlserverstorageengine/2015/10/07/bulk-importing-json-files-into-sql-server/) saved JSON file into table:
```SQL
SELECT json_data.*
FROM OPENROWSET (BULK 'C:\Temp\data.json', SINGLE_CLOB) AS x
CROSS APPLY OPENJSON(BulkColumn) WITH
(
    atext nvarchar(max),
    id    nvarchar(15)
) AS json_data;
```
However, I get incorrect data:
![IMG_1](https://nperza.am.files.1drv.com/y4m2E4mSdE3uLJQLG_JOHCsCHbdblTqSM2dNSA0DyWW8lUJnegp9eD9wWLi3JEV8EToeWGCWaUjnFIYNwGWd6G-2BA8NlMKwB-rxXo1rC-cu7VXA_khz3WMSs6djvfhnaecyvl3h5MvVFgEH39mFLdIQD4yXWuqZGH-TrWMMNyU4zO75D5AXzuQv3RiWpAHRL1I3h6PeeRlLkRt8oGTuupGPw?width=223&height=102&cropmode=none)

When I saved JSON file in external text editor with Windows-1251 encoding again, then everything worked perfectly:
![IMG_2](https://npekhq.am.files.1drv.com/y4mxM39Sx9n2BhzFocs8AZnM2tyhbFDzW45WoanYntmvon8HJC1eQzqcg3uViYuegK_s3KUwoQLfhzTvClDRd_3dq2r6xZxi4CS6iDHnBaoC_7RntGD5i2JQSr3fOPI3JxpyRb05BMXylkd5YZNrJRQn5fgmv7Uyuw3yqz7RLL1By1_pXpJn--h0hOh6VkCWiteuIYdFzLvETOo6hCWnUTe4A?width=154&height=81&cropmode=none)

**Comment by smartguest** [comment]
Issue appears that the Save as Json button seems to save using the UTC-8 encoding rather than Windows-1251, this will need to be fixed.

**Comment by smartguest** [comment]
@JohnyL For now: the workaround for this issue is to immediately after the JSON file pops up in the editor is to click the encoding button once more and click "Save with encoding" and select Windows-1251 to properly save the file into JSON with the right encoding. The current design of saving to JSON does not take into account the formatting of the editor and is handled by another service. More investigation is required.

**Comment by kburtram** [comment]
Closing based on about merged PR.
