### ISSUE TITLE
A11y_SQLAzureDataStudioMAC_Extensions - install_Usability: Non-interactive text elements such as Extension name (Example: SQL server import) and 'Microsoft' are receiving keyboard tab focus.

### ISSUE THREAD

**Issue by bbarik06** [microsoft/azuredatastudio#19877]
**GitHubTags:** #A11yUsable;#A11yTCS;#A11ySev4;#BM_SQLAzureDataStudioMAC_June2022;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#Keyboard;#AINotInScope;#A11yUsablehigh;

## Environment Details:
Application Name: SQL Azure Data Studio
Application Version: Version 1.37.0
Mac Version: macOS Monterey 12.4

## Repro Steps:

1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix.
2. Launch SQL Azure data studio.
3. Connect to a server.
4. Tab to 'Extensions' button and select.
5. Tab till Extension name (here: SQL server import) and microsoft text element.
6. Use keyboard to check of non-interactive text element receiving keyboard tab focus.

## Actual:
Non-interactive text elements such as Extension name (Example: SQL server import) and 'Microsoft' are receiving keyboard tab focus.

## Expected:
Non-interactive text elements such as Extension name (Example: SQL server import) and 'Microsoft' should not be receiving keyboard tab focus.

## User Impact:
Keyboard users will face difficulty in perceiving the user interface component and will think that the control has some action to perform.

## Attachment:
![17_Keyboard focus on](https://user-images.githubusercontent.com/98393966/176432801-3490748d-bbeb-4046-b8fd-6a6012ddad48.gif)

**Comment by alanrenmsft** [comment]
bulk closing the usability level issues since we are not planning to work on it anytime soon.
