### ISSUE TITLE
A11y_SQLAzureDataStudioMAC_Extensions - install_ScreenReader: When using Voice-over Ctrl+ Option+ Arrow keys the non-group contents such as 'version number', 'Preview', 'Microsoft' text element are being announced as 'Group'

### ISSUE THREAD

**Issue by bbarik06** [microsoft/azuredatastudio#19879]
**GitHubTags:** #A11yMAS;#A11yTCS;#A11ySev2;#BM_SQLAzureDataStudioMAC_June2022;#SQL Azure Data Studio;#MAC;#FTP;#DesktopApp;#AINotInScope;#WCAG1.3.1;#VoiceOver;

## Environment Details:
Application Name: SQL Azure Data Studio
Application Version: Version 1.37.0
Mac Version: macOS Monterey 12.4
Screen Reader: VoiceOver

## Repro Steps:

1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix.
2. Launch SQL Azure data studio.
3. Connect to a server.
4. Tab to 'Extensions' button and select.
5. Tab till 'Version' details, 'Microsoft' text.
6. User Voice-Over to observe.

## Actual:
Non - group contents such as 'version number', 'Preview', 'Microsoft' text element has been set into group and are being announced as group, when the user uses Voiceover Ctrl+ Option+ Arrow keys to move across the text element.

## Expected:
Non - group contents such as 'version number', 'Preview', 'Microsoft' text element should not be set into group.

## User Impact:
The users will receive wrong information of grouping.

## Attachment:
![17_Non group contents](https://user-images.githubusercontent.com/98393966/176434222-6acb4ec8-2da2-4db5-847c-d45af3f184de.gif)

**Comment by alanrenmsft** [comment]
this seems to be an issue with the voice-over screen reader, not sure why is it reading things as group. also, if you think this is an issue that needs to be fixed, please open an issue in vscode repo, we inherited it from vscode.

**Comment by sspatil123** [comment]
GithubTags:#Closed;Version 1.41.2
![image](https://user-images.githubusercontent.com/85863999/220017853-3aa970ca-223c-4415-a8f6-cb20724417ca.png)
