### ISSUE TITLE
Command or api to display dashboard

### ISSUE THREAD

**Issue by languy** [microsoft/azuredatastudio#19916]
**Is your feature request related to a problem? Please describe.**
I'm building a breadcrumb where one of the active elements would the dashboard for an account.
The dashboard, defined in [`package.json`](https://github.com/Azure/azure-cosmosdb-ads-extension/blob/e1280acb0f25b00f4e295db57378d06bf2489222/package.json#L109), is normally opened from the connection tree either by double-clicking on the connection node or selecting the "Manage" option item from the right-click context menu.

**Describe the solution or feature you'd like**
An api or an action that I can call from anywhere in my extension code to programmatically open this dashboard.

**Describe alternatives you've considered**
I've looked in the code and see that there's an internal "objectExplorer.Manage" command. The trick is to call it with all the correct connection parameters.

**Comment by Charles-Gagnon** [comment]
You should also be able to call [connect](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/azdata.d.ts#L198) and pass in true for `showDashboard`.
