### ISSUE TITLE
Can't edit design existing table and publish

### ISSUE THREAD

**Issue by NvHulst** [microsoft/azuredatastudio#19915]
Issue Type: <b>Bug</b>

Whenever I want to alter the design of a table by removing a column and then publish the changes, I get an error:

'
Table Designer Error

An error occurred while generating preview report: Object reference not set to an instance of an object
'

There is however no link to the specific deleted column, it just won't publish results. However altering the table trough Azure portal with plain sql commands works perfectly.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T19:53:12.357Z)
OS version: Darwin x64 21.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (0.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by NvHulst** [comment]
There was not constraint for the column, it seemed that it was just not possible to publish the changes in any way. Even adding new columns or changing anything to the table, all failed to publish. However changing the same things directly using a query without using this software, worked perfectly.

**Comment by caohai** [comment]
Got it, I just did a quick sanity check with the latest ADS version on my intel Mac and it's working fine.
@alanrenmsft Can you do a quick test on your M1 Mac?

**Comment by alanrenmsft** [comment]
@NvHulst could you please try the same operation using the latest insider build: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main?  When you see the error you should be able to use the 'copy details' button to get the detailed error message and share it with us.

![image](https://user-images.githubusercontent.com/13777222/177840541-e53e2a43-799f-4dac-a3f6-149e1d9f4c42.png)

**Comment by alanrenmsft** [comment]
@NvHulst please wait until at least 7/11, I realized there was a bug causing the call stack not being included in the error message, I've fixed it and 7/11's insider build should have the fix so that you can copy the detailed the message.

**Comment by erinstellato-ms** [comment]
@NvHulst Checking in to see if you can share more info on the error message with us.  Thanks!
