### ISSUE TITLE
Once signed in, always signed in...

### ISSUE THREAD

**Issue by j3ffc0ll1ns** [microsoft/azuredatastudio#19913]
Issue Type: <b>Bug</b>

1. Select Accounts from within ADS
2. From a previously successful GitHub sign in, an account will display
3. Choose to remove that account
4. Now select to add a new account
5. Browser window will open and the account I wish removed will display as already signed-in
6. Choose sign out (or sign out and forget, same result)
7. New sign-in window appears asking for credentials
8. Select other options then select sign in with GitHub

The login process then completes with the old account and does not prompt for the GitHub credentials of the account I want to use

....thus you cannot change to a different GitHub account if you have ever previously signed in.

I restarted both ADS and VS Code and also changed the default browser on my computer in an attempt to thwart the cookie monster to no avail.....

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.69GB (5.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.3
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
import|Mic|1.5.0
powershell|ms-|2022.5.1
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.14.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.1
whoisactive|Mic|0.1.4
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cssuh** [comment]
I am not able to reproduce this on my system, once I select "sign in with github" it brings me to this page where I can select an email associated with my account.  I am then able to select "use a different email address" which then allows me to enter a different account email.  Do you see this option @j3ffc0ll1ns ?  If not, can you please send a screenshot/video of what you see?
<img width="442" alt="Screenshot 2022-11-02 at 3 21 47 PM" src="https://user-images.githubusercontent.com/18150417/199613819-8eb49f21-e905-4bdc-981d-c123dc18deb1.png">

**Comment by cheenamalhotra** [comment]
Closing this as inactive and lack of repro.
