### ISSUE TITLE
Checkbox on table component is not aligned properly on multiple extension and needs CSS styling fix

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#19921]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Install SQL Migration extension and start migrating the server
2. Opens a Tab with "Step 1: Databases for assessment" which has all the checkboxes on the table and they are not aligned vertically center
3. Also, other way is through the SQL DB extension > right click on sql DB proj > publish > 'Advanced...' button and observer the checkboxes alignment.
![image](https://user-images.githubusercontent.com/74571829/177422381-faa0e378-4354-42d9-b22e-0fd8bddfe205.png)
![image](https://user-images.githubusercontent.com/74571829/177422437-db8dcb5d-9233-49f2-ae82-02dc8037b092.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
@aasimkhan30 could you please take care of this one?

**Comment by aasimkhan30** [comment]
This is already done. I will find the pr, mention it here and close the issue

**Comment by aasimkhan30** [comment]
This issue was addressed by this PR https://github.com/microsoft/azuredatastudio/pull/20514. Closing it for now.
