### ISSUE TITLE
Database Drop down in Query Window quickly disappears when clicked

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#19938]
- Azure Data Studio Version: Insiders build and 1.37
- OS Version: Windows Enterprise

Steps to Reproduce:

1. Right click on connected server instance and select New Query to open Query Window
2. Click the drop down containing list of databases (Drop-down is right next to "Change Connection" button)

Expected result: 

See list of databases in the drop down 

Actual result:

List appears but then quickly disappears

Does this issue occur when all extensions are disabled?: Yes

@kburtram

**Comment by chlafreniere** [comment]
Hi @tdoshin I can't repro this myself. Does this happen consistently for you?

**Comment by alanrenmsft** [comment]
no repro.
