### ISSUE TITLE
Show multiple explain plans even if they are in different batches

### ISSUE THREAD

**Issue by LitKnd** [microsoft/azuredatastudio#1995]
- SQL Operations Studio Version: 0.31.4, mac

Steps to Reproduce:

* Separate two queries by the GO batch separator
* Highlight both queries
* Click 'Explain'
* You will only see the explain plan / estimated plan for the first query

Desired behavior:

* Get estimated execution plans for both queries

(Note: This is also the same desired behavior for actual plans, currently you can only get one actual plan even if they are in the same batch.)

![2018-07-24_09-24-47](https://user-images.githubusercontent.com/1623675/43152731-2f5e6312-8f24-11e8-89e5-6440d2f1f0a4.gif)

**Comment by kburtram** [comment]
Note per #2922 this also impacts multiple statements in the same batch when getting the actual plan.

**Comment by kburtram** [comment]
Please try **SentryOne Plan Explorer** extension, which should support this scenario.  This extension is our recommended query plan viewer.  Thanks!
