### ISSUE TITLE
Bring back icons for Node/Edge graph table types 

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#19952]
- Azure Data Studio Version: Insiders
- OS Version: Windows System Enterprise

Steps to Reproduce:

Icons needed to differentiate between different table types. They were in version 1.34 but removed since then. 

![image](https://user-images.githubusercontent.com/72947001/177879406-f70ec09e-45aa-4343-a00d-55ae5cb0fd8d.png)

Does this issue occur when all extensions are disabled?: Yes/No

@alanrenmsft

**Comment by tdoshin** [comment]
Any chance we can get this for the August Release? We may be doing another PGI demo in September and will need to be able to visually describe node vs graph tables to audience members @alanrenmsft

**Comment by alanrenmsft** [comment]
not sure, the priority of this is lower than other issues that I am working on. but I will try to get to this once I am done with other high priority bugs.
