### ISSUE TITLE
SQL DB Localization needs to be fixed for some elements 

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#19972]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Open Publish tab on SQL DB Proj.
2. Observe Advanced button text and when click on it observe the table header text.
3. Some option's descriptions are in english

Does this issue occur when all extensions are disabled?: Yes/No

Latest SQL DB code, when language set to Spanish, found the below text shows in non-spanish, which needs to take a look at.
1. ![image](https://user-images.githubusercontent.com/74571829/178082046-b82287c0-edaf-40ed-b8cf-3df9099b1892.png)
2. ![image](https://user-images.githubusercontent.com/74571829/178082074-83ce9d34-c2ad-4da9-8eca-c9e8b585e7c5.png)
3. ![image](https://user-images.githubusercontent.com/74571829/178082097-741a936e-04ac-4df0-8824-086f92ab960c.png)
4. ![image](https://user-images.githubusercontent.com/74571829/178082130-ab2643a4-7a2c-4dee-8832-0b67e5a5b1e5.png)
5. ![image](https://user-images.githubusercontent.com/74571829/178082238-e4fb441b-c7ff-49d6-ac17-0320fd04c6a9.png)
6. ![image](https://user-images.githubusercontent.com/74571829/178082325-b7aec244-a594-4585-a880-c624df81dae7.png)
7. ![image](https://user-images.githubusercontent.com/74571829/178082360-5742afd6-f88e-42c2-bc2f-20d9053c6210.png)

**Comment by kisantia** [comment]
as discussed in standup, this localization is probably from DacFx and those strings haven't been localized yet in the DacFx repo. @ssreerama you can check the sql-database-projects .xlf files in ADS to confirm if the other other description strings that are localized are present there to verify if they come from DacFx.

**Comment by ssreerama** [comment]
I see all the non localized strings are recently updated DacFx string! Do you know when can we expect the new DacFx Localized strings? Is it a regular process before the release or need to log a request! thanks

**Comment by kisantia** [comment]
If you look at the history of DacFx commits, all the LEGO checkins are localization and these PRs get sent periodically, without us needing to request it. If it's urgent, there's probably a way to request it.

**Comment by ssreerama** [comment]
@kisantia , I see there is already a LEGO checkin happened in DacFx offical branch. We need to use that Nuget version in STS right!

**Comment by kisantia** [comment]
closing since loc updates will come from DacFx
