### ISSUE TITLE
Unable to authenticate against GitHub (Version not high enough)

### ISSUE THREAD

**Issue by extrobe** [microsoft/azuredatastudio#19979]
- Azure Data Studio Version: `1.37.0` & `1.38.0-insider`
- OS Version: MacOS 12.3

Steps to Reproduce:

1. Open a GitHub repo folder for the first time (Clean install)
2. Change a file
3. Attempt to commit file
4. You'll be prompted to authenticate against GitHub

<img width="263" alt="image" src="https://user-images.githubusercontent.com/25456852/178134907-4a0c4b17-3d75-4dee-94df-d9306ad2b8d8.png">

5. After selecting Allow you'll be taken to GitHub which fails with the following error

<img width="1503" alt="image" src="https://user-images.githubusercontent.com/25456852/178134937-b1904407-7f40-4ed7-afa8-94f6baf87344.png">

Note: This was all on a clean install on a new machine - my existing laptop, also on 1.37.0 and was already authenticated, remains authenticated fine. Further, a clean VS Code install on v1.69.0 authenticates fine

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
How did you originally clone this repo? I'm unable to repro this issue if I clone the repo separately and then make changes as you said. I did see the issue though when trying to clone a new repo within ADS and selecting `Clone from Github`.

We'll be working on a fix, but for now are you able to work around the issue by cloning the repo from the command line and then opening the folder in ADS from there and pushing/pulling as normal?

**Comment by extrobe** [comment]
I cloned it via GitHub desktop rather than CLI

My workaround for now has been to just use Github desktop or VS Code to make my commits, but I'll also trying doing a clone via CLI to see if that solves it.

**Comment by ALZDBA** [comment]
Is my understanding correct that ADS includes its own copy of VSCode ?
Why isn't it just using the VSCode installed by the client ? ( and only installs it when needed )

**Comment by Charles-Gagnon** [comment]
ADS is actually a modified fork of VS Code. So we share a lot of the same code but there are some differences, and we lag behind a bit with getting the latest updates from them (which is why you're seeing this error)

**Comment by kisantia** [comment]
closing since the lates update on this thread is that this is working
