### ISSUE TITLE
Create view with extended properties "incorrect syntax" caused by position of GO without line break

### ISSUE THREAD

**Issue by ALZDBA** [microsoft/azuredatastudio#19982]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.Reverse engineer a database that has views with extended properties
2.Reverse engineer again and "apply" the changes with the local repository
-----
example script
CREATE VIEW [kw].[v_SignaalLog_CRM3]
AS
SELECT     guid, ts_registratie_GMT, d331, d332, d333, d354, 
                      d355
FROM         kw.t_SignaalLog_CRM3GO      **<-- here is the buggy part**
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPaneCount', @value = 1, @level0type = N'SCHEMA', @level0name = N'kw', @level1type = N'VIEW', @level1name = N'v_SignaalLog_CRM3';

GO
EXECUTE sp_addextendedproperty @name = N'MS_DiagramPane1', @value = N'[0E232FF0-B466-11cf-A24F-00AA00A3EFFF, 1.00]
Begin DesignProperties = ...

Does this issue occur when all extensions are disabled?: Yes/No I don't know

**Comment by Charles-Gagnon** [comment]
@kisantia @Benjin This seems like it might be a DacFX bug

**Comment by kisantia** [comment]
@ALZDBA can you please provide:
- scripts for a sample source and target project to repro
- what the folder structure of the project is (ex: schema/object type, object type, schema, flat, file)

**Comment by ALZDBA** [comment]
This db project has been reverse engineered from an old db to ADS [schema/object type] using ADS.
[View1.sql.txt](https://github.com/microsoft/azuredatastudio/files/9091507/View1.sql.txt)

**Comment by kisantia** [comment]
@ALZDBA can you help clarify the steps a bit more? What changed in the database between when the project was created and later updated?

This is what I tried, but was unable to repro the GO being added without a line break:
1. Created a new db on SQL Server 2019
2. Created a basic dbo.Table1:
```
CREATE TABLE [dbo].[Table1]
(
  [Id] INT NOT NULL PRIMARY KEY
)

```
3. Ran the provided script (after moving the GO to the next line so it would run) to create View1 and the extended properties.
4. Created a sql project from the database using the "Create Project from Database" dialog in ADS.
5. Changed the script for View1 to have a difference so it was now: 
```
CREATE VIEW [dbo].[View1]
AS
SELECT        dbo.Table1.Id
FROM            dbo.Table1
GO
```
6. Used the "Update Project from Database" dialog to update the project from the original db. The script for View1 went back to what it was originally before the change in step 5 and the GO was on the correct line.

**Comment by ALZDBA** [comment]
Actually, I just reverse engineered that database and had it compare it
again.
If I create a new database and perform the creates myself, It works
correctly.
So I suppose it may be an issue with older versions of SSMS that may cause
the problem.

However, preparing version control and devops integration, this reverse
engineering project will need way more attention and time as previously
hoped for

**Comment by kisantia** [comment]
@ALZDBA can you try again with the latest ADS release (1.38.0)? I made a fix for GO being on the same line in some cases, which looks related to this bug, if not the same: https://github.com/microsoft/azuredatastudio/issues/20143

**Comment by ALZDBA** [comment]
Now it is OK
The GO statement is on a line of its own.

CREATE TABLE [dbo].[Table2] (
    [Tb2Col1] INT          NOT NULL,
    [Tb2Col2] VARCHAR (50) NULL
);


GO

EXECUTE sp_addextendedproperty @name = N'MS_Description', @value = N'This is the description for this column', @level0type = N'SCHEMA', @level0name = N'dbo', @level1type = N'TABLE', @level1name = N'Table2', @level2type = N'COLUMN', @level2name = N'Tb2Col2';


GO
