### ISSUE TITLE
Connection Advanced Properties Not Rendering

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#20002]
Likely related to merge, this is what I see on my machine:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/40371649/178391901-8c606f32-b20a-4fc0-827a-20d0771831de.png">

Unfortunately, nothing in the dev console 😞

**Comment by chlafreniere** [comment]
This isn't a 100% repro for me. Curious what other folks see.

**Comment by kburtram** [comment]
Closing since we haven't seen a repro of this.
