### ISSUE TITLE
Insight widgets not displaying correctly on dashboard

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20014]
- Azure Data Studio Version: `insider`
- OS Version: All

Steps to Reproduce:

1. Connect to a non-Azure server and open Manage dashboard

Expected: Widgets render correctly

Actual: Widgets don't render.

![image](https://user-images.githubusercontent.com/599935/178557028-f68a46ce-f440-48b5-8386-12fc0e05316d.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
FYI @kburtram I'm also seeing this now after I cleared the previous settings I had and made some new connections. I'll try to dig into it to see if I can figure out what's going on

**Comment by Charles-Gagnon** [comment]
Fixed with https://github.com/microsoft/azuredatastudio/pull/20037
