### ISSUE TITLE
Database Projects - Do Not Expand Projects Treeview

### ISSUE THREAD

**Issue by ALZDBA** [microsoft/azuredatastudio#20032]
Issue Type: <b>Feature Request</b>

- In AzureDataStudio how do you **prevent all DatabaseProjects folder structures being opened** at DBExtension activate time?
**ToLongAList**
It might be interesting if you could specify e.g. **OpenTreeView=false** in the _settings.json_, so it would only show a first level of folders in the map.

With hundereds of SQLServer instances to support, this list is way to long to be managed by scrolling. 
- A **Filter** feature would also be nice.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<!-- generated by issue reporter --
![2022-07-14 08_29_19-Welcome - MijnDbProject - Azure Data Studio](https://user-images.githubusercontent.com/4035114/178915652-d8d57d75-6dfe-42f9-91bd-2a81c7a825ad.jpg)
vs
![2022-07-14 08_29_34-Welcome - MijnDbProject - Azure Data Studio](https://user-images.githubusercontent.com/4035114/178915702-4c67ae82-3e75-42e9-8666-4e669934c735.jpg)

>

**Comment by Charles-Gagnon** [comment]
For your second ask - if you click in the view area and start typing you can search/filter the nodes 

![image](https://user-images.githubusercontent.com/28519865/179046759-19cef130-8666-4bc8-9ee7-091e7655359f.png)

(click the filter icon in the widget to switch between search and filter view)

Is that what you want? Or are you talking about filtering the servers list? (which currently isn't supported)

**Comment by kisantia** [comment]
@ALZDBA just to confirm, the request is for the project nodes to be collapsed like this when the sql database projects extension is activated, right?
![image](https://user-images.githubusercontent.com/31145923/179085251-12fd663e-415d-407e-8f1f-77c161cabca6.png)
