### ISSUE TITLE
Notebook Kernels list does not update after .Net Interactive Ext install

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#20041]
ADS Dev Version: 1.38.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z (4 yrs ago)
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.5.0

Steps to Reproduce:

1. Uninstall the .Net Interactive Extension and reload ADS.
2. Open a new notebook (check to see that the .Net Interactive kernel is not in the list)
3. Install the .Net Interactive Extension & wait for it to complete

**Issue**:
See the currently opened notebook kernel list not updating to show the `.Net Interactive` kernel.
**Expected**:
The user should have the .Net Interactive kernel in the kernel list 

Potential solutions:
1. Show a reload notebook notification once .Net Interactive extension is installed. 
2. Reload ADS once .Net interactive is installed to update all notebooks open in order to show all available kernels.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by chlafreniere** [comment]
@corivera is this something that we could address soon, or should this go to backlog for further triage?

**Comment by corivera** [comment]
It might just be a kernel dropdown thing. I'll take a look

**Comment by chlafreniere** [comment]
Sounds good, thanks @corivera
