### ISSUE TITLE
Smoke tests fail with `no such file or directory`

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20078]
Occasionally the smoke tests will fail with an error similar to this 

```
Caught exception from ncp: Error: ENOENT: no such file or directory, lstat '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/vscsmoke/d/logs'

  41 passing (12m)
  2 pending
  1 failing

  1) Query Editor
       "before all" hook for "can open, connect and execute file":
     Error: connect ENOENT /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmp-51519I272z84PzAtw
      at PipeConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)
```

It doesn't seem directly related to the specific test (the logs folder is created for each test) though.

**Comment by aasimkhan30** [comment]
This seems similar to the bug https://github.com/microsoft/vscode/issues/112543

**Comment by aasimkhan30** [comment]
Here is why they vscode team had decided to close it https://github.com/microsoft/vscode/issues/137731

**Comment by Charles-Gagnon** [comment]
I'm going to close this for now then - if we start seeing failures again after the driver update we can reopen and investigate.
