### ISSUE TITLE
Text cells are created in split view mode when setting defaultTextEditMode setting to markdown

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#20093]
Repro steps:
1. In the user settings, set notebook.defaultTextEditMode to "Markdown"
2. Create a new text cell
3. That cell will be opened in split view mode, but the markdown view tab is selected.

**Comment by Charles-Gagnon** [comment]
Can repro in 1.37.0

![image](https://user-images.githubusercontent.com/28519865/179850930-cdae5c4e-0d0c-41ee-8a14-6254860b25b4.png)
