### ISSUE TITLE
Enable Radio Buttons' defaultValue to be type ResourceTypeOptionValue

### ISSUE THREAD

**Issue by candiceye** [microsoft/azuredatastudio#20094]
**Is your feature request related to a problem? Please describe.**
DefaultValue can only be a string right now. This causes a default value to not be selected when a radio button's option type is a ResourceTypeOptionValue (looks like: { name, displayName }. 

**Describe the solution or feature you'd like**
I made defaultValue of type string | ResourceTypeOptionValue.

**Describe alternatives you've considered**
None

**Additional context**
![image](https://user-images.githubusercontent.com/22386690/179851057-d7b7b73d-a7d1-4464-bd30-062e6720c576.png)

**Relevant PRs**
https://github.com/microsoft/azuredatastudio/pull/20070
https://github.com/microsoft/azuredatastudio/pull/20088

**Comment by Charles-Gagnon** [comment]
Turns out this isn't needed, there were some other issues that made this seem like a bug.
