### ISSUE TITLE
Markdown cell toolbar shortcuts don't work just after creating new split view cell

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#20092]
Repro steps:
1. In the user settings, set the defaultTextEditMode setting to "Split View".
2. Create a new text cell and add some text.
3. Select that text and try to bold it with Ctrl+B.
4. A notification will pop up in the lower right saying "Command 'bold' not found" and the selected text will not be bolded.

Toolbar buttons also don't work in the same repro scenario.

Note that exiting and re-entering the cell, or changing the cell view, no longer causes the issue to repro.

**Comment by Charles-Gagnon** [comment]
Can repro in 1.37
