### ISSUE TITLE
Additional color themes

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#201]
It would be nice to include a feature to add color themes from Visual Studio code market place.

**Comment by Code-DJ** [comment]
Just in case someone doesn't know, a workaround is to copy the theme folder from the VSCode extensions folder to SQLOps extensions folder. You can then change the theme in the User Settings file exactly like VSCode.

The only thing (I have found) that SQLOps doesn't do is custom titlebar.

On macOS, the VSCode extensions are stored in ~/.vscode/extensions. Copy the ones you want to ~/.sqlops/extensions.

**Comment by issacekbote** [comment]
Thanks Code-DJ. It worked. I am enjoying sqlops studio with my favorite Cobalt2 theme.

**Comment by kburtram** [comment]
Please open a PR to add any additional themes you'd like to see in the marketplace.  Or use the workaround mentioned above to install from VS Code marketplace.  We're still in the process of determine how best to integrate with VS Code extension marketplace in general.
