### ISSUE TITLE
Width of database drop down

### ISSUE THREAD

**Issue by paweston70** [microsoft/azuredatastudio#20106]
Issue Type: <b>Bug</b>

I realise this is a tiny thing, in the grand scheme of things, but would it be possible to make the database drop-down list either dynamic, based on the width of the current database or database list of names, OR make it a much wider fixed width (or a configurable fixed width)?

![image](https://user-images.githubusercontent.com/37217207/179961004-0437adce-905e-4f4a-9309-d7770fa74bc7.png)

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (16.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.48.0
cms|Mic|0.8.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.14.1
sql-database-projects|Mic|0.17.2
azdata-sanddance|msr|3.3.0

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@paweston70 if the current database name is truncated you can also find it in other places: 
![image](https://user-images.githubusercontent.com/13777222/180879908-1afce239-c3c9-44cf-b853-8fc01c3509ce.png)

At this point, we don't see a need to introduce a setting or dynamically change the width of it. but we can definitely revisit if this becomes a major complaint.
