### ISSUE TITLE
Attempting to Reopen Closed Notebook or SQL File has No Effect

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#20103]
- Open notebook (or .sql file)
- Close file
- Press ctrl/cmd+shift+t (or try to navigate via File->Open Recent->Reopen Closed Editor)

Expected: last file reopens
Actual: nothing happens

Note: with .md file, this functionality works as expected. Possibly something to do with how we register our custom editors?

**Comment by alanrenmsft** [comment]
the issue also exists in the previous stable release.

**Comment by chlafreniere** [comment]
@alanrenmsft yes agreed. If it doesn't meet the bar for July, can we move it to August?
