### ISSUE TITLE
Blank error when connection string connection fails

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20111]
1. Open connection dialog
2. Select `Connection String` connection type
1. Enter connection string that will fail (such as `server=skflds`)

A blank error appears instead of the actual error message 

![image](https://user-images.githubusercontent.com/28519865/180037781-54e289b8-33b5-4826-819d-21889f45ce1e.png)

**Comment by cheenamalhotra** [comment]
When you click on "Copy Details", you'd get "UserName cannot be null or empty when using SqlLogin authentication" in text copied.. issue seems to be in rendering the text on dialogbox.
