### ISSUE TITLE
SQLCMD in TSQL not working in ADS

### ISSUE THREAD

**Issue by DigitalDuquette** [microsoft/azuredatastudio#20119]
- Azure Data Studio Version: 1.37.0
- OS Version: Windows 10 Pro

Steps to Reproduce:

1. test.sql executes via sqlcmd in SSMS; however, an `Object reference not set to an instance of an object.` is thrown when running in ADS
![Screen Shot 2022-07-20 at 3 17 37 PM](https://user-images.githubusercontent.com/47231954/180064875-02311c78-3056-4437-8548-5c8d27f74549.png)
![Screen Shot 2022-07-20 at 3 18 07 PM](https://user-images.githubusercontent.com/47231954/180064878-b56e898b-1b77-42b1-b777-ec4cd2d09826.png)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/180276020-d73171db-9e04-4db3-bca2-7e9dbee5f69d.png)

@DigitalDuquette have you enabled SQLCMD in the query editor?

**Comment by DigitalDuquette** [comment]
@alanrenmsft 100% I am and obsessively have checked a few times. Here's a .gif example where it's enabled in SSMS _and_ ADS with SSMS working and ADS kicking the error: 

![Screen Recording 2022-07-21 at 1 34 29 PM](https://user-images.githubusercontent.com/47231954/180277629-ed4d9493-829e-4f19-bacc-6a1e4192733c.gif)

I've also tested on macOS and on another windows box with the same error.

**Comment by DigitalDuquette** [comment]
[20220721T135202.zip](https://github.com/microsoft/azuredatastudio/files/9161657/20220721T135202.zip)

Cleaned up log folder, then enabled debug mode, attached .zip.  I don't see anything in here but I dunno what I'm looking for either. 🤷‍♂️

**Comment by DigitalDuquette** [comment]
Also, here are the scripts I used for testing:
[sqlcmd.zip](https://github.com/microsoft/azuredatastudio/files/9161752/sqlcmd.zip)

**Comment by alanrenmsft** [comment]
@DigitalDuquette I've fixed the issue and it will be available in tomorrow's [Insider build](https://github.com/microsoft/azuredatastudio/issues/20008), please give it a try. Thanks

**Comment by alanrenmsft** [comment]
corrected the link in above comment.

**Comment by alanrenmsft** [comment]
@DigitalDuquette I've fixed the issue and it will be available in tomorrow's [Insider build](https://github.com/microsoft/azuredatastudio/#try-out-the-latest-insiders-build-from-main), please give it a try. Thanks

**Comment by DigitalDuquette** [comment]
@alanrenmsft working beautifully on the insider build, thanks!
