### ISSUE TITLE
Unable to open markdown files.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#20114]
Issue Type: <b>Bug</b>

Open any book that has a markdown readme file 
Try opening the markdown file.
Fails with the below error:
<img width="476" alt="image" src="https://user-images.githubusercontent.com/12754347/180047219-f85495f3-6494-489d-9668-30b434a26f72.png">

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T19:53:12.357Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (1.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
kusto|Mic|0.5.4

</details>

**Comment by Charles-Gagnon** [comment]
Known issue, this has to do with running multiple versions of ADS at the same time (insiders/RC1/stable). Nothing we can realistically do about it - fix/workaround is just to close all other instances of ADS and then  open up the version you're testing with.

**Comment by chlafreniere** [comment]
Same as #18048. Closing as known issue with multiple instances open.
