### ISSUE TITLE
using file explorer dialog to open a file system folder crashes ops studio

### ISSUE THREAD

**Issue by ranasaria** [Microsoft/azuredatastudio#2011]
- SQL Operations Studio Version:
Version 0.32.1
Commit 9ca6200018fc206d67a47229f991901a8a453781
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. Fire up SQL Ops Studio
2. From the left navigation bar, select Explorer -> Open Folder
3. Browse your file system and select a folder to open and hit 'Select Folder'
4. This crashes Ops Studio.

This worked in the following version:

Version 0.31.4
Commit e026ab85a72c190cc4ccc834503aa9fe36dd6407
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by abist** [comment]
Hi  @ranasaria, I am not able to repro this issue. Also when you say Explorer -> Open Folder, did you mean File -> Open Folder? I'm not sure where you find the Open Folder option in Explorer.

**Comment by ranasaria** [comment]
Do you see this left navigation bar? The 3rd item from top is the explorer (short cut is Ctrl+Shift+E)
[cid:image001.png@01D42364.876D0E40]


-  Arvind.

________________________________

**Comment by abist** [comment]
@ranasaria Yes, I am aware of that. I am not aware of any "Open Folder" option that you talk about. A screenshot would be helpful.

**Comment by ranasaria** [comment]
It is the blue button on the bottom right of this picture.
[cid:image001.png@01D42366.700C07E0]


-  Arvind.

________________________________

**Comment by ranasaria** [comment]
It repro-es for Chris as well. However, I am not sure if this is a 100% reproducible. After failing a few times, it just worked for me.


-  Arvind.

________________________________
