### ISSUE TITLE
Wizard page custom buttons are not implemented

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2013]
Steps to Reproduce:
1. Create a wizard as an extension and set the `customButtons` property on a page

Actual behavior: The custom buttons do not show up
Expected behavior: The custom buttons show up

Custom buttons for pages were never implemented. As a workaround you can set custom buttons on the whole wizard and just display them when needed

**Comment by kburtram** [comment]
Closing out old issues.  Please reactive if this is impacting an extension under active development.
