### ISSUE TITLE
Agent extension causes connections to stop working

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20130]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Agent dashboard
2. Click on Notebooks view when there are no Notebook jobs

Expected: Text saying no notebook jobs

Actual: Spinner never stops and connections stop working.  I suspect the agent service is blocking the message dispatcher.

![image](https://user-images.githubusercontent.com/599935/180098654-a518c119-056c-4b26-84bc-ad1674f0ce3a.png)

**Comment by alanrenmsft** [comment]
fix has been merged to release branch. closing the issue
