### ISSUE TITLE
Adding 2022 container to deployment wizard

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#20141]
![image](https://user-images.githubusercontent.com/12227241/180326657-54c9bea6-ef25-4b09-aaed-0f4155d4aed7.png)

mcr.microsoft.com/mssql/server:2022-latest
for SQL Server 2022 (preview)

**Comment by alanrenmsft** [comment]
@dzsquared you read my mind, i was just about to ask when testing this feature.
