### ISSUE TITLE
CentOS7 unable to connect to database

### ISSUE THREAD

**Issue by justinw-SMC** [microsoft/azuredatastudio#20151]
- Azure Data Studio Version: 1.29.0 and later
- OS Version: CentOS 7
```
azuredatastudio -v
1.29.0
0f5cfdc2c8c2433028842e16dc5ac1a65da24292
x64

cat /etc/system-release
CentOS Linux release 7.9.2009 (Core)

uname -a
Linux localhost.localdomain 3.10.0-1160.66.1.el7.x86_64 #1 SMP Wed May 18 16:02:34 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

rpm -qa libXScrnSaver*
libXScrnSaver-1.2.2-6.1.el7.x86_64
```
Steps to Reproduce:

1. sudo yum install -y azuredatastudio-linux-1.29.0.rpm
2. ensure libXScrnSaver is installed
3. azuredatastudio --disable-extensions
4. Select "Add Connection" under CONNECTIONS
5. Enter anything and press Connect (doesn't have to be valid credentials, since error should pop up)
6. Notice connection will hang w/o error message (indefinitely?)

Does this issue occur when all extensions are disabled?: Yes

![azure_1_29_0_not_connecting](https://user-images.githubusercontent.com/91086628/180499300-804bfbda-8305-45d7-a206-511977c42989.png)

This is a follow-up to #20061 but cannot confirm if these issues are related

**Comment by justinw-SMC** [comment]
Expected behavior from 1.28.0

Should show at least an error message. I'm also able to make a connection to my company database using this version.

![image](https://user-images.githubusercontent.com/91086628/180500322-6d3c752f-b36c-40c3-8de6-f15c7a7f6c38.png)

**Comment by kburtram** [comment]
I'm going to consolidate this issue into https://github.com/microsoft/azuredatastudio/issues/20061 since they look similar.  We'll investigate both the UI freezes and the inability to connect in with CentOS 7 in that issue.  Thanks!
