### ISSUE TITLE
Azure SQL Migration extension 

### ISSUE THREAD

**Issue by ankushcngls** [microsoft/azuredatastudio#20160]
- Azure Data Studio Version:  1.37.0
- OS Version:Windows_NT x64 10.0.19044

Steps to Reproduce:

1.Click on Azure SQL Migration extension
2.Select a database migration service and get a below screenshot
3. Not able to view location and resource group.

![image](https://user-images.githubusercontent.com/109872570/180618687-cfc30799-a97d-437f-9cf5-a5d0f323f44d.png)

Note: Location,Resource group and Database Migration service is already created in azure subscription and same subscription is selected here also

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
@brian-harris @raymondtruong @rchlkm

**Comment by brian-harris** [comment]
this is by design:
the service selection dialog will only show the list of locations and resource groups that contain one or more services.  In this case it does not appear that the subscription has any migration services created under it yet.
