### ISSUE TITLE
Cannot create new Agent Job Step

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20171]
- Azure Data Studio Version: 1.37

Steps to Reproduce:

1. Create agent job
2. Add step to job
3. Fill out all required fields

Expected: Job step can be created.

Actual: OK button is disabled even when all required fields have been populated.

![image](https://user-images.githubusercontent.com/599935/181069537-41ef3510-eee6-4b42-8c37-f1f56020046a.png)

**Comment by tpeixinho** [comment]
I can confirm this is happening to me also:
Version: 1.39.0-insider
Commit: 4d1be1e2882e9bead453bed88c340930e5055701
Date: 2022-08-03T05:35:18.830Z (3 hrs ago)
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Darwin x64 21.6.0
