### ISSUE TITLE
XML Columns - Linearized

### ISSUE THREAD

**Issue by gfoley97** [microsoft/azuredatastudio#20191]
Issue Type: <b>Feature Request</b>

I would like an option to be able to click on an XML column in the SQL results view and have it open the XML in a new window "pretty printed" instead of linearized. 

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.18363
Restricted Mode: Yes

**Comment by alanrenmsft** [comment]
the feature you requested is already there, please see the gif below.
![format-xml](https://user-images.githubusercontent.com/13777222/183156427-4353dbe4-7787-4b8c-b73a-d9022ad21ce9.gif)

there is another issue with this feature: https://github.com/microsoft/azuredatastudio/issues/20176, I've submitted a fix for it.

**Comment by gfoley97** [comment]
Mine does not do this and I'm on the latest version. Is this a setting?

**Comment by alanrenmsft** [comment]
@gfoley97 no setting for this behavior. 

In the new document that contains the xml, if you press "SHIFT+ALT+F" (or run the `format document` in command palette (Menu: View->Command Palette...)), does it format the document correctly? 

also, what do you see if you type `@builtin xml` in the extensions view container's search box
![image](https://user-images.githubusercontent.com/13777222/183982823-ef36be69-eeeb-4eed-a79b-3b19a2fd3fe3.png)

**Comment by gfoley97** [comment]
Ahhh I found it finally. My workspace was not trusted. I trusted it and now
the xml is formatted

**Comment by alanrenmsft** [comment]
great! 🥇
