### ISSUE TITLE
Query History has no icon when moved to the Activity Bar

### ISSUE THREAD

**Issue by clcridgeview** [microsoft/azuredatastudio#20193]
When query history is dragged from the default location (bottom panel) over to the activity bar it doesn't show an icon.  

I generally keep the bottom panel closed, especially with results showing, that's a lot of screen lost.  So dragging it off to the activity bar puts in a visible space when I need it without having to open the bottom panel, restore the query, close bottom panel.  Feels more natural to me on the activity bar.

Thanks

![image](https://user-images.githubusercontent.com/13118662/181575314-cf387271-9e85-4445-bcb6-7826245aaf19.png)

**Comment by Charles-Gagnon** [comment]
@clcridgeview I just updated the Insiders gallery with a version of the extension that should fix this, try it out and let me know if you still see any issues! Thank you for the feedback!
