### ISSUE TITLE
save as, ctrl Z, removes all content

### ISSUE THREAD

**Issue by OzBob** [microsoft/azuredatastudio#20207]
Issue Type: <b>Bug</b>

open a saved document
type
1<enter>
2<enter>
3<enter>
press ctrlZ 3 times, as expected.
Now, SaveAs
press ctrlZ and the whole document dissappears

expected behaviour
press ctrl Z after saveas and the 1,2,3 dissapear.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (7.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
dacpac|Mic|1.10.1
schema-compare|Mic|1.15.0
sql-database-projects|Mic|0.18.0
sql-migration|Mic|1.0.4

</details>

**Comment by alanrenmsft** [comment]
This is an issue we inherited from vscode, I've created an issue in vscode repo:https://github.com/microsoft/vscode/issues/156697
