### ISSUE TITLE
Redo is limited to only one redo, while Undo is not limited.

### ISSUE THREAD

**Issue by pelsql** [microsoft/azuredatastudio#20226]
Issue Type: <b>Bug</b>

This is so unexpected, as VS-CODE and SSMS Redo aren't limited to only one Redo. For example, add three words to a text file, repeat undo three times, and then redo three times, and the text is back as it was before.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.86GB (13.67GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@pelsql I am unable to repro this issue.  If I open a new file and type 'one two three' and then undo three times, then redo three times the text 'one two three' is the final result in the file.  Did I miss something with the repro?

For what it's worth, ADS has not done any customizations to the undo/redo code from the VS Code implementation so the behaviors between the two tools should be the same.

**Comment by pelsql** [comment]
I tried to repro it again. It doesn’t work.  I think that the fact or restarting the program, cleared some incorrect state the program got into.
If I do something that triggers the bug, I will try to find out what just happened before

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
