### ISSUE TITLE
Saving a notebook as a dib file not working correctly

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#20230]
- Azure Data Studio Version: 1.38
- OS Version: mac

Steps to Reproduce:

1. Create new notebook
2. Add some code cells and text cells
3. Save notebook with dib extension

Expected:
![Screen Shot 2022-08-02 at 1 01 31 PM](https://user-images.githubusercontent.com/23462877/182462854-4d75ff08-7f18-42e9-88ef-af02434ce2bf.png)

Actual:
Notebook content gets saved as json in one code cell.
![Screen Shot 2022-08-02 at 12 34 07 PM](https://user-images.githubusercontent.com/23462877/182462871-5fe02f4e-7dd1-4c70-bff2-0b756b4fd4da.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by corivera** [comment]
@lucyzhang929 were you doing New Notebook and then saving it manually with a dib extension? If so, that's not supported. There's a separate Create New Notebook command in the command palette for creating Interactive dib notebooks.

**Comment by lucyzhang929** [comment]
Ah I see. Yes I was using New Notebook. Just tested the Interactive command palette command and that worked as expected. I'll close this issue, thanks @corivera!
