### ISSUE TITLE
How can I run/connect Azure Data Studio from existing virtual env in Anaconda?

### ISSUE THREAD

**Issue by lauraaawr** [microsoft/azuredatastudio#20239]
Azure Data Studio 1.38.0
OS: Windows Server 2019
Anaconda3 & Python 3.9

1. Configured the Python installation path to the main Anaconda folder (C:\Users\Administrator\Anaconda3) and the option of Anaconda package type appears in the Manage Packages panel, together with the list of all installed conda packages. 
![image](https://user-images.githubusercontent.com/85976879/182820954-9aaa2e62-fba4-4451-b1c0-968e2b3b8ad4.png)

2. I then created a virtual environment in Anaconda to isolate packages, especially to store packages from conda-forge repository. When I change the Python installation path to this venv folder (C:\Users\Administrator\Anaconda3\envs\CRA), only the pip packages are displayed. There is no option of 'Anaconda' package type, although I have successfully installed 25+ packages from conda-forge. 
![image](https://user-images.githubusercontent.com/85976879/182821300-e9363a39-01d7-4a37-8d89-b2dc454cd918.png)
![image](https://user-images.githubusercontent.com/85976879/182821419-a7d06b3d-863f-42ea-889e-fc40ff791982.png)
![image](https://user-images.githubusercontent.com/85976879/182821595-dd4fced7-49dc-4124-b714-fb0a959f7cb8.png)

Is this because there is no 'pkgs' folder inside the CRA directory? I realized that all the conda-forge packages are stored inside this 'pkgs' folder in the main directory instead. Should I copy this 'pkgs' folder to the CRA directory as well? Am I missing any steps in between or is there any workaround?

Would be great if I can access specific venv in Anaconda so as to isolate packages based on different project. I wouldn't want to mess with the base environment and there will be multiple users using the Azure Data Studio as well. Hope to hear from anyone who is familiar with ADS & Anaconda!

**Comment by chlafreniere** [comment]
@corivera can you provide guidance here

**Comment by corivera** [comment]
I remember there was a path detection bug when using virtual environments. Basically, the notebook thinks it's using pip because it can't find the conda executable, which is why there's no anaconda in the packages dropdown. Let me look around and see if that's the case here.

**Comment by corivera** [comment]
Yeah, there's no conda exe in the env folder, so we don't detect that it's conda when starting the notebook.

**Comment by corivera** [comment]
@lauraaawr Are you able to see the packages if you activate the conda environment manually from a terminal, launch ADS from that same terminal, and then select the root python folder in the Configure Python dialog?

**Comment by lauraaawr** [comment]
Hi @corivera nope, still not able to see the conda packages after launching ADS from the activated environment in Anaconda terminal. The only difference is ADS automatically detected the conda environment's python path in Configure Python dialog, but only pip packages appear in Manage Packages dropdown.

**Comment by corivera** [comment]
What path are you using in the Configure dialog?

**Comment by lauraaawr** [comment]
@corivera sorry for confusion, I mean this Python path: c:\Users\Administrator\anaconda3\envs\CRA (custom)

**Comment by corivera** [comment]
Are you able to see the expected environment packages if you use the path c:\Users\Administrator\anaconda3 in the dialog after activating the environment manually?

**Comment by lauraaawr** [comment]
@corivera 
- I activated the environment & launch ADS from there
![image](https://user-images.githubusercontent.com/85976879/185796409-5ad36375-b734-483e-aa7f-febacab97d1b.png)
- Choose the main Python path instead of the environment path
![image](https://user-images.githubusercontent.com/85976879/185796601-547f39a7-fc13-4ae5-8c23-7ffd9e07c4bb.png)
- Yeah, now I'm able to see the Anaconda drop-down & all the expected Anaconda packages correctly 
![image](https://user-images.githubusercontent.com/85976879/185796912-6d6e4d95-6597-4f55-9015-47abd74d724d.png)
- However, it shows all the 352 pip packages within the base environment instead of the expected 120+ pip packages in the activated CRA_all env
![image](https://user-images.githubusercontent.com/85976879/185797354-d3140698-9004-4feb-8d77-f7970c17655a.png)

Any possible way to show both the isolated pip & Anaconda packages in the specific env we activated?

**Comment by corivera** [comment]
I'll be opening a fix later today to use the env's python executable

**Comment by lauraaawr** [comment]
Thanks @corivera for the fix! Sorry but I'm new to Github, what is the next step I need to do?

Do I need to redownload the ADS installer as I installed it in a computer without internet?

**Comment by corivera** [comment]
That fix won't be available in our stable builds for another 2 months. You can use the nightly builds if you want, called the Insiders version, but that version is not guaranteed to be 100% stable since it's built daily from whatever is in the main branch. You can find the insiders version here: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
