### ISSUE TITLE
error select top 1000 with Synapse Dedicated Pools

### ISSUE THREAD

**Issue by christianleivam** [microsoft/azuredatastudio#20241]
Issue Type: <b>Bug</b>

in versión 1.38 sql, the select 1000 did not work. I had to install the previous version

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.2.1
schema-compare|Mic|1.15.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@christianleivam please include more details so that it is actionable for us, and a screenshot would help.

**Comment by sturginho** [comment]
I am getting the same error as martinleo above:

ERR Scripting failed. error: An error occurred while scripting the objects. Failed to retrieve data for this request.

It only affects Azure SQL Pool (SQL DW) and not Azure SQL DB

**Comment by hdrenollet-csusa** [comment]
Yes, this matches the error that I'm receiving as well for Azure Synapse Analytics Dedicated SQL Pools

**Comment by hdrenollet-csusa** [comment]
October?  Really?!  I really want to use Azure Data Studio daily, but bugs like this keep me switching back to SQL Server Management Studio.  Maybe I'll just give up hope and try it again in a couple years once you guys get all the basics figured out.  In its current state, it's not a reliable alternative to SSMS.

**Comment by alanrenmsft** [comment]
the fix will be the Nov stable release. If you are using Insiders build, Oct 17th's Insider build should have it.
