### ISSUE TITLE
New Query opens editor with an old query

### ISSUE THREAD

**Issue by hcc-donder** [microsoft/azuredatastudio#20247]
Issue Type: <b>Bug</b>

Action: Selected New Query from the file men

Expectation: I expected to have a new tab opened with a blank editor.

Actual: Creating a new query from the file menu will frequently create a new tab with an old query in the editor box. Seems to be a former query that I closed. This does not always occur, but occurs most of the time.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.60GB (43.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
machine-learning|Mic|0.11.0
profiler|Mic|0.11.0
query-history|Mic|0.2.1
schema-compare|Mic|1.15.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.3
sql-database-projects|Mic|0.18.0
azdata-sanddance|msr|3.3.0
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by smartguest** [comment]
Fixed by a recent update made to ADS
