### ISSUE TITLE
SDK 'Microsoft.Build.Sql/0.1.3-preview' specified could not be found

### ISSUE THREAD

**Issue by PowerDBAKlaas** [microsoft/azuredatastudio#20240]
Issue Type: <b>Bug</b>

1. open a sql database project
1. in 'database projects', right-click projectname and choose 'Build'

=> OUTPUT
```
	[ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\m.yusername\\OneDrive - mycompany\\DBProjects\\DatabaseProjectTESTDB\\DatabaseProjectTESTDB.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\m.yusername\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.18.0\\BuildDirectory"
    stdout: Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout: c:\Users\m.yusername\OneDrive - mycompany\DBProjects\DatabaseProjectTESTDB\DatabaseProjectTESTDB.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.3-preview)' for '.NETStandard,Version=v0.0'.
    stdout: 
    stdout: c:\Users\m.yusername\OneDrive - mycompany\DBProjects\DatabaseProjectTESTDB\DatabaseProjectTESTDB.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.3-preview' specified could not be found.
    stdout: 
    stdout: 
    stdout: Build FAILED.
    stdout: 
    stdout: 
    stdout: c:\Users\m.yusername\OneDrive - mycompany\DBProjects\DatabaseProjectTESTDB\DatabaseProjectTESTDB.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.3-preview)' for '.NETStandard,Version=v0.0'.
    stdout: c:\Users\m.yusername\OneDrive - mycompany\DBProjects\DatabaseProjectTESTDB\DatabaseProjectTESTDB.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.3-preview' specified could not be found.
    stdout:     0 Warning(s)
    stdout:     2 Error(s)
    stdout: 
    stdout: 
    stdout: Time Elapsed 00:00:00.48
    stdout: 
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\m.yusername\\OneDrive - mycompany\\DBProjects\\DatabaseProjectTESTDB\\DatabaseProjectTESTDB.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\m.yusername\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.18.0\\BuildDirectory"    … exited with code: 1
	>>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\m.yusername\\OneDrive - mycompany\\DBProjects\\DatabaseProjectTESTDB\\DatabaseProjectTESTDB.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\m.yusername\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.18.0\\BuildDirectory"   … errored out: Process exited with code 1
```

Extension version: 0.18.0
Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (8.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@PowerDBAKlaas Did building this project used to work and recently start failing? Can you please share the sqlproj for this project?

**Comment by DaveSkender** [comment]
Same happens to me.  Builds fine in full Visual Studio Community edition IDE.  I have both VS 2022 and VS 2022 Preview installed, which I suspect is the root of the problem … kind of the risk one takes with previews. :neckbeard:

**Comment by PowerDBAKlaas** [comment]
@kisantia it is the first time I try to build a proj, so I have no idea since when this problem exists
I can share the proj later (on holiday now) but it is nothing complicated; 
I created a new testDB with just 1 table with 4 columns

**Comment by PowerDBAKlaas** [comment]
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>DBA_DB</Name>
    <ProjectGuid>{8FF4226E-F67B-4C5E-BBA1-176896CD6165}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.Sql150DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
</Project>
```

**Comment by kisantia** [comment]
@zijchen have you seen this error before or have any ideas on why Microsoft.Build.Sql can't be found? Maybe nuget.org needs to be added as a source or something like that?

**Comment by zijchen** [comment]
nuget.org should be included by default. @PowerDBAKlaas do you have any additional Nuget sources configured? You can run `dotnet nuget list source` to check.

**Comment by PowerDBAKlaas** [comment]
@zijchen 
"No sources found."

**Comment by kisantia** [comment]
nuget.org should be listed like this: 
![image](https://user-images.githubusercontent.com/31145923/186714976-7f003f37-9cbd-465a-b33a-b7a2b34deaf9.png)

Can you try adding nuget.org as a source like in the first example [here](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-nuget-add-source#examples)?

**Comment by PowerDBAKlaas** [comment]
`dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org`

fixed everything!

Thank you @kisantia !!!


should that have been executed when adding the extension? or any reason this could have been removed from my system(s)?
maybe useful to add this on the 'dependencies' tab?

**Comment by kisantia** [comment]
nuget.org should be included by default, as Zi mentioned. Have you used chocolatey or PowerShell’s `Install-Package` command at some point before building this project? It might be the same problem described here: https://developercommunity.visualstudio.com/t/missing-default-nuget-package-source/1453751

**Comment by PowerDBAKlaas** [comment]
I have used choco and winget and MS Store to install packages, but can't remember in what order or time frame.

Can you clarify with what nuget.org should be default installed? Is that with Windows setup, Azure Data Studio install, .Net SDK, .... ?
