### ISSUE TITLE
Missing Index definition repeats columns

### ISSUE THREAD

**Issue by jjturner** [microsoft/azuredatastudio#20249]
Issue Type: <b>Bug</b>

1) enable Actual Plan
2) create a query with:
    a.  predicates against various columns
    b.  sufficiently complex
    c.  lacking covering index(es)
3) run query

When Missing Index recommendation is returned in the plan, its definition will list the needed columns in the main column list and repeat them in the INCLUDE list.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by MisinformedDNA** [comment]
I had one query where the column was in the list of index columns and then in the include list **twice**.

```sql
CREATE NONCLUSTERED INDEX [<Name of Missing Index, sysname,>]
ON [dbo].[t_Order] ([OrderTypeID],[ActionEvent])
INCLUDE ([OrderTypeID],[ActionEvent],[ActionExtra])
```

**Comment by erinstellato-ms** [comment]
@jjturner @MisinformedDNA Hey there - can either of you provide a repro script that we can quickly test/verify with here?  It's possible this is behavior in the engine, not an issue with how we're reading the XML of the plan, but an example would help us confirm.  Thanks!

**Comment by MisinformedDNA** [comment]
What kind of script? Like the whole DB?

**Comment by jjturner** [comment]
@erinstellato-ms - first off, it's an honor to have your assistance on this - thanks for all your SQL contributions over the years!

As for the test case, I'm afraid I don't have a readily available AdventureWorks I can leverage for this.  BUT, this appears to be very simple to reproduce.  Running a query against a single sizable table with clustered index using the following air-code template:

`SELECT TOP 100 t.pk_id, t.some_other_col FROM SampleTable AS t WHERE t.missing_nc_idx_col = 'foo'`

And to prove I could reproduce this as per above SQL query template:
![image](https://user-images.githubusercontent.com/16421109/194427933-8214fc37-0290-4720-b65e-4a28f69e3cc2.png)

Kindly advise if this is sufficient to diagnose from your side.

Thanks,
John

**Comment by erinstellato-ms** [comment]
@jjturner Thanks for the feedback and for the example!  Unfortunately, I'm still not able to recreate it.  I'm using ADS 1.39 against SQL Server 2019.  What version of SQL are you running (and if Azure SQL DB or MI, please let me know).

SELECT TOP 100 
   o.orderid, o.backorderOrderid
FROM Sales.Orders AS o 
WHERE o.orderdate = '20180101'

![image](https://user-images.githubusercontent.com/98599126/195436760-0a96829b-04ed-4f4d-99f3-3d2eb6435c4d.png)

**Comment by jjturner** [comment]
Hmm... it's looking like SQL version may be the issue - can confirm I'm still getting the duplication on my side:

- Microsoft SQL Server 2016 (SP3-CU1-GDR) (KB5015371) - 13.0.7016.1 (X64)       May 21 2022 01:00:03    Copyright (c) Microsoft Corporation       Enterprise Edition: Core-based Licensing (64-bit) on Windows Server 2016 Datacenter 10.0 <X64> (Build 14393: ) (Hypervisor) 
- ADS 1.39.1

**Comment by erinstellato-ms** [comment]
@jjturner I can create the behavior in SQL 2016, but not in SQL 2019.  So, it's a bug in the engine/optimizer that was fixed in a later release, and not an ADS bug.  Hope this helps, let us know if you need anything else.

**Comment by jjturner** [comment]
Gave myself a sanity check by running SSMS with same query against same SQL instance/db:

SSMS:
![image](https://user-images.githubusercontent.com/16421109/195448864-cbbfdd20-ac62-4bc6-bfd3-ad07e118746d.png)

ADS:
![image](https://user-images.githubusercontent.com/16421109/195448946-68401744-0e3e-4b29-a94d-ce7c027b4318.png)

So now I'm confused!  How can the engine/optimizer render properly in one client app and improperly in another?

ps - just want to mention I love ADS / (VS Code) and use SSMS as infrequently as possible these days - ADS has been a game-changer -- hats off to all the crew working on making ADS a great dev platform!

**Comment by erinstellato-ms** [comment]
Ahhh, I see where I made a mistake. You are correct, and thank you for the continued testing!  I will re-open and we'll see if we can get it addressed before the next release.

And thank you for the feedback!  If you are interested in being part of a focus group I'm trying to put together, please feel free to email me.  It's erinstellato at microsoft dot com.  Thanks again :)

**Comment by erinstellato-ms** [comment]
Steps to recreate:
1. Connect to the sqltools server for 2016.
2. Open a new query window for the keep_MDW database.
3. Enable the actual execution plan and run the query below:

SELECT performance_counter_instance_id, snapshot_id, collection_time, formatted_value
from snapshots.performance_counter_values
WHERE raw_value_first = 23498

You will see this for 2016:
![image](https://user-images.githubusercontent.com/98599126/195457176-53ca9336-ec12-471c-aac9-ef27ab1f6ff3.png)

4. This is not the correct recommended index.  Right-click to view the plan XML.  You should see:

							<MissingIndexGroup Impact="99.9849">
								<MissingIndex Database="[keep_MDW]" Schema="[snapshots]" Table="[performance_counter_values]">
									<ColumnGroup Usage="EQUALITY">
										<Column Name="[raw_value_first]" ColumnId="5">
										</Column>
									</ColumnGroup>
									<ColumnGroup Usage="INCLUDE">
										<Column Name="[performance_counter_instance_id]" ColumnId="1">
										</Column>
										<Column Name="[snapshot_id]" ColumnId="2">
										</Column>
										<Column Name="[collection_time]" ColumnId="3">
										</Column>
										<Column Name="[formatted_value]" ColumnId="4">
										</Column>
									</ColumnGroup>
								</MissingIndex>
							</MissingIndexGroup>

**Comment by erinstellato-ms** [comment]
@aasimkhan30 @lewis-sanchez checking to see if we can take this for the release...we need to make sure we're generating the missing index recommendation T-SQL correctly.  Thanks!

**Comment by lewis-sanchez** [comment]
@erinstellato-ms, I think Aasim will need to take that one. I'm going to be OOF for 2 weeks starting next Monday.

**Comment by AronHetLam** [comment]
This is still an issue in version 1.44.0 (31bee67)
Was about to report it, but found this and two other issues for it (#20676 and #19273).
I Don't have any additional information. But the inconsistency you mention in https://github.com/microsoft/azuredatastudio/issues/20249#issuecomment-1276787431 @erinstellato-ms not only applies to the xml, but also to the properties window for the root node of an execution plan - which is probably build from the xml.

![image](https://github.com/microsoft/azuredatastudio/assets/5564813/a2587f5f-ef63-461d-8871-6f4568273b38)

**Comment by erinstellato-ms** [comment]
Duplicate issues opened (and closed) for this same issue (listing for history):
https://github.com/microsoft/azuredatastudio/issues/19273
https://github.com/microsoft/azuredatastudio/issues/24121
https://github.com/microsoft/azuredatastudio/issues/20676
https://github.com/microsoft/azuredatastudio/issues/24042

**Comment by lewis-sanchez** [comment]
Reopening since I haven't updated the SQL Tools Service version in Azure Data Studio.
