### ISSUE TITLE
blank results from query

### ISSUE THREAD

**Issue by sgomolka** [microsoft/azuredatastudio#20245]
Issue Type: <b>Bug</b>

query will return blank results, sometimes querys hang. this is after the latest update that just occured around august 1st 2022

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.67GB (8.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@sgomolka can you please provide additional details on how to repro this issue?  Do the queries you are executing have any particular characteristics (e.g. large BLOB columns, XML, JSON, etc.).  Is the CPU load particularly high/app not responding?  Any errors in the Help->Developer Tools->Console?  Thanks!

**Comment by cheenamalhotra** [comment]
Closing as not enough info available to investigate the issue.
Please re-open the issue if you have requested info available.
