### ISSUE TITLE
Issue when deleting and recreating Temporal Table

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20255]
- Azure Data Studio Version: 1.38
- OS Version: Windows Enterprise

Steps to Reproduce:

1. Create Temporal Table 
2. Delete Temporal Table and Refresh on OE
3. Recreate Temporal Table with same parameters as in Step 1, but change the Table name 

Expected Result:

User should be able to recreate Temporal Table

Actual Result 

System is not responding to deletion. See below. 

Old/Deleted Table Name was - dbo.temptable
New Table Name was - dbo.tabletemp 

System is still referencing old table name even though this table was deleted (script as drop) and OE was refreshed 

![image](https://user-images.githubusercontent.com/72947001/183150983-b2b2dbcf-e497-464b-8c1a-121eb3fb0192.png)

![image](https://user-images.githubusercontent.com/72947001/183150785-00285845-053f-4d61-9e8e-ff2b5833e759.png)

Does this issue occur when all extensions are disabled?: Yes/No Yes

@alanrenmsft

**Comment by caohai** [comment]
I'm not able to repro this on my machine with latest release/
For step2, by deleting you mean running the script from `Script as Drop`, right?
For step3, are you using `Add New` and doing all the same steps as in 1 for designing then publish?
If so I'm doing the same.

**Comment by caohai** [comment]
@tdoshin kindly ping

**Comment by tdoshin** [comment]
Apologies for the late reply. @caohai .I am also unable to repro. We can close for now.
