### ISSUE TITLE
If System-Versioning is set to "ON", user must be disallowed from dropping the History Table per sql server docs

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20258]
- Azure Data Studio Version: 1.38
- OS Version: Windows Enterprise

Steps to Reproduce:

1. Create Temporal Table
2. Set System-Versioning to "ON"
3. History Table is checked to be created by default, no need to do anything here
4. Delete History Table

Expected Result: 

User should be disallowed to delete history table when System-Versioning is set to "ON

Actual Result:

User is allowed to delete history table when System-Versioning is set to "ON

@alanrenmsft @kburtram 

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
@tdoshin did you delete the history table using T-SQL? I don't believe we have UI support in table designer to delete the table. if so please ping the SQL Server PM team that owns this feature.
