### ISSUE TITLE
Ability to filter Logins (quick search similar to tables/store procedure) search

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#2025]
Issue Type: <b>Feature Request</b>

When you expand SQL Logins, you can't filter or search user id.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Charles-Gagnon** [comment]
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as cleanup
