### ISSUE TITLE
Ability to save Execution plan

### ISSUE THREAD

**Issue by richardmunn17** [microsoft/azuredatastudio#2027]
the XML execution plan can be extracted using scripts like:

DECLARE @procnamestub NVARCHAR(100) ; 
SET @procnamestub = 'myProcName' ; 

SELECT query_plan FROM sys.dm_exec_cached_plans a
CROSS APPLY sys.dm_exec_query_plan(plan_handle) b
CROSS APPLY sys.dm_exec_sql_text (plan_handle) c
WHERE c.text LIKE '%' + @procnamestub + '%' 
AND a.objtype = 'Proc';

..and clicking the XML opens up a graphical plan, but closing this table doesn't prompt to save it. Please can this be added ?

It is useful to have the execution plan to pass to dev teams. This feature is in SSMS, and right now is about the only reason I still use SSMS !

**Comment by aasimkhan30** [comment]
This feature is added to the new Execution plan feature. You can save the using the save icon the top right corner or right click and select the option from the context menu. 

![image](https://user-images.githubusercontent.com/6816294/163852655-5865d311-3062-4a6f-9e31-83612bfa5844.png)
![image](https://user-images.githubusercontent.com/6816294/163852745-106c5102-858b-4984-a009-88b3a8025a9d.png)
