### ISSUE TITLE
Network-related or instance-specific error occured while establishing a connection to  SQL server

### ISSUE THREAD

**Issue by 4ouR04** [microsoft/azuredatastudio#20278]
- Azure Data Studio Version:Studio 1.38.0
- OS Version: 5.15.0-kali3-amd64

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No No

**Comment by 4ouR04** [comment]
![Screenshot_2022-08-09_20_51_23](https://user-images.githubusercontent.com/86522089/183724761-debfa687-cfed-487d-9c25-0d5674620866.png)

**Comment by kburtram** [comment]
@4ouR04 this error message is coming from the SQL Client driver and is saying that it cannot find an MSSQL server instance running on localhost on port 1433.  Tools such as netstat can be used to confirm SQL Server is running and bound to this IP/port, e.g `netstat -na | egrep 1433`.  Are other tools able to connect to this IP/port successfully?
