### ISSUE TITLE
Azure SQL migration assistant extensions for Azure Government 

### ISSUE THREAD

**Issue by jcbrooks92** [microsoft/azuredatastudio#20275]
- Azure Data Studio Version:
Version: 1.38.0 (system setup)
Commit: dff93c4736269ef2a7e8a225737a0d8354bf0246
Date: 2022-07-26T23:56:16.217Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

- OS Version:
Windows 11

Steps to Reproduce:

1. Run through the SQL migration process
2. Select Settings -> Azure Account -> Azure Gov 
3. Walk through the wizard up to where the Azure SQL Target blade is selected.

It looks like the extensions is correctly find the subscriptions but after the subscriptions are found the endpoint queried for the Azure resources is management.azure.com instead of management.usgovcloudapi.net. See screenshot below with Fiddler trace.

Please ping me internally for questions (jebrook)

![image](https://user-images.githubusercontent.com/18233035/183696897-26091f94-93b8-4c0d-9109-0e54ad997616.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by raymondtruong** [comment]
Currently investigating

**Comment by raymondtruong** [comment]
This is fixed in the latest version of the SQL Migration extension (v1.1.3) alongside the latest version of ADS (1.40)
