### ISSUE TITLE
Feedback on the migration experience

### ISSUE THREAD

**Issue by vihardik** [microsoft/azuredatastudio#20297]
Issue Type: <b>Bug</b>

1. I have a SQL MI instance on Azure. 
2. I created a migration from SQL Server on my laptop to Azure SQL MI. It worked fine. 
3. Later I got my SQL MI instance added to some backend process - So I can start and stop the Azure SQL MI. I stopped my Azure SQL and later started the Azure SQL MI through PS Script. 
4. I can connect to the Azure SQL MI through Azure Data Factory and SSMS. 
5. Now when I try to run the migration (from SQL Server on my laptop to this Azure SQL MI), I get an error - The Managed instance is unavailable because it is currently in the Stopped state. This is very strange, since my Azure Data Studio is connected to my Azure SQL MI.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|44%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-migration|Mic|1.0.4

</details>

**Comment by raymondtruong** [comment]
This bug has been identified as a transient issue - ARM (what we use to query MI state) metadata is sometimes out of sync with the true MI state. This has been reported to the MI team and the extension is working as expected. Please retry and if this issue still persists, feel free to reopen the issue.

**Comment by vRune4** [comment]
I hit the same phenomena today. The managed instance was started seven hours ago, yet migration wizard reports it as 'stopped'.
