### ISSUE TITLE
Schema Compare - Object Name filtering

### ISSUE THREAD

**Issue by alexszasz** [microsoft/azuredatastudio#20308]
Working with databases with over 500 different objects is really cumbersome. Even more so, when it's part of a smaller project involving only a few objects. In the current version you need to manually deselect ALL objects except the very few ones you need.

I would like to have a way of pre-filtering the objects to be compared using a schema/name filter (similar to the SSMS option)
<img width="528" alt="image" src="https://user-images.githubusercontent.com/2246690/184093356-b1fe045c-ab34-4bde-bdc2-b43fa74faefc.png">

Additionally, some other good options that could help would be to have  a way to "Unselect all", like in Visual Studio here you can right click on the grouped folder (Add/Update/Remove) and exclude all.

**Comment by kisantia** [comment]
closing as dups of https://github.com/microsoft/azuredatastudio/issues/10430 and https://github.com/microsoft/azuredatastudio/issues/12964. Please upvote these other issues to help us track interest in these enhancements.
