### ISSUE TITLE
Table Hint NOLOCK is not allowed

### ISSUE THREAD

**Issue by TidyPyAi** [microsoft/azuredatastudio#20313]
Schema Compare failed:  
Table Hint NOLOCK not Allowed
Source:  SQL Server Schema Compare Extension
![image](https://user-images.githubusercontent.com/109158403/184199534-d02e1956-61db-4275-9ff9-177a2045cb5c.png)

**Comment by kisantia** [comment]
@TidyPyAi can you check if this scenario works in SSDT in Visual Studio? Also, please provide a simple repro. Thanks!

**Comment by TidyPyAi** [comment]
I’m not sure about the request for a repo?
Below I’m able to connect;  probably an issue on my end; as I cannot see some things.





***@***.***

***@***.***



Best regards,
Christopher Lazok
Applications Systems Analyst
Office: 281.647.3789
Email: ***@***.******@***.***>
16850 Park Row Dr. Houston, TX 77084

This message and any files transmitted with it are intended exclusively for the intended recipient, and may contain confidential and/or privileged information. If you are not the intended recipient, please immediately notify the sender by replying to this message, and delete the message and any/all attachments.

**Comment by kisantia** [comment]
@NSP1790 @TidyPyAi to clarify, is the database synapse serverless pool for these failing schema compares? Synapse Serverless Pool is not yet supported at the DacFx level (the backend of schema compare) - https://github.com/microsoft/DacFx/issues/23

**Comment by NSP1790** [comment]
> @NSP1790 @TidyPyAi to clarify, is the database synapse serverless pool for these failing schema compares? Synapse Serverless Pool is not yet supported at the DacFx level (the backend of schema compare) - [microsoft/DacFx#23](https://github.com/microsoft/DacFx/issues/23)

Yes, it is Synapse Serverless Pool that fails.

**Comment by tidypy** [comment]
You are correct; this was a Sql serverless pool.  I am able to run the tool on our Local DB clone, with our lifecycle services VM.
I suppose this limitation should be put in the help files or FAQ?  
Also with SSP's the Schema and SYS files will only populate with header information; but will not populate with data unless specifically designed to do so.  

Example:  running a data definition query; will only produce the header information and not the data definitions.   Select TOP (100)  will produce blank data on SYS and Schema DBO's.   

also;  another limitation is the Syntax; alot of SQL has to be rewritten with ''_underscores" to replace ".dot" in the names of entities.  INFORMATION_SCHEMA.COLUMNS  is now INFORMATION_SCHEMA_COLUMNS;

**Comment by kisantia** [comment]
thanks for confirming! Support for Synapse Serverless Pools is in progress, and the DacFx issue linked above will be updated when it is completed. 

@tidypy thanks for the suggestion, we will add this limitation to the schema compare docs. For the other items, please create new issues to help better track them. Thanks!

**Comment by kisantia** [comment]
closing since support needs to be added upstream in DacFx
