### ISSUE TITLE
Python package in ADS

### ISSUE THREAD

**Issue by PyMach** [microsoft/azuredatastudio#20312]
- Azure Data Studio Version: 1.38
- OS Version: Windows 10

Steps to Reproduce:

1. Create a new Notebook and check the kernel to Python3
2.  In the Code Cell  add the below code
import os
import sys
import pyodbc
import pandas as pd
print(sys.version_info)
print(os.path.dirname(sys.executable))
3. run
 and you will receive error message

**ModuleNotFoundError: No module named 'pyodbc'**

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/49952992/184199666-38ab9ded-d2dc-4881-a556-07fa4d9878c5.png)

**Comment by chlafreniere** [comment]
@corivera can you help take a look?

**Comment by corivera** [comment]
Do you have pyodbc installed? Looks like it's a pip package on pypi.

**Comment by corivera** [comment]
Closing due to no repro
