### ISSUE TITLE
CLR types are not supported on .NET Core SQL Database Projects Publish

### ISSUE THREAD

**Issue by semics-tech** [microsoft/azuredatastudio#20310]
- Azure Data Studio Version: 1.38.0
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. Load existing SSDT project (created in Visual Studio)
2. Publish project from Publish Profile
3. Publish fails with errors:

```

    stdout: <PROJECT_DIR>\Lib\OcfLzw2\bin\Debug\OcfLzw2.dll : Build error SQL72025: CLR types are not supported on .NET Core. [<PROJECT_DIR>\Databases\DBNAME\DBNAME.sqlproj]
    stdout: <PROJECT_DIR>\DBNAME\obj\Debug\DBNAME.dll : Build error SQL72025: CLR types are not supported on .NET Core. [<PROJECT_DIR>\DBNAME\DBNAME.sqlproj]
    stdout:     570 Warning(s)
    stdout:     2 Error(s)
    stdout: 
    stdout: Time Elapsed 00:00:12.81
```

Does this issue occur when all extensions are disabled?: NA

**Comment by kisantia** [comment]
as the error message says, this is a limitation of .NET Core DacFx that CLR types are not supported. Use .NET full sqlpackage or SSDT to publish projects with CLR types
