### ISSUE TITLE
"Object Explorer task didn't complete within 45 seconds" Error when connected to a server for which I don't have access to all the databases.

### ISSUE THREAD

**Issue by ZacharyArgentin** [microsoft/azuredatastudio#20321]
Issue Type: <b>Bug</b>

I've successfully connected to a SQL Server that has 3 databases on it. I only have access to 2 of those databases (i.e. I have a SQL Login for the SQL Server, but I only have a SQL User for 2 out of those 3 databases).

The object explorer fails to load. I've faced a similar issue in the past and i've fixed it by creating a SQL User for my SQL Login for all of the databases on the server.

The problem is in this case I can't create a SQL User for myself because my organization (reasonably) doesn't want to give me access to databases I don't need access to simply because my RDBMS client has a glitch.

This is on Azure Data Studio for Mac. I've connected to the same server using SQL Server Management Studio on a windows machine and the object explorer works fine.

The SQL Server I'm connecting to is hosted on Azure, and the databases are Azure SQL databases, if that makes any difference.

Please let me know if you need any more info. Thanks,

Zach

[Console.log](https://github.com/microsoft/azuredatastudio/files/9313764/Console.log)

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T19:53:12.357Z)
OS version: Darwin x64 21.5.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>

**Comment by StefanBolling** [comment]
I get the same error message when I connect to a server, also Azure Hosted SQL database, with a lot of databases on it (100+), even if I have access to all of them. I´m hoping the October 2022 release will solve this for us as well.

**Comment by GlebStar1** [comment]
Having issue with the same error when connected to Azure SQL Server

Version: 1.39.1 (system setup)
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by cheenamalhotra** [comment]
Noticed an exiting issue we're tracking for the same concern: #5173

**Comment by ZacharyArgentin** [comment]
It looks like this fix was scheduled for the October 2022 release. I just downloaded the new release today and the issue has not been fixed.

I've attached log files and system info below

[console.log](https://github.com/microsoft/azuredatastudio/files/10027352/console.log)
[20221116T184908.zip](https://github.com/microsoft/azuredatastudio/files/10027353/20221116T184908.zip)


**Azure Data Studio Version Info:**
Version: 1.40.0
Commit: 3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:49.772Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin x64 22.1.0


**System Information:**
CPUs | Apple M1 (8 x 24)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled metal: disabled_off multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled webgl: enabled webgl2: enabled
Load (avg) | 2, 2, 2
Memory (System) | 8.00GB (0.04GB free)
Process Argv |  
Screen Reader | no
VM | 0%


**Enabled extensions:**
Extension | Author (truncated) | Version
-- | -- | --
admin-pack | Mic | 0.0.2
agent | Mic | 0.49.0
azuredatastudio-postgresql | Mic | 0.2.7
dacpac | Mic | 1.11.0
import | Mic | 1.5.3
profiler | Mic | 0.11.0


Thanks, and let me know if you need any more information.

- Zach

p.s.  @cheenamalhotra I've noticed this issue has been closed, should I move this comment over to [#5173](https://github.com/microsoft/azuredatastudio/issues/5173) ?

**Comment by cheenamalhotra** [comment]
Sure, you may. Issue is not fixed yet - it will be addressed in #5173.
This one was closed as a duplicate.
