### ISSUE TITLE
New Query not establishing connection when using instance context menu

### ISSUE THREAD

**Issue by LavKiv** [Microsoft/azuredatastudio#2032]
Issue Type: <b>Bug</b>

1. Right click on instance name
2. Click New Query - query window opens, but without established connection.
![image](https://user-images.githubusercontent.com/38527919/43217260-276bf12e-900f-11e8-99ed-b67c1592b099.png)
![image](https://user-images.githubusercontent.com/38527919/43217291-3cfd0f64-900f-11e8-8e7d-4a8234532ad7.png)

Expected behavior: Query window opens with connection to default database.
If I click New Query from Databases, Security, or Server Objects etc. context menu , query window will open with connection to default database.
![image](https://user-images.githubusercontent.com/38527919/43217470-b83b04c4-900f-11e8-858f-4d01f5ed2729.png)
![image](https://user-images.githubusercontent.com/38527919/43217333-556301b2-900f-11e8-81af-de212b96422a.png)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (7.56GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|1.3.0
ssmskeymap|kev|0.2.0
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1
sql-search|Red|0.2.0

</details>

**Comment by abist** [comment]
@LavKiv Can you tell us what kind of server it is? I'm not able to repro this issue.

**Comment by LavKiv** [comment]
@abist 
Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64) - here is the version. Do you need any other details that I can provide?
I also noticed that everything works fine, if I use Windows authentication. Issue is present with SQL Login authentication type.

**Comment by kburtram** [comment]
This is working for me against `Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14` using SQL Login with the latest ADS build.  Please let me know if the issue persists.

**Comment by LavKiv** [comment]
> 
> 
> This is working for me against `Microsoft SQL Server 2017 (RTM-GDR) (KB4293803) - 14.0.2002.14` using SQL Login with the latest ADS build. Please let me know if the issue persists.

Checked it. Works perfectly fine. Thank you.
