### ISSUE TITLE
SQL delete is performed for commented query in some situations

### ISSUE THREAD

**Issue by martinfbluesoftcz** [microsoft/azuredatastudio#20324]
Issue Type: <b>Bug</b>

Hello, this is second time when I have experience with running undesirable DELETE SQL query.
I had this code in editor (commented DELETE query):

```
-- delete from PP_BusinessCentralSyncHistory
-- where EntityType = 'UsersB2B'
-- go

SELECT TOP (1000) [BusinessCentralSyncHistoryID]
      ,[SiteName]
      ,[BusinessCentralSyncHistoryLastModified]
      ,[UnsuccessfulItems]
      ,[EntityType]
  FROM [dbo].[PP_BusinessCentralSyncHistory]
  order by BusinessCentralSyncHistoryID desc
```

First I had uncommented version and then commented DELETE part and pushed F5

But DELETE SQL performed and table was event completely deleted.
Probably performed this query:
`delete from PP_BusinessCentralSyncHistory`

This is very strange and dangerous behaviour, please check it or I have to return to SSMS.

Azure Data Studio version: azuredatastudio 1.36.1 (e56e1d931bbb110fe8f24751423c4e184bb8f22d, 2022-04-21T21:25:10.399Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10600K CPU @ 4.10GHz (12 x 4104)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (2.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by alanrenmsft** [comment]
not able to repro but will take another look later. 
@martinfbluesoftcz do you remember doing anything special that might help the repro?

**Comment by martinfbluesoftcz** [comment]
Hello, you need to comment DELETE statement with key shortcut (CTRL+K,C), then do not click to editor and run query.

**Comment by caohai** [comment]
![Nov-03-2022 17-08-23](https://user-images.githubusercontent.com/21186993/199857930-7ed00e12-ed70-491f-9829-9f25db772272.gif)
@martinfbluesoftcz I did a quick test using latest version, the test was done solely by keyboard. Steps for the test:
1. I input a query like this then run the query by pressing F5
```
select 1
select 2
```

2. I use up arrow key to switch to line 1 and then press command + k, c to comment out the first line
3. I press F5 again to run the query.

Is this the same steps you were using? Are you able to repro the issue consistently?

**Comment by kburtram** [comment]
The is a command "Run Current Query" (Ctrl-F5) which will run the current query or selected text.  If the delete statement was highlighted without the `--` and this command was executed you would run the commented-out code.  Otherwise, I'm not sure how you could have the commented-out statements execute.  I also wasn't able to repro as described.

**Comment by caohai** [comment]
Needs more info for a repro, will close for now but feel free to reopen once you have it.
