### ISSUE TITLE
ADS cannot find Azure CLI extension, but extension shows installed

### ISSUE THREAD

**Issue by ALZDBA** [microsoft/azuredatastudio#20322]
Issue Type: <b>Bug</b>

ADS cannot find Azure CLI extension, but extension shows installed !

message:
Could not find Azure CLI, install it now? If not then some features will not be able to function.

First time I clicked "Yes" for "install now" .

After succesful install, I restarted ADS and keep on getting the same message

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
arc|Mic|1.5.1
azcli|Mic|1.5.1
dacpac|Mic|1.10.1
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.11.0
schema-compare|Mic|1.15.0
sql-database-projects|Mic|0.18.0
sql-migration|Mic|1.0.4

</details>

**Comment by Charles-Gagnon** [comment]
@candiceye FYI

**Comment by ALZDBA** [comment]
After update to 1.39.0 I no longer receive this message.

Version: 1.39.0 (system setup)
Commit: 9fdb2161d49b4d4ab6798809faa042a898ca2eae
Date: 2022-08-20T01:46:47.606Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Kind regards,

Johan

**Comment by kburtram** [comment]
I'll close this issue based on the above comment.
