### ISSUE TITLE
Drop down menus should activate arrow cursor and not text cursor

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20348]
**Is your feature request related to a problem? Please describe.**
Drop down menus should activate arrow cursor or pointer cursor and not text cursor. 

**Describe the solution or feature you'd like**
Drop down menus should activate arrow cursor and not text cursor

**Describe alternatives you've considered**

**Additional context**
See below 
![DB object dropdown](https://user-images.githubusercontent.com/72947001/184697253-48ba319d-900c-4fac-ac3d-01b73fb35adb.gif)

Applies to Table Designer (e.g. when selecting data type), Query Editor (when navigating DB object dropdown). 
Could be missing out on where else this is the case

**Comment by alanrenmsft** [comment]
wrong screenshot? this seems to be a dupe of https://github.com/microsoft/azuredatastudio/issues/20347

**Comment by tdoshin** [comment]
Yes, its a dupe of the screen shot, but intended as such. If you see the drop down icon, the cursor is showing as a text cursor, instead of an arrow cursor @alanrenmsft

**Comment by alanrenmsft** [comment]
closing as dupe of #20347
