### ISSUE TITLE
Lower/Uppercase inconsistencies in dropdown data type names vs in script

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20349]
- Azure Data Studio Version: Insiders
- OS Version: Windows Enterprise 

Steps to Reproduce:

1. Open Table Designer in Azure Data Studio 
2. Open data type drown. Observe case settings in data type drop down 
3. Make changes to the table and select "Publish"
4. Select "Generate Script" to view T-SQL script of table 

Expected: 

Case-sensitivity should be consistent in data type drop down and script 

Actual: 

Script contains upper case data types and Designer drop down is lower case

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
no impact to the functionality
