### ISSUE TITLE
Bug when changing data type of two columns in the same index

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20345]
- Azure Data Studio Version: Insiders Build 
- OS Version: Windows Enterprise 

Steps to Reproduce:

1. Create a table like this 

 CREATE TABLE ThreeDates (id int NOT NULL,
                         d1 datetime NOT NULL,
                         d2 datetime NOT NULL,
                         d3 datetime NOT NULL,
      CONSTRAINT pk_ThreeDates PRIMARY KEY(id)
)
go
CREATE NONCLUSTERED INDEX d1_d2_ix ON ThreeDates (d1, d2)

2. Next, open the table in the Designer, Change the data types of d1 and d2 to date. This results in the Issues tab displaying Column with name ‘’ has already been added to the index ‘d1_d2_ix’. Row number 2. 

![image](https://user-images.githubusercontent.com/72947001/184693011-03ba4515-69c5-4a80-babc-43719061f919.png)

4. Hit Ctrl + S 

5. Select "Update Database"

Expected: 

User should not be able to save these changes as there is an error in 2.) 

Actual: 

User is able to save and update database even when there is error 

![image](https://user-images.githubusercontent.com/72947001/184693223-3e4c6e91-8139-42c6-93f0-5a10a5c49d2f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
fix is available in dacfx.
