### ISSUE TITLE
Provide support for Hash-Index in Memory-Optimized Tables

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20355]
**Is your feature request related to a problem? Please describe.**
Hash indexes are one of the possible index types in a memory-optimized table, and so they should be supported

**Describe the solution or feature you'd like**
Provide support for Hash Indexes for Memory-Optimized Table types

**Describe alternatives you've considered**

**Additional context**

**Comment by caohai** [comment]
@tdoshin Erin created the same issue a while ago #19257 I'm going to close this one.
