### ISSUE TITLE
Alter Table Considerations in Table Designer 

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20359]
**Is your feature request related to a problem? Please describe.**

Table Designer provides the ability to add new columns to a table, or re-order columns.  In some cases of adding a column to a table, for example, adding a column to the end of the table with a NULL value, it is only a metadata change.  In other cases, such as adding the new column to the middle of existing columns, or changing the ordinal location of one or more columns, it is required to create a new table and move all existing data to the new table.  Depending on the size of the table, and the hardware, this can be a lengthy operation which potentially consumes significant disk space for both the data file and the transaction log.  For seasoned database professionals, this change would be done via a script in batches.  For those with limited experience, executing this type of change via Table Designer could create unintended consequences such as locking the table for an extended time and creating downtime for the system. 

Current Behavior: 

Currently when a user changes the orders of columns, or adds a new column to the middle of the table, ADS generates the following dialog: 

![image](https://user-images.githubusercontent.com/72947001/184712126-035f6a4a-0c0a-4ca4-9fb8-e126801005a6.png)

For novice users, the concept of “table rebuild” may not be understood.  The potential for an outage during this change depends on the size of the table (volume of data), underlying hardware, and table use.  Further, the table will be unavailable for the duration of the operation.  If the table is critical to the business, there is a potential for the system to become unusable. 

**Describe the solution or feature you'd like**
Modify the ‘Preview Database Updates’ dialog (below) to provide more concise information, and a warning about the modification based on table size.   

Include a warning that the table will be unavailable while the change is being made.  

Consider not allowing any change which requires a table to be recreated and data migrated over, unless a specific setting has been changed (default value does not allow the change). 

Keep the behavior consistent with SSMS to timeout/rollback the transaction after 30 seconds. 

Dialog recommendations: 

Change ‘Tables that will be rebuilt’ to ‘Tables that will be recreated and data migrated’ 

Add another line until ‘Tables that will be rebuilt’ to state: 

‘Saving definition changes to tables with large amount of data could take a considerable amount of time.  While changes are being saved, the data in the table will not be accessible.’ 

Change ‘Table rebuild’ to ‘Table migration’ 

![image](https://user-images.githubusercontent.com/72947001/184712433-3c2a2a64-3f1b-45c8-9c26-d83e9074dfc6.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by erinstellato-ms** [comment]
For cases where there are more than 100K rows, but the table does not need to be recreated, provide information to the user that the update may take extended time and require the user to acknowledge it.  Optional: make number of rows a setting.
Examples: adding a column to a table with a default value
