### ISSUE TITLE
Linked accounts panel frozen on "Loading accounts"

### ISSUE THREAD

**Issue by thgauchet** [microsoft/azuredatastudio#20364]
left bottom corner, click on "Accounts" icon
it opens Linked accounts panel
Linked accounts panel is blocked for hours with "Loading accounts" as message.
I would like to be able to clean my all linked accounts and restart config from scratch.

**Comment by kburtram** [comment]
@thgauchet there isn't a way to clear the accounts specifically, outside using the UI.  But you can clear all the application config by removing the local application state.  One Windows you can delete `%APPDATA%\azuredatastudio` to get back to a 1st-launch config.

If you are getting any errors in the logs that may help us give better suggestion on how to workaround the UI hang.  Please let us know if you see any exceptions in the "Help->Developer Tools->Console".  Thanks!

**Comment by thgauchet** [comment]
Hi Karl,
thank you so much, I was blocked on this since several weeks. I have not found on internet your method to clear accounts.. It works perfectly. Great!



--
best regards
Thomas Gauchet

**Comment by cheenamalhotra** [comment]
Closing as customer unblocked with local config reset.
