### ISSUE TITLE
Not able to publish database

### ISSUE THREAD

**Issue by PyMach** [microsoft/azuredatastudio#20369]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. 1.38
2. Windows 10

Does this issue occur when all extensions are disabled?: Yes

I have a database project and try to publish but it fails and getting the below error message, can you please check and help?

**Deploy dacpac: Could not deploy package.
Warning SQL72012: The object [DBName***] exists in the target, but it will not be dropped even though you selected the 
'Generate drop statements for objects that are in the target database but that are not in the source' check box.
Warning SQL72012: The object [***] exists in the target, but it will not be dropped even though you selected the 'Generate drop statements for objects that are in the target database but that are not in the source' check box.
Warning SQL72015: The column [dbo].[*tablename*].[**column**] is being dropped, data loss could occur.
Warning SQL72015: The column [dbo].[*tablename*].[**column**]  is being dropped, data loss could occur.
Warning SQL72015: The column [dbo].[*tablename*].[**column**] is being dropped, data loss could occur.
Warning SQL72015: The column [dbo].[*tablename*].[**column**]  on table [dbo].[*tablename*] must be added, but the column has no default value and does not allow NULL values. If the table contains data, the ALTER script will not work. To avoid this issue you must either: add a default value to the column, mark it as allowing NULL values, or enable the generation of smart-defaults as a deployment option.
Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 15063, Level 16, State 1, Line 1 The login already has an account under a different user name.
Error SQL72045: Script execution error. The executed script:
CREATE USER [domain\USERID] FOR LOGIN [DOMAIN\USERID];**

and my publish profile is attached below

![image](https://user-images.githubusercontent.com/49952992/184970552-64fd6c74-5cae-4776-afc7-5dc2fb8b9270.png)

**Comment by kisantia** [comment]
@PyMach the error message says "The login already has an account under a different user name.", so either the other user associated with the login needs to be dropped or domain\USERID not created

**Comment by kisantia** [comment]
In the latest ADS release (1.39) and sql database projects (0.19.0), deployment options are available by clicking on the "Advanced..." button in the publish dialog. You can try excluding users or generating the script, then removing the line causing the error.

Closing issue since this isn't a bug
