### ISSUE TITLE
Schema Compare failed: The source and target platform must be the same to use Schema Compare for Azure Synapse Dedicated SQL Pool

### ISSUE THREAD

**Issue by monteholyfield** [microsoft/azuredatastudio#20363]
Azure Data Studio Version: 1.38.0 (user setup)
Commit: dff93c4736269ef2a7e8a225737a0d8354bf0246
Date: 2022-07-26T23:56:16.217Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

Steps to Reproduce:

1. create connection to Azure Synapse SQL Pool
2. choose 'Create project from database'
3. commit
4. choose 'Update project from database' which produces the following error:

Schema Compare failed: The source and target platform must be the same to use Schema Compare for Azure Synapse Dedicated SQL Pool

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Michael-Kagnew** [comment]
I get this exact same issue, and even more so doing anything involving schema compare and Azure Synapse Dedicated Sql Pool. Notably, doing this in Visual Studio will work instead.

**Comment by dzsquared** [comment]
In the .sqlproj file for that project - what is the value in the <DSP> tag?

**Comment by kisantia** [comment]
@monteholyfield please check if this is the DSP in the sqlproj:
`    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlDwDatabaseSchemaProvider</DSP>
`

The project's target platform can also be seen by right clicking on the project node and selecting "Change target platform", which will open this quickpick where the current target platform is displayed and can be changed 
![image](https://user-images.githubusercontent.com/31145923/185510129-2f683442-ebc0-44f4-8e2e-3ff81382417e.png)
