### ISSUE TITLE
Select Top 1000 Context Menu Does Nothing

### ISSUE THREAD

**Issue by hdrenollet-csusa** [microsoft/azuredatastudio#20365]
Issue Type: <b>Bug</b>

Every time I use the "Select Top 1000" option on a table in the context menu, absolutely nothing happens.  No window opens, no messages, no errors, nothing.  I've even sat here and waited for over 30 minutes after clicking it and still nothing happens.  It happens literally every time.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.89GB (19.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.48.0
azcli|Mic|1.5.1
azuredatastudio-postgresql|Mic|0.2.7
azuremonitor|Mic|0.1.4
cms|Mic|0.8.0
dacpac|Mic|1.10.1
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
machine-learning|Mic|0.11.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
query-history|Mic|0.2.1
schema-compare|Mic|1.15.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.3
sql-database-projects|Mic|0.18.0
sql-migration|Mic|1.0.4
whoisactive|Mic|0.1.4
dotnet-interactive-vscode|ms-|1.0.3255010
jupyter|ms-|2021.8.1046824664
vscodeintellicode|Vis|1.2.1

</details>

**Comment by martinleo** [comment]
Looks like a duplicate of [20241](https://github.com/microsoft/azuredatastudio/issues/20241)

**Comment by hdrenollet-csusa** [comment]
> Looks like a duplicate of [20241](https://github.com/microsoft/azuredatastudio/issues/20241)

Yes, this matches the error that I'm receiving as well for Azure Synapse Analytics Dedicated SQL Pools
