### ISSUE TITLE
[SQL Migration] Missing SKU recommendation and assessment functionality 

### ISSUE THREAD

**Issue by raymondtruong** [microsoft/azuredatastudio#20370]
- Azure Data Studio Version: 1.38.0
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Launch SQL Migration wizard, proceed to assessment and SKU recommendation steps
2. Observe missing functionality (see below)

Does this issue occur when all extensions are disabled?: Yes/No

----------

**Note:**

This bug is for tracking a port request to the release branch for sqltoolsservice / mssql in ADS. Discussed details internally with product team as part of ADS Shiproom.

**Background:** 

SQL Migration is adding several new features as part of its next extension release, which will happen off-cycle and independently of the ADS product release. However, some of these new features require backend changes to sqltoolsservice, which we are trying to release as part of ADS 1.39. These changes include:
- adding the ability to export assessment and SKU recommendation reports to a folder of the user's choosing
- adding the elastic SKU recommendation model, which will be made available via a feature switch
- fixing some misc bugs regarding logging and error handling in the backend migration service

Submitting this bug / port request now, as these changes did not get checked in on time for the code complete date.

**Changes:**

Specifically, this is accomplished by adding additional outputs to the `migration/getskurecommendations` and `migration/getassessments` requests. Tested and verified that  these changes are backwards compatible (tested by building STS locally, which includes these changes, but consumed from an older version of the SQL Migration extension). The PRs in question are the following:
- https://github.com/microsoft/sqltoolsservice/pull/1613
- https://github.com/microsoft/sqltoolsservice/pull/1602

**Comment by alanrenmsft** [comment]
PR merged
