### ISSUE TITLE
Cannot publish SQL Project to local emulator, Error SQL72014

### ISSUE THREAD

**Issue by delsehi** [microsoft/azuredatastudio#20380]
- Azure Data Studio Version: 1.38.0
- OS Version: Windows 10

Steps to Reproduce:

1. Install the SQL Database Projects extension and start Docker.
2. In the Database Projects extension, create project from database. I select an existing production database in Azure. It's an SQL server. Folder structure = Schema/Object Type, SDK-Style project enabled. 
3. Build the project. I get 0 errors and 357 warnings. Mostly warnings about that object references differ in case SQL71558 or unresolved references SQL71502. 
4. Publish project to new SQL server local development container. The docker container is published, but the "Deploy dacpac"-stage fails with error: 

```
Deploy dacpac: Could not deploy package.
Warning SQL0: A project which specifies SQL Server 2019 as the target platform may experience compatibility issues with SQL Server 2017.
Warning SQL0: The source contains users that rely on an external authentication provider that is not supported by the target. These users will be treated as users without logins.
Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 15007, Level 16, State 1, Line 1 'DATAFACTORY' is not a valid login or you do not have permission.
Error SQL72045: Script execution error. The executed script:
CREATE USER [DATAFACTORY] FOR LOGIN [DATAFACTORY];
```

6. I go back to step 3 and change the target platform to Azure SQL Server and build the project again. 
7. Publish the project, base image Azure SQL Database emulator Full. Same error:

```
Deploy dacpac: Could not deploy package.
Warning SQL0: The source contains users that rely on an external authentication provider that is not supported by the target. These users will be treated as users without logins.
Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 15007, Level 16, State 1, Line 1 'DATAFACTORY' is not a valid login or you do not have permission.
Error SQL72045: Script execution error. The executed script:
CREATE USER [DATAFACTORY] FOR LOGIN [DATAFACTORY];

```

I've also tried adding the master as a database reference. I've tried this in Azure Data Studio, Visual Studio Code and Visual Studio 2019. 

Extension version: 0.18.0
Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.39GB (7.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
Looks similar to #20290, more details in this comment https://github.com/microsoft/azuredatastudio/issues/20290#issuecomment-1212485474. This should be fixed in the upcoming August release.

**Comment by kisantia** [comment]
@delsehi can you try the latest ADS (1.39) and sql database projects extension (0.19.0) and verify if this is resolved? Publish options are now available by clicking on the "Advanced..." button in the publish dialog

**Comment by delsehi** [comment]
@kisantia 
It seems it's resolved without me having to specify anything in the Advanced options. I guess the defaults worked. Nice!

It is still unusable for me though. We use an Azure SQL server with full-text search. 

`Error SQL72014: Core Microsoft SqlClient Data Provider: Msg 7609, Level 17, State 5, Line 2 Full-Text Search is not installed, or a full-text component cannot be loaded.`

I'm guessing the default docker images used publish locally don't have all the tools installed that are included in the Azure SQL Server. Maybe a future feature could be the possibility to choose a custom local container image in the dropdown instead of just the Full/Lite versions? Because I've managed to install that and sqlPackage in a container. But until then I guess we won't be able to use ADS in our development workflow 😭

**Comment by dzsquared** [comment]
There is a section of surface area that is not yet covered by the SQL DB emulator options provided in Azure Data Studio, I apologize for lack of clarity on that and will work on getting the docs updated.  Getting closer fidelity with the full Azure SQL DB service is a goal for the emulator.

For your scenario it sounds like you had success creating your own container image - as a workaround it would be possible to start the container locally, then publish to an existing SQL instance in the ADS publish flow - setting the container image as the target endpoint.

**Comment by delsehi** [comment]
Thanks, good to know that it's on the roadmap.

I got a workflow working. Build the SQL project with a custom dockerfile with fts and sqlPackage, start the container, write failing tests in vitest, connect to the db with ADS and work until the tests pass, update project from database and select the local container, then publish to azure sql server. Something like that. I'll close the issue. Thanks for the help :)
