### ISSUE TITLE
Database queries taking a long time using domain name with VPN

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#20389]
Issue Type: <b>Bug</b>

When connected to our Azure database via our Azure VPN using the domain name, a simple query (select top 10 * from user) takes an order on magnitude longer than if I connect to the database via its IP address (10 seconds vs. milliseconds)

Even making the connection takes an extremely long time - I had to up the timeout values to 60 seconds.

The same connection and query using SSMS is almost instantaneous.

Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (4a2c6e9fb4500f11921dd3a463bd8e1b98b04f26, 2022-08-17T05:33:36.424Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (17.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.10.1
import|Mic|1.5.0
schema-compare|Mic|1.15.0
sql-database-projects|Mic|0.18.0
sql-search|Red|0.4.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by jtsom** [comment]
This is still a huge issue. I'm connected to our VPN to connect to our Azure database, and even trying to show the database structure takes several minutes...if it even completes. Trying a simple select takes minutes. Same operations to a local database work just fine and fast. Something with the network and VPN is causing HUGE issues. This is with the latest Insiders version 

Version: 1.41.0-insider (user setup)
Commit: 3239bb429fa73d80576d25820a58d6e15da8eda0
Date: 2023-01-13T06:29:45.091Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by cheenamalhotra** [comment]
Hi @jtsom 

Please capture and upload logs as per instructions above so we can take a closer look. 
Would recommend masking servername from MSSQL log file for any concerns.

**Comment by jtsom** [comment]
I will try and get this info again. I did try once, but all of the files that were in the folder referenced above were empty, so they'd be no help. ADS is all but unusable when trying to connect to our corporate azure MSSQL database over the VPN. The connection is slow to never responding. The exact same connection / query using SSMS is instantaneous. The was one error in the log window that just said "There was an error, check the log window". Helpful.

**Comment by cheenamalhotra** [comment]
As discussed in [#7440](https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1656138448) - VPN connectivity should get better performance with connection pooling enabled. For even better performance, please flush DNS cache or resolve environment DNS resolution timeouts, as the delay is related with DNS name resolution in your network.

I will close this issue as resolved.
