### ISSUE TITLE
Implement Command Line Switches

### ISSUE THREAD

**Issue by RandomNoun7** [microsoft/azuredatastudio#2039]
- SQL Operations Studio Version:
0.31.4

Steps to Reproduce:
Invoke sqlops.exe --help from the command line.
No return is given to the command line. The executable is full launched and new windows is spawned.

It would be nice to have command line switches for doing things like managing extensions in the style of VSCode and the --list-extensions, --install-extension, --uninstall-extension, and --extensions-dir switches, along with a --help switch for discoverability.

**Comment by mintsoft** [comment]
+1   I think this is absolutely vital. I'm trying to roll out ADS at the moment and I absolutely need the ability to install extensions from the command line so I can automate it. Ideally it'd behave the same as the vscode `--list-extensions` and `--install-extension` flags

**Comment by Charles-Gagnon** [comment]
You should be able to do that now : 

From command line :

```
azuredatastudio --help
azuredatastudio --list-extensions
```

If you want the full path you should point to the .cmd file - not the .exe directly.

```
%LOCALAPPDATA%\Programs\Azure Data Studio\bin\azuredatastudio.cmd --help
%LOCALAPPDATA%\Programs\Azure Data Studio\bin\azuredatastudio.cmd --list-extensions
```

Let me know if you still can't get this to work!
