### ISSUE TITLE
Add a stateChanged boolean property to InputBoxComponent

### ISSUE THREAD

**Issue by candiceye** [microsoft/azuredatastudio#20391]
**Is your feature request related to a problem? Please describe.**
Problem: increment/decrement button for the InputBoxComponent field is re-setting the value down to the minimum when clicked, despite the value in the field. Upon investigation, I found out that this problem is the result of a workaround that was implemented so that the page could determine when the Save and Discard buttons should be enabled or disabled. This workaround had to be implemented because the InputBoxComponent type is lacking a property that tells whether or not it is in a changed state or not (whether or not the save button should be enabled). 

**Describe the solution or feature you'd like**
Add a boolean property to InputBoxComponent called something like: stateChanged, which should be set to false by default.

**Describe alternatives you've considered**
This PR "fixes" the initial problem but exposes another problem in which the Save button will be enabled upon page load. This is a bug because upon initial page load, nothing has been changed so Save should be disabled. This is happening because we stateChanged property in the whole class of miaaComputeAndStoragePage, but what we really need is a property for each of the components. The property in the PR is called alreadySaved. See: https://github.com/microsoft/azuredatastudio/pull/20289

**Additional context**
If this is confusing, please Teams message me (alias canye) and I can explain further.
@alanrenmsft also knows some info about this problem.

**Comment by alanrenmsft** [comment]
@candiceye if I remember correctly, this is not a blocking issue let me know if this becomes a problem for customers.

**Comment by candiceye** [comment]
@alanrenmsft Yep, not blocking issue.
