### ISSUE TITLE
not able to delete server registration

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#20410]
1. add a central management server
2. add a server registration under it
3. delete the newly added server registration

actual: the server registration deletion doesn't work

![cms](https://user-images.githubusercontent.com/13777222/185500874-42773e78-6dc5-4fb8-9f1d-af6ce2056c7c.gif)

**Comment by cheenamalhotra** [comment]
Issue doesn't occur anymore, closing as resolved.

![Image](https://github.com/microsoft/azuredatastudio/assets/13396919/cf5aece0-9275-47cc-8e6d-49fab6b67bb3)
