### ISSUE TITLE
Cannot display query plane

### ISSUE THREAD

**Issue by CwjXFH** [microsoft/azuredatastudio#20418]
Azure Data Studio Version: 
![image](https://user-images.githubusercontent.com/11468733/185538508-30f9d0e3-91e0-408c-8c50-e41b7b19d17b.png)

![image](https://user-images.githubusercontent.com/11468733/185538476-0ef92b3e-61b0-4ae7-a147-d7b5e7639f22.png)

**Comment by aasimkhan30** [comment]
This issue was due to a broken caching code in execution plan. It is fixed as of now.
