### ISSUE TITLE
Please fix the infinite loading

### ISSUE THREAD

**Issue by MortenMeisler** [microsoft/azuredatastudio#20417]
When I try to connect via connection string I get an infinite loading.

![image](https://user-images.githubusercontent.com/17620242/185575544-79e117fd-f06f-4ab2-85e0-6ee2567c8da0.png)

Nomatter what might be causing this, it's very bad practice with no feedback here.

Using latest version: 1.38.0

**Comment by cheenamalhotra** [comment]
Hi @MortenMeisler 

Could you please let us know if connection timeout is set to more than 30 seconds (_timeout=0 is infinite timeout_) and does the loading exceed the timeout limit in that case? Also please provide client OS information.

Thanks!

**Comment by MortenMeisler** [comment]
Where is the timeout setting for connection?

I'm connecting via Mongo DB using Azure Cosmos DB API. Running on Windows Server 2012.

![image](https://user-images.githubusercontent.com/17620242/186600574-3d1155d4-e094-4cc3-aa00-51a7c018b78d.png)

**Comment by alanrenmsft** [comment]
@MortenMeisler Issue with the extension should be opened in the extension's repo, I've created an issue for you this time: https://github.com/Azure/azure-cosmosdb-ads-extension/issues/37.
