### ISSUE TITLE
Query history can get incorrect query text

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20424]
1. Type a query in an editor
2. Run the query
3. Immediately delete some characters from the query

When the query history item shows in the view it will often have incorrect text, with some of the letters that were deleted being gone. 

The root cause here is that query history gets the text range from the core and then uses the VS Code APIs to get the actual text. But because the event isn't sent until after the query is finished executing we run into a race condition where the extension host document state has been updated in that time and so when the event is received the text it tries to get has already been updated. 

A couple of potential solutions :

1. Send query text in original event. This was tried but quickly can run into perf issues with large queries. Potential workaround would be to send query text directly if it's small enough, otherwise send range (which still leaves us with race condition for large queries)
2. Use queryStart to capture the text and then on queryStop use that text. There's still potential for a race condition but it's much smaller since queryStart is kicked off much sooner. To do this we'd need to add some sort of "query ID" that's incremented for each query to be able to uniquely identify each query as it's ran (otherwise multiple queries running in parallel could cause messages to be incorrectly used)

**Comment by dzsquared** [comment]
Could we add an API listener for when query execution is called for, but before the query is executed?  This could be used by query history but would also be useful in creating extensions that parse the query text and potentially intercept statements such as UPDATE/DELETE without a where clause.

**Comment by Charles-Gagnon** [comment]
That's what 2 is suggesting - I'm trying that out now since we already send this event whenever a query is started.

The intercepting statements thing is definitely interesting as we've discussed before - but for that to truly be powerful I think we'd want to add additional features like being able to veto execution in some scenarios (which isn't something that query history would care about). And doing that would require a lot more changes and consideration for how to do that correctly.
