### ISSUE TITLE
Ctrl+Right Arrow goes to end of current word, not the start of the next one.

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#20454]
Issue Type: <b>Bug</b>

Select a word. Press Ctrl+RightArrow. Cursor goes to the end of the current word. I expect it to go to the beginning of the next one.

Ctrl+Left Arrow works correctly, it always goes to the start of the previous word.

Just to be sure, I checked in NotePad and Microsoft Word. Ctrl+Right Arrow goes to the beginning of the next word.

Azure Data Studio version: azuredatastudio 1.38.0 (dff93c4736269ef2a7e8a225737a0d8354bf0246, 2022-07-26T23:56:16.217Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (20.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|57%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.48.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.2.1
azdata-sanddance|msr|3.3.0
sql-search|Red|0.4.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
This is the default behavior, you can change it by changing your keybindings : 

Default key binding : 

![image](https://user-images.githubusercontent.com/28519865/186471423-a7f5c6e0-2faa-49f9-887b-3900f44a99e7.png)

If you clear this and instead set ctrl + right arrow to `cursorWordStartRight` then you should get the behavior you want. 

![image](https://user-images.githubusercontent.com/28519865/186471299-19148f93-bb99-4ec6-b5f7-f964dc4a87c8.png)

**Comment by barryseymour** [comment]
Thank you!
