### ISSUE TITLE
Issue renaming an existing table in table designer

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#20483]
Currently if we rename a table in table designer, it creates a new table instead of renaming the current existing one, we need to actually rename the table using `sp_rename`

**Comment by alanrenmsft** [comment]
@erinstellato-ms @tdoshin FYI, we are creating more work for ourselves :). I think the task makes sense and is a better experience than the current behavior (ADS and SSDT behaves the same way). Please let us know if you have different opinions.

**Comment by erinstellato-ms** [comment]
@alanrenmsft can you clarify what you mean by "the task makes sense and is a better experience than the current behavior"?  You agree that renaming the table should create a new table?  Or do you think it should NOT do that?

**Comment by alanrenmsft** [comment]
@erinstellato-ms :) I think creating a new table is not a good experience. I would it to rename the existing table.

**Comment by erinstellato-ms** [comment]
@alanrenmsft oh perfect!  Creating a new table is definitely not a good experience!  Yes, we just need to rename the table.

**Comment by alanrenmsft** [comment]
the fixes were brought in to ADS by https://github.com/microsoft/azuredatastudio/pull/20538

**Comment by caohai** [comment]
This issue has not been fixed and I'll work on it next.
