### ISSUE TITLE
Extremely slow to open server connection

### ISSUE THREAD

**Issue by SeanSmithKP** [microsoft/azuredatastudio#20496]
Issue Type: <b>Bug</b>

- Click on a saved connection
- Either the connection is never established, or when it does the server objects take an extremely long time to appear (have left for up to half an hour) 

Azure Data Studio version: azuredatastudio 1.39.0 (9fdb2161d49b4d4ab6798809faa042a898ca2eae, 2022-08-20T01:46:47.606Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (14.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@SeanSmithKP this sounds like it could be related to https://github.com/microsoft/azuredatastudio/issues/20472.  We are planning to release a hotfix for that issue in the next day or two once testing is complete.  Please let me know if that issue doesn't describe the issue you are encountering.

**Comment by kburtram** [comment]
@SeanSmithKP we released a hotfix for issue https://github.com/microsoft/azuredatastudio/issues/20472, which appears possibly related to this one.  Are you still experiencing this issue on `1.39.1`.

**Comment by SeanSmithKP** [comment]
Thanks @kburtram, the update has resolved the issue.
