### ISSUE TITLE
Can't set column to NULL

### ISSUE THREAD

**Issue by joerattz** [microsoft/azuredatastudio#20499]
Issue Type: <b>Bug</b>

I can't seem to insert a NULL into text or date columns in edit mode.  I can if I run in update SQL command though.

Azure Data Studio version: azuredatastudio 1.37.0 (d904740d93d7df76a0ba361f20e4351813b57645, 2022-06-14T01:05:12.352Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (16.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by kburtram** [comment]
@joerattz you should be able to do this by typing `NULL` in the field.  Which type of server are you connecting to when this issue occurs?

**Comment by kburtram** [comment]
Closing due to no response to previous question.  I wasn't able to repro typing NULL into a cell using SQL Server connection.
