### ISSUE TITLE
Changing Table Schema creates new Table instead of just altering existing 

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20508]
- Azure Data Studio Version: 1.39
- OS Version: Windows Enterprise

Steps to Reproduce:

1. Open Designer in Object Explorer for any existing Table in a Database Object. For my case, I opened 'dbo.likes' under TestData Database Object in my Object Explorer
2. In Table Properties, go to the Schema drop-down menu and select the new Schema you want this Table to reside in. I picked the 'guest' Schema

![image](https://user-images.githubusercontent.com/72947001/187538727-ffa111ae-d79b-4558-b207-50636d7d0ade.png)

4. Hit Publish and Update Database 

Expected: 

Table Schema is altered from 'dbo.likes' to 'guest.likes'

Actual: 

A new Table, 'guest.likes' is created but 'dbo.likes' is also in the Object Explorer. Now we have two Tables instead of one. 

![image](https://user-images.githubusercontent.com/72947001/187538841-43cf5e6d-8718-4205-84fd-5e4a078737dc.png)

It should follow the SSMS behavior (alters the existing Table Schema instead of creating a new Table). See below. In SSMS, the 'Students' table schema was changed from 'dbo' to 'guest' without creating a new Table as expected. 

![image](https://user-images.githubusercontent.com/72947001/187539635-2772d097-59f4-4fe8-89fe-48d4027dcc6d.png)

I believe this is related to this issue https://github.com/microsoft/azuredatastudio/issues/20483

Does this issue occur when all extensions are disabled?: Yes

**Comment by tdoshin** [comment]
FYI @dzsquared @erinstellato-ms

**Comment by erinstellato-ms** [comment]
Looks related to #20483

**Comment by alanrenmsft** [comment]
yes, this is a dupe. thanks for filing though. @tdoshin
