### ISSUE TITLE
Wrong tenant shows up while trying to connect to database with Azure AD login

### ISSUE THREAD

**Issue by solita-kalleka** [microsoft/azuredatastudio#20517]
Issue Type: <b>Bug</b>

If you save a connection that you log in with "Azure Active Directory - Universal with MFA support", it saves the correct Azure AD Tenant id to settings, but still shows different tenant in the connection details when you try to connect to that database.

It's always the same tenant that shows up with every connection, no matter what is saved when creating that connection. At least for me, it's the first tenant that I had for my Azure account. It's not a problem if you're using only one tenant and it happens to show up there everytime. Developers of this software might not have more than one tenant in their test accounts, so this bug might have been completely overlooked by them. 

However, as a data engineer consultant, I need to use multiple connections around multiple tenants with Azure AD Login, and it's annoying that I have to change that tenant manually every time I try to connect to database, as my most used tenant is not the one that shows up there every time.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10310U CPU @ 1.70GHz (8 x 2208)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.4.0
schema-compare|Mic|1.16.0
sql-database-projects|Mic|0.19.0

</details>

**Comment by nielsvdc** [comment]
Steps to Reproduce:

1. Create a connection with a SQL database in a foreign tenant and connect.
2. Edit the connection.
3. You'll see the tenant has changed to the default tenant.
---

1. Create a connection with a SQL database in a foreign tenant and connect.
2. Open a query tab connected to the foreign database.
3. Disconnect
4. Click Connect button on the query tab and select the connection to the database in the foreign tenant.
5. You'll see the tenant has changed to the default tenant.

**Comment by cheenamalhotra** [comment]
Revalidated and seems like a small change was missed out, this issue is not completely fixed currently.

**Comment by cheenamalhotra** [comment]
Fix available in latest insiders now, verified.
