### ISSUE TITLE
Could not create table

### ISSUE THREAD

**Issue by bobyin** [microsoft/azuredatastudio#20519]
Issue Type: <b>Bug</b>

When I tried to create a new table got this error

An error occurred while initializing the table designer: The target database schema could not be retrieved.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
azcli|Mic|1.5.1
import|Mic|1.5.0
schema-compare|Mic|1.16.0
sql-database-projects|Mic|0.19.0
ADS-add-columns|sof|0.0.12

</details>

**Comment by alanrenmsft** [comment]
@bobyin 
1. how many times did you try it? wondering whether it is an intermittent issue.
2. need some more information about the target database, server version/edition, authentication type, any special characters in the database/table names?

**Comment by alanrenmsft** [comment]
@bobyin We'll reopen the issue when you have the information we requested ready.
