### ISSUE TITLE
Error when Publishing new Database Project repository to GitHub from Azure Data Studio

### ISSUE THREAD

**Issue by tdoshin** [microsoft/azuredatastudio#20520]
- Azure Data Studio Version: 1.39.0
- OS Version: Windows Enterprise

Steps to Reproduce (This came from an MVP)

1. If I select "Publish to GitHub" and select Allow for "The extension 'GitHub' wants to sign in using GitHub", I get the following error message:

![image](https://user-images.githubusercontent.com/72947001/187717734-7db3a326-5f60-497f-9193-23ab54dcef1f.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kisantia** [comment]
@tdoshin can you please provide more details? There isn't a "Publish to GitHub" option in the sql database projects extension

**Comment by dzsquared** [comment]
This isn't SQL projects specific - it's from the source control pane and is dependent on the VS Code merge. I've updated the tags but might not have gotten them 100% correct.

**Comment by dzsquared** [comment]
appears to be resolved as of:
Version: 1.40.0-insider
Commit: d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:48:43.511Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 22.1.0
