### ISSUE TITLE
error

### ISSUE THREAD

**Issue by LalySanders** [microsoft/azuredatastudio#20539]
Issue Type: <b>Bug</b>

Hello there.
How to change the language, I cannot understand this language. I want to change to English language

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (3.41GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
ads-language-pack-es|Mic|1.39.0
agent|Mic|0.49.0
azuredatastudio-postgresql|Mic|0.2.7
cms|Mic|0.8.0
dacpac|Mic|1.10.1
datavirtualization|Mic|1.12.0
import|Mic|1.5.0
managed-instance-dashboard|Mic|0.4.2
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
azdata-sanddance|msr|3.3.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
You can change the UI language by running the `Configure Display Language` command (ctrl + shift + P)

**Comment by LalySanders** [comment]
@Charles-Gagnon thank you!
