### ISSUE TITLE
Jupyter install fails on Windows Server with "Microsoft Visual C++ 14.0 or greater is required"

### ISSUE THREAD

**Issue by stuartpa** [microsoft/azuredatastudio#20546]
- Azure Data Studio Version: Latest
- OS Version: Windows Server 2019 and 2022 Datacenter (Azure and GCP VMs tried)

Steps to Reproduce:

1. Create VM in Azure or GCP with Windows Server 2019 or 2022
2. Start ADS
3. Create new Notebook
4. Select Python Kernel
5. Hit "Install" (when it prompts to install Jupyter support)
6. Fails with:

    running build_ext
    building 'psutil._psutil_windows' extension
    error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/

Installing C++ Build Tools at that link is 5GB! (and issue with filling up boot drive when using ephemeral VMs)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by chlafreniere** [comment]
@corivera can you take a look please?

**Comment by corivera** [comment]
@stuartpa are you using our provided python package (New Install) or an existing python instance you installed separately?

**Comment by stuartpa** [comment]
The former (this is a completely vanilla Windows Server Datacenter VM (tried both Azure and GCP), with no other software involved.

**Comment by corivera** [comment]
Do you see the same issue when using a separately installed python instance?

**Comment by stuartpa** [comment]
I was just trying to install ADS on a vanilla Windows Server VM and select the Python kernel.  I haven't tried anything more than this.  I have tried multiple cloud providers and multiple versions of Windows Server (2019 and 2022)

**Comment by corivera** [comment]
Seems like this is just a jupyter dependency (required by jupyter's psutil dependent package), since I get the same error when trying to install it using a standalone python instance on Windows Server.
