### ISSUE TITLE
.net core version required for Sentry One plan explorer excepetion

### ISSUE THREAD

**Issue by hajerty** [microsoft/azuredatastudio#20553]
- Azure Data Studio Version: 1.39.1
- OS Version: win 10 enterprise 1803

Steps to Reproduce:

1. Start Azure data studio 
2. in the last days I receive this message "The .NET Core Runtime is required (version 2.1+), but cannot be found. Ensure it is installed, and in your path." and the sentry one plan explorer extension doesn't work. I installed 6.0 .net framework and runtime.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
This sounds like an issue with the extension itself, please contact Sentry One for support. If there seems to be an issue with Azure Data Studio itself then let us know and we can reopen this and investigate!
