### ISSUE TITLE
Select Top 1000

### ISSUE THREAD

**Issue by nathangmahler1987** [microsoft/azuredatastudio#20551]
Issue Type: <b>Bug</b>

Steps to Reproduce:
1) Open Azure Data Studio
2) Connect to database
3) right click on one of the tables in the database
4) select 'SELECT TOP 1000' option
5) sit back and watch nothing happen:)
On this and the last version of Azure Data Studio (maybe others too I don't know) the 'SELECT TOP 1000' does nothing. No error message, no nothing. This is a crucial feature please fix promptly

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics      (16 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.83GB (4.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by smartguest** [comment]
Issue currently does not reproduce on our side via a local database, can you please describe the server database configuration you are using?

**Comment by nathangmahler1987** [comment]
I am not sure. I work for a medium organization and we are connecting to
Azure. Wouldn’t our configuration be set by IT or those that set the DB up?

**Comment by smartguest** [comment]
That is correct, they should know what the database type/configuration is.

This issue appears to be similar to this previously submitted issue: https://github.com/microsoft/azuredatastudio/issues/20241

Ask your IT department or those who set the DB up if they are using Azure Synapse or not, we currently have an issue where Select Top 1000 does not work for those kinds of Databases.

**Comment by smartguest** [comment]
Closing as duplicate

**Comment by alanrenmsft** [comment]
@nathangmahler1987 please try it again when the new version is available in a month or so.

**Comment by nathangmahler1987** [comment]
Thanks!
