### ISSUE TITLE
Dashboard fails to render list of objects after returning to tab

### ISSUE THREAD

**Issue by AdrianoHebreu** [microsoft/azuredatastudio#20564]
Issue Type: <b>Bug</b>

When executing a query or edit data, when returning to the tab where the tables list does not appear.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.71GB (8.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.4.0
azdata-sanddance|msr|3.3.0

</details>

**Comment by alanrenmsft** [comment]
@AdrianoHebreu could you please add some screenshots or GIFs (even better)?

**Comment by AdrianoHebreu** [comment]
![AzureDB](https://user-images.githubusercontent.com/34030593/189237055-bd17aa2c-4974-43cd-8fc2-98247131fe62.gif)

Follow the gif with the problem.
