### ISSUE TITLE
Cannot change language mode on unsaved queries

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#2059]
Issue Type: <b>Bug</b>

If I create a new file and want to change it from .sql to something else like .md, changing the language mode appears to be unsupported.

![change language](https://user-images.githubusercontent.com/8250560/43292674-41f66ace-90eb-11e8-9c0f-12442ae4997c.gif)

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (3.36GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1
vsliveshare|ms-|0.3.472

</details>

**Comment by kburtram** [comment]
This was "by design" to avoid issues encountered when switching from a query editor to a normal editor.  The suggested workflow was to use "New File" instead of "New Query" to get a non-SQL file.  It looks like in current builds we can switch a query editor to another file type but then the editor gets into a bad state.  I'll open a new issue for that regression.
