### ISSUE TITLE
Select Top 1000 not working for Azure Synapse Analytics

### ISSUE THREAD

**Issue by AndrewMorris-scsu** [microsoft/azuredatastudio#20599]
Issue Type: <b>Bug</b>

Right click on a table and click "Select Top 1000" for an azure synapse analytics connection does not work. 

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (16.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.4.0
dotnet-interactive-vscode|ms-|1.0.3255010
jupyter|ms-|2021.8.1046824664
sql-prompt|Red|0.2.11
vim|vsc|1.23.2

</details>

**Comment by Charles-Gagnon** [comment]
@AndrewMorris-scsu Which tree is this from - the Azure one?

@smartguest FYI - likely related to the fix you're already doing for correcting the endpoint used

**Comment by cheenamalhotra** [comment]
It seems the user is able to connect, since they are able to right click on the table. 

Selecting table data is somehow not working possibly due to a large dataset? 
@AndrewMorris-scsu would appreciate more details about the table structure and estimated data size. Does no table work for you or a particular table?

**Comment by alanrenmsft** [comment]
please share the data requested and we will reopen the issue and investigate.
