### ISSUE TITLE
Cannot see General folder after adding Azure SQL Migration ext.

### ISSUE THREAD

**Issue by prhodesbajaj** [microsoft/azuredatastudio#20600]
Issue Type: <b>Bug</b>

Downloaded Azure Data Studio
Connected to an Azure database
Added the extension Azure SQL Migration
Unable to view the extension under the Home panel
I figured it out.  I needed to be connected to the onprem db.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.17763
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7452 32-Core Processor                 (4 x 2346)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
![ADS Home Page](https://user-images.githubusercontent.com/63602203/189979230-16f2fba9-571a-47cd-af2a-06d96ace1fbf.PNG)

|Memory (System)|32.00GB (18.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-migration|Mic|1.0.4

</details>

**Comment by Charles-Gagnon** [comment]
@prhodesbajaj You mentioned you figured it out - do you still have an issue that should be investigated or can we close this?

**Comment by prhodesbajaj** [comment]
You may close the ticket.  Thanks,
Patti




Upcoming PTO:

Wednesday, October 12 thru Friday October 14


Holiday Schedule:

  Thursday, November 24, 2022

  Friday, November 25, 2022 Friday, December 23, 2022

  Monday, December 26, 2022 Monday, January 2, 2023

Patti Rhodes | Senior SQL Developer

 [cid:ad4114e9-bfc1-4f3b-a0cf-3b70be9f8fd2]
m: 954.649.7801  |  o: 954.602.0618
***@***.******@***.***>
340bplus.com<http://340bplus.com/>  |  LinkedIn<https://www.linkedin.com/company/rxstrategiesinc-?trk=tyah&trkInfo=clickedVertical%3Acompany%2Cidx%3A2-1-2%2CtarId%3A1433444475163%2Ctas%3Arxstra>  |  Twitter<https://twitter.com/340BPlus>


________________________________
