### ISSUE TITLE
A11y_SQLMigrationControlPlane_ AssessmentResultsAndRecommendations_View/SelectButton_Keyboard: Keyboard focus is going over non-interactive text

### ISSUE THREAD

**Issue by BhanuPrakashGit** [microsoft/azuredatastudio#20627]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11yMAS;#A11yTCS;#AzureDataStudioextension'AzureSQLMigration'-Mac-Sept2022;#SQL Migration Control Plane;#A11ySev2;#WCAG2.1.1;#DesktopApp;#Win11;#ScreenReader;#Benchmark;#VoiceOver;#Mac

### Environment Details:
Azure Data Studio: Version: 1.39.1
Operating System: Mac Version 12.5.1

### Steps to Reproduce:

1. Install Azure data studio and open
2. Tab till Extension press enter key and install Azure SQL Migration 
3. Tab till Respective server and right click
4. Tab till manage and press enter key
5. Tab till Azure SQL Migration and press enter key
6. Tab till migrate to azure sql and press enter key
7. Saved session page will open 
8. Select start new session and give next
9. Databases for assessment page will open 
10. Select the respective databases and give next 
11. Assessment results and recommendations page will open
12. Select Azure SQL managed Instance /Virtual Machinesfrom Azure SQL Target
13. Tab till View/Select button, assessment results for '<server-name>' dialog will open	
14. Observe that keyboard focus is going over the non-interactive text.

### Actual:
Keyboard focus is going over non-interactive text

### Expected:
Keyboard focus should not go over non-interactive text

### User Impact:
Keyboard users will get confused with focus going over the non-interactive text.
[Screen Recording 2022-09-14 at 3.41.00 PM.zip](https://github.com/microsoft/azuredatastudio/files/9607118/Screen.Recording.2022-09-14.at.3.41.00.PM.zip)

**Comment by aasimkhan30** [comment]
@BhanuPrakashGit , the impacted objects table is an interactive component in the screen. In case there are multiple impacted objects, the user need to tab through them to select it.

**Comment by aasimkhan30** [comment]
![azuredatastudio_rpgXVPLuNm](https://user-images.githubusercontent.com/6816294/193667863-af1d93f3-5c7a-4a5a-bf7a-563b07c0fb07.gif)

**Comment by BhanuPrakashGit** [comment]
As per the above comment, "In case there are multiple impacted objects, the user needs to tab through them to select it." Hence closing the bug.

**Comment by InduPriya1805** [comment]
Githubtags:  #AzureDataStudioextensionAzureSQLMigration-Mac-Sept2022;

**Comment by BhanuPrakashGit** [comment]
Githubtags: #Closed;
