### ISSUE TITLE
Schema compare - file not found

### ISSUE THREAD

**Issue by Econ808** [microsoft/azuredatastudio#20646]
- Azure Data Studio Version: 1.39.1
- OS Version: Windows 10

When doing a schema compare with a file which include "@" in the name the schema compare fails:

![image](https://user-images.githubusercontent.com/36441764/191754663-dafd57ff-2d73-4d38-ad60-0595c49bc9b9.png)

Steps to Reproduce:

1. Have file in security which includes "@" in filename
2. Do schema compare

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
Might be similar to https://github.com/microsoft/azuredatastudio/issues/17020. Can you try find-replacing `%40`s that should be `@` in the sqlproj? This updated project should continue to work in SSDT and will be read correctly in ADS.

**Comment by Econ808** [comment]
Okay, that works. Thanks.
