### ISSUE TITLE
Schema Compare failed to apply when creating a new empty schema with a "DOMAIN\User"

### ISSUE THREAD

**Issue by lucasmarotta** [microsoft/azuredatastudio#20648]
- Azure Data Studio Version: 1.39.1
- OS Version: Windows 10 (21H2)

Steps to Reproduce:

1. Create a database project of your database.
2. Create a new schema with a pattern "DOMAIN\User", like "Contoso\Lucas", directly, without touching the database project.
3. Update the database project with Schema Compare.

When creating a new project is not the problem, the problem is when applying the new created schema, through schema compare. First I don't like the usage of a pattern "DOMAIN\User" as a schema, but I was dealing with an legacy database, so that happened. Secondly, when was trying to apply the error message was "Could not find part of path <folder of my project>\Domain\User\Schemas\Domain\User.sql". The folder "\Domain\User\Schemas" was there, but I imagine the character "\\" on the schema was the cause of the error.

Does this issue occur when all extensions are disabled?: Not applied (since Schema Compare is a built-in extension)

**Comment by kisantia** [comment]
When creating a project from db in SSDT for a db with a schema in this format, it creates the file name as domain_user.sql. We need to update the DacFx to do something similar for ADS sql projects.

**Comment by kisantia** [comment]
This is fixed in DacFx so that slashes and backslashes get replaced with an underscore in the file name. This will be brought into ADS the next time DacFx gets updated before the next release.
