### ISSUE TITLE
SQL Agent Scrolling

### ISSUE THREAD

**Issue by DianGermishuizen** [Microsoft/azuredatastudio#2064]
Issue Type: <b>Bug</b>

Used SQL Agent extension, but job steps dont fully show, only about 10 are showing. Additionally, you can only scroll down the list of steps once, then it doesnt allow you to scroll back up or down.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: unavailable_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>vpx_decode: unavailable_software<br>webgl: unavailable_off<br>webgl2: unavailable_off|
|Memory (System)|15.90GB (8.61GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.2
whoisactive|Mic|0.1.1
sql-search|Red|0.1.1

</details>

**Comment by kburtram** [comment]
@abist let's try to get this one fixed for August since it impacts our basic "View Job" scenario.
