### ISSUE TITLE
error when split screen

### ISSUE THREAD

**Issue by copycatcode** [microsoft/azuredatastudio#20642]
Issue Type: <b>Bug</b>

If i use a split screen, an error such as the right mouse not working on the database management screen will occur.
For example, if you search for a procedure and right-click, nothing will appear.
Please make the operation smooth when splitting the screen.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (7.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
ads-language-pack-ko|Mic|1.39.0
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
query-history|Mic|0.4.0

</details>

**Comment by alanrenmsft** [comment]
@copycatcode  could you please add a gif or screenshot demonstrating the problem?

**Comment by cheenamalhotra** [comment]
Closing as we don't have enough information to investigate the problem. If you continue to face issues, please upload more details as requested along with error captured in logs.
