### ISSUE TITLE
A11y_SQLMigrationControlPlane_ MigrateToAzureSQL_DatabasesForAssessment_Keyboard: Keyboard focus is incorrect for the table.

### ISSUE THREAD

**Issue by BhanuPrakashGit** [microsoft/azuredatastudio#20652]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11yMAS;#A11yTCS;#AzureDataStudioextension'AzureSQLMigration'-Mac-Sept2022;#SQL Migration Control Plane;#A11ySev2;#WCAG2.4.3;#DesktopApp;#Win11;#Keyboard;#Benchmark;#VoiceOver;#Mac

### Environment Details:
Azure Data Studio: Version: 1.39.1
Operating System: Mac Version 12.5.1

### Steps to Reproduce:

1. Install Azure data studio and open
2. Tab till Extension press enter key and install Azure SQL Migration 
3. Tab till Respective server and right click
4. Tab till manage and press enter key
5. Tab till Azure SQL Migration and press enter key
6. Tab till migrate to azure SQL and press enter, saved session page will open 
7. Select start new session and give next, Databases for assessment page will open
8. Observe that Keyboard focus is incorrect for the table.

### Actual:
Keyboard focus is incorrect for the table. Focus is not going over the first checkbox present on the table.

### Expected:
Keyboard focus is incorrect for the table. Focus should go over the first checkbox present on the header of the table.

### User Impact:
Keyboard user will not get confused while navigating.
[Screen Recording 2022-09-15 at 11.25.54 AM.zip](https://github.com/microsoft/azuredatastudio/files/9632844/Screen.Recording.2022-09-15.at.11.25.54.AM.zip)

**Comment by aasimkhan30** [comment]
@BhanuPrakashGit, this bug is fixed in the latest insiders of ADS. Can you please give it a try and close the issue.

**Comment by BhanuPrakashGit** [comment]
Verified the bug in the latest insiders of ADS. Issue is fixed and does not repro. Hence closing the bug. PFA for reference
[Screen Recording 2022-12-19 at 12.31.25 PM.zip](https://github.com/microsoft/azuredatastudio/files/10257839/Screen.Recording.2022-12-19.at.12.31.25.PM.zip)

**Comment by InduPriya1805** [comment]
Githubtags:  #AzureDataStudioextensionAzureSQLMigration-Mac-Sept2022

**Comment by BhanuPrakashGit** [comment]
Githubtags: #Closed;
