### ISSUE TITLE
Connection Problems

### ISSUE THREAD

**Issue by BahadirSoybakis** [microsoft/azuredatastudio#20654]
Issue Type: <b>Bug</b>

Hi All,

When I start using Azure, I met some connection problems. (SSMS to Azure) I execute prosedure or functions to finish but its delay. Its just need to finish in 1 min SQL script that takes long time to finish. When I look SSMS , application more dynamic and stable but Azure still has connection problems and less user interface features...

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 3500U with Radeon Vega Mobile Gfx   (8 x 2096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|9.88GB (1.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.49.0
profiler|Mic|0.11.0
azdata-sanddance|msr|4.0.0

</details>

**Comment by alanrenmsft** [comment]
@BahadirSoybakis could you please share more details with us? e.g. are you running into errors connecting to servers/databases?

**Comment by cheenamalhotra** [comment]
@BahadirSoybakis 

> Database connections are broken when I view job processes on the Azure side. 
This issue has been addressed in latest stable release v1.41.

Do you still have any remaining concerns with latest version of ADS?

**Comment by cheenamalhotra** [comment]
Closing as no further info available.
