### ISSUE TITLE
Missing index en plan de ejecución

### ISSUE THREAD

**Issue by sanpepo** [microsoft/azuredatastudio#20676]
Issue Type: <b>Bug</b>

Las recomendaciones de índices para los palnes de ejecución se generan mal
En included columns añade la columna del índice
Faltan columns que añadir en includen columns.

Es fácil detectar si se compara con las recomendaciones de SSMS

_Translation:_ 
> _The index recommendations for execution plans are incorrect. In included columns add an index column. There are missing columns that should be included._
> 
> _It's easy to see, if you compare these recommendations with the recommendations in SSMS._

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (0.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.49.0
azuremonitor|Mic|0.1.4

</details>

**Comment by lewis-sanchez** [comment]
Hola @sanpepo, podria incluir un imagen de lo que se refiere por favor, para poder mejor ayudarle? Gracias!

**Comment by sanpepo** [comment]
![Captura](https://user-images.githubusercontent.com/114484380/194078633-d7e1ec9d-7c0b-4577-a8e9-29979a59d1cf.PNG)

**Comment by erinstellato-ms** [comment]
@sanpepo  Gracias por registrar este problema.  Para su información, estoy cerrando esto como un duplicado de https://github.com/microsoft/azuredatastudio/issues/20249. Estoy enlazando a este tema desde el otro para que su información esté disponible si es necesario.  Siéntase libre de votar a favor de ese tema (la votación positiva y los comentarios nos ayudan a determinar la prioridad), ¡gracias!
