### ISSUE TITLE
SQL Agent UX - Prioritize current detail job view

### ISSUE THREAD

**Issue by Tarig0** [Microsoft/azuredatastudio#2067]
- SQL Operations Studio Version: 0.31.4
- SQL Server Agent: 0.31.4

Steps to Reproduce: 
1. Have a database with many jobs.
2. Open a job and view it

Information won't be push to the top of the queue of job info requests.

**Comment by abist** [comment]
@Tarig0 Hi, can you please clarify a bit more about the bug? Do you mean the jobs don't refresh for you or you can't view the full list of jobs?

**Comment by Tarig0** [comment]
The history information doesn't seem to come in, waited for 2-3 minutes then backed out to the list view. My guess its just an issue with the order the jobs are queried, and the order doesn't change when the user drills down into a report.

**Comment by abist** [comment]
@Tarig0 You can try refreshing the view by using the refresh button in the top right of the dashboard. We are currently working to automatically refresh the jobs and histories.

**Comment by kburtram** [comment]
This should be fixed in the latest release.  Please let me know if the problem persists.

**Comment by Tarig0** [comment]
I think this is still in the latest insider and latest extension I believe the isuue #3333 may be a another symptom of this.
