### ISSUE TITLE
Keychain Keeps Asking Me For Password

### ISSUE THREAD

**Issue by josh-rathke** [microsoft/azuredatastudio#20693]
Issue Type: <b>Bug</b>

When I open Azure Data Studio, it asks me to enter my keychain password. After I do this, I click Always Allow. However, this does not work. Often, the next time I open Azure Data Studio, it asks for my password again. Sometimes upon opening Azure Data Studio it asks for my keychain password multiple times before I can actually use the application. The Always Allow button seems to do nothing, which is quite annoying.

Azure Data Studio version: azuredatastudio 1.36.2 (2299a76973585fa962cfd06e8acab4abb41567de, 2022-05-19T04:10:47.073Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @josh-rathke 

Since we have an open issue #19269 with the same concern, I will close this as a duplicate. 
You may follow the original issue for future progress and updates.
