### ISSUE TITLE
Option to set default transaction isolation level

### ISSUE THREAD

**Issue by nickajordan** [microsoft/azuredatastudio#207]
- SQL Operations Studio Version: 0.23.6

It would be very useful to be able to set a default transaction isolation level, as you can in SSMS. Having to ensure I have 'set transaction isolation level read uncommitted' at the top of every query I write is rather tedious!

**Comment by kburtram** [comment]
This is available in the current insiders builds and will ship in the June release.

**Comment by nickajordan** [comment]
Thank you for this and for all your continuing hard work.
