### ISSUE TITLE
Can't connect with Azure AD account on 2nd computer

### ISSUE THREAD

**Issue by Lukydemboy** [microsoft/azuredatastudio#20707]
Issue Type: <b>Bug</b>

issue Type: Bug
1. Download Azure Data Studio, connect with Azure AD account (Mac).
2. Take a 2nd computer (both are Mac in my case).
3. Sign in with the same Azure AD account and try connecting. Login failed for user ‘\<token-identified principal\>’.

https://www.loom.com/share/09ce8e33d6724588b2a8c1f778bd1d92

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 21.3.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @Lukydemboy 

The computer that you logged in to, did you connect to a particular database or master? If it was a database, can you provide the same database name by typing it in the Database input box and try again? Otherwise, can you confirm you have access to master database from your first computer too?

**Comment by Lukydemboy** [comment]
Hi @cheenamalhotra

Tried connecting to both, the master and a particular database, both throw the same error. I can confirm that I can still connect to the database on the first computer (using the same procedure as shown in the Loom video).

**Comment by cheenamalhotra** [comment]
Before gathering logs, please:
* Clean token cache by running: **Command Palette > Azure Accounts: Clear Azure Account Token Cache**.
* Remove all accounts by running: **Command Palette > Clear all saved accounts**.

Thanks!

**Comment by cheenamalhotra** [comment]
Hi @Lukydemboy 

Following up, do you have Logs we can look into, or you were able to resolve issue?

**Comment by cheenamalhotra** [comment]
Closing as inactive
