### ISSUE TITLE
Accounts pane shows different icons for same account

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#20701]
- Azure Data Studio Version: 1.39.1
- OS Version: MacOs Monterey 12.6

Steps to Reproduce:

1. Add Account to Accounts pane
2. Sometimes it has the Microsoft logo, sometimes it has a different logo
<img width="500" alt="Screen Shot 2022-09-30 at 2 58 03 PM" src="https://user-images.githubusercontent.com/18150417/193338979-19d17302-e7e4-4a34-852c-e55045bf89fe.png">
<img width="500" alt="Screen Shot 2022-09-30 at 2 59 20 PM" src="https://user-images.githubusercontent.com/18150417/193338981-feb5b4bf-ab3d-4560-929e-b792759055f1.png">

Does this issue occur when all extensions are disabled?: N/A

**Comment by cheenamalhotra** [comment]
Same issue leads to multiple entries of same Azure account:
![image](https://user-images.githubusercontent.com/13396919/199620247-4bbc75b4-c2fe-406a-8b3c-56114f6b725e.png)
