### ISSUE TITLE
Trying to add or view extensions causes json error

### ISSUE THREAD

**Issue by godbrain** [Microsoft/azuredatastudio#2070]
Issue Type: <b>Bug</b>

Example is @recommended shows error and nothing shows

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.69GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![image](https://user-images.githubusercontent.com/16495226/43327535-4d90f85e-9181-11e8-9180-5d9eaac5b5c4.png)

**Comment by kburtram** [comment]
@godbrain I wasn't able to repro this.  Are you still hitting this issue?

**Comment by godbrain** [comment]
Yes , still doing this after the latest update. Was working fine before. restarted it etc. I'll try reinstalling though.

**Comment by kburtram** [comment]
@godbrain thanks for confirming!  Could you please check if there are any error messages in the `Help->Developer Tools` Console window?  I'll try to get an internal repro.

**Comment by godbrain** [comment]
![image](https://user-images.githubusercontent.com/16495226/43346888-ab29847c-91b8-11e8-9efb-b67ccf6504e3.png)

C:\Program Files\SQL Operations Studio\resources\app\node_modules\zone.js\dist\zone-node.js

**Comment by alanrenmsft** [comment]
I am going through the extension manager issues, seems the issue described here no longer exists on March release. closing the issue.
