### ISSUE TITLE
Unable to Export Data

### ISSUE THREAD

**Issue by calgrainger1990** [microsoft/azuredatastudio#20727]
**Kernel:**  5.10.131-19114-g6651b07c6153 #1 SMP PREEMPT Thu Sep 1 19:07:41 PDT 2022 x86_64 GNU/Linux, (debian)
**Azure Data Studio Version:** Azure Data Studio build Version: 1.39.1
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T00:59:13.108Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.131-19114-g6651b07c6153

I am unable to export any data after running my queries. When attempting to export to excel, JSON, CSV, text etc the app freezes and then i get a message saying that my connection(s) got disposed...

This happens everytime and regardless of the build of debin/ads i am running.

The only additional application I have running in relation to and conjunction with Azure data studio is gnome-keyring as this is the only way i can securly access my connections.

Please refer to the attached data.

Cal

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T00:59:13.108Z)
OS version: Linux x64 5.10.131-19114-g6651b07c6153
Restricted Mode: No

**Comment by alanrenmsft** [comment]
@caohai could you please give it a try on Linux?

**Comment by caohai** [comment]
> This happens everytime and regardless of the build of debin/ads i

@alanrenmsft I just tried "Save to CSV" from query result on my Ubuntu 20.04 machine and it's working fine.

![image](https://user-images.githubusercontent.com/21186993/195190075-2073254d-a1f1-451f-951c-f45041d1c69c.png)

**Comment by alanrenmsft** [comment]
@caohai could you please set up a Debian VM and try on it?

**Comment by caohai** [comment]
@alanrenmsft I tested on Debian 11 and it's working fine for me.
![image](https://user-images.githubusercontent.com/21186993/195417115-4e1deb8d-f55f-44fb-912b-87b901d5d4c8.png)

**Comment by alanrenmsft** [comment]
need more information in order to proceed, will reopen once we get the required information.
