### ISSUE TITLE
Unable to authenticate Azure AD on both new Azure Data Studio install and old

### ISSUE THREAD

**Issue by Knuffa** [microsoft/azuredatastudio#20730]
Issue Type: <b>Bug</b>

On my old install, where I had previously validated my Azure AD:
- Attempt to link Azure AD account by selecting the Accounts icon on the right-hand panel. See "Azure" and my old Corp account show up. Am told, "You need to refresh the credentials for this account."
- When I attempt to authenticate my Azure AD account (both through Azure Auth Code Grant or Azure Auth Device Code) neither seem to get my authentication back onto Data Studio.
- It appears, from my mysignins.microsoft.com page, that I have a successful verification, but this verification doesn't post to my local Azure Data Studio.

On my new install, on a separate computer, I encountered similar issues (it seems that the web verification doesn't redirect back to Azure Data Studio, appropriately... it seems, instead, trying to be calling vscode?)

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.39GB (11.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuremonitor|Mic|0.1.4
kusto|Mic|0.5.4

</details>

**Comment by cheenamalhotra** [comment]
Hi @Knuffa 

Could you test the same with Insiders build and let us know if you experience same behavior or solves issue?
You can download latest insiders build from here: [Try out the latest Insiders build from main](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)

**Comment by Knuffa** [comment]
Hi @cheenamalhotra , thanks for your speedy reply.

I installed the latest Data Studio Insiders build and this did not resolve the problem. On the stable build, attempting to link an account opened up an Edge window (Edge is my default browser). On the Insiders build, when I attempt to add an account, a notification shows up saying "Adding account..." but no browser is opened or is it apparent an authentication process has started.

> Also can you share with which version of ADS did AAD login work before for you?

I was/am on ADS 1.39.1 when AAD login worked for me.

**Comment by cheenamalhotra** [comment]
Hi @Knuffa

Could you try the following:
1. Command Palette > Azure Accounts: Clear Azure Account Token Cache
2. Command Palette > Clear all saved accounts
3. Command Palette > Developer: Reload Window
4. Try adding a new Azure account

Let us know if you still have problem signing in to add a new Azure Account.

**Comment by Knuffa** [comment]
Hi @cheenamalhotra -- That worked, thank you! Do you mind if I ask why that worked?

**Comment by cheenamalhotra** [comment]
Sometimes stale account caches can cause ADS to load inconsistent data, so cleaning up caches/accounts comes handy tool in times like these :)
