### ISSUE TITLE
Firewall Rule Dialog support for MySQL Extension

### ISSUE THREAD

**Issue by rishky-msft** [microsoft/azuredatastudio#20754]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by alanrenmsft** [comment]
ADS provides a generic firewall rule handling experience, to leverage it for your extension, you need to register a resource provider in your extension by calling the `azdata.resources.registerResourceProvider()` method: https://github.com/microsoft/azuredatastudio/blob/5f8cefc45c46c66625cfae5b83886c85ce6c172f/src/sql/azdata.d.ts#L2638

example of mssql extension using this API:
https://github.com/microsoft/azuredatastudio/blob/9516472f1b537d6618ee26778bf339252e692a7a/extensions/mssql/src/resourceProvider/resourceProvider.ts#L38
