### ISSUE TITLE
Extensibility: Add API for creating new connection to use with queryeditor.connect()

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#2075]
When opening a query in a query editor, there doesn't seem to be any way to change the target database besides having a USE statement in the query. queryeditor.connect() only takes the connection id of an existing connection, and the extension APIs don't seem to have any mechanism for creating a new connection to a different database.

**Comment by kburtram** [comment]
Closing old tasks.  Please track this in the context of an extension under active development.
