### ISSUE TITLE
Session not initializing after creating new session

### ISSUE THREAD

**Issue by JohnnySanabria** [microsoft/azuredatastudio#20767]
Issue Type: <b>Bug</b>

I've launched the Profiler and now I simply need to start the session, but there is nothing to select in the "Select Session" dropdown. No matter how many sessions I create, none of them are available and the session is unable to start. There are no visible errors, it simply doesn't work.

Extension version: 0.11.0
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

![image](https://user-images.githubusercontent.com/107206758/194623142-3cbfdb21-9c0d-4422-aa16-1241710532f4.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 2400G with Radeon Vega Graphics     (8 x 3593)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|13.93GB (4.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment]
what type of sql server are you connecting to just normal Azure SQL Database?

**Comment by alanrenmsft** [comment]
will reopen once we have the requested information.

**Comment by Chahk42** [comment]
Same issue.  Connecting to Azure SQL Database.  Here's the console log of what happens when I try to click on the Session dropdown:
![image](https://user-images.githubusercontent.com/116903311/198678123-3022e1ac-8943-46a2-a820-62a3d3fd38d2.png)
