### ISSUE TITLE
A11y_Azure Data Studio_Toolbar_Properties_ScreenReader: The screen reader is not announcing the expanded/Collapsed state of the row.

### ISSUE THREAD

**Issue by Truptik12** [microsoft/azuredatastudio#20783]
### Actual:
The screen reader is not announcing the expanded/Collapsed state of the row.

### Expected Result:
The screen reader shoukd announce the expanded/Collapsed state of the row.

### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #SQL Azure Data Studio; #SH-SQL Azure Data Studio-Win32-OCT2022; #DesktopApp; #NVDA; #WCAG1.31; #FTP;

### Environment Details:
Application Name: Azure Data Studio
Windows Version: Windows 11

### Repro Steps:

1. Launch the "Azure data studio" application.
2. Connect with the provided "sqltools2019-3" SQL server.
3. TAB to "New Query" button and hit ENTER key.
4. Enter the SQL query and TAB to "Estimated Plan" button and hit ENTER key.
5. "Query Plan (Preview) screen appear.
6. TAB to the toolbar present at right side of the screen.
7. TAB to "Properties" button and hit ENTER key.
8. Turn on the screen reader and observe the issue.

### Attachment:
![Screen Recording (7)](https://user-images.githubusercontent.com/86710491/194822053-8a79ec55-67b9-41e8-b452-973bd6e1e51f.gif)

**Comment by aasimkhan30** [comment]
@Truptik12, this is fixed in the latest insiders. Can you please re test and close this issue?

**Comment by Truptik12** [comment]
Verified the bug in the below environment
Version: 1.40.0-insider (user setup)
Commit: https://github.com/microsoft/azuredatastudio/commit/d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:45:47.459Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621
The bug does not repro. Hence closing the bug. Please find the screenshot below.

![20783](https://user-images.githubusercontent.com/86710491/197972078-6bf16dce-7a44-4039-bc2c-a7269dc40cd5.png)
