### ISSUE TITLE
Unable to locate SQLCMD mode after a recent update.

### ISSUE THREAD

**Issue by cyberguyvk** [microsoft/azuredatastudio#20799]
Issue Type: <b>Bug</b>

Not sure how, but after a recent ADS update, the SQLCMD mode is not visible.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
cms|Mic|0.8.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0
schema-compare|Mic|1.16.0

</details>

**Comment by Charles-Gagnon** [comment]
Do you have preview features enabled?

![image](https://user-images.githubusercontent.com/28519865/194997512-4a7d8c70-7467-462d-b452-154c937f4f0f.png)

**Comment by cyberguyvk** [comment]
I have. I am able to even see and use all the Preview extensions. But not able to see this.

**Comment by Charles-Gagnon** [comment]
Can you take a screenshot of what the editor toolbar looks like? e.g. 

![image](https://user-images.githubusercontent.com/28519865/195130219-62c4dc70-d12d-48ba-92f3-866241bd5214.png)

**Comment by alanrenmsft** [comment]
Will reopen once we have the requested information in order to proceed.
