### ISSUE TITLE
Extensibility/Bug: User has to click outside a component for the onDataChanged() event to be fired for it

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#2080]
Editing data on a textbox, editable dropdowns within tables don't cause the onDataChanged() event to be fired for them unless the user clicks outside of them.

**Comment by aaomidi** [comment]
Maybe another event here makes sense? onCharacterEntered?

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impacting an extension under active development.
