### ISSUE TITLE
Query results grid hyperlinks random text

### ISSUE THREAD

**Issue by timothyhoffmann** [microsoft/azuredatastudio#20819]
Issue Type: <b>Bug</b>

ADS seems to think (....) syntax is a hyperlink so if I click on the cell to select the text I get jumped to a new tab.

![image](https://user-images.githubusercontent.com/28546239/195384112-24f1271b-a6bf-4e5b-b3ce-215b1ba05282.png)

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.68GB (10.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
extra-sql-script-as|pac|0.5.0

</details>

**Comment by alanrenmsft** [comment]
it is actually the `{}` that made ADS think it is a json string, clicking the cell will open a new tab with the cell content formatted as JSON.

**Comment by alanrenmsft** [comment]
we can try to improve the regex to detect JSON strings.

**Comment by timothyhoffmann** [comment]
Thanks, these are string.format style text values.
