### ISSUE TITLE
Notebook Jobs UI does not render

### ISSUE THREAD

**Issue by sqlworldwide** [microsoft/azuredatastudio#20822]
Issue Type: <b>Bug</b>

When I click the "New Notebook Job" button, the form is empty with two buttons at the bottom. Those two buttons are Ok and Cancel.

Extension version: 0.49.0
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.60GB (2.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

![Screenshot 2022-10-12 144321](https://user-images.githubusercontent.com/26484126/195423001-a544a6d2-8f48-43f1-a3c6-9e6351b901f7.png)

**Comment by sqlworldwide** [comment]
I downloaded an older version .37, and it works fine there. Meaning some recent changes broke this functionality.

**Comment by alanrenmsft** [comment]
@sqlworldwide the issue has been fixed now, the fix will be included in the December release.

**Comment by sqlworldwide** [comment]
Thank you
