### ISSUE TITLE
You can't drag/drop columns/tables to query window

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#2083]
- SQL Operations Studio Version: Version 0.31.4
Commit e026ab85a72c190cc4ccc834503aa9fe36dd6407
Date 2018-07-18T02:14:21.826Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

- On the list of servers expand a SQL instance to the table level
- Try to drag/drop a table name, columns folder or individual column to a query window - nothing happens. In SQL Server Management Studio it would insert the table name, all column names comma separated or the individual column respectively.

I'm liking SQL Operations Studio over Management Studio purely because MS has bothered to finish dark mode, unlike the latter where you have to hack the config file to enable it and it's only 90% finished - perhaps this is why, but in order to use it full time it needs to have feature parity with Management Studio. I've only just started using it and have not done so in anger yet, but these little quality of life pieces of functionality are important.

**Comment by johnmart82** [comment]
I just wanted to add my voice to this feature request. As someone who is just coming to ADS from SSMS this is a feature that I used a lot to shortcut to writing queries, especially insert statements.

Thanks

**Comment by JASM2007** [comment]
I agree this is one of those things that users from SSMS would expect in Azure Data Studio it just makes things faster and easier. Intellisense can only do so much. Sometimes you just want to drag and drop as it's right there in front of you.  I have coworkers that have been bothered by not having this feature as well. I told them to file a feature request but then I found this one. I am sure there are many people would find this feature one of the last steps to move over from SSMS.

**Comment by ThatWionGuy** [comment]
Adding my approval as well since it has been a few months without any updates.  Drag and Drop of SQL objects is definitely a feature I miss since the switch from SSMS.

**Comment by kburtram** [comment]
@peterlukerow thanks for reporting this issue!  We are tracking this enhancement with issue https://github.com/microsoft/azuredatastudio/issues/296.  We plan to address this gap in an upcoming release.

**Comment by peterlukerow** [comment]
Fingers crossed this makes it into the April milestone as I note in the March milestone being in one doesn't mean it's going to get done. March has over 100 issues but only 32 are closed.
