### ISSUE TITLE
Select top 1000 do not run

### ISSUE THREAD

**Issue by raycelgraterol** [microsoft/azuredatastudio#20831]
Issue Type: <b>Bug</b>

When I click "Select top 1000" in rigth click of the table the select do not performance do not run 

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-1005G1 CPU @ 1.20GHz (4 x 1190)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.80GB (0.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
@raycelgraterol this appears to be a known issue, https://github.com/microsoft/azuredatastudio/issues/20551.
You may close this one and follow updates on the existing one :)

**Comment by cheenamalhotra** [comment]
Closing as duplicate
