### ISSUE TITLE
Create table fails for Azure Synapse non-master database

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#20839]
![image](https://user-images.githubusercontent.com/13777222/195673575-afa80f23-8a53-4356-89c5-8161e2b10c19.png)

this is due to the limitation listed here:
https://learn.microsoft.com/en-us/azure/synapse-analytics/sql-data-warehouse/sql-data-warehouse-develop-transactions#limitations

update the table designer to disable transaction support for Azure Synapse database, also similar to the memory-optimized table, add a warning about transaction support not availab.e

**Comment by cheenamalhotra** [comment]
Regular tables would work in a dedicated SQL Pool, so you may try that. 
Serverless SQL Pool provides limited data storage support.
Reference: https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/develop-tables-overview

**Comment by caohai** [comment]
Fixed
