### ISSUE TITLE
Unable to build my project due to missing assemblies after installing .net core 3.1.424

### ISSUE THREAD

**Issue by wapayne69** [microsoft/azuredatastudio#20833]
Issue Type: <b>Bug</b>

 
After installing .net core 3.1.424 sdk as per documented requirements. I am still unable to build my database project (there are also no other versions of .net on this machine).

I had to jump through a lot of infosec hoops just to get someone with admin permissions to install this on my laptop. Before I go through the whole process again, can someone please tell me exactly what else needs to be installed from a .net point of view?

    stdout: C:\Program Files\dotnet\sdk\3.1.424\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at [https://aka.ms/msbuild/developerpacks](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fmsbuild%2Fdeveloperpacks&data=05%7C01%7Cwaylon.payne%40microsoft.com%7C526469bcc6ca40af6b6108daace681dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638012403300296656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JLl8O9kiwivkWsQS1T%2FPsYWv0lk5kyGG2%2Br4Z0mZprE%3D&reserved=0)

    stdout:

    stdout:

    stdout: Build FAILED.

    stdout:

    stdout: C:\Program Files\dotnet\sdk\3.1.424\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at [https://aka.ms/msbuild/developerpacks](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2Fmsbuild%2Fdeveloperpacks&data=05%7C01%7Cwaylon.payne%40microsoft.com%7C526469bcc6ca40af6b6108daace681dd%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638012403300296656%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JLl8O9kiwivkWsQS1T%2FPsYWv0lk5kyGG2%2Br4Z0mZprE%3D&reserved=0)

    stdout:     0 Warning(s)

 

Extension version: 0.19.0

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)

OS version: Windows_NT x64 10.0.19042

Restricted Mode: No

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|

|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|

|Load (avg)|undefined|

|Memory (System)|31.39GB (18.81GB free)|

|Process Argv||

|Screen Reader|no|

|VM|0%|

</details>

**Comment by kisantia** [comment]
@wapayne69 It's strange that it's looking for .NETFramework assemblies. Does the project you're trying to build have a target framework specified in the .sqlproj? Can you check if building a new empty project fails?

**Comment by wapayne69** [comment]
So if I create a new project, I don't get the .net errors. If I copy the project with errors to a new location I also don't get .net errors. 

This appears to be related to the fact that my project is git connected?

**Comment by kisantia** [comment]
@SakshiS-harma can you look into it since you might have a repro?

**Comment by SakshiS-harma** [comment]
@wapayne69 did you create this project in SSDT and then imported it to ADS?
You said if you change the location, it builds fine - is this understanding correct?
Also, what is the target framework specified in the .sqlproj?

**Comment by SakshiS-harma** [comment]
@wapayne69 Can you please confirm if "Microsoft.NETFramework.ReferenceAssemblies" package is been referenced in the .sqlproj file?

**Comment by wapayne69** [comment]
This project was created using the Data Studio extension, I don't have SSDT installed on this machine. 

I don't see any reference to "Microsoft.NETFramework.ReferenceAssemblies" in the sqlproj file (is there somewhere else I should be looking?

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>DBNAME</Name>
    <ProjectGuid>{0A8937A1-8414-452B-ACBD-AC8324318096}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
  <ItemGroup>
    <Folder Include="FOLDER\Scripts\" />
  </ItemGroup>
  <ItemGroup>
    <PostDeploy Include="FOLDER\Scripts\postdeploy_CreateLogins.sql" />
  </ItemGroup>
</Project>

**Comment by SakshiS-harma** [comment]
Can you try adding the below line in your sqlproj file under a separate "ItemGroup":
<PackageReference Condition="'$(NetCoreBuild)' == 'true'" Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
and then try building the project? 
Can you also confirm if this package reference exists in your working project?

**Comment by SakshiS-harma** [comment]
@wapayne69 Any update? Can you share your sqlproj file, so that I can take a look at it as well.

**Comment by SakshiS-harma** [comment]
@wapayne69 Just checking back if you have any update on the raised issue.

**Comment by wapayne69** [comment]
Unfortunately still seem to be getting the error with the changes. 

<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build">
  <Sdk Name="Microsoft.Build.Sql" Version="0.1.3-preview" />
  <PropertyGroup>
    <Name>mydb</Name>
    <ProjectGuid>{0A8937A1-8414-452B-ACBD-AC8324318096}</ProjectGuid>
    <DSP>Microsoft.Data.Tools.Schema.Sql.SqlAzureV12DatabaseSchemaProvider</DSP>
    <ModelCollation>1033, CI</ModelCollation>
  </PropertyGroup>
  <Target Name="BeforeBuild">
    <Delete Files="$(BaseIntermediateOutputPath)\project.assets.json" />
  </Target>
  <ItemGroup>
    <Folder Include="folder\Scripts\" />
  </ItemGroup>
  <ItemGroup>
    <PostDeploy Include="folder\Scripts\postdeploy_CreateLogins.sql" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Condition="'$(NetCoreBuild)' == 'true'" Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>
</Project>

    [ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\username\\Documents\\git\\myproject\\SQLDB\\mydb\\mydb.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\username\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.19.0\\BuildDirectory"
    stdout: Microsoft (R) Build Engine version 16.7.3+2f374e28e for .NET
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout:
    stdout:
    stdout:   Determining projects to restore...
    stdout:
    stdout:   All projects are up-to-date for restore.
    stdout:
    stdout: C:\Program Files\dotnet\sdk\3.1.424\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [c:\Users\username\Documents\git\myproject\SQLDB\mydb\mydb.sqlproj]
    stdout:
    stdout:
    stdout: Build FAILED.
    stdout:
    stdout:
    stdout: C:\Program Files\dotnet\sdk\3.1.424\Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.6 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [c:\Users\username\Documents\git\myproject\SQLDB\mydb\mydb.sqlproj]
    stdout:     0 Warning(s)
    stdout:     1 Error(s)
    stdout:
    stdout: Time Elapsed 00:00:00.47
    stdout:
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\username\\Documents\\git\\myproject\\SQLDB\\mydb\\mydb.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\username\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.19.0\\BuildDirectory"    … exited with code: 1
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\username\\Documents\\git\\myproject\\SQLDB\\mydb\\mydb.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\username\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.19.0\\BuildDirectory"   … errored out: Process exited with code 1

**Comment by SakshiS-harma** [comment]
@wapayne69 Do you mind sharing your sqlproj file for further investigation?
Also, is this the only project that has the issue or you haven't been to build any project on your machine ever?

**Comment by wapayne69** [comment]
It’s a customer supplied machine. So this is my first project.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by SakshiS-harma** [comment]
Can you share the project file for further investigation, please?

**Comment by SakshiS-harma** [comment]
This issue hasn't had any recent activity and we are marking it as closed. If you are still experiencing this issue, please reopen this issue.
