### ISSUE TITLE
No context option on a database for backup/restore.

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#2084]
- SQL Operations Studio Version: 0.31.4
Commit e026ab85a72c190cc4ccc834503aa9fe36dd6407
Date 2018-07-18T02:14:21.826Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:

1. On the server explorer, expand to the database level on a SQL instance.
2. Right click on a database, there is no backup/restore option.

For a developer I often do off the cuff backups/restores, having to right click Manage >> restore is an extra step. It seems to be only so that you can display a dashboard for the DB.

It would be better to offer a way to configure which options appear on the context menu for a database. At least that way for those of us that prefer the SSMS way we can configure it to work that way. It's a bit like the way Tortoise SVN let's me config "Show log" to appear on the top left section for Tortoise SVN on the context menu in a folder under source control.

**Comment by udeeshagautam** [comment]
@kburtram, @yualan  This seems fixed for databases inside a server connections. Should we close this?

![image](https://user-images.githubusercontent.com/46980425/58352797-8ad8df00-7e21-11e9-9f34-4b46c17f094b.png)


Note that we don't have this for top level connections - do we need that? suggestions?

![image](https://user-images.githubusercontent.com/46980425/58352775-785ea580-7e21-11e9-94ae-2f683ba04df0.png)

**Comment by udeeshagautam** [comment]
This is fixed as per the above screenshot. Please reactivate if you still see the issue.
