### ISSUE TITLE
How to have a keyboard shortcut to focus the database switcher

### ISSUE THREAD

**Issue by aharpervc** [microsoft/azuredatastudio#20867]
**Is your feature request related to a problem? Please describe.**

I'm always frustrated when I have to click the database switcher with my mouse. I don't know if that's the right name, I mean this...
<img width="452" alt="image" src="https://user-images.githubusercontent.com/441085/196472244-ef085cff-2c7e-4d62-9f64-2900de1010eb.png">

**Describe the solution or feature you'd like**

I'd like to have a keyboard shortcut to put focus on that element, so I can then type the database name I want to switch to.

**Describe alternatives you've considered**

I'm pretty sure this either used to be possible or it could be done with an extension, since that's how my setup used to work. However, all of my settings, saved connections, and extensions were cleared in ADS after an update due for unknown reasons, so I don't have any way to verify that.

**Additional context**

This was a keyboard shortcut in SSMS (`ctrl + u`) and it'd be great to have here as well.

**Comment by aharpervc** [comment]
Possible duplicate: https://github.com/microsoft/azuredatastudio/issues/1187

**Comment by alanrenmsft** [comment]
closing as a dupe.
