### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by vikarBCC** [microsoft/azuredatastudio#20864]
Issue Type: <b>Bug</b>

When a new connection to SQL server database with MFA is attempted the following error message is produced:
TypeError: Cannot read property 'token' of undefined

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (1.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.16.0
sql-database-projects|Mic|0.19.0

</details>

**Comment by vikarBCC** [comment]
Hi, Is there any update on this issue?

**Comment by cheenamalhotra** [comment]
Hi @vikarBCC 

Can you begin by clearing access token cache from ADS by running below commands from Command Prompt:
- Azure Accounts: Clear Azure account token cache
- Clear all saved accounts

Try logging in again and if you still face issues, please gather logs for the failure and share with us.

**Comment by cheenamalhotra** [comment]
This issue should get resolved with insiders build and upcoming release, confirmed in #19763
