### ISSUE TITLE
Rendering HTML in Edit Rows mode

### ISSUE THREAD

**Issue by James-Pini** [microsoft/azuredatastudio#20881]
Issue Type: <b>Bug</b>

I was testing my API by deliberately inserting some harmless injected HTML to ensure it's being stripped. 

However it looks like azure data studio is rendering the html. 

Here's the HTML I used: 
```html
<h1> Look at this photograph </h1> <p>  <strong>Every time I do, it makes me laugh </strong> How did our eyes  get so red? And what the hell is on Joey's head? And this is where I grew up</p><p>  I think the present owner fixed it up I never knew we'd ever went without The  second floor is hard for sneaking out And this is where I went to school Most  of the time had better things to do</p><p>  Criminal record says I broke in twice I must have done it half a dozen times I  wonder if it's too late Should I go back and try to graduate? Life's better  now than it was back then If I was them, I wouldn't let me in</p><p>Oh, whoa, whoa Oh, God, I...</p><p>  Every memory of looking out the back door I had the photo album spread out on  my bedroom floor It's hard to say it, time to say it Goodbye, goodbye</p><p>  Every memory of walking out the front door I found the photo of the friend  that I was looking for It's hard to say it, time to say it</p><p>Goodbye, goodbye Goodbye</p><p>  Remember the old arcade Blew every dollar that we ever made The cops hated us  hangin' out They say, "Somebody went and burned it down" We used to listen to  the radio And sing along with every song we know We said, "Someday we'd find  out how it feels To sing to more than just the steering wheel" Kim's the first  girl I kissed I was so nervous that I nearly missed She's had a couple of kids  since then I haven't seen her since God knows when</p><script>  alert("xss");  window.open("https://google.com", "_blank").focus();</script><div onload="alert('xss')" style="background-color: red">  Test<img    src="test.gif"    style="background-image: url(javascript:alert('xss')); margin: 10px"  /></div><img  src="http://url.to.file.which/not.exist"  onerror="alert(document.cookie);"/>
```

Steps: 
1. Insert code while editing table rows into a specific column
2. I don't remember it rendering upon insert. I believe this only appeared when reopening azure data studio

### Screenshot
![image](https://user-images.githubusercontent.com/41030101/196816564-6b90e58a-100e-4c4b-80ca-90cf1742bc13.png)

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8705G CPU @ 3.10GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (4.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
profiler|Mic|0.11.0

</details>

**Comment by smartguest** [comment]
Testing of this issue shows it to not be related to editDataGridPanel itself, but rather it is an issue with ResultSetUpdated in STS, the data in ADS editDataGridPanel is passed as is currently into the query runner, something needs to be done on our side prior to handling or maybe it must be done on the STS side.

**Comment by kburtram** [comment]
@smartguest I could still repro this on the current insiders build.  Have you had a chance to investigate further?

**Comment by smartguest** [comment]
It appears that SlickGrid doesn't have any HTML checking built in when it loads the item directly from the grid, so because of this limitation, we cannot support HTML unless we strip the data in this case, which is not desirable.

**Comment by Charles-Gagnon** [comment]
@smartguest The fix should be to ensure that any cell content is HTML escaped or otherwise ignored for parsing (using document.createTextNode or something similar probably) before being set as the content. Is there something making this not be possible?

**Comment by smartguest** [comment]
@Charles-Gagnon The issue is that slick.grid renders the data from whatever dataprovider provides directly when we refresh the table upon entering HTML in one cell and switching back and forth to the tab. We cannot use document.createTextNode as the data is retrieved from the provider directly by slickgrid before it is rendered (as it's all part of the slick grid code). The only thing I can think to prevent this is to HTML escape the data before it is added to the cell or in the asyncDataView class
