### ISSUE TITLE
Server buttons aren't sized correctly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20886]
1. Open the Servers viewlet

Expected: Buttons are correct size

Actual:  Buttons are too big.  It looks like some styles got lost during merge to main.

![image](https://user-images.githubusercontent.com/599935/196861581-9e0ff87d-56a3-4e3b-ade0-d58f5c7c80ab.png)

**Comment by alanrenmsft** [comment]
ack!
