### ISSUE TITLE
Schema Compare - unchecked differences included in generated script

### ISSUE THREAD

**Issue by DSunrisein** [microsoft/azuredatastudio#20880]
after schema compare, when generate script. generate script contains all the script which is not selected in schema compare. even though I did not select the script I don't want to transfer click on generate script includes everything.

**Comment by SakshiS-harma** [comment]
Possible duplicate: https://github.com/microsoft/azuredatastudio/issues/14450

**Comment by kisantia** [comment]
it's possible that these are unexcludable differences that shouldn't have a checkbox shown - issue tracking that change is https://github.com/microsoft/azuredatastudio/issues/21035

@DSunrisein can you please share a sample repro for this so I can try debuging?

**Comment by kisantia** [comment]
closing due to lack of information
