### ISSUE TITLE
Errors in shared process on startup

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20893]
After the merge I'm now seeing the shared process dev tools window open on startup of the dev build of ADS with these errors

![image](https://user-images.githubusercontent.com/28519865/197008042-ed4584c3-f39f-477e-8e83-cdca53c13327.png)

It's unclear what this is affecting, although given the applicationinsights package this may be affecting our telemetry. Investigation is needed into the cause and effect of these errors.

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/vscode/issues/140624

Following up with VS Code team, seems like this will go away with the switch to 1DS appender.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon no milestone?
