### ISSUE TITLE
Can't generate SQL script

### ISSUE THREAD

**Issue by apasha14** [microsoft/azuredatastudio#20892]
Issue Type: <b>Bug</b>

I'm attempting to generate a create script on a table but am unable to do so. I a get an error saying that it could not connect to the server but the connection is fine and I'm able to query the table.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (6.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aasimkhan30** [comment]
Possible dup of #21344.

@apasha14 , are you using AAD auth to connect to the server.

**Comment by lewis-sanchez** [comment]
@apasha14 this issue appears to be fixed in the latest insider version of Azure Data Studio. Please try the latest insider version and see whether this is fixed for you: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch
