### ISSUE TITLE
Opening ADS from URL with a sqlplan file does not render graphical query plan

### ISSUE THREAD

**Issue by dimitri-furman** [microsoft/azuredatastudio#20902]
- Azure Data Studio Version: 1.39.1
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. With ADS installed on a machine, enter the following URL in a browser location bar: `azuredatastudio://file/path\to\file\untitled-1.sqlplan` and hit Enter. Here, `untitled-1.sqlplan` contains query plan XML retrieved from Query Store.
2. After a couple of prompts, ADS will open and display the XML contents of the file, instead of rendering graphical query plan.
3. Opening the same file directly in ADS via File->Open File renders it correctly as a graphical query plan.

Does this issue occur when all extensions are disabled?: Unclear. Unable to launch ADS from URL with extensions disabled.

**Comment by aasimkhan30** [comment]
Moving to march

**Comment by alanrenmsft** [comment]
@aasimkhan30 please add size label.
