### ISSUE TITLE
Seeking community feedback on SQL Server Import extension

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#2090]
As part of Microsoft's [Hackathon](https://news.microsoft.com/life/hackathon/), the engineering team created an initial prototype extension for the [SQL Server Import extension, otherwise known as Import Flat File Wizard](https://docs.microsoft.com/en-us/sql/relational-databases/import-export/import-flat-file-wizard?view=sql-server-2017).

The SQL Server Import extension can import any .txt or .csv file into a database and convert into a SQL table, and this marks our first import experience in SQL Operations Studio. The beauty of this feature is the user is not overwhelmed with complex configuration options when all they want to do is import a flat file. 

Harnessing the power of AI, the Import Wizard uses a Microsoft Research technology known as [Program Synthesis Using Examples, or PROSE](https://microsoft.github.io/prose/). PROSE can automatically detect a file's data types, delimiters, column names, and file structure without the user having to explicitly define the configuration. See an end-to-end demo in the GIF below. 

![image](https://user-images.githubusercontent.com/30873802/44820757-2006ba00-aba7-11e8-8f61-1fe7d0359f39.png)

For most users, SQL Server Import turns into a 5 click experience to go from flat file to SQL table. Let's go into a bit more detail.

## Requirement
In order to launch the wizard, **make sure you have an active connection.** Otherwise, error is thrown.

### UI Entry Point
After downloading the SQL Server Import Extension (in a future Insider's Build or on August 22nd), the user has two entry points:
- Hotkey (Ctrl + i on Windows and Mac)
- Settings (Bottom-left gear) -> Command Palette -> Type 'import'

We are still experimenting the best entry point. Things we are considering and would appreciate feedback:
- Right-click option on database in object explorer
- Default Task widget on Database dashboard. (we are concerned of overriding user's default dashboard)

## New Table Details
![image](https://user-images.githubusercontent.com/30873802/43433347-c958ed28-942b-11e8-8bbc-f4f2529c3978.png)

In SSMS, the user can only select a **file**, **table name**, and **schema**. We added **Server**, which detects only active servers, and **Databases**, which detects databases in the selected server. Since our current implementation allows the wizard to be opened anywhere and not restricted to a database, we allowed user flexibility to open wizard any time. Let us know if this is an issue.

We don't want to daunt the user of having too many configuration options on first page, but please let us know if we should include additional items. Next is disabled until all fields are filled. Table name is auto-filled, but will throw error on client-side if table name already exists.

### Preview Data
image

This page makes a call to our PROSE backend and pops out a preview. The PROSE learning is applied to the first 200 rows, but for now we just display the first 50 rows as a sanity check for the user. User does not do anything except view data.

One thing we are **considering** is adding override options on this page so that the user can:
- Change delimiter
- Skip _n_ number of lines of header
- Change number of lines to apply PROSE learning
- Change character encoding

The idea is that the user can automatically generate a new preview with new override options. Let us know if this is important to you.

### Modify Columns
![image](https://user-images.githubusercontent.com/30873802/43433552-bac809c8-942c-11e8-914d-c88104084fef.png)

This page allows the user to change Column Names, Data Types, Primary Key, and Nullability. PROSE automatically can learn the data types of the file and will choose best option. As a user, you have an editable dropdown to choose from T-SQL valid data types, and also change number of characters such as varchar(999) in case you have a long string value on row 9999. Let us know if this UI is helpful

We have heard feedback that a clusterable and columnstore checkbox would be helpful when dealing with those server instances. Let us know how important that is to you.

### Summary
![image](https://user-images.githubusercontent.com/30873802/43433643-1871ebac-942d-11e8-9a3a-f58f0decc690.png)

Once you click **Next**, PROSE will import the whole file into a SQL table that will be added to your database. If it is successful, a success message will appear and tell you how many rows were successfully inserted. Let us know if you would like a bigger checkmark or more colorful indicator.

The more interesting scenario is for error cases. For now, we are working on an error message that says "error at lines 10-20," but due to limitations of SQL Bulk Copy, we can't get any more granular than that. Let us know how high of a priority it is to have of error scenarios you have run into the past so that we can figure out how to best share this information.

### Import New file
This is a nice button on the summary page, but this will remember your server and database you selected and right away you can import another file. Makes it easy to import multiple files. We would eventually like to import directories of files or make this scriptable, but there are current complications and bandwidth issues, so that is lower priority for now.

### Future work
We captured some additional scenarios in the walkthrough above, but there are some plans in the works:
- JSON support and additional file support
- Excel Flash Fill in Modify Columns (so user doesn't have to modify 100 individual columns)
- Ability to apply learning to a file 

We can't wait to get this extension in your hands this month, but please let us know how we can improve the UI for this wizard. Let us know what you prioritize, and we can work together to incorporate into our plans. **Please spread the word about this conversation.**

Let us know what you would like to see in SQL Server Import in this issue. We would love to hear your feedback as we continue to experiment with Open Design so that we are building features that our users love. Thank you.

**Comment by peterlukerow** [comment]
Definitely there should be an option in the context menu on a database.

Everything on some dashboard is the thing I hate most about SOS. If I want to import a flat file into a database I assert I'm not going to pick a random database I'm going to know exactly which one.

Given SOS seems to be ripping up the rule book, so to speak of how SSMS works at least give config options for the feature so that you can choose to have it on the context menu on a database.

I want to use SOS mainly because it properly implements a dark theme, and some of it's functionality is nicer but it is missing so much functionality and changing so much of the way things use to work there needs to be a little give and take, i.e. have settings so long time SSMS users can have things closer to how they use to be as well as having access to the new bits. Especially important now that MS is seemingly dumping SSMS (a bit like their actions imply on full fat .NET)

**Comment by dzsquared** [comment]
Is it on the roadmap to extend the functionality to include inserting rows into an existing table?  I know this isn't part of the "Import Flat File" context item in SSMS, but rather the "Import Data" option - but the PROSE API might be helpful in automapping columns based on data types.

**Comment by yualan** [comment]
@peterlukerow Sounds good, context menu on a database when extension is downloaded seems to have been requested several times. Would you expect the server and database dropdown in the wizard to be disabled so that the user is only working in that database context? Or should user have flexibility still to change to another database?

Feedback noted. There is a difference between Server dashboards and Database dashboards, so the user should know the context they are in. Our main concern was the default dashboard is entirely up to the user, so overriding a user's default dashboard with a Task widget may not be ideal. Open to feedback. We can also look into adding better config settings.

To be transparent, SSMS is not going away. @vickyharp went into more detail about our roadmap [here](https://redmondmag.com/articles/2018/07/10/sql-server-tools-development.aspx), but in summary, we are continuing investments in SSMS through our monthly releases and consider SSMS as our flagship tool.  On SQL Ops side, we will continue to make investments in bringing over the most customer requested features like SQL Agent and Profiler into SQL Operations Studio. The upside with SQL Operations Studio is that we have an opportunity to work with this talented community to revisit some of the limitations in UI of SSMS and see if we can improve it or keep things the same. 

We have made some efforts to bring over things like SSMS keymap, these extensions, and Edit Data, but these all came from the community asking us to bring it in. We **love** to see this passion for SQL Server of what you like and what you don't like, and this feedback is valuable to us to build great tools.

@dzsquared 
Yes, this is currently on the roadmap and has been requested for the Import Flat File Wizard currently in SSMS. Do you have a suggestion of what would be a good flow in your mind to expose this functionality without having too many configuration options? For others, please chime in if this is something you are looking for by liking dzsquared's comment because if this is a very common scenario, we can move it up in priority.

**Comment by DaveDustin** [comment]
Similar to what @dzsquared said, we'd like to see the ability to import content into an existing object if present, or create one, even if a match is found.

Change the order of operations
- You open a file to import, it does it's analysis determining columns, types etc..., allows the user to change types.
- Next choose where to store the data, but have the application scan the destination database to see if any existing objects look like the proposed schema.  If they do, offer the option to import into that table (with optional delete of existing content first)

**Comment by peterlukerow** [comment]
@yualan - I wouldn't mind if the wizard disabled server/DB selections or left it open to change really. I'd lean towards disabled to enforce the route taken to get to that point.

Regarding MS commitment to SSMS, sorry that's not reassuring. Every time there is a new release of SSMS that are lots of comments literally saying things like "Dark theme 5000+" over and over across the last couple of years. Despite the fact that you can tweak the config file to enable dark theme that works 90% MS' only response is - "it's not currently on our roadmap". On the other hand SOS has dark theme out the box but lacks the functionality. However the functionality is gaining with each release, unlike Visual Studio vs. VS Code when feature parity hits it seems like there will no point in having both.

Regarding .NET full fat vs. .NET core it's a similar story. MVC on full fat .NET hasn't seen an update in 3 years, for example, mean whilst every article about .NET is about some new core thing that isn't available or isn't parity in full fat.

**Comment by rdymade** [comment]
I want to test this feature also but i am unable to find it. I downloaded the August Preview Insiders Build 0.32.6 from the 25.08.2018. Ctrl + i and the entry via Command Palette are not there.
Am i missing something?

I'm also interested in the import into an existing table.

**Comment by ndwivedi** [comment]
I do not see Import flat file extension in market place. Not sure what I am doing wrong. I installed latest version of Operations studio.

![image](https://user-images.githubusercontent.com/9135814/44908996-a62c1900-aceb-11e8-94fc-b4e5ecf4ae1d.png)

**Comment by IAmHopp** [comment]
This extension... Doesn't work?

Is there a repo for it where I can open an issue or should I file it in this one? I just installed it on Azure Data Studio and it just... Doesn't work at all.

**Comment by chojrak11** [comment]
I'd like to be able to use this kind of feature from command line. That's crucial.

**Comment by chojrak11** [comment]
I'd like to be able to use this kind of feature from command line. That's crucial.

**Comment by dzsquared** [comment]
> Hello @yualan
> 
> I'm a beginner at SQL.
> I try to import a csv file using the Import Flat File Wizard, but at the end of the wizard I get the error: "Error inserting data into table".
> Whats wrong?
> 
> best regards

@abusk1 In using this extension frequently, I find that I get that error message whenever the data types selected by the wizard based on the first 50 rows of the csv don't match all the way through and there's a data type mismatch.  (for example, an int column eventually has non-numeric data or a not null column is empty further down)

**Comment by BolunZhu** [comment]
However , sometimes it doesn't work well.
When I import a .txt file into sql server using this extension, it turns out an unexpected table like this.
![image](https://user-images.githubusercontent.com/21354261/56899393-ea172e00-6ac5-11e9-863c-210f2c702f1f.png)
But my .txt file looks like this.
<img width="216" alt="屏幕快照 2019-04-29 下午9 30 59" src="https://user-images.githubusercontent.com/21354261/56899516-35314100-6ac6-11e9-8059-3b6592322497.png">

I tried to save this file in UTF-8 or GBK ,but it doesn't work.
I'm using Sql Server on  Mac OS with Docker , So I can only use Azure Data Studio.
Could someone tell me how to import such file into my Sql Server.
Any help would be appreciated. Thanks

**Comment by gracielaPosadas** [comment]
I'm having the exact same issue as @BolunZhu with some CSV files by the way my .txt files are working fine. othere issue is that is converting zipcodes into datetimes. Any advice about how does the format of the data must be for a success import?

**Comment by dvlsg** [comment]
> Error inserting data into table

Is there a way to collect the error message in question? The extension usually works wonderfully, but I still run into issues every once in a while, even when opening up the types as far as I can (making everything nullable, importing everything as unbounded text, etc). When hopping over to SSMS, the import works without needing to change the file.

I see I have a "Flat File Import Service" section in the dropdown of my output panel in ADS, but there's nothing in it after an error. The problems tab doesn't report anything, either.

**Comment by williamthiago** [comment]
Modify Columns step is ignoring my edits on Azure Data Studio for macOS. After I choose to continue, the table is created with the suggested types instead my edits. That's causing an "Error inserting data into table" because of one of my columns is VARCHAR(72), and PROBE is setting VARCHAR(50)

**Comment by pnhughes** [comment]
> Modify Columns step is ignoring my edits on Azure Data Studio for macOS. After I choose to continue, the table is created with the suggested types instead my edits. That's causing an "Error inserting data into table" because of one of my columns is VARCHAR(72), and PROSE is setting VARCHAR(50)

Having a similar issue with the latest versions of ADS and Import Wizard. Changes to data types are being ignored by the import wizard in favor of initially detected types after preview.

**Comment by pnhughes** [comment]
> > Error inserting data into table
> 
> Is there a way to collect the error message in question? The extension usually works wonderfully, but I still run into issues every once in a while, even when opening up the types as far as I can (making everything nullable, importing everything as unbounded text, etc). When hopping over to SSMS, the import works without needing to change the file.
> 
> I see I have a "Flat File Import Service" section in the dropdown of my output panel in ADS, but there's nothing in it after an error. The problems tab doesn't report anything, either.

While useful, the Import Wizard is incomplete without the ability to capture more granular error or output data to a log file.  ADS is a perfect fit for most of my analysis operations, but the limitations of the Import Wizard more often than not drive me back to SSMS (or to drink...).

**Comment by anand348** [comment]
In "Modify columns", step 3 in wizard - can we have a "csv editor" option to do bulk changes. It will make importing faster in some rare cases.

**Comment by mdougherty3** [comment]
On Ubuntu 19.04/ADS 1.10.0 (same issue happened on previous builds): Receive an error message "Cannot Load Service Component" on ADS start each time and cannot use the import tool at all.

![image](https://user-images.githubusercontent.com/48739541/63479211-c9ac1e80-c47c-11e9-973b-c11ef441bc43.png)

**Comment by iAlexanderMoon** [comment]
Same as mdouherty3 on Xubuntu 19.04.

**Comment by amsteel** [comment]
Same as Mdouherty3 on Debian 10. Also got the error "command 'flatFileImport.start' not found when trying to launch the import wizard.

**Comment by kburtram** [comment]
Closing out older issues.  Thanks for all the feedback on this feature.  Please log new issues for any bugs impacting this scenario.

**Comment by rainabba** [comment]
Just updated Azure Data Studio (v1.16.1) and installed the Import plugin. When I hit Ctrl-I, I get a toast saying: command 'flatFileImport.start' not found

```
Version: 1.16.1 (system setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

**Comment by JohnA43** [comment]
I get an error: Login failed for user ''
Does it support MFA?

**Comment by andyleedev** [comment]
Will the imported file support other types such as XLS in the future?

**Comment by TalariaxKhin** [comment]
after upload the file, got an error message "Language Client is not ready yet." what does it means?

**Comment by dzsquared** [comment]
@TalariaxKhin please open a new issue with more details on the issue you encountered. The "report issue" menu item in ADS may be helpful.
