### ISSUE TITLE
SQL Tools Service does not start on macOS (arm and intel builds)

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#20916]
Version: 1.40.0-insider
Commit: 533e1ec1b921d2d246695f6edc441a8231790e9a
Date: 2022-10-21T16:32:05.903Z
VS Code: undefined
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 22.1.0

![image](https://user-images.githubusercontent.com/12227241/197261244-5caf93d8-d04c-497b-923f-a9cd9980b492.png)

**Comment by kburtram** [comment]
The current insider build shouldn't have this issue any more.  Sorry for the inconvenience.
