### ISSUE TITLE
Azure Data Studio cannot pull subscription information for MAG (Microsoft Azure Government)

### ISSUE THREAD

**Issue by cchurchwell** [microsoft/azuredatastudio#20915]
When registering linked services to Azure, my commercial Azure account works properly and shows my subscriptions, but my MAG account does not pull any subscription information.  My assumption is behind the scenes the tool is calling Connect-AzAccount without using the -Environment parameter, which defaults to Commercial

**Comment by cchurchwell** [comment]
![ADS_MAG](https://user-images.githubusercontent.com/51726004/197247228-059f405d-6b95-4730-a225-aaaee4faaec5.jpg)

**Comment by erinstellato-ms** [comment]
@kburtram @cheenamalhotra Not sure if this is expected behavior so I asked Chad to open an issue.  Let me know if you have questions, thanks!

**Comment by cheenamalhotra** [comment]
@cssuh 
Can you please take a look?

**Comment by cssuh** [comment]
Hi @cchurchwell have you been able to successfully fetch subscriptions previously?

**Comment by cchurchwell** [comment]
I’m not sure as I’ve never tried - I was performing an evaluation of the product for Erin

Chad Churchwell
Data and AI
Sr. Cloud Solution Architect

Sent from Outlook for IOS
________________________________

**Comment by cssuh** [comment]
Hi @cchurchwell, do you have the government cloud enabled in your settings?
<img width="1350" alt="Screen Shot 2022-10-25 at 3 58 28 PM" src="https://user-images.githubusercontent.com/18150417/197897587-0fe1e93a-d20b-492a-988f-bd1f6007a341.png">

**Comment by cchurchwell** [comment]
Yes it is enabled

[Graphical user interface, text, application  Description automatically generated]

**Comment by cchurchwell** [comment]
OK, I went and re-registered after enabling Azure government and if I register under the government section, it successfully pulls subscription information

[Graphical user interface, application  Description automatically generated]


Chad Churchwell
Senior Cloud Solution Architect
Microsoft Federal
Data and AI
[MSFT_logo]
***@***.******@***.***
Mobile: 904-502-7754
***@***.******@***.***>

SQL Server Support Lifecycle<http://support.microsoft.com/lifecycle/search/?sort=PN&alpha=SQL>

If you have any feedback about my work, please inform either myself or my manager Dwayne Boothe at ***@***.******@***.***>

**Comment by cssuh** [comment]
Ok, I will go ahead and close the issue.  If you run into any other problems, feel free to open a new issue.

**Comment by erinstellato-ms** [comment]
@cssuh thank you for your help with this!
