### ISSUE TITLE
Selection Summary Enhancement

### ISSUE THREAD

**Issue by clcridgeview** [microsoft/azuredatastudio#20913]
I love the selection summary feature and when I need quick stats for my results it's such a time saver.  It gives me the functionality that I have with SSMS and SSMS Boost.  But there are a couple of statistics missing that I feel would be valuable.

I realize UI space in the bottom bar is limited so I propose this may be better as a tooltip pop-up window.  But the addition of:
**Distinct Count
Min
Max**
Can be very useful and save time.

**Comment by alanrenmsft** [comment]
@clcridgeview FYI, this will be in our next stable release.

![selection-summary](https://user-images.githubusercontent.com/13777222/206804443-caa424e0-784a-49c7-a4eb-02cb28110b78.gif)
