### ISSUE TITLE
icon got stretched to the full height of the application

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#20921]
the application icon is stretched on the blank editor page, this only happen for the packaged version of ADS.

![image](https://user-images.githubusercontent.com/13777222/197289998-2ea85fd4-88c0-42f2-9e69-642aaf7f51a4.png)

**Comment by kburtram** [comment]
@alanrenmsft I think this is also related to the mixin issue.  We should have a new insiders build in an hour or two that I will use for verification.
