### ISSUE TITLE
Install package remains installed

### ISSUE THREAD

**Issue by naimsulejmani** [Microsoft/azuredatastudio#2092]
- SQL Operations Studio Version: 0.31.4

Steps to Reproduce:
1. When install the package the green button (install/update) is showing after install without reload, instead of blue reload button like visual studio code.

![image](https://user-images.githubusercontent.com/12331526/43450472-10b825e4-94b3-11e8-925f-d215151bde9f.png)

**Comment by alanrenmsft** [comment]
This issue is related to the acquisition experience for 3rd party extensions, (download vsix and install). we have Issue #3874 tracking this in a more general way.
