### ISSUE TITLE
ADS hangs opening folder

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#20932]
- Azure Data Studio Version: `insider`
- OS Version: Windows

Steps to Reproduce:

1. Open ADS and pick a folder to open from "Open Folder" command

Expected: ADS loads folder

Actual: ADS hangs.  I've only been able to repro with insiders build on Windows.  Open Folder is working fine for me on mac & on Windows in dev env and locally packaged build.

**Comment by Charles-Gagnon** [comment]
@kburtram Did you mean to close this with https://github.com/microsoft/azuredatastudio/pull/20934 or are you waiting to validate it with a packaged build?
