### ISSUE TITLE
Unable to expand column when double clicking on header in results grid view

### ISSUE THREAD

**Issue by nocomputeruser** [microsoft/azuredatastudio#20945]
Issue Type: <b>Bug</b>

Azure Data Studio Version: 1.39.1
OS Version: Windows 11 Enterprise 21H2

Steps to Reproduce:

1. Running any query that has a long field of text against our database in ADS will not allow me to double-click on the header column edge in the results grid view to expand the column width.  Double clicking on the header column edge only shrinks the column some or puts it back to where it was when the results first popped up. 

Does this issue occur when all extensions are disabled?: Yes

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (3.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
@nocomputeruser there is a configurable max column width, you can increase it to fit your needs.

![image](https://user-images.githubusercontent.com/13777222/199596714-8f89183f-83f7-4ebb-b7ea-dba195d033a5.png)
