### ISSUE TITLE
Search in Notebooks View not working

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#20948]
Error: spawn /Applications/Azure Data Studio - Insiders-3.app/Contents/Resources/app/node_modules.asar.unpacked/@vscode/ripgrep/bin/rg ENOENT	at Process.ChildProcess._handle.onexit (node:internal/child_process:282:19)	at onErrorNT (node:internal/child_process:477:16)	at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by corivera** [comment]
@barbaravaldez what notebook did you see this with? Searching in the notebooks viewlet works for me for books and notebooks

**Comment by barbaravaldez** [comment]
I used the SQL Server 2019 book. It's not finding results for me 
<img width="952" alt="Screen Shot 2022-10-25 at 11 49 55 AM" src="https://user-images.githubusercontent.com/34872381/197864225-d943c5a7-69b4-43b2-bedc-14eecd1b4a7c.png">
