### ISSUE TITLE
Cannot save untitled notebook

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#20951]
Version: 1.40.0-insider (Universal)
Commit: de3683dd018b1f28744f9eb8797a825bb38d784c
Date: 2022-10-24T05:29:21.556Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

When saving an untitled notebook, it generates an empty file.

**Comment by barbaravaldez** [comment]
Related to https://github.com/microsoft/azuredatastudio/issues/20933

**Comment by corivera** [comment]
Fixed by Karl's languageId PR
