### ISSUE TITLE
cannot build old style SQL project in insiders, M1

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#20955]
Issue Type: <b>Bug</b>

Created a SQL project from AdventureWorksLT as an old-style SQL project.  Attempted to build and received a build failure for missing targets.

(SDK-style SQL projects build fine)

	[ Build ]
    > "/usr/local/share/dotnet/dotnet"  build "/Volumes/Storage/CodeRepos/sample-sandbox/deleteme/DatabaseProjectAdventureWorksLT/DatabaseProjectAdventureWorksLT.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"
    stdout: Microsoft (R) Build Engine version 17.2.0+41abc5629 for .NET
    stdout: Copyright (C) Microsoft Corporation. All rights reserved.
    stdout: 
    stdout: 
    stdout: /Volumes/Storage/CodeRepos/sample-sandbox/deleteme/DatabaseProjectAdventureWorksLT/DatabaseProjectAdventureWorksLT.sqlproj(55,3): error MSB4019: The imported project "/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.
    stdout: 
    stdout: 
    stdout: 
    stdout: Build FAILED.
    stdout: 
    stdout: /Volumes/Storage/CodeRepos/sample-sandbox/deleteme/DatabaseProjectAdventureWorksLT/DatabaseProjectAdventureWorksLT.sqlproj(55,3): error MSB4019: The imported project "/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets" was not found. Confirm that the expression in the Import declaration "/Users/drewsk/.azuredatastudio-insiders/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets" is correct, and that the file exists on disk.
    stdout:     0 Warning(s)
    stdout:     1 Error(s)
    stdout: 
    stdout: Time Elapsed 00:00:00.15

Extension version: 0.19.0
Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (de3683dd018b1f28744f9eb8797a825bb38d784c, 2022-10-24T05:31:36.093Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
This is happening because the sql database projects extension hasn't been updated in insiders since the dependency on the DacFx dlls in STS was removed back in September. Copying the targets file from the DacFx nuget to the STS output was removed in https://github.com/microsoft/sqltoolsservice/pull/1674. 

When the sql database projects extension gets updated in insiders, this shouldn't be a problem anymore. Users previously building legacy projects in insiders shouldn't be affected if they still have the targets file in the BuildDirectory from the past.
