### ISSUE TITLE
Links in markdown open in external web browser

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#20968]
Version: 1.40.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Windows_NT x64 10.0.22621

1. Open a markdown file with relative links to other files
2. Click on the link

Instead of opening in ADS it tries to open it in an external web browser with a URL like this : `https://file+.vscode-resource.vscode-cdn.net/c%3A/Users/chgagnon/Desktop/sqlserver2019/content/repair/sop017-add-app-deploy-group.ipynb`

(I used the SQL 2019 troubleshooting book for this, opened up the folder into the workspace and then use the Notebook viewlet to open the MD file)

**Comment by barbaravaldez** [comment]
I looked into this and it seems that some files in the markdown-language extension are missing, specifically media/index.js and media/pre.js.

The notebook-out directory is also missing from the markdown-math extension which is causing this other issue https://github.com/microsoft/azuredatastudio/issues/20091
