### ISSUE TITLE
the change to the encrypt option resulted in 3 entries in OE for the same target databases

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#20982]
![image](https://user-images.githubusercontent.com/13777222/198099307-eb08d452-c2be-4806-861b-ed09498c7407.png)

the first one is the connection prior to upgrading to the latest insider.
the second is with Encrypt on.
the third is with Encrypt off.

IMO, this option shouldn't be an identity option, that means, there should be only 1 connection in the OE entry.

**Comment by Charles-Gagnon** [comment]
Same issue as https://github.com/microsoft/azuredatastudio/issues/20972 - see comments there for explanation of where the problem is exactly
