### ISSUE TITLE
import wizard will not active on macos M1

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#20998]
Issue Type: <b>Bug</b>

After installing the import wizard extension on the insiders for M1, it will not activate citing an incompatible platform

![image](https://user-images.githubusercontent.com/12227241/198153150-fac45ca8-c5b1-4165-9833-1a129fa64ec3.png)

Extension version: 1.5.0
Azure Data Studio version: azuredatastudio-insiders 1.40.0-insider (d5cf088ba7b794859438fd2c1902249fd1e6a947, 2022-10-26T05:48:43.511Z)
OS version: Darwin arm64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment]
I had to reactivate this issue because I reverted recent changes to the import extension due to regressions. @aasimkhan30 will handle this in December release.

**Comment by stateout** [comment]
@aasimkhan30 Just wanted to share my same problem. I'm not using the _Insiders_ version of Azure Data Studio, I'm currently using:
Version: 1.40.1 (Universal)
Commit: 3a32679ab590c1023ab4de6f191769e7e127d25b

But I'm getting the same error message as the author, dzsquared, where the following error message appears:
<img width="463" alt="image" src="https://user-images.githubusercontent.com/73503098/205512046-66b9a311-b737-4ffa-92f7-3ffb7be99977.png">
My SQL Server Import version is **v.1.5.3**

**Comment by liyenay** [comment]
I am facing the same issue and can I know how you resolve it if you managed to?

**Comment by alanrenmsft** [comment]
@liyenay  @stateout for now, the work around is to use the Intel version of Azure Data Studio.

**Comment by stateout** [comment]
> @liyenay @stateout for now, the work around is to use the Intel version of Azure Data Studio. The Intel version can also run on ARM64 Mac but it is less performant then the Universal version.

Alan, thank you so much for the insight! Can't believe I didn't think of doing that! This means a lot. @liyenay thanks for asking the right question. Looks like we have our solution now!

**Comment by aasimkhan30** [comment]
dup of #21313
