### ISSUE TITLE
schema compare include header turns into non-functional checkbox when clicked

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#20992]
Version: 1.40.0-insider
Commit: d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:48:43.511Z
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin arm64 22.1.0

Steps to Reproduce:
- run schema compare
- click "Include" column header
- word turns into checkbox
- apply changes
- all changes applied, even ones that were deselected magically by the new checkbox

![2022-10-26_13-07-51 (2)](https://user-images.githubusercontent.com/12227241/198128014-56fc36a4-b9e1-4a8d-94dc-b8e51d39df21.gif)

does not repro in ADS 1.39

**Comment by kisantia** [comment]
This is a regression from the August release

**Comment by kisantia** [comment]
This started failing at commit 37636012da25cca3cb0a1e0fe32c88d2766aec80. @aasimkhan30 can you please take a look since this is related to the table changes made in https://github.com/microsoft/azuredatastudio/pull/20514?
