### ISSUE TITLE
Kusto (recent or saved) connection does not get auto populated in connection details

### ISSUE THREAD

**Issue by VasuBhog** [microsoft/azuredatastudio#20994]
Version: 1.40.0-insider (Universal)
Commit: d5cf088ba7b794859438fd2c1902249fd1e6a947
Date: 2022-10-26T05:49:36.314Z (14 hrs ago)
VS Code: 1.67.0
Electron: 17.4.5
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.13-electron.0
OS: Darwin x64 21.6.0

Steps to Reproduce:

1. Either Open the Connection Dialog via the Connection Pane or Change the Connection in Query / Notebook Editor
2. Initially shows without selecting any recent:
![Screen Shot 2022-10-26 at 1 31 15 PM](https://user-images.githubusercontent.com/23587151/198131880-343bcfc8-086a-4106-8848-de97df507569.png)

3. Select a saved Kusto connection 
![Screen Shot 2022-10-26 at 1 31 30 PM](https://user-images.githubusercontent.com/23587151/198131920-3cbcbce0-3e5f-4004-babc-c9cb0f4cc4a0.png)

**Actual**: Does not update the connection details with the cluster details and leaves it blank.
**Expected**: Should auto-populate recent / saved Kusto connections 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
I noticed that it does take some time for extension to load, but once it does, it does populate fields. I don't reproduce the behavior otherwise. Can you confirm?

**Comment by cheenamalhotra** [comment]
Closing as issue not reproducible.
