### ISSUE TITLE
new table option is not there.

### ISSUE THREAD

**Issue by Sachid26** [microsoft/azuredatastudio#21009]
- Azure Data Studio Version: 1.39.1(user setup)
- OS Version:

Steps to Reproduce:

1. install the azure data studio
2. right click on the tables folder within an active connection

Does this issue occur when all extensions are disabled?: Yes/No

![image](https://user-images.githubusercontent.com/70128087/198205288-f2549442-b119-4b1b-887e-e31bd5a25ad6.png)

**Comment by Sachid26** [comment]
I am also not getting the design option when right clicking the table.
![image](https://user-images.githubusercontent.com/70128087/198208530-b71fbdf0-44bd-4117-ba23-3397c4ab6e34.png)

**Comment by dzsquared** [comment]
@Sachid26 the table designer feature is in preview, can you confirm that workbench preview features are enabled in Azure Data Studio?  This can be found in settings under search for "preview features".

**Comment by Sachid26** [comment]
yeah, i enabled this and it got visible now. The documentation is not clear on enabling the preview features. Can a link to the enabling preview features be put on all the feature docs that are released in preview?

**Comment by dzsquared** [comment]
There's an update for docs out for publishing: 
![image](https://user-images.githubusercontent.com/12227241/198358345-fec3f0c7-de2a-47d0-921e-c79500259a3f.png)

**Comment by kodima05** [comment]
I tried enabling the preview features setting but it doesn't work
My Azure Data Studio version is 1.44.1 (user setup) on Windows 11
![image](https://github.com/microsoft/azuredatastudio/assets/37368927/4400b657-9384-44f2-8c47-5573f4d9c033)

**Comment by Charles-Gagnon** [comment]
@kodima05 What version of ADS are you using? Make sure you update to the latest (currently 1.44.1)
