### ISSUE TITLE
SQL Server datetimeoffset precision not honored in select results

### ISSUE THREAD

**Issue by palhal** [microsoft/azuredatastudio#21011]
- Azure Data Studio Version: 1.39.1
- OS Version: Windows 10 21H2
- DB Version: Microsoft SQL Server 2019 (RTM-GDR) (KB5014356) - 15.0.2095.3 (X64)
 
Steps to Reproduce:

1. Run the following query:
```sql
SELECT 
    CONVERT(datetime2(0), SYSDATETIME()),
    CONVERT(datetimeoffset(0), SYSDATETIMEOFFSET())
```
This results in:
```
2022-10-27 08:51:28
2022-10-27 08:51:28.0000000 +02:00
```
2. Observe that datetime2 precision is honored, while datetimeoffset is not

Does this issue occur when all extensions are disabled?: Yes

I use a lot of datetimeoffset(0) columns because micro/milliseconds are overkill in many cases. But it's kind of annoying that datetimeoffset2 is always returned with precision 7 regardless of the actual column type.

**Comment by alanrenmsft** [comment]
@palhal this is a SQL Server topic and you should raise the question at https://techcommunity.microsoft.com/t5/sql-server/ct-p/SQL-Server. Azure Data Studio is just displaying whatever SQL Server returns.

**Comment by palhal** [comment]
@alanrenmsft I see. I guess that means that both SSMS and sqlcmd are doing special formatting based on the precision? When I run:
```bat
sqlcmd -Q "SELECT CONVERT(datetimeoffset(0), SYSDATETIMEOFFSET())"
```
I get the expected result without fractional seconds. If this really is the case, I wonder why they didn't fix it in the server instead.

**Comment by alanrenmsft** [comment]
SQL CMD: 
![image](https://user-images.githubusercontent.com/13777222/199621791-b89fe56f-ba02-463e-b941-8143f201afb3.png)

SSMS:
![image](https://user-images.githubusercontent.com/13777222/199621870-7aa93216-c53c-46c1-8c7c-66ca8dad33cd.png)

ads:
![image](https://user-images.githubusercontent.com/13777222/199621996-d67ea8c3-2066-4b4c-8e2b-dfe6ed9f7a84.png)

**Comment by caohai** [comment]
@palhal I've merged a fix for this issue today and you should be able to test it out in tomorrow's insider build or you can wait for the next official release.

**Comment by palhal** [comment]
Thanks! Looking forward to try it in the next official release 😃
