### ISSUE TITLE
Database Project on Ubuntu 22.04 Cannot find .NET Core SDK 3.1 or higher

### ISSUE THREAD

**Issue by gscheife** [microsoft/azuredatastudio#21027]
- Azure Data Studio Version: 1.39.1
- OS Version: Ubuntu 22.04

Steps to Reproduce:

1. clone git repo locally
2. build or publish throws "The .NET SDK cannot be located. Project build will not work. Please install .NET Core SDK version 3.1 or higher or update the .NET SDK location in settings if already installed.

Does this issue occur when all extensions are disabled?: Yes/No

Yes

This project does publish correctly under Windows.

**dotnet --info**

.NET SDK (reflecting any global.json):
 Version:   6.0.110
 Commit:    ce0a42998a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/

global.json file:
  Not found

Host:
  Version:      6.0.10
  Architecture: x64
  Commit:       5a400c212a

.NET SDKs installed:
  6.0.110 [/usr/lib/dotnet/dotnet6-6.0.110/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [/usr/lib/dotnet/dotnet6-6.0.110/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Updated path in settings:** 

/usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/

**Build output:**

**When I set the path in settings I get the same error and when I look at the path used it has "/**dotnet**" appended.** 

> "/usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/dotnet"  build "/home/gscheife/Projects/DataStation/DataStation.Database/DS_Exports/DS_Exports.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="/home/gscheife/.azuredatastudio/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"
    stderr: /bin/sh: 1: /usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/**dotnet**: not found
    stderr: 
    >>> "/usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/dotnet"  build "/home/gscheife/Projects/DataStation/DataStation.Database/DS_Exports/DS_Exports.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="/home/gscheife/.azuredatastudio/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"    … exited with code: 127
	>>> "/usr/lib/dotnet/dotnet6-6.0.110/sdk/6.0.110/**dotnet**"  build "/home/gscheife/Projects/DataStation/DataStation.Database/DS_Exports/DS_Exports.sqlproj" /p:NetCoreBuild=true /p:NETCoreTargetsPath="/home/gscheife/.azuredatastudio/extensions/microsoft.sql-database-projects-0.19.0/BuildDirectory"   … errored out: Process exited with code 127

**Comment by SakshiS-harma** [comment]
Hi @gscheife , can you try the latest insider build (https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main)? This issue was fixed after the August release (https://github.com/microsoft/azuredatastudio/issues/16598).

For the workaround, can you try updating the path to: /usr/lib/dotnet (and not the whole path). It tries to find the latest version within this folder.

Let me know if you have anymore questions, and if the insiders work for you.

**Comment by gscheife** [comment]
Thank you for the reply. I did download the Insiders from about. When I try "/usr/lib/dotnet" I get "/usr/lib/dotnet/dotnet: not found" but when I just use "/usr/lib" I get "/usr/lib/dotnet: permission denied." is there a specific path that needs access?

**Comment by SakshiS-harma** [comment]
My bad, the default installation location for Ubuntu/Linux version is under "/usr/share/dotnet". Can you try specifying "/usr/share" and see if that works?

**Comment by gscheife** [comment]
I do not have a dotnet install in /usr/share/.

**Comment by SakshiS-harma** [comment]
Just to be sure, do you have the access permissions for "/usr/lib/dotnet". Because if you have specified the location in Settings, it should be able to find the dotnet from there.
![image](https://user-images.githubusercontent.com/57200045/198734853-dbbe9ebc-f5c0-4938-8cd0-9809f21c9925.png)

**Comment by SakshiS-harma** [comment]
@gscheife additionally, does the sdk show up when you do "dotnet --list-sdks"?  And what is its path?

**Comment by cheenamalhotra** [comment]
Also to add, currently in latest insiders, .NET runtime is downloaded every time a reload happens.

**Comment by gscheife** [comment]
I appreciate the help but I have given up on this extension using Linux.

**Comment by SakshiS-harma** [comment]
Hey @gscheife , I understand your frustration here and I regret not been of any help to you. 
Thank you for trying out the extension in Linux though. I hope you will give this extension another chance and I will be pleased to assist you then.
For now since there is nothing that I can provide an aid to, I will go ahead and close this issue. You can either reopen it or create a new one for any more challenges you face.

**Comment by jbtcode** [comment]
@SakshiS-harma this issue is closed, so I just realized maybe no one will be reading this, should I create a new issue instead?

**Comment by SakshiS-harma** [comment]
@jbtcode Sure you can go ahead and create a new issue to track it.
In the meantime, can you try setting "/usr/share/dotnet" as the dotnet path- and see if that works?

**Comment by jbtcode** [comment]
Setting the dotnet path ("Sql Database Projects: Dotnet SDK Location") to `/usr/share/dotnet` solved the issue. Thanks !

**Comment by SakshiS-harma** [comment]
@jbtcode Glad that it worked for you. Do raise a new issue if you get stuck with any other complications. Thanks!
