### ISSUE TITLE
Query editor loses results when saved

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#21038]
- Azure Data Studio Version: `insider`

Steps to Reproduce:

1. Open an untitled SQL editor and run a query
2. Save query file

Expected: Results are retained

Actual: Results are lost

**Comment by kburtram** [comment]
This is how this issue was fixed when we encountered it previously https://github.com/microsoft/azuredatastudio/pull/16883.

**Comment by alanrenmsft** [comment]
verified the fix using today's insider build.
