### ISSUE TITLE
Systems Tables, Views, Stored Procedures missing in user databases

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2106]
- SQL Operations Studio Version: 0.31.4 and latest dev build

Steps to Reproduce:
- Connect to a SQL Server and expand Databases
- Go to a user databases and expand Tables, Views or Stored Procedures

Expected:
- I can see a System Tables / System Views / System Stored Procedures folder and expand it to see system objects
Actual:
- I cannot see these folders at all

note, this does not apply for master and other DBs under System Databases

The problem here is it's helpful to understand what system procs are there and how to run them.

![image](https://user-images.githubusercontent.com/10819925/43495281-0997491e-94ec-11e8-918f-b032b82a64ed.png)

**Comment by kevcunnane** [comment]
Changing this to a suggestion after syncing with Karl. It's currently by design but it's a change from SSMS.

**Comment by kburtram** [comment]
Some context is that when we originally designed the Object Explorer node layout we decided to only show System Objects on System Databases in order to simply the default view when working with User Databases.  The logic was that most users doing non-administrative work in User Databases would prefer not to see these "implementation details."  Whereas DBA users would likely be working in `master` in any case.  

In any case, this is a change from SSMS so it's reasonable to revisit if the change is really adding value or just making the SQL Ops harder to use for our SSMS users.

**Comment by byroniac** [comment]
Please consider adding this as an optional preference in settings (and let it be disabled by default). I find this to be very useful in SSMS when searching stored procedure schema in our user databases. I can understand, though, not wanting to see it by default.

**Comment by kburtram** [comment]
I'm going to close this issue as "closely related to" https://github.com/microsoft/azuredatastudio/issues/11511.  For 11511 the system tables are CDC and need to be in the user DB.  When fixing that we can consider if it makes sense to bring in all the system tables into user DBs.

**Comment by sgreenfield** [comment]
We need to be able to see system tables.  This program is worthless because I cannot see all database objects.  Why would you hide them?  It makes no sense.

**Comment by byroniac** [comment]
Not shown by default.

https://learn.microsoft.com/en-us/answers/questions/1297325/azure-data-studio-not-showing-system-views
[https://learn.microsoft.com/en-us/media/open-graph-image.png]<https://learn.microsoft.com/en-us/answers/questions/1297325/azure-data-studio-not-showing-system-views>
Azure Data Studio not showing system views - Microsoft Q&A<https://learn.microsoft.com/en-us/answers/questions/1297325/azure-data-studio-not-showing-system-views>
I have recently started using Azure Data Studio as well as SSMS. If I connect to a database in SSMS and go to the object explorer under views there is a system views folder that I can browse. If I connect to the same database in Azure Data Studio using…
learn.microsoft.com


Byron
Cell: 409-790-6008
Skype: 409-234-9011

________________________________
