### ISSUE TITLE
New notebook sends me to existing unsaved notebook-x

### ISSUE THREAD

**Issue by Silverutm** [microsoft/azuredatastudio#21073]
Issue Type: <b>Bug</b>

This happens when I reopen azure data studio and I have several unsaved notebooks (Notebook-0, 1, 2,...)
Then I go to a server and right click create new notebook, and it sends me to the unsaved already existing Notebook-0, if I clic create new nootebook again it sends me to NB-1 (that already exists and was unsaved), and I have to do this several times (nb 2 then nb 3...)until I finally get a really new notebook,

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
kusto|Mic|0.5.4
profiler|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
@corivera can you take a look at this please?

**Comment by corivera** [comment]
Sure

**Comment by corivera** [comment]
@chlafreniere Looks like notebooks don't show up in azdata.nb.notebookDocuments until we click on that notebook's tab, which throws off the search for a free editor title in the New Notebook command. If I open ADS with 10 notebook tabs already open, then when I click New Notebook it only sees the currently open notebook. But if I click through all those tabs first then it correctly opens an editor as "Notebook-10" (zero indexed titles). Does that sound familiar to you?
