### ISSUE TITLE
ADS Does Not Populate Location, Resource group, or Azure SQL Managed Instance Drop Down Lists (Azure Gov)

### ISSUE THREAD

**Issue by chrisbaudo** [microsoft/azuredatastudio#21074]
- Azure Data Studio Version: 1.39.1
- OS Version: Windows 10 Enterprise N

Steps to Reproduce:

1. Start a database assessment for a SQL Server VM in Azure Government
2. Choose Azure SQL Managed Instance as the Azure SQL target
3. Click Next and notice that the Subscriptions are populated, but the remaining drop-down lists are not

I do have Azure Government enabled in the Settings of Azure Data Studio and can browse to all the Azure resource under my Azure Gov account.  I also have Owner permissions for the subscription which contains the Azure SQL Managed Instance.

Does this issue occur when all extensions are disabled?: Yes, this is the only extension I have installed at this point.

**Comment by cheenamalhotra** [comment]
Hi @chrisbaudo 

To help us identify where this issue occurs, could you confirm if you meant to start a SQL Assessment or Azure SQL Migration, and does it seem related to https://github.com/microsoft/azuredatastudio/issues/20275 ?

**Comment by chrisbaudo** [comment]
I was doing an Azure SQL Migration, and I'm 99% sure I have the same issue as #20275 in that the wrong management endpoints are being used.  Azure Government endpoints need to be used if an Azure Government subscription is chosen.
