### ISSUE TITLE
 ip does not have access to the server, but I do

### ISSUE THREAD

**Issue by Silverutm** [microsoft/azuredatastudio#21072]
Issue Type: <b>Bug</b>

I keep receiving this pop up saying your ip does not have access to the server, but I do have access, (probably vpn tunneling), I just close it and query again, and the query works, but this things keeps comming up, a lot, and it's quite annoying

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
kusto|Mic|0.5.4
profiler|Mic|0.11.0

</details>

**Comment by cheenamalhotra** [comment]
Is that the firewall popup when connecting/refreshing connection with Azure? 
Have you tried specifying subnet range?

**Comment by cheenamalhotra** [comment]
Closing as inactive, and no repro information available.
