### ISSUE TITLE
Reconnect after saving notebook

### ISSUE THREAD

**Issue by Silverutm** [microsoft/azuredatastudio#21077]
Issue Type: <b>Bug</b>

Whenever right clic on a server and create a new book and run some queries, if after that I save the notebook, I have to connect again to server

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.10.1
import|Mic|1.5.0
kusto|Mic|0.5.4
profiler|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
Tracking this ask with #7681.
