### ISSUE TITLE
Encryption update notification should have different wording when there aren't any MSSQL connections

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21098]
Currently all users see the same message

![image](https://user-images.githubusercontent.com/28519865/199834247-41102f29-af1d-4881-bf42-02407424bdb2.png)

But this doesn't make much sense for new users or users who don't have any MSSQL connections. 

It'd be nice to have slightly different text when there aren't any saved MSSQL connections - or possibly even not showing the dialog at all in that case (since we'll still show the warning if they try to connect and get an SSL error then with basically the same content)

**Comment by cheenamalhotra** [comment]
cc @erinstellato-ms
