### ISSUE TITLE
Scripting errors returned by MySQL Tools Service are not being shown on the Script Error Dialog

### ISSUE THREAD

**Issue by rishky-msft** [microsoft/azuredatastudio#21091]
- Azure Data Studio Version: 1.40.0 insider's
- OS Version: Windows 11

Does this issue occur when all extensions are disabled?: Yes/No Yes

 

Hi Team,
Script errors returned by MySQL Tools Service are not being shown on the Script Error Dialog.
They are only coming in the output window as shown in the below screenshot.

<img width="1920" alt="MicrosoftTeams-image (1)" src="https://user-images.githubusercontent.com/102506628/199769527-af64a074-83c5-457d-a9e0-3cbce26f8520.png">

**Comment by alanrenmsft** [comment]
@rishky-msft 
 please go to your extension and edit \node_modules\dataprotocol-client\lib\main.js
line 800 and change it to `return Promise.reject(e);`
![image](https://user-images.githubusercontent.com/13777222/199861024-5472096c-752b-427e-89bc-334d5ed10aab.png)

then, run the reload ADS and retry the operation, let me know whether this does the job.

**Comment by rishky-msft** [comment]
@alanrenmsft 

Its working with the above change in dataprotocol client

**Comment by alanrenmsft** [comment]
@rishky-msft please update your sqlops-dataprotocolclient to latest version: https://github.com/microsoft/sqlops-dataprotocolclient/releases/tag/1.3.1

I noticed that you are using 0.3.0 which is really old, it might not be as easy as updating the package.json file, there could be compatibility issues.

**Comment by alanrenmsft** [comment]
@rishky-msft I created a patch release for 0.3.0 just in case there are too many issues need to be resolved in order to upgrade to 1.3.1. https://github.com/microsoft/sqlops-dataprotocolclient/releases/tag/0.3.1.

but you should just use this for the time being and upgrade to latest dataprotocol-client.
