### ISSUE TITLE
Support alt-key edits, to-uppercase, and to-lowercase in the editor (like SSMS and Visual Studio)

### ISSUE THREAD

**Issue by StyonsSoftware** [microsoft/azuredatastudio#21095]
In SSMS, Visual Studio, MS Word, Notepad++ and many other tools, you can hold down ALT+SHIFT+[up or down arrow keys] to edit multiple lines at once. 

You can also hold down CTRL+SHIFT+U to uppercase the selected text.

In Visual Studio (not SSMS) you can also do CTRL+U to lowercase the selected text. 

I use these features frequently, and I really miss them in ADS, which is in most other ways a really good tool.  Please bring the ADS editor to feature parity with SSMS and Visual Studio.

**Comment by Charles-Gagnon** [comment]
1. This is supported in Azure Data Studio (and VS Code) through the "Multiple Cursor" feature. See https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor for an explanation of how to use it. Note you can change the default keybinding for adding a new cursor (Ctrl+Alt+Up/Down) to something else (such as alt+shift+up/down) if you wish
2. Uppercase/Lowercase - these are available already but do not have a default keybinding assigning. You can give them one by opening the keyboard shortcuts editor (Ctrl+K -> Ctrl+S or by running the `Preferences: Open Keyboard Shortcuts` command and then searching for Uppercase/Lowercase and clicking `Add Keybinding`

I'd also suggest looking at the "SSMS Keymap" extension - this has a lot of the popular default keybindings from SSMS already set so you don't have to hunt around for them yourself!
