### ISSUE TITLE
Encryption update notification should tell user how to fix any issues

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21097]
The current text is very absolute, making it sound like the connections will be broken without a way to fix them which is a pretty scary thing for people to see pop up right after updating. 

I would suggest making it a little clearer that this is easily fixed - something like `...no longer working unless certain Encryption related connection properties are changed`.

![image](https://user-images.githubusercontent.com/28519865/199833876-d8f73786-afdd-4f3b-9e6d-dde8e7ad5716.png)

**Comment by cheenamalhotra** [comment]
cc @erinstellato-ms
