### ISSUE TITLE
Comment & Uncomment Selected text from a Query

### ISSUE THREAD

**Issue by MrAlex6204** [microsoft/azuredatastudio#2110]
I would like to comment & un comment selected text from a query instead the full row

Example  :

 Select * From Tbl_Temp Where Active  = 1 And Dept = 1024

Comment selected text " And Dept = 1024 " 
 Select * From Tbl_Temp Where Active  = 1  /*And Dept = 1024*/

 

- SQL Operations Studio Version: 0.32.2

Steps to Reproduce:

**Comment by kburtram** [comment]
The comment\uncomment behavior is part of the editor platform we inherit from vscode. We prefer to avoid significant changes to the base platform code as it is hard to maintain as we take continual vscode source code updates.  Please log this issue in the vscode repo for their consideration.  Thanks!
