### ISSUE TITLE
Intellisense doesn't update when a new column is added to a table

### ISSUE THREAD

**Issue by MrSimonC** [microsoft/azuredatastudio#2111]
Issue Type: <b>Bug</b>

Running:

```sql
USE [myDatabase]
GO
ALTER TABLE dbo.myTable ADD newColumn DATETIME NULL;
```

results in intellisense showing "newColumn" is not valid. I have to quit SQL Op Studio and reopen for it to refresh.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6400 CPU @ 2.70GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.68GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@MrSimonC you should be able to run the `Refresh IntelliSense Cache`  command to manually trigger an update.  I'll leave this open as a suggestion to handle the drift detection automatically.

**Comment by cheenamalhotra** [comment]
As suggested, "Refresh Intellisense Cache" should manually trigger an update to intellisense.
Closing as no-op.
