### ISSUE TITLE
Trying to download a notebook from a URI link fails

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#21114]
Repro Steps:
1. Open a notebook and create a text cell.
2. Click on the insert link button and use the following URI: azuredatastudio://microsoft.notebook/open?url=https://github.com/microsoft/azuredatastudio/blob/main/extensions/resource-deployment/notebooks/azuredb/create-sqldb.ipynb
3. No confirmation dialog pops up to download it, and a new tab opens with a resource not found error for that URI.

This works in the last stable release, but fails on main and in insiders. From some initial debugging, looks like our NotebookURIHandler in the notebooks extension isn't being hit at all after clicking that link, so maybe something changed with URI registration.

**Comment by Charles-Gagnon** [comment]
FYI - for what it matters the schema name is different for each different quality : 

`azuredatastudio://` - stable
`azuredatastudio-insiders://` - insiders
`azuredatastudio-oss://` - dev

**Comment by corivera** [comment]
With the oss part I no longer get the resource error, but nothing happens after clicking the link and there's still nothing hitting the URI Handler. There's also no errors in the log.

**Comment by barbaravaldez** [comment]
Setting the url as:  azuredatastudio://microsoft.notebook/open?url=https://raw.githubusercontent.com/microsoft/azuredatastudio/main/extensions/resource-deployment/notebooks/azuredb/create-sqldb.ipynb, fixes the issue.
