### ISSUE TITLE
Import flat file wizard on Macbook

### ISSUE THREAD

**Issue by nhuy4595** [microsoft/azuredatastudio#21124]
Import flat file wizard --> step 4: loading
(unable importing .csv file on Table)
<img width="714" alt="image" src="https://user-images.githubusercontent.com/117498048/200220130-f3c2ba1e-7f6a-41e4-a8d2-89d43d54fc4a.png">

**Comment by sophorn-thun** [comment]
I encountered the exact same issue. Did you happen to get this solved yet?

**Comment by pamelagumera1** [comment]
Hi, did you resolve the issue? I've been having the same problem since 2 days ago and was all over google to find the solution.

**Comment by alanrenmsft** [comment]
dupe of #21125, please refer to https://github.com/microsoft/azuredatastudio/issues/21125#issuecomment-1306006377.

sorry for the inconvenience.
