### ISSUE TITLE
Editing an existing database connection does not propagate all over

### ISSUE THREAD

**Issue by FairW** [microsoft/azuredatastudio#21127]
- Azure Data Studio Version: 1.39.1
- OS Version: Win 2019 server

Basic problem: Changing a database connection from using a db_owner user (or other "high level role"? - I haven't tested) to a user which only has GRANT EXE on Store Procedures, does NOT refresh the credentials for server tree structure fully. The "old" users credentials seems to "hang around" in some parts.

Steps to Reproduce:

1. Use a SQL User with db_owner to a given database
2. Create a SQL user with no roles assiged except for running USPs (GRANT EXECUTE)
1. Create a database connection towards an existing using user in 1. All tables etc are listed you can select from database etc. All good.
3. Edit the connection to use user described in 2.
4. The Connection displays the new user in the server view (see yellow underline in screen dump)
5. BUT if you expand tables node i tree structure ; all tables are displayed (they should not be) . Right click on a table and choose Select Top 100 gives you the data (it should not since we now have changed user for connection). Refresh does not help to resolve this; the OLD user (before connection edit is still used)
6. doing CTRL + N with cursor marked under the edited db conn also uses the previous connection with the wrong credentials; again you are able to do a select from this new query window.
7. Right click the Server node and select New Query from pop up menu uses the New, correct sql user 

Does this issue occur when all extensions are disabled?: Yes

![image](https://user-images.githubusercontent.com/16018281/200345579-5d11098e-6698-4fbf-91a1-125c3fdcd4cb.png)

**Comment by cheenamalhotra** [comment]
Hi @FairW 

We have addressed this issue recently, could you please try the latest insiders build and let us know if you still experience issues?

You may download insiders build from here:
https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by FairW** [comment]
Confirmation: Insiders Build 1.40.0 has fixed the issue I posted! Thanks!
