### ISSUE TITLE
CSV import not going through

### ISSUE THREAD

**Issue by loony-alice** [microsoft/azuredatastudio#21125]
Issue Type: <b>Bug</b>

The CSV import to an Asure SQL Database used to work fine until an update in early November. Now, I get a message in the extension's "Runtime Status" saying this:

Cannot read property 'Integrated' of undefined

There is no issue with the connection. I am able to query the existing contents of the database without issues. It is just the import which fails.

Extension version: 1.5.1
Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 20.6.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 17, 15|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pamelagumera1** [comment]
Hi, did you find how to fix this? I'
ve been having the same issue since 2 days ago.

**Comment by loony-alice** [comment]
> Hi, did you find how to fix this? I' ve been having the same issue since 2 days ago.

I have only managed a workaround - by using DBeaver for the upload. I'm still faced with the issue on Azure Data Studio.

**Comment by alanrenmsft** [comment]
@loony-alice @pamelagumera1 sorry about the inconvenience, I just released a new release that reverted the recent changes to the extension. the new version is 1.5.3. it should be available in a few minutes, please restart your ADS to pick it up.

let me know if it still doesn't work.
