### ISSUE TITLE
Updating the version of DacFx in ADS

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#21138]
- Azure Data Studio Version:
- OS Version:

The version of DacFx that ADS is using right now includes a commit which can potentially cause regression for some users. The change is related to a system schema name which SQL Server introduced recently and we added a change in DacFx to exclude any objects with that schema name in the bacpac.  It is possible users have schema in their db with the same name and that causes those objects to be excluded from export.  The change in dacfx could potentially cause regression for those users so it was reverted. We need to update ADS to use a version of DacFx with that change reverted. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
closing this one as the DacFx update will be done as part of the fix for #21151
