### ISSUE TITLE
Remove/hide newlines in XML results

### ISSUE THREAD

**Issue by StevenHibble** [Microsoft/azuredatastudio#2114]
SQL Operations Studio Version: 31.4

Run the following `SELECT CONVERT(XML, 'a'+CHAR(13)+'b'),'a'+CHAR(13)+'b'`

Expected: Both columns _shouldn't show_ a new line. Both still have a newline on copy+paste or save to file.
Actual: The XML column only shows the first line. The normal text column behaves as expected.

This helps a lot with previewing XML values. I encounter this most often with sp_WhoIsActive, where I want to scan the sql_text column quickly to find the query I'm interested in. In Ops Studio, all that's visible in the grid is "<?query --".

**Comment by anthonydresser** [comment]
We have a option that does something like what you are looking for `"sql.copyRemoveNewLine": true`

**Comment by StevenHibble** [comment]
That's not quite it, but it looks like this behavior exists in 1.1.3.
