### ISSUE TITLE
cell editor doesn't have horizontal scrollbar

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#21145]
![image](https://user-images.githubusercontent.com/13777222/200442820-4f5a73c6-4ed2-4445-9648-7bf54e89087b.png)

the first line is a very long line and I don't have word wrap enabled, I am expecting the scrollbar but it is not there.

**Comment by kburtram** [comment]
Closing as "Won't Fix" with the workaround to use word wrap in this scenario.  Per the discussion above.
