### ISSUE TITLE
[Table Designer] Cannot edit IsComputed for a computed column

### ISSUE THREAD

**Issue by caohai** [microsoft/azuredatastudio#21151]
Once a column is changed to computed (isComputed enabled), you cannot change it back to normal column. This is a regression from August release.

**Comment by PraveenMacherla** [comment]
when this will be implemented?

**Comment by caohai** [comment]
> when this will be implemented?

If you are talking about computed column support, it's been added since June release so if you are using latest version of ADS, computed column support should already be there.

This issue is for tracking a regression related to IsComputed setting and we'll be fixing this today.

**Comment by caohai** [comment]
Port PR https://github.com/microsoft/azuredatastudio/pull/21168 already merged to `release/1.40`, keep this issue open until PR to main is merged.
