### ISSUE TITLE
[SQL Migration] Missing Login migration and bug for SKU recommendation 

### ISSUE THREAD

**Issue by AkshayMata** [microsoft/azuredatastudio#21164]
- Azure Data Studio Version: 1.39
- OS Version: Windows 11 21H2

Steps to Reproduce:

1. Launch SQL Migration wizard, proceed to assessment and SKU recommendation steps
2. SKU recommendation fails due to error of malformed sql db 

Does this issue occur when all extensions are disabled?: Yes/No

Note: 
This bug is for tracking a port request to the release branch for sqltoolsservice / mssql in ADS. Discussed details internally with product team as part of ADS Shiproom.

Background:

Login Migration is new feature as part of its next extension release, which will happen off-cycle and independently of the ADS product release. However, some of these new features require backend changes to sqltoolsservice, which we are trying to release as part of ADS 1.40. Additionally, there was a bug with SQL SKU recommendation These changes include:

- adding the ability to migrate logins
- removes the creation of malformed SqlDB recommendations

Submitting this bug / port request now, as these changes were checked into STS just in time, but I didn't realize I had to also update STS version on ADS side before the code complete date.

Tested and verified that these changes are backwards compatible (tested by building STS locally, which includes these changes, and consumed from versions of the SQL Migration extension with the new changes and without). The PRs in question are the following:
https://github.com/microsoft/sqltoolsservice/pull/1728
https://github.com/microsoft/sqltoolsservice/pull/1681

**Comment by alanrenmsft** [comment]
@AkshayMata please verify the fix using the RC1 build and close the issue.

**Comment by AkshayMata** [comment]
@alanrenmsft  I believe @raymondtruong  tested the nugets part as well as the other features for the ADS release. I will verify, test and close the issue. Thanks for the follow up!

**Comment by AkshayMata** [comment]
@junierch tested the sku recommendation part: validation completed, it works fine, throws no more error on specific data set
I validated that my nuget changes are included in STS and doesn't break any existing migration features.
