### ISSUE TITLE
Cannot run anything when I did 'Join'

### ISSUE THREAD

**Issue by emessell** [microsoft/azuredatastudio#21192]
Issue Type: <b>Bug</b>

I excuted this query and stopped for twice.

UPDATE REPLACE_SHIP_NAME
SET REPLACE_SHIP_NAME.REPLACED_SHIP_NAME = POL_SHIP_NAME.SHORT_SHIP_NAME
FROM REPLACE_SHIP_NAME
    JOIN
    POL_SHIP_NAME
    ON REPLACE_SHIP_NAME.REPLACED_SHIP_NAME = POL_SHIP_NAME.SHIP_NAME

if something is weird, query should not start I think.
But it started and stopped. help.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:12:48.559Z)
OS version: Darwin x64 22.1.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (8 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|7, 4, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
could you please attach a screenshot? @emessell

**Comment by alanrenmsft** [comment]
@emessell could you please provide a screenshot and repro script?

**Comment by kburtram** [comment]
Closing based on no response to previous question for additional information.  Please let us know if you are still impacted by this issue.  Thanks!
