### ISSUE TITLE
Intellisense errors

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#212]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Enter a query using the $Partition function
2. Add OPTION (QUERYTRACEON 8649)

e.g.

select MAX(AccountNumber) from cert.USDemandCore_tmp
where $Partition.VisionPF(PartitionKey) in (10, 11, 12, 13, 14, 15, 16, 17, 25)
OPTION (QUERYTRACEON 8649)

Result:

Red squiggles under $Partition, PartitionKey, first member of IN list and QUERYTRACEON

Desired Result (no red squiggles)

**Comment by kburtram** [comment]
Closing this as "upstream" since the issue comes from the T-SQL Parser that is shared with SSMS.  We're not currently making this type of change to the parser as part of ADS, and will track language parsing bugs against the parser component directly.  Thanks for reporting!
