### ISSUE TITLE
New connection from schema compare doesn't show up in Active connections list

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#21209]
Steps to Reproduce:

1. Open Scmp
2. Add connections in schema compare dialog
3. The new connections don't show up in Active connections list.
![image](https://user-images.githubusercontent.com/57200045/201320263-02e75a37-5ceb-40de-a0d3-33156cd24d59.png)

**Comment by kisantia** [comment]
need to set SaveConnection to true when calling if we want the connection to show up https://github.com/microsoft/azuredatastudio/blob/12bca68a0dc29d4187862a3413b77c10e552cd5d/src/sql/azdata.d.ts#L187-L190

**Comment by SakshiS-harma** [comment]
Closing this issue, since the original problem is with Connections , not Schema Compare (https://github.com/microsoft/azuredatastudio/issues/21664)
