### ISSUE TITLE
[AzureDataStudio] 1.39.1  on Linux does not work with old Sql servers

### ISSUE THREAD

**Issue by jhay06** [microsoft/azuredatastudio#21204]
Hi Team,
   i will share my experience using azure data studio on my ubuntu 22.04 with version 1.39.1 

our company have some servers ST servers that are still in SQL version 2005 and 2008  , since it's ST servers it is not priority to them to migrate to newer version of SQL servers

on my windows workstation connecting to that servers using the latest version of azure is fine. i can connect using windows
but on the linux there's an error connecting to old SQL servers

please see below 
![image](https://user-images.githubusercontent.com/5191437/201246677-94c57822-3bdf-4bc2-8e37-c822fb6f2675.png)

i already tried enabling TrustServerCertificate but still the same 
![image](https://user-images.githubusercontent.com/5191437/201246765-0bb19cd6-6169-4101-9f21-e1df652b91e1.png)

on windows i dont need to enable it but still working 
on linux even i enable it , still not working 

any ideas ? 

actually i can connect to that servers using the DBeaver Community (i'm not endorsing it , just sharing my experiece) 
i have to use old TDS plugin . (actually i used this TDS driver on my php /python app to connect to old SQL  server)

**Comment by cheenamalhotra** [comment]
Hi @jhay06 

Please make sure you are able to negotiate a common TLS protocol with the server. As Linux operating systems now don't support anything below TLS1.2, it is possible that you will not be able to connect to a SQL Server if it doesn't support TLS 1.2. 
Please find guidelines to update SQL Server: [Enabling TLS 1.2 support in SQL Server](https://support.microsoft.com/en-us/topic/kb3135244-tls-1-2-support-for-microsoft-sql-server-e4472ef8-90a9-13c1-e4d8-44aad198cdbe)

If you cannot update SQL Server to support TLS 1.2, you can try to enable insecure protocols but please beware they may not be supported officially by Microsoft in the operating system hosting them. [Read SQL Server support policy for client drivers](https://learn.microsoft.com/troubleshoot/sql/general/use-sql-server-in-windows)

You can find some helpful comments from community to unblock yourself if TLS 1.2 support is not feasible: https://github.com/dotnet/SqlClient/issues/776#issuecomment-760798110

**Comment by jhay06** [comment]
hi @cheenamalhotra  , thanks for the response .  how can i enable insecure protocols ?

**Comment by cheenamalhotra** [comment]
The link https://github.com/dotnet/SqlClient/issues/776#issuecomment-760798110 takes you to solutions.

**Comment by jhay06** [comment]
hi @cheenamalhotra  , already did workarounds from the link but it doesn't solve the problem , is there a way i can change the driver of azure used ? 

the only working for those server as off the moment . is the old JTDS driver , right now i can work with those old servers using the DBeaver , but the UI of this app is not so good and very far from the SQL Studio design, azure data studio Ui is more closely to SQL Studio Management and easy to use.

**Comment by cheenamalhotra** [comment]
@jhay06 

Can you try using the latest ADS version (1.40) with TLS1 configuration enabled on your client using:

```
RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo -e "\n\n[default_conf]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA" >> /etc/ssl/openssl.cnf
```

**Comment by NCVIDevASD** [comment]
> 

still not working

**Comment by jhay06** [comment]
> @jhay06
> 
> Can you try using the latest ADS version (1.40) with TLS1 configuration enabled on your client using:
> 
> ```
> RUN sed -i '1i openssl_conf = default_conf' /etc/ssl/openssl.cnf && echo -e "\n\n[default_conf]\nssl_conf = ssl_sect\n[ssl_sect]\nsystem_default = system_default_sect\n[system_default_sect]\nMinProtocol = TLSv1\nCipherString = DEFAULT:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA:ECDHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA256:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:DES-CBC3-SHA" >> /etc/ssl/openssl.cnf
> ```

still not working

**Comment by jhay06** [comment]
Maybe adding support to TDS driver might help ?

**Comment by cheenamalhotra** [comment]
Hi @jhay06 

Reading more about it, It seems you may be using OpenSSL 3.0, and they did a breaking change that causes TLS v1 and v1.1 to not work with SECLEVEL=1 anymore, found this mentioned here: https://github.com/microsoft/msphpsql/issues/1419#issuecomment-1303626500

Recommendation would be to use, can you please try?
```
[system_default_sect]
CipherString = DEFAULT:@SECLEVEL=0
```

Also, when it comes to issues like these, it's not ADS or underlying SqlClient issue, or any other driver. This can happen with any driver that relies on environment OpenSSL settings. DBeaver uses mssql-jdbc which works differently as it supports TLS setting with FIPS, so is not the same.

**Comment by jhay06** [comment]
> Hi @jhay06
> 
> Reading more about it, It seems you may be using OpenSSL 3.0, and they did a breaking change that causes TLS v1 and v1.1 to not work with SECLEVEL=1 anymore, found this mentioned here: [microsoft/msphpsql#1419 (comment)](https://github.com/microsoft/msphpsql/issues/1419#issuecomment-1303626500)
> 
> Recommendation would be to use, can you please try?
> 
> ```
> [system_default_sect]
> CipherString = DEFAULT:@SECLEVEL=0
> ```
> 

It doesn't work either.


> Also, when it comes to issues like these, it's not ADS or underlying SqlClient issue, or any other driver. This can happen with any driver that relies on environment OpenSSL settings. DBeaver uses mssql-jdbc which works differently as it supports TLS setting with FIPS, so is not the same.


the default mssql-jdbc of dbeaver is not working on the SqlServer that i 'm connecting to.   i'm using jdbc:jtds  on dbeaver 
it uses FreeTDS driver ,

**Comment by cheenamalhotra** [comment]
Well in that case I don't think we can do much here, if there's a Microsoft owned driver that works in your environment and ADS does not, we can provide support for making that use case work, otherwise jTDS is not a bar to meet, it's outdated and insecure. 

ADS does not intend to support insecure protocols, and neither maintains any hooks to change underlying driver like that.
I would highly recommend upgrading your server to at-least SQL 2012 so you can get the security and benefits from Microsoft owned client drivers and tools.

**Comment by cheenamalhotra** [comment]
Closing this issue as nothing much can be done in ADS for legacy server support.

**Comment by jhay06** [comment]
i found out that when i downgrade my openssl 3 to openssl 1.1.1 , connecting to old sql is  working now
