### ISSUE TITLE
Excluding the last child of a folder in SQL Projects also hides the parent folder.

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#21216]
Steps:
1. Create a new SDK-style project (Framework-style projects work fine because they explicitly list each folder)
2. Create a new folder `Folder1` in the project - the empty folder is visible
3. Create a new file `Script.sql` in `Folder1`
4. Exclude or Delete `Script.sql` from the project

Expected:
`Folder1` is still visible in the project tree

Reality:
`Folder1` is automatically removed/excluded from the project because it's empty, even though this is the same state as at the end of Step 2.

This can result in confusing behavior if the user wants to put something back into that folder.  Attempts to create a new `Folder1` fails because the folder already exists on disk.  `Folder1` cannot be re-added to the project using "Add Existing Item..." because that only allows selection of files, not folders.

**Comment by kisantia** [comment]
Should get addressed in the current project xml parsing work in DacFx

**Comment by kisantia** [comment]
@Benjin is this fixed now with the DacFx.Projects library?

**Comment by Benjin** [comment]
Yeah, it should be.  It'll keep the (empty) folder around if there's a `<Folder Include>` entry in the .sqlproj, but it'll disappear if it's the last file.  I'll verify that randomly adding and deleting entries doesn't result in any "error: folder already exists" messages.

**Comment by Benjin** [comment]
Confirmed fixed.
