### ISSUE TITLE
Newly added connection doesn't get auto-populated in schema compare dialog

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#21210]
Steps to Reproduce:

1. Open schema compare dialog from within a server/server>database
2. Click ... to open schema compare dialog.
3. Add a new connection using + sign beside the server information.

Expected: New connection gets added to the server dropdown in schema compare dialog and auto populates as the Server information.
Actual: New connection auto populate as the Server information.

**Comment by kisantia** [comment]
I see the source connection staying as the original connection and the target connection getting updated to the new connection:

![schemaCompareNewConnection](https://user-images.githubusercontent.com/31145923/201401237-9986b243-70a8-4692-81fb-342ffb78cde3.gif)

**Comment by SakshiS-harma** [comment]
> 

It is working when the new connection is been added to the Target server, but not for Source server. I will investigate it further if this is really a code issue or some problem with my machine.

**Comment by SakshiS-harma** [comment]
Here is a gif capturing the issue.
![scConnectIssue](https://user-images.githubusercontent.com/57200045/213805088-5f3d2699-687f-4f32-b01e-8bd5fe36c04c.gif)

It only happens when Schema compare extension starts from within a database/server context. If no context is provided while starting SC, and new connections are added, they work as expected. In the attached gif, SC starts from server context, and when new connection is added at the source, the connection gets added to the drop down but doesn't get populated as the server info.
