### ISSUE TITLE
Cannot select top 1000

### ISSUE THREAD

**Issue by ChrisCottellNH** [microsoft/azuredatastudio#21212]
Issue Type: <b>Bug</b>

When clicking "Select top 1000" option on a table nothing happens on certain Azure warehouses.

Selecting "Script as Create" works and the select option works on other SQL databases.

Our IT have been over it and reinstalled ADS. This impacts some other users but not all.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.76GB (6.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.3

</details>

**Comment by alanrenmsft** [comment]
@ChrisCottellNH the issue has been fixed, the upcoming release (mid next week) will have the fix.

**Comment by alanrenmsft** [comment]
dupe of https://github.com/microsoft/azuredatastudio/issues/20241

**Comment by Charles-Gagnon** [comment]
If you get a chance you can try it out with the latest [Insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) build in the meantime - and let us know if you're still seeing issues!
