### ISSUE TITLE
Create project from database doesn't work in vscode mssql

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#21211]
Try to create project from database. It fails with the following error:
![image](https://user-images.githubusercontent.com/57200045/201329558-09f89412-80c1-4297-b6a8-2819a06514a2.png)

**Comment by kisantia** [comment]
This error is because vscode-mssql hasn't been released with the change in https://github.com/microsoft/vscode-mssql/pull/17445. We'll hold off on updating sql projects in vscode until the next vscode-mssql extension update

**Comment by kisantia** [comment]
closing since this will not be an issue as sql-database-projects-vscode will be updated at the same time as vscode-mssql goes out with the necessary api changes
