### ISSUE TITLE
Installed docker not found

### ISSUE THREAD

**Issue by Mootfrost777** [microsoft/azuredatastudio#21220]
- Azure Data Studio Version: 1.39.1
- OS Version: Arch linux with kde plasma 5.26

Steps to Reproduce:

1. Install it via pacman
2. Try to deploy container

Error message:
'docker' was not discovered and automated installation is not currently supported. Install 'docker' manually or ensure it is started and discoverable. Once done please restart Azure Data Studio. See [https://docs.docker.com/install] .
You will need to restart Azure Data Studio if the tools are installed manually to pick up the change. You may find additional details in 'Deployments' and 'Azure Data CLI' output channels

Does this issue occur when all extensions are disabled?: No, but there is no extensions installed!

**Comment by alanrenmsft** [comment]
@Mootfrost777 have you added it to the PATH environment variable? open the terminal in Azure Data Studio and run `docker`, you should be able to tell whether docker is discoverable.

**Comment by alanrenmsft** [comment]
Thanks @seanjseymour.
