### ISSUE TITLE
Increase scrollbar height for horizontal scroll of grid query results

### ISSUE THREAD

**Issue by Zeddox** [microsoft/azuredatastudio#21231]
Issue Type: <b>Feature Request</b>

The horizontal scrollbar is very thin on the grid query results, making it difficult to scroll without accidentally selecting a cell. The vertical scrollbar has a wide scroll thumb and is easy to select via the mouse.

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No

**Comment by alanrenmsft** [comment]
@Zeddox just to confirm you are talking about the bottom h-scroll bar in the image below, right?

![image](https://user-images.githubusercontent.com/13777222/202327761-bad1ad0e-3cf0-4c99-9dc7-7e7010d0d847.png)

**Comment by Zeddox** [comment]
@alanrenmsft Yep that is the one I'm referring to

**Comment by alanrenmsft** [comment]
@Zeddox please try the [latest insider build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and see whether it is fixed for you.
