### ISSUE TITLE
Comment Command Missing

### ISSUE THREAD

**Issue by azeembh** [microsoft/azuredatastudio#21236]
Issue Type: <b>Feature Request</b>

There shall be toolbar/menus like SQL Server Management Studio with some important featrues like following

1. Comment/Uncomment/Block Comments
2. Document Formatting

and more....

Azure Data Studio version: azuredatastudio 1.39.1 (7553f799e175f471b7590302dd65c997b838b29b, 2022-08-30T01:11:13.047Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by Charles-Gagnon** [comment]
You can assign shortcut keys to these commands already (in addition to just running the command directly from the command palette), is there a specific reason you want an actual button for these?
