### ISSUE TITLE
Add Column headers in copy paste 

### ISSUE THREAD

**Issue by vikarBCC** [microsoft/azuredatastudio#21246]
**Is your feature request related to a problem? Please describe.**
When copying output from results pan, I can select all the records and copy them but there is no option to copy column headers.

**Describe the solution or feature you'd like**
Provide 'Copy with Header' option similar to SSMS while copying result data from result pan.

**Comment by alanrenmsft** [comment]
@vikarBCC it is already there: 
![image](https://user-images.githubusercontent.com/13777222/202314765-25eaff78-eedc-4242-a2d1-e1e63ae30319.png)
