### ISSUE TITLE
Connecting to named instance

### ISSUE THREAD

**Issue by HealisticEngineer** [microsoft/azuredatastudio#2124]
Issue Type: <b>Bug</b>

I was unable to connect to a named instance Server\Instance however was able to connect to the Server,Port

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.84GB (2.98GB free)|
|Process Argv|C:\Users\John\Downloads\sqlops-windows-0.31.4\sqlops-windows\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
server-report|Mic|0.1.3

</details>

**Comment by kburtram** [comment]
@HealisticEngineer I wasn't able to repro this locally.  Do you happen to have any additional repro steps that may be helpful for us to diagnosis?  Do you know if there are there any errors in the "Help -> Developer Tools" Console pane?

![screen](https://user-images.githubusercontent.com/599935/43804809-3009b814-9a52-11e8-891a-5682ccad8a77.png)

**Comment by HealisticEngineer** [comment]
I have done some more testing and the issue is limited to non standard ports.
If the name instance is running on 1433 all works as expected however when port is something else say 7777 for example it does not manage to resolve this.

While SSMS does not require the port number to work.
