### ISSUE TITLE
Azure Data Studio Notebooks Intellisense Cache

### ISSUE THREAD

**Issue by jmetape** [microsoft/azuredatastudio#21252]
Mac:
- Azure Data Studio Version: Version: 1.39.1
- OS Version: Monterey 12.5.1  (21G83)

Windows:
- Azure Data Studio Version: Version: 1.39.0
- OS Version: Windows 10 Pro Version 20H2

Hi, I've noticed that my SQL notebooks will take a long time to refresh the intellisense compared to a .sql file. When I create a new object, no matter how many times I "Refresh Intellisense Cache", the object will not show up in intellisense until I close the notebook, reopen, reconnect, etc (and even then, that may not cause the intellisense to refresh). However, the newly created object shows up immediately after a cache refresh in a .sql file.

I've noticed this on every database I connect to--be it on prem, in the cloud, etc.

I have both a PC and a Mac and it happens on both  of them. Any ideas?

<img width="1222" alt="image" src="https://user-images.githubusercontent.com/10228011/200970770-357e7c49-c0ab-4229-a879-5e5a2a3fb7ed.png">

Does this issue occur when all extensions are disabled?: Yes

**Comment by chlafreniere** [comment]
@corivera can you investigate please?

**Comment by corivera** [comment]
Sure
