### ISSUE TITLE
Editing saved connection pre-fills connection details with wrong Azure AD tenant when B2B guest tenant is saved on saved connections

### ISSUE THREAD

**Issue by jikuja** [microsoft/azuredatastudio#21254]
- Azure Data Studio Version: 1.14.10
- OS Version: OS X 10.15.7 / Windows 10

Steps to Reproduce:

1. Open connections blade
2. Select saved connection that is using B2B guest Azure AD tenant for auth
3. click context menu of connection and click edit
4. Expand SQL database
6. Connection blade with pre-filled connection details open
7. Prefilled Azure AD tenant is set to home tenant instead of B2B guest tenant that was used when connection was saved

Does this issue occur when all extensions are disabled?: Yes

Some tenant selection persistency were fixed on 1.14.10 but this and other connection detail pre-fill logic are still misbehaving.

**Comment by cheenamalhotra** [comment]
Closing as resolved
