### ISSUE TITLE
Connect button on server blade/Azure prefills wrong Azure AD tenant information on Connection details when selected server/database is on B2B guest tenant

### ISSUE THREAD

**Issue by jikuja** [microsoft/azuredatastudio#21253]
- Azure Data Studio Version: 1.14.0
- OS Version: OS X 10.15.7 / Windows 10

Steps to Reproduce:

1. Open connections blade
2. Expand Azure section
3. Select subcription that is on B2B tenant guest AAD
4. Expand SQL database
5. Select existing database and click connect icon
6. Connection blade with prefilled connection details open
7. Pre-filled Azure AD tenant is set to home tenant instead of subscription tenant in step 3

Without changing Azure AD tenant login will fail with `Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.`

Does this issue occur when all extensions are disabled?: Yes

Some tenant selection persistency were fixed on 1.14.10 but this and other connection detail pre-fill logic are still misbehaving.

**Comment by cheenamalhotra** [comment]
Closing as resolved
