### ISSUE TITLE
Find Next triggers Find Next Select on tab change

### ISSUE THREAD

**Issue by Zwergin** [microsoft/azuredatastudio#2126]
Issue Type: <b>Bug</b>

It appears when changing tabs, the Find Next (default [F3]) triggers the Find Next Select (default [Ctrl-][F3]) action where the cursor is sitting, loosing the previously searched find next value.

I noticed this when the default cursor position got reset changing tabs and I tried to use Find Next.  That problem should now be resolved and make this problem less obviously noticeable, but I feel it is still a bug.

SQL Operations Studio version: sqlops 0.30.6 (df7e3ec7d52a82febee5b597a1019cabf021b883, 2018-06-19T21:45:43.589Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz (4 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.87GB (4.66GB free)|
|Process Argv|C:\Apps\PortableApps\sqlops\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by yualan** [comment]
In the latest insider build (https://github.com/Microsoft/sqlopsstudio/releases), it appears to have the same behavior as VS Code, now that the cursor position is kept at the same place when switching tabs. Pressing F3 or Ctrl+F3 seems to do the same thing. 


Can you try and see if it fits expected behavior?

**Comment by Zwergin** [comment]
Somewhat. This has a close to similar behavior, obfuscated if the cursor is still on the last "word" in the tab when you press F3 to activate the "Find Next" action, but if the cursor is on another word when you leave the tab and return, you will see it actually executes the Find Next Selected Ctrl+F3 action.  It was far more effective after that fix, but still not similar.  

It seems the F3 search feature is maintained universally across the VS Code's application's project not just the page/tab of SQL code. (Possibly all application windows and not just project... I forget,) .  

You could try to keep a Search Value per tab, but I suggest having a Search Value for the entire workbook allowing you the following:
1. Continue your current/prior Find Next/F3 on any current tab from the cursor's position.
2. Future idea: Have an advanced option In your dialog to continue find Next/F3 on every open tab in the entire workbook.

**Comment by kburtram** [comment]
This appears to be working correct in latest builds as far as I can tell.  The behavior comes from upstream vscode so if there continue to be bugs in this scenario we would probably want to try to get those fixed there.  Please let us know if you're still impacted by this bug.  Thanks!
