### ISSUE TITLE
service component could not start popup when opening Flat File Import Wizard

### ISSUE THREAD

**Issue by Liriel** [microsoft/azuredatastudio#21267]
- Azure Data Studio Version: 
Version: 1.40.0-insider
Commit: 9d921e4efc2a00c5c9c8f440c32fa2f6c9277737
Date: 2022-11-02T05:43:35.004Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Linux x64 5.10.150-gentoo
- OS Version: Linux x64 5.10.150-gentoo

Steps to Reproduce:

1. open "Flat File Import Wizard" 
2. error gets displayed

the installation seems to work fine, additional deps get pulled in on first start but after that the generic error message is displayed and thats it.

Nothing suspicious in the output window, selecting "Flat File Import Service" in the dropdown comes up empty. 

There is an error in the JS console though:
![image](https://user-images.githubusercontent.com/1565257/202743772-6331eabe-6c2b-49ef-b861-98e66519331b.png)

**Comment by frankdragan** [comment]
The same in Ubuntu 22.10 and Azure Data Studio 1.40.1 with SQL Server Import 1.5.3

**Comment by aasimkhan30** [comment]
dup of #21313
