### ISSUE TITLE
Azure Data Studio for ARM installer proposes incorrect installation directory

### ISSUE THREAD

**Issue by iemejia** [microsoft/azuredatastudio#21266]
- Azure Data Studio Version: Daily Insiders
- OS Version: Windows 11 for ARM

Steps to Reproduce:

1. Run the Azure Data Studio Insiders installer for ARM64
https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch
2. The installer proposes to install in the `Program Files (x86)` path
I am not sure what is the standard in this case since I see some native ARM installers propose `Program Files (Arm)` but VS Code proposes the main `Program Files`, probably the latter avoids the issue for all versions.

![Screenshot_20221118_094455](https://user-images.githubusercontent.com/79476/202662120-f48ed948-4f0a-4bc0-aade-25b8b51fda98.png)

**Comment by iemejia** [comment]
@alanrenmsft don't hesitate to ping me when this is ready to double check.

**Comment by alanrenmsft** [comment]
thanks! @iemejia

**Comment by erinstellato-ms** [comment]
@iemejia you should be able to test this with the latest Insider build

**Comment by iemejia** [comment]
Yes @erinstellato-ms I tested it and now the installation directory looks correct.
I will take a second check once this gets released in the stable version. But all good 👍

**Comment by alanrenmsft** [comment]
@iemejia also the backend service to access MSSQL has also being converted to native ARM64 bits, you probably will notice some performance improvement.
