### ISSUE TITLE
Add Filter\Search to search for tables,views, procs, etc like SQL Server has. 

### ISSUE THREAD

**Issue by nigel108** [microsoft/azuredatastudio#21265]
**Is your feature request related to a problem? Please describe.**
Yes, my problem is that whenever i want to search for anything in a database, for example a table, I have to expand Database>Tables> then scroll through the list of tables manually to find it.

**Describe the solution or feature you'd like**
Why not copy SQL Server, instead of making me scroll to find the table or proc etc i want. Instead, I can right click on Tables and select the filter option , to filter down the Tables\Views\Procs etc. that I want to see.

**Describe alternatives you've considered**
I end up using SQL Server to find the objects and copying them and pasting them into Azure Data Studio which really sucks

**Additional context**
see attached

ads

![No Filter Context on Right Click Menu Azure Data Studio](https://user-images.githubusercontent.com/101629582/202642843-a2088424-8624-44b0-8480-a409cfcfd384.png)

ssms

![ssms Filter on Right Click](https://user-images.githubusercontent.com/101629582/202642849-1b7161e2-9c58-4976-b34f-d4b3fea00b2b.png)

**Comment by jmetape** [comment]
rt click on the connection in ADS and go to "manage". A new editor tab window will be opened. Ust the filtering capabilities there

![image](https://user-images.githubusercontent.com/10228011/202800800-0a6a3b6c-f274-44fc-86e9-7b71ef569e5a.png)

**Comment by nigel108** [comment]
@jmetape  not sure where you got that screen grab from, i only see a search database option. Also even if that did work, its a terrible user experience, if I'm working in a database, I don't want to go clicking on manage the server connection to find a stored procedure.

**Comment by aasimkhan30** [comment]
dup of #12932
