### ISSUE TITLE
view container for object explorer and Azure

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21284]
What's the view container id for the "Connections" view container?
I've been able to access the "notebooks" view container for extensibility but "connections" isn't the correct id for the Connections panel and I haven't been able to guess it so far. thank you!

![image](https://user-images.githubusercontent.com/12227241/202960375-bf002e2a-0fe1-4f66-890b-c61ee7ab10eb.png)

**Comment by Charles-Gagnon** [comment]
AFAIK you can't contribute to the connections view container like other built-in ones. It's special in that you have to add it to package.json `contributes.dataExplorer` instead (you still register the views as normal with `vscode.window.registerTreeDataProvider`.

See the [Azure Arc](https://github.com/Microsoft/azuredatastudio/blob/6ab25a6a56e35d982401fd0ff9041fd85ac63a01/extensions/arc/package.json#L36) for an example

**Comment by dzsquared** [comment]
thanks @Charles-Gagnon!

**Comment by Charles-Gagnon** [comment]
I've updated the section in the wiki for our contribution points with more info about this. 

https://github.com/microsoft/azuredatastudio/wiki/Contribution-points#dataexplorer

I'll also add a sample to https://github.com/microsoft/azuredatastudio/tree/main/samples when I have some time.
