### ISSUE TITLE
Expired AD Token causes cascading connection issues

### ISSUE THREAD

**Issue by aborremans** [microsoft/azuredatastudio#21286]
Issue Type: <b>Bug</b>

After the most recent update I am getting frequent connection errors when connecting to Azure SQL Databases. 

It appears that the connection problems start after I have authenticated using Active Directory and the token expires, when this occurs ADS does not appear to refreshing the token as expected.

![unpw_s](https://user-images.githubusercontent.com/13876614/203124939-0cc45fa2-e5ac-4975-8ad4-773e0fe710ce.png)

Once the active directory token expires, I then seem to be unable to connect to any Azure SQL databases using a username/password where I get an "Object reference not set to an instance of an object" error in addition to requests that utilize Azure Active directory tokens.

![ExpiredToken_s](https://user-images.githubusercontent.com/13876614/203125078-1180f623-9921-43d9-a5f6-5e8d26719f0b.png)

The only way that I can get out of this and create new database connections is by restarting ADS.

Azure Data Studio version: azuredatastudio 1.40.0 (3fbaa3de931ef433090fe3deb8c89cba99d7952b, 2022-11-11T22:47:05.361Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.74GB (15.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.4
import|Mic|1.5.3
query-history|Mic|0.5.3
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
sql-migration|Mic|1.1.2

</details>

**Comment by cheenamalhotra** [comment]
Hi @aborremans 

I believe this is an existing issue, as also identified here: https://github.com/microsoft/azuredatastudio/issues/21174
We're looking into it and will hopefully have it addressed it soon!

**Comment by cheenamalhotra** [comment]
Closing this one as duplicate, please track progress with https://github.com/microsoft/azuredatastudio/issues/21174
