### ISSUE TITLE
Azure "Default Authentication Type" setting is ignored

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21280]
Insiders/Dev

In https://github.com/microsoft/azuredatastudio/pull/21276 the default auth type given to SQL Server/DB nodes was changed to MFA.

This makes the feature added in https://github.com/microsoft/azuredatastudio/pull/16999 not work as intended since it only applies that setting if there isn't an auth type specified. 

Repro: 
1. Change default auth type to SqlLogin 
![image](https://user-images.githubusercontent.com/28519865/202872418-55dc4517-bf8a-4605-a66c-60a582e4364c.png)
2. Try to expand a server node (or click the connection action on the node) in the Azure tree on a server/DB that doesn't allow AzureMFA access (or with a user doesn't have permission)

Expected : The connection attempted is made with SqlLogin auth type - and if it fails opens up the connection dialog with SqlLogin set as the default

Actual : The connection tries to connect with AzureMFA, and when it fails opens up the connection dialog with AzureMFA selected

If this is the behavior that we want then we should probably just remove the setting since it doesn't really do anything and would just be confusing to users. 

Although ideally it would be best if we could detect what types of auth are supported and only show those ones (and have this setting be used to choose the best default when there's more than one option). That way for servers that only support one type of auth we don't try to use one that isn't even supported.

**Comment by Charles-Gagnon** [comment]
@kburtram You worked to get this feature in so maybe you and @cheenamalhotra should chat about what we want the intended behavior here to be

**Comment by Charles-Gagnon** [comment]
This also breaks loading saved connections - at least for servers that are SqlLogin only. 

1. Open Azure tree and expand server configured to only allow SqlLogins
2. Enter credentials and connect
3. Tree expands as expected
4. Reload ADS
5. Try to expand node again

Expected : Credentials entered in earlier are loaded and node expands without issue

Actual : Login error `Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. The server is not currently configured to accept this token.`

This is a regression from stable - if I have SqlLogin configured as the default auth type then it will load the password I had entered in earlier and expand without needing to re-enter anything.

**Comment by cheenamalhotra** [comment]
I'll admit I didn't realize this setting exists. Will address it soon!
