### ISSUE TITLE
Failed to start Flat File Import Service: Error: Unsupported platform: darwin

### ISSUE THREAD

**Issue by Darshkuma123** [microsoft/azuredatastudio#21313]
Trying to install sql .mdf in azure data studio on Mac m1 but facing this error.

**Failed to start Flat File Import Service: Error: Unsupported platform: darwin**

**Comment by alanrenmsft** [comment]
@Darshkuma123 please share the version of both Azure Data Studio and import extension, also the build flavor (intel, apple silicon or universal) .

**Comment by Shatha-Naami** [comment]
> @Darshkuma123 please share the version of both Azure Data Studio and import extension, also the build flavor (intel, apple silicon or universal) .

Hi @alanrenmsft 
I face the same problem, and I am going to provide the needed data
**Version of Azure Data Studio**
<img width="295" alt="image" src="https://user-images.githubusercontent.com/60509531/205377791-80e57d1b-555c-450b-a087-ec820b2f61c3.png">
**Version of import extension**
<img width="801" alt="image" src="https://user-images.githubusercontent.com/60509531/205377891-9c4069b3-d2ad-49f1-9868-147449bcd168.png">
**And my build flavor is** Apple M1 Pro

**Comment by stateout** [comment]
I'm on the M1 MacBook Air and I'm getting the same problem. I also happen to be using _SQL Server Import v1.5.3_
Here's a screenshot of my error message which seems to be identical to what Darsh is getting:
<img width="457" alt="image" src="https://user-images.githubusercontent.com/73503098/205511172-999af6d1-a4db-4949-99bd-f4ec2ad9e200.png">

**Comment by Darshkuma123** [comment]
Hello @stateout  I also was getting the same error as you and build is same as @Shatha-Naami . I found a work around  by installing mcr.microsoft.com/azure-sql-edge but facing a new error. Not able to establish db connection through ODBC

**Comment by Darshkuma123** [comment]
@alanrenmsft my build is same as @Shatha-Naami

**Comment by alanrenmsft** [comment]
@aasimkhan30 is this a dupe, if so please link them and close this one.

**Comment by rakesh-rootspace** [comment]
Hi, getting the same issue when connecting to Azure SQL.
_Failed to start Flat File Import Service: Error: Unsupported platform: darwin_

My version: 
MacBook Air M2, 2022 13.0.1, Azure Data Studio Version: 1.40.1

Works on my intel based MacBook Air 2015 when connecting to the same database.

**Comment by stateout** [comment]
> Hi, getting the same issue when connecting to Azure SQL. _Failed to start Flat File Import Service: Error: Unsupported platform: darwin_
> 
> My version: MacBook Air M2, 2022 13.0.1, Azure Data Studio Version: 1.40.1
> 
> Works on my intel based MacBook Air 2015 when connecting to the same database.

Hey Rakesh, I had a feeling that this Import Wizard was just not working for ARM64 systems. Knowing that this works on your Intel Mac confirms this hypothesis. Thanks for sharing!

**Comment by aasimkhan30** [comment]
@alanrenmsft , can you please verify it on your m1 mac? If it is working then please close this issue. Thank you!

**Comment by alanrenmsft** [comment]
@Darshkuma123 the issue has been fixed now.
