### ISSUE TITLE
Table designer throws object with same name exists when publishing changes

### ISSUE THREAD

**Issue by JetterMcTedder** [microsoft/azuredatastudio#21325]
- Azure Data Studio Version: 1.40.1
- OS Version: Win 11

Steps to Reproduce:

1. Create a new table using table designer
2. Name the table the same name as an existing table
3. publish the table to the database and you will get an object exists error
4. change the name of the table in the table designer
5. publish the table to the database and you will get an object exists error even though you changes the name of the table

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by JetterMcTedder** [comment]
@tdoshin

**Comment by caohai** [comment]
can repro, will take a look

**Comment by alanrenmsft** [comment]
@caohai is the fix in ADS now?
