### ISSUE TITLE
Remove use of fs.promises.rmdir with recursive

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21331]
The recursive option of fs.promises.rmdir has been deprecated since Node 14 (https://nodejs.org/api/fs.html#fspromisesrmdirpath-options) - fs.promises.rm should be used instead. 

Currently only one place in our code I see using that

https://github.com/Microsoft/azuredatastudio/blob/main/extensions/sql-database-projects/src/models/project.ts#L967

**Comment by SakshiS-harma** [comment]
I can take a look at it today. Thanks!
