### ISSUE TITLE
Diffrent color schema and UI with VS Code

### ISSUE THREAD

**Issue by mkorsukov** [microsoft/azuredatastudio#21330]
Environment:

- Azure Data Studio Version: 1.39.1
- VS Code 1.73.1
- OS Version: Ubuntu 20.04.5

Steps to Reproduce:

1. Run Azure Data Studio and VS Code
2. Open Source Control tab
3. Change file(s) in the same repo
4. See the difference in UI and colors

Example:

On left - VS Code
On right - Azure Data Studio

![image](https://user-images.githubusercontent.com/21244808/204861439-76b528d1-cc26-4e02-8de9-bf33d1c46b7c.png)

**Comment by Charles-Gagnon** [comment]
ADS doesn't keep up with the very latest changes in VS Code - we're usually a few months behind at least. So differences are expected. If there's any specific fixes/improvements you'd like to see please open a separate issue detailing exactly what you'd like to see brought over and we can look into cherry picking stuff as needed.

**Comment by kburtram** [comment]
We don't have the exact same codebase as VS Code so this is not unexpected.  We will pickup more recent vscode changes through an on-going process that lags behind a bit.
