### ISSUE TITLE
版本: 1.40.1 After the update, the speed of querying data is significantly slower

### ISSUE THREAD

**Issue by LinEven** [microsoft/azuredatastudio#21359]
Issue Type: <b>Performance Issue</b>

There will be a delay of 2 to 3 seconds after the data is displayed after pressing Execute
But not in the previous version, only 5 records

版本: 1.40.1 (user setup)
提交: 3a32679ab590c1023ab4de6f191769e7e127d25b
日期: 2022-11-22T18:30:25.850Z
電子: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
作業系統: Windows_NT x64 10.0.19045

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) W-2223 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (22.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   110	  6516	azuredatastudio main
    0	   231	  4696	   window (● SQLQuery_1 - c365.jy (sa) - Azure Data Studio)
    0	   100	  5008	   gpu-process
    0	    46	 10600	   utility-network-service
    0	   127	 17012	   extensionHost
    0	    38	 11420	     "c:\Users\even\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.3.1.2\MicrosoftSqlToolsCredentials.exe" --locale zh-tw --log-file c:\Users\even\AppData\Roaming\azuredatastudio\logs\20221205T082856\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical --autoflush-log
    0	    11	  9224	       console-window-host (Windows internal process)
    0	   129	 13952	     "c:\Users\even\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.3.1.2\MicrosoftSqlToolsServiceLayer.exe" --locale zh-tw --log-file c:\Users\even\AppData\Roaming\azuredatastudio\logs\20221205T082856\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical --autoflush-log
    0	    11	 17680	       console-window-host (Windows internal process)
    0	    39	 16648	     "c:\Users\even\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.3.1.2\SqlToolsResourceProviderService.exe" --locale zh-tw --log-file c:\Users\even\AppData\Roaming\azuredatastudio\logs\20221205T082856\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical --autoflush-log
    0	    11	 21332	       console-window-host (Windows internal process)
    0	   103	 18268	   shared-process
    0	    74	 12112	     ptyHost
    0	    77	 19160	     fileWatcher
    0	    93	 20836	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hant|Mic|1.40.1
azdata-sanddance|msr|4.0.1

</details>
貼上。

**Comment by alanrenmsft** [comment]
@LinEven 
1. what is the data size being returned?
2. did you compare the difference by using 2 versions side by side? I just want to rule out the changes happened on the server side. you can find the previous version from: https://github.com/microsoft/azuredatastudio/releases/tag/1.40.0

**Comment by alanrenmsft** [comment]
close since we didn't receive response from the user.
