### ISSUE TITLE
Translation in "Trust Server Cert" dialog causing problems with connections

### ISSUE THREAD

**Issue by jppo** [microsoft/azuredatastudio#21353]
- Azure Data Studio Version:  1.40.1
- <html>
<body>

Extension | Author (truncated) | Version
-- | -- | --
admin-pack | Mic | 0.0.2
ads-language-pack-fr | Mic | 1.40.1
agent | Mic | 0.49.0
dacpac | Mic | 1.11.0
import | Mic | 1.5.3
managed-instance-dashboard | Mic | 0.4.2
profiler | Mic | 0.11.0
sql-migration | Mic | 1.1.2

</body>
</html>
- OS Version: win 10
- <html>
<body>

CPUs | Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)
-- | --
GPU Status | 2d_canvas: enabled canvas_oop_rasterization: disabled_off direct_rendering_display_compositor: disabled_off_ok gpu_compositing: enabled multiple_raster_threads: enabled_on oop_rasterization: enabled opengl: enabled_on rasterization: enabled raw_draw: disabled_off_ok skia_renderer: enabled_on video_decode: enabled video_encode: enabled vulkan: disabled_off webgl: enabled webgl2: enabled
Load (avg) |  
Memory (System) | 31.95GB (16.73GB free)
Process Argv |  
Screen Reader | no
VM | 0%

</body>
</html>

Bonjour,
Je veux me connecter sur une nouvelle instance Azure Managed database mais c'est impossible du fait de la traduction !
Pour les boites de dialogue "Chiffrer" et "Approuver le certificat du serveur" il est proposé un choix limité à "vrai/faux" mais quand on tente de valider la connexion le problème apparaît avec le message suivant :
"Valeur non valide 'Faux' pour Chiffrer. Les valeurs valides sont 'Optional', 'Mandatory', 'Strict', 'True', 'False', 'Yes' et 'No'"
Les valeurs possibles sont en anglais et les valeurs proposées en français.
Que faire pour passer cette difficulté ?
Merci d'un retour rapide.

--
--
**Karl Burtram edit** - Add English translation below.

"Hello,
I want to connect to a new Azure Managed database instance but it's impossible because of the translation!
For the "Encrypt" and "Approve server certificate" dialog boxes, a choice limited to "true/false" is offered, but when you try to validate the connection, the problem appears with the following message:
"Invalid value 'False' for Encrypt. Valid values are 'Optional', 'Mandatory', 'Strict', 'True', 'False', 'Yes' and 'No'"
The possible values are in English and the proposed values in French.
What to do to overcome this difficulty?
Thank you for a quick return."

**Comment by cheenamalhotra** [comment]
Hi @jppo 

Are you able to specify Connection String and connect to the instance alternatively?

We will investigate this issue and update you soon!

**Comment by kburtram** [comment]
@jppo unfortunately we are only able to provide support in English on this Github repo.  I've added translations based on Google Translate.  From my understanding there is some issue with the new encryption settings being translated and breaking the connection in the driver.  You may be able to open the "User Settings (JSON)" from the Command Palette to edit the connection metadata directly to correct the translated values.  We'll investigate.

**Comment by jppo** [comment]
Hello,

I can write it in english.
The problem comes from the translation, the dialog boxes are in French and they send answers in French, the engine expects answers in English and it cannot work ....
I don't know how to fix this problem.
Regards
JP P

**Comment by ejacquemoud** [comment]
> Hello,
> 
> I can write it in english. The problem comes from the translation, the dialog boxes are in French and they send answers in French, the engine expects answers in English and it cannot work .... I don't know how to fix this problem. Regards JP P

Hello,

j'ai eu le même souci. J'ai pu passer outre en repassant Azure Data Studio en Anglais, puis en créant ma connexion. Une fois que tu as pu te connecter une fois avec l'interface en Anglais, tu peux repasser l'appli en Français et tout fonctionne normalement.
J'espère avoir pu t'aider !

**Comment by cheenamalhotra** [comment]
Hi @ejacquemoud @jppo 

The fix is available in the [latest Insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), and will be available in the next stable release.

**Comment by jppo** [comment]
Bonjour,

Merci, je vais essayer cela à la première occasion et Microsoft m'a signalé que
cet "ennui" serait corrigé dans la prochaine version.
Ah quand on traduit il ne faut pas trop en faire ... le mieux est l'ennemi du
bien.

Cordialement

JP Pozzi
