### ISSUE TITLE
Cannot delete connection with expired AAD credentials

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21363]
- Azure Data Studio Version: 1.40.1
- OS Version: macOS

Steps to Reproduce:
0. Have connections saved but AAD tokens are expired/require refresh
1. Right-click connection to try to delete the connection
2. ADS cuts to browser to try to refresh the connection (immediately trying to connect) instead of letting the context menu open
![2022-12-05_09-19-19 (4)](https://user-images.githubusercontent.com/12227241/205702441-7615b0f1-82f5-487b-a894-37992c0f7cd0.gif)

I can work around by manually editing the settings file to remove the connection, but this isn't ideal.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
I was able to reproduce the issue by forcing cache deletion. 
PR #21557 should address this.
