### ISSUE TITLE
missing diff color highlighting

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21368]
Issue Type: <b>Bug</b>

A schema compare from DB to sql proj where a column is only present on the sqlproj shows the difference in the compare but it is not highlighted.

<img width="1632" alt="image" src="https://user-images.githubusercontent.com/12227241/206039251-eb77e6d3-f77b-4f1f-a63f-59e5cbdb3c3a.png">

Extension version: 1.17.0
Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:22:25.529Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 2|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
I was also able to repro this when adding a new column to a table in AdventureWorks. This should just be doing a text diff, so it's strange that the color highlighting isn't working. 

When I tried with a simple table example, then the color highlighting did show up:
![image](https://user-images.githubusercontent.com/31145923/206324337-b4e3d9e7-ec8d-4705-9327-31ddd7f5e3b1.png)
