### ISSUE TITLE
tSQLt - Build error SQL70557: This assembly is corrupt or not valid

### ISSUE THREAD

**Issue by Robertas-V** [microsoft/azuredatastudio#21370]
Issue Type: <b>Bug</b>

* Download latest tSQLt framework version from https://tsqlt.org/downloads/
* Create database in your server (can be localhost)
* Run tSQLt.class.sql on that database to install it
* Run EXEC tSQLt.RunAll to confirm that framework works
* Create SQL Project from this database
* Build project and you will get "Build error SQL70557: This assembly is corrupt or not valid" and 37 warnings (which are correct)

This issue not appear if I build in VS SSDT - it just shows same 37 warnings.

Extension version: 0.20.0
Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (17.18GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details>

**Comment by samer1977** [comment]
Did this ever get fixed ? If not ADS is a looser to me

**Comment by dzsquared** [comment]
Copying a response from a linked item. https://github.com/microsoft/DacFx/issues/523

Unfortunately, SQLCLR is based only on .NET Framework, we can't support it on SQL projects with .NET 8 unless significant changes are done to the SQLCLR. To build a SQL project (including SDK-style SQL projects) with SQLCLR assemblies you would need to build it with msbuild and/or Visual Studio.

I'd encourage you to share feedback on SQLCLR to the SQL engine team via https://aka.ms/sqlfeedback
