### ISSUE TITLE
Closing multiple documents requires single answer per document.

### ISSUE THREAD

**Issue by pdesimone** [microsoft/azuredatastudio#2139]
Issue Type: <b>Bug</b>

Open alot of unsaved documents.

Choose Close All

You are prompted for each document being closed.

In SSMS, it gives you a list in a single dialog.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.21GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
I agree that this is really annoying, though this is the behavior we inherit from VS Code.  Not sure why they do it this way.  Let's investigate a bit.

**Comment by x3r10n** [comment]
We should have a setting to disable the save prompt on unsaved files.

**Comment by Pajn** [comment]
I agree that there should be a setting to disable the warning completely.
I don't understand why I would ever want to save a query after I have run it against the database.

**Comment by kburtram** [comment]
The file close, save as prompts are implement upstream.  We would prefer to see this addressed by vscode and will pick up any improvements.  If you use the Open Editors view in the File Explorer it should allow closing all unsaved documents with a single prompt.  Thanks for reporting this suggestion!
