### ISSUE TITLE
Operators in execution plans: improving readability and making Ops Studio easier to use for demos

### ISSUE THREAD

**Issue by LitKnd** [microsoft/azuredatastudio#2140]
Issue Type: <b>Feature Request</b>

In presenting and teaching, I often need to explain a detail about a variety of execution plan operators. 

This is currently quite difficult in Operations Studio for the following reasons:

1) There is no annotation tool for Mac that I have found which "freezes" the screen like the windows Zoomit tool does. While I can zoom in on a tooltip, I cannot draw an arrow to it with an annotation tool live, as the tooltip will disappear once I move the mouse. Having a way to "freeze" the tooltip or to highlight something on it with the mouse would be incredibly helpful.

   1) Related: like SSMS, it is incredibly easy to accidentally cause a tooltip to appear by moving the mouse close to it, which is distracting for the audience. If there is some way you can address item 1, and it involves a mode in which tooltips only appear if the operator is clicked on, that would make for a much cleaner experience for demonstrating the tool. (Everyday users probably like the hover behavior as it is standard, so I understand that you might not want to change the default experience.)

1) There is no properties pane or alternate way to display the detailed properties from execution plan operators as a workaround to issue #1. 

1) Large numbers on the tooltip are often very difficult to read. There are no commas used in the numbers, so it's difficult to tell 501 million from 5 million, for example. Also, sometimes scientific notation is used for very small numbers that is difficult for a human to read. (This problem also exists in SSMS.)  Using commas in large numbers and avoiding scientific notation for small numbers (even at the expense of precision) would improve this quite a bit.

1) There is currently no way to see most of the operator / plan properties that are displayed in SSMS on the properties pane, and not in the tooltip. These include thing like the compiled values for parameters, what the heck a compute scalar is doing, partition elimination information, the scan direction for an index operation, and a more readable view for the predicates / seek predicates on a query.

I know that probably none of this stuff is super simple to resolve, but just wanted to let you know what has been difficult in trying this out as a demo tool in my sessions.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T01:53:50.812Z)
OS version: Darwin x64 17.7.0

**Comment by aasimkhan30** [comment]
Closing this issue as we have implemented these features in the new execution plan
