### ISSUE TITLE
Excel export can't filter on dates

### ISSUE THREAD

**Issue by BisonFan** [microsoft/azuredatastudio#21404]
Issue Type: <b>Bug</b>

When I save as Excel, the date filter in Excel can't parse the dates correctly so that it can collapse all the dates in a year and let you expand specific years to get to the months.

If I copy the data to my clipboard, and paste it into Excel the date filtering works just fine.

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T19:35:40.769Z)
OS version: Darwin x64 22.1.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 5, 6|
|Memory (System)|32.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0

</details>

**Comment by alanrenmsft** [comment]
@caohai please take a look.

**Comment by BisonFan** [comment]
Yes, that it is what I'm referring to.  That behavior works if I copy the results to the clipboard and paste it into Excel. If I export it to Excel it doesn't work. 

![Screenshot 2023-01-11 at 1 56 52 PM](https://user-images.githubusercontent.com/44282133/211905255-d5a8af75-0119-491a-8dfa-f1d5aa601fb7.png)

**Comment by caohai** [comment]
> @caohai Yes, that it is what I'm referring to. That behavior works if I copy the results to the clipboard and paste it into Excel. If I save as Excel it doesn't work.
> 
> ![Screenshot 2023-01-11 at 1 56 52 PM](https://user-images.githubusercontent.com/44282133/211905255-d5a8af75-0119-491a-8dfa-f1d5aa601fb7.png)

I see. This feature was working for me when I tested it. I'm guessing it's some issue with the data in date column. Can you share the following if possible?
1. A copy of the Excel file (w/o any sensitive info) that data filter doesn't work.
2. The data type of the date column. (It would be great if you can provide a small script that can create a similar table and insert a few rows of data that have have this issue reproduced)

**Comment by caohai** [comment]
Needs more info to proceed, feel free to reopen once we have that.
