### ISSUE TITLE
A11y_Azure Data Studio_Toolbar_FindNode_Label: Visual label is not provided for combo boxes in the Find node pop up.

### ISSUE THREAD

**Issue by Truptik12** [microsoft/azuredatastudio#21414]
“[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”

### GitHubTags:
#A11yMAS; #A11yTCS; #A11ySev2; #SQL Azure Data Studio; #SH-SQL Azure Data Studio-Win32-OCT2022; #DesktopApp; #HeadingsandLabels; #WCAG3.3.2; #FTP;

### Environment Details:
Application Name: Azure Data Studio
Windows Version: Windows 11

### Repro Steps:

1. Launch the "Azure data studio" application.
2. Connect with the provided "sqltools2019-3" SQL server.
3. TAB to "New Query" button and hit ENTER key.
4. Enter the SQL query and TAB to "Estimated Plan" button and hit ENTER key.
5. "Query Plan (Preview) screen appear.
6. TAB to the toolbar present at right side of the screen.
7. TAB to "Find Node" button and hit ENTER key.

### Actual:
Visual label is not provided for combo boxes in the Find node pop up.

### Expected Result:
Visual label should provided for combo boxes in the Find node pop up.

### Attachment:
![image](https://user-images.githubusercontent.com/86710491/194818046-9e583727-7af6-4a20-8b50-8fa888d1a494.png)

**Comment by aasimkhan30** [comment]
Based on the discussion in the accessibility design office hours, I need to add a single label "Find Nodes" in front the first field and shift the focus to the first dropdown.

**Comment by aasimkhan30** [comment]
@Truptik12, we have fixed this issue in the product. can you please retest and close this bug?

**Comment by kisantia** [comment]
@Truptik12 can you please retest and close this bug?

**Comment by aniketr99** [comment]
Regressed the bug in the below environment:
Version: 1.46.0 (user setup)
Issue is fixed. So closing the bug.
![MicrosoftTeams-image (17)](https://github.com/microsoft/azuredatastudio/assets/100269580/af25e07b-c926-43a1-a512-8dbb26d79014)

**Comment by aniketr99** [comment]
#Closed; #Regressed:10-13-23;
