### ISSUE TITLE
ADS Not reading whole file before executing query

### ISSUE THREAD

**Issue by drethedevjs** [microsoft/azuredatastudio#21416]
Issue Type: <b>Bug</b>

1. Write a simple query.
2. Execute it.

This is an intermittent issue but happens enough for it to be frustrating. Sometimes when I'm developing or looking for data, I'll execute a query and an error will show saying `"Incorrect syntax near ..."` when the syntax isn't incorrect. For instance, I'll have...

`SELECT * FROM dbo.My_Table`

... and the error would say, `"Incorrect syntax near 'SEL'."` indicating that whatever process that's supposed to read the file (or highlighted portion) isn't rerunning...or whatever. 

No it's not the case that I only have "SEL" highlighted when executing. To resolve, I have to either move the statement to a different line, cut in paste in the same tab, or cut and paste into a new tab.

This may be fixed in newer versions but I'm sticking with this version because of Issue #7440. The version I'm on doesn't have that issue but later versions do according to the issue feed.

Azure Data Studio version: azuredatastudio 1.39.0 (9fdb2161d49b4d4ab6798809faa042a898ca2eae, 2022-08-20T01:46:47.606Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (13.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.4.0
tsqllint-plex|Ple|2.1.1
sql-prompt|Red|0.2.11
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by alanrenmsft** [comment]
@drethedevjs If you are seeing this issue, I would assume that you have the `mssql.parallelMessageProcessing` setting enabled, right?

please refer to this comment: https://github.com/microsoft/azuredatastudio/issues/7440#issuecomment-1352309945 and see whether this particular issue as well as the query hang issue is gone.

**Comment by drethedevjs** [comment]
That setting is disabled for me.

**Comment by cssuh** [comment]
Hi @drethedevjs, we've made a number of improvements to address #7440, we have provided some updates in the discussion there.  If this continues to be an issue in the latest version, please feel free to re-open this issue.
