### ISSUE TITLE
Moving code up/down when cursor is on multiline mode

### ISSUE THREAD

**Issue by MrAlex6204** [microsoft/azuredatastudio#2142]
Issue Type: <b>Bug</b>

Is not moving well the code when cursor is no multiline

SQL Operations Studio version: sqlops 0.32.2-insider (461a158ac32ac67f17158c931f0c84fc38478341, 2018-07-26T20:59:24.143Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.76GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
sqlops-combine-scripts|Bat|1.2.0
profiler|Mic|0.1.2
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
This behavior is part of the editor platform we inherit from vscode. We prefer to avoid significant changes to the base platform code as it is hard to maintain as we take continual vscode source code updates. Please log this issue in the vscode repo for their consideration. Thanks for opening the suggestion!
