### ISSUE TITLE
Run button bar has gone missing

### ISSUE THREAD

**Issue by MJsusername** [microsoft/azuredatastudio#21431]
Issue Type: <b>Bug</b>

I was just using the software like normal and went to hit "Run" to test some code and the whole bar that run was in is missing. I have tried adding/removing all bars/panels under appearance and still nothing.

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.86GB (10.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2022.7.2

</details>

**Comment by alanrenmsft** [comment]
@MJsusername Could you please share a screenshot? If the action bar is not there, you can try close and reopen it.

**Comment by MJsusername** [comment]
After restarting twice, it turns out _only this tab_ was missing the bar so I just closed it and started a new query.

**Comment by GridTrekkor** [comment]
This is still an issue in 1.48.0.  As noted above, it happens to particular tabs.  In my case I've got a script file open, and even after restarting, this particular tab _will not_ get the actions container.  Worse, it seems to stick with the tab -- closing and opening the script doesn't fix the condition, so I can't ever run this script.  Maybe there's a cache file I can delete to clear the issue.

**Comment by GridTrekkor** [comment]
@MJsusername or @alanrenmsft - could we please re-open this issue?  It's still occurring.

I was able to work around it by renaming the `workspaceStorage` dir in: `C:\Users\username\AppData\Roaming\azuredatastudio\User\workspaceStorage`

This cleared all that cache and allowed the run / action bar to appear again for the script in question.  

Thank you.

**Comment by alanrenmsft** [comment]
@kisantia could you please take a look when are you back?

**Comment by jwyza-pi** [comment]
We had someone run into this issue as well yesterday in our organization too.
