### ISSUE TITLE
Display of an error that is not an error

### ISSUE THREAD

**Issue by OSch24** [microsoft/azuredatastudio#21448]
Issue Type: <b>Bug</b>

Hello,
ADS shows an error here, although this view has been around for a while (more than an hour).

I have changed again from create to alter. But there is no refresh or check whether this view exists. Therefore, the error is still displayed. 

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Enabled

![SQLQuery-Error](https://user-images.githubusercontent.com/48675132/208419398-05d41c0f-80ad-41ed-8b39-6ecaa04855fe.png)

**Comment by Charles-Gagnon** [comment]
If you run the command `Refresh Intellisense Cache` does it still show as invalid?

**Comment by OSch24** [comment]
After executing the command - even if I have just created the view - this error is no longer displayed.
Therefore, this cache should be updated automatically as soon as an object is created or changed.

**Comment by OSch24** [comment]
Yeah, sure, no problem.
