### ISSUE TITLE
JSON field no longer open a new file

### ISSUE THREAD

**Issue by kakins** [microsoft/azuredatastudio#21451]
Issue Type: <b>Bug</b>

Latest update to ADS doesn't allow me to select JSON fields and open raw JSON in a new file.

I've tried restarting ADS and the issue remains.

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-mysql|Mic|0.2.4
azuredatastudio-postgresql|Mic|0.2.7

</details>

**Comment by cheenamalhotra** [comment]
Hi @kakins 

Can you confirm this works fine with 1.39.1 if you install it instead - just to confirm this is a regression?
Also can you please try the same with [latest insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) build?

**Comment by jcw19k** [comment]
Hi @cheenamalhotra, I'm having the same problem immediately after updating to 1.40.1. Using the latest insiders build indicates that you can click on the JSON object to open it, as in 1.39.1, but doesn't actually open anything. In 1.40.1, not even the mouseover click prompt works.

**Comment by kakins** [comment]
Thank you @jcw19k I didn't have time to try reinstalling 1.39.1.

**Comment by cheenamalhotra** [comment]
Hi @jcw19k thanks for testing. In that case, this has been most likely fixed again in the insiders build.
I'll let @alanrenmsft take a closer look (after vacations) and re-affirm that this is fixed for good.

**Comment by jcw19k** [comment]
@cheenamalhotra To be clear, the issue is still present in the insiders build. it just shows a mouseover prompt now without doing anything. Thank you!

**Comment by cheenamalhotra** [comment]
Ok, sorry I misread. Makes sense!

**Comment by alanrenmsft** [comment]
@jcw19k @kakins , could you please share the JSON string that cannot be recognized properly?

**Comment by kakins** [comment]
Sadly I can't share because the data is for my work.  I can say that I believe I've seen it occur in multiple JSON fields.  Most of the JSON objects are several properties, some complex with multiple nested objects.

**Comment by alanrenmsft** [comment]
@kakins can you remove the sensitive information from the field and run the `select 'json string'`, I can use it for my local repro.

**Comment by jcw19k** [comment]
@alanrenmsft I can't share my data either but this occurs with all JSONs for me regardless of length or complexity. Here's an example with junk data I threw together. 
![image](https://user-images.githubusercontent.com/66041877/210481797-1431a3e2-5d98-4657-91b2-3577145067fc.png)
My mouse (doesn't show up with snipping tool unfortunately) hovers over the underlined json but doesn't change from the standard cursor to a hand. Clicking doesn't open anything.

**Comment by alanrenmsft** [comment]
@jcw19k if you are using the stable version, you won't see the hand cursor, that is a recent change I made that is only available in the Insiders build. I need some logs in order to proceed, please follow the instructions below to collect the logs.

**Comment by jcw19k** [comment]
@alanrenmsft Here are the logs with all private data removed.
[logs.zip](https://github.com/microsoft/azuredatastudio/files/10347219/logs.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/10347220/console.log)
Hope this helps, thanks for taking a look!

**Comment by alanrenmsft** [comment]
@kakins @jcw19k just want to confirm, are you guys connecting to SQL Server or other type of servers, mostly likely you guys are connecting to non-MSSQL servers.

**Comment by alanrenmsft** [comment]
I can reproduce the issue when connecting to a MySQL database, I'll come up with a fix.

**Comment by alanrenmsft** [comment]
@kakins @jcw19k The fix will be available in the next insider build, please give it a try when it is available.

**Comment by alanrenmsft** [comment]
@kakins @jcw19k today's insiders build is available, just tested and it is working for me. please let me know if you are still having problems with it.

**Comment by jcw19k** [comment]
Tested with Postgres and it now works perfectly. Thank you @alanrenmsft!

**Comment by kakins** [comment]
@alanrenmsft Sorry I've been missing in action on this issue -- I've been too busy to keep up with it lately.  Thanks @jcw19k for giving the feedback and helping get the issue resolved!
