### ISSUE TITLE
"An error occurred while loading Azure resources: Requests from this account have been throttled"

### ISSUE THREAD

**Issue by yooakim** [microsoft/azuredatastudio#21453]
Issue Type: <b>Bug</b>

Unable to see all Azure resources, whenever I try to browse I get this error message

"An error occurred while loading Azure resources: Requests from this account have been throttled. To retry, please select a smaller number of subscriptions."

I have two Azure identities, one with a single subscription and one with access to 12 subscriptions.

For all other tools (Azure Storage Explorer for example) this works fine.

But with Azure Data Studio I am throttleded.

Can this be handle in a more user-friendly way?

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (17.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.11.0
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @yooakim 

We're aware of this issue in the Browse tab and will hopefully fix this soon. 
In the meantime, you may access resources in the Connections > Azure tree view, and let us know if you face any issues.

![image](https://user-images.githubusercontent.com/13396919/208752530-911989c0-2dc3-4ebd-93aa-8c0ce8eb841a.png)
