### ISSUE TITLE
Github CoPilot

### ISSUE THREAD

**Issue by aalkhatib9** [microsoft/azuredatastudio#21462]
Add Support for Extension Github CoPilot in Azure Data Studio (currently available on VS Code)

**Comment by winzig** [comment]
FYI, there is some activity happening here: https://github.com/microsoft/azuredatastudio/issues/22977

**Comment by Charles-Gagnon** [comment]
We just released this extension in the gallery for our [Insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) releases, and this will be included in the upcoming stable release later this month! Try it out and let us know what you think!
