### ISSUE TITLE
cannot install extension from vsix

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#21465]
Issue Type: <b>Bug</b>

Selecting "Extensions > Install from VSIX" results in an error message "your extension policy does not allow installing extensions. please change your extension policy and try again."

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:22:25.529Z)
OS version: Darwin arm64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
ssmskeymap|kev|1.1.0
azuredatastudio-oracle|Mic|0.1.2
dacpac|Mic|1.11.0
dsct-oracle-to-ms-sql|Mic|0.2.0
import|Mic|1.5.4
net-6-runtime|Mic|1.1.0
profiler|Mic|0.11.0
query-history|Mic|0.5.3
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
azdata-sanddance|msr|4.0.1

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/12227241/208966833-5dfce2f6-4063-45ae-b864-fa2620a7b6c7.png)

**workaround:** based on https://github.com/microsoft/azuredatastudio/blob/6998c8787f5c7bf4378bd41092e218ed74e092a4/src/vs/platform/extensions/common/extensions.ts#L18, updated settings for "Extensions: Extensions Policy" to allowAll.  Was blank in my settings

**Comment by alanrenmsft** [comment]
@dzsquared when you say it was blank, do you mean in the setting editor or in the plain settings.json? The default value is `allowAll`, you won't see it in the settings.json if it is the default value.

**Comment by dzsquared** [comment]
@alanrenmsft the settings.json included:
```
 "extensions.extensionsPolicy": "",
```

**Comment by alanrenmsft** [comment]
last time we had the similar issue was because the setting contribution is removed accidentally: https://github.com/microsoft/azuredatastudio/issues/6456, I checked the code and it is still there, I also couldn't reproduce the problem on Windows or macOS. I suspect that you might have accidentally modified the setting.
