### ISSUE TITLE
can't refresh available azure  connections because of rate limiting...

### ISSUE THREAD

**Issue by ssoldatenkov** [microsoft/azuredatastudio#21464]
Issue Type: <b>Bug</b>

can't refresh available azure connections because of rate limiting...

Azure Data Studio version: azuredatastudio 1.40.1 (3a32679ab590c1023ab4de6f191769e7e127d25b, 2022-11-22T18:30:25.850Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10920X CPU @ 3.50GHz (24 x 3504)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|127.69GB (105.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @ssoldatenkov 

Does this look similar to: https://github.com/microsoft/azuredatastudio/issues/21453 ?
Please attach logs if its a different issue.

**Comment by ssoldatenkov** [comment]
Yes, it is a similar issue as #21453 
Attached my log.
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/10280345/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
Hi @ssoldatenkov 
Can you recheck your log setting is set to Verbose? I only see error logs.
In Settings: `Azure: Logging Level`

**Comment by alanrenmsft** [comment]
@ssoldatenkov how many subscriptions do you have? this is a known issue, if you have multiple subscriptions, for now the work around is to filter subscription before expanding the list. 

In the meanwhile, we will also fix it on our end.

**Comment by alanrenmsft** [comment]
@cheenamalhotra I can share more context about the issue when I get back from vacation.

**Comment by ssoldatenkov** [comment]
Hi
I have 9 subscriptions. Each with couple sql servers.
Filtering by subscription works as a workaround, thanks.

Here is vebose log, if it helps.
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/10280659/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
I see there's 1 tenant `cd99fef8-...` you're not able to authenticate to (you can find its name from logs or Azure Portal)
Using Azure Portal, are you able to authenticate to it (using Switch Directory) and view its resources?

**Comment by cheenamalhotra** [comment]
@alanrenmsft yes I'm aware of the throttling issue when fetching azure resources, but here token is not getting acquired so I'm trying to understand why would that happen.

**Comment by ssoldatenkov** [comment]
@cheenamalhotra I'm sorry for the confusion. I don't think it is relevant to the issue. Only one tenant is used by me and contains all my subscriptions`e21de8eb...`. 
I don't see a possibility to ignore the second tenant. Keeping myself authenticated with is tedious because of security policy that requires entrering second factor code all the time.

**Comment by cheenamalhotra** [comment]
If there is no other issue, I'll close this one and we can follow up progress on #21453
