### ISSUE TITLE
Change default folder for saving a SQL execution plan to be the user's home direction, not the root folder (when not in workspace)

### ISSUE THREAD

**Issue by josh-** [microsoft/azuredatastudio#21460]
Currently saving an execution plan when not in a workspace results in a default file in the root directory. For example:

<img width="345" alt="Screenshot 2022-12-21 at 4 50 36 pm" src="https://user-images.githubusercontent.com/712727/208832587-02875d6c-aa3a-483c-9193-0c34974dc2ee.png">

Instead of saving the file at `/` I believe it should default to somewhere like the users home directory.

**Comment by kburtram** [comment]
@aasimkhan30 please help @josh- review and merge his related PR.
