### ISSUE TITLE
Provide Support of extensibility API for charting in ADS

### ISSUE THREAD

**Issue by sagangwar** [microsoft/azuredatastudio#21489]
Issue Type: <b>Feature Request</b>

This is External PG Migration team, we are using Migration assistant repo for External PostgreSQL Migration extension development and wanted to show a donut chart for Ready, not ready and ready with condition of databases scenario.

we want Donut chart support to visualize this migration readiness data and is requesting an extensibility API for the same.

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

Screenshot: 
![image](https://user-images.githubusercontent.com/96845250/210181021-8e7cda13-29f0-4485-b758-ffbc5c807b12.png)

**Comment by alanrenmsft** [comment]
@deepaksa1 any update on this? I am moving this to May milestone, if you think you can get this done early next week, please feel free to move it back to March and go through the ASK mode process.

**Comment by deepaksa1** [comment]
@alanrenmsft it's still a work in progress. Looks like it won't be completed for March milestone.

**Comment by kisantia** [comment]
@deepaksa1 I'm moving this out of the July release because the PR still isn't complete. Is there an update on when this will get done?

**Comment by kisantia** [comment]
PR is out to add support for this: https://github.com/microsoft/azuredatastudio/pull/24357

**Comment by kisantia** [comment]
Closing since PR to add support is complete
