### ISSUE TITLE
Object Explorer node gets stuck randomly

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#21500]
- Azure Data Studio Version: 1.41.0-insider (user setup)
Commit: 09307822360654fb877db830577958b3b0852df4
Date: 2022-12-28T06:30:33.769Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

I haven't verified if its reproducible consistently, but in my case I had 2 connections:
- First connected to Azure SQL (master) and I expanded 'Databases' node, which leads to resuming DBs.
- While node was expanding, I created a new connection to 'localhost' which got added, but node expansion never completed.

The first 'Databases' node failed with "Error: Could not expand node" while the second connection never completes expansion in OE:

![image](https://user-images.githubusercontent.com/13396919/210428360-64b39093-7917-4143-843b-7b92c6e619c7.png)

![OE_Stuck](https://user-images.githubusercontent.com/13396919/210490426-ecd03155-2796-4993-83f6-1832a89a04d9.gif)

Edit: It doesn't seem related to Parallel Processing or a particular type of connection.

cc @alanrenmsft

**Comment by cheenamalhotra** [comment]
I tested it again, and it's happening almost everytime I connect to localhost\<> instance. 
Disabling parallel processing seems to be working fine, but I'm keeping a close eye on it.

![OE_Stuck](https://user-images.githubusercontent.com/13396919/210490426-ecd03155-2796-4993-83f6-1832a89a04d9.gif)

**Comment by alanrenmsft** [comment]
@cheenamalhotra have you restarted ads after making the setting change?

**Comment by cheenamalhotra** [comment]
Yes, I've been able to reproduce it (randomly) multiple times after restarting ADS (in both dev and insiders)

**Comment by cheenamalhotra** [comment]
The error I captured also happens with 1.40.2, if you put a breakpoint on [this line](https://github.com/microsoft/azuredatastudio/blob/8c8a7859a02e8907af183f60a6478895123a5cdc/src/sql/workbench/services/objectExplorer/browser/objectExplorerService.ts#L261), you can see it hits randomly whenever you try to open more than one connection - but it somehow refreshes again and doesn't stay stuck in stable build.

It might be related to #21578 and only impacts insiders builds as of now.
cc @caohai

**Comment by caohai** [comment]
https://github.com/microsoft/azuredatastudio/issues/21578 happens even if I'm opening only one connection and I'm mostly seeing it with Azure servers😆.

I'm not sure if this is caused by the same change but you can try to revert the commit https://github.com/microsoft/azuredatastudio/commit/e2327c393ad2a4947038b975a52d17200be49d6c I mentioned in #21578 locally and see if it fixes this issue as well.

**Comment by cheenamalhotra** [comment]
Closing as https://github.com/microsoft/azuredatastudio/issues/21578 has been addressed.
