### ISSUE TITLE
Cannot exclude items from Schema Compare update

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#21520]
After doing a schema compare, I attempted to de-select some items so they are not processed. However, an error message is shown and the un-checked item becomes checked again, which means I cannot do the update as I do not want those items included:

![image](https://user-images.githubusercontent.com/13488/210638159-acc9daff-d2ee-410b-bab8-43f474412981.png)

There are no messages in the developer console related to that error.

**Comment by kisantia** [comment]
When is the "Specified method is not supported" message getting shown? When dependent changes are still included, a warning like this should show and the change will get reincluded. For example, if trying to exclude a table, but a view that depends on it is still included:
![image](https://user-images.githubusercontent.com/31145923/210672135-07227eb5-ca1e-4aba-be68-48191f344b12.png)

**Comment by jtsom** [comment]
It happens as soon as I uncheck an item. There is no indication there are dependent entities. And as far as I know, there aren't any. The change I'm not including is an added column in the destination that is to be removed.

**Comment by kisantia** [comment]
Do you not see a similar warning notification as the one in the screenshot above?

I haven't seen the "Specified method is not supported" error before when using schema compare. Can you please share dacpacs of the source and target that repros this so I can try to debug? My email is kisantia@microsoft.com

**Comment by jtsom** [comment]
No. The message appears as I posted in the screenshot in the initial report.

**Comment by jtsom** [comment]
@kisantia I have forwarded the source and destination dacpac files to your email. This issue is still happening.

**Comment by jtsom** [comment]
@kisantia Any info on this? It is still happening and rendering schema compare useless in ADS.

**Comment by kisantia** [comment]
Sorry I forgot to hit send on my email a couple weeks ago. I also wasn't able to see the error message when I compared the two dacpacs you shared and tried unselected items, same as what you also observed. I'll need a repro to be able to debug this issue. Any chance you've been able to come up with a couple new dacpacs that can repro this issue?

**Comment by kisantia** [comment]
closing as I was unable to repro. Please reopen if this is still happening with the latest release and a couple dacpacs to repro the issue can be provided
