### ISSUE TITLE
Error when attempting to create a new table

### ISSUE THREAD

**Issue by son-le0** [microsoft/azuredatastudio#21525]
Issue Type: <b>Bug</b>

1. Open a new connection to an Azure subscription SQL database
2. Right-click on Tables node
3. Select "New Table"

Expected Result:
New window to create new table.

Actual Result:

Table Designer Error
"An error occurred while initializing the table designer: The target database schema could not be retrieved."

StackTrace from "Copy details":
at Microsoft.Data.Tools.Sql.DesignServices.TableDesigner.TableDesigner..ctor(String connectionString, String accessToken, String schemaName, String tableName, Boolean isNewTable, Int32 largeTableRowCount)
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.CreateTableDesigner(TableInfo tableInfo) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 1800
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass18_0.<<HandleInitializeTableDesignerRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 99
--- End of stack trace from previous location ---
   at Microsoft.SqlTools.ServiceLayer.TableDesigner.TableDesignerService.<>c__DisplayClass17_0`1.<<HandleRequest>b__0>d.MoveNext() in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\TableDesigner\TableDesignerService.cs:line 85

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:05:27.289Z)
OS version: Darwin arm64 22.2.0
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (1.31GB free)|
|Process Argv|--disable-extensions|
|Screen Reader|no|
|VM|0%|
</details>Extensions disabled

**Comment by alanrenmsft** [comment]
@son-le0 what type of azure SQL DB you were using? do you have full permission on the database?

**Comment by son-le0** [comment]
@alanrenmsft The database is a Azure SQL Database and `select USER_NAME()` returns `dbo`.

**Comment by alanrenmsft** [comment]
@caohai could you please take a look?

**Comment by alanrenmsft** [comment]
@son-le0 does it help if you restart Azure Data Studio?

**Comment by son-le0** [comment]
> @son-le0 does it help if you restart Azure Data Studio?

Nope.

Also noticed the same error (intermittently) when I try the "Design" context menu item on an existing table.

**Comment by alanrenmsft** [comment]
@son-le0 are you using the Intel version of Azure Data Studio or Universal/Apple Silicon version?

**Comment by son-le0** [comment]
Apple Silicon / arm64

**Comment by alanrenmsft** [comment]
@caohai ping...

**Comment by caohai** [comment]
> @caohai ping...

I currently don't have an Apple Silicon machine at hand... I tried latest insider on my Intel Mac this morning and didn't see this issue. I'm not sure if this issue is related to the db or the Apple Silicon build.
@alanrenmsft Can you verify that table designer works on Azure SQL DB with the Apple Silicon / arm64 build?

**Comment by alanrenmsft** [comment]
yes, I did, it works for me on my M1 Mac, in this case, can we add more logging to help us understand the problem?

**Comment by cheenamalhotra** [comment]
Related: #22486
