### ISSUE TITLE
Azure AAD is not working for MySQL extension in Insiders latest release.

### ISSUE THREAD

**Issue by nitishsharma25** [microsoft/azuredatastudio#21536]
- Azure Data Studio Version: Insiders 1.41.0-insider (January 5 release)
- OS Version: Windows

Steps to Reproduce:

1.  Select Azure Active Directory Authentication type.
2.  Select Account and connect

Error:

![image](https://user-images.githubusercontent.com/112425736/210954727-84379738-633e-4c02-a7ac-e59b84a707e4.png)

Our package.json file with azureAuth option specified:

![image](https://user-images.githubusercontent.com/112425736/210954947-7a4d5516-04de-4ce4-b525-cd8ef7047e76.png)
 
Our extension repo: https://github.com/microsoft/azuredatastudio-mysql

Note:

1. Azure AAD is working in stable release 1.40.2
 

Does this issue occur when all extensions are disabled?: Yes only MySQL extension is enabled

**Comment by nitishsharma25** [comment]
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/10359192/1-Azure.Accounts.log)

Attached the Azure Accounts.log file

**Comment by cheenamalhotra** [comment]
@nitishsharma25 

Could you please test the same with changes from PR #21540 ?
Thanks!

**Comment by nitishsharma25** [comment]
Thanks @cheenamalhotra, I am able to connect using AAD now.
