### ISSUE TITLE
Object Explorer fails when expanding Views

### ISSUE THREAD

**Issue by MrTobin** [microsoft/azuredatastudio#21541]
Issue Type: <b>Bug</b>

1) Connect to DB
2) Expand Tables, no problem
3) Expand Programmability, no problem
4) Expand Views... "Object Explorer task didn't complete within 45 seconds"

SSMS has no issues listing views.

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD FX(tm)-8320 Eight-Core Processor            (8 x 3793)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: unavailable_off<br>opengl: enabled_on<br>rasterization: unavailable_off<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.90GB (11.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.1

</details>

**Comment by kburtram** [comment]
@cheenamalhotra do you expect the OE timeout fix you were recently looking at will address this issue?

**Comment by cheenamalhotra** [comment]
The fix we've made is specifically for listing databases SMO query, so I don't think it will impact views.

We will investigate this next thing!

**Comment by MrTobin** [comment]
Connecting to an azure SQL database using SQL user authentication. The issue did not start impacting me until just recently. Perhaps in the past 30 to 90 days tops. Did not experience this problem with prior versions.

**Comment by cheenamalhotra** [comment]
Issue #21171 looks exactly similar to this one, so we can keep any one open.
I'll close this (recent) as duplicate, and PR https://github.com/microsoft/sqltoolsservice/pull/1801 should address both issues from STS.
