### ISSUE TITLE
Auto-select and execute SQL statement

### ISSUE THREAD

**Issue by bcoulam-fmg** [microsoft/azuredatastudio#21549]
Issue Type: <b>Feature Request</b>

I've been using and professionally evaluating database IDE's since 1998. My new employer uses Azure almost exclusively. ADS is the worst DB client experience I've ever hard. It is so incomplete. So few tools support AAD auth for DB connections, that I'm stuck with this. So it's time to submit enhancement requests in hopes your awesome team can make them reality in short order.

First thing I noticed is that I have to manually select each SQL statement I want to run. This is time consuming. Every other DB client I have used will auto-select the SQL statement AND allow you to execute it with a keyboard shortcut like Ctrl+Enter. Typically this feature depends on the developer using a semi-colon to end each SQL statement, in case it helps you to know that.

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Enabled

**Comment by alanrenmsft** [comment]
@bcoulam-fmg Azure Data Studio does have support for running all the queries or only the current query. You can either run the command from command palette (Main menu, View->Command Palette) or use the shortcut keys directly.

Run Query -> F5
Run Current Query -> Ctrl+F5

![image](https://user-images.githubusercontent.com/13777222/211112370-4de416be-f477-419e-8aa0-cae6bbd516fa.png)

hope this helps.

**Comment by bcoulam-fmg** [comment]
Well, that's embarrassing. OK, chalk this up to unfamiliarity with more recent Microsoft tools. I now see that most of the keyboard shortcuts I was looking for are buried in the Command Palette. No wonder this tool seemed so incomplete. Most of the possible commands are hidden. Interesting UX choice.

Every developer at my company who uses ADS does not know about this shortcut either. In every Teams meeting I see them laboriously selecting the statement and then clicking the Run button. I'll spread the word.
