### ISSUE TITLE
Fix install for MongoDB extension

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#21554]
- Azure Data Studio Version: 1.40.2 Insider
- OS Version:  Windows 11

Steps to Reproduce:

1. Within extension gallery select MongoDB for ADS extension
2. Install takes you to the GitHub page, it doesn't launch the visx

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
The Mongo extension install appears to working as expected following the merge of the referenced PR.
