### ISSUE TITLE
Focus Tab is not Obvious

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#2156]
Issue Type: <b>Feature Request</b>

Hi,

When you have a light color theme the Focus Tab is not obvious

Regards Dat.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alanrenmsft** [comment]
@datauduong I am going through the old issues and noticed this one, this is actually customizable, you can follow the instructions here: https://code.visualstudio.com/api/references/theme-color

e.g.:
![image](https://user-images.githubusercontent.com/13777222/204966816-24ee5e62-8485-4ac1-99d2-f5d3324d5f99.png)
