### ISSUE TITLE
Azure Data Studio get unresponsive when managing multiple connections 

### ISSUE THREAD

**Issue by steve-torchia** [microsoft/azuredatastudio#21568]
Issue Type: <b>Bug</b>

When I have to swtich between multiple connections, ADS often becomes undresponsive.  Most of the time I need to restart the App.   SSMS does not have this behavior.

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (13.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353

</details>

**Comment by cheenamalhotra** [comment]
Hi @steve-torchia 

Could you provide more details with screenshots if any, to help us understand better where ADS connections go unresponsive.
Also would recommend trying out the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if the issue continues to persist?

**Comment by cheenamalhotra** [comment]
Closing as not enough details available to investigate issue
