### ISSUE TITLE
Copy Headers doesn't escape commas properly

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21570]
Insiders/Dev

1. Run query with results that has a column containing a comma in its name, e.g.

`SELECT 1 AS foo, 2 AS [foo,bar], 3 AS bar`
2. Right click on grid and select `Copy Headers`

Expected: The copied text is copied as proper CSV, which means fields with commas are surrounded by double quotes

https://www.ietf.org/rfc/rfc4180.txt

`Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.`

Actual: The copied text does not escape commas so you end up with something like this 

`foo,foo,bar,bar`

**Comment by Charles-Gagnon** [comment]
Although I question whether this should even be copying them as CSV anyways. Copy and Copy with Headers use a tab-separated format so it's kind of odd to have this one be the only one that uses CSV. 

(it does feel to me though like the format should be a setting - since there's use cases for both)

**Comment by alanrenmsft** [comment]
@aasimkhan30 , I just realized that your PR https://github.com/microsoft/azuredatastudio/pull/22028/files#diff-6e35c00abf7006fa9a71f88d296983b3e4489c2f57e25e394a3dbc84967b1e10 actually reverted the fix for this issue, could you please review it and bring back the unexpected reverts?

**Comment by alanrenmsft** [comment]
@aasimkhan30 could you please take a look at this one?
