### ISSUE TITLE
"Connection providers incorrectly registered" error on Azure node expansion

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#21587]
Stable 1.40.2 & Insiders

1. Open dev console
2. Expand Azure server node in OE
3. Get multiple `Connection providers incorrectly registered. Defaulting to SQL Azure resource,` warnings in the console

Introduced in https://github.com/microsoft/azuredatastudio/pull/19387

**Comment by kburtram** [comment]
From looking at the commit it looks like https://github.com/microsoft/azuredatastudio/pull/19387 is adding a warning for failing an existing precondition check.  The investigation should probably be why are we getting `connection` objects with unregistered providers from the Azure view.
