### ISSUE TITLE
The Find feature is returning text that have been deleted from the text cell

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#21637]
I have a text cell in my notebook, trying to remove the text `Preview` from it, 
![image](https://user-images.githubusercontent.com/13777222/213318445-a86cad28-eeea-4e76-bfc3-1dfa34fe59b6.png)

after removing the `Preview` text, I am still able to find it using the Find feature.

![image](https://user-images.githubusercontent.com/13777222/213318252-1809d4f7-8b2c-4746-bd46-83aacf6f3333.png)

This is not a regression, I tried on 1.40.2, the issue also exists there.

**Comment by kenvanhyning** [comment]
This doesn't meet the askmode bar.  Should definitely be fixed but can move it to the may release.
