### ISSUE TITLE
Selecting server/database from Azure tree does not pick up correct account

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#21643]
- Azure Data Studio Version: RC1
- OS Version: Windows 11

Steps to Reproduce:

1. In Azure tree, connect to multiple accounts using ADAL
2. Migrate accounts to MSAL (update auth library and reload)
3. Reauthenticate to accounts as prompted.
4. Connect to any resource from second+ account in list.
5. The account loaded in dropdown is the first one in the list and not the one associated with the resource.

This is a new issue, and root cause is likely related to MSAL <> ADAL account id comparison when loading associated account in dropdown, as account id is different for ADAL live# accounts, and is not matched with MSAL live# accounts, but needs further investigation.

The issue does not apply to newly added MSAL accounts, and only applies to migrated accounts.

**Comment by cheenamalhotra** [comment]
Just discussed with @cssuh, it seems this issue is not consistently reproducible, and doesn't happen with ADAL accounts all the time. The steps above are not reproing the issue again in RC build, so it does lead us to think about lowering the urgency of this issue until we find a consistent repro to be able to confirm the fix we make is accurate.

@kenvanhyning @kburtram if you agree, we'd like to move it to March, and will keep close eye on possibilities that would lead to this issue when it happens again.

**Comment by cssuh** [comment]
To add more context, I thought this was referring to the account dropdown in the firewall rule dialog screen, so that is what I was working on (the firewall rule account selected by default did not match).  I can still make the PR but for that issue it doesn't need to go into the Jan release.
