### ISSUE TITLE
Notebook Grid Actions Appear Below (previously were above) Grids

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#21645]
1.40.2:

<img width="203" alt="image" src="https://user-images.githubusercontent.com/40371649/213329983-c7c62b53-8fe0-4a95-80e8-6d8f67108595.png">

1.41.0-rc1:
<img width="193" alt="image" src="https://user-images.githubusercontent.com/40371649/213330045-9085fc69-7a66-4e2d-8d83-616f2cd63797.png">

Even more bizarre, if you click the Chart action, then the actionbar moves above the chart:
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/40371649/213562558-030b821e-95a1-412f-a95f-ae12666bc961.png)

**Comment by alanrenmsft** [comment]
@lewis-sanchez Do you think this might be a side effect of your change?

**Comment by lewis-sanchez** [comment]
@alanrenmsft, yes, my change did cause that.

Here's what it looks like when I revert my action bar commit:
![image](https://user-images.githubusercontent.com/87730006/213569560-38ddbd26-c0ca-4912-a82c-5951c5b534f3.png)

**Comment by alanrenmsft** [comment]
@lewis-sanchez ok, if it is trivial to fix the issue then go ahead, otherwise you can revert your changes in the release branch.

**Comment by kburtram** [comment]
Fix ported to release/1.41.
