### ISSUE TITLE
Failed to retrieve data for this request (access token expired?)

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/azuredatastudio#21650]
Issue Type: <b>Bug</b>

So this happens to me every day. I'm connected to Azure SQL Databases using Azure AD with MFA support authentication. I connect to a database and open a folder with objects (Tables, Views, etc. folder). After I haven't used Data Studio for a while, when I try to refresh a folder, I get a message "Failed to retrieve data for this request.". No matter how many time I click the Refresh option, it's not working. Also, when trying right-clicking, for example, a view to open the CREATE script, I get an error message.

I opened the debug Console and see for query Windows the access token can expire and a new connection is created upon running the query. Could it be that the access token for the tree view connection also expires and is not automatically refreshed when try to do a refresh or any other action from the tree view?

The only way to continue working, is to Disconnect the connection to the database and reopen it in the tree view. It's the most annoying thing for me in Data Studio at the moment.

![image](https://user-images.githubusercontent.com/10850600/213470849-51f85efc-0c92-45df-ae86-c30612d42546.png)

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (18.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azcli|Mic|1.7.0
cms|Mic|0.9.2
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
sql-prompt|Red|0.2.12

</details>

**Comment by kburtram** [comment]
@cssuh any idea what could be happening here?  Should the tokens be getting auto-refreshed in this scenario?

**Comment by cssuh** [comment]
They should be getting auto-refreshed, we fixed this behavior in https://github.com/microsoft/azuredatastudio/pull/21206 so not sure why it's still happening here @cheenamalhotra any ideas? I'll try to get a repro on my windows machine as well

**Comment by nielsvdc** [comment]
@cheenamalhotra I'm trying the insider build 1.42.0 build 2023-01-20T06:30 and I'm running into a problem with loading the Object Explorer from the start. See attached video

https://user-images.githubusercontent.com/10850600/214023431-8e3da415-1240-41b7-b2af-55e62a06ea23.mp4

**Comment by cheenamalhotra** [comment]
Hi @nielsvdc 

Yes, our team is aware of the same, and we're tracking this issue with https://github.com/microsoft/azuredatastudio/issues/21578, it hasn't been fixed in the insiders build at the moment. 

As a workaround if you open another connection, that should stop the spinner and get the first connection tree loaded.

**Comment by cheenamalhotra** [comment]
@nielsvdc 

Let us know if you still experience the issue with latest stable release v1.41.1 or else we can close the same.
Thanks!

**Comment by nielsvdc** [comment]
@cheenamalhotra Works fine in v1.41.1

**Comment by cheenamalhotra** [comment]
Great! Closing issue as resolved.
