### ISSUE TITLE
Toggle Developer Tools keyboard shortcut not working out-of-the-box

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/azuredatastudio#21651]
Issue Type: <b>Bug</b>

Is it just me or is the Toggle Developer Tools keyboard shortcut Ctrl+Shift+I not working out-of-the-box?

Azure Data Studio version: azuredatastudio 1.40.2 (661384637db384fe5d4e6224069adbe708580b16, 2022-12-22T22:17:02.658Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (18.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azcli|Mic|1.7.0
cms|Mic|0.9.2
dacpac|Mic|1.11.0
import|Mic|1.5.4
profiler|Mic|0.11.0
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
sql-prompt|Red|0.2.12

</details>

**Comment by Charles-Gagnon** [comment]
Toggle Developer Tools doesn't have a keyboard shortcut by default outside of dev mode (built from source). You can either go to Help -> Toggle Developer Tools or change the "when" expression of the keybinding to remove the `isDevelopment` expression.

![image](https://user-images.githubusercontent.com/28519865/213511987-5326bf71-e197-442d-9780-a34665f71216.png)

**Comment by nielsvdc** [comment]
@Charles-Gagnon What I meant is, that in the help menu the Toogle Developer Tools option has the Ctrl+Shift+I keyboard shortcut behind it, but the shortcut is not mapped (see screenshot). Either map the keyboard short out-of-the-box or remove it from the menu option.

This is also the case in the upcoming 1.42 insider version.

![image](https://user-images.githubusercontent.com/10850600/213545194-00e32830-bdf6-4294-9004-41f7f7c03438.png)

**Comment by Charles-Gagnon** [comment]
Gotcha, yeah that's not the best behavior. But this is something we inherit upstream from VS Code so I'd suggest opening an issue there and seeing if they want to fix it. We usually avoid making changes to core stuff from them unless it's causing actual issues.
