### ISSUE TITLE
[SQL Migration] Remove exported database encrypted certificates when migrating certificates from source to target.

### ISSUE THREAD

**Issue by junierch** [microsoft/azuredatastudio#21679]
- Azure Data Studio Version:  1.40.2
- OS Version: 11 21H2

Steps to Reproduce:

1. Run Certificates Migration using the SQL Migration extension.
2. Observe that when the process successfully migrates the database encryption certificate or it fails, the exported certificate and the newly generated certificate are being left behind.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
@junierch Please close this issue once you've verified it's fixed in the latest RC1 build

**Comment by alanrenmsft** [comment]
@junierch have you tested the latest RC1 build?

**Comment by junierch** [comment]
It was already verified. Thanks.
