### ISSUE TITLE
Create SQL DDL of a table and indexes does not show the included columns

### ISSUE THREAD

**Issue by hermandr** [microsoft/azuredatastudio#21671]
- Azure Data Studio Version: 1.40.2 (system setup)
Commit: 661384637db384fe5d4e6224069adbe708580b16
Date: 2022-12-22T22:17:02.658Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.22623

Steps to Reproduce:

1. Manage Database
2. At list of tables, right-click on the hamburger at the rightmost of the table entry
3. Select Create SQL
4. Generates the CREATE Table and CREATE indexes in a new editor tab

For indexes that is created with
CREATE INDEX IX_ABC on dbo.TABLE1 (col1, col2, col3);
The create index script is correct

For indexes that is created with
CREATE INDEX IX_ABC on dbo.TABLE1 (col1, col2, col3) include (col4, col5,col6);
The create index script omits the include part.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by BrentOzar** [comment]
I can't reproduce this. I ran:

```
USE tempdb;
GO
CREATE TABLE dbo.Test (Id INT IDENTITY(1,1) PRIMARY KEY CLUSTERED,
    Test1 NVARCHAR(50),
    Test2 NVARCHAR(50));

CREATE INDEX Test1 ON dbo.Test(Test1)
    INCLUDE (Test2);
GO
```

I then clicked on TempDB, dbo.Test, right-clicked and clicked Create SQL. It generated the scripts with the includes:

```
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Test](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Test1] [nvarchar](50) NULL,
	[Test2] [nvarchar](50) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Test] ADD PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
CREATE NONCLUSTERED INDEX [Test1] ON [dbo].[Test]
(
	[Test1] ASC
)
INCLUDE([Test2]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
```


My Azure Data Studio info (you can see this in your menus under Azure Data Studio, About.)

```
Version: 1.40.2
Commit: 661384637db384fe5d4e6224069adbe708580b16
Date: 2022-12-22T22:05:12.502Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin x64 22.2.0
```

**Comment by Rheeser** [comment]
No

**Comment by hermandr** [comment]
I have tried it today and it is generating the include columns.
![image](https://user-images.githubusercontent.com/10177608/215257733-62a70996-e7d5-4b3f-abbf-35a6c9538027.png)

I will close this issue.
