### ISSUE TITLE
Feature Request: Improve the way how NULL value is displayed in Results grid

### ISSUE THREAD

**Issue by MarekMasko** [microsoft/azuredatastudio#217]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

Execute such query:
SELECT NULL AS [Null Value], 'NULL' AS [String]

In results grid there is no difference between NULL value and string. 

![image](https://user-images.githubusercontent.com/23073724/33239297-2a6f3bac-d29f-11e7-9693-1142ce9567ee.png)

Would be great to display NULL values in a different way. Something similar to the way how SSMS does it.

**Comment by LukeTheGit** [comment]
Is it possible to have this as a customisable setting? I'd like to be able to change the background colour to yellow for NULLs just like in SSMS.

**Comment by kburtram** [comment]
In `1.8.0` NULL values are display in italics.  Here is how the original snippet displays.

![image](https://user-images.githubusercontent.com/599935/59061838-430e7a80-8859-11e9-847f-4ce09798120a.png)
