### ISSUE TITLE
Opening json result increases zoom

### ISSUE THREAD

**Issue by gasortor** [microsoft/azuredatastudio#21715]
Issue Type: <b>Bug</b>

Using 2560x1440 display at 100% scale, when I open a json result it zooms in or out to one level above default zoom regardless of what my current zoom is at. 

Azure Data Studio version: azuredatastudio-saw 1.38.0-saw (34c7af19fef4bb0b167ac93554aa152d9b3cbcc6, 2022-07-29T23:59:14.588Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10810U CPU @ 1.10GHz (12 x 1608)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.34GB (18.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
the issue has been fixed, looks like we need a new SAW version release of ADS. 
@JustinMDotNet I believe your team has been doing the SAW ADS release. could you please create a new version?

**Comment by alanrenmsft** [comment]
synced up offline, the team is not planning to do a new release at this point.
