### ISSUE TITLE
Not able to connect to other Azure Clouds

### ISSUE THREAD

**Issue by ludwhe** [microsoft/azuredatastudio#21736]
**Is your feature request related to a problem? Please describe.**
It would be useful to be able to connect Azure accounts which are not on the part of `AzureCloud` (e.g. accounts on `AzureChinaCloud`) to be able to connect to databases/services hosted on these cloud instances.

**Describe the solution or feature you'd like**
When connecting a new account, to be able to select the cloud instance on which to connect (and when adding a server connection, to be able to list and connect to servers hosted on different instances).

**Describe alternatives you've considered**
No web-based apps to connect to the services which I want to reach and are hosted on different instances seem available.

**Comment by alanrenmsft** [comment]
I think this is already supported. @cheenamalhotra could you please share the instructions?

**Comment by ludwhe** [comment]
Thank you for the quick feedback!

**Comment by ludwhe** [comment]
Had some issues connecting to services after enabling this, updated Azure Data Studio but now it seems attempting to log into an account hosted on Azure China redirects to the Azure Global host (login.microsoftonline.com) ; it seems issues have already been opened for this in the past though (#14121). By "We only support this configuration to be made globally", do you mean only one cloud instance should be selected at a time?

**Comment by cheenamalhotra** [comment]
Hi @ludwhe 

> By "We only support this configuration to be made globally", do you mean only one cloud instance should be selected at a time?

We support multiple clouds being enabled.

It seems there's an issue identified with MSAL, being fixed with #21805. As a mitigation, please change authentication library to ADAL in Settings to be unblocked:

<img src="https://user-images.githubusercontent.com/13396919/216135174-8897fd08-6ba4-4906-b55f-f71b56d4b8cc.png" width=500 />

**Comment by cheenamalhotra** [comment]
Keeping this issue open for now until fixed in stable, so anyone hitting this can find helpful info.

**Comment by kburtram** [comment]
This will be fixed in the upcoming Hotfix release (planned for tomorrow)
