### ISSUE TITLE
Can't login with AAD MFA "Error: Failed to get token" without restart of ADS

### ISSUE THREAD

**Issue by AnthonyDewhirst** [microsoft/azuredatastudio#21750]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Select accounts and add an azure account with MFA enabled, this works fine and no prompt was given
2. Select a database, in the azure panel I can see that its logged into azure and can see the server and database but when expanding the database the error pops up
3.
![image](https://user-images.githubusercontent.com/642569/215049399-9cdd0c11-4a1c-488f-8c7f-95ba44574407.png)
The logs from the console in developer tools state:
 WARN Connection providers incorrectly registered. Defaulting to SQL Azure resource,
log.ts:313   ERR Error: Failed to get token
	at t.AzureAccountProvider._getAccountSecurityToken (c:\Program Files\Azure Data Studio\resources\app\extensions\azurecore\dist\extension.js:2:525749)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
4. Relaunching ADS fixed the issue, but this wasn't obvious nor should I have to do this

Does this issue occur when all extensions are disabled?: Yes/No
Tricky to answer, I tried this, and it started to work. So then I tried again with extensions enabled and now it all works. See step 4 from above.

**Comment by cheenamalhotra** [comment]
Hi @AnthonyDewhirst 

> Tricky to answer, I tried this, and it started to work. So then I tried again with extensions enabled and now it all works. See step 4 from above.

Let us know if you hit the issue again, please also provide ADS version when you do, so we can provide support accordingly.
Thanks!

**Comment by cheenamalhotra** [comment]
Closing as inactive, likely fixed with #22140
