### ISSUE TITLE
Defender blocking the product update

### ISSUE THREAD

**Issue by aistvan** [microsoft/azuredatastudio#21751]
- Azure Data Studio Version: 1.40.2
- OS Version: Windows 11 22621.1105

Steps to Reproduce:

1. Check update
2. Process the update

Does this issue occur when all extensions are disabled?: Yes

I tried to update the product, but the windows defender blocked something to run from Temp directory.

<img width="383" alt="Defender blocking the update" src="https://user-images.githubusercontent.com/4349061/215061979-edc069ca-7444-4ea0-b4fd-92da1663f44f.png">

Anybody has any clue why?

**Comment by kburtram** [comment]
Unfortunately this isn't something that we have control over.  The ADS installer is signed by Microsoft and is used relatively broadly, so should be trusted by Windows Defender.  Perhaps waiting a bit and trying again, or using the ZIP file installer instead could help.
