### ISSUE TITLE
Get Connection String should copy to clipboard

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/azuredatastudio#2175]
Get Connection string command should automatically copy the value to the clipboard, rather than have to click on the info box.

**Comment by kburtram** [comment]
@anthonydresser well, you should have made this suggestion during code review 😄

**Comment by anthonydresser** [comment]
Didn't think about it until I tried using it today to test the connection string input

**Comment by kburtram** [comment]
Closing as fixed based on https://github.com/Microsoft/azuredatastudio/pull/2331.
