### ISSUE TITLE
Connection type problem

### ISSUE THREAD

**Issue by KevinTodorov** [microsoft/azuredatastudio#21767]
- Azure Data Studio Version: 1.41.0
- OS Version: 13.2

 When I try to make a new connection it says "Cannot read properties of undefined (reading 'connection')" and there is nothing
I am trying to make a SQL Server connection. How do I make it possible to occur in the connection type?

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
Hi @KevinTodorov 

Can you please capture `verbose` logs of the event and upload them here? 
Also paste detailed version info from Help > About from menu bar.

**Comment by KevinTodorov** [comment]
Hello I hope I made things right 
[Archive.zip](https://github.com/microsoft/azuredatastudio/files/10527726/Archive.zip)

**Comment by cheenamalhotra** [comment]
Hi @KevinTodorov 

It seems the MSSQL Tools Service is not running when you captured logs - as there's no log file with that name. You may want to give some time to start backend services when ADS starts.

Did you see the below message "Starting SQL Tools Services" in ADS status bar followed by "SQL Tools Service started" when you give around 60 seconds to start services, or does any error occur during starting services?

![image](https://user-images.githubusercontent.com/13396919/215557571-ea8f0d8b-1563-49d9-a344-688a4d98cf7e.png)

**Comment by KevinTodorov** [comment]
Hello first of all thank you for your help and your time on my problem @cheenamalhotra  I've found fix on my problem 
and for me it was to first delete azure data studio then go to folder ~/library then go to application support folder and delete everything that contains  ADS and go to caches folder do the same thing and last of all go to preferences and delete everything that contains ADS then I installed ADS again and everything worked for me. (I'm typing this for the people that have this problem and for anyone that didn't understand I'm on Mac)
