### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by vikarBCC** [microsoft/azuredatastudio#21783]
Issue Type: <b>Bug</b>

I am getting below error after upgrading to Azure Data Studio version 1.41. I tried both MSAL and ADAL connection method but issue still persist. I tried deleting settings but no luck. This was working in previous version of Data Studio. 

Failed to get Azure account token for connection

Azure Data Studio version: azuredatastudio 1.41.0 (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:25:45.514Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
eltsnap-simple-data-flow|bit|1.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
azcli|Mic|1.7.0
azuredatastudio-oracle|Mic|0.1.2
cms|Mic|0.9.2
dacpac|Mic|1.11.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.4
managed-instance-dashboard|Mic|0.4.2
net-6-runtime|Mic|1.1.0
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
query-history|Mic|0.5.3
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
sql-dw|Mic|0.0.1
sql-migration|Mic|1.2.0
extra-sql-script-as|pac|0.5.0
schema-visualization|R0t|0.8.2
simple-data-scripter|sea|0.1.6

</details>

**Comment by vikarBCC** [comment]
[1-Azure Accounts-attach.log](https://github.com/microsoft/azuredatastudio/files/10541217/1-Azure.Accounts-attach.log)

**Comment by cheenamalhotra** [comment]
Hi @vikarBCC 

It seems you're using ADAL when logs were captured, however there is no concerning error in logs I see. Can you try to run `Command Palette (Ctrl + Shift + P) > 'Azure Accounts > Clear Azure Account Token Cache'` command, followed by reloading ADS to clear any cache related issues? You may need to refresh your credentials, so please do the same.

Eventually, you should try moving to MSAL, following same steps to clear cache and reauthenticate as requested. 
You will get much extensive logging with MSAL so please gather logs the same way and let us know if you see any exception.

**Comment by vikarBCC** [comment]
> Hi @vikarBCC
> 
> It seems you're using ADAL when logs were captured, however there is no concerning error in logs I see. Can you try to run `Command Palette (Ctrl + Shift + P) > 'Azure Accounts > Clear Azure Account Token Cache'` command, followed by reloading ADS to clear any cache related issues? You may need to refresh your credentials, so please do the same.
> 
> Eventually, you should try moving to MSAL, following same steps to clear cache and reauthenticate as requested (Reauthentication is needed when switching library).
> 
> You will get much extensive logging with MSAL so please gather logs the same way and let us know if you see any exception.

[Verbose]: MsalCachePluginProvider: Using cache path C:\Users\****\AppData\Roaming\azuredatastudio\Azure Accounts and serviceName azureTokenCacheMsal-azure_publicCloud - []
[Information]: Fetching saved token - []
[Error]: No access token found - []
[Information]: Fetching saved token - []
[Error]: No access token found - []
[Error]: User had no base tokens for the basic resource registered. This should not happen and indicates something went wrong with the authentication cycle - []
[Error]: Error refreshing access for account Vikar Ghory - Vikar.xxxx@abc.com - ["{\n  \"originalMessage\": \"No base token found\"\n}"]
[Verbose]: Starting login - []
[Verbose]: Fetching token for tenant {0} - ["common"]
[Verbose]: Fetching tenants with URI: {0} - ["https://management.azure.com/tenants?api-version=2019-11-01"]
[Verbose]: Tenants: XXX - []
[Verbose]: Token Claims acccount: xxxx xxxx, TID: a47f8d5a-a5f2-4813-xxxx-xxxxxxxx - []
[Verbose]: Tenant ID: a47f8d5a-a5f2-4813-xxxx-xxxxxxxxx, Tenant Name: xxxx - []

**Comment by vikarBCC** [comment]
MSAL log attached. I am using MFA but the prompt doesn't open dialog to enter Authenticator generated OTP
[1-Azure Accounts-clean.log](https://github.com/microsoft/azuredatastudio/files/10541828/1-Azure.Accounts-clean.log)

**Comment by cheenamalhotra** [comment]
I think you accidentally clicked on 'Ignore Tenant' on one of the popups, as I see this in logs:
`Tenant a47f8d5a-a5f2-4813-a71a-f0d70679e236 found in the ignore list`

Please remove this from ignore list by clearing this setting from `settings.json`:
```
    "azure.tenant.config.filter": [
        "a47f8d5a-a5f2-4813-a71a-f0d70679e236"
    ],
```

**Comment by vikarBCC** [comment]
I tried removing tenant filter, still getting same error.

**Comment by cheenamalhotra** [comment]
Hi @vikarBCC 

I hope you've restarted ADS after removing the setting, but if you're still experiencing issue, please upload Azure account log to identify reason for failure.

**Comment by vikarBCC** [comment]
Hi @cheenamalhotra, Yes, I restarted and I believe I already uploaded account log. 

I managed to make it work by manually adding below in settings.json

"datasource.connections": [
        {
            "options": {
                "connectionName": "abc",
                "server": "abc.database.windows.net",
                "database": "db1",
                "authenticationType": "AzureMFA",
                "user": "abc@xyz.com",
                "password": "",
                "connectTimeout": 30,
                "encrypt": "true",
                "trustServerCertificate": "false",
                "applicationName": "azdata",
                "azureTenantId": "a47f8d5a-a5f2-4813-xxxx-xxxxxxxxxx",
                "azureAccount": "xxxxxxx-xxxx-xxxxx-xxxxxxxxxxxxxx",
                "expiresOn": 1675218088,
                "originalDatabase": "db1",
                "groupId": "a7f0712e-1aad-4bc0-92ca-bec923c3972c",
                "databaseDisplayName": "db1"
            },
            "groupId": "a7f0712e-1aad-4bc0-92ca-bec923c3972c",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "efd8546b-45fd-4e2c-86e5-e08e66d90ba9"
        }
]

I have 2 accounts admin and non admin. ADS was working fine when I start it under admin account but didn't work under non admin account. I got above settings from my admin account and copied and pasted in settings.json of my non admin account after replacing admin account details with non admin account.
