### ISSUE TITLE
Provide a warning dialog before reverting file

### ISSUE THREAD

**Issue by jwatkin** [microsoft/azuredatastudio#21786]
Issue Type: <b>Feature Request</b>

Please provide a warning dialog when the "Revert File" menu option is selected so people who accidentally select the "Revert File" menu option can cancel the reverting of the file.

In the context menu that appears after right-clicking on a **SQL Notebook** file in the "EXPLORER > OPEN EDITORS" section, the "Save" and "Revert File" menu options are next to each other. My finger slipped and I accidentally selected "Revert File" instead of "Save" and so I lost my work. I tried uisng the "Undo" and "Redo" options but they didn't work in this case.

This happens in both Text and Code SQL Notebook cells.

Thank you.

Azure Data Studio version: azuredatastudio 1.41.0 (cf5e0fe1a33709e2a82dc94f42dbe88487803d62, 2023-01-24T17:29:04.297Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No
Preview Features: Enabled

**Comment by kburtram** [comment]
The core editor features such as this are cloned directly from VS Code upstream.  We rarely modify these behaviors unless there is something specific to data-focused scenarios vs. code-focused scenarios.  Please open this as an enhancement request against VS Code and if they take this update then we will pick up in a future code refresh.  Thanks for opening the issue.
