### ISSUE TITLE
Service Broker details missing

### ISSUE THREAD

**Issue by GHRandomUserName** [microsoft/azuredatastudio#21796]
Issue Type: <b>Bug</b>

Service broker details are missing from the server connections.

Azure Data Studio version: azuredatastudio 1.41.1 (33dce95b152227c4f10f6251ab30690fe9895c0c, 2023-01-28T00:46:39.274Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500T CPU @ 2.30GHz (12 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.72GB (4.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
markdown-mermaid|bie|1.14.2
eltsnap-simple-data-flow|bit|1.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.4
agent|Mic|0.49.0
dacpac|Mic|1.11.0
import|Mic|1.5.4
powershell|ms-|2022.7.2
profiler|Mic|0.11.0
schema-compare|Mic|1.17.0
sql-database-projects|Mic|0.20.0
jupyter|ms-|2022.4.1021342353

</details>

**Comment by cheenamalhotra** [comment]
Seems related to https://github.com/microsoft/azuredatastudio/issues/2831

**Comment by aasimkhan30** [comment]
Closing as dup of #2831
