### ISSUE TITLE
Pestañas

### ISSUE THREAD

**Issue by benitolnx** [microsoft/azuredatastudio#21791]
Issue Type: <b>Bug</b>

Tengo varias pestañas abiertas , con consultas ejecutadas, al cambias de pestañas se queda en blanco y la consulta no responde al volver a ejecutarla

Azure Data Studio version: azuredatastudio 1.41.1 (33dce95b152227c4f10f6251ab30690fe9895c0c, 2023-01-28T00:46:39.274Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.75GB (12.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
ads-language-pack-es|Mic|1.41.0
agent|Mic|0.49.0
dacpac|Mic|1.12.0
import|Mic|1.5.4
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.21.0
azdata-sanddance|msr|4.0.1

</details>

**Comment by alanrenmsft** [comment]
looks like the same as #21851

**Comment by alanrenmsft** [comment]
translated to English: `I have several tabs open, with queries executed, when you switch tabs it goes blank and the query does not respond when you run it again`

**Comment by alanrenmsft** [comment]
@benitolnx are you connected to those servers with admin access to the sql server?

**Comment by cssuh** [comment]
Closing as no logs were provided.
