### ISSUE TITLE
Wizard- the page should initialize and render when the page is entered 

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#2184]
Right now the wizard is initialized and rendered every page when the wizard is opened

Expected behavior: it should delay until the page is entered

**Comment by aaomidi** [comment]
I don't think this is the right move. The client should render before the user enters the page.

I believe this would be a better move: https://github.com/Microsoft/sqlopsstudio/issues/2079

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impact an extension under active development.
