### ISSUE TITLE
Azure Data Studio and kqlmagic extension rendering table and chart do not adjust to width 

### ISSUE THREAD

**Issue by brijenshah** [microsoft/azuredatastudio#21859]
- Azure Data Studio Version: (1.41.1 - user setup) 
- OS Version: Windows 11 (10.0.22621 Build 22621)
- kqlmagic extension: kqlmagic: 0.1.114.post22 (https://github.com/microsoft/jupyter-Kqlmagic)
Steps to Reproduce:

1. Open a ADS
2. Add notebook (select Python 3 kernel)
3. !pip install Kqlmagic --no-cache-dir --upgrade 
4. %reload_ext Kqlmagic
5. %kql StormEvents | limit 10
   1. chek the response the table width is beyond the width of ADS and there is not scrollbar to navigate right
6. %kql StormEvents | summarize count() by bin(StartTime, 1d) | render timechart
   1. verify the render chart, the width is not expanded to ADS notebook width 

Does this issue occur when all extensions are disabled?: No

**Comment by chlafreniere** [comment]
@lucyzhang929 can you take a look at this one?

**Comment by brijenshah** [comment]
Any update on this or workaround to adjust the size for table and chart?

**Comment by lucyzhang929** [comment]
@brijenshah I am currently looking into the issue and will update as soon as possible.

**Comment by lucyzhang929** [comment]
@brijenshah The fix will be available in tomorrow's insiders build which can be downloaded [here](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch).
