### ISSUE TITLE
Unable to login at all

### ISSUE THREAD

**Issue by suraj50488** [microsoft/azuredatastudio#21876]
Issue Type: <b>Bug</b>

I downloaded and unzipped both release and insider bits. Upon opening the app, I see the accounts loading (forever). The client is not usable. not sure whats going on. Notifications say "Couldnt start ARP", Couldnt start serializationprovider, failed to start SQL Tools Service, couldnt start SQL tools service. Wasnt expecting this on released version as well.

Azure Data Studio version: azuredatastudio-insiders 1.42.0-insider (99a924dbcdce7bbaa0ab78b19f84e83035e54651, 2023-02-08T06:57:44.839Z)
OS version: Darwin arm64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @suraj50488 

Are you getting any error in logs? 
You should be able to open Logs folder using command: `Developer: Open Logs Folder`

Also please share settings from `settings.json` that you have configured in your environment (other than connections), so we can try to replicate.

**Comment by alanrenmsft** [comment]
I realized that you are using the ARM64 version of ADS, have you followed the instructions here in the macOS installation section: https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio

![image](https://user-images.githubusercontent.com/13777222/217953216-395dabb0-a9ad-4516-a621-da21a07b0914.png)

**Comment by alanrenmsft** [comment]
the issue is resolved after installing Rosetta and deleting the cache folder.

**Comment by suraj50488** [comment]
Thanks Alan
