### ISSUE TITLE
Unable to build project due to certificate signature failure

### ISSUE THREAD

**Issue by philcart** [microsoft/azuredatastudio#21870]
Type: <b>Bug</b>

Open database project
Once the project is loaded, right-click and choose "Build"
Fails with error
"Error downloading https://www.nuget.org/api/v2/package/Microsoft.Build.Sql/0.1.7-preview. Error: certificate signature failure"

Extension version: 0.21.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.73GB (2.39GB free)|
|Process Argv|--crash-reporter-id c42c0b61-9f22-4daf-a70b-c68a6420348b|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vstes627:30244334
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
azure-dev_surveyonecf:30548226
pyindex848cf:30577861
nodejswelcome1cf:30587006
2e4cg342:30602488
f6dab269:30613381
pythonsymbol12:30657548
vsctsb:30659830

```

</details>

**Comment by kisantia** [comment]
@zijchen any idea what could be causing this error when building an SDK-style sql project?

**Comment by zijchen** [comment]
I'm not sure. The signing on the package seems correct.

`dotnet nuget verify`:
![image](https://user-images.githubusercontent.com/13544267/217621191-ea2c9677-f57f-418c-bf32-5dec836f920f.png)

**Comment by zijchen** [comment]
Can you verify if your nuget.config has the appropriate certificates if you have one of these set: https://learn.microsoft.com/en-us/nuget/reference/nuget-config-file#trustedsigners-section

**Comment by kisantia** [comment]
Closing from lack of activity. Please reopen if the requested information can be provided
