### ISSUE TITLE
Connection Error: Failed to get token

### ISSUE THREAD

**Issue by Marjay-Pulumbarit-Weir** [microsoft/azuredatastudio#21874]
Issue Type: <b>Bug</b>

Connection Error: Failed to get token

The error above randomly pops up, I am unable to reproduce it. 

I noticed that re-authenticating to Azure solves the issue, although I didn't get the notification to re-authenticate, just a vague message that failed to get token.

Azure Data Studio version: azuredatastudio 1.33.1 (0b9ef714c823d662815f441aec4a94eaa21940f8, 2021-11-04T17:45:15.872Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No

**Comment by cheenamalhotra** [comment]
Hi @Marjay-Pulumbarit-Weir 

We would recommend you to please update ADS to latest v1.41.1 as many improvements have been made in this area.
Let us know if you do experience the issue with latest version.

**Comment by hifni** [comment]
I am too getting this error. I was happily connecting myself a few days back before I applied the update. My current ADS spec reads as: 

Version: 1.41.2 (system setup)
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:16:49.071Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by cheenamalhotra** [comment]
@hifni 

Can you quickly check if changing back the below setting "Azure: Authentication Library" to ADAL makes a difference?

<img src="https://user-images.githubusercontent.com/13396919/218652097-de6d32b1-02ff-486d-bb7e-13f42bd1e20f.png" width=600 />

Also please gather Azure logs and upload here to be able to identify error that occurred.

**Comment by gregchak** [comment]
I was having the same issue also.  Changing Azure Authentication Library to ADAL fixed my issue as well.  If you need logs with the setting set to MSAL please let me know and I can provide. The original post mentioned they were unable to reproduce.  For me, any connection using MFA generated this error and I can readily reproduce it.

**Comment by cheenamalhotra** [comment]
Azure Account Logs would help us understand the root cause. Please gather using information above and attach the same.

**Comment by gregchak** [comment]
I was able to readily reproduce, but since switching from MSAL to ADAL and then back to MSAL to send you the logs I'm no longer able to reproduce the error.  I will keep on MSAL authentication and see if this pops up again.  If, and hopefully when, it does I will post logs here.
