### ISSUE TITLE
Problems to visualize Query Plan (preview)

### ISSUE THREAD

**Issue by jaimepc** [microsoft/azuredatastudio#21891]
- Azure Data Studio Version: **1.41.1 (user setup)**
- OS Version: **Windows 11**

Steps to Reproduce:

1. When I open a new query and try to get the execution plan while checking the option "Enable Actual Plan", the tab for Query Plan (preview) is not appearing.
![image](https://user-images.githubusercontent.com/9295747/217751734-8625ece7-c1dd-45e0-ba97-ce471c67fc27.png)
2. I have also tried on clicking the option "Estimated Plan" but still I am not able to get anything just the query running without showing the Query Plan (preview) tab.

From my side, I have installed the program in D drive, then C drive but the issue persist 
Also, I have installed SSMS along with the ADS just to make sure all possible DLLs or dependencies would be installed on my machine
Finally, I have also enabled the functionality "**workbench editor enable preview**" to True maybe I need to save it once I check the option but there is no Save button anywhere.

More info:
I am trying to connect to a Serverless SQL endpoint from a synapse instance and running a random query in Master DB

TO-DO:
- connect to a SQL server or Azure SQL DB and repeat the same test in a database
- The last thing that I will test, is installing it on my personal laptop instead of my desktop PC.

Does this issue occur when all extensions are disabled?: **Either if I disable or enable all extensions, the issue persists**

**Comment by alanrenmsft** [comment]
@aasimkhan30 please triage

**Comment by aasimkhan30** [comment]
@jaimepc. Currently, Synapse does not support execution plan on serverless sql endpoint. Please use a dedicated sql pool for it.
