### ISSUE TITLE
Allow user to turn off the special handling for JSON strings in query editor

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#21908]
This request is from a user who contacted @erinstellato-ms.

When ADS detect a JSON string in the query results, a hyperlink will be added to the cell and upon click, the content will be opened in a separate document. 

The hyperlinks could sometimes be annoying and make is hard to do click and selection because clicking on a JSON cell will open a new document.
1. The underline decoration should only be shown on hover.
2. A setting should be introduced to decide whether we treat JSON differently

**Comment by erinstellato-ms** [comment]
Original item: https://learn.microsoft.com/en-us/answers/questions/1165294/underlined-data-in-azure-data-studio

**Comment by erinstellato-ms** [comment]
@alanrenmsft can you share the name of this setting please?  I want to confirm I have it correct in the release notes.  Thanks!

**Comment by alanrenmsft** [comment]
@erinstellato-ms `resultsGrid.showJsonAsLink` is the setting that user can add to the configuration file, it is a boolean value. unfortunately, I just noticed it is not available in the settings editor UI(I will take a look), but adding it to the configuration file directly does work. 

also as you can see in the screenshots I attached here: https://github.com/microsoft/azuredatastudio/pull/21915#issue-1580507467, by default the underline won't show for links, it is visible only when user move the mouse over it. 

How to update the setting:
1. Open user settings and click the `Open Settings (JSON)` button circled in red.
![image](https://user-images.githubusercontent.com/13777222/224084034-94d95d60-6301-420f-8aee-2d6e57999170.png)
2. add `"resultsGrid.showJsonAsLink":true` or `"resultsGrid.showJsonAsLink":false` to it and save the file.
![image](https://user-images.githubusercontent.com/13777222/224085224-abfe6c31-d050-41e8-8541-cb7ec1e52619.png)
