### ISSUE TITLE
CPU and Memory Usage High w/ Data Workspace extension enabled

### ISSUE THREAD

**Issue by v3gan** [microsoft/azuredatastudio#21916]
Type: <b>Performance Issue</b>

Open VS Code with Data Workspace extension enabled

Extension version: 0.4.0
VS Code version: Code 1.75.0 (e2816fe719a4026ffa1ee0189dc89bdfdbafb164, 2023-02-01T15:23:45.584Z)
OS version: Windows_NT x64 10.0.19045
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 5800X 8-Core Processor              (16 x 3800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.93GB (16.77GB free)|
|Process Argv|--folder-uri file:///d%3A/repos/tutorials/code/udemy/complete-node-js/100_nasa-project|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   108	 44064	code main
    0	   266	  3984	   extension-host
    0	    98	 13076	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\monk\.vscode\extensions\streetsidesoftware.code-spell-checker-2.16.0\packages\_server\dist\main.js --node-ipc --clientProcessId=3984
    0	   117	 39764	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\monk\.vscode\extensions\ms-python.vscode-pylance-2023.2.20\dist\server.bundle.js --cancellationReceive=file:ff8ad9531b2b20737b01d4437601124331897d8cd8 --node-ipc --clientProcessId=3984
    0	    39	 12052	   utility-network-service
    0	    93	 15116	   issue-reporter
    0	   127	 31068	   shared-process
    0	    89	 40248	     fileWatcher
    0	    78	 47436	     ptyHost
    0	     4	 15524	       C:\WINDOWS\System32\cmd.exe
    0	     7	 46816	       console-window-host (Windows internal process)
    0	   112	 40820	   gpu-process
    0	   173	 48172	   window (node.yml - 100_nasa-project - Visual Studio Code)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (node.yml - 100_nasa-project - Visual Studio Code)
|    Folder (100_nasa-project): 131 files
|      File types: js(30) mp3(18) json(16) jpg(9) png(6) txt(5) gitignore(3)
|                  html(3) map(2) dockerignore(1)
|      Conf files: package.json(3) github-actions(1) settings.json(1)
|                  dockerfile(1);
```

</details>

**Comment by kburtram** [comment]
@v3gan The process information included in the report shows the CPU utilization at 0%.  Do you have any additional information on what you're observing with this bug?

```
CPU %	Mem MB	   PID	Process
    0	   108	 44064	code main
    0	   266	  3984	   extension-host
    0	    98	 13076	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\monk\.vscode\extensions\streetsidesoftware.code-spell-checker-2.16.0\packages\_server\dist\main.js --node-ipc --clientProcessId=3984
    0	   117	 39764	     "C:\Program Files\Microsoft VS Code\Code.exe" --ms-enable-electron-run-as-node c:\Users\monk\.vscode\extensions\ms-python.vscode-pylance-2023.2.20\dist\server.bundle.js --cancellationReceive=file:ff8ad9531b2b20737b01d4437601124331897d8cd8 --node-ipc --clientProcessId=3984
    0	    39	 12052	   utility-network-service
    0	    93	 15116	   issue-reporter
    0	   127	 31068	   shared-process
    0	    89	 40248	     fileWatcher
    0	    78	 47436	     ptyHost
    0	     4	 15524	       C:\WINDOWS\System32\cmd.exe
    0	     7	 46816	       console-window-host (Windows internal process)
    0	   112	 40820	   gpu-process
    0	   173	 48172	   window (node.yml - 100_nasa-project - Visual Studio Code)
```

**Comment by v3gan** [comment]
The cpu usage was around 40%. My fans were getting noisy! I honestly didn't
expect anyone to reply to this. I just thought it would end up in the same
dustbin that I assumed all app-prompted-report-this bug reports went to.
Thanks for getting back to me and sorry I don't have more information. I
don't use the extension regularly, so I'll just leave it disabled.

**Comment by kisantia** [comment]
@v3gan can you check if this still happens with the latest version 0.5.0 of data workspace? The extension was updated in the latest version to no longer activate on *, so it should only activate if the workspace has a .sqlproj file or if the sql projects extension is used

**Comment by kisantia** [comment]
Closing issue. Please reopen if this is still happening and more information can be provided

**Comment by v3gan** [comment]
Thanks for looking into this. I haven't tested this as I don't use the
extension in my day-to-day grind, and haven't had the time (or desire
frankly) to reinstall it and recreate the issue. I'm sure it's great!
Appreciate you!
