### ISSUE TITLE
Publish profile load fails for windows authentication

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#21927]
Steps to Reproduce:

1. Open Publish UI for a sql project.
2. Load publish profile with Windows auth.
3. Load fails with following error:
![image](https://user-images.githubusercontent.com/57200045/218577104-19ac5ed2-6d06-4338-a629-01352fcdd385.png)

**Comment by cheenamalhotra** [comment]
Hi @SakshiS-harma 

As discussed offline, you'd need to ensure all connection options are considered when restoring connection profile from connection string during publish. I will remove Connection area as it needs to be handled within Sql Database Project extension.
