### ISSUE TITLE
Cannot "select/unselect all" on Schema Compare

### ISSUE THREAD

**Issue by el1jaC** [microsoft/azuredatastudio#21944]
Hi all,
I'm trying to create a deploy script from Schema Compare.
I need to select only one stored procedure from the list, but there is no function about select/unselect all. That is a awkward scenario because I have to unselect ticks one by one.

Do you have any advice/solution?
![multi](https://user-images.githubusercontent.com/19836192/219096202-dfbe6759-2aa4-4f4c-ad3f-7fd9169759e5.png)

**Comment by kisantia** [comment]
closing as dup of https://github.com/microsoft/azuredatastudio/issues/10430
