### ISSUE TITLE
Cannot re-generate script after first time

### ISSUE THREAD

**Issue by el1jaC** [microsoft/azuredatastudio#21945]
- Azure Data Studio Version: 1.41.2
- OS Version: W10

Steps to Reproduce:

1. Schema Compare
2. Generate Script
3. Try to Generate Script
4. The "Generate script" button is dead after the generation task is completed. You need to re-compare.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kisantia** [comment]
I'm unable to repro this. The "Generate Script" button is still enabled for me after I generate the script for a schema compare. Can you please provide more details on how to repro this?
![schemaCompareGenerateScript](https://user-images.githubusercontent.com/31145923/219504490-d7d9329c-0524-43b5-9ad8-db499675c462.gif)
