### ISSUE TITLE
Azure Data Studio Linked Account Issues

### ISSUE THREAD

**Issue by murrydeleeuw2** [microsoft/azuredatastudio#21948]
I am having an issue with Azure Data Studio and connecting to my linked account. I previously could use data studio with my account but now when connecting it just spins and spins and actually never finds my linked account. I have un-installed and re-installed using the 'User Installer'.

![image](https://user-images.githubusercontent.com/125502266/219129542-e21a5f95-26d9-43a3-8c83-bf37536ad3e5.png)

Some additional background:

- OS: Microsoft Windows 10 Enterprise
- Build Version: Windows 10 GAC 21H2
    - AD is Cloud based I am able to connect to my Azure SQL db when using SSMS and use Azure Active Directory Integrated
- My other teammates are able to connect using ADS
- When trying to connect using ADS I get a loop of trying to connect. And I never get a timeout or failure. It just spins
- When I try and click on Refresh account credentials nothing occurs
- See attached some other photos

![image](https://user-images.githubusercontent.com/125502266/219129832-98d6fa6b-09b6-4e82-98dd-82a70df9e17c.png)

![image](https://user-images.githubusercontent.com/125502266/219129892-367289ef-eef3-4784-a027-d4ef3eb7648b.png)

**Comment by cheenamalhotra** [comment]
Hi @murrydeleeuw2 

Please verify your proxy setup. This looks like a typical proxy misconfiguration.
You can validate your settings with your colleagues.
- Verify `http.proxy` setting in _settings.json_ is correctly provided. Also note, `http_proxy` and `https_proxy` env variables also play a role. Failure to provide correct information can lead to issues where Azure  Data Studio tries communicate with network.

![image](https://user-images.githubusercontent.com/13396919/219133659-1d95c9ae-0f66-4308-96ad-3631a214c137.png)

Correct format of this setting, if you're working behind proxy is:
`"http.proxy": "https://user@fqdn:yourPassword@yourProxyURL.com:8080"`

**Comment by murrydeleeuw2** [comment]
@cheenamalhotra 

I have confirmed with a co-worker of mine who can access AAD to connect, that the settings appear to be the same.

![image](https://user-images.githubusercontent.com/125502266/219138199-810d7321-55fd-47b6-b352-e274b4ae1702.png)

Also, I ran developer tools and stepped through trying to create a new connection and I see that there are errors that come up.  

![image](https://user-images.githubusercontent.com/125502266/219139813-f485ff18-5cb9-48b0-85ce-fcbc64f2d282.png)

Lastly, I have our IT admin uninstall and and re-install.

**Comment by cssuh** [comment]
Hi @murrydeleeuw2, which version of ADS are you running?

**Comment by murrydeleeuw2** [comment]
@cssuh 

![image](https://user-images.githubusercontent.com/125502266/220132212-9407ccfb-6ac1-4b53-adfb-151605e09cd9.png)

**Comment by murrydeleeuw2** [comment]
@cheenamalhotra 

Going through the log files I came across this error:
From main.log
[2023-02-21 12:40:08.799] [main] [error] Blocked vscode-webview request vscode-webview://**SOMETHINGHERE**/index.html?id=**SOMETHINGHERE**&swVersion=4&extensionId=&platform=electron&vscode-resource-base-authority=vscode-resource.vscode-cdn.net&parentOrigin=vscode-file%3A%2F%2Fvscode-app


From renderer1.log
[2023-02-21 12:39:37.154] [renderer1] [error] Failed to create Object Explorer session
[2023-02-21 12:39:48.179] [renderer1] [error] Unexpected error populating Azure Account dropdown : TypeError: Cannot read properties of undefined (reading 'map')


From sharedprocess.log
[2023-02-21 12:37:17.050] [sharedprocess] [info] Starting worker process with pid 4484 (type: fileWatcher, window: 1).
[2023-02-21 12:37:18.305] [sharedprocess] [info] WSL is not installed, so could not detect WSL profiles

**Comment by cheenamalhotra** [comment]
@murrydeleeuw2 

Please gather Azure logs and upload them for investigation here. Feel free to mask any sensitive information. After enabling logging, please restart ADS and run use-case.

To mitigate, can you try switching back to ADAL if that resolves this issue and if changing back to MSAL brings the issue back?

![image](https://user-images.githubusercontent.com/13396919/220424069-20345b07-3122-4aec-9333-9763df281de4.png)

**Comment by murrydeleeuw2** [comment]
@cheenamalhotra 

I don't even have that as an option: Azure: Authentication Library under extension in settings.  I also tried what the Bot suggested and turned on verbose but it wasn't for Azure.  It was only for MSSQL config

![image](https://user-images.githubusercontent.com/125502266/220437755-b02f71db-e1af-4b48-b01b-cd9b223ec5de.png)


![image](https://user-images.githubusercontent.com/125502266/220438193-4d099a0a-955b-4c02-8e14-79de2785eb41.png)

**Comment by cheenamalhotra** [comment]
@murrydeleeuw2 Please look into the issue https://github.com/microsoft/azuredatastudio/issues/21422 for details as it looks similar to your usecase. The inbuilt AzureCore extension is likely disabled in your case as well.

**Comment by murrydeleeuw2** [comment]
@cheenamalhotra 

That worked.  It was because the @builtin Azure (Core) feature was disabled.  I enabled and I am not able to use my AD account.

Thank you for your help.

**Comment by tjhee** [comment]
[20230414T100057.zip](https://github.com/microsoft/azuredatastudio/files/11234911/20230414T100057.zip)
Oury requested my log files from my Mac to troubleshoot my inability to connect to my on-prem DB (works perfectly on Windows version of ADS.
Our thread is here:
https://learn.microsoft.com/en-us/answers/questions/1194048/azure-data-studio-on-mac-just-spins-but-works-on-w
