### ISSUE TITLE
Losing intellisense when connection is lost

### ISSUE THREAD

**Issue by ltsyen** [microsoft/azuredatastudio#21959]
Issue Type: <b>Bug</b>

If the connection is lost after specific time, the intellisense is also lost.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD EPYC 7763 64-Core Processor                 (16 x 2445)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|64.00GB (29.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
[console.log](https://github.com/microsoft/azuredatastudio/files/10756684/console.log)

</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuremonitor|Mic|0.1.9
cms|Mic|0.9.2
dacpac|Mic|1.12.0
import|Mic|1.5.4
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.18.0
server-report|Mic|0.2.3
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|0.21.0
whoisactive|Mic|0.1.4
azdata-sanddance|msr|4.0.1

</details>

**Comment by alanrenmsft** [comment]
@ltsyen what do you mean by connection lost? isn't it expected if a connection cannot be made?

**Comment by ltsyen** [comment]
@alanrenmsft I think it's more of a connection issue, and that indeed the lost intellisense is one of the consequences.

I think this might be related to some other connection topics like 

https://github.com/microsoft/azuredatastudio/issues/21766 
https://github.com/microsoft/azuredatastudio/issues/21774
#21788

**Comment by erinstellato-ms** [comment]
@alanrenmsft @cheenamalhotra  I think this is independent of Synapse, though.  This is frequent feedback from users ("Intellisense stops working).

**Comment by cheenamalhotra** [comment]
This should get resolved with the March release when `mssql:enableSqlAuthenticationProvider` setting is enabled.

**Comment by cheenamalhotra** [comment]
I looked more into it and I'm noticing a connection/connect event being triggered by QE after access token expires, which leads to creating a new connection. 

I will need to to disable that refresh when `mssql:enableSqlAuthenticationProvider` setting is enabled to allow continuing work on the same connection as the token will be refreshed internally. Other than that, intellisense connection seemed to have picked up the updated access token.

**Comment by cheenamalhotra** [comment]
Closing issue as `mssql:enableSqlAuthenticationProvider` setting is now enabled by default in the latest insiders build.
This will be available with the next release.
