### ISSUE TITLE
Unable to open or create connection on insiders

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#21950]
1. Click on add new connection icon, error pops up saying:
"Cannot read properties of undefined (reading 'password')"

2. click on New Connection, nothing happens.

This means I am unable to open or create a connection

![NewConnectionOnInsidersNotWorking](https://user-images.githubusercontent.com/18018452/219155285-a1c725dc-db45-4200-9ef3-d858f11cefa7.gif)

**Comment by cheenamalhotra** [comment]
@lewis-sanchez 
Can you please take a look?

This seems related to latest check-in and possibly this change: https://github.com/microsoft/azuredatastudio/pull/21813/files#diff-1c35cfd3000efef5f2127a369f5c49e1c5c6c8d83e12582d42b78326a1605f76R420

**Comment by lewis-sanchez** [comment]
@cheenamalhotra, looking now.

**Comment by lewis-sanchez** [comment]
This issues was fixed by this PR: https://github.com/microsoft/azuredatastudio/pull/21953
