### ISSUE TITLE
Connect Button throws exception

### ISSUE THREAD

**Issue by jtsom** [microsoft/azuredatastudio#21964]
Issue Type: <b>Bug</b>

Trying to use the "Connect" button in an existing window throws an error in the console and does not present the Connect pane. Cannot connect to a database.

![image](https://user-images.githubusercontent.com/13488/219435416-0f3f9d18-27e4-44c0-99f3-9e4539321ead.png)

Azure Data Studio version: azuredatastudio-insiders 1.42.0-insider (d9b24522e5c5ab11301ebc9c3addbcedf8e9229b, 2023-02-15T06:32:04.670Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8500 CPU @ 3.00GHz (6 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.78GB (14.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.12.0
import|Mic|1.5.4
schema-compare|Mic|1.18.0
sql-database-projects|Mic|0.21.0
sql-search|Red|0.4.0
ADS-add-columns|sof|0.0.12
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
Hi @jtsom 

This looks same as https://github.com/microsoft/azuredatastudio/issues/21950, and has been addressed in the 'main' branch but hasn't made it to insiders yet. Will keep this issue open till we get the insiders build available.

**Comment by cheenamalhotra** [comment]
Hi @jtsom 

Insiders release update now contains the fix, closing issue as resolved.
