### ISSUE TITLE
Create an API to create connection with connection string

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#21961]
Currently in sqlprojects extension, while loading publish profile- it reads target connection string from the file. It then parses the string to get the settings and options. It would be good if there is an API which does this, and reads all the options.

**Comment by cheenamalhotra** [comment]
Hi @SakshiS-harma 

I noticed we have this already: https://github.com/microsoft/azuredatastudio/blob/bd797ea6e141053dc23ae2486eb600361f112427/src/sql/azdata.d.ts#L572

**Comment by cheenamalhotra** [comment]
Closing as support exists, will follow up internally.

**Comment by SakshiS-harma** [comment]
Created https://github.com/microsoft/azuredatastudio/issues/22654 to keep track of using this API in projects extension.
