### ISSUE TITLE
Undefined error upon opening Connection Dialog

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#21979]
- Azure Data Studio Version: 1.42.0-Insiders
- OS Version: MacOS

Steps to Reproduce:

1. Open ADS
2. Open the Connection Dialog
3. Error is thrown in the Dev Tools Console:
![Screenshot 2023-02-17 at 11 51 50 AM](https://user-images.githubusercontent.com/18150417/219777769-94a93722-f3ed-4275-a8c8-29dc46dfc333.png)

**Comment by cssuh** [comment]
Upon initial investigation, it seems like the culprit might be `this._initialConnectionInfo.authenticationType = AuthenticationType.SqlLogin;` (line 673 in `connectionWidget.ts`), introduced here: #21813 

@lewis-sanchez do you think you could take a look?

**Comment by lewis-sanchez** [comment]
@cssuh, yes looking now.

**Comment by lewis-sanchez** [comment]
@cssuh, does your branch have the latest from main? I'm not able to see that error when I connect to accounts.
