### ISSUE TITLE
Buttons for Window Commands Missing

### ISSUE THREAD

**Issue by jim-elrod** [microsoft/azuredatastudio#21972]
I just upgraded Azure Data Studio to v1.41.2 on Pop Os.

In my `settings.json` I have the following entry: `"window.titleBarStyle": "custom"`

It worked with the previous version, and it works on VSCode v1.75.1

¯\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/123968261/219528962-47b98f9f-9afd-4cec-a419-8ca2f31d343b.png)

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:08:18.398Z)
OS version: Linux x64 6.0.12-76060006-generic
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 5850U with Radeon Graphics (16 x 1915)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|0, 1, 1|
|Memory (System)|62.14GB (54.21GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|pop|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|pop|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-markdownlint|Dav|0.49.0
material-icon-theme|PKi|4.23.1

(1 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment]
Closing as resolved.
