### ISSUE TITLE
Connection Dialog UI is showing black fields in MySQL extension in insiders

### ISSUE THREAD

**Issue by nitishsharma25** [microsoft/azuredatastudio#21973]
- Azure Data Studio Version: 1.42.0-insider
- OS Version: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Download MySQL extension in insider
2. Click on New Connection and select MySQL from Connection type
3. Select Authentication type, dropdowns are also not working as expected. 

![image](https://user-images.githubusercontent.com/112425736/219551658-187f9ad2-61b2-4439-9055-f19161a07a30.png)

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
Hi @nitishsharma25 

The fix has been merged, it will be available in the future insiders build.
