### ISSUE TITLE
Connection issue when saving a new query to disk

### ISSUE THREAD

**Issue by dubeg** [microsoft/azuredatastudio#21988]
Issue Type: <b>Bug</b>

1. Open Azure Data Studio
2. Connect to an MSSQL Server database (2019).
3. Open a new query tab/view (which should be automatically connected to your database after opening) using Ctrl+N.
4. Save the new query.
5. The query view will be in a weird connection state, where it will still appear connected (the "Disconnect" button will be present), but the database dropdown will have a red border.
![image](https://user-images.githubusercontent.com/6020602/220144747-84ee7353-fe42-4619-9f8f-a26a006f8c43.png)

  - In that state, if you try to execute the query, you'll get an error:
"Execution failed due to an unexpected error: 
	Cannot connect to the database due to invalid OwnerUri (Parameter 'OwnerUri')"
![image](https://user-images.githubusercontent.com/6020602/220144793-9ed4cf07-c54a-4596-a5c9-df8791145457.png)

- A notification might be displayed (I'm not sure it happens everytime, I might have screenshotted this from another instance where I tried to repro the issue): "Failed to save 'SQLQuery_1.sql - localh...grated)': Cannot read properties of undefined (reading 'resource').

![image](https://user-images.githubusercontent.com/6020602/220144609-92c769e6-248e-414a-9298-da7558291b0a.png)

To work around this issue, I click "Disconnect" in the query tab/view, then re-connect.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.20348
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4214 CPU @ 2.20GHz (4 x 2195)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|8.00GB (1.93GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

My connection settings, in case that's helpful.
```
{
    "workbench.editorAssociations": {
        "*.{sqlplan}": "workbench.editor.executionplan"
    },
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        }
    ],
    "datasource.connections": [
        {
            "options": {
                "connectionName": "",
                "server": "localhost",
                "database": "Runtime",
                "authenticationType": "Integrated",
                "user": "",
                "password": "",
                "encrypt": "true",
                "trustServerCertificate": "true",
                "applicationName": "azdata",
                "originalDatabase": "Runtime",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": "Runtime"
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "237b5c83-5800-4bce-8091-9c2c681bcc2f"
        }
    ],
    "security.workspace.trust.untrustedFiles": "open"
}
```

**Comment by alanrenmsft** [comment]
@dubeg can you reproduce this issue consistently?

**Comment by dubeg** [comment]
@alanrenmsft Yes!
