### ISSUE TITLE
Extensibility: Allow extension developers to create prepared statements in QueryProvider

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#2200]
Currently there is no way to use PreparedStatements, having them would especially when mitigating against SQL Injection bugs.

**Comment by MattIrv** [comment]
@aaomidi Really what we need is some way to execute queries with parameters while avoiding sql injection. Prepared statements would do it, but there are other ways to just set parameters from the C# client side as well

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impact an extension under active development.
