### ISSUE TITLE
I have 2 accounts, belonging to 2 separate tenants, using the same id, and I cannot switch from one to the other

### ISSUE THREAD

**Issue by maxmumford** [microsoft/azuredatastudio#22013]
Issue Type: <b>Bug</b>

We have two separate tenants in azure, and I have a user in each. Both of those users share the same ID (lets say me@domain-a.com). 

However the login for tenant A is me@domain-a.com, and the login for the tenant B is me@domain-b.com. 

After installing ADS, I logged in to tenant A using my email me@domain-a.com. I then realised all our databases are in tenant B. So I logged out, and logged in to tenant B using me@domain-b.com. 

When returning to ADS, I see that it has logged me _back in_ to tenant A! Despite me choosing the credentials for tenant B when the azure login page asked me to choose a tenant. I cannot seem able to log out of tenant A properly and log back in to tenant B.

Things I have tried:
- Deleting `~/Library/Application Support/azuredatastudio/`
- Setting a different --user-data-dir
- The insiders release of ADS
- Logging out of all azure accounts before logging in to the correct one
- Using a new unused browser
- Looking in keychain to find a relevant record to delete but could not find one

Note: I was able to reproduce this problem on Windows.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:18:32.853Z)
OS version: Darwin arm64 22.2.0
Restricted Mode: No
Preview Features: Disabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|43, 43, 46|
|Memory (System)|64.00GB (5.32GB free)|
|Process Argv|--ms-enable-electron-run-as-node --user-data-dir /tmp/ads|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @maxmumford 

> When returning to ADS, I see that it has logged me back in to tenant A! Despite me choosing the credentials for tenant B when the azure login page asked me to choose a tenant. I cannot seem able to log out of tenant A properly and log back in to tenant B.

It depends on the account you authenticate with microsoft online. And if it has associated tenant available in the list (as in Azure Portal), it should show up in the Azure tree.

Please check a few things.. have you ignored tenant you intend to log into second time by accident?
You can look for the below setting in settings.json:

`"azure.tenant.config.filter"`

Try to remove this and add account again.

If that's not applicable, I would recommend capturing logs (with PII Logging enabled) to help understand which tenant you logged into when you add account. If you wish to upload for investigation, please mask any sensitive information.

**Comment by maxmumford** [comment]
Hi @cheenamalhotra, thanks for your quick reply.

My settings.json was almost empty and had no reference to ignored tenants so I don't think it is that. I have also deleted the entire ~/Library/Application Support/azuredatastudio directory which would have removed it.

As for the logs, I did as requested but each time the 1-Azure Accounts.log file was completely empty. I tried deleting the azuredatastudio directory, restarting ADS, setting log level to all, and re-running the process, and nothing resulted in anything being added to the logs. The path I was looking at was:

`/Users/max/Library/Application Support/azuredatastudio/logs/20230223T185632/exthost1/output_logging_20230223T185634`

**Comment by maxmumford** [comment]
My settings.json:

```
{
    "workbench.editorAssociations": {
        "*.{sqlplan}": "workbench.editor.executionplan"
    },
    "azure.loggingLevel": "Verbose"
}
```

**Comment by maxmumford** [comment]
Ok so I have found a workaround. I added the following line to the root of my settings.json:

`"azure.tenant.config.filter": "my-tenant-guid-to-ignore"`

Where `my-tenant-guid-to-ignore` is the tenant id from Azure Devops > Active Directory > Properties > Tenant ID of the tenant I _don't_ want to log in to. Then restarted ADS, removed and added the login and now I am able to access my DBs. 

However the accounts list in ADS still shows the wrong email address.

**Comment by cheenamalhotra** [comment]
> As for the logs, I did as requested but each time the 1-Azure Accounts.log file was completely empty. 

I hope you're running command 'Developer: Open Logs Folder' every-time you restart/reload ADS, as the path changes too.. Sometimes it does show 0 KB but opening it loads logs, maybe try giving it some time :)

> However the accounts list in ADS still shows the wrong email address.

I'm interested to learn about how your accounts are created. Can you elaborate more about your account/email relation here?
- Which tenant is the owner of the user account (calling it Tenant A)? 
- And how was it given access to Tenant B (where you want to access it)? Was it added as a guest user?
- Why do you not see both tenants when you login with original email? Is that how it works in Azure Portal too?

**Comment by maxmumford** [comment]
I wasn't! When I do run that command I do indeed get the logs. 

This morning I removed the ignore setting from my settings.json, removed and re-added the account and seem able to connect without issue. It still shows the wrong email address, but I'm beginning to think that is because the ID (what it's showing) is different from the actual login username. 

I'm going to close this as I think I have a decent enough workaround / fix, and if it recurs I'll create another issue.

Thanks for your help.
