### ISSUE TITLE
not able to see the Administrative tab to check Sql jobs

### ISSUE THREAD

**Issue by satish84** [microsoft/azuredatastudio#22039]
Issue Type: <b>Bug</b>

not able to see the Administrative tab to check Sql jobs

Extension version: 0.0.2
Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.79GB (12.48GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
@satish84 could you please elaborate on this issue?  The SQL Agent UI should be in the Server page of the Manage dashboard.  Are you not seeing it there?

**Comment by alanrenmsft** [comment]
@satish84 please make sure you have the Agent extension installed. and let us know if you have any questions
