### ISSUE TITLE
download link not working

### ISSUE THREAD

**Issue by Xinyieng** [microsoft/azuredatastudio#22037]
Hi,
The download link is not working for the mac download.

<img width="1193" alt="Screen Shot 2023-02-25 at 2 40 51 PM" src="https://user-images.githubusercontent.com/124390868/221378729-6619f8c3-6715-4b3e-b9e1-8df758000a95.png">

**Comment by kburtram** [comment]
@Xinyieng I confirmed that the link https://go.microsoft.com/fwlink/?linkid=2222680 is currently working.  This could have been a temporary outage somewhere.  You can also try the direct link if the forward-link still isn't working for you https://azuredatastudio-update.azurewebsites.net/1.41.2/darwin-arm64/stable.
