### ISSUE TITLE
Angular UI code not working with Azure Data Studio

### ISSUE THREAD

**Issue by jdg9001** [microsoft/azuredatastudio#22066]
- Azure Data Studio Version: 1.41.2
- OS Version: Windows 11 Pro 22H2 OS build 22621.1265

Problem Description:
Trying to use Angular inside Azure Data Studio. Code is in 
https://github.com/microsoft/azuredatastudio/wiki/Angular-UI-Guidelines
Copied code from link. I get an error "cannot find module" 'sql/parts/bootstrap/bootstrapService' and
'sql/example/myComponent'.
Any suggestions or sample extension code for running angular code with Azure Data Studio.

Steps to Reproduce:

1. Install the following:
a) VS Code
b) Azure Data Studio Debugger Extension in VS Code
c) Git
d) NodeJS
e) TypeScript - npm install -g typescript
f) Yeoman Extension Generator - npm install -g yo generator-azuredatastudio 
g) Azure Data Studio
h) vsce - npm install -g vsce
2. Change to parent directory ie cd C:/ADS
a) yo azuredatastudio
3. Open app folder with Visual Studio Code. Code will be highlighted with errors, module not found.

![image](https://user-images.githubusercontent.com/32844274/221987041-309da3d2-1f44-491e-828c-277a2f5881d9.png)

Does this issue occur when all extensions are disabled?: Yes

 N/A - we are tyring to bootstrap angular to exentions

Attachments - full files zipped
[1answer-master.zip](https://github.com/microsoft/azuredatastudio/files/10855062/1answer-master.zip)

**Comment by Charles-Gagnon** [comment]
Unfortunately angular is not directly available for extensions to use - they run in a separate process that doesn't have access to the DOM.

We do expose a number of APIs through our extension API that can be used to display UI from an extension though - you can access this through the `azdata` module - you can see many examples of this in our extensions e.g. https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-database-projects/src/dialogs/addDatabaseReferenceDialog.ts

**Comment by jdg9001** [comment]
Hi Charles, thanks for quick response. Is there any other frameworks or
libraries that allow us to build a customized UI in Azure Data Studio. For
example React. What we are trying to do is take advantage of Azure Data
Studio APIs and then present the data in a customized UI.

**Comment by Charles-Gagnon** [comment]
You could look into using a [CustomEditor](https://code.visualstudio.com/api/extension-guides/custom-editors#custom-editor-api-basics). That limits you to creating an editor (not a dialog) but that should allow you to use whatever frameworks you want. 

(we're a fork of VS Code so their docs will generally be applicable to us as well. Although we are currently ~1 year behind them, so there may be APIs that exist in VS Code that we don't have yet as a heads up. If you come across such scenarios feel free to open an issue and we can look into porting over the necessary changes early if it's not too huge of a task)
