### ISSUE TITLE
Different Localhost instances share the same login credentials

### ISSUE THREAD

**Issue by richardseftonTNP** [microsoft/azuredatastudio#22131]
I have a couple of local Docker mssql images that I connect to frequently for different projects. 

I have created two different connections, both to localhost (on the default port 1433). They both have the sa user to login but each container has a different password. 

If I try to save the credentials for one of these connections, it overwrites the credentials stored for the other. 

I think that if you are creating two separate connections, you should be able to specify login credentials for either of these without having an impact on any other connection.

**Comment by cheenamalhotra** [comment]
Hi @richardseftonTNP 

It seems like the server name, port and credentials you're using to connect to both docker instances is same, how do you differentiate between the 2 images when connecting from ADS? Are you running one docker image at a time?

ADS will only be able to save credentials separately if you provide that difference in connection strings via server name/alias, port or username. The identity of password is managed with the server credentials that you provide.

**Comment by kburtram** [comment]
From ADS's perspective if the server is running on the same machine & port than it's the same server.  A couple workarounds would be to use different ports for different containers or to used named instances, but not sure if that works with docker.  Also using different user account names on the different containers would workaround this limitation.  I'll mark as an "Enhancement" for future consideration but unfortunately we don't have support for the exact use case you've mentioned.
