### ISSUE TITLE
Output window displays every time an exception is thrown in STS

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22149]
- Azure Data Studio Version: `main`
- 
Steps to Reproduce:

1. Run a scenario that raises an exception in STS

Expected: Errors are shown to users with appropriate error messages and diagnostics are logged to the output console in the dev tools.

Actual: The exception pops up the output window.  This isn't a good UX.

![image](https://user-images.githubusercontent.com/599935/222869970-91c9ec72-1db6-414f-8b1f-aae584123c5a.png)

**Comment by Charles-Gagnon** [comment]
FYI - @alanrenmsft changed this a while back to only auto-show in Dev mode to help us see and address issues. In packaged builds it shouldn't pop up. 

https://github.com/microsoft/azuredatastudio/pull/21880

**Comment by kburtram** [comment]
@Charles-Gagnon thanks for that context!  I don't think this is a problem in dev mode.  Let me confirm & close.
