### ISSUE TITLE
Adding Linked Accounts with the same first and last names but totally different domains does not work. 

### ISSUE THREAD

**Issue by roryteas** [microsoft/azuredatastudio#22154]
- Azure Data Studio Version: 1.41.2
- OS Version: Windows 11

Steps to Reproduce:

1. Have an account already linked to Azure Data Studio
2. Try to link an account with the same name but different domain ex tomcommon@microsoft.com vs tomcommon@microsoftstudio.com.
3. Azure Data Studio will think you are adding an already added user and will therefore do nothing.
4. Cry

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
Hi @roryteas 

Could you please validate the behavior with latest insiders and let us know if it continues to exist?
https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch

Thanks!

**Comment by roryteas** [comment]
Works perfect.

Thank you,
Cheers
Rory

**Comment by cheenamalhotra** [comment]
Thanks for confirming, it will be available in the April release (1.43)
Closing the issue as resolved.
