### ISSUE TITLE
A11y_SQLdatabase projects extension_Advance Publish_Exclude Object Type_Meaningful Sequence: After selecting any record, with Ctrl+option+ down arrow key focus is shifting to previous un-selected record and it skips all the selected records while navigating through the table cells in Exclude Object Type grid.

### ISSUE THREAD

**Issue by manaswita-chougule** [microsoft/azuredatastudio#22189]
### GitHub Tags:
#A11yWCAG2.1; #A11ySev2; #A11yTCS; #DesktopApp; #SH-SQL Azure Data Studio-MAC-March23; #SQL Azure Data Studio; #MAC; #AINotInScope; #WCAG1.3.2; #Meaningful Sequence; #Voiceover;

### Environment Details:​
Application Name: SQL Azure Data Studio
Version: 1.42.0-insider (Universal)
MAC Version: macOS Ventura 13.3

### Repro Steps:

1.Start Voiceover with using shortcut key Command+F5.
2.Launch Azure Data Studio
3.Tab till extension and search for “SQL Database Projects” and install it.
4.Tab till database project and press enter.
5.“Database Project” panel will open.
6.Tab till existing project name and press context menu button(right click).
7.Tab till "Publish" menu-item in list and press enter.
8.Tab till "Advance" button and press enter.
9. Tab till "Exclude Object Type" tab and press enter.
10.Tab till any cell and press enter to tick the tick-box.
11.Verify whether after selecting any record, with Ctrl+option+down arrow key focus is shifting to previous un-selected record in Exclude Object Type grid after and it skips all the selected records while navigating through the table cells or not.

### Actual Result:​
When voice over is on after selecting any record, with Ctrl+option+down arrow key focus is shifting to previous un-selected record in Exclude Object Type grid and it skips all the selected records while navigating through the table cells.
### Expected Result:​
When voice over is on after selecting any record, with Ctrl+option+down arrow key focus should shift to the next record and should not move to previous un-selected record in Exclude Object Type grid and it should not skip any selected record.
### User Impact:
Voiceover user will get confused if the meaningful sequence is not followed in the grid correctly after selecting any record and will not get the information about the selected record as it skips selected records.

### Attachment:
![advance publish_Meaningful sequence](https://user-images.githubusercontent.com/91586101/223469542-7d473a33-3788-4cf9-b3fa-05902a67e287.gif)

**Comment by kisantia** [comment]
@manaswita-chougule this has been fixed in the latest version of the sql database projects extension (0.23.0). Please download the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and verify this is fixed. Thanks!

**Comment by manaswita-chougule** [comment]
#Closed; #Regressed:03-31-23;
Verified the issue in below environment:
Application Name: SQL Azure Data Studio
Version: 1.43.0-insider (Universal)
MAC Version: macOS Ventura 13.3

The issue is fixed, hence closing the bug. Please find below attachment for reference. Thanks!

![22189_Fixed](https://user-images.githubusercontent.com/91586101/229084251-93d7b79d-4f9a-44b4-9483-c93399da0577.gif)
