### ISSUE TITLE
Group by Schema action icon changes size when toggled

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22208]
Doesn't look very polished like this, the icon itself should stay the same size with only the x being added/removed.

![SchemaIconResize](https://user-images.githubusercontent.com/28519865/223589484-7dcaf5f0-32ea-403a-9390-a4bc2efd01ea.gif)

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 @erinstellato-ms FYI

**Comment by alanrenmsft** [comment]
verified in latest rc1 build.
