### ISSUE TITLE
Missing Object Management menu item errors in console

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22207]
![image](https://user-images.githubusercontent.com/28519865/223588572-dd7d726c-b465-49fc-98c1-5dd58173d851.png)

**Comment by Charles-Gagnon** [comment]
@alanrenmsft @kburtram FYI

**Comment by alanrenmsft** [comment]
more information about the issue: the errors are complaining about the entries I added under the commandPalette menu contribution point to always hide these commands. no feature is broken because of this, but should be removed so that we don't have errors in the console.

@kenvanhyning
