### ISSUE TITLE
Expanding Paused database leads to breaking OE connection

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22211]
- Azure Data Studio Version: 1.42.0-rc1
- OS Version: Windows 11

Steps to Reproduce:

1. Create a connection to Azure SQL Server
2. Expand a paused database node.

Notice the error message contains entire stack-trace and OE connection is dropped.

![OE_PausedDB](https://user-images.githubusercontent.com/13396919/223595760-b1b45939-80f2-460b-96fa-57ca667504ae.gif)

Expected:
1. Error message dialog should only show error message and not entire stack trace.
2. OE connection to Azure Server should not get dropped.

**Comment by kburtram** [comment]
This sounds similar to https://github.com/microsoft/azuredatastudio/issues/22311.  Maybe this is already in the scope of what @smartguest is looking into?

**Comment by cheenamalhotra** [comment]
I think this bug is not just for Serverless DB, but in general for any exception that is thrown from OE nodes.
I also noticed this elsewhere, but generally when an exception occurs and error dialog popup shows, OE parent connection drops.
