### ISSUE TITLE
Causing High CPU

### ISSUE THREAD

**Issue by benlui** [microsoft/azuredatastudio#22216]
Type: <b>Bug</b>

Install extension, and restart VSCode. High CPU will be experienced.
By Extension Bisect, the extension is identified.

Extension version: 0.4.0
VS Code version: Code 1.76.0 (92da9481c0904c6adfe372c12da3b7748d74bdcb, 2023-03-01T10:22:44.506Z)
OS version: Windows_NT x64 10.0.19042
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.80GB (17.79GB free)|
|Process Argv|-n --crash-reporter-id d04d4299-dd5f-4c9b-82f9-6c45643e1fee|
|Screen Reader|no|
|VM|20%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242:30382549
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593:30376534
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30662994
nodejswelcome1cf:30587006
282f8724:30602487
pyind779:30671433
f6dab269:30613381
pythonsymbol12:30671437
vsccsb:30677849
vscodedisable:30660115
pythonms35cf:30676801

```

</details>

**Comment by Charles-Gagnon** [comment]
What extension? This repo is for Azure Data Studio - a completely separate product (not an extension). 

If this is about the [VS Code MSSQL extension](https://github.com/Microsoft/vscode-mssql) then 0.4.0 is an extremely out of date version - please update to the latest version of the extension and let us know if you continue to see any issues.
