### ISSUE TITLE
"mssql.enableSqlAuthenticationProvider" causing SQL Tools Service crash on macOS

### ISSUE THREAD

**Issue by bwyatt-mcr** [microsoft/azuredatastudio#22223]
Issue Type: <b>Bug</b>

I've enabled this setting as advised to fix/improve authentication stability with Azure databases, but enabling this on macOS causes SQL Tools to crash. A restart doesn't resolve. If I disable the new setting, the crashes stop.

Azure Data Studio version: azuredatastudio-insiders 1.43.0-insider (b4d5a08199e9e0cb0138ce540c086ac32d072019, 2023-03-07T06:29:50.721Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 14, 8|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @bwyatt-mcr 

The fix has been merged and is available in the latest insiders build.
Thanks again for bringing this to our attention! I will proceed to close the issue.
