### ISSUE TITLE
sql login password complexity check is different from the server's requirement.

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22231]
I tried to create a login on SQLTOOLS2019-3 with sql auth and enforce password policy on. it failed because the server's requirement is stricter than what we expected. according to https://learn.microsoft.com/en-us/sql/relational-databases/security/password-policy?view=sql-server-ver16, it is customizable.

We need to expose the inner exceptions so that it is clear to the user why it is failed, otherwise user will only get "create login failed".

meanwhile, need to investigate whether it is possible to get the actual complexity requirement from the server and then enforce it in the UI.

**Comment by caohai** [comment]
![image](https://user-images.githubusercontent.com/21186993/223823265-6fef725b-0c0e-4a47-9cff-8190d4f38605.png)
I tested on my local SQL Server (2019) and this appears to be the related windows password policy.
Let me debug the exception in STS to see if it contains the actual error msg.

**Comment by alanrenmsft** [comment]
it does, it says password is too short.

**Comment by caohai** [comment]
Followup issue https://github.com/microsoft/azuredatastudio/issues/22275
