### ISSUE TITLE
Validation Navigator for the import wizard should handle multiple functions at the same time

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#2223]
https://github.com/Microsoft/sqlopsstudio/blob/8daaa89d96f422198cd767ac87039fc32a56e66c/extensions/import/src/wizard/flatFileWizard.ts#L122-L124

The wizard's navigation validation can only be set to a specific callback at any given time. The method that handles the navigation validation should keep track of all of them per-page they're being called and have one navigation validation cached per page.

**Comment by kburtram** [comment]
Closing old tasks.  Please open as a bug against an extension if this is still needed.
