### ISSUE TITLE
not able to remove server role

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22234]
![remove-role](https://user-images.githubusercontent.com/13777222/223820615-7089d6f1-b25c-4ca3-9ea0-39a6a1ba8865.gif)

not able to reproduce with dev build on main branch.

**Comment by caohai** [comment]
@alanrenmsft 
This has been fixed by https://github.com/microsoft/sqltoolsservice/pull/1899 but I've no idea why it's no included in
https://github.com/microsoft/sqltoolsservice/commits/release/4.5 It appears all commits from 3/3 were not included, do you know when the cutoff happened?

**Comment by alanrenmsft** [comment]
you have to port it to the STS release branch. the cut off for STS is not friday it is whatever version is in ADS on cutoff day.
