### ISSUE TITLE
SQLOPS Studio gets stuck / takes too long and resource intensive on 1-Core Windows R2 2012 VM 

### ISSUE THREAD

**Issue by SQLDBASRI** [microsoft/azuredatastudio#2224]
- SQL Operations Studio Version: sqlops-windows-0.31.4

Steps to Reproduce: Logon to the SQL Server and run sqlops studio , it disconnects with the time out issue and also get stuck/hangs looks like very resource intensive too . Please find the screen shots compared to the SSMS (2014 ) and both are on Windows 2012 R2 running SQL Server 2014 , 1 CPU and dynamic allocated ram. Let me know if there is a min and max requirement for the CPU and memory for sqlops 
![connection time out](https://user-images.githubusercontent.com/37841222/44067243-8dbc7826-9f42-11e8-90e2-142ff6850737.PNG)
![resource intensive_li](https://user-images.githubusercontent.com/37841222/44067244-8dc81f96-9f42-11e8-9cf8-5b25248cc3d3.jpg)

**Comment by kburtram** [comment]
@SQLDBASRI we don't currently focus on perf for the 1-core scenario.  Generally we consider 4-core, 8GB RAM as a typical mid-range configuration.  We'll publish minimal recommended machine configurations in the future, but in the meantime I would recommend adding additional cores to your VM.

**Comment by SQLDBASRI** [comment]
I will try to update the cores and update the thread. Thanks @kburtram

**Comment by kburtram** [comment]
Closing older issues.  Please try to use a machine with at least 4-cores for best performance.  Thanks!
