### ISSUE TITLE
not able to create login with server role selected for Windows auth and AAD auth

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22245]
1. Connect to an on-prem server
2. Open new login dialog
3. Select windows auth and select a server role
4. fill out the form and click ok

the request will fail

same issue with AAD login. SQL Auth works fine.

**Comment by caohai** [comment]
Are you testing with RC build or main?

**Comment by alanrenmsft** [comment]
working fine with latest main now.
