### ISSUE TITLE
Latency and Hangs on SQL Server Connections

### ISSUE THREAD

**Issue by jroanstandards** [microsoft/azuredatastudio#22264]
Issue Type: <b>Performance Issue</b>

Extreme latency, lag, connection hangs when connecting to sql server.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 Microsoft Surface (R) Edition (16 x 1996)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.45GB (4.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   101	  6744	azuredatastudio main
    0	   101	  3564	   shared-process
    0	    82	  2168	     ptyHost
    0	     6	  5264	       console-window-host (Windows internal process)
    0	    80	 19800	       "C:\Program Files\PowerShell\7\pwsh.exe"
    0	    77	 29572	     fileWatcher
    0	    40	  5056	   utility-network-service
    0	   296	 10416	   window (● SQLQuery_2 - REDACTED (REDACTED) - SQL Queries - Azure Data Studio)
    0	   152	 12164	   gpu-process
    0	    89	 25220	   issue-reporter
    0	   140	 31276	   extensionHost
    0	    75	  5744	     "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\node\jsonServerMain" --node-ipc --clientProcessId=31276
    0	  1763	  6088	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\MicrosoftSqlToolsServiceLayer.exe" --locale en --log-file c:\Users\JacobRoan\AppData\Roaming\azuredatastudio\logs\20230309T101011\exthost1\Microsoft.mssql\sqltools.log --tracing-level Critical --autoflush-log
    0	    10	 24564	       console-window-host (Windows internal process)
    0	    37	 11112	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\SqlToolsResourceProviderService.exe" --locale en --log-file c:\Users\JacobRoan\AppData\Roaming\azuredatastudio\logs\20230309T101011\exthost1\Microsoft.mssql\resourceprovider.log --tracing-level Critical --autoflush-log
    0	    10	 21448	       console-window-host (Windows internal process)
    0	    36	 31508	     "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\4.4.1.5\MicrosoftSqlToolsCredentials.exe" --locale en --log-file c:\Users\JacobRoan\AppData\Roaming\azuredatastudio\logs\20230309T101011\exthost1\Microsoft.mssql\credentialstore.log --tracing-level Critical --autoflush-log
    0	    10	 16188	       console-window-host (Windows internal process)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (● SQLQuery_2 - REDACTED (REDACTED) - SQL Queries - Azure Data Studio)
|    Folder (SQL Queries): 25 files
|      File types: sql(25)
|      Conf files:;
```

</details>
<details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.12.0
import|Mic|1.5.4
profiler|Mic|0.12.2
query-history|Mic|0.5.3

</details>

**Comment by cheenamalhotra** [comment]
Hi @jroanstandards 

Could you please try out the latest insiders build and let us know if that helps improve connection performance as we've made some improvements in the area. Thanks!

**Comment by cheenamalhotra** [comment]
Closing issue as related issues are fixed in the latest insiders build.
