### ISSUE TITLE
Azure Data Studio is very slow on my mac

### ISSUE THREAD

**Issue by Bahar-Pasha** [microsoft/azuredatastudio#22263]
I recently installed Azure Data Studio on my mac and it works very slow, what should I do to address this issue?
- Azure Data Studio Version:1.41.2
- OS Version:13.1

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
@Bahar-Pasha does it help?

**Comment by Bahar-Pasha** [comment]
> @Bahar-Pasha are you using Mac with Apple Silicon and Intel version of Azure Data Studio? If so, please try the Apple Silicon version which will be much faster: https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release

I downloaded Apple Silicon Version 

> @Bahar-Pasha does it help?

I guess it is faster but I am new to SQL and need more time to work with it. Anyway, thanks for your help.

**Comment by Bahar-Pasha** [comment]
GO command does not work on my Azure data Studio , where should I define it in the setting so that it works ?

**Comment by alanrenmsft** [comment]
@Bahar-Pasha could you please elaborate a bit more? what do you mean by GO command not working?
