### ISSUE TITLE
Attempting to expand a Dataverse database folder throws an error 'Create Table' is not supported

### ISSUE THREAD

**Issue by mscottsewell** [microsoft/azuredatastudio#22272]
- Azure Data Studio Version:

Version: 1.43.0-insider (system setup)
Commit: 87defc0367ba40c43e8b9fe3f10996aa434f9056
Date: 2023-03-09T06:51:26.692Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Connect to a dataverse db
2. Expand the server / expand the list of Databases
3. (right click on the database name and you can query it successfully)
4. Click on the database name or try to expand it and it throws an error

```
Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch.
---> Microsoft.Data.SqlClient.SqlException (0x80131904): "'CREATE TABLE' statement​ is not supported. Line:2, Position:9"
RequestId: TDS;844c5c3a-6100-46ef-b2c5-3894c41e6cad;4
Time: 2023-03-09T17:59:37.8853945Z
at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)
ClientConnectionId:844c5c3a-6100-46ef-b2c5-3894c41e6cad
Error Number:40000,State:1,Class:16
```

Before attempting to expand my dataverseadl database:
![image](https://user-images.githubusercontent.com/6276300/224116044-13ec189a-1376-473f-b441-bf3e0eb3cbb0.png)

After clicking on it, this error is thrown:
![image](https://user-images.githubusercontent.com/6276300/224116154-ab7393f4-a76c-49ed-bc2b-df68b907085a.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by MohammadShalaby** [comment]
I have the same exact issue. 
Client Machine ........ Macbook Apple Silicon based - M1 Max
MacOS .................... MS Ventura 13.2.1
Azure Data Studio ... https://azuredatastudio-update.azurewebsites.net/latest/darwin-arm64/insider 

I can't neither expand tables under the Database (_same way I can on Microsoft SQL Management Studio_) nor Columns names/tables names appear when I start writing their names :( 

the error produced is sometime the large one illustrated in the issue description or the short one as per below screenshot

![image](https://user-images.githubusercontent.com/67863417/226687468-9e29b67c-9125-467c-bf34-e4ef7463b590.png)

**Comment by cheenamalhotra** [comment]
Closing since #22500 was fixed.
