### ISSUE TITLE
Error when trying to remove a project from the workspace

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#22278]
<img width="446" alt="image" src="https://user-images.githubusercontent.com/1609827/224145926-487b5105-0e7c-42f0-a43c-9dfc28a659c3.png">

Occurring in RC build with RC gallery versions of extensions, does not repro in main or `release/1.42`

**Comment by kisantia** [comment]
likely caused by this change made for sql database projects drag and drop support https://github.com/microsoft/azuredatastudio/pull/21956/files#diff-e874a6c9d2cf5d2086f01229b4facb771d82963a95353528f941e36e240af9eb that isn't being released this month
