### ISSUE TITLE
most of the database roles cannot be assigned to a user in Azure SQL DB

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22279]
![image](https://user-images.githubusercontent.com/13777222/224137949-15212950-cc3b-47ff-892a-ad6a8f04ed5a.png)

only `dbmanager` and `loginmanager` can be assigned. use of other database roles will cause the following error:
`Add member failed for DatabaseRole 'db_owner'. ---> An exception occurred while executing a Transact-SQL statement or batch. ---> Cannot alter the role 'db_owner', because it does not exist or you do not have permission.`

if this is by design, we may want to disable those options to avoid confusion.

**Comment by dzsquared** [comment]
https://learn.microsoft.com/en-us/azure/azure-sql/database/logins-create-manage?view=azuresql#using-fixed-and-custom-database-roles

**Comment by kburtram** [comment]
@alanrenmsft do you think STS should not include these roles in the list?  or that the UI should show then as unavailable/disabled?

**Comment by alanrenmsft** [comment]
@kburtram definitely should be handled in STS side.

**Comment by caohai** [comment]
@alanrenmsft Is the user you are testing with in `master` db? I can repro this issue with `master` db but have no issue with other dbs.
