### ISSUE TITLE
user dialog is displaying wrong information for existing users that do not have a login.

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#22280]
the user shown in the screenshot below is a user with no login, but it is displayed as user with login and updating user is not possible because the login is missing. 

![image](https://user-images.githubusercontent.com/13777222/224147328-53095e24-7fd5-4e7a-bdcf-2fcaefa09a3d.png)

trying to update the user:
![image](https://user-images.githubusercontent.com/13777222/224147737-9b647a1c-1a0e-4c96-8d01-30115607b8b3.png)

**Comment by kburtram** [comment]
Fix has been merged to release branch.
