### ISSUE TITLE
Schema Visualization 

### ISSUE THREAD

**Issue by Bahar-Pasha** [microsoft/azuredatastudio#22296]
- Azure Data Studio Version:
- OS Version:13.1
Hello, 
I've jus downloaded Scheme Visualization from https://github.com/R0tenur/visualization/releases/tag/v0.8.2, the zip file 
, but I don't know how to run it. would you please help me to do so. 

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
You should be downloading and installing the VSIX - instructions for doing that are here : https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16#install-from-a-vsix

Let us know if you encounter any issues with doing this!

**Comment by Bahar-Pasha** [comment]
> You should be downloading and installing the VSIX - instructions for doing that are here : https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/add-extensions?view=sql-server-ver16#install-from-a-vsix
> 
> Let us know if you encounter any issues with doing this!

I could install it and could see its logo but I could not run it by clicking on it :(

**Comment by Charles-Gagnon** [comment]
If you're having issues with the extension itself, please open a discussion/issue in their repo 
 - they should be able to help! 
 
 https://github.com/R0tenur/visualization
