### ISSUE TITLE
Remove tenant selection from UI as tenant Id is received from server with SQL Auth provider implementation.

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22298]

**Comment by Charles-Gagnon** [comment]
Would this potentially be related to https://github.com/microsoft/vscode-mssql/issues/17598?

**Comment by cheenamalhotra** [comment]
This is handled in VSCode-MSSQL, and there is no question prompt for tenant when this setting is enabled.
The tenant is received as part of [Authority](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlauthenticationparameters.authority?view=sqlclient-dotnet-standard-5.1#microsoft-data-sqlclient-sqlauthenticationparameters-authority) from server during Login flow.
