### ISSUE TITLE
mssql user settings need to be localized and capitalized correctly

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2230]
1. Entries in sqlopsstudio\extensions\mssql\package.json need to use localized references in sqlopsstudio\extensions\mssql\package.nls.json
2. Some descriptions like:
```
_"mssql.format.placeCommasBeforeNextStatement": {
          "type": "boolean",
          "description": "**should** commas be placed at the beginning of each statement in a list e.g. ', mycolumn2' instead of at the end e.g. 'mycolumn1,'",_
```
should be starting with capital letter and should be punctuated properly.

**Comment by kburtram** [comment]
Closing older issues.
