### ISSUE TITLE
Missing groupBySchema SVG errors

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22312]
- Azure Data Studio Version: `main`
- OS Version: `linux`

Steps to Reproduce:

1. Open ADS and connect to server. 
2. Hover over 

Expected: No errors

Actual:  Errors in below screenshot.  I assume this is likely breaking the inline command button for enable/disable group by schema.  The issue appears to be a mismatch in casing of the file and reference to the file in the source.

![image](https://user-images.githubusercontent.com/599935/224790823-ec2521b1-7bb2-4fc4-bcb9-0fa08f74aadb.png)

**Comment by kburtram** [comment]
Here's what the OE toolbar looks like on Linux with and without this fix.

![image](https://user-images.githubusercontent.com/599935/224845602-3cb88e28-861f-449a-9340-c199b03e899b.png)

and


![image](https://user-images.githubusercontent.com/599935/224827734-c83a9c87-2ffb-4d11-a66b-6583a0a8af8b.png)

**Comment by aasimkhan30** [comment]
Closing as the fix is in the release
