### ISSUE TITLE
"..error occured while loading Azure resources"

### ISSUE THREAD

**Issue by yooakim** [microsoft/azuredatastudio#22321]
Issue Type: <b>Bug</b>

- Log in with my Azure AD account
- Open Azure Datat Studio
- Add new connection, "Browse" the Azure AD Account
- The error says "An error occurred while loading Azure resources"
<img width="776" alt="Screenshot 2023-03-14 080124" src="https://user-images.githubusercontent.com/862546/224922559-ccef8f51-751b-4179-b783-97366c68fe15.png">
 
The underlying issue seems to be that request are throttled to the Azure back-end.

It would really be great if Azure Data Studio could be more clever in terms of caching results. I understand the API rate limit but the list of resources is not updated so often so it would make sense if Azure Data Studio could keep a local cache of this infromation to avoid hitting the rate limit API.

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900K (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.58GB (16.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by bwyatt-mcr** [comment]
@cheenamalhotra I'm just tagging you as can see you've sized this up etc. This error is now making ADS unusable for me in my case. After I've opened a few tables, I'm locked out due to throttling. I don't know how much this is affecting others but just letting you know my experience.

I'll probably try and disable the new authentication provider in the meantime...

**Comment by cheenamalhotra** [comment]
Hi @bwyatt-mcr 

You could navigate your resources without throttling when using Azure tree view.. does that work for you?

![image](https://user-images.githubusercontent.com/13396919/226975547-5c581c07-42c2-4e0d-8ec4-165723e73d1e.png)

**Comment by bwyatt-mcr** [comment]
> Hi @bwyatt-mcr
> 
> You could navigate your resources without throttling when using Azure tree view.. does that work for you interim?
> 
> ![image](https://user-images.githubusercontent.com/13396919/226975547-5c581c07-42c2-4e0d-8ec4-165723e73d1e.png)

Unfortunately not, as that's how I use it anyway, I expand Azure and seek the server, database and object I'm looking for. Works for a bit and then ultimately throttles me.

**Comment by cheenamalhotra** [comment]
I managed to reproduce the issue, it's separate than the issue above so I've opened a new issue #22403 to track the same.
Until then, you may disable 'MSSQL: Enable Sql Authentication Provider' if this prompt bothers a lot.

I will start investigations and try to get a fix asap.

**Comment by kburtram** [comment]
@cheenamalhotra do we have an understanding of this issue yet, before we ship stable release with 'MSSQL: Enable Sql Authentication Provider' on by default?

**Comment by cheenamalhotra** [comment]
This is a separate issue, still exists and is related to throttling of ARM requests when fetching resources from subscription.
