### ISSUE TITLE
Deselect the last selection of other table 

### ISSUE THREAD

**Issue by tanyaranjan** [microsoft/azuredatastudio#22332]
In case of multiple tables, unable to deselect the selection.
![image](https://user-images.githubusercontent.com/38867337/225267527-fc06895e-ec9e-4ab7-b67d-fee258a1b630.png)
We have created 4 tables in the above image but cannot deselect them.

**Comment by kburtram** [comment]
@tanyaranjan so I can understand the scenario better, why does the user want to unselect the items in the table?  Is the idea that the selections in these different tables are mutually exclusive?

**Comment by alanrenmsft** [comment]
@tanyaranjan could you please provide more information as Karl requested?

**Comment by tanyaranjan1995** [comment]
Hi @alanrenmsft / @kburtram 
Sorry for the delay in response.
Raised the same issue with my Microsoft id. Please have a look.
https://github.com/microsoft/azuredatastudio/issues/23022

**Comment by kburtram** [comment]
Closing as duplicate as suggested above.
