### ISSUE TITLE
'Properties' shows twice on right clicking user name

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22340]
- Azure Data Studio Version: Latest
- OS Version: Windows 11

Steps to Reproduce:

1. Login to on-premise SQL Server
2. Right click on username

Properties shows twice, the second one opens the SSMS-MIN dialog, while the new one opens the newly added User Management flow.

<img src="https://user-images.githubusercontent.com/13396919/225472977-dce75093-bfef-453b-a66c-5787adc49522.png" width=450/>

Was the second one supposed to be removed?

**Comment by Charles-Gagnon** [comment]
@alanrenmsft Was this something you were planning on addressing yourself, or should I be looking at removing it?

https://github.com/microsoft/azuredatastudio/pull/21981#discussion_r1110491296

Also - side note but you should probably move the current location in the menu. Properties options are generally at the bottom of menus like this.

**Comment by alanrenmsft** [comment]
I'll add a preview label to the new one so that it won't be confusing for those with SSMS-min installed.
