### ISSUE TITLE
Unchecking and rechecking options in properties can modify other values

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22348]
I happened to notice this for "Enforce Password Policy" but didn't go through all options so there might be more

Note that not only does it change the value of `User must change password at next login` but the dialog seems to think there's no actual changes (OK button is greyed out)

![LoginDialog](https://user-images.githubusercontent.com/28519865/225726453-b4d783ea-9fa9-4b60-8177-9a4b2cb8da91.gif)

**Comment by alanrenmsft** [comment]
these 3 fields are associated:
when enforce policy is false, these other 2 options will be unchecked and disabled.
when password expiration is false, the Must_Change option will be unchecked and disabled.

I tested with the latest build and changes to any of those fields will cause the dialog to become dirty, there is an issue with the scripting of the must change option which is being tracked by https://github.com/microsoft/azuredatastudio/issues/22857.
