### ISSUE TITLE
Unable to open Connect side window

### ISSUE THREAD

**Issue by kristinald** [microsoft/azuredatastudio#22358]
Issue Type: <b>Bug</b>

Multiple times, and multiple versions. when I need to change connection or use the connect button in a window, I'm not able to see the connection panel. It doesn't show up and even re-opening the application will not have it appear. I need to restart my computer, then sometimes it will show up. 

Steps:
Open query window, press connect (to the right of the run command button) and nothing happens.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.19044

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (7.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|0.2.6
import|Mic|1.5.4
powershell|ms-|2022.6.3
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
jupyter|ms-|2021.8.1046824664
azdata-sanddance|msr|3.3.0

</details>

**Comment by Charles-Gagnon** [comment]
@kristinald It looks like you're using an extremely old version of ADS. Could you please update to the latest and let us know if you're still seeing issues?
