### ISSUE TITLE
ModelViewPanel.registerContent handler should return promise

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2236]
Ran into this while writing tests over `registerContent` method. Every single implementation of the handler I've seen is async since it calls `await modelview.InitializeModel(...)`, but the handler says it returns void. This makes it hard to test easily, since you can't await the result of the call.

```

			export interface ModelViewPanel {
				/**
				 * Register model view content for the dialog.
				 * Doesn't do anything if model view is already registered
				 */
				registerContent(handler: (view: ModelView) => void): void;
```

should be:
```
				registerContent(handler: (view: ModelView) => void | Promise<void>): void;
```

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impacting an extension under active development.
