### ISSUE TITLE
Edit table - Commit row failed

### ISSUE THREAD

**Issue by organictx** [microsoft/azuredatastudio#22371]
Azure Data Studio Version:
Version: 1.41.2
Commit: 0f0960d0e774e1ce903b79378addff96117c27a6
Date: 2023-02-08T20:18:32.853Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin arm64 22.3.0

Steps to Reproduce:
Connect to SQL instance
R-click on a table -> Edit Data
Show SQL pane and edit statement
Edit an existing value or add a row -> Enter
Observe parser error: Commit row failed: Incorrect syntax near 'inserted'. <-- Note: error message varies depending on SQL statement and result set data

images:
<img width="369" alt="image" src="https://user-images.githubusercontent.com/128369846/226311038-416c2bc1-43ee-4096-bddb-64c801454487.png">
<img width="580" alt="image" src="https://user-images.githubusercontent.com/128369846/226311358-27944d82-1e19-44f9-8aea-1eecf5182237.png">
<img width="762" alt="Screenshot 2023-03-20 at 5 07 37 AM" src="https://user-images.githubusercontent.com/128369846/226311677-1ca7cb72-2d3e-4d0f-9f8d-588e37441fe5.png">
<img width="444" alt="Screenshot 2023-03-20 at 5 04 16 AM" src="https://user-images.githubusercontent.com/128369846/226311728-254f8e5a-0384-4b4a-b439-333e5b599ded.png">

**Comment by kburtram** [comment]
@smartguest do you have any ideas what's failing here or how best to diagnose this bug?

**Comment by smartguest** [comment]
@kburtram No idea currently, but from my testing, this does not happen.

 @organictx Please let me know if this happens in STS with its edit data feature or not as well. Thanks.

**Comment by organictx** [comment]
@smartguest I do not have access to SSMS that I know of. My OS: Darwin arm64 22.3.0 (Macbook Air M1)

**Comment by smartguest** [comment]
Understood, will attempt to try and reproduce this issue.

**Comment by smartguest** [comment]
From my testing so far, I am not able to reproduce this issue, when adding a new row on a shrunken display table, it is added to the end of the table no matter what, and also editing the existing row appears to work fine. On a table that has integer, varchar, varchar, varchar. columns. 

Can you please tell me what part of the query you changed (if this is the edit data query)? and what is the type of your table that you are editing/inserting into? @organictx

**Comment by kburtram** [comment]
I wonder if this could be related to the content being inserted?  Perhaps making the INSERT statement to be invalid SQL for some reason, like we are properly escaping content or something like that.  @organictx is there anything noteworthy about the content being inserted or is it simple text/numbers?

Also, could you please check the Developer Tools->Console to see if there are any exceptions being printed out there?  Thanks!

**Comment by organictx** [comment]
My original error is with update of an existing row and not with the insert of a new row. I am able to update a table row when SQL statement is select * from table. The table data is simple text/number/dates. I did not see any errors in the Console. When I change the 'select * from table' to select a subset of columns from the table is when I get the error updating a row on a varchar(1) column from _NULL_ to Y.

<img width="981" alt="image" src="https://user-images.githubusercontent.com/128369846/226465131-c4925f5e-85f6-4620-9715-79067471c94f.png">

**Comment by smartguest** [comment]
If you're attempting to edit a column that has multiple rows with NULL in it, it will not work even in SSMS, as we have no way to determine which row to alter if there are multiple null rows on a table (this is a limitation with MSSQL), but the error message for that should say the change would affect multiple rows, which is not what I'm seeing here.

**Comment by smartguest** [comment]
Also from what I'm reading about the error itself, it appears to have been documented here: https://powerusers.microsoft.com/t5/Using-Connectors/error-SQL-with-Insert-row-from-Excel-File-quot-incorrect-syntax/td-p/21950

With similar data in the table, perhaps it's a general SQL error that is not just limited to ADS

**Comment by smartguest** [comment]
Changing to varchar(1) did not result in any change to the results, nor did copying directly from Excel reproduce the issue

**Comment by smartguest** [comment]
@organictx Is this issue still persisting with the latest build or not? We have no further update on this issue.

**Comment by organictx** [comment]
I'm good. Thanks.
