### ISSUE TITLE
Notebook created from Azure is not running SQL code

### ISSUE THREAD

**Issue by sukkaur** [microsoft/azuredatastudio#22381]
Issue Type: <b>Bug</b>

I created a new notebook from Azure View by selecting my database. I created a code section and added select @@version. I got an error 
"Execution failed due to an unexpected error: can't connect to the database due to invalid OwnerUri
![image](https://user-images.githubusercontent.com/64991618/226473954-f07ce0cc-feb1-4f43-ac70-fae6d4166c0a.png)

Azure Data Studio version: azuredatastudio-rc1 1.42.0-rc1 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T05:30:07.825Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (1.54GB free)|
|Process Argv|--open-url -- azuredatastudio://openConnectionDialog/?server=sk-aw-server0602.database.windows.net&database=AdventureWorks0602&authenticationType=SqlLogin|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by corivera** [comment]
Was able to repro this. Looking into it.
