### ISSUE TITLE
Download

### ISSUE THREAD

**Issue by lowfitcorp1** [microsoft/azuredatastudio#22394]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kburtram** [comment]
@lowfitcorp1 unfortunately this issue does not contain enough information to provide any assistance.  Please additional details if you are still experiencing a problem with the Azure Data Studio download.  The release download links appear to be working properly at the moment.
