### ISSUE TITLE
Couldn't change the Kernel to Powershell

### ISSUE THREAD

**Issue by sukkaur** [microsoft/azuredatastudio#22391]
Issue Type: <b>Bug</b>

I opend a new Notebook - clicked on the dropdown next to Kernel and selected Powershell. It asked me to install the extension and asked to install python or select an existing python installation. I selected existing installation and hit install. I got a error "Failed to change Kernel. Kernel SQL will be used." Then I see a message saying "Another Python installation is currently in progress waiting for it to complete"
![image](https://user-images.githubusercontent.com/64991618/226722807-cab2c0b1-4e57-43b2-bfba-788d15b8cc61.png)

As the error said access issue so I thought I would install a new python and I got this message 
![image](https://user-images.githubusercontent.com/64991618/226724779-6b554c39-7ceb-4219-bfab-838c5a179745.png)

Azure Data Studio version: azuredatastudio 1.41.2 (0f0960d0e774e1ce903b79378addff96117c27a6, 2023-02-08T20:16:49.071Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.60GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by corivera** [comment]
Looks like that C:\Program Files\WindowsApps folder always needs Admin rights to open. I get an access denied error when trying to run that python.exe just from a terminal. Looks like there's a version of it under the user appdata directory that works, though. It's the one that runs when doing just "python3.11" from a terminal window.

**Comment by corivera** [comment]
Looks like the install flag not being cleared on error is a bug, though. I'll look into it. It'll at least get cleared when restarting ADS.
