### ISSUE TITLE
insert data other language(farsi)

### ISSUE THREAD

**Issue by hamidrasouli2951** [microsoft/azuredatastudio#22424]
Issue Type: <b>Bug</b>

Hi
At the time of entering information in Farsi language in INSERT Command in an unorderd way

Azure Data Studio version: azuredatastudio 1.34.0 (83a4316cf89cbf961a0f09a72c861379cfd01fa9, 2021-12-15T20:50:08.229Z)
OS version: Darwin x64 22.2.0
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
arc|Mic|0.11.0
azcli|Mic|0.3.0
azuredatastudio-postgresql|Mic|0.2.7
dacpac|Mic|1.13.0
import|Mic|1.5.4
profiler|Mic|0.12.2
schema-compare|Mic|1.12.0
sql-database-projects|Mic|0.14.1
azdata-sanddance|msr|4.0.3
sql-prompt|Red|0.2.11

(1 theme extensions excluded)

</details>

**Comment by hamidrasouli2951** [comment]
![Image 3-23-23 at 20 36](https://user-images.githubusercontent.com/101826308/227280869-456d4792-0a38-4a55-8bb4-6756703d6790.jpeg)

**Comment by kburtram** [comment]
@hamidrasouli2951 thanks for opening this issue.  I'm not able to see in the screenshot the bug your pointing out.  It looks like there is an unexpected `N'` before the integers in the second column and no trailing `'` in the final string column.  But I'm not sure what you're trying to do.

**Comment by cheenamalhotra** [comment]
@hamidrasouli2951 

Gentle reminder, we're waiting for your response.

**Comment by cheenamalhotra** [comment]
Closing as not enough information available to investigate issue.
