### ISSUE TITLE
Cannot Export Query Results with Postgres connection on Apple M1

### ISSUE THREAD

**Issue by sherman-disruhpt** [microsoft/azuredatastudio#22441]
Issue Type: <b>Bug</b>

1. On Apple M1 Max Chip, open Azure Data Studio using Rosetta
2. Install PostgreSQL extension for Azure Data Studio
3. Create Jupyter Book and add a sql query to run
4. Run the sql query with a Postgres connection
5. Try to export results in json, markdown, xml, excel, etc

Outcome:
Failed to save results. Could not find a serialization provider with the specified ID 'PGSQL'

Azure Data Studio version: azuredatastudio 1.42.0 (Universal) (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:04:34.407Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 5, 4|
|Memory (System)|64.00GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7

</details>

[vscode-app-1679671057776.log](https://github.com/microsoft/azuredatastudio/files/11063943/vscode-app-1679671057776.log)

**Comment by kburtram** [comment]
@alanrenmsft do you think this could be related to any of the Apple M1 changes in 1.42?

**Comment by alanrenmsft** [comment]
@sherman-disruhpt if you are using the Intel version of ADS, then the PGSQL extension would work, but if you use Universal or Apple Sillicon version it won't work, it is being tracked by: https://github.com/microsoft/azuredatastudio-postgresql/issues/349

**Comment by alanrenmsft** [comment]
@nitishsharma25 I think you ran into a similar problem, after looking into the issue, I think you guys shouldn't need to implement this provider and we can leverage the MSSQL provider to do the job because serialization a given set of data is database engine agnostic.

**Comment by alanrenmsft** [comment]
@sherman-disruhpt the fix is merged and will be shipped in the upcoming release.
