### ISSUE TITLE
Remember Password Field always marked but my database have no password

### ISSUE THREAD

**Issue by jmhasan** [microsoft/azuredatastudio#22459]
- Azure Data Studio Version: 
Version: 1.42.0 (user setup)
Commit: 22f384e569bc90d8b3231cc8c8cff99ea16c5052
Date: 2023-03-17T18:15:48.982Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19045
- OS Version: Windows 10 Pro 22H2

Steps to Reproduce:

Remember Password Field always marked but my database have no password, 
and when i write query no suggestion show of table field

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cheenamalhotra** [comment]
Hi @jmhasan 

It's possible you've reached limit of saved passwords in Windows Credential Manager created by Azure Data Studio (related to #20990), please try removing any "Microsoft|SqlTools" prefixed credentials that don't apply anymore and connect with 'Remember Password' checked again.

**Comment by cheenamalhotra** [comment]
Realizing this is likely similar request as #22773 
@jmhasan Could you please try with the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if this issue is resolved for you?

**Comment by cheenamalhotra** [comment]
Closing as issue is fixed and released with 1.44 release.
