### ISSUE TITLE
Database build is failing using the SQL Database Projects extension

### ISSUE THREAD

**Issue by jcbendernh** [microsoft/azuredatastudio#22467]
Version: 1.42.0 (system setup)
Commit: 22f384e569bc90d8b3231cc8c8cff99ea16c5052
Date: 2023-03-17T18:15:48.982Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
Windows Version - Windows 11 Enterprise - 22H2

Steps to Reproduce:

1.  RMB on the SQL Database Project
2.  Select BUILD

Does this issue occur when all extensions are disabled?: Yes/No

This is the error from OUTPUT in Azure Data Studio.

	[ Build ]
    > "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Install\\SQL\\SQLMIgration\\WideWorldImporters\\WideWorldImporters.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\jobender\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.21.0\\BuildDirectory"
    stdout: MSBuild version 17.4.1+fedecea9d for .NET
    stdout: 
    stdout: c:\Install\SQL\SQLMIgration\WideWorldImporters\WideWorldImporters.sqlproj : error : Unable to find package Microsoft.Build.Sql. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
    stdout: 
    stdout: c:\Install\SQL\SQLMIgration\WideWorldImporters\WideWorldImporters.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.7-preview' specified could not be found.
    stdout: 
    stdout: 
    stdout: Build FAILED.
    stdout: 
    stdout: c:\Install\SQL\SQLMIgration\WideWorldImporters\WideWorldImporters.sqlproj : error : Unable to find package Microsoft.Build.Sql. No packages exist with this id in source(s): Microsoft Visual Studio Offline Packages
    stdout: c:\Install\SQL\SQLMIgration\WideWorldImporters\WideWorldImporters.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.7-preview' specified could not be found.
    stdout:     0 Warning(s)
    stdout: 
    stdout:     2 Error(s)
    stdout: 
    stdout: Time Elapsed 00:00:00.43
    stdout: 
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Install\\SQL\\SQLMIgration\\WideWorldImporters\\WideWorldImporters.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\jobender\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.21.0\\BuildDirectory"    … exited with code: 1
	>>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Install\\SQL\\SQLMIgration\\WideWorldImporters\\WideWorldImporters.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\jobender\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-0.21.0\\BuildDirectory"   … errored out: Process exited with code 1

**Comment by kisantia** [comment]
Can you try running `dotnet nuget list source` and make sure nuget.org is listed? If it isn't, please try adding it as mentioned in this comment: https://github.com/microsoft/azuredatastudio/issues/20240#issuecomment-1227478333

**Comment by jcbendernh** [comment]
Performing the `dotnet nuget add source https://api.nuget.org/v3/index.json -n nuget.org` command resolved the issue.  Thanks!
