### ISSUE TITLE
GO command in SQL

### ISSUE THREAD

**Issue by Bahar-Pasha** [microsoft/azuredatastudio#22461]
GO command doesn't work in Data Azure Studio , Where should I define it in the setting so that it works?

**Comment by alanrenmsft** [comment]
@Bahar-Pasha Please add repro steps so that we know what you are trying to do.

**Comment by kburtram** [comment]
The GO command appears to working as a batch separator and a batch loop operator.  Please let us know which functionality is not working correctly if you are still impacted by this issue.

![image](https://user-images.githubusercontent.com/599935/230135359-ff7371c7-2e3c-4b62-811b-7694e4cb9604.png)
