### ISSUE TITLE
Adding a new connection requires a password

### ISSUE THREAD

**Issue by PublicV0id** [microsoft/azuredatastudio#22496]
Issue Type: <b>Bug</b>

I have a lot of test databases that don't have a password and the issue i'm facing is that now it throws an error even if when adding a new connection choosing "connection string" with an empty password

Azure Data Studio version: azuredatastudio 1.42.0 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:15:48.982Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.80GB (2.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuremonitor|Mic|0.1.9
dacpac|Mic|1.13.0
import|Mic|1.5.4
net-6-runtime|Mic|1.1.0
profiler|Mic|0.12.2
query-history|Mic|0.5.3

</details>

**Comment by Charles-Gagnon** [comment]
@PublicV0id If I'm reading this correctly, it seems you were trying to connect with an empty password. This should be addressed by https://github.com/microsoft/sqltoolsservice/pull/2021, would you be able to try out the latest [insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) build and see if it resolves your issue?

**Comment by kburtram** [comment]
Closing based on the above comment.  Please let us know if this isn't resolved in the current insiders build or the next stable release.
