### ISSUE TITLE
Opening a read-only source (Dataverse) throws an error that it can't create a table

### ISSUE THREAD

**Issue by mscottsewell** [microsoft/azuredatastudio#22500]
Issue Type: <b>Bug</b>

1) Connect to Dataverse
2) Attempt to expand the 'database' to view the tables
![image](https://user-images.githubusercontent.com/6276300/228359328-efeecc1b-0c5e-4723-93f0-892d4ce81ec0.png)

3) Boom! Error
![image](https://user-images.githubusercontent.com/6276300/228359510-847311d3-a828-4e6a-a31c-3f023f061798.png)

Microsoft.SqlServer.Management.Common.ExecutionFailureException: An exception occurred while executing a Transact-SQL statement or batch.
---> Microsoft.Data.SqlClient.SqlException (0x80131904): "'CREATE TABLE' statement​ is not supported. Line:2, Position:9"
at Microsoft.SqlServer.Management.Common.ConnectionManager.ExecuteTSql(ExecuteTSqlAction action, Object execObject, DataSet fillDataSet, Boolean catchException)
at Microsoft.SqlServer.Management.Common.ServerConnection.GetExecuteReader(SqlCommand command)

Azure Data Studio version: azuredatastudio-insiders 1.43.0-insider (e15b612166aad66ed7b0048b6763e16f45989d53, 2023-03-28T05:30:23.682Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (22.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@aasimkhan30 can we investigate if there's something we can do in April to fix?  Or at least understand why this is happening.

**Comment by kburtram** [comment]
The fix has been merged into release branch.
