### ISSUE TITLE
ADS telemetry is not capturing 'Provider' name

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22502]
Discussed internally with the team, the 'provider' name is not available in the connection telemetry data for all providers and all data is mapping to 'BLANK' provider.

Issue started with ADS Version: 1.42.0 (stable)

cc @alanrenmsft @Charles-Gagnon

**Comment by alanrenmsft** [comment]
this should be put under Connection area, right?

**Comment by Charles-Gagnon** [comment]
Fixed it, I changed the name of the property in https://github.com/microsoft/azuredatastudio/pull/22112 - so the report just needed to be updated.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon does it mean the report can only work with either versions prior to 1.42 or after 1.42?

**Comment by Charles-Gagnon** [comment]
No, I fixed it so that it'll pull from whichever name is used for each event for the provider column.
