### ISSUE TITLE
Double clicking column headers to auto-resize width resets scroll position to the top

### ISSUE THREAD

**Issue by JFitzMan** [microsoft/azuredatastudio#2251]
- SQL Operations Studio Version: 0.32.4

Steps to Reproduce: 
1 - Run a query that returns more rows than can fit into the result grid without scrolling
2 - Scroll down and double click on a column header to auto-resize column width to width of data. The scroll position will reset to the top, and the column will be auto-resized based on the data at the top.

It would be ideal to be able to auto-resize columns using data currently in view rather than always resetting the scroll position and using the top rows returned.

**Comment by jvincent-siplay** [comment]
> column will be auto-resized based on the data at the top
I've seen this too, resizing only takes the visible data into account. If there are longer values scrolled out of view then auto-resizing doesn't size the columns wide enough.

**Comment by alanrenmsft** [comment]
I don't know whether it is really double clicking the header, at least now to auto resize the column, you have to double click the column divider. and it does resize the column width, but as mentioned by @JFitzMan , the view will be scrolled to the top, and there also seems to be a max column width. in the screenshot below, the highlighted cells are not fully expanded:
![image](https://user-images.githubusercontent.com/13777222/59981192-fb0b8980-95b4-11e9-95ab-0129699b8c54.png)

**Comment by peterlukerow** [comment]
For me double-clicking column header divider does nothing, but of course it should expand the column to fit max content width.

**Comment by smartguest** [comment]
The issue with the resizing is that Autoresizecolumn plugin no longer works with double clicking as it uses outdated HTML elements that do not fire when a double click is made on the grid, it needs to be rewritten to handle that.

For the issue of scrolling, what happens is that when the header is clicked, the grid automatically scrolls to the top (slick.grid does this on its own) and it registered as scrolled, to fix this and restore the scroll state to the desired position, scroll must be marked as false when double clicking the header.

**Comment by smartguest** [comment]
Already fixed by pull
