### ISSUE TITLE
SQL Proj name validation message incorrect

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22523]
In the name validation for a new SQL Project if you type in `/` or `\` alone then it shows up with this error message even though there's non-whitespace characters there.

![image](https://user-images.githubusercontent.com/28519865/228676431-aaec583c-127a-46dd-94a7-0ef914bb0467.png)

**Comment by Benjin** [comment]
Tacking onto this one, it seems the error box flits through a few different messages, resulting in a barely-perceptible "jump"

![image](https://user-images.githubusercontent.com/1609827/228678256-7d1dc11b-17ca-48f3-b542-4b652bff5a8a.png)
![image](https://user-images.githubusercontent.com/1609827/228678281-37be7c96-cf1f-4ef1-90ac-da33bf4a510b.png)
![image](https://user-images.githubusercontent.com/1609827/228678310-4c054350-7433-426b-89a6-e9cb353c7244.png)
