### ISSUE TITLE
Publish Project/SQLCMD Variables: Reload values from project doesn't reload values

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#22526]
I'm a bit confused around this functionality. When I click the following button:

<img width="240" alt="image" src="https://user-images.githubusercontent.com/40371649/228678096-6f678c8e-f905-4d5f-ae8e-43145b718e05.png">

Nothing is reloaded if the variable is changed from outside of ADS (e.g. editing the .sqlproj in vscode) - this feels like a bug to me.

If I go and edit the value of the variable in ADS, I need to close the dialog, edit the value, then reopen the dialog (and the value is updated as expected).

Is there another scenario that I'm missing here?

**Comment by kisantia** [comment]
The reload sqlcmd variables button was meant for if you change the value in the publish dialog, then decide you want to reload the values from the project instead, not for reloading after the .sqlproj is manually edited while the dialog is open.

**Comment by Benjin** [comment]
Maybe the string should be "reset values"?

@chlafreniere does raise a good point, about detecting changes that happen to the project outside of ADS.  We have some ideas for that sorta thing in the DacFx library in an ADO task, but the idea needs a little more fleshing out and might make 1.1.

**Comment by Benjin** [comment]
Proposal:
disable button if the values haven't been changed

Less important, but consider: "reset" or "revert" as the verb
