### ISSUE TITLE
Row count column isn't wide enough, can't be resized

### ISSUE THREAD

**Issue by JFitzMan** [Microsoft/azuredatastudio#2252]
- SQL Operations Studio Version: 0.32.4

Steps to Reproduce:
Run any query that returns more than 9 results

The row count column isn't wide enough to display more than 1 digit, and this column is not able to be resized.

![count not visible](https://user-images.githubusercontent.com/10967207/44285437-2ba6c800-a21a-11e8-9d9e-f0e5d769d63a.PNG)

**Comment by kburtram** [comment]
Hmm, I'm not able to repro this.  @anthonydresser any ideas what could be happening?  It looks like the column is being auto-sized correctly for me.

![screen](https://user-images.githubusercontent.com/599935/44289580-cbb81d80-a229-11e8-9eb4-bcb8741f07b4.png)

**Comment by anthonydresser** [comment]
It probably only happens when you have exactly 10 rows. It is probably because of #2232 @alanrenmsft can you address

**Comment by JFitzMan** [comment]
Further testing looks like it happens with anywhere between 10 and 99 rows. 100+ works fine
![test1](https://user-images.githubusercontent.com/10967207/44290434-8d246200-a22d-11e8-86ad-c5b576a975df.PNG)
![test2](https://user-images.githubusercontent.com/10967207/44290438-8eee2580-a22d-11e8-88f4-81974f45c4ee.PNG)

**Comment by anthonydresser** [comment]
Alright, I'll revamp the calculations for the row width. @alanrenmsft I'll handle it.

**Comment by kburtram** [comment]
FWIW, I still couldn't repro with a query returning between 10 and 99 rows (e.g. `SELECT TOP 50 * FROM sys.all_objects;`).

**Comment by zeekbrown** [comment]
I just upgraded to SQL Operations Studio Version 0.32.8 (Commit efd470b3c771ef7473ba3cf108a33b6579c96a53) and have this problem as well with results between 10 and 99 rows. I had not had this issue prior to the upgrade.
