### ISSUE TITLE
Opening Legacy style project is not showing up when we lose a scope of update project notification.

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#22528]
- Azure Data Studio Version: 1.43.0-insiders
- OS Version: Windows 11
- SQL Projects version: v0.23.0

Steps to Reproduce:

1. Create a VS legacy style SQL Project in visual studio.
2. In ADS, click on open existing projects and select the created legacy project created in step-1.
3. A popup will appear "Do you want to update the project?" (Image-1)
4. Wait for a few seconds till the popup disappears.
5. Reload button on top left corner should do something to get the half-loaded project. (Image -2)
6. Try to re-open by doing step-2, new notification pops up (Image-3)
7. Once I'm at this state, loading any projects not showing up in the projects tab, have to restart the ADS instance.

Images-1:
![image](https://user-images.githubusercontent.com/74571829/228678984-5a5fa2fa-1442-4711-afcf-e57524a0ed18.png)

Image-2
![image](https://user-images.githubusercontent.com/74571829/228679415-fbeb1cdd-658d-4c22-9073-531c7890c8e4.png)

Image-3:
![image](https://user-images.githubusercontent.com/74571829/228679146-41bc32a3-98e3-478e-a4e3-b2790cca0ad6.png)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Benjin** [comment]
Three issues to split into:
1. Prompt to update goes away after a few seconds
2. If you don't update the project, it doesn't show up in the tree (but it should)
3. If the user rejects updating the project then tries building or publishing, they should be prompted to update again.

**Comment by Benjin** [comment]
Closing this, as it's been split into its constituent issues.
