### ISSUE TITLE
SQL Project tree doesn't refresh after update from database

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22532]
1. Create empty sql project
2. Go through "update from database" flow

Expected: Project tree refreshes after completion, showing the new files added

Actual: Nothing appears until you refresh the view

Note - this might be related to https://github.com/microsoft/azuredatastudio/issues/22531, since I'm hitting that every time I try and go through this flow.

**Comment by kisantia** [comment]
can't repro this in main anymore, so likely also fixed by https://github.com/microsoft/azuredatastudio/pull/22534, which fixed the related issue mentioned above
