### ISSUE TITLE
Error applying schema compare changes to sqlproj

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22531]
1. Create new sqlproj
2. Select "Update project from database"
3. Select local DB and select "apply changes"

This error appears

`Error: No script found at 'c:\c:\Users\chgagnon\Desktop\testproject\az_func\Tables\GlobalState.sql'`

Note how there's two `c:\` at the start.

The files seem to be created correctly though (although I have to refresh the project first)

![image](https://user-images.githubusercontent.com/28519865/228686086-334b3cf6-bbc6-4fbc-a4de-fd0400fc1f26.png)

**Comment by kisantia** [comment]
looks similar to https://github.com/microsoft/azuredatastudio/issues/22522

**Comment by kisantia** [comment]
This issue was also fixed by https://github.com/microsoft/azuredatastudio/pull/22534
