### ISSUE TITLE
Azure Data Studio on Mac Just Spins but Works on Windows

### ISSUE THREAD

**Issue by Oury-MSFT** [microsoft/azuredatastudio#22537]
-All latest versions on Mac fail to connect with a new or edited connection, but the latest Windows version works fine.

The most recent installed on local laptop that fails is: 1.42.0 (Universal)

ADS in Windows connects immediately with the same connection string and settings.

The behavior is it just spins when trying to connect to my database on a new or edited connection. When trying to connect to an existing/cached connection that normally works, it just spins, but closing the app and restarting allows for an existing connection to succeed. Trying to create a new connection, or editing a connection gets me spinning again, until I close the app.

I see no errors, just spinning - viewing all views in the OUTPUT tab.

Question: What can I do to see why it spins?

Version: 1.42.0 (Universal)
Commit: 22f384e569bc90d8b3231cc8c8cff99ea16c5052
Date: 2023-03-17T18:04:34.407Z (1 wk ago)
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Darwin x64 22.3.0

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
@cheenamalhotra and @aasimkhan30 I couldn't tell whether this is a connection or object explorer issue, could you please take a look at the issue?

**Comment by cheenamalhotra** [comment]
@Oury-MSFT 

Please feel free to close the issue if issue is resolved, or let us know if you need additional support.

**Comment by cheenamalhotra** [comment]
Closing as discussed internally.
