### ISSUE TITLE
Publishing changes via the table designer disables DDL triggers

### ISSUE THREAD

**Issue by richardtallent-erm** [microsoft/azuredatastudio#22546]
- Azure Data Studio Version: 1.42.0
- OS Version: Windows 10

We have a DDL trigger that logs all ALTER/CREATE/etc. statements for our dev database.

However, when a developer makes a change via the Table Designer in ADS (the "Update Database" button), the script that is generated and run by ADS contains a `DISABLE TRIGGER ALL ON DATABASE` before the generated statement(s), and an `ENABLE TRIGGER ALL ON DATABASE` statement afterward.

I was hoping to find a setting available to prevent this, but I can't find anything like that.

I'm not quite following the code, but this appears to be an issue with the `mssql` extension and how it calls `sqltoolservice`?

Steps to Reproduce:

1. Add a DDL trigger to a database (`CREATE TRIGGER tr_db_ddl ON DATABASE FOR CREATE_TABLE AS PRINT 'Table created!';`
2. In the Object Explorer for the database, right-click on Tables and choose New Table.
3. Click the "Publish Changes" button at the top.
4. Choose Generate Script.
5. Around line 41, you'll see `DISABLE TRIGGER ALL ON DATABASE`

Desired state:

Some optional setting in `settings.json` (perhaps `mssql.tabledesigner.deploymentOptions`?) that would pass the options to the tool that actually generates the script, so we can add a `disableAndReenableDdlTriggers` option (or whatever it should be called) to ensure our DDL triggers are not subverted by the SQL code generated.

Does this issue occur when all extensions are disabled?: Yes

**Comment by caohai** [comment]
@richardtallent-erm Thanks for reporting this. I can confirm the behavior and it's currently by design. 

Just want to make sure I understand the request correctly, are you saying you want to have an option to disable this re-enable mechanism so that the trigger can capture what happened (in this case a new table is created) between the disabling and enabling steps? 

I'll need to discuss with the team and see what we can do.

**Comment by richardtallent-erm** [comment]
Correct.

I can see why one might disable DDL triggers for generating a standalone script.

But when using "Update Database" button directly, doing this subverts database-level logic the DBA has put in place. Often, this is by the most junior developers (the ones using Table Designer over T-SQL). And these are probably the folks whose changes you *most* want to validate or log using a trigger. :)

In our case, we have junior devs changing the schema of a dev environment database. They're *supposed* to log *all* changes for review and migration to other environments, but sometimes they forget, especially the ones who rely more on Table Designer.

So we're trying to use a DDL trigger to ensure that all changes are logged.

**Comment by caohai** [comment]
> Correct.
> 
> I can see why one might disable DDL triggers for generating a standalone script.
> 
> But when using "Update Database" button directly, doing this subverts database-level logic the DBA has put in place. Often, this is by the most junior developers (the ones using Table Designer over T-SQL). And these are probably the folks whose changes you _most_ want to validate or log using a trigger. :)
> 
> In our case, we have junior devs changing the schema of a dev environment database. They're _supposed_ to log _all_ changes for review and migration to other environments, but sometimes they forget, especially the ones who rely more on Table Designer.
> 
> So we're trying to use a DDL trigger to ensure that all changes are logged.

Makes sense. I'm working on a fix and will discuss with the team. We'll let you know once we have the change in `main`.

**Comment by caohai** [comment]
Hi @richardtallent-erm , I've merged a PR which adds a config setting for the trigger behavior in table designer. This change will be included in tomorrow's Insider build and you can try it out with that or wait for the next official release in July.

**Comment by richardtallent-erm** [comment]
Thanks! I'll pass the info along to that team.
