### ISSUE TITLE
SQL Server Import extension available in azure data studio unable to import csv file data into mysql database on M1 chip Mac

### ISSUE THREAD

**Issue by preetamBetaVersion** [microsoft/azuredatastudio#22542]
- Azure Data Studio Version: 1.41.2
- OS Version: Ventura 13.1

Steps to Reproduce:

1. 
<img width="1105" alt="Screenshot 2023-03-30 at 5 22 19 PM" src="https://user-images.githubusercontent.com/59973313/228827644-350d2539-0484-4f4f-9bf2-85731268fe9e.png">

2.

Does this issue occur when all extensions are disabled?: Yes/No
No

**Comment by kburtram** [comment]
@preetamBetaVersion the SQL Server Import extension only currently supports SQL Server.  Please open a feature request for the MySQL extension to add support for this scenario at https://github.com/microsoft/azuredatastudio-mysql.  Each data source extension would need to implement the support for this functionality.
