### ISSUE TITLE
Accessibility Internals window too small on hi-res display

### ISSUE THREAD

**Issue by bciesielski** [microsoft/azuredatastudio#2259]
Minor bug

- SQL Operations Studio Version:
Version 0.32.5-insider
Commit d10e08e63ec26830efbcd070175ed935c36031f7
Date 2018-08-17T00:57:43.255Z
VS Code 1.23.1
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Help -> Accessibility Options 
Window is too small on a 4k display. Also the window title differs from the menu option name.

![image](https://user-images.githubusercontent.com/36210825/44302866-f42b3f00-a331-11e8-8ddc-f706ff1b4794.png)

Display settings
![image](https://user-images.githubusercontent.com/36210825/44302884-48ceba00-a332-11e8-8e3e-cc3279879952.png)

**Comment by kburtram** [comment]
This UI is coming from upstream dependencies.  I think this may be coming from Chromium.  We would prefer to see this addressed upstream and we'll pick it up as we refresh dependencies.  Thanks for opening this bug!
