### ISSUE TITLE
Error trying to script procedure to create/alter

### ISSUE THREAD

**Issue by DellyIan** [microsoft/azuredatastudio#22605]
Issue Type: <b>Bug</b>

When trying to script a procedure to create/alter keeping getting error after being logged in for a period of time:
An error occurred while scripting the objects. Failed to connect to server sql-dfy-uks-sl01.database.windows.net,1433.

Microsoft.SqlServer.Management.Common.ConnectionFailureException: Failed to connect to server sql-dfy-uks-sl01.database.windows.net,1433.
 ---> Microsoft.Data.SqlClient.SqlException (0x80131904): Login failed for user '<token-identified principal>'. Token is expired.
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)

D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Scripting\ScriptAsScriptingOperation.cs:line 86

Azure Data Studio version: azuredatastudio 1.42.0 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:15:48.982Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10510U CPU @ 1.80GHz (8 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.76GB (4.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.4
profiler|Mic|0.12.2

</details>

**Comment by aasimkhan30** [comment]
@cheenamalhotra is this a connection issue.

**Comment by cheenamalhotra** [comment]
Hi @DellyIan 

The issue can be resolved by enabling 'mssql:enableSqlAuthenticationProvider' setting - it's currently in preview, but can be enabled manually to resolve token expiry issues if they cause concerns in daily operations.

**Comment by cheenamalhotra** [comment]
Closing as issue has now been resolved with May release.
