### ISSUE TITLE
ADS - recent changes to RestClient are failing Post and Put calls w/ "Content-Length" undefined

### ISSUE THREAD

**Issue by brian-harris** [microsoft/azuredatastudio#22606]
- Azure Data Studio Version:  (build and debug latest code from main as of 4/3/2023)
- OS Version: Windows 11

Steps to Reproduce:
1. Launch ads
2. run SQL-Migration extension migration wizard
3. select any database, and SQL DB target to ensure ValidateIR is a required step in database configuration
4. run ValidateIR and notice the following console error:
![image](https://user-images.githubusercontent.com/61598682/229837636-ac516122-1baa-4b94-8c87-444974ab1534.png)

Does this issue occur when all extensions are disabled?: n/a

**Comment by kburtram** [comment]
We reverted the underlying change that introduced this regression in the April release branch and will do a proper fix in main.  @cssuh please confirm you've verified the migration scenario described in this bug is now working as expected in the April release build after the revert has been merged.
