### ISSUE TITLE
SQL Agent > Create operator - bugs/improvements

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/azuredatastudio#2260]
- SQL Operations Studio Version:
Version 0.32.5-insider
Commit d10e08e63ec26830efbcd070175ed935c36031f7
Date 2018-08-17T00:57:43.255Z
VS Code 1.23.1
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

4k display if it matters.

Bugs:
1. Ok / Cancel buttons missing
2. "Schedule" misspelled in "Pager on duty schdule"
![image](https://user-images.githubusercontent.com/36210825/44303122-f47b0880-a338-11e8-9d5e-fc3d0bf88f23.png)

Additional suggestions:
3. standardize font sizes (checkboxes seem to have smaller font sizes, Workday begin/end are larger and seem equally large as the "Pager on duty schedule" header)
4. could not find a way to switch between 12h/24h time format in Workday begin/end
5. maybe change font color a bit to improve readability (headers white, labels light gray in dark theme? disabled combo has white background and an active combo has black background - that does not look intuitive either in my opinion)

**Comment by kburtram** [comment]
@bciesielski thanks for opening this bug.  The SQL Agent configuration dialogs are still in "early preview" state and have several known bugs we'll be fixing.
