### ISSUE TITLE
Create project from database UI doesn't populate databases if not started from database context

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#22616]
When you connect to a server with no database specified (Database: `<default>`), then calls to `azdata.connection.listDatabases(connectionId)` only returns `[master].

If you connect to a server with a specific database selected (master, any user db) then `listDatbases()` returns correct info.

This appears to be consistent across everywhere data developer extensions call this API (all of Schema Compare, SQL Database Projects, Dacpac extensions).

**Comment by SakshiS-harma** [comment]
Can't repro.

**Comment by Benjin** [comment]
I'm hitting this today, on the latest version of ADS RC.  Will investigate to find more info

**Comment by SakshiS-harma** [comment]
The database populates when the server is connected to master database, but with default it doesn't.

**Comment by alanrenmsft** [comment]
I debugged and turns out it didn't even send request to STS, the isConnected in line 1580 is returning false. File name:  src\sql\workbench\services\connection\browser\connectionManagementService.ts

![image](https://user-images.githubusercontent.com/13777222/230225069-1230e8c1-e36a-482d-a19e-0eb6fb5ccc38.png)

**Comment by alanrenmsft** [comment]
repro steps:

![error-repro](https://user-images.githubusercontent.com/13777222/230225477-5aae711f-3009-4457-bb54-e2d5a14c8204.gif)

**Comment by cheenamalhotra** [comment]
This is related with changes from #22511. 
@aasimkhan30 do you have an idea why double click would not set the default database properly?

**Comment by cheenamalhotra** [comment]
@aasimkhan30 is preparing a PR to fix the bug we found while debugging!
_Help is on the way...🚨_

**Comment by kburtram** [comment]
Revert is merged to release branch.  Moving to May for fix in main.

**Comment by cheenamalhotra** [comment]
Closing as resolved.

**Comment by SakshiS-harma** [comment]
I am seeing this issue with the latest ADS insiders. Was this fixed?

**Comment by SakshiS-harma** [comment]
@cheenamalhotra Just checking, I saw this issue a couple of weeks back in insiders. Was this fixed back in time?

**Comment by cheenamalhotra** [comment]
I wonder if it came back with async server tree 🤔

@aasimkhan30 any ideas?

**Comment by SakshiS-harma** [comment]
As a workaround, the server can be connected with the database context, so the anticipated db is already in the dropdown.

**Comment by cheenamalhotra** [comment]
Issue is addressed in PR https://github.com/microsoft/azuredatastudio/pull/24017, closing as resolved.
