### ISSUE TITLE
Can't connect to Log Analytics after changing password

### ISSUE THREAD

**Issue by Henri-Wiechers** [microsoft/azuredatastudio#22624]
Issue Type: <b>Bug</b>

Change password of Azure AD account that is used for a connection. Try to access that connection afterwards. A Connection error dialog is displayed with the following error: 'Error: invalid_grant occurred when acquiring token.'. It includes the note: 'The provided grant has expired due to it being revoked, a fresh auth token is needed. The user might have changed ore reset their password.'

Azure Data Studio version: azuredatastudio 1.42.0 (22f384e569bc90d8b3231cc8c8cff99ea16c5052, 2023-03-17T18:15:48.982Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuremonitor|Mic|0.1.9
azdata-sanddance|msr|4.0.3

</details>

**Comment by cheenamalhotra** [comment]
Hi @Henri-Wiechers 

Have you tried removing and adding your account again?

**Comment by Henri-Wiechers** [comment]
Removing and adding the account again works.

**Comment by cheenamalhotra** [comment]
Based on the error message, that seems expected since your old access token would be revoked. 
We can look into resetting user account to prompt for re-authentication when this error occurs.

@cssuh can you handle this scenario and clear this account's token cache, mark it stale and prompt user to re-authenticate when this error occurs during token acquire request?

**Comment by cheenamalhotra** [comment]
Fixed with PR #22853 - will be included in upcoming release.
