### ISSUE TITLE
Some azure REST calls not returning correct information

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22631]
When updating from axios to the https module some of the response fields weren't properly updated, which means that they won't return the correct values.

example showing the returned fields not matching:

![image](https://user-images.githubusercontent.com/28519865/230163669-5f3cb301-4c79-4b9e-a08e-95f3e08ec490.png)

This should only apply to the calls that were switched from axios to the https module and weren't updated in the original PR, which there's two I see:

createResourceGroup
getStorageAccountAccessKey

These are both used by the sql-migration extension, as well as other features in ADS (such as backup).

**Comment by cheenamalhotra** [comment]
@cssuh I guess these are missed changes to use 'body' instead of 'data'?

**Comment by cssuh** [comment]
yep exactly, I tried to search for every response.data usage to change to response.body but I think these got missed because it was response?.data
