### ISSUE TITLE
Build fails in ADS when a cross-plat Legacy-style project has a new system db reference added in SSDT

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#22638]
Repro:
1. Create project in SSDT, close.
2. Open project in ADS, convert, close.
3. Open project in SSDT, add reference to master db, close.
4. Open project in ADS, build.

Expected:
successful build

Reality:
Build error:
`File "c:\Users\benjind\.azuredatastudio-rc1\extensions\microsoft.sql-database-projects-1.0.0\BuildDirectory\Extensions\Microsoft\SQLDB\Extensions\SqlServer\160\SqlSchemas\master.dacpac" does not exist. `

Already tracked in ADO as [Bug 15749](https://mssqltools.visualstudio.com/SQL%20Tools%20Semester%20Work%20Tracking/_workitems/edit/15749)

Work-around:
remove and re-add reference to master db in ADS.

**Comment by kisantia** [comment]
fixed in DacFx.Projects and the fix will get brought over when it next gets updated in STS
