### ISSUE TITLE
A11y_MySQLextensionforAzureDataStudio_Create new server group_Info and Relationships:In "Add server group" dialog After entering the Server group name, only the "Ok" button will be enabled, but the "Server group name" is not marked as required.

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/azuredatastudio#22658]
"[Check out Accessibility Insights! ](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier.”
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio; #Win32; #WCAG3.3.2; #Benchmark; #AILimited; 

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**

### Environment and OS details:
Azure Data Studio Version: 1.42.0 (user setup)
Windows 11 Enterprise Version	22H2
Installed on	‎28-‎12-‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
### Pre-Requisite:

1. Install Azure data studio From here https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall
2. Once installation done , Install MySQL Extension in Azure data studio
3. Tab Till  new connection and press enter 
4. Enter a valid server name username and password and press connect
### Repro Steps:

1. Launch Azure Data Studio.
2. Connect to server.
3. Tab till connection pane and press enter
4. Tab till New group color and press enter
5. Tab till server group name 
6. Verify that Server group name is required one 
### Actual Result:
In "Add server group" dialog After entering the Server group name, only the "Ok" button will be enabled, but the "Server group name" is not marked as required.
### Expected Result:
"Server group name" must be marked as required in add server group dialog
### Attachment:
![A11y_MySQLextensionforAzureDataStudio_Create new server group_Info and Relationships](https://user-images.githubusercontent.com/100189407/228777997-dddba9c1-0d59-4058-aa8d-32f7623a6a35.gif)

**Comment by VijayaBharathyA** [comment]
Primary bug https://github.com/microsoft/azuredatastudio-mysql/issues/175

**Comment by alanrenmsft** [comment]
@VijayaBharathyA Please use the latest insider build to verify the fix.

**Comment by VijayaBharathyA** [comment]
#Closed; #Regressed:05-09-23;
![image](https://user-images.githubusercontent.com/100189407/237018629-da4ba026-1669-47dd-9b5c-50084bb0852d.png)
Issue is fixed 
Version: 1.44.0-insider (user setup)
Commit: ff3f6d53c7aecf551b308ed03333943194316009
Date: 2023-05-08T05:31:07.830Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621
