### ISSUE TITLE
SQL Database Projects API needs a function for retrieving project metadata without scanning project files.

### ISSUE THREAD

**Issue by sergten** [microsoft/azuredatastudio#22662]
**Is your feature request related to a problem? Please describe.**
I'd like to get a list of all SQL Database projects whose target SQL Server version is 2012 or later. For that, I call `listProjects()`, and then iterate through the returned list and call `openProject(projectPath)` followed by `getProjectTargetVersion()`. The issue is that the call to `openProject()` is an O(n) runtime and depends on the number of files in the project (I have a few very large projects, 3000+ files). Currently for a 300+ files project the call to `openProject()` takes ~10-12 seconds.

**Describe the solution or feature you'd like**
It would be nice to have an API that would return the project metadata (which would include the target version) without a full-blown project opening. That call would be an O(1) operation.

**Describe alternatives you've considered**
I'm about to parse the project XML manually to avoid calling `openProject()`, but this way I depend on the project's XML format to be stable.

**Additional context**

**Comment by Benjin** [comment]
This has been completed in DacFx.Projects and Tools Service with https://github.com/microsoft/sqltoolsservice/pull/2040.  The APIs are now available for use by calling into the `mssql` extension like we do here: https://github.com/microsoft/azuredatastudio/blob/main/extensions/sql-database-projects/src/models/project.ts#L250

**Comment by Benjin** [comment]
Feel free to re-open if calling mssql directly doesn't meet your needs for whatever reason.
