### ISSUE TITLE
Installer throws error IPersistFile::Save failed

### ISSUE THREAD

**Issue by Thallerich** [microsoft/azuredatastudio#2267]
- SQL Operations Studio Version: 0.32.5

The Installer throws the following error at the end of the installation process:
IPersistFile::Save failed; code 0x80070002
The system cannot find the file specified.

Clicking OK finishes the installation and SQL Ops Studio works fine afterwards.

**Comment by kburtram** [comment]
@Thallerich have you seen this issue with recent Azure Data Studio releases?  I've never seen this error myself and don't have a repro.

**Comment by Thallerich** [comment]
@kburtram No, haven't seen this error lately.
However this could also be because our organization switched from a redirected home drive (to a server share) to a home folder that is synced with onedrive some time ago.

**Comment by kburtram** [comment]
Closing out older issues.  Please reactive if you see this issue again.  Thanks for logging this bug!
