### ISSUE TITLE
language-configuration.json settings are erased after new update

### ISSUE THREAD

**Issue by MrAlex6204** [microsoft/azuredatastudio#2268]
Issue Type: <b>Bug</b>

I add some custom configuration in the language-configuration.json
and after new update is been erased.

SQL Operations Studio version: sqlops 0.32.5-insider (d10e08e63ec26830efbcd070175ed935c36031f7, 2018-08-17T00:57:43.255Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7600 CPU @ 3.50GHz (4 x 3504)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.87GB (2.54GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
Bookmarks|ale|9.0.3
sqlops-combine-scripts|Bat|1.3.0
profiler|Mic|0.1.3
sql-search|Red|0.2.1

</details>

**Comment by kevcunnane** [comment]
Those are files built into the extensions and are not intended to be user-editable. Can you give more information on what you are trying to do by editing this file? Am I correct in thinking you're editing this inside the `extensions/sql` extension?

**Comment by MrAlex6204** [comment]
I add the below configuration for code folding
when I comment code between 
--#region 
--#endregion

"folding": {
		"markers": {
			"start": "^--\\s*#region.*$",
			"end": "^--\\s*#endregion\\s*.*$"
		}
	}

**Comment by kevcunnane** [comment]
I'd suggest a PR to add this by default is the way to go. @kburtram - given this is in the SQL extension, is our repo the right place to fix this or is it in the VSCode repository so we pick it up in a source code refresh?

You may alternatively be able to create your own extension and contribute this.

**Comment by MrAlex6204** [comment]
Is very useful ;D

![foldedcode](https://user-images.githubusercontent.com/8126962/44356188-39578a00-a474-11e8-9d76-fad52fbef7f4.jpg)
![unfoldedcode](https://user-images.githubusercontent.com/8126962/44356189-39578a00-a474-11e8-90c2-13a5039747c5.jpg)

**Comment by kburtram** [comment]
Closing out this older issue since we haven't seen recent repros.  Please let us know if this issue persists on current releases.  Thanks!
