### ISSUE TITLE
Cannot Log Into Azure Data Studio

### ISSUE THREAD

**Issue by josh122398** [microsoft/azuredatastudio#22716]
Issue Type: <b>Bug</b>

I have tried authenticating to this app for a number of attempts. I have deleted and reinstalled this application at least 4 times, and did so after restarting my machine to get my credentials to the SQL server authenticated. I cannot access the database, and my credentials WILL NOT update. This happens EVERY TIME Azure Data Studio updates. Any assistance would be greatly appreciated.

Attached file:
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11226299/1-Azure.Accounts.log)

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (21.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.4

</details>

**Comment by kburtram** [comment]
@cheenamalhotra do you have any ideas what could be happening here or next steps to diagnosis?  Thanks!

**Comment by cheenamalhotra** [comment]
Yes I noticed immediately after adding the tag, and I see error in logs:
`MsalCachePlugin: Failed to read from cache file: TypeError: Invalid initialization vector `

Which related to crypto package that we're using for encryption of cache. I'm looking into possible options to resolve the error, and will get back to you.

In the meantime, can you try adding account with below setting in settings.json:
`"azure.authenticationLibrary": "ADAL"`

Please continue capturing verbose logs so we can find out if ADAL caching throws any error.

**Comment by cheenamalhotra** [comment]
Although I don't know root cause, but it seems your IV in credential store is somehow corrupted. Can you try removing these credentials from Windows Credentials Store:
* `azureAccountProviderCredentials|accessTokenCache-iv`
* `azureAccountProviderCredentials|accessTokenCache-key`

And try with `MSAL` auth library again?
The cache will be cleared and keys will be regenerated when you reload Azure Data Studio with `MSAL` auth library.
