### ISSUE TITLE
Async Server Tree Drag and Drop not allowing you to move profiles outside group or back into group after editing.

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#22723]
Adding connections to a sever group (That are distinct) works, but when you try to move a connection out to the base, it doesn't allow you to even though it should.

Changing the connection's group manually to default seems to cause a bug that prevents you from adding the connection back in or other weird bugs as my below GIFs shows (although the gif is in the developer branch, it also happens in insiders as well), Also sometimes when a connection is already in a server group upon opening, editing the connection says the connection is in default instead of server group, Changing it to the server group works at first, but then if you decide to change it back to default, you aren't able to add it back in again. There is also one instance where the two profiles that I have swapped places after messing around with it a bit as I demonstrate below.

This will cause issues among users who want to frequently move the connections around and also issues with my new connection URI feature as it is to be expected to allow moving connections from different groups seamlessly.

![Server Group Bug Insiders Part 1](https://user-images.githubusercontent.com/18018452/231895641-814366bc-3976-4023-828a-a8bb808be508.gif)
![Server Group Bug Insiders Part 2](https://user-images.githubusercontent.com/18018452/231895652-57e2b10b-39ec-4470-975a-1b150d7f5566.gif)

**Comment by Charles-Gagnon** [comment]
@smartguest You should be able to drag it to the root if you drag it to the blank space under the existing connections. This is how VS Code works as well for their trees and also seems to be the current behavior with the existing non-async tree.

**Comment by cheenamalhotra** [comment]
Closing as no-op.
