### ISSUE TITLE
When flat file and mssql are both downloading, it flashes the output window a lot

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#2272]
when they are both writing messages to the output window during download, it flashes the output window between them.

**Comment by kburtram** [comment]
Since we bundle SQL Tools Service with mssql in our release builds I think this should only impact the developer scenario for now.

**Comment by kburtram** [comment]
Closing older issues with low customer impact.  We now download STS during build so I don't think this will typically impact common dev scenarios any more.
