### ISSUE TITLE
Object Explorer timeout occurs when should not happen

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22737]
Consider cases like:
- Expanding a connection node made with Serverless database 
  (takes ~50 seconds to expand since we retry and wait for DB to resume)
- Expand a node where Azure account token needs refresh (user is prompted to login)

These cases will always take more than 45 seconds (default OE timeout), and the second case should wait indefinitely on purpose to allow user to login into AAD account using MFA authentication.

These are common scenarios and OE timeout on parent tree node is causing unwanted disruptions.

@aasimkhan30 Do you think with Async Server tree changes this property is still required? Since we fixed the hang issue by triggering completion event, can we remove this setting?

**Comment by aasimkhan30** [comment]
In certain situations, a timeout may be necessary. How would we manage those circumstances? For example, what if the provider fails to respond to a connection or a connections has too many children and fetching them takes time. The user might think that OE has just stopped responding.

**Comment by aasimkhan30** [comment]
We can probably increase the timeout limit @cheenamalhotra

**Comment by cheenamalhotra** [comment]
> In certain situations, a timeout may be necessary. How would we manage those circumstances? For example, what if the provider fails to respond to a connection or a connections has too many children and fetching them takes time. The user might think that OE has just stopped responding.

The root connection node is the only area where we have these cases, I don't mean to suggest remove timeout from child nodes/folder nodes. Since we recently added it there for the hang issue (that we have possibly fixed too), we could consider removing it form root.
