### ISSUE TITLE
Double-click a column separator in the Results grid to auto-size the column

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#22731]
**Is your feature request related to a problem? Please describe.**
When I run a query, the results in the grid all have the same column width. In many cases, it's not wide enough.

**Describe the solution or feature you'd like**
I'd like the ability to double-click a column separator in the header row to resize the column width to accommodate the longest *visible* value in the column. 

**Describe alternatives you've considered**
N/A

**Additional context**
The double-click resize column feature is common in Windows (File Explorer) and Windows applications (Excel). We should have it here.
![image](https://user-images.githubusercontent.com/22224925/232105158-cb631ec2-0441-4f18-af4e-f848e32061d4.png)

**Comment by alanrenmsft** [comment]
@barryseymour this is already supported, but there is a setting to control the max width of the auto-sized column, the default value is 212px, that does seem to be too small, I can adjust the default value to a larger value.

![image](https://user-images.githubusercontent.com/13777222/232138854-144c2945-8291-4c15-9edd-ed824ee69fdb.png)

**Comment by barryseymour** [comment]
That would be great, thanks! I would even go so far as to ask why is there a maximum at all? But an increase in the max would definitely help.
