### ISSUE TITLE
ADS - An error occurred during the login process

### ISSUE THREAD

**Issue by tahmid-bari** [microsoft/azuredatastudio#22749]
Hi Team,
Please find the issue below, which occurred while I was attempting to connect to an on-premises SQL server 2019 via Azure Data Studio (version: 1.32.0) on a windows 10 machine.
Microsoft.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the login process. (provider: SSL Provider, error: 0 - The certificate chain was issued by an authority that is not trusted.)

![Connecting to on-prem sql server using ADS](https://user-images.githubusercontent.com/45582415/232277155-d0a9ba5d-04c8-40fd-8e09-b42e26f7df22.jpg)

**Comment by kburtram** [comment]
@tahmid-bari have you tried upgrading to the latest ADS version?  It has improvements in how encrypted connections are handled.  The error seems to be saying there is an issue with the certificate used on the server for encryption, perhaps it is a self-signed cert and the CA isn't registered on the client machine, for example.  You could try setting the "Trust server certificate" Advanced option to True to bypass this certificate validation.

**Comment by tahmid-bari** [comment]
Hi @kburtram - After upgrading the ADS to the newest version, I noticed the 'Enable Trust Server Certificate' option. I also see the 'Encrypt' and 'Trust server certificate' options. Probably, because the server certificate was not validated, I was unable to connect to the SQL servers. All good now as I can connect to the on-premises SQL servers. Many thanks.
![ADS_Update](https://user-images.githubusercontent.com/45582415/232849607-85446333-0d5b-40f8-b14c-62583d696e1c.png)
![certificate_connection](https://user-images.githubusercontent.com/45582415/232849933-baf1d30d-2025-4766-88b6-e07f86974c0c.png)

**Comment by cheenamalhotra** [comment]
Great to hear! Closing as resolved.
