### ISSUE TITLE
 Screen reader announcing section when tab focus is on red bar of graph and in scan mode it is announcing clickable

### ISSUE THREAD

**Issue by kapilvaishna** [microsoft/azuredatastudio#22754]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio;#Win32; #WCAG1.3.1; #NVDA; #Screenreader; #Benchmark;#AILimited; #Regressed05-30-23; #Closed;
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**
### Environment and OS details:
Application name: Assessment
App version: Azure Data Studio 1.39.1
Windows Version: Win11
Screen reader: NVDA [version: 2022.2], JAWS [version: 2022.2207.25 ILM]
### Pre-Requisite:

1. Download the azure data studio from the link https://docs.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver15
2. Once installation done , Install Database Migration Assessment for Oracle Extension in Azure data studio
3. Tab Till new connection and press enter
4. Select connection type as oracle
5. Enter a valid server name username and password and press connect
### Repro Steps

1. Tab to the Database Migration Assessment for Oracle button and then press enter. "Database Migration Assessment for Oracle" page will be opened.
2. Tab to the "Run New Assessment" button at top the page and press enter.New  Database Migration Assessment for Oracle dialog box will open. Select Target Platform as "PostgreSQL". Fill the correct details. Tab to "Start Assessment button and press enter.
3. New Assessment can be seen in last five assessment tab. Tab to the assessment press enter. New tab will get open.
4. Tab to Assessment overview by platforms section. Tab to Assessment for Azure virtual machine  in the section.Tab to view report details button and press enter. New screen will open.
5. Tab to "Code Compatibility" tab and press enter.
6. Start NVDA and press tab to navigate red bar of graph 
7. observed that when focus is on red bar graph it announces section only 
### Actual Result:
Screen reader announcing section when tab focus is on red bar of graph and in scan mode it is announcing clickable
### Expected Result:
Screen reader should  announce the data for that bar graph on tab or scan mode
### Attachment:

https://user-images.githubusercontent.com/124254981/232493180-1051a6d5-2425-473b-b3b1-c461ade83bc4.mp4

**Comment by kapilvaishna** [comment]
Primary bug:https://msdata.visualstudio.com/Migration%20Assistant/_workitems/edit/2081147

**Comment by P-Gaharwar** [comment]
@Charles-Gagnon  \ @kburtram : Can you please triage this bug?

**Comment by alanrenmsft** [comment]
@stuti149 please work with the tester to get the issue closed.

**Comment by kapilvaishna** [comment]
Issue is not there in ADS Insiders version 1.45.0 and vsix (rc0010).
So, closing the bug 


https://github.com/microsoft/azuredatastudio/assets/124254981/35c73a8b-d0c1-4187-8b19-bf67dae45587
