### ISSUE TITLE
A11y_AzureDataStudio_New Database_Keyboard:When error message is occur in New Database dialog, Keyboard focus is not shifting error message

### ISSUE THREAD

**Issue by VijayaBharathyA** [microsoft/azuredatastudio#22752]
### GitHub Tags:
#A11yMAS; #A11yTCS; #A11ySev2; #DesktopApp; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio;#Win32; #WCAG2.4.3; #Focus Order; #Keyboard; #Benchmark; #Closed; #Regressed:04-18-23

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**

### Environment and OS details:
Azure Data Studio Version: 1.42.0 (user setup)
Windows 11 Enterprise Version	22H2
Installed on	‎28-‎12-‎2022
OS build	22621.1413
Experience	Windows Feature Experience Pack 1000.22639.1000.0
### Pre-Requisite:

1. Install Azure data studio From here https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall
2. Once installation done , Install MySQL Extension in Azure data studio
3. Tab Till  new connection and press enter 
4. Enter a valid server name username and password and press connect
### Repro Steps:

1. Launch Azure Data Studio.
2. Connect to server.
3. In the Connections pane, right-click on a server connection. 
4. Then select 'Manage' from the context menu to view the dashboard.
5. From dashboard, click on New Database.
6. Tab till name enter any invalid keyword
7. Tab till connect and press enter
8. Verify that, When error is occurring keyboard Focus not shifting error message or not
### Actual Result:
When error message is occur in New Database dialog, Keyboard focus is not shifting error message.
### Expected Result:
When error message is occur in New Database dialog, Keyboard focus should shift there.
### Attachment:
![A11y_MySQLextensionforAzureDataStudio_New Database_Keyboard](https://user-images.githubusercontent.com/100189407/228866131-1f3ec8d3-c8e4-4966-97bf-f254957021e4.gif)

**Comment by VijayaBharathyA** [comment]
Primary bug: https://github.com/microsoft/azuredatastudio-mysql/issues/185

**Comment by alanrenmsft** [comment]
@VijayaBharathyA this is fixed now, please use the latest insiders build to verify. Thanks
