### ISSUE TITLE
SQL Server Connection Issue

### ISSUE THREAD

**Issue by prestonvk** [microsoft/azuredatastudio#22765]
Issue Type: <b>Performance Issue</b>

I am trying to connect to a SQL server using Azure Data Studio on a MacBook.  The MacBook is a 2020 Intel MacBook Pro with Ventura 13.1.  I configured the connection with the proper server name, which I can ping from the MacBook, Authentication Type is set to Windows Authentication and Trust Server Certificate is set to True.  When I attempt to connect, I get this error:

Connection Error

Connection failed due to Kerberos error.
Help configuring Kerberos is available at https://aka.ms/sqlopskerberos
If you have previously connected you may need to re-run kinit.

I haver a valid Kerberos ticket in Ticket Viewer on the MacBook and have tried running kinit.

Could you please tell me what I need to resolve this?  Thank you.

Azure Data Studio version: azuredatastudio 1.43.0 (Universal) (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:12:47.777Z)
OS version: Darwin x64 22.2.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz (8 x 2000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   19	    98	  6035	azuredatastudio main
    4	    33	  6036	   gpu-process
    0	     0	  6040	   utility-network-service
    1	    82	  6109	   shared-process
    0	    16	  6114	     ptyHost
    0	    49	 25335	     fileWatcher
    2	     0	 25366	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   229	 25333	   window (Welcome)
    0	   131	 25334	   extensionHost
    0	    66	 25341	     /private/var/folders/d8/5h2kfwmd545cxrfs588l1r8m0000gn/T/AppTranslocation/95741833-2F25-42F2-BDE0-4B52894F5D31/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/4.6.1.4/MicrosoftSqlToolsServiceLayer --application-name azuredatastudio --data-path /Users/q735993/Library/Application Support --locale en --log-file /Users/q735993/Library/Application Support/azuredatastudio/logs/20230417T120323/exthost4/Microsoft.mssql/sqltools.log --tracing-level Critical --autoflush-log
    0	    33	 25343	     /private/var/folders/d8/5h2kfwmd545cxrfs588l1r8m0000gn/T/AppTranslocation/95741833-2F25-42F2-BDE0-4B52894F5D31/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/4.6.1.4/SqlToolsResourceProviderService --application-name azuredatastudio --data-path /Users/q735993/Library/Application Support --locale en --log-file /Users/q735993/Library/Application Support/azuredatastudio/logs/20230417T120323/exthost4/Microsoft.mssql/resourceprovider.log --tracing-level Critical --autoflush-log
    0	    33	 25344	     /private/var/folders/d8/5h2kfwmd545cxrfs588l1r8m0000gn/T/AppTranslocation/95741833-2F25-42F2-BDE0-4B52894F5D31/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/4.6.1.4/MicrosoftSqlToolsCredentials --application-name azuredatastudio --data-path /Users/q735993/Library/Application Support --locale en --log-file /Users/q735993/Library/Application Support/azuredatastudio/logs/20230417T120323/exthost4/Microsoft.mssql/credentialstore.log --tracing-level Critical --autoflush-log
    4	    66	 25360	   issue-reporter
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @prestonvk 

When connecting with Kerberos, there are few things to note:
- ADS will fetch the latest ticket (only) from the Kerberos Ticket cache
- By default, ADS will use default TGT location, unless you override the location with KRB5CCNAME env variable
- The ticket you create should be created for the user/email (with `kinit <username>` is logged in user is different.
- Try running `klist` command on terminal to list the tickets available to verify the 'latest' ticket is valid one for the user who needs to be authenticated.

**Comment by cheenamalhotra** [comment]
Hi @prestonvk 

Checking in, do you have an update on this issue?

**Comment by cheenamalhotra** [comment]
Closing as stale.
