### ISSUE TITLE
Can't connect to server where user sa has no password

### ISSUE THREAD

**Issue by jimkilliansentinel** [microsoft/azuredatastudio#22773]
Issue Type: <b>Bug</b>

This works in SSMS as shown here: 
![image](https://user-images.githubusercontent.com/85969574/232923253-16aec5de-5515-440d-8469-444dcb666060.png)
And the connection is completely functional when completed.

When I try the same connection in ADS:
![image](https://user-images.githubusercontent.com/85969574/232923447-477c6b50-7e07-464d-bb5e-e0025b4371c2.png)

I get an error: 
![image](https://user-images.githubusercontent.com/85969574/232923530-559e9f40-83bf-4fb6-8b8d-bdb305db9aaf.png)
Details:
```
System.ArgumentNullException: Value cannot be null. (Parameter 'Password')
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.CreateConnectionStringBuilder(ConnectionDetails connectionDetails) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 1354
   at Microsoft.SqlTools.ServiceLayer.Connection.ConnectionService.TryOpenConnection(ConnectionInfo connectionInfo, ConnectParams connectionParams) in D:\a\_work\1\s\src\Microsoft.SqlTools.ServiceLayer\Connection\ConnectionService.cs:line 741
```

Changing the settings for `Remember Password`, `Encrypt`, and `Trust Server Certificate` has no effect.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (4.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.7
query-history|Mic|0.5.3
extra-sql-script-as|pac|0.5.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by simonsabin** [comment]
Enabling this would support a very very bad practice. 
Why do you need a server with no password?

**Comment by jimkilliansentinel** [comment]
If there's a desire to make this a more obvious action, include a "□ Confirm **No Password**" checkbox next to the "Remember Password" one when the password isn't supplied. It still won't pass security if there actually _is_ a password, but will confirm that this isn't the result of an oversight.

**Comment by simonsabin** [comment]
I've tried to do a pull request to enable this. Lets see what happens

**Comment by Charles-Gagnon** [comment]
@jimkilliansentinel This should be addressed by https://github.com/microsoft/sqltoolsservice/pull/2021, would you be able to try out the latest [insiders](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main) build and see if you run into any issues?

**Comment by jimkilliansentinel** [comment]
Was able to login successfully to the server with no password. Other servers are working as well.

Thanks!

Jim

Jim Killian | Software Developer
Sentinel Offender Services, LLC
111 Corporate Drive, Suite 125 | Ladera Ranch, CA 92694<webextlink://111%20Corporate%20Drive,%20Suite%20125%20|%20Ladera%20Ranch,%20CA%2092694/>
C| 949.239.3722
E| ***@***.******@***.***>
W| www.sentineladvantage.com<http://www.sentineladvantage.com/>

**Comment by cheenamalhotra** [comment]
Closing as resolved.
