### ISSUE TITLE
User dialog validation logic steals focus while trying to correct warnings

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22777]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Create User dialog
2. Change to Contained user with SQL Login auth
3. Click Script button with empty passwords
4. Try to fix the passwords by typing two new values in text boxes

Expected: The warning can be corrected.

Actual: After each character is typed into password text box focus is stolen and moved to the warning on dialog.  This makes it very difficult to correct the errors.

![image](https://user-images.githubusercontent.com/599935/232964705-89d86efd-af4b-4f3d-9a1c-f6ac5e7fb2fa.png)

**Comment by alanrenmsft** [comment]
I also noticed this yesterday and the fix is in https://github.com/microsoft/azuredatastudio/pull/22781/files#diff-79b7efb31cab44e8b386bea529ce174e39c3f4a601c3acb8e4494e321e3c860dR615, I'll send out a seperate PR to fix the issue.
