### ISSUE TITLE
Ability to copy (in order to paste) Column Names from Results

### ISSUE THREAD

**Issue by Ben-CA** [microsoft/azuredatastudio#22785]
If you could right click on a column name and select "Copy", that would save time vs. typing it out to add it as a filter, etc.

![image](https://user-images.githubusercontent.com/47060874/233168919-f714d1ed-ea51-4514-a644-0c5ce1d92c67.png)

So for instance, to be able to select or right click on WKO_WorkOrderID to copy the column name.

**Comment by alanrenmsft** [comment]
@Ben-CA In the latest Insiders build, you can select cells and select `Copy Headers` to copy the headers for selected columns.

![image](https://github.com/microsoft/azuredatastudio/assets/13777222/42e73c7c-59a2-4f01-b2de-d8486330b811)
