### ISSUE TITLE
不能使用使用报错

### ISSUE THREAD

**Issue by 1264216036** [microsoft/azuredatastudio#22792]
Issue Type: <b>Bug</b>

不能使用使用报错

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:12:44.872Z)
OS version: Darwin arm64 22.4.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|5, 5, 4|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hans|Mic|1.43.0
azuredatastudio-oracle|Mic|0.1.2
net-6-runtime|Mic|1.1.0

</details>

**Comment by cheenamalhotra** [comment]
Hi @1264216036

We only provide support in English, please update title and add additional info in issue description.
