### ISSUE TITLE
What you see on screen is not what the app thinks it is executing

### ISSUE THREAD

**Issue by mmcaulay** [microsoft/azuredatastudio#22790]
Issue Type: <b>Bug</b>

After several hours of using Azure Data Studio with some reasonably large stored procedure scripts, it gets confused about what SQL I am trying to execute.
What I see on screen is no longer what it is executing under the hood, like the error messages refer to older versions of the file.
For example I copy a file and start changing it, but if I execute that script then it's not seeing the changes under the hood and executes the original script.
If I close the app and reopen it, it comes good.
It doesn't have to be a large file to see the behaviour, any size file will experience it.
It happens after some time of having the app open, not straightaway.
I'll attach some images where it just happened today.

Image 1 - Bug happening, incorrect error showing when executing this script
Image 2 - After restarting app, was able to run the portion of the script just fine
![image](https://user-images.githubusercontent.com/4042561/233273291-a8dccdcf-cdd0-4e7b-8744-836d738b0b18.png)

![image](https://user-images.githubusercontent.com/4042561/233273317-e3262c66-dab1-41cb-8f03-5b7dd1b4dc78.png)

This issue has been occurring for me for quite a long time, maybe 12 months. I just reopen the app.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (12.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-data-inspector|ern|0.6.0
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.4
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.0.1
azdata-sanddance|msr|4.0.1

(1 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment]
Hi @mmcaulay 

Can you try the latest insiders build and let us know if that has improved the experience?

**Comment by cheenamalhotra** [comment]
Closing as we haven't heard back on the issue, and with recent improvements this issue should be resolved.

**Comment by mmcaulay** [comment]
Thanks I haven't seen this issue since upgrading
