### ISSUE TITLE
ADS v1.43.0 crashes with CodeWindow: renderer process crashed (reason: crashed, code: -36861) 

### ISSUE THREAD

**Issue by ajayparwani** [microsoft/azuredatastudio#22797]
- Azure Data Studio Version: 1.43.0
- OS Version: Win11
<img width="944" alt="Ads_Crash" src="https://user-images.githubusercontent.com/31746599/233441246-439fbaa0-421a-482b-bdb4-d6cfddf0b0dd.png">
@Charles-Gagnon 

Steps to Reproduce:
1. Install the DMAO extension using the private vsix.
2. Right click on the server , select Manage and click on Migration Assessment
3. Run an Assessment – Select SQL as target platform and CODE ASSESSMENT as Assessment Type
4. Run Validation and start the assessment.
5. The assessment takes hours so go for a coffee break.
6. Minimize ADS and wait for the assessment to complete (Usually crashes after 6-7 hours).

Does this issue occur when all extensions are disabled?: Yes/No - No

**Comment by kburtram** [comment]
This was tracked down to a memory leak in the modelview framework and a workaround was provided.  The API improvements to allow cleaning up unused controls is tracked in extensibility backlog.  Please let us know if there is anything else needed for this specific crash.
