### ISSUE TITLE
'Run Kinit' Prompt doesn't show anymore when expanding OE node

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#22798]
Haven't run kinit in a while, tried using integrated auth from my mac to connect to an on prem server, and the experience looks to have regressed.

Stable:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/40371649/233452509-e45138d7-754c-4013-864f-62d69be78dd5.png">

Latest insiders:
<img width="640" alt="image" src="https://user-images.githubusercontent.com/40371649/233452566-7515bd80-81c0-45af-8afd-9b2d95e96624.png">

**Comment by cheenamalhotra** [comment]
Does that happen with OE node expansion "only"? 
Could you please check by creating new connection from the connection dialog?

I don't see 'Copy Details' in the screenshot so it doesn't look like the connection error dialog.

**Comment by chlafreniere** [comment]
> @chlafreniere Does that happen with OE node expansion "only"? Could you please check by creating new connection from the connection dialog?
> 
> I don't see 'Copy Details' in the screenshot so it doesn't look like the connection error dialog.

Yes, only from OE node expansion - it doesn't repro for me when starting from the connection dialog:

<img width="640" alt="image" src="https://user-images.githubusercontent.com/40371649/233484603-8597dd5c-9611-43b7-a97e-49aaea182a75.png">

**Comment by cheenamalhotra** [comment]
Can you also check in stable build? Just to understand if this is a recent regression or an existing issue.
Sorry I don't have mac yet :P

**Comment by chlafreniere** [comment]
> Can you also check in stable build? Just to understand if this is a recent regression or an existing issue. Sorry I don't have mac yet :P

In the stable build, I see the expected behavior in both scenarios (OE + connection dialog) where the "Run Kinit" button is visible and I don't see the stack trace.

**Comment by cssuh** [comment]
I am not able to see the Run Kinit button either, I get the same error as @chlafreniere

**Comment by cssuh** [comment]
After testing with Aasim, disabling async server tree seems to fix the issue.
