### ISSUE TITLE
Error expanding database nodes disconnects entire session

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22804]
Version: 1.44.0-insider (user setup)
Commit: a9951e977c8a706930171149de5e12d281059b38
Date: 2023-04-20T16:11:04.794Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

(not a regression it seems)

1. Connect to a server with multiple databases
2. Try to expand database that you don't have access to

The connection errors out, but then the whole server connection is put in a sort-of disconnected state.

![DatabaseExpandError](https://user-images.githubusercontent.com/28519865/233462582-502da3fd-1cdc-47d2-a24a-1600cf9cb314.gif)

**Comment by cheenamalhotra** [comment]
Related issue: https://github.com/microsoft/azuredatastudio/issues/22211

**Comment by cheenamalhotra** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/22211
