### ISSUE TITLE
DEB file not produced during CI builds

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22808]
- Azure Data Studio Version: `insider`

The DEB file build was disabled during the vscode merge and needs to be reenabled.

**Comment by kburtram** [comment]
We'll need to revert https://github.com/microsoft/azuredatastudio/pull/22795 and apply fixes for this error in order to reenable DEB file creation.

```
libxrandr2
xdg-utils (>= 1.0.2)
    at Object.getDependencies (/__w/1/s/build/linux/debian/dependencies-generator.js:58:19)
    at Stream.<anonymous> (/__w/1/s/build/gulpfile.vscode.linux.js:84:54)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
error Command failed with exit code 1.
```

**Comment by lewis-sanchez** [comment]
This PR was fixed by: https://github.com/microsoft/azuredatastudio/pull/22811

![image](https://user-images.githubusercontent.com/87730006/235832686-e2cff32b-8964-4082-a414-8a8607e91b45.png)

**Comment by cheenamalhotra** [comment]
Re-opening issue as the related change has been reverted.

**Comment by kburtram** [comment]
I believe this is fixed by other build folder updates merged to release branch.
