### ISSUE TITLE
Connection identifier in the status bar has unnecessary details

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#22817]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Connect to a server and open a connected editor

Expected: Connection name string in status bar has server name and auth name, but not a lot of unnecessary details so the string isn't too long.  Having a very long string makes less space for other content and makes the status bar more cluttered.

Actual: Connection name contains advanced options, like timeout and app name, which aren't really needed to provide context on what connection the editor is using.

![image](https://user-images.githubusercontent.com/599935/233699921-f39efce6-a2e9-4914-8811-64991f4a9dd8.png)

**Comment by kburtram** [comment]
@smartguest this looks like a regression from the connection name change you recently made. Could you please restore this string to previous behavior?  Also, please go through the entire product where connections are displayed and make sure that we aren't included the advanced options, except where needed to disambiguate the connection being used (such as in OE if there are multiple very similar connections, etc.).

**Comment by smartguest** [comment]
Closing issue as connection string was reverted for now.

**Comment by smartguest** [comment]
Reopening as new connection string is being reintroduced.
