### ISSUE TITLE
Investigate automatic conversion of response headers into objects in Azurecore

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22835]
https://github.com/microsoft/azuredatastudio/blob/14a57b3dcf25ce3b3d3312ba99354db9410295b6/extensions/azurecore/src/account-provider/auths/httpClient.ts#L236

In https://github.com/microsoft/azuredatastudio/pull/22417 this logic was added to automatically check if incoming header response values were actually JSON objects - and if so convert them into an object before returning the response. But that value is put into a map that is typed to contain only strings, which seems dangerous. 

We should investigate:

1. Why we need to do that in the first place - is there a specific header value that is always going to be an object?
2. Whether we can instead leave it as a string and then do the conversion later on where whatever is using the header value can convert it instead
3. If it makes sense to do this for every header value (very questionable) - then at least we should update the typings of the returned map to be correct (`string | object` instead of just string).

**Comment by cheenamalhotra** [comment]
> Is there a specific header value that is always going to be an object?

_Http: Proxy Authorization
The value to send as the Proxy-Authorization header for every network request._

Http Proxy authorization header is a user defined setting that would be included here. I'm not sure if we are reading this as of now, but that would be something to support here, and hence the design is abstracted to support it.
