### ISSUE TITLE
A11y_User Management feature for Azure Data Studio_Login_LoginNew_AI4D:The Name property of a focusable element must not be null.

### ISSUE THREAD

**Issue by sspatil123** [microsoft/azuredatastudio#22841]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**GitHubTags:**#A11yMAS;#A11yTCS;#SH_User Management feature for Azure Data Studio_Apr2023;#SQL Azure Data Studio ;#DesktopApp;#A11ySev3;#AI4D;#Win11;#Win32;#WCAG4.1.2;#Benchmark;#AINotInScope;

## Environment Details:
Application Name: Azure Data studio insiders
Version:1.44.0
Windows Version: Win11
Operating system : Windows 11 Enterprise (OS build22621.1555)

## Repro Steps:
1. Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after verification of the fix
1. Open Azure data studio (Insiders) and connect with server with correct credentials
2. Tab till Security drop down and expand it
3. Tab till Logins Drop down and right click on it
4. Select New Login
5. Login - New (Preview) Dialog will open
6. Run Accessibility Insights for Web.

## Issue:

The following accessibility issue needs investigation.

**App:** azuredatastudio-insiders

**Element path:** check box ''

**Issue Details:** The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/ict/#502-interoperability-assistive-technology)

## **How To Fix:** 
Provide a UI Automation Name property that concisely identifies the element.

This accessibility issue was found using Accessibility Insights for Windows, a tool that helps debug and find accessibility issues earlier. Get more information and download this tool at https://aka.ms/AccessibilityInsights.

### **Similar issue observed in following Scenarios also.**

1. 'General_SQL Authentication'
2. Newly Created Login_Login - Access (Preview)
3. Users_User - New (Preview)
4. Users_User - test (Preview)

## User Impact:
Screen reader user will not able to correct information about control.

## Attachment:
![AI focusable](https://user-images.githubusercontent.com/85863999/234179833-e12a4a3d-c440-4b2b-92b5-7e466fb0dbd0.png)
![Similar issue Focusable](https://user-images.githubusercontent.com/85863999/234179862-d0c5794f-38b8-4dec-b1ae-22934b3710e3.png)
![Similar issue User New Focusable](https://user-images.githubusercontent.com/85863999/234264717-8a1ea0dc-9312-47e3-8f7c-b1e6d0921d48.png)

**Comment by alanrenmsft** [comment]
@sspatil123 please use the latest insiders build to verify the fix. https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch

**Comment by alanrenmsft** [comment]
@sspatil123 pinged me offline and confirmed the issues has been fixed, so closing the issue.

**Comment by sspatil123** [comment]
The issue was fixed in Version: 1.45.0-insider (user setup). Hence closing bug
![image](https://github.com/microsoft/azuredatastudio/assets/85863999/9b43ef9b-c3e6-4a20-b540-781d4864a88f)
![image](https://github.com/microsoft/azuredatastudio/assets/85863999/1588f69f-695d-42ef-8e14-c52ae6705c4f)
