### ISSUE TITLE
Remove built-in BDC Troubleshooting book

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22868]
Now that we've removed the BDC functionality we should remove this as well.

The item from the remote book dialog should also be removed.

**Comment by Charles-Gagnon** [comment]
@chlafreniere Do we want to remove the whole provided books view? Right now it seems like the only two things contributing to it are the 2019 TSG and [azurehybridtoolkit](https://github.com/microsoft/azuredatastudio/blob/main/extensions/azurehybridtoolkit/package.json#L50) - but that one doesn't even seem like it was ever actually released.

**Comment by chlafreniere** [comment]
@barbaravaldez Can you remind me if there are other scenarios around provided jupyter books (other than loading the 2019 TSG guide)? Can users access it in another way too?
