### ISSUE TITLE
"Invalid tree item, invalid iconPath" Console Errors in Azure View after Expanding Subscription Tree Item

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#22865]
(Latest insiders, Windows)

In Azure view, when I expand any subscription, the following messages show up in the console. Note that folder icons seem to load just fine from what I can tell, so there may not be any user impact beyond messages going to the console:

[Extension Host] **INVALID tree item, invalid iconPath** {dark: 'c:\\Users\\<redacted>\\AppData\\Local\\Programs\\Azure Dat…sions\\azurecore\\resources\\dark\\folder_inverse.svg', light: 'c:\\Users\\<redacted>\\AppData\\Local\\Programs\\Azure Dat…p\\extensions\\azurecore\\resources\\light\\folder.svg'} (at console.<anonymous> (c:\Users\<redacted>\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:196417))

console.ts:137 [Extension Host] **Extension Microsoft.azurecore has provided an invalid tree item.** (at console.<anonymous> (c:\Users\<redacted>\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:83:196417))

**Comment by chlafreniere** [comment]
Looks like we'll get the fix when the following code comes in via the merge: https://github.com/microsoft/vscode/pull/157771

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Is there a reason this is in the backlog? If it's just porting over a single commit that seems easy enough to warrant bringing in for the next release - I'm happy to take a look at doing that if you're busy with other stuff. But getting rid of unnecessary warnings/errors in the console is definitely a good thing for us to keep working towards.
