### ISSUE TITLE
Status Bar Row Count not updating in real time

### ISSUE THREAD

**Issue by Blindeddie** [microsoft/azuredatastudio#2286]
- SQL Operations Studio Version: 0.32.5-insider

Steps to Reproduce:
1. Open Two Editor windows 
2. run select top 1 query in editor  1 SB row count shows 1
3. run select top 10 query in same editor, SB row count remains 1
4. click tab to switch to editor 2 then switch back to editor 1, SB row count indicates 10 rows
5. and so on....

This relates to  closed issue #2023. 

also noticed that sometimes when opening new editor window, SB row count does not clear.

**Comment by kburtram** [comment]
@Blindeddie I wasn't able to repo this myself.  The status bar row count is being updated consistently when tab switching.  I'll check on different machines to see if there is some environment component.  Please let me know if you have additional repro details.

**Comment by Blindeddie** [comment]
@kburtram This appears to be intermittent, not sure why, but does happen frequently when selecting a large number of columns that you need to scroll to see.  Not sure if that helps, but will see if I can get some screenshots when I have a chance.

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if you're still impacted by this issue.  Thanks!
