### ISSUE TITLE
 Failed to generate select script for the selected object.

### ISSUE THREAD

**Issue by tanmoycuat** [microsoft/azuredatastudio#22872]
Issue Type: <b>Bug</b>

Right click on Azure data Studio. Right click on Table script to slelect top 1000 rows and it throws error " "Failed to generate select script for the selected object.""

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 2803)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.49.0
import|Mic|1.5.4
kusto|Mic|0.5.8
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
azdata-sanddance|msr|4.0.3

</details>

**Comment by cheenamalhotra** [comment]
Hi @tanmoycuat 

Can you capture 'Verbose' logs (MSSQL) when this error occurs and upload them here for investigation?

**Comment by teodor-io** [comment]
If it helps others: in my case I fixed it by adding my external IP address to whitelist.

**Comment by cheenamalhotra** [comment]
> ERR Scripting failed. error: An error occurred while scripting the objects. Failed to connect to server synw-xxx-xxxdwh-dev-ondemand.sql.azuresynapse.net.

@SaschaProdware This seems like an issue you're facing where server connection could not be made. With support of connection pooling (enabled by default), this should not occur now. I will close this issue, and if it occurs again, let us know.
