### ISSUE TITLE
Sql db projects non-working codeflows in VSCode

### ISSUE THREAD

**Issue by SakshiS-harma** [microsoft/azuredatastudio#22886]
After PR #22847  is checked in- following workflows need more investigation in VSCode to work:

- Create project from database doesn't pick the context from profile correctly
- Create project from database doesn't complete (because of the next issue)
- sanitizeStringForFilename doesn't work as expected, so can't add new objects to the project.

**Comment by kisantia** [comment]
closing this since these work when the new version of data workspace is installed

**Comment by kisantia** [comment]
@SakshiS-harma I didn't run into the first problem mentioned ("Create project from database doesn't pick the context from profile correctly"). The correct connection and database were getting chosen when I tried create project from db
