### ISSUE TITLE
Connection failure no longer has reason

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22915]
main

The connection failure dialog used to state the reason for the connection failure, now it just says the connection failed.

Current stable:

![image](https://user-images.githubusercontent.com/28519865/235544147-f3a52209-b429-492f-aa65-3e0fb7c7530f.png)

Current main:

![image](https://user-images.githubusercontent.com/28519865/235545045-8b415a65-15f6-4cfa-ba48-01ae5ec3a997.png)

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra I believe this is caused by https://github.com/microsoft/azuredatastudio/pull/22890, if I go back to the commit before that then I see the full error message again.

**Comment by cheenamalhotra** [comment]
Reason is not defined by ADS or the driver. It comes from the server with error information:

![image](https://user-images.githubusercontent.com/13396919/235711334-42733584-4388-4ade-89f1-8493f70b9aba.png)

Can you verify using same protocol on both ADS versions? The protocol driver chooses can vary and is not consistent if multiple protocols are supported by server.

Try setting server name: `tcp:<servername>; or np:<servername>;`

**Comment by Charles-Gagnon** [comment]
Uh... huh. That's pretty weird. It was the exact same connection and changed what it displayed by just switching to different commit points in the repo. 

Let me try to set up the repro again and see if this is still happening. This was with a SQL 2022 docker container for what that matters, maybe something is funky there.

**Comment by Charles-Gagnon** [comment]
Given what you said I'm closing this as "expected behavior" for now, if I can repro this issue again I'll try to dig a bit deeper to see if it's some driver issue.
