### ISSUE TITLE
Can I clear the Results pane in code?

### ISSUE THREAD

**Issue by jimkilliansentinel** [microsoft/azuredatastudio#22911]
### Discussed in https://github.com/microsoft/azuredatastudio/discussions/21923

<div type='discussions-op-text'>

<sup>Originally posted by **jimkilliansentinel** February 13, 2023</sup>
I'm running this code to check some queues on a schedule and would like to clear the Results pane before each iteration so that the current results are always in view:
```
    while ({some test}) 
    BEGIN  
        {clear Results pane}  
        exec [dbo].[_JimK_CheckJobQueues];  
        RAISERROR( 'Just to print everything',0,1) WITH NOWAIT  
        WAITFOR DELAY @waitTime;  
    END  
```
The code works fine except for clearing the Results pane. I had to add the RAISERROR to get the results to show before pausing.

Is this doable?</div>

**Comment by alanrenmsft** [comment]
@jimkilliansentinel using SQL script to clear the results in ADS is not possible and I don't think it is something we will be supporting.
