### ISSUE TITLE
"Update project from database" doesn't work anymore since ADS version 1.43

### ISSUE THREAD

**Issue by thomas-svrts** [microsoft/azuredatastudio#22923]
- Azure Data Studio Version: 1.43
- OS Version: Windows 11

Steps to Reproduce:

1. create project from database (in my case a synapse dedicated sql pool) (create project from database extracts the wrong platform version)
2. update that project (via 'update project from database') with the same database
3. error received of "target platform isn't matching", even if I change target platform it doesn't work. 

Does this issue occur when all extensions are disabled?: Yes/No
I need to use the extensions SQL DB project & schema compare for this to work

**Comment by kisantia** [comment]
@thomas-svrts can you please confirm that in ADS version 1.42 that create project from database was creating the project with the correct platform version?

**Comment by thomas-svrts** [comment]
I can't revert to the old version anymore. 1.42 isnt compatible with the latest DB projects plugin.
But I'm quite sure it worked before. So maybe related to the recent data studio/DB project recent releases, or something changed on the synapse dedicated pool.

**Comment by SakshiS-harma** [comment]
Hi @thomas-svrts , I am working on a fix and will provide the insiders location once it is ready to test.

**Comment by thomas-svrts** [comment]
@SakshiS-harma Do you already have something to test?

**Comment by SakshiS-harma** [comment]
Hi @thomas-svrts, please download the latest Azure Data Studio version from insiders: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch . Confirm that it is upgraded to v1.44.0 . 
Then, update the Sql database projects extension from the extensions gallery and verify the version is v1.1.0 . This version has the fix for the issue you were facing.
Do let me know if you still face any issues, and I would be happy to help.

**Comment by thomas-svrts** [comment]
I updated to insiders v1.45 and projects extension to v1.1.0.

I created a new project based on my synapse dedicated pool
but when I update fresh project from the same synapse dedicated pool nothing happens. Schema compare windows doesnt even open and no errors

**Comment by thomas-svrts** [comment]
@SakshiS-harma also tried with v1.44 and extension v1.1.0. Same behaviour as above.

**Comment by thomas-svrts** [comment]
![image](https://github.com/microsoft/azuredatastudio/assets/81048302/50cd77e6-c295-4b26-800e-e62961ca5d8d)

**Comment by thomas-svrts** [comment]
I retried. No succes...
screencast is here: https://we.tl/t-ycrewABOEb

**Comment by SakshiS-harma** [comment]
Just to validate, does Schema Compare extension open on its own? Can you also check if it can open from a Sql database context and then for a database in synapse dedicated sql pool?

Also, what does the server outputs for "select @@version" query?

**Comment by thomas-svrts** [comment]
I can open the Schema Compare extension on its own.
But comparing a dacpac with a synapse database never finishes.
This is already running for +60 minutes:
![image](https://github.com/microsoft/azuredatastudio/assets/81048302/a81df9a0-b98e-41bc-9c17-747539825581)

**Comment by thomas-svrts** [comment]
My synapse server version:
Microsoft Azure SQL Data Warehouse - 10.0.20443.0 Mar 14 2023 04:45:46 Copyright (c) Microsoft Corporation

**Comment by SakshiS-harma** [comment]
> I can open the Schema Compare extension on its own. But comparing a dacpac with a synapse database never finishes. This is already running for +60 minutes: ![image](https://user-images.githubusercontent.com/81048302/237687083-a81df9a0-b98e-41bc-9c17-747539825581.png)

Does it finish for a normal database?

**Comment by SakshiS-harma** [comment]
@thomas-svrts can you test it with SSDT as well? Do you see the same behavior there as well?
Do you see any errors in the developer console?

**Comment by thomas-svrts** [comment]
I don't have SSDT.
ADS 1.45 is using a lot of RAM:
![image](https://github.com/microsoft/azuredatastudio/assets/81048302/d35dd5b8-35f5-4d19-8986-36999b37e8e7)

I see the same memory consumption in the last release of SQLpackages CLI.
see last comments in https://github.com/microsoft/azuredatastudio/issues/23060

**Comment by SakshiS-harma** [comment]
Hey @thomas-svrts , hope you are having a good day.

Can you try installing SSDT (it is a free Windows only data tool), and verify if you are still seeing the issue?

If not, then can you please share the dacpacs for the problematic database with me (sakshis@microsoft.com), for further investigation ?

**Comment by SakshiS-harma** [comment]
Hey @thomas-svrts, thanks for your patience with testing this issue.
Can you try to start the "Update project from database" from the Projects context (right click on the project > Update project from database) instead of the ... menu on top right; and see if the original issue is fixed?
