### ISSUE TITLE
New server group button dissapears

### ISSUE THREAD

**Issue by cmpl-giedriusk** [microsoft/azuredatastudio#22941]
Issue Type: <b>Bug</b>

Hi.

New server group button disappears, when Azure view is hidden from Connections panel.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.74GB (16.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.4
profiler|Mic|0.12.2

</details>

**Comment by cheenamalhotra** [comment]
I haven't been able to reproduce this - @cmpl-giedriusk is there a particular sequence of events that leads to this behavior?
Can you consistently reproduce this?

**Comment by cheenamalhotra** [comment]
May I know what Color theme are you using?

cc @aasimkhan30
