### ISSUE TITLE
Unable to login with AAD in Azure Data studio 

### ISSUE THREAD

**Issue by vafe23** [microsoft/azuredatastudio#22951]
- Azure Data Studio Version: 1.43.0 (user setup)
- OS Version: Windows 11 Enterprise build: 22000.1817

Steps to Reproduce:

1. Updated the ADS and try to login
2. There is no pop up for account details but throws Error: error 
3. Deleted account and deleted cache token then uncheck the System Certificate option under application in settings.
4. Restarted the ADS then try to add account then this time new error:  Unable to verify the first certificate.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
Hi @vafe23 

This is likely related to an expired root CA certificate on your system. Could you please try this recommendation:
https://github.com/microsoft/azuredatastudio/wiki/Troubleshoot-Azure-Authentication-Issues#ensure-no-system-ca-certificates-are-expired

**Comment by vafe23** [comment]
@cheenamalhotra 
I have already tried this recommendation as mentioned in my OP, and then only I received the error: Unable to verify the first certificate. If left default settings getting Error: error.
To mitigate this error, you should remove any expired Root CA Certificates or **_disable the setting to not validate system certificates._**

**Comment by cheenamalhotra** [comment]
@vafe23 

Can you confirm which library you're using for Azure authentication? Please ensure you're using MSAL, and if it's MSAL and continues to fail, please upload Azure logs we can use for investigation.

**Comment by vafe23** [comment]
@cheenamalhotra  

I can't find the azure.authenticationLibrary setting to determine the library we are using for Azure authentication, but I did sew this in old version of ADS and I believe then the setting was Azure Active Directory with Universal MFA (AAD).

As requested, I am also attaching the logs.
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11409846/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
Could you please try [the latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and confirm if issue continues to occur?

**Comment by cheenamalhotra** [comment]
Hi @vafe23 

I looked more into the error: `Unable to verify the first certificate` and this is likely related with Strict SSL enabled in your environment, which leads to error if an unauthorized certificate is being validated (applies to `rejectUnauthorized` - [read more](https://github.com/microsoft/vscode/issues/173314)).

To resolve this, you can uncheck `http.proxyStrictSSL` setting in ADS or set it to `false` and that should solve the issue.
<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/b0c79f46-ab9a-46b2-a3bb-d1260dbe7520" width=600 />

Alternatively you can install the self-signed certificates to Root CA certificate store.

Closing as external.
