### ISSUE TITLE
Error when drag-and-drop file in Database Project extension

### ISSUE THREAD

**Issue by nielsvdc** [microsoft/azuredatastudio#22958]
Type: <b>Bug</b>

When trying to move a project file from one folder to another in the Database Projects view using drag-and-drop, I get this error:

"Error when moving file from c:\Users\<username>\source\repos\VDP\DB\DWH\ETL ADF\OWM\BDP\AccountCategory\Programmability\LOAD.BDP_OWM.AccountCategory.sql to \vdp_dwh\ETL ADF\OWM\BDP\AccountCategory\Tables\LOAD.BDP_OWM.AccountCategory.sql.
Error: Script entry 'ETL ADF/OWM/BDP/AccountCategory/Tables/LOAD.BDP_OWM.AccountCategory.sql' does not exist in vdp_dwh.sqlproj, so could not be moved."

The file path in the last line points to the target file, which indeed does not exist yet.
In the non-insider version of Data Studio, moving the file using drag-and-drop doesn't work at all.

Extension version: 1.0.1
Azure Data Studio version: azuredatastudio-insiders 1.44.0-insider (1f3a514c9062d74c2a96c54ec37eecc6d0e93105, 2023-05-02T05:34:11.809Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (15.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

Extension version: 1.0.1
Azure Data Studio version: azuredatastudio-insiders 1.44.0-insider (1f3a514c9062d74c2a96c54ec37eecc6d0e93105, 2023-05-02T05:34:11.809Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.64GB (15.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nielsvdc** [comment]
I get the same error message when trying to rename a file

**Comment by nielsvdc** [comment]
Seems to be fixed in version 1.44.0-insider

**Comment by kisantia** [comment]
closing since it appears to be fixed in insiders already
