### ISSUE TITLE
Opening dashboard from 2 connections against same server doesn't update connection string

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#22968]
- Azure Data Studio Version: 1.43.0, Insiders
- OS Version: Windows 11

Steps to Reproduce:

1. Open first connection against server with 'Integrated' authentication
2. Open a second connection against same server with 'SqlLogin' authentication
3. Right Click > Manage on first connection
4. Right Click > Manage on second connection (redirects to same dashboard)
5. Click "New Query" or "New Notebook" on Dashboard

Expected:
Connection string of the last "Right Click> Manage" action is used for opening new query/notebook.

Actual:
Connection string still points to first connection and doesn't get updated on step 4.

Description of Issue:
This is likely a design decision in Dashboards that connection string doesn't get updated for open tabs, but redirecting users to same open dashboard even when connection strings don't match leads to this behavior. 

Impact:
This causes confusions to users as connection properties are not updated, and specially with many tabs open, if users are being redirected to old open tabs, they don't get connection properties updated with what they intended to see.

**Comment by smartguest** [comment]
Closing issue as it no longer reproduces.
