### ISSUE TITLE
RESTORE DB on Managed Instance doesn't work

### ISSUE THREAD

**Issue by jovanpop-msft** [microsoft/azuredatastudio#2296]
Issue Type: <b>Bug</b>

Connect to managed instance and restore database - restore flow doesn't work.
GENERAL tab
1. MI doesn't supports restore from the database/file - please put URL as source.
2. Cannot choose the file path. It selects path for automated backups https://wasd2prodwcus1abakmi55.blob.core.windows.net/managedserverbac-b48544e2-eaa6-4280-a837-05400712d912/backup and then returns "An error occurred while loading the file browser." error.
2.1 Wishlist 1- could backup file path be somehow pre-populated the list with URL from credentials that start with https: because these are credentials for blob storages that will be used for restore.
3. When I return back from select file path dialog I'm getting some Database dropdown that is not loaded - probably bug.
4. Target database cannot  be dropdown with existing databases because MI don't support restore into existing database. User must enter new database name in text box.
5. Not sure what is Restore to and Restore plan - they are empty.
FILES tab
1. Remove it because we are not supporting relocation of files. in restore syntax you cannot specify file names because we are automatically relocating files on internal paths.
OPTIONS tab
1. Remove because RESTORE WITH options are not supported.

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.97GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2

</details>

**Comment by sk8federico** [comment]
+1

**Comment by Charles-Gagnon** [comment]
This should be fixed with https://github.com/microsoft/azuredatastudio/pull/19244, the latest insiders builds have this improvement and it will be included in the next stable release (1.37)
