### ISSUE TITLE
BACKUP flow on Managed Instance don't work

### ISSUE THREAD

**Issue by jovanpop-msft** [microsoft/azuredatastudio#2297]
Issue Type: <b>Bug</b>

Connect to managed instance, select a database and try to backup it:
1. Backup type must be full - we are not supporting differential/log user backups
2. COPY_ONLY is mandatory
3. I tried to add backup files and it put blob url file path for automated backup. this is wrong because backup can be done only on user's blob storage. Maybe you can list backups from credentials that start with https://
4. Remove transaction log check boxes they are not supported

SQL Operations Studio version: sqlops 0.31.4 (e026ab85a72c190cc4ccc834503aa9fe36dd6407, 2018-07-18T02:14:21.826Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (5.57GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2

</details>

**Comment by Charles-Gagnon** [comment]
This should be fixed with https://github.com/microsoft/azuredatastudio/pull/19244, the latest insiders builds have this improvement and it will be included in the next stable release (1.37)
