### ISSUE TITLE
[SQL DB Projects] "large extension state" warning in console 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#22987]
Seeing this show up in the console with the latest VS Code when I create a project from a database

`WARN [mainThreadStorage] large extension state detected (extensionId: docsmsft.docs-markdown, global: true): 2128.76171875kb. Consider to use 'storageUri' or 'globalStorageUri' to store this data on disk instead.`

**Comment by SakshiS-harma** [comment]
Not related to projects extension, but docs-markdown extension.
