### ISSUE TITLE
資料表中無法輸入中文

### ISSUE THREAD

**Issue by tin0723** [microsoft/azuredatastudio#22985]
Issue Type: <b>Feature Request</b>

如標題

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:12:44.872Z)
OS version: Darwin arm64 21.6.0
Restricted Mode: No
Preview Features: Enabled

**Comment by kburtram** [comment]
@tin0723 sorry, but we are only able to provide support in English on this repo.  You can try to run the text through a translation service prior to posting and that may be sufficient for us to understand the issue.  Thanks!
