### ISSUE TITLE
Silent failure for updating value for a SQLCMD variable that is used by a database reference

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#22992]
Repro:
1. Create new project
2. Add a reference to a nuget/dacpac/sqlproj (not system db).  Give it a SQLCMD variable name/value.
3. Update value for the SQLCMD variable

Expected: success

Reality:
Silent failure in VS Code, error in ADS:
![image](https://user-images.githubusercontent.com/1609827/236541069-ea008171-77fa-440f-a293-1bdd3b220bd8.png)

If you delete the database reference first (ahem #22988), this can be updated/deleted just fine.

**Comment by Benjin** [comment]
Also occurring in ADS, except instead of silent failure for rename, it displays an error:
![image](https://user-images.githubusercontent.com/1609827/236541069-ea008171-77fa-440f-a293-1bdd3b220bd8.png)

**Comment by erpett** [comment]
fix is in release branch
