### ISSUE TITLE
Failed to expand node

### ISSUE THREAD

**Issue by karlgreenwood** [microsoft/azuredatastudio#23009]
Issue Type: <b>Bug</b>

Open connection to server
Expand node
Wait for child items to appear
Expand Databases
Wait for child items to appear
Receive errors

Error 1 - Error: Failed to expand node
Error 2 - Node expansion timed out for node <server name>

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (16.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|0.2.9
azuredatastudio-oracle|Mic|0.1.2
dacpac|Mic|1.13.0
import|Mic|1.5.4
net-6-runtime|Mic|1.1.0
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.0.1

</details>

**Comment by aasimkhan30** [comment]
This PR #22955
