### ISSUE TITLE
Unable to disable previous/next button in middle pages of wizard

### ISSUE THREAD

**Issue by tanyaranjan1995** [microsoft/azuredatastudio#23023]
- Azure Data Studio Version: 1.43.0
- OS Version: Windows 10
![image](https://user-images.githubusercontent.com/121925167/236745743-db8b7a0a-7477-46cf-bd23-18fa949d2fe2.png)
In the attached image, a process is in progress, I wanted to disable the back button so that the user cannot navigate to other pages while the process is ongoing. The back is not getting disabled.
Steps to Reproduce:
1. Create multiple pages wizard in the ADS extension
2. Suppose on the second page we want to disable the previous button until some requirement is met. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
@tanyaranjan1995 you can use `wizard.nextButton.enabled = false` or `wizard.backButton.enabled=false`

![image](https://user-images.githubusercontent.com/13777222/236875302-b991b016-9c43-4466-82ce-d6f843254d6b.png)

please let me know if it doesn't work.
