### ISSUE TITLE
Deselect the last selection of other table in case of multiple tables

### ISSUE THREAD

**Issue by tanyaranjan1995** [microsoft/azuredatastudio#23022]
- Azure Data Studio Version: 1.43.0
- OS Version: Windows 10
![image](https://user-images.githubusercontent.com/121925167/236743448-9a104406-adbe-40c8-8c00-56d7b6f90a25.png)
Steps to Reproduce:
1.  There are 5 tables in the attached image. On the left is Instance Table & Database Table and in the center is Features Table & Server Settings Table and on the right is Details Section.
2. The requirement is to deselect the selection of instance table when a row of database table is selected and vice versa. Similarly to deselect the selection of features table when a row of server settings table is selected and vice versa. This is to enhance exactly for which instance/database the information are present in the details section on the right. Currently with are 4 tables data selected it create confusion.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by alanrenmsft** [comment]
hi @tanyaranjan1995 , this is supported, you can do it by assigning an empty array to the `selectedRows property`: `table.selectedRows = [];`
