### ISSUE TITLE
ADS Cannot access local file system for .bak files during restore

### ISSUE THREAD

**Issue by craigs100** [microsoft/azuredatastudio#23054]
Issue Type: <b>Bug</b>

Install ADS on Linux MInt
Create new DB
Try to restore to new DB via ADS's Restore wizard from Backup File

Find path to file stuck at /var/opt/mssql/data/   No access to local user file system.  

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:08:07.209Z)
OS version: Linux x64 5.15.0-71-generic
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 1, 1|
|Memory (System)|31.02GB (11.37GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details>

**Comment by Charles-Gagnon** [comment]
This is working as intended, the RESTORE command is ran from the context of the SQL engine so it doesn't (usually) have access to local storage so the file browser reflects that.


If you have your bak file in a shared location the server can access you can paste that path directly into the file path box and it should work. Let us know if you have any issues doing that.
