### ISSUE TITLE
SqlCmdVariables are not getting populated at publish time

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#23079]
Occurring with RC builds

<img width="907" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/1609827/204f3285-dd24-4b52-b39e-81ffbdb5550c">

**Comment by Benjin** [comment]
Appears to be stemming from `JSON.stringify()` not being able to handle `Map`s natively, so no sqlcmdvars are getting included in the JSON serialization to SqlToolsService.

**Comment by kisantia** [comment]
verified this is fixed in the latest ADS RC build
