### ISSUE TITLE
Support for Team Foundation Server

### ISSUE THREAD

**Issue by vinodj** [microsoft/azuredatastudio#2307]
Does SQL Operations Studio support source control with Team Foundation Server?

**Comment by kburtram** [comment]
@vinodj thanks for the suggestion!  We're considering including this support in feature release.

By the way, have you tried using the VS Code TFS extension in SQL Ops Studio?  You can get it from https://marketplace.visualstudio.com/items?itemName=ms-vsts.team then click `Download Extension` to download the VSIX, then click `File->Install Extension from VSIX Package` to side-load the extension.
