### ISSUE TITLE
Invalid tree item error in console for modelview tree icons

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23084]
Seeing this error in the console when displaying the Data Virtualization tree : 

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/068337c3-1892-443e-9bfa-82efc2417492)

This is likely a general issue with all ModelView trees, should investigate the impact of this and whether it's something we can/should fix

**Comment by cheenamalhotra** [comment]
Duplicate of #22865

**Comment by Charles-Gagnon** [comment]
Ah, thanks @cheenamalhotra 😄
