### ISSUE TITLE
Suggestion: Add horizontal scrollbar for Explorer widget - Can't see right most characters of names of "searched for" database objects

### ISSUE THREAD

**Issue by AndyAatOCC** [Microsoft/azuredatastudio#231]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. Open a new connection to a database with a lot of stored procedures with long names.
2. Scroll down the central "Search" panel to the stored procedures.

You will be unable scroll horizontally, unable to right justify the list and unable to widen the search box and so will be unable to distinguish things with names that only differ after 30 or so characters (very common on our projects).

**Comment by SebastianPfliegel** [comment]
@AndyAatOCC, I agree that there should be a scrollbar, but you're not correct about widening the search box. There is a possibility to do so. Open the user defined settings with **Ctrl + Comma** and place this code on the right side of the screen:

```json
  "dashboard.database.widgets": [
    {
      "name": "Tasks",
      "gridItemConfig": {
        "sizex": 1,
        "sizey": 1
      },
      "widget": {
        "tasks-widget": {}
      }
    },
    {
      "gridItemConfig": {
        "sizex": 2,
        "sizey": 2
      },
      "widget": {
        "explorer-widget": {}
      }
    }
  ],
```

I changed property *sizex* to 2 for the explorer-widget. Hope this is at least a decent workaround for you :)

**Comment by AndyAatOCC** [comment]
Thanks. That does indeed work.

**Comment by SebastianPfliegel** [comment]
Glad I could help :)
Issue should stay open though for the scroll bar.

**Comment by erickangMSFT** [comment]
@AndyAatOCC @SebastianPfliegel Thanks! I update the title to be specific about the horizontal scrollbar ask.
