### ISSUE TITLE
Remove BDC provided book from Books viewlet.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#23107]
Steps to Reproduce:

1. Open ADS and navigate to Books view
2. On the Provided Books view pane, expand the options -> Sql Server 2019 Guide shows up.

The BDC book contribution was removed in an earlier PR, so currently this menu option does nothing and appears broken. This should be removed to avoid confusing customers.

**Comment by Charles-Gagnon** [comment]
@MaddyDev Please open a port
