### ISSUE TITLE
server list not refreshing view to show server in different group

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#23102]
Type: <b>Bug</b>

I managed to get my server tree in a bad state after attempting to drag-n-drop a database connection from 1 group to another. 
Now when I click edit on the database, it reflects the new group in the connection info, but even if I hit connect again it stays in the wrong/old group visually.

Azure Data Studio version: azuredatastudio-insiders 1.45.0-insider (0158bd986199bab56b4ceda71f53a84a5e101568, 2023-05-11T05:39:43.158Z)
OS version: Darwin arm64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|8, 4, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
copilot|Git|1.83.41
asde-deployment|Mic|0.4.1
dacpac|Mic|1.13.0
import|Mic|1.5.4
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.1.0
indent-rainbow|ode|8.2.2

(1 theme extensions excluded)

</details>

![2023-05-11_11-06-06 (1)](https://github.com/microsoft/azuredatastudio/assets/12227241/a9be2b66-8060-4bce-946c-f82e418b964d)

Once I close ADS and reopen, the server is reflected in the correct grop

**Comment by aasimkhan30** [comment]
@dzsquared, are you seeing some console errors?

**Comment by cheenamalhotra** [comment]
Closing as it could be a one-off scenario.
Not enough details to investigate why tree went into bad state.

Let us know if you experience the issue again.
