### ISSUE TITLE
Database size seems to be incorrect

### ISSUE THREAD

**Issue by meet-bhagdev** [Microsoft/azuredatastudio#2310]
- SQL Operations Studio Version:
August Preview Insiders Build 0.32.5

Steps to Reproduce:

- Log into SQL Ops studio and connect to a SQL DW/SQL DB database
- Go to the overview page and visualize the database size. In my case i had a 10TB database, and the widget reported that it is 8MB in size. This seems inaccurate.

![image](https://user-images.githubusercontent.com/11928821/44530253-4a133480-a6ee-11e8-84b5-f5b5e2dab548.png)

@yualan @vickyharp as FYI

**Comment by kburtram** [comment]
@meet-bhagdev that chart is executing the below query.  If possible, could you please confirm the output of this query on this server?  The chart shouldn't be show on Azure DB if I recall correctly, so I wonder if this an Azure DW specific issue.

```SQL
with fs
as
(
    select database_id, type, size * 8.0 / 1024 size
    from sys.master_files
)
select top 10
    name,
    (select sum(size) from fs where type = 0 and fs.database_id = db.database_id) DataFileSizeMB,
    (select sum(size) from fs where type = 1 and fs.database_id = db.database_id) LogFileSizeMB
from sys.databases db
where database_id > 4
order by DataFileSizeMB desc
```
