### ISSUE TITLE
Dacpac Deploy when no SQLCMD variables are defined silently fails

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#23111]
Occurring because `Object.fromEntries(sqlCmdVars)` throws when `sqlCmdVars` is undefined.  Will also need updating in vscode-mssql. Introduced by https://github.com/microsoft/azuredatastudio/pull/23082, which was originally a fix for SQLCMD variables not getting passed to STS

**Comment by kisantia** [comment]
verified this is fixed in the latest RC build
