### ISSUE TITLE
Default saveType for untitled notebook is JSON

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#23117]
Version: 1.44.0-rc1 (user setup)
Commit: c44ecf56f262ed8e7fbd81a6f4620dd3fdcf944b
Date: 2023-05-11T06:52:16.039Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.23451

Steps to Reproduce:

1. Create new notebook
2. Save notebook 

<img width="559" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/34872381/3a10d1c5-ae3d-4d89-adaa-b937ac2b0558">

**Comment by chlafreniere** [comment]
@barbaravaldez does the file still get saved as .ipynb and save/open correctly?

**Comment by barbaravaldez** [comment]
@chlafreniere this issue is still in main

**Comment by corivera** [comment]
The file extensions are listed next to JSON now (including ipynb) and VS Code uses this same behavior for saving their notebooks. I'll close this for now until we get any feedback to change it.
