### ISSUE TITLE
Server Group styling looks distorted for Async Server Tree

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23129]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/9b1bc5be-353c-4273-82a3-6c9e09723a27)
(only for Async Server Tree)

**Comment by aasimkhan30** [comment]
@cheenamalhotra . Thats's by design due to contrast issue when highlighting search results

**Comment by cheenamalhotra** [comment]
Can we try to fix the contrast issue by selecting colors more carefully - for both dark/light themes?

**Comment by aasimkhan30** [comment]
Closing as it is by design and not a bug
