### ISSUE TITLE
Unable to add account in Azure data Studio

### ISSUE THREAD

**Issue by heramb-joshi** [microsoft/azuredatastudio#23140]
- Azure Data Studio Version: 1.43.0 (user setup)
- OS Version: ADS OS Version Windows_NT x64 10.0.22621
- Machine OS version: Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎2/‎6/‎2023
OS build	22621.1555
Experience	Windows Feature Experience Pack 1000.22640.1000.0

Steps to Reproduce:

1. After successfully installing ADS, I face issue while linking my enterprise account.
2. The error doesn't contain any error codes. Attaching error snapshot.
3. I tried disabling VPN. But the issue persists.

Appreciate of you can provide  solution.

Does this issue occur when all extensions are disabled?: Yes/No

![Azure Data Studio - Error - 05152023](https://github.com/microsoft/azuredatastudio/assets/18359658/09063272-e5c2-444a-8fd6-7bd52fbc0bb2)

**Comment by cheenamalhotra** [comment]
Hi @heramb-joshi 

Please try recommendation from here:
https://github.com/microsoft/azuredatastudio/wiki/Troubleshoot-Azure-Authentication-Issues#ensure-no-system-ca-certificates-are-expired
