### ISSUE TITLE
Connection Failure to Mongo account

### ISSUE THREAD

**Issue by sailorjack** [microsoft/azuredatastudio#23146]
Issue Type: <b>Bug</b>

I tried to connect my Azure Cosmos DB (Mongo DB) following the instructions in https://learn.microsoft.com/de-de/sql/azure-data-studio/quickstart-azure-cosmos-db-mongodb?view=sql-server-ver16.
I got an connection error with the following message:
"Failed to connect: getaddrinfo ENOTFOUND eta-db-2.mongo.cosmos.azure.com"
Same issue occurred while using the connection string instead.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.1.2
azcli|Mic|1.8.0
azure-cosmosdb-ads-extension|Mic|0.3.3
azuredatastudio-oracle|Mic|0.1.2
dsct-oracle-to-ms-sql|Mic|0.4.1
net-6-runtime|Mic|1.1.0
schema-compare|Mic|1.18.0
sql-database-projects|Mic|1.0.1
mongodb-vscode|mon|0.9.3

</details>

**Comment by cheenamalhotra** [comment]
FYI, I get this error from Cosmos DB extension, when the server URL is incorrect (tested garbage value) or unavailable.

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/6f6736a3-ea6f-41f4-b79d-73993a67abd7" width=500 />


Please review your server endpoint, and if it doesn't work, let us know and we'll transfer the issue to respective extension repository. 

cc @languy

**Comment by sailorjack** [comment]
> FYI, I get this error from Cosmos DB extension, when the server URL is incorrect (tested garbage value) or unavailable.
> 
> <img alt="" width="500" src="https://user-images.githubusercontent.com/13396919/238791908-6f6736a3-ea6f-41f4-b79d-73993a67abd7.png">
> Please review your server endpoint, and if it doesn't work, let us know and we'll transfer the issue to respective extension repository.
> 
> cc @languy

Here is how I did it:
1. "Add new connection"
2. in the connection pane I have choosen the Cosmos DB I want to connect to from the list shown
3. ADS is automatically retrieving the information and doing an auto-entry into the connection details panel below (no manual adjustment by me)
4. clicking the connect button gives me the error message below.
![image](https://github.com/microsoft/azuredatastudio/assets/18065774/33bc386e-06a6-47dc-8c70-9b65c2919a24)

Error message:
![image](https://github.com/microsoft/azuredatastudio/assets/18065774/8bcef804-3cf1-49e3-9c65-4748fabd3906)

So I do not know how I can even have had an impact on the outcome.

Alternatively, I have tried to setup a connection with the Primary connection string for the Cosmos DB - got the same error message.

Please advice.
Thanks, Alex

**Comment by sailorjack** [comment]
> We need more info to debug your particular issue. If you could attach your logs to the issue (ensure no private data is in them), it would help us fix the issue much faster. First open the Settings page, find the `Azure: Logging Level` setting and change that to `All` then restart ADS and repro your issue.
> 
> Next there are two types of logs to collect:
> 
> **Console Logs**
> 
> * Open Developer Tools (Help -> Toggle Developer Tools)
> * Click the **Console** tab
> * Click in the log area and select all text (CTRL+A)
> * Save this text into a file named console.log and attach it to this issue.
> * Developer Tools can be closed via Help -> Toggle Developer Tools
> 
> **Application Logs**
> 
> * Open command palette (Click **View** -> **Command Palette**)
> * Run the command: **`Developer: Open Logs Folder`**
> * This will open the log folder locally. Please zip up this folder and attach it to the issue.

Here is the output:
[ADS_connection_error_Log_out.txt](https://github.com/microsoft/azuredatastudio/files/11497352/ADS_connection_error_Log_out.txt)

**Comment by languy** [comment]
@sailorjack This error indicates that the javascript Mongo client (which the extension uses internally) is not able to connect. It could be a network problem (DNS, firewall, etc) or something related to your Cosmos DB account configuration (private endpoint, vnet, etc). 
Can you try to `ping eta-db-2.mongo.cosmos.azure.com` ? If you can ping it, then please create a ticket in the Azure portal from your Cosmos DB account under "Support + Troubleshooting" (last item at the bottom) so we can better assist you. Thanks.

**Comment by cheenamalhotra** [comment]
Hi @sailorjack 

Closing this issue in reference to https://github.com/Azure/azure-cosmosdb-ads-extension/issues/85, please follow up with the team in the extension repository once you've gathered details requested [above](https://github.com/microsoft/azuredatastudio/issues/23146#issuecomment-1551662967).
