### ISSUE TITLE
Delay in executing

### ISSUE THREAD

**Issue by veeresh224** [microsoft/azuredatastudio#23145]
Issue Type: <b>Bug</b>

Most of the times query execution will take more time to initiate

Azure Data Studio version: azuredatastudio 1.43.0 (Universal) (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:12:47.777Z)
OS version: Darwin arm64 22.4.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by alanrenmsft** [comment]
add logging in July.
