### ISSUE TITLE
Incorrect database shown in Backup/Restore dialog title

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#23158]
When using back up or restore for certain databases, I see the title on the  dialog with wrong name. Action is still performed correctly.
![image](https://user-images.githubusercontent.com/69922333/236584043-1ec6fa73-ec23-40c1-9383-f30b4e0dacd4.png)
![image](https://user-images.githubusercontent.com/69922333/236584055-adac6681-363b-49b8-9732-ddf43d29ef3c.png)

**Comment by Charles-Gagnon** [comment]
Can repro - only for non-MSSQL databases though.

**Comment by Charles-Gagnon** [comment]
@nasc17 This will be fixed in insiders/dev and then go out for the July release.
