### ISSUE TITLE
Folding incorrectly includes trailing blank lines

### ISSUE THREAD

**Issue by asherber** [microsoft/azuredatastudio#23167]
Issue Type: <b>Bug</b>

The code folding algorithm incorrectly includes blank lines at the end of a block to be folded.

Here's some sql in which I have a couple of blank lines between one block and the next:

![image](https://github.com/microsoft/azuredatastudio/assets/5248041/8ba02328-edae-4ba0-bffb-59022293953e)

As you can see, the line drawn next to the indented block already includes the blank lines under the inserted values. And when I fold this block, those lines get folded as well:

![image](https://github.com/microsoft/azuredatastudio/assets/5248041/566b24a3-f777-4186-a4b9-e78161d84fa3)

Trailing blank lines should not be included in a folding block, so that vertical whitespace can be used as a delimiter.

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:14:27.236Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|16.00GB (5.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.5.3

</details>

**Comment by alanrenmsft** [comment]
@Charles-Gagnon do you know how does this work? is this language service related?

**Comment by alanrenmsft** [comment]
This seems to be a vscode feature: https://code.visualstudio.com/docs/editor/codebasics#_folding, let me take a look and see whether it is customizable.

**Comment by Charles-Gagnon** [comment]
Not deeply. There's customization for folder in the grammar files (https://github.com/microsoft/azuredatastudio/blob/514b4546436acc838d1ce7af3fc4e829d155c1ca/extensions/sql/language-configuration.json#L27) - but I think this might just be the default folding logic. Possibly related to the indentation?

**Comment by Charles-Gagnon** [comment]
Yeah, this seems to just be native folding logic. You see the same behavior with just a normal text file

![FoldingIndent](https://github.com/microsoft/azuredatastudio/assets/28519865/c96083ed-42aa-49c5-aec5-3bd5cb283550)

**Comment by Charles-Gagnon** [comment]
Yup, that does it. I'll get a PR out for updating this.

@asherber Does this look like what you were expecting?

![SqlFoldingIndent](https://github.com/microsoft/azuredatastudio/assets/28519865/15457c72-6551-4ee5-afdc-838827a52fd0)

**Comment by asherber** [comment]
@Charles-Gagnon Yes, thanks!
