### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by sahalMoidu** [microsoft/azuredatastudio#23180]
Issue Type: <b>Bug</b>

I almost experience connection issue when accessing remote sql server on my mac,although i am able to connect to the same server using Sql server management studio using windows on virtual box on the same machine.

Sometimes the message would be 
Total execution time: 00:00:00

And sometimes the error msg which states TCP related connection issue.

Whatever be the message SSMS on windows does not have any connection is issue whatever the timeline be. 

I tried changing internet connections and still the problem persists

Azure Data Studio version: azuredatastudio 1.43.0 (b790d700898b1095d83e62f0de14678a58222520, 2023-04-10T23:12:47.777Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (1.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.4
query-history|Mic|0.5.3
schema-compare|Mic|1.18.0
extra-sql-script-as|pac|0.3.0
ADS-add-columns|sof|0.0.12

</details>

**Comment by cheenamalhotra** [comment]
Hi @sahalMoidu 

Can you please provide logs for investigation as per instructions above?

**Comment by cheenamalhotra** [comment]
Closing as not enough info available to investigate error.
