### ISSUE TITLE
Account picker dialog spins forever if no clouds are selected

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23208]
If a user unselects all "Enable cloud" settings and then opens the account picker dialog then it sits there with a "Loading accounts" spinner forever, without displaying any error. (there is one in the console though)

We should show an error to the user in this case so they know how to fix it (or even better don't let them unselect ALL clouds, always requiring at least one be selected)

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/e14cf739-8bf6-48a3-b81e-5a0ac90856de)

**Comment by Charles-Gagnon** [comment]
Looked into this a bit since I was curious why the "no-floating-promises" rule wasn't catching this, and it's because this is being called through an event handler. 

https://github.com/microsoft/azuredatastudio/blob/514b4546436acc838d1ce7af3fc4e829d155c1ca/extensions/azurecore/src/azureResource/tree/connectionDialogTreeProvider.ts#L33

We're calling getAllAccounts here (and correctly awaiting it), but then that's throwing the "No account providers registered" error on https://github.com/microsoft/azuredatastudio/blob/514b4546436acc838d1ce7af3fc4e829d155c1ca/src/sql/workbench/api/common/extHostAccountManagement.ts#L67 So the await above rejects, but there's nothing handling that error. One possible fix would be to make the event handle catch any errors itself and then handle them appropriately.

**Comment by cssuh** [comment]
fixed in #24004
