### ISSUE TITLE
Add support for custom cloud providers

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23205]
It maybe useful to allow user to provide settings for their cloud provider (one or multiple) when authenticating with AAD, by accepting below info:
- Cloud Name, e.g. "Azure Custom Cloud"
- Host URL: e.g. 'https://login.microsoftonline.com/',
- Microsoft resource endpoint: e.g. 'https://management.core.windows.net/',
- Graph resource endpoint: e.g. 'https://graph.microsoft.com/',
- ARM resource endpoint: e.g. 'https://management.azure.com/',
- and so on.. for all resources.

The cloud owners can authorize ADS' app ID as needed and enable authentication support on their end, to bring experience similar to SSMS:

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/0a06f0a3-8540-4d6a-b6a0-06e5ecc29387)

**Proposed solution:**
New setting is introduced that accepts JSON object array for provider settings and if that's provided, the clouds gets appended to the list of clouds supports by ADS.

**Comment by Charles-Gagnon** [comment]
While you're at it, refactoring the cloud settings to not be checkboxes for enabling each cloud would be fantastic. Choosing the current cloud from a list makes a lot more sense given that we only allow one at a time anyways.

**Comment by cheenamalhotra** [comment]
We do allow and work with multiple clouds btw. Users get to choose which cloud to use for adding account from selector.

**Comment by Charles-Gagnon** [comment]
Oh neat, somehow I missed that. Carry on then!
