### ISSUE TITLE
Save As features not working

### ISSUE THREAD

**Issue by wuerapop** [microsoft/azuredatastudio#23214]
Type: <b>Bug</b>

Steps:
- Ran a query on a Synapse serverless SQL pool
- Once I got the results, clicked on Save As Excel
- Saving process hanges, notification window never stops saying "Saving file..." and the progress bar just keeps moving.

I did the same with Save As CSV and got same behavior. I noticed an Excel file is created but I cannot open it, get an error related to extension being wrong.

![image](https://github.com/microsoft/azuredatastudio/assets/134632093/e70e4df5-f23e-40db-9f21-b39d84a6ac56)
![image](https://github.com/microsoft/azuredatastudio/assets/134632093/1121c7bd-151d-4f61-9b7c-4e81aeffe41d)
![image](https://github.com/microsoft/azuredatastudio/assets/134632093/f6416e30-a2ab-46e5-b710-12d38b272ed1)

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.59GB (8.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
azuremonitor|Mic|0.1.9
kusto|Mic|0.5.8
machine-learning|Mic|0.12.0
query-history|Mic|0.5.3
sql-dw|Mic|0.0.1
azdata-sanddance|msr|4.0.1

</details>

**Comment by alanrenmsft** [comment]
@wuerapop how many rows/columns are you trying to export?

**Comment by wuerapop** [comment]
6 columns and ~ 1.2M rows. I remember exporting more data in the past with no issues.

**Comment by alanrenmsft** [comment]
@caohai could you please take a look?

**Comment by alanrenmsft** [comment]
@wuerapop The save as Excel operation will eventually fail because the limitation of Excel: https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3, I've just added a check in Azure Data Studio so that you will be prompted immediately if the size exceeds the limit. The error you saw is mostly because the serialization is only partially done.

I tried to save the results as XML and it took about a minute or 2 to export 1.2+ million rows and 48 columns. are your columns mostly long strings?

**Comment by wuerapop** [comment]
Hi @alanrenmsft, query returns 2 datetime, 2 nvarchar(4000), and 2 integer. The nvarchar are always 36 long.

**Comment by alanrenmsft** [comment]
@wuerapop could you please restart ADS and try the save as CSV scenario again, I tried with 2 million rows and it eventually succeeded.

**Comment by wuerapop** [comment]
@alanrenmsft, it did work. I exported as CSV 2.75M rows and 11 columns. File was opened by ADS when ready.

**Comment by alanrenmsft** [comment]
Thanks for confirming.

**Comment by wuerapop** [comment]
Thanks @alanrenmsft for the help. I also tried Save As Excel to check I get the warning you added, but I did not. Rows are the same, 2.75M.

![image](https://github.com/microsoft/azuredatastudio/assets/134632093/6a1ebaca-28d7-44df-889c-a1476901f2e5)

**Comment by alanrenmsft** [comment]
I guess you are using the stable build, the change I made will be released in next stable release, currently it is available in the insiders build: https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch

![image](https://github.com/microsoft/azuredatastudio/assets/13777222/ee6b9972-26ef-4d8f-a26b-0ddf7a3c953a)

**Comment by wuerapop** [comment]
This is what I have. I think I will wait until it gets released. I am aware of the limitation now, so I will not try that option now.

Version: 1.44.1 (system setup)
Commit: 8f53a316fa00a98264f1ab119641cd540b5af25c
Date: 2023-06-01T02:12:48.765Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by alanrenmsft** [comment]
@wuerapop yep, you are using the latest stable build.
