### ISSUE TITLE
Sql Authentication Provider breaks login

### ISSUE THREAD

**Issue by scottrudy** [microsoft/azuredatastudio#23210]
- Azure Data Studio Version: 1.44.0
- OS Version: Version 22H2 (OS Build 19045.2965)

Steps to Reproduce:

1. Upgrade from version 1.43.0 to 1.44.0
2. Try to login to a database using "Azure Active Directory - Universal with MFA support"
3. Get message, Invalid email address format for user: [_Department)_] received for Azure Active Directory authentication.
    * Important: the display name of the user is in the format _"LastName, FirstName :(Role - Department)"_
    * The email address is in the format firstname.lastname@domain.com and the UPN is in the format account@otherdomain.com

Does this issue occur when all extensions are disabled?: Yes

I'm guessing this has to do with the display name having a dash. I imagine Studio is trying to get the UPN for login by looking for the first "-" and it should be looking for the last instance of the "-" in that string. Note that [disabling SQL Authentication Provider](https://learn.microsoft.com/en-us/sql/azure-data-studio/connect?view=sql-server-ver16#sql-authentication-provider) allows for a workaround.

[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11566598/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
I believe this is a special scenario and can be fixed by ensuring we capture the last index of '-'. Thanks for letting us know!

You may continue to use workaround in the meantime.

**Comment by scottrudy** [comment]
I did the steps for logging anyway, but even after encountering the error the `Azure Accounts.log file` is empty.

**Comment by cheenamalhotra** [comment]
You may need to reload Azure Data Studio to allow setting to take effect.

**Comment by darknoon29** [comment]
Same issue on my side with an email account with the following format: xxxx-yyyyyyyyy@tenant.onmicrosoft.com
