### ISSUE TITLE
No Way to Refresh Intellisense

### ISSUE THREAD

**Issue by sivan-koren** [microsoft/azuredatastudio#23218]
Type: <b>Bug</b>

I've tried setting various keyboard shortcuts to refresh intellisense. They don't work. The only workaround I can find is to disconnect and reconnect.

Additionally, it seems to cause the connection to the server to hang. I believe this becuase If I try to refresh intellisense using the keyboard shortcut FIRST, and THEN attempt to disconnect and reconnect, I can't reconnect. The connection dialoge just spins forever. Exiting ADS and reopening resolves that issue. The issue doesn't present if reconnecting WITHOUT first attempting the keyboard shortcut to refreesh intellisense.

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900 12-Core Processor              (24 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.4
powershell|ms-|2022.12.1
profiler|Mic|0.12.2
code-settings-sync|Sha|3.4.3

</details>

**Comment by kburtram** [comment]
@sivan-koren have you tried to use the "Refresh IntelliSense" command from the Command Palette?  I just tried on 1.44 connected to Azure SQL DB instance and worked as expected.

![image](https://github.com/microsoft/azuredatastudio/assets/599935/d6704744-0252-424c-b835-ca72d44652e3)

**Comment by sivan-koren** [comment]
I just tried and it seemed to work. And then I disconnected and tried another server and the keyboard shortcut worked also, so maybe it's fixed? I don't remember updating though, so it could also be intermittent. I'll update if I run into this again.
