### ISSUE TITLE
SQL Server Import: With the latest Azure Data Studio version import fails

### ISSUE THREAD

**Issue by peterbud** [microsoft/azuredatastudio#23220]
Type: <b>Bug</b>

1. Connect to an Azure SQL server using Azure AD authentication
2. Select "Import Wizard"
3. Select a CSV file to import
4. Import fails with the following message:
```
✗ System.InvalidOperationException: Cannot set the AccessToken property if 'UserID', 'UID', 'Password', or 'PWD' has been specified in connection string.
at Microsoft.Data.SqlClient.SqlConnection.CheckAndThrowOnInvalidCombinationOfConnectionOptionAndAccessToken(SqlConnectionString connectionOptions)
at Microsoft.Data.SqlClient.SqlConnection.set_AccessToken(String value)
at Microsoft.SqlServer.Prose.Import.BcpProcess.CreateTableAndInsertDataIntoDb(String connectionString, Int32 batchSize, String azureAccessToken)
```

I'm wondering what kind of UserID, UID the error message is referring to, as I'm connecting using AAD authentication. Also Interestingly this was working with the previous Azure Data Studio. Also I can connect to the Azure SQL Database using Azure Data Studio, and can query/manipulate the data. Only the SQL Server Import extension stopped working.

Extension version: 1.5.4
Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cheenamalhotra** [comment]
This was addressed with https://github.com/microsoft/azuredatastudio/issues/22999, but looks like the extension hasn't been updated.
@aasimkhan30 can you look into it?

**Comment by Charles-Gagnon** [comment]
@peterbud We just released a new version of the extension, which should contain the fix for this issue. Please update to 1.5.5 and let us know if you're still seeing issues!

**Comment by peterbud** [comment]
Thanks, it works!
