### ISSUE TITLE
When doing a commit in resource control, it keeps on spinning and never ands

### ISSUE THREAD

**Issue by mcronaldp** [microsoft/azuredatastudio#23235]
- Azure Data Studio Version: 1.44
- OS Version: Windows 10

Steps to Reproduce:

1. I create a branch from the master branch
2. I make some adjustments, in this branch, in this case i addes a stored procedure.
3. I press on Commit. Then it keeps on spinning.

I allready closed the program, restarted the programm, cloned the repository again and uninstalled and installed data studio again, but without positive result.

Does this issue occur when all extensions are disabled?: Yes/No yes (i don't use extensions

**Comment by kburtram** [comment]
@mcronaldp I wasn't able to repo this locally.  Are you seeing any errors in the "Help->Developer Tools" Console log?  Also, it may be helpful to confirm (1) you can successfully commit to the repo using CLI git tools (e.g. `git commit`) and (2) that this scenario works in VS Code, to help isolate if this is upstream issue or not.  Thanks!

**Comment by cheenamalhotra** [comment]
Closing as inactive, please re-open if you have more details to provide and it still happens.
