### ISSUE TITLE
Beep When Query Completes

### ISSUE THREAD

**Issue by SSpeet** [microsoft/azuredatastudio#23234]
Hi,

Sometimes a query can take a long time to finish, so I rather work on something else while it's running. I often get distracted and forget about the query I was running in the first place.

Therefore, I want to be able to play a sound when the query finishes. SQL Server Management Studio (SSMS) already provides an option for this. In Tools, Options, Query Results, there is an option to Play the Windows default beep when a query batch completes.

Additionally, I'd like to:

- Have the ability to play a different sound, not just the default Windows beep.
- Have the ability to enable/disable this on a specific query window once a query is already running. Having this on all the time would be quite annoying, so a toggle to easily switch it on or off would be nice.

Thanks

**Comment by kburtram** [comment]
Thanks for opening this issue and adding  the context on the use case.  We're currently tracking this request with issue https://github.com/microsoft/azuredatastudio/issues/21110.  I will close as duplicate, please add any additional context on that issue.
