### ISSUE TITLE
Add a Trust Server Certificate switch at command line

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#23267]
**Is your feature request related to a problem? Please describe.**
Azure Data Studio now (for some time) uses Encrypted connections by default, which means for a default installation (of SQL Server) the certificate will be self-signed. When using ADS's GUI you can select the "Trust server certification" option in the connection details. There is, however, no such switch when using command line to launch ADS and automatically connect to a host.

**Describe the solution or feature you'd like**
A switch should be added to the `azuredatastudio` executable so that trust server certification can be passed to the application. I would suggest this this would be `-C`/`--trust-server-certificate`, as it's available and that's what [go-sqlcmd](https://learn.microsoft.com/en-us/sql/tools/sqlcmd/go-sqlcmd-utility?view=sql-server-ver16) uses. So would look like:
```powershell
azuredatastudio -S localhost -d Sandbox -E -C
azuredatastudio --server localhost --database Sandbox --integrated --trust-server-certificate
```

**Describe alternatives you've considered**
The alternative would be to use a non-self signed cert, however, for many (home) developments environments, this isn't a viable option

**Additional context**
None.

**Comment by cheenamalhotra** [comment]
Hi @LarnuUK 

We've introduced support for advanced options in command line to be provided in JSON format with https://github.com/microsoft/azuredatastudio/pull/23104, and support is available in 1.44, could you give this a try?

`azuredatastudio --server localhost --provider mssql --integrated --connectionProperties '{"trustServerCertificate":"true"}'`

**Comment by LarnuUK** [comment]
Hi @cheenamalhotra I get the following error:
```none
Warning: 'connectionProperties' is not in the list of known options, but still passed to Electron/Chromium.
```
I am using 1.44. I also tried `ConnectionProperties` and `connectionproperties`.

The `--help` switch also does not show `--connectionproperites` as an option.

**Comment by cheenamalhotra** [comment]
I've reproduced this issue with native command line args and I'm working on a fix soon.
Can you try launching with URI instead?
