### ISSUE TITLE
Not able to publish database project

### ISSUE THREAD

**Issue by PyMach** [microsoft/azuredatastudio#23287]
I updated ADS to 1.44 version and am not able to publish any database projects.

I had to revert to 1.43 and it works.

**Comment by alanrenmsft** [comment]
@kisantia FYI.

**Comment by kisantia** [comment]
@PyMach can you please share what the error is? Can you also try publishing using the [latest sqlpackage](https://learn.microsoft.com/en-us/sql/tools/sqlpackage/release-notes-sqlpackage?view=sql-server-ver15#162052-sqlpackage) and see if that works?

**Comment by PyMach** [comment]
This is the error 

![image](https://github.com/microsoft/azuredatastudio/assets/49952992/869cada6-066a-482e-a9f9-2f2f03ba15b8)

**Comment by PyMach** [comment]
@kisantia   Please see above screenshot

**Comment by kisantia** [comment]
@PyMach the screenshot shows 0 errors, so the build completed successfully. The warning shown is just a warning and can be fixed by updating the casing. As long as the project and database's collation is case insensitive, this shouldn't block the project from building and publishing.

**Comment by PyMach** [comment]
@kisantia   its not triggering the publish task (Deploy dacpac)

**Comment by kisantia** [comment]
@PyMach can you please share the steps to repro this? I tried creating a simple project with a table and view that references the table with different casing for the name, but the publish task is triggered after the build:
https://github.com/microsoft/azuredatastudio/assets/31145923/55618ded-8587-4395-8fe4-03da4104d4a8

**Comment by PyMach** [comment]
@kisantia   looks like you are you v1.44.1 , let me try with that version but definitely its not working in v1.44

**Comment by kisantia** [comment]
closing as I was unable to repro. Please reopen if this is still happening with the latest release
