### ISSUE TITLE
Azure Connections show "No subscriptions found" now.

### ISSUE THREAD

**Issue by XMLDiva** [microsoft/azuredatastudio#23282]
Type: <b>Bug</b>

Azure panel will show account, but when expanded shows "No subscriptions found". I have version 1.43 also installed and it works correctly and lists the databases.

Things tried:
* Removing Azure account and readding account.
* Confirmed Azure Core is installed.
* Toggling verbose logging and Azure log file is 0 bytes / emtpy.
* Confirming tenant ID filter in settings is correct
* Toggle Enable SQL Authentication provider
* Opening up debug tools and I don't see any error in the console when I delete & readd account
* I have a parallel windows version also installed, but I get a "User account not received" with the current version. I've not tried version 1.43 on Windows to know if it worked

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:50:03.880Z)
OS version: Darwin arm64 22.3.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|2, 3, 3|
|Memory (System)|64.00GB (10.22GB free)|
|Process Argv||
|Screen Reader|yes|
|VM|0%|
</details><details><summary>Extensions (24)</summary>

Extension|Author (truncated)|Version
---|---|---
demo-mode|dre|1.1.1
copilot|Git|1.82.15
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
cms|Mic|0.9.3
dacpac|Mic|1.13.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.19.0
server-report|Mic|0.2.4
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.1.1
whoisactive|Mic|0.1.5
azdata-sanddance|msr|4.0.1
sqlops-spexecutesql-to-sql|pej|1.0.2
schema-visualization|R0t|0.8.2
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.2.1

</details>

**Comment by kburtram** [comment]
@cheenamalhotra any idea what could be happening or how best to troubleshoot?

**Comment by cheenamalhotra** [comment]
@XMLDiva 

Please try reloading ADS after enabling Azure logging, or you can also view logs in the 'Azure Accounts' output pane as below:
![image](https://github.com/microsoft/azuredatastudio/assets/13396919/65b0bf0d-cb8f-4530-99bc-47c6fa7d8eb8)

Can you also provide screenshot to understand where you're looking for subscriptions, is it Azure Tree view or Browse > Azure view?

> I have a parallel windows version also installed, but I get a "User account not received" with the current version

Please try clearing account cache using Command Palette (Ctrl + Shift + P): `accounts.clearTokenCache`, i.e. "Azure Accounts: Clear Azure Account Token Cache" followed by re-authentication if prompted.

**Comment by cheenamalhotra** [comment]
@XMLDiva You may also use the steps from here, if you're hitting a similar issue: https://github.com/microsoft/azuredatastudio/issues/23286#issuecomment-1572668567

**Comment by XMLDiva** [comment]
@cheenamalhotra Thank you! The output pane helped find the issue. I had my tenant ID in the settings. I had read it as a inclusive list and not exclude list. I don't know why it was working in 1.43 though.

Also the clear token helped the windows, so that is fixed as well.

Thank you for the fast reply. TBH I have been fighting ADS last year on the mac. This reinvigorating me to start to be involved in reporting so I can help. I'm hopeful 1.44 helps some of the crashing I previously had.

Question: If ADS crashes, do you look at the Apple reports if I submit there? Or better to just reopen and submit a bug with steps that happened?

**Comment by XMLDiva** [comment]
Good to close

**Comment by cheenamalhotra** [comment]
Good to know you're unblocked. 

We don't follow Apple reports, so please let us know on GitHub if you encounter any issues. You can use "Help > Report Issue" dialog to prepare bug report.
