### ISSUE TITLE
Can the cursor change to spinner for the customer to know they have to wait

### ISSUE THREAD

**Issue by goyal-anjali** [microsoft/azuredatastudio#23288]

**Comment by alanrenmsft** [comment]
@goyal-anjali could you please add more description?

**Comment by goyal-anjali** [comment]
@alanrenmsft I want the cursor to look something like this when a button is clicked. This is usually achieved by setting the css cursor: wait
But I dont think I can do that on ADS for the entire screen.
![image](https://github.com/microsoft/azuredatastudio/assets/66509246/39aa18dc-bdfc-4e8c-9baa-9524619a7935)

**Comment by goyal-anjali** [comment]
Had a discussion with @aasimkhan30 and it looks like the spinner wouldn't be possible in ADS.
Only loading component is available for utlization

**Comment by aasimkhan30** [comment]
There is a way to add loading to dialogs and wizard. Will that work for this scenario?
![image](https://github.com/microsoft/azuredatastudio/assets/6816294/0b956702-6d37-47b4-b985-673367a273f5)

**Comment by alanrenmsft** [comment]
@goyal-anjali please close the issue if the suggestions above work for you.

**Comment by kisantia** [comment]
Closing this issue. @goyal-anjali please reopen if the suggestions provided don't work for you
