### ISSUE TITLE
AAD Auth Failing

### ISSUE THREAD

**Issue by milawell** [microsoft/azuredatastudio#23294]
Type: <b>Bug</b>

New Connection > Authentication Type AAD - Universal with MFA Support > Account > Add an account > Pick an account (from browser) > fails with 301
Suspect maybe a firewall issue or another network issue? 

Error message:
Error: unknown_error
Error Message: undefined - [undefined]: An unknown error occured.
Http status code: 301
Http status message: Moved Permanently
Headers: {"location":"https://login.microsoftonline.com/login.microsoftonline.com:443"} - Correlation ID: undefined - Trace ID: undefined

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.20348
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Platinum 8370C CPU @ 2.80GHz (8 x 2793)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|32.00GB (24.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Is this error message exactly how you received?

Error message:
Error: unknown_error
Error Message: undefined - [undefined]: An unknown error occured.
Http status code: 301
Http status message: Moved Permanently
Headers: {"location":"[https://login.microsoftonline.com/login.microsoftonline.com:443"}](https://login.microsoftonline.com/login.microsoftonline.com:443") - Correlation ID: undefined - Trace ID: undefined

The URL doesn't seem right and I'm not sure what would cause it.. can you please provide Verbose Azure Account logs? Please reload ADS after enabling the same.

**Comment by milawell** [comment]
Here you go...

[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11635601/1-Azure.Accounts.log)

**Comment by milawell** [comment]
Here you go...

[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/11635623/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
Closing as no further info is received.
