### ISSUE TITLE
After changing connection SQL server disconnects

### ISSUE THREAD

**Issue by gvv5485** [microsoft/azuredatastudio#23293]
Type: <b>Bug</b>

Work on a session on a DB.

Connect to a different saved server and try to query the same query on that server.

This disconnects / don't run the query.
if you cancel it , sometimes it cancels and some times it won't.

Not sure why this is happening?

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.40GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
eltsnap-simple-data-flow|bit|1.0.1
demo-mode|dre|1.1.0
sql-data-inspector|ern|0.6.0
lz-scripts|Fai|1.3.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
azuremonitor|Mic|0.1.9
dacpac|Mic|1.13.0
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.19.0
azdata-sanddance|msr|4.0.1
extra-sql-script-as|pac|0.5.0
sql-search|Red|0.4.2

(1 theme extensions excluded)

</details>

**Comment by Jopnert** [comment]
I'm experiencing the same problem as described above. Sometimes it works, some times you can cancel and then run it again and it  works. Sometimes cancelling doesn't work.
It seems to happen with CRUD statements. When i run a select it finishes immediatley, when i run an update statement in the same  window it hangs on "Started executing query at Line 6"
Version: 1.44.1

**Comment by cheenamalhotra** [comment]
Could you give the latest insiders build a try? 
I'm suspecting this could be related with https://github.com/microsoft/azuredatastudio/issues/23316#issuecomment-1578161404 fixed by https://github.com/microsoft/azuredatastudio/issues/23316#issuecomment-1578161404, planned for July release.

**Comment by Jopnert** [comment]
I've installed  the insider build. I'll keep you posted

**Comment by Jopnert** [comment]
I don't have the issue anymore with the insider build. Sometimes the spinner keeps loading besides the connection, but i have seen this mentionned in other thread.

I consider it fixed in the insider build.

**Comment by cheenamalhotra** [comment]
Thanks @Jopnert ! Appreciate your support in validation.. I'll close the issue as resolved.
The fix will be available in upcoming July release.
