### ISSUE TITLE
Unable to install extensions via extension tab

### ISSUE THREAD

**Issue by gsk143** [microsoft/azuredatastudio#23302]
Type: <b>Bug</b>

Open extension tab and try to install any extension

Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:52:43.653Z)
OS version: Darwin x64 22.3.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kisantia** [comment]
@gsk143 are you still seeing this happening in the latest ADS release? What is the error?

**Comment by gsk143** [comment]
Hi @kisantia sorry for the late reply got caught up in irl stuff. I did check it in Version: 1.45.1
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2 and it did indeed seem to have fixed it. Thanks
