### ISSUE TITLE
Error downloading

### ISSUE THREAD

**Issue by qsfdfdsvcv** [microsoft/azuredatastudio#23324]
- Azure Data Studio Version: 1.44.1
- OS Version: 10

Steps to Reproduce:

1.
![Capture](https://github.com/microsoft/azuredatastudio/assets/135722925/e3becbfe-55b0-4eb0-b9c9-e25824380b61)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
@Benjin do you have any ideas what's happening here? or what info we'd need to diagnosis?

**Comment by Benjin** [comment]
@qsfdfdsvcv does this error persist when you try again (now that it's been several hours)?

If it still errors, can you use run this command to load it into your nuget cache, then restart ADS and try building again?

`nuget install Microsoft.Build.Sql -Version 0.1.9-preview -PreRelease`

Note that you'll need to have nuget installed and accessible in your path first.

**Comment by kisantia** [comment]
Closing from lack of response. Please reopen the issue if the requested information is provided
