### ISSUE TITLE
Notebook cells are showing empty sometimes after reopening 

### ISSUE THREAD

**Issue by jvcampbell** [microsoft/azuredatastudio#23333]
Type: <b>Bug</b>

After running a SQL query, the notebook usually saves the resultset.
After re-opening the notebook, the dataset sometimes is blank. I can export the results to a csv file and they are there, but they aren't showing the the cell.

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.14393
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v4 @ 2.60GHz (4 x 2600)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|12.00GB (5.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
dacpac|Mic|1.13.0
import|Mic|1.5.5
profiler|Mic|0.12.2
query-history|Mic|0.5.3
schema-compare|Mic|1.19.0
server-report|Mic|0.2.4
sql-assessment|Mic|0.6.4
whoisactive|Mic|0.1.5
sql-prompt|Red|0.2.12

</details>

**Comment by Charles-Gagnon** [comment]
Closing due to no response, if you see this again please attach the logs as requested and we can investigate further!

If you're able to attach the original notebook that had the issue as well that might help us repro the issue.
