### ISSUE TITLE
Feedback on the migration experience

### ISSUE THREAD

**Issue by AzureSunil** [microsoft/azuredatastudio#23352]
Type: <b>Feature Request</b>

1) when # of databases exceed 100, that are selected for the assessment it could prompt user for a recommendation to have a separate run so that MI recommendations are not excluded.

Extension version: 1.4.5
Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by abhims14** [comment]
Hello, could you please share the assessment results by saving it as JSON file?

**Comment by Ramudaykumar** [comment]
Code change completed and will be available in next SQL Migration extension release, marking it closed.
