### ISSUE TITLE
Chart type "image" not working

### ISSUE THREAD

**Issue by AlexFsmn** [microsoft/azuredatastudio#2335]
- SQL Operations Studio Version:
0.31.4

Steps to Reproduce:
1. Run query
2. Go to chart view
3. Select chart type "image"

Result:
![image](https://user-images.githubusercontent.com/11557675/44685700-61cf1d80-aa4c-11e8-912f-e3a9170fcbab.png)

Im not really sure what this chart type is supposed to do but it seems like it doesn't work.

**Comment by kburtram** [comment]
Closing out older issues.  I believe this is working as designed, but the design is not intuitive for that option.  Thanks for reporting this issue!
