### ISSUE TITLE
Remove Linked Server Logins node under Security (instance level)

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23365]
There isn't a comparable object in SSMS, and if I create a linked server login (EXEC sp_addlinkedsrvlogin 'servername\SQL2022';), it doesn't show up under the Linked Server Logins node.

**Comment by caohai** [comment]
@alanrenmsft @erinstellato-ms Taking a look, can confirm the behavior and SSMS doesn't have this node. Btw this feels more likely to be a OE issue instead of User Management issue, I'll adjust the labels.
