### ISSUE TITLE
Move default database, default language and permission to connect higher up in Create Login dialog, add User Mapping

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23366]
The default database drop down, default language drop down, and permission to connect to database engine check box are not Advanced options.  Can we move those up (above Server Roles), as in the screen shot below for creating a SQL login?  If those three items need to be under collapsible section with a title, can we brainstorm a word to use instead of Advanced?  

Also, we don't have the User Mapping dialog to map between server login and database user.  That can be an expandable node below Server Roles.

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/a827bf03-d33d-4fe2-a1e8-d3c09903e9d9)

**Comment by alanrenmsft** [comment]
@erinstellato-ms could you please open a separate issue for user mapping? we can implement the rest of it in July, and for User Mapping feature, I'd prefer to let the users vote for it.

**Comment by erinstellato-ms** [comment]
@alanrenmsft if you cannot map a login to a database in that dialog, then you are expecting the ADS user to create the login, then go to the database, go to security, create a new user, and then map it back to the login they just created.  That's a lot of extra friction and steps for the user.
