### ISSUE TITLE
Add "Starts With" as a drop down option in the Operator field for Filter

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23364]
Within the Filter Settings dialog, in the Operator field, add "Starts With" as a drop down option.  This would be useful for scenarios where the text matches a large number of objects using Contains, but folks are only interested in seeing objects that start with the text

Contains: WHERE Name LIKE '%Sales%'
Starts With: WHERE Name LIKE 'Sales%'

**Comment by aasimkhan30** [comment]
Fixed by #23422
