### ISSUE TITLE
A11y_Azure Cosmos DB Migration for MongoDB_Migration Assessment_Run New assessments_High Contrast : In High contrast mode, there is no way to differentiate between the normal text and alert message.

### ISSUE THREAD

**Issue by bharathpalaksha** [microsoft/azuredatastudio#23385]
- Azure Data Studio Version: 1.44.1
- OS Version: windows 11

Steps to Reproduce:

1. Go to contrast themes of windows OS in settings, select Night sky
2. Start Azure data studio, have a mongo connection, right click on manage to open extension
3. Go to "Migration Assessment" tab and Click on "Run new assessment"
4. In the dialog that is open, input assessment name with a single or two character. It shows validation error message on input box but outline is not in different color indicating error. outline still shows as correct validation.

Does this issue occur when all extensions are disabled?: No

**Comment by alanrenmsft** [comment]
original issue https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2413109

**Comment by kisantia** [comment]
closing since original issue was closed due to UI redesign
