### ISSUE TITLE
Incomplete list of stored procedures displayed

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#23399]
Type: <b>Bug</b>

The Programmability/Stored Procedures tree node does not display all stored procedure from our database.  I only see 68, but our database has 603.

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.20GB (51.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
import|Mic|1.5.5
powershell|ms-|2023.2.1
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.3
extra-sql-script-as|pac|0.5.0
sql-prompt|Red|0.2.12
sql-search|Red|0.4.2

(1 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment]
@barryseymour can you please capture verbose logs when expanding OE nodes?

**Comment by barryseymour** [comment]
Sorry, I'm out of work for 6-8 weeks due to knee surgery.

**Comment by cssuh** [comment]
@barryseymour Hi are you able to provide logs for this error?

**Comment by barryseymour** [comment]
Sorry, I am no longer able to reproduce this issue. Please close the ticket.

**Comment by cheenamalhotra** [comment]
Closing as no longer reproducible.
