### ISSUE TITLE
Recent Connections does not reflect on Object Explorer connection status (and vice versa)

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#23406]
1. Connect to a connection on the object explorer tree.
2. Open the recent connections list.
3. It is observed that the entry for the connection in recent connections is marked as disconnected, even after clearing it and reconnecting. However, opening the connection via notebook changes the status, although the object explorer connection won't be connected as well. (Unless this is by design now).

This was observed to occur before the introduction of the new connection string format (for multiple connection options) so it isn't caused by that. This might have been something to do with how closing the recent connections flyout affected the connection status in recent connections.

**Comment by cheenamalhotra** [comment]
I think this is in non-async server tree - status from recent connections was removed with Async server tree design.

**Comment by cheenamalhotra** [comment]
Closing as async server tree is going to be enabled by default in July release.
