### ISSUE TITLE
Unable to authenticate to SQL Pool using Cross-Cloud B2B guest account (GCC to Azure Gov)

### ISSUE THREAD

**Issue by thevinnie** [microsoft/azuredatastudio#23402]
- Azure Data Studio Version: 1.44.1 and 1.45.0-insider (user setup)
- OS Version: WIndows_NT x64 10.0.19044

I'm working with a customer who is trying to authenticate from their local machine to an Azure Synapse dedicated SQL Pool. The user identity is homed in a GCC tenant and is authenticating to a Synapse instance in Azure Government. The user identity was invited using the Cross-Cloud B2B preview feature (https://learn.microsoft.com/en-us/azure/active-directory/external-identities/cross-cloud-settings) and can successfully authenticate using SSMS and in the web-based Synapse Workspace.

I walked them through trying all that I know within Azure Data Studio, including the options to enable Azure Gov endpoints, device code authentication, and switching between available authentication types. Before I opened this, I had them install the insiders build based on the guidance you put in #21612 

Included here is a generic architecture diagram of the environment:
![environment-configuration](https://github.com/microsoft/azuredatastudio/assets/455129/6cfa176b-dd02-40e9-92db-9a63ff527e78)

Here is the error message we see with the production release (1.44.1):
![login-failed-for-user](https://github.com/microsoft/azuredatastudio/assets/455129/939d1c0f-1c17-48d6-8346-f5e559ea9d22)

Here is the error from the insiders build (1.45.0_insiders):
![insider-build-error](https://github.com/microsoft/azuredatastudio/assets/455129/25edc0af-0e66-486e-8fd3-f5ed5a306c92)

And here is the settings page. Note that we've tried a number of combinations, none successful:
![settings-page](https://github.com/microsoft/azuredatastudio/assets/455129/ed663044-09fa-4b76-b8d0-302a252da2bd)

Steps to reproduce:

0. Using an Azure Government tenant and a GCC tenant, create a trust relationship between the two using the CCB2B feature (https://learn.microsoft.com/en-us/azure/active-directory/external-identities/cross-cloud-settings)
1. Create Synapse Dedicated SQL Pool in Azure Government
2. Invite guest user from GCC tenant into Gov tenant and provide access to the Synapse instance
3. Attempt to login to the database from Azure Data Studio from an Azure AD joined machine (under the GCC tenant) to the Synapse SQL Pool in Azure Gov

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cheenamalhotra** [comment]
Hi @thevinnie 

Could you also confirm Cx has enabled Gov Cloud using this setting?
[Azure Account Configuration](https://learn.microsoft.com/en-us/sql/azure-data-studio/azure-connectivity?view=sql-server-ver16#azure-account-configuration)

**Comment by thevinnie** [comment]
> 

I have confirmed that they enabled this setting.

**Comment by cheenamalhotra** [comment]
Hi @thevinnie 

Please request customer to gather logs as per above comment. Do ensure they restart ADS after enabling the setting.

**Comment by cheenamalhotra** [comment]
Now that I recall, cross-cloud is not supported with default settings.
You can disable `mssql:enableSqlAuthenticationProvider` setting to get this scenario working.

**Comment by cheenamalhotra** [comment]
Closing this as alternate solution can be used for cross-cloud authentication.
