### ISSUE TITLE
Gear menu missing "Check for Updates"

### ISSUE THREAD

**Issue by thoffmann-fms** [microsoft/azuredatastudio#23411]
Type: <b>Bug</b>

_Download and install Azure Data Studio
Microsoft
https://learn.microsoft.com › Learn › Azure Data Studio
Jun 5, 2023 — Check for updates. To check for the latest updates, on the left pane, select Manage (gear icon), and then select Check for Updates.
‎[Download Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio#download-azure-data-studio) · ‎[Install Azure Data Studio](https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio#install-azure-data-studio)_

When I left-click Gear icon I don't see the check for updates menu any more.
![image](https://github.com/microsoft/azuredatastudio/assets/28546239/155cb896-43bf-4159-a9f7-721bd086eb0e)

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.20348
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (16 x 2688)|
|GPU Status|2d_canvas: unavailable_software<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>opengl: disabled_off<br>rasterization: disabled_software<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.93GB (8.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kisantia** [comment]
@thoffmann-fms do you still not see the "Check for Updates..." option after restarting ADS? How did you install ADS?

I just updated user installation on windows to 1.44.1 and see the "Check for Updates..." option:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/8ef4e20b-a984-4b99-a259-6699adfdbcea)

**Comment by thoffmann-fms** [comment]
At some point since that day it's magically re-appeared. V 1.45.0-insider (user setup)
