### ISSUE TITLE
DB Extensions do not recover from intermittent network outages

### ISSUE THREAD

**Issue by kpconnell** [microsoft/azuredatastudio#23418]
Type: <b>Bug</b>

SQL Server, MySQL and Postgres extensions all suffer from not recovering from intermittent network outages, and require a full restart of application to re-connect.  

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:13:21.084Z)
OS version: Darwin x64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|0.2.9
azuredatastudio-postgresql|Mic|0.3.1
dacpac|Mic|1.13.0
import|Mic|1.5.5
profiler|Mic|0.12.2

</details>

**Comment by cheenamalhotra** [comment]
Hi @kpconnell 

It would be great if you can provide us logs, please gather them from previous timestamp folder (under azuredatastudio\logs\) if ADS crashes for you.

**Comment by cheenamalhotra** [comment]
Hi @kpconnell 

We don't have enough data to investigate your issue and it's not reproducible as described for MS-SQL connections.
For postgres/mysql issues, please open new issue in below repos:
- https://github.com/microsoft/azuredatastudio-postgresql
- https://github.com/microsoft/azuredatastudio-mysql
