### ISSUE TITLE
The ability to show MULTIPLE TAB ROWS when lots of tabs are open

### ISSUE THREAD

**Issue by gregclerk** [microsoft/azuredatastudio#23426]
**Is your feature request related to a problem? Please describe.**
Whenever I have lots of tabs open I have to scroll left and right.

**Describe the solution or feature you'd like**
It'd be easier if the tabs would spill over onto the next row(s) like VS2022 has with its "Show tabs in multiple rows" setting.

**Describe alternatives you've considered**

**Additional context**

**Comment by kisantia** [comment]
@gregclerk this feature is currently available with the "Wrap Tabs" setting
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/67854dd3-7285-48f8-b236-d4bae775dc70)
