### ISSUE TITLE
Show DB Connection Details when live editing data

### ISSUE THREAD

**Issue by whiskeyremorse** [microsoft/azuredatastudio#23438]
It is very disconcerting when live editing data in Azure Data Studio that I cannot see the database I am connected to when editing the data.  As with possibly many other user I have many similar databases (dev, test, uat, prod) that I connect to for day to day work.  

Sometimes it is useful to live edit data (right click on the table in the Servers side panel and select Edit Data).  The new tab that is created doesn't show which database you are currently working on unlike the standard Query tab.

It would be great if the Edit Data tab showed the current connection details just like the standard query tab does too please.

There is no obvious workaround to this issue other than a familiarity with the data in each instance of the databases which in some cases may be identical.

**Comment by cheenamalhotra** [comment]
Closing as resolved.
