### ISSUE TITLE
Update property dialog window to include "Properties"

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23450]
When viewing the properties for a user, login, database, server, etc. we should include the word Properties in the dialog name.

Examples:
Login Properties - loginame
User Properties - username
Server Role Properties - serverrolename
Database Role Properties - databaserolename
Application Role Properties - applicationrolename
Database Properties - databasename
Server Properties - servername

Current behavior:

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/12adf563-41eb-4b88-a0af-d032ffd76539)

**Comment by barbaravaldez** [comment]
Cannot repro anymore.
