### ISSUE TITLE
Change contrast for text boxes that are not editable

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23451]
For text boxes that display information that is not editable (e.g. login name, database name, etc.) the shaded box and text contrast is difficult to read.  

Make the text the same color as the label, and lighten the shaded box.

For the User Properties dialog, make the Name and Authentication boxes the same (right now, Authentication is not editable but the background is the same as the dialog.

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/ce5f2293-7749-4a37-8023-3a87879de848)

**Comment by corivera** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/23715
