### ISSUE TITLE
Should update naming convention for Azure Postgres Single Server

### ISSUE THREAD

**Issue by nasc17** [microsoft/azuredatastudio#23458]
Including Azure Database for PostgreSQL Flexible servers was  addressed by this https://github.com/microsoft/azuredatastudio/issues/23292 , however to better differentiate between the flex server and single I propose changing Azure Database for PostgreSQL servers -> Azure Database for PostgreSQL Single servers.

Secondly what if we were to consolidate all databases for PostgreSQL under "Azure Databases for PostgreSQL"? 

Version: 1.45.0-insider (user setup)
Commit: 378585d43e0554e919a3f7c423fafa37a344f96a
Date: 2023-06-23T05:37:42.523Z
VS Code: 1.70.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by cheenamalhotra** [comment]
I'm more inclined to include all databases under "Azure Databases for PostgreSQL", this would include:
- microsoft.DBforPostgreSQL/flexibleServers (Azure Database for PostgreSQL flexible servers)
- microsoft.DBforPostgreSQL/servers (Azure Database for PostgreSQL servers)
- microsoft.DBforPostgreSQL/serversv2 (Azure Database for PostgreSQL servers v2)
- microsoft.dbforpostgresql/singleservers

Do you also want to include server groups? Does extension support these?
- microsoft.DBforPostgreSQL/serverGroups (Azure Database for PostgreSQL server groups)
- microsoft.DBforPostgreSQL/serverGroupsv2 (Azure Database for PostgreSQL server groups)

**Comment by cheenamalhotra** [comment]
@nasc17

Can these categories have same server names? If yes, we should keep them separate I would say.

**Comment by cheenamalhotra** [comment]
We've discussed naming convention with @erinstellato-ms and concluded to keep it as-is.
Rest of the servers are all available in Azure tree now.
Closing as resolved.
