### ISSUE TITLE
Azure Data Studio too slow when connecting or performing some query

### ISSUE THREAD

**Issue by wospl** [microsoft/azuredatastudio#23461]
- Azure Data Studio Version: 1.41.2
- OS Version: Windows 10.0.19045 Build 19045

Steps to Reproduce:

1. Connect to a Azure SQL DW instance
2. Sometimes, also if already connected to the instance, running any query is a problem

Does this issue occur when all extensions are disabled?: Yes

Hello,
when connecting to an Azure SQL DW instance, Azure Data Studio seems to endless load and never gets connected. It does not happen always. When it finishes, an error popup shows us, but it's totally blank.
Sometimes, it also happens that, if already connected to a SQL DW or Azure SQL instance, launching any query could need some time (minutes) to let it be run by the server (the "query running" message does not appear immediately).

Thanks

**Comment by cheenamalhotra** [comment]
Hi @wospl 

This is a known issue at the moment and we're looking into it, ref issue https://github.com/microsoft/azuredatastudio/issues/23400 (Azure SQL DW is now called Azure Synapse Dedicated SQL Pool). I will close this as a duplicate.
