### ISSUE TITLE
Text editor keeps losing focus

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#23463]
Type: <b>Bug</b>

I run a query. I look at the results in the grid.  I tab away to another window. I tab back to ADS and the text editor doesn't have the focus. I have to click it with my mouse.  

Repeat. When I tab back, I hit my keyboard shortcut to hide the grid. Focus is STILL not on the editor. I hit tab again and again, hoping to get back without having to use the mouse. Can't find it. I have to click in the editor with my mouse to use it.
EVERY TIME. 

It's REALLY annoying. 

Thanks,

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.20GB (49.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.1.2
agent|Mic|0.49.0
import|Mic|1.5.5
powershell|ms-|2023.2.1
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.3
extra-sql-script-as|pac|0.5.0
sql-prompt|Red|0.2.12
sql-search|Red|0.4.2

(1 theme extensions excluded)

</details>

**Comment by cssuh** [comment]
Hi @barryseymour, I believe this has been fixed in 1.45.1 - can you please give it a try? If you are still having problems, please feel free to re-open this issue.

**Comment by barryseymour** [comment]
Yes, this is fixed now. Thanks!
