### ISSUE TITLE
Can we share useful User Snippets with eachother?

### ISSUE THREAD

**Issue by elerilamp** [microsoft/azuredatastudio#2347]
I can't seem to find any examples of **sql.json** online. The snippets are one of the main reasons I still need to use SSMS and SQL Prompt. 
For example - I wonder if it would be possible to create a snippet such as "add commas and quotes" around a list of values? Has anyone created any cool snippets?
I only have the following in my **sql.json** so far:
```
{
	"Select top 5": {
 "prefix": "stop5",
 "body": "SELECT TOP 5 * FROM ${1:TableName}",
 "description": "User-defined snippet example 1"
 },

"Select * from": {
 "prefix": "ssf",
 "body": "SELECT * FROM ",
 "description": "SELECT * FROM"
 },

"Select count(*) from": {
 "prefix": "scf",
 "body": "SELECT COUNT(*) FROM ",
 "description": "SELECT COUNT(*) FROM"
 },

 "Select group by": {
	"prefix": "sgroupby",
	"body": [
			"SELECT COUNT(*) AS CNT,${2:ColumnName} FROM ${1:TableName}",
			"GROUP BY ${2:ColumnName}",
			"ORDER BY 1 DESC"
	],
	"description": "SELECT COUNT(*),Column FROM Table GROUP BY"
}
}
```

**Comment by corivera** [comment]
Closing this one since it's more of a discussion topic, rather than a task.
