### ISSUE TITLE
Modelview Toolbar text unreadable in light mode

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#23514]
After the merge, the text in the schema compare toolbar doesn't show in light mode:
expected:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/b0dd7f13-58ba-4193-867c-689d83d62903)

actual:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/489950bd-0442-46ba-be21-3e915b308dd1)

dark mode (shows as expected):
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/3ff34e1c-41eb-4a38-b12d-e32a9756ce2f)

The toolbar used by the server/db dashboard is still working as expected

**Comment by kisantia** [comment]
After checking the different themes, this is the case for the new themes:
- Light (Visual Studio)
- Light+
![toolbarThemes](https://github.com/microsoft/azuredatastudio/assets/31145923/68c1e90e-907f-4969-a4f6-9d7a43414b88)

The ADS default light theme still shows the text as expected

**Comment by cheenamalhotra** [comment]
Also noticed the same in SQL migration extension:
![image](https://github.com/microsoft/azuredatastudio/assets/13396919/36870038-0d7c-4261-afb3-7ea22d2dd418)

**Comment by alanrenmsft** [comment]
fixed by https://github.com/microsoft/azuredatastudio/pull/23581
