### ISSUE TITLE
Group by Schema menu item is always at bottom

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23510]
Currently the "Enable/Disable Group by Schema" menu item is always at the bottom. This should probably go up higher - at the very least above the "Properties" menu items.

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/3f6442af-d693-49bc-8314-a4adf41cd7ec)

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 Would you have time to take a look at moving this?

@erinstellato-ms FYI if you have opinions on where it should go

**Comment by erinstellato-ms** [comment]
@Charles-Gagnon @aasimkhan30 Let's brainstorm - we should be consistent for the right-click menu for both the instance and database (since it appears on both menus).

Do we have a "pattern" or "template" right now for how things are organized on the menu?

**Comment by Charles-Gagnon** [comment]
Nope, and it would be great to have that IMO. At the very least have a definition of what groups we have now and suggestions for where extension-contributed items should generally go (for example suggestion that properties is always at the bottom)

Example from VS Code : https://code.visualstudio.com/api/references/contribution-points#Sorting-of-groups
