### ISSUE TITLE
No border on Modelview input boxes and dropdowns used in extensions for new light themes

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#23515]
After the merge, the outline of input boxes and dropdowns does not show until they are selected. This is confusing because users wouldn't be able to tell that a field is editable.

Sql projects new project dialog:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/0c923bab-281e-4dbd-bdc9-cab4e63287aa)

Schema compare dialog:

https://github.com/microsoft/azuredatastudio/assets/31145923/a88b8d06-dfc8-4b4a-a091-3ad80b67786b

**Comment by kisantia** [comment]
This is only the case for a couple of the new light themes:
- Light (Visual Studio)
- Light+
![theming](https://github.com/microsoft/azuredatastudio/assets/31145923/df988e75-345e-4b82-840e-9d64c28e4dad)

**Comment by alanrenmsft** [comment]
will be fixed by https://github.com/microsoft/azuredatastudio/pull/23599
