### ISSUE TITLE
Post Merge > Manage tab selected database unreadable in light mode

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23520]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Multiple theme issues:
* Light Modern
* Quiet Light
* Solarized Light

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/24b6262b-74e6-445c-a8d7-1cad77977bf4)

Also interested to know: 
Is there a reason to use blue (#2c3295) color in all themes when a cell is selected? Can we not select a theme based darker shade for all focus foreground colors?

cc @erinstellato-ms

**Comment by erinstellato-ms** [comment]
I agree that being consistent to use a theme-based darker shade would be ideal here.
