### ISSUE TITLE
Post Merge > Query editor tab color top border overlaps connection/account dialogs

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#23522]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Steps to Reproduce:
1. Set Query Editor Tab color mode to "Fill"
2. Open multiple tabs with a connection using server group
3. Open any of the dialog: New Connection Dialog or Linked account dialog
4. Notice the top border overlays over the dialogs, where it shouldn't.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/97023efc-149b-481f-8d6a-937ef0db184d)
![image](https://github.com/microsoft/azuredatastudio/assets/13396919/009c7a06-3483-40bf-b732-80a564d69804)

On the contrary, New Server Group dialog seems to work fine and overlays over the border as expected.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/42e46376-9b19-48be-8d51-7033f47698d5)

**Comment by alanrenmsft** [comment]
@cheenamalhotra are you still able to reproduce the issue?

**Comment by alanrenmsft** [comment]
not reproducible now. must have been fixed.
