### ISSUE TITLE
Allow toggling insert/overwrite mode while typing in text editor

### ISSUE THREAD

**Issue by jimkilliansentinel** [microsoft/azuredatastudio#23524]
**Is your feature request related to a problem? Please describe.**
There are times (few though they may be) where I want to use "overwrite" mode while typing in the editor, rather than inserting new text. Pressing [Insert] has no effect, and I can't find any mention of it in the program.

**Describe the solution or feature you'd like**
Allow the user to toggle insert/overwrite mode by pressing [Insert] (ideally) or some other shortcut or onscreen button. The cursor should also change to indicate the mode.

**Additional context**
This isn't something that I've thought of before today, but for this instance it's annoying not to have it. Certainly not keeping me from getting work done, but it's a normal feature everywhere else (SSMS, notepad, Notepad++, etc.) and doesn't make sense to not allow it.

**Comment by Charles-Gagnon** [comment]
Unfortunately this doesn't seem to be something that VS Code has built in natively (see https://github.com/microsoft/vscode/issues/1012) - but looking around it seems the most common suggestion is to use the Vim extension. To use this in ADS follow these instructions:

1. Download the [1.24.3](https://marketplace.visualstudio.com/_apis/public/gallery/publishers/vscodevim/vsextensions/vim/1.24.3/vspackage) VSIX (later versions aren't compatible with ADS currently)
2. Open ADS and run the `Extensions: Install from VSIX...` command
3. Select the VSIX you downloaded

With that I was able to get insert to toggle between overwrite mode

*Note: Installing extensions like this could potentially cause other problems, so do this at your own risk. But the issues are unlikely to cause any major issues so it should probably be fine

I'm going to close this as it's something we would inherit from VS Code, so hopefully they implement that natively at some point!

**Comment by jimkilliansentinel** [comment]
Thanks! Took some time for it to start working correctly (initially the cursor just changed shape every time I pressed a key, and then it wouldn’t toggle correctly) but it finally figured itself out and I’m happy!

Jim

Jim Killian | Software Developer
Sentinel Offender Services, LLC
111 Corporate Drive, Suite 125 | Ladera Ranch, CA 92694<webextlink://111%20Corporate%20Drive,%20Suite%20125%20|%20Ladera%20Ranch,%20CA%2092694/>
C| 949.239.3722
E| ***@***.******@***.***>
W| www.sentineladvantage.com<http://www.sentineladvantage.com/>

**Comment by jimkilliansentinel** [comment]
Update: I disabled this extension because it makes it so that selecting text and trying to paste to replace it doesn’t work. Not worth the hassle of trying to figure out if that’s fixable.

Jim

Jim Killian | Software Developer
Sentinel Offender Services, LLC
111 Corporate Drive, Suite 125 | Ladera Ranch, CA 92694<webextlink://111%20Corporate%20Drive,%20Suite%20125%20|%20Ladera%20Ranch,%20CA%2092694/>
C| 949.239.3722
E| ***@***.******@***.***>
W| www.sentineladvantage.com<http://www.sentineladvantage.com/>

**Comment by GitMensch** [comment]
You could try the overtype extension which _only_ tries to fix that (and provide the current mode) - still a "native" implementation would be much better.

**Comment by jimkilliansentinel** [comment]
Thanks! This appears to work exactly as advertised, both in ADS and VSC. I’ll update if I run into any issues.

Jim

Jim Killian | Software Developer
Sentinel Offender Services, LLC
111 Corporate Drive, Suite 125 | Ladera Ranch, CA 92694<webextlink://111%20Corporate%20Drive,%20Suite%20125%20|%20Ladera%20Ranch,%20CA%2092694/>
C| 949.239.3722
E| ***@***.******@***.***>
W| www.sentineladvantage.com<http://www.sentineladvantage.com/>
