### ISSUE TITLE
A11y_SqlDatabaseProjectsExtension_DatabaseProject_Keyboard: keyboard focus is getting disappeared when we press TAB key after project.

### ISSUE THREAD

**Issue by PoojaNamde** [microsoft/azuredatastudio#23548]
[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

### Git hub Tags:
#A11yTCS; #A11yMAS; #A11ySev2; #DesktopApp; #Benchmark; #WCAG2.4.7; #FTP; #SH-SQL Azure Data Studio-Linux-Jul23; #SQL Azure Data Studio; #Linux; #Keyboard;

### Environment Details:
Application Name: Sql Database Projects Extension
Operating System: Ubuntu 20.04.2 LTS
Azure data studio 1.44.1 
SQL Database projects v1.1.1

### Repro Steps:

1. Launch Azure Data Studio application.
2. TAB to 'Extension' and search for “SQL Database Projects” and install it.
3. TAB to "Database project" and press ENTER key.
4. Navigate using TAB key after the project and observe the issue.

### Actual Result:
keyboard focus is getting disappeared when we press TAB key after project.

### Expected Result:
keyboard focus should not get disappeared when we press TAB key after project.

### User Impact:
Keyboard users will get confused here as they will not understand where the focus is.

### Attachment:

https://github.com/microsoft/azuredatastudio/assets/90901519/aa8af3f0-992e-452e-8a21-e165ef6da504

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver"**

**Comment by kisantia** [comment]
@PoojaNamde this is expected, users should use arrow key navigation within the projects view.

**Comment by PoojaNamde** [comment]
@kisantia 

Here the issue is not with project view. When we press TAB key after the project control the keyboard focus is getting disappeared.

**Comment by kisantia** [comment]
@PoojaNamde if a file is open, then the focus goes to that tab next and this is the normal workflow when using the product(to have files open). If no file is open, then the focus goes to the blank area, but as there is no selectable element there, then nothing shows as outlined.

example with screenreader on to see where the focus is.
https://github.com/microsoft/azuredatastudio/assets/31145923/9bf53b49-abaf-47e6-b881-1002840fcc1d

**Comment by kisantia** [comment]
Upstream issue - filed an issue for this in VS Code: https://github.com/microsoft/vscode/issues/191027

**Comment by kisantia** [comment]
@PoojaNamde the upstream team says this is working as designed. Please follow up with them on questions on the linked issue above.

**Comment by kisantia** [comment]
@PoojaNamde any updates on this?
