### ISSUE TITLE
Text in Extension Manager extension readme doesn't pick up color theme settings correctly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23553]
The text in the Extension Manager extension readme page seems to picking up system colors rather than color theme styles.  This creates some readability issues in when the system has High Contrast mode on.  The below screenshot shows an example.

![image](https://github.com/microsoft/azuredatastudio/assets/599935/49d2b061-efd0-4088-80a0-532b384d29ef)

**Comment by alanrenmsft** [comment]
@kburtram this turns out to be a vscode issue, i can also reproduce it. I'll open one for vscode.
![image](https://github.com/microsoft/azuredatastudio/assets/13777222/6b3cb8e4-67bf-4a45-9456-b95d6263e14c)

**Comment by alanrenmsft** [comment]
opened this issue in vscode repo: https://github.com/microsoft/vscode/issues/186682
