### ISSUE TITLE
Azure Tree subitem icons are missing

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23554]
The icons for subitems under SQL Servers and SQL DB in the Azure Tree are missing, such as for Schemas, Tables, etc.  This is a follow-up to https://github.com/microsoft/azuredatastudio/issues/23531, but I'm not sure if this is by design or related impact from that previous bug. 

![image](https://github.com/microsoft/azuredatastudio/assets/599935/4039ab25-6d61-4d3e-8dc8-7491aa062a34)

**Comment by kburtram** [comment]
@cheenamalhotra could you please confirm if this is by design or a remaining bug following vscode source refresh?

**Comment by cheenamalhotra** [comment]
Likely a remaining bug.. these icons appear in stable build. I will take a look!
