### ISSUE TITLE
Copy-pasting multiple columns is incorrect

### ISSUE THREAD

**Issue by abist** [Microsoft/azuredatastudio#2356]
- SQL Operations Studio Version: release branch

Steps to Reproduce:

1. Run any query to get the result query grid.
2. Click on any column to select that column for all the rows.
3. Hold Shift and click another column to select it as well.
4. Copy-paste the selection.

Expected - Either multiple selection is disabled or copy paste works like the actual selection.

Actual - Cope-paste works but the columns are one after the other instead of being side by side.

**Comment by anthonydresser** [comment]
dupe #26
