### ISSUE TITLE
Connecting in Query Editor breaks connection in Servers view

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23562]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Connect to a server in Servers view
2. Open a new query editor that doesn't auto-connect to the same server.  For example, set focus into the Welcome page prior to running New Query command.
3. Connect the new query editor to the server from step 1 using the Connect button in the Query Editor.

Expected: Both the Servers and QE window are connected to the same server and working correctly.

Actual: Connecting to the server in QE breaks the connection in the servers view.  The connection does a busy spin wait forever.  I confirmed this issue is not present in previous stable build and was in the insiders build prior to recent vscode merge.  It is likely from the connection URI changes (if I had to guess).

![image](https://github.com/microsoft/azuredatastudio/assets/599935/e8f93c95-eecc-4b18-a97e-f569447e5566)

**Comment by cheenamalhotra** [comment]
Figured this is related with https://github.com/microsoft/azuredatastudio/issues/23501 (Fix for https://github.com/microsoft/azuredatastudio/issues/6406 introduced by https://github.com/microsoft/azuredatastudio/commit/89386c9c11c704243b908c34d05201966a426d0d)

Reverting the commit fixed the issue, fyi @smartguest
