### ISSUE TITLE
Post Merge > running USE database statement in query editor doesn't change the database context

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23565]
Version: 1.45.0-insider (user setup)
Commit: 8d0ba0fe1217ada55a6fee01b66b3bdc4c898ff3
Date: 2023-06-29T07:55:27.790Z
VS Code: 1.79.0
Electron: 22.3.10
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1. Open Query Editor (default database is master)
2. Type a USE database statement (e.g. USE WideWorldImporters)
3. Run the query.  The database context doesn't change.

Database context can be changed manually via the drop down.

Interestingly, the intellisense does pick up context.  Specifically, with master selected as the database in the drop down, and both the USE statement and a query in the editor, prior to running the query, there are squiggly lines underneath the table names, etc.  After running the USE statement, those disappear.

**Comment by kburtram** [comment]
FWIW, this appears to repro on an insiders build from before the vscode merge, but does not repro on the current stable build.  That doesn't really change anything other than were we should look for the regressed code (e.g. in STS).

**Comment by smartguest** [comment]
Testing has indicated that this is not caused by the recent change to a new connection string, the issue existed before the STS change to a new connection URI format and the connection title update. So that can be ruled out.

**Comment by cheenamalhotra** [comment]
It seems to have occurred with PR https://github.com/microsoft/azuredatastudio/pull/23363. 
I've ruled out STS updates and confirmed that STS v4.8.0.19 works fine with previous commit before this change.

@alanrenmsft fyi

**Comment by cheenamalhotra** [comment]
This is related with "dataprotocol-client" upgrade to 1.3.5 as doing just that on previous commit leads to same issue. 

The PRs that were part of the upgrade:
- https://github.com/microsoft/sqlops-dataprotocolclient/pull/85
- https://github.com/microsoft/sqlops-dataprotocolclient/pull/86

The impact of the change is that:
- Call to ListDatabases doesn't happen on query execution, as before, until user manually clicks on the dropdown.
- Dropdown and Status bar doesn't update database in context - even though the current connection string is updated.
- If USE <> statement is proceeded with select query - the select query gets stuck!! The only way is to Cancel the QE manually.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/abb8f957-133a-48ac-96cd-aa14c673b67a)

My instinct says it may have to do with QueryEventListener and related code.. and possibly that post query events are not firing.. but I'm yet to peel off all the changes to understand the design and how it changed.. @alanrenmsft the impact may be larger than what's been observed so far.. can you take a close look to what went wrong with dataprotocol-client upgrade?

**Comment by Charles-Gagnon** [comment]
Ok, found the issue. Need to get a bit more information but should have a fix ready here shortly.
