### ISSUE TITLE
Escape key no longer reverts a pending edit while updating a cell value

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23579]
- Azure Data Studio Version: `main`

Steps to Reproduce:

1. Open Edit Data on a table
2. Edit a cell but do not navigate out of the embedded input box
3. Press ESC key to revert the pending edit

Expected: Changes to row are reverted and embedded input box is gone.

Actual: Nothing, the ESC key is ignored.

**Comment by kburtram** [comment]
@alanrenmsft this bug sounds similar to the issue your mentioned with SlickGrid not working properly with arrow keys.  If this isn't the same key of bug could you please let me know and I'll investigate what' going on.

**Comment by alanrenmsft** [comment]
let me give it a try on my local dev environment.

**Comment by alanrenmsft** [comment]
just tried, this is fixed by my changes
