### ISSUE TITLE
Updates to menu item ordering for server and database

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#23577]
The Refresh option for both server and database exists in the top half of the right-click menu (screenshot below).  With the addition of the new Properties dialog for databases and servers, it makes sense to align those and put them at the bottom of the menu, so the last three items would be (in order):

Enable Group by Schema
Refresh 
Properties 

![image](https://github.com/microsoft/azuredatastudio/assets/98599126/aa34ddc2-7c45-4d93-a777-f70c5db6ca9f)

**Comment by cheenamalhotra** [comment]
@erinstellato-ms 

This can be coupled with #22344 to create a new multi-level experience. Let me know what you think and if you can update the other issue instead with new proposed hierarchy?

**Comment by erinstellato-ms** [comment]
@cheenamalhotra yes - I was going to check with Design about a final recommendation.  Do you want me to update the other issue with what I propose (multi-level option) and then if Design has changes we can adjust?

**Comment by cheenamalhotra** [comment]
Yes, we can use the other issue for tracking OE menu updates with multi-level hierarchy. So I will proceed to close this one.
