### ISSUE TITLE
API proposals error for Github Copilot extension

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23588]
Insiders/main

I'm seeing this error on startup with the Github copilot extension installed : 

`Extension 'github.copilot' appears in product.json but enables LESS API proposals than the extension wants.
package.json (LOSES): inlineCompletionsAdditions, interactive, semanticSimilarity
product.json (WINS): inlineCompletionsAdditions, terminalDataWriteEvent`

**Comment by kisantia** [comment]
@lewis-sanchez can you please take a look at this one?

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, is this with the post merge version of ADS?

**Comment by lewis-sanchez** [comment]
The two API's we use are the only ones needed to embed suggestions into the editor. Karl added those in this PR: https://github.com/microsoft/azuredatastudio/pull/22805

**Comment by Charles-Gagnon** [comment]
Have you verified that not having those proposed APIs isn't going to cause any issues with the copilot extension?

**Comment by lewis-sanchez** [comment]
@Charles-Gagnon, yeah, I found that it didn't impact extension usage in a negative way, but I can also add the missing API to make API message go away from the console. I tested with adding the missing API and didn't see find anything that negatively impacted usage. I'll send out the PR and if we prefer to take it, we can take it or close this issue again.

**Comment by clemens-tolboom** [comment]
VSCode: My Java env is broken after enabling Copilot. Not sure I'm barking the wrong tree :-O
