### ISSUE TITLE
"Refuses to accept new listeners" when expanding tree nodes

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23596]
Insiders/main

1. Expand a couple nodes in the Azure view (or really any of our tree nodes - but Azure is probably easiest because there's so many more nodes there)
2. It starts off as "Potential listener LEAK" warnings, but then eventually after expanding/collapsing nodes a few times you start to see a huge amount of these warnings in the console : `REFUSES to accept new listeners because it exceeded its threshold by far`

As indicated by the message - this results in the event listener never actually being attached : https://github.com/microsoft/azuredatastudio/blob/7a90e22cd485db6e5166c3ec58ed3fa469ff01ef/src/vs/base/common/event.ts#L951

Which is likely to cause problems later on if not addressed.

Callstack : 
![image](https://github.com/microsoft/azuredatastudio/assets/28519865/ab47af11-f3f7-4abd-804c-2c50e6d5a2bc)

The event causing this seems to be https://github.com/microsoft/azuredatastudio/blob/7a90e22cd485db6e5166c3ec58ed3fa469ff01ef/src/sql/workbench/contrib/views/browser/treeView.ts#L1498

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra FYI, seems like this was added in https://github.com/microsoft/azuredatastudio/pull/23530

**Comment by cheenamalhotra** [comment]
I can remove that from sql\workbench, but should we also remove it from vs treeview?
https://github.com/microsoft/azuredatastudio/blob/7a90e22cd485db6e5166c3ec58ed3fa469ff01ef/src/vs/workbench/browser/parts/views/treeView.ts#L1514

**Comment by Charles-Gagnon** [comment]
*shrug* We should probably figure out first what it's doing and what removing it would impact.

**Comment by cheenamalhotra** [comment]
Addressed it by using disposables in sql\workbench - as it's done in vs\workbench.
Since our code is modified - we needed to update it accordingly.

**Comment by lemonkey** [comment]
I also see this warning whenever VS Code no longer handles copying text to the clipboard (i.e., copy/paste no longer works). Only thing that fixes it is to reload.

`event.ts:1038 [7h6] REFUSES to accept new listeners because it exceeded its threshold by far
q @ event.ts:1038`
