### ISSUE TITLE
Null ref when expanding "Unsupported connection" node

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23604]
1. Create a connection for a non-MSSQL provider (such as PGSQL)
2. Uninstall the connection and reload ADS
3. Try to expand the node

The prompt asking to install the extension appears as expected, but the console has this error :

`TypeError: Cannot read properties of undefined (reading 'onReady')
    at wa.sendConnectRequest (connectionManagementService.ts:1372:53)`

**Comment by cheenamalhotra** [comment]
Adding to this, OE expansion doesn't end when clicking 'Cancel' on the popup.

@aasimkhan30 this part is likely related to async server tree - can you ensure the OE tree expansion ends on either selection in this case?
