### ISSUE TITLE
Compat Level dropdown value order for New Database dialog is inconsistent

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23649]
Starts off at 160, then jumps down to 100 and goes up from there. We should probably be ordering it high -> low and then just selecting whatever the current level is from the list.

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/daf48eda-84b5-4f1c-8f12-5c89ec4c066d)

**Comment by dzsquared** [comment]
also collation is oddly collated :)

**Comment by corivera** [comment]
SSMS selects the current version as the default value IIRC. Since we don't have access to the dropdown options in STS, putting that value first in the list was an easy way to implement it.
