### ISSUE TITLE
New Database dialog doesn't show name as required or have validation on required fields

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23651]
If you open the New Database dialog and try to click "Script" or "OK" immediately it pops up with an error saying Name cannot be empty. We should : 

1. Be showing the field as required in the UI (typically with a * next to it)
2. Have validation on the input box so it is highlighted in red if the input isn't valid
3. Disabling the OK and Script buttons until all fields have valid inputs (that are reasonable for us to check at least)

**Comment by corivera** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/23823
