### ISSUE TITLE
no new (+) icon on database folder when hovering

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#23655]
![image](https://github.com/microsoft/azuredatastudio/assets/12227241/0a6ad542-19ee-4dc0-9f24-83528a5d24bf)

items that support "new" (table, users) have a ➕ icon on the item when the mouse hovers over, but the database folder does not

![image](https://github.com/microsoft/azuredatastudio/assets/12227241/66859faf-49bd-4a5c-9a3f-d9d5c4ec844e)

**Comment by kisantia** [comment]
verified this is in the RC build
