### ISSUE TITLE
Default theme has changed in latest insider build

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#23668]
I installed today's insiders build on a clean machine without existing settings and the default theme seemed to match VS Code instead of the light theme we typically used.

![image](https://github.com/microsoft/azuredatastudio/assets/599935/bd39dbdb-2def-4064-ad9f-eae9fb1b332d)

**Comment by kburtram** [comment]
@alanrenmsft could you please check if this is a regression from the recent vscode source refresh?

**Comment by alanrenmsft** [comment]
@kburtram ack
