### ISSUE TITLE
No subscription found Azure Sql Migration Extension Error

### ISSUE THREAD

**Issue by bhavparikh** [microsoft/azuredatastudio#23709]
Type: <b>Bug</b>

Azure Sql migration fails to load and says "No subscriptions found", "No locations found" and "No resource groups found" on Step3. The Azure account is linked and all the subsciptions are listed in Azure data studio but Azure Sql migration Extension fails to load subscriptions, locations and resource groups. No errors under the OUTPUT window for "Extensions".

Extension version: 1.4.8
Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9700F CPU @ 3.00GHz (8 x 3000)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abhims14** [comment]
Hello, please ensure to provision and deploy the Azure SQL target first and extension should show you the subscription containing the Target.

**Comment by abhims14** [comment]
Hope with latest updated ADS version and ensuring the Resource group have the target deployed. This problem should not reoccur.
