### ISSUE TITLE
Database properties Script for IsLedger is empty

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#23719]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Create a database
2.Open Properties 
3. Check "IsLedger"
4. click on "Script"

Expected: valid script
Actual: USE [master]
GO

GO

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ssreerama** [comment]
Update: IsLedger property is immutable and cannot be altered once database has created. Treating this issue as workitem to make the property read-only. Thanks
