### ISSUE TITLE
New Database Dialog Sets SINGLE_USER by Default

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#23729]
(latest insiders bits, connected to SQL 2022 on-prem instance. Running on amd64 Mac)

- Open New Database dialog
- Input name
- Click "Script"

You'll find the following as part of the script:
ALTER DATABASE [db_name] SET  SINGLE_USER

**Comment by Charles-Gagnon** [comment]
Just realized the build isn't quiiiiiite done. So wait for this build to finish before testing

https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=206358&view=results
