### ISSUE TITLE
Collation dropdown is slow to load; any other options?

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#23724]
The Database properties collation dropdown takes 500ms - 5s to load on my computer.  Is there anything we can do to ease this?

Ideas:

* Select core language first (e.g. Begali), then options second (e.g. `CI_AI`, `CI_AS`, etc.)
* Preload more of the drop-down (after the dialog opens, but before the dropdown is clicked, if possible)
* Typing dropdown filter (similar to how quickpicks work)

**Comment by corivera** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/23648
