### ISSUE TITLE
Add validation to not allow empty value for Maximum Server Memory

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#23722]
There's validation to make sure the Max server memory is greater than or equal to 128, but if you leave it blank then it enables the "OK" button and sets it to 0

https://github.com/microsoft/azuredatastudio/assets/31145923/f7f79b10-7e8d-4599-928c-d08f314194f9

**Comment by Benjin** [comment]
Additional live validators would be very nice.  Any string that can't be blank, any number that can't be blank or negative.  I understand it's difficult to track down the specific ranges for every single item, but negative and blank cases seem easy enough.
