### ISSUE TITLE
is ledger database option on <2022 databases

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#23735]
- Azure Data Studio Version:
- OS Version:

![2023-07-10_10-54-49 (1)](https://github.com/microsoft/azuredatastudio/assets/12227241/e8eedd03-7146-48bc-93b2-8d338f43392d)

Steps to Reproduce:

1. open database properties dialog on database with compat level 150
2. set "is ledger database" to checked (enabled)
3. click script
4. information message "there is no action to be scripted" - doesn't give the user a hint that this feature is incompatible with the database

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by erinstellato-ms** [comment]
@erinstellato-ms finish testing

**Comment by erinstellato-ms** [comment]
@dzsquared I think this is a dup of https://github.com/microsoft/azuredatastudio/issues/23719 - it's not that it's not supported with the compat mode, it's that we don't script it at all.

**Comment by corivera** [comment]
Closing this issue since the field is now read only.
