### ISSUE TITLE
Update Server task never completes after updating max memory

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#23734]
Repro Steps
1. Open Server Properties dialog
2. Switch to Memory tab and decrement max memory by 1.
3. Hit OK.
4. A Task is added to the task view, but the task never completes, even after 5 minutes.

The server max memory is updated correctly, but the task doesn't finish. Interestingly, if you open the dialog again and change the memory again, the old task completes but the new one hangs.

**Comment by barbaravaldez** [comment]
This caused by this issue other issue: https://github.com/microsoft/azuredatastudio/issues/23718

**Comment by corivera** [comment]
Closing as duplicate
