### ISSUE TITLE
SqlToolService stopped working

### ISSUE THREAD

**Issue by liamdo** [Microsoft/azuredatastudio#2374]
Issue Type: <b>Bug</b>

I get "couldn't start client Azure Resource Provider, SerializationProvider and SqlToolsService".
Starting without any extentions doesn't make a difference.
Starting after removing the app and redownloading a new version doesn't make a difference. I've tried the current version, v-1 and v-2 back with no success.

Below are lines from the output.

Launching server using command /Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.28/MicrosoftSqlToolsCredentials failed.

Launching server using command /Applications/SQL Operations Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.28/SqlToolsResourceProviderService failed.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:48:41.576Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5557U CPU @ 3.10GHz (4 x 3100)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.86GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.31.4
profiler|Mic|0.1.2
whoisactive|Mic|0.1.1

</details>

**Comment by K0sM1c** [comment]
I've got the same errors.
Uninstalling and reinstalling the application did not solve the issue.
![error](https://user-images.githubusercontent.com/24754665/45146575-76858100-b1c3-11e8-946c-8fdd24c8349f.jpg)

**Comment by liamdo** [comment]
@K0sM1c What OS are you running on right now? Did this error just show up one day for you?

**Comment by K0sM1c** [comment]
I'm running Windows 10 and I've got these errors since a week or so.
I've got the impression that I started having these errors when I upgraded the mssql extension in Visual Studio Code, but I'm not entirely sure.

**Comment by alanrenmsft** [comment]
@ranasaria Currently, Are we logging anything for errors like this to help us track down the issue?

**Comment by liamdo** [comment]
Just for info, I have had this bug on my mac for probably more than a month. I can't remember exactly but I had to revert to Management Studio in the mean time. 
Oddly, I installed Ops Studio this inside my Windows 10 VM and it worked fine so this might be a tricky one to reproduce.

**Comment by ranasaria** [comment]
@alanrenmsft we do not have logging for this yet :(

**Comment by liamdo** [comment]
I ended up removing SQL ops completely and put in Azure Data Studio, now it seems to work.

**Comment by ranasaria** [comment]
Thanks for the update @liamdo. We have released logging support so if you run into this issue again in future, logs would be immensely helpful in getting to the bottom of it. 

Closing this issue for now.

**Comment by JFitzMan** [comment]
I get this error almost every time I update to a new version. I'm not sure what fixes it. Last time I thought running as administrator did it, but now it's happening again and that's not doing the trick. I've reverted back to the 5 most recent builds, all of which have worked for me previously, with no luck. I'd be happy to provide logs.
