### ISSUE TITLE
Non-Prod Az Sub NOT found in Step-3 Drop-Down

### ISSUE THREAD

**Issue by PGDominguez1964** [microsoft/azuredatastudio#23768]
I am trying to do a demo in Azure Data Studio using the Azure SQL Migration extension. My Non-Prod Azure Subscription (MCAPS-Hybrid-REQ-50717-2023-phdoming
/c1029e3a-8a8c-4cc6-8103-e6b83da312eb) is NOT listed during Step-3 of the migration process. It appears I need to be logged into that Non-Prod account within ADS to create an Azure Data Migration Service. Unfortunately, our Non-Prod Azure Subscription is linked to our @microsoft.com account, so I am not able to login directly. I had to request an External Azure Subscription to get around this issue.

Steps to recreate:

- Select 'Azure SQL Migration'
- Select 'Migrate to Azure SQL'
- Execute Step-1 (Database for assessment)
- Execute Step-2 (Assessment results & recommendations)
- Attempt to execute Step-3 (Azure SQL Target)
-- Select 'Azure Account'
-- Select 'Subscription': Non-Prod Azure Subscription is NOT listed in drop-down
![ADS-No Az Sub Listed](https://github.com/microsoft/azuredatastudio/assets/127969223/34302adc-5623-4b3e-a2d5-5e13f0887914)

**Comment by PGDominguez1964** [comment]
Have installed sql-migration-1.4.8 (hotfix).vsix Hot Fix & issue is now resolved. Currently waiting on GA version of Hot Fix.

**Comment by brian-harris** [comment]
Version 1.4.9 currently available in stable gallery.
