### ISSUE TITLE
Save As Excel - List index out of bounds

### ISSUE THREAD

**Issue by karlgreenwood** [microsoft/azuredatastudio#23769]
Type: <b>Bug</b>

1. Run a query
2. Save query results to Excel
3. Use Import Table Data wizard in Toad for Oracle (my use case) to import the data from the Excel file
4. Receive Error "List index out of bounds"
![TOAD List index error - 2023-06-06 132607](https://github.com/microsoft/azuredatastudio/assets/54817760/49854051-6636-48ff-9aa9-129276943c6a)
5. Open the Excel file in Excel, navigate cells, no substantive edits necessary but enough to register a change.
6. Save the Excel file in Excel
7. Attempt Import wizard again successfully

I assume there may be a glitch in the underlying file format/syntax, but I do not have the understanding of the internals to troubleshoot further. Resaving in Excel seems to fix the import error. I have attempted this with different queries from different servers. I'm not sure which tool or both are not aligning.

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|31.76GB (17.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|1.0.0
azuredatastudio-oracle|Mic|0.1.3
dacpac|Mic|1.13.0
import|Mic|1.5.5
net-6-runtime|Mic|1.1.0
powershell|ms-|2022.7.2
profiler|Mic|0.12.2
schema-compare|Mic|1.19.0
sql-database-projects|Mic|1.1.1

</details>

**Comment by cssuh** [comment]
Closing as no logs were provided.
