### ISSUE TITLE
When clicking on a result from the search pane, it takes you to the bottom of the document rather than the search point

### ISSUE THREAD

**Issue by tigerhawkvok** [microsoft/azuredatastudio#2376]
Issue Type: <b>Bug</b>

1. Have local files
2. Search globally (eg, a table name filtering on `*.sql`)
3. Click on a search result

## Expected

You're taken to the search result

## Actual

You're taken to the correct document with the search results highlighted, but the bottom of the document.

SQL Operations Studio version: sqlops 0.32.7 (b3766d7421bac5d8596eb2ce4980da5546325282, 2018-08-30T02:59:53.029Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (12.39GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|1.0.59
vscode-emacs-friendly|lfs|0.8.2
agent|Mic|0.31.4
profiler|Mic|0.1.2
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
This issue no longer repro's on the last stable build.  Thanks for reporting this bug!
