### ISSUE TITLE
Port fix for flaky unit tests to release branch

### ISSUE THREAD

**Issue by lewis-sanchez** [microsoft/azuredatastudio#23780]
This issue is to track the port for fixing the flaky unit tests caused by xterm not using DOM rendering.

**Comment by kisantia** [comment]
The canary builds have still had a test failing with the error `Error: Uncaught TypeError: Cannot read properties of undefined (reading 'getRasterizedGlyph')`. Was this fix supposed to also fix this flaky test that's been failing?

**Comment by Charles-Gagnon** [comment]
@kisantia Let's reopen the linked issue and include details on the test that's failing for investigation, it might be that the fix Lewis did didn't cover all tests

**Comment by kisantia** [comment]
Reopened the original issue. Will close this one
