### ISSUE TITLE
Search results not showing for books

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#23793]
Version: 1.45.0-rc1 (user setup)
Commit: 90fccfda34a4aed6bee24a454f5b92f29884cdb6
Date: 2023-07-12T03:59:45.962Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23493
Steps to Reproduce:
1. Open a book in Notebooks View
2. Search for a common word

<img width="184" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/34872381/92f12ce1-472c-421a-8d1b-ec316778ac14">

<img width="576" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/34872381/da8c0b8b-1b80-4dcd-b9ef-07c2a3eef1a8">

**Comment by MaddyDev** [comment]
Fixed by the above port.
<img width="1572" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/12754347/4577fe43-3441-40ed-b78f-28a393e9e6a8">
