### ISSUE TITLE
OE reports "database is not accessible" when database is in single user mode

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23829]
1. Create database with single user mode, e.g.

```sql
CREATE DATABASE [single_user]
GO
ALTER DATABASE [single_user] SET  SINGLE_USER 
GO
```

2. Try to expand the database in OE

The error displayed is `The database single_user is not accessible.`. But if I try to switch to the db manually the error I get from the engine is `Database 'single_user' is already open and can only have one user at a time.` which is much more useful of an error. To help users understand why the database isn't accessible we should be providing as much information as we can.

**Comment by cheenamalhotra** [comment]
@Charles-Gagnon 

Can you attach logs to understand where the error comes from?

**Comment by Charles-Gagnon** [comment]
Just put a database in single user mode and then try to expand it (instructions in the original description) 

The reason for why it can't expand isn't in question - this is more about the information we give to the user when an error happens and whether they are able to understand what actually happened.

**Comment by Charles-Gagnon** [comment]
Let me know if the instructions I gave aren't clear enough and I can walk you through it.

**Comment by cheenamalhotra** [comment]
From the logs it seems we get below errors:
```
Info Number 4060, Error State 1, Error Class 11, 
Error Message 'Cannot open database "single_user" requested by the login. The login failed.', Procedure '', Line Number 1

Info Number 18456, Error State 1, Error Class 14, 
Error Message 'Login failed for user 'sa'.', Procedure '', Line Number 1
```

So best case we can let this bubble up to error dialog, but this is what we're getting from server from external login attempt.

**Comment by Charles-Gagnon** [comment]
Let me look into a bit more when I get some time, it's unfortunate that the login error doesn't provide any useful information like the `use [single_user]` statement does though...

**Comment by Charles-Gagnon** [comment]
Going to close this given what you said above, we can reopen if other people hit this and are confused
