### ISSUE TITLE
Expanded node with error in OE will cause other connections being made to display error

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23830]
1. Expand a node that has an error in OE (for example, try to expand a database that's set to single_user)
2. Get error as expected, node is now in expanded state with error text (expected)
3. Make another connection for a completely different server
4. Connection succeeds, but an error is displayed for the original node expansion error

This seems to be a regression from 1.44 (although there amusingly we have a different bug where the database node is duplicated instead of showing the error node. But that bug at least seems to be gone)

**Comment by Charles-Gagnon** [comment]
@aasimkhan30 @cheenamalhotra Please triage for July

**Comment by cheenamalhotra** [comment]
Fix verified in latest RC build.
