### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by robinhalabicki** [microsoft/azuredatastudio#2386]
Issue Type: <b>Feature Request</b>

Could you add release notes to the auto update?  Or a link in the Help

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:30:28.766Z)
OS version: Darwin x64 17.7.0

**Comment by kburtram** [comment]
@robinhalabicki the release notes are available using the `Show Release Notes` command.  I'll discuss with PM about adding the command to the Help menu (most it was removed from the VS Code menu items to simply the menus a bit).


![image](https://user-images.githubusercontent.com/599935/44922730-04142d00-acfb-11e8-81e0-899b942b3a2c.png)

**Comment by kburtram** [comment]
There is now an option to view the release notes after update.  Thanks for the suggestion!
