### ISSUE TITLE
Horizontal scroll bar appears while displaying error message on dialog 

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#23865]
- Azure Data Studio Version: Latest
- OS Version: All

Steps to Reproduce:

1. Modify any dialog and save the changes that causes an error
2. Ex: open login dialog properties on a test user and remove the password and save, this generates the error.
3. It will generate the error banner at the top of the dialog along with the horizontal scroll bar.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by Charles-Gagnon** [comment]
Cory brought up that this might be because the vertical scrollbar is showing, which makes sense to me since it's taking up horizontal space. So I'd start there for investigation.

**Comment by corivera** [comment]
Issue no longer repros
