### ISSUE TITLE
Commands Fail to Execute with ADS on Mac Using PowerShell Kernel

### ISSUE THREAD

**Issue by stevebanik** [microsoft/azuredatastudio#23860]
- Azure Data Studio Version: 1.44.1
- OS Version: Darwin Kernel Version 22.5.0

Steps to Reproduce:

1. Open ADS
2. run 'whoami' in notebook with powershell as kernel

"play" spins, never-ending

**Comment by Charles-Gagnon** [comment]
We're unable to repro the issue ourselves, could you get the logs as instructed below so we can investigate further?

**Comment by Charles-Gagnon** [comment]
Closing this since we haven't had a response, let us know if you can provide more information and we can investigate further!
