### ISSUE TITLE
Create Project From Database fails when launched without DB context

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#23861]
![image](https://github.com/microsoft/azuredatastudio/assets/1609827/ecd9932e-35ac-4f98-b689-66634fc6c287)

The code checks to see if the connection profile is undefined, but a property is getting set on it unexpectedly, so the undefined check doesn't trigger, and an incomplete connection profile is getting passed to the connection service instead of skipping that flow.

Proposed fix: update conditional to check that the object is defined && that the connection profile at least has a the server set

![image](https://github.com/microsoft/azuredatastudio/assets/1609827/5a162f31-5cdc-4cbf-8a8e-9a5467243a86)

**Comment by kisantia** [comment]
verified this is fixed with the latest RC build and new version of the sql projects extension from the RC build drop
