### ISSUE TITLE
Support Per-User Installer

### ISSUE THREAD

**Issue by Bydia** [Microsoft/azuredatastudio#2387]
Issue Type: <b>Feature Request</b>

Can you make the installer install as a user install like Visual Studio Code?

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@Bydia we're in the process of merging the VS Code 1.26 source code which has the per-user install code.  We'll look into enabling this feature as part of that update.

**Comment by kburtram** [comment]
This is blocked on this bug https://github.com/Microsoft/azuredatastudio/issues/3352

**Comment by kburtram** [comment]
There is a per-user installer available with this insider build https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.6.  We'll publish a stable installer either in Dec or Jan based on testing.
