### ISSUE TITLE
erorr 40

### ISSUE THREAD

**Issue by qaisnafiz** [microsoft/azuredatastudio#23911]
Type: <b>Bug</b>

erorr 40 I need A suliotion

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (9.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

```[tasklist]
### Tasks
```

```[tasklist]
### Tasks
```

**Comment by kburtram** [comment]
Please add additional context to this issue if you require further assistance.  Thank you.
