### ISSUE TITLE
"trustServerCertificate" showing unnecessarily on connection hover

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#23930]
RC1

1. Create new connection with "trustServerCertificate" as true
2. Hover over connection

Title shows the trustServerCertificate value, even if it's the only connection for that server

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/3b67b3cb-0b81-4fb3-a757-2b86b5e8a9de)

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra FYI

**Comment by cheenamalhotra** [comment]
This is by design to show non-default advanced options on hover (fix for https://github.com/microsoft/azuredatastudio/issues/13274) - we had this discussed with @aasimkhan30 as well from OE perspective

**Comment by Charles-Gagnon** [comment]
Hrm, ok I guess that makes sense. Will be interested to see if people find this useful or annoying though - especially for a setting that we prompt them to enable when using a self-signed cert.
