### ISSUE TITLE
Azure tenant move to ignore list.

### ISSUE THREAD

**Issue by rishky-msft** [microsoft/azuredatastudio#23943]
- Azure Data Studio Version: 
- 
![image](https://github.com/microsoft/azuredatastudio/assets/102506628/d685a73c-2f30-4607-8159-65bd139581e2)

- OS Version:
![image](https://github.com/microsoft/azuredatastudio/assets/102506628/deb13d75-7ed9-4a68-809a-49d0128ae3f8)

Does this issue occur when all extensions are disabled?: Yes/No 

Error: Tenant found in ignore list, authentication not attempted. You can remove tenant 81927cc7-b253-495d-af3b-5b4b91bc8fa4 from ignore list in settings.json file: if you wish to access resources from this tenant.

Also,
There is one more user request: Can we make the error message more clear so that user can navigate to settings.json easily?

**Comment by cssuh** [comment]
Hi @rishky-msft, is the only ask here to make the error message more clear? If the user removes the tenant from the ignore list in the `settiings.json` file they should stop seeing this message.

**Comment by cheenamalhotra** [comment]
I think this setting should be removed now, now that we support tenant filtering and we wouldn't trigger authentication to all tenants unless user wants to expand the same.

cc @erinstellato-ms

**Comment by erinstellato-ms** [comment]
@cheenamalhotra removing the setting works for me - let's make sure we (meaning me :) update docs
