### ISSUE TITLE
Encounter MSB4236 Error But nuget.org Has Been Registered

### ISSUE THREAD

**Issue by heyheys** [microsoft/azuredatastudio#23978]
- Azure Data Studio Version: 1.44.1 (system setup)
- OS Version: Windows_NT x64 10.0.19045
- SQL Database Projects Version: v1.1.1
- SQL Server Dacpac Version: v1.13.0

Steps to Reproduce:

1. This is the first time I build a database project. I have this error message when building the project:

stdout: c:\Users\Kylie.Fu\Downloads\test\TestHiddenHistory\TestHiddenHistory.sqlproj : error : Could not resolve SDK "Microsoft.Build.Sql". Exactly one of the probing messages below indicates why we could not resolve the SDK. Investigate and resolve that message to correctly specify the SDK.
    stdout: c:\Users\Kylie.Fu\Downloads\test\TestHiddenHistory\TestHiddenHistory.sqlproj : error :   SDK resolver "Microsoft.DotNet.MSBuildWorkloadSdkResolver" returned null.
    stdout: c:\Users\Kylie.Fu\Downloads\test\TestHiddenHistory\TestHiddenHistory.sqlproj : error :   Unable to resolve 'Microsoft.Build.Sql (= 0.1.9-preview)' for '.NETStandard,Version=v0.0'.
    stdout: c:\Users\Kylie.Fu\Downloads\test\TestHiddenHistory\TestHiddenHistory.sqlproj : error :   MSB4276: The default SDK resolver failed to resolve SDK "Microsoft.Build.Sql" because directory "C:\Program Files\dotnet\sdk\7.0.203\Sdks\Microsoft.Build.Sql\Sdk" did not exist.
    stdout: c:\Users\Kylie.Fu\Downloads\test\TestHiddenHistory\TestHiddenHistory.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.9-preview' specified could not be found.
    stdout:     0 Warning(s)
    stdout:     2 Error(s)
    stdout: 
    stdout: Time Elapsed 00:00:00.25
    stdout: 
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\Kylie.Fu\\Downloads\\test\\TestHiddenHistory\\TestHiddenHistory.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\Kylie.Admin\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-1.1.1\\BuildDirectory"    … exited with code: 1
	>>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\Kylie.Fu\\Downloads\\test\\TestHiddenHistory\\TestHiddenHistory.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\Kylie.Admin\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-1.1.1\\BuildDirectory"   … errored out: Process exited with code 1

2. Running "dotnet nuget list source", got this:
Registered Sources:
      nuget.org [Enabled]
      https://api.nuget.org/v3/index.json

**Comment by dzsquared** [comment]
What .net sdks are installed?
```
dotnet --list-sdks
```

**Comment by heyheys** [comment]
7.0.203 [C:\Program Files\dotnet\sdk]

**Comment by dzsquared** [comment]
Potentially related to others reporting issues with MSBuildWorkloadSdkResolver under SDK 7.0.2xx
https://github.com/dotnet/core/issues/8395

If you don't have a reliance on .NET 7 for other workloads, a workaround may be to uninstall .NET 7 and install the .NET 6 LTS release.

tagging @zijchen in case I'm missing something before we transfer into the DacFx repo

**Comment by heyheys** [comment]
I uninstalled .NET 7 and installed .NET 6 LTS release, still got a problem.

>dotnet nuget list source
Registered Sources:
  1.  nuget.org [Enabled]
      https://api.nuget.org/v3/index.json

>dotnet --list-sdks
6.0.315 [C:\Program Files\dotnet\sdk]

**Error message:**
c:\Users\TestHiddenHistory.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.9-preview)' for '.NETStandard,Version=v0.0'.
    stdout: c:\Users\TestHiddenHistory.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.9-preview' specified could not be found.
    stdout: 
    stdout: 
    stdout: Build FAILED.
    stdout: 
    stdout: 
    stdout: c:\Users\TestHiddenHistory.sqlproj : error : Unable to resolve 'Microsoft.Build.Sql (= 0.1.9-preview)' for '.NETStandard,Version=v0.0'.
    stdout: c:\Users\TestHiddenHistory.sqlproj : error MSB4236: The SDK 'Microsoft.Build.Sql/0.1.9-preview' specified could not be found.
    stdout:     0 Warning(s)
    stdout:     2 Error(s)
    stdout: 
    stdout: Time Elapsed 00:00:00.52
    stdout: 
    >>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\TestHiddenHistory.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-1.2.0\\BuildDirectory"    … exited with code: 1
	>>> "C:\\Program Files\\dotnet\\dotnet.exe"  build "c:\\Users\\Downloads\\test\\TestHiddenHistory\\TestHiddenHistory.sqlproj" /p:NetCoreBuild=true /p:SystemDacpacsLocation="c:\\Users\\.azuredatastudio\\extensions\\microsoft.sql-database-projects-1.2.0\\BuildDirectory"   … errored out: Process exited with code 1

**Comment by kisantia** [comment]
@heyheys Can you try running dotnet nuget list source and make sure nuget.org is listed? If it isn't, please try adding it as mentioned in this comment: https://github.com/microsoft/azuredatastudio/issues/20240#issuecomment-1227478333

**Comment by kisantia** [comment]
Closing issue. Please reopen if this is still happening and more information can be provided
