### ISSUE TITLE
Azure AD - Universal with MFA support doesn't work on Redhat Linux

### ISSUE THREAD

**Issue by asharovarov** [microsoft/azuredatastudio#23975]
Type: <b>Bug</b>

When attempting connect to Azure SQL Database on Redhat Linux using "Azure Active Directory - Universal with MFA support" it fails with the following error "User account 'xxxx' not found in MSAL cache, please add linked account or refresh account credentials.

I tried everything here: 
https://github.com/microsoft/azuredatastudio/wiki/Troubleshoot-Azure-Authentication-Issues

The Azure Account is valid, I am able to browse  all Azure SQL DBs in our subscription in the "AZURE" tree of ADS. I tried removing it and adding back, but it didn't help.

One more bit, Connection to on-prem server using Windows Auth works.

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:10:44.473Z)
OS version: Linux x64 5.14.0-284.18.1.el9_2.x86_64
Restricted Mode: No
Preview Features: Enabled
Modes:

Extensions: none

**Comment by cheenamalhotra** [comment]
@asharovarov 

Could you please try installing the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) which should allow you to get unblocked.
Using the insiders build, run the command: `Azure Accounts: Clear Azure Account Token Cache` and reload ADS to add/refresh account credentials again.

**Comment by asharovarov** [comment]
I did what you suggested. Didn't help. Same error.

**Comment by cheenamalhotra** [comment]
Hi @asharovarov 

Please upload logs for investigation if issue continues to persist.

**Comment by asharovarov** [comment]
Hi @cheenamalhotra,

The issue still persists. But I need to clear the upload with the security team.

I can look for errors or specific sections in the logs if that would be helpful w/o uploading files.

**Comment by cheenamalhotra** [comment]
Yes you may find Azure log errors in the `Azure Accounts.log` file or `Azure Accounts` Output pane. 
For MSSQL log file, look for errors in `sqltools.log` file. You can launch with command: `MSSQL: Show Log file`

**Comment by asharovarov** [comment]
I didn't find any errors in the `Azure Accounts.log`.

But there is an error in `sqltools.log`

`23-07-26 13:44:13.6237493 pid:233528 tid:11 sqltools Information: 0 : Registering MSAL token cache with encrypted file storage
23-07-26 13:44:13.6309586 pid:233528 tid:11 sqltools Verbose: 0 : Before cache access, acquiring lock for token cache
23-07-26 13:44:13.6347223 pid:233528 tid:11 sqltools Verbose: 0 : Before access, the store has changed
23-07-26 13:44:13.6349381 pid:233528 tid:11 sqltools Verbose: 0 : Received IV and Key from callback
23-07-26 13:44:13.6360366 pid:233528 tid:11 sqltools Verbose: 0 : eventTID:233567 <sc.SqlConfigurableRetryLogicLoader.MakeFullPath|INFO> Looking for 'System.Security.Cryptography.resources' assembly in '/home/user_name' directory.
23-07-26 13:44:13.6360624 pid:233528 tid:11 sqltools Verbose: 0 : eventTID:233567 <sc.SqlConfigurableRetryLogicLoader.MakeFullPath|INFO> Looking for 'System.Security.Cryptography.resources' assembly by '/home/user_name/System.Security.Cryptography.resources' full path.
23-07-26 13:44:13.6363195 pid:233528 tid:11 sqltools Verbose: 0 : eventTID:233567 <sc.SqlConfigurableRetryLogicLoader.Default_Resolving|INFO> Looking for 'System.Security.Cryptography.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a' assembly that is requested by '"Default" System.Runtime.Loader.DefaultAssemblyLoadContext #1' ALC from 'null' path.
23-07-26 13:44:13.6389950 pid:233528 tid:11 sqltools Error: 0 : Could not read the token cache. Ignoring. Exception: System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at System.Security.Cryptography.SymmetricPadding.GetPaddingLength(ReadOnlySpan`1 block, PaddingMode paddingMode, Int32 blockSize)
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at System.Security.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Microsoft.SqlTools.Authentication.Utility.EncryptionUtils.AesDecrypt(Byte[] cipherText, Byte[] key, Byte[] iv) in /_/src/Microsoft.SqlTools.Authentication/Utility/Encryption/EncryptionUtils.cs:line 51
   at Microsoft.SqlTools.Authentication.Utility.MsalEncryptedCacheHelper.BeforeAccessNotification(TokenCacheNotificationArgs args) in /_/src/Microsoft.SqlTools.Authentication/MSALEncryptedCacheHelper.cs:line 199
23-07-26 13:44:13.6395854 pid:233528 tid:11 sqltools Verbose: 0 : After access
23-07-26 13:44:13.6397080 pid:233528 tid:11 sqltools Information: 0 : Released local lock
23-07-26 13:44:13.6428957 pid:233528 tid:11 sqltools Critical: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z] (azuredatastudio: 0.0.0.0) [Internal cache] Total number of cache partitions found while getting refresh tokens: 0
23-07-26 13:44:13.6449801 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z - 9a6dfb00-b9c1-4b23-a66e-5ab08f7ee263] (azuredatastudio: 0.0.0.0) IsLegacyAdalCacheEnabled: yes
23-07-26 13:44:13.6482670 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z - 9a6dfb00-b9c1-4b23-a66e-5ab08f7ee263] (azuredatastudio: 0.0.0.0) [Region discovery] Not using a regional authority. 
23-07-26 13:44:13.6487950 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z - 9a6dfb00-b9c1-4b23-a66e-5ab08f7ee263] (azuredatastudio: 0.0.0.0) IsLegacyAdalCacheEnabled: yes
23-07-26 13:44:13.6495239 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z - 9a6dfb00-b9c1-4b23-a66e-5ab08f7ee263] (azuredatastudio: 0.0.0.0) IsLegacyAdalCacheEnabled: yes
23-07-26 13:44:13.6507950 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z] (azuredatastudio: 0.0.0.0) Found 0 cache accounts and 0 broker accounts
23-07-26 13:44:13.6510137 pid:233528 tid:11 sqltools Information: 0 : False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.3 Linux 5.14.0-284.18.1.el9_2.x86_64 #1 SMP PREEMPT_DYNAMIC Wed May 31 10:39:18 EDT 2023 [2023-07-26 18:44:13Z] (azuredatastudio: 0.0.0.0) Returning 0 accounts
23-07-26 13:44:13.6521793 pid:233528 tid:11 sqltools Error: 0 : Authenticator.GetTokenAsync | Account not found in MSAL cache for user.
23-07-26 13:44:13.6529868 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 SqlError.ctor | ERR | Info Number 0, Error State 0, Error Class 20, Error Message 'User account 'email@email.com' not found in MSAL cache, please add linked account or refresh account credentials.', Procedure 'AcquireToken', Line Number 0
23-07-26 13:44:13.6541083 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 <sc|ActiveDirectoryAuthenticationTimeoutRetryHelper|GetCachedToken|Info>Retrieved cached token null.
23-07-26 13:44:13.6542140 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 <sc|ActiveDirectoryAuthenticationTimeoutRetryHelper|CheckCanRetry|Error>Cannot retry when cached token is null.
23-07-26 13:44:13.6544560 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 <sc.SqlInternalConnectionTds.LoginFailure|RES|CPOOL> 4
23-07-26 13:44:13.6547170 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 TdsParserStateObjectManaged.Dispose | Info | State Object Id 1, Session Id 55b23bb0-45df-4453-997f-9951da284ec4, Disposing session Handle and counters.
23-07-26 13:44:13.6548011 pid:233528 tid:14 sqltools Verbose: 0 : eventTID:233579 TdsParserStateObjectManaged.Dispose | Info | State Object Id 1, Session Id 55b23bb0-45df-4453-997f-9951da284ec4, sessionHandle is available, disposing session.
23-07-26 13:44:13.6579126 pid:233528 tid:11 sqltools Verbose: 0 : eventTID:233567 SqlConnection.Retry | Info | Object Id 1
`

**Comment by asharovarov** [comment]
A couple of things to note:

1. I have multiple subscriptions associated with my account. I saw that there were issues with that in the past.
2. I can see all the databases accessible by my account in ADS, so the account is valid and has access to Azure.

**Comment by asharovarov** [comment]
Hi @cheenamalhotra!
I wonder if you have any updates on the issue? Thanks.

**Comment by cheenamalhotra** [comment]
@asharovarov 

This should work with the latest release or the insiders build. If needed, please try clearing Azure account token cache and reloading ADS.

**Comment by kisantia** [comment]
closing this issue since it should be working, as mentioned above. Please reopen if this is still happening.
