### ISSUE TITLE
Fail to import columns as DateTimeOffset

### ISSUE THREAD

**Issue by michaeldaw** [microsoft/azuredatastudio#23988]
- Azure Data Studio Version: 1.44.1 user setup
- OS Version: Windows 11

Steps to Reproduce:

1. Use a CSV file with a column intended to be of type DateTimeOffset with the format '2023-06-01T:13:00:00-4:00'
2. Attempt to import the file, indicating that the column is of type DateTimeOffset(7)

The following exception is thrown:
```
---> System.InvalidOperationException: The given value '2023-06-01T:13:00:00-4:00' of type String from the data source cannot be converted to type datetimeoffset for Column <<column index and name>>.
```
The indicated value is definitely a DateTimeOffset. It should convert.

Does this issue occur when all extensions are disabled?: Yes/No
No. This is regarding the Sql Server Import extension

The support link for the extension links to this repo.

**Comment by ckaczor** [comment]
Maybe I'm not familiar with some edge case of the DateTimeOffset serialization format but is "2023-06-01T:13:00:00-4:00" a valid format?  I'm pretty sure the extra colon after the T is not correct.  If I try to use "2023-06-01T13:00:00-4:00" (removing the extra colon) then the import works correctly for me.

**Comment by michaeldaw** [comment]
In light of @ckaczor comment, this looks like a mistake on my part. I'm not sure how I let that extra colon in there, but ckaczor is correct.
This should probably be closed and ignored. 
Apologies for time spent pursuing it.
