### ISSUE TITLE
Select Session Dropdown not showing results

### ISSUE THREAD

**Issue by supertx2** [microsoft/azuredatastudio#23998]
Type: <b>Bug</b>

With this new update the Select Session dropdown are not showing previous created sessions

Extension version: 0.14.0
Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (7.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by supertx2** [comment]
I Downgraded Data Studio and now I event can't install the profiler.
"Unable to install version '0.14.0' of extension 'microsoft.profiler' as it is not compatible with Azure Data Studio '1.44.1'. Update to Azure Data Studio >=1.45.0 to install the extension."

Where can I find the older versions of the extensions?

**Comment by Charles-Gagnon** [comment]
@SakshiS-harma FYI

Unfortunately we don't have a list of previous extension install links - but they all follow the format defined in https://github.com/microsoft/azuredatastudio/blob/release/extensions/extensionsGallery.json

In this case you can get the previous (0.12.2) version of the extension from https://sqlopsextensions.blob.core.windows.net/extensions/profiler/profiler-0.12.2.vsix

Make sure you have extension auto-update turned off, otherwise it'll just revert back to the newer version on restart.

**Comment by SakshiS-harma** [comment]
@supertx2 The latest profiler extension update has dependency on the latest Azure Data Studio version, hence the error that you are receiving.
And for the original issue, I am able to repro it. Let me take a look.

**Comment by SakshiS-harma** [comment]
@supertx2 As a workaround for now, if you stop the session, the dropdown gets enabled and populates with the previous sessions.

**Comment by SakshiS-harma** [comment]
@supertx2 can you state the exact steps that you are following to repro the issue? I am able to repro it while a session is running, and I anticipate that we don't need to have the Session dropdown to be enabled while it is in a running state.

1. Is it when a profiler window is opened, without starting a session? 
2. Is it a regression? Has this happened before the release or is it the first time you are seeing this issue?

**Comment by supertx2** [comment]
@SakshiS-harma 
1. Yes, I just right click on the database connection to open the profiler and usually I close the create session window and the dropdown was populated with previous created sessions, I would choose my session and start it
2. Yup, It happened right after I updated data studio to the latest version, never happened before

**Comment by SakshiS-harma** [comment]
Thank you for confirming @supertx2 . I am working on a fix.

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.
