### ISSUE TITLE
Links to conversions are not working after starting a conversion or assessment in DSCT/DMAO

### ISSUE THREAD

**Issue by SrivenNookala** [microsoft/azuredatastudio#23994]
Type: <b>Bug</b>

1. Open DSCT or DMAO extension
2. Start any conversion/assessment.
3. After starting the conversion, links that open the assessment/conversion stop working. 

Specifically, calling the command registered with extension context are not working. (attached video)
We will work on this further and update as we find out more.

https://github.com/microsoft/azuredatastudio/assets/109157441/164fa77f-ef00-4f3a-ac6b-a0928e422894

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 1805)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (14.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-de|Mic|1.45.0
ads-language-pack-ru|Mic|1.45.0
azuredatastudio-dma-oracle|Mic|4.2.1
azuredatastudio-oracle|Mic|0.1.3
dsct-oracle-to-ms-sql|Mic|0.6.0
net-6-runtime|Mic|1.1.0
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0

</details>

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.
