### ISSUE TITLE
Stop showing copy notification

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#24009]
Type: <b>Feature Request</b>

I don't remember seeing this behavior before but starting with 1.45.0 every time I copy data from the query results window I get a notification in the lower right of the window saying the data was copied with a Close option. I want to disable this option. The reason I don't like it is:

1) It shows up to 3 notifications that honestly provide no real value over a simple notification in the status bar or equivalent.
2) The notifications don't go away so you have to close the message even though it is just a notification. 
3) Even though you only see 3 notifications on the screen, it appears that the others are still there because if you had, say 5, notifications then you have to close all 5 even though you only see 3 at a time.

I would like to request the following:

1) Make the notification a toast that automatically goes away after a few seconds. This is pretty standard for "non-critical" notifications.
2) Give me an option to not show this notification at all.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by chris-tietgen** [comment]
Tbh, I don't mind the notification as most of the time prior to this release the copy wouldn't even work using CTRL+C. At least now I will know. Hopefully copying has been fixed in general.

I agree with your two suggestions, though.

**Comment by rolovargas** [comment]
Please please please provide the option to disable this notification!
It's so unnecessary. 
I don't know of any other app that shows this kind of notification for a Copy.

**Comment by DrMarkX** [comment]
I agree, either have a toggle to turn off or a timeout setting on the notifications show they do not continue to stack.

**Comment by dubeg** [comment]
I wonder what prompted the team to add this "feature".

**Comment by cg-tm** [comment]
> I wonder what prompted the team to add this "feature".

My guess is a long-standing issue where data wouldn't copy to the clipboard immediately. For whatever reason data studio had to 'process' that for even basic stuff like a single cell. 

That's a lot better now so this popup/notification progress (similar to save as CSV/Excel) is now the confirmation the copy is 'done'

**Comment by stahler** [comment]
If you have three notifications you have to click on them multiple times to close.

**Comment by cheenamalhotra** [comment]
Yes indeed. The fix is now merged in main:
- Notifications will auto-close in 3 seconds (when they show up)
- You will have an option to disable them completely with below setting:
![image](https://github.com/microsoft/azuredatastudio/assets/13396919/2f8b135f-e7d8-45f6-b87c-904ea7a904b7)

**Comment by cheenamalhotra** [comment]
Will proceed to close this issue as fix is now available in the latest insiders build.
Thanks!

**Comment by PaulSpoerry** [comment]
I hate this so much I'm tempted to just install the insiders build just to not have to see it!

**Comment by barrygrow** [comment]
I too hate this so much, I am installing the Insiders Build 1.46.0!

**Comment by jagdishrajan** [comment]
While I prefer to stay with the main release I have to move to the insider's build because of how disruptive this feature is.  It's amazing that such a pointless feature implemented without a setting to turn it off has been so disruptive.

**Comment by jkmuka** [comment]
I hope future iterations will think through the UX more. Productivity and efficiency are some of what I believe many of us are seeking in ADS and this popup runs counter to that. Even if you try to ignore it and leave the 3 notifications, the top one is constantly refreshed whenever a new copy operation is performed. Our eyes are continuously scanning the results area for meaningful errors, results, server name, warnings, etc. This copy notification is a huge distraction and steals attention in even the most menial of tasks.

**Comment by anthonylevine** [comment]
I know this is closed, but I cannot express how frustrating it is to have to close pop-up notifications each time I hit Control + C. 
![image](https://github.com/microsoft/azuredatastudio/assets/4107984/bdf1f126-db64-4000-bcf9-ffaa7e753bb2)

**Comment by Charles-Gagnon** [comment]
If you update to the latest version we've added the ability to disable this notification.

**Comment by anthonylevine** [comment]
Thank you.

**Comment by richardtallent-erm** [comment]
While removing the pop-up is nice, can anyone tell me where we're tracking the issue that selecting a *single cell* and hitting Ctrl-C does not **IMMEDIATELY** push that data into my clipboard? Why is it taking 3-5 seconds to update the clipboard?

I could understand if I was trying to copy and paste thousands of records, which may not be loaded into the grid, but for copying text from a few rows and columns that are directly viewable on my screen should take milliseconds.
