### ISSUE TITLE
save file .sql in folder OneDrive

### ISSUE THREAD

**Issue by soouzza** [microsoft/azuredatastudio#2400]
Issue Type: <b>Bug</b>

I receive error:
"failed to save 'file.sql': insuficient permissions.

button Retry as Admin don't work

i'm open sql operations studio in Administrator mode, don't work too

the file saves normaly in other folder i.e. c:\temp but don't save in any folder in Onedrive folder

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17738

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3537U CPU @ 2.00GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (1.35GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.32.7
import|Mic|0.1.0
profiler|Mic|0.1.5
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if this issue is still impacting you.  Thanks!

From the description it sounds external to ADS as we rely on external dependencies to handle actually writing files to disk.
