### ISSUE TITLE
Recent Connections garbles first connection label in UI

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#24007]
Type: <b>Bug</b>

Starting with the latest 1.45.0 update the first connection in the Recent Connections window is garbled when it is first added.

1. Go to the Recent Connections list and clear it
2. Go to the Connections window and connect to any saved database connection
3. Go back to the Recent Connections list and the new connection shows up but is garbled text.

![image](https://github.com/microsoft/azuredatastudio/assets/38144840/c6e72e49-d95e-4d42-aeab-0bd25bce1d12)

I have found that if you close ADS and open it back up then the problem is resolved. However I saw it get garbled in at least one other scenario initially but assumed it was an oddity and I don't remember what I did.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
@cssuh can you help investigate the issue?

**Comment by cssuh** [comment]
Hi @mtaylorfsmb, I'm having trouble reproducing this issue, here are the steps I took:
1. Clear recent connections list
2. Connect to a saved DB connection
3. Open recent connections list

This is what I see: 
![Screenshot 2023-07-28 at 10 39 56 AM](https://github.com/microsoft/azuredatastudio/assets/18150417/6129ae99-ce90-4da1-9a74-a9a996a9a4e0)

Are there any other details you can share to help me reproduce the issue on my end? Additionally, do you see any errors in the developer tools console when running into this issue?

**Comment by cheenamalhotra** [comment]
This is most likely related with https://github.com/microsoft/azuredatastudio/issues/24027, let's keep an eye on it after the fix from PR #24038 arrives in insiders.

**Comment by mtaylorfsmb** [comment]
I have replicated the issue again and I think it reveals more of what the actual problem is. It might be related to the earlier mentioned issue, I don't know for sure. 

It appears that the UI is overwriting the labels for one row with another row. In my case I was in the state where my groups weren't showing up, just the first connection in the default group. I typed in the name of a group to trigger the loading of the groups in the UI. But of course that filters out by connection name so I then cleared the group name from the filter box. At that point the UI shows a progress indicator below the filter box that never goes away. At this point the UI gets garbled. It is not properly refreshing the list of items as you expand and collapse nodes causing the garbled text I saw originally, I believe.

![image](https://github.com/microsoft/azuredatastudio/assets/38144840/ca2c6fd2-8603-4321-adb9-0bbf0582b3e5)

**Comment by cheenamalhotra** [comment]
Hi @mtaylorfsmb 

The fix is now available in insiders, could you give that a try?

**Comment by mtaylorfsmb** [comment]
@cheenamalhotra Just a quick test of the Insiders build shows that it appears to be fixed.

**Comment by cheenamalhotra** [comment]
That sounds great! I will proceed to close the issue as fixed, please reopen if needed.
