### ISSUE TITLE
Recent Connections no longer adds new connections

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#24008]
Type: <b>Bug</b>

Starting in ADS 1.45.0 I see a difference in behavior (I believe) from what ADS used to do when connecting to a new data source. In previous versions if you used the `Connect` command to connect to a database and filled in the details then that connection was saved to the Recent Connections list. Starting with this update the only connections that seem to be added are those that are already saved under the Servers section.

1. Open a new query window.
2. Click  `Connect`
3. Type in the details for a new database connection in the `Connection` window's `Connection Details`.
4. Connect to the database.
5. Go back to the Recent connections list and notice the new database wasn't added to the list.
6. Instead of creating a new connection use the `Browse` tab to select an existing connection.
7. The saved connection is added to the Recent connections list.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (17.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
@smartguest can you pick up this issue for investigation?

**Comment by smartguest** [comment]
Fixed

**Comment by cheenamalhotra** [comment]
Re-opening for July hotfix consideration.

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.

**Comment by josborne-longevity** [comment]
I'm on 1.47.1 - I can't get any connections to appear in Recent.

**Comment by GridTrekkor** [comment]
I'm on 1.47.1 - this appears to still be an issue.  I can't get any connections to appear in Recent.

**Comment by drc-bsvee** [comment]
Same here. Recent connections list never saves.

**Comment by GridTrekkor** [comment]
@drc-bsvee I discovered (for me at least) that it will add to the recent connections list once you connect to a server over in the Connections panel on the left.

**Comment by drc-bsvee** [comment]
> @drc-bsvee I discovered (for me at least) that it will add to the recent connections list once you connect to a server over in the Connections panel on the left.

Yes, that workaround worked for me. Thank you!
