### ISSUE TITLE
Connection Browse tab delay initialization doesn't work properly

### ISSUE THREAD

**Issue by mtaylorfsmb** [microsoft/azuredatastudio#24027]
Type: <b>Bug</b>

Starting with the version 1.45.0 the delay initialization of the Browse tab of the Connection window doesn't work properly. What it is supposed to do is show you saved connections, including any groups that you have defined. What it actually does is just show you connections that aren't in groups. 

Pre-steps (important):
1. You need to ensure the Connections sidebar window is hidden when you start ADS. If it is open then this changes the behavior.
2. Create some connection groups with connections.
3. Ensure you have one connection that is not in any groups (aka it is in the default group).

1. Start ADS without the Connections sidebar window visible.
2. Open a new query window and click Connect. Then go to the Browse tab.
4. Notice that none of the connection groups show up. If they do show up then clear the recent list and restart ADS again. However the connection that is in the default group does show up.

There are several ways to get the groups to show up again.
1. Type the name of a group in the search bar at the top of the Browse window. In my case it always seems to work for one group but generatings a progress bar that doesn't go away for another group.
2. Alternatively open the Connections sidebar window. 
3. Start ADS with the Connections sidebar window not hidden.

In all of these cases the groups then show up in the Browse list. It seems like one of these actions cause the list to get initialized and therefore show up.

Another thing that I noticed as I tested more is that if you have no connections in the default group then it does properly load the connection groups in all cases. It is almost like it sees a connection in the default group and doesn't bother looking at the rest. But if it doesn't find any in the default group then it loads the rest of the groups.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (21.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by cheenamalhotra** [comment]
Closing as fix verified in release branch.
