### ISSUE TITLE
ADS hangs indefinitely after trying to apply Schema Compare changes

### ISSUE THREAD

**Issue by malthew** [microsoft/azuredatastudio#24025]
Type: <b>Bug</b>

Steps to reproduce:
1. Run Azure Data Studio (ADS) as admin
2. Compare two large databases from two different servers, with the exact same tables, except the target tables are missing FK connections and relations.
3. Assure that ADS will attempt to create said missing connections in target tables.
4. Hit 'Apply'

Expected result:
ADS applies previewed changes and displays the task first as "loading" and then either an error or successful task in the 'TASK' window at the bottom (just like in the GIF of the extension's page).

Actual result:
Nothing displays and no further actions can be made in the program until the program is completely closed and re-opened.

Extension version: 1.20.0
Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.78GB (1.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details>

**Comment by ttruong001** [comment]
After updating ADS to 1.45.0 and Schema Compare to 1.20.0, the Schema Compare tool runs indefinitely when comparing two SQL pool in Synapse Analytics. Is it the same bug?

**Comment by PFranks-blah** [comment]
Same issue.
Comparing a small database to its equivalent data project (for source control) takes minutes (previously a few seconds) to compare and clicking the apply button doesn't do anything other than disable the apply button.

ADS v1.45.0
SQL Server Schema Compare v1.20.0

**Comment by ttruong001** [comment]
It used to take 2-3 minutes to compare two databases and now it takes 2-3 hours to do that. It seems the tool scans the data as well instead of schemas only

**Comment by SakshiS-harma** [comment]
@ttruong001 , @PFranks-blah , @malthew Do you have any repro that you can share? I tried at my end and I wasn't able to repro the issue.

**Comment by SakshiS-harma** [comment]
> It used to take 2-3 minutes to compare two databases and now it takes 2-3 hours to do that. It seems the tool scans the data as well instead of schemas only

That shouldn't be the case. Have you seen perf issues with empty databases vs databases that have huge amount of data?

**Comment by ttruong001** [comment]
I tried comparing two sql pools in Synapse Analytics with space used of 28 GB for each and two databases in Azure Managed Instance with space used of 9GB for each. The one with Azure Managed Instance returns the result faster but it still takes over 1 hour.

**Comment by malthew** [comment]
> @ttruong001 , @PFranks-blah , @malthew Do you have any repro that you can share? I tried at my end and I wasn't able to repro the issue. Also, what type of sql instance are you connecting to?

Sorry, I'm not entirely sure what you mean by "type of sql instance". Unfortunately I cannot share the repo I used to reproduce the bug, however I can inform that the servers are running two different versions of SQL. My source is running version 12.0.2000.8 and my target is running version 15.0.4312.2 .

**Comment by SakshiS-harma** [comment]
Thank you for your responses, @ttruong001 , @malthew .
I am trying to narrow down the problem, hence checking- have you tried the latest insiders build? Do you still see the issue and are able to repro it consistently there?

**Comment by ttruong001** [comment]
Sorry we can only install GA version

**Comment by SakshiS-harma** [comment]
@malthew , @ttruong001 , @PFranks-blah I am hoping to send out a custom ADS build to test out a change with optimistic solution to this problem. Will any of you be willing to try it out to make sure it actually fixes the underlying issue?

**Comment by SakshiS-harma** [comment]
@malthew @ttruong001 @PFranks-blah just checking in to see if either of you can help with testing? The change is not a custom build, but a probable solution checked in. If any of you are willing to test the insiders, it will be great to make sure we are able to fix this issue.

**Comment by PFranks-blah** [comment]
Hi. I can test for you.

Regards

Paul Franks
Data Manager | CX Operations Prof Services

**Comment by SakshiS-harma** [comment]
@PFranks-blah thank you so much for your response. Can you test the latest insiders build here: https://github.com/microsoft/azuredatastudio/tree/main#try-out-the-latest-insiders-build-from-main-branch . This should have the fix.
Let me know if it did/did not fix the issue.
Thanks again for your help!

**Comment by SakshiS-harma** [comment]
@PFranks-blah just checking if you had a chance to test the latest insiders build. Let me know if you still face this issue.

**Comment by SakshiS-harma** [comment]
@PFranks-blah hope you are doing good. I am closing this issue for now, since we have a probable fix for this issue in the latest insiders. Please re-open the issue if you find that this issue hasn't been fixed yet in the latest release. Thanks!

**Comment by aistvan** [comment]
With the february update the problem still persists.

Version: 1.48.0 (system setup)
Commit: 4970733324ef8254b7c22a5dc55af7f8a1dea93f
Date: 2024-02-27T00:05:08.293Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
