### ISSUE TITLE
VS Code Engine version is wrong

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24021]
It currently is set to 1.79.0, but the latest merge brought us up to 1.79.2. This means that any extension which requires 1.79.1/2 won't be able to be installed, even though they should be supported just fine.

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.

**Comment by Charles-Gagnon** [comment]
Reopening until I verify in RC build

**Comment by Charles-Gagnon** [comment]
Verified version updated in latest RC1 build
