### ISSUE TITLE
node-gyp checksum verification failing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24028]
Getting this on win-arm64 builds now. win-arm64 isn't officially supported until v19, with older versions now returning a 404. 

```
gyp WARN install got an error, rolling back install
gyp ERR! configure error 
gyp ERR! stack Error: win-arm64/node.lib local checksum 4c62bed7a032f7b36984321b7ffdd60b596fac870672037ff879ae9ac9548fb7 not match remote undefined
```

**Comment by cheenamalhotra** [comment]
Closing as fix has been merged to release branch.

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra I'm going to leave mine open until I verify the fixes in the RC builds

**Comment by Charles-Gagnon** [comment]
Build successfully published
