### ISSUE TITLE
Refresh Intellisense Cache freezes query and opening new connection

### ISSUE THREAD

**Issue by air-khogard** [microsoft/azuredatastudio#24045]
Version: 1.45.0 (user setup)
Commit: 8eff468100f02157f2219335f7a566d14451ca49
Date: 2023-07-24T18:22:12.106Z
VS Code: 1.79.0
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Connect to synapse pool
2. Run query, works fine
3. Ctrl-Shift-P Refresh Intellisense Cache 
4. No visual UI change to say Refresh is still running 
5. Try to run query again or start new connection
6. Query will freeze for minutes, connection will error out after minutes

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
Hi @air-khogard 

This is a known issue, see https://github.com/microsoft/azuredatastudio/issues/9170
However I don't see connection erroring out - it does cause significant delay, does your database has lots of tables/objects?

**Comment by air-khogard** [comment]
It seams to work fine on Azure SQL DB databases no matter how big, but struggle very badly on Azure Synapse sqppool instance. The Synapse instance does have a lot of objects but not the most I have seen.

**Comment by cheenamalhotra** [comment]
This issue has been fixed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and fix will be included in the upcoming release.
Closing as resolved :)
