### ISSUE TITLE
Copying of results to clipboard not working

### ISSUE THREAD

**Issue by Nikolai5** [microsoft/azuredatastudio#24043]
Type: <b>Bug</b>

If I try to copy the contents of a field, even a single field, it doesn't work. The first time I press a copy I get a progress bar/popup in the bottom-right of the window that says "copying.." and even if I wait for that to go away it hasn't actually copied the text to my clipboard.

After that the message doesn't appear but copy still seems to do nothing. It is the same if I right click and select copy or use the ctrl + c shortcut.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:11:05.791Z)
OS version: Linux x64 5.15.0-78-generic
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor (16 x 3743)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 2|
|Memory (System)|31.27GB (22.77GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|cinnamon|
|XDG_CURRENT_DESKTOP|X-Cinnamon|
|XDG_SESSION_DESKTOP|cinnamon|
|XDG_SESSION_TYPE|x11|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.5

</details>

**Comment by cssuh** [comment]
I was able to repro this issue, this is the error I'm getting in the Developer Tools Console when I try to copy anything from the query results.

![image](https://github.com/microsoft/azuredatastudio/assets/18150417/f601a02e-6a9f-4b52-b34d-1886cd941a57)

**Comment by cssuh** [comment]
@Nikolai5 can you try installing xsel as a workaroud? Seems like this worked for another user in #24066.

**Comment by Nikolai5** [comment]
> @Nikolai5 can you try installing xsel as a workaroud? Seems like this worked for another user in #24066. Meanwhile, we will be working on a fix.

It seems to work fine with xsel installed yeah. It looks like its related to a new feature where it tells you how many rows its copied, I guess due to previous complaints that the copy and paste from results seemed to be a little unreliable at times.

I guess a solution would be to add xsel as a dependency of the package so that it gets auto installed?

**Comment by jhubsharp** [comment]
I'm seeing this same issue on Windows 11. Here's what I see in DevTools:
```
ERR Object reference not set to an instance of an object.: Error: Object reference not set to an instance of an object.
	at \AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:694866
	at \AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:695160
	at Immediate.<anonymous> (\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\dist\main.js:2:695521)
	at process.processImmediate (node:internal/timers:466:21)
```

**Comment by cssuh** [comment]
@Nikolai5 The fix should be in the [latest insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), if you'd like to give it a try.

**Comment by jhubsharp** [comment]
@cssuh I downloaded the latest insiders build (1.4.7.0-insider) but this still doesn't work on Windows 11 with the same error in the dev tools:

ERR Object reference not set to an instance of an object.: Error: Object reference not set to an instance of an object.
	at c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682049
	at c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682343
	at Immediate.<anonymous> (c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682704)
	at process.processImmediate (node:internal/timers:466:21)

**Comment by cssuh** [comment]
@jhubsharp do you mind opening a new issue for this? Also, what type of server are you connected to?

**Comment by jhubsharp** [comment]
@cssuh new issue filed with details of which databases (both SQL Server) are having problems. Thanks for taking a look.
