### ISSUE TITLE
Query Plan XML no longer formatted

### ISSUE THREAD

**Issue by airtank20** [microsoft/azuredatastudio#24059]
Type: <b>Bug</b>
Updated ADS to v1.45.0
Run a query with Enable Actual plan activated.  
Right click the execution plan, select "Show Query Plan XML"
The XML is no longer formatted whereas previous releases I believe that it was formatted.  

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:20:47.177Z)
OS version: Darwin arm64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|12, 12, 11|
|Memory (System)|64.00GB (0.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
qpi|joc|0.1.6
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azcli|Mic|1.8.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
powershell|ms-|2022.12.1
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.20.0
sql-migration|Mic|1.4.9

</details>

**Comment by airtank20** [comment]
To try and clarify, it seems the line breaks are no longer included when viewing the query plan XML, thus it isn't formatting cleanly when viewing it.

**Comment by cheenamalhotra** [comment]
HI @lewis-sanchez 

Can you pick this one for next release? Thanks!
