### ISSUE TITLE
Recent connections list not populating

### ISSUE THREAD

**Issue by jevangelistfw** [microsoft/azuredatastudio#24056]
Type: <b>Bug</b>

Open Azure Data Studio, run a query, the connection screen pops up. Note the name of the top "Recent" connection. Go to Browse, and connect to a different connection. The query should run. Select Change above the query editor and the Recent list will not have the two connections it should, instead it is a jumbled mess of both the connection names in one entry.

Screenshot below shows this. The connections should be "P21 Prod" and "P21 Play" but are combined into one recent entry:

![image](https://github.com/microsoft/azuredatastudio/assets/141241529/29a53a38-1292-4ac0-b8d2-65821d8827b9)

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.1
sql-prompt|Red|0.2.12
sql-search|Red|0.4.1
vscodeintellicode|Vis|1.2.1

(3 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment]
Hi @jevangelistfw 

This had been identified in https://github.com/microsoft/azuredatastudio/issues/24027 and addressed in Insiders, will be included in upcoming patch fix.
