### ISSUE TITLE
Saved connections view is broken

### ISSUE THREAD

**Issue by robert-oh** [microsoft/azuredatastudio#24057]
Type: <b>Bug</b>

The browse tab for the saved connections is only displaying folders and in total only one saved connection, regardless of which folder is expanded. And the name of saved connection names is overlapping folder names.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10885H CPU @ 2.40GHz (16 x 2400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (12.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.5.0

</details>

**Comment by cheenamalhotra** [comment]
Hi @robert-oh 

This had been identified in https://github.com/microsoft/azuredatastudio/issues/24027 and addressed in Insiders, will be included in upcoming patch fix. Thanks!
