### ISSUE TITLE
xml column data not formatted anymore

### ISSUE THREAD

**Issue by OzBob** [microsoft/azuredatastudio#24067]
Type: <b>Bug</b>

when querying a column with an xml datatype,
clicking the column used to open a tab of formatted xml.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i9-13900KF (32 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (3.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|29%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
dacpac|Mic|1.14.0
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0
extra-sql-script-as|pac|0.5.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Similar to https://github.com/microsoft/azuredatastudio/issues/24059
