### ISSUE TITLE
Azure Connections not showing all tenants I have access to

### ISSUE THREAD

**Issue by basland** [microsoft/azuredatastudio#24061]
Type: <b>Bug</b>

As a BI and DWH consultant I have access to quite a few Azure tenants with databases, that I should be able to connect to in Data Studio. However, it seems I only get to see the first 10 tenants I got access to. No matter what I do, I cannot see Azure connections to newer tenants and that's quite annoying. 

I am 100% certain I have access to the tenants I don't see because, under servers, I can create connections to them just fine. Please fix the Azure connections. 

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:20:47.177Z)
OS version: Darwin arm64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|32.00GB (1.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
dacpac|Mic|1.14.0
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0

</details>

**Comment by basland** [comment]
[](url)
[1-Azure Accounts.log](https://github.com/microsoft/azuredatastudio/files/12247040/1-Azure.Accounts.log)

**Comment by cheenamalhotra** [comment]
Can you capture logs for event when you add your account? That's the place your tenants are retrieved from token.
Also, let us know if you see any discrepancy in list of tenants when compared with Azure Portal?

**Comment by basland** [comment]
> 

Where can I find those logs? 

And yes: in Azure Portal I see more tenants I have access to with my account (currently 2 tenants I can see in Portal I cannot see in ADS).

**Comment by cheenamalhotra** [comment]
You need to enable the logs as per above comment > Remove account > Restart ADS > Add account again > Fetch logs.

**Comment by basland** [comment]
The weird thing - after removing and enabling the account, the tenants show up. We can close this ticket for now - but I would suggest moving this to your development backlog as adding access to tenants will happen often, and if we need to remove and add back accounts every time that would be annoying.

**Comment by germanjc** [comment]
Although the ticket is closed and azure data studio will disappear in 20256, in case someone gets here, I get them to update the tenants adding the same account that already exists, and so I get lso tenants to which I have access, updated. No need to delete and add. Only 're-add'
