### ISSUE TITLE
Button Color Issue in Azure PostgreSQL migration extension

### ISSUE THREAD

**Issue by tanyaranjan1995** [microsoft/azuredatastudio#24077]
- Azure Data Studio Version: 1.45
- OS Version:

Steps to Reproduce:
1. Launch Azure PostgreSQL migration
2. Run an assessment and check page 3 i.e. View assessment result page.
3. The button text color has changed everywhere, though I’m able to click it.
Attaching image for before and after image for reference:
Earlier Image:
If you see under findings(47) we have 3 components: Summary/Features/Sever settings.
![image](https://github.com/microsoft/azuredatastudio/assets/121925167/27183c15-fe77-406d-8ce6-88b3bb39d1f1)
Now:
If you see under findings(47) we have 3 components: Summary/Features/Sever settings. 
Now the are grey and not clearly visible.
![image](https://github.com/microsoft/azuredatastudio/assets/121925167/d9c14783-6da1-431f-8662-27b2aaf2a9d1)
Similarly here for Recommendion Reason/ Source Properties:
![image](https://github.com/microsoft/azuredatastudio/assets/121925167/ba09dc36-6ce6-46ae-9c17-b49873fff6a6)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kenvanhyning** [comment]
Unfortunate but not a hotfix level issue if the UI is still generally readable.  Moving this to next release.

**Comment by smartguest** [comment]
Appears to be an issue with the extension itself rather than any code on the ADS side.

**Comment by smartguest** [comment]
@sagangwar Can you please take a look at this issue? You need to remove the hardcoded color used on the affected text as it does not respect the user's set ADS theme. We want it to inherit the wide-dialog element color.

Screenshot showing it set from the extension itself:
![Postgre SQL Migration Style](https://github.com/microsoft/azuredatastudio/assets/18018452/86060611-6f05-4e70-b74c-90845c02c1f0)

**Comment by tanyaranjan1995** [comment]
We will fix it going forward.
