### ISSUE TITLE
Incorrect sorting in notebook result

### ISSUE THREAD

**Issue by orcawave-dliu** [microsoft/azuredatastudio#24072]
Type: <b>Bug</b>

Notebook result does not follow the sorting in the sql query

example: 
I have a table with the following data
Name
David
Susan
Kent

if I do select name from table order by name asc
The sorting in the result returned in the notebook ignores the sorting in the query

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz (8 x 1690)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (1.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|1.0.0
cms|Mic|0.9.3
dacpac|Mic|1.14.0
import|Mic|1.5.5
managed-instance-dashboard|Mic|0.4.2
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0
whoisactive|Mic|0.1.5
sql-search|Red|0.4.2
simple-data-scripter|sea|0.1.6

</details>

**Comment by Charles-Gagnon** [comment]
@orcawave-dliu Can you include a screenshot of the query + results grid? It seems to work fine for me, so I want to make sure there isn't something going on with your setup that I'm missing

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/bc4b3aa7-e0ba-41d2-b32e-c2a049d5704e)

**Comment by cheenamalhotra** [comment]
Rrelated with https://github.com/microsoft/azuredatastudio/issues/24095 ?
