### ISSUE TITLE
Cannot read properties of undefined (reading 'serverInfo')

### ISSUE THREAD

**Issue by Serge-N** [microsoft/azuredatastudio#24088]
Type: <b>Bug</b>

This is really frustrating. The error above keeps happening after the last update.
To reproduce : Select a store procedure and click any the avaualbe menu options, For Example Script as Execute.

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (2.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azuredatastudio-mysql|Mic|1.0.0
cms|Mic|0.9.3
dacpac|Mic|1.14.0
datavirtualization|Mic|1.12.0
import|Mic|1.5.5
machine-learning|Mic|0.12.0
profiler|Mic|0.14.0
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
azdata-sanddance|msr|4.0.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @Serge-N 

Please provide us verbose logs for investigation, thanks!

**Comment by Serge-N** [comment]
This issue can now be closed. Seems to have been resolved in version 1.45.1.
