### ISSUE TITLE
Built-in tree filtering no longer working for Object Explorer

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24086]
Regression from 1.44

Previously, the built-in tree filtering allowed filtering tree nodes in OE by pressing ctrl+f and then selecting filter from the search/filter widget. This stopped working in 1.45.

1.44

![Filter144](https://github.com/microsoft/azuredatastudio/assets/28519865/416a0e42-c4f5-40f8-8431-742f9c8e031e)

1.45

![Filter145](https://github.com/microsoft/azuredatastudio/assets/28519865/a626afc6-8d4f-4648-be21-775de69cf3fa)

**Comment by Charles-Gagnon** [comment]
I'm also seeing some odd behavior with node expansion - if I expand folders while the filtering widget is opened then sometimes they'll disappear (I assume because it doesn't contain any nodes that fit the filter so gets filtered out?)

![FilterFolderDisappear](https://github.com/microsoft/azuredatastudio/assets/28519865/4173c8b7-b97a-4a22-ac75-d1df16708904)

**Comment by Charles-Gagnon** [comment]
It's possible this is related to https://github.com/microsoft/vscode-mssql/issues/17539 as well. Maybe something changed where the filtering doesn't apply if the node isn't expanded? That might explain some of the weird behavior we're seeing.

**Comment by cheenamalhotra** [comment]
It seems to be happening due to code here:

https://github.com/microsoft/vscode/blob/85daa35afb86202badbee79532537bf226961f25/src/vs/base/browser/ui/tree/asyncDataTree.ts#L272-L282

```
defaultFindVisibility: e => {
	if (e.hasChildren && e.stale) {
		return TreeVisibility.Visible; // most of the nodes fall in this category.
	} else if (typeof options.defaultFindVisibility === 'number') {
		return options.defaultFindVisibility;
	} else if (typeof options.defaultFindVisibility === 'undefined') {
		return TreeVisibility.Recurse; // if child nodes are unexpanded, shows all parent nodes recursively.
	} else {
		return (options.defaultFindVisibility as ((e: T) => TreeVisibility))(e.element as T);
	}
}
```

Which as per first condition determines that node has children and is stale, continues to keep them visible. 
It seems to be by-design in VS Code, for reference: https://github.com/microsoft/vscode/issues/66971

**Comment by cheenamalhotra** [comment]
Since this is related to VS Code's implementation, I don't think we intend to behavior as before to keep code in sync with VS Code.
I'll close this as an issue from upstream.
