### ISSUE TITLE
VSCode default new window doesn't fit in ADS

### ISSUE THREAD

**Issue by Duenke** [microsoft/azuredatastudio#24085]
Type: <b>Bug</b>

VSCode opens a new default tab with "select language or fill with template...etc" when no other tab is open.

This doesn't fit in ADS because 1) we are here to do sql and 2) the tab doesn't have the connection bar at the top. You HAVE to close this tab and open a new one to do any work, so it's a waste of time and clicks.

If this is totally intended, then note that "fill with template" does not do anything.

Also, I notice this tab opening kinda randomly as I am doing work and I do have valid tabs open. So this kinda clutters the tab row and causes confusion. I wish it didn't do that, and again, I just have to close it and open another new tab if I should need a new tab.

<img width="960" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/46510548/a182cf10-2d3e-4f17-b709-cb355d983daf">

Azure Data Studio version: azuredatastudio 1.45.0 (8eff468100f02157f2219335f7a566d14451ca49, 2023-07-24T18:22:12.106Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.59GB (20.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.82.15
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.20.0
sql-prompt|Red|0.2.12

</details>

**Comment by kisantia** [comment]
@Duenke thanks for the feedback! I have a PR out to change this to default to not opening anything in the editor when the welcome page "Show welcome page on startup" checkbox is unchecked, which is the same default behavior as vscode. Please note that if the `"workbench.startupEditor"` setting was previously already specified in your user settings as `newUntitledFile`, then you will need to update it to `none` to no longer see the untitled file on startup:

This is the setting in the settings UI or you can set it in your settings.json:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/d064cb35-4e65-4584-bdfb-3f3560bc633d)
