### ISSUE TITLE
Linux - Cannot Copy Results to Clipboard

### ISSUE THREAD

**Issue by photoTed** [microsoft/azuredatastudio#24090]
- Azure Data Studio Version: 1.45.1
- OS Version: Ubuntu 23.04

Steps to Reproduce:

1. Using a select statement get results.
2. Select the contents of a cell and copy with Ctrl-C, Shift-Ctrl-C, or with the right mouse menu select Copy or Copy with Headers.  Neither of the Linux clipboards (Ctrl-V or middle mouse button click) are populated.  The last copied text is pasted instead.

BTW, right-mouse-menu "Copy Headers" does work.

Does this issue occur when all extensions are disabled?: Yes.  I do not have any extensions installed.

**Comment by cssuh** [comment]
duplicate of https://github.com/microsoft/azuredatastudio/issues/24043, as a workaround please install the xsel extension

**Comment by photoTed** [comment]
Happy to but I don't know where to find it.

**Comment by photoTed** [comment]
Sorry, I thought you meant an azure extension not an OS package.  Installed with apt and it's now working.
