### ISSUE TITLE
Compare Details windows in no longer resizeable

### ISSUE THREAD

**Issue by Ligtorn** [microsoft/azuredatastudio#24107]
Type: <b>Bug</b>

in schema compare, when you select and object and the compare details section shows, it used to be a resizable window, but for some reason it is not any longer. You can see an example of it in the attached screenshot

The old issue was https://github.com/microsoft/azuredatastudio/issues/8276

![image](https://github.com/microsoft/azuredatastudio/assets/3890900/9ca352bc-f162-4b8f-869b-b4cbc934f00f)

Extension version: 1.20.0
Azure Data Studio version: azuredatastudio 1.44.0 (31bee67f005648cdc9186f28ef39b4f1d6585e0f, 2023-05-19T16:53:04.348Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-10900K CPU @ 3.70GHz (20 x 3696)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|63.78GB (41.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@Ligtorn is this a regression from the previous release? The schema compare window hasn't been resizeable before as it was hardcoded to have a height of 800px in the 1.45 release and all the releases before that.

The recent fix for the original issue, https://github.com/microsoft/azuredatastudio/pull/23910 will be included in the upcoming September release and makes it so that the whole window height is used to display the schema compare split view.

**Comment by Ligtorn** [comment]
@kisantia I dont know, if the issue existed in previous versions, as it is the first time, I use database projects in ADS. I just noticed the issue, and that, it have been reported/fixed before

But looks forward to see it fixed again

**Comment by kisantia** [comment]
Got it, yes this was fixed in main a few weeks ago, but a new version of the extension has not been released yet. This will be available in the upcoming September release.
