### ISSUE TITLE
couldn't start flat file import wizard

### ISSUE THREAD

**Issue by neiltownend** [microsoft/azuredatastudio#24117]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Couldn't start client Flat File Import Service
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
@neiltownend 

Please provide more info - what error are you facing?

**Comment by cheenamalhotra** [comment]
Closing as not enough info available.
Please re-open when you have more details to provide.
