### ISSUE TITLE
SQL Server Profiler feature request

### ISSUE THREAD

**Issue by Susja** [microsoft/azuredatastudio#24124]
Hello. I hit this issue when started to use SQL Server Profiler. It works fine but at the end when I stop profiling I don't have an option to save Results grid for Analysis.

I would suggest adding the feature to Save Results.

I don't have any alternative for it.

**Comment by cheenamalhotra** [comment]
Hi @Susja 

We have an open enhancement request for the same: https://github.com/microsoft/azuredatastudio/issues/12987
Closing this as duplicate request.
