### ISSUE TITLE
DACPAC build failures after upgrading to version 1.2 of the SQL Database Projectes extension (macOS)

### ISSUE THREAD

**Issue by JeremySkinner** [microsoft/azuredatastudio#24142]
- Azure Data Studio Version: 1.45.1
- OS Version: macOS Ventura 13.4

Steps to Reproduce:

1. Ensure the SQL Database Projects extension is installed (1.2.0)
2. Open SQL Project previously upgraded by Azure Data Studio
3. Build

The following error occurs:

```
stdout: /Users/jskinner/.azuredatastudio/extensions/microsoft.sql-database-projects-1.2.0/BuildDirectory/Microsoft.Data.Tools.Schema.SqlTasks.targets(451,5): error MSB4216: 
Could not run the "SqlModelResolutionTask" task because MSBuild could not create or connect to a task host with runtime "NET" and architecture "arm64".  
Please ensure that (1) the requested runtime and/or architecture are available on the machine, and (2) that the required executable "MSBuild.exe" exists and can be run. 
```

This error didn't occur with version 1.1.1 of the SQL Database Project extension, but it doesn't seem possible to downgrade to the older version as it's no longer available to install. This seems related to working on a mac as its mentioning arm64. 

Please let me know if you need any further info. 

Does this issue occur when all extensions are disabled?: N/A (requires the SQL project extension)

**Comment by kisantia** [comment]
Looks like the same error as reported in https://github.com/microsoft/DacFx/issues/275. @JeremySkinner is this for an SDK-style .sqlproj? If it is, can you try setting the SDK version to `0.1.9-preview` in the .sqlproj?

**Comment by JeremySkinner** [comment]
hi @kisantia no, unfortunately it's not a SDK project. This is an old-style sqlproj that's had the compatibility process done [that's described here](https://learn.microsoft.com/en-us/sql/azure-data-studio/extensions/sql-database-project-extension-build-from-command-line?view=sql-server-ver16#non-sdk-style-sql-projects)

**Comment by kisantia** [comment]
Got it, there's one more thing to try that I expect will fix this. Old-style (also called legacy sql projects) sql projects now get built with the dlls from the Microsoft.Build.Sql SDK, and the default version got bumped to 0.1.10-preview in the latest release. Can you try setting the version to 0.1.9-preview in the settings? This is the setting:

![image](https://github.com/microsoft/azuredatastudio/assets/31145923/d24c30e7-6756-4b54-8856-dc0fe1fe4b08)

**Comment by JeremySkinner** [comment]
hi @kisantia unfortunately that doesn't make a difference - same error message.

**Comment by kisantia** [comment]
Forgot to mention to also restart ADS after changing the setting. Can you try that too?

If that doesn't work, you can download the previous version of the extension here:
https://sqlopsextensions.blob.core.windows.net/extensions/sql-database-projects/sql-database-projects-1.1.1.vsix

**Comment by JeremySkinner** [comment]
hi @kisantia yes that worked after a restart, switching back to 0.1.9-preview seems to work after a restart. Thanks so much for the help!

**Comment by kisantia** [comment]
Glad to hear that worked! The actual bug fix has already been made and will be in the next release of the Microsoft.Build.Sql sdk and expected to also be brought in the next ADS release in September.
