### ISSUE TITLE
Execution plan - Actual and Estimated do not show any results

### ISSUE THREAD

**Issue by VisualMicro** [microsoft/azuredatastudio#24145]
Type: <b>Bug</b>

Title speaks for itself

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by cheenamalhotra** [comment]
Can you please let us know what Query are you running that doesn't show Query plan on enabling it?
Logs would be useful too.

**Comment by VisualMicro** [comment]
For logs etc, we would prefer to use microsoft connect or other reporting system that is not public.

I can say that the sql is a stored proc that uses a cte against a sql view. the sql view uses a sql function to get the data of each columns. The view has 440 columns. The cte result is used by the stored proc to lookup additonal information from related tables. The data is returned correctly, in a few seconds.

**Comment by lewis-sanchez** [comment]
Hi @VisualMicro, are both estimated and actual query execution plans still not working for you with the latest insider version of Azure Data Studio (Version 1.46.0-insider)?

**Comment by cheenamalhotra** [comment]
Closing as we haven't received more info on the issue.
Let us know if you continue to face issue with error from logs if possible.
