### ISSUE TITLE
SQL Migration Extension: No assessment saved when there are no issues

### ISSUE THREAD

**Issue by DOliana** [microsoft/azuredatastudio#24165]
Type: <b>Bug</b>

1. setup a vm with SQL Server 2016 and two databases that could be migrated without issues to Azure SQL database
2. start migration
3. Select any target in step 2
4. click view/select
5. observe that no database has issues
6. click on "save assesment report" and select destination folder
7. observer the folder being empty

Extension version: 1.4.9
Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11370H @ 3.30GHz (8 x 3302)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (12.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Ramudaykumar** [comment]
This bug is not reproducible as I am able to save assessment Json report for different version of SQL server including SQL server 2016.
