### ISSUE TITLE
Query Results Options

### ISSUE THREAD

**Issue by mcneely6071** [microsoft/azuredatastudio#2417]
In SSMS under Options -> Query Results -> SqlServer -> Results to grid
The option to set a Maximum characters retreived for XML/Non-XML data is configurable
In my use case I have a varchar(Max) field containing a JSON string that I would like to be able to copy out and because it is over the character limit, it is getting truncated.  If I cast it as XML it is still limited by some restriction.  I would like to be able to change these limits to accomidate.   I have also noticed that on the data I am using cast to xml returns much slower in sqlopsstudio than in SSMS running the same query.   

The end goal is that I would like to be able to get the entirety of the data whether or not that is present in the grid or a click link to the data using XML.

**Comment by jmgalzate** [comment]
Hi there, 

Why on ADS we can't modify the NON-XML max chars to show?

![image](https://user-images.githubusercontent.com/88916499/129786853-a8dcc491-e1b7-4a93-9daa-be968f92b6fb.png)

![image](https://user-images.githubusercontent.com/88916499/129786962-891ff156-fe97-44a2-a419-5de378da2b72.png)

**Comment by kburtram** [comment]
These options are now available in ADS User Settings.  Please let us know if you are having any issues with these settings.  Thanks!

**Comment by jmgalzate** [comment]
Hi there, 

@kburtram, to clarify, the new feature is this? 

![image](https://user-images.githubusercontent.com/88916499/133495036-b7add1ff-c761-468a-a116-60fdeebbcf74.png)

Thank you!

**Comment by kburtram** [comment]
@jmgalzate I believe that is the setting to control the amount of data retrieved from large text columns.  The setting for JSON/XML/BLOB would be the one I referenced above.  

@cavonac is looking at a related bug where this particular setting may be getting overridden in the query execution code (apparently as some type of perf optimization).  The related issues are https://github.com/microsoft/azuredatastudio/issues/392 and https://github.com/microsoft/azuredatastudio/issues/15672 if you have any follow-ups on the behavior of this setting.  Thanks!

**Comment by jmgalzate** [comment]
@kburtram sorry but on my ADS version, I haven't seen yet the option. Do you know if I can configure it with the JSON key directly? Like this: 

"mssql.query.maxXmlCharsToStore": 2097152

Maybe: 

"mssql.query.maxJsonCharsToStore": 2097152

My version: 
![image](https://user-images.githubusercontent.com/88916499/133538131-5655bc49-7c82-4e21-9883-958f94619119.png)

Thanks!

**Comment by kburtram** [comment]
@jmgalzate you should be able to locate the setting in the Preference UI by filter with the search term `XML`.  If you prefer to set in the JSON file directly you can use the following key: `"mssql.query.maxXmlCharsToStore": 10000`.

**Comment by jmgalzate** [comment]
Dear @kburtram ok, now, if I understood well, the issue you close here is just for xml result data, but I'm asking for the json result data.

Must I create a mew issue?
