### ISSUE TITLE
how to relogin or change github account of Azure Data Studio

### ISSUE THREAD

**Issue by Shixin-Tang** [microsoft/azuredatastudio#24173]
Type: <b>Feature Request</b>

I have installed Azure Data Studio on my Macbook pro. And I installed GitHub Copilot Extension. The first time I login my github account successfully. But I need to change to another github account which has copilot subscription. But there is no feature to log out or sign out the github account and relogin with another github account.

Azure Data Studio version: azuredatastudio 1.45.1 (Universal) (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:36.656Z)
OS version: Darwin x64 21.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by phnogues** [comment]
I found a solution (not the best one)
Go to AppData\Roaming\azuredatastudio\User\globalStorage\state.vscdb replace your github login by the new one
Be careful, you may lost some saved password.

I hope MS will add the option to manage GitHub account as it is in VS Code

**Comment by gauravkumar796** [comment]
Hi, I can't even login with GitHub account, everytime it opens up a window in browser to sign-in with Azure account.

**Comment by cheenamalhotra** [comment]
We could consider supporting commands for `GitHub Copilot: Sign In/Sign Out` - @lewis-sanchez ?

**Comment by peter-curiousit** [comment]
To elaborate on @phnogues comment, I was able to remove the GitHub creds from my ADS with:
```sh
sqlite3 state.vscdb "delete from ItemTable where key like '%github%';"
```

The above command needs to be run in your globalStorage folder:

Linux:
```sh
~/.config/azuredatastudio/User/globalStorage
```

Windows:
```cmd
<user>\AppData\Roaming\azuredatastudio\User\globalStorage
```

Requires sqlite3 CLI to be installed (e.g. `sudo apt install sqlite3`)

**Comment by avinewman** [comment]
@phnogues  Deleting the file AppData\Roaming\azuredatastudio\User\globalStorage\state.vscdb worked for me.

**Comment by kisantia** [comment]
@lewis-sanchez should this be supported now that https://github.com/microsoft/azuredatastudio/pull/25014 was merged?

**Comment by lewis-sanchez** [comment]
@kisantia, yeah, this should be supported. PR #25014 allowed users to log out. The Copilot extension would then prompt the user to sign back in, but in some cases the user would need to close and reopen Azure Data Studio for the extension to trigger the prompt to sign back in with the same or different account.

**Comment by kisantia** [comment]
Closing this issue since it is now supported in [insiders](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and will be available in the next release.
