### ISSUE TITLE
Extra GO when scripting drop database

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#24189]
If both "Close existing connections" and "Delete backup and restore history information for database" are selected, then the generated script has an extra `GO` (line 6)
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/9abf884b-8e5d-4eae-8b7c-a005d9c5d325)

Also happens when only "Close existing connections" is selected

**Comment by corivera** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/25224
