### ISSUE TITLE
Failure to drop a database still deletes backup history

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#24194]
1. Create a new database (e.g. ADSTest)
2. Run a couple backups on the database (BACKUP DATABASE [ADSTest] 
TO  DISK = N'C:\Backups\ADSTest1.bak' 
WITH INIT,  STATS = 10)
3. Verify the backups exist in msdb (select database_name, backup_finish_date, *
from msdb.dbo.backupset
order by backup_set_id desc)
4. Open a query editor, make sure the context is the ADSTest database, create a table in the database (create table dbo.test (col1 int)) and leave the query editor open  (OR, highlight database in OE and expand it so you see all the objects)
6. Right-click on the database to drop it, select Delete backup and restore history info (do not select Close Existing Connections).  Select Drop.
7. The drop will fail (expected, there is an open connection).
8. Run the query to look at msdb, the history is gone.

Version: 1.46.0-insider (user setup)
Commit: d5a9c172d10dc49ef18b02455835cdba0b938a02
Date: 2023-08-22T18:08:21.002Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by corivera** [comment]
@erinstellato-ms Looks like SSMS has the same behavior. Do we still want to stick with that behavior, or treat it as an old bug and fix it? It's a simple change to make, just want to check.

**Comment by Charles-Gagnon** [comment]
If we do change it - would we want to wrap both actions in a transaction to ensure they either both happen or neither?

**Comment by erinstellato-ms** [comment]
@corivera So if it's the same behavior, then it could be in SMO, correct?  I would prefer we not stick with that behavior.  I would like us to fix it.  I don't know if it needs to be one transaction, as @Charles-Gagnon suggested, or if there should be logic that verifies the database is deleted before deleting the backup history.

**Comment by corivera** [comment]
No, it's an SSMS code thing. It calls SMO's delete backups method before doing the drop, so I copied that logic. I have a PR open to fix it already. Charles mentioned wrapping the whole generated script in a transaction too. Does that sound like a good idea to you?

**Comment by erinstellato-ms** [comment]
DROP DATABASE cannot be within a transaction...so we aren't able to wrap it (just tested it via T-SQL).

**Comment by corivera** [comment]
Got it. I'll merge the changes as-is then

**Comment by erinstellato-ms** [comment]
Apologies, which change?  Are we doing a check to confirm the database is dropped before deleing backup history?

**Comment by corivera** [comment]
We do the delete history steps after doing the drop, so if drop throws an error we won't delete the history either

**Comment by corivera** [comment]
https://github.com/microsoft/sqltoolsservice/pull/2202

**Comment by corivera** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/24273
