### ISSUE TITLE
DB Scoped Secondary values aren't updated when hidden

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24197]
If you change the primary value for an option and then uncheck the "Set Secondary same as Primary" checkbox then the secondary value still has the original value

![DbScopedSecondaryUpdate](https://github.com/microsoft/azuredatastudio/assets/28519865/4a14e1fe-5c4b-45c2-bfe1-540b88ff0152)

**Comment by ssreerama** [comment]
Actually, when we uncheck the checkbox, the secondary dropdown is setting back to its original value, but table is not updating. anyway setting it to original value causing confusion and will allow the user to update the value
