### ISSUE TITLE
WebviewComponent `message` property needs to be an event

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2419]
Setting message as a property doesn't make any sense, we really need to plumb through the concept of extension-side messages that can be passed to components. `sendMessage` for webview seems like a great 1st candidate. There's prior art in the vscode.d.ts webview implementation. We should solve how to do this generically so other components can easily define and hook up to extension-side messages just like we handle events from the UI right now.

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impacting an extension under active development.
