### ISSUE TITLE
Apply button not available after updating max server memory

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#24200]
1. Connect to a server (e.g. SQL 2022 in my scenario)
2. Right-click on the server and select Properties
3. Go to the Memory tab
4. Change Max server memory by using the up/down arrows - the Apply button is available.
5. Highlight text and start typing a new value, you'll see the message that the value must be greater than 128.  Even with a valid value, the Apply button doesn't appear.

I am guessing that the check for a valid value is causing the issue.  Would it be possible to check AFTER the user either changes focus to something else, or when they select Apply?

Also note: in SSMS, if a value less than 128 is entered, it will automatically change to 128.  That may be a better option here...

https://github.com/microsoft/azuredatastudio/assets/98599126/08f9b61b-cf5b-422b-bc12-02db54b17376

Version: 1.46.0-insider (user setup)
Commit: d5a9c172d10dc49ef18b02455835cdba0b938a02
Date: 2023-08-22T18:08:21.002Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by barbaravaldez** [comment]
Oh ok so we want to update the value and show an error message right?

**Comment by erinstellato-ms** [comment]
> Oh ok so we want to update the value and show an error message right?

I think if you automatically set the value to 128 if they enter something below that, then there should not be a need for an error message.  Unless I'm missing something?

**Comment by lucyzhang929** [comment]
This happens for Curser Threshold field in Advanced tab too. 
While typing "-1" the negative sign causes an error and the Apply button is not available afterwards.
Script button seems to work as expected.

https://github.com/microsoft/azuredatastudio/assets/23462877/a3d0fda2-3b0b-4d27-9c94-b2ce5deb89c3
