### ISSUE TITLE
GitHub Copilot extension doesn't work with HTTPS proxy using self-signed cert

### ISSUE THREAD

**Issue by ITS-JacobL** [microsoft/azuredatastudio#24211]
Type: <b>Bug</b>

Be in an environment where outbound HTTPS connections are PitM'ed by a layer-7 proxy that uses a self-signed cert to terminate the connection. In our case this proxy cert is one that's issued by an internal CA and is trusted by the Windows OS trust stores, but isn't present by default in an OpenSSL CA bundle trust store or similar.

Install the GitHub Copilot extension in ADS, authorise the extension to login using your Github credentials.

Attempt to activate the extension in ADS, observe that this fails and the following error message appears in the GitHub Copilot OUTPUT log:

[ERROR] [default] [2023-08-24T04:22:11.950Z] GitHub Copilot could not connect to server. Extension activation failed: "unable to get local issuer certificate"

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10500 CPU @ 3.10GHz (12 x 3096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.72GB (21.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.82.15

</details>

**Comment by cheenamalhotra** [comment]
@ITS-JacobL 

Can you please try the same using the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and confirm?

Thanks!

**Comment by cheenamalhotra** [comment]
This issue is resolved with latest 1.47 release, since we haven't heard back on this.. I will close this as resolved.
