### ISSUE TITLE
Azure SQL Migration showing up for Azure databases

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#24223]
- Azure Data Studio Version: Insiders
- OS Version: Windows 11

Noticed this:
Happens when you open dashboard on Azure SQL DB the first time on a fresh ADS launch.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/1f087d46-f68c-4503-9113-5e60d39b8015)

**Comment by abhims14** [comment]
Ideally, source should be a SQL server instance (on-prem). Azure SQL migration extension support SQL Server (source) to Azure SQL Targets (VM/MI/DB).
Refer: https://learn.microsoft.com/azure/dms/migration-using-azure-data-studio?tabs=azure-sql-mi#recommendations-for-using-a-self-hosted-integration-runtime-for-database-migrations
