### ISSUE TITLE
A11y_On doing resize, the contents present in "Provide a name for the conversion" blade is truncated.

### ISSUE THREAD

**Issue by ShaileshChudawkar** [microsoft/azuredatastudio#24220]
### Github tags
#A11yMAS; #A11yTCS; #A11ySev1; #DesktopApp; #Benchmark; #BM-AzureDataStudio-Win32-Feb2022; #Azure Data Studio; #DSCT1.0.0; #WCAG1.4.4; #ScreenReader; #Win10; #Win32; 
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**
### Environment Details:
Application Name: Database Schema Conversion Toolkit Azure data studio
Version: 1.43.0 (System user)
Windows Version: Windows 10
OS Build: 19045.2846
### Pre-requisite:-
Change the display resolution to 1280*768
Apply text resize slider to 200%
### Repro Steps:

1. Login to vm with appropriate credentials
2. Launch Azure data studio.
3. Tab to 'Manage Connection' and press enter
4. Tab to the dash board for Oracle extension
5. Perform 'Convert Objects'
6. "Provide a name for the conversion" blade should open
7. Change the resolution to 1280*768.
8. Apply text scaling to 200%.
9. Check whether the contents present in "Provide a name for the conversion" blade is truncated or not.

### Actual Result: 
On doing resize, the contents present in "Provide a name for the conversion" blade is truncated.
**Similar issues is observed in other screens:-**

1. Object Selection
2. Database Project Selection
3. Conversion Settings

### Expected Result:
On doing resize, the contents present in "Provide a name for the conversion" blade should not get truncated.
### User Impact:
Users who use to zoom the contents to view it will not get proper information about the contents present if it is truncated.
### Attachment:
![2397243_Normal 100% view](https://github.com/microsoft/azuredatastudio/assets/143179527/bec895de-0f65-404d-8415-ac467a954c6f)

https://github.com/microsoft/azuredatastudio/assets/143179527/83d8cd7b-6f40-49be-a117-bd27f767949b

**Comment by ShaileshChudawkar** [comment]
Primary bug: https://msdata.visualstudio.com/Migration%20Assistant/_workitems/edit/2397243

**Comment by cpichuka** [comment]
@ShaileshChudawkar , did you retest this issue? it's been pending from last month. If this is not an issue, you can close that.

**Comment by ShaileshChudawkar** [comment]
#closed; #Regressed:11-01-23;
Verified the issue at 
Version: 1.46.1 (user setup)
Commit: ba29842b81dec01177415e53948ca2168e69c3f8
Date: 2023-10-02T18:14:22.887Z
VS Code: 1.79.2
Electron: 22.3.25
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621
issue is not repro. So, Closing the bug. please find attachment for reference

https://github.com/microsoft/azuredatastudio/assets/143179527/3b34abd6-775e-45cf-acfa-023074383a50
