### ISSUE TITLE
F11 throws [InvokeFunction] unknown service 'debugService' error rather than toggling full screen mode

### ISSUE THREAD

**Issue by philipnye** [microsoft/azuredatastudio#24233]
Type: <b>Bug</b>

Press F11.

Expected result: Full screen mode is toggled
Actual result: `[InvokeFunction] unknown service 'debugService'` pop-up appears

Note: Using View>Appearance>Full Screen still works fine

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8365U CPU @ 1.60GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (1.08GB free)|
|Process Argv|--folder-uri file:///c%3A/Users/nyep/Institute%20for%20Government/Data%20-%20General/UK%20government%20and%20politics/Ministers/Ministers%20database|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.5

</details>

**Comment by philipnye** [comment]
This is a new issue since upgrade to either v1.44 or 1.45 - and to me looks similar to #23236

**Comment by edvvdev** [comment]
> This is a new issue since upgrade to either v1.44 or 1.45 - and to me looks similar to #23236

The problem continues

**Comment by philipnye** [comment]
@edvvdev I think there hasn't been a release yet in which the fix would be present
