### ISSUE TITLE
"Deploy a server" menu item on the "Welcome" page doesn't respond when user clicks on it

### ISSUE THREAD

**Issue by Yevhen-Myroshnychenko** [microsoft/azuredatastudio#24239]
Type: <b>Bug</b>

"Deploy a server" menu item on the "Welcome" page doesn't respond when user clicks on it

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:56.773Z)
OS version: Darwin arm64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|64.00GB (49.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kisantia** [comment]
I'm not able to repro this on the 1.45.1 release. If you open the developer tools, are there any errors in the console?

Does the new deployment wizard open if you try to launch it when clicking `New Deployment...` the `...` menu in the connections view?
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/aef553f0-f596-461d-a028-91131f91d76c)

**Comment by kisantia** [comment]
Closing since I was not able to repro this. Please reopen if more details can be provided
