### ISSUE TITLE
Publish Project failing to load advanced settings or  SQLCMD Variables

### ISSUE THREAD

**Issue by teado25** [microsoft/azuredatastudio#24240]
Type: <b>Bug</b>

When attempting to publish database changes, opening an xml script with the settings saved fails to populate any of the expected SQLCMD Variables or alter the advanced settings, the advanced settings are not as the xml script dictates.

I have verified the settings exist in the xml file.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (6.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.20.0
sql-database-projects|Mic|1.2.0

</details>

**Comment by SakshiS-harma** [comment]
@teado25 Thanks for opening this bug. 
Have you seen this happen before or is it the first time you are seeing it in the latest release? Any errors in the console?
Also, what version of SQL are you on?

**Comment by SakshiS-harma** [comment]
Thanks @teado25 for your response.
Unfortunately, I haven't been able to repro the issue.
These are the things I tried:
- Added sqlcmd variable. It shows up in the script on Generate Script request.
- Added a setting from Advanced options, and it takes effect when Published.
- Added setting and sqlcmd variable in publish profile xml, and it takes effect when Published.
So, I haven't been successful to repro the issue.

Do you mind sharing your repro to make sure I can investigate this further?

**Comment by SakshiS-harma** [comment]
Hi @teado25 , do you happen to share a repro that can be used for investigation?

Thanks!

**Comment by SakshiS-harma** [comment]
@teado25 just checking in to see if you are still encountering this problem?

**Comment by SakshiS-harma** [comment]
@teado25 I haven't been able to repro the issue at my end with the latest release version of ADS. 
There is nothing that I can do here without any additional information. I will go ahead and close the issue for now, hoping that it works for you with the latest version.
Please re-open or create a new issue if you still face this problem. Thanks!
