### ISSUE TITLE
not able to use python

### ISSUE THREAD

**Issue by sumitcreates** [microsoft/azuredatastudio#24258]
Type: <b>Bug</b>

Notebook dependencies installation is in progress
Installing Notebook dependencies failed with error: ETIMEDOUT
Notebook dependencies installation is in progress
Installing Notebook dependencies failed with error: ETIMEDOUT
Notebook dependencies installation is in progress
    > "C:\Python3.10.5\python.exe" -m pip install --user "jupyter>=1.0.0"
    stdout: Requirement already satisfied: jupyter>=1.0.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (1.0.0)
    stdout: 
    stdout: Requirement already satisfied: notebook in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (7.0.3)
    stdout: 
    stdout: Requirement already satisfied: qtconsole in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (5.4.3)
    stdout: Requirement already satisfied: jupyter-console in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (6.6.3)
    stdout: Requirement already satisfied: nbconvert in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (7.8.0)
    stdout: 
    stdout: Requirement already satisfied: ipykernel in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (6.25.1)
    stdout: 
    stdout: Requirement already satisfied: ipywidgets in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter>=1.0.0) (8.1.0)
    stdout: 
    stdout: Requirement already satisfied: comm>=0.1.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (0.1.4)
    stdout: 
    stdout: Requirement already satisfied: debugpy>=1.6.5 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (1.6.7.post1)
    stdout: 
    stdout: Requirement already satisfied: ipython>=7.23.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (8.14.0)
    stdout: 
    stdout: Requirement already satisfied: jupyter-client>=6.1.12 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (8.3.1)
    stdout: 
    stdout: Requirement already satisfied: jupyter-core!=5.0.*,>=4.12 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (5.3.1)
    stdout: 
    stdout: Requirement already satisfied: matplotlib-inline>=0.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (0.1.6)
    stdout: 
    stdout: Requirement already satisfied: nest-asyncio in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (1.5.7)
    stdout: 
    stdout: Requirement already satisfied: packaging in c:\python3.10.5\lib\site-packages (from ipykernel->jupyter>=1.0.0) (23.0)
    stdout: 
    stdout: Requirement already satisfied: psutil in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (5.9.5)
    stdout: 
    stdout: Requirement already satisfied: pyzmq>=20 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (25.1.1)
    stdout: 
    stdout: Requirement already satisfied: tornado>=6.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (6.3.3)
    stdout: 
    stdout: Requirement already satisfied: traitlets>=5.4.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipykernel->jupyter>=1.0.0) (5.9.0)
    stdout: 
    stdout: Requirement already satisfied: widgetsnbextension~=4.0.7 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipywidgets->jupyter>=1.0.0) (4.0.8)
    stdout: 
    stdout: Requirement already satisfied: jupyterlab-widgets~=3.0.7 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipywidgets->jupyter>=1.0.0) (3.0.8)
    stdout: 
    stdout: Requirement already satisfied: prompt-toolkit>=3.0.30 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-console->jupyter>=1.0.0) (3.0.39)
    stdout: 
    stdout: Requirement already satisfied: pygments in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-console->jupyter>=1.0.0) (2.16.1)
    stdout: 
    stdout: Requirement already satisfied: beautifulsoup4 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (4.12.2)
    stdout: 
    stdout: Requirement already satisfied: bleach!=5.0.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (6.0.0)
    stdout: 
    stdout: Requirement already satisfied: defusedxml in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (0.7.1)
    stdout: 
    stdout: Requirement already satisfied: jinja2>=3.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (3.1.2)
    stdout: 
    stdout: Requirement already satisfied: jupyterlab-pygments in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (0.2.2)
    stdout: 
    stdout: Requirement already satisfied: markupsafe>=2.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (2.1.3)
    stdout: 
    stdout: Requirement already satisfied: mistune<4,>=2.0.3 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (3.0.1)
    stdout: 
    stdout: Requirement already satisfied: nbclient>=0.5.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (0.8.0)
    stdout: 
    stdout: Requirement already satisfied: nbformat>=5.7 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (5.9.2)
    stdout: 
    stdout: Requirement already satisfied: pandocfilters>=1.4.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (1.5.0)
    stdout: 
    stdout: Requirement already satisfied: tinycss2 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbconvert->jupyter>=1.0.0) (1.2.1)
    stdout: 
    stdout: Requirement already satisfied: jupyter-server<3,>=2.4.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from notebook->jupyter>=1.0.0) (2.7.3)
    stdout: 
    stdout: Requirement already satisfied: jupyterlab-server<3,>=2.22.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from notebook->jupyter>=1.0.0) (2.24.0)
    stdout: 
    stdout: Requirement already satisfied: jupyterlab<5,>=4.0.2 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from notebook->jupyter>=1.0.0) (4.0.5)
    stdout: 
    stdout: Requirement already satisfied: notebook-shim<0.3,>=0.2 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from notebook->jupyter>=1.0.0) (0.2.3)
    stdout: 
    stdout: Requirement already satisfied: ipython-genutils in c:\users\vasud\appdata\roaming\python\python310\site-packages (from qtconsole->jupyter>=1.0.0) (0.2.0)
    stdout: 
    stdout: Requirement already satisfied: qtpy>=2.0.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from qtconsole->jupyter>=1.0.0) (2.4.0)
    stdout: 
    stdout: Requirement already satisfied: six>=1.9.0 in c:\python3.10.5\lib\site-packages (from bleach!=5.0.0->nbconvert->jupyter>=1.0.0) (1.16.0)
    stdout: 
    stdout: Requirement already satisfied: webencodings in c:\users\vasud\appdata\roaming\python\python310\site-packages (from bleach!=5.0.0->nbconvert->jupyter>=1.0.0) (0.5.1)
    stdout: 
    stdout: Requirement already satisfied: backcall in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.2.0)
    stdout: 
    stdout: Requirement already satisfied: decorator in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (5.1.1)
    stdout: 
    stdout: Requirement already satisfied: jedi>=0.16 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.19.0)
    stdout: 
    stdout: Requirement already satisfied: pickleshare in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.7.5)
    stdout: 
    stdout: Requirement already satisfied: stack-data in c:\users\vasud\appdata\roaming\python\python310\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.6.2)
    stdout: 
    stdout: Requirement already satisfied: colorama in c:\python3.10.5\lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.4.6)
    stdout: 
    stdout: Requirement already satisfied: python-dateutil>=2.8.2 in c:\python3.10.5\lib\site-packages (from jupyter-client>=6.1.12->ipykernel->jupyter>=1.0.0) (2.8.2)
    stdout: 
    stdout: Requirement already satisfied: platformdirs>=2.5 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter>=1.0.0) (3.10.0)
    stdout: 
    stdout: Requirement already satisfied: pywin32>=300 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-core!=5.0.*,>=4.12->ipykernel->jupyter>=1.0.0) (306)
    stdout: 
    stdout: Requirement already satisfied: anyio>=3.1.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (4.0.0)
    stdout: Requirement already satisfied: argon2-cffi in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (23.1.0)
    stdout: 
    stdout: Requirement already satisfied: jupyter-events>=0.6.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.7.0)
    stdout: 
    stdout: Requirement already satisfied: jupyter-server-terminals in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.4.4)
    stdout: 
    stdout: Requirement already satisfied: overrides in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (7.4.0)
    stdout: 
    stdout: Requirement already satisfied: prometheus-client in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.17.1)
    stdout: 
    stdout: Requirement already satisfied: pywinpty in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (2.0.11)
    stdout: 
    stdout: Requirement already satisfied: send2trash>=1.8.2 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (1.8.2)
    stdout: 
    stdout: Requirement already satisfied: terminado>=0.8.3 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.17.1)
    stdout: 
    stdout: Requirement already satisfied: websocket-client in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (1.6.2)
    stdout: 
    stdout: Requirement already satisfied: async-lru>=1.0.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter>=1.0.0) (2.0.4)
    stdout: 
    stdout: Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter>=1.0.0) (2.2.0)
    stdout: 
    stdout: Requirement already satisfied: tomli in c:\python3.10.5\lib\site-packages (from jupyterlab<5,>=4.0.2->notebook->jupyter>=1.0.0) (2.0.1)
    stdout: 
    stdout: Requirement already satisfied: babel>=2.10 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (2.12.1)
    stdout: 
    stdout: Requirement already satisfied: json5>=0.9.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (0.9.14)
    stdout: 
    stdout: Requirement already satisfied: jsonschema>=4.17.3 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (4.19.0)
    stdout: 
    stdout: Requirement already satisfied: requests>=2.28 in c:\python3.10.5\lib\site-packages (from jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (2.28.2)
    stdout: 
    stdout: Requirement already satisfied: fastjsonschema in c:\users\vasud\appdata\roaming\python\python310\site-packages (from nbformat>=5.7->nbconvert->jupyter>=1.0.0) (2.18.0)
    stdout: 
    stdout: Requirement already satisfied: wcwidth in c:\python3.10.5\lib\site-packages (from prompt-toolkit>=3.0.30->jupyter-console->jupyter>=1.0.0) (0.2.6)
    stdout: 
    stdout: Requirement already satisfied: soupsieve>1.2 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from beautifulsoup4->nbconvert->jupyter>=1.0.0) (2.4.1)
    stdout: 
    stdout: Requirement already satisfied: idna>=2.8 in c:\python3.10.5\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (3.4)
    stdout: 
    stdout: Requirement already satisfied: sniffio>=1.1 in c:\python3.10.5\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (1.3.0)
    stdout: 
    stdout: Requirement already satisfied: exceptiongroup>=1.0.2 in c:\python3.10.5\lib\site-packages (from anyio>=3.1.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (1.1.0)
    stdout: 
    stdout: Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from async-lru>=1.0.0->jupyterlab<5,>=4.0.2->notebook->jupyter>=1.0.0) (4.7.1)
    stdout: 
    stdout: Requirement already satisfied: parso<0.9.0,>=0.8.3 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jedi>=0.16->ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.8.3)
    stdout: 
    stdout: Requirement already satisfied: attrs>=22.2.0 in c:\python3.10.5\lib\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (22.2.0)
    stdout: 
    stdout: Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (2023.7.1)
    stdout: 
    stdout: Requirement already satisfied: referencing>=0.28.4 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (0.30.2)
    stdout: 
    stdout: Requirement already satisfied: rpds-py>=0.7.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (0.10.0)
    stdout: 
    stdout: Requirement already satisfied: python-json-logger>=2.0.4 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (2.0.7)
    stdout: 
    stdout: Requirement already satisfied: pyyaml>=5.3 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (6.0.1)
    stdout: 
    stdout: Requirement already satisfied: rfc3339-validator in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.1.4)
    stdout: 
    stdout: Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jupyter-events>=0.6.0->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (0.1.1)
    stdout: 
    stdout: Requirement already satisfied: charset-normalizer<4,>=2 in c:\python3.10.5\lib\site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (3.1.0)
    stdout: 
    stdout: Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\python3.10.5\lib\site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (1.26.14)
    stdout: 
    stdout: Requirement already satisfied: certifi>=2017.4.17 in c:\python3.10.5\lib\site-packages (from requests>=2.28->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (2022.12.7)
    stdout: 
    stdout: Requirement already satisfied: argon2-cffi-bindings in c:\users\vasud\appdata\roaming\python\python310\site-packages (from argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (21.2.0)
    stdout: 
    stdout: Requirement already satisfied: executing>=1.2.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (1.2.0)
    stdout: 
    stdout: Requirement already satisfied: asttokens>=2.1.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (2.2.1)
    stdout: 
    stdout: Requirement already satisfied: pure-eval in c:\users\vasud\appdata\roaming\python\python310\site-packages (from stack-data->ipython>=7.23.1->ipykernel->jupyter>=1.0.0) (0.2.2)
    stdout: 
    stdout: Requirement already satisfied: fqdn in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (1.5.1)
    stdout: 
    stdout: Requirement already satisfied: isoduration in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (20.11.0)
    stdout: 
    stdout: Requirement already satisfied: jsonpointer>1.13 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (2.4)
    stdout: 
    stdout: Requirement already satisfied: uri-template in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (1.3.0)
    stdout: 
    stdout: Requirement already satisfied: webcolors>=1.11 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (1.13)
    stdout: 
    stdout: Requirement already satisfied: cffi>=1.0.1 in c:\python3.10.5\lib\site-packages (from argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (1.15.1)
    stdout: 
    stdout: Requirement already satisfied: pycparser in c:\python3.10.5\lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi->jupyter-server<3,>=2.4.0->notebook->jupyter>=1.0.0) (2.21)
    stdout: 
    stdout: Requirement already satisfied: arrow>=0.15.0 in c:\users\vasud\appdata\roaming\python\python310\site-packages (from isoduration->jsonschema>=4.17.3->jupyterlab-server<3,>=2.22.1->notebook->jupyter>=1.0.0) (1.2.3)
    stdout: 
Notebook dependencies installation is complete
... Ensuring C:\Users\vasud\AppData\Roaming\jupyter\instances\920c1f99-6d1f-4f33-acdd-812ee8ab3139 exists
... Ensuring C:\Users\vasud\AppData\Roaming\jupyter\instances\920c1f99-6d1f-4f33-acdd-812ee8ab3139\config exists
... Ensuring C:\Users\vasud\AppData\Roaming\jupyter\instances\920c1f99-6d1f-4f33-acdd-812ee8ab3139\data exists
... Ensuring C:\Users\vasud\AppData\Roaming\jupyter\instances\920c1f99-6d1f-4f33-acdd-812ee8ab3139\config\custom exists
... Ensuring C:\Users\vasud\AppData\Roaming\jupyter\kernels exists
... Starting Notebook server
    > "C:\Python3.10.5\python.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --ip=127.0.0.1  --no-mathjax --notebook-dir "c:\Users\vasud" --NotebookApp.token=d65f22fa3ae51dfa12b6de6e1b843a85eae956c28ec7aac1

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 5 5500U with Radeon Graphics          (12 x 2096)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.35GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lucyzhang929** [comment]
Hi @sumitcreates, can you try running the below to pin the notebook package to v6.5.5 and see if that fixes your issue?
```
pip3 install notebook==6.5.5
```

**Comment by corivera** [comment]
Going by the error message it looks like there was some kind of network timeout during the install process which was eventually resolved before the third install attempt. Closing the issue since we don't have a way to repro.
