### ISSUE TITLE
XML Column result click formatting

### ISSUE THREAD

**Issue by MirkoVrielink** [microsoft/azuredatastudio#24284]
- Azure Data Studio Version: 1.45.1
- OS Version: Mac OS Ventura 13.5.1 (22G90)

Steps to Reproduce:

This issue https://github.com/microsoft/azuredatastudio/issues/2717 seems to be back. Exact seem behaviour.

Does this issue occur when all extensions are disabled?: Yes

**Comment by lewis-sanchez** [comment]
Hi @MirkoVrielink, this issue is fixed in the latest version of Azure Data Studio Insiders and will be available in our next planned release. Thank you!
