### ISSUE TITLE
Column Filters Stoped Working

### ISSUE THREAD

**Issue by ecassidy-etc** [microsoft/azuredatastudio#24297]
Type: <b>Bug</b>

After running a query, the result view grid column filters no longer populate and can not be used.

Azure Data Studio version: azuredatastudio-insiders 1.46.0-insider (306af5645b4546399ec7b58ad641345ef41c2c12, 2023-09-06T05:35:16.437Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz (40 x 2195)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: unavailable_off<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.89GB (20.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-postgresql|Mic|0.5.0
profiler|Mic|0.14.0
schema-compare|Mic|1.20.0
sql-assessment|Mic|0.6.4
sql-database-projects|Mic|1.2.0
azdata-sanddance|msr|4.1.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @ecassidy-etc 

Could you let us know if this is only applicable to 1.46.0-insider or also happens in stable release (1.45.1) for you?

**Comment by ecassidy-etc** [comment]
It works on;

Version: 1.45.1 (system setup)
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:42:37.945Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

still not working on;

Version: 1.46.0-insider (user setup)
Commit: db3ea9abd9b24c9c4ed08708105fa27df7320b05
Date: 2023-09-07T05:53:16.448Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.19045

Eric Cassidy | Software Engineer, Energetics Systems
1100 Vanguard Blvd | Miamisburg, OH 45342-0312 | USA | www.excelitas.com<http://www.excelitas.com/>
[cid:c79d519d-2e40-475e-a2f9-56cc79dd63f9]

________________________________

**Comment by cheenamalhotra** [comment]
Thanks, fix has been merged and will be included in future releases. 
Appreciate your quick feedback ❤️
