### ISSUE TITLE
Performance: It takes ~10-12 seconds to populate\load Detach dialog

### ISSUE THREAD

**Issue by abhikum** [microsoft/azuredatastudio#24319]
Repro Steps:
1. Right click on database and click Detach (Preview)

Actual: It took an average of ~10-12 seconds to load the dialog.

![image](https://github.com/microsoft/azuredatastudio/assets/9576880/fcdce4c7-4631-4acc-944e-79e9d67e4499)

**Comment by corivera** [comment]
What type of database is this? All the dialogs have slow performance against Azure instances for example, which is even more pronounced in SSMS.
