### ISSUE TITLE
Unable to undo server authentication selection

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#24310]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Open Properties on a SQL Server instance on a docker container
2. Go to Security tab
Not sure if it's expected that neither radio button is selected, so I'm unsure of which mode it is to start with, but if I select one, then I can't undo the selection. I have to exit the dialog to make sure it didn't get changed from the original mode.
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/db2fce3f-a7da-44a6-911f-ec9733253fb7)

**Comment by barbaravaldez** [comment]
The user can close the dialog before applying the changes. @erinstellato-ms what do you think about this behavior for reverting changes?

**Comment by erinstellato-ms** [comment]
The type of security (Windows vs mixed) is determined at install, so one of these options MUST be selected the first time the user opens the dialog.  I agree that they should be able to close the dialog without applying changes (we would have a Cancel button, correct?).  But the bigger issue, in my mind, is making sure the value selected on install (or previously selected value) is shown the first time the user goes into this dialog.

**Comment by corivera** [comment]
No longer repros. Fields show up as read-only now
