### ISSUE TITLE
"add database file" filepicker points to local filesystem

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#24318]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. database properties
2. add database file
3. click the ellipsis button (...) for the path

filepicker that opens is pointed at the client (workstation) filesystem instead of the sql server

![image](https://github.com/microsoft/azuredatastudio/assets/12227241/6d328c5a-a434-4098-bbae-f4ae3d9e5285)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by corivera** [comment]
Another remote file one, so I can pick this up.
