### ISSUE TITLE
Detach through script does not refresh the database list in object browser

### ISSUE THREAD

**Issue by abhikum** [microsoft/azuredatastudio#24315]
Steps to Reproduce:

1. Right click on database --> Detach (Preview)
2. Select option to generate detach script
3. Run the script

Expected: Detached database should be removed from list in object browser after successful completion of script.
Actual: Detached database still appears in the list.

![image](https://github.com/microsoft/azuredatastudio/assets/9576880/60212222-1020-421e-956b-664b19b7ff33)

![image](https://github.com/microsoft/azuredatastudio/assets/9576880/305e3c0c-df64-439a-8503-e7210e1b8a8e)

**Comment by corivera** [comment]
We have the same behavior with any generic query in the editor, such as drop, detach, create, etc. Outside of a dialog there's no longer an object explorer context to refresh the server with. If anything, this would be more of a query editor enhancement.

**Comment by cheenamalhotra** [comment]
I think it would be challenging for Query Editor to queue OE node refresh on execution, if user modifies the editor script or repurposes it, we might end up doing unnecessary refreshes.

I would rather handle exception in OE if database no longer exists and refresh parent node in this case.
Let me know if that is an acceptable solution: @corivera @abhikum

**Comment by corivera** [comment]
That works for me.
