### ISSUE TITLE
database default locations file picker is client filesystem

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#24313]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. open server properties, database settings
2. click folder icon for file picker on any database default location

filepicker that opens is for the local (client machine) file system, not the SQL instance

![image](https://github.com/microsoft/azuredatastudio/assets/12227241/389359c4-ea23-455d-91d9-d56f2574e938)

![image](https://github.com/microsoft/azuredatastudio/assets/12227241/a47b661c-8861-42c8-97e2-4946cdb1fbed)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by corivera** [comment]
@barbaravaldez I already had to add a remote file explorer with the Attach DB dialog, so I can take this one.
