### ISSUE TITLE
Cannot open Server Properties dialog against SQL Express 2019

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#24321]
When I try to open the server properties dialog for my SQL Express 2019 instance, it fails to open because an error is thrown on the STS side. I did some debugging, and it looks like it's a NullReferenceExeption that's coming from this line: https://github.com/microsoft/sqltoolsservice/blob/main/src/Microsoft.SqlTools.ServiceLayer/ObjectManagement/ObjectTypes/Server/ServerPrototype.cs#L2330

**Comment by barbaravaldez** [comment]
does this happen using the Admin Tools extension as well?

**Comment by corivera** [comment]
No, that properties window opens without any issues.
