### ISSUE TITLE
max file size input field has wierd enable/disable behavior

### ISSUE THREAD

**Issue by dzsquared** [microsoft/azuredatastudio#24322]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. database properties
2. add database file

gif 1: uncheck "enable autogrowth", recheck "enable autogrowth".  max file size field is now enabled even though growth is unlimited
![2023-09-06_15-45-58 (1)](https://github.com/microsoft/azuredatastudio/assets/12227241/dc7098da-5a8e-405d-b6ae-a88f6be36efe)

gif 2: change max file size to "limited to MB", set max size to an invalid value, then change max file size to unlimited.  max file size field is still enabled
![2023-09-06_15-44-31 (1)](https://github.com/microsoft/azuredatastudio/assets/12227241/f91851db-1abd-4045-9241-b6949376dfff)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@ssreerama reopening this issue until it gets merged into the release branch and verified.
