### ISSUE TITLE
Peek Definition and Intellisense Not working

### ISSUE THREAD

**Issue by bcodernet** [Microsoft/azuredatastudio#2433]
- SQL Operations Studio Version: 0.32.8
- OS Version: Windows 10 Enterprise 1803

Steps to Reproduce:

1. While connected to a SQL Server using windows authentication. I receive no intellisense assistance while writing T-SQL Code. Additionally, when I right-click the table name and choose peek definition then I get "no definition found". I toggled developer tools and the console shows login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.

Does this issue occur when all extensions are disabled?: Yes
![sqlopsissue](https://user-images.githubusercontent.com/43039241/45163735-9e221c80-b1b6-11e8-8771-f5b5648a8801.png)

**Comment by bcodernet** [comment]
Upon more troubleshooting on this issue, I discovered that it was one particular server that was having the issue. However, I have yet to determine the cause. There is no difference between this server and several others that I tried it on other than the fact that they work and this one server doesn't.

**Comment by kburtram** [comment]
I'll close as a duplicate of https://github.com/Microsoft/azuredatastudio/issues/2767 to consolidate related issues.  Please add any additional comments to that issue.  Thanks!
