### ISSUE TITLE
Issue connecting via refresh account credentials for AAD MFA

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#24369]
adding from customer -- waiting for customer github account and then will tag them:

I retried connecting to my Azure SQL database after installing the latest version of the Azure Data Studio. However, I’m stilling seeing an issue during what seems to be authentication step. Appreciate any inputs your team has on getting past this issue.

Version details for Azure Data Studio:

Version: 1.45.1 (system setup)
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:42:37.945Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Connection inputs:
![image](https://github.com/microsoft/azuredatastudio/assets/28786161/d5420257-da2e-43e6-a3c5-8617451802d5)

Screen displayed when selecting ‘Refresh account credentials’ link:
![image](https://github.com/microsoft/azuredatastudio/assets/28786161/6275cdb8-ac2f-4f57-8eaf-8c5f77b7fbec)

**Comment by cheenamalhotra** [comment]
Hi @amthomas46 

Please request customer to gather logs as per above comment.

**Comment by amthomas46** [comment]
Hi @cheenamalhotra customer was able to resolve, here's their troubleshooting/feedback:

Hey Anna,

Thanks for your response. I was able to spend some researching this issue and resolve it myself. The core issue was the redirect that was happening within Edge browser to use https protocol instead of http. Once I changed the browser settings to not perform an auto re-direct, I was able to view the Microsoft login screen and authenticate my Azure account.

 Perhaps this can be added to troubleshooting section of documentation if it is applicable.

**Comment by Charles-Gagnon** [comment]
We actually have a page already set up for this! 

https://github.com/microsoft/azuredatastudio/wiki/Troubleshoot-Azure-Authentication-Issues#ssl-error-on-localhost-page-err_ssl_protocol_error

@cheenamalhotra It would probably be good to make this more discoverable - possibly start by at least linking it in the label action where we ask for logs.

**Comment by cheenamalhotra** [comment]
It's also documented in MS Docs fyi.. https://learn.microsoft.com/en-us/sql/azure-data-studio/azure-connectivity?view=sql-server-ver16#common-authentication-issues for the purpose of indexing in search results. But I will link it in GitHub Actions as well.

**Comment by cheenamalhotra** [comment]
Closing as GitHub actions is now updated.
