### ISSUE TITLE
Build failures with database scoped credential in project

### ISSUE THREAD

**Issue by ClemJax** [microsoft/azuredatastudio#24379]
Type: <b>Bug</b>

Database project fails to build with syntax error when including a database scoped credential object.

ADS version: 1.45.1
.NET version: 7.0.4

Steps to repro
1. Create new database project
2. Add a script for a new master key:
     CREATE MASTER KEY ENCRYPTION
	     BY PASSWORD = '<SuperSecurePassword>'
3. Add a script for a database scoped credential:
     CREATE DATABASE SCOPED CREDENTIAL [testCredential] WITH IDENTITY = [testcred],
	SECRET = '<AnotherSuperSecretPassword>'
4. Build the project. Build fails with error "Build error SQL46010: Incorrect syntax near [testcred]"

Note - when creating the item on step 3, the window behavior is the same as described in https://github.com/microsoft/azuredatastudio/issues/4298

Extension version: 1.2.0
Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.64GB (13.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@ClemJax what is the target platform of the sql project?

**Comment by ClemJax** [comment]
SQL 2019

**Comment by Benjin** [comment]
This is occurring for the same reason as #4298.  This appears to be working on the version of ScriptDom that's in SSDT right now, if you can use that as a workaround.

We'll look into getting this syntax updated. (attn: @llali, @barbaravaldez)

**Comment by Benjin** [comment]
@ClemJax, can you confirm that you syntax is valid, and executes against your SQL instance?  I have tested it against SQL 2022 and Azure SQL, and [I think you have a syntax error](https://learn.microsoft.com/en-us/sql/t-sql/statements/create-database-scoped-credential-transact-sql?view=sql-server-ver16):

> CREATE DATABASE SCOPED CREDENTIAL [testCredential] WITH IDENTITY = [testcred], SECRET = ''

should be

> CREATE DATABASE SCOPED CREDENTIAL [testCredential] WITH IDENTITY = 'testcred', SECRET = ''

Single quotes for the identity name - not square brackets - is the documented syntax.
