### ISSUE TITLE
AriaLabel and Name property are not working for RadioButtonComponent

### ISSUE THREAD

**Issue by stuti149** [microsoft/azuredatastudio#24381]
- Azure Data Studio Version: 1.45.0
- OS Version:

Steps to Reproduce:

1. On focusing a radio button, screen reader (NVDA/ narrator) is not able to read title of radio button group.

Bug Reference: [Bug 2572155](https://msdata.visualstudio.com/Migration%20Assistant/_workitems/edit/2572155): A11y_Database Migration Assessment for Oracle_Run New Assessment_Run a new assessment of your oracle database_ScreenReader: Narrator is not announcing label name and "required field" status when radio button is getting focused.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@stuti149 can you share a screenshot of the radio button group not getting announced? I see the radio buttons names getting announced by NVDA and the aria labels set for another extension with radio buttons:
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/de6f92f8-5771-4645-b2e9-d1ff5f47fbbb)
![radioButton](https://github.com/microsoft/azuredatastudio/assets/31145923/450c898f-4349-430e-8178-4fd838917200)

example code: https://github.com/microsoft/azuredatastudio/blob/41e6f3b84b9c5fb2a063d56df367e160f006d533/extensions/data-workspace/src/dialogs/openExistingDialog.ts#L101-L126

**Comment by stuti149** [comment]
@kisantia ,

![Screenshot (530)](https://github.com/microsoft/azuredatastudio/assets/87131830/8f0ca72c-982c-46e1-b8d3-a0e1e5f17878)



Here the ask from accessibility team is to read radio button group title when radio button is focus.
For example: In above picture **when radio button is focused, "Assessment Type" must also be read.**

Here is the piece of code:
```
const assessmentTypeContainer = view.modelBuilder.flexContainer().withLayout({
            flexFlow: 'column',
        }).withProps({
            width: '447px'
        }).component();

        const assessmentType = view.modelBuilder.text().withProps({
            value: localize(constants.ASSESSMENT_TYPE.key, constants.ASSESSMENT_TYPE.value),
            ariaLabel: localize(constants.ASSESSMENT_TYPE.key, constants.ASSESSMENT_TYPE.value),
            description: localize(constants.ASSESSMENT_TYPE_DESCRIPTION.key, constants.ASSESSMENT_TYPE_DESCRIPTION.value),
            width: '447px',
            requiredIndicator: true,
            CSSStyles: {
                ...styles.LABEL_CSS,
            }
        }).component();

        const workloadAssessmentRadioButton = view.modelBuilder.radioButton().withProps({
            name: localize(constants.ASSESSMENT_TYPE.key, constants.ASSESSMENT_TYPE.value),
            label: localize(constants.WORKLOAD_ASSESSMENT.key, constants.WORKLOAD_ASSESSMENT.value),
            checked: true,
            CSSStyles: {
                ...styles.BODY_CSS,
                'margin-top': '-1em',
            }
        }).component();

        const codeAssessmentRadioButton = view.modelBuilder.radioButton().withProps({
            name: localize(constants.ASSESSMENT_TYPE.key, constants.ASSESSMENT_TYPE.value),
            label: localize(constants.CODE_ASSESSMENT.key, constants.CODE_ASSESSMENT.value),
            checked: false,
            CSSStyles: {
                ...styles.BODY_CSS,
                'margin-bottom': '16px',
            }
        }).component();
assessmentTypeContainer.addItems([assessmentType, workloadAssessmentRadioButton, codeAssessmentRadioButton]);
```


I see in your own example also, **Location** is not being announced when ratio button is focused. 

I have tried changing "arialabel" and "name" property to add "Assessment type", but screen reader is only reading what is given inside property "label"

**Comment by kisantia** [comment]
@stuti149 "Location grouping" gets announced right before the radio button when it gets navigated to. You need to set the ariaLabel for the flexContainer containing the radio buttons for this to happen. Similar issue: https://github.com/microsoft/azuredatastudio/issues/19884
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/7abec784-4136-49db-b7b4-ad639f10230b)

**Comment by kisantia** [comment]
@stuti149 do you still need help with this issue or can it be closed?

**Comment by stuti149** [comment]
@kisantia 
Thanks for the help. I have done the changes in suggested way and shared bits to test with accessibility team.
We can close it.
