### ISSUE TITLE
Increase dialog width for server and database properties

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#24403]
Increase the dialog width so that the multiple tabs fit in the dialog. 

<img width="320" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/34872381/fc2e3742-be6e-4c95-9c6e-710a7317a994">

**Comment by corivera** [comment]
Fixed by using vertical tabs: https://github.com/microsoft/azuredatastudio/pull/24521
