### ISSUE TITLE
Cannot connect to Azure account

### ISSUE THREAD

**Issue by aparnajll** [microsoft/azuredatastudio#24419]
Type: <b>Bug</b>

Not able to login to azure account getting ERROR CODE : AADSTS700082

Azure Data Studio version: azuredatastudio 1.45.1 (Universal) (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:36.656Z)
OS version: Darwin x64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by cheenamalhotra** [comment]
Hi @aparnajll 
In upcoming releases, we will prompt you for re-authentication when this error occurs. In the meantime, please try refreshing your account by removing and adding it again.

Closing as resolved.
