### ISSUE TITLE
ModuleNotFoundError: No module named 'jupyter_server.contents' switching to Python kernel

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#24436]
Started seeing this after the installing the 6.5.5 version of the notebook package for the python kernel. Unclear exactly what's causing it currently though.

While this issue was caused by switching to 6.5.5 (through the RC1 build) it also affects stable so seems to be something related to the packages themselves.

```
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Traceback (most recent call last):
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\notebook\traittypes.py", line 235, in _resolve_classes
    klass = self._resolve_string(klass)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\traitlets.py", line 2009, in _resolve_string
    return import_item(string)
  File "C:\Users\chgagnon\AppData\Roaming\Python\Python38\site-packages\traitlets\utils\importstring.py", line 30, in import_item
    module = __import__(package, fromlist=[obj])
ModuleNotFoundError: No module named 'jupyter_server.contents'
```

Additional info:

1. Here's the PR that introduced the line that's failing : https://github.com/jupyter/notebook/pull/5957
2. Changing line 1411 in `$(Python)\Python38\site-packages\notebook\notebookapp.py` from

`'jupyter_server.contents.services.managers.ContentsManager'`

to

`'jupyter_server.services.contents.manager.ContentsManager'`

seems to fix the issue.

**Comment by Charles-Gagnon** [comment]
Filed https://github.com/jupyter/notebook/issues/7048

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/azuredatastudio/issues/24443 will be used to track this

**Comment by anuragdogra2192** [comment]
The same issue with notebook 6.5.4

**Comment by Miguel-TX** [comment]
The Workaround:
 &nbsp; &nbsp; Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).

Command Line:
```
pip uninstall traitlets
pip install traitlets==5.9.0
```
After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

**Comment by jeapenach** [comment]
thanks @Miguel-TX, that worked for me

**Comment by sauravmishra1710** [comment]
+1, @Miguel-TX that worked for me as well...

**Comment by KWagnerCS** [comment]
Thanks @Miguel-TX, it worked 👍

**Comment by Charles-Gagnon** [comment]
For anyone else hitting this - we just released a new version of ADS which checks to make sure that traitlets package is 5.9.0. So if you update to the latest version then that should handle it for you.

**Comment by maxi-musz** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

Thanks man it worked

**Comment by REBECCANI** [comment]
Thank you @Miguel-TX. It worked

**Comment by Ctrl-Jay** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

Thanks @Miguel-TX this was very helpful

**Comment by Kushagra128** [comment]
thanks that works 🙏

**Comment by Apurva710555** [comment]
> pip install traitlets==5.9.0

worked for me as well

**Comment by lollipop190** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.↳

lifesaver, genius!

**Comment by Wieso97** [comment]
You are my hero. Love from china

**Comment by benzi604** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

Thanks a lot!

**Comment by Addic021101** [comment]
> pip install traitlets==5.9.0

broo you are good it worked for me tooo

**Comment by TienMinh99** [comment]
Thank u!

**Comment by JuanPalomeque** [comment]
Thanks @Miguel-TX, It worked!

**Comment by Aashir-tech** [comment]
Thanks man , It worked

**Comment by Abhishek-Ramamurthy** [comment]
Thanks @Miguel-TX. It worked for me too!

**Comment by sebgobb** [comment]
Thanks @Miguel-TX ! It worked too ! :)

**Comment by bandari-thiru** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

It works, awsome!!!

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/77549554/13086128

**Comment by Amik-TJ** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

It worked. Thanks a lot

**Comment by SeeenyaOhar** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

Works perfectly!

**Comment by MartinUQ** [comment]
> pip install traitlets==5.9.0

For me 5.8.0 did the job on macos

**Comment by Bhavil-Ahuja** [comment]
Thanks @Charles-Gagnon for the solution!

**Comment by henry3556108** [comment]
thx @Miguel-TX it work for me too

**Comment by WK-Shim** [comment]
> > The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> > Command Line:
> > ```
> > pip uninstall traitlets
> > pip install traitlets==5.9.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.
> 
> Thanks man it worked

Thanks!! it worked very well

**Comment by White-Lucifer-002** [comment]
Thanks!! I had the same issue. It worked for me.

**Comment by Morten202** [comment]
Please anyone can help bc i have been battling with this for the past 3 days. It didn't open the camera at the module
(base) C:\Users\matek\avatarify-python>run_windows.bat
Traceback (most recent call last):
  File "afy/cam_fomm.py", line 6, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

(avatarify) C:\Users\matek\avatarify-python>

**Comment by pm80** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

notebook==6.5.5
traitlets==5.9.0
Django
django-extensions
jupyter

**Comment by pm80** [comment]
notebook==6.5.5
traitlets==5.9.0
Django
django-extensions
jupyter

**Comment by arturomoncadatorres** [comment]
> pip uninstall traitlets
> pip install traitlets==5.9.0

For the sake of completeness, this can also be done with `conda`:

    conda install traitlets=5.9.0

(Note the use of a single `=` instead of `==`)

Don't worry, this won't install two versions of `traitlets`. `conda` will perform the downgrade automatically.

**Comment by YizhouZ0v0** [comment]
> The Workaround:     Uninstall the Recent Problematic Release (`v5.10.0`) and Install the Prior Version (`v5.9.0`).
> 
> Command Line:
> 
> ```
> pip uninstall traitlets
> pip install traitlets==5.9.0
> ```
> 
> After I did this, I was finally able to open up my Jupyter Notebook (via Anaconda3) without the OP's error.

It worked for me. Thanks!!

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/77549554/13086128

**Comment by hlnull** [comment]
> https://stackoverflow.com/a/77549554/13086128

Tried `pip install traitlets==5.9.0` and met the following error:
```
ipython 8.27.0 requires traitlets>=5.13.0, but you have traitlets 5.9.0 which is incompatible.
```

Upgrade the notebook helps.
```
pip install --upgrade --no-cache-dir notebook==6.*
```
