### ISSUE TITLE
can not execute queries

### ISSUE THREAD

**Issue by pkite4** [microsoft/azuredatastudio#24469]
Type: <b>Bug</b>

I can no longer execute SQL queries. I click Option+R and nothing happens ??

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:36.656Z)
OS version: Darwin x64 21.4.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by SakshiS-harma** [comment]
@pkite4 Did Option+R used to work as executing SQL queries before? I mean to ask is it a regression? Are you able to execute queries with "Run" instead?

**Comment by pkite4** [comment]
Thank you. Regression, yes. I can no longer execute queries at all. There is no Run button. It used to be there and now it is completely gone. Nothing in my environment changed that I know of. Any suggestions appreciated.

**Comment by SakshiS-harma** [comment]
Weird. Isn't the screen showing the "Run" button like in this screenshot:
![image](https://github.com/microsoft/azuredatastudio/assets/57200045/e8d37716-63cd-42f5-9661-bc8ba606d23c)

Can you try the latest version of ADS? It was released a couple of days ago- ADS 1.46
Let me know if you still see the issue with the latest version as well.

**Comment by pkite4** [comment]
@SakshiS-harma No, I have searched all of the menus that I can think of and can not find where to get that toolbar back! Here is what it looks like now: 
<img width="543" alt="screen" src="https://github.com/microsoft/azuredatastudio/assets/145463633/a91376ab-d791-4895-9987-582f90067b81">

**Comment by SakshiS-harma** [comment]
@pkite4 can you try it with the latest released version- ADS 1.46? Do you still don't see the toolbar?

**Comment by SakshiS-harma** [comment]
In the meantime, can you try opening the command palette (from within View), open Keyboard Shortcuts and find Run Current Query. And try the key combination provided there to run the query, or you can even modify it to whatever key combo you want, as I did in the screenshot below:
![Screenshot 2023-09-25 at 10 54 06 AM](https://github.com/microsoft/azuredatastudio/assets/57200045/a0196837-86d9-46cc-ad8b-2ea3e845d84a)

**Comment by pkite4** [comment]
@SakshiS-harma I just tried it again and nothing happens. On version **1.46.0**.

**Comment by SakshiS-harma** [comment]
@pkite4 how about the keyboard shortcut setting? Did that help?

**Comment by SakshiS-harma** [comment]
@pkite4 Ok, so this caught attention of one of my team mates: "OS version: Darwin x64 21.4.0", CPU: "Apple M1 (8 x 24)". Just checking if you actually mistakenly installed incorrect version of x64 build from Windows instead. Can you try to clean up your install directory and try re-installing the mac version from here (universal version): https://learn.microsoft.com/en-us/sql/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=redhat-install%2Credhat-uninstall

**Comment by pkite4** [comment]
@SakshiS-harma OK! I was hoping to not have to reinstall, but it was much easier and painless than I was imagining. I appreciate the link. It is very odd to me; I had been using the installation for almost 2 years. 
Anyway—I have reinstalled and am able to run queries again!  🎉
Thank you again. 🌼

**Comment by SakshiS-harma** [comment]
I am glad it is working for you. 
And yes, I had the same question that why suddenly it stopped working. And the reasoning behind it was that we recently synced to some new changes that might have surfaced this problem.
Delightedly it works! 👍
