### ISSUE TITLE
SQL Server Profile Search (CTRL + F) has stopped working

### ISSUE THREAD

**Issue by semics-tech** [microsoft/azuredatastudio#24467]
- Azure Data Studio Version:
Version: 1.45.1 (system setup)
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:42:37.945Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.22621

Steps to Reproduce:

1.Launch Profiler on a database
2.Press `CTRL + F` to search, nothing happens. This used to search for text

Does this issue occur when all extensions are disabled?: Unable to check as Profiler is an extension

**Comment by alfabian** [comment]
Yes, I have the same problem, I also tried with the latest insiders version, it doesn't work.

**Comment by SakshiS-harma** [comment]
I am able to repro this issue as well. Looking into it.
