### ISSUE TITLE
Copying of results to clipboard not working

### ISSUE THREAD

**Issue by jhubsharp** [microsoft/azuredatastudio#24476]
Type: <b>Bug</b>

On WIndows 11 when connected to an Azure SQL database or local Docker SQL Server instance, after running a query, I am unable to copy the results of that query to the clipboard.

In the dev tools, each time I attempt to copy, I see this error in the logs:

ERR Object reference not set to an instance of an object.: Error: Object reference not set to an instance of an object.
at c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682049
at c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682343
at Immediate. (c:\Users\MyUser\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\mssql\dist\main.js:2:682704)
at process.processImmediate (node:internal/timers:466:21)

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (4.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.20.0

</details>

**Comment by cheenamalhotra** [comment]
@jhubsharp 

Could you please provide more detailed verbose logs as requested? From the above log its not clear where the NRE is coming from.

**Comment by jhubsharp** [comment]
[logs.zip](https://github.com/microsoft/azuredatastudio/files/12705048/logs.zip)
[console.log](https://github.com/microsoft/azuredatastudio/files/12705051/console.log)

Logs attached, though I looked at the console.log after turning up all log levels and the error is the same.

**Comment by cheenamalhotra** [comment]
I see your configuration is failing to load: 

```
  settings": {
    "mssql": {
      "query": {
        "textSize": 10000000000000000, // System.OverflowException in backend service
```

Could you try removing that setting or set it to a valid integer (32-bit) value?

**Comment by cheenamalhotra** [comment]
I was able to find the NRE exception details from SqlTools log:

```
Error: 0 : query/copy : Object reference not set to an instance of an object.
   at Microsoft.SqlTools.ServiceLayer.QueryExecution.QueryExecutionService.HandleCopyResultsRequest(CopyResultsRequestParams requestParams, RequestContext`1 requestContext) in /_/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/QueryExecutionService.cs:line 785
   at Microsoft.SqlTools.Hosting.Protocol.MessageDispatcher.<>c__DisplayClass31_0`2.<<SetRequestHandler>b__0>d.MoveNext() in /_/src/Microsoft.SqlTools.Hosting/Hosting/Protocol/MessageDispatcher.cs:line 157
```

Which is likely failing here: https://github.com/microsoft/sqltoolsservice/blob/d3c28d358ffdcdda5548a42e13b84fcf87ac50bf/src/Microsoft.SqlTools.ServiceLayer/QueryExecution/QueryExecutionService.cs#L783C37-L783C44 where settings are being read.

Your update to settings should address the issue.

**Comment by jhubsharp** [comment]
Confirmed that changing thetext size fixed the issue. That seeting has been that way for several months trying to get around an issue with JSON maximums so not sure what that caused the break, but glad to have it fixed!

**Comment by cheenamalhotra** [comment]
> Confirmed that changing the text size fixed the issue. That setting has been that way for several months trying to get around an issue with JSON maximums so not sure what that caused the break, but glad to have it fixed!

For your reference, this value should be less than 2147483647 (2 GB) as supported by SQL Server.
[MS Docs: SET TEXTSIZE](https://learn.microsoft.com/en-us/sql/t-sql/statements/set-textsize-transact-sql?view=sql-server-ver16#arguments)
