### ISSUE TITLE
Failure when attempting to change password

### ISSUE THREAD

**Issue by lgonzalezsa** [microsoft/azuredatastudio#24477]
Version: 1.45.1
Commit: 88c21b1725a3e79440027bdb7b5a55fb036be0e2
Date: 2023-08-03T00:38:54.891Z
VS Code: 1.79.2
Electron: 22.3.14
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Linux x64 6.4.6-76060406-generic

Steps to Reproduce:

1. My MS SQL password expired
2. Opening Azure Data Studio and ask me to change the password, when changed got the error
 
![image](https://github.com/microsoft/azuredatastudio/assets/704686/7ff80eaf-ae04-4cf9-b383-f61f78f40818)

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
We haven't received more details from you, and with above error it's not clear why connection failed. Please re-open issue if issue persists with requested logs.
