### ISSUE TITLE
Startup Fails when DOTNET_STARTUP_HOOKS is empty

### ISSUE THREAD

**Issue by jayholliday** [microsoft/azuredatastudio#24470]
Type: <b>Bug</b>

If the environment variable DOTNET_STARTUP_HOOKS exists but is empty all sorts of issues occur.

It's been a while but if I remember right VS (not sure what version) failed to start if the environment variable didn't exist so I created it but left it empty. I've deleted it for now but hopfully it's not a Catch-22 where one needs it and the other can't have it unless it has a value.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:37.945Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by cheenamalhotra** [comment]
@jayholliday 

Can you please try with the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if this issue is resolved?
Thanks!

**Comment by jayholliday** [comment]
@cheenamalhotra 

I tried it and it still failed. However, since I had deleted that variable to make it work before I logged this issue, I had to recreate the DOTNET_STARTUP_HOOKS variable to test this update. I found that I couldn't create the var as an empty string but it would let me create it with a single space. The error I received after setting it to a space was;

> Unhandled exception. System.ArgumentException: The startup hook simple assembly name ' ' is invalid. It must be a valid assembly name and it may not contain directory separator, space or comma characters and must not end with '.dll'.
>    at System.StartupHookProvider.ProcessStartupHooks()

in both the old version and the Insiders version. I suspect that's what was in the variable before and the message is pretty clear that a space isn't allowed so to some degree it's working as designed making this a self inflicted wound even if it was created to get around a bug in VS.

**Comment by cheenamalhotra** [comment]
Ok, I think the .NET runtime teams have addressed empty values and not spaces.
PR https://github.com/dotnet/runtime/pull/84322 and [Code Reference](https://github.com/dotnet/runtime/blob/89f674318009fba8527738609925c70f27f2aae1/src/installer/tests/TestUtils/Assertions/CommandResultAssertions.cs#L119-L124)

Either way, if its not yet addressed by .NET runtime - I don't think we can do anything from here. You may report this issue to .NET runtime teams ([dotnet/runtime](https://github.com/dotnet/runtime)) and request support on this. We can't do anything from ADS side. Environment variables are loaded during launch into our backend .NET services and if low level .NET variables are defined in environment they would impact the functioning, as our backend services run within user's context in .NET runtime processes.

I will close this as external, we are using latest .NET SDK 7.0.401
