### ISSUE TITLE
Add ability to logout of GitHub account from Copilot extension

### ISSUE THREAD

**Issue by erinstellato-ms** [microsoft/azuredatastudio#24478]
Currently, there is no easy way to log out of your GitHub account from the Copilot extension within ADS (in the event that you logged in with the wrong account).  If we could add this functionality to log out from the Accounts dialog, that would be great.

Example user issue: https://learn.microsoft.com/en-us/answers/questions/1348464/how-to-sign-out-my-github-account-on-azure-data-st

**Comment by dzsquared** [comment]
Ran into this today with GitHub auth that was exited mid-process, resulting in a broken state and requiring a manual intervention in cache files.
related to #24173

**Comment by erinstellato-ms** [comment]
Thanks @lewis-sanchez!!
