### ISSUE TITLE
SQL Query Editor - Duplicate Tab Feature

### ISSUE THREAD

**Issue by grahamoriley** [microsoft/azuredatastudio#24541]
SQL Query Editor

![image](https://github.com/microsoft/azuredatastudio/assets/9946897/0a4ea259-15a7-4c70-b0dd-f5597258d4f7)

**Duplicate editor from the context menu**

It would be useful to have a Duplicate editor facility from an existing editors context menu.
This would be a quicker way to split queries against the same or different databases with the same table schema.

Regards,
Graham O'Riley

**Comment by cheenamalhotra** [comment]
We have an existing feature request for the same: https://github.com/microsoft/azuredatastudio/issues/245
Closing as duplicate.
