### ISSUE TITLE
Create Database fails Version 1.46

### ISSUE THREAD

**Issue by dbabulldog-repo** [microsoft/azuredatastudio#24559]
- Azure Data Studio Version: 1.46.0
![image](https://github.com/microsoft/azuredatastudio/assets/61699725/8363876c-59d1-46f4-89df-392ec3daa07a)
- OS Version:
OS Name	Microsoft Windows Server 2022 Datacenter
Version	10.0.20348 Build 20348

Steps to Reproduce:

1. After connecting to Azure SQL Managed instance, opening up the drop down, right mouse clicking on databases and select New Database (Preview)
![image](https://github.com/microsoft/azuredatastudio/assets/61699725/f7acee7b-d3b0-445d-8379-55638e0f8dd5)

I received the following error message:
![image](https://github.com/microsoft/azuredatastudio/assets/61699725/9052c04d-b7ce-4faa-beeb-5ca947fb22fa)

2. Note, I am able to script out the database and it creates T-SQL that then is able to successfully create the new database. 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@ssreerama please verify this is fixed in the latest RC build and close this issue when you get a chance. Thanks!

**Comment by ssreerama** [comment]
Confirming the nee RC build has the fix and can create a new Database for MI server. Thanks
