### ISSUE TITLE
Cannot browse programmability (stored procedures) under ondemand pool

### ISSUE THREAD

**Issue by YorBraakman2022** [microsoft/azuredatastudio#24557]
SSMS:
![image](https://github.com/microsoft/azuredatastudio/assets/99035463/66b33964-f86c-4cb6-816e-e7ea2f1e6f3d)
ADS:
![image](https://github.com/microsoft/azuredatastudio/assets/99035463/ff21af64-7ce8-40fd-be4e-bc4b35bd3405)

The folder programmability is not available in ADS, it is in SSMS.

Alter statements work fine, however I'm really missing the feature.

**Comment by sharpt00th** [comment]
As well as Lakehouse databases, this is also the case for Azure SQL databases that sit in an "ondemand" serverless SQL environment, in ADS these will show Tables, Views, External Resources and Security, but not Programmability.

![image](https://github.com/user-attachments/assets/bdaadcf8-9572-4645-81d9-a83745df0366)

**Comment by kburtram** [comment]
Fixed in 1.50 release.
