### ISSUE TITLE
Error when trying to open database properties for databases with special characters

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#24569]
Version: 1.46.1-rc1 (user setup)
Commit: ba29842b81dec01177415e53948ca2168e69c3f8
Date: 2023-10-02T17:59:25.245Z
VS Code: 1.79.2
Electron: 22.3.25
Chromium: 108.0.5359.215
Node.js: 16.17.1
V8: 10.8.168.25-electron.0
OS: Windows_NT x64 10.0.23555

`An error occurred while opening the properties dialog for database: @#)(&. An error occurred while parsing EntityName. Line 7, position 32.`

**Comment by ssreerama** [comment]
I faced an error while creating the database with special characters "@#)(&", but when i refresh, the database is created.
