### ISSUE TITLE
Developer Getting Started Guide Python Version

### ISSUE THREAD

**Issue by ecassidy-etc** [microsoft/azuredatastudio#24582]
https://github.com/microsoft/azuredatastudio/wiki/Developer-Getting-Started-Guide

Getting Started Guide doesn't specify which version on Python to get.

Python 3.12 could not be used due to distutils being dropped.

**Comment by cheenamalhotra** [comment]
I wonder if this is a recent issue that we will investigate, but latest versions should ideally be compatible.
Have you tried using v3.11 in the meantime?

**Comment by ecassidy-etc** [comment]
Yeah I rolled back to v3.10 but I suspect v3.11 will also work. See [PEP 632 – Deprecate distutils module](https://peps.python.org/pep-0632/) for details

**Comment by cheenamalhotra** [comment]
@ecassidy-etc 

I've updated the Wiki to address the same. 
Thanks!
