### ISSUE TITLE
Can't connect!

### ISSUE THREAD

**Issue by ManOguaR** [microsoft/azuredatastudio#24599]
Type: <b>Bug</b>

On Linked accounts hit +
then opens to localhost and shows invalid security lock, and no options to continue.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-migration|Mic|1.4.10

</details>

**Comment by Charles-Gagnon** [comment]
@ManOguaR Could you try the instructions listed here to see if that fixes it for you?

https://github.com/microsoft/azuredatastudio/wiki/Troubleshoot-Azure-Authentication-Issues#change-url-to-http

**Comment by cssuh** [comment]
Closing as issue is resolved
