### ISSUE TITLE
multiple_matching_tokens occurred when acquiring token. 

### ISSUE THREAD

**Issue by bwyatt-mcr** [microsoft/azuredatastudio#24604]
Type: <b>Bug</b>

I've started to get this error. I am not using ADS in a different way to what I used to. I've got several Azure servers I connect to using my Azure account. It seems to happen more when I come back to the app having not used it in a while.

Disconnected/reconnecting does not fix it. I have to restart the app.

```
Execution failed due to an unexpected error: 
	multiple_matching_tokens occurred when acquiring token. 
The cache contains multiple tokens satisfying the requirements. Call AcquireToken again providing more requirements such as authority or account..
```

Azure Data Studio version: azuredatastudio-insiders 1.47.0-insider (186f8d3771ed7a9f2e50b5ff4aefdf7093319485, 2023-10-04T05:31:52.011Z)
OS version: Darwin x64 23.0.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by KevinInKy** [comment]
I am getting the same error and can't log into any SQL Server using Azure Data Studio version 1.49.0

I get same error telling me to clear token cache but provides no instructions how to do this vague request.

Failed to authenticate the user in Active Directory (Authentication=ActiveDirectoryInteractive).
Error code 0xmultiple_matching_tokens_detected
The cache contains multiple tokens satisfying the requirements. Try to clear token cache.

**Comment by forgeDeepakBalasubramanian** [comment]
I have the same error this morning ? Did something change ?

**Comment by KevinInKy** [comment]
My issue seemed to start after my last upgrade to version 1.49.
I found in another forum a solution.
Press F1 and search for clear Azure token and that fixed my problem
![image](https://github.com/user-attachments/assets/b7caa999-87e0-49ec-bbf4-6fee584773e9)

**Comment by forgeDeepakBalasubramanian** [comment]
Yes, that helped. Thank you @KevinInKy
