### ISSUE TITLE
Unwanted Default Query Files Loading By Default

### ISSUE THREAD

**Issue by yesnovo** [microsoft/azuredatastudio#24603]
Type: <b>Bug</b>

On ADS launch, the software loads query files that were open on the previous exit.  I believe there was an issue with my previous upgrade.  I now can't close a set of queries that were "unsaved" (I created a new query and did not explicitly save it) when the system upgraded.  This set of files (SQLQuery_29, SQLQuery_30...etc) always open by default.  I've tried to saving them, even using "Save As", but I'm unable to prevent this set of files from loading by default every time.   

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-12700H (20 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.68GB (42.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Closing as response provided above to address user concern.
