### ISSUE TITLE
Can't connect!

### ISSUE THREAD

**Issue by ManOguaR** [microsoft/azuredatastudio#24600]
Type: <b>Bug</b>

On Linked accounts hit +
then opens to localhost and shows invalid security lock, and no options to continue.
https://localhost:60101/signin?nonce=3b44f26b-c4f4-4b09-8ce5-ff273dae5fc3

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz (8 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (8.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-migration|Mic|1.4.10

</details>

**Comment by bulrush15** [comment]
I had trouble connection also about an hour ago, but the problem resolved itself. Normally one should wait an hour to see if the problem resolves before posting a bug report. 

We could use a website which shows if the Azure services are up or down at that moment. That would help to see when they come back up.

**Comment by kisantia** [comment]
duplicate of #24599
