### ISSUE TITLE
Allow extension API access to result set column metadata, not just row data.

### ISSUE THREAD

**Issue by cpwood** [microsoft/azuredatastudio#24617]
**Is your feature request related to a problem? Please describe.**
I'm writing an extension where, for a SQL query that's been executed, I need to grab a sample of the rows (e.g. 5 rows) plus information about the columns (names, data types, precision, max lengths, etc).

To get the rows, I can use the Query Provider as follows:

```js
const editor = vscode.window.activeTextEditor;
const connection = await azdata.connection.getCurrentConnection();
const queryProvider = azdata.dataprotocol.getProvider(connection.providerId, azdata.DataProviderType.QueryProvider) as azdata.QueryProvider;

const result = await queryProvider.getQueryRows({
            ownerUri: editor.document.uri.toString(), 
            rowsCount: 5
        } as azdata.QueryExecuteSubsetParams);
```
However, I have no way of finding out (that I can see!) about the columns, their names, types, etc.

**Describe the solution or feature you'd like**
A similar call to `getQueryRows()` - e.g. `getQueryColumns()` - that returns an array of `IDbColumn` objects.

**Describe alternatives you've considered**
I can work around this by re-running the query in the background, but if the query is slow-running, this gives a poor user experience.

I also tried hooking into the OnQueryComplete event (ignoring the many warnings not to do so!):

```js
    const cols = new Map<string, azdata.IDbColumn[]>();
    const providers = azdata.dataprotocol.getProvidersByType(azdata.DataProviderType.QueryProvider);

    for (let provider of providers) {
        const qp = azdata.dataprotocol.getProvider(provider.providerId, azdata.DataProviderType.QueryProvider) as azdata.QueryProvider;
        
        qp.registerOnQueryComplete(result => {
            // BREAKS THE QUERY WINDOW! :-(
            cols.set(result.ownerUri, result!.batchSummaries![0].resultSetSummaries![0].columnInfo);
        });    
    }
```

but this breaks the query window (it looks like the query never stops running).

Would this require a product change or am I just not seeing a more obvious solution to the problem?

**Comment by Charles-Gagnon** [comment]
Unfortunately I believe this is a gap in the API currently. As you found out, registering the event handlers on the query provider will break ADS so shouldn't be done. See https://github.com/microsoft/sqlops-dataprotocolclient/issues/62 for details. And I don't think there's another API we expose for this.

@alanrenmsft can you think of anything I might be missing?

**Comment by alanrenmsft** [comment]
@Charles-Gagnon you are right, we have to make it a real `Event` in order to support this.

@cheenamalhotra  FYI.

**Comment by Charles-Gagnon** [comment]
FYI, I'm going to start working on fixing the dp client to allow multiple handlers to be registered. If this is something you want to prioritize @cheenamalhotra we can chat, otherwise it should hopefully not take too long.

**Comment by Charles-Gagnon** [comment]
@cpwood The latest insiders should have this change to allow you to hook into the registerOnQueryComplete event without breaking ADS - so if you were able to try it out let us know if you still see any issues!

**Comment by cpwood** [comment]
Many thanks, @Charles-Gagnon ! Have just given it a test, and it works perfectly!
