### ISSUE TITLE
ADS disconnects and cannot connect

### ISSUE THREAD

**Issue by mindit-alexandru-puiu** [microsoft/azuredatastudio#24611]
Type: <b>Bug</b>

Continuously adjusting a query and rerunning ends up in ADS not responding commands - query starts but never returns result set and cancel does not respond anymore. Disconecction works and connection does not work.

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:56.773Z)
OS version: Darwin arm64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Pro (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|5, 4, 4|
|Memory (System)|32.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.14.0
sql-prompt|Red|0.2.12
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kisantia** [comment]
@mindit-alexandru-puiu can you try the latest release 1.46.1 and see if this still happens?

**Comment by cheenamalhotra** [comment]
Not enough information to investigate issue, closing as inactive.
