### ISSUE TITLE
Couldn't start client Flat File Import Service error while clicking on import wizard in azure data studio

### ISSUE THREAD

**Issue by harshrajchauhan** [microsoft/azuredatastudio#24612]
**Is your feature request related to a problem? Please describe.**

Couldn't start client Flat File Import Service error while clicking on import wizard in azure data studio

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by cheenamalhotra** [comment]
Hi @harshrajchauhan 

Can you please provide additional information:
- ADS Version
- Extension Version

Have you tried with the [latest ADS insiders](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) version?

**Comment by lautou** [comment]
Hi @cheenamalhotra 
I am facing the same issue:

- SQL Server Import v1.5.5
- ADS Version: 1.47.0

About info:
Commit: c7c2b2f21505562d21972d4c135119d00806db4f
Date: 2023-11-07T17:14:47.439Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Linux x64 6.5.10-200.fc38.x86_64

**Comment by cheenamalhotra** [comment]
I tested on Linux, and cannot reproduce the issue. Are you working in some sort of proxy-enabled env?

Do you see any errors in this or any other Output window: 

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/a6936e24-f2af-4c9d-b48c-3f93cd31e55a)

**Comment by lautou** [comment]
Hi @cheenamalhotra . Finally it worked fine.
Root cause was the downloading of **flatfileimportservice-linux-x64.tar.gz** file took 10 minutes.

**Comment by jamesyoung007** [comment]
I have waited for a few hours. 
The error message is still "could not start client flat file import service"
