### ISSUE TITLE
Failure to Connect

### ISSUE THREAD

**Issue by barryseymour** [microsoft/azuredatastudio#24621]
Type: <b>Bug</b>

SQL Server - trying to connect to a server and the connection takes forever, or fails. It's a known connection, good credendials, SSMS connects with no problem. I have to close and restart ADS to make it work.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19044
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i9-11950H @ 2.60GHz (16 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.20GB (46.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.1
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azuredatastudio-postgresql|Mic|0.5.0
import|Mic|1.5.5
powershell|ms-|2023.2.1
query-history|Mic|0.5.3
azdata-sanddance|msr|4.0.3
extra-sql-script-as|pac|0.5.0
sql-prompt|Red|0.2.12
sql-search|Red|0.4.2

(1 theme extensions excluded)

</details>

**Comment by cssuh** [comment]
Hi @barryseymour , do you see any errors in the Developer Tools Console?  Is this an Azure Server you are connecting to?

**Comment by barryseymour** [comment]
> Hi @barryseymour , do you see any errors in the Developer Tools Console? Is this an Azure Server you are connecting to?

I'm afraid not. It's intermittent, hard to catch it in action. A possible clue is that I sometimes connect to one connection, then use the USE statement to switch to another database on the same server. That seems to confuse Intellisense, or at least slow it down.

I'll keep my eye open.

**Comment by cheenamalhotra** [comment]
@barryseymour 

You can always enable logging as per above comment and let us know if you experience an error in SQLTools.log file.
(you can open it directly in ADS by running command > `mssql.showLogFile` (MSSQL: Show Log File) > `sqltools.log`)

**Comment by barryseymour** [comment]
Okay, thanks to you both. I'll give it a shot tomorrow.  I hope I can catch it in action!

**Comment by cheenamalhotra** [comment]
@barryseymour 

Checking in, have you been able to reproduce the error again?
Thanks!

**Comment by kisantia** [comment]
please reopen if this still repros and logs can be provided.
