### ISSUE TITLE
Auto Hide Notifications

### ISSUE THREAD

**Issue by CePur** [microsoft/azuredatastudio#24637]
It would be great if the notifications (toasts) at the bottom right would disappear automatically and an option to specify timeout for this.

**Comment by cheenamalhotra** [comment]
@CePur 

Can you provide more detail on notifications that you're concerned about?
Screenshots/use cases should help us identify areas of improvement.

**Comment by CePur** [comment]
@cheenamalhotra sure :

![resim](https://github.com/microsoft/azuredatastudio/assets/36715887/146d2436-d074-4469-8464-83f57246b302)
