### ISSUE TITLE
Option to exclude -azdata from appname suffix

### ISSUE THREAD

**Issue by rayzinnz** [microsoft/azuredatastudio#24651]
**Is your feature request related to a problem? Please describe.**
I would like to connect to a controlled database that only allows specific application names

**Describe the solution or feature you'd like**
Please add an option to exclude the "-azdata" from the suffux when using a custom Application Name in an MSSql connection

**Describe alternatives you've considered**
No alternative, this is hard-coded?

**Additional context**
Code is here, sorry I do not know the typescript language so well. Is there a way to specify the suffix?: string in the adjustForMssqlAppName function?

[src/sql/platform/connection/common/connectionProfile.ts](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/platform/connection/common/connectionProfile.ts)
Line 78:
```typescript
this.options[Constants.mssqlApplicationNameOption] = adjustForMssqlAppName(model.options[Constants.mssqlApplicationNameOption]);
```

and
[src/sql/platform/connection/common/utils.ts](https://github.com/microsoft/azuredatastudio/blob/main/src/sql/platform/connection/common/utils.ts)
```typescript
export function adjustForMssqlAppName(currentAppName: string, suffix?: string): string {
	let appName = suffix ? applicationName + '-' + suffix : applicationName;
	let finalSuffix = '-' + appName;
	return (currentAppName && currentAppName !== appName && !currentAppName.endsWith(finalSuffix))
		? currentAppName + finalSuffix
		: currentAppName ?? appName;
}
```

**Comment by cheenamalhotra** [comment]
Hi @rayzinnz 

This is by design. Azdata in appname is used for telemetry purposes.
