### ISSUE TITLE
new connection

### ISSUE THREAD

**Issue by Samarr1981** [microsoft/azuredatastudio#24683]
Type: <b>Bug</b>

on making new connection it is showing -  A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server: Could not open a connection to SQL Server)

Azure Data Studio version: azuredatastudio 1.45.1 (Universal) (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:36.656Z)
OS version: Darwin arm64 22.5.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M2 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
cms|Mic|0.9.3
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-assessment|Mic|0.6.4
sql-migration|Mic|1.4.10

</details>

**Comment by cheenamalhotra** [comment]
Hi @Samarr1981 

Have you verified your setup is done properly using this article: https://learn.microsoft.com/en-us/troubleshoot/sql/database-engine/connect/network-related-or-instance-specific-error-occurred-while-establishing-connection?

**Comment by cheenamalhotra** [comment]
Closing as not enough information available.
