### ISSUE TITLE
Clicking an XML in Results Grid...

### ISSUE THREAD

**Issue by GearTheWorld** [microsoft/azuredatastudio#24696]
Type: <b>Feature Request</b>

In a Results grid when we click a JSON it opens clearly in a Untitled-1 window which is super practical.  Now when we want to see an XML, it's not clickable but it would be great.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by GearTheWorld** [comment]
We can right click, Save as XML and open it immediately however we see escape characters which aren't too beautiful ;)

![image](https://github.com/microsoft/azuredatastudio/assets/8614008/813d2d0b-c96f-46b2-be60-c5826681ead6)

**Comment by cheenamalhotra** [comment]
XML formatting is supported for XML datatypes as far as I can see.... is your column "TRL_Request" of XML datatype?

![xmlformat](https://github.com/microsoft/azuredatastudio/assets/13396919/f0e9397c-a079-4cb8-b0a2-7c6748691510)

**Comment by GearTheWorld** [comment]
No, it's a varchar(max).  But it's the same for my JSON since there's no datatype JSON right ?

**Comment by cheenamalhotra** [comment]
That's true, we'll look into supporting this for XML content likewise.

**Comment by GearTheWorld** [comment]
Excellent
