### ISSUE TITLE
Table selection color in darker themes should be more distinct

### ISSUE THREAD

**Issue by AlexFsmn** [Microsoft/azuredatastudio#2471]
- SQL Operations Studio Version: Master - 2bc97c2 

Steps to Reproduce:

1. Run Query
2. Make a selection of the results

Light theme looks pretty good:
![image](https://user-images.githubusercontent.com/11557675/45265019-ca070180-b445-11e8-983f-2017db747283.png)

Dark theme:
![image](https://user-images.githubusercontent.com/11557675/45265020-d0957900-b445-11e8-9d98-2c53edb1ea5a.png)

**Comment by kburtram** [comment]
The data grid now uses colors from the current theme.
