### ISSUE TITLE
Auto complete suggests "ABORT" whenever a new comment is begun

### ISSUE THREAD

**Issue by irahsu** [microsoft/azuredatastudio#24716]
Type: <b>Feature Request</b>

In a new query window, type "--". Auto complete suggests "ABORT", and if the user subsequently presses the TAB key, auto complete inserts "ABORT". 100% of the time, I want to format my comment by indenting it with a tab character, not insert the word "ABORT" into my comment!

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by cheenamalhotra** [comment]
I believe hyphen(-) is a trigger to `textdocument/completion` which loads all keywords in a dropdown and resolves with first keyword. But why and where it's configured is something to be investigated.

@Charles-Gagnon @alanrenmsft any ideas to disable this trigger?

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/sqltoolsservice/blob/16c7e323567023b08200ab35b2bfb2a5042385e0/src/Microsoft.SqlTools.ServiceLayer/ServiceHost.cs#L41 is where we define the triggers.

So I could see a couple of options: 

1. Look into whether we actually need/want - as a trigger character. If not then remove it
2. Have the completion provider be smarter about what it returns when it sees a - (so it would return nothing if it's a comment for example)

**Comment by cheenamalhotra** [comment]
Thanks Charles! By the time user writes 2 consecutive hyphens, there are no suggestions, so comment can be written, it's just the first hyphen that causes the problem.  If response is slow, it may arrive little late which may seem to cause what user is experiencing.

For SQL language, hyphen(-) doesn't seem to be useful to complete anything. It's also not a trigger for intellisense in SSMS, so I would lean towards removing it to keep language experience similar.

**Comment by irahsu** [comment]
Actually, the suggestion do appear after typing 2 consecutive hyphens, but this is only if you are typing lines _above_ a valid SQL statement:
`
-- <-- suggestions appear here

select 1

-- <-- suggestions don't appear here
`

Thanks!

**Comment by cheenamalhotra** [comment]
Thanks @irahsu 
I was able to capture that later and the PR https://github.com/microsoft/sqltoolsservice/pull/2270 should fix this too!
