### ISSUE TITLE
Expanding Keys, Constraints, Constraints or Indexes in a table with Large number of Column does not work

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2474]
- SQL Operations Studio Version:
Version 0.33.2
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Create the BroadTest table using the attached [CreateBroadTest.sql.txt] file on a server.
(https://github.com/Microsoft/sqlopsstudio/files/2364846/CreateBroadTest.sql.txt)
2. After connecting to the server in ops studio, in object explorer navigate to Databases->DbName->Tables->dbo.BroadTest->Keys (or Triggers or Indexes or Constraints)(https://github.com/Microsoft/sqlopsstudio/files/2364846/CreateBroadTest.sql.txt)

There is an hovering icon on the node for about 45 seconds to a minute and after that no information gets displayed. Sometimes one gets a timeout message after 45 seconds.

**Comment by ranasaria** [comment]
I mean there is a circling icon on the node for about 45 seconds to a minute and after that no information gets displayed.

**Comment by ranasaria** [comment]
The exact timeout message when the timeout message is received is:
`Object Explorer task didn't complete within 45 seconds.`

**Comment by abist** [comment]
@ranasaria I'm not able to repro this issue. There's a spinning wheel until all the nodes are shown and it takes a short while, but it doesn't error out. Do you have a specific server where I can repro this issue?

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if you're still impacted by this bug.  Thanks!
