### ISSUE TITLE
Refresh fails to refresh

### ISSUE THREAD

**Issue by deej79** [microsoft/azuredatastudio#24758]
Type: <b>Bug</b>

Opened a saved query.
Called designer.
Added a column.
Published change.
Closed designer.
Added new column to saved query.
New column flagged as not found.
Refreshed (several times).
Error still there.
Closed query.
Reopened query.
Problem gone.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.3.1
schema-visualization|R0t|0.9.1
db-snapshot-creator|sea|0.1.0
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
@deej79 

Can you elaborate how did you refresh?
Did you try running "Refresh Intellisense Cache" command?

**Comment by deej79** [comment]
Right-click on table | Refresh
Right-click on database | Refresh
Right-click on connection | Refresh

I don't know anything about the "Refresh Intellisense Cache" command. Where is it or how is it invoked?

**Comment by deej79** [comment]
Additional information:
I added more columns using Design option.
I added the new columns to a DISCONNECTed query. They were all recognized.
I connected and ran successfully.

In the first pass (as reported earlier) the query tab was CONNECTed to the database.

**Comment by cheenamalhotra** [comment]
You can run "Refresh Intellisense Cache" command using below steps:
- Ctrl + Shift + P or Go To "Manage" (Gear) Icon > Run Command Palette...
- Start typing "Refresh Intellisense Cache" and select command to run.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/b6f265e6-2ee1-4b3b-a64e-f2667489c4e0)

This will trigger refresh in intellisense to load new database objects added to your database.
Refreshing connection or objects doesn't trigger this command.

**Comment by cheenamalhotra** [comment]
Closing as solution has been provided.
