### ISSUE TITLE
SEQUENCES

### ISSUE THREAD

**Issue by JohnDizzle** [microsoft/azuredatastudio#2475]
I just install SQL Server 2017 on Linux - Ubuntu.   I download the SQL operations suite and I restored my databases from a .bak file.   I can't find my sequences that are defined in my table definition.   I tried to peek to definition and there is no definition, although i tried to do a [ select (next value for dbo.seq_lineitems) ] and a new value appears.  I queried the sys.objects and its there with an object_id and I queried select OBJECT_SCHEMA_NAME(OBJECT_ID(N'dbo.seq_lineitems', 'SO'))  and it has a schema, but no definition.

thanks, 

john doyle

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if you're still impacted by this issue.  Thanks!
