### ISSUE TITLE
Query database

### ISSUE THREAD

**Issue by akasfikis** [microsoft/azuredatastudio#24752]
Type: <b>Bug</b>

Iam unable to view table data when connected to an Oracle database

Error:

Execution failed due to an unexpected error: 
	No Handler Registered
Total execution time: 00:00:00

Extension version: 0.1.3
Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.44GB (5.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by cheenamalhotra** [comment]
This is not currently supported, see #6724 for reference.
Closing as duplicate.
