### ISSUE TITLE
Can not open any files

### ISSUE THREAD

**Issue by hjpinndx** [microsoft/azuredatastudio#24762]
Type: <b>Bug</b>

Good day

Clicking on a file in the Explorer does not open it in the editor window. Going to File -> Open File does also not open the file. AKA trying to open any script or file results in nothing happening.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.24GB (10.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.3.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @hjpinndx 

Do you see any errors in logs? Does restarting ADS work?

**Comment by hjpinndx** [comment]
Hi @cheenamalhotra,  

No errors in the logs. I've restarted ADS, uninstalled ADS and installed a fresh download with no luck. The problem seems to be when opening .sql files with the default 'Query Editor'. If I open the files with 'Text Editor' it does open.

Any ideas? Please see my logs below.

Thanks for your help!

[logs.zip](https://github.com/microsoft/azuredatastudio/files/13121899/logs.zip)

**Comment by hjpinndx** [comment]
@cheenamalhotra and update: If I click on File -> New Query, I get renderer errors, please see attached log.

[renderer.log](https://github.com/microsoft/azuredatastudio/files/13122012/renderer.log)

**Comment by cheenamalhotra** [comment]
Can you share your settings.json content (feel free to strip away connection information)?

**Comment by cheenamalhotra** [comment]
Never mind, I believe this is an issue when acquiring Global Connection - async server tree view being unrendered is likely causing problems. I will post an update when we have a potential fix in Insiders that can be tested.

**Comment by hjpinndx** [comment]
A workaround for the issue is to first open the Connections tab so it's rendered and then open the Query Editor.

**Comment by cheenamalhotra** [comment]
@hjpinndx 

Could you please try the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if that resolves the issue?

**Comment by hjpinndx** [comment]
It renders the Connections tab on startup and opening *.sql files work fine in Query Editor. Thanks @cheenamalhotra for your help.
