### ISSUE TITLE
The size of the query Results/Messages panel of the all open Query editor tabs are synchronized. 

### ISSUE THREAD

**Issue by whizkidwwe1217** [microsoft/azuredatastudio#2476]
Issue Type: <b>Bug</b>

1. Execute a script in the current query tab document.
2. Resize the Results/Messages panel.
3. Issue 1: The Results/Messages panel in other query tabs also resize.
4. Issue 2: Unable to minimize or close the Results/Messages panel.
![image](https://user-images.githubusercontent.com/1977391/45281971-259bc280-b50c-11e8-83c1-3f59b774eede.png)
5. Issue 3: When switching to other tabs, the panel resizes to the same height as the panel in the previous tab.
![image](https://user-images.githubusercontent.com/1977391/45282019-4c59f900-b50c-11e8-9a23-89890faccc36.png)

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (6.16GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.1.5
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
Thanks for reporting these bugs.  I believe these  issues are fixed in current build (I could no longer repro).  Please let us know if you're still impacted by these bugs.
