### ISSUE TITLE
Compare Details Section not able to maximize.

### ISSUE THREAD

**Issue by mohammadsjr** [microsoft/azuredatastudio#24787]
Type: <b>Bug</b>

1. Install Schema compare plugin
2. Select two DB schema to compare and compare
3. Check Compare Details Tab, only 2 line of code can able to see, it is difficult to do right scroll

Azure Data Studio version: azuredatastudio 1.44.1 (8f53a316fa00a98264f1ab119641cd540b5af25c, 2023-06-01T02:12:48.765Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i5-1245U (12 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.68GB (3.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azcli|Mic|1.8.0
azuremonitor|Mic|0.1.9
machine-learning|Mic|0.12.0
powershell|ms-|2023.6.0
schema-compare|Mic|1.21.0

</details>

**Comment by kisantia** [comment]
Please reopen if more details can be provided
