### ISSUE TITLE
username and passowrd

### ISSUE THREAD

**Issue by jenna-lab** [microsoft/azuredatastudio#24827]
Type: <b>Feature Request</b>

i forggot my username

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22000
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by cheenamalhotra** [comment]
Hi @jenna-lab 

How can we help?

**Comment by cheenamalhotra** [comment]
No enough info..
