### ISSUE TITLE
Error occurred while opening the properties dialog for login

### ISSUE THREAD

**Issue by mrlife** [microsoft/azuredatastudio#24830]
Type: <b>Bug</b>

This occurs when right-clicking a database login in Security->Logins and choosing Properties (Preview). "SERVER\GROUPNAME" is the login that is right-clicked. The error occurs on all servers and logins.

> An error occurred while opening the properties dialog for login: SERVER\GROUPNAME. An exception occurred while executing a Transact-SQL statement or batch. ---> Cannot execute as the server principal because the principal "SERVER\GROUPNAME" does not exist, this type of principal cannot be impersonated, or you do not have permission.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:38.547Z)
OS version: Darwin x64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
sql-search|Red|0.4.1
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kisantia** [comment]
@corivera can you check if this is something that should be in the November milestone?

**Comment by corivera** [comment]
Disregard that, I was able to get a repro.
