### ISSUE TITLE
Invalid link to download Azure Data Studio Insiders on Mac OS ARM

### ISSUE THREAD

**Issue by iemejia** [microsoft/azuredatastudio#24840]
Version: 1.48.0-insider
Commit: d225efce34448e22d451e02f7c395ac779b16280
Date: 2023-11-01T05:32:44.934Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 23.1.0

Steps to Reproduce:

1. Install Azure Data Studio Insiders Intel version in a Mac OS ARM machine.
2. You will see a pop-up that prompts you to download the ARM version.
3. The URL suggested is https://code.visualstudio.com/docs/?dv=osx&build=insiders which is not the good one. It should probably be https://learn.microsoft.com/azure-data-studio/download-azure-data-studio?tabs=macOS-install#download-the-insiders-build-of-azure-data-studio

![azuredatastudio-wrongarmdownloadlink](https://github.com/microsoft/azuredatastudio/assets/79476/2a180321-cd6d-4ba9-a8b4-cb214ad71258)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
@kisantia For Nov consideration

**Comment by iemejia** [comment]
I just wanted to confirm this is now working correctly, thanks @Charles-Gagnon!
