### ISSUE TITLE
Account not found in MSAL cache after Disabling SQL Auth Provider Setting

### ISSUE THREAD

**Issue by cssuh** [microsoft/azuredatastudio#24853]
- Azure Data Studio Version: 1.47.0 RC
- OS Version: Windows 11

Steps to Reproduce:

1. Disable SQL Authentication Provider
2. Reload ADS
3. Add Account & try to connect to Azure server
4. See the following error: "User account '[user]@microsoft.com' not found in MSAL cache, please add linked account or refresh account credentials."

![image](https://github.com/microsoft/azuredatastudio/assets/18150417/650d85d5-cba4-471d-a7ab-10eb9252e510)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
Verified as fixed.
