### ISSUE TITLE
Zip File Created by Azure Data Studio on Windows Flagged as Trojan

### ISSUE THREAD

**Issue by gburkecw** [microsoft/azuredatastudio#24859]
- Azure Data Studio Version: 1.46.1
- OS Version: Windows_NT x64 10.0.22000

Steps to Reproduce:

Yesterday I closed Azure Data Studio and later received a security report from Cynet antivirus that a malicious file had been downloaded to my machine by the Azure Data Studio process. I suspect this was a false positive, but I am hoping someone involved with this repo could confirm that creation of these zip files is normal for this application, perhaps as part of an auto-update process?

I haven't seen the issue again.

I looked through the code in this repo for 'zip' and 'package' and didn't immediately see anything that would create this sort of file in the Temp directory. If someone could confirm or deny that this is expected behavior for this application, that would give us some peace of mind.

Here are the details:

**Malicious File Path: C:\\Users\\<username>\\AppData\\Local\\Temp\\package-38592DCdVktxkzo1B.zip**

**Process Path: c:\\users\\<username>\\appdata\\local\\programs\\azure data studio\\azuredatastudio.exe**

**Process Command Line:** c:\\users\\gburke\\appdata\\local\\programs\\azure data studio\\azuredatastudio.exe \"C:\\Users\\GBurke\\AppData\\Local\\Programs\\Azure Data Studio\\azuredatastudio.exe\" --type=utility --utility-sub-type=node.mojom.NodeService --lang=en-US --service-sandbox-type=none --inspect-port=0 --user-data-dir=\"C:\\Users\\GBurke\\AppData\\Roaming\\azuredatastudio\" --standard-schemes=vscode-webview,vscode-file --secure-schemes=vscode-webview,vscode-file --bypasscsp-schemes --cors-schemes=vscode-webview,vscode-file --fetch-schemes=vscode-webview,vscode-file --service-worker-schemes=vscode-webview --streaming-schemes --mojo-platform-channel-handle=5440 --field-trial-handle=1692,i,15471854563844679446,11075637917071296911,131072 --disable-features=CalculateNativeWinOcclusion,SpareRendererForSitePerProcess,WinRetrieveSuggestionsOnlyOnDemand /prefetch:8

**Malware Type:** trojan
**Malware ID:** TR/Crypt.ZPACK.Gen2

Does this issue occur when all extensions are disabled?: Yes/No

Cannot reproduce. My only installed extensions are from Microsoft and GitHub:

Azure SQL Migration
GitHub Copilot
SQL Database Projects
SQL Server Dacpac
SQL Server Import
SQL Server Profiler
SQL Server Schema Compare

**Comment by cheenamalhotra** [comment]
This is the ADS Service downloader downloading backend services ("SqlToolsService" most likely, which is the backend service for MSSQL provider that does the real backend job when working with SQL targets.

Since ZIP is created on the fly in the temp directory, it's most likely getting flagged. This is where it happens: https://github.com/microsoft/ads-service-downloader/blob/9fdf0611dcb2eb1e4e68f85944a422427af94914/src/serviceDownloadProvider.ts#L138

One example of log (similar for Kusto as MSSQL):

```
Downloading the package: 'https://github.com/Microsoft/sqltoolsservice/releases/download/4.11.0.2/microsoft.sqltools.servicelayer-win-x64-net7.0.zip' to file: 'C:\Users\CMALHO~1\AppData\Local\Temp\package-21256H8UAe75dab5z.zip'
Downloading https://github.com/Microsoft/sqltoolsservice/releases/download/4.11.0.2/microsoft.sqltools.servicelayer-win-x64-net7.0.zip
(76,661 KB)....................
Downloaded Kusto Tools Service
Installing the package from file: C:\Users\CMALHO~1\AppData\Local\Temp\package-21256H8UAe75dab5z.zip
Installing Kusto Tools Service to c:\Users\cmalhotra\Code\GitHub\azuredatastudio\extensions\kusto\out\sqltoolsservice\Windows\4.11.0.2
Extracting arhive 'C:\Users\CMALHO~1\AppData\Local\Temp\package-21256H8UAe75dab5z.zip' to 'c:\Users\cmalhotra\Code\GitHub\azuredatastudio\extensions\kusto\out\sqltoolsservice\Windows\4.11.0.2'.
Installed Kusto Tools Service
Deleted the package file: C:\Users\CMALHO~1\AppData\Local\Temp\package-21256H8UAe75dab5z.zip
```

This file should be deleted after extraction is done, in case it's left behind, you can safely delete it.

@Charles-Gagnon correct me here, if I missed anything.

**Comment by gburkecw** [comment]
Thanks for the detailed answers @Charles-Gagnon and @cheenamalhotra!
