### ISSUE TITLE
Filter (Ctrl + F) under Connections/Servers/Tables do not work

### ISSUE THREAD

**Issue by alex-thom-wein** [microsoft/azuredatastudio#24857]
Type: <b>Bug</b>

Open Connections/Servers/Tables and press (Ctrl + F). Write table name and select "kebab/burger" button (this button have "Filter" label on hover). List of tables remain unchanged.

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22635
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11850H @ 2.50GHz (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.73GB (9.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Hi @alex-thom-wein 

This is in-line with VS Code's filter behavior. See https://github.com/microsoft/vscode/issues/66971 for more information.
