### ISSUE TITLE
Schema Compare failed: Unexpected exception caught during population of source model: Value cannot be null. (Parameter 'catalogStamp')

### ISSUE THREAD

**Issue by GillundGullbrand** [microsoft/azuredatastudio#24893]
- Azure Data Studio Version: v1.21.0
- OS Version: Windows 11 Enterprise Build 22621.2428

Steps to Reproduce:

1. Compare database project with Synapse Data Warehouse in Fabric
2. Error message: "Schema Compare failed: Unexpected exception caught during population of source model: Value cannot be null. (Parameter 'catalogStamp')"
<img width="230" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/143995125/99814875-eda2-4cd9-ae02-57eebaeb58b2">

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by SakshiS-harma** [comment]
@GillundGullbrand What version of SC are you testing with? Is this a consistent repro? Has it ever worked before or it worked before and just recently broken?

**Comment by GillundGullbrand** [comment]
@SakshiS-harma Version 1.21.0. It is the first time I'm trying on Datawarehouse database in Fabric.
<img width="318" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/143995125/5d57c80f-ae65-432f-8893-4f47e694e914">

**Comment by kisantia** [comment]
@GillundGullbrand can you try using the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch)? This was fixed recently and should be in the next stable ADS build (due to be released soon).

**Comment by GillundGullbrand** [comment]
@kisantia Thanks, it worked in the latest insider build.
