### ISSUE TITLE
UserName cannot be null or empty when using SqlLogin authentication

### ISSUE THREAD

**Issue by drmcclelland** [microsoft/azuredatastudio#24899]
Type: <b>Bug</b>

I am trying to test a connection string to an Azure SQL Server that I copied directly from the Azure Portal (server and DB names removed):

`Server=tcp:<myservername>.database.windows.net,1433;Initial Catalog=<mydatabasename>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Default";`

However, when I paste the connection string into Azure Data Studio (after selecting Input Type = Connection String), I get the following error when I click the "Connect" button:

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/a58f7e01-341d-4349-b929-c0dc871d8dc7)

...but I'm not trying to connect with a SQL Login!!!

Azure Data Studio version: azuredatastudio 1.46.1 (ba29842b81dec01177415e53948ca2168e69c3f8, 2023-10-02T18:14:22.887Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-1185G7 @ 3.00GHz (8 x 2995)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (15.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by drmcclelland** [comment]
Additionally, if I tweak the connection string (copied from the Azure Portal) to use `Authentication=Active Directory Interactive` I get a slightly different error message:

`Error: Failed to get Azure account token for connection`

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/0ab90c69-c117-48b6-8314-4a47d265e85d)

**Comment by cheenamalhotra** [comment]
Hi @drmcclelland 

We don't directly support specifying 'Active Directory Default' with ADS as of now.

When setting "Active Directory Interactive", please ensure you provide User Id as email address of the user to make it work. User Hint is required in ADS, since before making a connection, an Azure account is required to be added.

**Comment by drmcclelland** [comment]
Thanks @cheenamalhotra, I have modified the connection string as you suggested:

```
Server=tcp:<myservername>.database.windows.net,1433;Initial Catalog=<mydatabasename>;User ID=<myusername@mycompany.com>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Interactive";
```

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/aae20d41-7ac3-470f-b684-5c1a2d1e8ddd)

When I click "Connect" I never get an interactive prompt...   all I get is the following error message:

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/720bc823-f263-49c6-b2b0-a1b492b3a678)

**Comment by drmcclelland** [comment]
@cheenamalhotra any update on this issue?

**Comment by cheenamalhotra** [comment]
@drmcclelland 

We recently addressed this issue in the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch), could you give it a try?

**Comment by drmcclelland** [comment]
Using the "system installer" for the insiders build:  

```
Version: 1.48.0-insider (system setup)
Commit: ded5c2dedb277127a07e31d306e610a4e92867d7
Date: 2024-01-18T06:31:37.257Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
```

Connection Details - using `Active Directory Interactive` authentication:

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/b441c167-caf7-415a-9bbd-6fa12c82d969)



I still get the same error:

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/d1bf0086-b9db-498b-b40f-1ff27fe6bf13)

**Comment by cheenamalhotra** [comment]
Can you confirm you have added user account for same email address under Azure Accounts before attempting this connection?

**Comment by drmcclelland** [comment]
Yes, I can confirm that I have set it up already:  

![image](https://github.com/microsoft/azuredatastudio/assets/6124858/8f3a744c-61ab-439d-8432-f992082e2229)

**Comment by drmcclelland** [comment]
I believe I may have identified the issue!  When I added my Azure Account, it has the following email address:

`MYUSERNAME@mycompany.com`

When I used a connection string, I had tried the following:

```
Server=tcp:<myservername>.database.windows.net,1433;Initial Catalog=<mydatabasename>;User ID=<myusername@mycompany.com>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Interactive";
```

Notice that the email address in my connection string was all lowercase...   but when I tried this instead:

```
Server=tcp:<myservername>.database.windows.net,1433;Initial Catalog=<mydatabasename>;User ID=<MYUSERNAME@mycompany.com>;Encrypt=True;TrustServerCertificate=False;Connection Timeout=30;Authentication="Active Directory Interactive";
```

... changing the case of my email address to exactly match the email address for my Azure Account made the connection string works!

**Comment by drmcclelland** [comment]
Thank you for fixing this @cheenamalhotra!  I have verified that it is working for me as of the Azure Data Studio 1.48.0 release.
