### ISSUE TITLE
Add support for the NoSQL for CosmosDB emulator (local)

### ISSUE THREAD

**Issue by ericvdberge** [microsoft/azuredatastudio#24925]
I would like to have a possibility to use azure data studio in combination with the NoSQL for CosmosDB emulator (local) testing environment.

The alternative is to use the data explorer on the local website that the emulator is providing, but it would be way nicer to use azure data studio to connect with the databases.

I am running the docker container of the emulator that you can find [here](https://learn.microsoft.com/en-us/azure/cosmos-db/emulator):

**Comment by cheenamalhotra** [comment]
@languy FYI.

Could you transfer this to ADS Cosmos DB extension for ownership?

**Comment by cheenamalhotra** [comment]
@kisantia @alanrenmsft could you help transfer?

**Comment by alanrenmsft** [comment]
@cheenamalhotra I no longer see the cosmos extension as transferable target, could you please email Laurent directly?

**Comment by cheenamalhotra** [comment]
@languy doesn't have transfer permission on ADS repo, can you grant him?

**Comment by alanrenmsft** [comment]
@ericvdberge this is the repo for the cosmos db extension: https://github.com/Azure/azure-cosmosdb-ads-extension, could you please open the issue over there?

**Comment by cheenamalhotra** [comment]
Closing in favor of https://github.com/Azure/azure-cosmosdb-ads-extension/issues/103
@ericvdberge please follow the same for updates.

Thanks!

**Comment by ericvdberge** [comment]
Hi @cheenamalhotra, thank you for opening the new thread on the right place.

**Comment by languy** [comment]
NoSQL support is currently available in the ADS insider track. You can download ADS Insiders [here](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and install the Azure Cosmos DB extension v0.4.0 which supports NoSQL. Connect using the emulator's connection string and you should be able to manage your databases/collections and also query the data via a query editor.
