### ISSUE TITLE
Can't start client flat file import service on MacBook

### ISSUE THREAD

**Issue by jamesyoung007** [microsoft/azuredatastudio#24965]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by cheenamalhotra** [comment]
@jamesyoung007 try looking at logs as mentioned here: https://github.com/microsoft/azuredatastudio/issues/24612#issuecomment-1806102413
I wonder if it's the same issue relating to slow download speed.

**Comment by jamesyoung007** [comment]
I tried it on Windows PC, it worked straight away, I suspect that this extension might encounter some security settings on MacOS.

**Comment by cheenamalhotra** [comment]
I cannot reproduce in macOS myself, so it you can share logs, we can take a look at what's happening there.

**Comment by cheenamalhotra** [comment]
Can you try installing Rosetta using below command:
```
softwareupdate --install-rosetta
```

**Comment by jamesyoung007** [comment]
yes, it worked, many thanks
