### ISSUE TITLE
Import wizard not opening

### ISSUE THREAD

**Issue by mrlife** [microsoft/azuredatastudio#24975]
Type: <b>Bug</b>

Selecting "Import wizard" on a database shows "Activating Extensions..." on the bottom left of the app but does not do anything else. It was working previously.

Azure Data Studio version: azuredatastudio 1.47.0 (Universal) (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:18:22.205Z)
OS version: Darwin arm64 22.6.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
sql-search|Red|0.4.1
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kisantia** [comment]
@mrlife do you see the import extension getting activated if you go to the Output view and select "Extension Host" in the dropdown? 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/2b7fa38f-a2cb-4126-987a-be4904381ad7)

Also check if there are any errors when "Flat File Import Service" is selected in the Output view

**Comment by mrlife** [comment]
@kisantia Thanks for the suggestions. I had already closed Azure Data Studio and don't see anything in those sections now. Is there a log history somewhere?

After 10 minutes or so, all of the Import wizard panes opened up at the same time. There was some kind of significant delay there.

**Comment by kisantia** [comment]
might be similar to the slow download speed mentioned in https://github.com/microsoft/azuredatastudio/issues/24612#issuecomment-1806824359

**Comment by mrlife** [comment]
> might be similar to the slow download speed mentioned in [#24612 (comment)](https://github.com/microsoft/azuredatastudio/issues/24612#issuecomment-1806824359)

Yes, that could definitely be it. I have previously used the Import wizard, but maybe it was downloading an update to it?

**Comment by cheenamalhotra** [comment]
Closing as issue is resolved and was related with network delay.
