### ISSUE TITLE
Results not appearing when (bad?) xml in response?

### ISSUE THREAD

**Issue by RandomBlueThing** [microsoft/azuredatastudio#24989]
Type: <b>Bug</b>

varchar table column containing xml-looking data returns no data if xml looks off?

example:

```
declare @test table (NotXml varchar(max))

insert into @test values (
    '<a>{0}</a><br />xx'
)

select * from @test
```

Expected: Single row retured:
```
 '<a>{0}</a><br />xx'
```
Actual: Returns no results

Think I can see the results appear briefly then disappear again.

Removing either the [br] or the 'xx' (either from the initial insert data or via a replace() in the query) returns expected results

---

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1260P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.61GB (8.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.82.15
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
whoisactive|Mic|0.1.5
azdata-sanddance|msr|4.0.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @RandomBlueThing 

This has been fixed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), and will be included in next stable release.

Thanks!
