### ISSUE TITLE
Getting results from a different db

### ISSUE THREAD

**Issue by cyberdrome** [microsoft/azuredatastudio#24995]
Type: <b>Bug</b>

I am connected to an SQL server through VPN. At random times I receive results from a different database with a similar schema.

I run e.g. "select * from customers" and I get the customers from the database "mydb" instead of the database "mydb_test" where I am currently at (both databases are on the same server). If I change the databases back and forth from the "Database:" dropdown at the top then the problem seems to be fixed but then it appears again. I have noticed that the problem shows mainly if I've been idle for a while.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:19:19.203Z)
OS version: Darwin arm64 23.1.0
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.49.0

</details>

**Comment by cheenamalhotra** [comment]
@cyberdrome 

Can you enable capturing logs as per above comment, and when you do reproduce the issue, retrieve logs and upload them here. Please make sure to mask any servername or any other sensitive data as needed.

**Comment by kisantia** [comment]
please reopen if logs can be provided, as requested above.
