### ISSUE TITLE
Please allow graphical mgmt like create DB, managing logins etc. like in SSMS.

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#25]
Created from twitter feedback: https://twitter.com/borgdylan/status/930894693487071233. Request is for graphical create database and user / login management. We can track using this issue.

**Comment by borgdylan** [comment]
Thanks for adding my issue.

**Comment by kburtram** [comment]
We added `Database Administration Tool Extensions for Windows` extension to the gallery this month to fill this gap.  Please log new issues for any missing dialogs.

**Comment by borgdylan** [comment]
That extension only covers the Windows use case. Is naything planned for other OSes?
