### ISSUE TITLE
Feature Request: Dual Sidebars

### ISSUE THREAD

**Issue by Grzy7316** [microsoft/azuredatastudio#250]
- SQL Operations Studio Version: sqlops-windows-0.23.6
- OS Version: Windows 10 Enterprise 

Steps to Reproduce:
When using this product it would be extremely helpful to have the option to have a sidebar on both sides. 
That way it would be possible to have the file explorer on one side of the window and the object explorer on the opposite side.   If this is not possible, would it be possible to add the object explorer as a widget to the dashboard? The search widget does not give a hierarchical view of things the way the object explorer does.

**Comment by kburtram** [comment]
I'm going to close out this upstream issue.  This isn't a shell feature that we would want to implement without having the change accepted upstream in the VS Code source code.  Please open against VS Code's repo if you're still interested in this feature.  Thanks!
