### ISSUE TITLE
Field with HTML Markup Causes Invalid Results

### ISSUE THREAD

**Issue by steve-landis** [microsoft/azuredatastudio#25004]
Type: <b>Bug</b>

SSMS handles this correctly, but something strange going on in ADS.

DECLARE @sampleData nvarchar(500) = `'<p>What the heck?</p><p> </p><p>&nbsp;</p>'`

-- Returns 0 rows
SELECT @sampleData SampleData

-- Returns 1 row
SELECT STRING_ESCAPE(@sampleData, 'json') SampleData

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (1.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
net-6-runtime|Mic|1.1.0
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
server-report|Mic|0.2.4
sql-database-projects|Mic|1.4.1
sql-migration|Mic|1.5.0
whoisactive|Mic|0.1.5
dotnet-interactive-vscode|ms-|1.0.3504060
jupyter|ms-|2022.4.1021342353
azdata-sanddance|msr|4.0.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by cheenamalhotra** [comment]
Re-opened to consider in the next Hotfix release

**Comment by Charles-Gagnon** [comment]
@cheenamalhotra Have you had a chance to test out the perf with the new implementation? I definitely think running it through a couple stress test (large data sets, long strings, etc.) before we release it would be a good idea.

**Comment by cheenamalhotra** [comment]
Closing as fixed with PR #25018
