### ISSUE TITLE
Add Folder to Workspace issue

### ISSUE THREAD

**Issue by Susja** [microsoft/azuredatastudio#25002]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

I am using ADS on macOS.
I have a few drives that I mount after I login and connect to VPN.
Then I add those drives to Workspace.
E.g. my drives are A, B and C.
In ADS Explorer I added it and I see A, D and C.
Recently I started to see instead of C drive ... drive called C-1
In macOS Finder I still have C and only in ADS it's pointed as C-1
Remove and add back did not help.
I still see in ADS Explorer: A , B and C-1
in macOS Finder I see A, B and C
Hence ... I think something with ADS Workspace issue.
It's minor ... but it's irritate me.
Could you suggest how to fix C-1 in ADS for C?
Note: I don't have sudo access on macOS ... but it worked fine before and I don't know the reason why it changed.
btw: every time I remove folder from Workspace and add back C ... it still shows C-1 instead of C.
Any suggestions?
Thanks

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@susja can you try seeing if the same thing happens with vscode? The 1.47 ADS release brought in a merge up to vscode version 1.82, which might have introduced this changed behavior

**Comment by Susja** [comment]
Hi @kisantia 
Thanks for replying 
Unfortunately I can’t validate it because I have only ADS installed on this MacBook. I don’t have VS Code installed.

**Comment by Susja** [comment]
It's not the issue for me anymore hence, I propose to Close it.
