### ISSUE TITLE
Power Apps Error

### ISSUE THREAD

**Issue by artross26** [microsoft/azuredatastudio#25006]
Type: <b>Bug</b>

Accessing SQL DB from Power Apps, the app does everything except update activites. I recieve the following error: "Network error when using the patch function OnSelect". The code below is what executes to point and then update.

Patch(
    Student,
    LookUp(Student, Student_TAF_Key = Gallery1.Selected.Student_TAF_Key),
    {
        Student_Media: Text(editform_UserDetails.LastSubmit.Student_Media)  // Make sure to convert to the appropriate data type
        // Include other fields as needed
    }
)

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1255U (12 x 2611)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (2.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|1.5.5

</details>

**Comment by cheenamalhotra** [comment]
Are you running this query in ADS or Power Apps? 
Can you elaborate how is ADS related to the issue?

**Comment by artross26** [comment]
It says: “Network error when using patch: there is an error on the server.”
I don’t know what I am to do to make this work with the server since it does not say what the error is.

This is the code I am using:

Patch(
    Student,
    LookUp(Student, Student_TAF_Key = Gallery1.Selected.Student_TAF_Key),
    {
        Student_Media: Text(editform_UserDetails.LastSubmit.Student_Media)  // Make sure to convert to the appropriate data type
                                                                                                                                      // Include other fields as needed
    }
)

Thanks.

**Comment by cheenamalhotra** [comment]
Do you have any screenshot you can share?

**Comment by cheenamalhotra** [comment]
Screenshot didn't come through.. can you post it on GitHub?

Also, are you running this code in Azure Data Studio or Power Apps?
It doesn't look like you're executing a SQL Script, so I'm not sure how is it ADS related.

**Comment by artross26** [comment]
![Power Apps - Error](https://github.com/microsoft/azuredatastudio/assets/110565860/d7672393-e738-4a21-97fb-f59881a90aee)
This is being done using Power Apps. The DB is on Azure SQL and sever.

**Comment by artross26** [comment]
There is a connector to Azure SQL. It is erroring out on any function involving an update.

**Comment by artross26** [comment]
This is yet to be resolved. Can you please connect again?

**Comment by cheenamalhotra** [comment]
This repository is for [Azure Data Studio](https://learn.microsoft.com/en-us/azure-data-studio/), we don't provide support for Power Apps.
