### ISSUE TITLE
Email addresses and phone numbers in results grid have annoying click behavior

### ISSUE THREAD

**Issue by RandScullard** [microsoft/azuredatastudio#25013]
Type: <b>Bug</b>

In a query results grid, any cell containing an email address or phone number displays the text as a clickable link, and when I click anywhere in the cell, it opens a new editor window containing just the text from the cell in the editor.

This is annoying - I often click in a cell with the intent of just selecting the cell, and it's very distracting to have another editor open up. I tried to find a setting to disable this behavior, but I had no luck.

If there is going to be special click behavior for certain types of data, it would be better if the user had to hold down the Ctrl key to get the special behavior. The default click should just select the cell, no matter its contents. And in any case, this special behavior of opening another editor is not particularly useful.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (16.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
profiler|Mic|0.14.0
azdata-sanddance|msr|4.1.1

</details>

**Comment by kisantia** [comment]
Might be related to https://github.com/microsoft/azuredatastudio/issues/24929, which has already been fixed in insiders. @RandScullard can you try the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and check if this is still happening?

**Comment by RandScullard** [comment]
@kisantia I just tried the latest insiders build, and it is fixed. Clicking the cell just selects it. Thanks!

**Comment by kisantia** [comment]
Great! Thanks for confirming that it's fixed insiders. The fix will be available in the next ADS stable release, currently targeted for February.
