### ISSUE TITLE
SELECT * does not show results

### ISSUE THREAD

**Issue by stephan-ansems** [microsoft/azuredatastudio#25025]
Type: <b>Bug</b>

When run the following three queries:
```
SELECT * FROM «table» WHERE id=«id»
SELECT id, «column» FROM «table» WHERE id=«id»
SELECT COUNT(*) FROM «table» WHERE id=«id»
```

I get no results from the first query
Some data from the actual record in the second.
And the value 1 from the third

Note that i tried the exact same in SSMS and there I do get full results when using ```SELECT *```.

Screenshot:
![image](https://github.com/microsoft/azuredatastudio/assets/37153948/013ecb95-3da7-445f-83fa-e5ef49959e05)

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 1382)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (1.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuremonitor|Mic|0.1.9
import|Mic|1.5.5

</details>

**Comment by cheenamalhotra** [comment]
Hi @stephan-ansems 

Can you please try the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and let us know if that works for you?

**Comment by digitalcolony** [comment]
The insiders build fixed this issue for me.

**Comment by cheenamalhotra** [comment]
Closing as resolved,
