### ISSUE TITLE
Slow execution of queries

### ISSUE THREAD

**Issue by rodrigoreissm** [microsoft/azuredatastudio#25037]
Type: <b>Bug</b>

Frequentemente acontece uma lentidão ao executar querys, mesmo estando tudo correto com a conexão ao servidor SQL, obrigando a reiniciar o azure data studio.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz (16 x 2304)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.78GB (2.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-prompt|Red|0.2.12
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by rodrigoreissm** [comment]
There is often a slowdown when executing queries, even though everything is correct with the connection to the SQL server, forcing you to restart Azure Data Studio.

**Comment by cheenamalhotra** [comment]
Please provide us logs to understand time delay so we can assist you better.
