### ISSUE TITLE
Synapse Serverless Pool Missing Programmability folder and objects

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/azuredatastudio#25034]
Type: <b>Bug</b>

when navigating to the objects under a synapse serverless pool the folder for Programability is missing. This folder should contain the functions and stored procedures in the serverless pool

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-1065G7 CPU @ 1.30GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (15.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.49.0
azcli|Mic|1.8.0
azuremonitor|Mic|0.1.9
cms|Mic|0.9.3
dacpac|Mic|1.14.0
kusto|Mic|0.5.8
powershell|ms-|2022.7.2
profiler|Mic|0.14.0
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.4.1
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.5
dotnet-interactive-vscode|ms-|1.0.3255010
jupyter|ms-|2021.8.1046824664
sql-prompt|Red|0.2.12
sql-search|Red|0.4.0

</details>

**Comment by cheenamalhotra** [comment]
@jasonhorner 

I see them just fine.. 🤔 
Tested in both Server and Azure tree views..

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/34e3e2de-a9ee-4a6b-a338-f08efd0760a7" width=500 />

**Comment by jasonhorner** [comment]
@cheenamalhotra thanks for the quick response. This is for the Synapse Serverless Pool it looks like you are using a Dedicated pool from the screenshot above.  Here is what I see from my end: 
![image](https://github.com/microsoft/azuredatastudio/assets/7981510/3dd58b1f-5281-4246-8e58-664dc159aa71)

it should be noted I had to manually register the serverless pool db because it isn't enumerated in the Connections - >Azure per this semi-related request: https://github.com/microsoft/azuredatastudio/issues/24330

As a small piece of additional feedback it would be great to have a different icon for the different types of sql servers. for example Serverless pool, Dedicated pool, Azure SQLD B etc. 

The Connections -> Azure browsing seems to do this: 
![image](https://github.com/microsoft/azuredatastudio/assets/7981510/cbc80d4a-b2a7-4f1a-a0ca-658d2bf44d73)

but it doesn't happen in Connections - > Servers tab:
![image](https://github.com/microsoft/azuredatastudio/assets/7981510/ac3f49ac-ceb0-4e6a-935a-39a5747bce3d)

I can open this as a new feature request if that is helpful but it's probably more important to get the object browsing functionally fully working. thanks again.

**Comment by cheenamalhotra** [comment]
Thanks for the details, I can reproduce it now.
Will investigate and get back on this.

**Comment by KRallanwang** [comment]
Hello, I have found the same issue, ie., in Synapse Studio, when conncted to a Serverless SQL pool, the "Programmability" folder is not available.

Have you addressed it yet?

**Comment by SanderDoD** [comment]
Is there any update when this will be updated? It is a major drawback for us potentially having to migrate away from Azure Data Studio.

**Comment by kristofegedy** [comment]
I have the same issue, and I agree this is a major problem for anyone who works with Synapse and has no alternatives but to use Azure Data Studio (using Mac or Linux). Please let us know if there is any plan to fix this

**Comment by JohnE4U** [comment]
This issue also affects Fabric data warehouse.
Is there any update?

**Comment by GraemeBrownTL** [comment]
We are also experiencing this issue, using Azure Serverless SQL DB. Would be great to see a fix!

**Comment by kburtram** [comment]
Fixed in 1.50 release.
