### ISSUE TITLE
spawn unkown system error -86 with import extension

### ISSUE THREAD

**Issue by vaishnavitripa** [microsoft/azuredatastudio#25038]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1.
2.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by vaishnavitripa** [comment]
![Uploading Screenshot 2023-11-23 at 11.15.30 PM.png…]()

**Comment by vaishnavitripa** [comment]
![Uploading Screenshot 2023-11-23 at 11.15.30 PM.png…]()

**Comment by vaishnavitripa** [comment]
it is showing this error and nothing happened with import wizard.

**Comment by cheenamalhotra** [comment]
Can you please try uploading screenshot again? There seems to be an issue with uploaded image.

**Comment by cheenamalhotra** [comment]
Please try installing Rosetta with below command, as we've seen similar issues getting resolved with it:
```
softwareupdate --install-rosetta
```

**Comment by vaishnavitripa** [comment]
Thank you so much. It works.

**Comment by cheenamalhotra** [comment]
Closing as resolved.
