### ISSUE TITLE
Query grid scrollbar overlaps over buttons

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2504]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Run a query 
2. Click on one of the Export buttons

Expected: Buttons are unobstructed

Actual: Scrollbar overlays buttons

> Note: I see the scrollbar overlaps content in other places.  I didn't see anywhere that buttons are overlapped.  I'm fine with this change as long as we do a quick UX review.

![image](https://user-images.githubusercontent.com/599935/45376637-2df80a00-b5ad-11e8-97b9-29d56679564c.png)

**Comment by smithaBharadwaj** [comment]
We need to look at designing the placement of these icons better. As there was another issue where we see a column of these icons if the results don't have many rows.
