### ISSUE TITLE
not able to select notebook - python

### ISSUE THREAD

**Issue by MKLZur** [microsoft/azuredatastudio#25049]
- Azure Data Studio Version:`.34.0
- OS Version:Windows_NT x64 10.0.19045

Steps to Reproduce:

1.Click on File -> New Notebook
2.Select Python3
3.Select New Python Installation
4.Second step click on next
5. It starts downloading python package - mentioning installing notebook dependencies, then it writes:
Unpacking python package
Python download is complete
Encountered an error when trying to retrieve list of installed packages: Unexpected token c in JSON at position 85
Installing Notebook dependencies failed with error: Cannot read property 'version' of undefined

Does this issue occur when all extensions are disabled?: Yes/No Yes
![ADS_Fail2](https://github.com/microsoft/azuredatastudio/assets/152166993/730c0546-fac1-4900-af14-fafd8e606fff)
![ADS_Fail](https://github.com/microsoft/azuredatastudio/assets/152166993/9d15a32b-3bf3-4615-97f6-3dedfe3ce041)

**Comment by kisantia** [comment]
@MKLZur can you try the [latest ADS release](https://github.com/microsoft/azuredatastudio#download-the-latest-azure-data-studio-release) (1.47.0) and see if this is still happening?

**Comment by MKLZur** [comment]
Hello apparently i did some copy paste error. I am already using latest version and its happening there.
![ADS version](https://github.com/microsoft/azuredatastudio/assets/152166993/9e4603e9-a7bd-4103-b2f9-dceca8e74fcb)
