### ISSUE TITLE
Support ‘Connect’ command to work from Command Line interface

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#25055]
- Azure Data Studio Version: main
- OS Version: Windows 11

Execute command from command prompt:
`azuredatastudio --command connect --user sa --server localhost`

Spent some time while working on https://github.com/microsoft/azuredatastudio/issues/25050, I noticed that prompt to 'connect' doesn't work when invoked from command line, and threw this error instead. It doesn't seem to cause issues when invoked from URL:

```
[error] command 'connect' not found: Error: command 'connect' not found
    at S._tryExecuteCommand (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2322:17512) [<root>]
    at S.executeCommand (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2322:17394) [<root>]
    at async C.processCommandLine (vscode-file://vscode-app/c:/Users/cmalhotra/AppData/Local/Programs/Azure%20Data%20Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:2097:19922) [<root>]
```

It seems as though this command got removed at some point, whereas the code to call the command stayed..
As the code that invoked this command was added quite long ago in PR https://github.com/microsoft/azuredatastudio/issues/4364 and hadn't been modified in a long time..

cc @Charles-Gagnon @alanrenmsft for awareness.

**Comment by Charles-Gagnon** [comment]
FYI, the command is supposed to be for executing a command, so `connect` doesn't work because there's no command named `connect`. So this is working as intended - just passing in the server info will try and connect automatically.

The URI handling is a bit different since that uses the paths in the URI to determine what to do.

Here's the logic for the various combinations that it should be supporting. 

```
	// (serverName, commandName) => Connect object explorer and execute the command, passing the connection profile to the command. Do not load query editor.
	// (null, commandName) => Launch the command with a null connection. If the command implementation needs a connection, it will need to create it.
	// (serverName, null) => Connect object explorer and open a new query editor if no file names are passed. If file names are passed, connect their editors to the server.
	// (null, null) => Prompt for a connection unless there are registered servers
```

**Comment by cheenamalhotra** [comment]
I see, I guess I understood it would work when comparing with URL command values.

We can treat it a feature in that case to make sure existing behaviour is intact to invoke command service for commands that are not 'connect'/'openConnectionDIalog' but these are also supported to keep parity with URL parameters. As a developer it seemed like a bug.

**Comment by Charles-Gagnon** [comment]
Currently the command functionality will also connect the profile - if you combine them so you specify either connect or running a command then that will break. So you'd have to add support for combining multiple commands if that was the case.

So given that I think it'd be simpler to have actions (connect/openConnectionDialog) separate from commands. And I'd even say that we should consider having connect be the default and just have a simple flag for opening the connection dialog. That might be an issue if we want to add other actions later on - but I think that's unlikely enough to happen (and honestly should probably be done through a command directly instead) that it's fine enough for now.

**Comment by cheenamalhotra** [comment]
> Currently the command functionality will also connect the profile first - if you combine them so you specify either connect or running a command then that will break. 

This was also an issue I saw, that when running command=openConnectionDialog, it would always connect irrespective of us wanting to simply open the connection dialog. We can do that for other commands maybe, but connecting (always) when opening a dialog seemed to cause issues, e.g. if password was not available, or tokens are not refreshed. It causes the tool to first fail and then open dialog.

**Comment by Charles-Gagnon** [comment]
Oh huh, yeah that seems like a bug. If we're just opening the connection dialog it shouldn't be connecting.

(for commands I think that makes sense though, as many commands will expect to be passed an active profile)

**Comment by cheenamalhotra** [comment]
So I agree with treating it 'connect/openConnectionDialog' like an action, and defaulting to 'connect' with a command specified. It however contradicts in the command line interface, as the same argument (`--command`) is being repurposed for commands/actions. It would have been better if there was a flag to open connection dialog and command simply executed one like you said.
