### ISSUE TITLE
openConnectionDialog URI Handler doesn't prompt to install missing extension

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#25050]
1. Open ADS via URI using the `openConnectionDialog` path and a provider specified that isn't installed - e.g. `azuredatastudio://openConnectionDialog?server=myserver.mysql.database.azure.com&provider=MySQL&user=sa`

Expected : User is prompted to install the missing extension

Actual : The user is only prompted if they want to open the connection, but then the connection dialog just defaults to the MSSQL provider since the one specified doesn't exist.

**Comment by Charles-Gagnon** [comment]
I wonder if we should even just put that logic in the connection dialog itself so if it's ever opened with an unknown provider it prompts to install the extension? That might help other scenarios - for example extensions that are opening connection dialogs themselves so they don't have to do the check for the extension before opening the dialog (of course in that case I'd suggest that they have an extension dependency on the provider extension in the first place, but some extensions might be more generic so wouldn't be able to easily do that for all provider types)

**Comment by cheenamalhotra** [comment]
I too think it would be best to raise a prompt in the connection dialog area, so it applies generically to any extension/cli. Will take a look to see its feasibility..

**Comment by dlevy-msft** [comment]
Is there a chance that this is something that vs code has already solved for and we just need to enable due to our tailored marketplace?
