### ISSUE TITLE
Connected Context profiles don't pass through when executing commands from commandline

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#25068]
- Azure Data Studio Version: main
- OS Version: Windows 11

Steps to Reproduce:

1. Try running ADS with command line as below:
  `azuredatastudio --command=explorer.query --server=localhost --user=sa`
2. It is expected that 'connect' is default action, which runs and connection is opened.
3. After opening connection, `azdata.connectedContext` is passed to commandService as per design, which "should" ideally pass connection profile from the context and commands should consume it for creating connection.

This is where the connected context is set:
https://github.com/microsoft/azuredatastudio/blob/fed32bf7b2550c07f3be5a2b76193e455a6ba6e9/src/sql/workbench/contrib/commandLine/electron-sandbox/commandLine.ts#L141

Definition of `azdata.ConnectedContext` interface:

https://github.com/microsoft/azuredatastudio/blob/fed32bf7b2550c07f3be5a2b76193e455a6ba6e9/src/sql/azdata.d.ts#L5517-L5524

Command execution receives context here for NewQuery and notice it tries to read `profile` and not `connectionProfile` as set in `ConnectedContext`:

https://github.com/microsoft/azuredatastudio/blob/fed32bf7b2550c07f3be5a2b76193e455a6ba6e9/src/sql/workbench/contrib/query/browser/query.contribution.ts#L93-L97

It seems to be defined here:

https://github.com/microsoft/azuredatastudio/blob/fed32bf7b2550c07f3be5a2b76193e455a6ba6e9/src/sql/workbench/browser/actions.ts#L23-L26

So clearly `profile` and `connectionProfile` don't match and connection is not made in the query editor when opened this way.

### Expected behavior

Connection Profile property names should be consistent in both interfaces.

### Thoughts
`azdata.ConnectedContext` seems to be used only in Notebooks & command line area, is it possible to rename `connectionProfile` to `profile` to fix this issue? It will be a breaking change in `azdata` for sure... but seems critical to make this work.

cc @Charles-Gagnon @alanrenmsft

**Comment by Charles-Gagnon** [comment]
I think the reverse is a better option - update BaseActionContext to extend azdata.ConnectedContext and update uses of it to use the connectionProfile property instead.

**Comment by cheenamalhotra** [comment]
Oh yeah, `BaseActionContext` is internal type, easier to patch. Thanks!

**Comment by cheenamalhotra** [comment]
Closing as by design, we'll revisit if there's a huge demand for this.
