### ISSUE TITLE
Expanding ~ 160 tables within different databases each with ~1000 tables hangs OE

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2507]
- SQL Operations Studio Version:
Version 0.33.2
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Create ~200 databases as copies of the db created by this script:
[AdventureWorks2.Sql.txt](https://github.com/Microsoft/sqlopsstudio/files/2372185/AdventureWorks2.Sql.txt)
2. For all 200 databases, repeatedly click on a table in a different database to show the child nodes (columns, keys, indexes etc.) of that table.

Expected: all clicks are responsive and the child nodes of all tables clicked up on show correctly.
Actual: Object Explorer stops responding to clicks after expanding tables of about 160 databases.

**Comment by kburtram** [comment]
Closing older issues.  This is tracked by this similar issue https://github.com/microsoft/azuredatastudio/issues/1205.
