### ISSUE TITLE
Can not show query result

### ISSUE THREAD

**Issue by Coder7777** [microsoft/azuredatastudio#25086]
Version: 1.47.0
Commit: c7c2b2f21505562d21972d4c135119d00806db4f
Date: 2023-11-07T17:18:22.205Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin x64 22.5.0

Steps to Reproduce:

Execute `Select * from Table`, it is very offen to show blank data grid.

I disabled all plugin and relaunch it. but it still show blank data grid. 

This bug happens very offen.

Does this issue occur when all extensions are disabled?: Yes

<img width="1251" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/17242425/4f4362db-e3ba-49cc-be94-c8a36c228426">

**Comment by Coder7777** [comment]
Maybe I find out what cause this bug.

I have a column store the HTML string, if my SQL include that HTML column, the this bug will be reproduced very easily.

If exclude this HTML column, the data grid can show data normally.

**Comment by Coder7777** [comment]
> Could you try the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch)? We recently fixed a related XML format issue in insiders.

It is working fine in Insider version. 

Thanks.

**Comment by cheenamalhotra** [comment]
The fix will be available in next stable release, closing as resolved.
