### ISSUE TITLE
Query Editor doesn't work properly with grid layout

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2509]
- SQL Operations Studio Version: `master`

Steps to Reproduce:

1. Open Grid Layout (2x2)
2. Put a query window with results in top-left and bottom-right cells
3. Drag the horizontal separator up and down

Expected: The content of the editors doesn't overflow cells and all editor content is accessible via the scrollbars.

Actual: Top-left cell overflows into bottom-left cell.  Query text is obscured in the bottom-right cell and isn't accessible via scrollbar.

**Top-Left Scenario**
![image](https://user-images.githubusercontent.com/599935/45381008-f5f6c400-b5b8-11e8-8b93-931cc0e9d22f.png)

**Bottom-Right Scenario**
![image](https://user-images.githubusercontent.com/599935/45381014-fabb7800-b5b8-11e8-9679-2985fa7ee08f.png)

**Comment by anthonydresser** [comment]
This is the problem I pointed out last week regarding the calculation problems in the query editor.

**Comment by kburtram** [comment]
@anthonydresser thanks, I think if this is a big refactor it's better to take the fix in October.  I'll push the milestone.

**Comment by anthonydresser** [comment]
dupe #2815
