### ISSUE TITLE
Request: Include rows count (rows affected) in status bar

### ISSUE THREAD

**Issue by luismiguelgilbert** [microsoft/azuredatastudio#251]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.16299
---

Change Request:
Is there any chance to include rows affected (rows count) in status bar?
I know "rows affected" is shown in messages pane, but I work with "Messages" pane minimized, because i don't like to loose that extra space. However, when I need to know query affected rows count, it's a bit annoying to expand results.

**Comment by kburtram** [comment]
We currently show the row count in the status bar.

**Comment by kburtram** [comment]
There is a bug with update statements that I'll open now, but I assume this is more general, including SELECT, etc.
