### ISSUE TITLE
Backup and Restore operations displays two messages on tasks panel

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#25105]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Start a backup or restore operation
2. Observe the status message of backup/restore in tasks panel
3. Ex: 
![image](https://github.com/microsoft/azuredatastudio/assets/74571829/c352c5da-74b3-480e-90bc-e6fedbee0b95)

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by barbaravaldez** [comment]
@ssreerama, can you confirm if the restore was successful?

**Comment by ssreerama** [comment]
@barbaravaldez  If I remember correctly, no, the restore was failed as per the message-II. Message-I pops up instantly when the process starts.
