### ISSUE TITLE
SSH tunneling

### ISSUE THREAD

**Issue by Nova-Logic** [microsoft/azuredatastudio#25106]
Add ssh tunnelling support for MS SQL databases, MongoDB extensions already supports it.  first request for this feature came more than 5 years ago, most other clients like dbeaver,datagrip and so on supports it, absence of this feature highly decreasing usability of azure data studio

**Comment by cheenamalhotra** [comment]
I've reopened #398 in favor of users requesting a lot for this feature.
That said, it continues to be in backlog for now.
