### ISSUE TITLE
Results not showing / are distorted for one database

### ISSUE THREAD

**Issue by aathar** [microsoft/azuredatastudio#25144]
<img width="500" alt="Screenshot 2023-12-20 1203130" src="https://github.com/microsoft/azuredatastudio/assets/3337849/d9e81b1d-582f-4f4f-a333-5deaa7ff44a0">
Type: <b>Bug</b>

When I write a query like:
SELECT TOP 200 * FROM pubs ORDER BY 1 DESC

it executes the query but the results pane is empty. However, the scroll bar shrinks - showing that some rows were generated but just not showing.
When I scroll down, some rows randomly show up and if I continue scroll up and down, these rows that were showing a moment ago, hide again. 
I am not sure whats causing this behaviour, I have uninstalled and reinstalled the latest version too.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (1.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|4.1.1

</details>

**Comment by cheenamalhotra** [comment]
Hi @aathar 

Could you try the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and let us know if it still occurs?

**Comment by aathar** [comment]
i installed that and it does not seem to happen in the latest insiders build. Thanks

**Comment by cheenamalhotra** [comment]
I will close this as resolved, the fix will be available in the next stable build.
