### ISSUE TITLE
Can't connect with latest Mac OS X version (14.2.1) to any db.

### ISSUE THREAD

**Issue by mirokorja** [microsoft/azuredatastudio#25146]
Type: <b>Bug</b>

Problems with connecting to Azure db's.

Error message:
Failed to authenticate the user in Active Directory (Authentication=ActiveDirectoryInteractive).
Error code 0xinvalid_grant
AADSTS53003: Access has been blocked by Conditional Access policies. The access policy does not allow token issuance.

We have basic conditional access 302 in place. With 14.2.1 it will give the above mentioned error. If you use it with 14.2, then it will go fine through.

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:19:19.203Z)
OS version: Darwin arm64 23.2.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
azcli|Mic|1.8.0
dacpac|Mic|1.14.0
import|Mic|1.5.5
powershell|ms-|2022.7.2
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-assessment|Mic|0.6.4

</details>

**Comment by cheenamalhotra** [comment]
Hi @mirokorja 

ADS cannot do much here since this is an external issue, please troubleshoot using below link and create an Azure support incident if needed: https://learn.microsoft.com/en-us/entra/identity/conditional-access/troubleshoot-conditional-access
