### ISSUE TITLE
Do not appear the extemnsion

### ISSUE THREAD

**Issue by cesarefe** [microsoft/azuredatastudio#25155]
Type: <b>Bug</b>

i have installed the extension but just not appears the option for creating a job or just the extension.

![image](https://github.com/microsoft/azuredatastudio/assets/32394855/3ebb4741-cae2-422c-8e85-1bf0aea8ef73)

Extension version: 0.0.2
Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (3.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
@cesarefe which extension did you install and try to use?

**Comment by kisantia** [comment]
please reopen if more information can be provided
