### ISSUE TITLE
Clicking on a blank result cell opens a new query window

### ISSUE THREAD

**Issue by parvezapathan** [microsoft/azuredatastudio#25153]
Type: <b>Bug</b>

Clicking on a blank result cell opens a new query window

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by cheenamalhotra** [comment]
@parvezapathan 

This has been fixed in the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and fix will be available in the next stable release.
