### ISSUE TITLE
Maximum Call Stack size Exceeded when running multiple notebook's cells

### ISSUE THREAD

**Issue by SqrtPapere** [microsoft/azuredatastudio#25165]
- Azure Data Studio Version: 1.49.0
- OS Version: Windows 11

Steps to Reproduce:

1. run two cells notebook at the same time, only one gets executed and notebook throws error `Maximum Call Stack size Exceeded`

Does this issue occur when all extensions are disabled?: Yes

**Comment by kisantia** [comment]
@SqrtPapere can you check again which ADS version you're using? 1.49.0 doesn't exist yet. The latest stable version is 1.47.0 and insiders is currently 1.48.0-insider.

**Comment by kisantia** [comment]
please reopen if this still happens with the latest ADS release

**Comment by romannl** [comment]
I get the same error message when trying to run 2 SQL cells in parallel

Azure Data Studio v 1.48

More information about my system:
![image](https://github.com/microsoft/azuredatastudio/assets/5169096/18291bf7-41b4-498b-8835-4344fd987c4d)
