### ISSUE TITLE
Selecting string with certain HTML tags causes no records to be returned

### ISSUE THREAD

**Issue by nim81** [microsoft/azuredatastudio#25204]
Type: <b>Bug</b>

Running the following results in no records being returned:
`SELECT '<div><br></div><div><br></div>'`

Certain other combinations of tags seem to cause the same problem but I can't put my finger on exactly what they are - the above is a concrete example.

The following does work:
`SELECT '<div><br></div>`

As does the following (extra line break in the first div): 
`SELECT '<div><br><br></div><div><br></div>'`

Azure Data Studio version: azuredatastudio 1.47.0 (c7c2b2f21505562d21972d4c135119d00806db4f, 2023-11-07T17:17:45.669Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (9.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.6.0
machine-learning|Mic|0.12.0
profiler|Mic|0.14.0
schema-compare|Mic|1.21.0
azdata-sanddance|msr|4.0.1
extra-sql-script-as|pac|0.5.0

(3 theme extensions excluded)

</details>

**Comment by cheenamalhotra** [comment]
Hi @nim81 

This has been addressed in the latest insiders build, and fix will be available in the next Stable release.
