### ISSUE TITLE
Azure Data Studio not honoring Encrypt=false

### ISSUE THREAD

**Issue by dansanderssns** [microsoft/azuredatastudio#25200]
- Azure Data Studio Version: Version: 1.47.0 (system setup)
- OS Version: Windows_NT x64 10.0.20348

Steps to Reproduce:

1.  Start Azure Data Studio
2.  Create Connection to SQL Server not using encrypted TSL connections.  
3.  Uncheck "Use Encryption"
4.  Try to connect.  
5.  We receive an error.  (Stack Trace attached)
6.  We sniffed the network and can confirm that Azure Data Studio tried to connect with TLS 2.0.  (Screen shot attached)

Azure Data Studio seems to force TSL 2.0 on every connection regardless
![error3](https://github.com/microsoft/azuredatastudio/assets/156346995/ef54a0b4-2035-4604-9998-078ff3cbbf22)
![error2](https://github.com/microsoft/azuredatastudio/assets/156346995/cfe2f54a-c03a-4b10-96e9-b42a945d12bb)
 of configuration on Connection Screen.l
[error4.txt](https://github.com/microsoft/azuredatastudio/files/13906133/error4.txt)

Does this issue occur when all extensions are disabled?: Yes/No
Yes

**Comment by cheenamalhotra** [comment]
@dansanderssns 

Pre-Login handshake is always encrypted to pass connection info securely.

You should also verify if the server is enforcing Strict encryption here as the above error could occur when client attempts to use TLS 1.2 whereas server requires TLS 1.3 (Strict) encryption.

**Comment by dansanderssns** [comment]
@cheenamalhotra Thank you.  The server is a 2012 server that has never enforced encryption.  I checked the server and it doesn't have a certificate for SQL. I am trying to use Azure Data Studio to convert all these databases off the the 2012 server and onto Azure Managed Instance.  

I have done this before and there has never been an issue.  But this VM I am using is a brand new Azure 2022 server.  So, I haven't used one of those.,

Azure Data Studio is still forcing TLS 1.2.

**Comment by dansanderssns** [comment]
I found a work around.  This was not just a Azure Data Warehouse issue, but a "all programs that talk to older SQL Server" problem. 

There is a workaround here;  https://learn.microsoft.com/en-us/answers/questions/1095561/windows-11-22h2-update-breaking-connections-to-leg

Please feel free to close this issue.
