### ISSUE TITLE
A11y_Azure Data Studio Nov2023_Security_New Login Preview_ScreenReader: Orca is announcing unnecessary extra information when the combo box list items are receiving orca focus.

### ISSUE THREAD

**Issue by Swati1700** [microsoft/azuredatastudio#25211]
### Actual Result:
Orca is announcing unnecessary extra information when the combo box list items are receiving orca focus. Orca is announcing whole dialog information while list items are getting focus. 

**Note: Similar issue is observed for all combo box list items throughout the application.**

### Expected Result:
Orca should only announce the list item name when it is receiving screen reader focus in "New Loging preview" dialog. 

### GitHub Tags:
#A11yTCS; #A11yMAS; #A11ySev2; #DesktopApp; #WCAG1.3.1; #Info and Relationships; #FTP; #SH_Azure Data Studio_Nov2023_Linux_Dec2023; #SQL Azure Data Studio; #Linux; #ORCA; #Element:ListItems; #Closed;

### Environment Details:
Application Name: Azure Data Studio
Azure data studio 1.47.0
Screen Reader: ORCA

### Repro Steps:

1. Launch the "Azure data studio". Make sure to enable "Preview" feature in settings.
2. Start screen reader ORCA.
3. TAB till "Server" and press enter to expand the tree.
4. TAB till "Security" and press enter.
5. TAB till "Login" and press enter.
6. TAB till any login and pressF10 to open context menu.
7. TAB till "New Login Preview" and press enter.
8. TAB till "Authentication" combo box and press enter.
9. TAB to any list item.
10. Observe the issue orca is announcing unnecessary extra information when the combo box list items are receiving orca focus.

### User Impact:
Screen Reader users will get information about the whole dialog again and again unnecessary.

### Attachment:
[25211 (2).zip](https://github.com/microsoft/azuredatastudio/files/13952109/25211.2.zip)

**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility or the Divisional Driver."**
[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-stfe%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458850501301&sdata=mxhokIKNMb22llsjXHLgU3XZibj1Qfx37rpY4PU2sfE%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Comment by corivera** [comment]
@Swati1700 We aren't setting any extra info on the authentication dropdown items, so it seems like this is an issue with Orca rather than ADS. Here's the accessibility insights data for those dropdown items:
![AuthDropdown](https://github.com/microsoft/azuredatastudio/assets/12820011/6713ef2f-f6cd-4043-8879-bbe75dac1fae)

Would we be able to close this issue as external? Neither Narrator nor NVDA show the same issue.

**Comment by Swati1700** [comment]
Verified the issue in the latest environment version 1.47.1. Issue does not repro hence closing the bug. please find the closing file for the reference. 
[25211_Closed.zip](https://github.com/microsoft/azuredatastudio/files/14208430/25211_Closed.zip)
