### ISSUE TITLE
Azure Data Studio Import Wizard not working with Mac OS

### ISSUE THREAD

**Issue by Katru83** [microsoft/azuredatastudio#25230]
Version: 1.47.1 (Universal)
Commit: b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e
Date: 2024-01-10T00:31:52.936Z
VS Code: 1.82.0
Electron: 25.8.4
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Darwin arm64 23.1.0
SQL Server Import: v1.6.0

Steps to Reproduce:

1. Make the connection to DB
2. right click "Import Wizard"

Wizard is not opening even thought it tries to open it. 
I also updated data studio to be the latest version, but it didn´t help.

![Screenshot 2024-01-22 at 15 23 36](https://github.com/microsoft/azuredatastudio/assets/157379652/36a5c7c8-9fe4-4878-855d-413428b05539)

Does this issue occur when all extensions are disabled?: Yes/No    <-- The issue is related with extension.

**Comment by cheenamalhotra** [comment]
@Katru83 

Please try installing Rosetta, as mentioned in docs: https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=macOS-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall#tabpanel_1_macOS-install

```
/usr/sbin/softwareupdate --install-rosetta --agree-to-license
```

**Comment by Katru83** [comment]
Thanks! 

That helped!

**Comment by cheenamalhotra** [comment]
Closing as resolved.
