### ISSUE TITLE
Icon reuse in modelview is inefficient.

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2524]
In componentWithIconBase we're creating a new CSS rule for every single instance of a button or other component, even if they share the same iconPath. A more efficient way would be to:
- Have a map of icon paths to CSS rules
- On defining a component with an icon path, add it to the map
- If you're adding a button and that icon was already added, reuse the CSS rule.

We'd need to handle cleanup of the CSS rules in this case since we're currently wiping out the rule on ngDestroy. This can't be done for shared icons so we'd have to either ref count or do something else.

**Comment by kburtram** [comment]
Closing out older issues. Please reactive if this is impacting an extension under active development.
