### ISSUE TITLE
Restoring database shows task as succeeded immediately after closing the dialog

### ISSUE THREAD

**Issue by barbaravaldez** [microsoft/azuredatastudio#25250]
When restoring database, the console will say that the task succeeded immediately after closing the dialog but then throws an error  if the tasks fails shortly afterwards.

![image](https://github.com/microsoft/azuredatastudio/assets/34872381/90d49686-875d-4595-a175-7d0a74ae415a)

**Comment by corivera** [comment]
This might be a combination of the admin dialog starting its own task and STS doing the same.

**Comment by corivera** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/commit/4269fe0b532deec30042a86d1e4cd02d2d2cd34a
