### ISSUE TITLE
query does not retrieve data 

### ISSUE THREAD

**Issue by irvingesp** [microsoft/azuredatastudio#25276]
Type: <b>Bug</b>

When I query a table dows not show me information, but when I run the same query from sql server if exist data and give me information. 

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1270P (16 x 2496)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.67GB (12.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.6.0
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-assessment|Mic|0.6.4
azdata-sanddance|msr|4.1.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by irvingesp** [comment]
The error occurs when a text column data start with '#' symbol.

**Comment by cheenamalhotra** [comment]
Hi @irvingesp 

Could you please try with the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and confirm if that resolves the issue? I suspect this might be related to the XML datatype detection fixes we made.

**Comment by irvingesp** [comment]
> Hi @irvingesp
> 
> Could you please try with the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) and confirm if that resolves the issue? I suspect this might be related to the XML datatype detection fixes we made.

Hello I just check and it's working now, thanks for the fix

**Comment by cheenamalhotra** [comment]
The fix is checked into main and will be available in the next release, closing as resolved.
