### ISSUE TITLE
Data-Studio not downloadable

### ISSUE THREAD

**Issue by MWurzinger** [microsoft/azuredatastudio#25288]
- Azure Data Studio Version: All
- OS Version: All

Steps to Reproduce:

1. Go to https://learn.microsoft.com/de-de/azure-data-studio/download-azure-data-studio
2. Scroll down
3. Click to download the files ( all links are broken )
4. Browser shows HTTP-500 Error "Internal Server Error"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ser789654** [comment]
Please fix this asap, I need it today!!!!

**Comment by 57ud3n7c0d3r** [comment]
Same here, please fix.
**https://azuredatastudio-update.azurewebsites.net/  is down.**
Internal server error.
Links to current and previous releases are not working

**Comment by sofusskovgaard** [comment]
I can confirm this issue is still present.

**Comment by OliverRagu** [comment]
Still present

**Comment by BenWillet** [comment]
are there any alternative mirrors to download from?

**Comment by sofusskovgaard** [comment]
> are there any alternative mirrors to download from?

I haven't found any, sadly. They should be provided in the releases here on github imho.

**Comment by DanikingRD** [comment]
https://azuredatastudio-update.azurewebsites.net/ is still down.

**Comment by d4r1us-drk** [comment]
Microsoft Store seems also down, maybe related to this
![image](https://github.com/microsoft/azuredatastudio/assets/131416536/051f95fe-d605-46de-881e-4e365d413947)

**Comment by AlexeyLoychenko** [comment]
**winget install "azure data studio"** worked perfectly for me

**Comment by jakvelIngraphic** [comment]
> **winget install "azure data studio"** worked perfectly for me

Thank you! This worked for me as well!

**Comment by atericcruz** [comment]
chocolatey also works: 
choco install azure-data-studio -y

Hear is the URL chocolatey used and works:
https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-setup-1.47.1.exe

**Comment by usf-jradwan** [comment]
winget didn't work for me:

```
Failed in attempting to update the source: winget
Failed when searching source: winget
An unexpected error occurred while executing the command:
0x8a15000f : Data required by the source is missing
```

But chocolately did, thanks @atericcruz!

**Comment by lennyankireddi** [comment]
Trying to install through homebrew on macOS didn't work either.

<img width="948" alt="image" src="https://github.com/microsoft/azuredatastudio/assets/2095906/2d723bbd-974d-4a2b-ba30-9fa1e948eb55">

Looks like the download source is kaput.

**Comment by Charles-Gagnon** [comment]
Hey everyone, apologies for the issues. We're investigating and hope to have the links working again shortly! In the meantime here's the direct download links you can use : 

|Platform |Type             |Download |
| --------|-----------------|----------------------- |
|Windows  |User Installer   |[64 bit][win-user]&emsp;[ARM][win-user-arm64] |
|         |System Installer |[64 bit][win-system]&emsp;[ARM][win-system-arm64] |
|         |.zip             |[64 bit][win-zip]&emsp;[ARM][win-zip-arm64] |
|Linux    |.tar.gz          |[64 bit][linux-zip] |
|         |.deb             |[64 bit][linux-deb] |
|         |.rpm             |[64 bit][linux-rpm] |
|Mac      |.zip             |[Universal][osx-universal]&emsp;[Intel Chip][osx-zip]&emsp;[Apple Silicon][osx-arm64] |

[win-user]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-user-setup-1.47.1.exe
[win-system]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-setup-1.47.1.exe
[win-zip]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-1.47.1.zip
[win-user-arm64]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-arm64-user-setup-1.47.1.exe
[win-system-arm64]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-arm64-setup-1.47.1.exe
[win-zip-arm64]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-windows-arm64-1.47.1.zip
[linux-zip]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-linux-1.47.1.tar.gz
[linux-deb]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-linux-1.47.1.deb
[linux-rpm]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-linux-1.47.1.rpm
[osx-universal]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-macos-universal-1.47.1.zip
[osx-zip]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-macos-1.47.1.zip
[osx-arm64]: https://sqlopsbuilds.azureedge.net/stable/b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e/azuredatastudio-macos-arm64-1.47.1.zip

**Comment by Charles-Gagnon** [comment]
The links should be working again, sorry for the interruption! Let us know if anyone sees any further issues.
