### ISSUE TITLE
Missing Rows

### ISSUE THREAD

**Issue by kjyounkin** [microsoft/azuredatastudio#25314]
Type: <b>Bug</b>

Selecting from data source sometimes results in showing rows affected but they are not rendered in results grid. If I run the same query in SSMS, it will show all results.
![image](https://github.com/microsoft/azuredatastudio/assets/153095751/42c6df21-53e0-46dc-a1cd-83a68d3e8752)

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-10850H CPU @ 2.70GHz (12 x 2712)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.71GB (11.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-oracle|Mic|0.1.6
net-6-runtime|Mic|1.1.0

</details>

**Comment by kisantia** [comment]
@kjyounkin can you try the [1.46.1](https://github.com/microsoft/azuredatastudio/releases/tag/1.46.1) release to see if this was a regression introduced in 1.47.1?

**Comment by cheenamalhotra** [comment]
Or try the [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch) - as it might be already fixed if your data has XML/HTML content.

**Comment by cheenamalhotra** [comment]
We haven't heard from you, and many other customers have reported the latest insiders build fixes the issue, so we'll proceed to close this issue. If you encounter it again in future releases, let us know.
