### ISSUE TITLE
ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by ievsantillan** [microsoft/azuredatastudio#25327]
- Azure Data Studio Version: 1.47.1 (system setup)
- OS Version: Windows 11, 23HS (OS Build 22631.3007)

Steps to Reproduce:

1. Open Python notebook
2. Configure Python Runtime
3. Install Dependencies
   - Installing Notebook dependencies failed with error: Process exited with error code: 1. StdErr Output: error: subprocess-exited-with-error
   - Building wheel for pyzmq (pyproject.toml) did not run successfully.
exit code: 1
   - error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Tools\\MSVC\\14.39.33519\\bin\\HostX86\\x64\\cl.exe' failed with exit code 2
[end of output]
   - ERROR: Failed building wheel for pyzmq
   - ERROR: Could not build wheels for pyzmq, which is required to install pyproject.toml-based projects
      - note: This error originates from a subprocess, and is likely not a problem with pip.

Does this issue occur when all extensions are disabled?: Yes/No
- yes

**Comment by nixiPython80** [comment]
Hello Ievsantillan
Did you find a solution?

I have the same problem

Thanks in advance

**Comment by JohnSweeney85** [comment]
Having same problem here.  Assumed it was because of Python 3.13 ....anyone find a fix yet ?

**Comment by ievsantillan** [comment]
> Hello Ievsantillan
> Did you find a solution?
> 
> I have the same problem
> 
> Thanks in advance

No, unfortunately not. Still experiencing the issue.

**Comment by ievsantillan** [comment]
> Having same problem here. Assumed it was because of Python 3.13 ....anyone find a fix yet ?

on 3.12.2 here

**Comment by ievsantillan** [comment]
Thanks for that previous comment, @JohnSweeney85!

I reverted back to **3.11.8** and was able to get the notebooks back into a working state! Issue appears to be with latest >= 3.12.2

**Comment by Pookam90** [comment]
Having the same issue after i upgraded to 3.12.2 . @ievsantillan  tried what you did and it worked for me as well thank you so much!

**Comment by airhartm** [comment]
I have the same problem on Apple Silicon, with Python 3.12.5 in either a conda environment or the python.org installed version.

Reverting to 3.10.14 appears to have worked as a workaround.
