### ISSUE TITLE
Results pane is empty

### ISSUE THREAD

**Issue by vheijke** [microsoft/azuredatastudio#25339]
Type: <b>Bug</b>

Create a query. Press Run. 
It shows number of results correctly.
The Table grid is empty, scrollbars work and just scroll through a blank page.
Exporting results in proper data
![image](https://github.com/microsoft/azuredatastudio/assets/11017350/23870fc9-e6e3-4ad4-888d-db6a7f9cca41)

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.26058
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (23.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
Moving out to February milestone since fix is already merged, while we wait for confirmation.

**Comment by vheijke** [comment]
Hi Cheena,

Thanks for reaching out. I can confirm that the insiders build doesn't have this problem.
This is great!
[cid:f86cc933-06d0-4b7b-9aea-53dfae871c8c]

Regards Victor Heijke
________________________________

**Comment by cheenamalhotra** [comment]
Closing as resolved, fix will be available in stable build soon.
