### ISSUE TITLE
Unable to connect to sql server on Azure

### ISSUE THREAD

**Issue by easinus** [microsoft/azuredatastudio#25342]
Type: <b>Bug</b>

After recent software update I am not able to connect to Sql Server database on Azure from Azure Data Studio. The program detects my subscription and server (including the database, but when I attempt to connect using Entra ID, I get an "Invalid request. Request is malformed or invalid" message. The request is generated by the program itself when I browse to my database.

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|39.69GB (27.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azcli|Mic|1.8.0

</details>

**Comment by easinus** [comment]
Clearing token cache and saved accounts solved the problem. :)

**Comment by cheenamalhotra** [comment]
Thanks for confirming, closing as resolved.
