### ISSUE TITLE
STS version update to release branch 1.48

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#25361]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Update STS version in Release branch to 4.11.0.22
2. This includes the below code merges.
![image](https://github.com/microsoft/azuredatastudio/assets/74571829/f26d68f8-c4b8-42ab-b239-a16f1339873d)
3. From DacFx, we get to see the latest functionalities such as parquet support (+SQL Server, SQLMI, SQLDB), net8, online index 

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@ssreerama can you please add more details on what this STS update brings (ex: it's to update the DacFx and SqlProjects nuget versions)

**Comment by ssreerama** [comment]
@cheenamalhotra , I don't see any commit related to the #25364 issue in STS. I have added the screen shot of version comparison and the items that comes from DacFx in the description.
