### ISSUE TITLE
Can't open notebook folder when a book is open in the notebooks viewlet

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#25369]
This error gets thrown when clicking the "Open Notebooks in Folder" button after opening a Book in the viewlet:
`Error running command notebook.command.openNotebookFolder: e.replace is not a function. This is likely caused by the extension that contributes notebook.command.openNotebookFolder.`

**Comment by kisantia** [comment]
I also ran into this when going through another test case. Interesting that running the "Open Notebooks in Folder" command from the command prompt works when the viewlet toolbar button doesn't.

**Comment by corivera** [comment]
The toolbar button has some context for the viewlet itself I think, which is why it gets passed a BookTreeItem as an argument in that case
