### ISSUE TITLE
Failed to start Migration Service

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#25364]
- Azure Data Studio Version: 1.48-rc1
- OS Version: Windows 11 (User)
- SQL Migration Extension version: 1.5.3

Steps to Reproduce:

1. Connect to any on-premise SQL server that loads Migration extension
2. Notice error when extension is loaded:

```
Failed to load System.Private.CoreLib.dll (error code 0x80131018)
Path: c:\Users\~\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.5.3\migrationService\Windows\4.11.0.17\System.Private.CoreLib.dll
Error message: Could not load file or assembly 'c:\Users\~\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.5.3\migrationService\Windows\4.11.0.17\System.Private.CoreLib.dll'. The module was expected to contain an assembly manifest. (0x80131018)
Failed to create CoreCLR, HRESULT: 0x80131018
[Error - 5:34:18 AM] Connection to server got closed. Server will not be restarted.
```

More info:
- No proxy is configured in environment.
- Error is permanent and not intermittent.

**Comment by kisantia** [comment]
I wasn't able to repro this on my windows machine when connecting to my docker container.  The migration service was installed and shows as the extension starting up: 
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/1c67181b-d7c5-4230-a0b6-094e96f352c8)
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/cbff005b-e96c-4979-a509-1776064b8a91).

Does this still repro if you uninstall the extension and delete the `c:\Users\~\.azuredatastudio-rc1\extensions\microsoft.sql-migration-1.5.3\` folder?

**Comment by cheenamalhotra** [comment]
If I delete the folder and reinstall extension, the issue is resolved.
Closing as no-op.
