### ISSUE TITLE
Remove the drop database icon from the connection browser menu

### ISSUE THREAD

**Issue by jsteinbergTCALLC** [microsoft/azuredatastudio#25366]
Type: <b>Feature Request</b>

I cannot understand why in the world that anyone would need a "Drop Database" Menu Icon in the database explorer. I did not know it was even there, until I accidentally clicked on it in a production database. Of course, it did give me a confirmation page, but that is only another small misclick away from disaster.
I have been developing database driven apps for over 25 years, and I probably dropped a database less than 10 times, and I think you will find that most developers have similar experience. 
The convenience of having a Drop button is immeasurably outweighed by the possible harm that this could cause. 

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by dthompsonwork** [comment]
I just unintentionally did the same thing.  Dangerous.
