### ISSUE TITLE
Error when doing dac operations on dacpac extension 

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#25375]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. Open then Dacpac extension
2. Try extract/deploy a dacpac
3. Error is thrown fore System.IO.Packaging not found for version 8.0.0
4. Error: Extract project files: Could not load file or assembly 'System.IO.Packaging, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
@ssreerama please go ahead and close this after verifying this is now fixed in the latest RC build

**Comment by ssreerama** [comment]
Verified with latest RC build and working as expected!!
