### ISSUE TITLE
Trust Server Cert dropdown not hidden for Strict Encryption

### ISSUE THREAD

**Issue by cheenamalhotra** [microsoft/azuredatastudio#25378]
- Azure Data Studio Version: 1.48.0-rc1, Insiders
- OS Version: Windows 11

Selecting Strict encryption should hide the Trust Server Certificate control as it does until 1.47.1

![Screenshot 2024-02-22 at 8 07 23 PM](https://github.com/microsoft/azuredatastudio/assets/13396919/18e0c008-584e-4071-9a65-f0a924d56113)

**Comment by kisantia** [comment]
probably related to this change I made https://github.com/microsoft/azuredatastudio/pull/25311

**Comment by kisantia** [comment]
Validated this is now fixed in the latest RC build
