### ISSUE TITLE
Telemetry opt out notification has wrong text (says opt in)

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#25371]
RC1

1. Clear/delete settings (%APPDATA%/azuredatastudio)
2. Start up RC1
3. This notification prompt is shown

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/04380280-9ba4-40fa-b323-d02a97f37961)

But that's incorrect - it should be saying "Opt Out" since telemetry is currently enabled.

This appears to be a regression from 1.47.1

**Comment by Charles-Gagnon** [comment]
@kisantia FYI, this is probably worth looking at so users aren't confused (assuming we aren't collecting telemetry when we actually are)

**Comment by Charles-Gagnon** [comment]
Nevermind, forgot that RC1 has telemetry disabled in product.json by default. I'm going to go change that since there isn't a reason we should have that disabled...

**Comment by kisantia** [comment]
ohhh is that why I wasn't seeing "Telemetry" as an option in the Tasks pane in the RC build, but see it in Stable? I was about to ask you about that

**Comment by kisantia** [comment]
yup meant output pane and yes I had set the log level to Trace
