### ISSUE TITLE
Import Wizard Ctrl + I does not work

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#2537]
- SQL Operations Studio Version: 0.33.3

Steps to Reproduce:

1. Make a connection to server
2. Press Ctrl+I to launch wizard
3. nothing appears, even though command persists in keyboard shortcuts.

This is a key demo blocker as it prevents the wizard from being used by any cloud SQL db.

**Comment by julielerman** [comment]
ahh, should have looked here before trying over & over LOL

**Comment by timetatime06** [comment]
Hi
