### ISSUE TITLE
STS Vbump required with the DacFx issue fix

### ISSUE THREAD

**Issue by ssreerama** [microsoft/azuredatastudio#25397]
- Azure Data Studio Version:
- OS Version:

Steps to Reproduce:

1. dacpac/sc/sql-db-projects are failing to load few dlls due to changes happened in DacFx for net8.0 support 
2. fix has been implemented in DacFx and updated in STS.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by ssreerama** [comment]
#25373 #25375 are the issues that mentioned in the description

**Comment by kisantia** [comment]
closing since this was merged
