### ISSUE TITLE
Results Rows Not Showing

### ISSUE THREAD

**Issue by brianjaikens** [microsoft/azuredatastudio#25392]
Type: <b>Bug</b>

Selecting a basic set of rows from a table (any table).
Grid flashes in the results pane. Then goes blank.
Same sql run in SQL Server Management Studio results expected results.

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.80GB (14.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1

</details>

**Comment by brianjaikens** [comment]
Tried an already open sql statement again. That then showed the results. Went to the tab with the problem. Ran the sql in that again. The results then showed. So it looks like a temp issue. Which can be worked around. But I will from now on have to double check every sql that doesn't return any rows. :-(

**Comment by cheenamalhotra** [comment]
Is this issue also reproducible with [latest insiders build](https://github.com/microsoft/azuredatastudio?tab=readme-ov-file#try-out-the-latest-insiders-build-from-main-branch)? Can you please try and confirm?

**Comment by mhenry-cb** [comment]
I'm experiencing the same issue (#25398) with the stable release (as of 1.47.1).

I just tried the insiders build and so far I'm not seeing the issue in the insiders build. So far the rows are showing up as expected in the insiders build.

Version: 1.49.0-insider
Commit: c511fdb40754b6c617f53632e5c17a4785e2390c
Date: 2024-02-23T06:42:48.118Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.19045

**Comment by cheenamalhotra** [comment]
Closing as issue is expected to be resolved with the latest insiders and upcoming release, as also confirmed above.
