### ISSUE TITLE
Temporary results files not cleaned up when same batch is run multiple times using GO 'n'

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2541]
- SQL Operations Studio Version:
Version 0.33.2
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.7
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:
1. run the following batch:
```
SELECT * FROM [master].[sys].[all_objects] o1 , [master].[sys].[all_objects] o2 
GO 100000
```

Expected: All executions go through correctly.
Observed: After about 2.5 hours we run out of 500 GB of space on ssd c: drive and get the following message:
Query failed: There is not enough space on the disk : 'C:\Users\arvran\AppData\Local\Temp\tmpE520.tmp'
Total execution time: 02:29:42.376

**Comment by anthonydresser** [comment]
Our front end doesn't keep the results in memory, instead it only keeps a window and instead makes requests to our out-of-proc service to get the rows when it needs to show them. This means the service needs to keep the files around until the editor is disposed in order to respond to the front end.

**Comment by ranasaria** [comment]
Yeah, I now, but I think we should scope the disposing off the files to batch exit instead of editor exit if possible.

Also in my cases may be because the execution of the batches ended with the out of disk error, the file did not get cleaned out even after ops studio exit.

-  Arvind.

________________________________

**Comment by anthonydresser** [comment]
I guess I'm not sure what you mean by `batch exit`, although it not cleaning up after closing the editor certainly is a pretty large bug.

**Comment by ranasaria** [comment]
Karl tested it and in his repro it did cleanup after normal exit. We will need to check exiting after some error conditions though.

For my scenario, since I am running GO ‘n’ the execution is creating multiple files, one per execution of ‘GO’. So when 2nd time the results are getting pulled the first round has already been displayed to the user and can get cleaned out.


-  Arvind.

________________________________

**Comment by kevcunnane** [comment]
Just to chime in, each batch has 1 or more resultsets and needs to persist while the file is open / the query is re-run. This is because as Anthony mentioned you can just scroll up to that resultset in the UI and it'll start querying for the data from the backend. Agree that having a stronger "clean up on error" would be good.

**Comment by kburtram** [comment]
Closing older issues from our internal testing.  We can reinvestigate this scenario in current test runs.
