### ISSUE TITLE
Accessibility bug - Description of text component is announced as image

### ISSUE THREAD

**Issue by bharathpalaksha** [microsoft/azuredatastudio#25441]
- ADO issue link - [A11y_Azure Cosmos DB Migration for MongoDB_New migration button_ Select or create Azure data base Migration service _Voice over: Voice over is announcing image to the tooltip present in front of "Migration name " and "Migration mode" ](https://msdata.visualstudio.com/CosmosDB/_workitems/edit/2830384)
- Application Name: Azure Data Studio extension (Azure Cosmos DB for MongoDB migration)
- MAC Version: Ventura 14.1.1
- Azure data studio version: 1.47.0
- Azure cosmos DB migration for Mongo DB Version: V2.0.1(Preview)
- Screen reader: Voice over 

This accessibility bug is on the extension but we use Azure data studio components, description of the text component is being announced as image

https://github.com/microsoft/azuredatastudio/assets/342603/fa274d29-f2a2-4b99-b513-96adbc2ee60a

Steps to Reproduce:

1. Open Azure data studio application.
2. Tab to Extensions.
3. Serach for Azure cosmos DB migration for MongoDB extension and install.
4. Tab to connections and click on new connection.
5. Select mongo account login with valid credentials.
6. Right click on the connection and click on manage.
7. Tab to azure cosmos DB migration.
8. Tab to Dash board tab.
9. Tab to New migration button .
10. Tab to Run a new assessment of your MongoDB server .
11. Fill all the details.
12. Tab to run validation and run the validation.
13. Succuss message will appear .
14. Tab to start assessment button.
15. View assessment results and select database (s) for migration will appear .
16. Tab to data base and select any data base .
17. Specify Azure cosmos DB for mongoDB target Account will appear .
18. Fill all the details and click next button.
19. Migration mapping screen will appear and fill all details and press enter.
20. Select or create Azure data base Migration service will appear .
21. Verify Voice over is announcing image to the tooltip present in front of "Migration name " and "Migration mode"

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kisantia** [comment]
this was fixed in https://github.com/microsoft/azuredatastudio/pull/24898 and included in the latest version of ADS. Please make sure the tester is using ADS 1.48.
