### ISSUE TITLE
Japanese translation of restore dialog is incorrect.

### ISSUE THREAD

**Issue by nobtak4035319** [microsoft/azuredatastudio#25451]
![Restore Dialog with EN](https://github.com/microsoft/azuredatastudio/assets/161723260/3d45f09b-2029-429f-99ad-2383ba19d23b)
![Restore Dialog with JA](https://github.com/microsoft/azuredatastudio/assets/161723260/165adca9-8a4c-4a34-aa35-22cdd2d81360)
Type: <b>Bug</b>

- Azure Data Studio Version: 1.48
- OS Version: Win10 Pro 22H2

Steps to Reproduce:

1. Install the Japanese Language Package for Azure Data Studio v1.48.0 extension in Azure Data Studio.
2. Display Database Restore Dialog.

'Options' translates as 'files' 

Extension version: 1.48.0
Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

**Comment by smartguest** [comment]
Issue has been fixed in the latest language resource update on the internal side. The fix will be included on the next langpack release once it is created.

**Comment by smartguest** [comment]
Was fixed here: https://github.com/microsoft/azuredatastudio/pull/25475/files Id for "Files" was shared with "Options"
