### ISSUE TITLE
After the sql is executed, the result window that appears cannot be hidden.

### ISSUE THREAD

**Issue by TomCatHe** [microsoft/azuredatastudio#25529]
Type: <b>Bug</b>

After the sql is executed, the result window that appears cannot be hidden.

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-26T20:59:27.181Z)
OS version: Darwin x64 23.4.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hans|Mic|1.48.0

</details>

**Comment by rmwin** [comment]
Just wondering if you'd searched through the keyboard shortcuts [ctrl]+[k] [ctrl]+[s] and then searched for "Toggle Query Results". You should be able to assign a shortcut to that shortcut and use that to show/hide the results pane. Works for me at least v 1.47.1, and worked in several previous versions too.

**Comment by corivera** [comment]
You can also use Toggle Query Results from Command Prompt if you don't want to rebind the keyboard shortcut.

**Comment by corivera** [comment]
Closing this since the functionality is already provided via Toggle Query Results.

**Comment by TomCatHe** [comment]
Solved, thank you very much
