### ISSUE TITLE
Cannot read properties of undefined (reading 'documents')

### ISSUE THREAD

**Issue by JoeFieck** [microsoft/azuredatastudio#25522]
Type: <b>Bug</b>

Upgrade ADS to 1.48.0
Install the Azure Cosmos DB extension.
Make a connection to Azure Cosmos DB using a connection string.
Notice that the UI correctly shows the same list of containers showing from Data Explore from withing Azure directly.

Open a query and run:
select * from c 

You may see a message saying:
Cannot read properties of undefined (reading 'documents')

No data is returned.  

What is interesting is that on the bug fix list for 1.48 it shows having fixed an issue with :
Connections	Fixed Error: “Cannot read properties of undefined (reading 'serverInfo')”

This message here is the same except for it shows 'serverInfo' where mine shows 'documents' 

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.22621
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.73GB (6.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azure-cosmosdb-ads-extension|Mic|0.4.2
azuredatastudio-postgresql|Mic|0.6.0
dacpac|Mic|1.14.0
import|Mic|1.6.1
net-6-runtime|Mic|1.1.0
profiler|Mic|0.14.0

</details>

**Comment by JoeFieck** [comment]
![error](https://github.com/microsoft/azuredatastudio/assets/148320389/b9d2b35b-9b47-4b14-8733-51b457c59046)

**Comment by JoeFieck** [comment]
Hi there.  Have we confirmed this is a bug?  Looks like maybe a regression to another bug fixed in 1.48.0 with Connections Fixed Error: “Cannot read properties of undefined (reading '**serverInfo**')”

**Comment by JoeFieck** [comment]
I ask because I still see nobody assigned.  It would be great to be able to use ADS to manage both SQL and Cosmos systems in the same client app but not possible until this gets corrected.  Maybe we can do some type of Dev to Dev build or something?

**Comment by JoeFieck** [comment]
Is this a bug?

**Comment by cheenamalhotra** [comment]
Please open issue in the https://github.com/Azure/azure-cosmosdb-ads-extension repository to get support from the respective extension team.
