### ISSUE TITLE
NULL = NULL in 1.47.1

### ISSUE THREAD

**Issue by Hattoff** [microsoft/azuredatastudio#25526]
- Azure Data Studio Version: 1.47.1
- OS Version: Windows_NT x64 10.0.19045

Steps to Reproduce:

1. Run the following query in ADS. It is a simple case statement that returns 'passed' if null = null evaluates to true and and 'failed' if it evaluates to false. I expect to get 'failed' but instead I get 'passed' :
`select
    case 
        when null = null then 'passed'
        else 'failed'
end`

2. The NULL value shouldn't equal anything, including itself. Null equivalence should be handled by the `is null` and `is not null` operators. I have colleagues who run version 1.47.0 of ADS and who get the opposite result, e.g. they see 'failed' when they run the query. This is a problem because now we are running queries on different logic, which can produce inconsistencies. I rely on the behavior of null values for a lot of my queries and procedures and to have that change puts into doubt most everything I've written.

Does this issue occur when all extensions are disabled?: Yes

**Comment by cheenamalhotra** [comment]
The query is executed on the SQL Server you're connected to, and not by ADS, please provide your feedback to the SQL Server team. More info: https://learn.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver16

**Comment by Hattoff** [comment]
![image](https://github.com/microsoft/azuredatastudio/assets/18622607/8d073baf-f817-44ae-a2ce-37bf346f49df)


> The query is executed on the SQL Server you're connected to, and not by ADS, please provide your feedback to the SQL Server team. More info: https://learn.microsoft.com/en-us/sql/sql-server/sql-server-get-help?view=sql-server-ver16

**Comment by Charles-Gagnon** [comment]
This is likely because of the ANSI_NULLS setting

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/88a1b9a6-ff6d-461f-bef9-b9910eae9660)

By default SSMS and ADS both have them on : 

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/67ccb400-16a4-4593-b826-98b2c07c66c7)

![image](https://github.com/microsoft/azuredatastudio/assets/28519865/0858e999-8808-495a-8edd-04e03aaf4aad)

Do you perhaps have different settings in your tools @Hattoff ?

**Comment by Hattoff** [comment]
> This is likely because of the ANSI_NULLS setting
> 
> ![image](https://private-user-images.githubusercontent.com/28519865/317012416-88a1b9a6-ff6d-461f-bef9-b9910eae9660.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODE2MjUsIm5iZiI6MTcxMTQ4MTMyNSwicGF0aCI6Ii8yODUxOTg2NS8zMTcwMTI0MTYtODhhMWI5YTYtZmY2ZC00NjFmLWJlZjktYjk5MTBlYWU5NjYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExMWZkYjFjNGI4Y2MxOWY5ODI3MGUyOWUzZGQwNTU4OWFkOWE2ODVjMDU1NTEwZDJhMGZmYzE0ZjQzMmNmMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jkO5GfNXk-OdIQ8uYgGCzJE8J8vhYKuo6HMjMNX3qJk)
> 
> By default SSMS and ADS both have them on :
> 
> ![image](https://private-user-images.githubusercontent.com/28519865/317008124-67ccb400-16a4-4593-b826-98b2c07c66c7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODE2MjUsIm5iZiI6MTcxMTQ4MTMyNSwicGF0aCI6Ii8yODUxOTg2NS8zMTcwMDgxMjQtNjdjY2I0MDAtMTZhNC00NTkzLWI4MjYtOThiMmMwN2M2NmM3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIyMjM2ZTBjYmYxOGYzOWNhY2JiYWQ4YTRjZGU0MGUxNjU3YWZjZTcyZGQ1ZGI5NTA4ODAzNDE1OTdiNDFhMGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z7ucA-vj0QI8rksPDn9okVaHIbgOrZuVFDYO0yS2JBM)
> 
> ![image](https://private-user-images.githubusercontent.com/28519865/317012236-0858e999-8808-495a-8edd-04e03aaf4aad.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0ODE2MjUsIm5iZiI6MTcxMTQ4MTMyNSwicGF0aCI6Ii8yODUxOTg2NS8zMTcwMTIyMzYtMDg1OGU5OTktODgwOC00OTVhLThlZGQtMDRlMDNhYWY0YWFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE5Mjg0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZWYxOWExODFhY2JiZjY3OTQ2ODM2ZDliOTRlMmU0NzhjZTc1ZjhjZjdjZDdjMDM0YmEwMTAzMTc5MmI5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OjPF5juNPXOQ5ZxkJsiLLtn90gk4zxwpEfITKKiAF9g)
> 
> Do you perhaps have different settings in your tools @Hattoff ?

Yes! Thank you. That was the issue. I do not know why or how that got disabled but that was the problem. Thank you so much for the help!
