### ISSUE TITLE
Auto-complete annoyance

### ISSUE THREAD

**Issue by ghost** [microsoft/azuredatastudio#2556]
If I try and type the following

```
select * 
from Table1 t1 
join Table2 t2 on t1.Id = t2.Table1Id 
```

When I type the alias t1 for Table1, the autocomplete list includes an entry "Table1" which is selected so as soon as I hit enter t1 is replaced with Table1 leaving

```
select * 
from Table1 Table1
```

It should recognise the t1 is an alias and not try and autocomplete

**Comment by kburtram** [comment]
I don't see Table1 in the autocomplete list when typing the above snippet on the latest build.  Please let us know if this issue is still impacting you.

![image](https://user-images.githubusercontent.com/599935/129619088-02d4b1af-934d-4109-b194-9becbdaeff94.png)
