### ISSUE TITLE
Don't ask to save scripted not-changed files

### ISSUE THREAD

**Issue by rojepp** [microsoft/azuredatastudio#2562]
Issue Type: <b>Feature Request</b>

When I create an editor by generating a script from an Sql server object, It would be nice if that editor tracked that I haven't changed what was scripted, and doesn't ask me if I want to save the file when closing the editor or the app.

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment]
File generated with SCRIPT commands that aren't changed should no longer prompt to be saved.  Please let us know if you're still impacted by this issue.  Thanks!
