### ISSUE TITLE
Mac and Linux downloads returning Internal Server Error

### ISSUE THREAD

**Issue by jlclemmons** [microsoft/azuredatastudio#25624]
Type: <b>Bug</b>

Navigate to https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?view=sql-server-ver16&tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall

Select any Linux download option, or the Mac Universal or Intel options.

You are redirected to an Internal Error page instead of getting the download.

![image](https://github.com/microsoft/azuredatastudio/assets/163581740/6aa7f8c2-089e-45e3-ab9f-ff2be6d05331)

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|12th Gen Intel(R) Core(TM) i7-1265U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.44GB (14.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by corivera** [comment]
Looking into it.

**Comment by corivera** [comment]
We've updated the download links, so they should work now.
