### ISSUE TITLE
Clicking on a new row in Edit Data doesn't put the cursor in the new cell it creates

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2563]
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Open edit data for a table
2. Click on the last row to create a new row

Expected behavior: The cursor starts in the cell of the newly created row that you clicked on so that you can immediately type the new content
Actual behavior: You need to click again in the new row to start editing

This also repros if you create the new row by tabbing or pressing enter from the row above

**Comment by smartguest** [comment]
Closing as issue no longer reproduces on the latest build
