### ISSUE TITLE
Azure Data Studio infinitly proposes updates even after it was updated

### ISSUE THREAD

**Issue by Yevhen-Myroshnychenko** [microsoft/azuredatastudio#25637]
Type: <b>Bug</b>

I installed Azure Data Studio updates, but in a few minutes later I see  Azure Data Studio message that proposes updates to me. This loop process is infinit.  

Azure Data Studio version: azuredatastudio 1.45.1 (88c21b1725a3e79440027bdb7b5a55fb036be0e2, 2023-08-03T00:42:56.773Z)
OS version: Darwin arm64 23.4.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|4, 5, 5|
|Memory (System)|64.00GB (0.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.128.504

</details>

**Comment by Charles-Gagnon** [comment]
Could you try downloading the latest version (1.48) directly from the links on this page?

https://github.com/Microsoft/azuredatastudio?tab=readme-ov-file#download-the-latest-azure-data-studio-release

**Comment by kburtram** [comment]
Closing based on the previous comment.  Please try to manually update to the latest build.
