### ISSUE TITLE
copying to clipboard

### ISSUE THREAD

**Issue by tim-dutemple** [microsoft/azuredatastudio#25632]
Type: <b>Bug</b>

takes forever.  what in the world.

Azure Data Studio version: azuredatastudio 1.47.1 (b6f7beb01f92adaa4b79b6b6f3ac704e95cafe6e, 2024-01-10T02:15:02.628Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

**Comment by xavierlaffargue-radiocanada-cbc** [comment]
Thanks! Same here!

**Comment by kburtram** [comment]
@lewis-sanchez this is a good issue to looking into.  I think we're currently copying to clipboard from the UI process, which requires streaming the entire result set over an IPC channel between processes, which can take a long time.  I'd like to copy the results directly to the clipboard from STS process when running on a single machine, and only use the redirect through the UI process when using a remove host for the STS process where it cannot access the interactive user's OS clipboard.
