### ISSUE TITLE
Clicking New Connection produces an error: Cannot read properties of null (reading 'fullName')

### ISSUE THREAD

**Issue by sivan-koren** [microsoft/azuredatastudio#25648]
Type: <b>Bug</b>

1. Open connections in the sidebar.
2. Click New Connection.

An error appears in the lower right corner of the screen: Cannot read properties of null (reading 'fullName')

I believe this may be related to deleting server groups. Possibly when deleting all servers in a server group, but I'm not able to reproduce it since I can no longer add connections.

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900 12-Core Processor              (24 x 2994)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (20.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
dacpac|Mic|1.14.0
import|Mic|1.6.1
powershell|ms-|2022.12.1
profiler|Mic|0.14.0
query-history|Mic|0.5.3
sql-assessment|Mic|0.6.4
azdata-sanddance|msr|4.1.1
code-settings-sync|Sha|3.4.3

</details>

**Comment by sivan-koren** [comment]
I resolved this by creating a new group, and then dragging the existing connections into that group. Then I deleted the group and restarted ADS.

That said, I don't know if someone who had no connections available would have a path to resolution. And either way, the behavior is surely not expected.

**Comment by lewis-sanchez** [comment]
Hi @sivan-koren, have you been able to see this issue reoccur? I attempted to get the error to occur but wasn't able to see it for myself.

If you're able to get the issue to reoccur could you attach console and/or application logs to help with correcting this?

**Comment by sivan-koren** [comment]
Currently unable to reproduce in the most recent version.
