### ISSUE TITLE
Result gets blank and database gets disconnected 

### ISSUE THREAD

**Issue by rvstrong** [microsoft/azuredatastudio#25644]
Type: <b>Bug</b>

Open Azure data studio stand alone exe file.
Connect to database.
Execute query multiple times.
When you execute more queries, many time it shows blank result as in screenshot and the database gets disconnectd. 
Only solution is to restart the Azure data studio.

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.69GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.4.2
azdata-sanddance|msr|4.1.1

</details>

<img width="960" alt="Picture2" src="https://github.com/microsoft/azuredatastudio/assets/169947542/8b642ea9-d05f-4d8f-8dc5-24d0910fe02b">

**Comment by Chewieez** [comment]
I think I've been experiencing this issue today on and off. The query will hang on "Executing Query" for a long time, out of the blue. I found I could fix it by reloading or quitting and reopening. But it is annoying for sure.

**Comment by lewis-sanchez** [comment]
Hi @Chewieez, I'm looking into this bug, but haven't been able to get it to occur. After using the `Developer: Reload Window` command or quitting and reopening, are you able to see the bug again?

**Comment by lewis-sanchez** [comment]
Hi @rvstrong, is this bug something you still run into while using Azure Data Studio? I haven't been able to get the bug to occur. Are you able to attach console or application logs to help me troubleshoot this?

**Comment by kburtram** [comment]
Closing based on lack of logs for further investigaiton.
