### ISSUE TITLE
Connection to database remains open.

### ISSUE THREAD

**Issue by akc42** [microsoft/azuredatastudio#25657]
Type: <b>Bug</b>

I do a lot of development work on a database called PAS_Live.  However as part of a backup script I drop the database before recreating it from a backup file created on the production system (another computer entirely).

Although the only tab open is the one with the backup script, and that is either totally disconnected or connected to the "Master" database a run sometimes fails because it cannot drop the database.

Opening a tab with the Master connection and running EXEC sp_who2 often shows a remaining connection to PAS_Live from Azdata (which I assume is Azure Data Studio).  I have to kill that connection for my backup to work

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-26T20:54:08.538Z)
OS version: Linux x64 6.1.0-21-amd64
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 9 5900HX with Radeon Graphics (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|1, 1, 1|
|Memory (System)|30.75GB (23.52GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|gnome|
|XDG_CURRENT_DESKTOP|GNOME|
|XDG_SESSION_DESKTOP|gnome|
|XDG_SESSION_TYPE|wayland|
</details>Extensions: none

**Comment by cheenamalhotra** [comment]
You can disable connection pooling, as connections maybe getting pooled.. 
Find in settings: 
![image](https://github.com/microsoft/azuredatastudio/assets/13396919/2a6765a8-6d75-4004-9aa7-846a5d664f73)

Or execute `Clear Pooled Connections` command, for the same.

[Read more about this here](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-1-46-and-new-features/ba-p/3933382)

**Comment by akc42** [comment]
Thanks solved my problem
