### ISSUE TITLE
Download links not working

### ISSUE THREAD

**Issue by FlashArrow2000** [microsoft/azuredatastudio#25675]
- Azure Data Studio Version:
- OS Version: Mac OS Sonoma 14.5 

Steps to Reproduce:

1.Acces this link: https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall
2.Click download for mac intel chip

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by jotomo75** [comment]
I'm in the same situation.
download link url 
https://go.microsoft.com/fwlink/?linkid=2261569

**Comment by Charles-Gagnon** [comment]
@jotomo75 @FlashArrow2000 There was a brief outage, but the links should be working again. Could you let us know if you're still seeing issues?

**Comment by jotomo75** [comment]
@Charles-Gagnon 
Thanks for letting me know, the link is now connected.
