### ISSUE TITLE
API Uri is not working to download insider or stable channel

### ISSUE THREAD

**Issue by steveturnbull** [microsoft/azuredatastudio#25679]
- Azure Data Studio Version: 1.48
- OS Version: Windows 10 Enterprise

Steps to Reproduce:

1. go to https://azuredatastudio-update.azurewebsites.net/api/update - no update feed found

Cannot GET /api/update

**Comment by kburtram** [comment]
@caohai do you know what's happening with the update link?

**Comment by steveturnbull** [comment]
broken again

**Comment by caohai** [comment]
Hi @steveturnbull ,
For insiders channel, please check https://github.com/microsoft/azuredatastudio/issues/25718
For stable channel, can you share the actual url you are sending request against? I just tested https://azuredatastudio-update.azurewebsites.net/api/update/win32-x64/stable/latest and it's working for me.
