### ISSUE TITLE
Edit Data: right click > delete row on the "new row" causes it to disappear

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#2568]
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Open edit data
2. Right click on the very last row (the one that allows you to add new rows) and choose "delete row"

Actual behavior: The row disappears and you can no longer add new rows
Expected behavior: The row cannot be deleted

**Comment by Charles-Gagnon** [comment]
This no longer reproes with the current build - attempting to delete the new row results in nothing happening.
