### ISSUE TITLE
Multi-monitor experience is bad

### ISSUE THREAD

**Issue by gcaughey** [microsoft/azuredatastudio#257]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.17046
---

Steps to Reproduce:

1. Launch SQL Studio and move it to large external monitor. Close app.
2. Launch app - only a tiny white square appears in upper right corner.
(Works fine when there is no external monitor.)

**Comment by kburtram** [comment]
Closing out older issues.  The multi-mon support is based off of vscode core platform and would be very costly for us to try to improve.  This will need to be fixed upstream.  Thanks for the suggestion!
