### ISSUE TITLE
Stop Azure Data Studio from launching automatically after installation

### ISSUE THREAD

**Issue by AScott-WWF** [microsoft/azuredatastudio#25711]
Type: <b>Bug</b>

I have just created a distribution for our users of the latest Azure Data Studio v1.48.1 (Released 18th June 2024)
N.B. This issue has been submitted via another Azure Data Studio v1.48.0 installation
We deploy software to all our users via Intune, the Application is installed as a System application
The command line I used to silently install the software was:
```
Execute-Process -Path ".\azuredatastudio-windows-setup.exe" -Parameters '/SP- /VERYSILENT /SUPPRESSMSGBOXES /CLOSEAPPLICATIONS /NORESTART /NORESTARTAPPLICATIONS  /LOG="C:\ProgramData\Microsoft\IntuneManagementExtension\Logs\AzureDataStudio_Install.log"'
```

Upon completion of the install Azure Data Studio automatically launches - unfortunately as the install was performed using the System account, the application assumes it should be launched using the same account - From a security perspective launching the newly installed app as System is not a good move. Personally, I feel that launching the application at the end of the install is completely unnecessary.
Please can you provide a method where by we can prevent Azure Data Studio from launching after install - Preferably a via command line switch we can use with the install.

Azure Data Studio version: azuredatastudio 1.48.0 (4970733324ef8254b7c22a5dc55af7f8a1dea93f, 2024-02-27T00:05:08.293Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Disabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 PRO 4750U with Radeon Graphics (16 x 1697)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.33GB (2.14GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
You should be able to use the `/MERGETASKS=!runcode` parameter to have it not launch ADS automatically after an installation.
