### ISSUE TITLE
stuck at activating

### ISSUE THREAD

**Issue by peteg55** [microsoft/azuredatastudio#25714]
Type: <b>Bug</b>

New install of Azure Data Studio and Azure SQL Migration extension. Everytime I open Azure Data Studio I get "SQL Tools Service component exited unexpectedly. Please restart Azsure Data Studio". Restarting the app makes no difference. Running extensions shows it is stuck at activating.

Azure Data Studio version: azuredatastudio 1.48.1 (8825ec21e67a34ede00e4f02a4afc692eb6cab61, 2024-06-13T21:07:19.253Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1145G7 @ 2.60GHz (8 x 1498)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.39GB (5.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-migration|Mic|1.5.4

</details>

**Comment by lewis-sanchez** [comment]
Hi @peteg55, I'm not able to get this error to occur, so I can be able to fix it. Would it be possible for you to add console or application logs to help me troubleshoot this?

**Comment by kburtram** [comment]
Closing due to lack of logs for further investigaiton.
