### ISSUE TITLE
Edit data creates a new row by default when there are no existing rows in a table

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#2573]
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Open edit data for a table with no rows

Expected behavior: The blank row to add a new row is the only row visible
Actual behavior: The blank row to add a new row is visible underneath a new row that gets created automatically

This is a minor bug since the new row doesn't actually get saved unless you put in any data, but it can be misleading since it makes it look like it's an existing row

**Comment by alanrenmsft** [comment]
The issue has been fixed
