### ISSUE TITLE
Download of older version of ADS doesn't work. I always get latest release.

### ISSUE THREAD

**Issue by gabolander** [microsoft/azuredatastudio#25735]
- Azure Data Studio Version: 1.48.1
- OS Version: Win 10

Hi there,
I need for some reasons, to download and install an older version of A.D.S.
In your page https://github.com/Microsoft/azuredatastudio/releases, I'm not able to download, e.g. release 1.47.0, because when I click to download links (and it reports correctly as https://go.microsoft.com/fwlink/?linkid=2251733), I get latest version though (as of writing: 1.48.1).

Steps to Reproduce:

1. go to page: https://github.com/Microsoft/azuredatastudio/releases
2. Scroll down until older version download table is displayed (es. 1.46 or 1.47.0), click on a link for any OS (even linux, or Win systemwide executable). When download starts, it gets 1.48.1 anyway.
3. Tested with browsers: Google Chrome, Mozilla Firefox, Brave browser, Edge ..

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
We recently made changes to our download/upgrade process to simplify our custom infrastructure as part of on-going security improvements.  We now are using the Microsoft Download Center to host our builds going forward.  A side-effect of this is that the links using the update server to download older builds no longer work correctly.

These builds can still be accessed directly from the BLOB storage location.  For example, for the 1.47.0 build you can use the following links.

```
Direct links for 1.47.0
Windows
 x64 User https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-user-setup-1.47.0.exe
 x64 System - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-setup-1.47.0.exe
 x64 ZIP - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-1.47.0.zip
 arm64 User - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-arm64-user-setup-1.47.0.exe
 arm64 System - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-arm64-setup-1.47.0.exe
 arm64 ZIP - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-windows-arm64-1.47.0.zip

MacOS
 Universal - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-macos-universal-1.47.0.zip
 arm64 - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-macos-arm64-1.47.0.zip
 x64 - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-macos-1.47.0.zip

Linux
 TAR.GZ - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-linux-1.47.0.tar.gz
 RPM - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-linux-1.47.0.rpm
 DEB - https://sqlopsbuilds.blob.core.windows.net/stable/c7c2b2f21505562d21972d4c135119d00806db4f/azuredatastudio-linux-1.47.0.deb
```

These same links can be used for other builds by replacing `c7c2b2f21505562d21972d4c135119d00806db4f` with the full commit hash of the build, which can be located by looking at the tag for the release in the Releases page on this site.  Please let me know if you need further details to download a particular build.

**Comment by kburtram** [comment]
I'll close this based on previous comment.  Please let us know if there's anything else for this.

**Comment by Rutgerdj** [comment]
@kburtram Is there any way to get a direct download link for versions that use the new Microsoft Download Center which are not the latest version? I could not manage to pin a specific version (`1.49.0` for example)

I ran into this issue when installing Azuredatastudio via the Nix package manager, here is a PR which describes and 'solves' the problem, but this PR is already broken again because in the meantime another update has come out so the `1.49.0` version tag actually downloads the `1.49.1` instead:

https://github.com/NixOS/nixpkgs/pull/334220

**Comment by kburtram** [comment]
@gaelj we are no longer using the Azure BLOB storage for new releases starting from 1.49.0.  We switch to Microsoft Download Center for media distribution as part of an upgrade to our auto-update infrastructure.

@caohai could you please post the direct URLs for the 1.49.0 release here for reference?  Going forward, we should consider adding these links into the release notes posted here.

**Comment by caohai** [comment]
@gaelj @Rutgerdj For version >= 1.48.1, the download links in the release page should be working, they are links that get redirected to the actual direct download links. Let me know if that works for you.
https://github.com/microsoft/azuredatastudio/releases

I'm also pasting the direct links here in case anyone needs them, but I'd suggest using the links in the release page if possible.
1.49.0
```
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-user-setup-1.49.0.exe
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-setup-1.49.0.exe
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-1.49.0.zip
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-arm64-user-setup-1.49.0.exe
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-arm64-setup-1.49.0.exe
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-windows-arm64-1.49.0.zip
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-macos-universal-1.49.0.zip
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-macos-1.49.0.zip
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-macos-arm64-1.49.0.zip
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-linux-1.49.0.tar.gz
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-linux-1.49.0.deb
https://download.microsoft.com/download/5/9/6/59609041-db64-475c-b82a-2b5795b904b7/azuredatastudio-linux-1.49.0.rpm
```

1.49.1
```
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-user-setup-1.49.1.exe
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-setup-1.49.1.exe
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-1.49.1.zip
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-user-setup-1.49.1.exe
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-setup-1.49.1.exe
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-windows-arm64-1.49.1.zip
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-macos-universal-1.49.1.zip
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-macos-1.49.1.zip
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-macos-arm64-1.49.1.zip
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-linux-1.49.1.tar.gz
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-linux-1.49.1.deb
https://download.microsoft.com/download/7/8/3/783c2037-8607-43c4-a593-0936e965d38b/azuredatastudio-linux-1.49.1.rpm
```

**Comment by Rutgerdj** [comment]
That makes sense, thanks for the help! @kburtram @caohai
