### ISSUE TITLE
Dashboard: Dashboard layout resets if details are expanded

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#2577]
- SQL Operations Studio Version: master

Steps to Reproduce:

1. Open any server dashboard. 
2. Click on the `Edit` icon in the top right corner of the dashboard.

![capture1](https://user-images.githubusercontent.com/6411451/45516002-a5b96680-b75e-11e8-9c08-47298cb10dfc.JPG)

3. Move around the widgets so that it's different from the original dashboard configuration.
4. Click on the `Expand` button in the top right corner to expand the server details.

![capture2](https://user-images.githubusercontent.com/6411451/45516008-ad790b00-b75e-11e8-91ea-17b996d49dac.JPG)

Expected - Server details expand and the dashboard layout stays the same.
Actual - The server details expand but the dashboard layout goes back to the original one.

**Comment by kburtram** [comment]
Closing out older issues.  This should be fixed by dashboard refactor in-progress.
