### ISSUE TITLE
Reach end of the Result Grid

### ISSUE THREAD

**Issue by bigleka** [microsoft/azuredatastudio#258]
- SQL Operations Studio Version: 0.23.6

Like SSMS, enable CRTL+END to reach end of the Result Grid

**Comment by erickangMSFT** [comment]
@bigleka This is supported feature. let us dig out and document it.

**Comment by bigleka** [comment]
Small things on keyboard shortcuts don´t exist like CTRL+R on SSMS close the result panel, the CTRL+END on Result Grid go to the end of result, or CTRL Left or Right  go to the last column or first column

**Comment by bigleka** [comment]
@kburtram any news about if this suggestion ?

**Comment by kburtram** [comment]
@anthonydresser do you know if we already have a keyboard shortcut for this scenario?

**Comment by anthonydresser** [comment]
doesn't seem so 
![image](https://user-images.githubusercontent.com/4324725/41631420-58c0908c-73e9-11e8-9a1b-d1a400999421.png)

probably didn't transfer it from the extension

**Comment by kburtram** [comment]
This is working on `1.8.0` as far as I can tell.  There is a SSMS Keymap extension that provides some of the other keyboard shortcuts discussed above.
