### ISSUE TITLE
Product Version attribute 'undefined' on Azure Data Studio v1.49.0

### ISSUE THREAD

**Issue by AScott-WWF** [microsoft/azuredatastudio#25804]
- Azure Data Studio Version: 1.49 (System Install)
- OS Version: Windows 10 22H2 x64 (Enterprise Edition)

Steps to Reproduce:

1. Install latest system install release of Azure Data Studio on Windows (10) - in my case using the following silent installation commands
```
azuredatastudio-windows-setup-1.49.0.exe /SP- /VERYSILENT /SUPPRESSMSGBOXES /CLOSEAPPLICATIONS /NORESTART /NORESTARTAPPLICATIONS /ALLUSERS /MERGETASKS=!runcode
```
2. Once installed, check the properties of the `"C:\Program Files\Azure Data Studio\azuredatastudio.exe"` file, specifically the Product version.
![image](https://github.com/user-attachments/assets/63984082-b2ac-4912-b254-fb9fdadb3d86)

The following PowerShell also confirms this:
```
$InstallPath = "C:\Program Files\Azure Data Studio\azuredatastudio.exe"
(Get-ItemProperty $InstallPath).VersionInfo.ProductVersion
undefined
```

As shown above, this version shows as 'undefined', earlier versions hold the version number (this version should show 1.49.0).
This is important when the software is deployed unattended using SCCM / MECM / ConfigMgr, Intune or other software deployment software, as the Product Version is often used as the detection method to confirm the latest version is / has been installed.

Does this issue occur when all extensions are disabled?: Yes

**Comment by kburtram** [comment]
This is fixed in forthcoming hotfix release.
