### ISSUE TITLE
GitHub Co-Pilot Extension outdated

### ISSUE THREAD

**Issue by fmir864** [microsoft/azuredatastudio#25802]
- Azure Data Studio Version: v1.49.0
- OS Version: Windows 11 Pro 22631.3880

Steps to Reproduce:

1. Open a new query window and start typing a query
2. Pop up as below

![Screenshot 2024-08-02 164331](https://github.com/user-attachments/assets/e0d6bdda-35e5-4e25-a8e4-4b246bce6c12)

Does this issue occur when all extensions are disabled?: No

I'm not getting an update for the extension as well

**Comment by kburtram** [comment]
@fmir864 there is a updated version of Copilot available in the Extension Manager view (v1.199.0).  If the extension didn't auto-update, please try to manually uninstall & reinstall the extension in the Extension Manager as a workaround.  We'll investigate why auto-update isn't working as expected for this extension.

**Comment by fmir864** [comment]
The Extension View doesn't show any update. What I did was, from the marketplace of vscode, downloaded the extension and installed it in ADS.

**Comment by kburtram** [comment]
Closing based on the previous comment that installing from VS Code marketplace worked successfully.  This doesn't appear to be a wide-spread issue yet, so will wait for additional reports before additional investigation.  Thanks for reporting!
