### ISSUE TITLE
OE - Node with no children still show chevron

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#2581]
- SQL Operations Studio Version:

Steps to Reproduce:
Nodes with no children still show the chevron (they shouldn't)

![image](https://user-images.githubusercontent.com/4324725/45518556-d6050300-b766-11e8-863a-33a20ccd0d66.png)

**Comment by JustinMDotNet** [comment]
This seems to be happening in serverTreeDataSource > hasChildren(). The code is returning !isAlwaysLeaf

**Comment by kburtram** [comment]
Closing older low-impact bugs.
