### ISSUE TITLE
CoPilot Extension needs an update but none is available

### ISSUE THREAD

**Issue by reedws** [microsoft/azuredatastudio#25819]
- Azure Data Studio Version: 1.49.0
- OS Version: MacOS 14.2.1

Steps to Reproduce:

1. Install ADS
2. Install CoPilot Extension and sign in
3. See error message about update
![Screenshot 2024-08-09 at 11 21 04 AM](https://github.com/user-attachments/assets/61b82e36-2fc9-437b-804d-ca179fccb413)

Does this issue occur when all extensions are disabled?: This is an extension issue

I attempted to report this using the report issue with extension button but it takes me to a [dead link](https://github.com/community/community/discussions/categories/copilot/issues/new?title=CoPilot%20needs%20to%20be%20updated%20but%20no%20update%20is%20available&body=%0AType%3A%20%3Cb%3EBug%3C%2Fb%3E%0A%0ACoPilot%20has%20stopped%20working%20and%20every%20time%20I%20launch%20ADS%20it%20notifies%20me%20that%20it%20needs%20an%20update%20to%20continue%20working%20but%20there%20is%20no%20update%20available%0A%0AExtension%20version%3A%201.82.15%0AAzure%20Data%20Studio%20version%3A%20azuredatastudio%201.49.0%20(6e6d22ddd74bbb4fbe344ed80b93b53489fe0239%2C%202024-08-01T04%3A59%3A46.131Z)%0AOS%20version%3A%20Darwin%20arm64%2023.2.0%0ARestricted%20Mode%3A%20No%0APreview%20Features%3A%20Disabled%0AModes%3A%0A%0A%3Cdetails%3E%0A%3Csummary%3ESystem%20Info%3C%2Fsummary%3E%0A%0A%7CItem%7CValue%7C%0A%7C---%7C---%7C%0A%7CCPUs%7CApple%20M1%20Max%20(10%20x%2024)%7C%0A%7CGPU%20Status%7C2d_canvas%3A%20enabled%3Cbr%3Ecanvas_oop_rasterization%3A%20enabled_on%3Cbr%3Edirect_rendering_display_compositor%3A%20disabled_off_ok%3Cbr%3Egpu_compositing%3A%20enabled%3Cbr%3Emultiple_raster_threads%3A%20enabled_on%3Cbr%3Eopengl%3A%20enabled_on%3Cbr%3Erasterization%3A%20enabled%3Cbr%3Eraw_draw%3A%20disabled_off_ok%3Cbr%3Evideo_decode%3A%20enabled%3Cbr%3Evideo_encode%3A%20enabled%3Cbr%3Evulkan%3A%20disabled_off%3Cbr%3Ewebgl%3A%20enabled%3Cbr%3Ewebgl2%3A%20enabled%3Cbr%3Ewebgpu%3A%20enabled%7C%0A%7CLoad%20(avg)%7C5%2C%205%2C%205%7C%0A%7CMemory%20(System)%7C64.00GB%20(0.68GB%20free)%7C%0A%7CProcess%20Argv%7C%7C%0A%7CScreen%20Reader%7Cno%7C%0A%7CVM%7C0%25%7C%0A%3C%2Fdetails%3E%0A%3C!--%20generated%20by%20issue%20reporter%20--%3E) instead of allowing me to submit my issue

**Comment by kburtram** [comment]
@reedws someone else ran into this too and workaround the issue discussed here https://github.com/microsoft/azuredatastudio/issues/25802.  The latest version in the marketplace is v.199.0, but for some reason it's not auto-updating in some cases, we'll investigate this.

Do you see the newer version if you uninstall the extension and try to reinstall from the Extension Manager?

<img width="1007" alt="Screenshot 2024-08-09 at 8 36 03 AM" src="https://github.com/user-attachments/assets/ff97f976-9540-4364-b38f-7960f39e398f">

**Comment by reedws** [comment]
Yep! manually uninstalling and re-installing forced it to update

**Comment by kburtram** [comment]
@reedws thanks for the update!  I'll use this issue to track the "Extension Manager not showing latest version & auto-updating" bug.
