### ISSUE TITLE
Windows System and User installer No certificate Publisher

### ISSUE THREAD

**Issue by Fumpdund** [microsoft/azuredatastudio#25824]
- Azure Data Studio Version: 1.49.0
- OS Version:Edition	Windows 11 Enterprise
  Version	23H2
  Installed on	‎10/‎23/‎2023
  OS build	22631.3880
  Experience	Windows Feature Experience Pack 1000.22700.1020.0

Steps to Reproduce:

1. Download either the 1.49.0 System or User installer.
2. Run Get-AppLockerFileInformation "%PathtoExe%"
3. 
![image](https://github.com/user-attachments/assets/4d70d9f2-37d6-4dff-b186-1d9d2e7a11a2)9)

Reviewing the digital signature shows a different signer than prior installs, it's not signed by Microsoft but Microsoft Azure. We do not have this certificate in our own store. Is this a new certificate signing authority that Microsoft will be using going forward?
![image](https://github.com/user-attachments/assets/0d73f769-f943-42c2-9fb0-021456e743f5)

Does this issue occur when all extensions are disabled?: Yes

**Comment by kburtram** [comment]
@Fumpdund thanks for bring this to our attention.  This is a valid Microsoft certificate but isn't the one we intended to use for these installer binaries.  We'll be releasing a hotfix in the next week or two to address this and some other issues introduced in the July release.

**Comment by dsidesfb** [comment]
I had reported this as a security issue, but couldn't take a screenshot of the UAC dialog so they closed the ticket. VULN-132088 CRM:0022057585

**Comment by Benjin** [comment]
I have checked in the fix internally.  You'll see this resolved in the upcoming hotfix release.

**Comment by Fumpdund** [comment]
> @Fumpdund thanks for bring this to our attention. This is a valid Microsoft certificate but isn't the one we intended to use for these installer binaries. We'll be releasing a hotfix in the next week or two to address this and some other issues introduced in the July release.

You're welcome. Going forward would this be a security issue and be reported through that manner? I wasn't sure where to report this.
