### ISSUE TITLE
OE Missing node icons

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#2582]
- SQL Operations Studio Version:

Steps to Reproduce:
Not sure what these nodes specifically are but this repros sql server 2016 under Security
![image](https://user-images.githubusercontent.com/4324725/45518626-0fd60980-b767-11e8-8ce9-37d24519810d.png)

**Comment by abist** [comment]
I added icons for triggers a while back so closing this issue.
