### ISSUE TITLE
OE - Blank row

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#2583]
- SQL Operations Studio Version:

Steps to Reproduce:
Blank row on sql server 2016
![image](https://user-images.githubusercontent.com/4324725/45518693-401da800-b767-11e8-8ae7-ac37b4778742.png)

**Comment by chlafreniere** [comment]
Just ran into this again. Still an issue 😄

**Comment by kburtram** [comment]
I don't see this repro'ing on the latest build.  Please let us know if this issue is still impacting you.

![image](https://user-images.githubusercontent.com/599935/129618222-23eae6b1-dbaa-4e6e-8d26-1139ba2a2b92.png)
