### ISSUE TITLE
Reload doesn't work

### ISSUE THREAD

**Issue by deej79** [microsoft/azuredatastudio#25843]
Type: <b>Bug</b>

Powershell extension showed the reload button. Clicking it did NOT clear the button. Stopping ADS and restarting it did NOT clear the button. The only way to clear it was to uninstall the extension.

Azure Data Studio version: azuredatastudio 1.49.1 (2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd, 2024-08-13T18:12:38.831Z)
OS version: Windows_NT x64 10.0.19045
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|15.92GB (6.99GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
import|Mic|1.6.1
profiler|Mic|0.14.0
query-history|Mic|0.5.3
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.4.3
schema-visualization|R0t|0.9.1
db-snapshot-creator|sea|0.1.0
simple-data-scripter|sea|0.1.6
vscodeintellicode|Vis|1.3.1

</details>

**Comment by kburtram** [comment]
This appears to be related to inconsistent metadata for the Powershell extension.  I'll see if this can be resolved by publishing an updated extension.

**Comment by kburtram** [comment]
Thanks for reporting this issue.  This should now be fixed with the new PowerShell extension published to the Extension Manager.  Please let me know if you see issues with any other extensions.
