### ISSUE TITLE
Cannot see the job steps in edit mode

### ISSUE THREAD

**Issue by CubsRep** [Microsoft/azuredatastudio#2586]
Issue Type: <b>Bug</b>

Go to SQLOPS and Open SQL Agent tab
Pick Job which has single/multiple job steps and right click to edit 
Go to STEPS tab
Expected: Job step(s) with Database Name and Command details
Actual:  None

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:40:40.895Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2693)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.05GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|50%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.32.7
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by abist** [comment]
@CubsRep thanks for opening this bug. The SQL Agent edit configuration dialogs are still in "early preview" state and have several known bugs we'll be fixing.

**Comment by abist** [comment]
Fixed in https://github.com/Microsoft/azuredatastudio/pull/2721
