### ISSUE TITLE
Dashboard: Errors when dragging widgets

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#2588]
- SQL Operations Studio Version: master

Steps to Reproduce:

1. Open any server or database dashboard.
2. Edit the widget configuration by moving around the widget by dragging the widgets towards the bottom of the page.

**Expected** - Nothing happens and the widgets get moved placed at the bottom.
**Actual** - The widget either gets placed at the bottom with a silent error in the background -
```
ERROR
zone-node.js:2280
TypeError: Cannot read property 'setScrollDimensions' of undefined
zone-node.js:2280
ERROR CONTEXT
zone-node.js:2280
DebugContext_ {view: Object, nodeIndex: 0, nodeDef: Object, elDef: Object, elView: Object}
```

OR

The widget just vanishes from the dashboard and can't be retrieved back.

**Comment by kburtram** [comment]
Closing out older issues.  This should be addressed by dashboard refactor in-progress.
