### ISSUE TITLE
Target size minimum (24x24) is failed for the "Copy" and "Refresh" buttons at "Configure Integration Runtime" section: A11y_[BM]SQL Migration extension for Azure Data Studio_Azure Database Migration Service_Create new Azure Database migration service_Target Size

### ISSUE THREAD

**Issue by Raj-ghuge** [microsoft/azuredatastudio#25913]
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after bug verification."**

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-nikpap%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847543876&sdata=6wiDneF0tmnVt4CroW43rkfVbB%2BL%2BAAdn0nD7xR5hQM%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHub Tags:**
#A11yMAS; #A11yWCAG2.2; #A11yTCS; #Win11; #DesktopApp; #A11ySev2; #BM_SQL Migration extension for Azure Data Studio_Win32_AUG2024; #SQL Migration extension for Azure Data Studio; #Target Size; #WCAG2.5.8; #AILimited; #FTP; #Win32;

## Environment Details:
Application Name: SQL Migration extension for Azure Data Studio
Microsoft Windows 11 version 23H2 (OS Build 22631.4037)
Version: 1.49.1 (user setup)
Commit: 2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T18:12:38.831Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
Azure SQL Migration v1.4.8

## Repro Steps:

1. Install Azure data studio and open
3. Tab till Extension press enter key and install Azure SQL Migration 
4. Tab till Respective server and right click
5. Tab till manage and press enter key
6. Tab till Azure SQL Migration and press enter key
7. Tab till migrate to azure sql and press enter key andSaved session page will open 
8. Select start new session and give next ,Databases for assessment page will open 
9. Select the respective databases and give next ,Assessment results and recommendations page will open
10. Select Azure SQL managed Instance/Virtual Machines from Azure SQL Target
11. Tab till Get Azure recommendation and press enter,
12. Get Azure Recommendation will open and select  collect performance data now ,Browse folder and give start
13. Tab till view/select and press enter, select database and give next
14. Azure SQL Target will open and give next; Migration mode page will open.
15. Choose Select offline or online mode and give next
16. Database backup page will open 
17. Select Azure blob container and give next
18. Azure Database Migration Service page will open and tab till Create, press enter
19. Create new Azure Database migration service page will open
20. Tab till “Create new Azure Database migration service " button and press enter key.
21. "Configure Integration Runtime" dialog is open.
22. Tab till "Copy" and "Refresh" buttons and observe the issue.

## Actual results:
Target size minimum (24x24) is failed for the "Copy" and "Refresh" buttons at "Configure Integration Runtime" section.
 
## Expected results:
Target size minimum (24x24) for the "Copy" and "Refresh" buttons should be 24X24 at "Configure Integration Runtime" section.

## User Impact:
Users with mobility or fine motor control impairments will not be able to accessible or select the button properly.

## Attachments:
![25913_A11y_ BM SQL Migration extension for Azure Data Studio_Azure Database Migration Service_Create new Azure Database migration service_Target Size _copy key button](https://github.com/user-attachments/assets/54735231-039f-447a-9434-93b000a00c08)
![25913_A11y_ BM SQL Migration extension for Azure Data Studio_Azure Database Migration Service_Create new Azure Database migration service_Target Size _refresh key button](https://github.com/user-attachments/assets/c0dfdb74-794f-4b26-add8-4db08427f7ce)

**Comment by akshika898** [comment]
Does this issue still exist? I see different dimensions in accessibility insights.![Image](https://github.com/user-attachments/assets/bc6451b0-d5e7-469f-bc99-c0be6f8299df)
![Image](https://github.com/user-attachments/assets/87f8123f-1d29-4da3-8c17-0890168616c5)

**Comment by Raj-ghuge** [comment]
Verified the bug in the environment-
Version: 1.49.1 (user setup)
Commit: 2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T18:12:38.831Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.26100
The "Configure Integration Runtime" dialog is blank. PFA below-

![Image](https://github.com/user-attachments/assets/ba7eac59-f3b2-4f8d-84c0-5596f64f4a4e)

**Comment by akshika898** [comment]
> Verified the bug in the environment- Version: 1.49.1 (user setup) Commit: [2f696aa](https://github.com/microsoft/azuredatastudio/commit/2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd) Date: 2024-08-13T18:12:38.831Z VS Code: 1.82.0 Electron: 25.9.8 Chromium: 114.0.5735.289 Node.js: 18.15.0 V8: 11.4.183.29-electron.0 OS: Windows_NT x64 10.0.26100 The "Configure Integration Runtime" dialog is blank. PFA below- #Regressed:10-29-24 ![Image](https://github.com/user-attachments/assets/ba7eac59-f3b2-4f8d-84c0-5596f64f4a4e)

@stuti149  Tagging you here, to verify as Rajeshwari saw this issue today although I saw that the fix PR has been merged?

**Comment by akshika898** [comment]
@Raj-ghuge  Do we have any updates on the issue. Let's please mark this closed if not reproducible?

**Comment by Raj-ghuge** [comment]
Verified the bug in the environment-
Version: 1.49.1 (user setup)
Commit: https://github.com/microsoft/azuredatastudio/commit/2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T18:12:38.831Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.26100
The "Configure Integration Runtime" dialog is blank. PFA below-
#Closed;

![Image](https://github.com/user-attachments/assets/6dc1afc4-9ab7-4906-992a-0c1dbb7dc58a)
![Image](https://github.com/user-attachments/assets/8c4f7895-4aa5-421e-9a1b-b817cbc5529e)

**Comment by Samhitha66** [comment]
#A11yfixed;
