### ISSUE TITLE
The information in the grid table is getting truncated, as no single pointer is provided to adjust the column header width at "Migration status-Database" section: A11y_[BM]SQL Migration extension for Azure Data Studio_Migration status_Database_Dragging Movements

### ISSUE THREAD

**Issue by Raj-ghuge** [microsoft/azuredatastudio#25914]
**"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after bug verification."**

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-nikpap%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847543876&sdata=6wiDneF0tmnVt4CroW43rkfVbB%2BL%2BAAdn0nD7xR5hQM%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**GitHub Tags:**
#A11yMAS; #A11yWCAG2.2; #A11yTCS; #Win11; #DesktopApp; #A11ySev2; #BM_SQL Migration extension for Azure Data Studio_Win32_AUG2024; #SQL Migration extension for Azure Data Studio; #Dragging Movements; #WCAG2.5.7; #AILimited; #FTP; #Win32;

## Environment Details:
Application Name: SQL Migration extension for Azure Data Studio
Microsoft Windows 11 version 23H2 (OS Build 22631.4037)
Version: 1.49.1 (user setup)
Commit: 2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T18:12:38.831Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
Azure SQL Migration v1.4.8

## Repro Steps:

1. Install Azure data studio and open
2. Tab till Extension press enter key and install Azure SQL Migration 
3. Tab till Respective server and right click
4. Tab till manage and press enter key
5. Tab till Azure SQL Migration and press enter key
6. Tab till databases migration in progress and press enter key
7. Select any databases and press enter key
8. Database page will open.
9. Tab till grid table and observe the issue.

## Actual results:
The information in the grid table is getting truncated, as no single pointer is provided to adjust the column header width at "Migration Status-Database" section.
 
## Expected results:
The information in the grid table should not be truncate, as single pointer should be provided to adjust/drag the column header width at "Migration Status-Database" section

## User Impact:
Users with mobility or fine motor control impairments will not be able to accessible or select the information properly at the grid table.

## Attachments:
[25914_A11y_[BM]SQL Migration extension for Azure Data Studio_Migration status_Database_Dragging Movements.webm](https://github.com/user-attachments/assets/305bd883-c1c4-4a41-bbc0-12d21ccb332d)

**Comment by Raj-ghuge** [comment]
Verified the issue in the environment -
Version: 1.50.0 (user setup)
Commit: 49c73a84388731fec941dac8d938345ac16bd470
Date: 2024-11-17T22:41:05.327Z
VS Code: 1.82.0
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
The issue is does not repro, hence closing the bug.
Please find the attachment for your reference.
#Closed;
#Regressed:11-25-24
https://github.com/user-attachments/assets/2ef9fd79-cd3f-4856-807e-3bffc75c92aa

**Comment by Samhitha66** [comment]
#A11yfixed;
