### ISSUE TITLE
No visible marker provided that can indicate the field are mandatory for "Target database name" and "Network share path":A11y_[BM]SQL Migration extension for Azure Data Studio_Database backup_Network file share_Labels or Instructions

### ISSUE THREAD

**Issue by Swati1700** [microsoft/azuredatastudio#25919]
"Please do not close this bug. This bug should only be closed by TCS, C+AI Accessibility tester after bug verification."

[Check out Accessibility Insights!](https://nam06.safelinks.protection.outlook.com/?url=https://accessibilityinsights.io/&data=02%7c01%7cv-nikpap%40microsoft.com%7cb67b2c4b646d4f9561a208d6f4b5c39b%7c72f988bf86f141af91ab2d7cd011db47%7c1%7c0%7c636965458847543876&sdata=6wiDneF0tmnVt4CroW43rkfVbB%2BL%2BAAdn0nD7xR5hQM%3D&reserved=0) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

### GitHub Tags:
#A11yMAS; #A11yTCS; #Win11; #DesktopApp; #A11ySev2; #BM_SQL Migration extension for Azure Data Studio_Win32_AUG2024; #SQL Migration extension for Azure Data Studio; #WCAG3.3.2; #FTP; #Win32; #Labels or Instructions;

### Environment Details:
Application Name: SQL Migration extension for Azure Data Studio
Microsoft Windows 11 version 23H2 (OS Build 22631.4037)
Version: 1.49.1 (user setup)
Commit: https://github.com/microsoft/azuredatastudio/commit/2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd
Date: 2024-08-13T18:12:38.831Z
VS Code: 1.82.0
Electron: 25.9.8
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22631
Azure SQL Migration v1.4.8

### Repro Steps:

1. Install Azure data studio and open
2. Tab till Extension press enter key and install Azure SQL Migration 
3. Tab till Respective server and right click
4. Tab till manage and press enter key
5. Tab till Azure SQL Migration and press enter key
6. Tab till migrate to azure sql and press enter key andSaved session page will open 
7. Select start new session and give next ,Databases for assessment page will open 
8. Select the respective databases and give next ,Assessment results and recommendations page will open
9. Select Azure SQL managed Instance/Virtual Machines from Azure SQL Target
10. Tab till Get Azure recommendation and press enter,
11. Get Azure Recommendation will open and select  collect performance data now ,Browse folder and give start
12. Tab till view/select and press enter ,select database and give next
13. Azure SQL Target will open  and give next, Migration mode page will open and select online.
14. Tab till "My databse backups are on a network share" radio button and select it.
15. Tab till "Next" button and press enter.
16. Tab till "Target database name" and "Network share path" grid columns.
17. Observe the fields are marked as mandatory visually.

**Note: Similar issue is also reproducing in the below scenarios:
Migrate to azure sql - Azure Database Migration Service (Subscription combo box)
Migrate to azure sql- Database backup**

### Actual results:
No visible marker provided that can indicate the field are mandatory for "Target database name" and "Network share path".

### Expected results:
Visible marker should be provided that can indicate the field are mandatory for "Target database name" and "Network share path".

### User Impact:
The Users will get confused and will miss out the mandatory fields.

### Attachments:
[25919_A11y_[BM]SQL Migration extension for Azure Data Studio_Database backup_Network file share_Labels or Instructions.webm](https://github.com/user-attachments/assets/6ca048e7-c51f-4b57-aa1a-b2d28da9bf27)

![25919_A11y_ BM SQL Migration extension for Azure Data Studio_Database backup_Network file share_Labels or Instructions](https://github.com/user-attachments/assets/cc5261b8-0156-4e01-9870-45c7fed20eaf)

**Comment by akshika898** [comment]
While reading through the issue i understand that we need the required indicator on 
1) subscription combo box
2) target database name and network share path (Database backup on network share)
3) What do we mean here by Similar issue in database backup?
Does it refer to Database Backups are on blob storage?
![Image](https://github.com/user-attachments/assets/59ea4903-442f-4085-a69c-dafc35172130)

**Comment by Swati1700** [comment]
Verified the issue in the environment Version: 1.50.0 (user setup)
Commit: 49c73a84388731fec941dac8d938345ac16bd470
Date: 2024-11-17T22:41:05.327Z
VS Code: 1.82.0
Electron: 30.5.1
Chromium: 124.0.6367.243
Node.js: 20.16.0
V8: 12.4.254.20-electron.0
OS: Windows_NT x64 10.0.26100
 and issue is fixed. Hence closing the bug.
![Image](https://github.com/user-attachments/assets/e27b5913-2ec1-47c5-b0aa-e521c3b91f75)
![Image](https://github.com/user-attachments/assets/492df029-89f6-498a-9855-aeeb3de4369d)
