### ISSUE TITLE
Saving As of 500 Mb files results in a 0 byte size file being written

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2591]
- SQL Operations Studio Version:
Version 0.33.5
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.8
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Open a 500 mb tsql file in editor.
    This gives a warning that the file is too big and turns of intellisense and other editing features on file. Do not force enable those features.

2. Make minor edits to this file and save this file. This succeeds.

3. Make some more edits and perform a Save As operation to a new file name. This ostensibly succeeds.

4. Go to the filesystem and check the size of the new file that was written.

Expected: A 500 mb file gets written to the new location.

Actual: A 0 byte size file gets written.

**Comment by kburtram** [comment]
There have been many fixes in handling large files that we picked up from upstream.  Please open an issue against vscode if this is still occurring and can be repro'ed upstream.  Thanks!
