### ISSUE TITLE
Ops studio becomes unresponsive after a query returns many result sets over many hours

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2592]
- SQL Operations Studio Version: master

Steps to Reproduce:
1. Run a query that returns, for example, 1 result set with 1000 rows every minute
2. Let this query run for a long time (I did it for ~24 hours)

At the end of the 24 hours Ops Studio is unresponsive.

It's probably reasonable to have some upper limit on what we can handle and this might be past it, but since our code is supposed to window results @ranasaria and I were a bit surprised to see this happen so we should at least investigate it

**Comment by ranasaria** [comment]
I did the same test as well. My observation was the following:

Sql Ops Studio was response. Just the Query Editor from which I was running the query that returns ~1k bytes per minute was unresponsive.


-  Arvind.

________________________________

**Comment by anthonydresser** [comment]
We window each result set but we don't window all the results sets. I.E if there are 100 results sets and we window 50 rows from each we have 5000 (50*100) rows in memory.

**Comment by ranasaria** [comment]
Yeah, the fix we will need to do is to window the number of resultsets as well. Or window total number of rows displayed across all result sets.


-  Arvind.

________________________________

**Comment by anthonydresser** [comment]
Can either of you send me instructions on reproing? (scripts or w/e) I have a fix that works in my quick testing.

**Comment by MattIrv** [comment]
I ran the following query:

```
WAITFOR DELAY '00:01:00';
select top 1000 * from AdventureWorks2016.Sales.SalesOrderDetail
go 1248
```

you'll need AdventureWorks2016 from https://docs.microsoft.com/en-us/sql/samples/adventureworks-install-configure?view=sql-server-2017, or you can run some other query

**Comment by kburtram** [comment]
We did some performance enhancements for handling many result sets a while back (when we removed angular from the query editor).  Please let us know if this issue is still impacting you on the latest builds.
