### ISSUE TITLE
Download link for WIndows .zip x64 downloads an .exe

### ISSUE THREAD

**Issue by martincook3** [microsoft/azuredatastudio#25933]
- Azure Data Studio Version: 1.49.1
- OS Version: Win 10

Steps to Reproduce:

1. https://learn.microsoft.com/en-us/azure-data-studio/download-azure-data-studio?tabs=win-install%2Cwin-user-install%2Credhat-install%2Cwindows-uninstall%2Credhat-uninstall#download-azure-data-studio
2. Click on Windows > .zip > x64 (https://go.microsoft.com/fwlink/?linkid=2282377)
3. azuredatastudio-windows-setup-1.49.1.exe is downloaded, not the zip.

The equivalent link on https://github.com/Microsoft/azuredatastudio/releases is correct (https://go.microsoft.com/fwlink/?linkid=2282378) so I have been able to download what I want. I am raising this issue as a fyi.

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
Closing as fixed.  Thanks for reporting!
