### ISSUE TITLE
Cannot find Stored Proc and Function folders for Fabric SQL Data warehouse in Azure Data Studio

### ISSUE THREAD

**Issue by viswk** [microsoft/azuredatastudio#25942]
Cannot find Stored Proc and Function folders for Fabric SQL Data warehouse in Azure Data Studio

![ADS_TVF_](https://github.com/user-attachments/assets/da015a0c-26be-4cac-a53d-393ea6e547b6)

Even though SP & TVFs aren't visible but when I tried to execute the Stored Proc or TVF, able to get the result sets

![ADS_TVF_1](https://github.com/user-attachments/assets/68501de8-3817-4597-a4ca-5803fe0bdcec)

However the same can be viewed from SSMS ( both TVFs and SP)

![SSMS_TVF_](https://github.com/user-attachments/assets/264f4fa1-ffc6-4b04-ae8e-6d740fffa20b)

- Azure Data Studio Version: 1.49.1
- OS Version: Windows_NT x64 10.0.22631

Steps to Reproduce:

1. Connect to Fabric SQL DW Instance through SSMS or Fabric UI 
2. Create TVF or Stored Proc
3. Once created check the TVF/SP in the SSMS (on latest version) - It would be organized in right folders
4. Now connect to Azure Data Studio to same Fabric SQL DW instance
5. Check the folders -- Function & Stored Proc folder doesn't exist at all

Does this issue occur when all extensions are disabled?: Yes/No

**Comment by kburtram** [comment]
Fixed in 1.50 release.
