### ISSUE TITLE
Can't log in MS SQL Server.

### ISSUE THREAD

**Issue by Vnsabhay** [microsoft/azuredatastudio#25978]
Type: <b>Bug</b>

Connection Error: 
Error: invalid_grant occurred when acquiring token.
135010 - [2024-10-17 16:46:57Z]: AADSTS135010: UserPrincipal doesn't have the key ID configured. Trace ID: 460f8d5d-a1be-4298-9afe-05878a0a1800 Correlation ID: 52671184-a1f1-4e9a-adf3-580128b771a7 Timestamp: 2024-10-17 16:46:57Z - Correlation ID: 52671184-a1f1-4e9a-adf3-580128b771a7 - Trace ID: 460f8d5d-a1be-4298-9afe-05878a0a1800

Azure Data Studio version: azuredatastudio 1.49.1 (2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd, 2024-08-13T18:12:38.831Z)
OS version: Windows_NT x64 10.0.26100
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|13th Gen Intel(R) Core(TM) i7-1365U (12 x 2688)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|31.60GB (14.40GB free)|
|Process Argv|-r --server=capacityreporting.database.windows.net --database=bireporting --user=abhasingh@microsoft.com|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by jonmozley** [comment]
In case anyone else encounters this issue, I cleaned up the cached token from here and it resolved the issue for me.

`C:\Users{UserNameHere}\AppData\Roaming\azuredatastudio\Azure Accounts`

Source: https://learn.microsoft.com/en-us/answers/questions/2080978/cannot-connect-to-azure-data-studio-sql-server-dat
