### ISSUE TITLE
GitHub API rate exceeded

### ISSUE THREAD

**Issue by maxfaa** [microsoft/azuredatastudio#26018]
Type: <b>Bug</b>

GitHub API rate exceeded error message in Issue Reporter :
![Image](https://github.com/user-attachments/assets/81585845-3dd2-436c-b3ea-3f1f73b0f8aa)

Azure Data Studio version: azuredatastudio 1.49.1 (2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd, 2024-08-13T18:03:28.478Z)
OS version: Darwin arm64 24.1.0
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 (8 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|28, 36, 17|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
It seems this was a temporary issue caused by ADS exceeding its rate limits. The issue appears to be resolved now. We apologize for any inconvenience caused.
