### ISSUE TITLE
Home/End key handling when editing data

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#2601]
- SQL Operations Studio Version:
latest master.

Steps to Reproduce:
1. Open edit data for any table and find an editable cell
2. Select the cell to edit it, inside the text box, press HOME or END key

Expected:
the focus moves to the end or beginning in the text editor

Actual:
the focus moves to the last cell or the first cell of the row

**Comment by MattIrv** [comment]
@alanrenmsft can you describe this issue a bit more? I can't repro it on Windows or Mac without your fix, and what you've described as the "actual" behavior above is what I would expect. If focus is in the edit data grid then home/end move through the grid, and if focus is in the editor then home/end move through the editor

**Comment by alanrenmsft** [comment]
@MattIrv inside the text box when you are editing a cell, when pressing Home/End keys, I would expect the focus to stay inside the text box just like in SSMS to easily move the focus to the beginning or end of the text, actual behavior is the focus will be moved to the last or the first cell of the row.

**Comment by MattIrv** [comment]
Oh ok I understand now. Thanks!

**Comment by alanrenmsft** [comment]
this has been fixed in the slickgrid repo, waiting for Anthony to produce a new release and reference it in ADS repo
