### ISSUE TITLE
Retire: "Azure PostgreSQL migration" extension from Azure Data Studio - 15th Nov 2024

### ISSUE THREAD

**Issue by apduvuri** [microsoft/azuredatastudio#26044]
The Azure PostgreSQL migration extension in Azure Data Studio currently offers limited functionality and lacks support for the latest Azure Database for PostgreSQL SKUs, making it less effective for user migration needs. By retiring the extension in Azure Data Studio, we aim to focus on improving and supporting the tools that will offer you the most value in users migration journey.

If users continue to use the Azure PostgreSQL migration extension after November 15, 2024 it will no longer be enhanced or supported, and will not have the latest security and compliance features. We encourage users to transition to the enhanced [migration services](https://go.microsoft.com/fwlink/?linkid=2283673) available in the Azure portal as a feature of Azure Database for PostgreSQL – Flexible server or through Azure CLI. These services include pre-migration validation and are designed to better support your migration projects, ensuring a smoother and more efficient transition to Azure.

Currently, the Azure PostgreSQL migration extension in Azure Data Studio is in public preview. We plan to retire this extension and remove it from all existing and future versions of Azure Data Studio. Please ensure the extension is removed from ADS after 15th Nov 2024

Announcement in Az Update - https://azure.microsoft.com/updates/v2/Azure-PostgreSQL-migration-extension-in-Azure-Data-Studio-1

Identifier - microsoft.postgresql-migration
cc: @croblesm 

![Image](https://github.com/user-attachments/assets/dedfa44a-067f-4912-8299-fe48769395c5)

**Comment by Benjin** [comment]
Hi @apduvuri - we can certainly help with removing the Azure PostgreSQL migration extension from Azure Data Studio.  Can you please answer these quick questions:

1. What date would you like your extension removed from Azure Data Studio?

    [ before | on | after ] \<date>

2. What known locations does your extension need to be removed from?

    * Built into or shipped with Azure Data Studio?
    * Code is checked into github.com/microsoft/azuredatastudio, but extension is installed separately?
    * Only in the gallery (you build the extension yourself)?
    * Any other locations or integration points referencing your extension?

**Comment by apduvuri** [comment]
Hi @Benjin ,

1. On 15th Nov 2024
2. Please remove the extension from both ADS and ADS insider JSON. Repo link - https://msdata.visualstudio.com/Migration%20Assistant/_git/ads-extension-postgresql?_a=history

**Comment by Benjin** [comment]
This change has been rolled out!  Please verify that it's no longer showing in the gallery for you.

**Comment by apduvuri** [comment]
Yes, not showing in the marketplace - "Azure PostgreSQL Migration" extension in ADS.

![Image](https://github.com/user-attachments/assets/bfad6be9-48a3-4840-9c5f-e482791a2948)
![Image](https://github.com/user-attachments/assets/604e7649-5e40-452d-bde8-529fa8ce0566)
![Image](https://github.com/user-attachments/assets/f561b23a-c25d-44b1-986d-bb118039ccdc)
![Image](https://github.com/user-attachments/assets/9b026d18-a385-4d7b-9f9d-c37a9afd48ea)
