### ISSUE TITLE
Stored procedures not listed on fabric data warehouse connnections

### ISSUE THREAD

**Issue by sufhayes** [microsoft/azuredatastudio#26065]
Type: <b>Bug</b>

Connect to a fabric data warehouse that has a stored procedure.

The programability folder (or stored procedures or functions) is not listed in Azure Data studio. It is listed when connecting to the same database via SSMS.

Azure Data Studio version: azuredatastudio 1.49.1 (2f696aa95a13ccabd7e0a4431d1d759e3a7b8cfd, 2024-08-13T18:12:38.831Z)
OS version: Windows_NT x64 10.0.22631
Restricted Mode: No
Preview Features: Enabled
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz (8 x 2419)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.69GB (46.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
copilot|Git|1.242.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.1.3
agent|Mic|0.49.0
azcli|Mic|1.8.0
dacpac|Mic|1.14.0
import|Mic|1.6.1
profiler|Mic|0.14.0
schema-compare|Mic|1.21.0
sql-database-projects|Mic|1.4.3
sql-migration|Mic|1.5.6

</details>

**Comment by cgettys-microsoft** [comment]
Hi @sufhayes - thanks for the thorough bug report. This is the same issue as https://github.com/microsoft/azuredatastudio/issues/25942.
It should be fixed in the November Azure Data Studio release (i.e. 1.50) release - which just came out. I personally wrote the fix and tested it before contributing it - please do let me know if it still isn't working how you'd expect :).

**Comment by sufhayes** [comment]
@cgettys-microsoft That's great news! Eagerly looking to test it!

**Comment by sufhayes** [comment]
Apparently I just updated to 1.50 and it works great!
