### ISSUE TITLE
Generated Create Table Script Has "Unrecognized" Syntax

### ISSUE THREAD

**Issue by benrr101** [microsoft/azuredatastudio#2617]
- SQL Operations Studio Version:

Steps to Reproduce:
1. We probably have a bunch of wonky tables. One generates the following script as create for the primary key:
```SQL
ALTER TABLE [dbo].[myTable] ADD  CONSTRAINT [PK_myTable] PRIMARY KEY CLUSTERED 
(
	[myTableId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
```

Expected: `SORT_IN_TEMPDB = OFF` and `ONLINE = OFF` would be acceptable to the editor
Actual: Red squigglies under the two above `WITH` clauses

<img width="660" alt="sqlops - unsupported with" src="https://user-images.githubusercontent.com/585878/45698753-bbe86d80-bb36-11e8-8476-a6c392549523.PNG">

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if this issue is still impacting you.
