### ISSUE TITLE
kerberos authentication does not work

### ISSUE THREAD

**Issue by mmalto** [Microsoft/azuredatastudio#2629]
Issue Type: <b>Bug</b>

we have verified that the SPN's are registered in AD but continue to receive kerberos authentication errors to sql servers.  ive searched/googled and cannot find a solution to this issue.  appears that others have had similar issues and i do not see a solution.

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:30:28.766Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>vpx_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.27GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
Closing since we don't have an internal repro for this.  Please let me know if the problem persists.
