### ISSUE TITLE
Result export "Open file" button does nothing on Mac/Linux

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2636]
- SQL Operations Studio Version: master 03ea265
- OS: Mac

Steps to Reproduce:
1. Run a query
2. Export the results to CSV, JSON, or Excel
3. Close out of the new file if it opens but do not dismiss the pop-up that tells you the export succeeded
4. Click the "Open file" button on that pop up

Expected behavior: The exported file opens
Actual behavior: nothing happens

**Comment by kburtram** [comment]
@MattIrv I think this may be related to the OS.  `Open file` seems to work for me on Windows, but not on Linux.

**Comment by kburtram** [comment]
This should be fixed on latest builds.  Thanks!
