### ISSUE TITLE
Query text is not visible when the editor is split

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#2637]
- SQL Operations Studio Version: master 03ea265

Steps to Reproduce:
1. Open 2 editors
2. Drag one of them to the bottom of the window so that your editors are split with 1 on top and 1 on the bottom
3. Run a query in the bottom editor

Expected behavior: The query editor shows up normally
Actual behavior: No text in the query editor is visible because it is cut off

![Bottom query editor with no text visible](https://user-images.githubusercontent.com/3758704/45781718-a8600400-bc15-11e8-88c3-0ba564c96fe7.png)

**Comment by kburtram** [comment]
I think this looks like a variation of https://github.com/Microsoft/sqlopsstudio/issues/2509.

**Comment by anthonydresser** [comment]
We'll track this under #2509
