### ISSUE TITLE
Wrong Query Plan shown after dragging editor to different group

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2639]
- SQL Operations Studio Version: `0.33.7`

Steps to Reproduce:

1. Open two query windows
2. Run `Explain` on a SQL query in first editor, such as `EXEC sp_who`
3. Run `Explain` on a SQL query in second editor, such as `SELECT 1`
4. Drag second editor to a new editor group

Expected: Both editors are correctly displayed side-by-side

Actual: The query plan for the first query is shown under the second query

![image](https://user-images.githubusercontent.com/599935/45782610-48b72800-bc18-11e8-94e8-0750b5c7f9fa.png)

**Comment by kburtram** [comment]
Another note is that in the show plan on the left there are now no arrows.  I assume these are related, but we should verify to fix both problems.

**Comment by abist** [comment]
@kburtram I investigated this and this might need a big fix.
