### ISSUE TITLE
Run the query with actual plan will add an extra vertical scrollbar to the results area of query editor

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#2640]
- SQL Operations Studio Version:
latest master

Steps to Reproduce:
1. Run the following query on any database
_select * from sys.objects
go 3_

2. after the query execution, you will be redirected to the query plan tab, now switch back to the results tab.

You can see there are 3 vertical scroll bars, the one on the right is introduced by the query plan tab

**Comment by anthonydresser** [comment]
This no longer repros
