### ISSUE TITLE
Query editor active result tab isn't remembered when document tab switch

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2641]
- SQL Operations Studio Version: `0.33.7`

Steps to Reproduce:

1. Run a query with `Explain` option
2. Switch to `Results` tab
3. Open a new document editor
4. Switch back to original document editor

Expected: Result tab state preserved with `Results` tab active and `Query Plan` tab in the background

Actual: `Query Plan` tab is active with `Results` tab in the background

**Comment by anthonydresser** [comment]
This isn't reproing anymore, I think this was fixed in a different fix.

**Comment by kburtram** [comment]
I'm still hitting this issue on a current build from master.
