### ISSUE TITLE
Data and object comparison

### ISSUE THREAD

**Issue by SebastianPfliegel** [microsoft/azuredatastudio#265]
- SQL Operations Studio Version: 0.23.6

One of my regular tasks is to compare the database schema between the testing/development and productive environment. I want to be able to compare the whole schema, only specific types (tables only) and only a single object with another database. I also often need to compare the data of a different database or CSV file. It would also come in handy being able to use a external comparison/merge tool.

**Comment by joshbooker** [comment]
+1 for compare suggestion. I'd love to see this include the functionality of ssdt in visual studio. Import a database makes a project containing create scripts for all objects, compare schema between project and server, generate update scripts, etc. in my opinion that's when source control begins to make sense in a db project. Thanks for listening.

**Comment by SebastianPfliegel** [comment]
@joshbooker: the sqlopsstudio team counts reactions (thumbs up and down) instead of +1 texts ;-)

**Comment by joshbooker** [comment]
If there was a way to give thumbs up on github mobile site then I would do so. Otherwise I suggest the team read our comments. Thanks.

**Comment by kburtram** [comment]
We recently released the Schema Compare extension to address this scenario.  Please log more specific issues against that feature for further improvements.  Thanks!
