### ISSUE TITLE
Can't scroll sideways in results with trackpad/mouse wheel

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#2653]
- SQL Operations Studio Version: master 216b6ee
- Operating System: Mac

Steps to Reproduce:
1. Run a query that has enough columns that the results have a horizontal scrollbar, or run a query then stretch one of the columns so that the results have a horizontal scrollbar
2. Try to scroll the results horizontally with the mouse wheel or trackpad

Expected behavior: The results scroll
Actual behavior: The results do not scroll and you have to use the scrollbar in order to scroll horizontally

Scrolling vertically works though

**Comment by anthonydresser** [comment]
this should be fixed by #2774
