### ISSUE TITLE
Double clicking in database dashboard search widget resets dashboard's connection to the server connection

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#2654]
- SQL Operations Studio Version: master 216b6ee

Steps to Reproduce:
1. Open a database dashboard for some database other than master
2. Double click in the search widget but not on any element

Actual behavior: The dashboard tab's title resets to match the server connection instead of the database and now if you right click and run an action on any of the items in the search widget it fails because the database is wrong

Expected behavior: Nothing happens

**Comment by kburtram** [comment]
This UX has been rewritten since this issue.  I wasn't able to repro on the current release.  Please let us know if this issue is still impacting your experience.  Thanks!
