### ISSUE TITLE
Add Microsoft SQL Server EXPORT DATA extension for SQL Operations Studio

### ISSUE THREAD

**Issue by grishRodCas** [microsoft/azuredatastudio#2658]
Please Add Microsoft SQL Server EXPORT DATA extension for SQL Operations Studio. It would be very usefull

![c-users-marko-appdata-local-microsoft-windows-ine](https://user-images.githubusercontent.com/40496188/45853600-f9eaba80-bd0b-11e8-9451-7c1a334357b9.png)

**Comment by kburtram** [comment]
The `SQL Server Dacpac` extension provide an option to Export data similar to the same command in SSMS.  Thanks!
