### ISSUE TITLE
Undo doesn't work after unfocusing data edit cell

### ISSUE THREAD

**Issue by AlexFsmn** [Microsoft/azuredatastudio#2667]
- SQL Operations Studio Version: `master`

Steps to Reproduce:
1. Edit a table
2. Mark and edit cell A
3. Mark cell B
4. Go back to cell A and try pressing Ctrl+Z or right-click -> undo

Expected: Undo should still function in cell A
Actual: Nothing happens

The real problem here is if you make a mistake when editing a cell and you input the incorrect format:
_(Column testdt in this example is of type datetime)_
![image](https://user-images.githubusercontent.com/11557675/45917426-34249b00-be77-11e8-827d-d610d46de70c.png)

If you edit a cell with the incorrect format like this:
![image](https://user-images.githubusercontent.com/11557675/45917433-6209df80-be77-11e8-8be3-3422d6c86684.png)

You will end up with the following error in the log:
![image](https://user-images.githubusercontent.com/11557675/45917435-7057fb80-be77-11e8-948a-d74f8f7e27e5.png)

If you then try to go back to that cell and undo your mistake it isn't possible at the moment.
The problem here is that if you forget the initial value you won't be able to unfocus that cell and expect it go back as normal as it will continue showing the error above.

The only current workaround I have found for this is to close the editing window and reopen it.

**Comment by alanrenmsft** [comment]
@AlexFsmn You could revert the changes by pressing the ESC key, NOTE: it will revert the changes in the selected row.
