### ISSUE TITLE
Number of rows affected displayed in the toolbar does not match the rows affected shown in the message panel

### ISSUE THREAD

**Issue by yvrkarthik** [Microsoft/azuredatastudio#2669]
Hi,

I have an issue with toolbar not updating the number of rows affected when a query is executed. 

Steps to reproduce: 
1. Execute the following  query against AdventureWorks database

SELECT  top 10 with Ties LoginID, JobTitle, HireDate, VacationHours, (VacationHours/24) as VacationDays
FROM HumanResources.Employee as emp
ORDER BY VacationDays DESC;

2. Now switch the database and execute a different query against WideWorldImports. 

use WideWorldImporters
GO
SELECT StockItemName, UnitPrice, TaxRate, (UnitPrice*TaxRate)/100 as 'SalesTax'
FROM Warehouse.StockItems
ORDER BY UnitPrice DESC;

The following result is being displayed 

![image](https://user-images.githubusercontent.com/1669197/45932960-cf815180-bfd8-11e8-91ae-2cbde871bbab.png)

**Comment by anthonydresser** [comment]
I can't seem to repro this.

**Comment by yvrkarthik** [comment]
@anthonydresser,- I tried to replicate the issue but it seems to be fixed. I'm on v1.3.8. 

It might have been fixed now. So, I will be closing this issue and will re-open if the issue does come back. 

Thanks
