### ISSUE TITLE
tabColorMode setting doesn't work

### ISSUE THREAD

**Issue by romanovmv** [Microsoft/azuredatastudio#2670]
Issue Type: <b>Bug</b>

1. Create any server group and assign any color to it.
2. Open new tab and connect to any server from server group
Expected: tab color changes to server group's color
Actual: tab color remains the same

Tested on both light and dark themes

SQL Operations Studio version: sqlops 0.33.7-insider (03ea265bab6e10ec63566813808e0e524965caca, 2018-09-19T03:02:31.597Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (7.77GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.2.0

</details>

**Comment by extrobe** [comment]
I have this too;
I tried both the 'fill' and 'border' variants
I also tried setting via both the user settings file and the new settings editor.

I couldn't get it to utilise the tab colour from the group

**Comment by JamesHyot** [comment]
I have the exact same issue. Clicking and dragging a tab makes the color appear again, until I click anywhere on the screen.

**Comment by charlietango558** [comment]
Same issue on my end

**Comment by kburtram** [comment]
This should be fixed in the latest insiders build and will be in the October stable build next week.
