### ISSUE TITLE
Double click on tab bar opens new query without toolbar

### ISSUE THREAD

**Issue by Bikonja** [Microsoft/azuredatastudio#2672]
Issue Type: <b>Bug</b>

When double clicking the tab area (not on a tab itself, but the area that holds the tabs) a new query opens, as expected. However, the new query does not have the toolbar that all the rest of the queries have (with the buttons to Run, Cancel, Disconnect, Change Connection and explain a query).

I've also noted that the icon is not a query icon, I assume what happens is it opens a new "File" instead of a new "query" and files don't need the query toolbar, but that's just my guess.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (2.19GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.32.7
profiler|Mic|0.1.5

</details>

**Comment by kburtram** [comment]
It looks like double-click in the tab bar is opening a plain text file.  We should have this open a new query editor instead.
