### ISSUE TITLE
syntax checker shows red underline for valid TSQL

### ISSUE THREAD

**Issue by fatherjack** [microsoft/azuredatastudio#2673]
open a query editor and connect to a database and enter code:

DROP TABLE IF EXISTS SalesPeople;

the code above has red underline for "IF EXISTS SalesPeople"

When hovering over the underlined code the context tooltip shows
"an expression of non-boolean type specified in a context where a condition is expected"

This syntax is accepted by SSMS.

This syntax executes as expected, without error, in both ADS and in SSMS

-------------------
CPUs	Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)
GPU Status	2d_canvas: unavailable_software
checker_imaging: disabled_off
flash_3d: unavailable_software
flash_stage3d: unavailable_software
flash_stage3d_baseline: unavailable_software
gpu_compositing: unavailable_software
multiple_raster_threads: enabled_on
native_gpu_memory_buffers: disabled_software
rasterization: unavailable_software
video_decode: unavailable_software
video_encode: unavailable_software
webgl: enabled_readback
webgl2: unavailable_off
Memory (System)	63.88GB (48.61GB free)
Process Argv	C:\Program Files\Azure Data Studio\azuredatastudio.exe
Screen Reader	no
VM	0%
-------------------
Extensions: none
-------------------

**Comment by mortgagemetrix** [comment]
This problem also exists with "CREATE OR ALTER PROCEDURE/TABLE/VIEW". I also have the DROP TABLE IF EXISTS issue. Azure SQL.

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by sgreenfield** [comment]
This bug is still active.  It is not fixed at all.  The red squiggly lines stay on the screen for 20-30 seconds AFTER the issue has been corrected.  They are effectively lying to the user, and it's sadly a much better user experience to simply turn them off.
