### ISSUE TITLE
Report Issue UI doesnt work in Azure Data Studio

### ISSUE THREAD

**Issue by fatherjack** [Microsoft/azuredatastudio#2674]
Open Help menu
Choose Report Issue
Complete the Issue Reporter UI
Click the Preview on GitHub

**********************
Expectation is to arrive at GitHub in the New Issue UI
**********************
What actually happens is a 404 error from GitHub

the browser opens a url starting https://github.com/Microsoft/azuredatastudio/issues/new

but none of that exists beyond https://github.com/Microsoft

**Comment by HugoKornelis** [comment]
I have the exact same issue.

**Comment by yualan** [comment]
This seems to be working now, let us know if this problem persists.

**Comment by kburtram** [comment]
This was caused by the gap in docs publishing and repo rename.  Closing since the issue is now resolved.

**Comment by fatherjack** [comment]
yep, agreed, working now. Thanks
