### ISSUE TITLE
CTRL+INSERT does not behave like CTRL+C in results grid

### ISSUE THREAD

**Issue by johnradke** [microsoft/azuredatastudio#2675]
- SQL Operations Studio Version: 0.32.9

Pressing CTRL+INSERT while the grid has focus copies the current line in the SQL editor instead of the currently highlighted cell(s) from the grid.

This is an issue for people (like myself) who mouse left-handed and like to use alternate shortcuts for cut/copy/paste (SHIFT+DELETE/CTRL+INSERT/SHIFT+INSERT respectively) which are easier to execute with the right hand.

Steps to Reproduce:

1. Connect to any MSSQL database
2. Enter query `SELECT 'hello world' as Foo`
3. Highlight the cell containing `hello world`
4. Press CTRL+INSERT
5. Open Notepad
6. Press CTRL+V

EXPECTED RESULT: pastes "hello world" into Notepad
ACTUAL RESULT: pastes "SELECT 'hello world' as Foo" into Notepad

**Comment by alanrenmsft** [comment]
this is fixed now with latest insiders build.
