### ISSUE TITLE
Actual Execution Plan only shown for last query instead of for all.

### ISSUE THREAD

**Issue by HugoKornelis** [Microsoft/azuredatastudio#2676]
- SQL Operations Studio Version: Azure Data Studio 1.0.0

Steps to Reproduce:

1. Open a query window and connect it to any database.
2, Enter at least two queries in it. (Either with or without GO batch separator in between). E.g.:
SELECT name FROM sys.databases;
SELECT name FROM sys.columns;
3. Click Explain - two estimated execution plans show, as expected.
4. From the command palette, choose Run Current Query With Actual Plan. Only the execution plan for the last of the queries is displayed.

**Comment by kburtram** [comment]
@HugoKornelis thanks for reporting this bug.  We're tracking with issue https://github.com/Microsoft/azuredatastudio/issues/2663.
