### ISSUE TITLE
Sql Color Tab Issue

### ISSUE THREAD

**Issue by bcodernet** [Microsoft/azuredatastudio#2679]
Issue Type: <b>Bug</b>

I have my setting on Sql.ColorTabMode set to Fill. This works when I double click on a server and it opens the dashboard. However, as soon as I chose to open a new query then the color tab goes back to the default color instead of the colored tab that it was.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.87GB (23.36GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.32.7
import|Mic|0.1.0
profiler|Mic|0.1.5
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@bcodernet thanks for reporting this problem.  We're tracking this bug with https://github.com/Microsoft/azuredatastudio/issues/2670.  We'll have a fix in the next release.
