### ISSUE TITLE
Incorrect error message in Azure Data Studio when running a cursor

### ISSUE THREAD

**Issue by HugoKornelis** [microsoft/azuredatastudio#2680]
- SQL Operations Studio Version: Azure Data Studio
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Create a simple query that uses a cursor
declare c CURSOR for select * from sys.databases;
open c;
fetch next from c;
close c;
deallocate c;

2. Run the query

3. Expected results resultset from FETCH statement and "success" message

4. Actual results: resultset from FETCH statement and "error" message:
Query failed: Object reference not set to an instance of an object.

**Comment by alanrenmsft** [comment]
The issue has been fixed in the latest [Insiders Build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) and the upcoming release will include the fix. Please give it a try.
