### ISSUE TITLE
A failed query window retains it's execution context

### ISSUE THREAD

**Issue by olegk25** [Microsoft/azuredatastudio#2681]
Issue Type: <b>Bug</b>

1. Open a new query window (Ctrl+N). It will be named Query1
2. type in a query which would time out or run indefinitely
3. Cancel the query - fail - query is still running
4. Disconnect
5. Close the window
6. Open a new query window (Ctrl+N). It will be named Query1 again.
7. type in a query that will succeed and run
8. FAIL - query is not executed, the messages retain the information from steps 3 and 4

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.44GB (7.75GB free)|
|Process Argv|C:\Program Files\SQL Op

**Comment by anthonydresser** [comment]
I can't seem to repro; can you verify if you still experience this?

**Comment by kburtram** [comment]
@anthonydresser I just checked and could repro on the latest build either.  Let's close for now.  @olegk25 please let us know if you're still impacted by this issue on current builds.

**Comment by olegk25** [comment]
Hello,
I confirm, the issue is resolved.
Thank you!
