### ISSUE TITLE
Edit Data: Null indicator behaves inconsistently

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#2685]
- SQL Operations Studio Version:

Steps to Reproduce:
1. Open the Edit Data window for a table with some null fields

issue 1: unlike other null values, the null values in the last row are not Italic

issue 2: click on a null cell that is in Italic and then move the focus away without changing it

Expected: the null string is in Italic
Actual: the null string is not in Italic and you have to press ESC in that row to make it Italic again.

**Comment by kburtram** [comment]
This should be addressed by #8773.
