### ISSUE TITLE
Export to CSV, JSON and Excel no longer works

### ISSUE THREAD

**Issue by EmanNo1** [Microsoft/azuredatastudio#2687]
Issue Type: <b>Bug</b>

Open any query that results in records from DB. Select export to CSV or JSON or Excel. In the save dialog, choose the Desktop folder and keep default file name. Click Save. (Dialog closes, no file written).

Note 1: I rebooted the machine and was able to reproduce the issue
Note 2: I have tried different export types and different save locations
Note 3: This feature worked last week when the app was first installed.
Note 4: There are no entries in the syslog file regarding a save or export operation

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:33:15.959Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 2810)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.70GB (4.74GB free)|
|Process Argv|/usr/share/sqlops/sqlops --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@EmanNo1 this issue should be fixed in today's build available at https://github.com/Microsoft/azuredatastudio/releases/tag/1.0.0.  Please reactive if the issue persists with this build.  Thanks for reporting this issue!
