### ISSUE TITLE
hot key, for table properties in sql server management studio is alt+f1.  it would be nice, if that is available in azure data studio.

### ISSUE THREAD

**Issue by digish777** [microsoft/azuredatastudio#2692]
- Azure Data Studio Version: 1

Steps to Reproduce:
hot key, for table properties in sql server management studio is alt+f1.  it would be nice, if that is available in azure data studio.

**Comment by R-i-c-h-B** [comment]
> * Azure Data Studio Version: 1
> 
> Steps to Reproduce:
> hot key, for table properties in sql server management studio is alt+f1. it would be nice, if that is available in azure data studio.

I'm slightly confused I thought we were in SQL OPS STUDIO... so apologies if the following makes no sense...

This is broadly implemented already... it is notable that on linux things like alt+f1 already do... stuff, so on a cross platform product like this some of the keybinding things will be a little more hard work than normal.

However, if you go to User Settings and search for workbench.action.query.shortcut you can set what you like in there for them.  
Then if you go to Keyboard Shortcuts you can work out some new shortcuts to go with them, or see the ones that are currently assigned.

Its a little ugly having the 2 seperate configs, but seems to work ok.

Cheers :)

**Comment by lkommuri** [comment]
> > * Azure Data Studio Version: 1
> > 
> > Steps to Reproduce:
> > hot key, for table properties in sql server management studio is alt+f1. it would be nice, if that is available in azure data studio.
> 
> I'm slightly confused I thought we were in SQL OPS STUDIO... so apologies if the following makes no sense...
> 
> This is broadly implemented already... it is notable that on linux things like alt+f1 already do... stuff, so on a cross platform product like this some of the keybinding things will be a little more hard work than normal.
> 
> However, if you go to User Settings and search for workbench.action.query.shortcut you can set what you like in there for them.
> Then if you go to Keyboard Shortcuts you can work out some new shortcuts to go with them, or see the ones that are currently assigned.
> 
> Its a little ugly having the 2 seperate configs, but seems to work ok.
> 
> Cheers :)

Worked for me! Thanks :)

**Comment by digish777** [comment]
alt+ f2 in windows for table properties. thanks.

**Comment by alanrenmsft** [comment]
@digish777 have you figured it out? I am not sure what is the ask here, what do you mean by `Table properties`?

**Comment by alanrenmsft** [comment]
closing due to no response.
