### ISSUE TITLE
Sometime, sql operations studio stop work, due to sql syntax error.

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#2694]
Issue Type: <b>Bug</b>

I click on the run, the query does not run (Not Responding), no error message in the messages tab

I then close the sql operation studio, then re-launch.

I then run the same query, it show me the error.

Started executing query at Line 1
Msg 4104, Level 16, State 1, Line 5 The multi-part identifier "c.OFFICEID" could not be bound.
Msg 207, Level 16, State 1, Line 11 Invalid column name 'office'.
Total execution time: 00:00:00.108

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (9.08GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
alwayson-insights|mat|0.2.1
agent|Mic|0.32.7
import|Mic|0.1.0
profiler|Mic|0.1.5
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by uniqalex** [comment]
@datauduong 
looks like you didn't choose target database for query and it uses master, where don't exists objects from your query.
I advise you to follow what database is chosen now:
![image](https://user-images.githubusercontent.com/22915408/46022191-d0a2a380-c0ea-11e8-9042-1cb1e60d41d6.png)

**Comment by datauduong** [comment]
No, the query was working, therefore it is not the target database. 
This problem was also occurred in the previous month release. Therefore

I then updating and running the query at some point the editor stop working due to my Syntax Error.
Editor not showing the error, then nothing will work (click on run or execute query is not working due to syntax error).

**Comment by cheenamalhotra** [comment]
I haven't reproduced this issue lately, so will proceed to close.
If it reoccurs, please let us know and we can reopen issue to investigate.
