### ISSUE TITLE
Is it possible to run SQL Operations Studio on Samsung Dex ?

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#2696]
- Azure Data Studio Version:

Steps to Reproduce:

**Comment by kburtram** [comment]
@datauduong sorry, we only x64 devices running Windows, macOS or Linux.

**Comment by datauduong** [comment]
kburtram, I have installed Samsung Linux Dex, is it possible run now ?

**I am getting the following error:**
dextop@localhost:~/Downloads$ sudo dpkg -i ./azuredatastudio-linux-1.2.4.deb 
[sudo] password for dextop: 
dpkg: error processing archive ./azuredatastudio-linux-1.2.4.deb (--install):
 **package architecture (amd64) does not match system (arm64)**
Errors were encountered while processing:
 ./azuredatastudio-linux-1.2.4.deb

Thanks.
