### ISSUE TITLE
Spatial tab (map viewer) when results include spatial column

### ISSUE THREAD

**Issue by jkirkland-cityoflewisville-com** [Microsoft/azuredatastudio#2697]
Issue Type: <b>Feature Request</b>

Please add a "spatial" tab (or spatial viewer in the "Chart" tab) for viewing results that include a spatial column

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/Microsoft/azuredatastudio/issues/267.  Thanks for the suggestion!
