### ISSUE TITLE
Messages window does not respect newlines

### ISSUE THREAD

**Issue by moswald** [Microsoft/azuredatastudio#2699]
Issue Type: <b>Bug</b>

`PRINT 'A' + char(13) + char(10) + 'B'` should output
```
A
B
```
Instead, we get
`A B`

This makes it difficult to work with really large dynamic queries that I output to the Messages window for debugging purposes.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.18234

**Comment by thesushil** [comment]
Query results window doesn't respect new line either. Change print to select in above and we see same issue.

**Comment by anthonydresser** [comment]
should be in the next release, #2935
