### ISSUE TITLE
Feature Request - Add SQL Server Agent Section

### ISSUE THREAD

**Issue by bush3102** [microsoft/azuredatastudio#27]
- SQL Operations Studio Version:

Version 0.23.6
Commit 8a3011756318a2ded1e6e84332230a2b2bf9c544
Date 2017-11-05T22:46:14.815Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Below the 'Server Objects' section have a section that shows the SQL Server Agent section that includes jobs, alerts, operations, etc.

![2017-11-15_16-19-27](https://user-images.githubusercontent.com/14627969/32861006-6fc52652-ca21-11e7-881f-749ca5444abd.jpg)

Steps to Reproduce:

**Comment by joshobud** [comment]
I agree with this much needed feature.  I downloaded the tool today and have been playing with the options.  I really like the customization we can do within the tool.  To my disappointment I found no SQL agent present.  Please add this feature.

**Comment by kburtram** [comment]
@bush3102 SQL Agent support is on our GA roadmap, though we still need to work through the details of what this will look like exactly.

**Comment by nick-wahlin** [comment]
Good to hear this is on the roadmap. I'm really enjoying SOS, but without SQL Sever Agent functionality I will have to stick with SSMS.

**Comment by bush3102** [comment]
@kburtram I apologize for the crudeness of the screenshot, but I am so excited that it is on the GA roadmap.  Please reach out to me (email or Twitter: @jeremyfegenbush) if you need any help testing.

**Comment by erickangMSFT** [comment]
@bush3102 Thanks for offering your help! Certainly we will reach out to you very soon. We want to prioritize the features and set iterative implementation and release.

**Comment by yualan** [comment]
We are working on the SQL Agent extension, and we would appreciate community feedback on the initial UX designs. Please provide your feedback in this issue: https://github.com/Microsoft/sqlopsstudio/issues/750

**Comment by justPaulo** [comment]
Any ETA for SQL Server Agent on SQL Ops Studio ?

**Comment by SebastianPfliegel** [comment]
@justPaulo, try the new sqlops version, it features extensions. The SQL agent extension is already available.

**Comment by justPaulo** [comment]
@SebastianPfliegel I'm already using latest version available (Version 0.26.7) on Linux. No extensions present though. How can I retrieve and install such extension?
Thanks

**Comment by SebastianPfliegel** [comment]
That's not the current release. This one is: https://github.com/Microsoft/sqlopsstudio/releases/tag/0.27.4

The page also mentions on how to obtain the extension.

**Comment by justPaulo** [comment]
Link resolves to March Public Preview (0.27.3) not 0.27.4 (although tagged as 0.27.4.)
I had to uninstall previous version 0.26.x to be able to use 0.27.3 which presents 2 extensions (sp_whoisactive and Server Reports) but no SQL Server Agent. Any ideas ?

**Comment by SebastianPfliegel** [comment]
@justPaulo, yeah it looks like they removed it from the extension market place. Don't know why, probably is was too bugged. @kburtram, any idea?

**Comment by kburtram** [comment]
@SebastianPfliegel we have different extension feeds for the `insiders` vs. `stable` builds.  Agent extension is only available in the `insiders` build since it's currently too buggy for `stable`.  We'll try to include it in April `stable` assume at least the Jobs View and Job History View are ready.

The VSIX is available at `https://sqlopsextensions.blob.core.windows.net/march-extensions/agent/agent-0.27.0.vsix` and can be manually installed on March `stable`.  I'll produce a new `insiders` build as soon as we get the VS Code 1.21 source code merged into `master`.  There are several Agent extension improvements that have gone in since we snapped to produce the VSIX, so those should be in the next `insiders` build as well.

**Comment by justPaulo** [comment]
Hi @SebastianPfliegel @kburtram 
I was able to install the SQL Server Agent extension from the .vsix file, thanks.
However, it doesn't show at the bottom of the object tree explorer as usual (nor anywhere else). Guess I'll have to wait for next stable releases.

**Comment by SebastianPfliegel** [comment]
Hey @justPaulo, it's not listed in the object explorer. Just right click on a server and press Manage. It's listed next to Home as a tab.

**Comment by justPaulo** [comment]
Spotted at last :-), thanks @SebastianPfliegel.

**Comment by zixindh** [comment]
@kburtram

**Comment by kburtram** [comment]
I'll close this now based on the availability of the SQL Agent extension.  Please let us know if there are any bugs encountered working with that extension.
