### ISSUE TITLE
Installed extensions don't appear as tabs on your management dashboard

### ISSUE THREAD

**Issue by Blinkenn** [Microsoft/azuredatastudio#2702]
Installed extensions don't appear as tabs on your management dashboard
https://docs.microsoft.com/en-us/sql/azure-data-studio/extensions?view=sql-server-2017
Using version 1.0.0 connecting to SQL 2016 Standard (13.0.5201.2), installed and enabled SQL Server Agent 0.33.0 & Server Reports 0.1.3.
This is a fresh install of Azure Data Studio after uninstalling SQL Ops Studio.

Issue: There is not a + sign when managing the connection to open dashboard extensions menu.
The developer tools do not have any errors, only 4 SimpleKeybinding warnings.

**Comment by Blinkenn** [comment]
> setting "workbench.enablePreviewFeatures": true  

that was it, thanks.

**Comment by kburtram** [comment]
Closing based on above replies.  We're looking at how to make the preview feature switch more obvious.

**Comment by nicknijenhuis** [comment]
Why does the preview switch even have to be enabled? Since you have to install an extension, doesn't that mean that you explicitly agree with it being enabled?
