### ISSUE TITLE
Grid Result cleared when switch to Keyboard Shortcut Listing

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#2704]
Issue Type: <b>Bug</b>

Step to Re-Procedue:
1. run a query
2. press ctrl+shift + r (accidentally pressed, suppose to press win+shift + r)
3. press ctrl + k + ctrl + s (keyboard shortcut)
4. then close the keyboard short cut tab.
you'll then see the grid result is empty and SQL Operation Studio no longer work (you can't run the query anymore).
you'll have to close and re-open the program.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.21GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
alwayson-insights|mat|0.2.1
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
server-report|Mic|0.1.3
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by anthonydresser** [comment]
I'm not seeing this; can you verify you still experience this?
