### ISSUE TITLE
Database backup fails

### ISSUE THREAD

**Issue by cragsdell** [Microsoft/azuredatastudio#2708]
- Azure Data Studio Version:  1.0.0

Steps to Reproduce:

1. Connect to MS-SQL database
2. Attempt a backup
3. Backup fails and posts this error message: Cannot write property CompressionOption. This property is not available on SQL Server 2005.

I have tried all options for compression, including "Do not compress backup".

**Comment by kburtram** [comment]
@cragsdell sorry, Azure Data Studio only officially support SQL Server 2014+.  Please reactive if the issue persists on a SQL Server 2014+ instance.
