### ISSUE TITLE
Improvement: Do not set automatically generated SQL queries such as "Select Top 1000" as modified by default in the Editor

### ISSUE THREAD

**Issue by theBull** [Microsoft/azuredatastudio#2711]
- Azure Data Studio Version: Version 0.32.8 (0.32.8) Sql Ops Studio for Mac

Problem:
* I need to quickly scan the contents of multiple tables in a database I manage, or have access to.
* I tend to right-click the tables and select `Select Top 1000` for a quick preview (works great)
* I often create several editor tabs rather quickly in my search for data
* I hit a point where I want to clean out my workspace and close irrelevant tabs, so I try to right-click a tab and choose `Close All`
* I'm forced to confirm a series of save prompts because the editor tabs created for the auto-generated `Select Top 1000` commands are marked as modified, even if I make no modifications to the provided code.

Steps to Reproduce:
* (assumes connection to a SQL database with populated tables)
* Connect to a SQL database
* In the Servers panel, expand the connected database
* Expand Tables
* Right-click on a table > Select Top 1000
* A new tab opens in the main editor with the query inserted into the command area, and the tab for the editor shows something to the effect of `SQLQuery1`, and an indicator showing that the automatically generated script in the new editor has been modified (does not show an `x` close icon).
* Hovering over the modified icon will display the `x`
* Clicking the `x`causes a prompt to save changes
--- Alternatively ---
* You've right-clicked several different tables and chosen to `Select Top 1000`
* You have several tabs opened, all marked as modified by default
* Right-click one of the tabs > `Close All`
* A prompt appears to save changes for every opened tab automatically generated, even if you have made no changes.

Expected Outcome:
* When an automatically generated query is created, and a new editor tab is opened, the file should not be marked as modified.
* Once you've opened one or more auto-generated queries, you should be able to `Close`, or `Close All` without a prompt. There is no need to be prompted to save a query that you have easy access to by subsequently right-clicking the appropriate table and selecting the auto-generated query function available, in this case `Select Top 1000`. 
* I should only be prompted to save a file that I've created or modified in some way. There is no need to prompt for saving an auto-generated command that is easily and more commonly accessible by right-clicking the desired resource.
* If I really want to save the auto-generated script, I can explicitly choose to do so easily, I see no benefit in being prompted to do so; in fact, it is the contrary.

I thought I'd share my feedback on your product, which is great! Thank you all for your hard work and dedication. No hard feelings if this idea gets shot down. Your time is much appreciated.

Cheers!

**Comment by theBull** [comment]
I've taken a gander through the preferences file in the various sections, although I didn't find any applicable settings:
* Editor
* Files
  - it's not `autoSave`, as I don't want to save automatically generated queries
  - it's not `hotExit` (I don't think), as it's not applicable to exit, it's applicable to explicitly closing
* SQL Editor

**Comment by kburtram** [comment]
@theBull thanks for the suggestion.  We made a change to have generated SQL scripts created as "not dirty" so there won't be Save prompt in the repro scenario. This is available in the latest insiders builds and will be in the Feb release.  The following setting will switch back the previous behavior `"sql.promptToSaveGeneratedFiles": true`

**Comment by theBull** [comment]
Sounds great. Thanks @kburtram!
