### ISSUE TITLE
"DROP TABLE IF EXISTS" statement is detected as an error

### ISSUE THREAD

**Issue by lberrocal** [microsoft/azuredatastudio#2712]
Issue Type: <b>Bug</b>

Connect to a database that supports the statement.
Build the statement for example:

drop table if exists #temp
select 1 as id into #temp;

The query will execute correctly but the editor detects the "drop table if exists" statement as it being erronous.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (8.54GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
I am seeing this when I connect to Azure SQL.  But not when I connect to SQL Server 2017.  Perhaps there is server version check issue in the T-SQL Parser.

**Comment by Charles-Gagnon** [comment]
Closing this as I'm not able to repro this - it isn't flagged as an error on either on-prem or Azure.

@kburtram - If you're still seeing this behavior let me know
