### ISSUE TITLE
Unable to connect to SQL Server 2000

### ISSUE THREAD

**Issue by iravinandan** [Microsoft/azuredatastudio#2713]
- Azure Data Studio Version: V1

Steps to Reproduce:

1. Sql Server 2000 instance is in AWS 
2. Connect using AzureData Studio(Mac OS Version) to this instance 
3. Error - The SQL Server instance returned an invalid or unsupported protocol version during login negotiation

**Comment by kburtram** [comment]
@iravinandan unfortunately Azure Data Studio doesn't support SQL Server 2000.  We officially support SQL Server 2014+, though we'd expect SQL Server 2008 R2+ to work fine.  Sorry for the inconvenience.
