### ISSUE TITLE
Is there a way to control how sql is formatted ?

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#2714]
Issue Type: <b>Feature Request</b>

I can't find where you can set the formatting. 

It would be nice to be able to select different style of sql format.

Thanks.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@datauduong we provide the following options to control SQL formatting.  Are there additional options you think we should provide?

![image](https://user-images.githubusercontent.com/599935/47054237-96667800-d165-11e8-80de-a1dadab64ffb.png)

**Comment by datauduong** [comment]
Thank you kburtram for the settings, I have used the last 2 settings:
placeCommasBeforeNextStatement
placeSelectStatementReferencesOnNewLine

placeSelectStatementReferencesOnNewLine (Adding a space after commas would be nice).

Notice a bug in the format, when the sql already format with "placeSelectStatementReferencesOnNewLine":true, 
Action> Reformat SQL
select col1
, col2
, col3

Then add the setting "keywordCasing":true, 
the select statement, the column name now have extra new line per column name.

select col1

, col2

, col3

**Comment by kburtram** [comment]
Closing this older "question" issue.  Please log a new issue if you are still experiencing issue with the T-SQL formatter.
