### ISSUE TITLE
Failed to start Import serviceError

### ISSUE THREAD

**Issue by SebastianPfliegel** [microsoft/azuredatastudio#2716]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Install SQL Server Import extension
2. (Re-)start Azure Data Studio
3. Error notification: `Failed to start Import serviceError: Request error: Error`
4. Execute task `Flat File Import: Import wizard` via `Ctrl + I` triggers this error: `command 'flatFileImport.start' not found`

**Comment by SebastianPfliegel** [comment]
Well, it's a layer 8 issue ...

I forgot to set the proxy in my new installation. Therefore the download of the additional components failed. The error description might be better, though.

**Comment by kburtram** [comment]
@SebastianPfliegel I'll leave this open to access if we can do anything to improve the error message, or be more helpful here.

**Comment by carolinegarrad1998** [comment]
Not sure if this is the same thing but I'm having an error when trying to launch the import wizard. I have the option when I right click on a database to select the import wizard, but nothing happens when I press it. I tried doing the shortcut (control I) and this gave me an error (screenshot attached). Please let me know if there was a fix for this which I have missed.
<img width="484" alt="screenshot 2019-02-12 at 10 34 37 pm" src="https://user-images.githubusercontent.com/47578467/52672667-6a41e480-2f16-11e9-91ef-3eea8bacb2d9.png">

**Comment by SebastianPfliegel** [comment]
Hi @carolinegarrad1998, I mentioned earlier that I received this error message due to lacking the additional components which get downloaded after installing and reloading the extension. The download of these components failed for me as I didn't set up a proxy.

**Comment by carolinegarrad1998** [comment]
Okay thank you.

**Comment by SebastianPfliegel** [comment]
@carolinegarrad1998, did this the trick for you?

**Comment by xNaii** [comment]
I get on open up `Failed to start Import serviceError: Request error` and after trying to get import wizard getting  `command 'flatFileImport.start' not found` on fresh install of Azure Studio 1.5.2 with this extension

**Comment by SebastianPfliegel** [comment]
@xNaii, you might have the same problem I had. As soon as you installed the extension Azure Data Studio tries to download additional dependencies. This might fail if you have a corporate proxy and you haven't configured Azure Data Studio to use this proxy.

**Comment by xNaii** [comment]
Yep, got it

**Comment by riddhi95** [comment]
Please open the connection. Do a right click on the database. Click on import. Do the import. You will see the additional files get installed. Next time onwards you will get import wizard when you press Cntrl + I shortcut

**Comment by rmvp** [comment]
@riddhi95 I have followed your suggestions and still have issue.

![Screenshot from 2019-09-23 14-35-37](https://user-images.githubusercontent.com/30558303/65456868-e63ace00-de0f-11e9-91a2-0074eb288022.png)

**Comment by Charles-Gagnon** [comment]
Could you please open the developer console (Help -> Toggle Developer Tools) and then go to the **Console** tab and include any error messages you're seeing there?

**Comment by rmvp** [comment]
@Charles-Gagnon 

![Screenshot from 2019-09-23 15-30-17](https://user-images.githubusercontent.com/30558303/65460345-441ee400-de17-11e9-94ec-962bf94dd5f9.png)
![Screenshot from 2019-09-23 15-30-00](https://user-images.githubusercontent.com/30558303/65460346-441ee400-de17-11e9-9b9a-f69874bbac2d.png)

**Comment by Charles-Gagnon** [comment]
Hmm, nothing too useful. Could you also look in `~/.azuredatastudio/extensions/microsoft.import-0.10.0/` and see if you have a flatfileimportservice folder there? And does it contain anything if it is?

If it isn't then could you try 

1. Closing ADS
2. Manually downloading https://sqlopsextensions.blob.core.windows.net/extensions/import/osx.tar.gz and then extracting the contents of that folder into `~/.azuredatastudio/extensions/microsoft.import-0.10.0/flatfileimportservice` 
3. Restarting ADS 

And seeing if that works?

**Comment by rmvp** [comment]
@Charles-Gagnon 
I think that the content of the folder in the link is for OSX. I am running Ubuntu 18.04
when I extract the content into ~/.azuredatastudio/extensions/microsoft.import-0.10.0/flatfileimportservice and I restart ADS, it installs Flat File Import Service service to ~/.azuredatastudio/extensions/microsoft.import-0.10.0/flatfileimportservice/Linux/0.0.2

**Comment by rmvp** [comment]
Correct,
I closed ADS
I deleted the Linux folder from ~/.azuredatastudio/extensions/microsoft.import-0.10.0/flatfileimportservice
Then when I re-start ADS, I can see in the Output window the installation script executes and creates /Linux/0.0.2 folders inside the flatfileimportservice.

![Screenshot from 2019-09-24 10-38-11](https://user-images.githubusercontent.com/30558303/65527112-c2cb5e00-deb7-11e9-92a2-505b14aea0ca.png)

**Comment by jintolonappan** [comment]
> Hmm, nothing too useful. Could you also look in `~/.azuredatastudio/extensions/microsoft.import-0.10.0/` and see if you have a flatfileimportservice folder there? And does it contain anything if it is?
> 
> If it isn't then could you try
> 
> 1. Closing ADS
> 2. Manually downloading https://sqlopsextensions.blob.core.windows.net/extensions/import/osx.tar.gz and then extracting the contents of that folder into `~/.azuredatastudio/extensions/microsoft.import-0.10.0/flatfileimportservice`
> 3. Restarting ADS
> 
> And seeing if that works?

These instructions helped to get the wizard _start_. However, it didnt show any preview and got stuck with a throbber when clicked on 'Next'.

OS: Mac OS Mojave Ver 10.14.6
ADS:  1.8.0

ADS Process Explorer shows 0 CPU for related service.
Related Log file:
[20200325T112022.zip](https://github.com/microsoft/azuredatastudio/files/4382816/20200325T112022.zip)

Related issues: #9728

**Comment by duyn9uyen** [comment]
I'm on a Mac with OS Catalina. Right-click context does not reveal the Import wizard. 
> ^i

Brings up the wizard but I am not able to select my json file.

Version: 1.16.1
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:06:16.901Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.4.0

**Comment by irshad-bluecast** [comment]
Any update on this?

**Comment by carlosal1015** [comment]
On Arch Linux, open ADS, first from Extensions (Ctrl + Shift + X) install SQL Server Import. Close ADS. Then:

```sh
$ mkdir /tmp/tmp_dir
$ cd /tmp/tmp_dir
$ wget https://sqlopsextensions.blob.core.windows.net/extensions/import/linux-x64.tar.gz
$ tar -xvzf linux-x64.tar.gz
$ cp -R /tmp/tmp_dir/* ~/.azuredatastudio/extensions/microsoft.import-0.14.0/flatfileimportservice/Linux
$ rm ~/.azuredatastudio/extensions/microsoft.import-0.14.0/flatfileimportservice/Linux/linux-x64.tar.gz
```
Open again ADS, and may works Import Wizard.

Cheers.

**Comment by aasimkhan30** [comment]
There were some missing awaits that was causing this issue. Closing this bug for now.

**Comment by craibuc** [comment]
The Cisco AnyConnect VPN was affecting the installation of the additional components.

I temporarily stopped the VPN connection, then started the extension (`ctrl + shift + p`; `Flat File Import: Import Wizard`).  

After a momentary pause, the additional components were installed:
```
Downloading https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.7/win-x64.zip
(37,917 KB)....................Done downloading Flat File Import Service
Installing Flat File Import Service to https://sqlopsextensions.blob.core.windows.net/extensions/import/service/0.0.7/win-x64.zip
Installed Flat File Import Service
```

**Comment by kawak1320** [comment]
> On Arch Linux, open ADS, first from Extensions (Ctrl + Shift + X) install SQL Server Import. Close ADS. Then:
> 
> ```shell
> $ mkdir /tmp/tmp_dir
> $ cd /tmp/tmp_dir
> $ wget https://sqlopsextensions.blob.core.windows.net/extensions/import/linux-x64.tar.gz
> $ tar -xvzf linux-x64.tar.gz
> $ cp -R /tmp/tmp_dir/* ~/.azuredatastudio/extensions/microsoft.import-0.14.0/flatfileimportservice/Linux
> $ rm ~/.azuredatastudio/extensions/microsoft.import-0.14.0/flatfileimportservice/Linux/linux-x64.tar.gz
> ```
> 
> Open again ADS, and may works Import Wizard.
> 
> Cheers.

you Sir, is the real MVP, BTW!

**Comment by Liriel** [comment]
any news on this? Still got this issue on my machine w/ import service 0.0.9...

Version: 1.39.0
Commit: 9fdb2161d49b4d4ab6798809faa042a898ca2eae
Date: 2022-08-20T01:35:35.924Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Linux x64 5.10.135-gentoo

**Comment by Zick-del** [comment]
yo guys, still got that issue. 
ADS
Version: 1.40.0 (Universal)
Commit: 3fbaa3de931ef433090fe3deb8c89cba99d7952b
Date: 2022-11-11T22:47:49.772Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Darwin arm64 22.1.0


Macbook Air
Chip: M1
macOs: Ventura 13.0

<img width="1440" alt="Screenshot 2022-11-21 at 19 52 48" src="https://user-images.githubusercontent.com/69795259/203136402-bccee1bd-f8b1-43c3-984b-095c91e1f795.png">

**Comment by hcristianowork** [comment]
I also am getting the error "Failed to start Flat File Import Service: {1}"

Version: 1.40.2 (system setup)
Commit: 661384637db384fe5d4e6224069adbe708580b16
Date: 2022-12-22T22:17:02.658Z
VS Code: 1.67.0
Electron: 17.4.11
Chromium: 98.0.4758.141
Node.js: 16.13.0
V8: 9.8.177.14-electron.0
OS: Windows_NT x64 10.0.17763

![Capture](https://user-images.githubusercontent.com/76495639/210865731-12d545b0-a5e3-4a32-9f54-494ad48f8e17.PNG)

**Comment by olaola-prog** [comment]
I also have the same issue. couldn't start client flat file import service.
