### ISSUE TITLE
XML Column result click formatting

### ISSUE THREAD

**Issue by nbred5** [Microsoft/azuredatastudio#2717]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Select data from a table that contains an xml column
Click on the data in the results grid for the xml column
The xml for the column is displayed in a new tab  but is no longer formatted.

![image](https://user-images.githubusercontent.com/12713921/46216270-18b60600-c337-11e8-8d06-dcbbe966b8d0.png)

In previous versions of SQ Operrations studio the xml was formatted.

![image](https://user-images.githubusercontent.com/12713921/46216322-371c0180-c337-11e8-960b-cb5061fe99b7.png)

**Comment by drmcclelland** [comment]
In addition to the "unformatted" XML, it is also "unformattable" - pressing the Shift+Alt+F key combination in the new tab displays the message:

![image](https://user-images.githubusercontent.com/6124858/47018401-48785280-d11a-11e8-9205-78593b05c056.png)

**Comment by peterlukerow** [comment]
Since there is no method do this - I heartily concur with this. I had to switch back to SSMS in order to do this, uber sigh!

**Comment by kburtram** [comment]
I'll take a look at why this regressed.  It happened the last time we merged VS Code source code.

**Comment by kburtram** [comment]
The next insiders build will contain a fix for this issue.
