### ISSUE TITLE
When using CTRL + TAB, all the line goes left, whereas in SSMS only the tabs between to words is removed

### ISSUE THREAD

**Issue by TyTyMu** [Microsoft/azuredatastudio#2726]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1.Opening a file
2.Write [Tab][Tab]Select[Tab]COLUMN1,[Tab][Tab]COLUMN2
3.Put the cursor before COLUMN2
4.Do CTRL + TAB

Expected result : the <Tab> near COLUMN2 is removed
[Tab][Tab]Select[Tab]COLUMN1,[Tab]COLUMN2

Actual result : the <Tab> at the beginning of the line is removed
[Tab]Select[Tab]COLUMN1,[Tab][Tab]COLUMN2

**Comment by kburtram** [comment]
This is the "by design" editor functionality we pick up from VS Code.  Please open an issue upstream and we'll pull it in with our next merge.

**Comment by TyTyMu** [comment]
Link to the issue in VSCODE : https://github.com/Microsoft/vscode/issues/60825
