### ISSUE TITLE
DB connections with AAD and MFA enabled

### ISSUE THREAD

**Issue by jschrap** [Microsoft/azuredatastudio#2728]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:
Add a new connection. Try to connect with Azure SQL using AAD account with MFA. Not possible to connect.

**Comment by dbrtly** [comment]
+1

**Comment by stevenjpbrown** [comment]
+1

**Comment by kburtram** [comment]
We're tracking this in https://github.com/Microsoft/azuredatastudio/issues/13.  This is planned for the December release.
