### ISSUE TITLE
Tab coloring has stopped working in 1.0

### ISSUE THREAD

**Issue by toddlindner** [Microsoft/azuredatastudio#2729]
Issue Type: <b>Bug</b>

In sql ops studio versions, this setting used to color the tab with the server group color
    "sql.tabColorMode": "fill",

It no longer does.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 6.1.7601

Extensions: none

**Comment by kburtram** [comment]
This is fixed in the latest insiders build at https://github.com/Microsoft/azuredatastudio/releases and will be in the stable build later this week.
