### ISSUE TITLE
Minimum system requirements need to be documented on download page

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#2732]
Minimum system requirements need to be documented on the Azure Data Studio download page https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017.  Specifically, we need to note that 1-Core environments are not supported.

**Comment by kburtram** [comment]
@yualan are we on-track for this to be published with the Nov. release?

**Comment by yualan** [comment]
Hi Karl, I was planning to include this in yesterday's merge, but decided to first write it up and get approval from team on it. Let me draft something.

From my understanding from last thread, we should stick with recommended system requirements?

**Comment by yualan** [comment]
![image](https://user-images.githubusercontent.com/30873802/47876561-ca34d500-ddd6-11e8-80cb-ec16b392057e.png)

PR is out, should be merged by EOD today.

**Comment by yualan** [comment]
https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017#recommended-system-requirements
