### ISSUE TITLE
Install from VSIX then reload doesn't always complete installation

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#2737]
- Azure Data Studio Version: 1.0
This has been reported by a number of PMs testing the SQL Server 2019 Preview extension

Steps to Reproduce:

1. Download the extension and Install from VSIX
2. Wait until prompted to reload Azure Data Studio
3. On reload go to the Extensions view and see it still shows "Reload" as required

Workaround: fully quit and reopen Azure Data Studio fixes the issue.

**Comment by alanrenmsft** [comment]
@kevcunnane I am not able to reproduce this issue either, are you still seeing this in the latest insider build?
