### ISSUE TITLE
Message pane cannot be dragged down easily

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#2739]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Run a query like SELECT * FROM sys.databases
2. When messages pane pops up below results grid, it cannot be dragged down to view more results. 

This has been reported in a Azure SQL DW demo. I know they can set a hotkey like Ctrl+R to minimize entire pane, but having the ability to control size of messages pane may allow the user to see more results.

A mitigation is to drag the whole results pane down until messages is flat. This may be a limitation with our current grid implementation, so any feedback appreciated if this is truly a bug or a feature request given grid limitations.

**Comment by anthonydresser** [comment]
I don't understand the ask here, dragging the results pane down is the same has affect has controlling the size of the message panes?
