### ISSUE TITLE
Maximum setlocal recursion level reached

### ISSUE THREAD

**Issue by b25** [microsoft/azuredatastudio#274]
- SQL Operations Studio Version:
I using node 8.9.1 (windows 10 pro Version 1703 ,Intel cpu 5820k 32 gb ram)
a infinite loop is printing into console 
Maximum setlocal recursion level reached

Steps to Reproduce:
run **npm.bat install from scripts directory**

I installed node 7.90 and npm 4.2 the same

**seems the issue was running inside of the  Scripts folder**
running from repository root scripts/npm.bat install  stop showing that error

**Comment by misha130** [comment]
The wiki mentions running 
scripts\npm.bat install
It doesn't mention cd scripts && npm.bat install.
You might classify this as working as intended.

**Comment by kburtram** [comment]
We should update the documentation to clarify `scripts\npm.bat install` needs to be run from the root directory.

**Comment by kburtram** [comment]
This bug isn't relevant to current build steps.  Thanks for reporting this issue!
