### ISSUE TITLE
Enhancment : Additional authentication methods

### ISSUE THREAD

**Issue by lakani** [Microsoft/azuredatastudio#2740]
It would be nice if you provided more additional authentication methods like the ones in Visual Studio 2017
For listing purpose (Active Directory Password authentication, Active Directory Integrated authentication, 
Active Directory interactive authentication)

![untitled](https://user-images.githubusercontent.com/9746768/46340514-46a09080-c63e-11e8-93cf-174409f4e1b2.png)

**Comment by kburtram** [comment]
We're tracking AAD in #13. That is planned for the December release.  Please add additional comments to that issue if it doesn't capture your suggestion.  Thanks!

**Comment by sergiokoval** [comment]
doesn't seem it supports "Azure Active Directory - Password" type of authentication. Any plans to have this feature as well?
