### ISSUE TITLE
Disabling GIT plugin breaks database connection

### ISSUE THREAD

**Issue by lxscaut** [microsoft/azuredatastudio#2741]
- Azure Data Studio Version: 1.0

Steps to Reproduce:

1. Go to user settings and set git.enabled = false
2. Try to connect to any sql server --> it won't work
3. Re-enabling the GIT plugin restores functionality.

**Comment by kburtram** [comment]
@sammyxx I was able to repro this.  In order to prioritize, what is the use case where you want to disable git?

**Comment by kburtram** [comment]
This appears to be fixed in the latest build.  Please let us know if you're still experiencing this issue.
