### ISSUE TITLE
Setting sql.tabColorMode does not work

### ISSUE THREAD

**Issue by lmfs** [Microsoft/azuredatastudio#2742]
Issue Type: <b>Bug</b>

Setting `sql.tabColorMode` to `fill` or `border` in user settings does not change the title tabs to their respective group color.

1. Create a new server group with a specific color
2. Add a connection to a SQL Server and specify group above
3. Open a connection to the server in the created group
4. `sql.tabColorMode` = [ `fill` | `border` ] => no colors on window tab

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3930K CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (6.95GB free)|
|Process Argv|C:\__APPS\azuredatastudio-windows-1.0.0\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by AisoRed** [comment]
I'm experiencing this issue as well.


```
SQL Operations Studio

Version 0.32.9
Commit 8004776eff330e8980b473b6a2f6faf607164005
Date 2018-09-19T05:11:56.160Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
```

**Comment by kburtram** [comment]
@MattIrv any ideas what may have broke here?  I think this regressed when we updated to VS Code 1.26.1 source code.

**Comment by MattIrv** [comment]
This is fixed in our code now and will be included in the next release
