### ISSUE TITLE
Export Option does not work when more than one column is seleted in results pain. 

### ISSUE THREAD

**Issue by EmanNo1** [microsoft/azuredatastudio#2744]
Issue Type: <b>Bug</b>

I am not able to use the export options when I select more than one column from the results pane. On the inverse, I am able to export a single column only. 

SQL Operations Studio version: sqlops 0.32.8 (efd470b3c771ef7473ba3cf108a33b6579c96a53, 2018-08-30T19:33:15.959Z)
OS version: Linux x64 4.15.0-34-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3096)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: enabled<br>vpx_decode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|7.70GB (1.54GB free)|
|Process Argv|/usr/share/sqlops/sqlops --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alanrenmsft** [comment]
I can confirm this is working fine now.
