### ISSUE TITLE
Single quote in table name breaks syntax coloring

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/azuredatastudio#2745]
![image](https://user-images.githubusercontent.com/2224906/46364158-fd067480-c642-11e8-99d2-6afe62cb8ef6.png)

Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by Charles-Gagnon** [comment]
Duplicate of #4630
