### ISSUE TITLE
show a progress ring in a tab that's executing a query

### ISSUE THREAD

**Issue by TyTyMu** [Microsoft/azuredatastudio#2750]
When I execute queries that take a few minutes, I work on other scripts, but I have to open the executing query tab to see if the query is done or if it's still executing.
It would be nice to have a progress ring or a specific icon in the tab to indicate that a tab is executing a query.

**Comment by kburtram** [comment]
I'll dup this with https://github.com/Microsoft/azuredatastudio/issues/2839 to reduce the issue count.  Thanks for reporting the problem!
