### ISSUE TITLE
SQLCMD enable Feature

### ISSUE THREAD

**Issue by CubsRep** [microsoft/azuredatastudio#2752]
- Azure Data Studio Version:

Nice to have SQLCMD tab to toggle ON/OFF to SQLOps session.

**Comment by joshbooker** [comment]
+1
Now that [Schema Compare Extension](https://github.com/Microsoft/azuredatastudio/pull/4974) is outputting SQLCmd scripts we need this more than ever.

**Comment by kburtram** [comment]
@udeeshagautam I recall you talking about this while discussing the Schema Compare feature.  Do you have any additional updates?

**Comment by yualan** [comment]
This was included in the Schema Compare spec, but I think there is a team discussion required here since this support will be nice to have for most of our cross-plat tools (Azure Data Studio, mssql-cli, etc.) so it comes down to who would do the work. Let's sync on this.

**Comment by udeeshagautam** [comment]
We will need to do a quick cost/pri analysis as Alan mentioned. The overall inital thought was to get core Schema Compare functionalities working and then we can pick this as needed.

**Comment by hfleitas** [comment]
+1 up-vote on sqlcmd!

**Comment by hfleitas** [comment]
you can do anything! 🎉:boom:
![image](https://user-images.githubusercontent.com/4984616/56854524-12582e80-6906-11e9-864f-9c9fd1c990c7.png)

**Comment by jasonhorner** [comment]
This also blocks running ssdt generated publish scripts in ADS

**Comment by kevcunnane** [comment]
@udeeshagautam moving this to Planning since it's in scope for September

**Comment by udeeshagautam** [comment]
This is enabled for September through query editor Enable SQLCMD mode Button.
