### ISSUE TITLE
Connection name is not used in 'Manage' tab name

### ISSUE THREAD

**Issue by kenvanhyning** [Microsoft/azuredatastudio#2763]
Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Create a connection profile and include a name for the connection.

2. Right click on that server in OE and choose manage

3. Observe the title used in the tab is the host name rather than the connection name.

**Comment by kburtram** [comment]
This is fixed in the latest insiders builds and will be included in the Oct stable release.
