### ISSUE TITLE
Copy with Headers duplicates the headers

### ISSUE THREAD

**Issue by KevinLeeBuchan** [Microsoft/azuredatastudio#2765]
Issue Type: <b>Bug</b>

When I copy a result set and include headers, the header is duplicated before each row in the result set.  I end up having to delete them after I paste into Excel.  

"Save as Excel" does not exhibit this behavior, but I'm often adding to an existing spreadsheet.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.62GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.1.0
profiler|Mic|0.2.0
server-report|Mic|0.1.3

</details>

**Comment by anthonydresser** [comment]
To repro this are you clicking the top corner? That is fixed via #2757

**Comment by darren-harrison** [comment]
I can see this happening as well.

**Comment by kburtram** [comment]
This is fixed in the latest insiders build at https://github.com/Microsoft/azuredatastudio/releases and will be in the stable build later this week.
