### ISSUE TITLE
Results pane trouble scrolling horizontally

### ISSUE THREAD

**Issue by hlkagency** [Microsoft/azuredatastudio#2766]
This issue in on the Mac version while using the magic mouse.

Currently the results pane is incapable of scrolling horizontally unless the pane is at the top or bottom fo the results list. If the results pane is at the top the user must scroll at an upwards angle (up + left/right) while if the results pane is at the bottom the user must scroll at a downwards angle (down + left/right). Pure horizontal scrolling doesn't work.

Note that this used to work (don't recall the version it did). And also, the query editor pane does still support pure horizontal scrolling on the Mac version with the magic mouse.

**Comment by anthonydresser** [comment]
dupe #2700
