### ISSUE TITLE
Configured debug type 'azuredatastudioExtensionHost' is not supported

### ISSUE THREAD

**Issue by rrgiles** [microsoft/azuredatastudio#2768]
Samples project serverReports is not able to be debugged.

Azure Data Studio Version: 1.0.0

Steps to Reproduce:

1. Download Github project 'azuredatastudio'
2. Open \samples\serverReports
3. Complete all prerequisites by installing package dependencies referred to in package.json 
4. Follow instructions for debugging an extension at https://docs.microsoft.com/en-us/sql/azure-data-studio/extension-authoring?view=sql-server-2017

The topic for Debug an Extension refers to installing Azure Data Studio Debug extension but only the SQL Operations Studio Debug 1.1.0 extension is available. That was installed.

Press F5 or click the Debug icon and click Start produces this error:

"Configured debug type 'azuredatastudioExtensionHost' is not supported".

In launch.json the azuredatastudioExtensionHost type is referrenced.

	"version": "0.2.0",
    "configurations": [

        {
            "name": "Debug in AzureDataStudio install",
            "type": "azuredatastudioExtensionHost",
            "request": "launch",
            "runtimeExecutable": "azuredatastudio",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ]
        },

**Comment by siyangMicrosoft** [comment]
same error here. 
How to solve this.

**Comment by Charles-Gagnon** [comment]
This has been fixed, the correct type is `sqlOpsExtensionHost`
