### ISSUE TITLE
Unable to view horizontal scroll bar in results

### ISSUE THREAD

**Issue by dmonder** [microsoft/azuredatastudio#2769]
Issue Type: <b>Bug</b>

I do not see the horizontal scroll bar in the results pane after running a query. I am able to click in a cell and move to the right and see the extra columns, but I cannot scroll to the right either with a mouse or by click on a scrollbar.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.88GB (17.28GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
We've made several improvements to scrolling since this issue was opened.  Including improving some of the cases with multiple resultsets and double-scrollbars and increasing the size of the scrollbars.  Please let us know if you're still impacted by this issue.
