### ISSUE TITLE
Server Groups dialog should provide a color picker

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#2785]
- Azure Data Studio Version: `master`

Server Groups dialog should provide a color picker control that allows the user to choose arbitrary colors rather than from a fixed set of colors.

> Note: based on PM feedback

![image](https://user-images.githubusercontent.com/599935/46563687-d3a24e80-c8b7-11e8-8c89-4ea2d283c440.png)

**Comment by smithaBharadwaj** [comment]
Here is a mockup I have 
![image](https://user-images.githubusercontent.com/27451624/46627295-e18de480-caee-11e8-93e5-c1f2e21ea3ff.png)

![image](https://user-images.githubusercontent.com/27451624/46627309-f0749700-caee-11e8-8ea2-99a9eeffb3fe.png)

**Comment by kburtram** [comment]
Closing out older issues.
