### ISSUE TITLE
Zen Mode not using whole screen

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#2790]
- Azure Data Studio Version:

Version 0.32.9
Commit 8004776eff330e8980b473b6a2f6faf607164005
Date 2018-09-19T05:11:56.160Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Enter Zen mode,
![2018-10-07_15-58-54](https://user-images.githubusercontent.com/12263288/46586264-ff553e00-ca49-11e8-994d-eb6998151143.png)

2. Observe that the screen has large borders to the left and right

**Comment by kburtram** [comment]
@gbritton1 you can turn off "Centered Layout" mode using the `View: Toggle Centered Layout` command.  In my opinion, I prefer "Centered Layout" to be off as well, but in general we defer to VS Code for design decisions around the core editor functionality.  We'll discuss switching this default in our next triage meeting.

![image](https://user-images.githubusercontent.com/599935/46623486-a5548700-cae2-11e8-8eb7-3afc3201bf35.png)

**Comment by gbritton1** [comment]
Yeah, whichever way I toggle the centered layout, the problem remains.  Blank space on both sides.  I expected to see, e.g. line numbers on the left edge.

**Comment by kburtram** [comment]
When I toggle centered layout the editor seems to fill nearly the entire screen (screenshot below). I still see some space between the numbers and the absolute left edge of the screen, but this gap is consistent with what I see in VS Code.

It might be worthwhile to log an issue upstream to see what the rationale is for not placing the line numbers flush against the edge.

![image](https://user-images.githubusercontent.com/599935/47055779-024cde80-d16e-11e8-80db-e9414ffdeb4a.png)

**Comment by gbritton1** [comment]
works for me now

**Comment by kburtram** [comment]
This is coming from the vscode implementation.  We'd prefer to see any improvements in this area come from upstream.  Please log an issue with vscode if this is still impacting you.  Thanks for reporting this suggestion!
