### ISSUE TITLE
Feature Ask: Gray out wizard page and disable its inputs while Next button validation is in progress.

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#2791]
Currently if someone wants to disable page inputs during validation, they need to manually set the enabled field for each model view component. This can be a little difficult for complex pages, or for model view components that have no enabled field. A possible solution to this is to gray out the wizard page while the validation is in progress after clicking the next button. This would be similar to how we gray out the rest of Azure Data Studio while the connection dialog is open, for example.

**Comment by kburtram** [comment]
Closing out older issues.  Please reactive if this is impacting an extension under active development.
