### ISSUE TITLE
Sort list of registered servers by name

### ISSUE THREAD

**Issue by vobrechkov** [microsoft/azuredatastudio#2799]
Issue Type: <b>Feature Request</b>

Please sort list of registered servers by name or add option to allow list to be sorted. Currently registered servers are sorted by the order they have been added to each server group. This is contrary to how registered servers are listed in SSMS.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

**Comment by jwk6** [comment]
WORKAROUND - You can rearrange them in your user settings.json file.  Hit Ctrl-Shift-P to open the command palette, and then type 'open user settings' and it enter.

Find the "datasource.connections" array and then rearrange the elements (between the { and }) however you'd like them to be displayed.

The easiest way to do that is to select all the lines for one element, and use Alt-Up Arrow or Alt-Down Arrow to move the whole block of text up or down.  Just be careful that the commas are in the right place.  Hit Ctrl-S to save, and close and re-open Azure Data Studio.
