### ISSUE TITLE
"Add Azure Account" presents an unclickable link

### ISSUE THREAD

**Issue by jrr** [microsoft/azuredatastudio#2800]
Issue Type: <b>Bug</b>

When you try to sign in to an Azure account ("To sign in, use a web browser to open the page ..."), the link is not clickable, and the text can't even be selected to copy/paste it!

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|32.00GB (0.12GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_3507032|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
This experience has been improved in the Feb release.  Please let us know if you're still impacted by this issue.  Thanks for reporting!
