### ISSUE TITLE
Opening a new folder (Ctrl-K Ctrl-O) closes existing editor and object explorer windos

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2801]
- Azure Data Studio Version:
Version 1.0.1
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Start Azure Data Studio
2. Open a query editor
3. Connect to a server in Object Explorer.
4. Go to File -> Open Folder, pick a folder and hit select folder.

Actual: The context of azuredatastudio gets reset as if the application just started. Open editor sessions get closed and object explorer sessions are also closed. Disconnect OE sessions are visible
Expected: The original state is maintained and the shows the 'Explorer' view with the folder just opened.

**Comment by kburtram** [comment]
This is based on upstream behavior that opening a folder reloads the process state.  If we want to change this behavior we should work with the vscode team.
