### ISSUE TITLE
Improve tasks view so script results can be included

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2803]
Current Tasks API doesn't allow you to provide the script that was used to execute an operation. This means that if you run a wizard like Create External Table and it fails, you can't see what ran.

Ask:
- Support including the script used to run the task, at a minimum
- Longer term, allow status to be linked to the script (e.g. failed at line 4, so user can see exact point of failure)

**Comment by kburtram** [comment]
Closing out older issues.  We're planning a a significant Tasks view update in a future release. Thanks!
