### ISSUE TITLE
Unify backend Tools Services provided by extensions

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2804]
Current implementations have multiple "SQL Tools Service" implementations running independently. These use a decent amount of both RAM and disk space (30-50MB). We've discussed unifying this by having an extension opt into a unified service, define where to look for its DLLs that contribute services, and then loading from a single backend. This could dramatically improve install time for extensions and reduce RAM usage.

**Comment by kburtram** [comment]
Closing out older issues.  We still need to do this but we should track this task elsewhere.  Perhaps on the sqltoolsservice repo.
