### ISSUE TITLE
Feature ask: Add option to close all tabs without saving

### ISSUE THREAD

**Issue by LucasWBritz** [Microsoft/azuredatastudio#2809]
Is it possible to add an option to close all tabs even when they aren't saved? 
Maybe an option "No to all" or something like this. 

- Azure Data Studio Version:
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2

Steps to Reproduce:

![closetabs](https://user-images.githubusercontent.com/24421665/46764082-dd5df480-ccb1-11e8-9e61-a7d9f477d143.gif)

**Comment by kburtram** [comment]
@LucasWBritz I agree this is annoying.  I would expect this to be handled upstream from VS Code.  I'll look through their issues to check for related discussions there (...or perhaps we're doing something incorrect on our side)

**Comment by anthonydresser** [comment]
Going to close as dupe #2826 . Although not the exact same ask, it is asking for a fix to the same problem.
