### ISSUE TITLE
printed result contains no new lines

### ISSUE THREAD

**Issue by DariusStank** [Microsoft/azuredatastudio#2811]
Issue Type: <b>Bug</b>

When I try generate views, they appear without new lines (everything in one row). 

This is more for code readability

Example

PRINT 'Darius test 

test2
'

Started executing query at Line 35
Darius test test2
Total execution time: 00:00:00.025

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (8 x 2397)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|56.00GB (33.40GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by anthonydresser** [comment]
This will be in the next release #2935
