### ISSUE TITLE
Query result does not return whole content if column is longer than 63 831 characters

### ISSUE THREAD

**Issue by panuoksala** [microsoft/azuredatastudio#2813]
Issue Type: <b>Bug</b>

Create table with varchar(max) column and insert very large string into column (for example large xml file). When querying this column result set contains only 63 831 characters from it.

This same bug is also in Management Studio, so it might be related to SQL Server itself. However in Management Studio this problem can be circumvented by converting column into XML (at least for xml data):
`CAST('<A><![CDATA[' + CAST(VeryLongXmlColumn as nvarchar(max)) + ']]></A>' as xml)`

In Management Studio this will return whole content, but in SQL Operations Studio this will return only first 2 097 153 characters.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4712HQ CPU @ 2.30GHz (8 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (3.91GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alanrenmsft** [comment]
@panuoksala this is configurable now, you can change the default max character: 
![image](https://user-images.githubusercontent.com/13777222/204968924-f7180716-d636-4dcf-97b7-6ecbf68e53dd.png)
