### ISSUE TITLE
Result pane shown over splitted screen with split screen text in background

### ISSUE THREAD

**Issue by VincentVerweij** [microsoft/azuredatastudio#2815]
Issue Type: <b>Bug</b> 
1) Open a new query 
2) Type a query and run it so the Results pane is shown 
3) Press the "Split Editor Right" button (top right corner) 
4) Right click on the newly created window 
5) Choose "Open File..." 
6) Choose any of the open queries 
7) [BUG] Result pane is shown on top of opened query and text of split window is visible behind the result pane text Azure Data Studio 

![image](https://user-images.githubusercontent.com/41574930/46808037-a9470a00-cd6b-11e8-9891-d548438c0f5a.png)

version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z) 
OS version: Windows_NT x64 10.0.14393 <details> <summary>System Info</summary> |Item|Value| |---|---| |CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)| |GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl:

**Comment by kburtram** [comment]
This should be fixed in current builds.  Please let us know if you're still impacted by this issue.  Thanks for reporting this bug!
