### ISSUE TITLE
Could not preview csv file in HDFS folder <aduxr>

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2816]
Issue Type: <b>Bug</b>

Error previewing file: Error: cannot open untitled:/Users/gengelb/faithful.csv. Detail: file already exists on disk

REPO
1. Create a directory in HDFS, name it "data"
2. Upload a csv file into "data" directory.
3. Right click to preview.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.84GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
Yes, looks like it's fixed now.
