### ISSUE TITLE
Unable to edit notebooks created from ADS in VS Code

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2820]
Issue Type: <b>Bug</b>

Create notebook in ADS. Open in VS code with the AI Explorer extension. Also sorts of error ensues in AI Explorer when you try to view the notebook and kernel dies there eventually.

Ex error:
Notebook validation failed: Additional properties are not allowed ('transient' was unexpected):
{
 "metadata": {},
 "data": {
  "text/plain": "<IPython.core.display.HTML object>",
  "text/html": "\n<table>\n  <tr>\n    <th>Magic</th>\n    <th>Example</th>\n    <th>Explanation</th>\n  </tr>\n  <tr>\n    <td>info</td>\n    <td>%%info</td>\n    <td>Outputs session information for the current Livy endpoint.</td>\n  </tr>\n  <tr>\n    <td>cleanup</td>\n    <td>%%cleanup -f</td>\n    <td>Deletes all sessions for the current Livy endpoint, including this notebook's session. The force flag is mandatory.</td>\n  </tr>\n  <tr>\n    <td>delete</td>\n    <td>%%delete -f -s 0</td>\n    <td>Deletes a session by number for the current Livy endpoint. Cannot delete this kernel's session.</td>\n  </tr>\n  <tr>\n    <td>logs</td>\n    <td>%%logs</td>\n    <td>Outputs the current session's Livy logs.</td>\n  </tr>\n  <tr>\n    <td>configure</td>\n    <td>%%configure -f<br/>{\"executorMemory\": \"1000M\", \"executorCores\": 4}</td>\n    <td>Configure the session creation parameters. The force flag is mandatory if a session has already been\n    created and the session will be dropped and recreated.<br/>Look at <a href=\"https://github.com/cloudera/livy#request-body\">\n    Livy's POST /sessions Request Body</a> for a list of valid parameters. Parameters must be passed in as a JSON string.</td>\n  </tr>\n  <tr>\n    <td>spark</td>\n    <td>%%spark -o df<br/>df = spark.read.parquet('...</td>\n    <td>Executes spark commands.\n    Parameters:\n      <ul>\n        <li>-o VAR_NAME: The Spark dataframe of name VAR_NAME will be available in the %%local Python context as a\n          <a href=\"http://pandas.pydata.org/\">Pandas</a> dataframe with the same name.</li>\n        <li>-m METHOD: Sample method, either <tt>take</tt> or <tt>sample</tt>.</li>\n        <li>-n MAXROWS: The maximum number of rows of a dataframe that will be pulled from Livy to Jupyter.\n            If this number is negative, then the number of rows will be unlimited.</li>\n        <li>-r FRACTION: Fraction used for sampling.</li>\n      </ul>\n    </td>\n  </tr>\n  <tr>\n    <td>sql</td>\n    <td>%%sql -o tables -q<br/>SHOW TABLES</td>\n    <td>Executes a SQL query against the variable sqlContext (Spark v1.x) or spark (Spark v2.x).\n    Parameters:\n      <ul>\n        <li>-o VAR_NAME: The result of the SQL query will be available in the %%local Python context as a\n          <a href=\"http://pandas.pydata.org/\">Pandas</a> dataframe.</li>\n        <li>-q: The magic will return None instead of the dataframe (no visualization).</li>\n        <li>-m, -n, -r are the same as the %%spark parameters above.</li>\n      </ul>\n    </td>\n  </tr>\n  <tr>\n    <td>local</td>\n    <td>%%local<br/>a = 1</td>\n    <td>All the code in subsequent lines will be executed locally. Code must be valid Python code.</td>\n  </tr>\n</table>\n"
 },
 "transient": {},
 "output_type": "display_data"
}

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by kevcunnane** [comment]
Hi UC, can you share the notebook with me? T
Thanks for raising this issue.

**Comment by rajmusuku** [comment]
Issue is fixed.
