### ISSUE TITLE
Cancel / re-run on a cell doesn't work...

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2821]
Issue Type: <b>Bug</b>

After cancelling execution of a cell there is no way to execute it again without closing & reopening the notebook.

Repro:
1. Put some code in a cell that will take long time to run
2. Hit play
3. Hit cancel
4. Hit play (gives Canceled message always)

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by kevcunnane** [comment]
@chlafreniere has a fix for this in PR (in the extension). Chris - will we get this in time for our October release? E.g. EOD tomorrow?

**Comment by kevcunnane** [comment]
This is fixed in October
