### ISSUE TITLE
Hitting CTRL + S in notebook gives error

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2822]
Issue Type: <b>Bug</b>

Open notebook, hit CTRL + S.

Cannot read property 'toString' of null

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by kevcunnane** [comment]
@uc-msft we've been trying to reproduce this but so far have failed. Can you repro on latest bits? If so can you open the Help -> Toggle Developer Tools and copy any errors you see? Thanks.

**Comment by kevcunnane** [comment]
I'm closing this as Not Repro. Please reopen if you are able to get a call stack or reference for this. Thanks!

**Comment by kevcunnane** [comment]
@rajmusuku  can you take a look - reopening as you found it on your machine too.

**Comment by kevcunnane** [comment]
We believe this is fixed with the built-in notebook viewer. If we can get a repro in that code path, please reopen.
