### ISSUE TITLE
Cannot get long query result out of Operations Studio

### ISSUE THREAD

**Issue by wbeckle** [Microsoft/azuredatastudio#2823]
Issue Type: <b>Bug</b>

After a query is run, only visible portion of the result in the Messages pane can be copied to the clipboard. So if the query result cannot be displayed entirely without scrolling, it is not possible to copy it all. Even when Select All is used.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T04:54:09.629Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|/Applications/SQL Operations Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@wbeckle this should be fixed in the latest insider build which adds a scroll bar to the message window.  Please checkout https://github.com/Microsoft/azuredatastudio/releases/tag/1.0.1 if you'd like to pick up that update prior to the October release.
