### ISSUE TITLE
Update PROSE in SQL Server Import Extension

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#2824]
We will need to update PROSE to pick up bug fixes in Import extension.

**Comment by rdaniels6813** [comment]
Just a forewarning, PROSE 6.8.1 looks like it moved some public classes internal that are used in BCP, such as ReadInputLineCount and the method AddInputsFromReaders was removed.  Would be interested if updating this would fix #3000.  Some local testing I did makes it seem like it wont, and that the fix needs to be more internal.  Likely that is adding support to PROSE for single column TXT.

**Comment by yualan** [comment]
Thanks @rdaniels6813, our engineer is aware of this change and is including the fix for SSMS and Azure Data Studio.

**Comment by aasimkhan30** [comment]
The prose version is updated to 7.13.1 in #11341 . Closing this issue.
