### ISSUE TITLE
Opening an existing Notebook in a fresh installation of the extension is not able to load the Attach To: context

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#2825]
Issue Type: <b>Bug</b>

1. Install the extension.
2. Open an existing Notebook locally.
3. Choose PySpark3 as a Kernel.

Attach to context is not set to the cluster and throws a Kernel error.

![image](https://user-images.githubusercontent.com/22312581/46842469-9f7cd100-cd82-11e8-815e-9e096a147aa5.png)

However if you create a New Notebook against the cluster first and then try opening an existing Notebook it would work.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (15.94GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by chlafreniere** [comment]
This was fixed many moons ago.
