### ISSUE TITLE
Combined confirmation dialog for unsaved changes

### ISSUE THREAD

**Issue by tslin306** [microsoft/azuredatastudio#2826]
- Azure Data Studio Version: 1.0.0

Steps to Reproduce:
- Create multiple query windows and make changes in all of them
- Pick one of the query window and choose "Close Others" from tab context menu
- Confirmation dialog will display multiple times for each and every windows.

Expected behavior: 
- There should be only 1 dialog for all unsaved changes windows (like from SSMS). Most developers will open a lot of query windows most of the time and clicking No on each dialog is not very good.

**Comment by kburtram** [comment]
This behavior is inherited from our upstream vscode platform.  We'd prefer to see any fixes in this area first accepted by vscode team.  As a workaround you can close all unsaved documented from the Open Editors view in the File Explorer to get a combined confirmation prompt.  Thanks for logging this suggestion!
