### ISSUE TITLE
Opening Notebook stored in c:\ root folder fails with "Starting local Notebook server failed with error Notebook process exited prematurely with error: 1"

### ISSUE THREAD

**Issue by pradm** [Microsoft/azuredatastudio#2828]
If a NoteBook is stored in the Root C:\ and if we try to open it from Azure Data Studio it fails and throws the error "Starting local Notebook server failed with error Notebook process exited prematurely with error: 1"

**Developer Tools Window Stack**
Starting local Notebook server failed with error Notebook process exited prematurely with error: 1
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function)   @      C:\Program Files\Azu…t\zone-node.js:2280
NotificationsAlerts.onDidNotificationChange                               @       workbench.main.js:157433
(anonymous)                                                                @       workbench.main.js:157421
Emitter.fire                                                               @       workbench.main.js:17786
NotificationsModel.notify                                                  @       workbench.main.js:157037
NotificationService.notify                                                @       workbench.main.js:217722
MainThreadMessageService._showMessage                                     @       workbench.main.js:204438
ZoneAwarePromise                                                           @      C:\Program Files\Azu…st\zone-node.js:891
MainThreadMessageService._showMessage                                     @       workbench.main.js:204403
MainThreadMessageService.$showMessage                                     @       workbench.main.js:204398
RPCProtocol._doInvokeHandler                                              @       workbench.main.js:206270
RPCProtocol._invokeHandler                                                @       workbench.main.js:206255
RPCProtocol._receiveRequest                                               @       workbench.main.js:206210
RPCProtocol._receiveOneMessage                                            @       workbench.main.js:206193
(anonymous)                                                                @       workbench.main.js:206130
(anonymous)                                                                @       workbench.main.js:206303
Emitter.fire                                                               @       workbench.main.js:17786
acceptChunk                                                                @       workbench.main.js:28137
Protocol.Protocol.firstDataChunk._socketDataListener                     @       workbench.main.js:28163
ZoneDelegate.invokeTask                                                   @      C:\Program Files\Azu…st\zone-node.js:421
Zone.runTask                                                               @      C:\Program Files\Azu…st\zone-node.js:188
ZoneTask.invokeTask                                                        @      C:\Program Files\Azu…st\zone-node.js:496
ZoneTask.ZoneTask.cancelFn.invoke                                         @      C:\Program Files\Azu…st\zone-node.js:485
emitOne                                                                    @      events.js:116
emit                                                                        @      events.js:211
addChunk                                                                   @       _stream_readable.js:263
readableAddChunk                                                           @       _stream_readable.js:250
Readable.push                                                              @       _stream_readable.js:208
onread                                                                     @      net.js:594
 
**C:\Users\pradm\AppData\Roaming\azuredatastudio\logs\20181011T224846\output_1_20181011T224900\extension-output-#6.log**
No additional errors here
... Creating c:\Users\pradm\.azuredatastudio\extensions\microsoft.sql-vnext-0.6.9\jupyter_config\instances\bf6e8a05-cb56-42d7-b5f6-e797479a1a94
... Creating c:\Users\pradm\.azuredatastudio\extensions\microsoft.sql-vnext-0.6.9\jupyter_config\instances\bf6e8a05-cb56-42d7-b5f6-e797479a1a94\config
... Creating c:\Users\pradm\.azuredatastudio\extensions\microsoft.sql-vnext-0.6.9\jupyter_config\instances\bf6e8a05-cb56-42d7-b5f6-e797479a1a94\data
... Creating c:\Users\pradm\.azuredatastudio\extensions\microsoft.sql-vnext-0.6.9\jupyter_config\instances\bf6e8a05-cb56-42d7-b5f6-e797479a1a94\config\custom
... Starting Notebook server
    > C:\Users\pradm\.scaleoutdata\python\0.0.1\python.exe -m jupyter notebook --no-browser --notebook-dir "c:\" --port=8888 --NotebookApp.token=8d17113f6317ece7a4c8b31e79f500aeb7e803342c9a8926
The Jupyter HTML Notebook.
 
This launches a Tornado based HTML Notebook Server that serves up an
HTML5/Javascript Notebook client.

- Azure Data Studio Version:
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:
1. Keep a note book in root c:\ try to open the same with Azure Data Studio

**Comment by kevcunnane** [comment]
This was fixed in November extension release
