### ISSUE TITLE
Copy with Headers

### ISSUE THREAD

**Issue by JCarden09** [Microsoft/azuredatastudio#2829]
Issue Type: <b>Bug</b>

When you select copy with headers it puts the headers before each row as opposed to just having the headers once.  So if I have 58 results it will provide the headers 58 times.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|16.00GB (8.60GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|0.2.0
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
@JCarden09 this should be fixed in the latest insiders build available at https://github.com/Microsoft/azuredatastudio/releases and will be fixed in the next stable build later this week.  You can work-around the issue by "Select All" either through the context menu or Ctrl-A (instead of clicking on top-left grid cell).
