### ISSUE TITLE
Exporting to XLS with large data set

### ISSUE THREAD

**Issue by alliedcvil** [microsoft/azuredatastudio#2830]
Issue Type: <b>Bug</b>

1. On a Win 7 Machine with Office 2010 run ADS.
2. Generate query that generates around 5 million rows or more.
3. Received the following error.

Received the following error:

Token EndElement in state EndRootElement would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.

Might be a limitation of version of Excel in 2010, but wanted to report to ask for clarity on the error generated.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 6.1.7601

**Comment by imranbaloch** [comment]
I am also getting the same error,

```
Token EndElement in state EndRootElement would result in an invalid XML document. Make sure that the ConformanceLevel setting is set to ConformanceLevel.Fragment or ConformanceLevel.Auto if you want to write an XML fragment.
```

**Comment by imranbaloch** [comment]
I got my reason it was due to excel maximum rows limitation which is 1,048,576 rows https://support.microsoft.com/en-us/office/excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3?ui=en-us&rs=en-us&ad=us
