### ISSUE TITLE
Main canvas command text are hard to read

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2832]
Issue Type: <b>Bug</b>

In the main canvas, the font used for the Cmd-G is difficult to read and looks like a Cmd-C. 

Recommendation:
- Replace the font with one where the G/C is clearly distinguished.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 1|
|Memory (System)|16.00GB (7.93GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment]
The default UI fonts are coming from upstream.  We'd prefer to see any fixing in this area first accepted by vscode.  Thanks!
