### ISSUE TITLE
Failures in task history are getting overlapped.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#2835]
Issue Type: <b>Bug</b>

Try throwing an error in the External Table wizard by setting multiple keys for the fields, when the task history throws an error like below -

![image](https://user-images.githubusercontent.com/22312581/46891762-d523c780-ce1f-11e8-99ef-a1cd57166a60.png)

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.94GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment]
This appears to be fixed in the latest build.  Please reactive if you're still seeing this issue.

![image](https://user-images.githubusercontent.com/599935/47752904-11925880-dc53-11e8-8e77-fb5d38eb2af9.png)
