### ISSUE TITLE
Hitting cancel in server connection dialog should keep the window open

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2837]
Issue Type: <b>Bug</b>

Repro:
1. Open new server connection
2. Type something wrong in the server name
3. Hit connect
4. Hit cancel

Expected:
Dialog stays open so I can correct typo or other errors.

Actual:
Dialog closes so I have to retype everything again.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by kburtram** [comment]
This makes sense if cancel is clicked while a connection is in progress.  Otherwise, the dialog should probably be closed when cancel is clicked.
