### ISSUE TITLE
No indication in window title if there are commands still executing...

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2839]
Issue Type: <b>Bug</b>

Run any long running command in a Window. Open multiple windows (don't memorize the title of each window) and now try to figure out which one has the long running window. In SSMS, you can clearly see from the window title which one has in-progress commands.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by anthonydresser** [comment]
dupe #1265
