### ISSUE TITLE
Add Server commands are difficult to find and differentiate

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2841]
Issue Type: <b>Bug</b>

It is difficult for new users to find the Add Server command.

The placement of the Add Server icon at the top of Servers panel takes some time to find.

Additionally, the icon is similar in shape and layout to *Add Server Group* and *Show Active Connections*.

![image](https://user-images.githubusercontent.com/41927913/46894920-02c23e00-ce2b-11e8-81a3-91c7d2bd7eed.png)

**Recommendation**

1. Modify the icons so that the + is more prominent on the Add Server icon. (Make it green.) For example, a plug like that used in SSMS could be used.
2. Make green dot/badge on the *Add Server Group* less dominant. Currently, the green badge get most of the use attention. 
3. The rollovers/hovers appears slowly. Make the hovers for these icons appear more quickly. 

	[From Aurora Harley and the Nielsen Norman Group](https://www.nngroup.com/articles/timing-exposing-content/)
> For hover interactions, the timing guidelines for speed of visual feedback and exposing hidden elements must be broken down into more steps:
>	
> 1. Mouse cursor enters target area: display visual feedback within 0.1 seconds.
>	2. Wait 0.3–0.5 seconds.
>	3. If cursor remains stopped within target area, display corresponding hidden content within 0.1 seconds.
>	4. Keep displaying the exposed content element until the cursor has left the triggering target area or the exposed content for longer than 0.5 seconds.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 3, 2|
|Memory (System)|16.00GB (5.28GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment]
Closing older issues.  We'll be factoring the Connections viewlet over the several months.  Thanks for the suggestion!
