### ISSUE TITLE
Unable to reset zoom to default settings...

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#2842]
Issue Type: <b>Bug</b>

Close your eyes, press CTRL + or CTRL - mutliple times in different order. At this point, it will be good to do CTRL + 0 or similar combo to reset to default instead of playing back the sequence.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.18252

**Comment by kburtram** [comment]
Please use the `View: Reset Zoom` command for this purpose.  It looks like the keyboard shortcut requires using the NumPad0 (but can be remapped with the keyboard shortcut editor).

![image](https://user-images.githubusercontent.com/599935/56621059-e70cd100-65df-11e9-84d7-bc56f0c0f253.png)
