### ISSUE TITLE
Double Click Tab Bar Bug

### ISSUE THREAD

**Issue by adhayward** [Microsoft/azuredatastudio#2850]
- Azure Data Studio Version:
Version 1.0.0
Commit cab8f3e37c9ac4367e0dacef5185da08bd8021c2
Date 2018-09-20T22:04:35.897Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
Steps to Reproduce:

1. Double Click in space next to open tabs opens a new blank file without any way to connect it to a DB to run SQL.
![image](https://user-images.githubusercontent.com/18305551/46943902-9b91cd00-d068-11e8-9947-1be5dce68e3f.png)

It appears to be running the New Untitled File Command whereas I think the New Query Command would be far more useful.

**Comment by kburtram** [comment]
This is fixed in the latest insiders build at https://github.com/Microsoft/azuredatastudio/releases and will be included in this month's stable build.
