### ISSUE TITLE
Dark SQL Operations Studio theme: JSON text unreadable

### ISSUE THREAD

**Issue by brianbraeckel** [Microsoft/azuredatastudio#2852]
Issue Type: <b>Bug</b>

Regression after updating to v0.32.9

The dark theme can't be used with JSON text columns because the blue link color for opening JSON snippets in the SQL results view is unreadable on top of the black background.

1. Run a SQL query that returns columns of JSON text.
2. Enable the standard dark theme.
3. The blue JSON text is not readable due to contrast issues.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

Extensions: none

**Comment by anthonydresser** [comment]
We'll track this issue here, #2648
