### ISSUE TITLE
The Spark UI and Driver Log link does not work and does look indicate they are links

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#2860]
Issue Type: <b>Bug</b>

Run a cell with pyspark code.

Expected:
The details for the Spark application should clearly indicate the Link under Spark UI and Driver Log are hyperlinks. 

The link does not work and also it does not indicate that it is a link.

![image](https://user-images.githubusercontent.com/27451624/46981209-33ed7900-d08c-11e8-9af1-670013b1a531.png)

Azure Data Studio version: Azure Data Studio 1.1.2-insider (58f950ffbde24e26691f38685a507743684b4be2, 2018-10-15T03:08:44.410Z)
OS version: Darwin x64 16.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.43GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_13585652|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
I'm going to close as the UI link now works, and we're tackling link CSS in a separate task
