### ISSUE TITLE
Wizards: clicking on Help icon should show hovertext

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#2863]
- Open Create External Data wizard
- Click on the help icon on the page

Expected:
- Help text shown, just like in portal and elsewhere
Actual:
- Nothing happens unless you hover for multiple seconds with mouse

![image](https://user-images.githubusercontent.com/10819925/46981805-c0993680-d08e-11e8-84c4-231cf37dc0b6.png)

**Comment by kburtram** [comment]
Closing out older issues.
