### ISSUE TITLE
Support dragging and drop table and columns into the query editor

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2880]
Issue Type: <b>Feature Request</b>

Support draging and droping objects (e.g., tables, columns) from the SERVER panel into the editor and having the name of the object fill in.

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

**Comment by anthonydresser** [comment]
dupe #1909
