### ISSUE TITLE
Notebooks are not detecting Attach to context

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#2897]
Issue Type: <b>Bug</b>

The Attach to contexts are not been properly detected and I am seeing the Kernel error as below -

<img width="1031" alt="image" src="https://user-images.githubusercontent.com/22312581/46994990-a16cca00-d0cb-11e8-9065-fcac8a12bac6.png">

There is also the session is disposed error.

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/22312581/46995018-c2351f80-d0cb-11e8-8acf-6beded7f6fc0.png">

Azure Data Studio version: Azure Data Studio 1.1.2-insider (58f950ffbde24e26691f38685a507743684b4be2, 2018-10-15T03:08:44.410Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.35GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/D8943F19-24D7-4292-91C5-92F24045D63C/d/Azure Data Studio-2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.2.0
sql-vnext|Mic|0.7.0

</details>

**Comment by chlafreniere** [comment]
This was fixed in 2018.
