### ISSUE TITLE
Excessive memory usage.

### ISSUE THREAD

**Issue by dalee-bis** [Microsoft/azuredatastudio#2899]
Issue Type: <b>Performance Issue</b>

I have been experiencing excessive memory usage (upwards of 2GB) from Azure Data Studio when the application is left open for several hours. This occurs after queries have finished and seems to be part of the main window process.

I have used the devtools to produce a memory snapshot so can look into the cause but cannot upload it as it is over 1GB in size. Most of the objects seem to be rather small "dispose()" objects. Presumably these are not being closed as expected.

I believe the "shared process" in the Process Info is caused by the snapshot generation so can be ignored. The high memory usage is usually on the window process.

This is possibly related to #2682.

Azure Data Studio version: azuredatastudio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T22:04:35.897Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.91GB (1.67GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    67	  3180	azuredatastudio main
    0	   139	  2364	   gpu-process
    0	    13	  3672	   shared-process
    2	    73	  7824	   window (Issue Reporter)
    0	  3683	 14672	   window (● SQLQuery3 - Azure Data Studio)
    0	     8	    84	     searchService
    0	    12	  8776	     extensionHost
    0	    15	  5596	       c:\Users\dalee\.azuredatastudio\extensions\microsoft.import-0.2.0\flatfileimportservice\Windows\0.0.2\MicrosoftSqlToolsFlatFileImport.exe --log-dir C:\Users\dalee\AppData\Roaming\azuredatastudio\flatfileimport
    0	     5	 11696	         console-window-host (Windows internal process)
    0	    37	  8948	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\MicrosoftSqlToolsServiceLayer.exe" --log-dir C:\Users\dalee\AppData\Roaming\azuredatastudio\mssql
    0	     5	 12652	         console-window-host (Windows internal process)
    0	    16	 13684	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\MicrosoftSqlToolsCredentials.exe" --log-dir C:\Users\dalee\AppData\Roaming\azuredatastudio\mssql
    0	     5	 16164	         console-window-host (Windows internal process)
    0	    12	 17216	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\SqlToolsResourceProviderService.exe" --log-dir C:\Users\dalee\AppData\Roaming\azuredatastudio\mssql
    0	     5	 12184	         console-window-host (Windows internal process)
    0	  2825	 19736	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0

</details>

**Comment by kburtram** [comment]
We've observed some memory leaks related to the query grid that can cause high memory usage even after the query editors are closed.  We're targeting a fix for Nov release (or hopefilly an insider build around the end of this month).

**Comment by kburtram** [comment]
PR #3458 fixed a significant memory leak that would hold query editor resources every time a tab was switched.  I'll close this issue based on that.  This fix is available in https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.7 and will be in the stable build planned for next week.  Please open an bug if the problem persists on a build containing #3458.  Thanks!
