### ISSUE TITLE
Results Pane should collapse to bottom of the screen

### ISSUE THREAD

**Issue by sebcruz** [microsoft/azuredatastudio#290]
- SQL Operations Studio Version: 0.23.6

Please change the behavior of the Results pane to collapse to the bottom of the screen in the same way the Messages pane collapses to the bottom of the screen when you click it.  This behavior, as opposed to the current behavior, would maximize the viewable area of the Editor (and your code).  It would also be more in-line with the behavior of SSMS where Ctrl-R will hide the query results.

**Comment by anthonydresser** [comment]
@kburtram @yualan is this still a valid issue?

**Comment by kburtram** [comment]
@sebcruz the `Shift-Windows-R` shortcut will toggle the results tab visibility similar to SSMS `Ctrl-R`.  Please let me know if that doesn't address this suggestions.

**Comment by sebcruz** [comment]
Thank you @kburtram
