### ISSUE TITLE
Support drag & dropping files in HDFS folder

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2902]
- Azure Data Studio Version: Version 1.0.0 (1.0.0)

Steps to Reproduce:
1. Create a directory under HDFS (e.g., OldFaithful)
2. Upload a data file (e.g., faithful.csv)
3. Create a subdirectory under HDFS/OldFaithful.
4. Try to move the data file to the data directory using drag and drop.

![image](https://user-images.githubusercontent.com/41927913/47035907-fd693a00-d12f-11e8-89f4-61cd43cdc1a7.png)

**Comment by kevcunnane** [comment]
Closing as stale
