### ISSUE TITLE
Not able to load existing Notebooks on the new extension

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#2903]
Issue Type: <b>Bug</b>

I installed the latest extension 0.7.1 and I cannot open the existing Notebooks. It throws a Kernel error and the Notebook session cannot start.

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/22312581/47038257-d9105c00-d135-11e8-8566-71abff380541.png">

Azure Data Studio version: Azure Data Studio 1.1.2-insider (58f950ffbde24e26691f38685a507743684b4be2, 2018-10-15T03:08:44.410Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/D8943F19-24D7-4292-91C5-92F24045D63C/d/Azure Data Studio-2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.2.0
sql-vnext|Mic|0.7.1

</details>

**Comment by chlafreniere** [comment]
Notebooks have been moved into ADS core now.
