### ISSUE TITLE
Attach To in notebooks does not display second cluster.

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2907]
Issue Type: <b>Bug</b>

I connected to a second cluster and wanted to run my notebook against the second cluster, but the second cluster was not displayed in the "Attach To" dropdown.

STEPS TO REPRO
1. Create a notebook that is attached to a cluster.
2. Add a second cluster
3. Try to atttach the notebook to the second cluster by clicking the "Attached To:" dropdown.
NOTE - That the second cluster does not appear on the dropdown.

![image](https://user-images.githubusercontent.com/41927913/47043259-07943400-d142-11e8-8ea6-6577ed635ba1.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
This was fixed in 2018.
