### ISSUE TITLE
Expanding the HDFS Node throws error

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#2917]
Issue Type: <b>Bug</b>

If I expand the HDFS Node I am seeing Unknown Error. However if I Refresh the error goes away.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/22312581/47052207-4505bb00-d15c-11e8-8a81-580ecc192741.png">

Azure Data Studio version: Azure Data Studio 1.1.2-insider (58f950ffbde24e26691f38685a507743684b4be2, 2018-10-15T03:08:44.410Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/D8943F19-24D7-4292-91C5-92F24045D63C/d/Azure Data Studio-2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.2.0
sql-vnext|Mic|0.7.1

</details>

**Comment by kevcunnane** [comment]
This is likely a cluster-side error that's transient. Let's consider how we can improve 
a) error indicators on expansion, including fixing the webhdfs module to do give better error messages and status codes so we can diagnose, and
b) consider adding some kind of retryable error logic to handle this, e.g. wait a second and re-query the endpoint.
