### ISSUE TITLE
Expanding Keys node on table with 1024 keys is too slow

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2925]
- Azure Data Studio Version:

Steps to Reproduce:

1. Create the BroadTest table using the attached [CreateBroadTest.sql.txt] file on a server. 
(https://github.com/Microsoft/sqlopsstudio/files/2364840/CreateBroadTest.sql.txt)
2. After connecting to the server in ops studio, in object explorer navigate to Databases->DbName->Tables->dbo.BroadTest->Keys

It takes ~ 41 seconds for the 1024 columns of that table to be displayed. In ssms this gets done in ~2 seconds.

If you have logging for SqlTools configured then here are the relevant entries show in the log pane:
**_18-10-16 19:22:18::6414555 pid:4840 tid:12 MicrosoftSqlToolsServiceLayer Information: 0 : 2018-10-16T19:22:18.6414459-07:00 - Missing regular property IndexKeyType property bag state Lazy for type Index
18-10-16 19:22:18::6414722 pid:4840 tid:12 MicrosoftSqlToolsServiceLayer Information: 0 : 2018-10-16T19:22:18.6414704-07:00 - get data for urn: Server[@Name='ARVRAN-2\SQL17RTM']/Database[@Name='AdventureWorks1']/Table[@Name='BroadTest' and @Schema='dbo']/Index[@Name='IX_BroadTest_Uniq_Id694']_**

This looks like a left-over issue after fix for the following issue: https://github.com/Microsoft/azuredatastudio/issues/2473

**Comment by kburtram** [comment]
Closing this as similar to https://github.com/microsoft/azuredatastudio/issues/1205.  We will check behavior of other database object types when investigating that bug.
