### ISSUE TITLE
Tail of SqlTools logs is cut off when the azure data studio exits

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2926]
- Azure Data Studio Version:
Version 1.1.3
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Configure sqltools logging by using the following in your usersettings.
    _"mssql.tracingLevel": "All",
    "mssql.logFilesRemovalLimit": 100,
    "mssql.logRetentionMinutes": 60,_

2. Expand some nodes in object explorer and execute a query to generate log entries.
3. Observe the log entries in output pane (Ctrl-Shift-U) -> Log (SqlTools)

**Observed:**
The very tail of the log entries is cutoff. The entries at tail do not make it to the log file even upon process exit.

**Expected:**
While the tail being cutoff is expected due to buffering. This should eventually flush especially on process exit.

**Comment by kburtram** [comment]
Closing older issues that aren't impacting user facing scenarios.
