### ISSUE TITLE
Getting a livy error when running a notebook - Standard_D8s_v3, 5 nodes

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2928]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/41927913/47093736-a9695e80-d1de-11e8-972a-e4fa6c23e051.png)

**CTP 2.0 Deployment**
pip3 install --index-url https://private-repo.microsoft.com/python/ctp-2.0 mssqlctl

**Ports**
Gengelb-MacBook-Pro:~ gengelb$ kubectl get svc -n kubcluster2 | grep -v "<none>"
NAME                            TYPE           CLUSTER-IP    EXTERNAL-IP     PORT(S)                                                                                                                                                                                    AGE
service-master-pool-lb          LoadBalancer   10.0.237.18   104.40.16.115   31433:30096/TCP                                                                                                                                                                            19h
service-mssql-controller-lb     LoadBalancer   10.0.51.34    40.78.48.203    30080:31156/TCP                                                                                                                                                                            19h
service-proxy-lb                LoadBalancer   10.0.152.85   104.40.20.70    30777:32367/TCP                                                                                                                                                                            19h
service-security-lb             LoadBalancer   10.0.89.169   104.40.18.171   30443:30366/TCP                                                                                                                                                                            19h

I created a 5 node cluster on AKS:
 
az aks create --name kubcluster2 \
--resource-group gengelbaksgroup \
--generate-ssh-keys \
--node-vm-size Standard_D8s_v3 \
--node-count 5 \
--kubernetes-version 1.10.7
 
When a run a notebook with a code cell with print(1), I get:
 
 
The code failed because of a fatal error:
        Invalid status code '500' from https://104.40.18.171:30443/gateway/default/livy/v1/sessions with error payload: <html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
<title>Error 500 Server Error</title>
</head>
<body><h2>HTTP ERROR 500</h2>
<p>Problem accessing /gateway/default/livy/v1/sessions. Reason:
<pre>    Server Error</pre></p><hr><i><small>Powered by Jetty://</small></i><hr/>
 
</body>
</html>
.
 
Some things to try:
a) Make sure Spark has enough available resources for Jupyter to create a Spark context.
b) Contact your Jupyter administrator to make sure the Spark magics library is configured correctly.
c) Restart the kernel.
 

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (6.48GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
We haven't seen this particular issue for a few months now, so closing this issue.
