### ISSUE TITLE
Built in extension changelog says to check the VSCode Release Notes for changes

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#2929]
Issue Type: <b>Bug</b>

Open the extension gallery, navigate to SQL Server Profiler. Click on Changelog.

Expected:
- *Please check the _Azure Data Studio Release Notes_ for changes to the built-in extensions*

Actual:
- Says VSCode instead
![image](https://user-images.githubusercontent.com/10819925/47105385-9f545980-d1f8-11e8-9a4d-eb8434a1d8f2.png)

Azure Data Studio version: azuredatastudio 1.1.3 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.48GB free)|
|Process Argv|/Users/kcunnane/projects/azuredatastudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --debugBrkPluginHost=46833 --debugId=d6a59bff-80d7-46ff-9412-0da0933da300 --extensionDevelopmentPath=/Users/kcunnane/projects/SqlOpsStudioExtensions/extensions/aris|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.0.0

</details>

**Comment by kburtram** [comment]
This is fixed now.  Thanks @hi-im-T0dd!
