### ISSUE TITLE
sqlops aborts with no error if X Window display is not accessible.

### ISSUE THREAD

**Issue by smooth1x1** [microsoft/azuredatastudio#293]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-05T22:46:14.815Z)
- OS Version: Linux x64 3.10.0-693.11.1.el7.x86_64
---

Steps to Reproduce:

1. During Installation create a seperate user called sqlops

2. When user sqlops tries to run sqlops, the sqlops process failed to connect to the X display and exits with no error message. 

3. Also update installation documentation as per http://www.smooth1.co.uk/installs/dbinstalls.html#7.2.2. 

NOTE: xdpyinfo is a good way to check the user can open a X Window display!

xhost +si:localuser:sqlops # permission sqlops user to use the X Window System
export DISPLAY=:0 # Use the local X display server
/usr/bin/xdpyinfo | head -5 # check no /usr/bin/xdpyinfo:  unable to open display ":0". errors.

**Comment by erickangMSFT** [comment]
@smooth1x1 I also hit a similar issue where I run xrdp, xfce-4 wm. when I try to run sql ops studio, it did not launch the UI. Any Linux expert to help us out step by step to properly setup 😄

**Comment by smooth1x1** [comment]
http://www.smooth1.co.uk/installs/dbinstalls.html#7.2.2

First as root use 

xhost +si:localuser:sqlops 

replacing sqlops with the user who needs to run sqlops.

Then in the session being used to run sqlops do

export DISPLAY=:0 

before running sqlops.


There must be an call that sqlops is doing which cannot open the X Window display but sqlops is not reporting the error.

Regards,
David.

**Comment by kburtram** [comment]
I'll close this as "no repro"\"out of scope".  Please let me know if we're missing an important scenario for Linux users here.
