### ISSUE TITLE
Error: Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding.

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#2931]
Issue Type: <b>Bug</b>

I disconnected from a database in ADS.

On reconnect, I got prompted to create a new firewall rule for the database. When I clicked OK, I received an error message telling me an error occurred. I quit and restarted ADS, then reconnected and it worked.

STEPS TO REPRODUCE
1. Start ADS
2. Connect to a SQL Server Database
3. Turn on Wifi - wait for Wifi to connect and Corpnet to connect.
4. Click on the SQL Database server in SERVERS
5. Expand the Databases node.
5. You are likely to see the error message when trying to expand the databases node.

NOTE - Some commands like manage work.

![image](https://user-images.githubusercontent.com/41927913/47112866-61613080-d20c-11e8-8d47-2e955cd3df4e.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (0.76GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by kburtram** [comment]
@gengelbms is this issue different than https://github.com/Microsoft/azuredatastudio/issues/2913?

**Comment by gengelbms** [comment]
I don't know, but suspect that there is a common root cause.


George Engelbeck

Senior Design Researcher | Azure Data Platform

Microsoft Corporation

Mobile: + 1.425.281.0836

<http://aka.ms/weboutlook>


________________________________

**Comment by kburtram** [comment]
@gengelbms I'll close this as a duplicate since it looks like the same error.  Please additional notes to #2913 if you'd like to add additional context to this issue.

**Comment by gengelbms** [comment]
Sounds good.


George Engelbeck

Senior Design Researcher | Azure Data Platform

Microsoft Corporation

Mobile: + 1.425.281.0836

<http://aka.ms/weboutlook>


________________________________
