### ISSUE TITLE
Search server names collapses all nodes in SERVER panel if no servers are found

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2932]
Issue Type: <b>Bug</b>

STEPS TO REPRODUCE
1. Add servers and groups to your SERVERS panel.
2. Expand several of them so you can see their databases....
3. Enter text in the "Search server names" field that will not match a server (e.g., "foo")
3. You should see "No connections found"
4. Delete the search text.
5. Note that all your expanded nodes have been collapsed.

RECOMMENDATION
- When no servers are not found, restore the nodes to their pre-search state.

![image](https://user-images.githubusercontent.com/41927913/47113754-ad14d980-d20e-11e8-85c3-1649f010fbf9.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (1.68GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.33.0
import|Mic|0.2.0
profiler|Mic|0.2.0
sql-vnext|Mic|0.6.9

</details>

**Comment by abist** [comment]
This bug isn't applicable any more since we don't have the search bar on top of OE any more.
