### ISSUE TITLE
Add "Refresh" command to datbases panel on Manage Page

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#2941]
Issue Type: <b>Feature Request</b>

I would like to see "Refresh" added to the right (command) click inside the Search panel showing databases. (The refresh commands is displayed off the ... menu in the panel.)

![image](https://user-images.githubusercontent.com/41927913/47120464-a2187400-d223-11e8-960f-dae3c5e57584.png)

Azure Data Studio version: Azure Data Studio 1.0.0 (cab8f3e37c9ac4367e0dacef5185da08bd8021c2, 2018-09-20T21:41:50.803Z)
OS version: Darwin x64 17.7.0

**Comment by kburtram** [comment]
Closing out older issues.  This will be addressed as part of the dashboard refactor in progress.
