### ISSUE TITLE
Scrolling in Results window across multiple resultset when batches are executin hangs UI

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#2944]
- Azure Data Studio Version:
Version 1.1.3
Commit 2c007115f77427a7ff7af47ad6916fccf111ea11
Date 2018-10-17T21:21:46.083Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
Steps to Reproduce:

1. In a new Query Editor execute the following query:
select * from sys.all_columns
go 500

2. While the batches are still executing as is evident from row count for each batch being displayed, scroll across the results pane to go to the last result set.

**Observed:**
These causes the scroll bar control to disappear and the UI is not responsive any more. It stays responsive when last resultset has been executed as evidenced from the messages pane. Yes the message pane continues to scroll and paint the latest messages.

**Expected**
UI to remain responses to it is possible to scroll across the results.

**Comment by kburtram** [comment]
There have been significant performance improvements in query editor for handling multiple resultsets since this issue was created.  Please let us know if the issue persists on current builds.
