### ISSUE TITLE
Results pane overlaps the Query Tabs bar when UI is made vertically the smallest possible

### ISSUE THREAD

**Issue by ranasaria** [Microsoft/azuredatastudio#2947]
- Azure Data Studio Version:
Version 1.1.3
Commit 2c007115f77427a7ff7af47ad6916fccf111ea11
Date 2018-10-17T21:21:46.083Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Execute a Query in the Query Tab so that we have visible result set.
2. Make the whole Azure Data Studio window the smallest possible vertically.

**Observed:**
The results tab overlaps the Query Tab. Now scroll vertical scrollbars are visible. Similarly Messages Tab gets overlayed on top of the Query Command bars with buttons like "Run" on them.

**Expected:**
The results table and Messages tab should stay below the Query Tab and the Command Bar, or some of those UI elements can vanish out of view, however they should not over lap with transparency of UI element below showing through the one on top.

**Comment by anthonydresser** [comment]
dupe #953
