### ISSUE TITLE
Editor reports incorrect syntax when FOR JSON is used

### ISSUE THREAD

**Issue by jsmircic** [microsoft/azuredatastudio#2953]
Issue Type: <b>Bug</b>

In a SELECT SQL statement with "FOR JSON" modifier,  query editor reports "Invalid syntax near JSON" with a red underline. But the statement is correct and executes successfully.

Simple example

![image](https://user-images.githubusercontent.com/10010504/47146204-e19a9b00-d2cb-11e8-88d4-1201004f7887.png)

The second issue is that the "FOR" keyword is not properly colorized. I think it should be blue color in this example.

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.90GB (6.89GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.2.0

</details>

**Comment by kburtram** [comment]
@jsmircic I couldn't repro this on the latest Azure Data Studio build (1.1.3).  Please try that and let me know if you're still getting the JSON error underline.  I do see the FOR colorization error, so I'll keep the issue open for that.

BTW, we don't have an auto-update from SQL Ops to Azure Data Studio, so this will require a 1 time manual upgrade.

![image](https://user-images.githubusercontent.com/599935/47315619-fd6aad80-d5f9-11e8-8740-0addd66a32ed.png)

**Comment by jsmircic** [comment]
Thanks, was not aware I need manual upgrade to latest version. 

Unninstall/install and I now have Azure Data Studio 1.1.3, but no luck. The issue is still here, but I did a quick few tests and now I see it depends on the server environment. I mainly work on the Azure Sql Db and the issue reproduces there. But if I try the same query on the on-premise SQL 2016 there is no error underline. 

I guess it only reproduces when the query editor is connected to Azure Sql Db. Looks like the editor assumes wrong compat level when connected to Azure, thinks that “for json” is not supported, but it is?

**Comment by kburtram** [comment]
@jsmircic thanks for confirming.  The syntax error underline comes from the Microsoft SQL Server T-SQL parser component that we consume from SSMS.  I'll log a bug to get this fixed upstream and we'll pick up the fix once it's available.

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
