### ISSUE TITLE
Copying out of results grid doesn't immediately update clipboard

### ISSUE THREAD

**Issue by JFitzMan** [Microsoft/azuredatastudio#2955]
Issue Type: <b>Bug</b>

There is a delay (sometimes 10+ seconds, it's inconsistent) before what is copied from the results grid is actually put into the clipboard.

Steps to reproduce:
1. Copy cell from results grid, paste in the editor
2. Immediately copy another cell, paste. Previous cell copied will paste.
3. In testing I've seen that when holding down ctrl+v and waiting, eventually the clipboard does update, it's just extremely delayed. This isn't an issue in 1.0.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.91GB (2.19GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|1.3.0
bracket-pair-colorizer|Coe|1.0.60
ssmskeymap|kev|1.0.0
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1
snippet-creator|nik|0.0.4

</details>

**Comment by anthonydresser** [comment]
Seems related #1388

**Comment by anthonydresser** [comment]
This is most likely being caused by the fact we query the backend service for rows when a copy request is performed, since we can't guarantee we have the data on the front end. However, I can't seem to repro so I can't confirm.
