### ISSUE TITLE
Install progress for the SQL19 preview extension is confusing...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#2957]
Issue Type: <b>Bug</b>

The progress information or indicators for the SQL19 preview extension is confusing. It is not obvious when the operation is done (install or update). Only indicator is the blue clock and in other cases when virtualenv is setup there is output in the messages window but there is one message that says "Creating..." at the end which never changes state. You just have to assume based on CPU usage on the machine and restart or wait for the reload message.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.14393

**Comment by kevcunnane** [comment]
This should likely be fixed on the extension side. The installer is designed for very quick installs and us bundling in Python reference bits is causing slow install during the unzip process. Moving to online installer (and ultimately using an official reference Python install) should resolve but won't land in the next sprint. We should see if we can do something to speed this up / fix on Windows if possible.

**Comment by kevcunnane** [comment]
I'll close this out - we've improved this in the upcoming release

**Comment by kevcunnane** [comment]
Apologies - wrong issue in this case (I had thought it was notebook dependency updating. Reopening.

**Comment by kburtram** [comment]
The `SQL 2019 Preview` extension has been deprecated.  Please reactive or log a new issue if you're still impacted by this or similar issue.  Thanks!
