### ISSUE TITLE
Make Azure login entry points more discoverable

### ISSUE THREAD

**Issue by richardcox13** [microsoft/azuredatastudio#2961]
- Azure Data Studio Version: 1.1.3

Steps to Reproduce:
- Add a login to Azure Resource Explorer
- Realise my default browser was logged in with a different account
- I'm seeing Azure subscriptions of no interest... not the ones I would like to see

But there is nothing in the UI that allows:

- Additional logins to be added
- A login to be removed

Suggestion: look at the account management UI and functionality offered by Azure Storage Explorer.

**Comment by kburtram** [comment]
I agree.  Now that the Azure account is used for more than the Create Firewall rule dialog we should definitely make this more prominent in UI.

**Comment by richardcox13** [comment]
Thanks for the update.

This does need to be discoverable.

**Comment by cheenamalhotra** [comment]
As of today, Azure Account management is advanced and supports removing account, adding more accounts and filtering subscriptions.

I've opened https://github.com/microsoft/azuredatastudio/issues/21383 to track request to include tenants in list.
Closing this feature request as resolved.
