### ISSUE TITLE
Azure Resource Explorer: Both Personal & Corporate "Sides" of Microsoft Login Can Be Valid

### ISSUE THREAD

**Issue by richardcox13** [microsoft/azuredatastudio#2965]
- Azure Data Studio Version: 1.1.3

Steps to Reproduce:

Have a Microsoft login where both corporate (AD) and personal "sides" of the same login email can be associated with different Azure subscriptions.

Having found out how to change the initial login used in Azure Resource Explorer (see #2961) I found I could not have both sides (the personal one, for historic reasons, links to some dev & test resources, the corporate to production & more test resources).

As long as such accounts exist this should be supported...

**Comment by kevinbowman** [comment]
I work in a corporate environment, with a globally managed AAD and a "Only My Tenant" proxy header in place, I can't get the login dialogue to work at all.  Is this related?

Thanks

Kevin.

**Comment by kburtram** [comment]
@kevinbowman it doesn't sound related from the high-level description as far as I can tell, so it may be best to create separate issue.  

If you can provide some details on what's happening in the Azure Account Login dialog and if there are any error messages in the "Help->Toggle Developer Tools" Console log we would be happy to try to troubleshot this problem.

**Comment by aaomidi** [comment]
This might be solved by the latest insiders. The problem with this is 
1. Testing this is extremely difficult on our side
2. This is most likely a limitation with how Microsoft handles the login page.

I'm going to close this, but please do test with the insiders again. If the issue persists update this and I'll reopen and see what's the best way of testing this functionality.
