### ISSUE TITLE
Session lost after script saving

### ISSUE THREAD

**Issue by DariusStank** [Microsoft/azuredatastudio#2966]
- Azure Data Studio Version:
Version 0.32.9
Commit 8004776eff330e8980b473b6a2f6faf607164005
Date 2018-09-19T05:11:56.160Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

--Open blank page

--execute
CREATE TABLE #test (ID INT)

--SAVE sql script locally

--execute
SELECT * FROM #test

--result
Msg 208, Level 16, State 0, Line 1 Invalid object name '#test'.

temp table can't be accessed and also in some cases it hides result tab even if it still execute script...

**Comment by anthonydresser** [comment]
This is caused by the same issue as #1876
