### ISSUE TITLE
Word wrapping is truncated in SQL Agent extension.

### ISSUE THREAD

**Issue by dnethi** [Microsoft/azuredatastudio#2967]
When I see my job history details.. you can see the message on the bottom right gets truncated.. I have to expand the ADS window to see it.

Steps to Reproduce:

1. Install the SQL Agent extension
2. If an existing job is not available, Create a new job & run it couple of times. Ideally a failed job history has the repro scenario.
3. View job history.

![image](https://user-images.githubusercontent.com/6411451/48874355-b104c000-eda7-11e8-8065-a03be08b1ced.png)

**Comment by abist** [comment]
Added the ability to scroll horizontally for any screen size.
