### ISSUE TITLE
Azure Resource explorer

### ISSUE THREAD

**Issue by Adikota** [Microsoft/azuredatastudio#2968]
- Azure Data Studio Version: 1.1.3

Steps to Reproduce:

Request to add active directory integrated authentication since windows auth is not supported by azure SQL.

**Comment by kburtram** [comment]
We're tracking AAD support with this issue https://github.com/Microsoft/azuredatastudio/issues/13.  This is being actively worked on and should land in either Nov or Dec.  To use Azure Resource Explorer you can add an Azure account using the Account icon in the status bar.
