### ISSUE TITLE
Result Grid Horizontal Scrollbar missing

### ISSUE THREAD

**Issue by tslin306** [Microsoft/azuredatastudio#2975]
Issue Type: <b>Bug</b>

When RESULTS section (below query editor section) is too narrow in height, additional vertical scrollbar appear beside result grid scrollbar. Then Horizontal scrollbar disappeared. I can scroll horizontally only after I scroll down to bottom of that vertical scrollbar.

Expected behaviour: when available, horizontal scrollbar should appear and must be visible for user instead of needing to scroll down. Additional vertical scrollbar should not appear since result grid already have its own scrollbar to show data.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz (4 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.69GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by DariusStank** [comment]
same for me. sometimes I need expend result pane to see horizontal line.

**Comment by maroonedsia** [comment]
The problem still exists on ver. 1.4.5.

**Comment by kburtram** [comment]
This should be fixed in the latest insiders build, and in the `1.7.0` release.  Please let me know if the issue persists on the latest builds.  Thanks!
