### ISSUE TITLE
Scroll Bar available in an editor when it is not needed.

### ISSUE THREAD

**Issue by saurabh500** [microsoft/azuredatastudio#2988]
Issue Type: <b>Bug</b>

Open ADS and maximize it. Open a query editor window.
Type SELECT @@VERSION and press enter. The scroll bar appears when it is not needed.
As you go to new line, by pressing enter, the scroll bar keeps reducing in size, showing there is more to scroll, when there is actually nothing.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.69GB (4.30GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![image](https://user-images.githubusercontent.com/1623701/47397588-d0df9000-d6e4-11e8-902c-b3f94e4cc21a.png)

**Comment by kburtram** [comment]
This appears to be the same behavior as in VS Code.  In general we differ to them for issues related to the core editing experience, so probably we'd prefer for this to be fixed upstream and then we can consume the fix in the next code refresh.

**Comment by kburtram** [comment]
This behavior is coming from upstream.  We'd prefer to see any fixes in this area coming from vscode.  Thanks for reporting!
