### ISSUE TITLE
Results pane border hidden by the results header

### ISSUE THREAD

**Issue by saurabh500** [microsoft/azuredatastudio#2990]
Issue Type: <b>Bug</b>

Run a query and the results pane comes up. 
Click on the right side in an empty area in the results pane.

The results pane has a blue border which is broken by the Table header row. 

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.69GB (4.22GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

![image](https://user-images.githubusercontent.com/1623701/47397799-c1147b80-d6e5-11e8-9aa7-7ffb645e273e.png)

**Comment by kburtram** [comment]
I'm not seeing this on current builds.  Thanks for reporting this bug!
