### ISSUE TITLE
Ability to use Azure Active Directory credentials to connect to SQL

### ISSUE THREAD

**Issue by masalter** [Microsoft/azuredatastudio#2995]
Issue Type: <b>Feature Request</b>

I cannot see an option to login to to SQL using Active Directory credentials. I would like to be able to do so.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kburtram** [comment]
@masalter thanks for opening this issue.  We're tracking this request at https://github.com/Microsoft/azuredatastudio/issues/13.  This task is currently in-progress and targeted for Dec. release.
