### ISSUE TITLE
Could not load file 'System.Diagnostics.Tracing' on Mac when connecting to DB

### ISSUE THREAD

**Issue by nauticalcoder** [Microsoft/azuredatastudio#2999]
- Azure Data Studio Version:
Version 1.2.1-insider (1.2.1-insider)
MacOS Version 10.14 (Mojave)

Steps to Reproduce:

1. Open Azure Data Studio
2. Attempt to connect to a Saved Database Connection
3. Get Connection Error - Could not load file or assembly 'System.Diagnostics.Tracing, Version=4.2.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.

Version 1.1.3 of Azure Data Studio works fine for me with the exception of the profiler which is a different bug.

**Comment by kburtram** [comment]
@nauticalcoder this probably related to a patch we had to take for a SqlClient bug.  I'll take a look at what's happening.

**Comment by nauticalcoder** [comment]
I downloaded the new build and am now able to connect to my databases.
Thank you

**Comment by kburtram** [comment]
@nauticalcoder thanks for confirming.  I'll include the reference changes in today's insider build.
