### ISSUE TITLE
Profiler:  Not capturing any useful information when accessing database outside of Azure Data Studio

### ISSUE THREAD

**Issue by nauticalcoder** [microsoft/azuredatastudio#3002]
- Azure Data Studio Version:
Version 1.2.2-insider (1.2.2-insider) 
Version 1.1.3 (1.1.3)
MacOS 10.14 Mojave

Steps to Reproduce:

1. Open Azure Data Studio and connect to either a local or remote SQL Server with 'sa' login.
2. Open Profiler (Ctrl-Alt-P)
3. Choose Standard_OnPrem template
4. Choose Standard View or Tuning View
5. Start Profiler (Ctrl-Alt-S)
6. With a .Net Core EF application, make queries against the database
7. There is activity in the Profiler.  A series of _login_, _rpc_starting_, _logout_ events.

Reads, Writes and Duration are usually populated on the _logout_ event but there is no information to tell us what query was executed.  The _login_ event does have some information under TextData but it is just some SET statements. This is not information to able to determine what queries are being run and how long they are taking.

If the TSQL View is selected, we have at one point been able to see the actual query in the TextData field, but we have not been able to reproduce or determine how that showed up the one time we saw it.  If we execute a query from within Azure Data Studio, we are able to see the query in the TextData column under the TSQL View in the Profiler. 

I guess the bottom line for us is it is not clear how to use the Profiler to capture profiling information from our application that has both the Duration, Reads and Writes as well as the actual TSQL being executed.

**Comment by alanrenmsft** [comment]
@nauticalcoder glad to know that.

**Comment by findtanmayray** [comment]
I am trying with 1.2.4 of Azure Data Studio and 0.5.1 of profile extension. When I am triggering the query from java application, I only get SELECT 1 in text field irrespective of the query. @alanrenmsft 
 Could you please test with Java application?
