### ISSUE TITLE
Suppress Save Prompt When Closing Unchanged View Query

### ISSUE THREAD

**Issue by jasonmueller** [Microsoft/azuredatastudio#3004]
Issue Type: <b>Feature Request</b>

Developers will often view data from multiple tables to get an idea of what a sampling of data looks like for a table.  When choosing to view data for a table without any changes (column selection, where clauses, etc.) it can get annoying to be prompted to close a bunch of tabs containing queries that were generated with a simple menu selection and not modified.

Given I've right clicked on a table and chosen to view data in that table
When I close the tab for the query
Then the tab closes without prompting me to save the query

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.15063

**Comment by kburtram** [comment]
We made a change to have generated SQL scripts created as "not dirty" so there won't be Save prompt in the repro scenario.  This is available in the latest insiders builds and will be in the Feb release.
