### ISSUE TITLE
High RAM usage

### ISSUE THREAD

**Issue by Ryukote** [Microsoft/azuredatastudio#3008]
- Azure Data Studio Version:

![studio version](https://user-images.githubusercontent.com/37113789/47546006-854d0200-d8ef-11e8-97b8-b171da0dab91.PNG)

Steps to Reproduce:

It is very unlikely for anyone to reproduce by me just providing screenshot

![ram usage](https://user-images.githubusercontent.com/37113789/47546050-b0375600-d8ef-11e8-9cae-fd9d8ba75384.PNG)

So I would like to ask if there is any logging in Azure Data Studio, so I could provide more information.

All I can say is that I have 4 open tabs with simple select queries and that I am not running any of them and Azure Data Studio is at 1 GB RAM usage which is not normal.

What happens cause of that is, when I select top 1000 from a table with 1207  records and with 2 columns, it says it is executed in 00:00:00.031, but it needs around 10 seconds to render results in table which is not normal at all.

Something is taking breath from Azure Data Studio and I would like to know what, but I don't know if ADS have logging or not.

**Comment by kburtram** [comment]
@Ryukote thanks for opening this issue.  We're tracking this problem with https://github.com/Microsoft/azuredatastudio/issues/2899.  I'll close as a dup.  Please add any additional comments on the other issue.
