### ISSUE TITLE
Can see extentions

### ISSUE THREAD

**Issue by rwlpf** [Microsoft/azuredatastudio#3010]
Issue Type: <b>Bug</b>

When right hand click on server, and select 'Manage' then the server dashboard opens.  When look at  the server dashboard,  to the right hand side of the word 'HOME' there is a grey bar with not text.  The grey bar is where I expect to see extentions reports to appear. This works as expected in SQL Operations Studio.  This is a blocker for me moving Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.89GB (9.86GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
alwayson-insights|mat|0.2.1
agent|Mic|0.34.0
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
@rwlpf could you please check if you have this setting in your users settings?  `"workbench.enablePreviewFeatures": true`  

We disable certain features when this setting is false.  We're looking at how to make this experience more obvious.

**Comment by rwlpf** [comment]
@kburtram thank you I've updated my settings and I can see the reports.  Would it not make more sense to enable this?  Give the user the same experience as with Data Studio?  Just my thoughts.
