### ISSUE TITLE
Intellisense NOT working at all

### ISSUE THREAD

**Issue by CalvinZhai** [Microsoft/azuredatastudio#3012]
Issue Type: <b>Bug</b>

Can not get any intellisense when entering sql like "Select ... from MyTable". 

I'm expecting the tool to show the table names after typing "from " but not at all. 

In addition, when moving back to type fields after "select ", there is NO field available  to help input as well.

Peek definition returns "No definition for MyTable"

However, the select does work!

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (4.31GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.34.0
import|Mic|0.3.0
profiler|Mic|0.2.0

</details>

**Comment by kburtram** [comment]
@shueybubbles this looks like it was introduced with the SMO 15 preview update.  I think we should rollback that update until we have a fix since this is a high impact bug.  I'm able to consistently repro on Azure DB and rolling-back to the previous SMO version resolves the issue for me.

**Comment by CalvinZhai** [comment]
@kburtram: thank you for the feedback and rollback to SMO 14 sounds like a reasonable solution, but there seems to be a path/parameter issue when issuing the command within ADS Terminal:

PS C:\Users\czhai> Install-Package Microsoft.SqlServer.SqlManagementObjects -Version 140.17283.0
Install-Package : A parameter cannot be found that matches parameter name 'Version'.
At line:1 char:58
+ ... all-Package Microsoft.SqlServer.SqlManagementObjects -Version 140.172 ...
+                                                          ~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Install-Package], ParameterBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage

PS C:\Users\czhai> dotnet add package Microsoft.SqlServer.SqlManagementObjects --version 140.17283.0
Could not find any project in `C:\Users\czhai\`.
Usage: dotnet add <PROJECT> package [options] <PACKAGE_NAME>

PS C:\Users\czhai> Install-Package -Name  Microsoft.SqlServer.SqlManagementObjects -MinimumVersion 140.17283.0 -MaximumVersion 140.17283.0
Install-Package : No match was found for the specified search criteria and package name 'Microsoft.SqlServer.SqlManagementObjects'. Try
Get-PackageSource to see all available registered package sources.

**Comment by kburtram** [comment]
@CalvinZhai we're currently investigating this issue still.  We think it's an intellisense initialization issue introduced by https://github.com/Microsoft/sqltoolsservice/pull/702.  Once we have a fix available I'll publish an updated `insiders` build and the fix will be included in the Nov. release next week.

**Comment by kburtram** [comment]
@MattIrv I merged your proposed fix for this issue with https://github.com/Microsoft/sqltoolsservice/pull/724.  Could you please verify that intellisense and peek\goto definition are working for the Nov release?  Thanks!

**Comment by kburtram** [comment]
The fix for the Intellisense cache initialization bug is included in https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.3.  Please reactive this issue if you still have this problem with this build or a subsequent build.  Thanks!
