### ISSUE TITLE
Cannot Add Azure Gov Account

### ISSUE THREAD

**Issue by Powderhound509** [microsoft/azuredatastudio#3013]
Issue Type: <b>Bug</b>

How do we specify a MAG subscription?

Reproduce: Navigate to the Azure Resource Page > Add Connection > enter yourAccount@MAGSubscription.onmicrosoft.com > enter password.  Receive the following error message:

Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'a69788c6-1d43-44ed-9ca3-b83e194da255'. 

Request Id: f24f44c0-0127-4264-9390-e729d15c1700 
Correlation Id: 387eaa02-a2ed-48d4-a1cd-d586d1afde6e 
Timestamp: 2018-10-26T16:48:15Z 
Message: AADSTS50011: The reply url specified in the request does not match the reply urls configured for the application: 'a69788c6-1d43-44ed-9ca3-b83e194da255'. 
Advanced diagnostics: Enable 
If you plan on getting support for an issue, turn this on and try to reproduce the error. This will collect additional information that will help troubleshoot the issue.

Azure Data Studio version: azuredatastudio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:21:46.083Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.33GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kevcunnane** [comment]
@kenvanhyning have you made progress / started on the process for this? We need you to get our AppId approved before we can do anything else.

**Comment by pedroreys** [comment]
hey folks, is there an ETA for adding support to Azure Gov Account?

**Comment by aaomidi** [comment]
US Government cloud is now enabled in insiders.

**Comment by Powderhound509** [comment]
Thanks Amir!
