### ISSUE TITLE
The Cell Options are broken when we change the theme

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3016]
Issue Type: <b>Bug</b>

The Cell Option on dark themes are not rendered correctly.

<img width="1018" alt="image" src="https://user-images.githubusercontent.com/22312581/47593675-0080d900-d92d-11e8-9b83-ba30352714d4.png">

Azure Data Studio version: Azure Data Studio 1.2.1-insider (f7d92caae51a679934a9f945ea0b48e89f02e1de, 2018-10-23T00:30:42.493Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.61GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/530D471D-0EAB-4D3A-A617-76E02B858FF4/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1487211|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.3.0
sql-vnext|Mic|0.7.2

</details>

**Comment by chlafreniere** [comment]
No longer repros in the latest build.
