### ISSUE TITLE
Explain link missing

### ISSUE THREAD

**Issue by thesushil** [Microsoft/azuredatastudio#3022]
Azure Data Studio Version:1.1.3
OS: Windows 10 Pro for Workstations
Data Server: Microsoft SQL Server 2016 (SP2-GDR) (KB4293802) - 13.0.5081.1 (X64) 	Jul 20 2018 22:12:40 	Copyright (c) Microsoft Corporation	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

Steps to Reproduce:
1. Create any query on a database
Explain button isn't there. It used to be near the database drop down in older version.
I do have SHOWPLAN permission on the database.

**Comment by kburtram** [comment]
Please verify that the following is in your User Settings `"workbench.enablePreviewFeatures": true`.  

We turn off some preview features when this setting is false.  We're discussing how to make it more discoverable that some features are disabled.

**Comment by thesushil** [comment]
Checked just now, it is true.

**Comment by kburtram** [comment]
@thesushil thanks for confirming.  I'll close this issue then.  We're tracking the "Preview Feature discoverablity" task elsewhere.

**Comment by thesushil** [comment]
Sorry maybe I misunderstood, if `"workbench.enablePreviewFeatures": true` is true as illustrated, wouldn't I expect to see the explain button. I checked and the flag is set true, but I still don't see the explain link or button.

**Comment by kburtram** [comment]
@thesushil sorry, the misunderstanding is on my side.  If Preview Features are enabled then the Explain button should be visible.

@anthonydresser any ideas why the `Explain` button wouldn't be visible in the query editor toolbar?

**Comment by thesushil** [comment]
@kburtram No problem.

I have a dozen installs in different laptops and virtual machines, all of them are missing the button. Can anybody in the community check if they see the `Explain `button in the new version 1.1.3?

**Comment by kburtram** [comment]
@thesushil it's interesting that this is impacting multiple machines.  The only code we have controlling visibility of this button is the above mentioned setting. For reference,  https://github.com/Microsoft/azuredatastudio/blob/05f6f4ea5bd2706bad977bbdea911cf5ebf287f4/src/sql/parts/query/editor/queryEditor.ts#L505

The only thing I can think of is the call to get the configuration value is failing for some reason.  You may double-check there aren't any syntax issues in the user settings or workspace settings, or something like that.

**Comment by thesushil** [comment]
I'm so sorry, It is oversight on my side, I was looking at the wrong setting `"workbench.editor.enablePreview": true`, instead of `"workbench.enablePreviewFeatures": true` It works as expected.
