### ISSUE TITLE
Filter search columns. 

### ISSUE THREAD

**Issue by Diego-MX** [microsoft/azuredatastudio#3034]
Issue Type: <b>Feature Request</b>

I'd like to be able to search for column-like names in the database.  

I do this all the time in Power BI and I will get all the columns from all the tables that have the corresponding string.  Like this: 
![image](https://user-images.githubusercontent.com/9877444/47661925-9734dc00-db5f-11e8-9f8c-8e16ee17db7a.png)

Ideally, this search box would be found in the SERVERS tab, where I searh by Server Names.  
As I write this I'm guessing there's this feature somewhere else, but I still can't find it.  So pointing in the right direction will be helpful. 

Regards from Mexico. 

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@Diego-MX we generally recommend people try out the Redgate SQL Search extension for searching active database connections.  We've discussed with them having better integration with Object Explorer and the Search viewlet, though currently they have a different UX for this task.  I'll leave this open as a suggestion for OE integration specifically as you've outlined.

**Comment by Diego-MX** [comment]
Thanks @kburtram 
That makes things easier.

**Comment by aasimkhan30** [comment]
closing as dup of #12932
