### ISSUE TITLE
Add a new view to Azure SQL Database could not be bound

### ISSUE THREAD

**Issue by jshinevar** [microsoft/azuredatastudio#3035]
Issue Type: <b>Bug</b>

1.Create a view in an Azure SQL Database
2.Open a new query
3.Query the view
4.See error: Msg 4104, Level 16, State 1, Line 2 The multi-part identifier "xxx" could not be bound.
5.Close Azure Data Studio
6.Open it again, and then run the same query, see your data

Every time I create a new object to use on my database, I have to close Azure Data Studio and then open it again to use that object.

Azure Data Studio version: Azure Data Studio 1.1.3 (2c007115f77427a7ff7af47ad6916fccf111ea11, 2018-10-17T21:07:31.484Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|16.00GB (2.36GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@jshinevar could you please try running the `Refresh IntelliSense Cache` command in this scenario to see if that helps?

**Comment by jshinevar** [comment]
I will give that a shot the next time I add a new object. Thanks.

**Comment by kburtram** [comment]
Closing older issues.  Refreshing the cache is needed after adding new objects to get them into the local metadata.  Perhaps we can try to detect queries that modify schema and trigger this refresh automatically.  Though unless we implement full drift detection there is still the problem of objects being created in a different client session.
