### ISSUE TITLE
Notebook Output view user story

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3040]
- [x] Create outputarea.component.ts and accept a list of outputs as a property
- [x] Create output.component.ts and create 1 for each output in the list
- [x] Copy over code from outputview-src (everything from app.tsx and outputitem.tsx) and add required npm imports such that the rendering code works
- [x] Implement code sanitization using the sanitizer (again, from outputview-src)
- [x] Hook up to trusted/untrusted button
- [x] Call sanitization for both markdown component and output component

**Comment by rajmusuku** [comment]
This task is complete.
