### ISSUE TITLE
Intellisense is not working even after cache refresh

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#3045]
Issue Type: <b>Bug</b>

Hi,

I have a very simple select statement.

eg:
select *
from cases c
where c. <- I am expecting the Editor to Return but it does not show any intellisense.

I have refreshed cache.

I have also try <ctrl> + <space> for adhoc listing.

when you first started with SQL without knowing what table it does not even show me any table, only show me the snippet.

I am on SQL Server 2016 Enterprise.

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.06GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Artur2** [comment]
Having same problem, after typing of ```dbo.``` in editor I'm not having suggestions from remote database, instead of this editor showing as suggestion keywords like ```FILE``` or same things. 
Something wrong with Intellisense.

**Comment by kburtram** [comment]
We're tracking this with this issue https://github.com/Microsoft/azuredatastudio/issues/3012.  The only thing I can think of that changed here recently is we updated to the latest SMO binaries.  I'll take a look today.
