### ISSUE TITLE
Take a long time before query is start to execute / return result

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#3046]
Issue Type: <b>Bug</b>

Hi,

I run a very simple query select without sql join, the query take more than 5 sec to respond after click on run.

The result take longer to return, you can see column header but it would not show the data until ~30 sec or more, which you think the query is not running.

Regards Dat.

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700T CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.92GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@datauduong I'm unable to repro this issue.  Is there any noteworthy regarding the data set you're querying?  (e.g. table with many blobs, huge dataset, slow server, etc.)
