### ISSUE TITLE
Time series chart should have good default min and max date values

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3048]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query that generates a time series 
2. Show it as a chart

Expected: Default min and max date values should be based on the content of the data.

Actual: Date range is very large and isn't optimal most the time.

Note: I couldn't see a way to set a same date range using current UI.  For example, if the data is spread over only a few minutes in duration.

Note: I think the charting library will choose good defaults if no date range is provided.  This might be the simplest way to choose good defaults.

**Comment by kburtram** [comment]
@anthonydresser could you please take a look at this so we can unblock @rgward's demo.

**Comment by anthonydresser** [comment]
The date selector only exists on timeseries
![image](https://user-images.githubusercontent.com/4324725/47743749-ffa5bb00-dc3c-11e8-951b-f13d6d527aa5.png)

We are using chartjs default values, but chartjs has never been good when it comes to minimum values

**Comment by kburtram** [comment]
@anthonydresser this issue is specifically about the date range for the time series chart.  I'm not sure the meaning of your previous comment beyond that?

**Comment by kburtram** [comment]
@anthonydresser oops, I missed your comment below the graphic.  By default values, I meant if the user doesn't provide any min\max date then we may get the previous behavior, which apparently was what @rgward was happy with.  Then we could only provide a min\max value when explicitly specified.

**Comment by anthonydresser** [comment]
That's what we do, if the input box is not fufilled by the user, we don't pass any min/max values into the chart. I'm trying to figure out why isn't working different now, event though no settings or options have changed.

**Comment by kburtram** [comment]
Sounds good.  As long as the behavior is as expected (i.e., how it was prior to the breaking regression) then I'm sure I'll be fine with the approach 😄.

**Comment by kburtram** [comment]
@anthonydresser please let me know how this investigation is going?  I'd like to include a fix in the insiders build if possible so folks can finish up demo prep.  I think @alanrenmsft may have some bandwidth to help with the investigation today if anything can be paralleled.  Thanks!

**Comment by anthonydresser** [comment]
There's nothing really to do in parallel since its just 1 problem. worst case scenario we can just try and be smart and create our own min and max.

**Comment by kburtram** [comment]
Closing based on https://github.com/Microsoft/azuredatastudio/pull/3070.
