### ISSUE TITLE
Dragging an active connection from the connected green state to within a pre connected Server group looses the connection state. 

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3049]
Issue Type: <b>Bug</b>

Create a connection to SQL Server.

Create a Server group.

Drag the connection to the Server group. The connection state is Red now.

<img width="371" alt="image" src="https://user-images.githubusercontent.com/22312581/47732437-6cac5700-dc23-11e8-8a09-26bc83a58f76.png">

Azure Data Studio version: Azure Data Studio 1.2.1-insider (f7d92caae51a679934a9f945ea0b48e89f02e1de, 2018-10-23T00:30:42.493Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.81GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/3EC7DA19-0CFB-44EB-8B97-3961178BD401/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
import|Mic|0.3.0
sql-vnext|Mic|0.7.2

</details>

**Comment by kburtram** [comment]
@ronychatterjee thanks for opening the issue.  We're tracking this problem with https://github.com/Microsoft/azuredatastudio/issues/632.  So I'll close as a duplicate.  Ping me if this is blocking one of your demos.
