### ISSUE TITLE
Support running shell commands from notebooks

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#3053]
It would be great to run shell commands from notebooks. In particular, this is helpful for install Python libraries.

Example:

! pip install pandas
! pip install numpy
! pip install matplotlib
! pip install statsmodels

import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt

**Comment by kevcunnane** [comment]
Is this against a cluster, or local? I'm pretty sure there's a %%bash magic for local execution

**Comment by chlafreniere** [comment]
This works today and was fixed when we fixed our %PATH% issues
