### ISSUE TITLE
Messages collapses whitespace

### ISSUE THREAD

**Issue by stevenreddie** [Microsoft/azuredatastudio#3054]
Issue Type: <b>Bug</b>

Output rendered into the Messages pane has each span of space characters collapsed to a single space. For something that I'm working on at the moment the whitespace is significant. ADS's current behavior makes it extremely difficult to debug. SSMS works the way that I expect.

STEPS:
1. Execute the following line:
```
        PRINT '1   2                           3      4               5'
```
2. Observe that the output in the Messages pane is rendered with a single space between each number rather than a variable number of spaces.
3. Repeat in SSMS and observe that the output does have the variable number of spaces as contained in the string passed to PRINT.

Azure Data Studio version: Azure Data Studio 1.2.2-insider (98d06b28923ad778491dd47dfa337939b4ee4efd, 2018-10-27T00:43:14.137Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_12577790|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by stevenreddie** [comment]
#3011 may be related

**Comment by BrianStork** [comment]
Please let us configure the font family for the MESSAGES pane. A proportional font in an IDE seems like an odd choice, and the ability to configure the font would be greatly appreciated.
