### ISSUE TITLE
Invalid Column Name when column names are in fact valid

### ISSUE THREAD

**Issue by gituser227** [Microsoft/azuredatastudio#3055]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 18.0.0
---

Steps to Reproduce:

1. Enter a TSQL Update command, making sure to use valid column names.

There are red lines under column names, with warning "Invalid column name [column-name-here]."
The column names are perfectly valid, and the command will execute successfully, so there should be no "Invalid column name" warning for valid column names.

**Comment by kburtram** [comment]
@gituser227 you may try the `Refresh Intellisense Cache` to see if that helps.

Also I see you're on an older version of Azure Data Studio.  I'd recommend updating to the latest build at https://github.com/Microsoft/azuredatastudio/releases/tag/1.1.4.  We fix a lot of bugs each month so hopefully it's worth the hassle of updating.

**Comment by gituser227** [comment]
Thanks for the fast response and good advice.

I've updated to latest release and the issue does not appear there....and to boot, there's so much more to love. Kudos to the team.  It seems I was quite far behind.

**Comment by yualan** [comment]
Here's a good summary of those changes: https://cloudblogs.microsoft.com/sqlserver/2018/10/18/the-october-release-of-azure-data-studio-is-now-available/ :)

**Comment by gituser227** [comment]
> Here's a good summary of those changes: https://cloudblogs.microsoft.com/sqlserver/2018/10/18/the-october-release-of-azure-data-studio-is-now-available/ :)

Thanks Alan!  Keep up the great work!

**Comment by kburtram** [comment]
@gituser227 please note that we are actively working on a different Intellisense bug with the latest release (details at https://github.com/Microsoft/azuredatastudio/issues/3012).  We'll have a fix for that issue in the Nov. release next week in case you run into that.
