### ISSUE TITLE
"overwrite" mentioned where "override" was meant

### ISSUE THREAD

**Issue by breyed** [Microsoft/azuredatastudio#3058]
Issue Type: <b>Bug</b>

In user settings, the text on top says "Place your settings here to overwrite the Default Settings." That should be "override", not "overwrite". If I overwrote the default settings, they would be gone and I couldn't fall back to them.

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@breyed this text is coming from the VS Code source code that we consume.  Generally we like to have these issues fixed upstream and the we pick up the fixes in subsequent source code refreshes.  You may consider opening a similar issue upstream against https://github.com/Microsoft/vscode.

**Comment by breyed** [comment]
Moved to Microsoft/vscode#62407.
