### ISSUE TITLE
Create a Task for "View Spark Jobs"

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#3062]
Issue Type: <b>Bug</b>

On the right click Manage of the HDFS end point create a new task "View Spark Jobs". 

If this is too late for Novemeber release and requires extensive testing, lets target this for December. 

If this is is less than 30 mins work and does not introduce regressions with just redirecting to the URL, then let's take this.

Azure Data Studio version: Azure Data Studio 1.2.1-insider (f7d92caae51a679934a9f945ea0b48e89f02e1de, 2018-10-23T00:30:42.493Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/3EC7DA19-0CFB-44EB-8B97-3961178BD401/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Implemented
