### ISSUE TITLE
SELECT 1000 on a table is creating a saved connection

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3065]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to a server 
2. SELECT 1000 on a table in one of the databases in the server

Expected: New editor window is opened but OE saved connections are not impacted

Actual:  A new saved connection is created in OE

**Comment by kburtram** [comment]
This appears to be caused by https://github.com/Microsoft/azuredatastudio/commit/7f66087d8c7758c07bf0735194f03aafebb47548.  @alanrenmsft is looking at a fix.  

I've reverted the change out of **release/1.2** branch while a fix is prepared and validated.

**Comment by shueybubbles** [comment]
probably just can remove the block in connectIfNotConnected that sets save to true. no need to autosave connections made from command line

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by alanrenmsft** [comment]
fix merged.

**Comment by shueybubbles** [comment]
Thanx for cleaning up after me!
Was this bug caught by a test? If not where could a test be added to cover this?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by alanrenmsft** [comment]
@shueybubbles Karl caught it by manual testing, I am not sure about the automated tests, I will let @kburtram  answer it.
