### ISSUE TITLE
Canceling Restore DB task doesn't actually cancel the task

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#3074]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Use the Restore Database dialog to restore a database
2. In the Task viewlet use the Cancel context menu to cancel task

Expected: Restore is canceled and no database is restored

Actual: Task shows as canceled in the Task viewlet, but then a DB showing in Restoring state in OE, then task shows as completed successful, and the database is successfully restored.

> Note that WideWorldImporters shows as Restoring even though Restore task was canceled.

![image](https://user-images.githubusercontent.com/599935/47868371-43293200-ddc1-11e8-8d12-1aa87c50b8ea.png)

**Comment by udeeshagautam** [comment]
Seems like SSMS has similar behavior

![restorecancel](https://user-images.githubusercontent.com/46980425/58352371-2f5a2180-7e20-11e9-83b8-bffb4b264809.gif)

**Comment by kburtram** [comment]
Closing as "by design" since SSMS behaves the same way.
