### ISSUE TITLE
Computer name in Manage page looks truncated

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3076]
Issue Type: <b>Bug</b>

Connect to SQL endpoint of SQL Server 2019 cluster and view Manage page. Note the computer name is likely meant to be mssql-master-pod but is truncated. No hovertext available to confirm this.

![image](https://user-images.githubusercontent.com/10819925/47869903-65bd4a00-ddc5-11e8-8288-c763dab55aeb.png)

Azure Data Studio version: Azure Data Studio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T03:48:03.475Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Users/kevcunnane/Downloads/insiders_nov/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_770236|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
sql-vnext|Mic|0.8.0

</details>

**Comment by kburtram** [comment]
Closing older issues.  This should be addressed as part of dashboard feature work.
