### ISSUE TITLE
SQL 2019 Preview Extension install failed

### ISSUE THREAD

**Issue by dnethi** [Microsoft/azuredatastudio#3078]
Issue Type: <b>Bug</b>

Installing SQL 2019 preview extension consistently fails for me.
ADS version 1.2.3.

Error:
This extension is not installable on any currently installed products.

![image](https://user-images.githubusercontent.com/43253513/47870603-2d1e7000-ddc7-11e8-945e-d3135528a143.png)

Install log:
--------------
11/1/2018 11:04:57 AM - Microsoft VSIX Installer
11/1/2018 11:04:57 AM - -------------------------------------------
11/1/2018 11:04:57 AM - vsixinstaller.exe version:
11/1/2018 11:04:57 AM - 15.8.3252
11/1/2018 11:04:57 AM - -------------------------------------------
11/1/2018 11:04:57 AM - Command line parameters:
11/1/2018 11:04:57 AM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\dinethi\AppData\Local\Packages\Microsoft.MicrosoftEdge_8wekyb3d8bbwe\TempState\Downloads\sql-vnext-0.7.2-win-x64 (2).vsix
11/1/2018 11:04:57 AM - -------------------------------------------
11/1/2018 11:04:57 AM - Microsoft VSIX Installer
11/1/2018 11:04:57 AM - -------------------------------------------
11/1/2018 11:05:21 AM - Initializing Install...
11/1/2018 11:05:24 AM - Extension Details...
11/1/2018 11:05:24 AM - 	Identifier         : sql-vnext
11/1/2018 11:05:24 AM - 	Name               : SQL Server 2019 (Preview)
11/1/2018 11:05:24 AM - 	Author             : Microsoft
11/1/2018 11:05:24 AM - 	Version            : 0.7.2
11/1/2018 11:05:24 AM - 	Description        : Support for configuring and managing a cluster with scale-out SQL Server and big data sources.
11/1/2018 11:05:24 AM - 	Locale             : en-US
11/1/2018 11:05:24 AM - 	MoreInfoURL        : 
11/1/2018 11:05:24 AM - 	InstalledByMSI     : False
11/1/2018 11:05:24 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
11/1/2018 11:05:24 AM - 
11/1/2018 11:05:25 AM - 	SignatureState     : Unsigned
11/1/2018 11:05:26 AM - 	Supported Products : 
11/1/2018 11:05:26 AM - 		Microsoft.VisualStudio.Code
11/1/2018 11:05:26 AM - 			Version : 
11/1/2018 11:05:26 AM - 
11/1/2018 11:05:26 AM - 	References         : 
11/1/2018 11:05:26 AM - Signature Details...
11/1/2018 11:05:26 AM - 	Extension is not signed.
11/1/2018 11:05:26 AM - 
11/1/2018 11:05:26 AM - Searching for applicable products...
11/1/2018 11:05:26 AM - Found installed product - Microsoft Visual Studio 2010 Shell - Integrated Mode
11/1/2018 11:05:26 AM - Found installed product - Microsoft Visual Studio 2012 Shell (Integrated)
11/1/2018 11:05:26 AM - Found installed product - Microsoft Visual Studio 2013 Shell (Integrated)
11/1/2018 11:05:26 AM - Found installed product - Global Location
11/1/2018 11:05:26 AM - Found installed product - ssms
11/1/2018 11:05:26 AM - Found installed product - ssms
11/1/2018 11:05:26 AM - Found installed product - ssms
11/1/2018 11:05:26 AM - Found installed product - Visual Studio Enterprise 2017
11/1/2018 11:05:26 AM - Found installed product - Microsoft SQL Server Data Tools for Visual Studio 2017 (SSDT)
11/1/2018 11:05:26 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.93GB (5.35GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.34.0
profiler|Mic|0.2.0
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@dnethi the VSIX file extension is registered to the Visual Studio VSIX installer (the UI in your screenshot).  That tool won't install extensions into Azure Data Studio.  To side-load an extension with a VSIX file try using the "Install extension from VSIX" item in the File menu.

![image](https://user-images.githubusercontent.com/599935/47872458-e2532700-ddcb-11e8-8cca-3dc01ada09e6.png)

**Comment by dnethi** [comment]
thanks @kburtram that worked.
