### ISSUE TITLE
Wizard framework should let 1st input box be focused by default

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3079]
We need to support default focus in the wizard. Example:
- Open create external data wizard, and choose Next
- See Create Database Master Key page
- Try to enter password & realize you can't! Have to click in instead.

![image](https://user-images.githubusercontent.com/10819925/47877686-b9d22980-ddd9-11e8-9582-810ab7fa0bf6.png)

Default focusability will help here. Probably want this controllable by the extension

**Comment by kburtram** [comment]
Closing old tasks.  Please log a bug against an extension if this is impacting a customer-facing scenario.  Thanks!
