### ISSUE TITLE
Extensibility: Help bubbles should be clickable

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3080]
Steps to Reproduce:

1. Open the create external data wizard & get to the "Create a connection to your data source" page
2. Try clicking on the help icon for help
3. It fails! Have to hover for several seconds instead.

Compare to the Azure Portal - clicking on help icons shows the help text in addition to having hover support.

**Comment by alanrenmsft** [comment]
did a quick research, code is here: src\sql\parts\modelComponents\formContainer.component.ts
in order to achieve this we will need to create a custom bubble component and handle the events to make sure it can appear and disappear properly.

I will leave this issue in backlog for future triage.

**Comment by kburtram** [comment]
Closing old tasks.  Please open as a bug against an extension if this is still needed.
