### ISSUE TITLE
Create External Data: Clicking cancel during connection validation should not exit wizard

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3081]
Steps to Reproduce:

1. Open create external data wizard and get to the connection configuration page
2. Enter invalid information, such that on clicking "Next" the wizard will spin for 30seconds before timing out and showing error
3. Click cancel to stop the connection validation (so that you can, for example, fix the connection information

Expected:
- Validation is canceled, but wizard is still open
Actual:
- Wizard immediately exits

**Comment by kevcunnane** [comment]
@geleems please take a look at this one.

**Comment by kburtram** [comment]
Closing old tasks.  Please log a bug if still impacted by this issue.
