### ISSUE TITLE
Entire Checkbox including label should be clickable

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3082]
Steps to Reproduce:

1. Connect to an Azure SQL DB with firewall closed, so that the Create New Firewall Rule dialog shows up
2. Try to click on the "Add my subnet IP range" checkbox.

Expected:
- Clicking anywhere in the "box" around the checkbox + the label will work
Actual:
- You have to very precisely click inside the Checkbox circle, at least on macOS. 

This is really inconvenient and a gap vs. any standard web / windows app. We should look to fix.

**Comment by kburtram** [comment]
Closing older issues.  Thanks for reporting!
