### ISSUE TITLE
Create External Data against empty Azure SQL DB fails

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3083]
Steps to Reproduce:

1. Connect to a SQL Server 2019 instance (I tested against the SQL Server master instance in the cluster)
2. Create External Data -> SQL Server -> enter credential information for a newly created Azure SQL Database. It has no user tables in it
3. Get to the Create External Table page and expand the database node.

Expected:
- Database is expanded and nothing is shown / we get some kind of non-checkable node showing no tables/views were found

Actual:
- Get the following error. Is this failing during metadata querying?

![image](https://user-images.githubusercontent.com/10819925/47880752-4b916500-dde1-11e8-94dc-3a38ff795eac.png)
```
105083;The following columns in the user defined schema are incompatible with the external table schema for table 'T2bccdf4ea3cd42': user defined column type: ([TABLE_TYPE] NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS) vs. detected external table column type: ([TABLE_TYPE] NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS). The detected external table schema is: ([TABLE_CATALOG] NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS, [TABLE_SCHEMA] NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS, [TABLE_NAME] NVARCHAR(128) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL, [TABLE_TYPE] NVARCHAR(10) COLLATE SQL_Latin1_General_CP1_CI_AS)
```

**Comment by geleems** [comment]
It is fixed. The PR for this fix is posted.
