### ISSUE TITLE
Create table snippet broken: No way to tab through and complete all entries in the snippet

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3084]
I tried using the sqlCreateTable snippet to quickly create a table. We have a situation you literally cannot create a table by tabbing through and entering all values. Specifically 2 issues break it and cause intellisense errors:
- 1st column has `[ColumnName]Id` as the name, which is broken (all things need to be inside the [ ] to pass engine validation)
- 2nd and 3rd columns have `[NVARCHAR]` as the type, which is invalid

The correct way to solve is to have tab targets so you can tab through all of these, but leave the actual values at defaults that a) compile and b) make sense.

**Comment by kburtram** [comment]
@kevcunnane if a fix for this is merged by EOD tomorrow we can take for Nov.

**Comment by kburtram** [comment]
Closing as fixed based on #3094.
