### ISSUE TITLE
Create external data: Master key password not validated until going through connection page

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3086]
Steps to Reproduce:

1. Open create external data wizard and go to master key page
2. Enter a really simple password that won't pass validation (e.g. 4 letters, no uppercase or special chars)
3. Click next

Expected:
- Wizard blocks with error
Actual:
- Wizard goes to next page. On completing connnection info & clicking next, then you get a "password is not complex enough" error. This is very confusing to the user as it might be related to the password field on the current page.

**Comment by geleems** [comment]
It works without the issue after full build. Can you test it again in your end?

**Comment by kevcunnane** [comment]
Interesting - I can't repro. Will close for now.
