### ISSUE TITLE
Create External Data: Missing horizontal scrollbar in table mapping page

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3087]
Issue Type: <b>Bug</b>

1. Make Azure Data Studio small and run Create External Data wizard
2.  Get to the table mapping page and ensure visible area is smaller than the table size

Expected:
- Get a horizontal scrollbar for that section
Actual:
- Table is truncated horizontally

![image](https://user-images.githubusercontent.com/10819925/47882948-70d5a180-dde8-11e8-89a5-d56b082a2bed.png)

Azure Data Studio version: Azure Data Studio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T03:48:03.475Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|/Users/kevcunnane/Downloads/insiders_nov/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
@geleems is this fixed? Triaging into June for confirmation.

**Comment by geleems** [comment]
This was fixed.
