### ISSUE TITLE
Extensibility: Only the 1st error message in a wizard is shown, until it's closed

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3088]
- Azure Data Studio Version: November preview

Steps to Reproduce:

1. Open Create External Data wizard and target Oracle
2. get to table mapping page, expand database and click on each table in rapid succession. Right now, this is causing errors to appear (this is a separate problem from bug I'm reporting)
3. Note that you only ever get 1 error message, and it never changes even if new errors are added
4. If you close the error message and keep clicking, new messages appear.

Expected:
- We pile up multiple error messages on top of one another, or at least update to show latest error message instead of staying on the 1st one

Actual:
- Only ever see 1st error message

**Comment by kburtram** [comment]
Closing older issues.  Please log a bug against a particular product feature\extension if this still occuring.  Thanks!
