### ISSUE TITLE
Create External Table: should clear column mapping cache when go previous page then next again

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3089]
Issue Type: <b>Bug</b>

- Open Create External Data wizard and connect to Oracle
- Get to table mapping page on create external data wizard
- Expand database and rapidly click a bunch of tables until you error
- The column mappings for current table will be empty
- Go back to the connection page and click "Next" again. This reconnects and on expanding databases, clearly updates the list of tables
- Click on the table name which previously errored and showed empty column mapping. 

Expected:
- Should re-query the column mappings and update with correct data
Actual:
- This instantly shows as being empty like before. This shows the cache isn't being cleared out on going back. It's important to do this (which we currently do for the tables cache) so that we can accurately update data and handle weird error cases cleanly.
![image](https://user-images.githubusercontent.com/10819925/47883433-3ec53f00-ddea-11e8-88b0-f5a244cb2555.png)

Azure Data Studio version: Azure Data Studio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T03:48:03.475Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Users/kevcunnane/Downloads/insiders_nov/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
@geleems please confirm this is fixed and close it out, thanks! I believe you already solved this one.

**Comment by geleems** [comment]
this was fixed.
