### ISSUE TITLE
Reorganize create external table UI

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3091]
Issue Type: <b>Bug</b>

Right now the source and target/destination information provided are mixed into different steps.
Could we have step for source info and target info so it would be clear what user is doing?

For example:
step 1: it says Select a Data source, but we have to select destination database

![image](https://user-images.githubusercontent.com/43652751/47885089-a8e0e280-ddf0-11e8-8418-711cc34ae1c0.png)

step 3:  it says create a connection to your Data source, which first require to give a external Data Source Name, which is used in the  destination database

![image](https://user-images.githubusercontent.com/43652751/47885176-f52c2280-ddf0-11e8-9919-7068b06f81a0.png)

Could we put the destination db selection and create External Data Source Name in one step?

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (51.68GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.8.0

</details>

**Comment by kevcunnane** [comment]
Closing, unlikely to fix without major redesign.
