### ISSUE TITLE
Create CI/CD process with Azure Pipelines

### ISSUE THREAD

**Issue by calloncampbell** [Microsoft/azuredatastudio#3098]
VS Code has been set-up in [Azure DevOps](https://dev.azure.com/vscode/VSCode), so why not Azure Data Studio? 

README can then be updated with the build status badge.

**Comment by kburtram** [comment]
This should be setup now.  For example https://github.com/Microsoft/azuredatastudio/pull/3202/checks?check_run_id=31457143.
