### ISSUE TITLE
Dashboard details are slow in loading

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#3099]
- Azure Data Studio Version: master/1.2.3-insider

Steps to Reproduce:

1. Connect to a server. I used an Azure SQL DB for this.
2. Click on the "V" button on the top right to show the server details.

**Expected** - Details shouldn't take a lot of time to show.

**Actual** - Details take a lot of time to show. If the details are collapsed and expanded again, it takes the same amount of time to load. It can be easily cached for a server.

**Comment by kburtram** [comment]
Closing older issues.  This should be address as part of current dashboard feature work.
