### ISSUE TITLE
Dashboard refresh doesn't work when changing user settings

### ISSUE THREAD

**Issue by martinisaksen** [microsoft/azuredatastudio#31]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Add an insight to user settings file.
2. Open Dashboard.
3. Change title for insight in user settings file.
4. Refresh Dashboard.

What I'd expect to see:
I'd expect to see the new title on the insight.

What I see instead:
I see the old title on the insight. Nothing changes.

**Comment by erickangMSFT** [comment]
@martinisaksen The expected feature is not implemented. Currently the layout of dashboard is refreshed only when the dashboard is restarted. Turned it as a suggestion.

**Comment by kburtram** [comment]
Per issue #30, please verify the Query setting when resolving this issue.

**Comment by kburtram** [comment]
Closing out older issues.  We have a major dashboard refactoring that will land in the next few months.
