### ISSUE TITLE
Adding new account

### ISSUE THREAD

**Issue by akonoplenko** [Microsoft/azuredatastudio#3106]
Issue Type: <b>Bug</b>

The following error message appears when signing in to Azure account :

Error adding account
Error: self signed certificate in certificate chain

Reproduce:
- Add an account
- Device Login (enter code -> continue)
- Pick an account
- Go to Azure Data Studio

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.44GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@akonoplenko I haven't been able to repro this.  Can you think of any noteworthy repro details, such as security policies or details regarding the Azure account settings?

**Comment by kburtram** [comment]
Closing due to lack of repro.  Please let me know if you have any additional details that could helps us isolate this problem.
