### ISSUE TITLE
Unable to define Azure Data Studio as the default software for .sql files on Windows

### ISSUE THREAD

**Issue by Tazaf** [Microsoft/azuredatastudio#3109]
- Azure Data Studio Version: 1.1.4

To be more specific, I can _select_ Azure Data Studio as the default software for `.sql` files, but when I do that, the OS reverts back to the previously selected software.
So if I had VS Code as the default software, and I were to select Azure Data Studio as the new default, then nothing would happen, and VS Code would still be the default software.

![image](https://user-images.githubusercontent.com/7702322/47998308-2497a380-e0ff-11e8-9258-b61939c4cd58.png)

Note that this behaviour is consistent wether I'm using the Windows Settings app to do so, or the "Open with..." command in a context menu.

![image](https://user-images.githubusercontent.com/7702322/47998337-3d07be00-e0ff-11e8-9a92-1169e48b5bde.png)

**Comment by kburtram** [comment]
@Tazaf I'm not able to repro this issue.  The default file association mechanism is handled outside the app by Windows, so you may try to see if there's something going at that level.  Is this mechanism working correctly when updating the default file handler for other file extensions?

**Comment by Tazaf** [comment]
Hi, @kburtram 

Yes, the mechanism is working when I try to change the default of another file extension (like `.txt`). I can switch back and forth between VS Code, NotePad or WordPad.

I cannot do that for `.sql` files. I can set VS Code as the default handler for this file type, but whenver I try to change it for another software, such as Azure Data Studio or simply NotePad, it does not work. It even remove VS Code as the default and reverts back to Notepad++, which I uninstall...

One thing strange, though, is that I can't define Azure Data Studio as the default handler for any file type. When trying to do so through the contextual menu of a `.txt` file, for example, I can select ADS and check the box for always opening `.txt` files with this software, but... it does not do anything. But this is also the case if I select Word as the default for `.txt`...

Really, I'm confused.

I'm currently exploring my options for setting a default handler for a specific file type in Windows (already tried going though UI options as well as the `assoc`/`ftype` command combo).
I agree that this looks like something more related to Windows than ADS per se. I posted this issue here because I discover my problem with ADS.

Anyways... thanks for your response. I suppose you could close the issue ?

**Comment by Tazaf** [comment]
OK, I resolved the problem using `regedit`. I had to manually change the value of the `HKEY_CLASSES_ROOT\sql_auto_file\shell\open\command` key to the path to the ADS executable.

This works (although the file icon does not reflect the fact that it opens with ADS) 🎉
