### ISSUE TITLE
files.hotExit does not work for me (mac, Version 0.24.1)

### ISSUE THREAD

**Issue by paolopiaggio** [Microsoft/azuredatastudio#3110]
Steps to Reproduce:

1. Open a new tab and write something into it
2. Close SqlOps - this still shows the dialog that warns about "Your changes will be lost if you don't save them"
3. Open SqlOps again -> no session/tab restored

I tried with both options:
- onExit
- onExitAndWindowClose

**Comment by kburtram** [comment]
@paolopiaggio we've made several bug fixes since 0.24.1.  Could you please see if the issue repros on the latest build, currently https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.4?

**Comment by paolopiaggio** [comment]
sorry about that, was sure I got the latest version. all good with 1.2.4 👍
