### ISSUE TITLE
Row count not updating in status bar

### ISSUE THREAD

**Issue by charlieridley** [Microsoft/azuredatastudio#3111]
Issue Type: <b>Bug</b>

Row count in status bar does not update when running different queries. When switching to another tab and then switching back it updates to the correct count

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2698 v4 @ 2.20GHz (4 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (6.64GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.2.0

</details>

**Comment by kburtram** [comment]
This should be fixed in the latest build available at https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.4.  Please reactive if the issue persists on the latest build.
