### ISSUE TITLE
Create Script for external table fails

### ISSUE THREAD

**Issue by bweissman** [Microsoft/azuredatastudio#3112]
- Azure Data Studio Version: 1.1.4

Steps to Reproduce:

1. Right mouse click on an external table
2. Script as Create

you get: No script was returned when scripting as Create on object Table

**Comment by kburtram** [comment]
I'll close this as a duplicate of https://github.com/Microsoft/azuredatastudio/issues/3119 to consolidate issues.  Thanks for reporting!
