### ISSUE TITLE
Scrolling does not work properly in the Notebook

### ISSUE THREAD

**Issue by ranvijaykumar** [Microsoft/azuredatastudio#3116]
Issue Type: <b>Bug</b>

I have a cell that produces a long text output. Aparently, that interferes with the scrolling, and the scrolling stops with the text in the center of window.

If I move the cursor all the way to the right, between the scroll bar and the right hand boundary of cells, I am able to scroll again.

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kevcunnane** [comment]
This has been fixed in latest, or at least we're no longer able to reproduce this. Please reopen if you run into it in the (soon to come) December release.
