### ISSUE TITLE
Notebook cells should show execution order

### ISSUE THREAD

**Issue by ranvijaykumar** [Microsoft/azuredatastudio#3117]
Issue Type: <b>Feature Request</b>

Notebooks allow us to move among the cells  and execute those in random order. Classical notebooks track the execution order using a number on the left hand side pane. In the ADS notebook we do not have any such indicator, which makes tracking difficult.

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chlafreniere** [comment]
@kevcunnane added this feature for February.
