### ISSUE TITLE
Autocomplete does not list PROSE in the import statement

### ISSUE THREAD

**Issue by ranvijaykumar** [microsoft/azuredatastudio#3118]
Issue Type: <b>Bug</b>

While importing pandas, autocomplete shows pandas in the list of packages when I type 'pan'. However, when I type 'pro' I do not see prose in the autocomplete list.

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (20.10GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by ranvijaykumar** [comment]
Just checked in Jupyter, and it does not work there too. Indeed seems like an upstream issue.

**Comment by kevcunnane** [comment]
Closing as somethign we can't fix.
