### ISSUE TITLE
'Failed to reinstall dependencies' error while executing 'reinstall notebook dependencies' command

### ISSUE THREAD

**Issue by ranvijaykumar** [Microsoft/azuredatastudio#3120]
Issue Type: <b>Bug</b>

This the error I get:

Failed to reinstall dependencies: EPERM: operation not permitted, unlink 'C:\Users\***redacted***\.scaleoutdata\python\0.0.1\python.exe'

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.91GB (19.47GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
This has been fixed in the latest insiders build, and will go out in the April release.
