### ISSUE TITLE
Not possible to use edit data for a table that has 0 rows and 1 column

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3127]
Steps to Reproduce:
1. Create a blank table that only has 1 column
2. Run edit data on that table
3. Enter data in the cell and try to save it

Expected behavior: There is some way to commit your change
Actual behavior: There is no way to commit your change

I'd suggest that the new "new row" bar show up as soon as the user enters text in the existing one instead of when the user changes cells after entering text.

**Comment by Charles-Gagnon** [comment]
Opened #4431 for further improvements
