### ISSUE TITLE
Intellisense intermittent on remote SQL server connection

### ISSUE THREAD

**Issue by MartinAnthonyBooker** [Microsoft/azuredatastudio#3128]
Issue Type: <b>Bug</b>

Steps to reproduce:
Establish connect to SQL Server  -> new query -> Select target database from dropdown:

SELECT * FROM tbl.....     --( "...". indicates pause in typing while waiting for suggestions )

Expected result: Editor intellisense displays list of db objects whos name contains 'tbl' alongside other snippet suggestions

Actual result: MIXED depending on connection

Connecting to SQL server on local machine:
As expected, works correctly. All expected candidate db objects along with snippet suggestions are returned.

Connecting to remote SQL server instance via vpn and repeating test:
Intermittent. 
Occasionally works returning both intellisense and snippet suggestions after multiple refreshes of intellisense cache. But more often than not only returns snippet suggestions, no intellisense db object items returned.

Further info.
() Consistent across multiple unrelated remote sql servers via different vpn clients. ( same fail result )
() Intellisense works as expected in SSMS v17 installed on the same test machine and connected to the same remote servers
() Application displays no progress / busy indicator when working nor error popup to indicate failure

Azure Data Studio version: azuredatastudio 1.1.4 (5d6390505643df3edd6f734c80082006efbeff5e, 2018-10-29T20:34:47.838Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.78GB (26.36GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.34.0
sql-search|Red|0.2.1

</details>

**Comment by MartinAnthonyBooker** [comment]
Update: may or may not be related to this issue here so feel free to mark resolved / closed etc
[https://github.com/Microsoft/azuredatastudio/issues/3012](url)

**Comment by kburtram** [comment]
We did take a fix for this that is included in https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.4.  Please let me know if the issue persists on that build.  Thanks!

**Comment by thiagobucca** [comment]
I have this problem also, i'm on 1.2.4 so unfortunately the issue persists, also, Intellisense for table names doesn't work if its followed by a suffix, like this: 

`select * from tablename` > working (but only sometimes like @MartinAnthonyBooker said)

'select  * from  tablename WITH (NOLOCK)' not working
