### ISSUE TITLE
Create external table error msg behavior is cleared when clicking previous button, but carried over by clicking previous step in the left bar

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3137]
Issue Type: <b>Bug</b>

Steps to repro: 
1) Select create external table

2) Give wrong credential for step 3. got error msg: 
![image](https://user-images.githubusercontent.com/43652751/48084441-8feb7f00-e1ac-11e8-8539-78553bc4d859.png)

3) Click Previous, the error msg is cleared.

4) Give wrong credential again and get the error msg. Now click 1 in the left bar, we can see the error msg is on the top.
![image](https://user-images.githubusercontent.com/43652751/48084671-30da3a00-e1ad-11e8-8858-16b2b0d00857.png)

Expected:
 Show error msg or not should be the same by clicking Previous or clicking the previous step from the left bar.

Azure Data Studio version: azuredatastudio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T04:31:37.329Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (56.62GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you are still impacted by this issue.  Thanks!
