### ISSUE TITLE
Create external table can't back and forth from the left bar

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3141]
- Azure Data Studio Version:

Steps to Reproduce:

1. Select Create external table 
2. go until step 3
3. Click 1 from the left bar, then step 2 and step 3 are not clickable.

Expected:
If only brow the previous step, we should be able to switch among those steps.

**Comment by kburtram** [comment]
Closing older issues.  Thanks for logging this suggestion!
