### ISSUE TITLE
Notebook port: editor not auto sizing on initial load so scrollbar is shown

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3144]
Steps to Reproduce:
- Open the churn analysis sample attached (I duplicated content a bunch of times to make it bigger)
- Scroll down, and see how some editor cells have scrollbar and are initially scrollable

Note that resizing bigger / smaller works, but scroll bar is always there and the initial scroll issue hides some content.

[largechurn.ipynb.zip](https://github.com/Microsoft/azuredatastudio/files/2555523/largechurn.ipynb.zip)

1.

**Comment by chlafreniere** [comment]
Closed along with #3236.
