### ISSUE TITLE
Can intellisense expand column names?

### ISSUE THREAD

**Issue by ThisNoName** [microsoft/azuredatastudio#3152]
In almost all SQL intellisense, when you type Tab after * or sometable in the following example, all column names can be auto filled.  But I can't figure out where this is.  Can someone give a hint?  Thanks.

SELECT * FROM sometable
INSERT INTO sometable

- Azure Data Studio Version: 1.2.4

**Comment by opus131** [comment]
Any news here? This is a MAJOR adoption blocker...

**Comment by vholmer** [comment]
Bumping this, Azure Data Studio is unusable without this feature.

**Comment by FascinateDK** [comment]
Any news here ?

**Comment by Michaeljohannessen** [comment]
Asking for the same feature, could be awesome to implement!

**Comment by CallSign-Filter** [comment]
Bumping to keep this alive... please implement!!!

**Comment by asmith3006** [comment]
I too will bump this to ask you to implement

**Comment by adnanberberovic** [comment]
While I am using ADS I feel like I shouldn't simply because star expansion is missing. Please, implemen this.

**Comment by rajmandalia** [comment]
Bump.

**Comment by JeffBusterCase** [comment]
Bumping, this feature would be insane.

**Comment by henkers** [comment]
Please add this. The lack of this feature slows me down a lot. It is biggest reason why I'm not moving over to ADS. 

Thank you.

**Comment by CallSign-Filter** [comment]
To all who have been holding your breath. This feature as well as many many others that Azure Data Studio are lacking are available in IntelliJ IDEA / Datagrip.

I did not make the transition earlier because I needed to log into my MSSQL DB on my Mac through Kerberos and I thought ADS was the only way to do it. I figured it out with IntelliJ and now I am permanently getting rid of ADS.

**Comment by cotyhuang** [comment]
Really need it, please implement it asap.

**Comment by aisbergde** [comment]
This missing feature is one major reason why use other software to work with sql server. For example SSMS, where I can use the graphical design editor to expand, or some SSMS extensions doing this job.

**Comment by FirebirdDP** [comment]
It will be a nice addition.  I just need a way to bring all the columns into the query without typing all of them.

**Comment by AnonnyMomo** [comment]
Seems like the more people that ask for this feature, the less likely MS are to implement it lol.

Yup, definetly need this or else SSMS is never gonna get uninstalled.

**Comment by DaveBabler** [comment]
I still would like to see this feature, has anyone from MS commented on this?

**Comment by vholmer** [comment]
Hi, just bumping again. @alanrenmsft is work being done on this feature?

**Comment by aasimkhan30** [comment]
@robolize @henkers, this feature is added in the insider's version of ads. Please give that feature a try and let us know if you have any feedback. 
It can used by placing the cursor at '*" and pressing ctrl+space (ads shortcut for intellisense suggestion).

**Comment by ThisNoName** [comment]
@aasimkhan30   Hi, thanks for the update.  SELECT * appears working.  What about Insert?  Is it possible to do something like this?

insert into sometable ( ... ...  ctrl+space here, column list here, probably excluding identity column

**Comment by aasimkhan30** [comment]
@ThisNoName can you please file a new issue for that feature? Thank you!

**Comment by henkers** [comment]
> @robolize @henkers, this feature is added in the insider's version of ads. Please give that feature a try and let us know if you have any feedback. It can used by placing the cursor at '*" and pressing ctrl+space (ads shortcut for intellisense suggestion).

@aasimkhan30 👍 Thank you so much for this. I can confirm it is working for me on Windows and Mac. 

(Apologies for the late reply)

**Comment by scredmond** [comment]
I'm on version 1.36.1. This feature is not working.
