### ISSUE TITLE
Saving indicator please

### ISSUE THREAD

**Issue by paladin2005** [microsoft/azuredatastudio#316]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
- Query large volumen of data (about 340k rows), sqlopstudio no display nothing until finish, after a long time I have results ok.
      Feature:
         * Would be nice display some data while fetching 
- When finish, I just want save data to CSV, but long time waiting and no saving indicator, after save... file is automatic open in editor (60 mb) of data.
     Feature:
        * Save directly to CSV/Excel/Json without query/display the data (like 'Run to file'), very useful in large volumen of data.
        * Disabled/Enable open file automatic after create CSV/Excel/Json

Thanks and sorry my english.
Nice job out there.

**Comment by JohnyL** [comment]
As per 0.30.6, the message reporting that file is created does appear, but there's no indicator progress when file is being saved to disk. Any info on that?
