### ISSUE TITLE
DacFx import/export wizard Tasks

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#3163]
**Export**
- [x] Add DacFx export handling to SqlToolsService
- [x] Create wizard to select parameters for export
- [x] Show progress of export in Task History
- [x] Add command palette command for export wizard
- [x] Add context menu action for export wizard
- [x] Clicking cancel on Task History item cancels the ongoing export

**Import**
- [x] Add DacFx import handling to SqlToolsService
- [x] Create wizard to select parameters for import
- [x] Show progress of import in Task History
- [x] Add command palette command for import wizard
- [x] Clicking cancel on Task History item cancels the ongoing import

**Deploy/Upgrade**
- [x] Add "Generate Script" button for deploy scenario 
- [x] Open generated script when Task History item is clicked on
- [x] Add Data loss page for upgrade scenario

**General**
- [x] Add telemetry
- [x] Add tests to SqlToolsService for these scenarios

**Needed for Release**
- [x] Rename extension to include DacFx import/export

**Comment by joshbooker** [comment]
@kisantia Nice feature!  I built the branch `feature/dacfxexport` and tried your wizard, but the .bacpac did not export.  Is there something I've done wrong?

Also I found that when I change the bacpac location, the default location still shows on the last page of the wizard.  Lastly, it would be nice is the location defaulted to the current root path open in the file explorer.

Thanks for listening.

**Comment by kisantia** [comment]
@joshbooker Thanks for the feedback! There's a dependency on the SqlToolsService, so you won't be able to run it yet. We hope to have something you can try out by tomorrow.

**Comment by joshbooker** [comment]
@kisantia Thanks for your reply. 

**Question:** it appears the DacFx Script action is not included here:

https://github.com/Microsoft/sqltoolsservice/pull/728

Any chance of adding the script action before this merges?  

Scripting changes rather than publishing directly to database is really a important scenario...essential for maintaining the DEV to DBA relationship. :-)

Thanks for listening.
