### ISSUE TITLE
Agent Jobs css File (jobs.css) Includes Non-Scoped CSS for actionbar-container

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3165]
While working on notebooks, I noticed that there was a 10px top padding for any actionbar-container that I created. 

In jobs.css, we have the following, which appears to be the culprit:

```
.actionbar-container .monaco-action-bar > ul.actions-container {
	padding-top: 10px;
}
```

I was able to overwrite this for my own purposes, but it would probably be good to fix to avoid confusion in the future.

**Comment by abist** [comment]
Fixed in this commit - https://github.com/Microsoft/azuredatastudio/commit/198f243181d11fee7d23cf13b361cd4d05bbb57d

I accidentally pushed to master directly, but there were only string changes and I tested it.
