### ISSUE TITLE
TypMoq should be updated to 2.1.0

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3170]
The version of TypeMoq we use is 0.3.2, way behind 2.1.0. I took a look at upgrading, but we'll have to update a bunch of test code and fix test regressions caused by breaking changes to the framework.

The benefits of updating:
- You can define mocks of interfaces instead of being forced to create a dummy implementation
- A lot more APIs to make use of when testing
- Easier to keep on a recent version since it's now a lot more stable post 1.0 release.

**Comment by kburtram** [comment]
Closing older issues.
