### ISSUE TITLE
Cannot see Installed Extenstions

### ISSUE THREAD

**Issue by AvnishVashist** [Microsoft/azuredatastudio#3174]
- Azure Data Studio Version:

Steps to Reproduce:
I installed the version 1.2.4 using the zip file as I don't have the admin privileges to run the .exe directly.
Was able to set up the DB connections easily but not able to see the extensions.
I install them and reload and click on manage as well, nothing appears in front of HOME.
I tried SQL server agent and whoisactive?

Please let me know what I can do.

![image](https://user-images.githubusercontent.com/44881972/48230069-6595ef00-e36f-11e8-9d9d-595356f67662.png)

**Comment by kburtram** [comment]
@AvnishVashist could you please check you have this value in your User Settings `"workbench.enablePreviewFeatures": true`?  If this value is true Agent should show up in the connection dashboard.

**Comment by kburtram** [comment]
Closing based on above response.  Please let me know if that didn't work for you.
