### ISSUE TITLE
Drag & Drop to group makes group name unreadable in light mode

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3175]
Issue Type: <b>Bug</b>

- Use light mode
- Create a group
- Drag a connection over the group

Expected:
- You can read the text
Actual:
- The text is white and our on-hover highlight is close to white, so this means you can no longer read the group text.
![image](https://user-images.githubusercontent.com/10819925/48235712-cd4e3900-e373-11e8-95ae-f5ffc5a46185.png)

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
sql-vnext|Mic|0.8.0

</details>

**Comment by kburtram** [comment]
I'm not seeing this on current builds.  Here is what server drag-and-drop on group looks like on 1.32 build.

![image](https://user-images.githubusercontent.com/599935/129630313-a80a10cb-ba7d-4324-b4f0-e94f11c9bd4d.png)
