### ISSUE TITLE
Messages still doesn't collapse to bottom of page

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3177]
Issue Type: <b>Bug</b>

Run a query such as create database. Collapse messages
Expected:
- Messages goes to bottom of the editor since there's no content
Actual:
- Messages stays 1/3 up the screen. Smallest it'll go is 25%
- It's confusing as below it is empty so it looks like a bug
![image](https://user-images.githubusercontent.com/10819925/48236089-8b25f700-e375-11e8-81b1-edb3fb9adcc1.png)

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.81GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
sql-vnext|Mic|0.8.0

</details>

**Comment by anthonydresser** [comment]
I fixes one issue which was allowing messages to collapse down with respect to results. But there is a different request here which has never been a feature which is allowing the entire results grid to collapse down; which is a feature request that I can handle when I merge in my query editor refactor.

**Comment by kburtram** [comment]
Here is a more recently reply on this issue that I'll capture here since this is the active tracking bug.

> snipped from https://github.com/microsoft/azuredatastudio/issues/5498
>if the query returns enough results to fill the available screen space then the resultgrid should be resizable to fill that space. If the query doesn't return enough results to fill the screen then the messages pane will occupy the available space. There is more discussion of this behavior in #3177. Please let me know if that doesn't address your question.

> I agree that the current behavior is confusing. We had a fix that collapsed the Message to the bottom even when the resultset didn't fill the available area, but that change had several side-effects and needed to be reverted. We're planning to move the Messages into its own tab soon, so we decided to wait for that change rather than try to correct the previous attempt at fixing this.

**Comment by kburtram** [comment]
This is fixed in the June release.
