### ISSUE TITLE
Default connection

### ISSUE THREAD

**Issue by Diego-MX** [Microsoft/azuredatastudio#3178]
Issue Type: <b>Performance Issue</b>

I only have one connection registered in my SQL Operations Studio. 
Still I have to reconnect to that connection every time I start a new session. 
The connection is lost also when a couple of hours go by without running a query, and I have to reconnect again.  
Is it possible to have my session connect on startup and to keep it open?  

Regards from Mexico. 

SQL Operations Studio version: sqlops 0.32.9 (8004776eff330e8980b473b6a2f6faf607164005, 2018-09-19T05:11:56.160Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.59GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    74	 11692	sqlops main
    0	    33	 25436	   shared-process
    0	   131	 27900	   gpu-process
    0	    69	 29012	   window (Issue Reporter)
    0	   154	 34944	   window (daily_Cartera.sql - SQL Operations Studio)
    0	    35	  5856	     extensionHost
    0	    44	  8164	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\MicrosoftSqlToolsServiceLayer.exe" --log-dir C:\Users\Diego\AppData\Roaming\sqlops\mssql
    0	     4	 19340	         console-window-host (Windows internal process)
    0	    11	 28284	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\SqlToolsResourceProviderService.exe" --log-dir C:\Users\Diego\AppData\Roaming\sqlops\mssql
    0	     4	 29036	         console-window-host (Windows internal process)
    0	    17	 34288	       "c:\Program Files\SQL Operations Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.34\MicrosoftSqlToolsCredentials.exe" --log-dir C:\Users\Diego\AppData\Roaming\sqlops\mssql
    0	     4	 30696	         console-window-host (Windows internal process)
    0	    12	 23316	     searchService
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.2.1

</details>

**Comment by yualan** [comment]
Hi Diego, have you tried downloading the latest version https://aka.ms/getazuredatastudio? If you need to retain your settings, you can follow the instructions on the top. The latest version has some improvements for connection that you may want to try.

**Comment by Diego-MX** [comment]
I did try "Check for Updates" and it didn't mention anything. 
Doing the whole thing now.  
Thanks.

**Comment by kburtram** [comment]
This feature hasn't been implemented in the latest build...but you should update in any case 😄.  We haven't provided an auto-update from SQL Ops Studio to Azure Data Studio do to some issue in with the auto-update.  Unfortunately at this time it requires a one-time manual update.
