### ISSUE TITLE
Import visx won't install or work after manual installation

### ISSUE THREAD

**Issue by aDarkling** [Microsoft/azuredatastudio#3181]
- Extension Name: import
- Extension Version: 0.4.0
- OS Version: Linux x64 4.15.0-34-generic
- VSCode version: 0.29.3

Pressing the "Install" button gets me this error:
"Failed to install 'Microsoft.import'." 

with a prompt to download it & install manually.  When I do that, it installs but fails to activate after reloads, restarts, right-clicks & ctrl-i

 We have written the needed data into your clipboard. Please paste:```json 
{
	"activationTimes": {
		"startup": true,
		"codeLoadingTime": 271,
		"activateCallTime": 6,
		"activateResolvedTime": 0,
		"activationEvent": "*"
	}
}
```

**Comment by kburtram** [comment]
@aDarkling could you please retry the scenario on the Nov. stable build from https://github.com/Microsoft/azuredatastudio/releases/tag/1.2.4.

**Comment by aDarkling** [comment]
@kburtram 
SQL Operations Studio Version 0.29.3 (Linux)
Seems that that's the problem.  I was directed to install that.  Azure Data Studio has replaced it?

Ok, I installed Azure Data Studio ver. 1.2.4 and it installed fine!
However, I can only access the Import dialog by pressing ctrl-I.  The right-click menu doesn't show "Import wizard".

@yualan , "workbench.enablePreviewFeatures" is set to true

**Comment by kburtram** [comment]
@aDarkling I wasn't able to repro the "no context menu" issue.  Could you please verify that you are right-clicking on the database node in the Object Explorer tree?

![image](https://user-images.githubusercontent.com/599935/48573924-a5eef300-e8c2-11e8-80d6-08c701714100.png)

**Comment by kburtram** [comment]
Closing since the original issue is fixed by upgrading to the latest.  Please open a new issue if you still are unable to see the `Import wizard` context menu on Database nodes in Object Explorer.
