### ISSUE TITLE
Feature request: Add description to firewall rule when creating from the app

### ISSUE THREAD

**Issue by richardmunn17** [microsoft/azuredatastudio#3182]
- Azure Data Studio Version:

Steps to Reproduce:
When you use the Azure Resource Explorer to find and connect to a database/instance, you get an option to add a firewall rule automagically if your IP address is not currently whitelisted.

This creates firewall rule in Azure that doesn't have a great description :-(

It would be nice to be able to add a description to the rule, like 'PASS Summit Hotel', 'Home internet' so that it's easier to tidy up firewall rules in Azure - don't really want to leave an IP in there for a network I'm only going to use once or twice...

**Comment by longzheng** [comment]
+1 on this request to make it easier to audit who added the rules if there are multiple users.

Alternatively would also be reasonable if the auto-generated firewall rule had a name that included the signed in Azure account name.

For example the current rules are named
```
ClientIPAddress_2022-01-19_02:32:03
```
it could be the name and email of the user, with the timestamp
```
Doe, John - john.doe@email.com_2022-01-19_02:32:03
```
