### ISSUE TITLE
Can never create a non-SQL new untitled file

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3186]
Issue Type: <b>Bug</b>

- Hit Ctrl+N to create a new file
- Try changing the file from SQL to any other lanugage

Expected:
- Switches
Actual:
- Get error `Change Language Mode is not supported for unsaved queries`

![image](https://user-images.githubusercontent.com/10819925/48280808-9165b300-e409-11e8-8584-14955f0c96de.png)

There are a few things to be done in fixing this:
- Allow switching untitled files from SQL to a different language so that Ctrl+N works
- I think we should add a "New Query" action and default Ctrl+N to this, but have a backup command for "New Untitled File" to still be used. That way when I do want a quick CSV / Txt scratchpad I can use the editor. Right now I have to hop over to VSCode which is really inconvenient.

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.29GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
sql-vnext|Mic|0.8.1

</details>

**Comment by kburtram** [comment]
This suggestion is being tracked with this issue https://github.com/Microsoft/azuredatastudio/issues/2059.  Closing as dup.
