### ISSUE TITLE
Hyperlinks in markdown in notebooks dont work

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#3193]
Issue Type: <b>Bug</b>

Create a new notebook
Create a markdown cell
Create a hyperlink in the cell
Something like
[test](http://www.microsoft.com)
Go into view mode of the cell
Try to click the link.  Does nothing.

Azure Data Studio version: Azure Data Studio 1.3.1-insider (bd53e685d0091f9fe09c2662c30e0e506c402561, 2018-11-09T21:10:38.782Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.1
ssmskeymap|kev|1.0.0
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.8.1
whoisactive|Mic|0.1.1

</details>

**Comment by chlafreniere** [comment]
This is tracked by #3440.
