### ISSUE TITLE
Process leak in Azure Data Studio

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3195]
Issue Type: <b>Bug</b>

I presently have 170 Azure Data Studio processes open for 2 instances of Azure Data Studio, one with 1 connection and 1 query, the other with 2 connections, 2 queries, 1 instance of SandDance, and 6 notebooks. It's been open for about 6 hours.
![image](https://user-images.githubusercontent.com/8250560/48380408-853d5800-e68c-11e8-8d79-8996168a9681.png)
![image](https://user-images.githubusercontent.com/8250560/48380414-8a9aa280-e68c-11e8-8b51-5dbc40f66bd7.png)
![image](https://user-images.githubusercontent.com/8250560/48380428-8ec6c000-e68c-11e8-9160-d04c032af794.png)
![image](https://user-images.githubusercontent.com/8250560/48380441-9be3af00-e68c-11e8-9969-1e623daee4ff.png)
![image](https://user-images.githubusercontent.com/8250560/48380445-9f773600-e68c-11e8-9e3b-86afb8e10fa8.png)

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.79GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.1
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.8.1
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
I haven't seen this before, but if I had to guess I this may be related to the extension host restart mechanism.  For example, if an extension was to cause that process to freeze during initialization additional process may be launched.

If this happens again, or if you have a consistent repro, please capture the command-line arguments for the duplication properties by double-clicking the process row in Process Explorer.
