### ISSUE TITLE
Server Tab Search

### ISSUE THREAD

**Issue by mikhey** [Microsoft/azuredatastudio#3201]
Issue Type: <b>Feature Request</b>

It would be nice if the search could also search/filter objects within the server or there was a way to filter specific objects eg: Right click on Tables or Stored Procedures, click on filter (or search) on the context menu pop-up.  At times there can be large numbers of objects and it would be a nice productivity feature to have.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 6.1.7601

**Comment by kburtram** [comment]
We're tracking this suggestion with this issue https://github.com/Microsoft/azuredatastudio/issues/2934.  Please leave any additional related comments on that issue.

In general, we recommend using Redgate SQL Search extension for searching active database connections, though it currently doesn't have integration with the Server viewlet.
