### ISSUE TITLE
Closed itself while computer was locked and unsaved files were blank

### ISSUE THREAD

**Issue by pamanes** [Microsoft/azuredatastudio#3213]
Issue Type: <b>Bug</b>

program closed itself while computer was locked and my unsaved files were BLANK, but then after connecting back to the server (also disconnected) and clicked "New Query" the unsaved files showed up with my code one by one.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz (8 x 2395)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (28.05GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
This sounds like some weird rendering issue.  I'm not sure how to repro since I haven't seen this when locking\unlocking my computer yet.
