### ISSUE TITLE
Password is not persisted in some cases

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#3220]
Issue Type: <b>Bug</b>

Repro:
Connect to a SQL Server, provide the password, *don't* choose to save the password.  Connection is now in recent connections list.
Create a new query tab.
Click Connect
Choose the connection from recent connections list.
Provide the password.
*click* the save password checkbox
Click connect
Repeat, but this time notice that the password is not persisted.

Azure Data Studio version: Azure Data Studio 1.3.1-insider (bd53e685d0091f9fe09c2662c30e0e506c402561, 2018-11-09T21:10:38.782Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.1
ssmskeymap|kev|1.0.0
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.8.1
whoisactive|Mic|0.1.1

</details>

**Comment by lberrocal** [comment]
I've got a similar issue. Password are not being persisted on my password auth saved connection even if the checkbox is selected upon creation or edition.

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still impacted by this issue.

**Comment by river-fall** [comment]
yes, the issue still persists
