### ISSUE TITLE
Connected query tab header still shows truncated text on hover

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#3222]
- Azure Data Studio Version: master f54d8ce

Steps to Reproduce:
1. Open a query tab with a connection
2. Hover over the tab with your mouse

Actual behavior: The truncated version of the connection name is shown in the hover text
Expected behavior: The full name is shown in the hover text like in SSMS

Likewise the text is cut off on Azure Data Studio's title bar even though it doesn't need to be

![Screenshot showing an active tab with a truncated server name in the tab name. The hover text is also truncated, as is the window's title, which is also showing the tab's name](https://user-images.githubusercontent.com/3758704/48523252-7ee7e100-e830-11e8-88bd-8e8c5208601a.png)

**Comment by kburtram** [comment]
This appears fixed in the latest build.

![image](https://user-images.githubusercontent.com/599935/129629194-4bed837f-a883-4850-9190-8489cbcc16d9.png)
