### ISSUE TITLE
Duplicate entries in recent connections list

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#3224]
Issue Type: <b>Bug</b>

Repro steps:
Connect to a SQL Server instance
Start to create a new connection
See that the connection is in the recent connections list (OK!)
Create a new connection to the same server, same username, etc. (OK!)
Start a new query window, type some query, run it, you get a prompt to connect to a SQL Server.  In the recent connections list you see the same entry twice.

Desired:
Don't duplicate connections in the recent connections list if the name and username and db is the same
Show the DB name from the connection string in the connection name in parenthesis or something if it is specified
Order the recent connectionsn list by MRU if it is not already

Azure Data Studio version: Azure Data Studio 1.3.1-insider (bd53e685d0091f9fe09c2662c30e0e506c402561, 2018-11-09T21:10:38.782Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.28GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.1
ssmskeymap|kev|1.0.0
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.8.1
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
I've seen this when one of the non-visible options is different, such as one being saved into a Server Group and one having its Server Group set to `<Do not Save>`.  In this case I agree there shouldn't be a duplicate.

If the non-visible option is significant then I agree that is should be shown in the MRU to disambiguate.  I'll take a look and see if there is a simple way to clean up the behavior a bit.

**Comment by kburtram** [comment]
Closing this issue based on this PR https://github.com/Microsoft/azuredatastudio/pull/4368.  There is still some work required with the MRU, but this solves the main "duplicate entry" issue.
