### ISSUE TITLE
Extension search doesn't work for anything with a space (and other inconsistencies)

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3243]
Issue Type: <b>Bug</b>

- Search for `SQL` and you'll see most extensions
![image](https://user-images.githubusercontent.com/10819925/48580264-91ffbd00-e8d3-11e8-8737-05f05c22da21.png)

- Search for `SQL Server` and none will show, not even `SQL Server 2019`
![image](https://user-images.githubusercontent.com/10819925/48580277-988e3480-e8d3-11e8-9806-d8a0d3f947fa.png)

- Search for `search` and you'll see Redgate extension
![image](https://user-images.githubusercontent.com/10819925/48580284-9e841580-e8d3-11e8-9353-41070b0954b0.png)

- Search for `Redgate` and nothing shows up.

![image](https://user-images.githubusercontent.com/10819925/48580295-a3e16000-e8d3-11e8-8507-c9c26b9cd1a9.png)
Azure Data Studio version: azuredatastudio 1.3.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|/Users/kevcunnane/projects/azuredatastudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --debugBrkPluginHost=13047 --debugId=cdb9af29-cb9a-4a3b-b629-2dc3a69e301e --extensionDevelopmentPath=/Users/kevcunnane/projects/SqlOpsStudioExtensions/extensions/aris|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by alanrenmsft** [comment]
this has been fixed for April release.
