### ISSUE TITLE
SQL Profiler is not capturing parameterized queries from .Net SqlClient Data Provider

### ISSUE THREAD

**Issue by spursrox** [Microsoft/azuredatastudio#3245]
- Azure Data Studio Version: 1.2.4
- SQL Query Profiler : 0.3.0

Steps to Reproduce:

1. Connect to Azure SQL Instance 
2. Execute via Web App, code that further executes parameterized SQL queries using the ADO.Net /  .Net SqlClient Data Provider.  Further details - In my case, very often, this is done in the application code via PetaPoco. 

Result: I can see the rpc_completed calls, and the reads / writes information, but not the actual parameterized SQL call itself in the TextData column.  

This may be related to issue #2125. 

I would test version 0.4.0 of SQL Query Profiler if someone could point me to a installable OSX build. 

![image](https://user-images.githubusercontent.com/25552386/48581959-dc3f6900-e8e8-11e8-9f1a-05057cb89af2.png)

**Comment by alanrenmsft** [comment]
@spursrox please try this Azure Data Studio insider build: https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.1 and install v 0.4.0 profiler extension.

**Comment by spursrox** [comment]
@alanrenmsft Tried latest builds, no luck. "rpc_completed" rows, for the TextData column, are still empty. Where is the definition of the trace file associated to the Session Template? Since I'm trying to profile Azure SQL Server, I assume I'm supposed to be using session template "Standard_Azure". 

Maybe its just the configuration of the hard-coded Session Templates?
[https://dba.stackexchange.com/questions/10269/sql-profiler-not-showing-rpc-calls]

In the "Events Selection" tab of the trace definition, make sure that the TextData column is checked for RPC:Completed events.

(This is unchecked in the default trace definition)

**Comment by alanrenmsft** [comment]
@spursrox Please try this build: https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.4 and make sure the profiler extension version is 0.5.1.

**Comment by spursrox** [comment]
@alanrenmsft Works great now, thank you.
