### ISSUE TITLE
Last row in a TableComponent is hidden below the bottom of the table's container

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#3246]
When using a TableComponent with a lot of rows, the last row gets hidden below the container. I can scroll slightly past the bottom of the container, and inspecting the html shows a row hidden below that. Seems like this may be an issue where the column header height isn't being subtracted from the height of the table grid.

Here's a sample image where the 30th row is hidden.
![image](https://user-images.githubusercontent.com/12820011/48583160-451fe480-e8db-11e8-9975-e91bfb9a8c7a.png)

**Comment by corivera** [comment]
CC @MattIrv @anthonydresser

**Comment by alanrenmsft** [comment]
@corivera It seems you can workaround the issue by calling loading=false before table.updateProperties(...). meanwhile I will investigate the root cause and work on the fix.

**Comment by kburtram** [comment]
Closing older engineering-focused issues.  Please activate a bug for the specific user-facing feature that is impacted by this behavior.  Thanks!
