### ISSUE TITLE
Multi Line Edit

### ISSUE THREAD

**Issue by Havondor** [microsoft/azuredatastudio#3247]
Issue Type: <b>Feature Request</b>

Azure Data Studio should have multi line edit (Alt + Shift + arrow up/arrow down) in a manner similar to what SSMS has today. 

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.15063

**Comment by dzsquared** [comment]
In VSCode (and Azure Data Studio), this is covered by ctrl+alt+up/down.
https://stackoverflow.com/questions/30037808/multiline-editing-in-visual-studio-code

Keybindings can be customized to swap "Add Cursor Above"/"Add Cursor Below" with "Copy Line Up"/"Copy Line Down"

**Comment by Breudje92** [comment]
in ssms, when a cursor moves to a place after the end of a line, it is automatically filled with spaces. Can this behavior also be implemented in azure data studio?
