### ISSUE TITLE
Peek Definition does not seem to work for UDFs

### ISSUE THREAD

**Issue by Havondor** [Microsoft/azuredatastudio#3248]
Issue Type: <b>Bug</b>

Peek and Go To Definition does not seem to work for User Defined Functions both scalar and Table valued. When this is used it provides the definition of the schema it belongs to not the defintion of the selected object.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz (4 x 3292)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.91GB (11.86GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
This looks like a variation of https://github.com/Microsoft/azuredatastudio/issues/2181.  I'll close as dup and make a note there to also check UDFs when fixing.  Thanks!
