### ISSUE TITLE
Enhancement - Executing Query Label

### ISSUE THREAD

**Issue by rkdiekhoffwk** [Microsoft/azuredatastudio#3252]
Issue Type: <b>Feature Request</b>

Can a setting be added that would allow a user to show a short notifiaction in a query editor tab if there is an executing query still in progress?

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/Microsoft/azuredatastudio/issues/227.  Thanks for the suggestion!
