### ISSUE TITLE
Samsung Linux Dex Support?

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#3265]
Hi,

I have installed Samsung Linux Dex(ubuntu 16.04).

- Azure Data Studio Version:
azuredatastudio-linux-1.2.4.deb

Steps to Reproduce:
1. Download Azure Data Studio Ubuntu linux  setup.

2. Run the following Command.
sudo dpkg -i ./azuredatastudio-linux-1.2.4.deb

3. I am getting the following error:
dextop@localhost:~/Downloads$ sudo dpkg -i ./azuredatastudio-linux-1.2.4.deb
[sudo] password for dextop:
dpkg: error processing archive ./azuredatastudio-linux-1.2.4.deb (--install):
package architecture (amd64) does not match system (arm64)
Errors were encountered while processing:
./azuredatastudio-linux-1.2.4.deb

Thanks.
Regards Dat

**Comment by jdeisenh** [comment]
Seems that this package contains binary code compiled for intel/amd, and is packaged as such. As long as the vendor does not supply an arm64 version (which shouldn't be too hard, but is currently quite unusual) you are out of luck.

**Comment by Fizard** [comment]
I'm also in the same problem. It's not that difficult to make an ARM64 version, please do that so we can use it on Samsung Linux On Dex and also on others.

**Comment by kburtram** [comment]
We're current tracking creating an ARM build with this issue https://github.com/microsoft/azuredatastudio/issues/1774.  Thanks for reporting this suggestion!
