### ISSUE TITLE
Database List Fails to Load

### ISSUE THREAD

**Issue by iamwyza** [microsoft/azuredatastudio#3270]
Issue Type: <b>Bug</b>

1. Connect to Server with 5000 databases (Maximum allowed in Azure).
2. Attempt to use Servers->Databases.
3. Error will show "Object Exporer task didn't complete within 45 seconds"

I had already lengthened the timeout in the advance properties of the connection to 120 seconds, but to no avail.  It doesn't seem like listing the DBs should take any appreciable amount of time unless it's trying to run some metadata queries on each one too. 

Azure Data Studio version: azuredatastudio 1.3.1-insider (bd53e685d0091f9fe09c2662c30e0e506c402561, 2018-11-09T19:34:35.108Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (12.49GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by iamwyza** [comment]
Any chance this is likely to make it into a near-term release?  This is the only thing that really holds me back from using this great tool.

**Comment by tbolon** [comment]
Same here.

We "only" have 300 databases but I am also facing this issue with the default timeout of 45 seconds.

I have the same remark: could you perhaps quickly display all databases, then, eventually when required, fetch each database properties in background (on demand).

**Comment by g-rad** [comment]
Getting the same issue after updating to 1.8.0
We have only 10 databases

**Comment by kburtram** [comment]
@g-rad are you getting the error `"Object Exporer task didn't complete within 45 seconds"` or is the list just failing to expand?

**Comment by g-rad** [comment]
@kburtram I updated my comment. The issue was resolved by using a different db user, I guess it's something to do with permissions.

**Comment by iamwyza** [comment]
This persists for me on 1.10.   Even on servers with only 300 databases it will time out.  Oddly, the list of of databases in the Search Widget on the Server Dashboard loads them just fine.  Even when there are 5k DBs.  So it seems like the code that fetches the list of DBs in the Search widget is different than the code that fetches the list of databases in the Servers Pane.

**Comment by dhiraj3301** [comment]
I am also facing same issue with only 100 databases.. Please let me know if any solution for it

**Comment by tbolon** [comment]
Moreover the "Search" area in the server details is able to list all databases quickly, but the Connections explorer does not.

I think you should at least try to use a lightweight query (using master db) to populate the nodes, then perform the long request on background, or only on demand for each node.

**Comment by eghazal** [comment]
Same issue with less than 20 databases ! 
I'm using user token as authentication method and connecting to Azure SQL database server.

**Comment by leewilson86** [comment]
Any chance this issue can be raised further. It has been an issue for coming up to two years and has spanned many versions. It is not like this is an intermittent or isolated issue to a specific version. This is a chronic issue which happens constantly. 

I have multiple Azure SQL Servers with varying numbers of databases from as few as 2 up to as much as 60. And this error appears for all.

Error and version details attached:

![Screenshot 2020-08-06 at 10 12 40](https://user-images.githubusercontent.com/264361/89514369-ac777980-d7cd-11ea-8ac2-ac61318c11e7.png)

![Screenshot 2020-08-06 at 10 12 52](https://user-images.githubusercontent.com/264361/89514383-b00b0080-d7cd-11ea-8519-29a79265ca08.png)

**Comment by slimmingworlduk** [comment]
Same issue on latest version with <100 databases.

**Comment by Oxoproline** [comment]
Still an issue Please fix this it's really annoying. It makes every task and navigation much more complicated.

**Comment by leewilson86** [comment]
Yes, still an issue for me too.

Unfortunately turning it off and turning it back on doesn't fix this one 🙄

Please fix as it's a really annoying issue and it has been open for over two years.

**Comment by dobbinjp** [comment]
Still an issue for a co-worker who has version 1.29.0 installed. His account can see all databases and objects in SSMS (everything works as you would expect there), but he cannot see them in his Connections window (under the databases folder).

**Comment by OskarNet** [comment]
This works for me when there are few databases on the server.  But if there are more than 100 databases this times out for me and I can't browse the databases.
If I create a query I can jump between the databases in the database dropdown fine.  It's just that navigation in the Object Explorer that is not working.

**Comment by FallDownTheSystem** [comment]
Same issue, 3 years running now, times out even though there are only about 50 databases on the server.

Running a query and connecting immediately shows all the databases in the dropdown. Wish this would get some attention for once.

**Comment by mdsharpe** [comment]
Happens to me, version 1.34.0.

Heading back to SSMS for now I guess.

**Comment by ddejohn** [comment]
Still having this issue in 2022.

**Comment by tudorels** [comment]
Same for me. Please fix this

**Comment by conradsuuna** [comment]
Kindly update your Azure data studio. Fixed the issue on my end.

**Comment by tbolon** [comment]
Nop, not here.

<img width="357" alt="image" src="https://user-images.githubusercontent.com/127185/168794401-35e33716-41ea-4e16-a069-55c87ab840a0.png">

**Comment by conradsuuna** [comment]
Well, I thought I'd just share the solution that has just worked for me 30 minutes ago when I faced the same exact issue.

**Comment by tbolon** [comment]
No pb, it reminded me to also check, thanks :)

**Comment by shudson302** [comment]
Please fix this!  I have to keep SSMS running just to use the object explorer!

**Comment by gabrielmaldi** [comment]
Same issue for me.

<img width="248" alt="Screen Shot 2022-09-21 at 11 11 20" src="https://user-images.githubusercontent.com/3728897/191527479-490c1544-2477-4855-98f2-a0b444d27965.png">

**Comment by PacoRivera13** [comment]
Same error: "Object Exporer task didn't complete within 45 seconds"

Version: 1.39.1 (system setup)
Commit: https://github.com/microsoft/azuredatastudio/commit/7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19043

**Comment by Timothyoverton** [comment]
Same issue for me,

Version: 1.39.1 (user setup)
Commit: 7553f799e175f471b7590302dd65c997b838b29b
Date: 2022-08-30T01:11:13.047Z
VS Code: 1.62.0
Electron: 13.6.6
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.22000

**Comment by cheenamalhotra** [comment]
Issue is now fixed with https://github.com/microsoft/azuredatastudio/issues/21475 addressed.
The [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch) contains fix, it will be available in the next stable release.
