### ISSUE TITLE
Default cell size for code and markdown should be the same.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3278]
Issue Type: <b>Bug</b>

The default cell size for code and markdown cells should be the same.

Also the "Double click to edit" font size should be different and preferably in Italics.

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/22312581/48737051-df489b00-ec01-11e8-84ba-6096ba2b9c13.png">

Azure Data Studio version: Azure Data Studio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:09:53.834Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/3FBEB819-7AC1-483F-8A42-53385002BE33/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1151257|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
This was fixed for March.
