### ISSUE TITLE
The Toolbar visuals need to be updated to make it more readable.

### ISSUE THREAD

**Issue by smithaBharadwaj** [microsoft/azuredatastudio#3280]
Issue Type: <b>Bug</b>

The current ADS toolbar control has the icons very small. The height of the toolbar can be increased.
Current - 

![image](https://user-images.githubusercontent.com/27451624/48737153-28005400-ec02-11e8-8017-4a33ef06bbcb.png)

Expected:
![image](https://user-images.githubusercontent.com/27451624/48737616-55013680-ec03-11e8-9622-d63b1ea53132.png)

CSS that I changed was 

![image](https://user-images.githubusercontent.com/27451624/48737708-998cd200-ec03-11e8-8477-9ee7c6aa395d.png)
![image](https://user-images.githubusercontent.com/27451624/48737654-79f5a980-ec03-11e8-81a3-4b09c67055b9.png)

![image](https://user-images.githubusercontent.com/27451624/48738169-fb9a0700-ec04-11e8-94d0-fdcbb005199a.png)
![image](https://user-images.githubusercontent.com/27451624/48738186-048ad880-ec05-11e8-82b3-e4273a8b07d5.png)

![image](https://user-images.githubusercontent.com/27451624/48738204-11a7c780-ec05-11e8-9069-893ac6847d69.png)
![image](https://user-images.githubusercontent.com/27451624/48738247-3308b380-ec05-11e8-8915-fa1a4ab9b3fd.png)

Azure Data Studio version: Azure Data Studio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:09:53.834Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.04GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_622744|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.4.0
sql-vnext|Mic|0.8.1
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
Closing older issues.
