### ISSUE TITLE
The cell borders are not visible in all themes

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3282]
Issue Type: <b>Bug</b>

We need to make sure the cell borders are visible in all themes -

![image](https://user-images.githubusercontent.com/22312581/48742101-56862b00-ec12-11e8-9a01-a08605f971d5.png)

Azure Data Studio version: azuredatastudio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:28:03.193Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (17.33GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
Notebook cells are theme aware now.
