### ISSUE TITLE
Error when saving a job step with no command

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3283]
Issue Type: <b>Bug</b>

Steps:

1) Create a new job, save it
2) Add a step to the job but only input the step name (not a command)
3) Receive error

![image](https://user-images.githubusercontent.com/8250560/48743256-2ee59180-ec17-11e8-832b-4f3f2543d803.png)

Azure Data Studio version: azuredatastudio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:28:03.193Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (5.76GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by yualan** [comment]
Hi @abist , can we investigate this bug and scope if this can land in December release? This came up during a SQLSaturday presentation and would help out a lot of users.
