### ISSUE TITLE
Notebook: No markdown cell are rendered when a Notebook is opened

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3287]
Issue Type: <b>Bug</b>

When a notebook is opened I only see code cells and no markdown cells are displayed.

![image](https://user-images.githubusercontent.com/27451624/48802313-c4d6f600-ecc3-11e8-973b-b38f63ea5408.png)

Azure Data Studio version: Azure Data Studio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:09:53.834Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_622744|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by vickyharp** [comment]
I did some detailed testing on Azure Data Studio 1.3.7-insider with extension 0.9.0. This is first open of Azure Data Studio after a system restart on Windows.

These are running timestamps:

Azure Data Studio Open - 0 seconds
Azure Data Studio Interactive  - 10 seconds
Open existing notebook - 18 seconds
Notebook code appears - 19 seconds
Markdown appears - 46 seconds
(The kernel never appeared on this notebook so I reopened)
Notebook reopen - 57 seconds (instant code and markdown)
Kernel appears - 69 seconds








Version 1.3.7-insider
Commit 487531cc52c9c7a54147dc179f97b0c4252f7458
Date 2018-12-04T21:37:09.298Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by smithaBharadwaj** [comment]
Wow, I did not realized there was a lag in rendering the Text cells.

**Comment by kevcunnane** [comment]
We need to fix for December - it's a startup issue that makes it so slow (waiting for extension host so we can access the markdown extension) but short-term we can solve by putting in placeholder loading component / text. Future, we need to port code internally so render isn't dependent on the extension host (as much as it was)
