### ISSUE TITLE
Get Error: Failed to show text document when right click and do preview on a notebook in HDFS

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3288]
Issue Type: <b>Bug</b>

Right click on a Notebook in HDFS and select Preview

Expected: 
The Notebook should render with Kernel as PySpark and Attached to that cluster.

Actual:
The Notebook opens but Kernel is Python 3 and Attached to is n/a and nothing is rendered as it failed to show text document.

![image](https://user-images.githubusercontent.com/27451624/48806661-e2aa5800-eccf-11e8-98e6-7f03d3906b64.png)

Azure Data Studio version: Azure Data Studio 1.3.2-insider (2c867a4b2c0c57d69cf80ff9b153fea8542ca12f, 2018-11-19T03:09:53.834Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.16GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_622744|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Duplicate
