### ISSUE TITLE
Modal text for 'copy details' displays incorrectly for default light theme

### ISSUE THREAD

**Issue by angdesign** [Microsoft/azuredatastudio#3292]
Issue Type: <b>Bug</b>

The modal dialog that appears after an error has an affordance in the lower left that allows you to copy details. The 'copy details' text appears as all-white when in a light theme, and is unreadable:

![image](https://user-images.githubusercontent.com/29785331/48808960-89debd80-ecd7-11e8-98d6-6a187c5756d9.png)

In dark theme, it appears as all-white but is against a dark background so is accessible.

![image](https://user-images.githubusercontent.com/29785331/48808931-6d428580-ecd7-11e8-890a-a09e7e35eee0.png)

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.8.0

</details>

**Comment by MattIrv** [comment]
This should be fixed in master by https://github.com/Microsoft/azuredatastudio/pull/3126. If you're still seeing this in master or in insiders builds please reopen this issue
