### ISSUE TITLE
Error: Entry not found in cache - December Build 1.3.1 Insider

### ISSUE THREAD

**Issue by Vapok** [Microsoft/azuredatastudio#3295]
I realize that there are other bugs similar to this, but they have all been closed or marked as duplicate in earlier versions. Where as I am using 1.2.4 and 1.3.1 (listed below) and getting the same error.

- Azure Data Studio Version: 1.3.1 Insider
![image](https://user-images.githubusercontent.com/1264136/48849545-906f4280-ed74-11e8-9539-21da8ee29f10.png)

Steps to Reproduce:
1. Open Azure Data Studio
2. Click on Azure in the left menu bar.
3. Click "Sign into Azure..." in the Azure: Resource Explorer
4. Click "Add Account"
5. Click "Copy & Open"
6. This opens a browser tab for device login. I copy code in Azure prompt.
7. I sign into Azure through web page.
8. Sign in is successful and the page said that I can now close the browser.
9. Go back to Azure Data Studio and get an error "Error adding account" "Error: Entry not found in cache.
![image](https://user-images.githubusercontent.com/1264136/48849733-f52a9d00-ed74-11e8-8455-643ca1ec18a7.png)

**Comment by kburtram** [comment]
@Vapok thanks for reporting this bug.  Here is the currently active issue we're tracking for this https://github.com/Microsoft/azuredatastudio/issues/545.  We'll investigate for the December release.  Please leave any additional related comments on that issue.
