### ISSUE TITLE
Sync servers across devices

### ISSUE THREAD

**Issue by joshuaquiz** [microsoft/azuredatastudio#3296]
Issue Type: <b>Feature Request</b>

For those who do things on different devices or share server connections within a group, it would be really great to have a way to do that rather than having to enter a new server on every computer that needs to have the new server connection added.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
Closing as out of scope since we don't have a service for this.  The recommendation would be to try to use workspace connections and sync the workspace to different machines with source control.  As mentioned above we'll look through out of scope issues again when doing longer-term planning.
