### ISSUE TITLE
Сant add an azure account.

### ISSUE THREAD

**Issue by vsingur** [Microsoft/azuredatastudio#3298]
Issue Type: <b>Bug</b>

When i try to add an Azure account and was going to the https://microsoft.com/devicelogin  i get error HTTP 400. When i adding in to address bar  'www.' before 'microsoft' , device auth page opens but  after entering authorization code from Azure Data Studio  not appear my Azure account that i trying to add

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17763

![azure data studio](https://user-images.githubusercontent.com/1479219/48892488-44dd9700-ee4f-11e8-99b5-dac67332b654.gif)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Pentium(R) CPU G2020 @ 2.90GHz (2 x 2893)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.69GB (1.65GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
whoisactive|Mic|0.1.1

</details>

**Comment by pazdedav** [comment]
I have exactly the same issue (without that first sign-in URL problem). I've just updated Data Studio to Version 1.2.4 _(Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c, Date 2018-11-02T21:50:52.634Z, VS Code 1.26.1, Shell 2.0.9, Renderer 61.0.3163.100, Node 8.9.3, V8: 6.1.534.41, Architecture x64)_

**Comment by kburtram** [comment]
This looks related to https://github.com/Microsoft/azuredatastudio/issues/545 which is getting numerous duplicate bug reports.

**Comment by vsingur** [comment]
@kburtram result of accessing this file (i have monitored it in procmon):   

![image](https://user-images.githubusercontent.com/1479219/49279604-fc4e5b00-f498-11e8-982e-436fc50c3474.png)

Console output:
![image](https://user-images.githubusercontent.com/1479219/49279395-6a465280-f498-11e8-863b-12d1e47053c9.png)

**Comment by kburtram** [comment]
@vsingur thanks for the additional info.  I think the issue may be related to the encoding we use while encrypting the token cache.  Currently the cache encodes with `latin1` which incorrectly decodes text in some cases.

Could you please delete `%APPDATA%\azuredatastudio\Azure Accounts\azureTokenCache-azurePublicCloud` and then retry the repro with this test build https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-windows-1.3.5-utf8-patch.zip?

**Comment by vsingur** [comment]
Thanks a lot @kburtram !  In this test build i successfully added   my personal Azure account.   I think that the errors  was because of the Cyrillic letters in the fields "Name" and "Last Name"  
![image](https://user-images.githubusercontent.com/1479219/49374867-b5b86500-f713-11e8-8e97-9b4b55829643.png)

**Comment by kburtram** [comment]
@vsingur thanks for confirming.  I've sent a PR with the update to use UTF8 for the token cache https://github.com/Microsoft/azuredatastudio/pull/3391.  This fix should be available in the next insiders build later this week.

**Comment by kburtram** [comment]
@vsingur the UTF8 cache encoding fix is in this build https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.6 and will be in the Dec build later this month.  Please let me know if you still have problems with a build containing this update.

**Comment by danatcofo** [comment]
Version 1.4.5 and I'm receiving this same error. Using a personal account login, not an aad account.
