### ISSUE TITLE
The recent files list is unusable if the file path is sufficiently long.

### ISSUE THREAD

**Issue by kentonvk** [microsoft/azuredatastudio#330]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: Browse to any file with a path longer than 140 characters. Close it.
Use the File>Open Recent, and find that file.

The filename itself (most important part) is lost in ellipses.

**Comment by kburtram** [comment]
Closing older issues.  The "Open Recent" list is part of the upstream code we've pull from vscode.  Ideally the fix will be applied there and we'll pickup in a future merge.  Thanks for reporting this problem!
