### ISSUE TITLE
Title Bar Style custom is not showing menubar

### ISSUE THREAD

**Issue by sujith-sreedhar-mariapps** [microsoft/azuredatastudio#3300]
Issue Type: <b>Bug</b>

I tried changing the settings window.titleBarStyle to "custom" . The menu became completely hidden, but it did not become part of the title bar (similar to how it is happening in Visual Studio Code).

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.82GB (5.99GB free)|
|Process Argv|E:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by anthonydresser** [comment]
This was purposly disabled as it was causing issues with our editor. We have plans to reenable when we fix those editor issues.

**Comment by winzig** [comment]
Latest insiders build looking good:

<img width="831" alt="screen shot 2019-02-25 at 11 16 04 am" src="https://user-images.githubusercontent.com/127062/53362329-bf0a3580-38ee-11e9-87b2-2418ec715a55.png">

😍

**Comment by winzig** [comment]
Well, other than the repeating area of the title. Was mostly talking about the new dark mode support getting activated. 😎

**Comment by winzig** [comment]
Setting the title bar from `custom` to `native` resolved that glitch also:

<img width="662" alt="screen shot 2019-02-25 at 11 19 14 am" src="https://user-images.githubusercontent.com/127062/53362498-3049e880-38ef-11e9-9a89-f927b7d22328.png">

**Comment by kburtram** [comment]
Both native and custom titlebar styles appear to be working fine on current builds.  Please let us know if you're still impacted by this issue.  Thanks!
