### ISSUE TITLE
Cannot connect AzureDataStudio from macOS 10.14.1 with SQLServer 2017 Windows 10

### ISSUE THREAD

**Issue by donhuvy** [Microsoft/azuredatastudio#3301]
- Azure Data Studio Version: Version 1.2.4 (1.2.4)

Steps to Reproduce:

1. Use Windows 10 Pro x64, IP 192.168.1.42 (via wifi)

2. Install Microsoft SQL Server 2017 (RTM) - 14.0.1000.169 (X64)   Aug 22 2017 17:04:49   Copyright (C) 2017 Microsoft Corporation  Enterprise Evaluation Edition (64-bit) on Windows 10 Pro 10.0 <X64> (Build 16299: ) 

3. From macOS 10.14.1 Mojave, connect to instance via WIFI.

Error
```
A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 40 - Could not open a connection to SQL Server)
```

<img width="1440" alt="screen shot 2018-11-24 at 15 51 05" src="https://user-images.githubusercontent.com/1328316/48966268-cc1e3c80-f000-11e8-8e53-e05059b530f6.png">

<img width="1440" alt="screen shot 2018-11-24 at 15 48 51" src="https://user-images.githubusercontent.com/1328316/48966264-a3964280-f000-11e8-9903-2bfd68b8bafb.png">

**Comment by kburtram** [comment]
@donhuvy the error message typically indicates that there is a network connectivity issue between the client and server machines (the error comes from the SQL Client driver component in .Net Core framework).  

Have you verified that the server is accessible from other tools running on the macOS client (such as sqlcmd, etc.)?  You may verify that the server's firewall rules are configured to allow 1443 incoming requests and that the TCP endpoint is enabled, for example.

**Comment by donhuvy** [comment]
I use two computers. 1 computer (slow, old computer run Windows 10 pro) and 1 computer (macOS 10.14).
Because the old computer is quite slow, I cannot program on it, I must program on macOS computer. I try to connect from macOS to Windows PC.

I think it is not a bug, I am confusing, because I don't allow remote connection to SQL Server on Windows PC.
