### ISSUE TITLE
Linked accounts doesn't work

### ISSUE THREAD

**Issue by nielsvdc** [Microsoft/azuredatastudio#3303]
Issue Type: <b>Bug</b>

I'm trying to see what Linked accounts does. After I fill in de code on the website, I get the message "Error: Entry not found in cache." in Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7200U CPU @ 2.50GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (1.52GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
We're tracking this problem with issue https://github.com/Microsoft/azuredatastudio/issues/545.  Thanks for reporting.  We'll take a look and try to figure out what's happening here.
