### ISSUE TITLE
Can't Import text file with 1 column

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#3305]
Issue Type: <b>Bug</b>

I have a text file with 1 column, I want to import, but the process is stopped at step 2 (nothing happen).

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.10240

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7- 2870  @ 2.40GHz (2 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|16.00GB (12.33GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|100%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0

(1 theme extensions excluded)

</details>

**Comment by kenvanhyning** [comment]
Hi, this is a known issue. You can track the issue here: https://github.com/Microsoft/azuredatastudio/issues/3000.  I'll close this one as a duplicate.
