### ISSUE TITLE
Duplicated results grids when doing SELECT queries

### ISSUE THREAD

**Issue by corivera** [Microsoft/azuredatastudio#3307]
After updating to the latest master build, I started hitting issues with SELECT queries. Multiple result grids will show up with the same results. Executing the query multiple times shows a different number of result grids, ranging from 1 to 3 in my case. Note that this happens with any select, not just with SELECT TOP as in this screenshot.

Edit: Issue repros consistently for me on Linux, and against several versions of SQL Server.

![image](https://user-images.githubusercontent.com/12820011/49049641-bb063480-f194-11e8-880f-3afa8ee39331.png)

**Comment by corivera** [comment]
CC @kburtram @anthonydresser

**Comment by kburtram** [comment]
@anthonydresser this appears related to this PR that went in yesterday https://github.com/Microsoft/azuredatastudio/pull/3124 (reverting the commit resolved the issue).  Please either (1) revert in master and work on a fix prior to recommitting or (2) fix in `master` as soon as possible.  Thanks!

**Comment by kburtram** [comment]
This was fixed by rolling back the streaming commit.
