### ISSUE TITLE
New Query Sets to Active Connection Inconsistently

### ISSUE THREAD

**Issue by rkdiekhoffwk** [microsoft/azuredatastudio#3309]
Issue Type: <b>Bug</b>

1. From the Servers side bar, click on the local SQL Server DB to set an active connection.

2. Open a New Query tab.  The new query tab shows as connected to the local DB.

3. Close the tab.

4. Open a New Query tab again.  The new query tab is not connected to any server.  

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.35GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
profiler|Mic|0.3.0

</details>

**Comment by kburtram** [comment]
I couldn't repro this on the current build.  Could you please let us know if you're still impacted by this issue?
