### ISSUE TITLE
Add new account error

### ISSUE THREAD

**Issue by wfsharon** [Microsoft/azuredatastudio#3326]
- Azure Data Studio Version: 1.2.4
The following error message appears when signing in to Azure account :

Error adding linked account
Error: self signed certificate in certificate chain

Steps to Reproduce:
I get this error when adding a new account. It immediately displays. It may have a lot to do with the corporate firewall. Do we need to import a "safe" certificate to ADS in order to get outside?

**Comment by kburtram** [comment]
@wfsharon  Thanks for reporting the problem.  We're currently investigating this bug with issues https://github.com/Microsoft/azuredatastudio/issues/545 and https://github.com/Microsoft/azuredatastudio/issues/3298.  I'll close this as a duplicate.

**Comment by 2axDeveloper** [comment]
I'm still getting this error in ADS

**Comment by wfsharon** [comment]
Same here .. even on V1.3.9. Other threads are pointing to a very-well known node.js issue of reading its own fixed list of certificates rather then the cert store (I'm amazed they can still get away with it). Face it, most developers (and potential ADS users) sit behind corporate firewalls.

**Comment by 2axDeveloper** [comment]
so I'm confused why they have this issue as marked as closed, when it's simply not fixed.  I'm just trying to play around with ADS and come up to speed with it, and it's not even working.  very frustrating
