### ISSUE TITLE
Failed to create csv file

### ISSUE THREAD

**Issue by SebastianPfliegel** [Microsoft/azuredatastudio#3329]
- Azure Data Studio Version: 1.3.4-insider (the previous version didn't have this bug)

Steps to Reproduce:

1. Execute SELECT-Query
2. Press `Save As Csv`
3. Select Filename
4. Receive error message

```
Failed to save results. Error: Failed to save list.txt: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

I assume the bug is located in Microsoft/sqltoolsservice. Should I open an issue there as well?

**Comment by yualan** [comment]
Hi Sebastian, which version didn't have this bug for you? Was it the November release or 1.3.3-insider?

**Comment by SebastianPfliegel** [comment]
Hi Alan,

it was definetely the insider channel as I received the update prompt. I assume I was on 1.3.3 before, but maybe it could have been 1.3.1 as well.

**Comment by kburtram** [comment]
@SebastianPfliegel did this work with the November release?  What OS are you using?

**Comment by kburtram** [comment]
@MattIrv this looks like it was introduced with the AAD and related project reference updates.  This is the first SQL Tools build that contains the bug https://github.com/Microsoft/sqltoolsservice/releases/tag/v1.5.0-alpha.55.

Can you take a look and see which references are misaligned?  *I repro'ed on Windows to confirm that it isn't related to the macOS SqlClient patch.*

**Comment by SebastianPfliegel** [comment]
Probably the update to `4.6.0-preview3-26501-04`: https://github.com/Microsoft/sqltoolsservice/blob/2f1097028fca69753931c3f6b7f6191afaabb71a/src/Microsoft.SqlTools.CoreServices/Microsoft.SqlTools.CoreServices.csproj#L20

**Comment by kburtram** [comment]
@SebastianPfliegel thanks, that reference update looks like the one that introduced this bug.  This build picks up a fix for this issue https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.5.
