### ISSUE TITLE
Horizontal scrollbar hidden in results by messages

### ISSUE THREAD

**Issue by Bikonja** [microsoft/azuredatastudio#3330]
Issue Type: <b>Bug</b>

When the results window needs a horizontal scrollbar and the messages panel is displayed, the horizontal scrollbar is hidden by the messages. If the messages panel is collapsed, the scrollbar is there. The horizontal scroll on the mouse works either way.

Messages shown, scrollbar hidden:
![image](https://user-images.githubusercontent.com/7753243/49146056-32ed6f80-f2f9-11e8-96a8-4fb58cabbb6b.png)

Messages collapsed, scrollbar visible:
![image](https://user-images.githubusercontent.com/7753243/49146187-8790ea80-f2f9-11e8-9fb6-90fefd279cb4.png)

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.90GB (0.50GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Bikonja** [comment]
I'm not sure what caused this, but I currently have the same situation and the scrollbar appears correctly. If I figure out if this is something that happens in a certain situation I will post with what that situation is.

**Comment by anthonydresser** [comment]
We have moved to messages as a tab, so this should be fixed.
