### ISSUE TITLE
[Feature][Agent] Ability to view steps when edit permissions is denied

### ISSUE THREAD

**Issue by Tarig0** [Microsoft/azuredatastudio#3332]
- Azure Data Studio Version:1.3.4-insider
- Sql Server Agent Version:0.35.1

Steps to Reproduce:

1. Open agent pane on sql server 2012
2. Right click job
3. Edit job
4. Edit pane will not show and no error is displayed

**Comment by Tarig0** [comment]
This may already exist but the server I want to view the steps on is causing #3333

**Comment by abist** [comment]
Closing this as they both are being tracked by https://github.com/Microsoft/azuredatastudio/issues/3333
