### ISSUE TITLE
AAD Authentication with Guest Accounts

### ISSUE THREAD

**Issue by jdanton** [microsoft/azuredatastudio#3334]
- Azure Data Studio Version: Version 1.3.4-insider (1.3.4-insider)

Steps to Reproduce:

1. Use an account from a different AAD that is a guest member of the directory for the database.
2. Attempt to login to the database.
3. Returns NT AUTHORITY\ANONYMOUS LOGIN error.

This is resolved in SSMS by the option to specify the AD Domain Name or TenantID in the connection properties tab.

**Comment by kburtram** [comment]
@aaomidi  do you have any context on this request and whether your recent auth updates will help here?

**Comment by aaomidi** [comment]
I think so - will validate once the work is complete.

**Comment by aaomidi** [comment]
So I think this issue has been covered by the auth updates, and the changes Matt made here.
