### ISSUE TITLE
BACPAC export fails if database contains Windows Authentication users

### ISSUE THREAD

**Issue by DaveDustin** [Microsoft/azuredatastudio#3337]
Issue Type: <b>Bug</b>

Create a new database
Add a new user based on a Windows Auth login
`CREATE USER [Domain Users] FOR LOGIN  [DOMAIN\Domain Users] `

Attempt to create a bacpac file from the database using the Data-Tier Application Wizard

Proceed through the dialogs, and begin the export
Fails with 
```
Error SQL71627: The element SqlUser: [domain\group] has property AuthenticationType set to a value that is not supported in Microsoft Azure SQL Database v12.
```

Azure Data Studio version: azuredatastudio 1.3.4-insider (8bf835c53163bb8024afbbe6224d809ab41a0994, 2018-11-28T01:02:12.569Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (12.25GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.0.0
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1

</details>

**Comment by kisantia** [comment]
This is by design - export bacpac only supports Azure v12 surface area, which doesn't support Windows Authentication.
