### ISSUE TITLE
Add Shortcut for Copying Results with Headers

### ISSUE THREAD

**Issue by nilamo** [microsoft/azuredatastudio#3341]
- Azure Data Studio Version: 0.32.9

Copying with Headers is available via the context menu, but it'd be beneficial to also have access to it through a keyboard shortcut.  In SQL Server Management Studio, the shortcut is ctrl+shift+c.

**Comment by excelosaurus** [comment]
The contextual menu should also appear when right-clicking the top left square and the column headers; it already works on the row headers.

**Comment by JASM2007** [comment]
I can't tell you how many times I right clicked the top left square thinking I could copy and paste with headers and nothing happens...

**Comment by emead-spentech** [comment]
This is probably the only thing keeping me from moving fully from SSMS :(

**Comment by jagdishrajan** [comment]
Along with a shortcut Copy with Headers should also be a command available in the Command Palette (via Ctrl+Shift+P).

**Comment by frank-yifei-wang** [comment]
I'm trying to set a custom shortcut key binding Ctrl+Shift+C but found no `grid.copySelectionWithHeaders`. 

Please add this feature as it would help me and other folks tens/hundreds of times a day! 

<details>
<p>

- Version: 1.34.0 (system setup)
- Commit: 83a4316cf89cbf961a0f09a72c861379cfd01fa9
- Date: 2021-12-15T20:47:33.863Z
- VS Code: 1.58.0
- Electron: 12.0.9
- Chrome: 89.0.4389.128
- Node.js: 14.16.0
- V8: 8.9.255.25-electron.0
- OS: Windows_NT x64 10.0.18363

</p>
</details>

![image](https://user-images.githubusercontent.com/42301547/152893556-c5fbfae9-f1c4-43cc-9c2b-18dadb2e5360.png)

**Comment by Diredumalde** [comment]
New to Github... Since this is still listed as "Open" even 5 years later, is it still unresolved? Husband pointed out how terrible SQL Server Management Studio is and had me download VS Code but not being able to use a keyboard shortcut to copy results with headers is huge for me, I use this constantly. Is there an extension that does this?

**Comment by erinstellato-ms** [comment]
@alanrenmsft There is a feedback comment requesting this same functionality - let me know if you want to discuss further.

**Comment by setzor** [comment]
> I can't tell you how many times I right clicked the top left square thinking I could copy and paste with headers and nothing happens...

3 years later I came here because honestly, same. Can't believe this still isn't implemented

**Comment by alanrenmsft** [comment]
These are the shortcut keys that are currently supported on the query result grid. they should be available in tomorrow's [insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch).

![image](https://github.com/microsoft/azuredatastudio/assets/13777222/9a01b1c0-ee39-499b-b23d-484e91e4fa0b)

@erinstellato-ms FYI.

**Comment by erinstellato-ms** [comment]
Hi @nilamo @excelosaurus @JASM2007 @emead-spentech @jagdishrajan @frank-yifei-wang @Diredumalde @setzor!  Wanted to follow up to request that you each download the latest Insider build and give this a try - it may take another day for the right build, but as this is a feature that you all requested/commented on/said it was a "must have", we would appreciate your feedback.  Thanks!
