### ISSUE TITLE
Can't Connect to Azure Government

### ISSUE THREAD

**Issue by KevinDMack** [Microsoft/azuredatastudio#3342]
Currently when I go to the Azure Tab within, I am only given the option to connect to Azure Commercial through the microsoft.com/devicelogin and does not allow using the deviceloginus version for the government sovereign cloud.

**Comment by kevcunnane** [comment]
This is a duplicate of #3013 and I'll use that for tracking so we just have 1. That's being put in the June bucket and @kenvanhyning should be kicking off the approval process.
