### ISSUE TITLE
Tasks from the Dashboard

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3347]
Issue Type: <b>Bug</b>

We need to have the tasks for the following when the extension is added -

New Spark Job
View Spark History  ( takes the same icon as the New Spark job )

Link: https://23.96.20.197:30443/gateway/default/sparkhistory/

View Yarn Applications

Link:

https://23.96.20.197:30443/gateway/default/yarn/cluster/apps

New Notebook
Open Notebook

Azure Data Studio version: Azure Data Studio 1.2.3-insider (8439cde6106ec3bf443fff5e8a8b54c5e98ac170, 2018-11-01T03:48:03.475Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.53GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/6985A09C-C476-468A-B1A9-411DF0FAECF3/d/Azure Data Studio-2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
This was fixed last year.
