### ISSUE TITLE
Per-user installer fails writing to HKCR regkey

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3352]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Build per-user installer
2. Try to install ADS with it

Expected: Works

Actual: Error writing to HKCR\azuredatasstudiSourceFile and a couple other values

> Note: ADS works after install if the error messages are ignored

![image](https://user-images.githubusercontent.com/599935/49256894-5a216b00-f3e5-11e8-8722-a035e8510089.png)

**Comment by kburtram** [comment]
@abist do you know if these registry keys are related to the desktop shortcut updates we made to the installer?  One of the keys mentioned desktopshortcut I think.

**Comment by abist** [comment]
@kburtram These registry keys aren't related to the desktop icon update we made. However, they are related to the "associated files" update where we try to associate all `.sql` files to ADS.

**Comment by kburtram** [comment]
@abist I also see the below one which I guess has something to do with icons.  Do have an idea what we need to do to makes these keys we added to setup work in per-user installs?

![image](https://user-images.githubusercontent.com/599935/49258108-2ba58f00-f3e9-11e8-94ee-7921f98a6da0.png)

**Comment by abist** [comment]
@kburtram It seems that we force `HKCR` which is the root class for some registry tasks. In `code.iss`, in lines 94-104, for `Root` we should be using `{#SoftwareClassesRootKey}` instead of using HKCR and HKCU, since we have a conditional for it.

**Comment by kburtram** [comment]
This is fixed by https://github.com/Microsoft/azuredatastudio/pull/3376
