### ISSUE TITLE
Preview Files is not working

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3356]
Issue Type: <b>Bug</b>

This is a regression.

We cannot preview files in HDFS.

This is also affecting the Create External Table from HDFS scenarios to preview files.

Azure Data Studio version: Azure Data Studio 1.3.4-insider (59b2e706cac78dabff9ca888ab5dbe335b195272, 2018-11-28T03:10:34.447Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.82GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/7D7525A3-6C5C-4AB3-8DCA-A7E8BDDB5B4F/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_704684|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Closed -was a cluster reliability issue
