### ISSUE TITLE
Query results crlf,lf not honored on copy

### ISSUE THREAD

**Issue by troglobytor** [Microsoft/azuredatastudio#336]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:46:54.710Z)
- OS Version: Darwin x64 16.7.0
---

Steps to Reproduce:

1. When querying a table with a sqlText column, crlf on windows sql db deleted on copy from select result
2.Note:SSMS results to grid has configuration option to preserve, optimal option to convert to query results computer's newline whether crlf or lf.

**Comment by antuneswilliam** [comment]
+1

**Comment by camargovitor** [comment]
+1

**Comment by kburtram** [comment]
Please verify https://github.com/Microsoft/sqlopsstudio/issues/2128 when resolving this issue.

**Comment by thesushil** [comment]
This should be marked resolved as it is no longer and issue after changing the settings as:
`"sql.copyRemoveNewLine": false`
