### ISSUE TITLE
"Something Went Wrong..."

### ISSUE THREAD

**Issue by Blindeddie** [Microsoft/azuredatastudio#3369]
This error is similar to closed issue #319 from Dec 2017
Error:
"Something went wrong getting more rows: Error: Start row cannot be less than 0 or greater than the number of rows in the result set
Parameter name: startRow"

Version 1.3.5-insider
Commit 6912e3893ede7d13afb54acc4571764b8ad78469
Date 2018-11-30T03:22:16.978Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
Steps to Reproduce:

1. have multiple Tabs open.

2. run a query that returns no results (select 1 where 1=0 or any query that returns no results)

3. switch to another Tab, switch back to tab with the empty results set.

4. Error above displayed! and scrollable empty results grid displayed.

**Comment by kburtram** [comment]
@anthonydresser  @ranasaria I'm seeing this error pretty frequently testing with the release candidate build.  I'm guess it has to do with the results streaming work.  Could you please take a look?

**Comment by kburtram** [comment]
This should be fixed in the latest builds.
