### ISSUE TITLE
File Management

### ISSUE THREAD

**Issue by mantadolphin** [microsoft/azuredatastudio#3371]
This is a basic functionality request. I would use Azure Data Studio if it had an efficient developer file management explorer, similar to visual studio.  eg copy paste files from open editor to workspace. These simple fast mouse grab and move functional operations are very basic GUI requirements even in web based client front ends today. (even though SQL SERVER MANAGEMENT STUDIO still fails at these simple tasks, can't drag files wherever I want to).

That's it, as a developer I quickly get frustrated at having to use multiple operations to accomplish simple tasks and this would be the most basic of file operations. With all the possibilities for Azure Data Studio I will continue to wait until it adds this basic functionality.

Regards Peter

**Comment by kburtram** [comment]
Ideally functionality like this would be added upstream in vscode and we would pickup in a source code refresh.  I'll resolve as out of scope/upstream.  Thanks for this suggestion!
