### ISSUE TITLE
Query editor should not send whitespace characters to engine for execution

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#3377]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Type a query such as `SELECT * FROM sys.tables;`
2. Run the query multiple times

Expected: The results are returned every time

Actual: Sometime the query results aren't returned an the the messages say "0 results returned"

Note: This doesn't repro consistently but I've seen it occur a few times in ~10 minutes of testing.  This appears to be a regression from the query streaming changes since it only recently started happening.

**Comment by kburtram** [comment]
This may have been related to running a query with blank lines selected, which now has the behavior outlined above.  I think this is still a regression, but less serious than losing resultsets.

**Comment by anthonydresser** [comment]
I can't seem to repro this.

**Comment by kburtram** [comment]
Actually this doesn't look like a regression from Nov, though I thought we did have this behavior at some point.

The repro is something like the following.

1. Type a query with some SQL and some whitespace, such as below (note the space characaters.

```SQL

SELECT * FROM sys.tables;


   

    

```

2. Select the SQL content and F5

3. Select the space characters and F5

Expected: In step 3 there is no action since only whitespace is highlighted

Actual: Results from step 2 go away and the space characters are passed to engine for execution.

Note: This is same behavior as SSMS, so I'll update the title and move to backlog as suggestion for consideration.

**Comment by kburtram** [comment]
Closing older issues.
