### ISSUE TITLE
Using Find text in Profiler moves keyboard focus on each key-press

### ISSUE THREAD

**Issue by ChrisLounsbury** [Microsoft/azuredatastudio#3379]
OS Version: Mac OS 10.14.1
Azure Data Studio Version: 1.3.5-insider

Steps to Reproduce:

1.  Open Profiler extension
2.  Connect to SQL engine and set trace type to TSQL - OnPrem
3.  Select view: TSQL View
4.  Run profiler trace to capture TSQL lines
5.  CMD-F to bring up Find window
6.  Begin typing. 

On each keystroke, the focus moves to the Profiler grid lines and searches for the character just entered.  You have to manually click back into the Find window to hit the next keystroke, rinse and repeat for entire string you wish to search for.

**Comment by alanrenmsft** [comment]
@ChrisLounsbury Thanks for reporting the issue, this will be fixed in next release later this week.
