### ISSUE TITLE
AX Performance testing support

### ISSUE THREAD

**Issue by kripashankarupadhyay** [Microsoft/azuredatastudio#3385]
We’re trying to utilize JMeter for AX Performance testing. When we tried to record actions on AX application using JMeter Recorder, it is throwing UnknownHostException in response code, and hitting “sqm.microsoft.com”. In Result, displaying “/sqm/MBS/sqmserver.dll” error having bad character in whatever script it recorded. In short, we are not able to record actions performed in AX using JMeter Recorder.

Below are the steps we followed to connect JMeter with AX –
1.	Installed the JMeter 4.0
2.	Generated the security certificate file to validate certificates (ApacheJMeterTemporaryRootCA)  -- Required for recording script
3.	Set the local Proxy settings, Sever name – Localhost , Port - 8888
4.	Go to JMeter -> File -> Templates  -> Click on Create recording
5.	Click on HTTP(S) Test Script Recorder and set Port -8888
6.	Click on start recording.
Getting Error – Response code: Non HTTP response code: java.net.UnknownHostException
             Response message: Non HTTP response message: sqm.microsoft.com
7.	We are getting error “/sqm/MBS/sqmserver.dll” and throwing the bad character while recording script.
Pl. note - We have tried same JMeter configuration with few other client server applications (e.g. Eclipse) installed on “uan-d-ax-rds-1” machine, its working fine. Just to make sure – we are facing issue with AX only.
![image](https://user-images.githubusercontent.com/8831927/49378427-94b33c80-f732-11e8-8d37-0e0874e968d4.png)
![image](https://user-images.githubusercontent.com/8831927/49378431-97ae2d00-f732-11e8-885a-97e7a484ef32.png)

**Comment by alanrenmsft** [comment]
@kripashankarupadhyay I guess you have opened the issue in the wrong repo, I don't see anything related to Azure Data Studio in the issue description.
