### ISSUE TITLE
Profiler does not capture all sql statements

### ISSUE THREAD

**Issue by guzo-kevin** [Microsoft/azuredatastudio#3386]
Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Customer would like to capture all sql statements from a .net web application.   Data studio capture some but not all sql statements.  Here @dbrowne had done analysis of possible root cause:

=======================================================
It looks like the Profiler add-in for Azure Data Studio (which is in preview) has some issues.  

The “Statements” capture configures an Extended Events session that captures 

CREATE EVENT SESSION [statements] ON SERVER 
ADD EVENT sqlserver.sp_statement_completed,
ADD EVENT sqlserver.sql_statement_completed

Which is a really odd set of events to capture.  It captures Ad-Hoc batches sent to SQL Server, but not queries sent over RPC.  And then it captures every statement inside a stored procedure.  

The “QuickSessionStandard” capture is more reasonable, but I couldn’t get that to actually return anything in Data Studio, although I could view the traffic in SSMS for that Extended Event Session.

**Comment by alanrenmsft** [comment]
@guzo-kevin Looks like you are using the latest stable release, we have fixed the issue in the insiders build: https://github.com/Microsoft/azuredatastudio/releases/tag/1.3.5

also, make sure you have version 0.5.1 of the profiler extension after installing the insiders build.

We will release the next stable build in around 2 weeks.
