### ISSUE TITLE
SELECT ALL on large resultset freezes & crashes ADS

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3392]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a large query, such as below.

```SQL
SELECT * FROM sys.tables
CROSS JOIN sys.all_columns a
CROSS JOIN sys.all_columns aa;
```

2. Let query run a couple minutes then cancel execution
3. Try to SELECT ALL on the resultset with Ctrl-A

Expected: Resultset is selected

Actual: ADS freezes and becomes nonresponvive, then crashes.

![image](https://user-images.githubusercontent.com/599935/49402184-0a50e580-f6fe-11e8-91c0-349d37955701.png)

![image](https://user-images.githubusercontent.com/599935/49402227-294f7780-f6fe-11e8-9bf2-2c81ac77179e.png)

**Comment by anthonydresser** [comment]
Are we still seeing this? I just executed and it seemed to run fine.
