### ISSUE TITLE
Feature request: change connection port

### ISSUE THREAD

**Issue by bpourkazemi** [Microsoft/azuredatastudio#3394]
- Azure Data Studio Version: 1.2.4

Doesn't seem we can change the default connection port (1433). Can we get an option to do so when setting up the connection?

Thanks!

**Comment by kburtram** [comment]
@bpourkazemi you can specify a non-default port using the syntax "servername,portnumber" in the Server field of the Connection Dialog  (for example, **localhost,1533**).  There is also an option "Port" in the Advanced Options "General" section which should accomplish the same.  

Are neither of these working?

**Comment by kburtram** [comment]
Closing based on previous response.  Please let me know if there is anything else needed for this request.

**Comment by bpourkazemi** [comment]
thanks @kburtram
