### ISSUE TITLE
Notebooks regression: invalid kernels aren't handled 

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3404]
Steps to Reproduce:

1. Connect to a big data connection
2. Open the attached notebook.

Expected:
-  This has an invalid kernel name so we "should" fall back to Python3
Actual:
- We throw an error with code 501 and the kernel / attach to dropdowns never finish loading

This is because we throw the error from extension to core and the response status is lost. The following code in clientSession.ts therefore doesn't pass:
```
if (err && err.response && err.response.status === 501) {
```

Note that a) we should fix this and b) we should find a way to be more resilient to this failure case.

**Comment by kevcunnane** [comment]
[Churn+Analysis+Demo.ipynb.zip](https://github.com/Microsoft/azuredatastudio/files/2645919/Churn%2BAnalysis%2BDemo.ipynb.zip)

**Comment by YurongHe** [comment]
The problem is not reproed in latest build.

**Comment by YurongHe** [comment]
It is reproed only when there is big data cluster connected.
