### ISSUE TITLE
Line number on markdown cells are lookign weird.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3408]
Issue Type: <b>Bug</b>

I think we should avoid having line numbers on the markdown cell types. This is looking odd.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/22312581/49427530-65afc180-f758-11e8-835d-eab39e601543.png">

Azure Data Studio version: Azure Data Studio 1.3.4-insider (59b2e706cac78dabff9ca888ab5dbe335b195272, 2018-11-28T03:10:34.447Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.12GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/7D7525A3-6C5C-4AB3-8DCA-A7E8BDDB5B4F/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_704684|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Let's think about this more. It needs consideration as to whether we override default behavior in this case.

**Comment by chlafreniere** [comment]
Line numbers have been removed for markdown cells.
