### ISSUE TITLE
Notebook - when an existing notebook is open with no Notebook dependencies installed, Attach to should say localhost

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3419]
Issue Type: <b>Bug</b>

Actual:
Open a notebook without Notebook dependencies installed or connected to any cluster.

The Attach to shows Select connection.
![image](https://user-images.githubusercontent.com/27451624/49465595-d8e62180-f7b2-11e8-9964-b3172277d0f6.png)

Click on Select connection and click Add connection. Not sure what the filtered Recent Connection list will show.
![image](https://user-images.githubusercontent.com/27451624/49465720-18147280-f7b3-11e8-96a8-0772d6cc3e76.png)

On connecting successfully, The Attach to now says undefined.
![image](https://user-images.githubusercontent.com/27451624/49465802-42fec680-f7b3-11e8-91cd-e8f7f77fd649.png)

Expected:
Just show localhost and don't have Select connection option till the dependencies are installed. 

In future when we have TSQL support then we can show Kernel - TSQL and Attach to - Select connection. 

Azure Data Studio version: Azure Data Studio 1.3.7-insider (cac8cc99e1bf916e13ae0b77b1e7a1af22a2cc8a, 2018-12-04T03:14:08.970Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.15GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_2294320|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
Fixed
