### ISSUE TITLE
Use of Arrow Keys in Notebooks is Confusing

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3428]
When I am in a notebook with multiple cells and am currently focused on a text cell, if I use the arrow keys to navigate around in the cell, I see other cells are selected. Even though we claim that other cells are "selected", the cursor is still on the first cell.

Can we just use tab/shift+tab to navigate between cells? I'm confused by this experience.

**Comment by kevcunnane** [comment]
Fixed
