### ISSUE TITLE
Increase the default code cell size for markdowns

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3429]
Issue Type: <b>Bug</b>

Could we please have the cell size to be the same for markdowns as it is for code cells?

Also single click should make it edit as well.

We need the look and feel to be consistent.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/49478993-625b1b00-f7d6-11e8-9796-550dbff0841c.png">

Azure Data Studio version: Azure Data Studio 1.3.7-insider (cac8cc99e1bf916e13ae0b77b1e7a1af22a2cc8a, 2018-12-04T03:14:08.970Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 3, 3|
|Memory (System)|16.00GB (0.11GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/F6C6A196-AA0B-454F-8238-BD3813830431/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1737128|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Chris - work with Smitha on correct solution to pretty up the empty markdown scenario

**Comment by chlafreniere** [comment]
This has been fixed with a previous PR.
