### ISSUE TITLE
Running empty code cell doesn't give any message

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3430]
![image](https://user-images.githubusercontent.com/44002319/49479830-4c028e80-f7d9-11e8-980a-7a4b9addbc8c.png)

Steps to Reproduce:

1.Create/open a notebook
2. Add a code cell and hit run. You don't see any message where as if you add some contnet and execute you see an error message
3. Need a message to the user.

**Comment by chlafreniere** [comment]
This has since been fixed.
