### ISSUE TITLE
Notebook saves are broken

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3432]
Issue Type: <b>Bug</b>

Clicking on the Save in Notebooks is broken.

Please verify that I can save blank notebook as well.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/49479951-be736e80-f7d9-11e8-83b4-76a77903cd35.png">

Azure Data Studio version: Azure Data Studio 1.3.7-insider (cac8cc99e1bf916e13ae0b77b1e7a1af22a2cc8a, 2018-12-04T03:14:08.970Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.22GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/F6C6A196-AA0B-454F-8238-BD3813830431/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1737128|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Looks like this is due to us not handling untitled notebook save. We should prompt for filename then save them.

**Comment by kevcunnane** [comment]
This has been mostly fixed. Issue #3522 has been opened to track most of the remaining work, so can close this. We'll look at whether we can fix in that issue as an ASK mode fix next week, but closing this one for now
