### ISSUE TITLE
When you open a Notebook the new Notebook is showing the counts of the notebook opened.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3433]
Issue Type: <b>Bug</b>

When we open a new notebook we should have the notebook title "Untitled", right now I see the counts.

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/22312581/49480072-2cb83100-f7da-11e8-9d83-8ee90aa76785.png">

Azure Data Studio version: Azure Data Studio 1.3.7-insider (cac8cc99e1bf916e13ae0b77b1e7a1af22a2cc8a, 2018-12-04T03:14:08.970Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.44GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/F6C6A196-AA0B-454F-8238-BD3813830431/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1737128|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Rony- can you clarify? You need a unique ID to avoid conflicts. See behavior of SQL files below. What's the issue exactly?

![image](https://user-images.githubusercontent.com/10819925/49480586-21660500-f7dc-11e8-8427-63fc6bfc37d2.png)

**Comment by kevcunnane** [comment]
Rony just needed to upgrade 😄
