### ISSUE TITLE
Alignment issue b/w ... and line highlighter for text and code cells

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3434]
![image](https://user-images.githubusercontent.com/44002319/49480089-422d5b00-f7da-11e8-90ad-5c9e3d32ef21.png)

Steps to Reproduce:

1.Space b/w the text editor and more icon is inconsistent for text and code cells

**Comment by chlafreniere** [comment]
We no longer highlight lines.
