### ISSUE TITLE
Failed to preview notebook after upload to HDFS

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3435]
- Azure Data Studio Version:

Steps to Reproduce:

1. Update load the attached 1.ipynb file to HDFS
[1.zip](https://github.com/Microsoft/azuredatastudio/files/2646594/1.zip)
2. Right click the file and select "Preview
![image](https://user-images.githubusercontent.com/43652751/49480786-eca67d80-f7dc-11e8-8064-3152a6adee17.png)

The same file can be opened in ADS.
![image](https://user-images.githubusercontent.com/43652751/49480841-18296800-f7dd-11e8-904d-412e25330705.png)

**Comment by chlafreniere** [comment]
Fixed by #4870.
