### ISSUE TITLE
Disabled input textbox is not responsive to themes

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3437]
Issue Type: <b>Bug</b>

This is a general UX issue, but will explain using SQL 2019 features:
- Open the New Spark Job wizard
- Pick a python file for upload. This disables the Main Class input box
- Change themes and note that other than default themes none respond "right" to the change. Seems like we need to have this be updated in built-in themes

Screenshot from Monokai (Dimmed): the 2 text boxes look the same even though the 1st if disabled, the 2nd isn't
![image](https://user-images.githubusercontent.com/10819925/49480944-853cfd80-f7dd-11e8-8cbf-7300d403003a.png)
Screenshot from default dark theme: It's clearer that one is disabled
![image](https://user-images.githubusercontent.com/10819925/49480993-b74e5f80-f7dd-11e8-94b4-772c345d7639.png)

Azure Data Studio version: Azure Data Studio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:21:11.749Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|/Users/kevcunnane/Downloads/Dec4_BugBash/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_8620088|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
sql-vnext|Mic|0.9.0

</details>

**Comment by kburtram** [comment]
Here is what I'm seeing with the Monokai (Dimmed) theme for disabled controls.  The colors are similar but I verified with a color picker tool they are different.

![image](https://user-images.githubusercontent.com/599935/129629673-5403538a-3aea-4643-87f9-1ff303d5dab3.png)
