### ISSUE TITLE
Separate Messages and Results windows

### ISSUE THREAD

**Issue by olcayseker** [microsoft/azuredatastudio#344]
- SQL Operations Studio Version: 0.24.1

It would be better to separate Messages and Results windows or make tabbed as SQL Management Studio.
Add option to change result view window grid columns size.
Add ability to toggle pin status for all windows

**Comment by kburtram** [comment]
We now have separate Results and Messages tabs.  Please create additional bugs for other suggestions if still applicable.  Thanks!
