### ISSUE TITLE
Notebook regression: link in Markdown requires cmd+click

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3440]
Update: This is an issue with requiring cmd+click instead of simple click. This is different from how things work in the markdown viewer.

- Enter the following text in a markdown cell

```
[bing](http://www.bing.com) should look like a link
```
- try to click on 'bing'
Expected:
- Link opens
Actual:
- Link requires you to use cmd+click which is non-obvious.

**Comment by YurongHe** [comment]
Investigate this a bit and didn't find a good way to override cmd+click. We can rewrite the link by adding onclick="window.open(this.href)" to make it response mouse click.

**Comment by kevcunnane** [comment]
@chlafreniere mind if I take this one? I fixed it as it was blocking my demo
