### ISSUE TITLE
Notebook: Link in markdown has no styling making it impossible to see

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3441]
It's impossible to see that a link is clickable in markdown.

In notebook ("bing" is the link):
![image](https://user-images.githubusercontent.com/10819925/49481379-87a05700-f7df-11e8-91b1-02faea975676.png)

In markdown viewer (correct implementation):
![image](https://user-images.githubusercontent.com/10819925/49481371-76efe100-f7df-11e8-8868-b27948126d8a.png)

**Comment by YurongHe** [comment]
After enable/disable "markdown.preview.linkify": true, in User Setting. it is always links no matter the settings.
