### ISSUE TITLE
Notebook: code cells show line select when not selected

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3443]
Issue Type: <b>Bug</b>

- Open a notebook with 2 code cells
- Edit 1 cell
- Note how the other has the text box around it, which looks "wrong"
![image](https://user-images.githubusercontent.com/10819925/49481750-21b4cf00-f7e1-11e8-8944-f26e710992ab.png)

Azure Data Studio version: Azure Data Studio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:21:11.749Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.32GB free)|
|Process Argv|/Users/kevcunnane/Downloads/Dec4_BugBash/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_8620088|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
sql-vnext|Mic|0.9.0

</details>

**Comment by chlafreniere** [comment]
We no longer select lines in code cells.
