### ISSUE TITLE
No warning when select db checkbox, but some tables are not selected

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3446]
Steps to Reproduce:

1. Select create external table 
2. go to step 4
3. Check xe,  some tables are not check because of unsupported data type. But no warning. 
So we have to select each individual not checked table to see the warning. 
Can we show global warning to tell why those tables are not selected by clicking db checkbox.

**Comment by kevcunnane** [comment]
@geleems this is fixed, correct? Triaging into June, please review and confirm it's fixed.

**Comment by kburtram** [comment]
@geleems where you able to verify this issue is fixed per @kevcunnane comment above?

**Comment by geleems** [comment]
This had been fixed long time ago. Closing.
