### ISSUE TITLE
Extensibility: need a way to list all connections, not just active ones

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3449]
Issue Type: <b>Bug</b>

- Connect to big data cluster and select a csv file. Choose "Create External Table"
- It asks you to select a SQL connection, but none are listed even if you have them saved. This is because the APIs only support listing active connections, not all connections in Object Explorer

Expected:
- We really need to be able to get the following
 - All connections
 - Active connections
 - Recent connections (to fill a dropdown), e.g. an MRU
![image](https://user-images.githubusercontent.com/10819925/49484445-eff53580-f7eb-11e8-90e4-7b8d317e0fd5.png)

Azure Data Studio version: Azure Data Studio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:21:11.749Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/private/var/folders/kd/f1542xn11qdbp218t_b316d80000gn/T/AppTranslocation/13DD4A3C-67C1-4A70-B3A4-090863D6FBE2/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_8808550|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
sql-vnext|Mic|0.9.0

</details>

**Comment by alanrenmsft** [comment]
this has been implemented
