### ISSUE TITLE
[Feature Request] Command Palette operations

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#346]
Provide the ability to perform common operations via commands in the command palette.

This could/may be more suited to an extension but thought I would start here just in case...A few examples of what I mean:

# Dropping objects

- Type "Drop" into the command palette
- A list of options is presented such as, `Drop: Database`.
- Selecting this option will then prompt to `enter the name of the database`
- In the background, it simply executes the `DROP DATABASES` command for us.
- Potentially also prompt to do it in a forcible manner like "do you want to kill active connections", with response options of yes or no.

# Creating new object

- Type "Create" into the command palette
- A list of options are presented such as, `Create: Database`
- Selecting this option will then prompt to `etner the name of the database`
- Next prompt could be some of the basic properties but this could get opinionated as to what should be there. So in the interim maybe it opens a new query with a template query statement for creating a database. Similar to snippets in SSMS.

Just thinking out loud but another option for the above would be to have the commands driven by snippets/templates via JSON file. This would allow us to control what a statement might do, or just have them all open a new query window with the provided answers included. 

I would say that folks asking for right-click menu's and such are taking away from what VS Code (base structure of what SQL Ops Studio is from my understanding). In Code, your main task to perform actions is via the command palette, not via mouse clicks or menu items. So integrating more of those common tasks we perform against SQL Server in the Command Palette I think will provide more value to SQL Ops Studio.

**Comment by cheenamalhotra** [comment]
Various Basic Admin features are available in preview, including Create/Drop databases, closing this as resolved.
