### ISSUE TITLE
Remove Auto-Connection

### ISSUE THREAD

**Issue by BuckWoody** [Microsoft/azuredatastudio#3468]
Issue Type: <b>Bug</b>

Remove the auto-start of the panel from the right that asks for a connection. Make it a selection in settings. 

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz (8 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.73GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (22)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sqlite|ale|0.3.2
docs-markdown|doc|0.2.0
firstresponderkit|dre|0.3.0
gitlens|eam|9.0.2
vscode-reveal|evi|2.0.3
docker-explorer|for|0.1.6
gc-excelviewer|Gra|2.1.26
live-html-previewer|hdg|0.3.0
r|Iku|1.0.0
kubernetes-snippets|ipe|0.1.9
copy-markdown-as-html|jer|1.1.0
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.8.0
whoisactive|Mic|0.1.1
python|ms-|2018.11.0
sql-search|Red|0.2.1
markdown-preview-enhanced|shd|0.3.11
open-in-browser|tec|2.0.0
vscode-todo-highlight|way|1.0.4

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
The Connection Dialog will only appear on startup until a user has at least 1 saved connection in the Server viewlet.  The idea is to help the user get started using the tool, since most functionality doesn't work without a connection.  

@BuckWoody are you using the Azure Data Studio in a way where you don't use saved connections?
