### ISSUE TITLE
Notebook: Slow switching from localhost to remote server dropdown on kernel change

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3471]
There is about a 5 second lag between switching kernels from local to remote and the update of the drop-down.

Steps to reproduce:

1) Open a notebook which was saved with Python3 kernel
2) Switch to a Spark kernel
3) Attempt to select a connection

Running timestamps:

Change from Python3 to Spark | R - 3.31 seconds
Dropdown updates to "Select connection" - 8.45 seconds
Dropdown adds "Add new connection" - 9.83 seconds

![slow update attach to](https://user-images.githubusercontent.com/8250560/49546658-a4976180-f895-11e8-909b-780319f22e6d.gif)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (5.02GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Doesn't meet December bar but will pick up in future.

**Comment by chlafreniere** [comment]
The experience is different now and we are tracking the perf issues in another issue.
