### ISSUE TITLE
Cell Selection icon in Wizard is not intuitive for users.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3474]
Issue Type: <b>Bug</b>

We need to provide a check mark to make sure what we selected in the cards on the wizard.

![image](https://user-images.githubusercontent.com/22312581/49547520-bb3eb800-f897-11e8-9afc-ce0b3242c254.png)

Azure Data Studio version: azuredatastudio 1.3.7-insider (6acea51f12837ddd88d0b5e81f8388876b576be0, 2018-12-05T03:25:26.185Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (20.28GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.4
import|Mic|0.4.2
sql-vnext|Mic|0.9.0

</details>

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/49664701-7d60a180-fa07-11e8-8d4b-b004458f2d86.png)
