### ISSUE TITLE
Notebook: Ctrl-A in a result cell appears to select ALL cells

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3479]
Steps to reproduce:

1) Create a notebook with multiple code and result cells
2) Click into one of the result cells and hit Ctrl-A
3) Note that ALL cells are selected, not just the active one or just the results

This basically breaks the PROSE demo notebook

Unselected:
![image](https://user-images.githubusercontent.com/8250560/49550285-f2b16280-f89f-11e8-992b-0a44dd82cdb3.png)

Ctrl-A:

![image](https://user-images.githubusercontent.com/8250560/49550305-fe9d2480-f89f-11e8-88a5-9253fd49b601.png)

Copied resultset from Ctrl-A, Ctrl-V:

Result Set 1
1
print ('Result Set 2')

 Result Set 2
1
print ('Result Set 3')

 Result Set 3

This differs from the behavior when copying in a code cell, which limits Ctrl-A to the expected boundary (just the code and just the current cell)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (3.87GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by chlafreniere** [comment]
Closed with #4981.
