### ISSUE TITLE
Notebook: Can only have 1 notebook open at a time 

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3480]
Steps to Reproduce:

1) Open a notebook from the Explorer view
2) Open any other notebook and note that your first one was closed

![single notebook at a time](https://user-images.githubusercontent.com/8250560/49551008-65234200-f8a2-11e8-8f67-3b16373da41f.gif)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (3.29GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by vickyharp** [comment]
Update: I have reproduced this with Open Notebook from the Command Palette as well

![single notebook at a time 2](https://user-images.githubusercontent.com/8250560/49552080-da911180-f8a6-11e8-8f53-ad038b6d9c78.gif)

**Comment by kevcunnane** [comment]
This is by design - you need to make the notebook "permanent" by using `Ctrl+K D` or double click on editor. 
We have 1 separate issue:
- Clicking on same file twice opens 2 editors (this is wrong)
