### ISSUE TITLE
Notebook: Markdown coloring appears incorrect

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3481]
The coloring in notebook markdown appears incorrect. In this screenshot the top is Azure Data Studio and the bottom is VS Code. Note the highlighting of reserved words in the first sentence - is, help, from, complex, or, and file.

![image](https://user-images.githubusercontent.com/8250560/49551244-643ee000-f8a3-11e8-8273-642e749d1ad9.png)

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (3.00GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
The bug here is we're always setting Python for the cells. We should be setting `md` for markdown to resolve this. We should also verify for code cells we use the language if defined (e.g. scala for scala notebooks).
