### ISSUE TITLE
results stream has boundaries between rows missing

### ISSUE THREAD

**Issue by ranasaria** [Microsoft/azuredatastudio#3484]
- Azure Data Studio Version:
Version 1.3.7
Commit 9ca6200018fc206d67a47229f991901a8a453781
Date 2017-12-15T12:00:00.000Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. Run the following query:
**select * from sys.objects o1 cross join sys.objects o2 cross join sys.objects o3
go**

2. After a few seconds when some results have shown up, move the scrollbar on the right of result set all the way to the bottom. 

**Actual:**
As new rows get displayed the row boundary between a few consecutive rows is missing:
![image](https://user-images.githubusercontent.com/41588310/49553064-ccdd8b00-f8aa-11e8-8382-e6e61d03c7be.png)

**Expected:**
The row boundary between all rows to be present.

**Comment by anthonydresser** [comment]
dupe  #3360
