### ISSUE TITLE
DacFx import wizard doesn't default to selected connection

### ISSUE THREAD

**Issue by kisantia** [Microsoft/azuredatastudio#3485]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to two servers
2. Select the second server
3. Launch Data-tier Application wizard from command palette
4. Select an operation
5. Default server is the first one connected to, not the currently selected connection

Works correctly if wizard is launched from the context menu of the database

**Comment by kburtram** [comment]
@kisantia could we also please fix for the Flat file Import wizard?
