### ISSUE TITLE
Show Missing Indexes when rendering query plan

### ISSUE THREAD

**Issue by stebet** [Microsoft/azuredatastudio#3491]
Issue Type: <b>Feature Request</b>

When rendering a SQL Server query plan the Plan visualizer does not show information about missing indexes, even if it is included in the ShowPlanXML response.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17763

Steps to reproduce:
1. Create a "bad" query that should suggest an obvious index.
2. Click "Explain" to render the query plan
3. Missing indexes are not rendered like in SQL Server Management Studio

See screenshots:

![image](https://user-images.githubusercontent.com/661658/49582459-0666d280-f94d-11e8-8cbb-702d8d0997b4.png)

![image](https://user-images.githubusercontent.com/661658/49582487-21394700-f94d-11e8-826c-7e47f09b7652.png)

**Comment by kburtram** [comment]
@anthonydresser I know we used to show missing indexes when this feature was added.  Any ideas where that modification to the XLST may have been lost?  Or is it no longer working as before?

**Comment by anthonydresser** [comment]
the modifications to the xlst are still there. https://github.com/anthonydresser/html-query-plan/blob/master/src/qp.xslt I'm not sure why it wouldn't be showing up

**Comment by kburtram** [comment]
@anthonydresser thanks, I'll take a look and see why this is no longer working.

**Comment by Tarig0** [comment]
This does not match a template.

https://github.com/anthonydresser/html-query-plan/blob/master/src/qp.xslt#L37

Looks like it needs to be MissingIndex not MissingIndexRow

**Comment by stebet** [comment]
Great to see this fixed. Will this land in the next release?

**Comment by kburtram** [comment]
@stebet yes, this should be included in the Feb release planned for 2/13.
