### ISSUE TITLE
Create External Table from CSV returns no data on large .csv files

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3493]
Issue Type: <b>Bug</b>

I have airlinedata_sample.csv file uploaded to HDFS.

Please try to create an external table over that file.

![image](https://user-images.githubusercontent.com/22312581/49605591-c2bc9a80-f945-11e8-90e7-bfe568a62ecb.png)

Azure Data Studio version: azuredatastudio 1.3.7-insider (6acea51f12837ddd88d0b5e81f8388876b576be0, 2018-12-05T03:25:26.185Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.85GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
@corivera can you prioritize investigating this for the current release?
