### ISSUE TITLE
Notebook: Get error when I try to save new notebook

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3510]
Issue Type: <b>Bug</b>

Steps to reproduce:
1.Open a new Notebook
2.Execute the notebook
3.Click on Save

Actual:
Get 2 error notification 

Failed to save Notebook error 
Failed to save notebook: EACCES: permission denied, open 'Untitled-0'

Expected:
Should open the save dialog similar to New query

 

  
 Azure Data Studio version: Azure Data Studio 1.3.7-insider (5a3087859918b1564d2622b95defa662facdbef6, 2018-12-07T03:09:14.777Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/private/var/folders/d3/kw4dh3311gncx1kstyqss_hr0000gn/T/AppTranslocation/D64B6402-C693-45E6-8623-ED16F61E1EC3/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
sql-vnext|Mic|0.9.0
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
Duplicate
