### ISSUE TITLE
The task pane on cluster manage says 'Actions' instead of Tasks like the one on SQL Server.

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3511]
Issue Type: <b>Bug</b>

This is just a text fix.
The Task pane on Cluster manage dashboard says Action instead of Tasks. 

Azure Data Studio version: Azure Data Studio 1.3.7-insider (5a3087859918b1564d2622b95defa662facdbef6, 2018-12-07T03:09:14.777Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/private/var/folders/d3/kw4dh3311gncx1kstyqss_hr0000gn/T/AppTranslocation/D64B6402-C693-45E6-8623-ED16F61E1EC3/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Fixed in extension - will look as follows
![image](https://user-images.githubusercontent.com/10819925/49673147-4cda3100-fa22-11e8-9c00-e722837e6367.png)
