### ISSUE TITLE
Connection dialog has overlapping elements

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3514]
![image](https://user-images.githubusercontent.com/8250560/49670139-755d2d80-fa18-11e8-88f6-fb66c31f1d25.png)

![image](https://user-images.githubusercontent.com/8250560/49670161-945bbf80-fa18-11e8-8491-17ce9da1a8d1.png)

Issue Type: <b>Bug</b>

The Connection dialog gets overlapping elements as shown.

I first noticed this when zoomed in and it persisted after zooming out. 

Azure Data Studio version: azuredatastudio 1.3.7-insider (487531cc52c9c7a54147dc179f97b0c4252f7458, 2018-12-04T21:37:09.298Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (4.93GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.0
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
For some reason this only happens in dark theme.

**Comment by kburtram** [comment]
This PR resolves the issue in the `release\1.3` branch.  I'm guess the regression is related to https://github.com/Microsoft/azuredatastudio/commit/f36f3ffd211b2a6aead709652dd175620a620223#diff-8d7ef5bb586fea22d1506d362b8a2d22 and a proper fix can be done in `master` for Jan.

**Comment by kburtram** [comment]
This is fixed in current builds.
