### ISSUE TITLE
"Unknown error" when providing wrong user name and connecting to Big data cluster

### ISSUE THREAD

**Issue by denzilribeiro** [Microsoft/azuredatastudio#3515]
Issue Type: <b>Bug</b>

Make a new connection to a big data cluster
a. In Host put in the IP of the service-security-lb service in kubernetes
b. In username just put in any username ( not root)  -- say xyzuser
c. Put in the password
Hit connect

Actual error:   "Connection failed with error": Unkown error

Expected: Valid error indicating that it is a bad username/password?

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|47.90GB (25.75GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.8.0

</details>

**Comment by kevcunnane** [comment]
Thanks for reporting this. Right now the HDFS library we're using to authenticate is swallowing some error messages. Right now this "usually" means you don't have permission / password is wrong.

We're working on unifying the connections to the cluster going forward, which is likely the best mitigation of this issue. @YurongHe please track this bug as we take on that work.

**Comment by kevcunnane** [comment]
We're going to close this as we are moving to a a single unified connection, and will remove the separate big data cluster connection type in an upcoming release. We'll be working to handle password differences in that case (e.g. on expanding Data Services node under a SQL connection)
