### ISSUE TITLE
Dup connections in AttachTo and Recent Connections

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3523]
Issue Type: <b>Bug</b>

1. Connect a cluster
2. Connect to the same cluster and set "Server group" to test
3. Open ConnectionDialog, we can see the cluster listed twice in Recent Connections.
Look like we treat the same connection as different connections based on "Server group" name. 
![image](https://user-images.githubusercontent.com/43652751/49679302-2f679000-fa3f-11e8-880c-25b81322520d.png)

This may be by design. But it looks weird from UI and caused AttachTo in Notebook displays the same host twice.
![image](https://user-images.githubusercontent.com/43652751/49679311-45755080-fa3f-11e8-8369-61bab6004a88.png)

Azure Data Studio version: azuredatastudio 1.3.7 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (168.11GB free)|
|Process Argv|D:\ads\azuredatastudio\.build\electron\azuredatastudio.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by YurongHe** [comment]
Manage server shows two tabs also if we open it from different server group
![image](https://user-images.githubusercontent.com/43652751/49679498-b10bed80-fa40-11e8-9bac-710f9c82491c.png)

**Comment by kburtram** [comment]
@YurongHe we're tracking the MRU issue at https://github.com/Microsoft/azuredatastudio/issues/3224.  So if that is the underlying issue let's close this as a duplication.  If you want to track this as a separate issue you may want to remove "Recent Connections" from the title to avoid redundancy.

**Comment by YurongHe** [comment]
@kburtram I removed MRS from title and would like to keep it to make sure attachTo not showing dup host name after [ #3224](url) is fixed.
