### ISSUE TITLE
Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (d:\ads\azuredatastudio\out\vs\workbench\node\extensionHostProcess.js:75:37))

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3524]
1. Open and close different Notebooks.
2. Open developer tool. Got the following errors.

Extension Host] rejected promise not handled within 1 second (at Timeout._onTimeout (d:\ads\azuredatastudio\out\vs\workbench\node\extensionHostProcess.js:75:37))
console.(anonymous function) @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280
log @ console.ts:136
ExtensionHostProcessWorker._logExtensionHostMessage @ extensionHost.ts:396
(anonymous) @ extensionHost.ts:214
ZoneDelegate.invokeTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485
emitTwo @ events.js:126
emit @ events.js:214
emit @ internal/child_process.js:772
ZoneDelegate.invokeTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485
data.args.(anonymous function) @ D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:1338
_combinedTickCallback @ internal/process/next_tick.js:141
_tickCallback @ internal/process/next_tick.js:180
D:\ads\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280   ERR request to http://localhost:9124/api/kernelspecs?1544229979539 failed, reason: connect ECONNREFUSED 127.0.0.1:9124: FetchError: request to http://localhost:9124/api/kernelspecs?1544229979539 failed, reason: connect ECONNREFUSED 127.0.0.1:9124
	at ClientRequest.<anonymous> (C:\Users\yuronhe\.azuredatastudio-dev\extensions\microsoft.sql-vnext-0.9.1\node_modules\node-fetch\index.js:133:11)
	at emitOne (events.js:116:13)
	at ClientRequest.emit (events.js:211:7)
	at Socket.socketErrorListener (_http_client.js:387:9)
	at emitOne (events.js:116:13)
	at Socket.emit (events.js:211:7)
	at emitErrorNT (internal/streams/destroy.js:64:8)
	at _combinedTickCallback (internal/process/next_tick.js:138:11)
	at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by chlafreniere** [comment]
Fixed in the extension.
