### ISSUE TITLE
Unable to see top operations tab in 1.2.4 version

### ISSUE THREAD

**Issue by lavanya2290** [Microsoft/azuredatastudio#3529]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open 1.2.4 azure data studio
2. Select server
3. run a query
4. click explain button
 
Expected:
- top operations tab should come

Actual
- top operations tab is not coming
- only results and query plan is coming

<img width="1079" alt="screen shot 2018-12-08 at 11 56 01 am" src="https://user-images.githubusercontent.com/13776413/49682794-6e99ed80-fae0-11e8-8fee-2c2f0df6245d.png">

**Comment by kburtram** [comment]
@anthonydresser any idea where the Top Operations tab went?

**Comment by anthonydresser** [comment]
I never readded it since it was based on angular. I can work on rewriting it.

**Comment by kburtram** [comment]
@anthonydresser we should add it back since it's one of the features that we're providing in the product.  We need to go through a design review process when removing functionality that customers may be depending on.

**Comment by lavanya2290** [comment]
Thanks pls let me know which version it will be available. And also when. Currently we have to analyze performance issues and that tab very useful and handy

**Comment by lavanya2290** [comment]
Thanks pls let me know which version it will be available. And also when. Currently we have to analyze performance issues and that tab very useful and handy

**Comment by lavanya2290** [comment]
Is this fixed when can I take the build

**Comment by kburtram** [comment]
@anthonydresser thanks for fixing!  I'll post an updated insiders build from master this afternoon.

**Comment by lavanya2290** [comment]
Working now checked in feb build
