### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by cypherworld** [Microsoft/azuredatastudio#3531]
Issue Type: <b>Feature Request</b>

Can't edit table structures!

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:38:48.126Z)
OS version: Linux x64 4.19.6-300.fc29.x86_64

**Comment by kburtram** [comment]
@cypherworld thanks for the suggestion.  We're tracking this feature request in https://github.com/Microsoft/azuredatastudio/issues/282.
