### ISSUE TITLE
When opening 2 database connections, only one will open and one will fail to open

### ISSUE THREAD

**Issue by th0mk** [microsoft/azuredatastudio#3533]
Issue Type: <b>Bug</b>

1. Open one database connection
2. While azure data studio is loading that connection, open another one on the same server but with a different database
![image](https://user-images.githubusercontent.com/9088316/49737956-6bdcfb00-fc8e-11e8-9243-fb502f5e507f.png)

3. When both connections have loaded, only one will show the tables, while the other one doesn't show anything when its opened. To fix this I have to reconnect to top connection
![image](https://user-images.githubusercontent.com/9088316/49737782-fcffa200-fc8d-11e8-9a00-d815f057da95.png)

This issue only occurs once, to reproduce it after fixing it you have to restart data studio.
Both connections are to the same server with different SQL user logins.

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2690 v2 @ 3.00GHz (8 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|6.00GB (0.92GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
import|Mic|0.4.0
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
@robertjanquist there is likely a bug in the way we're uniquely identifying the server nodes.  I'll take a look.  As a workaround, you could probably put the connections in different Server Groups.

**Comment by kburtram** [comment]
We've made several improvements to the async handling of server node expansion.  Please let us know if you're still impacted by this bug.
