### ISSUE TITLE
Chart viewer axis minimum/maximum value can't be 0

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#3538]
- Azure Data Studio Version: 1.3.8-rc

Steps to Reproduce:
1. Run a query that returns numeric results
2. Open chart viewer
3. Select horizontalBar or verticalBar chart types
4. Set X/Y Axis Minimum/Maximum values to 0

Expected behavior: The minimum/maximum values update like they do if you set them to any other value
Actual behavior: Entering 0 has no effect

**Comment by johny-numbers** [comment]
Any update? Still broken in ADS 1.5.2.

**Comment by kburtram** [comment]
This is a pretty annoying bug.  The below screenshot provides some visual context of the impact.

![image](https://user-images.githubusercontent.com/599935/60847384-5c2b8380-a197-11e9-91b0-e12c633850eb.png)

**Comment by gstolecki** [comment]
Still broken in ADS 1.23.0.
