### ISSUE TITLE
Azure Resource Explorer buttons are duplicated

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3540]
Issue Type: <b>Bug</b>

1. Add an Azure Account
2. Open Azure Resource Explorer

Actual behavior: All buttons are duplicated
Expected behavior: Only one copy of each button shows up

Azure Data Studio version: Azure Data Studio 1.3.8 (4a4b8574d0808adb33bc33d1112505fd42e22cc7, 2018-12-10T19:42:39.534Z)
OS version: Darwin x64 18.2.0

![Azure Resource Explorer with multiple refresh and filter buttons for each account, and multiple refresh buttons at the top](https://user-images.githubusercontent.com/3758704/49764773-413a7480-fc85-11e8-9c3b-78a0b465c462.png)

**Comment by kevcunnane** [comment]
@iVincentFeng can you investigate this?

**Comment by iVincentFeng** [comment]
I can't repro it on Ubuntu. Let me try to get a macbook to repro it.

![image](https://user-images.githubusercontent.com/2157307/49982274-b57f5b80-ff96-11e8-84f9-74fb8f944c47.png)

**Comment by iVincentFeng** [comment]
I can't repro it on macOS (Mojave, 10.14.1), either. 

![default](https://user-images.githubusercontent.com/2157307/50044967-57519600-00c6-11e9-9260-74f36d8e2ccd.png)
