### ISSUE TITLE
Backup scripting doesn't add a task until complete on big databases

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#3542]
- Azure Data Studio Version: 1.3.8-rc

Steps to Reproduce:
1. Open the database dashboard for a reasonably large database (mine is about 3000mb)
1. Open the backup widget and script the backup

Expected behavior: The backup script operation immediately appears in task history and stays there until it is complete
Actual behavior: The backup script operation only shows up in task history once it is complete, which takes about a minute

**Comment by kburtram** [comment]
Closing older issues.  There is a small delay between queuing a backup task and it showing in the UI, but it shouldn't wait until the backup is completed.  Please let us know if this is impacting current builds.
