### ISSUE TITLE
Notebook: When a new cell is added it is not made the active cell. Previously selected active cell remains active.

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3545]
Issue Type: <b>Bug</b>

Steps to repro:
1. Open a notebook
2. Select a cell and make it active.
3. Add a new cell by clicking on +Code or +Text in the tool bar

Actual:
The selected active cell remain active and the new cell is inactive.

![image](https://user-images.githubusercontent.com/27451624/49767971-69c76c00-fc8f-11e8-82c7-ed7e8f5f6cca.png)

Expected:
The new cell as soon as its added should become the active cell.

Azure Data Studio version: Azure Data Studio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T21:55:17.560Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (2.14GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_3126011|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
sql-vnext|Mic|0.9.1
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
I think this is covered by my other bug #3546 so closing this as a duplicate
