### ISSUE TITLE
Notebooks: Add cell should prompt for position (above/below/ at end of doc)

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3547]
- Open a notebook with a number of cells, and have 1 cell selected
- Click the `Code` or `Text` buttons to add a new cell

Expected:
- Get prompt so you can choose where to add the cell. Ideally would have above & below current cell in addition to an option to add at the end of the doc. If no cell is selected, always add to the end
Actual:
- Just add cell to the end. Made worse by #3546 which means that you often can't see the new cell

**Comment by chlafreniere** [comment]
We have this capability in the cell toggle more actions.
