### ISSUE TITLE
HDFS Create External Data: should filter system schemas from list of available schemas

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3555]
**Edit**: this is worse than expected as `sys` isn't scripted out, and get weird scripting and use of `dbo` instead.

Steps to Reproduce:

1. Connect to SQL Server big data cluster, right-click on a CSV file to start the wizard
2. Choose a SQL Server connection
3. In the `Select Database` page click the `Schemas` dropdown

![image](https://user-images.githubusercontent.com/10819925/49769136-e8bea380-fc93-11e8-85b9-5f4ddd2d7822.png)

Expected:
- only `dbo` and probably `guest` show up
Actual:
- `sys` and other system-level schemas show up. These aren't normal to import to and I believe should be blocked.
- If you choose `sys` schema, when you script out the external data commands you'll see that `sys` isn't there, and the actual table is created in dbo instead! This is quite bad.

![image](https://user-images.githubusercontent.com/10819925/49769323-8dd97c00-fc94-11e8-9231-e90998ca6264.png)

```sql
BEGIN TRY
    BEGIN TRANSACTION Te892f7e797ca4214bc784a82cf6ec79
        USE [NewDatabaseFTW];
        CREATE EXTERNAL FILE FORMAT [FileFormat__redmond_data]
            WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = ',', STRING_DELIMITER = '"', FIRST_ROW = 2));
        CREATE EXTERNAL TABLE .[redmond_data]
        (
            [ID%^&*(] nvarchar(50) NOT NULL,
            [Date] date NOT NULL,
            [Element] nvarchar(50) NOT NULL,
            [Data_Value] smallint NOT NULL
        )
        WITH (LOCATION = '/Sensor_Data/redmond_data.csv', DATA_SOURCE = [SqlStoragePool], FILE_FORMAT = [FileFormat__redmond_data]);
    COMMIT TRANSACTION Te892f7e797ca4214bc784a82cf6ec79
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION Te892f7e797ca4214bc784a82cf6ec79
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;
```

**Comment by corivera** [comment]
Fixed
