### ISSUE TITLE
New notebook with content should prompt for save while closing it

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3556]
![image](https://user-images.githubusercontent.com/44002319/49769112-d6446a00-fc93-11e8-8fbc-4c23afc6cbc0.png)

1. Create a new notebook and add some content
2. Try to close the editor, it should give us a message saying 'Do you want to save?' similar to SQL editor. 
3.  It's working in par with the earlier version of notebook but it's a good feature to have.

**Comment by kevcunnane** [comment]
Close as duplicate
