### ISSUE TITLE
Notebook doesn't infer header as part of schema

### ISSUE THREAD

**Issue by jrowlandjones** [Microsoft/azuredatastudio#3557]
Issue Type: <b>Bug</b>

1. Load data with no header but a mix of columns with NULLs, and values
2. Run notebook.

Two issues with this:
1.
Schema was not correctly inferred. .option("header") was set to true but there was no header.
2. 
NULL columns will use zero based (not 1 based) column ordinals but columns with values use the first row << inconsistent - either use the first row or use 1 based ordinals.

SparkSession available as 'spark'.
+-----+-----+----+-----+---+----+
|36890|40052| _c2| 4379| 34| _c5|
+-----+-----+----+-----+---+----+
|36890|41285|null| 6245| 34|null|
|36890|23115|null|13852| 34|null|
|36890|17702|null|15975| 34|null|
|36890|62676|null| 2119| 34|null|
|36890|34267|null|10273| 34|null|
|36890| 8502|null|17790| 34|null|
|36890|54340|null| 3453| 34|null|
|36890|54370|null| 6372| 34|null|
|36890| 6578|null|17203| 34|null|
|36890|75088|null| 4891| 34|null|
+-----+-----+----+-----+---+----+

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (25.06GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.0.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.8.0

</details>

**Comment by chlafreniere** [comment]
The text that we put into the cell for Analyze in notebook is static and an example and may require users to customize it to work for their scenarios.
