### ISSUE TITLE
External Data: Improve behavior when wizard is targeting an unsupported version

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3559]
When the External Data wizard is launched against an unsupported version of SQL Server, the UI looks a little broken. "Select your data source type" with no options listed, for example:

![image](https://user-images.githubusercontent.com/8250560/49769338-9a5dd480-fc94-11e8-86e8-bc600fb20af4.png)

It would be better still if the wizard could not be launched in the OE against an unsupported version.

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (2.73GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
We should disable the next button and not show content here.

**Comment by corivera** [comment]
Fixed
