### ISSUE TITLE
Markdown is not aligned with text in Text cell

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3560]
![image](https://user-images.githubusercontent.com/44002319/49769386-caa57300-fc94-11e8-9393-910407704c20.png)

Not sure if it's an issue but text and markdown are not aligned.

**Comment by kevcunnane** [comment]
This is by design from the UX team. We've added in padding, but otherwise leaving as-is for now.

**Comment by chlafreniere** [comment]
By design for now.
