### ISSUE TITLE
Manage Dashboard Shouldn't have "Copy Path" Option for Tab

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#3563]
Go to Manage dashboard when connected to a SQL Server big data cluster.

Right click on the tab title, and notice that "Copy Path" is an available option. This will copy "dashboard:dashboard" to the clipboard, which isn't helpful. We should remove this option.

**Comment by kburtram** [comment]
I no longer see the Copy Path option on dashboards.
