### ISSUE TITLE
Keyboard focus does not go to wizard on launch

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#3564]
Issue Type: <b>Bug</b>

When a wizard is launched from the OE, keyboard focus does not go to the wizard. You have to click to get focus adjusted.

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (2.62GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.0
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
@alanrenmsft is this still targeted for July?  If not, please move to Postponed milestone.

**Comment by kburtram** [comment]
This doesn't appear to repro on current builds.  Please let us know if this issue is still impacting your scenario.

**Comment by alanrenmsft** [comment]
@kburtram yes, I have fixed the issue a while back for both dialogs in core as well as the ones created by extensions, but forgot about this issue. thanks for closing.
