### ISSUE TITLE
Wizard button focus is too subtle

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#3566]
Issue Type: <b>Bug</b>

I am trying to navigate the External Data wizard with a keyboard. It's not possible to distinguish which of these buttons has focus.

![image](https://user-images.githubusercontent.com/8250560/49769606-a9915200-fc95-11e8-8c2c-9b1d51762a6d.png)

![subtle focus](https://user-images.githubusercontent.com/8250560/49769848-b8c4cf80-fc96-11e8-854b-eb965d7e352f.gif)

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (2.62GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.1
import|Mic|0.4.2
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.0
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Removing `accessibility` label since we only track color contrast issues report with the High Contrast theme.  Adding `ux` label instead.

**Comment by kburtram** [comment]
The button UX has been redesigned since this bug was filed.  Currently the active and inactive buttons have a more distinct appearance.

![image](https://user-images.githubusercontent.com/599935/129817237-96138b39-7110-4ac0-84d1-adcc728d4569.png)
