### ISSUE TITLE
Unnecessary double-scroll bar on results

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3567]
Issue Type: <b>Bug</b>

- Select top 1000 on a table with 100 rows
- Wait for results to be previewed

Expected:
- Just 1 resultset, so max 1 scrollbar on right
Actual:
- 2 scrollbars, 1 of which is small but annoying. If you try to move it up/down it'll be difficult, and it either clips the last result or the top of the header grid
![image](https://user-images.githubusercontent.com/10819925/49769855-c4b09180-fc96-11e8-88c4-078bb49c2d9d.png)

Azure Data Studio version: Azure Data Studio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T21:55:17.560Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|/Users/kevcunnane/Downloads/BugBash_Dec10/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_10353119|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
sql-vnext|Mic|0.9.1

</details>

**Comment by kburtram** [comment]
@anthonydresser I think this will likely go away once Messages are moved into there own tab.  Does that sound right to you?

**Comment by anthonydresser** [comment]
Likley, but it could still be a problem. I've never seen this before though.

**Comment by anthonydresser** [comment]
@kevcunnane I can't seem to repro. @kburtram can you repro this?
