### ISSUE TITLE
Notebook Doesn't Prompt for Save even when isDirty=true

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3568]
In a notebook, make a change. Dirty state of document will be true, and you will see a filled in circle in the title bar.

Close the notebook tab,  and notice that the user is not prompted to save the file.

**Comment by kevcunnane** [comment]
@rajmusuku  - verify whether on close of Azure Data Studio we prompt, since currently we would lose changes

**Comment by rajmusuku** [comment]
ADS gets closed without any prompt. Prompt applies only to notebooks.

**Comment by kevcunnane** [comment]
@rajmusuku we should be careful when fixing this. Our test automation currently doesn't handle closing notebooks so might hang if you fix this without some way to avoid prompt in test scenarios / have an option not to prompt on save.

**Comment by rajmusuku** [comment]
@kevcunnane : After a careful thought and little bit of investigation, here are my comments

- What if multiple notebooks are in dirty mode, should we prompt for each one of them while closing ADS? I agree that we will loose our changes, but with the native save implementation we can have a permenant fix.
- Right now we don't have save prompt for sql query editors, we can directly close ADS. Wouldn't it be confusing to user by fixing this issue?

Let me know you input.

**Comment by kevcunnane** [comment]
I agree. My only concern here is data loss. For query editors, they are reopened on next open of the editor with their previous in-progress changes available. Perhaps we can expedite this, and for now doc this as a known issue (work with Alan Yu for this)

**Comment by rajmusuku** [comment]
@yualan :  We need to document this as a knows issue for Feb release. Could you let me know what do you need from me.
Issue: All the opened notebooks in ADS with dirt state, will loose changes when we close Azure Data Studio. But, user will be prompted with a save message when each notebook is closed.

**Comment by yualan** [comment]
Sounds good, we will need to add to release note on docs and blog, thanks for letting me know. If you have a full list of known issues/features to highlight, feel free to email me

**Comment by rajmusuku** [comment]
@kevcunnane I think we can close this issue since save-prompt works for Notebooks and open a different one for ADS notebook persistency ?
