### ISSUE TITLE
Recent connection list keeps adding connections

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3569]
Issue Type: <b>Bug</b>

1. Connect a SQL Server
2. Query some table from different dbs in the sever connected from step 1 by right click the db name
3. We can see those connections are added to recent connection list since db name is different.
![image](https://user-images.githubusercontent.com/43652751/49769974-34bf1780-fc97-11e8-85c2-e8f6259e1cca.png)

Too many connections to the same servers if people only care about the server.

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (46.43GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by kburtram** [comment]
I think the intended design is that query editor adds connections to the MRU.  Perhaps this only makes sense if the user connects the query editor using the Connection Dialog, rather than New Query command from Server viewlet.

**Comment by Eagle3386** [comment]
I'm also bugged by this "feature". IMHO, it's a bug as the view's tab title clearly states "Recent connections", not "Recent databases" and the fact that one doesn't connect to a database, but instead to a server.

**Comment by kburtram** [comment]
This should be fixed in the latest builds.  Please let us know if you're still impacted by this issue.
