### ISSUE TITLE
Database Encryption Key has its own folder, and shows as key with no name

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3576]
I'm not sure if this is by design or a mess up, but we have a bunch of Security folders not in SSMS and one even has keys with no name.

- Connect to sql 2019 server and expand security folder
- You'll see a `Database Encryption Keys` folder even though none seems to be shown in SSMS
- Weirder still, you get 1 key, which appears blank, in the list. See screenshot below.

![image](https://user-images.githubusercontent.com/10819925/49770296-b794a200-fc98-11e8-8f41-0f6a07d973ba.png)

**Comment by kburtram** [comment]
I don't see this folder on SSMS but I do see it in SSDT.  I'll close this older issue as a low-impact inconsistency.
