### ISSUE TITLE
"Open EDITORS" UNSAVED don't track new notebooks

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3577]
Issue Type: <b>Bug</b>

1. Create new notebooks and edit them
2. We can see the files have dirty icon. But in EXPLORER, the UNSAVED count is not increased.

![image](https://user-images.githubusercontent.com/43652751/49770368-06dad280-fc99-11e8-97f2-e20bd82fdcbb.png)

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (46.43GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by YurongHe** [comment]
It does track SQL Files.
![image](https://user-images.githubusercontent.com/43652751/49770433-37227100-fc99-11e8-9448-fa65b48c6b59.png)

**Comment by chlafreniere** [comment]
This has been fixed and is now being tracked properly.
