### ISSUE TITLE
Extensibility: Unnecessary context menu on input box control

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#3578]
There is a right click context menu on the password field on Create Database Master Key. As far as I can tell it does not do anything, though keyboard shortcuts behave as expected (ctrl-v and ctrl-z allowed, ctrl-c not).

![image](https://user-images.githubusercontent.com/8250560/49770402-283bbe80-fc99-11e8-82d5-60195c086536.png)

**Comment by kevcunnane** [comment]
This is an extensibility issue - the inputbox control shouldn't show this if it doesn't make sense.

**Comment by anthonydresser** [comment]
Every inputbox in ads and vsc have this context menu. By "it does not do anything" do you mean you don't think it makes sense? or that the actions don't work? (e.x. Selecting the text and selecting cut doesn't cut the text)

**Comment by kburtram** [comment]
Closing older issues.  This is a built-in context menu for all input boxes as mentioned in previous comment.  Thanks!
