### ISSUE TITLE
Notebooks: Ensure Kernel Knows About Filename Changed Events

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3579]
Kernels aren't notified on filename changed events (i.e. save events); because of this, IntelliSense breaks in notebooks after the first file save occurs in a document.

**Comment by kevcunnane** [comment]
@rajmusuku I'm moving this to April unless you disagree.

**Comment by chlafreniere** [comment]
Dupe of #3522.
