### ISSUE TITLE
External Data Wizard: Data source objects folder icons are black on black in dark mode

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3584]
The data source folder icons on the External Data Wizard do not render well in dark mode. They are black on almost-black.

![image](https://user-images.githubusercontent.com/8250560/49771006-f415cd00-fc9b-11e8-9f1a-e99792f16179.png)

Some of the other icons look a little clipped.

![image](https://user-images.githubusercontent.com/8250560/49771105-77372300-fc9c-11e8-9219-f2b26678ab07.png)

**Comment by geleems** [comment]
This had been fixed.
