### ISSUE TITLE
Group name in "Saved connection" doesn't have icon (expanded/collapsed glyph) in front to indicate mulitple servers

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3589]
Issue Type: <b>Bug</b>

1. create few saved connections and put them in different groups.
2. Open connection dialog
3. Select "Saved connection"
![image](https://user-images.githubusercontent.com/43652751/49776130-aacf7880-fcaf-11e8-9433-808fcaecd9f8.png)

We can see the screenshot, the left server group name has icon in front of the name to indicate multiples connections. While the "Save connection" group name doesn't have the icon.

Azure Data Studio version: azuredatastudio 1.3.8-insider (b6e32cdeb439246afc6fdcd11d9af2c74ba0ea5a, 2018-12-10T22:09:47.695Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (45.76GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by cheenamalhotra** [comment]
Closed as stale.
