### ISSUE TITLE
"Active connection" view is replaced with all server connections after connect to a new server

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3590]
Issue Type: <b>Bug</b>

- Connect to a SQL Server
- Select "Show active connections"
- Select "New connection" From Servers
  After the new server is connected, the server explorer is replaced with all server connections.

Expected:
The new server is added to active connection view. 
The problem is on windows. Didn't test on Linux. Mac has no issue. The new server is added to active connection. And still shows "Active Connections".

Azure Data Studio version: azuredatastudio 1.3.8 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (170.47GB free)|
|Process Argv|C:\code\azuredatastudio\.build\electron\azuredatastudio.exe .|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.1

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still impacted by this issue.
