### ISSUE TITLE
Enhanced Results Grid

### ISSUE THREAD

**Issue by nexusio** [Microsoft/azuredatastudio#3591]
Issue Type: <b>Feature Request</b>

As a data analyst i would be highly useful to make the results grid more interactive. 
   1. Allow Column Sorting
   2. Allow Column Filtering (Think Excel)
   3. All user to select a column to remove (I dont need that after all)
   4. Allow Aggregation of Results, that are only client side and dont effect the sql query.
      4.1 Allow user to click a column and select SUM, COUNT, AVG, etc... and see the results at the bottom of the results
      4.2 Allow user to move column to "top" of results grid, resulting in a "group by'ing" of the results

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.15063

**Comment by kburtram** [comment]
@nexusio thanks for opening this issue.  We're tracking grid enhancements at https://github.com/Microsoft/azuredatastudio/issues/569.  I've copied your comments over.  Please add any additional comments to that issue.
