### ISSUE TITLE
User-Defined Function Bug - Errors thrown when there shouldn't be an Error

### ISSUE THREAD

**Issue by JASM2007** [Microsoft/azuredatastudio#3593]
- Azure Data Studio Version:

Steps to Reproduce:

1. I am having issues with User-Defined Functions using Azure Data Studio.
2. Create a function
3. SELECT the function and it throws an error.
4. If I run the same script in SQL Server Management Studio I get the expected results and no errors are thrown.
5. I have tried reconnected closing the application and reopening etc...

![image](https://user-images.githubusercontent.com/40634806/49811130-98e1ea00-fd30-11e8-84be-8fd42340eb76.png)

![image](https://user-images.githubusercontent.com/40634806/49810647-a5b20e00-fd2f-11e8-993d-f80f8b7f9c0a.png)

**Comment by yualan** [comment]
Hi @JASM2007, we are having issues reproing this, can you provide more info?
