### ISSUE TITLE
Jupyter Notebook file mode doesn't work

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3599]
- open any file
- Click on the language mode and change to `Jupyter Notebook`

Expected:
- This is called `Notebook`
- This opens as notebook viewer, or cleanly fails with error and shows as text
Actual:
- Literally nothing happens.

**Comment by chlafreniere** [comment]
@kevcunnane can you clarify here?

**Comment by kevcunnane** [comment]
- Open a non-sql file from disk (e.g. .json)
- Click the language in the bottom right
![image](https://user-images.githubusercontent.com/10819925/56447050-f7107200-62ba-11e9-81df-a262b0b4a4cc.png)

- Choose "Notebook". What should happen? Why do we have this / should it switch a file to be in notebook viewer mode?
![image](https://user-images.githubusercontent.com/10819925/56447036-e52ecf00-62ba-11e9-86e3-52e42641f531.png)
