### ISSUE TITLE
Performance issues (memory leak ?)

### ISSUE THREAD

**Issue by bciesielski** [Microsoft/azuredatastudio#3610]
- Azure Data Studio Version:
Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64 (win 7 on a virtual machine)
Steps to Reproduce:

After working in ADS for some time (hours/days) performance issues start to occur. 
The allocated memory grows to (currently) 1,5-2GB even though only about 5-8 tabs are open.
ADS becomes laggy and loads query results slowly (that might be due to high memory usage / limited memory on the remote virtual machine it is running on).
CPU can go to 40-50% e.g. when switching tabs.

![image](https://user-images.githubusercontent.com/36210825/49863314-538ced80-fe00-11e8-81b2-80dc196cd293.png)

I have also noticed (unsure if it matters) some errors in the dev console:

> [Extension Host] [Error - 4:46:00 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 4:49:23 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 4:58:49 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 4:58:50 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280   ERR Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
>     at _loop_1 (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:291684:57)
>     at GridPanel.addResultSet (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:291705:17)
>     at GridPanel.onResultSet (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:291657:18)
>     at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:291644:102
>     at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:17816:38)
>     at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:18459:21
>     at Emitter.fire (file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:17816:38)
>     at file:///C:/Program Files/Azure Data Studio/resources/app/out/vs/workbench/workbench.main.js:18501:37
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 5:42:27 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: This object type is currently not supported by this feature.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 5:42:27 PM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 9:37:04 AM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0 
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 10:50:50 AM] Request textDocument/definition failed.
> C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: No results were found.
>   Code: 0

**Comment by kburtram** [comment]
@bciesielski we fixed a significant memory leak for issue https://github.com/Microsoft/azuredatastudio/issues/2899 with PR https://github.com/Microsoft/azuredatastudio/pull/3458.  This fix will be available in the Dec release next week and hopefully will help with the issue you're seeing.

**Comment by kburtram** [comment]
I'll close this based on fixes that went on in the Jan release.  Please let me know if the problem persists on current builds.

**Comment by bciesielski** [comment]
@kburtram , thanks. I am running the Jan release for a few days now and haven't noticed any memory leaks, so this seems to be resolved.
