### ISSUE TITLE
Cannot see extension tabs next to Home Title Bar

### ISSUE THREAD

**Issue by CubsRep** [Microsoft/azuredatastudio#3621]
Issue Type: <b>Bug</b>

I have installed SQL server agent/import/whoisactive extensions and reloaded. Cannot see them in the dashboard screen. 
Never had this issue when using SQLOps which I recently replaced.

![image](https://user-images.githubusercontent.com/23372182/49919456-4c032e00-fe6c-11e8-9104-4ecb009fb36b.png)

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (10.17GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.3.0
agent|Mic|0.35.0
import|Mic|0.4.0
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by Yggwit** [comment]
Hello,

I had the same problem. A setting was missing from my old SQL Operations Studio settings file.
Just adding this should do the work:
`"workbench.enablePreviewFeatures": true`

Regards,
Ygg'

**Comment by alanrenmsft** [comment]
@CubsRep  Definitely do what @Yggwit mentioned here, after that if you still don't see it, try click the "+" button on the right side and select the dashboard from the pop out menu.

**Comment by CubsRep** [comment]
@Yggwit  - Thanks for the suggested fix. Yeah It is visible and working now 👍
