### ISSUE TITLE
We need to provide better error handling messages for conencting to clusters

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#3625]
Issue Type: <b>Bug</b>

When we connect to the SQL Server big data cluster we need a way to better surface error messages. For the unified connection work this might be something we need to raise and fix.

This error message is not helpful.

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22312581/49963865-fcede500-fecd-11e8-8890-349aa0e1ec28.png">

Azure Data Studio version: Azure Data Studio 1.3.8 (348b03327eba147e7018a7c0af4061373326802e, 2018-12-11T19:39:51.432Z)
OS version: Darwin x64 17.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|17, 14, 6|
|Memory (System)|16.00GB (0.56GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/C6BAACE7-4D88-4513-B72B-09D9E47129EE/d/Azure Data Studio-2.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please let me know if you are still impacted by this issue.  Thanks!
