### ISSUE TITLE
Unable to import file using Flat File Wizard when connected through AAD

### ISSUE THREAD

**Issue by JerroldM10** [microsoft/azuredatastudio#3626]
- Azure Data Studio Version: 1.3.6

Steps to Reproduce:

1. Open connection through "Azure Active Directory - Universal with MFA Support";
2. Open flat file import wizard (ctrl+i);
3. Select a file, schema and table name;
4. Click Next->Next->Import Data;
5. Error is shown: Cannot open server "@XXXX.com" requested by the login. The login failed.
Import does work when repeating same steps when logged in with 'SQL Login'

**Comment by NeilGoodUK** [comment]
This continues to be an issue for us as well.
SQL Version - Microsoft SQL Azure (RTM) - 12.0.2000.8
Using AAD with Universal MFA
ADS Version: 1.20.1 (user setup)
Commit: fe6312306647441b30102a64bb43abb06ebcf2be
Date: 2020-07-17T02:39:41.016Z
VS Code: 1.47.0
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
