### ISSUE TITLE
Support drag-n-drop columns and tables into Query Editor

### ISSUE THREAD

**Issue by sadlave** [microsoft/azuredatastudio#3630]
- Azure Data Studio Version:1.2.4

Steps to Reproduce:
when writing the query I can not drag tables or columns from server navigation pane. This feature is available in SSMS
![annotation 2018-12-17 090330](https://user-images.githubusercontent.com/45934929/50076851-adaff900-01da-11e9-9108-920dd8251ea9.jpg)

**Comment by SQLvariant** [comment]
Please don't limit this to the Columns node, we would like to drag-and-drop any object name, or collection of object names.  Please make sure this works for all file types as well.  For instance, I might want to drag-and-drop instance, database, or table name into a .PS1 file that I am currently working on.

**Comment by madcour11** [comment]
Wondering whether this is a bug since attempting the old drag-and-drop columns feature crashes SSMS your only option a task kill.

**Comment by dbrtly** [comment]
I really miss this feature. 
Possible alternative for columns would be automatic wildcard substitution.

**Comment by merrillaldrich** [comment]
Wishes: conditional inclusion of [square brackets] only when needed. *Formatted* list of columns with a choice of commas before or after each name. Then, ahem, star expansion.

**Comment by cssuh** [comment]
![DragDrop](https://user-images.githubusercontent.com/18150417/83922199-edabc880-a74d-11ea-8dca-26b1b851d9bb.gif)
Here is a brief gif of the functionality I have been working on, feel free to leave feedback.

**Comment by SQLvariant** [comment]
That looks awesome!  

Since we're working in this area...  
could we make it so that if you hold down the Ctrl key or the Shift key, before you drag (<kbd>Ctrl</kbd>+<kbd>{dragging action}</kbd>), that it copies the full path (URI?) of the object you're dragging?  

So in the .gif above, it would copy something like `chris-test-server.test-db.dbo.Employees.EmployeeId`.
