### ISSUE TITLE
Tabbing at end of Edit Data "New Row" moves focus outside grid

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3635]
- Azure Data Studio Version: 1.3.8

Steps to Reproduce:

1. Click on the "New Row" in Edit Data to add a new row
2. Fill out the required rows and click TAB at the last row

Expected: New row is committed and another "New Row" is created for inputting the next new row
Actual: Focus moves outside the grid to next tab-able element.  The new row is not committed.

**Comment by MattIrv** [comment]
This is mostly behaving correctly for me in last night's daily build. The only case where it behaves like you reported is if you only enter content in the last column of the new row and not any other columns, which is the same behavior in the November build

**Comment by kburtram** [comment]
@MattIrv thanks for confirming.  I'll this issue then.
