### ISSUE TITLE
Agent column header sort arrows overlap text

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3638]
- Azure Data Studio Version: 1.3.8

Steps to Reproduce:
1. Open the agent jobs dashboard

![Agent jobs dashboard showing grid column header text overlapping their sort arrows](https://user-images.githubusercontent.com/3758704/50176394-1b7c2380-02b4-11e9-93fc-75a81b499468.png)

**Comment by abist** [comment]
This is related to https://github.com/Microsoft/azuredatastudio/issues/3636, since both of them are dependent of the same column-sizing function

**Comment by abist** [comment]
Closed because fixed.
