### ISSUE TITLE
Fresh Install shows Black Screen without any icons 

### ISSUE THREAD

**Issue by MarianoKovo** [Microsoft/azuredatastudio#3640]
- Azure Data Studio Version:

Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

Default installation on Microsoft Windows 10 Pro [Version 10.0.16299.371].

The inner screen of the Azure Data Studio is completely black. 

![ads_blackscreen](https://user-images.githubusercontent.com/32372763/50222417-f1d80080-0376-11e9-875e-a3e522d04701.PNG)

**Comment by kburtram** [comment]
@MarianoKovo I haven't seen this behavior before.  Have you tried uninstalling and reinstalling?

**Comment by MarianoKovo** [comment]
@kburtram Yes, full uninstall and reinstall. Same issue with versión 1.2.4.

I have uninstalled version 1.2.4 and installed the actual version 1.4.5. The issue has been corrected. Thanks a lot!

**Comment by kburtram** [comment]
@MarianoKovo great to hear it's working now!  Not sure exactly what changed for this area.  I'll close the issue now.  Please let us know if the issue reoccurs.
