### ISSUE TITLE
Profiler Extension - Filtering please!

### ISSUE THREAD

**Issue by MikeYeager** [Microsoft/azuredatastudio#3645]
Thank you for the profiler. It finally allows me to profile against Azure SQL DBs. Unfortunately I'm getting a LOT of data profiling a database with a lot of users and I only care about a few specific events. Being able to only collect the events I'm interested in would be awesome!

Thanks,
Mike

**Comment by alanrenmsft** [comment]
thanks @MikeYeager for letting us know, this will the the next feature we will be working on for profiler.

**Comment by alanrenmsft** [comment]
@MikeYeager , The filtering feature has been implemented, You can check it out when the next insider build is released.

**Comment by MikeYeager** [comment]
Thanks. I'm really looking forward to it.

**Comment by alanrenmsft** [comment]
@MikeYeager please try this build: https://github.com/Microsoft/azuredatastudio/releases/tag/1.4.3

**Comment by MikeYeager** [comment]
Thank you!

Sent from my iPhone

On Jan 31, 2019, at 12:53 PM, Alan Ren <notifications@github.com<mailto:notifications@github.com>> wrote:


@MikeYeager<https://github.com/MikeYeager> please try this build: https://github.com/Microsoft/azuredatastudio/releases/tag/1.4.3

**Comment by yualan** [comment]
You can also wait for the stable February build, which will be coming out in 2 weeks :) If you are planning to try the insider build which Alan shared, feel free to give us feedback before we include this in stable. Thanks Mike and Alan!

**Comment by MikeYeager** [comment]
Will do!

Sent from my iPhone

On Jan 31, 2019, at 1:20 PM, Alan Yu <notifications@github.com<mailto:notifications@github.com>> wrote:


You can also wait for the stable February build, which will be coming out in 2 weeks :) If you are planning to try the insider build which Alan shared, feel free to give us feedback before we include this in stable. Thanks Mike and Alan!
