### ISSUE TITLE
Scrolling on table with many colums is janky

### ISSUE THREAD

**Issue by akraines** [microsoft/azuredatastudio#3646]
Issue Type: <b>Performance Issue</b>

I have a Table with about 39 columns and 429 rows
Select Top 100 rows (returns 429 rows)
Scrolling side to side is a bit janky
Scrolling down is much more janky (shows white until the data is loaded)

Since the user already made the query to load all 1000 rows, it should have that data in memory already, so this is probably display/windowing issue.

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_393312|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   12	    66	  1545	azuredatastudio main
    0	    33	  2284	   gpu-process
    0	   164	  2288	   window (SQLQuery_1)
    0	     0	  2310	     searchService
    0	    16	  2311	     extensionHost
    0	    16	  2463	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.52/MicrosoftSqlToolsServiceLayer --log-file /Users/akraines/Library/Application Support/azuredatastudio/mssql/sqltools_2311.log --tracing-level Critical
    0	     0	  2466	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.52/SqlToolsResourceProviderService --log-file /Users/akraines/Library/Application Support/azuredatastudio/mssql/resourceprovider_2311.log --tracing-level Critical
    0	     0	  2467	       /Applications/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/1.5.0-alpha.52/MicrosoftSqlToolsCredentials --log-file /Users/akraines/Library/Application Support/azuredatastudio/mssql/credentialstore_2311.log --tracing-level Critical
    0	    16	  2309	   shared-process
    0	    82	 53422	   window (Issue Reporter)
    0	     0	 53425	   /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by kburtram** [comment]
We've made several performance improvements to the results grid since this bug was filed.  Please let us know if you're still experiencing impact from this issue.
