### ISSUE TITLE
Table valued functions and Scalar functions in wrong function classification

### ISSUE THREAD

**Issue by dsmeltz** [microsoft/azuredatastudio#365]
- SQL Operations Studio Version:
0.24.1

I'm not sure how to reproduce.

Table Valued Functions and Scalar functions seem to be arbitrarily assigned to their respective Explorer Folders.  When opening Scalar-valued Functions a large portion of our TVF's are displayed.  Also when opening the Table-valued Functions some Scalar valued functions are displayed.  There is no duplication in names between the 2 folder views.  It just looks like the functions are somehow being categorized incorrectly.
[ScalarFunctions.xlsx](https://github.com/Microsoft/sqlopsstudio/files/1572679/ScalarFunctions.xlsx)

My comparison for what is 'right' is SSMS.

I've included 2 spreadsheets comprised of data from the following queries:

TVF's
select SPECIFIC_NAME, ROUTINE_TYPE, DATA_TYPE from INFORMATION_SCHEMA.ROUTINES
where ROUTINE_TYPE = 'function'
and data_type = 'table'
ORDER by SPECIFIC_NAME

Scalar's
select SPECIFIC_NAME, ROUTINE_TYPE, DATA_TYPE from INFORMATION_SCHEMA.ROUTINES
where ROUTINE_TYPE = 'function'
and data_type <> 'table'
ORDER by SPECIFIC_NAME
[TVFunctions.xlsx](https://github.com/Microsoft/sqlopsstudio/files/1572680/TVFunctions.xlsx)

**Comment by kburtram** [comment]
I am not able to repo on latest build.  Please let us know if you're still impacted by this issue.
