### ISSUE TITLE
I can't scroll sideways in the Chart tab after minimizing the window

### ISSUE THREAD

**Issue by MohamedSahbi** [microsoft/azuredatastudio#3651]
- Azure Data Studio Version:
Version 1.2.4
Commit 1ebfd0235690ad044ed2874a02e65188f5fea01c
Date 2018-11-02T21:50:52.634Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:
When I minimize the window, I can't scroll sideways in the chart tab. I can't change the type of chart or even see the whole chart. However, the results tab has a slide bar and displays the icons on the right side (Export to,..). 
I just found out that sometimes it is minimzed and I can see the whole picture after navigating between different tabs, but when I change the size of the window that can change. 

![image](https://user-images.githubusercontent.com/25180044/50520975-94a12500-0ac3-11e9-9db8-7da5b21bbede.png)

![image](https://user-images.githubusercontent.com/25180044/50520905-32482480-0ac3-11e9-992d-a02d242d8114.png)

**Comment by corivera** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/9306
