### ISSUE TITLE
Explain Tab beside the query results

### ISSUE THREAD

**Issue by MohamedSahbi** [microsoft/azuredatastudio#3652]
**Is your feature request related to a problem? Please describe.**
After clicking on Explain, the query result panel/tab disappears (with the chart tab) and Messages/Query Plan tab appears. There is no way to go back to the result tab and the created chart. 

**Describe the solution or feature you'd like**
What about displaying the Query plan tab with the Query result, or show the query plan in a pop-up window, or change the Explain button to toggle button that shows the Query plan when it is on and close it (and redisplay the hidden Query Result tab).

**Comment by anthonydresser** [comment]
The query plan and messages tabs are not tabs next to the results tab. So this should be resolved. Let me know if I'm missing something.
