### ISSUE TITLE
File File Import Wizard fails when column count is inconsistent

### ISSUE THREAD

**Issue by amtwo** [microsoft/azuredatastudio#3654]
Issue Type: <b>Bug</b>

1. Create a CSV file where the header row contains 5 columns of data, but the first 50+ rows have only 4 columns of data. At least one row at the end of the file should have all 5 columns fo data, matching the header. 
1. Use the Flat File Import Wizard to import the file. Notice on the Preview step that it samples the first 50 rows, and displays only 4 columns of data.
1. Execute the import, and it will end with the error "Error inserting data into table." with no additional details.

The import fails because the wizard is attempting to import only the 4 columns, and when it gets to the row with 5 columns, it fails. 

The wizard should at least be able to bubble up that the file has an inconsistent column count, so that I know the file is not properly formatted. Ideally, it would handle this gracefully, similar to the way the `Import-Csv` PowerShell cmdlet does, and successfully import the file, even with inconsistent column counts

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.59GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|50%|

</details>

**Comment by aasimkhan30** [comment]
The latest version works fine with such CSVs. Closing this issue for now.
