### ISSUE TITLE
Supporting Azure MySQL

### ISSUE THREAD

**Issue by datauduong** [Microsoft/azuredatastudio#3660]
Issue Type: <b>Feature Request</b>

Please making Azure Data Studio as Common Database Editor similar to Visual Studio Code.

Azure Data Studio version: azuredatastudio 1.3.7-insider (5a3087859918b1564d2622b95defa662facdbef6, 2018-12-07T02:33:40.014Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@datauduong thanks for opening this suggestion.  We're tracking this request with this issue https://github.com/Microsoft/azuredatastudio/issues/56.  Please add additional comments there is anything is missing.
