### ISSUE TITLE
Create External Table wizard does not support 500 columns

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#3663]
Issue Type: <b>Bug</b>

We have a customer who has a a view in sql server 2017 with 472 columns. Currently the UI shows only a subset of 67 columns.

We need this fixed.

![image](https://user-images.githubusercontent.com/22312581/50609984-376fef80-0e86-11e9-9f67-b3765e630f5e.png)

Azure Data Studio version: azuredatastudio 1.3.7-insider (5adcabc8dea4232bca4a46da445fbfc4b85703f3, 2018-12-08T02:30:52.580Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (22.23GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by geleems** [comment]
I could not reproduce the issue. It showed more than 500 column definitions without the issue in my trial. Can you try again in latest bits?

**Comment by geleems** [comment]
cannot repro.
