### ISSUE TITLE
Can you adjust the default run minimum SQL statement like Datagrip

### ISSUE THREAD

**Issue by sunmicosun** [Microsoft/azuredatastudio#3664]
- Azure Data Studio Version:

Steps to Reproduce:

能不能像datagrip一样可以调整默认运行最小的sql语句，不是全部，而且有delete这种危险操作没有加where语句时可以提示是否执行

**Comment by alanrenmsft** [comment]
what do you mean by "shortest sql statement"? ADS will only run the selected statement by default.

**Comment by alanrenmsft** [comment]
@sunmicosun

**Comment by sunmicosun** [comment]
I'm sorry, I find it, just press ctrl + F5
thank you！






在 2019-01-04 10:29:01，"sunmico" <sunmico@163.com> 写道：

I'd like to say this.
just like datagrip 





在 2019-01-04 02:21:26，"Alan Ren" <notifications@github.com> 写道：


what do you mean by "shortest sql statement"? ADS will only run the selected statement by default.

**Comment by kburtram** [comment]
..switching issue title to English based on Google translate so the issue can be triage.  Please correct the title if the translation is incorrect.

**Comment by kburtram** [comment]
Closing based on previous issue discussion.  Please let me know if there is still an issue that needs to be tracked here.
