### ISSUE TITLE
Notebooks are not supporting input from the users

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#3668]
Issue Type: <b>Bug</b>

We need an ability where users can provide input within the Notebooks.

![image](https://user-images.githubusercontent.com/22312581/50668614-ef7bc600-0f74-11e9-859d-755f9470160c.png)

sno=input('Enter SSN')
name=input('Enter Name')
print('Details are',sno,name)

This code works fine in python but not in our notebooks.

Azure Data Studio version: azuredatastudio 1.3.7-insider (5adcabc8dea4232bca4a46da445fbfc4b85703f3, 2018-12-08T02:30:52.580Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (18.16GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kevcunnane** [comment]
Fixed in latest Insiders
