### ISSUE TITLE
Simplified Azure Sign-In

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#3669]
**Is your feature request related to a problem? Please describe.**
Users have been confused when logging into Azure with the Device Login method where they have to copy and paste a device code. We should make this a simpler process.

**Describe the solution or feature you'd like**
VS Code's Azure Account extension has recently implemented a simplified login with the following flow:

1. Click Sign In to Azure
2. Browser pops up with Microsoft login
3. User selects their login
4. Confirmation screen of successful login

https://twitter.com/christof_marti/status/1081108329664073728 

This should remove friction as people test Azure subscriptions.

**Comment by kburtram** [comment]
Here are some notes from the Azure Identity regarding a problem they investigated with our current Device Login implementation.

> "The device code flow that's currently being used was meant for headless/IoT devices or other similar cases where user IO is severely constrained. It was never meant for general purpose app login. There are constraints on the protocol used in the device code flow that make certain scenarios not possible.
 
> In this specific case, the protocol is limiting because there is no logical "Device" entity associated with the auth request. "Device" entities encapsulate some device properties -- things like whether it's domain joined or configured for an MDM solution in corporate environments.
 
> In comes "AAD Conditional Access" which is a very popular mechanism used to author policies of where auth tokens are allowed to go for security purposes. A particularly popular policy that customers like to configure is "tokens can only be issued to domain joined devices". Since your app is behaving like a remote device, there's no logical device information and thus that policy can't be satisfied -> sign-in is blocked. Caterpillar hit that issue this week and was wondering why this doesn't work.
 
> Moving to a more standard auth stack for apps (like it looks VS code did) fixes that kind of case because the underlying AAD SDKs handles things like satisfying device constraints under the hood."

**Comment by kburtram** [comment]
This has been fixed in Feb release.
