### ISSUE TITLE
cannot connect / missing dependency in rpm file: mssql-tools unixODBC-devel

### ISSUE THREAD

**Issue by brassh** [microsoft/azuredatastudio#3671]
Issue Type: <b>Bug</b>

Steps to reproduce:
- install azure data studio rpm file (from https://github.com/Microsoft/azuredatastudio/releases/download/1.3.6/azuredatastudio-linux-1.3.6.rpm) to fresh rpm based linux system (I used openSUSE Leap 15.0)
- start program and setup new connection
- hit "connect button"

Result:
- does not connect, wheel keeps spinning forever, no error message

Reason:
- azure data studio needs mssql-tools and msodbcsql packages to connect
- but these packages are not installed automatically due to missing mssql-tools and msodbcsql dependencies in rpm file

Proposed Fix:
- add dependencies for mssql-tools and msodbcsql packages in the rpm-file (possibly to be added to file resources/linux/rpm/dependencies.json)
- and/or add the necessary steps for manual installation of the mssql-tools package to the documentation/website

Workaround for now: 
- manual installation of missing packages 
- see https://docs.microsoft.com/de-de/sql/linux/sql-server-linux-setup-tools

Azure Data Studio version: azuredatastudio 1.3.6-insider (efd809971ff50befee6535315f19c495af46c71a, 2018-12-04T01:04:27.077Z)
OS version: Linux x64 4.12.14-lp150.12.28-default

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|31.37GB (0.82GB free)|
|Process Argv|/usr/share/azuredatastudio/azuredatastudio|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.5.0

</details>

**Comment by alvinlohtpgit** [comment]
Thanks! Was getting a "Starting Service" status message and the connection icon kept spinning without being able to connect. Installing the mssql-tools in the linked page solved the issue. Am on Fedora 29.

**Comment by camckay** [comment]
Thanks for the workaround! Can confirm it works on openSuse Tumbleweed. Hopefully this bug gets fixed soon.

**Comment by camckay** [comment]
The missing dependency in OpenSUSE Tumbleweed is libopenssl1_0_0. I verified that once this package is installed, Azure Data Studio works as expected.

**Comment by kburtram** [comment]
@camckay I'll update the rpm file.

**Comment by camckay** [comment]
Same issue on Fedora as previously noted. The missing dependency there is compat-openssl10.

**Comment by kburtram** [comment]
I'm not seeing any missing dependency errors installing the RPM on current OS distros.  Please let me know if this issue is still impacting you.
