### ISSUE TITLE
Query plan fails or throws errors for certain queries

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3672]
Issue Type: <b>Bug</b>

1. Open a query tab and write the query `select top 1000 * from sys.all_columns`
2. Hit 'explain'

Actual behavior: The query plan shows up but an error message is displayed in the bottom right (one time the query plan didn't even show up)
Expected behavior: The query plan shows up with no errors

Error message:
```
Something went wrong getting more rows: Error: Start row cannot be less than 0 or greater than the number of rows in the result set
Parameter name: startRow
```

This happens regardless of what the streaming feature flag is set to, though I expect it's related. Simpler query plans work fine

Azure Data Studio version: Azure Data Studio 1.4.1-insider (47c4609f233b4ee722bfb5e61524b0ee913b2a05, 2019-01-07T03:09:53.352Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.34GB free)|
|Process Argv|/private/var/folders/0s/fr5b1xsn1zs7mr3127xy_5l80000gn/T/AppTranslocation/DAC0FDDF-9BAF-4D8E-B15D-0EBE633328EF/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by kburtram** [comment]
The error message has ben disabled in master.  Let's open issues for any user facing side-effects that are observed.
