### ISSUE TITLE
Running edit data on a table with lots of columns shows two tables

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3677]
Issue Type: <b>Bug</b>

1. Create a table that has 500 columns
2. Open it in edit data

Actual behavior: The table is shown twice
Expected behavior: The table should be shown once

![Edit data tab for a table with 500 columns. The table is shown twice in the tab](https://user-images.githubusercontent.com/3758704/50796529-c154f980-1286-11e9-8745-dffb7f442999.png)

Azure Data Studio version: Azure Data Studio 1.4.1-insider (47c4609f233b4ee722bfb5e61524b0ee913b2a05, 2019-01-07T03:09:53.352Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 4, 4|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|/Users/mairvine/Documents/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Diagonir** [comment]
This problem also happens to me, albeit not in a consistent manner. Running the same query sometimes returns one results-grid and other times two 
<pre>Version 1.3.8
Commit 84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1
Date 2019-01-08T23:59:38.228Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64</pre>

**Comment by MattIrv** [comment]
This was due to the duplicate result sets bug and fixed in #3620. Verified it no longer repros as of 1.4.5
