### ISSUE TITLE
Moving edit data to the bottom of the window breaks all tabs

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#3678]
Issue Type: <b>Bug</b>

1. Open some query tabs
2. Open edit data
3. Move the edit data tab to the bottom of the window grid

Actual behavior: Tab display breaks completely and you have to restart Azure Data Studio
Expected behavior: Edit data appears in the right place

![screen shot 2019-01-07 at 2 30 46 pm](https://user-images.githubusercontent.com/3758704/50797248-01b57700-1289-11e9-943e-d07a8ff18cf6.png)

Azure Data Studio version: Azure Data Studio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:36:55.143Z)
OS version: Darwin x64 18.2.0

**Comment by kburtram** [comment]
This appears to be fixed on the current build.  Please let us know if you're still impacted by this issue.
