### ISSUE TITLE
Notebooks: Separate ContentManager from NotebookManager

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#3685]
Now that it's possible to have multiple NotebookManagers (e.g. with SQL and Jupyter, for example), this now means that there are multiple (local) ContentManagers. We really should have a local ContentManager that's separate from the NotebookManager.

**Comment by kevcunnane** [comment]
While Jupyter implementation was removed still define it in sqlops.proposed. Need to delete / solve refactoring.
