### ISSUE TITLE
Results pane displayed 2 copies of the result set.

### ISSUE THREAD

**Issue by burtonrodman** [Microsoft/azuredatastudio#3695]
Issue Type: <b>Bug</b>

Steps:
1.  right-click on database and choose New Query
2.  execute select * from table1 where somefield = 'value'
3.  edit and execute select t2.* from table2 t2 join table1 t1 on t1.id = t2.Table1ID
where t1.somefield = 'value'

at this point, the results pane displays 2 exact copies of the result set of the second query.

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.85GB (6.82GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by burtonrodman** [comment]
![image](https://user-images.githubusercontent.com/7658657/50927862-0748c380-1427-11e9-9494-11e5e2d0a6b4.png)

**Comment by burtonrodman** [comment]
notice also, nothing displays in Messages pane.  this has been happening randomly today.

**Comment by kburtram** [comment]
@burtonrodman this was a regression related to the new query results streaming feature that we're previewing this month.  It's a timing related issue with how the results set is rendered.  The query is only executed once, so the bug only impacts the UI.  We've typically seen it when Execute is run multiple times quickly, though sometime it can occur from a single execute command.

@anthonydresser @ranasaria do we have a fix for this issue yet?  We should consider taking the fix in a hotfix release.

**Comment by anthonydresser** [comment]
https://github.com/Microsoft/azuredatastudio/pull/3620

**Comment by kburtram** [comment]
@anthonydresser thanks, any idea why we didn't include the PR in the Jan release?

**Comment by kburtram** [comment]
Closing as Fixed based on #3620.  The commit will be in the hotfix release planned for this week.

**Comment by kburtram** [comment]
@anthonydresser I still occasionally see duplicate resultsets even with #3620 merged.  Though it is occurring less frequently.  Could you please take a look to see what's going on?

Here is an example from the Jan Hotfix build.
![image](https://user-images.githubusercontent.com/599935/51212123-706b8380-18cc-11e9-91aa-4ff13808d72e.png)

**Comment by anthonydresser** [comment]
It's related to #763, once we get that in all instances of multiple results sets that I know about should be fixed

**Comment by kburtram** [comment]
@anthonydresser OK, I update the SQL Tools Service with PR #3748.  We can try your previous change for tomorrow's release and see if Microsoft/sqltoolsservice#763 resolves the issue in master.  Thanks!
