### ISSUE TITLE
Check for updates doesn't appear to work

### ISSUE THREAD

**Issue by kevchant** [microsoft/azuredatastudio#3701]
Issue Type: <b>Bug</b>

All

I'm trying to update from 1.2.4 to 1.3.8 today using the 'Check for updates' feature within the app, however I'm being told there's no updates available.

I'm running Azure Data Studio 1.2.4 on CentOS  7, which is exactly same binaries as Red Hat 7.

On a side note, are you guys going to look to put in support to update via yum in the future?

Regards

Kevin Chant

Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd0235690ad044ed2874a02e65188f5fea01c, 2018-11-02T21:38:48.126Z)
OS version: Linux x64 3.10.0-957.1.3.el7.x86_64

**Comment by kburtram** [comment]
@kevchant we still need to hook up auto-updates for Linux.  We plan to do this with the next couple releases.  To publish bits to the MS rum repo is a bit of a manual process, so we haven't set that up yet.

**Comment by kburtram** [comment]
This should be working now on Linux.  We have a different issue to tracking adding DEB and RPM to public repos.  Thanks for reporting!
