### ISSUE TITLE
Results view tooltip isn't showing correct values

### ISSUE THREAD

**Issue by CoolDadTx** [Microsoft/azuredatastudio#3704]
Issue Type: <b>Bug</b>

The Results view of a query is not showing the correct value when hovering over string columns in all cases. In our case we have VARCHAR columns that store JSON objects. When hovering over the values they get truncated. For example the following value prints {
{"abc":123}
![tooltip_wrong](https://user-images.githubusercontent.com/3778674/50976974-dca64b80-14b6-11e9-8d0c-fa831b0e8405.PNG)

It seems like the tooltip is stopping at the first double quote.

But we see this issue in other cases as well. For example we store exception information in a column in our error logs. Given this we also see just a {

{  "Message": "Value cannot be null.\r\nParameter name: key",  "Type": "System.ArgumentNullException",  "StackTrace": [    {      "Function": "System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)",      "FrameIndex": 0    },    {      "Function": "System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)",      "FrameIndex": 2    }, 

But this particular example is even worse because what you see in the result view itself (not the tooltip) is the middle part of this very long string. So the above string starts with { " but the result row itself starts about halfway through the string. 

![resultview](https://user-images.githubusercontent.com/3778674/50976971-dca64b80-14b6-11e9-921a-e6132dd8499a.PNG)
![startofvalue](https://user-images.githubusercontent.com/3778674/50976973-dca64b80-14b6-11e9-8cf9-e1353c87dff8.PNG)

Yet another string column in the same row which shows similarly long strings (but no double quotes) correctly starts at the front of the value.

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (9.73GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@CoolDadTx I wasn't able to repro on the latest build from master.  Though I don't recall any fixes in this area.   Please let us know if you still see this on the latest insiders build or the Feb stable build planned for next week.

![image](https://user-images.githubusercontent.com/599935/52383966-571fa800-2a30-11e9-86fb-45bdcdc8e046.png)

**Comment by CoolDadTx** [comment]
I'm running 1.3.9 now and I haven't seen the issue. I'll consider this closed for now. Thanks.
