### ISSUE TITLE
Clear List button and text

### ISSUE THREAD

**Issue by trendoid** [Microsoft/azuredatastudio#3706]
Issue Type: <b>Bug</b>

after recent upgrade the recent connections list has text over the clear list button

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_softwar
![clear-list](https://user-images.githubusercontent.com/7746539/50987438-a75e2580-14d7-11e9-8a57-4c759168914b.jpg)
e<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (6.80GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.0
import|Mic|0.4.0
profiler|Mic|0.3.0
server-report|Mic|0.1.3
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by trendoid** [comment]
![clear-list](https://user-images.githubusercontent.com/7746539/50987488-c3fa5d80-14d7-11e9-8e97-37586df8fcd6.jpg)

**Comment by alanrenmsft** [comment]
@trendoid Could you please provide repro steps?

**Comment by kburtram** [comment]
@alanrenmsft this repro on dark and HC themes.  I've send a proposed fix in PR https://github.com/Microsoft/azuredatastudio/pull/3721.
