### ISSUE TITLE
Disconnected servers are shown as connected

### ISSUE THREAD

**Issue by smereczynski** [microsoft/azuredatastudio#371]
- SQL Operations Studio Version: 0.24.1

Steps to Reproduce:

1. Create connection (for me it is a SQL 2017 on Linux in Docker on Mac)
2. Connect
3. Shut down the server
4. Nothing happened - connection seems to be active
5. Open "databases"
6. After some time popup with an information that server is unavailable shows
7. Click OK
8. Server is still as active on the list (green dot)

![2017-12-19_21-59-03](https://user-images.githubusercontent.com/705653/34178683-558145ee-e508-11e7-956c-70c9ab52cb9c.png)

![2017-12-19_21-59-33](https://user-images.githubusercontent.com/705653/34178688-5a5b5640-e508-11e7-89df-3369a2c52d6a.png)

**Comment by Charles-Gagnon** [comment]
I'm closing this since there hasn't been any activity in a long time. If you still see issues here let us know.
