### ISSUE TITLE
SQL ActionBar: Pull() Method Is Broken

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#3713]
While working on the notebook toolbar, I noticed that the pull() method in src/sql/base/browser/ui/taskbar/actionbar.ts has the following definition:
`

    public pull(index: number): void {
		if (index >= 0 && index < this._items.length) {
			this._items.splice(index, 1);
			this._actionsList.removeChild(this._actionsList.childNodes[index]);
		}
	}

`

Unfortunately, this implementation doesn't quite work because this._items only keeps tracks of actions that are added to the actionBar, where this._actionsList keeps track of not only actions but also HTMLElements. Therefore, if there are any HTMLElements in the ActionBar, the index in the 2 arrays will not point at the same element in the ActionBar.

I'm not familiar enough with this code to get a nice, clean fix. It wasn't intuitive that the underlying arrays could be of different lengths before I dug into this.

More than happy to work with anyone on this.

**Comment by chlafreniere** [comment]
Note: this means that anyone who uses the ActionBar cannot dynamically remove items if there are both actions and dropdowns. It's completely broken.

**Comment by kburtram** [comment]
@chlafreniere could you please explain a bit more about what customer experience is broken by this?  It sounds like you can't remove a button from the Notebook toolbar if I'm reading the issue correctly.

**Comment by chlafreniere** [comment]
@kburtram Correct, cannot remove actions from the toolbar reliably when an action has a greater index than an HTMLElement/dropdown.

If there are dropdowns and actions in the same toolbar, calling pull() can end up removing an item different than the desired item, since _items and _actionsList don't represent the same data (one only keeps track of actions, the other keeps track of actions + dropdowns), even though we're trying to remove items using the same index.

**Comment by kburtram** [comment]
@chlafreniere is this issue still impacting your scenario?  or can it be closed now?

**Comment by chlafreniere** [comment]
Can close it. Thanks for the reminder.
