### ISSUE TITLE
HTML query result messed up

### ISSUE THREAD

**Issue by erymuzuan** [Microsoft/azuredatastudio#3714]
Issue Type: <b>Bug</b>

When query result contains valid HTML text, the result pane displayed rendered HTML instead of the raw HTML text

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E31225 @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.96GB (4.49GB free)|
|Process Argv|D:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
Here's an example repro for this regression.

```SQL
select '<div style="background-color: red">test</div>'  -- OK
select '<div style="">txt</div> <div style="background-color: red">test</div>'  
```

![image](https://user-images.githubusercontent.com/599935/51057279-ff5d6080-1599-11e9-8917-93dbc5281a69.png)

**Comment by kburtram** [comment]
@anthonydresser any ideas on this one?  We should try to include a fix in the Hotfix release next week if possible.

**Comment by anthonydresser** [comment]
No clue why this keeps coming back, we should probably just modify slickgrid to handle it in there

**Comment by kburtram** [comment]
@anthonydresser thanks, could you please take a look at a fix?  I think this creates an XSS problem so we should repair ASAP.

**Comment by kburtram** [comment]
Closing as Fixed based on https://github.com/Microsoft/azuredatastudio/pull/3722.  The commit will be in the hotfix release planned for this week.
