### ISSUE TITLE
How to assign session "program_name"?

### ISSUE THREAD

**Issue by kkbruce** [microsoft/azuredatastudio#3716]
Issue Type: <b>Feature Request</b>

How assign seesion "program_name" by Azure Data Studio?

Like `sys.dm_exec_sessions` information, we need change it from Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.3.7-insider (5a3087859918b1564d2622b95defa662facdbef6, 2018-12-07T02:33:40.014Z)
OS version: Windows_NT x64 10.0.17134

**Comment by cheenamalhotra** [comment]
This is similar to #3991 , closing as duplicate.
