### ISSUE TITLE
Eating a lot of memory ram

### ISSUE THREAD

**Issue by zilverjk** [microsoft/azuredatastudio#3717]
I've been testing with a simple task like doing an Stored Procedure or checking some tables, I got a few open tabs and in some times the app rise up to almost the limit of my physical ram, this is unacceptable, please verify this, I don't want to go back to SSMS.

Note: I've checked this in 2 different systems with different hardware, both running Windows 10 Pro 64Bit with 12 GB and 16 GB respectively.

**Comment by zilverjk** [comment]
![image](https://user-images.githubusercontent.com/7515854/51042327-ffedfb00-1589-11e9-8b71-079ec7140b2a.png)

**Comment by kburtram** [comment]
@zilverjk we have seen excessive memory consumption in some scenarios (~1GB), but I haven't seen ADS consuming 8GB before under "normal usage".  

Could you please confirm the product version you're using?  1.3.8?
Is there anything noteworthy about your use case that may help repo this issue?

**Comment by zilverjk** [comment]
This is something I can't confirm but I think the reason of this is when I execute the app as Administrator. I was having the same issue with SSMS with an excessive memory consumption. Now without the admin, SSMS is running smooth. I'll confirm if this is the same problem with ADS.

**Comment by kburtram** [comment]
@ranasaria have you seen anything like this in our stress tests?  I can't think of any use case where I'd anticipate this level of memory consumption.

**Comment by ranasaria** [comment]
@zilverjk, how many tabs do you have? Does your tabs have actively long running queries?

**Comment by zilverjk** [comment]
@ranasaria simple task like building a stored procedure and bunch of select 3 - 5 tabs. but as I said simple things

**Comment by ranasaria** [comment]
The only scenario in which we have observed large memory usage is when the editor is running queries that return large amount of results. This is bewildering.

@zilverjk, would it be possible for you to share a memory snapshot of Azure Data Studio? To get a memory snapshot, go to:

Help -> Toggle Developer Tools (Ctrl + Shift + I) -> Memory Tab -> Profiles – Take Snapshot Radio button selected -> Press ‘Take Snapshot’ button

Once snapshot has been taken it will show in left pane under HEAP SNAPSHOTS. Right next to the snapshot name (Snapshot 1) there will be a Save button. Click on that button to save the snapshot to a file and share that file if possible using a web-drive like one-drive.



-  Arvind.

________________________________

**Comment by zilverjk** [comment]
@ranasaria Here is the requested. Also Im having trouble with the UI where the tabs and the query editor are gone and I have to reload the app for they can reapear again, I'm supplying this as well in the zip.

![ui](https://user-images.githubusercontent.com/7515854/51126078-3af16800-17f0-11e9-903a-b56d2d736966.jpg)

[ADS_bugs.zip](https://github.com/Microsoft/azuredatastudio/files/2756066/ADS_bugs.zip)

**Comment by kburtram** [comment]
@zilverjk could you please show the break down of memory usage for the Azure Data Studio child processes?  i.e., expand the Azure Data Studio node in the Task Manager screenshot above.  

I didn't see unusually memory consumption in the ADS heap snapshot you provided, so I think the memory should be consumed by one of the other child processes.

**Comment by MattIrv** [comment]
This may be the same issue we've seen in the VS Code MSSQL extension: https://github.com/Microsoft/vscode-mssql/issues/1028

Does it only happen when you have a specific query file open?

**Comment by ranasaria** [comment]
@zilverjk - could you expand the Azure Data Studio (13) process in Task Manager and share the snapshot specifically interested in seeing which child process is consuming the memory.

**Comment by zilverjk** [comment]
@ranasaria This is with the last version 1.4.5

![image](https://user-images.githubusercontent.com/7515854/53126844-0b402900-352f-11e9-9d55-50e55b23367c.png)

**Comment by ranasaria** [comment]
Thank you zilverjk!.  This is helpful. Already the below shows that the main consumption is in ‘MicrosoftSqlToolsServiceLayer’ process so now we will be able to focus our effort there. I will write later on best way to drill further into that. But for starters follow the instructions at: https://github.com/Microsoft/azuredatastudio/wiki/How-to-turn-on-Backend-Logging  and share the log from the ‘MicrosoftSqlToolsServiceLayer’.

Also, can you capture the same information as below but from the details view of the task manager with ‘Command Line’, Peak working set and active working set column expanded and broad enough to capture sufficient details. This will help shine light further and help narrow down which of. Be sure to capture these for all the processes that you have below. In particular capture all ‘azure data studio’ processes and *SqlTools* processes. Sorting by commandline is likely to bring these processes near each other to capture in a single screenshot. Here is an example from my machine:
[cid:image001.png@01D4C92E.BE6BEE50]

**Comment by cheenamalhotra** [comment]
Checking in if this is still reproducible and could we get some logging/memory dumps for MicrosoftSqlToolsServiceLayer.exe if possible? It seems related with database metadata that is loaded by language service. I could not reproduce this in a database containing 10k tables or a server containing 10k databases.

Has anyone tried disabling intellisense?

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/f7442f93-794d-40ef-ad4b-715a87c0ebd4" width=500 />

**Comment by cheenamalhotra** [comment]
Closing as inactive.
