### ISSUE TITLE
No language packages

### ISSUE THREAD

**Issue by mysmlz** [microsoft/azuredatastudio#3727]
Issue Type: <b>Feature Request</b>

There are only a few plug-ins in the marketplace and no language packages.

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Varorbc** [comment]
@kburtram The localization language is mentioned in the [release log](https://github.com/Microsoft/azuredatastudio/releases/tag/0.29.3), but how do I set up a localized language? I don't seem to find it.

**Comment by kburtram** [comment]
@Varorbc we're planing to publish langpacks with the May release.  Our localization support broke when VS Code moved from embedded resources to separate langpack extensions.

**Comment by kburtram** [comment]
There are lang packs available in the insiders build Extension Manager gallery, and they will be published to the stable gallery with the July release this week.  We'll continue to improve the localization quality of the next couple months.  Therefore I'll close this issue now.
