### ISSUE TITLE
unable to access devicelogin page

### ISSUE THREAD

**Issue by Adikota** [Microsoft/azuredatastudio#3732]
trying to sign into Azure account in Azure Data Studio and unable to connect to microsoft.com/devicelogin page.

- Azure Data Studio Version: 1.3.8

**Comment by kburtram** [comment]
@Adikota are you getting any particular error?  I've seen that some users have needed to type https://microsoft.com/devicelogin into the web browser to get the page to load, but I am not sure why.

**Comment by Adikota** [comment]
My request just times out

**Comment by kburtram** [comment]
Closing as "no repro".  Please let me know if the issue persists.
