### ISSUE TITLE
Last column in result is blank / rendered improperly

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#3733]
![repro](https://user-images.githubusercontent.com/10999577/51141443-1ef4c300-17fe-11e9-8f60-b0c46b9d4be0.png)
Issue Type: <b>Bug</b>

Ran query that returns 3 columns. However, the result displayed as shown. SSMS renders the results fine.
![repro](https://user-images.githubusercontent.com/10999577/51141627-a5110980-17fe-11e9-9ebd-1f6fa9f2fe1c.png)

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.18312

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.85GB (16.03GB free)|
|Process Argv|C:\SQL\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.1

</details>

**Comment by kburtram** [comment]
@uc-msft do you know if this is happening consistently?  or was this a "1-off" rendering issue?  Is it only impacting this one table or all queries?  Thanks!

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if this issue is impacting you on current builds.
