### ISSUE TITLE
Notebook cells are shown empty some times even when there is content

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#3734]
![repro](https://user-images.githubusercontent.com/10999577/51141879-3da78980-17ff-11e9-986e-73e9235fcab4.png)
Issue Type: <b>Bug</b>

See picture. It is unclear how to repro this issue. I had a notebook & multiple SQL windows open. After I do something in the SQL window and come back the notebook cells are empty. It seems if you give it few minutes then it shows some content.

Azure Data Studio version: azuredatastudio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:59:38.228Z)
OS version: Windows_NT x64 10.0.18312

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|31.85GB (16.11GB free)|
|Process Argv|C:\SQL\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.1

</details>

**Comment by kevcunnane** [comment]
Thanks UC. This is an issue we need to address for the Feb release, I saw it and had a separate issue tracking it. So far it seems to happen when re-rendering a Notebook after switching tabs but we need more investigation into it. A workaround is to save, close & reopen the notebook but I understand this isn't ideal.

**Comment by vickyharp** [comment]
Can repro again in 1.5.0 
![cell contents disappearing](https://user-images.githubusercontent.com/8250560/53211608-a51ed900-35f6-11e9-9f66-1dac3c17b1d8.gif)

**Comment by kevcunnane** [comment]
@rajmusuku can you quickly look at this?
