### ISSUE TITLE
Row Count not updated

### ISSUE THREAD

**Issue by luismiguelgilbert** [Microsoft/azuredatastudio#3737]
Issue Type: <b>Bug</b>

When you run a SELECT query  from a table, rowCount shows the results.
If  you run a differente SELECT query, rowCount doesn't update, but if user switch to other tab and return, then the rowCount is updated

![image](https://user-images.githubusercontent.com/20174916/51143032-84a37800-181b-11e9-875a-5f52e26239c8.png)

SQL Operations Studio version: sqlops 0.33.0 (deee2d8aa98bdeb549a72760c55fa6e53a353a81, 2018-12-11T00:29:11.751Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.70GB (8.47GB free)|
|Process Argv|C:\Program Files\SQL Operations Studio\sqlops.exe|
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.5.1
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
@luismiguelgilbert I think this issue should be fixed in the latest Azure Data Studio releases.

We are longer producing updates for SQL Operations Studio since we've rebranded the product.  Please manually uninstall SQL Ops Studio Preview and install Azure Data Studio from https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017 to upgrade.  Sorry for any inconvenience.

**Comment by luismiguelgilbert** [comment]
Yes, you are right…

 

I was still using SQL Operations… Today, I received un update for SQL Operations, and then I reeived a second update notification for Azure Data Studio…

Azure Data Studio is working as expected…

 

Thanks!

 

De: Karl Burtram <notifications@github.com> 
Enviado el: lunes, 14 de enero de 2019 16:51
Para: Microsoft/azuredatastudio <azuredatastudio@noreply.github.com>
CC: luismiguelgilbert <luismiguelgilbert@gmail.com>; Mention <mention@noreply.github.com>
Asunto: Re: [Microsoft/azuredatastudio] Row Count not updated (#3737)

 

@luismiguelgilbert <https://github.com/luismiguelgilbert>  I think this issue should be fixed in the latest Azure Data Studio releases.

We are longer producing updates for SQL Operations Studio since we've rebranded the product. Please manually uninstall SQL Ops Studio Preview and install Azure Data Studio from https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017 to upgrade. Sorry for any inconvenience.

**Comment by kburtram** [comment]
@luismiguelgilbert thanks for confirming, I'll close the issue then. 

Unfortunately, the SQL Ops to Azure Data Studio upgrade was a bit more complicated then we hoped since Windows depends on the product name in so many places we couldn't really get a clean auto-update experience.
