### ISSUE TITLE
+ button to add new cell in notebook

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#3742]
**Is your feature request related to a problem? Please describe.**
Extra clicks

**Describe the solution or feature you'd like**
Would like there to be a plus button to add a new cell. Right now, I have to right click and click again. It seems like not a big deal but it is annoying. I'd also love the ability to drag cells up or down (i.e. move a cell's location)

**Comment by kevcunnane** [comment]
@chlafreniere I believe you have work-in-progress code we can pick up for this. Let's try to prioritize in this sprint if we have bandwidth
