### ISSUE TITLE
support for SQL Server Machine Learning Services

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#3743]
**Is your feature request related to a problem? Please describe.**
By default, Notebooks run Python 3.6, but SQL MLS uses Python 3.5 and a very specific location to open. So you can't run revoscalepy in ADS

**Describe the solution or feature you'd like**
It's be nice if there was an easy way to connect and use revoscale py from within ADS

**Describe alternatives you've considered**
I just have to open Jupyter locally now.

**Comment by kevcunnane** [comment]
@rajmusuku / @corivera this is related to the work to add a setting pointing to a Python install and support getting required dependencies for Jupyter server running on that. Please track and assign to a target milestone, thanks!
