### ISSUE TITLE
Autosave ability for Notebooks

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#3744]
**Is your feature request related to a problem? Please describe.**
autosave isn't enabled, and if I accidentally close ADS or open a new folder, all my changes are lost, there's not even a toast message

**Describe the solution or feature you'd like**
Would like to be able to toggle autosave for my notebooks

**Comment by kevcunnane** [comment]
Would you be OK with this being tied to the `files.autosave` setting in Azure Data Studio? See snippet below. Once we implement true save support (including the Ctrl+S support you commented on) this should happen "for free". 

```json
 // Controls auto save of dirty files. Read more about autosave [here](https://code.visualstudio.com/docs/editor/codebasics#_save-auto-save).
  //  - off: A dirty file is never automatically saved.
  //  - afterDelay: A dirty file is automatically saved after the configured `files.autoSaveDelay`.
  //  - onFocusChange: A dirty file is automatically saved when the editor loses focus.
  //  - onWindowChange: A dirty file is automatically saved when the window loses focus.
  "files.autoSave": "off",

  // Controls the delay in ms after which a dirty file is saved automatically. Only applies when `files.autoSave` is set to `afterDelay`.
  "files.autoSaveDelay": 1000

```
