### ISSUE TITLE
after query all sections of azure data studio ui get messed up

### ISSUE THREAD

**Issue by vicana8635** [microsoft/azuredatastudio#3745]
Issue Type: <b>Bug</b>

run query

Azure Data Studio version: Azure Data Studio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:48:43.514Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 2|
|Memory (System)|32.00GB (8.34GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@vicana8635 could you please provide some additional details on the repro steps and the observed behavior?  I am not able to repro the issue as described.  Thanks!

**Comment by vicana8635** [comment]
the problem is that one of the fields returned in the query results has html in it and that messes up the UI
