### ISSUE TITLE
Inconsistent casing for Import extension context menus

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3747]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Install Import extension
2. Right-click database

Expected: Menus have consistent casing and possibly related commands should be in same group

Actual: Two different groups of menu items, each with only 1 item.  One says "Data-tier Application Wizard" other say "Import wizard".  Minimally, wizard should be cased the same.  It may also be good to put both items in same menu group.

![image](https://user-images.githubusercontent.com/599935/51209277-c0dee300-18c4-11e9-9f76-ccc1e6f39337.png)

**Comment by udeeshagautam** [comment]
@kisantia Can you please take a look as part of DacFx extension

**Comment by kisantia** [comment]
Fixed casing in #4115
