### ISSUE TITLE
Unable to delete connections

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3764]
- Azure Data Studio Version: 1.3.8

Steps to Reproduce:

1. I'm able to delete the "recent connections" but there's no way to remove saved connections from here

![image](https://user-images.githubusercontent.com/28786161/51333010-b857eb00-1a31-11e9-97ef-886a146a0e7d.png)

**Comment by kburtram** [comment]
@amthomas46 the Save Connections can be managed in the Servers viewlet.  They are displayed in the Connect Dialog as a convenience, but we currently certain operations in the viewlet.

![image](https://user-images.githubusercontent.com/599935/51338616-1f2fd100-1a3f-11e9-87ca-3d0c9b9c2429.png)
