### ISSUE TITLE
standard markdown support, e.g. > result in note

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3765]
**Is your feature request related to a problem? Please describe.**
I want to add notes within my markdown cells. Typically, you can do that in markdown using the ">" character and it will indent/grey-format it, but you can't do that currently

**Describe the solution or feature you'd like**
I want the above experience :-) 

**Describe alternatives you've considered**
Just pressing return a few times and typing "Note: note here", but it is not as pretty..

**Comment by kevcunnane** [comment]
@rajmusuku - stretch goal.

**Comment by kevcunnane** [comment]
@amthomas46 this should be in Insiders in the next day or so. Let me know if you see any Markdown issues after this - I think I caught them all but something may have slipped through the cracks

**Comment by amthomas46** [comment]
Thanks!
