### ISSUE TITLE
Azure Data Studio asks for Access to Photos, calendar

### ISSUE THREAD

**Issue by jdanton** [Microsoft/azuredatastudio#3766]
- Azure Data Studio Version: Version 1.4.1-insider (1.4.1-insider) Mac OS

Steps to Reproduce:

1.  New Install of Azure Data Studio (In this case replacement of existing file)
2. Select File > Open from menu
3. User is prompted to grant access to photos and calendar to ADS.

**Comment by kburtram** [comment]
@jdalton I could only repro this when I clicked on the "Photos" icon in the "Media" section of the open file dialog.  Are you getting these prompts when only browsing your file system?

**Comment by jdanton** [comment]
I was just trying to open a .sql file that was in downloads. Let me try it again.

**Comment by kburtram** [comment]
@jdalton thanks for confirming!  I'll keep any eye out for this.  We don't do anything regarding Photos or Calendar directly, but we have a lot of upstream dependencies (VS Code, Electron, Chromium, etc.) so it's possible something unexpected is happening.
