### ISSUE TITLE
why not support oracle?

### ISSUE THREAD

**Issue by github24518** [Microsoft/azuredatastudio#3773]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kburtram** [comment]
@github24518 thanks for the suggestion.  We're consolidating requests to support all non-SQL Server relational DB platforms into this issue https://github.com/Microsoft/azuredatastudio/issues/56.
