### ISSUE TITLE
Expand columns in SQL Server 2005 - unknown property IsColumnSet

### ISSUE THREAD

**Issue by mrrrk** [microsoft/azuredatastudio#3774]
Issue Type: <b>Bug</b>

1 - Connect to a database on instance of SQL Server 2005.

2 - Expand explorer tree down to "columns" level

Shows error dialogue with message, "unknown property IsColumnSet" when "Columns" is clicked and fails to expand.

:o)

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (4.85GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@mrrrk ADS currently only officially supports SQL Server 2014+, though we do try to support downlevel versions.  I think SQL Server 2008 R2 is the lowest version that pretty much works reliably.  

I'll take a look if this particular issue is something that is easy to avoid.  However, you'd likely run into several other issues working with a SQL Server 2005 instance.  Sorry for the inconvenience.

**Comment by mrrrk** [comment]
It's no biggie as we're retiring that server anyway - but I wondered if a message to say that support was missing rather than an exception dialogue would be appropriate :o)

**Comment by kburtram** [comment]
@mrrrk good point, perhaps the "fix" here is to add a better error message when working with unsupported server versions.

**Comment by sjmcallister** [comment]
I'm getting this same message on a SQL Server 2008 R2 server.  My expectation of the tool is that if the SQL server version is still officially supported by Microsoft, the tool should support it as well.

**Comment by kburtram** [comment]
Closing this issue since ADS doesn't support SQL Server 2005.  Thanks for reporting this bug.
