### ISSUE TITLE
Intellisense delayed

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#3778]
![gif](https://media.giphy.com/media/57UlHuxiBGGGmpNOTh/giphy.gif)

- Azure Data Studio Version: 1.3.9

Steps to Reproduce:

1. Download latest version of Azure Data Studio (1.3.9)
2. Connect to localhost SQL Server 2017
3. Open New Query Window
4. Type S
5. Intellisense has a clear delay

I have tried a fresh install and restarting computer, and refreshing intellisense cache. Computer is 16gb and 4 cores.

**Comment by anthonydresser** [comment]
We haven't made any changes in this area in a while that I know of. @kburtram is it possible that it was caused by https://github.com/Microsoft/sqltoolsservice/commit/0fd98df79b27a25a23dcc3dea98dd1999144661d

**Comment by yualan** [comment]
This was also repro-ed by @chlafreniere and appears to be affecting T-SQL notebooks. Thanks Anthony and Karl for investigating

**Comment by kburtram** [comment]
@anthonydresser this is not likely related to Microsoft/sqltoolsservice@0fd98df which bumps from a near-RTM preview of SqlClient to the RTM SqlClient.  IntelliSense is handled by SMO, SQL Parser, and logic in SQL Tools Service, so any minor changes in SqlClient between those two versions is unlikely to impact IntelliSense perf.  Most likely this is related to the issue we've always had populated the SMO MetadataProvider cache.

**Comment by vickyharp** [comment]
I'm experiencing this with snippet intellisense.

In this clip I am trying to use a snippet called vh_where. 

2.33 sec: I finish typing vh_ and pause to autofill
3.13 sec: red squiggles appear
5.75 sec: user snippet hint appears


![slow snippet intellisense](https://user-images.githubusercontent.com/8250560/51704056-e22e8600-1fcc-11e9-9f68-7cd2a91bc2d2.gif)

Here's another on a new query window that is entirely disconnected.

2.54 sec: I finish typing vh_where (the full snippet name)
5.67 sec: user snippet hint appears

![slow snippet intellisense disconnected](https://user-images.githubusercontent.com/8250560/51704309-916b5d00-1fcd-11e9-8719-52dee18116ce.gif)

This is vscode with the exact same sql.json user snippet file.

1.25 sec: I type v
1.29 sec: user snippet hint appears

![slow snippet intellisense vscode](https://user-images.githubusercontent.com/8250560/51704645-67ff0100-1fce-11e9-9f8e-901e281de5dc.gif)

**Comment by yualan** [comment]
We might need to do additional investigation on this issue since this is happening on Vicky's machine as well. I'll try the insider build

**Comment by kevcunnane** [comment]
This is a bug due to notebook support. Fixing and verifying now.

**Comment by yualan** [comment]
Thanks Kevin!
