### ISSUE TITLE
Cell errors cut off in Notebooks

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3779]
- Azure Data Studio Version: 1.3.9

Steps to Reproduce:

1. Run a cell with a long error. It doesn't Wrap like you would hope, e.g.
![image](https://user-images.githubusercontent.com/28786161/51417253-02c09100-1b32-11e9-98c2-a1f003c39488.png)

and there isn't a way that is obvious to scroll

**Comment by kevcunnane** [comment]
Rendering error

**Comment by kevcunnane** [comment]
@chlafreniere and @YurongHe maybe one of you can pick this up?

**Comment by chlafreniere** [comment]
I'll take it. I already took a cursory look.

**Comment by chlafreniere** [comment]
@amthomas46 do you have any sample T-SQL where this repros by any chance? I'll try to figure out one, but checking just in case 😃.

**Comment by chlafreniere** [comment]
> @amthomas46 do you have any sample T-SQL where this repros by any chance? I'll try to figure out one, but checking just in case 😃.

@amthomas46 I should've just tried this myself. Have a repro already. Sorry for the spam!

**Comment by chlafreniere** [comment]
Fixed by #5002.
