### ISSUE TITLE
Support querying log analytics/data explorer

### ISSUE THREAD

**Issue by simonsabin** [microsoft/azuredatastudio#3783]
It would be beneficial to be able to query all different data sources from Azure Data Studio. Thus being able to query Log Analytics/Data Explorer would be great.

This would provide more weight to Azure Data Studio being the tool for querying data in Azure and on premise.

https://feedback.azure.com/forums/267889-log-analytics/suggestions/36598216-integrate-log-analytics-with-data-studio-to-have-d
https://feedback.azure.com/forums/915733-azure-data-explorer/suggestions/36598138-have-an-desktop-client-that-allows-sharing-of-quer

**Comment by kburtram** [comment]
@simonsabin thanks for the suggestion.  This is certainly the direction we'd like to go with the project, though we don't have extensions for these two Azure services in-progress at this time.  I'll keep these services in mind as we discuss how to better integrate with Azure.

**Comment by kplantus** [comment]
+1 for being able to connect data studio directly to my Az Log Analytics Workspace and running/saving/managing my KQL queries locally.

**Comment by alanrenmsft** [comment]
we do have these extensions now, please give them a try.
![image](https://user-images.githubusercontent.com/13777222/204970245-0121958b-abb6-4fe9-91cf-b0aae4cf1794.png)

![image](https://user-images.githubusercontent.com/13777222/204970272-0c9c6a6f-1345-4ce8-aad9-a700c0741667.png)
