### ISSUE TITLE
Notebooks visualization improvements

### ISSUE THREAD

**Issue by rajmusuku** [microsoft/azuredatastudio#3784]
Work on visualization improvements by leveraging some features from Nteract. Below are some of the features to be implemented.

- [ ] Charts
- [x] Plotly
- [ ] Vega
- [ ] Vdom
- [ ] Support Prose team to improve Slick grid integration in Notebooks
- [x] Add an entry point to create a notebook from Fie menu (File -> New Notebook)
- [x] Notebook file save. (File -> Save)

**Comment by kevcunnane** [comment]
What about the following scenarios:
- Latex
- Javascript
- geojson
- JSON
- PDF

Have you looked at JupyterLab and also https://github.com/jupyterlab/jupyter-renderers for other scenarios? Which of these should we support?

What about the following additional visualization scenarios:
- Collapsible header sections: auto-detect markdown with 1-line `# Header` or `## Header` sections and make these into collapsible sections
- Support for input feedback prompt (request for StdIn) which isn't implemented yet

IPyWidgets
- What are the top N features / APIs we need to implement? E.g. clickable button with callback, grid, etc.?
 - Will we put this in a webview? If so which sqlops / notebook APIs would be available?

**Comment by kevcunnane** [comment]
Split StdIn support out into #5231 as I'm implementing this part.

**Comment by kevcunnane** [comment]
Plotly support added in https://github.com/microsoft/azuredatastudio/pull/6252. Will aim for Vega and VDOM if possible this sprint but it may be a bit close. After that will close and open separate issues for these separate renderers.

**Comment by kevcunnane** [comment]
Closing this out in favor of separate issues
