### ISSUE TITLE
Loading the first page in the Create External Table takes close to 5-10 secs

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3792]
Issue Type: <b>Bug</b>

When we load the Create External Table wizard it takes close to 5-10 secs to show the External Data Sources. This takes a long time specially during demo's. Why is taking so long from where is this information retrieved?

<img width="1197" alt="image" src="https://user-images.githubusercontent.com/22312581/51587971-8ac6e200-1f08-11e9-9492-5029e7a65c57.png">

Azure Data Studio version: Azure Data Studio 1.3.8 (84009f65ec6297d1cc16b1b2ec8f6fba9f5be2a1, 2019-01-08T23:48:43.514Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 3, 3|
|Memory (System)|16.00GB (0.45GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/2F220245-3E49-45A6-B21A-3AB65303A386/d/Azure Data Studio_January.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
gc-excelviewer|Gra|2.1.26
agent|Mic|0.35.2
import|Mic|0.5.0
sql-vnext|Mic|0.9.1

</details>

**Comment by geleems** [comment]
Since we uses direct query than then SMO for server information, this bug is fixed.

![loading fixed](https://user-images.githubusercontent.com/19577035/55192639-2b808a80-5162-11e9-81fd-888f17272cfe.gif)
