### ISSUE TITLE
SQL Kernel: Attach To Should Indicate Database as Well as Server

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3799]
When connecting with the SQL Kernel, the Attach To dropdown should indicate the database name. Perhaps:

FakeServer (fakedb)

**Comment by kevcunnane** [comment]
This is kinda related to the new toolbar work. For now, you can change by doing select connection, but we want a separate dropdown for it. Let's wait and do this right / wait for more customer feedback.

**Comment by chlafreniere** [comment]
This has been completed for March.
