### ISSUE TITLE
Chart Type values are not user friendly

### ISSUE THREAD

**Issue by martinisaksen** [microsoft/azuredatastudio#38]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. View Chart Type in list.

What I'd expect to see:
"Horizontal Bar" and similar naming for types.

What I see:
"horizontalBar" and other lowerCamelCase naming.

**Comment by smartguest** [comment]
I have implemented a preliminary fix that addresses this issue within the SelectBox class.
