### ISSUE TITLE
Tab coloring isn't retained after restart (sql.tabColorMode)

### ISSUE THREAD

**Issue by winzig** [Microsoft/azuredatastudio#3802]
Issue Type: <b>Bug</b>

1. Adjust user settings to define `"sql.tabColorMode": "fill"`
2. Open a new query tab and see it colored as expected.
3. Go to the app menu and select Quit (on macOS)
4. Restart the app, the tabs come back, but they're not colored.

Azure Data Studio version: Azure Data Studio 1.4.2-insider (637dc9b9b2d13c5161d4e31467585091d17adf69, 2019-01-18T17:58:19.614Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7920HQ CPU @ 3.10GHz (8 x 3100)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.2.1

</details>

**Comment by winzig** [comment]
Further testing shows that this is because when it restarts, it has not reconnected the tabs to the servers they were originally connected to. So I guess my question is: how can I have tabs reconnect to the SQL Server upon startup? I've got two saved connections in datasource.connections, but I guess right now this info is not being saved with the open tabs?

**Comment by kburtram** [comment]
@winzig thanks for reporting and clarifying the issue!  We're tracking reconnecting editors on restart with issue https://github.com/Microsoft/azuredatastudio/issues/1979.  Please leave any comments there is the issue description is incomplete.
