### ISSUE TITLE
Support for iOS?

### ISSUE THREAD

**Issue by winzig** [microsoft/azuredatastudio#3805]
Is there any hope of this app becoming available for iOS?

I've asked similar questions of the vscode team, and it sounds like the issue is getting Electron in general to work on iOS. 

Recently a cloud-oriented service called coder.com came out, and they've got vscode running directly in the browser. I'm wondering if something similar could happen with ADS.

**Comment by kburtram** [comment]
@winzig we don't have near-term plans to support running ADS in a web browser.  We may look at this at some point in the future.

**Comment by kburtram** [comment]
Closing this out as "out of scope" for now.  Thanks for the suggestion!
