### ISSUE TITLE
Row number column doesn't resize properly

### ISSUE THREAD

**Issue by amachanic** [Microsoft/azuredatastudio#3807]
Run the following query:

SELECT * FROM master.sys.columns

Scroll down to row 99 -- and rows 100+ are impossible to read thanks to the column being too small. And to add insult to injury, it's also not resizable.

![image](https://user-images.githubusercontent.com/39809964/51641722-e8712380-1f34-11e9-949a-6b92b19310eb.png)

**Comment by yualan** [comment]
Looks like this is fixed in the duped issue by making it resizable, closing for now. Adam, let us know if there is an issue.
