### ISSUE TITLE
Notebooks: Switching Kernels Between Notebooks Providers Quickly can Make Attach To Show Nothing

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3808]
Switching kernels that are in different notebook providers very quickly can cause the Attach To dropdown to falsely show no valid connections, even if there are, in fact, valid connections.

Repro:
- Create new notebook (with SQL kernel enabled)
- Connect to new SQL Server
- [SQL is default kernel selected]. Switch to PySpark3
- Immediately switch back to SQL kernel
[Attach To will only show Select Connection and Add New Connection]

**Comment by YurongHe** [comment]
Fixed by  #4371.
