### ISSUE TITLE
Request for a setting in Preferences:- Git Rebase when sync

### ISSUE THREAD

**Issue by thesushil** [Microsoft/azuredatastudio#3822]
Git: Rebase when sync
Force git to use rebase when running the sync command

This setting exists in vscode already. It would be nice to have this feature in azuredatastudio as well.

**Comment by kburtram** [comment]
We recently refreshed to VS Code 1.30.1 source code in master to pick-up this feature.  This will be available in the March release, and is currently available in the latest insiders build.
