### ISSUE TITLE
Cursor and line selection are not in sync

### ISSUE THREAD

**Issue by drhkocher** [Microsoft/azuredatastudio#3824]
When I select something in a list (e.g. database tables, or result records), the cursor is approximately 3-4 lines above the line that gets selected. Or put the other way round, if I click, the line which is 3-4 entries below gets selected...

Anybody els seen this? V1.39

**Comment by kburtram** [comment]
@drhkocher I haven't seen this behavior yet.  Are you seen any other rendering\UI issues?  Also, which OS are you using?  Thanks for reporting!

**Comment by drhkocher** [comment]
I am running the latest Windows 10 on Parallels Desktop VM on an iMac Pro.
However, I just started it again to send you a screen shot, bit this time it’s working alright…

So it might be some sort of hiccup…

Kind regards

Mit freundlichen Grüßen / Best regards

Dr.-Ing. Hartmut Kocher
Geschäftsleitung Technik / CTO

[Signet_s_hoch]

SMART IN OVATION GmbH
STEP8.1, Meitnerstraße 10, D-70563 Stuttgart
FON: +49 (0)711 / 255 212 - 31
FAX:  +49 (0)711 / 255 212 - 10


Internet: https://www.sio-gmbh.de<https://www.sio-gmbh.de/>
E-Mail:    hartmut.kocher@sio-gmbh.de<mailto:hartmut.kocher@sio-gmbh.de>

Sitz der Gesellschaft: Stuttgart
Geschäftsführer: Joachim Tauscher, Dr. Hartmut Kocher
Registergericht: Amtsgericht Stuttgart, HRB 739436



Von: Karl Burtram <notifications@github.com>
Gesendet: Freitag, 25. Januar 2019 20:04
An: Microsoft/azuredatastudio <azuredatastudio@noreply.github.com>
Cc: Kocher, Hartmut <Hartmut.Kocher@sio-gmbh.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Microsoft/azuredatastudio] Cursor and line selection are not in sync (#3824)


@drhkocher<https://github.com/drhkocher> I haven't seen this behavior yet. Are you seen any other rendering\UI issues? Also, which OS are you using? Thanks for reporting!

**Comment by kburtram** [comment]
@drhkocher I'll close since I wasn't able to repo.  Please let me know if the issue persists or reoccurs.  Thanks!
