### ISSUE TITLE
Touch bar Mac OS X - Remove or move over the directional arrows displayed on the left.

### ISSUE THREAD

**Issue by Tcoton** [microsoft/azuredatastudio#3833]
Issue Type: <b>Feature Request</b>

On the new MacBook Pro 2018 with touch bar, it is very annoying to be suddenly switched from one line to another just because the fingers pass over the two directional arrows displayed on the left of the touch bar when typing queries. I suggest to whether remove them or moving them to the middle of the touch bar.

Azure Data Studio version: Azure Data Studio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:17:16.459Z)
OS version: Darwin x64 18.2.0

**Comment by kburtram** [comment]
The ADS Touchbar support is coming from upstream vscode.  Please log an issue on that repro and we'll incorporate those changes in a future source code update.  Thanks!
