### ISSUE TITLE
Result Table Order Change on Tab Change

### ISSUE THREAD

**Issue by zengshengliu** [Microsoft/azuredatastudio#3834]
- Azure Data Studio Version: 1.4.2-Insider

Steps to Reproduce:

1. Open a query window, have 2+ select statements ready and execute
(Current result in result section is as following)
Result for Query 1
Result for Query 2
Result for Query 3
2. Switch to a new tab
3. Switch back to the previous tag
The result will switch to
Query 3
Query 2
Query 1
(Switching tab again at this point will not change the order any further)

**Comment by kburtram** [comment]
@anthonydresser this looks like a regression since the Jan release.  Could you please take a look?

**Comment by anthonydresser** [comment]
I think I know whats the cause. Just need to reverse the order on the repopulation code. I can send a PR out today
