### ISSUE TITLE
Freezes after idle

### ISSUE THREAD

**Issue by Ungerfall** [microsoft/azuredatastudio#3835]
Issue Type: <b>Performance Issue</b>

There appears the issues when switching to app after some idle time. The studio literally freezes and doesn't respond, even more sometimes windows asks to reopen the program.

Regards,
Leonid

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (8.36GB free)|
|Process Argv|C:\Users\Leonid_Petrov1\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    77	 17104	azuredatastudio main
    0	    22	 10748	   shared-process
    0	   225	 12956	   window (#########.sql - disconnected - trunk (Workspace) - Azure Data Studio)
    0	    85	 14132	     extensionHost
    0	    25	  1812	       "c:\Users\Leonid_Petrov1\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\SqlToolsResourceProviderService.exe" --log-file C:\Users\Leonid_Petrov1\AppData\Roaming\azuredatastudio\mssql\resourceprovider_14132.log --tracing-level Critical
    0	     5	  7172	         console-window-host (Windows internal process)
    0	    23	 22220	       "c:\Users\Leonid_Petrov1\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\Leonid_Petrov1\AppData\Roaming\azuredatastudio\mssql\credentialstore_14132.log --tracing-level Critical
    0	     5	  2060	         console-window-host (Windows internal process)
    0	    42	 25504	       "c:\Users\Leonid_Petrov1\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\Leonid_Petrov1\AppData\Roaming\azuredatastudio\mssql\sqltools_14132.log --tracing-level Critical
    0	     5	 16160	         console-window-host (Windows internal process)
    0	    42	 24680	     searchService
    0	    40	 25092	     watcherService
    0	   145	 13660	   gpu-process
    0	    72	 23300	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (##########.sql - disconnected - trunk (Workspace) - Azure Data Studio)
|    Folder (######): 150 files
|      File types: cs(87) sql(14) config(9) snk(7) csproj(6) resx(5) cmd(4)
|                  exe(2) fld(2) vdproj(2)
|      Conf files: csproj(6) sln(1)
|    Folder (#####): 5144 files
|      File types: sql(4821) xml(303) cs(6) fld(2) SQL(2) resx(2) exe(1)
|                  txt(1) sln(1) config(1)
|      Conf files: sln(1) csproj(1);
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vim|vsc|1.0.3

</details>

**Comment by kburtram** [comment]
We'll need to get a repro for this in our perf lab.  I'd guess it's related to paging the application back into memory, though, we'll need to investigate.

**Comment by kburtram** [comment]
Closing some older issues.  We've made numerous perf improvements since this bug was filed.  Please let us know if you're still impacted by this issue.
