### ISSUE TITLE
CSV context menu actions fail

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#3847]
Issue Type: <b>Bug</b>

1. Connect to a SQL Server 2019 master instance
2. Expand Data Services > HDFS in Object Explorer and keep expanding until you get to some csv file
3. Right click on the file and choose "Preview"

Actual behavior: The preview fails with this error message: "Node Command called without any node passed"

Azure Data Studio version: azuredatastudio 1.4.4 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.12GB free)|
|Process Argv|/Users/mairvine/code/sqlopsstudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlservices|dem|0.0.1
sql-vnext|Mic|0.9.3
whoisactive|Mic|0.1.1

</details>

**Comment by YurongHe** [comment]
This was not implemented before. It should be fix by #3862
