### ISSUE TITLE
New Notebook keybinding only works if Preview extension is not installed

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#3853]
Issue Type: <b>Bug</b>

I have Ctrl+Shift+N set as a keybinding for New Notebook. It worked fine until I installed the Preview Extension, and now it gives this error:

![image](https://user-images.githubusercontent.com/8250560/51951273-d38b0900-23e8-11e9-8f9c-5cecb306ee37.png)

![image](https://user-images.githubusercontent.com/8250560/51951290-e271bb80-23e8-11e9-8c6d-212fac6cfed5.png)

Azure Data Studio version: azuredatastudio 1.4.2-insider (14ed60114563c1876e05a34bc14fc74b7298dcbc, 2019-01-23T19:02:56.860Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.68GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer-2|Coe|0.0.25
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
server-report|Mic|0.1.3
sql-vnext|Mic|0.9.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kevcunnane** [comment]
Fixed in extension
