### ISSUE TITLE
Server in OE can't be expanded sometimes

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3854]
Issue Type: <b>Bug</b>

- Open a new SQL notebook
- Connect to Sql instance from attach to
- Connect to another SQL instance from attach to
- Expand the corresponding SQL server connectioned from the above two SQL instance.
- Sometimes the server can't expand.
   Tried to debug it. It works then.

Azure Data Studio version: azuredatastudio 1.4.4 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (173.94GB free)|
|Process Argv|D:\ads\azuredatastudio\.build\electron\azuredatastudio.exe . --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.9.3

</details>

**Comment by kburtram** [comment]
Closing old issues.  There have been many fixes in this area.  Please reactive if this is still occurring.
