### ISSUE TITLE
Cannot execute a query

### ISSUE THREAD

**Issue by romanovmv** [microsoft/azuredatastudio#3868]
Issue Type: <b>Bug</b>

Query window ocasionally stops responding to Execute query command, meanwhile the following queries can be traced via SQL Profiler:
exec sp_executesql N'select c.definition,convert(bit,OBJECTPROPERTY(c.object_id,N''ExecIsQuotedIdentOn'')) from [OmniMeta].sys.sql_modules c where c.object_id = @_msparam_0',N'@_msparam_0 nvarchar(4000)',@_msparam_0=N'303808640'

Those queries are initiated by sqlops-languageService application. Looks like it's a part ob built in intellisense running synchronously under the same SPID?

Azure Data Studio version: Azure Data Studio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:17:16.459Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8259U CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv|/private/var/folders/x7/rfbbhss14_lft0f2zyn5tk9w0000gn/T/AppTranslocation/159C6862-A3C3-47BC-9371-41EEA6716B0E/d/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.35.2
profiler|Mic|0.5.1

</details>

**Comment by kburtram** [comment]
@romanovmv does the UI freeze or clicking the "Execute" button just doesn't do anything?  Do you know if there are any additional repro steps, such as canceling a previously executing query or something like that?

**Comment by romanovmv** [comment]
@kburtram it does nothing, I've attached a sample video. But normally it's stuck for ~10-30 seconds. I've also noticed that it happens mostly when working on  our US servers (ping from Australia is about 200ms).
https://drive.google.com/open?id=1Bds2uHxkguJvibim0w1K0H2VR5q7Xpm9

**Comment by anthonydresser** [comment]
Could be related to #2694

**Comment by anthonydresser** [comment]
related to #3627

**Comment by cheenamalhotra** [comment]
This issue has been addressed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), closing as resolved.
