### ISSUE TITLE
Keystroke search on Servers -> Object List

### ISSUE THREAD

**Issue by ChrisLounsbury** [microsoft/azuredatastudio#3871]
Issue Type: <b>Feature Request</b>

When browsing Server Objects in the Server pane, would be nice to have the ability to type to search down the object list.  I.e. when selecting a table under the Tables folder, typing "dbo.MyT" would auto scroll and select the objects that match that string.  Similar functionality exists in SQL Management Studio.

Azure Data Studio version: Azure Data Studio 1.4.3-insider (9cffe4d476d2158ce904bdebffd5ed83ebede4f2, 2019-01-28T03:09:20.556Z)
OS version: Darwin x64 18.2.0

**Comment by cheenamalhotra** [comment]
Search/Filter feature is available in Server Tree > Object Explorer.
Closing as resolved.
