### ISSUE TITLE
Text Editor Improvement

### ISSUE THREAD

**Issue by MadMonkeyMan** [Microsoft/azuredatastudio#3872]
Issue Type: <b>Feature Request</b>

I want to use the feature available in many other IDEs where i can hold ALT and highlight text vertically.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.16299

**Comment by yualan** [comment]
Hi Brady, we inherit this behavior from VS Code where you can hold shift+alt to select text vertically. Let us know if this meets your ask.

**Comment by kburtram** [comment]
@MadMonkeyMan please try using Shift-Alt for box select as @yualan noted.  Thanks!

**Comment by MadMonkeyMan** [comment]
That worked

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
