### ISSUE TITLE
Editor tab "clears" query window and other tabs

### ISSUE THREAD

**Issue by DanielSSilva** [Microsoft/azuredatastudio#3885]
- Azure Data Studio Version: 
Version 1.3.9
Commit cacf0777c747046af6839de3688d709b10ef9fca
Date 2019-01-14T23:30:09.442Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

This issue doesn't always happen, and I don't have a pattern. What happens is that I'm working on a tab, and when I switch to another, suddently I've "lost" my tabs and can't see the content of the opened tab. If I go to another tab, it's all normal. Going back to the tab that causes the issue sometimes works, others the process repeats.

Steps to Reproduce:

1. Have more than 1 tab open;
2. Switch tab
3. ![image](https://user-images.githubusercontent.com/6862119/52115528-bd5a9400-2606-11e9-96e0-0dca0323d880.png)
   As can be seen on the left side, I have other tabs opened
4. Switching to another tab, it all comes back to normal
![image 1](https://user-images.githubusercontent.com/6862119/52115591-de22e980-2606-11e9-9147-f273bdbc6638.png)
5. Sometimes if I try again to go to the tab that I wanted, it's ok, other times I must restart ADS

**Comment by kburtram** [comment]
If you can repro again, please check the "Help->Developer Tools" Console to see if an error was raised.
