### ISSUE TITLE
Implement Custom Title Bar like in VS Code

### ISSUE THREAD

**Issue by liguori** [Microsoft/azuredatastudio#3886]
It would be nice to have aligned the same features of VS Code in Azure Data Studio as well. In this case I am talking about the Title Bar Style to Custom.

Currently it's implemented and user can change it via settings but it's not working:
![image](https://user-images.githubusercontent.com/8238828/52120308-2dbfe000-261c-11e9-99d5-300545feb0f7.png)

Another example it could be the Settings editor still in preview.

**Comment by anthonydresser** [comment]
dupe #3300
