### ISSUE TITLE
Column Encryption Setting Enabled not working

### ISSUE THREAD

**Issue by danaustralia** [microsoft/azuredatastudio#39]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---
When working with Always Encrypted, I found great you guys created the selection box for the encryption setting but it does not seem to be working at the moment. Has it been implemented yet?

Steps to Reproduce:

1. Create new connection (to a database with Always Encrypted)
2. Before clicking Connect, Click the Advanced button 
3. Under Security, click on the "Column Encryption Setting" dropbox and select "Enabled"
4. Click "OK" and then "Connect"
5. Run a SELECT statement from a table that has encrypted fields. The encrypted fields will not be decrypted.

**Comment by kburtram** [comment]
@corivera could you please email SqlClient owner to determine if AE is supported in .Net Core?

**Comment by corivera** [comment]
@kburtram Column Encryption is currently not supported in .Net Core SqlClient

**Comment by Xtrimmer** [comment]
The selection box for enabling the Always Encrypted column encryption is wired up and working. The feature is available in the insiders builds and will be generally available in the March release.
