### ISSUE TITLE
Connecting to Chinese Azure not possible with Azure AD authentication

### ISSUE THREAD

**Issue by MohsineC** [microsoft/azuredatastudio#3903]
The new feature to have Azure AD as authentication type works great for the Public Azure regions but unfortunately there is no way to choose the Chinese Azure when you are asked to enter your credentials.

Without this we still have to use normal sql users/logins to connect to those DB's in China.

Azure Storage Explorer has it for a while already...
![image](https://user-images.githubusercontent.com/31959380/52273802-3f222880-294b-11e9-81f3-7df84e1f2dcc.png)

**Comment by kburtram** [comment]
We're tracking this request for all National Clouds with https://github.com/microsoft/azuredatastudio/issues/3013.  We are working on this now and expect this to be available in the Dec release.
