### ISSUE TITLE
Connecting to a server takes a long time at first

### ISSUE THREAD

**Issue by mario-d-s** [Microsoft/azuredatastudio#3904]
Issue Type: <b>Performance Issue</b>

I have a saved connection to my local SQL Server instance (using "(local)" as the server name). When opening Azure Data Studio, expanding the connection node takes quite a long time (easily >5s). It is much faster after that when just disconnecting and reconnecting.

Compared to SSMS, it connects virtually instantly to the local MSSQL instance, but of course the program takes longer to start.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.23GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    87	  4432	azuredatastudio main
    0	    73	  3524	   shared-process
    0	    72	 11280	   window (Issue Reporter)
    0	   300	 12644	   window (Azure Data Studio)
    0	   110	 12588	     extensionHost
    0	    57	  1792	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\maridesc\AppData\Roaming\azuredatastudio\mssql\sqltools_12588.log --tracing-level Critical
    0	    11	  3508	         console-window-host (Windows internal process)
    0	    30	 20312	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\SqlToolsResourceProviderService.exe" --log-file C:\Users\maridesc\AppData\Roaming\azuredatastudio\mssql\resourceprovider_12588.log --tracing-level Critical
    0	    11	 13092	         console-window-host (Windows internal process)
    0	    29	 21268	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.63\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\maridesc\AppData\Roaming\azuredatastudio\mssql\credentialstore_12588.log --tracing-level Critical
    0	    11	 21460	         console-window-host (Windows internal process)
    0	    40	 14256	     searchService
    0	   117	 17844	   gpu-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.5.1

</details>

**Comment by yualan** [comment]
Hi Mario, is this still the case for you when trying to connect with the latest version of Azure Data Studio? v1.4.5?

**Comment by kburtram** [comment]
@mario-d-s when Azure Data Studio first launches it spawns a child service that handles database connections.  Any connection requests that occur prior to when the services have completed loading will be queued until the service is ready.  

This can cause initial connections to take an unexpectedly long time in some cases.  You'll know the services have completed loading once you've seen the "Service Started" message show and disappear in the status bar.  Please let me know if you still see this initial delay when connecting after the service has started.

![image](https://user-images.githubusercontent.com/599935/53371037-1b2b8480-3904-11e9-9e12-6caa97379a57.png)

**Comment by mario-d-s** [comment]
Unfortunately I cannot really do a representative test anymore as I am now working at a new employer since reporting this.

Being on a different machine is one thing but I'm also actually on Debian instead of Windows now.

I'd say feel free to close this issue, maybe people with the same problem can find it and ask to re-open if it turns out that fixes are needed.

**Comment by kburtram** [comment]
@mario-d-s thanks for reporting this issue.  I'll close based on your previous comment.
