### ISSUE TITLE
char(13) + char(10) Does not behave the same as SSMS

### ISSUE THREAD

**Issue by JonathanPinney** [Microsoft/azuredatastudio#3905]
I'm trying to create a string which contains a line break. When using Azure Data Studio, I tried using CONCAT to include the line break using char(13) + char(10) but the line break is not shown in the resulting string. I also tried concatenating the strings manually using +. I copied the exact same TSQL to SSMS and the char(13) + char(10) result in a true line break. The TSQL below is an example of this issue.

```
-- This is an example of char(13) + char(10) behaving differently in Azure Data Studio vs SSMS v11

DECLARE @string varchar(100)

SET @string = 'this is the first line. ' + char(13) + char(10) + 'this is the second line.'

SELECT @string

-- Azure Data Studio output:
-- this is the first line. this is the second line.

-- SSMS output: 
-- this is the first line. 
-- this is the second line.
```

SSMS Version:
Microsoft SQL Server Management Studio						11.0.6567.0
Microsoft Analysis Services Client Tools						11.0.6567.0
Microsoft Data Access Components (MDAC)						6.3.9600.17415
Microsoft MSXML						3.0 6.0 
Microsoft Internet Explorer						9.11.9600.19180
Microsoft .NET Framework						4.0.30319.42000
Operating System						6.3.9600

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17763

**Comment by yualan** [comment]
Hi Jonathan, I tried to repro this in Azure Data Studio 1.4.5 and SSMS 17.9.1. In both, your query seems to produce the same output of being on one line in both Azure Data Studio and SSMS.

![image](https://user-images.githubusercontent.com/30873802/53211773-427a0d00-35f7-11e9-8283-1ad4d50eb378.png)

Any additional info would be appreciated.

**Comment by JonathanPinney** [comment]
I tried to recreate this issue in SSMS and Azure Data Studio, pointing to multiple versions of SQL Server and was unable to recreate..
