### ISSUE TITLE
Installing Notebook Dependencies failing

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#3918]
Issue Type: <b>Bug</b>

Installed the latest bits.
Enabled SQL Kernel settings.
Opened a New Notebook.
Was prompted for the Notebook dependencies.
When installing hit the following issue -

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/52368384-45f88a80-2a74-11e9-97dc-8135147577e8.png">

Azure Data Studio version: Azure Data Studio 1.4.4-insider (a2c73771349e0cbe6e11523cd7688396f37e302f, 2019-02-06T03:23:11.987Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/A25A5AA8-C4E7-46E7-848A-1F3CB5521694/d/Azure Data Studio_Feb.app/Contents/MacOS/Electron -psn_0_3187466|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
gc-excelviewer|Gra|2.1.26
agent|Mic|0.35.2
import|Mic|0.5.0
sql-vnext|Mic|0.10.0

</details>

**Comment by kevcunnane** [comment]
@corivera  will prioritize fixing this.

**Comment by kevcunnane** [comment]
Update - this is happening in released vsix but not when running in debug mode. Needs more investigation...

**Comment by kevcunnane** [comment]
Update 2: bug fix ready, will have checked in & built shortly so can unblock testing.

**Comment by kevcunnane** [comment]
This is fixed in the extension. Sending mail with latest bits now.
