### ISSUE TITLE
Installing VSIX template for Mac

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3919]
- Azure Data Studio Version: latest

Steps to Reproduce:

Open an .ipynb file, starts to download dependencies. Then errors with "Installing Notebook dependencies: Installing Notebook dependencies failed with error: TypeError: pna.nextTick is not a function"

**Comment by kevcunnane** [comment]
Closing as a duplicate of #3918 as it is the same issue. We'll track there and @corivera will prioritize this immediately.
