### ISSUE TITLE
Save/Save As don't work with Notebooks

### ISSUE THREAD

**Issue by Charles-Gagnon** [Microsoft/azuredatastudio#3920]
Issue Type: <b>Bug</b>

1. Create new Notebook
2. Attempt to save either with File -> Save/Save As or ctrl+s/ctrl+shift+s
3. Either nothing happens or an error is displayed (haven't been able to reliably repro error)

![capture](https://user-images.githubusercontent.com/28519865/52368533-853ac300-2a03-11e9-81bd-c267e7290140.PNG)

Note that saving through the Save button on the Notebook appears to work correctly
Azure Data Studio version: azuredatastudio 1.4.4-insider (a2c73771349e0cbe6e11523cd7688396f37e302f, 2019-02-06T03:27:45.073Z)
OS version: Windows_NT x64 10.0.17763

<details>

<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (43.13GB free)|
|Process Argv|C:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.0

</details>

**Comment by kevcunnane** [comment]
Fixed in recent commit
