### ISSUE TITLE
Insiders build should have differently named app / exe

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#3921]
When unzipping the Insiders build it has the exact same name as the regular one. This makes it hard to put both side-by-side in the Mac Applications folder, and I'm unclear if for Windows there's a separate user/system installed Insiders build or it replaces the stable one. Can we fix this?

**Comment by wsmelton** [comment]
I would like to see this handled done as VS Code does.

They have `code-insiders` for the insider channel, as well this is a green icon vs the stable channel is just `code` and a blue icon. I think having `azuredatastudio-insider` would allow users and developers to more easily work between the two.
