### ISSUE TITLE
Notebooks: "..." on Cells Can Persist and Is Not Clickable when Cell Is Unselected

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3925]
<img width="1342" alt="image" src="https://user-images.githubusercontent.com/40371649/52375850-84129180-2a15-11e9-8561-fb7927155cb1.png">

Create new notebook, add some code cells. Mouse over the "..." and move your mouse vertically up through other cells and you will see the "..." appear on multiple unselected cells.

In addition, if a cell is unselected, clicking the "..." doesn't do anything.

**Comment by kevcunnane** [comment]
Fixed
