### ISSUE TITLE
'Attach To' is set to localhost when trying to connect to an existing connection

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3932]
- Create/open a notebook
- Select any of the spark kernels
- Select 'Add new connection' in Attach To dropdown
- Enter server details which was already connected
- Connection dialog stays opened
- Attach To is set to localhost

![image](https://user-images.githubusercontent.com/44002319/52377339-6e06d000-2a19-11e9-9f01-435f40e05330.png)

**Comment by chlafreniere** [comment]
This also occurs when you select "Add New Connection" and click cancel from the dialog.

**Comment by rajmusuku** [comment]
Fixed it.
