### ISSUE TITLE
While cell is running, F5 terminates the running cell

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3936]
- Open a notebook
- Select a cell
- F5, while it is running. F5 again.
- Cell stops. Outout displays the following. If it is desire behavior. Maybe we should document it.

Starting Spark application
 ---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-2-ce7a8a69c911> in <module>()
----> 1 get_ipython().run_cell_magic('spark', '', '1+1')

**Comment by kevcunnane** [comment]
Good question. Let's check with PM and compare to other notebook viewers. I think it's meant to cancel current and re-execute, but that we have a bug here.

**Comment by kevcunnane** [comment]
Should prompt to cancel current, and only run on confirm. Also doesn't restart. Also... should have dedicated cancel keybinding.
