### ISSUE TITLE
Notebooks: With SQL Not Enabled and the vNext Extension Not Installed, Error Message is Incorrect

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3938]
When the SQL kernel isn't enabled and the vnext extension isn't installed, the error message is incorrect. It says the following:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/40371649/52378862-b0caa700-2a1d-11e9-87a9-76e141c4354e.png">

The error message really should say something about "please install the 2019 extension or enable the sql kernel", since the 2019 extension itself isn't strictly required to run cells with the SQL kernel.

**Comment by kevcunnane** [comment]
Punting as will be solved in next release
