### ISSUE TITLE
Unable to delete or add cells in Mac with ... without double clicking cell first

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#3939]
- Azure Data Studio Version: 1.4.4 insider

Steps to Reproduce:

1. In a notebook, try to click the "..." in a cell (that hasn't been double clicked on for editing) 
2. Result: unable to get the drop down menu without double clicking in a cell

**Comment by kevcunnane** [comment]
Thanks for reporting, I have a bug fix that'll be out shortly.
