### ISSUE TITLE
SQL Server 2019 Tab Shows Up Even on Non-SQL 2019 Instances in Manage Dashboard

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#3942]
Connect to a non-2019 instance, and go to the Manage Dashboard.

There will be a "SQL Server 2019 (Preview)" tab next to the Home tab. Clicking on the Create External Table launches the wizard, and an error message appears, not allowing users to proceed.

It would be really nice not to show the tab at all in these cases.

**Comment by YurongHe** [comment]
Fixed by #3981
