### ISSUE TITLE
Clear output shows up even there is no output in code cell

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#3943]
- Create/open a notebook
- Add a code cell and select …
- Clear output is displayed although there is no content on output

![image](https://user-images.githubusercontent.com/44002319/52380007-f9379400-2a20-11e9-94d5-d54050c1cdf9.png)

**Comment by kevcunnane** [comment]
You already opened this, and I have a PR fix out. Closing as duplicate...
