### ISSUE TITLE
Another stuck at loading kernels

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3950]
- Open notebook with the following content. 
- Got the following notification
  Could not display contents: TypeError: Cannot read property 'display_name' of undefined

And Kernel stuck at "Loading kernels"

Notebook content.
{"cells":[{"cell_type":"code","execution_count":null,"metadata":{},"outputs":[],"source":[]}],"metadata":{},"nbformat":4,"nbformat_minor":2}

**Comment by kevcunnane** [comment]
No repro for now
