### ISSUE TITLE
New Notebook-> change to PySparks-> Failed to change kernel: Invalid response: 403 Forbidden

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3951]
- Has big data cluster connection in OE and server is selected.
- ctrl+shift+N create a new notebook
- switched kernel to PySpark3
- Attach to: localhost
  got notification: Failed to change kernel: Invalid response: 403 Forbidden

Expected: AttachTo list the big data cluster selected from OE.

**Comment by kevcunnane** [comment]
Dupe
