### ISSUE TITLE
Notebooks: open notebook and Ctrl+Z on code cell clears contents

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3952]
We're not respecting code editor undo history. By creating an editor then copying code in, we add an undo point. We should clear this so that on 1st use people don't accidentally remove all contents.

Repro:
- Open existing notebook with code cells
- Click on a code cell with text
- Use Ctrl+Z to undo

Expected:
- Nothing happens, didn't previously do something
Actual:
- Deletes all text

**Comment by rajmusuku** [comment]
Fixed
