### ISSUE TITLE
Should we use the server in AttachTo when Select "New Notebook" from dashboard

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3954]
- Select "New Notebook" from big data cluster dashboard
- Attach To: "Select connection"
Expected: the server is selected in Attach To

**Comment by kevcunnane** [comment]
@Yurong can you complete this bug report? Is this not auto-connecting? It should be so this is definitely a bug. When launched from dashboard it implies we should connect.

**Comment by kevcunnane** [comment]
@YurongHe please try on latest.

**Comment by YurongHe** [comment]
@kevcunnane, I figured it out. The problem is: new Notebook from BDC dashboard, but OE select a box server. getCurrentGlobalConnection returns OE server connection. So profile used in NotebookComponent is wrong.

**Comment by kevcunnane** [comment]
We should be using connection passed as argument to the task. Can we update to use that as expected?
