### ISSUE TITLE
Attach To: stuck at "Loading contexts...

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3955]
- OE has big data connection, sql 2017 and cloud connections
- Select cloud server in OE
- Open the attach notebook
- Attach To: stuck at "loading contexts..."
![image](https://user-images.githubusercontent.com/43652751/52382832-aca58600-2a2b-11e9-9f23-209224d3c020.png)

**Comment by YurongHe** [comment]
[train_and_create_machinelearning_models_with_spark.zip](https://github.com/Microsoft/azuredatastudio/files/2838825/train_and_create_machinelearning_models_with_spark.zip)

**Comment by rajmusuku** [comment]
Failed to reproduce this issue. Please do let me know if some one can repro it.

**Comment by kevcunnane** [comment]
new state: 
![image](https://user-images.githubusercontent.com/10819925/52449504-70862a00-2aec-11e9-8f65-baf060c63c69.png)

Let's fix for Feb.
