### ISSUE TITLE
Sql notebook IntelliSense should go away after hit F5

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#3958]
- Create a SQL notebook
- Input a query for code cell
- Hit F5 to run the cell
  The IntelliSense is still displayed after got query result from server. 

Expected: 
  After hit F5, IntelliSense goes away.

![image](https://user-images.githubusercontent.com/43652751/52384557-db732a80-2a32-11e9-916e-db0b730090f0.png)

**Comment by chlafreniere** [comment]
This keeps coming up. Let's bump this up to March to see what we can do to fix. After we have a solution for notebooks, let's talk to the broader team around whether we should enable for query editor as well.
