### ISSUE TITLE
ADS tries to shutdown notebook server twice after closing notebook

### ISSUE THREAD

**Issue by corivera** [Microsoft/azuredatastudio#3959]
Steps to Reproduce:
1. Open a new notebook via command palette.
2. Close Notebook.
3. Output window shows an error due to trying to stop a stopped server.

Output:
/home/corivera/azuredatastudio-python/0.0.1/bin/python3 -m jupyter notebook stop 8888
/home/corivera/azuredatastudio-python/0.0.1/bin/python3 -m jupyter notebook stop 8888
    stdout: Shutting down server on port 8888 ...
    stdout: 
    stderr: There is currently no server running on port 8888
    stderr: Ports currently in use:
    stderr:   - 8891
    stderr:   - 8889
    stderr: 
Error stopping Notebook Server: Command failed: /home/corivera/azuredatastudio-python/0.0.1/bin/python3 -m jupyter notebook stop 8888
There is currently no server running on port 8888
Ports currently in use:
  - 8891
  - 8889

**Comment by kevcunnane** [comment]
I think we do stop and shutdown which may be causing this. Should be easy to repro (and hence fix)
