### ISSUE TITLE
Can we use smaller font in grid so we can display more rows

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#3961]
Just suggestion. We don't have to change it.
![image](https://user-images.githubusercontent.com/43652751/52385146-31e16880-2a35-11e9-8829-a2fb72721423.png)

**Comment by kburtram** [comment]
@YurongHe I agree we should update the default to something closer to SSMS.  There are settings to control this, such as `"resultsGrid.fontSize": 10`.  Unfortunately, I couldn't get `"resultsGrid.rowHeight": 10` to work so regardless of how small the font is the same number of rows will always be displayed (though with a smaller font more content will be visible in each cell).

**Comment by sirphilliptubell** [comment]
resultsGrid.rowHeight is not working for me.
Tried values between 1 and 100 and this setting doesn't seem to have any effect at all.

**Comment by kevcunnane** [comment]
Moving to April - @anthonydresser / @kburtram should this "just work" for notebooks once it's fixed in query editor?

**Comment by chlafreniere** [comment]
We hardcode this at the moment in notebooks. We can change this, just need to read from the user settings here.

**Comment by chlafreniere** [comment]
We also have rowHeight hardcoded in notebooks, which we should be reading from user settings. Will look into font size as well.
