### ISSUE TITLE
No way to change connection name for existing connections

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/azuredatastudio#3963]
Apparently the feature to give a display name to a connection was implemented in #66.
However I see no way to change the name for existing connections in the SERVERS tab. I even tried to set `databaseDisplayName` manually in settings.json, but I don't see the name anywhere. Is this supposed to work?

**Comment by yualan** [comment]
Hi Thomas, there are two workarounds:

**Workaround 1:**
If you go to Settings.json, you can: go to datasource.connections, find your connection, and change connectionName to the custom display name you would like to see. Save your settings.json and restart Azure Data Studio. You should see the new custom name.

**Workaround 2:**
If you click on your target connection, click add new connection, and select your recent connection from the list, you can modify **name (optional)** to your new display name, and then reconnect.

If neither of these solutions work for you, we can mark this as a feature request and let us know what you would like to see.

**Comment by thomaslevesque** [comment]
Thanks @yualan!

Both workarounds work, but they don't to the same thing...

Workaround 1 changes the name in "recent connections", but not in "saved connections"
Workaround 2 changes the name in "Saved connections", but I think it really needs a UI to change the name; going to settings.json is far from obvious, and the schema isn't documented, as far as I can tell. Also, it's confusing that the JSON initially contains an empty "databaseDisplayName" property which doesn't seem to have any effect, and not a "connectionName" property (which is the one that actually does something)

It would be nice to unify the experience and make it easier to rename a connection.

**Comment by kkarakk** [comment]
If the connection fails then workaround no 2 fails, just **fyi**. came here to check for a solution to this. We use two data lines and the IP changes, went to create a duplicate connection with a different IP and modify the name of the older connection and am unable to do since the connection fails(as line is down)

**Comment by Charles-Gagnon** [comment]
We added the ability to edit a connection a while back - which includes the Display Name.
