### ISSUE TITLE
Upgrade pandas to 0.24.0

### ISSUE THREAD

**Issue by barik** [microsoft/azuredatastudio#3970]
The current version of the pandas python package in ADS is 0.22. There are several important bug fixes in newer releases related to basic ingestion scenarios such as reading fixed-width files and encoding detection. It would be helpful for notebook users if they did not have to workaround these issues and could use 0.24.

https://pandas.pydata.org/pandas-docs/stable/whatsnew/v0.24.0.html

**Comment by kevcunnane** [comment]
Blocked on testing & potentially fixing sparkmagic. Last I tried it wasn't compatible with higher versions than 0.22.0.

**Comment by kevcunnane** [comment]
@barik we have to move to April on this, haven't been able to update SparkMagic / do verification on this.

**Comment by kevcunnane** [comment]
@corivera this is done, right?
