### ISSUE TITLE
Opening several notebooks in a row causes some errors to be thrown

### ISSUE THREAD

**Issue by corivera** [Microsoft/azuredatastudio#3971]
Steps to Reproduce:
1. Run New Notebook several times in a row from Command Palette.
2. Some 403 errors are thrown, and kernels fail to load for affected notebooks.

Errors:
Failed to change kernel: Invalid response: 403 Forbidden
Could not start session: Invalid response: 403 Forbidden

**Comment by kevcunnane** [comment]
If this misses for Feb can push to March, but nice to have

**Comment by kevcunnane** [comment]
Ping - this definitely happens, would be good to get this fixed as we push for stability this week.

**Comment by chlafreniere** [comment]
This has been fixed.
