### ISSUE TITLE
Tabbing away and back to Notebook loses scroll position

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3973]

**Comment by rajmusuku** [comment]
Fixed it in https://github.com/Microsoft/azuredatastudio/pull/4531

**Comment by vickyharp** [comment]
This is happening on today's insider build
![Notebook scrolls to top](https://user-images.githubusercontent.com/8250560/54787616-84dc3d00-4be9-11e9-850b-5b1b621754e7.gif)

**Comment by vickyharp** [comment]
Re-updated, looks good
