### ISSUE TITLE
Notebook: Some markdown cells size is incorrect on editing

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#3986]
Issue Type: <b>Bug</b>

Take the below cell and add as text to a new markdown cell in a notebook. Click out, then double click to edit. 

Expected: All lines shown
Actual: Get a scrollbar, a number of lines are hidden.

```md
# Churn Analysis Demo

[**Customer Churn**](https://en.wikipedia.org/wiki/Customer_attrition) also known as Customer attrition, customer turnover, or customer defection, is the loss of clients or customers.

* Predicting and preventing customer churn represents a huge additional potential revenue source for every business.
* The ability to predict that a particular customer is at a high risk of churning, while there is still time to do something about it, represents a huge additional potential revenue source for every online business. Besides the direct loss of revenue that results from a customer abandoning the business, the costs of initially acquiring that customer may not have already been covered by the customer’s spending to date. (In other words, acquiring that customer may have actually been a losing investment.) 
* Furthermore, it is always more difficult and expensive to acquire a new customer than it is to retain a current paying customer.
* This solution is...  
  * Built on top of Databricks Platform
  * Uses a machine learning **Gradient boosting algorithm** implementation to analysis a Customer Churn dataset   
* This demo...  
  * demonstrates a simple churn analysis workflow.  We use Customer Churn dataset from the [UCI Machine Learning Repository](http://archive.ics.uci.edu/ml/index.html).
```

Azure Data Studio version: azuredatastudio 1.4.4 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 2|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|/Users/kevcunnane/projects/azuredatastudio/.build/electron/Azure Data Studio.app/Contents/MacOS/Electron . --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.0
PowerShell|ms-|1.11.0

</details>

**Comment by chlafreniere** [comment]
I cannot repro. @kevcunnane can you still repro?

**Comment by chlafreniere** [comment]
This has since been fixed.

**Comment by tonio-lora** [comment]
Hi @chlafreniere, I'm experiencing that issue on the latest version of Azure Data Studio. The Code cell does not expands to use all lines but instead shows a scrollbar. Can you tell me how to workaround this issue?

![image](https://user-images.githubusercontent.com/7561899/59467921-78394080-8df6-11e9-9e63-0881ad90b621.png)
