### ISSUE TITLE
Allow ApplicationName connection string parameter to be set by user.

### ISSUE THREAD

**Issue by johnmart82** [microsoft/azuredatastudio#3991]
When creating a connection to a SQL Server I would like to be able to go to the "Advacned" section and define a custom value for the "ApplicationName" parameter on the connection string. This is functionality I use in SSMS on a regular basis for naming my connections to a server.

Thanks :-)

**Comment by GitClickOk** [comment]
As an intermediate/temporary solution, it will be good at least add "Azure Data Studio" to application name. PgAdmin currently adds something like "pgAdmin 4 - CONN:1365003", while ADS adds nothing...

**Comment by TheRealChssAddct** [comment]
I love this request. Was just about to make it myself.  Hard to believe this is not addressed, since 2019.

Another intermediate solution, at least for executing queries, is to run this:

`set application_name to 'Azure Data Studio';`
