### ISSUE TITLE
Resultset magnify button doesn't unmagnify

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3993]
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Run a query with multiple resultsets
2. Click the Magnify button
3. Click the Un-Magnify button

Expected: Resultset grid return to original state

Actual: Resultset grid stays in magnified state and clicking button has no effect

**Comment by kburtram** [comment]
@anthonydresser could you please take a look at this issue?  I think there were some recent changes in this area and it doesn't appear to be working as expected.

**Comment by MattIrv** [comment]
I've worked on this code before so I'll investigate it. @anthonydresser let me know if you're already looking at it

**Comment by MattIrv** [comment]
PR to fix is at #4007
