### ISSUE TITLE
Notebook - Get Failed to change Kernel error message and Configure for Python dialog at the same time

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3994]
Issue Type: <b>Bug</b>

Open a new notebook.
The Configure for Python dialog opens and also see a Get Failed to change Kernel error. 

Expected:
Should not see Failed to change Kernel error.

Thanks
Smitha

![image](https://user-images.githubusercontent.com/27451624/52589509-d2e47080-2df3-11e9-893f-b2222f79d6b1.png)

Azure Data Studio version: Azure Data Studio 1.4.5 (0c316d322582f47881ac5928f607bbd2e15d30e1, 2019-02-11T17:27:24.731Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|8, 14, 16|
|Memory (System)|16.00GB (0.37GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1503599|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
sql-vnext|Mic|0.10.1
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
I think it's been fixed, but waiting on @rajmusuku  to confirm

**Comment by rajmusuku** [comment]
This is fixed. Attached screen shot for reference.

![image](https://user-images.githubusercontent.com/44002319/52661327-a6455d00-2eb6-11e9-91d6-bd1cf4cc4c6a.png)
