### ISSUE TITLE
Notebook - Blocked from using SQL notebook as Attach to show Loading context and not showing the active SQL Server connection also there is no option to add new SQL Server connection. 

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3995]
Issue Type: <b>Bug</b>

Open New Notebook.
You see in the background that the Kernel is SQL, Attach to is Loading context and a Configure Python dialog pops up. 
Cancel the configure Python dialog.

Actual:
=======
1. Attach to still shows Loading context. There is no option to add SQL Server connection. Kind of blocked from using the SQL Notebook.
![image](https://user-images.githubusercontent.com/27451624/52590474-396a8e00-2df6-11e9-9b4c-4f5fc9fb8fd4.png)

2. Because I dismissed the Configure Python dialog, I don't see the Python option in the Kernel
![image](https://user-images.githubusercontent.com/27451624/52590527-60c15b00-2df6-11e9-9749-3358fd7643a9.png)

3. As I am connected to a BDC, why don't I see other Kernel option like Pyspark 

Expected:
----------------
1. If I don't have Python libraries, then the default Kernel is SQL. Attach to should be the active SQL connection ( MRU )
2. I should have an option to add a sql server connection under Attach to.
3. I should have an option to change the kernel to Python, as I don't have the python dependencies show the configure python dialog. 
4. If I dismiss the dialog, I should have a way to open it again.
5. As I am connected to a SQL Server BDC, I should be able to see PySpark, R and other Kernels.

When I do a New Notebook from command palette , I get a Configure Python dialog ( a bug is already filed on this issue) but dismissing it I see that Attach to shows the active connection.
![image](https://user-images.githubusercontent.com/27451624/52591448-cf9fb380-2df8-11e9-932e-ba0f41cc5e76.png)
  

Azure Data Studio version: Azure Data Studio 1.4.5 (0c316d322582f47881ac5928f607bbd2e15d30e1, 2019-02-11T17:27:24.731Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|14, 16, 16|
|Memory (System)|16.00GB (0.41GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1503599|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
sql-vnext|Mic|0.10.1
whoisactive|Mic|0.1.1

</details>

**Comment by rajmusuku** [comment]
Issue is fixed. Please see attached below.

![image](https://user-images.githubusercontent.com/44002319/52650334-e6004a80-2e9e-11e9-83ba-b8d6d4182e26.png)
