### ISSUE TITLE
Notebook- if a dialog is cancelled, there should be an affordance to open it again.

### ISSUE THREAD

**Issue by smithaBharadwaj** [Microsoft/azuredatastudio#3996]
Issue Type: <b>Bug</b>

When we detect that Python libraries are not present on users machine and smartly prompt the Configure Python dialog, we should also have an affordance for the user to open the dialog if they dismissed it the first time. 

Right now we have this affordance through command palette but that is not very intuitive. 

When user dismisses the dialog without installing, the Kernel should show at the minimum Configure Python option. Here is the mockup
![image](https://user-images.githubusercontent.com/27451624/52592388-1abac600-2dfb-11e9-9a5b-ab2292f2be0b.png)

Right now we just show Loading Kernel, Loading Context and the dropdowns have no option.

![image](https://user-images.githubusercontent.com/27451624/52592238-b992f280-2dfa-11e9-8867-3e091afa76d8.png)

Azure Data Studio version: Azure Data Studio 1.4.5 (0c316d322582f47881ac5928f607bbd2e15d30e1, 2019-02-11T17:27:24.731Z)
OS version: Darwin x64 17.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|12, 17, 18|
|Memory (System)|16.00GB (1.32GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
agent|Mic|0.35.2
import|Mic|0.5.0
profiler|Mic|0.5.1
sql-vnext|Mic|0.10.1
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
@corivera / @rajmusuku we should get this for March

**Comment by chlafreniere** [comment]
This has been fixed.
