### ISSUE TITLE
Edit Job Doesn't Show Steps For Any Job

### ISSUE THREAD

**Issue by frs1717** [Microsoft/azuredatastudio#3997]
Issue Type: <b>Bug</b>

When I right click to edit a job the edit pane loads (albeit very slowly). For all jobs I have tried editing the "General" tab will be properly populated, but both the "Steps" and "Schedules" tables are empty when they should not be.

Azure Data Studio version: Azure Data Studio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:17:16.459Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (3.06GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by abist** [comment]
@frs1717  Thanks for reporting this bug! Could you try the latest build here - https://github.com/Microsoft/azuredatastudio/releases and see if you still hit this issue?

**Comment by frs1717** [comment]
@abist Still hitting the issue with the latest build. Although, I will note that one time that I opened the latest build I was able to see the steps and schedule of one specific job (but none of my other jobs). I reopened to test if it was consistently possible to view the same job and that time the job steps and schedule were blank again (as were all other jobs).

Thank you!
