### ISSUE TITLE
Installer file count foot print increased by 2000 files

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#3998]
- Azure Data Studio Version: Feb release

Steps to Reproduce:

1. Install Feb release

Actual: number of installed files ~2000 more

![screen](https://user-images.githubusercontent.com/599935/52594500-85bacb80-2e00-11e9-856e-b3a1450aa217.png)

**Comment by kburtram** [comment]
@YurongHe this is most likely related to the additional node modules added for unified connection.  Please take a look to confirm that the 2000 new files added to the installer are all required to be included in the bundled build.

**Comment by kevcunnane** [comment]
@YurongHe Karl mentioned there are ways to minimize the footprint by excluding unused parts of the new dependencies. Can you sync with him and get this resolved?

**Comment by YurongHe** [comment]
mssql extension footprint:
![image](https://user-images.githubusercontent.com/43652751/52889348-55db3300-3134-11e9-9765-acce5cba54e8.png)

**Comment by YurongHe** [comment]
Here are the new modules:
![image](https://user-images.githubusercontent.com/43652751/52889372-760af200-3134-11e9-9570-e1654a6a8a2c.png)
![image](https://user-images.githubusercontent.com/43652751/52889387-891dc200-3134-11e9-869d-7074ee2ac7b1.png)
![image](https://user-images.githubusercontent.com/43652751/52889403-9c309200-3134-11e9-81a3-e41c34350a79.png)
![image](https://user-images.githubusercontent.com/43652751/52889419-b0748f00-3134-11e9-8953-5fc9621cb6b5.png)

**Comment by YurongHe** [comment]
I carefully removed the above highlight modules one by one. mssql extension can be loaded only without dashdash and tunnel-agent modules. Not sure if any scenario will be broken by removing them. For some manually testing, ADS seems working.

All the other modules are required for mssql extension. Without them, running time error: 
     Activating extension 'Microsoft.mssql' failed: Cannot find module 'ajv'.

@kevcunnane, can we rewrite any code by using vs code dependencies, so we can reduce the number of modules?

**Comment by YurongHe** [comment]
3 files are in zip.
Folder list from previous - old.txt and new release - new.txt
File count excel in each folders for new release 

[fileCountsInfo.zip](https://github.com/Microsoft/azuredatastudio/files/2871630/fileCountsInfo.zip)

**Comment by kburtram** [comment]
@YurongHe thanks for investigating.  I think we should wait for the next VS Code source refresh to merge to master then try to enable ASAR on the extension node_modules.  Once that's done we can reassess if this is still relevant.

**Comment by kburtram** [comment]
@anthonydresser please verify we're below the ~8100 file count now.  thanks!

**Comment by kburtram** [comment]
The current packaged build contains ~4400 files, so I'll close this.
