### ISSUE TITLE
Analyze in Notebook doesn't select PySpark3 by default when using SQL BDC connection

### ISSUE THREAD

**Issue by corivera** [Microsoft/azuredatastudio#4002]
Steps to Reproduce:
1. Connect to a SQL big data cluster using a SQL connection.
2. Under the Data Services node, right click on a CSV file and select Analyze in Notebook.
3. The notebook's kernel is Python 3 instead of PySpark3, which causes the spark command to fail.

**Comment by YurongHe** [comment]
Fixed by #4009
