### ISSUE TITLE
Notebooks: Spark UI link broken in Notebooks

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4021]
Issue Type: <b>Bug</b>

- New notebook from SQL big data cluster
- Run 1+1 on PySpark3
- Click on SparkUI link

Expected:
- Get to correct page
Actual:
- Get failure due to this pointing to SQL IP instead of the Knox IP address

![image](https://user-images.githubusercontent.com/10819925/52668665-01804b00-2ec9-11e9-8174-4c62d7caffcf.png)

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.99GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.35.2
sql-vnext|Mic|0.10.2

</details>

**Comment by kevcunnane** [comment]
Update: this is only for unified connection. As we have older "big data cluster" connection still available we can doc as known issue for this release.

**Comment by kevcunnane** [comment]
When fixing, note the code is in [Cell.ts rewriteOutputUrls](https://github.com/Microsoft/azuredatastudio/blob/7ef2d52efdb20807380c739322d8e37cad1fafde/src/sql/parts/notebook/models/cell.ts#L358). Ideally this code should be moved to a contribution point so that this only gets called for Spark outputs, and only on live update. It should live where the Spark kernel code is.

**Comment by kevcunnane** [comment]
@chlafreniere you said you're take this, correct?

**Comment by chlafreniere** [comment]
Yes I will take this.
