### ISSUE TITLE
right-align in notebooks with wrap text

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4023]
- Azure Data Studio Version: latest insider

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/28786161/52673082-8a50b400-2ed4-11e9-841d-06a02508607c.png)

1. Shouldn't the test be left-align by default? I could be doing something wrong here.. please let me know.

**Comment by chlafreniere** [comment]
Now that we have grid support, this is no longer an issue. But yes, everything was right aligned accidentally for a very short period of time 😆
