### ISSUE TITLE
Cannot list SQL azure databases

### ISSUE THREAD

**Issue by code4quality** [Microsoft/azuredatastudio#4027]
Issue Type: <b>Bug</b>

I have a Sql Azure database, I can connect to it, but cannot expand the databases in servers panel.

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:30:09.442Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (8.39GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by MattIrv** [comment]
@code4quality What authentication mode are you using to connect (username/password or Azure Active Directory)? We've seen an error like this before with AAD auth so this might be something similar

**Comment by kburtram** [comment]
Closing since issue "needs more info".  Please reactive if the issue persists.  Thanks!
