### ISSUE TITLE
Clicking on column header when there is a large resultset crashes app

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#4028]
- Azure Data Studio Version: 1.4.5

Steps to Reproduce:

1. Run a query that generates a large resultset.  For example, 

```SQL
SELECT * FROM sys.objects CROSS JOIN sys.all_columns c
```
2. Click on a column header

Expected: App doesn't crash.  Either column is selected or no action.

Actual:

<img width="639" alt="screen shot 2019-02-13 at 8 56 01 am" src="https://user-images.githubusercontent.com/599935/52729278-b704da00-2f6d-11e9-8533-0d444fb70a8d.png">

**Comment by chlafreniere** [comment]
This does not repro for me on either of my machines.

**Comment by kburtram** [comment]
This doesn't repro for me on current builds.
