### ISSUE TITLE
Ensure changeKernels always resolves, even in error states

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4029]
We've had a number of issues where the kernels/attach to dropdown can get stuck in error states.

With the current design, we are waiting on changeKernels to resolve in notebookModel before proceeding to populate the dropdowns.

Either change this design to deal with error conditions like rejecting, or ensure that we always resolve.

**Comment by kevcunnane** [comment]
Moving to March - have a fix, and this will help with canceling Python install. Needs testing before pushing through ASK mode
