### ISSUE TITLE
Scripting partition functions failed with SQL Server running on docker accessed using SQL operations studio on Macbook

### ISSUE THREAD

**Issue by arvindravish** [microsoft/azuredatastudio#403]
- SQL Operations Studio Version:

Steps to Reproduce:

1. Create a docker SQL container
2. Connect to SQL instance from SQL Operations Studio
3. Create a partition function
4. Try to script it, it fails.

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if this issue is still impacting your workflow.  Thanks!
