### ISSUE TITLE
Random context failed error....

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#4034]
Issue Type: <b>Bug</b>

Got random popup after installing latest extension and Python install was done. No idea about the repro steps.

Changing context failed: Cannot read property 'updateConnection' of undefined

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.18334

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (14.73GB free)|
|Process Argv|C:\SQL\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.36.0
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.10.2

</details>

**Comment by kevcunnane** [comment]
Thanks UC for reporting. Looks like a timing issue on startup where the session wasn't ready before we set the connection. Will fix.

**Comment by kevcunnane** [comment]
@YurongHe  this is related to the client session work you're looking at.

**Comment by YurongHe** [comment]
Fixed by #4371. I have verified NB will be opened correctly after extension installed.
