### ISSUE TITLE
Clicking on the spark UI/driver log links doesn't do anything....

### ISSUE THREAD

**Issue by uc-msft** [Microsoft/azuredatastudio#4035]
Issue Type: <b>Bug</b>

Subject says it all. After I execute first cell and get the application details, clicking on the links doesn't do anything. Is it supposed to open browser with the link?

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.18334

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (14.07GB free)|
|Process Argv|C:\SQL\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.36.0
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.10.2

</details>

**Comment by kevcunnane** [comment]
Cmd+Click works. This is a limitation right now that we should fix.

Note: we have documented as a known issue for this release that when running from the SQL Server (unified) connection, the Spark UI link is not working. You need to use the older SQL Server big data cluster connection for now. 

Similarly there's a platform issue where driver log doesn't work. They're working on that for fixing in an upcoming CTP.

**Comment by chlafreniere** [comment]
This has been fixed and works with the latest CTPs
