### ISSUE TITLE
Icons for many operators in query plan are blank

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#4036]
Issue Type: <b>Bug</b>

For example, "Columnstore Index Scan", "Get", "External Round Robin" etc in query plan doesn't have any icon or image. This happens with any theme.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.18334

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (14.59GB free)|
|Process Argv|C:\SQL\azuredatastudio-windows\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.36.0
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.3
sql-vnext|Mic|0.10.2

</details>

**Comment by aasimkhan30** [comment]
This should be fixed in the new execution plan feature in April 2022 release. Closing this issue for now.
