### ISSUE TITLE
Enable Azure AD login directly with self-provided token

### ISSUE THREAD

**Issue by rwwilden** [microsoft/azuredatastudio#4044]
Issue Type: <b>Feature Request</b>

This enables some advanced testing scenarios where you have extracted a token (from App Service Managed Identity for example) and can use that identity to run queries against your database. 

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@aaomidi is there anything we can do for this scenario?

**Comment by aaomidi** [comment]
This seems like a pretty big edge case. It's certainly possible to pass this in but the code is currently not setup for that.

Is this a feature PM wants to see in ADS? @yualan

**Comment by cheenamalhotra** [comment]
cc @erinstellato-ms

**Comment by cheenamalhotra** [comment]
Closing as this feature request is not on ADS connectivity roadmap.
