### ISSUE TITLE
Cannot cancel a Query. Query runs too long.

### ISSUE THREAD

**Issue by jsh121988** [Microsoft/azuredatastudio#4045]
I'm running a very basic query that is taking too long and I cannot cancel it. Even if I disconnect from the server it still shows as running. I eventually just had to close the query window. When I went to SSMS, the query returned my 4 results in <1 second. 
So this seems to be an multi-level issue where queries take much longer than they should, and you cannot cancel them.

This is very frustrating because it makes this product unreliable and unusable. I really want to make a full change from SSMS, but I can't when I see issues like this. There are a lot of nice features in ADS that would make me much more productive than using SSMS.

The server is Azure SQL as a service, and I'm using AAD.
Query:
```sql
SELECT DISTINCT MyId, MyColumn
FROM MyTable
WHERE MyId IN (123, 124, 125, 126)
```

ADS Ver: 1.4.5 x64
Windows Ver: Windows Server 2016 x64 Version1607

**Comment by udeeshagautam** [comment]
This should fix most of the issues [https://github.com/Microsoft/sqltoolsservice/pull/780]

**Comment by udeeshagautam** [comment]
Validated with insiders build - able to cancel a running query. Closing this. Please re-open if you still see this issue.
