### ISSUE TITLE
Need asynchronus loading to the Results Pane

### ISSUE THREAD

**Issue by jsh121988** [Microsoft/azuredatastudio#4046]
I'm always frustrated when I run a query that I know will return more than 500k records, and I have to wait for all the data to be received by ADS before any of it is presented in the results pane.

I would like to see rows populate the results pane before all of the data is ready. Meaning at about every 50k rows, the results pane should be populated. This is supported in SSMS, though I'm not sure how it works.

The only way I get partial data is by killing my query, which then dumps the records to the results pane.

**Comment by anthonydresser** [comment]
we have this enabled under the user setting `sql.results.streaming`

**Comment by jsh121988** [comment]
Thank you. I tried searching, but I didn't look for streaming.
