### ISSUE TITLE
Generated script files don't open correctly after restarting ADS

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#4051]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Generate a file using "Script as CREATE' or "Go to Definition"
2. Move file in background behind other editor window that will reopen from Hot Exit
3. Restart ADS
4. Click on generated script in document tab header

Expected: Either generated file isn't included in Hotfix restore path or it reopens correct.

Actual: Generated file throws an error because temp file was deleted when ADS was closed, but tab is still in auto-restore list.

![image](https://user-images.githubusercontent.com/599935/52825386-5e1e6a00-3071-11e9-94d9-8b8cf9279bab.png)

**Comment by udeeshagautam** [comment]
@kburtram Looks like this got fixed by removing from restore path. Current behavior I see : The generated file or the error do not show at reopening ADS. Please let me know if you think that falls under expected and we should close this.

**Comment by udeeshagautam** [comment]
Reason for the issue : 
Definition files are created inside Temp folder as persisted file, (these are not explicitly added in HotExit cache or backup). Whenever VScode reopens it will reopen all the files opened in last session but since they are created in Temp these file are deleted between session and they show the error when opened.

This hapeens with any opened file in vscode if the file is deleted betweens sessions. 

We still have to figure out a way to fix this without creating it outside temp.

**Comment by anthonydresser** [comment]
I'm wondering if we should submit an issue on vscode for this, since presumably this  would repro on our mssql extension.

**Comment by udeeshagautam** [comment]
Good point - I think the bahvior shows with vscode in general if hotexit is set and file is deleted between sessions. I'll validate specifically with mssql ext to confirm it shows the same behavior, and then open an issue. Sounds okay?

**Comment by anthonydresser** [comment]
After testing in vscode, if I create a file, open it in vscode, close vscode, delete the file, and reopen vscode, I can see it try and reopen the file, but it just closes it immediately and doesn't show an error...

There might be more here than the original solution solves.

**Comment by anthonydresser** [comment]
The same behavior exists in ads...I'll investigate why the temp files might have been treated differently for some reason.

**Comment by udeeshagautam** [comment]
VSCode has a similar issue reported but doesn't seem like there will be any behavior change from their side in this regard...
https://github.com/microsoft/vscode/issues/785
