### ISSUE TITLE
SQL Notebook: update notebook.command.new action to work for any connection with a queryProvider

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4052]
- Need new ObjectExplorer context key entry
- Needs to indicate hasQueryProvider or similar
- Use this to detect if a connection would be supported for notebooks (and also new query!)

@chlafreniere and @YurongHe please get this for March

**Comment by chlafreniere** [comment]
Ack.

**Comment by kevcunnane** [comment]
This works now 😄
