### ISSUE TITLE
unable to see SQL2019 preview extension on Azure Data Studio after installing the sql-vnext-0.10.2-win-x64.vsix

### ISSUE THREAD

**Issue by ikflc** [Microsoft/azuredatastudio#4057]
- Azure Data Studio Version: Version 1.3.9
Commit cacf0777c747046af6839de3688d709b10ef9fca
Date 2019-01-14T23:30:09.442Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Steps to Reproduce:

1. download the Window VSIX file from https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-2019-extension?view=sqlallproducts-allversions
2) start up Azure Data Studio (on window server 2012 R2), from File->install extension from VSIX package-> specify the downloaded VSIX file location (from 1 above) 
3) reload after install.
4) I can see the sql 2019 extension enabled from LHS of ADS.
5) ctrl->G or view->server->[SQL2019 instance with polybase & R enabled]
6) from the server->right click->manage-> there is no tab for SQL2019 extension
7) from server->database->right click->manage-> there is no sign of external data source wizard
8) from server->database->exernal data source -> right click or double click-> nothing show up

The SQL2019 extension pack (preview) is installed as I can see from ADS->extension but somehow there is no trace of it at the server level.

I want to create SQL external data source to Oracle tables so we can perform distributed queries in SQL 2019.

**Comment by kevcunnane** [comment]
@ikflc can you update Azure Data Studio? The issue here is likely that the extension relies on new features in version 1.4.5 (Feb release), so updating should resolve. 

Right now we don't have the minimum version defined in the extension, so we need to fix the extension to start clearly mapping to this (e.g. we should have put 1.4.5 in as the version in this case, so when you tried to install it would've failed). Apologies for the trouble here - will update going forward to ensure this is the case.

**Comment by chlafreniere** [comment]
Hey Anthony, looks like we can't set a minimum version in the sql-vnext extension because the ./node_modules/sqlops/bin/install command fails when setting the version with something like '^1.4.5': [https://github.com/anthonydresser/sqlops-extension-sqlops/blob/master/bin/install](https://github.com/anthonydresser/sqlops-extension-sqlops/blob/master/bin/install)

Can you take a look when you have a chance?

**Comment by anthonydresser** [comment]
It's because we didn't have the release process that vscode has at the time of writing this, so we had no way of tying a semver number to a commit hash. Maybe we have that now with auto-update? I'll have to ask

**Comment by ikflc** [comment]
Hi Kevcunnane,

I have updated Azure Data Studio to 1.4.5.
I am able to see the "SQL Server 2019 (Preview)" and "Create External Table" feature on RHS of ADS, but when I click on it, it gives me an "**Error. This operation requires PolyBase to be enabled in the target server**".The Polybase is already installed in my SQL instance running SQL 2019 vNext CTP2.0.


SELECT SERVERPROPERTY ('IsPolybaseInstalled') AS IsPolybaseInstalled;  <-- returns 1

Configure Polybase with running
USE master;  
GO  
EXEC sp_configure 'show advanced option', '1';  
RECONFIGURE; 
GO
EXEC sp_configure 'hadoop connectivity', 7; 
GO 
RECONFIGURE; 
GO

Restarted SQL instance and both SQL Server PolyBase Data Movement and Polybase Engine Services are up and running. I would like to be able to define Oracle as an external table like in the following example.
https://www.sqlshack.com/enhanced-polybase-sql-2019-external-tables-for-oracle-db/

Can you please shed some light on this?

Thanks & regards,
IRene

**Comment by ikflc** [comment]
Hi Kevin,

Thanks for your reply. I have upgraded ADS to 1.4.5. I am able to see the following with my SQL 2019 CTP 2.0 instance, but not the SQL 2017 instance
[cid:image005.jpg@01D4C7AF.BC5C0B20]

When I try to create external table with my Test_Polybase database, it gives me the following error:
[cid:image006.jpg@01D4C7AF.BC5C0B20]

I double checked that “SELECT SERVERPROPERTY ('IsPolybaseInstalled') AS IsPolybaseInstalled;” returns 1
I also run  sp_configure ‘hadoop connectivity’,7;  <-- does this include Oracle as well ? Or do I need to enable other flags?
Polybase services are up and running.
[cid:image007.png@01D4C7AF.BC5C0B20]

I want to get to what shown in https://www.sqlshack.com/enhanced-polybase-sql-2019-external-tables-for-oracle-db/

Please shed some light on this.

Thanks & regards,
Irene

**Comment by kevcunnane** [comment]
@corivera can you help with polybase issue?

**Comment by ikflc** [comment]
Hi There,

Can you please shed some light on create external DB with SQL2019 using Azure Data Studio? Polybase has been enabled on the SQL2019 target server.

☹Irene
[cid:image002.jpg@01D4CABB.1FBB7120]

**Comment by ikflc** [comment]
Is there anyone out there successfully define an external datasource to an Oracle database with SQL 2019 preview?

**Comment by ikflc** [comment]
accidentally closed the comment .

**Comment by kevcunnane** [comment]
@corivera, can you please follow up here?

**Comment by corivera** [comment]
@ikflc Have you tried setting the "polybase enabled" setting? See the SQL 2019 doc here: https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-ver15#enable

**Comment by ikflc** [comment]
Hi There,

Polybase is installed and enabled as in my previous attachment. Here again,

[cid:image001.png@01D4CEBD.560A3F80]
Please shed some light on this and recommend any tracing to further diagnose would be great.

Thanks & regards,
Irene

**Comment by corivera** [comment]
The only time we throw this Polybase setup error from the wizard is if "IsPolybaseInstalled" or "polybase enabled" have a value of 0, or if the number of nodes in sys.dm_exec_compute_nodes is less than 2. What's the value_in_use for "polybase enabled" in your SQL instance?

For example: select value, value_in_use from sys.configurations where name='polybase enabled'

**Comment by ikflc** [comment]
Hi Cory,

The value is indeed “0” .
[cid:image001.png@01D4CF47.1D9CCCF0]

Thanks & regards,
Irene

**Comment by ikflc** [comment]
Hi Cory,

The value is indeed “0” .
[cid:image001.png@01D4D04A.02EADA10]

Thanks & regards,
Irene

**Comment by ikflc** [comment]
Thanks Cory,

I figure out I need the following steps after installing Polybase.

exec sp_configure @configname = 'polybase enabled', @configvalue = 1;
RECONFIGURE ;

Now, I am able to see the Oracle option in create external source.

Wonderful & thanks,
Irene

**Comment by ikflc** [comment]
The enable polybase step is in https://docs.microsoft.com/en-us/sql/relational-databases/polybase/polybase-installation?view=sql-server-2017

:)Irene
