### ISSUE TITLE
Add Application Name

### ISSUE THREAD

**Issue by felipeercolin** [microsoft/azuredatastudio#4059]
Issue Type: <b>Feature Request</b>

Please, add a feature in the connection string, the application name.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

**Comment by yualan** [comment]
Hi Felipe, can you provide additional info on what you are looking for and what scenario this helps unblock?

**Comment by Douuuglas** [comment]
Hi guys!
I have a connection string that uses application name, something like "Data Source=.\SQLEXPRESSPOS4;AttachDbFilename=|DataDirectory|\POS_data.mdf;Integrated Security=True;MultipleActiveResultSets=True;Application Name=X". Where "X" is the application name i defined in my application. Into the SQL Server instance i have a trigger that validates that application name, but in Azure Data Studio i don't see this option, so i can't use that feature.

**Comment by felipeercolin** [comment]
> Olá Felipe, você pode fornecer informações adicionais sobre o que está procurando e qual cenário isso ajuda a desbloquear?
