### ISSUE TITLE
Notebooks: Python Install Dialog can Show Up even after Python is Installed

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4068]
Improve the experience for users for reducing the number of times when the Python Installation dialog pops up.

This may be related to having multiple notebooks open at once.

**Comment by kevcunnane** [comment]
@corivera can you investigate it?

**Comment by corivera** [comment]
@chlafreniere Does this still show up for you?

**Comment by chlafreniere** [comment]
As I recall someone internally saw this during a demo, but I didn't try repro'ing it; I just created the issue 😄. I assume you couldn't repro with multiple notebooks open?

It may have been the following (I'm half guessing, but I'm half remembering... something):

- Open notebook 1. Get dialog that says that an install of python is necessary. Install dependencies
- Open notebook 2 while notebook dependencies are being installed. Dialog appears (which makes *some* sense, but we'd ideally have some state where dependencies can only be installed once at a time globally)
- Dependencies are installed from notebook 1. Going back to notebook 2, and dialog is still there.

**Comment by corivera** [comment]
There's no auto close logic for the dialog, so those behaviors would be by design.
