### ISSUE TITLE
Notebooks: Improve Install Packages with New Dialog

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#4069]
Install Packages is a little confusing and hard to find. It also requires users to run commands via the command line.

Create a simple dialog that lists a user's currently installed packages, and have a box where the user can input another package they would like installed, and install that package automatically for them.

**Comment by kevcunnane** [comment]
Adding to June. @corivera I think this is the main item, please add in
- [ ] checkboxes
If needed
