### ISSUE TITLE
Ordering of Data Explorer views inconsistent

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4071]
Steps to Reproduce: `master`

1. Sometimes Servers loads before Resource Explorer, other times it's the opposite.  (Note: Resource Explorer should be "Azure Resource Explorer" or "Azure Explorer" and should always be below Servers).

![image](https://user-images.githubusercontent.com/599935/52885315-a4cd9c00-3125-11e9-82b6-2477bf03e54b.png)

**Comment by anthonydresser** [comment]
Need a solid repro for this.

**Comment by kburtram** [comment]
I haven't seen this since the above screenshot was captured, so I'll close as no repo for now.
