### ISSUE TITLE
server groups not sorted

### ISSUE THREAD

**Issue by sivey42** [microsoft/azuredatastudio#4088]
Issue Type: <b>Bug</b>

When adding servers to a server group, the resulting group is not sorted in any order, and there is no way to re-order or sort the group. Please alphabetize the servers in the groups.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (6.13GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
mssql-db-insights|mat|0.2.2
mssql-instance-insights|mat|0.2.1
admin-pack|Mic|0.0.1
agent|Mic|0.36.0
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
sql-search|Red|0.3.0

</details>

**Comment by ben-thul** [comment]
As an alternative (or perhaps additional) implementation, allow for the server to be drag-and-dropped to a location of the user's choosing.

**Comment by yualan** [comment]
Hi @sivey42, a workaround to customize your server groups is to go to File -> Preferences -> Settings, and then you can change the order under the "datasource.connectionGroups" section. You will need to save your settings and restart.

However, we are rethinking how to make this process easier, so feel free to provide feedback on an ideal server group management experience (ie drag and drop)

**Comment by kburtram** [comment]
@sivey42 thanks for reporting this issue!  We are tracking this gap in issue https://github.com/microsoft/azuredatastudio/issues/2799.  We will address in an upcoming release.

**Comment by ben-thul** [comment]
This was marked as being addressed in the April 2020 release. I'm not seeing anything that jumps out at me for how to sort the list of servers (either automatically or manually). Am I missing something?

**Comment by Charles-Gagnon** [comment]
This wasn't closed because it was addressed - it's being tracked by https://github.com/microsoft/azuredatastudio/issues/2799.

**Comment by ben-thul** [comment]
Ah. I'm all for keeping a tidy house.

Maybe I don't understand the "Milestone - April 2020 release" labeling then. Either way, I'll track that issue. Thanks!
