### ISSUE TITLE
Linked account addition cancel

### ISSUE THREAD

**Issue by ducktin** [Microsoft/azuredatastudio#4089]
**Azure Data Studio Version:**
Version 1.5.0-insider (also checked current stable version: 1.4.5)
Commit d4ffe53dbd46829c77243e52cf06a9d6bc782f43
Date 2019-02-18T03:33:14.025Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
**Steps to Reproduce:**
1. Open "Manage linked accounts"
2. Click "Add an Account"
3. Click "Cancel"
**Result:**
Error message about adding account.
![image](https://user-images.githubusercontent.com/12184079/53015154-9e536300-344a-11e9-804b-1480219c0d58.png)
**Expected behavior:**
Operation is cancelled. No error message.

**Comment by yualan** [comment]
I was able to repro this behavior, there should not be an error message when cancelling.

**Comment by jaymegordo** [comment]
Same issue: Entry not found in cache.

Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
![Azure Add Account Failed](https://user-images.githubusercontent.com/29611875/55825639-9bc4cf80-5ac3-11e9-8c98-a293266b1461.JPG)

Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
