### ISSUE TITLE
SQL Server Import failed to start

### ISSUE THREAD

**Issue by dejan-shuki** [Microsoft/azuredatastudio#4091]
Issue Type: <b>Bug</b>

Failed to start Import: serviceError: Request error: Error

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1230 v5 @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.41GB free)|
|Process Argv|C:\Users\sunderde\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|75%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.1
agent|Mic|0.36.0
import|Mic|0.5.0
profiler|Mic|0.6.0
sql-search|Red|0.3.0

</details>

**Comment by dejan-shuki** [comment]
I was unable to start SQL Import. I am not getting very detailed msg. SQL Import is 0.5. It was installed as part of SQL Admin package.

**Comment by alanrenmsft** [comment]
@kisantia Could you please take a look?

**Comment by alanrenmsft** [comment]
@dejan-shuki are you still able to reproduce the error? I am not able to reproduce the issue with the build you used.

**Comment by alanrenmsft** [comment]
@dejan-shuki I have verified both the latest stable and insiders build, the import extension are working fine. please let me know if you still see the issue.
