### ISSUE TITLE
Multiple consecutive spaces in query results cells are condensed into one (like HTML).

### ISSUE THREAD

**Issue by consultcory** [Microsoft/azuredatastudio#4104]
Issue Type: <b>Bug</b>

Just run a query:

    SELECT 'say          what!?'

The results grid collapses the 10 spaces between the words into one when it displays. I can understand collapsing beginning or trailing spaces, but this incorrect display could be misconstrued or misinterpreted. 

Text in the results should probably be treated as preformatted text.

This is not an issue in SSMS.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.65GB (10.97GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by udeeshagautam** [comment]
Validated fix with Insiders build
