### ISSUE TITLE
Horizontal scrolling in viewlets

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#4106]
Tracking issue for how to handle horizontal scrolling in viewlets. Currently, VS Code doesn't support horizontal scrolling in viewlets, and relies on hover over or dragging the view window. Using this issue to get feedback and track related work around horizontal scrolling.

**Comment by anthonydresser** [comment]
I discovered this is actually covered by a user preference "workbench tree horizontal scrolling". We should respec this settings.

**Comment by angdesign** [comment]
Design pattern considerations: our team has seen both scroll and truncation behavior, with scroll for VS and truncation for VSCode. The ability to resize the viewlet width combined with tooltip on hover provides a minimal workaround, but respecting a user setting/preference to toggle horizontal scrolling should provide the flexibility needed.

**Comment by kburtram** [comment]
This is no longer needed since we're matching VS Code UX pattern.  Reopen if this needs reconsideration.

**Comment by alanrenmsft** [comment]
reopening the issue. I checked the setting @anthonydresser mentioned above and found 2 issues:

1. the servers viewlet does not respect this setting, i couldn't make it show the horizontal scrollbar
2. the Azure/CMS viewlets do respect the setting, but as shown in the screenshot below, the width calculation is off by maybe the width of the vertical scrollbar, the horizontal scrollbar is shown but the text is still cut by a couple letters

![image](https://user-images.githubusercontent.com/13777222/59981386-4a52b980-95b7-11e9-8ac3-7ce8aa8d8b8f.png)

**Comment by anthonydresser** [comment]
You should just open those up as separate issues. It helps with issue management and triage.
