### ISSUE TITLE
Moving server between groups shows as disconnected even while connected

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4108]
Issue Type: <b>Bug</b>

- Expand a server in the Servers view
- Move it to a different server group

Expected:
- Stays visibily connected (green dot)
Actual:
- Shows as disconnected. Can expand child nodes and it still shows as disconnected

Screenshot: After move, shows as disconnected
![image](https://user-images.githubusercontent.com/10819925/53135999-3a0bce80-3532-11e9-94d4-99ef9e43a3e1.png)

Screenshot: shows as disconnected even though child expansion works
![image](https://user-images.githubusercontent.com/10819925/53136015-42fca000-3532-11e9-9456-5ab31a5f693f.png)

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.0
server-report|Mic|0.1.4
sql-vnext|Mic|0.10.2

</details>

**Comment by kburtram** [comment]
Closing some older, low-impact issues.  Please let us know if this issue is still impacting your experience.
