### ISSUE TITLE
Restore backup - can't open Select a file... dialog when doing second restore

### ISSUE THREAD

**Issue by robert-niestroj** [Microsoft/azuredatastudio#4110]
Issue Type: <b>Bug</b>

In the restore dialog i cant open the window to select the backup file after a first successful backup. Pressing the [...] button does not open the file select window. I have to close ADS and open again. On first restore it works. Disabling extensions did not work either.

Steps:
1. Open ADS
2. Connect to local SQL 2012
3. Right click DB
4. Select Restore
5. Select Restore from: backup file
6. Select the backup file
7. Go to Options tab and check Overwrite ... and Close connections...
8. Click Restore
9. The backup sucessfully restores
10. Redo steps 3-6, Step 6 fails, the Select a File... dialog does not open.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (5.31GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.5.0
profiler|Mic|0.6.0

</details>

**Comment by kburtram** [comment]
This appears to be fixed in the latest insiders build.  Please let me know if you continue to see this problem with a current daily build or in the upcoming March release.

**Comment by robert-niestroj** [comment]
Works OK in march release
