### ISSUE TITLE
How to see which port Azure is using?

### ISSUE THREAD

**Issue by JoshFialkoff** [microsoft/azuredatastudio#4111]
Issue Type: <b>Question</b>

I am trying to troubleshoot a connection with another service. I am trying to make sure Azure and the other service (Zapier.com) are connecting on the same port. But I don't see a way to find out which port Azure is using

Azure Data Studio version: Azure Data Studio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:17:16.459Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4578U CPU @ 3.00GHz (4 x 3000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kevcunnane** [comment]
Can you provide more information? What are the steps when using Azure Data Studio that you need help with? SQL Server / Azure SQL DB connections default to port 1433 if that helps

**Comment by JoshFialkoff** [comment]
I am trying to confirm that it's port 1433 because the same credentials are
not working for another service. Ideally, I would like to be able to send
the other service a screenshot showing that I am able to successfully
connect via port 1433.
I will send them this email and see if that helps, but it might be good to
give people the ability to see, to confirm, what port is being used.
Thanks for your help!

**Comment by kburtram** [comment]
@JoshFialkoff as a workaround you can append the `,1433` to the connection to specify a particular port.  The connection will display the port in the Servers viewlet as below if the connection is successful.

![image](https://user-images.githubusercontent.com/599935/53365449-1c55b500-38f6-11e9-8503-7f188258f956.png)

**Comment by JoshFialkoff** [comment]
Great! I was trying to find the syntax in the documentation. It would be
great if this could be added.

**Comment by cheenamalhotra** [comment]
Linking SqlClient docs here for quick reference: [SqlConnectionStringBuilder.DataSource](https://docs.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient.sqlconnectionstringbuilder.datasource?view=sqlclient-dotnet-standard-5.0#remarks).
This can be referenced for ADS documentation too.

**Comment by cheenamalhotra** [comment]
Closing issue as answered.
