### ISSUE TITLE
3 notebook tests are failing

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#4113]
There are 3 tests in `cell.test.ts` that aren't running in master right now because of a bug but that will run after the VS Code merge is complete and which fail when they run. I'll disable them for the merge with a comment linking to this issue.

The tests were passing until I pulled down last night's changes so I think it was introduced by #4090

**Comment by corivera** [comment]
@kevcunnane Could this be related to your cell language changes? https://github.com/Microsoft/azuredatastudio/commit/1f501f45536ab335c6586332083239575a75a8a5

**Comment by kevcunnane** [comment]
I won’t know without seeing which tests fail. What ones and why? I can check on Monday if needed

**Comment by corivera** [comment]
Looks to be some tests that set the cell language based on languageInfo inputs: https://github.com/Microsoft/azuredatastudio/blob/master/src/sqltest/parts/notebook/model/cell.test.ts#L147

**Comment by chlafreniere** [comment]
I took a look at this, and this isn't high pri for April. Pushing out to Planning.
