### ISSUE TITLE
Idle Connection Closes

### ISSUE THREAD

**Issue by aarongiust** [microsoft/azuredatastudio#4114]
Issue Type: <b>Bug</b>

It seems that connections will close for query windows that sit idle.  This is fine if it could recover appropriately but doesn't.  If you try to execute the query, it will tell you that the connection is closed.  You can execute the query again and it will not come back with an error, but gets hung up and will not respond correctly until you close everything out.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.81GB (22.97GB free)|
|Process Argv|C:\Users\agiust\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@aarongiust are there any additional repro steps that may help isolate this problem?

**Comment by kburtram** [comment]
The current driver has Connection Resiliency and TCP KEEPALIVE features to help in this scenario.  Please let us know if you're still seeing this problem on current builds.
