### ISSUE TITLE
Use VS Code's new menu contributions

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#4117]
VS Code changed how they create the app's menu but I just brought over the old version of the menu in the 1.30.1 merge (see src/sql/workbench/electron-browser/menus.ts). We should look at whether it's worth doing it the way they do

**Comment by yualan** [comment]
What were the main differences they implemented? Are there differences to the end-user or is this mostly implementation?

**Comment by anthonydresser** [comment]
Its mainly implementation, but the main blocker from adopting it is we don't support custom menu bars

**Comment by kburtram** [comment]
Closing older issues.  Let's address this in the context of some funded feature work.
