### ISSUE TITLE
Notebooks: Converge on SlickGrid plugins with Query Editor

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#4119]
The SlickGrid used in notebooks lacks all of the plugins that the grid in the query editor has.

We need to come up with a plan where we can easily share plugins,  and where, when a new feature is added to the grid in the query editor, we can very easily get that feature to light up in notebooks as well.

**Comment by kevcunnane** [comment]
Moving to April

**Comment by chlafreniere** [comment]
This has since been completed.
