### ISSUE TITLE
Software lost after every logoff from computer

### ISSUE THREAD

**Issue by alexhass** [microsoft/azuredatastudio#4127]
- Azure Data Studio Version: Every per user installer

Steps to Reproduce:

0. Hot Desk environment with roaming profiles.
1. Install per user setup to default folder C:\Users\%username%\AppData\Local\Programs\Azure Data Studio
2. Logoff
3. Logon
4. AppData\Local has been whiped from disk as it is excluded from roaming via GPOs. This is a default recommended by MS for roaming profiles.

Solution:
Never install software to local app data as it does not roam for size reasons. AppData\Roaming will work fine. In AppData\Local only files should be safed that can get lost on logoff.

**Comment by kburtram** [comment]
@alexhass in this scenario you may prefer to use the xcopy ZIP installation available at https://go.microsoft.com/fwlink/?linkid=2072354, or the system-wide installer if you have admin permissions on the machine.

**Comment by alexhass** [comment]
How about fixing the bug? Installing software to local app data is always wrong. Also if a system wide exe installer exists.

**Comment by kburtram** [comment]
@alexhass thanks for opening the issue.  The per-user acquisition experience is picked-up from our upstream VS Code dependency (see https://github.com/Microsoft/vscode/issues/534).  

We'll evaluate this scenario to understand if there is a particular impact for ADS that isn't applicable to VS Code.  Otherwise, this would likely be something that we'd expect to be fixed upstream.  FWIW, I wasn't able to find a similar issue on their repo.

**Comment by alexhass** [comment]
The problem is the project manager of vscode. He has not understood the bug and simply closed the case and refused to understand after further explained. Maybe you are more expierenced with windows and can explain him that this need to be fixed. The argument that this need to be fixed upstream means it may never fixed as the project manager has no clue about setups.

**Comment by kburtram** [comment]
@alexhass thanks for following up!  I've changed the label to "Bug" to reflect your comment.  The installer behavior is coming from upstream VS Code design.  Please log this bug on our upstream repro and if they change this behavior we'll pick it up in ADS in a future source code refresh.
