### ISSUE TITLE
Command + "/"

### ISSUE THREAD

**Issue by ericdiliu** [Microsoft/azuredatastudio#4128]
Issue Type: <b>Feature Request</b>

Command + "/" to comment entire line doesn't work.

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.2.0

**Comment by yualan** [comment]
Hi Eric, you can set a custom keyboard shortcut to comment an entire line.

To modify keyboard shortcuts, go to File, then Preferences, then Keyboard Shortcuts. Search for A**dd Line Comment** and click the pencil to modify to the keyboard shortcut you prefer.

![image](https://user-images.githubusercontent.com/30873802/53272987-9c3a1000-36a7-11e9-82a2-01bebb3b7883.png)

Let us know if this works for you.

**Comment by kburtram** [comment]
@ericdiliu please try `Ctrl-K Ctrl-C` (or customize as @yualan mentions) for the Comment Line feature.  Thanks!
