### ISSUE TITLE
Insiders build - notebooks broken due to missing module

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4130]
Issue Type: <b>Bug</b>
@corivera  please work on this, caused by your checkin
Download latest insiders, start and do New Notebook. It'll fail. Open developer tools, will see:

[Extension Host] Can't load string bundle for /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/out/jupyter/jupyterController.js (at Object.loadMessageBundle (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/node_modules/vscode-nls/lib/main.js:133:21))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280
/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 [Extension Host] Can't load string bundle for /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/out/common/localizedConstants.js (at Object.loadMessageBundle (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/extensions/notebook/node_modules/vscode-nls/lib/main.js:133:21))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280

[Extension Host] Activating extension 'Microsoft.notebook' failed: Cannot find module 'request'. (at Object.showMessage (/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:53854:41))
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280
/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 [Extension Host] Activating extension `Microsoft.notebook` failed:  Cannot find module 'request' (at /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:31357:25)
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ /Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280
/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 

Azure Data Studio version: Azure Data Studio 1.5.0-insider (cc97198fe4b6f5b715addbda889e06900af8e08b, 2019-02-21T03:10:36.976Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|/Users/kevcunnane/Downloads/Insiders/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_1233197|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
server-report|Mic|0.1.4
sql-vnext|Mic|0.10.2

</details>

**Comment by anthonydresser** [comment]
I remember @YurongHe had this issue before, I'm not sure what they did to solve it. I believe @kburtram was helping.
