### ISSUE TITLE
Azure Resource Explorer sidebar icon is missing

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#4139]
Issue Type: <b>Bug</b>

1. Open a packaged build
2. The Azure Resource Explorer's sidebar icon will be blank

![Azure data studio sidebar showing a blank space where the Azure Resource Explorer icon should be](https://user-images.githubusercontent.com/3758704/53277524-276fd180-36b9-11e9-8839-1a2bc3e758f5.png)

Azure Data Studio version: Azure Data Studio 1.5.0-insider (ad46319c4469f38f35a5279e8c5fe9e8e52f13f6, 2019-02-22T22:43:26.305Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
sql-vnext|Mic|0.9.3
whoisactive|Mic|0.1.1

</details>

**Comment by kburtram** [comment]
I think this is related to the data explorer work in-progress, particularly when switching between dev and packaged builds.  In any case, the Azure viewlet is planned to be removed from the product in the March release.

**Comment by anthonydresser** [comment]
Should be fixed since this was removed
