### ISSUE TITLE
Failed to connect to the server while trying to list databases (Azure SQL)

### ISSUE THREAD

**Issue by UnitedColorsOfNerd** [microsoft/azuredatastudio#414]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:25:40.652Z)
- OS Version: Linux x64 4.4.0-104-generic
---

I get a failed connection error when I try to list the databases of the server

The error appears when I try to use this dropdown:

![cropped3](https://user-images.githubusercontent.com/20880466/34472087-df90f820-ef61-11e7-8b03-ee4b1baf48c1.png)

But the databases are visible here:

![cropped2](https://user-images.githubusercontent.com/20880466/34472095-188dfca4-ef62-11e7-9300-242b49f249c3.png)

and here:

![cropped1](https://user-images.githubusercontent.com/20880466/34472133-550e0d4e-ef63-11e7-9adc-b6debe9b4010.png)

**Comment by kburtram** [comment]
@UnitedColorsOfNerd this is likely related to the Object Explorer node population query timing out for some reason.  We'll look into how to make this more robust, perhaps with retries or longer timeouts.  In the meantime, I suspect that running "Refresh" on the OE node should populate the node correctly.

**Comment by hikirsch** [comment]
we have this problem too, i created a new user in the database but i'm unable to expand the left side, however, i still see a list of databases in the center. if i double click on one of the databases, i do see a list of tables. i can also create a new sql query and that works. so only the left side for us wont load.

**Comment by NalJensVB** [comment]
We are experiencing the same issue here.

**Comment by jschrap** [comment]
We have a similar issue with one user. 
In the right pane (servers) the server shows status as connected, but when you click open Databases below it, it shows: "Failed to connect to server".
We can set up and save the individual db connections. 
On SSMS, this functionality works fine for the user.  And other users don't have this issue. Any idea what it could be and/or how we can fix it?

We're using Version 1.4.5, on Windows 10 laptops.
![azuredatastudio-error-ev](https://user-images.githubusercontent.com/17762353/53556896-1a356580-3b45-11e9-9127-2131bf3fb755.JPG)

**Comment by kburtram** [comment]
We've fixed several OE reliability issues since this issue was created.  Please let us know if you're still seeing this issue, or if there are additional repro steps that could help identify the specific connectivity issue involved here.  Thanks!
