### ISSUE TITLE
Insider Build - DacFx commands fail to start

### ISSUE THREAD

**Issue by udeeshagautam** [Microsoft/azuredatastudio#4140]
Issue Type: <b>Bug</b>

Import Extension is not able to start any command. Looks like one of its dependency modules (htmlparser2) is missing post VS code merge.

Error:
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Activating extension 'Microsoft.import' failed: Cannot find module 'htmlparser2'.
Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280

Error:
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Error: command 'dacFx.start' not found
    at CommandService._tryExecuteCommand (workbench.main.js:198573)
    at workbench.main.js:198567
    at Promise_ctor.CompletePromise_then [as then] (workbench.main.js:17955)
    at CommandService.executeCommand (workbench.main.js:198567)
    at MenuItemAction.ExecuteCommandAction.run (workbench.main.js:98479)
    at MenuItemAction.run (workbench.main.js:98522)
    at workbench.main.js:195660
    at Promise_ctor.CompletePromise_done [as done] (workbench.main.js:17913)
    at Object.notifySuccess [as _notify] (workbench.main.js:17569)
    at Object.enter (workbench.main.js:17235)
    at Promise_ctor._run (workbench.main.js:17457)
    at Promise_ctor._completed (workbench.main.js:17425)

Azure Data Studio version: azuredatastudio 1.5.0-insider (cc97198fe4b6f5b715addbda889e06900af8e08b, 2019-02-21T03:23:49.599Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (46.18GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.6.0

</details>

**Comment by alanrenmsft** [comment]
@kisantia Could you please take a look? maybe related to #4091?
