### ISSUE TITLE
Notebooks: grid with no rows needs better min height

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4151]
See screenshot below. Should have sensible min height or the grid looks messed up.
![image](https://user-images.githubusercontent.com/10819925/53280230-a4f10d00-36cc-11e9-85b2-b8f1bfaa6439.png)

@smithaBharadwaj what would you suggest?

**Comment by smithaBharadwaj** [comment]
At min we should show 1 empty row.
