### ISSUE TITLE
query plan not rendering

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#4152]
- Azure Data Studio Version:
latest release with vscode merge

Steps to Reproduce:
1. open a query editor and type in a query, e.g. select * from sys.tables
2. click explain button
3. the query plan is rendered properly
4. click explain again

expected: query plan renders correctly

actual: empty query plan area

![image](https://user-images.githubusercontent.com/13777222/53283197-74729880-36f7-11e9-8d19-2e689709107d.png)

**Comment by anthonydresser** [comment]
Do you have a better repro for this?
![image](https://user-images.githubusercontent.com/4324725/53910985-148ac480-400a-11e9-9a28-0371804120d5.png)

**Comment by anthonydresser** [comment]
I'm going to close this as no repro
