### ISSUE TITLE
messages pane is not visible when collapsed

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#4154]
- Azure Data Studio Version:

Steps to Reproduce:

1. run a query that will return more results than a screen can fit
2. collapse the messages pane

expected:
the messages pane's header is visible at the bottom of the screen

actual:
can't see the messages pane even when the results pane has been scrolled to the bottom

![image](https://user-images.githubusercontent.com/13777222/53283291-fc0cd700-36f8-11e9-83da-f802e4527d9d.png)

**Comment by anthonydresser** [comment]
I'm pretty sure this is caused by the custom menu bar, can you verify?

**Comment by alanrenmsft** [comment]
@anthonydresser could you please provide more info?

**Comment by anthonydresser** [comment]
Do you have the custom menu bar active in preferences? If so can you disable it and see if this repros?

**Comment by alanrenmsft** [comment]
I can only see these settings in the preferences related to menu, but it doesn't help when turned off.

![image](https://user-images.githubusercontent.com/13777222/53283461-b271bb80-36fb-11e9-96b3-ea73c6deba56.png)

**Comment by anthonydresser** [comment]
do you have a better repro for this?
![image](https://user-images.githubusercontent.com/4324725/53910887-d55c7380-4009-11e9-993d-c9e0df599dc5.png)

**Comment by alanrenmsft** [comment]
I can no longer reproduce the issue, i tried both the latest master dev mode and insider build. closing...
