### ISSUE TITLE
Unable to link account

### ISSUE THREAD

**Issue by vainolo** [Microsoft/azuredatastudio#4157]
Issue Type: <b>Bug</b>

Use the "Add Account" functionality both by creating a new DB an also from the Azure resource explorer. In both cases it failed

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (2.45GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-dw|Mic|0.0.1

</details>

**Comment by kburtram** [comment]
@vainolo could you please provide any additional info on what's failing?  Are you getting any error messages in the `Help->Toggle Developer Tools` console?  Thanks!

**Comment by vainolo** [comment]
HI @kburtram - it seems that the problem was coming from AAD and not from Data Studio. I was part of an external directory that caused trouble logging into some applications. Yesterday I was removed from that directory and now this is working.
Thanks!
