### ISSUE TITLE
Add a pencil icon/view icon to markdown - Make edit/view user friendly

### ISSUE THREAD

**Issue by rajmusuku** [microsoft/azuredatastudio#4160]
Markdown editing 
It’s not visually obvious that to edit a markdown cell you need to d-click it.  
Can we add an option to the … button at a minimum if not something more obvious?  
Didn’t we use to have a pencil icon/view icon toggle button?

**Comment by chlafreniere** [comment]
We have since implemented this in the markdown toolbar:

![image](https://user-images.githubusercontent.com/40371649/102262602-30eaaf00-3ec8-11eb-964d-9c6ac9a3ab02.png)

Closing this issue.
