### ISSUE TITLE
Docker extension error: Cannot read property 'registerDebugConfigurationProvider' 

### ISSUE THREAD

**Issue by SQLvariant** [Microsoft/azuredatastudio#4162]
Issue Type: <b>Bug</b>

Repro steps:
Pretty simple to repro, just download the Docker .VSIX file ( https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker ) and load it up into ADS.

Please let me know if there's any more information I can provide?
( Probably fastest to just ping me on twitter: @SQLvariant )

Action: docker.activate
Error type: TypeError
Error Message: Cannot read property 'registerDebugConfigurationProvider' of undefined
Version: 0.5.2
OS: win32

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (1.21GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
sql-vnext|Mic|0.10.2
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.5.2
sql-search|Red|0.3.0

</details>

**Comment by kburtram** [comment]
@SQLvariant this is same error I expect to see when getting the PowerShell extension working (per issue https://github.com/Microsoft/azuredatastudio/issues/3929).  Once PS loads, I expect Docker will work too.  I'll test both.

**Comment by SQLvariant** [comment]
OK, thanks for having a look.  Since the error message I received was different, I couldn't tell if it was the same.

**Comment by kburtram** [comment]
Docker extension should be working with the latest build.  Please let me know if issues persist.
