### ISSUE TITLE
missing grid for the last column displayed in output area

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4163]
Issue Type: <b>Bug</b>

- open a sql notebook
- run query select * from sys.databases
- results look like
![image](https://user-images.githubusercontent.com/43652751/53371742-e9b3b880-3905-11e9-9c64-cfbcfd9da4ee.png)
 
we can see the grid is not drawn at the end of the window. If we move the scroll bar at the bottom, the grid will be added.

Could we display the grid for all visible columns?

Note:
this is from saved notebook. I just executed the query against a valid connection. Look like no such problem.

Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (171.87GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.3

</details>

**Comment by rajmusuku** [comment]
Not able to repro this issue. Talked to Yurong as well. Closing it.

**Comment by YurongHe** [comment]
Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

Repro on the version. query select * from sys.database_files

![image](https://user-images.githubusercontent.com/43652751/53600984-dbf96f80-3b5f-11e9-94b9-724bafabf62e.png)

**Comment by chlafreniere** [comment]
I can't repro for now. @YurongHe do you have a good repro still?

**Comment by chlafreniere** [comment]
Moving to April since I cannot repro.

**Comment by kburtram** [comment]
Closing as no repro.  Please reactive if the issue persists.
