### ISSUE TITLE
Execution count is cleared after click "Run button" when no valid connection

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4166]
Issue Type: <b>Bug</b>

1. Open a SQL notebook
2. Make sure no valid connection
Before run the cell 
![image](https://user-images.githubusercontent.com/43652751/53373511-8a0bdc00-390a-11e9-9299-696c692206b5.png)

3. click "Run button"
![image](https://user-images.githubusercontent.com/43652751/53373589-b293d600-390a-11e9-8bdc-a279b364706b.png)

Expected:
The execution count is not change and output is preserved.

Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (171.72GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.3

</details>

**Comment by chlafreniere** [comment]
This has been fixed by #4960.
