### ISSUE TITLE
Execution count behavior

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4168]
- Azure Data Studio Version:

Steps to Reproduce:

1. Right now I can see when we execute the cell, the execute count saved in the notebook will be reset to 1.  This looks correct to me.
2. The questions are:

- Sql change connection to a different server
- Python changes Kernel

I saw Jupyter notebook resets it when switches kernel
https://stackoverflow.com/questions/44559471/how-to-reset-the-number-inside-in-from-jupyter-notebook-cell?rq=1

**Comment by kevcunnane** [comment]
Can you clarify the question? The Jupyter docs state this is a monotonically increasing counter. It’s for each kernel instance so on changing kernel, gets reset (old one is closed). I don’t think connection change has same semantics so we should be consistent with Jupyter. 

So - is there a bug given this feedback?

**Comment by chlafreniere** [comment]
This is by design.
