### ISSUE TITLE
Incorrect product name when disabling extension

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4172]
Issue Type: <b>Bug</b>

When disabling an extension, the on screen text reads "Please reload Visual Studio Code to complete the disabling of this extension"

![image](https://user-images.githubusercontent.com/8250560/53377143-c5f86e80-3915-11e9-8318-0eccbcd6fa5e.png)

Azure Data Studio version: azuredatastudio 1.5.0-insider (c831596e0258aceca2ea4647d2fa2420860f6217, 2019-02-25T19:57:08.953Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (2.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by rajmusuku** [comment]
This might be due to extension not being loaded in ADS correctly.

**Comment by angdesign** [comment]
Likely related, but also seeing this on initial install as well. 
![screen shot 2019-02-26 at 2 46 15 pm](https://user-images.githubusercontent.com/29785331/53452136-59dd3f80-39d5-11e9-80b9-3354245c600d.png)

Azure Data Studio version 1.5.0-insider
OS version: MacOS 10.14.3

**Comment by alanrenmsft** [comment]
1. for disable scenario, the issue has been fixed
![image](https://user-images.githubusercontent.com/13777222/56759767-9667b600-674e-11e9-98f4-b9fb91b3f941.png)

2. for install scenario, latest ads no longer requires a reload
![image](https://user-images.githubusercontent.com/13777222/56760016-1a21a280-674f-11e9-91a9-8e16feec2798.png)


closing the issue.
