### ISSUE TITLE
Dup connections name in AttachTo

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4173]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a sql notebook
2. Add a sql connection to big data cluster master intance
3. Switch kernels
4. Set Kernel to SQL, AttachTo has dup connections created in 2.
![image](https://user-images.githubusercontent.com/43652751/53377280-47e89780-3916-11e9-803c-978d81583335.png)

**Comment by chlafreniere** [comment]
@YurongHe I can't repro this. Do you still have a consistent repro?

**Comment by chlafreniere** [comment]
We will revisit this in the May timeframe when we close on an updated connection experience.

**Comment by chlafreniere** [comment]
This no longer repros.
