### ISSUE TITLE
Error starting notebook - could not read property "replace" of null

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4174]
Issue Type: <b>Bug</b>

I am receiving this error every time I open a notebook.

"Error starting notebook - could not read property "replace" of null"

![image](https://user-images.githubusercontent.com/8250560/53377371-9d24a900-3916-11e9-94c2-6987898badd6.png)

The notebook appears to work fine.

![image](https://user-images.githubusercontent.com/8250560/53377253-356e5e00-3916-11e9-8743-7322a9ab6458.png)

Azure Data Studio version: azuredatastudio 1.5.0-insider (c831596e0258aceca2ea4647d2fa2420860f6217, 2019-02-25T19:57:08.953Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.84GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.4
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kevcunnane** [comment]
This is coming from Jupyter extension code if I had to guess. Probs my why SQL works but you see this error. Is this for a specific notebook? Can you mail the team all the console output and the notebook if available? Thanks!

**Comment by vickyharp** [comment]
Behavior seems to have changed to #4215 and goes away if I run as administrator.

**Comment by rajmusuku** [comment]
Fixed
