### ISSUE TITLE
Execution count is wrong for the new cell added before cell/after

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4175]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a SQL notebook
2. Execute a cell multiple times
3. Add a new cell above the cell just executed in step 2
4. Execute a query in the cell added in step 3.
5. We can see the execution count is increased based on the count number below it. For example in the attached screen. The execution count is 6 even though we only run it only once.

![image](https://user-images.githubusercontent.com/43652751/53377568-53888e00-3917-11e9-8bcb-ec58d628bc0a.png)

**Comment by rajmusuku** [comment]
By design
