### ISSUE TITLE
Can't run PySpark3 cell when connect to big data cluster master instance

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4178]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a SQL Notebook
2. Connect to big data cluster master
3. Add  code cell, run TSQL query
4. Switch Kernel to PySpark3-> Add code cell -> Input print "1"-> Select "Run button" 
   Got notification: The session for this notebook will start momentarily
   But no results. Here is the screenshot
![image](https://user-images.githubusercontent.com/43652751/53378391-44570f80-391a-11e9-97dc-33aff45170f3.png)

**Comment by rajmusuku** [comment]
Closing as duplicate
