### ISSUE TITLE
Starting local notebooks server failed with error 

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4183]
Open a notebook and observe the error 

Starting local notebooks server failed with error..

![image](https://user-images.githubusercontent.com/44002319/53379810-ee856600-391f-11e9-8a1b-2c31d21632e5.png)

**Comment by kevcunnane** [comment]
Raj, can you give more info? Is this only on windows? Is it a path issue or Jupyter config? What is shown in the output channel and does manually running the Jupyter start command from the command line work or fail?

**Comment by rajmusuku** [comment]
It's not the Path issue since python is run correctly. Launched 'jupyter notebook' from anaconda and now I am not able to repro. I saw it only on windows. Let me uninstall - reinstall python and see.
