### ISSUE TITLE
Syntax errors in Output window when opening a notebook

### ISSUE THREAD

**Issue by rajmusuku** [microsoft/azuredatastudio#4184]
Open notebooks and see 'problems' section of output window. Bunch of syntax errors are shown up from notebook editors. When you click on them, will disappear. I think, its probably related to HistoryService issue

![image](https://user-images.githubusercontent.com/44002319/53380095-01e50100-3921-11e9-8024-18da1c8273c1.png)

**Comment by chlafreniere** [comment]
Tracked by #7545. Closing as dupe.
