### ISSUE TITLE
Notebook: Opening new notebook on a database does not open in that database context.

### ISSUE THREAD

**Issue by MaddyDev** [Microsoft/azuredatastudio#4186]
- Azure Data Studio Version: 1.5.0

Steps to Reproduce:

1. Right click on a database that's connected from the Servers and click on 'New Notebook'. It should open the notebook attached to that server but instead it defaults to the first available online server.

**Comment by YurongHe** [comment]
select db->if Select file menu->New Notebook, the db is showed in attach to.
               ->if Select server->New notebook, the server connection title will be in attach to.

This is the same as New Query.
