### ISSUE TITLE
Setting "window.title" does not work

### ISSUE THREAD

**Issue by aktenkundig** [microsoft/azuredatastudio#4189]
- Azure Data Studio Version: 1.4.5

I just want to see where the file opened is located. It just is not possible. No hover on tab, not in tab, not in window tile. At least here it is configurable. But it just won't work.

Steps to Reproduce:

1. Open folder and open any file within.

2. Change setting to

${rootPath/folderPath/rootName/folderName}

No difference, it won't show the location within folder.

3. Change setting to 

${activeEditorShort/Medium/Long}

No difference, it won't show the location within folder.

**Comment by kburtram** [comment]
The `window.title` setting appears to be working on the current build.  Please let us know if you're still impacted by this issue.

![image](https://user-images.githubusercontent.com/599935/129642926-ab056a2e-38f8-442c-8864-45632ada36fc.png)
