### ISSUE TITLE
Create a icon theming scheme

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4193]
~~I'll need to look again at how to load in OE icons for nodes in extended views. VSCode changes the type of the icons which brakes the method I was doing before.~~

We need to come up with a plan for supporting icon themes and a way to standardize ux around database objects.

**Comment by anthonydresser** [comment]
My current plan for solving this generically (also bring our server tree and our extension trees inline) is to add something like what vscode has for resources; a resource label class that know how to render a URI generically. https://github.com/Microsoft/azuredatastudio/blob/master/src/vs/workbench/browser/labels.ts#L37

We could also use this as a chance to better integrate into the icon themeing service and allow extension icon themes to change the look of our OE items.

@kburtram @alanrenmsft @yualan

**Comment by YurongHe** [comment]
@anthonydresser will this add different icons for Azure SQL DB, standalone and big data cluster?

**Comment by anthonydresser** [comment]
No, my previous comment was a little optimistic, we don't have the time to implement a proper icon themeing scheme. I'll change the title and labels to make this a larger feature.
