### ISSUE TITLE
Data Explorer Actions

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4194]
Data Explorer Views (internal and extensions) should be contributable for actions.

**Comment by anthonydresser** [comment]
My current plan for implementing contributable actions is by added a new menu contribution point, `dataExplorer/context`.

This will apply to any tree view in the data Explorer viewlet; the built in server view and every extension view that is put in the dataExplorer.

This means there are 2 ways for extensions to add actions to a viewlet tree, the existing vscode method 
`view/item/context` which is what they expect extensions to use to contribute to their own tree.
Ex:
````json
{
    "command": "azure.resource.refresh",
    "when": "viewItem =~ /^azure\\.resource\\.itemType\\.(?:account|subscription|databaseContainer|databaseServerContainer)$/",
    "group": "inline"
},
````

And this new method `dataExplorer/context` which is basically a way for extension to generically contribute.

We need to make sure we expose the same context keys for the `when` statement that we already provide in the servers tree.

The one downside to this is that we will now have 3 contribution points `view/item/context` which is vscodes, `objectExplorer/item/context` which is only used by the built in servers view tree, and `dataExplorer/context` which will be used in the entire Data Explorer. There is probably some work we could do to combine `objectExplorer/item/context` and `dataExplorer/context`, but I think that can be future work as to not brake current extensions expectation of how to use `objectExplorer/item/context`.

@kburtram @yualan @alanrenmsft

**Comment by kburtram** [comment]
Closing older engineering-focused issues.  Thanks!
