### ISSUE TITLE
git diff viewer shows file encoding error

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4198]
- Azure Data Studio Version: 1.5.0 `master`

Steps to Reproduce:

1. Open a folder under git SCC
2. Edit a text file
3. View file diff

Expected: Diff appears correctly

Actual: File encoding error when viewing diff.  If the file is closed then the diff works properly.  This is a change in behavior since the VS Code 1.30 code merge.

![image](https://user-images.githubusercontent.com/599935/53437989-a7e14b80-39b3-11e9-9b85-c294abc57b74.png)

**Comment by Charles-Gagnon** [comment]
Not able to repro this on latest insiders build

Version: 1.5.1-insider (user setup)
Commit: 036ffe595ae711a08e8554f6f7a6475945221eea
Date: 2019-03-08T03:35:22.775Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/28519865/54039138-04dcbe80-4177-11e9-81eb-b5227a8a54b2.png)
