### ISSUE TITLE
Connection to on-premise (in-house) database not working

### ISSUE THREAD

**Issue by ericbrunner** [microsoft/azuredatastudio#421]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. Select Microssoft SQL Server
2. Enter Server name
3. Choose Windows Authentication
4. Hit connect

The result is show in the screenshot below. MSOS not working. SSMMS working:

![image](https://user-images.githubusercontent.com/6480047/34515001-5d648d66-f070-11e7-9cac-174d24648fd0.png)

**Comment by kburtram** [comment]
@ericbrunner we are unable to repro this issue.  Is there any additional server or environment details you could provide?  Also, please try the July release which several connection related fixes.

**Comment by ericbrunner** [comment]
@kburtram You can close that issue. Didn't occur again in the most recent stable version.

PS: It doesn't help when you guys reply after 7 MONTH! Not personally ment. Please excalate that inside Microsoft.
