### ISSUE TITLE
Unable to add Code/Text cell due to this.inErrorState

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4211]
We have two different client sessions, when there is an error from Jupyter session we are not able to create code/text cells although SQL kernel is enabled. Two things should be done here.

1. When there is an error from any client session, notify the error details
2. If the error is related to only single client session, the other session should work fine. 

![image](https://user-images.githubusercontent.com/44002319/53457543-987bf580-39e7-11e9-945f-f0ce301f41be.png)

**Comment by chlafreniere** [comment]
No longer an issue because we don't have multiple client sessions.
