### ISSUE TITLE
Change connect doesn't update tab colour

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#4216]
Issue Type: <b>Bug</b>

I have setup the tab colours to follow the colour of the server groups. 
When I start a query on one server in my production group I get a red tab as expected. 
When I then use the "Change connection" feature to change that connection to my test server, which is in a different server group with a green colour, my tab stays red instead of changing to green.

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4308U CPU @ 2.80GHz (4 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.39GB free)|
|Process Argv|/Applications/Azure Data Studio.app/Contents/MacOS/Electron|
|Screen Reader|no|
|VM|22%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by cheenamalhotra** [comment]
Closing as this isn't reproducible anymore.
Tab color changes with server group selected when changing connection.
