### ISSUE TITLE
Momento warning in output

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4226]
- Azure Data Studio Version: master 291f591af3421899481725016ccb08a40424c036

I've started seeing the following warning in the debug console after closing ads. 
```
WARN Unsupported write (store) access after close (key: memento/ConnectionManagement)
WARN Unsupported write (store) access after close (key: memento/AccountManagement)
WARN Unsupported write (store) access after close (key: memento/capabilities)
```

Looks like our momento writes might not be actually writing.

**Comment by kburtram** [comment]
I no longer see this.  Please reactive if the issue persists.
