### ISSUE TITLE
Connection dialog doesn't show 'sql big data server' connection type

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4227]
1. Open a notebook
2. Select any spark kernel -> attach To -> Add new connection
3. Connection dialog doesn't have option to select 'SQL Bigdata Server' connection type. It only has 'SQL Server'

Is it intentional due to Unified Connection implementation ? Bug?

![image](https://user-images.githubusercontent.com/44002319/53540093-fdf3e300-3ac8-11e9-98ce-e672161629ad.png)

**Comment by kevcunnane** [comment]
Silly question - is the SQL Server 2019 extension installed?

**Comment by rajmusuku** [comment]
@kevcunnane : Nope, but we did get rid of it with our notebooks built in extension. Should we still install the extension ?

**Comment by chlafreniere** [comment]
The other option shows up when the extension is installed. Closing this issue.
