### ISSUE TITLE
support for local R kernel

### ISSUE THREAD

**Issue by lgongmsft** [microsoft/azuredatastudio#4228]
We are integrating [sparklyr](https://spark.rstudio.com/) into the [big data cluster](https://docs.microsoft.com/en-us/sql/big-data-cluster/big-data-cluster-overview?view=sqlallproducts-allversions).  It works with ADS with the SparkR kernel except that it creates two spark applications: one created by sparklyr when it connects to spark and the other created by the SparkR kernel automatically when the kernel starts.  Since the spark application created by the SparkR kernel is never used in such case, it is not only inefficient but also might cause confusion to users.

One solution is for ADS to support local R kernel so that we can use the [Livy connection provided by sparklyr](https://spark.rstudio.com/#connecting-through-livy) to connect to a big data cluster similar to what users would do with [RStudio IDE](https://spark.rstudio.com/#rstudio-ide).  In this way, there will be just one Spark application (the one started by sparklyr) as we are using the local R kernel instead of the SparkR kernel.

I found that I can use the [IRkernel](https://github.com/IRkernel/IRkernel) with ADS by doing the following with an existing local R installation:
```
install.packages('IRkernel')
IRkernel::installspec()  # to register the kernel in the current R installation
```
However it seems that I can put only one line of R code in each cell, otherwise I will get an error, e.g., 

```
ls()
.libPaths()
 ```
```
Error in parse(text = x, srcfile = src): <text>:1:5: unexpected input
1: ls()
        ^
Traceback:
```

So I wonder if it is possible for ADS to support local R kernel natively.  Since ADS already supports [Python kernel](https://docs.microsoft.com/en-us/sql/big-data-cluster/notebooks-guidance?view=sqlallproducts-allversions#supported-kernels-and-attach-to-context) for local development, supporting local R kernel seems to be a natural next step and nice addition to ADS.  Moreover, sparklyr is quite [popular](https://eddjberry.netlify.com/post/2017-12-05-sparkr-vs-sparklyr/) among the R users working with Spark, I believe making ADS have better support for it will certainly be very welcoming feature.

**Comment by amthomas46** [comment]
I want support for local R kernel as well so I can do SQL ML Services stuff with R in notebooks locally!

Currently, I use RStudio, but in a perfect world, I could use the ADS Notebooks I know and love locally.

Thanks,
Anna
