### ISSUE TITLE
Cannot edit markdown cells after saving notebook

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4229]
Issue Type: <b>Bug</b>

After saving a notebook the markdown code disappears from the editor.

![unable to edit markdown](https://user-images.githubusercontent.com/8250560/53556268-5c848580-3af8-11e9-9330-c0363591751b.gif)

Azure Data Studio version: azuredatastudio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-28T03:34:08.321Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
Almost certainly related to #4225.
