### ISSUE TITLE
Azure Data Studio opens 2 copies on launch

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4233]
Issue Type: <b>Bug</b>

When launching Azure Data Studio from the Start menu, two copies are being opened.

This started when I changed from one folder to another in the file explorer. Since that time, both the previous and the new folder are opened in separate instances.

![double ads](https://user-images.githubusercontent.com/8250560/53572781-f2092f00-3b63-11e9-81a0-3f5f01d4c0fb.gif)

Azure Data Studio version: azuredatastudio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-28T03:34:08.321Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kevcunnane** [comment]
@rajmusuku was able to repro this on his dev box - possibly use for a repro case?

**Comment by vickyharp** [comment]
I have a repro now.

1) Go to File... New Window
2) In the new editor, Ctrl+N for a new query
3) Repeat steps 1 and 2 as often as you like
4) Close all editors with their close buttons or (in Windows) by right clicking in the tray and choosing Close All Windows
5) Say no to "Do you want to save?" prompts
6) Reopen ADS and all windows will reappear with the files you already chose not to save

You can stop the windows by explicitly closing each file before you close the window.

**Comment by kburtram** [comment]
I've seen this upstream so let's wait until they have a chance to fix it.
