### ISSUE TITLE
Error when closing a notebook immediately after opening

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4234]
ssue Type: <b>Bug</b>

Repro: Open a notebook and close before the kernels have loaded

Error: Loading kernel info failed: Cannot read property '0' of undefined

![error when fast closing notebook](https://user-images.githubusercontent.com/8250560/53586169-81700b80-3b7f-11e9-8b3f-499ad78c74f0.gif)
I

Azure Data Studio version: azuredatastudio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-28T03:34:08.321Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (4.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.6.0
profiler|Mic|0.6.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
This has been fixed.
