### ISSUE TITLE
Azure and Data Explorer viewlet shouldn't be visible at same time

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4239]
- Azure Data Studio Version: `master`

Azure and Data Explorer viewlets shouldn't both be visible at the same time since they contain overlapping functionality.  Once we have confidence that Data Explorer will be ready for March 20th release we should remove the Azure and Server viewlets from the product and only have Data Explorer.  

You may consider reusing the Server viewlets IDs to avoid some of the viewlet action bar out-of-order issues we're seeing moving between builds (basically Data Explorer needs to show as the first icon in action bar after updating from Feb release...though if this isn't the case I'll open a separate bug for that at that time)

![image](https://user-images.githubusercontent.com/599935/53590302-4ef5ec80-3b46-11e9-8b61-ff31d4697a56.png)

**Comment by anthonydresser** [comment]
Unfortunately there is no when clause on view containers so there no way to hide the azure view container only in the case of dev scenarios, when we only show the data explorer in dev scenarios.

**Comment by anthonydresser** [comment]
I'm also pretty sure the data explorer will show at the top for everyone, since the only time it would is if you already have the data explorer in your app saved state but it is set to be the bottom item.

**Comment by abist** [comment]
@anthonydresser Can we close this issue, now that we just have the Data Explorer?

**Comment by anthonydresser** [comment]
Yes this is fixed
