### ISSUE TITLE
Unable to stop a job after running it from SQL Agent.

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/azuredatastudio#4242]
- Azure Data Studio Version: 
```
Version 1.4.5
Commit 887f4e8985023602e599cf86bdb44df48bb28569
Date 2019-02-12T06:20:08.633Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
```

Steps to Reproduce:

1. Connect to server
1. Bring up manage editor
1. Click on SQL Agent dashboard
1. Select a job
1. Click Run
1. The stop button is never usable

I expect once I click on Run to be able immediately stop the job. Even clicking on refresh for a long running job does not allow you to stop it once you started it via ADS.

**Comment by yualan** [comment]
@abist Can you take a look at this tomorrow? Greatly appreciated :)

**Comment by wsmelton** [comment]
Trying this on a job that has multiple steps and one that I know runs for over 4 hours. I started the job at 3:00:08 AM UTC. I know the job is still running, but the view given by SQL Agent is that it succeeded, but the view of all the steps is completely false in the details....none of the steps shown failed on this run (some have not even run yet)....

Unsure if this is all connected to why that stop button is not available, but the screenshot below the job time slot I have selected is still running on the server:
![image](https://user-images.githubusercontent.com/11204251/53613720-94dd9f80-3b9c-11e9-8066-3ac3a9b11312.png)

**Comment by abist** [comment]
@wsmelton Thanks for reporting this bug! Just to make sure, the job was still running and yet it showed it succeeded with failing steps?

**Comment by wsmelton** [comment]
Correct
