### ISSUE TITLE
Enable VS Code's TSLint rules

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#4260]
VS Code added a bunch of new TSLint rules in 1.31. We should try to enable as many of them as we can. They are currently commented out in `tslint.json` and you can run tslint by running `gulp tslint`

**Comment by anthonydresser** [comment]
This is part of the work I have been working on as part of committer doing the code relayering, as a lot of their rules  have to do with limiting import access from certain areas to others.

**Comment by abist** [comment]
@anthonydresser I think this is done right? Can we close this issue?

**Comment by anthonydresser** [comment]
We haven't implemented all the layer rules.

**Comment by kburtram** [comment]
We've recently enabled various static analysis tools that should help address this suggestion.
