### ISSUE TITLE
Notebooks: get "Spark kernels require a connection to a SQL Server big data cluster" when 1 connection is still connecting

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4261]
Issue Type: <b>Bug</b>

Really fun one:
- Define a connection to a server that doesn't exist
- Try to connect (it'll spin for a minute)
- While that's connecting, open another SQL Server big data cluster in object explorer, right-click and do New Notebook
- Change kernel from SQL -> PySpark3

Expected:
- Kernel change works
Actual:
- Kernel change fails with error `Spark kernels require a connection to a SQL Server big data cluster`

Something is going wrong here, and I would have to guess the Jupyter kernel is getting the wrong connection . This needs investigating as there are other scenarios this could go wrong.

Azure Data Studio version: azuredatastudio 1.5.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.18GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
server-report|Mic|0.1.5
queryplan-show|phi|0.0.2

</details>

**Comment by chlafreniere** [comment]
@kevcunnane can you clarify this a bit more?

**Comment by kevcunnane** [comment]
This is mostly an interesting race condition / dual notebook editing issue. I can show you on my machine if that helps. We have a number of issues trying to work with more than 1 notebook at a time so this docks to that. Per the repro you need 1 notebook actively connecting / working, and then try to do changes to another one and it'll fail.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
