### ISSUE TITLE
Still showing errors from a query editor that has been closed

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#4266]
Issue Type: <b>Bug</b>

I had a query editor open and there were a number of syntax and intellisense errors. When I closed the editor the errors never went away in ADS.

![errors on closed editor](https://user-images.githubusercontent.com/8250560/53682644-aedbc700-3cef-11e9-8d5e-74322a41045e.PNG)

Azure Data Studio version: azuredatastudio 1.5.0-insider (18970ff0b9bfc788ff229ed4e1e81e9ac7e559e3, 2019-03-01T06:14:38.866Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (9)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.6.1
profiler|Mic|0.6.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
I couldn't repro this on the current build.  Please let us know if you're still impacted by this issue.
