### ISSUE TITLE
Zoom in/out via Ctrl mouse scroll

### ISSUE THREAD

**Issue by JohnMarkHowell** [Microsoft/azuredatastudio#4271]
- Azure Data Studio Version: 1.4.5

It would be great if the UI zoom worked the same as in other Microsoft IDEs by holding the Ctrl key down and using the mouse scroll wheel to zoom in/out.

Steps to Reproduce:
Hold Ctrl down and use Mouse scroll wheel to try to zoom in/out.  Simply scrolls the view up/down.

**Comment by anthonydresser** [comment]
You can enable this for editor font zoom using the user setting `"editor.mouseWheelZoom": true`

**Comment by JohnMarkHowell** [comment]
You rock!!  Thank you for such a quick response!!
