### ISSUE TITLE
Insiders update: On using "Check for update" get error The folder “azuredatastudio-darwin.zip” doesn’t exist.: The folder doesn’t exist.

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4279]
Issue Type: <b>Bug</b>

- Open Insiders build (see my version below)
- Check for updates, it'll start auto donwloading
- Get error `The folder “azuredatastudio-darwin.zip” doesn’t exist.: The folder doesn’t exist.`
- Update doesn't succeed.

![image](https://user-images.githubusercontent.com/10819925/53767650-47f31500-3e8b-11e9-85b9-45f07f15a4c8.png)

@MattIrv can you take a look? I will keep the folder with this available if you need to debug.

Azure Data Studio version: Azure Data Studio 1.5.0-insider (291f591af3421899481725016ccb08a40424c036, 2019-02-27T22:36:47.990Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
server-report|Mic|0.1.5

</details>

**Comment by MattIrv** [comment]
I tried to repro this on my machine by updating my insiders build even though it was older than yours and by downloading that build directly and then updating from it but both of them succeeded

**Comment by kevcunnane** [comment]
Using yesterday's build and updating to today doesn't repro, so I'll close. I guess it's a one-off issue, hope it doesn't repro again.
