### ISSUE TITLE
Notebook: grid header text is wrong color in dark mode

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4280]
Issue Type: <b>Bug</b>

Testing on insiders:
- Set theme to default dark
- Run a query in a SQL notebook
- Get unreadable header (see screenshot)
![image](https://user-images.githubusercontent.com/10819925/53768725-81794f80-3e8e-11e9-97f3-eeed9dab6fdc.png)

@chlafreniere  can you take a look?

Azure Data Studio version: Azure Data Studio 1.5.0-insider (ebc208cacdcdda792ac9594a537afafba47cda71, 2019-03-04T03:11:37.882Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
agent|Mic|0.36.1
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3

</details>

**Comment by chlafreniere** [comment]
Fixed by #4624.
