### ISSUE TITLE
Update SelectBox to take option objects instead of strings

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#4284]
In the VS Code 1.31.1 merge VS Code's `SelectBox` (src/vs/base/browser/ui/selectBox/selectBox.ts) is updated to take `ISelectOptionItem` objects instead of strings to set the available options. We should update our version of `SelectBox` too (src/sql/base/browser/ui/selectBox/selectBox.ts)

**Comment by kburtram** [comment]
Closing old tasks.  Please open in the context of an extension under active development if this is still needed.
