### ISSUE TITLE
Notebook doesn't work

### ISSUE THREAD

**Issue by llali** [Microsoft/azuredatastudio#4288]
Issue Type: <b>Bug</b>

When I open the notebook, after installing all the dependencies successfuly, it shows the "Kernal" as Python3 and the "Attach To" is "Loading contexts" and it stays on that sate. When I click on "Run", I get this message "The session for this notebook will start momentarily". 

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.76GB (10.31GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>

![image](https://user-images.githubusercontent.com/17187348/53830167-b3de8780-3f36-11e9-8d18-0290936be75f.png)

**Comment by corivera** [comment]
@llali Was this in a packaged build or running from master?

**Comment by llali** [comment]
package build 1.4.5

**Comment by corivera** [comment]
This doesn't repro for me on the latest insiders builds. Closing as fixed.
