### ISSUE TITLE
Cell highligting seems to be truncated for the Notebook Code Cells

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4292]
Issue Type: <b>Bug</b>

Open a New Notebook on the latest insiders build.

See that the cell is not highlighted properly.

Azure Data Studio version: Azure Data Studio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:09:15.672Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.19GB free)|
|Process Argv|/private/var/folders/vc/2qtbnhx57m56_lzr6h8gv8gh0000gn/T/AppTranslocation/CD9BD9A7-7903-48AB-89FE-CF9B9836B18E/d/Azure Data Studio.app/Contents/MacOS/Electron -psn_0_3908538|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
import|Mic|0.5.0
sql-vnext|Mic|0.10.3

</details>

**Comment by chlafreniere** [comment]
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/40371649/53848543-9676e100-3f69-11e9-8710-f3f10299797b.png">

I can't repro with latest from master ☹️

**Comment by kevcunnane** [comment]
Will close for now as we're heavily triaging March issues. reopen if it's happening in tomorrow's insiders build (today's is busted)
