### ISSUE TITLE
Feature Request: Work trhu proxy with Integrated/Kerberos Authentication

### ISSUE THREAD

**Issue by olegstrutinskii** [microsoft/azuredatastudio#43]
This is valid for VSCode too, when you specify proxy and that proxy requires NTLM/Kerberos authentication its not working at all, every time we need to create local proxy with Fiddler or CNTLM applications.

**Comment by kburtram** [comment]
Closing this older issue as upstream.  If this gets fixed in vscode we'll pick up that in a future source code refresh.
