### ISSUE TITLE
No info in Debug Console in VSCode when debugging ADS extension via sqlopsExtensionHost

### ISSUE THREAD

**Issue by grpeacock** [microsoft/azuredatastudio#4303]
**Azure Data Studio Version**:
Insider build downloaded 3/5/19.
![image](https://user-images.githubusercontent.com/42870542/53887845-1bf1a400-3ff1-11e9-9edf-a3919facc40d.png)

**Steps to Reproduce**:

1. Generate the default ADS extension project with Yeoman and generator-sqlops or generator-azuredatastudio.
     a. If using generator-sqlops, change the runtimeExecutable value in _launch.json_.
2. Observe mocha tests generated in file _extension.test.ts_.
3. In VSCode, run the launch configuration "Extension Tests."
4. Observe the Debug Console.

Expected: Testrunner output detailing passing and failing tests (see comparison image below).
Actual: Only the line detailing the command used to start the ADS extension host (see actual image below).

**Additional Information**:

Break points added inside the tests are hit normally, indicating the tests do properly run. Suggests the issue is in piping output back to the debug console. Could this be an issue with the VSCode extension "Azure Data Studio Debug" instead?

Image of actual behavior:
![image](https://user-images.githubusercontent.com/42870542/53887780-ff556c00-3ff0-11e9-97d2-17f369e79faa.png)

Image of expected behavior; captured by running the same generated extension through a VSCode extension host instead of ADS:
![image](https://user-images.githubusercontent.com/42870542/53887795-05e3e380-3ff1-11e9-9f2d-253d9abaccaa.png)

**Comment by kevcunnane** [comment]
This is interesting - what I've seen when using the debugger is that the output isn't as nicely formatted, but it does show up. Are you not seeing any output at all? 

In general the output isn't quite as nice as in VSCode's case - the core issue is that the VSCode debugger uses a different launch method and way of getting feedback than the ADS debugger, since it's just launching a new version of its own process. I wasn't able to replicate that so had to use standard Node.js launching instead. 

As a workaround, if you run tests from the cmdline you'll get all the test output shown fine and can verify using that, but I know it's more convenient to debug and see all output clearly.

**Comment by grpeacock** [comment]
No, no output at all beyond what is in the picture. I also tried a simple console.log() in the middle of the tests - it outputs fine in the VSCode extensionhost, but doesn't output at all for ADS.

I've had some difficulty with running tests from the command line:
- When using "npx mocha -testpath-," vscode and sqlops imports in the test file cannot be found. This runs tests fine if those imports are not required in the tests.
- When using the default "npm run test," script created by the generator, it runs the extension through VSCode.
- When using "npm run test" after updating the script to use the sqlops module instead of vscode, an error prevents starting.

Admittedly I'm new to this technology, so it's possible I'm missing the correct method to run tests from command line, but that does start to stray away from the original topic here.

**Comment by stelth240** [comment]
@kevcunnane, This issue still appears to be happening, at least for me. When I debug an ADS extension in VS Code, it does not output any console.log or console.info messages. This makes it much harder to debug.

I tried to add "outputCapture": "std" as other posts in the past have suggested, but that option does not appear to be available anymore.

This is my launch.json file:

```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Extension",
            "type": "sqlopsExtensionHost",
            "request": "launch",
            "runtimeExecutable": "azuredatastudio",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}"
            ],
            "outFiles": [
                "${workspaceFolder}/out/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        },
        {
            "name": "Extension Tests",
            "type": "sqlopsExtensionHost",
            "request": "launch",
            "runtimeExecutable": "azuredatastudio",
            "args": [
                "--extensionDevelopmentPath=${workspaceFolder}",
                "--extensionTestsPath=${workspaceFolder}/out/test"
            ],
            "outFiles": [
                "${workspaceFolder}/out/test/**/*.js"
            ],
            "preLaunchTask": "npm: watch"
        }
    ]
}
```

Thank you for your help with this.

**Comment by rayzinnz** [comment]
This issue is still apparent. For now I am logging debug messages to this function vscode.window.setStatusBarMessage() instead of console.debug(). There is no "outputCapture" option in the Extension configuration, and I've tried "internalConsoleOptions": "openOnSessionStart" to no avail.

**Comment by Charles-Gagnon** [comment]
Please update to the latest version of the debug extension and let us know if you're still seeing the issues - I've made some fixes there recently and it seems to be working as expected for me

![image](https://user-images.githubusercontent.com/28519865/131196848-6ec8d97b-2bda-40fa-af33-757ed5e95205.png)
