### ISSUE TITLE
Error showing dbs when using AAD auth after bumping SqlToolsService version to 1.5.0-alpha.74

### ISSUE THREAD

**Issue by kisantia** [Microsoft/azuredatastudio#4319]
Steps to Reproduce:

1. Bump SqlToolsService version to 1.5.0-alpha.74
2. Connect to a server using AAD auth
3. Click on the databases folder and see the error "Property NonPooledConnection cannot be changed or read after a connection string has been set."

![image](https://user-images.githubusercontent.com/31145923/53923825-7d843380-402e-11e9-929f-a96e901c87b4.png)

**Comment by kburtram** [comment]
This appears to be fixed on the latest build.  Please reactive if the issue persists.
