### ISSUE TITLE
Consider making github issue labels 1 word

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/azuredatastudio#4322]
Making github issue labels one word helps when build tooling as you don't have to worry about url encoding.

Example:
`query editor` could become `query-editor`

**Comment by kburtram** [comment]
@anthonydresser feel free to make this update to our existing labels.  Though we'd need a mechanism to enforce this policy for future labels since I don't think there's anything built into GitHub for that.

**Comment by kburtram** [comment]
We've adopted a new label scheme that encodes "Area" and "Priority" with lots of spaces.  So I'll close this for now.  We can revisit if we don't like the new labeling system.
