### ISSUE TITLE
Remove contentManager APIs from the sqlops / azdata modules

### ISSUE THREAD

**Issue by rajmusuku** [microsoft/azuredatastudio#4323]
Since we no longer use contentManagerAPI's to fetch data, we should clean them up from azdata modules.
We need to stop doing stuff with these in the MainThreadNotebook, SqlNotebookProvider etc. This task is created part of Notebooks save implementation.

**Comment by anthonydresser** [comment]
Could this potentially affect extensions?

**Comment by kevcunnane** [comment]
Only our built-in extensions currently use this. And we've actually removed usage in the Jupyter extension point already, so to my knowledge no extension uses this.

**Comment by kburtram** [comment]
Closing old tasks.
