### ISSUE TITLE
Add an icon to Notebook editors in ADS

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4328]
Right now, Notebook editor has the default icon of vscode’s text editor. We need to hookup an icon to represent Notebook.

![image](https://user-images.githubusercontent.com/44002319/53979117-c3d6a280-40c1-11e9-8bd2-7caaa8164e60.png)

**Comment by kevcunnane** [comment]
@smithaBharadwaj - if we can create a font glyph in WOFF format I know how to add the file icon support into the code. https://code.visualstudio.com/api/extension-guides/icon-theme is a good reference point for what we need, and seems like the built-in icon themes use this.

**Comment by chlafreniere** [comment]
This was fixed by #4419.
