### ISSUE TITLE
Messages occasionally loses first output line  

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4334]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query a few times

Expected: Messages always shows all the output

Actual: Sometimes the first output line is missing

Note: Likely a regression from https://github.com/Microsoft/azuredatastudio/pull/4313 since that is the change I'm currently trying to validate

![image](https://user-images.githubusercontent.com/599935/53990475-3a34ce00-40dd-11e9-9ddf-6af5159c5028.png)

Should look like

![image](https://user-images.githubusercontent.com/599935/53990624-8aac2b80-40dd-11e9-8798-cf9f45ee4b39.png)

**Comment by kburtram** [comment]
@anthonydresser could you please look at this? I'm guessing it may be related to the recent Messages sizing change.

**Comment by anthonydresser** [comment]
I'll take a look but that would be odd since those changes didn't touch the code for the messages panel

**Comment by kburtram** [comment]
OK, I'll try to repro on yesterday's insider build that doesn't have that change.  In any case, we'll want to fix this.

**Comment by kburtram** [comment]
@anthonydresser you're correct this isn't a regression from #4313, though it is a regression since 1.4.5 release.  Please take a look if you could in any case.  Thanks!

**Comment by anthonydresser** [comment]
I know the fix to this, but it changes some behavior that I'm not sure we want to do without more testing.
