### ISSUE TITLE
Messages can initially display expanded at 0 height after window resize

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4335]
Steps to Reproduce: `master`

1. Run a query such as `SELECT * FROM sys.objects`
2. Resize the messages to be about 1/2 the original height
3. Resize the ADS main window to be smaller (for example, a few 100 pixels less wide and tall)
4. Rerun the query

Expected: Messages are restore to original size after step 1 or after step 2 (either of those sizes would make sense)

Actual: Messages is 0 height but show as expanded.  Messages be manually resized to visible again.

Note: Likely a regression from https://github.com/Microsoft/azuredatastudio/pull/4313 since that is the change I'm currently trying to validate

![image](https://user-images.githubusercontent.com/599935/53990816-0017fc00-40de-11e9-962e-98f7c8d4b1c3.png)

**Comment by kburtram** [comment]
@anthonydresser could you please look at this? I'm guessing it may be related to the recent Messages sizing change.

**Comment by anthonydresser** [comment]
I'll take a look but that would be odd since those changes didn't touch the code for the messages panel

**Comment by kburtram** [comment]
@anthonydresser you're correct this isn't a regression from #4313, though it is a regression since 1.4.5 release.  Please take a look if you could in any case.  Thanks!

**Comment by anthonydresser** [comment]
This should be fixed by the revert
