### ISSUE TITLE
cluster deploy - create mssql-ctl wrapper

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4337]
- [ ] Refactor kubectl code to support targeting other CLI executables
- [ ] create mssql-ctl wrapper that can query its commands and call commands
- [ ] handle stdout and stderr from mssql-ctl so we can get sensible status on progress of deployment
- [ ] update wizard to actually use mssql-ctl wrapper in its model
- [ ] update script to point to the path of mssql-ctl so it works

**Comment by kburtram** [comment]
Closing out older issues.
