### ISSUE TITLE
Failed to connect to server

### ISSUE THREAD

**Issue by jschrap** [microsoft/azuredatastudio#4351]
- Azure Data Studio Version:   1.4.5, on Windows 10

Steps to Reproduce:

1. add managed connections to several Azure SQL server(s) with "default" db.
2. double click to "connect" and it connects
3. when you click open Databases below it, it shows: "Failed to connect to server".
**_NOTE:_**  this doesn't always happen... it happens only sometimes.

![azuredatastudio-error-ev](https://user-images.githubusercontent.com/17762353/54019609-e503c580-418b-11e9-99f3-cae56ced19f0.JPG)

**Comment by cheenamalhotra** [comment]
With many recent improvements, this should be resolved now. 
Let us know if you encounter this again.
