### ISSUE TITLE
dacpac export error

### ISSUE THREAD

**Issue by ralphke** [Microsoft/azuredatastudio#4358]
Issue Type: <b>Bug</b>

Tryed to export my SQL DW database to my local file an received the following error:
Extract dacpac: Could not extract package from specified database.
Parse error at line: 1, column: 5: Incorrect syntax near 'ANSI_NULLS'.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (2.47GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.1
agent|Mic|0.36.1
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.5
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1

</details>

**Comment by kisantia** [comment]
SQL DW is not currently supported by DacFx. As of now,  it is in [public preview](https://azure.microsoft.com/en-us/blog/azure-sql-data-warehouse-provides-a-frictionless-development-using-sql-server-data-tools/). It will be added in DacFx after it is officially released. Thanks!
