### ISSUE TITLE
Untitled notebook gets rehydrated in query editor in JSON format

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4363]
- Create a new untitled notebook in ADS and add some content
- Close ADS and open, untitled notebook gets rehydrated in sql query editor with content in JSON string. Please see screen print below

![image](https://user-images.githubusercontent.com/44002319/54062702-9e7a8f00-41bc-11e9-892c-5bfb4c998a7c.png)

@kburtram @anthonydresser  : Do you have any idea why it's happening

**Comment by anthonydresser** [comment]
I think its due to https://github.com/Microsoft/azuredatastudio/blob/master/src/vs/workbench/common/editor/editorGroup.ts#L690

**Comment by kburtram** [comment]
Closing based on #4424.
