### ISSUE TITLE
[Insiders Build] - Editor Split Down loses view of query completely

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#4373]
Issue found with Insiders Build.

- Azure Data Studio Version:

```
Version 1.4.3-insider
Commit 9cffe4d476d2158ce904bdebffd5ed83ebede4f2
Date 2019-01-28T03:26:24.244Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64
```

Steps to Reproduce:

1. Open multiple query editors
1. Split any one of them down
1. Type basic query `SELECT * FROM sys.databases` and execute it
1. As soon as the results and message panes are rendered you loose all visibility of the query
1. Click on the editor pane (that was split down) and `CTRL + END` to the end of the editor.
1. Hold down the `ENTER` key ...you will never see the cursor or line numbers show up within that editor
1. Move the Editor up to the main view again and everything appears as it should.

![image](https://user-images.githubusercontent.com/11204251/54081766-a840e700-42cf-11e9-98a4-5c6b268a78e3.png)

**Comment by kburtram** [comment]
This doesn't appear to repro on the current build.  Please let us know if you're still impacted by this issue.
