### ISSUE TITLE
Results Horizontal scroll bar

### ISSUE THREAD

**Issue by 3d8a7d** [microsoft/azuredatastudio#4374]
Issue Type: <b>Bug</b>

To Reproduce:
Execute a query with a large number of columns.
View the RESULTS pane and see that it has no visible horizontal scroll bar.
Expand the RESULTS pane and now the horizontal scroll bar is visible but is vertically too small to be selected and used to scroll.
Expand the RESULTS pane some more and now the vertical height of the horizontal scroll bar is large enough to be selected and used.

The Horizontal Scroll bar on the RESULTS pane should always be visible and have enough vertical height to be selected and used, without having to expand the RESULTS pane.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.85GB (20.08GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-db-insights|mat|0.2.2
mssql-instance-insights|mat|0.2.1
agent|Mic|0.36.1
import|Mic|0.5.0
profiler|Mic|0.6.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by herofusit** [comment]
Makes this pretty unusable. Any update on status?

**Comment by Bunghoolio** [comment]
Yep, I can echo that is makes it pretty unusable. 
I see the same issue when using azure data studio with python. When using it with SQL in a notebook the scroll bar works pretty well. 
Is there any update on this?

**Comment by kburtram** [comment]
Closing this older issue since it is specifically related to the horizontal scrollbar on the results grid in a query editor window.  We did changes a while ago to make sure the scrollbar is visible and making it larger vertically in size.  Please let us know if the issue persists on current builds.

@Bunghoolio could you please log a different bug for what you are seeing in Python Notebooks?  Thanks!

**Comment by Ossy81** [comment]
> Closing this older issue since it is specifically related to the horizontal scrollbar on the results grid in a query editor window. We did changes a while ago to make sure the scrollbar is visible and making it larger vertically in size. Please let us know if the issue persists on current builds.
> 
> @Bunghoolio could you please log a different bug for what you are seeing in Python Notebooks? Thanks!

This issue is still there... The horizontal scrollbar is very tiny threfor very hard to click on to scroll horizontally within the results
