### ISSUE TITLE
ADS Query window does not show hidden incompatible characters

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#4382]
Issue Type: <b>Bug</b>

Use the following code to create an external table:
CREATE EXTERNAL TABLE [dbo].[helloORC_HDP3_0] 
([name] varchar(20)
)  
WITH 
(  LOCATION='/',   
        DATA_SOURCE = AzureStorage,  
        FILE_FORMAT = OrcFileFormat,
        REJECT_TYPE = VALUE,
        REJECT_VALUE = 0 
)
;

Error message is:
Msg 103010, Level 16, State 1, Line 1
Parse error at line: 3, column: 3: Incorrect syntax near ' '.

![image](https://user-images.githubusercontent.com/10529018/54142188-6c4b7600-43e4-11e9-968f-bb448998957c.png)

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (42.15GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.10.2

</details>

**Comment by kevcunnane** [comment]
Can you clarify, what's the incompatible character here? Just trying to understand where to assign this.

**Comment by jrowlandjones** [comment]
Actually I couldn't tell what it was @kevcunnane 

I am reporting it as the error shows.

**Comment by kburtram** [comment]
Closing out this older issue.  We haven't seen similar repros so not sure what we can do in this case.  Please let us know if you're still impacted by this issue.
