### ISSUE TITLE
"Save as CSV" no longer works

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#4392]
Issue Type: <b>Bug</b>

1. Run a query
2. Click the "Save as CSV" button or select some cells, right click, and choose "Save as CSV"

An error message shows up: `Failed to save results. Error: Failed to save Results.csv: Could not load file or assembly 'System.Text.Encoding.CodePages, Version=4.1.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.2.0

**Comment by kburtram** [comment]
I worked-around this issue for March release by reverting the SQL Tools vbump.  I'll move to April milestone to investigate what's wrong with the current SQL Tools package.
