### ISSUE TITLE
No test and build check for PR

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4395]
I checked few recent PRs. There is only one check. The other 4 checks for build and test are not running. 
Could anyone take a look? This is blocking merge.

**Comment by anthonydresser** [comment]
Looks like someone might have messed with the permissions for the pipeline bot and removed access from our repo. @abist is emailing the owner to figure out the issue.

**Comment by abist** [comment]
Issue fixed.
