### ISSUE TITLE
Query Editor "Explain" results/operation do not go away when re-running the query

### ISSUE THREAD

**Issue by udeeshagautam** [Microsoft/azuredatastudio#4414]
[Insider Build testing]
Steps to Reproduce:

1. Run a query. It shows Result
2. Click Explain. It shows - Result, Top Operations and Query Plan
3. Re-run the query

The query Result tab comes as a child tab of Query Plan Result tab. and Top operation still remains in second tab. even if you change the query and rerun - the top operation tab keeps showing old query plan result.

![image](https://user-images.githubusercontent.com/46980425/54235976-c37a4500-44cf-11e9-928f-cfdd3f00d3d5.png)

**Comment by kburtram** [comment]
This appears fixed in the 1.6 build.  Please reactive if the issue persists.
