### ISSUE TITLE
Dashboard scroll not activated in case of split up/down view

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#4415]
[Inside build testing]
Steps to Reproduce:

1. Open Dashboard 
2. View --> Editor Layout --> Split Up/Down
3. Dashboard content is clipped.
Expected : Dashboard scrollbar should be activated

![image](https://user-images.githubusercontent.com/46980425/54236752-94fd6980-44d1-11e9-894a-4a2144e5cf36.png)

**Comment by kburtram** [comment]
This appears to be fixed in the current build.  Please let us know if you're still impacted by this issue.
