### ISSUE TITLE
Resizing of Message and Grid in query result view lost at tab changes

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#4417]
[Insider build testing]
( I was hoping this to be a dup bug but couldn't find one. Please close this if this is already a known bug)

Steps to Reproduce:

1. Run a query
2. Resize the results view **using the sash between message and results grid** 
3. Change tab to anything else
4. Come back to query editor tab
5. The Result Grid and Messages tab proportion is auto resized to a default 
(This doesn't repro if you use the sash above results view to resize)

**Comment by anthonydresser** [comment]
dupe #5972
