### ISSUE TITLE
Notebook file icon doesn't show for new notebook until clicking on another tab

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4418]
This issue shows once we add file icon support for notebooks. Because we're not pre-registering our untitled document with the untitledDocumentService before creating the NotebookInput it uses the default icon. Then on doing an action that refreshes the icon, it switches to the new Notebook icon instead.

The fix is tied to a more general refactor Raj is working on, so splitting this issue into its own bug.

**Comment by chlafreniere** [comment]
@rajmusuku please let us know if there's a quick fix here, or if you think we should push to April.

**Comment by rajmusuku** [comment]
> @rajmusuku please let us know if there's a quick fix here, or if you think we should push to April.

It's not yet ready. Will work on it tomorrow and if not will push it to April

**Comment by rajmusuku** [comment]
Fixed in https://github.com/Microsoft/azuredatastudio/pull/4676
