### ISSUE TITLE
Update on Mac requires re-entering all passwords for connections

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#4432]
- Azure Data Studio Version: 1.5.1-insider and 1.4.5

Steps to Reproduce: 
1. Download latest release or insider build on Mac
2. Open ADS
3. All connections have lost their password

Desired: Ideally this wouldn't happen, ADS would just remember my password (since I checked the box to remember my password) as I update to new versions. I don't have this issue on Windows.

Thanks!

**Comment by kburtram** [comment]
I'm not able to repro this.  The save passwords are stored in the KeyVault and shouldn't be cleared during update.  I've been prompted to reenter my KeyVault credentials after upgrading, but not for the connections themselves.  Are there any other repro steps or details that may help diagnosis?

**Comment by amthomas46** [comment]
Still happening on my Mac when I close and reopen
<img width="369" alt="Screen Shot 2019-03-14 at 1 29 53 PM" src="https://user-images.githubusercontent.com/28786161/54389421-4381e580-465d-11e9-95ea-054114783ed8.png">

So I click it and then I get
<img width="1162" alt="Screen Shot 2019-03-14 at 1 30 14 PM" src="https://user-images.githubusercontent.com/28786161/54389435-4ed51100-465d-11e9-9f2f-8b12f6851a1f.png">


Then I check the box and enter my password
<img width="810" alt="Screen Shot 2019-03-14 at 1 33 44 PM" src="https://user-images.githubusercontent.com/28786161/54389641-cc008600-465d-11e9-8191-ab0b9d08ca73.png">


Now I'm in.
<img width="377" alt="Screen Shot 2019-03-14 at 1 31 32 PM" src="https://user-images.githubusercontent.com/28786161/54389517-7d52ec00-465d-11e9-82e2-05bb1fa91553.png">

Close and reopen ADS and click the instance
<img width="1181" alt="Screen Shot 2019-03-14 at 1 32 08 PM" src="https://user-images.githubusercontent.com/28786161/54389554-93f94300-465d-11e9-8f04-dee29429a464.png">

**Comment by amthomas46** [comment]
It saves the connection info MINUS the password

**Comment by kburtram** [comment]
@amthomas46 is this specific to Big Data Cluster connections or do you see this on SQL Server connections as well?

**Comment by amthomas46** [comment]
BDC only. and only on my mac. I can try to repro it tomorrow

**Comment by jcosmo** [comment]
It is not specific to Big Data Cluster connections, it is happening on SQL Server and Postgres connections as well.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.

**Comment by Charles-Gagnon** [comment]
(if you still see this for non-BDC connections please open another issue so we start with fresh information since there's been a ton of work done in this area)
