### ISSUE TITLE
shift+enter to run cell in notebooks (specifically sql)

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4433]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that shift+enter works in Jupiter notebooks but doesn't work in ADS 

**Describe the solution or feature you'd like**
shift+enter should result in a cell being run

**Describe alternatives you've considered**
I have to click the button. I am too lazy for that

**Additional context**

**Comment by chlafreniere** [comment]
@amthomas46 and I already chatted about this issue, but in case anyone else sees this:

Opening the command palette, and finding "Preferences: Open Keyboard Shortcuts" allows users to customize shortcuts themselves. Search for "notebook", and you'll find the commands that we currently have keybindings for; for this scenario, changing Run Cell from F5 to another key combination (such as Shift+Enter) will work.

VS Code doesn't currently offer the ability to bind multiple keys to the same action, so we're a bit stuck at the moment and cannot support both F5 and Shift+Enter.

**Comment by chlafreniere** [comment]
As stated previously, this is configurable in keyboard shortcuts.
