### ISSUE TITLE
UI formatting - Connection tab formatting of groupings too close to edge

### ISSUE THREAD

**Issue by amthomas46** [microsoft/azuredatastudio#4434]
- Azure Data Studio Version: 1.5.1-insider

Steps to Reproduce:

![image](https://user-images.githubusercontent.com/28786161/54301511-5670b900-457c-11e9-9e55-f5e279173a8d.png)
In the above image, if I got to add a connection, the labels for my colored groupings are too close to the edge. It looks like they're almost getting cutoff. Can we add a few spaces before or something? It just gives me a bit of anxiety.

Thanks!

**Comment by kburtram** [comment]
The UX for Server Groups has been changed since this issue was filed.  Please let us know if you have suggestions on the current UX.  Thanks!
