### ISSUE TITLE
Auto size column can make the column smaller.

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4438]
- Azure Data Studio Version: master

Steps to Reproduce:

1. get a long column such as query plan
2. resize it fill the screen
3. double click to auto size column
4. the column size will shrink; presumably because the max size is smaller than what I had it sized too

We should take the max of maxSize and the current column width.

**Comment by strandloper** [comment]
Here's an example of this from version 1.9.0. A query returns the following values for an column.
````
Value
-----
1000
5:00
true
````
but the auto-sized column displays as
````
Value
-----
10…
5:…
tr…
````
