### ISSUE TITLE
Unseeable grid results

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4440]
- Azure Data Studio Version:

Steps to Reproduce:

1. Split a sql editor down
2. run queries on both top and bottom

The grid results are cut off on the bottom and you can't see the messages panel
![image](https://user-images.githubusercontent.com/4324725/54310255-2b439500-458f-11e9-9f11-819963f23886.png)

**Comment by kburtram** [comment]
Closing some older issues.  Please let us know if you're still impacted by this issue.
