### ISSUE TITLE
Message Panel overrides command pallet keybind

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#4442]
- Azure Data Studio Version:

Steps to Reproduce:

1. run query
2. click message panel

F1 to bring up command pallet no longer works.

**Comment by kburtram** [comment]
@anthonydresser do you know if is this a regression from Feb release?

**Comment by anthonydresser** [comment]
I'm not sure but I don't think so.

**Comment by kburtram** [comment]
This doesn't repro on the current build.  Please let us know if you're still impacted by this issue.
