### ISSUE TITLE
Recent connections not being saved

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/azuredatastudio#4443]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to a previously unconnected server
2. The server will appear in the recent connections
3. Reload the window

The server should still be in the recent connections but it isn't.

**Comment by kburtram** [comment]
This should be fixed now.

**Comment by Abhijit-Revamp** [comment]
Still not working on macOS Version 1.5.2

**Comment by anthonydresser** [comment]
@Abhijit-Revamp If you are still seeing a similar issue, can you open a new issue with repro steps. Thanks.
