### ISSUE TITLE
Connection stuck in "Loading..." state until connected

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4445]
- Azure Data Studio Version: `master` 1.5.1

Steps to Reproduce:

1. Clear ADS cache to get into 1st launch scenario
2. Add a connection
3. Restarted ADS

Expected:  Connection shows metadata details such as server name, etc.

Actual: Server shows in "Loading" state until the server is connected to and the metadata loads correctly.

![image](https://user-images.githubusercontent.com/599935/54313419-8cbb3200-4596-11e9-966e-61d7aea9d3ea.png)

**Comment by MattIrv** [comment]
I fixed a similar issue in the 1.31 merge branch and it might be the same issue just reproing easier in that branch. I'll check if the same fix applies here

**Comment by kburtram** [comment]
@MattIrv I'll assign to you then.  Please let me know if that fix doesn't help and I can try to investigate too.

**Comment by anthonydresser** [comment]
This also might have been caused by the state saving stuff I fixed
