### ISSUE TITLE
Notebook: Run cell shows as running if you move from 1 cell to another

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4450]
Issue Type: <b>Bug</b>

Add 2 cells:
```sql
select * from sys.tables
WAITFOR DELAY '00:00:05:00'
```

```
select 1
```

Click run on the 1st cell, and then move your mouse directly down over the other cell's Run button. You'll see it show as running too. 

Azure Data Studio version: Azure Data Studio 1.5.1-insider (58e5125cdebafd79b69683ce533210cc485175ae, 2019-03-13T03:13:01.826Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.36.1
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3

</details>

**Comment by chlafreniere** [comment]
I am unable to repro this issue.

**Comment by kevcunnane** [comment]
Chris fixed this by accident. Happy days!

**Comment by kevcunnane** [comment]
Spoke too soon...
