### ISSUE TITLE
Connection dialog "Add an account" option doesn't select the added account

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#4451]
Issue Type: <b>Bug</b>

1. Clear your Azure accounts
1. Open the connection dialog
2. Set the auth type to Azure Active Directory
3. Choose 'Add an account...' in the account picker
4. Log in to your account

Actual behavior: After logging in the login screen pops up again and you have to cancel out of it to select the account you just added
Expected behavior: The added account gets selected automatically

Azure Data Studio version: Azure Data Studio 1.5.1-insider (17901fbf3d33e175bd04dd44be0ed512fd4c9e4f, 2019-03-13T18:45:26.095Z)
OS version: Darwin x64 18.2.0

**Comment by dajomo** [comment]
Problem continues in 1.5.2

**Comment by Charles-Gagnon** [comment]
This no longer repros for me on 1.15. The issue described above is likely different than the original issue - likely similar to the other proxy issues we've had.
