### ISSUE TITLE
Notebook is reloaded with wrong kernel

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4452]
Issue Type: <b>Bug</b>

- Open a notebook with not SQL kernel save and close ADS when kenerl is in loading state
- Open ADS, the file will be loaded but the kernel is "SQL"
   Second issue: Kernel Dropdown has only "SQL" option.

Expected:
   The saved kernel should be displayed correctly after reload

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (42.75GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by rajmusuku** [comment]
I too see this issue. Looks like Spark kernels are not loaded when notebook is reopened.

![image](https://user-images.githubusercontent.com/44002319/54318753-90ee4c00-45a4-11e9-9b20-47b573d1cf73.png)
