### ISSUE TITLE
Image referencing in SQL Notebooks

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4454]
- Azure Data Studio Version: 1.5.1-insider

Steps to Reproduce:

1. Try to reference an image
2. image must be in C drive
3. Sometimes one of these options works, sometimes not:

```
![Java in SQL](/images/java-r-python.png)  
![Java in SQL](C:/images/java-r-python.png)  
```

4. It'd be nice to be able to reference images where they are, similarly to how it work in VSCode markdown previewer today

**Comment by amthomas46** [comment]
FYI @rgward

**Comment by chlafreniere** [comment]
Dupe of #3069.
