### ISSUE TITLE
Dacpac Extract crashes SqlToolsService if invalid version is used

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4458]
1. Open dacpac wizard and choose extract
2. Set version to 1.0.0.0abcd
3. Click Next and kick off the wizard

Actual:
Get error `SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.`
![image](https://user-images.githubusercontent.com/10819925/54319229-250ce300-45a6-11e9-9936-f72b00b65382.png)

Expected:
a) Validation on page blocks going Next until a valid version is defined
b) the SqlToolsService code needs an overall try/catch to avoid crashing if anything goes wrong with the dacpac export. This breaks the entire app

**Comment by yualan** [comment]
Documented as Known Issue

**Comment by alanrenmsft** [comment]
@kisantia , could you please take a look?

**Comment by kisantia** [comment]
this was fixed in SqlToolsService https://github.com/Microsoft/sqltoolsservice/pull/789
