### ISSUE TITLE
Object Explorer: right-click connection while other connection is expanding causes error to show

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4459]
1. Have 2 servers in OE, 1 of which is slow to expand (e.g. a remote Azure SQL DB)
2. Click on the Azure SQL DB instance to expand
3. Right-click on the other connection while the 1st is still expanding
![image](https://user-images.githubusercontent.com/10819925/54319679-9bf6ab80-45a7-11e9-8237-3042a083f82c.png)
Get error `Failed to create Object Explorer session`.

This seems pretty consistent. I would suggest not targeting for March since it's unclear when this happened, and workaround is click "OK" on error and redo what you were trying to do.

**Comment by MattIrv** [comment]
I've seen this error message in other situations too including when just connecting to a server in OE. I also have consistent repro steps that are a bit different:

1. Add a connection to Azure in OE (you may need to use AAD, I'm not sure)
1. Connect to the added connection then disconnect
1. Drag that connection to another server group
1. Click on the connection again to connect it and the error message pops up

See the referenced duplicate issue #4479 I filed for more

**Comment by udeeshagautam** [comment]
Another repro:

1. Have an AAD connection into OE (active or inactive)
2. Open second ADS which will have this connection too
3. Try to expand(connect) the connection in second ADS
4. Throws this error and then connects anyway.

**Comment by dylmye** [comment]
I'm also getting this with a local SQL server instance, on first and subsequential connections:
![image](https://user-images.githubusercontent.com/7024578/54744102-fb634580-4bbd-11e9-876e-d3ecc5b05e4b.png)
