### ISSUE TITLE
Inconsistent "Show Details" / "Hide Details" button

### ISSUE THREAD

**Issue by geleems** [microsoft/azuredatastudio#4463]
"Show Details" / "Hide Details" button is not consistent when user expands details, goes back to previous page, and comes back to current page.
Here is repro step

1) Error message is shown up after hitting "Next" button in ConnectionDetailsPage
![image](https://user-images.githubusercontent.com/19577035/54320099-0d832980-45a9-11e9-9ad2-a9d38899055b.png)

2)  User expands the details of the error message by clicking "Show Details"
![image](https://user-images.githubusercontent.com/19577035/54320132-2a1f6180-45a9-11e9-909d-037f0e9fd30e.png)

3) User goes back to previous page by clicking "Previous" button
![image](https://user-images.githubusercontent.com/19577035/54320142-31466f80-45a9-11e9-892f-5cdc3f571d35.png)

4) User comes back to ConnectionDetailsPage again and hits "Next" button. The error message is collapsed but it shows "Hide Details" instead of "Show Details"
![image](https://user-images.githubusercontent.com/19577035/54320307-b893e300-45a9-11e9-91eb-feb4d78bafc6.png)

**Comment by kevcunnane** [comment]
This is a bug in the core extensibility APIs

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still impacted by this issue.
