### ISSUE TITLE
ADS can be shrinked to strange looking level

### ISSUE THREAD

**Issue by geleems** [Microsoft/azuredatastudio#4467]
ADS can be shrinked like this.
Should this be fixed? or Do we allow this?

![image](https://user-images.githubusercontent.com/19577035/54320838-9f8c3180-45ab-11e9-8186-cda6db26786b.png)

**Comment by kburtram** [comment]
@geleems what is the behavior you expected in this scenario?

**Comment by kburtram** [comment]
Closing as "by design" since we don't have plans to make ADS display content in highly constrained resolutions.  We'd ask the user to workaround the issue by resizing the window a bit larger.
