### ISSUE TITLE
Backup/Restore shows in Context Menu for Azure DB and fails when started

### ISSUE THREAD

**Issue by udeeshagautam** [Microsoft/azuredatastudio#4471]
[Insider's build testing]

Azure Databases show Backup/Restore in context menu. Once clicked the Backup dialog opens and shows multiple issues (in filling up form/selecting file) and finally fails without giving any error.

Steps to Reproduce:

1. Open an Azure Connection in OE
2. Right Click Context menu shows backup restore option

Expected : shouldn't show the option on parity with manage dialog. Ref : [https://github.com/Microsoft/azuredatastudio/issues/815]

**Comment by kburtram** [comment]
This should be fixed now.
