### ISSUE TITLE
Connecting to Azure in OE sometimes pops up "Failed to create Object Explorer session"

### ISSUE THREAD

**Issue by MattIrv** [Microsoft/azuredatastudio#4479]
- Azure Data Studio Version: release/1.5

Steps to Reproduce:

I've seen this bug a few times where you connect to an Azure SQL DB instance in Object Explorer and the error message "Failed to create Object Explorer Session" shows up, even though if you dismiss the message OE works fine.

I don't have repro steps for all cases but the following seems to repro it every time for me:

1. Add a connection to Azure in OE (you may need to use AAD, I'm not sure)
2. Connect to the added connection then disconnect
3. Drag that connection to another server group
4. Click on the connection again to connect it and the error message pops up

I haven't seen this happen for non-Azure servers yet but it might

**Comment by kevcunnane** [comment]
I opened #4459 for the same thing. I think this is a fairly reliable repro. Can we close this one?
