### ISSUE TITLE
Create External Data Source - Cannot read property 'hasMasterKey' of undefined

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#4482]
Version: 1.5.1-insider (user setup)
Commit: 2c7b5578e7a6a35fd707fe83f1a73a717deb20e3
Date: 2019-03-13T18:56:07.201Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

(Note : not able to create a repro DB for this. Came across it using an existing DB)

1. Open create external table wizard
2. Select DB
3. Click "Next"
4. Following error displays, nothing useful in console log

![image](https://user-images.githubusercontent.com/28519865/54326091-7fb43800-45c2-11e9-8180-5c290a080753.png)

**Comment by Charles-Gagnon** [comment]
Note I'm unable to repro this with a debug build - the DB that I had this occur on before was probably in some weird state (it's one of the test DBs so all sorts of odd stuff is done to it). I'll try and keep an eye out for it occurring again but likely we can close this as no repro when we get around to triaging it if I haven't found anything. 

It's decently likely to have occurred in D:\src\SqlOpsStudioExtensions\extensions\aris\src\wizards\virtualizeData\virtualizeDataModel.ts!hasMasterKey() though - so we could also considering guarding against dbInfo being undefined after the call to loadDatabaseInfo as a precaution.

**Comment by kburtram** [comment]
Please open if this reoccurs.
