### ISSUE TITLE
Notebooks: Attach To Dropdown should have Constant Width

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#4485]
In the notebook, connecting to a database with a really long name. The attach to's width will expand to show something like "fakeServer (thisIsASuperLongDatabaseName)".

We should work with UX to determine a good max-width for the dropdown, and ensure that, on hover, the entire string can be seen.

**Comment by YurongHe** [comment]
We have to make sure hover to show the server name

**Comment by kevcunnane** [comment]
Fit & Finish work for June
