### ISSUE TITLE
Copy paste keys inconsistent behaviour

### ISSUE THREAD

**Issue by 9squirrels** [microsoft/azuredatastudio#4487]
Issue Type: <b>Bug</b>

There are two possible sets of keys for copying and pasting, ctrl+C/ctrl+V, or ctrl+insert/shift+insert (which are great for left handers like me).
For some reason, the ctrl+insert/shift+insert work when copying and pasting from the code window, but do not seem to work when copying from the messages window, whereas ctrl+C works as expected from both.
As a left hander who relies on the ctrl+insert/shift+insert keys for copy/paste, it's a bit frustrating.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1505M v5 @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (19.40GB free)|
|Process Argv|C:\Program Files\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-db-insights|mat|0.2.2
import|Mic|0.5.0
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by alanrenmsft** [comment]
I just verified using the insiders build and copy from results and messages using ctrl+insert and shift+insert both works now.
