### ISSUE TITLE
support Azure China

### ISSUE THREAD

**Issue by zirain** [Microsoft/azuredatastudio#4490]
Issue Type: <b>Feature Request</b>

is there any plan to support Azure China?

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@zirain we do plan to support Azure China in an upcoming release.  We're tracking this request with https://github.com/Microsoft/azuredatastudio/issues/3903.  I'll close this as a duplicate.  Thanks!
