### ISSUE TITLE
Select 1000 Rows not working

### ISSUE THREAD

**Issue by alex0520** [Microsoft/azuredatastudio#4492]
Issue Type: <b>Bug</b>

When I select Select 1000 rows from context menu on a table, nothings happen, the expected behavior is an editor with a query selecting the 1000 rows

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.63GB (6.03GB free)|
|Process Argv|C:\Users\lozanofa\AppData\Local\Programs\Azure Data Studio\azuredatastudio.exe|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@alex0520 could you please check if there are any error messages in the "Help->Developer Tools" Console log?

**Comment by alex0520** [comment]
> @alex0520 could you please check if there are any error messages in the "Help->Developer Tools" Console log?

Hi @kburtram , yeah there is an error
![image](https://user-images.githubusercontent.com/17637479/54389598-754f7800-466e-11e9-94f1-c56deb7623d7.png)

**Comment by kburtram** [comment]
@alex0520 it appears error was raised while generating the SELECT statement script for some reason.  Do you know if there is anything noteworthy about the table causing the error (e.g. column types, permissions, etc.)? Or are you hitting the issue with all tables?

**Comment by alex0520** [comment]
> @alex0520 it appears error was raised while generating the SELECT statement script for some reason. Do you know if there is anything noteworthy about the table causing the error (e.g. column types, permissions, etc.)? Or are you hitting the issue with all tables?

Thanks for your answer @kburtram , it fails with all the tables :(

**Comment by kburtram** [comment]
@Charles-Gagnon do you have any ideas how we could investigate this issue?

**Comment by Charles-Gagnon** [comment]
@alex0520 What type of server is this? Are you able to connect to the server and see what the query being sent is using xevents/profiler?
