### ISSUE TITLE
ADS launched from SSMS using SQL auth - prompts user for password

### ISSUE THREAD

**Issue by shueybubbles** [microsoft/azuredatastudio#4493]
Repro - install both SSMS 18 preview 7 and ADS, make sure ADS is in the machine-wide PATH or has run once. Run SSMS, connect to a server via SQL auth. Right click the server or a database node in SSMS OE, choose Azure Data Studio -> New Query. ADS runs and tries to connect but prompts for the password.
Even though SSMS stores the password in Windows Credential Manager, ADS isn't finding it. I suspect it's using a key that includes the generated connection profile id, while SSMS stored it with an empty id. 
Do we really need to include the profile id in the credential manager key?

**Comment by yualan** [comment]
Documented as Known Issue

**Comment by kburtram** [comment]
Closing older low-impact bugs.  Please reactive if this is still impacting your use-case.
