### ISSUE TITLE
Unable to install SQL notepad feature

### ISSUE THREAD

**Issue by martincroft** [Microsoft/azuredatastudio#4494]
Azure Data Studio Version:1.5.1 insider

Steps to Reproduce:

1. Select servers 
2. Right-click Server name and select  New Notebook
3. Get message Notebook dependancies will be installed in this location
C:\Users\[username removed]\azuredatastudio-python 
4. Click install
5 Get error message 
Installing Notebook dependencies failed with error: 
**Error: self signed certificate in certificate chain**

In location, there is a 0-byte file called python-3.6.6-win-x64-0.0.1.zip

This is probably down to the security( as works laptop without access to local admin) needs a workaround to install from exe

**Comment by kevcunnane** [comment]
@corivera can you take a look? This sounds like an issue behind a corporate firewall. 
- Can we detect and recommend offline install instead?
- Is there a workaround that we can use, e.g. VSCode has some kind of proxy support?

**Comment by corivera** [comment]
Karl posted some workarounds for a similar issue here: https://github.com/Microsoft/azuredatastudio/issues/3723

But doing an offline install is probably better. Here are some setup instructions for doing an offline install on Windows:
1. Download the offline installation package from the following link: https://go.microsoft.com/fwlink/?linkid=2074021

2. Extract the contents of the downloaded archive to a folder of your choice.
Example: C:\User\testUser\azuredatastudio-python

3. Open a command prompt and navigate to the 0.0.1 folder in that location.

4. Run the installLocalPythonPackages.bat script in that folder, supplying the full path to the folder as an argument. Wait for the package installation to complete.
Example: installLocalPythonPackages.bat C:\User\testUser\azuredatastudio-python\0.0.1

5. In Azure Data Studio, run the Open Settings command from the command palette, and update the notebook.pythonPath user setting with the path to the folder selected in step 2.
Example: "notebook.pythonPath": "C:\User\testUser\azuredatastudio-python"

**Comment by martincroft** [comment]
I can confirm those steps fixed the issues. Thanks
