### ISSUE TITLE
Notebook disconnects OE server connection

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4501]
Connect OE server
New Notebook from OE server
New another Notebook from OE server
Add the same connect from Attach To in one of the above Notebook
Close the above two Notebooks

We can see OE server is disconnected.

Expected:
- OE server shouldn't be disconnected.

The changeling here is without knowledge if  the connect is made from notebook when adding it from "Add new connection"

**Comment by chlafreniere** [comment]
This no longer repros.
