### ISSUE TITLE
If two ADS instances are open, second one fails to show logs in Output 

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#4509]
[Insider build testing]

Steps to Reproduce:

1. Open an ADS instance and perform any actions
2. Open Second ADS instance
3. In the second instance  open View --> Output
4. Set dropdown to any of logs (Main/Shared/SqlTools)

Shows following error 
![image](https://user-images.githubusercontent.com/46980425/54391095-32d36e80-4661-11e9-8738-bd33e5326093.png)

Checking at the %appdata% location - the logs file are actually not present for second instance.

**Comment by kburtram** [comment]
@ranasaria any ideas what's happening with this one?  I'm only repro'ing with the SQL Tools Service log.

**Comment by udeeshagautam** [comment]
I tried both bugs (this one and #4510) on today's insiders build. Actually both issues are happening for me - Main and Shared logs show file not found error (on windows) when two ADS instances are open but SQL Tools logs show error even when only single instance is open.

**Comment by udeeshagautam** [comment]
One more note - the problem that Main and shared logs fail to show in 2nd instance is present with VS code as well (seems like an upstream problem) but Sqltools logs not showing with single ADS looks like our problem - should be close this and reopen - #4510 ?

![image](https://user-images.githubusercontent.com/46980425/56380871-2d20f980-61c8-11e9-8ffe-dd8cd3835e9c.png)

**Comment by ranasaria** [comment]
Yes these are two separate issue so I am reactivating #4510.


-  Arvind.

________________________________

**Comment by kburtram** [comment]
I am not able to repro this on the latest builds.  Though I am still seeing something similar to https://github.com/microsoft/azuredatastudio/issues/4510 (with different actual end state).  Please reactive if you're still impacted by this issue.
