### ISSUE TITLE
Untitled count increases at creating new notebook even if previous was not saved

### ISSUE THREAD

**Issue by udeeshagautam** [Microsoft/azuredatastudio#4511]
[Insider Build Testing]
Steps to Reproduce:

1. create a notebook - it says something like untitled-1
2. close it without saving
3. create new notebook - it says untitled-2

This suffix number keeps on increasing even if no notebook is saved till we close and reopen ADS.

(Couldn't find a dup hence opening- if it's a child of existing work item please close it.)

**Comment by rajmusuku** [comment]
Fixed in https://github.com/Microsoft/azuredatastudio/pull/4727
