### ISSUE TITLE
Notebook stuck at changing kernel -insider build

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4513]
Issue Type: <b>Bug</b>

- New notebook
- Change kernel-SQL->PySpark3->Python 3
- Kernel Dropdown stuck at changing kernel

Azure Data Studio version: azuredatastudio 1.5.1-insider (6f1a03587a44b7fddc644f250116514997d95256, 2019-03-14T20:45:05.791Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (132.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
This may be fixed by @kevcunnane's recent PR.
