### ISSUE TITLE
During python installation, kernel changing is failed

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4514]
Issue Type: <b>Bug</b>

Open new notebook, switch kernel from SQL->Python to tigger Python installation.

Kernel dropdown display: Changing kernel, during installationation, got 

         Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error: 1, StdErr Output: The system cannot find the path specified.

Then kernel switches back SQL.

Azure Data Studio version: azuredatastudio 1.5.1-insider (6f1a03587a44b7fddc644f250116514997d95256, 2019-03-14T20:45:05.791Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (49.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by corivera** [comment]
Closing due to no repro.
