### ISSUE TITLE
Connection dialog: connection type dropdown keeps closing when output is updated

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4519]
1. Install an extension with a backend tools service (for example, a new connection provider)
2. Reload Azure Data Studio and you'll see Output constantly updating the number of `...`s in the download
3. While this is happening, open the connection dialog and try to change connection type

You'll find it almost impossible since the output update keeps closing the dropdown somehow. This is really frustrating.

**Comment by Charles-Gagnon** [comment]
Closing this as it should be fixed now for our first-party extensions, they won't grab focus when updating the output window text.
