### ISSUE TITLE
Recent connections list shows loading after delete the entry

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4520]
Issue Type: <b>Bug</b>

Open connection dialog
Right click the connection in Recent connections-> detele
The it shows Loading...

![image](https://user-images.githubusercontent.com/43652751/54397642-6370d380-4674-11e9-8067-71e564030aa7.png)

Reopen it, still in loading...

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (128.82GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
This appears to be fixed in the latest build. Please reactive if the issue still persists.
