### ISSUE TITLE
TS Strict Null Checks complains about missing file

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4522]
See error below - can we update this file? On next merge will this happen again?
```
[16:22:29] Starting compilation in watch mode...

error TS6053: File '/Users/projects/azuredatastudio/src/vs/workbench/parts/terminal/common/terminalMenu.ts' not found.

[16:22:50] Found 1 error. Watching for file changes.
```

**Comment by anthonydresser** [comment]
I believe @MattIrv  was going to bring this file back in at some point.

**Comment by MattIrv** [comment]
I fixed this in the 1.31 merge, just waiting for release work to be done before I bring that into master

**Comment by anthonydresser** [comment]
I believe karl has forked the release branch so its safe to merge into master now, @kburtram

**Comment by kburtram** [comment]
Yes, `master` is open for April changes now.
