### ISSUE TITLE
Stuck at loading for Analyze in Notebook when hdfs node has some issue

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4524]
Issue Type: <b>Bug</b>

Right click csv file in HDFS->Select Analyze in Notebook
Notebook has no content. Kernel, attachTo and editor are loading...
No content shows up

Error in developer tool.
�[93m[main 4:22:50 PM]�[0m Cannot find node status for session: 52.168.28.223,31433_master_sa_SqlLogin_C777F06B-202E-4480-B475-FA416154D458 and node path: 52.168.28.223,31433/52.168.28.223,31433/HDFS/tmp

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (128.85GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
Closing this for now.
