### ISSUE TITLE
Failed to load kernel after close and reopen ADS

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4526]
Issue Type: <b>Bug</b>

Open few notebooks with non sql kernel 
Close ADS
Reopen ADS
Some files failed to load kernel->Kernel Dropdown: No kernel. This is good.
Notification: Could not start session: Invalid response: 403 Forbidden

Then try to change pySpark kernel, got error:  Failed to change kernel due to error: Cannot start a session, the manager is not yet initialized
![image](https://user-images.githubusercontent.com/43652751/54399256-c9605980-467a-11e9-899e-4f57a2973c46.png)

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|255.93GB (128.19GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
The 403 occurs when two servers attempt to be started on the same port
