### ISSUE TITLE
Results and Messages should fully collapse

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4527]
If you collapse both the Results and Messages sections in the query editor you should get the 220 (minimum) pixels they use up back. By default this seems to use about 300px, so if collapsing both saved on this space we'd be doing really well. It's super annoying that I can't minimize, even though I know that I can hide using a keyboard shortcut. 
![image](https://user-images.githubusercontent.com/10819925/54399272-ded58380-467a-11e9-98a2-ebe17883fa58.png)

**Comment by anthonydresser** [comment]
dupe #3177
