### ISSUE TITLE
[View as Chart] Set 'Use column names as labels' by default

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#4529]
In demos and creating insight widgets, user almost always need to have the use column names as labels checkbox enabled. Let's set this as a default

![image](https://user-images.githubusercontent.com/30873802/54400456-227ebc00-4680-11e9-898c-a48c432f9680.png)

**Comment by anthonydresser** [comment]
we should also look at the names of those options (as mentioned #2261) I agree sometimes the naming can be confusing until you understand what the option does.

**Comment by yualan** [comment]
https://github.com/Microsoft/azuredatastudio/issues/2265 looks like it might be a regression
