### ISSUE TITLE
Notebooks / SQL2019 creating too many output channels, and creating before needed

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4535]
Issue Type: <b>Bug</b>

Open a Notebook in Azure Data Studio, go to Output and look at all the output channels:
![image](https://user-images.githubusercontent.com/10819925/54449770-1e987b80-470c-11e9-93c4-7bc6ec36c031.png)

We have 
- dataManagement (this shouldn't be needed, it's the old name so should be removed)
- Jupyter Notebooks (again, old name, we should just use "Notebooks"?)
- Somehow, a 2nd dataManagement
- SQL Server 2019 Preview (even though I didn't do a Data Virtualization scenario)
- scaleoutdataservice (at this point the wrong name as it's probably "DataVirtualizationService")
- MSSQL

The 2 things are:
- Reduce the number of these dramatically. We can remove at least 2, possibly 3 of these
- Stop creating these until we need them. Until we need to send 1st message why are these available? I can understand the channels to tools service but others really can wait until later.
 
Azure Data Studio version: Azure Data Studio 1.5.1-insider (31614247cf341abc9194080d0ab7eb720257fb06, 2019-03-13T21:13:30.723Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.36.1
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3

</details>

**Comment by geleems** [comment]
This is how it looks finally:
![image](https://user-images.githubusercontent.com/19577035/58729362-16acb700-839e-11e9-9247-508be1de9fdb.png)
