### ISSUE TITLE
Create external data from CSV: right-clicked connection not filled in 1st page

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4538]
Steps to Reproduce:

1. Expand to a CSV file in SQL Server big data cluster, right-click and choose `Create External Table from CSV Files`
2. Expect to see the connection you right-clicked from shown in the wizard, but instead have to select it from the dropdown.

Can we fix this? It seems like a gap from when we ported the unified connection work over.

![image](https://user-images.githubusercontent.com/10819925/54451564-51447300-4710-11e9-9462-99c09b018d66.png)

**Comment by corivera** [comment]
Fixed
