### ISSUE TITLE
Notebook Save As loses connection context

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4539]
Issue Type: <b>Bug</b>

1. Create a new Spark notebook, e.g. from Analyze in Notebook
2. Run the cell, it'll execute as expected (for Spark this'll take a while as the session has to start on the remote)
3. Save the notebook with a proper name
4. Run cell again

Expected:
- Notebook name changes but don't need full reload
- On running cell 2nd time, it immediately runs / you inherit the existing spark context

Actual:
- It does a close & reopen, and there's visible loading spinner while it creates new session & kernel
- Running cell starts a brand new session - any context in the previous one is lost.

We need to known issue this for March. It's technically a regression (because we weren't a "real" editor before, we got away without this happening).

Azure Data Studio version: Azure Data Studio 1.5.1-insider (4014c1d0abcae1a621480dcfbea278497343d647, 2019-03-15T07:13:26.881Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv|-psn_0_3511129|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.36.1
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0

</details>

**Comment by kevcunnane** [comment]
I'd suggest this as a stretch for June release

**Comment by YurongHe** [comment]
Query editor loses the connection info too.
