### ISSUE TITLE
Numbering for new "analyze in notebook" notebooks

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4540]
I use the "analyze in notebook" button, and I don't save the notebook. I just close it.

Now, when I do "analyze in notebook" again. I'm expecting "Notebook-1" again. However, it counts up.
<img width="1478" alt="Screen Shot 2019-03-15 at 11 15 16 AM" src="https://user-images.githubusercontent.com/28786161/54452994-9f0eaa80-4713-11e9-8238-a01f51c030c8.png">

And in the left view tab, it says I have 11 UNSAVED, and there's an "11" in the left bar on the notebook icon. But I only have 3 things open? 
<img width="91" alt="Screen Shot 2019-03-15 at 11 15 57 AM" src="https://user-images.githubusercontent.com/28786161/54453045-b64d9800-4713-11e9-91b6-756ed35c9c5d.png">

**Comment by amthomas46** [comment]
<img width="1410" alt="Screen Shot 2019-03-15 at 11 27 42 AM" src="https://user-images.githubusercontent.com/28786161/54453818-5ce66880-4715-11e9-8f85-0cecd299f11b.png">

(Just an update, I close all of the files, and the numbering still continues up)

**Comment by chlafreniere** [comment]
@amthomas46 can you still repro this issue?

**Comment by amthomas46** [comment]
I haven't been able to repro since I switched to using unified connection @chlafreniere

**Comment by chlafreniere** [comment]
Thanks, @amthomas46. Closing this for now then.
