### ISSUE TITLE
Webviews not including stylesheet references even though it works in VSCode

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4545]
Issue Type: <b>Bug</b>

1. @Danmarshall has an extension he's working on that opens a webview. Get that from him to debug
2. Use it to open a webview which has a fully qualified Stylesheet path
3. The styling isn't applied, but it's working in VSCode

@MattIrv is this a merge issue? Any ideas of the cause?

Azure Data Studio version: Azure Data Studio 1.5.1-insider (4014c1d0abcae1a621480dcfbea278497343d647, 2019-03-15T07:13:26.881Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.36.1
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is impacting an extension under active development.
