### ISSUE TITLE
Execution count is 2 though only run cell once

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4549]
Issue Type: <b>Bug</b>

1. Create a new notebook
2. Add a code cell
3. Change kernel to PySpark3
4. Connect to a big data cluster
5. Exectue the code cell
6. The execution count is 2. Not 1. Sql Kernel has no issue.
   Analyze in Notebook and run the cell. Got execution count 2 as well.

![image](https://user-images.githubusercontent.com/43652751/54462553-6bd91500-472d-11e9-8788-c45b4f199fda.png)

Azure Data Studio version: azuredatastudio 1.5.1 (a1d8bae6543147d70b60d60e453c8cebcb3bb256, 2019-03-15T19:05:37.674Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (51.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
This is by design.
