### ISSUE TITLE
Notebooks: New Cell can cause editor tabs to disappear

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4552]
Issue Type: <b>Bug</b>

This is a fun one:
- Open a Notebook editor and query editor side by side
- type `select * from sys.tables` into the query editor, and run so the messages / results show
- Click the `+Code` button to add a new code cell to the notebook
- The editor bar disappears! 
- You have to close the query editor for it to go back to normal.

![image](https://user-images.githubusercontent.com/10819925/54463776-6bdb1400-4731-11e9-9c24-4aaa687a6bdd.png)

This only happens for Notebook + Query, not Notebook + Notebook or Query + Query. I have _no_ idea why this is happening, and since there's a workaround it's not a March blocker. Still it is bizarre and should be fixed.

Azure Data Studio version: Azure Data Studio 1.5.1-insider (4014c1d0abcae1a621480dcfbea278497343d647, 2019-03-15T07:13:26.881Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.36.1
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
I took a super quick look at this, and code/markdown cells will both have this issue:

```
     private setFocusAndScroll(): void {
		if (this.cellModel.id === this._activeCellId) {
			this._editor.focus();
			this._editor.getContainer().scrollIntoView();
		}
	}
```

Commenting out the call to this method solves the problem above, so somehow the calculations around scrolling aren't working when editors are displayed while in a split view.

**Comment by kevcunnane** [comment]
Fit & Finish for June

**Comment by YurongHe** [comment]
Can't repro it. Everything is working fine.
