### ISSUE TITLE
Option to disable autocommit

### ISSUE THREAD

**Issue by gbellini79** [microsoft/azuredatastudio#456]
- SQL Operations Studio Version: sqlops 0.25.0 (c9067a0bafbfdd33388c5c3ce70c7b2afa32f367, 2018-01-04T01:29:29.876Z)
- OS Version: Windows_NT x64 10.0.16299
---

An option to disable autocommit, like the "SET IMPLICIT_TRANSACTIONS" option in SSMS, would be useful.

**Comment by kburtram** [comment]
The "SET IMPLICIT_TRASACTIONS" option is now available.
