### ISSUE TITLE
Results pane height and scrolling (auto adjust rows result height)

### ISSUE THREAD

**Issue by luismiguelgilbert** [microsoft/azuredatastudio#4570]
Issue Type: <b>Feature Request</b>

When writintg stored procedures, I usually resize results pane (so I have more space in editor).
It's not nice that after I resize results pane to smaller size, it adds a second scroll to rows section, so I'm force to scroll in 2 scrolls... It's not comfortable...

I suggest that results row should "auto adjust height", so there is not need to scroll in differents scrolls.

This first image is on normal size:
![image](https://user-images.githubusercontent.com/20174916/54495782-116ac080-48b5-11e9-83cd-f07b25761014.png)

This second image is resized:

![image](https://user-images.githubusercontent.com/20174916/54495795-3bbc7e00-48b5-11e9-837d-e895fef74355.png)

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
We've made several improvements to the query grid regarding spacing and scrolling.  The two scrollbar issue described here should not occur on current builds.   Please let us know if you're still impacted by this issue.
