### ISSUE TITLE
SQL Agent with single step set to go to the next step and wont change - Multiple issues

### ISSUE THREAD

**Issue by martincroft** [Microsoft/azuredatastudio#4574]
Version: 1.5.1-insider (user setup)
Commit: 31614247cf341abc9194080d0ab7eb720257fb06
Date: 2019-03-13T21:24:09.603Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 6.1.7601

There was several bugs found when trying to create a job ( didnt know if should have raised seperate tickets)

 - summarised below

- Jobs missing steps that had been created

- Deleted job still showing even after refresh and alllowing access to edit

- Couldn't save change to job step on success action - stayed the same

- Job owner was showing incorrectly between Azure Data Studio and management studio

Steps to Reproduce:

1. Create a new SQL Agent Job - Click + New Job
![image](https://user-images.githubusercontent.com/30621653/54520788-65cb7a00-4961-11e9-8291-a1ad42003148.png)
2 Add new step add details and click OK
![image](https://user-images.githubusercontent.com/30621653/54520837-84317580-4961-11e9-9395-9e59200cf78d.png)

[Note can't use the Run As box will not select anything]
3 Click ok 
![image](https://user-images.githubusercontent.com/30621653/54520937-bc38b880-4961-11e9-9589-3e97eaf8ca6f.png)

4 I realised at this point I should have gone into and edited the job to step to complete. Filter the job and Edit job 

5 I noticed recreating these steps another issue has occurred, going back into edit the job it shows as there are 0 steps 

![image](https://user-images.githubusercontent.com/30621653/54521330-9e1f8800-4962-11e9-8d25-5a8fddba6bbb.png)

Management studio disagrees
![image](https://user-images.githubusercontent.com/30621653/54521432-d32bda80-4962-11e9-923e-4ba57f39bcf5.png)

6 Click on Edit Job the job owner i set as SA is showing as my AD account (obfuscated to remove company details)

![image](https://user-images.githubusercontent.com/30621653/54521521-fe162e80-4962-11e9-8bc5-343fbf0c6b6b.png)

however as you can see management studio shows correctly 

![image](https://user-images.githubusercontent.com/30621653/54521644-403f7000-4963-11e9-8414-ce38406e1fcc.png)

7 I delete the job through management studio, refresh and it is no longer there. I go back in Azure Data studio and hit refresh and it still shows the job.  I redo the filter to "test job" and it still appears. I can click on it and it allows me to edit it, however it wont let me save it. 

Microsoft.SqlServer.Management.Smo.FailedOperationException: Attempt to retrieve data for object failed for Server 'FCL-SQL-VC200A'. ---> Microsoft.SqlServer.Management.Smo.MissingObjectException: The Job 'Test Job' does not exist on the server. at Microsoft.SqlServer.Management.Smo.Server.GetSmoObjectRec(Urn urn) at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn) --- End of inner exception stack trace --- at Microsoft.SqlServer.Management.Smo.Server.GetSmoObject(Urn urn) at Microsoft.SqlTools.ServiceLayer.Agent.JobData.get_Job() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\JobData.cs:line 688 at Microsoft.SqlTools.ServiceLayer.Agent.JobData.CheckAndLoadGeneralData() in D:\a\1\s\src\Microsoft.SqlTools.ServiceLayer\Agent\Jobs\JobData.cs:line 762 at Microsoft.SqlTools.ServiceLayer.Agent.JobData..ctor(CDataContainer data, AgentJobInfo jobInfo, ConfigAction configAction) in D:\a\1\s\src\Microsoft.SqlTools.Service...

I try and recreate the job and the same thing occurs.

My original issue was I was unable to change the job step to quite the job reporting success as each time I did it did not save the change.

**Comment by MattIrv** [comment]
Thanks for this report!

@abist tagging you in this in case you're working on any of these or have more info about any of them

**Comment by abist** [comment]
These should be fixed in the next release of the extension.
