### ISSUE TITLE
Can't expand HDFS node after vscode merge, because of "self signed certificate in certificate chain"

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4576]
Issue Type: <b>Bug</b>

1. Connect big data cluster master
2. In OE, expand the server
3. Expand HDFS node, got error: "self signed certificate in certificate chain"
![image](https://user-images.githubusercontent.com/43652751/54550085-982ca580-4968-11e9-9f15-047a514412b5.png)

vscode issue: https://github.com/Microsoft/vscode/issues/3492

Workaround is changing http:ProxySupport: on to unblock us

![image](https://user-images.githubusercontent.com/43652751/54550362-18530b00-4969-11e9-88c5-0d0a88cbd802.png)

This is blocking issue to us. Insider build wouldn't work. We have to document this.

Azure Data Studio version: azuredatastudio 1.5.1 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (45.73GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
@geleems Is this related to your work item in this area?

**Comment by geleems** [comment]
I cannot repro this.
It works fine.
![image](https://user-images.githubusercontent.com/19577035/59399939-9fd2cf00-8d4a-11e9-854e-76f1a9b8f3a2.png)
