### ISSUE TITLE
add docker extension from visual studio code

### ISSUE THREAD

**Issue by bruce-sqlwork** [microsoft/azuredatastudio#4578]
Issue Type: <b>Feature Request</b>

as many of are running sqlserver in a docker image, having the docker support in azure data studio would be handy.

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

**Comment by anthonydresser** [comment]
I believe we do have the docker extension (the language syntax). What specific docker features are you missing?

**Comment by bruce-sqlwork** [comment]
I use the one for visual studio code to start, stop my Sqlserver docker container, but would like to install it in azure data studio.

-- bruce

**Comment by anthonydresser** [comment]
Sounds like the ask here is to port the non-built in docker extension. https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer

**Comment by bruce-sqlwork** [comment]
You are correct. 

-- bruce

**Comment by SQLvariant** [comment]
> Sounds like the ask here is to port the non-built in docker extension. https://marketplace.visualstudio.com/items?itemName=formulahendry.docker-explorer

I've been using the [microsoft/vscode-docker](https://marketplace.visualstudio.com/items?itemName=PeterJausovec.vscode-docker) Docker extension, and it works pretty well for me.  I went ahead and [opened a Feature Request](Feature Request) on their repo asking them to add their extension to the ADS Marketplace.  I'm hopefuly that y'all will be able to make this happen soon 🙂

**Comment by anthonydresser** [comment]
@bruce-sqlwork per @SQLvariant you can sideload the vsix off vscode's marketplace into Azure Data Studio and it should work. We'll need to work with the extension owners in order to get it to show up as a downloadable extension in Azure Data Studio.

**Comment by yankyhoffman** [comment]
I fully agree with the OP that having this extension `ms-azuretools.vscode-docker` to work in Azure Data Studio would be a great help, as I am on Linux and am using MS SQL Server thru docker and I need to use 2 tools to manage it (VSCode to get access to the docker extension, and Azure Data Studio to access the DB).
I tried sideloading it but I get this error
```
Unable to install extension 'ms-azuretools.vscode-docker' as it is not compatible with Azure Data Studio '1.14.1'.
```
