### ISSUE TITLE
Licence change?

### ISSUE THREAD

**Issue by olafura** [Microsoft/azuredatastudio#4581]
Now that there is support for postgres under MIT licence, I'm wondering if you are considering a change of licence.

I'm don't know how to really intrepid the licence it seems like it's permissive in some parts and really restrictive in other parts, to the point where all the forks are illegal. I'm not a lawyer just a developer so I couldn't say. But it just means I'm not going to touch the source code as is.

**Comment by kburtram** [comment]
@olafura we're tracking this request in https://github.com/Microsoft/azuredatastudio/issues/102.  I'll close as a duplicate.  (*I'm not a lawyer either so I don't really have anything substantive to add.* 😄)

**Comment by olafura** [comment]
@kburtam thank you so much I tried searching but couldn't find the issue.
