### ISSUE TITLE
Notebook SQL result grid sizing 

### ISSUE THREAD

**Issue by JanosBerke** [Microsoft/azuredatastudio#4583]
Issue Type: <b>Feature Request</b>

It would be great if the SQL code result set grid can be resized by double clicking on a cell, like in SSMS.

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

**Comment by JanosBerke** [comment]
It applies to notebooks.

**Comment by chlafreniere** [comment]
This has been fixed with #4790, and is currently in our insiders builds. Will be included in our next stable release.
