### ISSUE TITLE
Associate SQL files on installation

### ISSUE THREAD

**Issue by way0utwest** [microsoft/azuredatastudio#4584]
Issue Type: <b>Feature Request</b>

Provide an option, per Ike Ellis, MVP, to associate all .SQL files (and notebook files) with ADS during installation.

Azure Data Studio version: azuredatastudio 1.4.5 (887f4e8985023602e599cf86bdb44df48bb28569, 2019-02-12T06:20:08.633Z)
OS version: Windows_NT x64 10.0.17134

**Comment by anthonydresser** [comment]
I believe this should be the case today. @kburtram

**Comment by kburtram** [comment]
This can be accomplished by setting the `Register Azure Data Studio as an editor for supported file types` checkbox during setup.  This can be setup in the Windows shell manually if you don't wish to rerun the installer.

![image](https://user-images.githubusercontent.com/599935/59074080-bd9dc100-887e-11e9-9f95-4ddd9baddea0.png)
