### ISSUE TITLE
Add file associations for .SQL files and .ipynb files to Azure Data Studio installation

### ISSUE THREAD

**Issue by IkeEllis** [Microsoft/azuredatastudio#4585]
Issue Type: <b>Feature Request</b>

I want ADS to open SQL files, not SSMS.

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17134

**Comment by anthonydresser** [comment]
dupe #4584
