### ISSUE TITLE
Add ability to clear all code results in notebook

### ISSUE THREAD

**Issue by jovanpop-msft** [Microsoft/azuredatastudio#4586]
- Azure Data Studio Version: 1.5.1

Steps to Reproduce:
1. Create notebook with multiple code cells and execute every cell to show results and they will be shown.
2. If I need to reset the notebook and start again (like repeat with the different connection) I need to click on every code cell to clear the results and get the clean initial notebook. 

Please add "clean all" results with a single button.

**Comment by rajmusuku** [comment]
Fixed in https://github.com/Microsoft/azuredatastudio/pull/4705
