### ISSUE TITLE
Multiple result set and chart controls bug

### ISSUE THREAD

**Issue by JanosBerke** [microsoft/azuredatastudio#4587]
Issue Type: <b>Bug</b>

When I run a multi result set query and trying to visualize as a chart, in some cases the control with the dropdown list with the chart types are not available, ui has some discrapancy

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz (4 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.93GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by JanosBerke** [comment]
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
> * [Preserve chart settings when re-running query (#185)](https://www.github.com/Microsoft/azuredatastudio/issues/185)

Nope, it is a different issue.

**Comment by jpomfret** [comment]
I have this issue for simple queries also.

![image](https://user-images.githubusercontent.com/981370/55581564-2df75d00-56eb-11e9-93c9-865a22d29286.png)

**Comment by alanrenmsft** [comment]
@jpomfret , Are you still seeing this issue with latest ADS?

**Comment by jpomfret** [comment]
Don't remember exactly what I was doing, but no it seems to work fine now. Thanks
