### ISSUE TITLE
SQL Notebook - support for earlier versions of SQL Server & additional Data Analyst scenarios!

### ISSUE THREAD

**Issue by MsSQLGirl** [Microsoft/azuredatastudio#4589]
Issue Type: <b>Feature Request</b>

Feedback:

1. Notebooks are awesome for Data Analysts. However, the instructions to get this started require SQL Server 2019 Big Data clusters on kubernetes. Barrier to entry is really high (I'm just a Data Analyst!!)

2. A lot of customers are still using in-market SQL Server versions (<= 2017). It'd be good to have this supported for SQL notebook.

3. What's the roadmap for supporting "notebook" sharing? Here's an example where ipynb is published to github along with the results (taking the snapshot of when it was last run by the author). 
https://github.com/barbagroup/AeroPython/blob/master/lessons/01_Lesson01_sourceSink.ipynb

Thank you!

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kevcunnane** [comment]
Julie, for 1 and 2 is this a doc request? All supported SQL Server versions (SQL Server 2008 and up) are supported with no install of other dependencies needed.

For sharing, right now Git / source control is the story. We've had some requests for "save to this data source", for example HDFS as a log output for what you ran, or it sounds like in this case it's to save a copy to Github? Would love to know more about the specifics here.

**Comment by MsSQLGirl** [comment]
Kevin,

I've just downloaded the latest version (version 1.5.1) and confirmed that Issues 1 and 2 are no longer there :) This is awesome!! Thank you for fixing this. Yes, this becomes a documentation issue now. 

For sharing, let me spend some time tinkering with Git right now and see if there are extensions that can be enabled etc to achieve my scenario below. 
I'm thinking of saving the output as at the time that the Notebook was last ran. There are a couple of scenarios that are at play here. For example, a data analyst writes a notebook to analyze a number of datasets and comes up with a conclusion - and would like to share the breakdown of the analysis as well as the conclusion (insights) to the entire team. So, this would require the ability to share the notebook as well as the output as at the time it was ran. If another person clones a copy and tried to repro, it'd be good if they could compare if they get the same results (auditing).  

Thanks again for the quick response and for bringing Notebooks in Azure Data Studio. Very excited to see notebook scenarios!!

**Comment by chlafreniere** [comment]
Thanks so much for the feedback :). looks like the issues in the original issue have been addressed.

**Comment by MsSQLGirl** [comment]
Yaaaaayyy!! Thank you, thank you, thank you! 👏
