### ISSUE TITLE
Multiple results when constantly pressing F5

### ISSUE THREAD

**Issue by phandrzejewski** [microsoft/azuredatastudio#4594]
- Azure Data Studio Version: 1.5.1

Steps to Reproduce:
1. Open a new Notebook (or an existing one) and insert a code cell

2. Use for example this query:
`SELECT * FROM sys.schemas`

3. Press F5 (really fast) a couple of times and then it randomly writes two tables as an output or sometimes a table and below the table 'Query failed: The Operation was canceled.'
Screenshot 1:
![tableAndError](https://user-images.githubusercontent.com/48710674/54604553-4f97e980-4a47-11e9-9b73-bdc7a11c975b.png)

Screenshot 2:
![twoTables](https://user-images.githubusercontent.com/48710674/54604554-50308000-4a47-11e9-8e68-5f7d0dfb48ba.png)

**Comment by Vaelek** [comment]
This is not specific to notebook, nor repeatedly pressing F5. I quite frequently see this, sometimes up to 3 times, from a single normal query execution

**Comment by kburtram** [comment]
@anthonydresser I though we made changes so this was longer happening.  Do you think this is the same result streaming issue we previously investigated?  Or something different?

**Comment by kburtram** [comment]
I am no longer able to repro.  Please let me know if the problem persists on a current build.  Thanks for reporting this bug.
