### ISSUE TITLE
Network-related error trying to connect to SQL Server 2008 R2 with Windows Authentication on Windows 10

### ISSUE THREAD

**Issue by StarkBotha** [Microsoft/azuredatastudio#4595]
I have a SQL Server 2008 R2 server running. I cannot find any information on whether or not Azure Data Studio supports 2008 R2 so failing that im assuming that it does.

SSMS 17.9.1 is able to connect to the db server:
![image](https://user-images.githubusercontent.com/862224/54605862-f1710380-4a52-11e9-8b02-29a9c5344e80.png)

![image](https://user-images.githubusercontent.com/862224/54605886-ffbf1f80-4a52-11e9-8edb-dd76eca93c12.png)

But Azure Data Studio gives me network-related or instance-specific error:
![image](https://user-images.githubusercontent.com/862224/54605931-12d1ef80-4a53-11e9-80d2-ac8f880ffb0b.png)

![image](https://user-images.githubusercontent.com/862224/54605941-1c5b5780-4a53-11e9-853e-df0afb5f12b9.png)

**Comment by MattIrv** [comment]
@StarkBotha for SQL Server 2008 R2 you'll need to have at least SP3 installed for Azure Data Studio to connect. Do you know if this server was running SP3?

We had this requirement documented somewhere at one point but I can't find it now. @yualan do you know where our documentation shows minimum supported versions for SQL Server? We should probably make it more discoverable

**Comment by kburtram** [comment]
We only officially support SQL Server 2014+, but as pointed out it should work against SQL Server 2008 with SP3.  I'll close this since we aren't actively looking at issues against this server version.
