### ISSUE TITLE
PowerShell Extension doesn't appear in Extension Search

### ISSUE THREAD

**Issue by brettmillerb** [Microsoft/azuredatastudio#4596]
- Azure Data Studio Version:
Version: 1.5.1 (system setup)
Commit: 6a500715a7f2a9c5466d66b3cc312308bf59846d
Date: 2019-03-16T01:14:53.392Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17134
Steps to Reproduce:

1. Search for any of the following in the extensions:
PowerShell
Power Shell
Power
Shell

None of these show the PowerShell extension. Searching through the popular extensions allows you to be able to Install however.

**Comment by alanrenmsft** [comment]
@brettmillerb Thanks for reporting the issue, we have fixed it.
