### ISSUE TITLE
Unhandled exception running query on PostreSQL

### ISSUE THREAD

**Issue by CodingGorilla** [Microsoft/azuredatastudio#4597]
Issue Type: <b>Bug</b>

The query:
-------------------
select  id
,data
,mt_last_modified
,mt_version
,mt_dotnet_type
,mt_doc_type
from docstore.mt_doc_datalist
LIMIT 1000

Results:
----------
Started executing query at Line 1
Commands completed successfully
Unhandled exception while executing query: 'dict' object has no attribute 'encode'
Total execution time: 00:00:00.382

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen 7 1800X Eight-Core Processor          (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.95GB (46.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by MattIrv** [comment]
@CodingGorilla is one of these columns `jsonb`? If so see this issue tracking it in the Postgres extension repo: https://github.com/Microsoft/azuredatastudio-postgresql/issues/94

**Comment by CodingGorilla** [comment]
Yes, it's a table created by [Marten](https://github.com/JasperFx/marten).  Here's a quick dump of the table schema if it helps:

```
CREATE TABLE docstore.mt_doc_datalist
(
    id uuid NOT NULL,
    data jsonb NOT NULL,
    mt_last_modified timestamp with time zone DEFAULT transaction_timestamp(),
    mt_version uuid NOT NULL DEFAULT (md5(((random())::text || (clock_timestamp())::text)))::uuid,
    mt_dotnet_type character varying COLLATE pg_catalog."default",
    mt_doc_type character varying COLLATE pg_catalog."default" DEFAULT 'BASE'::character varying,
    CONSTRAINT pk_mt_doc_datalist PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;
```

**Comment by CodingGorilla** [comment]
Yes, that seems to be the issue.  I will close this one.
