### ISSUE TITLE
Connection input boxes have no border in several color schemes

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4600]
Issue Type: <b>Bug</b>

- Install the High Color Queries or Powershell extensions and use the high color / powershell ISE themes
- Open connection dialog
- Note all the input boxes are missing borders.

![image](https://user-images.githubusercontent.com/10819925/54631427-3a1bc300-4a39-11e9-969a-0fd0c2381ee9.png)

We should have sensible default values to fall back to for these themes, or use a different color key to ensure this doesn't regress.

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.23GB free)|
|Process Argv|-psn_0_3892150|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.3
newdatabase|kev|0.0.3
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.11.0
PowerShell|ms-|1.11.0

(1 theme extensions excluded)

</details>

**Comment by anthonydresser** [comment]
What about the input boxes in the search menu? Some themes do this intentionally.

**Comment by kevcunnane** [comment]
Search looks OK because it's got a darker background:
![image](https://user-images.githubusercontent.com/10819925/54635015-8a4a5380-4a40-11e9-94b5-1290020d5ade.png)


This isn't intentional, it's because we use white as background in our dialogs. This means they're not fully compatible with VSCode's themes. It "looks" like a bug and we should handle it so we don't keep running into this issue.

**Comment by anthonydresser** [comment]
We should probably use the dark color of the viewlets for our background in the dialogs.

**Comment by kburtram** [comment]
Perhaps the background color should be themable.  I'm not a big fan of using the gray color as the dialog background, I'd personally rather resolve this bug a different way.

**Comment by kburtram** [comment]
The built-in themes are all showing the connection dialog controls with clear borders.  If extensions provide additional themes that don't render control borders it would be preferable to see the theme updated to work similar to the default themes.
