### ISSUE TITLE
Client Certificate authentication for Postgres

### ISSUE THREAD

**Issue by cocowalla** [Microsoft/azuredatastudio#4603]
Postgres support client certificate authentication, and login with this method is supported in other client tools such as pgAdmin.

It would be great to see client certificate authentication for Postgres in Azure Data Studio.

**Comment by alanrenmsft** [comment]
@cocowalla , for PG extension, Could you please open issues in PG extension's GitHub repo? https://github.com/Microsoft/azuredatastudio-postgresql/issues

I am going to close this one. @akamath46297, FYI.

**Comment by cocowalla** [comment]
@alanrenmsft apologies, the Postgres support is so well integrated that I forgot it was an extension 😆

**Comment by kevcunnane** [comment]
Alan - I think you can use "Move issue" functionality to move the issues between repos instead of duplicating. Might be good to try out / get used to since I expect it'll happen plenty for PG issues.

**Comment by cocowalla** [comment]
@kevcunnane sorry, I already opened [#96](https://github.com/Microsoft/azuredatastudio-postgresql/issues/96) 🙉
