### ISSUE TITLE
Query Shortcuts 

### ISSUE THREAD

**Issue by jjwillis** [microsoft/azuredatastudio#4605]
Issue Type: <b>Bug</b>

When executing query shortcuts using key bindings, the results work the first time, but subsequent attempts fail.  This worked properly prior to March release.

Steps to reproduce the problem.
Setup key binding:
        "key": "ctrl+5",
        "command": "-workbench.action.focusFifthEditorGroup"
        "key": "ctrl+5",
        "command": "workbench.action.query.shortcut5"
Add shortcut to user preferences:
"sql.query.shortcut5": "Select top 5 * from "

Create a table for testing and insert rows:
create table #tablename (
  id int not null primary key, -- primary key column
  columnname2 nvarchar(50) not null,
  columnname3 nvarchar(50) not null);
insert into #tablename (id, columnname2, columnname3) values(1, 'row1','r1'), (2, 'row2','r2')

Highlight #tablename and press Ctrl+5 multiple times.

Behavior experienced: The first time Ctrl+5 is pressed, results show 2 rows and messages show 2 rows affected.  
Started executing query at Line 1
(2 rows affected)
Total execution time: 00:00:00.004

The second time Ctrl+5 is pressed, a second results set appears with no records and a second message is appended to the message that shows:
Started executing query at Line 1
(2 rows affected)
Total execution time: 00:00:00.004

Any further attempts to press Ctrl + 5, no matter what table is highlighted, has the same results.  Executing something in the query window, like a blank line, will reset this action.

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (23.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by jjwillis** [comment]
Same issue reported in #4704

**Comment by jjwillis** [comment]
@kburtram This issue has been resolved with #4704 or #5480.

**Comment by kburtram** [comment]
Closing based on previous comment referring to related fixes.
