### ISSUE TITLE
Support "Analyze in Notebooks" from the file explorer.

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#4609]
Issue Type: <b>Bug</b>

We need to be able to launch notebooks for CSV and other files from the file explorer in VS Code. This should operate similarly to Analyze in Notebook in the HDFS object explorer hierarchy.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/54650394-6ea87280-4a6b-11e9-81db-c3edc32c624e.png">

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.38GB free)|
|Process Argv|-psn_0_49164|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0
sql-vnext|Mic|0.11.0

</details>

**Comment by kevcunnane** [comment]
Rony can you clarify?
- new file, use .ipynb as file name works fine
- click on notebook works fine

Can you clarify what you want and where? For example new button on open editors section? Or on the folders section?

**Comment by ronychatterjee** [comment]
Yeah Let me clarify -

Bring the Analyze in Notebooks for local files we already have for HDFS.

Thinking long term how we integrate PROSE here and make it more permissible in our experiences. We should possibly replace our code with the one generated from PROSE as I envision folks would be running into issues a lot with our generated code and let PROSE handle this.

**Comment by kevcunnane** [comment]
Great - updated title and details to reflect this.

**Comment by chlafreniere** [comment]
@ronychatterjee to determine exact scenario
