### ISSUE TITLE
T-SQL Notebook. Add a new connection doesn't work

### ISSUE THREAD

**Issue by drsqlgithub** [Microsoft/azuredatastudio#4613]
Issue Type: <b>Bug</b>

In a T-SQL Notebook, in the Attach to menu, choose Add New Connection. Enter the details, and it appears to work. Close the notebook and reopen it, and in the list was a link to the master database (I already had a connection . (master), so it could be a dup of that in memory?)  The only way I could get attach to to have my database was to enter it into the servers list manually

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (10.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
@YurongHe if you could try to repro that'd be great

**Comment by YurongHe** [comment]
Connect to master and other user db are different connections. The connection made from Add new connection will be closed when notebook closes. If you want to open notebook from the specific db by default when right click the server, please connect that db when make server connection.

**Comment by drsqlgithub** [comment]
I am not sure that we are on the same page, and after reading the description, I may not have been clear.  The problem is that I end up with multiple . (master) entries when I come back in. And if I use add new connection, the connection seems like it is there.. Close and reopen the notebook, and it shows as . (master) in another entry. 

![image](https://user-images.githubusercontent.com/29211339/55032565-88a40100-4fe7-11e9-9541-a733510d8edb.png)
