### ISSUE TITLE
Results overlaps a horizontally split window

### ISSUE THREAD

**Issue by Ungerfall** [microsoft/azuredatastudio#4615]
Running a query of the left window the results will overlap the right window. However, that behavior only appeared once.

![image](https://user-images.githubusercontent.com/8143895/54672092-c3ea8f80-4b10-11e9-8be2-e3f8f5bae309.png)

- Azure Data Studio Version:
Version: 1.5.1 (user setup)
Commit: 6a500715a7f2a9c5466d66b3cc312308bf59846d
Date: 2019-03-16T01:14:53.392Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:
Cannot reproduce the issue. Appeared once.

**Comment by kburtram** [comment]
This should be fixed in the current builds.
