### ISSUE TITLE
Extra } added at the end of a notebook file

### ISSUE THREAD

**Issue by tgrohser** [Microsoft/azuredatastudio#4618]
Issue Type: <b>Bug</b>

When you save a Notebook file there are two }} at the end of the file, the second one has no matching open { causing more restrictive readers (like pandoc) from reading it

Azure Data Studio version: azuredatastudio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:14:53.392Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (8.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.2
whoisactive|Mic|0.1.1

</details>

**Comment by kevcunnane** [comment]
Repro:
- Create a new notebook with 1 cell and save it
- Add text to the cell and save again
- You'll see the extra `}`

This is likely an issue with new text file service integration - we're applying an edit with the length of the doc, and we are always off by 1 after the initial save in terms of column length. This means we don't erase the final `}`. 
- Should be a quick fix
- Should add a test.

**Comment by rajmusuku** [comment]
Fixed in PR https://github.com/Microsoft/azuredatastudio/pull/4627
