### ISSUE TITLE
Allow export of data from SQL Notebook

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/azuredatastudio#4633]
After running a query in a SQL Notebook (March 2019 release), I want to export that data to XLSX or other formats, or copy to the clipboard with or without headers.

**Describe the solution or feature you'd like**
The same command buttons should appear on the right side of the results in the Notebook, and the same right-click menu should exist.

**Describe alternatives you've considered**
Tried pressing Ctrl+A with the focus on the results, but that selects the entire notebook, not the current results.

**Comment by chlafreniere** [comment]
We shipped this feature in our September release.
