### ISSUE TITLE
Error Notification for extensions that prompt for website

### ISSUE THREAD

**Issue by anthonydresser** [Microsoft/azuredatastudio#4634]
For extensions that require the user to download separately (the app doesn't do the downloading), we are showing a error message. This is probably caused by the vscode merge which no longer requires window reloads with installing extensions.

**Comment by alanrenmsft** [comment]
to be clear, this happens when user clicks the install button for the extensions that are not hosted by us, the web browser will be opened with the following error message in ADS:
![image](https://user-images.githubusercontent.com/13777222/55360796-46b50800-548a-11e9-9376-f4e65052adcd.png)
