### ISSUE TITLE
Failed to show notebook document untitled:Notebook-x

### ISSUE THREAD

**Issue by rajmusuku** [Microsoft/azuredatastudio#4635]
Create an untitled notebook , we see following exception from extension

![image](https://user-images.githubusercontent.com/44002319/54724471-87c32900-4b28-11e9-83b2-50fb3dd50d52.png)

**Comment by chlafreniere** [comment]
This is due to the latest VS Code merge. Looks like there are exceptions around editorPosition, so that's probably a place to start.
