### ISSUE TITLE
Notebooks: Can we Ctrl+F to search across the whole notebook (markdown + code)?

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4637]
- Azure Data Studio Version:

Steps to Reproduce:
- Open notebook document
- Hit Ctrl+F, nothing happens
- Click to enter code cell, ctrl+f just does that cell

Would like a way to search across the whole document which we are missing.

**Comment by chlafreniere** [comment]
This is a dupe.
