### ISSUE TITLE
Notebooks - Collapsible sections 

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#4641]
**Is your feature request related to a problem? Please describe.**
Please add the ability to collapse the code and text sections!!!

**Describe the solution or feature you'd like**
I have only used T-SQL notebook from Insider edition but having a 25 line query on a small monitor for remote access to environments (RDP sessions) it is unusable when we have to scroll back and forth.

I would say for code the result and the code should be separately collapsible, along with the whole code section.

**Describe alternatives you've considered**
I know of none.

**Comment by Vaelek** [comment]
I came here intending to request that the code and results blocks in notebooks be resizable. I feel that would be much more useful than just simply collapsible.

**Comment by jwcao** [comment]
I would love to be able to add a title to a code section and collapse it. I have several queries that I rarely change but I run throughout the day, and having them all organized in a single notebook would be great.

**Comment by jwk6** [comment]
Ability to resize or collapse both text and code sections would be nice.  If collapse, then maybe allow for the first line or two to be visible.

Also - SSMS Add-ins like SSMS Tools Pack and SSMS Boost both support adding regions to T-SQL code using the following syntax:
--#region Region Name
--#endregion

These regions can be collapse and expanded with a hotkey.
