### ISSUE TITLE
Notebooks: Only see SQL kernel in dropdown

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4643]
SQL is the only kernel that shows up using the latest bits from master:

<img width="167" alt="image" src="https://user-images.githubusercontent.com/40371649/54731955-637a4300-4b4e-11e9-9873-b85980c58c04.png">

**Comment by chlafreniere** [comment]
I can't say with 100% certainty that it's the VS Code merge... But it's fishy...

**Comment by chlafreniere** [comment]
The problem here does not repro 100%, and I can no longer repro it unfortunately...

The problem was that the NotebookService wasn't getting created before the notebook provider registration was occurring:

(from notebookserviceimpl.ts):
this._register(notebookRegistry.onNewRegistration(this.updateRegisteredProviders, this));


(onNewRegistration was firing before this listener was hooked up).

Let's see if we can repro this again. If we can, then we should probably check the registry one more time when getting a list of notebook providers instead of relying solely on this event firing in the right order.

**Comment by YurongHe** [comment]
@chlafreniere, after Anthony rollback, i don't see this issue anymore
