### ISSUE TITLE
Implement Azure Data Explorer support

### ISSUE THREAD

**Issue by amithegde** [microsoft/azuredatastudio#4647]
Tried this tool briefly, and liked it a lot. Please implement support for Azure Data Explorer/kusto. People are going to love it!
- Because ADX doesn't have good public desktop app
- ADX web app is pretty primitive
- adding support here avoids double effort!

**Comment by SQLvariant** [comment]
I would definitely like to see this as well.  Would it make sense to add the connections for Azure Storage to Registered Servers?  I think it would.

**Comment by codykonior** [comment]
I am also a heavy Kusto user and being able to use Kusto in ADS notebooks would be awesome.

**Comment by MsSQLGirl** [comment]
@amithegde  FYI - Kqlmagic is now in preview. You can check out on ADS Insiders. To see sample file and instructions as well as to provide feedback, please go to: #9713 .  

Thank you!

**Comment by abist** [comment]
This will be released in the September release via an extension.
