### ISSUE TITLE
Profiler Extension XML <> symbols not displayed correctly

### ISSUE THREAD

**Issue by VeritableHero** [Microsoft/azuredatastudio#4648]
![Capture](https://user-images.githubusercontent.com/42187813/54754402-d371e300-4bb9-11e9-8406-20b52804e4e1.JPG)
Issue Type: <b>Bug</b>

1. Start _New Session_ in Profiler extension
2. Have it capture a process that uses XML.  We have many stored procedures that receive XML for handling.
3. The XML displayed uses **&lt;** instead of **<** and **&gt;** instead of **>**.  

The values are still visible but it would be more helpful it the XML was properly formatted. 

Sample code:

```
--Create procedure
Create Procedure dbo.ExampleWithXML(@XML xml)
as
Begin
	Select @XML as FormattedXML
End

--Run procedure
Exec dbo.ExampleWithXML @XML = '<Root>
	<NodeOne>Sample data</NodeOne>
	<NodeTwo>Thank you, Azure Data Studio team.</NodeTwo>
	<NodeThree>I really enjoy the program.</NodeThree>
	<NodeFour>I hope this is an easy fix.</NodeFour>
	<NodeFive>
		<SubNode>123</SubNode>
	</NodeFive>
	<NodeSix>456</NodeSix>
</Root>'

--What I would expect is what is displayed above in "Run Procedure" section.
--What is actually displayed in the Text and Details section of Profiler extension is this:
Exec dbo.ExampleWithXML @XML = '&lt;Root&gt;
	&lt;NodeOne&gt;Sample data&lt;/NodeOne&gt;
	&lt;NodeTwo&gt;Thank you, Azure Data Studio team.&lt;/NodeTwo&gt;
	&lt;NodeThree&gt;I really enjoy the program.&lt;/NodeThree&gt;
	&lt;NodeFour&gt;I hope this is an easy fix.&lt;/NodeFour&gt;
	&lt;NodeFive&gt;
		&lt;SubNode&gt;123&lt;/SubNode&gt;
	&lt;/NodeFive&gt;
	&lt;NodeSix&gt;456&lt;/NodeSix&gt;
&lt;/Root&gt;'
```

Azure Data Studio version: azuredatastudio 1.5.1-insider (6d7d485a3840daf2da335b0cf527f98373ce29e6, 2019-03-19T07:23:34.608Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.88GB (2.15GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alanrenmsft** [comment]
@VeritableHero Thank you for reporting the issue and provide convenient repro steps, we will fix the issue and the fix will be included in the upcoming release.

**Comment by alanrenmsft** [comment]
it will look like this
![image](https://user-images.githubusercontent.com/13777222/54856006-bcb0b680-4cb5-11e9-9655-b89fbe9d036f.png)

**Comment by VeritableHero** [comment]
Thank you.
