### ISSUE TITLE
Results lost when selecting sql file again from Explorer pane

### ISSUE THREAD

**Issue by dkordik** [microsoft/azuredatastudio#4656]
Issue Type: <b>Bug</b>

1. Open a folder full of .sql files (File > Open)
2. Select a file in Explorer view (File1.sql), Run, Connect, get Results displayed in lower pane.
3. Select another file in Explorer view (File2.sql)
4. Select first file (File1.sql) from Explorer view (from file tree, NOT from Open Editors)

Expected: Existing "File1.sql" tab is brought into focus with existing Results (like if chosen from Open Editors)
Actual: "File1.sql" tab is selected, but Results are gone

Azure Data Studio version: Azure Data Studio 1.5.1-insider (6d7d485a3840daf2da335b0cf527f98373ce29e6, 2019-03-19T07:14:10.316Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.14GB free)|
|Process Argv|-psn_0_9918837|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
This appears to  be fixed in the current build.  Please let us know if you're still impacted by this bug.  I saw a related bug where the database drop-down selector losses context in this scenario, but the connection and results are persisted.  I'll open a different bug for the drop-down selector issue.  Thanks!
