### ISSUE TITLE
Submit a bug dialog shows VS Code instead of Azure Data Studio

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4659]
Issue Type: <b>Feature Request</b>

The dropdown for the issue reporter is showing Visual Studio Code

![image](https://user-images.githubusercontent.com/8250560/54789821-18fdd280-4bf1-11e9-99ff-fd3dafdbc178.png)

Azure Data Studio version: azuredatastudio 1.6.0-insider (ee5a76bb0c80d7f4d796c64d290bbc4d0e73d3ca, 2019-03-21T21:03:57.240Z)
OS version: Windows_NT x64 10.0.17763

**Comment by MattIrv** [comment]
Fixed in master by #4658
