### ISSUE TITLE
New Notebook Option Disappeared from OE Context Menu

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4662]
Right click on a server in OE:

<img width="172" alt="image" src="https://user-images.githubusercontent.com/40371649/54791586-c673e480-4bf7-11e9-86cc-4e06c68d0a41.png">

Notice that New Notebook isn't present. Here's what we see from the March release:

<img width="187" alt="image" src="https://user-images.githubusercontent.com/40371649/54791609-e0adc280-4bf7-11e9-80d2-cd80b1640e06.png">

**Comment by rajmusuku** [comment]
I don't see this issue exists any more. Tested in several ways, however, I see 'New Notebook' option by right clicking a server on OE. @chlafreniere I am surprised why do we have 'Refresh All" option. Is this a Mac thing Or am I missing anything here?

**Comment by YurongHe** [comment]
I don't see the issue either.

**Comment by kevcunnane** [comment]
I also cannot repro. Let's close
