### ISSUE TITLE
Unable to specify AAD login under Account tab with AAD-Universal with MFA Support Authentication type

### ISSUE THREAD

**Issue by ikflc** [Microsoft/azuredatastudio#4666]
- Azure Data Studio Version:
I am running Azure Data Studio 1.4.5. 
I am trying to connect to an Azure SQL database from on-premise tools server (window 2016).
It works with SQL authentication but not able to connect via "Azure Active Directory - Universal with MFA support".

Steps to Reproduce:

1.  Open the Azure Data Studio (no difference whether I kick it off with "run as admin" or not)
2. New connection->connection Details
3. Unable to enter the AAD user login at all under the Account field of ADS.

Connection Type -> Microsoft SQL Server
Server -> azeBLAHBLAH.database.windows.net
AuthenticationType -> Azure Active Directory - Universal with MFA support
Account -> Add an account ...
                     ^^^^ this drop down menu does not allow me to enter the account!!!

Version 1.4.5
Commit 887f4e8985023602e599cf86bdb44df48bb28569
Date 2019-02-12T06:20:08.633Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

Please help!
Irene

**Comment by ozhug** [comment]
me too version 1.5.2 (window does not change after selecting Add an account...)

**Comment by navicore** [comment]
same

**Comment by navicore** [comment]
this is fixed in master for me.  I downloaded the "Insider build" from the repo readme link.

**Comment by ikflc** [comment]
Can you please send me link to the “Insider Build”?

**Comment by navicore** [comment]
> Can you please send me link to the “Insider Build”? From: Ed Sweeney <notifications@github.com> 
The links to each insider build by platform are in the README here:
https://github.com/Microsoft/azuredatastudio

**Comment by ikflc** [comment]
Thanks.

**Comment by kburtram** [comment]
This appears to be fixed in `1.6.0` April release.  Please let me know if the issue persists.

**Comment by ozhug** [comment]
Thanks Karl this works for me now :-)
