### ISSUE TITLE
Opening the Python3 Notebook from the File > Open option without an active connection is not showing the Install package option

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4667]
Issue Type: <b>Bug</b>

This seems to be a bug. We should always have "Install package" option for Python3.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/54803256-0228a180-4c2c-11e9-88df-8b5f6572ef4a.png">

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
import|Mic|0.7.0
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
This has been fixed in master.
