### ISSUE TITLE
"Failed to show notebook document" when creating new notebooks

### ISSUE THREAD

**Issue by vickyharp** [Microsoft/azuredatastudio#4678]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Bug</b>

Receiving the error "Failed to show notebook document untitled:Notebook-3, should show in editor #untitled:Notebook-3" when starting a new notebook. The notebook editor name increments from 0 with each new notebook created. The notebook IS shown and works. See gif.
![Failed to show notebook document](https://user-images.githubusercontent.com/8250560/54869282-81fd5b80-4d53-11e9-8081-e42f0cca724b.gif)

Azure Data Studio version: azuredatastudio 1.6.0-insider (ee5a76bb0c80d7f4d796c64d290bbc4d0e73d3ca, 2019-03-21T21:03:57.240Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
azuredatastudio-postgresql|Mic|0.1.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
This was fixed last week, but the insiders build is 4 days old now. Investigating...

**Comment by chlafreniere** [comment]
Fixed when we push the next insiders build.
