### ISSUE TITLE
Settings search fails to find Dashboard settings

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#4683]
Issue Type: <b>Bug</b>

Searching for Dashboard in the settings viewer used to show the dashboard setting results in the current release (1.5.2) :

![image](https://user-images.githubusercontent.com/28519865/54934240-67ee8500-4edb-11e9-938f-4d40353e32ec.png)

(Although note that it says **No Settings Found** at the top even though it populates with found settings) 

But now nothing shows up in the Insiders build :

![image](https://user-images.githubusercontent.com/28519865/54934346-9704f680-4edb-11e9-9dc8-ff7320f3132b.png)

Even odder - searching for **Widget** returns values, 

Azure Data Studio version: azuredatastudio 1.6.0-insider (ee5a76bb0c80d7f4d796c64d290bbc4d0e73d3ca, 2019-03-21T21:03:57.240Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (48.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
sql-vnext|Mic|0.10.2

</details>

**Comment by anthonydresser** [comment]
I did some investigation here, we need to make changes to update the meta data around the new search tool. Which I don't think should be targeted at April since the old settings ui still works fine.

**Comment by kevcunnane** [comment]
I don't think this repros anymore - discovered while adding settings into the UI.

**Comment by Charles-Gagnon** [comment]
@kevcunnane - Can you post a screenshot of what you're seeing? I'm still not getting any of the dashboard settings to show up with the latest from master :

![image](https://user-images.githubusercontent.com/28519865/58034089-9d2de280-7ada-11e9-902f-b276db5a644d.png)

Although I can get settings to show up if I search for certain terms. For example searching for Widget brings up some of the Dashboard settings related to Widgets

![image](https://user-images.githubusercontent.com/28519865/58034206-de25f700-7ada-11e9-8512-4c6733a6a8b1.png)

**Comment by kevcunnane** [comment]
OK - I was seeing the "specific search shows items" working and thought it was fixed overall.

In any case, my PR #5524 should fix since once the settings are in the editor you can search for them since the strings like Dashboard are now indexable. I reckon that'll be the full solution, will check.

**Comment by yualan** [comment]
Can we confirm whether this was fixed with this PR?

**Comment by kevcunnane** [comment]
Just tested in master - looks good.
![image](https://user-images.githubusercontent.com/10819925/58587284-d6b8c900-8211-11e9-9774-57dd94c4d8a9.png)
