### ISSUE TITLE
Show Details no longer working

### ISSUE THREAD

**Issue by databull** [microsoft/azuredatastudio#4684]
Issue Type: <b>Bug</b>

right click show details on custom widgets no longer returns any details, grid is blank on all off them.
it worked couple of days ago on previous version.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (8 x 2394)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|28.00GB (21.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0
PowerShell|ms-|1.11.0

</details>

**Comment by databull** [comment]
Not really, its bben working a week ago, now they are blank no matter how i
try to access it.

**Comment by abist** [comment]
Thanks for opening the issue @databull. Could you please share what the application console says when you toggle developer tools (Ctrl + Shift + I)? Thanks!

**Comment by databull** [comment]
Hi, i have reinstalled and its now partially working items are populated
but individual items do not show item details when clicked - console prints
"[Violation] Forced reflow while executing JavaScript took 108ms"
but content is always showing first row.

**Comment by databull** [comment]
issue is back again :( 
![image](https://user-images.githubusercontent.com/22824483/54957455-ba1abf00-4f4a-11e9-88eb-e0d1c77e227e.png)

**Comment by abist** [comment]
Thanks for reporting the details! We'll look into this issue. Look out for the insider builds for possible fixes.

**Comment by kburtram** [comment]
@alanrenmsft did you fix this in May release?

**Comment by databull** [comment]
> @alanrenmsft did you fix this in May release?

just tried it it works again

**Comment by alanrenmsft** [comment]
fixed in May release. closing the issue
