### ISSUE TITLE
Intellisense not respecting user settings.

### ISSUE THREAD

**Issue by coder32768** [Microsoft/azuredatastudio#4688]
In my settings.json, I have the below settings. Even with every possible setting I could find set to "false" or "off", intellisense still pops up when I type certian characters, eg a period after a schema name. I DO NOT WANT THIS. If I want help, I'll ask! Otherwise the text popping up all the time is highly distracting and counterproductive. 

    "editor.hover.delay": 99999,
    "editor.matchBrackets": false,
    "editor.parameterHints": false,
    "editor.quickSuggestions": {
        "other": false,
        "comments": false,
        "strings": false
    },
    "editor.quickSuggestionsDelay": 99999,
    "editor.autoClosingBrackets": "never",
    "editor.cursorBlinking": "smooth",
    "editor.cursorStyle": "line",
    "editor.hover.enabled": false,
    "editor.links": false,
    "editor.codeLens": false,
    "editor.parameterHints.enabled": false,
    "editor.autoClosingQuotes": "never",
    "editor.autoSurround": "never",
    "editor.tabCompletion": "off"

**Comment by anthonydresser** [comment]
Have you tried `editor.suggestOnTriggerCharacters`; we use vscode intellisense so you can find documentation on how to control intellisense at https://code.visualstudio.com/docs/editor/intellisense#_customizing-intellisense

**Comment by coder32768** [comment]
Hi Anthony --

This worked. I'm satisfied the bug is resolved. However, this wasn't easy
to find. Maybe an "Intellisense" section under "Text Editor", in the
settings editor?
