### ISSUE TITLE
Notebook in hung state after ADS is restarted with latest bits

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4689]
Issue Type: <b>Bug</b>

If I have a working Notebook, saved and then if I restart Azure Data Studio then when the Notebook opens it fails to Load the Kernels and the contexts. This is going to be annoying for users when they work across multiple notebooks.

![image](https://user-images.githubusercontent.com/22312581/54950986-c9284f80-4eff-11e9-9d8f-a1ab4e71444a.png)

Azure Data Studio version: azuredatastudio 1.5.1-insider (6d7d485a3840daf2da335b0cf527f98373ce29e6, 2019-03-19T07:23:34.608Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.86GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
gc-excelviewer|Gra|2.1.26
newdatabase|kev|0.0.3
import|Mic|0.7.0
postgresql|Mic|0.1.0
sql-vnext|Mic|0.11.0

</details>

**Comment by chlafreniere** [comment]
These bits are extremely old (see 'Untitled-0'; this was changed for the March release); this no longer reproes, because we do not rehydrate untitled notebooks that were never saved.
