### ISSUE TITLE
Azure Data Studio completely blank

### ISSUE THREAD

**Issue by cstrout** [Microsoft/azuredatastudio#4694]
Issue Type: <b>Performance Issue</b>

I edited my widgets on the dashboard and saved the JSON. When I restarted Azure Data Studio the page was blank. I was unable to edit anything, and no buttons were working. I did find a work around by right clicking the icon and clicking 'new window'.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|15.88GB (9.81GB free)|
|Process Argv|-n|
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   118	 12268	azuredatastudio main
    0	   217	 11964	   window (Azure Data Studio)
    0	   119	 11780	     extensionHost
    0	    30	  2036	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\SqlToolsResourceProviderService.exe" --log-file C:\Users\cstrout\AppData\Roaming\azuredatastudio\mssql\resourceprovider_11780.log --tracing-level Critical
    0	    11	   216	         console-window-host (Windows internal process)
    0	    28	  2064	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\cstrout\AppData\Roaming\azuredatastudio\mssql\credentialstore_11780.log --tracing-level Critical
    0	    11	  1780	         console-window-host (Windows internal process)
    0	    44	  9288	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\cstrout\AppData\Roaming\azuredatastudio\mssql\sqltools_11780.log --tracing-level Critical
    0	    11	  7484	         console-window-host (Windows internal process)
    1	    75	 13420	   window (Issue Reporter)
    0	    74	 14532	   shared-process
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by abist** [comment]
Hi @cstrout, thanks for reporting the issue. Could you toggle the developer tools (Ctrl + Shift + I) and check the console and paste any errors here, or perhaps take a screenshot?

**Comment by cstrout** [comment]
![image](https://user-images.githubusercontent.com/48931797/55007625-f6770b00-4f9c-11e9-9b59-9aa280337a81.png)
![image](https://user-images.githubusercontent.com/48931797/55007641-0131a000-4f9d-11e9-9ab7-b2b3bd0fadfd.png)
The screenshot below seems to be the only error
![image](https://user-images.githubusercontent.com/48931797/55007710-232b2280-4f9d-11e9-96c0-d53eb546623d.png)

**Comment by cstrout** [comment]
I've located some more errors on my end, I'm not sure why it didn't show up the first time. At any rate, see below:

![image](https://user-images.githubusercontent.com/48931797/55016238-93d93b80-4fab-11e9-80e6-7d0bcd7eaca6.png)

**Comment by daghb** [comment]
I also got a blank Data Explorer, but with another error/console output

![image](https://user-images.githubusercontent.com/313628/55077985-59e66300-5099-11e9-811a-58f3fb2964af.png)

**Comment by abist** [comment]
@cstrout @daghb Thanks for reporting the issue and the help. This issue has now been fixed and should be fixed in the coming insider's build.
