### ISSUE TITLE
Text size in messages output is too small: make it configurable

### ISSUE THREAD

**Issue by richardcox13** [microsoft/azuredatastudio#4701]
**Is your feature request related to a problem? Please describe.**

My eyesight isn't great and I can't make the text in the messages output bigger. As it stands it is tiny.

**Describe the solution or feature you'd like**
An ability to customise the text: typeface and size.

**Describe alternatives you've considered**
Switching back to SSMS (despite no dark theme). Coping into a text editor to read.

**Additional context**
The red color used for errors makes this worse. The lack of contrast makes it even harder to read

**Comment by anthonydresser** [comment]
you can use the `Results Grid: Font Size` to adjust the font size of the font in the entire output area (grid and messages). Does this solve your issue?

**Comment by anthonydresser** [comment]
Regrading the color of the errors @yualan @angdesign we might look at making these theme aware colors so they can be configured

**Comment by richardcox13** [comment]
@anthonydresser  Results Grid: Font Size does work (but hardly discoverable: searches for "error", "output", "message" don't find it). 

A highly saturated red on a dark background does need improvement (I find it not great on a light background either, again lack of contrast makes reading very hard – I have a severe astigmatism: contrast is everything).

**Comment by anthonydresser** [comment]
I think we can add messages to the description in the setting which should make it more discoverable.

**Comment by kburtram** [comment]
The error message color needs to be theme aware.  I'm not sure Red on Black has enough contrast ratio to meet our Accessibility requirements.  

Adding messages to the description should address the original issue discussed, though we may want different settings for messages then resultsgrid, similar to SSMS.

**Comment by kburtram** [comment]
The Results Grid font family setting now shows up when searching for "Messages" so I'll close this out now.
