### ISSUE TITLE
Can't copy result from notebook

### ISSUE THREAD

**Issue by royhq** [Microsoft/azuredatastudio#4702]
Issue Type: Bug

- Azure Data Studio Version: 1.5.2
- OS: Windows 10 Home x64

Steps to Reproduce:

1. Make a select statement in notebook
2. Select a cell and do `Ctrl+c`
3. Paste in any text editor. It paste the executed code instead of the cell value.

**Comment by YurongHe** [comment]
@royhq we enable "copy" output result using ctrl+a for active cell on windows/linux in April release. Could you try it out and see if you get what you need? Feel reopen it if you need something else.
