### ISSUE TITLE
Data explorere empty

### ISSUE THREAD

**Issue by enecciari** [Microsoft/azuredatastudio#4703]
Issue Type: <b>Bug</b>

No view is registered with id: azureResourceExplorer

Azure Data Studio version: Azure Data Studio 1.6.0-insider (1bac929ab38e64560a6f663baa086a9b540c083c, 2019-03-25T23:14:03.156Z)
OS version: Darwin x64 18.5.0

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
sql-search|Red|0.3.2

</details>

**Comment by anthonydresser** [comment]
dupe  #4700
