### ISSUE TITLE
Keyboard Shortcut to execute Stored Procedure does not work if query window has results

### ISSUE THREAD

**Issue by dmorrissey-breuer** [microsoft/azuredatastudio#4704]
Issue Type: <b>Bug</b>

1) Set query shortcut 3 to `sp_columns`.

2) Bind Shortcut3 to "CTRL + Shift + 3"

3) Run a query (I ran `select top 1 * from Person.Person`  in the adventure works database)

4) Highlight the table in the text editor section

5) Run "CTRL + Shift + 3" one or more times

Actual results:
Each time you run the keyboard shortcut, the results will be placed below the existing query results. This renders the keyboard shortcut essentially unusable as you can't view the results. 

Expected results:
I expect the results window to clear and display the results of the keyboard shortcut's stored procedure only.

This seems like a regression, it only started recently.

Here is a gif demonstrating the error: 
![keyboard_shortcut_error_1](https://user-images.githubusercontent.com/23343931/55017361-f1c74c80-4fc6-11e9-8271-3c1866aa5fd9.gif)

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6920HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.02GB free)|
|Process Argv|-psn_0_12581887|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0

</details>

**Comment by Stevoni** [comment]
I'm seeing a similar issues with the keybindings. Running using Run/F5 works but the keybindings don't appear to clear the results pane.

For my steps, have a keybinding for sp_helptext (1, CTRL+F1) and "SELECT TOP 100 * FROM " (2, CTRL+0):
1. Run keybinding 1 (sp_helptext) on a procedure
2. View the contents of a table using keybinding 2 within that procedure (in the same file window).
The sp_helptext output is shown again
3. Within the same file window, executing a specific select statement will return the correct results.
4. Executing keybinding 2 will output the sp_helptext again.

When running multi-result select statements like sp_help (ALT+F1) then running sp_helptext (CTRL+F1) will replace the first result set but the others will be retained until running something through F5 again.

**Comment by kevcunnane** [comment]
Thanks @Stevoni for fixing this. The next Insiders build should have this in it, let us know how it goes!
