### ISSUE TITLE
High CPU usage and crash report: Ubuntu 19.04 / gnome 3.32 / kernel 5.0.0.7

### ISSUE THREAD

**Issue by wandoschneider** [Microsoft/azuredatastudio#4710]
- Azure Data Studio Version: 
Version: 1.5.2
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:07:48.490Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Linux x64 5.0.0-7-generic

Steps to Reproduce:

1. Open Azure Data Studio
2. Look into Gnome system monitor
3. 2 Threads are always at 100%
4. Reproducible even with all the extensions disabled.
[_usr_share_azuredatastudio_resources_app_extensions_mssql_sqltoolsservice_Linux_1.5.0-alpha.71_MicrosoftSqlToolsServiceLayer.1000.log](https://github.com/Microsoft/azuredatastudio/files/3010834/_usr_share_azuredatastudio_resources_app_extensions_mssql_sqltoolsservice_Linux_1.5.0-alpha.71_MicrosoftSqlToolsServiceLayer.1000.log)

Also, there's a crash report (Not sure if it's related).

**Comment by kburtram** [comment]
@wandoschneider do you have any additional info on the state of Azure Data Studio after step 1 in the repo.  For example, are there any SQL files open, any active connections, do the threads run at 100% indefinitely or slow down eventually, etc.?  Thanks!

**Comment by wandoschneider** [comment]
Hi! No files open, no active connections. Just launch the application and the CPU fan starts to scream. They run indefinitely.

Screenshot:
![Screenshot from 2019-04-08 08-34-15](https://user-images.githubusercontent.com/8496997/55721383-9ab77380-59d9-11e9-83a9-c75b6b51805a.png)

**Comment by wandoschneider** [comment]
Hi! Not sure what solve the problem, but after updating to the latest release on linux (1.6) the problem is gone.
