### ISSUE TITLE
Saving a query disconnects its session

### ISSUE THREAD

**Issue by BrentOzar** [Microsoft/azuredatastudio#4717]
Issue Type: <b>Bug</b>

From the insiders build downloaded just now:

1. Create a new query (target server doesn't seem to matter, happens on both SQL Server and Postgres)
2. Execute it
3. Save it (not the results - save the query, like command-S)

Results: the query disconnects and the results window disappears.

Demo: 
https://imgur.com/a/FkrKbW9

Azure Data Studio version: Azure Data Studio 1.6.0-insider (1bac929ab38e64560a6f663baa086a9b540c083c, 2019-03-25T23:14:03.156Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (6.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0
pastetheplan|dre|0.2.0
azuredatastudio-postgresql|Mic|0.1.0
sql-vnext|Mic|0.11.0

</details>

**Comment by anthonydresser** [comment]
related #1876

**Comment by kburtram** [comment]
This is the same underlying issue as https://github.com/Microsoft/azuredatastudio/issues/1876.  So closing as a duplicate.
