### ISSUE TITLE
Database tree does not open

### ISSUE THREAD

**Issue by robert-niestroj** [Microsoft/azuredatastudio#4718]
Issue Type: <b>Bug</b>

In servers tab often when clicking on the right arrow to open a database the spinner is spinning but the tree with databases does not open. It worked correctly on the previous version. Tested on multiple machines (i install ADS on remote machines of clients). Only thing helps is restart ADS. Even if i right click and Disconnect the spinner is still spinning. After that refresh does not help. Connect is not available, but i can click manage and the server dashboard appears and i get the green icon that im connected. But still no tree with the databases. The arrow remains showing right down (south-east) but no list. Happens on localhost databases as well as remote databases. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.69GB (5.69GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by anthonydresser** [comment]
If you can repro this; are you seeing any errors in the console? (Help -> Toggle Developer Tools -> Console)

**Comment by robert-niestroj** [comment]
Steps to reproduce:
1. Start system with Windows 10
2. Open ADS
3. Click the right arrow to open the Database tree
4. it fails to open the database tree
5. Close & Open ADS
6. Click the right arrow -> it works

I see no errors in the DEV tools. Are the any log files i could look in?

**Comment by robert-niestroj** [comment]
Additional info. 
The description above is OK. What i noticed now is:
the problem happens when i immediately after start of ADS try to open the tree. The problem does not appear when i wait until in the status bar appear two texts Service staring and then Service started. When i wait after that it open the tree correctly.

![obraz](https://user-images.githubusercontent.com/9776384/56034508-bac39b80-5d27-11e9-8cc2-6e91699f913a.png)

**Comment by kburtram** [comment]
ADS has child process services that provide database functionality.  We should the UI prior to loading the services since some users tasks can be done without needing them, but if anything is done that needs these services then the task will block until they are done loading.  

We're continually looking at how to make this quicker, but there are a lot of things trying to run on startup.  I'll close this issue since this is a known behavior that we are tracking elsewhere as part of our performance improvement targets.
