### ISSUE TITLE
It doesn't show all tables correctly

### ISSUE THREAD

**Issue by HofmannCh** [Microsoft/azuredatastudio#4720]
Issue Type: <b>Bug</b>

https://prnt.sc/n3mow9

After i resize the result window not all tables are shown. In this example i run 3 table selects, but only one is shown correctly, one is buggy and the last is invisible

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (6.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@anthonydresser this looks like more side-effects of the result streaming changes.  What do you think?

**Comment by kburtram** [comment]
This should be resolved by https://github.com/Microsoft/azuredatastudio/commit/c1cb9000a9d54b10a52118ffe7dc1ded7fc8a804 and will be in the May release next week.  @anthonydresser fyi, this is the issue I was mentioning regarding incorrect `top` value in the `HeightMap`.
