### ISSUE TITLE
SQL Notebooks - no ability to change database context in drop down and not ordered

### ISSUE THREAD

**Issue by martincroft** [microsoft/azuredatastudio#4722]
Using SQL notebooks it attaches to a server/database. There is no way to change to a different database on this server from the drop box/change connection.

Workaround being

- select drop down box"Attach to "
- Select Add new connections
- Create new connection ( this then adds to the drop down but noticed these are not ordered (shows the last connections, I have multiple from one server (different databases but come in different places in the list
![image](https://user-images.githubusercontent.com/30621653/55083556-a3d04880-509b-11e9-9b71-8f91ee1dbf5f.png)

Or using USE statement in each code segmentation would be useful to change database context easier like SSMS 

Neither of these are ideal to quickly change database context.

**Comment by corivera** [comment]
Will be fixed by https://github.com/microsoft/azuredatastudio/issues/4121
