### ISSUE TITLE
Data Explorer no longer populating

### ISSUE THREAD

**Issue by kplantus** [Microsoft/azuredatastudio#4723]
Issue Type: <b>Bug</b>

Just updated to the latest insider release. 1.6.0-insider
![image](https://user-images.githubusercontent.com/39968602/55090876-3d8cfb00-5086-11e9-8f6f-317e7ebea77e.png)

I can no longer see any servers or any of my saved connections in Data Explorer:
![image](https://user-images.githubusercontent.com/39968602/55090928-50073480-5086-11e9-81c4-1fc444905b76.png)

When I relaunch Data Studio I get:
No view is registered with id: azureResourceExplorer
![image](https://user-images.githubusercontent.com/39968602/55090945-5695ac00-5086-11e9-94bd-7eb273c86cc8.png)

Azure Data Studio version: azuredatastudio 1.6.0-insider (1bac929ab38e64560a6f663baa086a9b540c083c, 2019-03-25T23:25:02.789Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.78GB (2.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by abist** [comment]
@kplantus Thanks for reporting the issue. We are aware of the issue and it's fixed in the coming latest insider release.
