### ISSUE TITLE
No Data Explorer on latest Insider Build is not visible

### ISSUE THREAD

**Issue by wsmelton** [Microsoft/azuredatastudio#4724]
Issue Type: <b>Bug</b>

Installed latest insider build download. I receive this error when opening:
![image](https://user-images.githubusercontent.com/11204251/55090783-b3d92f80-507d-11e9-90f4-da76875958a1.png)

There is no ability to view a SQL Server instance in server explorer.
![image](https://user-images.githubusercontent.com/11204251/55090804-be93c480-507d-11e9-8854-cf4544d161f2.png)

Process explorer does not show the services is running:
![image](https://user-images.githubusercontent.com/11204251/55090887-df5c1a00-507d-11e9-847b-35ca9daccca6.png)
![image](https://user-images.githubusercontent.com/11204251/55091017-16cac680-507e-11e9-8d3d-0c9ff2497ffb.png)

```
Azure Data Studio version: azuredatastudio 1.6.0-insider (1bac929ab38e64560a6f663baa086a9b540c083c, 2019-03-25T23:25:02.789Z)
OS version: Windows_NT x64 10.0.17134
```
<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (5.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by wsmelton** [comment]
Additional details found... The log file showing in the message is not actually generated.

![image](https://user-images.githubusercontent.com/11204251/55091451-d7e94080-507e-11e9-9b2a-61f279ed973f.png)

**Comment by abist** [comment]
@wsmelton Thanks for reporting the issue. We are aware of the issue and it's fixed in the coming latest insider release.

**Comment by wsmelton** [comment]
So no "hey yeah don't let insiders update because it will become unusable" notice or anything?!!??

I mean we can't roll back to a previous version of insiders....

**Comment by abist** [comment]
@wsmelton Sorry about the issue, the next insider's build shouldn't have this issue.

**Comment by wsmelton** [comment]
Is that going to be pushed out within the next hour?

**Comment by abist** [comment]
@wsmelton Yes, it will be out soon today.
