### ISSUE TITLE
Unable to update ADS due to file in use error

### ISSUE THREAD

**Issue by paschott** [microsoft/azuredatastudio#4729]
I can't reproduce consistently, but I have had issues several times where trying to update ADS results in a "file in use" error. Tracing this back using sysinternals tools shows that when this happens, it's usually because something in the SYSTEM process has grabbed the executable. The only way I have to work around that is to restart the machine and manually update from the downloaded version before trying to launch ADS.

I've seen similar behavior with the Teams app.

This happened trying to update from the February to March release, but has happened in the past as well.

**Comment by anthonydresser** [comment]
Do you use vscode? If so, have you experienced this with vscode?

**Comment by paschott** [comment]
> 
> 
> Do you use vscode? If so, have you experienced this with vscode?

I actually haven't seen this with VS Code, but don't use that quite as often as ADS or Teams so far.

**Comment by paschott** [comment]
Happened again w/ the current release.

---------------------------
Error
---------------------------
%AppData%\Local\Programs\Azure Data Studio\azuredatastudio.exe



An error occurred while trying to replace the existing file:

DeleteFile failed; code 32.

The process cannot access the file because it is being used by another process.



Click Retry to try again, Ignore to skip this file (not recommended), or Abort to cancel installation.
---------------------------
Abort   Retry   Ignore   
---------------------------

**Comment by anthonydresser** [comment]
Is it possible that you have a anti-virus or something that is locking it? I'm racking my brain trying to think why the exe would be locked.

**Comment by paschott** [comment]
I get similar issues when Teams tries to update, but was able to update VS Code recently with no issues using the in-app updater.
________________________________

**Comment by paschott** [comment]
![procexp64_2019-04-18_14-48-44](https://user-images.githubusercontent.com/341111/56387173-3d959c00-61e9-11e9-9f84-17667ab51b1d.png)
So- Process Explorer shows that AzureDataStudio has been grabbed by the System process.

**Comment by kburtram** [comment]
I would guess this could be related to a virus scanner device driver.  Are you using an A\V software besides Windows Defender on this machine?

**Comment by paschott** [comment]
Just Windows Defender. Our older builds used to use Malwarebytes, but these machines don't.
________________________________

**Comment by kburtram** [comment]
Unfortunately, I'm not sure what we can do our side to avoid another process taking a lock on us.  We don't run anything in System directly as far as I know.

**Comment by kburtram** [comment]
Closing out older issues that don't have recent repros.   Please let us know if you're still impacted by this issue.
