### ISSUE TITLE
Feature Request: Nested Widget

### ISSUE THREAD

**Issue by chris904apps** [microsoft/azuredatastudio#473]
- SQL Operations Studio Version: 0.24.1
Would be nice to neat widgets (widget inside of a widget) to provide deeper insight. For example, maybe I am looking at storages at server level and have 4 DBs, I may want to click on db 1 to see how the 40gbs of data it is showing use is distributed across the tables it has. Now I can see that member table is only use 4 gb but transactions is hold 28 gbs.

**Comment by Tarig0** [comment]
This would also be nice to drill in to groupings on a pie chart.
