### ISSUE TITLE
Azure pane taking a long time to show account

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#4732]
Issue Type: <b>Bug</b>

The Azure pane is taking a long time (~30 seconds) to show my account. This is without my having expanded it.

![Startup Time for Azure](https://user-images.githubusercontent.com/8250560/55105915-e3daff80-508a-11e9-8d4f-c2d4b930cc7b.gif)

Azure Data Studio version: azuredatastudio 1.6.0-insider (e1e9c08242b66062cb22397238eede3bc92ef19f, 2019-03-27T17:57:19.823Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (3.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.0.1
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by aaomidi** [comment]
I don't think this is an issue anymore.
