### ISSUE TITLE
Restore database UI breaks when trying to set backup file path

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#4734]
Issue Type: <b>Bug</b>

From the dashboard on SQL 2019 BDC click on restore
Change restore from 'Database' to 'Backup file'
Click on "..." for Backup file path

![image](https://user-images.githubusercontent.com/10529018/55112006-cf9dff00-5098-11e9-849a-46c82450209a.png)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (29.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.11.0

</details>

**Comment by udeeshagautam** [comment]
Fixed with https://github.com/microsoft/sqltoolsservice/pull/816 pulled to ADS on 5/29.
