### ISSUE TITLE
Connection dialog UX - Recent History and Saved Connection pane is too small due to extra space in connection property pane

### ISSUE THREAD

**Issue by erickangMSFT** [microsoft/azuredatastudio#474]
- SQL Operations Studio Version:

Steps to Reproduce:

Possible regression: Connection dialog renders extra space below connection properties controls which makes Recent History pane smaller and harder to use with multiple connections.

![image](https://user-images.githubusercontent.com/11077282/34846265-70865b60-f6cc-11e7-8883-2f2fe989e34a.png)

**Comment by kburtram** [comment]
This issue no longer repros on current builds.  Thanks for reporting!
