### ISSUE TITLE
Database connection drop-down does not observe theme

### ISSUE THREAD

**Issue by amtwo** [Microsoft/azuredatastudio#4741]
Issue Type: <b>Bug</b>

When using a dark theme, the text in the database drop-down selector does not observe the theme coloring properly.

To reproduce:
* Set theme to "Dark Azure Data Studio (default dark)"
* Open a Query window & connect to any SQL Server instance
* Select the drop down for database

What happens:
* The text in the dropdown is nearly illegible black on dark grey. Even when highlighting the row, it is still nearly impossible to read
![image](https://user-images.githubusercontent.com/9381581/55167098-b94e7c80-5146-11e9-8587-cc8421886402.png)

What I expect to happen:
* The text should be white on the dark grey background

Azure Data Studio version: azuredatastudio 1.6.0-insider (e1e9c08242b66062cb22397238eede3bc92ef19f, 2019-03-27T17:57:19.823Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.86GB (7.89GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.10.2

</details>

**Comment by kburtram** [comment]
Note #5124 this also impacts the database selector drop down in Connection Dialog.

**Comment by alanrenmsft** [comment]
I tried on latest insiders build and this issue has been fixed, I took a quick look at the recent commits, but couldn't easily tell which one fixed the issue.
