### ISSUE TITLE
Failed to create Object Explorer session

### ISSUE THREAD

**Issue by jmarti326** [microsoft/azuredatastudio#4742]
Issue Type: <b>Bug</b>

Basically, I successfully open a connection with the database but it always prompts Failed to create Object Explorer session since the last update.

![Session Error Prompt](https://user-images.githubusercontent.com/4348632/55170487-06355180-514d-11e9-8ce5-fc91fd3bac29.jpg)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.94GB (7.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by anthonydresser** [comment]
#4718 could be related

**Comment by anthonydresser** [comment]
What connection type are you using? I can't seem to repro

**Comment by Chester8007** [comment]
Hi, I have the same Issue.
Prompt shows up after connected successfully to 2016 SQL Server, and I check the parent-folder of logFile for SqlToolsResourceProviderService.exe is empty.

![image](https://user-images.githubusercontent.com/39977277/56112273-1a6eb080-5f8d-11e9-956b-abadf968baaf.png)

**Comment by RachelAmbler** [comment]
Same issue here using MacOS Mojave. Oddly the issue seems to only bite on sessions connected using WIndows Authentication\Kerberos. None of my Sql Server authentication connections seem to exhibit the same issue. Also, just since this last update.

**Comment by cheenamalhotra** [comment]
Closing as stale.
