### ISSUE TITLE
Query Editor grid doesn't respond to resize events

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4743]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query with results that need a scrollbar
2. Resize window and\or splitter and\or collapse messages

Expected: Results grid resizes to available space

Actual: Grid stays fixes size

<img width="1241" alt="Screen Shot 2019-03-28 at 9 52 53 AM" src="https://user-images.githubusercontent.com/599935/55176983-7046fa00-513f-11e9-8709-b8a862dbace9.png">

**Comment by kburtram** [comment]
@anthonydresser could you please take a look?  I think this may be a regression from a vscode merge?

**Comment by anthonydresser** [comment]
I don't think this is caused by the merge, I think this is a remnant of the messages collapse work.

**Comment by kburtram** [comment]
I don't see this in the March release.  In any case we need to fix ASAP.  Please reassign the issue to me if you don't have time to investigate today and I can take look.  Thanks!

**Comment by kburtram** [comment]
...or maybe I forgot, did we turn off message collapse only in the release branch?  In any case, have the grid not resize to fill available space is a serious UX problem.  Should we turn-off message collapse in master as well then?
