### ISSUE TITLE
workbench.view.connections command disappeared

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4744]
Azure Data Studio version: Insiders.

Steps to Reproduce:

1. Install SSMSKeymap extension and run F8. This used to open the Server Explorer viewlet
2. Get error `workbench.view.connections` command is missing

@anthonydresser where did this go? it's a feature people are using. What replaces it or did we just delete the feature?

**Comment by kevcunnane** [comment]
Looks like view.dataexplorer replaces it. This is confusing from a back compat perspective, but if needed I can produce a new version of the extension that uses this instead? Will this be constant, and are there other things that might have regressed?
 
![image](https://user-images.githubusercontent.com/10819925/55182305-9d4cda00-514a-11e9-95eb-364be767761b.png)

**Comment by kburtram** [comment]
Yeah, I think "Data Explorer' should be in-place of the current "Servers" viewlet so that all the current dependencies continue to work.  It's probably a reasonable time now to pull out the old Servers and Azure Explorer viewlets and switch over.

**Comment by kevcunnane** [comment]
OK, so then it should continue to support the old command syntax of workbench.view.connections?

**Comment by anthonydresser** [comment]
`workbench.view.connections` isn't consistant with the rest of our naming schemes. It's always `workbench.view.${name of view}` I.E it would be `workbench.view.dataExplorer`

**Comment by kburtram** [comment]
don't we have a backcompat issue here?  is there any reason the viewlet's need to follow that naming scheme?  I don't recall reviewing that decision in a design meeting or doc, IIRC.

**Comment by anthonydresser** [comment]
This is the naming scheme we adopted from vscode, they use that naming scheme for all the views.

**Comment by kburtram** [comment]
I'm not sure consistency with VS Code's viewlet naming convention is more important than maintaining backcompat.  Is there any practical reason that we should follow this convention besides it's what VS Code is doing?  It seems like we should minimize breaking changes for seemingly arbitrary reasons, unless I'm missing something.

**Comment by anthonydresser** [comment]
Consistency? This view is no longer just connections, so it would be misleading naming

**Comment by kburtram** [comment]
Can you determine the impact of the breaking change?  And make a plan how we can notify and help upgrade anyone impacted?  Also, do we need to have a mitigation in place such that extension aren't broken in April?  For example, should we support both and then remove connections once extensions have time to be updated?  

In general, we need to stage breaking changes over multiple releases to give partners time to make and publish required changes.

**Comment by kevcunnane** [comment]
If SSMSKeymap is the only thing dependent on it, I can just update this and push the update to the insiders channel? I only found this because I'll add a new keymapping for F8 to handle the powershell extension's value being in conflict with view ~object~ data explorer keybinding in SSMS.

**Comment by kburtram** [comment]
Yeah, I'm not too concerned with this particular change.  It's more that we need to be deliberate with our breaking change process.  (i.e., assume we had a robust partner ecosystem that depends on the features we're building).  It's better to start following a well-defined process as soon as possible so that it's in-place before we need it.

In terms of feature design, I'm not sure "Data Explorer" is the name we want to go forward with in user facing strings\commands in any case.  We should discuss in the scenario review which will hopefully be scheduled for tomorrow or early next week.

**Comment by kevcunnane** [comment]
Cool. Agree with you on this being another example where we make breaking changes without thinking about the impact. Let's chat in the scenario review and decide what to do.
