### ISSUE TITLE
CREATE OR ALTER VIEW not recognized by editor as valid syntax

### ISSUE THREAD

**Issue by jdanton** [microsoft/azuredatastudio#4746]
Issue Type: <b>Bug</b>

create or alter view syntax shows red underlines

Azure Data Studio version: Azure Data Studio 1.6.0-insider (e1e9c08242b66062cb22397238eede3bc92ef19f, 2019-03-27T17:42:36.552Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_208947|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
alwayson-insights|mat|0.2.1
mssql-instance-insights|mat|0.2.1
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.6.9
whoisactive|Mic|0.1.1

</details>

**Comment by jdanton** [comment]
<img width="789" alt="Screen Shot 2019-03-28 at 11 39 45 AM" src="https://user-images.githubusercontent.com/7385792/55183972-3f21f600-514e-11e9-9545-aeee47ed8169.png">

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this currently so it's likely a recent update to the parser solved this. Reopen it if you're still seeing this issue in the latest release!
