### ISSUE TITLE
New Notebook didn't load

### ISSUE THREAD

**Issue by jrowlandjones** [Microsoft/azuredatastudio#4751]
Issue Type: <b>Bug</b>

From the manage window I clicked on New Notebook. 
![image](https://user-images.githubusercontent.com/10529018/55193429-2d4b4d80-5164-11e9-9a39-4d07e15fd79d.png)

The Notebook didn't load.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (26.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.11.0

</details>

**Comment by YurongHe** [comment]
@jrowlandjones , could you try it with latest insider build or release build. I can't repro it.
