### ISSUE TITLE
bang doesn't work in notebooks on mac

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4752]
- Azure Data Studio Version: 1.5.2 and 1.5.2-insider

Steps to Reproduce:

1. Open a notebook and in a code cell run anything starting with ! (bang)
2. Get an error about 
`"sh" shell not found`

cc: @chlafreniere and @ronychatterjee who have been looking at this

**Comment by chlafreniere** [comment]
This was due to having an old version of the SQL Server 2019 (Preview) extension installed.
