### ISSUE TITLE
Switching tabs causes strange query plan rendering

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#4755]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query with Explain
2. Switch tabs then switch back

Expected: Rendering is the same.

Actual: Arrows disappear from plan and a strange element is rendered.  I think this may be the missing arrows?

![image](https://user-images.githubusercontent.com/599935/55198410-1a8c4500-5173-11e9-8e4e-521d5aec1348.png)

**Comment by aasimkhan30** [comment]
This is likely fixed in the new execution plan feature
