### ISSUE TITLE
Reinstall notebook dependencies doesn't work without first restarting ADS

### ISSUE THREAD

**Issue by stuartpa** [Microsoft/azuredatastudio#4762]
Issue Type: <b>Bug</b>

Get an error dialog:

Installing Notebook Dependencies failed with error: {0}

The output window looks like this

Output Window just shows the following
... Jupyter is running at http://localhost:8888/?token%3Da62d6cf5e63474a583566b23c74d07f73d8be60460e02b07
    > C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe -m jupyter notebook stop 8888
    stdout: Shutting down server on port 8888 ...
    stdout: 
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\config
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\data
... Creating C:\Users\pradm\AppData\Roaming\jupyter\instances\77527b69-246e-4493-b28e-b2c662ad9728\config\custom
... Starting Notebook server
    > C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe -m jupyter notebook --no-browser --notebook-dir "e:\Projects\SQLAris\NoteBook_Deployment_TSG\Rony" --port=8888 --NotebookApp.token=0ff24b9dd3afc2c61da65a8b5fcace50e875f1a007137df0
... Jupyter is running at http://localhost:8888/?token%3D0ff24b9dd3afc2c61da65a8b5fcace50e875f1a007137df0
Python installation is in progress
Downloading python package (0 / 159.34 MB)
Downloading python package (15.94 / 159.34 MB)
Downloading python package (31.88 / 159.34 MB)
Downloading python package (47.81 / 159.34 MB)
Downloading python package (63.74 / 159.34 MB)
Downloading python package (79.67 / 159.34 MB)
Downloading python package (95.62 / 159.34 MB)
Downloading python package (111.55 / 159.34 MB)
Downloading python package (127.48 / 159.34 MB)
Downloading python package (143.41 / 159.34 MB)
Downloading python package (159.34 / 159.34 MB)
Unpacking python package
 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by corivera** [comment]
I've fixed the bug with that error message, so we can get some better info about the error the next time this happens. Looks like there was some error during the unpack here, but without any other information I won't be able to investigate. Feel free to open another bug if this happens again.
