### ISSUE TITLE
Stop Button Stay Active

### ISSUE THREAD

**Issue by blink2linkme** [microsoft/azuredatastudio#4763]
Issue Type: <b>Bug</b>

Stop Button Stays active on the studio.
1) In normal Condition
2) If there is infinite loop or  some process that takes longer time.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.84GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
Hi @blink2linkme, thanks for reporting the bug. Can you please elaborate which Stop button you're talking about? Is this the stop button for Query Execution?

**Comment by blink2linkme** [comment]
Yes @abist I am taking about the query execution button.

**Comment by kburtram** [comment]
This looks like the same underlying bug as described in https://github.com/microsoft/azuredatastudio/issues/4218.  I'll close as duplicate to consolidate issues.  Thanks for reporting!
