### ISSUE TITLE
Restore database and pickup file

### ISSUE THREAD

**Issue by codewithtomi** [microsoft/azuredatastudio#4764]
Issue Type: <b>Bug</b>

When working on database restore screen, select one file to backup, app shows  'db1' to restore on source combo

When I picked up wrong file, did repick another file which contains `db2` , application shows both 'db1' and 'db2' on combobox even newly picked up file did not contain 'db1'

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.81GB (17.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0

</details>

**Comment by udeeshagautam** [comment]
@codewithtomi thanks for reporting this issue. I tried to repro and noticed that two databases show in dropdown only when backup file path has two comma separated files. Please note that previous selected file doesn't go away when new file is added. Can you please check if you have two files in the text box when this issue shows or just one for db2. 

![image](https://user-images.githubusercontent.com/46980425/58348190-c7eaa480-7e14-11e9-8728-8c09589ef3a2.png)
