### ISSUE TITLE
Unable to browse to ~/Downloads on macOS

### ISSUE THREAD

**Issue by tgharold** [microsoft/azuredatastudio#4765]
Issue Type: <b>Bug</b>

1. Open up Azure Data Studio on macOS
2. right-click, Manage a server connection
3. Click Tasks, Restore
4. Attempt to browse to ~/Downloads (or /Users/username/Downloads)
5. The macOS Users directory does not appear and can't be found

Nor can you plug in "~/Downloads" in the file open dialog and have it change straight to the directory that you want.

Azure Data Studio version: Azure Data Studio 1.5.1 (6a500715a7f2a9c5466d66b3cc312308bf59846d, 2019-03-16T01:01:21.653Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|32.00GB (0.02GB free)|
|Process Argv|-psn_0_17506481|
|Screen Reader|no|
|VM|33%|

</details>Extensions: none

**Comment by kburtram** [comment]
@tgharold the Restore File Browser is exploring the filesystem on the SQL Server machine.  If you're connecting to SQL Server in Docker you'll see the contents of the docker container.  Please let me know if I misunderstand the issue.

**Comment by tgharold** [comment]
Yes, we're attaching to a SQLServer instance running in a docker container.  The interaction is just a bit weird in the docker container situation.

Workaround for us will be to mount the desired directories from the macOS host into the docker development container.

**Comment by kburtram** [comment]
Closing older issues.  This appears to be an issue with a particular configuration.  The proposed workaround of mounting directories into the container makes sense.  Thanks!
