### ISSUE TITLE
Unable to open file browser

### ISSUE THREAD

**Issue by Skydyvyr** [microsoft/azuredatastudio#4767]
Issue Type: <b>Bug</b>

I'm running a Mac with the latest O/S. When I attempt to brows to a backup file (stored locally), I get the following error:

An error occured while loading the file browser.

Hand entering the path into the field doesn't work either.

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by Skydyvyr** [comment]
<img width="949" alt="Screen Shot 2019-03-29 at 10 10 27 AM" src="https://user-images.githubusercontent.com/46822626/55250970-b1591000-520c-11e9-9cc8-4f683eeb06fa.png">

**Comment by kburtram** [comment]
@udeeshagautam according to @shueybubbles SSMS is mitigating this issue by setting the initial remote directory using the SMO `Server.BackupDirectory` property.  Which apparently is still enumerable properly with `sys.dm_os_enumerate_filesystem`  on non-Windows platforms.  This may be a reasonable workaround for ADS as well.

**Comment by udeeshagautam** [comment]
@kburtram @shueybubbles, we do currently check Server.BackupDirectory but use it only to expand the tree not populate (because we want to populate the tree from root). Should we use Server.BackupDirectory to populate the tree even when root folders are incorrect or in all cases? suggestions?

**Comment by shueybubbles** [comment]
There are a few places in SSMS that have this same problem; only one part of the SSMS experience handles this failure semi-gracefully by only populating the folder list with the default folder. 
Can ADS handle the failure to populate from the root by re-rooting the tree at the default directory?
![image](https://user-images.githubusercontent.com/2224906/58119628-671f5a00-7bd1-11e9-8942-6174a5cf5149.png)

**Comment by udeeshagautam** [comment]
Ah yes the above is good example.
I think yes, we can change sqltoolsservice to behave that way. Will try the change and send a PR for this.
