### ISSUE TITLE
Multiple SQL Notebooks with same query running against same database and table hang

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#4772]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/41927913/55258569-75c84100-5220-11e9-87aa-a0126a01a272.png)

REPO
1. Create a SQL Notebook & write a query against a table in the DB
SELECT TOP (1000) [InvoiceLineId]
      ,[InvoiceId]
      ,[TrackId]
      ,[UnitPrice]
      ,[Quantity]
  FROM [dbo].[InvoiceLine]

2. Create a second notebook and run the same query
SELECT TOP (1000) [InvoiceLineId]
      ,[InvoiceId]
      ,[TrackId]
      ,[UnitPrice]
      ,[Quantity]
  FROM [dbo].[InvoiceLine]

3. Note that the queries hang

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
@YurongHe I believe that this is related to the work that you're already doing for creating notebook connections
