### ISSUE TITLE
TSQL Notebook returns error for valid query

### ISSUE THREAD

**Issue by jrowlandjones** [Microsoft/azuredatastudio#4779]
Issue Type: <b>Bug</b>

Please see screenshot
![image](https://user-images.githubusercontent.com/10529018/55264573-18d58680-5232-11e9-8c90-5cf52991e057.png)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (23.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.11.0

</details>

**Comment by jrowlandjones** [comment]
![image](https://user-images.githubusercontent.com/10529018/55264680-72d64c00-5232-11e9-812e-e1554f2b4579.png)
Works fine in the query editor

**Comment by kevcunnane** [comment]
I can't repro this on either 1.5.2 or insiders. @chlafreniere any luck for you?

**Comment by jrowlandjones** [comment]
@kevcunnane  @chlafreniere have you run this against master? I found it worked against user database but not master

**Comment by chlafreniere** [comment]
Not seeing this on 1.5.2:

<img width="317" alt="image" src="https://user-images.githubusercontent.com/40371649/55264845-0576eb00-5233-11e9-9150-a67c00de85b2.png">

**Comment by chlafreniere** [comment]
Closing because no repro, @jrowlandjones.
