### ISSUE TITLE
Windows authentication needs to be easier

### ISSUE THREAD

**Issue by twiggy** [microsoft/azuredatastudio#4781]
Currently to use windows auth there is a considerable amount of work for both Mac and Linux clients. This includes joining the domain of the server. If you have to connect to servers in different domains this can be challenging. On windows SSMS you can use windows credential manager. At the end of the day we want the password to be in AD, but don't need all the domain and kerbos complications. This might require some relaxed security on the domain, but I think that should be the organizations call. We for instance have our SQL server in an isolated domain and network so the client joining that domain makes little sense.

**Comment by cheenamalhotra** [comment]
Hi @twiggy 

ADS makes use of the SqlClient library underneath that does not support NTLM on Unix platforms - known issue https://github.com/dotnet/SqlClient/issues/31. Please upvote and follow up on SqlClient issue for future support and it does not fall in scope of ADS. I will close the request as 'External'.
