### ISSUE TITLE
Refresh Intellisense Cache Not Working

### ISSUE THREAD

**Issue by vaidymohan** [microsoft/azuredatastudio#4785]
Issue Type: <b>Bug</b>

Trying to refresh the intellisense cache using the shortcut wouldn't work. I've ensured that the key combination "CTRL+SHIFT+R" is used only for this action, under Keyboard Shortcuts. Still having a problem with this.

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz (4 x 1600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|

</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by anthonydresser** [comment]
Does the command pallet action work for you?

**Comment by vaidymohan** [comment]
Yes, the command palette action works, but not the keyboard shortcut.

**Comment by vaidymohan** [comment]
I think this was caused by the SSMS key map plugin. I disabled the plugin, recreated the binding under keyboard shortcuts and can confirm that it works. I'm closing this issue.

**Comment by anthonydresser** [comment]
@kevcunnane

**Comment by vaidymohan** [comment]
Hi @anthonydresser, looks like I'm having this issue again. This time no SSMS Keymap extension. Just a custom keybinding entry. Version: 1.6.0. Annoying to say the least.

**Comment by anthonydresser** [comment]
Can you verify that the command pallete entry still works and its just a keybinding issue?

**Comment by vaidymohan** [comment]
I can confirm that the command palette wouldn't work either. Something's clearly messed up, not sure which one it is. I deleted the settings.json and keybindings.json. Started afresh. Still an issue.

**Comment by Charles-Gagnon** [comment]
@vaidymohan Are you still seeing this issue? I'm not able to repro it myself. 

How are you determining that the action isn't working? And what type of server are you connecting to - Azure or On-Prem? There's known performance problems with Intellisense and Azure so you might just be seeing that manifesting where triggering the refresh isn't updating immediately.
