### ISSUE TITLE
New session not created

### ISSUE THREAD

**Issue by anugrah86** [microsoft/azuredatastudio#4786]
Issue Type: <b>Bug</b>

Followed the instructions as on https://docs.microsoft.com/en-gb/sql/azure-data-studio/sql-server-profiler-extension?view=sql-server-2017

However, the profiler session is not getting created.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (7.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by alanrenmsft** [comment]
@anugrah86 , what do you see when you press ALT+P? if that is not working, can you try invoke it from the command palette from the main menu -> view->Command palette and type Launch Profiler.
