### ISSUE TITLE
Merge Azure Data Studio Features into VSCode

### ISSUE THREAD

**Issue by mqmashwani** [Microsoft/azuredatastudio#4787]
My SQL development rarely happens in isolation of other code that I am writing. There is a significant cognitive/productiviy tax in having to go from VSCode to Azure Data Studio. As Azure Data Studio is forked from VSCode can the functionality of Azure Data Studio be merged into VSCode?

**Comment by mqmashwani** [comment]
This is not already covered in any of the referenced issues. Please review the request. For human eyes only. :smile:

> 
> 
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [VSCode Merge (#4712)](https://www.github.com/Microsoft/azuredatastudio/issues/4712)
> 
>     * [VSCode merge (#4639)](https://www.github.com/Microsoft/azuredatastudio/issues/4639)
> 
>     * [VSCode Merge (#4759)](https://www.github.com/Microsoft/azuredatastudio/issues/4759)
> 
>     * [VSCode Merge (#4738)](https://www.github.com/Microsoft/azuredatastudio/issues/4738)
> 
>     * [Vscode Merge (#4696)](https://www.github.com/Microsoft/azuredatastudio/issues/4696)

**Comment by kburtram** [comment]
Part of the VS Code fork process has been to add a bunch of new extensibility APIs that aren't compatible upstream.  Most ADS features can't work in VS Code without a significant rewrite, so this isn't something we're looking into doing.

Please open feature requests against https://github.com/Microsoft/vscode-mssql for any functionality in ADS that you'd like to have implemented in VS Code.
