### ISSUE TITLE
Old Scripts Loading

### ISSUE THREAD

**Issue by timothymcgrath** [microsoft/azuredatastudio#4788]
Issue Type: <b>Bug</b>

When I open a New Query for a database by right-clicking, New Query, it loads an old script from the last time I had the app open. I have Hot-Exit set to Off in Preferences. 

Sometimes the script it loads isn't even for the database that I have opened a query for. It's just an old script.

I really want it to not load any old scripts when I open the app and when I open new queries. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (17.97GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by timothymcgrath** [comment]
This issue appears to be resolved in the April update to Azure Data Studio.

**Comment by kburtram** [comment]
@timothymcgrath thanks for confirming.  I'll close this since the issue no longer repros.
