### ISSUE TITLE
I restarted Azure Data Studio with the latest insiders build and I see this error message related to Azure Resource Explorer.

### ISSUE THREAD

**Issue by ronychatterjee** [Microsoft/azuredatastudio#4791]
Issue Type: <b>Bug</b>

See this screenshot -

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/55358215-b4116a80-5483-11e9-85b8-9f5d41ce0ce2.png">

Azure Data Studio version: Azure Data Studio 1.6.0-insider (1bac929ab38e64560a6f663baa086a9b540c083c, 2019-03-25T23:14:03.156Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.05GB free)|
|Process Argv|-psn_0_4859042|
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-sanddance|dan|0.1.390
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0
sql-vnext|Mic|0.11.0

</details>

**Comment by anthonydresser** [comment]
I'll double check but I fixed that in this commit bceeda1cfdecbc2b7d41e7202204876a03b2d5f6

**Comment by anthonydresser** [comment]
Seems to be working for me on latest 
![image](https://user-images.githubusercontent.com/4324725/55358490-5fbaba80-5484-11e9-9cf7-984267d84f57.png)

Can you double check you don't have an update.
