### ISSUE TITLE
Add new connection doesn't work

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#4795]
1. Double click OE server to connect it
2. Create new notebook from right click server name->"New Notebook"
3. In Notebook attachTo dropdown, select "New Connection" -> select the same connection as OE server.
4. Then Select "Add New Connection" from attach to, then connection dialog doesn't show up

**Comment by kburtram** [comment]
I could no longer repro this issue.  Please reactive if the problem persists.
