### ISSUE TITLE
AttachTo selectBox onSelect event doesn't always fire

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#4796]
1. Open a notebook,
2. Add few connection via "Add New connection" from AttachTo
3. Switch the connections among the list,
4. Occasionally the value is selected, but it is stuck there. It wouldn't be refreshed.

![image](https://user-images.githubusercontent.com/43652751/55374662-299a2c80-54be-11e9-8ec4-b807981064f5.png)

**Comment by chlafreniere** [comment]
@YurongHe can you try and repro?

**Comment by YurongHe** [comment]
Not repro. It may caused by VS code merge before.
