### ISSUE TITLE
Lots of broken <DIV> attributes in ADS

### ISSUE THREAD

**Issue by geleems** [Microsoft/azuredatastudio#4805]
For example, `ng-reflect-ng-style` attribute in `DIV` shows `"[object Object]"` instead of actual string.
```
<div ng-reflect-ng-style="[object Object]">
```
There are several other attributes broken like this.

![image](https://user-images.githubusercontent.com/19577035/55429092-770aae00-553f-11e9-917a-30b92c8971df.png)

**Comment by anthonydresser** [comment]
Unless there is an actual functional bug, this isn't a bug. You can store objects on DOM elements as attributes and retrieve them later. The chrome debugger just shows it as object rather than stringifying the entire object.

**Comment by kburtram** [comment]
@geleems please reactive with additional details if there is any user-facing impact associated with these DOM elements.
