### ISSUE TITLE
Connection Dialog: Advanced Settings Dialog broken

### ISSUE THREAD

**Issue by abist** [Microsoft/azuredatastudio#4809]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Open Connection Dialog.
2. Open Advanced Settings.

Expected - All options show up
Actual - Replication Options is missing due to sizing error. In addition, collapsing or expanding the options sections doesn't collapse the section.

![Capture](https://user-images.githubusercontent.com/6411451/55442543-f1e5c000-5563-11e9-88a8-89b23878a038.JPG)

**Comment by anthonydresser** [comment]
Have you discovered if this was on master?

**Comment by abist** [comment]
Closing as it seems fine. Will reopen if I find a concrete issue again.
