### ISSUE TITLE
TRANSLATE is not recognized built in function

### ISSUE THREAD

**Issue by databull** [Microsoft/azuredatastudio#4815]
Issue Type: <b>Bug</b>

can it be overriden and added so there is no squiggly line as compiler has no problems running the code?

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v3 @ 2.40GHz (8 x 2397)|
|GPU Status|2d_canvas: unavailable_software<br>checker_imaging: disabled_off<br>flash_3d: unavailable_software<br>flash_stage3d: unavailable_software<br>flash_stage3d_baseline: unavailable_software<br>gpu_compositing: unavailable_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled_readback<br>webgl2: unavailable_off|
|Memory (System)|32.00GB (26.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
import|Mic|0.7.0
profiler|Mic|0.7.0
sql-vnext|Mic|0.11.0

(1 theme extensions excluded)

</details>

![image](https://user-images.githubusercontent.com/22824483/55463854-c6a9b200-55f1-11e9-91aa-c2402f6c2099.png)

**Comment by kburtram** [comment]
These error messages are coming from the T-SQL parser which is share with SSMS.  We'd need this to be fixed upstream to resolve this issue.

**Comment by Charles-Gagnon** [comment]
This was recently fixed in the parser and no longer repros for me in the current version of ADS (1.6.0). I'll close this as such - if you still see that behavior even after updating please reopen the issue and I'll investigate. 

![image](https://user-images.githubusercontent.com/28519865/56635413-5ef7ed00-661a-11e9-9040-1c45f99a979b.png)
