### ISSUE TITLE
Check for updates 403 error not helpful enough

### ISSUE THREAD

**Issue by toddlindner** [microsoft/azuredatastudio#4818]
At my office the firewall likes to block software downloads.  This looks like it is blocking the Data Studio auto updater.  

When I click check for updates I get a small window in the bottom right hand corner that says "Server returned 403, Source: Update Service."  Is there a way I can find out the full URL it is trying to request so I can request it be whitelisted by my IT team?  This popup window detail arrow is a good opportunity to show the full URL when there is an error connecting.  

I tried digging through the developer tools including the network tab, but never was able to see where it is trying to connect to.

Here is the stacktrace from the console:

Server returned 403
\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 Server returned 403

  | Zone.__load_patch.consoleMethods.forEach.console.(anonymous function) | @ | C:\Users\tlindner\Ap…t\zone-node.js:2280
-- | -- | -- | --
  | NotificationsAlerts.onDidNotificationChange | @ | workbench.main.js:171322
  | (anonymous) | @ | workbench.main.js:171310
  | Emitter.fire | @ | workbench.main.js:21573
  | NotificationsModel.notify | @ | workbench.main.js:175790
  | NotificationService.notify | @ | workbench.main.js:238752
  | UpdateContribution.onError | @ | workbench.main.js:374292
  | UpdateContribution.onUpdateStateChange | @ | workbench.main.js:374254
  | Emitter.fire | @ | workbench.main.js:21576
  | (anonymous) | @ | workbench.main.js:153033
  | Emitter.fire | @ | workbench.main.js:21573
  | handler | @ | workbench.main.js:33450
  | ChannelClient.onResponse | @ | workbench.main.js:33502
  | ChannelClient.onBuffer | @ | workbench.main.js:33491
  | (anonymous) | @ | workbench.main.js:33355
  | Emitter.fire | @ | workbench.main.js:21573
  | (anonymous) | @ | workbench.main.js:33717
  | Emitter.fire | @ | workbench.main.js:21573
  | fn | @ | workbench.main.js:22053
  | ZoneDelegate.invokeTask | @ | C:\Users\tlindner\Ap…st\zone-node.js:421
  | Zone.runTask | @ | C:\Users\tlindner\Ap…st\zone-node.js:188
  | ZoneTask.invokeTask | @ | C:\Users\tlindner\Ap…st\zone-node.js:496
  | ZoneTask.ZoneTask.cancelFn.invoke | @ | C:\Users\tlindner\Ap…st\zone-node.js:485
  | emitTwo | @ | events.js:126
  | emit

**Comment by kburtram** [comment]
The update server is `https://azuredatastudio-update.azurewebsites.net`.  Then we download the update bits from `https://azuredatastudiobuilds.blob.core.windows.net`.

**Comment by kburtram** [comment]
Closing based on the previous comment.  Please let us know if there is anything else we can do to unblock this scenario.

**Comment by toddlindner** [comment]
Ok to close as those domains are no longer blocked for me, but per your comment I was under the impression you were going to enhance the error message.
