### ISSUE TITLE
Compare doesn't highlight differences

### ISSUE THREAD

**Issue by AndrewCarmichaelWiggle** [microsoft/azuredatastudio#4819]
Issue Type: <b>Bug</b>

1) Open two files which are slightly different (eg. an extra AND condition added to a WHERE clause)
2) Right-click on one file in the OPEN EDITORS list and click Select for Compare
3) Right-click on the other file in the OPEN EDITORS list and click Compare with Selected

Expected: A new pair of panes will be displayed showing the two files side-by-side with differences highligted

Actual: A new pair of panes is displayed showing the two files side-by-side, but no differences are highlighted. I can _see_ the differences if I know where to look, but they're not highlighted.

NB. If I perform the same steps with the same files in VSCode, then the differences are highlighted as expected.

NB2. Temporarily disabling extensions doesn't affect the Actual results

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (8 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.93GB (5.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.3.1

</details>

**Comment by yamatoya** [comment]
It might be resolved by PR #4826

**Comment by kisantia** [comment]
I'm unable to repro this in the latest ADS release. Please reopen with screenshots if this is still happening
