### ISSUE TITLE
Query results sometimes shows blank rows in multiple of resultsets

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azuredatastudio#4821]
Issue Type: <b>Bug</b>

I have a query that I run every day that displays error logs from our servers. This query can return 100+ rows. On occassion (once a week or so) running the query shows the results but as you scroll down you after a couple of pages you see blank rows for several pages and then the data data starts showing up again. It skips whatever rows were blank. So, for example, if I had a column that started at 1 and incremented for each row and 10 rows got skipped I might see the last row of 12 and then 10 blank lines followed by the start of 22. It is literally skipping the rows and putting blank lines instead.

![EndOfSkip](https://user-images.githubusercontent.com/3778674/55485561-4cc4f900-55f0-11e9-8d9d-97409cba3246.PNG)
![StartOfSkip](https://user-images.githubusercontent.com/3778674/55485562-4cc4f900-55f0-11e9-910e-aa5db042b88c.PNG)

The same query in SSMS works fine so it isn't a data issue. Rerunning the query also resolves the issue.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.92GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
This should be fixed in current builds.
