### ISSUE TITLE
Connection Handling with Azure SQL DB

### ISSUE THREAD

**Issue by jdanton** [microsoft/azuredatastudio#4824]
Issue Type: <b>Bug</b>

I'm getting erroneous error behavior when trying to reconnect to an open session on Azure SQL DB. I suspect this is related to firewall rules. I'm on Microsoft Corpnet, so my IP changes every day, and I suspect this is related to that and a lack of firewall rules, but the error does not report as such. 

Azure Data Studio version: Azure Data Studio 1.6.0-insider (e1e9c08242b66062cb22397238eede3bc92ef19f, 2019-03-27T17:42:36.552Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|6, 10, 9|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv|-psn_0_184365|
|Screen Reader|no|
|VM|20%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
alwayson-insights|mat|0.2.1
mssql-instance-insights|mat|0.2.1
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.6.9
whoisactive|Mic|0.1.1

</details>

**Comment by Charles-Gagnon** [comment]
@jdanton Can you provide any further information such as :

1. How frequently does this occur?
2. Are there any specific repro steps that can consistently repro the issue?
3. What's the error you're seeing?

**Comment by jdanton** [comment]
It does seem to be the same bug as reported here: Error to create new firewall rule (#4182)

**Comment by Charles-Gagnon** [comment]
Alright, I'll close this one as a duplicate then and if you see any other issues that aren't covered by that you can re-open this issue or create a new one.
