### ISSUE TITLE
Intellisense not refreshing

### ISSUE THREAD

**Issue by gh0st** [microsoft/azuredatastudio#4825]
Issue Type: <b>Bug</b>

Using the refresh intellisense command from the CTRL+SHIFT+P, intellisense does not pick up new schemas, and new tables created under that schema.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.88GB (16.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none
(1 theme extensions excluded)

**Comment by gh0st** [comment]
#3990 is closed, it's probably closer to #4817.

**Comment by robertwray** [comment]
It looks like the IntelliSense cache *is* being refreshed, but the refreshed cache is only picked up from new query tabs. If you do the following:

1. Open a tab connected to a SQL Server
2. Run 'CREATE TABLE dbo.OtherTable (ColumnName INT)'
3. Type 'SELECT * FROM dbo.OtherTable'
4. Note that dbo.OtherTable has squiggles
5. CTRL-SHIFT-P - Choose 'Refresh Intellisense Cache'

The red squiggles will remain under dbo.OtherTable. Follow this by:

1. Opening a new tab (CTRL-N)
2. Type 'SELECT * FROM dbo.OtherTable'

Code completion of the table name **is** provided and there won't be a red squiggle under the name of the table

**Comment by gh0st** [comment]
Aw is that by design?

**Comment by robertwray** [comment]
@gh0st - I very much doubt it, I’m sure it didn’t behave that way previously. I added the detail as it might help whoever picks this issue up to trace down a resolution a bit quicker :)

**Comment by Abhijit-Revamp** [comment]
Same issue on macOS

**Comment by Charles-Gagnon** [comment]
@robertwray Thanks for the detailed repro! I wasn't able to repro your exact issue though. If I :

1. Open a new query window
2. Type

```
CREATE TABLE dbo.Foo (col INT)
GO
SELECT * FROM dbo.Foo
```

then I don't get the red squiggles.

I DO have the issue though where if I delete the CREATE TABLE statement then the red squiggles appear - even after refreshing the Intellisense cache. So that's definitely a bug there that I'll look in to. 

But just to make sure we're not missing anything are you seeing other incorrect behavior?

**Comment by WholeStackDev** [comment]
I see that @Charles-Gagnon created a pull request to fix this, but just wanted to chime in as someone experiencing this issue. Hope it gets merged and goes out soon!
