### ISSUE TITLE
"Find" (Ctrl+F on Windows) not available in notebooks

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#4828]
Issue Type: <b>Bug</b>

I create a notebook and put code and text in it.  After a while, I want to find some code or text I previously entered.  But the Find option on the edit menu doesnt work

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.84GB (17.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.3.2
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by chlafreniere** [comment]
This won't end up making November so moving this back to planning. Still solving some challenges in this space.

**Comment by chlafreniere** [comment]
This was implemented by #8426.
