### ISSUE TITLE
Release notes linked in Insider build and Stable Build goes to VS Code

### ISSUE THREAD

**Issue by DaveDustin** [Microsoft/azuredatastudio#4835]
Issue Type: <b>Bug</b>

Ran Check For Updates on 1.5.1 insider build.
When the notification dialog popped up, I clicked "Release Notes"
![image](https://user-images.githubusercontent.com/12723166/55513861-3cca1980-56c3-11e9-9dae-cf76216d62a7.png)

The page that is presented appears to be the September 2016 notes for VS Code
![image](https://user-images.githubusercontent.com/12723166/55513876-4489be00-56c3-11e9-96dc-77e694be5333.png)

Azure Data Studio version: azuredatastudio 1.5.1-insider (6d7d485a3840daf2da335b0cf527f98373ce29e6, 2019-03-19T07:23:34.608Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2208)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.82GB (17.28GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by vickyharp** [comment]
I was able to repro this.

**Comment by yualan** [comment]
Edited this since it repros in Stable. Will work on changing this.
