### ISSUE TITLE
Need New Notebook Task from Database Dashboard

### ISSUE THREAD

**Issue by chlafreniere** [Microsoft/azuredatastudio#4838]
Need New Notebook Task from Dashboards when connecting to SQL.

**Comment by chlafreniere** [comment]
Blocked because database dashboard is hardcoded to be a 2x2 grid.

**Comment by yamatoya** [comment]
![image](https://user-images.githubusercontent.com/2118539/56074868-53275200-5df4-11e9-9574-a31803a5bfdf.png)
How about a 4*2 grid?

**Comment by chlafreniere** [comment]
This is a dupe.
