### ISSUE TITLE
Cannot connect to a database unless trying to connect to two at once

### ISSUE THREAD

**Issue by charlieduso** [Microsoft/azuredatastudio#4852]
Issue Type: <b>Bug</b>

Attempting to connect to a database will load indefinitely - unless, at the same time, you attempt to connect to another database.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (4.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
@charlieduso Thanks for reporting the issue. Can you elaborate a bit more on what kind of database you were trying to connect to? Was it a SQL Server DB?

**Comment by charlieduso** [comment]
Yes, this is an issue with a SQL Server 2016 instance. The initial connection stalls indefinitely (unless I attempt a connection on another server at the same time), but can instantly reconnect after the initial connection.
