### ISSUE TITLE
Unattended install of extensions

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#4853]
I try to automate my installs including azure data studio and am stuck with unattended/scripted installs of extensions.

for example:

azuredatastudio.exe --install-extension C:\Users\bigdata\Desktop\sql-vnext-0.11.0-win-x64.vsix

this does not have any effect.

ideally, this would install the extension WITHOUT opening the UI so this would work with any kind of installer script but even if this would require the UI to open, it would be a huge help.

unless this already works and I am just doing it wrong :)

**Comment by alanrenmsft** [comment]
@bweissman Hi Ben, I just tried it with the same extension and it worked for me, the only difference is I am using 'azuredatastudio --install-extension ...', azuredatastudio points to the azuredatastudio.cmd not the .exe file. I think by default the azuredatastudio.cmd got placed into the PATH environment variable, can you please give it a try and let me know?

Thanks
Alan

**Comment by bweissman** [comment]
Ok, this is working now. It did not work in April so apparently something changed but either way, I am happy :)

Thank you!
