### ISSUE TITLE
PIP INSTALL of MSSQLCTL with --force-reinstall from Juypter Notebook sometimes fails with EnvironmentError: [WinError 5] Access is denied:

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#4855]
- Azure Data Studio Version:
Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
The 2nd or 3rd execution of MSSQLCTL re-install from Notebook fails with Access Denied; We have tried this from command line many a times
but have never been able to reproduce the issue outside notebook.

import sys
url="https://" + docker_registry + "/python/" + mssql_version + "/mssqlctl/requirements.txt"
!{sys.executable} -m pip install -r {url} --force-reinstall

Looking in links: https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/
Collecting mssqlctl_cli_app>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 2))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli_app-15.0.1400.75-py2.py3-none-any.whl
Collecting mssqlctl_cli_profile>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 3))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli_profile-15.0.1400.75-py2.py3-none-any.whl
Collecting mssqlctl_cli_storage>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 4))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli_storage-15.0.1400.75-py2.py3-none-any.whl
Collecting mssqlctl_cli_cluster>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli_cluster-15.0.1400.75-py2.py3-none-any.whl (45kB)
Collecting mssqlctl_cli>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 6))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli-15.0.1400.75-py2.py3-none-any.whl
Collecting mssqlctl_cli_core>=15.0.1400.75 (from -r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Downloading https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/mssqlctl_cli_core-15.0.1400.75-py2.py3-none-any.whl (81kB)
Collecting PyYAML==3.13 (from mssqlctl_cli_app>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/4f/ca/5fad249c5032270540c24d2189b0ddf1396aac49b0bdc548162edcf14131/PyYAML-3.13-cp36-cp36m-win_amd64.whl
Collecting jinja2 (from mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting kubernetes>=7.0.0 (from mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/00/f7/4f196c55f1c2713d3edc8252c4b45326306eef4dc10048f13916fe446e2b/kubernetes-9.0.0-py2.py3-none-any.whl
Collecting requests>=2.9.1 (from mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Collecting urllib3>=1.15.1 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/62/00/ee1d7de624db8ba7090d1226aebefab96a2c71cd5cfa7629d6ad3f61b79e/urllib3-1.24.1-py2.py3-none-any.whl
Collecting knack (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/bc/f8/a3c3142d76b40c53272928b0f9e4d0675055c8cc13f67d65558e7d5029aa/knack-0.5.4-py2.py3-none-any.whl
Collecting humanfriendly>=4.17 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/90/df/88bff450f333114680698dc4aac7506ff7cab164b794461906de31998665/humanfriendly-4.18-py2.py3-none-any.whl
Collecting certifi>=14.05.14 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/60/75/f692a584e85b7eaba0e03827b3d51f45f571c2e793dd731e598828d380aa/certifi-2019.3.9-py2.py3-none-any.whl
Collecting python-dateutil>=2.5.3 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/41/17/c62faccbfbd163c7f57f3844689e3a78bae1f403648a6afb1d0866d87fbb/python_dateutil-2.8.0-py2.py3-none-any.whl
Collecting six==1.11.0 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting setuptools==30.4.0 (from mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/16/9b/5e491cef98014d9a1b1f15896e503661d3973d02970583cfb026b613d0fd/setuptools-30.4.0-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from jinja2->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/b9/82/833c7714951bff8f502ed054e6fbd8bd00e083d1fd96de6a46905cf23378/MarkupSafe-1.1.1-cp36-cp36m-win_amd64.whl
Collecting requests-oauthlib (from kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/c2/e2/9fd03d55ffb70fe51f587f20bcf407a6927eb121de86928b34d162f0b1ac/requests_oauthlib-1.2.0-py2.py3-none-any.whl
Collecting google-auth>=1.0.1 (from kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/c5/9b/ed0516cc1f7609fb0217e3057ff4f0f9f3e3ce79a369c6af4a6c5ca25664/google_auth-1.6.3-py2.py3-none-any.whl
Collecting websocket-client!=0.40.0,!=0.41.*,!=0.42.*,>=0.32.0 (from kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/29/19/44753eab1fdb50770ac69605527e8859468f3c0fd7dc5a76dd9c4dbd7906/websocket_client-0.56.0-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.9.1->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5 (from requests>=2.9.1->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting colorama (from knack->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/4f/a6/728666f39bfff1719fc94c481890b2106837da9318031f71a8424b662e12/colorama-0.4.1-py2.py3-none-any.whl
Collecting pygments (from knack->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/13/e5/6d710c9cf96c31ac82657bcfb441df328b22df8564d58d0c4cd62612674c/Pygments-2.3.1-py2.py3-none-any.whl
Collecting jmespath (from knack->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/83/94/7179c3832a6d45b266ddb2aac329e101367fbdb11f425f13771d27f225bb/jmespath-0.9.4-py2.py3-none-any.whl
Collecting argcomplete (from knack->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/2e/22/374114e3e3692002f6aad1038faa3ca062668942da9c43f25c04100cdfb1/argcomplete-1.9.5-py2.py3-none-any.whl
Collecting tabulate (from knack->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/c2/fd/202954b3f0eb896c53b7b6f07390851b1fd2ca84aa95880d7ae4f434c4ac/tabulate-0.8.3.tar.gz
Collecting pyreadline; sys_platform == "win32" (from humanfriendly>=4.17->mssqlctl_cli_core>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/bc/7c/d724ef1ec3ab2125f38a1d53285745445ec4a8f19b9bb0761b4064316679/pyreadline-2.1.zip
Collecting oauthlib>=3.0.0 (from requests-oauthlib->kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/16/95/699466b05b72b94a41f662dc9edf87fda4289e3602ecd42d27fcaddf7b56/oauthlib-3.0.1-py2.py3-none-any.whl
Collecting cachetools>=2.0.0 (from google-auth>=1.0.1->kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/39/2b/d87fc2369242bd743883232c463f28205902b8579cb68dcf5b11eee1652f/cachetools-3.1.0-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.2.1 (from google-auth>=1.0.1->kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/da/98/8ddd9fa4d84065926832bcf2255a2b69f1d03330aa4d1c49cc7317ac888e/pyasn1_modules-0.2.4-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from google-auth>=1.0.1->kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/02/e5/38518af393f7c214357079ce67a317307936896e961e35450b70fad2a9cf/rsa-4.0-py2.py3-none-any.whl
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=7.0.0->mssqlctl_cli_cluster>=15.0.1400.75->-r https://private-repo.microsoft.com/python/ctp-2.4/mssqlctl/requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/7b/7c/c9386b82a25115cccf1903441bba3cbadcfae7b678a20167347fa8ded34c/pyasn1-0.4.5-py2.py3-none-any.whl
Installing collected packages: urllib3, colorama, six, pygments, jmespath, argcomplete, PyYAML, tabulate, knack, pyreadline, humanfriendly, certifi, python-dateutil, setuptools, mssqlctl-cli-core, mssqlctl-cli-app, mssqlctl-cli-profile, mssqlctl-cli-storage, MarkupSafe, jinja2, chardet, idna, requests, oauthlib, requests-oauthlib, cachetools, pyasn1, pyasn1-modules, rsa, google-auth, websocket-client, kubernetes, mssqlctl-cli-cluster, mssqlctl-cli
  Found existing installation: urllib3 1.24.1
    Uninstalling urllib3-1.24.1:
      Successfully uninstalled urllib3-1.24.1
  Found existing installation: colorama 0.4.1
    Uninstalling colorama-0.4.1:
      Successfully uninstalled colorama-0.4.1
  Found existing installation: six 1.11.0
    Uninstalling six-1.11.0:
      Successfully uninstalled six-1.11.0
  Found existing installation: Pygments 2.3.1
    Uninstalling Pygments-2.3.1:
      Successfully uninstalled Pygments-2.3.1
  Found existing installation: jmespath 0.9.4
    Uninstalling jmespath-0.9.4:
      Successfully uninstalled jmespath-0.9.4
  Found existing installation: argcomplete 1.9.5
    Uninstalling argcomplete-1.9.5:
      Successfully uninstalled argcomplete-1.9.5
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13
  Found existing installation: tabulate 0.8.3
    Uninstalling tabulate-0.8.3:
      Successfully uninstalled tabulate-0.8.3
  Running setup.py install for tabulate: started
    Running setup.py install for tabulate: finished with status 'done'
  Found existing installation: knack 0.5.4
    Uninstalling knack-0.5.4:
      Successfully uninstalled knack-0.5.4
  Found existing installation: pyreadline 2.1
    Uninstalling pyreadline-2.1:
      Successfully uninstalled pyreadline-2.1
  Running setup.py install for pyreadline: started
    Running setup.py install for pyreadline: finished with status 'done'
  Found existing installation: humanfriendly 4.18
    Uninstalling humanfriendly-4.18:
      Successfully uninstalled humanfriendly-4.18
  Found existing installation: certifi 2019.3.9
    Uninstalling certifi-2019.3.9:
      Successfully uninstalled certifi-2019.3.9
  Found existing installation: python-dateutil 2.8.0
    Uninstalling python-dateutil-2.8.0:
      Successfully uninstalled python-dateutil-2.8.0
  Found existing installation: setuptools 30.4.0
    Uninstalling setuptools-30.4.0:
      Successfully uninstalled setuptools-30.4.0
  Found existing installation: mssqlctl-cli-core 15.0.1400.75
    Uninstalling mssqlctl-cli-core-15.0.1400.75:
      Successfully uninstalled mssqlctl-cli-core-15.0.1400.75
  Found existing installation: mssqlctl-cli-app 15.0.1400.75
    Uninstalling mssqlctl-cli-app-15.0.1400.75:
      Successfully uninstalled mssqlctl-cli-app-15.0.1400.75
  Found existing installation: mssqlctl-cli-profile 15.0.1400.75
    Uninstalling mssqlctl-cli-profile-15.0.1400.75:
      Successfully uninstalled mssqlctl-cli-profile-15.0.1400.75
  Found existing installation: mssqlctl-cli-storage 15.0.1400.75
    Uninstalling mssqlctl-cli-storage-15.0.1400.75:
      Successfully uninstalled mssqlctl-cli-storage-15.0.1400.75
  Found existing installation: MarkupSafe 1.1.1
    Uninstalling MarkupSafe-1.1.1:
      Successfully uninstalled MarkupSafe-1.1.1
jupyter-console 6.0.0 has requirement prompt-toolkit<2.1.0,>=2.0.0, but you'll have prompt-toolkit 1.0.15 which is incompatible.
Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 
'C:\\Users\\pradm\\AppData\\Local\\Temp\\1\\pip-uninstall-td2wem0d\\ads_python\\0.0.1\\lib\\site-packages\\markupsafe\\_speedups.cp36-win_amd64.pyd'
Consider using the `--user` option or check the permissions.

**Comment by kevcunnane** [comment]
I'm going to close this as external. @ronychatterjee please help pick this up from the point of view of notebook creation
