### ISSUE TITLE
ADS Notebook without activity consuming 1gb of Memory

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#4857]
- Azure Data Studio Version:
Version: 1.5.2 (user setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.14393

Steps to Reproduce:
Is it common for the Idle BDC Notebook to consume around 1gb of memory. At present I am not running any commands or making any installs, connections to Azure from Notebook.
This is the same notebook I had used for BDC deployment in the morning. Post deployment I have left it open and in idle state for more than 2hrs now. I had not validated what is the consumption When deployment or mssqlctl installation was happening so I am not sure if it was acquired during that time and never got released. I have taken a full dump of the process from debugdiag if someone Is interested to review the same. The dump cannot be attached as zip file is around 250mb and the dump is 1gb in size,Let me know if you want to investigate i can share it.

Snapshot from process explorer within ADS
![mem1](https://user-images.githubusercontent.com/27516588/55562194-13d07580-5711-11e9-8d0d-d3fb2408f5f0.jpg)

Debug Diag process display
![mem2](https://user-images.githubusercontent.com/27516588/55562219-1fbc3780-5711-11e9-9b19-13830e0733aa.jpg)

Further drilling this down I see the following where in the Jupyter-notebook.exe is not consuming much memory and also adding up private bytes of all the child processes
Doesn’t sum up to the parent consumption. So the consumption should be by the parent itself and none of the child is contributing to the same.

![mem3](https://user-images.githubusercontent.com/27516588/55562245-2cd92680-5711-11e9-819d-52e8134d2173.jpg)

To eliminate Notebook out of the picture I closed the notebook , disabled and un-installed SQL Server 2019 extension and that did not make much difference.
So I am not sure it’s actually contributed by notebook or not as after all these activities I still see the jupyter-notebook.exe launched and was not unloaded

After almost 1hr of duration I see that the jupyter-notebook has been unloaded and the memory consumption is back to normal.
So it looks like the behavior is not similar to mssqlctl.exe which was always resident rather for notebook binary unloading is very slow and memory release is also relative to the same.

If you notice this snapshot the azure data studio pid 19840 chain is completely gone under which jupyter-notebook was provisioned. More than the termination I am worried about
Why its consuming around a 1gb of memory even when the notebook is idle and I couldn’t account for that from child processes. Is it something like the python kernel takes huge amount
Of memory?
![mem4](https://user-images.githubusercontent.com/27516588/55562269-3bbfd900-5711-11e9-9cd1-c8097d6fdfb6.jpg)

On the same lines if I open multiple notebooks the jupyter-notebook , python chain duplicates here ; is this a by design behavior which cannot be changed. If I am managing
4 cluster via ADS then along with this 4 instances of mssqlctl would also get loaded. Is there a possibility to only load 1 occurance of necessary executables and binaries and reuse
them for all other notebook activity?

![mem5](https://user-images.githubusercontent.com/27516588/55562303-48dcc800-5711-11e9-9653-d66366e431a7.jpg)

**Comment by kevcunnane** [comment]
Perf improvement target for June

**Comment by YurongHe** [comment]
From Pradeep: "This issue as noticed in build 1.5.2 and I am currently using build 1.7.0.
I have not seen this issue re-occur so far on build 1.7.0. In case if it re-occurs I will capture the dumps again and probably re-open this bug."
