### ISSUE TITLE
Release Notes point to VS Code in Insider and Stable

### ISSUE THREAD

**Issue by yualan** [Microsoft/azuredatastudio#4860]
- Azure Data Studio Version: 1.5.2

Steps to Reproduce:

1. Open Command palette and type >release notes or click release notes when checking for an update
2. Open VS Code release notes (stable and Insiders

I'll work with team to define release note pipeline for in-app experience.

**Comment by anthonydresser** [comment]
I think this is a dupe of #4835

**Comment by yualan** [comment]
Sounds good, the past issue checker missed that one, and the older issue was only for the Insider build, not stable. I'll edit Dave's issue and make that the main issue.
