### ISSUE TITLE
[Feature] SQL Agent job details default date to DESC order

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#4867]
```
Version: 1.6.0-insider (user setup)
Commit: 504d5c91bc9d1781ea9f9eb6c245d43475941fef
Date: 2019-04-04T07:36:57.980Z
VS Code 1.31.1
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
```

Steps to Reproduce:

1. Open ADS
1. Connect to server
1. View SQL Agent job
1. Click on the job for history details
1. Dates are shown in ASC order, so it requires scrolling all the way down to find the latest execution.

![image](https://user-images.githubusercontent.com/11204251/55601706-c1e71a00-5727-11e9-9e94-e0d8e4bcce93.png)

SSMS defaults to job history in DESC order.

**Comment by abist** [comment]
@wsmelton Thanks for the suggestion. Will have the suggested change in the coming release of the Agent extension.
