### ISSUE TITLE
Git Diff not working

### ISSUE THREAD

**Issue by whizkidwwe1217** [Microsoft/azuredatastudio#4872]
Issue Type: <b>Bug</b>

If you go to the Source Control and click a modified file, it opens up a new diff viewer tab (Working Tree) but it's not showing the file differences/changes. Also, the left and right panels are not in-sync. If you scroll the left panel, the right panel doesn't scroll.

**Expected**: (Just like in Visual Code)
![image](https://user-images.githubusercontent.com/1977391/55608902-04edcf80-57b2-11e9-9ca4-2026dc2ec655.png)

**Actual**:
![image](https://user-images.githubusercontent.com/1977391/55608820-d96ae500-57b1-11e9-915c-7aaa04fa4e73.png)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (3.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0

(1 theme extensions excluded)

</details>

**Comment by anthonydresser** [comment]
dupe #4819
