### ISSUE TITLE
Cannot read property 'remove' of undefined.

### ISSUE THREAD

**Issue by mrakovich** [microsoft/azuredatastudio#4878]
- Azure Data Studio Version: Versión 1.5.2 (1.5.2)

When I change Query Tabs. Close all the tabs and for each tab indicate the error of the: 
Cannot read property 'remove' of undefined.

**Comment by kburtram** [comment]
Closing older issues that don't have recent repros.  The shell code in ADS has changed significantly since this issue was created.  Please let us know if the issue persists on current builds.
