### ISSUE TITLE
Open Dashboard's Search Panel Item Context Menu by Keyboard

### ISSUE THREAD

**Issue by maroonedsia** [microsoft/azuredatastudio#4881]
Issue Type: <b>Feature Request</b>

Currently, when an item is selected in Dashboard > Search panel, hitting the Menu key on keyboard does not open the right-click context menu for it, which I think it should. 

This issue may exist on other parts of the UI as well.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.81GB (2.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|1.3.0
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment]
The UX for this experience has significantly changed since this issue was filed.  Now there are `...` on the row that can display the context menu using the ENTER key.  Please let us know if you're still impacted by this issue.

![image](https://user-images.githubusercontent.com/599935/129646654-4f5208b8-8480-4588-84de-04e74f2d66a1.png)
