### ISSUE TITLE
can't change output column width in a notebook resultset grid

### ISSUE THREAD

**Issue by amthomas46** [Microsoft/azuredatastudio#4884]
- Azure Data Studio Version: 1.5.2

Steps to Reproduce:

1. Run a cell that has a table in the results
2. Try to resize any column width
3. I cant seem to make them wider or smaller like I used to

**Comment by chlafreniere** [comment]
Not able to repro this one in the insider build. @amthomas46 are you on Mac or Windows? I can test both just to be sure.

We fixed an output area notebook issue last week in the insiders build, which may be related. I'll confirm, though.

**Comment by amthomas46** [comment]
This was on Windows

**Comment by chlafreniere** [comment]
@YurongHe made improvements here for our April release with #4790. Just tried on both Windows and Mac, and we now resize correctly on double clicking.
