### ISSUE TITLE
Notebook: Misleading Execution Status / Action

### ISSUE THREAD

**Issue by MsSQLGirl** [Microsoft/azuredatastudio#4892]
Issue Type: <b>Bug</b>

When trying to execute a long running Code block (item 2 on the screenshot), the previous Code block (item 1) looks like it was still being run too. So users might think that the previous Code block is being executed together with the currenly long running Code block. 
![image](https://user-images.githubusercontent.com/6405919/55662759-7c7c2880-57cb-11e9-9a7b-c7bfb1b662a2.png)

Expected behavior:
Item 1's icon pointed by the red arrow above should not indicate like as if it's running. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.11.0
whoisactive|Mic|0.1.1

</details>

**Comment by chlafreniere** [comment]
Thanks for the bug, @MsSQLGirl. This has been fixed in the latest insiders builds.
