### ISSUE TITLE
Some actions hide Notebooks header (Tabs and ribbon)

### ISSUE THREAD

**Issue by RicardoNoerr** [microsoft/azuredatastudio#4896]
Issue Type: <b>Bug</b>

When creating a new notebook, sometimes adding markdown or code hides the top of the notebook (tabs and ribbon) not able to scroll top neither select actions of the ribbon. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (1.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
Over the past year, we've done quite a bit of work on the toolbar and cell styling. I cannot repro this issue any longer. Please feel free to reopen if you encounter this behavior again.
