### ISSUE TITLE
Splitted notebook don't show right ribbon on query results

### ISSUE THREAD

**Issue by RicardoNoerr** [microsoft/azuredatastudio#4897]
Issue Type: <b>Bug</b>

On splitted notebook (two panes) the left pane don't show the right ribbon (where I can select "save to csv...) on query result

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.18356

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.92GB (0.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
No longer able to repro this issue with 2 notebooks side by side:

![image](https://user-images.githubusercontent.com/40371649/102263382-15cc6f00-3ec9-11eb-829b-84cd3f40eca0.png)

Closing this issue for now. If you see this reoccur, please feel free to reopen.
