### ISSUE TITLE
Unable to execute query with results (Query failed: The file exists)

### ISSUE THREAD

**Issue by Matticusau** [microsoft/azuredatastudio#490]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce: Not sure that you will reproduce. 

I had a sqlops hang due to an endless loop of a cursor (whoops).

Now when ever I run a query that returns a resultset I get the error message
```
(9 rows affected)
Query failed: The file exists 
````
![01-errormsg](https://user-images.githubusercontent.com/11083642/34991222-8c214186-fb14-11e7-8f1f-8871cf1217f2.png)

This also is occurring in vscode through the mssql extension so maybe some shared storage or something?

I have tried deleting various temporary files without any success.

Tried uninstalling, reboot, and reinstall
Also tried removing the mssql ext and reinstalling that but nothing has worked.

**Comment by Matticusau** [comment]
I figured it out.
Had to delete the contents of $env:TEMP
I did try and delete the most recent files from that path earlier but obviously didn't get the culprit file.

Happy for you to close this. Although is it worth documenting this in the wiki? Otherwise I will blog about it myself :)

**Comment by kburtram** [comment]
@corivera could you please try to determine what's happening here?

**Comment by anthonypants** [comment]
Ran into this issue today, version 0.30.6 on Windows 10.

**Comment by kburtram** [comment]
I am going to close as "no repro".  Please let me know if you're still experiencing this problem.
