### ISSUE TITLE
[Database Support] SQLite

### ISSUE THREAD

**Issue by ConstantineK** [microsoft/azuredatastudio#4903]
If you want to see SQLite support in Azure Data Studio, click the thumbs up sign.

**Note:** Please keep comments to this issue focused on discussions of what you would like to see instead of +1 comments.

**Comment by OdinTech3** [comment]
Has there been any movements on this?

**Comment by hinchley2018** [comment]
New to this repo.
What work is involved in supporting SQLite in Azure Data Studio?
Maybe we can team up and build it?

**Comment by danielmeza** [comment]
It's important to point the community to the right direction, we need some start point to know how to get involved in to develop support for new engines.

**Comment by dhutchison** [comment]
So Azure Data Studio appears to be extension based, just like VS Code. 

The Postgres engine is an extension, with the repo for it here: https://github.com/microsoft/azuredatastudio-postgresql . There is developer documentation in the wiki for the repo for building the extension and installing locally. 

I can't seem to find any sort of documentation on adding an engine, but from a quick skim of the code there doesn't appear to be a huge amount of code behind this (few thousand LOC). Should be able to do some sort of reverse engineering to work out how this one works to create another.

**Comment by ferox** [comment]
This project provides a SQLite connection provider for use in Azure Data Studio tests.
Link: https://github.com/microsoft/azuredatastudio-sqlite

**Comment by OdinTech3** [comment]
@ferox Have you tried it, does it work well?

**Comment by ferox** [comment]
> @ferox Have you tried it, does it work well?

No.
Take a look at here: https://github.com/microsoft/azuredatastudio-sqlite/issues/5

**Comment by alanrenmsft** [comment]
Thank you for your feedback!  At this time we do not have this on our long-term roadmap and will close this issue to keep our backlog focused on requests that align with current plans.  Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.

**Comment by kilasuit** [comment]
@alanrenmsft It is of great sadness that this is currently out of scope for this tool. It is one of the few missing pieces that would IMO make it so much more useful than it already is.

**Comment by ffes** [comment]
It is a real shame that almost 1000 upvotes are not enough to at least keep the issue open

**Comment by asmith3006** [comment]
This would be a great addition to the program. Please reconsider this decision!

**Comment by DIMANRUS** [comment]
Hello. I'm interested in your products, so I'd like to see SqlLite support. Thanks.

**Comment by apis3445** [comment]
I would like to see SqlLite support.

**Comment by jerone** [comment]
> Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.

[Third most upvoted story](https://github.com/microsoft/azuredatastudio/issues?q=is%3Aissue+sort%3Areactions-%2B1-desc+). Please reopen.
