### ISSUE TITLE
When 'running all cells' continue to scroll the notebook to the active running cell

### ISSUE THREAD

**Issue by stuartpa** [Microsoft/azuredatastudio#4905]
Issue Type: <b>Feature Request</b>

Title says it all! :-)

Azure Data Studio version: azuredatastudio 1.6.0-insider (572010ded12659c9bb176017fadb7275c77b466b, 2019-04-05T07:34:09.569Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kevcunnane** [comment]
@chlafreniere - FYI this is something Jupyter does. The "run cell" behavior 1st sets cell as active & focuses it, then executes. We should definitely match this.

**Comment by chlafreniere** [comment]
Totally makes sense. We can make this happen for sure.
