### ISSUE TITLE
[Database Support] VistaDB

### ISSUE THREAD

**Issue by kendallmiller** [microsoft/azuredatastudio#4911]
I'm one of the developers of [VistaDB](https://vistadb.com) and we'd like to get in on this act - we have a VS extension and this seems like a natural fit!  VistaDB will be shipping .NET Core support soon and presently supports .NET Framework, Mono, and Xamarin for Mac, iOS, and Android so having an option for non-Windows developers would be a great fit for us.

VistaDB uses DML very close to SQL Server but the DDL is somewhat different.

---

If you want to see VistaDB support in Azure Data Studio, click the thumbs up sign.

Note: Please keep comments to this issue focused on discussions of what you would like to see instead of +1 comments.

**Comment by alanrenmsft** [comment]
Thank you for your feedback! This feature is currently out of scope and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.
