### ISSUE TITLE
Shouldnt prompt for storage pool external data source in the CSV external table wizard

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#4913]
Issue Type: <b>Bug</b>

There should only be one SqlStoragePool external data source per master instance SQL Server

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.2.0

**Comment by corivera** [comment]
Currently SQL allows creation of multiple storage pool data sources in the same database. So a user could theoretically have need for a dropdown here, although it's unlikely.
