### ISSUE TITLE
The error message about a database not having an external data source doesnt go away when you choose a DB that does

### ISSUE THREAD

**Issue by twright-msft** [Microsoft/azuredatastudio#4915]
Issue Type: <b>Bug</b>

Error message is "no valid data sources were found in the specified database".

Repro:
Create two DBs named 'A' and 'B'
Create the SqlStoragePool in B but not in A
Create a directory/CSV file in HDFS
Right click CSV file and use the external table wizard
Get to the screen to choose the DB
Error message will show because A does not have a SqlStoragePool external data source.  Choose B.  Error remains instead of going away.

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.2.0

![image](https://user-images.githubusercontent.com/14988070/55782275-c16cbd00-5a60-11e9-8880-bf3385a16e36.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
sql-vnext|Mic|0.11.0
sqlservbdc-app-deploy|Mic|2.3.0

</details>

**Comment by chlafreniere** [comment]
@geleems @corivera are you aware of this issue?

**Comment by corivera** [comment]
Fixed
