### ISSUE TITLE
[Database Support] Azure Cosmos DB

### ISSUE THREAD

**Issue by thomaslevesque** [microsoft/azuredatastudio#4916]
If you want to see Azure Cosmos DB support in Azure Data Studio, click the thumbs up sign.

**Note:** Please keep comments to this issue focused on discussions of what you would like to see instead of +1 comments.

**Comment by whitneyweaver** [comment]
My team spends a great deal of time in Data Explorer, via Azure Portal site, related to troubleshooting of individual user issues or within our analytics usage. Would be really great to execute the same basic SQL queries in ADS that can be done in web.

**Comment by d1820** [comment]
want cosmos support check out https://github.com/d1820/cosmos-query-manager

**Comment by anthonydotnet** [comment]
Any movement on this?

**Comment by iDanScott** [comment]
> Any movement on this?

came to ask the same thing

**Comment by zuhaerzim** [comment]
This would be super useful to have, any traction on this?

**Comment by onionhammer** [comment]
Any update? bumptybump

**Comment by willvelida** [comment]
This would be awesome to have! Especially since Cosmos DB support for Storage Explorer is deprecated.

It would be good to have support across all APIs. We use both Table and SQL API accounts and it would be nice to be able to navigate between them easily rather than having to navigate to different accounts in the portal.

+1 on being able to run queries in ADS (Similar to how you can use queries in the portal). Authoring notebooks, server-side scripts etc would also be nice-to-haves.

Support for RBAC roles would help us enable our Analytics team to read the data in our Cosmos accounts via ADS as Account Readers without having to provide them access to the portal. Being able to manage accounts as an Admin in ADS would be a nice-to-have, but not critical as we manage this via CI/CD anyway.

**Comment by onionhammer** [comment]
> Support for RBAC roles would help us enable our Analytics team to read the data in our Cosmos accounts via ADS as Account Readers without having to provide them access to the portal. Being able to manage accounts as an Admin in ADS would be a nice-to-have, but not critical as we manage this via CI/CD anyway.

SIDENOTE: Have you checked out azure synapse for this? I know it doesnt work for serverless which stinks...

**Comment by willvelida** [comment]
@onionhammer Synapse Link for Cosmos DB is awesome! I'm hoping it'll be open for all the APIs soon!

**Comment by fvilches17** [comment]
Hello 2021!

315 thumbs up at time of writing. What threshold are we looking at? 😃

**Comment by calloncampbell** [comment]
https://cosmos.azure.com works great but you need contributor access. It would be nice if this worked for read-only users.

**Comment by danparker276** [comment]
> https://cosmos.azure.com works great but you need contributor access. It would be nice if this worked for read-only users.

This seems like everything I need. It has upload and update item. I suppose I don't need it in azure data studio now.

**Comment by thomaslevesque** [comment]
I don't know if or when Cosmos support in ADS will happen, so in the meantime I created my own tool:
https://github.com/thomaslevesque/CosmosDBStudio/
It's far from complete, but it works well enough to have become my main tool for working with Cosmos DB.

**Comment by tomasznaumowicz** [comment]
As of today it's **429** thumbs up and **429** does have a hidden meaning to all of us here ;)
![image](https://user-images.githubusercontent.com/908651/141486189-aab7163b-57bd-429c-a570-c28e637aa970.png)

I wanted to let you know that we've built something as well. It's a professional IDE for Cosmos DB. Alpaqa Studio for Cosmos DB is being actively developed and we're adding new features on a weekly basis.

Feel free to try out Alpaqa Studio directly at https://alpaqastudio.com and to read a bit more about what it can do for you at https://alpaqastudio.com/features. A [Free Plan](https://alpaqastudio.com/sign-up) is available and can be activated [here](https://alpaqastudio.com/sign-up).

When you start it you'll discover that a demo database is attached - this means that you don't have to worry about a sandbox environment. It's there already.

The [Free Plan](https://alpaqastudio.com/sign-up) allows you to easily explore your Cosmos DB in a Table, Tree, and a JSON view.

**Comment by eabase** [comment]
Any other CLI options for CosmosDB?  
(Using CosmosDB without CLI is really a PITA!)

**Comment by alanrenmsft** [comment]
The Azure Cosmos DB extension is now available in Azure Data Studio:
![image](https://user-images.githubusercontent.com/13777222/193913624-e5eb96c0-3464-4146-b23d-dd88a4b27b3e.png)

You can open issues/feature requests at the extension's own repo: https://github.com/Azure/azure-cosmosdb-ads-extension

**Comment by calloncampbell** [comment]
This shows support for mongo db. When is SQL api support coming?

**Comment by alanrenmsft** [comment]
@calloncampbell The extension is owned by a different team in Microsoft, please open a feature request in the extension's repo: https://github.com/Azure/azure-cosmosdb-ads-extension.

> This shows support for mongo db. When is SQL api support coming?
