### ISSUE TITLE
[Database Support] Redis

### ISSUE THREAD

**Issue by atrauzzi** [microsoft/azuredatastudio#4918]
_As per [what's happening](https://github.com/Microsoft/azuredatastudio/issues/56#issuecomment-481007948) over at #56._

There is a glaring gap in the offering of tools around redis when it comes to a stable, easy to use and easy to acquire graphical front end.

Being able to peek into redis would be immensely helpful during local development when I want to debug or learn about the state my applications end up storing.

So, here we go again!

---
# STOP!
### Want redis supported??

 - **Click the 👍 icon**
 - Wait
 - Please **do not** add a comment with _"+1"_ in the message!

_I repeat_, please just upvote this initial problem-description. **Do not add a comment as it's harder for the maintainers to track and +1 comments create clutter for any detailed discussion.**

**CLICK THIS!!**
👇

**Comment by alanrenmsft** [comment]
Thank you for your feedback! This feature is currently out of scope, and we do not plan to work on it in a currently planned release. We will close this issue to keep our backlog focused on requests that we are planning to work on. Please note that users can continue to vote and comment on closed issues, which we encourage as it helps us understand user interest and can provide more details about why a feature is requested.

**Comment by atrauzzi** [comment]
JetBrains products are better anyway and they're adding redis support.
