### ISSUE TITLE
Ability to hide/close or resize Messages window

### ISSUE THREAD

**Issue by rsivakumar** [Microsoft/azuredatastudio#4919]
Issue Type: <b>Feature Request</b>

We need the ability to hide/close the messages window or at the very least being able to resize it to a smaller size. As it is right now, it takes up way too much space and leaves less room for the data that is being viewed. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment]
@rsivakumar have you tried setting the `Sql: Messages Default to Open" preference to false?  This will keep the messages window closed unless it is explicitly shown or there is an error.

**Comment by rsivakumar** [comment]
@kburtram  Looks like the latest update (version 1.6.0) has fixed this issue. When clicking on the arrow to close the Messages, it collapses down taking up little space. Thanks for fixing this.
