### ISSUE TITLE
Prompt for a file extension if one is not given for a new file under the Explorer (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4927]
Issue Type: <b>Feature Request</b>

1. Create a SQL Notebook by selecting New File under a folder group in Explorer.
2. Enter a name but do not add the notebook extension (.ipynb) needed to make this a SQL Notebook.

NOTE - that your notebook is just a file of unspecified type.

SUGGESTION
Provide a list of extensions for users to choose from if an extension is not given.

![image](https://user-images.githubusercontent.com/41927913/55818820-5ea11300-5aac-11e9-96ac-ed9bf5c70569.png)

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

**Comment by kburtram** [comment]
Closing as upstream.
