### ISSUE TITLE
Documentation on using SQL Notebooks does not tell you how you use SQL Notebooks (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4928]
Issue Type: <b>Bug</b>

1. Go to the ADS documentation to find information explaining how to work with SQL notebook cells. [https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-notebooks?view=sql-server-2017](https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-notebooks?view=sql-server-2017)

The help does not have any content that discussing working with code and text cells.

Add documentation explaining  how to use notebook compute and markdown cells (a.k.a., text cells).

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by chlafreniere** [comment]
@gengelbms Can you provide some more specifics here?

**Comment by gengelbms** [comment]
The SQL doc examples use only one code cell. Looking at the example you would not necessarily realize that notebooks let you write text using markdown. This is a request to change to the documentation to show the the use of markdown with SQL notebooks.  The person I observed did not find the documentation on writing text cells (**Code Cells and Markdown Cells**).  They stopped reading at the **Configure Python for Notebooks** section because they did not know Python and it seemed like a change of topic (i.e., it was not about SQL Notebooks).

**Comment by kevcunnane** [comment]
@ronychatterjee , @yualan have the docs been fixed? This is now in June milestone. Can you take on and commit to fixing? Thanks!

**Comment by ronychatterjee** [comment]
This was fixed and the changes were  pushed.
