### ISSUE TITLE
 Provide an easier way to re-connect to a database server (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4931]
Issue Type: <b>Feature Request</b>

Provide an easier way to re-connect to a database server if a server has disconnected. Often enough a server gets disconnected. Currently, you have to go through the process of getting re-connected by clicking on the server (too subtle) or creating a new connection to the server. We have watched a number of users create a new connection to connect to the server after looking for a "Reconnect" command off the right-click server menu.

Add a re-connect command.

![image](https://user-images.githubusercontent.com/41927913/55819734-403c1700-5aae-11e9-8ae5-14f04153c3fd.png)
![image](https://user-images.githubusercontent.com/41927913/55819778-5e097c00-5aae-11e9-8d12-c35c187fbaf0.png)

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

**Comment by cheenamalhotra** [comment]
OE now supports 'Refresh' icon which is more intuitive and easy to understand. Closing this issue as resolved.

<img src="https://github.com/microsoft/azuredatastudio/assets/13396919/21d19a02-db66-408d-b623-a6a3de8b565f" width=500 />
