### ISSUE TITLE
Let users sort and filter results sets by clicking on column headers (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4934]
Issue Type: <b>Feature Request</b>

Provide the ability to sort result sets by select the column header.

Additionally, filtering of result sets could be added to these commands.  This would make result sets behave close to Excel tables.

![image](https://user-images.githubusercontent.com/41927913/55820624-619e0280-5ab0-11e9-8c99-0ba86553fc7c.png)

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

**Comment by Callum-W** [comment]
Has there been any progress on this?  It's a massive flaw in the software imo.  To not be able to sort by id or name is extremely frustrating!

**Comment by kburtram** [comment]
We've added the ability to filter the query results.  We decided against sorting the table, and would recommend to use the `ORDER BY` clause in the query for that functionality.  Thanks for opening this suggestion!
