### ISSUE TITLE
Add a shortcut to create a notebook in the document well. (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4936]
Add the command and shortcut for creating a new notebook to the ADS document well (aka watermark).

![image](https://user-images.githubusercontent.com/41927913/55820862-f86abf00-5ab0-11e9-943e-95b15707654d.png)

**Comment by kevcunnane** [comment]
This is pretty easy and seems to add value. I'll pick this up. @kburtram any objections?

**Comment by kevcunnane** [comment]
Actually... I take this back. We would need to move the action internal (instead of via extension) and doing the right "when" clause on object explorer contributions with this might prove tricky. We can take a look for May instead.
