### ISSUE TITLE
Provide a command to convert a SQL file to a SQL Notebook file (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4937]
Provide a command that will convert a SQL file to a notebook file.

Ideally, this would convert comment lines to markdown and separate SQL statements into their own code cell.

**Comment by Charles-Gagnon** [comment]
@gengelbms This feature was recently added - you can try it out by using the `Export as Notebook` option in a SQL query editor

![image](https://user-images.githubusercontent.com/28519865/99839392-7f05d000-2b1f-11eb-8d89-facb0b423593.png)

Try it out and let us know if you have any other feedback!
