### ISSUE TITLE
Provide a command that display a diagram describing the database (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [Microsoft/azuredatastudio#4942]
When you are learning about or documenting a database it is great to have a diagram (e.g, ER diagram) of the database.

It would be great to have the ability to create a database diagram from for a database using ADS.

**Comment by gengelbms** [comment]
Duplicate of Please add database diagramming (#1752)

**Comment by kburtram** [comment]
Closing as duplicate of #1752
