### ISSUE TITLE
Add a create notebook command to the Manage Dashboard for databases (aduxr)

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4945]
Add a create notebook command to the Manage Dashboard for databases.

Currently you can create a new SQL File from the Manage Dashboard for a database but you cannot create a New SQL Notebook.

![image](https://user-images.githubusercontent.com/41927913/55822449-78465880-5ab4-11e9-992a-fae1a00c1021.png)

**Comment by kevcunnane** [comment]
Let's work on updating the default dashboard here.
