### ISSUE TITLE
Support switching text cells between code and text cells

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#4949]
It would be helpful if you could covert your code cell to a text cell and vice-versa.

This would make it easy to:
- Comment out a code cell
- Comment/uncomment unit test code
- Recover from mistakes when you write code into a text cell.

**Comment by MsSQLGirl** [comment]
This feature is now available in Sep 2020 RC1 as well as Insiders now. 
Version: 1.22.0-rc1 (user setup). 

![image](https://user-images.githubusercontent.com/6405919/93705740-74559d00-fad4-11ea-8ec2-dffa77370e01.png)

Please feel free to review and provide feedback :)
