### ISSUE TITLE
azdata.nb.notebookDocuments incorrect on restart

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4958]
The `notebookDocuments` API is incorrect on restart of Azure Data Studio if there are non-visible rehydrated documents. These all get treated as text documents until the customInputConverter codepath is fired. We should hook into the startup somehow to handle this and get these 2 sets of APIs (vscode.workspace.textDocuments and azdata.nb.notebookDocuments) to be accurate all the time.

**Comment by chlafreniere** [comment]
@kevcunnane can you describe the customer facing scenario that this impacts?

**Comment by kevcunnane** [comment]
So... I found this during "New Notebook" testing and mitigated by checking the textDocuments list. Without this you could be checking for what notebooks exist and wouldn't get any that were shown in tabs but not opened in the new session. Therefore customer impact is limited right now, because that's the primary use of the notebookDocuments API.

However a sample use case is:
- Have an extension that supports actions on any open notebook document
- Restart AzureDataStudio with notebooks listed but not visible
- Use the extension action
- Watch it fail to show your notebook.

**Comment by chlafreniere** [comment]
Closing this, given the ongoing API compat work, which will render this n/a.
