### ISSUE TITLE
Opening Azure Data Studio After Closing With Notebook Open Causes Error

### ISSUE THREAD

**Issue by ScaryDBA** [Microsoft/azuredatastudio#4965]
Every time I close Azure Data Studio while I have a Jupyter Notebook open, when I reopen ADS, I get the following error:
Could not display contents: Notebook provider does not exist

The Notebook will not load and no other notebooks will load. Closing all notebooks prior to closing ADS fixes the issue. ADS will load, then the notebooks will load.

CPUs | Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
-- | --
GPU Status | 2d_canvas: enabledchecker_imaging: disabled_offflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwarerasterization: enabledvideo_decode: enabledvideo_encode: enabledwebgl: enabledwebgl2: enabled
Memory (System) | 15.93GB (0.31GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
gitlens | eam | 9.5.1
docker-explorer | for | 0.1.6
agent | Mic | 0.37.0
azuredatastudio-postgresql | Mic | 0.1.0
import | Mic | 0.7.0
profiler | Mic | 0.7.0
sql-vnext | Mic | 0.11.0
PowerShell | ms- | 1.11.0
sql-search | Red | 0.3.1

**Comment by chlafreniere** [comment]
Thanks for the feedback! We're currently tracking this issue with #4580, so closing this one as a duplicate.
