### ISSUE TITLE
Azure Explorer Database node shows Server node content

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#4970]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Connect to Azure subscription
2. Expand a Database node

Expected: See database child content similar to if I expanded a database node in Servers view

Actual: See server child content, where a database shows all the databases available on the server.  It should show tables, views, etc. as top-level child content.

For example, `appdb` shouldn't be displayed below `master` in below screenshot.

<img width="494" alt="Screen Shot 2019-04-10 at 11 08 52 AM" src="https://user-images.githubusercontent.com/599935/55902942-549d1400-5b81-11e9-9d4f-5de2efa1c5de.png">

**Comment by anthonydresser** [comment]
I can't seem to repro.
![image](https://user-images.githubusercontent.com/4324725/55975895-cf2c6900-5c3f-11e9-8d40-87712abfb01d.png)

Can you try moving the connection to the servers view and see if it is the same as in the azure view?

**Comment by kburtram** [comment]
@anthonydresser it appears to be working now.  I'll close until I get consistent repro.
