### ISSUE TITLE
Azure account picker dropdown has no useful information

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#4975]
- Sign into Azure
- connect to an Azure server with no firewall rule set
- Click on your username to select between accounts.

Expected:
- Get concise account info
Actual:
- Just get org name like "Microsoft" (see screenshot below)

![image](https://user-images.githubusercontent.com/10819925/55915919-b10f2c00-5b9f-11e9-99d5-3fdea5d8829c.png)

**Comment by anthonydresser** [comment]
Is there a specific ask here? Theres a bug that it would be showing the org name and the user name. Does that accurately describe the scope of this bug?

**Comment by kevcunnane** [comment]
Yes. It just shows "Microsoft' right now. It should show the login (e.g. myname@myorg.com) for disambiguation. This seems like it's worse than it used to be, but happy to close if there's a matching bug.

Basically just look at how Visual Studio shows information in their Azure / identity dropdowns and do that. They're the gold standard in this regard.

**Comment by anthonydresser** [comment]
I'll scope this issue to just fixes the bug of bring the user name back to a visible state. Adding additional information (email) I think can be wrapped up with #3539
