### ISSUE TITLE
Azure: Firewall rule creation isn't supported from Azure section

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4978]
- Connect to Azure and expand to a server that doesn't have firewall rule open for your IP
- Expand to be prompted for login info
- Add valid SQL Login info

Expected:
- You're prompted for firewall info
Actual:
- Get error stating firewall isn't open. It's great we get the right error, but given it works elsewhere it's really weird it fails from here.

**Comment by anthonydresser** [comment]
fixes by #5564
