### ISSUE TITLE
Azure: SQL Databases should be sorted alphabetically not by SQL Server

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#4979]
- Have 2 or more Azure SQL servers (with SQL DBs)
- Connect to azure and expand SQL Databases node.

Expected:
- Sorted alphabetically by DB name
Actual:
- Grouped by server, then by DB name. This is really hard since there's no other filter. Makes it super hard to find the right DB.
- Even worse it's not by alphabetical server name, but in order servers were returned so it's completely arbitrary.

**Comment by aasimkhan30** [comment]
I see them organized alphabetically. Closing this issue.
