### ISSUE TITLE
How to connect to and run queries on CosmosDB

### ISSUE THREAD

**Issue by nptech9806** [Microsoft/azuredatastudio#4992]
Issue Type: <b>Feature Request</b>

a) Azure Cosmos DB - Microsoft's cloud service
b) Azure Data studio - Microsoft data management tool for Azure

Can (b) connect to (a)? 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kevcunnane** [comment]
At present this isn't supported. We are tracking this request in #4916 and would like to add support for other Azure Data services like this, however we do not have a committed date to start this work. I am going to close this issue as a duplicate as we'll use that issue to track requests for CosmosDB.
