### ISSUE TITLE
New Query/Manage menu items in Data Explorer always default to master

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#4994]
1. Right click on a Database node in the Data Explorer tree and select *New Query*

![image](https://user-images.githubusercontent.com/28519865/55982186-41f01100-5c4d-11e9-8c47-17a04b25b09a.png)

2. For New Query a login error is shown (separate issue #4351), after which the Connection dialog is shown. But the database field is always set to master, even if a user DB is selected

![image](https://user-images.githubusercontent.com/28519865/55982206-4f0d0000-5c4d-11e9-80f7-d60b75585684.png)

For Manage this is worse because it doesn't actually display the login error and connection dialog, instead it will happily connect to master - after which the user is unable to switch to viewing the Manage dashboard for a different DB so they're stuck.

**Comment by abist** [comment]
@Charles-Gagnon is this fixed?
