### ISSUE TITLE
Azure Repos

### ISSUE THREAD

**Issue by DataSlugger** [microsoft/azuredatastudio#5000]
Issue Type: <b>Feature Request</b>

Hello Team
I would like if you add azure repos [TFVC] like VS Code in this way we will have 2 options to choose where save our code for Source Control. In my actual job the company just use TFS as primary source control, so using VSCode I have the ability to choose which kind of source control use.

Thank you so much for read it. 

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.16299

**Comment by yualan** [comment]
I was looking into this with @geleems. I would be curious why it has a low rating on the marketplace, but I do know it works seamlessly for some of the engineers I spoke with. 

@MsSQLGirl this might be the best approach to get TFS/Azure DevOps integration into Azure Data Studio. We should think about approaching the Azure Repos maintainers.

**Comment by jmontero19** [comment]
@yualan the low rate could be for the high use of GitHub but in Enterprise environment the most common tool used is TFS and could a great enhancement in azure data studio if we can check in our code to TFS, for now I am using the azure repos in vscode for commit my SQL scripts to TFS.

**Comment by RowlandShaw** [comment]
I can't see anything in the Marketplace for connecting to Azure Repos / TFVC - which might be why you're seeing a low uptake :)

**Comment by MsSQLGirl** [comment]
Apologies for the late reply. As @jmontero19 mentioned, if you would like to use TFVC in Azure Data Studio, you can use the [Azure Repo](https://marketplace.visualstudio.com/items?itemName=ms-vsts.team) *vscode* extension. It seems to work reasonably well. There is some quirkiness when signing in (to my Azure DevOps TFVC repo), but eventually got it working after following [this instruction](https://github.com/microsoft/azure-repos-vscode/issues/371).

@jmontero19 - How are you going with TFVC in Azure Data Studio?
