### ISSUE TITLE
Connecting to local sqlexpress takes forever

### ISSUE THREAD

**Issue by nahojd** [microsoft/azuredatastudio#5011]
Issue Type: <b>Performance Issue</b>

Connecting to my local SQL Server Express instance with windows authentication takes a very long time, frequently several minutes. Once the connection is establish, everything works fine.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    4	    86	  2968	azuredatastudio main
    5	   224	    32	   gpu-process
    6	   227	  8744	   window (Azure Data Studio)
    0	   172	 20420	     extensionHost
    0	    28	 11408	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\SqlToolsResourceProviderService.exe" --log-file C:\Users\johan\AppData\Roaming\azuredatastudio\mssql\resourceprovider_20420.log --tracing-level Critical
    0	    11	 18852	         console-window-host (Windows internal process)
    0	    62	 15780	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\johan\AppData\Roaming\azuredatastudio\mssql\sqltools_20420.log --tracing-level Critical
    0	    11	 23408	         console-window-host (Windows internal process)
    0	    27	 18876	       "c:\Program Files\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.71\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\johan\AppData\Roaming\azuredatastudio\mssql\credentialstore_20420.log --tracing-level Critical
    0	    11	 14120	         console-window-host (Windows internal process)
    0	    32	 21360	       "C:\Program Files\Azure Data Studio\azuredatastudio.exe" "c:\Program Files\Azure Data Studio\resources\app\extensions\json-language-features\server\dist\jsonServerMain" --node-ipc --clientProcessId=20420
    2	    67	 13912	   shared-process
    1	    79	 23704	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by kburtram** [comment]
Closing out older issues that haven't seen recent repros.  I'm not sure what was happening in this scenario.  Though we have made significant changes in our connectivity stack since this issue, including moving to a different SQL Client driver, for example.  Please let us know if you're still impacted by this issue.  Thanks!
