### ISSUE TITLE
Cmd+a in Notebook Outputs Doesn't Do Anything on Mac

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5023]
On PC and Linux using the keyboard shortcut to select all in a notebook cell's output selects in the output.

On Mac, nothing happens.

**Comment by YurongHe** [comment]
I tried older build without any change. Look like never works on Mac.

**Comment by YurongHe** [comment]
query editor has the same behavior. It is general issue on Mac.

**Comment by kevcunnane** [comment]
This should work. Is it a regression and if so when did it happen? Select all needs to work.

**Comment by kevcunnane** [comment]
Fit & Finish for June

**Comment by YurongHe** [comment]
Similar request for query editor: Ctrl+A support in message pane and about pop-up #5153
