### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by RobLW** [Microsoft/azuredatastudio#5032]
When using the SQL engine in notebooks, if you do <img src=""> to an image on your drive, you need to provide the full path to the image, even if it is in the same folder as your notebook. If you then go to share that notebook, that image address is now invalid when user2 opens the notebook on their computer.

It would be really useful to be able to provide reletive paths for images. 

Also I've noticed that images are cached in the notebook. So If I loaded a local image. Then go and edit the image in another application, there appears to be no way to get that fresh edit into the notebook unless I rename the image file and update the link in the <img src> markup.

**Comment by chlafreniere** [comment]
We've fixed the relative path issue for markdown images in insiders builds. The fix will go out with our next release to our stable users.

For the second issue, we're a bit limited by what the markdown engine that we're using works under the covers, unfortunately.

**Comment by alanrenmsft** [comment]
Closing based on Chris's comment.
