### ISSUE TITLE
About box no longer shows VS Code source version

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#5033]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open About box

Expected: VS Code source code version is shown in About box

Actual:

![image](https://user-images.githubusercontent.com/599935/56154415-5134ce80-5f6d-11e9-816f-6ea790149693.png)

**Comment by alanrenmsft** [comment]
seems the issue has been fixed, i checked today's insiders build as well as local dev env.

![image](https://user-images.githubusercontent.com/13777222/56394556-94e93b80-61ec-11e9-9738-dba7300ae77a.png)

![image](https://user-images.githubusercontent.com/13777222/56394589-a9c5cf00-61ec-11e9-9211-d8bcc9d4f2d6.png)
