### ISSUE TITLE
The output for 'Configure Python for Notebooks' is not accurate

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#5036]
Run the command 'Configure Python for Notebooks' and open the output panel, I observed it first says 'Python installation is complete' and then followed by a bunch of other installation actions. 

Logs:
Downloading python package (159.34 / 159.34 MB)
Unpacking python package
Python installation is complete
Installing required packages to run Notebooks...
    > "C:\Users\alanren\azuredatastudio-python\0.0.1\python.exe" -m pip install --no-index -r "C:\Users\alanren\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt" --find-links "C:\Users\alanren\azuredatastudio-python\0.0.1\offlinePackages" --no-warn-script-location
    stdout: Looking in links: C:\Users\alanren\azuredatastudio-python\0.0.1\offlinePackages
    stdout: 
    stdout: Requirement already satisfied: pip in c:\users\alanren\azuredatastudio-pyth
.....

Expected:
I am expecting to see 'Python installation is complete' only when everything is completed.

**Comment by chlafreniere** [comment]
The string is a bit confusing, saying that python installation is complete. On Mac/Linux, we use the word complete here because the install (with packages) is actually done at this point. On PC, users see this message and then it takes some time until the packages are actually installed.
