### ISSUE TITLE
database size chart in server dashboard is not showing anything

### ISSUE THREAD

**Issue by alanrenmsft** [Microsoft/azuredatastudio#5037]
Today's insider build:
![image](https://user-images.githubusercontent.com/13777222/56167284-a3d1b300-5f8c-11e9-9507-a1fda915572b.png)

**Comment by anthonydresser** [comment]
Seems to be working for me
![image](https://user-images.githubusercontent.com/4324725/56170902-214ef080-5f98-11e9-945f-74222d1a160a.png)
Any additional repro steps?

**Comment by alanrenmsft** [comment]
@anthonydresser  I am using today's insider build on Windows, do you have the same config?

**Comment by alanrenmsft** [comment]
Error in the console

![image](https://user-images.githubusercontent.com/13777222/56171488-56f4d900-5f9a-11e9-8757-6b7e8a85a997.png)

**Comment by anthonydresser** [comment]
Hmm that shouldn't be a packaged version specific error.

**Comment by anthonydresser** [comment]
I'll take a look

**Comment by anthonydresser** [comment]
looks like it was caused by 51851efda ; its not immediately obviously to me what about it causes the issue. It might be some weird cascading event.

**Comment by alanrenmsft** [comment]
Verified in today's build the chart is working as expected now.
