### ISSUE TITLE
Infinite loop causes ADS to hang

### ISSUE THREAD

**Issue by DanielSSilva** [microsoft/azuredatastudio#5042]
- Azure Data Studio Version: 
Version: 1.5.2 (system setup)
Commit: f74080c96310354bc92211f1826c0fdce78ca2f6
Date: 2019-03-22T06:25:26.627Z
VS Code 1.30.1
Electron: 2.0.12
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Running the following query (or actually any query that has an infinite loop) causes ADS to freeze, making it unresponsive, even to close. (has to be closed on task manager)

```
DECLARE @i BIGINT = 0
WHILE @i < 10
BEGIN
    PRINT 'a'
END
```
2. At the first time, I left it running because I had already pressed the stop button, but it run for 2 minutes, before I forced the termination via task manager. The process was already using 4GB of RAM
![image (3)](https://user-images.githubusercontent.com/6862119/56195840-9d474800-602d-11e9-89e8-2e8b931fff5d.png)

**Comment by anthonydresser** [comment]
Does the entire UI become unresponsive? (Clicking things does give a visual response) or does the application become functionality unresponsive?

**Comment by DanielSSilva** [comment]
It's kind of both. it becomes unresponsive, but if I for example try to double click to select text, after some time the text is selected. But even so, doing CTRL+C does not copy the content. Plus, the application become functionality unresponsive because I can't even stop the query.
Pinging @vickyharp as she was also able to reproduce it, she might have aditional info

**Comment by anthonydresser** [comment]
I have a fix for this but its a pretty large change and will require additional changes in the sqltoolsservice to completely fix. @kburtram I think we should push this to the next release to give the fix time to age before we release it.

**Comment by DanielSSilva** [comment]
Don't know if anything was done regarding this, but now when it has an infinite loop, the app becomes unresponsive for a while, before prompting a box saying that it's unresponsive and if I would like to restart the window. It seems to mitigate the issue at least

**Comment by cheenamalhotra** [comment]
Tested in latest insiders build, cancelling an infinite loop query is able to terminate Query Editor execution, it may take few seconds to finish reading results, but will eventually stop execution with below message:

```
Started executing query at Line 1
a
...
Query was canceled by user
Total execution time: 00:00:02.286
```

Closing as resolved, let us know if you have anymore concerns.
