### ISSUE TITLE
Can't see New Notebook from home dashboard

### ISSUE THREAD

**Issue by YurongHe** [Microsoft/azuredatastudio#5047]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/43652751/56234305-ddacc300-6039-11e9-91f9-9f2c4e4c95b8.png)

Azure Data Studio version: azuredatastudio 1.6.0 (c2df3e0e0ae79713c34b51fee7b6e8a531cee1f1, 2019-04-15T17:44:43.676Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (47.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-pgsql|Mic|0.1.0

</details>

**Comment by chlafreniere** [comment]
I'm unable to repro ☹️ 
<img width="546" alt="image" src="https://user-images.githubusercontent.com/40371649/56252984-54b07e80-606f-11e9-99e7-a6cd19a5cbd8.png">

**Comment by chlafreniere** [comment]
Yurong and I worked on this this morning and this no longer repros after copying the default server dashboard json into her settings file.
