### ISSUE TITLE
Restoring from hibernation occasionally puts editor into an unusable state

### ISSUE THREAD

**Issue by RMMSecurity** [microsoft/azuredatastudio#5054]
Issue Type: <b>Bug</b>

Azure Data Studio was minimized and computer (Windows 10 - 1803) was put into hibernation over the weekend. Resumed from hibernation fine and no problems elsewhere on any of the previously running programs.

I restore the window and give it focus and it appears to have some sort of rendering issue. I can view the menu bar at the top (File, Edit, View, Help) and traverse that menu, however none of the CEF/panes render as expected. 

If I hover my mouse over them I can see the cursor change as the underlying elements appear to be there. Changing the editor layouts do change the underlying elements, but it still doesn't render anything intelligible. 

![image](https://user-images.githubusercontent.com/802527/56239505-30e53c80-605f-11e9-8b0d-8f6fba19ea95.png)

![image](https://user-images.githubusercontent.com/802527/56239513-36db1d80-605f-11e9-811b-220a2335cd26.png)

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4610M CPU @ 3.00GHz (4 x 2993)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_software<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Memory (System)|15.91GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|

</details><details><summary>Extensions (23)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.0
firstresponderkit|dre|0.4.0
pastetheplan|dre|0.2.0
sqldm-performance-insights|IDE|0.4.0
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
alwayson-insights|mat|0.2.1
mssql-db-insights|mat|0.2.2
mssql-instance-insights|mat|0.2.1
admin-pack|Mic|0.0.2
agent|Mic|0.37.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.11.0
whoisactive|Mic|0.1.1
PowerShell|ms-|1.11.0
sqlops-spexecutesql-to-sql|pej|0.0.1
sql-search|Red|0.3.2
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Closing older issues.  We've made significant updates to the ADS shell since this bug.  Please let us know if you're still impacted by this issue.
