### ISSUE TITLE
Left hand pane incorrectly displays MFA connection error

### ISSUE THREAD

**Issue by fjgarciaa** [microsoft/azuredatastudio#5055]
- Azure Data Studio Version: 1.5.2
- Extensions: None enabled.

Steps to Reproduce:

1. Connect to a SQL DB (that requires active directory integrated authentication) using the built-in MFA authentication type.
2. In the database dashboard, main area, I can see all of the databases in the search panel/widget and I can run queries off of it.
3. However when I expand the databases node (on the left hand side) I receive the following error: Failed to connect to server <name of server>

**Comment by alanrenmsft** [comment]
@fjgarciaa , Thanks for reporting the issue, Do you always see this issue or just happens randomly?

**Comment by fjgarciaa** [comment]
@alanrenmsft I always see this issue.

**Comment by alanrenmsft** [comment]
@fjgarciaa , could you please share a screenshot and also do you see any error in the debug console (Help-> Toggle Developer Tools)?

**Comment by fjgarciaa** [comment]
@alanrenmsft Sure, I've added the screenshot and the error logs.
<img width="578" alt="Screen Shot 2019-04-17 at 2 41 03 PM" src="https://user-images.githubusercontent.com/13701035/56323200-f8f1fe00-611f-11e9-9ea9-eb4bf13cf7d5.png">
[mylogs.log](https://github.com/Microsoft/azuredatastudio/files/3091690/mylogs.log)

**Comment by Charles-Gagnon** [comment]
Are you still seeing this with the latest ADS update (1.8.0)? If you are - are you able to connect successfully using other tools such as SSMS or Visual Studio?

**Comment by fjgarciaa** [comment]
@Charles-Gagnon Just tried it now, and it looks like everything is working as expected on v1.8.0.  I'll circle back if it repros again.  Thanks for the follow-up.

**Comment by Charles-Gagnon** [comment]
Good to hear! We've seen a lot of intermittent issues with MFA so if you do run into this again definitely let us know and we'll see what we can do to address it.
