### ISSUE TITLE
Import Wizard: Refresh when at Bottom of Results for Preview Data Shows Empty Grid

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5070]
Go through the import wizard (choose a file, etc). On the Preview Data page, wait for data to be displayed.

Scroll to the bottom of the grid.

Click refresh.

Grid will appear empty until you scroll back up:

<img width="739" alt="image" src="https://user-images.githubusercontent.com/40371649/56255398-921a0980-6079-11e9-8684-7d6d10208d0f.png">

**Comment by alanrenmsft** [comment]
@yualan not a regression, and also not a block issue, please triage.

**Comment by aasimkhan30** [comment]
Cannot reproduce this error. Closing the issue for now.
