### ISSUE TITLE
Restore Wizard Needs Horizontal Scrollbar when Resizing Columns

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5071]
Try to resize the columns in the Restore plan to be very large, like so, and notice that no scrollbar appears, so data from every other column is inaccessible:

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/40371649/56255562-3b60ff80-607a-11e9-9356-85449bf1aa11.png">

**Comment by alanrenmsft** [comment]
@yualan I believe this has always been like this, please triage.

**Comment by udeeshagautam** [comment]
@chlafreniere looks like this is fixed in latest bits... Can you please let me know if you still see this issue?
![image](https://user-images.githubusercontent.com/46980425/58728182-39899c00-839b-11e9-863b-a0dd458bad5c.png)

**Comment by udeeshagautam** [comment]
Please reactivate if you still see this
