### ISSUE TITLE
Titled notebook should respect "Auto Save" option in File menu

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5081]
Issue Type: <b>Bug</b>

Query editor will auto save the changes when "Auto Save" in File menu is checked.

So notebook should align with query editor.

Azure Data Studio version: azuredatastudio 1.6.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.93GB (137.80GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.12.1

</details>

**Comment by kevcunnane** [comment]
Fit & Finish for June

**Comment by YurongHe** [comment]
File opened from folder is auto saved.

**Comment by YurongHe** [comment]
Not reproed anymore.
