### ISSUE TITLE
Azure Explorer doesn't remember server credentials

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5082]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Sign-in to an Azure Subscription
2. Expand a server and fill out password and click remember password

Expected: Password is remembered

Actual: Password is not remembered

> Note: Please also address other related credentials issues such as if I have a saved server with a password to the same Azure server then don't prompt for password again when accessing in Azure Explorer, etc.

**Comment by anthonydresser** [comment]
fixed by #5564
