### ISSUE TITLE
Should untitled editor file name index also check opened editor

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5083]
Issue Type: <b>Bug</b>

![image](https://user-images.githubusercontent.com/43652751/56311525-15337200-6103-11e9-910a-9209d04f12e8.png)

If user saves untitled sql/notebook file as default for example: SqlQuery_1/Notebook-0
Then the file name has the extension in the tab. If create untitled Sql/notebook file, it will has the same file name. Check the above screenshot.

Problem: 
      It is a little bit confusing with two files with exact same name opened. Also could cause overwritten the saved file if user doesn't rename it.

When we check the file name, could we also check opened editor to find the index?

Azure Data Studio version: azuredatastudio 1.6.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2695 v2 @ 2.40GHz (48 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|255.93GB (137.94GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.12.1

</details>

**Comment by alanrenmsft** [comment]
I don't think it is feasible to check the open files when determining the name of new unsaved files, and i don't overwrite would happen. to me this is not an actual issue. @yualan  please triage.
