### ISSUE TITLE
Notebook: error if select connection and cancel

### ISSUE THREAD

**Issue by kevcunnane** [Microsoft/azuredatastudio#5088]
Open ADS and open a notebook
Click select connection and open the connection dialog.
Click cancel

Expected:
- Cleanly cancels out
Actual:
- Get error `Changing context failed: No valid connection`
- Get extra `Select connection` in the dropdown.

![image](https://user-images.githubusercontent.com/10819925/56322174-30ab7680-611d-11e9-9fb3-bea5b026304d.png)
![image](https://user-images.githubusercontent.com/10819925/56322184-3608c100-611d-11e9-97fe-008ec6c851d8.png)

**Comment by chlafreniere** [comment]
This has been fixed in master already.

**Comment by alanrenmsft** [comment]
close as it has been fixed.
