### ISSUE TITLE
Saved SQL Files Often Corrupt

### ISSUE THREAD

**Issue by WillTheDev** [Microsoft/azuredatastudio#5102]
Issue Type: <b>Bug</b>

When I create a a query and save it to disk as a .sql file, many times it will be saved as binary and when I try to open it, Azure Data Studio will tell me the file is corrupt.  It can not be opened with any other program either.

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 6.3.9600

<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.7.0

</details>

**Comment by kburtram** [comment]
@WillTheDev I haven't seen this issue before.  Are there any additional repro steps that may help narrow down what's happening?

**Comment by kburtram** [comment]
Closing since we don't have a repro for this.  Please let me know if you have additional repro details since this sounds like a high-impact issue that we need to fix.
