### ISSUE TITLE
Model View Dialog: Blank items included when using editable Dropdown

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#5110]
When using a Dropdown component with **editable**=true, some extra blank items get included in the dropdown even though they aren't in the dropdown's **values** array. In the following screenshot the only items in **values** are "dbo" and "guest", but a scrollable blank section also exists.

![image](https://user-images.githubusercontent.com/12820011/56385348-aeca5480-61d3-11e9-8d66-67c9d5dea0df.png)

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if this issue is still impacting a user-facing product scenario.  Thanks!
