### ISSUE TITLE
Where are keyboard bindings listed?

### ISSUE THREAD

**Issue by edag94** [microsoft/azuredatastudio#5122]
Issue Type: <b>Feature Request</b>

It would be nice to see the shortcuts next to the buttons in the toolbar menu dropdowns

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment]
@edag94 you can see all the available shortcuts from the `Preferences -> Keyboard Shortcuts` page.  If you provide filter text, such as `query`, you can see the available commands for a particular area.  I agree that there might be a better UX to surface these directly in the UI.

**Comment by kburtram** [comment]
Closing based on previous comment.  Thanks!
