### ISSUE TITLE
Color Theme - Dark Azure Data Studio (default dark) Bug

### ISSUE THREAD

**Issue by JASM2007** [Microsoft/azuredatastudio#5124]
I have just updated to the latest version of Asure Data Studio and it introduced a new bug.  While using Color Theme - Dark Azure Data Studio (default dark) theme and trying to connect to a database it's all black text when it use to be white text.  See the image below.

![image](https://user-images.githubusercontent.com/40634806/56428970-4b9df800-628f-11e9-8333-f835533faac7.png)

- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/40634806/56429174-fd3d2900-628f-11e9-9ae4-567ff5892586.png)

Steps to Reproduce:

1. Change Color Theme to Dark Azure Data Studio (default dark)
2. Connect to a database
3. Click Database Drop down
4. See black text.

**Comment by JASM2007** [comment]
It is covered by issue #4741 can you merge this one with that issue?

**Comment by kburtram** [comment]
@JASM2007 thanks for opening.  We'll track in #4741.
