### ISSUE TITLE
Database names do not sort alphabetically.

### ISSUE THREAD

**Issue by KevinLeeBuchan** [microsoft/azuredatastudio#5128]
Issue Type: <b>Bug</b>

I have some databases that, for silly reasons, start with lowercase letters.
I feel strongly that it makes the most sense for these to be sorted with their capitalized bretheren that start with the same letter

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3392)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|11.89GB (4.51GB free)|
|Process Argv||
|Screen Reader|no|
|VM|40%|

</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.7.0

</details>

**Comment by shueybubbles** [comment]
Should database names sort in the same order that "select [name] from sys.databases order by name asc" returns them? The server may have a different sort order than any given user's client.

**Comment by kburtram** [comment]
@shueybubbles the query you provided sorts the databases as @KevinLeeBuchan describes on my test machine (see below).  Though as you mention this could be different based on server settings.  I think using server sort order makes sense, but it may be a little confusing if the UI controls appear to behave differently and users don't understand why.


```SQL
-- example output from my machine
select [name] from sys.databases order by name asc;

name
----------------------------------------
AdventureWorks2014
AdventureWorks2014-2
AdventureWorks2014-3
AdventureWorks2016
AdventureworksDW2016
Issue2994
master
model
msdb
PerfDb
tempdb
WideWorldImporters
WideWorldImportersDW
```

**Comment by shueybubbles** [comment]
@KevinLeeBuchan what collation is your server using? a typical "CS_AS" collation will sort both "abcd" and "Abcd" before "aCbd", not put the lower case a entries before the upper case one. eg my server has Latin1_General_CS_AS collation:

![image](https://user-images.githubusercontent.com/2224906/56977629-9a774780-6b43-11e9-9654-83efa0151608.png)

**Comment by KevinLeeBuchan** [comment]
SQL_Latin1_General_CP1_*CI_AS*

It's a Case Insensitive collation.

If I perform the following query, the names come back alphabetical,
regardless of letter case... I'm hoping this is a valid test.
SELECT ID, Name
FROM (VALUES (1, 'Insight'), (2, 'Imagine'), (3, 'iNterpret'), (4,
'Intern')) as V(ID, Name)
ORDER BY Name

I confess, I only know English, so I don't know, for example, whether "n"
or "ñ" comes first, or if they should be treated the same.
______________________________
Kevin Buchan

**Comment by shueybubbles** [comment]
On my server with that same CI_AS collation, ADS sorts the list alphabetically, mixing in different capitalization. @KevinLeeBuchan  can you share a screenshot of the symptoms you see? Or are you asking for a different behavior than what my screenshot is showing?
![image](https://user-images.githubusercontent.com/2224906/57090715-6f246200-6cd5-11e9-9cd5-fdb1eb00c270.png)

**Comment by KevinLeeBuchan** [comment]
Here's an example, below.  You can see that the one with the lowercase "i"
comes sorted in the "M"s, it seems.  Or something like that.
[image: DatabaseSorting.jpg]
______________________________
Kevin Buchan

**Comment by shueybubbles** [comment]
your image didn't come through

**Comment by philosophicles** [comment]
I have a server with the same collation as @KevinLeeBuchan , `SQL_Latin1_General_CP1_CI_AS`. 

Here you can see that databases starting with lowercase letters (`i`) are sorted after all the uppercase letters (`W`):

![DB sort order](https://user-images.githubusercontent.com/5232616/68412882-f4377a80-0141-11ea-9272-ea5a964a3a57.png)

**ADS version info:**
> Version: 1.13.0 (user setup)
> Commit: cacd481bff25c890e4130aee392569bae43b7e60
> Date: 2019-11-02T00:40:05.147Z
> VS Code: 1.38.0
> Electron: 4.2.10
> Chrome: 69.0.3497.128
> Node.js: 10.11.0
> V8: 6.9.427.31-electron.0
> OS: Windows_NT x64 10.0.18362

**Comment by cheenamalhotra** [comment]
I don't see that issue anymore in latest ADS versions with `SQL_Latin1_General_CP1_CI_AS` collation, closing as resolved.
