### ISSUE TITLE
Copy Feature From Notebook Results

### ISSUE THREAD

**Issue by ypradeep23** [microsoft/azuredatastudio#5137]
Issue Type: <b>Feature Request</b>

SQL Notebook is really nice feature. But what it is lacking is Copy/export capability of Query Results targetting... Copy as Table, Export to Excel. This will increase the usage of Notebooks

Azure Data Studio version: azuredatastudio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:25:26.627Z)
OS version: Windows_NT x64 10.0.17763

**Comment by SQLvariant** [comment]
In addition to the copy options already listed, I'd really like to see the ability to copy individual & multiple cells from its results, to be added.  This should be identical to the behavior of query results in ADS & SSMS.

**Comment by chlafreniere** [comment]
Closed by the PRs above.
