### ISSUE TITLE
McAfee WebAdvisor  scanning bar appeared in ADS 

### ISSUE THREAD

**Issue by MohamedSahbi** [Microsoft/azuredatastudio#5138]
I downloaded the update extension of SQL Server 2019 (Preview) 0.12.1 using Google Chrome. The start point was Azure Data Studio - Marketplace). When it finished downloading the extension, the McAfee safety advisor bar appeared in Azure Data Studio as seen in the following picture.

<img width="949" alt="adsMcAfee" src="https://user-images.githubusercontent.com/25180044/56505509-2bcf3400-651c-11e9-9fde-8fdd4aa12bd1.PNG">

- Azure Data Studio Version:
Version: 1.6.0 (system setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. Install McAfee web advisor
2. Click on update extension from the marketplace (in my case it is SQL Server 2019 (Preview) )
3. Download it, the safety advisor bar should appear in Azure Data Studio when it is downloaded.

**Comment by kburtram** [comment]
I'm not sure there is anything we can do on our side to resolve this.  I think the bug should be logged against McAfee, unless I'm missing something.
