### ISSUE TITLE
Schema Compare Suggestions

### ISSUE THREAD

**Issue by joshbooker** [microsoft/azuredatastudio#5140]
Love the work by @kisantia on [Schema Compare Extension](https://github.com/Microsoft/azuredatastudio/pull/4974).  Bravo!

A couple requests:

**Ability to exclude Diffs from script/[publish](https://github.com/Microsoft/azuredatastudio/pull/5127)**:  Like in SSDT, ability to include\exclude items in the diff list with like a checkbox which will exclude them from the resulting script or publish action if not checked.

**Default Script File Path:** Save script file dialog should default to the root path opened in the file explorer.  Chosen path should be saved in config settings somewhere upon first save and persist upon subsequent saves.

**[SqlCmd mode](https://github.com/Microsoft/azuredatastudio/issues/2752)**: if we want to use the resulting script instead of Apply, we need to be able to execute an open file in sqlcmd mode.

Keep up the great work!

**Comment by okonon** [comment]
I would echo OP!! keep up the good work! and also like suggested improvements.
