### ISSUE TITLE
QueryEditor is rehydrated as Notebook-1 title

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5144]
Issue Type: <b>Bug</b>

Saw this twice. But don't know the exact repro:

![image](https://user-images.githubusercontent.com/43652751/56536904-12c28500-6514-11e9-8dec-2294a090a32f.png)

Even though closed the file, the same file is still rehydrated after close and reopen ADS.

Azure Data Studio version: azuredatastudio 1.6.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (47.33GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
I've seen this too.  We need to make sure the Notebook restore logic isn't hijacking the SQL Editor code path in some cases.

**Comment by YurongHe** [comment]
Similar issue: [#4749](url)

**Comment by YurongHe** [comment]
I have tried and can't find the repro so far. Will continue to try it.

**Comment by kburtram** [comment]
I've only seen this happen the one time when I opened #4749.  I'll let you know if I see again.
