### ISSUE TITLE
PowerShell extension in the ADS Marketplace is two versions behind

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#5150]
Issue Type: <b>Bug</b>

The PowerShell extension available in the ADS Marketplace is two versions behind what's currently available.  Please update extension in the Marketplace so we can work with the latest fixes.

Azure Data Studio version: azuredatastudio 1.6.0-insider (32374f264f95ee5a79166dffb1c8ac2848183b5a, 2019-04-23T07:33:12.242Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.50GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0
vscode-kubernetes-tools|ms-|0.1.18
PowerShell|ms-|1.11.0
vscode-docker|Pet|0.5.2
vscode-yaml|red|0.3.0

</details>

**Comment by kburtram** [comment]
@SQLvariant should this issue be opened against the Powershell extension repo?  Typically the extension owner should push updates to the ADS marketplace by opening PR to update the extensionGallery JSON.

**Comment by SteveL-MSFT** [comment]
I created https://github.com/PowerShell/vscode-powershell/issues/1921

**Comment by TylerLeonhardt** [comment]
@kburtram can you let us know what it takes to do this?

**Comment by kburtram** [comment]
@TylerLeonhardt please update the extension metadata against the `release/extensions` branch and submit a PR.  I'll merge the PR and copy the extension to BLOB storage.  Please assume the VSIX upload location will follow the same pattern already used in the file (i.e., just bump the version and assume rest is the same).  Thanks!

**Comment by SQLvariant** [comment]
Just dropping this link here to connect-the-dots and make sure I can find it again later: https://github.com/Microsoft/azuredatastudio/pull/5247

**Comment by kburtram** [comment]
Current `1.12.1` is published to the marketplace.  So I'll close this now.
