### ISSUE TITLE
Chart functionality is slow and has no progress indication

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#5151]
- Azure Data Studio Version:
Version: 1.6.0
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. run the following query against a local server:
select * from sys.all_objects o1 
go

2. Now hit the chart button.

Actual: For a while nothing happens and then a chart view appears. Meanwhile azure data studio appears unresponsive.
Expected:
Either chart functionality should be returning immediately or there should be a hover glass to indicate progress. Ideally ads should remain responsive so new work can be done in a new tab while chart is being built out.

**Comment by kburtram** [comment]
Closing older issues.  We're tracking this through some of the other related issues.
