### ISSUE TITLE
Saving a script resets connection and collapes results window

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#5155]
- Azure Data Studio Version: 1.6.0

Steps to Reproduce:

1. Make a connection to a server.
2. Write a query like SELECT 1
3. Run the query
4. Save the query as query.sql
5. Connection is lost and results pane collapses

**Expected Result:**
Results pane stays in place and connection is maintained instead of lost. This is request for PowerUser scenario since saving scripts is a common action.

**Comment by Chewieez** [comment]
I am experiencing this same behavior with the current build:  ver 1.13.0

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/1876.  Thanks for reporting this issue!
