### ISSUE TITLE
Support Database Tuning Advisor (DTA) scenarios

### ISSUE THREAD

**Issue by sneevand** [microsoft/azuredatastudio#516]
- SQL Operations Studio Version:

Feature:

Any plans to include execution plan and database tuning advisor as part of the tool.

**Comment by kburtram** [comment]
@sneevand the `Explain` button in the query editor will show the estimated execution plan and the `Run Current Query with Actual Plan` command can be used to get the actual execution plan.  We will add a button for actual plan in a upcoming build.

We don't currently have DTA support on the near-term roadmap, but will capture this suggestion and prioritize based on user interest.

**Comment by sneevand** [comment]
Thank that works.

**Comment by kburtram** [comment]
Great, I'll rename to track DTA ask.  Show Plan work is being tracked in other issues.
