### ISSUE TITLE
Execution failed due to an unexpected error {1}

### ISSUE THREAD

**Issue by Codered315** [microsoft/azuredatastudio#5171]
Issue Type: <b>Bug</b>

Connected to a MSSQL LocalDb and when running a batch of create procedures commands this is the only error given and nothing is executed, but highlighting and querying individually works

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.85GB (3.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

**Comment by Codered315** [comment]
Figured out bug, mistake on my part but Azure Query Editor does not notify a user if say a multi-line comment does not get closed 
Example)
/*Comment*/
/*Another comment*
/*Another comment*/

SQL Code with no errors

End Example

No red wavy lines are shown for the improperly closes multi-line comment but SQL Code is still highlighted correctly. And when you run the entire file as a query it gives "Execution failed due to an unexpected error {1}"

Let me know if further info is needed

**Comment by kburtram** [comment]
Thanks for providing more details on the bug and the resolution.  We have a couple other bugs tracking incorrect nested comment handling, such as https://github.com/microsoft/azuredatastudio/issues/848.  We'll consider this particular repro when looking at those issues.
