### ISSUE TITLE
Servers connection nodes don't expand consistently

### ISSUE THREAD

**Issue by andrewjboyd** [microsoft/azuredatastudio#5174]
Issue Type: <b>Bug</b>

I have a local server connection setup (I use . and AD to connect), I click the server to expand it and it sits there only showing the busy indicator

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz (4 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.89GB (0.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@andrewjboyd are there any error messages in the "Help->Developer Tools" Console log?

**Comment by andrewjboyd** [comment]
So I have these two warnings
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [createInstance] First service dependency of AccountManagementService at position 2 conflicts with 0 static arguments
console.(anonymous function) @ C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280
C:\Program Files\Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js:2280 [createInstance] First service dependency of ConnectionManagementService at position 3 conflicts with 0 static arguments

I'm not sure if it helps, but I'm running node 11.12.0

**Comment by andrewjboyd** [comment]
And for some reason, it has started working again???

**Comment by kburtram** [comment]
@andrewjboyd thanks for the updates.  We're planning to investigate this category of problems and try to improve general connectivity issues in the Servers view in a future iteration.

**Comment by kburtram** [comment]
We made significant improvements to the reliability of this scenario.  Please let us know if you're still seeing this issue.
