### ISSUE TITLE
Azure Data Studio Icon tiny on 4K display with multi-monitor/DPI setup

### ISSUE THREAD

**Issue by vobrechkov** [Microsoft/azuredatastudio#5176]
Issue Type: <b>Bug</b>

When using mutliple DPI displays, the Azure Data Studio Icon is tiny in the taskbar on the 4K display (renders fine on 1080p display set as primary).

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|15.85GB (6.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@vobrechkov could you please attach a screenshot of what you're seeing?  I have a high-DPI monitor and the icons appears to scale as expected for me.  Thanks!
