### ISSUE TITLE
OSX Mojave dark theme results in ADS initial run starting in dark theme before flashing over to default light

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#5181]
- Azure Data Studio Version: 1-7-0-insider
- System OS: MacOS 10.4.4 Mojave

Steps to Reproduce:

1. If ADS is installed, completely uninstall
2. Change system theme (Mojave) to Dark
3. Open ADS
4. Observe the flash as ADS starts in dark theme but then switches over to light

Intended behavior:
Similar to VS Code, the default application theme should show without interference from the system OS theme.

[Link to screen recording](https://microsoft-my.sharepoint-df.com/:v:/p/andrewn/EeX5LIlosWVBihaqp8XWcQgBE3DMT2cR-RmoVwyMjE2ENQ?e=6Vq4x3) (Internal MSFT access only):

**Comment by kburtram** [comment]
Closing older issues.  I haven't observed this behavior on recent builds.  Please let us know if this issue is still impacting your scenario.
