### ISSUE TITLE
Application toolbar theme is incorrectly tied to OSX system theme 

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#5182]
- Azure Data Studio Version: 1-7-0-insider
- System: MacOS 10.4.4 Mojave
- System theme: Dark theme

Steps to Reproduce:

1. In Mojave settings, change appearance to dark theme
2. Open ADS and change app theme to default light
3. Notice how the application toolbar remains dark

Intended behavior:
Similar to VS Code, the application toolbar is themed from the app theme, and will not change depending on the system theme
<img width="1136" alt="Screen Shot 2019-04-24 at 11 56 24 AM" src="https://user-images.githubusercontent.com/29785331/56685985-ffd0c180-6687-11e9-8a2d-c3165389c570.png">

**Comment by angdesign** [comment]
Example of VSCode application toolbar respecting app theme 
<img width="1449" alt="Screen Shot 2019-04-24 at 11 58 34 AM" src="https://user-images.githubusercontent.com/29785331/56686191-56d69680-6688-11e9-9f6b-e4f4abcf53c0.png">

**Comment by kburtram** [comment]
I think is because we currently have custom titlebar rendering disabled.

**Comment by Box-Of-Hats** [comment]
This appears to have been fixed in the June 2019 update

**Comment by Charles-Gagnon** [comment]
Closing since this has been fixed, let us know if you see any further issues with this.
