### ISSUE TITLE
Notebooks: Low contrast ratio for colored text in light theme

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#5186]
- Azure Data Studio Version: 1.7.0-insider
- System: MacOS 10.14.4

Steps to Reproduce:
1. Open a notebook with ADS in default light theme
2. Run a code cell that results in a warning or error (red text and/or yellow text) 
3. Notice the low contrast and legibility against the light background

Switching the app theme to dark results in greater contrast. Seems as though the text color is not changing properly to account for the different themes. 
![Screen Shot 2019-04-24 at 2 14 45 PM](https://user-images.githubusercontent.com/29785331/56695838-e2f3b880-669e-11e9-9fef-bd8b62a67f3a.png)
![Screen Shot 2019-04-24 at 2 14 37 PM](https://user-images.githubusercontent.com/29785331/56695839-e38c4f00-669e-11e9-9396-dcec66540eb4.png)

**Comment by kburtram** [comment]
Closing out older issues.  The current Notebook UI has went through contrast ratio testing and has addressed all the bugs reported in that process.  Thanks!
