### ISSUE TITLE
Double OE entries

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#5190]
Issue Type: <b>Bug</b>

I don't have a repro, but I saw a doubled up OE tree for one of my instances:

![image](https://user-images.githubusercontent.com/8250560/56698096-ac6d6c00-66a5-11e9-9bc1-6183543ca98e.png)

All of the tree branches properly expanded:
![image](https://user-images.githubusercontent.com/8250560/56698124-babb8800-66a5-11e9-8e77-88d4cd588ffb.png)

I noticed as well that the connection was listed twice and would not expand, so presumably it was expanding into the first entry of the instance
![image](https://user-images.githubusercontent.com/8250560/56698177-e50d4580-66a5-11e9-8cad-68105c1659d1.png)

I deleted the connection and both disappeared.

One thing I've been testing a lot is connecting to this particular server in SSMS and opening Azure Data Studio from that OE.

Azure Data Studio version: azuredatastudio 1.7.0-insider (e8220919073c965d2e0eefb0359c132b61e1eca9, 2019-04-24T07:39:12.819Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
schema-compare|Mic|0.1.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still experiencing this problem.  I haven't seen recent repro reports.  Thanks!
