### ISSUE TITLE
Connection Provider should indicate whether a connection profile is server connection

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5193]
In \src\sql\platform\connection\common\utils.ts, we have hard coded the way to determine whether the connection is a server connection or database connection, this should be supplied by the connection provider as a property of the connection profile.

impact: when opening the dashboard for server node of new connection providers, we will always show the database dashboard instead of the server dashboard.

**Comment by kburtram** [comment]
Closing out older engineering-focused issues.  Please reactivate if there is any customer-facing impact for this issue.
