### ISSUE TITLE
Infinite loading when connecting to a server on server group

### ISSUE THREAD

**Issue by LucasWBritz** [microsoft/azuredatastudio#5195]
- Azure Data Studio Version:
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. This is something that happens sometimes (I don't know exactly how to reproduce this because sometimes works and others don't). 
I've just created a server group and added a connection to a localhost\SQLEXPRESS server. 

After closing and opening Azure Data Studio then double clicking on the connection, the connection keeps 'loading' forever. I think it can just be a bug on the UI (that keeps the loading animation there) because if I open a query window I'm able to execute queries as usual on this connection.
![Infinity loading](https://user-images.githubusercontent.com/24421665/56701133-8e5a3880-66b2-11e9-8478-d3d2989ee67b.PNG)

**Comment by abist** [comment]
@LucasWBritz Could you copy-paste the logs on the Console (`Ctrl` + `Shift` + `I`) here when you hit this issue? I'm not being able to repro this issue.

**Comment by kburtram** [comment]
We're looking at a related bug in issue https://github.com/microsoft/azuredatastudio/issues/6128.  I'll close this as duplicate to consolidate issues.  We'll verify the Server Group scenario while fixing https://github.com/microsoft/azuredatastudio/issues/6128.
