### ISSUE TITLE
Dark theme isn't working for HDFS icon

### ISSUE THREAD

**Issue by stuartpa** [microsoft/azuredatastudio#5196]
Issue Type: <b>Bug</b>

The dark theme for the HDFS icon doesn't seem to be working.  The icon is black on dark!

(Kevin asked me to enter this!)

Azure Data Studio version: azuredatastudio 1.6.0-insider (5119d28b9d07040062be0146b7e294b65faf6955, 2019-04-18T19:51:40.486Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (4.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.12.0

</details>

**Comment by kevcunnane** [comment]
Now uses folder so not needed
