### ISSUE TITLE
Settings page fit and finish

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#5213]
Issue Type: <b>Bug</b>

I believe this is an ADS issue and not a VS Code issue.

1. Open VS Code and ADS
2. Set the theme for each to the default dark theme.
3. Go to settings in ADS and go to settings in VS Code.
4. Reduce the text size in each using Command - (on mac)
5. Note that  fields and dropdowns have lost their edges in ADS but not VS Code.
(Also note that the controls are different as well.)

VS Code is on the left.
ADS is on the right.

![image](https://user-images.githubusercontent.com/41927913/56771824-a8585180-676c-11e9-9889-954f900d8d95.png)

Azure Data Studio version: Azure Data Studio 1.7.0-insider (34457880c77068d787021329d2d55cea94aabe74, 2019-04-25T07:14:36.294Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|8.00GB (0.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0

</details>

**Comment by kburtram** [comment]
The Settings UI is coming from upstream.  We should have the UX once the code bases get synced to the same points.  Thanks for reporting.
