### ISSUE TITLE
OSX notebook editors not expanding, single line only

### ISSUE THREAD

**Issue by rondunn** [microsoft/azuredatastudio#5217]
Refer to attached screen shot. 

Notebook editors for Text and SQL are showing as a single, scrolling line on OSX. On Windows the editor expands with each line.

![notebook](https://user-images.githubusercontent.com/39228424/56775474-785f8b80-680a-11e9-9820-c155855ff8ce.jpg)

**Comment by kevcunnane** [comment]
Hi Ron, we've tried to repro this a number of times with no luck. Most of us develop on Mac but haven't seen this at all. Can we ask:
- What version of MacOS are you using?
- Do you have any customized settings that may cause this?
- Is this happening on the latest version of the code?

Thanks in advance, Kevin.

**Comment by rondunn** [comment]
I'm using OSX  10.13.6 and Azure Data Studio 1.7.0, both of which I believe to be current.

The only customisation to my environment is Consolas font, and 24 point font size.

**Comment by kevcunnane** [comment]
We've identified issues if using non-default font size, let's at least fix that part.

**Comment by chlafreniere** [comment]
This issue should now be fixed.
