### ISSUE TITLE
Icon not being used for title bar on Windows

### ISSUE THREAD

**Issue by KamasamaK** [microsoft/azuredatastudio#5220]
- Azure Data Studio Version: 1.6.0 (user setup)
- OS: Windows 10 Build 17763

See image below showing my title bar.

![ADS 2019-04-25 202031](https://user-images.githubusercontent.com/22951521/56775976-ace62f80-6797-11e9-9594-47ed3eeb028f.png)

**Comment by kburtram** [comment]
I've seen this a couple times, but only in dev environments so far.  I am not sure why sometimes Windows uses the default EXE icon.  Unfortunately application title bar icons are cached by Windows and can only be refreshed by clearing the Windows icon cache (e.g. https://www.thewindowsclub.com/rebuild-icon-clear-thumbnail-cache-windows-10).

**Comment by KamasamaK** [comment]
I followed the instructions on that page to rebuild icon cache in Windows 10, but it did not fix my issue.

**Comment by KamasamaK** [comment]
Updating to v1.8.0 seems to have fixed this.
