### ISSUE TITLE
[sqlbdc]-[ads]-[Notebook]- Need pre-check validation while loading notebook to verify pre-reqs are installed

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#5234]
- Azure Data Studio Version:
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.14393
Steps to Reproduce:

Name: SQL Server 2019 (Preview)
Id: microsoft.sql-vnext
Description: Support for SQL Server 2019 features, including Create External Data wizards.
Version: 0.12.1
Publisher: Microsoft

I hope the scenario will be common for customer who would upgrade from 1 version to the other and we cannot always make sure They will close ADS post-closing the notebook. So it would be good to add a check while opening notebook by default when the ADS gets launched to verify if all the required pre-reqs are in place and then raise error indicating the pre-reqs.

1.	I have a ADS installed , SQL 2019 Preview enabled , BDC Extension enabled – Life is happy and nice.
2.	I have opened a Notebook and I did some deployments and BDC administration – Things are fine so far.
3.	I go-ahead and close the ADS without closing the notebook.
a.	Note: The default behaviour of ADS is such that it will open the last opened file again when ADS gets launched.
4.	Now I go-ahead and un-install ADS completely on the box, It looks like all the binary and other folder gets cleaned but for some reason the last opened file activity doesn’t get erased.
5.	I freshly install ADS and then launch  ADS and when it opens for the first time it opens back the last opened notebook – This looks like the triggering point.
6.	Since it cannot load any notebook related kernels as the extension is not loaded and SQL Server 2019 preview is not enabled, The kernel loads seems to hang for ever.
7.	Even if I close the notebook , it looks like based on what @Karl Burtram explained it probably doesn’t release the lock on the extension directory?
8.	Then all other issues are seen.

I did not understand why the display text is “Please start VS Code before installing..” instead shouldn’t it be “Please start ADS”?
When I click on the Reload Window it seems as though nothing happens, I have now add the extension file again and then enable SQL Server 2019 Preview again and then 
One more restart of ADS , Things are back to normal.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
