### ISSUE TITLE
Tasks panel doesn't show automatically when a task is queued

### ISSUE THREAD

**Issue by kburtram** [Microsoft/azuredatastudio#5242]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Don't have Tasks panel visible 
2. Run an operation that queues a task, such as Restore

Expected: Tasks panel is shown when a new task is queued
Actual: Tasks panel is not shown

**Comment by anthonydresser** [comment]
Should we have a different label for tasks panel? since its a different feature
