### ISSUE TITLE
Database dropdown search

### ISSUE THREAD

**Issue by sadjadbp** [Microsoft/azuredatastudio#5245]
Issue Type: <b>Bug</b>

We used to be able to type into Database selection dropdown to search for name of the DB. But now it is not possible, it just shows "must be an option from the list"

![image](https://user-images.githubusercontent.com/6307366/56855484-ac1ade00-68fc-11e9-8000-b44714b22914.png)

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz (4 x 3093)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|19.96GB (11.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by sadjadbp** [comment]
a bit related to #3775, but for me it's now completely broken, it won't auto complete or search or anything. If I start typing anything it won't work at all.

Also the dropdown in dark mode is now dark text over dark background

![image](https://user-images.githubusercontent.com/6307366/56855528-5b57b500-68fd-11e9-95aa-14b048cce6b2.png)

**Comment by sadjadbp** [comment]
okay second issues is same as #4741

**Comment by alanrenmsft** [comment]
The fix for the issue will be included in the upcoming release
