### ISSUE TITLE
Results progressively slower

### ISSUE THREAD

**Issue by nige6** [microsoft/azuredatastudio#5249]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Performance Issue</b>

one sql window, with 2 or more different sql statements
highlight one, and execute
hightlight the next, execute

repeat, and results become slower and slower to appear on screen
with the results rows being blank, and then eventually populating
and eventually to the stage where results section does not appear for several minutes but the messages section does
execution time in message does not change

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    1	   123	 17724	azuredatastudio main
    0	   470	  7996	   gpu-process
    0	    55	 17440	   shared-process
    0	   240	 21760	   window (● contributions_transfer_in.sql - ps-test-rds.DEV_puntersouthall (Integrated) - Azure Data Studio)
    0	   109	 22968	     extensionHost
    0	    20	  7868	       "c:\Users\Nigel\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.85\MicrosoftSqlToolsCredentials.exe" --log-file C:\Users\Nigel\AppData\Roaming\azuredatastudio\mssql\credentialstore_22968.log --tracing-level Critical
    0	     5	 19988	         console-window-host (Windows internal process)
    0	    21	 14228	       "c:\Users\Nigel\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.85\SqlToolsResourceProviderService.exe" --log-file C:\Users\Nigel\AppData\Roaming\azuredatastudio\mssql\resourceprovider_22968.log --tracing-level Critical
    0	     6	 15156	         console-window-host (Windows internal process)
    0	    99	 22724	       "c:\Users\Nigel\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\mssql\sqltoolsservice\Windows\1.5.0-alpha.85\MicrosoftSqlToolsServiceLayer.exe" --log-file C:\Users\Nigel\AppData\Roaming\azuredatastudio\mssql\sqltools_22968.log --tracing-level Critical
    0	     5	 21492	         console-window-host (Windows internal process)
    0	    77	 24016	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by anthonydresser** [comment]
Do you have any information on what type of queries you are running to exhibit this behaviour? I can't seem to repro using just generic select all statements.
