### ISSUE TITLE
Results window sizing issues

### ISSUE THREAD

**Issue by nige6** [Microsoft/azuredatastudio#5250]
We have written the needed data into your clipboard because it was too large to send. Please paste.

Issue Type: <b>Bug</b>

one sql window, with 2 or more different sql statements
with expected results 10 or more per query
execute them 
- results pane/window has a scroll bar but cannot scroll to the bottom/end to see the last row in the last result set

- attempting to resize results just "moves" the results and message pane not resizing them

- occasionally the width of the results pane does not adjust when side bar is on the right
not sure on cause yet, but try having server/search/task on the right and visible 
then executing query/queries
eventually gets to the position where the results do not fill the width of ADS
resizinng the ADS window also does not then resize the results width
when rerunning the query

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
Another related issue, or perhaps covered by the above, is that when resizing the results pane the bottom horizontal scrollbar can become obscured by the Messages section and no longer accessible.  We need to fix as it makes the grid very difficult to work with.

For example, in the below results grid there should be a horizontal scrollbar visible.

![image](https://user-images.githubusercontent.com/599935/56927630-84a54c00-6a89-11e9-9982-bbdc8eaf28cd.png)

**Comment by kburtram** [comment]
@nige6 I've merged a PR #5285 that fixes the first issue you mentioned, probably the second, and I don't have a repro for the third, but it possible address that too.  Please let me know if you are still having problems with the latest insiders build from master or the `1.7.0` release next week.  Thanks!
