### ISSUE TITLE
Results Pane Header Issue

### ISSUE THREAD

**Issue by JASM2007** [Microsoft/azuredatastudio#5251]
The header row will disappear from results pane view when scrolling with the arrow keys on the keyboard.

- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/40634806/56922036-4e6dc980-6a95-11e9-969f-51d1786be133.png)

Steps to Reproduce:

1. Execute a query that has more records than you can screen in the results pane without scrolling
2. Click in the Results pane.
3. Navigate down (using the down arrow key on the keyboard) past the records that are visible on screen.
4. The header row will disappear no mater how much scrolling up you do (using the up arrow key on the keyboard) or using the search bars on the right hand side. [The header row should never disappear when scrolling with arrow keys]
![image](https://user-images.githubusercontent.com/40634806/56922121-765d2d00-6a95-11e9-9584-6c604c9f2cac.png)
5. The only way to see the headers again is to click the arrow to collapse the results pane which seems to refresh that pane.

**Comment by kburtram** [comment]
@JASM2007 thanks for reporting this issue.  I've updated the result grid sizing and scrolling behavior with #5285 and it should hopefully resolve this problem.  At least I can longer repro it.  Please let me know if the issue persists on the latest insider build or the `1.7.0` release planned for next week.
