### ISSUE TITLE
Attempting "Create External table from CSV files" gives error

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#5254]
Issue Type: <b>Bug</b>

Cannot read property 'connectionId' of undefined

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.18885

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Memory (System)|31.85GB (18.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.38.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.12.1

</details>

**Comment by kburtram** [comment]
@uc-msft do you happen to have the full callstack for the exception?

**Comment by kevcunnane** [comment]
UC, I'm closing for now. Please reopen if you have a callstack or more information available that can help us resolve this, then we'll address. Thanks!
