### ISSUE TITLE
select, copy and paste from results

### ISSUE THREAD

**Issue by RutgervdStap** [microsoft/azuredatastudio#5268]
Issue Type: <b>Feature Request</b>

After running a query it would be nice to be able to copy parts of the results in a text field or anywhere. now there is no way of copy pasting this information.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.15063

**Comment by kburtram** [comment]
@RutgervdStap you should be able to select the results in the grid and copy with with `Ctrl-C` or using the right-click context menu.  Is this not working?
