### ISSUE TITLE
%load magic broken in Azure Data Studio Notebooks

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#5276]
Issue Type: <b>Bug</b>

I am trying to use the %load magic and it seems broken in our Notebooks.

![image](https://user-images.githubusercontent.com/22312581/56988943-11addb00-6b46-11e9-95a0-f429fc09d1a4.png)

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.93GB (16.74GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|dan|0.2.1
gc-excelviewer|Gra|2.1.26
newdatabase|kev|0.0.3
import|Mic|0.7.0
postgresql|Mic|0.1.0

</details>

**Comment by chlafreniere** [comment]
No repro along with needs more info label. Closing this issue.
