### ISSUE TITLE
SQL server import ext doesn't work on MacOS Mojave

### ISSUE THREAD

**Issue by snehasi** [microsoft/azuredatastudio#5292]
I am trying to import flat csv files from my local machine to the mssql server running on Docker with Azure data studio. 
It gives a command cannot start error.
- Azure Data Studio Version: 1.3.9

I've tried:
- Copying files to the Docker container and bulk copying the flat files
- Changing Access rights
- Changing field terminators in the csv file.

**Comment by teach4learning** [comment]
Connects to server, I can see Dbs, etc. Using sql import extension. Trying to  import .csv from local machine to create new table. Freezes @ the preview stage. Have to cancel to escape. No error messages.

**Comment by aasimkhan30** [comment]
Closing this issue as I cannot reproduce it.
