### ISSUE TITLE
Connection not saving

### ISSUE THREAD

**Issue by joshuaquiz** [Microsoft/azuredatastudio#5294]
Issue Type: <b>Bug</b>

If I have a connection with name "Connection A" and then later I need to update say the password or something else and want to override "Connection A", no override happens. It asks where you want to save it be then does not overwrite the existing connection.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6800K CPU @ 3.40GHz (12 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|23.91GB (4.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by abist** [comment]
This issue is being tracked by https://github.com/Microsoft/azuredatastudio/issues/5026
Closing as duplicate.
