### ISSUE TITLE
SQL Notebook - cannot select a connection created after notebook has been opened

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5298]
Issue Type: <b>Bug</b>

Open a notebook with *no* active connections in object explorer.

Create a new connection in object explorer

Click on "select connection" error message is as follows:

Changing context failed: No valid connection

also noticed. 
When I mouse-over the error in bottom right corner the pointer turns to a hand. Clicking highlights the message box but does not perfom an action. All you can do is close the window.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|63.92GB (19.22GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
sql-dw|Mic|0.0.1
sql-vnext|Mic|0.12.1

</details>

**Comment by kevcunnane** [comment]
Gene please investigate - ping JRJ if needed to get exact repro steps

**Comment by geleems** [comment]
Contacted JRJ for repro, but unable to repro in the latest ADS bits.
