### ISSUE TITLE
Can't start the app...

### ISSUE THREAD

**Issue by mattyweb** [microsoft/azuredatastudio#5305]
Issue Type: <b>Bug</b>

Opening the app gets be 3 errors...can't connect to DBs or use the app at all:
Couldn't start client SerilizationProvider
Couldn't start client AzureResourceProvider
Couldn't start client SqlToolsService

Azure Data Studio version: Azure Data Studio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:14:17.039Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz (4 x 2700)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv|-psn_0_925922|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@mattyweb those failed clients are .Net Core child-processes.  If all of them are failing it's likely there is some incompatibility with .Net Core in this execution environment.  Are there any additional error messages logged in the "Help->Developer Tools" Console output that provide further details on why the processes are working?

Also, you may want to try the latest insiders build available at https://azuredatastudio-update.azurewebsites.net/latest/darwin/insider.  That build uses a newer .Net Core SDK.

**Comment by mattyweb** [comment]
Thanks for the response. I tried the insiders build but didn't have any more success with that.

Looking at the logs, I do see one error show up in the console before those other errors pop up ("Couldn't start client SerilizationProvider" etc.):

```
/Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280 [IPC Library: File Watcher (nsfw)] Unhandled Promise Rejection:  Error: Path must be a valid path to a file or a directory.
    at /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules.asar/vscode-nsfw/lib/src/index.js:79:11
console.(anonymous function) @ /Applications/Azure Data Studio.app/Contents/Resources/app/node_modules/zone.js/dist/zone-node.js:2280
```

Then a few messages later I see:

` WARN UNRESPONSIVE extension host, 'Microsoft.notebook' took 99% of 1073.108ms, saved PROFILE here: '/var/folders/lc/c6p1360x2817swm5qf2521xw0000gn/T/exthost-d1b547.cpuprofile'`

I'm also wondering if there is some way to do a clean install of the tool. Just dragging the app bundle to the trash doesn't seem to do it. There is some configuration stored somewhere outside of the app...

**Comment by kburtram** [comment]
@mattyweb are you still seeing this problem with current builds?  Thanks!

**Comment by AbhishekKumar26** [comment]
@kburtram : I downloaded the azuredatastudio-windows-user-setup-1.30.0.exe today and getting the same issue.
@mattyweb : Is the issue resolved for you? Please share the work around if it is resolved.

**Comment by thebrightwork** [comment]
Not sure if this will help you guys but with the mention of .NET above I installed .NET 7.0 from https://dotnet.microsoft.com/en-us/download and now ADS is loading all the extensions just fine at startup. Hope it helps.
