### ISSUE TITLE
Using a webview.component in a DialogTab

### ISSUE THREAD

**Issue by mjeaton** [microsoft/azuredatastudio#5312]
**Description**:

When adding a tab to a query document, I would like to include html, but no matter what I try, my html is not rendered.

**ADS Version**:
latest Insider build - 1.7.0

**Steps to Reproduce**:
```
let tab = azdata.window.createTab("My Test Tab");
tab.registerContent(async view => {
	let webView = view.modelBuilder.webView().component();
	let xmlTextBox = view.modelBuilder.inputBox().component();

	let formModel = view.modelBuilder.formContainer()
		.withFormItems([{
			component: xmlTextBox,
			title: 'Html that should be rendered'
		}, {
			component: webView,
			title: 'Webview title'
		}]).withLayout({ width: '100%' }).component()

	await view.initializeModel(formModel);

	webView.html = `<html><head></head><body><h1>This is a test</h1></body></html>`;
	xmlTextBox.value = webView.html;
});
document.createQueryTab(tab);
```
**Expected Results**:

I expect to see a new tab created within my query document titled "My Test Tab" - this works. Inside that tab, I expect to see an H1 with This is a test displayed after the text box. 

**Actual Results**:

The text box contains the html I want to see rendered, but I don't actually see the html, only the component title "Webview title".

![ADS_CreateTab_No_Html](https://user-images.githubusercontent.com/62956/57077865-0fb95880-6cbb-11e9-9e6f-a6a7ac2ba17d.png)

**Comment by alanrenmsft** [comment]
@kburtram , need help on this one?

**Comment by kburtram** [comment]
This should be working in the latest insiders builds.  Please let me know if there are still issues here.  Here is a snippet that demonstrates usage copied from https://github.com/kburtram/azuredatastudio-snippets/blob/master/samples/queryplan/src/main.ts.

```TypeScript
let tab2 = azdata.window.createTab('Web View Watcher');
tab2.registerContent(async view => {
	let html: string = '<pre>\n';
	html += escapeAndLineBreak(<string>args);
	html += "\n</pre>";

	let webview1 = view.modelBuilder.webView()
		.withProperties<azdata.WebViewProperties>({
			html: html
		}).component();

	let divModel = view.modelBuilder.divContainer()
		.withItems([webview1], { CSSStyles: {  'height': '100%',  'width': '100%' } } )
		.withLayout({ width: '100%', height: '100%' })
		.component();

	await view.initializeModel(divModel);
});

document.createQueryTab(tab2);
```
