### ISSUE TITLE
SQL Profiler

### ISSUE THREAD

**Issue by zippy1981** [microsoft/azuredatastudio#5313]
**Is your feature request related to a problem? Please describe.**
While you can copy the query or other TEXT data from a profiler via the text info, you cannot copy other columns. The grid of events does not support copy paste. Neither does the "data" tab next to the "text tab"

**Describe the solution or feature you'd like**

For both the main grid of the profiler and the data tab:

* Let Ctrl+C copy highlighted columns to the clipboard
* Add a right click context menu with a copy option.

**Describe alternatives you've considered**

* Using the stand alone SSMS profiler.
* Writing Xevents sessions in T-SQL and querying from manually.

**Additional context**

**Comment by alanrenmsft** [comment]
thanks @zippy1981  for reporting the issue, we are tracking the copy paste issue using https://github.com/microsoft/azuredatastudio/issues/5667, i am going to close this one as a dupe.
