### ISSUE TITLE
Syncing changes through OneDrive across machines

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5316]
Issue Type: <b>Bug</b>

# Scenario:
My notebook lives on OneDrive
I have two machines - a windows workstation and a Mac Laptop.

# Repro:
1) Open notebook (NB) on Windows (Win)
2) Open NB on Mac
3) Make changes on Win but don't save
4) Make changes on Mac but don't save
5) Save on Win
6) Save on Mac

On step 6 Onedrive detects the server change and won't save the file. However, the notebook window has closed and ADS still thinks it has unresolved changes when I try to close it on Mac.  

Azure Data Studio version: Azure Data Studio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:14:17.039Z)
OS version: Darwin x64 18.5.0

**Comment by jrowlandjones** [comment]
Hey @corivera what was the reason for closing this item? Has it been addressed?

**Comment by corivera** [comment]
We have a general deficiency in handling external file changes in open notebooks, so this was closed as an informal duplicate.

**Comment by corivera** [comment]
Another example of this, for reference: https://github.com/microsoft/azuredatastudio/issues/8522
