### ISSUE TITLE
Doesn't work on Ubuntu 19.04

### ISSUE THREAD

**Issue by ststeiger** [Microsoft/azuredatastudio#5317]
I'm running SQL-Server 2017 on my Ubuntu 19.04 machine  (kubuntu/KDE Plasma). 

Because 19.04 uses OpenSSL 1.1, I have to run sql-server [in a docker container](https://jojozhuang.github.io/tutorial/docker/installing-microsoft-sql-server-in-docker/).  

So I set it up with 
```
docker pull microsoft/mssql-server-linux
docker run -e 'ACCEPT_EULA=Y' -e 'TOP_SECRET' -p 1433:1433 --name mssql -d microsoft/mssql-server-linux
```
But I cannot connect to it with AzureDataStudio ! 

I download AzureDataStudio, `dpkg -i azuredatastudio-linux-1.6.0.deb` 
and then I get 
```
SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.
source: mssql (Extension)
```
I've disabled telemetry, and disabled crash reporting, and the crash persists.

However, I can connect just fine with a **.NET Core** application that runs on the same 19.04 machine. 

I see this has something to do with the OpenSSL version on Ubuntu 19.04. 
Probably the same reason why I had to install .NET Core from 
`https://github.com/dotnet/cli/blob/master/scripts/obtain/dotnet-install.sh`
Probably the SqlTools native doesn't run on Ubuntu 19.04. 
That's what you get when you don't statically link openssl and curl (sigh). 

I see there is a 
https://github.com/Microsoft/azuredatastudio/blob/master/resources/linux/snap/snapcraft.yaml 
in the repository, but there's no snapcraft and no flatpack - package of AzureDataStudio. 

Coud you either fix this, or provide a [snap](snapcraft.io) or/xor [flatpack](https://flathub.org/) package ? 

By the way, JetBrains DataGrip works - it's ironic that your own products don't work with your own software...

```
namespace TestApplication
{
    
    class Program
    {
        
        static void Main(string[] args)
        {
            System.Data.SqlClient.SqlConnectionStringBuilder csb = new System.Data.SqlClient.SqlConnectionStringBuilder();
            
            csb.DataSource = "127.0.0.1,1401";
            csb.DataSource = "localhost,1401";
            csb.DataSource = "localhost";
            csb.InitialCatalog = "master";
            csb.UserID = "sa";
            csb.Password="TOP_SECRET";
            csb.Pooling = false;

            string cs = csb.ConnectionString;
            System.Console.WriteLine(cs);

            try
            {

                using (var cn = new System.Data.SqlClient.SqlConnection(cs))
                {
                    if(cn.State != System.Data.ConnectionState.Open)
                        cn.Open();

                    using (var cmd = cn.CreateCommand())
                    {
                        cmd.CommandText = "SELECT @@version";

                        object obj = cmd.ExecuteScalar();
                        System.Console.WriteLine(obj);
                    }



                    if(cn.State != System.Data.ConnectionState.Closed)
                        cn.Close();
                }
            }
            catch (System.Exception e)
            {
                System.Console.WriteLine("Error! ");
                System.Console.WriteLine(e.Message);
            }

            
            
            System.Console.WriteLine("Finished !");            
        }
        
    }
    
}

```

> Microsoft SQL Server 2017 (RTM-CU13) (KB4466404) - 14.0.3048.4 (X64) 
>         Nov 30 2018 12:57:58 
>         Copyright (C) 2017 Microsoft Corporation
>         Developer Edition (64-bit) on Linux (Ubuntu 16.04.5 LTS)
> Finished !
>

**Comment by byroniac** [comment]
They're working on it, and will have another release soon. In the meantime, you can try my workaround here: https://github.com/Microsoft/azuredatastudio/issues/5134#issuecomment-485890327

**Comment by kburtram** [comment]
I just tested https://azuredatastudio-update.azurewebsites.net/latest/linux-x64/insider on Ubuntu 19.04 sucessfully.  I think upgrading SQL Tools Service to the latest .Net Core SDK should have resolved this issue.

**Comment by ststeiger** [comment]
Indeed, that works. 
Thanks for the tip.
