### ISSUE TITLE
Notebooks: some markdown stdout output looks messed up

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5320]
Issue Type: <b>Bug</b>

I don't think this is a regression, but it is annoying so let's investigate!
- Open Python3 notebook
- Run `!yo azuredatastudio`
Expected: output looks like output when run in terminal (see below)
Actual: Output has lots of question mark icons.
![image](https://user-images.githubusercontent.com/10819925/57099514-72b5ea00-6cd1-11e9-9fdc-8c583f94fdbc.png)

This appeared in older stable builds so isn't related to recent changes. I suspect we need to fix font-family for stdout/stderr to match our terminal font family.

Azure Data Studio version: Azure Data Studio 1.7.0-insider (f1e21ebe9dbbbf59c922cd8c8c77583241888556, 2019-04-29T07:13:39.370Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|dan|0.2.290
azuredatastudio-postgresql|Mic|0.1.0

</details>

**Comment by hfleitas** [comment]
I have a similar issue in comparison to ssms the ads stdout in a notebook is missing info.

Ref: **GetCognitiveAPI** for sample code in [notebook](https://github.com/hfleitas/SentimentPrediction/blob/master/CognitiveAPI.ipynb)

ADS
![image](https://user-images.githubusercontent.com/4984616/58601889-c415b280-8258-11e9-9a3e-2bea2be40b4f.png)

SSMS
![image](https://user-images.githubusercontent.com/4984616/58601895-c8da6680-8258-11e9-9829-367e31456552.png)

**Comment by corivera** [comment]
Issue also happens in standalone Jupyter, so closing this one.
