### ISSUE TITLE
CMS Fit and finish

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#5323]
CMS issues - 

- [x] CMS Connection type incorrectly shows in the “New Connection” dialog
- [x] SQL Login is default auth type, but username\password are disabled
- [x] View say “No providers available” during startup then shows CMS servers.  Should say something like “Loading…” during startup
- [x] Add new registered server not adding a new node for localhost
- [x] Add contirubtion to settings for cached CMS servers
- [x] Remove refresh cms server option
- [x] Edit the cached CMS server details
- [x] Rename provider to MSSQL
- [x] Get rid of Recent and Saved Connections
- [x] https://github.com/microsoft/azuredatastudio/issues/5504
- [x] Remove AAD for registered servers
- [x] https://github.com/microsoft/azuredatastudio/issues/5412

**Comment by abist** [comment]
@anthonydresser The third one looks like a Data Explorer issue because I see this error on Azure and CMS both.

**Comment by anthonydresser** [comment]
The third one isn't really a bug, its how vscode works. It should views as no provider until a provider is actually registered by the extension.

**Comment by yualan** [comment]
CMS is coming in June release and already available in our Insider Build. Closing issue.
