### ISSUE TITLE
Refactor Connection Dialog for CMS and other custom auth types

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5326]
The CMS extension required modifying the connection dialog to support the various differences in how connections are made in CMS. The changes made were very targeted towards CMS - this needs to be reviewed and ideally done in a manner that makes it easy for other auth types to reuse the dialog and change the functionality as desired.

**Comment by kburtram** [comment]
Closing old tasks.  We're looking at the authentication UX all-up, but we'll track that using our typical workstreams rather than through a Task issue.
