### ISSUE TITLE
Upgrade to ADS 1.6 (System Install) - Installer Locks Up and Requires Manual Removal

### ISSUE THREAD

**Issue by robinwilson16** [microsoft/azuredatastudio#5348]
I have installed ADS on 6 different Windows 10 machines at work and home and on each one the upgrade to ADS 1.6 just hung after requesting admin rights to upgrade (with progress remaining at zero) and after waiting a long time I eventually used Task Manager to end the task. Further attempts with/without reboots resulted in the same issue.

To get the updated version I had to manually remove from Programs and Features and then install the new version.

It works after this but not sure if this will be an issue next time there is an update.

**Comment by kburtram** [comment]
@robinwilson16 the first thing ADS tries to do when installing is to uninstall the previous version.  I haven't seen the behavior your describing myself, but it's possible the installer is having a problem removing the previous version, perhaps if the file is locked (maybe by an orphaned process, anti-virus, etc.).  Though in that case, I don't know why uninstall would work from Add\Remove Programs control panel.

If you see this again, please check if there are any ADS processes running.  If this has happened on multiple different machines it seems like it could be related to environmental configuration or something with the repro workflow.

Are there any additional details you can provide to help get an internal repro?  (e.g. anti-virus or client security software, any particular features being used, etc.).  Thanks!

**Comment by robinwilson16** [comment]
@kburtram after noticing it on each machine I just thought it was worth mentioning it.
I exited ADS first before trying to apply the upgrade. First I received the notification at the bottom-right that there was a new version available and used that to download the update, closed any instances of ADS and then ran the installer.

The machines are all quite different although all Windows 10 (2 have latest Windows 10 Insider Build and have been installed less than a year using Windows Defender as antivirus, another 3 I installed on are the Windows 10 1810 build and the other one is the original Windows 10 LTSC from 2015). 

The only commonality between them is that I install the same Dev tools including VS 2017, VS 2019 (including pre-release versions), VS Code, SSMS 17, SSMS 18 (including pre-release versions), Office 2016 or 2019.

In each case the removal from Control Panel was normal and then the subsequent install was normal too.

**Comment by robinwilson16** [comment]
In case it is of interest the same has just happened on one PC trying to upgrade to 1.7 but then another one upgraded successfully (which had previously had the issue with 1.6).
The program has no icon on the taskbar and task manager shows it as not responding so I have to end the task, uninstall 1.6 and am then able to install 1.7

**Comment by kburtram** [comment]
@robinwilson16 thanks for the additional context.  The auto-update basically downloads the setup EXE and then launches it.  From that point on it should be the same as if you downloaded and executed directly.

The installer tries to uninstall prior to reinstall, so uninstalling explicitly from the Control Panel would cause the installer to skip that step during upgrade.  The only thing I can think of is that either azuredatastudio or one of its child processes is still running after you've exited for reason and preventing uninstall.  If you can check the process list in Task Manager next time so you see this for "azuredatastudio.exe" or "microsoftsqltoolsservicelayer.exe" or other ADS child process that would help confirm this theory.

I haven't seen other reports of a similar issues, as far as I can recall, which makes it strange that you're encountering in such diverse machine setups.  Please let me know if you're able to confirm the "locked file" explanation if you encounter again.

**Comment by robinwilson16** [comment]
Thanks @kburtram 
I have just tried to apply 1.7 on another pc that previously had the issue updating to 1.6 and it also worked successfully.
I will try what you suggested if I run into this again and let you know if I do. I will be updating on at least one more PC this week depending where I end up.

**Comment by robinwilson16** [comment]
Just to report back, I booted the other PC, opened Outlook and then ADS and it prompted for the update and I said yes and then it locked up again and I looked in Task Manager and only Outlook was running plus the installer that said it wasn't responding. I left it for at least 30 mins in the background whilst I worked in SSMS and then all of a sudden it came to life, installed the update and re-opened.
So it seems if left long enough it does eventually install.

**Comment by kburtram** [comment]
Closing out older issues.  We haven't seen recent reports of similar behavior so perhaps it was something with the builds awhile back or some conflict with something on the machines (anti-virus, etc.).  Please let us know if you are still experiencing the problem described in this bug report.
