### ISSUE TITLE
Query Editor doesn't show row or execution status in statusbar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5351]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query

Expected: Details regarding row count and execution status are in the statusbar

Actual: Query status is no longer shown in the statusbar.  This is a recent regression.

> Note below that there is now query status in the statusbar

![image](https://user-images.githubusercontent.com/599935/57164515-3655bd00-6da9-11e9-8c1b-afc6ba61b877.png)

**Comment by kburtram** [comment]
I'm now seeing "Executing query..." while the query is running.  So perhaps the issue is that the Row Count goes away after execution is done.  I'll update if I have additional context.

**Comment by Charles-Gagnon** [comment]
@kburtram - I'm not able to repro this with latest version from master. Do you have more specific repro steps and does this seem to happen on any server you connect to?

![image](https://user-images.githubusercontent.com/28519865/57173514-d7626900-6de5-11e9-93db-47ab8b51a106.png)

**Comment by kburtram** [comment]
I'll see if this is a mac-only issue

**Comment by kburtram** [comment]
Closing as no repro.
