### ISSUE TITLE
SQL Agent is broken

### ISSUE THREAD

**Issue by abist** [Microsoft/azuredatastudio#5358]
SQL Agent is now broken due to layering refactoring.

**Comment by kburtram** [comment]
@abist do you know if this is caused by https://github.com/Microsoft/azuredatastudio/commit/db387eb770c24a931da1633469b7d3da29fefdb2?

**Comment by abist** [comment]
Yes, it was caused by that. I found the issue, and I'm sending a fix in a minute.
