### ISSUE TITLE
Notebooks: Add Format Buttons to Markdown Cells

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5362]
Add a toolbar to markdown cells with the ability to help users with common markdown actions, such as bolding/italicizing text and making headers.

**Comment by AlejoSQL** [comment]
Awesome, thank you for creating the item!

**Comment by claudio-salvio** [comment]
If I understand the requirement correctly, it seems that it is already implemented in version 1.22 of ADS.
However, I do not know the exact version in which the request was resolved.

**Comment by chlafreniere** [comment]
Thanks for the follow up, @claudio-salvio! Let's close this now that we have a markdown toolbar.
