### ISSUE TITLE
Azure on Linux does not support connection to MS SQL hosted on Windows Machine

### ISSUE THREAD

**Issue by shados250** [microsoft/azuredatastudio#5367]
- Azure Data Studio Version: 1.5.2

Steps to Reproduce:

1. Have the windows instance of MS SQL hosted by windows machine. For example: ms sql 2005 sp4 on windows XP, ms sql 2008 r2 on windows vista.

2. MS SQL instance is opened by TCP/IP protocol.

3. Azure on Windows (e.g windows 10) does supports connection to MS SQL (mssql 2005, mssql 2008). It is ok.

4. (error) Azure on Linux does not support connection MS SQL (mssql 2005, mssql 2008).

Linux Distribution: Debian GNU/Linux 9.8
Linux Kernel: 4.9.0.8-amd64

**Comment by kburtram** [comment]
@shados250 Azure Data Studio only officially supports connection to SQL Server 2014+ instances.  Though I expect it to work with SQL Server 2008 R2+.  Are you hitting the same issue connecting to SQL Server 2014+ instances?
