### ISSUE TITLE
Azure Data Studio fails to start (Fedora 30)

### ISSUE THREAD

**Issue by paaland** [microsoft/azuredatastudio#5368]
Issue Type: <b>Bug</b>

Fresh install of Azure Data Studio failes to start on Fedora 30 (libXScrnSaver is installed).

It comes up, has "starting service" in the status bar, then a notifications opens with "SQL Tools Service component exited unexpectedly. Souce: mssql (Extension)".

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T06:10:28.959Z)
OS version: Linux x64 5.0.11-300.fc30.x86_64

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2339)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.52GB (5.13GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|67%|

</details>Extensions: none

This is from the Development Tools console:

```
[Extension Host] No usable version of the libssl was found
 (at CustomOutputChannel.append (/home/paaland/bin/azuredatastudio-linux-x64/resources/app/extensions/mssql/out/main.js:262:17))
/home/paaland/bin/azuredatastudio-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:2280 

[Extension Host] (node:22962) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead. (at writeOut (internal/process/warning.js:18:20))
console.(anonymous function) @ /home/paaland/bin/azuredatastudio-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:2280
/home/paaland/bin/azuredatastudio-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:2280 SQL Tools Service component exited unexpectedly. Please restart Azure Data Studio.
console.(anonymous function) @ /home/paaland/bin/azuredatastudio-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:2280
/home/paaland/bin/azuredatastudio-linux-x64/resources/app/node_modules/zone.js/dist/zone-node.js:2280 

[Extension Host] [Error - 21:06:31] Connection to server got closed. Server will not be restarted. (at CustomOutputChannel.appendLine (/home/paaland/bin/azuredatastudio-linux-x64/resources/app/extensions/mssql/out/main.js:265:17))
```

**Comment by kburtram** [comment]
@paaland could you please try the latest insider build available for download from the repo README?  The insider build contains an update that resolves a openssl dependency problem that may address this issue.

**Comment by paaland** [comment]
Yes, the insider version works.

**Comment by kburtram** [comment]
@paaland thanks for confirming.  We're planning to publish that `1.7.0` release later this week.
