### ISSUE TITLE
Restore dialog checkboxes are missing in Restore plan

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#5371]
**Azure Data Studio Version:**
Version: 1.7.0-insider (system setup)
Commit: c7f5278430b9df35fb6e160a5b1cf4c653644efc
Date: 2019-05-03T07:38:02.297Z
VS Code 1.31.1
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Steps to Reproduce:**

1. start restore dialog
2. select source
3. The bottom part of the dialog shows restore plan with available steps and a checkbox to select those. The check box is missing on latest release. This seems to be a recent regression.

Previously
![image](https://user-images.githubusercontent.com/46980425/57199383-1eaa4000-6f33-11e9-8d0d-301e8a98377a.png)

Now
![image](https://user-images.githubusercontent.com/46980425/57199386-2964d500-6f33-11e9-9cf8-d4a04b92ad57.png)

**Comment by abist** [comment]
@kburtram This doesn't seem like a trivial fix. It's an issue with packaging and might take some refactoring in restore dialog.

**Comment by kburtram** [comment]
@abist could you please explain a little more?  How is the packaging process causing the checkbox not to show?

**Comment by abist** [comment]
@kburtram This table uses a slickgrid plugin called `checkboxSelectColumn.plugin.ts`, which uses an html template to create the checkbox instead of using the `Checkbox` class, which I suspect causes it to not show in packaged builds but in dev.

**Comment by udeeshagautam** [comment]
@abist yes - you are right the issue is not visible in dev, only in insiders (that makes me worry that other feature which are using checkbox plugin like Schema Compare may face this too after coming in insiders build)

Can you please point me to the layer refactor change you are mentioning?
