### ISSUE TITLE
command 'vscode.previewHtml' not found

### ISSUE THREAD

**Issue by sapan-sha** [microsoft/azuredatastudio#5374]
Issue Type: <b>Bug</b>

Ctrl + Shift + P
SQL Search : Search in Active Connection 
"<searchText>"
It throw an popup "command 'vscode.previewHtml' not found"

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5930K CPU @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (20.19GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Vaelek** [comment]
I found this https://github.com/red-gate/foundry/issues/23

**Comment by rubengmurray** [comment]
VSCode deprecated use of the previewHtml command. https://github.com/microsoft/vscode/issues/62630

**Comment by Charles-Gagnon** [comment]
I'm closing this since this looked to be an issue with the extension (and has since been resolved). Let us know if you're seeing this issue elsewhere with the latest version of ADS!
