### ISSUE TITLE
Notebook python intellisense is broken

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5375]
This is on Insiders.

Repro:
- Open notebook in folder with other files
- Choose Python kernel and try intellisense for `print`, and for filenames
- Neither will work.

@chlafreniere can you or @YurongHe look at this? It's a regression and possible ship blocker.

**Comment by YurongHe** [comment]
April release has the same issue.

**Comment by YurongHe** [comment]
![image](https://user-images.githubusercontent.com/43652751/57660607-38373180-759c-11e9-92df-2da39dd8e5a3.png)

Sync to latest. Changed to python and pyspark3. Intellisense is working fine. Also checked the code path, language is set properly for kernel change. Shouldn't be a problem.

Will close it.
