### ISSUE TITLE
Notebook: switching from Notebook to .json file and back loses all work

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5377]
Issue Type: <b>Bug</b>

- Open a folder with notebooks and other files (see https://github.com/kevcunnane/msbuild_ads_demo for example). 
- Open a notebook file and a .json file
- Make edits to the notebook (e.g. add some cells), then switch to the .json and edit, then switch back

Expected:
- Notebook shows the last edited state

Actual:
- Notebook shows initial state on first open, not the last edited state
- If you tab away then click on the notebook in the file tree, it'll load with correct state

This is, needless to say, very bad. I'm not sure if this is a regression so we should investigate, but it's got high risk. If I saved in its "showing initial content" state it would lose all active work.

@YurongHe can you please investigate for May release and see if this is a potential release blocker?

**Screenshots**

Initial:
![image](https://user-images.githubusercontent.com/10819925/57242194-c2552800-6fe7-11e9-805c-e61d288f4a77.png)

Edited:
![image](https://user-images.githubusercontent.com/10819925/57242207-cb45f980-6fe7-11e9-9c12-08e6e47039a6.png)

View after switching to package.json and back:
![image](https://user-images.githubusercontent.com/10819925/57242194-c2552800-6fe7-11e9-805c-e61d288f4a77.png)

Azure Data Studio version: Azure Data Studio 1.7.0-insider (c7f5278430b9df35fb6e160a5b1cf4c653644efc, 2019-05-03T07:13:39.307Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.83GB free)|
|Process Argv|-psn_0_5981620|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|dan|0.2.290
azuredatastudio-postgresql|Mic|0.1.0

</details>

**Comment by YurongHe** [comment]
@kevcunnane, when you switch between files, did you notice the dirty state of notebook is changed?

I can see the problem when the notebook is loading kernel. But not in ready state.

**Comment by YurongHe** [comment]
Got the same behavior in April release.

**Comment by YurongHe** [comment]
Chris and I got a repro under specific situation, which related to open folder->file re-hydration. Vs code does the same thing. https://github.com/microsoft/vscode/issues/73854

**Comment by YurongHe** [comment]
@kevcunnane, "This is, needless to say, very bad. I'm not sure if this is a regression so we should investigate, but it's got high risk. If I saved in its "showing initial content" state it would lose all active work."
The problem we got yesterday is by design and it is using different steps.

I can't repro. Do you save the notebook file before editing json file or tab away?

**Comment by kevcunnane** [comment]
This is so hard to repro - reducing priority and moving out of current milestone.

**Comment by kevcunnane** [comment]
Close as not repro for now, can reopen if we manage to recreate.
