### ISSUE TITLE
Server Dashboard header dissapears when collapsed

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5389]
Issue Type: <b>Bug</b>

After collapsing the dashboard header containing the server information the text disappears and doesn't reappear until something causes a refresh (leaving and re-entering the page, clicking on the text, etc)

Before : 

![image](https://user-images.githubusercontent.com/28519865/57260998-de25f180-701a-11e9-8e3b-ffdaa7f793a9.png)

After :
![image](https://user-images.githubusercontent.com/28519865/57261010-f0079480-701a-11e9-89a3-61eb8299eaec.png)

Azure Data Studio version: azuredatastudio 1.7.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (52.46GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
This should be fixed as part of on-going dashboard refactoring.
