### ISSUE TITLE
Missing feature: Hierarchical view of query plan

### ISSUE THREAD

**Issue by jubax** [microsoft/azuredatastudio#539]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:

* Load a .sqlplan file
* The execution plan with the various nodes is shown

What I'm missing is the hierarchical view (like in SQL Server Management Studio) on the right hand side. Sometimes it is useful to see the information text (Output List, Seek Predicate, ...) of multiple nodes together on the screen.

**Comment by aasimkhan30** [comment]
This is fixed with the new execution plan feature. There is a properties view added to the left side of the screen.
