### ISSUE TITLE
can't see the code in sql editor when stack the documents vertically

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5393]
- Azure Data Studio Version:

Steps to Reproduce:
1. open 2 query editors and run some queries
2. stack 2 editors vertically
3. can't see the code in the bottom editor

![image](https://user-images.githubusercontent.com/13777222/57262346-825e6700-7020-11e9-83f5-c84618684c28.png)

**Comment by anthonydresser** [comment]
@alanrenmsft can you verify if you can repro on master?

**Comment by kburtram** [comment]
This looks fixed in master.  @alanrenmsft please reactive if the issue persists on the latest builds in your environment.

<img width="929" alt="Screen Shot 2019-05-29 at 7 24 19 PM" src="https://user-images.githubusercontent.com/599935/58603932-6dec4380-8247-11e9-9f4d-8521c0e11e5b.png">
