### ISSUE TITLE
Intellisense autocompletion filter applies even after deletion

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5394]
- Azure Data Studio Version: 1.7.0

Steps to Reproduce:

1. Start typing some like sqlCreate
2. Suggestion list filters to snippets starting with that

![image](https://user-images.githubusercontent.com/28519865/57261608-483f9600-701d-11e9-9eb9-164fad83c245.png)

3. Delete all the text (but only exactly that text - no extra backspaces) and then immediately start typing something else, say CREATE

Expected : Autocompletion for CREATE shows up with all sensible options

Actual : List is still filtered to sqlCreate list

![image](https://user-images.githubusercontent.com/28519865/57261698-c865fb80-701d-11e9-90bd-28a274b462a3.png)

**Comment by kburtram** [comment]
This is the "by design" functionality of the auto-complete suggestion dropdown, that it will perform a partial match of the current text with the suggestions list.  e.g. the inputted value can be in the middle of the suggestion and still match.  This is upstream behavior from vscode.
