### ISSUE TITLE
dashboard widgets layout issue

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5398]
- Azure Data Studio Version:

Steps to Reproduce:
1. Connect to a server
2. Open the server dashboard
3. reduce the ADS window size until the dashboard changes the layout of the widgets
4. maximize the ADS window

expected:
The widgets layout should be restored (horizontally listed)

actual:
the widgets remains vertically listed

![image](https://user-images.githubusercontent.com/13777222/57322097-9903cd00-70b7-11e9-84f5-d3db100a99a1.png)

**Comment by kburtram** [comment]
This should be fixed as part of on-going dashboard feature work.
