### ISSUE TITLE
Abyss Theme Database DropDown Color

### ISSUE THREAD

**Issue by amt-kw** [microsoft/azuredatastudio#5399]
Issue Type: <b>Bug</b>

When you have the theme set to Abyss the text in the drop down for database has black text so you can't read the items.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU           E5620  @ 2.40GHz (16 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.99GB (19.01GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1

</details>

**Comment by amt-kw** [comment]
That issue does cover my problem. Thanks.

**Comment by anthonydresser** [comment]
Per that issue, this should be fixed in insiders and will be included in our next release, 1.7.
