### ISSUE TITLE
warning message in console

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5400]
- Azure Data Studio Version:
Latest master as well as 1.7 RC

I saw 2 warning messages in the console after ADS start up. not sure the impact at this point but worth looking into
![image](https://user-images.githubusercontent.com/13777222/57323733-2563bf00-70bb-11e9-8982-9bb900a2fe54.png)

**Comment by anthonydresser** [comment]
Theres no significant impact, but those classes should be refactored to not need objects to be passed only for testing (which is why those messages show up).

**Comment by anthonydresser** [comment]
I don't think this needs to be in May, it has no user impact.

**Comment by kburtram** [comment]
Closing out older low-impact bugs.
