### ISSUE TITLE
backup button in the backup insights dialog not working properly

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5401]
the backup button does nothing when the insights dialog is opened second 
Steps to Reproduce:
1. Start (restart) ADS
2. connect to a server and open dashboard
3. open the backup insights dialog (show details) via the "..." of backup status widget
4. click the backup button on the bottom left of the dialog
5. the backup dialog will be opened, close it and close the backup insights dialog
6. open the backup insights dialog (same as step 3)
7. click the backup button

expected:
backup dialog opens

actual:
nothing happens

**Comment by yualan** [comment]
Udeesha, can you take a look at this one? It may not have directly to do with Backup.
