### ISSUE TITLE
Delete Group on context menu does nothing

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/azuredatastudio#5404]
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Right-click on a server group
2. Click Delete group

Result: nothing happens

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this on either 1.6.0 or the latest insiders build. This happens to you for all server groups? After trying to delete the group could you open the Developer Console (Help -> Toggle Developer Tools) and then click on the Console tab and see if there's any errors listed there?

![image](https://user-images.githubusercontent.com/28519865/57331228-edfe0e00-70cc-11e9-9a00-7e9aa012c489.png)

**Comment by kburtram** [comment]
@SvenAelterman do you have any additional repro steps or error messages?  is this still occurring on the `1.7.0` release?  thanks!

**Comment by SvenAelterman** [comment]
@kburtram The issue appears to be resolved in 1.7.0.
