### ISSUE TITLE
Adding an Azure account with MFA results in infinite loop

### ISSUE THREAD

**Issue by SvenAelterman** [microsoft/azuredatastudio#5407]
Version: 1.6.0 (user setup)
Commit: eb35dae1d1238e03f1cab3bd45e151f381b22aef
Date: 2019-04-17T07:11:15.944Z
Electron: 3.1.6
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Click Add an account... in the Connection Details pane
2. Add Azure account pane opens with User code and Website showing.
3. Click Copy & Open.
4. Complete authentication using browser.
5. Return to Azure Data Studio.
6. Connection Details pane briefly flashes before the Add Azure account pane opens again showing a different User code.
7. Click the back arrow.
7. The account appears to be added but cannot be used to log in to an Azure SQL DB (error: Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'. Appears to be the same issue as #4085)

**Comment by Charles-Gagnon** [comment]
The add account pane re-appearing is a know issue #4451. The login as mentioned is reported in #4085. So I'm closing this issue out as a duplicate.
