### ISSUE TITLE
Read XEL files

### ISSUE THREAD

**Issue by Raymondd** [microsoft/azuredatastudio#541]
It would be awesome to use Sql Ops Studio as a lightweight XEL file reader!
The current output looks like: 
![image](https://user-images.githubusercontent.com/3318689/35354637-83a1542e-00ff-11e8-946b-5acae524a282.png)
Microsoft already has a DLL that does the file parsing. (Microsoft.SqlServer.XEvent.Linq.dll)

**Comment by SakshiS-harma** [comment]
Fixed with https://github.com/microsoft/azuredatastudio/pull/23666 .
