### ISSUE TITLE
Unable to load dashboard properties after dashboard opens awhile - Database dashboard

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5410]
Issue Type: <b>Bug</b>

- Connect a server and open dashboard
- Open a query or notebook, do some db operations in OE.
- Switch back to dashboard tab after half hour or awhile.

Noticed database dashboard has the following two issues. (Not sure how server dashboard is changed to db dashboard.)

1) Tasks are empty
2) Database properties are unable to load for cloud server in screenshot 1.

![image](https://user-images.githubusercontent.com/43652751/57334264-15a4a480-70d4-11e9-83c7-799ae31a8f88.png)

![image](https://user-images.githubusercontent.com/43652751/57334342-4a186080-70d4-11e9-8ec0-ec2983405130.png)

Azure Data Studio version: azuredatastudio 1.7.0 (1c694cbd3bfccbbd17cb68a65c7731ccc5f4e3dd, 2019-05-07T16:39:17.607Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (41.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-pgsql|Mic|0.1.0
profiler|Mic|0.7.0

</details>

**Comment by Charles-Gagnon** [comment]
1. Does this ever recover on its own (for example if you browse away and then back again, or try to do stuff on the dashboard to force a refresh such as edit)
2. Did you see if the console had any errors?
3. This was for an Azure server? Have you tested/seen it on any other server type?

**Comment by YurongHe** [comment]
@Charles-Gagnon 
Once in such state, can't recover by  itself
Did see any error any where
Tasks are empty for BDC and cloud. Second image is BDC.

**Comment by kburtram** [comment]
Closing older issues without recent repros.  Please let us know if you're still impacted by this issue.
