### ISSUE TITLE
Adding CMS server also connect OE server

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5412]
Issue Type: <b>Bug</b>

- Install cms extension
- Add cms server -> give a server name existing in OE list. But that server in OE is disconnected.
- cms server is connected.
  At the same time, OE server is connected too.
![image](https://user-images.githubusercontent.com/43652751/57336694-af238480-70db-11e9-9b89-84fb4586b3b9.png)

 

Azure Data Studio version: azuredatastudio 1.7.0 (1c694cbd3bfccbbd17cb68a65c7731ccc5f4e3dd, 2019-05-07T16:39:17.607Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (41.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-pgsql|Mic|0.1.0
profiler|Mic|0.7.0

</details>

**Comment by abist** [comment]
Fixed
