### ISSUE TITLE
Database size table in dashboard doesn't have the horizontal scroll bar

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5414]
Issue Type: <b>Bug</b>

If db name is long, can't see full name.

![image](https://user-images.githubusercontent.com/43652751/57337732-6ec60580-70df-11e9-8aeb-22cffa506013.png)

Expected:
There is horizontal bar. So no cut on db name.

Azure Data Studio version: azuredatastudio 1.7.0 (1c694cbd3bfccbbd17cb68a65c7731ccc5f4e3dd, 2019-05-07T16:39:17.607Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (46.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-pgsql|Mic|0.1.0
cms|Mic|0.1.0
dacpac|Mic|0.2.0
profiler|Mic|0.7.0
schema-compare|Mic|0.2.0

</details>

**Comment by kburtram** [comment]
The suggested workaround in this case would be to resize the widget to be large enough to accommodate the database name.  Please let us know if this doesn't resolve the issue in your scenario.  Thanks!
