### ISSUE TITLE
issue with localization - extension's contributions view 

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5415]
the CMS extension's contributions view, the descriptions for commands are not showing the actual strings

![image](https://user-images.githubusercontent.com/13777222/57337867-f875d300-70df-11e9-9088-4d99902208a8.png)

**Comment by Charles-Gagnon** [comment]
Note this isn't just the CMS extension (the SQL 2019 extension has this issue for example), it seems like this page just doesn't actually localize the strings.

**Comment by alanrenmsft** [comment]
this is an upstream issue: https://github.com/Microsoft/vscode/issues/54111
