### ISSUE TITLE
Idle notebook loses connections and cannot recover

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5423]
Steps to Reproduce:

1. Open notebook and run some code cells
2. Leave the notebook open for an extended period (in my case 1hr+)
3. run a code cell

Result: code cell does not return a result. Stopping and restarting the cell doesn't address the issue. 

Workaround: Close Azure Data Studio and re-open the notebook.

**Comment by kevcunnane** [comment]
@kburtram I'm interested to see if this is notebook-specific or similar to query editor. Is there any special handling in the editor that we might have missed in the kernel?

**Comment by kevcunnane** [comment]
Chris cannot repro this. At this point we are going to propose closing unless we can get better steps / repro for this.
