### ISSUE TITLE
Dark colour themes connection combo

### ISSUE THREAD

**Issue by Allann** [microsoft/azuredatastudio#5429]
Issue Type: <b>Bug</b>

The connection combo box text in the SQL query window is always black.  This makes it very difficult to read when using dark themes.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.88GB (3.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.1.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by kburtram** [comment]
This should be fixed in the `1.7.0` release published earlier today.  Please let me know if you still experience this behavior with the latest release.  Thanks!
