### ISSUE TITLE
Coloured groups - Custom Colours

### ISSUE THREAD

**Issue by cheng93** [microsoft/azuredatastudio#5430]
**Describe the solution or feature you'd like**

When choosing a colour for groups, we have a set of default [6] colours.

Would be great if we had the ability to choose our own.

**Comment by cheng93** [comment]
Quick workaround 

Edit the the colour in `datasource.connectionGroups` within `settings.json` 

Still, a colour picker would be nice

**Comment by kburtram** [comment]
@cheng93 thanks for the suggestion!  We're tracking this feature request with this issue https://github.com/microsoft/azuredatastudio/issues/2785.  As you mentioned, for now the server group colors can be customized in the settings.json.  Closing as duplicate.
