### ISSUE TITLE
agent job history status is not correctly displayed

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5434]
the entry reported as succeeded in the screenshot below is displayed as stopped in SSMS.

![image](https://user-images.githubusercontent.com/13777222/57397669-109e2e80-7182-11e9-87fe-568a19971bb6.png)

**Comment by alanrenmsft** [comment]
also the step status is not the same as SSMS 
![image](https://user-images.githubusercontent.com/13777222/57398061-fc0e6600-7182-11e9-9891-272ca3ca2536.png)

**Comment by abist** [comment]
This was fixed.
