### ISSUE TITLE
Agent: proxy 's displayed status is not correct

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5438]
![image](https://user-images.githubusercontent.com/13777222/57400256-ea7b8d00-7187-11e9-91f9-04b363ca8e9b.png)

![image](https://user-images.githubusercontent.com/13777222/57400283-f7987c00-7187-11e9-8939-ec8bd5441612.png)

**Comment by abist** [comment]
@alanrenmsft Where are you seeing this status on SSMS?

**Comment by alanrenmsft** [comment]
/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [proxy_id]
      ,[name]
      ,[credential_id]
      ,[enabled]
      ,[description]
      ,[user_sid]
      ,[credential_date_created]
  FROM [msdb].[dbo].[sysproxies]

**Comment by abist** [comment]
Closing as fixed.
