### ISSUE TITLE
Add "Connect to" ADS feature to Azure databases.

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#5440]
Issue Type: <b>Feature Request</b>

For databases that can be connected to in Azure (e.g., Azure SQL DB, Azure Postgres).  Add a "Connect to ADS"  function like the one that is available for Visual Studio.

![image](https://user-images.githubusercontent.com/41927913/57410827-b9f41d00-71a0-11e9-8780-3cc6b458cb63.png)

Azure Data Studio version: Azure Data Studio 1.7.0-insider (c7f5278430b9df35fb6e160a5b1cf4c653644efc, 2019-05-03T07:13:39.307Z)
OS version: Darwin x64 18.5.0

**Comment by kburtram** [comment]
We're tracking this request with issue https://github.com/microsoft/azuredatastudio/issues/1611.  Though this issue should probably be track in the Azure Portal issue tracker since this is an Azure Portal feature request.
