### ISSUE TITLE
[BDC]-[Notebook]- If we query a huge file in Notebook it reports - IOPub data rate exceeded

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#5446]
Issue Type: <b>Performance Issue</b>

In ADS Notebook if we query a large log file I notice the following warning and display data gets truncated.
 
IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.
 
Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)
 
This looks like relative to the Jupyter Notebook bug that has been already filed https://github.com/jupyter/notebook/issues/3010 https://github.com/jupyter/notebook/issues/2287, To work around the issue most of them have the following lines that needs to be executed https://stackoverflow.com/questions/43288550/iopub-data-rate-exceeded-in-jupyter-notebook-when-viewing-image. 
 
1.	To create a jupyter_notebook_config.py file, with all the defaults commented out, you can use the following command line:
$ jupyter notebook --generate-config
2.	Open the file and search for c.NotebookApp.iopub_data_rate_limit
3.	Comment out the line c.NotebookApp.iopub_data_rate_limit = 1000000 and change it to a higher default rate. l used c.NotebookApp.iopub_data_rate_limit = 10000000
This unforgiving default config is popping up in a lot of places. See git issues:
•	jupyter
•	IOPub data rate exceeded
It looks like it might get resolved with the 5.1 release
Update:
Jupyter notebook is now on release 5.2.2. This problem should have been resolved. Upgrade using conda or pip.

How to mitigate the Issue; How to apply the workaround that has been fixed. It looks like we are using Jupyter notebook of version 5.7.4 which is greater than the fixed build but the issue still occurs.

Repro:-
Just read some file from O/S or from K8s cluster either using cat or 

!kubectl exec -ti control-rfx7c -c mssql-controller -n mssql-cluster -- cat /var/opt/controller/log/2019-05-07/controller-trace.log

!type C:\EAPWebinar\controller-trace.log

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz (12 x 2394)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|31.92GB (22.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	    85	  5964	azuredatastudio main
    0	   289	  4264	   window (Azure Data Studio)
    1	   143	  4848	     extensionHost
    0	    70	  7620	   shared-process
    1	    80	 17208	   gpu-process
    0	    77	 19448	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
<details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.12.1

</details>

**Comment by kevcunnane** [comment]
@ronychatterjee - pushing this out to planning. We have 8 days left for feature improvements in June, and this will require adding a section to user settings which we can then copy over to the notebook config on startup. While that's not a crazy amount of work I'd guess it'll be 2 days and that doesn't fit.

**Comment by chlafreniere** [comment]
This has since been fixed in our September release with our performance enhancements re: text editor models.
