### ISSUE TITLE
vertical tabbed window panes - query pane unreadable when results and or messages displayed

### ISSUE THREAD

**Issue by nige6** [microsoft/azuredatastudio#5455]
Issue Type: <b>Bug</b>

new query window, short sql
copy sql, new query window, move below current pane so vertical

run sql in new query pane, results and or messages appear and the query pane appears blank.

resize query pane upwards and sql begins to appear once larger than half ADS window size.
cannot hide or remove results/messages to get query back

seperate request - can we can Results and messages as per SSMS to remove these types of issues

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700T CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|15.89GB (8.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
@nige6 we are actively looking at how to improve the query editor to address this type of issue.

**Comment by kburtram** [comment]
This should be fixed\improved in the June release.  Please let me know if there is additional feedback in this area.
