### ISSUE TITLE
Zoom Changed in Last Update

### ISSUE THREAD

**Issue by brhaut0802** [microsoft/azuredatastudio#5456]
Issue Type: <b>Bug</b>

The zoom out makes text very blurry even with just one zoom out.  Was perfectly fine before the most recent update.  VS Code is still perfectly fine

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7660U CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (5.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.38.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.2.1

</details>

**Comment by kburtram** [comment]
@brhaut0802 we did reduce the default font sizes in the `1.7.0` release based on customer feedback that we used too much whitespace.  The smaller fonts should also generally reduce the need to zoom out in many cases.

The fonts are adjustable from the Settings.  Please let me know if manual adjustment doesn't resolve the issue.

**Comment by brhaut0802** [comment]
Yes I did figure this out and changed it.  In the results I cannot figure out how to change the font size there.  Its really small

**Comment by kburtram** [comment]
@brhaut0802 please take a look for `Results Grid: Font Size` setting to increase the grid font.  Previously it was set to 14. 

Out of curiosity, which UI elements are you trying to scale smaller that we didn't address with the font changes in `1.7.0`?  The goal would be ideally that users don't need to zoom out (except in some limited cases such as large low-resolution displays, such as a projector, etc.).

**Comment by brhaut0802** [comment]
Thanks that worked.  I zoom out to make the icons smaller on the left.  and also to get the explorer bar to take up less room.  I am using VS Code on one screen and Azure Data Studio on the other and just want them to match so I can go back and forth easier with out my eyes having to adjust often

**Comment by kburtram** [comment]
@brhaut0802 thanks for the details!  I'll discuss with our UX folks whether we need further updates to our default sizing for those UI elements.

Can I close this issue now?  Or if there is still work you'd like us to consider please add a screenshot demonstrating the problem so we can review with UX.

**Comment by brhaut0802** [comment]
Yes we can close this.  Thank You
