### ISSUE TITLE
Notebooks: Outputs components should react to layout changed events

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5466]
In a notebook today, we re-render any output for any layout changed events that occur. This is overkill in many cases (including for tables), which already have existing functionality that handles changes to node sizes without re-rendering the entire table.

**Comment by kevcunnane** [comment]
This is complete. For markdown renderer, we don't re-layout. For the Jupyterlab-originated renderers we still do, but I looked at nteract and it does the same for these basic ones. We are moving grid to the new (don't re-build) model but it's tracked in a separate issue. So the core work here to support this is done.
