### ISSUE TITLE
Unable to resize results and messages windows in split view

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#5470]
Issue Type: <b>Bug</b>

 

WHen working with split view (2-3 columns), I've found that sometimes the messages window is resizable independently from the Results window (which is what I would want -- independent resizing), and sometimes not. 

 

For example, with this simple query:

 

`select @@version, SERVERPROPERTY('edition')`

 

In a single column, the messages and results windows are independently resizable.  If I hover over the top edge of either the Results or the Messages window, I see the up-down arrows and can pull the edges independently to resize them.  This is very handy when the messages are small (or not relevant) and the result set is large.

 

if I then split the editor into two columns, start a new query (same query) and drag it to the new column, A few things happen:

 

1. The left hand column results and messages windows are no longer independently resizeable.  They are locked together, although the resize arrows appear in both windows. The one on the messages windows stops working

2. The right-hand column results and messages window are now not resizable at all.  I can see the resize arrows but cannot drag the windows up or down to resize them.

3.  An "X" appears in the right-hand column's messages window.  Clicking it seems to unlock the resize arrows though I still cannot resize results and messages independently. 

 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)

OS version: Windows_NT x64 10.0.16299

 

<details>

<summary>System Info</summary>

 

|Item|Value|

|---|---|

|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|

|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|

|Load (avg)|undefined|

|Memory (System)|31.84GB (17.76GB free)|

|Process Argv|C:\Users\BRITTG2\Downloads\1.Alter_Function_results.IsReconDataReady4Consumption.sql|

|Screen Reader|no|

|VM|0%|

</details><details><summary>Extensions (13)</summary>

 

Extension|Author (truncated)|Version

---|---|---

ssmskeymap|kev|1.1.0

admin-pack|Mic|0.0.2

agent|Mic|0.38.0

dacpac|Mic|0.2.0

import|Mic|0.7.0

powershell|ms-|1.12.1

profiler|Mic|0.7.0

schema-compare|Mic|0.2.0

server-report|Mic|0.1.5

sql-vnext|Mic|0.13.0

whoisactive|Mic|0.1.1

sql-search|Red|0.3.3

poor-sql-formatter|WSR|0.1.0

 

 

</details>

**Comment by gbritton1** [comment]
Another related oddity.  I often have queries where the messages window has only three lines.  I want to resize it to the bottom of the editor area.  I can move it a little up and down (maybe half an inch?) but that's it.

Also, If I close the messages (Click the little arrow), the resize arrows do not appear, even though I want to drag the messages all the way to the bottom so that only one line is used on screen

**Comment by gbritton1** [comment]
Similar to [Window Resize (#4816)](https://www.github.com/microsoft/azuredatastudio/issues/4816) though that one does not mention split columns.

**Comment by kburtram** [comment]
This should be fixed by the change to move Message to its own tab.  Please let me know if you're still hitting this issue on 1.8.0.

I didn't open a related bug while validating this scenario https://github.com/microsoft/azuredatastudio/issues/5929.
