### ISSUE TITLE
Cannot create folder in HDFS in CTP 2.5 cluster

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#5473]
Issue Type: <b>Bug</b>

I am not able to create a folder in HDFS in 2.5 cluster. This is a regression which needs to be fixed.

Azure Data Studio version: Azure Data Studio 1.7.0-insider (c7f5278430b9df35fb6e160a5b1cf4c653644efc, 2019-05-03T07:13:39.307Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.21GB free)|
|Process Argv|-psn_0_12147605|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.1.0
sql-vnext|Mic|0.12.1
azdata-sanddance|msr|1.0.0

</details>

**Comment by kevcunnane** [comment]
Yurong fixed this today. It’s in tomorrow’s insider build
