### ISSUE TITLE
Cannot install add-in

### ISSUE THREAD

**Issue by Daxing1980** [microsoft/azuredatastudio#5474]
Azure Data Studio Version: User version 1.7.0
Case : Trying to install the add-in

Steps to Reproduce:

1. Search add-in, and find the Sql Server Import (or Admin Pack for SQL Server)
2. Press Install
3. Errors with : Failed to install 'microsoft.import'.
4. Download manually errors with : 

<Error>
<Code>BlobNotFound</Code>
<Message>The specified blob does not exist. RequestId:35fe3ac5-b01e-007c-7223-0a7037000000 Time:2019-05-14T07:04:05.7583389Z</Message>
</Error>

Hope someone can help getting this back online. Great tool.

**Comment by kburtram** [comment]
@Daxing1980 I wasn't able to repro this issue when installing the Import extension this morning.  We host the extensions on Azure BLOB Storage, so it's possible there was a temporary outage access this resource.  Please retry the install and see if it's back online now.  Thanks!

**Comment by Daxing1980** [comment]
@kburtram thanks for the answer. After uninstalling everything, I realized that the extension downloaded earlier caused a problem after updating the application to 1.7.0. Once deleted the extensions within the c drive itself, then re-installing the software, that made it work. Thanks for the reply!
