### ISSUE TITLE
Info "MESSAGES" on return GRID of queries

### ISSUE THREAD

**Issue by cmpsmarcio** [microsoft/azuredatastudio#5475]
Issue Type: <b>Feature Request</b>

I would like to suggestion a change information "messages" on return of queries. I wish it was this information on new tab.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment]
@cmpsmarcio thanks for the suggestion.  We're currently tracking moving the Messages content to its own tab with this issue https://github.com/microsoft/azuredatastudio/issues/4680.  Please add comments there if the issue doesn't fully capture your feature request.
