### ISSUE TITLE
Useless error message with unterminated comment

### ISSUE THREAD

**Issue by timothylcooke** [microsoft/azuredatastudio#5478]
Issue Type: <b>Bug</b>

From Azure Data Studio, execute a query with an unterminated comment:

    SELECT 1; /*

The error message is useless:

    Execution failed due to an unexpected error: 
    {1}

![image](https://user-images.githubusercontent.com/8904110/57710833-b1d22c80-763b-11e9-903e-24f3cf8a8b4e.png)

I ran this on ADS version 1.7.0 as well, with the same results.

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Memory (System)|7.73GB (1.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by kburtram** [comment]
It looks like the error message from the engine should be "`Missing end comment mark '*/'`".  This error is probably coming from the SQL Tools Service code that preps the query for execution.
