### ISSUE TITLE
Allow server messages bar to be resized, even when query returns less than 10 results

### ISSUE THREAD

**Issue by mhoelzel142** [microsoft/azuredatastudio#5494]
- Azure Data Studio Version: 1.7.0 (VSCode version 1.33.1)

The messages bar is too close to the query results bar and makes the results feel crowded and cramped when selecting a small result set from a single table. I would like the ability to shrink the Messages bar/expand the query results, even when less than 10 query results are present. If the messages bar is minimized, I would like it to be pinned to the bottom instead of hanging out in the middle of the screen and crowding the results. 

Steps to Reproduce:
connect to any table and run a "select top 10 * from table_name". The messages tab is pinned about 150 pixels below the Results view and leaves a lot of empty space beneath, making the results feel crowded and uncomfortable.

**Comment by kburtram** [comment]
@mhoelzel142 thanks for reporting this problem.  This is basically the same bug we're tracking with issue https://github.com/microsoft/azuredatastudio/issues/3177.  We're planning to move Messages into its own tab which will remove this particular UX problem.  I'll close as a duplicate.
