### ISSUE TITLE
Title Bar and Menu Don't Match Color Scheme Similar to VS Code

### ISSUE THREAD

**Issue by rkdiekhoff** [microsoft/azuredatastudio#5497]
Issue Type: <b>Feature Request</b>

The color/display of the title bar and menu doesn't coincide with the color scheme currently selected.  This feature is currently applied and available in VS Code.  Can this capability be added for Azure Data Studio?

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
We're tracking this enhancement request with https://github.com/microsoft/azuredatastudio/issues/3300.  Please update that issue if there is additional context you'd like to add.  Thanks!
