### ISSUE TITLE
Messages pane collapsed but still uses half screen

### ISSUE THREAD

**Issue by Allann** [microsoft/azuredatastudio#5498]
Issue Type: <b>Bug</b>

Is there a way to make the results pane much larger?  e.g.  splitter.  Currently the Messages section is collapsed but still takes 1/2 the screen height.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.34GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

Screen shot:  
![2019-05-16 12_54_51-](https://user-images.githubusercontent.com/2005474/57823208-04494f80-77da-11e9-88eb-b894eba88573.png)

**Comment by kburtram** [comment]
@Allann if the query returns enough results to fill the available screen space then the resultgrid should be resizable to fill that space.  If the query doesn't return enough results to fill the screen then the messages pane will occupy the available space.  There is more discussion of this behavior in https://github.com/microsoft/azuredatastudio/issues/3177.  Please let me know if that doesn't address your question.

**Comment by Allann** [comment]
Thanks that is quite confusing.  I used to use the SQL object viewer in VS201x and results is normally the thing that fill the screen.  Messages pane would normally be a fixed size at the bottom.

**Comment by kburtram** [comment]
@Allann I agree that the current behavior is confusing.  We had a fix that collapsed the Message to the bottom even when the resultset didn't fill the available area, but that change had several side-effects and needed to be reverted.  We're planning to move the Messages into its own tab soon, so we decided to wait for that change rather than try to correct the previous attempt at fixing this.
