### ISSUE TITLE
Widget is doubling the number of rows in some tables

### ISSUE THREAD

**Issue by B4PJS** [microsoft/azuredatastudio#55]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: add the widget for table-space-db-insight to the database dashboard.

The query underlying the table space widget is doubling the number of rows for some, not all, tables in my db.

```
SELECT Top 5
    TABL.name AS table_name,
    SUM(PART.rows) AS rows_count,
    SUM(ALOC.total_pages) AS total_pages,
    SUM(ALOC.used_pages) AS used_pages,
    SUM(ALOC.data_pages) AS data_pages,
    (SUM(ALOC.total_pages)*8/1024) AS total_space_MB,
    (SUM(ALOC.used_pages)*8/1024) AS used_space_MB,
    (SUM(ALOC.data_pages)*8/1024) AS data_space_MB
FROM sys.Tables AS TABL
    INNER JOIN sys.Indexes AS INDX
    ON TABL.object_id = INDX.object_id
    INNER JOIN sys.Partitions AS PART
    ON INDX.object_id = PART.object_id
        AND INDX.index_id = PART.index_id
    INNER JOIN sys.Allocation_Units AS ALOC
    ON PART.partition_id = ALOC.container_id
WHERE
INDX.object_id > 255
    AND INDX.index_id <= 1
GROUP BY TABL.name, 
INDX.object_id,
INDX.index_id,
INDX.name
ORDER BY 
(SUM(ALOC.total_pages)*8/1024) DESC


```

**Comment by B4PJS** [comment]
Identified it as being the allocation units table having up to 3 different types of allocation units when using a columnstore, thus doubling or trebling the row_count.

LOB_DATA
ROW_OVERFLOW_DATA
IN_ROW_DATA

**Comment by kburtram** [comment]
Cleaning up old issues.  I'm going to close this as "won't fix" for now since we don't plan to address in the next few milestones.
