### ISSUE TITLE
Ability to Copy From Notebook Results Grid

### ISSUE THREAD

**Issue by sheldonhull** [microsoft/azuredatastudio#5501]
Issue Type: <b>Feature Request</b>

Requesting the same behavior that a normal grid exhibits for selection and copying is applied to the notebook format to allow copying the contents contained in the notebook. 

Without this, it's difficult to leverage notebooks fully when using them to jump start other research based on the results in the gird. 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kevcunnane** [comment]
@chlafreniere let's treat this as a bug. I don't think it fits in June but let's push to figure a solution in July once your refactor it relies on is available.

**Comment by chlafreniere** [comment]
👍
