### ISSUE TITLE
CMS connection dialog showing for normal SQL connections

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5504]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Connection Dialog from Servers view with CMS extension installed

Expected: SQL Connection dialog page

Actual: CMS page (note Server description and lack of database field when connection type is SQL Server)

![image](https://user-images.githubusercontent.com/599935/57889237-2d251100-77e9-11e9-8f74-83b04e4ea465.png)

**Comment by kburtram** [comment]
@abist have you had a chance to investigate this?  this will prevent us from releasing the CMS extension this month.

**Comment by abist** [comment]
@kburtram This was already fixed in the PR out

**Comment by kburtram** [comment]
@abist any ETA on merging the fix?  the bug was logged a couple weeks ago.

**Comment by abist** [comment]
@kburtram Trying to get integration tests along with the fixes. There were ongoing issues with them which have been resolved, so I'll update the PR with tests by EOD. If the PR is approved, I'll merge.

**Comment by abist** [comment]
Fixed.
