### ISSUE TITLE
"Failed to start Scale Out Data service:Error: Request error: Error"

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5505]
Issue Type: <b>Bug</b>

I guess there must have been an error: :) 

This message popped up as soon as I opened ADS. 

I do have an issue with my AKS Cluster at the moment but I wanted to raise this as the error message itself isn't particularly helpful and the language used seems "internal".

<img width="453" alt="Screen Shot 2019-05-16 at 3 40 10 PM" src="https://user-images.githubusercontent.com/10529018/57891764-76795e80-77f1-11e9-80f1-8f27a1ab605f.png">

Azure Data Studio version: Azure Data Studio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:38:05.313Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|-psn_0_8066993|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.13.0

</details>

**Comment by kevcunnane** [comment]
@corivera / @geleems could one of you take a look at this? Is there better log info that JRJ can submit? Also would be great if we can fix service name here...

**Comment by geleems** [comment]
Looking at this issue.
So far, I am not able to repro it with my testing cluster.
 @jrowlandjones Can you provide a test access for me so that I can repro the issue?

**Comment by kevcunnane** [comment]
@geleems something caused the backend C# service to fail to start. Commonly this is if the wrong .vsix file (e.g. one for mac, but you're running on Windows) was used. if not let's follow up with JRJ and either close out or push for a fix, thanks!

**Comment by kevcunnane** [comment]
I verified it was using osx vsix on windows. Closing
