### ISSUE TITLE
Notebook: Trusted should be set if all cells are run

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5506]
Jupyter behavior is that on running all cells (either 1 at a time or using "Run All Cells") the notebook becomes trusted. We lost this logic somewhere along the line, such that there's no handling / notification of this. We should look to fix.

**Comment by corivera** [comment]
@chlafreniere When I try executing cells in jupyter the notebook stays Not Trusted. In my testing, the notebook only became trusted when clicking the Trusted button or through saving the notebook. Should we still proceed with this one?

**Comment by chlafreniere** [comment]
Yes, please proceed. We had some design discussions around this quite a while back and would like to re-enable this functionality.
