### ISSUE TITLE
[ADS]-[Notebook]-connect ECONNREFUSED 127.0.0.1:9288 error causing orphaned Python & Jupyter-notebook process chain

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#5510]
Issue Type: <b>Bug</b>

Hi Team,
 
I am noticing some variations of python and notebook executables not getting cleaned up correctly post Notebook closure. Intermittently when the Notebook is closed and then opened we get the following error is the starting point of the problem. Has anyone experienced this issue already and is this being looked into.
 
![1](https://user-images.githubusercontent.com/27516588/57924105-d0495980-78c1-11e9-8633-a1e3df18c244.png)

 
And for the Notebook Logs we notice the following errors on the Port issues
 
... Starting Notebook server
    > "C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe" -m jupyter notebook --no-browser --notebook-dir "c:\EapWebinar" --port=9288 --NotebookApp.token=8f97da0a6e66bd766a1f437ba2eb09f6b0d35329f62668c5
... Jupyter is running at http://localhost:9288/?token%3D8f97da0a6e66bd766a1f437ba2eb09f6b0d35329f62668c5
    > "C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe" -m jupyter notebook stop 9288
    stderr: There is currently no server running on port 9288
    stderr: Ports currently in use:
    stderr:   - 9198
    stderr:   - 9571
    stderr: 
Error stopping Notebook Server: Command failed: "C:\Users\pradm\azuredatastudio-python\0.0.1\python.exe" -m jupyter notebook stop 9288
There is currently no server running on port 9288
Ports currently in use:
  - 9198
  - 9571
 
Post this if you see the processes you will see an orphaned process chain of python and notebook as below which depicts as if though someone has launched the python and notebook outside ADS from command line.
 
![2](https://user-images.githubusercontent.com/27516588/57924117-d9d2c180-78c1-11e9-99c0-a733148fbda2.jpg)

 

Regards
Pradeep

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.83GB (10.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
@pradm have you seen this issue happen lately?

**Comment by pradm** [comment]
@chlafreniere , nope i have not seen this issue in recent repro's. if i encounter it again will reopen. you can archive this for now.
Thank you so much for looking into this.

**Comment by chlafreniere** [comment]
Thanks @pradm. Will close this then. Feel free to reopen if you see this behavior in the future.
