### ISSUE TITLE
Notebook syntax/error highlighting behaves differently before kernel start

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#5513]
Issue Type: <b>Bug</b>

If you enter code before a kernel session starts the syntax and error highlighting is incorrect and remains that way through the rest of the session. It seems that it uses the colorization and snippets from the first kernel and this does not reset even after adding new cells.

![Notebook Error Highlighting Incorrect](https://user-images.githubusercontent.com/8250560/57934404-838b6180-7874-11e9-809b-5f2ab91a43a1.gif)

Compare the colorization of this notebook where code cells were not added until after the kernel started:

![image](https://user-images.githubusercontent.com/8250560/57933773-f09df780-7872-11e9-9f99-83c88486e78b.png)

To this one, where the first code cell was added before the kernel started (but after moving from SQL) and the second code cell was added after the kernel had started:

![image](https://user-images.githubusercontent.com/8250560/57933814-0ca19900-7873-11e9-99c6-1e0768286609.png)

In the latter case, SQL snippets are available in all new cells even well after the kernel has been running.

![image](https://user-images.githubusercontent.com/8250560/57934321-5474f000-7874-11e9-95e6-806bb22bbc70.png)

Azure Data Studio version: azuredatastudio 1.7.0-insider (2b8e0cc6c43fa212741e57adc8966e434eb65628, 2019-05-10T15:55:49.193Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0
schema-compare|Mic|0.2.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.10.3
whoisactive|Mic|0.1.1
azdata-sanddance|msr|1.0.0

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
@lucyzhang929 can you check if your previous changes to intellisense after kernel change fix this particular issue?

**Comment by lucyzhang929** [comment]
Verified that the syntax/error highlighting, colorization, and sql snippets are reset after switching from SQL to Python even if contents are added before Changing kernel is complete.
