### ISSUE TITLE
Can't connect to any local server

### ISSUE THREAD

**Issue by sfweller** [microsoft/azuredatastudio#5519]
- Azure Data Studio Version:
Version 1.7.0 - Commit: e1280022d69b651cfff04b30e830904575c8acda

Steps to Reproduce:

1.   Launch a brand new Azure data studio session  and select connection type 'Microsoft SQL Server' or connection type 'SQL Server Big data cluster'. For connection type 'Microsoft SQL Server' I get the error:

'Connection error'
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occured while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server)) ---> System.ComponentModel.Win32Exception(53): The network path was not found 

Note: I am able to ping the SQL big data cluster just fine from a DOS command prompt.

**Comment by kburtram** [comment]
@kevcunnane did we remove the "Big Data Cluster" connection type from the latest v2019 extension?  Maybe the extension needs to be updated in this case?

The error message is a generic connection failure from SqlClient.  You could check that ports are open or try connecting from a different client to help isolate the issue a bit more.

**Comment by kevcunnane** [comment]
Yes, that's been removed in newer versions. The SQL Server endpoint is the one to connect to. @sfweller are you connecting to the right endpoint? Usually the 31433 port is the one you'll want for SQL Server inside a big data cluster.

**Comment by kevcunnane** [comment]
Resolved offline
