### ISSUE TITLE
Fails to get Properties for connected database in ADS

### ISSUE THREAD

**Issue by geleems** [microsoft/azuredatastudio#5525]
Fails to get Properties with this error message: 
```
Error calling SsmsMin with args '-a "sqla:Properties@Microsoft.SqlServer.Management.Smo.Server" -S "xxx.xxx.xxx.xxx,31433" -U "sa" -u "Server[@Name='xxx.xxx.xxx.xxx,31433']"' - The system cannot find the path specified.
```

![Honeycam 2019-05-17 16-15-47](https://user-images.githubusercontent.com/19577035/57960687-0b965900-78bf-11e9-9935-ef9f7e0c1018.gif)

**Comment by Charles-Gagnon** [comment]
You need to run 

gulp install-ssmsmin

prior to working on this in a dev environment. 

(It'll be released as a package which will have the EXE included in it for release)
