### ISSUE TITLE
Restore Database from file causes error

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5526]
Issue Type: <b>Bug</b>

Restore database from server dashboard
Click on the Restore from and choose backup file
Click on ellipsis ...
<img width="644" alt="Screen Shot 2019-05-17 at 4 39 00 PM" src="https://user-images.githubusercontent.com/10529018/57961278-b5c3b000-78c2-11e9-83f1-daac8e351df6.png">

Azure Data Studio version: Azure Data Studio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:38:05.313Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv|-psn_0_8066993|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.13.1

</details>

**Comment by jrowlandjones** [comment]
Using 0.13.1 extension and targeting docker

**Comment by kburtram** [comment]
We're tracking this bug with issue https://github.com/microsoft/azuredatastudio/issues/4767.  The current investigation is pointing to a recent change in behavior of the `sys.dm_os_enumerate_filesystem` on non-Windows platforms.
