### ISSUE TITLE
In the latest insiders build I cannot change the Kernel to Python3

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#5530]
Issue Type: <b>Bug</b>

We need this to work. I have a demo this week.

<img width="1433" alt="image" src="https://user-images.githubusercontent.com/22312581/57979709-76868380-79d6-11e9-96da-034ce8a5c29b.png">

Azure Data Studio version: Azure Data Studio 1.7.0-insider (fe17955fa11483d25aad5f05cefe99df71422dcb, 2019-05-17T07:14:03.590Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.26GB free)|
|Process Argv|-psn_0_23848637|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kevcunnane** [comment]
Rony - I haven't seen this. Can you give more info?

**Comment by kevcunnane** [comment]
Rony - I'm closing. Reopen if you have more info.
