### ISSUE TITLE
HDFS Not Loading

### ISSUE THREAD

**Issue by Kaijisse** [microsoft/azuredatastudio#5536]
Issue Type: <b>Bug</b>

Hi all, 

Under my Servers, my HDFS is not loading. It looks like there is a bug because I tried restarting azure data studio, refreshing it, but it just keeps staying on loading.  I've had this before and after 10 or so restarts it suddenly started working, but this time this luck is not at my hand. 

How can this be?

Many thanks, 

Kind Regards, 

Kaijisse Waaijer

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.81GB (55.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.13.1

</details>

**Comment by kevcunnane** [comment]
Does the expand eventually time out with an error? Given you are mentioning it sometimes works after 10 seconds, this sounds very much like a cluster issue. Suggestions:
- Reach out to CSS and ask for help on how to debug the issues on the server side
- Try following [this guide](https://docs.microsoft.com/en-us/sql/big-data-cluster/data-ingestion-curl?view=sqlallproducts-allversions) to working with HDFS using CURL. If this is going fine, then it's more likely to be a client issue. I suspect this will help give you the feedback you need to diagnose this issue.

**Comment by kevcunnane** [comment]
Closing this out, please reopen if it turns out to be a client side issue, thanks!
