### ISSUE TITLE
Can't install additional language packs

### ISSUE THREAD

**Issue by drgreenthumb93** [microsoft/azuredatastudio#5537]
Hey,

i downloaded the Azure Data Studio v 1.7.0 on my Linux-PC  (BackBox 5.3) but can't install ANY language pack. Tried Ctrl+Shift+P to change "Language Mode" or "Configure Display Language".
Didn't work yet. 
Do you guys have some idea, how to solve this?

greets

**Comment by Charles-Gagnon** [comment]
This is being tracked in #3727 - closing this one as a duplicate. 

@kburtram in case you have any other comments you want to give

**Comment by kburtram** [comment]
I'm working on this today.  The plan is to publish LangPacks to insiders build marketplace this week and to stable feed for June release.
