### ISSUE TITLE
There is apparently no way to edit an existing connection

### ISSUE THREAD

**Issue by drk-mtr** [microsoft/azuredatastudio#5538]
Issue Type: <b>Feature Request</b>

Can right click a connection and select "Edit Connection" to change - for example - the name or the connection string.

**Comment by kburtram** [comment]
@drk-mtr we are tracking this missing feature with issue https://github.com/microsoft/azuredatastudio/issues/3963.  There are a couple workarounds document there that may help you until this capability is available.  Thanks!
