### ISSUE TITLE
python notebook returns a blank rendering window

### ISSUE THREAD

**Issue by schlivo** [microsoft/azuredatastudio#5539]
- Azure Data Studio Version:
1.5.1
Steps to Reproduce:

Tested o both Windows 10 and macOS. 

Rendering a plotly chart in browser works fine

```python 
from plotly.offline import plot
import plotly.graph_objs as go
plot([go.Scatter(x=[1, 2, 3], y=[3, 2, 6])], filename='my-graph.html', image='jpeg')

```
However when I try to generate  an offline graph  within the Notebook it retrurns a blank image

```python
import plotly.graph_objs as go
from plotly.offline import download_plotlyjs, init_notebook_mode, plot, iplot

init_notebook_mode(connected=True)

iplot([go.Scatter(x=[1, 2, 3], y=[3, 1, 6])])

**Comment by kevcunnane** [comment]
@chlafreniere @corivera let's repro and see what the fallback content is when Plotly chart outputs are returned from Jupyter.

The correct fix for this is, I think, to just start shipping the Plotly rendered built-in. but it'd be nice to see whether we have an additional issue with not correctly rendering the fallback content though.

**Comment by kevcunnane** [comment]
I'll investigate this month.

**Comment by chlafreniere** [comment]
Validated that this has been fixed:

![image](https://user-images.githubusercontent.com/40371649/67136683-8c46e180-f1de-11e9-973d-e1d764b985a0.png)
