### ISSUE TITLE
Notebook save as is broken

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5546]
With latest master, Notebook->File Menu->Save as, the notebook is not saves as new name. The untitled notebook is changed to not dirty.

I checked May release, which is working fine.

Not sure if it is related to recent VS code merge. Saw some changed in fileCommand.ts file.

**Comment by anthonydresser** [comment]
The latest vscode merge did some stuff with how the editor status sets the mode, but thats the only big thing I remember from this area.
