### ISSUE TITLE
SQL Login connection does not work

### ISSUE THREAD

**Issue by cirilm** [microsoft/azuredatastudio#5549]
Issue Type: <b>Bug</b>

when I try to connect to SQL server nothing happens. when I click connect everything is gray and you could wait for long time. no error also

Azure Data Studio version: Azure Data Studio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:38:05.313Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4258U CPU @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (1.07GB free)|
|Process Argv|-psn_0_6489648|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1

</details>

**Comment by abist** [comment]
Hi @cirilm, thanks for reporting the issue. Could you check the error console from the Developer Tools (Ctrl + Shift + I) and paste it here for more information?
