### ISSUE TITLE
Notebooks: Unable to edit another notebook when one is running.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#5556]
Issue Type: <b>Bug</b>

Run cells in a notebook and try to open another notebook and edit a cell. It'll not let you edit. 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (45.98GB free)|
|Process Argv|C:\Users\makoripa.REDMOND\Desktop\HERO001 - Create AKS cluster and deploy BDC 3.ipynb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kevcunnane** [comment]
Closing as no repro. If you can give more details please let us know.
