### ISSUE TITLE
MongoDB Support

### ISSUE THREAD

**Issue by janhoon** [microsoft/azuredatastudio#5558]
The only thin keeping me from using data studio for all my dat requirements is the the fact that I can't use to to query mongo/cosmos.

I can't find a tool with which I can query sql and mongo in one application, neither for free nor any open source solutions. Would give Data Studio a real edge as a tool in the arsenal of anyone that needs to work with both sql and mongo.

**Comment by gruckion** [comment]
I would to see this. For local and remote mongodb instances. This would be really nice.

**Comment by kramer1007** [comment]
This would be very helpful. +1

**Comment by sfg11** [comment]
@kburtram any update on Azure data studio + mongo db support?

**Comment by alanrenmsft** [comment]
There is an extension for COSMOS DB in Azure Data Studio: https://github.com/microsoft/azuredatastudio/issues/4916#issuecomment-1267512387.

Please open issue in the extension team's own repository for feature requests/bugs.
