### ISSUE TITLE
Server dashboard disappears when a Notebook cell is run and then closed

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#5559]
- Azure Data Studio Version: 1.8.0-insider

Steps to Reproduce:

1. Open a server dashboard and click on New Notebook task.
2. Create a code cell using the Click on **+ Code** or **+ Text** blue links at the top (Not the button).
3. Run the cell and close the tab (don't save if prompted).
4. Go back to the server dashboard.

Expected - The dashboard should be they way it was before
Actual - The widgets and tasks disappear

**Comment by kevcunnane** [comment]
@abist moved to Dashboard as this isn't a notebook issue.

**Comment by abist** [comment]
This is now fixed.
