### ISSUE TITLE
Unable to make toolbar reappear

### ISSUE THREAD

**Issue by joshua-ReadyPro** [microsoft/azuredatastudio#5560]
- Azure Data Studio Version: 1.7.0 (MacOS)

The toolbar with "Run" button has disappeared and I can't seem to get it back.  I'm confident this is %100 user error, but I cannot figure out how to toggle this for the life of me.

**Comment by kburtram** [comment]
Hmm, I haven't seen this before and am not sure what could happening.  Are there any errors in the "Help -> Developer Tools" Console?

In the worst case, you could delete the application cached state to get back to a "first launch" environment.  You would lose connection metadata, etc. unless you manually backup and restore those settings.  To try this you can run something like `rm -rf ~/Library/Application\ Support\azuredatastudio`.

**Comment by joshua-ReadyPro** [comment]
No errors, but nuking the cache did the trick. Thanks!
