### ISSUE TITLE
Make MESSAGES pane collapse completely

### ISSUE THREAD

**Issue by JohnyL** [microsoft/azuredatastudio#5572]
Please, make MESSAGES pane resizable so that I could collapse it totally! Now it takes half of my not so big notebook monitor, and that's irritating. This is the feature most asked - and nothing is done. Pity.

**Comment by kburtram** [comment]
@JohnyL we're tracking this bug with issue https://github.com/microsoft/azuredatastudio/issues/3177 and will address in an upcoming release.  Here is a copy\paste of a previous reply for this issue.

> snipped from https://github.com/microsoft/azuredatastudio/issues/5498
>if the query returns enough results to fill the available screen space then the resultgrid should be resizable to fill that space. If the query doesn't return enough results to fill the screen then the messages pane will occupy the available space. There is more discussion of this behavior in #3177. Please let me know if that doesn't address your question.

> I agree that the current behavior is confusing. We had a fix that collapsed the Message to the bottom even when the resultset didn't fill the available area, but that change had several side-effects and needed to be reverted. We're planning to move the Messages into its own tab soon, so we decided to wait for that change rather than try to correct the previous attempt at fixing this.

Hope that provides a bit of context on the current behavior.  I'll close this issue as a duplicate.  Thanks for logging the issue!
