### ISSUE TITLE
Messages window/constraint windows sizes

### ISSUE THREAD

**Issue by neslekkim** [microsoft/azuredatastudio#5573]
Issue Type: <b>Feature Request</b>

Is it possible to give the messages window a size, or preferably hide it as an tab behind results?, as of now, it seems to take more space on screen that it needs, and results grid is varying size/moving around, giving an unconsistent workflow, compares to ssms. (or other comparable tools, jetbrains datagrip etc)

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ShaneCourtrille** [comment]
The amount of "wasted" space in the tool is the main reason I haven't switched over to it.  SSMS uses the available space much more efficiently.

**Comment by kburtram** [comment]
@neslekkim we're tracking moving Messages to tab with https://github.com/microsoft/azuredatastudio/issues/4680 which will hopeful remove the need for this issue.  You may try the `"sql.messagesDefaultOpen": false` setting which will hide the messages section by default unless an error occurs.

**Comment by kburtram** [comment]
@ShaneCourtrille in the May release we reduced the default font sizes and spacing across the product.  Please log an issue if there is too much wasted space in the app outside the initial sizing of the Messages pane.  I'm actively trying to address the "wasted space" issue over the next couple releases.

**Comment by kburtram** [comment]
Messages has been moved into its own tab now.  Please let me know if there are any issues with the updated UX.  Thanks!
