### ISSUE TITLE
[Accessibility]A11y_ Azure Data Studio_ NewJobs_Keyboard:Keyboard focus is going to the non- interactive content after the "Notification tab".

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/azuredatastudio#5575]
Bug Description:
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Additional details:**
Tool name: Keyboard
MAS Number: MAS2.1.1

**Steps to Reproduce:**
1.Launch the Azure Data Studio application.
2.Enable the SQL server agent extension.
3.Naviagte to the connected server->Select the database->Navigate to the SQL agent tab.
4.Navigate to the Jobs tab->hit on the "New job" button using the tab key.
5.Use the next tab to navigate to the "New job" page.
6.Observe if the keyboard focus land to the "New job".

**Actual:**
Keyboard focus is going to the non- interactive content after the "Notification tab". keyboard focus goes to the blank content  
**Similar issue**
Similar issue is observed in the following List of pages:
1.Title :- Create operator
Navigation steps for the Create operator page.
1.Launch the Azure Data Studio application.
2.Enable the SQL server agent extension.
3.Naviagte to the connected server->Select the database->Navigate to the SQL agent tab.
4.Navigate to the Operators tab->hit on the "New operator" button using the tab key.
5.Use the next tab to navigate to the "Create operator" page.
6.Observe if the keyboard focus land to the "New operator"
**Similar issue has been Observed in the CreateAlert.** 
**Navigation path**
1.Go to the  SQL server agent tab->On alerts tab->Click on new alert button.

**Expected:**
 After the notifications tab, the keyboard focus should land to the "Name" textbox.
**Recommendations:**
Refer below link which is repository of bug fixes code snippets:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
keyboard only user will face difficulty while navigating within the page.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={8492c4eb-c179-40ae-8777-cd044ed725a2}
**Attachment for Reference:**
[5575_[Accessibility]A11y_ Azure Data Studio_ NewJobs_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3207439/5575_.Accessibility.A11y_.Azure.Data.Studio_.NewJobs_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by ChitrarupaSharma** [comment]
Verified the bug in App version:
Version: 1.9.0-insider (user setup)
Commit: a79f1ac830e3cb99130a21797a48d8db76fda4a0
Date: 2019-06-13T07:43:03.456Z
VS Code 1.34.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
Bug is fixed and does not repro.
