### ISSUE TITLE
Add a Stop button to stop a schema compare

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#5576]
Issue Type: <b>Feature Request</b>

On my machine at least, schema compare takes a few minutes or more to run. I just misclick and started a Compare. I then looked for a STOP button for the compare, but there was no STOP button clearly visible.

REPO
- start a compare
- Try to cancel it.

Azure Data Studio version: Azure Data Studio 1.7.0-insider (c7f5278430b9df35fb6e160a5b1cf4c653644efc, 2019-05-03T07:13:39.307Z)
OS version: Darwin x64 18.6.0

**Comment by udeeshagautam** [comment]
related : https://github.com/microsoft/azuredatastudio/issues/5275

**Comment by udeeshagautam** [comment]
Available in latest build. Closing to clean up July.
