### ISSUE TITLE
Not able to copy the cell value

### ISSUE THREAD

**Issue by manikantanet1988** [microsoft/azuredatastudio#5578]
Issue Type: <b>Bug</b>

Not able to copy a cell value when tried to use CTRL+C and there is no right click option

Azure Data Studio version: azuredatastudio 1.6.0 (eb35dae1d1238e03f1cab3bd45e151f381b22aef, 2019-04-17T07:11:15.944Z)
OS version: Windows_NT x64 10.0.17763

**Comment by abist** [comment]
Hi @manikantanet1988, thanks for reporting this issue. It's being tracked here already - https://github.com/microsoft/azuredatastudio/issues/5501 and hence I'm going to close this one as duplicate. Feel free to follow the discussion and updates on the bug on that thread.
