### ISSUE TITLE
Left-Right arrow in treeview should open/close tree

### ISSUE THREAD

**Issue by ststeiger** [microsoft/azuredatastudio#5579]
On the left-hand side treeview, I'd like to be able to **open/collapse folders with the left/right arrows** on the keyboard, like in SSMS.

Here:
[![Left Hand TreeView][1]][1]

  [1]: https://i.stack.imgur.com/Bt8n1.png

**Comment by kburtram** [comment]
@ststeiger this sounds like a reasonable suggestion.  I think you can accomplish the same behavior using the space key to toggle expand\collapse state.

**Comment by ststeiger** [comment]
@kburtram: Ah, interesting. Thanks, works for me in the meantime.

**Comment by wsmelton** [comment]
Use of the space key is not sufficient when you dealing with the stored procedure folder that has 200 objects. It requires you to still page all the way up before you can collapse the folder. The same ability that the file explorer view has for arrow key control should exists in the Server View....this functionality is present in SSMS.

An example of what can be done with files....just to visualize what I'd see the Server Pane having:
[vscode_example_key_file_collapsing.zip](https://github.com/microsoft/azuredatastudio/files/3677287/vscode_example_key_file_collapsing.zip)

**Comment by paulirwin** [comment]
+1 FYI, Enter also works but it's much more convenient to use the arrow keys so you don't have to either jump around the keyboard or use two hands.

**Comment by leonardder** [comment]
From an accessibility perspective, this is also a must have.
Note that in explorer, keyboard accessibility works as normal. Is there anything holding back from using the same underlying control?

**Comment by cheenamalhotra** [comment]
I believe this support is available in the latest ADS insiders version - targeted for May release.

**Comment by KeithWalters** [comment]
> I believe this support is available in the latest ADS insiders version - targeted for May release.

Meaning 1.44? Left/Right arrows still don't work for me

**Comment by cheenamalhotra** [comment]
Support is available in latest insiders, targeted for July release.
