### ISSUE TITLE
Pasting text into a string literal formats it as though it is SQL

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azuredatastudio#558]
- SQL Operations Studio Version: 0.24.1

1) Create a string literal into a query window (i.e. '')
2) Copy some text from another application (i.e. From should not be converted. null should not be  converted.)
3) Now paste the copied text inside the string literal

The text is reformatted as though it is SQL. For example from, not and null become FROM, NOT, NULL if you have the option to uppercase keywords.

Pasting text into a string literal (or some other constructs like comments) should not auto-format the text. Note that this assumes you have the option to format on paste enabled. 

The only workaround I've found so far is to use SSMS to do these kinds of changes.

**Comment by kburtram** [comment]
This bug doesn't appear to reproduce on the latest build.  Please let us know if this is still impacting you.  Thanks!
