### ISSUE TITLE
sqlcreateTable snippet registers an error

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#5585]
Steps to Reproduce:

1. use the sqlCreateTable snippet against a azure database
2. get the following errors 
![image](https://user-images.githubusercontent.com/4324725/58214976-9f479b00-7cac-11e9-9123-53ae73a9cb05.png)

It still seems to work but with errors.

**Comment by kburtram** [comment]
@anthonydresser I'm not seeing this issue.  It looks like the `create` string was removed when the snippet was expanded.  Did you tab-complete the suggestion?  Or complete the suggestion a different way?

**Comment by anthonydresser** [comment]
I did it again and it didn't repro, it might have been something there originally.
