### ISSUE TITLE
Support other types of databases

### ISSUE THREAD

**Issue by atrauzzi** [Microsoft/azuredatastudio#56]
Primarily postgres (with GIS extensions), redis, azure cosmos and mariadb.

---
# STOP!
### Want your favourite database supported??

 - **Click the 👍 icon**
 - Wait
 - Please **do not** add a comment with _"+1"_ in the message!

_I repeat_, please just upvote this initial problem-description. **Do not add a comment as it's harder for the maintainers to track and +1 comments create clutter for any detailed discussion.**

**CLICK THIS!!**
👇

**Comment by carwyn** [comment]
SQLite would be good too.

**Comment by nurettin** [comment]
This would be great for some folks who still use informix.

**Comment by VaclavElias** [comment]
I was about to open this suggestion.
+1 MySQL / MariaDb, +1 PostgreSQL

**Comment by chrisramakers** [comment]
+1 postgres

**Comment by irufus** [comment]
Isn't that out of scope?

**Comment by mikeball** [comment]
+1 postgres

**Comment by IvanPudev** [comment]
+1 postgres

**Comment by pedrozoalencar** [comment]
+1 DB2

**Comment by atrauzzi** [comment]
@irufus - Based on community interest, nope!  And it shouldn't be.

**Comment by Raymonf** [comment]
@irufus Well, the program is called "SQL Operations Studio", not "SQL Server Operations Studio".

**Comment by b5n** [comment]
It makes sense to support Sqlite due to dotnet core. MySql and Postgres support will bolster both Azure DB and sqlops adoption.

**Comment by welkie** [comment]
+1 Postgres

PgAdmin4 is awful. I was thinking of learning Electron just to try starting a better cross platform Postgres tool.

**Comment by atrauzzi** [comment]
@welkie - Totally agree. And the only alternative on Windows is DataGrip by JetBrains.  Still leaves me wanting for something prettier and more direct.

**Comment by alfeg** [comment]
+1 for postgres

@welkie there is awesome dbeaver app to manage

**Comment by insinfo** [comment]
+1 postgres

**Comment by szabolcsx** [comment]
Have my vote for PostgreSQL!

**Comment by AlexTroshkin** [comment]
+1 postgres

**Comment by carwyn** [comment]
Convention on Github seems to be to add a thumbs up rather than a +1 as it created less clutter and less email.

**Comment by welkie** [comment]
@carwyn True

I added a thumbs up to the original post which mentioned MySQL and Postgres instead. Will delete my posts in this thread shortly.

**Comment by MikeElghali** [comment]
+1 MySQL

**Comment by insinfo** [comment]
@b5n  @welkie @atrauzzi @atrauzzi  I totally agree, you took the words out of my mouth.

**Comment by hugufc** [comment]
+1 postgres

**Comment by kokes** [comment]
It's been said, but it apparently needs repeating. Please stop with all that "+1". Use thumbs up/down emojis to express (dis)agreement and stop flooding what's supposed to be an issue tracker. 

Thank you.

**Comment by fellow99** [comment]
+1 mysql

**Comment by maglianim** [comment]
+1 postgres

**Comment by outwitevil** [comment]
+1 postgres

**Comment by willembressers** [comment]
DB2

**Comment by KISSMonX** [comment]
666, 希望支持 MySQL 和 PostgreSQL,  sqlite3 也不错.

**Comment by styfle** [comment]
### Want your favorite database supported??

1. Click here: https://github.com/Microsoft/sqlopsstudio/issues/56#issue-274488474
2. Click the :+1: icon.
3. Wait.

Why? Because https://github.com/Microsoft/sqlopsstudio/issues/56#issuecomment-345460923 and https://github.com/Microsoft/sqlopsstudio/issues/56#issuecomment-345786041

**Comment by sjvcdev** [comment]
+1 @styfle

**Comment by b5n** [comment]
+1 @styfle

**Comment by sjvcdev** [comment]
+1 @styfle

**Comment by talley** [comment]
+1 postgres

**Comment by talley** [comment]
+1 MongoDB

**Comment by eajardini** [comment]
+1 Postgres

**Comment by netroby** [comment]
+mysql

**Comment by gatspy** [comment]
+1 postgres
+1 mysql
+1 sqlite
+1 mongo

**Comment by bystro** [comment]
+1 mysql

**Comment by MathRobin** [comment]
@bystro why not just click on icon : +1 instead of commenting again and again for the same thing... And spamming everybody

**Comment by VaclavElias** [comment]
I guess many guys are not simply aware of that feature / "policy" / good practise / convention and they are not doing it on purpose.

Maybe @atrauzzi  could update his initial post with @styfle reworded comment? Maybe that would reduce a few emails?

**Comment by carwyn** [comment]
The issue could probably be locked now as I think the point has been made.

**Comment by atrauzzi** [comment]
@VaclavElias - Done.
@carwyn  - I prefer not to see issues locked as it silences the opportunity for any potentially good points.

**Comment by VaclavElias** [comment]
@atrauzzi great and nicely reworded, let's see what fish will slip through the net :)

**Comment by JiyongShi** [comment]
+1 mysql

**Comment by carloshm** [comment]
Multi Database Support (No-SQL, SQL, Graph, etc.), I would recommend to talk to Cosmos DB team for sharing multi-model api support
o	https://docs.microsoft.com/en-us/azure/cosmos-db/mongodb-introduction
o	https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-introduction
o	https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction
o	https://docs.microsoft.com/en-us/azure/cosmos-db/graph-introduction
o	https://docs.microsoft.com/en-us/azure/cosmos-db/cassandra-introduction

**Comment by LiceRewis** [comment]
Oracle support would be super useful at work right now...

**Comment by southsparrow** [comment]
Firebird!

**Comment by stephanebarbey** [comment]
+1 PostgreSQL

**Comment by drowa** [comment]
I think a fork for each system would be more appropriate.

- SQL Operations Studio for SQL Server
- SQL Operations Studio for SQLLite
- SQL Operations Studio for DB2
- SQL Operations Studio for Oracle
- SQL Operations Studio for MySQL
- SQL Operations Studio for PostgreSQL
- etc.

In this way experts of each system don't need to worry about other systems.

**Comment by L0stLink** [comment]
I disagree with the idea of having forks for different flavors of SQL, this should be a X-platform database management tool which supports multiple SQL dialects. Forking will not only fragment and divide the community around this product, but will also take away its somewhat unique selling point, their is also the added complexity of maintaining feature parity between all the forks with the divided development force.

**Comment by thecotne** [comment]
@drowa so you think there should be

sublime text for html
sublime text for css
sublime text for php
sublime text for javascript
sublime text for python
sublime text for sql
sublime text for plain text 🤣 

and not one sublime text with support for many languages

**Comment by L0stLink** [comment]
If support for different SQL dialects is implemented through extensions contributed by the community and/or the sqlops team, the modularity can still be maintained without the need of forking the entire code base. In my opinion, this is a 'best of both worlds' solution and vscode is proof that such a solution can be successful. I am quite sure that this is the direction the team is taking.

**Comment by DrSensor** [comment]
I wonder why not just load JDBC driver for each SQL based database?

> also is there a need for something like language-server-protocol? Maybe dblang-server-protocol?

**Comment by drowa** [comment]
@thecotne: you are comparing apples and oranges.

Take a look on how many dialog boxes SSMS has.

**Comment by atrauzzi** [comment]
@drowa - What you're suggesting ends up being frustrating.  There's no reason to assume that a combination of all the dialects would be confusing.  You can simply choose a mode if it's even applicable.  DataGrip does this and it works just fine.

**Comment by chandusekhar** [comment]
+1 Oracle

**Comment by brunocerecetto** [comment]
+1 mysql

**Comment by LoungeFlyZ** [comment]
I used the private preview of this tool prior to it changing names/repos and back then it supported Postgres out of the box. I also heard that it was going to be pluggable to enable other data sources. 

Did the stance on this change due to corporate politics? or did it just get removed for the time being until work can be done to support it better?

**Comment by atrauzzi** [comment]
# STOP!
### Are you here to show your interest in having a variety of database back ends supported?

**GREAT!**

 - Scroll to the top of this issue to the initial problem description.
 - **Click the 👍 icon**
 - Wait
 - Please **do not** add a comment with _"+1"_ in the message!

# STOP!
# Don't post a _"+1"_ comment!

**Comment by welkie** [comment]
Why don't we lock this issue? People visiting will still be able to see the original post, and they're get a chance to thumbs-up it.

**Comment by styfle** [comment]
@welkie Unfortunately, locking the thread also locks the reaction emojis too 😞 

We should delete these 2 comments so that @atrauzzi is the last comment in this thread 😄

**Comment by regs01** [comment]
FirebirdSQL would be good to be listed as well

**Comment by VaclavElias** [comment]
Is it art of reading or art of seeing? 

:)

**Comment by regs01** [comment]
> Is it art of reading or art of seeing?
sure, i went down all the thread and it wasn't mentioned, so it's not +1

**Comment by atrauzzi** [comment]
# STOP!
### Are you here to show your interest in having a variety of database back ends supported?

**GREAT!**

 - Scroll to the top of this issue to the initial problem description.
 - **Click the 👍 icon**
 - Wait
 - Please **do not** add a comment with _"+1"_ in the message!

# STOP!
# Don't post a _"+1"_ comment!

**Comment by yhvicey** [comment]
Can this feature achieved by extensions? So you can enjoy light-weight and flexibility at the same time.

**Comment by traceless0929** [comment]
+1 MySQL

**Comment by ringods** [comment]
Dear SQLOpsStudio Team,

Can you please install this Github app to prevent the `+1` reactions?
https://github.com/apps/reaction

**Comment by atrauzzi** [comment]
# STOP!
### Are you here to show your interest in having a variety of database back ends supported?

**GREAT!**

 - Scroll to the top of this issue to the initial problem description.
 - **Click the 👍 icon**
 - Wait
 - Please **do not** add a comment with _"+1"_ in the message!

# STOP!
# Don't post a _"+1"_ comment!

**Comment by thomaslevesque** [comment]
Why just relational databases? Why not CosmosDB, Mongo... ?
Frankly, from the name "Azure Data Studio", I would definitely have expected CosmosDB to be supported.

**Comment by yualan** [comment]
Welcome to Postgres! :)

Help us retweet: https://twitter.com/AzureDataStudio/status/1107726496213327872 
Azure Blog: https://azure.microsoft.com/en-us/blog/azure-data-studio-an-open-source-gui-editor-for-postgres/
SQL Server Blog: https://cloudblogs.microsoft.com/sqlserver/2019/03/18/the-march-release-of-azure-data-studio-is-now-available/

**Comment by netroby** [comment]
@yualan Dear sir, would you please add mysql/mariadb support for us ? nice to see postgres, but mysql was more popular and use widely .

**Comment by rushton3179** [comment]
Is anyone looking into doing an oracle extension? We use oracle and mssql at work so I might look into this if someone has started work on it. Considering there is prior art now in the posgres extension I would follow the pattern that sets.

**Comment by yualan** [comment]
Hi Everyone, thank you for contributing to our #1 most requested feature by far for Azure Data Studio. Love seeing the engagement in this thread.

Now that PostgreSQL support is in Azure Data Studio, we are now a multi-database tool. Thus, we plan to close this issue and re-open individual tracking issues for each database request.

Please upvote the following issues:
- [MySQL](https://github.com/Microsoft/azuredatastudio/issues/4904)
- [SQLite](https://github.com/Microsoft/azuredatastudio/issues/4903)
- MariaDB
- Azure Cosmos DB
- MongoDB

I will close this issue by the end of this week and update this comment with the the appropriate official tracking issues. 

If you would like to request a new DB, please add [Database Support] to the front of the issue. I will choose the main tracking issue to help consolidate. Once the official issue is up, feel free to advocate community to upvote.

**Comment by thomaslevesque** [comment]
@yualan thanks. I created the [issue for Cosmos DB](https://github.com/Microsoft/azuredatastudio/issues/4916), could you please add the link in your comment?

**Comment by anubischpc** [comment]
Oracle! +1

**Comment by atrauzzi** [comment]
# STOP!
### Are you here to show your interest in having a specific database back end supported?

**GREAT!**

This issue is closed now and has been replaced by individual ones for each type of DB desired!

 - Find the link to the github issue for DB you want supported
 - Go to it
 - **Click the 👍 icon on the original dsecription**
 - Wait
 - **Do not** add a comment with _"+1"_ in the message!

---

 - [Redis](https://github.com/Microsoft/azuredatastudio/issues/4918)
 - [MariaDB](https://github.com/Microsoft/azuredatastudio/issues/4917)
 - [Azure Cosmos DB](https://github.com/Microsoft/azuredatastudio/issues/4916)
 - [VistaDB](https://github.com/Microsoft/azuredatastudio/issues/4911)
 - [SQLite](https://github.com/Microsoft/azuredatastudio/issues/4903)
 - [MySQL](https://github.com/Microsoft/azuredatastudio/issues/4904)

---

# STOP!
# This issue is dead!

**Comment by kburtram** [comment]
I'll lock the conversation on this issue now.  Please see @atrauzzi's comment above with links to specific relational database types that can be individually upvoted.  Thanks for all the great feedback.
