### ISSUE TITLE
locked connection

### ISSUE THREAD

**Issue by elvysmarcos** [microsoft/azuredatastudio#5606]
Issue Type: <b>Bug</b>

many times when executing the query, the window connects and hangs and we have no return. to test open the sql management studio and the connection is working normally

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600U CPU @ 2.10GHz (4 x 2694)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.91GB (2.81GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0
sql-search|Red|0.3.3

</details>

**Comment by joshbooker** [comment]
related:
https://github.com/microsoft/azuredatastudio/issues/2694
https://github.com/microsoft/azuredatastudio/issues/3868
https://github.com/microsoft/azuredatastudio/issues/3627
https://github.com/microsoft/azuredatastudio/issues/3653

**Comment by fwd079** [comment]
Is it released yet? 

During a demo, this made my selling the idea of Data Studio instead of SSMS etc. fall flat. lol

**Comment by kburtram** [comment]
Closing older issues.  There are several related issues that we are tracking.  We've also pushed numerous related query editor perf fixes that hopefully have helped with this scenario.  Thanks!
