### ISSUE TITLE
Use DisposableStore

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#5610]
Vscode implemented a new class that replaces the need for an array of disposables https://github.com/microsoft/vscode/commit/3d5ce6be5ef8a770a8ecb1b1898e6609dacbb524 we would slowly migrate to using that in all cases that we are using array of disposables. (But also extend Disposable Class for places where that makes sense).

**Comment by kburtram** [comment]
Closing older engineering-focused tasks.
