### ISSUE TITLE
SOURCE CONTROL: GIT - ISSUES 

### ISSUE THREAD

**Issue by MAL-** [microsoft/azuredatastudio#5625]
Issue Type: <b>Bug</b>

I just can't demap, remap, do nothing with Source Control: GIT... how can i reconfigure this??? There's nothing in options.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 6.3.9600

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|6.00GB (0.70GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
managed-instance-dashboard|joc|0.3.0
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.1
sql-search|Red|0.3.3

</details>

**Comment by kburtram** [comment]
@MAL- I'm not clear what's the issue describing.  What do you mean by "demap" and "remap"?  

Are you experiencing the same problem in VS Code?  We haven't customized the experience at all from what we pick-up from upstream, AFAIK.
