### ISSUE TITLE
Backup form broken

### ISSUE THREAD

**Issue by chaim1221** [microsoft/azuredatastudio#5628]
- Azure Data Studio Version:

1.7.0 Mac OS X Mojave

Steps to Reproduce:

1. Open Azure Data Studio.
2. Connect to an Azure SQL Server database.
3. Click on Backup.

Form has the following issues:

![image](https://user-images.githubusercontent.com/3819970/58346378-9a4f2c80-7e0f-11e9-836f-9ff94bb7dedf.png)

a. Cannot select `Backup type`
b. `Script` and `Backup` buttons are greyed out but there are no validation messages on the form (until after you have successfully added a source, below).
c. You can get the Backup and Scripts buttons to show by adding a backup file and name manually (click past the error, specify a path)... the validation message does not show until you remove all the backup paths you have selected... but when you click Backup, nothing happens.

https://twitter.com/vickyharp/status/1131431330242211840

**Comment by chaim1221** [comment]
Dear bot,

There are some issues here that aren't addressed by #4572 but it's definitely related.

**Comment by udeeshagautam** [comment]
@chaim1221 thanks for reporting the issue. Backup for Azure SQL DB isn't supported inside of Azure Data Studio. From ADS version 1.6 onwards the context menu item for backup on Azure SQL Databases is removed. Can you please let us know if you are still seeing backup option in Azure Database context menu using latest Azure Data Studio or if you started backup using some other entry point?

(If you want to backup your Azure SQL DB instance we recommend using the Azure Portal.)

**Comment by kburtram** [comment]
@udeeshagautam I think the intended design is we don't show backup\restore menu items for Azure SQL DB connections.  There should be a when clause `!isCloud`, or something like that, to support hiding these items in that context.

**Comment by udeeshagautam** [comment]
@kburtram yes we added that in March (https://github.com/microsoft/azuredatastudio/pull/4498) and I dont see the option to backup for Azure in latest ADS. That is why I would like mpore infor on how user was able to reach the backup dialog for Azure db. 

here is how it shows in latest ADS
![image](https://user-images.githubusercontent.com/46980425/58656006-4ab9a680-82d0-11e9-9a3d-9b6507cf24b7.png)

![image](https://user-images.githubusercontent.com/46980425/58656035-5c02b300-82d0-11e9-86fe-205d093b0473.png)

**Comment by kburtram** [comment]
@udeeshagautam I was able to get into the backup dialog with the following.  Though I'm not sure this is how the user got into the dialog.

1. Connect to a Azure DB instance
2. Open the Manage page to the DB
3. Run `Backup` from the Command Palette

Expected: Error message such as "Azure DB isn't supported..."

Actual: Dialog displays in a broken state.

![image](https://user-images.githubusercontent.com/599935/58657101-6cb42880-82d2-11e9-9f67-91b4d7772532.png)

**Comment by udeeshagautam** [comment]
@kburtram ah thanks for the repro! I will remove the more info for this and work on closing this entry. Do you know of other entry point that I am missing here?

**Comment by udeeshagautam** [comment]
This is doable in June so moving back. Will send a PR today.
