### ISSUE TITLE
Connecting to an offline CMS registered server leaves node spinning forever

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5641]
- Azure Data Studio Version:

Steps to Reproduce: `master`

1.  Connect to a CMS server that contains a registration for an offline server
2. Try to expand the offline server

Expected: Server times-out with an error.

Actual: Node spins indefinitely and the CMS server node expand\collapse stops working

> Note sqltools300 is offline

![image](https://user-images.githubusercontent.com/599935/58361294-65a89880-7e42-11e9-8b08-d9a0c54794a7.png)

**Comment by abist** [comment]
This is fixed.
