### ISSUE TITLE
Dialog back button broken by custom menu bar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5642]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Connection Dialog and the Advanced Options Dialog
2. Click the "Back" button arrow

Expected: Advanced dialog is dismissed

Actual: Advanced dialog is not dismissed.  It appears the click is being captured by the custom menu bar.

![image](https://user-images.githubusercontent.com/599935/58361451-bc62a200-7e43-11e9-9530-5d795a06cc34.png)

**Comment by kburtram** [comment]
@anthonydresser this appears to be a regression related to enabling the custom menu bar.  Could you please take a look?

**Comment by anthonydresser** [comment]
I see the problem, should be a simple fix
