### ISSUE TITLE
Custom menu bar can obscure document tab bar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5644]
- Azure Data Studio Version: `master`

I don't have a consistent repro yet.  But after running through normal usage for ~15 minutes I noticed the below bug.  The menu bar should never obscure the document tab bar.

![image](https://user-images.githubusercontent.com/599935/58361921-b4f0c800-7e46-11e9-8da1-07721a407146.png)

**Comment by anthonydresser** [comment]
We don't do anything special here. If this is an actual repro, this should repro on vscode.
