### ISSUE TITLE
US Gov Azure SQL Database Connection

### ISSUE THREAD

**Issue by boosts** [microsoft/azuredatastudio#5647]
Issue Type: <b>Feature Request</b>

Unfortunately, there doesn't seem to be a way to setup a connection to an Azure SQL Database hosted on a GOV region (such as US Gov Virginia) using Azure Active Directory with MFA.

I see that the option exists for the commercial regions, but it would great if you could also add it for the Gov regions.

Thank you

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
@boosts thanks for reporting this bug!  We're tracking in issue https://github.com/microsoft/azuredatastudio/issues/3013.  I believe we need to have this access provisioned for ADS prior to enabling this functionality.
