### ISSUE TITLE
Scroll and Zoom Can't Reset

### ISSUE THREAD

**Issue by datauduong** [microsoft/azuredatastudio#5652]
Issue Type: <b>Bug</b>

When I use Scroll and Zoom, the Text font size changed. But it also affecting the Result Grid and Message Pane.

I try to use the Reset Zoom (Ctrl + 0 or Manually Select from Menu), but the Result Grid and The Message Pane is not back to normal.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2697 v3 @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|16.00GB (7.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5

</details>

**Comment by kburtram** [comment]
@datauduong I'm not able to repro this on the latest insiders build.  Please let me know if the issue persists on current builds, or there are additional repro steps that would help narrow down the issue.  Thanks!
