### ISSUE TITLE
Registered Servers Nested Folder Support

### ISSUE THREAD

**Issue by jasonhorner** [microsoft/azuredatastudio#5653]
I would like to be able to use nested folders from within Connections U/I. 

It should work similar to existing functionality in SSMS:
![image](https://user-images.githubusercontent.com/7981510/58378364-9aeedc80-7f4f-11e9-8e51-7900814ff7b0.png)

This is important because it helps provide better organization to groups of servers

**Comment by kburtram** [comment]
@jasonhorner this is supported by using the `/` character in the server group name, e.g., `group1/group2/group3`.  We haven't surfaced in the UI yet since there are some open discussions with our UX team regarding this functionality.  Please let me know if this doesn't address your suggestion.
