### ISSUE TITLE
it's too slow to get results

### ISSUE THREAD

**Issue by jingcsdn** [microsoft/azuredatastudio#5656]
Issue Type: <b>Bug</b>

 too many fields or results, need long time to display

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: unavailable_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: unavailable_off|
|Load (avg)|undefined|
|Memory (System)|7.91GB (3.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Closing older issues.  We have several related issues such as https://github.com/microsoft/azuredatastudio/issues/5477, https://github.com/microsoft/azuredatastudio/issues/304, or https://github.com/microsoft/azuredatastudio/issues/1119 that we are tracking for investigation.  Thanks!
