### ISSUE TITLE
Copy & Paste in Profiler Extension

### ISSUE THREAD

**Issue by wlouwster** [microsoft/azuredatastudio#5667]
Issue Type: <b>Bug</b>

Cannot copy and paste SQL Profiler Results

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.75GB (16.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alanrenmsft** [comment]
@wlouwster Thanks for submitting the issue, I have fixed the issue, you should be able to copy content from the tables in profiler in next ADS release.
