### ISSUE TITLE
Restore from Amazon S3 bucket doesn't work, prepends "D:\RDSDBDATA\BACKUP\"

### ISSUE THREAD

**Issue by craigdetter** [microsoft/azuredatastudio#567]
- SQL Operations Studio Version:
Version 0.25.4 (0.25.4)
on MAC OSX High Sierra

Steps to Reproduce:
run this:

DECLARE @path as nvarchar(max) = 'arn:aws:s3:::com.mydomain.main/db.bak'

RESTORE HEADERONLY   
    FROM DISK = @path
    WITH NOUNLOAD;
GO

Started executing query at Line 1
Msg 3201, Level 16, State 2, Line 3
Cannot open backup device 'D:\RDSDBDATA\BACKUP\arn:aws:s3:::com.mydomain.main/db.bak'. Operating system error 123(The filename, directory name, or volume label syntax is incorrect.). 
Msg 3013, Level 16, State 1, Line 3
RESTORE HEADERONLY is terminating abnormally. 
Total execution time: 00:00:00.051

**Comment by kburtram** [comment]
Closing out older issues.  Please let us know if you're still impacting by this bug.  Thanks!
