### ISSUE TITLE
Syntax highlighting breaks in messages pan after error occurs.

### ISSUE THREAD

**Issue by philcart** [microsoft/azuredatastudio#568]
![sqlops_message_highlighting](https://user-images.githubusercontent.com/4084083/35487631-ed5fd4c8-04d1-11e8-9a44-aebd1b2d7d38.png)
- SQL Operations Studio Version: sqlops 0.25.4 (8095643ed4421fbe5d713883b06bdac07a0dd01d, 2018-01-13T00:10:17.197Z)
- OS Version: Windows_NT x64 10.0.15063
---

We have a stored procedure that is used to drive a data synchronisation process. It executes a certain stored procedure with different parameters. The procedure being called, could be called 10-80 times depending on the data to synchronise.

Both procedures print progress messages using RAISERROR with severity 10. 
```
SET @msg = CONVERT(varchar(20),GETDATE(),120) + '' Captured update/insert data'';
RAISERROR(@msg, 10, 1) WITH NOWAIT;
```

In SQL Management Studio, this produces a list of progress messages. If there are any errors, the errors are highlighted red, but all other messages have the standard black on white formatting.

In SQL Operation Studio, when an error occurs, the error and each subsequent progress message is highlighted as an error (see attached)

Steps to Reproduce:
1. Execute long running procedure that issues messages via RAISERROR('msg',10,1) WITH NOWAIT
2. Introduce error that interrupts processing

Cheers
Phil

**Comment by kburtram** [comment]
Closing out older issues.  I know we did some updates to the message window a while back (after this bug was filed).  It is possible the bug is resolved on the latest build.  Please let us know if this issue is still impacting you.  Thanks!
