### ISSUE TITLE
Cannot edit in read-only editor SQL files

### ISSUE THREAD

**Issue by Ungerfall** [microsoft/azuredatastudio#5684]
- Azure Data Studio Version:
Version: 1.8.0-insider (user setup)
Commit: 3e8f25d8642c9560f6296d97bde2b164aedf25df
Date: 2019-05-27T07:46:13.508Z
VS Code 1.33.1
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Open .sql file
2. Try edit
3. ![image](https://user-images.githubusercontent.com/8143895/58474001-1375b900-815b-11e9-9475-b85062ee166b.png)

Things I tried:
1. Reload with window with extensions disabled
2. Other than .sql files are able to edit

**Comment by wandoschneider** [comment]
Same thing here. Started in the friday (05/24/2019) release, I think.

Version: 1.8.0-insider (user setup)
Commit: 3e8f25d8642c9560f6296d97bde2b164aedf25df
Date: 2019-05-27T07:46:13.508Z
VS Code 1.33.1
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by nikonso** [comment]
Still present in the new insiders release

```
Version: 1.8.0-insider (system setup)
Commit: 9a55ca3021f088a0781bf57070993bc2198de7e0
Date: 2019-05-29T07:42:26.310Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134
```
It's really annoying to have to copy the contents of the file to a new tab in order to perform modifications to the original script content....

**Comment by anthonydresser** [comment]
We'll have a fix out for this today.
