### ISSUE TITLE
Tab connection timeouts

### ISSUE THREAD

**Issue by SanderSade** [microsoft/azuredatastudio#5686]
Issue Type: <b>Bug</b>

Once tab connection expires/timeouts, it is impossible to restore the tab to normal state. Cancel (if query is trying to run) does nothing, Disconnect/reconnect doesn't help, Change connection doesn't work as well.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (4 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (17.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.7.0
profiler|Mic|0.7.0
server-report|Mic|0.1.5

</details>

**Comment by cheenamalhotra** [comment]
Tracking same issue with #20385, closing this as duplicate.
