### ISSUE TITLE
Add Control-R close Message Status like in SSMS

### ISSUE THREAD

**Issue by 2axDeveloper** [microsoft/azuredatastudio#5687]
there is no way to hide the messages panel on the bottom like in SSMS (control-R). This is a real pain.  ADS should be consistent as with SSMS in order to hide/display the message pane.

Steps to Reproduce:

1.  run a query
2.  press Control-R to remove the messages/results pane and view only code

**Comment by kburtram** [comment]
@2axDeveloper have you tried the `Toggle Query Results` command?  I think this should do the same thing as `Ctrl-R` in SSMS.

The default shortcut is `Windows-Shift-R` but can be remapped with the `File->Preferences->Keyboard Shortcut` UI.  Also, there is a "SSMS Keymap" extension in the Extension Manager that brings over a lot of SSMS keyboard shortcuts including the `Ctrl-R` mapping.

**Comment by 2axDeveloper** [comment]
thanks for the tip.  I wish the keyboard remapping wasn't even necessary  :^)

**Comment by kburtram** [comment]
@2axDeveloper thanks for the feedback.  I'm not sure exactly why this particular command has been mapped the way it is.  Typically it has to do with conflicts with existing VS Code shortcuts (it looks like Ctrl-R has 3 additional default mappings already).  @anthonydresser or @yualan do recall discussing this particular keymapping?

We're actively looking at how to improve the experience for users coming to ADS from SSMS.  Perhaps we can include the "SSMS Keymap" in the "Admin Pack for SQL Server" extension.  I'll close this issue based on the above workaround.  Please let me know if there is anything else related to this issue.

**Comment by anthonydresser** [comment]
Ctrl+R is a vscode default keybind.

**Comment by 2axDeveloper** [comment]
thanks Karl.  as a c# developer too, my first thought is to have ADS context sensitive as to the filetype (.SQL, or .cs, etc...  If you're using a .sql filetype, the keyboard mapping would logically be different than a VS dev - .cs, or .py, etc...  .  So ultimately, the problem is trying to have one tool do all, and be as close to previous environments as possible.  myself, I use VS or VS code for c#, not ADS.  and visa versa for .sql.  I think most database people will desire the SSMS keyboard layout.   That being said, I can see how a context sensitive key-mapper could get messy real quick

**Comment by kburtram** [comment]
Thanks for the additional context.  We're working through a "Professional DBA" scenario review over the next several weeks.  I'll add this item to be reviewed in that context to see if there's anything we can do to improve the default keymap.

I know in Visual Studio we used to have a 1st launch dialog that asked users to select which type of developer they were "C++, C#, VB, etc." and customized the environment a bit based on the selection.  Though most people ended up selecting General.

**Comment by 2axDeveloper** [comment]
I'm thinking outloud, maybe you could have a file, preferences, "keymapping theme", then select DBA/DBE, developer, python dev, etc... environment keymapping.  So in literally a few clicks, you'd get all what you want.  Color theme is there, so keymapping theme would be right next to it.  One drawback of the standard keymapping preferences now is it's overwhelming.  There are (it seems) like hundreds of options, and it's too much to wade thru.. Does that make sense?
