### ISSUE TITLE
Don't prompt for save when I close a blank doc

### ISSUE THREAD

**Issue by andrejpk** [microsoft/azuredatastudio#5688]
Issue Type: <b>Bug</b>

Screenshot: https://snag.gy/msgSW3.jpg 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.18898

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz (8 x 3999)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.96GB (12.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.38.0
azuredatastudio-postgresql|Mic|0.1.0
dacpac|Mic|0.2.0
import|Mic|0.7.0
profiler|Mic|0.7.0

</details>

**Comment by kburtram** [comment]
@andrejpk I'm not encountering the same behavior.  Do you have specific repro steps?  I'm trying the following:

1. Open a blank document with Ctrl-N or `New Query` menu item
2. Close the document

**Comment by andrejpk** [comment]
Hi @kburtram , this happened after my computer restarted so when I reopened Data Studio, I had a lot of blank documents open. (I'm not sure exactly why). Every time I tried to close one to clean it up, I got this prompt. (There was nothing to save.)

**Comment by kburtram** [comment]
This sounds like a side-effect of https://github.com/microsoft/azuredatastudio/issues/4964.  We shouldn't be prompting to save unmodified files in the normal use case.  Please let me know if that is not the case. I'll close for now to track the underlying problem with the other issue.  Thanks for reporting!
