### ISSUE TITLE
Titlebar application icon is incorrect

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5689]
- Azure Data Studio Version: `master`

Today's insider build is using the generic Dev icon.  Incorrect branding will prevent us from being able to ship the June release so we should resolve this week.

![image](https://user-images.githubusercontent.com/599935/58500261-a6e8c300-8136-11e9-8cfd-a1e71a66856b.png)

**Comment by anthonydresser** [comment]
dupe #5603
