### ISSUE TITLE
Feature Request: Enhanced Grid 

### ISSUE THREAD

**Issue by coreywebber** [microsoft/azuredatastudio#569]
The results grid needs to be more friendly post query. Having the ability to Sort, Filter, Rearrange, and Show/Hide Columns is useful anyone querying in production, and trying to reduce my impact.

**Comment by kburtram** [comment]
Here are some additional suggestions from https://github.com/Microsoft/azuredatastudio/issues/3591

"Issue Type: Feature Request

As a data analyst i would be highly useful to make the results grid more interactive.

Allow Column Sorting
Allow Column Filtering (Think Excel)
All user to select a column to remove (I dont need that after all)
Allow Aggregation of Results, that are only client side and dont effect the sql query.
4.1 Allow user to click a column and select SUM, COUNT, AVG, etc... and see the results at the bottom of the results
4.2 Allow user to move column to "top" of results grid, resulting in a "group by'ing" of the results
Azure Data Studio version: azuredatastudio 1.2.4 (1ebfd02, 2018-11-02T21:50:52.634Z)
OS version: Windows_NT x64 10.0.15063"

**Comment by NoGRo** [comment]
Hi. I was about to suggest these features, and I found the issue, it would be great to have it, it is the only reason I used the Oracle client. thanks for everything.

**Comment by Eggy1968** [comment]
This would be very useful for me as I often have to analyse data outside of normal user tools. I used this feature in an old product called Apex SQL Edit years ago before they canned the product.

**Comment by sm1810** [comment]
It would also be great to highlight the entire result row whenever any cell is clicked in result grid. This will be very useful if you have too many columns and scroll.

**Comment by Daemach** [comment]
And sorting/filtering should change the SQL in the editor - fast way to build queries.

**Comment by kburtram** [comment]
Closing based on #14589.  Please open specific issues for any additional results grid suggestions you may have.  Thanks!
