### ISSUE TITLE
Query Results section isn't initially sized correctly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5700]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query

Expected: The results section is sized appropriately in relation to the text editor based on the size of the application window.

Actual: The results section is too small.

Note: There was code that previously used a reasonable heuristic to determine the correct proportions that appears to have been lost in the custom sash refactor.

> In the below screenshot I would expect the results to be sized around where I placed the line.

![image](https://user-images.githubusercontent.com/599935/58513462-626c2000-8154-11e9-95e5-00fbb7c7fdf6.png)

**Comment by anthonydresser** [comment]
I'm not seeing any logic previously around sizing the grid, it is always a the same size regardless of the editor size
![image](https://user-images.githubusercontent.com/4324725/58593255-408b9f80-821f-11e9-9d1a-b160c4d37dcf.png)

**Comment by anthonydresser** [comment]
We could add this, but this would be new behavior and we should probably work with pm/ui to determine what the best approach here is.

**Comment by kburtram** [comment]
@anthonydresser in the screenshot you provided it doesn't appear that there is a 50%\50% split between the results and the text editor.  So unless I'm missing something it seems the behavior has changed.  In any case, let's discuss in our committer sync this Friday.

**Comment by kburtram** [comment]
For context here is default sizing for May vs. today's insiders build on my laptop.  The behavioral change is even more noticeable on a higher screen resolution.  We'll need to restore the behavior to something more similar to May's behavior for the June release.  Though I think the proportions in my PR are making the results section too large.

<img width="1277" alt="Screen Shot 2019-05-29 at 6 45 47 PM" src="https://user-images.githubusercontent.com/599935/58602561-421a8f00-8242-11e9-975f-a11f9bbca2a3.png">

**Comment by anthonydresser** [comment]
After doing some investigation it looks like we were using an arbitrary inital ratio defined in the sash class of 40% https://github.com/microsoft/azuredatastudio/blob/cf8f8907ee0bd8d492f8ebab2a21e26858d30715/src/sql/workbench/parts/query/browser/flexibleSash.ts#L165

**Comment by kburtram** [comment]
@anthonydresser thanks for digging that up!  I think the previous split seemed reasonable.  Though perhaps not optimal.  I'll switch it back while we discuss how this should behave.  The goal should be that users don't have to manually resize the splitter in most situations, is possible.
