### ISSUE TITLE
Right-click options lost in Object Explorer if a non-master database is set

### ISSUE THREAD

**Issue by jrowlandjones** [microsoft/azuredatastudio#5701]
Issue Type: <b>Bug</b>

* Create a connection to a SQL Server instance setting the a specific database in the connection (e.g. WideWorldImporters).
* Right click on the connection - "create external table" is missing - only "New notebook is showing"

<img width="314" alt="image" src="https://user-images.githubusercontent.com/10529018/58514394-b7a93100-8156-11e9-8115-2cf8c859a452.png">

Workaround 
* right click instance name
* click manage
* click SQL Server 2019 (preview) breadcrumb
* initiate wizard

Azure Data Studio version: Azure Data Studio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:38:05.313Z)
OS version: Darwin x64 18.6.0

**Comment by lewis-sanchez** [comment]
Not able to repro with the latest version of Azure Data Studio.
