### ISSUE TITLE
Stop YELLING

### ISSUE THREAD

**Issue by SanderSade** [microsoft/azuredatastudio#5713]
Issue Type: <b>Feature Request</b>

CONNECTIONS, SERVERS, RESULTS, MESSAGES - please stop titles yelling at me. It was hated when Microsoft tried this with Visual Studio 2015 (and reverted the bad design later), it is still as hated now. 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment]
@SanderSade thanks for the suggestion.  We are following the VS Code UX convention in this regard.  The closest issue I could find in their repo is https://github.com/microsoft/vscode/issues/36403.  In general, I think we'd like to get this addressed upstream if possible.  Though I leave open to discuss with our UX team.
