### ISSUE TITLE
Jump to object in Object Explorer

### ISSUE THREAD

**Issue by alextercete** [microsoft/azuredatastudio#572]
It's currently possible to jump to a file in Explorer using the shortcut `Cmd`/`Ctrl`+`p` and typing a part of the filename. Opening a file like this is normally quicker than navigating to the file in Explorer, especially if you take advantage of the fuzzy search capabilities of the dialog:

![screen shot 2018-01-29 at 10 59 40](https://user-images.githubusercontent.com/126538/35507123-95f5bae2-04e3-11e8-8462-186cea5aefa3.png)

It'd be useful if that search dialog allowed jumping to objects in the Object Explorer as well. The list of objects could be the same used by the search widget on the Dashboard (it would be nice to add the ability to jump to the object in Object Explorer in that widget too, using the context menu):

![screen shot 2018-01-29 at 10 48 27](https://user-images.githubusercontent.com/126538/35507386-78551f4a-04e4-11e8-8266-5568a47730e7.png)

### Potential use case
I want to see the columns of the `HumanResources.Employee` table, so I:
1. Hit `Cmd`/`Ctrl`+`p`
1. Type `hre`
1. _`HumanResources.Employee` appears as the first result_
1. Hit `Enter`
1. _`HumanResources.Employee` is given focus (and  maybe expanded) in Object Explorer:_

    ![screen shot 2018-01-29 at 11 17 48](https://user-images.githubusercontent.com/126538/35507869-1b9aaf84-04e6-11e8-8698-b6c0d151d09f.png)

1. Expand the _Columns_ node

**Comment by kburtram** [comment]
@MattIrv please look at this suggestion when designing the OE extensibility API.  Thanks!

**Comment by MattIrv** [comment]
Object explorer APIs for this are now available and will be included in the March release so that extension authors could add functionality like this if desired, though we haven't implemented any user-facing code to actually expose a dialog box like the suggested one yet

**Comment by alextercete** [comment]
@kburtram As far as interacting with the Object Explorer goes, I think the current API does the job well. I guess the workflow to navigate to an object from the Quick Open dialog (similarly to happens with a file on disk) would still require some extension points, but I'm happy to open a separate suggestion for that.
