### ISSUE TITLE
Insider build not updating itself on OS X

### ISSUE THREAD

**Issue by BrentOzar** [microsoft/azuredatastudio#5721]
Issue Type: <b>Bug</b>

Running an insider build from this week, and I get an error when ADS launches: "Could not locate update bundle for com.azuredatastudio.oss within file:///Users/brent/Library/Caches/com.azuredatastudio.oss.ShipIt/update.Oj5ugKF/ Source: Update Service"

I got this on an insider build last week too, but just to be safe, deleted that build, and re-downloaded a newer insider build to see if it'd happen again.

![Screen Shot 2019-05-29 at 10 08 53 AM](https://user-images.githubusercontent.com/245462/58576855-1c699780-81fa-11e9-9cd1-4404127d0ac7.png)

Azure Data Studio version: Azure Data Studio 1.8.0-insider (c1f73255b530e025c5dce4020decc0ef867db22d, 2019-05-21T07:16:19.571Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (9.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0
pastetheplan|dre|0.2.0
azuredatastudio-postgresql|Mic|0.1.0
sql-vnext|Mic|0.13.1

</details>

**Comment by kburtram** [comment]
We recently renamed the insiders build to have "- Insiders" appended to the application name in order to support side-by-side installation with the stable build.  An unfortunate side-effect of this is that the auto-updating from an insiders build with the previous name won't work due to filename mismatch.  The workaround is a one-time manual upgrade after which the auto-update should start working again.  Sorry for the inconvenience.

**Comment by BrentOzar** [comment]
Hmm, no, I don't think that's it - I have both of those running. Is it that you're not allowed to run them both side by side?

![Screen Shot 2019-05-29 at 7 39 39 PM](https://user-images.githubusercontent.com/245462/58604543-88272100-8249-11e9-85de-edd87ce76110.png)

**Comment by BrentOzar** [comment]
To clarify - I'm specifically opening "Azure Data Studio - Insiders" - this is the app having the problem of not being able to update itself. I've manually upgraded it already, as noted in the initial issue.

**Comment by kburtram** [comment]
@BrentOzar thanks for the update.  Let me give it a try and see if I can repro.

**Comment by kburtram** [comment]
@BrentOzar I wasn't able to repro this installing yesterday's insider build from https://sqlopsbuilds.azureedge.net/insider/3e8f25d8642c9560f6296d97bde2b164aedf25df/azuredatastudio-darwin.zip.  Could you try installing this version and see if auto-update works?

To your previous question, you should be able to install and run stable & insiders side-by-side now.

**Comment by BrentOzar** [comment]
It worked with today's build! Thanks, closing.
