### ISSUE TITLE
ADS new query page issues

### ISSUE THREAD

**Issue by geleems** [microsoft/azuredatastudio#5728]
1. New query page shows `disconnected` when being opened, but runs query successfully.
2. `Results` tab does not show anything after non-select query is executed. `Messages` tab shows message related with the operation though. (Not sure if this is intended or a bug)

![GIF](https://user-images.githubusercontent.com/19577035/58586952-16cb7c00-8211-11e9-83fb-30d5f79ccf8b.gif)

**Comment by Charles-Gagnon** [comment]
Yeah I'm seeing this as well. Seems like something is seriously broken with the editor as we also have #5746 and #5747 that just now popped up within the last few days. 

I've assigned these to myself for now and will look at them today, but if someone else wants to get to them first let me know and we can try to split the work.

**Comment by geleems** [comment]
Thank you @Charles-Gagnon !
