### ISSUE TITLE
Show the Actual error message

### ISSUE THREAD

**Issue by wandoschneider** [microsoft/azuredatastudio#5747]
- Azure Data Studio Version:

Steps to Reproduce:

1. Write a SQL with an error
2. Run in Azure Data Studio
![image](https://user-images.githubusercontent.com/8496997/58632271-7aaa7f00-82bb-11e9-99a8-e1e94a45dc2b.png)
3. Run the same query in SSMS
![image](https://user-images.githubusercontent.com/8496997/58632344-9ca40180-82bb-11e9-9709-98d128874460.png)

4. SSMS display the error, while Azure Data Studio just display that there's an error, without what's actually wrong.

**Comment by Charles-Gagnon** [comment]
@wandoschneider I'm unable to repro this myself on the latest released version (1.7.0). What version are you using?

**Comment by wandoschneider** [comment]
My mistake @Charles-Gagnon ! I forgot to add the version info.

Version: 1.8.0-insider (user setup)
Commit: 9a55ca3021f088a0781bf57070993bc2198de7e0
Date: 2019-05-29T07:42:26.310Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Comment by Charles-Gagnon** [comment]
Ah, yeah I'm able to repro this with the insiders builds. We'll look into it, thanks!

**Comment by Charles-Gagnon** [comment]
@anthonydresser has a fix for this out for PR #5734
