### ISSUE TITLE
Notebook: change to different clusters, the spark job doesn't go to the target cluster

### ISSUE THREAD

**Issue by YurongHe** [microsoft/azuredatastudio#5753]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to a good bdc cluster, run PySpark cell for example: 1+2. Get the correct result 3.
2. Change the connection to a different cluster, which has different password of Knox endpoints. run the same cell. Go the result 3. 
    Expected: should get 401 unauthorized error.

Another test:
1. Close ADS
2. Reverse the connection order in the above, even run the cell. For both clusters, get 401 unauthorized error.

From the above two tests, we can confirm. After switching clusters from attach to, the spark job doesn't go to the target cluster.

**Comment by YurongHe** [comment]
This should be a p0 bug.

**Comment by Charles-Gagnon** [comment]
Dupe
