### ISSUE TITLE
Edit Data has a blank gap under the toolbar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5754]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run Edit Data on a table

Expected: UI doesn't have large blank gaps

Actual: Screenshot below

![image](https://user-images.githubusercontent.com/599935/58651595-89e2fa00-82c6-11e9-8efb-28f7748064de.png)

**Comment by kburtram** [comment]
@anthonydresser I think this is may be related to the custom menu changes.  Can you take a look?  It only repros on Windows for me.

**Comment by anthonydresser** [comment]
Didn't realize edit data was using the old query editor custom splitview model; I should be able to patch it for June but we should move it to splitview like we didn;t query editor.
