### ISSUE TITLE
Have to Click Twice in OE to expand node when Disconnected

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5766]
Open ADS. Click on a server in OE to connect to it. After clicking the first time, the tree in OE won't be expanded, but a connection will be opened. Only after clicking a second time will the tree expand:

![ExpandTwice](https://user-images.githubusercontent.com/40371649/58666260-ac393f80-82e7-11e9-86e7-80e2402fe932.gif)

**Comment by kburtram** [comment]
I am unable to repro this in test env.  Is there a specific server or configuration this is happening with?
