### ISSUE TITLE
Ctrl+G shows Connections instead of Goto Line in SQL text editor

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#5774]
Issue Type: <b>Bug</b>

Ctrl+G should show Goto line window.

Azure Data Studio version: azuredatastudio-insiders 1.8.0-insider (9a55ca3021f088a0781bf57070993bc2198de7e0, 2019-05-29T07:42:26.310Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (7.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by anthonydresser** [comment]
Looks like we have a keybinding conflict with vscode 
![image](https://user-images.githubusercontent.com/4324725/58671059-178a0e00-82f6-11e9-9974-93adfeecca26.png)

**Comment by kburtram** [comment]
Yeah, we should probably remap the "Show Connections" shortcut to something else.  It looks manually removing that shortcut is a workaround, so we can review for next month.
