### ISSUE TITLE
Switching to new query editor doesn't clear results/messages for input without results

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5787]
Azure Data Studio Version: 1.8.0

Steps to Reproduce:

1. Open new query window
2. Run query that returns results
3. Open another new query window
4. Toggle query results (shift + win + r on Windows)
5. Results and messages are still there from previous query window

![image](https://user-images.githubusercontent.com/28519865/58722644-c8db8300-838c-11e9-8ae5-f3774536ed8e.png)

**Comment by anthonydresser** [comment]
I wonder what the desired behavior here is. do we show the window but with blank panels, or just not show the window? @kburtram @Charles-Gagnon @yualan

**Comment by Charles-Gagnon** [comment]
The current default behavior of hiding the tabs if there aren't any results is fine, and then if a user does manually toggle the window I'd say we just do what SSMS does and show a blank messages window.

![image](https://user-images.githubusercontent.com/28519865/58726613-0e9d4900-8397-11e9-82d2-35197b67167e.png)

**Comment by anthonydresser** [comment]
My pr basically does that, but shows a blank results tab and messages tab. I could change the logic to only be the messages tab if it's important.

**Comment by Charles-Gagnon** [comment]
I'm fine with having both, not like there's anything useful anyways.
