### ISSUE TITLE
Edit Data splitter isn't resizable

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5827]
- Azure Data Studio Version: `1.8.0`

Steps to Reproduce:

1. Open Edit Data on a table
2. Show SQL Pane
3. Try to resize the splitter window

Expected: The splitter is resizable

Actual: Size is fixed at ~50% split

> Note: In the below screenshot the editor component cannot be made smaller even though hovering the splitter line shows the resize cursor.

<img width="900" alt="Screen Shot 2019-06-03 at 9 59 33 AM" src="https://user-images.githubusercontent.com/599935/58820145-a93f9700-85e6-11e9-86b7-e0fbf4464d9a.png">

**Comment by kburtram** [comment]
@anthonydresser do you have any idea if something changed here with the custom sash refactor?

@Charles-Gagnon I'm moving into June to discuss today, though if the fix isn't trivial I don't think we need this in June.

**Comment by anthonydresser** [comment]
I made this change, #5777 but didn't see any issues in my testing, ill take a look

**Comment by anthonydresser** [comment]
I can only repro this is I make the window sufficiently small to hit the minimum size of both windows. This isn't different than how it was before though.

**Comment by kburtram** [comment]
I confirmed this repro's on `1.7.0` and is not a regression.  I'll push into Planning milestone to discuss reducing the minimum size.

**Comment by kburtram** [comment]
This is fixed on the latest build.
