### ISSUE TITLE
Change Connection in Query Editor disconnects immediately 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5829]
Issue Type: <b>Bug</b>

It disconnects even if Cancel is clicked in the Connection Dialog. This seems like bad behavior - I would think that it would only disconnect if a new connection is actually made. 

Steps : 

1. Open New Query connected to server
2. Click **Change Connection**
3. Click **Cancel** in connection dialog

Expected Behavior :

Original connection is kept 

Actual Behavior : 

Editor is now in disconnected state

Azure Data Studio version: azuredatastudio 1.8.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.38GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
This is fixed in 1.12.0
