### ISSUE TITLE
Peek Definition initially displaying collapsed

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5830]
Issue Type: <b>Bug</b>

When Peek Definition is used in a query editor it initially displays collapsed into a very small area

![image](https://user-images.githubusercontent.com/28519865/58822466-713b5280-85ec-11e9-877e-b91d07fa2ae8.png)

Doesn't seem to be a regression - I can repro this in 1.7.0 as well. 

And note that if you expand the area then future invocations will correctly have a minimum size set and so display much better :

![image](https://user-images.githubusercontent.com/28519865/58822669-e575f600-85ec-11e9-9720-1c9825d507c3.png)

Azure Data Studio version: azuredatastudio 1.8.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.16GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@Charles-Gagnon I don't see this on today's insider build.  Please reactive if the issue persists.

![image](https://user-images.githubusercontent.com/599935/60461345-2583c500-9bfb-11e9-81e6-7827ee9ab72b.png)
