### ISSUE TITLE
description for Big Data Cluster dashboard is not correct

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5833]
- Azure Data Studio Version:
master

- Connect to a SQL 2019 server and open the server dashboard, click on the + button on the top right of the dashboard

![image](https://user-images.githubusercontent.com/13777222/58824607-4e5f6d00-85f1-11e9-97a9-a8ef52d325a4.png)

**Comment by MaddyDev** [comment]
<img width="1652" alt="Screen Shot 2019-07-01 at 10 23 29 PM" src="https://user-images.githubusercontent.com/12754347/60484608-17f82a80-9c4f-11e9-870a-b3af3abff059.png">
