### ISSUE TITLE
Look into redesign of Connection Dialog Advanced Page

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5835]
Issue Type: <b>Bug</b>

1. Open connection dialog
2. Click **Advanced...**

![image](https://user-images.githubusercontent.com/28519865/58826186-f9bdf100-85f4-11e9-9852-f771da8c0901.png)

Azure Data Studio version: azuredatastudio 1.8.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (40.58GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@Charles-Gagnon that area is to display additional information about the selected property.  I think originally we placed focus on the first property so there was always some content displayed there.  We may want to restore that behavior.

![image](https://user-images.githubusercontent.com/599935/58827932-18be8200-85f9-11e9-923e-f271472bf784.png)

**Comment by Charles-Gagnon** [comment]
TBH I think it'd be better if we had clickable tips (!) next to the names instead. This is a lot of wasted space right now and doesn't work super well (you have to actually select an option, clicking on the name doesn't pop up the description for example which is normal behavior for that kind of thing)

**Comment by Charles-Gagnon** [comment]
Anyways I'll close this for now actually and we can look into it later.
