### ISSUE TITLE
Notebooks: Vertical Scrollbar is Unnecessary for Some Grid Outputs

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#5836]
Note: this is NOT a regression from the May release.

Notebook grids have unnecessary vertical scrollbars in some cases:

![image](https://user-images.githubusercontent.com/40371649/58826573-d9dafd00-85f5-11e9-812c-c1e7545ea7cc.png)

**Comment by geleems** [comment]
fix has been merged.
