### ISSUE TITLE
Profiler spiltter is not resizable and text doesn't scroll

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5843]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open a Profiler window
2. Click an event with SQL text content

Expected: The text region is resizable and the text content is scrollable if necessary

Actual: Splitter isn't resizable and the text area doesn't scroll (appears to be incorrectly sized with the visible region)

![image](https://user-images.githubusercontent.com/599935/58837230-c3419f80-860f-11e9-8548-f87fe096ff39.png)

> Note In the above screenshot the scrollbar has been dragged below the status bar and isn't visible.  However, the SQL text did not move while dragging scrollbar.  In other cases, the text moved but the last several lines couldn't be brought into focus.  The issue is more impactful when looking at events with larger blocks of SQL as far as I can tell.

**Comment by kburtram** [comment]
@alanrenmsft have you seen this behavior?

**Comment by alanrenmsft** [comment]
@kburtram 

I tested using last Friday's build and i don't see such issues. I will test on the latest master now.

1. for resize, do you see the drag cursor when moving the mouse over the red line you highlighted?
2. for scrollbar, the scrollbar will show up when the text area got focused. can u give it a try? 

![image](https://user-images.githubusercontent.com/13777222/58838589-fbe37800-8613-11e9-89d6-4ee85b6d0465.png)

**Comment by alanrenmsft** [comment]
@kburtram , just tried on lastest master and it is working as expected, are you on a Mac?

**Comment by kburtram** [comment]
@alanrenmsft I'm on a Windows machine using the latest build from master.  I see a scrollbar, but moving it doesn't actually move the content.  i.e. the text stays at the top and doesn't move when I drag the scrollbar down.  For resize,  I don't see any resize cursor.

@Charles-Gagnon could you please take a look at the scenario in your env to see if you can repro?  If it's just my machine I'm fine to assume it's something with my dev env.

**Comment by kburtram** [comment]
@alanrenmsft another related issue I'm consistently hitting is (1) same repro as above (2) go to details tab and focus on a row (3) down arrow key to get to non-visible rows (4) UI get messed up and document tab bar goes away and large blank area is left in profiler UI.

![image](https://user-images.githubusercontent.com/599935/58841461-cf812900-861e-11e9-9215-b638471c28e3.png)

**Comment by kburtram** [comment]
This appears to be working correctly on current builds/current machine.  I think the issue could be related to the top and bottom pane having large minimum sizes and working on a screen with low resolution.
