### ISSUE TITLE
Profiler details section is display collapsed and doesn't auto-expand

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5844]
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Run the profiler
2. Click on an event

Expected: The Details\Text pane auto-expands

Actual: Details Text pane is collapsed and it's not intutive that it's even there or how to expand it.  This is a change in how this previously worked.

![image](https://user-images.githubusercontent.com/599935/58837636-f89abd00-8610-11e9-9c9e-79452dbbc959.png)

**Comment by kburtram** [comment]
@alanrenmsft are you not seeing this one either?

**Comment by dylmye** [comment]
I can reproduce. Didn't see the arrow. Expected to be able to double-click on the line to bring up details. Additionally, I can't copy data from cells like I can SQL results (though that's obviously a different feature request)

**Comment by alanrenmsft** [comment]
@dylmye  copy data is being tracked in a different issue: https://github.com/microsoft/azuredatastudio/issues/5667

I have a fix for the expand issue. you will be able to click the tab header to expand the details section
