### ISSUE TITLE
CMS\Azure views show "Disconnect" on Table nodes

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5850]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Connect to a CMS and expand a registered server
2. Expand down to tables and right-click on a table

Expected: Menu items match menu items for tables in Servers view.

Actual: Menu items don't match and contain "Disconnect", which makes no sense for a table.

**Comment by kburtram** [comment]
@abist I thought in the design review we wanted to fix this for June, no?

**Comment by abist** [comment]
@kburtram This is a data explorer issue with CMS and Azure both. I'll try to get a fix for CMS, however, it should be ideally handled by the Data Explorer. @anthonydresser, are there any nuances here or can I make changes to remove that action?

**Comment by kburtram** [comment]
@abist I'm not sure-clear the distinction being made between CMS & Data Explorer, as CMS is being built as part of the Data Explorer workstream.  I assume the point is that the menu contributions are coming from the bit of code that attaches MSSQL schema contents to CMS\Azure tree nodes.  In this case, I agree that the fix should be made in that code rather than the CMS extension code.  I'll unassign and move into the Planning milestone to discuss tomorrow.

**Comment by kburtram** [comment]
@abist it looks like Disconnect is still available on Tables, Views, etc.  Even though there are now the correct SELECT 1000, Edit Data, etc. commands.  

Is this expected?  i.e., do we need a different fix to remove disconnect?  for some reason I thought this would be resolved by the change to add the correct commands.

**Comment by abist** [comment]
Let me take a look. It should have been resolved.
