### ISSUE TITLE
CMS doesn't work with SQL Login

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5858]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Add a CMS Server using SQL Login auth
2. Restart ADS
3. Try to expand the CMS Server

Expected: The server expands

Actual: An error is displayed in a notification pop-up

![image](https://user-images.githubusercontent.com/599935/58842285-5daade80-8622-11e9-8a15-a069cfdb779c.png)

**Comment by abist** [comment]
This is expected as only servers that also have Win Auth can login with SQL Login. The error message is incorrect, as Charles pointed out here - https://github.com/microsoft/azuredatastudio/issues/5859

I'm sending a PR that shows the correct error message instead.

**Comment by kburtram** [comment]
@abist I'm not quite following the comment regarding this being expected.  But the scenario works fine in SSMS.  We should be able to add Central Management Servers using SQL Login authentication.  My test server has mixed-mode authentication enabled.

**Comment by abist** [comment]
Closing as resolved by https://github.com/microsoft/azuredatastudio/pull/5873

**Comment by kburtram** [comment]
@abist I'm going to reactive and move to July.  The fix in #5873 removes SQL Login, which isn't the long-term fix we want to see here.
