### ISSUE TITLE
Error adding Azure CMS

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5859]
Issue Type: <b>Bug</b>

Getting an error after adding an Azure server as a CMS and trying to expand

![image](https://user-images.githubusercontent.com/28519865/58845013-17c53900-8669-11e9-97ea-b7c23aa2c669.png)

Note that Azure DBs are not supported as CMS so an error is expected, but it should be giving a better error.

Azure Data Studio version: azuredatastudio 1.8.0 (763080aea044accfd9a44b8676f6a6cd8da2841a, 2019-06-03T22:08:37.910Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz (2 x 2200)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|7.00GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by abist** [comment]
Being tracked here - https://github.com/microsoft/azuredatastudio/issues/5858
Investigating and will have a fix by tonight.

**Comment by Charles-Gagnon** [comment]
Reopening. Note that while the error message is the same this specifically is more about displaying a useful error when attempting to add an Azure server to CMS (which I don't believe it does currently).

**Comment by abist** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/commit/6197279e83d0cbb4e974c774854bd84b38498548
