### ISSUE TITLE
Don't prompt for save when I close a Json Collumn Untitled file

### ISSUE THREAD

**Issue by bmf-ribeiro** [microsoft/azuredatastudio#5863]
Issue Type: <b>Bug</b>

Click on a Json Collumn wich opens a new tab with the content.

Close the tab.

Expected: tab closes
Actual: It prompts to save

Azure Data Studio version: azuredatastudio-insiders 1.8.0-insider (50242b2c3543312ba0bfdac3810130e592c5d051, 2019-06-04T07:47:32.827Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210M CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.45GB (8.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by nikonso** [comment]
I work with a lot of json collumns so this is really a pain point when using ADS. If this is an area where you would accept a PR could you provide a code pointer so I can take a stab at it?

**Comment by nikonso** [comment]
Yearly reminder that this is still a very painful point while working with ADS...

**Comment by nikonso** [comment]
Is this something were you would be open to an external contribution? If so, and if you could give me a code pointer, I wouldn't mind giving this a shot..

As it is constant source of pain when working with an otherwise amazing product.
