### ISSUE TITLE
Results data table laggy

### ISSUE THREAD

**Issue by Heavygys** [Microsoft/azuredatastudio#587]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1.Open one tab, execute a sql statement.
2. switch to a second tab, then back to the first tab, it takes a few seconds to re draw the data grid.

**Comment by Heavygys** [comment]
[lag.zip](https://github.com/Microsoft/sqlopsstudio/files/1677117/lag.zip)

**Comment by kburtram** [comment]
@corivera could you please group this with the other Query Editor rendering issues we're tracking?  Thanks!

**Comment by bigleka** [comment]
Hi @kburtram , Just to add my 2 cents, when the Grid Result rendering laggy to load, the PageUP and PageDown movement on the result stop work and the arrows too.
I need to click with the mouse in any cell to restore the keyboard functions.

**Comment by anthonydresser** [comment]
Most of this issue should be fixed by the grid refactor
