### ISSUE TITLE
Cannot edit read-only editor message when trying to type in Output tab

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5870]
- Azure Data Studio Version: 1.8.0

Steps to Reproduce:

1. Try to type in output pane, "Cannot edit in read-only editor" message appears

![image](https://user-images.githubusercontent.com/28519865/58905869-9c42a680-86bf-11e9-8430-2e0aec7cbf1c.png)

While it doesn't really have any negative consequences it doesn't look that great. Ideally we should be using a text editor for that anyways and instead have something like the messages tab.

**Comment by anthonydresser** [comment]
That ui element is entirely controlled by vscode. Their editor is incredibly well optimized for perf, so they use it where ever possible. The only real thing here is to squelch the message, which seems like an upstream issue to me.

**Comment by Charles-Gagnon** [comment]
Yeah and it repros in vscode, I'll close this as upstream then.
