### ISSUE TITLE
Connection Dialog Advanced Properties reorder when collapsing/uncollapsing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#5883]
Issue Type: <b>Bug</b>

Seems like a couple of different ways to trigger this :

1. Open connection dialog
2. Click **Advanced...**
3. Click **Initialization** header to collapse it
4. Click **General** header to collapse it
5. Click **Advanced** header to collapse it

Expected : 

Sections stay in the original order

Actual :

**General** section jumps down to bottom, below **Advanced**

![image](https://user-images.githubusercontent.com/28519865/58917373-26e4cf00-86db-11e9-9bd7-ede4e4174bc0.png)

Scrolling around and/or collapsing/uncollapsing other sections seems to fix this, but other sections jump around oddly as well.

Azure Data Studio version: azuredatastudio 1.8.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (38.19GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
The current Advance dialog no longer contains collapsible sections.  Closing since this issue isn't applicable to the current implementation.

![image](https://user-images.githubusercontent.com/599935/129785482-aa2d9ea4-9b04-46ac-96f0-761cd2979425.png)
