### ISSUE TITLE
Import file preview grid columns not resizable

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5891]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run `Import flat file wizard` on a CSV with lots of columns

Expected: The table preview presents the data legibly, properly sizing columns with basic resize and scrolling behavior.

Actual: Preview is squashed into a fixed sized table without the ability to resize columns.  Some data cannot be adequately previewed.
 
![image](https://user-images.githubusercontent.com/599935/58921463-ba260080-86eb-11e9-9bb4-e4cc71039f16.png)

**Comment by aasimkhan30** [comment]
@kburtram I think this issue isn't present in the correct build. Correct me if I'm wrong.

**Comment by aasimkhan30** [comment]
@kburtram Please check my PR #10278. I think I fixes the issue.

**Comment by kburtram** [comment]
Closing as fixed based on #10278.
