### ISSUE TITLE
SQL Agent Jobs created using ADS aren't runnable without error

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5896]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open "New Job"
2. Add a simple job step, such as a T-SQL query like `SELECT @@VERSION`
3. Run Job

Expected: Job runs successfully

Actual: Job fails regarding "non-existent step"

![image](https://user-images.githubusercontent.com/599935/58925128-3f64e180-86fb-11e9-8c28-4f0217445c9b.png)

**Comment by kburtram** [comment]
It looks like the issue is that SSMS automatically sets the final Job Step "On Success" value to "Quit the job reporting success" whereas ADS steps the value to "Go to the next step".

*e.g. a job created with SSMS*
![image](https://user-images.githubusercontent.com/599935/58925410-493b1480-86fc-11e9-8ccc-2f419207edf9.png)

**Comment by abist** [comment]
@kburtram Was the step empty or did it have a command?
