### ISSUE TITLE
no expand/collapse icon for connection profile groups in saved connections view

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#5898]
in the connections view, we have the icon/button for users to expand/collapse a group, but it doesn't exist in saved connections view.

![image](https://user-images.githubusercontent.com/13777222/58935662-c4172600-8722-11e9-9837-1f124f20ceb6.png)

**Comment by kburtram** [comment]
This UI has been redesigned since the issue was created.  The new UI has typical expand/collapse icons.

![image](https://user-images.githubusercontent.com/599935/129784828-7000fa19-7ed0-412f-a307-c2d3d231802f.png)
