### ISSUE TITLE
Unnable to reach a server with workspace

### ISSUE THREAD

**Issue by gabrieldaj** [microsoft/azuredatastudio#5918]
Issue Type: <b>Bug</b>

Connect into a server when you are using a workspace it's impossible.., reinstall not affect anything 

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-08T00:55:40.928Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz (4 x 3193)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.80GB (9.33GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.0
ssmskeymap|kev|1.1.0
whoisactive|Mic|0.1.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by kburtram** [comment]
@gabrieldaj I'm not able to repro this on `1.8.0`.  Is the the repro steps something like below:

1. Open a .codeworkspace file that was previously created with ADS
2. Open Connection Dialog and connect to a server

Do connections work when a workspace isn't open?  Are there any connection related workspace settings?  Or other repro details?

**Comment by gabrieldaj** [comment]
Thanks for the support, I just update to 1.8.0 and the error no longer exists 

Do connections work when a workspace isn't open? : Yes,  the problem just happened when I was using a workspace

Are there any connection related to workspace settings?: I don't think so..., before creating the workspace, I installed some extensions and saved 3 connections. The error began when I create the workspace.

I look on the internet for some similar errors, i got the same messages as bellow: SqlToolService stopped working 

![image](https://user-images.githubusercontent.com/17691200/59061434-e40d2d80-8879-11e9-8f9d-a1007da646d8.png)
