### ISSUE TITLE
Results pane no longer pops back up

### ISSUE THREAD

**Issue by aarongiust** [microsoft/azuredatastudio#5919]
Issue Type: <b>Bug</b>

Run a query
Results pane pops up as expected
Press Shift+Windows to minimize the pane
Run another query
Results pane does not pop up again

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (22.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@aarongiust was this working on `1.7.0`?

**Comment by aarongiust** [comment]
I'm not sure what I just upgraded from but pretty sure I had the April release and it worked in that.

**Comment by kburtram** [comment]
@aaomidi thanks for the additional info.  I confirmed this regressed since the `1.7.0` release.  I'll add to our Hotfix milestone for triage.

**Comment by Charles-Gagnon** [comment]
Related to #5778
