### ISSUE TITLE
Feature Request: Report Issues should make it easier to report non-dup issues with version information

### ISSUE THREAD

**Issue by CoolDadTx** [microsoft/azuredatastudio#592]
- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.16299
---

 Click the Report Issues button and you go to the Issues tab in GitHub with a new issue open and the version info filled in. This is good but the first thing you really should do is verify the issue hasn't already been reported. For that you have to click on Issues. Once you've identified that the issue is new you want to create a new issue. If you simply click to create a new issue then the version information about the app is gone. You can go to the Help\About and get the version info but none of that is copyable text.

The current workarounds I see:
1) While on the new issue page, open the Issues in a new tab so you don't lose the initial issue information.
2) Close the GitHub tab after verifying the issue isn't a dup and then use Report Issues to open the window again.

**Comment by kburtram** [comment]
This feature comes from upstream vscode so we'd prefer to see this fixed there, and we'll pick-up in a source refresh.
