### ISSUE TITLE
Please keep focus in the SQL editing box

### ISSUE THREAD

**Issue by winzig** [microsoft/azuredatastudio#5926]
Issue Type: <b>Feature Request</b>

Seems like there is new behavior in the latest release that puts the focus in the bottom "Messages" pane after a query has run. It's rare that I would want the focus in that bottom pane to do something. But it makes continuing to edit the SQL more difficult, as you have to get the focus back up in the top pane after execution.

Azure Data Studio version: Azure Data Studio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:37:31.184Z)
OS version: Darwin x64 18.6.0

**Comment by Charles-Gagnon** [comment]
This issue is fixed and will be included in the next release. In the meantime if you use the insiders build the fix is in the latest version of that.

**Comment by winzig** [comment]
I wish there was some middle ground between waiting a month for the next release, and using the bleeding edge. ;-)

**Comment by kburtram** [comment]
@Charles-Gagnon is this the same issue as https://github.com/microsoft/azuredatastudio/issues/5864?  I thought we approved this bug for June release?

**Comment by winzig** [comment]
Does that mean this wasn't approved for a June hot fix

**Comment by Charles-Gagnon** [comment]
Correct - the July release will have the fix.

**Comment by rhmariano** [comment]
GREAT NEWS!!! This bug is really annoying! It happens only when there's no result grid, just Messages to show. Glad to read that next release Will Bring that fix! Thanks guys!
