### ISSUE TITLE
Profile, filter by DB, more filter options, more of actual SQL Profiler that you could use from SSMS

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#5932]
**Is your feature request related to a problem? Please describe.**
I really want to use Azure Data Studio 100% all the time instead of SSMS primarily because the intelli-sense of queries is massively faster, Dark mode out the box that works, extensability and more responive UI. However at present I always have to have Azure Data Studio and SSMS open both times because there are lots of little bits and pieces which are just to rough to use on ADS - profiler is one of them.

The layout is nice but...
I can't filter by database therefore it's completely useless. There are no templates for what events I want recorded - therefore useless.

**Describe the solution or feature you'd like**
Add more filter options, but specifically be able to filter to a specific database.
Add templates of events to profile - the one I use 99.9% of the time when I'm using the SSMS SQL profiler is TSQL SPs template. I want to know when SPs start and finish and how they were called, i.e. what the params were. Without being able to do these 2 things the ADS profiler is useless to me.

**Describe alternatives you've considered**
At this point ADS profiler is completely unuseable for me. All I can do is use the older SSMS SQL Profiler, which of course works but the UI is not as nice.

**Additional context**
For this extension plus ADS in general - you need to look at what is done already in SSMS, figure out the most useful parts, improve the UI (cause normally it's pretty average) and translate that to ADS. There are so many little things missing from ADS that I use all the time that are not even power user things they are basic quality of life things that not having them really ruins the experience. The most common one double clicking on the dividing line of column headers in a grid does not cause the column to resize to fit the maximum content, it does on virtually every other app - SSMS, Excel etc.... The is no horizontal scroll bar on the connections pane, so when you  expand Server >> database >> table you can see the column names without resizing the pane in some cases taking up 1/3 of the screen space!

**Comment by alanrenmsft** [comment]
thanks @peterlukerow for the great feedback, I am adding the database name column to the profile templates, and you will be able to filter by database name starting from next release. and I will also create separate issues to track other issues/suggestions. and i am going to use this issue to track the database name filtering issue.

In the future, it would be nice if you can open one github issue per problem/suggestion that will make the tracking easier.

**Comment by alanrenmsft** [comment]
the issue about missing templates is tracked by: #6138 
the issue about grid column resizing is tracked by: #2251 
the issue about horizontal scrollbar for connections view is tracked by: #4106
@peterlukerow Please subscribe to these issues so that you can get notified when there are updates to them. this issue will be closed once I merge the database name filtering related PR.

Thanks
Alan

**Comment by alanrenmsft** [comment]
the changes for the database name filtering has been merged to master branch, it will be available in the July release.

**Comment by peterlukerow** [comment]
Yay!
