### ISSUE TITLE
Quality of life improvements, concentrate on these before new features

### ISSUE THREAD

**Issue by peterlukerow** [microsoft/azuredatastudio#5933]
**Is your feature request related to a problem? Please describe.**
It's technically a feature request but ultimately for me I consider it to be a problem. No matter what you say ADS is growing up to be a cross-platform replacement for SSMS. No matter what you say I 100% believe that is the way people are viewing it. This leads to frustration because there are lots of things that just aren't available, don't work as nicely in ADS.

It's a shame because I most definitely want to use ADS instead of SSMS 100% of the time because the intelli-sense is massively faster, dark mode out the box, extensible, better UX experience (for the bits that work) but at present I find I have to keep both SSMS and ADS open at the same time because there are somethings that don't work, work badly or aren't there in ADS

**Describe the solution or feature you'd like**
- Go through all grids in the entire UI and ensure that double-clicking the dividing line between column headers expands the column to fit the content like every other app, e.g. SSMS, Excel etc... and ensure if the grid doesn't fit after doing so that a scrollbars in both directions are available as appropriate.
- Add a horizontal scrollbar to Connections pane so that when you expand server >> database >> table >> columns you don't have to expand the size of the pane to take up 1/3 of the screen when maximized (1920x1080 res screen) just to read the column names. I should be able to leave the pane as a 1/4 of screen when maximize and scroll to read it as necessary.
- Make backup and restore more reliable, half the time it doesn't work and I end up going back to SSMS.
- In the connection pane, when expanded to the table level let me drag the table name onto a query window and have it insert a CSV of all column names. Let me drag an individual column name from the pane on to a query windows and have it insert it.
- Go through the SSMS and look at all the useful little bits that give little time saving things and implement those but improve the UX like you've done with a lot of things.

**Describe alternatives you've considered**
Some of the things above are just annoyances and I either suffer through them or in cases where it takes me more than a minute to do something and it's still not done I switch back to SSMS and do the same job in 30 seconds without issue.

**Additional context**

**Comment by Charles-Gagnon** [comment]
Thanks for the feedback! We're constantly making changes to address usability concerns such as yours and having specific examples like these is very useful. It would be even more helpful though if you opened a separate issue for each of the problems described here - trying to track separate fixes from a single monolithic issue like this is difficult and makes it easy to miss things.

Could you also please go into more detail about _Make backup and restore more reliable_ and _Go through the SSMS and look at all the useful little bits that given little time savings_? Specific examples here would let us drill down to the problem quicker than trying to guess what you're having problems with.
