### ISSUE TITLE
Auto-show folders when connected not working

### ISSUE THREAD

**Issue by RogueSensei** [microsoft/azuredatastudio#5934]
Issue Type: <b>Bug</b>

When connecting to a saved server on the side bar, the databases and folders do not show automatically. The dropdown suggest this should happen, but I have to close it and re-open it, just a small inconvenience

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Could you post the steps you're taking and a screenshot of the tree state after connecting? It seems to be working as intended as far as I can tell - the nodes expand to their first levels after connecting. 

![screen](https://user-images.githubusercontent.com/28519865/59112988-101bc380-88f9-11e9-9fcb-88f91ad37a91.gif)

**Comment by RogueSensei** [comment]
I click on the server to connect and it prompts me to enter my password (I am using SQL authentication and I have it set to not remember my password). When I do, it connects but does not expand the tree view
![image](https://user-images.githubusercontent.com/32780495/59113356-c3f27280-893c-11e9-95b1-5bbf8ce5a60b.png)
Clicking on the tree view at this stage does expand it however, it's just confusing to see the arrow in a state implying it's expanded when it hasn't

**Comment by Charles-Gagnon** [comment]
Hmm, that still works for me. Could you open the developer console (**Help** -> **Toggle Developer **Console**** and see if there's any errors listed in the Console tab?

![image](https://user-images.githubusercontent.com/28519865/59114151-6a1d8880-88fb-11e9-9276-87230a2cc97b.png)

**Comment by RogueSensei** [comment]
No errors or anything that sticks out as far as I can tell (these popped up before I tried connecting and nothing else popped up after I connected)
![image](https://user-images.githubusercontent.com/32780495/59114744-bdb1c580-893f-11e9-9342-6cfeb21830c3.png)
