### ISSUE TITLE
Schema Compare generated script says it is successful but does not work

### ISSUE THREAD

**Issue by danuw** [microsoft/azuredatastudio#5936]
Issue Type: <b>Bug</b>

compared two databases
saving the generated script says it is successful but does not work

Azure Data Studio version: Azure Data Studio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:37:31.184Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.17GB free)|
|Process Argv|-psn_0_1229100|
|Screen Reader|no|
|VM|29%|
</details>

**Comment by udeeshagautam** [comment]
@danuw thanks for reporting the issue. Can you please elaborate what do you mean by "does not work" - is the script not created or saving the script doesn't save it as a sql file?

**Comment by danuw** [comment]
Sorry about that.

It takes me through the steps of selected the output location but when the operation finishes, even though the 'log' (bottom of screen) confirms the location selected, the file cannot be found at that location. 
I could double check for updates and try again if necessary...

**Comment by kisantia** [comment]
@danuw can you try again with the latest version of ADS and the Schema Compare extension? We made some changes so there should be an error message if the script generation was not successful.
