### ISSUE TITLE
Azure servers spinning forever if Create Firewall Dialog is opened and closed

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#5941]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Open a SQL Server with Firewall Rule in the Azure Extension.
2. The firewall rule dialog opens. 
3. Press Cancel.

Expected - Nothing happens
Actual - The server node is spinning forever.

**Comment by kevcunnane** [comment]
Backlog'd for now

**Comment by abist** [comment]
This is now fixed.
