### ISSUE TITLE
Feature Request: Jupyter Tags

### ISSUE THREAD

**Issue by abertsch72** [microsoft/azuredatastudio#5943]
Jupyter supports "tags," a feature where a code or markdown cell can have terms attached in its metadata. This is demonstrated below:
![image](https://user-images.githubusercontent.com/42593540/59136971-4af21b80-893a-11e9-81fc-73a0b15ca862.png)

Tags are a small feature, but they're absolutely essential for writing notebooks that are parameterized, scheduled, and executed with [Papermill](https://papermill.readthedocs.io/en/latest/), a powerful framework used widely in industry, most notably at [Netflix](https://medium.com/netflix-techblog/scheduling-notebooks-348e6c14cfd6). 

Papermill is commonly used and widely useful, but without tags, Azure Data Studio cannot be used with a Papermill-based process. A notebook with tags can be viewed currently without any errors in ADS, but tags can't be viewed, added, or removed. (Tags are part of the JSON metadata of a cell, and it appears ADS just ignores them completely if present.) 

A menu option to add tags, perhaps in the ellipsis menu on the right side of the cell, would solve this issue and allow ADS to be used to develop notebooks for Papermill processes.

**Comment by MsSQLGirl** [comment]
+ @VasuBhog bump 🎁

**Comment by VasuBhog** [comment]
@abertsch72 closing this since the new November release of ADS now includes the use of adding `parameters` tag in Notebooks (via the cell toolbar menu) that can now enable the use of papermill to parameterize notebooks :)! 

If you would like other tags to be included in ADS, please feel free to open this issue or create a new one.
