### ISSUE TITLE
Starting pgsql service message never disappears in June update

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5946]
- Update Azure Data Studio to June release
- Restart application
- See that "Starting pgsql service" stays in the toolbar forever
- You can still connect as usual

![image](https://user-images.githubusercontent.com/10819925/59122993-09994600-8911-11e9-8a3a-2490ef935141.png)

- There's no output under pgsqlToolsService

This was reported by a customer - see https://twitter.com/digitalduquette/status/1136974420638142464. I think this warrants investigation & planning to get an update going, right @akamath46297 ?

**Comment by alanrenmsft** [comment]
@DigitalDuquette , Thanks for reporting the issue, we have fixed the issue and released a new version of PostgreSQL Extension, please give it a try.
