### ISSUE TITLE
Azure Data Studio User vs System Installer

### ISSUE THREAD

**Issue by rhamenator** [microsoft/azuredatastudio#5951]
- Azure Data Studio Version:

Steps to Reproduce:

1. Download and install the user installer for Azure Data Studio, with OneDrive running.

2. Observe how slow and unresponsive your computer becomes

Solution: Uninstall Azure Data Studio, and download and install the system installer instead.  Problem solved.

**Comment by kburtram** [comment]
@rhamenator the user and system installer are identical product bits.  The only differences are in the installer packaging settings.  Once the product is installed there shouldn't be any significant difference.  

If there is a big perf difference you may check if there is are different virus scan rules on the user home directory vs. program files directory, or some other per-user setting.  I haven't been able to observed this behavior myself.  Please let me know if you have any additional repro or configuration steps that could help us get an internal repro to investigate.

**Comment by rhamenator** [comment]
I am using Windows Defender with its default settings. Give me a few days and I'll uninstall Azure Data Studio, then repeat the process. What information should I log to facilitate your investigation of the issue?

**Comment by rhamenator** [comment]
I repeated the installation of Azure Data Studio.  When I use the user installer, it causes OneDrive to start scanning for changes, even though the directory to which ADS was installed was not being synced to OneDrive.   The OneDrive scanning activity maxed-out my disk usage, but this time, the condition only lasted for a few minutes.  This behavior does not occur with the ADS system installer; therefore, I would suggest to people using OneDrive that they use the system installer instead of the user installer.
