### ISSUE TITLE
Support sqlcmd syntax within scripts

### ISSUE THREAD

**Issue by AdamWilbur** [microsoft/azuredatastudio#596]
- SQL Operations Studio Version:  0.25.4

Steps to Reproduce:

Open a file that uses sqlcmd syntax to execute another .sql file, like those commonly seen in pre and post deployment scripts in SSDT projects.  For example:

:r .\SomeDirectory\MyFile.sql
go

**Comment by kevcunnane** [comment]
There's a number of requests for this in the MSSQL repository too - https://github.com/Microsoft/vscode-mssql/issues/599. We should try to track both requests to help prioritize this.

**Comment by tlagrone** [comment]
1up

**Comment by hannahqin** [comment]
SQLCMD mode is supported as of September 2019. https://github.com/microsoft/azuredatastudio/issues/2752
