### ISSUE TITLE
Cannot use ADS - Trying to Add an Account - silent error

### ISSUE THREAD

**Issue by david-buzz** [microsoft/azuredatastudio#5962]
Issue Type: <b>Bug</b>

After various problems with an Azure AD account and multiple reinstalls, and attempts to delete all Azure AD accounts from Azure Data Studio, my installation now doesn't allow me to add an account at all.

Error is "zone-node.js:2280 Unhandled Promise rejection: Get Device Code  request returned http error: 400 and server response: {"error":"invalid_request","error_description":"AADSTS220050: The specified encryption key version override 26 was not found in the list of keys."

So I am stuck with a non-functional Azure Data Studio because it has no accounts and I can't add one.

Is there a procedure to totally clean off Azure Data Studio and start again?  Or a way to totally clean off all references to accounts in Azure Data Studio?

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.72GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by david-buzz** [comment]
[AzureDataStudio Error when try to add account.log](https://github.com/microsoft/azuredatastudio/files/3274154/AzureDataStudio.Error.when.try.to.add.account.log)

**Comment by david-buzz** [comment]
I have attached a file with the error information above and I don't think this error matches existing bug reports

**Comment by alanrenmsft** [comment]
feature owner, i have tested this on 1.8 release, but couldn't repro the issue, can someone please take a look?

**Comment by Charles-Gagnon** [comment]
@david-buzz 

First try just deleting %APPDATA%\azuredatastudio\Azure Accounts

If that doesn't work then you can delete the whole %APPDATA%\azuredatastudio folder - note this will clear all other user settings as well.

**Comment by david-buzz** [comment]
OK, now it works fine.  I can add an account and use the program.
Because my current test is a couple of days later I can't pin point the reason that it is now working.  Sorry.
