### ISSUE TITLE
[Accessibility]A11y_AzureDataStudio_CSVModifyColumn _Keyboard: As soon as we select any list item from “Data Type” expanded list through keyboard focus navigates to the next page “Summary.”

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/azuredatastudio#5966]
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS3.3.2; #A11y_AzureDataStudio; #Win32; #DesktopApp

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows10

**Additional Details:**
Tool name: keyboard
MAS reference: MAS3.2.2

**Repro Steps:**
1.Install the app Azure Data Studio.
2.Connect to database->navigate to the Data services folder->HDFS Folder-> navigate to CSV files folder->Right click on the files->Select option Create external table from CSV->Click on the "Next" button->Click on next button.
3.Navigate to the table.
4.Select any list item from “Data Type” expand list and press enter key.
5.Observed that next page is open without hitting next button.

**Actual:**
When we hit enter after selecting list item from “Data Type” expand list we find that next page is open without hitting next button.

**Expected:**
Until and unless we select and click the next button focus should not go on next page.

**User Impact:**
Keyboard user will get confuse with the unauthorize behaviour of the expand list.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx

**MAS Reference** :
**MAS3.2.2**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}

**Attachment for Reference:**
[5966_[Accessibility]A11y_AzureDataStudio_CSVModifyColumn _Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3275056/5966_.Accessibility.A11y_AzureDataStudio_CSVModifyColumn._Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
This has been fixed in master
