### ISSUE TITLE
[Accessibility]A11y_AzureDataStudio_CSVSelectDestinationDatbse_ScreenReader:Screen reader is announcing order of the list item incorrectly for “Schema for new external table” combo box.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/azuredatastudio#5969]
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS1.3.1; #A11y_AzureDataStudio; #Win32; #DesktopApp

**Environment Details:**
Application name: Azure Data Studio
Version: 1.8.0-insider (user setup)
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
NVDA Version:2019.1
JAWS version : 2019.1810.64 ILM

**Additional Details:**
Tool Name: NVDA
MAS Reference:MAS1.3.1

**Steps to Reproduce:**

1. Install the app Azure Data Studio.
2. Connect to database->navigate to the Data services folder->HDFS Folder-> navigate to CSV files folder->Right click on the files->Select option Create external table from CSV files.
3. Navigate till  “Schema for new external table” combo box .
4. Observe that screen reader is announcing the order of list item incorrectly.

**Actual:**
Navigate till  for “Schema for new external table” combo box , here screen reader is announcing the order of list item incorrectly. It reads  list item as “dbo 1of 3 level 1 ” but there are only two item present in the list.
**Similar issue also observed with JAWS**

**Expected:**
Screen reader should  read  list item as “ dbo 1of 2 level 1 ” for “Schema for new external table” combo box.

**Recommendation:**
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader users find it difficult to understand the number of item present in the list .

**MAS Reference:
MAS1.3.1-**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}

**Attachment for Reference:**
[5969_[Accessibility]A11y_AzureDataStudio_CSVSelectDestinationDatbse_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3275109/5969_.Accessibility.A11y_AzureDataStudio_CSVSelectDestinationDatbse_ScreenReader.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by Charles-Gagnon** [comment]
Possibly related to #5971

**Comment by corivera** [comment]
I've noticed some issues with editable dropdowns where there will be blank entries at the bottom. This may be related.

**Comment by corivera** [comment]
Reasonably sure this is due to those extra blank entries, so this is a dropdown problem, rather than an accessibility one.
