### ISSUE TITLE
Can't select the text data

### ISSUE THREAD

**Issue by gdirlam** [microsoft/azuredatastudio#5979]
Found it, please close.... but damned. that took 20minutes to hunt it up. I kept clicking on text and it did not show anything, 

Issue Type: <b>Bug</b>

In the regular sql profiler while debugging, I always copied and pasted the code from the text data and ran it. In your new extension, the data is in a tooltip and can't be copied. 

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (7.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
Closing based on customer edit.  We'll double-check the UX here.
