### ISSUE TITLE
Blank gap above query editor toolbar

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5981]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query

Expected: No blank gap above toolbar

Note: I see this in my local dev build but have been unable to confirm against insiders build due to delayed build today.

Actual:

![image](https://user-images.githubusercontent.com/599935/59294814-26968780-8c37-11e9-9538-b6152257f1ef.png)

**Comment by kburtram** [comment]
This went away when I reverted the previous VS Code merge (for an unrelated reason).  @alanrenmsft  @chlafreniere let's please investigate this when remerging those changes (though not necessarily as a blocking change).

**Comment by chlafreniere** [comment]
These are breadcrumbs that aren't showing up correctly for some reason. @alanrenmsft and I will investigate after the debugging issue is solved.
