### ISSUE TITLE
ADS hangs on startup when launched under VS Code debugger on Windows

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#5984]
I'm seeing the below when running ADS under the debugger on Windows.  I'm confirming if this is related to the previous VS Code source merge.

![image](https://user-images.githubusercontent.com/599935/59300255-927eed00-8c43-11e9-92ba-29343a56ca6b.png)

**Comment by kburtram** [comment]
Fixed by reverting previous VS Code merge.

**Comment by chlafreniere** [comment]
@kburtram rebuilding the node_modules solves this issue I believe. Did you try that? That's why the integration tests succeeded.

**Comment by kburtram** [comment]
@chlafreniere yes, I rebuilt the node_modules after pulling master prior to logging this issue.  The integration tests don't run ADS under the VS Code debugger AFAIK, so I don't believe the tests would catch this error.  Please let me know if you have any suggestions after investigating the issue.
