### ISSUE TITLE
SQL big data cluster tab doesn't scroll if needs vertical space

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#5988]
Issue Type: <b>Bug</b>

- Open the terminal about 1/2 way up the screen
- Click Manage on a big data cluster and go to the `SQL Server Big Data Cluster` tab
- Notice how the Service Endpoints table is cropped

The whole tab needs to be scrollable.
![image](https://user-images.githubusercontent.com/10819925/59304051-5ef49080-8c4c-11e9-87a6-9bed7a6abaf8.png)

@MaddyDev  this might be a nice one to look into for you.
Azure Data Studio version: azuredatastudio 1.9.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|. --remote-debugging-port=9222 --no-first-run --no-default-browser-check --inspect=5875 --no-cached-data|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kevcunnane** [comment]
@MaddyDev can this fit in current milestone? I've moved to planning but feel free to bring into July

**Comment by MaddyDev** [comment]
I sent a PR today. We can add this in the current milestone.

**Comment by MaddyDev** [comment]
Fixed this #6206
