### ISSUE TITLE
ADS update installer gets into a fight with Panda Endpoint Protection

### ISSUE THREAD

**Issue by logicalextreme** [microsoft/azuredatastudio#5999]
- Azure Data Studio Version: 1.8.0

On Windows 10 Pro with Panda Endpoint Protection installed, whenever an update (initiated from within the application) is initiated from Azure Data Studio, the Panda service seems to max out a CPU core. The ADS installer then doesn't progress unless I kill or suspend all Panda processes. It's happened every time I've updated ADS, but didn't happen on the initial install.

I know this isn't a traditional bug report as it's a software interaction thing, but hopefully having it highlighted and on a backlog will be useful to other users experiencing the same issues as uptake of ADS increases. I'm emailing Panda's technical support with a link to this issue as I imagine it might need some collab to resolve.

**Comment by Charles-Gagnon** [comment]
Thanks for the report @logicalextreme. Given that as you implied there's not much we can do if external processes are affecting performance I'll be closing this - although if Panda comes back with information on something ADS is doing that is wrong or unexpected we can look into it.
