### ISSUE TITLE
Hidden results pane show after switching query editor tab

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#6000]
Issue Type: <b>Bug</b>

Open query editor. Run a query that gives dataset.  Hide result pane with shortcut key.  Open new query editor (Ctrl+N). Switch to previous query editor. The result pane is visible again.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.38GB (5.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
abs-ex|ABS|0.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
import|Mic|0.8.0
profiler|Mic|0.8.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks for the report @GrzegorzLyp - this has actually already been fixed on the insiders builds. So it will be available in the next release of ADS, although if you wanted to try it on the insiders build to make sure it functions as expected that'd be great!
