### ISSUE TITLE
Failed to change kernel for Python3 and PySpark3

### ISSUE THREAD

**Issue by issacekbote** [microsoft/azuredatastudio#6003]
- Azure Data Studio Version: 1.8.0
- MacOS: 10.14.5

Steps to Reproduce:

1. Open new notebook
2. Select existing python installation

![image](https://user-images.githubusercontent.com/50624723/59348736-3c9d6880-8d5b-11e9-80d2-fcfab6865673.png)

3. Get below error

![image](https://user-images.githubusercontent.com/50624723/59348773-55a61980-8d5b-11e9-9ce8-bcc313d77659.png)

4. More information on errors from install logs

![image](https://user-images.githubusercontent.com/50624723/59348815-75d5d880-8d5b-11e9-88b8-f599d8a5cd00.png)

![image](https://user-images.githubusercontent.com/50624723/59348830-7c645000-8d5b-11e9-82d1-45ba0c514067.png)

![image](https://user-images.githubusercontent.com/50624723/59348841-81290400-8d5b-11e9-9bf9-91737e1c813f.png)

5. Get the same error when I change the kernel to PySpark3
6. Get the same error when tried shift+cmd+p, "Reinstall Notebook dependencies"

**Comment by corivera** [comment]
Does installing the Mac Command Line Tools fix this issue?

**Comment by issacekbote** [comment]
Installing the Mac command line tools fixed the issue. Thank you!
