### ISSUE TITLE
Notebooks: Keybinding for Clear Output

### ISSUE THREAD

**Issue by pnhughes** [microsoft/azuredatastudio#6019]
The ability to Clear Output from a Code cell in a Notebook is great, but there appears to be no way to associate a keybinding with this command.

I would like a keybinding entry associated with the Clear Output command for Code cells of Notebooks.  Output must be frequently cleared, and a keybinding would increase convenience greatly.

**Comment by chlafreniere** [comment]
This has been implemented with the above PR. Closing the issue.
