### ISSUE TITLE
Query grid loses scroll position when switching query tabs

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6021]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query and scroll the results grid
2. Switch to Messages tab
3. Switch to Results tab

Expected: Scroll position should be maintained

Actual: Scroll position isn't maintained

**Comment by anthonydresser** [comment]
I found the issue, ill work on finding a reliable solution.

**Comment by kburtram** [comment]
@anthonydresser any update on this issue?  If it's a regression we should try to get in for July release.
