### ISSUE TITLE
Does not respect Xmodmap Settings

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#6037]
Issue Type: <b>Bug</b>

I have an Xmodmap setting configuration file with the below in it, however, within Azure Data Studio (And VSCode, which is installed via Snap) this is not respected. Buttons 6 and 7 are not reversed. This means that the thumb scroller I have on my mouse needs to be scrolled right to scroll left (and left for right).

.Xmodmap file:
```
pointer = 1 2 3 4 5 7 6
```

These settings are respected by everything else I have installed that supports the functionality (Allows side scrolling). It's just Azure Data Studio and VSCode that does not.

Azure Data Studio version: azuredatastudio 1.7.0 (e1280022d69b651cfff04b30e830904575c8acda, 2019-05-07T21:35:31.938Z)
OS version: Linux x64 5.0.0-16-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|15.33GB (8.58GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-icons|vsc|8.7.0

</details>

**Comment by alanrenmsft** [comment]
@LarnuUK  Hi, Azure Data Studio is a fork of VSCode, and we implement the database related features, could you please open an issue in VSCode github repo? https://github.com/microsoft/vscode, once they fix the issue we can get it into Azure Data Studio. 

closing as an upstream issue.

Thanks

**Comment by LarnuUK** [comment]
Thanks @alanrenmsft , looks like it's a known issue on VSCode: [#23911](https://github.com/microsoft/vscode/issues/23991). Changing the Keyboard: Dispatch doesn't fix, as it appeared it used to as well, so I'll watch that bug for now.

Cheers.
