### ISSUE TITLE
 "MS SQL: Connect" command missing on "Command Palette"

### ISSUE THREAD

**Issue by realfreebird** [microsoft/azuredatastudio#604]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. press F1 to open "Command Palette"
2. type "connect"

SQL Operations Studio:
![sos](https://user-images.githubusercontent.com/17299389/35796021-cc3e5372-0a63-11e8-8b7b-eec70a5026ee.png)

Visual Studio Code:
![vscode](https://user-images.githubusercontent.com/17299389/35796044-dc17e3e4-0a63-11e8-9903-08ae639966d8.png)

**Comment by kburtram** [comment]
@realfreebird does the "New Connection" command do the action you're expecting in this scenario?

**Comment by realfreebird** [comment]
Yes. 
Maybe the title "New Connection" is a bit misleading since it does 2 things:
connect to saved/recent connection (which is similar to "MS SQL: Connect")  & create new connection.

**Comment by alanrenmsft** [comment]
'New Connection' is accurate for saved connections/recent connections scenario, it is creating a new connection using the information of the recent/saved connections.

I am closing the issue since we are not doing anything with this issue.
