### ISSUE TITLE
Multiple Database Support

### ISSUE THREAD

**Issue by azrull** [microsoft/azuredatastudio#6043]
Issue Type: <b>Feature Request</b>

Appreciated if you could provide native support for various database like MySQL, Oracle, DB2

Azure Data Studio version: Azure Data Studio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:37:31.184Z)
OS version: Darwin x64 18.6.0

**Comment by Charles-Gagnon** [comment]
Thanks for the suggestion @azrull! We're currently tracking adding support for other DBs in separate issues such as #4904 - if you'd like to see others added please open a similar separate issue for each of them so we can track the demand for each request separately.
