### ISSUE TITLE
Feature: Change password of expired login

### ISSUE THREAD

**Issue by martin-guth** [microsoft/azuredatastudio#605]
- SQL Operations Studio Version: 0.25.4

As a Linux user I have a SQL login with assigned password. After the password expires I am unable to reset it via SQL Operations Studio. Any attempts to connect via sqlops or sqlcmd fail with error message that the password for the login expired.

Steps to Reproduce:
- Create a SQL login whose password has to be changed
`CREATE LOGIN [test] WITH PASSWORD=N'test', DEFAULT_DATABASE=[master], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=ON, CHECK_POLICY=ON
GO`
- Login at SQL Operations studio

It would be extremely helpful to have a dialogue pop up to prompt the user for the new password. This is what SSMS does by default.

**Comment by dwijef** [comment]
So it happens to me on Azure Data Studio. Should this issue continue here or should it be opened anew?

**Comment by RamSQLDBA** [comment]
yes, i have same issue while expired my password, so i'm unable to change ads itself

**Comment by yualan** [comment]
Another customer using only macOS reported this issue, we may want to consider triaging this one.

**Comment by vinny1575** [comment]
Same issue.

**Comment by michaelpinnell** [comment]
I've come across this as well, is there a way to know if anyone is looking at doing this, or if there is a workaround that isn't tell my DBA/SRE to turn off MUST_CHANGE when they create a new login?

**Comment by carrjar** [comment]
We have a team upgrading MacBooks to Apple Silicon.  I'm the first to upgrade and cannot use VMWare Fusion anymore (not supported on Apple Silicon).  I've been using Azure Data Studio instead of SSMS just fine, until --> Login failed for user 'jcarr'. Reason: The password of the account has expired.  The only way I can update my password is to log into SSMS on my older MacBook Pro, running VMWare Fusion.

**Comment by markdodd9999** [comment]
This is not just on MacOS. I have had the same issue on PC running Windows 10 Enterprise 64bit. OS Build 19042.1706

![image](https://user-images.githubusercontent.com/107123621/172624347-9c3acb73-e0c0-4b9f-8210-87c86a038cf7.png)

As the original poster reports, there is no dialogue pop up to change password.

**Comment by viher3** [comment]
Same issue.

**Comment by rick-syncbak** [comment]
I'm still seeing this in version 1.48.0 in 2024. Every time I create a new user who uses Azure Data Studio with "User must change password at net login" , we have to have them use a desktop w/ SSMS to change their password.
