### ISSUE TITLE
document.setExecutionOptions only works with existing connection

### ISSUE THREAD

**Issue by mjeaton** [microsoft/azuredatastudio#6050]
- Azure Data Studio Version:

Version: 1.9.0-insider (user setup)
Commit: 449cd9ea27d49b66667bda043d467adb9377b734
Date: 2019-06-17T07:46:28.633Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763

**Steps** to Reproduce:

1. Per this PR (https://github.com/microsoft/azuredatastudio/pull/5484), I added code to my extension activate that will set query options for each newly opened document.

2. Start ADS, activate my extension

3. Ctrl-N to create a new query document. Write a query and click the 'Run' button.
3a. I am prompted for a connection which I provide.

4. The options I set for the query document do NOT work in this document.

5. Ctrl-N to create a new query document. Ener a query and click 'Run'. This time, the expected options are set for my query.

_It appears as if the query document options only work *if* I have an existing connection._

**Expected** results:

Even if I'm starting fresh and am prompted for a connection, the options I set for the query document should work.

**Comment by kburtram** [comment]
@mjeaton could you please take a look at this PR https://github.com/kburtram/azuredatastudio-snippets/pull/4/files?  That snippet example should set query options on all active and newly opened documents.  Please let me know if that doesn't resolve the issue you're encountering.

**Comment by mjeaton** [comment]
I took a slightly different approach, but with the same effect. It's all good now!
