### ISSUE TITLE
AZURE window for Azure services does not expand to fill panel

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6051]
Issue Type: <b>Bug</b>

When you collapse Server and Expand AZURE in the CONNECTIONS panel, the AZURE contents does not expand to fill the panel.

REPO STEPS:
1. Go the the CONNECTIONS panel.
2. Collapse SERVERS
3. Expand AZURE

Note that the scroll region is 5 lines making it difficult to scroll through your Azure databases.

![image](https://user-images.githubusercontent.com/41927913/59624795-95b72480-90ec-11e9-9044-cfc2f6fbd6d2.png)

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kevcunnane** [comment]
@anthonydresser and @abist this seems like an issue in the core Connections viewlet code?

**Comment by kburtram** [comment]
This issue appears fixed on current builds.  Please let us know if you're still impacted by this issue.
