### ISSUE TITLE
Unexpected Error Occurred while Connecting

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6052]
Issue Type: <b>Bug</b>

[2019-06-17 10:34:56.421] [main] [info] update#setState idle
[2019-06-17 10:35:26.428] [main] [info] update#setState checking for updates
[2019-06-17 10:35:26.574] [main] [info] update#setState idle
[2019-06-17 11:14:59.005] [main] [error] webContents#will-navigate: Prevented webcontent navigation

An unexpected error occurred while connecting. Please file an issue with the title 'Unexpected Error Occurred while Connecting' and include the log file /Users/george/Library/Application Support/azuredatastudio/logs/20190617T103456/renderer1.log

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|8.00GB (0.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
schema-compare|Mic|0.3.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks for reporting this! @gengelbms  Could you attach the renderer1.log file that was mentioned in the error? You can also mail it directly to me if you'd rather not attach it here. 

I'm going to close this since we're tracking the issue in #5388

**Comment by gengelbms** [comment]
Where would this file be located on a Mac? (I did not find renderer1.log in search.)


George Engelbeck

Senior Design Researcher | Azure Data Platform

Microsoft Corporation

Mobile: + 1.425.281.0836

<http://aka.ms/weboutlook>

________________________________

**Comment by gengelbms** [comment]
Here is the renderer1.log file:
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/3299702/renderer1.log)

**Comment by Charles-Gagnon** [comment]
Thanks, removed the link since I have it locally.
