### ISSUE TITLE
Support launching Schema Compare from AZURE databases

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6053]
Issue Type: <b>Feature Request</b>

You can launch the Schema Compare extension tool from CONNECTIONS/SERVERS but not from CONNECTIONS/AZURE.

From CONNECTIONS/SERVERS
![image](https://user-images.githubusercontent.com/41927913/59627049-33f9b900-90f2-11e9-820b-ae91d7ab5af7.png)

From CONNECTIONS/AZURE
![image](https://user-images.githubusercontent.com/41927913/59627117-5ab7ef80-90f2-11e9-809e-3094ec1ce5b5.png)

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

**Comment by udeeshagautam** [comment]
Schema compare is available for Azure Databases from server view in viewlet - but not from Azure View

**Comment by udeeshagautam** [comment]
Moving to backlog with other AAD work. We can brink it back as needed.

**Comment by kisantia** [comment]
closing due to lack of interest
