### ISSUE TITLE
Generated script contains syntax errors

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6055]
Issue Type: <b>Bug</b>

1. Compare two databases
2. Select Generate Script
3. Note that the generated script contains syntax errors.

![image](https://user-images.githubusercontent.com/41927913/59628252-07936c00-90f5-11e9-9ec8-6b9255738aeb.png)

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by udeeshagautam** [comment]
This is because SQLCMD support is not available yet. This seems dup for https://github.com/microsoft/azuredatastudio/issues/5140

**Comment by udeeshagautam** [comment]
closing as a dup of SQLCMD request #5140
