### ISSUE TITLE
Make it clear that  the comparison is only showing differences and is not showing a complete compare

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6057]
Issue Type: <b>Feature Request</b>

Make it clear that  the comparison is only showing differences and is not showing a complete compare.

Users who are unfamiliar with the databases being compared need to expand each database to see what objects are present to determine that they are viewing a difference comparison of the two schema.

![image](https://user-images.githubusercontent.com/41927913/59629791-7aeaad00-90f8-11e9-90d9-d03330eb445e.png)

Provide some text in UI telling users that it is a diff view. Perhaps, Source (diff), Target (diff) or something similar.

Azure Data Studio version: Azure Data Studio 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:14:48.724Z)
OS version: Darwin x64 18.6.0

**Comment by yualan** [comment]
@angdesign we should follow up with you on this to figure out how to make differences more clear

**Comment by kisantia** [comment]
closing due to lack of additional interest. Can reopen later if there are more requests
