### ISSUE TITLE
Postgresql Unable to open functions - failed to expand node

### ISSUE THREAD

**Issue by tsrctonyzoc** [microsoft/azuredatastudio#6059]
Couldn't find anything

- Azure Data Studio Version:
1.8.0 on Ubuntu 18.04 LTE and Windows 10
PostgreSQL extension 0.2.0

Steps to Reproduce:

1. Connect to a PostgreSQL server
2. expand database
3. Click on functions
4. Error message "Failed to expand node"

**Comment by Charles-Gagnon** [comment]
This looks to be a dupe of https://github.com/microsoft/azuredatastudio-postgresql/issues/100 so I'm closing this one
