### ISSUE TITLE
Console editor bug

### ISSUE THREAD

**Issue by sfweller** [microsoft/azuredatastudio#6063]
- Azure Data Studio Version:
1.8.0 Commit:  96e21459319000071f0b520439929b218f9fa673de
VS Code 1.34.0
Electron 3.1.8
Node.js: 10.2.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.   Paste the following spark/scala code into the editor window and attempt to run it, by clicking on the 'Run' icon. You will get the following error message:

<console>:4: error: ')' expected but ';' found.
  schema.fields.flatMap(f =&gt; {
                                                ^

This code is valid and it looks like the editor is not parsing nested '(' correctly, as the code snippet contains nested curly braces.

The code is copied from the following page:
https://www.data-engineer.in/bigdata/flatten-dataframes-apache-spark-sql-1/

Here is the code included below:

def flattenSchema(schema: StructType, prefix: String = null) : Array[Column] = {
  schema.fields.flatMap(f =&gt; {
    val colName = if (prefix == null) f.name else (prefix + "." + f.name)
    f.dataType match {case st: StructType =&gt; flattenSchema(st, colName)
       case _ =&gt; Array(col(colName))
    }
  })
}

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
