### ISSUE TITLE
Saved postgres connections switch to Sql Server when connecting

### ISSUE THREAD

**Issue by flipchart** [microsoft/azuredatastudio#6064]
Steps to Reproduce:

1. Create a postgres connection, saved in a server group
1. Disconnect from the connection
1. Click the connection to reconnect and note that the connection type has changed to Sql Server. Other fields are saved (server, username, etc.), although the sql server authentication type is set to windows auth so my postgres username doesn't show until you change the connection type back to postgres

This was working fine (i.e. the connection type was saved correctly) in the version when postgres was first released but newer versions have started exhibiting this problem

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.40.0
azuredatastudio-postgresql|Mic|0.2.0
import|Mic|0.8.0
profiler|Mic|0.8.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks for the report! I've confirmed that this is fixed by 59b0e6737f2f2c85635fc4c452562796eee40b3b so will be fixed in the next release.
