### ISSUE TITLE
Executing statements with no resultset removes focus from sql editor

### ISSUE THREAD

**Issue by flipchart** [microsoft/azuredatastudio#6065]
Similar to #103 but for statements which do not return a result set (e.g. updates)

Steps to Reproduce:

1. Type an update command into the query window
1. Execute the statement using F5
1. Notice that focus is no longer on the query editor

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17134

<details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.40.0
azuredatastudio-postgresql|Mic|0.2.0
import|Mic|0.8.0
profiler|Mic|0.8.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks for the report @flipchart! This was a bug in the latest release but has been fixed and focus should stay in the query window as designed in the next release.
