### ISSUE TITLE
Copy the text output for suggested indexes from "Explain" query

### ISSUE THREAD

**Issue by hantusk** [microsoft/azuredatastudio#6068]
When evaluating which indexes to create, SQL Server comes with good suggestions when using "Explain" in the query editor. However these suggestions cannot be copied, as text can not be selected from the "Query plan" tab.

**Describe the solution or feature you'd like**
If the text was selectable, it would be a benefit to copy the output

**Describe alternatives you've considered**
I have written the text manually, because i could not select it. I also considered taking a screenshot and running it through OCR, so I would not have to type everything out.

**Comment by yualan** [comment]
We have a new extension coming out that you might want to try. Stay tuned for July release.

**Comment by vicmonmena** [comment]
Hi! @yualan what about the extension. I'm looking forward to try it. It would be so great if I it works similar as works on SQL Server Management Studio where you can click on right button and click on "Missing Index Details" option that open a new tab with the SQL of the recommended Index.

Regards!

**Comment by wy193777** [comment]
Any update on this?

**Comment by aasimkhan30** [comment]
This is fixed in the new execution plan feature. You can just click on the recommendation, and it will open the missing index query in a new window.
![image](https://user-images.githubusercontent.com/6816294/163856977-0d7a3001-a9c0-4fe6-ac70-4fd2ee7ebd84.png)
