### ISSUE TITLE
Cannot cancel a query

### ISSUE THREAD

**Issue by Arthurvcs** [microsoft/azuredatastudio#6077]
Issue Type: <b>Bug</b>

I start to run a query and i can´t cancel it, cause the cancel button are disabled without reason. My query is running about a 58 minutes and my database were locked because this unexpected behavior. 
I hope that you fix that problem. Thanks.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3470S CPU @ 2.90GHz (4 x 2894)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (1.18GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.3.3

</details>

**Comment by ek1977** [comment]
This is a common problem that has existed since the start of this project.  Nothing more frustrating than not being able to stop the query if a mistake was made.

**Comment by Charles-Gagnon** [comment]
Can you give us more information about when this occurs? It seems to work fine for me 

![screen](https://user-images.githubusercontent.com/28519865/66079123-4fa99380-e518-11e9-83f9-fdf02d57af48.gif)

**Comment by Arthurvcs** [comment]
@Charles-Gagnon, maybe was the version that i was using...
After i update, that problem doesn't occurs anymore! 

Thank u guys! 👍

**Comment by Arthurvcs** [comment]
1
