### ISSUE TITLE
Save not working from the File Menu

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6078]
Issue Type: <b>Bug</b>

It seems that Save from the File Menu is not working and when I try to close the Notebook it prompts me to save again.

![image](https://user-images.githubusercontent.com/22312581/59711488-11ce6c80-91c0-11e9-8717-974d93890e5b.png)

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:46:28.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (22.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.13.2
azdata-sanddance|msr|1.2.0

</details>

**Comment by kevcunnane** [comment]
This will be fixed in https://github.com/microsoft/azuredatastudio/pull/6096

**Comment by kevcunnane** [comment]
Fixed, should be testable in today's insiders (though I think some smoke tests failed so don't have the build yet).
