### ISSUE TITLE
Provide a Tools menu to launch the compare extension

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6079]
Issue Type: <b>Feature Request</b>

For comparing dacpac files it is unintuitive to launch the compare tool from a database that you will not be using in the compare.

As an alternative, consider adding a Tools menu (or something like this) to ADS that lets you launch tools that do have a logical launch context.

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by yualan** [comment]
@udeeshagautam this seems like a reasonable suggestion, let's review if this meets the bar for July or August.

**Comment by udeeshagautam** [comment]
Checking if its possible from extension

**Comment by udeeshagautam** [comment]
This is not possible from extensions
