### ISSUE TITLE
Use headers  to provide more meaningful information like the source names and target names.

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6081]
Issue Type: <b>Feature Request</b>

It can be ambiguous which code panel was from the source and which was from the target.

![image](https://user-images.githubusercontent.com/41927913/59713502-7390d580-91c4-11e9-8215-06b96ddda88c.png)

Use the headers labeled "Object Definitions" to provide more meaningful information like the source names and target names.

PRIORITY - One participant reported that he initially was not sure which code panel was the source and which was the target. 

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by yualan** [comment]
@udeeshagautam and @kisantia let's review this in our tracking as well.

**Comment by kisantia** [comment]
closing since there haven't been any upvotes on this and this is the same as style as SSDT
