### ISSUE TITLE
Provide a confirmation step for Apply

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6082]
Issue Type: <b>Feature Request</b>

One participant - a SQL MVP - asked for a confirmation for the Apply action.

The concern was that an action applied against a production database could have great and maybe unintended consequences, so a confirmation is warranted.

(Note another participant asked for the ability to rollback an Apply for similar reasons.)

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by abist** [comment]
@gengelbms Which feature is this for? Schema Compare?

**Comment by yualan** [comment]
This one is also a good candidate if it is easy to implement.

**Comment by udeeshagautam** [comment]
Available in the latest builds
