### ISSUE TITLE
Provide a summary of the actions for an Apply

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6083]
Issue Type: <b>Feature Request</b>

One partcipant asked a summary as part of Apply that told him what the apply would do.

This could be included as part of the confirmation step. This could extend https://github.com/microsoft/azuredatastudio/issues/6082

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by yualan** [comment]
This is a good feature ask, we can consider this for 1.0 release of schema compare.
