### ISSUE TITLE
./python3 -m pip install fails

### ISSUE THREAD

**Issue by nigelainscoe** [microsoft/azuredatastudio#6084]
- Azure Data Studio Version:
Version: 1.8.0 (user setup)
Commit: 96e214593190071f0b520439929b218f9fa673de
Date: 2019-06-06T01:59:30.203Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17763
Steps to Reproduce:

1. Attempt to install a Python module with Pip

The following is displayed

(base) PS>: '
>> --------------------------------------------------------------------------------
>> This is the sandboxed instance of python used by Jupyter server.
>> To install packages used by the python kernel use './python3 -m pip install'
>> --------------------------------------------------------------------------------
>> '
At line:4 char:53
+ To install packages used by the python kernel use './python3 -m pip i ...
+                                                     ~
Missing property name after reference operator.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : MissingPropertyName
 
(base) PS>./python3 -m pip install lxml
./python3 : The term './python3' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the 
name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ ./python3 -m pip install lxml
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (./python3:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by corivera** [comment]
This terminal pop up has been replaced with a dedicated package installer dialog.
