### ISSUE TITLE
When a new code comparision is started the output panel blocks the lower part of the UI.

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6085]
Issue Type: <b>Bug</b>

It is disorienting when the Output Panel blocks your view of code comparison results.

When a new code comparision is started the output panel blocks the lower part of the UI.

![image](https://user-images.githubusercontent.com/41927913/59714456-8e644980-91c6-11e9-996c-c3a0224fafaa.png)

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) M-5Y51 CPU @ 1.10GHz (4 x 1200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|8.00GB (0.11GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kisantia** [comment]
closing due to lack of additional interest. Can reopen later if there are more requests
