### ISSUE TITLE
Provide a search/filter for find options and option types

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6086]
Issue Type: <b>Feature Request</b>

Add a search box that finds and filters the options (or object types) to those with matches to your search string.

![image](https://user-images.githubusercontent.com/41927913/59714803-53aee100-91c7-11e9-8a63-e57ddb6b9b90.png)

Participants in the Schema Compare study asked for an easy way to find options without having to scroll through the list.

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by udeeshagautam** [comment]
We have a task for this : https://github.com/microsoft/azuredatastudio/issues/5227

**Comment by yualan** [comment]
Closing as dupe
