### ISSUE TITLE
Provide the ability to name, save, and apply option profiles

### ISSUE THREAD

**Issue by gengelbms** [microsoft/azuredatastudio#6088]
Issue Type: <b>Feature Request</b>

Often the compare options set depend on the context:

1. Is the database a transactional or analytic database?
2. Is the database being compared in dev, test, or production?

Addtionally, you may want to focus your compare to certain object types: Tables, Views, Functions, ....

The schema compare tool could be improved by:

1. Support a simple set of Option/Object setings:
- Table compares
- View compares
- Schema compares
- Trigger compares
- Index compares

2. Let users define,  name, and apply customer sets of options/object settings.

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.6.0

**Comment by yualan** [comment]
This will be handled from SCMP file support https://github.com/microsoft/azuredatastudio/issues/5223. Closing as dupe
