### ISSUE TITLE
Modify Markdown cell while code cell is running

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6091]
Issue Type: <b>Bug</b>

Is this possible to do? While one code cell is running that I modify the markdown cell.

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (449cd9ea27d49b66667bda043d467adb9377b734, 2019-06-17T07:46:28.633Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1620 0 @ 3.60GHz (8 x 3591)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.93GB (21.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.13.2
azdata-sanddance|msr|1.2.0

</details>

**Comment by chlafreniere** [comment]
@ronychatterjee what happens if you try to do this today?

Also, a customer scenario would be fantastic 😄

**Comment by ronychatterjee** [comment]
@chlafreniere it stops me from doing anything as the cell is running.

Also when a cell is running for 30 mins you might want to quickly change something in the markdown cells. Perfect use case.

**Comment by ronychatterjee** [comment]
Closing it as it seems to be running fine on Windows.
