### ISSUE TITLE
Multiple database support using extensions: SQL, NoSQL, GraphDB, Real-Time Database

### ISSUE THREAD

**Issue by rajeev-kumar-sharma** [microsoft/azuredatastudio#6098]
**Is your feature request related to a problem? Please describe.**

**Describe the solution or feature you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rajeev-kumar-sharma** [comment]
Provide extensions for open source databases of all kind
1. MongoDB
2. Cassandra
3. Redis
4. Hadoop HBase
5. Neo4j
6. MemcacheDB

and many more

**Comment by Charles-Gagnon** [comment]
Per #56 support for other databases should be created as separate issues with the title [Database Support] <Name> (example #4918)

Any from your list that don't currently have an open issue like that should be created so we can track each request separately. Thanks!
