### ISSUE TITLE
Reuslts Pane looses its height when "Go to Definition" is used

### ISSUE THREAD

**Issue by luismiguelgilbert** [microsoft/azuredatastudio#6100]
Issue Type: <b>Bug</b>

Hi!

1) Run a query and resize results pane height
2) Use context menu option "Go to Definition"
3) Table definition tab shows (untill this point everything is ok)
4) Return to previous tab. At this point, results height resizes to something different.

![image](https://user-images.githubusercontent.com/20174916/59777524-777f2f00-927a-11e9-8e93-a2131e117089.png)

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.70GB (5.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|67%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.40.0
import|Mic|0.8.0
profiler|Mic|0.8.0
server-report|Mic|0.1.5

</details>

**Comment by kburtram** [comment]
@luismiguelgilbert thanks for filing the bug.  This was an unfortunate regression that got into the June release.

I think https://github.com/microsoft/azuredatastudio/pull/6018 will resolve this.  @anthonydresser are you waiting on anything prior to merging that PR (other than perhaps the failing CI build)?

**Comment by anthonydresser** [comment]
There is a test I need to fix, and I haven't had the time yet. I'll work on getting it in later today or tomorrow.

**Comment by kburtram** [comment]
@anthonydresser thanks!  It would be great to be able to point folks to the insiders build to pick up the fix.  This issues has been reported a few times now.

**Comment by anthonydresser** [comment]
fixed in the PR mentioned earlier
