### ISSUE TITLE
Add close button for "Connections" panel

### ISSUE THREAD

**Issue by GrzegorzLyp** [microsoft/azuredatastudio#6114]
Issue Type: <b>Feature Request</b>

There is no close button for connections panel (for others like extension either).

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:47:16.994Z)
OS version: Windows_NT x64 10.0.18362

![image](https://user-images.githubusercontent.com/29247982/59828151-a9f06100-933a-11e9-9b59-b0d2e11d72e0.png)

**Comment by kburtram** [comment]
@GrzegorzLyp the viewlet's visibility is toggle-able by clicking on the viewlet's icon in the action bar.  If the viewlet is hidden clicking the icon shows the pane, otherwise, clicking closes the pane.  Please let me know if this doesn't address your concern.
