### ISSUE TITLE
Task view icons get hidden if message is long

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#6116]
- Azure Data Studio Version:
Dev Builds

Steps to Reproduce:

If a task fails with long error (or has a long message) the task view icons  get hidden

![image](https://user-images.githubusercontent.com/46980425/59871151-b7621700-934b-11e9-8217-07c80fec1a5c.png)

**Comment by udeeshagautam** [comment]
Tagging as Data Explorer because we don't have a task view label

**Comment by abist** [comment]
@anthonydresser

**Comment by yualan** [comment]
This seems like an easy fix, adding to Planning
