### ISSUE TITLE
"View: Split Editor" doesn't work. 

### ISSUE THREAD

**Issue by realfreebird** [microsoft/azuredatastudio#612]
- SQL Operations Studio Version: sqlops 0.25.4 (475904d2b2e32e7f91284c199234399ee7d5d418, 2018-01-16T20:51:42.102Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Press F1 to open the command pallete
2. Choose "View: Split Editor"

**Comment by alanrenmsft** [comment]
I am not able to reproduce the issue anymore, Please reopen if you are still having the issue.
