### ISSUE TITLE
MSSQL config lower/uppercase formatting doesn't change

### ISSUE THREAD

**Issue by tysun** [microsoft/azuredatastudio#6121]
I'm using ADS on latest macOS + SQL Server inside Docker container. 

I don't want the ADS query code completion to force uppercase keywords.

I have changed the setting from none to lowercase and restarted ADS but the changes do not take effect.  

Please advise.

**Comment by kburtram** [comment]
@tysun I couldn't reproduce this issue.  Could you please confirm you're setting the below option?  I think the one you've mentioned controls the "Format Document" commands.

Check this setting
<img width="425" alt="Screen Shot 2019-06-21 at 5 55 41 PM" src="https://user-images.githubusercontent.com/599935/59957508-d1841e00-944d-11e9-8c77-54341a2d2bea.png">

Suggestions should now be lower-case
<img width="591" alt="Screen Shot 2019-06-21 at 5 53 54 PM" src="https://user-images.githubusercontent.com/599935/59957504-ccbf6a00-944d-11e9-9ebf-17b1aaccbba5.png">

**Comment by tysun** [comment]
Yes! That's the trick!  Thank you! I searched the settings bar for "format" so  I never saw that option. Then of course it says `Datatype Casing` and `Keyword Casing` so I thought I was selecting the correct setting.
