### ISSUE TITLE
Query Results tab is shown blank while script is executing

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6126]
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Run a SQL script that takes a while to complete and that doesn't generate a resultset.  For example, the Northwinds install script from https://raw.githubusercontent.com/microsoft/sql-server-samples/master/samples/databases/northwind-pubs/instnwnd.sql

Expected: Results tab is never shown and the Messages tab is shown while script is executing.  The Results tab should only show up when there are results.

Actual: Results tab is show blank and Messages are logged in the background.

<img width="859" alt="Screen Shot 2019-06-21 at 11 17 17 AM" src="https://user-images.githubusercontent.com/599935/59943250-987c8700-9416-11e9-86bd-058a18d2b528.png">

**Comment by yualan** [comment]
Agreed, let's review if we can get this into the July or August milestone.

**Comment by kburtram** [comment]
Moving into July to discuss in triage today.  I think this is going to annoy users.

**Comment by kburtram** [comment]
@Charles-Gagnon @anthonydresser this issue repro's on June 1.8 release.  Since no external users have reported perhaps this isn't annoying folks too much to require a fix at this point for July.

I still think we should investigate a fix and consider if it's trivial\very-low risk.  But likely this is fine to punt to August.

**Comment by Charles-Gagnon** [comment]
Given how small the fix is I think we should include this for July. Do you agree @kburtram @anthonydresser ?

**Comment by kburtram** [comment]
I think it looks like a good candidate since the fix is pretty simple.  I'll run some tests from the dev branch to see if I can hit any side-effects.

**Comment by kburtram** [comment]
One of the side-effects with the current proposed fix is that the results tab doesn't show until the entire query script is complete.  The correct behavior is the results tab shouldn't show until at least one resultset is available.  This will cause delays showing results with long running scripts and effective break the "resultset streaming" work.

Observing the behavior of the below script with and without the change illustrates the issue.

```SQL
-- this resultset should show prior to the delay
SELECT * FROM sys.all_columns;

GO

WAITFOR DELAY '00:00:05'

SELECT * FROM sys.all_columns;

GO 

SELECT * FROM sys.all_columns;
```

**Comment by Charles-Gagnon** [comment]
Good catch - while that probably isn't hard to fix either at this point I say let's just hold off until the August release so that we can make sure to nail down the experience. Trying to reduce churn in behavior of the output panes as well is something we should strive for since that's so core to people's workflow that constantly changing it is likely just as annoying as the issues themselves.

**Comment by kburtram** [comment]
I agree.  The issue isn't an in-cycle regression and the impact isn't high enough that it's worth taking a fix at this point.  Let's continue to work through the PR and that will give plenty of time to verify corner-cases for August, or a potential hotfix release if needed.
