### ISSUE TITLE
Notebook crashing ADS !

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6136]
Issue Type: <b>Bug</b>

Whenever I am having long running Notebooks being run or re-run this crashes ADS. There is no way out from this stage and the only option is to Close the window.

 At that stage you will lose the state of the Notebook and need to re-run again deleting resources and re-creating the resources.
 
You might need to run couple of times to repro the crash. Seems weird but GitHub is not letting me attach the Notebook file.

<img width="898" alt="image" src="https://user-images.githubusercontent.com/22312581/59970752-f9918100-9522-11e9-868d-c551a106abfd.png">

Azure Data Studio version: Azure Data Studio 1.9.0-insider (cecc899949d30fd28f1636cdb65e3a6e17e46a3a, 2019-06-18T07:15:07.629Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.46GB free)|
|Process Argv|-psn_0_11135646|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.0
sql-vnext|Mic|0.14.0
azdata-sanddance|msr|1.2.0
plan-explorer-ads|Sen|0.0.1

</details>

**Comment by chlafreniere** [comment]
@ronychatterjee please let me know if ADS crashes on you with any messages similar to the following:

![image](https://user-images.githubusercontent.com/40371649/63894070-9566bf80-c9a0-11e9-981d-9a35ea875546.png)

If it's unresponsive, we'll have to check what happens in the Jupyter viewer as well to determine if any of those issues are ADS-specific.
