### ISSUE TITLE
Recents list moves around when clicking

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/azuredatastudio#6142]
Issue Type: <b>Bug</b>

When I first click on an entry in the Recent Connections list, the list moves up by a few pixels. This is weird, but it also causes problems because I can double-click on a connection to use it. If I double-click close to the bottom of a connection, it may move enough that I end up connecting to the wrong database.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.49GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.0
firstresponderkit|dre|0.4.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.40.0
import|Mic|0.8.0
profiler|Mic|0.8.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.3.2

</details>

![AzureDataStudioRecents](https://user-images.githubusercontent.com/10893522/60003859-cad2f200-966b-11e9-8626-999195149884.gif)

**Comment by kburtram** [comment]
I am not able to observe this behavior on the current build.  We have significantly updated this UX since the issue was created.  Please let us know if the issue is still impacting your scenario.
