### ISSUE TITLE
[Accessibility]A11y_AzureDataStudio_MapDataSrcObjects_Keyboard: On expanding tree view items with the help enter key ,keyboard focus directly shift to the fifth "Summary" screen.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [microsoft/azuredatastudio#6156]
[Check out Keros!](https://microsoft.sharepoint.com/teams/msenable/Pages/accessibility-tools.aspx) - Identify accessibility bugs before check-in and make bug fixing faster and easier.

GitHubTags: #A11yMAS; #A11yTCS; #MAS3.2.2; #A11y_AzureDataStudio; #MacOs; #DesktopApp

**Environment Details**:
Application name: Azure Data Studio
Version: 1.9.0-insider (user setup)
Commit: 2ca39b5
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS :MacOS Mojave 10.14.5
**Additional Details**:
Tools Name: Keyboard
MAS References: MAS3.2.2
**Steps to Reproduce**:
Install the app Azure Data Studio.
Enable SQL server2019 preview->select table from the database->Create External Table screen should open->Next button->Create Database Master Key screen should open->click on next button->fill all the required details->click on next button.
Select any tree view item from left panel using arrow key and press enter.
Observe that keyboard focus directly shift to fifth "Summary" screen.
**Actual**:
On expanding tree view items with the help enter key ,keyboard focus directly shift to the fifth "Summary" screen. But when same thing is performed using mouse ,keyboard focus remains on the same screen.
**Expected**:
On expanding tree view items with the help enter key ,keyboard focus remains on the same screen .
User Impact:
Keyboard user will get confuse with the unauthorize behaviour of the expand tree view.
**Recommendation**:
Please refer the following snippet link for fixes:
https://microsoft.sharepoint.com/teams/msenable/mas/Pages/browse-fixes.aspx
**MAS Reference** :
MAS3.2.2:
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={24cbfff7-374e-42e6-b9ab-d87fcd53b3e8}
**Attachment for Reference**:
[6156_AccessibilityA11y_AzureDataStudio_MapDataSrcObjects_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3325280/6156_AccessibilityA11y_AzureDataStudio_MapDataSrcObjects_Keyboard.pptx)

**Comment by udeeshagautam** [comment]
Dup of https://github.com/microsoft/azuredatastudio/issues/6153

**Comment by Charles-Gagnon** [comment]
@AccessibilityTestingTeam-TCS - I'm closing this as a duplicate, see #6153 for the status of this issue
