### ISSUE TITLE
Script Out Table Triggers individually

### ISSUE THREAD

**Issue by Calidus** [microsoft/azuredatastudio#616]
There is no way to script out Triggers on tables either individually or the whole table as in #491.

- SQL Operations Studio Version: sqlops 0.24.1 (af2414efcb485ab5e435d1db693d3f7569c48453, 2017-12-19T02:19:09.998Z)
- OS Version: Windows_NT x64 10.0.14393
---

Steps to Reproduce:

1. Select a Table
2. Expand the Triggers folder
3. Right click a Trigger
4. "Script as Create" is missing

**Comment by kburtram** [comment]
Triggers can now be scripted individually with PR https://github.com/microsoft/azuredatastudio/pull/16885.  This will be in the next release or the current insiders build.
