### ISSUE TITLE
Search functionality in Books

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#6160]
Book viewlet should have a search tab that allows the user to search through all notebooks and markdown files in a book.

**Comment by Charles-Gagnon** [comment]
@MaddyDev Can we close this now that the initial feature work is completed?

**Comment by MsSQLGirl** [comment]
@chlafreniere , @MaddyDev - I agree with @Charles-Gagnon here. I think this can be closed? 
There are additional improvements on search in general but they have other items to track, yes? :)
