### ISSUE TITLE
Hung on Starting Service

### ISSUE THREAD

**Issue by nbsenno** [microsoft/azuredatastudio#6177]
Issue Type: <b>Bug</b>

Recently installed Azure Data Studio on laptop running Windows 10 Enterprise 

When launching the application the "Starting service" propmpt in the lower lefthand corner (in the purple band) never resolves. 

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.15063

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5600U CPU @ 2.60GHz (4 x 2594)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (10.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by nbsenno** [comment]
Update, the Starting Service is getting hung up on the mssql extension

**Comment by alanrenmsft** [comment]
@nbsenno do you see any errors in the console? you can open it from main menu -> Help> Toggle Developer Tools. and switch to the Console tab.

**Comment by nbsenno** [comment]
@alanrenmsft yes the main error is `Error: spawn EPERM`

```json
ApplicationInsights:Sender 
Array(1)
0:
code:"ECONNRESET"
errno:"ECONNRESET"
syscall:"read"
__proto__:Object
length:1
__proto__:Array(0)
```
The errors are in Azure Data Studio\resources\app\node_modules\zone.js\dist\zone-node.js
Besides that I've accidentally hidden the errors and can't figure out how to see them again

**Comment by alanrenmsft** [comment]
@nbsenno  is it a consistent repro for you? the error you pasted is for telemetry, which is very unlikely to cause the problem. can you launch ADS again and send us a screenshot of the console window?

**Comment by nbsenno** [comment]
Yes this problem occurs every time I open Azure Data Studio. Even after I uninstall/reinstall, restart, etc. 

I've attached a screenshot. Again, I'm not sure how to unhide all of the error information 

![Azure Data Studio Error](https://user-images.githubusercontent.com/47370478/60266942-b0d52180-98ae-11e9-9098-97e054276671.PNG)

**Comment by kburtram** [comment]
Closing older issues.  I don't see anything in the provided logs/screenshots that jumps out as a potential cause for a startup hang.  Please let us know if you're still experiencing this behavior on current builds.  Thanks!
