### ISSUE TITLE
openssl Issue in Mac

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#6180]
- Azure Data Studio Version:
I tried 1.8.0 as well as latest insider build on my Mac. I am getting the following error:

Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error: 1, StdErr Output: Traceback (most recent call last):
  File "/Users/alanren/azuredatastudio-python/0.0.1/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/Users/alanren/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/notebook/notebookapp.py", line 62, in <module>
    from tornado import httpserver
  File "/Users/alanren/azuredatastudio-python/0.0.1/lib/python3.6/site-packages/tornado/httpserver.py", line 29, in <module>
    import ssl
  File "/Users/alanren/azuredatastudio-python/0.0.1/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: dlopen(/Users/alanren/azuredatastudio-python/0.0.1/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so, 2): Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /Users/alanren/azuredatastudio-python/0.0.1/lib/python3.6/lib-dynload/_ssl.cpython-36m-darwin.so
  Reason: image not found

**Comment by corivera** [comment]
@MaddyDev was this the same Python issue you had?

**Comment by MaddyDev** [comment]
Yes! I asked @yualan to add this the docs.

**Comment by alanrenmsft** [comment]
@MaddyDev @yualan , what is workaround here?

**Comment by alanrenmsft** [comment]
workaround is to: brew install openssl

**Comment by MaddyDev** [comment]
Closing this now, we haven't seen anyone complain since then and am not able to repro it either.
