### ISSUE TITLE
Add context menu to allow delete a database

### ISSUE THREAD

**Issue by EdiWang** [microsoft/azuredatastudio#6183]
**Is your feature request related to a problem? Please describe.**
I usually delete and recreate databases on my dev machine. I was used to SSMS that can right click a database and choose "Delete"

![image](https://user-images.githubusercontent.com/3304703/60238797-345a3700-98de-11e9-90b2-ef93a965d0bd.png)

**Describe the solution or feature you'd like**
Please consider add the same menu to Azure Data Studio, currently there are no context menu for deleting a database from UI.

![image](https://user-images.githubusercontent.com/3304703/60238844-55bb2300-98de-11e9-92db-2bef69c443d2.png)

**Describe alternatives you've considered**
N/A

**Additional context**
I am on version 1.8.0

**Comment by Anduin2017** [comment]
If the delete feature is requested, how about the `Rename` feature?

**Comment by aasimkhan30** [comment]
dup of #109
