### ISSUE TITLE
Drag query window outisde of Data Studio to it's own separate window. 

### ISSUE THREAD

**Issue by edraji** [microsoft/azuredatastudio#6184]
- Azure Data Studio Version:

Steps to Reproduce:
It is self explanatory, why can't I drag the query window outside of the application so I can make use of multiple screens when working with multiple queries, its a very simple thing that both Visual Studio and Management Studio have.

**Comment by anthonydresser** [comment]
There is a open suggestion to allow this in vscode #10121 (which we are based on). It sounds like it is not a simple feature to add. I'm going to say this is an upstream issue.

**Comment by kburtram** [comment]
This behavior is inherited from the vscode platform we are built on.  We'd prefer to see fixes like this taken upstream and then we can pick up in a future source code merge.  Thanks for opening this suggestion!
