### ISSUE TITLE
Could not find query file...

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6188]
Issue Type: <b>Bug</b>

When viewing the "Server Reports" tab, all sections just show an error.  The path to the query files is messed up.  See screenshot.

![image](https://user-images.githubusercontent.com/85186/60288875-5e0d6100-98d2-11e9-9595-f3291ccf9354.png)

I also have "Managed Instance" and it has a similar error.

![image](https://user-images.githubusercontent.com/85186/60288923-7b422f80-98d2-11e9-9952-94bed1c81a20.png)

If I select "Refresh" in any section, the error changes to: "Error: Value cannot be null. Parameter name: queryText"

![image](https://user-images.githubusercontent.com/85186/60289025-b6dcf980-98d2-11e9-9b5c-42856fb21ed6.png)

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by glittle** [comment]
After closing Azure Data Studio (ADS) and opening it again, these errors were gone.  The extensions had been added but the ADS had not been closed.

Should have some sort of notice that the extensions may not work correctly until the ADS is restarted.

**Comment by kburtram** [comment]
@glittle good point that the extensions should indicate a restart is required if they don't work properly after install.

**Comment by kburtram** [comment]
Closing this older issue as it resolved itself after ADS restart.  Thanks for reporting this!
