### ISSUE TITLE
View -- incorrectly marked as changed in Schema Compare

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6190]
Issue Type: <b>Bug</b>

Some views show up as Changed, but the Object Definition windows show no changes at all.  They should not be included in the list.

Left database: SQL 2008 R2. Right database: Azure SQL.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (19.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by glittle** [comment]
As per #6195, this is for the Schema Compare extension.

**Comment by kisantia** [comment]
@udeeshagautam I think this got fixed in #6104. Can you confirm?

**Comment by udeeshagautam** [comment]
@kisantia .. yeah I think one reason could have been the dictionary index mistamtach which is fixed (https://github.com/microsoft/azuredatastudio/pull/6236) but not sure if there was anything else here. Lets try to repro once more before closing.

**Comment by udeeshagautam** [comment]
This should be fixed.
