### ISSUE TITLE
Schema Compare should support "Select all"

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6191]
Issue Type: <b>Feature Request</b>

Should have a way to "Select All" and then choose to Include or not Include.

Simplest UI would be to include a checkbox in the heading of the column that sets all the checkboxes.

![image](https://user-images.githubusercontent.com/85186/60290829-d544f400-98d6-11e9-94df-040ad23a04b7.png)

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by glittle** [comment]
As per #6195, this is for the Schema Compare extension, not the Query Editor.

**Comment by kisantia** [comment]
closing as dup of #10430
