### ISSUE TITLE
Wrong objects included in script due to not including SqlProcs

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6192]
Issue Type: <b>Bug</b>

I did a comparison and ended up with changes to 3 views and lots of stored procedures.

I deselected all items except for one view.

When I clicked to "Generate Script", that view was included in the script (as expected), but the LAST stored procedure in the list was also included in the script, even though it was NOT selected to "Include".

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (18.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by glittle** [comment]
No, this is not related to issue 556.

**Comment by glittle** [comment]
This is for the Schema Compare extension.

**Comment by udeeshagautam** [comment]
Seems like a DacFx issue - failing to exclude SqlProcs (was able to repro on SSDT too)

**Comment by esben2000** [comment]
I have the same problem, also with other objects. It seems like the 'Include' checkboxes is not respected very well.

**Comment by kisantia** [comment]
@glittle  @esben2000 is this still happening? We made a fix(https://github.com/microsoft/azuredatastudio/pull/8042) last year to make it more clear when an object can't be excluded. Previously, the schema compare differences table wouldn't get updated if an exclude request failed due to included dependencies, which could be why objects looked like they were excluded but still showed up in the generated script.
