### ISSUE TITLE
Not Copy, Not Retry all data

### ISSUE THREAD

**Issue by shpsyte** [microsoft/azuredatastudio#6193]
- Azure Data Studio Version:

Steps to Reproduce:

1. Just use sp_helptext <procedure>

The result is not copied to clipboard;
the connection lost most of the time;
Ctrl+Tab clear the result on the previous tab;

**Comment by kburtram** [comment]
@shpsyte I wasn't able to repro this issue.  To clarify, I'm trying the following.

1. Open two new queries.  
2. Run `EXEC sp_help` in one and a different query in the other.
3. Select all in the first resultset from sp_help and copy with Ctrl-C
4. Paste copied content into text editor
5. Use Ctrl-Tab to switch back and forth between the two edtiors.

All the above seemed fine in today's insider build.  Please let me know if I missed something in the repro.  Thanks!

**Comment by shpsyte** [comment]
hum.. Thank you, seems that can be a problem in my PC... However, I'll check for more details about it.
