### ISSUE TITLE
Issue Reporter does not report on Extension

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6195]
- Azure Data Studio Version: 1.8.0

Steps to Reproduce:

1. Use "Report Issue" from the "Help" menu.
2. Select an extension
3. Submit to GitHub

When I filled out the "Issue Reporter" dialog in the Azure Data Studio, I specified the extension that this is related to.  However, I don't see that information in the Issue in GitHub.

![image](https://user-images.githubusercontent.com/85186/60295317-adf32480-98e0-11e9-884f-be1330001253.png)

**Comment by glittle** [comment]
This is not related to issue 592.

**Comment by kburtram** [comment]
It looks like VS Code is using that option to redirect issues directly to the extensions' GitHub repos.  Since many of our extensions are built from this repo it doesn't provide any value in this scenario.  We can consider updating this feature to include the selected extension metadata.
