### ISSUE TITLE
Manage Packages "Add new" option is truncating the text box.

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6199]
Issue Type: <b>Bug</b>

Why is the text box being truncated?

<img width="303" alt="image" src="https://user-images.githubusercontent.com/22312581/60307618-3500c680-98fa-11e9-9975-9a6f25581ddb.png">

Azure Data Studio version: Azure Data Studio 1.9.0-insider (83410565da1992e6d96ebf61b112fe0a13c44f9a, 2019-06-21T18:27:33.029Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.0
import|Mic|0.8.0
sql-vnext|Mic|0.14.0
azdata-sanddance|msr|1.2.0
plan-explorer-ads|Sen|0.0.1

</details>

**Comment by corivera** [comment]
@ronychatterjee Can you provide some more info here? Is the issue just the length of the input box?
