### ISSUE TITLE
Save Options in "Schema Compare"

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6211]
Issue Type: <b>Feature Request</b>

When using "Schema Compare", there are options to adjust for the comparison.  After closing and re-opening Azure Data Studio, those options seem to be reset.

How can I save those options?  

As a mimimum, they could be saved in ADS for all comparisons.  

Ideally, they could be saved into named files that I can choose between.

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by udeeshagautam** [comment]
@yualan The options/exclude-includes and  should be able to saved as SCMP files. Should we keep this open or close this. (Marking it for July)

**Comment by udeeshagautam** [comment]
Saving options as SCMP file is available in latest release. Closing this.
