### ISSUE TITLE
Schema Compare - Invalid Script?

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#6214]
Issue Type: <b>Feature Request</b>

The script created to run against a SQL Server includes lines like:

   ` :setvar DatabaseName "MyDatabase"`

When attempting to Run the script directly in the edit window, SQL rejects those lines with "Incorrect syntax near ':' "

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment]
Thanks for the feedback, this is currently being tracked as adding support for sqlcmd #5140 so I'll close this one
