### ISSUE TITLE
Notebook - ability to copy result/cell value

### ISSUE THREAD

**Issue by subashsivaji** [microsoft/azuredatastudio#6225]
Issue Type: <b>Feature Request</b>

In Notebook need ability to 
- copy result/cell value
- copy the entire resultset
- ability "save as csv" the result

 

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by chlafreniere** [comment]
Thanks for the feedback, @subashsivaji. This is currently being tracked by a few issues:

#4536 #5137 

Closing this as a dupe. We're working on adding this functionality at the moment, so it shouldn't be too much longer.
