### ISSUE TITLE
Opened cluster status from the BDC tab in the dashboard & get error:

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#6231]
Issue Type: <b>Bug</b>

ERROR:

Could not start session: No Manager found

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (095f35d07eaae649a4a850c62dc475acd6135f6d, 2019-06-28T18:14:54.653Z)
OS version: Windows_NT x64 10.0.18922

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by yualan** [comment]
This issue was fixed in latest release
