### ISSUE TITLE
Servers search box missing

### ISSUE THREAD

**Issue by acofalc** [microsoft/azuredatastudio#6243]
Issue Type: <b>Bug</b>

Search box on servers side bar is missing, i cannot quick search servers by name. Does anyone have this problem or know how to bring it back?

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3398)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (4.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
cms|Mic|0.2.0
import|Mic|0.8.0
profiler|Mic|0.8.0

</details>

**Comment by abist** [comment]
Hi @acofalc, with the release of the new Data Explorer, we got rid of the search box. However, if you still want to use the search feature, you can use the `Search: Servers` command from the command palette.

**Comment by acofalc** [comment]
Thank you for info. It was an useful and fast way to quickly get to server i want.
