### ISSUE TITLE
Notebooks: need a method for keyboard navigation through cells 

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#6259]
Issue Type: <b>Feature Request</b>

1. Open a notebook that has several cells with at least one code cell.
2. Select the first cell.
3. Using the keyboard only, attempt to move selection to a subsequent cell.
4. Once selection or focus is inside a code cell, focus becomes stuck and there doesn't seem to be a way to move to another cell.

**Expected behavior:** 
(see Jupyter example GIF below)
In the example, keyboard arrows allow for the selection to move through cells. Hitting Enter changes the cell to edit mode, and ESC exits. 

Azure Data Studio version: Azure Data Studio 1.9.0-insider (ac76302d6cb54e9f80ea47eaec63e5b49971f862, 2019-06-25T07:13:47.926Z)
OS version: Darwin x64 18.6.0

![cell-navigation](https://user-images.githubusercontent.com/29785331/60616674-de2a3f80-9d86-11e9-9d3a-f6bc63ff961b.gif)

**Comment by gbritton1** [comment]
I often record my ADS notebook sessions and using the mouse to navigate between cells leads to more editing in post production.  Also, this could be considered an accessibility issue.

FYI the linked issues from Jul 3 do not cover this request

**Comment by chlafreniere** [comment]
This comes up again and again. Moving to March.

**Comment by dr00b** [comment]
Please prioritze! It's very difficult to avoid the mouse given the current situation.

**Comment by shtratos** [comment]
bump! this is basic functionality and makes it very hard to use for people who struggle with making precise mouse movements. Please make the product more accessible.

**Comment by gbritton1** [comment]
Yeah, last activity on this is from March 2020. be nice to see it completed

**Comment by chlafreniere** [comment]
@microsoft/azure-data-studio-notebook-devs any volunteers?
