### ISSUE TITLE
sparkrkernel raises 'Could not start session: EPERM: operation not permitted' error

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#6262]
Issue Type: <b>Bug</b>

Restarted an instance of Azure Data Studio with two notebooks open. Touched nothing and allowed the screen to render. Notebooks rendered very quickly but kernel was loading. After several seconds, received this error:

Could not start session: EPERM: operation not permitted, unlink 'C:\Users\viharp\AppData\Roaming\jupyter\kernels\sparkrkernel\kernel.json'

![image](https://user-images.githubusercontent.com/8250560/60623419-74666180-9d97-11e9-8ab4-09c942b4a795.png)

The kernel indeed did not load for one of two open notebooks. The other loaded successfully. Both are Python notebooks.

![image](https://user-images.githubusercontent.com/8250560/60623432-7f20f680-9d97-11e9-91ee-0dd567d92c54.png)

![image](https://user-images.githubusercontent.com/8250560/60623468-9829a780-9d97-11e9-825b-77f77b82e5c9.png)

Attempting to change the kernel from None shows another error, "Failed to change kernel due to error: Cannot start a session, the manager is not yet initialized"

![image](https://user-images.githubusercontent.com/8250560/60623542-c14a3800-9d97-11e9-9774-dc0841beaf0a.png)
![image](https://user-images.githubusercontent.com/8250560/60623570-d4f59e80-9d97-11e9-9489-60b3f5bafb2a.png)

Logs from above:

  | console.(anonymous function) | @ | C:\Program Files\Azu…t\zone-node.js:2280
-- | -- | -- | --
  | onDidNotificationChange | @ | workbench.main.js:165962
  | _register.model.onDidNotificationChange.e | @ | workbench.main.js:165950
  | fire | @ | workbench.main.js:10023
  | notify | @ | workbench.main.js:170307
  | notify | @ | workbench.main.js:250588
  | handleModelError | @ | workbench.main.js:308565
  | model.onError | @ | workbench.main.js:308498
  | fire | @ | workbench.main.js:10023
  | notifyError | @ | workbench.main.js:161340
  | (anonymous) | @ | workbench.main.js:161551
  | rejected | @ | workbench.main.js:5984
  | ZoneDelegate.invoke | @ | C:\Program Files\Azu…st\zone-node.js:388
  | Zone.run | @ | C:\Program Files\Azu…st\zone-node.js:138
  | (anonymous) | @ | C:\Program Files\Azu…st\zone-node.js:872
  | ZoneDelegate.invokeTask | @ | C:\Program Files\Azu…st\zone-node.js:421
  | Zone.runTask | @ | C:\Program Files\Azu…st\zone-node.js:188
  | drainMicroTaskQueue | @ | C:\Program Files\Azu…st\zone-node.js:595
  | ZoneTask.invokeTask | @ | C:\Program Files\Azu…st\zone-node.js:500
  | ZoneTask.invoke | @ | C:\Program Files\Azu…st\zone-node.js:485
  | emit | @ | events.js:182
  | addChunk | @ | _stream_readable.js:279
  | readableAddChunk | @ | _stream_readable.js:264
  | Readable.push | @ | _stream_readable.js:219
  | onread | @ | net.js:636

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (095f35d07eaae649a4a850c62dc475acd6135f6d, 2019-06-28T18:14:54.653Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.64GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
dacpac|Mic|0.3.0
import|Mic|0.8.0
profiler|Mic|0.9.0
schema-compare|Mic|0.4.0
azdata-sanddance|msr|1.2.0

</details>

**Comment by corivera** [comment]
Closing due to no repro
