### ISSUE TITLE
SsmsMin actions don't work for insiders builds

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6276]
Issue Type: <b>Bug</b>

The check for installation location only checks stable build location - not the new insiders folder. 

Error is something like
```
Error calling SsmsMin with args '-a "sqla:Properties@ Microsoft.SqlServer.Management.Smo.Login" -S "[server ip],1433" -u "Server/Login[@name='[my user]']"' - The system cannot find the path specified.
```

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (cf4dd4878478748bfa52e25594dea26075d6e11c, 2019-07-05T08:12:39.896Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (4 x 3600)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|4.00GB (1.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kburtram** [comment]
Closing out older issues.  Please reactive if this is still impacting your current use case.
