### ISSUE TITLE
French, Korean & Russian Language packs header not formatted

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6277]
![image](https://user-images.githubusercontent.com/28519865/60832746-79e5f200-a171-11e9-8e43-6f4b8c413384.png)

![image](https://user-images.githubusercontent.com/28519865/60832822-b74a7f80-a171-11e9-8064-9623b038df89.png)

![image](https://user-images.githubusercontent.com/28519865/60832845-c5989b80-a171-11e9-815a-8f7e186c131f.png)

Should look like this :

![image](https://user-images.githubusercontent.com/28519865/60832903-e8c34b00-a171-11e9-9c7e-dc9dfdddce97.png)

**Comment by kburtram** [comment]
I see this same issue in the upstream langpacks in VS Code.  I'll see if this a simple markdown update.  Otherwise we'll likely wait for the upstream fix.
