### ISSUE TITLE
Japanese Language Pack header not localized

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6278]
![image](https://user-images.githubusercontent.com/28519865/60832982-1e683400-a172-11e9-8db3-f39a4baab42f.png)

**Comment by kburtram** [comment]
We picked up this content from VS Code and it's also not localized there.  I'll make as upstream and we can determine whether it's worth localizing this string ourselves.

**Comment by kburtram** [comment]
Closing older issues.  We're matching the upstream vscode behavior and will pick this up if it is addressed there.  Thanks!
