### ISSUE TITLE
Japanese Language Pack missing contributions section

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6279]
![image](https://user-images.githubusercontent.com/28519865/60833079-52dbf000-a172-11e9-8d0c-0fa7af4942fd.png)

**Comment by kburtram** [comment]
This issue appears fixed with the latest langpacks.

![image](https://user-images.githubusercontent.com/599935/129786755-2b015bc8-be8e-4d62-939e-1eba44c33789.png)
