### ISSUE TITLE
Azure Data Studio does not remember the cursor position when switching between multiple tabs

### ISSUE THREAD

**Issue by JASM2007** [microsoft/azuredatastudio#6282]
- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/40634806/60835418-05bb4680-a191-11e9-9039-81b2fdd5e214.png)

Azure Data Studio does not remember the cursor position when switching between multiple tabs.  This was fixed months ago and it seem like this bug was reintroduced to Azure Data Studio for some reason.

Steps to Reproduce:

1. Have multiple tabs of files open in Azure Data Studio. 
2. Click on the first tab and ensure there is multiple lines that require you to scroll to the bottom. Then place your cursor at the bottom.
3.  Now click on another tab then click back on the first tab.
4. You will see the azure data studio does not remember when your cursor was at and you will have to scroll back to where you were as.

**Comment by kburtram** [comment]
@JASM2007 this should be fixed in the latest insiders builds.  And will be fixed in the stable build planned for later this week.  Sorry for the inconvenience from this regression.
