### ISSUE TITLE
Any VSIX download link can be opened from VS Code Marketplace

### ISSUE THREAD

**Issue by edelCustodio** [microsoft/azuredatastudio#6296]
- Azure Data Studio Version:

`Version: 1.8.0 (user setup)
Commit: 96e214593190071f0b520439929b218f9fa673de
Date: 2019-06-06T01:59:30.203Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362`

Steps to Reproduce:

Trying to install a "Atom One Dark Theme" I clicked on "download as a .vsix file" link and nothing happens. Same for all links. Event when I clicked on "Preview on GitHub" button to report this bug :P

**Comment by kburtram** [comment]
@edelCustodio please try the following steps to install an extension from the VS Code marketplace:

1. Download the extension from the marketplace using the "Download as VSIX" link
2. Open Azure Data Studio and run the "Install Extension From VSIX Package" from the file menu
3. The extension is usable once a notification message appears confirm the installation is complete

Please let me know if this does not address your question.

**Comment by kburtram** [comment]
Closing based on previous comment.  Thanks!
