### ISSUE TITLE
XML ShowPlan output truncated to 2 MB

### ISSUE THREAD

**Issue by AaronBertrand** [microsoft/azuredatastudio#6299]
Issue Type: <b>Bug</b>

1. Enter 30 copies of this query:
        SELECT * FROM sys.tables;
        SELECT * FROM sys.tables;
        SELECT * FROM sys.tables;
        ... 30 times
2. Click Explain
3. Copy the contents of the XML ShowPlan output in the Results tab
4. Paste to a text editor

You will notice that the text is cut off at 2,097,152 or 2,097,154 characters, often somewhere in the middle of the plan XML for one of the statements. This seems to be an arbitrary cap of XML length.

Azure Data Studio version: Azure Data Studio 1.9.0-insider (e8d4fba3c06614585fcfdb75428f9ea5f5047412, 2019-07-02T16:15:32.307Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2900)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|16.00GB (3.35GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aaomidi** [comment]
I had a hunch about this issue, it was either being caused by the actual table truncating values or the values were all truncated before they entered the table. So far I've found out that the former guess I had isn't correct.

**Comment by aaomidi** [comment]
https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/SqlContext/QueryExecutionSettings.cs#L33 Potentially related to this.
