### ISSUE TITLE
Error expanding node causes connection node to disconnect/collapse

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6300]
1. Connect to a server and attempt to expand a Database node that will throw an error (for example trying to expand a node for a database you don't have access to)
2. The error is displayed and then the connection node is disconnected and collapsed. Clicking on it will reconnect and expand

![screen](https://user-images.githubusercontent.com/28519865/60907228-e58d9500-a22d-11e9-9232-4e0bf5a5d162.gif)

**Comment by lewis-sanchez** [comment]
Closing this issue since access OE nodes that a user is not permitted to access no longer disconnects the connection.
