### ISSUE TITLE
Create External Table Wizard from HDFS not launching on latest insiders build.

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6308]
Issue Type: <b>Bug</b>

When connected to the latest CTP 3.1 cluster and trying to create an external table over HDFS files I am seeing this issue -

<img width="1435" alt="image" src="https://user-images.githubusercontent.com/22312581/60911367-cd227800-a237-11e9-868c-4651dbc514fe.png">
Azure Data Studio version: Azure Data Studio 1.9.0 (47e3761159736d76cfbcc4adfbdd29a80b49623e, 2019-07-06T21:28:05.417Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.09GB free)|
|Process Argv|-psn_0_5186802|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
Closing this as it doesn't repro with the latest test build.
