### ISSUE TITLE
CMS extension 0.3.0 has 0.2.0 in package.json

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6311]
The CMS 0.3.0 extension still has version 0.2.0 in the package.json at https://sqlopsextensions.blob.core.windows.net/extensions/cms/cms-0.3.0.vsix.  And the version doesn't appear to have been bumped either.  I would expect this to cause issues during update.

**Comment by kburtram** [comment]
@abist @alanrenmsft do we know where the current CMS 0.3.0 extension on the BLOB storage came from.  It appears to have been incorrectly packaged.

**Comment by Charles-Gagnon** [comment]
That was me - the build on Friday didn't have the version numbers updated and I didn't want to muck about with modifying the package.json before upload so I just renamed the VSIX and uploaded. I'm uploading the latest versions from the new build drop now which should be correct.

**Comment by kburtram** [comment]
@Charles-Gagnon could you please update the package.json in the repo?  We should get the VSIX files from the build output, which should correctly append the version number from the package.json, IIRC.

**Comment by Charles-Gagnon** [comment]
Yeah I just noticed that...bumped the extension gallery but missed doing the package.json somehow. Sending out PR now.
