### ISSUE TITLE
CMS tree is showing Database nodes twice

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6319]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Add a CMS server and browse through the tree

Expected: The Database folder is only list once

Actual: The Database folder is nested under database nodes

![image](https://user-images.githubusercontent.com/599935/60927329-619fd100-a25e-11e9-99b3-9f77a2e9afb0.png)

**Comment by kburtram** [comment]
@Charles-Gagnon @abist I'm guess is this related to the change to no longer distinguish between Database and Server connections in OE.

**Comment by Charles-Gagnon** [comment]
Yeah - the whole thing seems to be scoped to the Server level. There's the Security and Server Objects folders as well. I bet this is because of my change to default connections to be server-scoped for user DBs instead of DB scoped.

**Comment by Charles-Gagnon** [comment]
Beat me to it =)

**Comment by kburtram** [comment]
Probably we can live with this for July and work through a fix from August.  I don't think it's a good idea to touch that part of the code at this point, IMO.

**Comment by Charles-Gagnon** [comment]
Verified that this is no longer an issue after reverting the server-scoped connection chagnes.
