### ISSUE TITLE
OE connections become disconnected when dragged between server groups

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#632]
SQL Operations Studio Version: February Preview Insiders Build 0.26.1

Steps to Reproduce:
- Create a server group
- Save a connection outside of that server group
- Connect to the saved connection in OE
- Drag the connection into the server group

Expected behavior: The connection remains connected
Actual behavior: The connection appears to become disconnected, but if the password is saved you can still expand and interact with it without reconnecting. If the password is not saved, it will prompt you for the password when you interact with it
![screen shot 2018-02-07 at 2 45 52 pm](https://user-images.githubusercontent.com/3758704/35945756-1bf99f08-0c16-11e8-9536-4b6032bdd1a5.png)

**Comment by kburtram** [comment]
Closing older bugs that are planned for an upcoming milestone.  Thanks!
