### ISSUE TITLE
New Notebook menu item not localized

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6325]
![image](https://user-images.githubusercontent.com/28519865/60928322-c9a3e680-a261-11e9-882c-f7697aabe75a.png)

**Comment by Charles-Gagnon** [comment]
Oh right, langpack is just for ADS - not extensions. Closing this for now then.

**Comment by kburtram** [comment]
Let's leave this bug open.  Though the strings are currently not expected to be localized we still want to track fixing this.
