### ISSUE TITLE
File Menu Items not localized

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6329]
Likely an upstream issue but should investigate 

![image](https://user-images.githubusercontent.com/28519865/60928778-7d59a600-a263-11e9-87f7-852bccbe6dc9.png)

![image](https://user-images.githubusercontent.com/28519865/60928834-a8dc9080-a263-11e9-9561-b1724737d7a4.png)

**Comment by kburtram** [comment]
This UI appears to be correctly localized on current builds.  Please let us know if you're still seeing this issue.
