### ISSUE TITLE
New Query string not consistently localized

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6338]
Repros in Spanish - haven't checked other languages 

File Menu (Nuevo archivo)

![image](https://user-images.githubusercontent.com/28519865/60929372-f2c67600-a265-11e9-918b-fb9b71f3cdf1.png)

Context Menu (Nuevo consulta)

![image](https://user-images.githubusercontent.com/28519865/60929394-08d43680-a266-11e9-94cc-cb0010c1a4ba.png)

**Comment by kburtram** [comment]
The localization coverage has been greatly improved with recent lang packgs.  New Query appears localized properly in the lang packs I've checked.
