### ISSUE TITLE
CMS Extension doesn't prompt for reload when installed from gallery

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6346]
Repros in both 1.8.0 and 1.9.0

1. Go to CMS Extension in gallery
2. Click **Install**

Expected : Once install completes it should prompt to reload ADS to complete installation

Actual : No prompt is given. CMS does not work correctly until ADS is reloaded (for example connection dialog authentication type shows AAD as a valid option when adding a new registered server)

**Comment by abist** [comment]
It does prompt to reload. Feel free to reopen if you can repro this.
