### ISSUE TITLE
Improve readability of warning messages when opening notebook from a long URL

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#6348]
Issue Type: <b>Bug</b>

When opening a notebook from a URL, the warning messages do not show the full URL or the file name.

![Sample Link](azuredatastudio://microsoft.notebook/open?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fazuredatastudio%2Fmaster%2Fsamples%2FnotebookSamples%2FSampleTSQLNotebook.ipynb)

In plain text:
azuredatastudio://microsoft.notebook/open?url=https%3A%2F%2Fraw.githubusercontent.com%2Fmicrosoft%2Fazuredatastudio%2Fmaster%2Fsamples%2FnotebookSamples%2FSampleTSQLNotebook.ipynb

![image](https://user-images.githubusercontent.com/8250560/60993261-f0fec000-a302-11e9-8612-4703b6a1b4a0.png)

![image](https://user-images.githubusercontent.com/8250560/60993732-e3960580-a303-11e9-8307-ae13a15ef8e2.png)

Azure Data Studio version: azuredatastudio-insiders 1.9.0-insider (b1cc95d0f9feb82a17c8fb527bd3e835edcabf53, 2019-07-09T17:36:08.346Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (1.87GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.40.0
dacpac|Mic|0.3.0
import|Mic|0.8.0
profiler|Mic|0.9.0
schema-compare|Mic|0.4.0
azdata-sanddance|msr|1.2.0

</details>

**Comment by qifahs** [comment]
When I open a URL, ADS just opens the file. What are the repro steps to popup this dialog?
