### ISSUE TITLE
Ability to change existing DB connection

### ISSUE THREAD

**Issue by devlern** [microsoft/azuredatastudio#6354]
Issue Type: <b>Feature Request</b>

There doesn't seem to be a way to change/update an existing DB connection once setup in the Auze studio, the right click Manage option doesn't provide ability to do that either. Please add this feature if possible in the next release

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.17763

**Comment by cheenamalhotra** [comment]
ADS supports "Edit Connection" on right click now, closing this feature request as a no-op.
