### ISSUE TITLE
Azure data studio Query data is Chinese error code

### ISSUE THREAD

**Issue by longletian** [microsoft/azuredatastudio#6378]
![2019-07-12 23-44-50屏幕截图](https://user-images.githubusercontent.com/28197668/61167126-48697f80-a4ff-11e9-9146-a4bf68dedaaa.png)
Issue Type: <b>Bug</b>

Azure data studio Query data is Chinese error code

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:10:29.206Z)
OS version: Linux x64 4.18.0-25-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5200U CPU @ 2.20GHz (4 x 1935)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|7.70GB (0.24GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hans|Mic|1.9.0
azuredatastudio-postgresql|Mic|0.2.1
profiler|Mic|0.9.0

</details>

**Comment by Charles-Gagnon** [comment]
@longletian Are you able to copy the data from the grid that's displaying as the errors? Doing it both from the grid and from some other tool like SSMS? If you could get a direct repro where you just have a 

```
SELECT N'<Text Here>'
```

that contains characters displayed as errors that'd help as well.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon unfortunately, it doesn't repro by simply running a statement like this: select N'你好，查尔斯'

**Comment by kburtram** [comment]
@longletian if possible, could you please provide screenshot of this same data displayed in SSMS?  Or insert statements with sample repro data?  We unfortunately don't have an internal repro for this issue.

**Comment by kburtram** [comment]
@longletian could you please confirm that you are using `NVARCHAR` and inserting strings with `N` prefix?  I'm able to get a similar repro when inserting Chinese characters into `VARCHAR` columns.

![image](https://user-images.githubusercontent.com/599935/61415228-f92ba200-a8a4-11e9-8c9d-5fa312bd51d8.png)
