### ISSUE TITLE
The newly added feature on profiler filter database name not working

### ISSUE THREAD

**Issue by ndwivedi** [microsoft/azuredatastudio#6379]
- Azure Data Studio Version:

Steps to Reproduce:

1. Start new profiler 
2. Select Standard View (or any other view)
3. Select Filters 
4. Add a Clause 
5. Filed Database Name ='Database queries to be filtered'
6. Nothing is filtered.
7. Once we clear the filter, data is displayed.
8. Interesting thing is the in the view, database id is populated but database name is not.
9. Another interesting thing is that it is working on another server with same version but standard edition of sql server. 
10. I will try other servers and give more feedback.

![image](https://user-images.githubusercontent.com/9135814/61170313-97caa280-a535-11e9-9ce6-ec75181083c7.png)

SQL Server Version:
Microsoft SQL Server 2016 (SP2) (KB4052908) - 13.0.5026.0 (X64) 	Mar 18 2018 09:11:49 	Copyright (c) Microsoft Corporation	Developer Edition (64-bit) on Windows Server 2012 R2 Standard 6.3 <X64> (Build 9600: ) (Hypervisor)

**Comment by kburtram** [comment]
The Database Name filter options appears to be working correctly on the current build.  Please let us know if you're still impacted by this bug with current builds.

![image](https://user-images.githubusercontent.com/599935/129789836-33478e6a-0f85-4773-80cf-97b79091937e.png)
