### ISSUE TITLE
VSIX download on website comes as ZIP

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#6383]
when downloading the latest VSIX, it is downloaded as ZIP (had that on multiple machines)

all you need to do is rename it to VSIX and it works like a charm but might still be confusing to some

**Comment by Charles-Gagnon** [comment]
Are you downloading this via IE? It's a known issue with IE that it doesn't properly handle the file type. If you use a newer browser like Edge it should work fine.

**Comment by bweissman** [comment]
it seems like I was indeed using IE, it works in Edge and Chrome right now. 
As IE is not my default browser, strange how that happened - will close this and check if it happens again with these browsers.
