### ISSUE TITLE
Pipeline to bring in the troubleshooting book from aris to ads

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#6384]
Build a pipeline that copies over the latest troubleshooting notebooks created by Stuart in the Aris repo to our repo.

**Comment by alanrenmsft** [comment]
@MaddyDev is this still needed?

**Comment by Charles-Gagnon** [comment]
No, we'll be removing the troubleshooting books here along with the rest of the BDC stuff.
