### ISSUE TITLE
Settings for font in Messages pane

### ISSUE THREAD

**Issue by BrianStork** [Microsoft/azuredatastudio#639]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:
exec any query which prints output. The output appears in the "MESSAGES" pane in a proportional font. Other areas of the studio allow the user to specify the font they would like to use. The Messages pane should have a user-configurable font choice as well.

**Comment by anthonydresser** [comment]
dupe #181

**Comment by JFitzMan** [comment]
I noticed this was closed as a duplicate, but as of v 1.4.5 this is not an option. The default font is not fixed width. Could this be opened back up?

**Comment by BrianStork** [comment]
This request is for the MESSAGES pane. As of 1.4.5 there is not user-configuration for the font. This issue should not be closed.

**Comment by kburtram** [comment]
Please use this issue to track fixing all query editor font customization with the grid and messages window, for example https://github.com/Microsoft/azuredatastudio/issues/4302.  Thanks!

**Comment by anthonydresser** [comment]
I'm going to assume we can use the same font config as we do for results grid for both messages and results grid, unless we get a specific requests to distinguish between the two.
