### ISSUE TITLE
Executes query despite "closed" connection

### ISSUE THREAD

**Issue by JohannesGerk** [microsoft/azuredatastudio#6391]
Issue Type: <b>Bug</b>

When trying to execute a query after the connection closed when sitting idle for a while you see the following message:
"Query failed: Invalid operation. The connection is closed."

However the query has been executed regardless.
Query in question is INSERT.

Further INSERT or SELECT attempts lead to:
"The connection does not support MultipleActiveResultSets."
and require you to open a new query.

Azure Data Studio version: Azure Data Studio 1.5.2 (f74080c96310354bc92211f1826c0fdce78ca2f6, 2019-03-22T06:09:10.602Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz (4 x 2500)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>video_decode: enabled<br>video_encode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.39GB free)|
|Process Argv|-psn_0_32776|
|Screen Reader|no|
|VM|0%|

</details>Extensions: none

**Comment by aaomidi** [comment]
Related to: #6590

**Comment by kburtram** [comment]
Closing older issues without recent repro reports.  We've fixed several issues in the connectivity reliability area since this issue was filed.  Please let us know if you're still impacted by this issue.  Thanks!
