### ISSUE TITLE
Notebook crash

### ISSUE THREAD

**Issue by RicardoNoerr** [microsoft/azuredatastudio#6392]
Issue Type: <b>Bug</b>

I'm working with an SQL Notebook but it crashes frequently with "The window has crashed" popup, maybe after 10 or few actions on it.

there is no pattern to reproduce, but apparently the crash happens when editing a code section

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.92GB (1.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.41.0
import|Mic|0.9.0
profiler|Mic|0.9.0

</details>

**Comment by chlafreniere** [comment]
Should have been fixed with the referenced PR. Please feel free to re-open if you see this happen again.
