### ISSUE TITLE
Data Virtualization from HDFS often fails due to type errors

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#6395]
Repro (from Travis): 
- Right click on a CSV file in HDFS and created an external table.  
- Select from external table.  Works for first 100 rows, but fails on TOP 1000 because of a type mismatch. 

The main feedback is we need a larger row sample (perhaps 1,000-10,000) to correctly detect this. I would add:
- We should show "row sample size" as an option, either in settings.json or ideally also in the wizard
- We should allow overriding of the detected column if not supported already.

**Comment by corivera** [comment]
We start the prose parsing in the background after opening the wizard as a perf improvement, so there's not a good place to put a sample size dropdown. I'll try adding a settings field for it, with a default of 10,000.

We also already have a page for manually changing the detected column types.
