### ISSUE TITLE
Clicked Restore on database

### ISSUE THREAD

**Issue by mblataric** [microsoft/azuredatastudio#6409]
Issue Type: <b>Bug</b>

Right click database and select Restore

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (f720ec642f6ffd51d8772f663a611292f91a563d, 2019-07-15T07:47:15.691Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz (8 x 3503)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|10.17GB (2.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Are you reporting a bug here? Restore seems to be working for me. Please include repro steps and any relevant error messages if you're encountering an error so we can investigate. Thank!

**Comment by mblataric** [comment]
Hi, 

No idea, clicked Restore, crashed, report windows showed up, I filled info and submitted. 
I somehow thought bug report window will send all required info about what happened. 

Regards,
Mario

**Comment by mblataric** [comment]
Just tried again and there is no error any more ...
