### ISSUE TITLE
Persist Connection when dropping/opening files

### ISSUE THREAD

**Issue by BrianStork** [microsoft/azuredatastudio#641]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:
Connect to a database and open a New Query window.
Drag a .sql file into the studio. The file opens in a tab that needs to establish a connection before executing. It would be a great feature if we could drag a file into the workspace or onto a server and have it open in a tab with the connection already established (like in SSMS).
The same is true with opening files from the Studio's Explorer pane.

**Comment by justingrant** [comment]
Would be great to have this. Annoying to have to keep re-opening the same connection.

**Comment by kburtram** [comment]
@erickangMSFT you had some concerns with this feature when we discussed during triage.  Could you please add some detail here regarding your thinking?  Perhaps this could be a user setting?

**Comment by DaveProkop** [comment]
I vote for this feature, too. If you are working with multiple files on same database, it's really annoying, when you have to choose connection with every file. It could be user setting.

**Comment by Neone-pl** [comment]
IT would be great to have both options:

- a setting for folder/workspace in which you can set default connection for files in that folder or workspace.
- if no setting is set, then use last (or some default) connection.

**Comment by Galaeci** [comment]
This is crucial when working with multiple files. When a file is opened it should use the connection associated with the active query window. This feature is a great time saver when working with multiple  scripts associated with a database.

**Comment by heneds** [comment]
This is a critical feature, for instance when running update patches. I find it especially important when using the explorer view. The easiest solution could be simply to right click a server and select "Set as default connection". Neone-pl's workspace idea is also interesting.

sqlopsstudio is great but whenever you have to use SMS instead, because there is no way around the problem, it is just not good enough.

**Comment by kburtram** [comment]
When opening SQL files using Open File Dialog or drag-and-drop, ADS will try to connect the editor to the "current global connection."  The global connection is based on the current focused region in the application (e.g. active editor or node selected in Object Explorer, etc).  

If you're seeing cases where the opened editor is not being correctly connected could you please open an issue with the specific repro steps include what is the currently focused elements in the UI so we can resolve the bug in the global connection tracking code.  Thanks!
