### ISSUE TITLE
Execute SQL command cursor is in without having to highlight

### ISSUE THREAD

**Issue by mrlife** [microsoft/azuredatastudio#6410]
Issue Type: <b>Feature Request</b>

This would be a huge time and energy saver when working with multiple queries in one tab. Thank you for considering!

Azure Data Studio version: Azure Data Studio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:16:23.244Z)
OS version: Darwin x64 18.6.0

**Comment by kburtram** [comment]
The `Run Current Query` command executes the SQL statement where the cursor is currently located, and can be mapped to a keyboard shortcut if desired.  Please let us know if this doesn't address this suggestion.  Thanks!

**Comment by mrlife** [comment]
@kburtram That is awesome! It looks like it has a default keyboard shortcut defined for macOS, command-F5, but it conflicts with a system-level shortcut that brings up VoiceOver. I can change it (thanks for the tip!) but it may be useful for others if the default is changed.

**Comment by ChuckJonas** [comment]
Note: if this isn't working for you, check that the query above is properly terminated (`;`)
