### ISSUE TITLE
connection error

### ISSUE THREAD

**Issue by juliomutley** [microsoft/azuredatastudio#6411]
Issue Type: <b>Bug</b>

just tried to connect at localhost

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|23.27GB (3.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0
admin-pack|Mic|0.0.2
agent|Mic|0.41.0
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0

</details>

**Comment by Charles-Gagnon** [comment]
@juliomutley What error are you seeing?

**Comment by juliomutley** [comment]
I process for several seconds then says that It wasn't able to connect, I tried 2, 3 times more than it worked (and yes I checked the service and was on)

**Comment by Charles-Gagnon** [comment]
@juliomutley Sorry for not following up - this fell off my radar. Are you still seeing this issue?

**Comment by juliomutley** [comment]
to be honest it didn't happened anymorenin  this last build

Em seg, 16 de set de 2019 às 22:27, Charles Gagnon <notifications@github.com>
escreveu:

**Comment by Charles-Gagnon** [comment]
Alright, thanks for the follow-up! If this happens again let us know. If you do including a screenshot of the actual error will help us try to figure out what kind of issue it is.
