### ISSUE TITLE
Azure: Manage Linked Account command missing

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#6413]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Click on Sign in or any account management command.

Expected - to work
Actual - Fails

Upon investigation, I found that we are missing the `accountListStatusbarItem.ts` from `accountManagement.contribution.ts` which was added here - https://github.com/microsoft/azuredatastudio/pull/4882/files#diff-a2f6ee454ef3661cd188be6cbddeee02

but missing here - https://github.com/microsoft/azuredatastudio/blob/master/src/sql/platform/accounts/browser/accountManagement.contribution.ts

as a part of the relayering i think

**Comment by anthonydresser** [comment]
Can you specify what commands are failing? I fixed the + button in the azure viewlet title but not sure if there are other entry points I need to fix.

**Comment by abist** [comment]
@anthonydresser I think it was just that referenced in multiple places. Thanks for the fix.
