### ISSUE TITLE
Clicking on Started execution on line x does not scroll line into view

### ISSUE THREAD

**Issue by mottykohn** [microsoft/azuredatastudio#6417]
Issue Type: <b>Bug</b>

Run a query that span more than one screen that has multiple GOes.
In the Messages pane you will see multiple 

> 2:29:41 <u>Started executing query at Line X</u>

Click on one that is not currently in the view
Notice that it is highlighted but not scrolled into view. To see it you must manually scroll

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.17763

**Comment by anthonydresser** [comment]
fixed by #6435
