### ISSUE TITLE
Import Flat File Wizard -- no detail when import fails

### ISSUE THREAD

**Issue by bobhy** [microsoft/azuredatastudio#6418]
Issue Type: <b>Bug</b>

1. Run wizard, specifying reasonable inputs.
2. At step 3, click Import Data

Expect:
If there is an error, expect to see some detail to help understand the problem.

Observe:
x Error inserting data into table.

If you think this error report is lacking in detail to help you understand the problem I'm reporting, just imagine my frustration at being unable to take the first step in getting this extension to work.  I cannot decide whether I've specified an incorrect data type, or my input data is malformed, or I don't have access to the database or whether there's just a bug in the extension.  Oh well, back to BCP.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (8.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MikeDrewitt** [comment]
Similarly, it'd be really nice to be able to know why a file couldn't be opened if you can't even get so far as to run the import itself. Currently if you have a malformed CSV the only error message you get is 

```
The operation was unsuccessful. Please try a different input file.
```

**Comment by pnhughes** [comment]
It's hard to believe that this item hasn't been actioned yet given how serious a gap it is.  Wizard is unusable on larger imports due to the amount of time required to track down issues, retry and repeat.

**Comment by jasminsehic** [comment]
Yep, very frustrating not being able to see any clues to error.

**Comment by vtruong68** [comment]
Same issue here. I have to open up SSMS and go through the same process to view the errors.

**Comment by pnhughes** [comment]
In frustration I forced myself to install, learn and use BCP.  It's been years since my last attempt and I find it much more usable now.   I wouldn't call it verbose with respect to error reporting either, but it's better than ADS at present.

**Comment by aaomidi** [comment]
I've updated the import extension where you should be getting more error messages. These changes will be included in future insiders builds (24-48 from this comment). Hopefully that will give you more context on whats breaking.

Please file bugs for non obvious issues.
