### ISSUE TITLE
Remove notebookQuality context key once Jupyter Books no longer needs Insiders flighting

### ISSUE THREAD

**Issue by lucyzhang929** [microsoft/azuredatastudio#6427]
We've added a notebookQuality context key so that we only show books in Insiders. We need to remove once it's no longer needed.

**Comment by chlafreniere** [comment]
@MaddyDev this is related to your current PR. Can we remove the notebookQuality context key completely, or do you think that there's value in keeping it around?

**Comment by MaddyDev** [comment]
I don't think there's any use keeping it once it makes stable. I'll remove it in my PR. Thanks.

**Comment by MaddyDev** [comment]
this is removed for Nov release when we made Books public.
