### ISSUE TITLE
Side bar icon missing ( where you see system database, tables, etc)

### ISSUE THREAD

**Issue by smithcs456** [microsoft/azuredatastudio#6434]
<img width="773" alt="Screen Shot 2019-07-19 at 10 21 15 AM" src="https://user-images.githubusercontent.com/53089357/61542163-ff3d9200-aa0e-11e9-8725-250d33d2eb0b.png">
Issue Type: <b>Performance Issue</b>

hi,

opening Azure Data Studio is not showing the side icon bar ( i believe it called "Object Explorer). By sidebar I mean is that icon where you see system database, tables, keys, constraints, etc.

**Comment by kburtram** [comment]
@smithcs456 can you please try right-clicking where it says "Connections: Azure".  There should be a context menu command to reshow the Severs view.  It looks like it may be hidden.

![image](https://user-images.githubusercontent.com/599935/61560734-f609f080-aa21-11e9-9dc6-cf2419d2351a.png)

**Comment by anthonydresser** [comment]
You can also click the "..." on the title bar to get the same menu
