### ISSUE TITLE
External table: Checkboxes always have "-" on object mapping page

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#6454]
Checkboxes keep reverting to "-" state even after being checked and unchecked. The actual backend state of the checkboxes is fine though, since selected tables show up in the summary page as expected.

![Checkboxes](https://user-images.githubusercontent.com/12820011/61667578-36ba7180-ac8f-11e9-9739-b88a2495abc2.PNG)

**Comment by kevcunnane** [comment]
The [VSCode merge commit](https://github.com/microsoft/azuredatastudio/commit/0b7e7ddbf96bf76e2acc774ae560a06de064b4f5) broke this. That means the fix should be on the Azure Data Studio side. Seems like treeComponentRenderer wasn't changed so maybe tree itself or checkbox, which definitely had changes?

**Comment by geleems** [comment]
Fix has been merged.
