### ISSUE TITLE
Cannot install extension from VSIX Package.

### ISSUE THREAD

**Issue by rchlkm** [microsoft/azuredatastudio#6456]
- Azure Data Studio Version: 1.9.0

Issue Type: **Bug**

When I try to install an extension by uploading a VSIX Package, I get this error: "Your extension policy does not allow downloading extensions. Please change your extension policy and try again."  

![vsix_error](https://user-images.githubusercontent.com/14362577/61668287-1db2c000-ac91-11e9-8a30-abe04aaaf2ec.png)

**Comment by kburtram** [comment]
Here's what I did in my dev branch to unblock myself https://github.com/microsoft/azuredatastudio/commit/7576b62cee53ab09118d48dae7aee2778e3b4fc8.  For some reason the extension policy is now undefined.

**Comment by alanrenmsft** [comment]
@kburtram , thanks for the information.

**Comment by abist** [comment]
@alanrenmsft Can we close this?
