### ISSUE TITLE
Azure Data Studio window crash upon editing notebook SQL code syntax

### ISSUE THREAD

**Issue by jsarnowski96** [microsoft/azuredatastudio#6464]
I noticed that upon editing database's notebook, whole ADS window crashes. If I remove every sign one by one at time intervals in order for ADS to process it, it might still work, but it does it extremely slowly and between removing certain digits the app freezes. But if I repeatedly hit backspace, it completely crashes. My guess is that's caused by some heavy SQL transactions inside, however I don't execute them, just want to edit some of them, so no idea what's causing this problem.  Issue persists between app restarts.

![Przechwytywanie](https://user-images.githubusercontent.com/20375860/61683968-f7843300-ad17-11e9-97c3-487e4e827c1a.PNG)

**Comment by jsarnowski96** [comment]
Worth noting is the fact that it started to happen after last update. Before that it worked just fine.

**Comment by jsarnowski96** [comment]
The problem fixed itself. Upon closing the notebook and re-opening it, the app suddenly started to work properly.

**Comment by mmcaulay** [comment]
I've had the same issue, I think there's a bug here but can't pinpoint it

**Comment by mbyanfei** [comment]
Same issue here, it crashes even i just tried to edit text
