### ISSUE TITLE
Feature-request: Better insert-scripts 

### ISSUE THREAD

**Issue by ststeiger** [microsoft/azuredatastudio#6484]
I see scripting objects gets added in the insider builds. 
I figured, data scripting might be next. 

Thus a feature request: 

Until now, INSERT-scripts in SSMS look like: 
```
INSERT INTO T_Whatever (id, txt) VALUES(1, N'hello world');
INSERT INTO T_Whatever (id, txt) VALUES(2, N'hello new data');
INSERT INTO T_Whatever (id, txt) VALUES(3, N'i am an update for existing data');
```

This is problematic. 
Wouldn't it make more sense, if it generated an update script like this: 

```
DECLARE @whatever table (id int not null, txt nvarchar(256) NULL ); 

INSERT INTO @whatever (id, txt) VALUES(1, N'hello world');
INSERT INTO @whatever (id, txt) VALUES(2, N'hello new data');
INSERT INTO @whatever (id, txt) VALUES(3, N'i am an update for existing data');

-- INSERT INTO T_Whatever(id, txt) 
SELECT id, txt FROM @whatever AS t 
WHERE NOT EXISTS(SELECT * FROM T_Whatever WHERE T_Whatever.id = t.id)
; 

UPDATE T_Whatever 
	SET T_Whatever.txt = t.txt 
FROM @whatever AS t 
WHERE t.id = T_Whatever.id 
;
```
Anybody who didn't like the update part could delete it in a second. 

Or with the new merge-syntax:

```
;WITH CTE AS 
( 
	SELECT 
		 1 AS id
		,N'hello world' AS txt 
		 
		 
	UNION ALL 


	SELECT 
		 2 AS id
		,N'hello new data' AS txt 
		 
		 
	UNION ALL 


	SELECT 
		 3 AS id 
		,N'i am an update for existing data' AS txt 
) 
-- SELECT * FROM CTE 




MERGE INTO T_Whatever AS A 
USING CTE ON CTE.id = A.id 
WHEN MATCHED 
	THEN UPDATE 
		SET  A.txt = CTE.txt 
			 
WHEN NOT MATCHED THEN 
INSERT 
( 
	 id 
	,txt
) 
VALUES 
( 
	 CTE.id 
	,CTE.txt 
); 


-- DELETE FROM T_Whatever WHERE id = 1; 
-- SELECT * FROM T_Whatever; 


SET NOCOUNT OFF; 
```

Or the merge syntax with the table-variable instead of the CTE from the 1st example.

If the table doesn't have a primary key, it could just insert from the table-variable. 
(or use EXCEPT and INTERSECT to match on all fields - though INTERSECT/EXCEPT would be problematic with tables with xml and varbinary fields)

<h1>Also</h1>
If it creates an insert for datetime/datetime2 fields, it should use <b>ISO</b> syntax (you know, <b>international</b> standards organization - aka "yyyy-MM-ddTHH:mm:ss.fff"). Note the <b>T</b> delimiting time and date. Until now, the insert scripts omit the T, and put a whitespace instead, which apparently works for people who have an en-US-cultured windows account at work, but not for me and others, because we have a culture of de-CH or de-DE, or something else (which we by-the-way can't even choose, otherwise I'd use en-US because of boatloads of things like that), and there, that insert-script with a whitespace doesn't work. (also a problem when a script is run at an on-promise location, where you can't control under what account-language a script will be executed - which is especially problematic in Switzerland, as this can be 4 different languages). 

It's not funny if you have to search for the problem in a boatload of SQL-scripts, and then still need to change each and every value, because there could potentially be thousands of them. And just like that, precious (expensive) hour<b>s</b> pass by.

**Comment by Charles-Gagnon** [comment]
You can actually do this today if you install the **Database Administration Tool Extensions for Windows** extension (windows-only at the moment though unfortunately). You can find that in the Marketplace view.

Once you've installed that extension then right click on the Database containing the table you'd like to script and select **Generate Scripts**

![image](https://user-images.githubusercontent.com/28519865/61803012-44363f80-ade6-11e9-94e9-948b12bc0873.png)

Follow the dialog to choose the objects to script and on the **Set Scripting Options** page click the **Advanced** button. 

From there go down to **Types of data to script** and choose **Schema and Data**

![image](https://user-images.githubusercontent.com/28519865/61803129-7ba4ec00-ade6-11e9-85a6-b92c514862f3.png)

Finish going through the wizard and your script should be generated with the included INSERT statements as appropriate!

If you do this then the datetime fields should be generated with the ISO syntax - if yours aren't then file a separate issue and we can look into it.

**Comment by ststeiger** [comment]
@Charles-Gagnon: I've downloaded the latest insider build from AzureDataStudio today (25.07.2019), installed Database Administration Tool Extensions for Windows, connected to db, right-clicked "generate scripts", chose one table, "Save to new query window" + advanced "schema and data", next, next => and all it does is it opens https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017

**Comment by Charles-Gagnon** [comment]
Thanks for your feedback! The issue with opening a new window not working for insiders is a known issue #6276 so follow that for updates. You can also install the stable build of ADS and use that - the feature should work as expected there.

For your other requests please open up separate issues for them - it's better for tracking if we have a separate issue opened for each problem rather than bunching them all together into a single issue like this.
