### ISSUE TITLE
Troubleshooting book does not successfully reload if open folder is a workspace

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#6487]
Issue Type: <b>Bug</b>

Steps to reproduce:

1) Have Azure Data Studio open to a workspace
2) Navigate to the big data cluster dashboard and open the troubleshooting book
3) Reload

Expected: Book is Shown

Actual: Folder is added to workspace, book is not shown, and sqlopsextensions.code-workspace shows as a modified file

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (059e80003db7edada8901a9e713b01756562480b, 2019-07-24T05:03:33.331Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
schema-compare|Mic|0.4.0
azdata-sanddance|msr|1.2.0

</details>

**Comment by kevcunnane** [comment]
@lucyzhang929  can you take a look at this? It seems like we're not detecting when in a workspace with multiple folders. This one can block Troubleshooting notebook scenario, so if you can prioritize investigating that'd be great
