### ISSUE TITLE
Database Restore

### ISSUE THREAD

**Issue by PGrantcharov** [microsoft/azuredatastudio#6493]
Issue Type: <b>Bug</b>

Hi, 
I'm trying to restore a SQL Server database from a .bak file. When I'm on the server dashboard from localhost, I go to click the Restore button as that is what all tutorials are showing. I then get the error: 
```Restore command is not supported in Server Context. Please select a Database and try again.``` 
I can find virtually no info on this warning so I am at a standstill.

I have tried to restore the database via a few other methods but have had no luck. This seems to be the simplest way from all the tutorials I have found, but unfortunately I am having no luck. 

Would love any kind of help!

Peter

Azure Data Studio version: Azure Data Studio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:16:23.244Z)
OS version: Darwin x64 18.6.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (1.65GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by udeeshagautam** [comment]
@PGrantcharov thanks for reporting the issue. I understand that the presence of restore button on server tab is contradicting with the warning message. We will work to fix that. 

As a workaround - Please navigate to a database dashboard by double clicking a db name in server dashboard _OR_ right clicking a database in Connections view and select Manage. Once the database dashboard opens - select backup/restore functionality from this dashboard and proceed with restore. You can choose any database for target (it does not matter which database you started the restore from.
![restore](https://user-images.githubusercontent.com/46980425/61903788-3a8e0400-aeda-11e9-8c46-e17c90c6d2fb.gif)

Please let us know if this unblocks you.

**Comment by bkelley-nasb** [comment]
The issue here is when a developer is attempting to create a database from a .bak file via the Restore method, which is commonly done in SSMS. The use case here is when folks are moving a db from one development machine to another, or when initially creating a database for a project from a provided .bak file. In my case today, I was installing some tutorial files from a GitHub repo that contained a .bak file for database creation. This is a pretty common use case.

**Comment by udeeshagautam** [comment]
Restore from Server Dashboard is re-enabled in latest insiders build so closing this bug. Please reactivate/let us know, if you still see this issue.
