### ISSUE TITLE
Connection dialog box in bdc tree view does not honor cancel

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#6498]
Issue Type: <b>Bug</b>

1. Setup bdc with different passwords for controller, sql, knox
2. Connect to controller endpoint
3. Expand SQL Master
4. Connection will fail since password is different, now try to hit cancel in the connection dialog box. It will prompt again. Only way to get out of this mode is to put the correct password.

Expected behavior: Any dialog with cancel should allow the operation to be aborted.

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (6064904151d2ac3b3b6c84f25b890baa20ef43fe, 2019-07-24T22:21:08.135Z)
OS version: Windows_NT x64 10.0.18941

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
sql-vnext|Mic|0.14.1

</details>

**Comment by kevcunnane** [comment]
@Charles-Gagnon any plans to pick this up? If not let me know and I can. It's very annoying to run into this as you have to reopen ADS to get out of the loop.

**Comment by kevcunnane** [comment]
No worries, I will pick it up.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
