### ISSUE TITLE
Attached notebook crashes ADS

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#6499]
[0.1. spark-sql.zip](https://github.com/microsoft/azuredatastudio/files/3429798/0.1.spark-sql.zip)

Issue Type: <b>Bug</b>

1. Load the sample database / data per below in a BDC instance:

https://docs.microsoft.com/en-us/sql/big-data-cluster/tutorial-load-sample-data?view=sqlallproducts-allversions

2. Run attached notebook, it will crash ADS after executing few cells

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (6064904151d2ac3b3b6c84f25b890baa20ef43fe, 2019-07-24T22:21:08.135Z)
OS version: Windows_NT x64 10.0.18941

<details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0
sql-vnext|Mic|0.14.1

</details>

**Comment by kevcunnane** [comment]
@chlafreniere can you investigate this? Would there be logs etc. we need to get more information or can we easily repro?

**Comment by chlafreniere** [comment]
> @chlafreniere can you investigate this? Would there be logs etc. we need to get more information or can we easily repro?

Sure, will take a look. We need ADS logging if we can't repro. @kevcunnane what's the best way for users to enable this? Is there a simple mechanism?

**Comment by chlafreniere** [comment]
This should be fixed along with #6543, given the PRs merged in earlier this week.
