### ISSUE TITLE
CMS doesn't list/add servers

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6500]
I can add a CMS successfully but when I expand it all it lists is **No resources found** and trying to add a registered server under it doesn't seem to do anything. This is occurring in both stable and insiders builds.

**Comment by abist** [comment]
@Charles-Gagnon Do you know what kind of auth or server it's using? I can't seem to repro this

**Comment by Charles-Gagnon** [comment]
This is for registering a server under a CMS so it's just using windows auth.

(the existing registration is one that I did from SSMS to verify that it can read them correctly)

![screen](https://user-images.githubusercontent.com/28519865/62079529-c4540f00-b203-11e9-9cf8-d1a539bbddd9.gif)

**Comment by Charles-Gagnon** [comment]
And note that this is happening well after the MSSQL extension has loaded so your possible fix is unlikely to resolve what I'm seeing here.

No errors in the console either.

**Comment by abist** [comment]
@Charles-Gagnon could you confirm the extension version?

**Comment by Charles-Gagnon** [comment]
This is on master, so the version there (0.3.0). Are you not able to repro this yourself still? I just had Chris try and he was able to get the same behavior on his mac.

**Comment by abist** [comment]
Let me try with a clean install.

**Comment by abist** [comment]
@Charles-Gagnon Can I close this?

**Comment by Charles-Gagnon** [comment]
Yeah I'll close it now and reopen if I have any other information later on.
