### ISSUE TITLE
can we have select or deselected all/highlighted on the grid for the column "include".  Currently there is no option, we must do for each row.

### ISSUE THREAD

**Issue by giacatluong** [microsoft/azuredatastudio#6505]
- Azure Data Studio Version:

Steps to Reproduce:

**Comment by giacatluong** [comment]
Example, thousand rows .. we just want to exclude/include 200 rows in there..
Must do one by one .. very time consuming
Thanks

**Comment by anthonydresser** [comment]
Are you meaning the ability to select all rows? Or to select all cells from a column?

The former is covered by ctrl+A
