### ISSUE TITLE
Unable to communicate with the runtime for 'Python' script. 

### ISSUE THREAD

**Issue by robertnaum** [microsoft/azuredatastudio#6507]
- Azure Data Studio Version:  1.9.0 user setup

Steps to Reproduce:
1.
EXECUTE sp_execute_external_script @language = N'Python', @script = N'
import sys
print(sys.version)'

Msg 39012, Level 16, State 1, Line 0
Unable to communicate with the runtime for 'Python' script. Please check the requirements of 'Python' runtime.
STDERR message(s) from external script: Traceback (most recent call last): File "", line 1, in File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\__init__.py", line 6, in from .RxSerializable import RxMissingValues File "C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\PYTHON_SERVICES\lib\site-packages\revoscalepy\RxSerializable.py", line 26, in from . rxLibs.pylink import px_call ImportError: DLL load failed: The specified module could not be found.

I'm running PYTHON 3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)].  How do I know?  Because when I went to switch kernel from SQL to Python, it offered to install/upgrade Python.  I chose to upgrade the version of Python that SQL2017 ships with in PYTHON_SERVICES.  Now when I start Python, I get a warning "This Python interpreter is in a conda environment, but the environment has not been activated."  The solution is to type "activate base", but that needs to happen BEFORE the sp_execute_external_script is called.

So now my ADS notebook can run "native" PYTHON code, but the SQL kernel can no longer run PYTHON code.

**Comment by chlafreniere** [comment]
Hi @robertnaum I just tried this on my machine and was able to get a successful result back:

![image](https://user-images.githubusercontent.com/40371649/106542930-9cf59680-64b9-11eb-993d-ce1098bf61da.png)

Do you still see the behavior above?

**Comment by chlafreniere** [comment]
Closing since we're not able to repro any longer and need more info on whether our repro is different. If you see this in the future, feel free to reopen!
