### ISSUE TITLE
Color selection is gone for Server Group

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#6510]
- Azure Data Studio Version:
```
Version: 1.10.0-insider (system setup)
Commit: 9f342ec9d5ed3827ecd86d7e165044e1b73e77ea
Date: 2019-07-26T07:49:17.517Z
VS Code 1.37.0
Electron: 4.2.5
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Steps to Reproduce:

1. Edit a current server group/Create a new server group
2. Unable to see color differences

This applies to dark and light theme, same result. Note these are **built-in themes** for ADS and not VS Code based extensions manually installed.

Light theme:
![image](https://user-images.githubusercontent.com/11204251/61981536-954d5b80-afbf-11e9-88fc-161cfce126fa.png)

Dark theme:
![image](https://user-images.githubusercontent.com/11204251/61981547-9bdbd300-afbf-11e9-8e69-c23cbf227760.png)

**Comment by aaomidi** [comment]
I've tracked down the issue to be originating from this line:

https://github.com/microsoft/azuredatastudio/blob/06e9a6e684137b77e690fb69bc0ba8f516feb8a6/src/vs/base/browser/ui/checkbox/checkbox.ts#L163

Looks like VSCode changed how they're applying that specific style to checkboxes.
