### ISSUE TITLE
Insiders app icon is wrong

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6518]
Latest insiders seems to be falling back to the Electron icon. Insiders only, doesn't happen on dev build running locally. 

![image](https://user-images.githubusercontent.com/28519865/62056416-6c50e480-b1d2-11e9-8c32-22b32c740954.png)

**Comment by chlafreniere** [comment]
This is related to us changing to new build machines. Am following up with @alanrenmsft offline.

**Comment by nikonso** [comment]
Seems to be solved! At least mine is back to normal!

**Comment by kburtram** [comment]
Fixed in today's build.
