### ISSUE TITLE
Failed to Create Session - Profiler

### ISSUE THREAD

**Issue by tjbetts** [microsoft/azuredatastudio#6525]
- Azure Data Studio Version:1.9.0

Steps to Reproduce: Connect to Azure SQL Server then open Profiler then attempt to create new session. 
Error is the same on both Mac and Windows OS. I have tried against several different Azure Sql servers.

**Comment by chlafreniere** [comment]
Hi @tjbetts, sorry for the trouble. This is being tracked by #6353. Appreciate the feedback!
