### ISSUE TITLE
Extension is downloading as zip file

### ISSUE THREAD

**Issue by kevchant** [microsoft/azuredatastudio#6531]
Issue Type: <b>Bug</b>

If you download the Windows version of the extension for version 0.14.1 it appears to be downloading as a zip file. I renamed it to vsix as a workaround but thought I better report it...

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.15063

**Comment by Charles-Gagnon** [comment]
Are you using Internet Explorer? This is a known issue where it's incorrectly assigning the file type to VSIX packages. If you use another browser such as Edge/Chrome/Firefox it should download correctly.
