### ISSUE TITLE
Deploy Dialog Table Can Shift By a Pixel or Two

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#6542]
Super super minor. If I go to the Deploy page (starting at the BDC option), switch to the container option, and change the version dropdown, the table shifts by a pixel or two. Here’s how it looks:

![offbypixel](https://user-images.githubusercontent.com/40371649/62173147-d0b29780-b2e9-11e9-8f7b-c1ba0fb6fafc.gif)

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
