### ISSUE TITLE
Running SQL Script from extension

### ISSUE THREAD

**Issue by jamesrod817** [microsoft/azuredatastudio#6557]
- Azure Data Studio Version:

Steps to Reproduce:

1. I tried to use the example from sp_whoIsActive which runs a SQL script when you press on the task container except my script has multiple batches. Only the first batch is ran (all the code before the first Go command). I need to be able to run the whole script with multiple batches.

**Comment by alanrenmsft** [comment]
@jamesrod817 with latest ads master, you can use azdata.queryeditor.runQuery(filePath, undefined, false) to make it run the whole query
