### ISSUE TITLE
Execute current sql statement

### ISSUE THREAD

**Issue by csabhickory** [microsoft/azuredatastudio#6571]
Add a command or key combination that executes the current sql statement the cursor is on or in, not the entire script.   For example, you have 3 sql select statements separated by semi-colons.   ctl-Enter would run only the statement where your cursor sits, not the entire script.

**Comment by anthonydresser** [comment]
You can highlight a range to execute and it will execute just that range, but we don't currently have the ability to detect the current statement from cursor location.

**Comment by kburtram** [comment]
Have you tried the `Run Current Query` (CTRL-F5)?  This should only run the current statement.

**Comment by csabhickory** [comment]
Excellent; this seems to work.  I did not know this feature was available.   I am able to select one of the queries in my script and run just the one query with this key combination.   Thank you.

**Comment by kburtram** [comment]
@csabhickory thanks for confirming.  I'll close this issue based on your comment.
