### ISSUE TITLE
Loading Kernels broken on latest insiders

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6573]
Issue Type: <b>Bug</b>

Loading Kernels broken in latest insiders.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22312581/62397445-c6331080-b52a-11e9-956a-57ad012bcb3d.png">

Azure Data Studio version: Azure Data Studio 1.10.0-insider (c4ab7f64e6ccf4d3c8571eef691cc7a2d42f243a, 2019-08-02T07:24:02.465Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 2, 2|
|Memory (System)|16.00GB (0.58GB free)|
|Process Argv|-psn_0_9037982|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
import|Mic|0.9.0
sql-vnext|Mic|0.14.1
azdata-sanddance|msr|1.3.0

</details>

**Comment by chlafreniere** [comment]
@ronychatterjee I cannot repro with the latest bits:

![image](https://user-images.githubusercontent.com/40371649/62398807-9d147f00-b52e-11e9-953d-3be2926de3e8.png)

Does this consistently happen to you, or was this a one-off error?
