### ISSUE TITLE
Query event listener extensibility APIs are broken

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6589]
- Azure Data Studio Version: `master`

It looks like https://github.com/microsoft/azuredatastudio/commit/674351dc75b3b6e8198663dc85c3da16db824909 removed several extensibility hooks that used for query event listeners.

**Comment by kburtram** [comment]
Do you have an idea how to restore these events?  Or do we need to reimplement them differently?

**Comment by kevcunnane** [comment]
@RebeccaRunxinWang this means the Visualizer feature is likely broken on Insiders. Could you verify this? Anthony, any ETA on when this would be fixed? I believe we'd been hoping to announce Sandance integration from query editor as an August feature?

**Comment by RebeccaRunxinWang** [comment]
@kevcunnane I tested the Visualizer feature on the current master branch and it worked fine. I believe it's not broken at this time.

**Comment by anthonydresser** [comment]
This is no longer an issue.
