### ISSUE TITLE
Connection/Application state on disconnect/deleted connections don't get cleaned up

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#6590]
> @aaomidi cool, makes sense.  We probably still have an issue of keeping connection details retained in the application state after connections are disconnected\deleted.  Though if there are no user facing bugs that seems like a lower-priority.  Thanks!

_Originally posted by @kburtram in https://github.com/microsoft/azuredatastudio/pull/6560#issuecomment-518315949_

**Comment by kburtram** [comment]
Closing older engineering-focused bugs to prioritize customer scenario-facing bugs.  We can analyze connection internal state in perf testing for this area.
