### ISSUE TITLE
Object Explorer context menu items are in wrong order

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6597]
- Azure Data Studio Version: `master`

>Note: This is a recent regression.  We should keep the item order from the July release unless we go through a design review to update.

Steps to Reproduce:

1. Show context menu on an object explorer node

![image](https://user-images.githubusercontent.com/599935/62494278-f0cdd500-b787-11e9-807d-aa31b0625dc6.png)

**Comment by kburtram** [comment]
For reference, here's what this menu looked like in July release.

![image](https://user-images.githubusercontent.com/599935/62494636-d3e5d180-b788-11e9-9bf4-6a1c2ff12357.png)

**Comment by anthonydresser** [comment]
This is caused by #6550 The fix would be either making all the actions contributions and just mess with the ordering numbers, or when constructing the menu, make the contributed command come first.
