### ISSUE TITLE
Extension Manager viewlet icon is out of order

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6600]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Delete any cached application state from under Roaming directory
2. Open ADS

Expected: Order of viewlets hasn't changed from July

Actual: Extension Manager icon has moved up the list.   I think search has moved up above files.  We should revert the order back to the default July order.

![image](https://user-images.githubusercontent.com/599935/62497408-c6cce080-b790-11e9-918e-525d1f4e8cea.png)

**Comment by alanrenmsft** [comment]
testing on my Windows machine now

**Comment by alanrenmsft** [comment]
not able to repro on both mac and Windows, I ran into this issue before, and I realized it was my mistake, I dragged the icons around. @kburtram , does this repro for you on multiple machines?

**Comment by kburtram** [comment]
@alanrenmsft I've only tried this on one machine.  But I cleared my Roaming folder and it repo'd for me.  So don't think it's related to dragging the UI around.

**Comment by kburtram** [comment]
@alanrenmsft I doubled checked on a different machine and I can repro there as well with today's insider build.  You'll need to clear your cached application state to verify since that state contains the viewlet order from previous sessions.

![image](https://user-images.githubusercontent.com/599935/62502268-49f73200-b7a3-11e9-926d-58bd8e55f38f.png)

**Comment by alanrenmsft** [comment]
@kburtram , Thanks for the information, I am able to repro after deleting the cache. I have a fix for it, and will send out a PR shortly

**Comment by kburtram** [comment]
@alanrenmsft thanks!  this is fixed for me now.
