### ISSUE TITLE
Notebook TOC feature is causing long delay on startup

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6605]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open ADS with a folder loaded that has lots of files.  For example, load the azuredatastudio repo folder.

Expected: No long unnecessary delays on startup.

Actual: Notebook TOC loader adds 5 seconds to startup path even though I have no notebooks.

Note: The TOC crawler should limit itself to the top few levels of directories, or optimize itself some other way.

The below call tree shows the TOC loader taking 5+ seconds on startup.
<PRE>WARN UNRESPONSIVE extension host, 'Microsoft.notebook' took 100% of 5243.105ms, saved PROFILE here: </PRE>
![image](https://user-images.githubusercontent.com/599935/62501121-1cf45080-b79e-11e9-8b42-21d26142b87a.png)

**Comment by kburtram** [comment]
@lucyzhang929 could you please look at this issue this week?  We shouldn't ship this large a perf regression in the August release this month.  Thanks!

**Comment by lucyzhang929** [comment]
Will definitely take a look this week. Thanks for letting me know!

**Comment by Charles-Gagnon** [comment]
@lucyzhang929 Could you verify that this is resolved with your changes and close this if it is?
