### ISSUE TITLE
Flat File Import preview "Refresh" button is unnecessary

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6611]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run Flat File Import wizard and preview the data

Expected: Refresh button does something meaningful.  Perhaps refreshing the data after modifying it or with a different schema or something.

Actual: The refresh button re-reads the file without modification.  Not sure the use case.  I guess if the user manually changed the file on disk while the wizard was running, which seems like a corner-case scenario. 

Note: for reference SSMS does not provide a Refresh button on this screen.

ADS screen
![image](https://user-images.githubusercontent.com/599935/62505716-ab72cd00-b7b2-11e9-86b3-01e5ab0b04d3.png)

SSMS screen
![image](https://user-images.githubusercontent.com/599935/62505740-c1808d80-b7b2-11e9-9972-19f3b6325e12.png)

**Comment by aaomidi** [comment]
I remember we had a reason for getting this. I think the idea was if the user didn't like how ADS treated the data they can edit the file and refresh.

**Comment by kenvanhyning** [comment]
IIRC, it also was with the expectation that we would eventually provide options to configure the PROSE library on the preview page.  I'll move this to the backlog for now.

**Comment by kburtram** [comment]
This should be fixed on current builds.
