### ISSUE TITLE
Grid drag and select doesn't work all the time

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#6619]
Commit: https://github.com/microsoft/azuredatastudio/tree/0509234362278f9853a8167ebb9077d83baf3e24

If I place a breakpoint on https://github.com/microsoft/azuredatastudio/blob/bf4d53bd8a7c5df74df3414a5cf892f9d8ff5365/src/sql/base/browser/ui/table/plugins/cellRangeSelector.ts#L80-L83

Try to drag once, just simply tell the code to continue and then remove the breakpoint the drag and select functionality works for the life of that grid after that. 

However, drag and select essentially never works if I don't slow it down at least once with that breakpoint.

**Comment by alanrenmsft** [comment]
@aaomidi which feature are you working on? I don't think we have an area for the grid itself, If something is wrong with it and is blocking your feature development, you will need to assign it to yourself.

**Comment by aaomidi** [comment]
I'm making this issue so I can bring it up with @anthonydresser who has forked SlickGrid for ADS and try to see if anyone else has experienced this issue and what they might think it is.

**Comment by anthonydresser** [comment]
I've never seen an issue with drag selection @kburtram have you seen something around this before?

**Comment by kburtram** [comment]
The only issue I've seen with drag selection is that if you drag outside the visible region of the grid it doesn't scroll the grid and keep selecting (similar to how Excel behaves for example).  As long as the scrolling is within the visible grid the selection has worked correctly for me.  @aaomidi maybe we can checkout the repro you're seeing on your machine tomorrow.

**Comment by aaomidi** [comment]
Might be something I introduced in the PR I was working on. Thanks!

**Comment by aaomidi** [comment]
I'll probably close this because I can't repro this anymore, even on the branch I was working on.

Might have just been something else going on.
