### ISSUE TITLE
Moving to new row in Edit Data doesn't commit refresh previous rows changes

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#6638]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Edit Data on a table
2. Add a new row that has auto-populated files, such as generated primary keys or columns with default values
3. Navigate to next row

Expected: Row changes are committed when focus moves to different row and generated columns are refreshed with actual values.

Actual: Generated columns are not refreshed until at least one column in new row is updated and focus moved to another column.  Notice the issue in the below screenshot with `<TBD>` and `getdate` values after focus is in next row. 

<img width="679" alt="Screen Shot 2019-08-07 at 11 54 45 AM" src="https://user-images.githubusercontent.com/599935/62649752-3e724b00-b90a-11e9-90b7-a545fe4de0db.png">

**Comment by kburtram** [comment]
Looking somewhat related to https://github.com/microsoft/azuredatastudio/issues/2574.

**Comment by smartguest** [comment]
Closing as it no longer happens with the latest build
