### ISSUE TITLE
Import Wizard not showing up

### ISSUE THREAD

**Issue by ralphke** [microsoft/azuredatastudio#6639]
Issue Type: <b>Bug</b>

Trying to import data from an file, But Import Wizard dialog is not showing up.
Neither pressing CTRL-I nore activating it from the database context menue works with the current AZ-Data Studio build.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (8.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.41.0
import|Mic|0.9.0
profiler|Mic|0.9.0
server-report|Mic|0.1.5
sql-vnext|Mic|0.14.1
sql-dw|Mic|0.0.1

</details>

**Comment by kenvanhyning** [comment]
Tested and no repro on September release candidate build.  If you still see the issue please reopen and add any extra info you might have that could help us repro the issue too.
