### ISSUE TITLE
XML with 2 namespaces

### ISSUE THREAD

**Issue by davidmadi** [microsoft/azuredatastudio#6641]
Issue Type: <b>Bug</b>

When opening an xml with tags that belong to 2 different namespaces, one of the tags looses the namespace prefix.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
profiler|Mic|0.9.0

</details>

**Comment by alanrenmsft** [comment]
@davidmadi have you tried this scenario in VSCode? Does it behave the same, If so I'd recommend you to open an issue for vscode and once it is fixed there, we will get it automatically in Azure Data Studio.
