### ISSUE TITLE
Installing Notebook dependencies causes error

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#6644]
Running a notebook threw an error that I need to reinstall Notebook dependencies.
When I tried that I got the error:

"Cannot overwrite existing Python installation while python is running" ..

Close all my notebook/query tabs and tried again, and got the same error message. Its not clear what the user should do at this point. 

![image](https://user-images.githubusercontent.com/43253513/62663230-8eadd500-b92b-11e9-8a48-00ae07bbd7d3.png)

We need a better user experience .. something that tells the user what to do given the error condition.

**Comment by DataSnowman** [comment]
I got the same error

An exception has occurred, use %tb to see the full traceback.

SystemExit: Please upgrade the Notebook dependency before you can proceed, you can do it by running the "Reinstall Notebook dependencies" command in Azure Data Studio.
 C:\Users\darsch\AppData\Local\Continuum\anaconda3\envs\amldarwin\lib\site-packages\IPython\core\interactiveshell.py:3299: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

Also it was not clear where to run the command.  

I first tried to run it from the terminal and got this:

PS C:\Users\darsch> Reinstall Notebook dependencies
Reinstall : The term 'Reinstall' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ Reinstall Notebook dependencies
+ ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Reinstall:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException


I finally found it in the release notes at https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-2019-extension?view=sql-server-2017#release-notes-v080

Sometimes you get a bit to close to the process and others don't know where to find something the is very known to you

**Comment by DataSnowman** [comment]
Also I closed the notebook.  Was able to run the command to Reinstall Notebook dependencies.  It completed but when I tried the install again got the same error:
An exception has occurred, use %tb to see the full traceback.

SystemExit: Please upgrade the Notebook dependency before you can proceed, you can do it by running the "Reinstall Notebook dependencies" command in Azure Data Studio.
 C:\Users\darsch\AppData\Local\Continuum\anaconda3\envs\amldarwin\lib\site-packages\IPython\core\interactiveshell.py:3299: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

**Comment by corivera** [comment]
Updated the error messages to be more descriptive.
