### ISSUE TITLE
Notebook: Stopping cell in Spark kernel doesn't seem to stop Livy job

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#6650]
From @twright-msft:Open NB, connect to Live
Put some code in code cell.
Run a cell that takes some time.
Button changes to square icon (“stop”)
Click Stop
 
Actual result
Apparently nothing happens either in ADS or Spark/YARN.
 
Desired result
Kill job in Spark (not the YARN app container, just the Spark job)
Button goes back to Start state so I can run it again

**Comment by twright-msft** [comment]
In my recent testing this seems to be resolved now.
