### ISSUE TITLE
open file

### ISSUE THREAD

**Issue by aeromeme** [microsoft/azuredatastudio#6652]
Issue Type: <b>Feature Request</b>

When opening a file reconect is required, there must exist a default conection or preffered.

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.17134

**Comment by kburtram** [comment]
Thanks for this feature suggestion!  This looks like a duplicate of issue https://github.com/microsoft/azuredatastudio/issues/3410.  Please add any additional context there if anything is missing.
