### ISSUE TITLE
Confirmation message for code cells that dont return anything

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#6653]
Two different scenarios with same proposed solution:

When a user has a code cell with a bunch of variable assignments, function definitions etc, and the cell is run, theres no way for the user to know if the cell completed execution unless the user carefully watches the right arrow icon on the cell. 

Similar but slightly different scenario - The code cell has multiple long sequence of code (again could be variable assignments/function definitions etc as above) and the user knows it will take a few seconds to complete and proceeds to do other tasks. When the user is back to the notebook, (1) theres no easy way to know which cell the user just ran (2) when the cell completed execution and (3) how long did it take to complete execution etc.

**Proposed solution** -Display an "Execution completed at: <datetime>" message after each cell completes execution.

**Comment by alanrenmsft** [comment]
done
