### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader: Nvda announces the header row as "Clickable"

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6662]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #A11y_ADS_Schema_Dacpac_Backup; #Azure Data Studio; #DesktopApp; #Win10; #MAS1.3.1; #NVDA;

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Nvda Version: 2019.2rc2

**Additional Details:**
Tools Name: Nvda
MAS References: MAS1.3.1

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Dacpac extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Data-tier application wizard from Context menu.
8. Select first radio button.
9. Navigate till next button & hit enter.
10. Provide all the details for Deploy Dacpac & hit next.
11. Navigate till Next button & hit enter.
12. Start screen reader as Nvda.
13. Navigate to the table header row using arrow key arrow.

**Actual:**
On navigating to the header row of the table using arrow key, nvda announces "Clickable row1 column 1 setting " and announces the second header column perfectly without the word "Clickable".
When navigated from the last row to the first row of the table it announces   "Clickable row1 column 2 value" and coloumn1 is announced perfectly without the word "Clickable".

**Same issue is observed in the following pages:**
1.Extract Dacpac Summary Screen
Follow the exact same steps mentioned above but select the second radio button.
2.Import Bacpac Summary Screen
Follow the exact same steps mentioned above but select the third radio button.
3.Export Bacpac Summary Screen
Follow the exact same steps mentioned above but select the fourth radio button.

**Expected:**
The word "Clickable" should not be announced along with the cell value for the header row when navigated to it. The announcement should just be "row1 column 1 setting " and "row1 column 2 value" since they are not clickable.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: [(https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)](https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
Screen reader users will receive incorrect action information regarding the header row cells.

**MAS Reference:**
MAS 1.3.1- [https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4} ](https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}) 

**Attachment for Reference:**
[[Accessibility]A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3486207/Accessibility.A11y_AzureDataStudio.Schema.Dacpac.Backup._DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx)

**Comment by udeeshagautam** [comment]
Slickgrid header has on click and key down exposed and NVDA announces clickable for any such element which exposes this. Found similar issues 
https://github.com/nvaccess/nvda/issues/7430
https://github.com/nvaccess/nvda/issues/6161

The workaround from vscode (https://github.com/microsoft/vscode/pull/57127) seems to work but 
1) can not reach headers to apply role 
2) this does announce the element as form component which is not right for header

**Comment by hannahqin** [comment]
Reopening and reassigning to @fsteffi as per the [Accessibility External Bug Process](https://microsoft.sharepoint.com/teams/ceacc/SitePages/External-Bug-process.aspx). 

As Udeesha commented above, this issue is caused by how NVDA handles Slickgrid's header element. NVDA's default behavior is to announce 'Clickable' for any element that has a click listener, which is built into Slickgrid's header element. This is ultimately out of our control.

Per the discussion in nvaccess/nvda#7430, it seems like other users have had concerns with NVDA announcing 'Clickable' for any element that has a click listener, but there has been no resolution. It seems like they decided this is intended NVDA behavior.

Can you either file this issue with NVDA and track it there, or close this issue if you deem this to be expected NVDA behavior?

**Comment by hannahqin** [comment]
There's a related issue that was approved by an SME for exclusion: http://sqlbuvsts01:8080/Main/SQL%20Server/_workitems#_a=edit&id=11524922 (Azure Data Studio was formerly called SQL Operations Studio)

It references the same NVDA issue that is the cause of this accessibility bug in ADS. **Can we close this?**

**Comment by fsteffi** [comment]
Closing this bug as discussed with the SME.
