### ISSUE TITLE
Saving a previously-unnamed Query loses the connection/database setting

### ISSUE THREAD

**Issue by richardtallent** [microsoft/azuredatastudio#6668]
- Azure Data Studio Version: 1.9.0

Steps to Reproduce:

1. Create a new query, connect to a database.
2. Go to File:Save, enter a filename, and save the query.

Expected behavior:
Query continues to be connected to the same server and with the same database connection.

Actual behavior:
Query is immediately disconnected, requiring the user to connect the query to the desired server and database again.

This *may* be related to #4539, but I don't recognize the terms "Notebook," "Spark," and "cell" in the context of this tool (I'm only using it to run queries on Azure/MSSQL).

**Comment by Charles-Gagnon** [comment]
Thanks for the report! This is already being tracked with #5155 so I'm closing this as a duplicate.
