### ISSUE TITLE
Query database drop-down scroll position resets

### ISSUE THREAD

**Issue by richardtallent** [microsoft/azuredatastudio#6669]
- Azure Data Studio Version: 1.9.0 (Windows)

Steps to Reproduce:

1. Open a Query window.
2. Connect to a server with a fairly large number of databases (> 15 or so).
3. Open the drop-down menu for Database in the query toolbar and attempt to use the **mouse wheel** to scroll down to select a database closer to the bottom of the list.

Actual behavior: a few hundred milliseconds after scrolling down using the wheel, the drop-down's scroll position is reset back to the top of the database list. Scrolling down again works.

Cause: it appears the drop-down list is being refreshed from the server each time it is opened, but since there is a delay in getting the list, the scroll position gets reset when the database list is updated.

**Comment by alanrenmsft** [comment]
found this old issue and I gave it a try, no longer reproducible.
