### ISSUE TITLE
can not print

### ISSUE THREAD

**Issue by aeromeme** [microsoft/azuredatastudio#6674]
Issue Type: <b>Feature Request</b>

print is not enable

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alanrenmsft** [comment]
@aeromeme thanks for using ADS, ADS is a fork of VSCode with extra data related features, i noticed VSCode also doesn't have print, could you please open an issue in vscode repo instead?https://github.com/microsoft/vscode/
