### ISSUE TITLE
onConnectionComplete event only accepts a single handler

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#6681]
`ConnectionProvider#registerOnConnectionComplete` only accepts a single event handler. Any new event handler overwrites the last one.

This issue seems to go all the way down to `vscode-languageserver-node`. 

Useful codepoints:

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/azdata.d.ts#L459

https://github.com/microsoft/sqlops-dataprotocolclient/blob/master/src/main.ts#L263-L265

**Comment by aaomidi** [comment]
https://github.com/microsoft/vscode-languageserver-node/issues/299

**Comment by aaomidi** [comment]
So it seems like we need to handle this on sqlops-dataprotocolclient.

**Comment by kburtram** [comment]
Closing older engineering-focused issues to focus on customer scenario-facing bugs.
