### ISSUE TITLE
color issue

### ISSUE THREAD

**Issue by cyberh0me** [microsoft/azuredatastudio#6683]
Issue Type: <b>Bug</b>

same issue as with visual studio code
https://github.com/microsoft/vscode/issues/77678

works with "C:\Program Files\Azure Data Studio\azuredatastudio.exe --force-color-profile srgb"

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6600 CPU @ 3.30GHz (4 x 3312)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.94GB (8.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.41.0
dacpac|Mic|0.4.0
import|Mic|0.9.0
profiler|Mic|0.9.0

</details>

**Comment by cyberh0me** [comment]
this is a serious issue and makes this program UNUSABLE !

**Comment by kburtram** [comment]
@cyberh0me since this is being addressed upstream I'll close this issue.  We'll get the fix once it's merged into vscode master branch.  Thanks!

**Comment by cyberh0me** [comment]
still have the issue, ETA of the fix ?
Version: 1.12.0 (system setup)
Commit: f0b6180e15f455ccf9e8112b407a6aa8c5399fe9
Date: 2019-10-01T18:01:40.565Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18995

**Comment by aaomidi** [comment]
@cyberh0me https://github.com/microsoft/vscode/issues/77678 They've tagged it as fixed in electron 6. For now vscode has rolled back to electron 4 but once the update happens we'll also get it.

So hang tight for vscode to update - we're unable to speak of their timelines :)

**Comment by cyberh0me** [comment]
@aaomidi vscode already use Electron 6.1.2
