### ISSUE TITLE
Environment doesn't recover properly, after going back in once my laptop has gone back to sleep / period of inactivity passed.

### ISSUE THREAD

**Issue by acambitsis** [microsoft/azuredatastudio#6686]
Environment doesn't recover properly, after going back in once my laptop has gone back to sleep / period of inactivity passed.  Its doesnt ask me to reauthenticate, but things are in a "broken" state.  Open query windows dont seem to have a valid connection and the server explorer has a green status, but expanding the table view for example shows an error.

**Comment by kburtram** [comment]
Closing older issues.  We've made several improvements for this scenario in the ADS shell.  Please let us know if you still experience this bug on current builds.  Thanks!
