### ISSUE TITLE
OE behaving incorrectly with all of the Databases, Security and Server Objects folder missing

### ISSUE THREAD

**Issue by ronychatterjee** [microsoft/azuredatastudio#6687]
Issue Type: <b>Bug</b>

I observed this twice since yesterday in two separate machines.

<img width="378" alt="image" src="https://user-images.githubusercontent.com/22312581/62841858-a1911400-bc61-11e9-929a-78f5d8e88ce4.png">

Azure Data Studio version: Azure Data Studio 1.10.0-insider (1ff9a2ec4c7b88be01666bdd470bbbb4ab95716e, 2019-08-09T07:25:34.273Z)
OS version: Darwin x64 18.5.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 3, 3|
|Memory (System)|16.00GB (0.40GB free)|
|Process Argv|-psn_0_118813|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.41.0
azuredatastudio-postgresql|Mic|0.2.1
import|Mic|0.9.0
sql-vnext|Mic|0.15.0
azdata-sanddance|msr|1.3.90

</details>

**Comment by aaomidi** [comment]
Potentially related to: #6681 #6198 #5388

**Comment by abist** [comment]
@Charles-Gagnon do you have any additional context to this?

**Comment by Charles-Gagnon** [comment]
We've seen issues with the database nodes not populating before, which is likely what's happening here. The Data Services folder is provided by another provider so that'd likely be why it's the only one showing up.

Beyond that though we haven't investigated why the nodes aren't showing up since it's a bit difficult to repro currently. So some more investigation needs to be done.

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still impacted by this on current builds.
