### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader: Jaws announces the heading "Summary" as "Clickable"

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6693]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Jaws Version: 2019.1907.31 ILM

**Additional Details:**
Tools Name: Jaws
MAS References: MAS1.3.1

**Repro Steps:**
1.Launch Azure Data Studio application.
2.Connect to server with windows credentials.
3.Navigate to Extensions from left menu.
4.Search & install Dacpac extension.
5.Navigate to Connections from left menu.
6.Expand the server connected in step 2.
7.Right click an on prem database and select Data-tier application wizard from Context menu.
8.Select first radio button.
9.Navigate till next button & hit enter.
10.Provide all the details for Deploy Dacpac & hit next.
11.Navigate till Next button & hit enter.
12.Start screen reader as Jaws.
13.Navigate to the heading "Summary' using arrow key arrow.

**Actual:**
On navigating to the heading "Summary", Jaws announces it as "Clickable".

**Same issue is observed in the following pages:**
1.Extract Dacpac Summary Screen
Follow the exact same steps mentioned above but select the second radio button.
2.Import Bacpac Summary Screen
Follow the exact same steps mentioned above but select the third radio button.
3. ImportBacpacSettings
Follow the exact same steps mentioned above but Select third radio button and the page is displayed.
issue observed for the heading(Select import bacpac settings)
4. ExportDacpacSettings
Follow the same steps mentioned above but select the second radio button and the page is displayed.
issue observed for the heading(Select extract dacpac settings)

**Expected:**
The word "Clickable" should not be announced when navigated to the heading "Summary". The announcement should just be "Heading level 1 Summary"

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: (https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx)

**User Impact:**
The screen reader user will try to perform an unnecessary action on the heading due to the word clickable, which would not result in any action.

**MAS Reference:**
MAS 1.3.1- https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4} 

**Attachment for Reference:**
[#6693[Accessibility]A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3491927/6693.Accessibility.A11y_AzureDataStudio.Schema.Dacpac.Backup._DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx)

**Comment by fsteffi** [comment]
This issue is observed with other screen reader too.

**Comment by kisantia** [comment]
Closing this because it didn't repro with NVDA. Only "Summary" was announced, not clickable

![image](https://user-images.githubusercontent.com/31145923/64211683-c9882780-ce5b-11e9-9d63-4d12a3498374.png)

**Comment by fsteffi** [comment]
Checked and verified in below version the bug is no longer reproduced and hence closing the bug.

Version Details:
Version: 1.12.0-insider
Commit: a584aca96997a18ecedee73a575536332e542718
Date: 2019-09-19T07:58:50.448Z
VS Code 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
[#6693 A11y_AzureDataStudio(Schema,Dacpac,Backup)_DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3669124/6693.A11y_AzureDataStudio.Schema.Dacpac.Backup._DeployDacpac_DeployDacpacSummaryScreen_ScreenReader.pptx)
