### ISSUE TITLE
Import Extension Still References sqlops APIs; Users See Message on Startup

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#6701]
With the August RC bits, I see the following message when launching ADS with the Import extension installed:

![image](https://user-images.githubusercontent.com/40371649/62888613-828f9200-bcf4-11e9-92e2-4496329e9bc9.png)

**Comment by Charles-Gagnon** [comment]
Odd, I'm not seeing that...can you confirm the version of the Import Extension that you're using? @alanrenmsft any idea why I wouldn't be seeing this? The config setting to show the warnings is enabled. Does anyone else see this?

**Comment by alanrenmsft** [comment]
@chlafreniere I am not seeing that either, can you share the console log?

**Comment by kenvanhyning** [comment]
Looks fixed (or no repro) with September release.  May have been a mismatch of extension and core build.
