### ISSUE TITLE
Multiple Grids are Rendered on First Query

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#6703]
File -> New Query

do a “select 1”

2 grids will show up in the Results pane:
![image](https://user-images.githubusercontent.com/40371649/62889171-a1425880-bcf5-11e9-8620-028cb13e0497.png)

Note: this only appears to happen the first time that this query is run, but I’ve been able to repro the issue a number of times reliably.

**Comment by kburtram** [comment]
I hit this too.  @anthonydresser we saw a similar bug a while.  Could you please check if that logic has changed\regressed?

<img width="1103" alt="Screen Shot 2019-08-12 at 1 54 19 PM" src="https://user-images.githubusercontent.com/599935/62897852-eb810500-bd08-11e9-8a56-48e302b6c89f.png">

**Comment by anthonydresser** [comment]
I'll take look but I can't think of any changes in this area recently
