### ISSUE TITLE
Import wizard doesn't start on Ctrl+I

### ISSUE THREAD

**Issue by DFrizen** [microsoft/azuredatastudio#6704]
Issue Type: <b>Bug</b>

install, then just press Import Wizard from context menu
nothing happens (

Azure Data Studio version: azuredatastudio 1.3.9 (cacf0777c747046af6839de3688d709b10ef9fca, 2019-01-14T23:16:16.319Z)
OS version: Linux x64 5.0.0-23-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz (4 x 1882)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>video_decode: unavailable_software<br>video_encode: unavailable_software<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.60GB (10.92GB free)|
|Process Argv|/usr/share/azuredatastudio/azuredatastudio --unity-launch|
|Screen Reader|no|
|VM|0%|

</details>

**Comment by Charles-Gagnon** [comment]
Could you try updating to the latest stable version of ADS (1.9) and try again? I'm not able to repro this on that version. 

If that still doesn't work can you open the Developer Console (Help menu -> Toggle Developer Tools -> click the Console tab in the pane) and see if there's any errors there?

**Comment by DFrizen** [comment]
it works after update on 1.9.0 and reinstall extension
thanks!
