### ISSUE TITLE
Notebook Icon Overlaps with Indentation Lines in Explorer Viewlet

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#6706]
Indentation lines in the file explorer overlap with the notebook icon. May need to see if we can either make the icon smaller here, or add some padding.

![image](https://user-images.githubusercontent.com/40371649/62893197-dacb9180-bcfe-11e9-80f1-b565ac2e8747.png)

**Comment by MaddyDev** [comment]
Not able to repro this anymore, closing it.
