### ISSUE TITLE
Notebook tabs do not follow a rename in Explorer

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#6718]
Issue Type: <b>Bug</b>

If you create a notebook, then rename it in explorer while it is still open, the tab does not show the new name.
![image](https://user-images.githubusercontent.com/12263288/62905455-965ce780-bd38-11e9-82e6-e4722874cae9.png)
![image](https://user-images.githubusercontent.com/12263288/62905456-9a890500-bd38-11e9-8e3c-bf7f1d6e6c6d.png)

Azure Data Studio version: azuredatastudio 1.9.0 (78a42e1d112ae3231777722b51eaf44f83ddbe55, 2019-07-10T04:31:36.998Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: disabled_software<br>checker_imaging: disabled_off<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>rasterization: disabled_software<br>surface_synchronization: disabled_off<br>video_decode: disabled_software<br>webgl: disabled_off<br>webgl2: disabled_off|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.1
profiler|Mic|0.9.0
whoisactive|Mic|0.1.1

</details>

**Comment by chlafreniere** [comment]
We now close notebooks that have been renamed, so this bug no longer reproes.
