### ISSUE TITLE
OE expands original connection when changing the database from default before connecting

### ISSUE THREAD

**Issue by MattIrv** [microsoft/azuredatastudio#673]
SQL Operations Studio Version: Feb. release candidate 0.26.3

Steps to Reproduce:
1. Save a default database connection. Do not save the password. Make sure it is disconnected for the following steps:
2. Click on the saved connection. The connection dialog will open
3. Fill in the password and expand the databases dropdown and choose a different database
4. Connect and observe that the original connection shows as connected and expanded in OE, but has no folders

![The default database connection is connected and expanded but has no child folders](https://user-images.githubusercontent.com/3758704/36121300-95ce3fcc-0ffa-11e8-9980-8678f535cff6.png)

Expected behavior: Only the new connection (with the different database) shows as connected and expanded. This was the behavior in the January release, so this probably happens as a side effect of the databases dropdown creating a default connection.

**Comment by kburtram** [comment]
@MattIrv as far as I can tell, this appears to only be a problem when a "<default>" connection is in the same group as a connection explicitly to the default database (for example "master" in most cases).  Is this the same behavior you're seeing?

**Comment by MattIrv** [comment]
@kburtram I don't have a saved connection to master there, only to the default "" database

**Comment by kburtram** [comment]
Closing older bugs that are planned for an upcoming milestone.  Thanks!
