### ISSUE TITLE
Consolidate BDC logic

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6753]
Currently logic for handling BDC cluster display (such as mapping friendly names) is duplicated in the mssql and big-data-cluster extensions. We should consolidate them - likely having functionality like that be an export of one of the extensions that the other calls.

**Comment by kburtram** [comment]
Closing older issues.  I think for the most part we're tracking task-level work in the ADO Plans.  Please reactive if this issue is still being tracked for upcoming work.
