### ISSUE TITLE
Clicking on field containing JSON doesn't always open new file with formatted JSON

### ISSUE THREAD

**Issue by jpxrc** [microsoft/azuredatastudio#6765]
- Azure Data Studio Version: 1.9.0

Steps to Reproduce:
1. Run a query with results that includes a field with JSON.
2. Clicking on the JSON text sometimes results in a new window with formatted JSON and sometimes clicking on the text does nothing.

It seems that I am able to open the new window with formatted JSON only when the JSON block is not too long (< 30 lines) but doesn't work for larger JSON blocks (>100 lines). Is there some sort of line limitation for opening and formatting fields with JSON?

**Comment by kburtram** [comment]
I was not able to repro this on the current build.  Please let us know if this bug is still impacting your use case.  Thanks!
