### ISSUE TITLE
Refresh on HDFS subtree collapses up to top-level in NodeProvider API, so have to re-expand

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#6787]
Issue Type: <b>Bug</b>

Connect to a big data cluster and expand to some folder under HDFS. Right-click and choose "Refresh"

Expected:
- Refresh occurs, and we show new contents of the folder you refreshed on
Actual:
- Tree collapses up to "Data Services" which is the 1st of the nodes provided by the NodeProvider API. It fails to re-expand to the level you refreshed at. Users must click 3 levels deep, which is frustrating

Azure Data Studio version: azuredatastudio 1.10.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|16.00GB (0.20GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-es|Mic|1.9.0
sql-vnext|Mic|0.14.1

</details>

**Comment by mm-dsibinski** [comment]
Yes, this is really frustrating...
One more precise scenario to reproduce this issue:
1. Connect to a server, so you have a databases list tree
2. Expand: Databases 
3. Choose one database and expand it
4. Expand "Tables"
5. Choose one table and expand it
6. Expand for instance "Columns"
7. Click on "Columns" folder and select "Refresh"
8. See the issue: everything is collapsed, so to see the result (e.g. added column) you need to repeat expanding everything again

**Comment by iks111** [comment]
Yes, this is really frustrating...
One more precise scenario to reproduce this issue:

1. Connect to a server, so you have a databases list tree
2. Expand: Databases
3. Choose one database and expand it
4. Expand "Tables"
5. Choose one table and expand it
6. Expand for instance "Columns"
7. Click on "Columns" folder and select "Refresh"
8. See the issue: everything is collapsed, so to see the result (e.g. added column) you need to repeat expanding everything again
