### ISSUE TITLE
Allow separate theme for integrated terminal

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#6793]
**Is your feature request related to a problem? Please describe.**
When I'm screen-casting, I can't get a clear visual delineation between the editor and the integrated terminal.

**Describe the solution or feature you'd like**
I would like to be able to choose font and background colors for the integrated terminal separately from the editor and other elements. e.g. use a light theme for the editor but a dark theme (with green text e.g.) for the terminal, in order to have a greater visual differentiation between the two.

**Describe alternatives you've considered**
I haven't found any alternatives that do what I want.

**Additional context**
Here's a mock-up (I stitched two sessions together) of what it would look like:

![image](https://user-images.githubusercontent.com/12263288/63228817-dacc0580-c1c6-11e9-878f-89494dba6cdc.png)

**Comment by kburtram** [comment]
We are using the terminal unmodified from vscode.  Please log this enhancement against that repo if you are still impacted by this issue.  Thanks!
