### ISSUE TITLE
Server dashboard insight widgets are broken

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#6806]
tested on mac

![Screen Shot 2019-08-19 at 11 10 59 AM](https://user-images.githubusercontent.com/13777222/63288653-17087000-c272-11e9-89ad-41b28a1161e6.png)

**Comment by anthonydresser** [comment]
Do you have a more solid repro? It doesn't seem to be an issue for me.
![image](https://user-images.githubusercontent.com/4324725/63294812-170f6c80-c280-11e9-8371-1ac99fd9a236.png)

**Comment by alanrenmsft** [comment]
interesting, I can no longer reproduce it

**Comment by anthonydresser** [comment]
I can take a quick look through that code path and see if I see anything that would obviously cause this.

**Comment by alanrenmsft** [comment]
@anthonydresser additional information: I was using Mac when I saw this
