### ISSUE TITLE
Add toolbar button for Comment/Uncomment text selection

### ISSUE THREAD

**Issue by mrg3d** [microsoft/azuredatastudio#681]
- SQL Operations Studio Version:

Steps to Reproduce:

Consider to introduce the possibility of Commenting out or Uncommenting a block of selected text.

![image](https://user-images.githubusercontent.com/412938/36160504-a0530bb6-10e1-11e8-975c-79adc27f97da.png)

**Comment by kburtram** [comment]
@mrg3d have you tried the `Ctrl-K C` shortcut for the Comment Block command (`Ctrl-K U` is for Uncomment Block)?

**Comment by SebastianPfliegel** [comment]
Or `Ctrl #` for toggling.

**Comment by mrg3d** [comment]
Thank you guys for your suggestions!
But what about add this commands on a toolbar or on mouse right click context menu?

**Comment by SebastianPfliegel** [comment]
@mrg3d: yeah could be, using the German keyboard layout. Try `F1` to open the command prompt and enter `Toggle Line Comment`. On the right side you should see the hotkey for your layout.

**Comment by robinhalabicki** [comment]
> Thank you guys for your suggestions!
> But what about add these commands on a toolbar or on mouse right click context menu?

I would love this, in particular /* */ around selected section instead of --

**Comment by kburtram** [comment]
The comment\uncomment functionality is coming from the vscode platform upstream.  I'll close this older issue since we'd prefer to have this addressed upstream.  Thanks!
