### ISSUE TITLE
Error occurs when trying to connect Profiler to server in Azure Data Studio Insiders

### ISSUE THREAD

**Issue by nielsberglund** [microsoft/azuredatastudio#6820]
Issue Type: <b>Bug</b>

On the latest Insider build, (Version: 1.10.0-insider date 2019-08-18T14:37:30.357Z), the dialog to choose new profiler session does not appear, but instead the main profiler screen comes up together with an error notification: "An unexpected error occured when connecting. Please ...". 

Expected behavior is to get the Start New Profiler Session dialog, and connect.

This works fine on the non insider Azure Data Studio build: 
Version: 1.10.0 (system setup)
Date: 2019-08-14T18:28:10.311Z

Azure Data Studio version: azuredatastudio-insiders 1.10.0-insider (7f6839d38e24ebd637f2b7ae3b7a5995421c44b2, 2019-08-18T14:37:30.357Z)
OS version: Windows_NT x64 10.0.18950

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz (8 x 3400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|23.68GB (12.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by nielsberglund** [comment]
I just updated to the latest release of Azure Data Studio - Insiders (1.11.0-insider), and Profiler now works as expected. I am happy to close, but I'll let someone else decide.

**Comment by Charles-Gagnon** [comment]
I appreciate the follow up - glad to hear the issue was resolved!
