### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Screenredeader: NVDA reads "Row11 Include.. and focus remains constant on the check box".

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6821]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Additional Details : MAS1.3.1, NVDA 2019.2, Jaws
**Repro Steps :** 
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Compare menu from Schema compare Menu bar & hit enter.
12. Start NVDA and use up/down arrow keys or tab to navigate to the table.
13. Check how nvda reads the information.

**Actual:**
When we are moving to the table using up/down arrow keys or tab keys , NVDA reads the wrong information "Row 11 Include.. " and focus is highlighted on the check box which is not correct.

Same issue is observed with Jaws
 
**Expected:**
NVDA should not read the extra information and focus should not highlighted to the check box.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screenreader users will not able to know the right information.

**MAS Reference:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment for Reference:**
![6821_A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Screenredeader](https://user-images.githubusercontent.com/24580570/63328706-412f6000-c34e-11e9-8dec-c5d84c05770d.png)

**Comment by kisantia** [comment]
Fixed with table changes. 

![image](https://user-images.githubusercontent.com/31145923/64212651-f853cd00-ce5e-11e9-8bea-f33e8359406b.png)

**Comment by udeeshagautam** [comment]
As per the conversation with Accessibility team it is fine/ preferred to not have tabbing inside table at all. Only arrow navigation.
