### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Keyboard: Keyboard focus is not moving to the next control when we are pressing Shift+Tab after the "SqlTable cell value".

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6823]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Additional Details : MAS2.1.2, Keyboard
**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Compare menu from Schema compare Menu bar & hit enter.
12. Navigate to the "SqlTable" and press Shift tab to navigate to the previous control.

**Actual:**
Keyboard focus is not moving to the next control (...), when we are pressing Shift Tab after the "SqlTable cell value". It is getting trapped.

**Expected:**
Keyboard focus should move to the next element( …) when users press shift tab.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Keyboard users will not be able to access previous control.

**MAS Reference:**
https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={ebdc3fe1-09a9-4aa2-a29b-e97764774e6c}

**Attachment for Reference:**

[6823_A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Keyboard11.pptx](https://github.com/microsoft/azuredatastudio/files/3519819/6823_A11y_AzureDataStudio.Schema.Dacpac.Backup._Comparison_Keyboard11.pptx)

**Comment by kisantia** [comment]
Fixed by #6863. Focus can now be moved back from the table to to the "..." button using Shift Tab.

**Comment by fsteffi** [comment]
Issue does not repro now we able to move to previous control using Shift+tab Key
hence closing this bug.
