### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_ Review Deploy Plan_Screenreader: NVDA is not announcing the status after submitting the Select Deploy Dacpac Settings

### ISSUE THREAD

**Issue by mspatil110** [microsoft/azuredatastudio#6826]
“[Check out Accessibility Insights!](url) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”
**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.10.0-insider (user setup)
Commit: 1ff9a2ec4c7b88be01666bdd470bbbb4ab95716e
Date: 2019-08-09T07:49:00.254Z
VS Code 1.37.0
Electron: 4.2.7
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Additional Details:**
Tools Name: Accessibility insight tool
MAS References: MAS4.1.3

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Dacpac extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Data-tier application wizard from Context menu.
8. Select first radio button.
9. Navigate till next button & hit enter.
10. Launch NVDA.
11. Provide all the details for Deploy Dacpac & hit next.
12. Observed that After submitting the Select Deploy Dacpac Settings screen NVDA is announcing or not the Status “Loading ..Loading”.

**Actual:**
After submitting the Select Deploy Dacpac Settings screen NVDA is not announcing the Status “Loading ..Loading”.

**Expected:**
After submitting the Select Deploy Dacpac Settings screen NVDA should  announce the Status “Loading ..Loading”.

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader users will face difficulty to understand status of the Review the Deploy plan screen.

**MAS Reference:**

MAS 4.1.3- 
https://microsoft.sharepoint.com/:w:/r/teams/msenable/Documents/LCA/MAS%20-%20July%201,%202017%20Release/MAS%204.1.3%20%E2%80%93%20Status%20Messages.docx?d=w684573a7b08941319b390009054125d3&csf=1&e=e3Fr7d

**Reference Attachment:**
![6826_Bug](https://user-images.githubusercontent.com/51433293/63343214-0ee02b80-c36b-11e9-8ab6-224e9b4b5f16.png)

**Comment by Benjin** [comment]
Question added to OneNote: do we want to announce both "Loading" and completion of the LRO?

**Comment by Benjin** [comment]
NVDA does _not_ support `aria-live` fields, but the fix has been confirmed with Narrator and JAWS.
