### ISSUE TITLE
"AT TIME ZONE" in Query Erroneously Flagged as Incorrect Syntax

### ISSUE THREAD

**Issue by obviousSailfish** [microsoft/azuredatastudio#6827]
Issue Type: <b>Bug</b>

"Incorrect syntax near 'AT TIME ZONE'" is erroneously being generated for queries that properly use "AT TIME ZONE".

The following correct example is erroneously flagged as incorrect:

SELECT CONVERT(datetime2, '2019-07-01') AT TIME ZONE 'US Eastern Standard Time';

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3840QM CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|14%|
</details>Extensions: none

**Comment by kburtram** [comment]
@obviousSailfish I don't see an error message from the SQL snippet in the issue.

**Comment by obviousSailfish** [comment]
Please see the attached screenshot.

I'm connected to Azure SQL Database...

- Version: Microsoft SQL Azure (RTM) - 12.0.2000.8 	Aug 27 2019 17:56:41 	Copyright (C) 2019 Microsoft Corporation
- Database Compatibility Level: 140

Here's updated information on my version of Azure Data Studio:

Version: 1.11.0
Commit: 460c739a8d90bdbbde39e01abfb8ecdc278ea787
Date: 2019-09-06T17:14:33.682Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 18.7.0

![Screen Shot 2019-09-17 at 4 54 54 PM](https://user-images.githubusercontent.com/4428568/65082582-f2381300-d96b-11e9-8e07-5cfeff1d634d.png)

**Comment by KevinTupper** [comment]
Same issue affection Visual Studio 2019

**Comment by szymonos** [comment]
Bug still exists on Azure databases
![image](https://user-images.githubusercontent.com/27199249/83385079-d769d980-a3e8-11ea-8703-881c9e480b28.png)

Azure Data Studio 1.18.1.

**Comment by RichWK** [comment]
Any progress on this issue? It's been like this for a looooong time now.

@kburtram @Charles-Gagnon

**Comment by jberlyn** [comment]
I'm also experiencing this issue on 1.29.0.

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if anyone wants to try it out on our insiders builds to verify that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main

**Comment by RichWK** [comment]
@Charles-Gagnon Since coming across this, the project I was working on has finished and I've changed jobs, but — great to know that it's sorted now! 😄🎉

**Comment by potatoqualitee** [comment]
this is valid and processed by postgres but fails in ads. 

![image](https://user-images.githubusercontent.com/8278033/213923721-6ff730ab-7beb-47a1-84c3-9dae3c4b15dd.png)

![image](https://user-images.githubusercontent.com/8278033/213923737-85bc3beb-1aaa-46e0-8455-912c010e05a1.png)

![image](https://user-images.githubusercontent.com/8278033/213923765-868dd804-c28c-409e-93f8-76f011bb68ba.png)

**Comment by potatoqualitee** [comment]
maybe i should open a new issue 😅

**Comment by Charles-Gagnon** [comment]
@potatoqualitee - Yes, please open a separate issue in the https://github.com/microsoft/azuredatastudio-postgresql/issues repo
