### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Keyboard: After activating the popup "Recompare" keyboard focus order is not logical 

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6870]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362

**Additional Details:**
MAC 10.14.6 
MAS reference: MAS2.4.3
Repro Steps:

1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7.Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Options menu from Schema compare Menu bar & hit enter.
12. Check or uncheck some options & hit Ok.
13. Validate Re-compare pop will open
14. Use tab key to navigate to the control of the popup and check the navigation.

**Actual:**
After activating the popup "Re-compare" keyboard focus is moving to "Options button" , it does not move inside the popup.

Same issue is observed when the Voice over is on.

**Expected:**
After activating the popup keyboard focus should move "Inside the Re-compare Popup".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Keyboard user will not be able to know the flow of the screen.

**MAS Reference:**
MAS2.4.3: https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={0de7fbe1-ad7e-48e5-bcbb-8d986691e2b9}

**Attachment for Reference:**
![6870_A11y_AzureDataStudio(Schema,Dacpac,Backup)_Recompare pop up_Keyboard](https://user-images.githubusercontent.com/24580570/63512787-3b7a7b80-c502-11e9-829d-2fb819bcb589.png)

**Comment by fsteffi** [comment]
Reusing the bug as this is duplicate

**Comment by udeeshagautam** [comment]
Dup of this - https://github.com/microsoft/azuredatastudio/issues/6661
Related issue https://github.com/microsoft/azuredatastudio/issues/6663

**Comment by abist** [comment]
@udeeshagautam I'm going to remove these extra tags on these issues that didn't exist earlier because it broke the issues report. If you need these new tags, please let me know so I can change the report accordingly.
