### ISSUE TITLE
Unexpected error connecting

### ISSUE THREAD

**Issue by angiescott-macmillan** [microsoft/azuredatastudio#6874]
Issue Type: <b>Bug</b>

Connect to server
Click new notebook
Click new query
Wait for new query to pop up and wait.  
Unexpected error connecting .... is the error raised.

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (14)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.4.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
dacpac|Mic|0.5.0
import|Mic|0.9.0
managed-instance-dashboard|Mic|0.3.7
powershell|ms-|2019.5.0
profiler|Mic|0.9.0
schema-compare|Mic|0.5.0
server-report|Mic|0.1.5
whoisactive|Mic|0.1.1
sql-search|Red|0.3.3
plan-explorer|Sen|0.9.6

</details>

**Comment by Charles-Gagnon** [comment]
If this is on the insiders build this is a known issue and there should be a new build out today with a fix for this. Sorry for the inconvenience!
