### ISSUE TITLE
Notebook ModelReady Event can be Fired Multiple Times

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#6884]
A notebook's modelReady event is fired multiple times if the same notebook is opened/closed more than once. We're not disposing of the listeners correctly somewhere. This can cause some really nasty behavior (like reacting to contentChanged events n times instead of just once).

**Comment by aasimkhan30** [comment]
I have registered NotebookEditorModel so it won't happen. Please have a look at my PR
https://github.com/microsoft/azuredatastudio/pull/6891

**Comment by chlafreniere** [comment]
This isn't a ship blocker

**Comment by chlafreniere** [comment]
This was fixed by #6891.
