### ISSUE TITLE
A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Screenreader : Voice Over reads "Rows value Include ticked tick box .. and focus remains constant on the ticked box".

### ISSUE THREAD

**Issue by fsteffi** [microsoft/azuredatastudio#6904]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

**Environment Details:**
Application Name: Azure Data Studio
Application Version: 1.9.0 (user setup)
Commit: 78a42e1
Electron: 3.1.8
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.18362
Additional Details : MAS1.3.1
MAC 10.14.6

**Repro Steps :** 
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Compare menu from Schema compare Menu bar & hit enter.
12. Start Voice over and use control+option+arrow keys or tab to navigate to the table.
13. Check how Voice over reads the information.

**Actual:**
Voice Over reads "Rows value Include ticked tick box .. and focus remains constant on the ticked box".
 
**Expected:**
Voice Over should not read the "Rows value Include ticked tick box .. and focus should not move to the ticked box".

**Recommendations:**
Refer below link which is repository of bug fixes code snippets: https://microsoft.sharepoint.com/teams/msenable/mas/pages/browse-fixes.aspx

**User Impact:**
Screen reader users will not able to know the right information.

**MAS Reference:**
[https://microsoft.sharepoint.com/:w:/r/teams/msenable/_layouts/15/WopiFrame.aspx?sourcedoc={54f28d1f-a2d1-4dcd-84e1-5c9b87e8aba4}](url)

**Attachment for Reference:**
![6904_A11y_AzureDataStudio(Schema,Dacpac,Backup)_Comparison_Screenreader](https://user-images.githubusercontent.com/24580570/63582228-560e2c80-c5b6-11e9-9aa4-d78c38744667.png)

**Comment by udeeshagautam** [comment]
Validated this - seems like the PR for cell focus https://github.com/microsoft/azuredatastudio/pull/6882 fixed it

**Comment by fsteffi** [comment]
https://github.com/microsoft/azuredatastudio/issues/6821
As the primary bug still able to reproduced hence reopened this bug.
