### ISSUE TITLE
Click on sql_text column in sp_whoisactive does not open new document

### ISSUE THREAD

**Issue by phenno1** [microsoft/azuredatastudio#6906]
Hi all!

If we execute sp_whosactive and click on sql_text column there should be opened new document with data from sql_text column. It often happens that document is not opened though document counter on a left bar increments counter. After Azure studio is reopened all those documents appears. 

- Azure Data Studio Version:
Version: 1.10.0 (user setup)
Commit: 5fdb967ffcea41df0335ec17cfa396a694bb174e

Steps to Reproduce:

1. run sp_whoisactive with default options
2. click on sql_text column which does not open new document. In left bar we can see 10 open documents while none is shown in Azure Data Studio. 

![image](https://user-images.githubusercontent.com/47591999/63582589-a5922f80-c599-11e9-8640-086261705517.png)

3. restart Azure Data Studio and all documents are now shown

![image](https://user-images.githubusercontent.com/47591999/63582790-00c42200-c59a-11e9-8221-d3e5d4e35b2b.png)

**Comment by bortolin** [comment]
I have the same problem.
