### ISSUE TITLE
Maintenance Plans

### ISSUE THREAD

**Issue by pharbison** [microsoft/azuredatastudio#6913]
- Azure Data Studio Version: 1.10

Are there any plans to add Maintenance Plan management?

**Comment by kburtram** [comment]
@Fatboy125 we don't currently have plans to bring Maintenance Plans to ADS.  One challenge with this feature is that SSIS doesn't have a cross-platform implementation (it contains a lot of C++ COM).  I'll keep this feature request in the backlog for PMs to consider.
