### ISSUE TITLE
Clicking "submit a bug" or "report issue" does not open a dialog in Insiders

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#6919]
Clicking "submit a bug" or "report a bug" is not doing anything in my Insider's build today. Unsure if this will repro through a restart. I have the ProcMon logs from August stable vs today's Insider's, on request.

**Comment by chlafreniere** [comment]
I can't repro this at the moment. Can you still repro, @vickyharp?

**Comment by kburtram** [comment]
I can't repro either on today's build.  Please reactive if this persists.
