### ISSUE TITLE
Jupyter Books Viewlet : Nodes have extra actions

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#6927]
Refresh and Delete don't seem to do anything.

Manage launches the BDC dashboard which (as expected) doesn't load correctly. 

![image](https://user-images.githubusercontent.com/28519865/63628458-7c859500-c5c1-11e9-8b66-de7523fe4928.png)

**Comment by chlafreniere** [comment]
Fixed by #6964.
