### ISSUE TITLE
Populating connection information is very slow

### ISSUE THREAD

**Issue by jasoncavett** [microsoft/azuredatastudio#6936]
1. Open ADS
2. Open a new Query screen
3. Select "Connect"
4. Highlight a saved connection
5. It takes up to 10 seconds to populate the field.

Expected Result: Immediate population of the data

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (7.05GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
dacpac|Mic|0.5.0
import|Mic|0.9.0
profiler|Mic|0.9.0

</details>

**Comment by Charles-Gagnon** [comment]
@jasoncavett Can you attach a gif/video of this behavior? Does this happen for all connections through the connection dialog or only with ones from the **Connect** button in a query editor?

**Comment by jasoncavett** [comment]
Hi @Charles-Gagnon. I just checked on version 1.11.0 (user setup) and it now comes back quickly so this bug is no longer an issue. (It occurred when I would click Connect on the SQL Query editor, but it no longer happens.).

Thank you for checking in on this.
