### ISSUE TITLE
Extension "sp_executesql to SQL" is not working

### ISSUE THREAD

**Issue by DanielAdeniji** [microsoft/azuredatastudio#6942]
Azure Data Studio Version: 1.10.0
Extension :- sp_executesql to SQL
Versions :- 0.0.1 and 1.0.0

Steps to Reproduce

1. Add Extension - sp_executesql to SQL
2. Pasted SQL that contains sp_executesql
3. Selected SQL
4. Access Help/F1
5. Entered convert into Help text field
6. Chose "sp_executesql to sql: convert" from menu
7. No conversion

Documented Here :-

Azure Data Studio – Extension – “sqlops-spexecutesql-to-sql”
https://learningintheopen.org/2019/08/24/azure-data-studio-extension-sqlops-spexecutesql-to-sql/

**Comment by PejmanNik** [comment]
Hi @DanielAdeniji
I'm the author of "sp_executesql to SQL" extension.
Can you please flow up this issue in the extension repo?
https://github.com/PejmanNik/sqlops-spexecutesql-to-sql
Please create an issue there with your SQL code.
Thank you.

**Comment by Charles-Gagnon** [comment]
Thanks for following up @PejmanNik  - I'll close this one out then so you can track it in your extension repo.

**Comment by DanielAdeniji** [comment]
Pejman :-

I just checked https://github.com/PejmanNik/sqlops-spexecutesql-to-sql.

Currently, that GitHub repository does not have an Issue Tab.

And, it does not appear that there is an avenue to create bugs.

Please advice if otherwise.

Daniel

**Comment by PejmanNik** [comment]
It is strange @DanielAdeniji .
You can use this link to create an issue:
https://github.com/PejmanNik/sqlops-spexecutesql-to-sql/issues/new

**Comment by DanielAdeniji** [comment]
Pejman :-

Sorry about that.

Thanks so very much.
Daniel

**Comment by PejmanNik** [comment]
You're welcome @DanielAdeniji  👍
