### ISSUE TITLE
Sample "sp_WhoIsActive" throws warning on launch

### ISSUE THREAD

**Issue by Eagle3386** [microsoft/azuredatastudio#6968]
Issue Type: <b>Bug</b>

1. Install whoisactive via built-in extensions manager
2. Warning pops up immediately & every program launch after that:
> Some of the loaded extensions are using obsolete APIs, please find the detailed information in the Console tab of Developer Tools window

Developer Tools's Console tab details:
> The extension "Microsoft.whoisactive" is using sqlops module which has been replaced by azdata module, the sqlops module will be removed in a future release.
console.(anonymous function) @ c:\Program Files\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (b1ebf608367ec5c382d1c8f2510d3e9acaa3732b, 2019-08-26T17:29:06.648Z)
OS version: Windows_NT x64 6.1.7601

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4710MQ CPU @ 2.50GHz (8 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|19.63GB (7.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by amachanic** [comment]
@Charles-Gagnon the thing you linked to is *not* the extension, it's a SQL stored procedure on which the extension is based.

[The extension is here.](https://github.com/microsoft/azuredatastudio/tree/master/samples/sp_whoIsActive) -- And it's part of this repo, so this issue should be left open and/or fixed here.

**Comment by Charles-Gagnon** [comment]
Ah, sorry about that! Don't know how I missed that.

**Comment by Eagle3386** [comment]
@Charles-Gagnon Last question: how am I supposed to use your fixed extension/sample from 1.12+ onwards? Because uninstalling the outdated extension, then updating to 1.12+ didn't restore the card/tile within the "Manage DB" tab?! :confused:

**Comment by Charles-Gagnon** [comment]
It should appear as a tab at the top :

![image](https://user-images.githubusercontent.com/28519865/66765409-b7d56f00-ee60-11e9-8004-b657abbac941.png)

If that's not there then you should be able to add it again by clicking the + in the top right corner of the Dashboard :

![image](https://user-images.githubusercontent.com/28519865/66765492-db98b500-ee60-11e9-997e-b7205d86f0fa.png)

**Comment by Eagle3386** [comment]
Unfortunately, it's neither available at the top:
![image](https://user-images.githubusercontent.com/5111490/66809763-4b28a600-ef2e-11e9-8407-4713f0ad69ad.png)

.. nor addable via "+":
![image](https://user-images.githubusercontent.com/5111490/66809886-81662580-ef2e-11e9-807a-0ac883f69398.png)

**Comment by Charles-Gagnon** [comment]
1. Can you include a screenshot of your extensions page to verify that it's showing the extension as installed and active?
2. If you browse to %USERPROFILE%\.azuredatastudio\extensions\microsoft.whoisactive-0.1.2 does that folder exist and contain files such as this?

![image](https://user-images.githubusercontent.com/28519865/66844185-bcfaf280-ef22-11e9-8608-c90076d9dabb.png)

3. Restart ADS then open the Developer Console (Help -> Toggle Developer Tools) - are there any errors listed in the Console tab?

**Comment by Eagle3386** [comment]
I suppose that subfolder actually didn't ever exist. 

Back then, I tried uninstalling the original extension and failed to succeed. Hence I deleted its folder to finally get rid of it.
But that folder didn't start with "Microsoft", IIRC.

**Comment by Charles-Gagnon** [comment]
Installing the extension should create the folder. If you go to the extensions viewlet in ADS and find the entry for the whoisactive extension does it have the Install button enabled?

![image](https://user-images.githubusercontent.com/28519865/66847549-698ba300-ef28-11e9-971c-4d121884a505.png)

**Comment by Eagle3386** [comment]
That worked perfectly. Thanks a lot for your help - tab and functionality are back. :grinning:
