### ISSUE TITLE
SQl2019 Troubleshooting book - hint link to notebook fails

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#6973]
Issue Type: <b>Bug</b>

Open SQL 2019 troubleshooting book, and run tsg069-azdata-bdc-gateway-status without azdata installed

Expected:
Get `HINT: Use SOP055 - Install azdata command line interface to resolve this issue` with link that opens this SOP
Actual:
- Clicking link shows error file not found.

This is likely as the book is untitled after running cells? And the relative link no longer works?
- We need to look at a solution to this longer term, for now the links are busted.

Azure Data Studio version: Azure Data Studio 1.11.0-insider (811411e8883d01dc78fb5854eea5eab076abcdb4, 2019-08-27T01:38:21.365Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.31GB free)|
|Process Argv|-psn_0_1450338|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
nbopener|kc|0.0.1
ads-language-pack-es|Mic|1.9.0
azuredatastudio-postgresql|Mic|0.2.1
sql-vnext|Mic|0.14.1

</details>

**Comment by chlafreniere** [comment]
@MaddyDev if this is fixed by the PR linked here,   is this safe to close?

**Comment by MaddyDev** [comment]
This is fixed in my PR: https://github.com/microsoft/azuredatastudio/pull/7083#event-2622955869
