### ISSUE TITLE
Status bar at the bottom of ADS is purple instead of blue

### ISSUE THREAD

**Issue by hannahqin** [microsoft/azuredatastudio#6999]
Issue Type: <b>Bug</b>

The status bar at the bottom of ADS is now purple instead of blue.

Screenshot: 
![extension-details](https://user-images.githubusercontent.com/9788775/63876357-33935f00-c97a-11e9-840e-38cdfbf856e0.png)

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-de|Mic|1.9.0
ads-language-pack-fr|Mic|1.9.0
agent|Mic|0.41.0
dacpac|Mic|0.5.0
import|Mic|0.9.0
schema-compare|Mic|0.5.0

</details>

**Comment by kburtram** [comment]
The status bar color depends on the state of the application.  For example, if there is a folder open or not, etc.  We can consider changing this behavior but this is coming from upstream in VS Code.

**Comment by kburtram** [comment]
Closing as upstream based on previous comment.  Thanks for opening this suggestion!
