### ISSUE TITLE
Feature Request: Tree view database schemas

### ISSUE THREAD

**Issue by quesog** [microsoft/azuredatastudio#7]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 10.0.15063
---

Steps to Reproduce:

1. Navigate to database > Tables
2. The databases are listed without being grouped by schemas. For a large database with many schemas, the default view would be improved by a another level in the tree grouping tables/views/etc by the schema in which they reside.

**Comment by cwstanton** [comment]
Or, if you choose not to add this as a built-in option, at least make sure it's possible for someone else to develop a plugin that can do this.  :-)

**Comment by dbauszus-glx** [comment]
+1 On this. Probably the only feature for which I need to keep my Datagrip subscription going. I have hundreds of schema with hundreds of tables on dozens of servers. Without a folder organisation it becomes impossible for me to use Azure Data Studio.

It shouldn't be too hard to implement what is already used in the [Visual Studio PostgreSQL Explorer extension](https://github.com/Microsoft/vscode-postgresql).

**Comment by spydacarnage** [comment]
Adding another +1 to this.  I use this extension in SSMS to do the same thing, if it helps?

https://github.com/nicholas-ross/SSMS-Schema-Folders

**Comment by dbauszus-glx** [comment]
@spydacarnage How do you use SQL Server Management Studio extensions with Azure Data Studio? Have you tested whether the extension works with PostgreSQL which I assume is not available in SSMS.

**Comment by spydacarnage** [comment]
@dbauszus-glx - sorry, that's not what I meant.  I was meaning that if somebody wanting to code this extension wanted to look at the other project for inspiration - I don't know how close or compatible the codebases are.  That extension also adds schema folders to Stored Procedures, etc. as well, not just tables.

I've not used PostgreSQL, unfortunately.

**Comment by 9squirrels** [comment]
Yup, this would be a great feature, especially now that PostGRES is supported in Azure Data Studio. 
Here's a screenshot of how pgAdmin handles it for PostGRES.
![pgAdmin_SchemaHandling](https://user-images.githubusercontent.com/17567283/65113135-54a11a00-da25-11e9-9917-72df464c12d6.PNG)

**Comment by spowellnet** [comment]
Plus one for this. On huge DB's such as an enterprise DWH in AzDWH (now Synapse) this is a real pain point.

**Comment by pachitorusso** [comment]
+1! Would be great to have it.

**Comment by ScottSchwalm** [comment]
Please add this.  It would be a tremendous help in better adoption.  We have hundreds of tables in many many schemas.  Scrolling through hundreds of tables is a real problem trying to find the table you want.

**Comment by dbauszus-glx** [comment]
It's not just pgadmin... Pretty much every GUI bar azuredatastudio does the schema tree...

I have seen this in OMNI. And here is a screenshot from beekeeper.

![image](https://user-images.githubusercontent.com/22201617/88279551-2e4ea980-ccdc-11ea-839d-154e3977ed8b.png)

274 tables is by no means an exception. We have databases with many more relations.

**Comment by glolsh** [comment]
+1!

**Comment by ScottSchwalm** [comment]
Seriously?  The 7th issue entered and still nothing has been done in 3 years.  This is very disappointing.

**Comment by hoeztutar** [comment]
+1 ! I am using the https://github.com/nicholas-ross/SSMS-Schema-Folders add-in for SSMS and it works great. A similar feature at ADS would make things way easier for a lot of people.

**Comment by James-Firth** [comment]
I was considering using Azure Data Studio for a project but without this database newbies on my team will have difficulty, so we'll probably have to stick with DBeaver for now.

I'd love to see this feature (especially for postgres)!

**Comment by gregveres** [comment]
Please add this feature. This is worth 100 features on notebooks! This is core functionality!

**Comment by stephajn** [comment]
Heh!  I just added a feature request and THEN thought to look to see who else would have asked for this.  So, here's another +1 for this feature. I mean really, every node should be grouped by schema.  Views, Stored Procedures, functions, etc.

**Comment by uktherebel** [comment]
It's 2022 and still nothing. Really disappointing. The schema.table view is chaotic and tacky.

**Comment by Reign-Beau** [comment]
I'm not in any position to determine why such a necessary feature has evaded development for so many years, but I can attest that it's painful. We really don't want to integrate any other IDE, but this is a required feature for big data. It sounds like we may have to make a tough decision soon. Please integrate this

**Comment by ChadTmo** [comment]
Seriously though, this is one of the features that should have been in a very early release of any product called "data studio".

**Comment by mmdojo** [comment]
One more year passed, still waiting for this very basic feature. Working with big databases is too hard with this tool. Please prioritize this

**Comment by ScottSchwalm** [comment]
@kburtram @erickangMSFT  Would either of you care to explain why this is not being worked on?

**Comment by thomas-broethaler** [comment]
+1 this is an essential structural feature, every other DB Software like DB Visualizer has by default.

**Comment by aasimkhan30** [comment]
This is fixed by https://github.com/microsoft/azuredatastudio/pull/21941

**Comment by ScottSchwalm** [comment]
When will this be released?

**Comment by aasimkhan30** [comment]
@ScottSchwalm  Should be released in insiders soon.

**Comment by erinstellato-ms** [comment]
Hi @ScottSchwalm - you should see it in the Insider build tomorrow, as @aasimkhan30 noted.  The option to view the objects organized by schema can be enabled by right-clicking on the instance and there will be the "Enable Group By Schema" option at the bottom of the popup.

@quesog @cwstanton @dbauszus-glx @spydacarnage @9squirrels @spowellnet @pachitorusso @glolsh @pmatrasc @hoeztutar @James-Firth @gregveres @lainsw @stephajn @uktherebel @Reign-Beau @ChadTmo @mmdojo @thomas-broethaler 

Thanks to those who provided constructive feedback and screenshots.  We recognize this took a while to get implemented, but hopefully you've noticed that we've been making many more investments in ADS as of late, and that will continue.  We are looking to implement filter functionality next in OE, so please stay patient.  We may not always move at the pace you all would like to see, but we are making changes.  Thanks!

**Comment by gregveres** [comment]
@erinstellato-ms 
This is a great improvement. If you are looking to make the product much less frustrating to use for a regular dba type person, then might I recommend taking a look at some of these issues, in no particular order:

- [Please improve the user experience of opening a query](https://github.com/microsoft/azuredatastudio/issues/5527)
- [option to not run query by default with Select Top 1000](https://github.com/microsoft/azuredatastudio/issues/9336)
- [query running indicator please](https://github.com/microsoft/azuredatastudio/issues/9334)
- [Rerunning query should not reset column widths](https://github.com/microsoft/azuredatastudio/issues/9333)
- [Please allow multi-row delete](https://github.com/microsoft/azuredatastudio/issues/5950)

and for bonus marks:
[FR: Follow foreign keys when viewing sql results](https://github.com/microsoft/azuredatastudio/issues/248)


Thanks for listening

**Comment by lainsw** [comment]
Hi! What is the typical wait for an Insider Build making it to General Release - specifically this schema view feature?

**Comment by erinstellato-ms** [comment]
@lainsw we expect the schema view feature to be in the next general release (so shorter time frame)

**Comment by erinstellato-ms** [comment]
> @erinstellato-ms This is a great improvement. If you are looking to make the product much less frustrating to use for a regular dba type person, then might I recommend taking a look at some of these issues, in no particular order:
> 
> * [Please improve the user experience of opening a query](https://github.com/microsoft/azuredatastudio/issues/5527)
> * [option to not run query by default with Select Top 1000](https://github.com/microsoft/azuredatastudio/issues/9336)
> * [query running indicator please](https://github.com/microsoft/azuredatastudio/issues/9334)
> * [Rerunning query should not reset column widths](https://github.com/microsoft/azuredatastudio/issues/9333)
> * [Please allow multi-row delete](https://github.com/microsoft/azuredatastudio/issues/5950)
> 
> and for bonus marks: [FR: Follow foreign keys when viewing sql results](https://github.com/microsoft/azuredatastudio/issues/248)
> 
> Thanks for listening

@gregveres Thanks for the links to the other issues that you logged.  I reviewed each one and understand the scenarios you have described.  At this time, we are focusing on a few areas including improving reliability overall, improving the connection experience, user management, and OE.  I do have a bucket of "query editor" and "result set" requests, which is where most of your items seem to land.  One thing that would help me, when we get to focusing on those areas, is understanding the value of those changes for other users.  We have been looking at votes and comments on issues to understand importance and need.  If there are others that you work with or know of that would also be interested in seeing those same changes, please encourage them to upvote the issues.  Thank you!

**Comment by gregveres** [comment]
@erinstellato-ms Thanks for the reply Erin. I mostly work alone, but I have seen other issues that were similar and some of the issues I have opened tended to be misclassified as performance or some other issue by the MS people reviewing them.

I think the issue with using the up-votes is that I see lots of duplicate requests because people often don't search for their issue before filing a new one. :( I am guilty of that some times too. For instance, I bet you find quite a few requests for the multi-row delete request. That has been around for years.

What's OE? 

The thing about these requests is that not fixing them results in a really poor user experience for the product over all. I suspect the developers are always connecting and testing against really fast, local database servers and they don't see how horrible the experience is when working with remote servers in Azure.

**Comment by erinstellato-ms** [comment]
@gregveres Thanks for the additional perspective, that's helpful.  Some of the issues that you opened were older, and it's possible that they were mis-classified at that time.  I can ask one of the engineers to review them and see if anything should be re-categorized.    Valid that duplicates get created - we have been trying to work through the backlog and consolidate, but it's a process and there are finite hours in the day.  Hopefully, however, users have seen that we are working to improve the product.  But it takes time.

OE is Object Explorer.  Can you clarify a bit what you mean when you say "remote servers in Azure"?  Do you mean Azure SQL DB, or SQL in a VM in Azure?

**Comment by gregveres** [comment]
Azure SQL DB. I think it is more that the machine is in Eastern US and I am in Southern Ontario. There is latency. It's not like the server is a super fast at the end of the hall. When I open a tab to "Select the top 1000", it often takes 5 seconds for the tab to just show up, leaving me wondering if the system accepted my menu choice or not. There's just no feedback.

**Comment by erinstellato-ms** [comment]
@gregveres ok, got it.  That's good feedback.  Let me have one of the engineers review the issues you logged and get their thoughts.  Appreciate you taking the time to share your experience, it does help us. I'll keep you posted.

**Comment by lainsw** [comment]
> @lainsw we expect the schema view feature to be in the next general release (so shorter time frame)

Thanks. When is the next general release?

**Comment by erinstellato-ms** [comment]
> > @lainsw we expect the schema view feature to be in the next general release (so shorter time frame)
> 
> Thanks. When is the next general release?

@lainsw we are targeting this month

**Comment by matthhias** [comment]
Finally! It is here:
Thanks so much. It was a real burden in bigger projects and a real handicap to convince colleagues to use Azure Data Studio.

**Comment by gregveres** [comment]
So much better! Thank you for this.
