### ISSUE TITLE
Feature request: Different widgets per server/database

### ISSUE THREAD

**Issue by SebastianPfliegel** [microsoft/azuredatastudio#70]
- SQL Operations Studio Version: 0.23.6

Currently you can only configure a global dashboard layout for all your servers and dashboard. I'd love to have different dashboard for specific servers or databases. For my work I have queries that rely on the data of this specific database to ensure the health status of a service. But those queries only apply to this database and not on others.

**Comment by robertpreseau** [comment]
I haven't poked around at all, where do the User Settings save to?

**Comment by SebastianPfliegel** [comment]
You can open the settings with Ctrl + Comma
The file path where the settings are saved depends on the operating system of course.
If I'm right it should be like this:

* **Windows** `%APPDATA%\sqlops\User\settings.json`
* **Mac** `$HOME/Library/Application Support/sqlops/User/settings.json`
* **Linux** `$HOME/.config/sqlops/User/settings.json`

**Comment by ConstantineK** [comment]
This feature would be great to allow straight forward home grown monitoring with the SOS client.

To be able to specify something like a connection string or other persisted data source and display them in their own window/tab/session would greatly enhance this feature, maybe via adding another property in the JSON describing the widget?

**Comment by anthonydresser** [comment]
This is certainly doable, the main problem would be cluttering the user settings more than they already are. We are implementing a new "tab" feature that might solve this problem.

**Comment by SebastianPfliegel** [comment]
@anthonydresser, might want to share the concept of the tab feature?

**Comment by anthonydresser** [comment]
@SebastianPfliegel theres a good screen shot on this pr #629 of the feature I am referring to. It is essentially adding a tabbing concept to the dashboard in order to support extension contribution, however it would work for what is described here I think. You could define tabs that target specific servers/databases and they would only show up when the dashboard meets those criteria. 

It's still a work in progress, there is 1 main tracking issue for this #506 but there are a few issues surrounding the issue that aren't underneath that https://github.com/Microsoft/sqlopsstudio/issues?q=is%3Aopen+is%3Aissue+label%3Adashboard

**Comment by diasmanu** [comment]
Hello everyone,

Any update on the possibility to show/hide widgets in the dashboard depending on wich server or database we are connected to? 
There is a 'when' property that exists and that is used in the tasks widget:

```
widget: {
                "tasks-widget": [
                    {
                        "name": "backup",
                        "when": "!mssql:iscloud"
                    },
                    {
                        "name": "restore",
                        "when": "!mssql:iscloud"
                    },
                    "newQuery"
                ]
            }
```

Would'nt it be possible to use this property to show or hide widgets in dashboards like :
```
"when": "databasename = SPECIFIC_DATABASE" 
```
or
``` 
"when": "servername = SPECIFIC_SERVER" 
```

**Comment by anthonydresser** [comment]
This might be possible today, I'll take a look and if it is we can add docs around this.

**Comment by diasmanu** [comment]
Thank you, that would be very helpful!

**Comment by oappelt** [comment]
I think this can be closed.
I can control the display of widgets with the "when" attribute.
Though some better documentation for the widget options would be very welcome.
I had to google and guess a lot.

**Comment by kburtram** [comment]
Closing based on previous comment to use `when` clause for this purpose.
