### ISSUE TITLE
SQLCMD mode should have setting to hide\show toolbar button

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7010]
- Azure Data Studio Version: master

The new Enable SQLCMD Mode button has a long text label and causes the toolbar to wrap to two lines more often than before.  Since many users (such as myself 😄) almost never use this feature, it would be nice to be able to remove it from the toolbar.  (it may even make sense that the default was to not show it, since I suspect most users don't use this feature).

Steps to Reproduce:

1. Open query editor

Expected: Ability to hide SQLCMD button

Actual: No such ability.  Button text is long and causes toolbar to wrap and take more vertical space. 

*Note that the toolbar now wraps, where previously it wouldn't have*
<img width="660" alt="Screen Shot 2019-08-29 at 5 34 32 PM" src="https://user-images.githubusercontent.com/599935/63985304-e3082880-ca83-11e9-8a15-37026007acd8.png">

**Comment by kenvanhyning** [comment]
For September - trim text.

**Comment by kburtram** [comment]
Moving out of September since we took a fix to shorten the button string.  We should review the desired Toolbar UX for a future release as the current approach likely won't scale well.

**Comment by kburtram** [comment]
I'll close this since we trimmed the text and no external users have requested this yet.  We can come up with a more general solution for toolbar customization in a future release.
