### ISSUE TITLE
How to change/Revert Language to English

### ISSUE THREAD

**Issue by nssidhu** [microsoft/azuredatastudio#7013]
I by Mistake got my Language changed to Language other than English.
How do I change it back to English.

Tried Re-installing, but still default to some other non-English Language,

**Comment by kburtram** [comment]
@nssidhu the language can be reset using the "Configure Display Language" command.  This can be executed from the Command Palette (which can be shown with "F1" key, for example).

In the Command Palette, typing "language", selecting "Configure Display Language", then select "en" to restore back to the English.  Please let me know if that doesn't work.

![image](https://user-images.githubusercontent.com/599935/64041710-0dee8d00-cb15-11e9-9645-67a48ee86c9b.png)

![image](https://user-images.githubusercontent.com/599935/64041743-1d6dd600-cb15-11e9-9bbc-659a862d2e59.png)

**Comment by nssidhu** [comment]
That worked
