### ISSUE TITLE
[sqlbdc]-[ads]-[Notebook] - Loading Kernels... with multiple python versions 

### ISSUE THREAD

**Issue by blakhani-msft** [microsoft/azuredatastudio#7014]
While using ADS on new machine I have been running into “Loading kernels…” after following series of steps. 

### How to Reproduce ?
I have logged in as user "balmukund" in the OS so c:\users\balmukund is my profile folder. Replace with your configuration.

1.	Fresh Windows VM
2.	_Install ADS insider - user._ https://github.com/Microsoft/azuredatastudio 
3.	Install SQL Server 2019 extension: https://docs.microsoft.com/en-us/sql/azure-data-studio/sql-server-2019-extension
4.	Use notebook but it would try to install Python. Use default settings.
5.	Python will be installed by ADS which goes to this path. C:\Users\balmukund\azuredatastudio-python
6.	Now, I need Azdata because my notebook was failing with below error

> An exception has occurred, use %tb to see the full traceback.
> 
> SystemExit: azdata not found! Please make sure azdata is installed and added to path.
> 
> c:\users\balmukund\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\interactiveshell.py:2969: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
>   warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

7.	Followed https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata?view=sqlallproducts-allversions to install it. It asked to install Python from https://www.python.org/downloads/windows/ and PATH was added (as mentioned in article)
8.	While installing  azdata, I was getting below error.

    **ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)**
9.	The way to install azdata is to add PATH for the python which was installed by ADS like below. 
In my case path was “C:\Users\balmukund\azuredatastudio-python\0.0.1\Scripts”
(My PC > Right Click> Properties)
Also, rename actual python folder which was installed later (manually)

> C:\Users\balmukund\AppData\Local\Programs\Python\Python37
> To
> C:\Users\balmukund\AppData\Local\Programs\Python\Python37_x

Run **`pip3 install -r https://aka.ms/azdata`** command below folder 

C:\Users\balmukund\azuredatastudio-python\0.0.1\Scripts
10.	azdata should install now.

11.	Now rename the Python folder back (done in # 9) 

12.	close and reopen Azure Data Studio and it should shows “Loading Kernel” while opening notebook.

### How to fix?
Based on my research it is mostly due to multiple version of Python installed on the machine.
Best way to fix this is to reset the Python used by ADS

1.	Open command Palette (View > Command Palette)
2.	In Palette windows, type Pytho and it should automatically show below.  (make sure there is a > in the beginning)
3.	Once we choose it, new windows will pop-up. 
4.	Use second radio button.
5.	Press OK and let it install the dependency. You can monitor the status in “TASKS” and “OUTPUT” windows in Azure Data Studio as shown below.
6.	Once completed, we should relaunch Azure Data Studio and Kernel should be shown as “Python 3” and other kernels in dropdown.

If needed, feel free to contact me on teams/email for more details.
-----------------------------

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (faf6eae535aa7d054731fa877f86aa66e1e25426, 2019-08-29T09:07:55.627Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (4 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|16.00GB (12.46GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.15.0

</details>

**Comment by chlafreniere** [comment]
@corivera assigning this to you as it's related to the sparkmagic dependency chain issue.

**Comment by capnsue** [comment]
I'm encountering this on pretty much a daily basis - the "reinstall all the python stuff" is really not a great workaround and only fixes it for a little while for me.

**Comment by nielsberglund** [comment]
I am sorry to say, but this is still an issue in insider 1.12.0-insider.

**Comment by corivera** [comment]
@nielsberglund What version of sparkmagic are you using? We've updated our sparkmagic dependency in notebooks to 0.12.9. We currently don't have a prompt to upgrade packages automatically, but we're working on it.

**Comment by nielsberglund** [comment]
@corivera I am now doing a "reinstall" python for notebooks, and I assume I'll get the latest of everything. After the reinstall I'll see if I still experience this issue.

**Comment by nielsberglund** [comment]
@corivera I re-installed python as per my reply 4 days ago, and since then I have not experienced the "loading kernels" issue. Looks lime it is fixed! Thanks!!
