### ISSUE TITLE
Setup has incorrect "OSS" icon on EULA page

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7016]
- Azure Data Studio Version:

Steps to Reproduce:

1. Run latest setup.exe from master branch

Actual: Incorrect icon is shown during setup

![image](https://user-images.githubusercontent.com/599935/64040958-04642580-cb13-11e9-971a-6021f0998485.png)

**Comment by aaomidi** [comment]
These two lines are new to the installer process:
https://github.com/microsoft/azuredatastudio/blob/master/build/win32/code.iss#L23-L24

Change log associated with them:

<li>Improved support for high DPI systems:
<ul>
  <li>The <tt>WizardImageFile</tt> and <tt>WizardSmallImageFile</tt> [Setup] section directives now may list multiple files. This support wildcards. When multiple files are specified, Setup will automatically select the one which best matches the system's DPI setting. See the help file for a list of recommended sizes. Note: when you test this be sure to first log out and back in after any DPI change.</li>
  <li>If the <tt>WizardImageStretch</tt> [Setup] section directive is set to <tt>yes</tt> (which it is by default) then the quality of the stretching that occurs if the best matching wizard image is still larger or smaller than required has been improved (<a href="https://i.imgur.com/BNtbQd9.png">before</a> and <a href="https://i.imgur.com/BeFyqfn.png">after</a>). Also applies to any <tt>TBitmapImage</tt> which uses stretching.</li>
</ul>
</li>


These new images are being used: https://github.com/microsoft/azuredatastudio/tree/master/resources/win32

**Comment by aaomidi** [comment]
Should we get new icons to support the new high dpi build process or just remove the new highdpi support?

**Comment by aaomidi** [comment]
I'm going to remove those new lines but keep this issue active in case we want to get new icons to support hidpi screens.

**Comment by aaomidi** [comment]
This doesn't seem to be a problem anymore

**Comment by Charles-Gagnon** [comment]
This still is the case with the latest insiders :

![image](https://user-images.githubusercontent.com/28519865/66731964-db6fc980-ee0e-11e9-9f0e-61f0a01b57b7.png)

I'm currently working on getting updated icons for Insiders editions though so I'll assign this to myself and update once I get those from UX.

**Comment by aaomidi** [comment]
Oh interesting, thanks!

**Comment by kburtram** [comment]
I'm seeing this in the release/1.13 release branch.  @Charles-Gagnon should I port down #7857 or the workaround we used in Oct to remove the icon all together?

**Comment by Charles-Gagnon** [comment]
We had a workaround? As far as I know we never did anything to get around this issue.

Do we really need this though? Are you seeing this on the stable builds? It should only happen for the insiders builds which I would assume we aren't planning on releasing out the branch.

**Comment by Charles-Gagnon** [comment]
Alright, well my suggestion would be just to port over the updated icon images since that should fix the issue without any code changes.

**Comment by aaomidi** [comment]
The workaround was to get rid of high-dpi images and just use the single icons.

https://github.com/microsoft/azuredatastudio/pull/7057

**Comment by kburtram** [comment]
Now I'm seeing that the icons in setup don't match each other.  Is this expected?

![image](https://user-images.githubusercontent.com/599935/67440237-7d30ac80-f5ad-11e9-8498-16ae7a550f43.png)

**Comment by Charles-Gagnon** [comment]
Nope, good catch. Reaching out to get fixed icons now.

**Comment by kburtram** [comment]
I've reverted the new icons in release/1.13 and ported over the icon workaround from release/1.12 (https://github.com/microsoft/azuredatastudio/commit/770e38e53ffa1e5300f4bbf19b9abd401756ba45.  We can follow-up to get the icons reviewed and approved for 1.14 release.

**Comment by kburtram** [comment]
I've reverted #7857 with https://github.com/microsoft/azuredatastudio/commit/5590d60c5ac2dc5f37d74af45cf17429f5fa461c so we can prepare a fix that doesn't update the stable icons.

**Comment by kburtram** [comment]
I'm seeing the output of the CI ad-hoc build has the default electron icon now, so I'll try to track down what happened with the revert.  Probably something related to the merge conflicts and branch drift since #7857.

**Comment by kburtram** [comment]
I think this has been fixed.  I close this issue now.
