### ISSUE TITLE
Backup dialog "button bar" has incorrect background color

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7018]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Open backup dialog

Expected: Button bar background color follows theme.

Actual: Button bar has a dark background on light theme

*Backup dialog*
![image](https://user-images.githubusercontent.com/599935/64041313-04185a00-cb14-11e9-94af-313243e6a87a.png)

*Insights dialog for reference*
![image](https://user-images.githubusercontent.com/599935/64041374-2ca05400-cb14-11e9-8602-9fdd80e140f3.png)

**Comment by udeeshagautam** [comment]
Just Fixed. https://github.com/microsoft/azuredatastudio/pull/7025. Will close after validating on next insiders

**Comment by udeeshagautam** [comment]
Validated : looks right on release branch: 
![image](https://user-images.githubusercontent.com/46980425/64283764-e892c200-cf0c-11e9-879a-82fcaea6a82a.png)
