### ISSUE TITLE
SQL Server Authentication first time connection

### ISSUE THREAD

**Issue by garethprice1977** [microsoft/azuredatastudio#7030]
Issue Type: <b>Bug</b>

When using SQL Server Authentication with a new account for the first time where in SSMS you would be promped to change your password in ADS you are told your password needs to be change and cannot log on. I have only tested this from Mac OS for this version of ADS

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 16.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2700)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.9.0
server-report|Mic|0.1.5
sql-search|Red|0.3.3

</details>

**Comment by abist** [comment]
@garethprice1977, we have this issue recorded in the thread posted above. Since it's already being tracked, I'm going to go ahead and close this one as a duplicate. Thanks for opening the issue!

**Comment by garethprice1977** [comment]
That's a windows domain password issue, the one I raised was with SQL authentication, please reopen

**Comment by abist** [comment]
@garethprice1977 This is an authentication issue in general (SQL Auth or Windows Auth) where it wouldn't refresh. If you still believe it's something else, feel free to re-open the issue.
