### ISSUE TITLE
Unattended extension installation

### ISSUE THREAD

**Issue by ghstwhl** [microsoft/azuredatastudio#7031]
**Is your feature request related to a problem? Please describe.**
In an environment where workstations are ephemeral, and users do not have administrator access, we pre-bake a workstation image using packer.  This creates a problem when a feature, such as installing Extensions for AZD, does not have an off-line installer

**Describe the solution or feature you'd like**
A command line tool, or power-shell script, that can be used to add an Extension to Azure Data Studio once it is installed on the temporary instance used by packer to create the re-usable install image.

**Describe alternatives you've considered**
Our users have tried to install the PostgreSQL Extension onto their workstations themselves, but appear unable to do so without Administrator rights.

**Additional context**

**Comment by ghstwhl** [comment]
I'd like to amend the last sentence of my first paragraph.  I ended it with "does not have an off-line installer".  I should have said "does not have a command-line installer".  ADS supports the off-line installation of extensions; but that still has to be done via the GUI, which isn't possible in the described scenario.

**Comment by Charles-Gagnon** [comment]
Does using the --install-extension option not cover your scenario?


--install-extension <ext> | Install an extension. Provide the full extension name publisher.extension as an argument. Use --force argument to avoid prompts.
-- | --

**Comment by ghstwhl** [comment]
@Charles-Gagnon - I had not encountered that in the ADS documentation or when searching for a solution.  Let me give that a try, and I'll close this if it works.

**Comment by Charles-Gagnon** [comment]
Yeah it looks like that's a gap in our documentation. You can see the available options by running 

`azuredatastudio --help` 

from a command prompt or by looking at https://code.visualstudio.com/docs/editor/command-line (we have the same ones they do + a few extras such as server & database for starting with an existing connection open)

**Comment by Charles-Gagnon** [comment]
And note that you can give the full path to a VSIX as well if you want to do a truly off-line install of an extension

**Comment by Charles-Gagnon** [comment]
I'm going to close this now since this should resolve your ask - let us know if this doesn't cover your needs completely!

**Comment by ghstwhl** [comment]
@Charles-Gagnon I've added the installation of the extension to our packer build, and it seems to complete without any errors.  But when I deploy a new instance and launch Azure Data Studio I don't see PostgreSQL as an available connection type, and then when I go to View/Extensions I see the PostgreSQL extension as available to be installed.  Seems like the command line install didn't work.

**Comment by ghstwhl** [comment]
@Charles-Gagnon I do see a message that preview features need to be enabled for extensions.  Can preview features be enabled via the command line prior to the extension install?  I don't see a command line option for that.

It does seem that having updated to 1.11.0 to make sure I'd tried everything possible that extension installation no longer requires admin privs, so even though command line install of the extension doesn't seem to work my users are now able to self service.  So I guess I've got that going for me.  :)

**Comment by Charles-Gagnon** [comment]
@ghstwhl Are you calling the exe directly? You need to invoke the cmd file instead for command-line options to work :

`"%LOCALAPPDATA%\Programs\Azure Data Studio\bin\azuredatastudio.cmd" --install-extension microsoft.azuredatastudio.postgresql`

the above worked for me just fine. 

For enabling preview features I don't believe there's a way to do that directly. But you can modify `"%APPDATA%\azuredatastudio\User\settings.json"` to set the value yourself. If this is always going to be a clean install then you can just use the attached settings.json - copying it to the above location after installing.

[settings.zip](https://github.com/microsoft/azuredatastudio/files/3636547/settings.zip)

**Comment by ghstwhl** [comment]
@Charles-Gagnon This is the powershell I use to install the extension.  It works when I run it by hand; but while it runs without error in my build system the resulting image doesn't have the extension installed.  Since the command line option to install works when I run it by hand, the problem is clearly in my build system and not with the functionality itself.  Thank you for all your help.

`Try {
    # Set Variables
    $version = '0.2.1'
    $installerBinary = "azuredatastudio-postgresql-$version-win-x64.vsix"
    $installerSource = "https://github.com/microsoft/azuredatastudio-postgresql/releases/download/v$version/$installerBinary"
    $targetPath = 'c:\temp'
    $installOptions = "--install-extension   $targetPath\$installerBinary"


    # Download executable
    Write-Output "Ensure download target exists"
    New-Item -ItemType Directory -Force -Path $targetPath
    [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.SecurityProtocolType]::Tls12
    Write-Output "Retrieving $installerSource into $targetPath\$installerBinary"
    Invoke-WebRequest -Uri "$installerSource" -OutFile "$targetPath\$installerBinary"

    # Run installer
    Write-Output "Installing $targetPath\$installerBinary"
    Start-Process -NoNewWindow -FilePath "C:\Program Files\Azure Data Studio\bin\azuredatastudio.cmd" -ArgumentList "$installOptions" -Wait -PassThru
}

Catch {
    # If error, output and exit with a status of 1
    Write-Output $_
    [System.Environment]::Exit(1)
}
`
