### ISSUE TITLE
Azure Government sign-in

### ISSUE THREAD

**Issue by avbhaskar** [microsoft/azuredatastudio#7034]
**Problem**
Unable to connect to SQL Azure databases hosted in specialty clouds (ex: _AzureUSGovernment_)

**Feature to pick specialty clouds at add account pane**
Provide an option to pick Azure specialty cloud on "sign into Azure->Add Account"  pane. It only Allows Azure commercial default Page : https://microsoft.com/devicelogin. It wont work for Specialty cloud Sign-ins

**Alternatives considered**
SSMS provides an option to choose Azure cloud. Switching back forth is time consuming and requires multiple restarts

**Additional context**
This would be huge for developers at government agencies who work in Azure commercial and specialty clouds concurrently. Multiple Directory sign-ins are already a pain.

**Comment by kburtram** [comment]
@avbhaskar thanks for reporting this issue.  We are tracking this work in https://github.com/microsoft/azuredatastudio/issues/3013.  We plan to enable either in Oct. or Nov. release.
