### ISSUE TITLE
SSMSMin Error Opening Object Properties when SSMS Not Installed

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7036]
Expanded OE so that I could see the columns for a database and chose Properties.

SSMS is not on my machine, and was met with an error:

Error calling SsmsMin with args '-a "sqla:Properties@Microsoft.SqlServer.Management.Smo.Column............."' - The system cannot find the path specified.

And yes, I removed the rest of the args 😄 

Seems to me like we should be hiding the Properties here (or, at the very least, failing with a user-readable message).

**Comment by Charles-Gagnon** [comment]
This was insiders builds I assume? In that case that's a known issue - #6276. 

SSMSMin is separate from SSMS and so doesn't require SSMS being installed (we download SSMSMin as a separate package when the extension is installed). So you shouldn't see this on a stable build of ADS.
