### ISSUE TITLE
Results tab is incorrectly ordered

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7039]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Run a query

Expected: Results tab then Messages tab

Actual: Messages tab then Results tab

![image](https://user-images.githubusercontent.com/599935/64215989-dc0a5d00-ce6b-11e9-847d-e58c7bc34052.png)

**Comment by kburtram** [comment]
This PR https://github.com/microsoft/azuredatastudio/pull/7035 is supposed to fix this bug.  I'll confirm once a new build is available.

**Comment by aaomidi** [comment]
This is fixed @kburtram 

![image](https://user-images.githubusercontent.com/1465785/64299262-58b14000-cf2d-11e9-9b02-a7c13c8ec529.png)

**Comment by kburtram** [comment]
@aaomidi thanks for confirming!
