### ISSUE TITLE
Import Wizard Context Menu

### ISSUE THREAD

**Issue by wimmerb72** [microsoft/azuredatastudio#7043]
Issue Type: <b>Bug</b>

Install SQL Import Wizard
Right Click the Database Name
Import Wizard Menu Item should appear - it does not

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2643 v2 @ 3.50GHz (4 x 3500)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|16.00GB (11.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kenvanhyning** [comment]
Tested and no-repro on RC build of September release.
