### ISSUE TITLE
Feature Request: SQL Notebook Output Toolbar

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7045]
In SQL Notebook, each code cell output for a SQL code cell will have some type of results grid. Above each grid, we would like to have the **Save As** options in addition to future charting support.

**Comment by MsSQLGirl** [comment]
I think this is fixed now :)
![image](https://user-images.githubusercontent.com/6405919/85053958-2dac7b80-b150-11ea-92bf-7eccfd48cac1.png)

@yualan - can you please confirm?
