### ISSUE TITLE
Feature Request: Jupyter Book viewlet separation and features

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7046]
Jupyter Books are a collection of notebooks organized in a yml file.

Request #1: Add separate Jupyter Book viewlet to left bar to view only Jupyter Books

Request #2: Add workspace dividers to clearly show Jupyter Books from SQL Server team, custom Jupyter Books, and more.

**Comment by MaddyDev** [comment]
Separate books view-let with Saved and Unsaved sections (launching the books exposed inside ADS). This had been done and checked into masters (available in insiders for now).
