### ISSUE TITLE
After cancel on the add IP dialog the server is forever in loading mode

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#7052]
- Azure Data Studio Version:

Steps to Reproduce:

1. Connect to Azure Account
2. Double click a Sql Server in a Subscription which opens the add IP dialog
3. Hit Cancel on the dialog
4. The SqlServer remains in loading mode for the whole session (even refreshing the tree doesn't remove loading icon)

![image](https://user-images.githubusercontent.com/46980425/64287054-8ee1c600-cf13-11e9-88a1-89b841dd498e.png)

**Comment by aaomidi** [comment]
Not happening anymore
