### ISSUE TITLE
Jupyter Book Viewlet Should Not Show Up in Stable Builds

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7054]
Jupyter book viewlet should not be in stable builds yet.

**Comment by kburtram** [comment]
The viewlet icon is now gone in the stable builds.  Though there is still a Command Palette entry to show the viewlet, which doesn't do anything.  I assume that would be a September blocking issue?

![image](https://user-images.githubusercontent.com/599935/64370276-fad73380-cfd2-11e9-933c-a3269aa86177.png)

**Comment by MaddyDev** [comment]
Let me take a look.

**Comment by kburtram** [comment]
@MaddyDev sorry in my above comment "I assume that ~would~ be a September blocking issue?", this should read "I assume that **wouldn't** be a September blocking issue?".  (*Funny how a small typo completely changes the meaning.* 😄)

**Comment by MaddyDev** [comment]
@kburtram :) Yep, that wouldn't be a September blocker! Am working on a fix anyway.
