### ISSUE TITLE
Import Flat File Wizard Keyword not supported 'u:!skjl3qvfwbdwc'

### ISSUE THREAD

**Issue by sdings** [microsoft/azuredatastudio#7058]
- Azure Data Studio Version: 1.10.0

When attempting to upload any file using Azure Database Import Flat File Wizard, the wizard fails and produces

> X Keyword not supported 'u:!skjl3qvfwbdwc'"

I have tried restarting my laptop, reinstalling the SQL Server Import, and trying different files and databases. 

The file is a CSV (have tried a UTF-8 csv) and is located on my desktop.

**Comment by kburtram** [comment]
@kenvanhyning @aaomidi have you send this error before?

**Comment by aaomidi** [comment]
If this file isn't private or confidential/contains personal information I'd love to be able to repro it.

Can you take a screenshot of the error? Would like to see where this shows up.

**Comment by sdings** [comment]
> 
> 
> If this file isn't private or confidential/contains personal information I'd love to be able to repro it.
> 
> Can you take a screenshot of the error? Would like to see where this shows up.

**Comment by sdings** [comment]
Hi @aaomidi unfortunately i cannot share the file, but i created this CSV using tableau prep. The error happened again when i tried another CSV that i manipulated in tableau prep. 

I have also used excel to save as a CSV (tableau prep creates a UTF-8 CSV) to no avail.

**Comment by sdings** [comment]
@aaomidi 
![screenshot](https://user-images.githubusercontent.com/46386066/64355167-bba6e380-cfce-11e9-9adf-d2b2d0d85987.png)

**Comment by aaomidi** [comment]
Thanks!

**Comment by sdings** [comment]
@aaomidi i tried the file using the SQL Server Import and Export wizard in SSMS and had no issues uploading one of the files that did not work in Azure data studio.

**Comment by aaomidi** [comment]
@sdings I've updated the import extension where you should be getting more error messages. These changes will be included in future insiders builds (24-48 from this comment). Hopefully that will give you more context on whats breaking.
