### ISSUE TITLE
Azure Viewlet asks for databases level AAD connection details for every operation on databse

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#7060]
- Azure Data Studio Version:
Version: 1.11.0 (user setup)
Commit: acc85c2c23f4889b4ae9373282d92daec321b1bd
Date: 2019-09-03T23:55:40.484Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Connect to an Azure Account.
2. In Azure viewlet expand to a sever you have access for 
3. Expand till databases and right click --> Manage on a database
4. Asks for credentials 
5. Select AAD cred and connect --> Dashboard opens successfully
3. Right click and manage again on the same database immediately
5. Asks for creds again .. and every time you repeat the operation 
This happens for all operations like Manage/ New Query
There is not way to save this explicitly on the connection dialog since this is AAD connection

**Comment by kevcunnane** [comment]
@abist is this fixed? If not can we move out to Planning as I don't think it'll meet ASK mode bar?

**Comment by abist** [comment]
@kevcunnane I wasn't able to repro this consistently. We can move it to planning for now.

**Comment by cheenamalhotra** [comment]
Closing as issue doesn't exist anymore.
