### ISSUE TITLE
Opening new notebook is opening it in master context always

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#7061]
- Azure Data Studio Version:
Version: 1.11.0 (user setup)
Commit: acc85c2c23f4889b4ae9373282d92daec321b1bd
Date: 2019-09-03T23:55:40.484Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Connect to an Azure account 
2. In Azure Viewlet right click a server an open Manage i.e. Dashboard
3. Select new notebook --> opens in master context as expected
4. From dashboard navigate to a database dashboard
5. Select new notebook --> Still opens in master context

I am not sure if this is really the issue or by product of this issue : https://github.com/microsoft/azuredatastudio/issues/7060

Feel free to close if this looks related

**Comment by kevcunnane** [comment]
@chlafreniere is this fixed? If not, can we move out to Planning?

**Comment by chlafreniere** [comment]
@kevcunnane no, not fixed. It also affects OE as well. Not a regression from October, though 😞

**Comment by chlafreniere** [comment]
Merged into release branch.
