### ISSUE TITLE
Schema compare dialog doesn't remember context if opened from Azure Viewlet

### ISSUE THREAD

**Issue by udeeshagautam** [microsoft/azuredatastudio#7070]
- Azure Data Studio Version:
Version: 1.11.0 (user setup)
Commit: acc85c2c23f4889b4ae9373282d92daec321b1bd
Date: 2019-09-03T23:55:40.484Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. connect to Azure ccount 
2. expand Azure view let Server--> Databse 
3. start a schema compare from DB context menu (this asks for cred - give AAD creds)
4. the main page looks in right context
5. open source/target selection dilaog to select target
6. you would notice that source is not correct (it is some local connection in above viewlet)
![image](https://user-images.githubusercontent.com/46980425/64304037-b484c480-cf3f-11e9-97fa-dad5890a6db4.png)

Note that this will happen only initially if you have no connection to azure in servers viewlet... making Azure connection from servers view let once fixes the bahavior even for Azure viewlet.

**Comment by udeeshagautam** [comment]
Will take a first look from SC perspective to see if it can be solved from SC

**Comment by cheenamalhotra** [comment]
I believe this should be fixed by now, @SakshiS-harma can you please take a look?
Thanks!

**Comment by SakshiS-harma** [comment]
> I believe this should be fixed by now, @SakshiS-harma can you please take a look? Thanks!

Hey Cheena, as of now this hasn't been fixed. Let me know if there is a customer requirement, and we can prioritize it accordingly.
Thanks!

**Comment by kisantia** [comment]
closing due to lack of additional interest. Can reopen later if there are more requests
