### ISSUE TITLE
Feature Request: Setup Prometheus for TSG's

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7072]
Prometheus is a monitoring and learning platform on Kubernetes. The goal is that a set of notebooks will be configured as Promtheus monitors, which will always check if the clusters are working. If a notebook fails, there will be a hint to make the cluster work.

**Comment by Charles-Gagnon** [comment]
@yualan I'm closing this unless we think this is something we're actually going to be implementing
