### ISSUE TITLE
update node.js

### ISSUE THREAD

**Issue by Jagoop** [Microsoft/azuredatastudio#708]
- SQL Operations Studio Version: 0.25.4

Steps to Reproduce:

SqlOS includes node.js version 7.9.0.0, newest version is 9.5.0

node.js should be updated

**Comment by kburtram** [comment]
@Jagoop we get our Node version as a byproduct of using the VS Code build dependencies, so our version matches their current shipping version.  I think the node DLL is coming from the Electron dependency, so we'll likely need to wait for upstream to update their dependencies to get a newer node.js DLL.

**Comment by kburtram** [comment]
The current node.dll file version is `8.9.3`.  As noted the file is picked up from an upstream dependency which don't control so we may not be on the latest at any particular time.
