### ISSUE TITLE
Context menu in Azure Explorer is incorrect

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7082]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Connect to a database in Azure Explorer
2. Right-click on a table

Expected: Context menus consistent with context menus in Servers view.

Actual: The context menu ordering is different and there are nodes that don't make sense (e.g. Disconnect and Properties don't do anything in this context).

![image](https://user-images.githubusercontent.com/599935/64370061-83a19f80-cfd2-11e9-8260-4fce187d0931.png)

**Comment by kburtram** [comment]
@kenvanhyning please validate if this has ben fixed.

**Comment by kenvanhyning** [comment]
verified that the RCM is the same for table via the Azure Explorer and OE in Insiders 10/24.
