### ISSUE TITLE
Update an Existing Connection

### ISSUE THREAD

**Issue by westandy-dcp** [microsoft/azuredatastudio#7092]
How hard would it be to allow the ability to update an existing connection.  Like add SSL to an existing connection?  "Manage Connection" just opens a working window.  I would like it to open the original "Create Connection" dialog and allow you to edit the existing connection.

**Comment by Charles-Gagnon** [comment]
Thanks for the suggestion @westandy-dcp! This appears to be a duplicate of https://github.com/microsoft/azuredatastudio/issues/5158 though so I'll be closing this one. Please follow that for any updates on the request!
