### ISSUE TITLE
Dacpac extraction not working

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7098]
Issue Type: <b>Bug</b>

When I go through the Data Tier Application Wizard against my SQL 2017 instance, it is not extracting anything.

No visible errors, it just exits the wizard and does nothing.

There are however errors in the console log:

c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] rejected promise not handled within 1 second: TypeError: Cannot read property 'extractDacpac' of undefined (at protocol.onMessage.process.on.promise.catch.e (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55163:41))
console.(anonymous function) @ c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
16:36:56.402 c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] stack trace: TypeError: Cannot read property 'extractDacpac' of undefined	at DataTierApplicationWizard.extract (c:\Users\viharp\.azuredatastudio-insiders\extensions\microsoft.dacpac-0.5.0\out\wizard\dataTierApplicationWizard.js:226:38) (at protocol.onMessage.process.on.promise.catch.e (c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:55165:45))
console.(anonymous function) @ c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
16:36:56.403 c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [[object Object]]Cannot read property 'extractDacpac' of undefined
console.(anonymous function) @ c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280
16:36:56.403 c:\Users\viharp\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 TypeError: Cannot read property 'extractDacpac' of undefined
	at DataTierApplicationWizard.extract (c:\Users\viharp\.azuredatastudio-insiders\extensions\microsoft.dacpac-0.5.0\out\wizard\dataTierApplicationWizard.js:226:38)

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (b8518f5795ce15a5a524cbc0f9e531b8e02d8456, 2019-09-04T09:15:54.332Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (2.42GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.41.0
azuredatastudio-mysql|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.1
big-data-cluster|Mic|0.0.1
cms|Mic|0.4.0
dacpac|Mic|0.5.0
import|Mic|0.9.0
profiler|Mic|0.9.0
schema-compare|Mic|0.6.0
sql-vnext|Mic|0.14.1
azdata-sanddance|msr|1.3.3

</details>

**Comment by kisantia** [comment]
Fixed after extension version got bumped
