### ISSUE TITLE
alias support

### ISSUE THREAD

**Issue by DGuidi** [microsoft/azuredatastudio#71]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce: 
1. configure an alias for a sql server isntance
1. try to login to a server using alias name instead of server name

**Comment by EnjoyinMoss** [comment]
This feature would attract a lot of DBA's who look after large multi-domain SQL estates, myself one of them.  Ideally, and I will search for this after I write it, it would be nice to see compatibility with Central Management Servers and or at the very least - accept import of ".regsvr" registered servers files.

**Comment by adnans** [comment]
Started dealing with this issue yesterday.  Can connect to a local named instance, but remote named instances that have aliases set up in SQL Configuration Manager locally won't connect.

**Comment by thesobercoder** [comment]
Hope this gets resolved soon.

**Comment by cheenamalhotra** [comment]
SQL Server Alias support is now available in Windows with the insiders and [1.40.1-rc1](https://github.com/microsoft/azuredatastudio/issues/21131) builds, would request feedback from anyone waiting for this support.

Unix support is not yet available as the feature works with Windows Registry at the moment. 
Cross platform support is in design phase in the underlying driver.

**Comment by cheenamalhotra** [comment]
_Gentle ping..._

This feature is now available in [**Azure Data Studio v1.40**](https://aka.ms/getazuredatastudio) on Windows.

**Comment by lennybacon** [comment]
Thank you

**Comment by cheenamalhotra** [comment]
Closing this as now supported on Windows.
