### ISSUE TITLE
Warn before deleting connection

### ISSUE THREAD

**Issue by Code-DJ** [microsoft/azuredatastudio#711]
- SQL Operations Studio Version: 0.26.4

Steps to Reproduce:
Under Servers, right click on any server, you have Manage, New Query, Delete Connection, Refresh.
If you accidentally click Delete Connection instead of New Query, the connection is gone without a warning.

Can a warning be added "Are you sure you want to delete this connection?" or can the Delete Connection be moved all the way to the bottom with a separator in between?

Only reason for creating this issue is I have been bit by it a couple of times.

**Comment by kburtram** [comment]
This has been implemented in the current release.
