### ISSUE TITLE
SQL Import - hangs when trying to select database if destination is Azure SQL

### ISSUE THREAD

**Issue by jonescameron** [microsoft/azuredatastudio#7115]
- Azure Data Studio Version: 1.10.0

Steps to Reproduce:

1. Install SQL Import extension
2. Hit Ctrl + I to bring up wizard
3. Select a server that is an Azure SQL server (eg xyz.database.windows.net)
4. You'll be unable to select a database, there is just a progress wheel that goes around forever (see attached)
![issue](https://user-images.githubusercontent.com/22148905/64539858-26ca2000-d317-11e9-834a-cf5e2ef061e7.png)

**Comment by aasimkhan30** [comment]
This issue was fixed with PR #10216
