### ISSUE TITLE
Results and Message dissapears

### ISSUE THREAD

**Issue by martinezpedro** [microsoft/azuredatastudio#7118]
Results and Message disappears after saving the saving the sql query: 1. run a long query 2. save 3. results and message disappears leaving you to mistaken actions like re executing the query, not knowing what is happening in the background.

**Comment by Charles-Gagnon** [comment]
Thanks for the report @martinezpedro - this is a duplicate of https://github.com/microsoft/azuredatastudio/issues/5155 so I'm going to be closing this one. Pleaes follow that for any updates on the issue!
