### ISSUE TITLE
The HDFS file system in the object explorer for a big data cluster should be at the top level of the server

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#7144]
Issue Type: <b>Bug</b>

I think this is a relic of some original design thinking.  Right now HDFS is not immediately discoverable when you connect to a BDC because it is inside of the abstractly named 'Data Services' folder.  Especially since that is the only "data service" under the 'Data Service' folder and we dont have any plans to put any other "data service" under there that I know of, we should move HDFS up a level so that it is a peer of Databases and will therefore be more discoverable.

Azure Data Studio version: azuredatastudio-insiders 1.11.0-insider (b8518f5795ce15a5a524cbc0f9e531b8e02d8456, 2019-09-04T09:15:54.332Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kevcunnane** [comment]
@twright-msft We should quickly sync to verify there won't be any further services we want to list for 2019 at any stage (even post RTM). I'm happy to take this change just want to verify strategy.
