### ISSUE TITLE
Hangs every few minutes on a query execution

### ISSUE THREAD

**Issue by alexeystrakh** [microsoft/azuredatastudio#7145]
Issue Type: <b>Bug</b>

Works fine for a single query execution but hangs every few minutes if you execute a bunch of queries. As if every 10th execution it tries to reconnect or so. It happens since the very beggining the studio was created and I'm waiting for this bug to be fixed since then. 

Please fix!

Azure Data Studio version: Azure Data Studio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:12:56.165Z)
OS version: Darwin x64 18.7.0

**Comment by cheenamalhotra** [comment]
Hi @alexeystrakh 

This issue has been addressed in the [latest insiders build](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main-branch), please let us know if you experience it again.
Closing as resolved.
