### ISSUE TITLE
Uninstall of Azure Data Studio (User) requires Admin permissions

### ISSUE THREAD

**Issue by golaat** [microsoft/azuredatastudio#7148]
The uninstall of Azure Data Studio (User) via Windows 10 Apps & Features requires administrative access. I was however able to successfully uninstall via the following command:
"C:\Users\golaat\AppData\Local\Programs\Azure Data Studio\unins000.exe" /SILENT

- Azure Data Studio Version: 1.11

Steps to Reproduce:
1. Install Azure Data Studio (User) using an account without Administrative access to the computer on a Windows 10 machine.
2. After installation, go to the Apps & Features App and attempt to uninstall the product.

**Comment by kburtram** [comment]
I wasn't able to repro this with the current release.  Please let us know if you are still impacted by this issue.
