### ISSUE TITLE
Wrong imports being used

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7149]
Something from 'browser' is using this file, which then tries to get import('fs'). This isn't allowed.

Getting rid of 'fs', or splitting the functionality to two files would work here.

https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/parts/notebook/electron-browser/outputs/notebookMarkdown.ts#L6

**Comment by aaomidi** [comment]
Another one: https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/api/browser/mainThreadNotebookDocumentsAndEditors.ts#L19

**Comment by MaddyDev** [comment]
@aaomidi/@anthonydresser which library should I use intsead?

**Comment by anthonydresser** [comment]
IFileService

**Comment by anthonydresser** [comment]
https://github.com/Microsoft/azuredatastudio/blob/master/src/vs/platform/files/common/files.ts#L19

**Comment by MaddyDev** [comment]
@anthonydresser  IFileService accepts a URI and doesn't accept string reference paths. We have a several scenarios where we pass in a relative path (../xyz) to check if the path exists. And the IFileService exists function only accepts Uri and bombs when passed in a relative path. Do you know of any alternative to this?

**Comment by Charles-Gagnon** [comment]
[URI.file](https://github.com/microsoft/azuredatastudio/blob/0b7e7ddbf96bf76e2acc774ae560a06de064b4f5/src/vs/base/common/uri.ts#L318)

https://github.com/microsoft/azuredatastudio/blob/b2b28409904854ba94cb15698bb32c0399f5978f/src/sql/workbench/services/insights/common/insightsUtils.ts#L39
