### ISSUE TITLE
Central Management Servers plugin - extensionApi.getCmsServiceProvider is not a function

### ISSUE THREAD

**Issue by adnans** [microsoft/azuredatastudio#7152]
Azure Data Studio Version: Version: 1.11.0 (user setup)
Commit: 460c739a8d90bdbbde39e01abfb8ecdc278ea787
Date: 2019-09-06T18:08:50.974Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Attempt to open a CMS server

Central Management Servers 0.4.0.  When trying to open a CMS server to list available servers, the error message "extensionApi.getCmsServiceProvider is not a function" pops up and nothing else happens (no servers/etc displayed).

**Comment by kburtram** [comment]
@adnans could you please try updating the CMS 0.5.0 version of the extension?

@abist do you have any context this error?

**Comment by abist** [comment]
@kburtram I know there was refactoring in mssql which affected CMS, Schema Compare, DacFx etc. I'll look into this

**Comment by adnans** [comment]
@kburtram No updates showing itself as available in ADS, stuck at 0.4.0.

**Comment by adnans** [comment]
Pulled 0.5.0 out of the Github repo and added it to %userprofile%\.azuredatastudio\extensions\, 0.5.0 shows as installed.  Existing CMS list is gone, trying to re-add gives error "command 'cms.resource.registerCmsServer' not found.

**Comment by kburtram** [comment]
@adnans could you please try deleting the CMS extensions from the user directory and installing the VSIX using the `Install VSIX from Package` command in the file menu?  To confirm, are you trying to install this version of the extension https://sqlopsextensions.blob.core.windows.net/extensions/cms/cms-0.5.0.vsix?

Also, does everything appear to work as expected?  The extension manager should have updated to show the 0.5.0 extension earlier today.

@abist any ideas about the missing CMS command?

**Comment by abist** [comment]
@kburtram I'll have to repro this. I suspect a cached version in the users directory as well.

**Comment by adnans** [comment]
0.5.0 downloaded normally this morning (I had re-installed 0.4.0 last night before leaving for the day), and the plugin is behaving as expected now.  Thanks for the help, whatever the case.

**Comment by kburtram** [comment]
@adnans thanks for confirming that this is working now.  I'll keep an eye out for other related issues.  Perhaps our cached state is getting corrupted for some reason in some cases.
