### ISSUE TITLE
Schema Compare exclude doesn't always exclude the object

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#7157]
If an object is depended on by another object, the change will still be included even if it's unchecked as long as the dependency change is included. 

Current ADS behavior: Even though the two tables are unchecked, they are included in the generated script because the view depends on them
![image](https://user-images.githubusercontent.com/31145923/64657499-9b20c400-d3e8-11e9-8b61-6b4774052b82.png)

In these cases, SSDT doesn't allow an object to be unchecked if there is an included dependency 
![image](https://user-images.githubusercontent.com/31145923/64657480-80e6e600-d3e8-11e9-97a9-d273c96ec164.png)

**Comment by udeeshagautam** [comment]
to be fixed by https://github.com/microsoft/azuredatastudio/pull/8042
