### ISSUE TITLE
Add "New Query" for server group in Central Management Servers extension

### ISSUE THREAD

**Issue by blakemcneill** [microsoft/azuredatastudio#7167]
**Describe the solution or feature you'd like**
Please add "New Query" to the Central Management Servers extension. My coworkers and I use this feature often to query multiple servers at the same time.

**Describe alternatives you've considered**
Currently use SSMS for this feature.

**Comment by Charles-Gagnon** [comment]
Thanks for the suggestion @blakemcneill - this is currently being tracked with #28 so I'll be closing this. Follow that for any updates!
