### ISSUE TITLE
Count insight needs to support vertical data mode

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#719]
- SQL Operations Studio Version:

Steps to Reproduce:
- Run most any query that returns 2 column-result (label in Col 0, data in col 1)
- Try to use to represent a Count insight. This should be easy

Result:
- Only 1st row "works" as data is treated as horizontal. We really, really need a vertical layout. Horizontal only works when you can control the column info

**Comment by kburtram** [comment]
Closing old tasks.
