### ISSUE TITLE
SQL on Windows Deployment 

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#7192]
Clicking on the "SQL on Windows" card from the Deployment dialog Downloads the setup.exe but doesnt launch it.

It appears that for some users the setup launches and doesnt for some.
(1) The setup.exe currently downloads into user folder. It should go into downloads folder.
(2) We need a message in the Tasks tab, and a notification to let the user know that the download has finished and user can launch it .. 

"SQL Server XXXX setup has been downloaded and can be launched from c:\...\ folder."

**Comment by alanrenmsft** [comment]
1. move to the user's downloads folder
1. use sudo process start

**Comment by dnethi** [comment]
Thanks for taking care of this Alan.


Thanks,
Dinakar
