### ISSUE TITLE
Intellisense not working on new installation

### ISSUE THREAD

**Issue by Bokaii** [microsoft/azuredatastudio#7196]
Issue Type: <b>Bug</b>

New fresh installation of latest 1.11.0 ADS, but can never get the app to recognize any objects or recommend any tables when writing querys for example. I can browse and run querys just fine, but all objects are underlined red and show "Invalid object name" in the tooltip.

I have tried refreshing the Intellisence cache through the Command Palette, and connecting/disconnecting, but it makes no difference.

The server I am connecting to is an Azure DB.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.81GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

![image](https://user-images.githubusercontent.com/10463748/64848990-bb33cb80-d612-11e9-826e-921c41df0347.png)

**Comment by Bokaii** [comment]
Sorry if this is similar to #7161, please move/close if it is.

**Comment by Charles-Gagnon** [comment]
If you revert to 1.10 and/or try the custom versions of ADS that Karl made does that resolve the issue? There's known performance issues against Azure DBs so your case might just be one of that instead. 

Windows: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-windows-intellisense-bug.zip
macOS: https://azuredatastudiobuilds.blob.core.windows.net/test/azuredatastudio-macos-intellisense-bug.zip

I'll close this as a dupe for now - but let us know in the other thread if you have the same symptoms as the others have.

**Comment by Bokaii** [comment]
Hi, yes reverting to 1.10 solved it!

/Jakob

**Comment by Bokaii** [comment]
Until a forced update installed 1.11 without asking if I wanted it installed. Can I disable the auto update part somehow?

**Comment by Charles-Gagnon** [comment]
@Bokaii Open the settings pane (command palette -> Preferences: Open Settings UI) and then search for the **Update: Mode** setting. Choose either **None** or **Manual** to disable automatic updates.

![image](https://user-images.githubusercontent.com/28519865/64972437-26251280-d85e-11e9-8168-0cdae756a048.png)
