### ISSUE TITLE
The "Replace" menu is not completely hidden

### ISSUE THREAD

**Issue by konpl** [microsoft/azuredatastudio#7199]
The "Replace" menu is not completely hidden if the replacement text contains many lines.
Steps to Reproduce:
1. Open some sql file;
2. Copy text with 5 or more lines;
3. Ctrl+H;
4. Paste copied text to "Replace" textbox ("Find" text box must bee empty);
5. Close "Replace" menu or hit "Escape";
6. There's still part of the menu.
![изображение](https://user-images.githubusercontent.com/48159828/64890569-a558f180-d678-11e9-8c08-9e6717683f46.png)

Info:
Version: 1.11.0 (system setup)
Commit: 460c739a8d90bdbbde39e01abfb8ecdc278ea787
Date: 2019-09-06T18:08:50.974Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by anthonydresser** [comment]
This is most likley upstream, can you repro in a non-sql editor? (file -> new file)

**Comment by konpl** [comment]
Yes. The same situation with plain text and other formats.

**Comment by anthonydresser** [comment]
If you have vscode installrd, can you see if it repros in vscode?

**Comment by konpl** [comment]
Sorry, can't try in vscode

**Comment by kburtram** [comment]
This no longer repros on the current build as far as I can tell.  Please let us know if you're still impacted by this.
