### ISSUE TITLE
Books: When preview markdown file is open, cannot launch command palette

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#7209]
Steps to Reproduce:

1. Launch the troubleshooting guide book that opens up the preview markdown file (or any markdown file from the books in the view-let)
2. Try to open command pallet.

Expected behavior: Opens up command pallet.
Bug: command pallet flickers and disappears.

**Comment by chlafreniere** [comment]
This can be mitigated by opening the command palette through the shortcut keys. I know. Super weird.

**Comment by chlafreniere** [comment]
This no longer reproes. Likely was fixed on the vscode side.
