### ISSUE TITLE
Open SQL file, automatic prompt box does not have the corresponding information prompt of the database

### ISSUE THREAD

**Issue by joezjy** [microsoft/azuredatastudio#7214]
Issue Type: <b>Bug</b>

1，打开AZURE，连接上服务器
2，打开硬盘的SQL文件，输入内容，提示框里没有数据库的表、字段等信息提示。
3，新建查询窗口，输入内容时能正常提示以上信息

Azure Data Studio version: Azure Data Studio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:14:33.682Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2713)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|16.00GB (8.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hans|Mic|1.9.0

</details>

**Comment by abist** [comment]
From online translation,

1. Open AZURE, connect to the server
2. Open the SQL file of the hard disk, enter the content, there is no database table, field and other information prompts in the prompt box.
3. Create a new query window, the above information can be prompted normally when inputting content

**Comment by Charles-Gagnon** [comment]
@joezjy Could you include a screenshot showing what the problem is?

**Comment by joezjy** [comment]
> @joezjy Could you include a screenshot showing what the problem is?

@Charles-Gagnon 
1, open saved sql file,IntelliSense is broke
![屏幕快照 2019-09-17 上午7 53 43](https://user-images.githubusercontent.com/22520014/65001003-69e05080-d920-11e9-9a42-2e3cf783ed54.png)

2,new query windows,IntelliSense is correct
![屏幕快照 2019-09-17 上午7 45 48](https://user-images.githubusercontent.com/22520014/65001221-42d64e80-d921-11e9-9c24-9c4e1562a31e.png)

**Comment by Charles-Gagnon** [comment]
We're currently tracking this issue here : https://github.com/microsoft/azuredatastudio/issues/7161 Please follow that for any updates!
