### ISSUE TITLE
Create external tabel - sort order source tables/views alphabetical

### ISSUE THREAD

**Issue by hkroese** [microsoft/azuredatastudio#7218]
Issue Type: <b>Feature Request</b>

Please order the source tables in the selection window 'Create external table'-step 4 alphabetical or give us a filter functionality. Selection from large databases is difficult.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.18362

**Comment by corivera** [comment]
Fixed
