### ISSUE TITLE
Query Editor Does Not Adjust When Resolution Changes

### ISSUE THREAD

**Issue by rharris-ameresco** [microsoft/azuredatastudio#7219]
Issue Type: <b>Bug</b>

Hello,

I use Azure Data Studio for work and have to dock/undock my laptop throughout the day. When doing this, the resolution of the screen changes from the native resolution used on the built-in display to a resolution that has been set for external monitors. Each time my system changes resolution, the query editor no longer horizontally aligns with the text that is present or new text that is typed.

The only method of fixing this issue is for me to close Azure Data Studio each time I change resolutions and re-open it.

**Bug Present:**
This image shows what it looks like when the cursor is all the way to the right of the typed text and I double-click to highlight the table name.
![image](https://user-images.githubusercontent.com/51416059/64973064-fa128d00-d86f-11e9-80e0-65f774188b65.png)

**Restarted App:**
This image shows what the same selection above looks like after a restart of the app.
![image](https://user-images.githubusercontent.com/51416059/64973216-3c3bce80-d870-11e9-93fe-16eb68847db9.png)

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (5.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.42.0
import|Mic|0.10.0
profiler|Mic|0.9.0

</details>

**Comment by anthonydresser** [comment]
Can you open a non-query editor (file -> new file) and see if you can repro?

**Comment by rharris-ameresco** [comment]
> Can you open a non-query editor (file -> new file) and see if you can repro?

Hi,

Yes, opening a new query file as requested also contains the bug/issue if the display resolution was previously changed without a restart of Azure Data Studio directly afterwards.

**Comment by kburtram** [comment]
Closing older issues.  We've made numerous shell improvements, such as upgrading Electron, which may have helped with this scenario.  Please let us know if you're still impacted by this issue.
