### ISSUE TITLE
MSSQL Auto Complete Doesn't Work In Saved .sql Files

### ISSUE THREAD

**Issue by ideoclickVanessa** [microsoft/azuredatastudio#7221]
Issue Type: <b>Bug</b>

Create a new database script and save the file with the .sql extension.
Close file and reopen it.
The MSSQL Auto Complete (tables, fields, etc) no longer works.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (6.17GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Thanks for the report - I'm digging into this issue as part of the investigation into https://github.com/microsoft/azuredatastudio/issues/7221. So I'll be closing this for now - you can follow that one for any updates!

**Comment by Charles-Gagnon** [comment]
For the time being you can roll back to 1.10 if this is greatly impacting your work (make sure to disable auto-updates if you do)

**Comment by ideoclickVanessa** [comment]
> Thanks for the report - I'm digging into this issue as part of the investigation into #7221. So I'll be closing this for now - you can follow that one for any updates!

@Charles-Gagnon 
Thanks for your quick feedback; however, I'm a little confused as this issue is #7221.

I'm also a little unsure where I would get the old 1.10 installer to roll back to since it's no longer listed on https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-2017  As such, I've switched back to the blinding white of SSMS for the time being.

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/azuredatastudio/releases/tag/1.10.0

**Comment by Charles-Gagnon** [comment]
And shoot, put the wrong link. 

https://github.com/microsoft/azuredatastudio/issues/7161 is the one I'm tracking
