### ISSUE TITLE
Add test cases for new copy/paste

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7226]
Can you add some unit tests that cover this scenario (and other common ones with/without newlines)? Nothing complicated - just testing output of this function to verify that future changes aren't breaking expected behavior.

_Originally posted by @Charles-Gagnon in https://github.com/microsoft/azuredatastudio/pull/7225#issuecomment-531936669_

**Comment by kburtram** [comment]
Test gaps are being tracked through code coverage reports.
