### ISSUE TITLE
Extension field undefined when calling azdata.TreeComponent.registerDataProvider()

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#7233]
The latest vscode merge introduced the following lines: https://github.com/microsoft/azuredatastudio/commit/ea0f9e6ce95b45def2b694efcd8ffe909bc43d20#diff-9cac4292d1fe863254c28648b24ee20eR208

When calling TreeComponent.registerDataProvider() from the External Table wizard, the extension field at that line is undefined.

**Comment by corivera** [comment]
@alanrenmsft Seems like this is caused by azdata.createWizardPage not having an extension argument. Either we can check for undefined at that new line (and potentially hit this issue again after another merge), or pass through an extension argument from createWizardPage. Which seems better to you?

**Comment by rajmera3** [comment]
Has this been solved? Getting this error after a fresh install of the SQL Server 2019 Preview extension and then trying to create an external Oracle DB

**Comment by corivera** [comment]
Yes, this has been fixed. It should be available in the next insiders build.
