### ISSUE TITLE
Update to version 1.11.0 failing

### ISSUE THREAD

**Issue by theGrower** [microsoft/azuredatastudio#7239]
Issue Type: <b>Bug</b>

Running Win10 on a Dell XPS 15 laptop. The updater launches then freezes. I  have to end the process in task manager. This is also causing general PC performance issues while it is frozen. 

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.83GB (4.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@theGrower how long did the the installer hang prior to killing it?

When performing an upgrade the first the installer does is to uninstall the previous version, during which time the progress bar won't be updated.  The uninstall typically takes a minute or two depending on hardware, load on the machine, etc.

**Comment by theGrower** [comment]
> 
> 
> @theGrower how long did the the installer hang prior to killing it?
> 
> When performing an upgrade the first the installer does is to uninstall the previous version, during which time the progress bar won't be updated. The uninstall typically takes a minute or two depending on hardware, load on the machine, etc.

10 minutes the first time. I tried a two more times and stopped the process after 4 or so minutes. 

I ended up upgrading using the installer downloaded from the website.

**Comment by kburtram** [comment]
@theGrower thanks for the additional details!  We'll take a look.

**Comment by kburtram** [comment]
We haven't been able to reproduce this issue internally and haven't seen other reports for the 1.12 or 1.13 release.  So I'll close this issue out now.  Please let me know if you continued to see this bug on 1.12 or 1.13 updates.  Thanks!

**Comment by theGrower** [comment]
It happened again on 1.12. However, for 1.13 I just started the update and came back after a 20 minute meeting and it worked. Who knows. My guess is it is an environmental issue in my machine. Thanks for your due diligence.
