### ISSUE TITLE
Provide Advanced & ANSI query execution settings like SSMS

### ISSUE THREAD

**Issue by justingrant** [microsoft/azuredatastudio#726]
SSMS allows you to set query execution settings for new queries. For example, I always enable the following advanced settings when I install SSMS: 
* SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
* SET STATISTICS IO ON
* SET STATISTICS TIME ON

It'd be very helpful to have a similar capability in SQL Ops Studio. It'd be OK if there wasn't UI for each individual setting as long as there was some way to specify 1+ lines of SQL that should be run whenever a new connection is opened.

**Comment by kburtram** [comment]
This feature was added to the June release.  Please open issues for any bugs found in this area.
