### ISSUE TITLE
Script as Create returns error for tables created on DataPool

### ISSUE THREAD

**Issue by capnsue** [microsoft/azuredatastudio#7260]
Issue Type: <b>Bug</b>

1. Create an external table on a SQL 2019 BDC, with data source = SqlDataPool

2. In ADS, right click on "Script As Create"

3. Get error dialog: "Scripting Failed: No script was returned when scritping as Create on object Table"

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (48 x 2200)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|127.89GB (117.37GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-vnext|Mic|0.16.0

</details>

**Comment by chlafreniere** [comment]
@kevcunnane can you help triage here?

**Comment by kevcunnane** [comment]
@shueybubbles does this fail in SSMS also? Is this another case where we need folks to update SMO?

**Comment by kevcunnane** [comment]
Triaged - we should get fixed for future update but likely this needs a fix in SMO (by the folks who made related changes)?

**Comment by yualan** [comment]
@shueybubbles Would an update to SMO fix this issue?

**Comment by grange-sam** [comment]
This issue remains in ADS/SSMS. Is there any known workaround whilst we wait on a resolution?

Version: 1.13.1 (user setup)
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:08:09.800Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by saipuli** [comment]
Still running into this issue in ADS, while scripting external tables on Azure SQL DB

Version: 1.14.1
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:37:56.865Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 18.7.0

**Comment by Charles-Gagnon** [comment]
Update to this - we've made the fix in SMO and I have a PR out (https://github.com/microsoft/sqltoolsservice/pull/911) that will bring the fix in to SqlToolsService so that ADS can pick it up. So this should be fixed in the next stable release (but once SqlToolsService is updated you it'll be in the insiders builds so you can use that)

**Comment by Charles-Gagnon** [comment]
The fix is now available in our [insiders builds](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master). Otherwise it'll be available in the next stable release - currently targeted for early February.

**Comment by capnsue** [comment]
this is great news, thank you.

**Comment by jpmckearin** [comment]
> The fix is now available in our [insiders builds](https://github.com/Microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master). Otherwise it'll be available in the next stable release - currently targeted for early February.

Just a follow-up. I had a problem running "Script as Create" on an external table that was just using another Azure Sql Server as a data source. I was able to use the latest insiders mentioned here to work around the issue. Thanks guys!

**Comment by elonmallin** [comment]
Had this problem today with the latest version of ADS. `Script as Create` on a table in my `(LocalDb)\MSSQLLocalDB` took about 10 minutes to open. Tried a bunch of times though and it only opened once in the end so not sure if it actually took 10 min or if one of the later tries succeeded, either way it took minutes.

Tried restoring a backup to `mcr.microsoft.com/mssql/server` docker container and there it opened instantly. Tried again later with localdb and it opened instantly again. But I've had this problem a few times so it seems random when it's super slow and works as normal.

Can I see logs somewhere if there is an error?
