### ISSUE TITLE
Tab randomly closes when clicked on

### ISSUE THREAD

**Issue by novusnick** [microsoft/azuredatastudio#7263]
There have been several instances when I am on one tab in the SQL editor and then I click on a separate tab, that the tab that I click on closes.  It doesn't happen all the time and so far I can't detect a pattern for when it happens, save that I'm on a normal view (aka. not split view) when it does happen.  It is very frustrating as I lose all the SQL I was working on

**Comment by kburtram** [comment]
Closing older bugs without current repro reports.  I haven't seen behavior similar to this in recent builds and we've made numerous improvements to the ADS shell that may have helped address the underlying issue here.  Please let us know if this issue still is impacting your use case.
