### ISSUE TITLE
Main window is always on top

### ISSUE THREAD

**Issue by simonds** [microsoft/azuredatastudio#7265]
Issue Type: <b>Bug</b>

With the latest version, the main application window stays on top of all other windows in the operating system.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.90GB (0.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.42.0
import|Mic|0.10.0
profiler|Mic|0.9.0
server-report|Mic|0.1.5
sql-dw|Mic|0.0.1

</details>

**Comment by kburtram** [comment]
@simonds do you have any additional repro steps?  We haven't seen this behavior internally yet.

**Comment by simonds** [comment]
Restarted app and problem went away. Should have followed first rule of troubleshooting: restart!
