### ISSUE TITLE
Startup of ADS is really slow....

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7269]
Issue Type: <b>Bug</b>

I cannot connect to a server or do new query etc for almost a minute in the recent builds.

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (6af544afde27852343d403e2e11de7e104183a27, 2019-09-18T07:50:32.629Z)
OS version: Windows_NT x64 10.0.18975

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.76GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.1
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by anthonydresser** [comment]
For performance related issues can you post the results of the command `Developer: Startup Performance` 
![image](https://user-images.githubusercontent.com/4324725/65173868-9a011f80-da04-11e9-9f34-de2e3469c8b7.png)

The useful sections are `Performance Marks` and `Extension Activation Stats`

**Comment by Charles-Gagnon** [comment]
Please follow the instructions [here](https://github.com/Microsoft/azuredatastudio/wiki/Performance-Issues) to help us figure out where the problem is.
