### ISSUE TITLE
Left and Right arrows navigation on Servers/Objects Panel

### ISSUE THREAD

**Issue by yzraeu** [microsoft/azuredatastudio#727]
- SQL Operations Studio Version: 
Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

Steps to Reproduce:
Currently navigation through tables, procs is using Up and Down arrows + pressing Enter. Using Left and Right should have the same behavior as Windows Explorer/VSCode

**Comment by kburtram** [comment]
Please review the details in https://github.com/Microsoft/sqlopsstudio/issues/1120 when resolving this issue.

**Comment by kburtram** [comment]
We're tracking this issue with the duplicate https://github.com/microsoft/azuredatastudio/issues/5579.  This is supported by the new Servers tree control but was moved to July release for additional testing/stabilization.
