### ISSUE TITLE
Create Tests in ConnectionDialogService for Canceling out out of dialog

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7281]
Create tests for connectionDialogService for the following scenarios:

- Connection exists already in queryInput, user cancels out of dialog
- Connection does not yet exist in queryInput,  user cancels out of dialog
- User cancels out of dialog while connecting to new server

**Comment by kburtram** [comment]
Closing older engineering task issues.  Please reactive if this is tracking work you'll be picking up in the near/medium term.
