### ISSUE TITLE
[ADS] ADS LOGS url (Kibana) not working for Metrics and Logs Pods

### ISSUE THREAD

**Issue by demoolya** [microsoft/azuredatastudio#7285]
Issue Type: <b>Bug</b>

· In ADS under Big data cluster overview -> Cluster Details-> Control, the LOGS url for metricsdc, metricsui, metricsdb, logsui, logsdb and mgmtproxy takes us to "file:///C:/Program%20Files/Azure%20Data%20Studio%20-%20Insiders/resources/app/out/vs/code/electron-browser/workbench/workbench.html".
· The Kibana logs are not available for these PODS which I assume is expected considering we do not have fluentbit running in those PODs. But it would be better to either disable this option for these PODs or give a message stating the logs for these PODS are not collected by design. Or is there a plan to include any logs for this PODs?
		
	
![image](https://user-images.githubusercontent.com/54091686/65248704-3c59f980-db10-11e9-8256-94eadbaa24dc.png)
	 
· I am using latest ADS version:
		
![image](https://user-images.githubusercontent.com/54091686/65248710-40861700-db10-11e9-9d07-588b1bc7b321.png)

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (a584aca96997a18ecedee73a575536332e542718, 2019-09-19T07:58:50.448Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.90GB (18.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by Charles-Gagnon** [comment]
Thanks for the report @demoolya - I've confirmed that not all instances will have logs available and so am changing it to display N/A if a URL is not available.
