### ISSUE TITLE
Command Bar disappears on Save

### ISSUE THREAD

**Issue by pchristo4410** [microsoft/azuredatastudio#7289]
Issue Type: <b>Bug</b>

When you start a New Query, there is a command bar at the top of the file (Run, Cancel, Disconnect, etc.)

Upon saving the query to a file (File --> Save), the command bar disappears and I see no setting or other way to view it again.

Azure Data Studio version: Azure Data Studio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:14:33.682Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6567U CPU @ 3.30GHz (4 x 3300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|16.00GB (0.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@pchristo4410 are you saving the file with a `.sql` extension?  If not, then the language mode of the file would change causing the toolbar to not be shown.  

You should be able to get the get the toolbar back by switching the language mode to SQL by clicking one the language mode button in the status bar (if it already says SQL you should be able to switch to some thing else then switch back to SQL to get the toolbar back).

<img width="220" alt="Screen Shot 2019-09-19 at 12 10 39 PM" src="https://user-images.githubusercontent.com/599935/65273711-a190f900-dad6-11e9-9058-524272a9dbb3.png">

**Comment by pchristo4410** [comment]
Yes, it was being saved with .SQL extension. The workaround above does work to get it to go back into SQL language mode. Thanks!

**Comment by kburtram** [comment]
I can't repro this with the latest build.  Please let us know if the issue persists.  Thanks!
