### ISSUE TITLE
Electron 6 Merge : Connection Dialog clear list icon misaligned

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7294]
Expected :

![image](https://user-images.githubusercontent.com/28519865/65283056-3271cf80-daeb-11e9-9acb-c41edc579bef.png)

Actual : 
![image](https://user-images.githubusercontent.com/28519865/65282924-fc345000-daea-11e9-8f61-5be6901e5d70.png)

**Comment by anthonydresser** [comment]
should be fixed https://github.com/microsoft/azuredatastudio/pull/7282/commits/4a4d76da83bad12db80e1aa7870ec2668f0ffabe
