### ISSUE TITLE
Electron 6 Merge : Query Editor missing icons 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7295]
Expected : 

![image](https://user-images.githubusercontent.com/28519865/65283892-048d8a80-daed-11e9-8b94-dae7cd57a3ef.png)

Actual :
![image](https://user-images.githubusercontent.com/28519865/65283909-0d7e5c00-daed-11e9-90f8-f50656bafab9.png)

**Comment by anthonydresser** [comment]
should be fixed 4a4d76d
