### ISSUE TITLE
Liveshare extension errors in console 

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7296]
Activating extension 'Microsoft.liveshare' failed: Cannot find module 'c:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\liveshare\out\main'
Require stack:
- c:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\vs\loader.js
- c:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\bootstrap-amd.js
- c:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\out\bootstrap-fork.js.

And indeed nothing is in that folder

![image](https://user-images.githubusercontent.com/28519865/65284247-dbb9c500-daed-11e9-9e28-eb1642dcd8b3.png)

**Comment by anthonydresser** [comment]
I don't think this is new in electron 6. This existing in master.

**Comment by aaomidi** [comment]
Since we're getting this again I'm going to reopen and rename the issue.

**Comment by aaomidi** [comment]
![image](https://user-images.githubusercontent.com/1465785/67129038-61df2f00-f1b2-11e9-80a9-565a8b847738.png)
