### ISSUE TITLE
Electron 6 Merge : EnablePreviewFeature depends on UNKNOWN service windowsMainService

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7298]
I'm not seeing the pop up asking to enable preview features and this error appears in console

![image](https://user-images.githubusercontent.com/28519865/65284373-34895d80-daee-11e9-98f2-29a013b48d77.png)

**Comment by anthonydresser** [comment]
fixed https://github.com/microsoft/azuredatastudio/pull/7282/commits/4f2fbee44ecdcdc413a944b0deed744e0a09f30d
