### ISSUE TITLE
Server list collapses everything after doing a search

### ISSUE THREAD

**Issue by xt0rted** [microsoft/azuredatastudio#73]
- SQL Operations Studio Version: 0.23.6

Steps to Reproduce:
1. Expand one or more database connections so tables or views are showing
1. Search for anything in the box above
1. Clear the search

I'd expect the view to return to how it was once the search is cleared but instead all connections and groups are collapsed.

**Comment by aaomidi** [comment]
Is this an issue anymore?

**Comment by xt0rted** [comment]
I haven't used this since v1 was released so I'm not sure.

**Comment by abist** [comment]
This issue isn't applicable any more.
