### ISSUE TITLE
Ensure Test Suites are Written to stdout when Running Extension Unit Tests

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7316]
The ad-hoc Windows Azure DevOps build failed in part due to extension unit test timeouts.

**Comment by chlafreniere** [comment]
We see the following during test timeouts:

INFO:CONSOLE(177)] "Uncaught Error: write EPIPE", source: events.js (177)
[VS Code]: render process crashed!

**Comment by aaomidi** [comment]
I've done a lot of testing for this over the weekend on my topic branch for it, basically I've reached no where other than something environment specific is causing issues on the Microsoft hosted agents.

**Comment by aaomidi** [comment]
Moved to Linux PR validation.
