### ISSUE TITLE
Disable Ad-Hoc Scheduled Builds

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7317]
We don't need to be running the Ad-Hoc build definitions on a daily basis; these build definitions are supposed to only be run when necessary.

**Comment by kburtram** [comment]
@chlafreniere let's discuss this in DRI meeting today.  I think there is some value in have a redundant daily build against master, as it helps to determine real infra problems from transient issues.  Thought I agree it may not be worth adding the additional resource consumption\contention.

**Comment by chlafreniere** [comment]
We discussed this during the DRI meeting today, and decided to keep this build for no, as it gives more test coverage and allows us to find issues faster. It even found an issue last night that the REL builds didn't find.
