### ISSUE TITLE
Active sessions \ files closes when I open the command palette - Sporadic issue

### ISSUE THREAD

**Issue by dbamaster** [microsoft/azuredatastudio#7320]
- Azure Data Studio Version:
1.11
- Operating system:
macOS 10.14 (Mojave)

Steps to Reproduce:
1. Open a SQL File, connect to a SQL Server instance  (leave it open)
2. Right click on SQL Server instance name, select New Query (leave it open)
3. Open command palette ( ⌘ + ⇧ + p)
4. All active sessions and SQL files disappears

This is a sporadic issue, does not happens all the time. I think will be difficult to reproduce.

Thanks!

**Comment by dbamaster** [comment]
I have attached a short video on how to reproduce the issue
[Reproduction.zip](https://github.com/microsoft/azuredatastudio/files/3748551/Reproduction.zip)

**Comment by anthonydresser** [comment]
There have been various issues with people losing sql files, most likely they are all related.

**Comment by aaomidi** [comment]
In the video you've sent, the file was open in temporary mode. If you make an edit the file will be opened in permanent mode - or if you double click the title or file from the explorer.

If the title is italics: temporary mode
If the title is normal: permanent mode
