### ISSUE TITLE
Controller Dashboard: toolbar isn't styled

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#7324]
Issue Type: <b>Bug</b>

The toolbar styling isn't matching things like the Notebook toolbar. I believe this should be a built-in component so has this regressed? We should ensure this is consistent.

![image](https://user-images.githubusercontent.com/10819925/65460418-afac8580-de06-11e9-82eb-6637338f733d.png)

Specific issues:
- Spacing is off
- On click, get left with blue selection box around the button you clicked (should grow bigger then not show with blue selection box at the end)

Azure Data Studio version: azuredatastudio 1.12.0 (9ca6200018fc206d67a47229f991901a8a453781, 2017-12-15T12:00:00.000Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv|.|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|9.9.3
ads-language-pack-es|Mic|1.9.0
azuredatastudio-postgresql|Mic|0.2.2
sql-vnext|Mic|0.14.1

</details>

**Comment by yualan** [comment]
@Charles-Gagnon Is this issue related to the refresh button behavior?

**Comment by Charles-Gagnon** [comment]
@kevcunnane We don't use the same toolbar

Notebook is using a toolbar styled with the editor-toolbar and actionbar-container classes

https://github.com/microsoft/azuredatastudio/blob/60bf331f19f32cde22558992748790a0fb29704d/src/sql/workbench/parts/notebook/browser/notebook.component.html#L8

BDC dashboard is using the modelview toolbarContainer which is using its own CSS

https://github.com/microsoft/azuredatastudio/blob/e8e8ee59413886a2f8d92410ceaf52d1ee0409cb/src/sql/workbench/browser/modelComponents/media/toolbarLayout.css#L6

I agree this doesn't seem correct though - we should be using the same toolbar styling for both. 

As for the spacing - are you still seeing that on the latest master/insiders? I have a fix there which should make things look better

![image](https://user-images.githubusercontent.com/28519865/67498413-3fc33200-f634-11e9-91b3-08352050eb84.png)

**Comment by Charles-Gagnon** [comment]
@yualan I'm moving this into planning since I don't see this as being necessary for the November time frame
