### ISSUE TITLE
Notebooks: Run Button in Cells is Styled Incorrectly

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7325]
The run button for cells is not styled properly and is much smaller than it used to be:
![image](https://user-images.githubusercontent.com/40371649/65460809-95bf7280-de07-11e9-8f36-27407abbc536.png)

Note: not an October issue, as that branch doesn't have this change. This is a regression, however.

**Comment by MaddyDev** [comment]
Above merge fixes this.
