### ISSUE TITLE
flexbox.css is being pulled from a bad location

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7326]
The flexbox.css file manages a lot of our layout, for example allowing for scrolling and properly displaying content with the overflow settings. However it is only being pulled from https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/parts/editData/browser/gridParentComponent.ts#L6.

This means if  we disable the editData contribution point, the layout for notebooks & dashboard fall apart.

We need to change where we're pulling this file to some base file.

**Comment by kburtram** [comment]
@aaomidi I thought I saw you sent a PR to fix this?

**Comment by aaomidi** [comment]
I have. I'll close the issue.
