### ISSUE TITLE
Add validation logic for bdc.json & control.json 

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7344]

**Comment by alanrenmsft** [comment]
this is to make sure the format of the bdc.json and control.json are parsable and exit gracefully if the format is not as expected.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
