### ISSUE TITLE
Schema compare differences table not showing

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#7357]
After the comparison finishes, the table of differences shows for a second then disappears.

![image](https://user-images.githubusercontent.com/31145923/65561267-ae5a8600-def6-11e9-867a-dda54ade77b6.png)
![schemaCompareDisappearing](https://user-images.githubusercontent.com/31145923/65561274-b61a2a80-def6-11e9-9484-5222c75a9909.gif)

**Comment by kisantia** [comment]
I tried changing IProgressService to IEditorProgressService in https://github.com/Microsoft/azuredatastudio/blob/diff/src/sql/workbench/browser/modelComponents/diffeditor.component.ts#L73. This got rid of the error, but the table and diffeditor still aren't showing

**Comment by kisantia** [comment]
Caused by commit ea0f9e6ce95b45def2b694efcd8ffe909bc43d20

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/pull/6979 Take a look at this

**Comment by udeeshagautam** [comment]
@kisantia we can close this right?

**Comment by kisantia** [comment]
Yup I'll close it since it didn't close with the PR
