### ISSUE TITLE
Block Comments are not highlighted correctly

### ISSUE THREAD

**Issue by eschaubert** [microsoft/azuredatastudio#7358]
Issue Type: <b>Bug</b>

Block Comments are not highlighted correctly if there is another blockcomment within that blockcomment. In the following code the first test is highlighted as a comment, but the second is not. Evidently, the highlight code looks for the next closing */ even if it does not belong to the blockcomment itself.

/*
/* Test1 */
Test2
*/

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17134

**Comment by Charles-Gagnon** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/848
