### ISSUE TITLE
Querry

### ISSUE THREAD

**Issue by david8610** [microsoft/azuredatastudio#7365]
Issue Type: <b>Bug</b>

https://dev.azure.com/davidgalim

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-2450M CPU @ 2.50GHz (4 x 2494)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.82GB (0.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by david8610** [comment]
sql aula AS apelido

select top 10  AVG(Listprice) as Pre�o
from Production.Product

Select p.FirstName as Nome, p.LastName as Sobrenome
from Person.Person p

select p.ProductNumber as "Codigo do Produto"
from Production.Product p

select s.UnitPrice as "Pre�o unitario"
from Sales.SalesOrderDetail s

SQL Inner Join 


select top 10 *
from Person.Person

select top 10 *
from person.EmailAddress


select p.BusinessEntityID,p.FirstName,p.LastName, pe.EmailAddress
from Person.Person as P
inner join Person.EmailAddress PE on p.BusinessEntityID = pe.BusinessEntityID

select top 10 * 
from Production.Product

select top 10 *
from Production.ProductSubcategory

select pr.ListPrice, pr.Name,ps.Name as "Nome da Subcategoria"
from Production.Product PR
inner join Production.ProductSubcategory PS on PS.ProductSubcategoryID = PR.ProductSubcategoryID


select top 10 * 
from Person.BusinessEntityAddress

select top 10 * 
from Person.Address



select top 10 * 
from Person.BusinessEntityAddress BA
INNER JOIN Person.Address PA on PA.AddressID = BA.AddressID




select top 10 * 
from Person.PhoneNumberType

select top 10 * 
from Person.PersonPhone

select PE.BusinessEntityID,PP.Name,PE.PhoneNumberTypeID,PE.PhoneNumber
from Person.PhoneNumberType PP
INNER JOIN Person.PersonPhone PE on PE.PhoneNumberTypeID = PP.PhoneNumberTypeID


select top 10 * 
from Person.StateProvince

select top 10 *
from Person.Address


Select top 10 PA.AddressID,PA.City,PS.StateProvinceID,PS.Name
from Person.StateProvince PS
INNER JOIN Person.Address PA on PA.StateProvinceID = PS.StateProvinceID

**Comment by chlafreniere** [comment]
Hi @david8610 can you give some more info on the issue that you're seeing?

**Comment by david8610** [comment]
meu problema é a sicronização para o github, para o projeto

**Comment by chlafreniere** [comment]
Can you give us some more details about Github issues with synchronization?
