### ISSUE TITLE
For existing .sql files, Azure Data Studio isn't using the MSSQL language engine.

### ISSUE THREAD

**Issue by KyleStay** [microsoft/azuredatastudio#7366]
Issue Type: <b>Bug</b>

If I try to edit an existing SQL script, Azure Data Studio isn't selecting a SQL engine for it. This prevents intellisense for Database objects. Instead of listing MSSQL, it says "Choose SQL Language". If I copy the script to a new, unsaved file and connect using the same connection, is says "MSSQL".

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6820HQ CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.44GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.1
sql-search|Red|0.3.4

</details>

![image](https://user-images.githubusercontent.com/4483057/65636613-9c3d1e00-dfb0-11e9-8231-7f1a12cc5e4f.png)

**Comment by KyleStay** [comment]
To replicate, just a save a new `.sql` file. Intellisense immediately breaks and I see `Choose SQL Language` for `SQL Language Flavor` in the status bar instead of `MSSQL`

**Comment by Charles-Gagnon** [comment]
Thanks for the report! This is a known issue - I'm going to close this as a duplicate and you can follow https://github.com/microsoft/azuredatastudio/issues/1876 for any updates.

**Comment by anthonydresser** [comment]
@Charles-Gagnon I don't believe #1876 is the correct tracking issue.

**Comment by Charles-Gagnon** [comment]
Hmm, well the intellisense is part of that for sure in that we disconnect the editor when it's saved. 

The language status item thing could be considered a separate issue since it looks like it isn't fixed even by reconnecting but it's all from the fact that we disconnect the editor in the first place so I don't see the need to keep this open as a separate issue.
