### ISSUE TITLE
Line selection behavior

### ISSUE THREAD

**Issue by bciesielski** [microsoft/azuredatastudio#737]
- SQL Operations Studio Version: 26.7

**Description:**
The line selection mechanism has its logic to it, which at times is more disturbing then helpful.
When you click on a row number - the whole line gets selected = perfect.
Unfortunately if you want to select next line of code (i.e. you have two statements one after another) all the lines actually get deselected. I figured out that the weird logic to it is that if you have an empty line between statements it works like I would expect - every mouse click selects a row.

This might not seem like a big deal, but if you are used to do things quickly  - you might end up deselecting code and running unintentionally the whole script (been there, done that ). 

I'm not sure if the current selection behavior works well for most people, if so - it would be great to have it at least configurable.

**EDIT:** it seems it has more to do with the placement of the blinking cursor - not an empty line. If you select a line and then try to select a line where the blinking cursor is - it deselects instead of selecting a row.

**Steps to reproduce:**
Referring to the screenshot:
1. click 1st line and the 11111111111 row gets selected
2. click 2nd line and the selection is gone
3. click 1st line again, the 1111111111 row gets selected back
4. click 4th row and the 3333333333 row gets selected

![sos_selection](https://user-images.githubusercontent.com/36210825/36419913-940fc6f8-1633-11e8-9fd1-54689da4a7f9.gif)

**Comment by bciesielski** [comment]
I think the logic here might be even a bit different and it has more to do with the placement of the blinking cursor after selecting the row - if you select a row and try to select a row where the blinking cursor is - then instead of selecting row , it gets deselected.

in this case i would call it a bug rather then a feature :)

**Comment by kburtram** [comment]
@bciesielski I think the line selection behavior is adopted from VS Code defaults.  We generally defer to them for edit-specific functionality and ask for those issue to logged upstream (since that is there area of expertise).  Please let me know if you think this issue is a bug that is SQL-specific (vs. general editor).

**Comment by bciesielski** [comment]
@kburtram you are right, indeed it is the VSCode behavior. 
I think this should be handled differently (per file type?) for declarative/scripting languages and for procedural/compiled code. In languages like SQL or Powershell you frequently select a few lines of code and run only the selection - in this scenario I would consider this to be a bug. On the other hand in many other languages e.g. c# due to a different workflow this is not an issue at all.

Since other declarative languages could benefit from this improvement, i guess this might be a general editor issue.

**Comment by alanrenmsft** [comment]
@bciesielski  have you opened an issue in VSCode repository: https://github.com/microsoft/vscode? This does seem to be a general editor issue, once the requested feature is implemented by vscode, ADS will get it too. I am going to close this issue since this is an upstream issue.
