### ISSUE TITLE
Filter capabilities

### ISSUE THREAD

**Issue by joseluisrod** [microsoft/azuredatastudio#7377]
Issue Type: <b>Feature Request</b>

Hi All: could you add filtering by name for tables, programmability and views please?  Thanks for the great work!

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment]
Closing this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/8052 as some cleanup
