### ISSUE TITLE
Setting files are not revealed in explorer

### ISSUE THREAD

**Issue by Ungerfall** [microsoft/azuredatastudio#7379]
- Azure Data Studio Version:
Version: 1.12.0-insider (user setup)
Commit: 2d9f6dcd862227825050eb3182553c3a176e0ce9
Date: 2019-09-26T07:52:29.030Z
VS Code: 1.38.0
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Open Keyboard Shortcuts (JSON)
2. Press F1
3. Search for Reveal in Explorer command
4. Execute (press Enter key)

Other files are correctly revealed in explorer, but the settings are not. Same thing happens for snippets.
IIRC, previous versions do allow this feature.

**Comment by kburtram** [comment]
This issue didn't repro for me on the current release.  Please let us know if you're still impacted by this issue.
