### ISSUE TITLE
BDC Deploy Initial Page should disable Select button until EULA box is checked

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7380]
![image](https://user-images.githubusercontent.com/28519865/65709562-f20fd580-e045-11e9-8bb7-e2e460eb74dc.png)

**Comment by alanrenmsft** [comment]
@Charles-Gagnon  I intentionally did it, otherwise it might be hard for user to figure out why the select button is disabled.  @angdesign , what do you think?

**Comment by Charles-Gagnon** [comment]
You should at least have a red * next to it to show that it's required

**Comment by angdesign** [comment]
Recommend that we have a separate section for the license agreement that is marked as required, as per Charles' comment, attaching a mockup
<img width="1366" alt="BDC_deploy1" src="https://user-images.githubusercontent.com/29785331/65714683-79624680-e050-11e9-8286-f5cde1d126bf.png">

**Comment by alanrenmsft** [comment]
The required indicator part has been fixed. It seems the EULA might vary  based on the selected options, there are extra work there. Thanks @angdesign , I will incorporate your feedback when I work on that part.
