### ISSUE TITLE
ADS Right Click and Script External Table using DataPool fails

### ISSUE THREAD

**Issue by EricBuMSFT** [microsoft/azuredatastudio#7407]
**- Azure Data Studio Version:**
Version: 1.12.0-insider (user setup)
Commit: bf23a52ba433fa13fdc13e97fc0076b19a11de0c
Date: 2019-09-20T09:48:03.076Z
VS Code: 1.38.0
Electron: 6.0.9
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Steps to Reproduce:**

1. Create an external table that uses a datapool (I can let you log into my BDC if you like)
2. Right click on the table and select "Script as Create". The following error will appear:

_"No Script was returned when scripting as Create on object Table"_

![image](https://user-images.githubusercontent.com/47893745/65783749-72096e80-e11e-11e9-8a00-74d5f2af117e.png)

NOTE: The same issue, better error happens in SSMS. David Shiflet is working on this from the SSMS perspective.
Error is SSMS = _To accomplish this action, set property Location. (Microsoft.SqlServer.Smo)_

UC and David triaged. David's fix (script engine needs to allow for NULL Location) may work with ADS. Just not sure if we leverage the same code there between ADS and SSMS.

**Comment by chlafreniere** [comment]
This will be tracked with #7260
