### ISSUE TITLE
Feature Request: enhance add notebook cell API

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7411]
When adding a new cell to the notebook using API, we should be able to specify whether to focus it or not.

```TypeScript
InsertCell(cell: { cell_type: string, source:string}, index: number, focus: boolean);
```

**Comment by chlafreniere** [comment]
Closing old issue that's no longer needed after chatting with @alanrenmsft. If anything like this comes up in the future feel free to reopen.
