### ISSUE TITLE
Intellisense often not working

### ISSUE THREAD

**Issue by LokeSonne** [microsoft/azuredatastudio#7416]
Issue Type: <b>Bug</b>

Intellisense is very on/off. Sometimes it works - most times it doesn't. Otherwise - great product

Azure Data Studio version: Azure Data Studio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:14:33.682Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (2.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|25%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
There's already some open issues tracking general performance of Intellisense such as #4817 so I'm going to close this, keep an eye there for any updates!

As a note there was specifically a bug in 1.11 though that made it so Intellisense wasn't working on saved files. See #7161 for details. You can use the current insiders version which has that fix - otherwise we should have the next stable release out next week which will also contain that fix.

**Comment by LokeSonne** [comment]
Thanks!

Den 29. sep. 2019 kl. 19.09 skrev Charles Gagnon <notifications@github.com<mailto:notifications@github.com>>:


There's already some open issues tracking general performance of Intellisense such as #4817<https://github.com/microsoft/azuredatastudio/issues/4817> so I'm going to close this, keep an eye there for any updates!

As a note there was specifically a bug in 1.11 though that made it so Intellisense wasn't working on saved files. See #7161<https://github.com/microsoft/azuredatastudio/issues/7161> for details. You can use the current insiders version which has that fix - otherwise we should have the next stable release out next week which will also contain that fix.
