### ISSUE TITLE
The script generated from the HDFS option "Create external table from CSV files" for Storage Pool fails

### ISSUE THREAD

**Issue by Peter-Msft** [microsoft/azuredatastudio#7417]
Azure Data Studio Version: 1.12.0-insider

Steps to Reproduce:
1) ADS -> Right-click on a CSV file in HDFS -> Create external table from CSV files
2) At the end of the Wizard click -> Generate Script

Example script:
BEGIN TRY
    BEGIN TRANSACTION T4aba716521a64eb5bb273b07e6b25c5
        EXEC('USE [DeepSky]');
        CREATE EXTERNAL FILE FORMAT [FileFormat_Planets]
            WITH (FORMAT_TYPE = DELIMITEDTEXT, FORMAT_OPTIONS (FIELD_TERMINATOR = N',', STRING_DELIMITER = N'\"', FIRST_ROW = 1));
        CREATE EXTERNAL TABLE [dbo].[Planets]
        (
            [Number] tinyint NOT NULL,
            [Planet] nvarchar(50) NOT NULL
        )
        WITH (LOCATION = N'/Data/Planets.csv', DATA_SOURCE = [SqlStoragePool], FILE_FORMAT = [FileFormat_Planets]);
    COMMIT TRANSACTION T4aba716521a64eb5bb273b07e6b25c5
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION T4aba716521a64eb5bb273b07e6b25c5
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;

3) Execute the generated script in ADS. Fails with error (although the 'FileFormat_Planets' object does not exist):
	Started executing query at Line 1
	Msg 50000, Level 16, State 1, Line 20
	Type with name 'FileFormat_Planets' already exists.
	Total execution time: 00:00:00.167

(note: if you click on "Generate Table" instead of "Generate script" at the end of the wizard it will create the table).

4) Copy the same SQL script into SSMS (v18.2) and it executes without problems.

**Comment by yualan** [comment]
@corivera This should be fixed? Can you verify?

**Comment by corivera** [comment]
@yualan I'm guessing this is related to the EXEC USE statement. We already fixed that issue.

**Comment by corivera** [comment]
I don't think that fix shipped yet, so it should be available as part of this month's extension update.

**Comment by corivera** [comment]
@Peter-Msft Try removing the EXEC wrapper around

**Comment by kevcunnane** [comment]
@corivera can you clarify if this fix is in the next extension update? If so let's close and let folks know that's where to look for this fix.

**Comment by corivera** [comment]
@kevcunnane The fix for removing the EXEC wrapper was checked in on 9/19. Our last extension update was on 9/11, so the fix should be available in our next update.

**Comment by kevcunnane** [comment]
Closing this in that case. We will ship in our November release.
