### ISSUE TITLE
Script from "Create external Table" wizard is not working

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#7423]
Issue Type: <b>Bug</b>

seems like the "USE" statement in the script created by the wizard is not working

this leads to an error: 

`BEGIN TRY
    BEGIN TRANSACTION T12e45695fc5442b9920635d749179db
        EXEC('USE [BigDataFun]');
        CREATE EXTERNAL TABLE [dbo].[ProductModel]
        (
            [ProductModelID] INT NOT NULL,
            [Name] NVARCHAR(50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
            [CatalogDescription] NVARCHAR(4000),
            [rowguid] UNIQUEIDENTIFIER NOT NULL,
            [ModifiedDate] DATETIME2(3) NOT NULL
        )
        WITH (LOCATION = N'[AdventureWorks].[SalesLT].[ProductModel]', DATA_SOURCE = [AW]);
    COMMIT TRANSACTION T12e45695fc5442b9920635d749179db
END TRY
BEGIN CATCH
    IF @@TRANCOUNT > 0
        ROLLBACK TRANSACTION T12e45695fc5442b9920635d749179db
    DECLARE @ErrorMessage NVARCHAR(4000) = ERROR_MESSAGE();
    DECLARE @ErrorSeverity INT = ERROR_SEVERITY();
    DECLARE @ErrorState INT = ERROR_STATE();
    RAISERROR(@ErrorMessage, @ErrorSeverity, @ErrorState);
END CATCH;
`

with the error being:

`9:12:19 AMStarted executing query at Line 1
Msg 50000, Level 16, State 1, Line 21
External table references 'DATA_SOURCE' that does not exist.
Total execution time: 00:00:00.011`

if I manually run/set set database context before hitting F5, all is fine.

When replaceing

`EXEC('USE [BigDataFun]');`

with 

`USE [BigDataFun]`

it's fine, too

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.14393

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2673 v4 @ 2.30GHz (16 x 2295)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|64.00GB (58.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by kevcunnane** [comment]
@corivera is this fixed in Insiders? I think you had a solution, do we have it published/will we be publishing for October release?

**Comment by corivera** [comment]
@kevcunnane Yes, I updated the EXEC statement to be a plain USE.

**Comment by kevcunnane** [comment]
@corivera can you work with @yualan to ensure this is included as part of the October release?

@bweissman apologies for the inconvenience. We will publish a refreshed version of the extension with this fix available in our upcoming October release. I'm going to close the issue as the core fix is in, just needs release.
