### ISSUE TITLE
[SQL History extension] Add ability to persist history after an ADS restart

### ISSUE THREAD

**Issue by Peter-Msft** [microsoft/azuredatastudio#7438]
The history is not persisted after a restart of ADS. 
A nice additional option would be to retain the history entries following a restart.

**Comment by Rich-Ott** [comment]
Has there been any further traction on this? This is the one thing holding me back from using Azure Data Studio. I use query history all the time and can't imagine not being able to do so.

**Comment by TrishaMoore** [comment]
I would also like to have this feature.  I am new to ADS and recently installed the plug in.  I had no idea my history would be wiped out when I boot my laptop.  If this isn't going to be fixed, I'm with @Rich-Ott , I'll find a new tool.

**Comment by kburtram** [comment]
@TrishaMoore I think the concern with this suggestion was that we don't scrub passwords and other sensitive data out of users' queries when saving into their history.  Given this there was security/privacy concerns with persisting this data to disk.  Perhaps we can add a setting that would allow users to opt-in to this behavior if this isn't a concern in their scenario.  I'll review with the PM area owner.

**Comment by TrishaMoore** [comment]
Hi @kburtram , I totally understand the concern around password security.  Could you enhance the history such that it doesn't save the passwords and only the SQL.  I used SQL Assistant for years when working with Teradata.  It saves all the SQL history but you have to login to your TD system before running the query, it doesn't save the id/pw info.  Just a thought. Thanks!

**Comment by darren-kay** [comment]
We have switched from Teradata to Synapse and the Data team and some power users are reluctant to switch over from the Teradata query tool to ADS due to the lack of persistence of the SQL history. Could the app use encrypted storage and ask them for a password to store the data between sessions if the user enables persistence?
