### ISSUE TITLE
Unable to open diff of ipynb files form Source Control pane

### ISSUE THREAD

**Issue by amtwo** [microsoft/azuredatastudio#7439]
Issue Type: <b>Bug</b>

* Create a SQL Notebook and save it to an existing local git repo directory.  There is no need to actually stage/commit the change.
* Go to the Source Control pane.
* Double-click on the SQL Notebook you just created. 

Expected:
* The SQL Notebook should open, showing a diff of the the committed vs uncommitted versions.  Since the .ipynb file is stored as JSON, I'd expect to get a plain text comparison of the underlying JSON files. 
* Possibly, I would expect to get a "not supported" error message.

Actual:
* I get an error message "Unable to open 'MySQLNotebook.ipynb (Working Tree)': this.textEditorModel.onDidStageChange is not a function."

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (084524cd2dd30a1266f121c86527baf533ac8bf9, 2019-10-01T07:59:19.187Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (3.21GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
cms|Mic|0.5.0
powershell|ms-|2019.5.0
profiler|Mic|0.10.0
plan-explorer|Sen|0.9.4

</details>

**Comment by chlafreniere** [comment]
Thanks, @amtwo. We're tracking this with #7403 currently.

**Comment by amtwo** [comment]
Gah! Thanks. I missed that when I searched since was looking for "source control" rather than "git" 😁
