### ISSUE TITLE
Integration tests failing on Linux

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7464]
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=40373

**Comment by anthonydresser** [comment]
#7461 may fix is, not sure why that would cause the tests to straight up fail since it doesn't have any functional affect on the product, but its possible it is reading the raised error as a error for the test.

**Comment by aaomidi** [comment]
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=40388

**Comment by aaomidi** [comment]
Looks like it's still failing.

**Comment by aaomidi** [comment]
The issue is mkdir with recursive doesn't work on electron 4 ...

**Comment by aaomidi** [comment]
Standalone Database Context Menu test is failing. If anyone has a good background on these tests I'd love to get your help.

**Comment by aaomidi** [comment]
Moved to unstable tests.
