### ISSUE TITLE
Create JSON-backed dialog for virtualizing Teradata & MongoDB

### ISSUE THREAD

**Issue by rajmera3** [microsoft/azuredatastudio#7475]
Create JSON-backed dialog with following fields to inject into Teradata/MongoDB Virtualization Notebooks:

Summary of the variables we need support for:
- master_key
- external_data_source_name
- external_table_name
- database_name
- credential_name
- username
- password
- server_address

**Comment by Charles-Gagnon** [comment]
I'm going to close this since we're going to be enabling MongoDB/Teradata support in the Data Virt wizard soon so this seems unnecessary.
