### ISSUE TITLE
Query window does not reconnect to last database if connection is broken

### ISSUE THREAD

**Issue by patschaefer** [microsoft/azuredatastudio#749]
- SQL Operations Studio Version: February (0.26.7) Ubuntu, connected to SQL on Linux

Steps to Reproduce:
create database foo
go

use foo
go

CREATE TABLE SpatialTable   
    ( id int IDENTITY (1,1),  
    GeomCol1 geometry,   
    GeomCol2 AS GeomCol1.STAsText() );  
GO  

INSERT INTO SpatialTable (GeomCol1)  
VALUES (geometry::STGeomFromText('LINESTRING (100 100, 20 180, 180 180)', 0));  

INSERT INTO SpatialTable (GeomCol1)  
VALUES (geometry::STGeomFromText('POLYGON ((0 0, 150 0, 150 150, 0 150, 0 0))', 0));  
GO  

select * from SpatialTable
go

-- Restart the server
-- This is expected to fail with a connection error:
select * from SpatialTable

--[10:31:09 AM]	Started executing query at Line 29
--Msg 0, Level 20, State 0, Line 0
--A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, 
 error: 2 - Connection was terminated) 
--Total execution time: 00:00:00.023

-- This should work since the connection is reestablished in the background
select * from SpatialTable
-- But it fails
--Started executing query at Line 29
--Msg 208, Level 16, State 1, Line 1
--Invalid object name 'SpatialTable'. 
--Total execution time: 00:00:00.012

-- Because we are still in master
select db_name()
--(No column name)
--master

**Comment by kburtram** [comment]
Closing older bugs that are planned for an upcoming milestone.  Thanks!
