### ISSUE TITLE
app_name: azdata-GeneralConnection - Errors : "Use older DMV" ! 

### ISSUE THREAD

**Issue by hamidmira** [microsoft/azuredatastudio#7508]
- Azure Data Studio Version:
Version: 1.12.0 (user setup)
Commit: f0b6180e15f455ccf9e8112b407a6aa8c5399fe9
Date: 2019-10-01T18:01:40.565Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

Steps to Reproduce:
Why Azure Data studio (app: azdata-GeneralConnection) generates this error ? 
"Use older DMV"?  
I am logged in to a SQL Server 2017 instance.
See error below :
```
-- time_stamp : 2019-10-04 12:17:47.9490000
-- client_hostname : XXXX 
-- client_app_name : azdata-GeneralConnection
-- database_name : master
-- err_message : Use older DMV
-- sql_text : 
IF OBJECT_ID (N'sys.dm_cluster_endpoints') IS NOT NULL
SELECT [name], [description], [endpoint], [protocol_desc] FROM .[sys].[dm_cluster_endpoints];
ELSE THROW 50000, 'Use older DMV', 1
```

**Comment by Charles-Gagnon** [comment]
@kevcunnane FYI

This is something we do to support backwards compatibility with older CTP versions for retrieving BDC endpoints. It'll be removed in a future update. 

Although I wouldn't expect it to show up for a 2017 instance - what were you doing when this occurred?

**Comment by hamidmira** [comment]
Thank you for your answer. 
I selected a Server (a SQL Server 2017 instance) then New query, then I executed a simple SELECT query...
```
SELECT... 
FROM...  
```

What bothers me is the generation of the error 
`THROW 50000,'Use older DMV', 1`

It's a bit embarrassing, but not blocking for me, I'll ignore the  _azdata-GeneralConnection_  application when monitoring errors.

**Comment by Charles-Gagnon** [comment]
Yeah - that's definitely not desirable. I'll look into making it so we at least don't run this unless we have to!

**Comment by hamidmira** [comment]
OK.  Thank you very much.

**Comment by kevcunnane** [comment]
Thanks Charles. Yes removing is a good idea. I think David updated to only check for 2019+ versions, but still important to get rid of it.
