### ISSUE TITLE
ADS Notebooks Don't Match Jupyter Viewer's Output for Powershell Kernel

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7514]
Looks like we're outputting a bunch of information that Jupyter somehow filters out.

Jupyter:

![image](https://user-images.githubusercontent.com/40371649/66247697-bb386000-e6d4-11e9-9102-ec86eaf3c56c.png)

ADS:
![image](https://user-images.githubusercontent.com/40371649/66247700-c4293180-e6d4-11e9-947b-23a135e1e57b.png)

**Comment by chlafreniere** [comment]
(This is only on Windows, by the way)

**Comment by corivera** [comment]
@chlafreniere Does it repro with powershell core on windows?
