### ISSUE TITLE
Powershell Kernel Hangs on Kernel Change for Mac/Linux

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7515]
In the poweshell kernel's kernel.json, the following line needs to be different for Windows vs. other platforms:
Windows:
```"powershell_command": "powershell"```

Other platforms
```"powershell_command": "pwsh"```

Alternatively, we can just run the install command as @corivera previously suggested.

@corivera any preference?

**Comment by aaomidi** [comment]
We also should probably not hang and tell the user that its not possible or something.

**Comment by chlafreniere** [comment]
We follow the jupyter behavior here unfortunately. We can look into setting timeouts.
