### ISSUE TITLE
Syntax for Temporal Tables shows up as incorrect While MSSQL is the language flavor

### ISSUE THREAD

**Issue by ClutteredSchema** [microsoft/azuredatastudio#7526]
Issue Type: <b>Bug</b>

When creating a temporal table, the syntax isn't recoginzed and displayed as incorrect.

Azure Data Studio version: azuredatastudio 1.12.0 (f0b6180e15f455ccf9e8112b407a6aa8c5399fe9, 2019-10-01T18:01:40.565Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (2.90GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
import|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|0.6.0
server-report|Mic|0.2.0
sql-vnext|Mic|0.16.0
azdata-sanddance|msr|1.3.7
sql-search|Red|0.3.4
simple-data-scripter|sea|0.1.0

</details>

![Annotation 2019-10-07 085848](https://user-images.githubusercontent.com/56141426/66313651-b647fc00-e8e0-11e9-9c43-6c2bb90b4102.jpg)

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
