### ISSUE TITLE
Cannot double click to open notebook anymore in Insider's

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7547]
Issue Type: <b>Bug</b>

When I double click an .ipynb to open in Insider's I now receive an error. This used to work - unsure what changed.

![image](https://user-images.githubusercontent.com/8250560/66347297-db506500-e908-11e9-866b-dc05976264c7.png)

Azure Data Studio version: azuredatastudio 1.12.0 (f0b6180e15f455ccf9e8112b407a6aa8c5399fe9, 2019-10-01T18:01:40.565Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (4.06GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.43.0
import|Mic|0.11.0
profiler|Mic|0.9.0
server-report|Mic|0.2.0
sql-vnext|Mic|0.14.1
whoisactive|Mic|0.1.2
azdata-sanddance|msr|1.3.7
tsqllint|tsq|1.2.0

(1 theme extensions excluded)

</details>

**Comment by aaomidi** [comment]
Where do you double click?

**Comment by chlafreniere** [comment]
@vickyharp how about other file associations?

**Comment by Charles-Gagnon** [comment]
@vickyharp I'm going to close this since it doesn't seem to repro for me currently. If it's still happening for you let me know and we can sit down and debug it!
