### ISSUE TITLE
Markdown hyperlinks to open in new tab

### ISSUE THREAD

**Issue by stuartpa** [microsoft/azuredatastudio#7553]
Issue Type: <b>Feature Request</b>

Hyperlinks such as:

[I'm an inline-style link](afterfix.ipynb)

in unchanged notebooks open in the same tab.  Hyperlinks with in notebooks that have changed open another tab!   

This creates an odd experience, if you have ‘run all cells’, this causes the notebook to change… so you get new tabs for everything (which is the experience  my customers want)

But if you are in the top level notebokos that don’t have any code cells (just lots of links to the notebooks that do have code cells), you keep losing where you are because your tab keep getting replaced by what you just clicked on.

Can we have a way to always open a new tab. 
              

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (cacbcb54156f4748a0a2d3181f9fc0ad16805b13, 2019-10-07T07:56:20.452Z)
OS version: Windows_NT x64 10.0.18362

**Comment by aaomidi** [comment]
So I'm unable to repro this issue but I think I know whats happening.

When a file is opened, or a link is clicked - the file that was opened is in a temporary (preview) state:

![image](https://user-images.githubusercontent.com/1465785/66787225-ba9f8680-ee97-11e9-8709-621348649935.png)

The italics title represents this temporary (preview) state. Double clicking on that title will open it in a permanent state:

![image](https://user-images.githubusercontent.com/1465785/66787247-d145dd80-ee97-11e9-9bc6-885b4320daff.png)


What I'm guessing is happening is that the first notebook that has all those links you're mentioning isn't opening in this permanent state.

**Comment by aaomidi** [comment]
I'm going to be closing this issue. Please feel to comment if I misunderstood the issue and I'll reopen :)
