### ISSUE TITLE
Tokenization warning when opening a notebook

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7558]
I'm receiving an error about tokenizing long strings when I open a particular notebook.

![image](https://user-images.githubusercontent.com/8250560/66369340-d8796280-e950-11e9-8164-bcbfd0889b66.png)

As far as I can tell there are no long strings and syntax colorization etc seems to be working fine.

**Comment by chlafreniere** [comment]
This happens because of how we write HTML tables to files. Should be a quick fix.

**Comment by chlafreniere** [comment]
This causes performance implications, since when this occurs, we're not able to use the fast edit code path (and are instead serializing the notebook on every edit). Moving to March.

**Comment by chlafreniere** [comment]
When reaching max tokenization length for a given line, we need split up that line into n lines. I was hoping that this support existed as part of the vscode text model, but looks like we'll have to brew our own implementation here. Given the other high pri livesite asks, this won't make March.

**Comment by Charles-Gagnon** [comment]
Closing this since with the removal of the grammar this should no longer be an issue
