### ISSUE TITLE
Inconsistent behavior with "Close All" and notebooks

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7561]
Issue Type: <b>Bug</b>

See attached gif.

When bulk closing notebooks without saving - with or without changes - sometimes the notebooks remain in "Open Editors" and fail to fully disappear. They are "mostly" gone, but you cannot see the ADS logo in the main window panel so there is something remaining. Rehydration can occur from these closed, unsaved files.

![Close All Behvaior with Notebooks](https://user-images.githubusercontent.com/8250560/66370063-aa495200-e953-11e9-84c2-3c38bcb7a565.gif)

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (cacbcb54156f4748a0a2d3181f9fc0ad16805b13, 2019-10-07T07:56:20.452Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
big-data-cluster|Mic|0.0.1
cms|Mic|0.5.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
powershell|ms-|2019.9.0
profiler|Mic|0.10.0
query-history|Mic|0.1.0
schema-compare|Mic|0.7.0
sql-vnext|Mic|0.14.1
azdata-sanddance|msr|1.3.7

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
@vickyharp we've made improvements in this area this week. Do you still see this behavior?

**Comment by chlafreniere** [comment]
We've changed a number of things in this area and I was unable to repro after testing for a while just now. Please let us know if you see this again and feel free to reopen if you see this again @vickyharp!
