### ISSUE TITLE
Upper and lower case shortcut support

### ISSUE THREAD

**Issue by rigerta** [microsoft/azuredatastudio#7563]
In SSMS currently, when you want to convert a selection to upper or lower case you can use the following shortcuts:

CTRL + Shift + L 
CTRL + Shift + U

Could this be added as a feature? 
(I didn't know I use it that often, until I started using ADS :) )

Thanks, 
Keep up the great work!
Rigerta

**Comment by LarnuUK** [comment]
The functionality is in ADS already, i just don't think it is a default. hit <kbd>Ctrl</kbd>+<kbd>k</kbd>,<kbd>Ctrl</kbd>+<kbd>s</kbd> and type "Transform to". You'll see options for Uppercase, Lowercase and Title Case.

**Comment by rigerta** [comment]
True, thanks!
