### ISSUE TITLE
Connections Defaulting to Upper Most Server Group

### ISSUE THREAD

**Issue by brettmillerb** [microsoft/azuredatastudio#7565]
Issue Type: <b>Bug</b>

Creating New Connections in a server group places the connection in the correct server group but upon reconnecting the server group for that connection defaults to the upper most server group.

Azure Data Studio version: azuredatastudio 1.12.0 (f0b6180e15f455ccf9e8112b407a6aa8c5399fe9, 2019-10-01T18:01:40.565Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (4.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
powershell|ms-|2019.9.0
query-history|Mic|0.1.0
poor-sql-formatter|WSR|0.1.0

</details>

### Details
Creating New Connections in a server group places the connection in the correct server group but upon reconnecting the server group for that connection defaults to the upper most server group.

This means that I have to remember to change the server group every time I make a connection or go
back
and tidy the connections out of the first group periodically.

Looked through the settings and the groupID's etc all seemed correct.

### datasource.connectionGroups
```json
{
    "name": "testinggroup",
    "id": "6ce1ac6e-10f7-4956-a68d-223246eaa637",
    "parentId": "C777F06B-202E-4480-B475-FA416154D458",
    "color": "#98AFC7",
    "description": ""
},
{
    "name": "subgroup",
    "id": "ca5c6e10-7266-49ce-98a7-ae78670515d3",
    "parentId": "6ce1ac6e-10f7-4956-a68d-223246eaa637",
    "color": "#98AC96",
    "description": ""
}
```

### datasource.connections
```json
{
    "options": {
        "connectionName": "",
        "server": "Identifier.database.windows.net",
        "database": "master",
        "authenticationType": "SqlLogin",
        "user": "read-only",
        "password": "",
        "connectTimeout": 30,
        "applicationName": "azdata",
        "groupId": "ca5c6e10-7266-49ce-98a7-ae78670515d3",
        "databaseDisplayName": "Mydatabasae"
    },
    "groupId": "ca5c6e10-7266-49ce-98a7-ae78670515d3",
    "providerName": "MSSQL",
    "savePassword": false,
    "id": "1b619535-dbc9-4409-9aaf-c9c1f47c75ba"
}
```

So these appear to be correctly grouped within the settings.

**Comment by Charles-Gagnon** [comment]
@brettmillerb It appears to be working fine for me - reconnecting a server in a group correctly connects the server under the specified group. Could you include more detailed repro steps? And/or a gif showing the issue?

**Comment by brettmillerb** [comment]
### Test group created with a sub group
![image](https://user-images.githubusercontent.com/24279339/66572754-6c257b80-eb69-11e9-890a-b03dbd86617e.png)

### Closed the connection
- Click on the connection and it opens in the upper most group
- The datasource connections and connectiongroups still have it linked to the correct groupId,Parent etc


![image](https://user-images.githubusercontent.com/24279339/66572842-95460c00-eb69-11e9-9ad9-71e40eaf6bc9.png)

**Comment by Charles-Gagnon** [comment]
Ah got it - yeah there's an issue there where we're not correctly populating the server group with nested groups. I'll investigate this more - thanks for the report!
