### ISSUE TITLE
Functions being wrapped in Brackets

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#7570]
Issue Type: <b>Bug</b>

When typing functions native to SQL Server (I haven't tested with User Scalar functions, as I don't tend to use them) and using <kbd>Tab</kbd> to complete the name, the function is being wrapped in Brackets (`[]`), instead of having parentheses (`()`) added at the end and the cursor being put inside them.

Wrapping them in Brackets invalidates the function, as it would mean it is treated as an object name, not a function.

You can see this in the below animated image:
![Wrapped in brackets](https://user-images.githubusercontent.com/20837086/66422471-a542dc00-ea01-11e9-9758-a86bfef8cfe6.gif)

Edit: Note this was not a "feature" (bug) on previous versions of ADS. I did have ADS 1.8 installed on Windows, however, as a test I updated it to ~~1.12.1 (released yesterday at time of edit)~~ 1.12.0 and it now too has the above "feature".

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:03:49.463Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 1, 1|
|Memory (System)|15.58GB (6.42GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.6.0
profiler|Mic|0.9.0
material-icon-theme|PKi|3.9.0
sql-search|Red|0.3.4

</details>

**Comment by LarnuUK** [comment]
Seems to have no been fixed in 1.12.1 (I had installed 1.12.0 when I made the above edit, not 1.12.1)

**Comment by LarnuUK** [comment]
I'm reopening this issue, as it appears to be intermittent, and I am getting the behaviour in 1.12.1.

![Wrapped in brackets 2](https://user-images.githubusercontent.com/20837086/67796805-92f41500-fa78-11e9-9f5c-fdfe17d7cb1f.gif)

**Comment by kburtram** [comment]
@LarnuUK I haven't seen this before.  Do you happen to have any extensions, such as Postgres, installed?  Or any customized editor settings?

**Comment by LarnuUK** [comment]
Hi @kburtram , all the extensions installed are listed in my original post (which I believe are the same both on Ubuntu and Windows. PostgreSQL isn't one of those though.

**Comment by dimitri-b** [comment]
I have the same issue  in 1.13.0


I have 3 extentions:

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.12.0
azdata-sanddance|msr|1.3.9
poor-sql-formatter|WSR|0.1.0
