### ISSUE TITLE
VSCode test failure

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7573]
These tests failed on build 41090.

![image](https://user-images.githubusercontent.com/599935/66425173-e0beb580-e9c3-11e9-95fc-1e0855ba1bb9.png)

**Comment by aaomidi** [comment]
New test failure:

![image](https://user-images.githubusercontent.com/1465785/66672369-0097e880-ec13-11e9-9a28-785dc861ec8e.png)

**Comment by kburtram** [comment]
Let's turn these off these failing vscode tests.
