### ISSUE TITLE
Extensions search for publisher:"xxx" broken

### ISSUE THREAD

**Issue by BachhF00** [microsoft/azuredatastudio#7576]
Issue Type: <b>Bug</b>

* Click the Extensions button on the left
* type  __*publisher:"Microsoft"*__ in the __*"Search Extensions in Marketplace"*__ Box
> or click on a extension in the list e.g. "Central Management Server" and click on Microsoft under the "Central Management Servers" Title in the Editor View

Azure Data Studio version: Azure Data Studio 1.12.1 (cccb9327c707fe71de24d5ce655acb29cc8946d1, 2019-10-07T19:26:59.245Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-3615QM CPU @ 2.30GHz (8 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (1.09GB free)|
|Process Argv|-psn_0_651423|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.6.0
import|Mic|0.11.0
profiler|Mic|0.9.0

</details>

**Comment by alanrenmsft** [comment]
@BachhF00  I can repro the issue and will have this fixed in the next release. thanks!

**Comment by kburtram** [comment]
Closing older issues.  You can search for a Publisher by searching for the name without the filter prefix.  It will also include matches where the string is in other fields but in practice these two search results will generally be the same.
