### ISSUE TITLE
A11y_AzureDataStudio_AddNewController_Keyboard : The keyboard focus moves to the "URL" edit box after pressing tab on the "Authentication Type" combo box.

### ISSUE THREAD

**Issue by 12-shweta** [microsoft/azuredatastudio#7595]
"[Check out Accessibility Insights!](https://accessibilityinsights.io/)- Identify accessibility bugs before check-in and make bug fixing faster and easier."
​
GitHubTags:#A11y_AzureDataStudio;#A11yMAS;#A11yTCS;#WCAG2.4.3;DesktopApp;#Keyboard;#SQL Azure Data Studio;#Win32

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

**Additional Details:**
Tool Name : Keyboard

**Steps to Reproduce:**
1. Install and Launch the application the azure data studio application.
2. Connect to the servers with the required credentials.
3. Navigate to the "SQL Server Big Data Cluster" and expand it.
4. Navigate to the "SQL Server Big Data Cluster controller" and click on it.
5. Navigate till "Authentication Type" combo box and expand it .
6. Observe that after pressing tab again , the keyboard focus moves back to  "URL" edit box.

**Actual:**
**Issue 1:**
After expanding the "Authentication Type" combo box , pressing tab again the keyboard focus moves to the "URL" edit box .

**Issue 2:**
After expanding the "Authentication Type" combo box , pressing ESC the keyboard focus moves to the background.
 
**Expected:**
**Issue 1:**
After expanding the "Authentication Type" combo box , pressing tab again the keyboard focus should remain on the "Authentication Type" combo box and pressing tab again focus should move to the next control.

**Issue 2:**
After expanding the "Authentication Type" combo box , pressing ESC the keyboard focus moves to remain on the "Authentication Type" combo box

**User Impact:**
The keyboard only users will get confused while navigating the screen.

**Attachment for Reference:**
[7595_A11y_AzureDataStudio_AddNewController_Keyboard.pptx](https://github.com/microsoft/azuredatastudio/files/3707345/7595_A11y_AzureDataStudio_AddNewController_Keyboard.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by 12-shweta** [comment]
Verified the bug in below environment :
Version: 1.15.0-insider (user setup)
Commit: 041f34b
Date: 2020-01-08T05:36:19.161Z
VS Code: 1.38.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363
Issue is fixed and does not reproduce .
[7595_Closed.pptx](https://github.com/microsoft/azuredatastudio/files/4086039/7595_Closed.pptx)

**Comment by fsteffi** [comment]
#Azure Data Studio - New Features_win32;

**Comment by Rama8345** [comment]
A11ySev2

**Comment by Samhitha66** [comment]
#Closed; Regressed:07-14-23;
