### ISSUE TITLE
Disable unstable test step in ad-hoc daily build

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7610]
We should remove the unstable tests step from the ad-hoc build definition since it's making that step fail.

**Comment by aaomidi** [comment]
The ad-hoc build supports users specifically wanting to run builds with unstable tests. Should we disable that functionality for users to pick?

**Comment by kburtram** [comment]
We can leave the step in the build definition so it can be manually enabled if desired.  For recurring DRI reports we'll switch to using the canary builds for pipeline health to avoid the noise caused by the PR variations in the ad-hoc pipeline.
