### ISSUE TITLE
Spark submit options for reference jar file 

### ISSUE THREAD

**Issue by sfweller** [microsoft/azuredatastudio#7615]
Issue Type: <b>Bug</b>

It isn't clear to end-user which dialog entries to use when submitting a pyspark job that uses a reference jar file.
First upload a reference jar file, like the following:
https://spark-packages.org/package/databricks/spark-sklearn

Then create a python script with some code in it and upload it to a SQL Server big data cluster into HDFS. 

Sample code:
from sklearn import grid_search, datasets
from sklearn.ensemble import RandomForestClassifier
# Use spark_sklearn’s grid search instead:
from spark_sklearn import GridSearchCV
digits = datasets.load_digits()
X, y = digits.data, digits.target
param_grid = {"max_depth": [3, None],
              "max_features": [1, 3, 10],
              "min_samples_split": [1, 3, 10],
              "min_samples_leaf": [1, 3, 10],
              "bootstrap": [True, False],
              "criterion": ["gini", "entropy"],
              "n_estimators": [10, 20, 40, 80]}
gs = grid_search.GridSearchCV(RandomForestClassifier(), param_grid=param_grid)
gs.fit(X, y)

It isn't obvious to the end user that the following dialogs need to have the input:
Hi Stephen,
 
Is this a (1) scala spark application that references a python file? Or a (2) pyspark application that references a jar file?
 
For (1), set jar file in general tab, and python file in “referenced py files” in advanced tab.
 
For (2), set py file in general tab, and jar file in “referenced jar files” in advanced tab.

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T18:08:50.974Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (32.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.11.0

</details>

**Comment by ellbosch** [comment]
Thanks for your feedback @sfweller. This appears to be an enhancement rather than a bug (but a good improvement nonetheless) so I'll tag it as such.
