### ISSUE TITLE
Azure data studio can't be installed on mac os catalina

### ISSUE THREAD

**Issue by deshi9012** [microsoft/azuredatastudio#7620]
- Azure Data Studio Version:

Steps to Reproduce:

1. I've tried to install Azure Data Studio.app version: 1.12.1 on mac os catalina. The zip was downloaded from the official site.
2. When trying to start the app it gives me this error: 
![image](https://user-images.githubusercontent.com/11408215/66547984-075a2900-eb49-11e9-9c3a-cb6092e8529d.png)

**Comment by reaction1989** [comment]
This is probably because now only 64bit apps are working

**Comment by reaction1989** [comment]
@deshi9012 My last comment was wrong..

There is a easy fix.

try to open it then go to
--> Settings
--> Security

there stands that it was blocked from starting. Here you can allow it

**Comment by deshi9012** [comment]
Oh yes, thank you! That was helpful,  now it works!

**Comment by patelmurtuza** [comment]
I am unable to find the Settings Security in my MacBook Air. Can you please help me out to fix it MacBook Air.

**Comment by Charles-Gagnon** [comment]
@patelmurtuza - If you go to the System Preferences do you see a section for Security & Privacy? I don't have a Macbook air to check on myself unfortunately but it should hopefully be there

**Comment by mrzTo** [comment]
System Preferences --> Security & Privacy
ignore "Security" tab, go to  "General"
