### ISSUE TITLE
Unit tests failed from timeout in Windows REL build on 10/10

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7630]
Unit tests failed from timeout in Windows REL build on 10/10.  Still investigating the root cause.

**Comment by aaomidi** [comment]
This is the same exact thing we were seeing on the hosted machines.

**Comment by kburtram** [comment]
We've disabled the unit tests on Windows and are waiting for Electron 6 upgrade. 

See https://github.com/microsoft/azuredatastudio/issues/7739
