### ISSUE TITLE
Jupyter book save notebook adds extra '.ipynb' on Windows

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#7641]
This issue happens on running a notebook in a Jupyter book. Saving shows 2 .ipynb suffixes on Windows:

![image](https://user-images.githubusercontent.com/10819925/66607688-a7c04580-eb69-11e9-9e87-87f9bf57575e.png)

@MaddyDev can you look into this?

**Comment by MaddyDev** [comment]
Fixed https://github.com/microsoft/vscode/issues/83603
