### ISSUE TITLE
Cell output now shows string that starts with "FloatProgress..."

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7645]
![notebook-msgs](https://user-images.githubusercontent.com/10999577/66611650-13a7ab80-eb74-11e9-845a-cb57927ce314.png)
Issue Type: <b>Bug</b>

Test a notebook that has output by executing the cell.

Azure Data Studio version: azuredatastudio-insiders 1.12.0-insider (93c9426f25e632e8e3dd6e572d48d559ae07a7bf, 2019-10-10T18:18:16.586Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (16.09GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by chlafreniere** [comment]
Fixed by #7849.
