### ISSUE TITLE
Match Server Group Color with Color Tabs

### ISSUE THREAD

**Issue by fdacumos** [microsoft/azuredatastudio#7648]
Issue Type: <b>Feature Request</b>

As a user that has a Server Group setup with colors associated with the Server Group, when I run a "New Query" from the selected Server in the Server Group, the "New Query" tab should be color coded to match the color of the Server Group.

Example:
I have the following Server Groups configured:
DEV (Color Green)
QA (Color Blue)
PROD (Color Red)

If I select a Server under the "DEV" Server Group and select "New Query", it will be helpful if the Tab for the New Query is green.  This way it's easy to tell which Tabs belong to which Server Group.

Azure Data Studio version: azuredatastudio 1.12.1 (cccb9327c707fe71de24d5ce655acb29cc8946d1, 2019-10-07T21:49:53.568Z)
OS version: Windows_NT x64 10.0.16299

**Comment by cmmizer** [comment]
@fdacumos I think this feature exists already. There is a setting to enable it.

![image](https://user-images.githubusercontent.com/42183463/67804008-849bfe00-fa64-11e9-9fda-863603a91908.png)

**Comment by cheenamalhotra** [comment]
Closing as feature exists.
