### ISSUE TITLE
Request: "Copy result" should copy more formats than plain text

### ISSUE THREAD

**Issue by akdor1154** [microsoft/azuredatastudio#7655]
**Is your feature request related to a problem? Please describe.**
When I copy results from Azure Data Studio into an email, the results are formatted as TSV. I believe this is because ADS only provides plaintext values on the clipboard.

**Describe the solution or feature you'd like**
I'd like the results to be formatted as a table. E.G. I think this can be achieved by providing a suitably formatted `text/html` target to the clipboard on Mac/Linux, alongside the `text/plain` target.

**Additional context**
Running Azure Data Studio on Linux and pasting into Outlook Web in Firefox. Clipboard contents checked with python hackery.

**Comment by ellbosch** [comment]
May be related to #7189.

**Comment by aaomidi** [comment]
This is a good feature to have but not currently in the scope of ADS. You're welcome to provide this as a PR :)

**Comment by akdor1154** [comment]
don't think this is related to 7189, but I will have a peek if I get time.

**Comment by alanrenmsft** [comment]
close as dupe of https://github.com/microsoft/azuredatastudio/issues/168
