### ISSUE TITLE
Database Dashboard only opens in a tab, and not under the server-name in the connections window

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#7679]
Issue Type: <b>Bug</b>Docking the Database Dashboard/Object Explorer - 

In the GUI, before the update today, in the left window of Azure Data Studio I could click on the server connection to view a database object and expand it to see the individual attributes/columns.  The table/attribute explorer window went away. 

In this 1.12.2 version, the "database dashboard" only opens in a tab, and not under the server-name in the connections window.  

Viewing tables and columns is a basic and important feature for doing SQL development and writing queries.  Where is it?  

Please move it back to under the server name in the "Connections" pane.

Version: 1.12.2 (system setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by ooriblestsmshemir** [comment]
Update:  Upon restart of Data Studio, the database/attribute explorer returns to the "connections" pane.

Problem only appears in session immediately connected with the version update.

Exit/restart of the application restores desired behavior!

**Comment by Charles-Gagnon** [comment]
@ooriblestsmshemir I'm not sure I understand the issue here - could you include a screenshot/gif of the issue you have?

**Comment by ooriblestsmshemir** [comment]
The "Connections" tab normally shows the database, schema, tables, views, attributes, etc in a tree structure.

Sometimes this tree-structure completely goes away, and I can't find a way to get it back.  The database connection is still active and I can continue to run queries.  The only way to get the tree-structure back is to close and re-open Azure Data Studio.

The database object tree-structure is almost necessary for me to do development.  It's not reasonable to have all the objects and hierarchies memorized.

Next time this happens, I will grab a screenshot and any other information.

(It would also be tremendously useful to be able to drag and drop object names from to the query window, like other SQL IDE's can.  I created another request for this functionality.)

**Comment by alanrenmsft** [comment]
based on the comment history, the main issue that @ooriblestsmshemir reported is no longer reproducing and the suggestion about drag and drop column to query editor is being tracked by this issue: https://github.com/microsoft/azuredatastudio/issues/8335.

closing the issue for now.
