### ISSUE TITLE
Schema Compare Results Disappear

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#7680]
Issue Type: <b>Bug</b>

When using Schema Compare on the Insiders Build, after the compare process completes, the results disappear.  However, comparing the same databases using the non-Insiders build, the results are visible.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (6.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
powershell|ms-|2019.9.0
profiler|Mic|0.10.0
query-history|Mic|0.1.0
schema-compare|Mic|0.6.0
server-report|Mic|0.2.0
sql-vnext|Mic|0.13.1
vscode-kubernetes-tools|ms-|0.1.18
sqlops-debug|ms-|1.3.0
azdata-sanddance|msr|1.3.7
vscode-docker|Pet|0.5.2
sql-search|Red|0.3.4
vscode-yaml|red|0.3.0

</details>

![image](https://user-images.githubusercontent.com/18595280/66663485-d2b5a280-ec18-11e9-9fcb-b9da2b1b4af4.png)

**Comment by SQLvariant** [comment]
![ADS - Schema Compare Blank in Insiders 2019-10-11](https://user-images.githubusercontent.com/18595280/66663785-4fe11780-ec19-11e9-8de3-88e22d08d0af.jpg)
Looks like my screenshot didn't upload with the initial post.

**Comment by aaomidi** [comment]
Fixed with https://github.com/microsoft/azuredatastudio/pull/7549

Insiders build should have this fix. It will also be included in the november release.
