### ISSUE TITLE
Choose/Click Attributes and Drag to Query Window

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#7683]
Desired Functionality:
-- From the "Connections" pain, normally on the left, expand a connection to view individual columns/attributes
-- In a table/view, choose one or more attributes and drag to the query window
-- Fully qualified column/attribute names populate to the query window. (table_name.attribute_name)
-- Normal functions of the ctrl and shift keys work with no surprises
-- Attributes are comma delimited
-- Ability to select: database name, table name, view name, column name, etc.
-- Reference the functionality in the Teradata SQL Assistant, and others.

It's time consuming and  unproductive to manually type all the attribute names.  I can be so much more productive by semi-automating the chosen attributes.  

Dragging and Dropping is normal behavior in 2019, even in Chrome/Electron!

Thank you...

**Comment by yualan** [comment]
Closing as Dupe: https://github.com/microsoft/azuredatastudio/issues/3630
