### ISSUE TITLE
Sort in Results Pane - Ascending and Descending - Multiple Columns

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#7691]
As a data analyst, when I run a query and the database responds with results, I want to be able to choose a column and sort the results to better understand the data.

Some icons, like an up-arrows and down-arrows, should be displayed in the column header.  When I click on one of the arrows I want the data to be sorted appropriately, either ascending or descending.

The sort operation should be done in the cached result set, and not re-query the database.

 The icons should be small.  If I click on the column header to either view or copy the results, the sort action should not happen by accident.

Commonly, I would like to sort by more than one column.  It would be nice to be able to choose columns sequentially and for Azure Data  Studio to support sorting on more than one column, in the order chosen.

Sort order is important for data interrogation and learning.  It wastes time to have to rerun the query and use the "ORDER BY" to do the sorting, or copy/paste the data to Excel.

**Comment by ellbosch** [comment]
Thanks @ooriblestsmshemir for your feedback! Closing this since we have the same request tracked at #4934.
