### ISSUE TITLE
Highlight Entire Row - When I Click on Row Number

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#7696]
I want for Azure Data Studio to highlight the entire row when I click on one or more row numbers.

When a result set has been returned from a database query, each row is numbered on the left.

I need to examine the contents of groups of rows for data exploration.

I also want to ctrl-c/copy the rows into the operating system's clipboard, with the column headers, and paste into a text editor or Excel.  Probably the columns should be tab-delimited.

**Comment by aaomidi** [comment]
Can you click Help -> About and copy the information there into this issue?

**Comment by ooriblestsmshemir** [comment]
Version: 1.12.2 (system setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by Charles-Gagnon** [comment]
These features already exist - you can click/ctrl+click on the row numbers to select the whole row and then ctrl + c or right click -> Copy to copy the contents into the clipboard. Do you have a scenario where this isn't working as expected?

**Comment by aaomidi** [comment]
Next release should contain the fix.

**Comment by ooriblestsmshemir** [comment]
Hi Team,

Let me add another comment/clarification.

When we run a query and the results open in the "results" window, the left-most column is the calculated sequential row-number.  For example, if the query returns 100 rows, Azure Studio numbers each row from 1 to 100.

If I click on one row, that one row is highlighted across the result set, even when/if the results extend beyond the right window margin.

I want to be able to click on multiple rows, and for Azure studio to select the multiple rows.

When I scroll right, to view more columns of the result set, the row numbers dissipear.  I want for the row numbers to remain fixed to the left margin and be available to identify rows and to enable me to click on the row numbers and highlight/choose the rows I'm interested, no matter the left/right scroll position.

When doing data discovery, it's important to visually look at the details of the data, to make sure the queries are correct.  These are features that the .Net-based Teradata SQL Assistant has, and I miss the features.
