### ISSUE TITLE
Open Editors list does not match open editors

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#7706]
I closed a few open but unsaved editors and when I finished I noticed that the one editor I do have open is not listed in the open editors, but one which is closed is.

![image](https://user-images.githubusercontent.com/8250560/66690695-a31d8f00-ec46-11e9-80b4-8afae550a6c8.png)

Double clicking on the one which wasn't really opened rehydrated it, but also added a list item for another editor I had already closed (notebook 1) which is also not open

![image](https://user-images.githubusercontent.com/8250560/66690722-d4965a80-ec46-11e9-8d65-9c7c2107158d.png)

Double clicking on Notebook 1 gives this error

![image](https://user-images.githubusercontent.com/8250560/66690731-e841c100-ec46-11e9-9044-83d352cff178.png)

Clicking the tab for the original "notebook 2" which I had left open doubled up the deploy notebook in the open editors:

![image](https://user-images.githubusercontent.com/8250560/66690768-1aebb980-ec47-11e9-88c9-27d3532a301e.png)

Clicking between the tabs and clicking on the files in the viewlet shows this odd behavior:

![notebook and open file list tab behavior](https://user-images.githubusercontent.com/8250560/66690823-7c138d00-ec47-11e9-9018-47f98362828a.gif)

Attempting to close the notebook has odd behavior as well:

![close behavior](https://user-images.githubusercontent.com/8250560/66690887-d6ace900-ec47-11e9-98f5-fe6a62ebd764.gif)

**Comment by chlafreniere** [comment]
This was fixed by #7782.
