### ISSUE TITLE
Autocomplete on Spacebar

### ISSUE THREAD

**Issue by Jean-Paul76** [microsoft/azuredatastudio#7707]
Version: 1.12.2 (user setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

Start typing a `SELECT` Statement, e.g. `sele` and press `Space Bar`.

It would be great if one had the option of applying the currently selected autocomplete item when hitting `SPACE`. At the moment the keyword is applied when hitting `ENTER` or `TAB` only.

![Auto Complete Screenshot](https://user-images.githubusercontent.com/22476720/66712663-33bbb280-eda0-11e9-8aa9-aa0e23385238.png)

**Comment by Charles-Gagnon** [comment]
@Jean-Paul76 - Do you have any specific requirement where tab/enter doesn't suffice? We generally follow VS Code for keyboard shortcuts and the behavior they have is that space doesn't complete the suggestion.
