### ISSUE TITLE
Mac OSX Window controls disappear when not in focus

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#7719]
Issue Type: <b>Bug</b>

Observed only with ADS - ignore if intended. 
on Mac OSX 10.15 Catalina

Open Azure Data Studio - Insuders build
Change window focus to another application 
Notice the window controls change

Attaching window screenshot recording

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (6851b2091fbc209250edda48087ea2a32a2c7e43, 2019-10-14T20:50:48.126Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 2|
|Memory (System)|16.00GB (7.08GB free)|
|Process Argv|-psn_0_630938|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
cms|Mic|0.5.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
schema-compare|Mic|0.7.0
sql-vnext|Mic|0.16.0

</details>

[ADS_toolbar_OSX_Catalina.mov.zip](https://github.com/microsoft/azuredatastudio/files/3726769/ADS_toolbar_OSX_Catalina.mov.zip)

**Comment by ellbosch** [comment]
Thanks @angdesign for your feedback. Looks like your recording didn't attach there.

Can you clarify what you mean by the windows controls?

**Comment by angdesign** [comment]
Github unfortunately does not support MP4, but if you go to the URL at the bottom of this post you can see the MP4 that has been compressed into a ZIP file. It looks like this: 
![image](https://user-images.githubusercontent.com/29785331/66854752-c5f5bf00-ef36-11e9-91e4-8c5630f3767d.png)

[ADS_toolbar_OSX_Catalina.mov (1).zip](https://github.com/microsoft/azuredatastudio/files/3730653/ADS_toolbar_OSX_Catalina.mov.1.zip)

**Comment by angdesign** [comment]
Also, my OSX is in dark theme but the application header doesn't seem to inherit the correct dark theme header.

**Comment by ellbosch** [comment]
> Also, my OSX is in dark theme but the application header doesn't seem to inherit the correct dark theme header.

Interesting. I'm currently in dark mode on Mojave and there's no issue there, but maybe with the new dark theme in Catalina there's a bug. @angdesign would you mind creating a new issue in GitHub for this?

**Comment by ellbosch** [comment]
> Github unfortunately does not support MP4, but if you go to the URL at the bottom of this post you can see the MP4 that has been compressed into a ZIP file. It looks like this:
> ![image](https://user-images.githubusercontent.com/29785331/66854752-c5f5bf00-ef36-11e9-91e4-8c5630f3767d.png)
> 
> [ADS_toolbar_OSX_Catalina.mov (1).zip](https://github.com/microsoft/azuredatastudio/files/3730653/ADS_toolbar_OSX_Catalina.mov.1.zip)

Thanks for the upload, I see how the controls in the top left are disappearing there. This smells of an Electron issue here.

**Comment by angdesign** [comment]
New bug for Catalina theme support filed at https://github.com/microsoft/azuredatastudio/issues/7728

**Comment by kburtram** [comment]
This is an upstream issue that should be fixed in one of our dependencies.  We'll pick up the fix in the future once available.  Thanks!
