### ISSUE TITLE
BDC dashboard shows spinning circles when connecting to non-existant controller...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7721]
Issue Type: <b>Bug</b>

1. Setup bdc
2. Connect to controller endpoint
3. Delete bdc
4. Select the same endpoint from #2 and click Manage

You will get error below. However the dashboard is left with spinning circles & ADS keeps spinning in the task manager. Dashboard should quit gracefully and not consume CPU.

Error retrieving BDC status from https://pl-ubuntu-m-0:30180 - connect ECONNREFUSED 10.193.21.90:30180

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (6851b2091fbc209250edda48087ea2a32a2c7e43, 2019-10-14T21:04:50.772Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (11.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

![ads](https://user-images.githubusercontent.com/10999577/66798880-2ef01f00-eec4-11e9-8b54-b07b53250ac7.png)

**Comment by Charles-Gagnon** [comment]
I'll take a look at the behavior when we can't connect to a cluster - that's definitely not ideal behavior.

One question though - what do you mean ADS is "spinning in the background"? It shouldn't be doing anything while it's waiting for the status request to come back so if it's consuming extra CPU cycles that'd be very unexpected behavior.

**Comment by kburtram** [comment]
https://github.com/microsoft/azuredatastudio/pull/8103
