### ISSUE TITLE
Context menu missing in object-list on dashboard

### ISSUE THREAD

**Issue by slamidtfyn** [microsoft/azuredatastudio#7724]
Issue Type: <b>Bug</b>

When using database dashboard to query or edit data no context-menu is available

## Reproduce:
1. Select manage database in context menu
![image](https://user-images.githubusercontent.com/5030609/66833686-8f329f80-ef5c-11e9-80ad-ef6a8301fe5b.png)

2. Right-click on item in object list
![image](https://user-images.githubusercontent.com/5030609/66833719-9c4f8e80-ef5c-11e9-83d9-751d12faa433.png)

### Result:
No context menu is available

### Expected result:
Same context menu as in connections
![image](https://user-images.githubusercontent.com/5030609/66833784-b8ebc680-ef5c-11e9-9ba4-b476513378fb.png)

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (75388cc3afd30f5d69d4e5752b62fda6351b78ca, 2019-10-15T07:48:57.461Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz (16 x 3600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.94GB (11.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.11.0
schema-compare|Mic|0.7.0

</details>

**Comment by ellbosch** [comment]
Thanks for your feedback! I don't believe this is functionality we've enabled yet.

**Comment by slamidtfyn** [comment]
Here is the same functionality in a stable build

![image](https://user-images.githubusercontent.com/5030609/66867152-f8d19e80-ef9a-11e9-8de7-020b1ee37ace.png)

Version info for this screenshot:
Version: 1.9.0
Commit: 78a42e1d112ae3231777722b51eaf44f83ddbe55
Date: 2019-07-10T04:10:29.206Z
VS Code 1.34.0
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Linux x64 5.0.0-29-generic

**Comment by ellbosch** [comment]
Thanks for the update, I'll re-classify this as a bug.

**Comment by smartguest** [comment]
@anthonydresser There were a number of changes made to explorerWidget.component.ts and explorerTree.ts prior to this issue existing. The context menu worked fine in the latest release, but seemingly after these changes were made, the context menu no longer worked. Something is causing the context menu functions to not work properly on the items anymore. I suggest you look into what is preventing the context menu from popping up as this was a feature in previous builds.
