### ISSUE TITLE
Mac OSX Catalina theme support seems broken

### ISSUE THREAD

**Issue by angdesign** [microsoft/azuredatastudio#7728]
Issue Type: <b>Bug</b>

On Mac 10.15 Catalina

Switching the OS theme from light to dark does not seem to influence the application header. See MP4 in ZIP file URL below: 
[OSX_Catalina_theme.mov.zip](https://github.com/microsoft/azuredatastudio/files/3730707/OSX_Catalina_theme.mov.zip)

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (6851b2091fbc209250edda48087ea2a32a2c7e43, 2019-10-14T20:50:48.126Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (5.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
cms|Mic|0.5.0
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
schema-compare|Mic|0.7.0
sql-vnext|Mic|0.16.0

</details>

**Comment by kburtram** [comment]
ADS does not have custom titlebar render support, so this is "by design" in the current release.
