### ISSUE TITLE
BDC Dashboard: Show error message if cluster is down

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7730]
Version 1.13.0-insider (today's)

After downloading latest insiders, a cluster was down, and the entry for the controller endpoint persisted in the BDC viewlet. When I clicked right-click manage, there wasn't an indication that there was an error. Let's show an indication if user is unable to open dashboard.

**Comment by Charles-Gagnon** [comment]
Dupe of https://github.com/microsoft/azuredatastudio/issues/7721
