### ISSUE TITLE
Editor:Tab Size setting ignored

### ISSUE THREAD

**Issue by LarnuUK** [microsoft/azuredatastudio#7731]
Issue Type: <b>Bug</b>

The tab setting appears to now be ignroed, and regardless of what it is set to `2` is used. The setting screen clearly displays `4`, but the bars in the editor are 2 spaces, and 2 spaces are inserted on pressing <kbd>Tab</tab>.

Changing the setting does nothing apart from update the value in `settings.json` and in the settings menu. Closing and opening the application also does not change it. Regardless of settings, the inserted number of spaces is **always** 2.

Azure Data Studio version: azuredatastudio 1.12.1 (cccb9327c707fe71de24d5ce655acb29cc8946d1, 2019-10-07T19:16:03.172Z)
OS version: Linux x64 5.0.0-31-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4299)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.58GB (0.19GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
vsc-material-theme|Equ|30.0.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.43.0
cms|Mic|0.5.0
dacpac|Mic|0.6.0
managed-instance-dashboard|Mic|0.3.8
profiler|Mic|0.9.0
schema-compare|Mic|0.6.0
server-report|Mic|0.2.0
material-icon-theme|PKi|3.9.0
sql-search|Red|0.3.4

</details>

**Comment by LarnuUK** [comment]
OK, so it seems to be related to files that are already open **only** or opening files from the file system.. A new file will use the setting, however, open files appear to use a random setting and files opened from the file system appear to be set to 2.

**Comment by LarnuUK** [comment]
Further information, turns out the issue was due to the `editor.detectIndentation` setting, which was `true`. Although I can understand that this *might* override when the setting for `editor.tabSize` isn't set, when it is, I feel it shouldn't.

Even if it does intentionally override the setting in `settings.json` for the user settings it should not where it has been set at a workspace level. The setting in the workspace has been set for a reason, and `editor.detectIndentation` should not be overriding that.

**Comment by abist** [comment]
@LarnuUK This issue comes upstream from VS Code. I would recommend opening this issue against them.

**Comment by LarnuUK** [comment]
> @LarnuUK This issue comes upstream from VS Code. I would recommend opening this issue against them.

I was, in truth, expecting that to be the response. :/
