### ISSUE TITLE
BDC dashboard has too much whitespace...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7742]
![ads](https://user-images.githubusercontent.com/10999577/66888512-c07a9200-ef93-11e9-914d-56f183d15129.png)

Issue Type: <b>Bug</b>

see attached picture for an example of buttons with empty spacing/icons in wrong place.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (75388cc3afd30f5d69d4e5752b62fda6351b78ca, 2019-10-15T07:48:57.461Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (12.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by Charles-Gagnon** [comment]
https://github.com/microsoft/azuredatastudio/pull/7732 is fixing the buttons - was there anything else specifically that you think could use an improvement? Really appreciate the feedback, thanks!

**Comment by Charles-Gagnon** [comment]
I'm going to close this for now - if you think there's additional work to be done then let me know and I'll reopen!
