### ISSUE TITLE
Copied result values contain tab character

### ISSUE THREAD

**Issue by oskaremil** [microsoft/azuredatastudio#7743]
Version: 1.12.2 (user setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Copy a cell value from the result set
1. Paste the cell value somewhere else
1. Notice that the pasted contents contain a tab character

**Comment by Charles-Gagnon** [comment]
This should be fixed with https://github.com/microsoft/azuredatastudio/issues/7480 so I'm going to close this - let us know if you still encounter this issue after the next stable version is released!
