### ISSUE TITLE
'Create or Alter' Syntax not recognized by intellisense

### ISSUE THREAD

**Issue by ClutteredSchema** [microsoft/azuredatastudio#7745]
Issue Type: <b>Bug</b>

The 'Create or Alter' syntax isn't recognized by intellisense while window is set to the MSSQL flavor of SQL

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.81GB (1.95GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
agent|Mic|0.43.0
import|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|0.6.0
server-report|Mic|0.2.0
sql-vnext|Mic|0.16.0
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.4
simple-data-scripter|sea|0.1.0

</details>

![image](https://user-images.githubusercontent.com/56141426/66920708-d61ea480-eff1-11e9-9d47-0d326aa42b73.png)

**Comment by Charles-Gagnon** [comment]
Hm, this doesn't seem to repro for me. Can you try typing in this simpler script to see if you still see the red squigglies? If you mouse over them what do they say?

```
create or alter procedure procTest
as
begin
 print (1)
end
go
```

![image](https://user-images.githubusercontent.com/28519865/66935420-ca7eae00-eff0-11e9-9d31-a1f55664d4c6.png)

**Comment by ClutteredSchema** [comment]
Thanks for looking into this!

![image](https://user-images.githubusercontent.com/56141426/66970476-b0c68080-f05b-11e9-9e52-33eb521b5d77.png)

**Comment by Charles-Gagnon** [comment]
Ah, yup that was the key. Let me dig into it and see why - that definitely shouldn't be behaving like that on Azure. Thanks for the follow-up!
