### ISSUE TITLE
Bug: Cannot install Azure Data Studio on macOS Catalina 10.15

### ISSUE THREAD

**Issue by cyclesouth** [microsoft/azuredatastudio#7747]
- Azure Data Studio Version: 1.12.2

Steps to Reproduce: I am unable to install 1.12.2 to MacBook Pro running macOS Catalina 10.15 (19A602). Provided with the following message:

“Azure Data Studio” can’t be opened because Apple cannot check it for malicious software.

Downloaded latest version from here: https://docs.microsoft.com/en-us/sql/azure-data-studio/download?view=sql-server-ver15

**Comment by aaomidi** [comment]
Apple updated their software signing requirements and we haven't yet fixed this.

https://apple.stackexchange.com/questions/366542/install-spotify-cant-be-opened-because-apple-cannot-check-it-for-malicious-so

Here is a way to bypass this new security requirement. I'll see what we need to do to get "notarized" by Apple.

**Comment by Charles-Gagnon** [comment]
@aaomidi - You missed adding the actual instructions 😄 This should do it though - 

Try to open it then go to
--> Settings
--> Security

You can allow it from that dialog

**Comment by aaomidi** [comment]
@Charles-Gagnon it seems like that's not the way anymore on Catalina? I can't confirm either way.

**Comment by ellbosch** [comment]
We need to do this https://developer.apple.com/developer-id/

**Comment by ellbosch** [comment]
@cyclesouth there is a workaround to this issue—please open System Preferences -> Security -> General and then try to re-open Azure Data Studio. You should see a security check pop up regarding Azure Data Studio and prompts you if you'd still like to open it. Select "Open Anyway" to grant permission, and now you may open the app. You should only need to do this once.

We're working on fixing this, but hopefully the steps above will unblock you. Please let us know if you run into any other problems.

**Comment by andysousa** [comment]
Any update on this, unfortunately our MDM policy doesn't allow us to override these types of warnings via the security tab in the system preferences

**Comment by aaomidi** [comment]
Following this in #8642
