### ISSUE TITLE
Cannot close the connection dialog when connecting to a Azure db with wrong password

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#7750]
1. Login to Azure with a valid account. (and some existing SQL dbs)
2. from the viewlet, clinet on a SQL DB to connect to (it's possible I had old password for that db stored in my machine)
3. the connection dialog opens with "login failed' error and to get the correct  password  
4. entering the wrong password shows the same error. I didn't have the correct password so I canot say it will connect correcly 
5. try to close the dialog by clicking on the "Cancel" button

Expected: the dialog should close
Actual: I keep getting the connection error dialog and I cannot close the connection dialog

**Comment by Charles-Gagnon** [comment]
@aaomidi Maybe https://github.com/microsoft/azuredatastudio/commit/5da0e16e440a3991cc2caac6cd68697ac8985d52 broke this? Not sure what the behavior was before, could you check to see if it's related?

**Comment by abist** [comment]
I have verified that this was fixed. The same issue was tracked here - https://github.com/microsoft/azuredatastudio/issues/7051 and it was fixed by https://github.com/microsoft/azuredatastudio/pull/7711
