### ISSUE TITLE
Unable to create new connection

### ISSUE THREAD

**Issue by AkilanRagavaswamy** [microsoft/azuredatastudio#7760]
- Azure Data Studio Version:

Steps to Reproduce:

1. Close existing connection
2. Clear all recent connection and saved connections
3. Try creating new connection

![image](https://user-images.githubusercontent.com/27795412/66996046-99d06e80-f0ed-11e9-9cf9-9329c4051d1e.png)

**Comment by aaomidi** [comment]
I've been unable to reproduce this. If anyone has a repro please send in a comment :)
