### ISSUE TITLE
Error Renaming File in SQL Book - Insider Build

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#7761]
![ADS-SQLBook-error](https://user-images.githubusercontent.com/18595280/67005535-cca84180-f0b0-11e9-9bca-9e93da2d877c.jpg)
Issue Type: <b>Bug</b>

I'm receiving this error when I try to install this morning's update of the ADS Insiders build.  I just hit Ignore, but wanted to call it out in case anyone else is running into it?

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (82963ad075ba3c19e76437758c6dcef543770d55, 2019-10-17T07:39:57.538Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
cms|Mic|0.5.0
import|Mic|0.11.0
managed-instance-dashboard|Mic|0.3.8
powershell|ms-|2019.9.0
profiler|Mic|0.10.0
query-history|Mic|0.1.0
schema-compare|Mic|0.7.0
sql-dw|Mic|0.0.1
vscode-kubernetes-tools|ms-|1.0.2
azdata-sanddance|msr|1.3.9
vscode-docker|Pet|0.6.1
sql-search|Red|0.3.4
vscode-yaml|red|0.4.1
plan-explorer|Sen|0.9.6

</details>

![ADS-SQLBook-error](https://user-images.githubusercontent.com/18595280/67005489-b601ea80-f0b0-11e9-97f5-6542ca53a5ba.jpg)

**Comment by jtsom** [comment]
Same error here.

**Comment by jtsom** [comment]
Also, aborting the install breaks the application:

![image](https://user-images.githubusercontent.com/13488/67008217-0ed48180-f0b7-11e9-8d07-945509bb12e0.png)

**Comment by ellbosch** [comment]
For anyone running into this issue—please hit **Ignore** when you see the error. Installation should proceed without errors. Sorry about this!

**Comment by chlafreniere** [comment]
This was fixed by #7772
