### ISSUE TITLE
Notebook - Inconsistent UI to clear results/output

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#7763]
- Azure Data Studio Version: 
```
Version: 1.13.0-insider (system setup)
Commit: 82963ad075ba3c19e76437758c6dcef543770d55
Date: 2019-10-17T07:39:57.538Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
```

Steps to Reproduce:

1. Open ADS
1. Create a new notebook
1. Add code block
1. The top bar shows `Clear Results`
1. The menu on the code block shows `Clear Output`

The menu on the code block should show `Clear Results` to be consistent.
![image](https://user-images.githubusercontent.com/11204251/67020892-71804a00-f0c4-11e9-95ed-1db19cda367b.png)

**Comment by chlafreniere** [comment]
Just wanted to say that I love this bug 😄. Thanks so much for reporting it; we'll get a fix for this discrepancy out soon.
