### ISSUE TITLE
Database dashboard shows wrong content while doing certain actions...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7767]
![ads](https://user-images.githubusercontent.com/10999577/67039346-fde73880-f0d5-11e9-95f0-d2a588bc08fe.png)

Issue Type: <b>Bug</b>

1. Open BDC dashboard
2. Open database dashboard
3. Click back button in the mouse or some other way to go to dashboard from #1
4. Click back to database dashboard and you should be presented with screen with blank content

This also happens in other ways when you try to view these dashboards. Content will randomly disappear.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (82963ad075ba3c19e76437758c6dcef543770d55, 2019-10-17T07:39:57.538Z)
OS version: Windows_NT x64 10.0.18999

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.53GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by kenvanhyning** [comment]
No repro (or fixed indirectly) on latest insiders (10/24).  Verified with UC that not happening on his setup as well.  Closing now
