### ISSUE TITLE
Don't open files that we know are causing crashes - Working with big files (3,5 GB)

### ISSUE THREAD

**Issue by zvorko** [microsoft/azuredatastudio#7768]
Issue Type: <b>Bug</b>

Working with big files (3,5 GB)

I opened a big tSQL file (3.5 GB) and Azure Data Studio opened a dialog box and wanted to increase memory usage of the program and I said OK and set it to 4096 as the program suggested. I did a couple of small changes to the file and saved it and it was ok.

I turned off the studio and was not able to open the studio since. Each time I open it the big file opens up (because I left it open when I closed the studio) and the studio crashes in approximately 15 sec. 
I tried closing the file and studio before the crash.
I tried to lower memory usage.
I deleted the original location of the big file.

No matter what I do, the big file always opens on start and the studio crashes after 15 sec. I am guessing it is being processed on startup and it crashes during that time.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment]
You can set the application back to the default state by deleting `%APPDATA%/azuredatastudio/`

Please keep in mind if you do this ALL your settings would be reset.

If you wish to ONLY close the files you have open, go to the aforementioned path and look for a file called `storage.json`. In that file you can delete the `openedPathsList` key entirely (just make sure you don't mess up the json file format). 

Thank you for reporting this to us. We should create a safemode start or no-files start when we detect crashes multiple times.

**Comment by zvorko** [comment]
deleting the key `openedPathsList` didn't help. Still opens the files.

**Comment by zvorko** [comment]
I had to delete the file from this directory also %APPDATA%\azuredatastudio\Backups. After that it is working.

**Comment by aaomidi** [comment]
Thanks for finding that out!
