### ISSUE TITLE
In "New Spark Job" flow user cannot provide other fields declared in livy batch REST API

### ISSUE THREAD

**Issue by shanyu** [microsoft/azuredatastudio#7778]
**Is your feature request related to a problem? Please describe.**
For batch Spark job submission flow, we can only provide the main file and class, and referencing jars or py files. There is no way to specify, for example driverMemory, executorMemory and other Spark configurations.

**Describe the solution or feature you'd like**
Please provide a list of parameters in addition to “Main Class” and “Arguments” declared in “POST /batches” REST API:
driverMemory	Amount of memory to use for the driver process	string
driverCores	Number of cores to use for the driver process	int
executorMemory	Amount of memory to use per executor process	string
executorCores	Number of cores to use for each executor	int
numExecutors	Number of executors to launch for this session	int
queue	The name of the YARN queue to which submitted	string
conf	Spark configuration properties	Map of key=val

**Describe alternatives you've considered**
No alternatives.

**Comment by Charles-Gagnon** [comment]
Done

![image](https://user-images.githubusercontent.com/28519865/96620065-c8ae9100-12bb-11eb-8676-0696f6a90b96.png)
