### ISSUE TITLE
PowerShell Notebooks should allow all cells to execute in the same PowerShell session

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#7779]
Currently each code cell in a PowerShell Notebook fires of a new execution of PowerShell or pwsh, each time the cell is executed.  PowerShell Notebooks should allow all cells to execute in the same PowerShell session as every other cell in the Notebook.  That way, a variable can be populated in one code cell, and the values of that variable can be reused in a subsequent code cell.

**Comment by SQLDBAWithABeard** [comment]
This makes a lot of sense, will also enable users to fill in variables at the top of the notebook for their own environment and make use of them throughout the notebooks

**Comment by chlafreniere** [comment]
This will be fixed very, very soon 😄

**Comment by chlafreniere** [comment]
Fixed by #7972
