### ISSUE TITLE
Horizontal Scroll Bar in Results Pane does not Page Left or Page Right

### ISSUE THREAD

**Issue by mjcataldi** [microsoft/azuredatastudio#778]
## Configurations
- SQL Operations Studio Version: 0.26.7
- OS Version: Windows 10 Home Edition

## Steps to Reproduce
- Use [ScriptSample.txt](https://github.com/Microsoft/sqlopsstudio/files/1755611/ScriptSample.txt) to create a sample database and table.
- Expand Results Pane up to reveal horizontal scroll bar (Issue #222).
- Click on the Page Right area to demonstrate issue.

## Screenshot
![inkedmessagesupmorerows_li](https://user-images.githubusercontent.com/22238259/36637432-5428ca32-19a1-11e8-954a-d7e45275a181.jpg)

**Comment by alanrenmsft** [comment]
I tried to repro the issue, and I am able to make the scroll work when I click on the horizontal scrollbar, it has been a while, maybe the issue has been fixed, please reopen if you are able to repro the issue with latest Azure Data Studio build.
