### ISSUE TITLE
"Editor input was null" when opening Server Dashboard for BDC

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7787]
Connect to SQL (w/ BDC) via master.

Right click on server in OE --> Manage

c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280 editor input was null
console.(anonymous function) @ c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:2280
onConnectionChanged @ queryActions.ts:751
ListDatabasesActionItem._register.connectionManagementService.onConnectionChanged.params @ queryActions.ts:617
fire @ event.ts:580
_notifyConnectionChanged @ connectionManagementService.ts:871
onConnectionChangedNotification @ connectionManagementService.ts:866
$onConnectionChangeNotification @ mainThreadDataProtocol.ts:483
_doInvokeHandler @ rpcProtocol.ts:398
_invokeHandler @ rpcProtocol.ts:383
_receiveRequest @ rpcProtocol.ts:299
_receiveOneMessage @ rpcProtocol.ts:226
RPCProtocol._protocol.onMessage @ rpcProtocol.ts:101
fire @ event.ts:580
fire @ ipc.net.ts:453
_receiveMessage @ ipc.net.ts:733
PersistentProtocol._socketDisposables.push._socketReader.onMessage.msg @ ipc.net.ts:592
fire @ event.ts:580
acceptChunk @ ipc.net.ts:239
ProtocolReader._register._socket.onData.data @ ipc.net.ts:200
listener @ ipc.net.ts:28
ZoneDelegate.invokeTask @ c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:421
Zone.runTask @ c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:188
ZoneTask.invokeTask @ c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:496
ZoneTask.invoke @ c:\azuredatastudio\node_modules\zone.js\dist\zone-node.js:485
emit @ events.js:182
addChunk @ _stream_readable.js:283
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onStreamRead @ internal/stream_base_commons.js:94

@aaomidi @udeeshagautam is there any chance this is related to the weird test issues we see with this error?

**Comment by kevcunnane** [comment]
Charles take a look and close if cannot repro

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this so I'm going to close it out for now. Reopen if you still see this later on!
