### ISSUE TITLE
Many Icons for SQL Agent Toolbars aren't Showing

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7788]
Looks like the icons for Agent aren't showing up in a number of places. Here are a couple of examples:
![image](https://user-images.githubusercontent.com/40371649/67064786-aa4e0c80-f120-11e9-8c40-af45b78809bb.png)

![image](https://user-images.githubusercontent.com/40371649/67064792-b043ed80-f120-11e9-9dfc-10f626dd66f2.png)

**Comment by Charles-Gagnon** [comment]
@abist This should be fixed, please go through and verify that they're showing up correctly now.

**Comment by Charles-Gagnon** [comment]
Also - why was this in the planning milestone? This kind of thing is a pretty critical issue so I would have expected it to be in the current release milestone.

**Comment by abist** [comment]
Because there was no other tag other than November.

**Comment by abist** [comment]
@chlafreniere Looks like this issue is fixed, so I'm going to close this issue. If you have a specific repro to get to this state, please let me know.
