### ISSUE TITLE
A11y_AzureDataStudio_ManageAccessForFile_AI4D:Name property does not exist for check box.

### ISSUE THREAD

**Issue by V-sheman** [microsoft/azuredatastudio#7799]
GitHubTags: #A11y_AzureDataStudio;#A11yMAS; #A11yTCS;#SQL Azure Data Studio;#WCAG4.1.2;#WCAG4.2.1;#WCAG1.3.1;#DesktopApp;#Win32;#AI4D;

**Environment Details:**

Application Name: Azure Data Studio

Version: 1.12.0-insider (user setup)

Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7

Date: 2019-10-03T08:56:27.454Z

VS Code: 1.38.0

Electron: 4.2.10

Chrome: 69.0.3497.128

Node.js: 10.11.0

V8: 6.9.427.31-electron.0

OS: Windows_NT x64 10.0.18362

 

**Additional Details:**

Tool Name : AI4D

 

**Steps to Reproduce:**

1. Install and Launch the application the azure data studio application.

2.Connet to the servers with the required credentials.

3.Navigate to the control panel and click on the “Jupyter books” icon. 

 4.Navigate till HDFS folder and right click on it and click on manage access.

5. Hover on the check box with the help of AI4D 

**Actual:**
Name property does not exist for all the check box on the screen.

 

**Expected:** 
Name property should exist for Check box.
 

**User Impact:**
Screen reader user will not able to coonect with the check box as  there is no name for the check box.

**Attachment for Reference:**
[7799A11y_AzureDataStudio_ManageAccessForFile_AI4D.pptx](https://github.com/microsoft/azuredatastudio/files/3750170/7799A11y_AzureDataStudio_ManageAccessForFile_AI4D.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by hannahqin** [comment]
Looks related to https://github.com/microsoft/azuredatastudio/issues/7605

**Comment by vinodbk197** [comment]
Verified the issue in Version: 1.15.0-insider (user setup)

The issue is resolved, Hence closing this  bug

**Comment by V-sheman** [comment]
![image](https://user-images.githubusercontent.com/56344899/73456216-83e27300-4397-11ea-96df-c74b6d8e0982.png)

**Comment by fsteffi** [comment]
#Azure Data Studio - New Features_win32;

**Comment by sspatil123** [comment]
#A11ySev2;
