### ISSUE TITLE
Problematic code

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#7805]
This code is potentially problematic as it doesn't check where live.com, etc etc actually lives in - this would think `examplelive.com` is Microsoft.

**Comment by Charles-Gagnon** [comment]
What code?

**Comment by aaomidi** [comment]
ugh i said reference code in a new issue and I guess it just didn't. Will find it again

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/blob/master/extensions/azurecore/src/account-provider/azureAccountProvider.ts#L400-L404

**Comment by aaomidi** [comment]
Solved.
