### ISSUE TITLE
A11y_AzureDataStudio_Selectthedeploymentoptions_ScreenReader : VoiceOver is not announcing column header word for column name 

### ISSUE THREAD

**Issue by V-sheman** [microsoft/azuredatastudio#7820]
GitHubTags: #SQL Azure Data Studio;#A11y_AzureDataStudio;#A11yMAS;#A11yTCS;#WCAG1.3.1;#DesktopApp;#Voice Over;#Mac;
Environment Details:
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit: 32df727
Date: 2019-10-08T19:18:43.743Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: MACOS MOJAVE Version 10.14.6(18G87)
**Additional Details:**
VoiceOver
**Steps to Reproduce :**
Install /Launch the application Azure data studio.
Navigate to connections and click on more action button.
Select “Deploy SQL Server big data cluster” from more action drop down.
Click on “Deploy SQL Server big data cluster”.
 Start Voice over and observe the announcement.
**Actual:**
 VoiceOver is not announcing header word for column name.
**Expected:**
 VoiceOver is should announcing column header word for column name.
**User Impact:**
Screen reader User will not able to relate with the header.
**Attachment for Reference:**
[7820_A11y_AzureDataStudio_Selectthedeploymentoptions_ScreenReader.pptx](https://github.com/microsoft/azuredatastudio/files/3742995/7820_A11y_AzureDataStudio_Selectthedeploymentoptions_ScreenReader.pptx)
Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
no audio from the pptx file, but if i understand it correctly, you are expecting the voiceover to read the word "column name", which is not something we can control, according to VoiceOver documentation, you can use VO + C + C to let VO announce the column name and it works.
