### ISSUE TITLE
Deploy dialog isn't vertically scrollable

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#7828]
- Azure Data Studio Version: master

Steps to Reproduce:

1. Make ADS vertically small so not all the contents of the deploy dialog can fit on the screen
2. Open the deploy dialog and try to scroll down to the additional options

Expected:
- Scroll works as normal
Actual:
- Stuck unless you make it tall enough! 

@alanrenmsft  can you take a look?

![image](https://user-images.githubusercontent.com/10819925/67118980-f6d62e00-f19a-11e9-9e6d-7ebba92afc7a.png)

**Comment by kevcunnane** [comment]
@alanrenmsft I think you fixed this with recent accessibility changes? Can we close?

**Comment by alanrenmsft** [comment]
yes, fixed.
