### ISSUE TITLE
Error when Loading Deployment Wizard for BDC

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#7847]
I see the following error message on my screen when attempting to load the deployment wizard for BDC:
![image](https://user-images.githubusercontent.com/40371649/67165759-cf6b9680-f33d-11e9-985a-4b00f3eaa787.png)

**Comment by chlafreniere** [comment]
@alanrenmsft can you take a look?

**Comment by aaomidi** [comment]
Guessing its this: 

https://github.com/microsoft/azuredatastudio/blob/4dd6db57ee5e01841d84eed805a59c1b4fab1cd1/e
xtensions/resource-deployment/src/services/azdataService.ts#L43

**Comment by alanrenmsft** [comment]
@chlafreniere I think you don't have latest cu1 azdata installed?

**Comment by chlafreniere** [comment]
Almost certainly. Is there a way to do just sanity error checking (or check the version of azdata)?

**Comment by alanrenmsft** [comment]
@chlafreniere  azdata --version

**Comment by alanrenmsft** [comment]
it should be 15.0.2070

**Comment by chlafreniere** [comment]
Right. Can we ensure that that version is enforced before opening the wizard?

**Comment by alanrenmsft** [comment]
@ranasaria  I am assigning this to you to implement the minimum version check.

**Comment by ranasaria** [comment]
yeah, Alan and I were discussing about this need for this version check last week. I will take a look at this during the coming week.

**Comment by Charles-Gagnon** [comment]
How do we get the latest version of azdata? Following the instructions on https://docs.microsoft.com/en-us/sql/big-data-cluster/deploy-install-azdata?view=sql-server-ver15 just gives me 15.0.1900

**Comment by alanrenmsft** [comment]
solved offline.
