### ISSUE TITLE
Application crashes when creating a new folder in "Save as Excel"

### ISSUE THREAD

**Issue by mpkarlo** [microsoft/azuredatastudio#7853]
Issue Type: <b>Bug</b>

1. Run a Query against a SQL Server Database.
2. Click the "Save Results as Excel" button in the Results pane.
3. On the Save File Dialog, browse to the desired directory.
4. Click the "New Folder" button.

Expected Result:
A new directory is created in the current path, the new directory is called "New Folder" and is selected for renaming.

Actual Result:
The application dialog window hangs, becomes unresponsive and eventually the entire Azure Data Studio crashes. The query used is lost as well as the result.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7- 4860  @ 2.27GHz (4 x 2261)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|16.00GB (9.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by anthonydresser** [comment]
@kburtram can you repro? This seems to work fine on my local machine.
