### ISSUE TITLE
Unsaved Queries Get Deleted

### ISSUE THREAD

**Issue by mattedsonpalmer** [microsoft/azuredatastudio#7854]
Almost every time I start writing a new query and start writing code the entire tab gets deleted before I have a chance to save. This has been very frustrating. Aside from this issue I am a big fan of Data Studio, but unfortunately feel like I cannot use it any more with bugs like this

**Comment by Charles-Gagnon** [comment]
@mattedsonpalmer - That's very unusual - could you explain more about the situation? Does the entire tab disappear or just the text contained within it?

If you could use a tool such as ScreenToGIF to capture this in action that would help us understand the issue as well.

What version of ADS do you have that this is occurring on?
