### ISSUE TITLE
Insiders app menu bar icon is still stable version

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7870]
![image](https://user-images.githubusercontent.com/28519865/67249844-03b68400-f41e-11e9-9ba4-56d44ebe57e6.png)

Need to investigate where this is defined.

**Comment by chlafreniere** [comment]
Take a look at window-appicon and src\vs\workbench\browser\parts\titlebar\media\titlebarpart.css

**Comment by Charles-Gagnon** [comment]
Fixed
