### ISSUE TITLE
Common Property tests are disabled

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#7881]
Disabled since we are currently removing a lot of the properties for stable builds. Should be re-enabled once those are added back in.

https://github.com/microsoft/azuredatastudio/blob/master/src/vs/platform/telemetry/test/electron-browser/commonProperties.test.ts

**Comment by aaomidi** [comment]
The original link here is dead since it refers to your branch.

**Comment by anthonydresser** [comment]
The test that you skipped was deleted by vscode so I don't think this still applies.

**Comment by Charles-Gagnon** [comment]
Re-opening since I still want this for the other tests we disabled. Those should be able to be re-enabled after we fix the telemetry events.

**Comment by kburtram** [comment]
Closing older issues.  Please reactive if this is tracking something that is planned to be resolved at some point.
