### ISSUE TITLE
We should add option to export HDFS data to local system 

### ISSUE THREAD

**Issue by sfweller** [microsoft/azuredatastudio#7893]
It would be useful from a usability  standpoint to add an option to export HDFS data to the local file system by right-clicking on the HDFS directory to ADS notebooks while connected to a SQL big data cluster.

**Comment by Charles-Gagnon** [comment]
You can save individual files locally already using the **Save** action :

![image](https://user-images.githubusercontent.com/28519865/67317664-3e242d80-f4bf-11e9-96de-faa7ce58221c.png)

Is there a specific case you're looking at that isn't covered by this already?
