### ISSUE TITLE
Previously created notebook opens in code mode upon restart

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7899]
![ads-nb-code](https://user-images.githubusercontent.com/10999577/67321743-c8bb5b80-f4c4-11e9-9263-d37fb49bbc73.PNG)

Issue Type: <b>Bug</b>

See attached picture. I created a new notebook, edited, quit ADS and opened again. The previously edited notebook that was not saved now shows as code.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (65fb77ef5ce93fa1090033fe31606138b8059bbc, 2019-10-22T10:25:42.157Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E7-8890 v2 @ 2.80GHz (4 x 2793)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|24.00GB (17.88GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
Moving to November for now; if repro rate is too low, we can move out to planning, as we see this occasionally.

**Comment by kburtram** [comment]
Closing older issues without recent repos.  Please reactive if this is still occurring on current builds.  Thanks!
