### ISSUE TITLE
bdc dashboard stopped working

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7920]
I clicked around within the dashboard, nothing crazy, after a few clicks, it stopped responding and I got the following error in the console: 
![Screen Shot 2019-10-22 at 4 19 13 PM](https://user-images.githubusercontent.com/13777222/67342719-d1715900-f4e7-11e9-919c-220b2cfb2ee7.png)

**Comment by Charles-Gagnon** [comment]
I'm not able to repro this myself - let's wait until we get a build with the builtin version as expected and see if you can repro it again. I wouldn't be hugely surprised though - there's a lot of DOM stuff happening with clicks and I can easily see some race condition occurring.

**Comment by Charles-Gagnon** [comment]
I'm going to close this - if we see this again or more consistently we can reopen.
