### ISSUE TITLE
Notebook: Kernel switching gets stuck

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#7923]
Issue Type: <b>Bug</b>

I noticed that changing the kernel in an ADS Notebook gets stuck sometimes. 
![image](https://user-images.githubusercontent.com/7318752/67344629-69be0c80-f4ed-11e9-9b7e-bd5b48b7abe8.png)

To get a consistent repro I did the following:
- Choose Powershell kernel
- Add a code cell and add a Powershell command like "Get-Command".
- Run the code cell
- Repeat the following loop:
    - Change kernel to Python
    - Run same code cell (should get an error here)
    - Change kernel back to Powershell
    - Run the same code cell (should succeed now)

Within 2-5 times of the above loop I am able to get into a state where kernel switching gets stuck.

Azure Data Studio version: azuredatastudio 1.13.0 (05a53af085861999ed8dc99596cd55829387d490, 2019-10-22T07:41:49.347Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 3192)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.85GB (39.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
big-data-cluster|Mic|0.0.1
resource-deployment|Mic|0.0.1

</details>

**Comment by chlafreniere** [comment]
I haven't tested this myself but it's possible that #7974 could help alleviate this.

**Comment by chlafreniere** [comment]
Neither @qifahs nor I can repro this anymore, so moving back to planning.

**Comment by chlafreniere** [comment]
Since this no longer reproes, closing.
