### ISSUE TITLE
Error while closing a script that I did not want to save

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#7927]
Issue Type: <b>Bug</b>

No idea how to repro. I had few T-SQL windows open, typed some queries, hibernated my laptop, resumed it later & closed the unsaved T-SQL windows. After that, I got error below:

Unable to open 'SQLQuery_2 - pl-min...cadmin)': Cannot read property 'length' of null.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (65fb77ef5ce93fa1090033fe31606138b8059bbc, 2019-10-22T10:25:42.157Z)
OS version: Windows_NT x64 10.0.19002

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (10.82GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

</details>

**Comment by kburtram** [comment]
Closing older issues that don't have recent repro reports.  Please let us know if this issue is still impacting your use case.
