### ISSUE TITLE
Should be able to drag database table to the code editor, to instead of typing table name

### ISSUE THREAD

**Issue by Cyberspirit** [Microsoft/azuredatastudio#793]
- SQL Operations Studio Version:
Version 0.26.7
Commit 723c7cb3bfd80d87fc8a1141632089cd4808495c
Date 2018-02-16T21:34:47.034Z
Shell 1.7.11
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
Steps to Reproduce:

**Comment by anthonydresser** [comment]
dupe #296
