### ISSUE TITLE
Not able to launch ADS in my macOS dev environment

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#7930]
I am getting the following error in the console, also this only happens for master branch.

[19:22:23] Using gulpfile ~/Documents/git/azuredatastudio/gulpfile.js
[19:22:23] Task never defined: electron

**Comment by aaomidi** [comment]
`yarn gulp electron` 

isn't a command anymore

`yarn electron` is the new one

**Comment by alanrenmsft** [comment]
looks like it was fixed by: https://github.com/microsoft/azuredatastudio/commit/a94cbb528e04466a9dbcbd516f007ce53c5c2bee#diff-12f5d74829adb8a1730711c8ac4a2af5R28 

let me give it a try.

**Comment by MaddyDev** [comment]
@alanrenmsft  Can you verify and close this if it's fixed. Thanks!

**Comment by alanrenmsft** [comment]
verified.
