### ISSUE TITLE
Cell selection behavior is inconsistent

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#7931]
I'm seeing inconsistent and weird behaviors when copying irregular selections in the query results.

![selectionbug](https://user-images.githubusercontent.com/6411451/67359422-0bf2ea00-f518-11e9-884a-7ab0e0298f9c.JPG)

![selectionbug2](https://user-images.githubusercontent.com/6411451/67359462-157c5200-f518-11e9-9f38-92734f5a6bfb.JPG)

**Comment by aaomidi** [comment]
This is currently working as intended @abist. We don't preserve ordering of the rows.

If you paste this into excel it'd look much better.

@yualan we should come up with a good way to order these weird selections, right now its essentially random.

**Comment by abist** [comment]
@aaomidi @yualan I have a good implementation of the copy-selection behavior in the mssql extension. We could make the behavior consistent across all tools.
