### ISSUE TITLE
 A11y_Deploymentconfigurationtemplate_Usability:Unclear finctionality of the "1" button for screen reader users

### ISSUE THREAD

**Issue by V-sheman** [microsoft/azuredatastudio#7945]
GitHubTags: #A11y_AzureDataStudio;#A11yUsable; #A11yTCS;#SQL Azure Data Studio;#DesktopApp;#Win32;#NVDA;
Application Name: Azure Data Studio
Version: 1.12.0-insider (user setup)
Commit:6582debd7388b1be512fc3a9b956d3e54f6115e7
Date: 2019-10-03T08:56:27.454Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362
Additional Details:
Tool Name : Keyboard
Steps to Reproduce:
1.	Install /Launch the application Azure data studio.
2.	Navigate to connections and click on more action button.
3.	Select “Deploy SQL Server big data cluster” from more action drop down.
4.	Click on “Deploy SQL Server big data cluster” .
5. Navigate to step 1 button.
Actual:
While navigating a content through tab navigation screen reader announce the button as 1 but after activating the same no any predictions are identified clearly for screen reader users as well as focus remains on the same control.
**Expected:**
After activating the same no any predictions are identified clearly for screen reader users as well as focus remains on the same control.
User Impact:
 Screen reader users finds difficult to identify the input purpose as well as functionality associated with it.
**Attachment for Reference:**
[7945_A11y_Usability_Deploymentconfigurationtemplate.pptx](https://github.com/microsoft/azuredatastudio/files/3761948/7945_A11y_Usability_Deploymentconfigurationtemplate.pptx)

Does this issue occur when all extensions are disabled?: Yes

**Comment by alanrenmsft** [comment]
this is for Grade B (Usability), i am going to leave this open until we are planning to get to level B.

**Comment by alanrenmsft** [comment]
closing as won't fix since this is not accessibility grade c blocker.

**Comment by V-sheman** [comment]
Science this is usability issue we can not take any action at this point of time.
