### ISSUE TITLE
Can't "edit Data" when tablename contains '$'

### ISSUE THREAD

**Issue by AppaOmega** [microsoft/azuredatastudio#7947]
- Azure Data Studio Version: 1.12.2

Steps to Reproduce:

1. Create a table that contains $ in the tablename
2. right click on table -> Edit Data
3. Get an error massage

**Comment by MaddyDev** [comment]
Can you please post the error message here, thanks.

**Comment by AppaOmega** [comment]
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/3763906/renderer1.log)
