### ISSUE TITLE
Update Accessibility Conformance Documentation

### ISSUE THREAD

**Issue by 12-shweta** [microsoft/azuredatastudio#7948]
#SQL Azure Data Studio;#A11y_AzureDataStudio;#A11yMAS;#A11yTCS;#A11YAAT

Recommendation: "Fix and close other bugs before starting accessibility conformance documentation. Any bug that will not be fixed and closed within SLA must be declared in the AAT. The SLA for this bug is also 60 days."

**Comment by kenvanhyning** [comment]
Closing this issue as "not needed".  We have an active AAT document already in place for ADS that @hannahqin keeps up to date on a regular basis.  ADS is an evergreen product with regular monthly updates.
