### ISSUE TITLE
Copying/Pasting a single value (or single row of values) from results includes trailing Tab

### ISSUE THREAD

**Issue by rharris-ameresco** [microsoft/azuredatastudio#7952]
First, populate the Results pane with values. Next, use Ctrl+C or right-click -> Copy on any value in the results pane. When pasting this value into a notepad or Excel, the value is pasted along with a trailing Tab. Because of this, the end-user can no longer copy a row of values and paste them into an Excel document due to the trailing Tab deleting the data in the row to the right of the pasted area.

Version: 1.12.2 (system setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

CPUs | Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.82GB (7.10GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
ssmskeymap | kev | 1.1.0
admin-pack | Mic | 0.0.2
agent | Mic | 0.43.0
import | Mic | 0.11.0
profiler | Mic | 0.9.0

**Comment by Charles-Gagnon** [comment]
This should be fixed with #7516 so I'm going to close this - let us know if you still encounter this issue after the next stable version is released!
