### ISSUE TITLE
[Controller Dashboard] BDC section stuck in Loading... state without escape

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7956]
![image](https://user-images.githubusercontent.com/30873802/67418524-c7029e00-f57f-11e9-8749-0a0bd477f4ca.png)

I downloaded latest Insiders on 10/23.

I previously had an entry to a controller endpoint displayed in BDC section that had the cluster taken down. When I updated to latest insiders, the BDC section was stuck in a Loading... state.

There doesn't appear to be a way for me to escape loading. If I find more info, will include.

**Comment by Charles-Gagnon** [comment]
@yualan - Does this persist after a restart of ADS? Are there any errors in the dev debug console?

**Comment by Charles-Gagnon** [comment]
Closing until we can find repro
