### ISSUE TITLE
Windows ZIP - Insiders build version outdated

### ISSUE THREAD

**Issue by Bassetts** [microsoft/azuredatastudio#7960]
The "Windows ZIP - Insiders build" linked from the README is version 1.12.2 but all other insiders builds are 1.13.0.

**Comment by aaomidi** [comment]
![image](https://user-images.githubusercontent.com/1465785/67427322-c292b100-f590-11e9-88dc-8fef805698bc.png)

Left side is zip, right side is insiders installed.

**Comment by aaomidi** [comment]
I'm going to close this issue as I don't see this - let me know if you see this issue again and I'll reopen.
