### ISSUE TITLE
Results grids aren't sized proportionally

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#7965]
- Azure Data Studio Version: 1.13

Steps to Reproduce:

1. Open query window and type a query with two results sets
2. Execute query

Expected: results set grids height is split 50%\50% unless the grids are larger than minimum size

Actual: First grid gets disproportionate height

*Note: colored boxes should be same height*
![image](https://user-images.githubusercontent.com/599935/67440614-b584ba80-f5ae-11e9-9ba2-8eab6ec9e665.png)

**Comment by kburtram** [comment]
Another related note is that tab-switching away and back to this editor fixes the sizing issue.

**Comment by aaomidi** [comment]
Fixed for release/1.13

**Comment by aaomidi** [comment]
@kburtram what should we do for this release?

**Comment by kburtram** [comment]
@aaomidi do you know if we have a fix ready for this? Otherwise, I think we can hold this for March.

**Comment by aaomidi** [comment]
@kburtram Not yet, I'll change the milestone.

**Comment by aaomidi** [comment]
I've looked a bit at this problem and I'm not sure what's causing it. @anthonydresser can I assign this to you?

**Comment by aaomidi** [comment]
I've traced the issue to https://github.com/microsoft/azuredatastudio/blob/0405658be76624193055e79c74bda6f2f940721f/src/sql/workbench/contrib/query/browser/gridPanel.ts#L637-L645 so far, I'm not sure if that's relevant but a lot of this code is stuff I don't really understand.

**Comment by kburtram** [comment]
Closing older issues.
