### ISSUE TITLE
Copy from results output is appending tabs to end of data

### ISSUE THREAD

**Issue by Kirlac** [microsoft/azuredatastudio#7969]
- Azure Data Studio Version:
Version: 1.12.2 (system setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Run any select query
2. Highlight some data in the results output
3. Copy the data
4. Paste into text editor
5. Each line has an extra tab character appended to the end

This happens even when selecting the value from a single cell eg. copying a cell containing "Cell Data" will paste as "Cell Data	" as per attached repro gif:
![ads-copy-bug](https://user-images.githubusercontent.com/5118726/67442896-54acbf00-f64e-11e9-94b5-c39a895665d2.gif)

Expected behaviour is to have tabs inserted between cells but not at EOL. Actual behaviour is tab appears to be inserted after every cell

**Comment by Charles-Gagnon** [comment]
This should be fixed with #7516 so I'm going to close this - let us know if you still encounter this issue after the next stable version is released!
