### ISSUE TITLE
After October 19 release copy and paste of grid results now include a tab after every record

### ISSUE THREAD

**Issue by alliedcvil** [microsoft/azuredatastudio#7979]
- Azure Data Studio Version:

Steps to Reproduce:

1. Run any query.
2. Click on record in grid.
3. Copy record.
4. Paste record anywhere else (Notepad, Azure Data Studio query editor, etc.)

You will see a tab after the record.

**Comment by Charles-Gagnon** [comment]
This should be fixed with #7516 so I'm going to close this - let us know if you still encounter this issue after the next stable version is released!
