### ISSUE TITLE
search server list

### ISSUE THREAD

**Issue by sivey42** [microsoft/azuredatastudio#7982]
Issue Type: <b>Feature Request</b>

I have lots of server connections saved in the servers list. It would be great to either be able to search the list, or if the list had focus and I start typing the server name have the focus shift to the correct server as I type - similar to how the object pane in SSMS works.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.17134

**Comment by abist** [comment]
@sivey42 We have a command called `Search: Servers` in the command palette (`Ctrl`/`Cmd` + `Shift` + `P`)
