### ISSUE TITLE
Copy query plan as image to clipboard

### ISSUE THREAD

**Issue by codewithtomi** [microsoft/azuredatastudio#7987]
Issue Type: <b>Feature Request</b>

There is great feature available in ADS, to show Query plan in graphical way.
To learn queries  and plans , it would be great to copy query's  plan to clipboard (and save it furher for learning purposes)

Azure Data Studio version: azuredatastudio 1.11.0 (460c739a8d90bdbbde39e01abfb8ecdc278ea787, 2019-09-06T17:09:00.875Z)
OS version: Linux x64 4.15.0-65-generic

**Comment by erinstellato-ms** [comment]
To save the plan for further learning purposes, right-click on the plan and select Save Plan File.  If you just want an image of the plan, take a screen shot and save it as a file.  Make sure you are using the latest ADS and have query plan viewer enabled to see this functionality.

![image](https://user-images.githubusercontent.com/98599126/194159085-90e27a65-00e3-471c-8ae8-76bef7472803.png)

**Comment by codewithtomi** [comment]
Well, its fine for such small query plan. What about very large plan that take multiple pages horizontally and vertically?

**Comment by codewithtomi** [comment]
@erinstellato-ms Hi. Sorry for me been unclear. The request is to copy query plan to clipboard as IMAGE in png format. So image would contain visual representation of  whole query plan.

**Comment by erinstellato-ms** [comment]
@codewithtomi Ok...but if plan is multiple pages horizontally and vertically, then creating it as an image likely means that the operators are really small and hard to read (see image below for 600 operator plan).  Further, the true value in plans isn't simply the graphical rendering, it's the information embedded in the XML which you can view in the Properties.  I hear your request, but it's not something that we will look to implement.  The work around would be to maximize ADS and the plan within it, and then use the Zoom Out button until you have the entire plan on the screen, and take a screen shot.

![image](https://user-images.githubusercontent.com/98599126/194332113-008c5dc5-4fb1-4d54-8ead-647ff3c8acef.png)
