### ISSUE TITLE
Localized BDC TSG's experience

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#7990]
We need a way to access localized versions of the Troubleshooting Book.

- [x]  Create FW Link
- [ ]  Add books to tigertoolbox
- [x]  Add command palette entry
- [x]  Investigate launching Book from Github through a URL
- [x]  Finalize strings
- [ ]  Create readme for downloading Jupyter Book

**Comment by chlafreniere** [comment]
"Jupyter Books: Get localized BDC troubleshooting book" is the final string

**Comment by chlafreniere** [comment]
Sync'ed with PM Alan and the remaining (PM) tasks will be tracked separately.
