### ISSUE TITLE
Edit Data throws "Prevented webcontent navigation" exception

### ISSUE THREAD

**Issue by dewens12** [microsoft/azuredatastudio#7991]
[error] webContents#will-navigate: Prevented webcontent navigation

**Comment by kburtram** [comment]
@dewens12 is this error message associated with a particular problem in the user experience?  i.e. is this blocking you from being able to do something with the product?

**Comment by dewens12** [comment]
I am using SQL Server 2017. I am trying to edit the data in a table.

**Comment by kburtram** [comment]
@dewens12 thanks.  Just so I understand, when you run edit data command on a SQL Server 2017 table the UI fails to load and you see a pop-up message with this error message and you are unable to edit the data in the table?

**Comment by dewens12** [comment]
That is correct

**Comment by kburtram** [comment]
Thanks @dewens12.  Unfortunately I'm unable to repro this issue based.  Please let me know if you can think of anything else that may be useful in diagnosing the issue.  For example, are there any additional error messages in the "Help -> Toggle Developer Tools" Console?  Is this for all tables or particular tables?  Have you tried reinstalling?
