### ISSUE TITLE
OE Expansion of databases on an Azure SQL DB connection fails

### ISSUE THREAD

**Issue by kenvanhyning** [microsoft/azuredatastudio#7997]
- setup a connection to an azure sql db using default database (i.e. master)
- connect in OE
- expand databases
- Databases node gets element that says "Failed to connect to server <servername>"
- Expanding Logins works fine
- Creating a connection directly to a given database on that same logical server works fine

Tested on ADS Insiders build from 10/24 on Windows
![bug - failed to connect to server](https://user-images.githubusercontent.com/7833721/67528000-2b4f5b80-f66d-11e9-82a1-5529a96c4521.jpg)

**Comment by kburtram** [comment]
@kenvanhyning I wasn't able to repro.  It could be a intermittent connectivity issue to the server.  Did you try disconnect\reconnect on the connection?

**Comment by abist** [comment]
I can't seem to repro this either.

**Comment by kburtram** [comment]
@abist can you follow-up with @kenvanhyning to determine if we need a fix for Nov.  One key question is whether this is a regression from Oct.

**Comment by abist** [comment]
@kburtram Will follow up with @kenvanhyning. For what it's worth, SSMS gives the following error for the specific server having issues - 

![Capture](https://user-images.githubusercontent.com/6411451/67723190-81d3d700-f998-11e9-8d2d-36da75e46874.JPG)

**Comment by kenvanhyning** [comment]
I stepped through this in ADS and it's down in low-level parts of SMO.  It looks to be due to the server having a "paused" database.  SMO is trying to enumerate the databases collection and we are requesting name and status properties.  As SMO is building the items in the collection it is failing on the paused database.  It throws and exception that the login failed to the paused database.

@shueybubbles could you take a look at the SMO code here?  IIRC, you played around a bit with SMO in regards to paused databases a few months back.  

Also curious, around how we are populating the collection here and are we really needing to connect to each database to fill the collection?

Here's the call stack from the exception:
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnection.OnError(System.Data.SqlClient.SqlException exception, bool breakConnection, System.Action<System.Action> wrapCloseInAction) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(System.Data.SqlClient.TdsParserStateObject stateObj, bool callerHasConnectionLock, bool asyncClose) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.TdsParser.TryRun(System.Data.SqlClient.RunBehavior runBehavior, System.Data.SqlClient.SqlCommand cmdHandler, System.Data.SqlClient.SqlDataReader dataStream, System.Data.SqlClient.BulkCopySimpleResultSet bulkCopyHandler, System.Data.SqlClient.TdsParserStateObject stateObj, out bool dataReady) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.TdsParser.Run(System.Data.SqlClient.RunBehavior runBehavior, System.Data.SqlClient.SqlCommand cmdHandler, System.Data.SqlClient.SqlDataReader dataStream, System.Data.SqlClient.BulkCopySimpleResultSet bulkCopyHandler, System.Data.SqlClient.TdsParserStateObject stateObj) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnectionTds.CompleteLogin(bool enlistOK) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnectionTds.AttemptOneLogin(System.Data.SqlClient.ServerInfo serverInfo, string newPassword, System.Security.SecureString newSecurePassword, bool ignoreSniOpenTimeout, System.Data.ProviderBase.TimeoutTimer timeout, bool withFailover) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnectionTds.LoginNoFailover(System.Data.SqlClient.ServerInfo serverInfo, string newPassword, System.Security.SecureString newSecurePassword, bool redirectedUserInstance, System.Data.SqlClient.SqlConnectionString connectionOptions, System.Data.SqlClient.SqlCredential credential, System.Data.ProviderBase.TimeoutTimer timeout) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnectionTds.OpenLoginEnlist(System.Data.ProviderBase.TimeoutTimer timeout, System.Data.SqlClient.SqlConnectionString connectionOptions, System.Data.SqlClient.SqlCredential credential, string newPassword, System.Security.SecureString newSecurePassword, bool redirectedUserInstance) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlInternalConnectionTds.SqlInternalConnectionTds(System.Data.ProviderBase.DbConnectionPoolIdentity identity, System.Data.SqlClient.SqlConnectionString connectionOptions, System.Data.SqlClient.SqlCredential credential, object providerInfo, string newPassword, System.Security.SecureString newSecurePassword, bool redirectedUserInstance, System.Data.SqlClient.SqlConnectionString userConnectionOptions, System.Data.SqlClient.SessionData reconnectSessionData, bool applyTransientFaultHandling, string accessToken) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlConnectionFactory.CreateConnection(System.Data.Common.DbConnectionOptions options, System.Data.Common.DbConnectionPoolKey poolKey, object poolGroupProviderInfo, System.Data.ProviderBase.DbConnectionPool pool, System.Data.Common.DbConnection owningConnection, System.Data.Common.DbConnectionOptions userOptions) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(System.Data.Common.DbConnection owningConnection, System.Data.ProviderBase.DbConnectionPoolGroup poolGroup, System.Data.Common.DbConnectionOptions userOptions) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(System.Data.Common.DbConnection owningConnection, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal> retry, System.Data.Common.DbConnectionOptions userOptions, System.Data.ProviderBase.DbConnectionInternal oldConnection, out System.Data.ProviderBase.DbConnectionInternal connection) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(System.Data.Common.DbConnection outerConnection, System.Data.ProviderBase.DbConnectionFactory connectionFactory, System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal> retry, System.Data.Common.DbConnectionOptions userOptions) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlConnection.TryOpen(System.Threading.Tasks.TaskCompletionSource<System.Data.ProviderBase.DbConnectionInternal> retry) (Unknown Source:0)
System.Data.SqlClient.dll!System.Data.SqlClient.SqlConnection.Open() (Unknown Source:0)
Microsoft.SqlServer.ConnectionInfo.dll!Microsoft.SqlServer.Management.Common.ConnectionManager.InternalConnect() Line 617 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\ConnectionInfo\ConnectionManager.cs:617)
Microsoft.SqlServer.ConnectionInfo.dll!Microsoft.SqlServer.Management.Common.ConnectionManager.Connect() Line 663 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\ConnectionInfo\ConnectionManager.cs:663)
Microsoft.SqlServer.ConnectionInfo.dll!Microsoft.SqlServer.Management.Common.ConnectionManager.PoolConnect() Line 884 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\ConnectionInfo\ConnectionManager.cs:884)
Microsoft.SqlServer.ConnectionInfo.dll!Microsoft.SqlServer.Management.Common.ConnectionManager.GetServerInformation() Line 337 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\ConnectionInfo\ConnectionManager.cs:337)
Microsoft.SqlServer.ConnectionInfo.dll!Microsoft.SqlServer.Management.Common.ConnectionManager.DatabaseEngineEdition.get() Line 273 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\ConnectionInfo\ConnectionManager.cs:273)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.ExecutionManager.GetDatabaseEngineEdition() Line 799 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\ExecutionManager.cs:799)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.Database.DatabaseEngineEdition.get() Line 177 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\DatabaseBase.cs:177)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.Database.GetPropertyMetadataProvider() Line 54 (e:\SqlManagementObjects\src\obj\Microsoft\SqlServer\Management\Smo\netstandard2.0\Gen\Database.cs:54)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.Properties.get() Line 1866 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:1866)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(System.Data.IDataReader reader, bool skipIfDirty, int startColIdx, int endColIdx) Line 1785 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:1785)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.AddObjectPropsFromDataReader(System.Data.IDataReader reader, bool skipIfDirty) Line 1755 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:1755)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.Microsoft.SqlServer.Management.Sdk.Sfc.ISqlSmoObjectInitialize.InitializeFromDataReader(System.Data.IDataReader reader) Line 1744 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:1744)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.CreateNewObjectFromRow(Microsoft.SqlServer.Management.Smo.AbstractCollectionBase childColl, System.Type childType, System.Data.IDataReader reader, int columnIdx, bool isOrderedByID, bool skipOrderChecking) Line 5344 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:5344)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResultsRec(Microsoft.SqlServer.Management.Smo.SqlSmoObject currentSmoObject, Microsoft.SqlServer.Management.Sdk.Sfc.XPathExpression levelFilter, int filterIdx, System.Data.IDataReader reader, int columnIdx, object[] parentRow, bool forScripting, System.Collections.Generic.List<string> urnList, int startLeafIdx) Line 5306 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:5306)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitObjectsFromEnumResults(Microsoft.SqlServer.Management.Sdk.Sfc.Urn levelFilter, System.Data.IDataReader reader, bool forScripting, System.Collections.Generic.List<string> urnList, int startLeafIdx, bool skipServer) Line 4916 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:4916)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.DoDatabaseSpecialCase(Microsoft.SqlServer.Management.Sdk.Sfc.Request levelQuery, Microsoft.SqlServer.Management.Sdk.Sfc.Urn levelFilter, bool forScripting, System.Collections.Generic.List<string> urnList, int startLeafIdx) Line 4543 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:4543)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SqlSmoObject.InitChildLevel(Microsoft.SqlServer.Management.Sdk.Sfc.Urn levelFilter, Microsoft.SqlServer.Management.Smo.ScriptingPreferences sp, bool forScripting, System.Collections.Generic.IEnumerable<string> extraFields) Line 4483 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SqlSmoObject.cs:4483)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SmoCollectionBase.InitializeChildCollection(bool refresh, Microsoft.SqlServer.Management.Smo.ScriptingPreferences sp, string filterQuery, System.Collections.Generic.IEnumerable<string> extraFields) Line 270 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SmoCollectionBase.cs:270)
Microsoft.SqlServer.Smo.dll!Microsoft.SqlServer.Management.Smo.SmoCollectionBase.ClearAndInitialize(string filterQuery, System.Collections.Generic.IEnumerable<string> extraFields) Line 206 (e:\SqlManagementObjects\src\Microsoft\SqlServer\Management\Smo\SmoCollectionBase.cs:206)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SqlDatabaseQuerier.Query(Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoQueryContext context, string filter, bool refresh, System.Collections.Generic.IEnumerable<string> extraProperties) Line 30 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoQueryModel.cs:30)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.OnExpandPopulateNonFolders(System.Collections.Generic.IList<Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode> allChildren, Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode parent, bool refresh, string name, System.Threading.CancellationToken cancellationToken) Line 127 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:127)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.SmoModel.SmoChildFactoryBase.Expand(Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode parent, bool refresh, string name, bool includeSystemObjects, System.Threading.CancellationToken cancellationToken) Line 35 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\SmoModel\SmoChildFactoryBase.cs:35)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.PopulateChildren(bool refresh, string name, System.Threading.CancellationToken cancellationToken) Line 346 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:346)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.Expand(string name, System.Threading.CancellationToken cancellationToken) Line 247 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:247)
MicrosoftSqlToolsServiceLayer.dll!Microsoft.SqlTools.ServiceLayer.ObjectExplorer.Nodes.TreeNode.Expand(System.Threading.CancellationToken cancellationToken) Line 257 (e:\sqltoolsservice\src\Microsoft.SqlTools.ServiceLayer\ObjectExplorer\Nodes\TreeNode.cs:257)

**Comment by shueybubbles** [comment]
I’ve been bugging the DW team about this issue for a few weeks. I need to upgrade it from a bug to a live site issue.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________

**Comment by kenvanhyning** [comment]
Going to close our issue here as it is not on the tools side.
