### ISSUE TITLE
Comment in the last line of Power Shell code block hangs execution

### ISSUE THREAD

**Issue by ebruersan** [microsoft/azuredatastudio#7999]
- Azure Data Studio Version: 1.13.0-insider

Steps to Reproduce:

1.Create a notebook with Power Shell kernel
2. Add code block: 
```PowerShell
write "hello"
# last line being a comment hangs the execution
```

**Comment by chlafreniere** [comment]
Synced and this isn't a demo blocker, so moving this to Planning for now.
