### ISSUE TITLE
Feature request: actual execution plans

### ISSUE THREAD

**Issue by BrentOzar** [microsoft/azuredatastudio#8]
- SQL Operations Studio Version: 0.23.6

When running queries, the "Explain" button gets the estimated execution plan, but there doesn't appear to be a way to get the actual execution plan for a query.

**Comment by JanMulkens** [comment]
There's not more to say, we need this

**Comment by kevcunnane** [comment]
Thanks for your feedback. This is definitely on our roadmap, and hearing strong customer feedback on features helps us prioritize. Please keep the requests coming.

**Comment by kburtram** [comment]
This was planned for the initial release, but didn't fit in the schedule.  We should be able to include this in the Dec. release.

**Comment by BrentOzar** [comment]
Awesome! I figured it had to be close because there's an execution plan viewer for estimated plans.

Feel free to tell me to create another issue for this, but I also noticed that the plan viewer doesn't show when you click on results cells with execution plans (like sp_whoisactive @get_plans = 1, or sp_BlitzCache) the way SSMS does. Don't know if that's part of the same bundle of tweaks or not. Thanks!

**Comment by Matticusau** [comment]
You can just include this before you query and it will automatically load the "Query Plan" tab in the results area.
```
SET showplan_xml ON
GO
```

Agree though that a button to enable this would be nice :)

**Comment by BrentOzar** [comment]
@Matticusau bad news: that's still the estimated plan. For example, hovering your mouse over the operators doesn't show any information about the actual number of rows returned from each operator.

You only get the actual plan by actually running the query.

**Comment by Matticusau** [comment]
Good pick up @BrentOzar that's what I get for rushing to answer ;)

If you include `SET STATISTICS XML ON`  in the query it will return the XML SHOWPLAN as a resultset. 

![image](https://user-images.githubusercontent.com/11083642/32891475-627b5b94-cb1e-11e7-8fbe-28c61bda3496.png)

Then if you click the XML link (same as you would in SSMS), then save that XML to a file with the .sqlplan. You can then open that in SQLOPS. And that is the actual execution plan (unless i am mistaken again)

![image](https://user-images.githubusercontent.com/11083642/32891519-88845336-cb1e-11e7-90fb-25496e9f954e.png)

So SQLOPS does have the ability to display .sqlplan files which is nice, and we can get the actual execution plan XML, just need some UI functionality to tie the two together?

**Comment by BrentOzar** [comment]
Bingo, yep, now you understand the problem!

**Comment by kburtram** [comment]
This build has basic support for viewing an actual query plan https://github.com/Microsoft/sqlopsstudio/releases/tag/v0.24.1.  The release note has a description of the current implementation.  

I didn't have time in Dec. to get the UX how I want it, so finishing this up is planned for Jan.  We'll probably have a toggle toolbar button similar to SSMS, though this we still need to review with our UX designer what pattern to us for "additional query data" scenarios.

**Comment by BrentOzar** [comment]
Woohoo! This is so awesome, thanks! I'm going to play around with it this week and start blogging about it. I really appreciate this! Makes all the difference in the world in me getting it adopted.

**Comment by kburtram** [comment]
I'm going to close this issue out now.  There is a built-in command `Run Current Query with Actual Plan` that will should the actual plan details.  This command can be mapped to a keyboard shortcut if desired.

Also, we now have the **SentryOne Plan Explorer** extension in the marketplace that provides the ability to inspect actual execution plans.  This extension is the recommended solution for this scenario.  Please open issues if problems are encounter with these solutions.  Thanks!
