### ISSUE TITLE
Auto generated Insights of type count include unwanted JSON

### ISSUE THREAD

**Issue by jeffest** [microsoft/azuredatastudio#80]
- SQL Operations Studio Version: sqlops 0.23.6 (8a3011756318a2ded1e6e84332230a2b2bf9c544, 2017-11-06T21:51:43.232Z)
- OS Version: Windows_NT x64 6.1.7601
---

Steps to Reproduce:

1. Run "SELECT 10 AS ColA"
2. Go to Chart Viewer
3. Change type to "count"
4. Click "Create Insight"

What I see:
                "count": {
                    "dataDirection": "vertical",
                    "dataType": "number",
                    "legendPosition": "none",
                    "labelFirstColumn": false,
                    "columnsAsLabels": false
                }

What I expect:
                "count": null

**Comment by EnjoyinMoss** [comment]
Oddly, the tutorial page for custom insights has the incorrect JSON listed in example code and screenshots yet show it to work.  Despite that, the bug described above occurs and switching to null or "vertical" does not remedy the lack of text/value in the dashboard grid.

**Comment by lzimmermann** [comment]
Hi all, this problem still exists in current build, is there any fix expected?
Version 1.3.9
Date 2019-01-14T23:30:09.442Z
VS Code 1.26.1
Shell 2.0.9
Renderer 61.0.3163.100
Node 8.9.3
V8: 6.1.534.41
Architecture x64

**Comment by kburtram** [comment]
@lzimmermann we're planning some improvements in the charting area, though we aren't currently working on this now.  This looks like it should be a pretty simple bug we could pick-up before that.  

Did switching to `"count": null` resolve the problem for you?

**Comment by lzimmermann** [comment]
Hi Karl, thanks for contacting me!

No unfortunitly this did not work, but after all there only seem to be warnings - no errors

And I have a great Thank You for you for Building this tool! It is really a great tool and with the ability to be enhanced that simple ist really woth going Forward with the Development!



Kind regards

Lars Zimmermann



PS:

This is my USER SETTINGS which works but has warnings:

{
    "workbench.enablePreviewFeatures": true,
    "datasource.connectionGroups": [
        {
            "name": "ROOT",
            "id": "C777F06B-202E-4480-B475-FA416154D458"
        }
    ],
    "datasource.connections": [
        {
            "options": {
                "connectionName": "",
                "server": "sqlserver-.database.windows.net",
                "database": "-dev",
                "authenticationType": "SqlLogin",
                "user": "extern",
                "password": "",
                "connectTimeout": 30,
                "applicationName": "sqlops",
                "groupId": "C777F06B-202E-4480-B475-FA416154D458",
                "databaseDisplayName": "dev"
            },
            "groupId": "C777F06B-202E-4480-B475-FA416154D458",
            "providerName": "MSSQL",
            "savePassword": true,
            "id": "c6866d37-235a-4d3d-988c-ef97554e2904"
        }
    ],
    "workbench.colorTheme": "Atom One Dark",
    "dashboard.database.widgets": [
        {
            "name": "Slow Queries Widget",
            "gridItemConfig": {
                "sizex": 2,
                "sizey": 1
            },
            "widget": {
                "query-data-store-db-insight": null
            }
        },
        {
            "name": "Space Used by Tables",
            "gridItemConfig": {
                "sizex": 2,
                "sizey": 1
            },
            "widget": {
                "table-space-db-insight": null
            }
        },


        {
            "name": "My-Widget",
            "gridItemConfig": {
                "sizex": 2,
                "sizey": 1
            },
            "widget": {
                "insights-widget": {
                    "type": {
                        "table": {
                            "dataDirection": "horizontal",
                            "columnsAsLabels": false,
                            "labelFirstColumn": true,
                            "legendPosition": "right"
                        }
                    },
                    "queryFile": "c:\\Users\\larsz\\OneDrive\\Program Files\\ADT Widgets\\WaitTime.sql"
                }
            }
        },



        {
                "name": "Active Sessions",
                "gridItemConfig": {
                    "sizex": 1,
                    "sizey": 1
                },
                "widget": {
                    "insights-widget": {
                        "type": {
                            "count": {
                                "dataDirection": "vertical",
                                "dataType": "number",
                                "legendPosition": "none",
                                "labelFirstColumn": false,
                                "columnsAsLabels": false
                            }
                        },
                        "queryFile": "C:\\Users\\larsz\\OneDrive\\Program Files\\ADT Widgets\\ActiveSession.sql",
                        "details": {
                            "queryFile": "C:\\Users\\larsz\\OneDrive\\Program Files\\ADT Widgets\\ActiveSessionDetail.sql",
                            "label": "SID",
                            "value": "Login Name"
                        }
                    }
                }
            },

            {
                "name": "Slwoest Queries current Hour",
                "gridItemConfig": {
                    "sizex": 2,
                    "sizey": 1
                },
                "widget": {
                    "insights-widget": {
                        "type": {
                            "table": {
                                "dataDirection": "horizontal",
                               "columnsAsLabels": false,
                                "labelFirstColumn": true,
                                "legendPosition": "top"
                            }
                        },
                        "queryFile": "c:\\Users\\larsz\\OneDrive\\Program Files\\ADT Widgets\\RessourceConsumingQueries.sql"
                    }
                }
            }
    ],
}

Von: Karl Burtram<mailto:notifications@github.com>
Gesendet: Mittwoch, 13. Februar 2019 19:16
An: Microsoft/azuredatastudio<mailto:azuredatastudio@noreply.github.com>
Cc: lzimmermann<mailto:lzimmermann@live.de>; Mention<mailto:mention@noreply.github.com>
Betreff: Re: [Microsoft/azuredatastudio] Auto generated Insights of type count include unwanted JSON (#80)


@lzimmermann<https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Flzimmermann&data=02%7C01%7C%7C92d15fe0af084049089008d691df60eb%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C636856785912921479&sdata=9E28TP01xp2PvOw8PZDqbz0xMSnl5pGYGFYDTwwwJjA%3D&reserved=0> we're planning some improvements in the charting area, though we aren't currently working on this now. This looks like it should be a pretty simple bug we could pick-up before that.

Did switching to "count": null resolve the problem for you?

**Comment by kburtram** [comment]
Closing older issues.  We're moving in a slightly different direction with dashboarding and custom widgets in future releases that will resolve problems such as this.
