### ISSUE TITLE
Editor doesn't receive mouse events at correct location after extending the monitor

### ISSUE THREAD

**Issue by ayepez1975** [microsoft/azuredatastudio#8004]
Cuando se extiende la pantalla del monitor y se envia el Azure Data Studio a otra pantalla , al trabajar en el editor y se seleciona un texto con el puntero del mouse , visualmente el cursor se posiciona correctamente pero el Azure Data Studio lo interpreta 3 o 4 a la derecha, para solucionarlo  se tiene que cerrar y abrir nuevamente el Azure Data Studio .

Ejemplo 

K_PROCESO_EVAL_X_CERT, se posiciona el puntero del mouse en el 2do guion bajo, pero el Azure Data Studio interpreta que esta en la letra A, es decir se desplazada 3 a 4 caracteres

**Comment by aaomidi** [comment]
From Google Translate:

When the monitor screen is extended and the Azure Data Studio is sent to another screen, when working in the editor and a text is selected with the mouse pointer, the cursor is visually positioned correctly but the Azure Data Studio interprets it 3 or 4 to the right, to solve it you have to close and open the Azure Data Studio again.

Example

K_PROCESO_EVAL_X_CERT, the mouse pointer is positioned in the 2nd underscore, but the Azure Data Studio interprets that it is in the letter A, that is, it moves 3 to 4 characters

**Comment by kburtram** [comment]
Closing older issues.  This appears to be an upstream issue in Electron as we don't have code that routes mouse-clicks to event handlers directly (this is handled by the upstream platform).
