### ISSUE TITLE
ADS 1.12.2 won't open on Macbook running MacOS Catalina

### ISSUE THREAD

**Issue by danaustralia** [microsoft/azuredatastudio#8013]
- Azure Data Studio Version:
1.12.2
Steps to Reproduce:

1. Double click to open the application on Mac running Catalina.
The attached error message shows up. 
I can successfully run ADS v1.12.1v though.

<img width="424" alt="Screen Shot 2019-10-24 at 9 28 01 pm" src="https://user-images.githubusercontent.com/5178604/67538203-776dc080-f6ac-11e9-8963-990b7eb9a147.png">

**Comment by aaomidi** [comment]
Follow the instructions here https://github.com/microsoft/azuredatastudio/issues/7747
