### ISSUE TITLE
Connected Server asks for credentials in Object Explorer

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8022]
Steps to reproduce -

1. Open Connection Dialog to make a new connection. Intentionally connect to a non-existent server with a new server group.
2. The connection fails but the Server Group is made anyway. (This is another bug).
3. Open Connection Dialog again to create new SQL Login connection with no password saved.
4. Drag and drop the newly made connection to the group that was made in step 1.

**Expected** - The server is under the group and nothing else changes.
**Actual** - The server is under the group but gets in a disconnected state (with red dot) with nodes expanded, and opens Connection Dialog again to make a connection.

**Comment by kburtram** [comment]
I could not repro this bug on current builds.  I was not able to add a server to the Servers list if it failed to connect in Connection Dialog as described in the repo steps.
