### ISSUE TITLE
Document magic code

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#8028]
This code is essentially magic and extremely hard to understand whats happening, a few comments would help explain it:

https://github.com/microsoft/azuredatastudio/blob/613cd58aa3c8b8e8a7e2daa49d90e9ede87d221f/src/sql/base/browser/ui/scrollableSplitview/scrollableSplitview.ts#L771-L835

**Comment by kburtram** [comment]
Closing older engineering tasks to focus on customer facing issues.  Please reactive if this issue is tracking upcoming planned work.
