### ISSUE TITLE
Refresh command in Azure doesn't work when expanding a node

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#8044]
Repro:
- Have a server in Azure where you don't have the DNS name resolving (example: SQL Managed Instance server)
- Expand it, will time out after 1min
- Try to do other things in the meantime (e.g. refresh a list). It's not possible!

**Comment by aaomidi** [comment]
This is a larger issue with the data explorer that I'm going to tackle in December. 

We can either do temporary work around or go and fix the core data explorer code.

**Comment by kevcunnane** [comment]
Please wait and fix properly in a future release 😄 It can wait until then.

**Comment by cheenamalhotra** [comment]
Closing as issue not reproducible anymore
