### ISSUE TITLE
Notebooks View should have actions

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8053]
![Capture](https://user-images.githubusercontent.com/6411451/67702708-75875400-f96f-11e9-8fc5-7e05b555e2fb.JPG)

The Viewlet should add any associated notebook commands as actions contributed to the Viewlet. As a first time user, I didn't know what to do after opening the Notebooks Viewlet

**Comment by nbfritz** [comment]
Confirming, as a first time user of the feature. I have NO idea what the viewlet does, but it shows up as the first one in the list after updating to the November release. I love the burgeoning notebook feature, so I'm generally quite excited, but would be more so if I could actually do something...

**Comment by abist** [comment]
This is now implemented.
