### ISSUE TITLE
English version suddenly switched to Portugese/Spanish

### ISSUE THREAD

**Issue by HugoShebbeare** [microsoft/azuredatastudio#8057]
Nós escrevemos os dados necessários em sua área de transferência porque era muito grande para ser enviado. Por favor, Cole...Nós suportamos Markdown no padrão GitHub. Você poderá editar o seu problema e adicionar capturas de tela quando nós o pré-visualizarmos no GitHub.

I shall reinstall, but just wanted you guys to know that the languages flip on data studio, Windows 10 pro, EN language version.

**Comment by kburtram** [comment]
@HugoShebbeare the ADS display language is stored as a user settings.  You should be able to run the `Configure Display Language` command to reset back to English.  Or if you open your User Settings JSON file you can remove the setting from there.  Please let me know if that doesn't work.  Thanks!
