### ISSUE TITLE
IntelliSense  and underscore in object name

### ISSUE THREAD

**Issue by tekken22** [microsoft/azuredatastudio#806]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 6.1.7601
- Extensions: none
---

Steps to Reproduce:

1. table name tActive_Persons
2. when typing select * from _Pers, IntelliSense will not pickup tActive_Persons

**Comment by kburtram** [comment]
This appears to be working on current builds of ADS.  Please let us know if you're still impacted by this issue.

![image](https://user-images.githubusercontent.com/599935/129613124-b92941d7-237f-4f36-8515-f861f76daed4.png)
