### ISSUE TITLE
Query Editor Tab Executing Indicator

### ISSUE THREAD

**Issue by cmmizer** [microsoft/azuredatastudio#8063]
**Is your feature request related to a problem? Please describe.**
It's not possible to tell if a query is still running on another tab.

**Describe the solution or feature you'd like**
A text or icon indication on the tab when it is executing.

**Describe alternatives you've considered**
Selecting the tab to see if it's still executing.

**Additional context**
![image](https://user-images.githubusercontent.com/42183463/67711332-24d82100-f998-11e9-941d-9caa2dd5c096.png)

**Comment by kburtram** [comment]
Thanks for reporting this issue!  We are tracking here https://github.com/microsoft/azuredatastudio/issues/7686 and will fix in an upcoming release.  Closing as a duplicate.
