### ISSUE TITLE
Error while trying to execute command in T-SQL editor...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8064]
Issue Type: <b>Bug</b>

I just tried to run "select system_user" against a server and got below. The connectivity to this server is bit slow but I don't think that should raise this sort of error.

Execution failed due to an unexpected error: 
	This editor is not connected to a database
Parameter name: OwnerUri
Total execution time: 00:00:00

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (a7f597c9431c2ee82e6175eb744c328e8c680019, 2019-10-28T07:38:19.274Z)
OS version: Windows_NT x64 10.0.19008

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (19.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
Closing older issues.  Please let us know if you're still impacted by this issue.
