### ISSUE TITLE
Command flatFileImport.start not found

### ISSUE THREAD

**Issue by debasisg** [microsoft/azuredatastudio#8066]
Issue Type: <b>Bug</b>

1. Install Extension
2. Ctrl+I or try to find the extension -- not there -- reports "Command flatFileImport.start not found"
3. Also, shows a warning about extension load failure after install.

Ubuntu Version: Linux 5.0.0-32-generic x86_64

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:03:49.463Z)
OS version: Linux x64 5.0.0-32-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (2 x 2903)|
|GPU Status|2d_canvas: unavailable_software<br>flash_3d: disabled_software<br>flash_stage3d: disabled_software<br>flash_stage3d_baseline: disabled_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: disabled_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: disabled_software<br>viz_display_compositor: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|1, 1, 0|
|Memory (System)|7.79GB (1.63GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|40%|
</details>

**Comment by aaomidi** [comment]
Can you share the startup logs?
