### ISSUE TITLE
Check whether release was published in Azure Pipelines

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8069]
Need to add a step that detects a breaking change in the post-pipeline task (release publish) and fails the pipeline if that happens.

**Comment by alanrenmsft** [comment]
@abist can we close the issue now?

**Comment by abist** [comment]
@alanrenmsft Is it automated?

**Comment by alanrenmsft** [comment]
I haven't done anything related to this.  I am going to keep this open

**Comment by alanrenmsft** [comment]
added notification for release pipeline failure.
