### ISSUE TITLE
Cannot change Language Flavor

### ISSUE THREAD

**Issue by swjain23** [microsoft/azuredatastudio#8077]
Unable to change language flavor for .sql files. It shows "Choose SQL Language" in status bar and it is un clickable.

**Comment by aaomidi** [comment]
can you click Help -> About and copy the information here?

**Comment by swjain23** [comment]
![image](https://user-images.githubusercontent.com/36710109/67728714-7047fa80-f9ab-11e9-9893-059c727b2c8f.png)

**Comment by swjain23** [comment]
Some more information: I have PostgreSQL extension installed and I am trying to change the flavor to pgsql.

**Comment by swjain23** [comment]
I tried to debug the problem and 1 issue I see is that in flavorStatus.ts line 150 when we compare (uri === currentUri), the value of current Uri is "file:///d%3A/GitHub/PGExtension/TestDatabase/1ae730a9.sql" whereas the value for uri is "file:///d:/GitHub/PGExtension/TestDatabase/1ae730a9.sql" because of which it returns the default label. 

Even if I kinda fix this by replacing '%3A' with ':' I see that pgsql provider is never returned. So I don't have an option to change to pgsql.

**Comment by swjain23** [comment]
Another find:

If I connect to a PostgreSQL server and run a query, then it shows PGSQL as the flavor and that language server is used. But if I save the query on disk and then open the file, it defaults to MSSQL. So it does not even show PG as an option in file explorer. It looks like it only works when there is a connectionProvider.

**Comment by aaomidi** [comment]
So I think this is by design - you're not supposed to click it. It's supposed to find the language flavor based on the server you have that editor connected to.

**Comment by aaomidi** [comment]
We should probably give the ability to select a flavor from this list based on whatever flavors are registered.
