### ISSUE TITLE
Delay in query execution

### ISSUE THREAD

**Issue by saitheodore** [microsoft/azuredatastudio#8080]
Issue Type: <b>Bug</b>

I am using an On-Prem SQL Server (2016) installation. Whenever I execute a query after connecting to the SQL Server, the first query that I try to execute takes at least 3-4 mins to complete. This happens on different SQL Server instances that I use. The taskbar shows "Executing Query", but the timer beside that stays on "00:00:00" for a good 2-3 mins.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.91GB (7.84GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.11.0
profiler|Mic|0.9.0

</details>

**Comment by alanrenmsft** [comment]
similar to https://github.com/microsoft/azuredatastudio/issues/23145, issue has been fixed in latest insiders build, please give it a try.
