### ISSUE TITLE
Can't connect to database 

### ISSUE THREAD

**Issue by mattedsonpalmer** [microsoft/azuredatastudio#8082]
Issue Type: <b>Bug</b>

When I have a file opened that is linked to a GIT repo it won't let me connect to any SQL DB

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (7.83GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.11.0
schema-compare|Mic|0.6.0

</details>

**Comment by kburtram** [comment]
@mattedsonpalmer are you getting a particular error message?  is there any errors in the "Help->Developer Tools" Console?

**Comment by mattedsonpalmer** [comment]
Hey Karl,

The only message I got was "An unexpected error occurred while connecting".

This only happens when I try connecting while I am on a file that is in a
GIT Repo. If I were to do this in an unsaved notebook or a non GIT file it
is fine

**Comment by Charles-Gagnon** [comment]
@mattedsonpalmer I'm going to close this since we are already tracking this general class of issue in #7897. If you have any other information to add please do so in that one, thanks!
