### ISSUE TITLE
Notebook: When cell execution runs more than 5min, it shows 'kernal is dead'

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#8088]
Issue Type: <b>Bug</b>

Launch the tsg books comand from commnd pallet: SQL Server 2019 Guide
Open the TSG014 notebook under Monitor - Big Data Clusters section.
Run it
run_azdata cell runs for few min and you see the execution stops wtih 'Kernal is Dead' error  notification.

Azure Data Studio version: azuredatastudio-insiders 1.13.0-insider (f8067ffadab178d2929a162408032ff63b0b717b, 2019-10-25T07:42:15.891Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.62GB free)|
|Process Argv|-psn_0_7767912|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
I'm having trouble repro'ing this issue. Let's keep trying though, as this would be pretty bad (even if there's a corner case).

**Comment by chlafreniere** [comment]
We couldn't repro this afterwards. @MaddyDev if you see this again please feel free to reopen.
