### ISSUE TITLE
Mocha J Unit Test Reporter is disabled for now

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8094]
There's an error and a corresponding fix for Mocha JUnit Reporter - https://github.com/michaelleeallen/mocha-junit-reporter/pull/95.

The reporter is disabled until the issue is fixed as it causes Uncaught Promise errors.

**Comment by aaomidi** [comment]
https://github.com/michaelleeallen/mocha-junit-reporter/pull/95
