### ISSUE TITLE
BDC connections doesn't save new password...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8102]
Issue Type: <b>Bug</b>

1. Create bdc with specific admin credentials
2. Add controller endpoint from #1 to BDC connections
3. Delete bdc
4. Create bdc with same username as #1 but different password
5. Connect to endpoint from #2 & click Manage
6. It will show the connections dialog again since password is different. Type new password and hit ok
7. Close bdc dashboard
8. do #5 again, you will be prompted again!!

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (a7f597c9431c2ee82e6175eb744c328e8c680019, 2019-10-28T07:38:19.274Z)
OS version: Windows_NT x64 10.0.19008

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (14.23GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.43.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|0.7.0
import|Mic|0.11.0
profiler|Mic|0.10.0
sql-vnext|Mic|0.16.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
This has been fixed so that it will prompt to reconnect if an error occurs
