### ISSUE TITLE
Could not expand table lists or view lists.

### ISSUE THREAD

**Issue by JEONPPA** [microsoft/azuredatastudio#8106]
- Azure Data Studio Version: 1.12.2

Steps to Reproduce:

1. Click Data Explorer then choice the Database.
2. Expand Tables, Views or etc

When I clicked expanding button that shows Azure Data Warehouse's folders which have tables and views lists, the following error massage occurred
"Failed to retrieve data for this request."
On the other hand, If I do the very same action with SQL Server Management Studio,
it works right. That means SSMS shows me the lists of tables or views . 
Here is a jpeg image file which shows my problem.
I want to know how to solve this problem but I don't want to open Azure Data Studio with administrator permission. 

![GibQuestion](https://user-images.githubusercontent.com/50439244/67836620-71eefb00-fb30-11e9-9821-9fdba0f4d1d0.jpg)

**Comment by JEONPPA** [comment]
Still, I can not solve this problem.

**Comment by cheenamalhotra** [comment]
Closing as stale issue
