### ISSUE TITLE
MacOS icon is very small in dock

### ISSUE THREAD

**Issue by warrior107** [microsoft/azuredatastudio#8107]
Issue Type: <b>Bug</b>

Open the application. It is barely visible in the dock

Azure Data Studio version: Azure Data Studio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:05:05.798Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by warrior107** [comment]
<img width="204" alt="Screenshot 2019-10-31 at 10 55 02 AM" src="https://user-images.githubusercontent.com/8248598/67921170-f2633980-fbcc-11e9-8602-f0f2a420d30f.png">
Attacking screenshot. Tiny icon between firefox and preview icons is the Azure Data Studio icon. Zooming in the image may show the icon.

**Comment by kburtram** [comment]
@warrior107 I haven't seen this before.  It's is supposed to look something like below.  Are you still seeing this after upgrading to 1.13.0?

<img width="391" alt="Screen Shot 2019-11-12 at 9 26 55 PM" src="https://user-images.githubusercontent.com/599935/68735657-412cae00-0593-11ea-9e6d-5cee44df1d6c.png">

**Comment by warrior107** [comment]
@kburtram, I am not seeing this issue after updating to 1.13.0
I can now see it as shown above in your image.
Thanks for fixing this.

can I close this issue?

**Comment by DarthXoc** [comment]
I'm seeing the same issues on Version: 1.13.0. After deleting and reinstalling, the issue persists.
<img width="177" alt="Screen Shot 2019-11-14 at 8 01 53 AM" src="https://user-images.githubusercontent.com/6225954/68863474-0d49a980-06b5-11ea-898c-71941efb5a03.png">

**Comment by joshkel** [comment]
I ran into this and was able to fix it by executing `killall Dock`, as described [here](https://apple.stackexchange.com/a/338882/136525).

**Comment by olegueret** [comment]
There is the same bug in Visual Studio Code:
https://github.com/microsoft/vscode/issues/63068

They released a possible fix in the insiders version: https://github.com/microsoft/vscode/issues/63068#issuecomment-634428303

killall Dock fixes the issue.
Before that, I tried uninstalling the app, download again and reinstall, but that doesn't fix it. Reopening Finder also doesn't work.
**When it was uninstalled, the icon still appeared in the Dock** (in the **Recents** list).

I'm on Mojave 10.14.6 (18G4032).

**Azure Data Studio**
Version: 1.18.1
Commit: 5b3b97f4a34018f3b37b0fce30e32f2af7ad78fa
Date: 2020-05-26T21:11:42.467Z (1 wk ago)
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0

![Captura de Pantalla 2020-06-03 a les 12 07 10](https://user-images.githubusercontent.com/49993/83626286-7c291a00-a595-11ea-8788-7dd3d91d1db5.png)

**Comment by abist** [comment]
This is now fixed with the commit - https://github.com/microsoft/vscode/commit/f8f0c0ec5499cf5d210b12672d71784e93d42f0d
