### ISSUE TITLE
Query results take a long time to display while query is executing

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8118]
- Azure Data Studio Version: 1.13.0

Steps to Reproduce:

1. Execute a long running query with lots of results

Expected: Results display while the query is executing

Actual: The grid displays with blank cells for a long time.  Eventual the results will render.  It could take any where from ~20 seconds up to a few minutes for any results to render in the cells.

![image](https://user-images.githubusercontent.com/599935/67891735-6db2e580-fb10-11e9-84df-afabdb142249.png)

**Comment by ek1977** [comment]
I think this is saying the same thing as https://github.com/microsoft/azuredatastudio/issues/7186.  A fix here may fix both issues depending on how its done.

**Comment by kburtram** [comment]
Closing as a duplicate of https://github.com/microsoft/azuredatastudio/issues/7186.
