### ISSUE TITLE
Azdata install error on mac when running tsg notebook sop038. 

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#8119]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open ADS and launch the command "SQL Server 2019 BDC Guide" from command pallet.
2. Open the SOP038 and run it, pip install fails with the below error:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 4969: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command outpu

**Comment by chlafreniere** [comment]
To fix this, we need new versions of the books that set the LC_All environment variable for mac.

**Comment by MaddyDev** [comment]
Stuart has a fix for this and once that's in, I'll refresh the book contents and vbump the package.
