### ISSUE TITLE
Schema compare cannot exclude message missing name of dependant

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#8126]
So far have only noticed it for this case(other excludes show the name of the dependency correctly):

Repro steps:
1. Compare AdventureWorks with something
2. Try to exclude a SqlUser like amy0
3. Fails with this message
![image](https://user-images.githubusercontent.com/31145923/67905652-4ae3f980-fb2f-11e9-815f-65283e3e9447.png)

It's failing because of the SqlRole dependency of SalesPersons, but for some reason the name of the object isn't populated when passed back from the GetExcludeDependencies() call to DacFx.
![image](https://user-images.githubusercontent.com/31145923/67905841-fc832a80-fb2f-11e9-8b77-abe1417b48cb.png)

**Comment by udeeshagautam** [comment]
We can start by fixing the error message before going to DacFx and fixing that
