### ISSUE TITLE
Error installing notebook dependencies breaks Notebook usage

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#8134]
This was encountered by Meet when testing, it seems like we're failing to read JSON from the config file when installing notebook dependencies. This is breaking notebook usage. Workaround was to delete and reinstall the notebook python install. @corivera any ideas how to guard against this?

![image](https://user-images.githubusercontent.com/10819925/67909485-9ea90f80-fb3c-11e9-9c6e-bcb6bc5fbf1e.png)

**Comment by chlafreniere** [comment]
@kevcunnane what's the scenario here? I intentionally installed a lower version of a package that we need, restarted ADS, was prompted, and it installed as expected

**Comment by corivera** [comment]
Where is this json file from? Can we get the rest of the install output?

**Comment by kevcunnane** [comment]
@corivera it wasn't showing any output, so I think it's erroring before that part. Can you & @MaddyDev help investigate?

**Comment by kevcunnane** [comment]
@MaddyDev please send an ASK mode request to get your fix ported over. I believe we should approve given impact on demo-ers.
