### ISSUE TITLE
Can't open relative notebook links on dev build

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8147]
```
Unable to read file (Error: File not found (d:\src\azuredatastudio.build\builtInExtensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\common\sop007-get-key-version-information.ipynb))
```

Looks like we're not concatenating the path correctly. It should be `d:\src\azuredatastudio\.build` Oddly this only seems to be on dev builds though - I'm not seeing this on the release branch nor insiders builds. 

It's in the actual link on the page too - so something is going on when opening the notebook.

![image](https://user-images.githubusercontent.com/28519865/67968617-f8edb300-fbc4-11e9-8958-e47e12c94514.png)

This is what it looks like in the Notebook 

```
    "-   [SOP007 - Version information (azdata, bdc,\n",
    "    kubernetes)](../common/sop007-get-key-version-information.ipynb)\n",
```

**Comment by llali** [comment]
also see the same issue. I see the following error:
![image](https://user-images.githubusercontent.com/17187348/67983435-ec2b8800-fbe1-11e9-9107-6abe3564059e.png)

both notebooks are in same folder. This was working fine a week ago so might be a regression.
