### ISSUE TITLE
Spark kernel using wrong connection

### ISSUE THREAD

**Issue by rajmera3** [microsoft/azuredatastudio#8156]
- Azure Data Studio Version: Insiders and Oct. 30, 2019 Build

Steps to Reproduce:

1. Run a spark notebook while connected to a BDC. Quit ADS and reopen and connect to a new cluster and open the same notebook. The notebook will continue to use the old connection even if it has been disconnected or deleted. 

<img width="1440" alt="Screen Shot 2019-10-31 at 12 41 36 PM" src="https://user-images.githubusercontent.com/22081978/67980761-55a89800-fbdc-11e9-86c3-6529f2431260.png">

In the image above I am connected to 52.170... and ran SQL queries against this BDC. However, when I try to use the Spark kernel, it uses the BDC at https://13.82.....

**This occurs even if you make a new notebook.**

**Comment by alanrenmsft** [comment]
correct the Area label

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
