### ISSUE TITLE
Unable to open 2019 TSG readme's

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8178]
1. Run the **Jupyter Books: SQL Server 2019 Guide** command from the command palette 
2. On the initial readme.md click any of the links under **Chapters**

This error appears and the referenced files aren't opened :

Unable to open 'readme.md': Unable to read file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\file\c:\Users\chgagnon\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\Microsoft.sqlservernotebook\books\sqlserver2019\content\troubleshooters\readme.md').

**Comment by MaddyDev** [comment]
Looking into it,  i tested this and everything worked fine for me.

**Comment by Charles-Gagnon** [comment]
Did you test on master or the release build? I'm testing it with a [release build](https://mssqltools.visualstudio.com/_apis/resources/Containers/1642651?itemPath=drop%2Fuser-setup%2FAzureDataStudioSetup.exe) so let's make sure things are working as expected

**Comment by MaddyDev** [comment]
I tested on the insiders build. Below is the experience:
![welcomeLinksWork](https://user-images.githubusercontent.com/12754347/68038871-1fc0ed80-fc88-11e9-827a-9c8fdc2517d2.gif)

**Comment by Charles-Gagnon** [comment]
Please verify on the release candidate too - there's a lot of changes made to master which might have fixed this issue (if it is indeed an issue)

**Comment by MaddyDev** [comment]
Able to reproduce it on release, checking the code difference. Thanks!

**Comment by Charles-Gagnon** [comment]
The URLs are different when I hover over :

Release : 
![image](https://user-images.githubusercontent.com/28519865/68039564-a4603b80-fc89-11e9-9a2d-5075b8984dc1.png)

Master :

![image](https://user-images.githubusercontent.com/28519865/68039596-b6da7500-fc89-11e9-88f1-a1ff4ba59641.png)

Hopefully that helps figure it out.

**Comment by MaddyDev** [comment]
yea, it was an issue introduced by vscode and they fixed it in the last merge. Looking into how to minimally incorporate the vscdoe merge fix to address this.

**Comment by MaddyDev** [comment]
This is an issue only on the release branch and is fixed on the master branch by the last vscode merge.
