### ISSUE TITLE
Dashboard: Not rendered correctly after you perform a notebook execute task.

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#8186]
Issue Type: <b>Bug</b>

1. Connect to a server and doucle click to open the dashboard.
2. From the tasks widget, click new notebook
3. Select python kernal and add code cell and execute random code ex: 1+1
4. Come back to the dashboard tab.

Expected: You get back to the dashboard tab with tasks as rendered before.
Current Behavior: It renders incomplete screen (ex:below).
![image](https://user-images.githubusercontent.com/12754347/68060870-7eee2480-fcbf-11e9-9c30-f191fcbaac53.png)

Azure Data Studio version: azuredatastudio 1.13.0 (a016c38288d831ed37022ecb147a6bdfb891f016, 2019-11-01T18:14:33.016Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (41.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
I cannot repro this consistently.

**Comment by MaddyDev** [comment]
Am still seeing this issue intermittently:
![image](https://user-images.githubusercontent.com/12754347/69463151-c6505980-0d2f-11ea-845a-35e435ae6588.png)

**Comment by chlafreniere** [comment]
With the dashboard refactor occurring and the fact that we won't get to this before then, let's close this issue for now.
