### ISSUE TITLE
Deploying WideWorldImporters in SQL Server 2019 failed

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#8192]
- Azure Data Studio Version:
1.13.0 (user setup)

Steps to Reproduce:

1. I already had WideWorldImporters database in my server so I exported that to a bacpac in ADS
2. In the same server open "Data tier Application Wizard" and select Deploy
3. Choose dacpac file created from step 1

Expected: the deploy should completed successfully 
Actual: I get the following error:

Deploy dacpac: Could not deploy package.
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 98 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 135 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 172 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 209 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 246 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 283 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 320 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 357 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 394 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 431 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 468 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 505 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 542 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 579 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 616 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 653 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =
Error SQL72014: Core .Net SqlClient Data Provider: Msg 137, Level 15, State 2, Procedure DeactivateTemporalTablesBeforeDataLoad, Line 690 Must declare the scalar variable "@Crlf".
Error SQL72045: Script execution error. The executed script:
CREATE PROCEDURE DataLoadSimulation.DeactivateTemporalTablesBeforeDataLoad
AS
BEGIN
SET NOCOUNT ON;
IF EXISTS (SELECT 1
FROM sys.procedures
WHERE name = N'Configuration_RemoveRowLevelSecurity')
BEGIN
EXECUTE [Application].Configuration_RemoveRowLevelSecurity ;
END
DECLARE @SQL AS NVARCHAR (MAX) = N'';
DECLARE @CrLf AS NVARCHAR (2) = NCHAR(13) + NCHAR(10);
DECLARE @Indent AS NVARCHAR (4) = N' ';
DECLARE @SchemaName AS sysname;
DECLARE @TableName AS sysname;
DECLARE @NormalColumnList AS NVARCHAR (MAX);
DECLARE @NormalColumnListWithDPrefix AS NVARCHAR (MAX);
DECLARE @PrimaryKeyColumn AS sysname;
DECLARE @TemporalFromColumnName AS sysname = N'ValidFrom';
DECLARE @TemporalToColumnName AS sysname = N'ValidTo';
DECLARE @TemporalTableSuffix AS NVARCHAR (MAX) = N'Archive';
DECLARE @LastEditedByColumnName AS sysname;
ALTER TABLE [Application].[Cities] SET (SYSTEM_VERSIONING =

**Comment by udeeshagautam** [comment]
Needs to be fixed in DacFx - same behavior in SSDT.

**Comment by kisantia** [comment]
This error is because the server is case sensitive and this stored procedure declares @CrLf, but both CrLf and Crlf (lowercase L) are used. Importing is successful on a case insensitive server. Nothing to be fixed in DacFx for this one.
