### ISSUE TITLE
Notebook git diff view doesn't render correctly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8195]
- Azure Data Studio Version: 1.13

Steps to Reproduce:

1. Edit a notebook file that's under git source control
2. View diff in git Changes view

Expected: Either a diff of JSON or a graphical notebook that highlighted the diffs

Actual: Side-by-side notebooks with no way to scroll or see diffs

<img width="1230" alt="Screen Shot 2019-11-01 at 11 35 26 PM" src="https://user-images.githubusercontent.com/599935/68067194-a1ecf880-fd00-11e9-87e5-db466226808c.png">

**Comment by retorquere** [comment]
I'm on 1.18, and I just get the diff of the raw JSON (of both the code and the results BTW). It's pretty hard to tell what change I'm checking in this way.

**Comment by retorquere** [comment]
Can https://github.com/jupyter/nbdime be of help here?

**Comment by MsSQLGirl** [comment]
+ @joberume : FYI.

**Comment by MsSQLGirl** [comment]
Adding this feature request #10238 to consider when implementing "diff" experience.

**Comment by chlafreniere** [comment]
This now opens as JSON. Closing this issue as that's our current story. Enhancement for graphical diff experience is tracked by #10238.
