### ISSUE TITLE
Database drop-down is too short

### ISSUE THREAD

**Issue by awojtas** [microsoft/azuredatastudio#8202]
Issue Type: <b>Bug</b>

The database dropdown above a script is too short, it is very hard to tell which database I'm selecting - I have to wait until the tool-tip appears for confirmation.

This is because our database are the product, plus the branch name, e.g. _FeatureSet2, suffixed by _Dev, _Review, etc for the environment. So they all are too long to short fully in the dropdown.

More than one user moving from SSMS to Azure Data Studio has commented on this.

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

**Comment by chlafreniere** [comment]
This is also true for notebooks; we should consider any changes that can apply to both, if at all possible.
