### ISSUE TITLE
Could not display contents: Cell type ssss unknown

### ISSUE THREAD

**Issue by kingtrade32** [microsoft/azuredatastudio#8208]
After updating to version 1.13.0 I tried to open an existing SQL notebook and get the error message:
Could not display contents: Cell type ssss unknown

One on the cells has very large number of characters (about 22000).
i have tried increasing max maxTokenizationLineLengthline length to 1 million but still does not work. This was based on the feedback error "Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.

This all worked prior to this upgrade.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (8.54GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.43.0
cms|Mic|0.5.0
import|Mic|0.11.0
managed-instance-dashboard|Mic|0.3.8
profiler|Mic|0.9.0
query-history|Mic|0.1.0
schema-compare|Mic|0.6.0
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.3

**Comment by kevcunnane** [comment]
@corivera can you help on this? @kingtrade32 if you can help with some (non-sensitive) repro case that would be very helpful. We'll try to repro but might need some assistance.

**Comment by chlafreniere** [comment]
Do you mind sharing a notebook with us?

**Comment by kingtrade32** [comment]
Hi

It works now - only thing I did was reboot my PC.  I cannot reproduce this problem now.
Thanks everyone for the speedy response.
I will close this off now.

Version: 1.13.0 (user setup)
Commit: cacd481bff25c890e4130aee392569bae43b7e60
Date: 2019-11-02T00:40:05.147Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by kingtrade32** [comment]
Hi

It works now - only thing I did was reboot my PC.  I cannot reproduce this problem now.
Thanks everyone for the speedy response.
I will close this off now.

Version: 1.13.0 (user setup)
Commit: cacd481bff25c890e4130aee392569bae43b7e60
Date: 2019-11-02T00:40:05.147Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763
