### ISSUE TITLE
Excel files open in editor instead of excel after exporting result set

### ISSUE THREAD

**Issue by Thallerich** [microsoft/azuredatastudio#8218]
- Azure Data Studio Version: 1.13.0

Steps to Reproduce:
Export result set to excel (via the "Save As Excel"-Button on the right). In the notification that shows after the file has been saved click "Open file".
I get a new tab in Azure Data Studio and the message "The file is not displayed in the editor because it is either binary or uses an unsupported text encoding. Do you want to open it anyway?".
Clicking on the text link to open the file anyways shows the file as text in the editor instead of opening excel.

**Comment by anthonydresser** [comment]
I'm not sure it makes sense for us to open excel files, its a binary format so we don't really know how to parse that. There is an extension for vscode that knows how to open excel formatted files, we could reach out to that owner and adopt it into our eco system. @kburtram

**Comment by Thallerich** [comment]
@anthonydresser Just to clarify: I don't want to open them in Azure Data Studio, i want to open them in excel.
After exporting data to excel you get a notification with a button to open the file that was just saved. For an excel file this should launch excel, but right now it tries to open the file in Azure Data Studio.

This did work this way before version 1.13, so this should be a bug in my opinion.
