### ISSUE TITLE
Download link for 2019.11 PowerShell extension doesnt work in the ADS Marketplace 

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#8220]
There's an issue with the download link for the 2019.11 PowerShell extension in the November build of ADS.
![tmp_1572973406107](https://user-images.githubusercontent.com/18595280/68229006-6b470480-ffc4-11e9-9025-3d2d64c603fd.jpg)

Version: 1.13.0 (system setup) Commit: cacd481bff25c890e4130aee392569bae43b7e60 Date: 2019-11-02T00:40:05.147Z VS Code: 1.38.0 Electron: 4.2.10 Chrome: 69.0.3497.128 Node.js: 10.11.0 V8: 6.9.427.31-electron.0 OS: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment]
Thanks for the report @SQLvariant  - I'm investigating this now.

**Comment by Charles-Gagnon** [comment]
Alright, should be fixed. Try again now and let us know if you're still having issues! Sorry about that!
