### ISSUE TITLE
error when activating datavirtualization extension

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#8223]
I am seeing the following error

![Screen Shot 2019-11-05 at 11 25 07 AM](https://user-images.githubusercontent.com/13777222/68239140-5156f300-ffbf-11e9-8e45-ac5d0570d8d2.png)

**Comment by aaomidi** [comment]
Which extension is this?

**Comment by Charles-Gagnon** [comment]
I have a fix out to remove the proposed API from that extension since we don't need it anymore, but if we do in the future for this or any other extension then the fix should be just to add it to https://github.com/microsoft/azuredatastudio/blob/master/product.json#L62
