### ISSUE TITLE
Failures during installer creation aren't failing the build

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8226]
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=42865

This build had a failure in the create system installer task but that didn't fail the build. We need to make sure the build fails if any errors such as that occur. 

```
Reading file (WizardImageFile)
   File: e:\mssqltoolsagentworkspace\87\s\resources\win32\inno-big-100-insiders-insiders.bmp
Error on line 23 in E:\mssqltoolsagentworkspace\87\s\build\win32\code.iss: Could not read "e:\mssqltoolsagentworkspace\87\s\resources\win32\inno-big-100-insiders-insiders.bmp".

Error: The system cannot find the file specified.
Compile aborted.
```

**Comment by alanrenmsft** [comment]
updated the build pipeline to enable "Fail on Standard Error"
