### ISSUE TITLE
Filter tables

### ISSUE THREAD

**Issue by ofvargas** [microsoft/azuredatastudio#8228]
Issue Type: <b>Feature Request</b>

I have been using the previous version and now the lattest one, one of the features I missed is been able to filter tables by name, we have plenty tables on a database and I use the filter in SSMS a lot. I like this tool !

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.16299

**Comment by ellbosch** [comment]
Thanks @ofvargas, this is covered in #8052 so I'll close this.
