### ISSUE TITLE
BDC wizard Docker image tag "2019-RC1-ubuntu" needs to change to "latest"

### ISSUE THREAD

**Issue by rl-msft** [microsoft/azuredatastudio#8230]
ADS Deploy SQL server Wizard  > BDC > Docker Sessions Image Tag is set to "2019-RC1-ubuntu", can we update the image tag in that wizard to use "latest" instead of "2019-RC1-ubuntu"?

![bdc wizard](https://user-images.githubusercontent.com/20459971/68245531-84859a80-0030-11ea-9cf3-dc516bec5a19.JPG)

- Azure Data Studio Version:
Version: 1.14.0-insider (user setup)
Commit: c70e7794ebe1bdff82aafc149ae104ba587bd1a6
Date: 2019-11-05T08:55:52.327Z
VS Code: 1.38.0
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by alanrenmsft** [comment]
@rl-msft This value is not hard coded in ADS, it is coming from azdata, I guess you are not using the latest azdata, I am seeing 2019-GDR1-ubuntu-16.04.

**Comment by alanrenmsft** [comment]
latest image tag is not recommended since your local azdata might not work with the latest image out there.

**Comment by rl-msft** [comment]
thank @alanrenmsft
