### ISSUE TITLE
ERR Error while adding account: Error: Entry not found in cache.

### ISSUE THREAD

**Issue by jruckert** [microsoft/azuredatastudio#8236]
Issue Type: <b>Bug</b>

Whilst linking my account, it comes up with the error "ERR Error while adding account: Error: Entry not found in cache." after successful authentication to Azure using the device login.

I am getting the following extension host initalized which I haven't seen before.

[Extension Host] Initialized Azure account extension storage.

My login email address to Azure is also different to my primary email, i'm not sure if this helps.

This has been happening for the last couple of releases and never been successful.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (3.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.44.0
cms|Mic|0.5.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.11.0
profiler|Mic|0.9.0
schema-compare|Mic|1.0.0

</details>

**Comment by onionhammer** [comment]
![image](https://user-images.githubusercontent.com/969938/68334395-242e4180-00a0-11ea-8057-4c0735131ad0.png)


This issue keeps getting posted and getting closed with **not resolution**, stop closing it if it's not fixed.

**Comment by ellbosch** [comment]
Thanks @jruckert and @onionhammer for the feedback. Sorry this hasn't been fixed yet. We currently have this bug tracked at #7619 and scheduled for our December milestone.

Closing this thread to consolidate our conversation to #7619.
