### ISSUE TITLE
Azure Devops

### ISSUE THREAD

**Issue by ehutton** [microsoft/azuredatastudio#8237]
Issue Type: <b>Feature Request</b>

There should be an option to use Azure DEVOPS for source control!

Azure Data Studio version: azuredatastudio 1.10.0 (5fdb967ffcea41df0335ec17cfa396a694bb174e, 2019-08-14T18:28:10.311Z)
OS version: Windows_NT x64 10.0.16299

**Comment by kburtram** [comment]
Closing as duplicate of https://github.com/microsoft/azuredatastudio/issues/16001.  Thanks for opening this suggestion!
