### ISSUE TITLE
Copying individual field results is padded with a trailing tab character

### ISSUE THREAD

**Issue by WilkoSki** [microsoft/azuredatastudio#8238]
Issue Type: <b>Bug</b>

When copying individual field contents from the results window in Azure Data Studio a trailing tabis being appended to the end of the copied content.

e.g.
Copying an Id field (uniqueidentifier)
Field value is 'cabbec01-0592-4ff5-93db-c0f65fee0eba' 
Copied value is 'cabbec01-0592-4ff5-93db-c0f65fee0eba	'

This appears to be fairly recent behaviour.

The version details are as follows:

Version: 1.12.2 (user setup)
Commit: c9bef82ace6c67190d0e83820011a2bbd1f793c1
Date: 2019-10-11T04:56:40.634Z
VS Code 1.37.0
Electron: 4.2.9
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Azure Data Studio version: azuredatastudio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:56:40.634Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (14.63GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by w-corey-masters** [comment]
I was experiencing this issue as well. It appears to have been fixed in the 1.13.0 update. Can you confirm?

**Comment by WilkoSki** [comment]
Yes I can confirm the issue has been fixed in 1.13.0.
