### ISSUE TITLE
Installation bug - wrong username in Users folder

### ISSUE THREAD

**Issue by plsloan** [microsoft/azuredatastudio#8244]
- Azure Data Studio Version: 1.13.0

Steps to Reproduce:

1. Try to run User Installation (or update system-installed version)
2. Accept terms and conditions
3. Click next
4. Click next
5. Click install
6. Observe error

I get 
"
Setup was unable to create the directory "C:\Users\First Last". 
Error 5: Access is denied.
"

My actual username is firstlast not "First Last" (where first = my first name and last = my last name).

**Comment by plsloan** [comment]
Is there an ETA on this? I installed the system version, but it won't update due to this bug either.

**Comment by plsloan** [comment]
This is still happening with version 1.13.1

**Comment by plsloan** [comment]
I gave up and created a new account, and it fixed the issue. This maybe be related to me changing the name of the user folder.

**Comment by kburtram** [comment]
Closing older issues.  We reuse the upstream vscode installer scripts with little modification so ideally any fix would be done there.  Though this sounds like an issue triggered due to machine config and some uncommon bug in the installer.  Thanks for reporting!
