### ISSUE TITLE
Integrity of Copying data from Results Grid is failing

### ISSUE THREAD

**Issue by epikMaowPhailure** [microsoft/azuredatastudio#8247]
Issue Type: <b>Bug</b>

1. Run a query that returns multiple rows, I've been using 50-1000 row results grid
2. copy everything from ONE row from top to bottom.
3. Check copied data (I use ditto or Microsoft's copy tool)

The integrity is currently not kept since it updated this morning(Which is, I assume, the November 2019 update). When I check the data, the rows are NOT in the same order as they are displayed. This is happening on copy, not paste.

This is not happening in the insiders build for me, because I can't even get into a query window in the insiders build.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.91GB (24.12GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-tool-ext-win|Mic|0.0.1
import|Mic|0.12.0
powershell|ms-|2019.11.0
profiler|Mic|0.9.0
query-history|Mic|0.1.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
This issue has been fixed in #8072 and is currently in our [insiders releases](https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master). If you can, can you verify that ADS Insiders behaves properly?

This fix will be included in the next release.
