### ISSUE TITLE
Ran simple spark SQL command & got message about long line

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8256]
Issue Type: <b>Bug</b>

open pyspark notebook
run below & make sure you have about 5-10 tables:

%%sql
show tables

Error:

Tokenization is skipped for long lines for performance reasons. The length of a long line can be configured via `editor.maxTokenizationLineLength`.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (e801a04bcf3429336c8057c3b66cfb359a188752, 2019-11-06T20:11:21.759Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.44.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.0.0
import|Mic|0.12.0
profiler|Mic|0.10.0

(1 theme extensions excluded)

</details>

**Comment by kevcunnane** [comment]
@corivera can you look into this? It has come up a number of time.

**Comment by corivera** [comment]
@kevcunnane When I try running that cell ADS completely locks up. I can't even get to the tokenization message. Looking into it.

**Comment by corivera** [comment]
Fixed by https://github.com/microsoft/azuredatastudio/pull/9725
