### ISSUE TITLE
Deploy toolBase storagePath has race condition

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8260]
https://github.com/microsoft/azuredatastudio/blob/master/extensions/resource-deployment/src/services/tools/toolBase.ts#L124

This is currently leaving a floating promise on the creation of the directory. But in general this function should probably be redone to be async itself - right now there's a race condition where it returns the path which may not necessarily exist yet and so if a caller tried to use it that might fail.

**Comment by ellbosch** [comment]
Hey guys, can this be closed?

**Comment by ranasaria** [comment]
fixed by #8250
