### ISSUE TITLE
BDC deployment .ipynb files set  ACCEPT_EULA = 'yes', we should be setting from outside where possible.

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#8262]
Steps to Reproduce:

1. Code Review:

ACCEPT_EULA = 'yes' setting should be eliminated from files like those in the following folder if possible:
https://github.com/microsoft/azuredatastudio/tree/master/extensions/resource-deployment/notebooks/bdc/2019

**Comment by ranasaria** [comment]
@alanrenmsft - can you help triage this issue?

**Comment by alanrenmsft** [comment]
@dnethi please check with the security team

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
