### ISSUE TITLE
deployments not possible due to error: command 'azdata.resource.deploy' not found

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#8265]
- Azure Data Studio Version:
Version: 1.14.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.38.0
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1. Start a new instance of azuredatastudio (in my repro case from dev environment)
2. Quickly (as soon as possible after startup) Invoke the 'Deploy SQL Server' button.

Actual: The expected dialogue on the right to allow the user to select one of may deployment tiles does not show up. Instead the following error pops:
command 'azdata.resource.deploy' not found

The issue is definitely timing related and does not happen after all the extensions have been loaded (ostensibly one containing azdata.resource.deploy command). Once the issue has happened, redoing this operation no longer helps and it is no longer possible to deploy any resources.

Expected: The error does not happen and the user is able to invoke deployment workflows through the dialogue that opens.

**Comment by ranasaria** [comment]
@alanrenmsft - kindly help triage this issue.

**Comment by alanrenmsft** [comment]
I've seen the command not found happening before, but once the extension is loaded, everything works just fine. do you have a consistent repro?

**Comment by ranasaria** [comment]
I have a very high probability repro when testing within a windows VM. Perhaps, we should now show that UI element until the command azdata.resource.deploy is available.

**Comment by alanrenmsft** [comment]
waiting for your repro @ranasaria

**Comment by alanrenmsft** [comment]
i think this has been fixed by Chris.
