### ISSUE TITLE
Schema compare - Compare Details doesn't scale as expected

### ISSUE THREAD

**Issue by 7even7** [microsoft/azuredatastudio#8276]
- Azure Data Studio Version: 1.13

Steps to Reproduce:
- Launch Schema compare
- Resize Output/Problems/Terminal section vertically
- Notice that there's a lot of free space that "Compare Results" doesn't use (yellow arrow in picture).  It seems to have fixed max height instead of reactive per space available.
![image](https://user-images.githubusercontent.com/18673617/68460363-67a7bd80-0210-11ea-90de-6b9b0754188a.png)

1.

**Comment by ellbosch** [comment]
Thanks for your feedback. I was able to repro this issue as well.
