### ISSUE TITLE
Comment in Powershell Notebook Code Cell breaks code execution

### ISSUE THREAD

**Issue by CKrumel** [microsoft/azuredatastudio#8277]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a new notebook
2. Change the kernel to Powershell
3. Enter code "Get-DscResource  # put in some comments" into first line of code cell
4. Execute
The Execute button will change to a square and no result will be returned. Any other code in that notebook will not execute until the notebook is closed and reopened. The same code without the comment will execute as expected after restart.

**Comment by m82labs** [comment]
This is a little more nuanced. This bug pops up when the last characters in a cell are a comment. So you could have 100 lines of code with comments, but if that last line ends in a comment you will see this issue.

![PowerShellNotebookError02](https://user-images.githubusercontent.com/8697204/68594222-193f2c80-0465-11ea-8958-6b6fb10568e3.gif)
