### ISSUE TITLE
Cannot edit contents of notebook text cell

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#8286]
Issue Type: <b>Bug</b>

I have a text cell in my notebook.  If I double-click it to edit it, only the header line appears.  Not the contents after it.

Screenshot 1: display mode

![image](https://user-images.githubusercontent.com/12263288/68532095-89c03f00-02e7-11ea-8c45-458281086204.png)

Screenshot 2:  After double-clicking

![image](https://user-images.githubusercontent.com/12263288/68532101-947ad400-02e7-11ea-8a20-76427a98a820.png)

(Cannot edit the text after the header line)

Screenshot 3: JSON markup for the text cell

![image](https://user-images.githubusercontent.com/12263288/68532116-b2483900-02e7-11ea-847d-49f504332c03.png)

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (3.21GB free)|
|Process Argv|--folder-uri file:///c%3A/Pluralsight/Repos/postgresql-functions-playbook/07%20Windowing%20functions/Demos|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2
powershell|ms-|2019.11.0

</details>

**Comment by kevcunnane** [comment]
@chlafreniere can you take a look?

@gbritton1 do you have anything regarding font / text sizes changed in your user settings? I've seen stuff like that before and thought we fixed all issues around it, but would be good to check.

**Comment by gbritton1** [comment]
No font changes. You can see the json.  Btw I think this a regression,
possibly caused by the new collapse expand options

**Comment by chlafreniere** [comment]
@gbritton1 you're right on with the collapsible cells here, that's the culprit.
