### ISSUE TITLE
Cannot set Include checkbox on Add Column Change (Extension: Schema Compare)

### ISSUE THREAD

**Issue by ArtemOrlovGmail** [microsoft/azuredatastudio#8293]
**Extension: SQL Server Schema Compare**
Version: latest on 11.11

**Azure Data Studio**
Version: 1.13.0 (user setup)
Commit: cacd481bff25c890e4130aee392569bae43b7e60
Date: 2019-11-02T00:40:05.147Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18362

Cannot set Include checkbox for the Change when add-remove column involved
Steps to reproduce:

1. Find Table with difference that include new or missing columns
2. Try to enable or disable Include checkbox

Result: after a second checkbox is set back with message popup (see attachment)

![add-drop column](https://user-images.githubusercontent.com/41300509/68594968-46a9cb80-04a1-11ea-95b2-7f9cdc6fe935.png)

Expected: checkbox must be set and Change excluded from comparison

**Comment by ArtemOrlovGmail** [comment]
In the same time SSDT Schema Compare tool show that Dependencies exist (see attachment)

So expected result would be to show the same message as in SSDT
![add-drop column 2](https://user-images.githubusercontent.com/41300509/68596826-8aea9b00-04a4-11ea-9cc3-1867f84e9e11.png)

**Comment by udeeshagautam** [comment]
@ArtemOrlovGmail Thanks for you feedback. The checkbox in ADS does not take effect if the dependencies are not excluded  to prevent from giving a false impression when something is not really excluded. But the message should mention the dependencies like following,
![image](https://user-images.githubusercontent.com/46980425/68705743-7b6e5f00-0543-11ea-8bfd-d989574524ae.png)



We will work to make sure the behavior is more clear and smoot. Regarding the error message can you please check if you are using the latest version of Schema compare extension
![image](https://user-images.githubusercontent.com/46980425/68705855-a789e000-0543-11ea-8d44-f04bab170aaf.png)
