### ISSUE TITLE
Welcome Page should have ADS Icon in Tab Titlebar

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#8297]
In VSCode, we see the following:

![image](https://user-images.githubusercontent.com/40371649/68612390-472a6e00-0471-11ea-9d89-749953df4302.png)

In ADS, we see a generic icon:

![image](https://user-images.githubusercontent.com/40371649/68612413-56112080-0471-11ea-8b8e-701d88d793ad.png)

**Comment by Charles-Gagnon** [comment]
Yeah I actually just looked into this over the weekend - there's a couple places we didn't have icons. This one in particular is coming from https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/contrib/welcome/code-icon.svg 

I reached out to the design team to get an updated svg for this and the other ones we're missing.

**Comment by chlafreniere** [comment]
Awesome. Looking forward to it 😄
