### ISSUE TITLE
Need support for Conditional Access

### ISSUE THREAD

**Issue by olamer** [microsoft/azuredatastudio#8298]
Azure Data Studio does not support Conditional Access. An Intune enrolled device leveraging AAD Conditional Access capabilities will fail when evaluating its compliance status. This limitation will prevent Azure Data Studio to access company resources as the device will not pass the enforced policies. This is why we need Azure Data Studio to fully support Conditional Access.

**Comment by kburtram** [comment]
@olamer we have an updated sign-in process that no longer depends on Device Code merged into the master branch.  This can be tested using the latest insiders build and will be in the Dec stable build next week.

To enable the new sign-in process please add environment variable `NEW_SIGN_IN_EXPERIENCE` with a value of `true`.  The plan is to make this the default Azure sign-in experience in Feb release.
