### ISSUE TITLE
Feature Request: Create snippets on the fly

### ISSUE THREAD

**Issue by tapan-p** [microsoft/azuredatastudio#83]
- SQL Operations Studio Version:0.23.6

Steps to Reproduce:
1. Assume that you have query that you use frequenty
`select *
from Table1 t1
inner join Table2 t2 on t1.col = t2.col`
2. Highlight the query and in context menu/or through some action button, create a snippet 
3. Pop out another window with above highlighted text and option to name this snippet and save button.

**Comment by alanrenmsft** [comment]
@tapan-p I know this is an old issue, but still want to understand the issue a bit better here, Azure Data Studio inherited the user snippet feature: https://code.visualstudio.com/docs/editor/userdefinedsnippets, does this meet your needs?
