### ISSUE TITLE
Disable explorer folder expansion when moving files/folders

### ISSUE THREAD

**Issue by JasonGoemaatAtCorteva** [microsoft/azuredatastudio#8301]
Issue Type: <b>Feature Request</b>

Scenario:  I use Azure Data Studio to organize demos (ipynb) and documents for tasks.  To keep it organized, I have a _Current, _Old, and _Recent folders, and subfolders for my tasks.  When I'm done with one task, I'll move its folder from _Current to _Recent while it's being tested, and from _Recent to _Old when done.  The explorer pane in ADS is very convenient for this.

The problem is that it automatically expands the folders I'm dropping the folders into, and possibly other folders if I'm not fast or accurate enough in my dragging.   It's much more natural for me to expant the folders to where I want to drag the folder to start with.   This auto-expansion doesn't help me out at all and adds an extra step of collapsing the expanded folder every time I drag.  It's especially bothersome since I have to drag past _Old on my way to _Recent, and _Old has so many subfolders that _Recent is several pages off screen if it gets expanded.

It would be nice if there was a flag to disable the expansion of folders when dragging and dropping.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17134

**Comment by alanrenmsft** [comment]
@JasonGoemaatAtCorteva  Azure Data Studio is a fork of the Visual Studio Code, we inherit the  feature you mentioned above from VS Code, could you please open an issue there? we will automatically get it once they make the changes. vscode repo: https://github.com/microsoft/vscode
