### ISSUE TITLE
cannot install schema compare extension

### ISSUE THREAD

**Issue by dbrtly** [microsoft/azuredatastudio#8306]
- Azure Data Studio Version: 1.12.2

Steps to Reproduce:

1. click install

get error message "Failed to install 'microsoft.schema-compare'
download manually from 
https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json/publishers/Microsoft/

This url does not exist. I searched the code from this url: 
https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery.json

and downloaded from this url:
https://sqlopsextensions.blob.core.windows.net/extensions/schema-compare/schema-compare-1.0.0.vsix

manually installing from this file yielded this error message:
Unable to install version '1.0.0' of extension 'microsoft.schema-compare' as it is not compatible with Azure Data Studio '1.12.2'.

**Comment by Charles-Gagnon** [comment]
Please update to the latest version of ADS (1.13.0) - the extension requires changes made in that update and so trying to install in an earlier version will fail as you've seen.

(the link being bad is a separate issue that we've since fixed in insiders)
