### ISSUE TITLE
Query Tab won't close

### ISSUE THREAD

**Issue by martin-guth** [microsoft/azuredatastudio#8308]
- Azure Data Studio Version: 1.13.0 (user setup)
- OS Version: Windows 7 Professional Service Pack 1

Steps to Reproduce:

I have a query file which always open as Azure Data Studio comes up. However I don't want to see that query opened any more. So I clicked "Close"....a dialogue comes up asking me if I would like to save changes. Whatever I select here (Save, Don't save) the tab just doesn't close. I uninstalled Azure Data Studio, did a reboot, reinstalled it and that query magically comes up again (even if the underlying file is deleted!). I can run it on SQL, I can kill the session...try to close it again...nothing seems to work.

How do I get rid of this tab automatically opened?

**Comment by alanrenmsft** [comment]
@martin-guth I believe the state information is saved in the azuredatastudio folder under %appdata% (type this in the address bar of file explorer). based on your description, I am assuming you don't care about setting changes you've made. you can rename the azuredatastudio folder to something else just in case you want something back, then start ADS.

**Comment by martin-guth** [comment]
@alanrenmsft Thanks renaming AppData/Roaming/azuredatastudio did the trick for me. ADS starts up fresh with no query reopening.
