### ISSUE TITLE
Create external table - Oracle date mapping

### ISSUE THREAD

**Issue by hkroese** [microsoft/azuredatastudio#8310]
Issue Type: <b>Bug</b>

Just created an new external table (source Oracle-12, destination SQL Server 2019). The Generate script-function maps the date in Oracle to date in SQL Server. This should be datetime/datetime2. Wasn't this already a old bug? 

BTW. When previewing the bug-report to GitHub I got an error (to much data). Unchecking the include-boxes solved the problem.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18362

**Comment by kevcunnane** [comment]
@corivera can you investigate this? I'd like to know if it's by design or needs a fix.

**Comment by corivera** [comment]
Fixed
