### ISSUE TITLE
Error adding account - Error: Entry not found in cache.

### ISSUE THREAD

**Issue by chet5619** [microsoft/azuredatastudio#8311]
Issue Type: <b>Bug</b>

Using Azure Data Studio 
1. Expand the Azure tree to "Sign in to Azure..."
2. Click "Add an account" button
3. Click the "Copy & Open" button to authenticate
4. Use my organization authenticated account to sign in
The following error pops up in Azure Data Studio
[Error adding account - Error: Entry not found in cache.]

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17763

**Comment by ahryshchanka** [comment]
installed version:
```
Version: 1.13.1
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:00:55.976Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Darwin x64 19.0.0
```

**Comment by AlejoSQL** [comment]
I can repro too 

Version: 1.13.0-insider (user setup)
Commit: f8067ffadab178d2929a162408032ff63b0b717b
Date: 2019-10-25T09:46:57.975Z
VS Code: 1.38.0
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by AlejoSQL** [comment]
Hey, doesn't this seem as the saem as #7619 ?

**Comment by aaomidi** [comment]
Closing in favor of #7619
