### ISSUE TITLE
find and replace in selection (not always global)

### ISSUE THREAD

**Issue by jensf** [microsoft/azuredatastudio#8312]
**Issue:** I want to just global replace on a subsection of my sql code. I have to find and replace one by one, or everything.  

Commonly occurs for me when writing an update statement and pasting in long string containing many apostrophes. Though, there are many other use cases for this feature.

_Example:_

LongString = `I'm writ'n lot's of apostrophes and 'single quotes'!`

```
update someTable 
set someColumn='Paste-LongString-Here', otherColum='staticValue' 
where ColA='ConditionX' and ColY='ConditionY'
```

Now replace `'` with `''`

**Work-around:** copy my selection into notepad, find and replace there, paste back into ADS.

**Solution:** allow find and replace but only for the currently selected text, not the entire document.

_Options for Implementation:_

1. Option A: Add a paste in selection icon
![image](https://user-images.githubusercontent.com/1754057/68696705-76151280-054b-11ea-9617-89b365f881dc.png)

2. Option B: add a checkbox to limit replace in selection
![image](https://user-images.githubusercontent.com/1754057/68696888-ce4c1480-054b-11ea-8c98-3fae00f03f0f.png)

3. Option C (BEST): Limit global replace to selection, if selection exists
![image](https://user-images.githubusercontent.com/1754057/68698328-b4600100-054e-11ea-8d71-d97b37cf17f8.png)

**Comment by Charles-Gagnon** [comment]
You can already do this by enabling the "Find in Selection" option on the find dialog.

![image](https://user-images.githubusercontent.com/28519865/68698662-44de1780-0536-11ea-8c94-27948681fcae.png)

This will search/replace only the selected text.

**Comment by jensf** [comment]
AHHH!!  What do you know ... there it is.  I spent at least 20 minutes looking for this feature and some time searching on line before writing the request. Would be nice to have it a bit more intuitive, but I'm super glad it's available. 

Thanks!
