### ISSUE TITLE
Azure Account cant be deleted

### ISSUE THREAD

**Issue by RubenMaldonado** [microsoft/azuredatastudio#8314]
Issue Type: <b>Bug</b>

Add an Azure account.
Use it to connect to sql server.
Deactivate/block the Account.
Then Azure account cant be deleted.
I cant add any other account, because there is a problem with the blocked one.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-01T23:25:46.501Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz (12 x 3200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|32.00GB (1.00GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
@RubenMaldonado You can remove accounts by opening the Accounts dialog (the little person symbol in the bottom left) and clicking the X.

![image](https://user-images.githubusercontent.com/28519865/68721732-3f012a00-0568-11ea-8188-2e70f8ae67a0.png)

Although it sounds like you might be referring to something else. Could you walk through what you mean by "I can't add any other account"?

**Comment by RubenMaldonado** [comment]
@Charles-Gagnon , actually that's the problem. For this particular account the X is not displayed:

![image](https://user-images.githubusercontent.com/9390686/68722456-251d1280-057b-11ea-80de-e4a3113e3ce2.png)

![image](https://user-images.githubusercontent.com/9390686/68722472-323a0180-057b-11ea-9aa8-e6e194d95b92.png)

I have the message that the credentials must be refreshed, but I can't do this because this account was from an old employer, so its already deactivated/blocked. Any suggestions?

**Comment by Charles-Gagnon** [comment]
If you open the developer console (Help -> Toggle Developer Tools) and then go to the console tab are there any errors displayed there after you open the dialog?

If you're fine losing some settings you can also delete/rename the %appdata%\azuredatastudio\User folder and that will clear all saved accounts.
