### ISSUE TITLE
Explain button does nothing

### ISSUE THREAD

**Issue by skanthb** [microsoft/azuredatastudio#8324]
![no explain plan](https://user-images.githubusercontent.com/17520646/68794476-138c4700-061d-11ea-8d1f-32bcb2073d25.JPG)

- Azure Data Studio Version: 
Version: 1.13.0 (user setup)
Commit: cacd481bff25c890e4130aee392569bae43b7e60
Date: 2019-11-02T00:40:05.147Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17134

Steps to Reproduce:

1. run a simple query like select * from table
2. click on "Explain" button

output:
the query runs and show data. in the data output pane below i see only "results" tab and "Messages" tab. I do not see any query plan.

How to view the query plan?

Thanks,
Srikanth

**Comment by skanthb** [comment]
no, my issue does not seem to be the one mentioned in #3652. I do not see Query plan tab at all. Both Run query and explain button behave the same.

**Comment by kburtram** [comment]
@skanthb are you seeing any errors in the "Help->Developer Tools" Console?  The Explain button should show the Query Plan tab.
