### ISSUE TITLE
Can't copy from output of notebook code cell while cell is executing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8328]
1. Create code cell with some long running code, such as this 
```
import time
print('try to copy me')
time.sleep(30)
```
2. Execute cell
3. While it's running try to copy the output text

The code cell keeps grabbing focus so you can actually select and copy text from the output.

**Comment by chlafreniere** [comment]
Turned out to be an easy fix to an issue that's impacted a few folks. Bringing it back into February.
