### ISSUE TITLE
Saving a SQL Query disconnects from the current connection

### ISSUE THREAD

**Issue by Chewieez** [microsoft/azuredatastudio#8333]
Issue Type: <b>Bug</b>

Connect to a database
Create a query against that database
Save the query
The open tab which shows the current query you just saved is now disconnected requiring me to sign back into the database

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-01T23:25:46.501Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (12 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 4|
|Memory (System)|32.00GB (0.27GB free)|
|Process Argv||
|Screen Reader|no|
|VM|22%|
</details>Extensions: none

**Comment by SEary342** [comment]
I am having the same issue on Windows 10 azuredatastudio 1.13.0. If I save an existing file, the connection is kept; however, if I save as a new file, the connection is deleted.

**Comment by dzsquared** [comment]
I'm no longer seeing the behavior in 1.15.0, untitled editors automatically reconnect on save

**Comment by anthonydresser** [comment]
There was no intentional fix for this. If it was fixed we should investigate and ensure its the correct behavior.

**Comment by Charles-Gagnon** [comment]
@anthonydresser - I wonder if my fix here had the side effect of fixing this https://github.com/microsoft/azuredatastudio/pull/8901

I'll check this out tomorrow if you don't get around to it tonight.

**Comment by dzsquared** [comment]
@Charles-Gagnon based on the impact #8901 had on the way I had implemented (editor reconnect on save) functionality in the Query Editor Boost extension, I suspect you are correct.

**Comment by Charles-Gagnon** [comment]
Yeah - verified it was that which fixed it. That seems fine to me so I'm going to close this, @anthonydresser let me know if you think of any possible issues with this.
