### ISSUE TITLE
Opening An Exported XLSX File No Longer Opens System's Default App

### ISSUE THREAD

**Issue by rharris-ameresco** [microsoft/azuredatastudio#8336]
Issue Type: <b>Bug</b>

In older versions of Azure Data Studio, I could right-click data and save as xlsx, then once the pop-up said the file was saved and if I want to "Open File Location" or "Open File", I used to be able to click the "Open File" button to have the file loaded into Microsoft Excel (my system's default app for .xlsx files). Now, it tries to open it in the Azure Data Studio editor as a binary file.

![image](https://user-images.githubusercontent.com/51416059/68884915-cd48ed80-06d9-11ea-9d82-e26e3d2ff670.png)

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.82GB (6.66GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
import|Mic|0.12.0
profiler|Mic|0.9.0

</details>

**Comment by chlafreniere** [comment]
This appears to be the same issue as #8218, so we can track that there.
