### ISSUE TITLE
Mouse wheel scrolling is erratic

### ISSUE THREAD

**Issue by brobichaud** [microsoft/azuredatastudio#8347]
Issue Type: <b>Bug</b>

In recent releases I have found mouse behavior to have degraded. In the query window a single turn of the mouse wheel is scrolling far too much. I've checked the "Editor: Mouse Wheel Scroll Sensitivity" setting in Data Studio and it is set to 1. Changing it to 0 makes no difference, higher numbers make it worse. Other apps I use are scrolling a reasonable amount.

In the Results window I am finding that the mouse wheel is not working at all unless I move the mouse cursor over to the scrollbar (or the icons next to it). THere it works fine, elsewhere it does not work at all.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-02T00:40:05.147Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (5.61GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by kburtram** [comment]
@anthonydresser can you think of anything that could have changed in this area?  Nothing's coming to mind, perhaps the Electron update?

**Comment by anthonydresser** [comment]
It could be the electron update...but then vscode would be getting similar complaints I imagine. I can't think of anything we have done in this area.

**Comment by kenvanhyning** [comment]
Tried this out on my Windows 10 desktop comparing VS Code latest release with current code in master.  I don't see any difference between the two.  On the ADS side, I checked a plain text file, a disconnected sql file (7700+ lines), and then with the sql editor in a connected state with that same sql file.  The mousewheel scrolling appeared consistent across all those.

Probably need some more info from Brett here unless someone else can repro this.

**Comment by brobichaud** [comment]
I am now seeing a pattern in the results scrolling. If I have multiple result sets and both return a small number of results (small enough to avoid scrollbars in each grid) then I see this behavior. If I have a single resultset or multiple and they each have their own scrollbars then scrolling works ok. On the query window I am consistently seeing this jumpy scrolling behaviour always.

**Comment by mchenx** [comment]
I think I'm having the same issue, when I scroll in the query window, it moves 16~18 lines, that's really too much, I can't even follow the lines that I read. When the result window shows up, the screen space became smaller and I can't continue reading the content in the query window when scrolling.

The vs code is much better, moves like 3 lines each time I scroll the window use the mouse wheel

here is the version

![image](https://user-images.githubusercontent.com/1550186/70798036-dadcba80-1de0-11ea-9f73-5a89aed3380e.png)

**Comment by imseor** [comment]
I have same issue

![image](https://user-images.githubusercontent.com/2198944/71252250-c6d71280-2324-11ea-9104-267f11399b3b.png)

**Comment by brobichaud** [comment]
> upgraded to 1.14.1 just now, and it's fixed, wonderful

Agreed. I don;t know if this was 1.14.1 of DataStudio or some random Windows 10 Update, but the scrolling is now normal again in the SQL Script window (about 3 lines per wheel click).

I do still have issues (totally different) in a multi-resultset window where it seems to get confused and does nothing when I turn the wheel.

**Comment by brobichaud** [comment]
I'm going to go ahead and close this.
