### ISSUE TITLE
Syntax highlight - EXCEPT & INTERSECT as in SSMS [DBL]

### ISSUE THREAD

**Issue by databull** [Microsoft/azuredatastudio#835]
- SQL Operations Studio Version:
![sketch](https://user-images.githubusercontent.com/22824483/36933947-73eef2d2-1ed9-11e8-860c-7a9554f045bc.png)

Steps to Reproduce:

**Comment by DanielSSilva** [comment]
Instead of creating a new issue, I'll add info here. `DATALENGTH` is a built-in function that's not getting highlighted (like replace in this example)
![image](https://user-images.githubusercontent.com/6862119/40558259-aadd5d80-604a-11e8-8d4d-44f835f5ae82.png)
