### ISSUE TITLE
Opening a notebook that doesn't exist now gives error...

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8358]
Issue Type: <b>Bug</b>

Unable to read file (Unknown (FileSystemError): Error: UNKNOWN: unknown error, stat '\\machine_name\public\blah\blah\blah.ipynb')

I opened notebook from share, and closed ADS. Now the share doesn't exist and the error above is thrown upon first start.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (02b1673c717529e2d34805b1e80194596159d327, 2019-11-15T09:31:15.318Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (21.92GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.44.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.10.0

(1 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
vscode changed a lot of their editor backup + rehydration logic, and with our latest vs code merge (i.e. in Insiders), user-facing errors are no longer being thrown when trying to rehydrate editors whose locations no longer exist.

Instead, there is now a simple fileOperationResult message and stack that's printed to the developer console. Users will no longer see an error message appear on their machines.
