### ISSUE TITLE
Running two cells in a T-SQL notebook at the same time has unexpected effect

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8372]
Issue Type: <b>Bug</b>

I did a SELECT TOP 1000 * FROM sys.messages in the first cell and then a SELECT 1 in the second cell.  Ran the first one and while that one was running I ran the second one.  Not only did the first cell appear to stop executing but the results from the first query showed up as the results pane for the second cell!

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (02b1673c717529e2d34805b1e80194596159d327, 2019-11-15T08:22:04.489Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
deletedb|Ale|0.0.3
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
arcsqlmideployment|Mic|0.0.1
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.11.0
profiler|Mic|0.10.0
sqlservbdc-app-deploy|Mic|1.1.0
azdata-sanddance|msr|1.3.9
scala|sca|0.3.8

(3 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
This is being tracked by #5300. I'll move that up to planning.
