### ISSUE TITLE
Unable to edit row

### ISSUE THREAD

**Issue by VendolaSolutions** [microsoft/azuredatastudio#8376]
Issue Type: <b>Bug</b>

Select Edit data, but keep encountering the error, unable to edit any data and row at all.

Azure Data Studio version: azuredatastudio 1.13.0 (cacd481bff25c890e4130aee392569bae43b7e60, 2019-11-01T23:25:46.501Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8257U CPU @ 1.40GHz (8 x 1400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 4, 4|
|Memory (System)|8.00GB (0.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@VendolaSolutions I'm not clear on the bug.  Is the repro something like:

1. Connect to database and select Edit Data on a Table
2. An error message pops-up saying "Unable to Edit Row"

Could you also please check the "Help->Developer Tools" Console to see if there are any related error messages logged there?

**Comment by kburtram** [comment]
Closing older bugs without current repro reports.  Please let us know if you're still impacted by this issue.
