### ISSUE TITLE
Creating an external table over Oracle gives error

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8378]
Issue Type: <b>Bug</b>

Create an external table over an Oracle XE instance

In one case I get an error message that says this:
105083;The following columns in the user defined schema are incompatible with the external table schema for table 'Tf492bbad85ff4d': user defined column: ([OWNER] VARCHAR(30) COLLATE Latin1_General_BIN) is not compatible with the type of detected external table column: ([OWNER] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL), user defined column: ([TABLE_NAME] VARCHAR(30) COLLATE Latin1_General_BIN) is not compatible with the type of detected external table column: ([TABLE_NAME] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL), user defined column: ([TABLESPACE_NAME] VARCHAR(30) COLLATE Latin1_General_BIN) is not compatible with the type of detected external table column: ([TABLESPACE_NAME] VARCHAR(30) COLLATE Latin1_General_100_BIN2_UTF8). The detected external table schema is: ([OWNER] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL, [TABLE_NAME] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8 NOT NULL, [TABLESPACE_NAME] VARCHAR(30) COLLATE Latin1_General_100_BIN2_UTF8, [CLUSTER_NAME] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8, [IOT_NAME] VARCHAR(128) COLLATE Latin1_General_100_BIN2_UTF8, [STATUS] VARCHAR(8) COLLATE Latin1_General_100_BIN2_UTF8, [PCT_FREE] FLOAT(53), [PCT_USED] FLOAT(53), [INI_TRANS] FLOAT(53), [MAX_TRANS] FLOAT(53), [INITIAL_EXTENT] FLOAT(53), [NEXT_EXTENT] FLOAT(53), [MIN_EXTENTS] FLOAT(53), [MAX_EXTENTS] FLOAT(53), [PCT_INCREASE] FLOAT(53), [FREELISTS] FLOAT(53), [FREELIST_GROUPS] FLOAT(53), [LOGGING] VARCHAR(3) COLLATE Latin1_General_100_BIN2_UTF8, [BACKED_UP] VARCHAR(1) COLLATE Latin1_General_100_BIN2_UTF8, [NUM_ROWS] FLOAT(53), [BLOCKS] FLOAT(53), [EMPTY_BLOCKS] FLOAT(53), [AVG_SPACE] FLOAT(53), [CHAIN_CNT] FLOAT(53), [AVG_ROW_LEN] FLOAT(53), [AVG_SPACE_FREELIST_BLOCKS] FLOAT(53), [NUM_FREELIST_BLOCKS] FLOAT(53), [DEGREE] VARCHAR(10) COLLATE Latin1_General_100_BIN2_UTF8, [INSTANCES] VARCHAR(10) COLLATE Latin1_General_100_BIN2_UTF8, [CACHE] VARCHAR(5) COLLATE Latin1_General_100_BIN2_UTF8, [TABLE_LOCK] VARCHAR(8) COLLATE Latin1_General_100_BIN2...

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (02b1673c717529e2d34805b1e80194596159d327, 2019-11-15T08:22:04.489Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|16.00GB (4.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
deletedb|Ale|0.0.3
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
arcsqlmideployment|Mic|0.0.1
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.11.0
profiler|Mic|0.10.0
sqlservbdc-app-deploy|Mic|1.1.0
azdata-sanddance|msr|1.3.9
scala|sca|0.3.8

(3 theme extensions excluded)

</details>

**Comment by corivera** [comment]
Fixed

**Comment by Charles-Gagnon** [comment]
Let's keep this open until the service and extension are updated

**Comment by Charles-Gagnon** [comment]
New extension published to insiders and will be updated when stable is released.
