### ISSUE TITLE
No accept/reject buttons in compare mode

### ISSUE THREAD

**Issue by erikmourits** [microsoft/azuredatastudio#8385]
Issue Type: <b>Bug</b>

When trying to save a 'dirty' file, I am prompted to compare my changes with the one on disk. An extra tab is opened with both versions loaded. However I am not able to accept or reject any changes because the buttons are not visible.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz (8 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.85GB (4.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
profiler|Mic|0.9.0
schema-compare|Mic|1.0.0
sql-search|Red|0.3.5

</details>

**Comment by kisantia** [comment]
ADS now has support for the diff merge with accept and reject buttons that's also available in vscode
