### ISSUE TITLE
Not able to generate script after a database compare

### ISSUE THREAD

**Issue by dlalancette** [microsoft/azuredatastudio#8387]
Version: 1.13.1 (user setup)
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:08:09.800Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 6.1.7601

Name: SQL Server Schema Compare
Id: microsoft.schema-compare
Description: Schema Compare tool for dacpac and databases
Version: 1.0.0
Publisher: Microsoft
VS Marketplace Link: undefined?itemName=Microsoft.schema-compare

Steps to Reproduce: Compare two database and trying to apply changes or generate script. 

I get this error : 
Generate script: Exception of type 'System.Exception' was thrown.
Exception of type 'System.Exception' was thrown.

Thanks for your help

**Comment by kisantia** [comment]
@dlalancette can you please share the dacpacs of these databases so that we can try to repro this?

**Comment by dlalancette** [comment]
Sorry I can't since this is an enterprise database.

**Comment by kisantia** [comment]
@dlalancette do apply changes and generate script also fail for this comparison when comparing using SSDT?

**Comment by dlalancette** [comment]
No, it works.
I have to say that I only get this error since I updated my ADS and the extension SQL Server Schema Compare. Before that, everything was working.

**Comment by kisantia** [comment]
Can you send a non-enterprise sample that repros this issue? It would help us narrow down what caused this regression. 

Did you update from October release to November release? Or from an older version?
