### ISSUE TITLE
Show Import Wizard context menu option when connected directly to a database

### ISSUE THREAD

**Issue by paulirwin** [microsoft/azuredatastudio#8388]
**Is your feature request related to a problem? Please describe.**
The Import Wizard context menu option shows if you're connected to the `<Default>` database and then you right click on the database name. However, it does not appear if you specify a database when adding the connection, then right click on the server/database. 

I believe this might have been what was reported in #7043 but that issue is now locked for comment.

**Describe the solution or feature you'd like**
Would like the Import Wizard option when right clicking on a database-specified connection.

**Describe alternatives you've considered**
None, as that is the only way I'm aware of to access the Import Wizard. To workaround, I have to add a new connection to `<Default>`.

**Additional context**
![image](https://user-images.githubusercontent.com/1874103/69167910-ee7f5480-0ab2-11ea-9dbb-35eceda08662.png)

**Comment by aasimkhan30** [comment]
This issue was addressed by #16700
