### ISSUE TITLE
Update the build pipeline to read secrets from azure key vaults

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#8390]
so that we only need to make changes in one place instead of updating all build pipelines.

**Comment by anthonydresser** [comment]
Im doing this as part of the mixin stuff; I can probably just extend it to include this.

**Comment by alanrenmsft** [comment]
@anthonydresser nice! when are we planning to switch to the YAML based build pipelines?

**Comment by anthonydresser** [comment]
the yml pipelines and the mixin stuff are not related. The yml stuff will probably be whenever we are comfortable with them being stable. The mixin stuff will probably be today or tomorrow.

**Comment by Charles-Gagnon** [comment]
@ranasaria @anthonydresser With the latest updates to the tools service release pipelines this should be finished, correct?

**Comment by ranasaria** [comment]
No I will finish it this afternoon.
