### ISSUE TITLE
Feature Request: Select/Highlight the object in ServerWindow/Object Explorer 

### ISSUE THREAD

**Issue by tapan-p** [microsoft/azuredatastudio#84]
- SQL Operations Studio Version:0.23.6

Steps to Reproduce:
1. select the object in editor (or keep your cursor on the object) (for example, `select * from TableName`, either select TableName or keep cursor on TableName) and through context menu(or keyboard shortcut), highlight the same object in object explorer/server window.
it would be great feature (with many database on the same server) as current SSMS doesn't allow to do so unless you use RedGate Tools.

**Comment by tpatel11** [comment]
@erickangMSFT , while designing/writing SP, one would often look at certain columns from different tables. Depending on the amount of tables, it would be difficult to go back and forth looking for the same (without filter on object explorer). 
Having this feature would allow to not only to see columns and key constraints, but any other feature available on context menu on the node in object explorer without scrolling though tables. 
So if I want to see table X, I can type the same, and if this feature allows me to navigate to object explorer to this table, I can view details including column,keys, etc.  

Key usage would be to eliminate time we spend in searching for right table/object (like database,SP, Function and types). I know that there is a quick definition available to view the table details but it selecting/expanding the node would be quicker to back and forth.

**Comment by cheenamalhotra** [comment]
Search/Filter feature (Ctrl+F) is available in Object Explorer that can be used for highlighting/searching table in Server/OE view.

![image](https://github.com/microsoft/azuredatastudio/assets/13396919/6d06729d-5f74-478e-a731-ab36009ebc4e)
