### ISSUE TITLE
Database Dashboard and Object Explorer won't open when connecting to APS/PDW

### ISSUE THREAD

**Issue by patrickmcdermo** [microsoft/azuredatastudio#840]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
1. Open SQL Operations Studio and connect to an APS/PDW server using the server name and port number.
2. Select a specific database and attempt to view objects in the object explorer: tables, views, etc.
3. Note that the object explorer does not open and that there is an error message under the Database Dashboard: "Unable to load dashboard properties." (See attached screenshot).
![image](https://user-images.githubusercontent.com/25159921/36985377-f8e25ee8-204b-11e8-97e9-e2db29055e0b.png)

**Comment by patrickmcdermo** [comment]
I'd also like to note that SQL Operations Studio specifically supports connections to Azure SQL Data Warehouse, which uses the same basic code base as SQL APS/PDW (AU6): 
https://docs.microsoft.com/en-us/sql/sql-operations-studio/quickstart-sql-dw

**Comment by filipefumaux** [comment]
Was it fixed?

**Comment by Charles-Gagnon** [comment]
We were closing old items that hadn't seen any activity in a while. Are you still experiencing this issue? We haven't been able to investigate but if you are then I can re-open (please provide the latest version of both ADS and the server you're using).
