### ISSUE TITLE
Please update Extension Authoring topics

### ISSUE THREAD

**Issue by rrgiles** [microsoft/azuredatastudio#8406]
- Azure Data Studio Version: current

The Extension Authoring topics located at https://docs.microsoft.com/en-us/sql/azure-data-studio/extensibility?view=sql-server-ver15 should to be updated. Some references to 'sqlops' still exist and should be updated to reflect the use of 'azdata' instead. The instructions for upgrading from older extensions should be referenced here as well and it would be helpful to include any new information since the topics are over a year old.

**Comment by alanrenmsft** [comment]
thanks @rrgiles , i have submitted a PR to update the content. regarding to the instructions for upgrading sqlops, don't think it is needed tthere since Idera extension is the only one still using sqlops.
