### ISSUE TITLE
Unable to Verify the First Certificate Error When Trying to Add Azure Account

### ISSUE THREAD

**Issue by olivesandtrees** [microsoft/azuredatastudio#8408]
Issue Type: <b>Bug</b>

When trying to add a Azure account to Azure Data Studio I am greated by the following error "unable to verify the first certificate" as soon as I click the Add an account button.

I have added "http.proxyStrictSSL": false to my settings but it did not make any difference.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6126 CPU @ 2.60GHz (2 x 2600)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: disabled_off<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|4.00GB (0.78GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details>Extensions: none

**Comment by olivesandtrees** [comment]
I was able to fix this issue by bypassing our security web proxy (which had TLS inspection turned on).

**Comment by kburtram** [comment]
@olivesandtrees thanks for providing the additional context.  ADS uses Node.JS for http communication, which doesn't use the system Certificate Authorities.  This creates issues with packet inspection firewalls that decode HTTPS traffic.  As noted, disabling SSL certificate validation with `"http.proxyStrictSSL": false` is the correct workaround at this time.
