### ISSUE TITLE
Deleting row in when using editdata causes entire table to be null

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#8414]
Steps to Reproduce:

1. Open a table using EditData. (for my case, it was a simple one row table)
2. Click on any rowCell to be deleted, it appears to be removed just fine.
3. When looking in the SQL Server Management Studio or upon refresh, the entire table is null and entries have to be reentered again as a result.

This happens in the master branch as well as in my editdatatest branch (where the table doesn't update to reflect the row deletion, but that's unrelated to this).

**Comment by kburtram** [comment]
It looks like this is related to the type of the column.  I was able to repro using the TEXT column type, but not varchar or int, for example.  The below snippet created a table that repro's this bug.

```SQL
CREATE TABLE TestEdit
(
    val TEXT 
)
INSERT INTO TestEdit VALUES('Test1')
INSERT INTO TestEdit VALUES('Test2')
INSERT INTO TestEdit VALUES('Test3')
INSERT INTO TestEdit VALUES('Test4')
INSERT INTO TestEdit VALUES('Test5')
```

**Comment by smartguest** [comment]
From what I'm seeing, this has been an issue with the earliest build of Azure Data Studio/SQL-Server from the very beginning (pre release). 

Since the command for the call to the SQL server does not involve the datatype of the table (only the row to be deleted, and the name of the table) I suspect this is likely an issue that is on the SQL Server side treating string tables differently from other table types. 

I need to know the exact syntax that SMSS uses to delete rows for a string table in order to fix this issue, which I currently lack.

**Comment by smartguest** [comment]
When examining the delete SQL query for a string in ADS compared to SMSS, it is completely different for some reason.

In SMSS: 
![SMSS Delete command](https://user-images.githubusercontent.com/18018452/74389987-c737db00-4db4-11ea-9803-780712b2e58e.png)

In ADS for a string table:
![ADS Delete Command](https://user-images.githubusercontent.com/18018452/74390007-d0c14300-4db4-11ea-9a41-a2f7314fa5aa.png)

And in ADS for a non string table (identical to SMSS for a non string table):
![ADS Delete Command Non String](https://user-images.githubusercontent.com/18018452/74390027-e20a4f80-4db4-11ea-979f-20afd06b4583.png)

At some point after the request to delete the row is sent, something (in one of the extensions or something else) is outputting the wrong SQL query command. 

I've searched for this but could not find where the SQL query is created, which file handles this?

**Comment by Charles-Gagnon** [comment]
What do you mean "string table"?

Delete requests for ADS use the SqlToolsService : https://github.com/microsoft/sqltoolsservice/blob/master/src/Microsoft.SqlTools.ServiceLayer/EditData/UpdateManagement/RowDelete.cs#L23

**Comment by smartguest** [comment]
@Charles-Gagnon I mean a table with string values

**Comment by smartguest** [comment]
After debugging the SqlToolsService, I found out that in RowEditBase.cs, if a cell data is text based, then the clause is replaced with 'IS NOT NULL' instead of using the value directly. This means that SqlToolsService cannot accept strings directly as cell values without deleting the whole table

Screenshot attached below:
![RowEditBase screenshot](https://user-images.githubusercontent.com/18018452/74486891-f6ad1d00-4e72-11ea-8291-d5424b12d345.png)

**Comment by smartguest** [comment]
@kburtram I need help determining where the query for the WHERE statement is being formed, it appears to be generated in sqltoolsservice from what I'm seeing and not inside ADS

**Comment by smartguest** [comment]
@kburtram I'm not sure where to find the query statement and to add onto it, it appears to be created in the SqlToolsService and not anywhere in the code for ADS.

**Comment by kburtram** [comment]
Merged change into SQL Tools Service to fix this issue https://github.com/microsoft/sqltoolsservice/pull/931.  The change will be picked up in the next sqltoolsservice refresh and included in September release.
