### ISSUE TITLE
Notebooks: Internal Document Links Not Functional

### ISSUE THREAD

**Issue by joshs-STCU** [microsoft/azuredatastudio#8428]
Azure Data Studio Version: 1.13.1

CPUs | Intel(R) Core(TM) i7-6600U CPU @ 2.60GHz (4 x 2808)
-- | --
GPU Status | 2d_canvas: enabledflash_3d: enabledflash_stage3d: enabledflash_stage3d_baseline: enabledgpu_compositing: enabledmultiple_raster_threads: enabled_onnative_gpu_memory_buffers: disabled_softwareoop_rasterization: disabled_offprotected_video_decode: unavailable_offrasterization: enabledskia_deferred_display_list: disabled_offskia_renderer: disabled_offsurface_synchronization: enabled_onvideo_decode: enabledviz_display_compositor: disabled_offwebgl: enabledwebgl2: enabled
Load (avg) | undefined
Memory (System) | 15.89GB (6.68GB free)
Process Argv |  
Screen Reader | no
VM | 0%

Extension | Author (truncated) | Version
-- | -- | --
powershell | ms- | 2019.11.0
whoisactive | Mic | 0.1.2
sql-search | Red | 0.3.4

Steps to Reproduce:

1. Create a internal document anchor `<a name="regrets"> </a>`
2. In a different cell create a link to the anchor `[link](#regrets)`
3. clicking the created link does not navigate to the document anchor but instead opens a second tab called workbench.html with the following content:

```<!-- Copyright (C) Microsoft Corporation. All rights reserved. -->
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<!-- {{SQL CARBON EDIT}} @anthonydresser add 'unsafe-eval' under script src; since its required by angular -->
		<meta http-equiv="Content-Security-Policy" content="default-src 'none'; img-src 'self' https: data: blob: vscode-remote-resource:; media-src 'none'; frame-src 'self' https://*.vscode-webview-test.com; object-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; connect-src 'self' https:; font-src 'self' https: vscode-remote-resource:;">
	</head>
	<body class="vs-dark" aria-label="">
	</body>

	<!-- Startup via workbench.js -->
	<script src="workbench.js"></script>
</html>
```

**Comment by anthonydresser** [comment]
What kind of document are you trying to do this in? notebook, markdown? etc.

**Comment by joshdba** [comment]
Apologies: in a Notebook.

**Comment by MsSQLGirl** [comment]
The following table shows what is supported by Jupyter in terms of linking to document parts or Heading.

Markdown syntax for linking to a section in   notebook | Markdown syntax for the section that it will jump   to
-- | --
`[this link works   using "a id"](#cream)` | `<a   id='cream'></a>CREAM!`   or   `<a   id='cream'>CREAM!</a>`
`[this link works   using "a name"](#ice)` | `<a   name='ice'></a>ICE!`   or   `<a   name='ice'>ICE!</a>`
`[this link works   for Headings](#Introduction)` | `# Introduction`
`[this link works   for Multi-word Headings](#Ice-Cream)` | `# Ice Cream`
`[this link works   for Heading Level 2](#My-chocolate-Ice-Cream)` | `## My chocolate   Ice Cream`
`[Duplicated   Heading will always goes to the first one](#My-chocolate-Ice-Cream)` ` | `## My chocolate   Ice Cream`   <br>`## My chocolate   Ice Cream`

File to repro:
[Anchors.zip](https://github.com/microsoft/azuredatastudio/files/4252021/Anchors.zip)




``

**Comment by chlafreniere** [comment]
I was just trying on my Mac, and am trying to get a full picture of what works today 😄:

Markdown syntax for linking to a section in notebook | Markdown syntax for the section that it will jump to | Works Today?
-- | -- | --
[this link works using "a id"](#cream) | <a id='cream'></a>CREAM! or <a id='cream'>CREAM!</a> | **Yes**
[this link works using "a name"](#ice) | <a name='ice'></a>ICE! or <a name='ice'>ICE!</a> | **No**
[this link works for Headings](#Introduction) | # Introduction | **Yes**
[this link works for Multi-word Headings](#Ice-Cream) | # Ice Cream | **Yes**
[this link works for Heading Level 2](#My-chocolate-Ice-Cream) | ## My chocolate Ice Cream | **Yes**
[Duplicated Heading will always goes to the first one](#My-chocolate-Ice-Cream) ` | ## My chocolate Ice Cream## My chocolate Ice Cream | **No**

I'll update this when we've added more support

**Comment by MsSQLGirl** [comment]
@chlafreniere On my Windows, I still get workbench.html as reported at the beginning of this issue for both Insiders and standard build. 

Version: 1.16.0-insider (user setup)
Commit: 9f9c65591d58c2999a72268e38e176f802fa184d
Date: 2020-03-09T05:48:25.421Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363


Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
Moving to April for the other relative document links. Will also remove the Approved label to prevent confusion 😄

**Comment by MsSQLGirl** [comment]
@barbaravaldez - it seems that if the reference/link and the linked item are on the same cell, and the linked item is at the bottom of the text cell and ADS window is short, clicking on the item seems to not work well. Can you please help investigate?

![ADSAnchorEndOfCell](https://user-images.githubusercontent.com/6405919/79008359-13cc3800-7b12-11ea-9b0b-5fe0948425b6.gif)
