### ISSUE TITLE
Investigate default connection picking behavior in NotebookContexts

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#8438]
When selecting the default connection in NotebookContexts.getActiveContexts, the only criteria used is whether the serverName matches the one in the provided connection profile. We should investigate whether things like database name and user name should also be considered.

Note that this doesn't cause any issues with picking a "wrong" connection. All the other active connections for the supported providers are still included in the dropdown, just that the default connection may not be the most accurate.

**Comment by chlafreniere** [comment]
This has since been fixed by the connection changes in the Attach To dropdown.
