### ISSUE TITLE
Auto reload ipynb when updated on disk

### ISSUE THREAD

**Issue by dfinke** [microsoft/azuredatastudio#8442]
I'm building this PowerShell module https://github.com/dfinke/PowerShellNotebook.
One feature, it has a DSL to create PS Notebooks.

Does Azure Data Studio have the feature that reloads the `ipynb`  when it gets updated on disk? If not, it'd be very handy.

**Comment by chlafreniere** [comment]
Not yet unfortunately. We're tracking this ask with #8522 and intend on addressing this concern. Thanks!
