### ISSUE TITLE
In Servers pane refresh will intermittently stop working

### ISSUE THREAD

**Issue by peterrow** [microsoft/azuredatastudio#8455]
Issue Type: <b>Bug</b>

After adding columns via SQL statements and importing a CSV into a new table right clicking and choosing the refresh option on the database stops refreshing and I can't see the new tables/columns added.

Furthermore when it is working refreshing collapses the whole tree, it shouldn't do this. It should be possible to use the refresh option at the Table node of a DB without the tree collapsing. Further to that it should be possible to refresh at any level and have it refresh just at that level, e.g. if I refresh on a specific table it should just refresh that, or if I refresh Stored Procedures under programmability it should just refresh that list.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz (8 x 4008)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (22.25GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
import|Mic|0.12.0
profiler|Mic|0.9.0

</details>

**Comment by kburtram** [comment]
@peterrow could you please check if there are any errors in the "Help->Developer Tools" Console the next time this occurs?  I haven't been able to repro yet.

**Comment by peterrow** [comment]
Will do, I'll being some more SQL dev with it soon at home so will be sure to check that out and report back.
