### ISSUE TITLE
Error connecting to azure server

### ISSUE THREAD

**Issue by TGod-Ajayi** [microsoft/azuredatastudio#8461]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

download azure on macbook pro,
Try connecting to a database

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:00:55.976Z)
OS version: Darwin x64 19.0.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-5350U CPU @ 1.80GHz (4 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|8.00GB (0.06GB free)|
|Process Argv|-psn_0_532610|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
   20	    74	  3939	azuredatastudio main
    3	    25	  3941	   gpu-process
    0	   229	  3945	   window (Welcome)
    0	   139	  3958	     extensionHost
    0	    41	  3967	       /private/var/folders/1z/_tjh1q_15mgdp93rb61_kv_m0000gq/T/AppTranslocation/D0913488-437A-4567-94E3-1356C2E4468B/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/2.0.0-release.30/MicrosoftSqlToolsServiceLayer --log-file /Users/dev/Library/Application Support/azuredatastudio/logs/20191125T140713/exthost1/Microsoft.mssql/sqltools.log --tracing-level Critical
    0	    25	  3968	       /private/var/folders/1z/_tjh1q_15mgdp93rb61_kv_m0000gq/T/AppTranslocation/D0913488-437A-4567-94E3-1356C2E4468B/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/2.0.0-release.30/SqlToolsResourceProviderService --log-file /Users/dev/Library/Application Support/azuredatastudio/logs/20191125T140713/exthost1/Microsoft.mssql/resourceprovider.log --tracing-level Critical
    0	    25	  3969	       /private/var/folders/1z/_tjh1q_15mgdp93rb61_kv_m0000gq/T/AppTranslocation/D0913488-437A-4567-94E3-1356C2E4468B/d/Azure Data Studio.app/Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/2.0.0-release.30/MicrosoftSqlToolsCredentials --log-file /Users/dev/Library/Application Support/azuredatastudio/logs/20191125T140713/exthost1/Microsoft.mssql/credentialstore.log --tracing-level Critical
    0	    25	  3983	       /private/var/folders/1z/_tjh1q_15mgdp93rb61_kv_m0000gq/T/AppTranslocation/D0913488-437A-4567-94E3-1356C2E4468B/d/Azure Data Studio.app/Contents/Frameworks/Azure Data Studio Helper.app/Contents/MacOS/Azure Data Studio Helper /private/var/folders/1z/_tjh1q_15mgdp93rb61_kv_m0000gq/T/AppTranslocation/D0913488-437A-4567-94E3-1356C2E4468B/d/Azure Data Studio.app/Contents/Resources/app/extensions/json-language-features/server/dist/jsonServerMain --node-ipc --clientProcessId=3958
    4	    66	  3954	   shared-process
    0	     0	  4007	     /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    6	    74	  4005	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
;
```

</details>
Extensions: none

**Comment by Charles-Gagnon** [comment]
@TGod-Ajayi Could you please provide more information - such as any errors you're seeing?

We're already tracking some issues with connections to Azure here -https://github.com/microsoft/azuredatastudio/issues/7619. Could you see if the issues described there are the same as the ones you're experiencing?
