### ISSUE TITLE
Query History: Logs should remain forever

### ISSUE THREAD

**Issue by thiagolunardi** [microsoft/azuredatastudio#8463]
- Azure Data Studio Version:

Version: 1.13.1 (user setup)
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:08:09.800Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.19030

- Query History Extension Version:

Version: 0.1.0

Steps to Reproduce:

1. Connect to any database
2. Run any query. Eg: `SELECT GETDATE()`
3. Close ADS
4. Open ADS again
5. No query is displayed at Query History tab;

And that's important to be persisted, after a restart - for updating purposes or any, or even for small auditing into past executions.

**Comment by Charles-Gagnon** [comment]
Thanks for the feedback @thiagolunardi - we're already tracking this request here - https://github.com/microsoft/azuredatastudio/issues/8243 - so I'm going to close this one as a duplicate.
