### ISSUE TITLE
Cant export to excel

### ISSUE THREAD

**Issue by despo4** [microsoft/azuredatastudio#8465]
Cant export to excel i can save the file but when pouching Open file in the pop up the file insists on opening ion Azure data studio not in excel. What to do=?

1.

**Comment by kburtram** [comment]
This looks like a duplicate of https://github.com/microsoft/azuredatastudio/issues/8218.  I'll take a look at why this is happening.

@despo4 the workaround in the meantime would be to "Open File Location" then double-click the file to have it opened by the default application for that file extension.
