### ISSUE TITLE
Data is null for Sql Server Central Management Servers extension

### ISSUE THREAD

**Issue by lisaburnett-ha** [microsoft/azuredatastudio#8471]
On Central Management Servers extension.
Added the Azure server and it shows up under the Central Management Servers.
Click on the server and get this error:

Data is Null. This method or property cannot be called on Null values.

**Comment by kburtram** [comment]
We should probably be raising a more appropriate error messages such as how SSMS handles this scenario.

![image](https://user-images.githubusercontent.com/599935/69591168-bc845b80-0fa6-11ea-9111-b8026c00367e.png)

**Comment by kenvanhyning** [comment]
Though SSMS does allow an azure server to be specified too - is there any reason why we are not disallowing this to even be added?
