### ISSUE TITLE
HotExit query editors don't work correctly from stable to insiders

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8478]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open some SQL scripts and type of content in them using 1.13.1 stable build
2. Close ADS stable with documents unsaved\open for HotExit
3. Open ADS insiders

Expected: SQL editor windows behavior normally

Actual: Closing the SQL editors creates "untitled plain text" tab documents which can't be closed.  Clicking close button on tab doesn't do anything.

![image](https://user-images.githubusercontent.com/599935/69589314-9065dc00-0fa0-11ea-971d-ef4e4bc60536.png)

**Comment by kburtram** [comment]
@anthonydresser I think this is likely related to the custom editors change that went in recently.  Could you please take a look?

**Comment by anthonydresser** [comment]
This is interesting since aren't insiders and table supposed to use different data store directories? so they don't share hot exit?

**Comment by kburtram** [comment]
@anthonydresser insiders and stable share cached state for ADS (unlike with vscode).  However, the real issue here isn't going back-and-forth with stable\insiders.  I'm expecting this issue should impact all users when they upgrade from 1.13 to 1.14, right?

**Comment by anthonydresser** [comment]
I see, yes, I'm looking into the issue, I know where the issue is, I'm thinking on the best way to solve it.

**Comment by chlafreniere** [comment]
Does this affect notebooks as well, or just query editors?

**Comment by anthonydresser** [comment]
Yes it will affect every custom edtior we have that uses inputs, I have a patch for this upgrade scenario.
