### ISSUE TITLE
tools service fails to start on mac if it has not been previously downloaded on machine

### ISSUE THREAD

**Issue by ranasaria** [microsoft/azuredatastudio#8485]
This issue is observed only on a mac using the latest insiders build produced by the new yaml pipeline. When I run the insiders build produced by the old pipeline, this issue is not observed.

Repro steps:
1. Download the latest insiders build for mac using the URL: https://azuredatastudio-update.azurewebsites.net/latest/darwin/insider
2. Unzip the folder
3. run the 'Azure Data Studio - Insiders' package.
4. On startup the following message pops up:

**Observed:** The following error pops on the bottom right as a notification. 
'Failed to start SQL Tools Service' 
Source: mssql (Extension)

**Expected:** Sqltoolservice to start-up successfully and azure sql server connectivity to work.

Upon investigation in the Contents/Resources/app/extensions/mssql/sqltoolsservice/OSX/2.0.0-release.35 folder is not found.

This is is not observed when we run the latest insiders build produced by the old pipeline from here:
https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=47760

**Comment by anthonydresser** [comment]
This should be fixed for #8464 you can just produce a new manual build to test.

**Comment by ranasaria** [comment]
Yes  #8464 has fixed it.
