### ISSUE TITLE
Data virt wizard for Oracle is not showing a list of tables

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8491]
Issue Type: <b>Bug</b>

Repro steps:
Provision Oracle XE instance with HR sample DB.
Create a demo DB in BDC master.
Right click - start external table wizard
Provide encryption key, data source name, server name/IP, etc.
Get to the screen where you select tables or views to virtualize.
Expand tables.  Shows nothing.  Expand views. Those show up.
Can virtualize using T-SQL just fine using the same settings.
No error messages in wizard.

Extension version: 1.1.0
Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (ffee69a765d333f59333bc3f3f59d5a5bfdecc7b, 2019-11-26T05:46:42.188Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (2.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by Charles-Gagnon** [comment]
I'm going to close this since we'll be moving to an entire different method of querying the metadata here soon which should be a lot more stable - if we see the issue still occurring then I'll investigate for fixing.
