### ISSUE TITLE
Clicking Next on the data source page of the wizard does nothing

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8496]
Issue Type: <b>Bug</b>

Repro steps:
In external table wizard for Oracle, get to the data source configuration page.  Provide some information that will not be something that you can connect to.  In my case, i mistyped the service name.  Click Next.  

Expected:
Some error message.

Actual:
Nothing happens other than a quick flicker on the next button.

Extension version: 1.1.0
Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (a1fc621e1b81d6eeaec5363ff8f27cc5fed45410, 2019-11-26T21:36:04.899Z)
OS version: Windows_NT x64 10.0.19013

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (4.47GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by corivera** [comment]
Should be fixed by https://github.com/microsoft/azuredatastudio/pull/8545
