### ISSUE TITLE
Shipping multiple version of the toolsservice

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#8498]
We are currently shipping multiple versions of the sqltoolsservice; we should only ship the newest.

**Comment by chlafreniere** [comment]
Like, when downloading the tools service, the package actually contains multiple versions?

**Comment by Charles-Gagnon** [comment]
Correct. From a fresh install of the latest insiders :

![image](https://user-images.githubusercontent.com/28519865/69979438-2f2f9280-14e3-11ea-97f1-879c35f9bfb6.png)

This should also fix https://github.com/microsoft/azuredatastudio/issues/8517 - the [installer from the ad hoc run for this PR](https://mssqltools.visualstudio.com/_apis/resources/Containers/1710019?itemPath=drop%2Fuser-setup%2FAzureDataStudioSetup.exe) has the size back down to ~90MB again

![image](https://user-images.githubusercontent.com/28519865/69979656-8b92b200-14e3-11ea-9feb-9104a4135fcd.png)

**Comment by chlafreniere** [comment]
Have we shipped this in stable as well?

**Comment by Charles-Gagnon** [comment]
No. My understanding is that this was caused by recent changes in the pipelines which were done after the November release. I've verified that the current stable release only includes a single version of the service.

**Comment by chlafreniere** [comment]
> No. My understanding is that this was caused by recent changes in the pipelines which were done after the November release. I've verified that the current stable release only includes a single version of the service.

Awesome, thanks!

**Comment by Charles-Gagnon** [comment]
Verified this is fixed with the latest insiders 
![image](https://user-images.githubusercontent.com/28519865/70078131-02e54600-15b7-11ea-8407-f1a2358383eb.png)
