### ISSUE TITLE
azdata sql query -q "select * from sys.dm_cluster_endpoints" doesnt work from BDC notebook

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8504]
Issue Type: <b>Bug</b>

TSG070-use-azdata-sql-query.ipynb doesnt seem to work when running the azdata sql query command.

Error output below.

Works from CLI terminal.

---------------------------------------------------------------------------
SystemExit                                Traceback (most recent call last)
<ipython-input-11-4d51265c305f> in <module>
----> 1 run(f'azdata sql query -q "{query}"')

<ipython-input-2-dae64885653a> in run(cmd, return_output, no_output, error_hints, retry_hints, retry_count)
    114 
    115     if p.returncode != 0:
--> 116         raise SystemExit(f'Shell command:\n\n\t{cmd}\n\nreturned non-zero exit code: {str(p.returncode)}.\n')
    117 
    118     print(f'\nSUCCESS: {cmd}\n')

SystemExit: Shell command:

	azdata sql query -q "select * from sys.dm_cluster_endpoints"

returned non-zero exit code: 1.
 START: azdata sql query -q "select * from sys.dm_cluster_endpoints" (using: C:\Users\Travis\azuredatastudio-python\0.0.1\Scripts\azdata.EXE)
 ERR: ERROR: cannot import name 'CliCommandsLoader'
ERR: Traceback (most recent call last):
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\__init__.py", line 188, in invoke
ERR:     args=args)
ERR:   File "C:\Users\Travis\AppData\Roaming\Python\Python36\site-packages\knack\cli.py", line 162, in raise_event
ERR:     func(self, **kwargs)
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\logging.py", line 138, in init_command_file_logging
ERR:     self._init_command_logfile_handlers(cmd_logger, args)
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\logging.py", line 149, in _init_command_logfile_handlers
ERR:     self.cli_ctx.invocation.commands_loader.load_command_table(args)
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\commands.py", line 65, in load_command_table
ERR:     merge.update(_load_module_command_loader(self, args, mod))
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\commands.py", line 29, in _load_module_command_loader
ERR:     command_table = command_loader.load_command_table(args)
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\commands\app\__init__.py", line 18, in load_command_table
ERR:     from mssqlctl.cli.commands.app.command_table import \
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\commands\app\command_table.py", line 5, in <module>
ERR:     from mssqlctl.cli.commands.app import client
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\commands\app\client.py", line 15, in <module>
ERR:     from mssqlctl.cli.core.clients.cli_client import CliClient
ERR:   File "c:\users\travis\appdata\roaming\python\python36\site-packages\mssqlctl\cli\core\clients\__init__.py", line 11, in <module>
ERR:     pkg_resources.declare_namespace(__name__)
ERR:   File "c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\pkg_resources\__init__.py", line 2147, in declare_namespace
ERR:     declare_namespace(parent)
ERR:   File "c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\pkg_resources\__init__.py", line 2163, in declare_namespace
ERR:     _handle_ns(packageName, path_item)
ERR:   File "c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\pkg_resources\__init__.py", line 2098, in _handle_ns
ERR:     loader.load_module(packageName)
ERR:   File "c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\mssqlctl\cli\core\__init__.py", line 11, in <module>
ERR:     from mssqlctl.cli.core.commands import CliCommandsLoader
ERR: ImportError: cannot import name 'CliCommandsLoader'
 An exception has occurred, use %tb to see the full traceback.

SystemExit: Shell command:

	azdata sql query -q "select * from sys.dm_cluster_endpoints"

returned non-zero exit code: 1.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (c9226a07c594cd8be1bf66358da57a82cfe20d82, 2019-11-28T02:19:15.581Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (4.29GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.2.0
ssmskeymap|kev|1.1.0
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
datavirtualization|Mic|1.1.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by chlafreniere** [comment]
@MaddyDev sorry this one too 😄

**Comment by MaddyDev** [comment]
This will be fixed once I refresh the contents as well. I tested it on my windows after refreshing the contents and it worked

![image](https://user-images.githubusercontent.com/12754347/70170251-2b397700-1681-11ea-96a6-3456e290aaf6.png)
