### ISSUE TITLE
Typo in azdata command in the SAM001 notebook

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8505]
Issue Type: <b>Bug</b>

cluster_res = run('azdata bdcta('bdc endpoint list --endpoint="livy"', return_output=True)

Should be
cluster_res = run('azdata bdc endpoint list --endpoint="livy"', return_output=True)

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (c9226a07c594cd8be1bf66358da57a82cfe20d82, 2019-11-28T02:19:15.581Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (3.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.2.0
ssmskeymap|kev|1.1.0
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
datavirtualization|Mic|1.1.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by chlafreniere** [comment]
@MaddyDev if you could ensure this is fixed with the latest books update that'd be fantastic

**Comment by MaddyDev** [comment]
This will be fixed once I complete the https://mssqltools.visualstudio.com/_git/SqlOpsStudioExtensions/pullrequest/832?_a=overview

**Comment by MaddyDev** [comment]
Fixed by the above merge.
