### ISSUE TITLE
SUGGEST_MACRO is undefined in SAM0002

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8506]
Issue Type: <b>Bug</b>

try:
    %load_ext sql
except ModuleNotFoundError:
    SUGGEST_MACRO("SOP062")
    raise

Error message is:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-abe9e0515c7a> in <module>
      3 try:
----> 4     get_ipython().run_line_magic('load_ext', 'sql')
      5 except ModuleNotFoundError:

c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\interactiveshell.py in run_line_magic(self, magic_name, line, _stack_depth)
   2313             with self.builtin_trap:
-> 2314                 result = fn(*args, **kwargs)
   2315             return result

<c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\decorator.py:decorator-gen-65> in load_ext(self, module_str)

c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\magic.py in <lambda>(f, *a, **k)
    186     def magic_deco(arg):
--> 187         call = lambda f, *a, **k: f(*a, **k)
    188 

c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\magics\extension.py in load_ext(self, module_str)
     32             raise UsageError('Missing module name.')
---> 33         res = self.shell.extension_manager.load_extension(module_str)
     34 

c:\users\travis\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\extensions.py in load_extension(self, module_str)
     79                 with prepended_to_syspath(self.ipython_extension_dir):
---> 80                     mod = import_module(module_str)
     81                     if mod.__file__.startswith(self.ipython_extension_dir):

c:\users\travis\azuredatastudio-python\0.0.1\lib\importlib\__init__.py in import_module(name, package)
    125             level += 1
--> 126     return _bootstrap._gcd_import(name[level:], package, level)
    127 

c:\users\travis\azuredatastudio-python\0.0.1\lib\importlib\_bootstrap.py in _gcd_import(name, package, level)

c:\users\travis\azuredatastudio-python\0.0.1\lib\importlib\_bootstrap.py in _find_and_load(name, import_)

c:\users\travis\azuredatastudio-python\0.0.1\lib\importlib\_bootstrap.py in _find_and_load_unlocked(name, import_)

ModuleNotFoundError: No module named 'sql'

During handling of the above exception, another exception occurred:

NameError                                 Traceback (most recent call last)
<ipython-input-7-abe9e0515c7a> in <module>
      4     get_ipython().run_line_magic('load_ext', 'sql')
      5 except ModuleNotFoundError:
----> 6     SUGGEST_MACRO("SOP062")
      7     raise

NameError: name 'SUGGEST_MACRO' is not defined

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (c9226a07c594cd8be1bf66358da57a82cfe20d82, 2019-11-28T02:19:15.581Z)
OS version: Windows_NT x64 10.0.19025

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.97GB (3.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.2.0
ssmskeymap|kev|1.1.0
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
datavirtualization|Mic|1.1.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by chlafreniere** [comment]
@MaddyDev can you ensure that this is fixed with the latest book updates?

**Comment by MaddyDev** [comment]
Should be fixed with the above merge.
