### ISSUE TITLE
Unable to Add Azure AD Account

### ISSUE THREAD

**Issue by ld0614** [microsoft/azuredatastudio#8510]
Issue Type: <b>Bug</b>

First installation of Azure Data Studio
Connection Type: Microsoft SQL Server
Authentication Type: Azure Active Directory - Universal
Account: Add Account

This opens the device authentication screen, after clicking open and copy Edgium opens and I copy the code into the window.  This sucessfully acknowledges the connection, after a few seconds the dialog in Azure Data Studio closes by no account appears.  Repeating several times does not solve the issue.  

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz (6 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.74GB (4.62GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@aaomidi do you think the work you're doing with the auth stack will help here?

**Comment by aaomidi** [comment]
@kburtram yep - the authentication flow is completely different now.

**Comment by aaomidi** [comment]
@ld0614 If you click Help -> Toggle Developer Tools and click Console and try to login to Azure again, do you get any errors?

**Comment by ld0614** [comment]
@aaomidi, thanks for the prompt response.  My account appears to be adding now.  One thing I did do yesterday after attempting this was to remove myself from an external B2B directory which also required MFA.  Looking at the successful authentication it appears that the tenants I am connected to are enumerated, I'm wondering if this requirement to MFA a second time caused a silent error?  I may have time to be able to configure a test tenant tomorrow to replicate this scenario if it might be an issue

**Comment by aaomidi** [comment]
There's some weird oddities with the device code authentication. That may be the reason it failed.

I've been working on refactoring this area and I'll update this issue when we have it ready for testing, it might be interesting to see how this new system behaves in these weird scenarios.

**Comment by aaomidi** [comment]
Closing in favor of #7619
