### ISSUE TITLE
Context menu to support rename

### ISSUE THREAD

**Issue by sql-koala** [microsoft/azuredatastudio#8511]
**Is your feature request related to a problem? Please describe.**
Right now, renaming an object (table, view, ...) is quite a chore. It can be done by typing
`exec sp_rename 'schema.oldname' 'newname'`
but there is no intellisense inside the quotes.

**Describe the solution or feature you'd like**
It would be nice to have a rename entry in the context menu of items in both connection explorer and search in Database Dashboard.
![grafik](https://user-images.githubusercontent.com/30384885/69872673-5a816a00-12b6-11ea-91fc-1b4922465208.png)
and
![grafik](https://user-images.githubusercontent.com/30384885/69872703-74bb4800-12b6-11ea-9e91-9a29238287d6.png)

I see two options: A script support, (clicking on dbo.Table1 would generate:
`exec sp_rename 'dbo.Table1' 'Table1'`

or a "dialog" like in ssms. The second option is probably more work, but I think it is better for users. 
Because, for example: what is a good default value for `@newname`?

Thanks for considering this.

**Comment by kisantia** [comment]
This is now available in Preview ("Enable Preview Features" setting needs to be enabled)
![image](https://github.com/microsoft/azuredatastudio/assets/31145923/00814db4-b03b-45cf-8526-352b19dcb134)
