### ISSUE TITLE
Notebook null ref error after cancelling a query

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8521]
Versions : 1.13.1 (current stable) and current insiders

1. Start running query
2. Immediately cancel
3. Get this message in the output pane

![image](https://user-images.githubusercontent.com/28519865/69982765-1676ab00-14ea-11ea-88fb-530c89c29d8f.png)

**Comment by chlafreniere** [comment]
I can't repro this right this second, but I'd be shocked if it's a regression from a recent month. Because of that, moving to planning.

**Comment by Charles-Gagnon** [comment]
Yeah interesting, I can't seem to repro it either. Odd. Anyways I'll close this for now and if I see it again I'll let you know.
