### ISSUE TITLE
Notebook view does no update when there is a new version

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#8522]
Issue Type: <b>Bug</b>

Repro steps:
- Open a notebook in Azure Data Studio.
- After the Notebook opens, go to the folder and overwrite it.

Observed:
- The view does not update. There is no dialog indicating that the file has changed.

Expected:
- ADS should atleast notify the user and give an option to load the latest version.

Azure Data Studio version: azuredatastudio 1.13.0 (05a53af085861999ed8dc99596cd55829387d490, 2019-10-22T07:41:49.347Z)
OS version: Windows_NT x64 10.0.18362

**Comment by MsSQLGirl** [comment]
@chlafreniere - This seems to be addressed in Sep 2020 RC1. Can you please confirm?
