### ISSUE TITLE
deploy bdc wizard 's profile page takes a long time to load

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#8527]

**Comment by ranasaria** [comment]
Moving this back to the backlog as we need a discussion for the changes needed for this and it does not fit into the December release.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
