### ISSUE TITLE
Move build/release pipelines/tasks into checked in YAML

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8528]
The build and release pipelines we have now should be converted into checked-in yaml files and the AutomatedReleases scripts checked into the source repos for a more controlled review process and visibility. 

- [x] SqlToolsService build

- [x] SqlToolsService release

- [ ] VSCode MSSQL build

- [ ] VSCode MSSQL release

**Comment by aaomidi** [comment]
@Charles-Gagnon @anthonydresser @alanrenmsft can we close this?

**Comment by Charles-Gagnon** [comment]
There's still other pipelines we need to convert so probably not - but we can split that into separate issues for each pipeline if we want as well for better tracking. (I just did the SqlToolsService one)

**Comment by aaomidi** [comment]
Do we have a list of the other pipelines that need to be updated?

**Comment by Charles-Gagnon** [comment]
Not directly, I'll try and get that done before I leave otherwise I'll go through after I get back.
