### ISSUE TITLE
An existing connection is replaced with a new one

### ISSUE THREAD

**Issue by maddoxdev** [microsoft/azuredatastudio#8532]
- Azure Data Studio Version: 1.13.1

Steps to Reproduce:

1. exists connection1 in group X
2. add new connection2 to X group with the same server name, user and password, but another port
3. connection1 is replaced by connection2 (see below)

![VisualStudioCodeReplacement](https://user-images.githubusercontent.com/10694484/69969651-dfc28400-152d-11ea-95c7-76634d59de16.gif)

**Comment by kburtram** [comment]
I wasn't able to repro this on current builds.  Please let us know if you're still impacted by this issue.

**Comment by artemsaveliev** [comment]
reproduces on current build. We are using mysql plugin - so port number is in "Advanced" properties - not part of server name like ms sql. The name of the server seems to be used as key for stored connections, so it reuses existing one that has same server name.
