### ISSUE TITLE
ML Extension dashboard getting cut off

### ISSUE THREAD

**Issue by rajmera3** [microsoft/azuredatastudio#8536]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open ADS on a Mac in a window of any size.
2. 
![image](https://user-images.githubusercontent.com/22081978/70080264-18f50580-15bb-11ea-9f7d-55f2b7ac4535.png)

3. Top of dashboard is cut off (buttons are missing)

**Potential Cause**:
In the image below, we can see that the 'Machine Learning Books' box is larger than it needs to be. The scroll bar only scrolls to the bottom of the box, but there is remaining empty space underneath that is being registered as screen space, but not by the scrollbar. Thus, it is truncating the same amount of space from the top.
![image](https://user-images.githubusercontent.com/22081978/70080377-4346c300-15bb-11ea-80f8-48afc005f366.png)

**Comment by llali** [comment]
this should not happen in the new extension. @rajmera3 please reopen if you still see this
