### ISSUE TITLE
Ability to convert selected text into a new cell in a notebook

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#8541]
Issue Type: <b>Feature Request</b>

Select text in a markdown
Right-Click ->Convert to Code Cell OR Convert to Text Cell option

A new cell with the selected text gets created. Depending upon location of the selected text the new cell can be created above or below the current cell. If the selected text is in the middle then the current cell is divided into 2 cells and the selected text cell is placed in between them

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

**Comment by MsSQLGirl** [comment]
This split cell would be very useful for code cell also.

**Comment by chlafreniere** [comment]
Tracked by #17169
