### ISSUE TITLE
SQL Agent Extension - The Schedules list does not show the list of schedules

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#8543]
- Azure Data Studio Version: 1.13.1
- Extension SQL Agent Extension.

Steps to Reproduce:

1. Create a new job with schedule in SSMS. 
2. Using Azure Data Studio, edit the job to view the schedule. 

You should see something like this:
SSMS - 
![image](https://user-images.githubusercontent.com/6405919/70097947-78650c80-15df-11ea-8258-80ceedc1a7f2.png)

Azure Data Studio - 
![image](https://user-images.githubusercontent.com/6405919/70097958-8024b100-15df-11ea-913f-c81b821a7752.png)

**Comment by roysumanjit** [comment]
@abist how was this issues resolved. I have the same issue on my Azure Data Studio v 1.25.2
