### ISSUE TITLE
Check for Updates menu item missing

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8550]
Not sure if this is intentional on dev builds. Quickly looked through the update contribution code and didn't see anything immediately that would indicate that. 

Merge branch :

![image](https://user-images.githubusercontent.com/28519865/70104462-ecf57680-15f2-11ea-8b42-08de5f0c8230.png)

**Comment by anthonydresser** [comment]
If you look at the drop, it looks like it shows up there, so it must be a trigger for not having an update url specified. I can take a look where that would be.

**Comment by anthonydresser** [comment]
Looks like they are using the when condition to do this.
https://github.com/Microsoft/azuredatastudio/blob/ads-master-vscode-2019-12-02T20-33-52/src/vs/workbench/contrib/update/browser/update.ts#L411

I think this is fine since I verified it shows up in drops.
