### ISSUE TITLE
Object explorer does not display databases if Azure Data Warehouse is paused

### ISSUE THREAD

**Issue by matteote** [microsoft/azuredatastudio#8555]
Issue Type: <b>Bug</b>

I have an Azure Data Warehouse in my Azure SQL Database logical server. When the Data Warehouse is paused, the Databases list shows "Failed to connect to server <serve name>"

![image](https://user-images.githubusercontent.com/837087/70134572-ae120000-1688-11ea-8146-bfa1b056751b.png)

Steps to repro:
1. Create an Azure Data Warehouse
2. Pause the Data Warehouse
3. Connect to the server in Data Studio
4. Browse the Databases in the object explorer

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.19033

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (5.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.44.0
azuredatastudio-postgresql|Mic|0.2.2
cms|Mic|0.5.0
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.11.0
profiler|Mic|0.9.0
query-history|Mic|0.1.0
schema-compare|Mic|1.0.0
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.3
vscodeintellicode|Vis|1.2.1

(1 theme extensions excluded)

</details>

**Comment by kburtram** [comment]
I couldn't reproduce on the latest build.  Please let us know if you're still impacted by this issue.  Thanks!
