### ISSUE TITLE
Running query from saved file has empty results and messages pane

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8561]
Current master/insiders

1. Open query file saved to disk
1. Execute query

Results pane is blank :
![image](https://user-images.githubusercontent.com/28519865/70174326-8707fe00-1689-11ea-8424-ebc626e89624.png)

Sometimes switching to the messages tab and then back fixes it, sometimes I get this error instead :

```
Uncaught TypeError: Cannot read property 'onResultSet' of undefined
    at GridPanel.set queryRunner [as queryRunner] (gridPanel.ts:116)
    at ResultsView.set queryRunner [as queryRunner] (queryResultsView.ts:117)
    at ResultsView.onShow (queryResultsView.ts:111)
    at TabbedPanel.showTab (panel.ts:247)
    at HTMLDivElement.<anonymous> (panel.ts:163)
```

**Comment by Charles-Gagnon** [comment]
@anthonydresser - Can you look into this? Is this another problem with the editor refactor?

**Comment by anthonydresser** [comment]
I fixed this issues yesterday...I'll take a look.

**Comment by anthonydresser** [comment]
I'm not seeing this behavior on the latest, can you verify you are on the latest build.

**Comment by Charles-Gagnon** [comment]
I've had weird stuff like this occasionally with the VM I have this installed on. Let me see if it repros with a fresh install...

Version: 1.14.0-insider (user setup)
Commit: 6cce532ca474cb3272a81c7317d759579e4c2afb
Date: 2019-12-04T07:00:59.701Z
VS Code: 1.38.0
Electron: 6.0.12
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.14393

**Comment by Charles-Gagnon** [comment]
Thought I had closed this. 

Anyways this is very weird - I see it sometimes but then it'll just go away. I'll close this out until I have some more solid information on what might be the issue here since there's nothing in the logs indicating an issue occurred.
