### ISSUE TITLE
Save As doesnt update the file name in the tab

### ISSUE THREAD

**Issue by twright-msft** [microsoft/azuredatastudio#8573]
Issue Type: <b>Bug</b>

Repro steps:
1) Open a new notebook (SQL in my case) OR open an existing notebook
2) Put some stuff in the notebook or otherwise make some edits
3) Save As a file name or different file name

Expected:
New file name is shown in the tab.

Actual:
Notebook-0 is shown for a new notebook or the previous name of the file is shown instead of the new name.

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (6cce532ca474cb3272a81c7317d759579e4c2afb, 2019-12-04T05:35:56.287Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz (8 x 2200)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 3, 3|
|Memory (System)|16.00GB (0.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (17)</summary>

Extension|Author (truncated)|Version
---|---|---
deletedb|Ale|0.0.3
newdatabase|kev|0.0.3
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
arcsqlmideployment|Mic|0.0.1
azurecore|Mic|0.1.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.0.0
datavirtualization|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.11.0
profiler|Mic|0.10.0
sqlservbdc-app-deploy|Mic|1.1.0
azdata-sanddance|msr|1.3.9
scala|sca|0.3.8

(3 theme extensions excluded)

</details>

**Comment by chlafreniere** [comment]
@anthonydresser and I were talking about this last night, and we're trying to track it down.

**Comment by anthonydresser** [comment]
@chlafreniere this doesn't happen to query editors. Do you have any ideas what might be happening here?
