### ISSUE TITLE
Cannot configure notebook to use built-in python if python 3.6.6 exists in my machine 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#8575]
- Azure Data Studio Version:

note sure if this is by design but after I installed python 3.6.6 in my machine and change ADS to use the new location, I cannot change it back to use it's own builtin python 
Steps to Reproduce:

1. open ADS, make sure notebook is using ADS python
2. Install 3.6.6 in other location and configure ADS to use that
3. Configure ADS back to use it's own python.  ('Configure Python for notebook' command and select new installation. Assuming this is how to use existing ADS 
4. run a notebook and get the sys.path

what I see is, Jupyter starting using ADS python but my path shows my other 3.6.6 installation still 

![image](https://user-images.githubusercontent.com/17187348/70262157-ad40a300-1748-11ea-89ac-5450a404ee1f.png)

**Comment by chlafreniere** [comment]
We've done a bunch of work in this area since this was opened a few years ago, addressing issues in this specific area. Closing as a result. If you still encounter any issues here, please feel free to reopen @llali.
