### ISSUE TITLE
ADS errors on space character from OneNote

### ISSUE THREAD

**Issue by dday-dba** [microsoft/azuredatastudio#8576]
1) create query in ADS
2) verify it runs fine
3) copy-paste query from ADS into a OneNote page
4) copy-paste query from OneNote into query window of ADS
5) run query which will return:
Msg 102, Level #, State 1, Line #
Incorrect syntax near ' '.
6) retype / replace all spaces in the ADS query window
7) verify it runs fine

**Comment by kburtram** [comment]
Closing older issues without current repro reports.  I haven't seen this error myself copying in and out of OneNote.  I'm not sure if this is perhaps a Windows setting or something?
