### ISSUE TITLE
Missing buttons to create or edit connections

### ISSUE THREAD

**Issue by waynebloss** [microsoft/azuredatastudio#8588]
Issue Type: <b>Bug</b>

I don't know. The buttons are just missing.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T22:56:48.883Z)
OS version: Linux x64 4.19.85-1-MANJARO

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3850)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|15.56GB (7.09GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.9.0

</details>

**Comment by Charles-Gagnon** [comment]
What buttons are these? Can you include a screenshot of where these would normally be? We don't currently have a way to edit existing connections so I'm not sure what "edit connections" button you're referring to here.

**Comment by waynebloss** [comment]
I found them - only after I re-applied my theme though.

The buttons in the upper right corner of this screenshot [from this YouTube video](https://youtu.be/CsjRU_5wnfI?t=7):

![Screenshot_2019-12-06_15-24-36](https://user-images.githubusercontent.com/623736/70354021-a4c99480-183c-11ea-9c2a-9705c07206d6.png)

_(Buttons in the image are: `New Connection`, `New Server Group` and `Show Active Connections`)_

As I am now at a completely different workstation - I am _only slightly_ unsure if I just missed them the last _two times_ that I looked for them on my other workstation...or if something is actually broken. I don't think that I missed them before... because now that I found them I can see that **you must hover over the default SERVERS group of connections** to display the buttons. [1] I was mousing all over that area on my other workstation so that's why I doubt that I missed them.

At this time I can't get back to the desktop of my work machine (which is presumably still in the corrupt theme state) without setting up a desktop remoting server, so I just can't confirm. But, only when I thought to switch themes here at home did I find them immediately. (I have the same exact setup in both places - Manjaro Linux/XFCE.) Anyway, I'll close this until I can confirm for sure on Monday.

Thanks for some great software!

*[1] This is bad discoverability of function, in my opinion.*

**Comment by waynebloss** [comment]
Just one note about my setup: I have a dark theme for my OS. I was on a dark theme in Azure Data Studio, but when I went to adjust the theme - Azure Data Studio settings showed me that the light theme was set, which I don't think was true. I'll confirm that this happening as well on my other machine.

**Comment by Charles-Gagnon** [comment]
Thanks for the additional information @waynebloss! Things seem fine for me in dark theme if you mouse over the buttons so for now it seems like that's working as intended. 

![image](https://user-images.githubusercontent.com/28519865/70356161-9e312200-1828-11ea-9787-d0716df4e503.png)

Thanks for the feedback on the discoverability of the buttons though. It's definitely one of those "it's not obvious unless you know it's there" kind of things that we've inherited from VS Code. You're not the only person confused by this though so if there's enough feedback along those lines we would consider changing the behavior here.

**Comment by waynebloss** [comment]
@Charles-Gagnon I figured out the issue - If you hide all the `Azure` and `SQL Server Big Data Clusters` sub-panels on the CONNECTIONS panel so that the only sub-panel is `Servers` - the buttons disappear.
