### ISSUE TITLE
Spacing on drop down lists isn't correct on mac

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8610]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open the Connection Dialog

Expected: Spacing before text in drop down lists

Actual: Text is flush with the left side of the control

*Note check the appearance of the editable combo box text below*
<img width="500" alt="Screen Shot 2019-12-09 at 12 14 58 PM" src="https://user-images.githubusercontent.com/599935/70469357-bbaaf980-1a7d-11ea-9fc2-6ec66af401b5.png">

**Comment by anthonydresser** [comment]
dupe #8608
