### ISSUE TITLE
Export to CSV has 'empty lines' for every second line

### ISSUE THREAD

**Issue by olebenny** [microsoft/azuredatastudio#8618]
- Azure Data Studio Version:
Version: 1.13.1 (user setup)
Commit: d08d07fe39c7fe74f9265db02cb963c38d048299
Date: 2019-11-14T23:08:09.800Z
VS Code: 1.38.0
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create query that outputs 100 rows and export it to CSV.
2. Open created CSV file in excel or notepad, and you will see every second line is empty

**Comment by slyce130** [comment]
Also an issue for me with postgres csv exports

**Comment by caseylutz** [comment]
@kburtram @anthonydresser This issue should definitely be re-opened. The issue is very reproducible with postgres queries specifically.

**Comment by joekakone** [comment]
Hello everyone,

Any update ? I'm facing the same issue with Postgres.

**Comment by zenolee22** [comment]
Hi All,

I'm also facing the same issue with Postgres DB's when I'm trying to export.

**Comment by Charles-Gagnon** [comment]
Please file any issues with the PG extension here : https://github.com/Microsoft/azuredatastudio-postgresql

**Comment by amerilife-pace** [comment]
Thanks, @Charles-Gagnon - this is tracked there as https://github.com/microsoft/azuredatastudio-postgresql/issues/238
