### ISSUE TITLE
Failed to start Scale Out Data service

### ISSUE THREAD

**Issue by cincy122** [microsoft/azuredatastudio#8621]
Issue Type: <b>Bug</b>

Install extension.  Reload ads.  Error comes up.  Failed to start Scale Out Data service

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.17134

**Comment by cincy122** [comment]
Failed to start Scale Out Data service:Error: 407

Data Virtualization Extension

**Comment by alanrenmsft** [comment]
@corivera and @Charles-Gagnon  could you please take a look?

**Comment by Charles-Gagnon** [comment]
@cincy122 Apologies for the delay on this. I'm going to close it for now since it's been a while but if you're still having this issue please let us know and I'll reopen and we can investigate.
