### ISSUE TITLE
File->Save is Disabled for Notebooks and Query Editor

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#8629]
@SQLvariant found an interesting bug earlier today where the Save menu item is disabled both for untitled and saved notebooks/query editors. Keyboard shortcuts work just fine.

![image](https://user-images.githubusercontent.com/40371649/70580595-3a309580-1b69-11ea-8a72-98664b6d1da5.png)

**Comment by chlafreniere** [comment]
@anthonydresser have you ever seen anything like this before?

**Comment by SQLvariant** [comment]
FWIW: I received a reply to my tweet about this to the [@code handle](https://twitter.com/code) earlier today: https://twitter.com/chrisdias/status/1204520000888832007?s=20

The reply linked to this item in the VSCode repo: https://github.com/microsoft/vscode/issues/77131

**Comment by anthonydresser** [comment]
Does ctrl+s still work?

**Comment by chlafreniere** [comment]
@anthonydresser yes.
