### ISSUE TITLE
Have alternate keybindings for Run Query

### ISSUE THREAD

**Issue by kevcunnane** [microsoft/azuredatastudio#863]
This comes from Travis: he'd like to have the VSCode-MSSQL `Cmd+Shift+E` option to execute query in addition to F5 this would be great. We've heard this from a few people, and having 2 shortcuts for our most common action doesn't seem unreasonable.

**Comment by anthonydresser** [comment]
Theres no reason you can't do this currently. It just not doable through the vscode ui as I can see, but you can edit the keybinding.json to assigning multiple keybindings to the same action

**Comment by kevcunnane** [comment]
Yep, the ask here is to just add a 2nd action so this "just works" out of the box. It's a fair ask to have the common command work across both, especially for macOS where the function keys aren't enabled by default. This is just to remove / reduce user friction.

**Comment by anthonydresser** [comment]
Wouldn't it make more since to have a different keybind for default on mac then? we can have different default commands between platforms. This seems like a niche request to have **_by default_** the same action on 2 different keybinds, when its easily configurable by the user.

**Comment by kevcunnane** [comment]
I don't fully understand what's wrong with having multiple keybindings for this. That's how it works in SSMS/SSDT. We're being more consistent with our own existing applications by doing this.

**Comment by kburtram** [comment]
Let's discuss in our weekly triage meeting whether this is something to take prior to GA or move to the backlog.

My personal opinion is that if this is something that VS Code already supports and it's easy to do then why not ease customer friction whenever we can.  Though I understand the position that if this isn't a common ask and is really an individual user(s) preference then why not let them setup their settings themselves exactly as they want.  In any case, it's certainly a valid suggestion to consider.

**Comment by kburtram** [comment]
Closing older issues.  Thanks for filing this suggestion.
