### ISSUE TITLE
Test.sh --grep arguments parsed incorrectly on Linux

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#8643]
When running test.sh with the --grep argument, only the first value in a space separated string is being picked up. For example, running test.sh --grep "Notebook Input" will run every test that starts with "Notebook". Internally it seems like **opts.grep** in **renderer.js** only has the first term "Notebook", and the rest of the string is discarded.

CC @Charles-Gagnon

**Comment by kburtram** [comment]
Closing older engineering-focused to prioritize customer facing bugs.  Please reactive if this is tracking work that is planned to be resolved soon.
