### ISSUE TITLE
Microsoft access database

### ISSUE THREAD

**Issue by adrianlfns** [microsoft/azuredatastudio#8652]
It would be really nice if I could use azuredatastudio to manage and run queries on microsoft access databases. 

- Azure Data Studio Version:

Steps to Reproduce:

**Comment by alanrenmsft** [comment]
@yualan @vickyharp  thoughts?

**Comment by adrianlfns** [comment]
Any update on this??

**Comment by yualan** [comment]
There are no plans on the roadmap for supporting Microsoft Access. Will be closing this issue, thank you for submitting.
