### ISSUE TITLE
Icon on desktop tab for ADS is very small.

### ISSUE THREAD

**Issue by smartguest** [microsoft/azuredatastudio#8662]
Steps to Reproduce:

1. Start running the build, and you'll see that the desktop tab icon is microscopic in comparison to other icons. See attached screenshot:

![Small Icon](https://user-images.githubusercontent.com/18018452/70752013-95d45d80-1ce6-11ea-9f48-ca5402609a43.png)

This doesn't look very good and it looks inconsistent with other apps.

**Comment by kburtram** [comment]
@Charles-Gagnon I think this is the second report of this type of an issue.  I haven't seen it myself.  Do you have any ideas?

**Comment by Charles-Gagnon** [comment]
Hmm, not off hand.

@smartguest Does this occur for both insiders and stable versions? If you uninstall and reinstall does it persist?

**Comment by smartguest** [comment]
This isn't Mac OS (Mine is Catalina 10.15.2 if you're wondering), this is for Windows 10, does not occur for the stable branch, nor is it in the insiders version, only when I try to run the master branch from visual studio code.

**Comment by Charles-Gagnon** [comment]
So interestingly enough I'm also now seeing this. It only happens for me on my secondary monitors though - is that the same experience you're seeing @smartguest or does this happen on all monitors?

Seems like VS Code also had this similar issue reported for MacOS as well : https://github.com/microsoft/vscode/issues/63068 Although I'm not seeing any similar reports for Windows. But until today we also had only ever seen reports of this on MacOS so I'm not sure if this was a recent break or what. Looking into it but this currently is looking like most likely an upstream issue...

**Comment by Charles-Gagnon** [comment]
@smartguest Can you try cleaning your repo (git clean -fxd, make sure you stash any changes you have before doing this) and then rebuilding and see if this still repros? You might need to restart explorer.exe after doing that too - but after doing that the icon is back to the regular size for me.

**Comment by alanrenmsft** [comment]
@smartguest could you please move this into a milestone?
