### ISSUE TITLE
Transport Level Error on Ubuntu

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8684]
This [issue](https://github.com/microsoft/vscode-mssql/issues/1241#issuecomment-491267630) was opened in the [vscode-mssql](https://github.com/microsoft/vscode-mssql) repository, but the user saw the same issue in ADS as well.

> When trying to execute a long query I'm getting some sort of timeout apparently? I'm not sure about what's happening. The error message I receive is the following:
> ```
> A transport-level error has occurred when receiving results from the server. (provider: TCP Provider, error: 35 - An internal exception was caught).
> ```
> 
> The strange thing is that I have no problem when trying to run a simpler version of the query, it works fine. Also, another thing I noticed is that when running the same long query on Windows through SQL Management Studio does actually work, so maybe there are some hidden configurations on Linux or inside VS Code that are different from SQL MS?

**Comment by kburtram** [comment]
Closing older issues without current repro reports.  Please let us know if you're still impacted by this issue.

**Comment by richard-ob** [comment]
I get this error on Ubuntu also. I migrated my existing DB from Azure to an Ubuntu VPS, and get these errors intermittently in production applications, maybe once an hour on queries that had never previously failed. There seems to be little info out there unfortunately.
