### ISSUE TITLE
Not able to authenticate to a Azure SQL via Azure AD Account with the subscription in a different Tenant

### ISSUE THREAD

**Issue by DerAlbertCom** [microsoft/azuredatastudio#8696]
We have an Office 365 Organization. We have several Azure Subscription, one older Subscription (was created without Office 365, this is our Developer Subscription), but are are members of that Azure AD. And it works like a charm, except with Azure Data Studio.

We have Setup a Azure SQL Database with access via Azure AD Account only (and managed identity from the WebApplication). We have no problem to connect via Micorosoft SQL Server Managmenet Studio (if with set the right tenant id), also we can connect with a user over the Azure Portal via the Query Editor. 

But we are not able to connect to that database. we get: Login failed for user 'NT AUTHORITY\ANONYMOUS LOGON'.  as an error.

I know that this error happens if we don't select the right azure tenant for the connection. But there are some problems with Azure Data Studio.

But Using the SQL Management Studio is not an option on Mac OS.

I have setup my azure account in azure data studio. This works. Also i can see  in the Azure Pane all my Subscriptions, Servers and Database which i can access (even the Developer Stuff). But when i try to manage from there database the  connection faile. Because in the Connection Details is SQL Login prefilled as Authentication Type, not Azure Active Directory. If i choose Azure Active Directory my account will be used but Azure AD Tenant is empty, no option to select one.

If I try to connect to a SQL Database of an Subscription which is bound to our office 365 then i'm able to connect.

Some obervations. Sometine (for whatever reason) i can select an Azure Tenant in the Connection Details, but this seems to be ignored because it does not help.

I choose to select the database the connection details dropdown, no no database for the server is showing up. For the Database in the right Active Directory Tenant the Database shows up.

I'm member the Azure AD Group which is selected as the AD Administration Group.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:00:55.976Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz (16 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|64.00GB (33.04GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
profiler|Mic|0.9.0

</details>

**Comment by aaomidi** [comment]
Hey! Thanks for reporting this, can you see if this comment fixes your problem:

https://github.com/microsoft/azuredatastudio/issues/7619#issuecomment-566231484

**Comment by DerAlbertCom** [comment]
Yes, mostly (now i can work) but still a hickup, i commented on the other issue.
