### ISSUE TITLE
Server icons incorrect for dark theme

### ISSUE THREAD

**Issue by abist** [microsoft/azuredatastudio#8698]
Server icons for the Connections explorer seem incorrect for Dark Theme -

![Capture](https://user-images.githubusercontent.com/6411451/70933638-32ea0b80-1ff1-11ea-9072-ba227c1b19cf.JPG)

![Capture](https://user-images.githubusercontent.com/6411451/70936209-b22e0e00-1ff6-11ea-977c-25cbd1aedf91.JPG)

**Comment by kburtram** [comment]
@anthonydresser could you please provide an update on this issue when you have a chance?  This will block the 1.14 release so I'd like to merge a fix as soon as possible.  Thanks!

**Comment by anthonydresser** [comment]
I patched the wrong section of code before I left this afternoon, I'll try again this evening. Worse case scenario we can just remove the min from the compile in the release branch which is causing this.

**Comment by kburtram** [comment]
@anthonydresser thanks for the update!  If we don't have a fix tomorrow let's looking into removing minimization for this month's release build.
