### ISSUE TITLE
Error on recovery from hot exit for a basic notebook

### ISSUE THREAD

**Issue by vickyharp** [microsoft/azuredatastudio#8700]
Issue Type: <b>Bug</b>

I had a simple unsaved SQL notebook with a "select * from sys.databases" query open when I restarted my laptop for a Windows update. On reopen, the notebook did not open, but two errors were shown in the error pane. On clicking on the error, the notebook JSON opened as shown.

![image](https://user-images.githubusercontent.com/8250560/70937451-2e295580-1ff9-11ea-8191-27413b32bf26.png)

Notebook attached as .txt 
[notebook error.txt](https://github.com/microsoft/azuredatastudio/files/3969856/notebook.error.txt)

Azure Data Studio version: azuredatastudio-insiders 1.14.0-insider (659f39219623b7005416f38ef3e8b50d064c9886, 2019-12-11T05:59:08.400Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.75GB (6.43GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
I saw this one time last night as well.  But I didn't have a consistent repro.

**Comment by chlafreniere** [comment]
I saw this once this afternoon when i killed the ADS process. not consistent otherwise, though. will move to Feb.

**Comment by kburtram** [comment]
Closing older issues without recent repro reports.  Please reactive if you're still impacted by this bug.
