### ISSUE TITLE
Connection type is blank for CMS connection dialog

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8708]
- Azure Data Studio Version: 1.8

Steps to Reproduce:

1. Add a CMS connection

Expected: Server type says something like `SQL Server CMS` or whatever it used to say.

![image](https://user-images.githubusercontent.com/599935/70951698-f4684700-2018-11ea-92c5-d5f23353a7c1.png)

**Comment by abist** [comment]
Seems to be broken by - https://github.com/microsoft/azuredatastudio/pull/8419

@swjain23  Please add owners/people who have worked on the files as reviewers when making changes.

**Comment by kburtram** [comment]
@abist do you think we should take a fix for this in Dec?

**Comment by abist** [comment]
@kburtram Yes, I'm working on a fix right now and will send a PR soon
