### ISSUE TITLE
Database dropdown is expanding its width after initial open

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8709]
![screen](https://user-images.githubusercontent.com/28519865/70954153-da326700-2020-11ea-8f6d-039ffe97a4b1.gif)

**Comment by Charles-Gagnon** [comment]
@aaomidi Could you look at this when you get a chance? This seems to be a regression and likely tied to your changes made for increasing the dropdown width.

**Comment by aaomidi** [comment]
Sorry I didn't see the notification for this yesterday.

**Comment by kburtram** [comment]
Bring into Dec to discuss. Though I suspect this isn't at the current triage bar.

**Comment by aaomidi** [comment]
From @Charles-Gagnon 

>  I don't think this is worth bringing to ask mode but you may want to bring it up so at least people are aware the behavior is going to be a bit weird if we leave it as is

**Comment by kburtram** [comment]
@aaomidi I agree after seeing in the product that this doesn't meet Dec. bar.  I'll move to Feb milestone.
