### ISSUE TITLE
Refresh on Tables doesn't work

### ISSUE THREAD

**Issue by igormicev** [microsoft/azuredatastudio#8718]
Issue Type: <b>Bug</b>

When I click refresh on the Tables folder the refresh is made for the whole tree structure instead of for the Tables node only. Also, not everything should be collapsed, but the tree structure should remain as the user's left it before the Refreshing.

BR, Igor Micev

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.90GB (2.16GB free)|
|Process Argv||
|Screen Reader|no|
|VM|33%|
</details><details><summary>Extensions (16)</summary>

Extension|Author (truncated)|Version
---|---|---
firstresponderkit|dre|0.5.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.1
agent|Mic|0.44.0
cms|Mic|0.5.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
powershell|ms-|2019.11.0
profiler|Mic|0.9.0
query-history|Mic|0.1.0
schema-compare|Mic|1.0.0
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.6
simple-data-scripter|sea|0.1.0
vscodeintellicode|Vis|1.2.1

</details>

**Comment by Charles-Gagnon** [comment]
These issues should be fixed by https://github.com/microsoft/azuredatastudio/pull/8625 - you can download the latest insiders to try it out otherwise the next stable build should be out this week and will contain those fixes. Let me know if you're still seeing issues after that!
