### ISSUE TITLE
Notebook edits to markdown cells cannot be undone after switching to preview mode

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#8723]
Issue Type: <b>Bug</b>

While editing Notebooks the user has to keep switching between the preview and edit mode of a markdown cell. However after making some unwanted changes there is no Undo (Ctrl+Z). Undo/Redo should work as you toggle between the edit and preview modes.

Azure Data Studio version: azuredatastudio 1.13.0 (c7d7faa1670e829a8252cbf83ec691496f4d0502, 2019-10-30T18:45:12.404Z)
OS version: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment]
@qifahs @MsSQLGirl  If you could provide specific examples of what isn't working as you'd expect that would be great. So far in my testing I've found that the only scenario that doesn't seem to work is 

1. Switch to markdown/split view mode
2. Make change in MD cell
3. Switch to rich text mode
4. Try to undo change

If I do the reverse (make change in rich text and switch to markdown/split view) then the undo seems to work as I'd expect. 

Can you confirm that this is the only scenario that's broken here?

**Comment by qifahs** [comment]
In general it should be possible to undo a change on any cell. Another scenario which is broken is jumping between cells:
- Edit markdown cell
- Click on a code cell
- Come back to the markdown cell
- Try to undo change

This works for a code cell though. You can go back to a code cell after loosing focus on it, and undo the code you had written there. Markdown cell seems to loose the change history as soon as you click out of it.

**Comment by chlafreniere** [comment]
Chatted with Julie on this; this work was delayed given unexpected telemetry work that @Charles-Gagnon had to pick up. @corivera is taking over this and working on this currently.
