### ISSUE TITLE
Separate "Delete Connection" from "Disconnect" more in context menu

### ISSUE THREAD

**Issue by mikewo** [microsoft/azuredatastudio#8725]
**Is your feature request related to a problem? Please describe.**
When you have a connection with a database and you click in the navigation tree to get the context menu to disconnect the connection the "Delete Connection" option is very close to the disconnect. Twice now I've accidentally clicked on Delete instead and had to reconfigure the connection. It doesn't look like there is a way to organize the connections within a server group other than the order they are added, so if you are trying to organize the nodes in some way that gets lost when you have to recreate a connection.

**Describe the solution or feature you'd like**
Either separate the two options more with a separator, better yet, move the "Delete Connection" to the bottom of the context menu with a separator directly above it.

**Describe alternatives you've considered**
Have a configuration option to prompt if the user really wants to delete the connection before doing so.

**Comment by kburtram** [comment]
We've added the `Edit Connection` menu item which is now between delete and disconnection.  Please let us know if you're still impacted by this issue.  Thanks!

**Comment by mikewo** [comment]
This looks like it will work just fine. Thanks!
