### ISSUE TITLE
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output

### ISSUE THREAD

**Issue by cwkoenigs** [microsoft/azuredatastudio#8729]
Issue Type: <b>Bug</b>

1. Install Azure Data Studio 
2. Configure Python For Notebooks
3. Use new python installation 
4.  Change kernel from SQL to Python: 

Expected Result: Kernel Change
Actual Result: Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output

Azure Data Studio version: azuredatastudio-insiders 1.15.0-insider (0fd870d156c4d1e2831e9f9f1bb37a1935e8fa6f, 2019-12-18T05:47:05.663Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.88GB (7.56GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
Hi @cwkoenigs, sorry to hear that you're having an issue with python and notebooks. Can you verify that the issue persists when you close and reopen Azure Data Studio?

I tried myself on a clean machine and couldn't reproduce this issue unfortunately. It would be helpful if you could paste the output for the "Notebooks" channel:

- View menu -> Output
- From the dropdown, select "Notebooks"

What you should see is a "Starting Notebook server" followed by a "Jupyter is running at..." message.

**Comment by cwkoenigs** [comment]
"c:\Users\python_azure\0.0.1\python.exe" -m jupyter notebook --no-browser --no-mathjax --notebook-dir "c:\Users" --port=9304 --NotebookApp.token=492ad591583ed0dbbeed2e718dfa740ce58902369e7dc4ef

Is what I see...But I still receive the error, even if I open and close.

**Comment by corivera** [comment]
The Users folder is a system folder, so there may be permissions issues when using that folder. If you re-run the python setup using your own user folder (like in %USERPROFILE%) does the notebook start successfully?

**Comment by marknhenry** [comment]
Still facing an issue here.  Tried all solutions, but I still get the same error.  I even tried installing the python libraries in a location not under Users.

**Comment by cwkoenigs** [comment]
> The Users folder is a system folder, so there may be permissions issues when using that folder. If you re-run the python setup using your own user folder (like in %USERPROFILE%) does the notebook start successfully?

This answer solved my problem! Thank you.

**Comment by samikhwaireh** [comment]
still facing the same issue, I tried all the solutions, and here is the output 

... Starting Notebook server
"C:\Users\root_user\anaconda3\python.exe" "c:\Users\root_user\AppData\Local\Programs\Azure Data Studio\resources\app\extensions\notebook\resources\pythonScripts\startNotebook.py" --no-browser --ip=127.0.0.1  --no-mathjax --notebook-dir "c:\Users\root_user" --NotebookApp.token=31e01f003c85b5ede0c00daec9ae44ef1a29e14d8581e1c2

**Comment by johninstockie** [comment]
Just doesnt work if you do not have admin on your laptop...

**Comment by johninstockie** [comment]
Failed to change kernel. Kernel SQL will be used. Error was: Invalid response: 500 Internal Server Error
