### ISSUE TITLE
add more logging to the build scripts

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#8730]
specifically for this script build/azure-pipelines/linux/createDrop.sh, when the step fails, we only get a message stating that bash exited with code 1.

**Comment by anthonydresser** [comment]
The logging issue is something wrong with devops, if you take a look at other runs for that step there is lots of logging.

**Comment by alanrenmsft** [comment]
ado issue, found the related log in the full log.
