### ISSUE TITLE
While editing markdown, find widget scrolls away if the markdown is too big

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#8739]
Issue Type: <b>Bug</b>

Repro:
- In a Notebook, create a markdown cell which is more than one page long. You need a big markdown cell to repro this issue.
- Edit the markdown and scroll down more than a page.
- Hit Ctrl+F. The find widget is not visible anymore. It looks like Ctrl+F is a no-op. You have to scroll to the beginning of the markdown to see the find widget.
![image](https://user-images.githubusercontent.com/7318752/71137142-f0c0f580-21bb-11ea-9059-d178510be36a.png)

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

**Comment by MaddyDev** [comment]
@qifahs Can you share the markdown file. I have one with which am not able to repro it.
