### ISSUE TITLE
SSL Error 

### ISSUE THREAD

**Issue by 0Architectus0** [microsoft/azuredatastudio#8743]
Issue Type: <b>Bug</b>

Azure Data Studio returns an SSL error when attempting to connect with Azure cloud account. 

Error: write EPROTO 3166410856:error:100000f7:SSL routines:OPENSSL_internal:WRONG_VERSION_NUMBER:../../third_party/boringssl/src/ssl/tls_record.cc:242:

Where can the solution to this be found?

Thanks,
Vincent Rodriguez

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6650U CPU @ 2.20GHz (4 x 2208)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.62GB (3.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.44.0
dacpac|Mic|1.0.0
import|Mic|0.12.0
profiler|Mic|0.9.0
schema-compare|Mic|1.0.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by aaomidi** [comment]
This seems like some sort of corrupted ssl issue.

Does it repro everytime you try to login?
