### ISSUE TITLE
OE expansion fails with "invalid argument" after hibernation

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8747]
- Azure Data Studio Version: 1.14.0

Steps to Reproduce:

1. Connect to server (Azure DB in my case)
2. Hibernate computer (close macbook laptop in my case)
3. Log back into computer and try to use connection

Expected: Connections are reestablished

Actual: Connection is not reestablished and I get "invalid argument" errors in OE

<img width="510" alt="Screen Shot 2019-12-19 at 11 39 54 AM" src="https://user-images.githubusercontent.com/599935/71204417-f1599a80-2254-11ea-8304-e90ead7f984d.png">

**Comment by alanrenmsft** [comment]
tracked by issue: https://github.com/dotnet/SqlClient/issues/359, do we still need to keep this open? @kburtram

**Comment by kburtram** [comment]
Closing since this is tracked upstream in dotnet/SqlClient#359.
