### ISSUE TITLE
listInactiveSelectionBackground color was too faint on both light and dark theme to be noticeable

### ISSUE THREAD

**Issue by eligoldner** [microsoft/azuredatastudio#8748]
Light theme - current view
![light-theme-current-color](https://user-images.githubusercontent.com/763806/71208173-77d2a400-2276-11ea-9240-5affffd04b65.png)

Light theme - suggested color
![light-theme-new-color](https://user-images.githubusercontent.com/763806/71208170-77d2a400-2276-11ea-8dc8-777b174a41fa.png)

Dark theme - current view
![dark-theme-current-color](https://user-images.githubusercontent.com/763806/71208171-77d2a400-2276-11ea-959e-3665ca82e418.png)

Dark theme - suggested color
![dark-theme-new-color](https://user-images.githubusercontent.com/763806/71208172-77d2a400-2276-11ea-954b-15b170d2a369.png)

The background colors of files selected in the explorer are too faint to be noticeable while the focus is outside of the explorer (e.g. while you're in the editor).

**Comment by kburtram** [comment]
Closing this issue as the associated PR was closed.  Please let us know if this issue is still impacting your use case.
