### ISSUE TITLE
Notebooks: Disable the Add Code/Add Text popups

### ISSUE THREAD

**Issue by gbritton1** [microsoft/azuredatastudio#8756]
**Is your feature request related to a problem? Please describe.**
I'm frustrated when using a notebook to demo something in ADS.  The popups that appear when moving with the mouse from cell to cell (Add Text and Add Code) make the presentation look messy.

**Describe the solution or feature you'd like**
I'd like to see a way to disable the Add Text / Add Code popups for situations like this.

**Describe alternatives you've considered**
There really are no alternatives that I'm aware of.

**Additional context**
![image](https://user-images.githubusercontent.com/12263288/71222976-6d2d0480-22a0-11ea-82d0-cf02eab6efac.png)

**Comment by chlafreniere** [comment]
This has since been done; in the June release, the popups no longer appear.
