### ISSUE TITLE
Transfer data from Windows network path to SQL Server Big data cluster HDFS

### ISSUE THREAD

**Issue by dddd45** [microsoft/azuredatastudio#8758]
I am new to Big data and SQL Server Big data cluster. There are a ton of folders/sub folders with a few files in each sub folder, please anyone lets me know how to transfer them to HDFS SQL Server Big data cluster on Ubuntu.

Thanks

**Comment by Charles-Gagnon** [comment]
Currently you can't upload an entire directory of files through the ADS UI. You can select multiple files though from the file picker dialog - they just have to be in the same directory.

If that's not a viable option then you can use the azdata tool directly to copy the directory : https://docs.microsoft.com/sql/big-data-cluster/reference-azdata-bdc-hdfs?view=sql-server-ver15#azdata-bdc-hdfs-cp

**Comment by dddd45** [comment]
Thank you
