### ISSUE TITLE
%set_env VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{},

### ISSUE THREAD

**Issue by SQLvariant** [microsoft/azuredatastudio#8759]
Issue Type: <b>Bug</b>

I'm not sure if this is a PowerShell-kernel or a Notebooks issue, so I'm opening this issue here just in case it's a Notebooks issue:
https://github.com/vors/jupyter-powershell/issues/34

Azure Data Studio version: azuredatastudio-insiders 1.15.0-insider (778a34a9d288da35279e3ffe0c2aca19e1c8d7ed, 2019-12-20T05:31:39.928Z)
OS version: Windows_NT x64 10.0.19041

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.20GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (15)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
cms|Mic|0.6.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.1.0
server-report|Mic|0.2.1
sql-dw|Mic|0.0.1
azdata-sanddance|msr|1.3.9
vscode-docker|Pet|0.5.2
sql-search|Red|0.3.6

</details>

**Comment by chlafreniere** [comment]
This should be fixed with the latest version of the powershell_kernel (0.1.3). @SQLvariant please let us know if you see this after updating and feel free to reopen if so.

**Comment by lerchdude** [comment]
Seeing this with 0.1.3

Issue Type: <b>Bug</b>

Occasionally, after toggling the kernel in a notebook (FWIW I am typically using PowerShell), I will get an error that is unrelated to the code in the cell during its first execution. For example:

```
At line:58 char:37
+ %set_env VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{}, ...
+                                     ~~~~~~~~
Unexpected token ':"en-us"' in expression or statement.
At line:58 char:45
+ %set_env VSCODE_NLS_CONFIG={"locale":"en-us","availableLanguages":{}, ...
+                                             ~
Missing argument in parameter list.
At line:1 char:3
+ . {
+   ~
Missing closing '}' in statement block or type definition.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 
}
At line:1 char:1
+ }
+ ~
Unexpected token '}' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnexpectedToken
 

. {
>> Start-Sleep -Seconds 2
>> 
````

I also noticed a brief pop-up saying  "Kernel is dead".

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (d6b5d3c6b1c717a02e791175417b5d31c5b017b3, 2020-02-27T18:07:15.223Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|159.90GB (36.71GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
