### ISSUE TITLE
105082 ; Erreur ODBC générique : [Oracle][ODBC]Invalid SQL data type <-25>. .

### ISSUE THREAD

**Issue by khelouim** [microsoft/azuredatastudio#8761]
- Azure Data Studio Version:

Steps to Reproduce:

1.
CREATE EXTERNAL DATA SOURCE Sourceoracleodbcinstant19
WITH ( LOCATION = 'odbc://SRV-PR-SQL16P7',
PUSHDOWN = ON,
CREDENTIAL = ConsulB  ,CONNECTION_OPTIONS = 'DSN = oracleodbcinstant19;ssl=false') 

CREATE EXTERNAL TABLE DBO.ORACATEG_EMPLOYE_TBInst19
(
	CLIENTCODE	  TINYINT  , --in oracle it is number(3)
	CATEG_EMPL_CODE	TINYINT   ,--in oracle it is number(1)
	[DESCRIPTION]	  NCHAR(40) COLLATE Latin1_General_BIN NULL --in oracle it is NCHAR(40)
)
WITH (DATA_SOURCE = Sourceoracleodbcinstant19 ,LOCATION = N'RLGI01.FP.CATEG_EMPLOYE_TB');

Msg 105082, Niveau 16, État 1, Ligne 52
105082 ; Erreur ODBC générique : [Oracle][ODBC]Invalid SQL data type <-25>. .

Heure de fin : 2019-12-20T09:45:46.6220540-05:00

**Comment by kburtram** [comment]
Closing this older issue as it's not clear what the Azure Data Studio scenario is broken from the report.  Please let us know if you're still impacted by this issue.
