### ISSUE TITLE
1.14 version does not run under LocalSystem

### ISSUE THREAD

**Issue by genifycom** [microsoft/azuredatastudio#8762]
- Azure Data Studio Version:

Steps to Reproduce:

1. Version 1.13.1 runs fine under Local System using 
Administrative Command Prompt:
Run psexec64 -i -s cmd.exe
In the new "nt authority\system" command promt:
Run "C:\Program Files\Azure Data Studio\azuredatastudio.exe"

The application starts and runs as normal.

After upgrade to 1.14, when trying this same scenario, the application starts and you can see it in the taskbar, but the UI will not activate.

Tried this on multiple machines now and same result. We have had to back down all 1.14 back to 1.13.1 in order to use Azure Data Studio

**Comment by alanrenmsft** [comment]
@genifycom I am not able to reproduce the issue. do you see any error in the command window or in this folder: C:\Windows\System32\config\systemprofile\AppData\Roaming\azuredatastudio\logs?

**Comment by genifycom** [comment]
So I ran version 1.13.1 under Local System and that ran fine (run from the Command Prompt as "C:\Program Files\Azure Data Studio\azuredatastudio.exe"). Then I upgraded to 1.14.1
I ran the same command.
The command line says
update#setState idle
update#setState checking for updates
[VS Code]: detected unresponsive

Then I get a Dialog saying "The window is no longer responding" Reopen, Keep Waiting, Close

Mouse on the Azure Data Studio Icon shows [Administrator] (unresponsive)

It is definitely a permissions issue. Running from the Task Bar via the icon opens immediately.
So the test is run Administrative Command Prompt. Run psexec64 -i -s cmd.exe
In the new CMD prompt, run "C:\Program Files\Azure Data Studio\azuredatastudio.exe"

I see that Azure Data Studio does eventually open. It is taking several minutes.

Please advise if you can reproduce.

**Comment by genifycom** [comment]
BTW, I see the log directories. Which file should I be looking at for you (there are several directories and files in there)?

**Comment by alanrenmsft** [comment]
@genifycom still no repro from our team. and you are saying it eventually worked after several minutes? to help understanding the issue, do you mind zipping up log files and send it to me (alanren@microsoft.com)? also do you see anything error in the Windows event viewer?

**Comment by genifycom** [comment]
[logs.zip](https://github.com/microsoft/azuredatastudio/files/4048829/logs.zip)

**Comment by alanrenmsft** [comment]
@abist , Hi Aditya, I will be on vacation, could you please take a look at this one?

**Comment by genifycom** [comment]
What else do I need to send? I can record video of the behavior or additional logs.

**Comment by genifycom** [comment]
Here are the timing. After requesting "C:\Program Files\Azure Data Studio\azuredatastudio.exe" in an "nt authority\system" command prompt. I do not touch anything.

Here are the messages shown in the CMD window.
 [main 2020-01-23T15:04:20.331Z] update#setState idle
[main 2020-01-23T15:04:50.333Z] update#setState checking for updates
[main 2020-01-23T15:04:50.635Z] update#setState idle

Notice that 30 seconds pass from the first idle to the "checking for updates" happens.
The window opens around 2 minutes after issuing the start program command.

**Comment by genifycom** [comment]
There are no errors shown in the Event log

**Comment by abist** [comment]
@genifycom Unfortunately I couldn't repro this issue either. Could you try running the application with the flag `--verbose` i.e. `"C:\Program Files\Azure Data Studio\azuredatastudio.exe" --verbose`  and paste the logs here?

**Comment by genifycom** [comment]
Thank you for that. --disable-gpu allows immediate opening. I suspect LogMeIn is interfering somehow. Have to use LogMeIn since these 30 machines are not on a Corporate network and are standalone.

So now I have a workaround.
