### ISSUE TITLE
Color theme should allow the terminal color to change independently

### ISSUE THREAD

**Issue by AdamWilbur** [microsoft/azuredatastudio#877]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1.  Change a theme, and notice that you cannot change the terminal window independent of the theme.  I prefer my SQL, and Python windows with a light theme, but I am used to seeing my Powershell terminal in "Powershell blue".  Currently this theme is impossible. 
2.

**Comment by Tyriar** [comment]
You can do this now in vscode by setting theme keys in `workbench.colorCustomizations`

**Comment by kburtram** [comment]
This was fixed upstream.  Thanks @Tyriar!
