### ISSUE TITLE
Reload message and choice not provided

### ISSUE THREAD

**Issue by ToddABarnes** [microsoft/azuredatastudio#8772]
Issue Type: <b>Bug</b>

If a notebook is open in ADS and it's .ipynb file is changed there is no reload of the file, no prompting to let the user the file has changed.  It is as if nothing has been altered.

repro steps:
- load a .ipynb file
- alter the .ipynb file (copy a different .ipynb file over the source .ipynb file)
- note the loaded file does not change, there is no message or option to reload.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (6.64GB free)|
|Process Argv|C:\ADSLiveSite\Dev\ADS LiveSite Support\TSG\Backup Restore (Sterling)\[How to] Get Backup MDS Logs.ipynb|
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by chlafreniere** [comment]
Fixed by #12309. ADS should show the change automatically now.
