### ISSUE TITLE
Sorting by clicking table header doesn't work

### ISSUE THREAD

**Issue by nitzanms** [microsoft/azuredatastudio#8774]
Issue Type: <b>Bug</b>

1. Create a profiler session
2. Set up filters
3. Start profiler, get results, pause
4. Sort (eg by TextData)
5. TextData is not sorted correctly

Azure Data Studio version: azuredatastudio 1.8.0 (96e214593190071f0b520439929b218f9fa673de, 2019-06-06T01:59:30.203Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz (8 x 3600)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.87GB (30.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by aaomidi** [comment]
Unable to repro this.

**Comment by aaomidi** [comment]
I'm going to close this issue. If this problem happens again please comment back!
