### ISSUE TITLE
V1.14.0 does not work at all

### ISSUE THREAD

**Issue by olebenny** [microsoft/azuredatastudio#8776]
Issue Type: <b>Bug</b>

I just upgraded to 1.14.0, and it does not work at all.
Results and Messages windows is empty.
Status line shows: 179983 rows 00:02:34, but none 'exporters'
How do I downgrade ??

Version: 1.14.0 (user setup)
Commit: 27468f75a5c969736ff663140d46f927d3ac749b
Date: 2019-12-18T20:21:08.840Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Ole Benny Hansen

Azure Data Studio version: azuredatastudio 1.14.0 (27468f75a5c969736ff663140d46f927d3ac749b, 2019-12-18T20:21:08.840Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.78GB (16.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
schema-compare|Mic|1.1.0
server-report|Mic|0.2.1
sql-dw|Mic|0.0.1
azdata-sanddance|msr|1.3.9
vscodeintellicode|Vis|1.2.1

</details>
<img width="1228" alt="AzureDataStudio_V1 14 0" src="https://user-images.githubusercontent.com/23648154/71444592-cc609e00-2712-11ea-8a09-b7ab22ac7e0d.png">

**Comment by anthonydresser** [comment]
Dupe #8768, we have a fix in the pipeline. In the mean time you can work around this by closing and reopening files that were automatically opened by the hotexit.

**Comment by olebenny** [comment]
Hi Anthony

Thanks, I am running again.

Best regards

Ole

**Comment by kburtram** [comment]
Please update to 1.141. to resolve this issue.  Sorry for the inconvenience.
