### ISSUE TITLE
Results and Messages Not Returning Data

### ISSUE THREAD

**Issue by ooriblestsmshemir** [microsoft/azuredatastudio#8777]
When I run a query, nothing is shown in the results or messages.  The results and messages windows/tabs are completely blank.

I am successfully authenticated to the database.  I see the objects in the explorer.  The abbreviated messages in the bottom ribbon update correctly.  (For example, if I execute a select query limited to 5 rows, the blue ribbon at the bottom correctly shows "5 rows" and the execution time.)

I can execute the queries in pgAdmin or the command line with the same user-context.

I upgraded to the latest version this morning.

Version: 1.14.0 (system setup)
Commit: 27468f75a5c969736ff663140d46f927d3ac749b
Date: 2019-12-18T20:21:08.840Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by ooriblestsmshemir** [comment]
When I open a new tab, or right-click over a table/view and select "return top 1000 rows" the results are returned correctly, but still not from an existing tab.  It's like the connection between the old tab and the data stream is broken the step directly before when the data is displayed.

**Comment by kburtram** [comment]
@ooriblestsmshemir please update to version 1.14.1 to resolve this issue.  Sorry for the inconvenience.
