### ISSUE TITLE
Profiler: Failed to create session (1.14.1)

### ISSUE THREAD

**Issue by kross51** [microsoft/azuredatastudio#8782]
- Azure Data Studio Version:
Version: 1.14.1 (user setup)
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:42:26.303Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

Steps to Reproduce:

1. Register Azure DB Server / Database (BC_Gen5_40 ; Compatibility Level 130)
2. Launch Profiler ( Standard_Azure / ADS_Standard_Azure)
3. Click "Start" button
* EXCEPTION Dialog Box Shown:
Failed to create session: An exception occurred while executing a Transact-SQL statement or batch.

Also, I tried to create the event session manually in SSMS like other bug comments suggested but got the following error:

Msg 25632, Level 16, State 29, Line 1
The specified buffer size is less than the minimum size. The minimum allowed size is 13066200 bytes.

from executing in SSMS:

```CREATE EVENT SESSION [ADS_Standard_Azure] ON DATABASE ADD EVENT sqlserver.attention( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.existing_connection(SET collect_options_text=(1) ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), ADD EVENT sqlserver.login(SET collect_options_text=(1) ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), ADD EVENT sqlserver.logout( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), ADD EVENT sqlserver.rpc_completed( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.sql_batch_completed( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), ADD EVENT sqlserver.sql_batch_starting( ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))) ADD TARGET package0.ring_buffer(SET max_events_limit=(1000),max_memory=(51200)) WITH (MAX_MEMORY=8192 KB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)```

**Comment by kross51** [comment]
FYI: Executing the following workaround works (as opposed to the above):

CREATE EVENT SESSION [ADS_Standard_Azure]
ON DATABASE ADD EVENT sqlserver.attention( 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) 
WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), 
ADD EVENT sqlserver.existing_connection(SET collect_options_text=(1) 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), 
ADD EVENT sqlserver.login(SET collect_options_text=(1) 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.username,sqlserver.session_id)), 
ADD EVENT sqlserver.rpc_completed( 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) 
WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), 
ADD EVENT sqlserver.sql_batch_completed( 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) 
WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))), 
ADD EVENT sqlserver.sql_batch_starting( 
ACTION(package0.event_sequence,sqlserver.client_app_name,sqlserver.client_pid,sqlserver.database_id,sqlserver.username,sqlserver.query_hash,sqlserver.session_id) 
WHERE ([package0].[equal_boolean]([sqlserver].[is_system],(0)))) 
ADD TARGET package0.ring_buffer(SET max_events_limit=(1000)) 
WITH (MAX_MEMORY=16 MB,EVENT_RETENTION_MODE=ALLOW_SINGLE_EVENT_LOSS,MAX_DISPATCH_LATENCY=5 SECONDS,MAX_EVENT_SIZE=0 KB,MEMORY_PARTITION_MODE=PER_CPU,TRACK_CAUSALITY=ON,STARTUP_STATE=OFF)

**Comment by kburtram** [comment]
Closing older issues without current repro reports.  I didn't encounter this issue when testing profiler earlier today on a current build.  Please let us know if you're still impacted by this issue.
