### ISSUE TITLE
Setting misspelling

### ISSUE THREAD

**Issue by DbCutter** [microsoft/azuredatastudio#8788]
- Azure Data Studio Version:  1.14.1
- My OS:  Windows Server 2016 Datacenter

Steps to Reproduce:
1. Open Settings
1. Navigate to section:  Data > SQL
1. Observe misspelling
    Save As Csv: Line Seperator

SettingID
> sql.saveAsCsv.lineSeperator

SettingID as JSON
> "sql.saveAsCsv.lineSeperator": null

**Comment by smartguest** [comment]
It should be Separator apparently, but this is mainly a cosmetic issue

**Comment by anthonydresser** [comment]
Fixing the spelling here will potentially break existing users that have this setting set.

**Comment by aaomidi** [comment]
What do we want to do with this?

**Comment by Charles-Gagnon** [comment]
I think just close it. There's no user impact and while unfortunate changing the setting would either require some extra logic to port over the setting to the new value or resetting it for all users - neither which are great options.

**Comment by kburtram** [comment]
Closing older lower-impact issues.  Too bad we didn't have spellcheck enabled in the code reviews when adding that setting.
