### ISSUE TITLE
hanning on connect 

### ISSUE THREAD

**Issue by ghostiewm** [microsoft/azuredatastudio#8793]
Issue Type: <b>Bug</b>

Cannot connect to data sourcre 

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-1650 v3 @ 3.50GHz (12 x 3492)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.92GB (38.03GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|0.0.3
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.2
cms|Mic|0.6.0
dacpac|Mic|1.1.0
import|Mic|0.12.0
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by Charles-Gagnon** [comment]
- How long are you waiting for the connection? 

-What type of server are you connecting to (SQL on-prem, azure, etc)?
-If you open the dev console (Help -> Toggle Developer Tools) and go to the Console tab are there any errors there? 
- Are you able to connect to any other servers and if so are they similar to this one?
