### ISSUE TITLE
Query results are disappearing after switching to new query tab

### ISSUE THREAD

**Issue by stona1** [microsoft/azuredatastudio#8795]
- Azure Data Studio Version:
Version: 1.14.1 running on MacOS Catalina 10.15.2
Commit: f9b968c1ae514a0d1210788629e1c69125857279
Date: 2019-12-24T02:37:56.865Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.2.0

Steps to Reproduce:

1. Open or create query
2. Open or create query in another tab
3. Run that query (results are shown)
4. Switch to tab with first query
5. Run the query
6. Switch to second tab and query result disappear 
7. Switch to first tab and query result disappear too

Important: If you click 'Message' (next to 'Result') it will show results but it will always shows results from last run query not the results from current tab. It is really misleading. 

BR
Arek

**Comment by anthonydresser** [comment]
I can't seem to repro with the steps provided. Are there any errors in the log (F1 -> developer: show logs -> Window)

**Comment by stona1** [comment]
It is fully replicable on my two Macs but I found that sometimes on the first run everything is OK. When I run it again (restart ADS) appears. 

Yes, there is one error in console:
[2020-01-04 10:00:29.034] [renderer1] [error] No application in the Launch Services database matches the input criteria.: Error: No application in the Launch Services database matches the input criteria.

**Comment by CoolDadTx** [comment]
This happens to me as well. It only happens on specific queries though. Specifically the query that is seeing this issue is a saved SQL file that is opened in the editor every time I start ADS. Any new query windows that you open during the session are fine. I wonder if it is related to the recent bug that was fixed where the editor wouldn't render results for queries that were saved. This was fixed in the most recent update.

**Comment by CoolDadTx** [comment]
Interestingly, if you click on the Message tab and then back on the Results tab you do see some query results but they are for a completely different query. In my case the results are similar to the results I have in another unsaved query window but the columns are not all there. So I have no idea where these results are coming from unless they are cached somewhere.

**Comment by anthonydresser** [comment]
I think i found a good repro, @CoolDadTx thanks for your help in finding this. This should be an easy fix and I am targeting our next release for this fix (although it will be in insiders sooner).

**Comment by stona1** [comment]
>This should be an easy fix and I am targeting our next release for this fix (although it will be in insiders sooner).

Thank you for information. What you mean by next release? Now we have 1.14.1 so next will be 1.14.2 or we need to wait until 1.15.0?

**Comment by anthonydresser** [comment]
We do monthly releases or our main build, then ext being early February.
