### ISSUE TITLE
SQL Server Agent blank job history

### ISSUE THREAD

**Issue by HanzoX7** [microsoft/azuredatastudio#8800]
- Azure Data Studio Version: 1.14.1

Steps to Reproduce:

1. Right-click on server and choose manage
2. Select any of the existing jobs
3. Notice the blank job history
4. Hit refresh to check... still blank.
5. Uninstall extension, reinstall extension... still blank

I checked SSMS and job history there. Running a job from Azure Data Studio does make it run, but it fails to show the results. It's funny because the little bar chart for "previous runs" does update.

**Comment by HanzoX7** [comment]
Just thought I'd add that I uninstalled and reinstalled Azure Data Studio and no joy... still doesn't show the job history.

**Comment by abist** [comment]
@HanzoX7 Thanks for reporting the issue. Could you toggle the developer tools (`Help` -> `Toggle Developer Tools` or `Ctrl`/`Cmd` + `Shift` + `I`) to go to the console and see if there are any errors?

**Comment by HanzoX7** [comment]
Yes... there are a few, but one in particular pops out: 
![image](https://user-images.githubusercontent.com/33915375/71855158-e05ab700-30a5-11ea-9de0-71f098c11672.png)

This one is right below:
![image](https://user-images.githubusercontent.com/33915375/71855202-fcf6ef00-30a5-11ea-9140-3988d3664e8e.png)

Not sure if this is related in any way:
![image](https://user-images.githubusercontent.com/33915375/71855255-2748ac80-30a6-11ea-826b-860f48a1bf1f.png)

Thanks for looking into this!

**Comment by abist** [comment]
@HanzoX7 Thanks for the prompt response! That was really helpful!

**Comment by martincroft** [comment]
I am also getting the same issue with no job history showing for any jobs message that e.convertToJobHistoryRow is not a function in developers console
running version 1.15.0-insiders (user setup)
