### ISSUE TITLE
Blank Screen Again

### ISSUE THREAD

**Issue by nadjibnet** [microsoft/azuredatastudio#8810]
Hello,

I got a blank screen, I checked and it was already reported on [this Issue](https://github.com/Microsoft/azuredatastudio/issues/4694). After checke I have a different error,

![Capture](https://user-images.githubusercontent.com/39797899/71766194-81f2d480-2efd-11ea-8301-9ce91dfa8047.PNG)

Thanks

**Comment by kburtram** [comment]
@nadjibnet could you please add version info for ADS and the operating system?  I don't see anything in the dev console log that should cause a blank screen after launching the application.

**Comment by dzsquared** [comment]
This might be related to #8775 ?

**Comment by anthonydresser** [comment]
Can you try disabling gpu acceleration? https://code.visualstudio.com/updates/v1_40#_disable-gpu-acceleration

**Comment by nadjibnet** [comment]
Windows Server 2019 running on VMWare 15.1.0
ADS azuredatastudio-windows-user-setup-1.14.1

A video here: https://www.dropbox.com/s/zbi53ui40jmmk7r/20200111104034.mp4?dl=0

**Comment by Nikolai5** [comment]
I'm getting the same.

Quite often to the point where it's unusable the screen will go blank and I have to close the app and reopen it. It happens so frequently that I basically can't use it.

I'm not doing the same thing every time to get it to go blank either. I might have minimised and then maximised the window, tried to open a new query, attempted to connect to a database or it's just opened like that.

I have tried disabling GPU acceleration but didn't make much of a difference overall.

I've included some system details based off what the issue reporter in the app pulls out.

![Azure Data Studio Blank Screen](https://user-images.githubusercontent.com/2317234/72433940-5f30ad80-3792-11ea-8347-917cf173ee04.png)


Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i3-7100 CPU @ 3.90GHz (4 x 3912)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|3.88GB (0.41GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
import|Mic|0.12.0


</details>

**Comment by anthonydresser** [comment]
Next time you experience this, can you check if there is anything in the logs, they are located at `$User-Folder$\AppData\Roaming\azuredatastudio\logs`.

The interesting log files are the `main.log` and `renderer1.log`

**Comment by Nikolai5** [comment]
Hi, I checked the log files after it happened again and there aren't any errors or anything of note. Most of the files were empty.

It seems one of the causes is idling for too long.

**Comment by kburtram** [comment]
Consolidating this bug to issue https://github.com/microsoft/azuredatastudio/issues/8775.  Please add any related comments to that issue.  Thanks for reporting!
