### ISSUE TITLE
Open File Dialog Box Feature request

### ISSUE THREAD

**Issue by ibuda** [microsoft/azuredatastudio#8811]
First of all, let me thank you for a great product that we use on a daily basis!

I think that there might be an improvement if we had an option to "remember" the option chosen previously when selecting whether to allow or not opening the file.

![Screenshot from 2020-01-05 12-37-50](https://user-images.githubusercontent.com/42291858/71778610-d60ebf00-2fb8-11ea-8743-40bef92cdbbb.png)

I understand that it's a security reason the dialog box is there in the first place. But in the case when the user knows that the blob storage is private and secure, and works very often with files, it would be much easier if we could have a checkbox to "Remember the choice" and Open the files automatically from now on.

Once again thank you for your efforts to bring us such a great product.

**Comment by Charles-Gagnon** [comment]
@ibuda Is this dialog from Azure Data Studio? I don't recognize it as being a feature in this tool.

**Comment by ibuda** [comment]
My bad, I was referring to Azure Storage Explorer. I will propose it on the corresponding git repo.
