### ISSUE TITLE
Authentication flow for AADU w/MFA do not match SSMS and VS and are wonky

### ISSUE THREAD

**Issue by StingyJack** [microsoft/azuredatastudio#8813]
Issue Type: <b>Bug</b>

Choosing  "Azure AD - Universal with MFA" in this program does not allow me to type in a user name. Instead it puts me thought the devicelogin auth workflow like I have to do for remote CLI programs. 

If you want to use that path you should be doing so in the program and giving me a list of accounts to pick _from the program_ and not make me shell out to something else to pick, and have to click "yes open external site". 

Its more clicks and interactions than I had to do with SSMS. This program should always be at least equal or better.

**Comment by kburtram** [comment]
@aaomidi do you know if any of the upcoming auth changes will address this issue?  I think we'll still be opening an external web page, but the user will have the option to provide a username\password with on of the new AAD options.  Is that correct?

**Comment by aaomidi** [comment]
This should get fixed-ish, but we should come back to it once the changes are in.

**Comment by cheenamalhotra** [comment]
Closing this as resolved, as ADS supports account selection from list of added accounts.
