### ISSUE TITLE
DB list drop-down shrinks after second when drop-down is opened.

### ISSUE THREAD

**Issue by valentinsgaiduceks** [microsoft/azuredatastudio#8818]
Issue Type: <b>Bug</b>

In condition, when user is connected to DB server, when user opens drop-down, for choosing data-base, after second this drop-down is shrinked and db's in list are not shown fully.

Steps to reproduce:
1. Connect to DB server.
2. Open DB's list in drop-down.

Expected result:
1. Drop-down is opened, it's size is not changed.

Actual result:
1. Drop-down is opened, it's size becomes smaller after second-two.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (18.07GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none
(1 theme extensions excluded)

**Comment by kburtram** [comment]
@valentinsgaiduceks this issue should be fixed in the latest insiders builds from master branch.  The fix will be included in the next stable release.  Please let us know if you continue to see this issue one of these builds.  Thanks!
