### ISSUE TITLE
Update VSIX links in List of Extensions Wiki page

### ISSUE THREAD

**Issue by petros-d** [microsoft/azuredatastudio#8831]
- Azure Data Studio Version: N/A

The [list of extensions](https://github.com/microsoft/azuredatastudio/wiki/List-of-Extensions) page is currently the only way to download extensions for offline install. The link to SQL Server Schema Compare VSIX package is for version 0.7.0, but the current version is 1.1.0. 

Until there is an equivalent to the [VS Code Extensions marketplace](https://marketplace.visualstudio.com/vscode), these links should be kept up to date with each extension release.

The actual download links (e.g. https://sqlopsextensions.blob.core.windows.net/extensions/schema-compare/schema-compare-0.7.0.vsix) are obfuscated with Microsoft forward link (e.g. https://go.microsoft.com/fwlink/?linkid=2099886), which I'm assuming only Microsoft staff can create.

I'd argue it would be simpler to remove the obfuscation and link directly to the download link containing the version number.

**Comment by hannahqin** [comment]
Hi Petros, thank you for your feedback. The page has now been updated with the most current VSIX download links. 

We do try to maintain this page with each extension release, but this pipeline is still a work in progress; the forward links are part of this pipeline, and do help streamline our maintenance process. We appreciate your patience as we work to smooth out any gaps.
