### ISSUE TITLE
Save As Excel/CSV headers - Notebook vs Query

### ISSUE THREAD

**Issue by moreofabeige** [microsoft/azuredatastudio#8839]
Issue Type: <b>Bug</b>

Performing a Save As Excel or CSV in a regular query includes the headers.

When performing the same steps from a Notebook cell, the headers are not included with the data.

"Sql › Save As Csv: Include Headers" is ticked.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6500T CPU @ 2.50GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (2.59GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (5)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.11.0

</details>

**Comment by RicardoNoerr** [comment]
I had the same problem but also on copy/paste
I opened the issue #11246

**Comment by lucyzhang929** [comment]
Issue fixed in this PR https://github.com/microsoft/azuredatastudio/pull/11491
