### ISSUE TITLE
Attempt to change Kernel to 'PowerShell' ADS goes through a long install of a Python instance, then is unable to change kernel

### ISSUE THREAD

**Issue by realworldis** [microsoft/azuredatastudio#8856]
- Azure Data Studio Version:

Steps to Reproduce:

1. Install Azure Data Studio (tried with December and November versions - 1.14.x and 1.13.x)
2. Start Azure Data Studio
3. New Notebook

4. Change Kernel to 'PowerShell'

Receive the error:
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Error executing Jupyter command 'notebook': [WinError 5] Access is denied

The kernel reverts back to SQL, unable to execute any PowerShell commands.

Was prompted to select either a new or existing python instance (?? not sure how related to powershell)  Selected a new instance... It eventually completed, but still displayed an error.  In subsequent tries, I selected existing instance.  Tried the various 'Python' related kernels, all show the same error.

**Comment by corivera** [comment]
Can you provide the errors you were seeing in these failure cases? Did the install complete successfully in the first case?

**Comment by corivera** [comment]
As for why we need Python for Powershell, the cell commands run through jupyter, which in turn runs through python. So we need to install a powershell pip package to be able to use the powershell kernel in jupyter.

**Comment by realworldis** [comment]
To recreate the issue, Iried uninstalling all Python packages.  Then when starting Azure Data Studio and switching to PowerShell, was prompted to create a new Python instance.  Below is the full log, but basically, it ends in "Notebook dependencies installation is complete"

Same error as original: When attempting to switch to Kernel 'powershell', get the following error and it reverts to SQL
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Error executing Jupyter command 'notebook': [WinError 5] Access is denied



Here's the full log from the new python instance:
Notebook dependencies installation is in progress
Downloading python package (0 / 144.21 MB)
Downloading python package (14.43 / 144.21 MB)
Downloading python package (28.85 / 144.21 MB)
Downloading python package (43.26 / 144.21 MB)
Downloading python package (57.69 / 144.21 MB)
Downloading python package (72.12 / 144.21 MB)
Downloading python package (86.53 / 144.21 MB)
Downloading python package (100.95 / 144.21 MB)
Downloading python package (115.38 / 144.21 MB)
Downloading python package (129.79 / 144.21 MB)
Downloading python package (144.21 / 144.21 MB)
Unpacking python package
Python download is complete
Installing required packages to run Notebooks...
    > "c:\Program Files\azuredatastudio-python\0.0.1\python.exe" -m pip install --no-index -r "c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt" --find-links "c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages" --no-warn-script-location
    stdout: Looking in links: c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages
    stdout: 
    stdout: Requirement already satisfied: pip in c:\program files\azuredatastudio-python\0.0.1\lib\site-packages (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 1)) (19.2.3)
    stdout: 
    stdout: Collecting pandas>=0.24.2 (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: 
    stdout: Collecting jupyter>=1.0.0 (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting prose-codeaccelerator>=1.3.0 (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting sparkmagic>=0.12.9 (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting powershell-kernel>=0.1.0 (from -r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 6))
    stdout: 
    stdout: Collecting pytz>=2017.2 (from pandas>=0.24.2->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting python-dateutil>=2.6.1 (from pandas>=0.24.2->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting numpy>=1.13.3 (from pandas>=0.24.2->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting ipywidgets (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting nbconvert (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting qtconsole (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting notebook (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jupyter-console (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting ipykernel (from jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting protobuf>=3.8.0 (from prose-codeaccelerator>=1.3.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting regex>=2017.7.28 (from prose-codeaccelerator>=1.3.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting dotnetcore2>=2.1.8 (from prose-codeaccelerator>=1.3.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: 
    stdout: Collecting hdijupyterutils>=0.6 (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting autovizwidget>=0.6 (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting ipython>=4.0.2 (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting nose (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting mock (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting requests (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting tornado>=4 (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting requests_kerberos>=0.8.0 (from sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas>=0.24.2->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting nbformat>=4.2.0 (from ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting widgetsnbextension~=3.5.0 (from ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting traitlets>=4.3.1 (from ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting mistune<2,>=0.8.1 (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jupyter-core (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting testpath (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jinja2>=2.4 (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting entrypoints>=0.2.2 (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting bleach (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting pygments (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting defusedxml (from nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jupyter-client>=4.1 (from qtconsole->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting ipython-genutils (from qtconsole->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting prometheus-client (from notebook->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting terminado>=0.8.1 (from notebook->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting Send2Trash (from notebook->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pyzmq>=17 (from notebook->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting prompt-toolkit<2.1.0,>=2.0.0 (from jupyter-console->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Requirement already satisfied: setuptools in c:\program files\azuredatastudio-python\0.0.1\lib\site-packages (from protobuf>=3.8.0->prose-codeaccelerator>=1.3.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4)) (39.0.1)
    stdout: 
    stdout: Collecting distro>=1.2.0 (from dotnetcore2>=2.1.8->prose-codeaccelerator>=1.3.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting plotly>=3 (from autovizwidget>=0.6->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting backcall (from ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting colorama; sys_platform == "win32" (from ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting pickleshare (from ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting decorator (from ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting jedi>=0.10 (from ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting chardet<3.1.0,>=3.0.2 (from requests->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting idna<2.9,>=2.5 (from requests->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting certifi>=2017.4.17 (from requests->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting cryptography>=1.3; python_version != "3.3" (from requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting winkerberos>=0.5.0; sys_platform == "win32" (from requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting jsonschema!=2.5.0,>=2.4 (from nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting pywin32>=1.0; sys_platform == "win32" (from jupyter-core->nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting MarkupSafe>=0.23 (from jinja2>=2.4->nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting webencodings (from bleach->nbconvert->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pywinpty>=0.5; os_name == "nt" (from terminado>=0.8.1->notebook->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting retrying>=1.3.3 (from plotly>=3->autovizwidget>=0.6->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting parso>=0.5.0 (from jedi>=0.10->ipython>=4.0.2->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3; python_version != "3.3"->requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting attrs>=17.4.0 (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pyrsistent>=0.14.0 (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting importlib-metadata (from jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3; python_version != "3.3"->requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting zipp>=0.5 (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting more-itertools (from zipp>=0.5->importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat>=4.2.0->ipywidgets->jupyter>=1.0.0->-r c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Installing collected packages: pytz, six, python-dateutil, numpy, pandas, ipython-genutils, decorator, traitlets, backcall, colorama, pygments, pickleshare, wcwidth, prompt-toolkit, parso, jedi, ipython, pywin32, jupyter-core, attrs, pyrsistent, more-itertools, zipp, importlib-metadata, jsonschema, nbformat, pandocfilters, mistune, testpath, MarkupSafe, jinja2, entrypoints, webencodings, bleach, defusedxml, nbconvert, prometheus-client, tornado, pyzmq, jupyter-client, pywinpty, terminado, Send2Trash, ipykernel, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter-console, jupyter, protobuf, regex, distro, dotnetcore2, prose-codeaccelerator, nose, mock, hdijupyterutils, retrying, plotly, autovizwidget, urllib3, chardet, idna, certifi, requests, pycparser, cffi, cryptography, winkerberos, requests-kerberos, sparkmagic, powershell-kernel
    stdout: 
    stdout:   Running setup.py install for backcall: started
    stdout: 
    stdout:     Running setup.py install for backcall: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pyrsistent: started
    stdout: 
    stdout:     Running setup.py install for pyrsistent: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pandocfilters: started
    stdout: 
    stdout:     Running setup.py install for pandocfilters: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for prometheus-client: started
    stdout: 
    stdout:     Running setup.py install for prometheus-client: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for hdijupyterutils: started
    stdout: 
    stdout: 
    stdout:     Running setup.py install for hdijupyterutils: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for retrying: started
    stdout: 
    stdout:     Running setup.py install for retrying: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for autovizwidget: started
    stdout: 
    stdout:     Running setup.py install for autovizwidget: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pycparser: started
    stdout: 
    stdout:     Running setup.py install for pycparser: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for sparkmagic: started
    stdout: 
    stdout:     Running setup.py install for sparkmagic: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for powershell-kernel: started
    stdout: 
    stdout:     Running setup.py install for powershell-kernel: finished with status 'done'
    stdout: 
    stdout: Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 autovizwidget-0.13.1 backcall-0.1.0 bleach-3.1.0 certifi-2019.9.11 cffi-1.13.0 chardet-3.0.4 colorama-0.4.1 cryptography-2.8 decorator-4.4.0 defusedxml-0.6.0 distro-1.4.0 dotnetcore2-2.1.9 entrypoints-0.3 hdijupyterutils-0.13.1 idna-2.8 importlib-metadata-0.23 ipykernel-5.1.2 ipython-7.8.0 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.15.1 jinja2-2.10.3 jsonschema-3.1.1 jupyter-1.0.0 jupyter-client-5.3.4 jupyter-console-6.0.0 jupyter-core-4.6.0 mistune-0.8.4 mock-3.0.5 more-itertools-7.2.0 nbconvert-5.6.0 nbformat-4.4.0 nose-1.3.7 notebook-6.0.1 numpy-1.17.3 pandas-0.25.1 pandocfilters-1.4.2 parso-0.5.1 pickleshare-0.7.5 plotly-4.2.0 powershell-kernel-0.1.0 prometheus-client-0.7.1 prompt-toolkit-2.0.10 prose-codeaccelerator-1.7.0 protobuf-3.10.0 pycparser-2.19 pygments-2.4.2 pyrsistent-0.15.4 python-dateutil-2.8.0 pytz-2019.3 pywin32-225 pywinpty-0.5.5 pyzmq-18.1.0 qtconsole-4.5.5 regex-2019.8.19 requests-2.22.0 requests-kerberos-0.12.0 retrying-1.3.3 six-1.12.0 sparkmagic-0.13.1 terminado-0.8.2 testpath-0.4.2 tornado-6.0.3 traitlets-4.3.3 urllib3-1.25.6 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.5.1 winkerberos-0.7.0 zipp-0.6.0
    stdout: 
    > "c:\Program Files\azuredatastudio-python\0.0.1\python.exe" -m pip install --force-reinstall --no-index pip --find-links "c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages" --no-warn-script-location
    stdout: Looking in links: c:\Program Files\azuredatastudio-python\0.0.1\offlinePackages
    stdout: 
    stdout: Collecting pip
    stdout: 
    stdout: Installing collected packages: pip
    stdout: 
    stdout:   Found existing installation: pip 19.2.3
    stdout: 
    stdout:     Uninstalling pip-19.2.3:
    stdout: 
    stdout:       Successfully uninstalled pip-19.2.3
    stdout: 
    stdout: 
    stdout: Successfully installed pip-19.3
    stdout: 
... Jupyter installation complete.
Notebook dependencies installation is complete

**Comment by corivera** [comment]
Do you get the same access denied error when installing to a location outside of Program Files? Like in the default location in the user directory, for example?

**Comment by realworldis** [comment]
So I believe I tried that previously.   My thoughts were to try the Program Files as i swap between an admin account and a standard user account.

Found a place in settings where i could set the Notebook: Python Path...Setting this, I was prompted again to choose a new or existing Python installation.  When I chose a new instance, 

Got the message:
Python already exists at the specific location. Skipping install.

After that, same error as before:
Failed to change kernel. Kernel SQL will be used. Error was: Notebook process exited prematurely with error code: 1. StdErr Output: Error executing Jupyter command 'notebook': [WinError 5] Access is denied

**Comment by corivera** [comment]
Since you'll be switching between different users, then the usual solution of installing with the --user option won't work here. That's what we do when installing packages with the Existing python option in the dialog, since it avoids permission issues by installing packages in the user's AppData folder.

It might be best to delete that python install and start fresh with a new python install from the python website. Then once that's setup, you can install the required packages by running the following command from an Administrator command prompt:

python.exe -m pip install "jupyter>=1.0.0" "pandas>=0.24.2" "sparkmagic>=0.12.9" "prose-codeaccelerator>=1.3.0" "powershell-kernel>=0.1.2" --extra-index-url https://prose-python-packages.azurewebsites.net
