### ISSUE TITLE
Notebook: Trust an entire directory of Notebooks

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#8864]
Issue Type: <b>Bug</b>

When working with many Notebooks in a single directory, it is cumbersome to keep clicking on the "Not Trusted" button to trust the Notebook. It would make the experience so much better if the user can trust the entire directory where the Notebooks live. This should be configurable at the user and workspace level.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
We're still commenting on the PR, so moving to April release.
