### ISSUE TITLE
Big Data Cluster Deployment Wizard - No string validation for AKS cluster name

### ISSUE THREAD

**Issue by rajmera3** [microsoft/azuredatastudio#8874]
- Azure Data Studio Version: 1.13

Big Data Cluster deployment wizard - AKS Cluster name only allows alphanumeric characters or "-". No validation for AKS Cluster name. Fails in notebook

Steps to Reproduce:

1. Go through deployment wizard
2. Enter improper string for AKS cluster name. Ex: "rahul_bdc_test"
3. Continue to deployment notebook. Will get error in "Create AKS Cluster" cell for having underscores in the name. 

`Executing: az aks create --name rahul_bdc_test --resource-group rahul_bdc_test --generate-ssh-keys --node-vm-size Standard_E8s_v3 --node-count 5`

` --name cannot exceed 63 characters and can only contain letters, numbers, or dashes (-).`

**Comment by ranasaria** [comment]
This is a corner case issue that we will tackle in march release.

**Comment by Charles-Gagnon** [comment]
@ranasaria Is this something you're planning to bring to ask mode? If not please move it out of this milestone.

**Comment by ranasaria** [comment]
nope note for this month.

**Comment by ranasaria** [comment]
I have moved it out.
