### ISSUE TITLE
Blackout 

### ISSUE THREAD

**Issue by hquesantos** [microsoft/azuredatastudio#8881]
It happened every time i used the azure data studio and clicked in other place besides the app, and it can happen anytime i do a "select *" query. The Whole azure data software turns into full dark-gray(i'm using the dark theme) and then doesn't come back, unless i minimize it a lot of times using the windows taskbar. I can see that the software is still working because the mouse changes if i put it where the input is or when i find the close button, but i can't use a software without seeing what is going on
![bug](https://user-images.githubusercontent.com/50104541/72429573-0c91ca00-376f-11ea-8db8-3e8a45386d62.png)

**Comment by kburtram** [comment]
Consolidating this bug to issue https://github.com/microsoft/azuredatastudio/issues/8775.  Please add any related comments to that issue.  Thanks for reporting!

**Comment by hquesantos** [comment]
> Consolidating this bug to issue #8775. Please add any related comments to that issue. Thanks for reporting!

Got it!
Do you know anything that i can do to resolve this problem? If don't, I will start to use MSSMS since this one doesn't cause issues on my machine
