### ISSUE TITLE
Create or alter statement breaks syntax highlighting

### ISSUE THREAD

**Issue by CobusKruger** [microsoft/azuredatastudio#8882]
Issue Type: <b>Bug</b>

This simple SP breaks syntax highlighting:

```
create or alter procedure DoSomething
as
return
```

The SQL is actually valid, but the editor places red squiggles beneath every word from the "or" onward.

There is also a message:
```
Incorrect syntax: 'ALTER PROCEDURE' must be the only statement in the batch.
```

Expected: No error, and working syntax highlighting.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8550U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (15.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by andrewbusch7** [comment]
I'm also encountering this, it's when connecting to an Azure SQL DB. I experience it for procedures, functions and views.

Seems it was previously reported at https://github.com/microsoft/azuredatastudio/issues/7745

**Comment by Charles-Gagnon** [comment]
This should be fixed in the next release of ADS - if you are able to verify this on the latest version of our insiders builds that would be great!

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-main
