### ISSUE TITLE
Connection and selected database is lost when opening a new query

### ISSUE THREAD

**Issue by petertirrell** [microsoft/azuredatastudio#8883]
Issue Type: <b>Bug</b>

Steps to Reproduce:

    1. Connect to a database server
    2. Open a new query
    3. Select a database
    4. Open a new query (Ctrl + N)

I'm aware of issue #6 (https://github.com/microsoft/azuredatastudio/issues/6) but has there been a regression?  I am sure this functionality was working, but as of a recent update (not sure which one) if I ctrl+N a new query window from an existing one that has a valid connection and database selected, I am prompted to select a new connection.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (8.77GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
I looked into this and believe I have found the issue. 

@anthonydresser It looks like your recent refactor to rework the custom editor logic (https://github.com/microsoft/azuredatastudio/pull/5696) broke this behavior. We no longer do any of the logic to get the current global connection like we do for [query actions](https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/query/browser/queryActions.ts#L119) and so all new queries that aren't from action contributions are opening in a disconnected state. 

Do you have time to look into this? I can work on it if not but you have the most context here.
