### ISSUE TITLE
Edit Data leaving a SQL text document in HotExit auto-recover list

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8890]
- Azure Data Studio Version: `master`, regression from 1.14.1

Steps to Reproduce:

1. Edit Data on a table
2. Leave Edit Document open and close ADS shell window
3. Reopen ADS

Expected: Edit Data document gone and no residual UI elements

Actual: Edit Data backing SQL query is reopened in SQL query editor document

*This document was restored from an Edit Data document as part of HotExit auto-recover behavior*
![image](https://user-images.githubusercontent.com/599935/72473787-4a591780-379c-11ea-907f-e18fdf699673.png)

**Comment by smartguest** [comment]
Apparently when HotExit is enabled, the code will attempt to back up the table into that state shown on the screenshot. When it is disabled, this issue does not occur.

This means we have to remove backup functionality for the grid.

**Comment by kburtram** [comment]
@smartguest yes, the editor should opt-out of the HotExit functionality, similar to how this behaves in the Query editor.  I don't think this is related to the grid directly, AFAIK.  Ping me if you'd like a more detailed explanation.
