### ISSUE TITLE
Edit Data grid never displays if Run is clicked many times

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8891]
- Azure Data Studio Version: `1.14.1`

Steps to Reproduce:

1. Open Edit Data on a table
2. Show the SQL Pane
3. Click the Run button over-and-over numerous times (e.g. ~5-10 times) without waiting for previous Run to complete 

Expected: Once done clicking the Run button the result grid displays respecting the current SQL query

Actual: The grid never displays.  The Run button is disabled and Stop is enabled.  Clicking Stop does nothing and editor must be closed and reopened to be usable again.

![image](https://user-images.githubusercontent.com/599935/72474758-5a71f680-379e-11ea-8495-d48478c0282b.png)

**Comment by smartguest** [comment]
In the current version of the build, the table is now completely set to null after that is done.
