### ISSUE TITLE
Add saved notebook (on disk) to Azure Data Studio

### ISSUE THREAD

**Issue by Smile4ever** [microsoft/azuredatastudio#8897]
**Is your feature request related to a problem? Please describe.**
I already saved a notebook, but now I want to register it inside Azure Data Studio.

**Describe the solution or feature you'd like**
I would like to add an item (shortcut) to a notebook on disk.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by chlafreniere** [comment]
I'm a little unclear on what is being asked here. Can you give a few more details on how a shortcut can be used here?
