### ISSUE TITLE
Allow Vs Code Tasks in Azure Data Studio

### ISSUE THREAD

**Issue by srinath999** [microsoft/azuredatastudio#8898]
I want to use an SSDT Project with build definitions which generate a .dacpac for schema compare file that made me execute a sequence of commands on command prompt and the compare the .dacpac allowing tasks would make that easier to build and deploy my changes across databases.

I used .vscode folder with tasks.json file in that.I would be glad if this is already available.

**Comment by rrmistry** [comment]
I'd prefer not reading tasks from `.vscode/tasks.json` file as this adds a dependency on another tool for users.

I'd prefer just supporting similar functionality with definition stored udner `.azuredatastudio/tasks.json` file location.

Would be nice to have custom tasks in general though (however possible)

**Comment by srinath999** [comment]
Is there a plan to support SSDT projects with this tool?

**Comment by kburtram** [comment]
vscode tasks are supported in the latest ADS builds.  SQL Project support is available through the related extension.  Thanks!
