### ISSUE TITLE
Add / Edit Table or Sp from GUI

### ISSUE THREAD

**Issue by dvanurag1308** [microsoft/azuredatastudio#89]
- SQL Operations Studio Version:
0.23.6
Steps to Reproduce:
Right Click on Tables.

Add new menu item to add/edit table and store procedures from GUI.

**Comment by kburtram** [comment]
I'm going to close this as a duplicate of https://github.com/microsoft/azuredatastudio/issues/282 since that issue has a bit more context.  Please add any related comments in that issue.  Thanks!
