### ISSUE TITLE
Column Name Copy

### ISSUE THREAD

**Issue by NanookSoftware** [microsoft/azuredatastudio#8902]
Issue Type: <b>Feature Request</b>

It would be great if we could copy the column name to the clip board. You offer the copy with headers, but just a copy header would be great also.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:37:56.865Z)
OS version: Darwin x64 19.3.0

**Comment by alanrenmsft** [comment]
this is now supported in the stable build, and in next release, you will be able to only copy the header for selected columns.
