### ISSUE TITLE
Script execution never finishes/hangs after raiserror that terminates the connection

### ISSUE THREAD

**Issue by joukokynsijarvi** [microsoft/azuredatastudio#891]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

Run the following script against a local SQL Server 2017 instance (for example in master database) where you have sysadmin permissions:

```
raiserror('test', 20, -1) with log
go
begin tran
go
select 1
go
commit
go
```

I would expect SQL Ops Studio **to NOT run** the remaining parts of the script after the raiserror line that terminates the current connection. Instead SQL Ops Studio tries to run the rest of the script and never finishes and shows the following output:

```
[9:14:54 AM]	Started executing query at Line 1
Msg 233, Level 20, State 0, Line 0
A transport-level error has occurred when receiving results from the server. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) 
[9:14:54 AM]	Started executing query at Line 2
Query failed: BeginExecuteReader requires an open and available Connection. The connection's current state is closed. 
 Executing query <=== stays here forever
```

SQL Server Management Studio correctly stops executing the script after the raiserror.

(This is a simplified script, in the real script there is an if statement that checks the name of the database and only runs raiserror for some databases.)

**Comment by cheenamalhotra** [comment]
Issue not reproducible anymore, closing as resolved.
Tested version 1.45.1
