### ISSUE TITLE
Missing excel file extension in excel export

### ISSUE THREAD

**Issue by kimipsen** [microsoft/azuredatastudio#892]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

Steps to Reproduce:

1. Create a SELECT statement
2. Click "Save as Excel"
3. Write a name in dialogue
4. Hit "Save"

The excel file will now be saved without the proper file extension.
The same goes for JSON and CSV file exports.

**Comment by kevcunnane** [comment]
I can confirm this one still repros. We need to add a check for file path and append the default value if none exists.

**Comment by kburtram** [comment]
This looks related to #615.  The default export file does contain the proper extension, but if the file is renamed we don't auto-append it.

**Comment by kburtram** [comment]
This doesn't appear to repro on the latest release.  Please let us know if you are still impacted by this bug.

![image](https://user-images.githubusercontent.com/599935/129609697-c35ccf71-f069-49ea-a115-4f16c1a4e3f1.png)
