### ISSUE TITLE
Dashboard extension tabs are displaying incorrectly on Azure SQL DB

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8938]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Connect to Azure SQL DB with SQL Agent extension installed

Expected: These extensions don't contribute tabs to the dashboard since they aren't applicable to Azure SQL DB.  They should be filtered by a `when` clause.

Actual: These tabs incorrectly display.

**Comment by alanrenmsft** [comment]
- [ ] update the first party extensions to have proper when clause for contributed tabs

- [ ] publish extensions
