### ISSUE TITLE
Users cannot select a files in the search results

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#8939]
Steps to Reproduce:

1. Search (Ctrl+Shift+F) for a file
2: If user selects the file the search results of that file collapses.  User has to select the search results of the content of file to open it.

It would be nice for the users to just open the file by clicking on it.

**Comment by kburtram** [comment]
The "Find In Files" experience is taken without modification from the vscode shell.  I would suggest opening this issue against vscode so the can triage it.  We may customize our search experience in the future to include DB search ,etc., at which point we could revisit UX improvements.

**Comment by chlafreniere** [comment]
This has since been fixed by the search experience in the notebooks viewlet.
