### ISSUE TITLE
error while saving file

### ISSUE THREAD

**Issue by BryanAldrich** [microsoft/azuredatastudio#8943]
Issue Type: <b>Bug</b>

Closed tab that was associated with a file. Chose Yes to save the file and close. Received an error and the file was closed.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (20.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (12)</summary>

Extension|Author (truncated)|Version
---|---|---
query-editor-boost|dre|0.4.0
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
import|Mic|0.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
simple-data-scripter|sea|0.1.3
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(1 theme extensions excluded)

</details>

**Comment by BryanAldrich** [comment]
[renderer1.log](https://github.com/microsoft/azuredatastudio/files/4105027/renderer1.log)

**Comment by anthonydresser** [comment]
Did the file successfully save? The error might be unrelated.

**Comment by BryanAldrich** [comment]
I believe it did. the file modified date matches the time I saved the file.
It wasn't a very meaningful change I was saving and I don't remember what
it was exactly.

**Comment by kburtram** [comment]
Thanks for reporting this issue!  I haven't been able to repro, but I'll note this bug in case we see additional reports or are able to get an internal repro.  Please let us know if you encounter again, or have additional details that will help us root cause the error.
