### ISSUE TITLE
Replace TS Lint scan uploads

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#8945]
TS Lint was used for security scans - but with the move to ES Lint the output file is no longer being generated. We need to determine whether the upload task can understand the output from ES Lint and if not determine how to work around that until the upload task is updated to handle ES Lint.

**Comment by Charles-Gagnon** [comment]
This is currently a work in progress - an ADO task is being developed to support this. I'm tracking that currently and will update as progress is made.

**Comment by aaomidi** [comment]
Do you have a link for the task that's being created?

**Comment by Charles-Gagnon** [comment]
No, they might have a work item somewhere but they just told me over e-mail that they were working on it.

**Comment by kburtram** [comment]
Closing older engineering task issues.  Please reactive if you're still using this to track some upcoming work.
