### ISSUE TITLE
SQL server import extension is not loading in Azure data studio

### ISSUE THREAD

**Issue by helenwxdong** [microsoft/azuredatastudio#8955]
- Azure Data Studio Version:

Steps to Reproduce:
Control I to activate import wizard, then this pops up with no way to click next 
![E05B922F-DAF1-4019-BCF2-0DB985577000_4_5005_c](https://user-images.githubusercontent.com/33271708/73075093-26c35a80-3e89-11ea-9b94-27207dd22b00.jpeg)

**Comment by Charles-Gagnon** [comment]
@helenwxdong Are you still seeing this issue? If you open the developer console (Help -> Toggle Developer Tools -> Console tab) are there any errors displayed there?

**Comment by kenvanhyning** [comment]
If the target is SQL Azure, it looks like the same as https://github.com/microsoft/azuredatastudio/issues/7115.

**Comment by aaomidi** [comment]
Closing in favor of #9748
