### ISSUE TITLE
Results Grid Spacing Seems Off with Small and Larger Result Sets Mixed In

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#8959]
I did a test with the following query:

select 12
select * from sys.tables
select 987

The spacing between each grid was inconsistent. The last grid appears to have no padding around it at all. Is this a result of us trying to subdivide the results area into n pieces?

![image](https://user-images.githubusercontent.com/40371649/73112353-ee407280-3ec2-11ea-8a5a-0b6cb2cb2453.png)

**Comment by anthonydresser** [comment]
This is by design as we need to make sure there is space for the actions on the right side of the grids.
