### ISSUE TITLE
I have to re-authenticate with Azure SQL Servers multiple times a work day

### ISSUE THREAD

**Issue by jefflafay** [microsoft/azuredatastudio#8965]
Issue Type: <b>Bug</b>

There isn't a particular pattern that I noticed but this issue makes it a pain to use the app

I have to click disconnect/connect in a query tab to reconnect again so it times out.

Also, the connections in the server tab timeout often. They have the green circle on the server icon but when you drill down into tables, sprocs, etc. an error occurs and I have to manually disconnect and then click the server again to have it reconnect.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz (8 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (5.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
profiler|Mic|0.11.0
schema-compare|Mic|1.1.0

</details>

**Comment by Charles-Gagnon** [comment]
ADS shouldn't be doing anything to close connections. Have you looked at the server logs to see if that indicates why the connection is being closed? You can start with https://docs.microsoft.com/en-us/previous-versions/sql/sql-server-2005/ms176013(v=sql.90)

What server type is this? (On-Prem, Azure, other)

**Comment by jefflafay** [comment]
Azure Sql Server. I suppose I'll look at the server to see what it could be, I don't get this issue with SSMS so I didn't expect it to occur with ADS.

**Comment by jefflafay** [comment]
Do you have any recommendations to what I could look at on the azure sql server instance? The table you recommended shows current active sessions but is there somewhere I could look to see where my session ended from errors? I'm just not sure what to look at first.

**Comment by Charles-Gagnon** [comment]
I'd start with this https://docs.microsoft.com/en-us/azure/sql-database/troubleshoot-connectivity-issues-microsoft-azure-sql-database

If you open the developer console (Help -> Toggle Developer Tools -> Console tab) do you see any errors that seem like they might be relevant?

You can also enable debug logging: 

1. Open settings (command palette -> Settings (UI) 
2. Set the **Mssql: Tracing Level** to **All**
![image](https://user-images.githubusercontent.com/28519865/73204249-802ec200-40f3-11ea-885f-1f65afea65c5.png)
3. Restart ADS
4. Wait until the issue repros
5. Open command palette and execute the **MSSQL: Show log file** command, then choose **sqltools.log**
6. See if that has any errors that look related - it'd also help if you either uploaded log file here or sent it directly to me (chgagnon@microsoft.com). There is going to be stuff such as server names and paths in that file so feel free to do any cleaning of the data before sending it over.

**Comment by magnusbratt** [comment]
Hi @Charles-Gagnon , I have the same / a similar issue in #8903. I followed your suggestion above, and there were no errors in the Console tab that seemed relevant. I will email you my **sqltools.log**. Very grateful for any recommendations.

**Comment by osmant** [comment]
This occurs to me frequently as well. When I am not active in Azure Data Studio more than approx 30 minutes, and try to run a query on active session, I also experience connection drop.

According to https://docs.microsoft.com/en-us/sql/connect/jdbc/connecting-to-an-azure-sql-database?view=sql-server-ver15#connections-dropped , Azure SQL database service drops those idle connection after 30 mins of inactivity.
In SSMS, when I leave my pc idle for a while and come back and run a query, query execution does not start immediately (takes 1-2 seconds to see the timer countng) and then executes the query. This indicates to me, SSMS is actually retrying to establish connection if the connection is dropped. Looks like same mechanism does not exists in ADS or not working properly.

**Comment by jefflafay** [comment]
@osmant I'm pretty sure this is my scenario too. It's annoying and intellisense stops working for me when this happens. It makes this tool a pain to use for Azure SQL work. I want Azure Data Studio to be a useful tool but it's a bit lackluster and little comical that the UX for working in Azure data is not so good.

@Charles-Gagnon is this functionality somewhere in the road map/backlog for this application by chance? I'd rather work with this tool than SSMS but I can't rely on it until reconnecting isn't a manual chore. Thanks!

**Comment by mrjrdnthms** [comment]
There are serious connection issues to Azure sql databases that are really painful. ADS cannot hold on to a connection to an Azure SQL Database. Connections are lost regularly over the course of several hours. We use ADS all day targeting several different Azure SQL databases and as a result we have to disconnect and reconnect multiple times per hour. ADS has so many benefits over SSMS. But this bug makes it almost not worth while to switch.

Can someone please review the state of the retry logic with respect to connections to Azure hosted databases? In Microsoft's own documentation they describe the need to implement retry logic when writhing the connection code in order to maintain a resilient connection (see link below).

[implementing-retry-logic](https://docs.microsoft.com/en-us/azure/azure-sql/database/troubleshoot-common-errors-issues#implementing-retry-logic)

My guess is that this logic is not in place or is not working. As a result, users have to manually disconnect and reconnect regularly. Its not just the 30 minute timeout @osmant and @jefflafay are talking about. That happens. Plus as the documentation states "Applications that connect to a cloud service such as Azure SQL Database should expect periodic reconfiguration events and implement retry logic to handle these errors instead of surfacing application errors to users." Those reconfiguring events happen regularly. That breaks existing connections. ADS needs to look for those and re-establish the connections.

Sorry for the long diatribe, but this has been a problem for years. I think a lot of people walk away from ADS because of this. At least take a look...

**Comment by tcc-sejohnson** [comment]
This has been a consistent issue for us as well. There are actually two auth issues I run into: 
1. When the user has been inactive for 30 minutes or so, the database appears to still be connected, but is actually not. Expanding nodes in the server explorer and trying to run queries will fail. Even more annoyingly, each query has to be reconnected as well.
2. When the user has been inactive for a week or two (on PTO, working on non-data-related-projects, etc), there's a catastrophic issue that completely prevents them from connecting to Azure SQL databases. When trying to connect, it'll go through the login flow by taking them to their browser, but it will fail to connect. The only way to fix this that I've found is to clear out the login tokens from their filesystem folder and completely re-add the account. I have a feeling it has something to do with the refresh token expiring, but I'm not sure.

**Comment by Tanner-Tran** [comment]
College student here:

Was ripping my hair out on the application side until I realized Azure SQL was forcibly closing my idle connections. I've configured an aggressive connection validation scheme on my end, but I'll probably just switch to a different host to avoid the performance hit.

**Comment by Charles-Gagnon** [comment]
Hey all - we've had a couple people working on improving the various timeout issues that have been reported. Specifically we will now refresh the auth token when running queries and interacting with the object explorer among other fixes.

Some of the fixes are in the latest build already and some will be included in the upcoming release (targeted for mid-December). So if you are/were hitting these issues please try updating to the latest and let us know if you're still seeing problems!

@caohai @cssuh Do you think we'd be able to close this issue then? There's a number of different categories of problems listed here but I think that they should mostly/all be resolved by the fixes you've been doing.

**Comment by caohai** [comment]
For query editor related scenario, we should be good. 
For object explorer (expanding server node, etc), it was not fixed yet last time I checked but we do have a separate issue #17087 tracking that.
@cssuh Are you still working on these AAD bugs lately, if so you could probably take a look at that issue as well.

**Comment by Charles-Gagnon** [comment]
Thanks @caohai 

I'm going to close this issue then to consolidate the open issues we have - for anyone still hitting this please let us know if you're still encountering issues with the latest release and we can investigate each specific issue separately!
