### ISSUE TITLE
Notebook internal links not working

### ISSUE THREAD

**Issue by gregsoc** [microsoft/azuredatastudio#8966]
- Azure Data Studio Version:
Steps to Reproduce:

1. I have a simple notebook with two links at the top.  The links are to headers in the same notebook.  Images below show the layout

![image](https://user-images.githubusercontent.com/7413641/73196871-65ae1600-40fe-11ea-8005-fc10837addc2.png)
![image](https://user-images.githubusercontent.com/7413641/73196898-6f377e00-40fe-11ea-846d-9e7ce1080017.png)
![image](https://user-images.githubusercontent.com/7413641/73196906-73fc3200-40fe-11ea-93e1-5f95951cf977.png)
Here's code I used. 

/**General User Queries**  
/[Header1](#header1)  
/[Header2](#header2)

/# Header1

2. When I click on one of the links e.g. 'Header1', I get new tab called workbench.html.
It has the following code in it.

![image](https://user-images.githubusercontent.com/7413641/73197421-3cda5080-40ff-11ea-8998-eff780ce8962.png)

![image](https://user-images.githubusercontent.com/7413641/73196995-9726e180-40fe-11ea-80db-2db191ec71eb.png)

**Comment by chlafreniere** [comment]
Internal links/anchor issues are being tracked by #8428. Please let us know if there's anything that we're missing from that issue, but closing this one as duplicate for now.
