### ISSUE TITLE
[ADS]-[Data Virtualization]- Enable Validation for Table Selection and Post wizard completion message

### ISSUE THREAD

**Issue by pradm** [microsoft/azuredatastudio#8967]
- Azure Data Studio Version:
Version: 1.15.0-insider (user setup)
Commit: b02bf17d1f12902559e914bf022a014e4542e7f4
Date: 2020-01-24T05:30:15.976Z
VS Code: 1.42.0
Electron: 7.1.7
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Name: Data Virtualization
Id: microsoft.datavirtualization
Description: Support for Data Virtualization in SQL Server, including Create External Data wizards.
Version: 1.2.0
Publisher: Microsoft

Steps to Reproduce:
Even without selecting the External Table the wizard allows us to move ahead and later reports that External Table creation completed.  Please add validation to not proceed without Selecting the required table so that it doesn't confuse when it reports external table created successfully.

**Comment by pradm** [comment]
There are multiple variations of the problem I am noticing. Could you please share your thoughts on these as well.

1.	If I select an existing data source and credential then it doesn’t allow me to proceed ahead without selecting at least 1 single object from external data source it fetched.
2.	Some times if I select the existing data source then the next button is disabled and I cannot move ahead. Pasting the snapshot for your review – notice all the fields are populated but “Next” option is disabled.
3.	If I click previous button in-case if I want to create a new credential so that I can access the oracle database with a new user name and password based on object permissions then I cannot type anything in the Choose Credential text box.
4.	If I select an existing data source it some times allows me to create a new credential and sometimes I cannot.
5.	If I type a new data source name and select and existing credential then without selecting any object it goes through fine and will create only a new data source.
![image](https://user-images.githubusercontent.com/27516588/73389810-f4878200-42fa-11ea-82d2-1153683796bc.png)
![image](https://user-images.githubusercontent.com/27516588/73389821-f9e4cc80-42fa-11ea-8a07-fbc939614b15.png)
![image](https://user-images.githubusercontent.com/27516588/73389832-ff421700-42fa-11ea-98bc-c54a5efd4a64.png)

**Comment by Charles-Gagnon** [comment]
I'm going to close this issue for now since there isn't really anything actionable I can do at this time - but if you're still having issues let me know and I'll see if I can figure out what the problems might be.
