### ISSUE TITLE
"Corrupt ZIP: end of central directory record signature not found" when installing an extension using VSIX on Ubuntu

### ISSUE THREAD

**Issue by swjain23** [microsoft/azuredatastudio#8970]
Azure Data Studio Version: 1.14.1

Steps to Reproduce:

1. Get vsix from https://github.com/Microsoft/azuredatastudio-postgresql/releases 
2. Open Azure Data Studio on your machine and go to File -> Install Extension from VSIX package.
3. Select the vsix package installed from the link above or any other vsix package that you have.

It failes with error "Corrupt ZIP: end of central directory record signature not found"

I am able to install and run the extension on Windows.

**Comment by swjain23** [comment]
I tried to debug and found this stackTrace:

Error: Corrupt ZIP: end of central directory record signature not found"
1: "    at h (file:///usr/share/azuredatastudio/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:413:745)"
2: "    at file:///usr/share/azuredatastudio/resources/app/out/vs/code/electron-browser/sharedProcess/sharedProcessMain.js:415:234"
3: "    at /usr/share/azuredatastudio/resources/app/node_modules.asar/yauzl/index.js:37:7"
4: "    at /usr/share/azuredatastudio/resources/app/node_modules.asar/yauzl/index.js:187:5"
5: "    at /usr/share/azuredatastudio/resources/app/node_modules.asar/yauzl/index.js:631:5"
6: "    at /usr/share/azuredatastudio/resources/app/node_modules.asar/yauzl/node_modules/fd-slicer/index.js:32:7"
7: "    at FSReqCallback.wrapper [as oncomplete] (fs.js:477:5)"

**Comment by kburtram** [comment]
Closing older issues without recent repro reports.  Please let us know if you're still impacted by this issue.
