### ISSUE TITLE
BDC explorer doesn't work. It just says "Loading...."

### ISSUE THREAD

**Issue by uc-msft** [microsoft/azuredatastudio#8977]
![ads](https://user-images.githubusercontent.com/10999577/73290097-b0896580-41b2-11ea-899e-1218f06bdac3.png)
Issue Type: <b>Bug</b>

subject says it all.

Azure Data Studio version: azuredatastudio-insiders 1.15.0-insider (136a1d8ceef183c401bc84ff57306282bb1087ff, 2020-01-28T02:23:15.397Z)
OS version: Windows_NT x64 10.0.19551

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.85GB (17.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.2
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
profiler|Mic|0.11.0

(1 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
@uc-msft Are there any errors in the developer console?

**Comment by chlafreniere** [comment]
@Charles-Gagnon I can also repro. No errors in the console.

**Comment by Charles-Gagnon** [comment]
In that case (for either of you) - was this something you noticed broken recently? Like have you seen it working in the past couple of days and then today it was broken? Or did you just happen to notice today?

**Comment by kburtram** [comment]
This should be fixed in master and the 1.15 release branch now.
