### ISSUE TITLE
Colour Coding of KeyWords + Multi-Line + (CTRL+R)

### ISSUE THREAD

**Issue by vbmike86** [microsoft/azuredatastudio#898]
- SQL Operations Studio Version: sqlops 0.26.7 (723c7cb3bfd80d87fc8a1141632089cd4808495c, 2018-02-16T21:34:47.034Z)
- OS Version: Windows_NT x64 10.0.16299
- Extensions: none
---

- KeyWords like "DEFAULT", "CLUSTERED", "IDENTITY" and "ADD" are not colour coded
- No means to Parse a query before running
- SHIFT+ALT+Up/Down arrows (for multi-line) it copies the line instead of moving the cursor. It only works if you click with the mouse.
Also, if the second line does not have the same length (or is blank) and you started from the middle of the line, the multi-line does not remain on top of one another.
- CLTR+R no longer opens/minimizes the Results window*

**Comment by arinwt** [comment]
> SHIFT+ALT+Up/Down arrows (for multi-line) it copies the line instead of moving the cursor. It only works if you click with the mouse.

This is multiple cursors which is a little different from column select.
The keyboard shortcuts for this are configurable.  You can assign `SHIFT+ALT+Up/Down` to `editor.action.insertCursorAbove` or `editor.action.insertCursorBelow` to achieve similar functionality.
By default, I believe the keyboard shortcuts are instead `CTRL+ALT+Up/Down`.

**Comment by kburtram** [comment]
This issue mentions several different issues.  I think some have been fixed so I'll close based on that.  Please open individual issues for any problems you're still experiencing.  Thanks!
