### ISSUE TITLE
Notebooks: More specific descriptions for Python configuration blade

### ISSUE THREAD

**Issue by hannahqin** [microsoft/azuredatastudio#8988]
"Configure Python for Notebooks" blade should have more specific descriptions about what is being installed.

If I select 'Use existing Python location', what am I installing here? If I select this option and click 'Install', will we overwriting my existing python3 installation with a new one? If we are just installing additional packages in this location, we should make this clear with a short description. 

Is there a recommended configuration option here? If so, it could be helpful to specify "(recommended)."

![MicrosoftTeams-image](https://user-images.githubusercontent.com/9788775/73409316-c468c080-42b3-11ea-8153-b234318acfac.png)

**Comment by MsSQLGirl** [comment]
Also we heard the following feedback:
ADS installs (upgrades and forcibly overwrites) a bunch of Python packages into my Python environment. 
It would be useful for Python installation for ADS to take into account user's virtual environment - for example: is it possible to install on an existing Python virtual environment (out of many).

**Comment by chlafreniere** [comment]
We've since made improvements to this flow, and make it much more clear which package(s) are installed, and which versions are currently installed.
