### ISSUE TITLE
Cmd+a Doesn't Do Anything on Mac on Angular components

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#8989]
****
Related to https://github.com/microsoft/azuredatastudio/issues/5023, while finding a fix for the aforementioned bug, we realized that mac is invoking editor's select All irrespective of whether an editor is associated with it. This should effect all angular components, so filing this to track it.

**Comment by Charles-Gagnon** [comment]
@MaddyDev I'm going to close this for now actually. Unless we think this is a big enough issue to try and fix all-up I think it's fine just to acknowledge and reopen if we want to fix it in the future.
