### ISSUE TITLE
Feb RC builds aren't following the correct naming convention

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8993]
Stable release build builds should include the entire product version in the filename and folder name.  Currently the file and folder are missing the 3rd digit.

![temp1](https://user-images.githubusercontent.com/599935/73486556-3eec1b80-435a-11ea-9a52-438fdfd90b08.jpg)

**Comment by Charles-Gagnon** [comment]
Fixed, the installers should be fine. This was just a file renaming issue.
