### ISSUE TITLE
Linux tar.gz build fails to run on default CentOS 7 install

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#8994]
When I decompress the TAR.GZ on a default CentOS 7 machine I get the following error.  Changing the owner and mode on the subdirectory resolves the issue, but I shouldn't need root permissions to update the bits in order to run as a normal user.

```
[4285:0124/124537.503315:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was
found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You 
need to make sure that /home/karlb/Downloads/azuredatastudio-linux-x64/chrome-sandbox is 
owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

**Comment by kburtram** [comment]
@anthonydresser any ideas what's going on here?  I haven't confirmed it's related to the build pipeline changes yet, that is one of the more significant changes related to Linux builds that's occurred recently.

**Comment by kburtram** [comment]
FWIW, I verified that vscode has the same error on this machine.

**Comment by anthonydresser** [comment]
The old build definition is this there. Could run that and see if the same issue occurs.

**Comment by kburtram** [comment]
@anthonydresser since it repros on vscode I doubt it's related to the build definitions.  Sorry, I should have made that point clearer in my previous comment.  I guess this is something related to Electron or vscode that will probably need to be fixed upstream.

**Comment by kburtram** [comment]
Closing as upstream.
