### ISSUE TITLE
Creating external tables attempts to put all external tables in dbo schema

### ISSUE THREAD

**Issue by mrdenny** [microsoft/azuredatastudio#8997]
Issue Type: <b>Bug</b>

When creating external tables on a BDC, all the external tables are created in the DBO schema, even if the tables are in a different schema on the source system. This is very problematic when there are two tables with the same name, in different schemas.  ADS just fails to create the external table and doesn't give any information as to why.

To repro, create a new schema on your source system called test1.  Create the table dbo.account and test1.account.

Create external tables using the GUI for both these tables.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.91GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
plan-explorer|Sen|0.9.6

</details>

**Comment by Charles-Gagnon** [comment]
@mrdenny You're able to modify the schema during table creation by changing the value in the input box for the destination table

![image](https://user-images.githubusercontent.com/28519865/77473963-867baa80-6dd3-11ea-8545-53eda255bdcf.png)

It looks like it currently isn't populating the schema with the source schema which would probably improve this experience but I wanted to make sure first that you were at least able to modify the schema without issue.

**Comment by mrdenny** [comment]
You can, but this is done table by table. For this example I a couple hundred tables across three schemas, and having them all in dbo by default didn’t work.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
denny@dcac.com<mailto:denny@dcac.com>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar Bookings<https://calendly.com/mrdenny>
[cid:image001.png@01D601E8.F8FE1590]<http://www.dcac.co/>
[cid:image002.jpg@01D601E8.F8FE1590]
[cid:image003.png@01D601E8.F8FE1590]
[cid:image004.jpg@01D601E8.F8FE1590]

**Comment by Charles-Gagnon** [comment]
Yeah - that's a good point. I'll try to take a look at this while I'm doing the other work to at least fix it to default to the source schema if that schema exists in the destination DB. There's a lot more we could do here but that should hopefully be an easy fix in the short term.

**Comment by mrdenny** [comment]
That would be a good solution. Or even just create the schema if it doesn’t exist.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting, an Inc. 5000 company
denny@dcac.com<mailto:denny@dcac.com>
(o) +1 (323) 686-1478<tel:3236861478> | (d) +1 (213) 973-3669<tel:2139733669>
Online Calendar Bookings<https://calendly.com/mrdenny>
[cid:image001.png@01D601F0.D84DBB40]<http://www.dcac.co/>
[cid:image002.jpg@01D601F0.D84DBB40]
[cid:image003.png@01D601F0.D84DBB40]
[cid:image004.jpg@01D601F0.D84DBB40]

**Comment by Charles-Gagnon** [comment]
Just merged in a fix so that it'll default to the source schema if that schema exists in the destination DB. I'll close this now then - there's extra enhancements that could be done to make this more fully featured (such as creating schemas) but that's currently not work we have planned to take on.

**Comment by mrdenny** [comment]
That'll work. People can create the schema in advance and that's a reasable thing to ask people.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting
denny@dcac.com | +1 (323) 686-1478

________________________________
