### ISSUE TITLE
When external tables fail to create, no information is given

### ISSUE THREAD

**Issue by mrdenny** [microsoft/azuredatastudio#8998]
Issue Type: <b>Bug</b>

When an external table fails to create, no information is given as to why.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.80GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
plan-explorer|Sen|0.9.6

</details>

**Comment by aaomidi** [comment]
Is this with the import extension?

**Comment by mrdenny** [comment]
No, this is with the native process.

Thank You,
Denny Cherry
Owner & Principal Consultant
Denny Cherry & Associates Consulting
denny@dcac.com | +1 (323) 686-1478

________________________________

**Comment by Charles-Gagnon** [comment]
@mrdenny Is this using the Create External Table wizard? If so are you not seeing the pop up with the error message when it fails?

![image](https://user-images.githubusercontent.com/28519865/77476212-6817ae00-6dd7-11ea-9ae8-506ceac79c66.png)

If this is not happening are you able to make a recording of the steps you're taking so I can see what it looks like when it fails?

**Comment by mrdenny** [comment]
no, it was just popping up with the Create external table failed message with no other info. But if this is already being rewritten it might be worth ignoring this until then.

**Comment by Charles-Gagnon** [comment]
And this was after clicking Create in the wizard dialog and it closing? And it did still have the dialog shown in my screenshot - just not with any useful information?

If you see it again and can get a screenshot that might help too - the actual creation of the external table isn't really going to change. I'm just modifying how we're querying the metadata for the schema to use to create the table.

**Comment by Charles-Gagnon** [comment]
@mrdenny I'll let this stay closed for now since I'm not sure there's much actionable work I can do here without running into the issue myself. If you see it again try to get some more information and then let me know and I'll try to dig more into it!
