### ISSUE TITLE
If memory usage is high, ADS just goes white

### ISSUE THREAD

**Issue by mrdenny** [microsoft/azuredatastudio#8999]
Issue Type: <b>Bug</b>

If memory usage on the machine ends up being to high, ADS just goes white and doesn't show anything. This usually happens when ADS is minamized. You have to kill ADS in order to restart it normally.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
plan-explorer|Sen|0.9.6

</details>

**Comment by richardtallent** [comment]
This started happening for me as well with the most recent release. May be related more to graphics resources than system RAM. I'm able to recover the window by aiming carefully for where the restore icon would be on the top-right corner of the window.

I'm using a fairly new Dell laptop running Windows 10, my other running apps usually include Chrome, VS, Excel, VS Code, Access, Outlook, and Teams.

**Comment by Charles-Gagnon** [comment]
@richardtallent You're still seeing this with the 1.15.0 release (that came out today)?

**Comment by richardtallent** [comment]
I've been working with 1.15.0 for about a week now, no issues, so this appears to be fixed!

**Comment by Charles-Gagnon** [comment]
Thanks for the confirmation, I'm going to close this out then as fixed and if anyone else is seeing this issue again let us know!

**Comment by ThatDeaf-ITGuy** [comment]
So I'm seeing this on Linux with v1.23.0. The server that its running on has 4 cores, 4GB of RAM, and 4GB of swap space. Should also mention that this is a remote server that I'm VNC'd into.

I get the white screen behavior regardless of whether the window is maximized or minimized, and it happens when I launch Azure Data Studio. Restarting the app doesn't seem to help. Moving to a different box which has more RAM fixes the issue.
