### ISSUE TITLE
RAISERROR call in BDC external table script only returns line raiserror line number

### ISSUE THREAD

**Issue by mrdenny** [microsoft/azuredatastudio#9000]
Issue Type: <b>Bug</b>

Using RAISERROR in the CATCH block when creating the script with the external table wizard doesn't return correct information.

As is currently written the RAISERROR will only throw error 50000 and reuturn the line number that has the RAISERROR statement. If you change this line to be simply "THROW" this will return the correct error message number and the correct line number.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.17134

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (2.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
plan-explorer|Sen|0.9.6

</details>

**Comment by Charles-Gagnon** [comment]
Thanks @mrdenny! I'm actually currently working on a refactor of the wizard to utilize a new stored procedure that's being added so I'm going to close this as Won't Fix since the new method won't be using any of the old scripts. 

It'll still use those scripts for older versions of SQL that don't have the new stored procedure though so if this is causing any issues in your experience let me know and I can work on fixing those so at least it isn't going to break anything for anyone.
