### ISSUE TITLE
Edit Data: On edit data the table name isn't shown anywhere

### ISSUE THREAD

**Issue by MaddyDev** [microsoft/azuredatastudio#9006]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open any table and right click to launch edit data.

Expected: 
It should open table in edit mode and show the table name on the title-header.
Current behavior:
It opens the table in edit mode but doesn't show the table name info anywhere. It shows the query instead of the table-name now.

**Comment by MaddyDev** [comment]
I see this issue again.

**Comment by kburtram** [comment]
This looks like the same underlying issue as https://github.com/microsoft/azuredatastudio/issues/9058.  And should be fixed in today's release/1.16 build.

**Comment by kburtram** [comment]
Closing as duplicate of #9058 which is fixed in today's build
