### ISSUE TITLE
TSG Notebook links aren't working

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9008]
Clicking on a link in the 2019 TSG results in an error similar to this :

```
Unable to open 'sop007-get-key-version-information.ipynb': Unable to read file 'd:\src\azuredatastudio\out\vs\code\electron-browser\common\sop007-get-key-version-information.ipynb' (Error: Unable to resolve non-existing file 'd:\src\azuredatastudio\out\vs\code\electron-browser\common\sop007-get-key-version-information.ipynb').
```

Repros on both 1.15 and dev. 

Probably related to https://github.com/microsoft/azuredatastudio/issues/8534

**Comment by Charles-Gagnon** [comment]
@chlafreniere @MaddyDev What's the status on the relative links issue? This is going to be pretty annoying for anyone using the TSG.

**Comment by MaddyDev** [comment]
relative links only work if the notebook is trusted. We'll have to take a look on how to make it work if it's not trusted. But once I make it trusted, I don't see the error you got. Will look into it.

**Comment by chlafreniere** [comment]
This reproes when the book is unsaved. @MaddyDev can you take a look?

**Comment by MaddyDev** [comment]
> This reproes when the book is unsaved. @MaddyDev can you take a look?

Not able to repro it on my machine, do either of you have a min to show me? Thanks
