### ISSUE TITLE
Azure Account signin failing silently if account has no Azure tenants

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9009]
Trying to log in with an account that doesn't have any Azure tenants, nothing happens after logging in and no indication an error occurred. Console has this :

![image](https://user-images.githubusercontent.com/28519865/73562771-ac5a8380-4410-11ea-9488-bb11b0dca0c0.png)

We should ideally surface that to the user so they know why it didn't add.

**Comment by kburtram** [comment]
@Charles-Gagnon or @aaomidi  do we know if this is a regression from 1.14.1?

**Comment by Charles-Gagnon** [comment]
Merged into 1.15 branch https://github.com/microsoft/azuredatastudio/commit/fb4ab6b5016e06460407bbd6beed29eff66ea3b4
