### ISSUE TITLE
exec sp_executesql does not show Query Plan

### ISSUE THREAD

**Issue by glittle** [microsoft/azuredatastudio#9010]
- Azure Data Studio Version: 1.14.1

Steps to Reproduce:

1. Run this: (using any table)

```
select * from Users
exec sp_executesql N'select * from Users'

```
Then click "Explain".  My result:

   ![image](https://user-images.githubusercontent.com/85186/73563674-2c85e680-441b-11ea-8f96-7afb4c21aa26.png)

As you can see, when `exec sp_executesql` is used, there is no query plan available.

The same set of queries running SSMS result in:

   ![image](https://user-images.githubusercontent.com/85186/73563797-7078eb80-441b-11ea-8843-28e57cfea91d.png)

**Comment by glittle** [comment]
This is particularly needed because scripts copied from SQL Profiler are in this format.

**Comment by erinstellato-ms** [comment]
This behavior is consistent across ADS and SSMS for estimated plans.  When viewing actual plans in the new query plan viewer feature in the latest release, the plans display correctly (and the same between ADS and SSMS).
