### ISSUE TITLE
Azure signed-in landing page shows a blank page

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9011]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Sign in to Azure account

Expected: Azure Data Studio branded landing page

Actual:

![image](https://user-images.githubusercontent.com/599935/73566864-d19fbf80-4419-11ea-930f-2d6a78b12286.png)

**Comment by kburtram** [comment]
@aaomidi have you seen this before?

**Comment by aaomidi** [comment]
This means the webserver didn't start for some reason. Hmm
