### ISSUE TITLE
Azure explorer node spins forever when credentials are expired

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9013]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Add Azure accounts and let the credentials expire
2. Expand one of the subscription nodes

Expected: Error message that credentials need to refreshed and perhaps the Account dialog should be displayed

Actual: The node spins forever with no error message.

**Azure explorer looks like this**
![image](https://user-images.githubusercontent.com/599935/73567926-38be7380-441c-11ea-98bc-afc465e20411.png)

**Accounts are expired**
![image](https://user-images.githubusercontent.com/599935/73567977-51c72480-441c-11ea-925e-f9b83da41c0a.png)

**Comment by abist** [comment]
@aaomidi This might be fixed now with the work you're doing right now, is that correct?

**Comment by aaomidi** [comment]
Yeah this is fixed with the new azure auth.

**Comment by abist** [comment]
@aaomidi Should this issue be closed then?
