### ISSUE TITLE
Export XML results from Notebook table doesn't format content

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9017]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Run a query in a Notebook cell
2. Export the results to an XML file

Expected: Results are formatted
Actual: Results are not formatted

**This is XML results from Query Editor and Notebook side-by-side for comparision**
![image](https://user-images.githubusercontent.com/599935/73572402-8b505d80-4425-11ea-8b1e-90813b7e4afa.png)

**Comment by lucyzhang929** [comment]
This issue is no longer reproducible in stable.
