### ISSUE TITLE
Comments cause strange behavior in PowerShell notebooks with functions

### ISSUE THREAD

**Issue by BobPusateri** [microsoft/azuredatastudio#9018]
- Azure Data Studio Version:
Version: 1.15.0-insider (user setup)
Commit: 7d751a20ab4ae23799b8ac61f20000d4d9ed1b61
Date: 2020-01-31T18:42:04.788Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

- Steps to Reproduce:

Create a PowerShell notebook with a cell containing one or more functions. At the end of each function, either on the same line as the closing bracket or on the line following that, add a comment. 

When running the cell to define the function(s) so they can be called in subsequent cells, the cell will never complete - it just keeps running. 

Removing the comments, or placing them in multi-line comment format, causes the cell to execute properly.

I have created a [PowerShell notebook to demonstrate this](https://gist.github.com/BobPusateri/5b99ff352e9e2166204be54ce671b954).

**Comment by SQLDBAWithABeard** [comment]
Yup, it's a very strange one and I confirm that I have the same behaviour on my machine as well

**Comment by chlafreniere** [comment]
Which version of the powershell-kernel python package is installed on your machines?

The Manage Packages button on the notebook toolbar will take you to a dialog that lists all of the packages and their versions.

0.1.3 is the latest.

**Comment by chlafreniere** [comment]
On the off chance that you're both on an older version of the PS package, I created another bug (and its corresponding PR) to track ensuring that we prompt users to install the newest version of the Powershell kernel. #9023

**Comment by BobPusateri** [comment]
@chlafreniere I believe that was exactly the issue! I was running 0.1.2. As soon as I upgraded to 0.1.3, that demo notebook behaved exactly as expected. Thank you so much for pointing that out and taking care of this!

**Comment by SQLDBAWithABeard** [comment]
Also confirm that this has resolved the issue.

When was this new package released? I was testing on a brand new deployed win 10 machine that a client had given me where I installed ADS only last week and I had version 0.1.2

Where is this information? and can it be surfaced in a public manner ?

I agree that #9023 will provide a prompt and that is a good thing but it will also be good for those of us who inform and educate people to know as this would help to resolve issues quicker (speaking as someone who gladly receives many questions about PowerShell notebooks :-) )

**Comment by corivera** [comment]
Closing this one since it's related to https://github.com/microsoft/azuredatastudio/issues/9022
