### ISSUE TITLE
Notebooks: Ensure Users are Prompted to Install Latest Powershell Kernel Package

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9022]
In jupyterServerInstallation, we don't give users a notification that a new version of the powershell kernel is available (it has version 0.1.2 as the latest version, whereas 0.1.3 is the real latest version).

**Comment by chlafreniere** [comment]
Not a February blocker.

**Comment by SQLDBAWithABeard** [comment]
When was this new package released? I was testing on a brand new deployed win 10 machine that a client had given me where I installed ADS only last week and I had version 0.1.2

Where is this information? and can it be surfaced in a public manner ?

I agree that #9023 will provide a prompt and that is a good thing but it will also be good for those of us who inform and educate people to know as this would help to resolve issues quicker (speaking as someone who gladly receives many questions about PowerShell notebooks :-) )

**Comment by chlafreniere** [comment]
@SQLDBAWithABeard we released the new package in early January, if memory serves; we do more involved testing before making it a package that we prompt users to install by ensuring that more folks test the package beforehand.

I'll defer to @yualan for how to better surface this info in a public manner, so I'll let him comment from the PM perspective 😄
