### ISSUE TITLE
The praogram goes white/blank

### ISSUE THREAD

**Issue by TerjeST** [microsoft/azuredatastudio#9028]
Issue Type: <b>Bug</b>

I've started experienceing tha tthe program goes blank (totally white), even the buttons and the windo w fram.  I can see the cursor change, but nothing happens when I presse it.

I'm sure Im running th altest release, and I've uninstalled and reinstalled it (with a reboot in between). And it's still there.

Some times, I can be lucky that by resizing the program(draggin the edge) it comes back, but now always.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz (4 x 2394)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.88GB (0.38GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by kburtram** [comment]
@TerjeST thanks for reporting this issue!  We are tracking this bug in https://github.com/microsoft/azuredatastudio/issues/8775 so I'll close this as a duplicate.  We think the issue  may be resolved in the latest insiders builds.  Please give that a try and let us know if you continue to see the issue, or we have the Feb release planned later this week that hopefully resolved the issue (we still don't have an internal repro to validate with, unfortunately).
