### ISSUE TITLE
Restoring an SQL-Server 2008 R2 database backup file fails with error (Linux)

### ISSUE THREAD

**Issue by ststeiger** [microsoft/azuredatastudio#9029]
AzureDataStudio (or the db-engine respectively) on Linux, fails to restore an SQL-Server 2008R2 database backup file (.bak). 

If I restore a .bak file created by SQL-Server-2008R2, I get an out of memory exceptions (but my laptop has 32 GB RAM, and 90% of that is free - also enough HD space -150GB free). 
(I use sql-server 20017 Linux docker image)

If I restore the .bak file from SQL-Server 2008R2 on Windows on SQL-Server 2016, then set compatiblity level to 130, and then re-backup, and restore that 2016-backup on Linux, then it works... 

Version: 
SQL-Server 2017 Ubuntu docker image
Azure Data Studio Insider Build Feb-03-2020 10:54 CET: 
https://azuredatastudio-update.azurewebsites.net/latest/linux-x64/insider

It also fails in older/stable versions.

**Comment by kburtram** [comment]
Azure Data Studio only supports SQL Server 2014+.  The suggested workaround for this server version would be to try to run the restore using SQL statements directory or to use SSMS on Windows if available.

**Comment by ststeiger** [comment]
If so, maybe it should output an error then, like "backup file version only supported as of SQL-server 2014+", or whatever, instead of just running around in circles forever until it runs out of memory, and finishing with some cryptic error message about "not enough memory" ? 

But I guess having to guess what the problem is, goes as implicit.

**Comment by kburtram** [comment]
@ststeiger fair point.  I created this issue to provide a general error message when connecting to downlevel versions https://github.com/microsoft/azuredatastudio/issues/16856.  Thanks for the suggestion.
