### ISSUE TITLE
Edit Data new row doesn't show up until after a cell change is committed

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9033]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Edit Data on a table
2. Add a new row then tab into the next new row

Expected: Once the focus cursor moves into the new row, then additional new row should be appended below

Actual: The additional new row is only added once a cell change is committed to one of the cells in the new row

**Cursor in new row, but no new row shown**
![image](https://user-images.githubusercontent.com/599935/73688846-c5b63680-4681-11ea-92a5-893443c23b99.png)

**New row only shown after a cell is changed.  The new row should have shown once the current new row received focus**
![image](https://user-images.githubusercontent.com/599935/73688874-d666ac80-4681-11ea-8dc9-2428a592ee11.png)

**Comment by kburtram** [comment]
@smartguest I think this may be a regression from the Edit Data refactor.  Could you confirm whether this is a regression?  And prepare a fix?

**Comment by smartguest** [comment]
@kburtram This isn't a regression, this was on builds as early as the September 2019 build, fix is already created.
