### ISSUE TITLE
Dictionary of term pairs to ignore for schema compare

### ISSUE THREAD

**Issue by matepolsps** [microsoft/azuredatastudio#9038]
It would be useful to be able to give the schema compare tool a possibility to specify pairs of terms that are to be ignored when the comparison is made. The use case is that I have a dev/test environment that I want to compare with prod, and there are different references, object names for certain items due to the different context of each environment. e.g. I have a Staging and DWH database in each environment, where they are called test_Staging and test_DWH vs the production environment with prod_Staging and prod_DWH. Whenever I have 3-part object names that include the database name, those will be different in each environment. However, when I do the compare, such difference implies no action to be taken, thus I would like such differences not to be highlighted in the comparison results.

**Comment by kisantia** [comment]
closing due to lack of additional interest. Can reopen later if there are more requests
