### ISSUE TITLE
Active Window Indicator

### ISSUE THREAD

**Issue by mikalelu** [microsoft/azuredatastudio#9053]
Issue Type: <b>Feature Request</b>

For each open quety window, there is a tab with an identifier for the query. Howeve, when several query tabs are lined up along the top, how do I know which query is the active window (has focus?). Please implement a visual cue to indicate which tab is active. If the indicator already exists, please let me know how to recognize it.

Azure Data Studio version: Azure Data Studio 1.12.2 (c9bef82ace6c67190d0e83820011a2bbd1f793c1, 2019-10-11T04:05:05.798Z)
OS version: Darwin x64 17.7.0

**Comment by Charles-Gagnon** [comment]
@mikalelu The active tab is colored differently and flows into the active editor : 

![image](https://user-images.githubusercontent.com/28519865/73859083-57db4d80-47ee-11ea-844f-d8ec921e1802.png)

![image](https://user-images.githubusercontent.com/28519865/73859124-67f32d00-47ee-11ea-8a47-a15e84fe4869.png)

There are other color themes as well if you open the command palette and run the `Preferences: Color Theme` command.

Do any of these help make it more obvious which tab is the active one?

**Comment by mikalelu** [comment]
Thank you for your swift and helpful response.

I was finally able to observe the color difference between the tabs by reviewing a darker color theme. Then, when I returned to the default theme, I could detect the barely perceptible difference between the background color, and the active tab color. Not exactly white-on-white, but close enough.

Now to figure out how to build my own color theme...which of course, will display an obvious indication of the active tab.

Thanks again for your feedback.

**Comment by Charles-Gagnon** [comment]
Glad that was able to help! You can use [this guide](https://code.visualstudio.com/docs/getstarted/themes#_creating-your-own-color-theme) to get started on creating your own theme (and find information about modifying existing ones).
