### ISSUE TITLE
Database Dashboard Search Does Not Show TVF's

### ISSUE THREAD

**Issue by rkdiekhoffwk** [microsoft/azuredatastudio#9055]
Issue Type: <b>Bug</b>

The search tool on the database dashboard does not bring back table-valued functions searched on.  Scalar-valued functions do show.

1. Create a new table-valued function in a database of choosing.
2. Right-click on the database on the Connections side bar and choose 'Manage'
3. Try to search for the TVF created in the Search tool on the dashboard.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz (8 x 3592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.89GB (4.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (10)</summary>

Extension|Author (truncated)|Version
---|---|---
pastetheplan|dre|0.2.0
agent|Mic|0.45.0
datavirtualization|Mic|1.2.0
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
azdata-sanddance|msr|1.3.9
sql-search|Red|0.3.6
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

**Comment by oappelt** [comment]
This bug is not covered by closed issue #8832.

Inlined TVF (type: 'IF') search does work.
But not-inlined TVF (type: 'TF') do not appear as search result.
ADS Version: 1.15.0 (OS: Linux x64 4.15.0-76-generic)
