### ISSUE TITLE
[renderer1] [error] Error while adding account: Error: Entry not found in cache.

### ISSUE THREAD

**Issue by wforney** [microsoft/azuredatastudio#9056]
Issue Type: <b>Bug</b>

When trying to add my Azure account to it goes through device login and succeeds but then shows this error and will not add the account to the UI.

[renderer1] [error] Error while adding account: Error: Entry not found in cache.

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.19555

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6850K CPU @ 3.60GHz (12 x 3599)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.92GB (13.60GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (30)</summary>

Extension|Author (truncated)|Version
---|---|---
sqlops-combine-scripts|Bat|2.0.1
firstresponderkit|dre|0.5.0
pastetheplan|dre|0.2.0
sqldm-performance-insights|IDE|0.4.0
newdatabase|kev|1.0.0
ssmskeymap|kev|1.1.0
alwayson-insights|mat|0.2.1
mssql-db-insights|mat|0.2.2
mssql-instance-insights|mat|0.2.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.2
cms|Mic|0.6.0
dacpac|Mic|1.1.0
datavirtualization|Mic|1.2.0
import|Mic|0.12.0
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2019.12.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.1.0
server-report|Mic|0.2.1
sql-dw|Mic|0.0.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
sqlops-spexecutesql-to-sql|pej|0.0.1
sql-search|Red|0.3.6
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(3 theme extensions excluded)

</details>

**Comment by wforney** [comment]
It seems similar to other issues but they were closed and this is still not fixed.

**Comment by kburtram** [comment]
@aaomidi any thoughts on this one?  I think the Azure Auth implementation has changed a bit since 1.141.?

**Comment by aaomidi** [comment]
The cache method is unfortunately the same, but this should get fixed with the new auth method I'm planning for April (and insiders by end of this week)

**Comment by aaomidi** [comment]
Fixed with the latest insiders.
