### ISSUE TITLE
File titles aren't being correctly restored during HotExit

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9058]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open an untitled SQL query editor and modify the content
2. Close and reopen ADS

Expected: Documents are restored with the same title they had prior to closing ADS

Actual: Documents have a title based on the files content

*The document below should say something like `SQLQuery_1`*
![image](https://user-images.githubusercontent.com/599935/73872484-a267c480-4804-11ea-9788-4931fae891b9.png)

**Comment by kburtram** [comment]
@smartguest this seems similar to #9012 but is impacting SQL query documents.  Could you please verify this isn't related to the Edit Data changes?  And in either case, could you please help root cause this issue?  Thanks!

**Comment by smartguest** [comment]
This doesn't appear to be related to any of the code I did, it does not use the newSqlEditor at all, and I only changed it so that the EditData Editor is affected, not this one.

**Comment by smartguest** [comment]
Upon closer inspection, it turns out when you enter ANYTHING into the editor, it updates the title for the header, this must mean we must make the editor so it doesn't alter the header.

**Comment by kburtram** [comment]
This appears to be fixed in Feb RC build.  I'll move to March milestone since we fixed directly in release/1.15.

**Comment by Charles-Gagnon** [comment]
When we fix this make sure we're adding tests for the title of untitled SQL editors. The tests we disabled in 1.15 should be a good place to start for what those would look like (https://github.com/microsoft/azuredatastudio/blob/master/src/vs/workbench/test/common/editor/untitledTextEditor.test.ts#L306)

**Comment by Charles-Gagnon** [comment]
FYI - this was indeed an intentional change on VS Codes part : https://code.visualstudio.com/updates/v1_42#_untitled-editor-improvements

**Comment by kburtram** [comment]
Fixed
