### ISSUE TITLE
Edit Data grid doesn't properly resize when showing\hiding SQL Pane

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9061]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open Edit Data on a table with lots of rows and columns (~100+ rows and ~10+ columns) so that the grid requires horizontal and vertical scrollbars
2. Open the SQL Pane window and update the `TOP` clause to be something like `TOP 10`
3. Collapse and reexpand the SQL pane

Note: this is just one example variant of the repro

Expected: The grid is resized so that scrollbars are positioned correctly and there is no extraneous whitespace

Actual: Resizing is inconsistent and not correct.  The two screenshots below show a couple examples.

**Example 1**
![image](https://user-images.githubusercontent.com/599935/73882529-19a65400-4817-11ea-8d0e-acd62ae733ff.png)

**Example 2**
![image](https://user-images.githubusercontent.com/599935/73882689-5c682c00-4817-11ea-85db-3399d48fe672.png)

**Comment by kburtram** [comment]
@smartguest could you please prepare a PR that resolves this issue so we can consider taking for the Feb release?

**Comment by smartguest** [comment]
I've been attempting to figure out where the scroll bar is handled at, I'm going to need assistance on this issue.

**Comment by aaomidi** [comment]
@smartguest I think what you want to do is:

https://github.com/microsoft/azuredatastudio/blob/8c61538a2737a68d1c588e26e59a5818d14fb529/src/sql/workbench/contrib/editData/browser/editDataEditor.ts#L500

Probably add another this._queryModelService.resizeResultsets(this.uri). the this.input.uri is referencing the SQL query part of EditData
