### ISSUE TITLE
Display name ignored for advanced connection property: Data value used instead

### ISSUE THREAD

**Issue by Xtrimmer** [microsoft/azuredatastudio#9066]
In ADS, when defining a connection option with selectable values (combo box), it is possible to have what the user sees and selects be a different value than what is put in the options object that is sent to sqltoolsservice via Json RPC call. This is evident with the Authentication type.
If a user selects "Windows Authentication"
![image](https://user-images.githubusercontent.com/4079568/73897342-aadaf200-483a-11ea-9219-651927dc2bf3.png)
Then "Integrated" is sent as the value to sqltoolsservice.
![image](https://user-images.githubusercontent.com/4079568/73897423-e5448f00-483a-11ea-8d07-00c841bb6566.png)
These category values, selectable by the user, are defined in the [package.json](https://github.com/microsoft/azuredatastudio/blob/343daf58fef1a5b08c37efb33e04ec3ef08e3875/extensions/mssql/package.json#L552-L584) and corresponding resource strings in the [package.nls.json](https://github.com/microsoft/azuredatastudio/blob/343daf58fef1a5b08c37efb33e04ec3ef08e3875/extensions/mssql/package.nls.json#L77-L81)
![image](https://user-images.githubusercontent.com/4079568/73897685-c4c90480-483b-11ea-9283-a99ceb5cc4ab.png)
![image](https://user-images.githubusercontent.com/4079568/73897696-c98db880-483b-11ea-941e-75e6c3b95d43.png)
While this configuration works for authentication type, it does not work for those advanced connection options. An example is the advanced security setting Enclave Attestation Protocol. While a separate display name and value are defined in the same way, ADS ignores the display name and uses the data value for both display and as the value sent to sqltoolsservice back-end.
The following images show that "AAS" and "HGS" are both shown to the user and sent to the back end. The desired behavior would be for "Azure Attestation" and "Host Guardian Service" to be displayed to the user for selection and have "AAS" and "HGS", respectively, sent to the back-end.
![image](https://user-images.githubusercontent.com/4079568/73897978-b7604a00-483c-11ea-8cc6-0f62bdcddcdd.png)
![image](https://user-images.githubusercontent.com/4079568/73897986-bf1fee80-483c-11ea-8a37-ed43f652fe10.png)
![image](https://user-images.githubusercontent.com/4079568/73897992-c3e4a280-483c-11ea-9425-6ba7d55352b1.png)
![image](https://user-images.githubusercontent.com/4079568/73897997-c810c000-483c-11ea-981a-4af5dcf9dbb0.png)

**Comment by aaomidi** [comment]
External requirement per @Xtrimmer, lets try to get this issue fixed for March.

**Comment by aaomidi** [comment]
Is this an issue that has to land in March? Can we plan for April?
