### ISSUE TITLE
Untitled editor automatically opened on startup

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9070]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open ADS and close all windows
2. Close and reopen ADS

Expected: Welcome page or "watermark" screen displayed

Actual: An untitled editor is opened

Note: This is a change in behavior that occurred at some point, but it is not a regression from 1.14.1.  We'll look at the desired behavior when we look at fixing 1st-Launch and Startup experiences in the next couple months.

*Untitled document is opened even though it wasn't requested by user*
<img width="1029" alt="Screen Shot 2020-02-06 at 11 17 51 AM" src="https://user-images.githubusercontent.com/599935/73970977-f6d97580-48d2-11ea-885f-7001be919d39.png">

**Comment by chlafreniere** [comment]
Just as another data point, this looks to happen when the option to show the welcome page at startup is unchecked.

When the welcome page is shown at startup and no windows were previously open, only the welcome page is shown.

**Comment by kburtram** [comment]
This doesn't repro on recent builds.

**Comment by catalin-ifacts** [comment]
it still does.
