### ISSUE TITLE
legend position for chart is not working

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9071]
![Screen Shot 2020-02-06 at 12 02 21 PM](https://user-images.githubusercontent.com/13777222/73974077-91888300-48d8-11ea-8d8f-ea5e71328851.png)

**Comment by chlafreniere** [comment]
I just confirmed that this behavior is also present in 1.14.1

**Comment by alanrenmsft** [comment]
also, the label, min/max value options are not working.

**Comment by chlafreniere** [comment]
Hmm, that's not good. Let's discuss further.
