### ISSUE TITLE
Ability to sort files in Explorer

### ISSUE THREAD

**Issue by smc395** [microsoft/azuredatastudio#9072]
### Environment
- Version: 1.14.1 (user setup)
- Commit: f9b968c1ae514a0d1210788629e1c69125857279
- Date: 2019-12-24T02:42:26.303Z
- VS Code: 1.38.0
- Electron: 6.1.5
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 6.1.7601

#### User Story
As a developer, I would like the ability to sort the files within the Explorer view by name, modified date, extension type, etc. in ascending or descending order similar to how Windows Explorer works.

#### Acceptance Criteria
- Ability to sort files within the Explorer view by name, modified date, extension type, etc. in ascending or descending order 
- Includes ability to sort folders

**Comment by alanrenmsft** [comment]
Thanks for submitting the issue, i am assuming you are talking about the below view, this is actually coming from VSCode. ADS is a fork of VSCode, please open the issue in VSCode repo: https://github.com/Microsoft/vscode/issues.

i am closing the issue as an upstream issue.
![Screen Shot 2020-02-24 at 12 58 46 PM](https://user-images.githubusercontent.com/13777222/75190574-7190f600-5705-11ea-88eb-4a9ed3b9d2a2.png)
