### ISSUE TITLE
SQL Import hangs when loading table schema for Azure db

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#9076]
- Azure Data Studio Version:
Version: 1.15.0
Commit: ebf47df35ef56748747b51280155e7fd98a5883e
Date: 2020-02-04T22:55:14.654Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Connect to an Azure db
2. Launch Import wizard from the Azure db's context menu
3. Table schema dropdown will not load:
![image](https://user-images.githubusercontent.com/31145923/73987441-4335ad00-48f5-11ea-94fd-597ad25df1ec.png)

**Comment by aaomidi** [comment]
If I recall correctly this feature wasn't to be used with Azure DBs?

I'll double check the issue again.

**Comment by markfischle** [comment]
I get the same issue (I suspect) when trying to load either a csv or text file. For test purposes I am trying to load just two rows of data, as follows:

'EFDECD', 'Almond', '239'
'CD9575', 'Antique Brass', '205'

but wizard does not get past Step 1 of 4.  I tested with & without header rows; txt & csv files. 

![image](https://user-images.githubusercontent.com/28077509/76671440-10f92880-65e2-11ea-96ae-8787b21f3192.png)

Build info below



Version: 1.15.1 (system setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18362

**Comment by Unimog** [comment]
I'm getting this error every time I use the import wizard.  What information do you need?

**Comment by aaomidi** [comment]
@Unimog Are you using this with Azure DBs? This is a known issue for that at the moment.

Connecting to the master DB in Azure would temporarily fix it but I understand if you can't do that due to permissions.

We're working on a fix for this.

**Comment by Unimog** [comment]
Yes, on Azure.  Thanks for the workaround.  I can try that.
