### ISSUE TITLE
Schema compare OK button is always disabled for comparing databases

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#9077]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Open schema compare dialog
2. select databases for source and target

expected: OK button is enabled after selecting db names
actual: OK is disabled without any error message 

![image](https://user-images.githubusercontent.com/17187348/73987429-3a44db80-48f5-11ea-93f3-b9015be75336.png)

**Comment by kburtram** [comment]
I could not repro this either with the latest RC product and extension builds.  So I'll close now as "no repro" please reactive if you see this again.  Thanks!
