### ISSUE TITLE
Edit Operator UI doesn't have begin/end boxes for Monday-Thursday

### ISSUE THREAD

**Issue by Benjin** [microsoft/azuredatastudio#9078]
Version: 1.15.0
Commit: ebf47df35ef56748747b51280155e7fd98a5883e
Date: 2020-02-04T22:55:14.654Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Repo steps:
1. Open SQL Agent dashboard
2. Go to Operators panel
3. Click "New Operator" or right-click on an existing operator and select "Edit"

Expected:
* ability to select duty schedule hours for M-Th individually from Friday

Reality:
* Mis-aligned grid
* No workday spinner for M-Th
* Checking M-Th enables the workday spinners for Friday

![image](https://user-images.githubusercontent.com/1609827/73987101-35335c80-48f4-11ea-814e-6499be76b819.png)

**Comment by aaomidi** [comment]
This is intended

Monday - Friday is handled by one time box.

Saturday and Sunday are handled separately.

The UI is a bit of a mess though, so it causes confusion.
