### ISSUE TITLE
Azure Viewlet Filter Subscription OK Button is Missing

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9079]
From the Azure viewlet, click the filter action on an account. On the RC build, the OK button is missing from the quick pick list, not allowing me to filter which subscriptions are shown in the viewlet.

1.14.1:
![image](https://user-images.githubusercontent.com/40371649/73987764-4bdab300-48f6-11ea-9585-2a2ed40a0777.png)

1.15.0:
![image](https://user-images.githubusercontent.com/40371649/73988050-644acd80-48f6-11ea-94de-62c656a1b0c7.png)

**Comment by chlafreniere** [comment]
Putting this in February so that it shows up in our query. Can always move it out if it's deemed necessary.

**Comment by Charles-Gagnon** [comment]
While the OK button not being there is definitely a bug and should ideally be fixed - do note that you can still filter the subscriptions by hitting enter after selecting/unselecting the subscriptions that you want. (Just clicking out of the quick pick cancels it though, you have to actually hit enter)

**Comment by aaomidi** [comment]
This is a behavior change from vscode - the fix for it would be creating our own showQuickPick, but I'm not sure if it's a large enough issue for February.

@Charles-Gagnon thoughts?

**Comment by aaomidi** [comment]
![image](https://user-images.githubusercontent.com/1465785/73990720-e3440400-48fe-11ea-8203-f6a807cc19af.png)

e.g. Also using showQuickPick, no more okay button.

**Comment by Charles-Gagnon** [comment]
We'll discuss it tomorrow, but I think since the feature still works we should just look at whether we want to add the button back in for next month's release.

**Comment by aaomidi** [comment]
Tracking: https://github.com/microsoft/vscode/pull/90269

Let's see if they think this is worthwhile to take or not.

**Comment by aaomidi** [comment]
Still no update from the vscode team.

**Comment by aaomidi** [comment]
Fixing this in master for ADS.

**Comment by kburtram** [comment]
Moving to April as a targeted fix was taken for March, but the issue persists in master.

**Comment by aaomidi** [comment]
I'm not seeing this issue anymore. I'm guessing vscode reversed their decision.

![image](https://user-images.githubusercontent.com/1465785/78283556-caa53400-74d2-11ea-9fe1-94476715641c.png)
