### ISSUE TITLE
Show Active Connections is Non-Functional when > 0 Active Connections Exist

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9081]
- Connect to a server in OE
- Click "Show Active Connections" action in the servers viewlet
- No connections will show up in the servers viewlet; action still says "Show Active Connections":

![image](https://user-images.githubusercontent.com/40371649/73988603-06b78080-48f8-11ea-8ac9-9e190e011214.png)

User is now stuck in this state until restarting ADS

**Comment by chlafreniere** [comment]
Moving to February for consideration. Regression from December.

**Comment by kburtram** [comment]
This is a slight variant of https://github.com/microsoft/azuredatastudio/issues/9081.  But both are related to lack of null ref checks in the ConnectionProfileGroup. 
 Fix out for review in https://github.com/microsoft/azuredatastudio/pull/9099.  Closing as duplicate to consolidate issues.
