### ISSUE TITLE
ESC doesn't revert cell edits when Editing Data on a table

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9083]
- Azure Data Studio Version: `1.15.0` - This is a regression from `1.14.1`

Steps to Reproduce:

1. Edit Data on a table
2. Start editing a cell then hit ESC character. 

Expected: Cell is reverted and focus moved out of cell.  Cell is no longer in edit mode.

Actual: Cell is not reverted and focus is not moved out of cell.  This functionality is particularly important when a cell has a validation error.  Users often hit ESC to revert the edits.  With the current experience user either has to keep editing the cell until its valid or bring up the row context menu to revert the row.  Otherwise, the user is stuck in a validation loop and can't move focus out of cell

*For example, below ESC should dismiss the notification, revert the cell edit and move focus out of edited cell*
<img width="658" alt="Screen Shot 2020-02-07 at 12 36 03 AM" src="https://user-images.githubusercontent.com/599935/74013681-e8767280-4941-11ea-8950-b8516acfdfe9.png">

**Comment by smartguest** [comment]
It turns out there was no listener for the keyboard, thus the revert Row function was never called.
