### ISSUE TITLE
Ctrl +Tab shortcut doesn't switch between editor 

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#9096]
- Azure Data Studio Version: 1.15.0

Ctrl +Tab is the default short key to navigate in editor but it doesn't seem to work any more  

![image](https://user-images.githubusercontent.com/17187348/74074104-9aa14f00-49c1-11ea-933b-858c16ed8aa2.png)

**Comment by EricTechcert** [comment]
Ctrl + Tab is working for me.

**Comment by kburtram** [comment]
This is fixed in Feb release.
