### ISSUE TITLE
Notebooks lost on save

### ISSUE THREAD

**Issue by rondunn** [microsoft/azuredatastudio#9101]
I'm persistently losing notebooks when I attempt to save.

When I take the SAVE AS... menu option I get a new tab open with the same notebook name, and a save dialog that defaults to a TXT file type.

Taking the SAVE action then creates an empty text file, also deleting the original contents of the notebook in memory.

**Comment by chlafreniere** [comment]
@rondunn I can't reproduce your issue at the moment. Are you running our stable (latest is 1.14.1) or insiders build? Can you also share which OS which you're using as well?

**Comment by chlafreniere** [comment]
Cannot repro so closing this issue for now. If you can still reproduce this, please feel free to reactivate.
