### ISSUE TITLE
Entire UI goes blank

### ISSUE THREAD

**Issue by DaveRogala** [microsoft/azuredatastudio#9103]
- Azure Data Studio Version: 1.14.1
- OS Windows 10 Home
- Version 10.0.17134

Entire user interface goes completely black

**Steps to Reproduce:**

- Open Azure Data Studio
- Use it for a little while
- Watch the screen go completely black

Sometimes minimizing and maximizing the window fixes the issue for a bit but it always comes back

**Screenshot**

![Capture](https://user-images.githubusercontent.com/34407302/74110734-00760e00-4b5d-11ea-8fe6-bd5a4bd20a15.PNG)

**Comment by alanrenmsft** [comment]
@DaveRogala  i believe this has been fixed in the Feb release of ADS, please give it a try and reopen the issue if you still see it.

**Comment by uc-msft** [comment]
I still hit this problem in the latest RC1 build. See screenshot.
![blank-ads](https://user-images.githubusercontent.com/10999577/93375728-76d2a100-f80d-11ea-9e7e-c7730141e59a.png)
