### ISSUE TITLE
Editor database drop-down not the proper size

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#9106]
Issue Type: <b>Bug</b>

The drop-down list of databases on an editor window is a third the size of the field itself.

![image](https://user-images.githubusercontent.com/11204251/74176314-0f140200-4bfd-11ea-81fe-6b27809844ae.png)

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (14.67GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (4)</summary>

Extension|Author (truncated)|Version
---|---|---
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.1.0
sql-prompt|Red|0.0.2

</details>

**Comment by Charles-Gagnon** [comment]
@wsmelton This should be fixed with https://github.com/microsoft/azuredatastudio/pull/8716 to never be smaller than the input box width. That'll be included in the next stable release (this week hopefully) - or you can try it out on the current insiders build and let us know if you still see issues!

I'm going to close this for now given that - we can reopen it if you're still seeing issues.

**Comment by wsmelton** [comment]
I'm on the current insiders build.

**Comment by Charles-Gagnon** [comment]
That isn't the insiders version - that's the stable release from before this fix was made.

You can install the insiders builds from here : https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master
