### ISSUE TITLE
Document window icons are incorrect after HotExit

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9113]
- Azure Data Studio Version: `1.15.0`

Steps to Reproduce:

1. Open several untitled SQL documents and modify them
2. Close and Reopen ADS

Expected: Documents are restored with correct icon

Actual: Many of the background SQL text documents have the Plain Text document icon.  When a document is brought to the foreground the correct icon is restored.  See below many background SQL documents have Plain Txt icon in tab bar and Open Editors section of File Explorer viewlet.

<img width="1311" alt="Screen Shot 2020-02-11 at 10 17 12 AM" src="https://user-images.githubusercontent.com/599935/74265867-2237d800-4cb8-11ea-8c93-053966d9bf6b.png">

**Comment by Charles-Gagnon** [comment]
Note : This isn't a regression from previous release and is also an issue in VS Code.

Submitted a bug for this : https://github.com/microsoft/vscode/issues/90486

**Comment by kburtram** [comment]
@Charles-Gagnon I don't think we need this Feb, IMO.  Particularly if we suspect its upstream.

**Comment by kburtram** [comment]
I haven't seen this repro on recent builds.
