### ISSUE TITLE
Untitled documents have different naming convention based on how created

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9115]
- Azure Data Studio Version: `master`
 
Steps to Reproduce:

1. Create an untitled SQL editor using New Query command on node in OE
2. Create an untitled SQL editor using New Query command from File menu

Expected: Both documents follow same naming convention

Actual: One is named `SQLQuery_1` the other is named `Untitled-1`

<img width="512" alt="Screen Shot 2020-02-11 at 10 28 46 AM" src="https://user-images.githubusercontent.com/599935/74271500-dab64980-4cc1-11ea-9bc0-e01322e8f0da.png">

**Comment by aaomidi** [comment]
Approved label added during shiproom meeting.

**Comment by kburtram** [comment]
Fixed
