### ISSUE TITLE
Dev Builds: Unable to write to User Settings because sync.enable is not a registered configuration.

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9119]
When I got the latest from master on my dev machine and launch ADS, I'm met with the following error:

'Unable to write to User Settings because sync.enable is not a registered configuration.'

![image](https://user-images.githubusercontent.com/40371649/74285621-1c072300-4cdb-11ea-866c-ba31a8d21d14.png)

**Comment by chlafreniere** [comment]
Looking at vscode commits, there is at least one commit that changes "sync.enable". @anthonydresser just as FYI master may be sync'ed at an unfortunate spot at the moment 😞

**Comment by anthonydresser** [comment]
I have another vscode merge I'll verify its fix in that and close if it is.

**Comment by anthonydresser** [comment]
Should be fixed
