### ISSUE TITLE
Allow to remove noisy messages Changed database context to %s in Messages windows

### ISSUE THREAD

**Issue by mikedavem** [microsoft/azuredatastudio#912]
**SQL Operations Studio Version:**
0.26.7

**Steps to Reproduce:**
We have a bunch of scripts that use PRINT command either for logging or debug purpose. 
But with SQL Management Operation Studio additional noisy messages appear concerning database context changes. It could be good to remove them in this specific context

MESSAGES
[15:30:39]	Started executing query at Line 1
_**Changed database context to 'DB1'.**_ 
=> Task 1 completed 
_**Changed database context to 'DB2'.**_ 
=> Task 2 completed
_**Total execution time: 00:00:00.018**_

**Comment by alanrenmsft** [comment]
@mikedavem could you please share the script to reproduce the issue?

**Comment by kburtram** [comment]
I don't see messages from switching databases on the current build.  Closing as no repo.  Please let us know if I misunderstand the scenario.  For example, query below...

```
USE master
SELECT 1
USE msdb
SELECT 2
USE model
SELECT 3
```

...outputs messages...

```
1:15:26 PM Started executing query at Line 1
(1 row affected)
(1 row affected)
(1 row affected)
Total execution time: 00:00:00.107
```
