### ISSUE TITLE
Edit Data render the result grid incorrectly when using custom query (Show SQL Pane)

### ISSUE THREAD

**Issue by danielsbarros** [microsoft/azuredatastudio#9145]
- Azure Data Studio Version:
Version: 1.15.0
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:47:11.037Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Darwin x64 19.3.0

Steps to Reproduce:
1 - Connect to SQL Server instance
2 - R-click on a table -> Edit Data
3 - Click Show SQL Pane
4 - Comment or delete some columns from the query
5 - Run

Expected: The grid to show only data from the columns mentioned.
Actual: The header of the grid renders all the columns from the table, but the data respects the query. This way, the data do not correspond to the columns.

Showing default query, with all columns:
![Captura de Tela 2020-02-13 às 22 27 50](https://user-images.githubusercontent.com/1953962/74493205-2dedef00-4eb0-11ea-89b0-968a03a9a8bf.png)

When commenting two columns, the number of columns rendered are incorrect, and the data on incorrect columns.
![Captura de Tela 2020-02-13 às 22 33 10](https://user-images.githubusercontent.com/1953962/74493425-db610280-4eb0-11ea-9587-25a7f1e53b41.png)

**Comment by Charles-Gagnon** [comment]
@smartguest Could you look into this? I verified the issue - although it does look like switching to another tab and back redraws it correctly.

**Comment by Charles-Gagnon** [comment]
Moving into February Recovery milestone for hotfix consideration.
