### ISSUE TITLE
Azure > Sign in to Azure.. > Add Account - [Not Working]

### ISSUE THREAD

**Issue by Git-BT-Hub** [microsoft/azuredatastudio#9147]
- Azure Data Studio Version:

Steps to Reproduce:

1. Click on Azure > Sign in to Azure.. > Add Account
![image](https://user-images.githubusercontent.com/47550225/74503930-33bcf200-4efb-11ea-8e71-c0af23e31502.png)

2. Gets redirected to Local host with below Error
![image](https://user-images.githubusercontent.com/47550225/74503950-46cfc200-4efb-11ea-9e57-bc8ded5f3f8d.png)

Version Info:
--------------
Version: 1.15.0 (user setup)
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:48:43.389Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by jjusiak** [comment]
I got exactly the same problem with the same version info.

**Comment by Charles-Gagnon** [comment]
@aaomidi Can you look into this?

Moving into February Recovery milestone for hotfix consideration

**Comment by kburtram** [comment]
@Git-BT-Hub thanks for reporting this issue!  We have updated the auth mechanism in the Feb release to no longer use Device Code mechanism.  While we troubleshoot this issue could you please try to reenable the Device Code mechanism to see if that helps mitigate the issue.  You can enable the previous auth mechanism with the below setting.

<img width="693" alt="Screen Shot 2020-02-14 at 10 14 52 AM" src="https://user-images.githubusercontent.com/599935/74556620-522ee780-4f13-11ea-8a93-81367d7d8ff5.png">

**Comment by aaomidi** [comment]
@Git-BT-Hub @jjusiak 

Do you by any chance have an extension that is forcing https on localhost? 

That error means you're trying to load localhost with https - which shouldn't happen. Do you regularly do local development on localhost with https enabled? I can see the browser using a previous "upgrade" to https to think this website should also be https.

**Comment by aaomidi** [comment]
A way to mitigate this is:

1. Let your browser load the broken page.
2. Copy the URL from the address bar.
3. Paste it into another browser, remove the `https://` and change it to `http://`.
4. Load that page.

**Comment by aaomidi** [comment]
You can also see if you have HSTS enabled on localhost here:

(Assuming you're using chrome):

```
chrome://net-internals/#hsts
```

Query: `localhost`

It should look like this: 

![image](https://user-images.githubusercontent.com/1465785/74564293-97f3ac00-4f23-11ea-87fb-67449a4512df.png)

**Comment by Git-BT-Hub** [comment]
> You can also see if you have HSTS enabled on localhost here:
> 
> (Assuming you're using chrome):
> 
> ```
> chrome://net-internals/#hsts
> ```
> 
> Query: `localhost`
> 
> It should look like this:
> 
> ![image](https://user-images.githubusercontent.com/1465785/74564293-97f3ac00-4f23-11ea-87fb-67449a4512df.png)

@aaomidi - Thanks for responding
1. I do local dev. regularly , also see the screenshot below from my chrome
![image](https://user-images.githubusercontent.com/47550225/74622314-06fe1a00-5149-11ea-967a-897345ec2cf3.png)
2. If copy paste the broken localhost url into another browser window and use http:// it works..

**Comment by aaomidi** [comment]
I've added the knowledge label to this because it contains information that would be interesting to reference in the future. However since this is a local environment problem, I'm going to close this issue.

The next release will also include device code login for people who have problems using the regular code grant method.

**Comment by rockyfan-up** [comment]
Hi Azure Guru:
I am using MacBook With Apple M1 Pro. I still get same issue. 
Copy URL to another browser and change to http:// does not work for me. 
HSTS query 'localhost' shows a big list.
Any idea on how to resolve the issue?
I also checked, there is no update for my current version of Azure Data Studio.
