### ISSUE TITLE
Show Active Connections

### ISSUE THREAD

**Issue by marcselman** [microsoft/azuredatastudio#9149]
Issue Type: <b>Bug</b>

When I click the small 'Show Active Connections' icon in the Servers overview all my servers disappear from the list.

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6200U CPU @ 2.30GHz (4 x 2400)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.86GB (5.13GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
@marcselman This is fixed in the insiders build but unfortunately didn't make it into the February release. You can use either the previous version of ADS or use the insiders build for the time being.

https://github.com/microsoft/azuredatastudio/pull/9102

Moving this into recovery milestone for consideration of hotfix.

**Comment by kburtram** [comment]
Fixed in master and Feb Hotfix release candidate build.
