### ISSUE TITLE
Unable to download SQL Server Import extension

### ISSUE THREAD

**Issue by jinglish** [microsoft/azuredatastudio#9150]
Issue Type: <b>Bug</b>

1. Click "install" button for the extension

2. Click "download manually" button on the "failed to install 'microsoft.import'" alert

3. Select "open" on the resulting dialog box

4. Your web browser will reach an error page with a message like `BlobNotFoundThe specified blob does not exist. RequestId:46a5297e-301e-000b-3c62-e3f576000000 Time:2020-02-14T18:15:01.3387097Z`

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:47:11.037Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz (8 x 2800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|5, 4, 3|
|Memory (System)|16.00GB (0.75GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
agent|Mic|0.45.0
dacpac|Mic|1.2.0
profiler|Mic|0.11.0

</details>

**Comment by Charles-Gagnon** [comment]
@jinglish Apologies for the inconvenience, I've updated the extension gallery but it'll take a little bit of time for the change to propagate through the caches. 

In the meantime you can download the VSIX manually from here : https://sqlopsextensions.blob.core.windows.net/extensions/import/import-0.13.1.vsix

And then install it via File -> Instal Extension from VSIX Package and select the file downloaded above.
