### ISSUE TITLE
Ensure Spark Session Timeout is 100 Seconds

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9155]
Reports have come back that the spark session creation timeout is still 60 seconds, even though we set the following in our sparkmagic config:

'livy_session_startup_timeout_seconds': 100

**Comment by shanyu** [comment]
I believe it is @Charles-Gagnon 's PR removed the config from configBase in extensions/notebook/src/jupyter/jupyterSessionManager.ts:
https://github.com/microsoft/azuredatastudio/commit/abbb1e54da5ad9f49e9f22eb03b6ee468490503a#diff-5de6eb5a3d545e9854995d40855bad9d

**Comment by Charles-Gagnon** [comment]
Ah, good catch. Thanks @shanyu!
