### ISSUE TITLE
Security/Encryption connection property 

### ISSUE THREAD

**Issue by echatzig** [microsoft/azuredatastudio#9166]
Hello,

tried to connect to an in-premise SQL server which is not using SSL encryption.

So I tried to set the Security|Encrypt "advanced property" in the connection to false. 

I tried first to set it from the UI but the setting is not persisted.
I also tried editing the settings.json file and set the option
"encrypt": false,]

but this didn't work either.

Please advice
![AzureDataStudio](https://user-images.githubusercontent.com/10130688/74606659-f8791980-50da-11ea-8383-f211481af948.png)

**Comment by Charles-Gagnon** [comment]
@echatzig I just put out a PR to fix the persistence issue. But are you seeing any functional issues? I investigated and it seemed like the setting was applied correctly - it was just the UI that wasn't displaying false values if they were specifically selected as false. Plus the default for encrypt is false anyways so setting it specifically to false shouldn't change anything.
