### ISSUE TITLE
When opening a notebook (.ipynb) from the taskbar jump list, the document appears as json

### ISSUE THREAD

**Issue by simonmckenzie** [microsoft/azuredatastudio#9167]
Issue Type: <b>Bug</b>

If I create a notebook using Azure Data Studio, save it, then try to reopen it from the jump list on the taskbar (I have Azure Data Studio pinned to the taskbar), it opens in a "raw" view (JSON):

![view when ipynb loaded from jump list](https://user-images.githubusercontent.com/17579442/74613741-fc517e00-5164-11ea-8f88-32ddee0802c8.png)

If I reopen the file from within the studio, it opens correctly (as a notebook with text and code sections):

![view when reopened from the "File" menu in Azure Data Studio](https://user-images.githubusercontent.com/17579442/74613722-cf9d6680-5164-11ea-8363-7a0ca0d9b9fe.png)

Azure Data Studio version: azuredatastudio 1.14.1 (f9b968c1ae514a0d1210788629e1c69125857279, 2019-12-24T02:42:26.303Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz (8 x 3408)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (6.93GB free)|
|Process Argv|C:\working\Losing conditions when valuations received - COM IQ\Losing conditions when valuations received - COM IQ.ipynb|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-search|Red|0.3.3

</details>

**Comment by chlafreniere** [comment]
We've made improvements in this error. Please feel free to reactivate if you're still seeing these issues.

**Comment by MsSQLGirl** [comment]
@chlafreniere When I set my ADS to be the default program to open ipynb files and I double click on the ipynb file to open it from File Explorer, ADS does not render the notebook (i.e. it stays in json format). 

However, if I open a second ipynb file (by double clicking in File Explorer), the second ipynb file is rendered to notebook in ADS. 

When navigating back to the first ipynb file in ADS, ADS starts opening a new tab with the rendered view of the first ipynb file.

![NotebookRenderingIssue](https://user-images.githubusercontent.com/6405919/79296274-cfcd9000-7e8f-11ea-994b-284a522f2b16.gif)

Note: the error that you see in the gif file occasionally comes up. 
Happy to open this as a separate bug if it makes it easier to track the issue. Thank you!

This is the version that I'm using to repro:
Version: 1.17.0-insider (user setup)
Commit: 15fc4517eeaa551f8f352e0fed54c6044d31f530
Date: 2020-04-13T17:32:48.451Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by MsSQLGirl** [comment]
Tracking as a separate bug instead. https://github.com/microsoft/azuredatastudio/issues/10027
