### ISSUE TITLE
PowerShell broken after update Unable to instantiate; language client undefined.

### ISSUE THREAD

**Issue by martincroft** [microsoft/azuredatastudio#9173]
- Azure Data Studio Version:
Version: 1.16.0-insider (user setup)
Commit: 506c6a5e5f8423d3249670f55b1466b1980a5f03
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.16299

tried on 

Version: 1.14.0 (user setup)
Commit: 27468f75a5c969736ff663140d46f927d3ac749b
Date: 2019-12-18T20:21:08.840Z
VS Code: 1.38.0
Electron: 6.1.5
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

which work fine

Steps to Reproduce:

1. Open existing PowerShell file that ran previously
2. Highlight any valid PowerShell
3 Press F8
4 get Unable to instantiate; language client undefined. Pop up box and open to click logs

17/02/2020 14:38:14 [NORMAL] - Visual Studio Code v1.42.0 64-bit
17/02/2020 14:38:14 [NORMAL] - PowerShell Extension v2020.1.0
17/02/2020 14:38:14 [NORMAL] - Operating System: Windows 64-bit
17/02/2020 14:38:16 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
17/02/2020 14:39:18 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
17/02/2020 14:46:46 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
17/02/2020 14:47:29 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.
17/02/2020 14:49:05 [ERROR] - <ConsoleFeature>: Unable to instantiate; language client undefined.

**Comment by martincroft** [comment]
Works fine on ( so just insiders that its not working for me)

This was after the Powershell extention has been updated to version 2020.1.0! pop up message 

![image](https://user-images.githubusercontent.com/30621653/74664478-ac3edf80-5195-11ea-8cd4-4aa7d0a4ea87.png)


Version: 1.15.0
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:48:43.389Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.16299

**Comment by Charles-Gagnon** [comment]
@anthonydresser - Looks like your changes for the layering broke this : https://github.com/microsoft/azuredatastudio/pull/9111/files#diff-4654cd1aa2a333bc6cc7ca0d19fdfb6eR804

I'm getting this upon installing the extension

![image](https://user-images.githubusercontent.com/28519865/74765940-499f1f80-5239-11ea-99ff-7985a424fb7b.png)

I tested locally and reverting the changes there to return undefined fixes it. Was there a specific reason you had it throw instead of just returning undefined?

**Comment by anthonydresser** [comment]
returning undefined breaking strict undefined checks since those apis are defined as returning a type... we can force undefined...but its not a good long term coding pattern. We should ask the extension owners if they can update their extension to fail check on debug apis... @yualan

**Comment by anthonydresser** [comment]
fixes #9193, will be in tonights insiders.
