### ISSUE TITLE
BDC with AD mode wizard  hasn't implemented the newly introduced  activeDirectory Node under security config.

### ISSUE THREAD

**Issue by rl-msft** [microsoft/azuredatastudio#9179]
ADS hasn’t implemented AD the new security config node activeDirectory,

Control.json generated by AD and see activeDirectory  node is empty and the variables were added under security node directly similar to CU1 

    "security": {
        "activeDirectory": {
            "ouDistinguishedName": "",
            "dnsIpAddresses": [],
            "domainControllerFullyQualifiedDns": [],
            "domainDnsName": "",
            "clusterAdmins": [],
            "clusterUsers": []
        },
        "ouDistinguishedName": "OU=bdc, DC=contoso, DC=com",
        "dnsIpAddresses": [
            "192.168.1.200"
        ],
        "domainControllerFullyQualifiedDns": [
            "DC1.CONTOSO.COM"
        ],
        "domainDnsName": "contoso.com",
        "realm": "CONTOSO.COM",
        "clusterAdmins": [
            "bdcadmins"
        ],
        "clusterUsers": [
            "bdcusers"
        ]
    }

This deployment is failing with this error

Creating SQL Server 2019 Big Data Cluster: mssql-cluster using configuration ads-bdc-custom-profile
If you don't see output produced by azdata, you can run the following command in a terminal window to check the deployment status:
	C:\Users\<user>\AppData\Local\Programs\Python\Python37\kubectl.exe get pods -n mssql-cluster 
Executing: azdata bdc create -c ads-bdc-custom-profile
The privacy statement can be viewed at:
https://go.microsoft.com/fwlink/?LinkId=853010

The license terms for SQL Server Big Data Cluster can be viewed at:
Enterprise: https://go.microsoft.com/fwlink/?linkid=2104292
Standard: https://go.microsoft.com/fwlink/?linkid=2104294
Developer: https://go.microsoft.com/fwlink/?linkid=2104079

Cluster deployment documentation can be viewed at:
https://aka.ms/bdc-deploy

**ERROR: Failed to set security configuration. Please check the deployment documentation https://aka.ms/bdc-deploy . Security configuration parameter 'clusterAdmins' must contain a single domain group. Values specified: 
An exception has occurred, use %tb to see the full traceback.**

SystemExit: Command execution failed with exit code: 1.
	azdata bdc create -c ads-bdc-custom-profile

c:\users\<user>\azuredatastudio-python\0.0.1\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)

ADS version

Version: 1.16.0-insider (user setup)
Commit: 506c6a5e5f8423d3249670f55b1466b1980a5f03
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by alanrenmsft** [comment]
@rl-msft Thanks for reporting the issue, I have fixed it and please try the latest insider build.
