### ISSUE TITLE
Refreshing table list doesn't do anything

### ISSUE THREAD

**Issue by oerpli** [microsoft/azuredatastudio#9184]
Issue Type: <b>Bug</b>

Repro:
- Set up Azure account set up with ADS and some Server/Database/Tables to look at the available tables
- Run some queries on that server to drop several tables
- Press refresh on the table-list-header (right mouse button + refresh)
- Doesn't seem to refresh - dropped tables are still there

Same for created tables or similar stuff. 

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:48:43.389Z)
OS version: Windows_NT x64 10.0.17763

<details><summary>Extensions (2)</summary>

Extension|Author (truncated)|Version
---|---|---
azuredatastudio-postgresql|Mic|0.2.2
datavirtualization|Mic|1.3.0

</details>

**Comment by oerpli** [comment]
According to #8718 it should have been fixed somewhere around December 2019 - I have the current release and the issue doesn't seem to be fixed so far.

**Comment by Charles-Gagnon** [comment]
Thanks for the report @oerpli  - I've confirmed that the Azure viewlet is still not functioning correctly for refresh and will investigate a fix. In the meantime as a workaround you can add the connection to the Servers view and the refresh there should work correctly.
