### ISSUE TITLE
Notebook Markdown Editor Find Doesn't Work as Expected

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#9196]
- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Double click a large markdown cell for editing. 
2: Ctrl+F and enter the text to be searched within the editor
3: It finds the text but the text is not highlighted AND the content does not scroll if the text is beyond the window

**Comment by chlafreniere** [comment]
Discussed this and when the markdown editor is visible, we should search markdown editors too. That's the behavior change for March.
