### ISSUE TITLE
Add Markdown support to Jupyter book with SQL kernel

### ISSUE THREAD

**Issue by AndreyQC** [microsoft/azuredatastudio#9209]
Currently Jupyter book with SQL kernel does not support Markdown

**Comment by chlafreniere** [comment]
Hi @AndreyQC can you elaborate a bit? Markdown ("text") cells should be rendering just fine when using the SQL kernel. Are you referring to cells inside of a notebook or .md files inside of a book? Neither should be associated with the kernel chosen.
