### ISSUE TITLE
Extension API support:  Run a query and get results

### ISSUE THREAD

**Issue by AbbiePetcht** [microsoft/azuredatastudio#921]
It is the main scenario of most extensions. It needs to run query to get some information.

**Comment by AlexFsmn** [comment]
We really need this. Also having extensions that can subscribe to entered queries would be great.

**Comment by kburtram** [comment]
We now have a `QueryEventListener` interface that allows getting events related to query execution.  A pending PR for visualization shows how an extension can access query data.  Please let me know if the API is missing something fundamental.
