### ISSUE TITLE
A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ColorContrast: Color contrast ratio is below 4.5:1 for some text present on the screen.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9211]
[“Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopApp;#Win32;#Benchmark; #A11y_SQLAzureDataStudio;#A11ySev1;#MAS1.4.3;#ColorContrast;

**Environment Details:**
Version: 1.16.0-insider
Commit: 506c6a5
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS reference: MAS1.4.3

**Repro Steps:**
1. Launch Azure Data Studio.
2. Select the Connections icon (if not already selected) from left bar.
3. Hover over the 'Servers' header and select the 'New Connection' icon.
4. Provide server and windows authentication details, then click 'Connect'.
5.Check if minimum color contrast ratio is met for all texts present on the screen.

**Actual:**
The minimum color contrast ratio is not met for the text present on the screen.

**Expected:**
The Color contrast ratio must be =>4.5:1 for the content present in the screen.

**User Impact:**
Low vision users might face difficulty in visualizing what text is present on the screen.

**Attachment link reference:**
[9211_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ColorContrast.zip](https://github.com/microsoft/azuredatastudio/files/4291445/9211_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ColorContrast.zip)
[9211_A11y_SQLAzureDataStudio_ConnectToASQLServer_Servers_ColorContrast.zip](https://github.com/microsoft/azuredatastudio/files/4291453/9211_A11y_SQLAzureDataStudio_ConnectToASQLServer_Servers_ColorContrast.zip)

**Comment by alanrenmsft** [comment]
both issues are vscode issue, please open an issue for vscode repo.

**Comment by Harika1702** [comment]
<img width="857" alt="image" src="https://user-images.githubusercontent.com/100270074/218952036-184f54e6-1748-4500-8a15-f409d774b7cb.png">
<img width="679" alt="image" src="https://user-images.githubusercontent.com/100270074/218952682-2c372b17-d206-4f25-b603-1cb61e11696a.png">
Verified the issue now issue is not repro'ing.
GitHub Tags: #Closed;

**Comment by mstechie** [comment]
GitHubTags:#SQLADS-Win32-Feb2020;
