### ISSUE TITLE
Azure Account doesn't link properly

### ISSUE THREAD

**Issue by eddynaka** [microsoft/azuredatastudio#9216]
Issue Type: <b>Bug</b>

1. Click in Azure menu
2. Sign-in using your azure account
3. After sign-in, it says it failed to get credentials.
4. Add credentials again -> go to step 3.

With that, I can't use Azure credentials to see the databases

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.82GB (18.02GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by aaomidi** [comment]
Could you provide screenshots of these errors. Do they happen when you try to login?

Does the blue screen show up?

Also, you can always go back to the old sign in mechanism to get unblocked as pointed out here: https://github.com/microsoft/azuredatastudio/issues/9147#issuecomment-586408376

**Comment by eddynaka** [comment]
With or without the option in #9147, i still can't use the Azure login part.
Probably something related to my account.
