### ISSUE TITLE
SqlPackage bacpac import not working on linux

### ISSUE THREAD

**Issue by Parasrah** [microsoft/azuredatastudio#9217]
- Azure Data Studio Version:

Version: 1.15.0
Commit: e57eb999fc5f1e000477da8fe0b8679ff0bfd57b
Date: 2020-02-12T20:45:05.264Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Linux x64 5.3.0-7625-generic

(Have attempted on `Ubuntu 18.04 and PopOS 19.10`)

Steps to Reproduce:

1. Install `Admin Pack for SQL Server`
2. Go to `Connections`
3. Add connection for sql server running locally in docker swarm
4. Right click on `databases` and choose `Data Tier Application Wizard`
5. Choose `[Import Bacpac]`
6. Select the `bacpac` file, leaving target server unchanged and a new target database `Testing`
7. Click `Next` and `Import`

**Result**

![image](https://user-images.githubusercontent.com/14935550/74886794-5e151200-5336-11ea-8b9b-f88a37df8cf7.png)

This has been occurring for ~2 months for me, with many different versions of sqlpackage and azure data studio

My workaround for the time being has been to revert to `18.3.1 sqlpackage` which seems to work, albeit warning me about `users that rely on an external authentication provider that is not supported by the target. These users will be treated as users without logins.`

I cannot provide you with any of the contents of the bacpac file unfortunately.

[This](https://stackoverflow.com/questions/59734778/how-to-fix-sqlpackage-failure-to-restore-bacpac-file-to-linux-but-not-windows) might also be related

**Comment by kisantia** [comment]
We had a regression in the sqlpackage 18.4.1 release where there's the error “Object reference not set to an instance of an object.” when importing a bacpac with a user with an external login. This got fixed for importing/deploying to and Azure db in the 1.16 ADS release. For on prem, we are targeting to get the fix in the April release.

**Comment by kisantia** [comment]
first fix didn't work, so now targeting to get this fixed for June release.

**Comment by Parasrah** [comment]
Thanks for the update @kisantia. Would it be possible to get a pre-release version (windows/linux) of `sqlpackage` when it's working? I work for [Nude Solutions](https://www.nudesolutions.com/) and we've been struggling with this for some time now. We'd be happy to help test it out and provide feedback

**Comment by kisantia** [comment]
@Parasrah it would be great if you could try out the fix we have. I send an email to the email address on your github profile.
