### ISSUE TITLE
Notebooks

### ISSUE THREAD

**Issue by donlovett** [microsoft/azuredatastudio#9219]
We have written the needed data into your clipboard because it was too large to send. Please paste.
Issue Type: <b>Performance Issue</b>

I need some help in understanding what is required to have saved Jupyter Books appear in the Saved Books and Unsaved Books pannel.  It is possible that it is obvious to everyone but me but I have not been to find the answer.  When I try and open a notebook the .ipyng files are all greyed out in the file tool.

Azure Data Studio version: azuredatastudio 1.15.0 (e57eb999fc5f1e000477da8fe0b8679ff0bfd57b, 2020-02-12T20:45:05.264Z)
OS version: Linux x64 5.3.0-40-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4600M CPU @ 2.90GHz (4 x 3426)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|0, 0, 0|
|Memory (System)|15.55GB (9.05GB free)|
|Process Argv|--no-sandbox --unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>Process Info</summary>

```
CPU %	Mem MB	   PID	Process
    0	   127	  4829	azuredatastudio main
    0	    32	  4832	   zygote
    0	    96	  4854	   gpu-process
    0	    96	  4961	   shared-process
    0	     0	 14241	     /bin/sh -c /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	     0	 14242	       /bin/ps -ax -o pid=,ppid=,pcpu=,pmem=,command=
    0	   255	 13174	   window (DJL First Notebook-0.ipynb - AzureNotebook - Azure Data Studio)
    0	   127	 13208	     extensionHost
    0	    80	 13251	       /usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/2.0.0-release.46/MicrosoftSqlToolsServiceLayer --log-file /home/don/.config/azuredatastudio/logs/20200219T182815/exthost1/Microsoft.mssql/sqltools.log --tracing-level Critical
    0	    32	 13252	       /usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/2.0.0-release.46/MicrosoftSqlToolsCredentials --log-file /home/don/.config/azuredatastudio/logs/20200219T182815/exthost1/Microsoft.mssql/credentialstore.log --tracing-level Critical
    0	    32	 13253	       /usr/share/azuredatastudio/resources/app/extensions/mssql/sqltoolsservice/Linux/2.0.0-release.46/SqlToolsResourceProviderService --log-file /home/don/.config/azuredatastudio/logs/20200219T182815/exthost1/Microsoft.mssql/resourceprovider.log --tracing-level Critical
    0	    64	 13220	     watcherService
    0	     0	 13795	     /bin/bash
    0	    96	 14203	   window (Issue Reporter)
```

</details>
<details>
<summary>Workspace Info</summary>

```
|  Window (DJL First Notebook-0.ipynb - AzureNotebook - Azure Data Studio)
|    Folder (AzureNotebook): 2 files
|      File types: ipynb(1)
|      Conf files:;
```

</details>
Extensions: none

**Comment by donlovett** [comment]
This reference was helpful https://tsql.tech/the-sql-diagnostic-jupyter-book/

**Comment by chlafreniere** [comment]
Thanks @donlovett. We’re working to improve the first time experience for users not familiar with Jupyter books. If you have any specific questions please feel free to reactivate and we will answer any questions that come up. Thanks!
