### ISSUE TITLE
Test connection feature is required

### ISSUE THREAD

**Issue by saumyasuhagiya** [microsoft/azuredatastudio#9222]
- Azure Data Studio Version: 1.13.1

Steps to Reproduce:

**Comment by kburtram** [comment]
@saumyasuhagiya I assume you mean another button on the Connection Dialog that says something like "Test Connection".  So I understand better, could you please describe the use case vs. just clicking Connect, perhaps setting the Save To combobox to `<None>`?

**Comment by saumyasuhagiya** [comment]
@kburtram Its basically, before we load the DB connection, it should validate if the connection is working or not.

**Comment by cheenamalhotra** [comment]
Tracked by #23419
