### ISSUE TITLE
Find In Files does not highlight result when searching Notebooks

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9238]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open a couple Notebooks and add a few cells in each with the same text
2. Search for this text in File In Files
3. Click on the various results in the Search results

Expected: Each result is highlighted

Actual: Each different Notebook is opened but the specific result text is not highlighted

**Comment by Charles-Gagnon** [comment]
Duplicate of #9196
