### ISSUE TITLE
Peek definition is not read-only and saves edits

### ISSUE THREAD

**Issue by yualan** [microsoft/azuredatastudio#924]
- SQL Operations Studio Version: 0.26.7

Steps to Reproduce:
1. Connect to local SQL Server database
2. Right click a database and create a new query: 'SELECT * FROM dbo.<table_name>' 
3. Right click 'table' and click Peek Definition
4. Type new lines or delete existing lines in the Peek Definition view
5. Close Peek definition, then open peek definition again.

This behavior is mimiced from VSCode. I feel like Peek Definition should not be editable, or at least should not remember any changes made when Peek Definition is reloaded. I was able to reset the Peek Definition view after clearing the reference or exiting SQL Operations Studio.

![image](https://user-images.githubusercontent.com/30873802/37548573-273a53e8-2936-11e8-94a5-0a8a6b71bfa4.png)

**Comment by kburtram** [comment]
The Peek definition behavior comes from upstream and should be fixed there.  Please open this bug in the vscode repo if it is still impacting your experience.  Thanks!
