### ISSUE TITLE
Jupyter Books - Searching experience - Navigating Search results

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9241]
Issue Type: <b>Bug</b>

Currently the search results show the files along with the list of occurrences of the specified search keyword. While it is possible to collapse the occurrences, however when clicking the file name, it does the expand occurrences in the file, rather than opening the file. It takes 3 clicks after the search to open a searched file, then 2 more clicks to open another one. Once the file is found, I don't know where the file is in the context of the Jupyter book viewlet.

This is the default view:
![image](https://user-images.githubusercontent.com/6405919/74970151-b994dd80-53d2-11ea-83e8-9d27370671b7.png)

This is the collapse view: (from here, I would have to choose one of the files first, then choose a metadata to click then it will open)
![image](https://user-images.githubusercontent.com/6405919/74970101-a8e46780-53d2-11ea-9b21-361391c24564.png)

Once I click open one of the files from the search output, when I navigate to the Jupyter Book viewlet, the file is not highlighted. So I don't know where it is.
![image](https://user-images.githubusercontent.com/6405919/74970794-df6eb200-53d3-11ea-8a45-c1bb112a3407.png)

In summary, the challenges are:
1. Navigating to the files seem to involve a few clicks to get there. When there are multiple files (hundreds) found, it becomes information overload to see the output. 
2. Finding location of where the found file within the Jupyter Book viewlet is impossible. It would be great to have Jupyter Book viewlet to highlight the file clicked / found. 

Ideal search experience: OneNote search.
Scenario: searching for a keyword in Jupyter Books and trying to navigate the relevant information and topic related to it. 

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (3.98GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-browser-preview|auc|0.5.9
demo-mode|dre|1.1.0
ssmskeymap|kev|1.1.0
agent|Mic|0.45.0
import|Mic|0.13.1
schema-compare|Mic|1.2.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by chlafreniere** [comment]
Waiting on design feedback. Will move it probably into April milestone once we have a design folks are happy with.

**Comment by MsSQLGirl** [comment]
@chlafreniere .. 

Updating the following based on my tests on ADS Sep 2020 RC: 

> 1. Navigating to the files seem to involve a few clicks to get there. When there are multiple files (hundreds) found, it becomes information overload to see the output.

Update: _We've introduced collapse which means less click now._ 

> 2. Finding location of where the found file within the Jupyter Book viewlet is impossible. It would be great to have Jupyter Book viewlet to highlight the file clicked / found.

Update: _As long as the user search from the Book, when they open the notebook from the Searched Results, the active notebook will be highlighted on the Notebook viewlet._ 

Can you please confirm? 

We may be able to revisit the experience more as we iterate on the search experience.
