### ISSUE TITLE
Jupyter Books - Ability to search rendered view on notebook and highlighting

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9243]
**Steps to Reproduce:**

1. Search for a keyword in Jupyter book, especially where notebooks have heavy markdowns.
2. The results can get very difficult to understand, see below.  
![image](https://user-images.githubusercontent.com/6405919/74975805-80616b00-53dc-11ea-8b46-eafd4cf37b26.png)
3. Clicking on the occurrence doesn't show the searched keyword highlighted on the activated/opened Notebook preview (rendered mode). See the arrows.

It would be great to be able to toggle between search any and search "rendered" view. 

- Azure Data Studio Version: 1.15.1

Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
Thought this issue was a similar one to one of the other issues around search within a notebook. This one actually tracks issues around searching a Jupyter book, which isn't in scope for March. Changing this to the April milestone; we'll use the latest designs to try and improve this experience 😄

**Comment by chlafreniere** [comment]
This will be resolved by #9929.

**Comment by chlafreniere** [comment]
alwaysCollapse will be the default in the livesite workspace for April. We will work on the long-term solution for May.
