### ISSUE TITLE
Ability to favorite / pin files and to display the favorited notebooks in Jupyter Book viewlets

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9245]
**Is your feature request related to a problem? Please describe.**
When working in a large collaborative environment as part of a big team, I'd like to be able to favorite / pin files that I think are important so that I can access information / script more easily. Especially when using Jupyter book, it would be great to surface this favorited / pinned notebooks and/or add a new notebook to the favorites.

**Describe the solution or feature you'd like**
See above.
Also, Microsoft Word has tabs on "Recent Files", "Pinned" and "Shared with me". I think all of these three are very useful for quick file discovery in collaborative environment. 

**Describe alternatives you've considered**
ADS has recent files, but these are not sufficient. 

**Additional context**
n/a

**Comment by chlafreniere** [comment]
This needs design work. When we have that we will move it into a monthly milestone
