### ISSUE TITLE
Jupyter Book - Active (opened) file should be highlighted in the Jupyter Book Viewlet 

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9248]
This scenario happens usually when there are multiple notebooks in Jupyter book. The issue impact increases when there are many linked notebooks (files) and / or the hierarchy is deep. 

- Azure Data Studio Version:
Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Open a notebook (that has a link to another notebook) from Jupyter Book viewlet. 
2. Click on the link to open another notebook. 
3. The (2nd) notebook now is not highlighted in Jupyter Book viewlet.

Another way of reproducing is:
1. Search for a notebook and open it from one of the results. 
2. View the Jupyter Book viewlet, the opened notebook is not highlighted in the viewlet.

**Comment by qifahs** [comment]
Regressed in RC1 build.

**Comment by chlafreniere** [comment]
Tracked by #10780, which has been approved for June.
