### ISSUE TITLE
Notebook - linking to anchors / sections in a notebook

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9250]
- Azure Data Studio Version:
Version: 1.15.1 (user setup)
Commit: 83544eba2504f564d785534cc780d2073feec2cc
Date: 2020-02-15T05:03:16.545Z
VS Code: 1.42.0
Electron: 6.1.6
Chrome: 76.0.3809.146
Node.js: 12.4.0
V8: 7.6.303.31-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create an anchor with <a id> value first.
2. Create a link to the anchor.
3. In ADS, clicking on the link opens workbench.html file instead of going to the relevant anchored area.

 Example:
~~~
[this link should work](#icecream)


... put lots of <br> here to make it obvious if the link "jumps" to the expected section ... 


<a id='icecream'></a>ICE CREAM!
~~~

**Comment by MsSQLGirl** [comment]
It looks like a similar issue has been reported here: #8428

**Comment by chlafreniere** [comment]
Yeah let’s track this with #8428. I added the impact live site label to that issue.
