### ISSUE TITLE
Support for WYSIWYG editing for markdown in Notebooks

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9251]
**Is your feature request related to a problem? Please describe.**
Ability to easily highlight text, to make font bold / italics / strike-through and to upload images should be made easy. It'd be great if we don't have to remember too markdown

**Describe the solution or feature you'd like**
Similar to Wordpress or equivalent.. e.g.
![image](https://user-images.githubusercontent.com/6405919/74999002-3645ad00-540f-11ea-99bb-bc711f8f024b.png)

or GitHub, eg.
![image](https://user-images.githubusercontent.com/6405919/74999026-507f8b00-540f-11ea-9cb2-8091f775e95a.png)

**Describe alternatives you've considered**
Markdown and complex HTML :(

**Additional context**
n/a

**Comment by chlafreniere** [comment]
One of the DIs will be working on this task soon.

**Comment by chlafreniere** [comment]
This won't make March so moving out to April.

**Comment by chlafreniere** [comment]
Reopening for triage into release branch.
