### ISSUE TITLE
Open tab for query while waiting for results

### ISSUE THREAD

**Issue by mkotb** [microsoft/azuredatastudio#9252]
When I perform an action like "Select Top 1000" on a table, I'm stuck waiting for a decent amount of time (a couple of seconds) for the tab to open, then a little bit more (half a second) for the results to open. When I first did this, I thought the app was bugging out since there was no indication that it was doing any work.

It would be nice if ADS would open the tab with the query immediately and have an indication that it is in process until the results appear. This way, as a user, I could know that something is actually happening instead of it bugging out.

**Comment by kburtram** [comment]
@mkotb thanks for logging this issue.  It looks a little similar to what's reported here https://github.com/microsoft/azuredatastudio/issues/8513.  We plan to improve the flow in this scenario in a subsequent release to reduce the initial delay showing the query editor.

**Comment by kburtram** [comment]
@mkotb thanks for reporting this issue.  We're tracking this bug with https://github.com/microsoft/azuredatastudio/issues/8513 and fix is planned for March release

**Comment by gregveres** [comment]
@kburtram You guys are still missing the point of this request and my request that is identical. This is not a performance problem. This is a UI problem. You should open the query window immediately - before you ever build a query to send to the server to get the shape of the ultimate query. 

I just updated to the april release and I can tell that you guys did some great performance work on executing the query and building the query. But there is still a 1-2 second delay between the time that I select "Select Top 1000" and the time that the new tab opens. Once that new tab opens, it fills really fast (which is a welcome change), but it is that initial time of waiting for that new tab to open. 

From a code point of view it should be something like this:

queryTopN() {
  open tab with spinner 
  build query and put query into tab query window
  open tab results window and put spinner in it
  send query to the server
  fill results in the results window
}

Notice that the UI feedback is always done before the query is set to the server. I think that is what you guys are missing in all of this work. We understand that queries take a long time to communicate with the server and execute, but the user shouldn't be waiting for UI feedback during that time.

**Comment by gregveres** [comment]
I think this is more a dup of [#8926](https://github.com/microsoft/azuredatastudio/issues/8926) rather than #8513.
