### ISSUE TITLE
A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader: Unnecessary Hidden content read by screen reader.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9256]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS; #A11yTCS; #SQL Azure Data Studio; #DesktopApp; #Win32; #MAS1.3.1; #Benchmark; #A11y_SQLAzureDataStudioBenchmark; #A11ySev2; #NVDA;

**Environment Details:**
Version: 1.16.0-insider
Commit: 506c6a5
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
Screen Reader: NVDA(2019.3.1)
MAS reference: MAS1.3.1

**Repro Steps:**
1. Launch Azure Data Studio.
2. From the left menu, click the 'Extensions' icon to open the Extension Manager.
3. Choose any extension from the library.
4. Click the green 'Install' button to install.
5. Launch NVDA screen reader and navigate to the content present below 'Admin pack for SQL Server' heading.
5. Check if hidden content is read by screen reader.

**Actual:**
Hidden content present on the screen is read by screen reader(NVDA).

**Expected:**
Hidden content present on the screen should not be read by screen reader.

**User Impact:**
Users might get confused as the content that is not present on the screen is read by screen reader.

**Attachment link reference:**
[9256_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4297877/9256_A11y_SQLAzureDataStudio_Extension_Install-UninstallExtension_ScreenReader.zip)

**Comment by alanrenmsft** [comment]
this is a vscode issue, please open an issue for them.

**Comment by Harika1702** [comment]
<img width="331" alt="image" src="https://user-images.githubusercontent.com/100270074/217809441-1fed8d8c-41fa-4ed0-96cb-09a162316970.png">
As remove the unused widgets from the environment. Hence closing the bug.
GitHub Tags: #Closed;

**Comment by mstechie** [comment]
GitHubTags:#SQLADS-Win32-Feb2020;
