### ISSUE TITLE
not able to open the new job dialog

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9270]
with latest master code, i am not able to launch the new job dialog from the dashboard agent tab. no error or warning in the console. i am using Mac.

IIRC, @aaomidi,  you are making changes in this area. could u please take a look?

**Comment by alanrenmsft** [comment]
repro'ed also on Windows.

**Comment by aaomidi** [comment]
Don't think I've made any changes here recently just looked at it. Will assign the area owner.
