### ISSUE TITLE
Notebook: Find doesn't highlight the searched text in a text cell

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9275]
- Azure Data Studio Version: 1.5.1

Steps to Reproduce:

1. Create a new notebook with just one text cell (with lots of text).
2. Use Ctrl + F to find word.
3. Click down arrow button on the dialog. The highlight doesn't show properly.
Added: **Text Cell in editable mode should also be included as part of the search**. #9196

**Comment by chlafreniere** [comment]
@MsSQLGirl please share a notebook and search query if you can.

**Comment by MsSQLGirl** [comment]
Keywords to find: "SQL" and "waldo".
"SQL" highlights the wrong area when it's in a table. 
"Waldo" highlights the wrong area when it's after a numbered list.
[FindHighlightIssue.zip](https://github.com/microsoft/azuredatastudio/files/4248464/FindHighlightIssue.zip)

**Comment by MsSQLGirl** [comment]
This is also related to #9196 ..

**Comment by MsSQLGirl** [comment]
@chlafreniere 

By the way, it is possible for users to write the following:
`the\_waldo\_search`

The preview will look like "the_waldo_search", e.g.
![image](https://user-images.githubusercontent.com/6405919/75393511-14cb4200-58a3-11ea-91c8-e2bbab9fe02c.png)


It looks like the_waldo_search is not going to come up although the rendered view shows the_waldo_search.

**Comment by chlafreniere** [comment]
This particular issue should be taken care of by #9419.
