### ISSUE TITLE
Unable to Change Kernel to Python 3

### ISSUE THREAD

**Issue by marknhenry** [microsoft/azuredatastudio#9284]
Issue Type: <b>Bug</b>

Worked through all the steps on docs, and looked at submitted/solved bugs.  Still get the Internal Server Error 500.  

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (7eef23f2321a8f95220c974209561593f802d918, 2020-02-20T05:49:05.139Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.84GB (6.68GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.3.0

</details>

**Comment by chlafreniere** [comment]
Are you doing this with a new notebook, or opening from an existing notebook?

If you open the Output Window (View -> Output) and change the channel to Notebooks, can you paste what's there?
