### ISSUE TITLE
Adding color for different environments

### ISSUE THREAD

**Issue by twinbitz** [Microsoft/azuredatastudio#93]
- SQL Operations Studio Version: Preview

I love that we can have different themes within the app.  What I would love is to be able to have server specific changes like, have the background change color or the cursor foreground change depending on my environment, Production red, Accpt yellow, test green.  Having the ability to set server specific color changes would be great and useful for people that have the production environment not locked down like it should and the dev is on the hook if things break.  
Thanks for this app it is great.

**Comment by anthonydresser** [comment]
We implemented something like this using the ` "sql.tabColorMode"` option which color codes your query tabs with the color of your groups. Is this sufficient for what you are asking for?

**Comment by twinbitz** [comment]
Yes that works great actually.

Get Outlook for Android

________________________________
