### ISSUE TITLE
A11y_SQLAzureDataStudio_SchemaCompare_SchemaCompareOptions_Keyboard: Keyboard focus is not shifted to the latest popped up window on the screen. 

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9301]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”
#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopApp;#Win32;#MAS2.4.3;#Keyboard; #Benchmark;#A11y_SQLAzureDataStudioBenchmark;#A11ySev2;

**Environment Details:**
Version: 1.16.0-insider
Commit: 506c6a5e5f8423d3249670f55b1466b1980a5f03
Date: 2020-02-17T05:43:18.399Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Additional Details:**
MAS reference: MAS2.4.3

**Repro Steps:**
1. Launch Azure Data Studio application.
2. Connect to server with windows credentials.
3. Navigate to Extensions from left menu.
4. Search & install Schema Compare extension.
5. Navigate to Connections from left menu.
6. Expand the server connected in step 2.
7. Right click an on prem database and select Schema compare from Context menu.
8. Navigate till Select Source or Select Target & hit enter.
9. Provide all the details for Source & Target.
10. Navigate till Ok button & hit enter.
11. Navigate till Options menu from Schema compare Menu bar.
12. After hitting enter, check if focus order is proper.

**Actual:**
The focus is not shifted to the new window that pop ups on the screen after hitting enter on the options menu.

**Expected:**
As soon as any new window pop ups which contains any interactive element inside it the focus should shift inside that new screen.

**User Impact:**
Keyboard as well as screen reader users will get confused as the focus remains on the previous screen and not shifted to the latest screen that is visible to us.

**Attachment link reference:**
[9301_A11y_SQLAzureDataStudio_SchemaCompare_SchemaCompareOptions_Keyboard.zip](https://github.com/microsoft/azuredatastudio/files/4291419/9301_A11y_SQLAzureDataStudio_SchemaCompare_SchemaCompareOptions_Keyboard.zip)

**Comment by alanrenmsft** [comment]
the new window should gain focus.

**Comment by kisantia** [comment]
Dup of #9409

**Comment by Harika1702** [comment]
https://user-images.githubusercontent.com/100270074/217802104-84c70821-82c2-4690-86f8-e3b07989e077.mp4

Verified this issue in the below environmnet.
App Name: Azure data studio.
Version: 1.41.1 (user setup)
Commit: 33dce95b152227c4f10f6251ab30690fe9895c0c
Date: 2023-01-28T00:46:39.274Z
VS Code: 1.67.0
Electron: 19.1.8
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.22623
GitHub Tags:#Closed;

**Comment by mstechie** [comment]
GitHubTags:#SQLADS-Win32-Feb2020;
