### ISSUE TITLE
Error: "Your azuredatastudio installation appears to be corrupt. Please reinstall."

### ISSUE THREAD

**Issue by mrlife** [microsoft/azuredatastudio#9302]
Any idea what causes this error I received? 

> Your azuredatastudio installation appears to be corrupt. Please reinstall.

- Azure Data Studio Version: 1.15.0

Steps to Reproduce:

1. Open Azure Data Studio
2. Try to connect to a database

**Comment by kburtram** [comment]
@mrlife I haven't ever this this particular error message before.  Have you tried uninstalling\reinstalling?  If I was guessing something may have went wrong installing the application files (e.g. corrupt files on disk, etc.), but not enough info yet to make a credible assessment.

**Comment by mrlife** [comment]
@kburtram I was in the middle of using it, so not quite sure, but it may have been trying to update itself, since after downloading the latest version via a browser and installing, looks like the version is now 1.15.1.

**Comment by kburtram** [comment]
@mrlife thanks for the additional details.  Could you please confirm the Operating System you're using?  On macOS there is a background auto-updated that could possibly interfere with open files.  On Windows we download an MSI that the user needs to initiate (using Next buttons) before it will update any files.

**Comment by mrlife** [comment]
Thank you. Yes, this is on macOS.

**Comment by OliverPearmain** [comment]
I'm seeing the same issue.  I think its just tried to auto updated itself to v1.20.0.  Pretty annoying as I'm right in the middle of something important and having to reinstall is pretty inconvenient.  I'm running Catalina FYI.

**Comment by kburtram** [comment]
Closing this older issue.  The mac updater comes from Electron so we don't really provide any of that implementation.  You can set the Update settings to manual to prevent the auto-updated from running a background update when you aren't expecting it.
