### ISSUE TITLE
[Insiders] Paste is adding line break

### ISSUE THREAD

**Issue by wsmelton** [microsoft/azuredatastudio#9316]
- Azure Data Studio Version:
```
Version: 1.16.0-insider (system setup)
Commit: 7eef23f2321a8f95220c974209561593f802d918
Date: 2020-02-20T05:49:05.139Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362
```

Steps to Reproduce:

1. Open a new editor
1. Paste the following code: `s.whatever = 'somevalue'`
1. See a linebreak is being added

![ads_paste_issue](https://user-images.githubusercontent.com/11204251/75207162-93a66a80-573d-11ea-9ed9-35395f235e0c.gif)

**Comment by Charles-Gagnon** [comment]
@wsmelton I can't seem to repro this - could you attach (or e-mail me) the full script from the above repro to see if it's something specific with that?

Does the line break get added every time you paste? Or just for specific selections?

**Comment by wsmelton** [comment]
Didn't matter what code. The sample I added in the steps does the same thing.

**Comment by aaomidi** [comment]
![w7b8JclI4j](https://user-images.githubusercontent.com/1465785/78624741-396dee80-783f-11ea-9893-3de5d268eb67.gif)

Also unable to repro this

**Comment by aaomidi** [comment]
I'm going to close this issue for now as @Charles-Gagnon and I haven't been able to repro it. If this happens again please feel free to comment back on this issue.
