### ISSUE TITLE
notebookEditorVisible Context Key Isn't Defined

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9318]
Somewhere down the road, the notebookEditorVisible context key was deleted. Please investigate and ensure that the commands defined in the notebook extension's package.json show up in the command palette as expected.

**Comment by MaddyDev** [comment]
I see activeEditor == workbench.editor.notebookEditor being checked for the same commands on tochbar. Shouldn't we be using the same instead of context key, which once set shows the commands on unrelated editors?
