### ISSUE TITLE
Tab colors change to match the first tab's color when dragging/reordering tabs

### ISSUE THREAD

**Issue by AisoRed** [microsoft/azuredatastudio#9329]
**Azure Data Studio Version:**
- Version: 1.15.1 (user setup)
- Commit: 83544eba2504f564d785534cc780d2073feec2cc
- Date: 2020-02-15T05:03:16.545Z
- VS Code: 1.42.0
- Electron: 6.1.6
- Chrome: 76.0.3809.146
- Node.js: 12.4.0
- V8: 7.6.303.31-electron.0
- OS: Windows_NT x64 10.0.17134

**Steps to Reproduce:**
1. Set "Sql: Tab Color Mode" to "fill" in the Settings.
2. Create two or more server groups with different colors.
3. Open a new connection to each server in new tabs. 
   - Each tab should be filled with the server groups associated color.
      ![tabcolor1](https://i.imgur.com/p4xZiSc.png)
4. Drag one of the tabs to reorder it in the window.
   - The tab that is being dragged changes color to match the color of the first tab in the window. Any tab that you hover over while dragging is changed to that color also.
      ![tabcolor2](https://i.imgur.com/43QsL3a.png)

**Comment by guillaume86** [comment]
Tangentially related, a note about tab colors and server groups:

Currently this is not reliable at all (changing connection not changing color, selecting connection from recent do not give color, etc). 
In my opinion this is a critical feature, it prevents users like me doing very damaging stuff, maybe we need a way to enforce it? With an optional setting of course.

That setting would enforce a tab MUST have a color (or server group if you prefer) and if the color is not found a confirmation message should be displayed before running a query.

**Comment by anthonydresser** [comment]
Do the tab colors get restored once you are done dragging?

**Comment by AisoRed** [comment]
The tab colors remain changed when you finish dragging. You actually need to click into each tab to get its color reset to the original color.

**Comment by anthonydresser** [comment]
This seems to be fixed in insiders, so should be fixed in the next release. I'll track down where this fix came from for verification.

**Comment by anthonydresser** [comment]
Looks like this was fixed in 1d0f76d26a45d60c54419f659a23382cbd16af46 which is a happy accident, but intentional.

**Comment by AisoRed** [comment]
Thanks for looking into this!
