### ISSUE TITLE
open tab immediately on query request

### ISSUE THREAD

**Issue by gregveres** [microsoft/azuredatastudio#9335]
Issue Type: <b>Feature Request</b>

When I right click on a table in the servers list and select "Select Top 1000" or "Edit Data", please open a window immediately.

I believe what is happening behind the scenes is that once I click on one of those options, ADS needs to query the server to find the columns of the table. While this query is happening (can be a couple of seconds with a remote server), no tab is opened. In fact, ADS just sits there as if nothing was happening. I have to guess that it did take my command. 

I would like to see a tab opened immediately and where the query text should be, there should be a spinner. This spinner should spin until the query string is available to be displayed. Then the spinner can be replaced with the query string. 

Without this change, the product is just super frustrating to use with a remote server. Please don't say this is a performance problem because there are always going to be situations where the latency from my machine to the server is long enough that some sort of spinner is needed. Give me some indication that something is happening. If I see that something is happening, the my blood pressure will go down and I will just be happy waiting for it to finish. 

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

**Comment by anthonydresser** [comment]
dupe #8926
