### ISSUE TITLE
SSMS Key Mapping Extension Author

### ISSUE THREAD

**Issue by JASM2007** [microsoft/azuredatastudio#9356]
Shouldn't this extension say it's from Microsoft and not Kevin? Again not taking away credit from Kevin just optics.

- Azure Data Studio Version: Latest and Greatest

![image](https://user-images.githubusercontent.com/40634806/75390883-1b63b480-58b7-11ea-9d8a-97d307bc18c9.png)

**Comment by kburtram** [comment]
@alanrenmsft this is a non-Microsoft extension that Kevin published under his personal account.  In order to be published by Microsoft we'd want to revisit the scenario a bit.  I'll close as "By Design."
