### ISSUE TITLE
azdata.connection.listDatabases fails if user does not have access to master db

### ISSUE THREAD

**Issue by kisantia** [microsoft/azuredatastudio#9361]
- Azure Data Studio Version: 1.16.0

azdata.connection.listDatabases fails if user does not have access to master db. Same issue as in #9187.
Steps to Reproduce:

1. Create a contained database
2. Create a user on the contained database
3. Connect to db
4. Launch flat file import wizard 
5. Databases dropdown doesn't load

![image](https://user-images.githubusercontent.com/31145923/75404776-69c98100-58c0-11ea-9c0a-c396db52dbd0.png)

![image](https://user-images.githubusercontent.com/31145923/75404721-3edf2d00-58c0-11ea-9101-40d308714c35.png)

**Comment by kisantia** [comment]
@aasimkhan30 the PR #10216 only made changes in the import extension. Can azdata.connection.listDatabases be fixed to not fail when the user does not have access to master db? Other extensions besides the import extension use this api, like the dacpac extension. Right now, the dacpac extension has been modified to catch this in #9362, but it would be nice if azdata.connection.listDatabases got fixed so that each extension wouldn't have to handle the error.

**Comment by aasimkhan30** [comment]
It makes more sense. I'll look into it on the SQL Tool service end to fix the issue.
