### ISSUE TITLE
Links to Markdown headers not working

### ISSUE THREAD

**Issue by pacorreia** [microsoft/azuredatastudio#9369]
Issue Type: <b>Bug</b>

When working with Jupyter notebooks, I tried to have links to headers in same cell or other cells, and it opens some HTML code instead of going to the header

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz (12 x 2592)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.79GB (3.73GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (19)</summary>

Extension|Author (truncated)|Version
---|---|---
newdatabase|kev|1.0.0
mssql-db-insights|mat|0.2.2
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
azuredatastudio-postgresql|Mic|0.2.3
cms|Mic|0.7.0
dacpac|Mic|1.2.0
datavirtualization|Mic|1.3.0
import|Mic|0.13.1
powershell|ms-|2020.1.0
profiler|Mic|0.11.0
query-history|Mic|0.1.0
schema-compare|Mic|1.2.0
server-report|Mic|0.2.1
sql-dw|Mic|0.0.1
azdata-sanddance|msr|1.3.9
sqlops-spexecutesql-to-sql|pej|1.0.1
vscodeintellicode|Vis|1.2.1

</details>

**Comment by chlafreniere** [comment]
We've vastly improved this with #9513. The html page definitely shouldn't show up any longer.

Fix is in insiders, and will make it into our upcoming March release.

**Comment by pacorreia** [comment]
This is great, looking forward to see it and other improvements on markdown
support

A sexta, 13 de mar de 2020, 21:02, Chris LaFreniere <
notifications@github.com> escreveu:
