### ISSUE TITLE
Getting user properties from OE shows an error message

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#9370]
- Azure Data Studio Version:
1.16.0 not seeing the properties menu item  in 1.15.1
Steps to Reproduce:

1. In  User select a user and right click
2. Select properties

Expected: display the properties 
Actual: seeing this error:
Error calling SsmsMin with args '-a "sqla:Properties@ Microsoft.SqlServer.Management.Smo.Login" -S "[server ip],1433" -u "Server/Login[@Name='[my user]']"' - The system cannot find the path specified.

**Comment by Charles-Gagnon** [comment]
Do you have the extension installed in 1.15.1?

And if you're running the command from an insiders build this is a known issue - #6276. I'm closing this assuming that's the problem - if this seems to be some other problem reopen and add any further details.
