### ISSUE TITLE
Kqlmagic command doesn't work if Notebook is not in saved state

### ISSUE THREAD

**Issue by gupta1** [microsoft/azuredatastudio#9378]
- Azure Data Studio Version:

Steps to Reproduce:

1. Open a new notebook and add Kqlmagic package to python kernel.
2. Add a code cell and run this command "%reload_ext Kqlmagic".
3. The above command will throw error.
4. Save the notebook and it will work.

**Comment by MsSQLGirl** [comment]
The error says:
“PermissionError: [WinError 5] Access is denied: 'c:\\Users\\Kqlmagic_temp_files'”

**Comment by chlafreniere** [comment]
Given that kqlmagic isn't shipping by default in April (and the other high pri issues already in that milestone), moving this out.

**Comment by chlafreniere** [comment]
Can move this into a milestone when this work is planned.

**Comment by MsSQLGirl** [comment]
I can't seem to repro this anymore. Perhaps we can close it? 
@gupta1 - thoughts?
