### ISSUE TITLE
ADS always prompts for SQL connection on startup

### ISSUE THREAD

**Issue by lerchdude** [microsoft/azuredatastudio#9380]
Issue Type: <b>Bug</b>

# Repro:
1. Have fresh install or clear all connections and queries.
2. Open ADS
# Actual:
ADS prompts to connect to SQL Server.
![image](https://user-images.githubusercontent.com/9547098/75501017-8c709e00-5983-11ea-89c0-00d93ab87e92.png)

# Expected:
Don't prompt. Since I may be using ADS for its notebooks feature and do not have a SQL Server.

# Info
Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (d6b5d3c6b1c717a02e791175417b5d31c5b017b3, 2020-02-27T18:07:15.223Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz (48 x 2295)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|159.90GB (37.26GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by lerchdude** [comment]
Also happens when I open a notebook from an already running ADS window.

**Comment by chlafreniere** [comment]
@Charles-Gagnon do we have a bug tracking this already?

**Comment by Charles-Gagnon** [comment]
I thought we did but I couldn't find anything. I think mostly we've just talked about removing this functionality a lot but never actually followed through with creating a bug for it.

**Comment by kburtram** [comment]
This is the current "By Design" behavior.  If the user saves a connection then the dialog won't be displayed.  Any changes here should be part of a larger 1st-Launch redesign.

**Comment by kburtram** [comment]
The Connection Dialog is no longer shown on startup.  Thanks!
