### ISSUE TITLE
New Deployment not working

### ISSUE THREAD

**Issue by Loai-Alhalabi** [microsoft/azuredatastudio#9389]
Issue Type: <b>Bug</b>

New Deployment button not working, no any action trigger for this.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (2.58GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (3)</summary>

Extension|Author (truncated)|Version
---|---|---
datavirtualization|Mic|1.3.0
powershell|ms-|2020.1.0
azdata-sanddance|msr|1.3.9

</details>

**Comment by Charles-Gagnon** [comment]
@Loai-Alhalabi If you open the Developer console (Help menu -> Toggle Developer Tools) and go to the Console tab are there any errors displayed there after clicking the button?
