### ISSUE TITLE
Test coverage improvement

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9391]
- [x] produce the test coverage result for extension unit tests - done by Charles

- [ ] upload the results to the drop folder so that the area owner can easily check their code coverage rate (in progress)
- [ ] merge the coverage results in to one to utilize the pipeline's code coverage results viewer
there is a limitation in the ADO pipeline, only one result file is accepted.
https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-code-coverage-results?view=azure-devops

- [ ] leverage coveralls

- [ ] enable test coverage for integration tests

**Comment by kburtram** [comment]
Closing older engineering issues.  Please reactive if you're still using this to track this work.
