### ISSUE TITLE
Sometimes it crashes when executing statements

### ISSUE THREAD

**Issue by gaocheng1986** [microsoft/azuredatastudio#9403]
Issue Type: <b>Bug</b>

Unable to open '': Cannot read property 'length' of null.

Azure Data Studio version: azuredatastudio-insiders 1.16.0-insider (d6b5d3c6b1c717a02e791175417b5d31c5b017b3, 2020-02-27T18:07:15.223Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8565U CPU @ 1.80GHz (8 x 1992)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.77GB (7.94GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by gaocheng1986** [comment]
Sometimes queries are slow to execute

**Comment by abist** [comment]
@gaocheng1986 Thanks for opening this issue. Could you open Developer Tools (Help -> Toggle Developer Tools or `Ctrl/Cmd + Shift + I` and open the Console and see if it has any errors there? If there are, could you please paste any errors here so we can investigate it?

**Comment by kburtram** [comment]
Closing older issues without concrete repro steps.  We are tracking several query editor reliability and performance bugs so hopefully some of those will address this issue.  Please let us know if you're still impacted by this issue and have additional repro steps that may be helpful in determining the underlying issue.
