### ISSUE TITLE
A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader: Hidden content is read by screen reader.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9407]
[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

GitHubTags:#A11y_SQLAzureDataStudioBenchmark;#A11yMAS;#A11ySev2;#A11yTCS;#SQL Azure Data Studio;#Benchmark; #DesktopApp;#VoiceOver;#MacOs;#MAS1.3.1;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

**Additional Details:**
Mac OS:10.15.3
MAS References:MAS1.3.1
Screen reader: VoiceOver

**Repro Steps:**
1.Launch Azure Data Studio.
2.Select the Connections icon (if not already selected) from left bar.
3.Hover over the 'Servers' header and select the 'New Connection' icon.
4.Navigate till Advanced button under Connection details & hit enter.
5.Launch Narrator desktop app.
6.Check if hidden content is read by screen reader.

**Actual:**
After hitting Advanced button present on Connection details screen "Advanced Properties" screen is opened.
On "Advanced properties" screen on pressing shift+tab hidden content is being read by Voice Over.

**Expected:**
Hidden content on the screen should not be read by screen reader.

**User Impact:**
Users might get confused as the hidden content is read which is not present visually.

Attachment link reference:
[9407_A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4291316/9407_A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader.zip)

**Comment by alanrenmsft** [comment]
The issue described here will be fixed if we set the focus to the newly opened dialog.

another issue i noticed, I am not able to get to all the text/dropdown controls using tab navigation on the advanced settings dialog.

**Comment by Charles-Gagnon** [comment]
This was fixed in a previous PR - the issue here was the focus wasn't being set correctly on open so it was escaping the dialog.

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-SQLADS-MAC-Feb2020;
