### ISSUE TITLE
Existing SQL Notebooks do not open correctly and cannot be executed.

### ISSUE THREAD

**Issue by michaelplumb** [microsoft/azuredatastudio#9412]
Issue Type: <b>Bug</b>

On upgrading to version 1.15.1 my existing SQL Notebooks do not open correctly. They seem to open in python where there is no kernel dropdown to change to SQL.

Steps:
open EXPLORER.
open an existing SQL Notebook. 
There is no kernel drop-down box. SQL code does not execute.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.16299

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.82GB (3.57GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
tsqlchecker|Dan|0.0.1
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
import|Mic|0.13.1
powershell|ms-|2020.1.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
python|ms-|2019.10.41019
azdata-sanddance|msr|1.3.9
poor-sql-formatter|WSR|0.1.0

</details>

**Comment by chlafreniere** [comment]
@michaelplumb this isn't good. Can you share a notebook where this issue reproduces on your machine? I tried some test notebooks and wasn't able to see the same behavior.

When you say that there isn't a kernel dropdown, does the dropdown not show up in the toolbar, or does the dropdown say "No Kernel"?

**Comment by michaelplumb** [comment]
What I expect to see in the menu tab is Code, Text then Kernel etc
What I get is Refresh Symbol, red Square box, Plus Sign, double right arrow etc and it looks like 
the sql code is being executed in python.
Sorry, Could not seem to attach a word doc.

**Comment by chlafreniere** [comment]
This is due to the Python extension being installed; the Python extension overwrites ADS' ability to open notebooks.

The toolbar looks like this, right?

![image](https://user-images.githubusercontent.com/40371649/75813269-880e0180-5d44-11ea-96c9-4f46c03d838c.png)

**Comment by chlafreniere** [comment]
If so, please go to the Settings in ADS, and uncheck the following option, if you would like the ADS notebooks experience:
![image](https://user-images.githubusercontent.com/40371649/75813465-e0450380-5d44-11ea-9aa9-bf61b9ebfd3d.png)

**Comment by michaelplumb** [comment]
The toolbar did look like above. I have changed the ADS setting to unchecked. 
New notbooks opens up in the editor but any saved ipynb files open with just JSON.
If I right click and select 'Open in Notebook editor' I get the Toolbar as above.

**Comment by michaelplumb** [comment]
This can be closed. I removed my installation of Python and Azure Data Studio and then did a re-install of ADS by itself and it now works.
