### ISSUE TITLE
Jupyter code cell results 'caching'

### ISSUE THREAD

**Issue by trminalator** [microsoft/azuredatastudio#9413]
- Azure Data Studio Version: 1.15.1

Steps to Reproduce:

.Jupyter notebook
kernel = powershell
Attach To: = localhost (SQL2017 dev Ed on Windows )

The last query ran in a code cell appears to be cached, as the next code cell when run shows the results of the previous code cell. On running the code cell twice the correct result is observed.

**Comment by chlafreniere** [comment]
@trminalator which version of the powershell kernel are you running?

You can hit the Manage Packages button on the notebook toolbar, and scroll down to powershell-kernel. The latest is 0.1.3.

If you don't have the latest, go to the "Add New" tab (can also be used for upgrading packages), search for "powershell-kernel", and ensure that 0.1.3 is selected in the Package Version dropdown.

**Comment by trminalator** [comment]
@chlafreniere have updated that to 0.1.3 as advised. Restarted ADS an i can confirm the issues still exists.

**Comment by chlafreniere** [comment]
Thanks. Let's track this with #9138 then.
