### ISSUE TITLE
Can not connect to DB file window

### ISSUE THREAD

**Issue by kwenzel1** [microsoft/azuredatastudio#9416]
Issue Type: <b>Bug</b>

IF I open a SQL file from my GIT repo, I can not connect to the database.  However, If I create a new file I can then use the Connect command from the tool bar to connect.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (8 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.86GB (1.96GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
sql-dw|Mic|0.0.1

</details>

**Comment by kwenzel1** [comment]
Forgot to attach the log.

[renderer1.log](https://github.com/microsoft/azuredatastudio/files/4278169/renderer1.log)

**Comment by aaomidi** [comment]
I've been unable to repro this. Do you have a screen recording of this happening? Are you able to repro this consistently?
