### ISSUE TITLE
Unable to Open Notebook in Azure Data Studio "*.ipynb extension"

### ISSUE THREAD

**Issue by Devinder-pal-singh** [microsoft/azuredatastudio#9422]
Issue Type: <b>Bug</b>

I am trying to open *.ipynb notebook file in Azure Data Studio but it throws an error "Could not display contents: This file does not have a valid notebook format"

File Downloaded from Source: 

https://github.com/microsoft/sql-server-samples/tree/master/samples/features/in-memory-database/memory-optimized-tempdb-metadata

If you explore the below link, look for 7 min video and they opened the same notebook.

https://docs.microsoft.com/en-us/sql/relational-databases/databases/tempdb-database?view=sqlallproducts-allversions#memory-optimized-tempdb-metadata

I am on latest version for the Azure Data Studio as well.

Please suggest.

Regards
Devinder

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7600U CPU @ 2.80GHz (4 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.88GB (16.32GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by chlafreniere** [comment]
Hmm, I can't repro this issue. I went to both of the notebooks, clicked "Raw", and copied the file contents into a new file on disk. Was able to open both notebooks on both Mac and on PC.

GitHub doesn't like attaching .ipynb files, so I've just changed the file extension to .txt here. If you change it back to .ipynb, can you open these files?

[tempdbpython.txt](https://github.com/microsoft/azuredatastudio/files/4283118/tempdbpython.txt)
[tempdbsql.txt](https://github.com/microsoft/azuredatastudio/files/4283120/tempdbsql.txt)

**Comment by Devinder-pal-singh** [comment]
I download the txt files and changed the extension back to ipynb and tried opening the python files first with ADS and it started working on installing dependencies like python and other libraries. Pasting the o/p for the reference. Both the notebooks are opening now.

Notebook dependencies installation is in progress
Downloading python package (0 / 146.09 MB)
Downloading python package (14.61 / 146.09 MB)
Downloading python package (29.22 / 146.09 MB)
Downloading python package (43.83 / 146.09 MB)
Downloading python package (58.45 / 146.09 MB)
Downloading python package (73.05 / 146.09 MB)
Downloading python package (87.65 / 146.09 MB)
Downloading python package (102.26 / 146.09 MB)
Downloading python package (116.87 / 146.09 MB)
Downloading python package (131.48 / 146.09 MB)
Downloading python package (146.09 / 146.09 MB)
Unpacking python package
Python download is complete
Installing required packages to run Notebooks...
    > "C:\Users\des\azuredatastudio-python\0.0.1\python.exe" -m pip install --no-index -r "C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt" --find-links "C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages" --no-warn-script-location
    stdout: Looking in links: c:\Users\des\azuredatastudio-python\0.0.1\offlinePackages
    stdout: 
    stdout: Requirement already satisfied: pip in c:\users\des\azuredatastudio-python\0.0.1\lib\site-packages (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 1)) (19.2.3)
    stdout: 
    stdout: Collecting pandas>=0.24.2 (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: 
    stdout: Collecting jupyter>=1.0.0 (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting prose-codeaccelerator>=1.3.0 (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting sparkmagic>=0.12.9 (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting powershell-kernel>=0.1.2 (from -r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 6))
    stdout: 
    stdout: Collecting pytz>=2017.2 (from pandas>=0.24.2->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting python-dateutil>=2.6.1 (from pandas>=0.24.2->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting numpy>=1.13.3 (from pandas>=0.24.2->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting jupyter-console (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting notebook (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting ipywidgets (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting ipykernel (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting nbconvert (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting qtconsole (from jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting regex>=2017.7.28 (from prose-codeaccelerator>=1.3.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting protobuf>=3.8.0 (from prose-codeaccelerator>=1.3.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting dotnetcore2>=2.1.8 (from prose-codeaccelerator>=1.3.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting hdijupyterutils>=0.6 (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting autovizwidget>=0.6 (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting ipython>=4.0.2 (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting nose (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting mock (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting requests (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting tornado>=4 (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting requests_kerberos>=0.8.0 (from sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting six>=1.5 (from python-dateutil>=2.6.1->pandas>=0.24.2->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 2))
    stdout: 
    stdout: Collecting pygments (from jupyter-console->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting prompt-toolkit<2.1.0,>=2.0.0 (from jupyter-console->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jupyter-client (from jupyter-console->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting Send2Trash (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jinja2 (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting traitlets>=4.2.1 (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting terminado>=0.8.1 (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pyzmq>=17 (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting prometheus-client (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting nbformat (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting ipython-genutils (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jupyter-core>=4.6.0 (from notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting widgetsnbextension~=3.5.0 (from ipywidgets->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pandocfilters>=1.4.1 (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting bleach (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting entrypoints>=0.2.2 (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting mistune<2,>=0.8.1 (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting defusedxml (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting testpath (from nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Requirement already satisfied: setuptools in c:\users\des\azuredatastudio-python\0.0.1\lib\site-packages (from protobuf>=3.8.0->prose-codeaccelerator>=1.3.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4)) (39.0.1)
    stdout: 
    stdout: Collecting distro>=1.2.0 (from dotnetcore2>=2.1.8->prose-codeaccelerator>=1.3.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 4))
    stdout: 
    stdout: Collecting plotly>=3 (from autovizwidget>=0.6->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting decorator (from ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting backcall (from ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting jedi>=0.10 (from ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting pickleshare (from ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting colorama; sys_platform == "win32" (from ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 (from requests->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting certifi>=2017.4.17 (from requests->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting idna<2.9,>=2.5 (from requests->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting chardet<3.1.0,>=3.0.2 (from requests->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: 
    stdout: Collecting winkerberos>=0.5.0; sys_platform == "win32" (from requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting cryptography>=1.3; python_version != "3.3" (from requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting wcwidth (from prompt-toolkit<2.1.0,>=2.0.0->jupyter-console->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pywin32>=1.0; sys_platform == "win32" (from jupyter-client->jupyter-console->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting MarkupSafe>=0.23 (from jinja2->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pywinpty>=0.5; os_name == "nt" (from terminado>=0.8.1->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting jsonschema!=2.5.0,>=2.4 (from nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting webencodings (from bleach->nbconvert->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: 
    stdout: Collecting retrying>=1.3.3 (from plotly>=3->autovizwidget>=0.6->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting parso>=0.5.0 (from jedi>=0.10->ipython>=4.0.2->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting cffi!=1.11.3,>=1.8 (from cryptography>=1.3; python_version != "3.3"->requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting pyrsistent>=0.14.0 (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting attrs>=17.4.0 (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting importlib-metadata (from jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting pycparser (from cffi!=1.11.3,>=1.8->cryptography>=1.3; python_version != "3.3"->requests_kerberos>=0.8.0->sparkmagic>=0.12.9->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 5))
    stdout: 
    stdout: Collecting zipp>=0.5 (from importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Collecting more-itertools (from zipp>=0.5->importlib-metadata->jsonschema!=2.5.0,>=2.4->nbformat->notebook->jupyter>=1.0.0->-r C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages\requirements.txt (line 3))
    stdout: 
    stdout: Installing collected packages: pytz, six, python-dateutil, numpy, pandas, pygments, decorator, backcall, ipython-genutils, traitlets, parso, jedi, wcwidth, prompt-toolkit, pickleshare, colorama, ipython, tornado, pywin32, jupyter-core, pyzmq, jupyter-client, ipykernel, jupyter-console, Send2Trash, MarkupSafe, jinja2, pywinpty, terminado, prometheus-client, pyrsistent, attrs, more-itertools, zipp, importlib-metadata, jsonschema, nbformat, pandocfilters, webencodings, bleach, entrypoints, mistune, defusedxml, testpath, nbconvert, notebook, widgetsnbextension, ipywidgets, qtconsole, jupyter, regex, protobuf, distro, dotnetcore2, prose-codeaccelerator, nose, mock, hdijupyterutils, retrying, plotly, autovizwidget, urllib3, certifi, idna, chardet, requests, winkerberos, pycparser, cffi, cryptography, requests-kerberos, sparkmagic, powershell-kernel
    stdout: 
    stdout:   Running setup.py install for backcall: started
    stdout: 
    stdout:     Running setup.py install for backcall: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for prometheus-client: started
    stdout: 
    stdout:     Running setup.py install for prometheus-client: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pyrsistent: started
    stdout: 
    stdout:     Running setup.py install for pyrsistent: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pandocfilters: started
    stdout: 
    stdout:     Running setup.py install for pandocfilters: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for hdijupyterutils: started
    stdout: 
    stdout:     Running setup.py install for hdijupyterutils: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for retrying: started
    stdout: 
    stdout:     Running setup.py install for retrying: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for autovizwidget: started
    stdout: 
    stdout:     Running setup.py install for autovizwidget: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for pycparser: started
    stdout: 
    stdout: 
    stdout:     Running setup.py install for pycparser: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for sparkmagic: started
    stdout: 
    stdout:     Running setup.py install for sparkmagic: finished with status 'done'
    stdout: 
    stdout:   Running setup.py install for powershell-kernel: started
    stdout: 
    stdout: 
    stdout:     Running setup.py install for powershell-kernel: finished with status 'done'
    stdout: 
    stdout: Successfully installed MarkupSafe-1.1.1 Send2Trash-1.5.0 attrs-19.3.0 autovizwidget-0.13.1 backcall-0.1.0 bleach-3.1.0 certifi-2019.9.11 cffi-1.13.2 chardet-3.0.4 colorama-0.4.1 cryptography-2.8 decorator-4.4.1 defusedxml-0.6.0 distro-1.4.0 dotnetcore2-2.1.10 entrypoints-0.3 hdijupyterutils-0.13.1 idna-2.8 importlib-metadata-0.23 ipykernel-5.1.3 ipython-7.9.0 ipython-genutils-0.2.0 ipywidgets-7.5.1 jedi-0.15.1 jinja2-2.10.3 jsonschema-3.1.1 jupyter-1.0.0 jupyter-client-5.3.4 jupyter-console-6.0.0 jupyter-core-4.6.1 mistune-0.8.4 mock-3.0.5 more-itertools-7.2.0 nbconvert-5.6.1 nbformat-4.4.0 nose-1.3.7 notebook-6.0.2 numpy-1.17.3 pandas-0.25.3 pandocfilters-1.4.2 parso-0.5.1 pickleshare-0.7.5 plotly-4.2.1 powershell-kernel-0.1.2 prometheus-client-0.7.1 prompt-toolkit-2.0.10 prose-codeaccelerator-1.7.0 protobuf-3.10.0 pycparser-2.19 pygments-2.4.2 pyrsistent-0.15.5 python-dateutil-2.8.1 pytz-2019.3 pywin32-225 pywinpty-0.5.5 pyzmq-18.1.0 qtconsole-4.5.5 regex-2019.11.1 requests-2.22.0 requests-kerberos-0.12.0 retrying-1.3.3 six-1.13.0 sparkmagic-0.13.1 terminado-0.8.2 testpath-0.4.4 tornado-6.0.3 traitlets-4.3.3 urllib3-1.25.6 wcwidth-0.1.7 webencodings-0.5.1 widgetsnbextension-3.5.1 winkerberos-0.7.0 zipp-0.6.0
    stdout: 
    > "C:\Users\des\azuredatastudio-python\0.0.1\python.exe" -m pip install --force-reinstall --no-index pip --find-links "C:\Users\des\azuredatastudio-python\0.0.1\offlinePackages" --no-warn-script-location
    stdout: Looking in links: c:\Users\des\azuredatastudio-python\0.0.1\offlinePackages
    stdout: 
    stdout: Collecting pip
    stdout: 
    stdout: Installing collected packages: pip
    stdout: 
    stdout:   Found existing installation: pip 19.2.3
    stdout: 
    stdout: 
    stdout:     Uninstalling pip-19.2.3:
    stdout: 
    stdout:       Successfully uninstalled pip-19.2.3
    stdout: 
    stdout: Successfully installed pip-19.3.1
    stdout: 
... Jupyter installation complete.
Notebook dependencies installation is complete
... Creating C:\Users\des\AppData\Roaming\jupyter\instances\e826c1f9-b4ed-42fc-a75b-9941adca8266
... Creating C:\Users\des\AppData\Roaming\jupyter\instances\e826c1f9-b4ed-42fc-a75b-9941adca8266\config
... Creating C:\Users\des\AppData\Roaming\jupyter\instances\e826c1f9-b4ed-42fc-a75b-9941adca8266\data
... Creating C:\Users\des\AppData\Roaming\jupyter\instances\e826c1f9-b4ed-42fc-a75b-9941adca8266\config\custom
... Creating C:\Users\des\AppData\Roaming\jupyter\kernels
... Starting Notebook server
    > "C:\Users\des\azuredatastudio-python\0.0.1\python.exe" -m jupyter notebook --no-browser --no-mathjax --notebook-dir "c:\Users\des" --port=9720 --NotebookApp.token=8ea6aa62a29c311965ae317a26576c6870f65e3394ef68bc
... Jupyter is running at http://localhost:9720/?token%3D8ea6aa62a29c311965ae317a26576c6870f65e3394ef68bc

**Comment by chlafreniere** [comment]
Thanks, glad that the notebooks are opening now. Closing the issue for not being to open notebooks.
