### ISSUE TITLE
Intellisense fails

### ISSUE THREAD

**Issue by chomelchizo** [microsoft/azuredatastudio#9424]
Issue Type: <b>Bug</b>

Frequently, intellisense disappears for tables, columns, etc.

Refreshing the intellisense cache does not correct the situation. The only thing that helps is restarting Azure Data Studio.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:01:39.777Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (2.85GB free)|
|Process Argv||
|Screen Reader|no|
|VM|15%|
</details>Extensions: none

**Comment by cnshenj** [comment]
This happens way too often.

**Comment by shaneholder** [comment]
Agreed still happens in 1.25.3.  SSMS has the same issues, Intellisense just stops working.

**Comment by jumiguelga** [comment]
Hi guys, to add to this issue, In my case, sometimes IntelliSense doesn't show to me all fields' names on a table. It'll better if you can resolve this issue includes that we don't need to refresh the cache. Thanks!

**Comment by kburtram** [comment]
We've made numerous improvements to intellisense since this bug was last updated, including several connect reliability bugs.  Please let us know if you're still impacted by this bug.
