### ISSUE TITLE
Big Data Clusters - HDFS file recognition

### ISSUE THREAD

**Issue by rajmera3** [microsoft/azuredatastudio#9430]
- Azure Data Studio Version: Latest Version
In Azure Data Studio, while using a Big Data Cluster, if you use Spark to write a CSV or Parquet file to HDFS, in the file tree, ADS does not recognize it as a file, but rather a directory with several partitions. Because of this, it shows incorrect right-click options such as the ability to add new folder underneath, while things like "Preview" are not available.

Steps to Reproduce:

1. Using Spark, write a CSV or Parquet file to HDFS. 
2. Look at HDFS in the file tree and see bug.

Images of Bug Below:

![image](https://user-images.githubusercontent.com/22081978/75822393-be537d00-5d54-11ea-90dc-819ca284777c.png)
![image](https://user-images.githubusercontent.com/22081978/75822690-37eb6b00-5d55-11ea-9f2d-c82c0d2fce59.png)

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
