### ISSUE TITLE
Unable to remove a connected Azure Account

### ISSUE THREAD

**Issue by PedroMiguelFigueiredo** [microsoft/azuredatastudio#9435]
Issue Type: <b>Bug</b>

How can I remove a connected Azure Account?

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.87GB (1.52GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
If you mouse over the account there's an x you can click to remove the account.

![image](https://user-images.githubusercontent.com/28519865/75898058-68cbae80-5dee-11ea-9dba-97fe717ebc84.png)

**Comment by PedroMiguelFigueiredo** [comment]
![2020-03-05_09-57-56](https://user-images.githubusercontent.com/6414408/75970394-2bd3ea80-5ec8-11ea-888a-785913da5daa.png)

More information: it happens when the account is asking for new credential (changed password). In this case the "X" to delete the account is not visible.

**Comment by Charles-Gagnon** [comment]
Ah, thanks @PedroMiguelFigueiredo - there was an issue I found with long names hiding the delete action. I have a PR out to fix that now so it should be out in insiders soon.

In the meantime if you really want to get rid of it you can delete %APPDATA%\azuredatastudio\User\globalStorage. **WARNING** This will delete a number of other settings too. Unfortunately there's no other way to just delete the accounts currently.

**Comment by Charles-Gagnon** [comment]
@PedroMiguelFigueiredo This fix is out in the latest insiders build if you wanted to test it out

**Comment by kburtram** [comment]
The fix is ported to release/1.16
