### ISSUE TITLE
Release notes have incorrect dates

### ISSUE THREAD

**Issue by devendra2108** [microsoft/azuredatastudio#9447]
- Azure Data Studio Version:

Steps to Reproduce:

1.Connect to release notes URL for Azure Data Studio and you would notice dates are 2019 should instead be 2020 as attached

![image](https://user-images.githubusercontent.com/20104284/75966328-947c9080-5ee3-11ea-9a60-e726db7fa3b6.png)

**Comment by devendra2108** [comment]
> 
> 
> Thanks for submitting this issue. Please also check if it is already covered by an existing one, like:
> 
>     * [Update release notes link (#9191)](https://www.github.com/microsoft/azuredatastudio/issues/9191)
> 
>     * [Release Notes notification should have an option to "Do not show again" (#8623)](https://www.github.com/microsoft/azuredatastudio/issues/8623)

**Comment by devendra2108** [comment]
Accidently closed it :)

**Comment by Charles-Gagnon** [comment]
Thanks for the report @devendra2108, this should be fixed now!
