### ISSUE TITLE
A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader: Wrong data announced by voice over for wrong label.

### ISSUE THREAD

**Issue by v-atkulk** [microsoft/azuredatastudio#9448]
“[Check out Accessibility Insights!](https://accessibilityinsights.io/) - Identify accessibility bugs before check-in and make bug fixing faster and easier.”

#A11yMAS;#A11yTCS;#SQL Azure Data Studio;#DesktopApp;#MacOs;#Benchmark;#A11y_SQLAzureDataStudioBenchmark;#A11ySev2;#MAS1.3.1;

**Environment Details:**
Application Name: Azure Data Studio
Version: 1.15.0-insider
Commit: 3a8b74a
Date: 2020-02-11T05:49:41.181Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 19.3.0
Mac OS:10.15.3

**Additional Details:**
Screen reader: Voice Over
MAS reference: MAS1.3.1

**Repro Steps:**
1.Launch Azure Data Studio.
2.Select the Connections icon (if not already selected) from left bar.
3.Hover over the 'Servers' header and select the 'New Connection' icon.
4.Navigate till Advanced button under Connection details & hit enter.
5.Under Advanced Properties check if proper announcements are made by screen reader.

Actual:
"30 unselected" is announced for "Current Language" label under initialization drop down.

**Expected:**
"30 unselected" should not be announced by voice over screen reader as it is irrelative data  assigned to the "current language" label.

**User Impact:**
Screen reader users will get confused as wrong data is being announced for the wrong label.

**Attachment link reference:**
[9448_A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader.zip](https://github.com/microsoft/azuredatastudio/files/4296554/9448_A11y_SQLAzureDataStudio_ConnectToASQLServer_AdvancedProperties_ScreenReader.zip)

**Comment by alanrenmsft** [comment]
this is a voice over behavior, we can't really do much here. we are using standard html input tags.

**Comment by Raghu-addepalli** [comment]
https://user-images.githubusercontent.com/91586743/218715239-e4f5e30d-8cab-412e-b7f7-c663f230573e.mov

Verified the bug issue is fixed.

Git Hub Tags: #Closed;

**Comment by mstechie** [comment]
GitHubTags:#BM-TCS-SQLADS-MAC-Feb2020;
