### ISSUE TITLE
Provide a way to override default icon in a custom tab

### ISSUE THREAD

**Issue by santiaago** [microsoft/azuredatastudio#948]
Provide a way to override default icon in a custom tab for **SQL Operations Studio** extensions.

The simplest way would be to use the favicon provided by the document served in the extension.

That is usualy defined in the head of the tab document

```html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>My SQL Ops Studio extension</title>
  <link rel="shortcut icon" href="%PUBLIC_URL%/favicon.ico">
  ...
```

This is probably a limitation on how vscode icons work:

From @anthonydresser :

> @santiaago @kburtram from my experience in the past with vscode icons, it is a all or nothing sort of deal. A icon theme has to specify all icons to use, any not specified will just be blank.

**Comment by anthonydresser** [comment]
To clarify the issue you are referring the the icon for query windows, correct?

![image](https://user-images.githubusercontent.com/4324725/37728419-6e09f80e-2cf7-11e8-8a80-6099c8d31a26.png)

**Comment by santiaago** [comment]
@anthonydresser I am referring to the icon next to an extension window

<img width="886" alt="screen shot 2018-03-22 at 09 05 46" src="https://user-images.githubusercontent.com/825563/37761111-a6ff33ae-2db0-11e8-91d4-c86165d6abc6.png">

**Comment by anthonydresser** [comment]
Is this an extension window created by `vscode.commands.executeCommand('vscode.previewHtml')` or what other method?

**Comment by santiaago** [comment]
This extension uses `vscode.TextDocumentContentProvider`

```ts
vscode.workspace.registerTextDocumentContentProvider(scheme, new MyContentProvider())
```

This is the same [technique as vscode-arduino](https://github.com/Microsoft/vscode-arduino/blob/master/src/arduino/arduinoContentProvider.ts#L56).

In general  there are many ways people can build extensions for **SQL Operations Studio**.

For extensions that are shown as a tab, giving the ability to override the `favicon/tab icon` allows for differentiation and it helps user find what they want faster.

**Comment by anthonydresser** [comment]
This sounds like it may be an upstream issue for vscode to solve since it is across all extensions, both vscode and sqlops, and is really just a downside of how they have built the icon extensibility in. @kburtram thoughts

**Comment by alanrenmsft** [comment]
upstream issue.
