### ISSUE TITLE
Restore database from BAK failing when launch from Dashboard

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9480]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Try to restore (i.e. create) a database from the Server dashboard

Note: this is a Linux SQL 2017 docker image with no existing DBs trying to restore AdventureWorks sample BAK

Actual: Error below

<img width="1394" alt="Screen Shot 2020-03-06 at 11 31 16 AM" src="https://user-images.githubusercontent.com/599935/76116532-02d25900-5f9f-11ea-9e32-19eee6aa1160.png">

**Comment by udeeshagautam** [comment]
@kburtram I will take a look on this one, can you please check if you close the connections (there is a checkbox on second tab of restore dialog) does this still happen?

**Comment by udeeshagautam** [comment]
@kburtram  I was able to repro this with multiple restore calls - but it worked when I did the close connection check (its not most visible setting - so we work with UX to fix that) but can you please check if this fixes the issue

![image](https://user-images.githubusercontent.com/46980425/76359240-17348f80-62d8-11ea-9c9a-ed2ebafaf8a9.png)

**Comment by udeeshagautam** [comment]
Quick update
Tried to repro - I am able to get these three error related to connection if i dont chekc the checkbox.
- Couldn’t get exclusive connection
- Already opened associated data reader 
- If I change the database then “Collection was modified enumeration operation cannot execute”

But not able to get to the restore closing other connection yet. Will sync offline.

**Comment by kburtram** [comment]
I couldn't repro when using a clean docker image.  I'll close this out for now since we couldn't root cause the issue in the one particular environment.  We can investigate further if we see again.
