### ISSUE TITLE
External wizard requires two clicks to uncheck a table

### ISSUE THREAD

**Issue by mrdenny** [microsoft/azuredatastudio#9493]
Issue Type: <b>Bug</b>

When you use the external table wizard you need to check the check box twice to uncheck an object.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.93GB (1.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (13)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
datavirtualization|Mic|1.3.0
import|Mic|0.13.1
managed-instance-dashboard|Mic|0.3.9
powershell|ms-|2020.1.0
profiler|Mic|0.11.0
server-report|Mic|0.2.1
whoisactive|Mic|0.1.3
azdata-sanddance|msr|1.3.9
plan-explorer|Sen|0.9.6

</details>

**Comment by chlafreniere** [comment]
@Charles-Gagnon can you take a look at this one?

**Comment by Charles-Gagnon** [comment]
@mrdenny I'm going to close since I can't repro this on the current stable or insiders builds. Let me know if you're still seeing this issue!

![Capture](https://user-images.githubusercontent.com/28519865/78194495-2bc8fb00-7432-11ea-95a8-34b34c1ab5db.gif)
