### ISSUE TITLE
XML links don't open formatted properly

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9509]
- Azure Data Studio Version: `1.16.0`

Steps to Reproduce:

1. Run a query with an XML link
2. Click the link

Expected: XML document is formatted

Actual: XML document is not formatted

Note: This is a regression from 1.15.1

<img width="1260" alt="Screen Shot 2020-03-09 at 1 08 21 PM" src="https://user-images.githubusercontent.com/599935/76253094-3fa08900-6207-11ea-9416-2cfa2b8e9e18.png">

**Comment by kburtram** [comment]
@anthonydresser I recall when we last looked at a similar issue it was a race condition in loading the XML extension, or something like that.  I thought the fix we discussed at the time was to preload the XML extension on startup.  Could you please take a look at what happened here since 1.15.1?

**Comment by aaomidi** [comment]
Approved label added during shiproom.

**Comment by kburtram** [comment]
Fixed
