### ISSUE TITLE
March 2020 Endgame

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9511]
# March 2020 - Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.16

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

## Extensions Testing

Install the latest build of ADS from the link above.

### Windows

- Open `product.json` on %LOCALAPPDATA%\Programs\Azure Data Studio\resources\app\
- Change the `extensionsGallery` URL to `https://sqlopsextensions.blob.core.windows.net/marketplace/v1/extensionsGallery-test.json`

### macOS and Linux
Please use the VSIX files to install the latest extensions. 
build for macOS are signed and notarized, we can't change its content.
#### VSIX Files

Extension | Changed in this Release?
-- | --
Admin Pack |  | No
Admin Tool Extension for Windows | No
[Agent][Agent] | No
[CMS][CMS]  | Yes
[Dacpac][Dacpac] | Yes
[Import][Import] | Yes
Profiler | No
[Schema Compare][Schema-Compare] | Yes
[PostgreSQL][PostgreSQL] | Yes
Query History | No
Data Virtualization | No

## Scenario Sign Off

- [x] Edit Data @smartguest 
- [x] ADS Shell @kburtram 
- [x] Query Editor @anthonydresser 
- [x] Notebooks  @chlafreniere 
- [x] Livesite tooling @qifahs 
    - Found some issues which have been postponed to the April release.
- [x] Data Virtualization @corivera 
- [x] Acquisition @kburtram 
- [x] Connection @Charles-Gagnon 
- [x] Language Service @Charles-Gagnon 
- [x] SSMS Integration @Charles-Gagnon 
- [x] Query History @Charles-Gagnon 
- [x] Big Data Cluster @Charles-Gagnon 
- [x] Charting and Insights @alanrenmsft 
- [x] Dashboard @alanrenmsft  
- [x] Backup/Restore @udeeshagautam 
- [x] File Import @kenvanhyning / @aaomidi
- [x] DacFx Deployment @kisantia 
- [x] SQL Agent @abist 
- [x] SQL Profiler @alanrenmsft 
- [x] Spark Job Submission @chlafreniere 
- [x] CMS @abist 
- [x] Extension Manager @alanrenmsft 
- [x] Schema Compare @kisantia / @udeeshagautam 
- [x] Azure Integration @aaomidi
- [x] Resource Deployment @alanrenmsft 
- [x] Books @MaddyDev 
- [x] Data Explorer @abist 
  1. Incorrect ordering for connection viewlet https://github.com/microsoft/azuredatastudio/issues/9588

## Partner Signoffs
- [x] PGSQL @akamath46297 
- [x] SQL On Demand @BranislavGrbicMDCS 

[win-user]: https://go.microsoft.com/fwlink/?linkid=2121609
[win-system]: https://go.microsoft.com/fwlink/?linkid=2121612
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2121511
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2121611
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2121510
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2121613
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2121610
[Agent]: https://sqlopsextensions.blob.core.windows.net/extensions/agent/agent-0.46.0.vsix
[CMS]: https://sqlopsextensions.blob.core.windows.net/extensions/cms/cms-0.8.0.vsix
[Dacpac]: https://sqlopsextensions.blob.core.windows.net/extensions/dacpac/dacpac-1.3.0.vsix
[Import]: https://sqlopsextensions.blob.core.windows.net/extensions/import/import-0.14.0.vsix
[Schema-Compare]: https://sqlopsextensions.blob.core.windows.net/extensions/schema-compare/schema-compare-1.3.0.vsix
[PostgreSQL]: https://sqlopsextensions.blob.core.windows.net/extensions/postgresql/azuredatastudio-postgresql-0.2.4.vsix

**Comment by chlafreniere** [comment]
Notebooks testing in progress.
