### ISSUE TITLE
Change Actionbar actions to trigger on KEY_DOWN instead of KEY_UP

### ISSUE THREAD

**Issue by corivera** [microsoft/azuredatastudio#9515]
When using keyboard navigation, I've run into an issue where a dialog opened from the actionbar will be immediately reopened after hitting the Close button with the Enter key. This seems to be caused by Actionbar items being triggered on KEY_UP, while the Close button is triggered on KEY_DOWN. So as soon as you lift off the Enter key, the open dialog action gets run again.

**Comment by kburtram** [comment]
Closing older engineering-focused bugs.  Please open an issue for the customer-facing scenario that is impacted by this API behavior.
