### ISSUE TITLE
Use "Server Group" colors in "Recent Connections" pane

### ISSUE THREAD

**Issue by winzig** [microsoft/azuredatastudio#9517]
**Is your feature request related to a problem? Please describe.**

I often have to work with the "Recent Connections" pane due to bug #8867. I have quite a few recent connections and it's difficult to quickly select the right one, especially differentiating between our different environments (e.g. staging vs production).

**Describe the solution or feature you'd like**

The "Saved Connections" pane organizes saved connections by Server Group, which we've defined with specific colors (e.g. red=Production, green=Staging). It would be helpful if the "Recent Connections" pane could do the same kind of display. (I would also like both panes to keep the groups expanded or closed, i.e. remembering how I left them, either expanded or not.)

Our recent connections pane currently looks like this:

<img width="307" alt="Screen Shot 2020-03-09 at 5 35 40 PM" src="https://user-images.githubusercontent.com/127062/76268777-67eeae80-622c-11ea-8855-d5baa27ee973.png">

Contrast that with the "Saved Connections" panel:

<img width="311" alt="Screen Shot 2020-03-09 at 5 33 23 PM" src="https://user-images.githubusercontent.com/127062/76268689-16deba80-622c-11ea-91d8-625503937278.png">

**Describe alternatives you've considered**

An alternative approach could be to add a colored/labeled badge in front of each connection row, which would allow the recent connections pane to continue sorting by most-recently used. Right now we've resorted to naming our server connections with `(prod)` and `(staging)` to try and provide us more context, but I personally have a hard time parsing the list quickly without color. 

Ideally we would end in a place where adding `(environment)` after each server connection name would not be required at all, and could be inferred from the server group name/color.

**Comment by kburtram** [comment]
We've redesigned the UX for the Recent Connections since this issue was opened.  Please let us know if you have any suggestions on the current UX.  Thanks!
