### ISSUE TITLE
Don't hide the chart tab on subsequent re-runs of a query.

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#952]
Re-issue from #35 

When you rerun a query the results view is re-rendered, which un-renders the query tab. The suggestion here is to keep the tab to make it easy to make small adjustments to a query and see the results.

The problem here is there will be implementation pains based on the current implementation method, and may require a redesign of the chart system in the results view.

**Comment by kburtram** [comment]
Closing some older issues.
