### ISSUE TITLE
Connect using Azure Active Directory - Integrated

### ISSUE THREAD

**Issue by dbajonm** [microsoft/azuredatastudio#9523]
Issue Type: <b>Feature Request</b>

I'm unable to connect to my Azure Sql Databases using Azure Active Directory - Integrated. I can do this from SSMS.  I hope that this is a future enhancement as it is how I connect.  Curiously, when connecting from my home computer to my work ASD, AAD-MFA works. However, within my company firewall, AAD-MFA does not work and I need to use AAD-Integrated. I'm trying to move from SSMS to ADS but this is preventing the move.
Thanks!
-jon
P.S. server subfolders would be a useful addition as well.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.17763

**Comment by kburtram** [comment]
@aaomidi do have context on this authentication method?

**Comment by aaomidi** [comment]
From my understanding this auth method isn't supported by .NET Core and is out of scope for the time being.

https://github.com/AzureAD/azure-activedirectory-library-for-dotnet/issues/482

**Comment by dbajonm** [comment]
Okay. That makes sense.  I’ll start playing with Data Studio more when Active Directory – Integrated becomes available.  I like the tool so thank you for your hard work!

Jonathon Moorman
One Call -- Data Architect
O: 904-646-0199, 51103
M: 904-445-1176
