### ISSUE TITLE
AKS deployment for Big Data Cluster fails

### ISSUE THREAD

**Issue by bweissman** [microsoft/azuredatastudio#9527]
the deployment of a Big Data Cluster on a new AKS fails on some machines. I have modified the deployment script on the BDC github here: https://github.com/microsoft/sql-server-samples/commits/master/samples/features/sql-big-data-cluster/deployment/aks/deploy-sql-big-data-aks.py

maybe you want to bring in that change to the ADS generated notebooks as well

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
