### ISSUE TITLE
If the results view is too small, the tab list overlaps the rest of the UI

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#953]
- SQL Operations Studio Version: master 089577c5a8ab8d6ecf4cbef10a899eabf79e826f

Steps to Reproduce:

Open the output viewlet and size its height large to make the results view small.

![image](https://user-images.githubusercontent.com/4324725/37734687-275e4c54-2d09-11e8-93bc-a481622289cd.png)

**Comment by kburtram** [comment]
This is fixed.
