### ISSUE TITLE
Need support Oracle

### ISSUE THREAD

**Issue by ahdung** [microsoft/azuredatastudio#9543]
Dear ADS team:

I have been using Sql Server and its tools for almost 10 years. This is a pleasant experience. These tools have made my job easier.

But, but, sadly, recently my boss decided to replace ERP, It is based on oracle. After several searching and trying, I found that oracle has almost no any good tool, any!

I miss the days of writing code in SSMS and ADS (mainly the former, I will also ask them). So I sincerely ask you to help me this poor DBA, let your tools support oracle.

THANK YOU!

**Comment by Charles-Gagnon** [comment]
Hello @ahdung - thank you for the feedback, I'm glad our tools are useful to you! Currently for database support we're collecting all requests into single issues to reduce duplication - for Oracle support that's https://github.com/microsoft/azuredatastudio/issues/6724

I'm going to close this one but I encourage you to go upvote that issue and leave any other feedback/suggestions related to supporting that there. Thanks!
