### ISSUE TITLE
Azure Data Studio — Run Button Dimming

### ISSUE THREAD

**Issue by emalcolmb** [microsoft/azuredatastudio#9546]
Context: I'm running some simple queries in Azure Data Studio to query and manipulate data in a local instance of SQL Server 2019.

Question: When I query the table via "Select", the Run button is accessible. As soon as I Truncate the table, the Run button dims & is no longer accessible --__-- Why!? Once the button dims seems I'm unable to execute any other queries in the same query window afterwards. SMH.

I expect this button to be easily accessible, similarly to SQL Server Management studio. I read through the docs and dont see anything about this button dimming issue. Can someone please share any tips/tricks they know on how to fix this issue?

https://stackoverflow.com/questions/60638170/azure-data-studio-run-button-dimming

**Comment by anthonydresser** [comment]
The run button becomes disabled when the query is executing. The cancel button will then become enabled. Is this what you are experiencing?

**Comment by emalcolmb** [comment]
The issue seems to have resolved itself. Not sure how or why but seems to be working now.
