### ISSUE TITLE
Cant connect

### ISSUE THREAD

**Issue by marcoschoma-ltm** [microsoft/azuredatastudio#9549]
Issue Type: <b>Bug</b>

While selecting from "saved connections" and trying to connect to an SQL Server Database the connection properties form is not filled with stored info. Can't connect to any databases.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:01:39.777Z)
OS version: Darwin x64 19.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz (4 x 2300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|4, 4, 4|
|Memory (System)|8.00GB (0.45GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by Charles-Gagnon** [comment]
Can you give us more information? You're saying when you click on an item in the saved connections list nothing is populated below? What happens if you manually enter the information into the fields and try to connect?

**Comment by marcoschoma-ltm** [comment]
Precisely. Although it was solved with a computer reset.
