### ISSUE TITLE
Notebook - Find highlights the entire line/paragraph instead of highlighting the word

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#9550]
Issue Type: <b>Bug</b>

Repro steps:
- Open a Notebook with markdown text in it.
- Try to find items in the Notebook by clicking Ctrl+F
- Click on "Next Match" button to go to other matches.

The Find functionality highlights the entire line/paragraph, making it difficult to see what matched. This is especially true for long sentences. In the image below, the faint yellow highlight is showing where the text 'Severity' is found. It should have highlighted only the word 'Severity', but is highlighting the entire paragraph.

![image](https://user-images.githubusercontent.com/7318752/76454576-24ae5000-6392-11ea-9470-52db31b2d1af.png)

Azure Data Studio version: azuredatastudio 1.16.0 (29031462c7de8d562a348276a27b616e14ffc103, 2020-03-11T16:51:08.075Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MsSQLGirl** [comment]
It looks like .md file exhibits some of the search attributes properly, but not .ipynb.

![image](https://user-images.githubusercontent.com/6405919/80921493-915b2080-8d2b-11ea-8e85-b014dc6d8902.png)

1. the highlight is done at the word level
2. the scroll bar shows the occurrences of the keywords

However, it seems that the search doesn't give an option to do regex or case sensitive option - as shown in (3).

**Comment by MsSQLGirl** [comment]
@chlafreniere / @MaddyDev - can you please help updating the milestone appropriately? :)
