### ISSUE TITLE
Notebook - On switching Notebooks, the Find popup remembers previous context

### ISSUE THREAD

**Issue by qifahs** [microsoft/azuredatastudio#9551]
Issue Type: <b>Bug</b>

Repro steps:
- Open a Notebook with markdown text in it.
- Try to find items in the Notebook by clicking Ctrl+F
- Click on "Next Match" button to go to other matches.
- Open another Notebook

The Find popup sticks around and remembers the previous context. It shows find match count from previous Notebook. The find results are not relevant on the new file.

In the image below, the results are from a previous file. Clicking on Next/Previous match does not do anything. 
![image](https://user-images.githubusercontent.com/7318752/76456080-b36f9c80-6393-11ea-8102-f1637278bed0.png)

Azure Data Studio version: azuredatastudio 1.16.0 (29031462c7de8d562a348276a27b616e14ffc103, 2020-03-11T16:51:08.075Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.84GB (20.79GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by anthonydresser** [comment]
Verified in our own editors. We maintain the hide/show state of the find and the actual search content, but the results of the search update for the editor (the x/y).

**Comment by MaddyDev** [comment]
I tested on the latest insiders and the search results are updated. 
![SearchContextAcrossNBs](https://user-images.githubusercontent.com/12754347/76467626-3fd78a80-63a7-11ea-8426-f66ac85c156b.gif)
