### ISSUE TITLE
Azure Linked Accounts picker is blank

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9562]
Azure Linked Accounts picker is blank

![image](https://user-images.githubusercontent.com/1465785/76467820-baa0a580-63a7-11ea-9976-0964839ca3f5.png)

I think this was introduced in the merge.

**Comment by aaomidi** [comment]
There's also that weird scrollbar.

I'll take a look at this, but @anthonydresser do you have any context on what might have changed?

**Comment by aaomidi** [comment]
Hmm, looks like its a CSS issue.

**Comment by anthonydresser** [comment]
might be the merge, it was a large one.

**Comment by aaomidi** [comment]
The bug exists in the paneview. It impacts basically every part of the product that uses it (extension gallery, azure pane, advanced properties, etc.
