### ISSUE TITLE
Notebooks: Notebooks have no Navigation Buttons when Linked from md File in Book

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9576]
When opening a notebook linked from a markdown file in a Jupyter Book, there are no navigation buttons on the notebook (Previous/Next), and the Jupyter Books viewlet doesn't highlight the opened file.

Note: this is not a regression, so setting milestone to April, since it's still an impacting issue.

**Comment by chlafreniere** [comment]
Update: this does not 100% repro.

**Comment by MaddyDev** [comment]
Am not able to repro this and haven't heard anyone complaint so far. @chlafreniere Can I close this?

**Comment by chlafreniere** [comment]
@MaddyDev I can't repro any longer either. Sure, let's close this one out.
