### ISSUE TITLE
Unable to Create Jupyter Book on Mac

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9577]
On the first cell, I see the following:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-850cfee8bb11> in <module>
      4 cmd = f'{sys.executable} -m pip show jupyter-book'
      5 cmdOutput = get_ipython().getoutput('{cmd}')
----> 6 if len(cmdOutput) > 0 and '0.6.4' in cmdOutput[1]:
      7     print('Jupyter-book required version is already installed!')
      8 else:

IndexError: list index out of range

I don't have jupyter-book installed.

**Comment by MaddyDev** [comment]
Will take a look.
