### ISSUE TITLE
BDC Cluster Dashboard Task Always Adds Item in BDC View with admin Username

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9578]
I have a cluster where i've designated the admin username as "controlleradmin" instead of admin.

I was navigating back and forth between the controller dashboard to the master dashboard and back to the cluster dashboard.

I noticed that we were optimistically adding an item under the BDC view with admin for the username. This left me with 2 items in the view that point to the same controller endpoint:

![image](https://user-images.githubusercontent.com/40371649/76493046-eeeb8480-63ee-11ea-913d-bbd3b1391d0e.png)

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
