### ISSUE TITLE
Connect to saved server connection failed

### ISSUE THREAD

**Issue by mcx808** [microsoft/azuredatastudio#9583]
Issue Type: <b>Bug</b>

An unexpected error ocurred

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6300U CPU @ 2.40GHz (4 x 2496)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.93GB (0.39GB free)|
|Process Argv||
|Screen Reader|no|
|VM|50%|
</details><details><summary>Extensions (8)</summary>

Extension|Author (truncated)|Version
---|---|---
admin-pack|Mic|0.0.2
admin-tool-ext-win|Mic|0.0.2
agent|Mic|0.45.0
dacpac|Mic|1.2.0
import|Mic|0.13.1
profiler|Mic|0.11.0
schema-compare|Mic|1.2.0
whoisactive|Mic|0.1.3

</details>

**Comment by abist** [comment]
@mcx808 Thanks for opening the issue. Could you give some more details about the problem? What kind of server were you connecting to? Could you also check if there are any errors on the Dev Console (Help -> Toggle Developer Tools -> Console or `Ctrl/Cmd + Shift + I` -> Console) and paste the errors here if there are any?
