### ISSUE TITLE
Token cache clear command not working

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9585]
Oh huh, yeah sorry @iamwyza looks like the command isn't currently hooked up to do anything.

@aaomidi - do you know why this was commented out in https://github.com/microsoft/azuredatastudio/pull/8483? https://github.com/microsoft/azuredatastudio/blob/master/extensions/azurecore/src/account-provider/azureAccountProviderService.ts#L73

_Originally posted by @Charles-Gagnon in https://github.com/microsoft/azuredatastudio/issues/9350#issuecomment-598313312_

**Comment by aaomidi** [comment]
Workarounds:

# Windows

Run the following command:

```
 Remove-Item -LiteralPath "$Env:appdata/azuredatastudio/Azure Accounts" -Force -Recurse
```

# Linux
TBA

# MacOS
TBA

**Comment by Parasrah** [comment]
For those struggling with this issue on linux, the config for azure data studio is typically found at `~/.config/azuredatastudio`. Removing this directory (`rm -rf ~/.config/azuredatastudio`) will resolve the issue, but will also remove all config/settings
