### ISSUE TITLE
Secondary Account Authentication (MFA) broken

### ISSUE THREAD

**Issue by willsql4food** [microsoft/azuredatastudio#9610]
Issue Type: <b>Bug</b>

## How it's broken for me
1. Try to connect to a server in Azure
2. Page in default browser is opened and offers account choice for authentication
3. Choices available are my Windows account and my personal @live account
4. Choose "Another account" and enter my secondary Azure AD username
5. Authentication routes back to my Windows account, which is not authorized for Azure.

## How it used to work
1. Try to connect to a server in Azure
2. Azure Data Studio presented a code I could copy
3. Open Firefox (only browser I've found to distinguish between my Windows and Azure AD accounts)
4. Navigate to https://www.microsoft.com/devicelogin and paste code from Azure Data Studio
5. Select my secondary Azure AD account (and enter password if stale)
6. Azure AD recognizes the MFA login and I'm running queries.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.17763

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.86GB (20.24GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>Extensions: none

**Comment by kburtram** [comment]
@willsql4food we are moving to a new auth model that doesn't use device code auth (which is intended for IoT devices).  You can turn on the old device code auth.  With the below user setting.

<img width="839" alt="Screen Shot 2020-03-13 at 1 19 41 PM" src="https://user-images.githubusercontent.com/599935/76656680-60315180-652d-11ea-8f1d-bfed9085295e.png">

@aaomidi any thoughts on this?  Also, I don't see the device code setting in 1.16.0.  Is that intentional?

**Comment by kenvanhyning** [comment]
Approved to add the setting back for 1.16

**Comment by willsql4food** [comment]
Thanks for the quick response!  Setting that flag and restarting ADS gave me the code back.  I can now connect again.

**Comment by willsql4food** [comment]
Enabled setting and working as desired now.

**Comment by kburtram** [comment]
@aaomidi I think this is now fixed in release/1.16, so I'll move to April milestone for the fix that's going into master.  Thanks!

**Comment by aaomidi** [comment]
The setting is now in master.
