### ISSUE TITLE
Cannot Open Created Book in Windows in Create Book Flow

### ISSUE THREAD

**Issue by chlafreniere** [microsoft/azuredatastudio#9617]
Went through the create book flow on my PC.

However, when I got down to the part where I can click the link to open the created book, the following error occurs:

![image](https://user-images.githubusercontent.com/40371649/76662310-d0929f80-653a-11ea-8edc-887143e3b4d6.png)

This breaks the create book flow.

Note: if I open the book through the Open Book command from the command palette, it opens as expected in the viewlet, so the book itself was generated correctly. Just need to fix up the command URI.

**Comment by Charles-Gagnon** [comment]
@MaddyDev You were able to repro this too? I just tried and it seems to work fine for me...
