### ISSUE TITLE
Default backup filename doesn't sort correctly

### ISSUE THREAD

**Issue by scott-moxham** [microsoft/azuredatastudio#9634]
The default name for backup files is almost really good but the formatting could be better.
For example backups form 28th Feb come out as
2020228

Backups from the 1st Mar come out as
202031

Windows will sort them with the March one first.

It really should be formatted as
20200301
and then Windows would sort all the files in date order. Same goes for the time.
Small refinement but would make things much nicer and I know you can sort by date in Windows but this then mixes up backups for different DBs. I always have to manually add the 0s into the filenames.

- Azure Data Studio Version: 1.15.0

Steps to Reproduce:
Go to dashboard for the DB.
Click Backup button
Look at default filename

**Comment by erinstellato-ms** [comment]
@scott-moxham Hi there - in tested with build 1.34 of ADS, backup files now have the following naming convention: DBName-Full-2022-02-03T23:33:45.  Can you please confirm this satisfies your request?  Thank you!

**Comment by scott-moxham** [comment]
Hi,
This looks exactly like I was asking for.
Sorry for slow reply, I was busy with other things when message was sent and then got lost in the mass of my e-mail 🤦‍♂️
