### ISSUE TITLE
Encoding issue when running script from open file

### ISSUE THREAD

**Issue by hrapchik** [microsoft/azuredatastudio#9673]
![1vGZOebsbH](https://user-images.githubusercontent.com/12158869/77079108-2d40ff00-6a00-11ea-9a6e-a75822dbd0ca.gif)

Issue Type: <b>Bug</b>

Encoding settings in ADS: "files.encoding": "windows1251"
1) Open sql file in windows1251 encoding (via menu "File\Open File") with text 
`select 'Тестовое сообщение'`
2) Connect to SQL Server
3) Run script
4) In the results pane, the expected result is "Тестовое сообщение", but in fact, the result is "???????? ?????????"
5) Copy and Paste the script to a new line and click "Run"- now the old part of the script returns "???????? ?????????", the new part returns correct "Тестовое сообщение"
6) Close file and open again, connect and run script - results is correct "Тестовое сообщение"

It seems that the problem is reproduced only the first time you open the file.

Azure Data Studio version: azuredatastudio 1.15.1 (83544eba2504f564d785534cc780d2073feec2cc, 2020-02-15T05:03:16.545Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (6 x 2808)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.87GB (7.55GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (6)</summary>

Extension|Author (truncated)|Version
---|---|---
vscode-tfs|iva|0.7.2
vscode-peacock|joh|3.6.0
ssmskeymap|kev|1.1.0
azdata-sanddance|msr|1.3.9
code-settings-sync|Sha|3.4.3
vscodeintellicode|Vis|1.2.6

</details>

**Comment by anthonydresser** [comment]
Do you have ssms installed? If so could you check if it repros in ssms?

**Comment by hrapchik** [comment]
No, in ssms the problem does not reproduce:
![Ssms_C9vvY0LyKy](https://user-images.githubusercontent.com/12158869/77146097-eb14cd80-6a92-11ea-97d2-0675ca5d5d3e.png)

**Comment by jyrijh** [comment]
Similar problem

Settings
![image](https://user-images.githubusercontent.com/22392357/158582064-589cd0de-54f6-4d6e-b7ee-8ad0ab576aea.png)

Opened scipt file, detect encoding correctly as Windows 1252, but seems to internally treating it as UTF-8
![image](https://user-images.githubusercontent.com/22392357/158582107-57623fca-7feb-4dcd-a4c1-5fa6716b7960.png)

**Comment by hrapchik** [comment]
It looks like this bug has been fixed in version 1.46. I specifically downloaded version 1.45.1 - the error is still there. No longer reproduce in 1.46.
