### ISSUE TITLE
Edit cell doesn't work in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9696]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Open a table in Edit Data
2. Edit a cell

Expected: cell edits similar to desktop

Actual: Cell is blanked out and cannot be edited.  See the screenshot below, all the blank cells should have content but appear blank after being clicked on.

<img width="1015" alt="Screen Shot 2020-03-23 at 12 23 38 PM" src="https://user-images.githubusercontent.com/599935/77355193-42b87080-6d01-11ea-9dee-50bf3d42fe79.png">

**Comment by kburtram** [comment]
@smartguest could you take a look at this?  It looks like the grid now loads since angular was removed, but the cell edit functionality isn't working.

**Comment by smartguest** [comment]
I'll look at it when testing it in web mode
