### ISSUE TITLE
Export results shows error after saving file in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9697]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Run a query
2. Export results to CSV or JSON

Expected: File is opened after being saved.

Actual: File is saved but an error is raised.

<img width="527" alt="Screen Shot 2020-03-23 at 12 29 19 PM" src="https://user-images.githubusercontent.com/599935/77355707-2a952100-6d02-11ea-9a5b-e5ad03612207.png">

**Comment by anthonydresser** [comment]
This is a known issue I need to rewrite the code in this area.

**Comment by anthonydresser** [comment]
fixed #10934
