### ISSUE TITLE
Product Build must fail when SQLToolsService fails to properly download

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9702]
This has a potential of completely breaking our release builds. Sometimes SQLToolsService doesn't get downloaded and built into the package. 

For example: https://mssqltools.visualstudio.com/CrossPlatBuildScripts/_build/results?buildId=58802&view=results

These builds need to fail instead of pass with warnings.

**Comment by aaomidi** [comment]
Did this get fixed with a PR?

**Comment by anthonydresser** [comment]
#9722
