### ISSUE TITLE
Unable to Create Jupyter Book

### ISSUE THREAD

**Issue by way0utwest** [microsoft/azuredatastudio#9704]
- Azure Data Studio Version: 1.16.0

Steps to Reproduce:

1. Open the Jupyer Book panel
2. Click the run icon in the "1. Installation" cell.

I receive this:
![2020-03-23 15_29_54-Window](https://user-images.githubusercontent.com/3932940/77365211-4e189580-6d1b-11ea-8f9c-bc44f23b27d1.jpg)

My Python config looks like this:
![2020-03-23 15_31_18-Window](https://user-images.githubusercontent.com/3932940/77365233-5b358480-6d1b-11ea-8beb-f4ad47b0aadd.jpg)

I'm not sure why I get this syntax error for the f string.

**Comment by chlafreniere** [comment]
@MaddyDev can you take a look when you have some free cycles? I'm wondering if we need some Python version-dependent code, or whether this is a different issue.

**Comment by MaddyDev** [comment]
@way0utwest Can you do pip list and check what version of pip is installed?

**Comment by way0utwest** [comment]
OK, I had to restart a bunch of things here. I started this when Python was v3.5.3. After upgrading, I reset the Python environment here, but I think the PATH was still with v3.5 in the top of the path. I changed this, refreshed the env (refreshenv.com) and then restarted ADS. This then let me go forward with creating the book. Steps 1 and 2 did run. 3 had this error:

![2020-03-23 16_07_39-Window](https://user-images.githubusercontent.com/3932940/77422133-97f09280-6d92-11ea-8606-541088d8e6f5.jpg)

This might be my issue, but the doc in the notebook doesn't really explain well how to structure the source location with files. I had a new notebooks in there, but the structure didn't build.

My Pip for 3.5.3 was 10.x when I started, but I upgraded to v20.x. For 3.8, it was 19.x, and I upgraded.

I do think there isn't version checking for Python in the notebook, and there needs to be a restart message as well if you upgrade.

**Comment by MaddyDev** [comment]
@way0utwest are you still facing this issue?

**Comment by way0utwest** [comment]
@MaddyDev Got a new machine, and haven't tried again in a month or so, but I will give it another try and see how smooth this is. The new machine only has Python 3.8, so that might make things easier.

**Comment by MaddyDev** [comment]
Closing this since we haven't heard any further issues on this. We can revisit if anyone complains.
