### ISSUE TITLE
Sign-In to Azure tree node "link" doesn't work in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9706]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Click the SIgn-in to Azure tree node "link" in the Azure view

Actual: Nothing happens

<img width="398" alt="Screen Shot 2020-03-23 at 3 10 39 PM" src="https://user-images.githubusercontent.com/599935/77368185-efeab300-6d18-11ea-9bbd-ee8429183696.png">

**Comment by aaomidi** [comment]
Unable to repro this on the latest webmode builds.

**Comment by aaomidi** [comment]
This bug has been fixed
