### ISSUE TITLE
Seeking community feedback on Kqlmagic preview

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9713]
The Azure Data Studio team is working on enabling Kqlmagic in Notebooks. With Kqlmagic, you can create a Python notebook and use `%kql` to start their Kusto / kql queries. Kqlmagic allows you to connect to Azure Data Explorer (ADX), Application Insights and Log Analytics.

We would appreciate your feedback or any questions you may have. 

Sample code:
`%kql azureDataExplorer://code;cluster='help';database='Samples'`
`%kql StormEvents | summarize count() by State | sort by count_ | limit 10`
`%kql StormEvents \`
`| summarize event_count=count() by bin(StartTime, 1d) \`
`| render timechart title= 'Daily Storm Events'`

Here's what it should look like:
![image](https://user-images.githubusercontent.com/6405919/77446662-e9f1e200-6dab-11ea-9ebd-73a2a4507d36.png)

Quick gif on user experience:
![Kqlmagic-short](https://user-images.githubusercontent.com/6405919/77450220-37704e00-6db0-11ea-9140-67f86747a23d.gif)

Currently this preview is available on Azure Data Studio Insiders build. 

> Version: 1.17.0-insider (user setup)
> Commit: 6e5fbc9012c05cfd0cc8f3db014d245df2afc174
> Date: 2020-03-25T06:26:38.833Z
> VS Code: 1.42.0
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

To get started: download [Kqlmagic-ADSDemo.txt](https://github.com/microsoft/azuredatastudio/files/4385335/Kqlmagic-ADSDemo.txt) notebook and **rename** the file extension from "txt" to "ipynb" (since GitHub does not support ipynb file attachment). Once you rename the file extension to ipynb, open the file in the latest ADS Insiders.

**Comment by cairneym** [comment]
Connection String also needs to have the Azure region included for the cluster - e.g. 'clusterName.australiaeast'

The KQL queries only seem to support simple queries at this time - LET doesn't appear to work

**Comment by MsSQLGirl** [comment]
Hi @cairneym , 

Thanks for the feedback. 

It looks like "let" works. However the indentation is a little sensitive. Here's an example of how it should work:
In a code cell, set the connection -
`%kql appinsights://appid='DEMO_APP';appkey='DEMO_KEY'`

In a new cell, write the query with the proper indentation:
```
%%kql 
    let totalPagesPerDay = pageViews 
        | summarize by name, Day = startofday(timestamp) 
        | summarize count() by Day
        | limit 10;
    totalPagesPerDay

```

![image](https://user-images.githubusercontent.com/6405919/77714419-39940180-6f96-11ea-8834-456fd63f0404.png)

Can you please try it out and see if it works?

Thanks!

**Comment by cairneym** [comment]
Hi @MsSQLGirl 

I found that the empty line between the LET statement and then the query that uses it was also causing the issue.  My revised query with now appears to run OK.

I noticed also that a command window is opened up running python as well. Currently displays
 * Serving Flask app "kqlmagic_temp_files_server" (lazy loading)
 * Environment: development
 * Debug mode: on
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 169-990-870
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
127.0.0.1 - - [27/Mar/2020 12:23:47] "[37mGET /files/Kqlmagic_temp_files/_<my database name>_at_<my instance name>_schema.html HTTP/1.1[0m" 200 -
127.0.0.1 - - [27/Mar/2020 12:23:47] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -

**Comment by codykonior** [comment]
Just wanted to note that the 'an empty line breaks stuff' is how Kusto.Explorer and other applications work (I think it's treated as a batch separator).

What's the chances the same or similar method could be added to the PowerShell kernel? Because my notebooks are typically PowerShell rather than Python, and you can't mix the two.

**Comment by Expecho** [comment]
Can we expect some intellisense in the (near) future?

**Comment by MsSQLGirl** [comment]
@gupta1  - FYI.

**Comment by kburtram** [comment]
Closing older issues without recent updates.  Please reactive if you're still trying to get feedback on this preview feature.  Thanks!
