### ISSUE TITLE
Azure Sign-In goes to unreachable page in webpage

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9714]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Sign-in to Azure using Account Manager

Expected: Works

Actual: Unreachable page.  We should default to devicecode auth in webmode to avoid this.

<img width="948" alt="Screen Shot 2020-03-24 at 9 20 45 AM" src="https://user-images.githubusercontent.com/599935/77450785-ff1d3f80-6db0-11ea-9f83-ddd1f09412cf.png">

**Comment by anthonydresser** [comment]
@aaomidi you'll need to port forward the local port you are using.

**Comment by aaomidi** [comment]
@anthonydresser Can I do that dynamically? I pick a random port at the moment. I could change it to something static but I guess we'd have to document that.

**Comment by anthonydresser** [comment]
https://github.com/microsoft/azuredatastudio/blob/master/src/vs/vscode.proposed.d.ts#L207

**Comment by anthonydresser** [comment]
Take a look at what vscode is doing for their auth. Last time I checked it works in web mode.

**Comment by aaomidi** [comment]
https://github.com/microsoft/azuredatastudio/blob/d810da9d87f3a875135f971de1fe89a1bd4dfb2a/extensions/vscode-account/src/AADHelper.ts#L314
