### ISSUE TITLE
Extension details page doesn't load in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9715]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Click on an extension in the Extension Manager

Expected: Details page loads

Actual: Page load error

<img width="1363" alt="Screen Shot 2020-03-24 at 9 25 17 AM" src="https://user-images.githubusercontent.com/599935/77451198-984c5600-6db1-11ea-8a84-301e20b5ac46.png">

**Comment by anthonydresser** [comment]
The issue here is vscode uses an external service to render external resources, and we don't have that service.

**Comment by kburtram** [comment]
Webmode bugs are currently tracked in ADO
