### ISSUE TITLE
New Notebook doesn't open connected when launched from OE

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9716]
- Azure Data Studio Version: `master` + `web`

Steps to Reproduce:

1. Connect to a server
2. Open New Notebook from the connection

Expected: Notebook uses the connection

Actual: Notebook opens disconnected

<img width="732" alt="Screen Shot 2020-03-24 at 9 35 57 AM" src="https://user-images.githubusercontent.com/599935/77452378-1eb56780-6db3-11ea-8848-e5abffe4e0fd.png">

**Comment by chlafreniere** [comment]
We had this issue in insiders earlier this week, but it no longer reproes. Need to verify that it is also fixed in web mode.

**Comment by chlafreniere** [comment]
Just tried this myself with latest bits from master on web mode, and this no longer reproes. Likely fixed by the issue that we were seeing a couple of weeks ago.
