### ISSUE TITLE
Unable to open a Notebook in Jupyter Book Viewlet

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9721]
- Azure Data Studio Version:
Version: 1.16.0-insider (user setup)
Commit: a7dbb68f7d4b862d76e91284a619ed022e8b4745
Date: 2020-03-23T06:17:26.698Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Run _Azure Data Studio Insiders_.
2. Type **Ctrl** + **Shift** + **P** and type *Jupyter Books: SQL Server 2019 Guide*. 
3. Navigate to the **Jupyter Book viewlet** and try to open a notebook. 
Nothing happens. 
Note: opening the notebook from search works though.

![ADSInisders-OpenSQL2019NotebookIssue](https://user-images.githubusercontent.com/6405919/77486432-fa767c80-6dec-11ea-8a3e-90ef526924c9.gif)

**Comment by chlafreniere** [comment]
Looks to be fixed in today's insiders build.
