### ISSUE TITLE
openTextDocument API creates two untitled editor

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#9723]
- Azure Data Studio Version:

Steps to Reproduce: 1.17.0

1. in an extension, use openTextDocument API to open a SQL document:
 await vscode.workspace.openTextDocument({
				language: 'sql',
				content: 'Select * from sys.tables'
			});

2. Verify the document is opened
3. close ADS and reopen
Expected: only one untitled document should be open
Actual: I see two untitled document. one with SQLQuery prefix and one with name 'untitled'
clicking on the 'untitled' doc opens a new 'SQQuery' doc 

<img width="1440" alt="Screen Shot 2020-03-24 at 4 40 51 PM" src="https://user-images.githubusercontent.com/17187348/77486966-52fa4980-6dee-11ea-8547-d8ffc06f23eb.png">

Also, looks like running queryeditor.runQuery api, passing the untitled document doesn't do anything. This seems to be a regression because I'm pretty sure it was Working.

**Comment by kburtram** [comment]
Closing older engineering-focused bugs.  Please open a bug with details on the customer-facing scenario impacted.  Thanks!
