### ISSUE TITLE
schema compare shows empty window for source/target selection

### ISSUE THREAD

**Issue by zaferaydinosf** [microsoft/azuredatastudio#9727]
Not sure if it is a bug or happens only to me, I cannot select `Source` nor `Target` to compare. An empty window is opened like below image with nothing to select.

- Azure Data Studio Version: 1.16.1 (user setup) / Windows 10 OP
- SQL Server Schema Compare Version: 1.3.0

Steps to Reproduce:
1. Ctrl + Shift + P and type `Schema Compare` then click
2. Click eclipse button **(...)** to choose `Source `or `Target`
3. The displayed window is empty. Cannot select any db connection.

![image](https://user-images.githubusercontent.com/45619053/77522108-bccd2e80-6e94-11ea-8008-6ccf9eef5bb5.png)

**Comment by kisantia** [comment]
Does this repro every time? Can you open up the developer tools and see if there are any errors in the console?

**Comment by zaferaydinosf** [comment]
Hello @kisantia 
Yes, it happens every time. I opened developer tools console. I see some errors after clicking **Cancel** in **Schema Compare** popup window which is show as empty window. It seems there is an exception while trying to list the database names but not sure why it tries to retrieve database name lists. I can just select from the saved connections or enter the database name manually.

**First One:**
`c:\Users\myuser\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] [Error - 11:44:19 PM] Request connection/listdatabases failed.`

**Second:**
`c:\Users\myuser\AppData\Local\Programs\Azure Data Studio\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host]   Message: Microsoft.Data.SqlClient.SqlException (0x80131904): The server principal "myusername" is not able to access the database "master" under the current security context.
Cannot open database "master" requested by the login. The login failed.
Login failed for user 'myusername'.
`

**Others:**
`Cannot read property 'databaseNames' of undefined: TypeError: Cannot read property 'databaseNames' of undefined
    at v.$listDatabases (file:///C:/Users/myuser/AppData/Local/Programs/Azure Data Studio/resources/app/out/vs/workbench/workbench.desktop.main.js:5168:236)
    at processTicksAndRejections (internal/process/task_queues.js:85:5)`
