### ISSUE TITLE
Import wizard from SQL Server Import not appearing

### ISSUE THREAD

**Issue by EliasDel** [microsoft/azuredatastudio#9728]
- Azure Data Studio Version: 1.16.0

Steps to Reproduce:

Download Azure Data Studio 1.16.0 (I have the Linux .deb) 
Install the SQL Server Import 0.14.0

Right-click on the database where you want to import to.
Now there should be an option 'Import Wizard', but it's not there.

Ctrl+I should open the Import Wizard to, but that gives me the error:
command 'flatFileImport.start' not found

Does anyone know how to fix this?

**Comment by kburtram** [comment]
@EliasDel could you please try connecting to the server without specifying a database?  Then right-click on the database in the Databases child folder.  There is a bug where the context-menus are different for the top-level DB node and child nodes.

*Server connection*
<img width="419" alt="Screen Shot 2020-03-25 at 12 02 13 PM" src="https://user-images.githubusercontent.com/599935/77575405-b6d54e80-6e90-11ea-83af-61bb4ff71d4b.png">

*Database connection*
<img width="398" alt="Screen Shot 2020-03-25 at 12 02 21 PM" src="https://user-images.githubusercontent.com/599935/77575422-bd63c600-6e90-11ea-9cd5-7637a9fdd2d3.png">

**Comment by EliasDel** [comment]
Yes that was the problem. Thanks a lot!
