### ISSUE TITLE
Existing pyspark notebook fails to execute or create SparkSession

### ISSUE THREAD

**Issue by carrollwp** [microsoft/azuredatastudio#9729]
- Azure Data Studio Version:
Version: 1.16.0-insider (user setup)
Commit: 03ce5d1ba76b39423c1625495e044bd9520453cd
Date: 2020-03-19T06:14:53.618Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:
Open an existing pyspark notebook and run the notebook and fails. No SparkSession created.
Cut an paste same code to new pyspark notebook and runs successfully.

Workaround: 
Open same existing pyspark notebook and toggle from the pyspark kernel to a sql kernel and then back to the pyspark kernel and run the notebook. Runs successfully.

**Comment by chlafreniere** [comment]
I tested this locally and was unable to repro this. We have an internal thread going on, so will keep this open in case the repro steps are slightly different.

**Comment by chlafreniere** [comment]
This should be fixed now with our June release. Please feel free to reactivate if you still encounter this problem.
