### ISSUE TITLE
Dashboard Server page widgets don't display correctly in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9731]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Connect to a server and open the Manage dashboard

Expected: Widgets load correctly

Actual: Widgets can't find a required SQL file

<img width="1024" alt="Screen Shot 2020-03-25 at 12 58 33 PM" src="https://user-images.githubusercontent.com/599935/77580023-82fe2700-6e98-11ea-893f-65b6cf7a1333.png">

**Comment by alanrenmsft** [comment]
@kburtram are you working on this issue?
