### ISSUE TITLE
Duplicate Azure sign-in button in action bar for vscode experience

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9732]
- Azure Data Studio Version: `master`

Steps to Reproduce:

1. Open ADS

Expected: One Azure account experience

Actual: Two Account icons, 1 in actionbar & 1 in statusbar.  Actionbar button goes through VS Code account experience.

<img width="482" alt="Screen Shot 2020-03-25 at 1 03 57 PM" src="https://user-images.githubusercontent.com/599935/77580638-96f65880-6e99-11ea-8575-7aeb35da1232.png">

**Comment by aaomidi** [comment]
What should we do with this?

**Comment by aaomidi** [comment]
Well it seems like the button is gone atm.
