### ISSUE TITLE
Ctrl-N doesn't open a new Query Editor in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9734]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Ctrl-N opens a new default web browser window in webmode

Expected: A new query editor document.  We should offer a different keyboard shortcut for New Query in webmode, since I assume we can't use Ctrl-N in this environment.

**Comment by aaomidi** [comment]
Something interesting:


![image](https://user-images.githubusercontent.com/1465785/78624312-332b4280-783e-11ea-8d33-f8bf80e2c616.png)


You can install this as an application, and in those situations ctrl+n works.

**Comment by aaomidi** [comment]
https://src.chromium.org/viewvc/chrome?revision=127787&view=revision
