### ISSUE TITLE
Expanding Azure Server\DB nodes spins forever in webmode

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9736]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Connect to an Azure subscription with an Azure SQL DB2. 
2. Expand Server or DB nodes in the subscription

Expected: Nodes expand

Actual: Nodes spin forever

<img width="440" alt="Screen Shot 2020-03-25 at 2 06 52 PM" src="https://user-images.githubusercontent.com/599935/77585675-1be57000-6ea2-11ea-8f17-5737622c7124.png">

**Comment by aaomidi** [comment]
I'm not seeing this issue on my instance:

![image](https://user-images.githubusercontent.com/1465785/78619334-f0fc0400-7831-11ea-9626-ddab1c61dea8.png)


I think I've noticed the loading times for those nodes are longer on WSL environments, but they do eventually load.

**Comment by anthonydresser** [comment]
I'm no longer seeing this.
