### ISSUE TITLE
New connection - Advanced properties duplicated

### ISSUE THREAD

**Issue by bergeron** [microsoft/azuredatastudio#9738]
When adding a new SQL Server or Postgres connection, the Advanced Properties window duplicates the input cells when switching to/from the advanced tab.

1. Create a new connection
2. Click Advanced:
![image](https://user-images.githubusercontent.com/3500406/77586462-76cb9700-6ea3-11ea-803a-7e912b151592.png)
3. Use the arrow in the top left to go back:
![image](https://user-images.githubusercontent.com/3500406/77586485-877c0d00-6ea3-11ea-8bbf-77f515269e69.png)
4. Click Advanced again.
5. The sections and input cells are duplicated each time you do this.  I can't show it via screenshot but you can see the scroll bar got smaller:
![image](https://user-images.githubusercontent.com/3500406/77586539-9c58a080-6ea3-11ea-83ae-a6be0ec150e2.png)
6.  Even if I discard/cancel the connection then re-initiate a new connection, the fields in the advanced properties window remain duplicated (and they duplicate an additional time)

I'm running ADS that I built from source against the latest master commit (74b0dc28c4872f289f17d6cff59454d0be336e23).  Although the help -> about window thinks differently:

Version: 1.17.0
Commit: 9ca6200018fc206d67a47229f991901a8a453781
Date: 2017-12-15T12:00:00.000Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by Charles-Gagnon** [comment]
Shoot, good catch @bergeron. I know what the issue is here - thanks for the report!
