### ISSUE TITLE
Import Flat File Wizard - hangs at table schema

### ISSUE THREAD

**Issue by nichojo89** [microsoft/azuredatastudio#9748]
Azure Data Studio Version: 1.16.1
Steps to Reproduce:

Download Azure Data Studio 1.16.1 Mac
Install the SQL Server Import 0.14.0

Launch Flat file import wizard. When selecting anything other than master Table Schema area just hangs and I cannot use this tool. 
![image](https://user-images.githubusercontent.com/7871976/77665651-57417680-6f56-11ea-8a6a-d57bb79c30a5.png)

Does anyone know how to fix this?

**Comment by aaomidi** [comment]
Are you connected to an Azure SQL database or local?

**Comment by nichojo89** [comment]
Hello Amir,

This issue happens while connected to Azure db but not while master is
selected. I also had a colleague replicate the same issue while using same
version of ADS & Import wizard and she has also replicated.

Please let me know if there is any further information required.
[image: image.png]

Jon Nichols
*https://NicholsSoftware.com <https://NicholsSoftware.com>*
(248) 890 6977

**Comment by stegley** [comment]
Is this issue fixed now? Will it be available as an update in the import flat file tool?
Thanks

**Comment by kburtram** [comment]
@aasimkhan30 merged #10216 to resolve this bug.  The fix should be in the next Import extension release planned for next Wednesday (5/20).

**Comment by stegley** [comment]
Hi Karl, That's great news, thanks for the info and I look forward to the fix.  Cheers
