### ISSUE TITLE
Notebooks kernel is opening up a separate cmd window

### ISSUE THREAD

**Issue by anthonydresser** [microsoft/azuredatastudio#9755]
- Azure Data Studio Version: insiders.
![image](https://user-images.githubusercontent.com/4324725/77701226-09873700-6f73-11ea-8c31-26c5c02084e0.png)

Steps to Reproduce:

1. Open a notebook with python kernel

See a separate cmd window

**Comment by anthonydresser** [comment]
I'm assuming this is related to the kusto magic stuff

**Comment by chlafreniere** [comment]
@anthonydresser, yes. @gupta1 is looking into this already.

**Comment by chlafreniere** [comment]
Fixed by #9871 for new users (and for April) to remove kqlmagic as a default package. 

To fix this problem in insiders/dev builds, you can uninstall the kqlmagic python package through the manage packages button, and the cmd window will no longer appear.
