### ISSUE TITLE
No prompt on 1st launch to turn on preview features

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9759]
- Azure Data Studio Version: `master` + `webmode`

Steps to Reproduce:

1. Open ADS

Expected: On first launch there is a prompt to turn on preview features

Actual: No prompt and preview features are disabled

**Comment by aaomidi** [comment]
Is this only for webmode or for ADS as well?

I wasn't able to repro this locally

![image](https://user-images.githubusercontent.com/1465785/78618345-1a676080-782f-11ea-991b-5d0368cb48b2.png)
