### ISSUE TITLE
Close All Tabs

### ISSUE THREAD

**Issue by brentn** [microsoft/azuredatastudio#9764]
It would be great, when selecting "close all tabs", and it prompts you to save each tab - if there were a checkbox that said "do this for all tabs".  

I like to clean up by closing tabs, and not saving any of them, but it requires an inordinate amount of clicking "Don't Save" in order to do so.

Thank.

**Comment by kburtram** [comment]
@brentn you can close all open unsaved editors with a single prompt using the "Close all Editors" command from the Open Editors section of the Explorer viewlet.  The current "Save Prompt on Close" behavior is coming from default vscode upstream.

![image](https://user-images.githubusercontent.com/599935/78413698-80ed4400-75cd-11ea-9bac-022528b9b577.png)

**Comment by kburtram** [comment]
Closing based on the previous comment.  Thanks for opening this suggestion!
