### ISSUE TITLE
not able to open command palette

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9768]
today's insider, tried on Windows and macOS

I am getting an error notification when trying to open the command palette with the following errors in console.

<img width="527" alt="Screen Shot 2020-03-27 at 12 34 35 PM" src="https://user-images.githubusercontent.com/13777222/77793693-bde29500-7027-11ea-86e1-45d876301eb7.png">

**Comment by Charles-Gagnon** [comment]
Duplicate of https://github.com/microsoft/azuredatastudio/issues/9763
