### ISSUE TITLE
Previous Connection not reopening

### ISSUE THREAD

**Issue by raedwa01** [microsoft/azuredatastudio#9769]
Issue Type: <b>Bug</b>

Before the latest updates to ADS, when I would open a SQL window, the last connection to a server from the previous window would reconnect automaticly.  Now it prompts to select a connection again.  This seemed to start autoconnecting in January and suddenly stopped.

1. Open a SQL file from hard drive. 
2. Select a connection.
3. Open another file.
4. Prompted for another connection (this was autoconnecting to the previous connection recently)

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 19.3.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i9-8950HK CPU @ 2.90GHz (12 x 2900)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 2|
|Memory (System)|32.00GB (5.30GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (11)</summary>

Extension|Author (truncated)|Version
---|---|---
gitlens|eam|10.2.0
gc-excelviewer|Gra|2.1.32
admin-pack|Mic|0.0.2
agent|Mic|0.46.0
dacpac|Mic|1.3.0
import|Mic|0.14.0
profiler|Mic|0.11.0
vscode-print|pdc|0.7.12
sql-search|Red|0.3.6
vscodeintellicode|Vis|1.2.1
poor-sql-formatter|WSR|0.1.0

(2 theme extensions excluded)

</details>

**Comment by Charles-Gagnon** [comment]
@raedwa01 Are you sure this is still happening even after the update to 1.16.1? There was a regression in 1.16 that caused that behavior to be broken but it should be working again in 1.16.1.

**Comment by raedwa01** [comment]
Yes.  I am running 1.16.1 and I just duplicated the problem

**Comment by Charles-Gagnon** [comment]
If you're able to get a capture of the repro that would also be helpful - Screen2Gif is a useful tool I use for that to capture GIFs.
