### ISSUE TITLE
Execution messages and results printed out of order in messages window

### ISSUE THREAD

**Issue by casperOne** [microsoft/azuredatastudio#9779]
- Azure Data Studio Version:

Version: 1.16.1 (user setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

Execute the following in any query window against a SQL server instance

```
drop schema if exists temp_should_not_exist
go

create schema temp_should_not_exist
go

drop schema if exists temp_should_not_exist
go
```

The expected output is:

````
7:56:12 PM Started executing query at Line 1
Commands completed successfully.

7:56:12 PM Started executing query at Line 3
Commands completed successfully.

7:56:12 PM Started executing query at Line 6
Commands completed successfully.

Total execution time: 00:00:00.130
````

Actual output is

````
7:56:12 PM Started executing query at Line 1
7:56:12 PM Started executing query at Line 3
7:56:12 PM Started executing query at Line 6
Commands completed successfully.
Commands completed successfully.
Commands completed successfully.
Total execution time: 00:00:00.130
````

![image](https://user-images.githubusercontent.com/561862/77836689-ac37e500-712e-11ea-8d35-2bf6d1c7b696.png)

Notes:

Originally reported:

https://twitter.com/casperOne/status/1243992443076427779

**Comment by kburtram** [comment]
Ported fix to release/1.18
