### ISSUE TITLE
Jupyter Books viewlet shows duplicated book structure when TOC is updated

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9781]
Azure Data Studio version: azuredatastudio-insiders 1.17.0-insider (be83b31e378774ed14879fb1889c47422e68bea5, 2020-03-27T06:21:06.051Z)
OS version: Windows_NT x64 10.0.18363

Issue Type: <b>Bug</b>

1. Update toc.yml with another line item.
2. Press Ctrl + S to save.
3. The Saved Books subviewlet in Jupyter Books viewlet will show duplicated books. 

![JupyterBookViewletTOCUpdate](https://user-images.githubusercontent.com/6405919/77838237-e309fd00-7126-11ea-8288-0500762f5865.gif)

![image](https://user-images.githubusercontent.com/6405919/77838205-8a3a6480-7126-11ea-89ac-924a7c101b3b.png)

**Comment by MaddyDev** [comment]
Well this happens only when we try to update the toc file from ADS. Not sure how events are triggered when editing toc from editor in ADS. But this doesn't happen when you edit and save the file outside ADS. 
I'll look into what's happening when editing within ads.
