### ISSUE TITLE
Create Book (Preview) doesn't work for notebooks spanning across multiple folders (list index out of range)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9783]
- Azure Data Studio Version:
> Version: 1.17.0-insider (user setup)
> Commit: be83b31e378774ed14879fb1889c47422e68bea5
> Date: 2020-03-27T06:21:06.051Z
> VS Code: 1.42.0
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Setup the directory of the notebook files to be imported (source files) in multiple directories.
NotebookSource\Chapter1\Notebook11.ipynb
NotebookSource\Chapter1\Notebook12.ipynb
NotebookSource\Chapter1\Notebook13.ipynb
NotebookSource\Chapter2\Notebook21.ipynb
NotebookSource\Chapter2\Notebook22.ipynb
NotebookSource\Chapter2\Notebook23.ipynb

2. Use Create Book (Preview) and follow the instructions.
On the third cell you'll see "list index out of range"

![image](https://user-images.githubusercontent.com/6405919/77839185-67607e00-712f-11ea-96f4-f619d32e62d1.png)

Expected outcome:
- MyNewNotebook
   - Chapter 1
        - Notebook11.ipynb
        - Notebook12.ipynb
        - Notebook13.ipynb
   - Chapter 2
        - Notebook21.ipynb
        - Notebook22.ipynb
        - Notebook23.ipynb

**Comment by MaddyDev** [comment]
@MsSQLGirl  Can you tell me if there are any other files in the folders other than ipynb? My current implementation should be able to create the above, not sure why it's failing for you.
