### ISSUE TITLE
Decorations are not Refreshed on Kernel Change

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9785]
- Azure Data Studio Version:

> Version: 1.17.0-insider (user setup)
> Commit: be83b31e378774ed14879fb1889c47422e68bea5
> Date: 2020-03-27T06:21:06.051Z
> VS Code: 1.42.0
> Electron: 7.1.11
> Chrome: 78.0.3904.130
> Node.js: 12.8.1
> V8: 7.8.279.23-electron.0
> OS: Windows_NT x64 10.0.18363

Steps to Reproduce:

1. Create a new Notebook (the default should be "SQL").
2. Start typing in `%kql` statement like below:
![image](https://user-images.githubusercontent.com/6405919/77839502-2322ad00-7132-11ea-8f5a-5dc2dfcf2d3b.png)
There should be a squiggly red on the notebook as shown in the image above.
3. Change the Kernel to Python 3. You should still see the squiggly red like below.
![image](https://user-images.githubusercontent.com/6405919/77839520-5b29f000-7132-11ea-917e-5ee67e6c93b5.png)
However if you type in %kql in another cell, the squiggly red doesn't appear post kernel update to Python.
![image](https://user-images.githubusercontent.com/6405919/77839524-667d1b80-7132-11ea-8268-7f4690195b36.png)

Expected outcome:
After changing to Python kernel, the syntax warning squiggly red should get refreshed.

**Comment by chlafreniere** [comment]
Let me take a quick look at this one. If there's a simple solution I'll fix it now; otherwise, we can assess with other bugs.

**Comment by kburtram** [comment]
Approved in shiproom, pending availability of fix and code review.

**Comment by chlafreniere** [comment]
This doesn't have a fix yet, so pushing out to June. Removed the Approved label.

**Comment by chlafreniere** [comment]
This has been since fixed by our friend @lucyzhang929
