### ISSUE TITLE
窗口没有智能提示

### ISSUE THREAD

**Issue by joezjy** [microsoft/azuredatastudio#9799]
Issue Type: <b>Bug</b>

数据库连接后，智能提示功能失效

Azure Data Studio version: azuredatastudio 1.16.1 (16801c522df68e63218b39ccb5b4a7431f9bf667, 2020-03-23T22:06:16.901Z)
OS version: Darwin x64 18.7.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8559U CPU @ 2.70GHz (8 x 2712)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|3, 2, 2|
|Memory (System)|32.00GB (5.36GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
ads-language-pack-zh-hans|Mic|1.9.0

</details>

**Comment by aaomidi** [comment]
Title: Window without smart tips

Body: After the database is connected, the intelligent prompt function fails

**Comment by Charles-Gagnon** [comment]
Sounds like an intellisense issue. I'm going to close it because we already have a ton of these - there's a general class of issues here that mostly just revolve around how we handle slow metadata requests.
