### ISSUE TITLE
Creating a new tab from focussed tab on right group creates tab in left group

### ISSUE THREAD

**Issue by FuegoArtificial** [microsoft/azuredatastudio#9804]
- Azure Data Studio Version:
Version: 1.16.1 (system setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763

Steps to Reproduce:

1. Open two sql query tabs and split them into a left and a right group.
2. click on the tab in the right group
3. use ctrl+N to create a new tab
4. the new tab is created in the left group
expected: the new tab is created in the same group as the one of the focussed tab (right).

When creating new tabs/queries I now usually have to drag and drop the newly created tab to the other group before continuing my work.

Off topic: I love your azure data studio and use it all the time! Keep it up!

**Comment by kburtram** [comment]
@FuegoArtificial when I try the repro my new query editor documents are being opened in the editor group with focus as expected (i.e. the right group in this example).  @anthonydresser are you able to repro this bug?

**Comment by FuegoArtificial** [comment]
The issue still consists in my environment.
In addition a second empty tab is opened together with the initial one without any connection.
Am I doing something wrong?

Azure Data Studio Version:
Version: 1.18.0 (system setup)
Commit: 2acd37a1b1cff34b64fbb4ea2d40715d7e2accac
Date: 2020-05-19T23:54:30.554Z
VS Code: 1.45.0
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17763
