### ISSUE TITLE
Configuring Anaconda for notebook in mac takes long time and fails at the end

### ISSUE THREAD

**Issue by llali** [microsoft/azuredatastudio#9815]
I installed anaconda in mac and configured it in notebook so notebook started to install the dependencies. It took an hour for it to install the packages but it failed at the end with this error:
`Installing Notebook dependencies failed with error: Process exited with  with error code: 1. StdErr Output:  Building graph of deps:   0%|          | 0/305 [00:00<?, ?it/s] Examining libcurl:   0%|          | 0/305 [00:00<?, ?it/s]      Examining distributed:   0%|          | 1/305 [00:00<00:03, 78.91it/s] Examining ripgrep:   1%|          | 2/305 [00:03<07:49,  1.55s/it]     Examining ripgrep:   1%|          | 3/305 [00:03<05:12,  1.03s/it] Examining lazy-object-proxy:   1%|   ` 

the output or developer console didn't have anything useful.

**Comment by corivera** [comment]
If you repeat the install operation in a separate Anaconda prompt does it succeed?

**Comment by llali** [comment]
yes @corivera , I retired multiple times. every time it starts from beginning, takes about an hour and fails at the end

**Comment by corivera** [comment]
Looks like this may be an issue with the latest release of Anaconda. I tried the release from July 2019 and didn't hit any hangs.

**Comment by corivera** [comment]
FYI @chlafreniere

**Comment by corivera** [comment]
Reopening to track port to rel branch.
