### ISSUE TITLE
[tht13.python]: "configuration.jsonValidation.url" 必须是绝对 URL 或者以 "./" 开头，以引用扩展中的架构。

### ISSUE THREAD

**Issue by sisrfeng** [microsoft/azuredatastudio#9821]
- Azure Data Studio Version:

Steps to Reproduce:

1.[tht13.python]: "configuration.jsonValidation.url" 必须是绝对 URL 或者以 "./" 开头，以引用扩展中的架构。
请问这怎么解决呢？

**Comment by chlafreniere** [comment]
This "absolute URL" issue has since been fixed.

**Comment by whubaichuan** [comment]
@chlafreniere  how can the problem "configuration.jsonValidation.url" be sovled?
