### ISSUE TITLE
Unable to import the data from excel to New Tables in Azure Data Warehouse

### ISSUE THREAD

**Issue by dheerajm31** [microsoft/azuredatastudio#9822]
- Azure Data Studio Version:

Steps to Reproduce:

1.

**Comment by dheerajm31** [comment]
Hi , 

I am unable to load the data from CSV file to table in azure datawarehouse database.

Getting below error :

“Cannot open server – – requested by the login"

**Comment by DTronD** [comment]
Similar to #10104  perhaps?

**Comment by aasimkhan30** [comment]
#11341  has added compatibility for DWs. Closing this issue
