### ISSUE TITLE
Government/National cloud support on ADS

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9832]
- [x] US Government Cloud
- [ ] China Cloud
- [ ] Germany Cloud

**Comment by kburtram** [comment]
@aaomidi do you know the status of this task with regards to the May release?

**Comment by aaomidi** [comment]
I haven't added any of the other national clouds yet. Just the US govt one.

**Comment by aaomidi** [comment]
@yualan @kburtram has there been an ask for govt clouds of other regions? If not I think we can keep this in the backlog and start tracking when there is an ask.

**Comment by roxxette** [comment]
Hi, please add China Cloud support.

**Comment by kburtram** [comment]
@roxxette have you enabled support for Azure Chine in the User Settings?  Please let us know if this doesn't resolve the issue?

<img width="708" alt="Screen Shot 2020-12-17 at 11 28 48 PM" src="https://user-images.githubusercontent.com/599935/102586846-b4babc00-40bf-11eb-84cc-fac04a568f1a.png">

**Comment by cheenamalhotra** [comment]
Closing issue as commonly used Azure Clouds are supported in ADS.
