### ISSUE TITLE
Unexpected Paste Operations on SQL Script

### ISSUE THREAD

**Issue by valerionet** [microsoft/azuredatastudio#9851]
Issue Type: <b>Bug</b>

Using Azure Data Studio on Linux Mint 19 I'm facing an unexpected issue.

Just after some copy and paste operation, when scrolling my SQL Script up and down rapidly, somehow a lot of paste operations are made on all over the Script, messing the code.

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T22:56:48.883Z)
OS version: Linux x64 4.15.0-20-generic

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz (12 x 4300)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: disabled_off<br>protected_video_decode: unavailable_off<br>rasterization: disabled_software<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: unavailable_off<br>viz_display_compositor: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|1, 1, 1|
|Memory (System)|31.26GB (24.12GB free)|
|Process Argv|--unity-launch|
|Screen Reader|no|
|VM|0%|
</details><details><summary>Extensions (7)</summary>

Extension|Author (truncated)|Version
---|---|---
ssmskeymap|kev|1.1.0
admin-pack|Mic|0.0.2
agent|Mic|0.46.0
dacpac|Mic|1.3.0
import|Mic|0.14.0
managed-instance-dashboard|Mic|0.4.1
profiler|Mic|0.11.0

</details>

**Comment by kburtram** [comment]
@valerionet are you seeing this behavior frequently?  I couldn't repro and the 1.13.1 build, has been released for a couple months and we haven't seen any similar bug reports yet.  Could you please try upgrading to the latest ADS release and confirm if the bug reproduces?  Thanks!

**Comment by anthonydresser** [comment]
If you could turn on tracing (`F1` -> `Developer: Set Log Level`), reproduce the issue and post your render logs, that would be helpful in tracking down this issue.
