### ISSUE TITLE
PowerShell Notebook dose not switch to PSVersion 7

### ISSUE THREAD

**Issue by ralphke** [microsoft/azuredatastudio#9864]
- Azure Data Studio Version:

Steps to Reproduce:

1.Start a new PowerShell Notebook
2. enter $PSVersionTable and press enter
3. the reported PowerShell version remains Version 5
PSVersion                      5.1.18362.628   
4. even the Settings have been set to version 7
    "powershell.powerShellDefaultVersion": "7"

**Comment by chlafreniere** [comment]
This is being tracked by #7758.
