### ISSUE TITLE
Replace tabs with spaces when saving

### ISSUE THREAD

**Issue by OSch24** [microsoft/azuredatastudio#9879]
I would like to be able to configure that not only the spaces at the beginning and end are deleted when saving. I would also like to be able to configure that all tabs are replaced by spaces. I still have to do this by hand.

cu Oliver

**Comment by Charles-Gagnon** [comment]
There's a setting to auto-trim trailing whitespaces when saving a file :

![image](https://user-images.githubusercontent.com/28519865/78692318-8b9a2880-78ae-11ea-8d75-9cd87cf5da9f.png)

This doesn't do leading whitespaces - but you might be able to find a VS Code extension that does that. Many VS Code extensions work in ADS as well so you can browse the marketplace for one that does what you need and then :

1. Download it from the marketplace page 

![image](https://user-images.githubusercontent.com/28519865/78692422-bc7a5d80-78ae-11ea-84f2-4981324a4c9b.png)

This will download the VSIX. 
2. Then open ADS and choose File -> Install Extension From VSIX Package

Not all extensions will work, but if you find one you like that does then I'd suggest reaching out to the author and seeing if they'd be willing to help support it in ADS as well (we'll gladly work with any extension authors to support their extension working in ADS as well)


For the replacing tabs with spaces (or vice versa) there's two commands you can use - `Convert Indentation to Spaces` and `Convert Indentation to Tabs`.

**Comment by OSch24** [comment]
First of all many thanks for the tips.
I'm looking for an extension.
When I press TAB, it is already replaced by 4 spaces. 
But my point is, if I don't just open my old projects or if other developers open the projects, that I replace all existing tabs with 4 spaces at once. Best when saving or I could somehow put this on key.

**Comment by Charles-Gagnon** [comment]
Did you look at the two commands I mentioned above? Those will replace all leading tabs/spaces in the document when ran. 

There's no built-in functionality to replace ALL tabs/spaces in a document though directly as far as I know. I suppose you could use a regex replace or something do achieve that behavior though if you can't find an extension to do it for you though.

**Comment by OSch24** [comment]
The two options are of course activated.
But my wish would be to replace all tabs with spaces.

I'll check the extensions right away.

But your idea with RegEx also sounds exciting.

What or how should I do this?
Can I put this on key? 
Do I have to write a script for this?
Is there an example?

Thank you very much in advance.

**Comment by Charles-Gagnon** [comment]
If you open a document and press ctrl+F that will open the find/replace dialog. Then you can expand it and enter the character you want to replace and the character you want to replace it with. So if you wanted to replace all tabs with spaces it'd look like this :

![image](https://user-images.githubusercontent.com/28519865/78915049-33932b80-7a40-11ea-8213-7eb5a9c6feab.png)

(note the first box has a space in it and the regex button on the right is selected)

Then just click replace all and it'll replace all spaces in the documents with tabs. And to replace tabs with spaces just switch the characters in the text boxes.

**Comment by OSch24** [comment]
Thank you very much.
Is there a way to put this on a " key"?

Tab -> Space.

And if I may make a suggestion, it would be great if I could set this in the settings when saving.
