### ISSUE TITLE
cannot view my installed extensions

### ISSUE THREAD

**Issue by psalqvist** [microsoft/azuredatastudio#9880]
Installed extensions won't appear upon the management dashboard as they are suppose to do. I have enabled preview extensions as well as installed the extensions. The reload button doesn't appear when I install the extensions though, I wonder if that has anything to do with it. Or are there any further settings I have to take into consideration before being able to use extensions?

**Comment by Charles-Gagnon** [comment]
Could you include a screenshot of what you're seeing? Include the version of ADS you're using (and make sure to update to the latest build if you haven't already)
