### ISSUE TITLE
Can't connect cloud shell

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9882]
Open new cloud shell terminal instance and it just shows this forever

![image](https://user-images.githubusercontent.com/28519865/78695331-d158f000-78b2-11ea-869e-cba1452d101a.png)

From console :

![image](https://user-images.githubusercontent.com/28519865/78695265-bbe3c600-78b2-11ea-91ba-90a6b566bb63.png)

**Comment by aaomidi** [comment]
So this happens if the user hasn't ever used cloudshell before.

We can look into bringing the first time use experience of the cloudshell to ADS, but it's pretty involved so for now I'll just fail with an informative message telling users what to do.
