### ISSUE TITLE
2019 TSG is opening text editor to files on disk

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9883]
When I run the command to open the 2019 TSG and then edit any of the pages it opens up the actually backing file and thus any changes made there are persisted to the shipped version of the book.

This is especially confusing because the book is opened in the "Unsaved Books" section which implies that changes won't be persisted anywhere. 

![image](https://user-images.githubusercontent.com/28519865/78695974-acb14800-78b3-11ea-9c20-279a4985a902.png)

**Comment by MaddyDev** [comment]
Huh, it's not prompting you for save? It's directly saving it to the file? I wonder what vscode changed again, we haven't changed anything around that code for the last two iterations.

**Comment by Charles-Gagnon** [comment]
No, double clicking to edit a file opens the editor for the file on disk itself and thus saving it just acts like a normal file save.

**Comment by chlafreniere** [comment]
@MaddyDev does this still repro?

**Comment by MaddyDev** [comment]
@chlafreniere yes, I was able to root cause it, the reason is we don't open markdown files as untitled (there isn't way currently). We can open them as read-only but that doesn't seem to do the trick. Need to find an alternative for this.

**Comment by Charles-Gagnon** [comment]
BDC support in ADS is [being deprecated](https://techcommunity.microsoft.com/t5/sql-server-blog/azure-data-studio-and-bdc-retirement/ba-p/3669192) so closing all related issues.
