### ISSUE TITLE
Azure Account adding not working

### ISSUE THREAD

**Issue by waldyd** [microsoft/azuredatastudio#9885]
- Azure Data Studio Version:
![image](https://user-images.githubusercontent.com/1531796/78701787-3ae5f800-78cd-11ea-972d-981a5039f7d9.png)

Steps to Reproduce:

1.Try to Sign in to Azure
![image](https://user-images.githubusercontent.com/1531796/78701492-c14e0a00-78cc-11ea-926e-dc651ee75e00.png)
2. Click Add an Account:
![image](https://user-images.githubusercontent.com/1531796/78701551-d75bca80-78cc-11ea-95d6-994f3a34a77d.png)

3. Supposedly account added:
![image](https://user-images.githubusercontent.com/1531796/78701695-1427c180-78cd-11ea-9457-846dcd1e10ab.png)
4. No account added:

**Comment by aaomidi** [comment]
Hey @waldyd, could you please see if adding an account works on the latest insiders build?

https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master

**Comment by waldyd** [comment]
> Hey @waldyd, could you please see if adding an account works on the latest insiders build?
> 
> https://github.com/microsoft/azuredatastudio#try-out-the-latest-insiders-build-from-master

Yes. It is working for the Latest Windows User Insider version.

**Comment by aaomidi** [comment]
Thanks! Then this problem should be fixed for next release.

**Comment by waldyd** [comment]
@aaomidi but when trying to connect. This was prompted:

![image](https://user-images.githubusercontent.com/1531796/78715404-ffeebf00-78e2-11ea-9554-bb1f424b3e8f.png)

**Comment by aaomidi** [comment]
Hmm, that's weird. Does it repro 100% of the time?

**Comment by waldyd** [comment]
`Adding key failed: Error: A specified logon session does not exist. It may already have been terminated.
 (at t.SimpleTokenCache.<anonymous> (c:\Users\nalvarez\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:23460))
2c:\Users\nalvarez\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280 [Extension Host] Getting key failed: Error: A specified logon session does not exist. It may already have been terminated.
 (at t.SimpleTokenCache.<anonymous> (c:\Users\nalvarez\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\extensions\azurecore\dist\extension.js:166:23670))
c:\Users\nalvarez\AppData\Local\Programs\Azure Data Studio - Insiders\resources\app\node_modules.asar\zone.js\dist\zone-node.js:2280   ERR Error: Failed to get Azure account token for connection
    at e.connectWithOptions (workbench.desktop.main.js:5617) [<root>]
    at processTicksAndRejections (internal/process/task_queues.js:85) [<root>]
    at async e.handleDefaultOnConnect (workbench.desktop.main.js:7773) [<root>]`

**Comment by magnusbratt** [comment]
I am getting the sate issue in insiders build on Mac OSX.
![image](https://user-images.githubusercontent.com/6708638/78809278-f3dc2d80-79c6-11ea-8c9d-292e7dbc3fa5.png)

After adding the account I get the following error message, and no account is added
![image](https://user-images.githubusercontent.com/6708638/78809344-0fdfcf00-79c7-11ea-98c5-0e351349f538.png)

In the console I get
![image](https://user-images.githubusercontent.com/6708638/78809511-56cdc480-79c7-11ea-8a4f-8394a8cbd9ac.png)

**Comment by aaomidi** [comment]
Thank you this is extremely useful to investigate.

**Comment by aaomidi** [comment]
@waldyd It seems like your issue is something to do with how your windows is setup. Azure Data Studio uses Windows Credential Manager to store authentication tokens.

![image](https://user-images.githubusercontent.com/1465785/78825387-bd85ba80-7994-11ea-9ef0-fc75b9805e2e.png)

This is technically the expected/secure way for us to store authentication tokens.

I think there is an argument to be made for us to enable flat-file storage for users like yourself that may have a stricter domain configuration, but I'm not entirely sure if that's wise as these tokens essentially identify you to the Azure service.

I recommend looking up the error you've received "A specified logon session does not exist. It may already have been terminated & Credential Manager", and you'll find a few threads that talk about that same issue.

If you look at your Local Group Policy Editor (Win+R, gpedit.msc) the following setting might be switched on to "Enabled":

![image](https://user-images.githubusercontent.com/1465785/78825652-3258f480-7995-11ea-9419-189f69ff4f25.png)

This is likely blocking ADS to store credentials there.

**Comment by waldyd** [comment]
Hi @aaomidi . That policy was already disabled in my case:

![image](https://user-images.githubusercontent.com/1531796/78924011-b9be6a80-7a5e-11ea-8de2-3d86fb54d181.png)

**Comment by aaomidi** [comment]
@waldyd If it's enabled it wouldn't work I think. Can you try to use ADS on another device and see if you can repro this?

**Comment by aaomidi** [comment]
@magnusbratt We've published a new insiders build with more debug output, can you try to add your account on the latest version of ADS insiders?

**Comment by magnusbratt** [comment]
OK. I updated to the lastest Insider version. I added my Azure account, and get the web page sign in. Then I get this error message in ADS:
![image](https://user-images.githubusercontent.com/6708638/78927665-8fd96800-7a9f-11ea-837a-8831275583db.png)

and this in the developer tools console
![image](https://user-images.githubusercontent.com/6708638/78927735-ac75a000-7a9f-11ea-94e1-cb0feaae4505.png)

**Comment by magnusbratt** [comment]
I now also installed the Insiders build on a Windows PC. When signing into Azure, I got 
![image](https://user-images.githubusercontent.com/6708638/78928057-42a9c600-7aa0-11ea-9e4e-a4c8d10ad254.png)

I then get the same
![image](https://user-images.githubusercontent.com/6708638/78928166-6e2cb080-7aa0-11ea-986c-4c21b0c0e35e.png)

and in the developer tools console
![image](https://user-images.githubusercontent.com/6708638/78928237-8ef50600-7aa0-11ea-960c-37d2731ece7e.png)

**Comment by aaomidi** [comment]
So it seems you belong to a tenant where you don't actually have permissions to do resource management on it.

I'll make a PR that silently ignores tenants where you don't have permissions to do operations on them. Hopefully that fixes your problem.

It'll also contain some more debug information giving you information on why that's failing.

Can you check on azure portal to see if you have permissions to the tenant described by:
![image](https://user-images.githubusercontent.com/1465785/78931787-4cf5a100-7a5b-11ea-973b-5893b6efd3e6.png)

**Comment by magnusbratt** [comment]
My account does belong to a few directories where I do not have permissions. However, for the directory referenced, I am  "global administrator".
![image](https://user-images.githubusercontent.com/6708638/78937072-1ac25e80-7ab0-11ea-9d4f-67801f9c10e4.png)

However, I removed "left the organization" for another tenant that I know I do not have permissions to. After this, I was able to expand my subscriptions and access resources. But when I try to expand a database to view it, it does not expand. The spinner never stops, se screenshot. There are no additional messages in the developer tools console.
![image](https://user-images.githubusercontent.com/6708638/78940751-a8a14800-7ab6-11ea-8d54-d51205e94ee6.png)

**Comment by aaomidi** [comment]
Whoops didn't mean to close this issue. Let's wait for the insiders build tomorrow and go over this. Thank you so much for helping me debug this @magnusbratt :)

**Comment by magnusbratt** [comment]
Just FYI. I just updated to the latest Insider build and the issue persists.

![image](https://user-images.githubusercontent.com/6708638/79247388-bf5eea80-7e7a-11ea-98c9-38b43d4a27be.png)

I get no new messages in developer tools console.

**Comment by aaomidi** [comment]
Could you please share your console either way? Would still be helpful :)

**Comment by magnusbratt** [comment]
Here is a screenshot, including developer tools console

![image](https://user-images.githubusercontent.com/6708638/79267885-293abc80-7e9a-11ea-834d-bb8cd1100469.png)

**Comment by aaomidi** [comment]
Oh so it lists the databases, just doesn't connect to them right?

**Comment by magnusbratt** [comment]
Correct. That's a new behavior since after I left the tenant for which I did not have permissions. That is, I can expand the account, the subscription, "SQL database", but not view the database.

I can also expand the account, the subscription, "SQL server", but not view/expand the server.
![image](https://user-images.githubusercontent.com/6708638/79271239-c3513380-7e9f-11ea-82c2-3c75c4f81c44.png)

**Comment by aaomidi** [comment]
@magnusbratt Alright that's a whole different issue. Could you try making yourself the admin on that server on azure portal. 

Open the SQL Database on Azure Portal, and add your account as the Active Directory admin.

![image](https://user-images.githubusercontent.com/1465785/79274137-f58b7280-7e58-11ea-8509-df04d64cfb91.png)

**Comment by magnusbratt** [comment]
@aaomidi Is it OK to continue in this thread, or do you want me to create a new issue?

I am already a member of the Active Directory group that is admin of the server.

![image](https://user-images.githubusercontent.com/6708638/79325590-ba00af00-7f11-11ea-8084-eef879555be7.png)

![image](https://user-images.githubusercontent.com/6708638/79325819-1f54a000-7f12-11ea-9ba7-e622cd8528d8.png)

**Comment by magnusbratt** [comment]
@aaomidi FYI: Today I updated ADZ Insiders on my Mac and it now works to sign in with my AAD account and access the database servers and databases I have access to. 

It still does not work with the non-insider build, but I assume that is a matter of time.

I have also tested the latest insiders build on my PC and it works just as well.

Thanks for developing great software!

**Comment by chriskinsman** [comment]
This is still an issue for me with Azure Insiders 1.18.0 build.

Trying to connect to postgres.

  ERR Error: Failed to get Azure account token for connection
    at e.connectWithOptions (workbench.desktop.main.js:5724) [<root>]
    at async e.handleDefaultOnConnect (workbench.desktop.main.js:7901) [<root>]

**Comment by aaomidi** [comment]
Insiders is unfortunately a little broken at the moment. I would suggest sticking to the release branch.

If this issue is specific to PostgreSQL, I would recommend opening another issue.

**Comment by chriskinsman** [comment]
Wasn't working in release which is why I tried insiders.

**Comment by aaomidi** [comment]
So since the original issue is fixed, I'll be closing this issue.

Please definitely open a new issue if you are seeing any issues with AzureMFA.

**Comment by tcoldiron** [comment]
Azure Data Studio is not providing much detailed feedback, it just fails.

Using Azure Data Studio Version: 1.42.0 (Universal) on MacBook Pro with MacOS Ventura Version 13.2.1 (22D68)

<img width="1650" alt="Screenshot 2023-04-04 at 2 27 56 PM" src="https://user-images.githubusercontent.com/104081326/229927555-c1b21c0c-b895-446c-827d-4ddfe2f51d28.png">

We recently changed from SQL Server login, to Azure Active Directory authentication, and I haven't been able to log in since, whether by "Connection" or "Add Account" or any way.

**Comment by cheenamalhotra** [comment]
@tcoldiron 

Please find this related issue and recommendation: https://github.com/microsoft/azuredatastudio/issues/22227#issuecomment-1466631757

**Comment by tcoldiron** [comment]
That recommendation got me going!  Thanks!
