### ISSUE TITLE
Copy carriage return/line feeds when copying results grid to clipboard

### ISSUE THREAD

**Issue by DaveBoltman** [microsoft/azuredatastudio#9898]
I'm always frustrated when I try to copy multi-line text in the SQL query results grid to the clipboard, and it puts everything in a single line when the text is pasted. E.g: please see the screenshots below.

It would be great if the text being copied is not "fiddled with" when copying to the clipboard, so carriage return & line feed characters (and anything and everything else) are preserved.

As a workaround in the mean-time, it's interesting that all the other options there - Save as CSV, Excel, JSON, XML - preserve carriage returns and line feeds in the saved text. So I saved as a CSV file, and copied the text from my text editor to the clipboard (which obviously copied the CR/LFs as well). But it would be much easier, and "the right thing to do", if the text didn't get modified on it's way to the clipboard.

Additional context:
Azure Data Studio Version: 1.16.1 (system setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.17134

**When copying:**
    ![image](https://user-images.githubusercontent.com/8627894/78765761-ba84cd00-7988-11ea-80c4-184855a6e681.png)

**When pasting:**
    ![image](https://user-images.githubusercontent.com/8627894/78769374-94156080-798d-11ea-9e5a-900e9643b3b2.png)

**Comment by DaveBoltman** [comment]
@anthonydresser Please note this is a problem with the query results grid, not with

**Comment by DaveBoltman** [comment]
@anthonydresser I see the [adsbot](https://github.com/apps/adsbot) assigned this to you under the "Area - Query Editor". It's nothing to do with the query editor though, but the results grid. Would you mind, please, assigning this feature request to the correct "Area" so it gets triaged correctly?
I appreciate your help.

**Comment by anthonydresser** [comment]
We consider the results grid to be in the same feature bucket as the query editor, so the query editor tag is correct.

**Comment by DaveBoltman** [comment]
I see there's an option in Settings to fix this. I tested it and it works, so I'm closing this issue:

&nbsp;&nbsp;&nbsp;&nbsp;![2020-04-24_144448](https://user-images.githubusercontent.com/8627894/80214279-db147e80-863a-11ea-83b9-ee2fe6c1012b.png)

@anthonydresser Thank you for your contributions to Azure Data Studio!
