### ISSUE TITLE
Notebook readability

### ISSUE THREAD

**Issue by sassora** [microsoft/azuredatastudio#9899]
When I write a notebook in ADS I'd like to make it easy for me convert to PDF and have the code cells not be truncated. In general, I'd like it to be easier to have a narrower paragraph width. This is help with the readability and would help make best practice consistent (I've read 80 characters as a rule of thumb).

I think the feature would take the form of a setting / option as people have different tastes.

**Comment by chlafreniere** [comment]
Thanks, we'll consider adding this in a future release.

**Comment by chlafreniere** [comment]
Tracked by #4536. Closing this issue as a result.
