### ISSUE TITLE
Issue #9851 - Unexpected Paste Operations on SQL Script

### ISSUE THREAD

**Issue by valerionet** [microsoft/azuredatastudio#9900]
Folowing Karl Burtram's suggestion for issue #9851, I performed the upgrade for the latest release (1.16.1), however the problem persists. Couldn't it be related to any Extension I use?

Also, I can record the issue happening if somehow it may help. Thanks a lot!

**Comment by Charles-Gagnon** [comment]
Definitely please try running without any extensions and see if the problem persists. You can do this easily by passing the `--disable-extensions` parameter to the process through the command line. 

e.g. on Windows it'd look like this

`%USERPROFILE%\Programs\Azure Data Studio\bin\azuredatastudio.cmd --disable-extensions`
