### ISSUE TITLE
Custom Metadata gets deleted from notebooks

### ISSUE THREAD

**Issue by rajeshka** [microsoft/azuredatastudio#9906]
- Azure Data Studio Version: 1.16.1

**Steps to Reproduce:**

1. Edit a notebook .ipnb file in text editor and add a field to metadata property.
2: Open that notebook in ADS, edit and save

**Observation:**
Custom field added to the metadata properties disappears

**Expected:**
ADS should retain custom properties

**Comment by chlafreniere** [comment]
This was checked in as part of #9948.

**Comment by rajeshka** [comment]
Added Custom telemetry here #9948
