### ISSUE TITLE
Connections closed after opening folder

### ISSUE THREAD

**Issue by benrr101** [microsoft/azuredatastudio#991]
- SQL Operations Studio Version: 889b60a71bb877087da90dd959a44bd4662db25d (Feb 27th)
- OSX 10.12.16

Steps to Reproduce:
* Open SQLOps, connect to a database
* Open workspace viewlet, no folder is opened, select a folder to open
* SQLOps "restarts"

Expected result: Previously opened connection (and dashboard) remain open
Actual result: Previously opened connection is closed

Even if this is by design, I'd like to double-check:
* Are the connections any active queries being cleaned up?
* Does the sqltoolsservice stop or is it being orphaned?

**Comment by kburtram** [comment]
This is application lifecycle behavior that we've inherited from VS Code.  Opening a folder is basically the same as closing and reopening the application.  This should cleanly shutdown the extension host and associated child process.  Please open an issue if you observe that not being the case.  I'll move to backlog as an upstream suggestion.

**Comment by benrr101** [comment]
Understandable. It will be a more tolerable issue if we make sure that #79 is resolved -- I can give you more repro data on that one if you need.

**Comment by kburtram** [comment]
@benrr101 I wasn't able to repro #79.  I left some notes in that issue.  Please add additional repro data there if possible.

**Comment by kburtram** [comment]
Closing out older issues.  Thanks for reporting!
