### ISSUE TITLE
Notebook: kqlmagic tabular output got truncated (please support tabular output like SQL kernel)

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9912]
Steps to Reproduce:

1. Rename the attached txt file to ipynb.
[Kqlmagic tabular output.txt](https://github.com/microsoft/azuredatastudio/files/4453503/Kqlmagic.tabular.output.txt)

2. The notebook is pre-run so you can see the results.
3. Resize the window to less wide.

What the output looks like when ADS window is maximized.
![image](https://user-images.githubusercontent.com/6405919/78847719-6c8dba80-79c4-11ea-92bb-e6ebf509db4c.png)

After ADS window resize (narrower width), the results got chopped off with no way of scrolling vertically.
![image](https://user-images.githubusercontent.com/6405919/78847748-84653e80-79c4-11ea-81e9-b9e03c5800f4.png)

It looks like kqlmagic output is using wordwrap. This makes it harder to navigate large resultset. 

Suggestion: It would be nice to be able to navigate tabular output similar to SQL notebook, i.e.
* it allows vertical scrolling and horizontal scrolling
* it supports file export to different formats
* it supports charting
![image](https://user-images.githubusercontent.com/6405919/78848039-68ae6800-79c5-11ea-9e22-17c95900898d.png)

Azure Data Studio Version:
Version: 1.17.0-insider (user setup)
Commit: fca2344c2edce2c561b34b130504adae7a74ea73
Date: 2020-04-08T06:01:27.168Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by chlafreniere** [comment]
There's an ongoing thread where the kqlmagic folks will enable this for us by changing the type in which results are returned.

**Comment by MsSQLGirl** [comment]
The tabular output is now working similar to in SQL Notebook. It would be great if the "index" column (from kql result) gets dropped since SQL Notebook has row number in the tabular output by default. 
Currently the "index" column muddies the resultset that could be used with Charting feature. 

tagging @gupta1

**Comment by chlafreniere** [comment]
Assigning to @gupta1 to work with kqlmagic folks on the index issue. Feel free to move into a milestone when we have an ack that this can be done from the kqlmagic side.

**Comment by MsSQLGirl** [comment]
@gupta1 - I think this issue is resolved now.

**Comment by chlafreniere** [comment]
@MsSQLGirl @gupta1 is this resolved yet? Can we close this issue?

**Comment by MsSQLGirl** [comment]
Closing this issue since it's already fixed.
cc @gupta1
