### ISSUE TITLE
Notebook: kqlmagic perf issue when there are too many rows returned

### ISSUE THREAD

**Issue by MsSQLGirl** [microsoft/azuredatastudio#9913]
Azure Data Studio version: azuredatastudio-insiders 1.17.0-insider (fca2344c2edce2c561b34b130504adae7a74ea73, 2020-04-08T06:01:27.168Z)
OS version: Windows_NT x64 10.0.18363

Issues:

1. When retrieving large resultset from Kusto using kqlmagic, ADS freezes and becomes unresponsive for a while until the resultset is completely fetched and rendered.
To repro: 
```
%kql azureDataExplorer://code;cluster='help';database='Samples'
%kql StormEvents | limit 10000
```
2. After the resultset comes back, ADS becomes sluggish.

Size of ipynb file after running: 14MB.

![image](https://user-images.githubusercontent.com/6405919/78848799-a7ddb880-79c7-11ea-953e-1162953226b7.png)

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz (12 x 3696)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|63.78GB (36.10GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by MsSQLGirl** [comment]
If I do `%kql StormEvents` with no `limit`, and start navigating other areas of ADS, I'll get the following:
![image](https://user-images.githubusercontent.com/6405919/78849201-a19c0c00-79c8-11ea-963d-52391c0476b9.png)

**Comment by chlafreniere** [comment]
This has since been fixed with kqlmagic giving data in the dataresource MIME type.
