### ISSUE TITLE
EULAs are not localized

### ISSUE THREAD

**Issue by Matteo-T** [microsoft/azuredatastudio#9935]
- Azure Data Studio Version:
Version: 1.16.1 (system setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.19605

**Steps to Reproduce:**
1. On a non-English OS (I was on Win10 Italian)
2. Run the Setup (I downloaded the "System-wide package"
3. Look at the EULA

**Result:**
It's in English

**Expected:**
Should be in Italian (or whatever language the user decided to use)

**Comment by kburtram** [comment]
The EULAs were provided as-is from CELA so we've kept them that way for compliance.
