### ISSUE TITLE
Preview Button in ADS Welcome Page 

### ISSUE THREAD

**Issue by aaomidi** [microsoft/azuredatastudio#9943]
![image](https://user-images.githubusercontent.com/1465785/79160079-10dd7b80-7d8e-11ea-804a-2624fef129fe.png)

I use my mouse to follow the text I'm reading, it makes it easier. However, when I move the mouse off of the preview button and onto the text box the box disappears.

**Comment by alanrenmsft** [comment]
@v-bbrady our issue triage process: triage and move the issue to proper milestone, after that you can remove the Triage:Needed label and add the Triage:Done label. since you are the owner of the Area-UX, please also keep monitoring the issues coming into this area.

**Comment by chlafreniere** [comment]
@alanrenmsft does the welcome page still have the preview tag? I don't see it anymore.

**Comment by alanrenmsft** [comment]
![image](https://user-images.githubusercontent.com/13777222/107680320-8a662480-6c52-11eb-939c-efdf54f21818.png)
it is still there but it is now a standard tooltip. I think this issue is no longer relevant. Closing it.
