### ISSUE TITLE
Tabbed panel inside ModelView Dashboard is not preserving tab orientation when switching tabs

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9947]
![Capture](https://user-images.githubusercontent.com/28519865/79163625-49805380-7d94-11ea-8a47-712e798a7a3a.gif)

**Comment by alanrenmsft** [comment]
The sample in the sql services extension is similar to this, but i can't reproduce the issue. Which branch is this, i 'd like to use it as a repro.

**Comment by Charles-Gagnon** [comment]
I don't have this pushed to a branch yet, but I'm working on fixing this up.

The primary issue I believe is that the layout isn't being enforced correctly and the defaults aren't working correctly. I'll let you know if I'm having any issues otherwise I should have a PR out shortly.
