### ISSUE TITLE
Key Length too long when adding Azure Account

### ISSUE THREAD

**Issue by Charles-Gagnon** [microsoft/azuredatastudio#9950]
Reported through https://github.com/microsoft/azuredatastudio/issues/9525

The user was getting a key length error when attempting to add their Azure account. 

![image](https://user-images.githubusercontent.com/28519865/79167574-9405ce00-7d9c-11ea-84db-5d7fa289c903.png)

**Comment by rhythmnewt** [comment]
Just to confirm this happens with this version:

Version: 1.17.0-insider (system setup)
Commit: 15fc4517eeaa551f8f352e0fed54c6044d31f530
Date: 2020-04-13T17:32:48.451Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by aaomidi** [comment]
@rhythmnewt with the latest insiders build, please do the following:

- Open Settings
- Open Extensions
- Open "Azure"
- Tick the box that says "Disable system keychain"
- Restart ADS
- Try logging in again

![image](https://user-images.githubusercontent.com/1465785/79264948-34fe9280-7e4a-11ea-92ba-f3fd0dd76fed.png)

**Comment by rhythmnewt** [comment]
Followed the steps and checked the box to disable system keychain. Same error still occurs.

Version: 1.17.0-insider (system setup)
Commit: a8cf029633c1e725d41bb28654615e112c58d111
Date: 2020-04-14T05:49:33.406Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

![image](https://user-images.githubusercontent.com/1319322/79266486-a26bec80-7e65-11ea-9d5e-986bfc4a34a0.png)

**Comment by aaomidi** [comment]
And just to confirm, you restarted after checking that checkbox?

**Comment by rhythmnewt** [comment]
Yes, I have restarted the ADS. I also tried it with a freshly downloaded ZIP version of the insider's build to the same effect.

**Comment by aaomidi** [comment]
Can you navigate to `%appdata\Roaming\azuredatastudio\Azure Accounts`. Are there any files under that path?

Can you delete all of those files and restart ADS and see if those files are being created?

**Comment by rhythmnewt** [comment]
These were the two files that were there which I deleted.
![image](https://user-images.githubusercontent.com/1319322/79275955-22e61980-7e75-11ea-98c3-c78a999ff19f.png)

Restarted ADS and tried to login, that generated this new file.
![image](https://user-images.githubusercontent.com/1319322/79275911-0c3fc280-7e75-11ea-8ed4-ee286accc927.png)

**Comment by rhythmnewt** [comment]
The workaround with the "No System Keychain" setting turned on now works in this insider's build:
Version: 1.17.0-insider (system setup)
Commit: 30607ec61b9eb47ad55d931e528b5ecab4bdf4eb
Date: 2020-04-15T05:57:54.355Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by aaomidi** [comment]
Great! I'm glad to hear that.

Really surprised that your keys were that long to begin with.

**Comment by rhythmnewt** [comment]
@aaomidi I actually did a fiddler trace of the authentication and grabbed the JWT access_token which turned out to be 2523 characters in length. I'm assuming that's the key that's throwing the error.

My organizational account is an AD account synced to Azure AD, and in the decrypted JWT there were a good 15 guids in the groups array which base64-encoded comes out to >900characters in just that section.

I am an owner/member of many distribution lists and groups in my organization and that array of guids will only grow with time.

**Comment by aaomidi** [comment]
The fix for this is in master and release branch.
