### ISSUE TITLE
Change default option for Deployment wizard

### ISSUE THREAD

**Issue by dnethi** [microsoft/azuredatastudio#9957]
Currently, upon launching the Deployment dialog, the default selection is "SQL Server Container image". The dialog dynamically displays the Required Tools based on the selection of deployment option and displays in a red banner at the top if the user doesnt have any of the required tools. 
Most users may or may not have "docker" tool installed on their machine causing an unwelcome launch experience. 

We should change the default to "SQL Server on Windows" which does not require any tools and thus users wont see any ugly red error messages as their first launch experience.

thanks,
Dinakar

**Comment by alanrenmsft** [comment]
I have a fix for it but i don't think this meets the ASK mode bar for april release.
