### ISSUE TITLE
Not able to connect to MS SQL Sever installed locally 

### ISSUE THREAD

**Issue by vk-ravi82** [microsoft/azuredatastudio#9960]
Issue Type: <b>Bug</b>

Not able to connect to MS SQL Sever installed locally 

Azure Data Studio version: azuredatastudio 1.13.1 (d08d07fe39c7fe74f9265db02cb963c38d048299, 2019-11-14T23:08:09.800Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8350U CPU @ 1.70GHz (4 x 1896)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: disabled_software<br>oop_rasterization: unavailable_off<br>protected_video_decode: unavailable_off<br>rasterization: unavailable_off<br>skia_deferred_display_list: disabled_off<br>skia_renderer: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: disabled_off<br>webgl: enabled_readback<br>webgl2: enabled_readback|
|Load (avg)|undefined|
|Memory (System)|3.00GB (0.40GB free)|
|Process Argv||
|Screen Reader|no|
|VM|100%|
</details><details><summary>Extensions (1)</summary>

Extension|Author (truncated)|Version
---|---|---
azdata-sanddance|msr|1.3.9

</details>

**Comment by alanrenmsft** [comment]
@vk-ravi82 what name did you use when connecting to the local instance and what error are you getting?

**Comment by Marklb** [comment]
I don't know if my issue is related, but it may be. I can connect to my local instance, using Windows Authentication, and execute queries, but at first I didn't realize it was connecting correctly. I used the "New Connection" button on the SERVERS header of the Connections panel and it opened a dashboard tab for my local , but didn't add the server to the list of servers in the Connections panel. If mine isn't related to the same problem I can open a new issue.

Azure Data Studio version 1.16.1

Local SQL Server version: 15.0.2000.5 Microsoft SQL Server Developer (64-bit)

**Comment by vk-ravi82** [comment]
Hello,

I tried with localhost as well as computer name.

**Comment by alanrenmsft** [comment]
@Charles-Gagnon could you please follow up on this issue?

**Comment by Charles-Gagnon** [comment]
@vk-ravi82 Are you able to connect with other tools such as SSMS?

This guide may also be helpful in diagnosing issues you have connecting : https://support.microsoft.com/en-us/help/4009936/solving-connectivity-errors-to-sql-server

**Comment by Charles-Gagnon** [comment]
@Marklb So you're saying these are the steps you went through :

1. Clicked "New Connection" button at the top of the Servers view pane

![image](https://user-images.githubusercontent.com/28519865/80011639-fd629c80-8480-11ea-983c-8868c98d7c59.png)

1. Filled out the server information in the connection dialog
1. Clicked Connect
1. The dialog closed and the dashboard was opened - but the connection was NOT added to the list of servers

Is that correct? Did you verify that you had the server group set as something besides "Do not save"?

![image](https://user-images.githubusercontent.com/28519865/80011881-55010800-8481-11ea-94f6-048fcc36dccc.png)

**Comment by Marklb** [comment]
@Charles-Gagnon That is correct, but I am not 100% certain what the Server group was set as. I have never intentionally changed it, so I don't see a reason it would have been anything other than "<Default>". My local server is getting added to the list correctly now though, so my issue may not have been the same.

Since I no longer see the problem it may not matter, but I'll list my guesses for what may have caused mine, in case they make sense for solving this. 
- I may not have restarted my computer after installing SQL Server. I don't remember if I tried before or after restarting my computer last week.
- Some setting I may have changed in SQL Server when I was restoring a few databases from a backup made from one of the remote servers I could connect to and see in the list.

**Comment by vk-ravi82** [comment]
Hey Thank You!

After I updated the Azure Data Studio, all the problems are sorted and it
is connecting. I am not sure where the problem was. But it is all fine.

My latest version is 1.16.1

Version: 1.16.1 (user setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363
