### ISSUE TITLE
Create insight feature not working inside Notebook context

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9964]
1. Connect to a SQL Server instance
2. Open a new notebook and use SQL Kernel
3. Add a code cell and run a select statement
4. In the results area, click the 'Show chart' button
5. Click the 'Create insight' button
<img width="974" alt="Screen Shot 2020-04-14 at 10 40 53 AM" src="https://user-images.githubusercontent.com/13777222/79256547-0e862a80-7e3d-11ea-8d67-3a36990c7027.png">

i am getting the following error:
<img width="461" alt="Screen Shot 2020-04-14 at 10 45 49 AM" src="https://user-images.githubusercontent.com/13777222/79256687-48efc780-7e3d-11ea-9dfd-e83082de2a44.png">

**Comment by chlafreniere** [comment]
@corivera can you take a quick look at this and see if we can fix for April? If it's not a quick fix, we can punt to another month, since we shipped this experience in March as well.

**Comment by corivera** [comment]
I don't think it was an easy thing to do, from what I remember. I'll take a look, though.

**Comment by Charles-Gagnon** [comment]
If it isn't we should at least remove the button from the Notebook editor view

**Comment by corivera** [comment]
Looks like the insight action references the .sql file directly as part of the InsightsConfig. https://github.com/microsoft/azuredatastudio/blob/master/src/sql/workbench/contrib/charts/browser/actions.ts#L66

I'll remove the insight action from the notebook charts for now.

**Comment by chlafreniere** [comment]
Reopened it for ASK mode consideration.
