### ISSUE TITLE
query result table's side buttons need more spacing

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9965]
left side: 1.16.1 stable build
right side: 1.17 insider build
as you can see, there is a change in the spacing between the buttons.

<img width="97" alt="Screen Shot 2020-04-14 at 10 53 54 AM" src="https://user-images.githubusercontent.com/13777222/79257333-55c0eb00-7e3e-11ea-893c-7f4ad2fd9221.png">

**Comment by kburtram** [comment]
@cssuh if you have a chance could you please take a look at this issue?
