### ISSUE TITLE
Edit Data is not utilizing all the available space of the editor

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9967]
- Azure Data Studio Version:
today's insider build.

Steps to Reproduce:
1. find a table with maybe more than 10 columns
2. choose Edit data on the table

the edit data area is not utilizing all the spaces of the editor window.
<img width="1219" alt="Screen Shot 2020-04-15 at 3 08 48 PM" src="https://user-images.githubusercontent.com/13777222/79393863-0c9a9500-7f2b-11ea-8562-a5027a89ca28.png">

**Comment by alanrenmsft** [comment]
@smartguest Please bring this to Ken and Karl's attention, this should be in the April release.

**Comment by kburtram** [comment]
Fix is merged into release branch now.
