### ISSUE TITLE
Troubleshoot BDC - Missing file error

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9970]
I am using today's insider build.

Repro steps:
1. connect to a BDC controller
1. open the bdc dashboard
1. click the Troubleshoot button

i am getting the following error:

<img width="458" alt="Screen Shot 2020-04-14 at 11 50 31 AM" src="https://user-images.githubusercontent.com/13777222/79262678-89a00e80-7e46-11ea-9cdd-dfef30afef5d.png">

**Comment by MaddyDev** [comment]
Should be fixed with the below PR: https://mssqltools.visualstudio.com/_git/SqlOpsStudioExtensions/pullrequest/1093?_a=overview
Will validate on tomorrow's insiders and close this.

**Comment by MaddyDev** [comment]
Validated on the latest insiders, this is fixed.

**Comment by alanrenmsft** [comment]
@chlafreniere and @MaddyDev, we need to get this into the April release, right? if so, please reopen it and ask for approval

**Comment by MaddyDev** [comment]
The change is not on ADS side, we updated the books on sqlops to have the correct toc and got the PR in. ADS already has the correct version to pull the latest tsg book.

**Comment by alanrenmsft** [comment]
@MaddyDev thanks for clarification, yeah, i thought you need to bump the version from ads side :)
