### ISSUE TITLE
dashboard doesn't properly handle the extra long tab name and large number of tabs

### ISSUE THREAD

**Issue by alanrenmsft** [microsoft/azuredatastudio#9975]
1. extra long tab name should be truncated 
2. scrollbar should be visible when there are too many tabs to fit in the view port.

<img width="706" alt="Screen Shot 2020-04-14 at 3 25 30 PM" src="https://user-images.githubusercontent.com/13777222/79280042-3a68d680-7e64-11ea-918e-b151a9e2f5c5.png">

**Comment by alanrenmsft** [comment]
fixed by PR: #9937

**Comment by kburtram** [comment]
@alanrenmsft let's please leave the issue open until it gets ported to the April release branch.  It looks like we should take this one.
