### ISSUE TITLE
Intellisense not working when connecting from an already open tab

### ISSUE THREAD

**Issue by LucasWBritz** [microsoft/azuredatastudio#9987]
- Azure Data Studio Version:

Version: 1.16.1 (user setup)
Commit: 16801c522df68e63218b39ccb5b4a7431f9bf667
Date: 2020-03-23T22:08:06.892Z
VS Code: 1.42.0
Electron: 7.1.11
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18362

Steps to Reproduce:

1.
Hey guys! I'm able to reproduce this by just clicking in the "Connect" button on an already open tab.
Then switching from 'master' to my database. 
Intellisense does not show table names and columns anymore. 

![query](https://user-images.githubusercontent.com/24421665/79363212-03ef9200-7f1e-11ea-88d1-108905e5f001.JPG)

Note: I can make them work again if I go to my database, then, right click and "New Query".
Note2: I'm connected to an azure sql server database.

**Comment by kburtram** [comment]
I haven't been able to repro this bug with the provided steps.  Though we do have several other similar intellisense bugs we are still investigating.  when a connected editor is reconnected the intellisense cache will be rebuilt, so perhaps your observing the delay while the cache is being created or the cache rebuild failed for some reason.  We'll try to make these tasks/errors more transparent in the logs to aid with diagnosis.
