### ISSUE TITLE
ADS pops-up Firewall rule dialog when adding Azure account

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9996]
- Azure Data Studio Version: `release/1.17`

Steps to Reproduce:

1. Add a Azure Account

Expected: No OS pop-ups

Actual: Windows asks for Firewall permissions.

![image](https://user-images.githubusercontent.com/599935/79384174-3fd52800-7f1b-11ea-85cc-df99bdc49a1e.png)

**Comment by kburtram** [comment]
@aaomidi could you please take a look at this?  I don't recall seeing this before and assume it's related to the localhost redirect.  Perhaps we're opening an externally visible port vs. on the loopback IP?  If we're using loopback (non-externally visible port) we should see this OS pop-up I think.

**Comment by aaomidi** [comment]
@kburtram this was a mistake on my part, should be fixed now.

**Comment by kburtram** [comment]
Fix is merged into release branch.
