### ISSUE TITLE
April 2020 Endgame

### ISSUE THREAD

**Issue by kburtram** [microsoft/azuredatastudio#9998]
# April 2020 - Release Endgame

Branch: https://github.com/microsoft/azuredatastudio/tree/release/1.17

## Testing Links:

- [Windows User EXE][win-user]
- [Windows System EXE][win-system]
- [Windows ZIP][win-zip]
- [MacOS Zip][osx-zip]
- [Linux tar.gz][linux-zip]
- [Linux rpm][linux-rpm]
- [Linux deb][linux-deb]

## Extensions Testing

Install the latest build of ADS from the link above.

#### VSIX Files

Extension | Changed in this Release?
-- | --
Admin Pack |  No
Admin Tool Extension for Windows | No
Agent | Yes (ae131313708c4f412f522500fee034a6c266f36e)
CMS  | No
Dacpac | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/dacpac/dacpac-1.4.0.vsix) (ae131313708c4f412f522500fee034a6c266f36e)
Import | No
Profiler | No
Schema Compare | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/schema-compare/schema-compare-1.4.0.vsix) (ae131313708c4f412f522500fee034a6c266f36e)
PostgreSQL | No
Query History | No
Data Virtualization | [Yes](https://sqlopsextensions.blob.core.windows.net/extensions/datavirtualization/datavirtualization-1.4.0.vsix)

## Scenario Sign Off

- [x] Edit Data @smartguest 
- [x] ADS Shell @kburtram 
- [x] Query Editor @anthonydresser 
- [x] Notebooks  @chlafreniere 
- [x] Livesite tooling @qifahs, @MsSQLGirl      
- [x] Data Virtualization @Charles-Gagnon   
- [x] Acquisition @kburtram 
- [x] Connection @Charles-Gagnon 
- [x] Language Service @Charles-Gagnon 
- [x] SSMS Integration @Charles-Gagnon 
- [x] Query History @Charles-Gagnon 
- [x] Big Data Cluster @Charles-Gagnon 
- [x] Spark Job Submission @chlafreniere 
- [x] SQL Agent @abist 
- [x] Azure Integration @aaomidi
- [x] Resource Deployment @alanrenmsft 
- [x] Books @MaddyDev 
- [x] Charting and Insights @alanrenmsft 
- [x] Dashboard @alanrenmsft  
- [x] Backup/Restore @udeeshagautam 
- [x] File Import @kenvanhyning / @aaomidi
- [x] DacFx Deployment @kisantia 
- [x] SQL Profiler @alanrenmsft 
- [x] CMS @abist 
- [x] Extension Manager @alanrenmsft 
- [x] Schema Compare @kisantia / @udeeshagautam 
- [x] Data Explorer @abist 
 
## Partner Signoffs
- [ ] PGSQL @akamath46297 
- [ ] SQL On Demand @BranislavGrbicMDCS 

[win-user]: https://go.microsoft.com/fwlink/?linkid=2127522
[win-system]: https://go.microsoft.com/fwlink/?linkid=2127432
[win-zip]: https://go.microsoft.com/fwlink/?linkid=2127716
[osx-zip]: https://go.microsoft.com/fwlink/?linkid=2127431
[linux-zip]: https://go.microsoft.com/fwlink/?linkid=2127523
[linux-rpm]: https://go.microsoft.com/fwlink/?linkid=2127433
[linux-deb]: https://go.microsoft.com/fwlink/?linkid=2127524

**Comment by udeeshagautam** [comment]
Added SC/Dacpac links

**Comment by anthonydresser** [comment]
I wasn't adding links to the latest extensions because we should be using the marketplace to download the extensions, not side loading them.

**Comment by Charles-Gagnon** [comment]
Good point - we should check in extensionGallery-test and then have people be updating that along with the other extensionGallery files when they're pushing updates for a release

**Comment by alanrenmsft** [comment]
> Good point - we should check in extensionGallery-test and then have people be updating that along with the other extensionGallery files when they're pushing updates for a release

This is more of an internal thing, by checking it in, we are adding one more file to be updated, I'd recommend to make it part of the release DRI's job, copy extensionGallery.json and rename it to extensionGallery-test.json, this step can be automated, so almost no additional work for the release DRI.

**Comment by Charles-Gagnon** [comment]
@anthonydresser It looks like you (or someone) has been updating the extensionGallery-test on the storage account. Is that accurate? 

@alanrenmsft Yeah realized that after I typed it. Let's just make sure we get that documented.

**Comment by Charles-Gagnon** [comment]
Hmm, we could even have it as part of the RC publishing pipeline (or maybe it already is @anthonydresser ?)

**Comment by anthonydresser** [comment]
It's not automatic, but yes I have been updating the test json with what is currently checked in as the extensiongallery.json
